### PR TITLE
Fix quirks for PrettyCompactMonoBlock

### LINKED ISSUE #7746: PrettyCompactMonoBlock is not listed in system.formats so no autocompletion for it
```
SELECT *
FROM system.formats
WHERE name LIKE '%Mono%'

Ok.

0 rows in set. Elapsed: 0.001 sec. 


SELECT *
FROM numbers(2)
FORMAT PrettyCompactMonoBlock

┌─number─┐
│      0 │
│      1 │
└────────┘

2 rows in set. Elapsed: 0.001 sec. 
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix PrettyCompactMonoBlock for clickhouse-local. Fix extremes/totals with PrettyCompactMonoBlock. Fixes #7746

- Fix PrettyCompactMonoBlock for clickhouse-local (broken in 20.3+, fails with an error `Unknown format PrettyCompactMonoBlock`, after #6239)
- Fix extremes/totals with PrettyCompactMonoBlock (even before 20.3 breakage they were simply ignored)

Cc: @KochetovNicolai 

Fixes: #7746

### CODE REVIEW

**Comment by azat** [comment]
Although not sure about bug fix label, but too late anyway

**Review by KochetovNicolai — APPROVED** [review]
LGTM

File: src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp [hunk 1]
```diff
@@ -60,6 +60,8 @@ void PrettyCompactBlockOutputFormat::writeSuffixIfNot()
         writeChunk(mono_chunk, PortKind::Main);
         mono_chunk.clear();
     }
+
+    PrettyBlockOutputFormat::writeSuffixIfNot();
```
Comment (azat) [inline src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp:64]: Thanks!
