### PR TITLE
Exclude partition key columns from SummingMergeTree 

### LINKED ISSUE #7867: Discrepancy. SummingMergeTree sums partition key but does't update min_max
It was kinda unexpected that SummingMergeTree sums partition key columns.

Probably CH have to forbid such schema on create table and raise an error.
Or exclude partition key columns from sum list.
```
CREATE TABLE tt
( a   Int64, d   Int64, val Int64 ) 
ENGINE = SummingMergeTree PARTITION BY (a) ORDER BY (d);

insert into tt select number%13, number%17, 1 from numbers(1000000);

optimize table tt final;

select a, count() from tt group by a;
┌─────a─┬─count()─┐
│     0 │      17 │
│ 40725 │      15 │
│ 18096 │       2 │
│ 45240 │       2 │
│ 13572 │       2 │
│ 49775 │      15 │
│ 54288 │       2 │
│ 31668 │       2 │
│ 40716 │       2 │
│  4524 │       2 │
│ 36192 │       2 │
│ 18100 │      15 │
│ 13575 │      15 │
│  4525 │      15 │
│ 22625 │      15 │
│ 45250 │      15 │
│  9050 │      15 │
│ 27150 │      15 │
│ 54300 │      15 │
│ 27144 │       2 │
│ 49764 │       2 │
│ 36200 │      15 │
│ 22620 │       2 │
│  9048 │       2 │
│ 31675 │      15 │
└───────┴─────────┘


select * from tt where a>13;
Ok.

0 rows in set. Elapsed: 0.001 sec.
```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed the behaviour when `SummingMergeTree` engine sums up columns from partition key. Added an exception in case of explicit definition of columns to sum which intersects with partition key columns. This fixes #7867

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp [hunk 1]
```diff
@@ -1180,7 +1182,7 @@ Pipes MergeTreeDataSelectExecutor::spreadMarkRangesAmongStreamsFinal(
 
             case MergeTreeData::MergingParams::Summing:
                 return std::make_shared<SummingSortedTransform>(header, pipes.size(),
-                           sort_description, data.merging_params.columns_to_sum, max_block_size);
+                           sort_description, data.merging_params.columns_to_sum, partition_key_columns, max_block_size);
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:1185]: We also need a test with SELECT FINAL?
