### PR TITLE
Fix #5439 bug PrettySpace format

### LINKED ISSUE #5439: PrettySpace format: infinite loop printing whitespaces
```
create table test_pretty_space_bug(property String,value String) Engine=TinyLog;

insert into test_pretty_space_bug values ('geoplugin_request','3.3.3.3'),('geoplugin_status','200'),('geoplugin_delay','1ms'),('geoplugin_credit','Some of the returned data includes GeoLite data created by MaxMind available from <a href=\'http://www.maxmind.com\'>http://www.maxmind.com</a>.'),('geoplugin_city','Seattle'),('geoplugin_region','Washington'),('geoplugin_regionCode','WA'),('geoplugin_regionName','Washington'),('geoplugin_areaCode',''),('geoplugin_dmaCode','819'),('geoplugin_countryCode','US'),('geoplugin_countryName','United States'),('geoplugin_inEU','0'),('geoplugin_euVATrate',''),('geoplugin_continentCode','NA'),('geoplugin_continentName','North America'),('geoplugin_latitude','47.6339'),('geoplugin_longitude','-122.3476'),('geoplugin_locationAccuracyRadius','1000'),('geoplugin_timezone','America/Los_Angeles'),('geoplugin_currencyCode','USD'),('geoplugin_currencySymbol','&#36;'),('geoplugin_currencySymbol_UTF8','$'),('geoplugin_currencyConverter','1');

select * from test_pretty_space_bug FORMAT PrettySpace;
```

### PR DESCRIPTION
**Pull request by stavrolia**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.
- Bug Fix

Short description (up to few sentences):
Fix infinite loop in pretty space format

### CODE REVIEW

File: dbms/src/Formats/PrettySpaceBlockOutputStream.cpp [hunk 1]
```diff
@@ -26,12 +25,6 @@ void PrettySpaceBlockOutputStream::write(const Block & block)
     Widths name_widths;
     calculateWidths(block, widths, max_widths, name_widths, format_settings);
 
-    /// Do not align on too long values.
```
Comment (stavrolia) [inline dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: This block affects only appearance, but it breaks the invariant "max_width[i] >= widths[i][j] for each j for each i" that leads to infinite loop at https://github.com/yandex/ClickHouse/blob/master/dbms/src/Formats/PrettyBlockOutputStream.cpp#L202

Subtracting unsigned integers (size_t) is problematic because it can easily lead to overflow (but here it makes this bug visible).

Comment (alexey-milovidov) [reply dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: But I want to save this behaviour.

File: dbms/src/Formats/PrettySpaceBlockOutputStream.cpp [hunk 2]
```diff
@@ -64,14 +57,12 @@ void PrettySpaceBlockOutputStream::write(const Block & block)
         }
     }
     writeCString("\n\n", ostr);
-
```
Comment (alexey-milovidov) [inline dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: Irrelevant change.

File: dbms/src/Formats/PrettySpaceBlockOutputStream.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: It is really important.

Comment (stavrolia) [reply dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: Could you explain in more details the behaviour?

Comment (stavrolia) [reply dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: Or I can just change result cycling loop from "a < b - c" to "a + c < b" here https://github.com/yandex/ClickHouse/pull/5560#discussion_r291810162 . It would save the behavior without infinite loop. Is it good in your opinion?

Comment (alexey-milovidov) [reply dbms/src/Formats/PrettySpaceBlockOutputStream.cpp]: As we have this logic:

https://github.com/yandex/ClickHouse/blob/master/dbms/src/Formats/PrettyBlockOutputStream.cpp#L64

the code you deleted is really obsolete.
