### PR TITLE
Use global settings for query to VIEW

### LINKED ISSUE #20551: select with join_use_nulls=1 breaks some views created under join_use_nulls=0
Reproduction example:

```(sql)
SET join_use_nulls = 0;

create or replace view
  some_test_view
as
select *
from
  (
    select
      arrayJoin([1, 2]) as a,
      arrayJoin([11, 12]) as b
  ) as t1
  full join
  (
    select
      arrayJoin([2, 3]) as a,
      arrayJoin([22, 23]) as c
  ) as t2
  using a
order by a
```

In `describe table some_test_view` the resulting columns are non-nullable, as expected.

However, changing the setting and selecting from the view:

```(sql)
SET join_use_nulls = 1;
select * from some_test_view
```

Results in an error: `Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column c to destination column c: while executing 'FUNCTION CAST(c :: 2, UInt8 :: 5) -> CAST(c, UInt8) UInt8 : 4' (version 21.2.3.15 (official build))`

There's no clearly-good solution to this problem;
one of the suggestions is to add the setting to the view schema, e.g.:

```(sql)
SET join_use_nulls = 0;

create or replace view
  some_test_view
as
select *
from
  (
    select
      arrayJoin([1, 2]) as a,
      arrayJoin([11, 12]) as b
  ) as t1
  full join
  (
    select
      arrayJoin([2, 3]) as a,
      arrayJoin([22, 23]) as c
  ) as t2
  using a
order by a
settings join_use_nulls = 0  -- prevent the join behavior inside the view from changing
```

which could be done implicitly by CH to improve the user experience.

Side note: `… settings join_use_nulls = …` seems to be poorly documented, only appearing in a few examples without any explanation.

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Use global settings for query to `VIEW`.  Fixed the behavior when queries to `VIEW` use local settings, that leads to errors if setting on `CREATE VIEW` and `SELECT` were different. As for now, `VIEW` won't use these modified settings, but you can still pass additional settings in `SETTINGS` section of `CREATE VIEW` query. Close #20551

### CODE REVIEW

File: src/Storages/StorageView.cpp [hunk 1]
```diff
@@ -33,8 +33,10 @@ namespace ErrorCodes
 StorageView::StorageView(
     const StorageID & table_id_,
     const ASTCreateQuery & query,
-    const ColumnsDescription & columns_)
+    const ColumnsDescription & columns_,
+    const Settings & settings)
     : IStorage(table_id_)
+    , settings_changes{{"join_use_nulls", Field(settings.join_use_nulls)}}
```
Comment (nikitamikhaylov) [inline src/Storages/StorageView.cpp:39]: Maybe better to save all changed settings, not only join_use_nulls?

Comment (vdimir) [reply src/Storages/StorageView.cpp]: Changed to `settings.changes()`, but I'm not sure that it won't have any unexpectable side-effects, can we imagine some setting shouldn't be saved?

Comment (hhell) [reply src/Storages/StorageView.cpp]: > unexpectable side-effects

`join_use_nulls` case is special here because it can break in unclear ways.

Other settings should probalby not be saved, unless there are known similar problems.

And I'm not sure whether it should be possible to do `select ... settings http_send_timeout = ...`, especially in a subquery or view.

**Comment by vdimir** [comment]
@mergifyio update

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Testflows...
