### PR TITLE
Functions `searchAny|All`: match every for empty needles

### LINKED ISSUE #86300: `searchAll` returns false when needles is an empty array
### Company or project name

_No response_

### Describe what's wrong

[`searchAll`](https://clickhouse.com/docs/sql-reference/functions/string-search-functions#searchall) requires that all needles are matched.

However when providing it with 0 needles (an empty array), it is always **false** rather than **true**.
Logically, this is incorrect and causes problems when composing conditions in the WHERE clause.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
CREATE OR REPLACE TABLE search_all_empty
(
  address_line String,
  INDEX text_address(address_line) TYPE text(tokenizer = 'default')
) ENGINE=MergeTree
ORDER BY (address_line)
SETTINGS allow_experimental_full_text_index = true;

INSERT INTO search_all_empty
VALUES ('hellostreet amsterdam'), ('foobarlane amsterdam');

SELECT *
FROM search_all_empty
WHERE searchAll(address_line, [])
SETTINGS allow_experimental_full_text_index=true;
```

https://fiddle.clickhouse.com/5d89cf26-5a93-446e-963e-1f6dfdd2ad0f

In this example, I would expect `WHERE searchAll(address_line, [])` to always be true and return 2 rows.
Instead this returns 0 rows.

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

My use-case here is to split an input search:
- Using `searchAll` for all tokens *except the last one*.
- Using `startsWith` for the last token.

The idea is we're assuming the user is still typing the last token.

Currently that uses a view similar to this.

```sql
CREATE OR REPLACE VIEW find_address
AS WITH
  tokens(lowerUTF8({search:String})) as allTokens,
  arrayElement(allTokens, -1) as lastToken,
  arrayPopBack(allTokens) as fullTokens
SELECT *
FROM search_all_empty
WHERE searchAll(address_line, fullTokens)
  AND startsWith(address_line, lastToken)
SETTINGS allow_experimental_full_text_index=true;
```

Where having one of both types (fullTokens and lastToken) works fine.
```sql
SELECT *
FROM find_address(search='amsterdam hello');
```

But an empty array of fullTokens fails to match.
```sql
SELECT *
FROM find_address(search='amster');
```

### PR DESCRIPTION
**Pull request by ahmadov**
Fixes #86300

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Functions `searchAny` and `searchAll` when called with empty needles now return `true` (aka. "matches everything"). Previously, they returned `false`. (issue #86300)

### CODE REVIEW

**Review by rschu1ze — APPROVED** [review]

File: src/Functions/searchAnyAll.cpp [hunk 1]
```diff
@@ -177,6 +177,13 @@ void execute(
 {
     col_result.resize(input_rows_count);
 
+    if (needles.empty())
```
Comment (rschu1ze) [inline src/Functions/searchAnyAll.cpp]: Side note: L. 217-222 are superfluous (l. 97 covers it).

Comment (rschu1ze) [inline src/Functions/searchAnyAll.cpp]: Let's add a comment: `/// No needles mean we don't filter and all rows pass`

File: src/Functions/searchAnyAll.cpp [hunk 2]
```diff
@@ -177,6 +177,13 @@ void execute(
...
+    {
```
Comment (rschu1ze) [inline src/Functions/searchAnyAll.cpp]: Could you check if we can remove l. 180 - 185 and instead twist l. 117 - 132 a bit like this:

```cpp
std::vector<std::string_view> tokens;
for (size_t i = 0; i < input_rows_count; ++i)
{
    const std::string_view value = col_input.getDataAt(i).toView();
    col_result[i] = true;

    tokens = token_extractor->getTokensView(value.data(), value.size());
    for (const auto & token : tokens)
    {
        if (!needles.contains(token))
        {
            col_result[i] = false;
            break;
        }
    }
}
```

(same for `executeSearchAll`)

(please double check the code ^^, I'm writing this from a noisy room)

File: src/Storages/MergeTree/MergeTreeIndexGin.cpp [hunk 3]
```diff
@@ -203,12 +203,20 @@ bool MergeTreeIndexConditionGin::mayBeTrueOnGranuleInPart(MergeTreeIndexGranuleP
             chassert(element.query_strings_for_set.size() == 1);
             const std::vector<GinQueryString> & query_strings = element.query_strings_for_set.front();
             bool exists_in_gin_filter = false;
-            for (const GinQueryString & query_string : query_strings)
+            if (query_strings.empty())
```
Comment (rschu1ze) [inline src/Storages/MergeTree/MergeTreeIndexGin.cpp]: Could this simply be:

```cpp
bool exists_in_gin_filter = true;
for (const GinQueryString & query_string : query_strings)
{
    if (!granule->gin_filter.contains(query_string, postings_lists_cache_for_store, GinSearchMode::Any))
    {
        exists_in_gin_filter = false;
        break;
    }
}
```

(again, better double-check ... I'm in a noisy room and it is hard to think straight :-) )

File: src/Functions/searchAnyAll.cpp (hunk 2 above)
Comment (ahmadov) [reply src/Functions/searchAnyAll.cpp]: actually it's tricky for `executeSearcAny`:
```
if (!needles.contains(token))
        {
            col_result[i] = false;
            break;
        }
```
we should set `col_result[i] = false` if none (not any) matches and this makes the implementation bit complex. I moved it to another place.

File: src/Functions/searchAnyAll.cpp [hunk 4]
```diff
@@ -214,10 +212,18 @@ ColumnPtr FunctionSearchImpl<SearchTraits>::executeImpl(
...
+    col_result->getData().resize(input_rows_count);
+    if (needles->empty())
+    {
+        /// No needles mean we don't filter and all rows pass
+        for (size_t i = 0; i < input_rows_count; ++i)
+            col_result->getData()[i] = true;
+    }
+    else
+    {
+        const auto * column_string = checkAndGetColumn<ColumnString>(col_input.get());
```
Comment (rschu1ze) [inline src/Functions/searchAnyAll.cpp]: Now that path `else if (const auto * column_fixed_string = checkAndGetColumn<ColumnFixedString>(col_input.get()))` was removed, does `searchAny/All` still support `FixedString` haystacks?

**Review by rschu1ze — APPROVED** [review]

File: src/Functions/searchAnyAll.cpp (hunk 4 above)
Comment (ahmadov) [reply src/Functions/searchAnyAll.cpp]: yes, I pushed the missing tests.

Comment (rschu1ze) [reply src/Functions/searchAnyAll.cpp]: The new tests are for FixedString needles, e.g. `WHERE searchAny(message, [toFixedString('abc', 3)])` but `col_input` refers to the haystack column. Will FixedString inputs/haystacks still work?

Comment (ahmadov) [reply src/Functions/searchAnyAll.cpp]: ah that was a wrong test. I added it back and added a test for `FixedString` column

File: tests/queries/0_stateless/02346_text_index_function_search.sql [hunk 5]
```diff
@@ -86,6 +103,14 @@ SELECT groupArray(id) FROM tab WHERE searchAll(message, ['abc', 'bar']);
 SELECT groupArray(id) FROM tab WHERE searchAll(message, ['foo', 'bar']);
 SELECT groupArray(id) FROM tab WHERE searchAll(message, ['abc', 'fo']);
 
+--- Test for FixedString
+SELECT groupArray(id) FROM tab WHERE searchAny(message, [toFixedString('abc', 3)]);
+SELECT groupArray(id) FROM tab WHERE searchAll(message, [toFixedString('abc', 3)]);
+
+--- Test for GitHub issue #86300
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02346_text_index_function_search.sql]: Tests for text index bugs live in their own files, could you move l. 111-112 to 02346_text_index_bug86300.sql please? (the test can create a small example table)

File: tests/queries/0_stateless/02346_text_index_function_search.sql [hunk 6]
```diff
@@ -86,6 +103,14 @@ SELECT groupArray(id) FROM tab WHERE searchAll(message, ['abc', 'bar']);
 SELECT groupArray(id) FROM tab WHERE searchAll(message, ['foo', 'bar']);
 SELECT groupArray(id) FROM tab WHERE searchAll(message, ['abc', 'fo']);
 
+--- Test for FixedString
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02346_text_index_function_search.sql]:
```
-- Test for FixedString needles
-- Not a systematic test, just to see that FixedString needles work in principle
```

File: tests/queries/0_stateless/02346_text_index_function_search.sql [hunk 7]
```diff
@@ -47,6 +47,23 @@ SELECT id FROM tab WHERE searchAny(message, ['a', 'b', 'c', 'd', 'e', 'f', 'g',
 
 DROP TABLE tab;
 
+SELECT 'FixedString column';
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02346_text_index_function_search.sql]: Minor: `FixedString input columns`
