### PR TITLE
Fix create statement when using default minmax indicies

### LINKED ISSUE #87286: CREATE STATEMENT altered after ALTER when using  add_minmax_index_for_xxx flags
### Company or project name

_No response_

### Describe the unexpected behaviour

When minmax indices are added using the flags `add_minmax_index_for_numeric_columns` or `add_minmax_index_for_string_columns`, they are created implicitly and not added to CREATE statement. 

But when ALTER is used for the table, the implicitly created indices appear in the CREATE statement

### Which ClickHouse versions are affected?

25.9

### How to reproduce

https://fiddle.clickhouse.com/6fa176f1-862e-4bc9-a884-3a995729674c

### Expected behavior

The indices should not appear in the CREATE statement

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Multiple fixes around implicit indices. The schema shown or stored (keeper metadata) won't include implicit indices, such as the ones created by settings `add_minmax_index_for_numeric_columns` or `add_minmax_index_for_string_columns`. This might cause metadata errors when a ReplicatedMergeTree table is created or updated in a newer version, while there is a replica in an older release. For those cases send DDLs to the old replica until the cluster is upgraded completely. 

This PR:
* Extends and slightly simplifies https://github.com/ClickHouse/ClickHouse/pull/87723.
* Fixes implicit indices when the column type changes (related to https://github.com/ClickHouse/ClickHouse/pull/89335)
* Fixes implicit indices with ephemeral or alias columns
* Fixes ReplicatedMergeTree metadata sharing with implicit indices, so it does not include them (as they are not included in disk metadata). This is necessary to treat them properly as implicitly. It creates a minor incompatibility between versions.

Closes https://github.com/ClickHouse/ClickHouse/issues/87286.
Closes https://github.com/ClickHouse/ClickHouse/pull/87723

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/MergeTree/ReplicatedMergeTreeTableMetadata.cpp [hunk 1]
```diff
@@ -369,11 +370,17 @@ bool ReplicatedMergeTreeTableMetadata::checkEquals(
...
     if (skip_indices != parsed_zk_skip_indices)
     {
-        handleTableMetadataMismatch(table_name_for_error_message, "skip indexes", from_zk.skip_indices, parsed_zk_skip_indices, skip_indices, strict_check, logger);
-        is_equal = false;
+        String all_parsed_zk_skip_indices = IndicesDescription::parse(from_zk.skip_indices, columns, context).allToString();
+        // Backward compatibility: older replicas included implicit indices in metadata,
+        // while newer ones exclude them. This check allows comparison between both formats.
+        if (skip_indices != all_parsed_zk_skip_indices)
+        {
+            handleTableMetadataMismatch(table_name_for_error_message, "skip indexes", from_zk.skip_indices, parsed_zk_skip_indices, skip_indices, strict_check, logger);
```
Comment (SmitaRKulkarni) [inline src/Storages/MergeTree/ReplicatedMergeTreeTableMetadata.cpp:381]: @Algunenano : to handleTableMetadataMismatch function we are passing `parsed_zk_skip_indices` is that intentional ? Shouldn't it be `all_parsed_zk_skip_indices` or I am missing something ?

Comment (Algunenano) [reply src/Storages/MergeTree/ReplicatedMergeTreeTableMetadata.cpp:381]: It's just for logging or throwing an exception. I prefer passing the new format without the explicit indices.

**Review by SmitaRKulkarni — APPROVED** [review]
Rest all LGTM
