### PR TITLE
Fix text_index optimization on multiple passes.

### LINKED ISSUE #101913: full-text index direct-read throws error when multiple filters used on a merged, distributed table
### Company or project name

groundcover

### Describe what's wrong

ran into this error when having multiple filter on a table with text index, when querying it via a merged table over a distributed table:
```

Code: 49. DB::Exception. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000017814baa
1. DB::Exception::Exception(String const&, int, String, bool) @ 0x00000000164d9e8e
2. DB::readException(DB::ReadBuffer&, String const&, bool) @ 0x0000000017967b13
3. DB::Connection::receiveException() const @ 0x000000001e371f22
4. DB::Connection::receivePacket() @ 0x000000001e37c8ed
5. DB::ClientBase::receiveAndProcessPacket(boost::intrusive_ptr<DB::IAST>, bool) @ 0x000000001e331f3d
6. DB::ClientBase::receiveResult(boost::intrusive_ptr<DB::IAST>, int, bool) @ 0x000000001e3313df
7. DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, boost::intrusive_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001e32de1a
8. DB::ClientBase::executeMultiQuery(String const&) @ 0x000000001e33ab79
9. DB::ClientBase::processQueryText(String const&) @ 0x000000001e33ccf9
10. DB::ClientBase::runNonInteractive() @ 0x000000001e34812b
11. DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000017aead6f
12. Poco::Util::Application::run() @ 0x0000000023c94e71
13. mainEntryClickHouseClient(int, char**) @ 0x0000000017afadd2
14. main @ 0x000000000fad2baa
15. __pow_finite @ 0x0000000000029d90
16. __remainder_finite @ 0x0000000000029e40
17. _start @ 0x000000000960f3ae

Received exception from server (version 26.3.3):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Column __text_index_idx_text_like_5d15a905cd42cea2d53b727e9e004eef already added for reading. (LOGICAL_ERROR)
```

when disabling the direct read from the index, the query succeeds. also when querying the table/dist table directly.

I found this PR that resolved a similar bug: https://github.com/ClickHouse/ClickHouse/pull/93516

attaching a fiddle link reproducing on latest version (26.3.3)
https://fiddle.clickhouse.com/2a7d1893-84cb-4854-878c-5f0608603438

thank you!

### Does it reproduce on the most recent release?

Yes

### How to reproduce

https://fiddle.clickhouse.com/2a7d1893-84cb-4854-878c-5f0608603438

### Expected behavior

query should not fail, return filtered rows correctly

### Error message and/or stacktrace

```

Code: 49. DB::Exception. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000017814baa
1. DB::Exception::Exception(String const&, int, String, bool) @ 0x00000000164d9e8e
2. DB::readException(DB::ReadBuffer&, String const&, bool) @ 0x0000000017967b13
3. DB::Connection::receiveException() const @ 0x000000001e371f22
4. DB::Connection::receivePacket() @ 0x000000001e37c8ed
5. DB::ClientBase::receiveAndProcessPacket(boost::intrusive_ptr<DB::IAST>, bool) @ 0x000000001e331f3d
6. DB::ClientBase::receiveResult(boost::intrusive_ptr<DB::IAST>, int, bool) @ 0x000000001e3313df
7. DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, boost::intrusive_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001e32de1a
8. DB::ClientBase::executeMultiQuery(String const&) @ 0x000000001e33ab79
9. DB::ClientBase::processQueryText(String const&) @ 0x000000001e33ccf9
10. DB::ClientBase::runNonInteractive() @ 0x000000001e34812b
11. DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000017aead6f
12. Poco::Util::Application::run() @ 0x0000000023c94e71
13. mainEntryClickHouseClient(int, char**) @ 0x0000000017afadd2
14. main @ 0x000000000fad2baa
15. __pow_finite @ 0x0000000000029d90
16. __remainder_finite @ 0x0000000000029e40
17. _start @ 0x000000000960f3ae

Received exception from server (version 26.3.3):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Column __text_index_idx_text_like_5d15a905cd42cea2d53b727e9e004eef already added for reading. (LOGICAL_ERROR)
(query: SELECT str FROM tab_merged WHERE 
hasAllTokens(str, ['par'])
AND str LIKE concat('%',lower('(par)'),'%')
LIMIT 10
SETTINGS query_plan_direct_read_from_text_index=1;)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ergus**
Pre-populate the cache with any text-index virtual column inputs that are already present in this DAG from a previous optimization pass.

Fix: #101913

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fixes an exception when querying Merge or Distributed tables with a full-text index and combined filter conditions that mix `has*Tokens` with LIKE, while `query_plan_direct_read_from_text_index` is enabled.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.652`

### CODE REVIEW

File: tests/queries/0_stateless/02346_text_index_bug101913.sql [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+DROP TABLE IF EXISTS tab;
+DROP TABLE IF EXISTS tab_dist;
+DROP TABLE IF EXISTS tab_merged;
+
+CREATE TABLE tab
+(
+    `id` UInt64,
+    `str` String,
+    INDEX idx_text str TYPE text(tokenizer = splitByNonAlpha)
```
Comment (PedroTadim) [inline tests/queries/0_stateless/02346_text_index_bug101913.sql:13]: Does it make a difference to test with other tokenizers and functions that support the text index?

Comment (Ergus) [reply tests/queries/0_stateless/02346_text_index_bug101913.sql:13]: Likely not. Look that my explication [here](https://github.com/ClickHouse/ClickHouse/issues/101913#issuecomment-4198784580)

But it worth adding a test for `PREWHERE` just in case.

**Review by CurtizJ — APPROVED** [review]
