### PR TITLE
Fix flaky autocompletion test

### LINKED ISSUE #50626: 01676_clickhouse_client_autocomplete is flaky
```sql
SELECT
  check_name,
  test_name,
  toStartOfDay(check_start_time) as t,
  count() as runs,
  100 * (countIf(test_status != 'OK' AND test_status != 'SKIPPED') AS f) / runs as failure_percentage
FROM checks
WHERE
    test_name LIKE '01676_clickhouse_client_autocomplete%'
    AND pull_request_number = 0
    AND check_start_time > today() - interval 30 day
GROUP BY check_name, test_name, t
HAVING f > 0
ORDER by check_name, test_name, t
 ```

№ | check_name | test_name | t | runs | failure_percentage
-- | -- | -- | -- | -- | --
1 | Stateless tests (release, analyzer) | 01676_clickhouse_client_autocomplete | 2023-06-02 00:00:00 | 34 | 29.41176470588235
2 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-07 00:00:00 | 26 | 7.6923076923076925
3 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-09 00:00:00 | 17 | 17.647058823529413
4 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-12 00:00:00 | 31 | 3.225806451612903
5 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-15 00:00:00 | 13 | 7.6923076923076925
6 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-17 00:00:00 | 8 | 12.5
7 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-21 00:00:00 | 5 | 20
8 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-22 00:00:00 | 16 | 6.25
9 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-23 00:00:00 | 22 | 4.545454545454546
10 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-05-24 00:00:00 | 18 | 5.555555555555555
11 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-06-01 00:00:00 | 23 | 4.3478260869565215
12 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-06-02 00:00:00 | 34 | 11.764705882352942
13 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-06-04 00:00:00 | 8 | 12.5
14 | Stateless tests (ubsan) [2/2] | 01676_clickhouse_client_autocomplete | 2023-06-06 00:00:00 | 6 | 16.666666666666668

Sample run: https://s3.amazonaws.com/clickhouse-test-reports/50594/29e886fdf4e90a48b303e49f15c276e04f3cc7d2/stateless_tests__ubsan__[2_2].html

### PR DESCRIPTION
**Pull request by thevar1able**
Fixes: https://github.com/ClickHouse/ClickHouse/issues/50626

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 123d4cfe4bbd06fbfbdaf03d6572a3bbb282b603 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65246/123d4cfe4bbd06fbfbdaf03d6572a3bbb282b603/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Client/LocalConnection.cpp [hunk 1]
```diff
@@ -477,13 +477,25 @@ Packet LocalConnection::receivePacket()
...
+        ret = poll(0);
 
     if (!next_packet_type)
     {
-        packet.type = Protocol::Server::EndOfStream;
-        return packet;
+        if (state && !ret)
+        {
+            /// We should retry.
+            /// Let's send a dummy packet and hope for the best.
```
Comment (kssenii) [inline src/Client/LocalConnection.cpp:489]: May be just  a while cycle for poll to avoid dummy packet?

File: src/Client/LocalConnection.cpp [hunk 2]
```diff
@@ -356,7 +356,7 @@ bool LocalConnection::poll(size_t)
 
         try
         {
-            pollImpl();
+            while (pollImpl());
```
Comment (kssenii) [inline src/Client/LocalConnection.cpp:359]: Let's add logging about an intention to retry because of a failed timeout. Also we have timeout in pullBlock, because the assumption was that we might want to send progress/metrics in between poll attempts. Which is done in lines 344-355. So currently this while loop in this place makes timeout pointless, as we could just pass 0 instead of timeout - which will just block until block is ready or query finished - an the effect will be the same. So I'd suggest to include lines 344-355 inside the loop + logging about poll retry because of failed timeout as I mentioned before.

File: src/Client/LocalConnection.cpp [hunk 3]
```diff
@@ -356,7 +356,23 @@ bool LocalConnection::poll(size_t)
 
         try
         {
-            while (pollImpl());
+            while (pollImpl())
+            {
+                LOG_DEBUG(&Poco::Logger::get("LocalConnection"), "Executor timeout encountered");
```
Comment (kssenii) [inline src/Client/LocalConnection.cpp:361]:
```suggestion
                LOG_DEBUG(&Poco::Logger::get("LocalConnection"), "Executor timeout encountered, will retry");
```

File: src/Client/LocalConnection.cpp [hunk 4]
```diff
@@ -356,7 +356,23 @@ bool LocalConnection::poll(size_t)
...
+
+                if (send_progress && (state->after_send_progress.elapsedMicroseconds() >= query_context->getSettingsRef().interactive_delay))
```
Comment (kssenii) [inline src/Client/LocalConnection.cpp:363]: Would be good to unite the code in lines 344-355  into a separate method may be - to avoid copy pasted code, may be something like 
```
if (needSendProgressOrMetrics)
    return true;
```
where 
```
bool needSendProgressOrMetrics()
{
    if (send_progress && (state->after_send_progress.elapsedMicroseconds() >= query_context->getSettingsRef().interactive_delay))
    {
            state->after_send_progress.restart();
            next_packet_type = Protocol::Server::Progress;
            return true;
    }
    if (send_profile_events && (state->after_send_profile_events.elapsedMicroseconds() >= query_context->getSettingsRef().interactive_delay))
     {
            sendProfileEvents();
            return true;
    }
    return false;
}
```
Though this is just a suggestion, not necessary

**Review by kssenii — APPROVED** [review]
