### PR TITLE
Fix lazy execution of default argument in dictGetOrDefault for RangeHashedDictionary

### LINKED ISSUE #56661: runtime error: member call on null pointer of type 'DB::ColumnLowCardinality' SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/src/Functions/FunctionsConversion.h
https://s3.amazonaws.com/clickhouse-test-reports/56609/9c954046afb31527bd807b134e9592258f83d5a7/fuzzer_astfuzzerubsan/report.html

```
   #0 0x556a27d87927 in DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)::operator()(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) const build_docker/./src/Functions/FunctionsConversion.h:4243:55
    #1 0x556a27d869d3 in decltype(std::declval<DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)&>()(std::declval<std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&>(), std::declval<std::__1::shared_ptr<DB::IDataType const> const&>(), std::declval<DB::ColumnNullable const*>(), std::declval<unsigned long>())) std::__1::__invoke[abi:v15000]<DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long>(DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*&&, unsigned long&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #2 0x556a27d869d3 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__invoke_void_return_wrapper<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, false>::__call<DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long>(DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*&&, unsigned long&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
    #3 0x556a27d869d3 in std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::operator()[abi:v15000](std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*&&, unsigned long&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #4 0x556a27d869d3 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const::'lambda0'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>>(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #5 0x556a27a3b0ca in std::__1::__function::__policy_func<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::operator()[abi:v15000](std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*&&, unsigned long&&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #6 0x556a27a3b0ca in std::__1::function<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::operator()(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #7 0x556a27a3b0ca in DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const build_docker/./src/Functions/FunctionsConversion.h:3147:20

```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix lazy execution of default argument in dictGetOrDefault for RangeHashedDictionary that could lead to nullptr dereference on bad column types in FunctionsConversion. Closes https://github.com/ClickHouse/ClickHouse/issues/56661.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 9b055c3a43039387b42e755efddd83b9a8934ca6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61196/9b055c3a43039387b42e755efddd83b9a8934ca6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — APPROVED** [review]

File: src/Functions/FunctionsConversion.h [hunk 1]
```diff
@@ -4561,7 +4561,7 @@ arguments, result_type, input_rows_count); \
 
                 if (from_low_cardinality)
                 {
-                    const auto * col_low_cardinality = typeid_cast<const ColumnLowCardinality *>(arguments[0].column.get());
+                    const auto * col_low_cardinality = assert_cast<const ColumnLowCardinality *>(arguments[0].column.get());
```
Comment (Algunenano) [inline src/Functions/FunctionsConversion.h:4564]: Keep in mind that this is only going to work in debug mode. It's still going to crash in release

Comment (Avogar) [reply src/Functions/FunctionsConversion.h:4564]: Do you think it's better to add a separate check `if (col_low_cardinality) throw ...`?

Comment (Avogar) [reply src/Functions/FunctionsConversion.h:4564]: Ah, I see you found repro, this is great. Are you going to debug it? If no, I can do it

Comment (Algunenano) [reply src/Functions/FunctionsConversion.h:4564]: I'm trying to fix other things right now, so if you are familiar with dictionaries or conversion functions you can have it. Otherwise I'll go through the fuzzer issues as soon as builds are fine

Comment (Avogar) [reply src/Functions/FunctionsConversion.h:4564]: I will take it then

**Review by vdimir — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @Avogar @Algunenano @vdimir — while reviewing this PR I found the following:

- **Coverage gap:** Laziness of default argument in 5-arg `dictGetOrDefault` for `RANGE_HASHED` dictionary is untested — https://github.com/ClickHouse/ClickHouse/pull/103920

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
