### PR TITLE
Fix weak hash for sparse

### LINKED ISSUE #65596: `first_value` produces unexpected result.
**Describe what's wrong**
`first_value` produces unexpected result.

**How to reproduce**

* Which ClickHouse server version to use: `24.5.3.5`
* Which interface to use, if it matters: `MySQL Shell`
* Non-default settings, if any: `distributed_product_mode='allow'`

* init database:
```sql
create database ch_main on cluster default;
use ch_main;

create table __t_vlb0j97q73 on cluster default ( 
  c_krlvf7r Int32 not null ,
  c_j Float64 not null ,
  c_mql9vleain Float64 ,
  c_g12cd6 Bool ,
  c_ybbt4 Int32 primary key ,
  c_au Float64 ,
  c_qkvm Float64 ,
  c_c0 String ,
  c_sv8 Float64 ,
  c_u7rl Int32 not null primary key ,
  );

create table t_vlb0j97q73 on cluster default as __t_vlb0j97q73 ENGINE = Distributed(default, ch_main, __t_vlb0j97q73, c_u7rl);

alter table t_vlb0j97q73 on cluster default add column c_rvbdzh05z2 Float64;

alter table __t_vlb0j97q73 on cluster default add column c_rvbdzh05z2 Float64;

-- sql #200
insert into t_vlb0j97q73 (c_krlvf7r, c_j, c_mql9vleain, c_g12cd6, c_ybbt4, c_au, c_qkvm, c_c0, c_sv8, c_u7rl, c_rvbdzh05z2) values 
  (-1296505474, -9223372036854775808.1, -32766.9, coalesce(false, false), 1705178392, 31.51, 7.25, 'gcb85', 257.5, 1789497921, -4294967297.3), 
  (1415982483, 129.4, 72.69, coalesce((NOT NOT(cast( (27.95 < -49) as Nullable(Bool)))), false), 1498165591, -65537.1, 61.3, 'wsa', 2147483649.4, 28, -65537.0), 
  (-1, 78.79, 257.3, coalesce(false, false), 27, 35.36, 50.8, 'v', 72.27, 1319586506, 16.97), 
  (-943848536, 72.54, 45.4, coalesce((NOT NOT(cast( ((NOT NOT(cast( (4309333590239081003 < 1919386270203424658) as Nullable(Bool)))) >= cast(null as Nullable(UInt16))) as Nullable(Bool)))), false), 1451852280, 95.68, -254.3, 'bwf', 97.19, -385119672, 44.24);

-- sql #118
insert into t_vlb0j97q73 (c_krlvf7r, c_j, c_mql9vleain, c_g12cd6, c_ybbt4, c_au, c_qkvm, c_c0, c_sv8, c_u7rl, c_rvbdzh05z2) values 
  (1872965090, 4294967296.5, -254.7, coalesce(true, false), 223667259, 257.7, -126.3, 'fppgprme_', 28.86, 1, 23.28), 
  (863501642, 64.77, 53.3, coalesce(true, true), 4, 65536.3, 100.87, 'svc0gj', 90.35, -1709612210, 20.44), 
  (-930745500, 83.34, 2147483648.100000, coalesce((NOT NOT(cast( (-14272 AND 6) as Nullable(Bool)))), false), -1382928137, 68.79, 3.92, 's', -9223372036854775807.6, 2012296048, -2.0), 
  (1029445083, -2147483646.6, 2.5, coalesce((1636710674 between 4096 and -1), true), 1948189386, 99.39, -1.2, 'la', 9223372036854775807.2, -2112636050, 79.89);

  -- sql #80
insert into t_vlb0j97q73 (c_krlvf7r, c_j, c_mql9vleain, c_g12cd6, c_ybbt4, c_au, c_qkvm, c_c0, c_sv8, c_u7rl, c_rvbdzh05z2) values 
  (-981982931, 35.69, 78.92, coalesce((false) 
    or (true), true), 747913102, 100.13, -9223372036854775808.1, 'szclpikm', 24.71, -2070018982, -0.3), 
  (931163950, 129.3, 254.2, coalesce((NOT NOT(cast( (7110798446849532427 OR -17266) as Nullable(Bool)))), true), 1853241461, 95.6, 2147483647.4, 'esfz7ac', 128.4, -1051135399, 98.1), 
  (1, 73.40, 73.76, coalesce((-811268288 is NULL), false), 682404355, 4294967296.3, 18446744073709551615.5, 'bsqzqh7c32', 18446744073709551616.7, 2016799203, 66.79), 
  (-1, 3.76, 74.59, coalesce((NOT NOT(cast( (-2147483649.3 > (1378727582 between 1936442277 and 1418436539)) as Nullable(Bool)))), true), 200763128, -32769.7, 2147483646.1, 'v6', 31.5, 593252920, 51.67);


```

* Queries to run that lead to an unexpected result
```sql
SELECT DISTINCT
  first_value(ref_0.c_u7rl) over (partition by ref_0.c_g12cd6 order by ref_0.c_u7rl) as c7
FROM
  t_vlb0j97q73 as ref_0
;

```

**Expected behavior**
previous SQL produces:
```
mysql> SELECT DISTINCT
    ->   first_value(ref_0.c_u7rl) over (partition by ref_0.c_g12cd6 order by ref_0.c_u7rl) as c7
    -> FROM
    ->   t_vlb0j97q73 as ref_0
    -> ;
+-------------+
| c7          |
+-------------+
|  -385119672 |
| -2070018982 |
| -2112636050 |
+-------------+
3 rows in set (0.01 sec)
Read 196 rows, 986.00 B in 0.008507 sec., 23039 rows/sec., 113.19 KiB/sec.
```

**However, there are only two possible values for columns used for partitioning:**

```
mysql> select distinct ref_0.c_g12cd6 from t_vlb0j97q73 as ref_0;
+----------+
| c_g12cd6 |
+----------+
|        0 |
|        1 |
+----------+
2 rows in set (0.01 sec)
Read 12 rows, 26.00 B in 0.007368 sec., 1628 rows/sec., 3.45 KiB/sec.
```

rows in table:
```
mysql> select ref_0.c_g12cd6, ref_0.c_u7rl from t_vlb0j97q73 as ref_0 order by 1,2;
+----------+-------------+
| c_g12cd6 | c_u7rl      |
+----------+-------------+
|        0 | -2112636050 |
|        0 |  -385119672 |
|        0 |          28 |
|        0 |   593252920 |
|        0 |  1319586506 |
|        0 |  1789497921 |
|        0 |  2016799203 |
|        1 | -2070018982 |
|        1 | -1709612210 |
|        1 | -1051135399 |
|        1 |           1 |
|        1 |  2012296048 |
+----------+-------------+
12 rows in set (0.01 sec)
Read 12 rows, 65.00 B in 0.002577 sec., 4656 rows/sec., 24.63 KiB/sec.
```
Therefore, correct result should be:
```
mysql> SELECT DISTINCT   first_value(ref_0.c_u7rl) over (partition by ref_0.c_g12cd6 order by ref_0.c_u7rl) as c7 FROM   t_vlb0j97q73 as ref_0;
+-------------+
| c7          |
+-------------+
| -2112636050 |
| -2070018982 |
+-------------+
2 rows in set (0.01 sec)
Read 12 rows, 65.00 B in 0.003031 sec., 3959 rows/sec., 20.94 KiB/sec.
```

**Additional context**
docker compose config:
```
version: '3.8'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.1
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.2
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.5
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.6
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.7
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

networks:
  cluster_2S_1R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.7.0/24
          gateway: 10.0.7.254
```

config.xml
```xml
<clickhouse replace="true">
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <display_name>cluster_2S_1R node 1</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>
    <postgresql_port>9005</postgresql_port>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
    </user_directories>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
    <zookeeper>
        <node>
            <host>clickhouse-keeper-01</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-02</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-03</host>
            <port>9181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>
```
users.xml
```xml
<?xml version="1.0"?>
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <distributed_product_mode>allow</distributed_product_mode>
        </default>
    </profiles>
    <users>
        <default>
            <access_management>1</access_management>
            <profile>default</profile>
            <networks>
                <ip>::/0</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```
keeper_config.xml:
```xml
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>::</listen_host>
    <max_thread_pool_size>10000</max_thread_pool_size>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>3</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```
#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the potential above-mentioned vulnerability that may lead to database logic error.

### LINKED ISSUE #66121: `count` produces unexpected result
**Describe what's wrong**
`count` produces unexpected result.

**How to reproduce**

* Which ClickHouse server version to use: `24.5.3.5`
* Which interface to use, if it matters: `MySQL Shell`
* Non-default settings, if any: `distributed_product_mode='allow'`

* init database:
```sql
create database ch_main on cluster default;
use ch_main;
```
Then execute the SQL statements in `init.sql`.
[init.sql.txt](https://github.com/user-attachments/files/16108098/init.sql.txt)

* Queries to run that lead to an unexpected result
```sql
SELECT DISTINCT
  count(ref_0.c_zosphq2t1) over (partition by ref_0.c_hqfr9 order by ref_0.c_ylzjpt, ref_0.c_hqfr9, ref_0.c_zosphq2t1) as c0,
  ref_0.c_ylzjpt as c1
FROM
  t_vkx4cc as ref_0;
```

previous SQL produces:
```
mysql> SELECT DISTINCT
    ->   count(ref_0.c_zosphq2t1) over (partition by ref_0.c_hqfr9 order by ref_0.c_ylzjpt, ref_0.c_hqfr9, ref_0.c_zosphq2t1) as c0,
    ->   ref_0.c_ylzjpt as c1
    -> FROM
    ->   t_vkx4cc as ref_0;
+------+-------------+
| c0   | c1          |
+------+-------------+
|    1 | -1981899149 |
|    2 | -1650266905 |
|    3 | -1646738223 |
|    4 | -1618912877 |
|    5 | -1317193174 |
|    6 | -1219769753 |
|    7 | -1154269118 |
|    8 | -1150980622 |
|    9 | -1098155311 |
|   10 |  -841067875 |
|   11 |  -816935497 |
|   12 |  -599948807 |
|   13 |  -526570556 |
|   14 |  -504713125 |
|   15 |  -411038390 |
|   16 |  -331834394 |
|   17 |  -176934810 |
|   18 |          -2 |
|   19 |           6 |
|   20 |         255 |
|   21 |   406615258 |
|   22 |   541758331 |
|   23 |   897064234 |
|   24 |  1116921321 |
|   25 |  1207796283 |
|   26 |  1603772265 |
|   27 |  1664059402 |
|   28 |  1688303275 |
|   29 |  1913361922 |
|   30 |  1929066636 |
|   31 |  1968095908 |
|   32 |  2054878592 |
|   33 |  2125075305 |
|    1 |   720985423 |
|    2 |   745669725 |
|    1 | -2081147898 |
|    2 | -2051538534 |
|    3 | -1975508531 |
|    4 | -1700730666 |
|    5 | -1465484835 |
|    6 | -1458338029 |
|    7 | -1450619195 |
|    8 | -1365934326 |
|    9 | -1203382363 |
|   10 | -1197430632 |
|   11 | -1176267855 |
|   12 | -1020892864 |
|   13 |  -991301833 |
|   14 |  -685902265 |
|   15 |  -653505826 |
|   16 |  -451392958 |
|   17 |  -262516786 |
|   18 |  -222873194 |
|   19 |  -153185515 |
|   20 |   -74234560 |
|   21 |         -41 |
|   22 |          -6 |
|   23 |          -5 |
|   24 |          -3 |
|   25 |          15 |
|   26 |       65535 |
|   27 |    77089559 |
|   28 |   100663045 |
|   29 |   561061873 |
|   30 |   643897141 |
|   31 |   914629990 |
|   32 |  1159852204 |
|   33 |  1258218855 |
|   34 |  1459407556 |
|   35 |  1936334332 |
|   36 |  1962246186 |
|   37 |  2030467062 |
+------+-------------+
72 rows in set (0.01 sec)
Read 72 rows, 943.00 B in 0.007997 sec., 9003 rows/sec., 115.16 KiB/sec.

```

**Expected behavior**
In the returned rows, the content of the following rows is incorrect.
```
|    1 |   720985423 |
|    2 |   745669725 |
|   23 |   897064234 |
|   24 |  1116921321 |
|   25 |  1207796283 |
|   26 |  1603772265 |
|   27 |  1664059402 |
|   28 |  1688303275 |
|   29 |  1913361922 |
|   30 |  1929066636 |
|   31 |  1968095908 |
|   32 |  2054878592 |
|   33 |  2125075305 |
```
The correct rows shoule be:
```
|   23 |   720985423 |
|   24 |   745669725 |
|   25 |   897064234 |
|   26 |  1116921321 |
|   27 |  1207796283 |
|   28 |  1603772265 |
|   29 |  1664059402 |
|   30 |  1688303275 |
|   31 |  1913361922 |
|   32 |  1929066636 |
|   33 |  1968095908 |
|   34 |  2054878592 |
|   35 |  2125075305 |
```

**Additional context**
docker compose config:
```
version: '3.8'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.1
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.2
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.5
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.6
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.7
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

networks:
  cluster_2S_1R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.7.0/24
          gateway: 10.0.7.254
```

config.xml
```xml
<clickhouse replace="true">
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <display_name>cluster_2S_1R node 1</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>
    <postgresql_port>9005</postgresql_port>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
    </user_directories>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
    <zookeeper>
        <node>
            <host>clickhouse-keeper-01</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-02</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-03</host>
            <port>9181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>
```
users.xml
```xml
<?xml version="1.0"?>
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <distributed_product_mode>allow</distributed_product_mode>
        </default>
    </profiles>
    <users>
        <default>
            <access_management>1</access_management>
            <profile>default</profile>
            <networks>
                <ip>10.0.0.1/8</ip>
                <ip>127.0.0.1/8</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```
keeper_config.xml:
```xml
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>::</listen_host>
    <max_thread_pool_size>10000</max_thread_pool_size>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>3</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```
#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the potential above-mentioned vulnerability that may lead to database logic error.

### LINKED ISSUE #66128: `min over (partition)` produces unexpected result
**Describe what's wrong**
`min` produces unexpected result.

**How to reproduce**

* Which ClickHouse server version to use: `24.5.3.5`
* Which interface to use, if it matters: `MySQL Shell`
* Non-default settings, if any: `distributed_product_mode='allow'`

* init database:
```sql
create database ch_main on cluster default;
use ch_main;

create table __t_vkx4cc on cluster default ( 
  c_ylzjpt Int32 primary key ,
  c_hqfr9 Bool ,
  );

create table t_vkx4cc on cluster default as __t_vkx4cc ENGINE = Distributed(default, ch_main, __t_vkx4cc, c_ylzjpt);

insert into t_vkx4cc (c_ylzjpt, c_hqfr9) values 
  (255, coalesce(false, false)), 
  (-1317193174, coalesce(false, false)), 
  (-41, coalesce(true, false)), 
  (1929066636, coalesce(false, true));

insert into t_vkx4cc (c_ylzjpt, c_hqfr9) values 
  (-2, coalesce(false, false)), 
  (1962246186, coalesce(true, false)), 
  (-991301833, coalesce(true, true)), 
  (2054878592, coalesce(false, false));

insert into t_vkx4cc (c_ylzjpt, c_hqfr9) values 
  (439499072, coalesce((NOT NOT(cast( (6 AND true) as Nullable(Bool)))), true)), 
  (1393290072, coalesce((true) 
    and ((NOT NOT(cast( (77.66 != 98) as Nullable(Bool))))), false)), 
  (3, coalesce((NOT NOT(cast( (6912410221475350151 <= 18.78) as Nullable(Bool)))), true)), 
  (189195893, coalesce((NOT NOT(cast( (-26 >= 69.24) as Nullable(Bool)))), true));

alter table t_vkx4cc on cluster default add column c_zosphq2t1 Float64;

alter table __t_vkx4cc on cluster default add column c_zosphq2t1 Float64;

insert into t_vkx4cc (c_ylzjpt, c_hqfr9, c_zosphq2t1) values 
  (-1338380855, coalesce(true, false), -0.7), 
  (-755809149, coalesce(false, false), 43.18), 
  (-1893563136, coalesce(true, false), 41.55), 
  (195550885, coalesce(false, true), 9223372036854775806.7);
```

* Queries to run that lead to an unexpected result
```sql
SELECT
  c4 as c4, c0 as c0
FROM
  (select  
    ref_0.c_ylzjpt as c0,
    
      min(
        ref_0.c_zosphq2t1) over (partition by ref_0.c_hqfr9 order by ref_0.c_ylzjpt, ref_0.c_hqfr9, ref_0.c_zosphq2t1) as c4
  from 
    t_vkx4cc as ref_0
);
```

previous SQL produces:
```
mysql> SELECT
    ->   c4 as c4, c0 as c0
    -> FROM
    ->   (select  
    ->     ref_0.c_ylzjpt as c0,
    ->     
    ->       min(
    ->         ref_0.c_zosphq2t1) over (partition by ref_0.c_hqfr9 order by ref_0.c_ylzjpt, ref_0.c_hqfr9, ref_0.c_zosphq2t1) as c4
    ->   from 
    ->     t_vkx4cc as ref_0
    -> );
+-------+-------------+
| c4    | c0          |
+-------+-------------+
| 43.18 |  -755809149 |
|     0 |          -2 |
|     0 |         255 |
|     0 |   195550885 |
|     0 |  2054878592 |
| 41.55 | -1893563136 |
|  -0.7 | -1338380855 |
|  -0.7 |  -991301833 |
|  -0.7 |         -41 |
|  -0.7 |   439499072 |
|  -0.7 |  1393290072 |
|  -0.7 |  1962246186 |
|     0 | -1317193174 |
|     0 |           3 |
|     0 |   189195893 |
|     0 |  1929066636 |
+-------+-------------+
16 rows in set (0.00 sec)
Read 16 rows, 222.00 B in 0.005943 sec., 2692 rows/sec., 36.48 KiB/sec.
```

**Expected behavior**
In the returned rows, the content of the following row is incorrect.
```
| 43.18 |  -755809149 |
```
The correct row shoule be:
```
|     0 |  -755809149 |
```

**Additional context**
docker compose config:
```
version: '3.8'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.1
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.2
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.5
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.6
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.7
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

networks:
  cluster_2S_1R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.7.0/24
          gateway: 10.0.7.254
```

config.xml
```xml
<clickhouse replace="true">
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <display_name>cluster_2S_1R node 1</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>
    <postgresql_port>9005</postgresql_port>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
    </user_directories>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
    <zookeeper>
        <node>
            <host>clickhouse-keeper-01</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-02</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-03</host>
            <port>9181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>
```
users.xml
```xml
<?xml version="1.0"?>
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <distributed_product_mode>allow</distributed_product_mode>
        </default>
    </profiles>
    <users>
        <default>
            <access_management>1</access_management>
            <profile>default</profile>
            <networks>
                <ip>10.0.0.1/8</ip>
                <ip>127.0.0.1/8</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```
keeper_config.xml:
```xml
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>::</listen_host>
    <max_thread_pool_size>10000</max_thread_pool_size>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>3</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```
#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the potential above-mentioned vulnerability that may lead to database logic error.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix an invalid result for queries with `WINDOW`. This could happen when `PARTITION` columns have sparse serialization and window functions are executed in parallel.

Fixes #65596 , fixes #66128 , fixes #66121

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 902e548a2daf087bdb4363694a91bf665a7f7f9b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66579/902e548a2daf087bdb4363694a91bf665a7f7f9b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66537/5efbb42a2a0efbb5a32267fec60ab73eddaea4cf/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by novikd** [comment]
I suspect #66128 and #66121 also relate to this bug fix. Let's add tests here and close the issues.

File: src/Columns/ColumnSparse.cpp [hunk 1]
```diff
@@ -807,6 +809,24 @@ size_t ColumnSparse::getValueIndex(size_t n) const
...
+    if (off_size == 0 || offsets_data[0] > 0)
+        return 0;
+
+    size_t idx = 0;
+    while (idx + 1 < off_size && offsets_data[idx] + 1 == offsets_data[idx + 1])
+        ++idx;
+
+    return offsets_data[idx] + 1;
+}
+
```
Comment (CurtizJ) [inline src/Columns/ColumnSparse.cpp:829]: Is this method actually needed?

**Review by CurtizJ — APPROVED** [review]

File: src/Columns/ColumnSparse.cpp (hunk 1 above)
Comment (KochetovNicolai) [reply src/Columns/ColumnSparse.cpp:829]: No. Forgot to remove.

**Review by novikd — APPROVED** [review]
