### PR TITLE
Fix adding sub-second intervals to DateTime

### LINKED ISSUE #45779: Adding intervals of a fraction of a second to a datetime gives incorrect result
**Describe what's wrong**

Adding millisecond, microsecond or nanosecond intervals to a DateTime seems totally broken:

```
SELECT
    CAST(today(), 'DateTime') AS t,
    t + toIntervalSecond(1),
    t + toIntervalMillisecond(1),
    t + toIntervalMicrosecond(1),
    t + toIntervalNanosecond(1)

Query id: d76c3515-6ea3-4997-885d-1c2b5fcf9c7f

Row 1:
──────
t:                                                         2023-01-30 00:00:00
plus(CAST(today(), 'DateTime'), toIntervalSecond(1)):      2023-01-30 00:00:01
plus(CAST(today(), 'DateTime'), toIntervalMillisecond(1)): 2105-12-22 11:44:17
plus(CAST(today(), 'DateTime'), toIntervalMicrosecond(1)): 1977-11-28 02:08:17
plus(CAST(today(), 'DateTime'), toIntervalNanosecond(1)):  1983-04-14 20:27:13
```

I would expect to not see any changes to the Datetime (as the rounding goes to 0), and to see t+toIntervalMillisecond(1000) add `1` second to the DateTime. 

It works as expected with DateTime64:

```
SELECT
    CAST(today(), 'DateTime64') AS t,
    t + toIntervalSecond(1),
    t + toIntervalMillisecond(1),
    t + toIntervalMicrosecond(1),
    t + toIntervalNanosecond(1)

Query id: 1225a403-4f78-4130-b251-7235306b6be3

Row 1:
──────
t:                                                           2023-01-30 00:00:00.000
plus(CAST(today(), 'DateTime64'), toIntervalSecond(1)):      2023-01-30 00:00:01.000
plus(CAST(today(), 'DateTime64'), toIntervalMillisecond(1)): 2023-01-30 00:00:00.001
plus(CAST(today(), 'DateTime64'), toIntervalMicrosecond(1)): 2023-01-30 00:00:00.000001
plus(CAST(today(), 'DateTime64'), toIntervalNanosecond(1)):  2023-01-30 00:00:00.000000001
```

**Does it reproduce on recent release?**

* 22.3: Not supported
* 22.8.11.15: Fails
* Master: Fails

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed adding intervals of a fraction of a second to DateTime producing incorrect result.

Closes https://github.com/ClickHouse/ClickHouse/issues/45779

```
:) select toDateTime('2000-01-01') + interval 1 millisecond
```
Before:
```
┌─plus(toDateTime('2000-01-01'), toIntervalMillisecond(0))─┐
│                                      2026-10-14 16:21:20 │
└──────────────────────────────────────────────────────────┘
```
After:
```
┌─plus(toDateTime('2000-01-01'), toIntervalMillisecond(1))─┐
│                                  2000-01-01 00:00:00.001 │
└──────────────────────────────────────────────────────────┘
```

It was a simple bug in AddNanosecondsImpl/etc - it was returning a wrong type.

---

Along the way added a check for this overflow (very incomplete, other overflows remain unchecked):
```
:) select toDateTime64('3000-01-01 12:00:00.12345', 0) + interval 0 nanosecond
```
Before:
```
┌─plus(toDateTime64('3000-01-01 12:00:00.12345', 0), toIntervalNanosecond(0))─┐
│                                               1900-01-01 00:00:00.290448384 │
└─────────────────────────────────────────────────────────────────────────────┘
```
After:
```
Received exception:
Code: 407. DB::Exception: Decimal math overflow: While processing toDateTime64('3000-01-01 12:00:00.12345', 0) + toIntervalNanosecond(0). (DECIMAL_OVERFLOW)
```

---

And made incompatible types get rejected during typechecking rather than execution:
```
:) select toTypeName(materialize(toDate('2000-01-01')) + interval 1 nanosecond)
```
Before:
```
┌─toTypeName(plus(materialize(toDate('2000-01-01')), toIntervalNanosecond(1)))─┐
│ DateTime64(9)                                                                │
└──────────────────────────────────────────────────────────────────────────────┘
```
After:
```
Received exception:
Code: 43. DB::Exception: addNanoseconds cannot be used with Date: While processing toTypeName(materialize(toDate('2000-01-01')) + toIntervalNanosecond(1)). (ILLEGAL_TYPE_OF_ARGUMENT)
```

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 2d2a9c23a8898560df7c72062fc0ba6cc5d621f9 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53309/2d2a9c23a8898560df7c72062fc0ba6cc5d621f9/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Functions/FunctionDateOrDateTimeAddInterval.h [hunk 1]
```diff
@@ -45,140 +47,104 @@ struct AddNanosecondsImpl
...
-        return static_cast<UInt32>(t * multiplier + delta);
+        return DateTime64(DecimalUtils::multiplyAdd(static_cast<Int64>(t), multiplier, delta));
     }
 
-    static inline NO_SANITIZE_UNDEFINED DateTime64 execute(UInt16, Int64, const DateLUTImpl &, UInt16 = 0)
+    static inline NO_SANITIZE_UNDEFINED Int8 execute(UInt16, Int64, const DateLUTImpl &, UInt16 = 0)
     {
-        throw Exception(ErrorCodes::ILLEGAL_TYPE_OF_ARGUMENT, "addNanoSeconds() cannot be used with Date");
+        chassert(false);
+        return 0;
```
Comment (antonio2368) [inline src/Functions/FunctionDateOrDateTimeAddInterval.h:66]: maybe throw a logical error in cases like this?
Returning 0 seems strange on something that shouldn't be called + it could make it harder to debug.

Comment (al13n321) [reply src/Functions/FunctionDateOrDateTimeAddInterval.h:66]: Yeah, that sounds better, changing.

**Comment by al13n321** [comment]
Stress test (debug): https://github.com/ClickHouse/ClickHouse/issues/53454

**Review by antonio2368 — APPROVED** [review]

**Comment by tavplubix** [comment]
The new test is flaky:
https://s3.amazonaws.com/clickhouse-test-reports/0/407bb57ba9b4727b135635d3e6479f9e635b6ded/stateless_tests__release__s3_storage__[1_2].html

https://s3.amazonaws.com/clickhouse-test-reports/53673/61f4b6e2294a13541e8304336b427bcbafb199a9/stateless_tests__debug__s3_storage__[1_6].html

**Comment by al13n321** [comment]
> The new test is flaky:

Wow, a simple `toDateTime('2000-01-01 12:00:00') + INTERVAL 1234567 SECOND` produced a result that's off by exactly one hour. Must be something related to timezones. But what exactly? The only thing I can think of is session's or server's timezone changing between the `toDateTime` execution and the formatting of the results; but AFAICT server timezone can't change at runtime and session timezone can't change without the test doing any queries to change it. What else can it be? Am I misunderstanding how timezones work in CH?

**Comment by tavplubix** [comment]
Maybe this is the culprit:
https://github.com/ClickHouse/ClickHouse/blob/16cbda14f8ad0685b05965f083ff170b41dad923/tests/clickhouse-test#L613-L624

**Comment by al13n321** [comment]
Ah, turns out the real timezone randomization is in `docker/test/stateless/run.sh` rather than `tests/clickhouse-test`, that's why I couldn't reproduce it locally. Fix in https://github.com/ClickHouse/ClickHouse/pull/53906
