### PR TITLE
Fix waiting while dropping empty parts

### LINKED ISSUE #23292: Replication may stuck due to clearEmptyParts (>=20.12)
Symptoms: all threads in BackgroundScheduledPool busy, lot of tasks in replication queue, none of the tasks is executing. 

Screenshot from 2021-04-16 16-21-44_

Related to #16895

Possible workarounds (poor options): increasing the background_schedule_pool_size to huge values, or restart server every time when that happens etc. -

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix waiting of automatic dropping of empty parts. It could lead to full filling of background pool and stuck of replication.

Fixes #23292.

### CODE REVIEW

**Comment by CurtizJ** [comment]
It's hard to implement test with stable behaviour for this PR, because dropping of empty parts is executing asynchronously and there is no mechanism to control time of it's start.

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -1305,14 +1305,17 @@ void MergeTreeData::clearEmptyParts()
...
+    context_for_drop->setSetting("replication_alter_partitions_sync", Field(0));
     auto parts = getDataPartsVector();
     for (const auto & part : parts)
     {
         if (part->rows_count == 0)
         {
             ASTPtr literal = std::make_shared<ASTLiteral>(part->name);
             /// If another replica has already started drop, it's ok, no need to throw.
-            dropPartition(literal, /* detach = */ false, /*drop_part = */ true, getContext(), /* throw_if_noop = */ false);
+            dropPartition(literal, /* detach = */ false, /*drop_part = */ true, context_for_drop, /* throw_if_noop = */ false);
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeData.cpp:1318]: Looks ugly. Why don't extract another method from `dropPartition` that will do the internal parts without the whole query-related logic?

**Comment by alexey-milovidov** [comment]
@Mergifyio update

File: src/Storages/MergeTree/MergeTreeData.h [hunk 2]
```diff
@@ -964,7 +964,9 @@ class MergeTreeData : public IStorage, public WithContext
     // Partition helpers
     bool canReplacePartition(const DataPartPtr & src_part) const;
 
-    virtual void dropPartition(const ASTPtr & partition, bool detach, bool drop_part, ContextPtr context, bool throw_if_noop = true) = 0;
+    /// Tries to drop part in background without any waits or throwing exceptions in case of errors.
+    virtual void dropPart(const String & name) = 0;
+    virtual void dropPartition(const ASTPtr & partition, bool detach, bool drop_part, ContextPtr context) = 0;
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeData.h:969]: But now the parameter `drop_part` looks weird.

File: src/Storages/StorageReplicatedMergeTree.h [hunk 3]
```diff
@@ -624,12 +624,13 @@ class StorageReplicatedMergeTree final : public ext::shared_ptr_helper<StorageRe
     /// Info about how other replicas can access this one.
     ReplicatedMergeTreeAddress getReplicatedMergeTreeAddress() const;
 
+    void dropPart(const String & name) override;
     bool dropPart(zkutil::ZooKeeperPtr & zookeeper, String part_name, LogEntry & entry, bool detach, bool throw_if_noop);
```
Comment (alexey-milovidov) [inline src/Storages/StorageReplicatedMergeTree.h:628]: Here the code becomes prohibitively complicated.

File: src/Storages/StorageReplicatedMergeTree.h [hunk 4]
```diff
@@ -624,12 +624,13 @@ class StorageReplicatedMergeTree final : public ext::shared_ptr_helper<StorageRe
     /// Info about how other replicas can access this one.
     ReplicatedMergeTreeAddress getReplicatedMergeTreeAddress() const;
 
+    void dropPart(const String & name) override;
```
Comment (alexey-milovidov) [inline src/Storages/StorageReplicatedMergeTree.h:627]: At least need to name the method differently.

File: src/Storages/StorageReplicatedMergeTree.h (hunk 3 above)
Comment (alexey-milovidov) [inline src/Storages/StorageReplicatedMergeTree.h:628]: Move to private? Name it with `Impl`?

**Comment by CurtizJ** [comment]
Stress test looks suspicious:
```
2021.05.17 20:03:59.789358 [ 269 ] {} <Fatal> BaseDaemon: (version 21.6.1.6861, build id: 51338596DD99F8FD4D9DB1771AC33D051563333F) (from thread 333) Terminate called for uncaught exception:
Code: 49, e.displayText() = DB::Exception: Part 0_0_1_999999999 intersects previous part 0_0_0_0_1. It is a bug., Stack trace (when copying this message, always include the lines below):
```

```
2021.05.17 20:03:59.634206 [ 272 ] {ba358a21-a74a-49d8-bab6-d71ea3ace476} <Debug> executeQuery: (from [::1]:44052, using production parser) alter table rmt drop partition '0';
2021.05.17 20:03:59.634415 [ 272 ] {ba358a21-a74a-49d8-bab6-d71ea3ace476} <Trace> ContextAccess (default): Access granted: ALTER DELETE ON test_13.rmt
2021.05.17 20:03:59.682750 [ 272 ] {ba358a21-a74a-49d8-bab6-d71ea3ace476} <Trace> test_13.rmt: Deleted 1 deduplication block IDs in partition ID 0
2021.05.17 20:03:59.682818 [ 272 ] {ba358a21-a74a-49d8-bab6-d71ea3ace476} <Debug> test_13.rmt: Disabled merges covered by range 0_0_1_999999999
2021.05.17 20:03:59.695639 [ 272 ] {ba358a21-a74a-49d8-bab6-d71ea3ace476} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
```

**Comment by CurtizJ** [comment]
Probably fix is here: #24208.

File: src/Storages/StorageMergeTree.cpp [hunk 5]
```diff
@@ -1240,56 +1240,63 @@ MergeTreeDataPartPtr StorageMergeTree::outdatePart(const String & part_name, boo
     }
 }
 
-void StorageMergeTree::dropPartition(const ASTPtr & partition, bool detach, bool drop_part, ContextPtr local_context, bool throw_if_noop)
+void StorageMergeTree::dropPartNoWaitNoThrow(const String & part_name)
 {
-    {
-        MergeTreeData::DataPartsVector parts_to_remove;
-        auto metadata_snapshot = getInMemoryMetadataPtr();
+    if (auto part = outdatePart(part_name, false))
```
Comment (filimonov) [inline src/Storages/StorageMergeTree.cpp:1245]:
```suggestion
    if (auto part = outdatePart(part_name, /* force*/ false))
```
btw that 'force' is a bit misleading...

File: src/Storages/StorageMergeTree.cpp [hunk 6]
```diff
@@ -1240,56 +1240,63 @@ MergeTreeDataPartPtr StorageMergeTree::outdatePart(const String & part_name, boo
...
+        dropPartsImpl({part}, false);
```
Comment (filimonov) [inline src/Storages/StorageMergeTree.cpp:1246]:
```suggestion
        dropPartsImpl({part}, /* detach */ false);
```

File: src/Storages/StorageMergeTree.cpp [hunk 7]
```diff
@@ -1240,56 +1240,63 @@ MergeTreeDataPartPtr StorageMergeTree::outdatePart(const String & part_name, boo
...
-        {
-            /// If DETACH clone parts to detached/ directory
-            /// NOTE: no race with background cleanup until we hold pointers to parts
-            for (const auto & part : parts_to_remove)
-            {
-                LOG_INFO(log, "Detaching {}", part->relative_path);
-                part->makeCloneInDetached("", metadata_snapshot);
-            }
-        }
+    /// Else nothing to do, part was removed in some different way
```
Comment (filimonov) [inline src/Storages/StorageMergeTree.cpp:1256]: else is not possible when force = true, so it can be assert or just w/o any if.

File: src/Storages/StorageMergeTree.cpp (hunk 5 above)
Comment (azat) [reply src/Storages/StorageMergeTree.cpp:1245]: To make [clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-argument-comment.html) complains, it should be

```suggestion
    if (auto part = outdatePart(part_name, /* force= */ false))
```

(Here and below)

File: src/Storages/StorageMergeTree.cpp [hunk 8]
```diff
@@ -1240,56 +1240,63 @@ MergeTreeDataPartPtr StorageMergeTree::outdatePart(const String & part_name, boo
...
+}
 
-        if (deduplication_log)
+void StorageMergeTree::dropPartition(const ASTPtr & partition, bool detach, ContextPtr local_context)
+{
+    /// Asks to complete merges and does not allow them to start.
+    /// This protects against "revival" of data for a removed partition after completion of merge.
+    auto merge_blocker = stopMergesAndWait();
```
Comment (filimonov) [inline src/Storages/StorageMergeTree.cpp:1263]: it's a pity that we can't do it per partition... Stopping (and waiting) of all merges in 'hot' partition during dropping some old partition is not great. And while files are removed no merges will start. 

Maybe we can release the merge_blocker bit earlier - for ex. after removePartsFromWorkingSet ?

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 9]
```diff
@@ -4927,46 +4927,61 @@ bool StorageReplicatedMergeTree::getFakePartCoveringAllPartsInPartition(const St
...
-        did_drop = dropPart(zookeeper, part_name, entry, detach, throw_if_noop);
-    }
-    else
-    {
-        String partition_id = getPartitionIDFromQuery(partition, query_context);
-        did_drop = dropAllPartsInPartition(*zookeeper, partition_id, entry, query_context, detach);
-    }
+    bool did_drop = dropPartImpl(zookeeper, part_name, entry, detach, true);
 
     if (did_drop)
```
Comment (filimonov) [inline src/Storages/StorageReplicatedMergeTree.cpp:4953]: always true (otherwise dropPartImpl shoud raise exception due to throw_if_noop=trie

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 10]
```diff
@@ -4927,46 +4927,61 @@ bool StorageReplicatedMergeTree::getFakePartCoveringAllPartsInPartition(const St
...
-        String partition_id = getPartitionIDFromQuery(partition, query_context);
-        cleanLastPartNode(partition_id);
+        /// If necessary, wait until the operation is performed on itself or on all replicas.
+        if (query_context->getSettingsRef().replication_alter_partitions_sync == 1)
+            waitForReplicaToProcessLogEntry(replica_name, entry);
+        else if (query_context->getSettingsRef().replication_alter_partitions_sync == 2)
+            waitForAllReplicasToProcessLogEntry(entry);
     }
+
+    cleanLastPartNode(partition_id);
```
Comment (filimonov) [inline src/Storages/StorageReplicatedMergeTree.cpp:4984]: looked bit safer inside `if (did_drop)` (why should we clean it if the drop was not successful?)

File: src/Storages/StorageMergeTree.cpp (hunk 8 above)
Comment (CurtizJ) [reply src/Storages/StorageMergeTree.cpp]: Yes, lock can released after `removePartsFromWorkingSet`. It's better to lock for merges only parts, that are currently removing, but not in this PR.
