### PR TITLE
Functions calculation after sorting

### LINKED ISSUE #11103: Calculate functions after sorting and LIMIT if possible.
Example:

```
SELECT throwIf(number = 5) FROM (SELECT * FROM numbers(10)) ORDER BY number LIMIT 1
```

If the optimization exists, `throwIf(number = 5)` will be calculate only on first row and the query won't throw exception.

### PR DESCRIPTION
**Pull request by nickitat**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
A new query plan optimization. Evaluate functions after `ORDER BY` when possible. As an example, for a query `SELECT sipHash64(number) FROM numbers(1e8) ORDER BY number LIMIT 5`, function `sipHash64` would be evaluated after `ORDER BY` and `LIMIT`, which gives ~20x speed up.

Calculation of functions that are not required to calculate sorting columns is now moved after SortingStep in the query plan. 

Closes #11103.

### CODE REVIEW

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by nickitat** [comment]
tests are ok, a bit of code clean-up is needed.

File: src/Interpreters/ActionsDAG.cpp [hunk 1]
```diff
@@ -1527,6 +1527,17 @@ ActionsDAG::SplitResult ActionsDAG::splitActionsBeforeArrayJoin(const NameSet &
     return res;
 }
 
+ActionsDAG::SplitResult ActionsDAG::splitActionsBySortingDescription(const NameSet & sort_columns) const
+{
+    std::unordered_set<const Node *> split_nodes;
+    for (const auto & sort_column : sort_columns)
+        if (const auto * node = tryFindInIndex(sort_column))
```
Comment (KochetovNicolai) [inline src/Interpreters/ActionsDAG.cpp:1534]: I think it is reasonable to throw an exception otherwise

File: src/Processors/QueryPlan/SortingStep.cpp [hunk 2]
```diff
@@ -88,6 +89,18 @@ SortingStep::SortingStep(
     output_stream->sort_mode = DataStream::SortMode::Stream;
 }
 
+void SortingStep::updateInputStream(DataStream input_stream)
+{
+    input_streams.clear();
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/SortingStep.cpp:94]: Sort description may be invalid with a new input_stream if there were positions in there.

Actually, I don't know in which case positions are used. Maybe we can remove this code and see what will be broken:
https://github.com/ClickHouse/ClickHouse/blob/31c367d3cd3aefd316778601ff6565119fe36682/src/Core/SortDescription.h#L49-L55

File: tests/performance/function_calculation_after_sorting_and_limit.xml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+<test>
+    <query>SELECT sipHash64(number) FROM numbers(1e8) ORDER BY number LIMIT 5</query>
```
Comment (KochetovNicolai) [inline tests/performance/function_calculation_after_sorting_and_limit.xml:2]: Is it faster now? :)

File: src/Processors/QueryPlan/Optimizations/Optimizations.h [hunk 4]
```diff
@@ -44,16 +44,20 @@ size_t tryMergeExpressions(QueryPlan::Node * parent_node, QueryPlan::Nodes &);
...
-    static const std::array<Optimization, 5> optimizations =
-    {{
+    static const std::array<Optimization, 6> optimizations = {{
         {tryLiftUpArrayJoin, "liftUpArrayJoin", &QueryPlanOptimizationSettings::optimize_plan},
         {tryPushDownLimit, "pushDownLimit", &QueryPlanOptimizationSettings::optimize_plan},
         {trySplitFilter, "splitFilter", &QueryPlanOptimizationSettings::optimize_plan},
         {tryMergeExpressions, "mergeExpressions", &QueryPlanOptimizationSettings::optimize_plan},
         {tryPushDownFilter, "pushDownFilter", &QueryPlanOptimizationSettings::filter_push_down},
-     }};
+        {tryExecuteFunctionsAfterSorting, "liftUpFunctions", &QueryPlanOptimizationSettings::optimize_plan},
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/Optimizations/Optimizations.h:59]: Let's maybe add a special setting to it.

Also, I think more generic name would be `pushDownSorting` (and something like `query_plan_sorting_push_down`). For it we could check what other steps could be swapped with sorting.

**Review by KochetovNicolai — COMMENTED** [review]
Generally looks ok

File: src/Processors/QueryPlan/Optimizations/Optimizations.h (hunk 4 above)
Comment (KochetovNicolai) [reply src/Processors/QueryPlan/Optimizations/Optimizations.h:59]: hm, can't find any other step. Probably I am wrong

**Comment by KochetovNicolai** [comment]
Can you also add a query with `throwIf` from the issue?

File: src/Processors/QueryPlan/SortingStep.cpp (hunk 2 above)
Comment (nickitat) [reply src/Processors/QueryPlan/SortingStep.cpp:94]: let's see https://github.com/ClickHouse/ClickHouse/pull/35805

**Comment by nickitat** [comment]
> Can you also add a query with `throwIf` from the issue?

it's already added to `tests/queries/0_stateless/01655_plan_optimizations`

File: tests/performance/function_calculation_after_sorting_and_limit.xml (hunk 3 above)
Comment (KochetovNicolai) [reply tests/performance/function_calculation_after_sorting_and_limit.xml:2]: x20 times faster!

**Review by KochetovNicolai — APPROVED** [review]
