### PR TITLE
Fix docs for timeDiff and dateDiff

### LINKED ISSUE #89225: timDiff expects 2 parameters, while documentation mentions 3
### Company or project name

_No response_

### Describe what's wrong

i suspect that the timeDiff function is broken since a while, including v25.11.1.683 that's on play.clickhouse.com

i'm trying few examples from https://clickhouse.com/docs/sql-reference/functions/date-time-functions#timeDiff and they fail:

```
SELECT timeDiff('hour', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-02 23:00:00')) AS res

Code: 42. DB::Exception: Number of arguments for function timeDiff doesn't match: passed 3, should be 2: In scope SELECT timeDiff('hour', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-02 23:00:00')) AS res. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 25.11.1.683 (official build))
```

```
SELECT
    toDate('2022-01-01') AS e,
    toDate('2021-12-29') AS s,
    timeDiff('day', s, e) AS day_diff,
    timeDiff('month', s, e) AS month_diff,
    timeDiff('year', s, e) AS year_diff


Code: 42. DB::Exception: Number of arguments for function timeDiff doesn't match: passed 3, should be 2: In scope SELECT toDate('2022-01-01') AS e, toDate('2021-12-29') AS s, timeDiff('day', s, e) AS day_diff, timeDiff('month', s, e) AS month_diff, timeDiff('year', s, e) AS year_diff. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 25.11.1.683 (official build))
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

try above examples at https://play.clickhouse.com

### Expected behavior

i'd expect responses as in https://clickhouse.com/docs/sql-reference/functions/date-time-functions#timeDiff

thank you!

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by raimannma**
### Changelog category (leave one):
- Documentation (changelog entry is not required)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### Details

Closes #89225

### CODE REVIEW

File: src/Functions/dateDiff.cpp [hunk 1]
```diff
@@ -524,17 +514,77 @@ SELECT timeDiff('hour', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-0
...
+    dateDiff('year', s, e) AS year_diff
         )",
         R"(
 ┌──────────e─┬──────────s─┬─day_diff─┬─month_diff─┬─year_diff─┐
 │ 2022-01-01 │ 2021-12-29 │        3 │          1 │         1 │
 └────────────┴────────────┴──────────┴────────────┴───────────┘
         )"}
     };
-    FunctionDocumentation::IntroducedIn introduced_in = {23, 4};
+    FunctionDocumentation::IntroducedIn introduced_in = {1, 1};
```
Comment (yariks5s) [inline src/Functions/dateDiff.cpp]:
```suggestion
    FunctionDocumentation::IntroducedIn introduced_in = {23, 4};
```

File: src/Functions/dateDiff.cpp [hunk 2]
```diff
@@ -524,17 +514,77 @@ SELECT timeDiff('hour', toDateTime('2018-01-01 22:00:00'), toDateTime('2018-01-0
...
+    timeDiff(toDateTime('2021-12-29'), toDateTime('2022-01-01')) AS time_diff_result,
+    dateDiff('second', toDateTime('2021-12-29'), toDateTime('2022-01-01')) AS date_diff_result
+        )",
+        R"(
+┌─time_diff_result─┬─date_diff_result─┐
+│           259200 │           259200 │
+└──────────────────┴──────────────────┘
+        )"}
+    };
+    FunctionDocumentation::IntroducedIn introduced_in = {1, 1};
```
Comment (yariks5s) [inline src/Functions/dateDiff.cpp]:
```suggestion
    FunctionDocumentation::IntroducedIn introduced_in = {23, 4};
```

**Review by yariks5s — APPROVED** [review]
All other than that is OK

**Comment by yariks5s** [comment]
[Stateless tests (amd_debug, distributed plan, s3 storage, sequential)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89359&sha=e2b805683d97f4283f30a1ed208dbe3012feb659&name_0=PR&name_1=Stateless+tests+%28amd_debug%2C+distributed+plan%2C+s3+storage%2C+sequential%29) -- https://github.com/ClickHouse/ClickHouse/issues/87801

[Integration tests (amd_asan, old analyzer, 4/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89359&sha=e2b805683d97f4283f30a1ed208dbe3012feb659&name_0=PR&name_1=Integration+tests+%28amd_asan%2C+old+analyzer%2C+4%2F6%29) -- flaky
