### PR TITLE
Fix possible Logical error: Cannot write to finalized buffer

### LINKED ISSUE #31710: Logical error: Cannot write to finalized buffer
https://clickhouse-test-reports.s3.yandex.net/0/1f2087fc7b9ff941676a08e7a843320625e97f8b/stress_test_(debug).html#fail1

```
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:22:35.735607 [ 1183 ] {f38e5156-a989-46eb-95cd-115a849c9d36} <Fatal> : Logical error: 'Cannot write to finalized buffer'.
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:25.898545 [ 11122 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:25.912984 [ 11122 ] {} <Fatal> BaseDaemon: (version 21.12.1.8845 (official build), build id: 69382CCFADDAB23384BE9C81FFBFCC521A8B35FD) (from thread 1183) (query_id: f38e5156-a989-46eb-95cd-115a849c9d36) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:25.941391 [ 11122 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:25.948533 [ 11122 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fa0f91fe18b 0x7fa0f91dd859 0x1513dd78 0x1513de82 0x1515e2e5 0x1515dcae 0x1515f405 0x15276f7a 0x22e1b031 0x22e1bfe7 0x22eb3eaf 0x27359b39 0x2735a348 0x274abad4 0x274a85ba 0x274a739c 0x7fa0f93e0609 0x7fa0f92da293
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:25.960497 [ 11122 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:25.966294 [ 11122 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:26.337969 [ 11122 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:51: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x1513dd78 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:26.490329 [ 11122 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:58: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1513de82 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:26.913618 [ 11122 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Common/Exception.h:35: DB::Exception::Exception(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1515e2e5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:27.118714 [ 11122 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/IO/WriteBuffer.h:78: DB::WriteBuffer::write(char const*, unsigned long) @ 0x1515dcae in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:27.433838 [ 11122 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/IO/WriteHelpers.h:186: DB::writeString(char const*, unsigned long, DB::WriteBuffer&) @ 0x1515f405 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:27.786882 [ 11122 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/IO/WriteHelpers.h:197: DB::writeString(std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::WriteBuffer&) @ 0x15276f7a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:30.738992 [ 11122 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Server/HTTPHandler.cpp:856: DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x22e1b031 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:31.665807 [ 11122 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Server/HTTPHandler.cpp:940: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x22e1bfe7 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:32.210490 [ 11122 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Server/HTTP/HTTPServerConnection.cpp:58: DB::HTTPServerConnection::run() @ 0x22eb3eaf in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:32.552799 [ 11122 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x27359b39 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:33.154075 [ 11122 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x2735a348 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:33.843395 [ 11122 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x274abad4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:34.086817 [ 11122 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x274a85ba in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:34.258406 [ 11122 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x274a739c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:34.259897 [ 11122 ] {} <Fatal> BaseDaemon: 20. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:34.262247 [ 11122 ] {} <Fatal> BaseDaemon: 21. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:39.806237 [ 11122 ] {} <Fatal> BaseDaemon: Checksum of the binary: 7663321023338C7B5F7816E08C043741, integrity check passed.
/var/log/clickhouse-server/clickhouse-server.log.2:2021.11.24 16:23:47.290468 [ 505 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

cc: @Avogar

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix possible Logical error: Cannot write to finalized buffer. Closes https://github.com/ClickHouse/ClickHouse/issues/31710

### CODE REVIEW

File: src/Server/HTTPHandler.h [hunk 1]
```diff
@@ -60,20 +60,28 @@ class HTTPHandler : public HTTPRequestHandler
...
+
         inline bool hasDelayed() const
         {
             return out_maybe_delayed_and_compressed != out_maybe_compressed;
         }
 
-        inline void finalize() const
+        inline void finalize()
         {
+            finalized = true;
```
Comment (nikitamikhaylov) [inline src/Server/HTTPHandler.h:72]:
```
if (finalized) return;
finalized = true;
```

File: src/Server/HTTPHandler.cpp [hunk 2]
```diff
@@ -929,15 +929,25 @@ void HTTPHandler::handleRequest(HTTPServerRequest & request, HTTPServerResponse
             request_credentials.reset(); // ...so that the next requests on the connection have to always start afresh in case of exceptions.
         });
 
-        tryLogCurrentException(log);
+        /// Check if exception was thrown in used_output.finalize().
+        /// In this case used_output can be in invalid state and we
+        /// cannot write in it anymore. So, just log this exception.
+        if (used_output.isFinalized())
+        {
+            tryLogCurrentException(log, "Cannot flush data to client");
```
Comment (nikitamikhaylov) [inline src/Server/HTTPHandler.cpp:937]: tryLogCurrentException and maybe immediately return from handler? The code will be slightly more readable

**Review by nikitamikhaylov — APPROVED** [review]
