### PR TITLE
Always schedule direct IO to threadpool for pread_threadpool

### LINKED ISSUE #85689: test_threadpool_readers/test.py::test_local_fs_threadpool_reader is flaky
### Describe the bug

Seen here: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=85654&sha=9bd848011b26be9910e94d5c59d307337d180f34&name_0=PR&name_1=Integration+tests+%28amd_asan%2C+old+analyzer%2C+5%2F6%29

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by korowa**
Closes #85689 

preadv2 with RWF_NOWAIT may perform reads from device and return data (not EAGAIN) when called on fd with O_DIRECT flag. This leads to data reading being executed in query thread, instead of threadpool which is intended for pread_threadpool.

This patch skips preadv2 / pagecache checking logic when direct io is requested, so that it always executed in threadpool.

<details>
<summary>Simple reproducer out of ClickHouse context</summary>

```c
// "iotest.c"

#define _GNU_SOURCE
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/uio.h>
#include <unistd.h>
#include <errno.h>
#include <assert.h>

#define ALIGNMENT 131072
#define BUF_SIZE ALIGNMENT

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <filename>\n", argv[0]);
        return 1;
    }
    const char *filename = argv[1];

    int fd = open(filename, O_RDONLY | O_DIRECT | O_CLOEXEC);
    if (fd < 0) {
        perror("open");
        return 1;
    }

    void *buf;
    if (posix_memalign(&buf, ALIGNMENT, BUF_SIZE) != 0) {
        perror("posix_memalign");
        close(fd);
        return 1;
    }

    memset(buf, 0, BUF_SIZE);

    struct iovec iov = {
        .iov_base = buf,
        .iov_len = BUF_SIZE
    };

    ssize_t offset = 0;
    ssize_t ret = 0;

    while (ret >= 0)
    {
        ret = syscall(SYS_preadv2, fd, &iov, 1, offset, offset >> 32, RWF_NOWAIT);

        if (ret >= 0) {
            printf("preadv2 RWF_NOWAIT succeeded, read %zd bytes\n", ret);
        } else {
            if (errno == EAGAIN) {
                printf("preadv2 RWF_NOWAIT returned EAGAIN (data not in page cache)\n");
                return 1;
            } else {
                perror("preadv2");
                return 1;
            }
        }

        if (ret == 0)
        {
            break;
        }

        offset += ret;
    }

    free(buf);
    close(fd);

    return 0;
}
```

```sh
# Build
clang -o iotest iotest.c

# Create non-cached data file on ext4 fs
dd if=/dev/urandom of=/tmp/trash.dat oflag=direct bs=128K count=100

# Read the file (it'll succeed, while failing for fd opened w/o O_DIRECT).
# Running it with strace + blktrace shows successful preadv2 along with
# disk reads.
./iotest /tmp/trash.dat
```

</details>

(or added test which demonstrates this behavior)

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

cc @kssenii

### CODE REVIEW

**Comment by korowa** [comment]
Marked as draft, as the description is not completely correct -- even in cases when there are only `ThreadPoolReaderPageCacheHit` profile events in the query (and there are no misses), the data is still read from disk (according to OSReadBytes), so may not be related to data presence in page cache.

**Comment by korowa** [comment]
> [Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=85765&sha=779fc192ca915b8189ad6132df4b8a49f69adab3&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%20parallel%29)

https://github.com/ClickHouse/ClickHouse/issues/85861

> [Stress test (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=85765&sha=779fc192ca915b8189ad6132df4b8a49f69adab3&name_0=PR&name_1=Stress%20test%20%28amd_debug%29)

https://github.com/ClickHouse/ClickHouse/issues/84186

File: src/Disks/IO/ThreadPoolReader.cpp [hunk 1]
```diff
@@ -113,7 +113,7 @@ std::future<IAsynchronousReader::Result> ThreadPoolReader::submit(Request reques
     /// disable pread with nowait.
     static const bool has_pread_nowait_support = !hasBugInPreadV2();
 
-    if (has_pread_nowait_support)
+    if (has_pread_nowait_support && !request.direct_io)
```
Comment (azat) [inline src/Disks/IO/ThreadPoolReader.cpp:118]:
```suggestion
    /// RWF_NOWAIT is ignored for O_DIRECT (mostly, it may return EAGAIN if it cannot lock the inode in case of ext4, see [1])
    ///   [1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=548feebec7e93e58b647dba70b3303dcb569c914
    if (has_pread_nowait_support && !request.direct_io)
```

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql [hunk 2]
```diff
@@ -0,0 +1,44 @@
+-- Tags: stateful
+
```
Comment (azat) [inline tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]:
```suggestion
```

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+select * from 03595_data
+format Null
+settings
+    local_filesystem_read_method = 'pread_threadpool',
+    min_bytes_to_use_direct_io = 1,
+    log_query_threads = 1,
+    use_uncompressed_cache = 0;
+
+select * from 03595_data
```
Comment (azat) [inline tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql:22]:
```suggestion
-- If previous query was running w/o O_DIRECT (due to some bug) it may fill pagecache,
-- and then subsequent query will read from cache (if it will ignore O_DIRECT flag as well) with RWF_NOWAIT,
-- so let's make sure that this is not the case
select * from 03595_data
```

**Review by azat — APPROVED** [review]
@korowa nice catch! Patch looks good to me, please take a look at my adjustments (mostly comments in the code)

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    use_uncompressed_cache = 0;
+
+system flush logs query_log, query_thread_log;
+
+with queries as (
+    select query_id, row_number() over(order by event_time_microseconds) as ordinal
+    from system.query_log
+    where type = 'QueryFinish'
+     and current_database = currentDatabase()
+     and query like 'select * from 03595_data%'
```
Comment (azat) [inline tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]:
```suggestion
     and Settings['min_bytes_to_use_direct_io'] = '1'
```

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql (hunk 3 above)
Comment (korowa) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql:22]: Seems to be not the best idea due to settings randomization (maybe revert or explicitly `set min_bytes_to_use_direct_io = 0` in the beginning of the test script)

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql (hunk 2 above)
Comment (korowa) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]: That was intended to prevent runs s3 backed tests (there are no local-fs -- but I can adapt the tests to them also if required)

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql (hunk 3 above)
Comment (azat) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql:22]: Make sense, let's set it explicitly at the beginning

File: tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql (hunk 2 above)
Comment (azat) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]: Will `no-object-storage` work?

Comment (korowa) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]: Yes, it should help.

And one more thing I've realized just now that it may fail for parallel replicas in case read will be performed not on initiator replica (due to query ids usage in the last query). Will `no-parallel-replicas` be ok here or better to adjust for this case?

Comment (azat) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]: Sure thing!

Comment (azat) [reply tests/queries/0_stateless/03595_pread_threadpool_direct_io.sql]: >Will no-parallel-replicas be ok here

Yep, the complexity does not worth it, let's simply add a tag

**Comment by azat** [comment]
CI issues either known or reported

**Comment by azat** [comment]
@korowa Thanks for keeping history clean!
