### PR TITLE
Try fix rabbitmq potential leak

### LINKED ISSUE #44840: RabbitMQConnection direct leak
https://s3.amazonaws.com/clickhouse-test-reports/44825/c3b3ae886f4e98d7681800cdb8cc1701af942af8/integration_tests__asan__[4/6].html

test_storage_rabbitmq
```
==8==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 155648 byte(s) in 22 object(s) allocated from:
    #0 0xe69e756 in realloc (/usr/bin/clickhouse+0xe69e756) (BuildId: e5cec1fe866a6c357fbf065b62bbd2dac427bc4a)
    #1 0x3e2cdb1b in uv__realloc build_docker/../contrib/libuv/src/uv-common.c:98:12
    #2 0x3e2cdb1b in uv__reallocf build_docker/../contrib/libuv/src/uv-common.c:106:12
    #3 0x3e2d6163 in maybe_resize build_docker/../contrib/libuv/src/unix/core.c:846:14
    #4 0x3e2d6163 in uv__io_start build_docker/../contrib/libuv/src/unix/core.c:885:3
    #5 0x3e2f50b2 in uv__signal_loop_once_init build_docker/../contrib/libuv/src/unix/signal.c:265:3
    #6 0x3e2f50b2 in uv_signal_init build_docker/../contrib/libuv/src/unix/signal.c:312:9
    #7 0x3e2ecd1c in uv_loop_init build_docker/../contrib/libuv/src/unix/loop.c:82:9
    #8 0x33acb390 in DB::UVLoop::UVLoop() build_docker/../src/Storages/UVLoop.h:24:19
    #9 0x33ac7025 in DB::RabbitMQConnection::RabbitMQConnection(DB::RabbitMQConfiguration const&, Poco::Logger*) build_docker/../src/Storages/RabbitMQ/RabbitMQConnection.cpp:14:21
    #10 0x33a8c8c0 in std::__1::__unique_if<DB::RabbitMQConnection>::__unique_single std::__1::make_unique[abi:v15000]<DB::RabbitMQConnection, DB::RabbitMQConfiguration&, Poco::Logger*&>(DB::RabbitMQConfiguration&, Poco::Logger*&) build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714:32
    #11 0x33a8c8c0 in DB::StorageRabbitMQ::StorageRabbitMQ(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, bool) build_docker/../src/Storages/RabbitMQ/StorageRabbitMQ.cpp:171:22
    #12 0x33ac5f18 in DB::StorageRabbitMQ* std::__1::construct_at[abi:v15000]<DB::StorageRabbitMQ, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, bool const&, DB::StorageRabbitMQ*>(DB::StorageRabbitMQ*, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, bool const&) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #13 0x33ac5f18 in void std::__1::allocator_traits<std::__1::allocator<DB::StorageRabbitMQ>>::construct[abi:v15000]<DB::StorageRabbitMQ, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, bool const&, void, void>(std::__1::allocator<DB::StorageRabbitMQ>&, DB::StorageRabbitMQ*, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, bool const&) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #14 0x33ac5f18 in std::__1::__shared_ptr_emplace<DB::StorageRabbitMQ, std::__1::allocator<DB::StorageRabbitMQ>>::__shared_ptr_emplace[abi:v15000]<DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, bool const&>(std::__1::allocator<DB::StorageRabbitMQ>, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, bool const&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #15 0x33ac5f18 in std::__1::shared_ptr<DB::StorageRabbitMQ> std::__1::allocate_shared[abi:v15000]<DB::StorageRabbitMQ, std::__1::allocator<DB::StorageRabbitMQ>, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, bool const&, void>(std::__1::allocator<DB::StorageRabbitMQ> const&, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, bool const&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #16 0x33ab6710 in std::__1::shared_ptr<DB::StorageRabbitMQ> std::__1::make_shared[abi:v15000]<DB::StorageRabbitMQ, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>, bool const&, void>(DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings>>&&, bool const&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #17 0x33ab6710 in DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21::operator()(DB::StorageFactory::Arguments const&) const build_docker/../src/Storages/RabbitMQ/StorageRabbitMQ.cpp:1196:16
    #18 0x33ab6710 in decltype(std::declval<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21&>()(std::declval<DB::StorageFactory::Arguments const&>())) std::__1::__invoke[abi:v15000]<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21&, DB::StorageFactory::Arguments const&>(DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21&, DB::StorageFactory::Arguments const&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #19 0x33ab6710 in std::__1::shared_ptr<DB::IStorage> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::IStorage>, false>::__call<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21&, DB::StorageFactory::Arguments const&>(DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21&, DB::StorageFactory::Arguments const&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:470:16
    #20 0x33ab6710 in std::__1::__function::__default_alloc_func<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()[abi:v15000](DB::StorageFactory::Arguments const&) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #21 0x33ab6710 in std::__1::shared_ptr<DB::IStorage> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerStorageRabbitMQ(DB::StorageFactory&)::$_21, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #22 0x3323e811 in std::__1::__function::__policy_func<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()[abi:v15000](DB::StorageFactory::Arguments const&) const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #23 0x3323e811 in std::__1::function<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #24 0x3323e811 in DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const build_docker/../src/Storages/StorageFactory.cpp:229:16
    #25 0x3161c492 in DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::__1::unique_ptr<DB::DDLGuard, std::__1::default_delete<DB::DDLGuard>>&) build_docker/../src/Interpreters/InterpreterCreateQuery.cpp:1362:42
    #26 0x3160ee14 in DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) build_docker/../src/Interpreters/InterpreterCreateQuery.cpp:1226:20
    #27 0x31624fd8 in DB::InterpreterCreateQuery::execute() build_docker/../src/Interpreters/InterpreterCreateQuery.cpp:1636:16
    #28 0x324b4cde in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:705:36
    #29 0x324adbab in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1104:30
    #30 0x34c0669d in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:375:24
    #31 0x34c37545 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1920:9
    #32 0x3c36ea2e in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #33 0x3c36f784 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #34 0x3c83383b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #35 0x3c82cdec in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #36 0x7f187694c608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Direct leak of 131072 byte(s) in 17 object(s) allocated from:
    #0 0xe69e756 in realloc (/usr/bin/clickhouse+0xe69e756) (BuildId: e5cec1fe866a6c357fbf065b62bbd2dac427bc4a)
    #1 0x3e2cdb1b in uv__realloc build_docker/../contrib/libuv/src/uv-common.c:98:12
    #2 0x3e2cdb1b in uv__reallocf build_docker/../contrib/libuv/src/uv-common.c:106:12
    #3 0x3e2d6163 in maybe_resize build_docker/../contrib/libuv/src/unix/core.c:846:14
    #4 0x3e2d6163 in uv__io_start build_docker/../contrib/libuv/src/unix/core.c:885:3
    #5 0x3e2f50b2 in uv__signal_loop_once_init build_docker/../contrib/libuv/src/unix/signal.c:265:3
    #6 0x3e2f50b2 in uv_signal_init build_docker/../contrib/libuv/src/unix/signal.c:312:9
    #7 0x3e2ecd1c in uv_loop_init build_docker/../contrib/libuv/src/unix/loop.c:82:9
    #8 0x33acb390 in DB::UVLoop::UVLoop() build_docker/../src/Storages/UVLoop.h:24:19
    #9 0x33ac7025 in DB::RabbitMQConnection::RabbitMQConnection(DB::RabbitMQConfiguration const&, Poco::Logger*) build_docker/../src/Storages/RabbitMQ/RabbitMQConnection.cpp:14:21
    #10 0x33ae7ff0 in DB::WriteBufferToRabbitMQProducer::WriteBufferToRabbitMQProducer(DB::RabbitMQConfiguration const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType, unsigned long, bool, std::__1::atomic<bool>&, Poco::Logger*, std::__1::optional<char>, unsigned long, unsigned long) build_docker/../src/Storages/RabbitMQ/WriteBufferToRabbitMQProducer.cpp:42:11
    #11 0x33aa4df5 in DB::WriteBufferToRabbitMQProducer* std::__1::construct_at[abi:v15000]<DB::WriteBufferToRabbitMQProducer, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>, int, int, DB::WriteBufferToRabbitMQProducer*>(DB::WriteBufferToRabbitMQProducer*, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>&&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long&&, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>&&, int&&, int&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #12 0x33aa4df5 in void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferToRabbitMQProducer>>::construct[abi:v15000]<DB::WriteBufferToRabbitMQProducer, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>, int, int, void, void>(std::__1::allocator<DB::WriteBufferToRabbitMQProducer>&, DB::WriteBufferToRabbitMQProducer*, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>&&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long&&, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>&&, int&&, int&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #13 0x33aa4df5 in std::__1::__shared_ptr_emplace<DB::WriteBufferToRabbitMQProducer, std::__1::allocator<DB::WriteBufferToRabbitMQProducer>>::__shared_ptr_emplace[abi:v15000]<DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>, int, int>(std::__1::allocator<DB::WriteBufferToRabbitMQProducer>, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>&&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long&&, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>&&, int&&, int&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #14 0x33aa4df5 in std::__1::shared_ptr<DB::WriteBufferToRabbitMQProducer> std::__1::allocate_shared[abi:v15000]<DB::WriteBufferToRabbitMQProducer, std::__1::allocator<DB::WriteBufferToRabbitMQProducer>, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>, int, int, void>(std::__1::allocator<DB::WriteBufferToRabbitMQProducer> const&, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>&&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long&&, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>&&, int&&, int&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #15 0x33aa4df5 in std::__1::shared_ptr<DB::WriteBufferToRabbitMQProducer> std::__1::make_shared[abi:v15000]<DB::WriteBufferToRabbitMQProducer, DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>, int, int, void>(DB::RabbitMQConfiguration&, std::__1::shared_ptr<DB::Context const>&&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, AMQP::ExchangeType&, unsigned long&&, bool const&, std::__1::atomic<bool>&, Poco::Logger*&, std::__1::optional<char>&&, int&&, int&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #16 0x33aa4df5 in DB::StorageRabbitMQ::createWriteBuffer() build_docker/../src/Storages/RabbitMQ/StorageRabbitMQ.cpp:931:12
    #17 0x33ae5fdf in DB::RabbitMQSink::onStart() build_docker/../src/Storages/RabbitMQ/RabbitMQSink.cpp:27:22
    #18 0x352f847f in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #19 0x352f847f in std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #20 0x352f847f in DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:115:9
    #21 0x352f7007 in DB::ExceptionKeepingTransform::work() build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:137:30
    #22 0x34d21520 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #23 0x34d21520 in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #24 0x34d0055c in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26
    #25 0x34cff6ba in DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:126:5
    #26 0x34d3637a in DB::PushingPipelineExecutor::start() build_docker/../src/Processors/Executors/PushingPipelineExecutor.cpp:91:20
    #27 0x34c19394 in auto DB::TCPHandler::processInsertQuery()::$_0::operator()<DB::PushingPipelineExecutor>(DB::PushingPipelineExecutor&) const build_docker/../src/Server/TCPHandler.cpp:693:18
    #28 0x34c19394 in DB::TCPHandler::processInsertQuery() build_docker/../src/Server/TCPHandler.cpp:728:9
    #29 0x34c068bd in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:384:17
    #30 0x34c37545 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1920:9
    #31 0x3c36ea2e in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #32 0x3c36f784 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #33 0x3c83383b in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #34 0x3c82cdec in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #35 0x7f187694c608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

Direct leak of 8192 byte(s) in 1 object(s) allocated from:
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/44840.

### CODE REVIEW

File: src/Storages/UVLoop.h [hunk 1]
```diff
@@ -30,7 +31,34 @@ class UVLoop : public boost::noncopyable
...
+
+                /// Run the loop until there are no pending callbacks.
+                while (true)
+                {
+                    res = uv_run(loop_ptr.get(), UV_RUN_ONCE);
+                    if (res)
+                        LOG_DEBUG(log, "Waiting for pending callbacks to finish ({})", res);
+                    else
+                        break;
+                }
```
Comment (antonio2368) [inline src/Storages/UVLoop.h:50]: can we get "stuck" here and prevent server from shutting down?

Comment (antonio2368) [inline src/Storages/UVLoop.h:50]:
```suggestion
                while (uv_run(loop_ptr.get(), UV_RUN_ONCE))
                {
                    LOG_DEBUG(log, "Waiting for pending callbacks to finish ({})", res);
                }
```
maybe

Comment (kssenii) [reply src/Storages/UVLoop.h:50]: Actually I do not think so, because I also added closing of the connection object before this loop is destructed, so the number of events must be fixed and new events should not arise afterwards.

Comment (kssenii) [reply src/Storages/UVLoop.h]: And also handler is destructed before the loop too (see comment [d3e26c2](https://github.com/ClickHouse/ClickHouse/pull/44897/commits/d3e26c28cb15a24b740b733514d8e2973641805c)), so noone else can use this loop.

**Review by antonio2368 — APPROVED** [review]

**Comment by antonio2368** [comment]
😢 
https://s3.amazonaws.com/clickhouse-test-reports/44897/283388cfa6c155120c865094da62b427ce484077/integration_tests__release__[2/4].html

**Comment by kssenii** [comment]
> 😢
[https://s3.amazonaws.com/clickhouse-test-reports/44897/283388cfa6c155120c865094da62b427ce484077/integration_tests__release__[2/4].html](https://s3.amazonaws.com/clickhouse-test-reports/44897/283388cfa6c155120c865094da62b427ce484077/integration_tests__release__%5B2/4%5D.html)

Running the loop runs all pending callbacks and looks like some callback which touchs `handler` (lies inside connection wrapper) is touched from the callback when we run the loop in the destructor of connection wrapper class and so it crashes. Love asynchronous libraries 🥲 

```
2023.01.04 15:56:58.716302 [ 333 ] {} <Trace> BaseDaemon: Received signal 11
2023.01.04 15:56:58.716525 [ 719 ] {} <Fatal> BaseDaemon: ########################################
2023.01.04 15:56:58.716556 [ 719 ] {} <Fatal> BaseDaemon: (version 22.13.1.1213, build id: BB9F3795EE551878EC1EEE0489113189126FDA47) (from thread 412) (no query) Received signal Segmentation fault (11)
2023.01.04 15:56:58.716577 [ 719 ] {} <Fatal> BaseDaemon: Address: 0xd0 Access: read. Address not mapped to object.
2023.01.04 15:56:58.716596 [ 719 ] {} <Fatal> BaseDaemon: Stack trace: 0x1522dfb4 0x15226538 0x192fd4d1 0x1931a521 0x193163a8 0x19311d12 0x192febe0 0x1930c9bd 0x19306d55 0x1933a9c1 0x19325b18 0x1522db85 0x1522c125 0x152230e5 0x13f42a8e 0x139203e1 0x139239aa 0x139248ce 0xf27bfb6 0xf281181 0x7fcc129cc609 0x7fcc128f1133
2023.01.04 15:56:58.716635 [ 719 ] {} <Fatal> BaseDaemon: 2. DB::RabbitMQHandler::stopLoop() @ 0x1522dfb4 in /usr/bin/clickhouse
2023.01.04 15:56:58.716644 [ 719 ] {} <Fatal> BaseDaemon: 3. ? @ 0x15226538 in /usr/bin/clickhouse
2023.01.04 15:56:58.716653 [ 719 ] {} <Fatal> BaseDaemon: 4. ? @ 0x192fd4d1 in /usr/bin/clickhouse
2023.01.04 15:56:58.716661 [ 719 ] {} <Fatal> BaseDaemon: 5. ? @ 0x1931a521 in /usr/bin/clickhouse
2023.01.04 15:56:58.716669 [ 719 ] {} <Fatal> BaseDaemon: 6. ? @ 0x193163a8 in /usr/bin/clickhouse
2023.01.04 15:56:58.716680 [ 719 ] {} <Fatal> BaseDaemon: 7. AMQP::ReceivedFrame::processQueueFrame(AMQP::ConnectionImpl*) @ 0x19311d12 in /usr/bin/clickhouse
2023.01.04 15:56:58.716691 [ 719 ] {} <Fatal> BaseDaemon: 8. AMQP::ConnectionImpl::parse(AMQP::Buffer const&) @ 0x192febe0 in /usr/bin/clickhouse
2023.01.04 15:56:58.716699 [ 719 ] {} <Fatal> BaseDaemon: 9. ? @ 0x1930c9bd in /usr/bin/clickhouse
2023.01.04 15:56:58.716710 [ 719 ] {} <Fatal> BaseDaemon: 10. ? @ 0x19306d55 in /usr/bin/clickhouse
2023.01.04 15:56:58.716719 [ 719 ] {} <Fatal> BaseDaemon: 11. uv__io_poll @ 0x1933a9c1 in /usr/bin/clickhouse
2023.01.04 15:56:58.716727 [ 719 ] {} <Fatal> BaseDaemon: 12. uv_run @ 0x19325b18 in /usr/bin/clickhouse
2023.01.04 15:56:58.716735 [ 719 ] {} <Fatal> BaseDaemon: 13. DB::RabbitMQHandler::iterateLoop() @ 0x1522db85 in /usr/bin/clickhouse
2023.01.04 15:56:58.716744 [ 719 ] {} <Fatal> BaseDaemon: 14. DB::RabbitMQConnection::~RabbitMQConnection() @ 0x1522c125 in /usr/bin/clickhouse
2023.01.04 15:56:58.716752 [ 719 ] {} <Fatal> BaseDaemon: 15. ? @ 0x152230e5 in /usr/bin/clickhouse
2023.01.04 15:56:58.716761 [ 719 ] {} <Fatal> BaseDaemon: 16. DB::DatabaseCatalog::dropTableDataTask() @ 0x13f42a8e in /usr/bin/clickhouse
2023.01.04 15:56:58.716770 [ 719 ] {} <Fatal> BaseDaemon: 17. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x139203e1 in /usr/bin/clickhouse
2023.01.04 15:56:58.716778 [ 719 ] {} <Fatal> BaseDaemon: 18. DB::BackgroundSchedulePool::threadFunction() @ 0x139239aa in /usr/bin/clickhouse
2023.01.04 15:56:58.716786 [ 719 ] {} <Fatal> BaseDaemon: 19. ? @ 0x139248ce in /usr/bin/clickhouse
2023.01.04 15:56:58.716798 [ 719 ] {} <Fatal> BaseDaemon: 20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xf27bfb6 in /usr/bin/clickhouse
2023.01.04 15:56:58.716806 [ 719 ] {} <Fatal> BaseDaemon: 21. ? @ 0xf281181 in /usr/bin/clickhouse
2023.01.04 15:56:58.716814 [ 719 ] {} <Fatal> BaseDaemon: 22. ? @ 0x7fcc129cc609 in ?
2023.01.04 15:56:58.716822 [ 719 ] {} <Fatal> BaseDaemon: 23. __clone @ 0x7fcc128f1133 in ?
```

**Comment by antonio2368** [comment]
But it looks good now, so awesome job

**Comment by qoega** [comment]
- test_snapshot_on_exit 44908
- test_version_update_after_mutation new #44929
- test_azure_blob_storage_zero_copy_replication #44862
- test_merge_tree_s3_restore/test.py::test_restore_without_detached[True-True] #44928
