### PR TITLE
Fix TSAN error in ParquetV3BlockInputFormat::onCancel

### LINKED ISSUE #92299: ThreadSanitizer: data race (STID: 3680-3680)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: ThreadSanitizer: data race (STID: 3680-3680)
CI report: [Stress test (azure, amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=41975d20cb2c60a2798281faae9b5566ea849a62&name_0=MasterCI&name_1=Stress%20test%20%28azure%2C%20amd_tsan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdUaHJlYWRTYW5pdGl6ZXI6IGRhdGEgcmFjZSAoU1RJRDogMzY4MC0zNjgwKScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0cmVzcyB0ZXN0IChhenVyZSwgYW1kX3RzYW4pJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
Error:
WARNING: ThreadSanitizer: data race (pid=4297)
  Read of size 1 at 0x7290003dde98 by thread T900 (mutexes: write M0, write M1):
---

Stack trace:
#0 std::__1::__optional_storage_base<DB::Parquet::ReadManager, false>::has_value[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/optional:361:82 (clickhouse+0x2665d85d) (Build...
#1 std::__1::optional<DB::Parquet::ReadManager>::operator bool[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/optional:825:84 (clickhouse+0x2665d85d)
#2 DB::ParquetV3BlockInputFormat::onCancel() ci/tmp/build/./src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp:140:9 (clickhouse+0x2665d85d)
#3 DB::IProcessor::cancel() ci/tmp/build/./src/Processors/IProcessor.cpp:73:5 (clickhouse+0x2636d73c) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#4 DB::ExecutingGraph::cancel(bool) ci/tmp/build/./src/Processors/Executors/ExecutingGraph.cpp:421:32 (clickhouse+0x26392a36) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#5 DB::PipelineExecutor::cancel(DB::PipelineExecutor::ExecutionStatus) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:104:12 (clickhouse+0x263878fe) (BuildId: 95fc8369c3c4eaf9082ec7cbe11...
#6 DB::PipelineExecutor::executeImpl(unsigned long, bool) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:609:9 (clickhouse+0x26388208) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#7 DB::PipelineExecutor::execute(unsigned long, bool) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:136:9 (clickhouse+0x26387b69) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#8 DB::CompletedPipelineExecutor::execute() ci/tmp/build/./src/Processors/Executors/CompletedPipelineExecutor.cpp:105:18 (clickhouse+0x263860ca) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#9 DB::executeQuery(std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer>>, DB::WriteBuffer&, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails...
#10 DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned l...
#11 DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) ci/tmp/build/./src/Server/HTTPHandler.cpp:758:9 (click...
#12 DB::HTTPServerConnection::run() ci/tmp/build/./src/Server/HTTP/HTTPServerConnection.cpp:105:34 (clickhouse+0x26235f81) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#13 Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3 (clickhouse+0x2ebc61a2) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#14 Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38 (clickhouse+0x2ebc6ac1) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#15 Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14 (clickhouse+0x2eb28a90) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#16 Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x2eb26b6f) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
#17 Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:341:27 (clickhouse+0x2eb24e09) (BuildId: 95fc8369c3c4eaf9082ec7cbe11ef764d9abffda)
```

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/92299

(I didn't reproduce it.)

### Version info
- Merged into: `26.1.1.643`

### CODE REVIEW

File: src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp [hunk 1]
```diff
@@ -137,13 +140,17 @@ const BlockMissingValues * ParquetV3BlockInputFormat::getMissingValues() const
 
 void ParquetV3BlockInputFormat::onCancel() noexcept
 {
+    std::unique_lock lock(reader_mutex);
```
Comment (scanhex12) [inline src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp]: lock_guard

**Review by scanhex12 — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@al13n321, you meant TSan, not UBSan.

File: src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp (hunk 1 above)
Comment (alexey-milovidov) [inline src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp]:
```suggestion
    std::lock_guard lock(reader_mutex);
```

File: src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp [hunk 2]
```diff
@@ -137,13 +140,17 @@ const BlockMissingValues * ParquetV3BlockInputFormat::getMissingValues() const
...
+    std::lock_guard lock(reader_mutex);
     if (reader)
         reader->cancel();
 }
 
 void ParquetV3BlockInputFormat::resetParser()
 {
-    reader.reset();
+    {
+        std::unique_lock lock(reader_mutex);
```
Comment (alexey-milovidov) [inline src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp]:
```suggestion
        std::lock_guard lock(reader_mutex);
```

File: src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp [hunk 3]
```diff
@@ -90,10 +90,13 @@ void ParquetV3BlockInputFormat::initializeIfNeeded()
                 parser_shared_resources->opaque = ext;
             });
 
-        reader.emplace();
-        reader->reader.prefetcher.init(in, read_options, parser_shared_resources);
-        reader->reader.init(read_options, getPort().getHeader(), format_filter_info);
-        reader->init(parser_shared_resources, buckets_to_read ? std::optional(buckets_to_read->row_group_ids) : std::nullopt);
+        {
+            std::unique_lock lock(reader_mutex);
```
Comment (alexey-milovidov) [inline src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp]:
```suggestion
            std::lock_guard lock(reader_mutex);
```
