### PR TITLE
Fix CREATE AS for ReplicatedMergeTree with default arguments

### LINKED ISSUE #35577: RENAME + CREATE AS fails on replicated
**Describe what's wrong**

Renaming a table, followed by a create as fails for a replicated database. For example:

1. Create a database
  ```
  CREATE DATABASE imdb
  ENGINE = Replicated('/clickhouse/databases/{shard}', '{shard}', '{replica}')
  ```

2. Create replicated table

```
CREATE TABLE imdb.movie_directors
(
    `director_id` UInt64,
    `movie_id` UInt64
)
ENGINE = ReplicatedMergeTree
ORDER BY (director_id, movie_id)
SETTINGS index_granularity = 8192;
```

3. Rename the table

```
RENAME table movie_directors TO movie_directors_old;
```

3. Attempt to create a new table using the schema of the old
```
CREATE TABLE default.movie_directors AS default.movie_directors_old;
```

Throws error

```
Code: 253. DB::Exception: Replica /clickhouse/tables/56b41aa1-8a01-4958-b56e-61798988d496/default/replicas/c-gracious-morse-39-server-2 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.3.1.1)
default
```

**Does it reproduce on recent release?**

Tested on 22.3.1.1

**How to reproduce**

See above

**Expected behavior**

I'd expect the 2nd creation to work.

**Additional context**

Reproducible in ClickHouse Cloud on default db.

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`CREATE TABLE ... AS` might fail with `Replica ... already exists` even if `ReplicatedMergeTree` table was created with default arguments. It's fixed. Now `{uuid}` macro is not unfolded when saving table metadata. Therefore, it's not allowed to move `ReplicatedMergeTree` table from `Atomic` to `Ordinary` database if `zookeeper_path` contains `{uuid}` macro (or table was created with default engine arguments). Fixes #35577.

### CODE REVIEW

File: src/Databases/DatabaseReplicated.h [hunk 1]
```diff
@@ -107,6 +112,7 @@ class DatabaseReplicated : public DatabaseAtomic
     zkutil::ZooKeeperPtr getZooKeeper() const;
 
     std::atomic_bool is_readonly = true;
+    bool is_recovering = false;
```
Comment (antonio2368) [inline src/Databases/DatabaseReplicated.h:115]: Shouldn't this be atomic also?
Recovery is done in a DDLWorker thread, while the check `allowMoveTableToOtherDatabaseEngine` is called on rename.

**Review by antonio2368 — APPROVED** [review]

**Comment by tavplubix** [comment]
Stress test (thread, actions) - `Hung check failed` - actually it was segfault without stacktrace - #35985
