### PR TITLE
Some improvements and fixes for Bool data type

### LINKED ISSUE #33244: Поддержка типа Bool
Запрос:
```
SELECT
  toTypeName(true),
  toTypeName(if(1=1,true,false))
```
возвращает значения UInt8 UInt8 вместо ожидаемых Bool Bool

В релизе 21.12.3.32 поддержка типа Bool анонсирована,
но перейти в запросе к типу Bool нельзя.
Например, если необходимо вывести явно тип в формате 
TSVWithNamesAndTypes.

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add some improvements and fixes for Bool data type. Fixes https://github.com/ClickHouse/ClickHouse/issues/33244

Detailed description / Documentation draft:
- Parse literals `true`/`false` as `Bool`, not as `UInt8`.
- Output values with `Bool` type as `true`/`false`, not as `1`/`0`.
- Make the result type of functions `not`, `and`, `or`, `xor` type `Bool` if at least one of arguments is `Bool`
- Add function `toBool`.
- Fix bug in casting to `Bool` type when big numbers were casted to `false`.

### CODE REVIEW

**Comment by qoega** [comment]
This one is backward incompatible?

File: src/Core/Field.h [hunk 1]
```diff
@@ -580,6 +592,11 @@ class Field
             case Types::Array:   return f(field.template get<Array>());
             case Types::Tuple:   return f(field.template get<Tuple>());
             case Types::Map:     return f(field.template get<Map>());
+            case Types::Bool:
+            {
+                bool value = bool(field.template get<UInt64>());
+                return f(value);
+            }
```
Comment (vdimir) [inline src/Core/Field.h:599]: I'd write single line as in other cases, but actually up to you.
```suggestion
            case Types::Bool: return f(static_cast<bool>(field.template get<UInt64>()));
```

**Review by vdimir — APPROVED** [review]
The only question in that formatting is not compatible with old version (and test are broken). Can we handle it without another one setting or not?

File: src/Core/Field.h (hunk 1 above)
Comment (Avogar) [reply src/Core/Field.h:599]: Couldn't write it like that, because there are cases when `f` accepts value by non const reference. But I think It would be better to change that places to const reference. Will do it

**Comment by Avogar** [comment]
> The only question in that formatting is not compatible with old version (and test are broken). Can we handle it without another one setting or not?
I asked @alexey-milovidov what he thinks about it, let's see what he says. I think we can mark this PR as backward incompatible change and just change all tests, but I'm not sure about it.

File: src/Core/Field.h (hunk 1 above)
Comment (Avogar) [reply src/Core/Field.h:599]: UPD: can't change all places to const reference, because some of them change the value (for example FieldVisitorSum)

**Comment by Avogar** [comment]
We decided to make the result of logical functions `Bool` only when one of the arguments is `Bool`. It won't break anything, because `Bool` type was added quite recently.
