### PR TITLE
Fix vertical merges in wide parts

### LINKED ISSUE #36687: 22.4 Vertical merges of wide parts are broken
Vertical merges of wide parts fail if there is an array in the table and not all columns are present in parts.
```sql
CREATE TABLE aaa 
(
  a   Array(Int16),
  b   Int8
)
ENGINE = MergeTree
ORDER BY tuple() 
settings
    vertical_merge_algorithm_min_columns_to_activate=1,
    vertical_merge_algorithm_min_rows_to_activate=1,
    min_bytes_for_wide_part=0;

insert into aaa select [], 0;
alter table aaa clear column b;

optimize table aaa final;

Received exception from server (version 22.4.2):
Code: 16. DB::Exception: Received from localhost:9000. 
DB::Exception: There is no column a.size0 in table. (NO_SUCH_COLUMN_IN_TABLE)
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix vertical merges in wide parts. Previously an exception `There is no column` can be thrown during merge.

Fixes #36687.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeSequentialSource.cpp [hunk 1]
```diff
@@ -41,7 +41,8 @@ MergeTreeSequentialSource::MergeTreeSequentialSource(
     addTotalRowsApprox(data_part->rows_count);
 
     /// Add columns because we don't want to read empty blocks
-    injectRequiredColumns(storage, storage_snapshot, data_part, columns_to_read);
+    injectRequiredColumns(storage, storage_snapshot, data_part, /*with_subcolumns=*/ false, columns_to_read);
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeSequentialSource.cpp:44]: Do I understand correctly that this is the most imprtant line?
Maybe add a comment explaining - why we should not inject subcolumns as required columns here?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
You can also pull this test: #36706
So when we will merge this PR, the other PR will be automatically merged.

File: src/Storages/MergeTree/MergeTreeSequentialSource.cpp (hunk 1 above)
Comment (CurtizJ) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:44]: Yes. I can add a comment. 

Actually the problem is not exactly that we shouldn't require subcolumns, because we will read only columns for requested  names and there are no subcolumns. But subcolumn can be added as the smallest column in case when all requested columns are missing.

**Comment by CurtizJ** [comment]
I've already added tests from #36706. If it's not important to keep the authorship of commits, we can close it.
