### PR TITLE
Analyzer: Storage Join support joining with nullable columns

### LINKED ISSUE #61247: StorageJoin is not utilized when there are multiple joins
**Describe the situation**
When there are multiple joins, storage join is not utilised even if it's in the right hand side of the join and joining key match.

**How to reproduce**
Fact table:
```sql
CREATE TABLE default.tab
(
    `k1` Nullable(UInt64),
    `k2` Nullable(UInt64),
    `v` String
)
ENGINE = Memory;
```

Join table:
```sql
CREATE TABLE default.mem
(
    `k` UInt64,
    `v` String
)
ENGINE = Join(ANY, LEFT, k)
```

1. Non-analyzer:

```sql
EXPLAIN PIPELINE
SELECT *
FROM tab
ANY LEFT JOIN mem ON k1 = mem.k
ANY LEFT JOIN mem AS t ON k2 = t.k

Query id: 30ff1f46-8e45-4a05-9815-32c991617afc

┌─explain───────────────────────────┐
│ (Expression)                      │
│ ExpressionTransform               │
│   (Join)                          │
│   JoiningTransform 2 → 1          │
│     (Expression)                  │
│     ExpressionTransform           │
│       (FilledJoin)                │
│       JoiningTransform            │
│         (Expression)              │
│         ExpressionTransform       │
│           (ReadFromMemoryStorage) │
│     (Expression)                  │
│     FillingRightJoinSide          │
│       Resize 128 → 1              │
│         ExpressionTransform × 128 │
│           (ReadFromStorage)       │
│           Resize 1 → 128          │
│             Join 0 → 1            │
└───────────────────────────────────┘
```

Note that in the second join, we need to alias `mem` because old analyzer cannot resolve column names. In the second join, it's building hash join again from join table, which is not optimal.

2. Analyzer

New analyzer is good, it can resolve column names and we, but it doesn't allow converting join key from non-nullable -> nullable.

```sql
EXPLAIN PIPELINE
SELECT *
FROM tab
ANY LEFT JOIN mem ON k1 = mem.k
ANY LEFT JOIN mem ON k2 = mem.k
SETTINGS allow_experimental_analyzer =1

Query id: 7addb722-0063-4e5f-b04a-d1b8efb79fc9


Elapsed: 0.002 sec.

Received exception from server (version 24.2.1):
Code: 264. DB::Exception: Received from localhost:9100. DB::Exception: JOIN with 'Join' table engine should be performed by storage keys [k], but column '_CAST(__table2.k, 'Nullable(UInt64)'_String)' was found. (INCOMPATIBLE_TYPE_OF_JOIN)
```

**Expected performance**

Storage join can be utilised in both old and new analyzer.

**Additional context**

When removing nullable from fact table, new analyzer works perfectly 👍 

```sql
CREATE TABLE default.tab
(
    `k1` Nullable(UInt64),
    `k2` Nullable(UInt64),
    `v` String
)
ENGINE = Memory;

EXPLAIN PIPELINE
SELECT *
FROM tab
ANY LEFT JOIN mem ON k1 = mem.k
ANY LEFT JOIN mem AS t ON k2 = t.k
SETTINGS allow_experimental_analyzer =1

Query id: c037244f-2550-4b3d-96c4-6dff151aa8e9

┌─explain───────────────────────────┐
│ (Expression)                      │
│ ExpressionTransform               │
│   (FilledJoin)                    │
│   JoiningTransform                │
│     (Expression)                  │
│     ExpressionTransform           │
│       (FilledJoin)                │
│       JoiningTransform            │
│         (Expression)              │
│         ExpressionTransform       │
│           (ReadFromMemoryStorage) │
└───────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Storage Join support for nullable columns in left table, close https://github.com/ClickHouse/ClickHouse/issues/61247

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 383221b04d57948364514106b2f48b03140bfbd0 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66926/383221b04d57948364514106b2f48b03140bfbd0/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/91693daf599bbaeaed5adb8cba257c176628e2be/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Planner/PlannerJoins.cpp [hunk 1]
```diff
@@ -561,7 +567,7 @@ JoinClausesAndActions buildJoinClausesAndActions(
                 if (!left_key_node->result_type->equals(*common_type))
                     left_key_node = &left_join_actions->addCast(*left_key_node, common_type, {});
 
-                if (!right_key_node->result_type->equals(*common_type))
+                if (!is_join_with_special_storage && !right_key_node->result_type->equals(*common_type))
```
Comment (novikd) [inline src/Planner/PlannerJoins.cpp:570]: Is it okay not to do type conversion? Maybe it's better to add an alias after adding a cast.

Comment (vdimir) [reply src/Planner/PlannerJoins.cpp:570]: If types are `Nullable(T)` and `T` it's alright, HashJoin handles it. For the case for example `UInt64` and `UInt32` HashJoin will throw exception about type mismatch, and it should be expected, because StorageJoin has nothing to do with it and should not rebuild prepared hash-table (alright, we might always covert left table column to right table type handling values that cannot be converting e.g. with accurateCastOrNull, but it's more generic solution, that is not implemented yet).

**Comment by vdimir** [comment]
> Integration tests (tsan) [5/6] — fail: 1, passed: 603 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66926/383221b04d57948364514106b2f48b03140bfbd0/integration_tests__tsan__[5_6].html)

https://github.com/ClickHouse/ClickHouse/issues/67102

**Review by novikd — APPROVED** [review]
Let's merge when CI passes

**Comment by vdimir** [comment]
> Fast test — Some queries hung, fail: 1, passed: 5638, skipped: 1201 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66926/d24fe7c7a3084afb7d8ad800180e70d8b47427dd/fast_test.html)

`DROP DATABASE` hung https://github.com/ClickHouse/ClickHouse/issues/66044

**Comment by vdimir** [comment]
> Integration tests (asan, old analyzer) [5/6] — fail: 4, passed: 611 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66926/1c0a09a98a4b082798637f4e9b7f39f1ad97ad2d/integration_tests__asan__old_analyzer__[5_6].html)

Fixed in https://github.com/ClickHouse/ClickHouse/pull/67590

**Comment by vdimir** [comment]
> Upgrade check (debug) — Changed settings are not reflected in settings changes history (see changed_settings.txt) 

https://github.com/ClickHouse/ClickHouse/pull/67524


> Performance Comparison (release) [1/4] — 4 errors, 4 too long, 5 unstable [Details](https://s3.amazonaws.com/clickhouse-test-reports/66926/7e0be5b48d16186f89ed0f6f891f4bcc858a8cfb/performance_comparison__release__[1_4]/report.html)

I need to continue https://github.com/ClickHouse/ClickHouse/issues/66978

**Comment by novikd** [comment]
Requires to merge with master again.

**Comment by clickgapai** [comment]
Hi @vdimir @novikd — while reviewing this PR I found the following:

- **Bug (P2):** `StorageJoin` cast skipping in `buildJoinClausesAndActions` fails when `StorageJoin` has smaller type than left table — https://github.com/ClickHouse/ClickHouse/issues/104918

Happy to discuss — close anything that's wrong or already addressed.
