### PR TITLE
Fix a bug in `Map` data type

### LINKED ISSUE #46855: MSan report in ColumnUnique (LowCardinality)
**How to reproduce**
```
milovidov-desktop :) SET allow_suspicious_low_cardinality_types = 1

SET allow_suspicious_low_cardinality_types = 1

Query id: 74086d0f-0d7c-4ef1-beee-dfa586bd712f

Ok.

0 rows in set. Elapsed: 0.003 sec. 

milovidov-desktop :) CREATE TEMPORARY TABLE datetime__fuzz_14 (`d` LowCardinality(Nullable(UInt128)));

CREATE TEMPORARY TABLE datetime__fuzz_14
(
    `d` LowCardinality(Nullable(UInt128))
)

Query id: 5d8fc3d3-39cf-44cb-ae40-3161fbaf0263

Ok.

0 rows in set. Elapsed: 0.004 sec. 

milovidov-desktop :) SELECT max(mapPopulateSeries(mapPopulateSeries(map(toInt64(1048575), toInt64(9223372036854775806), 3, -2147483649))), toInt64(1048575), map('11', 257, '', NULL), cityHash64(*)) > NULL FROM (SELECT max(cityHash64(mapPopulateSeries(mapPopulateSeries(map(toInt64(1048575), toInt64(2147483646), 65537, -2147483649))), *)) > NULL, map(toInt64(-2147483647), toInt64(100.0001), -2147483647, NULL), mapPopulateSeries(map(toInt64(1024), toInt64(1048576), 1048575, -1)), map(toInt64(256), toInt64(NULL), -1, NULL), quantile(0.0001)(d) FROM datetime__fuzz_14 WITH TOTALS)

SELECT max(mapPopulateSeries(mapPopulateSeries(map(toInt64(1048575), toInt64(9223372036854775806), 3, -2147483649))), toInt64(1048575), map('11', 257, '', NULL), cityHash64(*)) > NULL
FROM
(
    SELECT
        max(cityHash64(mapPopulateSeries(mapPopulateSeries(map(toInt64(1048575), toInt64(2147483646), 65537, -2147483649))), *)) > NULL,
        map(toInt64(-2147483647), toInt64(100.0001), -2147483647, NULL),
        mapPopulateSeries(map(toInt64(1024), toInt64(1048576), 1048575, -1)),
        map(toInt64(256), toInt64(NULL), -1, NULL),
        quantile(0.0001)(d)
    FROM datetime__fuzz_14
        WITH TOTALS
)
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug in the `Map` data type. This closes #46855.

### CODE REVIEW

File: src/Functions/FunctionsHashing.h [hunk 1]
```diff
@@ -1343,10 +1347,9 @@ class FunctionAnyHash : public IFunction
             const auto & type_map = assert_cast<const DataTypeMap &>(*type);
             executeForArgument(key, type_map.getNestedType().get(), map->getNestedColumnPtr().get(), vec_to, is_first);
         }
-        else if (const auto * const_map = checkAndGetColumnConstData<ColumnMap>(column))
+        else if (const auto * const_map = checkAndGetColumnConst<ColumnMap>(column))
         {
-            const auto & type_map = assert_cast<const DataTypeMap &>(*type);
-            executeForArgument(key, type_map.getNestedType().get(), const_map->getNestedColumnPtr().get(), vec_to, is_first);
```
Comment (alexey-milovidov) [inline src/Functions/FunctionsHashing.h:1349]: The bug was here.

**Review by davenger — APPROVED** [review]
