### PR TITLE
Revert invalid RegExpTreeDictionary optimization

### LINKED ISSUE #50641: RegExpTree dictionary lookup misses values in some cases
**Describe what's wrong**

Under specific circumstances, values are missing from `dictGet` output from a RegExpTree dictionary. For example:

```yaml
# regexp_tree.yaml
- regexp: '(?i)clickhouse\.com'
  tag: 'ClickHouse'
  children:
    - regexp: '(?i)clickhouse\.com/docs'
      tag: 'ClickHouse Documentation'
```

```sql
CREATE DICTIONARY regexp_dict
(
    regexp String,
    tag String
)
PRIMARY KEY(regexp)
SOURCE(YAMLRegExpTree(PATH '/var/lib/clickhouse/user_files/regexp_tree.yaml'))
LIFETIME(0)
LAYOUT(regexp_tree);

SELECT dictGet('regexp_dict', 'tag', 'clickhouse.com/docs');
```
```
┌─dictGet('regexp_dict', 'tag', 'clickhouse.com/docs')─┐
│                                                       │
└───────────────────────────────────────────────────────┘
```

This also affects the newly added `dictGetAll`, in the same way.

```sql
SELECT dictGetAll('regexp_dict', 'tag', 'clickhouse.com/docs');
```
```
┌─dictGetAll('regexp_dict', 'tag', 'clickhouse.com/docs')─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
```

[Fiddle repro](https://fiddle.clickhouse.com/38758875-b2ac-40ff-bc76-7a47b6f46daf). See below for more details.

**Does it reproduce on recent release?**

Repros on 23.4 and 23.3.

**How to reproduce**

* Create a RegExpTree dictionary with any level of nesting, prefixing all regular expressions with `(?i)` to enable case-insensitive mode. Alternatively, set `regexp_dict_allow_hyperscan=false`.
* Call `dictGet` with a key that validly matches one of the leaf nodes.
* Observe an empty return value.

**Expected behavior**
`dictGet` returns the attribute value at the leaf node.

**Additional context**

This is specifically caused by a faulty optimization introduced in https://github.com/ClickHouse/ClickHouse/pull/46822. The issue is the result of multiple interacting factors.

ClickHouse will [sequentially scan patterns using RE2](https://github.com/ClickHouse/ClickHouse/blob/5af18191434085c07e2e95174177a904b73edbf8/src/Dictionaries/RegExpTreeDictionary.cpp#L689) instead of Vectorscan in a few circumstances:

- It was compiled without Vectorscan
- The dictionary had `regexp_dict_allow_hyperscan=false`
- The pattern itself was deemed "complex" after analysis. For example, any pattern containing the `(?i)` mode flag will be marked as "complex".

In these cases, there's an attempted optimization to [break from the loop early if a matching leaf node containing the requested attributes is found](https://github.com/ClickHouse/ClickHouse/blob/5af18191434085c07e2e95174177a904b73edbf8/src/Dictionaries/RegExpTreeDictionary.cpp#L694). However, a matching node might still be discarded later if [its parent node wasn't also added to the list of matches](https://github.com/ClickHouse/ClickHouse/blob/5af18191434085c07e2e95174177a904b73edbf8/src/Dictionaries/RegExpTreeDictionary.cpp#L705). Within the scan loop we have some problems:
- (Easily fixable) There's no guarantee that a leaf node's parent node will have been scanned before it and added to the list of matches, which means the `is_valid` check will discard that leaf node before yielding its value. This could be fixed by just sorting `complex_regexp_nodes`. It would be slightly harder to make this work with `dictGetAll`, since we can't just break on the first match regardless.
- (Not easily fixable) In general, there's no way to tell whether a matching leaf node is a "false positive" without doing something complicated like checking whether all a child node's parent matched before breaking. Especially since `complex_regexp_nodes` only contains a subset of all the tree nodes, with others instead scanned via `hs_scan`. For example, suppose we have the following tree:
   ```yaml
   - regexp: 'clickhouse\.com'
     tag: 'ClickHouse'
     children:
       - regexp: '(?i)docs'
         tag: 'ClickHouse Documentation'
   - regexp: '(?i)/docs'
      tag: 'Documentation'
   ```
   One would expect `dictGet('regexp_dict', 'tag', '/docs')` to return `Documentation`. The `(?i)docs` would be marked as "complex", and is a leaf node that fully matches the `/docs` string, but we would need to recognize that its parent node `clickhouse\.com` (which is a "simple" pattern handled by `hs_scan`) was not a match so as _not_ to break out of the loop before scanning the other complex pattern `(?i)/docs`.

For the second reason especially, I think the best solution might just be to remove this faulty optimization entirely. IMO, it  seems like it maybe isn't worth the complication for what seems like a somewhat minor optimization on `complex_regexp_nodes`, which presumably would be small-ish in most normal cases.

### PR DESCRIPTION
**Pull request by johanngan**
Fixes https://github.com/ClickHouse/ClickHouse/issues/50641 by reverting the changes from https://github.com/ClickHouse/ClickHouse/pull/46822. Additionally, functional tests are added.

When scanning complex regexp nodes sequentially with RE2, the old code has an optimization to break out of the loop early upon finding a leaf node that matches. This is an invalid optimization because there's no guarantee that it's actually a VALID match, because its parents might NOT have matched. Semantically, a user would expect this match to be discarded and for the search to continue. Instead, since we skipped matching after the first false positive, subsequent nodes that would have matched are missing from the output value. This affects both dictGet and dictGetAll.

It's difficult to distinguish a true positive from a false positive while looping through complex_regexp_nodes because we would have to scan all the parents of a matching node to confirm a true positive. Trying to do this might actually end up being slower than just scanning every complex regexp node, because complex_regexp_nodes is only a subset of all the tree nodes; we may end up duplicating work with scanning that Vectorscan has already done, depending on whether the parent nodes are "simple" or "complex". So instead of trying to fix this optimization, just remove it entirely.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed a bug causing RegExpTree dictionary lookups to be missing values in some cases.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: tests/queries/0_stateless/02504_regexp_dictionary_yaml_source.sh [hunk 1]
```diff
@@ -175,6 +175,70 @@ select dictGetAll('regexp_dict3', ('tag', 'topological_index', 'captured', 'pare
...
+SETTINGS(regexp_dict_allow_hyperscan = false);
+
+select dictGet('regexp_dict3', 'tag', 'clickhouse.com');
+select dictGetAll('regexp_dict3', 'tag', 'clickhouse.com');
+select dictGet('regexp_dict3', 'tag', 'clickhouse.com/docs');
+select dictGetAll('regexp_dict3', 'tag', 'clickhouse.com/docs');
+select dictGet('regexp_dict3', 'tag', 'docs.github.com');
+select dictGetAll('regexp_dict3', 'tag', 'docs.github.com');
+select dictGet('regexp_dict3', 'tag', '/docs');
+select dictGetAll('regexp_dict3', 'tag', '/docs');
```
Comment (johanngan) [inline tests/queries/0_stateless/02504_regexp_dictionary_yaml_source.sh:239]: For reference, when I run this test on the old version, I get:

```
ClickHouse
['ClickHouse']

[]

[]

[]
```

Instead of the expected 
```
ClickHouse
['ClickHouse']
ClickHouse Documentation
['ClickHouse Documentation','ClickHouse','Documentation']
GitHub Documentation
['GitHub Documentation','GitHub']
Documentation
['Documentation']
```

**Comment by johanngan** [comment]
@hanfei1991 Kind of a followup to https://github.com/ClickHouse/ClickHouse/pull/50255 since it affects `dictGetAll`, but also just a general bugfix since it was already affecting `dictGet` in 23.3 and 23.4. Deleting the optimization seems like the simplest thing to do, but maybe there's a smarter solution that I'm not seeing.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit be8e0487994d70c3c6350cb675475b12dffda8e5 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50642/be8e0487994d70c3c6350cb675475b12dffda8e5/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by hanfei1991 — APPROVED** [review]
