### PR TITLE
Fix fatal using approx-top-k issue 86882

### LINKED ISSUE #86882: Fatal using approx_top_k and finalizeAggregation
### Company or project name

_No response_

### Describe what's wrong

Fatal on this example https://fiddle.clickhouse.com/a294579c-66f0-4170-8810-4c99ad7602ab

### Does it reproduce on the most recent release?

Yes

### How to reproduce

https://fiddle.clickhouse.com/a294579c-66f0-4170-8810-4c99ad7602ab

### Expected behavior

_No response_

### Error message and/or stacktrace

```
012A0300000000000000030000000000000043434303000000000000004141410400000000000000414141410100800200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

[b21ffff1e365] 2025.09.09 11:44:13.035127 [ 85 ] <Fatal> BaseDaemon: ########################################
[b21ffff1e365] 2025.09.09 11:44:13.035339 [ 85 ] <Fatal> BaseDaemon: (version 25.8.2.29 (official build), build id: D184451B72176B2935BBC1C0474CD16A6A21CB52, git hash: 874146507b059896a7ca4ca257ee847fe05dbe05) (from thread 87) (query_id: 76a47ba7-a29e-4c7b-a25f-726fc0cc7dff) (query: select finalizeAggregation(CAST(unhex('012A0300000000000000030000000000000043434303000000000000004141410400000000000000414141410100800200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'AggregateFunction(approx_top_k(3), Array(Array(String)))'))) Received signal Segmentation fault (11)
[b21ffff1e365] 2025.09.09 11:44:13.035476 [ 85 ] <Fatal> BaseDaemon: Address: 0x79bb14a00000. Access: read. Address not mapped to object.
[b21ffff1e365] 2025.09.09 11:44:13.035605 [ 85 ] <Fatal> BaseDaemon: Stack trace: 0x000000000c845d08 0x00000000186d7080 0x00000000185dd230 0x00000000185dd230 0x0000000014edb190 0x00000000185d522a 0x000000000eba1b18 0x000000000c84d28a 0x0000000015fcddfa 0x0000000015fc6438 0x0000000015fc61f8 0x0000000015fc78de 0x0000000015fc8c7b 0x00000000173d29be 0x00000000173b21bd 0x00000000173b1634 0x00000000173e95e7 0x00000000173a812e 0x00000000173a5a24 0x00000000173a5044 0x000000001740ebf6 0x0000000017f636cd 0x0000000017f6161c 0x0000000017f64ca2 0x0000000017ed64eb 0x000000001832c147 0x000000001832668b 0x00000000199e5b54 0x0000000019a07718 0x000000001ef1e687 0x000000001ef1eb19 0x000000001eee5147 0x000000001eee3541 0x000079bc7ecfbac3 0x000079bc7ed8ca04
[b21ffff1e365] 2025.09.09 11:44:13.035766 [ 85 ] <Fatal> BaseDaemon: 2. memcpy @ 0x000000000c845d08
[b21ffff1e365] 2025.09.09 11:44:13.035961 [ 85 ] <Fatal> BaseDaemon: 3. DB::ColumnString::deserializeAndInsertFromArena(char const*) @ 0x00000000186d7080
[b21ffff1e365] 2025.09.09 11:44:13.036112 [ 85 ] <Fatal> BaseDaemon: 4. DB::ColumnArray::deserializeAndInsertFromArena(char const*) @ 0x00000000185dd230
[b21ffff1e365] 2025.09.09 11:44:13.036246 [ 85 ] <Fatal> BaseDaemon: 5. DB::ColumnArray::deserializeAndInsertFromArena(char const*) @ 0x00000000185dd230
[b21ffff1e365] 2025.09.09 11:44:13.036357 [ 85 ] <Fatal> BaseDaemon: 6. DB::(anonymous namespace)::AggregateFunctionTopKGeneric<false, false>::insertResultInto(char*, DB::IColumn&, DB::Arena*) const (.af55b01932afbb36d3f0f9552790a9bd) @ 0x0000000014edb190
[b21ffff1e365] 2025.09.09 11:44:13.036541 [ 85 ] <Fatal> BaseDaemon: 7. DB::ColumnAggregateFunction::convertToValues(COW<DB::IColumn>::mutable_ptr<DB::IColumn>) @ 0x00000000185d522a
[b21ffff1e365] 2025.09.09 11:44:13.036700 [ 85 ] <Fatal> BaseDaemon: 8. DB::(anonymous namespace)::FunctionFinalizeAggregation::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000eba1b18
[b21ffff1e365] 2025.09.09 11:44:13.036859 [ 85 ] <Fatal> BaseDaemon: 9. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000c84d28a
[b21ffff1e365] 2025.09.09 11:44:13.037019 [ 85 ] <Fatal> BaseDaemon: 10. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000015fcddfa
[b21ffff1e365] 2025.09.09 11:44:13.037170 [ 85 ] <Fatal> BaseDaemon: 11. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000015fc6438
[b21ffff1e365] 2025.09.09 11:44:13.037322 [ 85 ] <Fatal> BaseDaemon: 12. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000015fc61f8
[b21ffff1e365] 2025.09.09 11:44:13.037446 [ 85 ] <Fatal> BaseDaemon: 13. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000015fc78de
[b21ffff1e365] 2025.09.09 11:44:13.037602 [ 85 ] <Fatal> BaseDaemon: 14. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000015fc8c7b
[b21ffff1e365] 2025.09.09 11:44:13.037773 [ 85 ] <Fatal> BaseDaemon: 15. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000173d29be
[b21ffff1e365] 2025.09.09 11:44:13.037953 [ 85 ] <Fatal> BaseDaemon: 16. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x00000000173b21bd
[b21ffff1e365] 2025.09.09 11:44:13.038071 [ 85 ] <Fatal> BaseDaemon: 17. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x00000000173b1634
[b21ffff1e365] 2025.09.09 11:44:13.038144 [ 85 ] <Fatal> BaseDaemon: 18. DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000173e95e7
[b21ffff1e365] 2025.09.09 11:44:13.038262 [ 85 ] <Fatal> BaseDaemon: 19. DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x00000000173a812e
[b21ffff1e365] 2025.09.09 11:44:13.038393 [ 85 ] <Fatal> BaseDaemon: 20. DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x00000000173a5a24
[b21ffff1e365] 2025.09.09 11:44:13.038445 [ 85 ] <Fatal> BaseDaemon: 21. DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x00000000173a5044
[b21ffff1e365] 2025.09.09 11:44:13.038522 [ 85 ] <Fatal> BaseDaemon: 22. DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x000000001740ebf6
[b21ffff1e365] 2025.09.09 11:44:13.038580 [ 85 ] <Fatal> BaseDaemon: 23. DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) (.llvm.6832786340529785429) @ 0x0000000017f636cd
[b21ffff1e365] 2025.09.09 11:44:13.038648 [ 85 ] <Fatal> BaseDaemon: 24. DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000017f6161c
[b21ffff1e365] 2025.09.09 11:44:13.038707 [ 85 ] <Fatal> BaseDaemon: 25. std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__function::__policy_invoker<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) (.llvm.6832786340529785429) @ 0x0000000017f64ca2
[b21ffff1e365] 2025.09.09 11:44:13.038789 [ 85 ] <Fatal> BaseDaemon: 26. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000017ed64eb
[b21ffff1e365] 2025.09.09 11:44:13.038854 [ 85 ] <Fatal> BaseDaemon: 27. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001832c147
[b21ffff1e365] 2025.09.09 11:44:13.038932 [ 85 ] <Fatal> BaseDaemon: 28. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001832668b
[b21ffff1e365] 2025.09.09 11:44:13.038997 [ 85 ] <Fatal> BaseDaemon: 29. DB::TCPHandler::runImpl() @ 0x00000000199e5b54
[b21ffff1e365] 2025.09.09 11:44:13.039052 [ 85 ] <Fatal> BaseDaemon: 30. DB::TCPHandler::run() @ 0x0000000019a07718
[b21ffff1e365] 2025.09.09 11:44:13.039098 [ 85 ] <Fatal> BaseDaemon: 31. Poco::Net::TCPServerConnection::start() @ 0x000000001ef1e687
[b21ffff1e365] 2025.09.09 11:44:13.039142 [ 85 ] <Fatal> BaseDaemon: 32. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef1eb19
[b21ffff1e365] 2025.09.09 11:44:13.039182 [ 85 ] <Fatal> BaseDaemon: 33. Poco::PooledThread::run() @ 0x000000001eee5147
[b21ffff1e365] 2025.09.09 11:44:13.039241 [ 85 ] <Fatal> BaseDaemon: 34. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001eee3541
[b21ffff1e365] 2025.09.09 11:44:13.039303 [ 85 ] <Fatal> BaseDaemon: 35. ? @ 0x0000000000094ac3
[b21ffff1e365] 2025.09.09 11:44:13.039356 [ 85 ] <Fatal> BaseDaemon: 36. ? @ 0x0000000000125a04
[b21ffff1e365] 2025.09.09 11:44:13.212488 [ 85 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 163960DD413D7F55F8E3C2E9EC2A8588)
[b21ffff1e365] 2025.09.09 11:44:13.391316 [ 85 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[b21ffff1e365] 2025.09.09 11:44:13.391576 [ 85 ] <Fatal> BaseDaemon: Changed settings: parallel_replicas_for_cluster_engines = false, output_format_pretty_color = 0, output_format_pretty_grid_charset = 'ASCII'
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jitendra1411**
Resolves: https://github.com/ClickHouse/ClickHouse/issues/86882
**Changelog category (leave one):**
Bug Fix (user-visible misbehavior in an official stable release)

**Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):**
Fix fatal using approx_top_k and finalizeAggregation

### CODE REVIEW

**Comment by jitendra1411** [comment]
Hi @yariks5s 
Please review the fix and let me know if any changes are required
thanks

**Review by yariks5s — APPROVED** [review]

File: tests/queries/0_stateless/03631_finalize_approx_top_k_unhex.sh [hunk 1]
```diff
@@ -0,0 +1,33 @@
+#!/usr/bin/env bash
+# Tags: no-parallel
+
+CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CURDIR"/../shell_config.sh
+
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03631_finalize_approx_top_k_unhex.sh:7]: Please put in at least a brief description or issue reference of what this test is supposed to test, otherwise every future reader will need to read and decipher the test from beginning to end.

File: src/Common/SpaceSaving.h [hunk 2]
```diff
@@ -306,13 +306,56 @@ class SpaceSaving
 
     void readAlphaMap(ReadBuffer & rb)
     {
-        size_t alpha_size = 0;
-        readVarUInt(alpha_size, rb);
-        for (size_t i = 0; i < alpha_size; ++i)
+        // Reset current alpha_map; we'll rebuild it based on serialized data, but
```
Comment (rschu1ze) [inline src/Common/SpaceSaving.h:309]: Problem 1: This PR (as a whole) needs more code comments that explain the _why_ of the changes.

Problem 2: We are relaxing the way how data is read, and we forever need to keep such code. It would be much nicer if there was a "relaxed mode" that can be turned on by a compatibility setting.

**Comment by rschu1ze** [comment]
> Fix fatal using approx_top_k and finalizeAggregation

@yariks5s @jitendra1411 Please rewrite the changelog entry so that an average ClickHouse user is able to understand it. This means: 1) add an example of a failing statement (if that exists) 2) mention when the problem was introduced (e.g. in which versions) 3) add a reference to the GitHub issue.

File: src/DataTypes/Serializations/SerializationAggregateFunction.cpp [hunk 3]
```diff
@@ -53,8 +54,21 @@ void SerializationAggregateFunction::deserializeBinary(IColumn & column, ReadBuf
     }
     catch (...)
     {
-        function->destroy(place);
-        throw;
+        // For approx_top_* states, optionally swallow malformed input and keep an empty state instead of failing CAST
+        const String & fname = function->getName();
+        const bool is_approx_top = fname.starts_with("approx_top_");
```
Comment (Algunenano) [inline src/DataTypes/Serializations/SerializationAggregateFunction.cpp:59]: This code looks like a bomb waiting to explode. We should never ignore malformed input

**Comment by Algunenano** [comment]
This PR doesn't fix one of the issues reported:

```

SELECT finalizeAggregation(CAST(unhex('012A0300000000000000030000000000000043434303000000000000004141410400000000000000414141410100800200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'AggregateFunction(topK(3), Array(Array(String)))'))

Query id: 8d04b5d3-4847-4d08-b918-eb4bae70f8c5

2025.10.08 10:56:42.048375 [ 46129 ] {} <Fatal> ClientBase: ########## Short fault info ############
2025.10.08 10:56:42.076116 [ 46129 ] {} <Fatal> ClientBase: (version 25.10.1.1953 (official build), build id: 2690AB6E1D63BEB93B82D7BF52EBED0DDE8FE5AF, git hash: eea0282b3c3c2e2c259dcb2d7b33f0c0f68e0695, architecture: x86_64) (from thread 46120) Received signal 11
2025.10.08 10:56:42.076122 [ 46129 ] {} <Fatal> ClientBase: Signal description: Segmentation fault
2025.10.08 10:56:42.076125 [ 46129 ] {} <Fatal> ClientBase: Address: 0x7f8493000000. Access: read. Address not mapped to object.
2025.10.08 10:56:42.076128 [ 46129 ] {} <Fatal> ClientBase: Stack trace: 0x000000000c71eb08 0x0000000018b1056b 0x0000000018a18c70 0x0000000018a18c70 0x00000000151fc4c8 0x0000000018a10e2a 0x000000000ebd2dd8 0x000000000c72604a 0x000000001637243a 0x000000001636a9d5 0x000000001636a7b8 0x000000001636bf1e 0x000000001636d2bb 0x0000000017a91e51 0x00000000177f5f33 0x00000000177f5300 0x0000000017819b67 0x00000000177ebc2b 0x00000000177e943a 0x00000000177e8a9c 0x000000001783d4f6 0x0000000018377acd 0x00000000183759ea 0x00000000183790e2 0x00000000182e8eae 0x000000001874b96a 0x0000000018745db3 0x0000000019cfff43 0x0000000019c676ee 0x0000000019c74483 0x0000000019c7661c 0x0000000019c7fb20 0x0000000013a8c6c3 0x000000001ef1e3e6 0x0000000013a9f105 0x000000000c7200dd 0x00007f8497027675 0x00007f8497027729 0x000000000767202e
2025.10.08 10:56:42.076130 [ 46129 ] {} <Fatal> ClientBase: ########################################
2025.10.08 10:56:42.076160 [ 46129 ] {} <Fatal> ClientBase: (version 25.10.1.1953 (official build), build id: 2690AB6E1D63BEB93B82D7BF52EBED0DDE8FE5AF, git hash: eea0282b3c3c2e2c259dcb2d7b33f0c0f68e0695) (from thread 46120) (query_id: 8d04b5d3-4847-4d08-b918-eb4bae70f8c5) (query: SELECT finalizeAggregation(CAST(unhex('012A0300000000000000030000000000000043434303000000000000004141410400000000000000414141410100800200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'AggregateFunction(topK(3), Array(Array(String)))'))) Received signal Segmentation fault (11)
2025.10.08 10:56:42.076167 [ 46129 ] {} <Fatal> ClientBase: Address: 0x7f8493000000. Access: read. Address not mapped to object.
2025.10.08 10:56:42.076171 [ 46129 ] {} <Fatal> ClientBase: Stack trace: 0x000000000c71eb08 0x0000000018b1056b 0x0000000018a18c70 0x0000000018a18c70 0x00000000151fc4c8 0x0000000018a10e2a 0x000000000ebd2dd8 0x000000000c72604a 0x000000001637243a 0x000000001636a9d5 0x000000001636a7b8 0x000000001636bf1e 0x000000001636d2bb 0x0000000017a91e51 0x00000000177f5f33 0x00000000177f5300 0x0000000017819b67 0x00000000177ebc2b 0x00000000177e943a 0x00000000177e8a9c 0x000000001783d4f6 0x0000000018377acd 0x00000000183759ea 0x00000000183790e2 0x00000000182e8eae 0x000000001874b96a 0x0000000018745db3 0x0000000019cfff43 0x0000000019c676ee 0x0000000019c74483 0x0000000019c7661c 0x0000000019c7fb20 0x0000000013a8c6c3 0x000000001ef1e3e6 0x0000000013a9f105 0x000000000c7200dd 0x00007f8497027675 0x00007f8497027729 0x000000000767202e
2025.10.08 10:56:42.076189 [ 46129 ] {} <Fatal> ClientBase: 2. memcpy @ 0x000000000c71eb08
2025.10.08 10:56:42.076211 [ 46129 ] {} <Fatal> ClientBase: 3. DB::ColumnString::deserializeAndInsertAggregationStateValueFromArena(char const*) @ 0x0000000018b1056b
2025.10.08 10:56:42.076219 [ 46129 ] {} <Fatal> ClientBase: 4. DB::ColumnArray::deserializeAndInsertAggregationStateValueFromArena(char const*) @ 0x0000000018a18c70
2025.10.08 10:56:42.076224 [ 46129 ] {} <Fatal> ClientBase: 5. DB::ColumnArray::deserializeAndInsertAggregationStateValueFromArena(char const*) @ 0x0000000018a18c70
2025.10.08 10:56:42.076238 [ 46129 ] {} <Fatal> ClientBase: 6. DB::(anonymous namespace)::AggregateFunctionTopKGeneric<false, false>::insertResultInto(char*, DB::IColumn&, DB::Arena*) const @ 0x00000000151fc4c8
2025.10.08 10:56:42.076247 [ 46129 ] {} <Fatal> ClientBase: 7. DB::ColumnAggregateFunction::convertToValues(COW<DB::IColumn>::mutable_ptr<DB::IColumn>) @ 0x0000000018a10e2a
2025.10.08 10:56:42.076261 [ 46129 ] {} <Fatal> ClientBase: 8. DB::(anonymous namespace)::FunctionFinalizeAggregation::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const (.b418c3f09e41ddf88ec68397a96e63e2) @ 0x000000000ebd2dd8
2025.10.08 10:56:42.076271 [ 46129 ] {} <Fatal> ClientBase: 9. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000c72604a
2025.10.08 10:56:42.076283 [ 46129 ] {} <Fatal> ClientBase: 10. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001637243a
2025.10.08 10:56:42.076292 [ 46129 ] {} <Fatal> ClientBase: 11. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001636a9d5
2025.10.08 10:56:42.076299 [ 46129 ] {} <Fatal> ClientBase: 12. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001636a7b8
2025.10.08 10:56:42.076305 [ 46129 ] {} <Fatal> ClientBase: 13. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001636bf1e
2025.10.08 10:56:42.076309 [ 46129 ] {} <Fatal> ClientBase: 14. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001636d2bb
2025.10.08 10:56:42.076319 [ 46129 ] {} <Fatal> ClientBase: 15. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x0000000017a91e51
2025.10.08 10:56:42.076330 [ 46129 ] {} <Fatal> ClientBase: 16. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x00000000177f5f33
2025.10.08 10:56:42.076338 [ 46129 ] {} <Fatal> ClientBase: 17. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x00000000177f5300
2025.10.08 10:56:42.076345 [ 46129 ] {} <Fatal> ClientBase: 18. DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x0000000017819b67
2025.10.08 10:56:42.076349 [ 46129 ] {} <Fatal> ClientBase: 19. DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x00000000177ebc2b
2025.10.08 10:56:42.076358 [ 46129 ] {} <Fatal> ClientBase: 20. DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x00000000177e943a
2025.10.08 10:56:42.076367 [ 46129 ] {} <Fatal> ClientBase: 21. DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x00000000177e8a9c
2025.10.08 10:56:42.076376 [ 46129 ] {} <Fatal> ClientBase: 22. DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x000000001783d4f6
2025.10.08 10:56:42.076386 [ 46129 ] {} <Fatal> ClientBase: 23. DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) (.llvm.8395296845371277703) @ 0x0000000018377acd
2025.10.08 10:56:42.076396 [ 46129 ] {} <Fatal> ClientBase: 24. DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000183759ea
2025.10.08 10:56:42.076406 [ 46129 ] {} <Fatal> ClientBase: 25. std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__function::__policy_invoker<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) (.llvm.8395296845371277703) @ 0x00000000183790e2
2025.10.08 10:56:42.076416 [ 46129 ] {} <Fatal> ClientBase: 26. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x00000000182e8eae
2025.10.08 10:56:42.076426 [ 46129 ] {} <Fatal> ClientBase: 27. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x000000001874b96a
2025.10.08 10:56:42.076437 [ 46129 ] {} <Fatal> ClientBase: 28. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018745db3
2025.10.08 10:56:42.076448 [ 46129 ] {} <Fatal> ClientBase: 29. DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool, std::vector<String, std::allocator<String>> const&, std::function<void (DB::Progress const&)>) @ 0x0000000019cfff43
2025.10.08 10:56:42.076458 [ 46129 ] {} <Fatal> ClientBase: 30. DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared_ptr<DB::IAST>, bool&, unsigned long) @ 0x0000000019c676ee
2025.10.08 10:56:42.076467 [ 46129 ] {} <Fatal> ClientBase: 31. DB::ClientBase::executeMultiQuery(String const&) @ 0x0000000019c74483
2025.10.08 10:56:42.076473 [ 46129 ] {} <Fatal> ClientBase: 32. DB::ClientBase::processQueryText(String const&) @ 0x0000000019c7661c
2025.10.08 10:56:42.076485 [ 46129 ] {} <Fatal> ClientBase: 33. DB::ClientBase::runInteractive() @ 0x0000000019c7fb20
2025.10.08 10:56:42.076496 [ 46129 ] {} <Fatal> ClientBase: 34. DB::LocalServer::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000013a8c6c3
2025.10.08 10:56:42.076505 [ 46129 ] {} <Fatal> ClientBase: 35. Poco::Util::Application::run() @ 0x000000001ef1e3e6
2025.10.08 10:56:42.076515 [ 46129 ] {} <Fatal> ClientBase: 36. mainEntryClickHouseLocal(int, char**) @ 0x0000000013a9f105
2025.10.08 10:56:42.076525 [ 46129 ] {} <Fatal> ClientBase: 37. main @ 0x000000000c7200dd
2025.10.08 10:56:42.076749 [ 46129 ] {} <Fatal> ClientBase: 38. ../sysdeps/nptl/libc_start_call_main.h:58: __libc_start_call_main @ 0x0000000000027675
2025.10.08 10:56:42.076888 [ 46129 ] {} <Fatal> ClientBase: 39. ../csu/libc-start.c:360: __ieee754_j0f128 @ 0x0000000000027729
2025.10.08 10:56:42.076897 [ 46129 ] {} <Fatal> ClientBase: 40. _start @ 0x000000000767202e
2025.10.08 10:56:42.076904 [ 46129 ] {} <Fatal> ClientBase: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.10.08 10:56:42.077042 [ 46129 ] {} <Fatal> ClientBase: Changed settings: allow_introspection_functions = true, serialize_query_plan = false, storage_file_read_method = 'mmap', parallel_replicas_for_cluster_engines = false, implicit_select = true
Segmentation fault         (core dumped) ./clickhouse local

```

Seeing the multiple comments, let's revert and reintroduce with a proper fix that covers all cases
