### PR TITLE
Fix checkpoint position after putting it on buffer end

### LINKED ISSUE #22433: Get 'Malformed message: Field name is invalid or no colon found' for some very specific requests
**Describe the bug**
When the requests are done in a very specific environment, they got an error from ClickHouse. The partially it was fixed in https://github.com/ClickHouse/ClickHouse/pull/21936

**Does it reproduce on recent release?**
It's reproducible with docker image `yandex/clickhouse-server:latest` having digest `sha256:d359e6cff39486d2563cd16a307e0981ea6150760d7589b35e0e76ee7ba889ce`

**How to reproduce**
The very precise case for reproduction is present in https://github.com/Felixoid/ch-forms-issue

**Expected behavior**
The requests should work

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Follow-up fix for #21936. Also fixes #22433

### CODE REVIEW

File: src/IO/PeekableReadBuffer.cpp [hunk 1]
```diff
@@ -175,7 +175,7 @@ bool PeekableReadBuffer::nextImpl()
 
     if (checkpoint_at_end)
     {
-        checkpoint.emplace(working_buffer.begin());
+        checkpoint.emplace(position());
```
Comment (abyss7) [inline src/IO/PeekableReadBuffer.cpp:178]: Previous approach didn't work in situation when we put the checkpoint on the end of internal buffer, but still have some pending data in sub-buffer, i.e. after `makeContinuousMemoryFromCheckpointToPos()` call.

Comment (abyss7) [reply src/IO/PeekableReadBuffer.cpp:178]: Also I have to add some unit-tests.

**Review by tavplubix — APPROVED** [review]

**Comment by abyss7** [comment]
Yandex build looks like a fluke
