### PR TITLE
Fix assertion failure in CRoaring on self-merge of NumericIndexedVector

### LINKED ISSUE #99704: Assertion `x1 != x2' failed (STID: 2794-3a2f)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Assertion `x1 != x2' failed (STID: 2794-3a2f)
CI report: [AST fuzzer (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=03ae0dd6a5cc6812ddc7300f8f95ea718ea70102&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_debug%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdBc3NlcnRpb24gYHgxICE9IHgyJycgZmFpbGVkIChTVElEOiAyNzk0LTNhMmYpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQVNUIGZ1enplciAoYW1kX2RlYnVnKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBiYXNlX3JlZiBJTiAoJycsICdtYXN0ZXInKSkKICAgIC0tIEFORCB0ZXN0X2NvbnRleHRfcmF3IExJS0UgJyVwYXR0ZXJuJScgIC0tIHVuY29tbWVudCBhbmQgZWRpdCB0byBmaWx0ZXIgYnkgZmFpbHVyZSBwYXR0ZXJuCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
Error:
Assertion `x1 != x2' failed
---

Stack trace:
pthread_kill @ 0x00000000000969fd
__GI_raise @ 0x0000000000042476
__lgamma_r_finite @ 0x00000000000287f3
_nl_load_domain.cold @ 0x000000000002871b
? @ 0x0000000000039e96
/ClickHouse/contrib/croaring/src/roaring.c:1109:5: roaring_bitmap_xor_inplace @ 0x0000000024cc6b5b
inlined from /ClickHouse/contrib/croaring/cpp/roaring/roaring.hh:366: roaring::Roaring::operator^=(roaring::Roaring const&)
/ClickHouse/src/AggregateFunctions/AggregateFunctionGroupBitmapData.h:238:9: DB::RoaringBitmapWithSmallSet<int, (char8_t)32>::rb_xor(DB::RoaringBitmapWithSmallSet<int, (char8_t)32> const&) @ 0x000000000e34cb9c
/ClickHouse/src/AggregateFunctions/AggregateFunctionGroupNumericIndexedVectorDataBSI.h:503:18: DB::BSINumericIndexedVector<int, double>::pointwiseAddInplace(DB::BSINumericIndexedVector<int, double> const&) @ 0x000000000ec752b6
/ClickHouse/src/Functions/FunctionBinaryArithmetic.h:1201:31: DB::FunctionBinaryArithmetic<DB::MultiplyImpl, DB::NameMultiply, true, true, false>::executeAggregateMultiply(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000013c64ad2
/ClickHouse/src/Functions/FunctionBinaryArithmetic.h:2549:20: DB::FunctionBinaryArithmetic<DB::MultiplyImpl, DB::NameMultiply, true, true, false>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000013c642a5
/ClickHouse/src/Functions/FunctionBinaryArithmetic.h:2902:22: DB::FunctionBinaryArithmeticWithConstants<DB::MultiplyImpl, DB::NameMultiply, true, true, false>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000013c635f5
/ClickHouse/src/Functions/IFunction.h:472:16: DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000e27730a
/ClickHouse/src/Functions/IFunctionAdaptors.cpp:16:22: DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001a1324fa
/ClickHouse/src/Functions/IFunction.cpp:363:15: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a12b1ba
/ClickHouse/src/Functions/IFunction.cpp:438:22: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a12cb71
/ClickHouse/src/Functions/IFunction.cpp:577:16: DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a12de6a
/ClickHouse/src/Functions/IFunction.cpp:486:20: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a12d821
/ClickHouse/src/Analyzer/Resolve/resolveFunction.cpp:1541:47: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool) @ 0x000000001bc8d692
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:2931:46: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool, bool) @ 0x000000001b9f9f73
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:3083:49: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000001b9f9548
/ClickHouse/src/Analyzer/Resolve/resolveFunction.cpp:742:39: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool) @ 0x000000001bc87cf5
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:2931:46: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool, bool) @ 0x000000001b9f9f73
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:3083:49: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000001b9f9548
/ClickHouse/src/Analyzer/Resolve/resolveFunction.cpp:742:39: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool) @ 0x000000001bc87cf5
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:2931:46: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool, bool) @ 0x000000001b9f9f73
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:3083:49: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000001b9f9548
/ClickHouse/src/Analyzer/Resolve/resolveFunction.cpp:742:39: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool) @ 0x000000001bc87cf5
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:2931:46: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool, bool) @ 0x000000001b9f9f73
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:3083:49: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000001b9f9548
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:3412:40: DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x000000001ba17f7f
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:4956:30: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000001b9f3fde
/ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:139:13: DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x000000001b9f2d54
/ClickHouse/src/Analyzer/Resolve/QueryAnalysisPass.cpp:18:14: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x000000001b9f22cd
/ClickHouse/src/Analyzer/QueryTreePassManager.cpp:194:20: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>&) @ 0x000000001ba49309
/ClickHouse/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:207:33: DB::buildQueryTreeAndRunPasses(boost::intrusive_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x000000001c5f3bce
/ClickHouse/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:221:18: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(boost::intrusive_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, DB::ActionsDAG const*) @ 0x000000001c5f22d1
/ClickHouse/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:773:30: std::unique_ptr<DB::InterpreterSelectQueryAnalyzer, std::default_delete<DB::InterpreterSelectQueryAnalyzer>> std::make_unique[abi:se210105]<DB::InterpreterSelectQueryAnalyzer, boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, 0>(boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000001c5f92b3
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
/ClickHouse/src/Interpreters/InterpreterFactory.cpp:409:12: DB::InterpreterFactory::get(boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x000000001c5abc2b
/ClickHouse/src/Interpreters/executeQuery.cpp:1707:66: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001c96b254
/ClickHouse/src/Interpreters/executeQuery.cpp:2105:11: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c965ce3
/ClickHouse/src/Server/TCPHandler.cpp:821:68: DB::TCPHandler::runImpl() @ 0x00000000200ddc18
/ClickHouse/src/Server/TCPHandler.cpp:2959:9: DB::TCPHandler::run() @ 0x00000000200f92a4
```

### PR DESCRIPTION
**Pull request by Daedalus-Icarus**
Fix assertion failure in CRoaring `roaring_bitmap_xor_inplace` on self-merge of NumericIndexedVector

Closes https://github.com/ClickHouse/ClickHouse/issues/99704

The `executeAggregateMultiply` uses exponentiation by squaring, which calls `function->merge(vec_from[i], vec_from[i], arena)` (self-merge) on even iterations. For `BSINumericIndexedVector`, this calls `pointwiseAddInplace` where `this == &rhs`. Since `shallowCopyFrom` shares Roaring bitmap pointers, the full adder loop performs `sum->rb_xor(*addend)` on aliased bitmaps, triggering `assert(x1 != x2)` in debug builds and producing incorrect results (A XOR A = 0) in release builds.

Added a self-merge guard to both `pointwiseAddInplace` and `pointwiseSubtractInplace` that deep-copies the argument when `this == &rhs`.

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix assertion failure (exception in debug builds, incorrect results in release builds) when multiplying `NumericIndexedVector` aggregate states by an even integer constant, caused by self-XOR on aliased Roaring bitmaps in `pointwiseAddInplace`.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.3.1.884`
- Backported to: `26.3.1.894`, `26.2.6.5`, `26.1.6.5`, `25.12.9.53`, `25.8.21.7`

### CODE REVIEW

File: tests/queries/0_stateless/04049_aggregate_function_numeric_indexed_vector_self_merge.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
+-- Test that self-merge of NumericIndexedVector aggregate states does not trigger
+-- assertion failure in CRoaring (x1 != x2 in `roaring_bitmap_xor_inplace`).
+-- https://github.com/ClickHouse/ClickHouse/issues/99704
+
+-- `multiply` triggers self-merge via exponentiation by squaring (even branch).
+SELECT arrayJoin([numericIndexedVectorToMap(
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/04049_aggregate_function_numeric_indexed_vector_self_merge.sql:6]: Yes, the test reproduces the issue.

**Review by alexey-milovidov — APPROVED** [review]
LGTM
