### PR TITLE
Fix analyzer with positional arguments in distributed query

### LINKED ISSUE #62289: new analyzer: Positional argument number 0 is out of bounds in Distrbiuted queries
https://fiddle.clickhouse.com/ba2e163f-644b-4a4c-b6f7-614aa285ca00

```sql
set allow_experimental_analyzer=0;

select 0 as x
from remote('127.0.0.{1,2}', system.one)
group by x
format Pretty;

   +---+
   | x |
   +---+
1. | 0 |
   +---+


set allow_experimental_analyzer=1;

select 0 as x
from remote('127.0.0.{1,2}', system.one)
group by x
format Pretty;

Received exception from server (version 24.3.2):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: 
Positional argument number 0 is out of bounds. Expected in range [1, 1]. 
In scope SELECT 0 AS x FROM system.one AS __table1 GROUP BY 0. (BAD_ARGUMENTS)
(query: select 0 as x
from remote('127.0.0.{1,2}', system.one)
group by x
format Pretty;)
```

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Resolve positional arguments only on the initiator node. Closes #62289.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit b6dd55827fc5f19a763fa7b06e165cbd8b05fcea with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62362/b6dd55827fc5f19a763fa7b06e165cbd8b05fcea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -6681,7 +6681,7 @@ void QueryAnalyzer::resolveGroupByNode(QueryNode & query_node_typed, IdentifierR
         QueryTreeNodes nullable_group_by_keys;
         for (auto & grouping_sets_keys_list_node : query_node_typed.getGroupBy().getNodes())
         {
-            if (settings.enable_positional_arguments)
+            if (settings.enable_positional_arguments && scope.context->getClientInfo().query_kind == ClientInfo::QueryKind::INITIAL_QUERY)
```
Comment (novikd) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:6684]: Let's put this condition inside of `replaceNodesWithPositionalArguments`.

**Review by novikd — COMMENTED** [review]
In general LGTM, but I want to move condition into `replaceNodesWithPositionalArguments` to avoid mistakes in the future.
