### PR TITLE
Fix `test_delayed_replica_failover`

### LINKED ISSUE #69753: test_delayed_replica_failover/test.py::test is flaky
https://s3.amazonaws.com/clickhouse-test-reports/0/a997cfad2b61200c81371202acf5c6382d3d57f6/integration_tests__asan__[4_4].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgLS0gQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0JST0tFTicpCiAgICBBTkQgdG9EYXRlKGNoZWNrX3N0YXJ0X3RpbWUpID4gJzIwMjQtMDctMDEnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2RlbGF5ZWRfcmVwbGljYV9mYWlsb3ZlciUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQw==

```
            # At this point all replicas are stale, but the query must still go to second replicas which are the least stale ones.
            assert (
                instance_with_dist_table.query(
                    """
    SELECT sum(x) FROM distributed SETTINGS
        load_balancing='in_order',
        max_replica_delay_for_distributed_queries=1
    """
                ).strip()
                == "3"
            )
    
            # Prefer fallback_to_stale_replicas over skip_unavailable_shards
            assert (
                instance_with_dist_table.query(
                    """
    SELECT sum(x) FROM distributed SETTINGS
        load_balancing='in_order',
        skip_unavailable_shards=1,
        max_replica_delay_for_distributed_queries=1
    """
                ).strip()
                == "3"
            )
    
            # If we forbid stale replicas, the query must fail. But sometimes we must have bigger timeouts.
            for _ in range(20):
                try:
                    instance_with_dist_table.query(
                        """
    SELECT count() FROM distributed SETTINGS
        load_balancing='in_order',
        max_replica_delay_for_distributed_queries=1,
        fallback_to_stale_replicas_for_distributed_queries=0
    """
                    )
                    time.sleep(0.5)
                except:
                    break
            else:
>               raise Exception("Didn't raise when stale replicas are not allowed")
E               Exception: Didn't raise when stale replicas are not allowed

```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

I didn't find another way apart from using a failpoint.
The test seems extremely flaky because it depends on timings for Keeper session expiry, ZK request processing, watch triggers, background thread execution...
With failpoint we can force the delay and not rely on stars to align.

Fix https://github.com/ClickHouse/ClickHouse/issues/69753

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 2e715ccf47cbbb2a34001fa2291c0ac9ae327e1f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69826/2e715ccf47cbbb2a34001fa2291c0ac9ae327e1f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69819/ccb89e9a727cca6d5ecb4046311eca75b7ba062b/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Client/ConnectionEstablisher.cpp [hunk 1]
```diff
@@ -91,7 +97,15 @@ void ConnectionEstablisher::run(ConnectionEstablisher::TryResult & result, std::
 
         const UInt32 delay = table_status_it->second.absolute_delay;
         if (delay < max_allowed_delay)
+        {
             result.is_up_to_date = true;
+
+            fiu_do_on(FailPoints::replicated_merge_tree_all_replicas_stale,
+            {
+                result.delay = 1;
```
Comment (antaljanosbenjamin) [inline src/Client/ConnectionEstablisher.cpp:105]: In case anything depends on it, set the delay to a value that exceeds the max value.
```suggestion
                result.delay = max_allowed_delay + 1;
```

**Review by antaljanosbenjamin — APPROVED** [review]
Just a minor comment, if it makes sense for you then feel free to use it, but merging this as is is also fine for me.

File: src/Client/ConnectionEstablisher.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Client/ConnectionEstablisher.cpp:105]: I'm going to merge it now just to fix the flakiness.
In this test we don't care about the exact value of the delay, I just set it to minimal possible value to emulate some kind of ordering (which I also don't think is necessary).
Also, it's questionable if any test can rely on the exact value of the delay because it's a timestamp over which we have no complete control.
