### PR TITLE
Fix applying async_insert from server (via apply_settings_from_server)

### LINKED ISSUE #78130: async_insert in config.xml causes `UNKNOWN_PACKET_FROM_SERVER` (`apply_settings_from_server`)
### Company or project name

BrowserUp

### Describe what's wrong

`CREATE TABLE test (`id` FixedString(4), json JSON) ENGINE = Memory;
`
```
INSERT INTO test (id, json)
VALUES
    ('1234', '{"a": 45}'),
    ('9012', '{"b": 23}');

```
`
Error on processing query: Code: 100. DB::Exception: Unknown packet 11 from server localhost:9000. (UNKNOWN_PACKET_FROM_SERVER) (version 25.4.1.350 (official build))`

### Does it reproduce on the most recent release?

Yes

### How to reproduce

The error can be seen by running the insert above. 

If you toggle async_insert, you'll see the error when it is set to 1, but not otherwise.

```
<clickhouse>
    <listen_host>0.0.0.0</listen_host>
    <tcp_port>9000</tcp_port>
    <http_port>8123</http_port>

    <profiles>
        <default>
          <enable_json_type>1</enable_json_type>

          <!-- This causes/exposes the problem. If you remove it, it is fine.-->
          <async_insert>1</async_insert>

        </default>
    </profiles>

    <users>
        <default>
            <password></password> <!-- Empty password -->
        </default>
    </users>
</clickhouse>
```

### Expected behavior

It should work without error.

### Error message and/or stacktrace

_No response_

### Additional context

Version:  25.4.1.350 (official build))

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix applying `async_insert` from server (via `apply_settings_from_server`) (previously leads to `Unknown packet 11 from server` errors on the client)

The problem is that async_insert is checked during parsing, to know what
to send to the server, even before server settings available. And this
leads to "Unknown packet 11 from server" errors.

So, first approach will be to simply ignore async_insert for
apply_settings_from_server, but this setting is interesting to apply
from the server (since this may have performance impact).

Another is to detect what part of the query we should apply after server
settings had been received, this patch follows this approach.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/78130
Supersedes: https://github.com/ClickHouse/ClickHouse/pull/78493

### CODE REVIEW

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -2270,6 +2250,19 @@ void ClientBase::processParsedSingleQuery(const String & full_query, const Strin
...
         }
 
+        String query_to_execute;
+        /// An INSERT query may have the data that follows query text.
+        /// Send part of the query without data, because data will be sent separately.
+        /// But for asynchronous inserts we don't extract data, because it's needed
+        /// to be done on server side in that case (for coalescing the data from multiple inserts on server side).
+        if (insert && !is_async_insert_with_inlined_data)
+        {
+            chassert(full_query.data() <= insert->data && insert->end <= full_query.data() + full_query.size() && "INSERT query points to full_query");
```
Comment (azat) [inline src/Client/ClientBase.cpp:2260]: @al13n321 I've updated my patch finally (if it will pass CI, we can close https://github.com/ClickHouse/ClickHouse/pull/78493), but it has extra complexity, due to now we have to calculate the `query_to_execute` inside this function, so we need that `ASTPtr` will point to the same memory region, so I've converted all callers and related API to use `std::string_view`, so PTAL

**Comment by azat** [comment]
An update on it, I have to change the signature of `processParsedSingleQuery`, since it broke fuzzers.

You can find details in commit messages, but in a nut shell, now it accept only one `query` and the length of INSERT without data to adjust for the case `async_insert==false`

Before this patch it accepts two queries, `query_to_execute` and `final_query`, the first does not include data for INSERT, I have to change it to apply `async_insert`, so I change the meaning of it, but to make it work I need to adjust the query inside the function in case of `async_insert==false`, and for this I need for the `ASTInsertQuery::data` to look at the `query_to_execute`, but, for fuzzers it is not possible to satisfy due to fuzzers changes the query and then generate query from it (new string), but I cannot do another `parseQuery` since this will remove the `ASTInsertQuery::data`

Hope this will clarify things.

**Comment by azat** [comment]
>[Stateless tests (release, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77578&sha=a595877d02ad0ab28e04b5f41ea7e1416f5d4591&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20ParallelReplicas%2C%20s3%20storage%29) — fail: 1, passed: 6866, skipped: 959

- `02441_alter_delete_and_drop_column` - flaky

**Comment by azat** [comment]
@al13n321 @yariks5s it is ready!

File: src/Storages/Distributed/DistributedSink.cpp [hunk 2]
```diff
@@ -448,9 +448,9 @@ DistributedSink::runWritingJob(JobReplica & job, const Block & current_block, si
                     copy_query_ast,
                     job.local_context,
                     allow_materialized,
-                    /* no_squash */ false,
-                    /* no_destination */ false,
-                    /* async_isnert */ false);
+                    /* no_squash= */ false,
```
Comment (al13n321) [inline src/Storages/Distributed/DistributedSink.cpp:451]: Unimportant question: is there some guide or consensus saying which style we should use for these comments? Searching clickhouse code, I see occurrences of almost all possible styles: `/*foo*/false`, `/*foo*/ false`, `/* foo */ false`, `/* foo */false`, `/*foo=*/false`, `/* foo= */ false`, `/* foo = */ false`. Does something distinguish `/* foo= */ false` as the Schelling point for clickhouse codebase? Should I switch to it?

File: src/Client/ClientBase.cpp [hunk 3]
```diff
@@ -2270,16 +2241,26 @@ void ClientBase::processParsedSingleQuery(const String & full_query, const Strin
                     "Processing async inserts with both inlined and external data (from stdin or infile) is not supported");
         }
 
+        String query;
+        /// An INSERT query may have the data that follows query text.
+        /// Send part of the query without data, because data will be sent separately.
+        /// But for asynchronous inserts we don't extract data, because it's needed
+        /// to be done on server side in that case (for coalescing the data from multiple inserts on server side).
```
Comment (al13n321) [inline src/Client/ClientBase.cpp:2248]: If we send data separately anyway, will insert become synchronous, or will async insert just use more cpu on the server (on squashing the blocks?)? Would tests notice if this is broken and e.g. `is_async_insert_with_inlined_data` is always false?

**Review by al13n321 — APPROVED** [review]

File: src/Storages/Distributed/DistributedSink.cpp (hunk 2 above)
Comment (azat) [reply src/Storages/Distributed/DistributedSink.cpp:451]: Oh, this is a good question, this style is checked by the clang, so if the name in the comment will not match with the name of the parameter it will throw an error.

Comment (azat) [reply src/Storages/Distributed/DistributedSink.cpp:451]: One tiny note, it will not work obviously for i.e. `make_unique` and friends

File: src/Client/ClientBase.cpp (hunk 3 above)
Comment (azat) [reply src/Client/ClientBase.cpp:2248]: >If we send data separately anyway, will insert become synchronous, or will async insert just use more cpu on the server (on squashing the blocks?)?

The only benefit of async INSERT over TCP AFAICS is decreasing number of real INSERTs i.e. number of parts for MergeTree family

> Would tests notice if this is broken and e.g. is_async_insert_with_inlined_data is always false?

They should, since all of the combinations are checked in the test.
