### PR TITLE
Replace Turbo-Base64 with aklomp/base64

### LINKED ISSUE #31643: Replace "Turbo-Base64" to "lemire/fastbase64"
https://github.com/lemire/fastbase64

### LINKED ISSUE #41957: AVX512VBMI implementation of base64Encode / base64Decode
I just got to know this library yesterday https://github.com/WojciechMula/base64-avx512. Make some efforts to use it in base64Encode / base64Decode, and the performance on my local test (enable AVX512 and AVX512VBMI) is quite impressive compared to current approach (Turbo)

- Turbo - single thread:

ZMn1hglDTR

- Mula - single thread:

i01oe4QAYR

- Turbo - multi thread:

zwcBhCEJUf

- Mula - multi thread:

gIInamy6ca

Have you look at this lib before? One of my concern is it's not actively maintained, and the code quality is actually quite bad.
If you think it's good, then I can make a PR with this library.
Thanks.
@rschu1ze

### LINKED ISSUE #45790: Error in base64Decode function running clickhouse-server in Mac M1 (Arm)
> You have to provide the following information whenever possible.

This command bellow return error when running clickhouse-server docker instance in a Mac M1 (Arch64) machines. 

`select  base64Decode('AGy1cKzasOC/yOPct7tO3w')`

image

The command runs with no error in x86_64 machines. 

image

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

I'm running the latest version if the docker image. "clickhouse/clickhouse-server:23.1.2.9"

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

`2023.01.30 15:28:47.617942 [ 269 ] {509dae28-20d7-43df-8a36-557d7f7edea6} <Error> DynamicQueryHandler: Code: 117. DB::Exception: Failed to base64Decode input 'AGy1cKzasOC/yOPct7tO3w': While processing base64Decode('AGy1cKzasOC/yOPct7tO3w'). (INCORRECT_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xbb157c4 in /usr/bin/clickhouse
1. ? @ 0x84672b8 in /usr/bin/clickhouse
2. ? @ 0x84671cc in /usr/bin/clickhouse
3. ? @ 0x8466b4c in /usr/bin/clickhouse
4. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0xf53b454 in /usr/bin/clickhouse
5. DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0xf53b018 in /usr/bin/clickhouse
6. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0xf53b400 in /usr/bin/clickhouse
7. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0xf53be28 in /usr/bin/clickhouse
8. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0xf53d2b0 in /usr/bin/clickhouse
9. DB::ActionsDAG::addFunctionImpl(std::__1::shared_ptr<DB::IFunctionBase const> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*>>, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool) @ 0xfb7b6d8 in /usr/bin/clickhouse
10. DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) @ 0xfb7ae14 in /usr/bin/clickhouse
11. DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) @ 0xfd5d4f0 in /usr/bin/clickhouse
12. ? @ 0xfd66434 in /usr/bin/clickhouse
13. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xfd61f9c in /usr/bin/clickhouse
14. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xfd64cb8 in /usr/bin/clickhouse
15. ? @ 0xfd56480 in /usr/bin/clickhouse
16. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0xfd38128 in /usr/bin/clickhouse
17. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0xfd4651c in /usr/bin/clickhouse
18. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0xfd4b9a4 in /usr/bin/clickhouse
19. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x104242f4 in /usr/bin/clickhouse
20. ? @ 0x1041e724 in /usr/bin/clickhouse
21. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x10419ec4 in /usr/bin/clickhouse
22. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1049488c in /usr/bin/clickhouse
23. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x1049294c in /usr/bin/clickhouse
24. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x103db348 in /usr/bin/clickhouse
25. ? @ 0x1074e18c in /usr/bin/clickhouse
26. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x1075252c in /usr/bin/clickhouse
27. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x11343a9c in /usr/bin/clickhouse
28. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x11346994 in /usr/bin/clickhouse
29. DB::HTTPServerConnection::run() @ 0x113b1da8 in /usr/bin/clickhouse
30. Poco::Net::TCPServerConnection::start() @ 0x1201a5cc in /usr/bin/clickhouse
31. Poco::Net::TCPServerDispatcher::run() @ 0x1201c160 in /usr/bin/clickhouse
 (version 23.1.2.9 (official build))`

### PR DESCRIPTION
**Pull request by mkmkme**
Fixes #31643
Fixes #45790
Fixes #41957

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Replaced the library to handle (encode/decode) base64 values from Turbo-Base64 to aklomp-base64. Both are SIMD-accelerated on x86 and ARM but 1. the license of the latter (BSD-2) is more favorable for ClickHouse, Turbo64 switched in the meantime to GPL-3, 2. with more GitHub stars, aklomp-base64 seems more future-proof, 3. aklomp-base64 has a slightly nicer API (which is arguably subjective), and 4. aklomp-base64 does not require us to hack around bugs (like non-threadsafe initialization). Note: aklomp-base64 rejects unpadded base64 values whereas Turbo-Base64 decodes them on a best-effort basis. RFC-4648 leaves it open whether padding is mandatory or not, but depending on the context this may be a behavioral change to be aware of.

### CODE REVIEW

**Comment by mkmkme** [comment]
I noticed the build fails on x86_64. I'll fix it and undraft it.

Please keep in mind that as I mentioned earlier, **this actually makes `base64{Encode,Decode}` slower**

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 9abc056085924f916f695d5e4c32a8ec2f4dbc56 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54119/9abc056085924f916f695d5e4c32a8ec2f4dbc56/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: .gitmodules [hunk 1]
```diff
@@ -42,7 +42,7 @@
 	url = https://github.com/ClickHouse/boost
 [submodule "contrib/base64"]
 	path = contrib/base64
-	url = https://github.com/ClickHouse/Turbo-Base64
+	url = https://github.com/aklomp/base64.git
```
Comment (rschu1ze) [inline .gitmodules:45]: Git fails to checkout the new submodule in an existing repository with weird errors, no amount of `git submodule update` and `git reset --hard` helps. Repro (in case you like to try on an fresh, existing repo)

```sh
git remote add mkmkme https://github.com/mkmkme/ClickHouse.git
git fetch mkmkme
git switch --create mkmkme/aklomp-base64 mkmkme/mkmkme/aklomp-base64

git reset --hard && git clean --force -d
git submodule update --recursive --init
```

It won't be a problem in CI where the tree and all submodules are checked out from scratch but developers that rebase or merge this PR into their local repositories will complain (a lot). I think (not sure) that it is a problem that the existing `submodule` entry is reused. Unfortunately, someone reused the existing "base64" submodule already for "Turbo-base64" in the past already :-(

So, as as fix, could you try to
- make a commit which moves the existing Turbo64 submodule labeled as "base64" to a submodule labeled "Turbo64"?
- make a commit with the content of this PR what adds "base64" as a new submodule?

Comment (mkmkme) [reply .gitmodules:45]: Yeah, this might help.

There's also a solution of running `git submodule sync --recursive`. This is the command needed for syncing the submodule URLs.

`base64` had already been changed before, and it was also done within a commit: https://github.com/ClickHouse/ClickHouse/pull/8444/commits/063682ef9c20aeffd7aaa9d642ef263cd5f1b8e6

However, I can do it in two steps, if it makes the development easier :)

Comment (mkmkme) [reply .gitmodules:45]: Actually this might not work as well, because the changes will be applied all at once, not one-by-one.

How about I put the new library into `aklomp-base64` (and `aklomp-base64-cmake` respectively) instead, so there is no ambiguity in the future?

Comment (rschu1ze) [reply .gitmodules:45]: Sounds good, let's go for `aklomp-base64'.

File: src/Functions/FunctionBase64Conversion.h [hunk 2]
```diff
@@ -225,6 +218,16 @@ class FunctionBase64Conversion : public IFunction
         return dst_column;
     }
 };
+
+/** We must call it in advance from a single thread
+  *  to avoid thread sanitizer report about data race in "codec_choose" function.
+  */
+inline void initializeBase64()
```
Comment (rschu1ze) [inline src/Functions/FunctionBase64Conversion.h:225]: That's a kind of unbeautiful workaround. Yes, the extensive testing in ClickHouse's CI uncovers many sanitizer issues in submodules, and base64 seems no exception here. If possible, it would be appreciated if you could
- make a local tsan build of ClickHouse. For that, open the "BuilderDebTsan" log of an arbitrary other PR, e.g. [here](https://github.com/ClickHouse/ClickHouse/actions/runs/6042827088/job/16403984335?pr=54047), then search for "cmake " and run a stripped down version of this statement locally, e.g. `cmake  -DCMAKE_BUILD_TYPE=None -DSANITIZE=thread ..` + `ninja`
- try to reproduce the issue, e.g. run tests
- In the best case: fix the issue in base64 - we then can either reference a fork of "base64" in the ClickHouse [GItHub organization](https://github.com/ClickHouse/) with the fix or reference an upstream commit with the fix 
- use `__attribute__((no_sanitize("thread")))` (https://clang.llvm.org/docs/ThreadSanitizer.html), respectively the wrapper macro from "base/base/defines.h"

Comment (mkmkme) [reply src/Functions/FunctionBase64Conversion.h:225]: Sure, will do!

Comment (mkmkme) [reply src/Functions/FunctionBase64Conversion.h:225]: Also just for the record: I'm not sure this issue is still the case, as this comment was included back in the days when CH used `aklomp/base64` before `Turbo-Base64`.

Comment (rschu1ze) [reply src/Functions/FunctionBase64Conversion.h:225]: Feel free to make an experimental push to CI with the workaround removed. We can check if tsan (still) complains or not.

File: contrib/base64-cmake/CMakeLists.txt [hunk 3]
```diff
@@ -11,50 +11,74 @@ endif()
 
 SET(LIBRARY_DIR "${ClickHouse_SOURCE_DIR}/contrib/base64")
 
-add_library(_base64_scalar OBJECT "${LIBRARY_DIR}/turbob64c.c" "${LIBRARY_DIR}/turbob64d.c")
-add_library(_base64_ssse3 OBJECT "${LIBRARY_DIR}/turbob64sse.c") # This file also contains code for ARM NEON
-
-if (ARCH_AMD64)
-    add_library(_base64_avx OBJECT "${LIBRARY_DIR}/turbob64sse.c") # This is not a mistake. One file is compiled twice.
-    add_library(_base64_avx2 OBJECT "${LIBRARY_DIR}/turbob64avx2.c")
+set(HAVE_NEON32 0)
```
Comment (rschu1ze) [inline contrib/base64-cmake/CMakeLists.txt:14]: Looking at l. 1-5, I think we don't need the restriction to x86/ARM/PPC/s390 any more. Not that there are major other platforms (maybe RISC-V) but base64 should fall back to a generic algorithms on these architectures.

File: contrib/base64-cmake/CMakeLists.txt [hunk 4]
```diff
@@ -11,50 +11,74 @@ endif()
...
+
+        # Codec implementations
+        "${LIBRARY_DIR}/lib/arch/generic/codec.c"
+
+        "${LIBRARY_DIR}/lib/arch/ssse3/codec.c"
+        "${LIBRARY_DIR}/lib/arch/sse41/codec.c"
+        "${LIBRARY_DIR}/lib/arch/sse42/codec.c"
+        "${LIBRARY_DIR}/lib/arch/avx/codec.c"
+        "${LIBRARY_DIR}/lib/arch/avx2/codec.c"
+        "${LIBRARY_DIR}/lib/arch/avx512/codec.c"
```
Comment (rschu1ze) [inline contrib/base64-cmake/CMakeLists.txt:57]: Building avx512 is pointless if we don't define `HAVE_AVX512` (l. 34).

File: contrib/base64-cmake/README.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+`tables.h` file was generated by the base64 library with it's makefile:
```
Comment (rschu1ze) [inline contrib/base64-cmake/README.md:1]: Useful comment but please move it into contrib/base64-cmake-CMakeLists.txt to increase the chance that somebody reads it :-)

Comment (rschu1ze) [reply contrib/base64-cmake/README.md:1]: Related to that, the very same file already exists in contrib/base64/lib/tables/table_dec_32bit.h. Can't we simply use it?

**Comment by mkmkme** [comment]
There's also a test failure caused by an incorrect string not raising error:
```
chbuilder :) SELECT base64Decode('Zm9vYmF=Zm9v')

SELECT base64Decode('Zm9vYmF=Zm9v')

┌─base64Decode('Zm9vYmF=Zm9v')─┐
│ fooba                        │
└──────────────────────────────┘
```

I wonder what's the best action here. Other base64 implementations also work with this string, but they produce inconsistent data:

## Python3

```
In [2]: base64.b64decode('Zm9vYmF=Zm9v')
Out[2]: b'fooba'
```

## zsh

```
% echo -n 'Zm9vYmF=Zm9v' | base64 -d
foobafoo%
```

**Comment by rschu1ze** [comment]
Interesting question, there is no definite answer. On the one hand, the padding character `=` must only trail the encoded base64 value, i.e. `Zm9vYmF=Zm9v` is not valid base64 and the implementation is theoretically supposed to detect that. It is interesting that Python and CLI `base64` don't do that (probably for speed reasons). Looking at the Python docs and the manpage, the only type of detected errors are non-base64 characters (e.g. `$`). "Logical" errors go by unnoticed, i.e. garbage in, garbage out.

On the other hand, ClickHouses' [docs](https://clickhouse.com/docs/en/sql-reference/functions/string-functions#base58decode) of base64Decode are vague about detected errors. That leaves some leeway.

Maybe you could check if aklomp/base64 has a way to detect logical errors as well, e.g. by setting some flag somewhere. If not, we can accept the behavior and don't need to replicate Turbo64's error behavior 1:1.

File: contrib/base64-cmake/CMakeLists.txt (hunk 4 above)
Comment (mkmkme) [reply contrib/base64-cmake/CMakeLists.txt:57]: We can't simply omit this file unfortunately, because there's a possible run-time codec choose, which requires the function to be present on link time: https://github.com/aklomp/base64/blob/master/lib/codec_choose.c#L146-L150

If we want to drop this, we'll have to patch it out.

Comment (rschu1ze) [reply contrib/base64-cmake/CMakeLists.txt:57]: Then keep it in, but kindly add a comment (basically what you wrote before) so that readers are not confused, thanks!

**Comment by mkmkme** [comment]
@rschu1ze it seems that they don't have such an argument, hence I had to change the test.

**Comment by rschu1ze** [comment]
(as a meta comment: force-pushing a PR is okay if nobody reviewed it already. As force-pushing rewrites history, it is in general no longer possible to relate review comments with the code. Better push additional commits (and if you don't like a certain commit C, push a revert of C on top).

**Comment by mkmkme** [comment]
Ah sure, sorry for inconvenience! Actually rewriting history was exactly my point :)
Is it okay if "fixing" commits end up in the main branch? Or can/should I squash everything in the end?

**Comment by rschu1ze** [comment]
No problem. While a clean Git history is nice, the actual commit history in ClickHouse PRs is quite dirty (look at [this](https://github.com/ClickHouse/ClickHouse/commits/master) to see what I mean). Different people have different opinions about squashing (actually GitHub offers this functionality as an option to the "Merge" button - not sure if you can see it), I personally don't mind as long as the PR description is to the point.

**Comment by mkmkme** [comment]
Rebased on the top of the current master and squashed the original fix. The fixes regarding the comments will be pushed as separate commits.

File: .gitmodules (hunk 1 above)
Comment (mkmkme) [reply .gitmodules]: I think I made a mistake of leaving the submodule name intact. I used `git rm contrib/aklomp-base64` and re-added it via `git submodule add`. Let's see if it helps. I'll also double-check this on my other clone of CH

Comment (mkmkme) [reply .gitmodules]: For my clone seems to have worked. I had to invoke `git submodule update --init`, but AFAU it's fine when there's a new submodule?

Comment (rschu1ze) [reply .gitmodules]: I can confirm that it works with a new submodule.

**Comment by rschu1ze** [comment]
@mkmkme I pushed a few cleanups, including a check for the return code of base64's decode function. It restores the previous error behavior with invalid inputs.

**Comment by mkmkme** [comment]
> @mkmkme I pushed a few cleanups, including a check for the return code of base64's decode function. It restores the previous error behavior with invalid inputs.

Ah thanks! My bad

**Comment by spff** [comment]
I found `select tryBase64Decode('aoeo054640eu=')` returns non-empty string from 23.9, should we update the doc or should we turn it into empty string?

**Comment by rschu1ze** [comment]
@spff Thanks for reporting, a fix is [here](https://github.com/ClickHouse/ClickHouse/pull/56913).
