### PR TITLE
Fix segfault in FuzzJSON engine

### LINKED ISSUE #57858: Segfault: AggregationMethodOneNumber with FuzzJSON engine
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/57749/2a0a5f755c166604ca67901559afa50261556222/fuzzer_astfuzzerasan/report.html

**How to reproduce**
```sql
CREATE TABLE `02919_test_table_valid_args__fuzz_18`
(
    `str` Nullable(Int64)
)
ENGINE = FuzzJSON('{"pet":"rat"}', NULL);

SELECT
    _CAST(NULL, 'Nullable(Nothing)') AS `NULL`,
    count() AS `count()`
FROM
(
    SELECT default.`02919_test_table_valid_args__fuzz_18`.str AS str
    FROM default.`02919_test_table_valid_args__fuzz_18`
    GROUP BY default.`02919_test_table_valid_args__fuzz_18`.str
    LIMIT _CAST(257, 'UInt64')
);
```

### PR DESCRIPTION
**Pull request by jkartseva**
Allow only String type for FuzzJSON engine table columns.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/57858

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit cd7cb38d603fabf82d9abe7bc5bf6c0b6a583d4a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58015/cd7cb38d603fabf82d9abe7bc5bf6c0b6a583d4a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7255045724">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58015/cd7cb38d603fabf82d9abe7bc5bf6c0b6a583d4a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: tests/queries/0_stateless/02919_storage_fuzzjson.sql [hunk 1]
```diff
@@ -42,3 +42,15 @@ CREATE TABLE 02919_test_table_reuse_args(str String) ENGINE = FuzzJSON(
...
 
 DROP TABLE IF EXISTS 02919_test_table_reuse_args;
+
+--
+DROP TABLE IF EXISTS 02919_test_table_invalid_col_type;
+CREATE TABLE 02919_test_table_invalid_col_type
+(
+   str Nullable(Int64)
+)
+ENGINE = FuzzJSON('{"pet":"rat"}', NULL);
```
Comment (evillique) [inline tests/queries/0_stateless/02919_storage_fuzzjson.sql:52]: Shouldn't we forbid creating such storages in the first place and throw an exception during the CREATE query?

File: src/Storages/StorageFuzzJSON.cpp [hunk 2]
```diff
@@ -481,7 +481,11 @@ class FuzzJSONSource : public ISource
     {
         Columns columns;
         columns.reserve(block_header.columns());
-        columns.emplace_back(createColumn());
+        for (const auto& col : block_header)
```
Comment (kssenii) [inline src/Storages/StorageFuzzJSON.cpp:484]:
```suggestion
        for (const auto & col : block_header)
```
(https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/development/style.md)

**Review by kssenii — APPROVED** [review]
