### PR TITLE
Disable use of projections for the parallel replicas over distributed tables

### LINKED ISSUE #88899: Aggregations like count(), max() return zero values for Distributed tables with enable_parallel_replicas=1
### Company or project name

_No response_

### Describe what's wrong

SELECT max(col_name) FROM DB.table; 
returns zero value (1970-01-01 for DateTime) for Distributed tables on 3-node replicated cluster with allow_experimental_parallel_reading_from_replicas=1 setting.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

- version 25.8.10 official build
- 25.8 and 25.9 seem to be affected, 25.7.8.71 works as expected
- 3-node cluster with replication and allow_experimental_parallel_reading_from_replicas=1

```SQL
CREATE TABLE TestDB.test_repl on cluster cluster
(
    `time_col` DateTime
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/TestDB/test_repl-{uuid}', '{replica}')
        PARTITION BY tuple()
        ORDER BY time_col;

create table TestDB.test on cluster cluster
    as TestDB.test_repl
engine = Distributed('cluster', 'TestDB', 'test_repl', rand());

insert into TestDB.test (time_col) values (now());
insert into TestDB.test (time_col) values (now());

select count(), max(time_col) from TestDB.test;
```

produces
0, 1970-01-01 00:00:00

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

With
SETTINGS enable_parallel_replicas=0 or optimize_use_implicit_projections=0
results are correct

SELECT max(toDateTime(time_col)) ...
SELECT countIf(...)
SELECT max(time_col) FROM TestDB.table WHERE time_col>1;
return correct results too

### PR DESCRIPTION
**Pull request by zoomxi**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Disable parallel_replicas_support_projection for queries with parallel replicas over distributed tables. Closes #88899.

### CODE REVIEW

**Comment by zoomxi** [comment]
[Bugfix validation (functional tests)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88922&sha=d19844afce7ab4f96d50d1b278e91584b99f32a3&name_0=PR&name_1=Bugfix%20validation%20%28functional%20tests%29)
The newly added test case has passed, but this check step has failed.

[Stateless tests (amd_ubsan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88922&sha=d19844afce7ab4f96d50d1b278e91584b99f32a3&name_0=PR&name_1=Stateless%20tests%20%28amd_ubsan%2C%20parallel%29)
#88893

[Integration tests (arm_binary, distributed plan, 4/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88922&sha=d19844afce7ab4f96d50d1b278e91584b99f32a3&name_0=PR&name_1=Integration%20tests%20%28arm_binary%2C%20distributed%20plan%2C%204%2F4%29)
#71049

File: src/Interpreters/ClusterProxy/executeQuery.cpp [hunk 1]
```diff
@@ -512,6 +514,17 @@ static ContextMutablePtr updateContextForParallelReplicas(const LoggerPtr & logg
         /// disable hedged connections -> parallel replicas uses own logic to choose replicas
         context_mutable->setSetting("use_hedged_requests", Field{false});
     }
+
+    /// If parallel replicas are scoped to a specific shard, The local plan for parallel replicas cannot be generated.
+    /// And projections may need to be read from the local plan in certain scenarios, such as min-max projection. So we disable it here.
+    if (shard_num > 0 && settings[Setting::parallel_replicas_support_projection].value)
```
Comment (devcrafter) [inline src/Interpreters/ClusterProxy/executeQuery.cpp:523]: The test doesn't have any projections involved. It looks the error should still appear if parallel_replicas_support_projection is disabled.

Comment (zoomxi) [reply src/Interpreters/ClusterProxy/executeQuery.cpp:523]: Indeed, I had set the wrong ORDER BY key. Now fixed.

Comment (devcrafter) [reply src/Interpreters/ClusterProxy/executeQuery.cpp:523]: @zoomxi could you clarify why disabling `parallel_replicas_support_projection` should fix the issue?

Comment (zoomxi) [reply src/Interpreters/ClusterProxy/executeQuery.cpp:523]: AFAIK, in addition to explicitly defined projections, when optimizing aggregate projections (e.g., count/min/max), virtual projections are generated for trivial optimizations. These rely solely on index analysis and do not require reading part data. In such cases, `ReadFromMergeTree` is replaced with `ReadFromPreparedSource`.

To prevent data duplication caused by all replicas executing `ReadFromPreparedSource`, only the local plan executes `ReadFromPreparedSource`. In the example of https://github.com/ClickHouse/ClickHouse/issues/88899, no local plan was generated, leading to incorrect results.

If we disable `parallel_replicas_support_projection`, the projection optimization is skipped, and `ReadFromMergeTree` is executed to read part data, which avoids the issue.

**Comment by zoomxi** [comment]
@devcrafter PTAL

**Review by devcrafter — APPROVED** [review]
LGTM, this is a workaround, the proper fix will be done by enabling local plan for parallel replicas over distributed tables (currently doing it in https://github.com/ClickHouse/ClickHouse/pull/88991)
