### PR TITLE
CompileExpressions comparison function constant case fix

### LINKED ISSUE #24020: Cannot convert column `less(c0, c1)` because it is non constant in source stream but must be constant in result
``` sql
CREATE TABLE IF NOT EXISTS t0 (c0 Int32, c1  ALIAS c0) ENGINE = Memory() ;
INSERT INTO t0(c0) VALUES (-341725483);
INSERT INTO t0(c0) VALUES (-781504249), (-1079304144);
INSERT INTO t0(c0) VALUES (-1959608342), (1263536992), (1194580216);
INSERT INTO t0(c0) VALUES (-1639118561), (436683656), (275548633);
INSERT INTO t0(c0) VALUES (-871574473), (-397603882);
INSERT INTO t0(c0) VALUES (-1307576992), (-2034446574);
INSERT INTO t0(c0) VALUES (-1717404319), (-2004827833);
INSERT INTO t0(c0) VALUES (-1604878293), (172290479), (-1808153737);
INSERT INTO t0(c0) VALUES (-1808153737);
INSERT INTO t0(c0) VALUES (1196759186);
INSERT INTO t0(c0) VALUES (-1748576439);
INSERT INTO t0(c0) VALUES (2051389761), (1204228597);
INSERT INTO t0(c0) VALUES (1651756927), (681110175);
INSERT INTO t0(c0) VALUES (-1156920855);
INSERT INTO t0(c0) VALUES (-772388572), (-537624259), (-370697325);
INSERT INTO t0(c0) VALUES (2022909935);
INSERT INTO t0(c0) VALUES (713759928), (1172984613);
INSERT INTO t0(c0) VALUES (1739371629), (-111374952);
INSERT INTO t0(c0) VALUES (139603219), (-2131108571);
INSERT INTO t0(c0) VALUES (-1549239644), (784065114), (420077195);
INSERT INTO t0(c0) VALUES (-1843334206), (-6457985);
INSERT INTO t0(c0) VALUES (-638819909), (-1909459444), (-943510506);
INSERT INTO t0(c0) VALUES (1894781567), (-1985859792), (-476468556);
INSERT INTO t0(c0) VALUES (-618823782), (460423584);
INSERT INTO t0(c0) VALUES (-940596656);
INSERT INTO t0(c0) VALUES (-857101409), (-397603882);
INSERT INTO t0(c0) VALUES (-428805410), (2051389761);
INSERT INTO t0(c0) VALUES (297657448);
INSERT INTO t0(c0) VALUES (-163039758);
SELECT MIN(((t0.c0)<(t0.c1))) FROM t0 SETTINGS aggregate_functions_null_for_empty = 1 FORMAT TabSeparatedWithNamesAndTypes;
```

```
2021.05.11 14:34:57.075596 [ 200 ] {c0304913-59cb-4210-8f3e-7f22acec69c4} <Error> DynamicQueryHandler: Code: 44, e.displayText() = DB::Exception: Cannot convert column `less(c0, c1)` because it is non constant in source stream but must be constant in result, Stack trace (when copying this message, always include the lines below):

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x120b19c8 in /usr/bin/clickhouse
1. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:111: std::exception::exception() @ 0x120b1995 in /usr/bin/clickhouse
2. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x214f78c3 in /usr/bin/clickhouse
3. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:55: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x12092150 in /usr/bin/clickhouse
4. ./obj-x86_64-linux-gnu/../src/Interpreters/ActionsDAG.cpp:819: DB::ActionsDAG::makeConvertingActions(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, DB::ActionsDAG::MatchColumnsMode, bool, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >*) @ 0x1c0d120a in /usr/bin/clickhouse
5. ./obj-x86_64-linux-gnu/../src/Processors/QueryPlan/ExpressionStep.cpp:66: DB::ExpressionStep::transformPipeline(DB::QueryPipeline&, DB::BuildQueryPipelineSettings const&) @ 0x1db7d464 in /usr/bin/clickhouse
6. ./obj-x86_64-linux-gnu/../src/Processors/QueryPlan/ITransformingStep.cpp:44: DB::ITransformingStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipeline, std::__1::default_delete<DB::QueryPipeline> > > >, DB::BuildQueryPipelineSettings const&) @ 0x1db8e23f in /usr/bin/clickhouse
7. ./obj-x86_64-linux-gnu/../src/Processors/QueryPlan/QueryPlan.cpp:168: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x1dbb50c6 in /usr/bin/clickhouse
8. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:313: DB::InterpreterSelectWithUnionQuery::execute() @ 0x1c9a36e5 in /usr/bin/clickhouse
9. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:561: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1cc00559 in /usr/bin/clickhouse
10. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:997: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x1cc02a2b in /usr/bin/clickhouse
11. ./obj-x86_64-linux-gnu/../src/Server/HTTPHandler.cpp:772: DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x1d655089 in /usr/bin/clickhouse
12. ./obj-x86_64-linux-gnu/../src/Server/HTTPHandler.cpp:911: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1d656d1f in /usr/bin/clickhouse
13. ./obj-x86_64-linux-gnu/../src/Server/HTTP/HTTPServerConnection.cpp:48: DB::HTTPServerConnection::run() @ 0x1d6fffc2 in /usr/bin/clickhouse
14. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x21428f5c in /usr/bin/clickhouse
15. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x214297e4 in /usr/bin/clickhouse
16. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x21584ac3 in /usr/bin/clickhouse
17. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x2158137d in /usr/bin/clickhouse
18. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x21580108 in /usr/bin/clickhouse
19. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
20. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.6.1.6804)
```
Found by SQLancer https://clickhouse-test-reports.s3.yandex.net/20393/6aa7c0fafcca9c1493e6923ef68592ab68b286da/sqlancer_test.html#fail1

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Fixes #24020.

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: src/Interpreters/ExpressionJIT.cpp [hunk 1]
```diff
@@ -316,7 +316,7 @@ static bool isCompilableConstant(const ActionsDAG::Node & node)
     return node.column && isColumnConst(*node.column) && canBeNativeType(*node.result_type) && node.allow_constant_folding;
 }
 
-static bool checkIfFunctionIsComparisonEdgeCase(const ActionsDAG::Node & node, const IFunctionBase & impl)
+static bool checkIfFunctionIsComparisonEdgeCase(const ActionsDAG::Noomparision de & node, const IFunctionBase & impl)
```
Comment (qoega) [inline src/Interpreters/ExpressionJIT.cpp:319]: typo? Noomparision

Comment (kitaisreal) [reply src/Interpreters/ExpressionJIT.cpp]: Yes.

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
SQLancer found more:
```
--java.lang.AssertionError: SELECT SUM((t0.c1) or (((((t0.c0) IS NOT NULL)) IS NOT NULL))), MAX((((t0.c1)>=(((t0.c1) IS NULL)))) or (t0.c1)), COUNT(((((((t0.c1) IS NULL)) IS NULL))==(((t0.c1)>=(t0.c0))))), COUNT((t0.c0) and ((- (((t0.c0)<=(t0.c1)))))), SUM((- (t0.c1))) FROM t0 GROUP BY t0.c1, t0.c0 HAVING (NOT (t0.c1)) UNION ALL SELECT SUM((t0.c1) or (((((t0.c0) IS NOT NULL)) IS NOT NULL))), MAX((((t0.c1)>=(((t0.c1) IS NULL)))) or (t0.c1)), COUNT(((((((t0.c1) IS NULL)) IS NULL))==(((t0.c1)>=(t0.c0))))), COUNT((t0.c0) and ((- (((t0.c0)<=(t0.c1)))))), SUM((- (t0.c1))) FROM t0 GROUP BY t0.c1, t0.c0 HAVING (NOT ((NOT (t0.c1)))) UNION ALL SELECT SUM((t0.c1) or (((((t0.c0) IS NOT NULL)) IS NOT NULL))), MAX((((t0.c1)>=(((t0.c1) IS NULL)))) or (t0.c1)), COUNT(((((((t0.c1) IS NULL)) IS NULL))=(((t0.c1)>=(t0.c0))))), COUNT((t0.c0) and ((- (((t0.c0)<=(t0.c1)))))), SUM((- (t0.c1))) FROM t0 GROUP BY t0.c1, t0.c0 HAVING (((NOT (t0.c1))) IS NULL) SETTINGS aggregate_functions_null_for_empty=1, enable_optimize_predicate_expression=0;
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:100)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:131)
--	at sqlancer.ComparatorHelper.getResultSetFirstColumnAsString(ComparatorHelper.java:54)
--	at sqlancer.clickhouse.oracle.tlp.ClickHouseTLPHavingOracle.check(ClickHouseTLPHavingOracle.java:66)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:49)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:326)
--	at sqlancer.Main$2.run(Main.java:510)
--	at sqlancer.Main$2.runThread(Main.java:488)
--	at sqlancer.Main$2.run(Main.java:478)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
--	at java.base/java.lang.Thread.run(Thread.java:832)
--Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 44, host: localhost, port: 8123; Code: 44, e.displayText() = DB::Exception: Cannot convert column `equals(isNull(isNull(c1)), greaterOrEquals(c1, c0))` because it is non constant in source stream but must be constant in result (version 21.6.1.6812)```

**Comment by qoega** [comment]
Why `Cannot convert column` is not a LOGICAL_ERROR? We should find bugs like this in AST Fuzzer

File: src/Interpreters/ExpressionJIT.cpp [hunk 2]
```diff
@@ -316,28 +316,6 @@ static bool isCompilableConstant(const ActionsDAG::Node & node)
     return node.column && isColumnConst(*node.column) && canBeNativeType(*node.result_type) && node.allow_constant_folding;
 }
 
-static bool checkIfFunctionIsComparisonEdgeCase(const ActionsDAG::Node & node, const IFunctionBase & impl)
```
Comment (akuzm) [inline src/Interpreters/ExpressionJIT.cpp:319]: This should be done by the expression analyzer at about the same stage where it evaluates constants.

File: src/Functions/FunctionsComparison.h [hunk 3]
```diff
@@ -1148,17 +1148,24 @@ class FunctionComparison : public IFunction
...
-                return DataTypeUInt8().createColumnConst(input_rows_count, 1u);
+                result_column = DataTypeUInt8().createColumnConst(input_rows_count, 1u);
             }
             else
             {
-                return DataTypeUInt8().createColumnConst(input_rows_count, 0u);
+                result_column = DataTypeUInt8().createColumnConst(input_rows_count, 0u);
             }
+
+            if (!isColumnConst(*col_left_untyped))
```
Comment (KochetovNicolai) [inline src/Functions/FunctionsComparison.h:1165]: Please, add a comment why materialization is needed.
BTW, why not we always convert it to full?

Comment (kitaisreal) [reply src/Functions/FunctionsComparison.h:1165]: @KochetovNicolai can be fixed to always be full, old code.

File: src/Interpreters/TautologicalComparisonOptimizer.cpp [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+        auto & rhs = func->arguments->children[1];
+
+        auto lhs_hash = lhs->getTreeHash();
+        auto rhs_hash = rhs->getTreeHash();
+
+        if (likely(lhs_hash != rhs_hash))
+            return;
+
+        func->arguments->children[0] = std::make_shared<ASTLiteral>(1);
+        func->arguments->children[1] = std::make_shared<ASTLiteral>(1);
```
Comment (KochetovNicolai) [inline src/Interpreters/TautologicalComparisonOptimizer.cpp:44]: Ok, but maybe we can replace the whole function to literal 1 or literal 0

File: src/Interpreters/TreeRewriter.cpp [hunk 5]
```diff
@@ -940,6 +949,10 @@ TreeRewriterResultPtr TreeRewriter::analyzeSelect(
         replaceAliasColumnsInQuery(query, result.metadata_snapshot->getColumns(), result.getArrayJoinSourceNameSet(), getContext());
     }
 
+    std::cerr << "Query before tautological comparison " << query->formatForErrorMessage() << std::endl;
```
Comment (KochetovNicolai) [inline src/Interpreters/TreeRewriter.cpp]: pls remove debug output

**Review by KochetovNicolai — APPROVED** [review]

File: src/Interpreters/TreeRewriter.cpp (hunk 5 above)
Comment (kitaisreal) [reply src/Interpreters/TreeRewriter.cpp]: Fixed.

File: src/Interpreters/TautologicalComparisonOptimizer.cpp (hunk 4 above)
Comment (kitaisreal) [reply src/Interpreters/TautologicalComparisonOptimizer.cpp:44]: @KochetovNicolai right now seems easier to understand what is going on.

File: tests/queries/0_stateless/00911_tautological_compare.sql [hunk 6]
```diff
@@ -1,10 +1,10 @@
-SELECT count() FROM system.numbers WHERE number != number;
-SELECT count() FROM system.numbers WHERE number < number;
-SELECT count() FROM system.numbers WHERE number > number;
+-- SELECT count() FROM system.numbers WHERE number != number;
```
Comment (alesapin) [inline tests/queries/0_stateless/00911_tautological_compare.sql:1]: I hope we will revert this?

Comment (KochetovNicolai) [reply tests/queries/0_stateless/00911_tautological_compare.sql:7]: It is not so easy to do.
It's actually not so clear why reading from infinite table **must** return at all.
We can go farter and want a query `SELECT count() FROM system.numbers WHERE number < 10` return `10`. But is it necessary?

This optimizations is implemented in a not obvious way for now. We expected that a function `!=` for two same non-constant arguments will return constant `0`, and assume that constant will remain. It could have been ok if we had some meta info that columns are really same. But we just compare two ptrs. I don't think there is a guarantee that it is true for all other blocks. (However, I could not find counterexample. Queries like `where x != if(blockNumber() == 0, x, y)` work correctly only because `blockNumber` does not return constant.)

**Comment by alesapin** [comment]
Stress test:
```
zgrep -a '8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1' clickhouse-server.log.gz
2021.05.18 00:09:15.537857 [ 35027 ] {8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1} <Debug> executeQuery: (from [::1]:50154, using production parser) (comment: /usr/share/clickhouse-test/queries/0_stateless/00429_long_http_bufferization.sh) SELECT greatest(toUInt8(1), toUInt8(intHash64(number))) FROM system.numbers LIMIT 2500000 FORMAT RowBinary
2021.05.18 00:09:15.544607 [ 35027 ] {8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1} <Trace> ContextAccess (default): Access granted: SELECT(number) ON system.numbers
2021.05.18 00:09:15.546831 [ 35027 ] {8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.05.18 00:09:18.726076 [ 35027 ] {8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1} <Information> executeQuery: Read 2500000 rows, 19.07 MiB in 3.187516281 sec., 784309 rows/sec., 5.98 MiB/sec.
2021.05.18 00:09:18.819026 [ 35027 ] {8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1} <Debug> DynamicQueryHandler: Done processing query
2021.05.18 00:09:37.379188 [ 78460 ] {} <Fatal> BaseDaemon: (version 21.6.1.6862, build id: 902A04D557495CBDC22EAA45AEF413357E72A75C) (from thread 35027) (query_id: 8c05de33-7dd9-47ef-a4b0-d7ee11ddbac1) Received signal Aborted (6)
2021.05.18 00:09:37.378816 [ 78460 ] {} <Fatal> BaseDaemon: ########################################
2021.05.18 00:09:37.379421 [ 78460 ] {} <Fatal> BaseDaemon: 
2021.05.18 00:09:37.498338 [ 78460 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f08fdd2b18b 0x7f08fdd0a859 0x8f7cf6e 0x921335d 0x1931b354 0x1931b247 0x9009a3b 0x143c12a8 0x143488fe 0x1433fd0f 0x143ba4e1 0x16fa81a3 0x16fa8930 0x1711fb02 0x1711df90 0x1711c708 0x8f7776d 0x7f08fdee0609 0x7f08fde07293
2021.05.18 00:09:37.498812 [ 78460 ] {} <Fatal> BaseDaemon: 5. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.05.18 00:09:37.499068 [ 78460 ] {} <Fatal> BaseDaemon: 6. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.05.18 00:09:50.095824 [ 78460 ] {} <Fatal> BaseDaemon: 7. abort @ 0x8f7cf6e in /usr/bin/clickhouse
2021.05.18 00:09:50.598741 [ 78460 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:0: terminate_handler() @ 0x921335d in /usr/bin/clickhouse
2021.05.18 00:09:50.648051 [ 78460 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x1931b354 in /usr/bin/clickhouse
2021.05.18 00:09:50.695754 [ 78460 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/include/atomic_support.h:78: void (*std::__1::(anonymous namespace)::__libcpp_atomic_load<void (*)()>(void (* const*)(), int))()
2021.05.18 00:09:50.695959 [ 78460 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../contrib/libcxxabi/src/cxa_handlers.cpp:49: std::get_terminate()
2021.05.18 00:09:50.696065 [ 78460 ] {} <Fatal> BaseDaemon: 10. ../contrib/libcxxabi/src/cxa_handlers.cpp:92: std::terminate() @ 0x1931b247 in /usr/bin/clickhouse
2021.05.18 00:10:03.808964 [ 292 ] {} <Fatal> Application: Child process was terminated by signal 6.

```

**Comment by alesapin** [comment]
Wait for perf tests and merge.

**Comment by alesapin** [comment]
```

+1.249x | 0.249 | 0.247 | agg_functions_min_max_any
-- | -- | -- | --


```
Flap?

**Comment by alesapin** [comment]
I'll retry the task.

**Comment by alesapin** [comment]
`column_column_comparison | xml.etree.ElementTree.ParseError: no element found: line 39, column 0`

**Comment by azat** [comment]
@kitaisreal looks like this should be backported?
