### PR TITLE
Fix replaceRegexpAll

### LINKED ISSUE #35117: Bug in `replaceRegexpAll`
```sql
SELECT replaceRegexpAll('a', 'z*', '')
```

```
┌─replaceRegexpAll('a', 'z*', '')─┐
│                                 │
└─────────────────────────────────┘
```

```sql
SELECT replaceRegexpAll('aaaa', 'z*', '')
```

```
┌─replaceRegexpAll('aaaa', 'z*', '')─┐
│ aaa                                │
└────────────────────────────────────┘
```

Please create another issue.

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/35046#issuecomment-1061220789_

### PR DESCRIPTION
**Pull request by vdimir**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix `replaceRegexpAll`, close #35117

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alesapin — APPROVED** [review]

File: src/Functions/ReplaceRegexpImpl.h [hunk 1]
```diff
@@ -137,8 +137,13 @@ struct ReplaceRegexpImpl
 
                 if (replace_one)
                     can_finish_current_string = true;
-                else if (match.length() == 0)
-                    ++match_pos; /// Step one character to avoid infinite loop.
+
+                if (match.length() == 0)
+                {
+                    /// Step one character to avoid infinite loop
```
Comment (alesapin) [inline src/Functions/ReplaceRegexpImpl.h:143]: Maybe update a comment.

**Review by alesapin — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
