### PR TITLE
Fix filter analysis when only constant alias column is read

### LINKED ISSUE #79448: Column identifier __table2.c1 is already registered
### Describe the bug

Logical error: 'Column identifier __table2.c1 is already registered'.

similar to #75511

### How to reproduce

```
CREATE TABLE t0 (c0 Int, c1 Int ALIAS 1) ENGINE = Memory;
CREATE TABLE t0__fuzz_42 (`c0` Array(Nullable(UInt32)), `c1` IPv4 ALIAS 1) ENGINE = Memory;
SELECT c0 FROM remote('localhost', currentDatabase(), 't0') AS tx INNER JOIN t0__fuzz_42 USING (c1);
```

### Error message and/or stacktrace

```
2025.04.23 06:07:04.907953 [ 148443 ] {4cca82ef-abd1-4ba8-8374-60af44ffab91} <Fatal> : Logical error: 'Column identifier __table2.c1 is already registered'.
2025.04.23 06:07:04.932770 [ 148443 ] {4cca82ef-abd1-4ba8-8374-60af44ffab91} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. /home/ubuntu/ClickHouse-final/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001ab5d112
1. /home/ubuntu/ClickHouse-final/src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000fc54779
2. /home/ubuntu/ClickHouse-final/src/Common/Exception.h:112: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009f878ac
3. /home/ubuntu/ClickHouse-final/src/Common/Exception.h:130: DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x
0000000009f9cb4b
4. /home/ubuntu/ClickHouse-final/src/Planner/PlannerContext.cpp:39: DB::GlobalPlannerContext::createColumnIdentifier(DB::NameAndTypePair const&, std::shared_ptr<DB::IQueryT
reeNode> const&) @ 0x0000000013ef52cf
5. /home/ubuntu/ClickHouse-final/src/Planner/PlannerJoinTree.cpp:441: DB::buildJoinTreeQueryPlan(std::shared_ptr<DB::IQueryTreeNode> const&, DB::SelectQueryInfo const&, DB:
:SelectQueryOptions&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&, std::shared_ptr<DB::PlannerContext>&) @ 0x0000000014208610
6. /home/ubuntu/ClickHouse-final/src/Planner/Planner.cpp:1557: DB::Planner::buildPlanForQueryNode() @ 0x00000000141f100e                                                    7. /home/ubuntu/ClickHouse-final/src/Planner/Planner.cpp:1328: DB::Planner::buildQueryPlanIfNeeded() @ 0x00000000141ede52
8. /home/ubuntu/ClickHouse-final/src/Planner/Planner.cpp:248: DB::Planner::Planner(std::shared_ptr<DB::IQueryTreeNode> const&, DB::SelectQueryOptions&) @ 0x00000000141ecbbe9. /home/ubuntu/ClickHouse-final/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:183: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000148f2006
10. /home/ubuntu/ClickHouse-final/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::make_unique[abi:se190107]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x00000000148f4964
11. /home/ubuntu/ClickHouse-final/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000148aa70b                                                   12. /home/ubuntu/ClickHouse-final/src/Interpreters/executeQuery.cpp:1447: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::Q
ueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x0000000014bbda2b
13. /home/ubuntu/ClickHouse-final/src/Interpreters/executeQuery.cpp:1707: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingS
tage::Enum) @ 0x0000000014bb8568
14. /home/ubuntu/ClickHouse-final/src/Client/LocalConnection.cpp:263: DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String
, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long, DB::Settings const*, DB::ClientIn
fo const*, bool, std::vector<String, std::allocator<String>> const&, std::function<void (DB::Progress const&)>) @ 0x000000001679088f
15. /home/ubuntu/ClickHouse-final/src/Client/ClientBase.cpp:1254: DB::ClientBase::processOrdinaryQuery(String, std::shared_ptr<DB::IAST>) @ 0x0000000016730718
16. /home/ubuntu/ClickHouse-final/src/Client/ClientBase.cpp:2264: DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared
_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001672eb5d
17. /home/ubuntu/ClickHouse-final/src/Client/ClientBase.cpp:2636: DB::ClientBase::executeMultiQuery(String const&) @ 0x0000000016739cd9
18. /home/ubuntu/ClickHouse-final/src/Client/ClientBase.cpp:2823: DB::ClientBase::processQueryText(String const&) @ 0x000000001673addb
19. /home/ubuntu/ClickHouse-final/src/Client/ClientBase.cpp:3378: DB::ClientBase::runInteractive() @ 0x000000001674226b
20. /home/ubuntu/ClickHouse-final/programs/local/LocalServer.cpp:0: DB::LocalServer::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000fecea66
21. /home/ubuntu/ClickHouse-final/base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x000000001ac1fcc6
22. /home/ubuntu/ClickHouse-final/programs/local/LocalServer.cpp:1148: mainEntryClickHouseLocal(int, char**) @ 0x000000000fedb31c
23. /home/ubuntu/ClickHouse-final/programs/main.cpp:304: main @ 0x0000000009f7fcaa
24. ? @ 0x00007ffff7c29d90
25. ? @ 0x00007ffff7c29e40
26. _start @ 0x0000000009f7f02e
```

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix filter analysis when only a constant alias column is used in the query. Fixes #79448.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by novikd** [comment]
> [AST fuzzer (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82037&sha=dfc121bf88ace84ca351147461724fbdb1dc7efd&name_0=PR&name_1=AST%20fuzzer%20%28amd_ubsan%29) — Logical error: 'Column ID UInt32 query tree node does not have valid source node[AST fuzzer (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82037&sha=dfc121bf88ace84ca351147461724fbdb1dc7efd&name_0=PR&name_1=AST%20fuzzer%20%28amd_ubsan%29) — Logical error: 'Column ID UInt32 query tree node does not have valid source node

https://github.com/ClickHouse/ClickHouse/issues/82092

> [Integration tests (tsan, 5/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82037&sha=dfc121bf88ace84ca351147461724fbdb1dc7efd&name_0=PR&name_1=Integration%20tests%20%28tsan%2C%205%2F6%29) — fail: 1, passed: 569[Integration tests (tsan, 5/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82037&sha=dfc121bf88ace84ca351147461724fbdb1dc7efd&name_0=PR&name_1=Integration%20tests%20%28tsan%2C%205%2F6%29) — fail: 1, passed: 569
> [Integration tests (tsan, 3/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82037&sha=dfc121bf88ace84ca351147461724fbdb1dc7efd&name_0=PR&name_1=Integration%20tests%20%28tsan%2C%203%2F6%29) — fail: 1, passed: 618[Integration tests (tsan, 3/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82037&sha=dfc121bf88ace84ca351147461724fbdb1dc7efd&name_0=PR&name_1=Integration%20tests%20%28tsan%2C%203%2F6%29) — fail: 1, passed: 618

Unrelated

File: src/Planner/Utils.cpp [hunk 1]
```diff
@@ -442,12 +442,12 @@ QueryTreeNodePtr replaceTableExpressionsWithDummyTables(
...
         {
             const auto & storage_snapshot = table_node ? table_node->getStorageSnapshot() : table_function_node->getStorageSnapshot();
-            auto get_column_options = GetColumnsOptions(GetColumnsOptions::All).withExtendedObjects().withVirtuals();
             const auto & storage = storage_snapshot->storage;
 
             auto storage_dummy = std::make_shared<StorageDummy>(
                 storage.getStorageID(),
-                ColumnsDescription(storage_snapshot->getColumns(get_column_options)),
+                /// To preserve information about alias columns, column description must be extracted directly from storage metadata.
+                storage.getInMemoryMetadata().getColumns(),
```
Comment (davenger) [inline src/Planner/Utils.cpp]: Isn't it cleaner to use `storage_snapshot->metadata->getColumns()` instead of accessing `storage.getInMemoryMetadata()`?

**Comment by novikd** [comment]
This PR found a bug with parallel replicas. I updated the test to avoid running it with enabled parallel replicas and created an issue with another repro: https://github.com/ClickHouse/ClickHouse/issues/82754
