### PR TITLE
Solve direct read issue with low cardinality text columns

### LINKED ISSUE #87887: Logical error: 'Column __text_index_i0_hasToken_0 with type LowCardinality(UInt8) should not be filled by text index reader'
### Describe the bug

Found during this CI run: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87696&sha=beb293141a641c25930dbe1caefa2160c20dc951&name_0=PR&name_1=AST+fuzzer+%28arm_asan%29 cc @ahmadov and @rschu1ze 

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/040d2e38-a49d-4e6f-b5d1-72bbed350474

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Column __text_index_i0_hasToken_0 with type LowCardinality(UInt8) should not be filled by text index reader'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000276bf432
1. src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000149f80a9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d2ff30e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d2fed11
4. src/Common/Exception.h:141: DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000e1dfaf6
5. src/Storages/MergeTree/MergeTreeReaderTextIndex.cpp:46: DB::MergeTreeReaderTextIndex::MergeTreeReaderTextIndex(DB::IMergeTreeReader const*, DB::MergeTreeIndexWithCondition, DB::NamesAndTypesList) @ 0x000000001f12c994
6. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::MergeTreeReaderTextIndex>::__unique_single std::make_unique[abi:se190107]<DB::MergeTreeReaderTextIndex, DB::IMergeTreeReader const*&, DB::MergeTreeIndexWithCondition const&, DB::NamesAndTypesList const&>(DB::IMergeTreeReader const*&, DB::MergeTreeIndexWithCondition const&, DB::NamesAndTypesList const&) @ 0x000000001f12fb87
7. src/Storages/MergeTree/MergeTreeReaderTextIndex.cpp:405: DB::createMergeTreeReaderTextIndex(DB::IMergeTreeReader const*, DB::MergeTreeIndexWithCondition const&, DB::NamesAndTypesList const&) @ 0x000000001f12ee4d
8. src/Storages/MergeTree/MergeTreeReadTask.cpp:158: DB::MergeTreeReadTask::createReaders(std::shared_ptr<DB::MergeTreeReadTaskInfo const> const&, DB::MergeTreeReadTask::Extras const&, DB::MarkRanges const&, std::vector<DB::MarkRanges, std::allocator<DB::MarkRanges>> const&) @ 0x000000001f144499
9. src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:319: DB::MergeTreeReadPoolBase::createTask(std::shared_ptr<DB::MergeTreeReadTaskInfo const>, DB::MarkRanges, std::vector<DB::MarkRanges, std::allocator<DB::MarkRanges>>, DB::MergeTreeReadTask*) const @ 0x000000001fcffc92
10. src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:341: DB::MergeTreeReadPoolBase::createTask(std::shared_ptr<DB::MergeTreeReadTaskInfo const>, DB::MarkRanges, DB::MergeTreeReadTask*) const @ 0x000000001fd00e5b
11. src/Storages/MergeTree/MergeTreeReadPoolInOrder.cpp:76: DB::MergeTreeReadPoolInOrder::getTask(unsigned long, DB::MergeTreeReadTask*) @ 0x000000001fd2e5ed
12. src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:262: DB::MergeTreeSelectProcessor::read() @ 0x000000001f1542ca
13. src/Storages/MergeTree/MergeTreeSource.cpp:229: DB::MergeTreeSource::tryGenerate() @ 0x000000001fcef4a9
14. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001f730802
15. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001f74df90
16. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f73fd18
17. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001f740329
18. src/Processors/Executors/PipelineExecutor.cpp:602: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001f73ec21
19. src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001f73e33f
20. src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001f7564a4
21. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000014b387a6
22. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000014b3f1c0
23. start_thread @ 0x00000000000a27f1
24. __GI___clone3 @ 0x0000000000133b5c
```

### LINKED ISSUE #88119: Fuzzer error: `'Column __text_index_idx_hasToken_0 with type Nullable(UInt8) should not be filled by text index reader`
See [here](https://github.com/ClickHouse/ClickHouse/pull/88109).

```sql
CREATE TABLE tab__fuzz_0
(
    `k` Nullable(UInt64),
    `text` String,
    INDEX idx text TYPE text (tokenizer = 'splitByNonAlpha') GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY k
SETTINGS index_granularity = 2, index_granularity_bytes =  '10Mi', allow_nullable_key = 1;

INSERT INTO tab__fuzz_0 FORMAT Values (101, 'Alick a01'), (102, 'Blick a02');

SELECT 'Test hasToken:' FROM tab__fuzz_0 WHERE hasToken(text, toNullable('Alick')) GROUP BY 1, 1, 1  IS NOT NULL;
```

fails with a logical error:

```
[ip-172-31-34-62] 2025.10.06 08:31:57.302138 [ 2417592 ] {28358ba8-2b86-4f52-a045-db1621fcdb4a} <Fatal> : Logical error: 'Column __text_index_idx_hasToken_0 with type Nullable(UInt8) should not be filled by text index reader'.
[ip-172-31-34-62] 2025.10.06 08:31:57.536496 [ 2417592 ] {28358ba8-2b86-4f52-a045-db1621fcdb4a} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. /data/ch1/contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::exception::capture() @ 0x000000000e328962
1. /data/ch1/contrib/llvm-project/libcxx/include/__exception/exception.h:85: std::exception::exception[abi:se190107]() @ 0x000000000e32892d
2. /data/ch1/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x0000000037acd620
3. /data/ch1/src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000018fb05b4
4. /data/ch1/src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000e32318c
5. /data/ch1/src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000e322011
6. /data/ch1/src/Common/Exception.h:141: DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000f22b3cd
7. /data/ch1/src/Storages/MergeTree/MergeTreeReaderTextIndex.cpp:46: DB::MergeTreeReaderTextIndex::MergeTreeReaderTextIndex(DB::IMergeTreeReader const*, DB::MergeTreeIndexWithCondition, DB::NamesAndTypesList) @ 0x000000002a2ad98b
8. /data/ch1/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::MergeTreeReaderTextIndex>::__unique_single std::make_unique[abi:se190107]<DB::MergeTreeReaderTextIndex, DB::IMergeTreeReader const*&, DB::MergeTreeIndexWithCondition const&, DB::NamesAndTypesList const&>(DB::IMergeTreeReader const*&, DB::MergeTreeIndexWithCondition const&, DB::NamesAnd
ypesList const&) @ 0x000000002a2b19fb
9. /data/ch1/src/Storages/MergeTree/MergeTreeReaderTextIndex.cpp:405: DB::createMergeTreeReaderTextIndex(DB::IMergeTreeReader const*, DB::MergeTreeIndexWithCondition const&, DB::NamesAndTypesList const&) @ 0x000000002a2b0265
10. /data/ch1/src/Storages/MergeTree/IMergeTreeReader.cpp:544: DB::createMergeTreeReaderIndex(DB::IMergeTreeReader const*, DB::MergeTreeIndexWithCondition const&, DB::NamesAndTypesList const&) @ 0x0000000029da1e0b
11. /data/ch1/src/Storages/MergeTree/MergeTreeReadTask.cpp:158: DB::MergeTreeReadTask::createReaders(std::shared_ptr<DB::MergeTreeReadTaskInfo const> const&, DB::MergeTreeReadTask::Extras const&, DB::MarkRanges const&, std::vector<DB::MarkRanges, std::allocator<DB::MarkRanges>> const&) @ 0x000000002a2e5b74
12. /data/ch1/src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:322: DB::MergeTreeReadPoolBase::createTask(std::shared_ptr<DB::MergeTreeReadTaskInfo const>, DB::MarkRanges, std::vector<DB::MarkRanges, std::allocator<DB::MarkRanges>>, DB::MergeTreeReadTask*) const @ 0x000000002b96f9c7
13. /data/ch1/src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:344: DB::MergeTreeReadPoolBase::createTask(std::shared_ptr<DB::MergeTreeReadTaskInfo const>, DB::MarkRanges, DB::MergeTreeReadTask*) const @ 0x000000002b9701fa
```

### PR DESCRIPTION
**Pull request by Ergus**
When the input column for  is low cardinality, it seems like hasToken and similar functions are reported also as low cardinality result type in the dag.

This is strictly true, but for direct read the column will contain only 0 and 1. So it is simpler and easier just set it as UInt8 explicitly in all the cases.

Maybe one day we will have some boolean support in columns (storing internally some bitmap) and we can use that specialization.

Resolves: #87887
Resolves: #88119

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by rschu1ze — APPROVED** [review]

File: tests/queries/0_stateless/02346_text_index_bug87887.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
+-- Test for Bug 87887
+
+SET allow_experimental_full_text_index = 1;
```
Comment (ahmadov) [inline tests/queries/0_stateless/02346_text_index_bug87887.sql:3]: don't you have to set these settings to enable the direct read?

```sql
SET use_skip_indexes_on_data_read = 1;
SET use_skip_indexes = 1;
SET query_plan_direct_read_from_text_index = 1;
```

File: tests/queries/0_stateless/02346_text_index_bug87887.sql [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+DROP TABLE IF EXISTS tab;
+CREATE TABLE tab (c0 LowCardinality(String), INDEX i0 c0 TYPE text(tokenizer = 'default')) ENGINE = MergeTree ORDER BY tuple();
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02346_text_index_bug87887.sql]: Need to use the new tokenizer name from Elmis PR here.

**Comment by rschu1ze** [comment]
Stateless tests (arm_binary, parallel):
- 02844_max_backup_bandwidth_s3: https://github.com/ClickHouse/ClickHouse/issues/85084

File: tests/queries/0_stateless/02346_text_index_bug87887.sql (hunk 1 above)
Comment (rschu1ze) [reply tests/queries/0_stateless/02346_text_index_bug87887.sql:3]: Yes, this ^^ will make sense.

Comment (Ergus) [reply tests/queries/0_stateless/02346_text_index_bug87887.sql:3]: Solved via [85d0133](https://github.com/ClickHouse/ClickHouse/commit/85d01339c74760c44351fe0e1c0ca044a96d047b)

**Review by ahmadov — APPROVED** [review]

**Comment by rschu1ze** [comment]
More funny and unrelated errors in the private repo :-/
Needs a merge from `master`.

**Comment by rschu1ze** [comment]
@Ergus Let's check the test failures and merge? This is a small fix and we better don't let it bit-rot.

**Comment by Ergus** [comment]
> @Ergus Let's check the test failures and merge? This is a small fix and we better don't let it bit-rot.

I already checked the last week. IIUC all the failures are unrelated with this change.
