### PR TITLE
Fixed inserting into Buffer engine

### LINKED ISSUE #52436: Table functions don't work anymore in scenarios when currentDatabase is unknown
> A clear and concise description of what works not as it is supposed to.

The reference to a table function (mysql / mongo etc) stop working in 23.1 when the call of that functions happens out of the query context (flushes from Buffer, from Distributed etc).

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/444a8a64-52f8-445e-bd58-bc183fa2348c

22.12 - works: https://fiddle.clickhouse.com/c60cbea6-6167-4a3a-ab9e-14c6d97b0b21
23.1 and newer - fails: https://fiddle.clickhouse.com/d0f1e276-8d35-45c3-ac5f-cfd1f57e56c1 

The test
```
DROP TABLE IF EXISTS null_table;
DROP TABLE IF EXISTS null_table_buffer;
DROP TABLE IF EXISTS null_mv;
DROP VIEW IF EXISTS number_view;
CREATE TABLE null_table (number UInt64) ENGINE = Null;
CREATE VIEW number_view as SELECT * FROM numbers(10) as tb;
CREATE MATERIALIZED VIEW null_mv Engine = Log AS SELECT * FROM null_table LEFT JOIN number_view as tb USING number;
CREATE TABLE null_table_buffer (number UInt64) ENGINE = Buffer(currentDatabase(), null_table, 1, 1, 1, 100, 200, 10000, 20000);
INSERT INTO null_table_buffer VALUES (1);
SELECT sleep(3) FORMAT Null;
SELECT count() FROM null_mv;
WITH arrayMap(x -> demangle(addressToSymbol(x)), last_error_trace) as all SELECT *,  arrayStringConcat(all, '\n') AS res 
                FROM system.errors
                WHERE (name = 'UNKNOWN_DATABASE')  SETTINGS allow_introspection_functions=1 FORMAT Vertical;
```

The exception:
```
2023.07.21 16:27:12.889829 [ 69 ] {} <Error> void DB::StorageBuffer::backgroundFlush(): Code: 81. DB::Exception: Database name is empty: while pushing to view default.null_mv (417ed1eb-9a73-413a-be8b-532f20c28524). (UNKNOWN_DATABASE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe22f215 in /usr/bin/clickhouse
1. ? @ 0xd78d3b6 in /usr/bin/clickhouse
2. DB::StorageID::getDatabaseName() const @ 0x13af2c45 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x12ee7a80 in /usr/bin/clickhouse
4. DB::DatabaseCatalog::tryGetTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x12eeeb18 in /usr/bin/clickhouse
5. DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, DB::ASTSelectQuery const*) @ 0x12e4e15b in /usr/bin/clickhouse
6. DB::JoinedTables::getLeftTableStorage() @ 0x139e3d57 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x139005b6 in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x1399f4c2 in /usr/bin/clickhouse
9. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x1399d133 in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x1399c58c in /usr/bin/clickhouse
11. DB::StorageView::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x142cb89c in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x1391adc8 in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x1390c92d in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1390bcad in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x139a0ff6 in /usr/bin/clickhouse
16. DB::SelectQueryExpressionAnalyzer::makeJoin(DB::ASTTablesInSelectQueryElement const&, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::ActionsDAG>&) @ 0x12f5f33c in /usr/bin/clickhouse
17. DB::SelectQueryExpressionAnalyzer::appendJoin(DB::ExpressionActionsChain&, std::shared_ptr<DB::ActionsDAG>&) @ 0x12f5ddd8 in /usr/bin/clickhouse
18. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::shared_ptr<DB::FilterDAGInfo> const&, std::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x12f6b25a in /usr/bin/clickhouse
19. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x13910251 in /usr/bin/clickhouse
20. ? @ 0x13908ad9 in /usr/bin/clickhouse
21. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x13902fec in /usr/bin/clickhouse
22. DB::ExecutingInnerQueryFromViewTransform::onConsume(DB::Chunk) @ 0x14d7e4b2 in /usr/bin/clickhouse
23. ? @ 0x14ce302b in /usr/bin/clickhouse
24. ? @ 0x14ce2d79 in /usr/bin/clickhouse
25. DB::ExceptionKeepingTransform::work() @ 0x14ce265f in /usr/bin/clickhouse
26. DB::ExecutionThreadContext::executeTask() @ 0x14afd94a in /usr/bin/clickhouse
27. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14af29bb in /usr/bin/clickhouse
28. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x14af1da8 in /usr/bin/clickhouse
29. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::shared_ptr<DB::IStorage>) @ 0x1430ff06 in /usr/bin/clickhouse
30. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool) @ 0x1430cc32 in /usr/bin/clickhouse
31. DB::StorageBuffer::backgroundFlush() @ 0x14310dc2 in /usr/bin/clickhouse
 (version 23.3.8.21 (official build))
```

The problem was intoduced by that change:
https://github.com/ClickHouse/ClickHouse/commit/614fd4cf42ca77dc0329639cc4003e1e2ea2f242#diff-c7c4cea868f661341c1e9866836dc34c1c88723f9f33b4e09db530c2ea074036R1248

which replace safe call to isTableExist to a code which can throw (tryGetTable) and don't catch the exception.

### PR DESCRIPTION
**Pull request by Enmk**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed writing to table functions when executed upon flushing Buffer engine. Happened in background, when there was no associated query and hence no "current database".

Fixes: #52436

### CODE REVIEW

File: src/Interpreters/DatabaseCatalog.cpp [hunk 1]
```diff
@@ -344,7 +344,8 @@ DatabaseAndTable DatabaseCatalog::getTableImpl(
     DatabasePtr database;
     {
         std::lock_guard lock{databases_mutex};
-        auto it = databases.find(table_id.getDatabaseName());
+        // hasDatabase() to avod getDatabaseName() throwing exception if database is empty.
```
Comment (alexey-milovidov) [inline src/Interpreters/DatabaseCatalog.cpp:347]: `avod` - a typo.

Comment (alexey-milovidov) [inline src/Interpreters/DatabaseCatalog.cpp:347]: The comment is not explanatory enough. It does not explain the motivation for this logic.

**Comment by alexey-milovidov** [comment]
> Fixed inserting into Buffer engine.

The changelog entry is not detailed enough.

**Comment by Enmk** [comment]
> The changelog entry is not detailed enough.
Updated source code comments and changelog entry description, please take another look.

File: src/Interpreters/DatabaseCatalog.cpp [hunk 2]
```diff
@@ -344,7 +344,8 @@ DatabaseAndTable DatabaseCatalog::getTableImpl(
     DatabasePtr database;
     {
         std::lock_guard lock{databases_mutex};
-        auto it = databases.find(table_id.getDatabaseName());
+        // Callers assume that this method doesn't throw exceptions, but getDatabaseName() will throw if there is no database part.
+        auto it = table_id.hasDatabase() ? databases.find(table_id.getDatabaseName()) : databases.end();
```
Comment (Enmk) [inline src/Interpreters/DatabaseCatalog.cpp:348]: The only downside I see here is a bit cryptic error message in the `system.errors`: something like "Database doesn't exists".

Slightly better alternative would be to generate different error message, something like "Database is empty".
But that still would be a very confusing to the end user since effectively there is no error, and calling code handles this situation correctly.

We can't just return the empty object without creating `Exception` object, since that would break `DatabaseCatalog::getTable`.

I considered adding special case into `tryGetTable`, and `tryGetDatabaseAndTable`, to handle empty database name. But that looks worse from a maintenance perspective: somebody is deemed to forged about this special case down the road and most likely to re-introduce similar error.

So the choice here seems to be between two bogus error messages.

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 9bd8bdca98d21605f10d172b76c80951f990d965 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52440/9bd8bdca98d21605f10d172b76c80951f990d965/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by Avogar — APPROVED** [review]
