### PR TITLE
Fix handling of aliases in query cache

### LINKED ISSUE #56258: Return same datas by query cache after change some alias
ClickHouse version: 23.8.3

```
CREATE OR REPLACE TABLE test
(
    `id` UInt64
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO test VALUES (1),(2),(3);
```

If I set `use_query_cache=1`, `SELECT id FROM test` and `SELECT id AS id1 FROM test` return the same datas, column name is `id`, which `id1` should the correct answer for the second query.

Is it by design?

### PR DESCRIPTION
**Pull request by rschu1ze**
Resolves #56258

See Changelog Entry.

The query result cache indexes query results by the hashes of their corresponding query ASTs. A query is answered directly from the cache only if the hash of its AST matches a hash of another querys's AST stored in the query cache.

The problem was that hashing of ASTs (`IAST::getTreeHash()`) ignores aliases, i.e. was based on the underlying column name. I don't know if that was intended or an oversight. Hashing now incorporates aliases.

There is a chance something breaks, so let's look carefully at tests.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The query cache now correctly handles literal / identifier / function aliases. For example, queries `SELECT 1 SETTINGS use_query_cache = 1` and `SELECT 1 AS X SETTINGS use_query_cache = 1` were previously considered the same and the second query was answered directly from the cache. In this example and most real-world use cases, both queries produce the same result and only their result field names differ. There exist however pathological cases where the results differ. The query cache now always treats queries with different aliases as different.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Initially, it was made to implement common subexpression elimination. Let's check that it does not break.

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 1dc565cd223480a8c7f9cdb2ec82808c7f60d9e8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56545/1dc565cd223480a8c7f9cdb2ec82808c7f60d9e8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6817401995">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56545/1dc565cd223480a8c7f9cdb2ec82808c7f60d9e8/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by rschu1ze** [comment]
Hm, makes sense. I fear common subexpression elimination will break :-) The fix would be to make it configurable is the hash calculation is "logical" vs. "physical", I first hoped I could avoid it. Let's see at least if there are any tests for it and if not, I may add some.

**Comment by Algunenano** [comment]
If you want to see me suffering because of this same issue see this PR -> https://github.com/ClickHouse/ClickHouse/pull/40065

I tried to use the query hash (instead of query string) in the block cache and found the same problem as you can see in the query cache right now. Those are the changes I tried to introduce to differentiate between when you need the alias and when you don't. It was from a time when we thought the analyzer was going to be ready sooner and made the changes unnecessary (for the block cache).

**Review by alexey-milovidov — APPROVED** [review]
Ok. Looks straightforward.

File: src/Interpreters/Cache/QueryCache.cpp [hunk 1]
```diff
@@ -147,17 +147,18 @@ QueryCache::Key::Key(ASTPtr ast_, const String & user_name_)
 {
 }
 
+/// Hashing of ASTs must consider aliases (issue #56258)
+constexpr bool ignore_aliases = false;
```
Comment (alexey-milovidov) [inline src/Interpreters/Cache/QueryCache.cpp:151]: static ?

File: src/Parsers/IAST.h [hunk 2]
```diff
@@ -78,11 +78,13 @@ class IAST : public std::enable_shared_from_this<IAST>, public TypePromotion<IAS
...
 
     /** Get hash code, identifying this element and its subtree.
+     *  Hashing by default ignores aliases (e.g. identifier aliases, function aliases, literal aliases) which is
+     *  useful for common subexpression elimination. Set 'ignore_aliases = false' if you don't want that behavior.
       */
     using Hash = CityHash_v1_0_2::uint128;
-    Hash getTreeHash() const;
-    void updateTreeHash(SipHash & hash_state) const;
-    virtual void updateTreeHashImpl(SipHash & hash_state) const;
+    Hash getTreeHash(bool ignore_aliases = true) const;
```
Comment (alexey-milovidov) [inline src/Parsers/IAST.h:85]: One nitpick - I generally tend to avoid default arguments for functions because:

1. It is error-prone, and it was proven by a few bugs in our codebase.
2. Default arguments in virtual functions increase the size of the virtual table.
3. I've heard that Rust does not have default function arguments, so it might be good.
