### PR TITLE
Fix DateTime64 parsing after constant folding

### LINKED ISSUE #66773: [analyzer] Cannot parse DateTime: In scope SELECT _CAST('0', 'DateTime64(3)') AS `toDateTime64('1970-01-01 00:00:00', 3)` for distributed table with more than one host in select
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

**Describe what's wrong**

```sql
SELECT toDateTime64('1970-01-01 00:00:00', 3)
FROM remote('127.0.0.{1,2,3,4}', system, one)
SETTINGS allow_experimental_analyzer = 1
```

https://fiddle.clickhouse.com/4aa61476-b9bf-4ad0-a67f-9224a0528153

return error
```
Received exception from server (version 24.6.2):
Code: 41. DB::Exception: Received from localhost:9000. DB::Exception: Received from 127.0.0.2:9000. DB::Exception: Cannot parse DateTime: In scope SELECT _CAST('0', 'DateTime64(3)') AS `toDateTime64('1970-01-01 00:00:00', 3)` FROM system.one AS __table1. (CANNOT_PARSE_DATETIME)
(query: SELECT toDateTime64('1970-01-01 00:00:00', 3)
FROM remote('127.0.0.{1,2,3,4}', system, one)
SETTINGS allow_experimental_analyzer = 1
)
```

**Does it reproduce on the most recent release?**

yes
reproduced with any release when  allow_experimental_analyzer = 1

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix DateTime64 parsing after constant folding in distributed queries, close https://github.com/ClickHouse/ClickHouse/issues/66773

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by vdimir** [comment]
Related a bit to https://github.com/ClickHouse/ClickHouse/pull/58118/files

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 5c4f2c198573ba03b793e4610f4e9854a61a5543 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67920/5c4f2c198573ba03b793e4610f4e9854a61a5543/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67920/5c4f2c198573ba03b793e4610f4e9854a61a5543/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/ConstantNode.cpp [hunk 1]
```diff
@@ -162,14 +163,33 @@ QueryTreeNodePtr ConstantNode::cloneImpl() const
...
     if (requiresCastCall())
     {
-        auto constant_type_name_ast = std::make_shared<ASTLiteral>(constant_value->getType()->getName());
+        /** Value for DateTime64 is Decimal64, which is serialized as a string literal.
+          * If we serialize it as is, DateTime64 would be parsed from that string literal, which can be incorrect.
+          * For example, DateTime64 cannot be parsed from the short value, like '1', while it's a valid Decimal64 value.
+          * It could also lead to ambiguous parsing because we don't know if the string literal represents a date or a Decimal64 literal.
+          * For this reason, we use a string literal representing a date instead of a Decimal64 literal.
+          */
+        if (WhichDataType(constant_value_type->getTypeId()).isDateTime64())
```
Comment (novikd) [inline src/Analyzer/ConstantNode.cpp:180]: The change makes sense. But I'm unsure if it can change the execution name on the follower node.
Do you think we also need to update `calculateActionNodeNameWithCastIfNeeded`?

**Review by novikd — APPROVED** [review]

File: src/Analyzer/ConstantNode.cpp (hunk 1 above)
Comment (vdimir) [reply src/Analyzer/ConstantNode.cpp:180]: Will merge this PR since CI passed, adding test case in https://github.com/ClickHouse/ClickHouse/pull/67966
