### PR TITLE
Avoid projections if INTERPOLATE with expressions is present

### LINKED ISSUE #36530: INTERPOLATE doesn't work for MergeTree
**Describe what's wrong**
INTERPOLATE doesn't work for tables with ENGINE = MergeTree

**Does it reproduce on recent release?**
yes

**How to reproduce**
```
CREATE TABLE t1 (n Int32) ENGINE = MergeTree ORDER BY n;
INSERT INTO t1 VALUES (1),(3),(3),(6),(6),(6);

SELECT
    n,
    count() AS m
FROM t1
GROUP BY n
ORDER BY n ASC WITH FILL
INTERPOLATE ( m AS m + 1 );

Received exception from server (version 22.5.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'm' while processing query: 'SELECT n, count() FROM t1 GROUP BY n ORDER BY n ASC WITH FILL INTERPOLATE ( m AS m + 1 )', required columns: 'n' 'm', maybe you meant: ['n','n']. (UNKNOWN_IDENTIFIER)
```

**Expected behavior**
same as
```
CREATE TABLE t1 (n Int32) ENGINE = Memory;
INSERT INTO t1 VALUES (1),(3),(3),(6),(6),(6);

SELECT
    n,
    count() AS m
FROM t1
GROUP BY n
ORDER BY n ASC WITH FILL
INTERPOLATE ( m AS m + 1 );

┌─n─┬─m─┐
│ 1 │ 1 │
│ 2 │ 2 │
│ 3 │ 2 │
│ 4 │ 3 │
│ 5 │ 4 │
│ 6 │ 3 │
└───┴───┘
```

**Error message and/or stacktrace**
```
Received exception from server (version 22.5.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'm' while processing query: 'SELECT n, count() FROM t1 GROUP BY n ORDER BY n ASC WITH FILL INTERPOLATE ( m AS m + 1 )', required columns: 'n' 'm', maybe you meant: ['n','n']. (UNKNOWN_IDENTIFIER)
```

**Additional context**
INTERPOLATE is a new feature added in #35349

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `Missing column` exception which could happen while using `INTERPOLATE` with `ENGINE = MergeTree` table.

closes #36530

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]
Test is needed

File: tests/queries/0_stateless/02233_interpolate_1.sql [hunk 1]
```diff
@@ -70,3 +70,10 @@ SELECT n, source, inter + NULL AS inter_p FROM (
 SELECT n, source, inter AS inter_p FROM (
     SELECT toFloat32(number % 10) AS n, 'original' AS source, number + NULL AS inter FROM numbers(10) WHERE (number % 3) = 1
 ) ORDER BY n ASC WITH FILL FROM 0 TO 11.51 STEP 0.5 INTERPOLATE ( inter_p AS inter_p + 1 );
+
+# Test INTERPOLATE for MergeTree
+DROP TABLE IF EXISTS t_inter_02233;
+CREATE TABLE t_inter_02233 (n Int32) ENGINE = MergeTree ORDER BY n;
+INSERT INTO t_inter_02233 VALUES (1),(3),(3),(6),(6),(6);
+SELECT n, count() AS m FROM t_inter_02233 GROUP BY n ORDER BY n WITH FILL INTERPOLATE ( m AS m + 1 );
+DROP TABLE IF EXISTS t_inter_02233;
```
Comment (amosbird) [inline tests/queries/0_stateless/02233_interpolate_1.sql:79]: Missing newline

**Comment by KochetovNicolai** [comment]
#36611
