### PR TITLE
Fix null deference for GROUP BY WITH TOTALS HAVING (when the column from HAVING wasn't selected)

### LINKED ISSUE #29687: UBSan: TotalsHavingTransform: reference binding to null pointer of type 'COW::immutable_ptr'
https://clickhouse-test-reports.s3.yandex.net/29626/ad0fcda71349536da482b57f53ef6da730e4581a/fuzzer_ubsan/report.html#fail1

```
2021.10.03 14:06:08.134083 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Debug> executeQuery: (from [::1]:51312) SELECT '102.4' FROM remote('127.0.0.{1,2}', currentDatabase(), local_t) GROUP BY '0.3', 0.5, a WITH TOTALS HAVING a IN (SELECT NULL)
2021.10.03 14:06:08.134554 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE, REMOTE ON *.*
2021.10.03 14:06:08.134782 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE, REMOTE ON *.*
2021.10.03 14:06:08.135169 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.10.03 14:06:08.135229 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.10.03 14:06:08.136048 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> ContextAccess (default): Access granted: SELECT(a) ON default.local_t
2021.10.03 14:06:08.136113 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState
2021.10.03 14:06:08.136232 [ 92 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> InterpreterSelectQuery: WithMergeableState -> Complete
2021.10.03 14:06:08.137296 [ 753 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> CreatingSetsTransform: Creating set.
2021.10.03 14:06:08.137336 [ 753 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Debug> CreatingSetsTransform: Created Set with 0 entries from 1 rows in 3.7373e-05 sec.
2021.10.03 14:06:08.137487 [ 753 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> AggregatingTransform: Aggregating
2021.10.03 14:06:08.137499 [ 655 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> Connection (127.0.0.2:9000): Connecting. Database: (not specified). User: default
2021.10.03 14:06:08.137511 [ 753 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> Aggregator: Aggregation method: key8
2021.10.03 14:06:08.137567 [ 753 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Debug> AggregatingTransform: Aggregated. 1 to 1 rows (from 1.00 B) in 0.001148927 sec. (870.377 rows/sec., 870.38 B/sec.)
2021.10.03 14:06:08.137584 [ 753 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> Aggregator: Merging aggregated data
2021.10.03 14:06:08.137673 [ 93 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::ffff:127.0.0.1]:36766
2021.10.03 14:06:08.137738 [ 93 ] {} <Debug> TCPHandler: Connected ClickHouse server version 21.11.0, revision: 54449, user: default.
2021.10.03 14:06:08.137938 [ 655 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> Connection (127.0.0.2:9000): Connected to ClickHouse server version 21.11.1.
2021.10.03 14:06:08.138259 [ 655 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Debug> Connection (127.0.0.2:9000): Sent data for 2 scalars, total 2 rows in 6.3697e-05 sec., 31035 rows/sec., 66.00 B (998.98 KiB/sec.), compressed 0.4520547945205479 times to 146.00 B (2.16 MiB/sec.)
2021.10.03 14:06:08.138733 [ 93 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Debug> executeQuery: (from [::ffff:127.0.0.1]:36766, initial_query_id: b8908591-f455-4f8a-89df-8601d016bc1b) SELECT '102.4' FROM default.local_t GROUP BY a WITH TOTALS HAVING a IN ((SELECT NULL) AS _subquery1757)
2021.10.03 14:06:08.139371 [ 93 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Trace> ContextAccess (default): Access granted: SELECT(a) ON default.local_t
2021.10.03 14:06:08.139444 [ 93 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState
2021.10.03 14:06:08.139850 [ 335 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Trace> AggregatingTransform: Aggregating
2021.10.03 14:06:08.139878 [ 335 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Trace> Aggregator: Aggregation method: key8
2021.10.03 14:06:08.139913 [ 335 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Debug> AggregatingTransform: Aggregated. 1 to 1 rows (from 1.00 B) in 0.000369719 sec. (2704.757 rows/sec., 2.64 KiB/sec.)
2021.10.03 14:06:08.139930 [ 335 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Trace> Aggregator: Merging aggregated data
2021.10.03 14:06:08.140335 [ 93 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Information> executeQuery: Read 1 rows, 1.00 B in 0.001530648 sec., 653 rows/sec., 653.32 B/sec.
2021.10.03 14:06:08.140378 [ 93 ] {874d559e-5da7-486f-8172-9d482a0337fb} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.10.03 14:06:08.140533 [ 93 ] {} <Debug> TCPHandler: Processed in 0.002293391 sec.
2021.10.03 14:06:08.140642 [ 655 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Trace> Aggregator: Merging partially aggregated blocks (bucket = -1).
2021.10.03 14:06:08.140692 [ 655 ] {b8908591-f455-4f8a-89df-8601d016bc1b} <Debug> Aggregator: Merged partially aggregated blocks. 1 rows, 1.00 B. in 1.565e-05 sec. (63897.764 rows/sec., 62.40 KiB/sec.)
../contrib/libcxx/include/vector:677:16: runtime error: reference binding to null pointer of type 'COW<DB::IColumn>::immutable_ptr<DB::IColumn>'
2021.10.03 14:06:08.327558 [ 140 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 7763 entries to flush up to offset 2961142
2021.10.03 14:06:08.333680 [ 140 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:08.335549 [ 140 ] {} <Trace> system.asynchronous_metric_log (060e4e81-2438-45fb-860e-4e81243825fb): Renaming temporary part tmp_insert_202110_381_381_0 to 202110_381_381_0.
2021.10.03 14:06:08.335826 [ 140 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 2961142
2021.10.03 14:06:08.447251 [ 143 ] {} <Trace> SystemLog (system.session_log): Flushing system log, 235 entries to flush up to offset 892
2021.10.03 14:06:08.451140 [ 143 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:08.452451 [ 143 ] {} <Trace> system.session_log (4b7c9778-e379-4fff-8b7c-9778e3797fff): Renaming temporary part tmp_insert_202110_5_5_0 to 202110_5_5_0.
2021.10.03 14:06:08.452752 [ 143 ] {} <Trace> SystemLog (system.session_log): Flushed system log up to offset 892
2021.10.03 14:06:08.593412 [ 91 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #1
2021.10.03 14:06:09.000169 [ 274 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.20 GiB, peak 7.00 GiB, will set to 3.20 GiB (RSS), difference: 2.31 MiB
2021.10.03 14:06:09.381769 [ 86 ] {} <Trace> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Found 6 old parts to remove.
2021.10.03 14:06:09.381849 [ 86 ] {} <Debug> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Removing part from filesystem 202110_1_286_57
2021.10.03 14:06:09.382283 [ 86 ] {} <Debug> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Removing part from filesystem 202110_287_287_0
2021.10.03 14:06:09.382525 [ 86 ] {} <Debug> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Removing part from filesystem 202110_288_288_0
2021.10.03 14:06:09.382728 [ 86 ] {} <Debug> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Removing part from filesystem 202110_289_289_0
2021.10.03 14:06:09.382941 [ 86 ] {} <Debug> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Removing part from filesystem 202110_290_290_0
2021.10.03 14:06:09.383149 [ 86 ] {} <Debug> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Removing part from filesystem 202110_291_291_0
    #0 0x1c9be436 in std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >::front() obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:677:9
    #1 0x1c9be436 in DB::TotalsHavingTransform::transform(DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/Transforms/TotalsHavingTransform.cpp:227:28
    #2 0x1743eaca in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:37:9
    #3 0x1c66cdec in DB::ISimpleTransform::work() obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89:9
    #4 0x1c6c5338 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:88:20
    #5 0x1c6c5226 in DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:105:13
    #6 0x1c6c5226 in decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #7 0x1c6c37c7 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #8 0x1c6c37c7 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #9 0x1c6c37c7 in DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:599:17
    #10 0x1c6c5c09 in DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:487:5
    #11 0x1c6c5c09 in DB::PipelineExecutor::executeImpl(unsigned long)::$_4::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:790:21
    #12 0x1c6c5c09 in decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #13 0x1c6c5ae2 in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #14 0x1c6c5ae2 in decltype(auto) std::__1::apply<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #15 0x1c6c5ae2 in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #16 0x1c6c5ae2 in decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #17 0xc856b99 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #18 0xc856b99 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #19 0xc856b99 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:274:17
    #20 0xc8595a1 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:139:73
    #21 0xc8595a1 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #22 0xc8595a1 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #23 0xc8595a1 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #24 0x7fa87227c608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #25 0x7fa8721a3292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../contrib/libcxx/include/vector:677:16 in 
2021.10.03 14:06:09.550834 [ 42 ] {} <Trace> BaseDaemon: Received signal -3
2021.10.03 14:06:09.551032 [ 820 ] {} <Fatal> BaseDaemon: ########################################
2021.10.03 14:06:09.551146 [ 820 ] {} <Fatal> BaseDaemon: (version 21.11.1.8288, build id: 64FF6E4C23A87DD97702A5D153EC381C43644F5E) (from thread 655) (query_id: b8908591-f455-4f8a-89df-8601d016bc1b) Received signal Unknown signal (-3)
2021.10.03 14:06:09.551187 [ 820 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.10.03 14:06:09.551258 [ 820 ] {} <Fatal> BaseDaemon: Stack trace: 0xc827eea 0x1a823651 0xc7e9826 0xc7f61ef 0x1c9be437 0x1743eacb 0x1c66cded 0x1c6c5339 0x1c6c5227 0x1c6c37c8 0x1c6c5c0a 0x1c6c5ae3 0xc856b9a 0xc8595a2 0x7fa87227c609 0x7fa8721a3293
2021.10.03 14:06:09.562467 [ 820 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:303: StackTrace::tryCapture()
2021.10.03 14:06:09.562499 [ 820 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:264: StackTrace::StackTrace() @ 0xc827eea in /workspace/clickhouse
2021.10.03 14:06:09.585517 [ 820 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:400: sanitizerDeathCallback() @ 0x1a823651 in /workspace/clickhouse
2021.10.03 14:06:10.000148 [ 274 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.20 GiB, peak 7.00 GiB, will set to 3.27 GiB (RSS), difference: 74.29 MiB
2021.10.03 14:06:10.602440 [ 139 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 2673
2021.10.03 14:06:10.623703 [ 139 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:10.629310 [ 139 ] {} <Trace> system.metric_log (f80699a3-cbdc-4de0-b806-99a3cbdc4de0): Renaming temporary part tmp_insert_202110_355_355_0 to 202110_355_355_0.
2021.10.03 14:06:10.631654 [ 139 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 2673
2021.10.03 14:06:10.754004 [ 820 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xc7e9826 in /workspace/clickhouse
2021.10.03 14:06:10.858442 [ 138 ] {} <Debug> DiskLocal: Reserving 4.37 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:10.866435 [ 138 ] {} <Trace> system.text_log (e0afbbf6-3e1f-4aa0-a0af-bbf63e1f5aa0): Renaming temporary part tmp_insert_202110_356_356_0 to 202110_356_356_0.
2021.10.03 14:06:10.986113 [ 135 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 2804 entries to flush up to offset 100823
2021.10.03 14:06:11.000147 [ 274 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.26 GiB, peak 7.00 GiB, will set to 3.53 GiB (RSS), difference: 276.43 MiB
2021.10.03 14:06:11.009967 [ 135 ] {} <Debug> DiskLocal: Reserving 2.57 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:11.016411 [ 135 ] {} <Trace> system.query_thread_log (05c64860-def2-459f-85c6-4860def2359f): Renaming temporary part tmp_insert_202110_269_269_0 to 202110_269_269_0.
2021.10.03 14:06:11.016615 [ 213 ] {} <Debug> system.query_thread_log (05c64860-def2-459f-85c6-4860def2359f) (MergerMutator): Selected 7 parts from 202110_1_116_35 to 202110_269_269_0
2021.10.03 14:06:11.016739 [ 213 ] {} <Debug> DiskLocal: Reserving 7.24 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:11.016820 [ 135 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log up to offset 100823
2021.10.03 14:06:11.016906 [ 59 ] {} <Debug> MergeTask::PrepareStage: Merging 7 parts: from 202110_1_116_35 to 202110_269_269_0 into Wide
2021.10.03 14:06:11.017198 [ 59 ] {} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2021.10.03 14:06:11.017423 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 6 marks from part 202110_1_116_35, total 38406 rows starting from the beginning of the part
2021.10.03 14:06:11.019551 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 5 marks from part 202110_117_264_32, total 28442 rows starting from the beginning of the part
2021.10.03 14:06:11.021469 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_265_265_0, total 5684 rows starting from the beginning of the part
2021.10.03 14:06:11.021951 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_266_266_0, total 10617 rows starting from the beginning of the part
2021.10.03 14:06:11.022407 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_267_267_0, total 10285 rows starting from the beginning of the part
2021.10.03 14:06:11.022848 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_268_268_0, total 4585 rows starting from the beginning of the part
2021.10.03 14:06:11.023317 [ 59 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_269_269_0, total 2804 rows starting from the beginning of the part
2021.10.03 14:06:11.364396 [ 62 ] {} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 100823 rows, containing 44 columns (44 merged, 0 gathered) in 0.34754014 sec., 290104.6192822504 rows/sec., 267.90 MiB/sec.
2021.10.03 14:06:11.373951 [ 62 ] {} <Trace> system.query_thread_log (05c64860-def2-459f-85c6-4860def2359f): Renaming temporary part tmp_merge_202110_1_269_36 to 202110_1_269_36.
2021.10.03 14:06:11.374225 [ 62 ] {} <Trace> system.query_thread_log (05c64860-def2-459f-85c6-4860def2359f) (MergerMutator): Merged 7 parts: from 202110_1_116_35 to 202110_269_269_0
2021.10.03 14:06:11.374358 [ 62 ] {} <Debug> MemoryTracker: Peak memory usage: 212.16 MiB.
2021.10.03 14:06:11.924160 [ 820 ] {} <Fatal> BaseDaemon: 3. ? @ 0xc7f61ef in /workspace/clickhouse
2021.10.03 14:06:11.942970 [ 820 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/TotalsHavingTransform.cpp:227: DB::TotalsHavingTransform::transform(DB::Chunk&) @ 0x1c9be437 in /workspace/clickhouse
2021.10.03 14:06:11.963305 [ 820 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:38: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x1743eacb in /workspace/clickhouse
2021.10.03 14:06:11.977218 [ 820 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x1c66cded in /workspace/clickhouse
2021.10.03 14:06:12.000149 [ 274 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.53 GiB, peak 7.00 GiB, will set to 3.61 GiB (RSS), difference: 85.87 MiB
2021.10.03 14:06:12.011207 [ 820 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:96: DB::executeJob(DB::IProcessor*) @ 0x1c6c5339 in /workspace/clickhouse
2021.10.03 14:06:12.039570 [ 134 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 526 entries to flush up to offset 34445
2021.10.03 14:06:12.044141 [ 820 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:108: operator()
2021.10.03 14:06:12.044186 [ 820 ] {} <Fatal> BaseDaemon: 8. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1c6c5227 in /workspace/clickhouse
2021.10.03 14:06:12.064311 [ 134 ] {} <Debug> DiskLocal: Reserving 1.45 MiB on disk `default`, having unreserved 1.02 TiB.
2021.10.03 14:06:12.069351 [ 134 ] {} <Trace> system.query_log (470fc1de-632e-4179-870f-c1de632e3179): Renaming temporary part tmp_insert_202110_271_271_0 to 202110_271_271_0.
2021.10.03 14:06:12.069824 [ 134 ] {} <Trace> SystemLog (system.query_log): Flushed system log up to offset 34445
2021.10.03 14:06:12.074222 [ 820 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:606: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1c6c37c8 in /workspace/clickhouse
2021.10.03 14:06:12.107619 [ 820 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2851: std::__1::shared_ptr<DB::ThreadGroupStatus>::operator bool() const
2021.10.03 14:06:12.107663 [ 820 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../src/Processors/Executors/PipelineExecutor.cpp:783: operator()
2021.10.03 14:06:12.107694 [ 820 ] {} <Fatal> BaseDaemon: 10.3. inlined from ../base/base/../base/scope_guard.h:94: basic_scope_guard<DB::PipelineExecutor::executeImpl(unsigned long)::$_4::operator()() const::'lambda'()>::invoke()
2021.10.03 14:06:12.107715 [ 820 ] {} <Fatal> BaseDaemon: 10.4. inlined from ../base/base/../base/scope_guard.h:44: ~basic_scope_guard
2021.10.03 14:06:12.107736 [ 820 ] {} <Fatal> BaseDaemon: 10.5. inlined from ../src/Processors/Executors/PipelineExecutor.cpp:798: operator()
2021.10.03 14:06:12.107754 [ 820 ] {} <Fatal> BaseDaemon: 10. ../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_4&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&) @ 0x1c6c5c0a in /workspace/clickhouse
2021.10.03 14:06:12.140950 [ 820 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:0: operator()
2021.10.03 14:06:12.140989 [ 820 ] {} <Fatal> BaseDaemon: 11. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&) @ 0x1c6c5ae3 in /workspace/clickhouse
2021.10.03 14:06:12.154218 [ 820 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: std::__1::function<void ()>::operator=(std::nullptr_t)
2021.10.03 14:06:12.154246 [ 820 ] {} <Fatal> BaseDaemon: 12. ../src/Common/ThreadPool.cpp:277: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xc856b9a in /workspace/clickhouse
2021.10.03 14:06:12.169254 [ 820 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xc8595a2 in /workspace/clickhouse
2021.10.03 14:06:12.169323 [ 820 ] {} <Fatal> BaseDaemon: 14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.10.03 14:06:12.169368 [ 820 ] {} <Fatal> BaseDaemon: 15. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.03 14:06:12.434437 [ 820 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 6017BBB8BEDB5731140B5F8A0F638548. There is no information about the reference checksum.
```

### PR DESCRIPTION
**Pull request by azat**
Found by UBsan fuzzer [1].

  [1]: https://clickhouse-test-reports.s3.yandex.net/29503/a4f2663b8209e0e75021d8b84f932bc162c81857/fuzzer_ubsan/report.html#fail1

Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix null deference for `GROUP BY WITH TOTALS HAVING` (when the column from `HAVING` wasn't selected)

Detailed description / Documentation draft:

Fixes: #29475 (cc @KochetovNicolai )
Fixes: #29687

*NOTE: marked as `Not for changelog` since original PR is not included into any release yet*
*UPD: have to mark it as `Bug fix` since orignial PR was a `Bug fix`*

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

File: src/Processors/Transforms/TotalsHavingTransform.cpp [hunk 1]
```diff
@@ -224,7 +225,7 @@ void TotalsHavingTransform::transform(Chunk & chunk)
             }
         }
 
-        num_rows = columns.front()->size();
+        num_rows = columns.empty() ? countBytesInFilter(*filter_description.data) : columns.front()->size();
```
Comment (azat) [inline src/Processors/Transforms/TotalsHavingTransform.cpp:228]: Egh, I submitted PR w/o real fix, anyway you fix looks better, thanks!

P.S. I was going to fix this by removing `filter_column_name` at the end.
