### PR TITLE
Improvement and fix for use_structure_from_insertion_table_in_table_functions

### LINKED ISSUE #47730: Setting use_structure_from_insertion_table_in_table_functions doesn't work properly with virtual columns.
**Describe what's wrong**
The setting `set use_structure_from_insertion_table_in_table_functions=1` doesn't work properly

setting:
```
set use_structure_from_insertion_table_in_table_functions=1;
insert into function file(data.LineAsString) select 'Hello';
```

table with the same column name:
```
create table test (_path String) engine=Memory;
insert into test select _path from file(data.LineAsString);

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_path String String(size = 0)
_path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (AMBIGUOUS_COLUMN_NAME)
```
here error makes perfect sense, since virtual column `_path` is a LowCardinality(String) but table column is `String`, however, the cause of error shows that something wrong is going on here - apparently the columns matched by name and not by position which is stated in manual. And seemingly due to this we have some wrong behavior here:
```
insert into test select CAST(_path as String) from file(data.LineAsString);

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_path String String(size = 0)
_path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (AMBIGUOUS_COLUMN_NAME)
```
and even more strange here:
```
drop table test;
create table test (_path LowCardinality(String)) engine=Memory;
insert into test select _path from file(data.LineAsString);

Received exception:
Code: 80. DB::Exception: This input format is only suitable for tables with a single column of type String.: While executing File. (INCORRECT_QUERY)
```
not sure about this one - probably this is because `file()` table function produce single `String` column, and virtual columns were not taken into account.

However for table with different than `_path` column name there is no issue:
```
drop table test;
create table test (aaa String) engine=Memory;
insert into test select _path from file(data.LineAsString);
```
but from code it's seems that in this case the setting `use_structure_from_insertion_table_in_table_functions` is ignored and CAST is added.

**Does it reproduce on recent release?**
reproduces on current master

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
For use_structure_from_insertion_table_in_table_functions more flexible insert table structure propagation to table function. Fixed bug with name mapping and using virtual columns. No more need for 'auto' setting.

closes #47730

### CODE REVIEW

File: src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -1394,59 +1396,64 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
-                        have_asterisk = true;
-                    }
-                    else if (!expression->as<ASTLiteral>())
-                    {
-                        use_columns_from_insert_query = false;
-                        break;
-                    }
-                }
+                        if (asterisk)
+                            throw Exception(ErrorCodes::ILLEGAL_COLUMN, "Asterisk cannot be mixed with column list in INSERT SELECT query.");
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1419]: Is it ok that we forbid it only when table function needs a structure hint?
So, this won't work:
```sql
insert into test select c1, * from file(data.parquet)
```
But this will work:
```sql
insert into test select c1, * from file(data.parquet, auto, 'c1 UInt32, c2 UInt32, ...')
```
Why don't set a hint and fallback to schema inference in this case?

File: src/Interpreters/Context.cpp [hunk 2]
```diff
@@ -1394,59 +1396,64 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
-                {
-                    if (!structure_hint.has(column_name) || virtual_column_names.contains(column_name))
-                    {
-                        use_columns_from_insert_query = false;
-                        break;
+                        structure_hint.add({ identifier->name(), insert_column->type });
                     }
+
+                    if (asterisk)
+                        --insert_structure_end;
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1425]: Maybe add a comment with an example?

File: src/Interpreters/Context.cpp [hunk 3]
```diff
@@ -1394,59 +1396,64 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
+                    else
+                        ++insert_column;
                 }
+                else if ((*expression)->as<ASTAsterisk>())
+                {
+                    if (asterisk)
+                        throw Exception(ErrorCodes::ILLEGAL_COLUMN, "Only one asterisk can be used in INSERT SELECT query.");
+                    if (!structure_hint.empty())
+                        throw Exception(ErrorCodes::ILLEGAL_COLUMN, "Asterisk cannot be mixed with column list in INSERT SELECT query.");
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1434]: Same as above, maybe just don't set a hint and fallback to schema inference.

File: src/Interpreters/Context.cpp [hunk 4]
```diff
@@ -1394,59 +1396,64 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
+                else
                 {
-                    /// For input function we should check if input format supports reading subset of columns.
-                    if (table_function_ptr->getName() == "input")
-                        use_columns_from_insert_query = FormatFactory::instance().checkIfFormatSupportsSubsetOfColumns(getInsertFormat());
+                    if (asterisk)
+                        --insert_structure_end;
                     else
-                        use_columns_from_insert_query = table_function_ptr->supportsReadingSubsetOfColumns();
+                        ++insert_column;
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1443]: Why? In case of complex expression we should not set a hint and fallback to schema inference. Now we just ignore this expression, so structure hint will have less columsn than expressions in select. How it will work?
```
insert into test select c1, c2 + 10, c3 from file(data.csv)
```

File: src/Interpreters/Context.cpp [hunk 5]
```diff
@@ -1394,59 +1396,64 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
+                throw Exception(ErrorCodes::NUMBER_OF_COLUMNS_DOESNT_MATCH, "Number of columns in insert table less than required by SELECT expression.");
+
+            if (asterisk)
+            {
+                for (; insert_column != insert_structure_end; ++insert_column)
+                    structure_hint.add({ insert_column->name, insert_column->type });
+            }
+
+            if (!structure_hint.empty())
                 table_function_ptr->setStructureHint(structure_hint);
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1457]: I would prefer not to set a hint when we have a list of column names and format that doesn't support reading subset of columns.
For example if we have `data.csv` with 4 columns but we want to insert into table only two of them:
```
insert into test select c1, c2 from file(data.csv)
```
And it won't work now

File: src/Interpreters/Context.cpp (hunk 4 above)
Comment (Avogar) [reply src/Interpreters/Context.cpp:1443]: It will lead to `Code: 47. DB::Exception: Missing columns: 'c2' `

File: src/Interpreters/Context.cpp (hunk 2 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/Context.cpp:1425]: not clear comment about what?

Comment (Avogar) [reply src/Interpreters/Context.cpp:1425]: Why we decrement  `insert_structure_end;` in case of `asterisk` here. It was not easy to understand while reading. (maybe just for me).
Or maybe write a comment before the loop with explanation what we do and why (just to help future readers ti understand it better)

File: src/Interpreters/Context.cpp (hunk 5 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/Context.cpp:1457]: so, we want `use_structure_from_insertion_table_in_table_functions=auto`?

File: src/Interpreters/Context.cpp (hunk 1 above)
Comment (Avogar) [reply src/Interpreters/Context.cpp:1419]: > the whole idea is to infer structure from insert table

Yes, but I think we should not throw an exception when we cannot do it and just don't set a hint. Most of the userrs don't know about `use_structure_from_insertion_table_in_table_functions` setting, so they will think that smth is broken when they cannot read data from file.

> or we are talking about using `use_structure_from_insertion_table_in_table_functions=auto` again

Maybe ... I just think that by default we definitely should use structure from insert table only when it's possible and don't throw an exception when it's not possible. We can do it under value `1` not `auto`. But if you think that  value `1` means "use structure from insertion table or throw", than yes, I am talking about `auto` again.

File: src/Interpreters/Context.cpp (hunk 4 above)
Comment (Avogar) [reply src/Interpreters/Context.cpp:1443]: I guess it's again about `auto` value. We should discuss it one more time.

File: src/Interpreters/Context.cpp [hunk 6]
```diff
@@ -1393,62 +1395,128 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
-                }
 
-                /// Check that all identifiers are column names from insertion table and not virtual column names from storage.
-                for (const auto & column_name : columns_names)
+                    asterisk = true;
+                }
+                else if (auto * function = (*expression)->as<ASTFunction>())
                 {
-                    if (!structure_hint.has(column_name) || virtual_column_names.contains(column_name))
+                    if (use_structure_from_insertion_table_in_table_functions == 2 && find_identifier(function))
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1484]: I see that in case when `use_structure_from_insertion_table_in_table_functions=1` and `find_identifier(function)=true` we just skip this expression. Maybe better to throw an exception? Or it's ok that we will have an exception `missing column` later?

File: src/Interpreters/Context.cpp [hunk 7]
```diff
@@ -1393,62 +1395,128 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
...
+                if (expression == expression_list.end())
+                {
+                    if (asterisk)
+                    {
+                        for (; insert_column != insert_structure_end; ++insert_column)
+                            structure_hint.add({ insert_column->name, insert_column->type });
+                    }
+
+                    if (!structure_hint.empty())
+                        table_function_ptr->setStructureHint(structure_hint);
```
Comment (Avogar) [inline src/Interpreters/Context.cpp:1515]: I still think when we have `auto` we should not set a hint when we have a list of column names and format that doesn't support reading subset of columns.

File: src/Interpreters/Context.cpp (hunk 6 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/Context.cpp:1484]: There can be a case when having identifier in function will work - for example `select a+1,a`, so I think it's better to left this opportunity for optimization.

File: src/Interpreters/Context.cpp (hunk 7 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/Context.cpp:1515]: but column list can be a full list of columns - this approach gives more flexibility - for example for csv with 2 columns we can have `SELECT c1, _path, c2`

Comment (Avogar) [reply src/Interpreters/Context.cpp:1519]: > this approach gives more flexibility 

Yes, that's true. But there is always a possibility that there is not a full list of columns, and in `auto` I would prefer the way that will always work. With schema inference it will always work. 

Anyway, that's a rare case I think, we can leave current way if you prefer it more.

**Review by Avogar — APPROVED** [review]

File: src/Interpreters/Context.cpp (hunk 7 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/Context.cpp:1519]: >in auto I would prefer the way that will always work

yeah, it makes sense... will fix this
