### PR TITLE
Lower memory usage in vertical merges

### LINKED ISSUE #57773: Vertical merge could consume a lot of memory
See the stack trace with memory allocations.
https://pastila.nl/?0001d4ae/376da778773f6223011c64914c06ec3e#xGswcayE+r52tA2oBpGs6A==

Stack trace in short:
There are big allocations (up to 2,5Gb) happen in 
```
Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long)
DB::ColumnString::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) | DB::ColumnString::insertFrom(DB::IColumn const&, unsigned long)
DB::ColumnString::gather(DB::ColumnGathererStream&)','DB::ColumnGathererStream::merge()
```

That happen because the value size is highly different. Table has a string column with 
```
SELECT quantilesExactExclusive(0.5, 0.9, 0.99, 0.999)(length(column))
FROM table

┌─quantilesExactExclusive(0.5, 0.9, 0.99, 0.999)(length(column))─┐
│ [79064,121150,135871,1413296]                                      │
└────────────────────────────────────────────────────────────────────┘
```

```
SELECT
    max(length(column))
FROM table
┌─max(length(column))─┐
│      9834237        │
└─────────────────────┘
```

There is a big string could happen.

ColumnGathererStream doesn't care about column size in bytes. It always takes `#define DEFAULT_BLOCK_SIZE 65409` rows in gathered column.

That is very annoying reason why 8Gb memory is not enough for small databases. it leads to the situation when all data is read into the memory.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Lower memory usage in vertical merges

Fixes #57773.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit d3cdc8826eb5209562ae743c7a385a7f33bbc015 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59340/d3cdc8826eb5209562ae743c7a385a7f33bbc015/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59340/d3cdc8826eb5209562ae743c7a385a7f33bbc015/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Processors/Transforms/ColumnGathererTransform.h [hunk 1]
```diff
@@ -134,14 +137,17 @@ void ColumnGathererStream::gather(Column & column_res)
...
+        column_res.reserve(size_to_reserve);
     }
 
-    size_t cur_size = column_res.size();
     next_required_source = -1;
 
-    while (row_source_pos < row_sources_end && cur_size < cur_block_preferred_size)
+    while (row_source_pos < row_sources_end
+        && column_res.size() < block_preferred_size_rows
+        && column_res.allocatedBytes() < block_preferred_size_bytes)
```
Comment (nickitat) [inline src/Processors/Transforms/ColumnGathererTransform.h:150]: really minor. maybe it makes sense to use `byteSize()` because I'd expect `block_size_bytes` to refer to the actual data size.

**Review by nickitat — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

File: src/Processors/Transforms/ColumnGathererTransform.h (hunk 1 above)
Comment (CurtizJ) [reply src/Processors/Transforms/ColumnGathererTransform.h:150]: I checked that `allocatedBytes` is [used](https://github.com/ClickHouse/ClickHouse/blob/5a024dfc0936e062770d0cfaad0805b57c1fba17/src/Processors/Merges/Algorithms/MergedData.h#L125) in`MergedData` and did the same. But we can change it in both places.

**Comment by azat** [comment]
FWIW this patch changes serialization for LowCardinality, so you can get `DataAfterMergeDiffersFromReplica` (`We will download merged part from replica to force byte-identical result.`) error during upgrading replicas
