### PR TITLE
Vector search: Pre-filtering & post-filtering 

### LINKED ISSUE #78161: Clickhouse server process can assert / crash if vector index search is performed after initial range pruning by primary key or other skip index
### Company or project name

Clickhouse Vector Search

### Describe what's wrong

Following type of query can assert or crash Clickhouse server process -

```sql
SELECT id FROM items
PREWHERE id < 300000
ORDER BY cosineDistance(vector, [-0.004410677 ...])
LIMIT 10
```
The EXPLAIN looks like this -

```
Expression (Project names)
  Limit (preliminary LIMIT (without OFFSET))
    Sorting (Sorting for ORDER BY)
      Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
        ReadFromMergeTree (default.items)
        Indexes:
          PrimaryKey
            Keys:
              id
            Condition: (id in (-Inf, 299999])
            Parts: 1/1
            Granules: 175/575
          Skip
            Name: vector_index
            Description: vector_similarity GRANULARITY 100000000
            Parts: 1/1
            Granules: 18446744073709551566/175     <<<<<< 
```
Note the last line. 

The assert is -

```
2025.03.24 04:52:09.160569 [ 1239968 ] {fb2b487a-511d-4568-b318-d5c4bd64bf07} <Error> PipelineExecutor: Code: 49. DB::Exception: 
Trying to get non existing mark 384307168202282550, while size is 576: While executing 
MergeTreeSelect(pool: ReadPool, algorithm: Thread). (LOGICAL_ERROR), 
Stack trace (when copying this message, always include the lines below):
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Version : 25.4.1
Check above query

### Expected behavior

No errors/crashes

### Error message and/or stacktrace

```
0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000176614d2
1. ./build/./src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d6c5219
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000806beac
3. DB::Exception::Exception<unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, unsigned long&, unsigned long&&) @ 0x00000000080f430b
4. ./build/./src/Storages/MergeTree/MergeTreeIndexGranularityAdaptive.cpp:24: DB::MergeTreeIndexGranularityAdaptive::getMarkRows(unsigned long) const @ 0x0000000013c25558
5. ./build/./src/Storages/MergeTree/MergeTreeReadTask.cpp:139: DB::MergeTreeReadTask::estimateNumRows() const @ 0x0000000013cbb1ca
6. ./build/./src/Storages/MergeTree/MergeTreeReadTask.cpp:169: DB::MergeTreeReadTask::read() @ 0x0000000013cbb3f2
7. ./src/Storages/MergeTree/MergeTreeSelectAlgorithms.h:38: DB::MergeTreeThreadSelectAlgorithm::readFromTask(DB::MergeTreeReadTask&) @ 0x000000001463702c
8. ./build/./src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:204: DB::MergeTreeSelectProcessor::read() @ 0x0000000013cc534e
9. ./build/./src/Storages/MergeTree/MergeTreeSource.cpp:229: DB::MergeTreeSource::tryGenerate() @ 0x000000001463e929
10. ./build/./src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x00000000141f6c05
11. ./build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001420f6e1
12. ./build/./src/Processors/Executors/PipelineExecutor.cpp:296: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014205285
13. ./build/./src/Processors/Executors/PipelineExecutor.cpp:262: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000014205f81
14. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000d7f0bbb
15. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000000d7f5de2
16. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000d7ee836
17. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000d7f419b
18. ? @ 0x000072b69de9caa4
19. ? @ 0x000072b69df29c3c
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shankar-iyer**
Resolves #78161

### Changelog category (leave one):
- New feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Clickhouse vector search now supports both pre-filtering and post-filtering and provides related settings for finer control. (issue #78161)

### CODE REVIEW

**Comment by shankar-iyer** [comment]
@rschu1ze

File: src/Core/Settings.cpp [hunk 1]
```diff
@@ -6547,6 +6547,12 @@ SELECT queries with LIMIT bigger than this setting cannot use vector similarity
 )", EXPERIMENTAL) \
     DECLARE(UInt64, hnsw_candidate_list_size_for_search, 256, R"(
 The size of the dynamic candidate list when searching the vector similarity index, also known as 'ef_search'.
+)", EXPERIMENTAL) \
+    DECLARE(Bool, ann_prefer_pre_filtering, false, R"(
```
Comment (rschu1ze) [inline src/Core/Settings.cpp:6551]: I didn't look at the entire PR yet but could we use setting name "vector_search_prefiltering" instead?

File: src/Core/Settings.cpp [hunk 2]
```diff
@@ -6547,6 +6547,12 @@ SELECT queries with LIMIT bigger than this setting cannot use vector similarity
...
+If a vector search query has a WHERE clause, this parameter determines if the predicates are evaluated first (pre-filtering) OR if the vector similarity index is looked up first (post-filtering). Please check documentation for additional specifics.
+)", EXPERIMENTAL) \
+    DECLARE(UInt64, ann_post_filter_multiplier, 1, R"(
```
Comment (rschu1ze) [inline src/Core/Settings.cpp:6554]: `ann_post_filter_multiplier` --> `vector_search_postfilter_multiplier`

File: src/Processors/QueryPlan/Optimizations/useVectorSearch.cpp [hunk 3]
```diff
@@ -126,6 +143,11 @@ size_t tryUseVectorSearch(QueryPlan::Node * parent_node, QueryPlan::Nodes & /*no
         else if (child->type == ActionsDAG::ActionType::INPUT) /// old analyzer
         {
             search_column = child->result_name;
+            /// if there is a Filter step, then the result_name is "__table1.vec"
+            if (search_column.find('.') != std::string::npos)
```
Comment (rschu1ze) [inline src/Processors/QueryPlan/Optimizations/useVectorSearch.cpp:147]: Could use `.contains()`.

File: tests/queries/0_stateless/02354_vector_search_post_filtering.sql [hunk 4]
```diff
@@ -0,0 +1,91 @@
+-- Tags: no-fasttest, no-ordinary-database
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02354_vector_search_post_filtering.sql:1]: Let's unite this test with the other one to 02354_vector_search_pre_and_postfiltering.sql.

File: src/Core/Settings.cpp (hunk 1 above)
Comment (shankar-iyer) [reply src/Core/Settings.cpp:6551]: Did you mean "vector_search_filtering" (because one of the values is "postfilter")? 

"prefilter" will always work, irrespective of query shape. I don't see a case for "prefilter" to throw an exception.

The only case that "postfilter" can thrown an exception is when all the ranges of a part were not selected by a PK filter. Currently, the PR transparently falls back to KNN on such a part. Do you think we should thrown an exception?

File: src/Processors/QueryPlan/Optimizations/useVectorSearch.cpp (hunk 3 above)
Comment (shankar-iyer) [reply src/Processors/QueryPlan/Optimizations/useVectorSearch.cpp:147]: Thanks, will change!

File: tests/queries/0_stateless/02354_vector_search_post_filtering.sql (hunk 4 above)
Comment (shankar-iyer) [reply tests/queries/0_stateless/02354_vector_search_post_filtering.sql:1]: Alright, I also missed a testcase for the "multiplier" setting, added that.

File: src/Core/Settings.cpp (hunk 1 above)
Comment (shankar-iyer) [reply src/Core/Settings.cpp:6551]: And "auto" just maps to "postfilter" right now?

Comment (shankar-iyer) [reply src/Core/Settings.cpp]: Done.

File: src/Core/Settings.cpp (hunk 2 above)
Comment (shankar-iyer) [reply src/Core/Settings.cpp]: Done.

File: tests/queries/0_stateless/02354_vector_search_post_filtering.sql (hunk 4 above)
Comment (shankar-iyer) [reply tests/queries/0_stateless/02354_vector_search_post_filtering.sql]: Done, combined both files and added a testcase for "multiplier"

**Comment by shankar-iyer** [comment]
Good catch by AST fuzzer - need to put a max. value check on the new multiplier setting.

**Comment by shankar-iyer** [comment]
Only failure in latest run is in `03355_join_to_in_optimization` : https://github.com/ClickHouse/ClickHouse/issues/80007

**Comment by shankar-iyer** [comment]
@rschu1ze I pushed a commit with a couple of fixups. The new test is failing in `ParallelReplicas` due to just additional  indentation in the EXPLAIN output. The test does have` explicit parallel_replicas_local_plan=1`

Other failure in "Stateless tests (debug, distributed plan, s3 storage) is unrelated test : `01169_alter_partition_isolation_stress`

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@shankar-iyer LGTM. Perhaps you like to add a test for explicit PREWHERE clauses (could also be done in a separate PR).

**Comment by shankar-iyer** [comment]
Latest CI run -
- New test `02354_vector_search_postfiltering_bug` needs `no-msan, no-tsan` tags in addition to `no-asan, no-ubsan `because test is a long-running test
- Corrected a github link in the doc
- Because the multiplier parameter now is a `float`, need an additional `std::isfinite()` validation for `(multiplier x limit)`

File: src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp [hunk 5]
```diff
@@ -415,9 +417,14 @@ MergeTreeIndexConditionVectorSimilarity::MergeTreeIndexConditionVectorSimilarity
     , index_column(index_column_)
     , metric_kind(metric_kind_)
     , expansion_search(context->getSettingsRef()[Setting::hnsw_candidate_list_size_for_search])
+    , postfilter_multiplier(context->getSettingsRef()[Setting::vector_search_postfilter_multiplier])
+    , max_limit(context->getSettingsRef()[Setting::max_limit_for_vector_search_queries])
 {
     if (expansion_search == 0)
         throw Exception(ErrorCodes::INVALID_SETTING_VALUE, "Setting 'hnsw_candidate_list_size_for_search' must not be 0");
+    if (!std::isfinite(postfilter_multiplier) || postfilter_multiplier < 0.0 ||
+        (parameters && !std::isfinite(postfilter_multiplier * parameters->limit)))
```
Comment (rschu1ze) [inline src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:426]: Minor comment, and we can fix it in a follow-up PR:

It is not clear to me when `limit` in `parameters` can be non-finite. As far as I see ([example](https://fiddle.clickhouse.com/12cd380a-6e15-4728-a080-53950179e6e0)), ClickHouse rejects such cases already. Likewise, negative LIMITs are also prohibited ([examples](https://fiddle.clickhouse.com/13a891f6-c730-49f1-8575-fe96ab989248)).

I actually looked at the failing fuzzer run ([here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79854&sha=997cb4624710d680220c08011c4ee04c26877a07&name_0=PR&name_1=AST+fuzzer+%28amd_ubsan%29)) and found this crashing query:

```
2025.05.11 17:11:14.103188 [ 1468 ] {} <Fatal> BaseDaemon: (version 25.5.1.1, build id: 9A734D409A5D22DC249C6808C9FBADA467686F46, git hash: 9f266333696568acdf004d1a1f403ab705b43eaf) (from thread 1462) (query_id: e4f4c0fa-504a-4765-a078-82ae9c759a51) (query: SELECT DISTINCT 1008, 16 AND toNullable(10) AND 16 AS alias287 FROM tab RIGHT JOIN viewExplain('EXPLAIN', 'indexes = 1', (SELECT id FROM tab PREWHERE date != '2025-01-02' ORDER BY L2Distance(vec, [1., 1.]) ASC LIMIT 256  WITH TIES SETTINGS vector_search_filter_strategy = 'postfilter')) AS alias291 ON attr2 <=> alias291.date PREWHERE date IS NOT NULL WHERE isNotNull(isNullable(58) AND 16 AS alias292, 16) ORDER BY ALL ASC NULLS FIRST LIMIT 9223372036854775807 SETTINGS
```

I could not reproduce the issue

```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:471
```

with an UBSAN build locally. I also experimented with some weird combinations of LIMIT and vector_search_postfilter_multiplier but again could not reproduce the issue.

Just to understand, do you know what was the problem in the first place? Is it that the result of a big float (limit) with another big float (postfilter_multiplier) is so big that it cannot be represented as a size_t (`static_cast<size_t>(limit * postfilter_multiplier))`? That would be undefined behavior indeed.

What we should do in any case (this or a separate PR) is to move check `(parameters && !std::isfinite(postfilter_multiplier * parameters->limit)))` somewhere to l. 472 so we don't duplicate the code unnecessary.

**Review by rschu1ze — APPROVED** [review]

File: src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp (hunk 5 above)
Comment (shankar-iyer) [reply src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:426]: Yes, a big multiplier with a small limit that crosses INF. Below are the values that caused the assert and now caught by the new code -

```
ip-172-31-41-45.eu-central-1.compute.internal :) select id from tab
  order by cosineDistance(vec, [1.0, 1.0]) limit 256
  settings vector_search_postfilter_multiplier=3.4028234663852886e38;

SELECT id
FROM tab
ORDER BY cosineDistance(vec, [1., 1.]) ASC
LIMIT 256
SETTINGS vector_search_postfilter_multiplier = 3.4028234663852886e38

Query id: 32dedbc7-4cd2-462e-a15e-00e52590851f


Elapsed: 0.015 sec.

Received exception from server (version 25.5.1):
Code: 471. DB::Exception: Received from localhost:9000. DB::Exception: Setting 'vector_search_postfilter_multiplier' must be bigger than 0.0. (INVALID_SETTING_VALUE)
```

The assert will be seen only in ubsan build. In normal build, silent truncation should be happening. I got 256 and the big float value from the Fuzz'ed query -

```
2025.05.11 17:11:13.017171 [ 175 ] {e4f4c0fa-504a-4765-a078-82ae9c759a51} <Debug> executeQuery: (from [::ffff:127.0.0.1]:39114) (query 30, line 151) SELECT DISTINCT 1008, 16 AND toNullable(10) AND 16 AS alias287 
FROM tab RIGHT JOIN viewExplain('EXPLAIN', 'indexes = 1', (SELECT id FROM tab PREWHERE date != '2025-01-02' 
ORDER BY L2Distance(vec, [1., 1.]) ASC LIMIT 256 WITH TIES SETTINGS vector_search_filter_strategy = 
'postfilter')) AS alias291 ON attr2 <=> alias291.date PREWHERE date IS NOT NULL WHERE isNotNull(isNullable(58) 
AND 16 AS alias292, 16) ORDER BY ALL ASC NULLS FIRST LIMIT 9223372036854775807 SETTINGS 
vector_search_postfilter_multiplier = 3.4028234663852886e38 (stage: Complete)
```
Yes, I can modify the code in a follow-on PR.

**Comment by shankar-iyer** [comment]
Only 2 failures in latest CI run -

"Integration tests (tsan, 1/6)" : 
`test_host_regexp_multiple_ptr_records/test.py::test_host_regexp_multiple_ptr_v6 `

"CH Inc sync" : Investigated.
