### PR TITLE
Fix possible "Cannot finalize buffer after cancellation" in estimateCompressionRatio()

### LINKED ISSUE #87380: [CI crash] Double destruction of AggregatedDataVariants in AggregatingTransform
<details><summary>Stack trace details</summary>

The sipHash64(st.trace_full) is 1638650557911007942
The trace is from the master or release branch: True

The query for CIDB to compare the trace with the known one:

```sql
WITH
    (
        SELECT groupArrayDistinct(cleanStackTrace(trace_full) AS trace) FROM default.stack_traces
        WHERE sipHash64(trace) IN (1638650557911007942, {ANOTHER_TRACE_HASH}) -- FIXME: replace with the known hash
    ) AS traces,
    1.97 AS alpha,
    stack_frame_weights AS (
        WITH
            (
                SELECT count()
                FROM default.stack_traces
                FINAL
            ) AS total,
            2.0 AS beta,
            3.7 AS gamma
        SELECT
            arrayJoin(cleanStackTrace(trace_full)) AS frame,
            countDistinct(trace_full) AS count,
            log(total / count) AS IDF,
            sigmoid(beta * (IDF - gamma)) AS weight
        FROM default.stack_traces
        FINAL
        GROUP BY frame
    ),
    (SELECT groupArray(weight) AS w, groupArray(frame) AS f FROM stack_frame_weights) AS weights,
    (trace -> arrayMap((_frame, pos) -> (pow(pos, -alpha) * arrayFirst(w, f -> (f = _frame), weights.w, weights.f)), trace, arrayEnumerate(trace))) AS get_trace_weights,
    (arr -> arrayStringConcat(arr, '\n')) AS joinArr

SELECT arraySimilarity(traces[1], traces[2], get_trace_weights(traces[1]) AS weights1, get_trace_weights(traces[2]) AS weights2) AS similarity,
    arrayLevenshteinDistanceWeighted(traces[1], traces[2], weights1, weights2),
    joinArr(traces[1]), joinArr(traces[2]), joinArr(weights1), joinArr(weights2)

```
</details>

The following new stack trace from CI Logs `system.crash_log` found:

```
   DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long)
   DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&)
   DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)
   DB::WriteBuffer::finalize()
   ~AggregationFunctionEstimateCompressionRatioData
   DB::IAggregateFunctionDataHelper<DB::(anonymous namespace)::AggregationFunctionEstimateCompressionRatioData, DB::(anonymous namespace)::AggregateFunctionEstimateCompressionRatio>::destroy(char*) const
   DB::Aggregator::destroyWithoutKey(DB::AggregatedDataVariants&) const
   DB::Aggregator::destroyAllAggregateStates(DB::AggregatedDataVariants&) const
   DB::AggregatedDataVariants::~AggregatedDataVariants()
   void std::__destroy_at[$ABI]<DB::AggregatedDataVariants, 0>(DB::AggregatedDataVariants*)
   void std::allocator_traits<std::allocator<DB::AggregatedDataVariants>>::destroy[$ABI]<DB::AggregatedDataVariants, void, 0>(std::allocator<DB::AggregatedDataVariants>&, DB::AggregatedDataVariants*)
   void std::__shared_ptr_emplace<DB::AggregatedDataVariants, std::allocator<DB::AggregatedDataVariants>>::__on_zero_shared_impl[$ABI]<std::allocator<DB::AggregatedDataVariants>, 0>()
   std::__shared_ptr_emplace<DB::AggregatedDataVariants, std::allocator<DB::AggregatedDataVariants>>::__on_zero_shared()
   std::__shared_count::__release_shared[$ABI]()
   std::__shared_weak_count::__release_shared[$ABI]()
   ~shared_ptr
   void std::__destroy_at[$ABI]<std::shared_ptr<DB::AggregatedDataVariants>, 0>(std::shared_ptr<DB::AggregatedDataVariants>*)
   void std::allocator_traits<std::allocator<std::shared_ptr<DB::AggregatedDataVariants>>>::destroy[$ABI]<std::shared_ptr<DB::AggregatedDataVariants>, void, 0>(std::allocator<std::shared_ptr<DB::AggregatedDataVariants>>&, std::shared_ptr<DB::AggregatedDataVariants>*)
   std::vector<std::shared_ptr<DB::AggregatedDataVariants>, std::allocator<std::shared_ptr<DB::AggregatedDataVariants>>>::__base_destruct_at_end[$ABI](std::shared_ptr<DB::AggregatedDataVariants>*)
   std::vector<std::shared_ptr<DB::AggregatedDataVariants>, std::allocator<std::shared_ptr<DB::AggregatedDataVariants>>>::__clear[$ABI]()
   std::vector<std::shared_ptr<DB::AggregatedDataVariants>, std::allocator<std::shared_ptr<DB::AggregatedDataVariants>>>::__destroy_vector::operator()[$ABI]()
   ~vector
   DB::ManyAggregatedData::~ManyAggregatedData()
   std::default_delete<DB::ManyAggregatedData>::operator()[$ABI](DB::ManyAggregatedData*) const
   std::__shared_ptr_pointer<DB::ManyAggregatedData*, std::default_delete<DB::ManyAggregatedData>, std::allocator<DB::ManyAggregatedData>>::__on_zero_shared()
   std::__shared_count::__release_shared[$ABI]()
   std::__shared_weak_count::__release_shared[$ABI]()
   ~shared_ptr
   DB::AggregatingTransform::~AggregatingTransform()
   void std::__destroy_at[$ABI]<DB::AggregatingTransform, 0>(DB::AggregatingTransform*)
   void std::allocator_traits<std::allocator<DB::AggregatingTransform>>::destroy[$ABI]<DB::AggregatingTransform, void, 0>(std::allocator<DB::AggregatingTransform>&, DB::AggregatingTransform*)
   void std::__shared_ptr_emplace<DB::AggregatingTransform, std::allocator<DB::AggregatingTransform>>::__on_zero_shared_impl[$ABI]<std::allocator<DB::AggregatingTransform>, 0>()
   std::__shared_ptr_emplace<DB::AggregatingTransform, std::allocator<DB::AggregatingTransform>>::__on_zero_shared()
   std::__shared_weak_count::__release_shared[$ABI]()
   ~shared_ptr
   void std::__destroy_at[$ABI]<std::shared_ptr<DB::IProcessor>, 0>(std::shared_ptr<DB::IProcessor>*)
   void std::allocator_traits<std::allocator<std::shared_ptr<DB::IProcessor>>>::destroy[$ABI]<std::shared_ptr<DB::IProcessor>, void, 0>(std::allocator<std::shared_ptr<DB::IProcessor>>&, std::shared_ptr<DB::IProcessor>*)
   std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__base_destruct_at_end[$ABI](std::shared_ptr<DB::IProcessor>*)
   std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__clear[$ABI]()
   std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__destroy_vector::operator()[$ABI]()
   ~vector
   void std::__destroy_at[$ABI]<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, 0>(std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>*)
   void std::allocator_traits<std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::destroy[$ABI]<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, void, 0>(std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>&, std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>*)
   void std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared_impl[$ABI]<std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>, 0>()
   std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared()
   std::__shared_count::__release_shared[$ABI]()
   std::__shared_weak_count::__release_shared[$ABI]()
   ~shared_ptr
   DB::QueryPipeline::~QueryPipeline()
   DB::QueryPipeline::reset()
   DB::BlockIO::onException(bool)
   DB::TCPHandler::runImpl()
   DB::TCPHandler::run()
   Poco::Net::TCPServerConnection::start()
   Poco::Net::TCPServerDispatcher::run()
   Poco::PooledThread::run()
   Poco::(anonymous namespace)::RunnableHolder::run()
   Poco::ThreadImpl::runnableEntry(void*)
```

Possible causes:  
- Incorrect manual memory management leading to double deletion
- Improper use of shared pointers causing multiple destruction
- Race condition during destruction of shared resources
- Improper cleanup of aggregated data structures in Aggregator
- Incorrect lifecycle management of AggregatedDataVariants

The stack trace appeared in the following checks:  
- [Stress test (azure, amd_msan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=2850c039acfefd705bd75edee7a83af1cdaee2e5&name_0=MasterCI&name_1=Stress%20test%20%28azure%2C%20amd_msan%29&name_1=Stress%20test%20%28azure%2C%20amd_msan%29)

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix possible `Cannot finalize buffer after cancellation` in `estimateCompressionRatio()`. Fixes: https://github.com/ClickHouse/ClickHouse/issues/87380

Fixes https://github.com/ClickHouse/clickhouse-core-incidents/issues/1265.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
Ok, but:

- it argues, if it is a bug fix it needs a test;
- the fix looks fragile, do we have more code like this, shouldn't we put the check inside the finalize method?

**Comment by azat** [comment]
> it argues, if it is a bug fix it needs a test;

The fix looks simple to me, and I am not sure that the test worth it, since it will be either "stress" test or requires some failpoints

> the fix looks fragile, do we have more code like this

Likely...

> shouldn't we put the check inside the finalize method?

It actually has an explicit check in finalize - https://github.com/ClickHouse/ClickHouse/blob/48f3d59232b0606f21ee18af443b736349948902/src/IO/WriteBuffer.cpp#L89-L90

I guess, the reason was to avoid misuse, but if cancel happens during unwind maybe it is OK to allow finalize it, but this will require one more flag (or make `cancel` some `enum`)

@CheSema WDYT?

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp [hunk 1]
```diff
@@ -59,9 +59,10 @@ struct AggregationFunctionEstimateCompressionRatioData
 
     [[maybe_unused]] ~AggregationFunctionEstimateCompressionRatioData()
     {
-        if (compressed_buf)
+        /// WriteBuffer can be cancelled on exception
```
Comment (CheSema) [inline src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: It is interesting what is `[[maybe_unused]]` for here.

Could we do not do `finalize` call in the d-tor? It is tottaly ok to cancel buffers in d-tor, but not finalize.

Comment (azat) [reply src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: > It is interesting what is [[maybe_unused]] for here.

I guess clangd/tidy cannot handle explicit dtor calls (like we have in `IAggregateFunctionDataHelper::destroy`)

> Could we do not do finalize call in the d-tor? It is tottaly ok to cancel buffers in d-tor, but not finalize.

Ok

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by alexey-milovidov** [comment]
Ok. Now I'm concerned about the failing tests.

`test_checking_s3_blobs_paranoid` - this is by @CheSema, let's make sure he is aware and will fix.

**Comment by alexey-milovidov** [comment]
> python3 ./ci/jobs/scripts/workflow_hooks/new_tests_check.py

Still needs something to please the CI.

**Comment by azat** [comment]
>[Integration tests (amd_tsan, 1/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=93068&sha=f3d3f9214795f4bc4e74843a8aa96e9f00ac0edc&name_0=PR&name_1=Integration%20tests%20%28amd_tsan%2C%201%2F6%29)

- https://github.com/ClickHouse/ClickHouse/issues/93185

**Comment by azat** [comment]
>Still needs something to please the CI.

I don't think it worth to add a test, the code is not complex, function is not major and the test will require extra failpoint to make it deterministic

**Comment by alexey-milovidov** [comment]
@azat, then the path is as follows:
- change the category to Improvement;
- ask @maxknv to implement a fix for CI, so it reruns the "Finish Workflow" check on each edit of the description.

**Comment by alexey-milovidov** [comment]
In the meantime, let's ignore all complications and merge.
