### PR TITLE
Validate create query after altering tables

### LINKED ISSUE #67508: `ALTER` query can make table definition invalid
**Describe what's wrong**

When a column is added to a table, the materialized expression (and maybe other expressions) might make the table definition invalid. E.g.: defining an alias with an already existing name. No error is thrown on alter, but only on the first insert after the alter.

[Repro](https://fiddle.clickhouse.com/5746afd4-ffbc-4da9-b4b8-4924b2324357):
```
CREATE TABLE test
(
    str String,
    mat_1 String MATERIALIZED concat(str, 'a' AS a),
)
ENGINE = MergeTree()
ORDER BY tuple();

INSERT INTO test (str) VALUES ('asd1');

ALTER TABLE test ADD COLUMN mat_2 String MATERIALIZED concat(str, 'b' AS a);

INSERT INTO test (str) VALUES ('asd2');
```

Result:
```
Received exception from server (version 24.6.2):
Code: 179. DB::Exception: Received from localhost:9000. DB::Exception: Different expressions with the same alias a:
'b' AS a
and
'a' AS a
: While processing 'b' AS a. (MULTIPLE_EXPRESSIONS_FOR_ALIAS)
(query: INSERT INTO test (str) VALUES ('asd2');)

```

**Does it reproduce on the most recent release?**

Yes.

**How to reproduce**

See above.

**Expected behavior**

The `ALTER` query should fail if it makes the table definition invalid.

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
Fixes #67508 https://github.com/ClickHouse/ClickHouse/issues/68414

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Prevent `ALTER` queries that would make the `CREATE` query of tables invalid. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 2454b6840fc3e709dc7efc4a837d87eda088b1a0 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68574/2454b6840fc3e709dc7efc4a837d87eda088b1a0/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68497/9dee9ecfb4adee4cff099f13afe61bdc2c38170e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -1493,7 +1493,16 @@ void StorageReplicatedMergeTree::setTableStructure(const StorageID & table_id, c
...
     setProperties(new_metadata, old_metadata);
 
-    DatabaseCatalog::instance().getDatabase(table_id.database_name)->alterTable(local_context, table_id, new_metadata);
+    try
+    {
+        DatabaseCatalog::instance().getDatabase(table_id.database_name)->alterTable(local_context, table_id, new_metadata);
+    }
+    catch (...)
+    {
+        LOG_ERROR(log, "Failed to set table structure, reverting changes");
```
[the remark this answers is not in the document]
Comment (antaljanosbenjamin) [reply src/Storages/StorageReplicatedMergeTree.cpp:1502]: I expect that the thrown exception is logged, so I don't want to duplicate it. If you think it is better to log the exception here, I can do that. However I have some issues with the current solution (horrible FastTest failure) that I need to fix first.

File: src/Databases/DatabasesCommon.cpp [hunk 2]
```diff
@@ -31,8 +35,65 @@ namespace ErrorCodes
...
+        context->getSettingsRef().max_parser_backtracks);
+    const auto & new_query = new_query_raw->as<const ASTCreateQuery &>();
+    /// If there are no columns, then there is nothing much we can do
+    if (!new_query.columns_list || !new_query.columns_list->columns)
+        return;
+
+    const auto & columns = *new_query.columns_list;
+    /// Do some basic sanity checks. Let's enforce strict rules, just like on CREATE, because otherwise the default expressions might not be checked
+    const auto columns_desc
+        = InterpreterCreateQuery::getColumnsDescription(*columns.columns, context, LoadingStrictnessLevel::CREATE, false);
```
Comment (antaljanosbenjamin) [inline src/Databases/DatabasesCommon.cpp:61]: This is something I am not happy about, but don't see any other easy way. One solution might be to extract the logic from `getColumnsDescription` that creates `default_expr_list`, then `validateColumnsDefaultsAndGetSampleBlock` could be called outside of `getColumnsDescription`. What do you think, does it worth to extract the logic, or just use `CREATE` here?

Comment (tavplubix) [reply src/Databases/DatabasesCommon.cpp:61]: This is fine as is

Comment (antaljanosbenjamin) [reply src/Databases/DatabasesCommon.cpp]: I ended up separating it, because:
1. `getColumnsDescription` with `LoadingStrictnessLevel::CREATE` does a lot of checks that might fail without the correct context (e.g. session settings allow some suspicious/experimental thing), so I had to lower the level to `SECONDARY_CREATE`. But that doesn't check the default expressions. I tried to only validate, but not evaluate the default expressions, but that breaks `ATTACH` queries. So I ended up separating the logic that is necessary to validate default expressions.

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 3]
```diff
@@ -10451,7 +10461,7 @@ void StorageReplicatedMergeTree::createAndStoreFreezeMetadata(DiskPtr disk, Data
 }
 
 
-void StorageReplicatedMergeTree::adjustCreateQueryForBackup(ASTPtr & create_query) const
+void StorageReplicatedMergeTree::adjustCreateQueryForBackup(ASTPtr & create_query, ContextPtr local_context) const
```
Comment (antaljanosbenjamin) [inline src/Storages/StorageReplicatedMergeTree.cpp:10464]: This is wrong, we should use the same context as for the metadata.

**Comment by antaljanosbenjamin** [comment]
@alexkats @tavplubix I added a commit in private to make the tests pass with SMT, please also take a look at that commit. If it is fine, then please somehow sign that you have checked that, probably approving the sync PR is the most straightforward.

**Comment by antaljanosbenjamin** [comment]
The stress test failure is not related, see [the issue](https://github.com/ClickHouse/ClickHouse/issues/70169) about it.

File: src/Databases/DatabasesCommon.cpp [hunk 4]
```diff
@@ -31,8 +42,87 @@ namespace ErrorCodes
...
+    }
+    if (!new_query.storage)
+        return;
+    const auto & storage = *new_query.storage;
+
+    std::optional<KeyDescription> primary_key;
+    /// First get the key description from order by, so if there is no primary key we will use that
+    if (storage.order_by)
+        primary_key = KeyDescription::getKeyFromAST(storage.order_by->ptr(), columns_desc, context);
+    if (storage.primary_key)
```
Comment (alexkats) [inline src/Databases/DatabasesCommon.cpp:114]: Should we check for `primary_key` here as well or not?

**Review by alexkats — APPROVED** [review]

File: src/Databases/DatabasesCommon.cpp (hunk 4 above)
Comment (antaljanosbenjamin) [reply src/Databases/DatabasesCommon.cpp:114]: I think no. Because if we have `storage.primary_key`, then we have to use that anyway. We also have to call `getKeyFromAST` for `storage.order_by` to ensure it is analyzed in the same way as on table creation.

**Comment by antaljanosbenjamin** [comment]
`test_merge_tree_custom_disk_setting` - https://github.com/ClickHouse/ClickHouse/pull/70505
