### PR TITLE
Fix JIT for `Date32` and `Time64` types

### LINKED ISSUE #93674: Logical error: Cannot get native value for column with type A (STID: 2316-2928)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: Cannot get native value for column with type A (STID: 2316-2928)
CI report: [BuzzHouse (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=93339&sha=6fc71f37d0ebc3d271e789280dcd519ce2a97aa8&name_0=PR&name_1=BuzzHouse%20%28arm_asan%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiBDYW5ub3QgZ2V0IG5hdGl2ZSB2YWx1ZSBmb3IgY29sdW1uIHdpdGggdHlwZSBBIChTVElEOiAyMzE2LTI5MjgpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQnV6ekhvdXNlIChhcm1fYXNhbiknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwIEFORCBoZWFkX3JlZiA9ICdjaV9hc3RfZnV6el9sb2NhbF9ydW4nKSBPUiAocHVsbF9yZXF1ZXN0X251bWJlciAhPSAwIEFORCBiYXNlX3JlZiA9ICdtYXN0ZXInKSkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
Error:
Logical error: 'Cannot get native value for column with type Date32'.
---

Failed query:
ALTER TABLE d0.`t13` (UPDATE `c0` = TRUE::Bool, `c1` = '1984-09-29'::Date32::Date32 WHERE (NOT -4453072044078389917::Int = `c0`));
---

Stack trace:
__pthread_kill_implementation @ 0x0000000000082009
__GI_raise @ 0x000000000003a83c
__GI_abort @ 0x0000000000027134
src/Common/Exception.cpp:57: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x000000001e18a3f4
src/Common/Exception.cpp:90: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000001e18b81c
src/Common/Exception.cpp:143: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001e18bd64
./src/Common/Exception.h:172: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000f4db05c
./src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000f4da348
./src/Common/Exception.h:190: DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000f4e1fa0
src/DataTypes/Native.cpp:245: DB::getColumnNativeValue(llvm::IRBuilderBase&, std::shared_ptr<DB::IDataType const> const&, DB::IColumn const&, unsigned long) @ 0x00000000297f71e4
src/Interpreters/JIT/CompileDAG.cpp:41: DB::CompileDAG::compile(llvm::IRBuilderBase&, std::vector<DB::ValueWithType, std::allocator<DB::ValueWithType>> const&) const @ 0x000000003125c308
src/Interpreters/ExpressionJIT.cpp:160: DB::LLVMFunction::compile(llvm::IRBuilderBase&, std::vector<DB::ValueWithType, std::allocator<DB::ValueWithType>> const&) const @ 0x000000002ba39f3c
src/Interpreters/JIT/compileFunction.cpp:140: DB::compileFunction(llvm::Module&, DB::IFunctionBase const&)
src/Interpreters/JIT/compileFunction.cpp:175: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&>::type std::__invoke[abi:ne210105]<DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&>(DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&>(DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: void std::__invoke_r[abi:ne210105]<void, DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&>(DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&)::$_0&, llvm::Module&)
./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000003126e708
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Interpreters/JIT/CHJIT.cpp:415: DB::CHJIT::compileModule(std::function<void (llvm::Module&)>) @ 0x000000003124a214
src/Interpreters/JIT/compileFunction.cpp:173: DB::compileFunction(DB::CHJIT&, DB::IFunctionBase const&) @ 0x000000003126b30c
src/Interpreters/ExpressionJIT.cpp:298: operator()
inlined from ./src/Common/CacheBase.h:173: std::pair<std::shared_ptr<DB::CompiledExpressionCacheEntry>, bool> DB::CacheBase<wide::integer<128ul, unsigned int>, DB::CompiledExpressionCacheEntry, UInt128Hash, DB::CompiledFunctionWeightFunction>::getOrSet<DB::compile(DB::CompileDAG const&, unsigned long)::$_0>(wide::integer<128ul, unsigned int> const&, DB::compile(DB::CompileDAG const&, unsigned long)::$_0&&)
src/Interpreters/ExpressionJIT.cpp:295: DB::compile(DB::CompileDAG const&, unsigned long)
src/Interpreters/ExpressionJIT.cpp:612: DB::ActionsDAG::compileFunctions(unsigned long, std::unordered_set<DB::ActionsDAG::Node const*, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<DB::ActionsDAG::Node const*>> const&) @ 0x000000002ba2e844
src/Interpreters/ActionsDAG.cpp:1538: DB::ActionsDAG::compileExpressions(unsigned long, std::unordered_set<DB::ActionsDAG::Node const*, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<DB::ActionsDAG::Node const*>> const&) @ 0x000000002a186d14
src/Interpreters/ExpressionActions.cpp:64: DB::ExpressionActions::ExpressionActions(DB::ActionsDAG, DB::ExpressionActionsSettings const&, bool) @ 0x000000002b9a924c
./contrib/llvm-project/libcxx/include/__memory/construct_at.h:38: DB::ExpressionActions* std::construct_at[abi:ne210105]<DB::ExpressionActions, DB::ActionsDAG, DB::ExpressionActionsSettings const&, DB::ExpressionActions*>(DB::ExpressionActions*, DB::ActionsDAG&&, DB::ExpressionActionsSettings const&) @ 0x000000002a20b940
inlined from ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:46: DB::ExpressionActions* std::__construct_at[abi:ne210105]<DB::ExpressionActions, DB::ActionsDAG, DB::ExpressionActionsSettings const&, DB::ExpressionActions*>(DB::ExpressionActions*, DB::ActionsDAG&&, DB::ExpressionActionsSettings const&)
inlined from ./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:302: void std::allocator_traits<std::allocator<DB::ExpressionActions>>::construct[abi:ne210105]<DB::ExpressionActions, DB::ActionsDAG, DB::ExpressionActionsSettings const&, 0>(std::allocator<DB::ExpressionActions>&, DB::ExpressionActions*, DB::ActionsDAG&&, DB::ExpressionActionsSettings const&)
inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:162: __shared_ptr_emplace<DB::ActionsDAG, const DB::ExpressionActionsSettings &, std::allocator<DB::ExpressionActions>, 0>
inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:736: std::shared_ptr<DB::ExpressionActions> std::allocate_shared[abi:ne210105]<DB::ExpressionActions, std::allocator<DB::ExpressionActions>, DB::ActionsDAG, DB::ExpressionActionsSettings const&, 0>(std::allocator<DB::ExpressionActions> const&, DB::ActionsDAG&&, DB::ExpressionActionsSettings const&)
inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:744: std::shared_ptr<DB::ExpressionActions> std::make_shared[abi:ne210105]<DB::ExpressionActions, DB::ActionsDAG, DB::ExpressionActionsSettings const&, 0>(DB::ActionsDAG&&, DB::ExpressionActionsSettings const&)
src/Processors/QueryPlan/ExpressionStep.cpp:77: DB::ExpressionStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x00000000347d38bc
src/Processors/QueryPlan/ITransformingStep.cpp:21: DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000003481fd24
src/Processors/QueryPlan/QueryPlan.cpp:209: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x00000000348a5cc4
src/Interpreters/MutationsInterpreter.cpp:1596: DB::MutationsInterpreter::addStreamsForLaterStages(std::vector<DB::MutationsInterpreter::Stage, std::allocator<DB::MutationsInterpreter::Stage>> const&, DB::QueryPlan&) const @ 0x000000002bd62044
src/Interpreters/MutationsInterpreter.cpp:1641: DB::MutationsInterpreter::validate() @ 0x000000002bd67a78
src/Interpreters/InterpreterAlterQuery.cpp:294: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x000000002bb66a68
src/Interpreters/InterpreterAlterQuery.cpp:85: DB::InterpreterAlterQuery::execute() @ 0x000000002bb621d8
src/Interpreters/executeQuery.cpp:1738: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000002c2b3cec
src/Interpreters/executeQuery.cpp:2122: DB::executeQuery(std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>, DB::WriteBuffer&, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>, std::function<void ()>, std::function<void ()>) @ 0x000000002c2bd1dc
src/Interpreters/executeQuery.cpp:1987: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>, std::function<void ()>, std::function<void ()>) @ 0x000000002c2bc268
src/Interpreters/DDLWorker.cpp:516: DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&, bool) @ 0x000000002b922304
src/Interpreters/DDLWorker.cpp:684: DB::DDLWorker::processTask(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&, bool) @ 0x000000002b91e658
src/Databases/DatabaseReplicatedWorker.cpp:466: DB::DatabaseReplicatedDDLWorker::tryEnqueueAndExecuteEntry(DB::DDLLogEntry&, std::shared_ptr<DB::Context const>, bool) @ 0x0000000029c36498
src/Databases/DatabaseReplicated.cpp:1314: DB::DatabaseReplicated::tryEnqueueReplicatedDDL(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::QueryFlags) @ 0x0000000029be2888
src/Interpreters/InterpreterAlterQuery.cpp:139: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x000000002bb64544
src/Interpreters/InterpreterAlterQuery.cpp:85: DB::InterpreterAlterQuery::execute() @ 0x000000002bb621d8
src/Interpreters/executeQuery.cpp:1738: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000002c2b3cec
src/Interpreters/executeQuery.cpp:1962: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000002c2ac0c8
src/Server/TCPHandler.cpp:774: DB::TCPHandler::runImpl() @ 0x0000000033baa138
src/Server/TCPHandler.cpp:2867: DB::TCPHandler::run() @ 0x0000000033be16a4
base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000003fd00f78
base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000003fd01ba8
base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000003fc15bf8
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix JIT for `Date32` and `Time64` types. Closes #93674.

### Version info
- Merged into: `26.1.1.644`

### CODE REVIEW

File: src/DataTypes/Native.cpp [hunk 1]
```diff
@@ -232,6 +232,7 @@ llvm::Constant * getColumnNativeValue(llvm::IRBuilderBase & builder, const DataT
     GET_NUMERIC_CONSTANT(Enum8, Int8)
     GET_NUMERIC_CONSTANT(Enum16, Int16)
     GET_NUMERIC_CONSTANT(Date, UInt16)
+    GET_NUMERIC_CONSTANT(Date32, Int32)
```
Comment (PedroTadim) [inline src/DataTypes/Native.cpp:236]: Time64 seems to be missing on the list. Should it be added?

**Review by PedroTadim — APPROVED** [review]

**Comment by PedroTadim** [comment]
`03792_jit_time64` test is still failing
