### PR TITLE
Try to fix some trash in Disks and part moves

### LINKED ISSUE #51087: Issues around `localBackup`, `copyThroughBuffers` and `AsyncThreadPoolExecutor`
1. `localBackup` does `copyDirectoryContent`/`copyThroughBuffers` instead of `copyFile`/`copyS3File` (s3-server-side-copy) when `copy_instead_of_hardlinks` was set
2. `IDisk::copyThroughBuffers`/`asyncCopy` do not attach tasks to the current thread group. As a result, profile events and memory consumption may be incorrect. Also, it's impossible to use the query profiler because threads of `AsyncThreadPoolExecutor` are not profiled
3. Huge tail latencies in `copyThroughBuffers`, especially when copying multiple files consequently

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Partially fixes https://github.com/ClickHouse/ClickHouse/issues/51087

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 76faacd23ca6137feb52741a7217432ab961aea3 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51135/76faacd23ca6137feb52741a7217432ab961aea3/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests (asan) [4/6] - `test_multiple_disks/test.py::test_start_stop_moves` is flaky ([CI DB](https://play.clickhouse.com/play?user=play#V0lUSAogICAgJ3Rlc3RfbXVsdGlwbGVfZGlza3MvdGVzdC5weTo6dGVzdF9zdGFydF9zdG9wX21vdmVzJyBBUyBuYW1lX3N1YnN0ciwKICAgIDkwIEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=)), https://github.com/ClickHouse/ClickHouse/issues/45404
Upgrade check (debug) - #51313

File: src/Common/Exception.cpp [hunk 1]
```diff
@@ -400,6 +400,18 @@ PreformattedMessage getCurrentExceptionMessageAndPattern(bool with_stacktrace, b
                 << " (version " << VERSION_STRING << VERSION_OFFICIAL << ")";
         }
         catch (...) {}
+
+// #ifdef ABORT_ON_LOGICAL_ERROR
+//         try
+//         {
+//             throw;
+//         }
+//         catch (const std::logic_error &)
```
Comment (tavplubix) [inline src/Common/Exception.cpp:409]: `std::logic_error` indicates a bug just like our `LOGICAL_ERROR`, but it is thrown in the CI sometimes, so it's commented out. I will try to enable it in another PR

**Review by alexey-milovidov — APPROVED** [review]
LGTM

File: programs/disks/CommandCopy.cpp [hunk 2]
```diff
@@ -59,7 +59,7 @@ class CommandCopy final : public ICommand
         String relative_path_from = validatePathAndGetAsRelative(path_from);
         String relative_path_to = validatePathAndGetAsRelative(path_to);
 
-        disk_from->copy(relative_path_from, disk_to, relative_path_to);
+        disk_from->copyDirectoryContent(relative_path_from, disk_to, relative_path_to);
```
Comment (azat) [inline programs/disks/CommandCopy.cpp:62]: This changes the behavior of the copy command.

Before it was `cp foo bar`
After it will do `cp foo bar/foo`

Was that the intention?

Comment (tavplubix) [reply programs/disks/CommandCopy.cpp:62]: No, it was not intended, I will fix it. However, it means that we don't have proper tests for `clickhouse-disk` utility, cc: @Varinara, @kssenii

Comment (azat) [reply programs/disks/CommandCopy.cpp:62]: Indeed. I've added one in https://github.com/ClickHouse/ClickHouse/pull/51448, that how I found it.

**Comment by alexey-milovidov** [comment]
We can remove the `clickhouse-disks` utility if it is unsupported by the author.

**Comment by azat** [comment]
>We can remove the clickhouse-disks utility if it is unsupported by the author.

It can be useful to access disks like clickhouse does (since S3/GCS has some implementation quirks). So I'm suggesting to keep it. After https://github.com/ClickHouse/ClickHouse/pull/51448 there will be a test, and write something generic is not a big deal.

@tavplubix you said that you going to fix this, can you add a test as well then?
