### PR TITLE
Fix error NO_SUCH_COLUMN_IN_TABLE in Merge engine over tables with aliases

### LINKED ISSUE #88665: `merge` function does not work correctly with tables with aliases
### Company or project name

_No response_

### Describe what's wrong

The `merge` functions does not merge tables with different schemas if they have aliases.

https://fiddle.clickhouse.com/982fbfff-f210-4428-a630-b220987105e0

Stack trace: https://pastila.nl/?00404c87/71652d17b5c488b91030a4d1301095e7#ofe/WXIJQM6TgcNGqfc4Cw==

### Does it reproduce on the most recent release?

Yes

### How to reproduce

https://fiddle.clickhouse.com/982fbfff-f210-4428-a630-b220987105e0

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix error `NO_SUCH_COLUMN_IN_TABLE` in Merge engine over tables with aliases. Closes https://github.com/ClickHouse/ClickHouse/issues/88665

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by Fgrtue** [comment]
Hi @Avogar, that a neat fix. I just wanted to suggest to add a test case that creates a table with `Merge` engine. Your fix currently works for both table function and table engine. Even though at the moment hey are basically identical, for the sake of completeness and in case paths diverge later, this might be useful.

**Review by Fgrtue — APPROVED** [review]

File: tests/queries/0_stateless/03777_merge_engine_with_aliases_bug.sql [hunk 1]
```diff
@@ -0,0 +1,29 @@
+DROP TABLE IF EXISTS test1;
+DROP TABLE IF EXISTS test2;
```
Comment (Fgrtue) [inline tests/queries/0_stateless/03777_merge_engine_with_aliases_bug.sql:4]: Also, should we remove the test from old analyzer? I saw the only reasonable failure related to the old analyzer test case. [Stateless tests (amd_binary, old analyzer, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92910&sha=3238593068d5e392fe899f741af6487e617c8834&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%20parallel%29)

Comment (Avogar) [reply tests/queries/0_stateless/03777_merge_engine_with_aliases_bug.sql:4]: Let me check if I can fix it for old analyzer quickly

Comment (Avogar) [reply tests/queries/0_stateless/03777_merge_engine_with_aliases_bug.sql:4]: Seems like it's not trivial, so let's disable this test without analyzer
