### PR TITLE
Keep track of the number of async tables loading jobs. If there are some running jobs, do not update `tail_ptr` in `TransactionLog::removeOldEntries`

### LINKED ISSUE #60406: DB::Exception: Trying to get CSN for too old TID when killing clickhouse server process while big atomic insert
I create database and table:
```sql
CREATE TABLE IF NOT EXISTS test_table_A (timestamp DateTime,host String,response_time Int32,Path String,Time DateTime,Value Float64,Timestamp Int64,sign Int8)
ENGINE = MergeTree
ORDER BY (host, timestamp)
```

I make a big insert into the table and kill clickhouse server process in parallel:
```sql
BEGIN TRANSACTION;INSERT INTO test_table_A (timestamp, host, response_time, sign) SELECT now() + number/10, toString(number), number, 1 FROM numbers(50000000000); COMMIT;
```
```
kill -SIGKILL {pid}
```
I get:
```
Error on processing query: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF) (version 23.3.19.32 (official build))
```

I restart server  and get:
```
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

In server error log I get
```
2024.02.26 12:01:18.988795 [ 1880 ] {} <Error> Application: Code: 49. DB::Exception: Trying to get CSN for too old TID (40, 35, 82e71eab-e7ff-4faa-8bb5-16b7bf3e4bfa), current tail_ptr is 41, probably it's a bug: Cannot attach table `test_database5c2304b9_d496_11ee_901a_cf40acb2a173`.`table_A5c2304b9_d496_11ee_901a_cf40acb2a173` from metadata file /var/lib/clickhouse/store/a6a/a6a01912-8d18-4880-9e7a-6803f2f31847/table_A5c2304b9_d496_11ee_901a_cf40acb2a173.sql from query ATTACH TABLE test_database5c2304b9_d496_11ee_901a_cf40acb2a173.table_A5c2304b9_d496_11ee_901a_cf40acb2a173 UUID '30b93009-9076-49d4-b71a-52eff8d377bb' (`timestamp` DateTime, `host` String, `response_time` Int32, `Path` String, `Time` DateTime, `Value` Float64, `Timestamp` Int64, `sign` Int8) ENGINE = MergeTree ORDER BY (host, timestamp) SETTINGS index_granularity = 8192. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xbb942a4 in /usr/bin/clickhouse
1. ? @ 0x1078c0c8 in /usr/bin/clickhouse
2. DB::TransactionLog::assertTIDIsNotOutdated(DB::TransactionID const&, std::atomic<unsigned long> const*) @ 0x10788c4c in /usr/bin/clickhouse
3. DB::MergeTreeData::loadDataPart(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, std::mutex&) @ 0x11002d7c in /usr/bin/clickhouse
4. ? @ 0x11075b80 in /usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xbc4dbd0 in /usr/bin/clickhouse
6. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xbc5051c in /usr/bin/clickhouse
7. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xbc49fa4 in /usr/bin/clickhouse
8. ? @ 0xbc4f448 in /usr/bin/clickhouse
9. start_thread @ 0x7624 in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so
10. ? @ 0xd149c in /usr/lib/aarch64-linux-gnu/libc-2.31.so
 (version 23.3.19.32 (official build))
2024.02.26 12:01:18.989006 [ 1880 ] {} <Error> Application: DB::Exception: Trying to get CSN for too old TID (40, 35, 82e71eab-e7ff-4faa-8bb5-16b7bf3e4bfa), current tail_ptr is 41, probably it's a bug: Cannot attach table `test_database5c2304b9_d496_11ee_901a_cf40acb2a173`.`table_A5c2304b9_d496_11ee_901a_cf40acb2a173` from metadata file /var/lib/clickhouse/store/a6a/a6a01912-8d18-4880-9e7a-6803f2f31847/table_A5c2304b9_d496_11ee_901a_cf40acb2a173.sql from query ATTACH TABLE test_database5c2304b9_d496_11ee_901a_cf40acb2a173.table_A5c2304b9_d496_11ee_901a_cf40acb2a173 UUID '30b93009-9076-49d4-b71a-52eff8d377bb' (`timestamp` DateTime, `host` String, `response_time` Int32, `Path` String, `Time` DateTime, `Value` Float64, `Timestamp` Int64, `sign` Int8) ENGINE = MergeTree ORDER BY (host, timestamp) SETTINGS index_granularity = 8192
```
Caught on versions 23.3. and 23.8 on arm machine.

### LINKED ISSUE #82718: Tasks in BackgroundSchedulePool cannot throw: Cannot parse input: expected 'version: 1' before: '\ncreation_csn: 43
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=ca2087f7d14d9e30de026b66c05101f64b8ebb0b&name_0=MasterCI&name_1=Stress%20test%20%28azure%2C%20tsan%29

It's different from https://github.com/ClickHouse/ClickHouse/issues/50666 and apparently a recent change

### How to reproduce

_No response_

### Error message and/or stacktrace

```
2025.06.27 12:51:24.960058 [ 27810 ] {} <Test> AzureObjectStorage: Removing single object: jceayannbflqrxznnuyiowzdjjoyxzfg
2025.06.27 12:51:24.961594 [ 6804 ] {BgSchPool::8cd421ed-06a6-47d9-b2a6-80c9ad520cca} <Error> void DB::BackgroundSchedulePoolTaskInfo::execute(BackgroundSchedulePool &): Code: 27. DB::Exception: Cannot parse input: expected 'version: 1' before: '\ncreation_csn: 43': While loading version metadata from table test_jo84u8mu.reader (b0f5ae6b-bf73-45d7-9393-2ac5c79d976f) part all_1_1_0. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000232e1620
1. ./ci/tmp/build/./src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000126f5d54
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000008c78500
3. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x0000000008c97960
4. ./ci/tmp/build/./src/IO/ReadHelpers.cpp:95: DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x00000000128182cc
5. ./ci/tmp/build/./src/IO/ReadHelpers.cpp:131: DB::assertString(char const*, DB::ReadBuffer&) @ 0x0000000012818768
6. ./ci/tmp/build/./src/Interpreters/TransactionVersionMetadata.cpp:343: DB::VersionMetadata::read(DB::ReadBuffer&) @ 0x000000001b13e152
7. ./ci/tmp/build/./src/Storages/MergeTree/IMergeTreeDataPart.cpp:1824: DB::IMergeTreeDataPart::loadVersionMetadata() const @ 0x000000001d6b511f
8. ./ci/tmp/build/./src/Storages/MergeTree/MergeTreeData.cpp:1726: DB::MergeTreeData::loadDataPart(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, std::mutex&) @ 0x000000001d7cf4b7
9. ./ci/tmp/build/./src/Storages/MergeTree/MergeTreeData.cpp:1851: DB::MergeTreeData::loadDataPartWithRetries(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, std::mutex&, unsigned long, unsigned long, unsigned long) @ 0x000000001d7d5716
10. ./ci/tmp/build/./src/Storages/MergeTree/MergeTreeData.cpp:2314: DB::MergeTreeData::refreshDataParts(unsigned long) @ 0x000000001d7e0b89
11. ./ci/tmp/build/./src/Storages/MergeTree/MergeTreeData.cpp:2253: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::MergeTreeData::loadDataParts(bool, std::optional<std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>>)::$_5, void ()>>(std::__function::__policy_storage const*) @ 0x000000001d88f833
12. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000018f9cc89
13. ./ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:356: DB::BackgroundSchedulePool::threadFunction() @ 0x0000000018fa1eaf
14. ./ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:219: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000018fa2b6e
15. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000128a0043
16. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000128a8d9c
17. __tsan_thread_start_func @ 0x0000000008beb428
18. ? @ 0x0000000000094ac3
19. ? @ 0x0000000000126850
 (version 25.7.1.1409 (official build))
2025.06.27 12:51:24.962230 [ 43811 ] {9381613b-760f-4937-a6be-f295c4024b9c} <Trace> WriteBufferFromAzureBlobStorage: Committed single block for blob `tqkmwsmvxwslwwjayrldpjowkbxervez`
2025.06.27 12:51:24.962316 [ 43811 ] {9381613b-760f-4937-a6be-f295c4024b9c} <Test> DiskObjectStorage(azure): Write file: store/b04/b048a11c-59f2-4203-a4fc-56adb2b56da2/tmp_insert_all_1_1_0/default_compression_codec.txt
2025.06.27 12:51:24.961830 [ 6804 ] {BgSchPool::8cd421ed-06a6-47d9-b2a6-80c9ad520cca} <Fatal> : Logical error: 'false && "Tasks in BackgroundSchedulePool cannot throw"'.
```

### PR DESCRIPTION
**Pull request by tuanpach**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Keep track of the number of async tables loading jobs. If there are some running jobs, do not update `tail_ptr` in `TransactionLog::removeOldEntries`

Because `loadTableFromMetadataAsync` is running asynchronously, it is possible that the outdated parts are loading while the `tail_ptr` is updated here. It might trigger assertion when the part `create_csn` is lower than `tail_ptr`. Refer: https://github.com/ClickHouse/ClickHouse/issues/60406

We keep track of `asyncTablesLoadingJobNumber`, and not update `tail_ptr` if there are running jobs.

Closes #60406
Closes #82718

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/TransactionLog.cpp [hunk 1]
```diff
@@ -638,4 +650,16 @@ void TransactionLog::sync() const
...
+{
+    async_tables_loading_job_number.fetch_add(1, std::memory_order_relaxed);
+}
+void TransactionLog::decreaseAsyncTablesLoadingJobNumber()
+{
+    async_tables_loading_job_number.fetch_sub(1, std::memory_order_relaxed);
+}
+Int64 TransactionLog::asyncTablesLoadingJobNumber()
+{
+    return async_tables_loading_job_number.load(std::memory_order_relaxed);
```
Comment (tavplubix) [inline src/Interpreters/TransactionLog.cpp]: why `memory_order_relaxed`?

**Review by tavplubix — APPROVED** [review]

File: src/Interpreters/TransactionLog.cpp (hunk 1 above)
Comment (tuanpach) [reply src/Interpreters/TransactionLog.cpp]: I removed `memory_order_relaxed`.
I thought it might help to optimize the implementation but it seems to have some problems.
In `DatabaseOrdinary::loadTableFromMetadataAsync`:

```
LoadTaskPtr DatabaseOrdinary::loadTableFromMetadataAsync(
    AsyncLoader & async_loader,
    LoadJobSet load_after,
    ContextMutablePtr local_context,
    const String & file_path,
    const QualifiedTableName & name,
    const ASTPtr & ast,
    LoadingStrictnessLevel mode)
{
    TransactionLog::increaseAsyncTablesLoadingJobNumber();
    std::scoped_lock lock(mutex);
    auto job = makeLoadJob(
        std::move(load_after),
        TablesLoaderBackgroundLoadPoolId,
        fmt::format("load table {}", name.getFullName()),
        [this, local_context, file_path, name, ast, mode](AsyncLoader &, const LoadJobPtr &)
        {
            SCOPE_EXIT(TransactionLog::decreaseAsyncTablesLoadingJobNumber(););
            loadTableFromMetadata(local_context, file_path, name, ast, mode);
        });
```

Even though `TransactionLog::increaseAsyncTablesLoadingJobNumber()` is called before `std::scoped_lock lock(mutex);`, it might be called after `makeLoadJob`.

**Comment by azat** [comment]
@tuanpach looks like this fixes only https://github.com/ClickHouse/ClickHouse/issues/60406 and not https://github.com/ClickHouse/ClickHouse/issues/82718
