### PR TITLE
Fix possible "No column to rollback" logical error during INSERT into Buffer

### LINKED ISSUE #42740: Logical error: No column to rollback
https://s3.amazonaws.com/clickhouse-test-reports/42234/615b73773ae321a0c024dd5bcc05fcf96d55a4f3/stress_test__ubsan_.html
```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:36.842657 [ 3138 ] {104629a3-6826-49e0-99e2-2df6e0168032} <Fatal> : Logical error: 'No column to rollback'.
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.769579 [ 323414 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.769613 [ 323414 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: 8A8428F6D936D94EC465034E3D3A6E7F0131A27B) (from thread 3138) (query_id: 104629a3-6826-49e0-99e2-2df6e0168032) (query: INSERT INTO t_buffer_map SELECT (range(10), range(10)), (range(10), range(10)) from numbers(100)) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.770089 [ 323414 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.770335 [ 323414 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f261da2c00b 0x7f261da0b859 0x1fa06da3 0x1fa0704f 0x2bf5e15d 0x2bf5ccdc 0x2cd0d8b1 0x2cbdef53 0x2cbdebd2 0x2cbddc08 0x2c809414 0x2c7f949b 0x2c7f8cd6 0x2c7f8a8a 0x2c7f7f14 0x1faec1d3 0x1faeffa4 0x7f261dbe3609 0x7f261db08133
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.770379 [ 323414 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7f261da2c00b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.770412 [ 323414 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f261da0b859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.788916 [ 323414 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:47: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1fa06da3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.806922 [ 323414 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1fa0704f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.880892 [ 323414 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../src/Storages/StorageBuffer.cpp:498: DB::appendBlock(DB::Block const&, DB::Block&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.880933 [ 323414 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Storages/StorageBuffer.cpp:628: DB::BufferSink::insertIntoBuffer(DB::Block const&, DB::StorageBuffer::Buffer&) @ 0x2bf5e15d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.951765 [ 323414 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/StorageBuffer.cpp:0: DB::BufferSink::consume(DB::Chunk) @ 0x2bf5ccdc in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.959571 [ 323414 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../src/Processors/Chunk.h:32: ~Chunk
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.959609 [ 323414 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Processors/Sinks/SinkToStorage.cpp:18: DB::SinkToStorage::onConsume(DB::Chunk) @ 0x2cd0d8b1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.974325 [ 323414 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../src/Processors/Chunk.h:32: ~Chunk
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.974360 [ 323414 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:151: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.974384 [ 323414 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::ExceptionKeepingTransform::work()::$_1&>(fp)()) std::__1::__invoke<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.974406 [ 323414 ] {} <Fatal> BaseDaemon: 10.4. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.974435 [ 323414 ] {} <Fatal> BaseDaemon: 10.5. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>::operator()()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.974452 [ 323414 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()> >(std::__1::__function::__policy_storage const*) @ 0x2cbdef53 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.988593 [ 323414 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x2cbdebd2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:09:59.998997 [ 323414 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:0: DB::ExceptionKeepingTransform::work() @ 0x2cbddc08 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.005665 [ 323414 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.005705 [ 323414 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2c809414 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.022113 [ 323414 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2c7f949b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.037056 [ 323414 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2c7f8cd6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.060324 [ 323414 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:284: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::operator->() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.060379 [ 323414 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:92: DB::PipelineExecutor::execute(unsigned long) @ 0x2c7f8a8a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068527 [ 323414 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:0: DB::threadFunction(DB::CompletedPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068583 [ 323414 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:79: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068611 [ 323414 ] {} <Fatal> BaseDaemon: 17.3. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3648: decltype(static_cast<DB::CompletedPipelineExecutor::execute()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::CompletedPipelineExecutor::execute()::$_0&>(DB::CompletedPipelineExecutor::execute()::$_0&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068637 [ 323414 ] {} <Fatal> BaseDaemon: 17.4. inlined from ./build_docker/../contrib/libcxx/include/tuple:1595: decltype(auto) std::__1::__apply_tuple_impl<DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&>(DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068672 [ 323414 ] {} <Fatal> BaseDaemon: 17.5. inlined from ./build_docker/../contrib/libcxx/include/tuple:1604: decltype(auto) std::__1::apply<DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&>(DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068693 [ 323414 ] {} <Fatal> BaseDaemon: 17.6. inlined from ./build_docker/../src/Common/ThreadPool.h:193: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068718 [ 323414 ] {} <Fatal> BaseDaemon: 17.7. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::CompletedPipelineExecutor::execute()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&>(DB::CompletedPipelineExecutor::execute()::$_0&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068754 [ 323414 ] {} <Fatal> BaseDaemon: 17.8. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068781 [ 323414 ] {} <Fatal> BaseDaemon: 17.9. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>::operator()()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.068799 [ 323414 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x2c7f7f14 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.080979 [ 323414 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.081021 [ 323414 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.081040 [ 323414 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x1faec1d3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.095667 [ 323414 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x1faeffa4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.095712 [ 323414 ] {} <Fatal> BaseDaemon: 20. ? @ 0x7f261dbe3609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.095730 [ 323414 ] {} <Fatal> BaseDaemon: 21. __clone @ 0x7f261db08133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:10:00.410487 [ 323414 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: CEF493DADCB5D4DAD4F42E4D27175BE8)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.10.22 07:13:51.717883 [ 1518 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible (very unlikely) "No column to rollback" logical error during INSERT into Buffer

In case of concurrent INSERT and SELECT, and memory pressure it is
possible to get this error, if you are very lucky.

*More details you will find in the comments in the code and tests*

Fixes: #42740 (cc @tavplubix @alexey-milovidov )

### CODE REVIEW

File: tests/queries/0_stateless/02124_buffer_insert_select_race.sh [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS t_buffer_string"
+$CLICKHOUSE_CLIENT -q "CREATE TABLE t_buffer_string(key String) ENGINE = Buffer('', '', 1, 1, 1, 1000000000000, 1000000000000, 1000000000000, 1000000000000)"
+
+# --continue_on_errors -- to ignore possible MEMORY_LIMIT_EXCEEDED errors
+# --concurrency -- we need have SELECT and INSERT in parallel to have refcount
+#                  of the column in the Buffer block > 1, that way we will do
+#                  full clone and moving a column may throw.
+#
+# It reproduces the problem 100% with MemoryTrackerFaultInjectorInThread in the appendBlock()
```
Comment (azat) [inline tests/queries/0_stateless/02124_buffer_insert_select_race.sh:21]: Submitted it separately - #43337

**Review by davenger — APPROVED** [review]

**Comment by davenger** [comment]
AST Fuzzer (asan) failure: https://github.com/ClickHouse/ClickHouse/issues/43202
