### PR TITLE
Fix some races in MergeTree

### LINKED ISSUE #42654: Logical error: 'Part 5_1_1_0 (state PreActive) not found in data_parts'.
https://s3.amazonaws.com/clickhouse-test-reports/0/f33ae3cb87bc67f24a0506ca648eecbee875522c/stress_test__msan_.html

```
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:03.465927 [ 2485 ] {e1176296-8f59-45ea-bd4f-f337b1cb39c7} <Fatal> : Logical error: 'Part 5_1_1_0 (state PreActive) not found in data_parts'.
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:50.533625 [ 27372 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.148790 [ 27372 ] {} <Fatal> BaseDaemon: (version 22.10.1.1 (official build), build id: D8453E648C6C194D64704F37278DE189DF1C7951) (from thread 2485) (query_id: e1176296-8f59-45ea-bd4f-f337b1cb39c7) (query: INSERT INTO concurrent_optimize_table SELECT rand(1), rand(2), 1 / rand(3), toString(rand(4)), [rand(5), rand(6)], rand(7) % 2 ? NULL : generateUUIDv4(), (rand(8), rand(9)) FROM numbers(10000)) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.149909 [ 27372 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.151424 [ 27372 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fbf3898d00b 0x7fbf3896c859 0x25cac235 0x25cac7d3 0x444a7b86 0x44522154 0x44d29ad5 0x44d1b314 0x44d17b29 0x45fafd46 0x45cf5242 0x45cf4ad9 0x45cf3d5e 0x454aaace 0x45470e3d 0x4546ef28 0x4546e8ae 0x4546be67 0x25f7a631 0x25f87503 0x7fbf38b44609 0x7fbf38a69133
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.153671 [ 27372 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7fbf3898d00b in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.154778 [ 27372 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7fbf3896c859 in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.568315 [ 27372 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x25cac235 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.824190 [ 27372 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../src/Common/Exception.cpp:0: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:51.824856 [ 27372 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x25cac7d3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:55.849163 [ 27372 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:0: DB::MergeTreeData::removePartsFromWorkingSet(DB::MergeTreeTransaction*, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&, bool, std::__1::unique_lock<std::__1::mutex>*) @ 0x444a7b86 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:58.405038 [ 27372 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../contrib/libcxx/include/vector:399: ~vector
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:58.405184 [ 27372 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:5184: DB::MergeTreeData::Transaction::rollback() @ 0x44522154 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:58.870965 [ 27372 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:0: DB::ReplicatedMergeTreeSink::commitPart(std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, unsigned long) @ 0x44d29ad5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.187515 [ 27372 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:0: DB::ReplicatedMergeTreeSink::finishDelayedChunk(std::__1::shared_ptr<zkutil::ZooKeeper>&) @ 0x44d1b314 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.481309 [ 27372 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:0: DB::ReplicatedMergeTreeSink::consume(DB::Chunk) @ 0x44d17b29 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.574730 [ 27372 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Processors/Sinks/SinkToStorage.cpp:18: DB::SinkToStorage::onConsume(DB::Chunk) @ 0x45fafd46 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.792617 [ 27372 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:151: operator()
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.793264 [ 27372 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::ExceptionKeepingTransform::work()::$_1&>(fp)()) std::__1::__invoke<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.793662 [ 27372 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.794001 [ 27372 ] {} <Fatal> BaseDaemon: 14.4. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>::operator()()
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.794084 [ 27372 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()> >(std::__1::__function::__policy_storage const*) @ 0x45cf5242 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:48:59.935564 [ 27372 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x45cf4ad9 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.030523 [ 27372 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:813: ~__policy_func
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.030892 [ 27372 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:1171: ~function
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.030975 [ 27372 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:151: DB::ExceptionKeepingTransform::work() @ 0x45cf3d5e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.108746 [ 27372 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.108887 [ 27372 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x454aaace in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.358561 [ 27372 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x45470e3d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.496064 [ 27372 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:366: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x4546ef28 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.658897 [ 27372 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::execute(unsigned long) @ 0x4546e8ae in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.733911 [ 27372 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./build_docker/../contrib/libcxx/include/atomic:939: std::__1::__atomic_base<bool, false>::store(bool, std::__1::memory_order)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.734300 [ 27372 ] {} <Fatal> BaseDaemon: 21.2. inlined from ./build_docker/../contrib/libcxx/include/atomic:1777: std::__1::atomic<bool>::operator=(bool)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.734629 [ 27372 ] {} <Fatal> BaseDaemon: 21.3. inlined from ./build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:51: DB::threadFunction(DB::CompletedPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.734720 [ 27372 ] {} <Fatal> BaseDaemon: 21.4. inlined from ./build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:79: operator()
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.734839 [ 27372 ] {} <Fatal> BaseDaemon: 21.5. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3648: decltype(static_cast<DB::CompletedPipelineExecutor::execute()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::CompletedPipelineExecutor::execute()::$_0&>(DB::CompletedPipelineExecutor::execute()::$_0&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.734983 [ 27372 ] {} <Fatal> BaseDaemon: 21.6. inlined from ./build_docker/../contrib/libcxx/include/tuple:1595: decltype(auto) std::__1::__apply_tuple_impl<DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&>(DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.735101 [ 27372 ] {} <Fatal> BaseDaemon: 21.7. inlined from ./build_docker/../contrib/libcxx/include/tuple:1604: decltype(auto) std::__1::apply<DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&>(DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.735189 [ 27372 ] {} <Fatal> BaseDaemon: 21.8. inlined from ./build_docker/../src/Common/ThreadPool.h:193: operator()
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.735325 [ 27372 ] {} <Fatal> BaseDaemon: 21.9. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::CompletedPipelineExecutor::execute()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&>(DB::CompletedPipelineExecutor::execute()::$_0&&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.736082 [ 27372 ] {} <Fatal> BaseDaemon: 21.10. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.740387 [ 27372 ] {} <Fatal> BaseDaemon: 21.11. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>::operator()()
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.740488 [ 27372 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x4546be67 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:00.895275 [ 27372 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../contrib/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x25f7a631 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:01.074478 [ 27372 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x25f87503 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:01.077577 [ 27372 ] {} <Fatal> BaseDaemon: 24. ? @ 0x7fbf38b44609 in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:01.077697 [ 27372 ] {} <Fatal> BaseDaemon: 25. clone @ 0x7fbf38a69133 in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:49:04.118125 [ 27372 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: F926556C620E1EC40AE6596B18448FCB)
/var/log/clickhouse-server/clickhouse-server.stress.log:2022.10.21 07:50:26.030060 [ 1574 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes  https://github.com/ClickHouse/ClickHouse/issues/42654
Also fixes https://pastila.nl/?00454a25/6fdcb8bceb9bf9587c7e6255b9319d37

### CODE REVIEW

**Comment by tavplubix** [comment]
AST fuzzer (asan) - https://github.com/ClickHouse/ClickHouse/issues/42819
Stress test (debug) - OOM in dmesg
Stress test (msan) - slow `clearOldPartsFromFilesystem` on shutdown
Stress test (tsan) - https://github.com/ClickHouse/ClickHouse/issues/42638
Stress test (ubsan) - failed to get process list for hung check due to MEMORY_LIMIT_EXCEEDED

File: src/Storages/MergeTree/MergeTreeData.h [hunk 1]
```diff
@@ -584,10 +584,33 @@ class MergeTreeData : public IStorage, public WithMutableContext
...
     void removePartsInRangeFromWorkingSet(MergeTreeTransaction * txn, const MergeTreePartInfo & drop_range, DataPartsLock & lock);
 
+    /// This wrapper is required to restrict access to parts in Deleting state
+    class PartToRemoveFromZooKeeper
+    {
+        DataPartPtr part;
+        bool was_active;
+
+    public:
+        PartToRemoveFromZooKeeper(DataPartPtr && part_, bool was_active_ = true)
```
Comment (serxa) [inline src/Storages/MergeTree/MergeTreeData.h:594]:
```suggestion
        explicit PartToRemoveFromZooKeeper(DataPartPtr && part_, bool was_active_ = true)
```

**Review by serxa — APPROVED** [review]
