### PR TITLE
Fix wrong result of non-correlated EXISTS.

### LINKED ISSUE #86415: 'SELECT EXISTS' query incorrectly produces 0 on ClickHouse 25.8.1
### Company or project name

TensorZero

### Describe the unexpected behaviour

On ClickHouse 25.7, the following query produces `1`, as expected:
```
SELECT EXISTS(SELECT 1 from system.columns where database != '');
```
This is consistent with the behavior of `SELECT 1 from system.columns where database != '';`, which produces multiple rows of `1`s

However, on ClickHouse 25.8, `SELECT EXISTS(SELECT 1 from system.columns where database != '');` produces 0, even though the inner `SELECT 1 from system.columns where database != ''` query still produces multiple rows of 1s.

### Which ClickHouse versions are affected?

I've reproduced this locally with the `25.8.1-alpine`. I cannot reproduce the issue on ClickHouse Cloud.

### How to reproduce

Run `SELECT EXISTS(SELECT 1 from system.columns where database != '');` on a default ClickHouse Docker setup, and observe that the output is `0`. It's not necessary to create any tables.

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix possible wrong result of non-correlated `EXISTS`. It was broken with `execute_exists_as_scalar_subquery=1` which was introduced in https://github.com/ClickHouse/ClickHouse/pull/85481 and affects `25.8`.
Fixes https://github.com/ClickHouse/ClickHouse/issues/86415

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Analyzer/Resolve/evaluateScalarSubqueryIfNeeded.cpp [hunk 1]
```diff
@@ -235,12 +236,12 @@ void QueryAnalyzer::evaluateScalarSubqueryIfNeeded(QueryTreeNodePtr & node, Iden
                 io.pipeline.setConcurrencyControl(context->getSettingsRef()[Setting::use_concurrency_control]);
 
                 executor.emplace(io.pipeline);
-                while (block.rows() == 0 && executor->pull(block))
+                while (chunk.getNumRows() == 0 && executor->pull(chunk))
```
Comment (KochetovNicolai) [inline src/Analyzer/Resolve/evaluateScalarSubqueryIfNeeded.cpp:239]: The fix is to replace Block with Chunk because an optimized for EXISTS plan may return a chunk with no columns but non-zero rows.

**Review by novikd — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
`test_disks_app_interactive` is flaky
