### PR TITLE
Fix fault injection in copier and test_cluster_copier flakiness

### LINKED ISSUE #30399: Flaky test: test_cluster_copier
https://clickhouse-test-reports.s3.yandex.net/0/d004fd96edbc3eb63561a12b846972a3b4961372/integration_tests_(asan).html
```
____________________________ test_copy_simple[True] ____________________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3

started_cluster = <helpers.cluster.ClickHouseCluster object at 0x7f9093fcb460>
use_sample_offset = True

    @pytest.mark.parametrize(('use_sample_offset'), [False, True])
    def test_copy_simple(started_cluster, use_sample_offset):
        if use_sample_offset:
>           execute_task(started_cluster, Task1(started_cluster), ['--experimental-use-sample-offset', '1'])

test_cluster_copier/test.py:387: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_cluster_copier/test.py:377: in execute_task
    task.check()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_cluster_copier.test.Task1 object at 0x7f9093dd2f40>

    def check(self):
        assert self.cluster.instances['s0_0_0'].query("SELECT count() FROM hits_all").strip() == "1002"
>       assert self.cluster.instances['s1_0_0'].query("SELECT count() FROM hits_all").strip() == "1002"
E       AssertionError: assert '927' == '1002'
E         - 1002
E         + 927

test_cluster_copier/test.py:109: AssertionError
```

[Query CI DB](https://play-ci.clickhouse.com/play?user=play#c2VsZWN0IGNoZWNrX25hbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIHRlc3Rfc3RhdHVzLCByZXBvcnRfdXJsLCBjb21taXRfc2hhLCB0ZXN0X25hbWUKZnJvbSBgZ2gtZGF0YWAuY2hlY2tzIAp3aGVyZSAKdGVzdF9zdGF0dXMgbm90IGluIFsnT0snLCAnU1VDQ0VTUycsICdTS0lQUEVEJywgJ1hGQUlMJywgJ1hFUlJPUiddIGFuZCAKLS0gY2hlY2tfbmFtZSBsaWtlICdJbnRlZ3JhdGlvbiUnIGFuZApwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBhbmQKdGVzdF9uYW1lIExJS0UgJyV0ZXN0X2NsdXN0ZXJfY29waWVyJScgYW5kCmNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBpbnRlcnZhbCAzMCBkYXkgCm9yZGVyIGJ5IGNoZWNrX3N0YXJ0X3RpbWUgZGVzYyAKbGltaXQgMTAKZm9ybWF0IE1hcmtkb3duCg==
)
| check_name | pull_request_number | check_start_time | test_status | report_url | commit_sha | test_name |
|:-|-:|-:|:-|:-|:-|:-|
| Integration tests (asan) | 0 | 2021-10-18 22:01:32 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/d004fd96edbc3eb63561a12b846972a3b4961372/integration_tests_(asan).html | d004fd96edbc3eb63561a12b846972a3b4961372 | test_cluster_copier/test.py::test_copy_simple[True] |
| Integration tests (release) | 0 | 2021-10-18 20:54:39 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/75c16b8f8924f3e397c5b2e8a4c8da8ddfd7c79e/integration_tests_(release).html | 75c16b8f8924f3e397c5b2e8a4c8da8ddfd7c79e | test_cluster_copier/test.py::test_copy_with_recovering[True] |
| Integration tests (asan) | 0 | 2021-10-18 13:36:04 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/158b4c26b72c5494a831403e8f0392e30fbab386/integration_tests_(asan).html | 158b4c26b72c5494a831403e8f0392e30fbab386 | test_cluster_copier/test.py::test_copy_with_recovering_after_move_faults[False] |
| Integration tests (release) | 0 | 2021-10-18 08:37:02 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/158b4c26b72c5494a831403e8f0392e30fbab386/integration_tests_(release).html | 158b4c26b72c5494a831403e8f0392e30fbab386 | test_cluster_copier/test.py::test_copy_month_to_week_partition |
| Integration tests (release) | 0 | 2021-10-18 08:37:02 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/158b4c26b72c5494a831403e8f0392e30fbab386/integration_tests_(release).html | 158b4c26b72c5494a831403e8f0392e30fbab386 | test_cluster_copier/test.py::test_copy_with_recovering[False] |
| Integration tests (asan) | 0 | 2021-10-18 01:08:29 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/f032fb71f0903e181e92479803a88fb482adbec1/integration_tests_(asan).html | f032fb71f0903e181e92479803a88fb482adbec1 | test_cluster_copier/test.py::test_copy_month_to_week_partition_with_recovering |
| Integration tests (release) | 0 | 2021-10-17 19:02:52 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/f4bfed9d3a7d87e596c2a264617f890a034bfbb0/integration_tests_(release).html | f4bfed9d3a7d87e596c2a264617f890a034bfbb0 | test_cluster_copier/test.py::test_copy_with_recovering[True] |
| Integration tests (asan) | 0 | 2021-10-17 11:13:42 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/e1969e26933e81fbd288bc411a893ea667e5b071/integration_tests_(asan).html | e1969e26933e81fbd288bc411a893ea667e5b071 | test_cluster_copier/test.py::test_copy_month_to_week_partition_with_recovering_after_move_faults |
| Integration tests (asan) | 0 | 2021-10-17 04:49:08 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/0285a15aeca720c4ecccb16755b9d0bd81de0d45/integration_tests_(asan).html | 0285a15aeca720c4ecccb16755b9d0bd81de0d45 | test_cluster_copier/test.py::test_copy_month_to_week_partition_with_recovering_after_move_faults |
| Integration tests (asan) | 0 | 2021-10-17 00:00:14 | FLAKY | https://clickhouse-test-reports.s3.yandex.net/0/0dd8c70d28ad44d0db386dd225732a5d201cfee5/integration_tests_(asan).html | 0dd8c70d28ad44d0db386dd225732a5d201cfee5 | test_cluster_copier/test.py::test_copy_with_recovering[False] |

### PR DESCRIPTION
**Pull request by azat**
_Let's fix one more long standing flakiness, in the road to PR auto-merge._

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix fault injection in copier (`--copy-fault-probability`) and `test_cluster_copier` test flakiness

There are very frequent flakiness of `test_cluster_copier` test, here is an example of copier failures on CI [1]:

    AssertionError: Instance: s0_1_0 (172.16.29.9). Info: {'ID': '5d68dcb46fdb4b0c54b7c7ba1ddde83b8f34d483bbb32abcb0c52b966444ce82', 'Running': False, 'ExitCode': 85, 'ProcessConfig': {'tty': False, 'entrypoint': '/usr/bin/clickhouse', 'arguments': ['copier', '--config', '/etc/clickhouse-server/config-copier.xml', '--task-path', '/clickhouse-copier/task_simple_4DFWYTDD49', '--task-file', '/task0_description.xml', '--task-upload-force', 'true', '--base-dir', '/var/log/clickhouse-server/copier', '--copy-fault-probability', '0.2', '--experimental-use-sample-offset', '1'], 'privileged': False, 'user': '0'}, 'OpenStdin': False, 'OpenStderr': True, 'OpenStdout': True, 'CanRemove': False, 'ContainerID': 'f356df6694b3cc09ee9830c623681626f8e8d999677c188b9fe911aa702784ca', 'DetachKeys': '', 'Pid': 84332}
    assert 85 == 0

But let's look what the error it is, apparently it is UNFINISHED:

    SELECT
        name,
        code
    FROM system.errors
    WHERE ((code % 256) = 85) AND (NOT remote)
    SETTINGS system_events_show_zero_values = 1

    ┌─name─────────────────────────────┬─code─┐
    │ FORMAT_IS_NOT_SUITABLE_FOR_INPUT │   85 │
    │ UNFINISHED                       │  341 │
    │ NO_SUCH_ERROR_CODE               │  597 │
    └──────────────────────────────────┴──────┘

Let's verify:

    $ grep -r UNFINISHED ./test_cluster_copier/_instances_0/s0_1_0/logs/copier/clickhouse-copier_*
    ./test_cluster_copier/_instances_0/s0_1_0/logs/copier/clickhouse-copier_20230206220846_368/log.log:2023.02.06 22:09:19.015251 [ 368 ] {} <Error> : virtual int DB::ClusterCopierApp::main(const std::vector<std::string> &): Code: 341. DB::Exception: Too many tries to process table cluster1.default.hits. Abort remaining execution. (UNFINISHED), Stack trace (when copying this message, always include the lines below):

And apparently that it is due to query error with fault injection:

    2023.02.06 22:09:15.654724 [ 368 ] {} <Error> Application: An error occurred while processing partition 0: Code: 62. DB::Exception: Syntax error (Query): failed at position 168 ('Native'): Native. Expected one of: token, Dot, OR, AND, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, IS NULL, IS NOT NULL, alias, AS, Comma, OFFSET, WITH TIES, BY, LIMIT, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

Example:

    select x from x limit  1FORMAT Native

    Syntax error: failed at position 32 ('Native'):

So fixing this should fix test_cluster_copier flakiness.

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/46045/bd4170e03c6af583a51d12d2c39fa775dcb9997b/integration_tests__release__[4/4].html

Fixes: #30399 (cc @nikitamikhaylov @alexey-milovidov @qoega )

### CODE REVIEW

**Comment by azat** [comment]
>[Integration tests (release) [2/4] — fail: 1, passed: 547, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/46120/ff324fe81af22d04fd4bbec7958449197c1f755d/integration_tests__release__[2/4].html)

- `test_storage_rabbitmq/test.py::test_rabbitmq_overloaded_insert` - https://github.com/ClickHouse/ClickHouse/issues/45160#issuecomment-1418978784

File: programs/copier/ClusterCopier.cpp [hunk 1]
```diff
@@ -1306,7 +1306,7 @@ TaskStatus ClusterCopier::processPartitionPieceTaskImpl(
         if (!limit.empty())
             query += " LIMIT " + limit;
 
-        query += "FORMAT Native";
+        query += " FORMAT Native";
```
Comment (alexey-milovidov) [inline programs/copier/ClusterCopier.cpp:1309]: Hilarious!

**Review by alexey-milovidov — APPROVED** [review]
