### PR TITLE
Optimize memory consumption during backup to S3

### LINKED ISSUE #43083: Backup to S3 endpoint out of memory
**Describe what's wrong**

When we backup a lot of data to a minio S3 storage, ClickHouse takes all the available memory and crashes.

**Does it reproduce on recent release?**

Tested on ClickHouse 22.10.2.11 and on this build : https://s3.amazonaws.com/clickhouse-builds/0/12c6a1116c16ddefce8632138b7871753e1394f3/clickhouse_build_check/report.html

**How to reproduce**

* ClickHouse server version : 22.10.2.11
* Docker-compose with : 
  * **clickhouse-server** with 10GB of memory (to reproduce faster)
  * **minio**
  * **docker-tc** : to limit minio bandwidth

`docker-compose.yml` :

```yml
services:
  tc:
    image: lukaszlach/docker-tc
    container_name: docker-tc
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker-tc:/var/docker-tc
    deploy:
      mode: global
      restart_policy:
        condition: any
    environment:
      HTTP_BIND: "127.0.0.1"
      HTTP_PORT: "4080"
    network_mode: host

  clickhouse:
    depends_on:
      - tc
    image: clickhouse/clickhouse-server:latest-alpine
    networks:
      - limited-network
    deploy:
      resources:
        limits:
          memory: 10G

  minio-backup:
    depends_on:
      - tc
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secretkey
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.limit=8mbps"
    command: server /var/lib/minio
    networks:
      - limited-network

  createbuckets:
    image: registry.dametis.dev/proxy/minio/mc
    depends_on:
      - minio-backup
      - tc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio-backup:9000 access secretkey;
      /usr/bin/mc rm -r --force myminio/backups;
      /usr/bin/mc mb myminio/backups;
      /usr/bin/mc policy download myminio/backups;
      exit 0;
      "
    networks:
      - limited-network

networks:
  default:
    external:
      name: host
  limited-network:
```
Launch a clickhouse-client :
`docker run -it --rm --name client --network docker-tc_limited-network clickhouse/clickhouse-server:latest-alpine clickhouse-client --host clickhouse
`
Create a test database with many rows : 
```sql
CREATE DATABASE IF NOT EXISTS test;

CREATE TABLE IF NOT EXISTS test.test
(
  `a` Array(Int8),
  `d` Decimal32(4),
  `c` Tuple(DateTime64(3), UUID)
)
ENGINE = MergeTree
ORDER BY a;

INSERT INTO test.test SELECT * FROM generateRandom('a Array(Int8), d Decimal32(4), c Tuple(DateTime64(3), UUID)', 1, 10, 2) LIMIT 500000000;
```

Backup database to minio S3 :
```sql
BACKUP DATABASE test TO S3('http://minio-backup:9000/backups/backup', 'access', 'secretkey')
```

**Expected behavior**

Backup query should succeed and this should not take all the memory to send data to minio.

**Error message and/or stacktrace**

ClickHouse crashes (sometimes) because memory is full :
```
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from clickhouse:9000. (ATTEMPT_TO_READ_AFTER_EOF)
```

Thank you in advance ! Don't hesitate to ask me with you need more information.

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize memory consumption during backup to S3: files to S3 now will be copied directly without using `WriteBufferFromS3` (which could use a lot of memory).

This PR fixes https://github.com/ClickHouse/ClickHouse/issues/43083

### CODE REVIEW

File: src/IO/S3/copyDataToS3.cpp [hunk 1]
```diff
@@ -0,0 +1,682 @@
...
+        String processUploadPartRequest(Aws::AmazonWebServiceRequest & request) override
+        {
+            auto & req = typeid_cast<Aws::S3::Model::UploadPartRequest &>(request);
+
+            ProfileEvents::increment(ProfileEvents::S3UploadPart);
+
+            auto outcome = client_ptr->UploadPart(req);
+            if (!outcome.IsSuccess())
+            {
+                abortMultipartUpload();
```
Comment (CheSema) [inline src/IO/S3/copyDataToS3.cpp:477]: > However, if any part uploads are currently in progress, those part uploads might or might not succeed. As a result, it might be necessary to abort a given multipart upload multiple times in order to completely free all storage consumed by all parts.

As I see, this call is concurrent with other UploadPart calls. In that case it might be useless.

File: src/IO/StdStreamBufFromReadBuffer.cpp [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+
+std::streampos StdStreamBufFromReadBuffer::seekoff(std::streamoff off, std::ios_base::seekdir dir, std::ios_base::openmode which)
+{
+    if (dir == std::ios_base::beg)
+        return seekpos(off, which);
+
+    if (dir == std::ios_base::cur)
+        return seekpos(getCurrentPosition() + off, which);
+
+    throw Exception(ErrorCodes::LOGICAL_ERROR, "Wrong seek's base {}", static_cast<int>(dir));
```
Comment (CheSema) [inline src/IO/StdStreamBufFromReadBuffer.cpp:62]: Interesting. There is should be case for std::ios_base::end also.
I definitely have seen that S3 do '.seekg(0, body->end);'.
When it sets context-length in httpRequest (actually that seems like a bug because that information has been provided).

**Comment by CheSema** [comment]
I like that approach. Actually this is the best way when we upload file from local disk to S3. 
I have several question. Mostly just to make history, what and why this code do.

When you copy file you know its size. Why do you still use exponential part upload size instead some fixed?

When you copy from S3 to S3 why do you prefer seakable reading from S3 instead UploadPartCopyRequest? My concern is the following. With seakable reading you read a file twice. First is to calc sha hash. Second is to upload it to S3. Indeed this read is made with fixed buffer size, memory consumption is low. However I think it is worth to do with existing code in order not to have one more realisation with UploadPartCopyRequest.

File: src/IO/S3/copyDataToS3.cpp (hunk 1 above)
Comment (vitlibar) [reply src/IO/S3/copyDataToS3.cpp:477]: I think I have to check the result of `aboutMultipartUpload` - and if it didn't succeed then I need to call `aboutMultipartUpload` again in the end. I'll change the code.

File: src/IO/StdStreamBufFromReadBuffer.cpp (hunk 2 above)
Comment (vitlibar) [reply src/IO/StdStreamBufFromReadBuffer.cpp:62]: The problem is that `ReadBuffer` doesn't have an interface to get the total size. However it's not a problem, I can pass it via a new parameter of the constructor of `StdStreamBufFromReadBuffer`.

**Comment by vitlibar** [comment]
> When you copy file you know its size. Why do you still use exponential part upload size instead some fixed?

Yes you're right, that code was copied from `WriteBufferFromS3` but there are no reason why we should keep that exponential approach for those copy functions.

> When you copy from S3 to S3 why do you prefer seakable reading from S3 instead UploadPartCopyRequest? My concern is the following. With seakable reading you read a file twice. First is to calc sha hash. Second is to upload it to S3. Indeed this read is made with fixed buffer size, memory consumption is low. However I think it is worth to do with existing code in order not to have one more realisation with UploadPartCopyRequest.

I don't quite understand. I don't prefer seekable reading over `UploadPartCopyRequest`. Copying from S3 to S3 with ``UploadPartCopyRequest` must always be better. Seekable reading is not for copying from S3 to S3, it's mostly for uploading data from local disks to S3.

**Comment by CheSema** [comment]
> I don't quite understand. I don't prefer seekable reading over UploadPartCopyRequest

Sorry. Indeed, you don't. You have dedicated realisation for S3toS3 with UploadPartCopyRequest.

File: src/IO/S3/copyDataToS3.cpp (hunk 1 above)
Comment (vitlibar) [reply src/IO/S3/copyDataToS3.cpp:530]: done

File: src/IO/StdStreamBufFromReadBuffer.cpp (hunk 2 above)
Comment (vitlibar) [reply src/IO/StdStreamBufFromReadBuffer.cpp]: done

**Comment by vitlibar** [comment]
> When you copy file you know its size. Why do you still use exponential part upload size instead some fixed?

I did that. Now an uploaded file is splitted into parts of the same size.

File: src/IO/S3/copyDataToS3.cpp [hunk 3]
```diff
@@ -0,0 +1,723 @@
...
+                    /// Otherwise, WriteBuffer could be destroyed in between
+                    /// Releasing lock and condvar notification.
+                    bg_tasks_condvar.notify_one();
+                };
+
+                try
+                {
+                    task->req = fillUploadPartRequest(part_number, part_offset, part_size);
+
+                    schedule([this, task, task_finish_notify]()
```
Comment (CheSema) [inline src/IO/S3/copyDataToS3.cpp:311]: Help me understand here, how many  concurrent uploads are run here? Is it limited thread pool?
My concern is that it runs a lot of tasks, each makes a new connection. It could run out of available inodes or face other limitation inside CH.

Comment (vitlibar) [reply src/IO/S3/copyDataToS3.cpp:311]: It's normally used with `IOThreadPool` . It's limited of course. By default it runs up to 100 threads, so maximum 100 parallel uploads. But it actually must be smaller because `IOThreadPool` is also used for other tasks.

File: src/IO/StdStreamBufFromReadBuffer.cpp [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+std::streampos StdStreamBufFromReadBuffer::seekoff(std::streamoff off, std::ios_base::seekdir dir, std::ios_base::openmode which)
+{
+    if (dir == std::ios_base::beg)
+        return seekpos(off, which);
+    else if (dir == std::ios_base::cur)
+        return seekpos(getCurrentPosition() + off, which);
+    else if (dir == std::ios_base::end)
+        return seekpos(size, which);
```
Comment (CheSema) [inline src/IO/StdStreamBufFromReadBuffer.cpp:60]: You are ignoring arg off in that case. It might be wrong.
S3 sdk always do call seekg(0, end). However it is legal to call for example seekg(-10, end).

File: src/IO/S3/copyDataToS3.cpp [hunk 5]
```diff
@@ -0,0 +1,723 @@
...
+        {
+            calculatePartSize(size);
+            createMultipartUpload();
+
+            size_t position = start_offset;
+            size_t end_position = start_offset + size;
+
+            for (size_t part_number = 1; position < end_position; ++part_number)
+            {
+                if (multipart_upload_aborted)
```
Comment (CheSema) [inline src/IO/S3/copyDataToS3.cpp:207]: Isn't it better to check this right before processUploadPartRequest? In order to stop work as fast as possible if non retryable error occurs. 
My concern is that the code have to wait all task which has been scheduled. If 1000 task were scheduled and only 100 of then is running and finishing with connection timeout. It would take 10 x timeout to finish the upload with an error.

Comment (CheSema) [reply src/IO/S3/copyDataToS3.cpp:207]: It seems like the queue size is pretty big
>         auto queue_size = config.getUInt(".threadpool_writer_queue_size", 1000000);
and all task are about to be pushed to the schedule's queue. In case if first task fail no need to run the rest.

File: src/IO/StdStreamBufFromReadBuffer.cpp (hunk 4 above)
Comment (vitlibar) [reply src/IO/StdStreamBufFromReadBuffer.cpp]: Done, I made it correct

File: src/IO/S3/copyDataToS3.cpp (hunk 5 above)
Comment (vitlibar) [reply src/IO/S3/copyDataToS3.cpp:207]: > Isn't it better to also check multipart_upload_aborted right before processUploadPartRequest?

Done, I changed the code.

File: src/IO/S3/copyDataToS3.cpp (hunk 3 above)
Comment (vitlibar) [reply src/IO/S3/copyDataToS3.cpp:311]: In fact it should use its own thread pools `backups_thread_pool` and `restores_thread_pool`, so I changed the code to use the correct thread pools. Those thread pools are created specially for backups and restores.

**Review by CheSema — APPROVED** [review]

**Comment by vitlibar** [comment]
The test `test_backup_restore_on_cluster/test_disallow_concurrency.py::test_concurrent_restores_on_different_node` is [flaky](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2JhY2t1cF9yZXN0b3JlX29uX2NsdXN0ZXIvdGVzdF9kaXNhbGxvd19jb25jdXJyZW5jeS5weTo6dGVzdF9jb25jdXJyZW50X3Jlc3RvcmVzX29uX2RpZmZlcmVudF9ub2RlJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj)

File: src/IO/StdStreamFromReadBuffer.h [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+};
+
+
+/// `std::iostream`-compatible wrapper around a ReadBuffer.
+class StdStreamFromReadBuffer : public std::iostream
+{
+public:
+    using Base = std::iostream;
+    StdStreamFromReadBuffer(std::unique_ptr<ReadBuffer> buf, size_t size) : Base(&stream_buf), stream_buf(std::move(buf), size) { }
+    StdStreamFromReadBuffer(ReadBuffer & buf, size_t size) : Base(&stream_buf), stream_buf(buf, size) { }
```
Comment (Lloyd-Pottiger) [inline src/IO/StdStreamFromReadBuffer.h:32]: I have some questions about this, 

`Base(&stream_buf)` will call the following constructor

```cpp
template <class _CharT, class _Traits>
basic_streambuf<_CharT, _Traits>::basic_streambuf()
    : __binp_(nullptr),
      __ninp_(nullptr),
      __einp_(nullptr),
      __bout_(nullptr),
      __nout_(nullptr),
      __eout_(nullptr)
{
}

template <class _CharT, class _Traits>
basic_streambuf<_CharT, _Traits>::basic_streambuf(const basic_streambuf& __sb)
    : __loc_(__sb.__loc_),
      __binp_(__sb.__binp_),
      __ninp_(__sb.__ninp_),
      __einp_(__sb.__einp_),
      __bout_(__sb.__bout_),
      __nout_(__sb.__nout_),
      __eout_(__sb.__eout_)
{
}
```

so, `__ninp_` and `__einp_` are nullptr. But std::iostream will call `sgetc()` to get char, so we will always call `underflow()` which does not advance the position.

```cpp
inline _LIBCPP_HIDE_FROM_ABI_AFTER_V1
int_type sgetc() {
    if (__ninp_ == __einp_)
        return underflow();
    return traits_type::to_int_type(*__ninp_);
}
```
