### PR TITLE
Better postgres db engine numeric conversion 

### LINKED ISSUE #20869: postgresql dbEngine bug
when I use clickhouse postgresql dbEngine to connect my postgresql db,I find a bug when my pg table has numeric type col.When I exec "desc pgdb.t1" and pgdb.t1 has numeric type col,it reports `Received exception from server (version 21.2.3):
Code: 42. DB::Exception: Received from localhost:9000. DB::Exception: Decimal data type family must have exactly two arguments: precision and scale: while fetching postgresql table structure.` 
When I exec "desc pgdb.t2" and pgdb.t2 doesn't have numeric type col,everything is ok

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Fixes https://github.com/ClickHouse/ClickHouse/issues/20869

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support conversion from Postgres numeric without precision and scale. https://github.com/ClickHouse/ClickHouse/issues/20869

### CODE REVIEW

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp [hunk 1]
```diff
@@ -54,19 +54,30 @@ static DataTypePtr convertPostgreSQLDataType(std::string & type, bool is_nullabl
...
-            res = std::make_shared<DataTypeDecimal<Decimal32>>(precision, scale);
-        else if (precision <= DecimalUtils::maxPrecision<Decimal64>())
-            res = std::make_shared<DataTypeDecimal<Decimal64>>(precision, scale);
-        else if (precision <= DecimalUtils::maxPrecision<Decimal128>())
-            res = std::make_shared<DataTypeDecimal<Decimal128>>(precision, scale);
-        else if (precision <= DecimalUtils::maxPrecision<Decimal256>())
-            res = std::make_shared<DataTypeDecimal<Decimal256>>(precision, scale);
+        /// Numeric and decimal will both end up here as numeric. If it has type and precision,
+        /// there will be Numeric(x, y), otherwise just Numeric
+        uint32_t precision, scale;
```
Comment (kitaisreal) [inline src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:59]: Consider to use UInt32.

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp [hunk 2]
```diff
@@ -54,19 +54,30 @@ static DataTypePtr convertPostgreSQLDataType(std::string & type, bool is_nullabl
...
+                res = std::make_shared<DataTypeDecimal<Decimal128>>(precision, scale);
+            else if (precision <= DecimalUtils::maxPrecision<Decimal256>())
+                res = std::make_shared<DataTypeDecimal<Decimal256>>(precision, scale);
+        }
+        else
+        {
+            precision = DecimalUtils::maxPrecision<Decimal128>();
+            res = std::make_shared<DataTypeDecimal<Decimal128>>(precision, precision);
+        }
+
```
Comment (kitaisreal) [inline src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:80]: Below there are lines
```
    if (is_nullable)
        res = std::make_shared<DataTypeNullable>(res);
    while (dimensions--)
        res = std::make_shared<DataTypeArray>(res);
```
Should not we first parse array and then convert it to nullable if is_nullable true ?

Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:80]: You mean Nullable(Array(...)) ? It is written [here](https://clickhouse.tech/docs/ru/sql-reference/data-types/nullable/) that is not allowed or has it changed?

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp (hunk 1 above)
Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:59]: Ok

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp [hunk 3]
```diff
@@ -54,19 +54,30 @@ static DataTypePtr convertPostgreSQLDataType(std::string & type, bool is_nullabl
...
+                res = std::make_shared<DataTypeDecimal<Decimal64>>(precision, scale);
+            else if (precision <= DecimalUtils::maxPrecision<Decimal128>())
+                res = std::make_shared<DataTypeDecimal<Decimal128>>(precision, scale);
+            else if (precision <= DecimalUtils::maxPrecision<Decimal256>())
+                res = std::make_shared<DataTypeDecimal<Decimal256>>(precision, scale);
+        }
+        else
+        {
+            precision = DecimalUtils::maxPrecision<Decimal128>();
+            res = std::make_shared<DataTypeDecimal<Decimal128>>(precision, precision);
```
Comment (kitaisreal) [inline src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:78]: Why Decimal128, probably we should use Decimal256 ? And is that correct that for numeric in postgres precision and scale are equal ?
It seems that from https://www.postgresql.org/docs/9.1/datatype-numeric.html#DATATYPE-NUMERIC-TABLE.
```
NUMERIC
without any precision or scale creates a column in which numeric values of any precision and scale can be stored, up to the implementation limit on precision. 
```

For example
```
38 = max precision for Decimal 128.
CREATE TABLE test_decimal (value Decimal(38, 38)) ENGINE=TinyLog
INSERT INTO test_decimal VALUES (2.0);
Code: 69. DB::Exception: Decimal value is too big: 1 digits were read: 2e0. Expected to read decimal with scale 38 and precision 38:  at row 0: data for INSERT was parsed from query
```

From my perspective according to postgreSQL documentation the best we can do is to use Decimal256 and set scale and precision both to 38. What do you think ?

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp (hunk 2 above)
Comment (kitaisreal) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:80]: @kssenii no it is not allowed. No need to fix.

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp (hunk 3 above)
Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:78]: May be 76 instead of 38?

Comment (kitaisreal) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: @kssenii I am not sure but it seems that scale and precision in sum for Decimal256 must be 76 ?

Comment (kitaisreal) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: @kssenii misread 76 for precision 38 for scale.

Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: If referring to doc, they can be equal. 
>  P - precision. Valid range: [ 1 : 76 ]. Determines how many decimal digits number can have (including fraction).
> S - scale. Valid range: [ 0 : P ]. Determines how many decimal digits fraction can have.

Comment (kitaisreal) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: @kssenii  If they will be equal we could not insert value greater than zero right ?

Comment (kitaisreal) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: @kssenii greater than one.

Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: >  the best we can do is to use Decimal256 and set scale and precision both to 38

But it with this it will be the same then. Seems like 76 precision and 38 scale is ok?

Comment (kitaisreal) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: Yes Decimal256, 76 precision, 38 scale will be best.

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp [hunk 4]
```diff
@@ -54,19 +54,31 @@ static DataTypePtr convertPostgreSQLDataType(std::string & type, bool is_nullabl
...
+            precision = getDecimalPrecision(*res);
+            scale = getDecimalScale(*res);
+
+            if (precision <= DecimalUtils::maxPrecision<Decimal32>())
+                res = std::make_shared<DataTypeDecimal<Decimal32>>(precision, scale);
+            else if (precision <= DecimalUtils::maxPrecision<Decimal64>())
+                res = std::make_shared<DataTypeDecimal<Decimal64>>(precision, scale);
+            else if (precision <= DecimalUtils::maxPrecision<Decimal128>())
+                res = std::make_shared<DataTypeDecimal<Decimal128>>(precision, scale);
+            else if (precision <= DecimalUtils::maxPrecision<Decimal256>())
```
Comment (kitaisreal) [inline src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:72]: Probably in postgreSQL explicit precision can be greater than we can support, in that case better to throw exception.

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp (hunk 3 above)
Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp]: Lets leave it Decimal128 instead of 256: `because experimental bigint types are not allowed. Set 'allow_experimental_bigint_types' setting to enable..`

**Review by kitaisreal — APPROVED** [review]

**Comment by AndresElizondo** [comment]
Hello, I know this issue has been closed.
Can someone explain why Decimal128 was preferred over Decimal256?
We're looking into moving data from Postgres to Clickhouse, these `numeric` values are up to `Decimal(76,6)`.
Any guidance on how to get this data moved?
