### PR TITLE
Fix bug when using the same column in the TTL for GROUP BY and SET

### LINKED ISSUE #82055: LOGICAL_ERROR Invalid number of rows in Chunk when using TTL GROUP BY with same columns in SET
```
2025.06.17 17:47:48.974017 [ 724253 ] {1de187f8-24d1-4685-a483-d7f6cb0cc469::all_1_1_1} <Fatal> : Logical error: 'Invalid number of rows in Chunk  UInt32(size = 1) String(size = 2) UInt32(size = 1) UInt8(size = 1) column String at position 1: expected 1, got 2'.
2025.06.17 17:47:48.985426 [ 724253 ] {1de187f8-24d1-4685-a483-d7f6cb0cc469::all_1_1_1} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. ../contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001eff2592
1. ./build/../src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000102167bb
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000a09be2c
3. ./src/Common/Exception.h:137: DB::Exception::Exception<String, String, unsigned long&, unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, String&&, String&&, unsigned long&, unsigned long&, unsigned long&&) @ 0x00000000172b0079
4. ./build/./src/Processors/Chunk.cpp:65: DB::Chunk::checkNumRowsIsConsistent() @ 0x00000000172ae26d
5. ./build/./src/Processors/Chunk.cpp:19: DB::Chunk::Chunk(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long) @ 0x00000000172ae0f0
6. ./build/./src/Processors/Transforms/TTLTransform.cpp:154: DB::TTLTransform::generate() @ 0x00000000175fd423
7. ./build/./src/Processors/IAccumulatingTransform.cpp:96: DB::IAccumulatingTransform::work() @ 0x00000000172b77cb
8. ./build/../src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x00000000172d835b
9. ./build/../src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000172cd026
10. ./build/../src/Processors/Executors/PipelineExecutor.cpp:177: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000172cc8c3
11. ./build/../src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x00000000172dcd1c
12. ./build/../src/Processors/Executors/PullingPipelineExecutor.cpp:65: DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x00000000172dce78
13. ./build/../src/Storages/MergeTree/MergeTask.cpp:889: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() const @ 0x0000000016b9dd3b
14. ./build/../src/Storages/MergeTree/MergeTask.cpp:716: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x0000000016b9c559
15. ./build/../src/Storages/MergeTree/MergeTask.cpp:1518: DB::MergeTask::execute() @ 0x0000000016ba2f6a
16. ./build/../src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:58: DB::MergePlainMergeTreeTask::executeStep() @ 0x0000000016f686a5
17. ./build/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:318: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x0000000016bcc1d0
18. ./build/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:363: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000016bccb13
19. ../contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000010339bd3
20. ../contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000001033fb1d
21. ../contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000010337246
22. ../contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001033d6e0
23. start_thread @ 0x0000000000094ac3
24. __GI___clone3 @ 0x0000000000126850
```

Repro:

```sql
CREATE TABLE t
(
    `timestamp` DateTime,
    `id` String,
    `value` UInt8,
)
ENGINE = MergeTree
ORDER BY (id, toStartOfDay(timestamp))
TTL timestamp + toIntervalDay(1)
GROUP BY id, toStartOfDay(timestamp)
SET id = argMax(id, timestamp), value = argMax(value, timestamp);

INSERT INTO t VALUES (parseDateTimeBestEffort('2025-06-9 10:00'), 'pepe', 1);
```

### PR DESCRIPTION
**Pull request by pamarcos**
- Fix LOGICAL_ERROR and following crash with intersecting columns in TTL GROUP BY and SET by adding the column values once once.
- Prioritize the SET over the GROUP BY to make the result what's expected

```sql
CREATE OR REPLACE TABLE t
(
    `timestamp` DateTime,
    `id` String,
    `value` String,
)
ENGINE = MergeTree
ORDER BY (id, toStartOfDay(timestamp))
TTL timestamp + toIntervalDay(1)
GROUP BY id, toStartOfDay(timestamp)
SET id = max(value);

INSERT INTO t VALUES (parseDateTimeBestEffort('2020-06-9 10:00'), 'pepe', 'a');
INSERT INTO t VALUES (parseDateTimeBestEffort('2020-06-10 10:00'), 'pepe', 'b');
INSERT INTO t VALUES (parseDateTimeBestEffort('2020-06-10 11:00'), 'pepe', 'c');
```

Before, with GROUP BY first
```sql
-- TTL GROUP BY is applied
2020-06-09 10:00:00     pepe    a
2020-06-10 10:00:00     pepe    b
```

Now, with SET first
```sql
-- TTL GROUP BY is applied
2020-06-09 10:00:00     a       a
2020-06-10 10:00:00     c       b
```

Close https://github.com/ClickHouse/ClickHouse/issues/82055

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix LOGICAL_ERROR and following crash when using the same column in the TTL for GROUP BY and SET

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/TTL/TTLAggregationAlgorithm.cpp [hunk 1]
```diff
@@ -215,18 +217,26 @@ void TTLAggregationAlgorithm::finalizeAggregates(MutableColumns & result_columns
...
 
             for (const auto & it : description.set_parts)
             {
                 const IColumn * values_column = agg_block.getByName(it.expression_result_column_name).column.get();
-                auto & result_column = result_columns[header.getPositionByName(it.column_name)];
-                result_column->insertRangeFrom(*values_column, 0, agg_block.rows());
+
+                /// In case the same column is used in the GROUP BY and in the SET clause, we need to make sure
+                /// it's only added once.
+                if (!columns_added.contains(it.column_name))
```
Comment (antaljanosbenjamin) [inline src/Processors/TTL/TTLAggregationAlgorithm.cpp]: I will be honest, this feels kind of wonky. Technically you are right, however it is not clear why the column is not updated. Have you considered:
1. Using the result of the `SET` expression instead of `GROUP BY`?
2. Have you considered preventing such cases when there are common expressions between `GROUP BY` and `SET`?

File: tests/queries/0_stateless/03545_number_of_rows_in_ttltransform.sql [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+INSERT INTO t VALUES (parseDateTimeBestEffort('2025-06-10 11:00'), 'pepe', 3);
+
+OPTIMIZE TABLE t FINAL;
+SELECT '-- TTL GROUP BY is applied';
+SELECT * FROM t;
+
+INSERT INTO t VALUES (parseDateTimeBestEffort('2025-05-10 11:00'), 'pepe', 4);
+OPTIMIZE TABLE t FINAL;
+SELECT '-- TTL removes old elements';
+SELECT * FROM t;
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03545_number_of_rows_in_ttltransform.sql]: Just to make sure the test doesn't get flaky in any case.

```suggestion
SELECT * FROM t ORDER BY ALL;

INSERT INTO t VALUES (parseDateTimeBestEffort('2025-05-10 11:00'), 'pepe', 4);
OPTIMIZE TABLE t FINAL;
SELECT '-- TTL removes old elements';
SELECT * FROM t ORDER BY ALL;
```

File: src/Processors/TTL/TTLAggregationAlgorithm.cpp (hunk 1 above)
Comment (pamarcos) [reply src/Processors/TTL/TTLAggregationAlgorithm.cpp]: >1. Using the result of the SET expression instead of GROUP BY?

It's still using the SET expression because of the prior

```cpp
            for (const auto & it : description.set_parts)
                it.expression->execute(agg_block);
```

>Have you considered preventing such cases when there are common expressions between GROUP BY and SET?

Yes, we discussed a little bit about it. I didn't want to break any existing tables. I've made my peace with this thing and even though I think using the same column in GROUP BY and in SET might be confusing, there might be use cases in which you may want to use it. I've updated the test in https://github.com/ClickHouse/ClickHouse/pull/82054/commits/c55601d3cd5a02ccd089e0178b0601a7527c4d9b to ensure it works as expected

Comment (pamarcos) [reply src/Processors/TTL/TTLAggregationAlgorithm.cpp]: I've done a commit so that `SET` takes preference over `GROUP BY` because otherwise results are quite inconsistent: https://github.com/ClickHouse/ClickHouse/pull/82054/commits/a6fdb1063ffca82afc769b3eedb8fc2c57cb3ac6

**Comment by pamarcos** [comment]
I've created another issue to address separately: https://github.com/ClickHouse/ClickHouse/issues/82434

**Review by antaljanosbenjamin — APPROVED** [review]
