### PR TITLE
Make ClickHouse behaviour on multiple read from pipe more understandable

### LINKED ISSUE #11124: clickhouse-local freezes on multiple read from pipe
```
echo 1 | build-clang10/programs/clickhouse-local --structure "a int" --query "select a from table where a in (select a from table)"
```

This does not finish. Works fine if I put this `1` into a file and specify it with `--file`.
This is a usability problem for using `clickhouse-local` in a pipeline. Also sometimes it doesn't freeze but returns unexpected result, which is even worse. I've had this happen but don't remember the exact scenario now.

### PR DESCRIPTION
**Pull request by BoloniniD**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If file descriptor in `File` table is regular file - allow to read multiple times from it. It allows `clickhouse-local` to read multiple times from stdin (with multiple SELECT queries or subqueries) if stdin is a regular file like `clickhouse-local --query "SELECT * FROM table UNION ALL SELECT * FROM table" ... < file`. This closes #11124. Co-authored with @alexey-milovidov.

### CODE REVIEW

**Review by azat — COMMENTED** [review]
Consider adding a test, smth like:

```sh
clickhouse local --structure 'key String' -q 'select * from table; select * from table;' <<<foo # fails with pipeline error

echo foo > /tmp/foo
./clickhouse local --structure 'key String' -q 'select * from table; select * from table;' --file /tmp/foo # ok

mkfifo /tmp/pipe
echo foo > /tmp/pipe &
./clickhouse local --structure 'key String' -q 'select * from table; select * from table;' --file /tmp/pipe # hangs because it opens via path, and it will hang for the second open of pipe, since there is no write endpoint.

```

Also right now the following does not works, while it should:

```sh
./clickhouse local --structure 'key String' -q 'select * from table; select * from table;' --file <(echo foo)
```

And the following does not work because of additional check in `ITableFunctionFileLike::parseArguments`

```sh
./clickhouse local --stacktrace -q "select * from file(0, 'TSV', 'key String');" <<<foo
```

File: src/Storages/StorageFile.h [hunk 1]
```diff
@@ -90,6 +90,7 @@ class StorageFile final : public shared_ptr_helper<StorageFile>, public IStorage
     std::optional<FormatSettings> format_settings;
 
     int table_fd = -1;
+    int reads = 0;
```
[the remark this answers is not in the document]
Comment (BoloniniD) [reply src/Storages/StorageFile.h:93]: Yes, it seems we can just use `if (this_ptr->table_fd_was_used)` instead of `if (reads > 0 && this_ptr->use_table_fd)`. Fixed it.

File: src/Storages/StorageFile.cpp [hunk 2]
```diff
@@ -509,9 +510,23 @@ Pipe StorageFile::read(
             else
                 return metadata_snapshot->getColumns();
         };
+        // if we do multiple reads from pipe, we want to check if pipe is a regular file or a pipe
+        if (reads > 0 && this_ptr->use_table_fd)
+        {
+            if (fs::is_regular_file(this_ptr->base_path) && lseek(this_ptr->table_fd, this_ptr->table_fd_init_offset, SEEK_SET) < 0)
```
[the remark this answers is not in the document]
Comment (BoloniniD) [reply src/Storages/StorageFile.cpp:516]: Would it be okay to use S _ISREG to check the file, or should I use something else?

[the remark this answers is not in the document]
Comment (azat) [reply src/Storages/StorageFile.cpp:516]: Yep, this is what I meant.

[the remark this answers is not in the document]
Comment (BoloniniD) [reply src/Storages/StorageFile.cpp:516]: Ok

**Comment by BoloniniD** [comment]
Tried to reproduce the problem with 

> ./clickhouse local --stacktrace -q "select * from file(0, 'TSV', 'key String');" <<<foo

As it turns out `ITableFunctionFileLike::parseArguments` fails to represent 0 in the arguments for the file as a String. If I use '0' instead, then `ITableFunctionFileLike::parseArguments` works fine. Is it really necessary to change the `.safeGet<String>()` check? @azat

**Comment by azat** [comment]
>As it turns out ITableFunctionFileLike::parseArguments fails to represent 0 in the arguments for the file as a String.

Right.

> If I use '0' instead, then ITableFunctionFileLike::parseArguments works fine. Is it really necessary to change the .safeGet<String>() check? @azat

Actually thinking about this a little bit more, and it should not accept custom fd, since this a security vulnerability (since any user may read from any file that the process keeps open)

File: src/Storages/StorageFile.cpp [hunk 3]
```diff
@@ -509,6 +497,27 @@ Pipe StorageFile::read(
             else
                 return metadata_snapshot->getColumns();
         };
+        // if we do multiple reads from pipe, we want to check if pipe is a regular file or a pipe
+        if (this_ptr->table_fd_was_used)
+        {
+            if (S_ISREG(this_ptr->table_fd))
```
Comment (azat) [inline src/Storages/StorageFile.cpp:503]: `S_ISREG` is a macro, that accept `stat.st_mode` not fd.

File: src/Storages/StorageFile.cpp [hunk 4]
```diff
@@ -509,6 +497,27 @@ Pipe StorageFile::read(
...
+                int seekable_table_fd = dup(this_ptr->table_fd);
+                if (lseek(seekable_table_fd, this_ptr->table_fd_init_offset, SEEK_SET) < 0)
+                {
+                    throw Exception("File descriptor isn't seekable, inside " + this_ptr->getName(), ErrorCodes::CANNOT_SEEK_THROUGH_FILE);
+                }
+            }
+            else
+            {
+                // else if fd is a pipeline, then throw an Exception
+                throw Exception("Cannot read from a pipeline twice", ErrorCodes::CANNOT_READ_FROM_FILE_DESCRIPTOR);
```
Comment (azat) [inline src/Storages/StorageFile.cpp:518]: I guess this should mean that this file is not regular.

File: src/Storages/StorageFile.cpp [hunk 5]
```diff
@@ -509,6 +497,27 @@ Pipe StorageFile::read(
...
+        // if we do multiple reads from pipe, we want to check if pipe is a regular file or a pipe
+        if (this_ptr->table_fd_was_used)
+        {
+            if (S_ISREG(this_ptr->table_fd))
+            {
+                if (this_ptr->table_fd_init_offset < 0)
+                {
+                    throw Exception("File descriptor isn't seekable, inside " + this_ptr->getName(), ErrorCodes::CANNOT_SEEK_THROUGH_FILE);
+                }
+                int seekable_table_fd = dup(this_ptr->table_fd);
```
Comment (azat) [inline src/Storages/StorageFile.cpp:509]: But why do you change the offset via dupped fd? Yes it will change the offset on the initial fd, but it will leak fd, and why do we need separate fd here?

**Review by azat — CHANGES_REQUESTED** [review]
Also please don't miss this comment - https://github.com/ClickHouse/ClickHouse/pull/25960/#pullrequestreview-699604186 (everything except for `File` by numeric fd)

File: src/Storages/StorageFile.cpp (hunk 4 above)
Comment (BoloniniD) [reply src/Storages/StorageFile.cpp:518]: Fixed the comment.

File: src/Storages/StorageFile.cpp (hunk 3 above)
Comment (BoloniniD) [reply src/Storages/StorageFile.cpp:503]: Added `struct stat fd_stat` and fixed that.

File: src/Storages/StorageFile.cpp (hunk 5 above)
Comment (BoloniniD) [reply src/Storages/StorageFile.cpp:509]: I thought it was incorrect to apply lseek directly to the table file descriptor, so I dupped it and lseek'd the separate fd. It seems that we don't need to do this, so `lseek(this_ptr->table_fd, this_ptr->table_fd_init_offset, SEEK_SET) < 0` will be ok.

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 6]
```diff
@@ -0,0 +1,52 @@
+#!/usr/bin/env bash
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:1]: You forget to make it eXecutable (hence fasttest fails)

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+STD_ERROR_CAPTURED="$CURDIR/01941_std_error_captured.log"
+
+echo 'File generated:'
+${CLICKHOUSE_LOCAL} -q "SELECT number, if(number in (4,6), 'AAA', 'BBB') from numbers(7) FORMAT TSV" | tr '\t' ',' >"$SAMPLE_FILE"
+cat "$SAMPLE_FILE"
+
+echo '******************'
+echo 'Attempt to read twice from a pipeline'
+cat ${CLICKHOUSE_LOCAL} --structure 'key String' -q 'select * from table; select * from table;' <<<foo 2>"$STD_ERROR_CAPTURED"
+ret = $?
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:16]: [shellcheck report](https://clickhouse-test-reports.s3.yandex.net/25960/350f2c0455b37f7e6249dbcb255ea923275ccc83/style_check.html#fail1) reports:

```

In 01941_multiple_pipe_read.sh line 16:
ret = $?
    ^-- SC1068: Don't put spaces around the = in assignments (or quote to make it literal).
```

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 8]
```diff
@@ -0,0 +1,52 @@
+#!/usr/bin/env bash
+CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CURDIR"/../shell_config.sh
+
+SAMPLE_FILE="$CURDIR/01941_sample_data.csv"
+STD_ERROR_CAPTURED="$CURDIR/01941_std_error_captured.log"
+
+echo 'File generated:'
+${CLICKHOUSE_LOCAL} -q "SELECT number, if(number in (4,6), 'AAA', 'BBB') from numbers(7) FORMAT TSV" | tr '\t' ',' >"$SAMPLE_FILE"
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:10]:
```suggestion
${CLICKHOUSE_LOCAL} -q "SELECT number, if(number in (4,6), 'AAA', 'BBB') from numbers(7) FORMAT CSV" --format_csv_delimiter=, >"$SAMPLE_FILE"
```

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+cat "$SAMPLE_FILE"
+
+echo '******************'
+echo 'Attempt to read twice from a pipeline'
+cat ${CLICKHOUSE_LOCAL} --structure 'key String' -q 'select * from table; select * from table;' <<<foo 2>"$STD_ERROR_CAPTURED"
+ret = $?
+echo "Return code: $ret"
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:17]: you can use `set -e` instead of manually checking return code every time (`set -e` is not perfect, but will work for you)

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 10]
```diff
@@ -0,0 +1,52 @@
...
+SAMPLE_FILE="$CURDIR/01941_sample_data.csv"
+STD_ERROR_CAPTURED="$CURDIR/01941_std_error_captured.log"
+
+echo 'File generated:'
+${CLICKHOUSE_LOCAL} -q "SELECT number, if(number in (4,6), 'AAA', 'BBB') from numbers(7) FORMAT TSV" | tr '\t' ',' >"$SAMPLE_FILE"
+cat "$SAMPLE_FILE"
+
+echo '******************'
+echo 'Attempt to read twice from a pipeline'
+cat ${CLICKHOUSE_LOCAL} --structure 'key String' -q 'select * from table; select * from table;' <<<foo 2>"$STD_ERROR_CAPTURED"
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:15]: Why do you redirect stderr?

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 11]
```diff
@@ -0,0 +1,52 @@
...
+ret = $?
+echo "Return code: $ret"
+if [ "$ret" -eq "0" ]; then
+    echo "OK"
+else
+    echo "FAILED: return code is not 0"
+fi
+
+echo '******************'
+./clickhouse local --structure 'key String' -q 'select * from table; select * from table;' --file /tmp/foo
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:25]: Hm, it should report `File /tmp/foo` doesn't exist

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh [hunk 12]
```diff
@@ -0,0 +1,52 @@
...
+echo 'Attempt to read twice from a pipe'
+mkfifo /tmp/pipe
```
Comment (azat) [inline tests/queries/0_stateless/01941_multiple_pipe_read.sh:39]: Better to use some random name, i.e. `mktemp` or `$test_name.pipe`

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh (hunk 10 above)
Comment (azat) [reply tests/queries/0_stateless/01941_multiple_pipe_read.sh:15]: And what is `cat ${CLICKHOUSE_LOCAL}` ?

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh (hunk 11 above)
Comment (azat) [reply tests/queries/0_stateless/01941_multiple_pipe_read.sh:25]: And you should use `${CLICKHOUSE_LOCAL}` everywhere

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh (hunk 6 above)
Comment (BoloniniD) [reply tests/queries/0_stateless/01941_multiple_pipe_read.sh:1]: Fixed that

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh (hunk 11 above)
Comment (BoloniniD) [reply tests/queries/0_stateless/01941_multiple_pipe_read.sh]: Fixed that

File: tests/queries/0_stateless/01941_multiple_pipe_read.sh (hunk 12 above)
Comment (BoloniniD) [reply tests/queries/0_stateless/01941_multiple_pipe_read.sh]: Done

File: tests/queries/0_stateless/01947_multiple_pipe_read.sh [hunk 13]
```diff
@@ -0,0 +1,27 @@
+#!/usr/bin/env bash
+CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CURDIR"/../shell_config.sh
+
+SAMPLE_FILE="$CURDIR/01947_sample_data.csv"
```
Comment (azat) [inline tests/queries/0_stateless/01947_multiple_pipe_read.sh:6]: Because it uses one file, it is not possible to run flaky check (runs tests in parallel multiple times) - https://clickhouse-test-reports.s3.yandex.net/25960/bab7681bc18fbaf7df49737ca72cfe70756a5f62/functional_stateless_tests_flaky_check_(address)/test_run.txt.out.log
To fix this, you can simply use `mktemp`, i.e. `mktemp --tmpdir "$CURDIR" 01947_multiple_pipe_read_saple_data_XXXXXX.sh` (completely untested, but you can check it using `clickhouse-test --test-runs 100 01947_multiple_pipe_read. --jobs 8`)

File: tests/queries/0_stateless/01947_multiple_pipe_read.sh [hunk 14]
```diff
@@ -0,0 +1,27 @@
...
+STD_ERROR_CAPTURED="$CURDIR/01947_std_error_captured.log"
```
Comment (azat) [inline tests/queries/0_stateless/01947_multiple_pipe_read.sh:7]: Same here.

File: src/Storages/StorageFile.cpp [hunk 15]
```diff
@@ -509,6 +498,31 @@ Pipe StorageFile::read(
...
+                }
+                if (lseek(this_ptr->table_fd, this_ptr->table_fd_init_offset, SEEK_SET) < 0)
+                {
+                    throw Exception("File descriptor isn't seekable, inside " + this_ptr->getName(), ErrorCodes::CANNOT_SEEK_THROUGH_FILE);
+                }
+            }
+            else
+            {
+                // else if fd is not a regular file, then throw an Exception
+                throw Exception("Cannot read from a pipeline twice", ErrorCodes::CANNOT_READ_FROM_FILE_DESCRIPTOR);
```
Comment (azat) [inline src/Storages/StorageFile.cpp:523]: BTW why do you call this pipeline not pipe?

File: tests/queries/0_stateless/01947_multiple_pipe_read.sh [hunk 16]
```diff
@@ -0,0 +1,27 @@
...
+
+echo 'File generated:'
+${CLICKHOUSE_LOCAL} -q "SELECT number, if(number in (4,6), 'AAA', 'BBB') from numbers(7) FORMAT CSV" --format_csv_delimiter=, >"$SAMPLE_FILE"
+cat "$SAMPLE_FILE"
+
+echo '******************'
+echo 'Attempt to read twice from a pipeline'
+${CLICKHOUSE_LOCAL} --structure 'key String' -q 'select * from table; select * from table;' <<<foo
```
Comment (azat) [inline tests/queries/0_stateless/01947_multiple_pipe_read.sh:15]: Also it is better not to use this in tests, since the behavior is different in different versions on bash:

```
$ echo -n "$BASH_VERSION: "; test -p /dev/fd/0 <<<foo && echo pipe || echo regular
5.1.8(1)-release: pipe
$ docker run --rm -it ubuntu:20.04 bash -c 'echo -n "$BASH_VERSION: "; test -p /dev/fd/0 <<<foo && echo pipe || echo regular'
5.0.17(1)-release: regular
```

You already have test with pipe (`echo 1 | clickhouse-local`), this is enough.

File: src/Storages/StorageFile.cpp (hunk 15 above)
Comment (BoloniniD) [reply src/Storages/StorageFile.cpp]: Changed error message

File: tests/queries/0_stateless/01947_multiple_pipe_read.sh (hunk 14 above)
Comment (BoloniniD) [reply tests/queries/0_stateless/01947_multiple_pipe_read.sh]: Done

File: tests/queries/0_stateless/01947_multiple_pipe_read.sh (hunk 16 above)
Comment (BoloniniD) [reply tests/queries/0_stateless/01947_multiple_pipe_read.sh]: Removed that test

**Comment by azat** [comment]
>[Stress test (undefined) — Killed by signal (in clickhouse-server.log)](https://clickhouse-test-reports.s3.yandex.net/25960/19b673fb3b2ef2c5292193e255818a62e5361a68/stress_test_(undefined).html#fail1)

#26464

**Review by azat — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Merged in #26777.
