### PR TITLE
Move CatBoost evaluation into clickhouse-library-bridge

### LINKED ISSUE #27870: CatBoostModel.cpp calls `dlerror` from libc
test_catboost_model_first_evaluate
```
2021.08.19 13:59:13.236203 [ 348 ] {} <Fatal> BaseDaemon: ########################################
2021.08.19 13:59:13.237234 [ 348 ] {} <Fatal> BaseDaemon: (version 21.9.1.7821 (official build), build id: B93FC7D1AC073387F233DA0D5F4B5D59FC5A5F66) (from thread 194) (query_id: ec2b7d73-664e-46be-8e8a-e48c71f0b91a) Received signal Illegal instruction (4)
2021.08.19 13:59:13.237834 [ 348 ] {} <Fatal> BaseDaemon: Illegal operand.
2021.08.19 13:59:13.238528 [ 348 ] {} <Fatal> BaseDaemon: Stack trace: 0x139acebd 0x1e5d6e4a 0x1e5d17f7 0x1e5ccfa4 0x1e5cc7fa 0x1e5cc74d 0x1e5cc688 0x1e5cc620 0x1e5cc3e0 0x1e5cc064 0x1e5cbe92 0x1e5cbd31 0x1e5cb5dc 0x1e5cb2f7 0x1e5ca59f 0x1e5ca1f6 0x1e590120 0x1e5933d0 0x1e59335c 0x1e5932dc 0x1e59325a 0x1e5931e2 0x1e5a0368 0x1e5a027a 0x1e59cca6 0x1e59ac0b 0x1e598be9 0x1e5c6cff 0x1e5c6ac9 0x1e5c69d2 0x1e593c67 0x1e593bf5 0x1e593f8d 0x1717321d 0x171721b2 0x1631fa33 0x1dc60266 0x1dc5fdb0 0x1dc602c4 0x1e333ca3 0x1e6b61cb
2021.08.19 13:59:13.242518 [ 348 ] {} <Fatal> BaseDaemon: 4. ./obj-x86_64-linux-gnu/../base/harmful/harmful.c:199: dlerror @ 0x139acebd in /usr/bin/clickhouse
2021.08.19 13:59:13.304643 [ 348 ] {} <Fatal> BaseDaemon: 5. ./obj-x86_64-linux-gnu/../src/Common/SharedLibrary.cpp:36: DB::SharedLibrary::getImpl(std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool) @ 0x1e5d6e4a in /usr/bin/clickhouse
2021.08.19 13:59:13.467250 [ 348 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/SharedLibrary.h:24: void* (*DB::SharedLibrary::get<void* (*)()>(std::__1::basic_string_view<char, std::__1::char_traits<char> >))() @ 0x1e5d17f7 in /usr/bin/clickhouse
2021.08.19 13:59:13.627541 [ 348 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Interpreters/CatBoostModel.cpp:456: void DB::(anonymous namespace)::CatBoostLibHolder::load<void* (*)()>(void* (*&)(), std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5ccfa4 in /usr/bin/clickhouse
2021.08.19 13:59:13.785122 [ 348 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Interpreters/CatBoostModel.cpp:464: DB::(anonymous namespace)::CatBoostLibHolder::initAPI() @ 0x1e5cc7fa in /usr/bin/clickhouse
2021.08.19 13:59:13.941766 [ 348 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Interpreters/CatBoostModel.cpp:443: DB::(anonymous namespace)::CatBoostLibHolder::CatBoostLibHolder(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x1e5cc74d in /usr/bin/clickhouse
2021.08.19 13:59:14.097582 [ 348 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:886: void std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder>::construct<DB::(anonymous namespace)::CatBoostLibHolder, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(DB::(anonymous namespace)::CatBoostLibHolder*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cc688 in /usr/bin/clickhouse
2021.08.19 13:59:14.254706 [ 348 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:521: void std::__1::allocator_traits<std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder> >::__construct<DB::(anonymous namespace)::CatBoostLibHolder, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder>&, DB::(anonymous namespace)::CatBoostLibHolder*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cc620 in /usr/bin/clickhouse
2021.08.19 13:59:14.411101 [ 348 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:482: void std::__1::allocator_traits<std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder> >::construct<DB::(anonymous namespace)::CatBoostLibHolder, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder>&, DB::(anonymous namespace)::CatBoostLibHolder*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cc3e0 in /usr/bin/clickhouse
2021.08.19 13:59:14.568291 [ 348 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2594: std::__1::__shared_ptr_emplace<DB::(anonymous namespace)::CatBoostLibHolder, std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder> >::__shared_ptr_emplace<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cc064 in /usr/bin/clickhouse
2021.08.19 13:59:14.735862 [ 348 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3360: std::__1::shared_ptr<DB::(anonymous namespace)::CatBoostLibHolder> std::__1::allocate_shared<DB::(anonymous namespace)::CatBoostLibHolder, std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void>(std::__1::allocator<DB::(anonymous namespace)::CatBoostLibHolder> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cbe92 in /usr/bin/clickhouse
2021.08.19 13:59:14.900351 [ 348 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3369: std::__1::shared_ptr<DB::(anonymous namespace)::CatBoostLibHolder> std::__1::make_shared<DB::(anonymous namespace)::CatBoostLibHolder, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cbd31 in /usr/bin/clickhouse
2021.08.19 13:59:15.083533 [ 348 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Interpreters/CatBoostModel.cpp:490: DB::(anonymous namespace)::getCatBoostWrapperHolder(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e5cb5dc in /usr/bin/clickhouse
2021.08.19 13:59:15.244953 [ 348 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/Interpreters/CatBoostModel.cpp:502: DB::CatBoostModel::CatBoostModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::ExternalLoadableLifetime const&) @ 0x1e5cb2f7 in /usr/bin/clickhouse
2021.08.19 13:59:15.469473 [ 348 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068: std::__1::__unique_if<DB::CatBoostModel>::__unique_single std::__1::make_unique<DB::CatBoostModel, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::ExternalLoadableLifetime&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, DB::ExternalLoadableLifetime&) @ 0x1e5ca59f in /usr/bin/clickhouse
2021.08.19 13:59:15.691083 [ 348 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalModelsLoader.cpp:30: DB::ExternalModelsLoader::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1e5ca1f6 in /usr/bin/clickhouse
2021.08.19 13:59:16.017786 [ 348 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:1498: DB::ExternalLoader::createObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) const @ 0x1e590120 in /usr/bin/clickhouse
2021.08.19 13:59:16.418175 [ 348 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:1264: auto DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1::operator()<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) const @ 0x1e5933d0 in /usr/bin/clickhouse
2021.08.19 13:59:16.805223 [ 348 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1&>(fp)(std::__1::forward<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(fp0), std::__1::forward<DB::ExternalLoader::ObjectConfig const&>(fp0), std::__1::forward<std::__1::shared_ptr<DB::IExternalLoadable const> const&>(fp0))) std::__1::__invoke<DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&>(DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) @ 0x1e59335c in /usr/bin/clickhouse
2021.08.19 13:59:17.162490 [ 348 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:317: std::__1::shared_ptr<DB::IExternalLoadable const> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::IExternalLoadable const> >::__call<DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&>(DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) @ 0x1e5932dc in /usr/bin/clickhouse
2021.08.19 13:59:17.524810 [ 348 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1, std::__1::shared_ptr<DB::IExternalLoadable const> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) @ 0x1e59325a in /usr/bin/clickhouse
2021.08.19 13:59:17.901028 [ 348 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: std::__1::shared_ptr<DB::IExternalLoadable const> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IExternalLoadable const> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExternalLoader::ExternalLoader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Logger*)::$_1, std::__1::shared_ptr<DB::IExternalLoadable const> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&)> >(std::__1::__function::__policy_storage const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) @ 0x1e5931e2 in /usr/bin/clickhouse
2021.08.19 13:59:18.248391 [ 348 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<std::__1::shared_ptr<DB::IExternalLoadable const> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) const @ 0x1e5a0368 in /usr/bin/clickhouse
2021.08.19 13:59:18.585908 [ 348 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560: std::__1::function<std::__1::shared_ptr<DB::IExternalLoadable const> (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const> const&) const @ 0x1e5a027a in /usr/bin/clickhouse
2021.08.19 13:59:18.924246 [ 348 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:1026: DB::ExternalLoader::LoadingDispatcher::loadSingleObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const>) @ 0x1e59cca6 in /usr/bin/clickhouse
2021.08.19 13:59:19.254967 [ 348 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:981: DB::ExternalLoader::LoadingDispatcher::doLoading(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>) @ 0x1e59ac0b in /usr/bin/clickhouse
2021.08.19 13:59:19.582242 [ 348 ] {} <Fatal> BaseDaemon: 30. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:921: DB::ExternalLoader::LoadingDispatcher::startLoading(DB::ExternalLoader::LoadingDispatcher::Info&, bool, unsigned long) @ 0x1e598be9 in /usr/bin/clickhouse
2021.08.19 13:59:19.975862 [ 348 ] {} <Fatal> BaseDaemon: 31. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:0: DB::ExternalLoader::LoadingDispatcher::loadImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, bool, std::__1::unique_lock<std::__1::mutex>&)::'lambda'()::operator()() const @ 0x1e5c6cff in /usr/bin/clickhouse
2021.08.19 13:59:20.370266 [ 348 ] {} <Fatal> BaseDaemon: 32. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__mutex_base:405: void std::__1::condition_variable::wait<DB::ExternalLoader::LoadingDispatcher::loadImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, bool, std::__1::unique_lock<std::__1::mutex>&)::'lambda'()>(std::__1::unique_lock<std::__1::mutex>&, DB::ExternalLoader::LoadingDispatcher::loadImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, bool, std::__1::unique_lock<std::__1::mutex>&)::'lambda'()) @ 0x1e5c6ac9 in /usr/bin/clickhouse
2021.08.19 13:59:20.758840 [ 348 ] {} <Fatal> BaseDaemon: 33. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:829: DB::ExternalLoader::LoadingDispatcher::loadImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >, bool, std::__1::unique_lock<std::__1::mutex>&) @ 0x1e5c69d2 in /usr/bin/clickhouse
2021.08.19 13:59:21.078837 [ 348 ] {} <Fatal> BaseDaemon: 34. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:595: DB::ExternalLoader::LoadResult DB::ExternalLoader::LoadingDispatcher::tryLoad<DB::ExternalLoader::LoadResult>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) @ 0x1e593c67 in /usr/bin/clickhouse
2021.08.19 13:59:21.403902 [ 348 ] {} <Fatal> BaseDaemon: 35. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:1354: DB::ExternalLoader::LoadResult DB::ExternalLoader::tryLoad<DB::ExternalLoader::LoadResult, void>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) const @ 0x1e593bf5 in /usr/bin/clickhouse
2021.08.19 13:59:21.738466 [ 348 ] {} <Fatal> BaseDaemon: 36. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalLoader.cpp:1366: std::__1::shared_ptr<DB::IExternalLoadable const> DB::ExternalLoader::load<std::__1::shared_ptr<DB::IExternalLoadable const>, void>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1e593f8d in /usr/bin/clickhouse
2021.08.19 13:59:22.002970 [ 348 ] {} <Fatal> BaseDaemon: 37. ./obj-x86_64-linux-gnu/../src/Interpreters/ExternalModelsLoader.h:25: DB::ExternalModelsLoader::getModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1717321d in /usr/bin/clickhouse
2021.08.19 13:59:22.256946 [ 348 ] {} <Fatal> BaseDaemon: 38. ./obj-x86_64-linux-gnu/../src/Functions/FunctionsExternalModels.cpp:52: DB::FunctionModelEvaluate::getReturnTypeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x171721b2 in /usr/bin/clickhouse
2021.08.19 13:59:22.363653 [ 348 ] {} <Fatal> BaseDaemon: 39. ./obj-x86_64-linux-gnu/../src/Functions/IFunctionAdaptors.h:123: DB::FunctionToOverloadResolverAdaptor::getReturnTypeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x1631fa33 in /usr/bin/clickhouse
2021.08.19 13:59:22.713087 [ 348 ] {} <Fatal> BaseDaemon: 40. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:359: DB::IFunctionOverloadResolver::getReturnTypeWithoutLowCardinality(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x1dc60266 in /usr/bin/clickhouse
2021.08.19 13:59:23.066185 [ 348 ] {} <Fatal> BaseDaemon: 41. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:314: DB::IFunctionOverloadResolver::getReturnType(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x1dc5fdb0 in /usr/bin/clickhouse
2021.08.19 13:59:23.419197 [ 348 ] {} <Fatal> BaseDaemon: 42. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:329: DB::IFunctionOverloadResolver::build(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x1dc602c4 in /usr/bin/clickhouse
2021.08.19 13:59:25.033066 [ 348 ] {} <Fatal> BaseDaemon: 43. ./obj-x86_64-linux-gnu/../src/Interpreters/ActionsDAG.cpp:204: DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x1e333ca3 in /usr/bin/clickhouse
2021.08.19 13:59:25.662213 [ 348 ] {} <Fatal> BaseDaemon: 44. ./obj-x86_64-linux-gnu/../src/Interpreters/ActionsVisitor.cpp:570: DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x1e6b61cb in /usr/bin/clickhouse
2021.08.19 13:59:27.013815 [ 348 ] {} <Fatal> BaseDaemon: Checksum of the binary: 1EFCD06204779A2EAFBED96BAEF63211, integrity check passed.
2021.08.19 13:59:35.964010 [ 190 ] {} <Fatal> Application: Child process was terminated by signal 4.
```

### PR DESCRIPTION
**Pull request by rschu1ze**
This PR re-introduces #39629 which has been reverted (#40877).

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
For security and stability reasons, catboost models are no longer evaluated within the ClickHouse server. Instead, the evaluation is now done in the clickhouse-library-bridge, a separate process that loads the catboost library and communicates with the server process via HTTP.

#### Upgrade notes

Function `modelEvaluate()` function is no longer available. To evaluate catboost models, user can now use the new function `catboostEvaluate()`, documented [here](https://clickhouse.com/docs/en/sql-reference/functions/other-functions/#catboostevaluatepath_to_model-feature_1-feature_2--feature_n):

```
  SELECT
    FEAT_1, ..., FEAT_N, catboostEvaluate('/path/to/model.bin', FEAT_1, ..., FEAT_N)
  FROM data
  LIMIT 10
```
The syntax of function`catboostEvaluate()` is similar to the previous `modelEvaluate()`, but instead of specifying a model name which is mapped to a model path using an XML file, users now specify the model path directly.

Required configuration:
```
  <catboost_lib_path>/path/to/libcatboostmodel.so</catboost_lib_path>
```
Configuration parameter `catboost_lib_path` corresponds to the previous configuration parameter `catboost_dynamic_library_path` which is now ignored.

Fixes #27870

### CODE REVIEW

File: src/Interpreters/InterpreterSystemQuery.cpp [hunk 1]
```diff
@@ -374,19 +373,10 @@ BlockIO InterpreterSystemQuery::execute()
...
-            external_models_loader.reloadModel(query.target_model);
-            break;
-        }
         case Type::RELOAD_MODELS:
         {
             getContext()->checkAccess(AccessType::SYSTEM_RELOAD_MODEL);
-
-            auto & external_models_loader = system_context->getExternalModelsLoader();
-            external_models_loader.reloadAllTriedToLoad();
+            /// SYSTEM RELOAD MODEL(S) is no longer supported. For compat reasons, it is not completely removed but retained as no-op.
```
Comment (rschu1ze) [inline src/Interpreters/InterpreterSystemQuery.cpp:379]: Fix for RBAC issue.

Comment (rschu1ze) [reply src/Interpreters/InterpreterSystemQuery.cpp:379]: I spend quite some time today to verify locally that the issue found by Nikita in the cloud (aka. reason for revert #40877) no longer happens.

Overall, I think "normal" users would not have run into the issue anyway - 1. it requires granting the [*undocumented*](https://clickhouse.com/docs/en/sql-reference/statements/grant/#grant-select) `SYSTEM RELOAD MODELS` privilege to a user/role and 2. ... which is needed only for the slightly obscure catboost usecase. My guess is that Nikitas cloud machine configuration has some history and is pretty "wild".

(Just FYI for the record: Besides `SYSTEM RELOAD MODELS`, this PR also removes view `SYSTEM.MODELS`. In theory, there could be a similar problem for SELECT privileges on this view. In practice, there isn't because SELECT privileges can be [defined on non-existing tables](https://clickhouse.com/docs/en/operations/access-rights/#access-control-properties).)

To sum up, this PR is good to merge in my POV.

**Comment by UnamedRus** [comment]
> SYSTEM RELOAD MODEL(S) is no longer supported

That is really sad, as we know multiple companies which used this feature.

**Comment by rschu1ze** [comment]
The catboost feature itself is retained but in a way that `SYSTEM RELOAD MODELS` is no longer needed. In fact, due to a last-minute bug, `SYSTEM RELOAD MODELS` continues to exist but as a no-op (see https://github.com/ClickHouse/ClickHouse/pull/40897/commits/0183a370414a400573fd70d8f4d71a7a81a90670 for details)

**Comment by UnamedRus** [comment]
Yes, i understand that catboost models now works via http bridge like jdbc/odbc, but it's unclear for me for example, what will happen if we will replace model .bin file? 
Will bridge auto-reload model by itself?
There is another concern about performance penalty, but i guess it inevitable for now.

**Comment by rschu1ze** [comment]
Each call to `catboostEvaluate()` loads the model .bin freshly from disk (the path to the .bin file must now be specified in SQL). So updates are supported. The cost of reloading can be amortized by evaluating multiple rows at once. The maximum HTTP URL length however limits the number of rows to be evaluated at once, in my tests the threshold was around 50k rows (but that depends on the number of features).

Yes, HTTP communication with the library-bridge has a performance cost but that's inevitable ...

**Comment by kssenii** [comment]
> Each call to catboostEvaluate() loads the model .bin freshly from disk

btw why not reuse the loaded result and reload it only when explicitly said to do that? For example, library bridge does not load the library for each request and reloads it only when the library dictionary source is reloaded.

**Comment by rschu1ze** [comment]
It works as designed :)
To be serious, there were 3 reasons for reloading the model with each call: 1. My assumption was that catboost evaluation is a quite exotic feature and only used for experiments/demonstration, but that's obviously not true as per https://github.com/ClickHouse/ClickHouse/pull/40897#issuecomment-1237405340. My aim was to keep the logic after migration to library-bridge as simple as possible 2. The .bin files contain a bunch of integers as decision tree parameters and are not too big (in average). I worked only with two models, they were 0.8 MB and 4.8 MB in size. 3. The cost of loading the model is amortized by doing so only once per batch evaluation (e.g. 50k rows).

@kssenii Will change to the behavior you described (shouldn't be more than a few hours work). This will also resurrect `SYSTEM RELOAD MODELS`. (I thought about merging this PR and doing the fix separately but keeping it around for a bit longer doesn't matter too much)

**Comment by rschu1ze** [comment]
I restored `SYSTEM RELOAD MODEL(S)` and also system view `SYSTEM.MODELS`. There are still minor caveats where the new behavior is slightly different from the previous behavior (documented in [this commit msg](https://github.com/ClickHouse/ClickHouse/pull/40897/commits/484c541acd07a035a5972d42de9f6f482720b944)). But I think that should be okay.

**Comment by rschu1ze** [comment]
@kssenii This PR is done IMHO and the tests for the last run were also fine. Green light would be great. Thanks!

File: src/BridgeHelper/CatBoostLibraryBridgeHelper.h [hunk 2]
```diff
@@ -17,9 +18,15 @@ class CatBoostLibraryBridgeHelper : public LibraryBridgeHelper
...
 
     CatBoostLibraryBridgeHelper(ContextPtr context_, std::string_view library_path_, std::string_view model_path_);
+    CatBoostLibraryBridgeHelper(ContextPtr context_, std::string_view model_path_);
+    explicit CatBoostLibraryBridgeHelper(ContextPtr context_);
 
-    size_t getTreeCount();
+    ExternalModelInfos listModels();
+
+    void removeModel();
+    void removeAllModels();
```
Comment (kssenii) [inline src/BridgeHelper/CatBoostLibraryBridgeHelper.h:27]: this seems a little inconsistent that model_path can be an argument in bridge helpers constructor and at the same not be, e.g. some methods need to ensure that bridge helper was created with a certain constructor. May be rework it somehow to avoid such complication?

File: src/Interpreters/InterpreterSystemQuery.cpp [hunk 3]
```diff
@@ -373,10 +374,17 @@ BlockIO InterpreterSystemQuery::execute()
             break;
         }
         case Type::RELOAD_MODEL:
+        {
+            getContext()->checkAccess(AccessType::SYSTEM_RELOAD_MODEL);
+            auto bridge_helper = std::make_unique<CatBoostLibraryBridgeHelper>(getContext(), query.target_model);
+            bridge_helper->removeModel();
```
Comment (kssenii) [inline src/Interpreters/InterpreterSystemQuery.cpp:380]: why not actually reload and not just remove? I would expect that time for reloading the model lies on the reload model command instead of the next attempt to access it

Comment (rschu1ze) [reply src/Interpreters/InterpreterSystemQuery.cpp:380]: I agree in general (even if the reload costs are small because models are small)

The problem is that the model evaluation is not an atomic operation. It is actually two operations A and B with a dependency between them. This cannot be changed easily because of ClickHouse's function interface.

So we need to deal with a `SYSTEM RELOAD MODEL` call between A and B. The simplest approach is the one implemented: Simply unload the model, and let B check if the model is still in memory. If A finds a model unloaded, load it.

If `SYSTEM RELOAD MODEL` actually *reloads* the model, then B must somehow find that out and fail. There are multiple approaches. I'll mention just two
- A locks the model on the bridge side until B starts. This avoids reloads in between. Obviously there is a risk of livelocks here ...
- More sophisticated: Generated for each `catboostEvaluate()` call a random "request id" on the server side, send it to the bridge in A and store it in a queue. A reload in between clears the queue. The same request id is send to the bridge in B. If it is not found in the queue, fail. The length of the queue limits the number of parallel requests which is why I did not like this option too much. It's also harder to maintain and test.

TLDL: I think the current behavior is not a deal breaker for such quite exotic functionality. If it's okay, I'll ask Nikolai what he thinks (he was the original author) and if needed implement an actual load in a separate PR.

**Review by kssenii — APPROVED** [review]

File: src/Interpreters/InterpreterSystemQuery.cpp (hunk 3 above)
Comment (rschu1ze) [reply src/Interpreters/InterpreterSystemQuery.cpp:380]: For completeness, I talked briefly to Nikolai yesterday and he's fine with the lazy semantics.
