### PR TITLE
Fix Digest of local metadata (X) is not equal to in-memory digest (Y) error in Replicated database

### LINKED ISSUE #64936: Replicated database engine: Assert `checkDigestValid`
https://s3.amazonaws.com/clickhouse-test-reports/64312/553fcb5e0618858cfa7659522208be49320b0e48/stress_test__debug_.html

```
2024.06.04 23:25:10.678261 [ 4043 ] {} <Debug> DatabaseReplicated (test_5): Calculated metadata digest of 0 tables: 0
2024.06.04 23:25:10.719797 [ 4072 ] {} <Test> DatabaseReplicated (test_5): Current in-memory metadata digest: 0
2024.06.04 23:25:10.747811 [ 4072 ] {} <Test> DatabaseReplicated (test_5): Current in-memory metadata digest: 0
2024.06.04 23:26:50.153936 [ 4111 ] {8ab65d22-8ead-4cf8-9419-60ea44f6cf59} <Test> DatabaseReplicated (test_5): Current in-memory metadata digest: 13373415254152722228
2024.06.04 23:35:53.334547 [ 6459 ] {65c52219-12c8-4ed9-9f31-05c06ea59f75} <Test> DatabaseReplicated (test_5): Current in-memory metadata digest: 12292136910814453539
2024.06.04 23:40:15.214524 [ 9263 ] {25017dbb-6a2a-4eb3-b7bb-a54f4b114aae} <Test> DatabaseReplicated (test_5): Current in-memory metadata digest: 1075451882521992441
2024.06.04 23:40:15.245034 [ 9263 ] {25017dbb-6a2a-4eb3-b7bb-a54f4b114aae} <Error> DatabaseReplicated (test_5): Digest of local metadata (6819634925577158989) is not equal to in-memory digest (1075451882521992441)


245013:2024.06.05 00:10:11.830290 [ 9356 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
245077:2024.06.05 00:10:11.873529 [ 9356 ] {} <Fatal> BaseDaemon: (version 24.6.1.2779, build id: D5D36F5D042A18FD1AC95C01D8059E23B9CA0318, git hash: c4ecf40f205c5b68584a1049a31a4d66a3faf059) (from thread 9263) Received signal 6
245078:2024.06.05 00:10:11.907070 [ 9356 ] {} <Fatal> BaseDaemon: Signal description: Aborted
245079:2024.06.05 00:10:11.909392 [ 9356 ] {} <Fatal> BaseDaemon: 
245081:2024.06.05 00:10:11.910385 [ 9356 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000012d4af0a 0x0000000012d4ae00 0x000000001316f251 0x00007f57820c8520 0x00007f578211c9fd 0x00007f57820c8476 0x00007f57820ae7f3 0x00007f57820ae71b 0x00007f57820bfe96 0x000000001a109cd1 0x000000001a0b5833 0x000000001b02fa91 0x000000001b0293b6 0x000000001b031bd6 0x000000001bb61777 0x000000001bb639fb 0x000000001a62f3da 0x000000001a62e13d 0x000000001a12f6ef 0x000000001a0f7dd3 0x000000001b028f69 0x000000001b031bd6 0x000000001bb61777 0x000000001bb5bc6a 0x000000001d3e9d99 0x000000001d3ff07f 0x00000000227c75d9 0x00000000227c7e28 0x000000002299ec94 0x000000002299ba3a 0x000000002299a77e 0x00007f578211aac3 0x00007f57821ac850
245082:2024.06.05 00:10:11.910920 [ 9356 ] {} <Fatal> BaseDaemon: ########################################
245084:2024.06.05 00:10:11.912963 [ 9356 ] {} <Fatal> BaseDaemon: (version 24.6.1.2779, build id: D5D36F5D042A18FD1AC95C01D8059E23B9CA0318, git hash: c4ecf40f205c5b68584a1049a31a4d66a3faf059) (from thread 9263) (query_id: 25017dbb-6a2a-4eb3-b7bb-a54f4b114aae) (query: /* ddl_entry=query-0000000039 */ CREATE TABLE test_5.data UUID 'a69d3eed-7e99-4d89-9b44-26d14852b462' (`key` Int32) ENGINE = Memory) Received signal Aborted (6)
245093:2024.06.05 00:10:11.926485 [ 9356 ] {} <Fatal> BaseDaemon: 
245096:2024.06.05 00:10:11.933049 [ 9356 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000012d4af0a 0x0000000012d4ae00 0x000000001316f251 0x00007f57820c8520 0x00007f578211c9fd 0x00007f57820c8476 0x00007f57820ae7f3 0x00007f57820ae71b 0x00007f57820bfe96 0x000000001a109cd1 0x000000001a0b5833 0x000000001b02fa91 0x000000001b0293b6 0x000000001b031bd6 0x000000001bb61777 0x000000001bb639fb 0x000000001a62f3da 0x000000001a62e13d 0x000000001a12f6ef 0x000000001a0f7dd3 0x000000001b028f69 0x000000001b031bd6 0x000000001bb61777 0x000000001bb5bc6a 0x000000001d3e9d99 0x000000001d3ff07f 0x00000000227c75d9 0x00000000227c7e28 0x000000002299ec94 0x000000002299ba3a 0x000000002299a77e 0x00007f578211aac3 0x00007f57821ac850
245385:2024.06.05 00:10:12.203551 [ 9356 ] {} <Fatal> BaseDaemon: 0. /build/src/Common/StackTrace.cpp:349: StackTrace::tryCapture() @ 0x0000000012d4af0a
246479:2024.06.05 00:10:12.740185 [ 9356 ] {} <Fatal> BaseDaemon: 1. /build/src/Common/StackTrace.cpp:323: StackTrace::StackTrace(ucontext_t const&) @ 0x0000000012d4ae00
248361:2024.06.05 00:10:13.315403 [ 9356 ] {} <Fatal> BaseDaemon: 2. /build/src/Daemon/BaseDaemon.cpp:157: signalHandler(int, siginfo_t*, void*) @ 0x000000001316f251
248408:2024.06.05 00:10:13.351738 [ 9356 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007f57820c8520
248422:2024.06.05 00:10:13.364106 [ 9356 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f578211c9fd
248430:2024.06.05 00:10:13.375042 [ 9356 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f57820c8476
248435:2024.06.05 00:10:13.393714 [ 9356 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f57820ae7f3
248444:2024.06.05 00:10:13.404921 [ 9356 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007f57820ae71b
248461:2024.06.05 00:10:13.416617 [ 9356 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00007f57820bfe96
249190:2024.06.05 00:10:14.425374 [ 9356 ] {} <Fatal> BaseDaemon: 9. /build/src/Databases/DatabaseReplicated.cpp:1498: DB::DatabaseReplicated::commitCreateTable(DB::ASTCreateQuery const&, std::shared_ptr<DB::IStorage> const&, String const&, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001a109cd1
250344:2024.06.05 00:10:15.620759 [ 9356 ] {} <Fatal> BaseDaemon: 10. /build/src/Databases/DatabaseOnDisk.cpp:257: DB::DatabaseOnDisk::createTable(std::shared_ptr<DB::Context const>, String const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::IAST> const&) @ 0x000000001a0b5833
250868:2024.06.05 00:10:16.725221 [ 9356 ] {} <Fatal> BaseDaemon: 11. /build/src/Interpreters/InterpreterCreateQuery.cpp:1540: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x000000001b02fa91
252138:2024.06.05 00:10:18.100674 [ 9356 ] {} <Fatal> BaseDaemon: 12. /build/src/Interpreters/InterpreterCreateQuery.cpp:1312: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000001b0293b6
252441:2024.06.05 00:10:19.120424 [ 9356 ] {} <Fatal> BaseDaemon: 13. /build/src/Interpreters/InterpreterCreateQuery.cpp:0: DB::InterpreterCreateQuery::execute() @ 0x000000001b031bd6
252716:2024.06.05 00:10:20.061706 [ 9356 ] {} <Fatal> BaseDaemon: 14. /build/src/Interpreters/executeQuery.cpp:1210: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001bb61777
252735:2024.06.05 00:10:20.455301 [ 9356 ] {} <Fatal> BaseDaemon: 15. /build/src/Interpreters/executeQuery.cpp:1508: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000001bb639fb
252737:2024.06.05 00:10:20.662081 [ 9356 ] {} <Fatal> BaseDaemon: 16. /build/src/Interpreters/DDLWorker.cpp:497: DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x000000001a62f3da
252755:2024.06.05 00:10:20.868619 [ 9356 ] {} <Fatal> BaseDaemon: 17. /build/src/Interpreters/DDLWorker.cpp:661: DB::DDLWorker::processTask(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x000000001a62e13d
252773:2024.06.05 00:10:21.046923 [ 9356 ] {} <Fatal> BaseDaemon: 18. /build/src/Databases/DatabaseReplicatedWorker.cpp:313: DB::DatabaseReplicatedDDLWorker::tryEnqueueAndExecuteEntry(DB::DDLLogEntry&, std::shared_ptr<DB::Context const>) @ 0x000000001a12f6ef
252826:2024.06.05 00:10:21.468634 [ 9356 ] {} <Fatal> BaseDaemon: 19. /build/src/Databases/DatabaseReplicated.cpp:831: DB::DatabaseReplicated::tryEnqueueReplicatedDDL(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::QueryFlags) @ 0x000000001a0f7dd3
252963:2024.06.05 00:10:22.083370 [ 9356 ] {} <Fatal> BaseDaemon: 20. /build/src/Interpreters/InterpreterCreateQuery.cpp:1293: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000001b028f69
253179:2024.06.05 00:10:22.795872 [ 9356 ] {} <Fatal> BaseDaemon: 21. /build/src/Interpreters/InterpreterCreateQuery.cpp:0: DB::InterpreterCreateQuery::execute() @ 0x000000001b031bd6
253360:2024.06.05 00:10:23.267882 [ 9356 ] {} <Fatal> BaseDaemon: 22. /build/src/Interpreters/executeQuery.cpp:1210: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001bb61777
253387:2024.06.05 00:10:23.672968 [ 9356 ] {} <Fatal> BaseDaemon: 23. /build/src/Interpreters/executeQuery.cpp:1376: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001bb5bc6a
253419:2024.06.05 00:10:24.255583 [ 9356 ] {} <Fatal> BaseDaemon: 24. /build/src/Server/TCPHandler.cpp:523: DB::TCPHandler::runImpl() @ 0x000000001d3e9d99
253422:2024.06.05 00:10:24.675241 [ 9356 ] {} <Fatal> BaseDaemon: 25. /build/src/Server/TCPHandler.cpp:2342: DB::TCPHandler::run() @ 0x000000001d3ff07f
253423:2024.06.05 00:10:24.691140 [ 9356 ] {} <Fatal> BaseDaemon: 26. /build/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x00000000227c75d9
253424:2024.06.05 00:10:24.716858 [ 9356 ] {} <Fatal> BaseDaemon: 27. /build/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000227c7e28
253425:2024.06.05 00:10:24.744386 [ 9356 ] {} <Fatal> BaseDaemon: 28. /build/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x000000002299ec94
253426:2024.06.05 00:10:24.770961 [ 9356 ] {} <Fatal> BaseDaemon: 29. /build/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000002299ba3a
253427:2024.06.05 00:10:24.795973 [ 9356 ] {} <Fatal> BaseDaemon: 30. /build/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000002299a77e
253428:2024.06.05 00:10:24.796227 [ 9356 ] {} <Fatal> BaseDaemon: 31. ? @ 0x00007f578211aac3
253429:2024.06.05 00:10:24.796461 [ 9356 ] {} <Fatal> BaseDaemon: 32. ? @ 0x00007f57821ac850
253430:2024.06.05 00:10:24.796633 [ 9356 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
254366:2024.06.05 00:10:32.097249 [ 9356 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.

```

Probably related to materialized views with inner table:
```
2024.06.04 23:25:20.875654 [ 4059 ] {fecd0195-7f2b-44d9-9ba1-95a70a492324} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000002 */ CREATE TABLE test_5.tab UUID '1ccb38e7-67d8-4c68-b84e-ca51b6b4394a' (`A` Int64) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0, index_granularity = 869, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = true, max_file_name_length = 128, min_bytes_for_full_part_storage = 536870912, compact_parts_max_bytes_to_buffer = 3943609, compact_parts_max_granules_to_buffer = 1, compact_parts_merge_max_bytes_to_prefetch_part = 14609175, merge_max_block_size = 8816, old_parts_lifetime = 480., prefer_fetch_merged_part_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1000000, vertical_merge_algorithm_min_columns_to_activate = 100, min_merge_bytes_to_use_direct_io = 1, index_granularity_bytes = 14518409, concurrent_part_removal_threshold = 100, allow_vertical_merges_from_compact_to_wide_parts = false, cache_populated_by_fetch = false, marks_compress_block_size = 38191, primary_key_compress_block_size = 34584
2024.06.04 23:25:23.315864 [ 4059 ] {bb1fce2e-22d8-4b6b-9278-232f22d20399} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000003 */ DROP TABLE IF EXISTS test_5.tab SYNC
2024.06.04 23:25:40.758192 [ 4110 ] {f172871b-8043-468a-8fd8-dd7de80e256a} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000004 */ CREATE TABLE test_5.defaults UUID '920fa8ea-5892-4c84-884c-3bc96cd5f973' (`n` Int32, `s` String) ENGINE = Memory
2024.06.04 23:26:27.973931 [ 4367 ] {6111b6e8-a087-4266-9932-2a942d9289b3} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000005 */ CREATE TABLE test_5.file_log UUID '50a123d9-6ebc-432d-998d-723a813acc81' (`k` UInt8, `v` UInt8) ENGINE = FileLog('/var/lib/clickhouse/user_files/02025_storage_filelog_virtual_col_test_5/', 'CSV')
2024.06.04 23:26:50.172017 [ 4111 ] {8ab65d22-8ead-4cf8-9419-60ea44f6cf59} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000006 */ CREATE TABLE test_5.codecTest UUID '76a7213d-344e-41fa-a773-d0e812e80c0a' (`key` UInt64, `ref_valueU64` UInt64, `ref_valueU32` UInt32, `ref_valueU16` UInt16, `ref_valueU8` UInt8, `ref_valueI64` Int64, `ref_valueI32` Int32, `ref_valueI16` Int16, `ref_valueI8` Int8, `ref_valueDT` DateTime, `ref_valueD` Date, `valueU64` UInt64 CODEC(DoubleDelta), `valueU32` UInt32 CODEC(DoubleDelta), `valueU16` UInt16 CODEC(DoubleDelta), `valueU8` UInt8 CODEC(DoubleDelta), `valueI64` Int64 CODEC(DoubleDelta), `valueI32` Int32 CODEC(DoubleDelta), `valueI16` Int16 CODEC(DoubleDelta), `valueI8` Int8 CODEC(DoubleDelta), `valueDT` DateTime CODEC(DoubleDelta), `valueD` Date CODEC(DoubleDelta)) ENGINE = MergeTree ORDER BY key SETTINGS min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization = 1
2024.06.04 23:29:08.730976 [ 4367 ] {041e5255-34e2-404c-9796-95f441caebb8} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000008 */ CREATE TABLE test_5.`02898_parallel_replicas_final` UUID 'a0264870-dc94-47d3-94c1-1af9a8a61c32' (`x` String, `y` Int32) ENGINE = ReplacingMergeTree ORDER BY cityHash64(x) SETTINGS index_granularity = 22293, min_bytes_for_wide_part = 1073741824, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = true, max_file_name_length = 128, min_bytes_for_full_part_storage = 251958580, compact_parts_max_bytes_to_buffer = 28837517, compact_parts_max_granules_to_buffer = 203, compact_parts_merge_max_bytes_to_prefetch_part = 25591691, merge_max_block_size = 19874, old_parts_lifetime = 62., prefer_fetch_merged_part_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1000000, vertical_merge_algorithm_min_columns_to_activate = 100, min_merge_bytes_to_use_direct_io = 1473556458, index_granularity_bytes = 12622430, concurrent_part_removal_threshold = 88, allow_vertical_merges_from_compact_to_wide_parts = false, cache_populated_by_fetch = false, marks_compress_block_size = 10220, primary_key_compress_block_size = 98646
2024.06.04 23:29:46.180135 [ 5078 ] {d4d35c93-da19-438c-bc65-e59bf752bf5d} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000009 */ CREATE TABLE test_5.data UUID 'a0ee68ac-8b68-4288-8793-d7eed1694dca' (`key` UInt64 CODEC(NONE)) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_bytes_for_wide_part = 1000000000.
2024.06.04 23:31:55.847309 [ 6533 ] {083fb680-adc3-47c9-8a12-6517c95046e3} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000010 */ CREATE TABLE test_5.temp UUID '2639601c-40cc-419b-b36c-44e29e9f973e' (`x` Decimal(38, 2), `y` Nullable(Decimal(38, 2))) ENGINE = Memory
2024.06.04 23:32:01.672491 [ 6533 ] {a9e83fe3-f867-4aad-bd56-fee2ce156579} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000011 */ TRUNCATE TABLE IF EXISTS test_5.temp
2024.06.04 23:32:19.371561 [ 6519 ] {47b99998-5f0b-4a70-80b8-fb6596e203f4} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000012 */ CREATE TABLE test_5.src UUID '03a6f151-2b97-42b6-afd2-afefed9a0ffb' (`id` UInt64, `value` Int32) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 56382, min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = true, max_file_name_length = 128, min_bytes_for_full_part_storage = 247417554, compact_parts_max_bytes_to_buffer = 531224596, compact_parts_max_granules_to_buffer = 203, compact_parts_merge_max_bytes_to_prefetch_part = 57503, merge_max_block_size = 10655, old_parts_lifetime = 480., prefer_fetch_merged_part_size_threshold = 1622104571, vertical_merge_algorithm_min_rows_to_activate = 633437, vertical_merge_algorithm_min_columns_to_activate = 1, min_merge_bytes_to_use_direct_io = 9566344647, index_granularity_bytes = 18200186, concurrent_part_removal_threshold = 100, allow_vertical_merges_from_compact_to_wide_parts = false, cache_populated_by_fetch = false, marks_compress_block_size = 22672, primary_key_compress_block_size = 52979 AS SELECT number AS id, toInt32(1) AS value FROM numbers(1)
2024.06.04 23:32:20.409130 [ 6519 ] {95e56f31-da76-4502-9760-7d81b28d38a8} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000013 */ CREATE TABLE test_5.dst UUID '1a19c9e5-5f19-4ac2-8357-c0e02de3e8b5' (`id` UInt64, `delta` Int64) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 56382, min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = true, max_file_name_length = 128, min_bytes_for_full_part_storage = 247417554, compact_parts_max_bytes_to_buffer = 531224596, compact_parts_max_granules_to_buffer = 203, compact_parts_merge_max_bytes_to_prefetch_part = 57503, merge_max_block_size = 10655, old_parts_lifetime = 480., prefer_fetch_merged_part_size_threshold = 1622104571, vertical_merge_algorithm_min_rows_to_activate = 633437, vertical_merge_algorithm_min_columns_to_activate = 1, min_merge_bytes_to_use_direct_io = 9566344647, index_granularity_bytes = 18200186, concurrent_part_removal_threshold = 100, allow_vertical_merges_from_compact_to_wide_parts = false, cache_populated_by_fetch = false, marks_compress_block_size = 22672, primary_key_compress_block_size = 52979
2024.06.04 23:32:21.506843 [ 6519 ] {75f31cd6-e272-4e08-aa19-6259a5a68ef9} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000014 */ CREATE MATERIALIZED VIEW test_5.src2dst_true UUID '5b34714d-1a7d-4310-b0f9-880188a25059' TO test_5.dst (`id` UInt64, `delta` Int64) AS SELECT id, src.value - deltas_sum AS delta FROM test_5.src LEFT JOIN (SELECT id, sum(delta) AS deltas_sum FROM test_5.dst WHERE id IN (SELECT id FROM test_5.src WHERE NOT sleepEachRow(0.001)) GROUP BY id) AS _a USING (id)
2024.06.04 23:34:53.286223 [ 6668 ] {7d4ce83f-f501-4b28-a7ad-354ecd90bb66} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000015 */ CREATE TABLE test_5.file UUID '7fff68dd-2d07-4604-b393-0f335361c611' (`x` UInt64) ENGINE = File(JSONEachRow, 'test_5/data.JSONEachRow.lz4')
2024.06.04 23:34:57.298857 [ 6663 ] {781cb081-c9ff-4dce-9f1c-1a3391b48127} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000016 */ TRUNCATE TABLE test_5.file SYNC
2024.06.04 23:35:09.983435 [ 6668 ] {c5bcefb5-59bd-4b7e-9710-bcdd34080446} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000017 */ TRUNCATE TABLE test_5.file SYNC
2024.06.04 23:35:23.435520 [ 7988 ] {d59a857f-e0bc-4679-be8f-d0f6e5b98aea} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000018 */ TRUNCATE TABLE test_5.file SYNC
2024.06.04 23:35:38.082978 [ 6459 ] {dabe191a-6c0d-4722-9eaa-e11b3f7e2588} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000019 */ TRUNCATE TABLE test_5.file SYNC
2024.06.04 23:35:53.478844 [ 6459 ] {65c52219-12c8-4ed9-9f31-05c06ea59f75} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000020 */ DROP TABLE test_5.file SYNC
2024.06.04 23:36:01.888313 [ 6600 ] {321c149d-b2aa-4ec6-a1e2-7620be13e3f8} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000021 */ CREATE TABLE test_5.ontime UUID '5c480ce9-eab8-4497-8480-8e6bcfbe1938' (`FlightDate` Date, `Carrier` String, `FlightNum` String) ENGINE = Memory
2024.06.04 23:36:03.572101 [ 6600 ] {fdc92d0d-6898-48bc-b8b0-6a0f6fcf0b2a} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000022 */ TRUNCATE TABLE test_5.ontime
2024.06.04 23:36:09.713640 [ 6459 ] {5c019ca3-8741-48f4-8854-90e3edbebbc8} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000023 */ CREATE TABLE test_5.github_events UUID '103df86a-6007-44ce-945f-9aeac9b8922b' (`file_time` DateTime, `event_type` Enum8('CommitCommentEvent' = 1, 'CreateEvent' = 2, 'DeleteEvent' = 3, 'ForkEvent' = 4, 'GollumEvent' = 5, 'IssueCommentEvent' = 6, 'IssuesEvent' = 7, 'MemberEvent' = 8, 'PublicEvent' = 9, 'PullRequestEvent' = 10, 'PullRequestReviewCommentEvent' = 11, 'PushEvent' = 12, 'ReleaseEvent' = 13, 'SponsorshipEvent' = 14, 'WatchEvent' = 15, 'GistEvent' = 16, 'FollowEvent' = 17, 'DownloadEvent' = 18, 'PullRequestReviewEvent' = 19, 'ForkApplyEvent' = 20, 'Event' = 21, 'TeamAddEvent' = 22), `actor_login` LowCardinality(String), `repo_name` LowCardinality(String), `created_at` DateTime, `updated_at` DateTime, `action` Enum8('none' = 0, 'created' = 1, 'added' = 2, 'edited' = 3, 'deleted' = 4, 'opened' = 5, 'closed' = 6, 'reopened' = 7, 'assigned' = 8, 'unassigned' = 9, 'labeled' = 10, 'unlabeled' = 11, 'review_requested' = 12, 'review_request_removed' = 13, 'synchronize' = 14, 'started' = 15, 'published' = 16, 'update' = 17, 'create' = 18, 'fork' = 19, 'merged' = 20), `comment_id` UInt64, `body` String, `path` String, `position` Int32, `line` Int32, `ref` LowCardinality(String), `ref_type` Enum8('none' = 0, 'branch' = 1, 'tag' = 2, 'repository' = 3, 'unknown' = 4), `creator_user_login` LowCardinality(String), `number` UInt32, `title` String, `labels` Array(LowCardinality(String)), `state` Enum8('none' = 0, 'open' = 1, 'closed' = 2), `locked` UInt8, `assignee` LowCardinality(String), `assignees` Array(LowCardinality(String)), `comments` UInt32, `author_association` Enum8('NONE' = 0, 'CONTRIBUTOR' = 1, 'OWNER' = 2, 'COLLABORATOR' = 3, 'MEMBER' = 4, 'MANNEQUIN' = 5), `closed_at` DateTime, `merged_at` DateTime, `merge_commit_sha` String, `requested_reviewers` Array(LowCardinality(String)), `requested_teams` Array(LowCardinality(String)), `head_ref` LowCardinality(String), `head_sha` String, `base_ref` LowCardinality(String), `base_sha` String, `merged` UInt8, `mergeable` UInt8, `rebaseable` UInt8, `mergeable_state` Enum8('unknown' = 0, 'dirty' = 1, 'clean' = 2, 'unstable' = 3, 'draft' = 4), `merged_by` LowCardinality(String), `review_comments` UInt32, `maintainer_can_modify` UInt8, `commits` UInt32, `additions` UInt32, `deletions` UInt32, `changed_files` UInt32, `diff_hunk` String, `original_position` UInt32, `commit_id` String, `original_commit_id` String, `push_size` UInt32, `push_distinct_size` UInt32, `member_login` LowCardinality(String), `release_tag_name` String, `release_name` String, `review_state` Enum8('none' = 0, 'approved' = 1, 'changes_requested' = 2, 'commented' = 3, 'dismissed' = 4, 'pending' = 5)) ENGINE = MergeTree ORDER BY (event_type, repo_name, created_at) SETTINGS index_granularity = 43020, min_bytes_for_wide_part = 1073741824, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = true, max_file_name_length = 56, min_bytes_for_full_part_storage = 505323136, compact_parts_max_bytes_to_buffer = 201558404, compact_parts_max_granules_to_buffer = 1, compact_parts_merge_max_bytes_to_prefetch_part = 16940640, merge_max_block_size = 738, old_parts_lifetime = 350., prefer_fetch_merged_part_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1, vertical_merge_algorithm_min_columns_to_activate = 100, min_merge_bytes_to_use_direct_io = 1, index_granularity_bytes = 31143499, concurrent_part_removal_threshold = 69, allow_vertical_merges_from_compact_to_wide_parts = true, cache_populated_by_fetch = true, marks_compress_block_size = 96390, primary_key_compress_block_size = 30034
2024.06.04 23:37:30.568049 [ 6519 ] {49760fcf-818f-4f51-80ec-31b99cf48f71} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000024 */ CREATE TABLE test_5.t UUID 'a671c635-ddbf-42ca-90ad-92e85a3d3550' (`a` UInt32) ENGINE = MergeTree PARTITION BY a % 16 ORDER BY tuple()
2024.06.04 23:37:52.397790 [ 6519 ] {3a402bec-8343-45b3-a170-1bf87e910fdb} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000025 */ DROP TABLE IF EXISTS test_5.data SYNC
2024.06.04 23:37:58.350036 [ 6519 ] {3b67c688-6c9a-47df-858c-b1215550d470} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000027 */ CREATE TABLE test_5.main UUID 'f0951e5f-de68-49c0-bfcb-f7d4355c16ba' (`id` String, `color` String, `section` String, `description` String) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 64843, min_bytes_for_wide_part = 1073741824, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = true, max_file_name_length = 70, min_bytes_for_full_part_storage = 536870912, compact_parts_max_bytes_to_buffer = 98146680, compact_parts_max_granules_to_buffer = 1, compact_parts_merge_max_bytes_to_prefetch_part = 2621454, merge_max_block_size = 5794, old_parts_lifetime = 10., prefer_fetch_merged_part_size_threshold = 1, vertical_merge_algorithm_min_rows_to_activate = 1000000, vertical_merge_algorithm_min_columns_to_activate = 100, min_merge_bytes_to_use_direct_io = 3062476998, index_granularity_bytes = 18697989, concurrent_part_removal_threshold = 46, allow_vertical_merges_from_compact_to_wide_parts = true, cache_populated_by_fetch = false, marks_compress_block_size = 41290, primary_key_compress_block_size = 67004
2024.06.04 23:37:58.914966 [ 6519 ] {f7fae755-83ee-49e5-953b-58c710248590} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000028 */ CREATE TABLE test_5.destination_join UUID '62d1ff8d-2522-4eda-9883-7c2848975147' (`key` String, `id` String, `color` String, `section` String, `description` String) ENGINE = Join(ANY, LEFT, key)
2024.06.04 23:37:59.302078 [ 6519 ] {11160dcb-7edb-4323-bf4f-d950ee660196} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000029 */ CREATE TABLE test_5.destination_set UUID 'c5cc9c0c-dc68-48fd-b430-38c53cb08af9' (`key` String) ENGINE = Set
2024.06.04 23:38:00.004577 [ 6519 ] {acb58145-0147-4c27-af06-df45f9561b28} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000030 */ CREATE MATERIALIZED VIEW test_5.mv_to_join UUID 'b8d4cd9b-58a8-405f-aa99-1b072c05aabb' TO test_5.destination_join (`key` String, `id` String, `color` String, `section` String, `description` String) AS SELECT concat(id, '_', color) AS key, * FROM test_5.main
2024.06.04 23:38:00.628741 [ 6519 ] {8df3a22f-6773-426b-8836-d2ea280cc0c5} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000031 */ CREATE MATERIALIZED VIEW test_5.mv_to_set UUID '8fb3692f-5701-47d5-bda3-6abc272e0233' TO test_5.destination_set (`key` String) AS SELECT key FROM test_5.destination_join
2024.06.04 23:38:45.886717 [ 8572 ] {38772049-c5d1-4976-acdb-dbadee889f59} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000033 */ CREATE MATERIALIZED VIEW test_5.mv UUID '8b58a067-f545-40ce-b12d-3a5612622b1e' TO INNER UUID 'fa2b1b10-a199-4a27-be99-3d61cd75dc08' (`timestamp` DateTime, `c12` Nullable(String)) ENGINE = MergeTree ORDER BY timestamp SETTINGS index_granularity = 17313, min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization = 0.7701940536499023, replace_long_file_name_to_hash = false, max_file_name_length = 0, min_bytes_for_full_part_storage = 185181515, compact_parts_max_bytes_to_buffer = 128414128, compact_parts_max_granules_to_buffer = 22, compact_parts_merge_max_bytes_to_prefetch_part = 9979205, merge_max_block_size = 7749, old_parts_lifetime = 10., prefer_fetch_merged_part_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1, vertical_merge_algorithm_min_columns_to_activate = 100, min_merge_bytes_to_use_direct_io = 10737418240, index_granularity_bytes = 15990087, concurrent_part_removal_threshold = 0, allow_vertical_merges_from_compact_to_wide_parts = true, cache_populated_by_fetch = false, marks_compress_block_size = 95225, primary_key_compress_block_size = 87154 AS SELECT Timestamp AS timestamp, concat(c1, c2) AS c12 FROM test_5.src
2024.06.04 23:40:14.546160 [ 9263 ] {44f690eb-8d63-4d37-8a86-ef9415222628} <Debug> DDLWorker(test_5): Executed query: /* ddl_entry=query-0000000038 */ DROP TABLE IF EXISTS test_5.data SYNC

```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The problem that this check fails in debug builds (on CI) is because
the digest is checked before committing the changes to coordinator,
while digest assume that it should be committed already.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/64936

### CODE REVIEW

File: src/Databases/DatabaseReplicated.cpp [hunk 1]
```diff
@@ -1669,7 +1696,7 @@ void DatabaseReplicated::dropTable(ContextPtr local_context, const String & tabl
     DatabaseAtomic::dropTableImpl(local_context, table_name, sync);
     tables_metadata_digest = new_digest;
 
-    assert(checkDigestValid(local_context));
+    assertDigestInTransactionOrInline(local_context, txn);
```
Comment (tavplubix) [inline src/Databases/DatabaseReplicated.cpp:1699]: Looks like we need to add the finalized before calling the DatabaseAtomic method (same for other methods)

**Review by tavplubix — COMMENTED** [review]
LGTM

**Comment by azat** [comment]
>[Integration tests (tsan, 1/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76622&sha=c94d471a38b9b2e2b30d296070eff5d5c2a5b6db&name_0=PR&name_1=Integration%20tests%20%28tsan%2C%201%2F6%29) — fail: 2, passed: 522

- [test_quorum_inserts](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76622&sha=c94d471a38b9b2e2b30d296070eff5d5c2a5b6db&name_0=PR&name_1=Integration+tests+%28tsan%2C+1%2F6%29&name_2=test_quorum_inserts%2Ftest.py%3A%3Atest_insert_quorum_with_move_partition%5BFalse%5D) - https://github.com/ClickHouse/ClickHouse/issues/67604

>[Stateless tests (debug, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76622&sha=c94d471a38b9b2e2b30d296070eff5d5c2a5b6db&name_0=PR&name_1=Stateless%20tests%20%28debug%2C%20s3%20storage%29) — fail: 1, passed: 7390, skipped: 325

- [03367_bfloat16_tuple_final](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76622&sha=c94d471a38b9b2e2b30d296070eff5d5c2a5b6db&name_0=PR&name_1=Stateless+tests+%28debug%2C+s3+storage%29&name_2=03367_bfloat16_tuple_final) - https://github.com/ClickHouse/ClickHouse/issues/77087

**Review by tavplubix — APPROVED** [review]
