### PR TITLE
Fix tracing of profile events

### LINKED ISSUE #44037: Segmentation fault while sending trace_type = 'ProfileEvent' to trace log
https://s3.amazonaws.com/clickhouse-test-reports/43987/3725cf4aa7a9aa022b11d08b2f8e4f7f0dd70283/stress_test__ubsan_/gdb.log

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #44037

### CODE REVIEW

File: src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp [hunk 1]
```diff
@@ -17,7 +17,10 @@ void WriteBufferFromFileDescriptorDiscardOnFailure::nextImpl()
 
         if ((-1 == res || 0 == res) && errno != EINTR)
         {
-            ProfileEvents::increment(ProfileEvents::CannotWriteToWriteBufferDiscard);
+            /// Never send this profile event to trace log because it may cause another
+            /// write into the same fd and likely will trigger the same error
```
Comment (kssenii) [inline src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:21]: why fd can be the same when sending profile event?

Comment (CurtizJ) [reply src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:21]: Because traces are always sent to one [pipe](https://github.com/ClickHouse/ClickHouse/blob/44fde45aa4aca792a15903e39465220259de0994/src/Common/TraceSender.cpp#L45).

Comment (kssenii) [reply src/IO/WriteBufferFromFileDescriptorDiscardOnFailure.cpp:21]: Ok, I thought "the same" is about the fd in this particular file a few lines above, which is very strange. May be just a comment is a bit unclear.

**Review by kssenii — APPROVED** [review]

**Comment by CurtizJ** [comment]
Stress test: #44081.
