### PR TITLE
Kafka work with formats based on PeekableReadBuffer and other improvements

### LINKED ISSUE #11216: Kafka premature flush when reaching end of partition
When a consumer gets to the end of topic flush happens w/o respect of `stream_flush_interval_ms` (that can lead to more frequent flushes of smaller blocks).

Discovered during testing of https://github.com/ClickHouse/ClickHouse/pull/11149

### LINKED ISSUE #11218: Kafka with num_consumers > available partitions in topic = performance degradation
Consuming speed of topic with single partition:
num_consumers = 1: 262144 rows / sec. 
num_consumers = 2: 43018 rows / sec.  (6 times slower!)

It's a misconfiguration actually, but it seems possible to avoid that.

### LINKED ISSUE #11514: 20.5 Kafka + JSONAsString = assert fail in PeekableReadBuffer::checkStateCorrect
```
2020.06.08 16:53:02.113533 [ 9 ] {} <Trace> BaseDaemon: Received signal 11
2020.06.08 16:53:02.113791 [ 75 ] {} <Fatal> BaseDaemon: ########################################
2020.06.08 16:53:02.113923 [ 75 ] {} <Fatal> BaseDaemon: (version 20.5.1.1) (from thread 73) (query_id: 11a4a97a-2c5a-4eb4-ad0b-4cbb362ae30e) Received signal Segmentation fault (11).
2020.06.08 16:53:02.114044 [ 75 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2020.06.08 16:53:02.114120 [ 75 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f658efed8f0 0x7f658efdd39a 0x7f658efdd412 0x157a5608 0x1d0b8566 0x1d0b902c 0x157ac74b 0x157d0f7b 0x1d0b4921 0x1d045f6f 0x1cf4e657 0x1cace454 0x1cacd3fd 0x1bb8fcad 0x1d217e01 0x1cf4e657 0x1d217ab3 0x1cf9f54c 0x1cf9f4c0 0x1cf9f47d 0x1cf9f42d 0x1cf9f3fd 0x1cf9e55e 0x157c7455 0x157c6355 0x1cf9ccf5 0x1cf9d507 0x1cf9ba60
2020.06.08 16:53:02.114388 [ 75 ] {} <Fatal> BaseDaemon: 4. /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:107: __GI_abort @ 0x408f0 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.06.08 16:53:02.114536 [ 75 ] {} <Fatal> BaseDaemon: 5. /build/glibc-OTsEL5/glibc-2.27/assert/assert.c:89: __assert_fail_base @ 0x3039a in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.06.08 16:53:02.114780 [ 75 ] {} <Fatal> BaseDaemon: 6. ? @ 0x30412 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.06.08 16:53:02.115076 [ 75 ] {} <Fatal> BaseDaemon: 7. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Common/Exception.cpp:47: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x157a5608 in /usr/bin/clickhouse
2020.06.08 16:53:02.148737 [ 75 ] {} <Fatal> BaseDaemon: 8. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/IO/PeekableReadBuffer.cpp:177: DB::PeekableReadBuffer::checkStateCorrect() const @ 0x1d0b8566 in /usr/bin/clickhouse
2020.06.08 16:53:02.171948 [ 74 ] {} <Fatal> BaseDaemon: 14. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Formats/IRowInputFormat.cpp:64: DB::IRowInputFormat::generate() @ 0x1d045f6f in /usr/bin/clickhouse
2020.06.08 16:53:02.184119 [ 75 ] {} <Fatal> BaseDaemon: 9. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/IO/PeekableReadBuffer.cpp:111: DB::PeekableReadBuffer::nextImpl() @ 0x1d0b902c in /usr/bin/clickhouse
2020.06.08 16:53:02.184527 [ 75 ] {} <Fatal> BaseDaemon: 10. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/IO/ReadBuffer.h:53: DB::ReadBuffer::next() @ 0x157ac74b in /usr/bin/clickhouse
2020.06.08 16:53:02.184699 [ 75 ] {} <Fatal> BaseDaemon: 11. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/IO/ReadBuffer.h:81: DB::skipWhitespaceIfAny(DB::ReadBuffer&) @ 0x157d0f7b in /usr/bin/clickhouse
2020.06.08 16:53:02.221443 [ 75 ] {} <Fatal> BaseDaemon: 12. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Formats/Impl/JSONAsStringRowInputFormat.cpp:103: DB::JSONAsStringRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0x1d0b4921 in /usr/bin/clickhouse
2020.06.08 16:53:02.258763 [ 75 ] {} <Fatal> BaseDaemon: 13. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Formats/IRowInputFormat.cpp:64: DB::IRowInputFormat::generate() @ 0x1d045f6f in /usr/bin/clickhouse
2020.06.08 16:53:02.274056 [ 74 ] {} <Fatal> BaseDaemon: 15. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/ISource.cpp:48: DB::ISource::work() @ 0x1cf4e657 in /usr/bin/clickhouse
2020.06.08 16:53:02.295283 [ 75 ] {} <Fatal> BaseDaemon: 14. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/ISource.cpp:48: DB::ISource::work() @ 0x1cf4e657 in /usr/bin/clickhouse
2020.06.08 16:53:02.331305 [ 75 ] {} <Fatal> BaseDaemon: 15. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Storages/Kafka/KafkaBlockInputStream.cpp:88: DB::KafkaBlockInputStream::readImpl()::$_0::operator()() const @ 0x1cace454 in /usr/bin/clickhouse
2020.06.08 16:53:02.365384 [ 75 ] {} <Fatal> BaseDaemon: 16. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Storages/Kafka/KafkaBlockInputStream.cpp:128: DB::KafkaBlockInputStream::readImpl() @ 0x1cacd3fd in /usr/bin/clickhouse
2020.06.08 16:53:02.370875 [ 74 ] {} <Fatal> BaseDaemon: 16. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Storages/Kafka/KafkaBlockInputStream.cpp:88: DB::KafkaBlockInputStream::readImpl()::$_0::operator()() const @ 0x1cace454 in /usr/bin/clickhouse
2020.06.08 16:53:02.394171 [ 75 ] {} <Fatal> BaseDaemon: 17. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/DataStreams/IBlockInputStream.cpp:60: DB::IBlockInputStream::read() @ 0x1bb8fcad in /usr/bin/clickhouse
2020.06.08 16:53:02.434780 [ 75 ] {} <Fatal> BaseDaemon: 18. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Sources/SourceFromInputStream.cpp:145: DB::SourceFromInputStream::generate() @ 0x1d217e01 in /usr/bin/clickhouse
2020.06.08 16:53:02.467556 [ 74 ] {} <Fatal> BaseDaemon: 17. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Storages/Kafka/KafkaBlockInputStream.cpp:128: DB::KafkaBlockInputStream::readImpl() @ 0x1cacd3fd in /usr/bin/clickhouse
2020.06.08 16:53:02.471475 [ 75 ] {} <Fatal> BaseDaemon: 19. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/ISource.cpp:48: DB::ISource::work() @ 0x1cf4e657 in /usr/bin/clickhouse
2020.06.08 16:53:02.529883 [ 75 ] {} <Fatal> BaseDaemon: 20. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Sources/SourceFromInputStream.cpp:97: DB::SourceFromInputStream::work() @ 0x1d217ab3 in /usr/bin/clickhouse
2020.06.08 16:53:02.553526 [ 74 ] {} <Fatal> BaseDaemon: 18. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/DataStreams/IBlockInputStream.cpp:60: DB::IBlockInputStream::read() @ 0x1bb8fcad in /usr/bin/clickhouse
2020.06.08 16:53:02.570632 [ 75 ] {} <Fatal> BaseDaemon: 21. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:155: DB::executeJob(DB::IProcessor*) @ 0x1cf9f54c in /usr/bin/clickhouse
2020.06.08 16:53:02.594073 [ 74 ] {} <Fatal> BaseDaemon: 19. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Sources/SourceFromInputStream.cpp:145: DB::SourceFromInputStream::generate() @ 0x1d217e01 in /usr/bin/clickhouse
2020.06.08 16:53:02.610344 [ 75 ] {} <Fatal> BaseDaemon: 22. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:172: DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1::operator()() const @ 0x1cf9f4c0 in /usr/bin/clickhouse
2020.06.08 16:53:02.634033 [ 74 ] {} <Fatal> BaseDaemon: 20. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/ISource.cpp:48: DB::ISource::work() @ 0x1cf4e657 in /usr/bin/clickhouse
2020.06.08 16:53:02.650700 [ 75 ] {} <Fatal> BaseDaemon: 23. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&>(DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&) @ 0x1cf9f47d in /usr/bin/clickhouse
2020.06.08 16:53:02.676312 [ 74 ] {} <Fatal> BaseDaemon: 21. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Sources/SourceFromInputStream.cpp:97: DB::SourceFromInputStream::work() @ 0x1d217ab3 in /usr/bin/clickhouse
2020.06.08 16:53:02.691960 [ 75 ] {} <Fatal> BaseDaemon: 24. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&>(DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&) @ 0x1cf9f42d in /usr/bin/clickhouse
2020.06.08 16:53:02.717487 [ 74 ] {} <Fatal> BaseDaemon: 22. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:155: DB::executeJob(DB::IProcessor*) @ 0x1cf9f54c in /usr/bin/clickhouse
2020.06.08 16:53:02.732639 [ 75 ] {} <Fatal> BaseDaemon: 25. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1, std::__1::allocator<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1>, void ()>::operator()() @ 0x1cf9f3fd in /usr/bin/clickhouse
2020.06.08 16:53:02.757431 [ 74 ] {} <Fatal> BaseDaemon: 23. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:172: DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1::operator()() const @ 0x1cf9f4c0 in /usr/bin/clickhouse
2020.06.08 16:53:02.771716 [ 75 ] {} <Fatal> BaseDaemon: 26. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1, std::__1::allocator<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1>, void ()>::operator()() @ 0x1cf9e55e in /usr/bin/clickhouse
2020.06.08 16:53:02.773112 [ 75 ] {} <Fatal> BaseDaemon: 27. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x157c7455 in /usr/bin/clickhouse
2020.06.08 16:53:02.773316 [ 75 ] {} <Fatal> BaseDaemon: 28. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x157c6355 in /usr/bin/clickhouse
2020.06.08 16:53:02.796382 [ 74 ] {} <Fatal> BaseDaemon: 24. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&>(DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&) @ 0x1cf9f47d in /usr/bin/clickhouse
2020.06.08 16:53:02.812032 [ 75 ] {} <Fatal> BaseDaemon: 29. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:633: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1cf9ccf5 in /usr/bin/clickhouse
2020.06.08 16:53:02.835429 [ 74 ] {} <Fatal> BaseDaemon: 25. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&>(DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1&) @ 0x1cf9f42d in /usr/bin/clickhouse
2020.06.08 16:53:02.850103 [ 75 ] {} <Fatal> BaseDaemon: 30. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:546: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0x1cf9d507 in /usr/bin/clickhouse
2020.06.08 16:53:02.873647 [ 74 ] {} <Fatal> BaseDaemon: 26. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1, std::__1::allocator<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1>, void ()>::operator()() @ 0x1cf9f3fd in /usr/bin/clickhouse
2020.06.08 16:53:02.888132 [ 75 ] {} <Fatal> BaseDaemon: 31. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:812: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1cf9ba60 in /usr/bin/clickhouse
2020.06.08 16:53:02.910534 [ 74 ] {} <Fatal> BaseDaemon: 27. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1, std::__1::allocator<DB::PipelineExecutor::addJob(DB::PipelineExecutor::ExecutionState*)::$_1>, void ()>::operator()() @ 0x1cf9e55e in /usr/bin/clickhouse
2020.06.08 16:53:02.910884 [ 74 ] {} <Fatal> BaseDaemon: 28. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x157c7455 in /usr/bin/clickhouse
2020.06.08 16:53:02.911045 [ 74 ] {} <Fatal> BaseDaemon: 29. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x157c6355 in /usr/bin/clickhouse
2020.06.08 16:53:02.947298 [ 74 ] {} <Fatal> BaseDaemon: 30. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:633: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1cf9ccf5 in /usr/bin/clickhouse
2020.06.08 16:53:02.983363 [ 74 ] {} <Fatal> BaseDaemon: 31. /home/mfilimonov/workspace/ClickHouse/build-vscode/clang_8_Debug/../../src/Processors/Executors/PipelineExecutor.cpp:546: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0x1cf9d507 in /usr/bin/clickhouse
```

```
@pytest.mark.timeout(180)
def test_kafka_json_as_string(kafka_cluster):
    kafka_produce('kafka_json_as_string', ['{"t": 123, "e": {"x": "woof"} }', '{"t": 123, "e": {"x": "woof"} }', '{"t": 124, "e": {"x": "test"} }'])

    instance.query('''
        CREATE TABLE test.kafka (field String)
            ENGINE = Kafka
            SETTINGS kafka_broker_list = 'kafka1:19092',
                     kafka_topic_list = 'kafka_json_as_string',
                     kafka_group_name = 'kafka_json_as_string',
                     kafka_format = 'JSONAsString',
                     kafka_flush_interval_ms=1000;
        ''')

    time.sleep(9)

    result = instance.query('SELECT * FROM test.kafka;')
    print(result)
```

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md)
Make more input format work with Kafka engine. Fix the issue with premature flushes.  Fix the performance issue when `kafka_num_consumers` is greater than number of partitions in topic.

Detailed description / Documentation draft:
- Formats using PeekableReadBuffer were not working because one `next()` call were bypassing PeekableReadBuffer and it was confused by state change of underlying buffer. Also I've added state resetting to some formats. Because it required to check the `eof` another way - i've split `poll` / `nextImpl`, and did some refactoring. Closes #11514 /cc @Avogar 
- if some buffer can't get an assignment - it was doing several retries to get an assignment on every block. So even if one consumer was working fast flush was blocked by another waiting for assignments. Now it allowed waiting for assignment longer only after initialization or after rebalances. If consumer can't get an assignment it will do single short poll (50ms) on every block to ensure that it's not assigned yet. Closes #11218
- if Kafka returns no new messages (due to coming to the partition end, or because we drained librdkafka queue to fast) we do `MAX_FAILED_POLL_ATTEMPTS` (10) reties.  Closes #11216
- Now if message parse returns no rows we write a warning in logs.

### CODE REVIEW

File: src/Storages/Kafka/ReadBufferFromKafkaConsumer.cpp [hunk 1]
```diff
@@ -302,102 +303,131 @@ void ReadBufferFromKafkaConsumer::resetToLastCommitted(const char * msg)
...
-                        return false;
-                    }
-
+                    continue;
                 }
                 else
                 {
-                    LOG_TRACE(log, "Stalled");
-                    stalled = true;
+                    LOG_TRACE(log, "Can't get assignment");
```
Comment (azat) [inline src/Storages/Kafka/ReadBufferFromKafkaConsumer.cpp:370]: While you are are here, can you change the level of this message from trace to at least warning (or even better error)?

File: src/IO/PeekableReadBuffer.cpp [hunk 2]
```diff
@@ -20,6 +20,19 @@ PeekableReadBuffer::PeekableReadBuffer(ReadBuffer & sub_buf_, size_t start_size_
...
 }
 
+void PeekableReadBuffer::reset()
+{
+    peeked_size = 0;
+    checkpoint = nullptr;
+    checkpoint_in_own_memory = false;
+
+    if (!currentlyReadFromOwnMemory())
+        sub_buf.position() = pos;
```
Comment (tavplubix) [inline src/IO/PeekableReadBuffer.cpp:30]: Is it possible that `pos` became an invalid pointer because internal memory of `sub_buf` was reallocated for some reason after direct manipulations with `sub_buf`?

Comment (filimonov) [reply src/IO/PeekableReadBuffer.cpp:30]: All direct manipulations on subbuf possible only after after reset() call before next(). May be i should add comment dicumneting that requirement.

File: src/Storages/Kafka/ReadBufferFromKafkaConsumer.cpp (hunk 1 above)
Comment (filimonov) [reply src/Storages/Kafka/ReadBufferFromKafkaConsumer.cpp:370]: That makes sence. Will do.

File: src/IO/PeekableReadBuffer.cpp (hunk 2 above)
Comment (filimonov) [reply src/IO/PeekableReadBuffer.cpp:30]: Added a comment in PeekableReadBuffer.h

File: tests/integration/test_storage_kafka/test.py [hunk 3]
```diff
@@ -103,6 +103,433 @@ def kafka_produce_protobuf_messages(topic, start_index, num_messages):
...
+                '\x05\x02\x69\x64\x07\x62\x6c\x6f\x63\x6b\x4e\x6f\x04\x76\x61\x6c\x31\x04\x76\x61\x6c\x32\x04\x76\x61\x6c\x33\x05\x49\x6e\x74\x36\x34\x06\x55\x49\x6e\x74\x31\x36\x06\x53\x74\x72\x69\x6e\x67\x07\x46\x6c\x6f\x61\x74\x33\x32\x05\x55\x49\x6e\x74\x38\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x41\x4d\x00\x00\x00\x3f\x01',
+                #''
+                # !!! On empty message segfault: Address not mapped to object
```
Comment (filimonov) [inline tests/integration/test_storage_kafka/test.py:309]: This one is really strange. I don't really understand how it happen (it looks the needed checks are there).

File: src/IO/PeekableReadBuffer.h [hunk 4]
```diff
@@ -38,6 +39,11 @@ class PeekableReadBuffer : public BufferWithOwnMemory<ReadBuffer>
             peeked_size = 0;
         }
         checkpoint = pos;
+
+        // FIXME: we are checking checkpoint existence in few places (rollbackToCheckpoint/dropCheckpoint)
+        // by simple if(checkpoint) but checkpoint can be nullptr after
+        // setCheckpoint called on empty (non initialized/eof) buffer
+        // and we can't just use simple if(checkpoint)
```
Comment (filimonov) [inline src/IO/PeekableReadBuffer.h:46]: It is the reason why Template format doesn't work with Kafka. 
I've fixed the issue by adding one more flag but after that I get to a very similar problem as segfault with empty message in RowBinaryWithNamesAndTypes

Comment (filimonov) [reply src/IO/PeekableReadBuffer.h:46]: If i fix that i get the following segfault
```
########################################
(version 20.5.1.1) (from thread 25) (no query) Received signal Segmentation fault (11).
Address: NULL pointer. Access: read. Address not mapped to object.
Stack trace: 0x15c8d9c1 0x15c8db3d 0x1dfbb955 0x1dfb2e05 0x1de7289f 0x1dd79807 0x1d8f80c4 0x1d8f6942 0x1c9c92fd 0x1c9ea01c 0x1c9e9fc7 0x1d8cc3fa 0x1d8cb509 0x1d8ce978 0x1d8ce93d 0x1d8ce8ed 0x1d8ce8bd 0x1d8cda1e 0x15c4f055 0x15c4dfb5 0x1cbcfe12 0x1cbd6f96 0x1cbd1873 0x1cbd4c58 0x1cbd4c2d 0x1cbd4bf1 0x1cbd4bc2 0x1cbd4abc
/src/IO/ReadHelpers.cpp:92: DB::checkString(char const*, DB::ReadBuffer&) @ 0x15c8d9c1 in /usr/bin/clickhouse
/src/IO/ReadHelpers.cpp:119: DB::assertString(char const*, DB::ReadBuffer&) @ 0x15c8db3d in /usr/bin/clickhouse
/src/IO/ReadHelpers.h:181: DB::assertString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadBuffer&) @ 0x1dfbb955 in /usr/bin/clickhouse
/src/Processors/Formats/Impl/TemplateRowInputFormat.cpp:171: DB::TemplateRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0x1dfb2e05 in /usr/bin/clickhouse
```

**Comment by filimonov** [comment]
The current state of formats supported by engine=Kafka 

| name | checked | working | 
|:-|-:|-:|
| Arrow | 1 | 0 |
| ArrowStream | 1 | 0 |
| Avro | 1 | 0 |
| AvroConfluent | 0 | 0 |
| CSV | 1 | 1 |
| CSVWithNames | 1 | 1 |
| CapnProto | 1 | 1 |
| CustomSeparated | 0 | ? |
| CustomSeparatedIgnoreSpaces | 0 | ? |
| JSONAsString | 1 | 1 |
| JSONCompactEachRow | 1 | 1 |
| JSONCompactEachRowWithNamesAndTypes | 1 | 1 |
| JSONEachRow | 1 | 1 |
| MsgPack | 1 | 1 |
| Native | 1 | 1 |
| ORC | 1 | 1 |
| Parquet | 1 | 0 |
| Protobuf | 1 | 1 |
| Regexp | 1 | 1 |
| RowBinary | 1 | 1 |
| RowBinaryWithNamesAndTypes | 1 | 1 |
| TSKV | 1 | 1 |
| TSV | 1 | 1 |
| TSVWithNames | 1 | 1 |
| TSVWithNamesAndTypes | 1 | 1 |
| Template | 1 | 0 |
| TemplateIgnoreSpaces | 0 | 0 |
| Values | 1 | 1 |

TabSeparated = TSV
TabSeparatedWithNames = TSVWithNames
TabSeparatedWithNamesAndTypes = TabSeparatedWithNamesAndTypes

**Comment by filimonov** [comment]
Formats which support for Kafka was fixed in that PR:
- MsgPack
- RowBinaryWithNamesAndTypes
- JSONCompactEachRowWithNamesAndTypes 
- TSVWithNamesAndTypes (there was segfault there) 
- Regexp 
- JSONAsString

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
FWIW The following format should be supported after #31434
- CustomSeparated
- CustomSeparatedIgnoreSpaces
