### PR TITLE
Fix crash on call dictGet() with bad arguments.

### LINKED ISSUE #25533: ../src/Interpreters/MarkTableIdentifiersVisitor.cpp:16:16: runtime error: member call on null pointer of type 'DB::TypePromotion' Received signal -3
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/22535/567043113cd0d8e7846a94de1ac85821fd310709/fuzzer_ubsan/report.html#fail1

**How to reproduce**

```sql
SELECT dictGetFloat64(t.b.s, 'database_for_dict.dict1', dictGetFloat64('Ta\0', toUInt64('databas\0_for_dict.dict1databas\0_for_dict.dict1', dictGetFloat64('', '', toUInt64(1048577), toDate(NULL)), NULL), toDate(dictGetFloat64(257, 'database_for_dict.dict1database_for_dict.dict1', '', toUInt64(NULL), 2, toDate(NULL)), '2019-05-2\0')), NULL, toUInt64(dictGetFloat64('', '', toUInt64(-9223372036854775808), toDate(NULL)), NULL))
```

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Bug Fix

Changelog entry:
Fix crash on call dictGet() with bad arguments.

This PR fixes https://github.com/ClickHouse/ClickHouse/issues/25533

### CODE REVIEW

File: src/Interpreters/MarkTableIdentifiersVisitor.cpp [hunk 1]
```diff
@@ -23,37 +43,22 @@ bool MarkTableIdentifiersMatcher::needChildVisit(ASTPtr & node, const ASTPtr & c
...
     else if (functionIsJoinGet(func.name) || functionIsDictGet(func.name))
     {
-        if (!func.arguments || func.arguments->children.empty())
-            return;
-
-        auto ast = func.arguments->children.at(0);
-        auto opt_name = tryGetIdentifierName(ast);
-        if (opt_name && !data.aliases.count(*opt_name) && ast->as<ASTIdentifier>())
-        {
-            ptr->as<ASTFunction>()->arguments->children[0] = ast->as<ASTIdentifier>()->createTable();
```
Comment (vitlibar) [inline src/Interpreters/MarkTableIdentifiersVisitor.cpp:54]: The crash was here because `createTable()` returned nullptr and `assert()` didn't alert on that in release.

**Review by alexey-milovidov — APPROVED** [review]
