### PR TITLE
Fix synchronization in GRPCServer

### LINKED ISSUE #27024: grpc query hangs in ClickHouse 21.3 and 21.6
Sending simple queries like `insert into test_insert(i) values(<random number>)` or `select toUInt32(<random number>) as n` via grpc(non-ssl) using multiple threads, often some of them hang in ClickHouse for ever. Using JDBC driver, which uses http protocol, won't run into this issue.

```
SHOW PROCESSLIST

Query id: 5026d02f-b13b-4ffa-a9bc-f7b764691617

┌─is_initial_query─┬─user────┬─query_id─────────────────────────────┬─address───────────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address───────┬─initial_port─┬─interface─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent─┬─http_referer─┬─forwarded_for─┬─quota_key─┬──────────elapsed─┬─is_cancelled─┬─read_rows─┬─read_bytes─┬─total_rows_approx─┬─written_rows─┬─written_bytes─┬─memory_usage─┬─peak_memory_usage─┬─query─────────────────────────────┬─thread_ids────┬─ProfileEvents.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─ProfileEvents.Values───────────────────────────────────┬─Settings.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─Settings.Values──────────────────┬─current_database─┐
│                1 │ default │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │ 51284 │ default      │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │        51284 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │ 338897.503978826 │            0 │         0 │          0 │                 0 │            1 │             9 │            0 │                 0 │ insert into test_insert(i) values │ [141]         │ ['Query','InsertQuery','QueryTimeMicroseconds','InsertQueryTimeMicroseconds','IOBufferAllocs','IOBufferAllocBytes','FunctionExecute','InsertedRows','InsertedBytes','SelectedRows','SelectedBytes','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SystemTimeMicroseconds'] │ [1,1,438,438,1,1048591,2,1,9,1,9,18,2,571,237,177]     │ ['max_threads','use_uncompressed_cache','aggregation_memory_efficient_merge_threads','max_execution_time','max_memory_usage'] │ ['4','0','0','300','6442450944'] │ system           │
│                1 │ default │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │ 52600 │ default      │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │        52600 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │ 338838.453987025 │            1 │         1 │          1 │                 0 │            0 │             0 │            0 │                 0 │ select toUInt32(5593) as n        │ [140,137]     │ ['Query','SelectQuery','QueryTimeMicroseconds','SelectQueryTimeMicroseconds','SelectedRows','SelectedBytes','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SoftPageFaults']                                        │ [1,1,983,983,1,1,20,1,1317,1010,1]                     │ ['max_threads','use_uncompressed_cache','aggregation_memory_efficient_merge_threads','max_execution_time','max_memory_usage'] │ ['4','0','0','300','6442450944'] │ system           │
└──────────────────┴─────────┴──────────────────────────────────────┴───────────────────────┴───────┴──────────────┴──────────────────────────────────────┴───────────────────────┴──────────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴─────────────────┴──────────────┴───────────────┴───────────┴──────────────────┴──────────────┴───────────┴────────────┴───────────────────┴──────────────┴───────────────┴──────────────┴───────────────────┴───────────────────────────────────┴───────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴──────────────────┘

SELECT *
FROM system.query_log
WHERE initial_query_id IN ('0fb974b6-fbf8-4a96-a211-c6148c613ab7', 'f6140ae8-8f77-49a9-bc26-d79471495334')

Query id: ee33fecd-6fd5-44b7-b22e-8eed795910d3

┌─type────────┬─event_date─┬──────────event_time─┬────event_time_microseconds─┬────query_start_time─┬─query_start_time_microseconds─┬─query_duration_ms─┬─read_rows─┬─read_bytes─┬─written_rows─┬─written_bytes─┬─result_rows─┬─result_bytes─┬─memory_usage─┬─current_database─┬─query─────────────────────────────┬─normalized_query_hash─┬─query_kind─┬─databases──┬─tables─────────────────┬─columns─┬─projections─┬─exception_code─┬─exception─┬─stack_trace─┬─is_initial_query─┬─user────┬─query_id─────────────────────────────┬─address───────────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address───────┬─initial_port─┬─interface─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent─┬─http_referer─┬─forwarded_for─┬─quota_key─┬─revision─┬─log_comment─┬─thread_ids─┬─ProfileEvents.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─ProfileEvents.Values───────────────────────┬─Settings.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─Settings.Values──────────────────┬─used_aggregate_functions─┬─used_aggregate_function_combinators─┬─used_database_engines─┬─used_data_type_families─┬─used_dictionaries─┬─used_formats─┬─used_functions─┬─used_storages─┬─used_table_functions─┐
│ QueryStart  │ 2021-07-26 │ 2021-07-26 13:45:37 │ 2021-07-26 13:45:37.063429 │ 2021-07-26 13:45:37 │    2021-07-26 13:45:37.063429 │                 0 │         0 │          0 │            0 │             0 │           0 │            0 │            0 │ system           │ insert into test_insert(i) values │  15736145110192260209 │ Insert     │ ['system'] │ ['system.test_insert'] │ []      │ []          │              0 │           │             │                1 │ default │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │ 51284 │ default      │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │        51284 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │             │ []         │ []                                                                                                                                                                                                                                                         │ []                                         │ ['max_threads','use_uncompressed_cache','aggregation_memory_efficient_merge_threads','max_execution_time','max_memory_usage'] │ ['4','0','0','300','6442450944'] │ []                       │ []                                  │ []                    │ []                      │ []                │ []           │ []             │ []            │ []                   │
│ QueryFinish │ 2021-07-26 │ 2021-07-26 13:45:37 │ 2021-07-26 13:45:37.063913 │ 2021-07-26 13:45:37 │    2021-07-26 13:45:37.063429 │                 0 │         0 │          0 │            1 │             9 │           1 │            9 │            0 │ system           │ insert into test_insert(i) values │  15736145110192260209 │ Insert     │ ['system'] │ ['system.test_insert'] │ []      │ []          │              0 │           │             │                1 │ default │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │ 51284 │ default      │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │        51284 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │             │ [141]      │ ['Query','InsertQuery','IOBufferAllocs','IOBufferAllocBytes','FunctionExecute','InsertedRows','InsertedBytes','SelectedRows','SelectedBytes','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SystemTimeMicroseconds'] │ [1,1,1,1048591,2,1,9,1,9,16,2,571,237,177] │ ['max_threads','use_uncompressed_cache','aggregation_memory_efficient_merge_threads','max_execution_time','max_memory_usage'] │ ['4','0','0','300','6442450944'] │ []                       │ []                                  │ []                    │ []                      │ []                │ ['Values']   │ ['replicate']  │ []            │ []                   │
└─────────────┴────────────┴─────────────────────┴────────────────────────────┴─────────────────────┴───────────────────────────────┴───────────────────┴───────────┴────────────┴──────────────┴───────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴───────────────────────────────────┴───────────────────────┴────────────┴────────────┴────────────────────────┴─────────┴─────────────┴────────────────┴───────────┴─────────────┴──────────────────┴─────────┴──────────────────────────────────────┴───────────────────────┴───────┴──────────────┴──────────────────────────────────────┴───────────────────────┴──────────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴─────────────────┴──────────────┴───────────────┴───────────┴──────────┴─────────────┴────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴──────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────────────┴───────────────────┴──────────────┴────────────────┴───────────────┴──────────────────────┘
┌─type────────┬─event_date─┬──────────event_time─┬────event_time_microseconds─┬────query_start_time─┬─query_start_time_microseconds─┬─query_duration_ms─┬─read_rows─┬─read_bytes─┬─written_rows─┬─written_bytes─┬─result_rows─┬─result_bytes─┬─memory_usage─┬─current_database─┬─query──────────────────────┬─normalized_query_hash─┬─query_kind─┬─databases──┬─tables─────────┬─columns──────────────┬─projections─┬─exception_code─┬─exception─┬─stack_trace─┬─is_initial_query─┬─user────┬─query_id─────────────────────────────┬─address───────────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address───────┬─initial_port─┬─interface─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent─┬─http_referer─┬─forwarded_for─┬─quota_key─┬─revision─┬─log_comment─┬─thread_ids─┬─ProfileEvents.Names───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─ProfileEvents.Values───────┬─Settings.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─Settings.Values──────────────────┬─used_aggregate_functions─┬─used_aggregate_function_combinators─┬─used_database_engines─┬─used_data_type_families─┬─used_dictionaries─┬─used_formats───────────────────┬─used_functions─┬─used_storages─┬─used_table_functions─┐
│ QueryStart  │ 2021-07-26 │ 2021-07-26 13:46:36 │ 2021-07-26 13:46:36.113378 │ 2021-07-26 13:46:36 │    2021-07-26 13:46:36.113378 │                 0 │         0 │          0 │            0 │             0 │           0 │            0 │            0 │ system           │ select toUInt32(5593) as n │  10364793771821666952 │ Select     │ ['system'] │ ['system.one'] │ ['system.one.dummy'] │ []          │              0 │           │             │                1 │ default │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │ 52600 │ default      │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │        52600 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │             │ []         │ []                                                                                                                                                            │ []                         │ ['max_threads','use_uncompressed_cache','aggregation_memory_efficient_merge_threads','max_execution_time','max_memory_usage'] │ ['4','0','0','300','6442450944'] │ []                       │ []                                  │ []                    │ []                      │ []                │ []                             │ []             │ []            │ []                   │
│ QueryFinish │ 2021-07-26 │ 2021-07-26 13:46:36 │ 2021-07-26 13:46:36.114464 │ 2021-07-26 13:46:36 │    2021-07-26 13:46:36.113378 │                 0 │         1 │          1 │            0 │             0 │           1 │           72 │            0 │ system           │ select toUInt32(5593) as n │  10364793771821666952 │ Select     │ ['system'] │ ['system.one'] │ ['system.one.dummy'] │ []          │              0 │           │             │                1 │ default │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │ 52600 │ default      │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │        52600 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │             │ [140,137]  │ ['Query','SelectQuery','SelectedRows','SelectedBytes','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SoftPageFaults'] │ [1,1,1,1,18,1,1317,1010,1] │ ['max_threads','use_uncompressed_cache','aggregation_memory_efficient_merge_threads','max_execution_time','max_memory_usage'] │ ['4','0','0','300','6442450944'] │ []                       │ []                                  │ []                    │ []                      │ []                │ ['RowBinaryWithNamesAndTypes'] │ ['toUInt32']   │ []            │ []                   │
└─────────────┴────────────┴─────────────────────┴────────────────────────────┴─────────────────────┴───────────────────────────────┴───────────────────┴───────────┴────────────┴──────────────┴───────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴────────────────────────────┴───────────────────────┴────────────┴────────────┴────────────────┴──────────────────────┴─────────────┴────────────────┴───────────┴─────────────┴──────────────────┴─────────┴──────────────────────────────────────┴───────────────────────┴───────┴──────────────┴──────────────────────────────────────┴───────────────────────┴──────────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴─────────────────┴──────────────┴───────────────┴───────────┴──────────┴─────────────┴────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴──────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────────────┴───────────────────┴────────────────────────────────┴────────────────┴───────────────┴──────────────────────┘

SELECT *
FROM system.query_thread_log
WHERE initial_query_id IN ('0fb974b6-fbf8-4a96-a211-c6148c613ab7', 'f6140ae8-8f77-49a9-bc26-d79471495334')

Query id: 4e5fe055-25a6-4033-a055-1872f8fb6c3e

┌─event_date─┬──────────event_time─┬────event_time_microseconds─┬────query_start_time─┬─query_start_time_microseconds─┬─query_duration_ms─┬─read_rows─┬─read_bytes─┬─written_rows─┬─written_bytes─┬─memory_usage─┬─peak_memory_usage─┬─thread_name─────┬─thread_id─┬─master_thread_id─┬─current_database─┬─query─────────────────────────────┬─normalized_query_hash─┬─is_initial_query─┬─user────┬─query_id─────────────────────────────┬─address───────────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address───────┬─initial_port─┬─interface─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent─┬─http_referer─┬─forwarded_for─┬─quota_key─┬─revision─┬─ProfileEvents.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─ProfileEvents.Values───────────────────────┐
│ 2021-07-26 │ 2021-07-26 13:45:37 │ 2021-07-26 13:45:37.063891 │ 2021-07-26 13:45:37 │    2021-07-26 13:45:37.063305 │                 0 │         0 │          0 │            1 │             9 │            0 │                 0 │ QueryPipelineEx │       141 │              141 │ system           │ insert into test_insert(i) values │  15736145110192260209 │                1 │ default │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │ 51284 │ default      │ 0fb974b6-fbf8-4a96-a211-c6148c613ab7 │ ::ffff:192.168.84.249 │        51284 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │ ['Query','InsertQuery','IOBufferAllocs','IOBufferAllocBytes','FunctionExecute','InsertedRows','InsertedBytes','SelectedRows','SelectedBytes','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SystemTimeMicroseconds'] │ [1,1,1,1048591,2,1,9,1,9,16,2,571,237,177] │
└────────────┴─────────────────────┴────────────────────────────┴─────────────────────┴───────────────────────────────┴───────────────────┴───────────┴────────────┴──────────────┴───────────────┴──────────────┴───────────────────┴─────────────────┴───────────┴──────────────────┴──────────────────┴───────────────────────────────────┴───────────────────────┴──────────────────┴─────────┴──────────────────────────────────────┴───────────────────────┴───────┴──────────────┴──────────────────────────────────────┴───────────────────────┴──────────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴─────────────────┴──────────────┴───────────────┴───────────┴──────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────┘
┌─event_date─┬──────────event_time─┬────event_time_microseconds─┬────query_start_time─┬─query_start_time_microseconds─┬─query_duration_ms─┬─read_rows─┬─read_bytes─┬─written_rows─┬─written_bytes─┬─memory_usage─┬─peak_memory_usage─┬─thread_name─────┬─thread_id─┬─master_thread_id─┬─current_database─┬─query──────────────────────┬─normalized_query_hash─┬─is_initial_query─┬─user────┬─query_id─────────────────────────────┬─address───────────────┬──port─┬─initial_user─┬─initial_query_id─────────────────────┬─initial_address───────┬─initial_port─┬─interface─┬─os_user─┬─client_hostname─┬─client_name─┬─client_revision─┬─client_version_major─┬─client_version_minor─┬─client_version_patch─┬─http_method─┬─http_user_agent─┬─http_referer─┬─forwarded_for─┬─quota_key─┬─revision─┬─ProfileEvents.Names────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─ProfileEvents.Values───┐
│ 2021-07-26 │ 2021-07-26 13:46:36 │ 2021-07-26 13:46:36.114308 │ 2021-07-26 13:46:36 │    2021-07-26 13:46:36.114169 │                 0 │         1 │          1 │            0 │             0 │            0 │                 0 │ QueryPipelineEx │       137 │              140 │ system           │ select toUInt32(5593) as n │  10364793771821666952 │                1 │ default │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │ 52600 │ default      │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │        52600 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │ ['SelectedRows','SelectedBytes','ContextLock','RealTimeMicroseconds']                                                          │ [1,1,2,107]            │
│ 2021-07-26 │ 2021-07-26 13:46:36 │ 2021-07-26 13:46:36.114441 │ 2021-07-26 13:46:36 │    2021-07-26 13:46:36.113216 │                 1 │         0 │          0 │            0 │             0 │            0 │                 0 │ QueryPipelineEx │       140 │              140 │ system           │ select toUInt32(5593) as n │  10364793771821666952 │                1 │ default │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │ 52600 │ default      │ f6140ae8-8f77-49a9-bc26-d79471495334 │ ::ffff:192.168.84.249 │        52600 │         3 │         │                 │             │               0 │                    0 │                    0 │                    0 │           0 │                 │              │               │           │    54451 │ ['Query','SelectQuery','ContextLock','RWLockAcquiredReadLocks','RealTimeMicroseconds','UserTimeMicroseconds','SoftPageFaults'] │ [1,1,16,1,1210,1010,1] │
└────────────┴─────────────────────┴────────────────────────────┴─────────────────────┴───────────────────────────────┴───────────────────┴───────────┴────────────┴──────────────┴───────────────┴──────────────┴───────────────────┴─────────────────┴───────────┴──────────────────┴──────────────────┴────────────────────────────┴───────────────────────┴──────────────────┴─────────┴──────────────────────────────────────┴───────────────────────┴───────┴──────────────┴──────────────────────────────────────┴───────────────────────┴──────────────┴───────────┴─────────┴─────────────────┴─────────────┴─────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴─────────────┴─────────────────┴──────────────┴───────────────┴───────────┴──────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────┘
```
I posted some more information at [here](https://gist.github.com/zhicwu/663f28deb3dc44314b5439fadd15082d) but not sure if that helps.

**Expected Behavior**
No query hangs in server - if we have to live with that, at least they can be killed.

### PR DESCRIPTION
**Pull request by vitlibar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category:
- Bug Fix

Changelog entry:
Fix synchronization in GRPCServer
This PR fixes https://github.com/ClickHouse/ClickHouse/issues/27024

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
What is really fixed in this PR? Also add a few comments like "We don't need to lock any mutex, because a predicate for a condition variable is atomic."

**Comment by vitlibar** [comment]
> What is really fixed in this PR? Also add a few comments like "We don't need to lock any mutex, because a predicate for a condition variable is atomic."

I've changed this PR, now it provides a completely different solution, and also I've added a link to an issue in the description.

File: src/Server/GRPCServer.cpp [hunk 1]
```diff
@@ -480,6 +481,40 @@ namespace
...
+        void wait(bool wanted_value) const
+        {
+            std::unique_lock lock{mutex};
+            changed.wait(lock, [this, wanted_value]() { return value == wanted_value; });
+        }
+
+    private:
+        bool value;
+        mutable std::mutex mutex;
+        mutable std::condition_variable changed;
```
Comment (vitlibar) [inline src/Server/GRPCServer.cpp:514]: It appears that the previous solution (`std::atomic<bool> value` + null mutex) didn't work very well. Because `changed.wait(lock, predicate)` is the same as

```
while(!predicate())
  changed.wait();
```

and sometimes the following could happen:

```
Thread1 - running wait(): the predicate is checked, and it's false
Thread2 - running set(): value of the predicate is changed, now it's true, but Thread1 don't know yet
Thread2 - running set(): changed.notify_all() is called
Thread1 - running wait(): changed.wait() is called
```

Finally `Thread1` is waiting for `changed` to be notified, but it's never going to happen because it was notified before `changed.wait()` was called.

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Server/GRPCServer.cpp (hunk 1 above)
Comment (nikitamikhaylov) [reply src/Server/GRPCServer.cpp:514]: Sure, this is default mistake everyone does using condition variables.
