### PR TITLE
cp/mv operations for keeper client

### LINKED ISSUE #68934: Support `copy (cp)` and `move (mv)` requests in `clickhouse-keeper-client`
These types of requests are not supported neither by `clickhouse-keeper` nor by `ZooKeeper` however it's easy to simulate them on client side (https://github.com/ClickHouse/ClickHouse/tree/master/programs/keeper-client). 

To implement copy:
```
auto source_path = xxx;
auto dest_path = yyy;
while (true)
{
    auto [version_source, source_content] = zk->get(source_path).stat.version;
    auto multitx;
    multitx.append(check_version(source_path, version_source));
    multitx.append(create(dest_path, source_content));
    if (auto code = zk->multi(multitx); code == ZOK)
        break;
    else if (code == ZNODEEXISTS)
       throw exception("Dest path already exsits");
    else if (code == ZBADVERSION)
      continue;
    else
       throw exception("Something weird");
}
```
To implement move:
``` try to guess ``` :)

### PR DESCRIPTION
**Pull request by Michicosun**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added cp/mv commands for keeper client which atomically copies/moves node. 

Closes: https://github.com/ClickHouse/ClickHouse/issues/68934

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 4d486f1a74b265ec746bdb87d98b16d4c57e72e4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69034/4d486f1a74b265ec746bdb87d98b16d4c57e72e4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: programs/keeper-client/Commands.cpp [hunk 1]
```diff
@@ -677,4 +677,105 @@ void GetAllChildrenNumberCommand::execute(const ASTKeeperQuery * query, KeeperCl
...
+}
+
+void CPCommand::execute(const ASTKeeperQuery * query, KeeperClient * client) const
+{
+    auto src = client->getAbsolutePath(query->args[0].safeGet<String>());
+    auto dest = client->getAbsolutePath(query->args[1].safeGet<String>());
+
+    CPMVOperation operation(std::move(src), std::move(dest), /*remove_src_=*/false, /*client_=*/client);
+
+    while (!operation.perform())
```
Comment (alesapin) [inline programs/keeper-client/Commands.cpp:751]: Let's limit to big value, like 1000 times, just in case

File: programs/keeper-client/Commands.cpp [hunk 2]
```diff
@@ -677,4 +677,105 @@ void GetAllChildrenNumberCommand::execute(const ASTKeeperQuery * query, KeeperCl
...
+        Coordination::Requests ops{
+            zkutil::makeCheckRequest(src, src_stat.version),
+            zkutil::makeCreateRequest(dest, data, zkutil::CreateMode::Persistent), // Do we need to copy ACLs here?
+        };
+
+        if (remove_src)
+            ops.push_back(zkutil::makeRemoveRequest(src, src_stat.version));
+
+        Coordination::Responses responses;
+        auto code = client->zookeeper->tryMultiNoThrow(ops, responses);
```
Comment (alesapin) [inline programs/keeper-client/Commands.cpp:705]: I think `tryMulti` is enough. `NoThrow` avoiding throw in case of `SESSION EXPIRED` but why do we need it?

**Review by alesapin — COMMENTED** [review]
Let's add at least a smoke test https://github.com/ClickHouse/clickhouse/blob/master/tests/queries/0_stateless/03135_keeper_client_find_commands.sh

File: programs/keeper-client/Commands.cpp (hunk 2 above)
Comment (Michicosun) [reply programs/keeper-client/Commands.cpp]: fixed

File: programs/keeper-client/Commands.cpp (hunk 1 above)
Comment (Michicosun) [reply programs/keeper-client/Commands.cpp]: Added 1000 retries, if it does not work in the end, then the last error is thrown

**Review by alesapin — APPROVED** [review]
LGTM🚀
