### PR TITLE
Fix final=1 for distributed over non-mt table.

### LINKED ISSUE #63960: Unexpected exception when using final modifier with non MergeTree table
https://fiddle.clickhouse.com/2f3e3b06-468c-43d2-abc9-d92dbc990d05
```sql
CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=Log;

CREATE TABLE IF NOT EXISTS distributed_table as users ENGINE = Distributed(default, currentDatabase(), users);

insert into distributed_table (age) values (1), (2), (3);

set final=1;
select count() from users;
select count() from distributed_table;
```
```
3

Received exception from server (version 24.3.3):
Code: 181. DB::Exception: Received from localhost:9000. DB::Exception: Storage Log doesn't support FINAL. (ILLEGAL_FINAL)
(query: select count() from distributed_table;)
```
Exception looks really misleading to me, I can actually use FINAL with log storage.  Exception only appears when analyzer is on. 
Seems like FINAL should be ignored when it is not applicable. 

I know that FINAL modifier can be used only for a SELECT from ReplacingMergeTree, SummingMergeTree, AggregatingMergeTree, CollapsingMergeTree and VersionedCollapsingMergeTree tables.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not throw `Storage doesn't support FINAL` error for remote queries over non-MergeTree tables with `final = true` and new analyzer. Fixes #63960

### CODE REVIEW

**Comment by SmitaRKulkarni** [comment]
clang tidy build fails looks like unrelated, maybe merging master will fix

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

File: src/Analyzer/QueryTreePassManager.cpp [hunk 1]
```diff
@@ -192,7 +192,7 @@ void QueryTreePassManager::run(QueryTreeNodePtr query_tree_node)
 void QueryTreePassManager::runOnlyResolve(QueryTreeNodePtr query_tree_node)
 {
     // Run only QueryAnalysisPass and GroupingFunctionsResolvePass passes.
-    run(query_tree_node, 2);
+    run(query_tree_node, 3);
```
Comment (novikd) [inline src/Analyzer/QueryTreePassManager.cpp:195]: Probably we need to invent something better than indexing here.

File: src/Analyzer/Passes/AutoFinalOnQueryPass.cpp [hunk 2]
```diff
@@ -42,7 +42,7 @@ class AutoFinalOnQueryPassVisitor : public InDepthQueryTreeVisitorWithContext<Au
             return;
 
         const auto & storage = table_node ? table_node->getStorage() : table_function_node->getStorage();
-        bool is_final_supported = storage && storage->supportsFinal();
+        bool is_final_supported = storage && !storage->isRemote() && storage->supportsFinal();
```
Comment (novikd) [inline src/Analyzer/Passes/AutoFinalOnQueryPass.cpp:45]: Just curious: how did it work in old infrastructure?

**Review by novikd — APPROVED** [review]
LGTM

File: src/Analyzer/Passes/AutoFinalOnQueryPass.cpp (hunk 2 above)
Comment (KochetovNicolai) [reply src/Analyzer/Passes/AutoFinalOnQueryPass.cpp:45]: Same. I have copied from this
https://github.com/ClickHouse/ClickHouse/blob/51afec49107864e97eb36f9e5760efd1e11bfea8/src/Interpreters/InterpreterSelectQuery.cpp#L3268
