### PR TITLE
Revert "fix replaceRegexpAll bug" + proper fix

### LINKED ISSUE #30245: trim incorrect result in case of BOTH
```sql
SELECT trim(BOTH ', ' FROM '5935,5998,6014, ')||'|' x

SELECT concat(replaceRegexpAll('5935,5998,6014, ', concat('^[', regexpQuoteMeta(', '), ']*|[', regexpQuoteMeta(', '), ']*$'), ''), '|') AS x

┌─x─────────────────┐
│ 5935,5998,6014, | │
└───────────────────┘

psql> SELECT trim(BOTH ', ' FROM '5935,5998,6014, ')||'|'
5935,5998,6014|

```
http://sqlfiddle.com/#!17/0a28f/406

though trailing
```sql
SELECT trim(trailing ', ' FROM '5935,5998,6014, ')||'|' x
┌─x───────────────┐
│ 5935,5998,6014| │
└─────────────────┘
```

### LINKED ISSUE #32777: replaceRegexpAll has different behavior in 21 vs 20, and doesn't match the documentation
**Describe the unexpected behaviour**

I expect

```sql
select replaceRegexpAll('Hello, World!', '^', 'here: ')
```

to produce 

```
here: Hello, World!
```

in v20, this is the case, and in v21 the result is:

```
here: ello, World!
```

**How to reproduce**

Run the above query in clickhouse v20, then in v21

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Reverts ClickHouse/ClickHouse#30292

The code was incorrect. This closes #32777.

Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a regression in `replaceRegexpAll` function. The function worked incorrectly when matched substring was empty. This closes #32777. This closes #30245.

### CODE REVIEW

File: src/Functions/ReplaceRegexpImpl.h [hunk 1]
```diff
@@ -32,10 +32,18 @@ template <bool replace_one = false>
 struct ReplaceRegexpImpl
 {
     /// Sequence of instructions, describing how to get resulting string.
-    /// Each element is either:
-    /// - substitution (in that case first element of pair is their number and second element is empty)
-    /// - string that need to be inserted (in that case, first element of pair is that string and second element is -1)
-    using Instructions = std::vector<std::pair<int, std::string>>;
+    struct Instruction
+    {
+        /// If non zero - perform substitution of n-th subpattern from the regexp match.
```
Comment (vdimir) [inline src/Functions/ReplaceRegexpImpl.h:37]: Value `-1` means use `literal`, but `0` is still number of pattern, isn't it?

```suggestion
        /// If not negative - perform substitution of n-th subpattern from the regexp match.
```

**Review by vdimir — APPROVED** [review]
