### PR TITLE
Fix merging of aggregated data for grouping sets.

### LINKED ISSUE #68532: Stateless test `03023_group_by_use_nulls_analyzer_crashes` has failed
https://s3.amazonaws.com/clickhouse-test-reports/0/da1d09b2d9c8f9a70527f704de54019f64331bc7/stateless_tests__ubsan__[2_2].html

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix merging of aggregated data for grouping sets

Fixes #68532

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

File: src/Processors/Transforms/MergingAggregatedTransform.cpp [hunk 1]
```diff
@@ -10,11 +11,118 @@ namespace ErrorCodes
...
+
+        /// Optimization for equal ranges.
+        if (last_group == group)
+            continue;
+
+        /// Optimization for single group.
+        if (enumerated_groups.empty())
+        {
+            selector.reserve(num_rows);
+            enumerated_groups.emplace(last_group, enumerated_groups.size());
```
Comment (novikd) [inline src/Processors/Transforms/MergingAggregatedTransform.cpp:71]: This line looks redundant because there's another `emplace` call outside of `if`

**Review by novikd — COMMENTED** [review]
LGTM

File: src/Processors/Transforms/MergingAggregatedTransform.cpp (hunk 1 above)
Comment (KochetovNicolai) [reply src/Processors/Transforms/MergingAggregatedTransform.cpp:71]: Ah, yes, there is a bug below.

File: src/Processors/QueryPlan/MergingAggregatedStep.cpp [hunk 2]
```diff
@@ -127,15 +137,19 @@ void MergingAggregatedStep::transformPipeline(QueryPipelineBuilder & pipeline, c
...
-        pipeline.addSimpleTransform([&](const Block & header)
-                                    { return std::make_shared<MergingAggregatedTransform>(header, transform_params, max_threads); });
+        auto transform = std::make_shared<MergingAggregatedTransform>(pipeline.getHeader(), params, final, grouping_sets_params, max_threads);
+        pipeline.addTransform(std::move(transform));
     }
     else
     {
+        if (input_streams.front().header.has("__grouping_set") || !grouping_sets_params.empty())
+            throw Exception(ErrorCodes::LOGICAL_ERROR,
+                 "Memory efficient merging of aggregated results is not supported for grouping sets.");
```
Comment (novikd) [inline src/Processors/QueryPlan/MergingAggregatedStep.cpp:147]: I'm just curious why?

File: src/Processors/Transforms/MergingAggregatedTransform.cpp [hunk 3]
```diff
@@ -10,11 +13,192 @@ namespace ErrorCodes
...
+    {
+        if (index[output->result_name] != outputs.size())
+            new_outputs.push_back(output);
+    }
+
+    outputs.swap(new_outputs);
+    return reordering;
+}
+
+MergingAggregatedTransform::~MergingAggregatedTransform() = default;
```
Comment (novikd) [inline src/Processors/Transforms/MergingAggregatedTransform.cpp:64]: You could specify it as `= default` in the header. I was thinking, why would it have a special destructor.

**Review by novikd — COMMENTED** [review]
LGTM

File: src/Processors/QueryPlan/MergingAggregatedStep.cpp (hunk 2 above)
Comment (KochetovNicolai) [reply src/Processors/QueryPlan/MergingAggregatedStep.cpp:147]: Because nobody has implemented it.
It is disabled with grouping sets, and I do not want to support it now.
