### PR TITLE
Respect settings truncate_on_insert/create_new_file_on_insert in s3/hdfs/azure engines during partitioned write

### LINKED ISSUE #61492: `INSERT INTO FUNCTION s3(...)` overwrites existing objects regardless of configuration when using `PARTITION BY`
## Description

`INSERT INTO FUNCTION s3(...) PARTITION BY` queries replace any existing objects regardless of the value of `s3_truncate_on_insert`. This is inconsistent with both the documentation and the behaviour when `PARTITION BY` is not used, which throws an exception if an object already exists in the write destination path.

**How to reproduce**
Truncate on insert is disabled on the cluster:
```
SELECT * FROM system.settings WHERE name = 's3_truncate_on_insert'

Query id: c58a7291-14b2-4587-9b8d-4b7d1e07b1dc

┌─name──────────────────┬─value─┬─changed─┬─description─────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type─┬─default─┬─alias_for─┬─is_obsolete─┐
│ s3_truncate_on_insert │ 0     │       0 │ Enables or disables truncate before insert in s3 engine tables. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool │ 0       │           │           0 │
└───────────────────────┴───────┴─────────┴─────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴──────┴─────────┴───────────┴─────────────┘
```

Write an object to S3:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/1/data.csv', 'admin', 'password') SELECT * FROM generateRandom('dt Datetime') LIMIT 1000
```

Overwrite it using PARTITION BY:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/{_partition_id}/data.csv', 'admin', 'password') PARTITION BY 1 SELECT * FROM numbers(1000)

Query id: 8f61c70b-cb14-48fc-bb96-6c0410531ce1

Ok.
```

`blob_storage_log` shows that the file was successfully uploaded:
```
SELECT * FROM system.blob_storage_log WHERE query_id = '8f61c70b-cb14-48fc-bb96-6c0410531ce1' FORMAT Vertical

Row 1:
──────
event_date:              2024-03-16
event_time:              2024-03-16 15:56:18
event_time_microseconds: 2024-03-16 15:56:18.632598
event_type:              Upload
query_id:                8f61c70b-cb14-48fc-bb96-6c0410531ce1
thread_id:               5192
thread_name:             S3ParallelWrite
disk_name:
bucket:                  my-bucket
remote_path:             partition-overwrite/1/data.csv
local_path:
data_size:               3890
error:

1 row in set. Elapsed: 0.031 sec. Processed 614.35 thousand rows, 18.28 MB (19.55 million rows/s., 581.80 MB/s.)
Peak memory usage: 11.65 MiB.
```
And the file exists in minio with the new size and the new timestamp:
image

If we try to overwrite the file without the `PARTITION BY` it fails:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/1/data.csv', 'admin', 'password') SELECT *
FROM numbers(20)

Received exception from server (version 24.1.7):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Object in bucket my-bucket with key partition-overwrite/1/data.csv already exists. If you want to overwrite it, enable setting s3_truncate_on_insert, if you want to create a new file on each insert, enable setting s3_create_new_file_on_insert. (BAD_ARGUMENTS)
```

It also happens when inserting from a table and calculating partition basing on one of the table's fields

**Does it reproduce on the most recent release?**
Yes, tested in 24.2.2.71 and 4.1.7

**Expected behavior**

When `s3_truncate_on_insert` is disabled `INSERT INTO FUNCTION s3(...) PARTITION BY` queries fail if any existing object would be overwritten, as it happen when `PARTITION BY` is not used.

**Error message and/or stacktrace**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Respect settings truncate_on_insert/create_new_file_on_insert in s3/hdfs/azure engines during partitioned write. Closes https://github.com/ClickHouse/ClickHouse/issues/61492

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit ef518946f323c6f8c4c9d5265a8a542cfa728df7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62425/ef518946f323c6f8c4c9d5265a8a542cfa728df7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Storages/StorageS3.cpp [hunk 1]
```diff
@@ -1267,43 +1301,19 @@ SinkToStoragePtr StorageS3::write(const ASTPtr & query, const StorageMetadataPtr
...
     else
     {
         if (query_configuration.withGlobs())
             throw Exception(ErrorCodes::DATABASE_ACCESS_DENIED,
                             "S3 key '{}' contains globs, so the table is in readonly mode", query_configuration.url.key);
 
-        bool truncate_in_insert = local_context->getSettingsRef().s3_truncate_on_insert;
-
-        if (!truncate_in_insert && S3::objectExists(*query_configuration.client, query_configuration.url.bucket, query_configuration.keys.back(), query_configuration.url.version_id, query_configuration.request_settings))
+        if (auto new_key = checkFileExistsAndCreateNewKeyIfNeeded(local_context, configuration, query_configuration.keys.front(), query_configuration.keys.size()))
```
Comment (kssenii) [inline src/Storages/StorageS3.cpp:1312]: May be something like "checkAndGetNewFileOnInsertIfNeeded"? Seems more explanatory, but I do not insist

File: src/Storages/StorageS3.cpp [hunk 2]
```diff
@@ -988,6 +1018,9 @@ class PartitionedStorageS3Sink : public PartitionedSink, WithContext
         auto partition_key = replaceWildcards(key, partition_id);
         validateKey(partition_key);
 
+        if (auto new_key = checkFileExistsAndCreateNewKeyIfNeeded(getContext(), configuration, partition_key, 1))
```
Comment (kssenii) [inline src/Storages/StorageS3.cpp:1021]:
```suggestion
        if (auto new_key = checkFileExistsAndCreateNewKeyIfNeeded(getContext(), configuration, partition_key, /* sequence_number */1))
```

**Review by kssenii — APPROVED** [review]
