### PR TITLE
Refine marks cache metrics to track only queries

### LINKED ISSUE #88787: Mark Cache Hit Rate significantly dropped after upgrading from 25.6 to 25.8
### Company or project name

_No response_

### Describe the situation

MarkCacheMisses rate shot up after upgrading ClickHouse cluster from 25.6.1.3206 to 25.8.10.7

Image

### Which ClickHouse versions are affected?

25.8.10.7

### How to reproduce

I've only seen this on my cluster -- not sure 

### Expected performance

I would have expected the MarkCacheMisses to not be affected by the upgrade

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Refine marks cache metrics to track only queries (after #83415 `MarkCacheHits`/`MarkCacheMisses` was updated for merges as well, this PR will revert this behavior back)

These metrics measure query performance and should only track user-facing operations, not background tasks.

There are 3 different users of marks:
- queries - always fill marks cache and should update both metrics, since this directly impacts query performance
- async marks loader - should not update miss metric since this is a background task; the counter will be updated on `getOrSet` anyway
- merges/mutations - do not affect query performance and marks are typically not cached for them, so avoid updating metrics

Also update MergeTreeReaderSettings interface to sanitize all users: make the ctor private and introduce separate create*() methods, but keep properties public (not ideal, but should be acceptable).

Fixes: https://github.com/ClickHouse/ClickHouse/issues/88787

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> marks are typically not cached for them, so avoid updating metrics

If the mark cache is unused in the background operations, the metrics should not be updated.

File: src/Storages/MergeTree/MergeTreeMarksLoader.cpp [hunk 1]
```diff
@@ -240,7 +240,7 @@ MarkCache::MappedPtr MergeTreeMarksLoader::loadMarksSync()
         }
         else
         {
-            loaded_marks = mark_cache->get(key);
+            loaded_marks = mark_cache->getWithoutMetrics(key);
```
Comment (kssenii) [inline src/Storages/MergeTree/MergeTreeMarksLoader.cpp:243]: Let's add a comment here as well that as `save_marks_in_cache == false` we do not want to update metrics as well as this is used only for merges/mutations?

**Review by kssenii — APPROVED** [review]

File: src/Storages/MergeTree/MergeTreeMarksLoader.cpp (hunk 1 above)
Comment (azat) [reply src/Storages/MergeTree/MergeTreeMarksLoader.cpp:243]: I think that the comment for a method (`getWithoutMetrics`) should be enough (that's why I've added separate method for this), plus it is not only about merges/mutations, there are some other places like:
- https://github.com/ClickHouse/ClickHouse/blob/6e5db4a8c4e9204a74d6eb12a9feb18bcf3ac96b/src/Storages/MergeTree/IMergeTreeDataPart.cpp#L2741-L2749
- https://github.com/ClickHouse/ClickHouse/blob/6e5db4a8c4e9204a74d6eb12a9feb18bcf3ac96b/src/Storages/MergeTree/IMergeTreeDataPart.cpp#L1682

It somehow matches with `MergeTreeReaderSettings::createFromSettings()`

**Comment by azat** [comment]
>If the mark cache is unused in the background operations, the metrics should not be updated.

@alexey-milovidov Yes, this is how it will be after this PR

**Comment by azat** [comment]
And since I "broke" this, I will add a test, w/o this PR it fails - https://pastila.nl/?0087937a/984d59003fa20984c58e92b5961b1930#j1LR7doDT0adPjVOfRD3fA==
