### PR TITLE
Fix NULL values in postgresql protocol

### LINKED ISSUE #22622: Postgresql protocol: extraneous data in "D" message with NULL in resultset
**Describe the unexpected behaviour**
While connecting to clickhouse via psql and postgresql wire protocol endpoint, in case of returning Null value in resultset connection crashes.

**How to reproduce**
Clickhouse version 21.5
```
test_tpcds=> SELECT assumeNotNull(CAST(Null AS Nullable(UInt32))) as x;
 x
---
 0
(1 row)

test_tpcds=> SELECT assumeNotNull(CAST(Null AS Nullable(UInt32))) as x;
 x
---
 0
(1 row)

test_tpcds=> SELECT CAST(Null as Nullable(UInt32));
extraneous data in "D" message
lost synchronization with server: got message type "�", length 1124073472
The connection to the server was lost. Attempting reset: Succeeded.
psql (13.1 (Ubuntu 13.1-1.pgdg20.04+1), server 21.5.1.6436)
WARNING: psql major version 13, server major version 21.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
test_tpcds=>

```

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow NULL values in postgresql protocol. Closes https://github.com/ClickHouse/ClickHouse/issues/22622.

### CODE REVIEW

File: src/Core/PostgreSQLProtocol.h [hunk 1]
```diff
@@ -724,8 +724,9 @@ class DataRow : BackendMessage
     Int32 size() const override
     {
         Int32 sz = 4 + 2; // size of message + number of fields
```
Comment (nikitamikhaylov) [inline src/Core/PostgreSQLProtocol.h:726]: Is this size in bytes? Why not to use `sizeof` some structure here? What will be if we change protocol?

Comment (kssenii) [reply src/Core/PostgreSQLProtocol.h:726]: Yes, in bytes. But it is not a change in protocol, this is how it should have been by protocol.

**Review by nikitamikhaylov — APPROVED** [review]
