### PR TITLE
Do not access shared arenas in aggregate function columns.

### LINKED ISSUE #4402: groupUniqArray related Seg fault
Checked on versions 18.14.19, 19.1.6, 19.3.3 (problem reproduces)

Unfortunately, I was not able to reproduce the problem on some tiny / synthetics datasets, so just prepared some [fragment of data and test](https://github.com/filimonov/chbug) which allows reproducing that. 

How to reproduce:
```
git clone https://github.com/filimonov/chbug
cd chbug
./test.sh 
```

Stacktrace looks like that:
```
2019.02.14 14:50:04.216912 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.02.14 14:50:04.216990 [ 2 ] {} <Error> BaseDaemon: (from thread 65) Received signal Segmentation fault (11).
2019.02.14 14:50:04.217004 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.02.14 14:50:04.217012 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.02.14 14:50:04.217021 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
2019.02.14 14:50:04.250273 [ 2 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::AggreagteFunctionGroupUniqArrayGeneric<true>::merge(char*, char const*, DB::Arena*) const+0xbf) [0x4fe4c1f]
2019.02.14 14:50:04.250319 [ 2 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::ColumnAggregateFunction::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)+0x18c) [0x767c15c]
2019.02.14 14:50:04.250351 [ 2 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::SquashingTransform::append(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&&)+0x7c) [0x6ac35ac]
2019.02.14 14:50:04.250365 [ 2 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::SquashingTransform::add(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&&)+0xff) [0x6ac38ef]
2019.02.14 14:50:04.250376 [ 2 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::SquashingBlockOutputStream::write(DB::Block const&)+0x297) [0x79d8217]
2019.02.14 14:50:04.250391 [ 2 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x73d) [0x7951e2d]
2019.02.14 14:50:04.250402 [ 2 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::CountingBlockOutputStream::write(DB::Block const&)+0x2c) [0x79765ec]
2019.02.14 14:50:04.250412 [ 2 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0xc1) [0x6ac3b11]
2019.02.14 14:50:04.250427 [ 2 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::NullAndDoCopyBlockInputStream::readImpl()+0x24) [0x75b3024]
2019.02.14 14:50:04.250437 [ 2 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6aa852a]
2019.02.14 14:50:04.250447 [ 2 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::AsynchronousBlockInputStream::calculate()+0x56) [0x6a9d756]
2019.02.14 14:50:04.250456 [ 2 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server() [0x6a9dbc0]
2019.02.14 14:50:04.250466 [ 2 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(ThreadPool::worker()+0x19e) [0x9bd63ce]
2019.02.14 14:50:04.250479 [ 2 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server() [0xa3c68cf]
2019.02.14 14:50:04.250488 [ 2 ] {} <Error> BaseDaemon: 14. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f55401176db]
```

### PR DESCRIPTION
**Pull request by akuzm**
These arenas may be updated concurrently, so it is unsafe to
access them, as illustrated by issue #4402. Store them separately
and use a different arena for the updates. Change some callers
to accomodate for this.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Closes #4402

### CODE REVIEW

File: dbms/src/Columns/ColumnAggregateFunction.cpp [hunk 1]
```diff
@@ -265,26 +265,22 @@ void ColumnAggregateFunction::updateHashWithValue(size_t n, SipHash & hash) cons
...
 
-    for (const auto & arena : arenas)
-        res += arena->size();
-
     return res;
 }
 
-
-/// Like byteSize(), highly overestimates size
+/// Like in byteSize(), the size is underestimated.
```
Comment (alexey-milovidov) [inline dbms/src/Columns/ColumnAggregateFunction.cpp]: over/under?

File: dbms/src/Columns/ColumnAggregateFunction.cpp [hunk 2]
```diff
@@ -542,4 +539,30 @@ void ColumnAggregateFunction::getExtremes(Field & min, Field & max) const
     max = serialized;
 }
 
+namespace {
+
+ConstArenas concatArenas(const ConstArenas & array, ConstArenaPtr arena)
+{
+    ConstArenas result = array;
+    if (arena)
+        result.push_back(arena);
```
Comment (alexey-milovidov) [inline dbms/src/Columns/ColumnAggregateFunction.cpp]: std::move

**Review by alexey-milovidov — APPROVED** [review]

File: dbms/src/Columns/ColumnAggregateFunction.cpp (hunk 1 above)
Comment (akuzm) [reply dbms/src/Columns/ColumnAggregateFunction.cpp]: Yes, it's underestimated now, because we don't account for shared arenas (e.g. those used in Aggregator).
