### PR TITLE
Avoid timeouts in 03207_json_read_subcolumns_2_compact_merge_tree test

### LINKED ISSUE #80342: Test `03207_json_read_subcolumns_2_compact_merge_tree` has failed
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9kdXJhdGlvbl9tcywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBZRUFSCiAgICBBTkQgKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHN0YXJ0c1dpdGgoaGVhZF9yZXBvLCAnQ2xpY2tIb3VzZS8nKSkKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCAodGVzdF9zdGF0dXMgTElLRSAnRiUnIE9SIHRlc3Rfc3RhdHVzIExJS0UgJ0UlJykgCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJzAzMjA3X2pzb25fcmVhZF9zdWJjb2x1bW5zXzJfY29tcGFjdF9tZXJnZV90cmVlJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=

CC @Avogar

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/80342

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2 [hunk 1]
```diff
@@ -1,5 +1,5 @@
 -- Tags: no-fasttest, long, no-debug, no-tsan, no-asan, no-msan, no-ubsan
--- Random settings limits: index_granularity=(1000, None)
+-- Random settings limits: index_granularity=(1000, None), index_granularity_bytes=(100000, None)
```
Comment (tuanpach) [inline tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2:2]: Could you give some explanation on why increasing `index_granularity_bytes` helps to prevent the test from timing out?

Comment (Avogar) [reply tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2]: Small `index_granularity_bytes` (as well as small `index_granularity`) leads to creating a lot of granules with low number of rows in MergeTree parts. Inserting/selecting/merging lots of small granules is really slow in compact parts, because we always read/write data for each granule separately.

Comment (tuanpach) [reply tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2]: I noticed that the default value is `10MB`, which is bigger than the minimum value of the change. Do we need to set it to a bigger number than the default one?

Comment (tuanpach) [reply tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2]: I believe that we parse the setting limits here:
https://github.com/ClickHouse/ClickHouse/blob/25f2e13a8fc3ed6e6215ee7481677e1b8523ac4c/tests/clickhouse-test#L2282-L2301

From my understanding, before this PR, we did not randomize this setting `index_granularity_bytes` , and its value would be `10MB` by default. How could it be around tens of thousands before? Please correct me if I am wrong.

Comment (Avogar) [reply tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2]: This code parses `Random settings limits` section that is aimed to restrict the range for the randomized settings. The set of randomized settings and their ranges can be found here: https://github.com/ClickHouse/ClickHouse/blob/25f2e13a8fc3ed6e6215ee7481677e1b8523ac4c/tests/clickhouse-test#L985-L1195
And for setting `index_granularity_bytes` we have range `[1024, 30 * 1024 * 1024]`:
https://github.com/ClickHouse/ClickHouse/blob/25f2e13a8fc3ed6e6215ee7481677e1b8523ac4c/tests/clickhouse-test#L1157C59-L1157C81

Comment (tuanpach) [reply tests/queries/0_stateless/03207_json_read_subcolumns_2_compact_merge_tree.sql.j2]: Got it. Thanks for your explanation.

**Review by tuanpach — APPROVED** [review]
