### PR TITLE
Fix possible segfaults, use-heap-after-free and memory leak in aggregate function combinators

### LINKED ISSUE #40848: Segmentation fault when using uniqCombined64MergeStateMap
The server crashes with the following exception:

```
2022.08.31 12:38:30.037050 [ 250 ] {} <Fatal> BaseDaemon: ########################################
2022.08.31 12:38:30.037116 [ 250 ] {} <Fatal> BaseDaemon: (version 22.9.1.759 (official build), build id: 4A9014C655EC8A958D94BCFF6AD8F931EA146DDA) (from thread 48) (query_id: db243b04-f017-4e4e-bb88-ea0e9406aa36) (query: WITH tmp1 AS ( SELECT cluster, operator, ran_type, uniqCombined64MergeStateMap(17)(map(operator, session_count)) OVER (PARTITION BY cluster, ran_type) AS session_count_map FROM test ) SELECT cluster, operator, ran_type, any(session_count_map) FROM tmp1 GROUP BY cluster, operator, ran_type FORMAT TabSeparatedWithNamesAndTypes;) Received signal Segmentation fault (11)
2022.08.31 12:38:30.037149 [ 250 ] {} <Fatal> BaseDaemon: Address: 0x7f6b336f4000 Access: read. Attempted access has violated the permissions assigned to the memory area.
2022.08.31 12:38:30.037186 [ 250 ] {} <Fatal> BaseDaemon: Stack trace: 0xa3b7d36 0xa3d21cb 0xc60a8c0 0x1503de49 0x15100f71 0x150b8b2e 0xa6df7a9 0x145f2eb5 0x1451ad2a 0x145194fa 0x1451f845 0x15e6d49c 0x15e6b336 0x15cbbeca 0x15cb043b 0x15caf399 0x15caf19d 0x15cadd6c 0x14fb724a 0x15a31f09 0x15a36014 0x15c6a322 0x189ce5d3 0x189cf92d 0x18b92089 0x18b8f942 0x7f6b772cf609 0x7f6b771f4133
2022.08.31 12:38:30.037241 [ 250 ] {} <Fatal> BaseDaemon: 2. memcpy @ 0xa3b7d36 in /usr/bin/clickhouse
2022.08.31 12:38:30.037296 [ 250 ] {} <Fatal> BaseDaemon: 3. DB::WriteBuffer::write(char const*, unsigned long) @ 0xa3d21cb in /usr/bin/clickhouse
2022.08.31 12:38:30.037335 [ 250 ] {} <Fatal> BaseDaemon: 4. _ZNK2DB28CombinedCardinalityEstimatorIm12HashSetTableIm13HashTableCellIm11TrivialHash16HashTableNoStateES3_NS_27UniqCombinedHashTableGrowerE9AllocatorILb1ELb1EEELDu16ELDu12ELDu17ES3_m24HyperLogLogBiasEstimatorINS_20UniqCombinedBiasDataEEL15HyperLogLogMode3EdE5writeERNS_11WriteBufferE @ 0xc60a8c0 in /usr/bin/clickhouse
2022.08.31 12:38:30.037368 [ 250 ] {} <Fatal> BaseDaemon: 5. DB::ColumnAggregateFunction::operator[](unsigned long) const @ 0x1503de49 in /usr/bin/clickhouse
2022.08.31 12:38:30.037394 [ 250 ] {} <Fatal> BaseDaemon: 6. DB::ColumnTuple::get(unsigned long, DB::Field&) const @ 0x15100f71 in /usr/bin/clickhouse
2022.08.31 12:38:30.037419 [ 250 ] {} <Fatal> BaseDaemon: 7. DB::ColumnMap::get(unsigned long, DB::Field&) const @ 0x150b8b2e in /usr/bin/clickhouse
2022.08.31 12:38:30.037454 [ 250 ] {} <Fatal> BaseDaemon: 8. DB::IAggregateFunctionHelper<DB::AggregateFunctionsSingleValue<DB::AggregateFunctionAnyData<DB::SingleValueDataGeneric> > >::addBatch(unsigned long, unsigned long, char**, unsigned long, DB::IColumn const**, DB::Arena*, long) const @ 0xa6df7a9 in /usr/bin/clickhouse
2022.08.31 12:38:30.037510 [ 250 ] {} <Fatal> BaseDaemon: 9. void DB::Aggregator::executeImplBatch<false, false, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true> >(DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>&, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>::State&, DB::Arena*, unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const @ 0x145f2eb5 in /usr/bin/clickhouse
2022.08.31 12:38:30.037582 [ 250 ] {} <Fatal> BaseDaemon: 10. void DB::Aggregator::executeImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true> >(DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>&, DB::Arena*, unsigned long, unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const @ 0x1451ad2a in /usr/bin/clickhouse
2022.08.31 12:38:30.037639 [ 250 ] {} <Fatal> BaseDaemon: 11. DB::Aggregator::executeImpl(DB::AggregatedDataVariants&, unsigned long, unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const @ 0x145194fa in /usr/bin/clickhouse
2022.08.31 12:38:30.037670 [ 250 ] {} <Fatal> BaseDaemon: 12. DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) const @ 0x1451f845 in /usr/bin/clickhouse
2022.08.31 12:38:30.037705 [ 250 ] {} <Fatal> BaseDaemon: 13. DB::AggregatingTransform::consume(DB::Chunk) @ 0x15e6d49c in /usr/bin/clickhouse
2022.08.31 12:38:30.037731 [ 250 ] {} <Fatal> BaseDaemon: 14. DB::AggregatingTransform::work() @ 0x15e6b336 in /usr/bin/clickhouse
2022.08.31 12:38:30.037759 [ 250 ] {} <Fatal> BaseDaemon: 15. DB::ExecutionThreadContext::executeTask() @ 0x15cbbeca in /usr/bin/clickhouse
2022.08.31 12:38:30.037781 [ 250 ] {} <Fatal> BaseDaemon: 16. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15cb043b in /usr/bin/clickhouse
2022.08.31 12:38:30.037801 [ 250 ] {} <Fatal> BaseDaemon: 17. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x15caf399 in /usr/bin/clickhouse
2022.08.31 12:38:30.037825 [ 250 ] {} <Fatal> BaseDaemon: 18. DB::PipelineExecutor::execute(unsigned long) @ 0x15caf19d in /usr/bin/clickhouse
2022.08.31 12:38:30.037847 [ 250 ] {} <Fatal> BaseDaemon: 19. DB::CompletedPipelineExecutor::execute() @ 0x15cadd6c in /usr/bin/clickhouse
2022.08.31 12:38:30.037879 [ 250 ] {} <Fatal> BaseDaemon: 20. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x14fb724a in /usr/bin/clickhouse
2022.08.31 12:38:30.037912 [ 250 ] {} <Fatal> BaseDaemon: 21. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x15a31f09 in /usr/bin/clickhouse
2022.08.31 12:38:30.037934 [ 250 ] {} <Fatal> BaseDaemon: 22. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x15a36014 in /usr/bin/clickhouse
2022.08.31 12:38:30.037954 [ 250 ] {} <Fatal> BaseDaemon: 23. DB::HTTPServerConnection::run() @ 0x15c6a322 in /usr/bin/clickhouse
2022.08.31 12:38:30.037975 [ 250 ] {} <Fatal> BaseDaemon: 24. Poco::Net::TCPServerConnection::start() @ 0x189ce5d3 in /usr/bin/clickhouse
2022.08.31 12:38:30.037994 [ 250 ] {} <Fatal> BaseDaemon: 25. Poco::Net::TCPServerDispatcher::run() @ 0x189cf92d in /usr/bin/clickhouse
2022.08.31 12:38:30.038015 [ 250 ] {} <Fatal> BaseDaemon: 26. Poco::PooledThread::run() @ 0x18b92089 in /usr/bin/clickhouse
2022.08.31 12:38:30.038035 [ 250 ] {} <Fatal> BaseDaemon: 27. Poco::ThreadImpl::runnableEntry(void*) @ 0x18b8f942 in /usr/bin/clickhouse
2022.08.31 12:38:30.038055 [ 250 ] {} <Fatal> BaseDaemon: 28. ? @ 0x7f6b772cf609 in ?
2022.08.31 12:38:30.038070 [ 250 ] {} <Fatal> BaseDaemon: 29. __clone @ 0x7f6b771f4133 in ?
2022.08.31 12:38:30.225556 [ 250 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: DDC0E5661A79BDE4BEDAEEE5C7B86B1B)
```

Reproduced on the following versions: `22.9.1.759`, `22.8.3.13`, `22.6.1.1133`, `22.3.7.28`

**How to reproduce**
Table:
```
CREATE TABLE test (
    cluster Int64,
    operator Int32,
    ran_type Int8,
    session_count AggregateFunction(uniqCombined64(17), Int64),
    session_time SimpleAggregateFunction(sum, Int64),
    session_time_quantile AggregateFunction(quantilesTDigest(0.1, 0.25, 0.5, 0.75, 0.9), Int64)
)
ENGINE = AggregatingMergeTree
ORDER BY (
  cluster,
  operator,
  ran_type
)
SETTINGS index_granularity = 8192;
```

Test data:
```
INSERT INTO test
WITH sessions AS (
  SELECT 1 AS cluster, 1 AS operator, 1 AS ran_type, 1 AS uid, 1000 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 1 AS operator, 1 AS ran_type, 2 AS uid, 500 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 1 AS operator, 1 AS ran_type, 3 AS uid, 300 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 1 AS operator, 2 AS ran_type, 3 AS uid, 200 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 1 AS operator, 2 AS ran_type, 4 AS uid, 1200 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 21 AS uid, 1000 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 22 AS uid, 500 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 23 AS uid, 300 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 24 AS uid, 300 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 25 AS uid, 300 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 26 AS uid, 300 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 2 AS operator, 1 AS ran_type, 27 AS uid, 300 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 3 AS operator, 1 AS ran_type, 31 AS uid, 2000 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 3 AS operator, 1 AS ran_type, 32 AS uid, 1500 AS session_time
  UNION ALL
  SELECT 1 AS cluster, 3 AS operator, 1 AS ran_type, 33 AS uid, 3000 AS session_time
)
SELECT
  l.cluster,
  l.operator,
  l.ran_type,
  uniqCombined64State(17)(toInt64(l.uid)) AS session_count,
  sumSimpleState(toInt64(l.session_time)) AS session_time,
  quantilesTDigestState(0.1, 0.25, 0.5, 0.75, 0.9)(toInt64(l.session_time)) AS session_time_quantile
FROM sessions l
GROUP BY cluster, operator, ran_type
```

The request which leads to the crush:
```
WITH tmp1 AS (
    SELECT
      cluster,
      operator,
      ran_type,
      uniqCombined64MergeStateMap(17)(map(operator, session_count)) OVER (PARTITION BY cluster, ran_type) AS session_count_map
    FROM test
)
SELECT
  cluster,
  operator,
  ran_type,
  any(session_count_map)
FROM tmp1
GROUP BY cluster, operator, ran_type
```

It's interesting to note, that if exclude `ran_type` from the PARTITION BY clause, then the query succeed:
```
WITH tmp1 AS (
    SELECT
      cluster,
      operator,
      ran_type,
      uniqCombined64MergeStateMap(17)(map(operator, session_count)) OVER (PARTITION BY cluster) AS session_count_map
    FROM test
)
SELECT
  cluster,
  operator,
  ran_type,
  any(session_count_map)
FROM tmp1
GROUP BY cluster, operator, ran_type
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible segfaults, use-heap-after-free and memory leak in aggregate function combinators.
 Closes https://github.com/ClickHouse/ClickHouse/issues/40848

### CODE REVIEW

**Comment by Avogar** [comment]
I found similar problem with two combined combinators `ForEachResample`. I will make this fix more generic

**Comment by Avogar** [comment]
Heh:
```
avogar-dev :) select toTypeName(uniqStateForEachMapForEachMap(map(1, [map(1, [1,2])])))

SELECT toTypeName(uniqStateForEachMapForEachMap(map(1, [map(1, [1, 2])])))

Query id: 8f013243-931f-46d4-b338-51a516b19ed5

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.9.1 revision 54460.

┌─toTypeName(uniqStateForEachMapForEachMap(map(1, array(map(1, [1, 2])))))─┐
│ Map(UInt8, Array(Map(UInt8, Array(AggregateFunction(uniq, UInt8)))))     │
└──────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.021 sec.
```

File: src/AggregateFunctions/IAggregateFunction.h [hunk 1]
```diff
@@ -172,6 +172,14 @@ class IAggregateFunction : public std::enable_shared_from_this<IAggregateFunctio
       */
     virtual bool isState() const { return false; }
 
+    virtual IColumn * extractStateColumnFromResultColumn(IColumn *) const
```
Comment (Avogar) [inline src/AggregateFunctions/IAggregateFunction.h:175]: Suggestions for better name?

**Comment by Avogar** [comment]
`Stress test (asan) — Sanitizer assert (in stderr.log)` is related, it found memory leak, will investigate

File: src/AggregateFunctions/IAggregateFunction.h (hunk 1 above)
Comment (novikd) [reply src/AggregateFunctions/IAggregateFunction.h:179]: What about `unwrapStateColumn`?

**Review by novikd — APPROVED** [review]

File: src/Interpreters/Aggregator.cpp [hunk 2]
```diff
@@ -1754,8 +1754,8 @@ inline void Aggregator::insertAggregatesIntoColumns(Mapped & mapped, MutableColu
       * It is also tricky, because there are aggregate functions with "-State" modifier.
       * When we call "insertResultInto" for them, they insert a pointer to the state to ColumnAggregateFunction
       *  and ColumnAggregateFunction will take ownership of this state.
-      * So, for aggregate functions with "-State" modifier, the state must not be destroyed
-      *  after it has been transferred to ColumnAggregateFunction.
+      * So, for aggregate functions with "-State" modifier, only states of all combinators that are used
```
Comment (novikd) [inline src/Interpreters/Aggregator.cpp:1757]: I didn't understand what this sentence means.

File: src/Interpreters/AggregationUtils.cpp [hunk 3]
```diff
@@ -50,19 +50,15 @@ OutputBlockColumns prepareOutputBlockColumns(
...
-                    });
+                auto callback = [&](auto & subcolumn)
+                {
+                    /// The ColumnAggregateFunction column captures the shared ownership of the arena with aggregate function states.
+                    if (auto * column_aggregate_func = typeid_cast<ColumnAggregateFunction *>(subcolumn.get()))
+                        for (auto & pool : aggregates_pools)
+                            column_aggregate_func->addArena(pool);
+                };
+                callback(final_aggregate_columns[i]);
+                final_aggregate_columns[i]->forEachSubcolumnRecursively(callback);
```
Comment (novikd) [inline src/Interpreters/AggregationUtils.cpp:61]: Seems like `callback` can be called several times for `final_aggregate_columns[i]`.

File: src/AggregateFunctions/AggregateFunctionMap.h [hunk 4]
```diff
@@ -187,6 +212,33 @@ class AggregateFunctionMap final
...
+        for (const auto & [key, nested_place] : state.merged_maps)
+        {
+            if constexpr (up_to_state)
+                nested_func->destroyUpToState(nested_place);
+            else
+                nested_func->destroy(nested_place);
+        }
+
+        auto to_destroy = std::move(state.merged_maps);
+        this->data(place).~Data();
```
Comment (novikd) [inline src/AggregateFunctions/AggregateFunctionMap.h:229]:
```suggestion
        state.~Data();
```

File: src/AggregateFunctions/AggregateFunctionMap.h [hunk 5]
```diff
@@ -187,6 +212,33 @@ class AggregateFunctionMap final
...
+
+        for (const auto & [key, nested_place] : state.merged_maps)
+        {
+            if constexpr (up_to_state)
+                nested_func->destroyUpToState(nested_place);
+            else
+                nested_func->destroy(nested_place);
+        }
+
+        auto to_destroy = std::move(state.merged_maps);
```
Comment (novikd) [inline src/AggregateFunctions/AggregateFunctionMap.h:228]: Why is it moved? It'll be destroyed on the next line.

File: src/AggregateFunctions/AggregateFunctionMap.h [hunk 6]
```diff
@@ -84,6 +84,31 @@ class AggregateFunctionMap final
...
+
+    size_t getDefaultVersion() const override
+    {
+        return nested_func->getDefaultVersion();
+    }
+
+    bool hasTrivialDestructor() const override
+    {
+        return false;
+    }
```
[the remark this answers is not in the document]
Comment (novikd) [reply src/AggregateFunctions/AggregateFunctionMap.h:110]: Also why is it not trivial?

[the remark this answers is not in the document]
Comment (Avogar) [reply src/AggregateFunctions/AggregateFunctionMap.h:110]: hasTrivialDestructor() should return `true` if it's not necessary to delete this data (call destroy()). So, we should return `false` for state of `-Map` combinator because it contains `unordered_map` that should be destroyed correctly

File: src/Interpreters/Aggregator.cpp (hunk 2 above)
Comment (Avogar) [reply src/Interpreters/Aggregator.cpp:1757]: For example, if we have function `uniqStateForEachMap` after aggregation we should destroy all states that were created by combinators `-ForEach` and `-Map`, because resulting ColumnAggregateFunction will be responsible only for destruction of the states created by `uniq` function.

Comment (Avogar) [reply src/Interpreters/Aggregator.cpp:1757]: I will add this example to the comment

File: src/Interpreters/AggregationUtils.cpp (hunk 3 above)
Comment (Avogar) [reply src/Interpreters/AggregationUtils.cpp:61]: Why? It will be called for `final_aggregate_columns[i]` only once in line 60.`forEachSubcolumnRecursively ` method don't call callback on the column itself, only on subcolumns.

File: src/AggregateFunctions/AggregateFunctionMap.h (hunk 5 above)
Comment (Avogar) [reply src/AggregateFunctions/AggregateFunctionMap.h]: Forgot to remove it after I added next line, fixed

File: src/AggregateFunctions/AggregateFunctionMap.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (novikd) [reply src/AggregateFunctions/AggregateFunctionMap.h:110]: but it already must return false. In the base class it returns`std::is_trivially_destructible_v<Data>` which is `false`.

[the remark this answers is not in the document]
Comment (Avogar) [reply src/AggregateFunctions/AggregateFunctionMap.h:110]: Oh, yes, you are right, didn't see this in base class, thanks! WIll remove it

File: src/AggregateFunctions/IAggregateFunction.h [hunk 7]
```diff
@@ -113,6 +113,17 @@ class IAggregateFunction : public std::enable_shared_from_this<IAggregateFunctio
     /// Delete data for aggregation.
     virtual void destroy(AggregateDataPtr __restrict place) const noexcept = 0;
 
+    /// Delete all combinator states that were used after combinator -State.
+    /// For example for uniqArrayStateForEachMap(...) it will destroy
+    /// states that were created by combinators Map and ForEach.
+    /// It's needed because ColumnAggregateFunction in the result will be
+    /// responsible only for destruction of states that were created
+    /// by aggregate function and all combinators before -State combinator.
+    virtual void destroyUpToState(AggregateDataPtr __restrict place) const noexcept
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/IAggregateFunction.h:122]: Sounds complicated but understandable. LGTM :)

**Review by alexey-milovidov — APPROVED** [review]
