### PR TITLE
Apply preallocation optimisation more carefully

### LINKED ISSUE #44402: Degraded performance of window functions since 22.8
**Describe the situation**
Degraded performance of window functions since 22.8

**How to reproduce**

```
echo "select * from (select number, count(), dense_rank() over (order by number asc) rank from numbers(100000) group by number) where rank < 100" | clickhouse-benchmark -c 10 --max_threads=8
```

versions <= 22.7

```
localhost:9000, queries 3976, QPS: 442.505, RPS: 57972517.711, MiB/s: 442.295, result RPS: 43807.948, result MiB/s: 1.003.
...
95.000%		0.028 sec.
...
```

versions >= 22.8

```
localhost:9000, queries 202, QPS: 204.984, RPS: 26854915.343, MiB/s: 204.887, result RPS: 20293.387, result MiB/s: 0.464.
...
95.000%		0.056 sec.
...
```

**Additional context**

<= 22.7 explain
```
┌─explain───────────────────────────────────────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))                                               │
│   Filter ((WHERE + (Projection + Before ORDER BY)))                                       │
│     Window (Window step for window 'ORDER BY number ASC')                                 │
│       MergingSorted (Merge sorted streams for window 'ORDER BY number ASC')               │
│         MergeSorting (Merge sorted blocks for window 'ORDER BY number ASC')               │
│           PartialSorting (Sort each block for window 'ORDER BY number ASC')               │
│             Expression (Before window functions)                                          │
│               Aggregating                                                                 │
│                 Expression (Before GROUP BY)                                              │
│                   SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│                     ReadFromStorage (SystemNumbers)                                       │
└───────────────────────────────────────────────────────────────────────────────────────────┘
```

>= 22.8 explain
```
┌─explain───────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))               │
│   Filter ((WHERE + (Projection + Before ORDER BY)))       │
│     Window (Window step for window 'ORDER BY number ASC') │
│       Sorting (Sorting for window 'ORDER BY number ASC')  │
│         Expression (Before window functions)              │
│           Aggregating                                     │
│             Expression (Before GROUP BY)                  │
│               ReadFromStorage (SystemNumbers)             │
└───────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now optimisation is applied only if the cached HT size is sufficiently large (thresholds were determined empirically and hardcoded).

### CODE REVIEW

File: src/Interpreters/Aggregator.cpp [hunk 1]
```diff
@@ -236,15 +236,19 @@ void initDataVariantsWithSizeHint(
...
-                        params.group_by_two_level_threshold,
-                        hint->sum_of_sizes,
-                        /*group_by_two_level_threshold_bytes*/ 0,
-                        /*result_size_bytes*/ 0))
-                    method_chosen = convertToTwoLevelTypeIfPossible(method_chosen);
-                result.init(method_chosen, adjusted);
-                ProfileEvents::increment(ProfileEvents::AggregationHashTablesInitializedAsTwoLevel, result.isTwoLevel());
-                return;
+                /// https://github.com/ClickHouse/ClickHouse/issues/44402#issuecomment-1359920703
+                if ((max_threads > 1 && hint->sum_of_sizes > 100'000) || (max_threads == 1 && hint->sum_of_sizes > 500'000))
```
Comment (SmitaRKulkarni) [inline src/Interpreters/Aggregator.cpp:240]:
```suggestion
                if ((max_threads > 1 && hint->sum_of_sizes > 100'000) || hint->sum_of_sizes > 500'000)
```

File: src/Interpreters/Aggregator.cpp [hunk 2]
```diff
@@ -236,15 +236,19 @@ void initDataVariantsWithSizeHint(
             else
             {
                 const auto adjusted = std::max(lower_limit, hint->median_size);
```
Comment (SmitaRKulkarni) [inline src/Interpreters/Aggregator.cpp:238]: This can also be inside the new if block and you could make `else`  ->  `else if`.
Also I see in the above if block we log a message if we dont preallocate space, would it be helpful to also log if we dont preallocate because of max_threads & size too ? what do you think?

Comment (nickitat) [reply src/Interpreters/Aggregator.cpp:238]: > what do you think?

I find this a bit excessive. it is not really user visible behaviour and it is not actionable (user cannot change this behaviour using some setting).

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM
