### PR TITLE
disable inode lock for macos and freebsd

### LINKED ISSUE #41017: Issue running client from MacOS Aarch64 (Apple Silicon) binary
Hi,

I'm running the ClickHouse binary, I downloaded it with the command

```bash
curl -O 'https://builds.clickhouse.com/master/macos-aarch64/clickhouse' && chmod a+x ./clickhouse
```

But when I run `./clickhouse client` I got the following error:

```
$ ./clickhouse client
open maps: No such file or directory
Unable to obtain inode.
```

Any ideas of how to solve the issue?

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

procfs doesn't exist on MacOS and FreeBSD - disable locking decompressor on inode until we find workaround
closes #41017

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: utils/self-extracting-executable/decompressor.cpp [hunk 1]
```diff
@@ -361,6 +361,8 @@ int decompressFiles(int input_fd, char * path, char * name, bool & have_compress
 
 #endif
 
+#if !defined(OS_DARWIN) && !defined(OS_FREEBSD)
```
Comment (alexey-milovidov) [inline utils/self-extracting-executable/decompressor.cpp:364]: It can be written more naturally with
```
#if defined(OS_LINUX)
```

because other systems like Illumos also don't have it.

There was a port of ClickHouse to Illumos, but it was not added to CI:
https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Apr+illumos+is%3Aclosed

Comment (yakov-olkhovskiy) [reply utils/self-extracting-executable/decompressor.cpp:364]: I made it consistent with previous distinction for read_exe_path function which also relies on procfs. And BTW it means it will not work for Illumos - this function is not optional. However we don't build distribution for Illumos, so I think currently it's ok.
