### PR TITLE
Make Alias more stable

### LINKED ISSUE #85363: `00076_system_columns_bytes` is flaky (due to UNKNOWN_TABLE from Merge/Alias)
[CI DB](https://play.clickhouse.com/play?user=play#d2l0aCAnMjAyNS0wOC0xMSAxMjowMDowMCcgYXMgZW5kCi0td2l0aCBub3coKSBhcyBlbmQKU0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IGVuZCAtIElOVEVSVkFMIDEgbW9udGgKICAgIEFORCAoaGVhZF9yZWYgPSAnbWFzdGVyJykKICAgIEFORCBzdGFydHNXaXRoKGhlYWRfcmVwbywgJ0NsaWNrSG91c2UvJykKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9zdGF0dXMgTk9UIElOICgnT0snLCAnU0tJUFBFRCcsICcnLCAnQlJPS0VOJywgJ05PVF9GQUlMRUQnKQogICAgLS1BTkQgcG9zaXRpb24odGVzdF9uYW1lLCAnd2FybmluZycpID4gMAogICAgLS1hbmQgdGVzdF9uYW1lIGxpa2UgJyUwMjQ0M19kZXRhY2hfYXR0YWNoX3BhcnRpdGlvbiUnCiAgICBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMDA3Nl9zeXN0ZW1fY29sdW1uc19ieXRlcyUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYwpsaW1pdCAxIGJ5IHJlcG9ydF91cmwKCg==)

`Database test_6wl5dog0 does not exist` : https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=2bc1bd4f17bad33bb4aebef2f3aee7dfa15dd7a7&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%2C%201%2F2%29&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%2C%201%2F2%29

`There are no tables satisfied provided regexp`: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=88cceb21d676674901db491ed853ec9c230221d4&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_asan%2C%20distributed%20plan%2C%20parallel%2C%201%2F2%29&name_1=Stateless%20tests%20%28amd_asan%2C%20distributed%20plan%2C%20parallel%2C%201%2F2%29

### LINKED ISSUE #89106: 00938_fix_rwlock_segfault_long flaky: system.columns fails for StorageAlias
Example: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=358c48e41f02afb9063ef6918ec6b90267bc8bd6&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_ubsan%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_ubsan%2C%20parallel%29

```
2025-10-28 04:21:03 Reason: return code:  81
2025-10-28 04:21:03 [baa31d980ebd] 2025.10.28 03:21:03.521791 [ 15033 ] {d8ece5d4-821d-4a1c-946d-2a7b52af5da2} <Error> executeQuery: Code: 81. DB::Exception: Database test_8jhvk7uh does not exist: While executing Columns. (UNKNOWN_DATABASE) (version 25.11.1.399 (official build)) (from [::1]:34832) (comment: 00938_fix_rwlock_segfault_long.sh-test_602eq8px) (query 1, line 1) (in query: SELECT name FROM system.tables UNION ALL SELECT name FROM system.columns format Null), Stack trace (when copying this message, always include the lines below):
2025-10-28 04:21:03 
2025-10-28 04:21:03 0. std::exception::exception[abi:ne190107]() @ 0x000000001afaa0f4
2025-10-28 04:21:03 1. ./ci/tmp/build/./base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x0000000042525e20
2025-10-28 04:21:03 2. ./ci/tmp/build/./src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002a2ea96e
2025-10-28 04:21:03 3. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000001ae21bed
2025-10-28 04:21:03 4. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000001ae21386
2025-10-28 04:21:03 5. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000001ae383ef
2025-10-28 04:21:03 6. ./ci/tmp/build/./src/Interpreters/DatabaseCatalog.cpp:466: DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x0000000035c4d293
2025-10-28 04:21:03 7. ./ci/tmp/build/./src/Interpreters/DatabaseCatalog.cpp:1079: DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x0000000035c55212
2025-10-28 04:21:03 8. ./ci/tmp/build/./src/Storages/StorageAlias.cpp:57: DB::StorageAlias::getTargetTable(std::optional<DB::StorageAlias::TargetAccess>) const @ 0x000000003b76088a
2025-10-28 04:21:03 9. ./src/Storages/StorageAlias.h:108: DB::StorageAlias::getInMemoryMetadataPtr() const @ 0x000000003b768bdb
2025-10-28 04:21:03 10. ./ci/tmp/build/./src/Storages/System/StorageSystemColumns.cpp:150: DB::ColumnsSource::generate() @ 0x000000002faf2b71
2025-10-28 04:21:03 11. ./ci/tmp/build/./src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000003c9e1f59
2025-10-28 04:21:03 12. ./ci/tmp/build/./src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000003c9e1738
2025-10-28 04:21:03 13. ./ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000003ca1778e
2025-10-28 04:21:03 14. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000003c9fab78
2025-10-28 04:21:03 15. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:279: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000003c9fd0f1
2025-10-28 04:21:03 16. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000002a503159
2025-10-28 04:21:03 17. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000002a50c148
2025-10-28 04:21:03 18. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000002a50010f
2025-10-28 04:21:03 19. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000002a50832a
2025-10-28 04:21:03 20. ? @ 0x0000000000094ac3
2025-10-28 04:21:03 21. ? @ 0x0000000000126850
2025-10-28 04:21:03 
2025-10-28 04:21:03 Received exception from server (version 25.11.1):
2025-10-28 04:21:03 Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Database test_8jhvk7uh does not exist: While executing Columns. (UNKNOWN_DATABASE)
2025-10-28 04:21:03 (query: SELECT name FROM system.tables UNION ALL SELECT name FROM system.columns format Null)
2025-10-28 04:21:03 
2025-10-28 04:21:03 /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/test_602eq8px/00938_fix_rwlock_segfault_long.sh.debuglog:
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:11] set -e
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:14] for _ in {1..100}
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:15] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_602eq8px --log_comment 00938_fix_rwlock_segfault_long.sh-test_602eq8px --max_insert_threads 2 --group_by_two_level_threshold 402772 --group_by_two_level_threshold_bytes 23289929 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 10235297 --max_read_buffer_size 918025 --prefer_localhost_replica 0 --max_block_size 75510 --max_joined_block_size_rows 31623 --joined_block_split_single_row 0 --join_output_by_rowlist_perkey_rows_threshold 300 --max_threads 2 --optimize_append_index 0 --use_hedged_requests 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 42 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 36285889 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 2212213356 --min_bytes_to_use_mmap_io 3653403030 --local_filesystem_read_method pread --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 0 --filesystem_prefetch_step_bytes 0 --compile_expressions 0 --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 26 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 477443018 --min_compress_block_size 899559 --max_compress_block_size 1908656 --merge_tree_compact_parts_min_granules_to_multibuffer_read 13 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 5485978 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 0 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone America/Hermosillo --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction True --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.63 --prefer_external_sort_block_bytes 0 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 1 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 1 --query_plan_join_swap_table auto --enable_vertical_final 1 --optimize_extract_common_expressions 0 --use_async_executor_for_materialized_views 1 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 0 --use_skip_indexes_on_data_read 0 --optimize_rewrite_like_perfect_affix 0 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.2 --max_bytes_ratio_before_external_group_by 0.2 --use_skip_indexes_if_final_exact_mode 0 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 1 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 359573082 --index_granularity_bytes 21538604 --merge_max_block_size 3533 --index_granularity 39268 --min_bytes_for_wide_part 225809976 --marks_compress_block_size 84091 --primary_key_compress_block_size 46226 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 385439437 --compact_parts_max_bytes_to_buffer 188761569 --compact_parts_max_granules_to_buffer 246 --compact_parts_merge_max_bytes_to_prefetch_part 9865737 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 480 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --object_serialization_version v2 --object_shared_data_serialization_version map --object_shared_data_serialization_version_for_zero_level_parts map_with_buckets --object_shared_data_buckets_for_compact_part 31 --object_shared_data_buckets_for_wide_part 18 --dynamic_serialization_version v3 --serialization_info_version default --string_serialization_version with_size_stream --enable_shared_storage_snapshot_in_query 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/00938_fix_rwlock_segfault_long.stderr-fatal -q 'SELECT name FROM system.tables UNION ALL SELECT name FROM system.columns format Null'
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:14] for _ in {1..100}
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:15] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_602eq8px --log_comment 00938_fix_rwlock_segfault_long.sh-test_602eq8px --max_insert_threads 2 --group_by_two_level_threshold 402772 --group_by_two_level_threshold_bytes 23289929 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 10235297 --max_read_buffer_size 918025 --prefer_localhost_replica 0 --max_block_size 75510 --max_joined_block_size_rows 31623 --joined_block_split_single_row 0 --join_output_by_rowlist_perkey_rows_threshold 300 --max_threads 2 --optimize_append_index 0 --use_hedged_requests 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 42 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 36285889 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 2212213356 --min_bytes_to_use_mmap_io 3653403030 --local_filesystem_read_method pread --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 0 --filesystem_prefetch_step_bytes 0 --compile_expressions 0 --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 26 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 477443018 --min_compress_block_size 899559 --max_compress_block_size 1908656 --merge_tree_compact_parts_min_granules_to_multibuffer_read 13 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 5485978 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 0 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone America/Hermosillo --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction True --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.63 --prefer_external_sort_block_bytes 0 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 1 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 1 --query_plan_join_swap_table auto --enable_vertical_final 1 --optimize_extract_common_expressions 0 --use_async_executor_for_materialized_views 1 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 0 --use_skip_indexes_on_data_read 0 --optimize_rewrite_like_perfect_affix 0 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.2 --max_bytes_ratio_before_external_group_by 0.2 --use_skip_indexes_if_final_exact_mode 0 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 1 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 359573082 --index_granularity_bytes 21538604 --merge_max_block_size 3533 --index_granularity 39268 --min_bytes_for_wide_part 225809976 --marks_compress_block_size 84091 --primary_key_compress_block_size 46226 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 385439437 --compact_parts_max_bytes_to_buffer 188761569 --compact_parts_max_granules_to_buffer 246 --compact_parts_merge_max_bytes_to_prefetch_part 9865737 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 480 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --object_serialization_version v2 --object_shared_data_serialization_version map --object_shared_data_serialization_version_for_zero_level_parts map_with_buckets --object_shared_data_buckets_for_compact_part 31 --object_shared_data_buckets_for_wide_part 18 --dynamic_serialization_version v3 --serialization_info_version default --string_serialization_version with_size_stream --enable_shared_storage_snapshot_in_query 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/00938_fix_rwlock_segfault_long.stderr-fatal -q 'SELECT name FROM system.tables UNION ALL SELECT name FROM system.columns format Null'
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:14] for _ in {1..100}
2025-10-28 04:21:03 + [2025-10-28 04:20:51] [:15] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_602eq8px --log_comment 00938_fix_rwlock_segfault_long.sh-test_602eq8px --max_insert_threads 2 --group_by_two_level_threshold 402772 --group_by_two_level_threshold_bytes 23289929 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 10235297 --max_read_buffer_size 918025 --prefer_localhost_replica 0 --max_block_size 75510 --max_joined_block_size_rows 31623 --joined_block_split_single_row 0 --join_output_by_rowlist_perkey_rows_threshold 300 --max_threads 2 --opti
```

Reason: `IStorage::tryLockForShare` is the generic implementation. For StorageAlias it's only locking the alias, not the underlying table which might be dropped even when you hold the lock to the alias. We need to either hold the lock too or handle the error

### PR DESCRIPTION
**Pull request by nauu**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix Alias stability issues: Fix StrictnessLevel with SharedDatabaseCatalog, disallow target is also an alias, and implement additional interfaces (getSerializationHints, supportsReplication, getStoragePolicy, totalBytesUncompressed, lifetimeRows, lifetimeBytes, storesDataOnDisk, tryLockForShare, lockForShare). Resolves #89106

### Details

This PR addresses several stability issues with Alias:

1. Fix #89106
2. Fix `StrictnessLevel` with `SharedDatabaseCatalog`
3. Disallow target is also an alias
4. Implement more interfaces:
    - getSerializationHints
    - supportsReplication with explicit return false
    - getStoragePolicy
    - totalBytesUncompressed
    - lifetimeRows
    - lifetimeBytes
    - storesDataOnDisk with explicit return false
    - tryLockForShare
    - lockForShare

Resolves: #89106
Resolves: https://github.com/ClickHouse/ClickHouse/issues/85363

### CODE REVIEW

File: src/Storages/StorageAlias.h [hunk 1]
```diff
@@ -129,6 +129,9 @@ class StorageAlias final : public IStorage, WithContext
     bool isRemote() const override { return getTargetTable()->isRemote(); }
     bool isSharedStorage() const override { return getTargetTable()->isSharedStorage(); }
 
+    /// This is important for DatabaseReplicated, avoid not supported by distributed DDL
```
Comment (azat) [inline src/Storages/StorageAlias.h:142]: Deserves better comment, why it should return false?

File: src/Storages/System/StorageSystemColumns.cpp [hunk 2]
```diff
@@ -148,9 +149,22 @@ class ColumnsSource : public ISource
                     continue;
                 }
 
-                auto metadata_snapshot = storage->getInMemoryMetadataPtr();
+                StorageMetadataPtr metadata_snapshot;
+                /// Can throw UNKNOWN_DATABASE/UNKNOWN_TABLE in case of Alias table
+                try
+                {
+                    metadata_snapshot = storage->getInMemoryMetadataPtr();
```
Comment (azat) [inline src/Storages/System/StorageSystemColumns.cpp]: `tryLockForShare` (few lines above) can also fail, right?

File: src/Storages/System/StorageSystemTables.cpp [hunk 3]
```diff
@@ -283,7 +288,21 @@ class TablesBlockSource : public ISource
     {
         if (table)
         {
-            StorageMetadataPtr metadata_snapshot = table->getInMemoryMetadataPtr();
+            StorageMetadataPtr metadata_snapshot;
```
Comment (azat) [inline src/Storages/System/StorageSystemTables.cpp]: Here `tryLockForShare` can also throw for `Alias`

File: src/Storages/System/StorageSystemTables.cpp [hunk 4]
```diff
@@ -768,20 +821,40 @@ class TablesBlockSource : public ISource
...
+                            res_columns[res_index]->insert(*lifetime_bytes);
+                        else
+                            res_columns[res_index]->insertDefault();
+                    }
+                    catch (const Exception &)
+                    {
+                        /// Even if the method throws, it should not prevent querying system.tables.
+                        tryLogCurrentException("StorageSystemTables");
+                        res_columns[res_index]->insertDefault();
+                    }
```
Comment (azat) [inline src/Storages/System/StorageSystemTables.cpp]: Hm, I don't like how it looks now, but:
- adding try/catch into the `StorageAlias` is not safe - https://github.com/ClickHouse/ClickHouse/pull/89396#discussion_r2492229753 (p.s. better not to re-create PRs, since this looses context)
- and I am not sure that adding separate method into `IStorage` just for `Alias` worth it, though if those will non virtual, only in `IStorage`, it may be OK

Hm, actually I have slightly better idea, how about introducing separate abstraction for calling `IStorage` methods from places like `system.tables` and so on - `IStorageSafeWrapper`, and it will not throw in case of error and we can even use `std::expected` (wraps original return of the method) to make the code looks better. @nauu WDYT? Though maybe it will look too complex... need to verify

**Review by azat — CHANGES_REQUESTED** [review]

File: src/Storages/StorageAlias.h (hunk 1 above)
Comment (nauu) [reply src/Storages/StorageAlias.h:142]: https://github.com/ClickHouse/ClickHouse/blob/96c9926cbc3d2360d02c10df9b95acbcbe4f6c05/src/Interpreters/DDLWorker.cpp#L775C4-L777C1

If supportsReplication return true, Alias will failed with DatabaseReplicated

File: src/Storages/System/StorageSystemTables.cpp (hunk 4 above)
Comment (nauu) [reply src/Storages/System/StorageSystemTables.cpp]: > Hm, I don't like how it looks now, but:
> 
> * adding try/catch into the `StorageAlias` is not safe - [Fix race in Alias #89396 (comment)](https://github.com/ClickHouse/ClickHouse/pull/89396#discussion_r2492229753) (p.s. better not to re-create PRs, since this looses context)

Sorry for that, because I messed up that PR, after separate the experimental I merged from Master, so there were so many unrelated commits in my branch.

> * and I am not sure that adding separate method into `IStorage` just for `Alias` worth it, though if those will non virtual, only in `IStorage`, it may be OK
> 
> Hm, actually I have slightly better idea, how about introducing separate abstraction for calling `IStorage` methods from places like `system.tables` and so on - `IStorageSafeWrapper`, and it will not throw in case of error and we can even use `std::expected` (wraps original return of the method) to make the code looks better. @nauu WDYT? Though maybe it will look too complex... need to verify

I also think there are too many`try-catch` blocks and aren't very pretty, but they might be the most suitable for now. Because the similar approach already exists in `StorageTables`.  Introducing more design just for Aliases seems not worth it.

So let's continue add try catch for tryLockForShare and tryLockForShare to fix the bugs WDYT?

File: src/Storages/System/StorageSystemColumns.cpp (hunk 2 above)
Comment (nauu) [reply src/Storages/System/StorageSystemColumns.cpp]: Theoretically it could , but it does not occur in the tests

Comment (nauu) [reply src/Storages/System/StorageSystemColumns.cpp]: https://github.com/ClickHouse/ClickHouse/blob/a2731b0729c81e314fb5146afce4f51f39d7a6be/src/Storages/IStorage.cpp#L92C1-L101C2
`tryLockForShare` already handles this situation, it will return nullptr not throw err

Comment (nauu) [reply src/Storages/System/StorageSystemColumns.cpp]: but getTargetTable() will

**Comment by nauu** [comment]
Hi @azat , all review comments have been fixed, can we merge it?

File: src/Storages/System/StorageSystemTables.cpp (hunk 4 above)
Comment (azat) [reply src/Storages/System/StorageSystemTables.cpp]: I have another idea, instead of try/catch let's introduce separate methods into `IStorage`, i.e. `tryGetColumnSizes` (and similar), that will do something like this

```cxx
std::expected<IStorage::ColumnSizeByName, Exception> tryGetColumnSizes(const StoragePtr & storage)
{
 try
 {
  return storage->getColumnSizes();
 }
 catch (const Exception & e)
 {
  return std::unexpected(e);
 }
}
```

And use them for `system.columns` and `system.tables`.

Comment (nauu) [reply src/Storages/System/StorageSystemTables.cpp]: Let's do it

File: src/Storages/System/StorageSystemCompletions.cpp [hunk 5]
```diff
@@ -89,7 +89,18 @@ void fillDataWithTableColumns(
...
-    const auto & snapshot = table->getInMemoryMetadataPtr();
+    StorageMetadataPtr snapshot;
+    auto snapshot_result = table->tryGetInMemoryMetadataPtr();
+    if (snapshot_result.has_value())
+    {
+        snapshot = std::move(*snapshot_result);
+    }
+    else
+    {
+        LOG_DEBUG(getLogger("SystemCompletions"), "Failed to get inmemory metadata for {}: {}", table->getStorageID().getNameForLogs(), snapshot_result.error().message());
```
Comment (azat) [inline src/Storages/System/StorageSystemCompletions.cpp]:
```suggestion
        LOG_DEBUG(getLogger("SystemCompletions"), "Failed to get metadata for {}: {}", table->getStorageID().getNameForLogs(), snapshot_result.error().message());
```

File: src/Storages/StorageAlias.h [hunk 6]
```diff
@@ -149,10 +152,21 @@ class StorageAlias final : public IStorage, WithContext
...
 
+    /// Alias does not store data on disk
+    bool storesDataOnDisk() const override { return false; }
+
+    StoragePolicyPtr getStoragePolicy() const override { return getTargetTable()->getStoragePolicy(); }
+    SerializationInfoByName getSerializationHints() const override { return getTargetTable()->getSerializationHints(); }
     ActionLock getActionLock(StorageActionBlockType type) override { return getTargetTable()->getActionLock(type); }
 
+    TableLockHolder lockForShare(const String & query_id, const std::chrono::milliseconds & acquire_timeout) const { return getTargetTable()->lockForShare(query_id, acquire_timeout); }
+    TableLockHolder tryLockForShare(const String & query_id, const std::chrono::milliseconds & acquire_timeout) const {return getTargetTable()->tryLockForShare(query_id, acquire_timeout); }
```
Comment (azat) [inline src/Storages/StorageAlias.h]:
```suggestion
    TableLockHolder tryLockForShare(const String & query_id, const std::chrono::milliseconds & acquire_timeout) const { return getTargetTable()->tryLockForShare(query_id, acquire_timeout); }
```

File: src/Storages/IStorage.h [hunk 7]
```diff
@@ -185,6 +185,18 @@ class IStorage : public std::enable_shared_from_this<IStorage>, public TypePromo
     using ColumnSizeByName = std::unordered_map<std::string, ColumnSize>;
     virtual ColumnSizeByName getColumnSizes() const { return {}; }
 
+    virtual std::expected<ColumnSizeByName, Exception> tryGetColumnSizes() const
```
Comment (azat) [inline src/Storages/IStorage.h]:
```suggestion
    virtual std::expected<ColumnSizeByName, Exception> tryGetColumnSizes() const
```

All new `try*` methods should not be virtual

File: src/Storages/System/StorageSystemColumns.cpp [hunk 8]
```diff
@@ -140,32 +141,55 @@ class ColumnsSource : public ISource
...
+                TableLockHolder table_lock;
+                StorageMetadataPtr metadata_snapshot;
 
-                if (table_lock == nullptr)
+                /// Can throw UNKNOWN_DATABASE/UNKNOWN_TABLE in case of Alias table
+                try
                 {
-                    // Table was dropped while acquiring the lock, skipping table
-                    continue;
+                    table_lock = storage->tryLockForShare(query_id, lock_acquire_timeout);
```
Comment (azat) [inline src/Storages/System/StorageSystemColumns.cpp]: Let's also re-define `tryLockForShare` by returning `std::expected`

File: src/Storages/System/StorageSystemColumns.cpp [hunk 9]
```diff
@@ -140,32 +141,55 @@ class ColumnsSource : public ISource
...
+                catch (const Exception & e)
+                {
+                    if (storage->getName() != "Alias" || (e.code() != ErrorCodes::UNKNOWN_DATABASE && e.code() != ErrorCodes::UNKNOWN_TABLE))
+                        throw;
+                    tryLogCurrentException(getLogger("SystemColumns"), fmt::format("Cannot find target database/table for {}", storage->getStorageID().getNameForLogs()), LogsLevel::debug);
                 }
 
-                auto metadata_snapshot = storage->getInMemoryMetadataPtr();
+                auto metadata_result = storage->tryGetInMemoryMetadataPtr();
+                if (metadata_result.has_value())
```
Comment (azat) [inline src/Storages/System/StorageSystemColumns.cpp]: Let's rewrite all users of `try*` methods into smth like this

```cxx
auto map_storage_error = [&](auto && e)
{
    const auto & name = storage->getName();
    if ((name == "Alias" || name == "Merge") && (e.code() == ErrorCodes::UNKNOWN_DATABASE || e.code() == ErrorCodes::UNKNOWN_TABLE))
    {
        LOG_DEBUG(getLogger("SystemColumns"), "{}: {}", storage->getStorageID().getNameForLogs(), e.message());
        return e;
    }
    throw e;
};

auto metadata_result = storage->tryGetInMemoryMetadataPtr().transform_error(map_storage_error).value_or(std::make_shared<StorageInMemoryMetadata>());
if (auto result = storage->tryGetSerializationHints().transform_error(map_storage_error); result.has_value())
    serialization_hints = std::move(*result);

columns = metadata_snapshot->getColumns();

/// Certain information about a table - should be calculated only when the corresponding columns are queried.
if (columns_mask[7] || columns_mask[8] || columns_mask[9])
{
    if (auto result = storage->tryGetColumnSizes().transform_error(map_storage_error); result.has_value())
        column_sizes = std::move(*result);
}
```

I believe this should looks cleaner.

File: src/Storages/System/StorageSystemColumns.cpp (hunk 8 above)
Comment (azat) [reply src/Storages/System/StorageSystemColumns.cpp]: Bad idea, let's just redefine it for `StorageAlias` to ignore acceptable errors.

File: src/Storages/System/StorageSystemColumns.cpp (hunk 9 above)
Comment (azat) [reply src/Storages/System/StorageSystemColumns.cpp]: Or we can use a different approach, make `try*` methods return `std::optional<>` and make them `virtual`. Default implementation same as w/o `try`, and redefine them for `StorageAlias` to use internally `tryGetTargetTable` (new method, which internally uses `tryGetTable` that does not re-`throw` exception)

And adjust `StorageMerge` to use `StorageMerge::DatabaseNameOrRegexp::getDatabaseIterator` with `DatabaseCatalog::instance().tryGetDatabase` for all `try*` methods.

Comment (nauu) [reply src/Storages/System/StorageSystemColumns.cpp]: I prefer the second approach, it keep the complex inside the Alias

```C++

class IStorage 
{
    
    virtual std::optional<StorageMetadataPtr> tryGetInMemoryMetadataPtr() const
    {
        return getInMemoryMetadataPtr();
    }
}


class StorageAlias : public IStorage
{
    std::optional<StoragePtr> tryGetTargetTable() const
    {
        try {

            return DatabaseCatalog::instance().tryGetTable(StorageID(target_database, target_table), getContext());
        }
        catch (const Exception & e) {
            if (e.code() == ErrorCodes::UNKNOWN_DATABASE)
                return std::nullopt;
            throw;
        }
    }
    
    std::optional<StorageMetadataPtr> tryGetInMemoryMetadataPtr() const override
    {
        auto target = tryGetTargetTable();
        if (!target)
            return std::nullopt;

        return (*target)->getInMemoryMetadataPtr();
    }
}

StorageSystem
auto metadata_snapshot = storage->tryGetInMemoryMetadataPtr().value_or(std::make_shared<StorageInMemoryMetadata>());
```
I need to reimplement the related code.

**Review by azat — APPROVED** [review]
Now looks way better!

File: src/Storages/IStorage.h [hunk 10]
```diff
@@ -185,6 +185,8 @@ class IStorage : public std::enable_shared_from_this<IStorage>, public TypePromo
     using ColumnSizeByName = std::unordered_map<std::string, ColumnSize>;
     virtual ColumnSizeByName getColumnSizes() const { return {}; }
 
+    virtual std::optional<ColumnSizeByName> tryGetColumnSizes() const { return getColumnSizes(); }
```
Comment (azat) [inline src/Storages/IStorage.h:189]: Let's also add comments for new methods, i.e. `same as getColumnSizes() but may return nullopt in some specific engines like Merge/Alias`

File: src/Storages/IStorage.h [hunk 11]
```diff
@@ -203,6 +206,9 @@ class IStorage : public std::enable_shared_from_this<IStorage>, public TypePromo
         return metadata.get();
     }
 
+    /// Same as getInMemoryMetadataPtr() but may return nullopt in some specific engines like Alias
+    virtual std::optional<StorageMetadataPtr> tryGetInMemoryMetadataPtr() const { return getInMemoryMetadataPtr(); }
```
Comment (azat) [inline src/Storages/IStorage.h:210]: Here we need to pass `bypass_metadata_cache` (as in `getInMemoryMetadataPtr`)
