### PR TITLE
Fix assert with non uint8 in prewhere

### LINKED ISSUE #19589: GLOBAL SEMI LEFT JOIN: bad Field get in PREWHERE
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/19387/fb268ec339aeb2cbab0df5137ead3efb8374cc32/fuzzer_debug/server.log

**How to reproduce**
```
SELECT avg(diff) FROM (SELECT * FROM (SELECT learnerHash, passed - eventTime AS diff FROM statements GLOBAL SEMI LEFT JOIN (SELECT learnerHash, argMax(eventTime, resultScoreRaw) AS passed FROM (SELECT learnerHash, eventTime, resultScoreRaw FROM statements WHERE (courseId = 1) AND (onCourse = 1048575) AND (verb = 'http://adlnet.gov/expapi/verbs/passed') AND (objectId = 'https://crmm.ru/xapi/courses/spp/1/1/0-1') ORDER BY eventTime ASC) GROUP BY learnerHash) USING (learnerHash) WHERE resultScoreRaw AND (courseId = 1) AND (onCourse = 0) AND (verb = 'http://adlnet.gov/expapi/verbs/interacted') AND (eventTime <= passed) AND (diff > 0) ORDER BY eventTime DESC LIMIT 0 BY learnerHash) ORDER BY diff DESC LIMIT 7, 126)
```

Looks like query is based on `00586_removing_unused_columns_from_subquery.sql`.

MergeTreeBaseSelectProcessor.cpp:331

```
            auto & ctn = block.getByName(prewhere_info->prewhere_column_name);
            ctn.column = ctn.type->createColumnConst(block.rows(), 1u)->convertToFullColumnIfConst();
```

Looks like `prewhere_column_name` has type Float64.

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix assertion in PREWHERE with non-uint8 type, close #19589

### CODE REVIEW

**Comment by vdimir** [comment]
Or maybe better to add check here https://github.com/ClickHouse/ClickHouse/blob/e4d80f53fa25e9738a11d68a3be592ec5bd15c2d/src/Interpreters/ExpressionAnalyzer.cpp#L972-L974

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 1]
```diff
@@ -1038,18 +1037,6 @@ ActionsDAGPtr SelectQueryExpressionAnalyzer::appendPrewhere(
     return prewhere_actions;
 }
 
-void SelectQueryExpressionAnalyzer::appendPreliminaryFilter(ExpressionActionsChain & chain, ActionsDAGPtr actions_dag, String column_name)
```
Comment (vdimir) [inline src/Interpreters/ExpressionAnalyzer.cpp:1041]: It's just dead code

File: src/Columns/FilterDescription.cpp [hunk 2]
```diff
@@ -87,18 +87,4 @@ FilterDescription::FilterDescription(const IColumn & column_)
         ErrorCodes::ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER);
 }
 
-
-void checkColumnCanBeUsedAsFilter(const ColumnWithTypeAndName & column_elem)
```
Comment (vdimir) [inline src/Columns/FilterDescription.cpp:91]: Also was dead code

**Review by alexey-milovidov — APPROVED** [review]
