### PR TITLE
Fix external sort with lazy columns

### LINKED ISSUE #84718: `SELECT ... ORDER BY ... LIMIT ...` query with external sort results in `CORRUPTED_DATA`
### Company or project name

_No response_

### Describe what's wrong

The query always fails with external sorting.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Reproduces in 25.4+.
```
DROP TABLE IF EXISTS test SYNC;
CREATE TABLE test
(
    `service` LowCardinality(String),
    `user_type` LowCardinality(String),
    `campaign_id` UInt32
)
ENGINE = MergeTree
ORDER BY (service, user_type, campaign_id)
SETTINGS index_granularity = 8192;

INSERT INTO test SELECT * FROM generateRandom('`service` LowCardinality(String), `user_type` LowCardinality(String), `campaign_id` UInt32', 44, 300, 300) LIMIT 2;

SELECT * FROM test order by campaign_id limit 2 SETTINGS max_bytes_before_external_sort = 120, max_bytes_ratio_before_external_sort = 0.0;
```

### Expected behavior

The query succeeds just as with `query_plan_optimize_lazy_materialization = 0`.

### Error message and/or stacktrace

```
:) SELECT * FROM test order by campaign_id limit 2 OFFSET 2 SETTINGS max_bytes_before_external_sort = 120, max_bytes_ratio_before_external_sort = 0.0;

SELECT *
FROM test
ORDER BY campaign_id ASC
LIMIT 2, 2
SETTINGS max_bytes_before_external_sort = 120, max_bytes_ratio_before_external_sort = 0.

Query id: 2b64cbe4-411d-47f2-854f-24057d36e292

[ip-10-2-3-206] 2025.07.30 12:05:57.532893 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Debug> executeQuery: (from 0.0.0.0:0, user: ) (query 1, line 1) SELECT * FROM test order by campaign_id limit 2 OFFSET 2 SETTINGS max_bytes_before_external_sort = 120, max_bytes_ratio_before_external_sort = 0.0; (stage: Complete)
[ip-10-2-3-206] 2025.07.30 12:05:57.533178 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> Planner: Query to stage Complete
[ip-10-2-3-206] 2025.07.30 12:05:57.533272 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> Planner: Query from stage FetchColumns to stage Complete
[ip-10-2-3-206] 2025.07.30 12:05:57.533439 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Debug> default.test (5dc5b26b-5ae8-492e-a78c-21e789fc77dc) (SelectExecutor): Key condition: unknown
[ip-10-2-3-206] 2025.07.30 12:05:57.533460 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> default.test (5dc5b26b-5ae8-492e-a78c-21e789fc77dc) (SelectExecutor): Filtering marks by primary and secondary keys
[ip-10-2-3-206] 2025.07.30 12:05:57.533475 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Debug> default.test (5dc5b26b-5ae8-492e-a78c-21e789fc77dc) (SelectExecutor): PK index has dropped 0/1 granules, it took 0ms across 1 threads.
[ip-10-2-3-206] 2025.07.30 12:05:57.533503 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Debug> default.test (5dc5b26b-5ae8-492e-a78c-21e789fc77dc) (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 1/1 marks by primary key, 1 marks to read from 1 ranges
[ip-10-2-3-206] 2025.07.30 12:05:57.533518 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> default.test (5dc5b26b-5ae8-492e-a78c-21e789fc77dc) (SelectExecutor): Spreading mark ranges among streams (default reading)
[ip-10-2-3-206] 2025.07.30 12:05:57.533556 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> default.test (5dc5b26b-5ae8-492e-a78c-21e789fc77dc) (SelectExecutor): Reading 1 ranges in order from part all_1_1_0, approx. 2 rows starting from 0
[ip-10-2-3-206] 2025.07.30 12:05:57.534454 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> MergeSortingTransform: Will dump sorting block (424.00 B, limit: 120.00 B) to disk (query memory: 19.00 KiB, limit: 0.00 B)
[ip-10-2-3-206] 2025.07.30 12:05:57.534488 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> TemporaryFileOnLocalDisk: Creating temporary file 'tmp7101645b-173d-4a04-9736-413dbbdc6057'
[ip-10-2-3-206] 2025.07.30 12:05:57.534516 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> DiskLocal: Reserved 424.00 B on local disk `_tmp_default`, having unreserved 204.49 GiB.
[ip-10-2-3-206] 2025.07.30 12:05:57.534626 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Information> MergeSortingTransform: Sorting and writing part of data into temporary file disk(_tmp_default):///tmp/clickhouse-local-cac379de-a3f2-4de6-a22a-ecec0eb010fa/tmp//tmp7101645b-173d-4a04-9736-413dbbdc6057
[ip-10-2-3-206] 2025.07.30 12:05:57.534723 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Information> MergeSortingTransform: There are 1 temporary sorted parts to merge
[ip-10-2-3-206] 2025.07.30 12:05:57.534812 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Information> MergeSortingTransform: Done writing part of data into temporary file disk(_tmp_default):///tmp/clickhouse-local-cac379de-a3f2-4de6-a22a-ecec0eb010fa/tmp//tmp7101645b-173d-4a04-9736-413dbbdc6057, compressed 136.00 B, uncompressed 161.00 B 
[ip-10-2-3-206] 2025.07.30 12:05:57.534843 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Information> MergeSortingTransform: Start reading part of data from temporary file
[ip-10-2-3-206] 2025.07.30 12:05:57.535078 [ 2008731 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Trace> PipelineExecutor: Exception while executing query. Current state:
digraph
{
  rankdir="LR";
  { node [shape = rect]
    n0[label="MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder)_0:(2 jobs, execution time: 0 sec., preparation time: 0.0000026 sec.) (Finished)"];
    n1[label="ExpressionTransform_1:(1 jobs, execution time: 0 sec., preparation time: 0.00000197 sec.) (Finished)"];
    n2[label="PartialSortingTransform_2:(1 jobs, execution time: 0 sec., preparation time: 0.00000177 sec.) (Finished)"];
    n3[label="LimitsCheckingTransform_3:(1 jobs, execution time: 0 sec., preparation time: 0.00000144 sec.) (Finished)"];
    n4[label="MergeSortingTransform_4:(3 jobs, execution time: 0 sec., preparation time: 0.00000346 sec.) (NeedData)"];
    n5[label="Limit_5:(0 jobs, execution time: 0 sec., preparation time: 0.0000015 sec.) (NeedData)"];
    n6[label="ColumnLazyTransform_6:(0 jobs, execution time: 0 sec., preparation time: 7.3e-7 sec.) (NeedData)"];
    n7[label="ExpressionTransform_7:(0 jobs, execution time: 0 sec., preparation time: 7.8e-7 sec.) (NeedData)"];
    n8[label="LimitsCheckingTransform_8:(0 jobs, execution time: 0 sec., preparation time: 0.00000169 sec.) (NeedData)"];
    n9[label="NullSource_10:(0 jobs, execution time: 0 sec., preparation time: 0 sec.) (NotStarted)"];
    n10[label="NullSource_11:(0 jobs, execution time: 0 sec., preparation time: 0 sec.) (NotStarted)"];
    n11[label="LazyOutputFormat_9:(0 jobs, execution time: 0 sec., preparation time: 0.00000258 sec.) (NeedData)"];
    n12[label="BufferingFromFileSource_14:(0 jobs, execution time: 0 sec., preparation time: 2.5e-7 sec.) (Ready)"];
    n13[label="BufferingToFileSink_13:(3 jobs, execution time: 0 sec., preparation time: 6.5e-7 sec.) (Finished)"];
    n14[label="MergingSortedTransform_15:(0 jobs, execution time: 0 sec., preparation time: 0.00000145 sec.) (NeedData)"];
    n15[label="MergeSorterSource_16:(1 jobs, execution time: 0 sec., preparation time: 2.4e-7 sec.) (Finished)"];
  }
  n0 -> n1;
  n1 -> n2;
  n2 -> n3;
  n3 -> n4;
  n4 -> n5;
  n4 -> n13;
  n5 -> n6;
  n6 -> n7;
  n7 -> n8;
  n8 -> n11;
  n9 -> n11;
  n10 -> n11;
  n12 -> n14;
  n13 -> n12;
  n14 -> n4;
  n15 -> n14;
}

[ip-10-2-3-206] 2025.07.30 12:05:57.535232 [ 2007603 ] {2b64cbe4-411d-47f2-854f-24057d36e292} <Error> executeQuery: Code: 246. DB::Exception: Unknown serialization kind 95: While executing BufferingFromFileSource. (CORRUPTED_DATA) (version 25.8.1.1) (from 0.0.0.0:0) (query 1, line 1) (in query: SELECT * FROM test order by campaign_id limit 2 OFFSET 2 SETTINGS max_bytes_before_external_sort = 120, max_bytes_ratio_before_external_sort = 0.0;), Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000024190232
1. ./build/./src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000120eac1b
2. ./src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b0cf2ac
3. ./src/Common/Exception.h:137: DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000b0cef6b
4. ./build/./src/DataTypes/Serializations/SerializationInfo.cpp:161: DB::SerializationInfo::deserializeFromKindsBinary(DB::ReadBuffer&) @ 0x0000000017dc7643
5. ./build/./src/Formats/NativeReader.cpp:225: DB::NativeReader::read() @ 0x000000001c2ad220
6. ./build/./src/Processors/Transforms/MergeSortingTransform.cpp:122: DB::BufferingFromFileSource::generate() @ 0x000000001c5b37be
7. ./build/./src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001c2df41a
8. ./build/./src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001c2df0f6
9. ./build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001c2fb0bb
10. ./build/./src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001c2ee6b7
11. ./build/./src/Processors/Executors/PipelineExecutor.cpp:278: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001c2eebde
12. ./build/./src/Processors/Executors/PipelineExecutor.cpp:598: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001c2ed217
13. ./build/./src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001c2ec974
14. ./build/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001c302f54
15. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012228d46
16. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001222f5c0
17. start_thread @ 0x0000000000094ac3
18. clone3 @ 0x0000000000126850


Elapsed: 0.003 sec. 

Received exception:
Code: 246. DB::Exception: Unknown serialization kind 95: While executing BufferingFromFileSource. (CORRUPTED_DATA)

:) 
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
Fixes https://github.com/ClickHouse/ClickHouse/issues/84718. 
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix `CORRUPTED_DATA` error when lazy columns are used with external sort.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/TemporaryDataOnDisk.cpp [hunk 1]
```diff
@@ -336,8 +336,9 @@ void TemporaryDataOnDiskScope::deltaAllocAndCheck(ssize_t compressed_delta, ssiz
 
 TemporaryBlockStreamHolder::TemporaryBlockStreamHolder(SharedHeader header_, TemporaryDataOnDiskScope * parent_, size_t reserve_size)
     : WrapperGuard(std::make_unique<TemporaryDataBuffer>(parent_, reserve_size), DBMS_TCP_PROTOCOL_VERSION, header_)
-    , header(header_->cloneWithoutColumns()) /// header is copied without columns to exclude constant columns since they are not supported in (de/)serialization
 {
```
Comment (devcrafter) [inline src/Interpreters/TemporaryDataOnDisk.cpp:339]: Please add comment why we're doing it

File: src/Interpreters/TemporaryDataOnDisk.cpp [hunk 2]
```diff
@@ -336,8 +336,9 @@ void TemporaryDataOnDiskScope::deltaAllocAndCheck(ssize_t compressed_delta, ssiz
...
+    for (const auto & column : *header_)
+        header.insert(ColumnWithTypeAndName{column.column->cloneEmpty()->convertToFullColumnIfConst(), column.type, column.name});
```
Comment (devcrafter) [inline src/Interpreters/TemporaryDataOnDisk.cpp:343]: Please add comment why we're doing it

Comment (devcrafter) [reply src/Interpreters/TemporaryDataOnDisk.cpp:343]: Since `columns` can be absent in header here, - maybe the comment is ancient already, so we can just whole header with converting const columns to full

Comment (devcrafter) [reply src/Interpreters/TemporaryDataOnDisk.cpp:343]: @vdimir Please could you tell if it's still necessary?

**Review by devcrafter — APPROVED** [review]
LGTM

File: src/Interpreters/TemporaryDataOnDisk.cpp (hunk 2 above)
Comment (vdimir) [reply src/Interpreters/TemporaryDataOnDisk.cpp:343]: It is the fix for this issue https://github.com/ClickHouse/ClickHouse/issues/77522 Problem was something like he build pipeline for constant column, but end up having non constant after reading from disk. Materializing columns should also work

**Comment by devcrafter** [comment]
[PR / Stress test (amd_debug) (pull_request)](https://github.com/ClickHouse/ClickHouse/actions/runs/16629333109/job/47059122710?pr=84738) failure - https://github.com/ClickHouse/ClickHouse/issues/84669

File: src/Interpreters/TemporaryDataOnDisk.cpp (hunk 2 above)
Comment (antaljanosbenjamin) [reply src/Interpreters/TemporaryDataOnDisk.cpp:343]: > Materializing columns should also work

As we are operating only on a header, I wanted to be sure that I don't create to huge columns, that is why `cloneEmpty()` first before materializing the column.

**Comment by antaljanosbenjamin** [comment]
`02443_detach_attach_partition` - https://github.com/ClickHouse/ClickHouse/issues/84173

**Comment by antaljanosbenjamin** [comment]
[Stateless tests (amd_binary, ParallelReplicas, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84738&sha=ff33865465556b6209b60346bcafe7fa594e3d08&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%2C%20parallel%29) - https://github.com/ClickHouse/ClickHouse/issues/84771

**Comment by antaljanosbenjamin** [comment]
Manually marking mergeable check green.
