### PR TITLE
case insensitive aliases for CONNECTION_ID() and VERSION()

### LINKED ISSUE #22028: why connection_id() and version() aliases exists, but CONNECTION_ID() and VERSION() is not? ;)
**Describe the bug**
According to https://jira.percona.com/browse/PT-1945 and https://github.com/ClickHouse/ClickHouse/pull/21367

**Does it reproduce on a recent release?**
yep

**How to reproduce**
- define `mysql_port`
- run following SQL queries via MySQL client
```
mysql> SELECT DATABASE(), CONNECTION_ID(), VERSION()/*!50038 , @@hostname*/;
ERROR 46 (00000): Code: 46, e.displayText() = DB::Exception: Unknown function CONNECTION_ID. Maybe you meant: ['connection_id','connectionID']: While processing DATABASE(), CONNECTION_ID(), VERSION() (version 21.3.2.5 (official build))
mysql> SELECT DATABASE(), connection_id(), VERSION()/*!50038 , @@hostname*/;
ERROR 46 (00000): Code: 46, e.displayText() = DB::Exception: Unknown function VERSION. Maybe you meant: ['version']: While processing DATABASE(), connection_id(), VERSION() (version 21.3.2.5 (official build))
mysql> SELECT DATABASE(), connection_id(), version()/*!50038 , @@hostname*/;
+------------+-----------------+-----------+
| DATABASE() | connection_id() | version() |
+------------+-----------------+-----------+
| default    |               0 | 21.3.3.14  |
+------------+-----------------+-----------+
```

**Expected behavior**
VERSION() and CONNECTION_ID() aliases should work ;)

### PR DESCRIPTION
**Pull request by Slach**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added case insensitive aliases for `CONNECTION_ID()` and `VERSION()` functions. This fixes #22028

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Could you please add a test for these aliases?

File: src/Functions/connectionID.cpp [hunk 1]
```diff
@@ -34,7 +34,7 @@ class FunctionConnectionID : public IFunction
 
 void registerFunctionConnectionID(FunctionFactory & factory)
 {
-    factory.registerFunction<FunctionConnectionID>();
+    factory.registerFunction<FunctionConnectionID>(FunctionFactory::CaseInsensitive);
```
Comment (Slach) [inline src/Functions/connectionID.cpp:37]: @alexey-milovidov could you look to https://clickhouse-test-reports.s3.yandex.net/22042/769162765c71ab08f74afcab445a79327673c862/fast_test.html#fail1

I expect CONNECTION_ID should present
should I register all possible aliases in next line?

**Review by alexey-milovidov — APPROVED** [review]

File: src/Functions/connectionID.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply src/Functions/connectionID.cpp:37]: f4d014c
