### PR TITLE
Fix name for partition with a Bool value

### LINKED ISSUE #77297: Corrupted table with simple delete
### Describe the bug

This is a recent regression. Easy to reproduce.

### How to reproduce

Introduced in v25.2. Run Fiddle: https://fiddle.clickhouse.com/c1e4d3f9-499d-4f48-b9d6-1d069a42fe09

### Error message and/or stacktrace

Stack trace:
```
<Error> MergeTreeBackgroundExecutor: Exception while executing background task {a6463af2-6e21-4678-a478-e333830f11ee::0_1_1_0_2}: Code: 246. DB::Exception: While loading part /var/lib/clickhouse/store/a64/a6463af2-6e21-4678-a478-e333830f11ee/tmp_clone_0_1_1_0_2/: calculated partition ID: 5f5ddc1c16d86cf133ed0b4581dff31a differs from partition ID in part name: 0: Part contains files: serialization.json (85 bytes), default_compression_codec.txt (10 bytes), metadata_version.txt (1 bytes), checksums.txt (273 bytes), count.txt (1 bytes), partition.dat (1 bytes), data.bin (35 bytes), data.cmrk3 (48 bytes), columns.txt (47 bytes), minmax_c1.idx (2 bytes). (CORRUPTED_DATA), Stack trace (when copying this message, always include the lines below):

0. src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f252c9b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009ea49ec
2. src/Common/Exception.h:130: DB::Exception::Exception<String, String&, String&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String&>::type, std::type_identity<String&>::type>, String&&, String&, String&) @ 0x000000001229026b
3. src/Storages/MergeTree/IMergeTreeDataPart.cpp:1316: DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x00000000142072d8
4. src/Storages/MergeTree/MergeTreeData.cpp:7891: DB::MergeTreeData::cloneAndLoadDataPart(std::shared_ptr<DB::IMergeTreeDataPart const> const&, String const&, DB::MergeTreePartInfo const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::IDataPartStorage::ClonePartParams const&, DB::ReadSettings const&, DB::WriteSettings const&, bool) @ 0x0000000014357d44
5. src/Storages/MergeTree/MutateTask.cpp:2278: DB::MutateTask::prepare() @ 0x000000001453e072
6. src/Storages/MergeTree/MutateTask.cpp:2104: DB::MutateTask::execute() @ 0x000000001453be04
7. src/Storages/MergeTree/MutatePlainMergeTreeTask.cpp:100: DB::MutatePlainMergeTreeTask::executeStep() @ 0x00000000146d4baa
8. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:318: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x00000000142b870d
9. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000f3899db
10. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000f3905e2
11. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000f386c6f
12. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f38e09a
13. ? @ 0x00007435b0ca1e2e
14. ? @ 0x00007435b0d33a4c
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix name for partition with a Bool value. It was broken in https://github.com/ClickHouse/ClickHouse/pull/74533.

Closes https://github.com/ClickHouse/ClickHouse/issues/77297

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreePartition.cpp [hunk 1]
```diff
@@ -222,7 +222,7 @@ String MergeTreePartition::getID(const Block & partition_key_sample) const
     bool are_all_integral = true;
     for (const Field & field : value)
     {
-        if (field.getType() != Field::Types::UInt64 && field.getType() != Field::Types::Int64 && field.getType() != Field::Types::IPv4)
+        if (field.getType() != Field::Types::Bool && field.getType() != Field::Types::UInt64 && field.getType() != Field::Types::Int64 && field.getType() != Field::Types::IPv4)
```
Comment (Michicosun) [inline src/Storages/MergeTree/MergeTreePartition.cpp:225]: Why do you need this change?

If `read_bool_field_as_int = true` then bool will be deserialized using UInt8 serialization which will return UInt64 type and this should work?

Comment (Avogar) [reply src/Storages/MergeTree/MergeTreePartition.cpp:225]: It's not needed indeed, I forgot to remove this change after testing. Thanks

**Review by Michicosun — APPROVED** [review]
