### PR TITLE
Reduce memory usage for some formats when reading with s3/url/hdfs

### LINKED ISSUE #10461: Memory issue when importing Parquet data with S3 table function
Hello,
I'm trying to import parquet files from a S3 datalake into a Clickhouse MergeTree table.
The total size of the compressed parquet files is around 20GB distributed between ~200 files.
I'm running Clickhouse version 20.1.2.4 on a server with 32GB.
Since this version don't support wildcard with the S3 function I'm using a script like the following:
```sql
SET max_memory_usage=0;
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00000-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00001-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
INSERT INTO my_table SELECT * FROM s3('http://s3.amazonaws.com/bucket/path/part-00002-057cd7c2-2958-436f-864d-c32cef4fefea-c000.snappy.parquet', XXXXXX, YYYYYY, 'Parquet', 'id Int64, ...');
...
```
It easily reaches the default query memory limit, so the max_memory_usage needs to be raised/removed.
Most of the time it runs until it fills all the memory and get OOM killed and in fewer occasions it runs successfully.
The memory usage follows this sawtooth pattern:
Screenshot from 2020-04-17 15-59-09

I tried to use the wildcard with Clickhouse version 20.3.7.46 but it is worse than this current approach, the memory usage ramps up until the OOM, like if it was trying to load all files into RAM.

Are there any suggestion to improve this? Any way to force this flush to disk to free some memory between files?

Thanks in advance.

### LINKED ISSUE #16857: ORC + HDFS = memory limit exceeded
error：
```
DB::Exception: Memory limit (for query) exceeded: would use 256.34 GiB (attempt to allocate chunk of 206158431632 bytes), maximum: 186.26 GiB: While executing HDFS
```
set：
```
SET max_memory_usage =200000000000;
set max_bytes_before_external_group_by=100000000000;
set max_threads=1;
Set enable_scalar_subquery_optimization =0
Set distributed_aggregation_memory_efficient=1
```

execute sql:
```
SELECT phone , SUM(count) totalCount, count(1) days FROM tb_sql5and6 WHERE time >=20200707 AND time <= 20200731 
AND plate = '***' AND plate_type ='2' GROUP BY phone ORDER BY days DESC, totalCount DESC limit 100;
```
The same error is reported after the execution
table size：300GB
create table sql： 
```
CREATE TABLE tb_sql
(
plate String,
plate_type String,
phone String,
count Int32,
imsi String,
fullcount Int32,
time Int32
)
ENGINE = HDFS('hdfs://hacluster/user/clickhouse/table8', 'ORC')
```
ClickHouse client version 20.8.3.18.，

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reduce memory usage when reading with `s3` / `url` / `hdfs` formats `Parquet`, `ORC`, `Arrow` (controlled by setting `input_format_allow_seeks`, enabled by default). Also add setting `remote_read_min_bytes_for_seek` to control seeks. 
Closes https://github.com/ClickHouse/ClickHouse/issues/10461. Closes https://github.com/ClickHouse/ClickHouse/issues/16857.

This PR contains commits from https://github.com/ClickHouse/ClickHouse/pull/29894. Must be merged after.

```
:) SELECT sum(cityHash64(*)) FROM url('https://datasets.clickhouse.com/hits.parquet', 'Parquet','WatchID UInt64,  JavaEnable UInt8,  Title String,  GoodEvent Int16,  EventTime DateTime,  EventDate Date,  CounterID UInt32,  ClientIP UInt32,  ClientIP6 FixedString(16),  RegionID UInt32,  UserID UInt64,  CounterClass Int8,  OS UInt8,  UserAgent UInt8,  URL String,  Referer String,  URLDomain String,  RefererDomain String,  Refresh UInt8,  IsRobot UInt8,  RefererCategories Array(UInt16),  URLCategories Array(UInt16), URLRegions Array(UInt32),  RefererRegions Array(UInt32),  ResolutionWidth UInt16,  ResolutionHeight UInt16,  ResolutionDepth UInt8,  FlashMajor UInt8, FlashMinor UInt8,  FlashMinor2 String,  NetMajor UInt8,  NetMinor UInt8, UserAgentMajor UInt16,  UserAgentMinor FixedString(2),  CookieEnable UInt8, JavascriptEnable UInt8,  IsMobile UInt8,  MobilePhone UInt8,  MobilePhoneModel String,  Params String,  IPNetworkID UInt32,  TraficSourceID Int8, SearchEngineID UInt16,  SearchPhrase String,  AdvEngineID UInt8,  IsArtifical UInt8,  WindowClientWidth UInt16,  WindowClientHeight UInt16,  ClientTimeZone Int16,  ClientEventTime DateTime,  SilverlightVersion1 UInt8, SilverlightVersion2 UInt8,  SilverlightVersion3 UInt32,  SilverlightVersion4 UInt16,  PageCharset String,  CodeVersion UInt32,  IsLink UInt8,  IsDownload UInt8,  IsNotBounce UInt8,  FUniqID UInt64,  HID UInt32,  IsOldCounter UInt8, IsEvent UInt8,  IsParameter UInt8,  DontCountHits UInt8,  WithHash UInt8, HitColor FixedString(1),  UTCEventTime DateTime,  Age UInt8,  Sex UInt8,  Income UInt8,  Interests UInt16,  Robotness UInt8,  GeneralInterests Array(UInt16), RemoteIP UInt32,  RemoteIP6 FixedString(16),  WindowName Int32,  OpenerName Int32,  HistoryLength Int16,  BrowserLanguage FixedString(2),  BrowserCountry FixedString(2),  SocialNetwork String,  SocialAction String,  HTTPError UInt16, SendTiming Int32,  DNSTiming Int32,  ConnectTiming Int32,  ResponseStartTiming Int32,  ResponseEndTiming Int32,  FetchTiming Int32,  RedirectTiming Int32, DOMInteractiveTiming Int32,  DOMContentLoadedTiming Int32,  DOMCompleteTiming Int32,  LoadEventStartTiming Int32,  LoadEventEndTiming Int32, NSToDOMContentLoadedTiming Int32,  FirstPaintTiming Int32,  RedirectCount Int8, SocialSourceNetworkID UInt8,  SocialSourcePage String,  ParamPrice Int64, ParamOrderID String,  ParamCurrency FixedString(3),  ParamCurrencyID UInt16, GoalsReached Array(UInt32),  OpenstatServiceName String,  OpenstatCampaignID String,  OpenstatAdID String,  OpenstatSourceID String,  UTMSource String, UTMMedium String,  UTMCampaign String,  UTMContent String,  UTMTerm String, FromTag String,  HasGCLID UInt8,  RefererHash UInt64,  URLHash UInt64,  CLID UInt32,  YCLID UInt64,  ShareService String,  ShareURL String,  ShareTitle String,  ParsedParams Nested(Key1 String,  Key2 String, Key3 String, Key4 String, Key5 String,  ValueDouble Float64),  IslandID FixedString(16),  RequestNum UInt32,  RequestTry UInt8') settings input_format_allow_seeks=1;


:) select if(like(query, '%parquet%'), 'Parquet', 'ORC') as format, if(like(query, '%s3%'), 'S3', 'URL') as engine_type , Settings['input_format_allow_seeks'] as with_seeks, query_duration_ms / 1000 as query_duration_seconds, read_rows,  formatReadableSize(memory_usage),  formatReadableSize(read_bytes), formatReadableSize(ProfileEvents['S3ReadBytes']) as read_from_s3, ProfileEvents['ReadBufferSeekCancelConnection'] as seeks_with_reconnect  from system.query_log where memory_usage > 0 and read_bytes > 0 and notEmpty(with_seeks) and empty(exception) and type = 'QueryFinish' and read_rows > 8000000    order by format desc, engine_type, with_seeks, query_duration_seconds asc limit 2 by format, engine_type, with_seeks

┌─format──┬─engine_type─┬─with_seeks─┬─query_duration_seconds─┬─read_rows─┬─formatReadableSize(memory_usage)─┬─formatReadableSize(read_bytes)─┬─read_from_s3─┬─seeks_with_reconnect─┐
│ Parquet │ S3          │ 0          │                 41.161 │   8873898 │ 4.51 GiB                         │ 7.88 GiB                       │ 1.23 GiB     │                    0 │
│ Parquet │ S3          │ 0          │                 41.248 │   8873898 │ 4.51 GiB                         │ 7.88 GiB                       │ 1.23 GiB     │                    0 │
│ Parquet │ S3          │ 1          │                 33.209 │   8873898 │ 126.29 MiB                       │ 7.88 GiB                       │ 1.23 GiB     │                    7 │
│ Parquet │ S3          │ 1          │                 35.049 │   8873898 │ 130.75 MiB                       │ 7.88 GiB                       │ 1.23 GiB     │                    2 │
│ Parquet │ URL         │ 0          │                 45.619 │   8873898 │ 4.50 GiB                         │ 7.88 GiB                       │ 0.00 B       │                    0 │
│ Parquet │ URL         │ 0          │                 46.003 │   8873898 │ 4.50 GiB                         │ 7.88 GiB                       │ 0.00 B       │                    0 │
│ Parquet │ URL         │ 1          │                 46.093 │   8873898 │ 119.38 MiB                       │ 7.88 GiB                       │ 0.00 B       │                    2 │
│ Parquet │ URL         │ 1          │                 46.573 │   8873898 │ 119.38 MiB                       │ 7.88 GiB                       │ 0.00 B       │                    7 │
│ ORC     │ S3          │ 0          │                142.282 │   8873898 │ 9.00 GiB                         │ 7.88 GiB                       │ 3.67 GiB     │                    0 │
│ ORC     │ S3          │ 0          │                196.432 │   8873898 │ 9.00 GiB                         │ 7.88 GiB                       │ 3.67 GiB     │                    0 │
│ ORC     │ S3          │ 1          │                167.459 │   8873898 │ 158.32 MiB                       │ 7.88 GiB                       │ 3.76 GiB     │                  154 │
│ ORC     │ S3          │ 1          │                173.115 │   8873898 │ 158.32 MiB                       │ 7.88 GiB                       │ 3.76 GiB     │                  154 │
│ ORC     │ URL         │ 0          │                132.302 │   8873898 │ 9.00 GiB                         │ 7.88 GiB                       │ 0.00 B       │                    0 │
│ ORC     │ URL         │ 0          │                135.223 │   8873898 │ 9.00 GiB                         │ 7.88 GiB                       │ 0.00 B       │                    0 │
│ ORC     │ URL         │ 1          │                144.564 │   8873898 │ 154.43 MiB                       │ 7.88 GiB                       │ 0.00 B       │                  154 │
│ ORC     │ URL         │ 1          │                 148.05 │   8873898 │ 154.43 MiB                       │ 7.88 GiB                       │ 0.00 B       │                  154 │
└─────────┴─────────────┴────────────┴────────────────────────┴───────────┴──────────────────────────────────┴────────────────────────────────┴──────────────┴──────────────────────┘

```

### CODE REVIEW

**Comment by Avogar** [comment]
@kssenii can you resolve conflicts?

File: src/Processors/Formats/Impl/ORCBlockInputFormat.cpp [hunk 1]
```diff
@@ -39,23 +38,53 @@ Chunk ORCBlockInputFormat::generate()
...
+
+        NameToColumnPtr name_to_column_ptr;
+        for (const auto& column_name : column_names)
+        {
+            arrow::ArrayVector vec = {batch_result->GetColumnByName(column_name)};
+            std::shared_ptr<arrow::ChunkedArray> arrow_column = std::make_shared<arrow::ChunkedArray>(vec);
+            name_to_column_ptr[column_name] = arrow_column;
+        }
+        arrow_column_to_ch_column->arrowColumnsToCHChunk(res, name_to_column_ptr);
+        break;
```
Comment (Avogar) [inline src/Processors/Formats/Impl/ORCBlockInputFormat.cpp:85]: What is the reason of not using `arrowTableToCHChunk` as before? Now we create arrow table `table_result`, don't use it at all and create `name_to_column_ptr` from `batch_result`.

File: src/Processors/Formats/Impl/ORCBlockInputFormat.cpp [hunk 2]
```diff
@@ -39,23 +38,53 @@ Chunk ORCBlockInputFormat::generate()
...
-        throw ParsingException(ErrorCodes::CANNOT_READ_ALL_DATA,
-                               "Error while reading batch of ORC data: {}", table_result.status().ToString());
+        std::shared_ptr<arrow::RecordBatch> batch_result;
+        arrow::Status batch_status = batch_reader->ReadNext(&batch_result);
+        if (!batch_status.ok())
+            throw ParsingException(ErrorCodes::CANNOT_READ_ALL_DATA,
+                                   "Error while reading batch of ORC data: {}",
+                                   batch_status.ToString());
+
+        if (!batch_result || !batch_result->num_rows())
```
Comment (Avogar) [inline src/Processors/Formats/Impl/ORCBlockInputFormat.cpp:63]: Why do we reset batch_reader in case of empty batch? Does ampty batch mean end of stream too?

File: src/Processors/Formats/Impl/ORCBlockInputFormat.cpp [hunk 3]
```diff
@@ -39,23 +38,53 @@ Chunk ORCBlockInputFormat::generate()
...
+                                       reader_status.ToString());
+        }
 
-    std::shared_ptr<arrow::RecordBatch> batch_result;
-    arrow::Status batch_status = file_reader->ReadStripe(stripe_current, include_indices, &batch_result);
-    if (!batch_status.ok())
-        throw ParsingException(ErrorCodes::CANNOT_READ_ALL_DATA,
-                               "Error while reading batch of ORC data: {}", batch_status.ToString());
+        if (!batch_reader)
+            break;
```
Comment (Avogar) [inline src/Processors/Formats/Impl/ORCBlockInputFormat.cpp:54]: I think it would be better to move this under `if` in line 43 after checking `reader_status`

File: src/Processors/Formats/Impl/ORCBlockInputFormat.cpp [hunk 4]
```diff
@@ -39,23 +38,53 @@ Chunk ORCBlockInputFormat::generate()
     if (!file_reader)
         prepareReader();
 
-    if (stripe_current >= stripe_total)
-        return res;
+    while (true)
```
Comment (Avogar) [inline src/Processors/Formats/Impl/ORCBlockInputFormat.cpp:41]: Not important, but `generate` method now a bit difficult to read, maybe it would be better to split it into some small methods like `getNextBatchReader`, `getNextBatch`. If you don't think so or don't have time, just ignore it

File: src/Processors/Formats/Impl/ORCBlockInputFormat.cpp (hunk 1 above)
Comment (kssenii) [reply src/Processors/Formats/Impl/ORCBlockInputFormat.cpp:85]: My intention was to remove arrow::Table::FromRecordBatches at all because it doubles number of going throw rows, but after rewriting this part of code several times seems like I left arrow::Table::FromRecordBatches unremoved. Need to delete rows from 70-75.

**Review by Avogar — APPROVED** [review]

**Comment by kssenii** [comment]
`Integration tests (release) — fail: 1` -- `test_cross_replication/test.py::test` not related to changes
`Stateless tests (memory, actions) — fail: 1` --- `02010_lc_native` -- not related to changes
