### PR TITLE
`min_chunk_bytes_for_parallel_parsing` supposed to be non-zero always

### LINKED ISSUE #71110: BSONEachRow format with parallel parsing takes forever?
**Describe the bug**
An insert into table with primary key is taking forever when BSONEachRow format is used with `min_chunk_bytes_for_parallel_parsing = 0`.

**How to reproduce**
Run:

```sql
SET min_chunk_bytes_for_parallel_parsing = 0;
CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() PRIMARY KEY (c0);
INSERT INTO TABLE FUNCTION file('<path to file>', 'BSONEachRow', 'c0 Int') SELECT "number" FROM numbers(4);
INSERT INTO TABLE t0 (c0) FROM INFILE '<path to file>' FORMAT BSONEachRow; --takes forever
```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The setting `min_chunk_bytes_for_parallel_parsing` cannot be zero anymore. This fixes: https://github.com/ClickHouse/ClickHouse/issues/71110

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit c764922be29f53f4c2330948438c60ba7ad2cafd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75239/c764922be29f53f4c2330948438c60ba7ad2cafd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d819a5d0e4c4f9b1fe582ec61689c9a053c045d7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by davenger — APPROVED** [review]

File: tests/queries/0_stateless/03324_parallel_parsing_zero_bytes_buffer.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+#  shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+$CLICKHOUSE_LOCAL -q "desc file('$CUR_DIR/data_bson/c0_Int_10.bson')"
+
+$CLICKHOUSE_LOCAL -q """
+    DROP TABLE IF EXISTS t0;
+    CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() PRIMARY KEY (c0);
+    INSERT INTO TABLE t0 (c0) SELECT * FROM file('$CUR_DIR/data_bson/c0_Int_10.bson');
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/03324_parallel_parsing_zero_bytes_buffer.sh:12]: I initially wrote this test by just replicating the test case and didn't want to remove this afterwards.
