### PR TITLE
coordination: do not allow election_timeout_lower_bound_ms > election_timeout_upper_bound_ms

### LINKED ISSUE #32363: ClickHouse Keeper election_timeout_lower_bound_ms > election_timeout_upper_bound_ms breaks leader election.
**Unexpected behavior**
In ClickHouse Keeper config 
`<keeper_server>
    <coordination_settings>`

 when election_timeout_lower_bound_ms > election_timeout_upper_bound_ms seems that leader election doesn`t work. But if we watch the description from documentation:
election_timeout_lower_bound_ms — If the follower didn't receive heartbeats from the leader in this interval, then it **can** initiate leader election (default: 1000).
election_timeout_upper_bound_ms — If the follower didn't receive heartbeats from the leader in this interval, then it **must** initiate leader election (default: 2000).

**Expected behavior**
Initiate leader election tusing election_timeout_upper_bound_ms as **must** initiator or maybe some warning of incorrect election_timeout_lower_bound_ms value.

### PR DESCRIPTION
**Pull request by aiven-sal**
Closes #32363

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: src/Coordination/KeeperServer.cpp [hunk 1]
```diff
@@ -273,6 +273,13 @@ void KeeperServer::launchRaftServer(const Poco::Util::AbstractConfiguration & co
         coordination_settings->election_timeout_lower_bound_ms.totalMilliseconds(), "election_timeout_lower_bound_ms", log);
     params.election_timeout_upper_bound_ = getValueOrMaxInt32AndLogWarning(
         coordination_settings->election_timeout_upper_bound_ms.totalMilliseconds(), "election_timeout_upper_bound_ms", log);
+
+    if (params.election_timeout_lower_bound_ >= params.election_timeout_upper_bound_)
```
Comment (CheSema) [inline src/Coordination/KeeperServer.cpp:277]: Is it make sense to continue work? May be terminate execution?

For example, python has some restriction on arguments, if they break, programs fails to start.

Comment (CheSema) [reply src/Coordination/KeeperServer.cpp:277]: It is interesting. That code is triggered in our Fast Tests.

https://s3.amazonaws.com/clickhouse-test-reports/46274/fff2c09b87ce319c3b9e62c22cdf19a444a4c2fe/fast_test/server.log
`2023.02.13 12:42:27.884239 [ 19622 ] {} <Fatal> KeeperServer: election_timeout_lower_bound_ms is greater than election_timeout_upper_bound_ms, this would disable leader election completely.`

tests/config/config.d/keeper_port.xml 
```
            <!-- For instant start in single node configuration -->
            <heart_beat_interval_ms>0</heart_beat_interval_ms>
            <election_timeout_lower_bound_ms>0</election_timeout_lower_bound_ms>
            <election_timeout_upper_bound_ms>0</election_timeout_upper_bound_ms>
```

As I understand, that zero values are set just because there is the only one instance and the values are needless.

Comment (CheSema) [reply src/Coordination/KeeperServer.cpp]: I propose just pass zero values. The defaults are sensible 1s and 2s.
