### PR TITLE
Fix checkpoint in PeekableReadBuffer over ConcatReadBuffer

### LINKED ISSUE #19021: FORMAT CustomSeparated doesnt' work for http queries
(you don't have to strictly follow this form)

It seems that CH doesn't support  `FORMAT CustomSeparated` with http request
https://github.com/ClickHouse/ClickHouse/issues/12744#issuecomment-663738562

When I make a request with `format_custom_field_delimiter='^'`, I got an error
```
Code: 49, e.displayText() = DB::Exception: There is no checkpoint (version 20.1.2.4 (official build)) 
```
Bash script:
```
#!/bin/bash

find . -type f -name 'j.log' | while read f; do
  curl "http://localhost:8123
/?query=INSERT%20INTO%20mydb%20FORMAT%20CustomSeparated%20SETTINGS%20format_custom_escaping_rule%3D%27CSV%27%2C%20format_custom_field_delimiter%20%3D%20%27%5E%27" --data-binary "@${f}"
done
```
But all is OK, when I do it with client:
```
cat j.log |clickhouse-client  -q "INSERT into mydb FORMAT CustomSeparated SETTINGS format_custom_escaping_rule='CSV', format_custom_field_delimiter = '^'"
```

**How to reproduce**
* Which ClickHouse server version to use
 version 20.13.1.1 and github build `commit 6e34a0b71efc0e5af1cfb05b77a5e7b2568a2e49`
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE mydb
(
	datetime  String,
	d1 String,
	d2 String
)
engine=MergeTree()
ORDER BY d1
SETTINGS index_granularity = 8192;
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

j.log:
```
2021-Jan^d1^d2
```

* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `There is no checkpoint` error when inserting data through http interface using `Template` or `CustomSeparated` format.
Fixes #19021

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
> test_ttl_replicated/test.py::test_ttl_empty_parts

Fixed in master.

> 01149_zookeeper_mutation_stuck_after_replace_partition

Needs further investigation.

File: src/IO/PeekableReadBuffer.h [hunk 1]
```diff
@@ -38,7 +38,7 @@ class PeekableReadBuffer : public BufferWithOwnMemory<ReadBuffer>
             /// Don't need to store unread data anymore
             peeked_size = 0;
         }
-        checkpoint = pos;
+        checkpoint.emplace(pos);
 
         // FIXME: we are checking checkpoint existence in few places (rollbackToCheckpoint/dropCheckpoint)
```
Comment (abyss7) [inline src/IO/PeekableReadBuffer.h:43]: Does it still apply?

**Review by abyss7 — APPROVED** [review]

**Comment by tavplubix** [comment]
Functional stateless tests (release, wide parts enabled) - 01149_zookeeper_mutation_stuck_after_replace_partition - #19443
