### PR TITLE
Fix hashing of NULLs, attempt 3

### LINKED ISSUE #48365: AnyHash of arrays or tuples of nullable values
Currently these don't work:
```
SELECT cityHash64([1, null])
```
```
SELECT cityHash64((1, null))
```

In contrast, these work and return null:
```
SELECT cityHash64(null)
```
```
SELECT cityHash64(1, null)
```

What should the behavior be for arrays and tuples of nullables? Options:
 (a) Treat nulls as values, with some hash. Say that hash of null is some constant (chosen at random).
 (b) Null if any element is null.

(b) seems more consistent with typical behavior of nulls in SQL, like `cityHash64(1, null)` being null.

But (a) would be useful in practice for hashing whole tables or query results:
```
SELECT sum(cityHash64(tuple(*))) FROM (SELECT ...)
```

With (b), this would calculate a hash of the exact full results of the query, invariant to the order of rows (which is usually nondeterministic when using more than one thread). With (a), it can return the same hash for different data. E.g. if one column is always null, the whole sum of hashes will always be null, even if other columns contain actual nontrivial data.

Which one should we do? (a), (b), or something else?

### LINKED ISSUE #48623: Hash on array with NULL throws exception
```sql
CREATE TABLE test
(
    c Array(Nullable(Int64))
)
ENGINE = Memory;

INSERT INTO test VALUES (NULL) ([-1,NULL]);

SELECT xxHash32(c) FROM test
```

Produces
```
Received exception from server (version 23.4.1):
Code: 48. DB::Exception: Received from localhost:9001. DB::Exception: Method getDataAt is not supported for Nullable(Int64) in case if value is NULL: while executing 'FUNCTION xxHash32(a :: 0) -> xxHash32(a) UInt32 : 1'. (NOT_IMPLEMENTED)
```

This used to work until #40195.

See also #51541

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Hash functions now support NULLs inside arrays, tuples, and maps. (issues #48365 and #48623)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

Closes https://github.com/ClickHouse/ClickHouse/issues/48365
Closes https://github.com/ClickHouse/ClickHouse/issues/48623

Based on https://github.com/ClickHouse/ClickHouse/pull/58754 , which was based on https://github.com/ClickHouse/ClickHouse/pull/48625 . Hopefully this one will make it, this seems really useful for tests.

This shouldn't break compatibility because it only affects queries that would previously fail (refusing to hash an array/tuple/map with Nullable inside).

The somewhat error-prone behavior `hash(null, ...) == null` remains, but is easy to work around using `hash(tuple(...))`.

### CODE REVIEW

File: src/Functions/FunctionsHashing.h [hunk 1]
```diff
@@ -1201,6 +1207,74 @@ class FunctionAnyHash : public IFunction
...
+        if (const auto * col_from = checkAndGetColumn<ColumnNullable>(column))
+        {
+            const auto * nested_type = assert_cast<const DataTypeNullable &>(*from_type).getNestedType().get();
+            const auto & nested_col = col_from->getNestedColumn();
+
+            KeyType key {};
+            ToType null_hash;
+            if constexpr (Keyed)
+            {
+                /// Make the hash depend on key.
```
Comment (al13n321) [inline src/Functions/FunctionsHashing.h:1231]: Btw, I noticed two existing bugs: `sipHash128([])` has only lower 32 nonzero bits, and any keyed hash of `[]` doesn't depend on key:
```sql
SELECT reinterpret(sipHash128Keyed((number, number), []), 'UInt128')
FROM numbers(2)

Query id: 4a7f8a7f-c98b-4f41-897d-55d773e67fea

   ┌─reinterpret(⋯ 'UInt128')─┐
1. │               4249604106 │
2. │               4249604106 │
   └──────────────────────────┘
```
But idk how to fix it without breaking compatibility, guess we should leave it as is.

**Review by rschu1ze — APPROVED** [review]
