### PR TITLE
Fix race in `executeJob` when updating exception message

### LINKED ISSUE #62718: Data race at AsynchronousInsertQueue::processBatchDeadlines
Report: https://s3.amazonaws.com/clickhouse-test-reports/62297/e65dc63609f213ca2eb61221af8d6dbdb21c8b92/stress_test__tsan_.html

Thread:
```
WARNING: ThreadSanitizer: data race (pid=3169)
  Read of size 1 at 0x7b50023103a7 by thread T852 (mutexes: write M0):
    #0 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/string:1499:33 (clickhouse+0x1d0fb41f) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #1 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::size[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/string:968:17 (clickhouse+0x1d0fb41f)
    #2 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::empty[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/string:996:42 (clickhouse+0x1d0fb41f)
    #3 Poco::Exception::extendedMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./base/poco/Foundation/src/Exception.cpp:114:13 (clickhouse+0x1d0fb41f)
    #4 DB::Exception::addMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) <null> (clickhouse+0x7657351) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #5 DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:70:23 (clickhouse+0x194d59ad) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #6 DB::ExecutionThreadContext::executeTask() build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:95:9 (clickhouse+0x194d59ad)
    #7 DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273:26 (clickhouse+0x194c768f) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #8 DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:239:5 (clickhouse+0x194c768f)
    #9 DB::PipelineExecutor::executeImpl(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:411:9 (clickhouse+0x194c5e89) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #10 DB::PipelineExecutor::execute(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:111:9 (clickhouse+0x194c5b7e) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #11 DB::CompletedPipelineExecutor::execute() build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:110:18 (clickhouse+0x194c4339) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #12 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::FormatSettings> const&)>) build_docker/./src/Interpreters/executeQuery.cpp:1596:22 (clickhouse+0x17c426a8) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #13 DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) build_docker/./src/Server/HTTPHandler.cpp:906:5 (clickhouse+0x193b0c00) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #14 DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) build_docker/./src/Server/HTTPHandler.cpp:1113:9 (clickhouse+0x193b5635) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #15 DB::HTTPServerConnection::run() build_docker/./src/Server/HTTP/HTTPServerConnection.cpp:70:34 (clickhouse+0x19455e42) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #16 Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1cf86e02) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #17 Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1cf87671) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #18 Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14 (clickhouse+0x1d1893e6) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #19 Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x1d1876af) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #20 Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27 (clickhouse+0x1d185b69) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
```

Other thread:
```
  Previous write of size 8 at 0x7b50023103a0 by thread T1026 (mutexes: write M1):
    #0 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__set_long_cap[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/string:1592:37 (clickhouse+0x20505022) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #1 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__grow_by_and_replace(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char const*) build_docker/./contrib/llvm-project/libcxx/include/string:2367:5 (clickhouse+0x20505022)
    #2 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::append(char const*, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/string:2692:9 (clickhouse+0x20505022)
    #3 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::append[abi:v15000](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./contrib/llvm-project/libcxx/include/string:2812:12 (clickhouse+0x1d0fb4af) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #4 Poco::Exception::extendedMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./base/poco/Foundation/src/Exception.cpp:115:8 (clickhouse+0x1d0fb4af)
    #5 DB::Exception::addMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) <null> (clickhouse+0x7657351) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #6 DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:70:23 (clickhouse+0x194d59ad) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #7 DB::ExecutionThreadContext::executeTask() build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:95:9 (clickhouse+0x194d59ad)
    #8 DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273:26 (clickhouse+0x194c768f) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #9 DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:239:5 (clickhouse+0x194c768f)
    #10 DB::PipelineExecutor::executeImpl(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:411:9 (clickhouse+0x194c5e89) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #11 DB::PipelineExecutor::execute(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:111:9 (clickhouse+0x194c5b7e) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #12 DB::CompletedPipelineExecutor::execute() build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:110:18 (clickhouse+0x194c4339) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #13 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::FormatSettings> const&)>) build_docker/./src/Interpreters/executeQuery.cpp:1596:22 (clickhouse+0x17c426a8) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #14 DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) build_docker/./src/Server/HTTPHandler.cpp:906:5 (clickhouse+0x193b0c00) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #15 DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) build_docker/./src/Server/HTTPHandler.cpp:1113:9 (clickhouse+0x193b5635) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #16 DB::HTTPServerConnection::run() build_docker/./src/Server/HTTP/HTTPServerConnection.cpp:70:34 (clickhouse+0x19455e42) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #17 Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1cf86e02) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #18 Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1cf87671) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #19 Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14 (clickhouse+0x1d1893e6) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #20 Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x1d1876af) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #21 Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27 (clickhouse+0x1d185b69) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
```

Allocation:
```
  Location is heap block of size 480 at 0x7b5002310200 allocated by thread T717:
    #0 posix_memalign <null> (clickhouse+0x70e6185) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #1 std::__1::__libcpp_aligned_alloc[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxxabi/../libcxx/include/new:328:9 (clickhouse+0x20535c45) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #2 __cxxabiv1::__aligned_malloc_with_fallback(unsigned long) build_docker/./contrib/llvm-project/libcxxabi/src/fallback_malloc.cpp:215:20 (clickhouse+0x20535c45)
    #3 __cxa_allocate_exception build_docker/./contrib/llvm-project/libcxxabi/src/cxa_exception.cpp:190:17 (clickhouse+0x205335e5) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #4 void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) const build_docker/./src/Common/ThreadPool.cpp:175:13 (clickhouse+0xefc88f1) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #5 void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool) build_docker/./src/Common/ThreadPool.cpp:187:20 (clickhouse+0xefc2815) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #6 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleOrThrowOnError(std::__1::function<void ()>, Priority) build_docker/./src/Common/ThreadPool.cpp:279:5 (clickhouse+0xefc20ea) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #7 DB::AsynchronousInsertQueue::scheduleDataProcessingJob(DB::AsynchronousInsertQueue::InsertQuery const&, std::__1::unique_ptr<DB::AsynchronousInsertQueue::InsertData, std::__1::default_delete<DB::AsynchronousInsertQueue::InsertData>>, std::__1::shared_ptr<DB::Context const>, unsigned long) build_docker/./src/Interpreters/AsynchronousInsertQueue.cpp:287:14 (clickhouse+0x166be054) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
    #8 DB::AsynchronousInsertQueue::processBatchDeadlines(unsigned long) build_docker/./src/Interpreters/AsynchronousInsertQueue.cpp:660:13 (clickhouse+0x166c4d47) (BuildId: d2979013a1305e5011b5dde6564b478cd9aa711b)
```

Probably made visible by https://github.com/ClickHouse/ClickHouse/pull/62266 cc @tavplubix

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/62718

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 5c9427f6259bb5f83d8dd6ecbb27b4a98846299d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62972/5c9427f6259bb5f83d8dd6ecbb27b4a98846299d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Processors/Executors/ExecutionThreadContext.cpp [hunk 1]
```diff
@@ -67,7 +68,10 @@ static void executeJob(ExecutingGraph::Node * node, ReadProgressCallback * read_
     catch (Exception & exception)
     {
         if (checkCanAddAdditionalInfoToException(exception))
+        {
```
Comment (Algunenano) [inline src/Processors/Executors/ExecutionThreadContext.cpp:71]: Could you please explain what's going on?

Are multiple different threads throwing the same exception? How / why?

Do we need locking or do could we just copy the exception and change it, that is, change it to `catch (Exception exception)` instead of using a reference

Comment (Algunenano) [reply src/Processors/Executors/ExecutionThreadContext.cpp]: Uhmm, Looking at `rethrowExceptionIfHas` it seems that we should fix it there instead by doing a proper handling of the atomic variable (`has_exception`) with `compare_exchange_weak` or something similar. With the current code there is a race condition. WDYT?

Comment (tavplubix) [reply src/Processors/Executors/ExecutionThreadContext.cpp]: Hm, I meant `ExecutionThreadContext::rethrowExceptionIfHas()` (I don't see a race condition there), not `PushingAsyncPipelineExecutor::Data::rethrowExceptionIfHas()` (this looks suspicious). But I'm not familiar with this code and not sure which one actually throws

**Review by Algunenano — APPROVED** [review]

**Comment by tavplubix** [comment]
I love clang-tidy too:
```
Apr 25 19:28:17 /build/src/Processors/Executors/ExecutionThreadContext.cpp:67:12: error: catch handler catches by value; should catch by reference instead [cert-err09-cpp,cert-err61-cpp,misc-throw-by-value-catch-by-reference,-warnings-as-errors]
Apr 25 19:28:17    67 |     catch (Exception exception)
Apr 25 19:28:17       |            ^
Apr 25 19:28:17 20171 warnings generated.
```
