### PR TITLE
Lz4 compression: buffer block in a rare case

### LINKED ISSUE #50975: Lz4DeflatingWriteBuffer works with S3 incorrectly
Lz4DeflatingWriteBuffer writes compressed data directly to the working_buffer of below buffer bypassing write method.

Here Lz4DeflatingWriteBuffer checks if below buffer has enough space. Lz4DeflatingWriteBuffer makes _wrong_ assumption that calling `out->next();` increases the space. Actually that call do no-op if there is still some space left.

https://github.com/ClickHouse/ClickHouse/blob/e2d8299b232635210916fea3c18bf04351151aed/src/IO/Lz4DeflatingWriteBuffer.cpp#L63-L68

As a result Lz4DeflatingWriteBuffer ends up with exception (I added more details to the string):
```
2023.06.14 10:47:03.082967 [ 8 ] {INSERT_INTO_TABLE_FUNCTION_FAIL_UPLOAD_PART_lz4} <Error> TCPHandler: Code: 617. DB::Exception: LZ4 failed to encode stream. LZ4F version: 100, CodeName: ERROR_dstMaxSize_tooSmall, in_capacity: 1048497, out_capacity: 6, cur_buffer_size: 1048497, min_compressed_block_size: 9. (LZ4_ENCODER_FAILED), Stack trace (when copying this message, always include the lines below):
```

### PR DESCRIPTION
**Pull request by CheSema**
fixes https://github.com/ClickHouse/ClickHouse/issues/50975

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Lz4 compression. Buffer compressed block in a rare case when out buffer capacity is not enough for writing compressed block directly to out's buffer.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 5510dd8e7d991994ed4b9017ac3cbbea490aa1cf with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56938/5510dd8e7d991994ed4b9017ac3cbbea490aa1cf/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6906569241">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56938/5510dd8e7d991994ed4b9017ac3cbbea490aa1cf/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/IO/Lz4DeflatingWriteBuffer.cpp [hunk 1]
```diff
@@ -54,107 +109,76 @@ void Lz4DeflatingWriteBuffer::nextImpl()
...
-                    "LZ4 failed to encode stream. LZ4F version: {}",
-                    LZ4F_VERSION);
+        if (LZ4F_isError(compressed_size))
+            throw Exception(
+                ErrorCodes::LZ4_ENCODER_FAILED,
+                "LZ4 failed to encode stream. LZ4F version: {}, error {}, out_capacity {}",
+                LZ4F_VERSION, LZ4F_getErrorName(compressed_size), sink.getCapacity());
 
-            in_capacity -= cur_buffer_size;
-            in_data = reinterpret_cast<void *>(working_buffer.end() - in_capacity);
```
Comment (CheSema) [inline src/IO/Lz4DeflatingWriteBuffer.cpp:115]: I do not know how did it work.
`in_data = reinterpret_cast<void *>(working_buffer.end() - in_capacity);`
It could be correct only in one case. When next is called only for fully filled buffer. Fully filled buffer is the buffer with `0 == available()`.

**Comment by CheSema** [comment]
test_backward_compatibility/test_functions.py::test_string_functions is flaky
https://github.com/ClickHouse/ClickHouse/issues/56969

**Review by antonio2368 — APPROVED** [review]

**Comment by CheSema** [comment]
test_replicated_merge_tree_encryption_codec/test.py::test_different_keys was flaky https://github.com/ClickHouse/ClickHouse/pull/56768 but might be fixed in master.
