### PR TITLE
Fix bug with background moves in zero copy replication

### LINKED ISSUE #33643: Zero copy replication can lead to data duplication in case of background moves
I've added a test that reproduces the error https://github.com/ClickHouse/ClickHouse/pull/33642.

### PR DESCRIPTION
**Pull request by alesapin**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug in zero copy replication which lead to data duplication in case of TTL move. Fixes #33643.

### CODE REVIEW

**Comment by alesapin** [comment]
Unfortunately reproduce the error in about 5% of cases.

**Comment by alesapin** [comment]
```=========================== short test summary info ============================
FAILED test_s3_zero_copy_ttl/test.py::test_ttl_move_and_s3 - assert 320 == 300
=================== 1 failed, 1 warning in 68.42s (0:01:08) ====================
```

File: src/Common/ZooKeeper/ZooKeeperLock.cpp [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+    if (zookeeper->expired())
+    {
+        LOG_WARNING(log, "Lock is lost, because session was expired. Path: {}, message: {}", lock_path, lock_message);
+        return;
+    }
+
+    Coordination::Stat stat;
+    std::string dummy;
+    /// NOTE It will throw if session expired after we checked it above
+    bool result = zookeeper->tryGet(lock_path, dummy, &stat);
```
Comment (ianton-ru) [inline src/Common/ZooKeeper/ZooKeeperLock.cpp:60]: zookeeper->exists(lock_path, &stat) is be better when we need no node value.

**Review by ianton-ru — CHANGES_REQUESTED** [review]

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 2]
```diff
@@ -5535,8 +5537,40 @@ bool MergeTreeData::moveParts(const CurrentlyMovingPartsTaggerPtr & moving_tagge
...
+            /// If zero-copy replication enabled than replicas shouldn't try to
+            /// move parts to another disk simultaneously. For this purpose we
+            /// use shared lock across replicas. NOTE: it's not 100% reliable,
+            /// because we are not checking lock while finishing part move.
+            /// However it's not dangerous at all, we will just have very rare
+            /// copies of some part.
+            ///
+            /// FIXME: this code is related to Replicated merge tree, and not
+            /// common for ordinary merge tree. So it's a bad design and should
+            /// be fixed.
```
[the remark this answers is not in the document]
Comment (alesapin) [reply src/Storages/MergeTree/MergeTreeData.cpp:5549]: Not sure

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 3]
```diff
@@ -5548,7 +5584,7 @@ bool MergeTreeData::moveParts(const CurrentlyMovingPartsTaggerPtr & moving_tagge
             throw;
         }
     }
-    return true;
+    return result;
```
Comment (ianton-ru) [inline src/Storages/MergeTree/MergeTreeData.cpp:5587]: At first iteration some tests failed with exception "Cannot move parts because moves are manually disabled". This exception throws from MergeTreeData::movePartitionToVolume and MergeTreeData::movePartitionToDisk when MergeTreeData::movePartsToSpace (with "return moveParts" inside) returns false. I forget which test failed with this error but looks like it should be fail in current version too. But now all tests passed (except one timeout). Is's stange.

Comment (ianton-ru) [reply src/Storages/MergeTree/MergeTreeData.cpp:5587]: I missed that failed test was for non-replicated MergeTree, it's fixed now.

Comment (alesapin) [reply src/Storages/MergeTree/MergeTreeData.cpp:5587]: Discussed in TG problem fixed by `supportsReplication` flag.

**Review by ianton-ru — APPROVED** [review]

**Comment by alesapin** [comment]
Segfault reported: https://github.com/ClickHouse/ClickHouse/issues/33741
