### PR TITLE
Analyzer: prefer column name to alias from array join

### LINKED ISSUE #59894: Unexpected return type on join condition
Report: https://s3.amazonaws.com/clickhouse-test-reports/59857/13e38772546237e94864a55d6ea1ad58e1188591/ast_fuzzer__asan_.html

```
CREATE TABLE test_table (`id` UInt64, `value` String, `value_array` Array(UInt64)) ENGINE = MergeTree() ORDER BY id;

SELECT
    toFixedString(toFixedString('OK', 2), 2),
    toNullable(toFixedString('OK', 2)),
    *
FROM
(
    SELECT
        toFixedString('OK', 2)
) AS subquery ARRAY JOIN [0] AS id INNER JOIN test_table USING (id) WHERE materialize(id) SETTINGS allow_experimental_analyzer=1;
```

Result:
```
2024.02.12 16:19:10.702575 [ 369894 ] {22e4db5f-b4c7-463d-8c07-f728638ef1b5} <Fatal> : Logical error: 'Unexpected return type from materialize. Expected UInt8. Got UInt64'.
```

The expected would be something like:
```
Code: 59. DB::Exception: Illegal type UInt64 of column materialize(__table1.id) for filter. Must be UInt8 or Nullable(UInt8). (ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER)
```

We get the expected errors on other conditions (normal join) or without the analyzer, but something in this query avoids this check and it ends up calling `materialize` with an unexpected type/header.

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Close https://github.com/ClickHouse/ClickHouse/issues/59894

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 64dba76afe7d5fd423617b7370e5ccacadcd60e2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62995/64dba76afe7d5fd423617b7370e5ccacadcd60e2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
> Stateless tests (aarch64) — Tests are not finished, fail: 3, passed: 3366, skipped: 16 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62995/3a8ca9a68b01c922e6f7a802e603e10006b8fdcc/stateless_tests__aarch64_.html)

https://github.com/ClickHouse/ClickHouse/issues/60460

> Stateless tests (coverage) [3/6] — fail: 1, passed: 1061, skipped: 3 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62995/3a8ca9a68b01c922e6f7a802e603e10006b8fdcc/stateless_tests__coverage__[3_6].html)
> Stateless tests (coverage) [5/6] — Tests are not finished, fail: 0, passed: 688, skipped: 2 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62995/3a8ca9a68b01c922e6f7a802e603e10006b8fdcc/stateless_tests__coverage__[5_6].html)
> Stateless tests (coverage) [6/6] — fail: 1, passed: 1059, skipped: 1 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62995/3a8ca9a68b01c922e6f7a802e603e10006b8fdcc/stateless_tests__coverage__[6_6].html)

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -4096,6 +4096,21 @@ IdentifierResolveResult QueryAnalyzer::tryResolveIdentifier(const IdentifierLook
...
+             * SELECT id FROM ( SELECT ... ) AS subquery ARRAY JOIN [0] AS id INNER JOIN second_table USING (id)
+             * In the example, identifier `id` should be resolved into one from USING (id) column.
+             */
+            auto alias_it = scope.alias_name_to_expression_node.find(identifier_lookup.identifier.getFullName());
+            if (alias_it != scope.alias_name_to_expression_node.end() && alias_it->second->getNodeType() == QueryTreeNodeType::COLUMN)
+            {
+                const auto & column_node = alias_it->second->as<ColumnNode &>();
+                if (column_node.getColumnSource()->getNodeType() == QueryTreeNodeType::ARRAY_JOIN)
+                    prefer_column_name_to_alias = true;
+            }
```
Comment (SmitaRKulkarni) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:4111]: If we are not able to find the expression `(i.e alias_it == scope.alias_name_to_expression_node.end())` , should we throw error ?

Comment (vdimir) [reply src/Analyzer/Passes/QueryAnalysisPass.cpp:4111]: Not really, because the same method is used to resolve any identifer, so we need to go further in case it's not from `ARRAY JOIN`

**Review by SmitaRKulkarni — APPROVED** [review]
