### PR TITLE
Verify array offsets received over network

### LINKED ISSUE #81199: Missing validation for data send by an external client
### Company or project name

[Tenzir](https://tenzir.com/) ([github](https://github.com/tenzir/tenzir))

We have an integration that sends data to ClickHouse using `clickhouse-cpp`.

### Describe what's wrong

During the development/debugging of our integration, I discovered that sending `Array(T)` with invalid value- and offset-array combinations would cause various issues in the ClickHouse server.

* Sending too much data for the given offsets would cause the server to start interpreting the excess values as new commands to the server. This is obviously **very bad** and should never happen. The server needs to do some validation for this.
* Sending too few values for the given offsets would cause the server to wait for a timeout, expecting more data. I am not sure if this is addressable, as I have not looked into how the transfer protocol actually works
* Sending an non-monotonous offset-array is possible. This produces the table state in ClickHouse you would "expect", but probably should not be legal.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

I have already introduced a fix for this in the clickhouse-cpp repo, which can be found here: https://github.com/ClickHouse/clickhouse-cpp/pull/428. 

A C++ reproduction code can be found in this PR as well: https://github.com/ClickHouse/clickhouse-cpp/pull/428#issuecomment-2934661398

However, at the very least the first issue should be addressed in the ClickHouse server itself.

### Expected behavior

The server should validate data it gets from some client.

### Error message and/or stacktrace

Some server logs from my failed attempts can be found in my original issue https://github.com/ClickHouse/clickhouse-cpp/issues/426

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Verify array offsets received over network

Otherwise it can lead to:

    DB::Exception: Array size is too large: 18446744073709551615: while reading column col at /src/ch/clickhouse/.cmake/.server/store/bd6/bd64f151-1ade-459c-87ac-5d042bf14a55/

Fixes: https://github.com/ClickHouse/ClickHouse/issues/81199

### CODE REVIEW

File: src/DataTypes/Serializations/SerializationArray.cpp [hunk 1]
```diff
@@ -375,6 +378,19 @@ void SerializationArray::deserializeBinaryBulkWithMultipleStreams(
         else
             SerializationNumber<ColumnArray::Offset>().deserializeBinaryBulk(column_array.getOffsetsColumn(), *stream, 0, rows_offset + limit, 0);
 
+        /// Verify offsets if the data comes over the network
```
Comment (Algunenano) [inline src/DataTypes/Serializations/SerializationArray.cpp:381]: Few questions:
* Do you know if we do or need other validations, like checking the offsets finish where the data finishes and so on?
* Is this the only path data from network might take to deserialize into an Array?
* Can we add some minor test like sending malformed data and verify it fails? I guess we can do something like `echo "" | xxd | curl`

Comment (azat) [reply src/DataTypes/Serializations/SerializationArray.cpp:381]: > Do you know if we do or need other validations, like checking the offsets finish where the data finishes and so on?

There are bunch of checks already, but this one was missing. So AFAICS after this one it will not be possible to INSERT incorrect data that will pops up only during reading the column

> Is this the only path data from network might take to deserialize into an Array?

Array - yes.

> Can we add some minor test like sending malformed data and verify it fails? I guess we can do something like echo "" | xxd | curl

Test added and undrafted

File: tests/queries/0_stateless/03533_column_array_insert_broken_offsets.sh [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+$CLICKHOUSE_CLIENT 'create table array_deserialize_offsets (val Array(String)) engine=Memory()'
+
+{
+  # Native header
+  chc "select * from values('val Array(String)', (['foo','fooo']),(['bar','barr'])) format Native" | head -c20
```
Comment (Algunenano) [inline tests/queries/0_stateless/03533_column_array_insert_broken_offsets.sh]: I don't think we can use `chc` in tests since it's missing client config (or might not be in the PATH). In any case it might be better to just use `${CLICKHOUSE_LOCAL}` instead

Comment (azat) [reply tests/queries/0_stateless/03533_column_array_insert_broken_offsets.sh]: Thanks (that was a working copy that not supposed to go to the remote)

**Comment by azat** [comment]
>[Bugfix validation](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=81269&sha=275cc44b34c6948f97479fbb19140a5c3e0dae03&name_0=PR&name_1=Bugfix%20validation)

```
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://github.com/ClickHouse/ClickHouse/releases/download/v25.5.2.47-stable/clickhouse-common-static-dbg_25.5.2.47_amd64.deb
```

>[Stateless tests (debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=81269&sha=275cc44b34c6948f97479fbb19140a5c3e0dae03&name_0=PR&name_1=Stateless%20tests%20%28debug%29) — Some tests restarted, fail: 1, passed: 7913, skipped: 120

- `03002_part_log_rmt_fetch_merge_error` - https://github.com/ClickHouse/ClickHouse/pull/81547

**Review by Algunenano — APPROVED** [review]
