### PR TITLE
PR: fix INSERT into source table for MV with JOINS

### LINKED ISSUE #89742: PR: INSERT INTO materialized view with JOINS
### Describe the unexpected behaviour

It fails

### How to reproduce

```sql
CREATE TABLE n1 (key UInt64, value String) ENGINE = MergeTree ORDER BY key SETTINGS index_granularity=1;

CREATE TABLE n2 (key UInt64, value Int64) ENGINE = MergeTree ORDER BY key SETTINGS index_granularity=1;

CREATE TABLE n1_n2_join (k UInt64, v1 String, v2 Int64) ENGINE = MergeTree ORDER BY k;

CREATE MATERIALIZED VIEW mv TO n1_n2_join
AS SELECT n1.key as k, n1.value as v1, n2.value as v2 from n1 JOIN n2 ON n1.key = n2.key ORDER BY n1.key;

INSERT INTO n2 SELECT number, -number FROM numbers(10);

SET enable_parallel_replicas=1, max_parallel_replicas=3, cluster_for_parallel_replicas='test_cluster_one_shard_three_replicas_localhost', parallel_replicas_for_non_replicated_merge_tree=1;

-- this INSERT triggers JOIN in the materialized view, it fails with parallel replicas
INSERT INTO n1 SELECT number as key, toString(key) FROM numbers(10);
```
Fails differently depending on `query_plan_use_logical_join_step` setting
`query_plan_use_logical_join_step` enabled (default)
```
<Error> executeQuery: Code: 10. DB::Exception: Columns [__table2.key] are not found in blocks [__table1.key, __table1.value], [__table1.key, __table1.value, __table2.value]: while pushing to view default.mv. (NOT_FOUND_COLUMN_IN_BLOCK) (version 25.11.1.1) (from 127.0.0.1:48512) (query 1, line 1) (in query: INSERT INTO n1 SELECT number as key, toString(key) FROM numbers(10)), Stack trace (when copying this message, always include the lines below):
```
https://pastila.nl/?0014b72b/5b2e8d8e4419354dd733528ed5595dc1#TLOyOR6K7A4rZsY9O8KGYg==

`query_plan_use_logical_join_step` disabled
```
<Error> executeQuery: Code: 1. DB::Exception: JOIN  INNER JOIN ... ON n1.key = n2.key right table expression expected to process query to fetch columns stage. Actual WithMergeableState: while pushing to view default.mv. (UNSUPPORTED_METHOD) (version 25.11.1.1) (from 127.0.0.1:48512) (query 1, line 1) (in query: INSERT INTO n1 SELECT number as key, toString(key) FROM numbers(10) settings query_plan_use_logical_join_step=0), Stack trace (when copying this message, always include the lines below):
```
https://pastila.nl/?003d57b9/2e6030b572db02d47a360fff1576fa52#2eJR1gQSm/RxoeLRlv+pew==

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Details

Closes https://github.com/ClickHouse/ClickHouse/issues/89742

### CODE REVIEW

File: src/Planner/PlannerJoinTree.cpp [hunk 1]
```diff
@@ -1081,13 +1083,22 @@ JoinTreeQueryPlan buildQueryPlanForTableExpression(QueryTreeNodePtr table_expres
                         if (!join_node)
                             return true;
 
+                        const auto & left_table_expr = join_node->getLeftTableExpression();
+                        // don't allow parallel replicas with strange storages
+                        if (left_table_expr->getNodeType() == QueryTreeNodeType::TABLE)
+                        {
+                            const auto * left_table_node = left_table_expr->as<TableNode>();
+                            // Context: INSERT INTO a table with dependent materialized view (the mv with JOIN)
+                            // For some reason, the left table is wrapped up into StorageValues before execute the JOIN
```
Comment (vdimir) [inline src/Planner/PlannerJoinTree.cpp]: I suppose when we wrap the left table on MV insert, we join not the whole table over and over again, but rather only the inserted block.

Should parallel replicas actually already be disabled for everything except MergeTree?

**Review by vdimir — COMMENTED** [review]
Changelog entry can be

```
- Disable parallel replicas for JOINs during inserts into tables with dependent Materialized Views
```

**Review by vdimir — COMMENTED** [review]
Changelog entry can be

```
- Disable parallel replicas for all `INSERT SELECT` queries
 
```

What are the reasons, other than the bug with JOINs, not to use parallel replicas for INSERT SELECTs?

**Comment by devcrafter** [comment]
> What are the reasons, other than the bug with JOINs, not to use parallel replicas for INSERT SELECTs?

I've updated the change, - now we disable parallel replicas for inserts it's not case for distributed insert select
