### PR TITLE
Fix duplicate usage of table function input().

### LINKED ISSUE #55740: Segfault when input function in subquery
Clickhouse dies with segmentation fault on an insert query.

Verified on latest version. 
logs:
```
2023.10.17 12:51:29.252885 [ 331 ] {} <Trace> BaseDaemon: Received signal 11
2023.10.17 12:51:29.253180 [ 623 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.10.17 12:51:29.253246 [ 623 ] {} <Fatal> BaseDaemon: (version 23.9.1.1854 (official build), build id: EAC4523EFE21EC9D2EE1374198D8644F4B8F083F, git hash: 8f9a227de1f530cdbda52c145d41a6b0f1d29961) (from thread 332) Received signal 11
2023.10.17 12:51:29.253294 [ 623 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.10.17 12:51:29.253317 [ 623 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.10.17 12:51:29.253349 [ 623 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000012895e8c 0x00000000127d7559 0x00000000120bac48 0x00000000120a31a8 0x00000000120a25b3 0x00000000121446f6 0x0000000011918cfc 0x0000000011915269 0x0000000011908f55 0x00000000118e67fb 0x00000000118f0769 0x00000000120b0a43 0x00000000120a178d 0x00000000120945f1 0x0000000012140858 0x0000000012b2a534 0x00000000120bac48 0x00000000120a31a8 0x00000000120a25b3 0x00000000121446f6 0x0000000012073365 0x0000000012073272 0x000000001206e01c 0x000000001249cf96 0x000000001249fe01 0x00000000132e7054 0x00000000132eb644 0x000000001335ea52 0x0000000015d33b34 0x0000000015d34d31 0x0000000015e40387 0x0000000015e3e61c 0x00007f8b24c84609 0x00007f8b24ba9133
2023.10.17 12:51:29.253376 [ 623 ] {} <Fatal> BaseDaemon: ########################################
2023.10.17 12:51:29.253413 [ 623 ] {} <Fatal> BaseDaemon: (version 23.9.1.1854 (official build), build id: EAC4523EFE21EC9D2EE1374198D8644F4B8F083F, git hash: 8f9a227de1f530cdbda52c145d41a6b0f1d29961) (from thread 332) (query_id: 3ea41051-1a5b-4a92-a162-2a9555fa143f) (query: INSERT INTO ts_data_double_raw (device_id, data_item_id, data_time, data_value, is_deleted, ingestion_time)
SELECT
   device_id,
   data_item_id,
   data_time,
   data_value,
   1,  -- mark as deleted
   fromUnixTimestamp64Milli(1697547088995, 'UTC') -- all inserted records have new ingestion time
FROM ts_data_double
WHERE (device_id = 100) AND (data_item_id = 1)
    AND (data_time >= fromUnixTimestamp64Milli(0, 'UTC'))
    AND (data_time <= fromUnixTimestamp64Milli(1697547086764, 'UTC'))
    AND version < fromUnixTimestamp64Milli(1697547088995, 'UTC')
    AND (toUnixTimestamp64Milli(data_time) IN (SELECT timestamp FROM input('timestamp UInt64'))) SETTINGS insert_quorum=1
 FORMAT RowBinary
) Received signal Segmentation fault (11)
2023.10.17 12:51:29.253446 [ 623 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.10.17 12:51:29.253472 [ 623 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000012895e8c 0x00000000127d7559 0x00000000120bac48 0x00000000120a31a8 0x00000000120a25b3 0x00000000121446f6 0x0000000011918cfc 0x0000000011915269 0x0000000011908f55 0x00000000118e67fb 0x00000000118f0769 0x00000000120b0a43 0x00000000120a178d 0x00000000120945f1 0x0000000012140858 0x0000000012b2a534 0x00000000120bac48 0x00000000120a31a8 0x00000000120a25b3 0x00000000121446f6 0x0000000012073365 0x0000000012073272 0x000000001206e01c 0x000000001249cf96 0x000000001249fe01 0x00000000132e7054 0x00000000132eb644 0x000000001335ea52 0x0000000015d33b34 0x0000000015d34d31 0x0000000015e40387 0x0000000015e3e61c 0x00007f8b24c84609 0x00007f8b24ba9133
2023.10.17 12:51:29.253573 [ 623 ] {} <Fatal> BaseDaemon: 2. DB::StorageInput::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x0000000012895e8c in /usr/bin/clickhouse
2023.10.17 12:51:29.253612 [ 623 ] {} <Fatal> BaseDaemon: 3. DB::IStorage::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x00000000127d7559 in /usr/bin/clickhouse
2023.10.17 12:51:29.253655 [ 623 ] {} <Fatal> BaseDaemon: 4. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x00000000120bac48 in /usr/bin/clickhouse
2023.10.17 12:51:29.253705 [ 623 ] {} <Fatal> BaseDaemon: 5. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x00000000120a31a8 in /usr/bin/clickhouse
2023.10.17 12:51:29.253743 [ 623 ] {} <Fatal> BaseDaemon: 6. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000120a25b3 in /usr/bin/clickhouse
2023.10.17 12:51:29.253840 [ 623 ] {} <Fatal> BaseDaemon: 7. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000121446f6 in /usr/bin/clickhouse
2023.10.17 12:51:29.253875 [ 623 ] {} <Fatal> BaseDaemon: 8. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x0000000011918cfc in /usr/bin/clickhouse
2023.10.17 12:51:29.253910 [ 623 ] {} <Fatal> BaseDaemon: 9. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x0000000011915269 in /usr/bin/clickhouse
2023.10.17 12:51:29.253956 [ 623 ] {} <Fatal> BaseDaemon: 10. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::shared_ptr<DB::IAST> const>::doVisit(std::shared_ptr<DB::IAST> const&) @ 0x0000000011908f55 in /usr/bin/clickhouse
2023.10.17 12:51:29.253994 [ 623 ] {} <Fatal> BaseDaemon: 11. DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ActionsDAG>&, bool) @ 0x00000000118e67fb in /usr/bin/clickhouse
2023.10.17 12:51:29.254028 [ 623 ] {} <Fatal> BaseDaemon: 12. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::shared_ptr<DB::FilterDAGInfo> const&, std::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x00000000118f0769 in /usr/bin/clickhouse
2023.10.17 12:51:29.254074 [ 623 ] {} <Fatal> BaseDaemon: 13. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x00000000120b0a43 in /usr/bin/clickhouse
2023.10.17 12:51:29.254142 [ 623 ] {} <Fatal> BaseDaemon: 14. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>)::$_0::operator()(bool) const @ 0x00000000120a178d in /usr/bin/clickhouse
2023.10.17 12:51:29.254191 [ 623 ] {} <Fatal> BaseDaemon: 15. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x00000000120945f1 in /usr/bin/clickhouse
2023.10.17 12:51:29.254236 [ 623 ] {} <Fatal> BaseDaemon: 16. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000012140858 in /usr/bin/clickhouse
2023.10.17 12:51:29.254283 [ 623 ] {} <Fatal> BaseDaemon: 17. DB::StorageView::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x0000000012b2a534 in /usr/bin/clickhouse
2023.10.17 12:51:29.254310 [ 623 ] {} <Fatal> BaseDaemon: 18. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x00000000120bac48 in /usr/bin/clickhouse
2023.10.17 12:51:29.254343 [ 623 ] {} <Fatal> BaseDaemon: 19. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x00000000120a31a8 in /usr/bin/clickhouse
2023.10.17 12:51:29.254376 [ 623 ] {} <Fatal> BaseDaemon: 20. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000120a25b3 in /usr/bin/clickhouse
2023.10.17 12:51:29.254416 [ 623 ] {} <Fatal> BaseDaemon: 21. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000121446f6 in /usr/bin/clickhouse
2023.10.17 12:51:29.254454 [ 623 ] {} <Fatal> BaseDaemon: 22. DB::IInterpreterUnionOrSelectQuery::buildQueryPipeline(DB::QueryPlan&) @ 0x0000000012073365 in /usr/bin/clickhouse
2023.10.17 12:51:29.254484 [ 623 ] {} <Fatal> BaseDaemon: 23. DB::IInterpreterUnionOrSelectQuery::buildQueryPipeline() @ 0x0000000012073272 in /usr/bin/clickhouse
2023.10.17 12:51:29.254521 [ 623 ] {} <Fatal> BaseDaemon: 24. DB::InterpreterInsertQuery::execute() @ 0x000000001206e01c in /usr/bin/clickhouse
2023.10.17 12:51:29.254568 [ 623 ] {} <Fatal> BaseDaemon: 25. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001249cf96 in /usr/bin/clickhouse
2023.10.17 12:51:29.254607 [ 623 ] {} <Fatal> BaseDaemon: 26. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001249fe01 in /usr/bin/clickhouse
2023.10.17 12:51:29.254643 [ 623 ] {} <Fatal> BaseDaemon: 27. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x00000000132e7054 in /usr/bin/clickhouse
2023.10.17 12:51:29.254685 [ 623 ] {} <Fatal> BaseDaemon: 28. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000132eb644 in /usr/bin/clickhouse
2023.10.17 12:51:29.254734 [ 623 ] {} <Fatal> BaseDaemon: 29. DB::HTTPServerConnection::run() @ 0x000000001335ea52 in /usr/bin/clickhouse
2023.10.17 12:51:29.254824 [ 623 ] {} <Fatal> BaseDaemon: 30. Poco::Net::TCPServerConnection::start() @ 0x0000000015d33b34 in /usr/bin/clickhouse
2023.10.17 12:51:29.254859 [ 623 ] {} <Fatal> BaseDaemon: 31. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015d34d31 in /usr/bin/clickhouse
2023.10.17 12:51:29.254892 [ 623 ] {} <Fatal> BaseDaemon: 32. Poco::PooledThread::run() @ 0x0000000015e40387 in /usr/bin/clickhouse
2023.10.17 12:51:29.254930 [ 623 ] {} <Fatal> BaseDaemon: 33. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e3e61c in /usr/bin/clickhouse
2023.10.17 12:51:29.254959 [ 623 ] {} <Fatal> BaseDaemon: 34. ? @ 0x00007f8b24c84609 in ?
2023.10.17 12:51:29.254985 [ 623 ] {} <Fatal> BaseDaemon: 35. ? @ 0x00007f8b24ba9133 in ?
2023.10.17 12:51:29.339469 [ 446 ] {} <Trace> myplant.idx_ts_data_string_highres_daily (2c680187-5f87-4ed1-9a47-e390d941068c): Scheduling next merge selecting task after 14726ms
2023.10.17 12:51:29.463706 [ 623 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 5F87A3880053D4B54B99021990C2480E)
2023.10.17 12:51:29.464120 [ 623 ] {} <Debug> SystemLogQueue (system.crash_log): Requested flush up to offset 1
2023.10.17 12:51:29.464153 [ 623 ] {} <Information> SentryWriter: Not sending crash report
2023.10.17 12:51:29.464172 [ 623 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
```

query is sent by clickhouse-java, version 0.4.6, code:
```
    fun deleteFromSeries(deviceId: Int, dataItemId: Int, from: Long, to: Long, points: Set<Long>, timestamp: Long, dt: DataType) {
        val sql = """
            INSERT INTO myplant.ts_data_double_raw (device_id, data_item_id, data_time, data_value, is_deleted, ingestion_time) 
            SELECT
               device_id,
               data_item_id,
               data_time,
               data_value,         
               1,  -- mark as deleted
               fromUnixTimestamp64Milli($timestamp, 'UTC') -- all inserted records have new ingestion time
            FROM ${readTableName(dt)}
            WHERE (device_id = $deviceId) AND (data_item_id = $dataItemId)
                AND (data_time >= fromUnixTimestamp64Milli($from, 'UTC'))
                AND (data_time <= fromUnixTimestamp64Milli($to, 'UTC'))
                AND version < fromUnixTimestamp64Milli($timestamp, 'UTC')
                AND (toUnixTimestamp64Milli(data_time) IN (SELECT timestamp FROM input('timestamp UInt64')))
        """.trimIndent()

        val data = ByteArrayOutputStream()
        points.forEach {
            BinaryStreamUtils.writeUnsignedInt64(data, it)
        }
        trace("delete-points-from-series-$dt") { _ ->
            ClickHouseClient.newInstance(ClickHouseProtocol.HTTP).use { client ->
                client
                    .write(server)
                    .format(ClickHouseFormat.RowBinary)
                    .write()
                    .data(ByteArrayInputStream(data.toByteArray()))
                    .query(sql)
                    .execute()
                    .get(clickhouseConfig.timeout, TimeUnit.MILLISECONDS)
            }
        }
    }
```

table structure:
```
CREATE TABLE IF NOT EXISTS myplant.ts_data_double_raw ON CLUSTER myplant
(
    `device_id` UInt32 NOT NULL CODEC(ZSTD),
    `data_item_id` UInt32 NOT NULL CODEC(ZSTD),
    `data_time` DateTime64(3, 'UTC') NOT NULL CODEC(Delta, ZSTD),
    `data_value` Float64 NOT NULL CODEC(Delta, ZSTD),
    `is_deleted` Bool CODEC(ZSTD),
    `ingestion_time` DateTime64(3, 'UTC') NOT NULL CODEC(Delta, ZSTD)
    )
    ENGINE = ReplicatedReplacingMergeTree()
    PARTITION BY toYYYYMM(data_time)
    ORDER BY (device_id, data_item_id, data_time)
    SETTINGS index_granularity = 8192
```

Query worked fine until adding `AND (toUnixTimestamp64Milli(data_time) IN (SELECT timestamp FROM input('timestamp UInt64')))`. 
Expected behaviour - report sql syntax error if i got it wrong and this syntax is not supported.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the crash that might happen if table function `input()` was used in the subquery for IN. Fixes https://github.com/ClickHouse/ClickHouse/issues/55740

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 4004248c13d6e4b191e0b00ece7b4d30281f40e5 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56695/4004248c13d6e4b191e0b00ece7b4d30281f40e5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6854504883">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56695/4004248c13d6e4b191e0b00ece7b4d30281f40e5/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Interpreters/PredicateExpressionsOptimizer.cpp [hunk 1]
```diff
@@ -72,6 +84,9 @@ std::vector<ASTs> PredicateExpressionsOptimizer::extractTablesPredicates(const A
             return {};   /// Not optimized when predicate contains stateful function or indeterministic function or window functions
         }
 
+        if (hasInputTableFunction(predicate_expression))
+            return {}; /// Not optimized when predicate contains input table function
```
Comment (antaljanosbenjamin) [inline src/Interpreters/PredicateExpressionsOptimizer.cpp:88]:
```suggestion
            return {}; /// Not optimized when predicate contains input table function
```
I think this comment is not useful. From the if statement it is clear when we don't want to optimize. However it might worth to note _why_: `input table function can only be read once, but the optimization might copy the subquery which would result in reading more from StorageInput then it expects`. Or something along this line.

File: src/Storages/StorageInput.cpp [hunk 2]
```diff
@@ -47,32 +49,69 @@ class StorageInputSource : public ISource, WithContext
...
+        //StorageSnapshotPtr storage_snapshot_,
+        StorageInput & storage_)
+        : ISourceStep(DataStream{.header = std::move(sample_block)})
+        //, storage_snapshot(std::move(storage_snapshot_))
+        , storage(storage_)
+    {
+    }
+
+private:
+    //StorageSnapshotPtr storage_snapshot;
```
Comment (antaljanosbenjamin) [inline src/Storages/StorageInput.cpp:72]:
```suggestion
        Block sample_block,
        StorageInput & storage_)
        : ISourceStep(DataStream{.header = std::move(sample_block)})
        , storage(storage_)
    {
    }

private:
```

File: src/Storages/StorageInput.cpp [hunk 3]
```diff
@@ -47,32 +49,69 @@ class StorageInputSource : public ISource, WithContext
...
     }
 
-    if (pipe.empty())
+    if (!was_pipe_initialized)
         throw Exception(ErrorCodes::INVALID_USAGE_OF_INPUT, "Input stream is not initialized, input() must be used only in INSERT SELECT query");
 
-    return std::move(pipe);
+    auto reading = std::make_unique<ReadFromInput>(
+        std::move(sample_block),
+        //storage_snapshot,
```
Comment (antaljanosbenjamin) [inline src/Storages/StorageInput.cpp:102]:
```suggestion
```

**Review by antaljanosbenjamin — COMMENTED** [review]
There are also some failing tests that I think correlated.

**Review by antaljanosbenjamin — APPROVED** [review]
