### PR TITLE
ReplicatedMergeTree invalid metadata_version fix

### LINKED ISSUE #54902: Metadata on replica is not up to date with common metadata in Zookeeper
```sql
alter table test add column x Int32;

Received exception from server (version 23.8.2):
Code: 517. DB::Exception: Received from localhost:9000. 
DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. 
It means that this replica still not applied some of previous alters. 
Probably too many alters executing concurrently (highly not recommended). You can retry this error. (CANNOT_ASSIGN_ALTER)
```

I tried table detach/attach, no changes.

```
SELECT
    name,
    substr(replace(value, '\n', ' '), 1, 50) AS value_s,
    cityHash64(value)
FROM system.zookeeper
WHERE path = (
    SELECT zookeeper_path
    FROM system.replicas
    WHERE table = 'test'
)

┌─name───────────────────────┬─value_s────────────────────────────────────────────┬────cityHash64(value)─┐
│ alter_partition_version    │                                                    │ 11160318154034397263 │
│ metadata                   │ metadata format version: 1 date column:  sampling  │  4322393711038923972 │
│ temp                       │                                                    │ 11160318154034397263 │
│ table_shared_id            │ fc28061c-c819-4a0b-bc28-061cc8194a0b               │  7914521819417058279 │
│ log                        │                                                    │ 11160318154034397263 │
│ leader_election            │                                                    │ 11160318154034397263 │
│ columns                    │ columns format version: 1 243 columns: `access_tim │   594710015478039907 │
│ blocks                     │                                                    │ 11160318154034397263 │
│ nonincrement_block_numbers │                                                    │ 11160318154034397263 │
│ replicas                   │ last added replica: chdw1-1.sde10186               │  4784695667935888577 │
│ async_blocks               │                                                    │ 11160318154034397263 │
│ quorum                     │                                                    │ 11160318154034397263 │
│ pinned_part_uuids          │ {"part_uuids":"[]"}                                │ 16899393181724385792 │
│ block_numbers              │                                                    │ 11160318154034397263 │
│ mutations                  │                                                    │ 11160318154034397263 │
│ zero_copy_s3               │                                                    │ 11160318154034397263 │
│ part_moves_shard           │                                                    │ 11160318154034397263 │
│ zero_copy_hdfs             │                                                    │ 11160318154034397263 │
│ lost_part_count            │                                                    │ 11160318154034397263 │
└────────────────────────────┴────────────────────────────────────────────────────┴──────────────────────┘
```

```
SELECT
    name,
    substr(replace(value, '\n', ' '), 1, 50) AS value_s,
    cityHash64(value)
FROM system.zookeeper
WHERE path = (
    SELECT replica_path
    FROM system.replicas
    WHERE table = 'test'
)

┌─name────────────────────────┬─value_s────────────────────────────────────────────┬────cityHash64(value)─┐
│ is_lost                     │ 0                                                  │ 10408321403207385874 │
│ metadata                    │ metadata format version: 1 date column:  sampling  │  4322393711038923972 │
│ is_active                   │ UUID_'a57446f7-2cb9-47f9-b1b6-65573c29067c'        │  1870750756359300609 │
│ mutation_pointer            │ 0000000047                                         │ 10517147932185828611 │
│ columns                     │ columns format version: 1 243 columns: `access_tim │   594710015478039907 │
│ max_processed_insert_time   │ 1695306428                                         │  5882609297731162392 │
│ flags                       │                                                    │ 11160318154034397263 │
│ log_pointer                 │ 547980                                             │ 18155853374234986669 │
│ min_unprocessed_insert_time │ 0                                                  │ 10408321403207385874 │
│ host                        │ host: chdw1-1.sde10186.mycmdb.net port: 9009 tcp_p │ 16322273289710190182 │
│ parts                       │                                                    │ 11160318154034397263 │
│ queue                       │                                                    │ 11160318154034397263 │
│ metadata_version            │ 0                                                  │ 10408321403207385874 │
└─────────────────────────────┴────────────────────────────────────────────────────┴──────────────────────┘
```

I wonder what I should check else, to find the cause of the issue ?

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
ReplicatedMergeTree fix invalid `metadata_version` node initialization in Zookeeper during creation of non first replica. Closes #54902.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 06287e70c84690a6fa208ae2cbef2722a34f0d04 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59946/06287e70c84690a6fa208ae2cbef2722a34f0d04/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59946/06287e70c84690a6fa208ae2cbef2722a34f0d04/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -5872,10 +5873,6 @@ bool StorageReplicatedMergeTree::executeMetadataAlter(const StorageReplicatedMer
         resetObjectColumnsFromActiveParts(parts_lock);
     }
 
-    /// This transaction may not happen, but it's OK, because on the next retry we will eventually create/update this node
-    /// TODO Maybe do in in one transaction for Replicated database?
```
Comment (alexey-milovidov) [inline src/Storages/StorageReplicatedMergeTree.cpp:5876]: The TODO still holds.

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 2]
```diff
@@ -5826,6 +5826,7 @@ bool StorageReplicatedMergeTree::executeMetadataAlter(const StorageReplicatedMer
     Coordination::Requests requests;
     requests.emplace_back(zkutil::makeSetRequest(fs::path(replica_path) / "columns", entry.columns_str, -1));
     requests.emplace_back(zkutil::makeSetRequest(fs::path(replica_path) / "metadata", entry.metadata_str, -1));
+    requests.emplace_back(zkutil::makeSetRequest(fs::path(replica_path) / "metadata_version", std::to_string(entry.alter_version), -1));
```
Comment (alexey-milovidov) [inline src/Storages/StorageReplicatedMergeTree.cpp:5829]: Need more explanation about this change.

File: src/Storages/StorageReplicatedMergeTree.cpp (hunk 1 above)
Comment (kitaisreal) [reply src/Storages/StorageReplicatedMergeTree.cpp:5876]: As I understand if database is replicated it will execute requests in `setTableStructure`. And one of the requests will be new set.
```
if (is_in_replicated_database)
    {
        auto mutable_alter_context = Context::createCopy(getContext());
        const auto * replicated = dynamic_cast<const DatabaseReplicated *>(database.get());
        mutable_alter_context->makeQueryContext();
        auto alter_txn = std::make_shared<ZooKeeperMetadataTransaction>(zookeeper, replicated->getZooKeeperPath(),
                                                                       /* is_initial_query */ false, /* task_zk_path */ "");
        mutable_alter_context->initZooKeeperMetadataTransaction(alter_txn);
        alter_context = mutable_alter_context;

        for (auto & op : requests)
            alter_txn->addOp(std::move(op));
        requests.clear();
        /// Requests will be executed by database in setTableStructure
    }
```

**Comment by kitaisreal** [comment]
Setup:
```
DROP TABLE IF EXISTS test_table_replicated;
CREATE TABLE test_table_replicated
(
    id UInt64,
    value String
) ENGINE=ReplicatedMergeTree('/clickhouse/tables/test_table_replicated', '1_replica') ORDER BY id;

ALTER TABLE test_table_replicated ADD COLUMN insert_time DateTime;
```

Check ZooKeeper version of table '/metadata' node:
```
SELECT name, value, path, version FROM system.zookeeper WHERE path = '/clickhouse/tables/test_table_replicated/' AND name = 'metadata' FORMAT Vertical

Row 1:
──────
name:    metadata
value:   metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: id
data format version: 1
partition key:
granularity bytes: 10485760
merge parameters format version: 2

path:    /clickhouse/tables/test_table_replicated/
version: 1
```

Now we can drop current table and create new one. Or those table can be created on another ClickHouse instance with same or different name. For simplicity and reproducibility in single-node setup let's just drop table:
```
DROP TABLE test_table_replicated;
```

Create other non-first replica with right table structure:
```
CREATE TABLE test_table_replicated;
(
    id UInt64,
    value String,
    insert_time DateTime
) ENGINE=ReplicatedMergeTree('/clickhouse/tables/test_table_replicated', '2_replica') ORDER BY id;
```

Now in memory `metadata_version` is equal to version of table `/metadata` in ZooKeeper, but value of `metadata_version` node is invalid and initialized with 0. Check replica '/metadata_version' node value in ZooKeeper:
```
SELECT name, value, path, version FROM system.zookeeper WHERE path = '/clickhouse/tables/test_table_replicated/replicas/2_replica' AND name = 'metadata_version' FORMAT Vertical

Row 1:
──────
name:    metadata_version
value:   0
path:    /clickhouse/tables/test_table_replicated/replicas/2_replica
version: 0
```

We can restart replica and it will use `metadata_version` from ZooKeeper.
```
SYSTEM RESTART REPLICA test_table_replicated_new_replica;
```

Now in memory `metadata_version` is equal to value of `/metadata_version` node in ZooKeeper and is equal 0, but should be 1 and next ALTER queries will fail.

```
ALTER TABLE test_table_replicated_new_replica ADD COLUMN insert_time_updated DateTime;

Received exception from server (version 24.2.1):
Code: 517. DB::Exception: Received from localhost:9000. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper.
It means that this replica still not applied some of previous alters. Probably too many alters executing concurrently (highly not recommended).
You can retry this error. (CANNOT_ASSIGN_ALTER)
```

**Comment by kitaisreal** [comment]
Main fix https://github.com/ClickHouse/ClickHouse/pull/59946/files#diff-0f4308161ab179a68f01cabfce4dc9e6e4e5f9c1e6c46c37d5adaeaad74e9913R524.
Updating `metadata_version` in ZooKeeper during ALTER is better to have consistency between local `metadata_version` and `metadata_version` in ZooKeeper, but is unrelated to bug.

File: src/Storages/StorageReplicatedMergeTree.cpp (hunk 2 above)
Comment (kitaisreal) [reply src/Storages/StorageReplicatedMergeTree.cpp:5836]: We want to keep `metadata_version` in memory always consistent with `metadata_verion` in ZooKeeper. Before it was not done in single transaction, that modifies `metadata` and `columns` because `metadata_version` node was not always created. Now we can safely update `metadata_version` in single transaction.
I think it does not make sense to write this as comment in code, because it will only complicate code read, it is clear why we want to modify all replica metadata in single transaction.

**Review by alesapin — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by antonio2368** [comment]
@alexey-milovidov we have so many beautiful checks, why not give them a chance to run?
seems the new test is failing with DatabaseReplicated

**Comment by Algunenano** [comment]
Reverted. Please re-send with fixed test

**Comment by zeph** [comment]
we are affected by this bug too, on 24.4.1

**Comment by antonio2368** [comment]
The PR was actually submitted again and merged https://github.com/ClickHouse/ClickHouse/pull/60078

@zeph @chipzzz could you please create an issue with more information?
Tables you created, ALTERs you run, from ZK version of table `metadata` node and value stored in `metadata_version` for each replica.

**Comment by den-crane** [comment]
@zeph 

_It is not fixed automatically with migration to new version, you still need to manually make changes to ZooKeeper. In new version bug will not exist._

https://github.com/ClickHouse/ClickHouse/issues/54902#issuecomment-2078930323

https://github.com/ClickHouse/ClickHouse/issues/54902#issuecomment-2263570766
