### PR TITLE
Fix logical error in stress test "Not enough space to add ..."

### LINKED ISSUE #49553: Logical error: Not enough space to add {}:{} with size {}: current size: {}/{}
https://s3.amazonaws.com/clickhouse-test-reports/0/ab1a1ea5b73041076fc081fba8d44708ef0fc7b9/stress_test__ubsan_.html

```
 [ 3275 ] {34553f94-2f56-4023-8c6e-305c6d3c0574} <Fatal> : Logical error: \'Not enough space to add 8ea9278dfeedf2da9be1efd332f05fe0:15627328 with size 1048576: current size: 133251986/134217728\'.
 [ 15238 ] {} <Fatal> BaseDaemon: ########################################
 [ 15238 ] {} <Fatal> BaseDaemon: (version 23.5.1.1 (official build), build id: D3205CED35F1C1C2CF2C6EBCAABE279A72ED289F) (from thread 3275) (query_id: 34553f94-2f56-4023-8c6e-305c6d3c0574) (query: SELECT count() FROM test.hits_s3 WHERE URL LIKE \'%metrika%\';) Received signal Aborted (6)
 [ 15238 ] {} <Fatal> BaseDaemon: 
 [ 15238 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f7187a9d00b 0x7f7187a7c859 0x55b8458a3e88 0x55b8458a478d 0x55b8529d711f 0x55b8529d479c 0x55b8529b82cf 0x55b8529cee65 0x55b8512f41aa 0x55b8512f118f 0x55b83abb33d9 0x55b8512dfdd6 0x55b8512dead9 0x55b8512de8d7 0x55b8515d4c14 0x55b8515d62af 0x55b8515d750
 [ 15238 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f7187a9d00b in ?
 [ 15238 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f7187a7c859 in ?
 [ 15238 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:49: DB::abortOnFailedAssertion(String const&) @ 0x353e2e88 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x353e378d in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
 [ 15238 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:2333: ~basic_string
 [ 15238 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/./src/Common/Exception.h:42: ~MessageMasked
 [ 15238 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/./src/Common/Exception.h:54: Exception
 [ 15238 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Common/Exception.h:81: DB::Exception::Exception<DB::FileCacheKey const&, unsigned long&, unsigned long&, std::atomic<unsigned long>&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<DB::FileCacheKey const&>::type, std::type_iden
 [ 15238 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Interpreters/Cache/LRUFileCachePriority.cpp:43: DB::LRUFileCachePriority::add(std::shared_ptr<DB::KeyMetadata>, unsigned long, unsigned long, DB::CacheGuard::Lock const&) @ 0x4251379c in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:616: shared_ptr
 [ 15238 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:723: std::shared_ptr<DB::IFileCachePriority::IIterator>::operator=[abi:v15000](std::shared_ptr<DB::IFileCachePriority::IIterator>&&)
 [ 15238 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Interpreters/Cache/FileCache.cpp:686: DB::FileCache::tryReserve(DB::FileSegment&, unsigned long) @ 0x424f72cf in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Interpreters/Cache/FileSegment.cpp:503: DB::FileSegment::reserve(unsigned long) @ 0x4250de65 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:944: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x40e331aa in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:770: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x40e3018f in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 13. DB::ReadBuffer::next() @ 0x2a6f23d9 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:0: DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x40e1edd6 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:150: DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x40e1dad9 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:106: DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) @ 0x40e1d8d7 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Disks/IO/ThreadPoolRemoteFSReader.cpp:62: DB::RemoteFSFileDescriptor::readInto(char*, unsigned long, unsigned long, unsigned long) @ 0x41113c14 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./src/Disks/IO/ThreadPoolRemoteFSReader.cpp:91: operator()
 [ 15238 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/./src/Interpreters/threadPoolCallbackRunner.h:42: operator()
 [ 15238 ] {} <Fatal> BaseDaemon: 18.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::IAsynchronousReader::Result>()()) std::__invoke[abi:v15000]<std::function<std::future<DB::IAsynchronousReader::Result> (DB::ThreadPoolRemoteF
 [ 15238 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./contrib/llvm-project/libcxx/include/future:1694: std::__packaged_task_func<std::function<std::future<DB::IAsynchronousReader::Result> (DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, long)> DB::threadPoolCallbackRu
 [ 15238 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/future:1380: std::promise<DB::IAsynchronousReader::Result>::set_value(DB::IAsynchronousReader::Result&&)
 [ 15238 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./contrib/llvm-project/libcxx/include/future:1953: std::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() @ 0x41116501 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:789: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 15238 ] {} <Fatal> BaseDaemon: 20.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1456: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 15238 ] {} <Fatal> BaseDaemon: 20.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 15238 ] {} <Fatal> BaseDaemon: 20.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 15238 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./src/Common/ThreadPool.cpp:415: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x35505878 in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::\'lambda0\'()>(void&
 [ 15238 ] {} <Fatal> BaseDaemon: 22.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:789: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 15238 ] {} <Fatal> BaseDaemon: 22.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1456: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 15238 ] {} <Fatal> BaseDaemon: 22.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 15238 ] {} <Fatal> BaseDaemon: 22.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 15238 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./src/Common/ThreadPool.cpp:415: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x3550352f in /usr/bin/clickhouse
 [ 15238 ] {} <Fatal> BaseDaemon: 23. ./build_docker/./src/Common/ThreadPool.cpp:0: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, st
 [ 15238 ] {} <Fatal> BaseDaemon: 24. ? @ 0x7f7187c54609 in ?
 [ 15238 ] {} <Fatal> BaseDaemon: 25. clone @ 0x7f7187b79133 in ?
 [ 15238 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 8EB5A98AFCDBBFC9780FEDFCC09B3E96)
 [ 1669 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix logical error `"Not enough space to add {}:{} with size {}: current size: {}/{}"`. Closes https://github.com/ClickHouse/ClickHouse/issues/49553.

### CODE REVIEW

File: src/Interpreters/Cache/FileCache.cpp [hunk 1]
```diff
@@ -609,17 +609,19 @@ bool FileCache::tryReserve(FileSegment & file_segment, size_t size)
...
             if (segment->state() == FileSegment::State::DOWNLOADED)
             {
                 const auto & key = segment->key();
+
                 auto it = to_delete.find(key);
                 if (it == to_delete.end())
                     it = to_delete.emplace(key, locked_key.getKeyMetadata()).first;
                 it->second.add(segment_metadata);
+
+                removed_size += segment_metadata->size();
```
Comment (devcrafter) [inline src/Interpreters/Cache/FileCache.cpp:622]: AFAIU, removed non-DOWNLOADED segments size were accounted twice. So, the fix for `removed_size` seems correct.

But `queue_size` calculation looks incorrect since actual queue size can change when non-DOWNLOADED elements are removed
It'd be more straightforward to calculate the number of segments to remove and subtract it from the actual queue size in `is_main_priority_overflow` check

File: src/Interpreters/Cache/FileCache.cpp [hunk 2]
```diff
@@ -653,10 +650,11 @@ bool FileCache::tryReserve(FileSegment & file_segment, size_t size)
...
     {
         /// max_size == 0 means unlimited cache size,
-        /// max_element_size means unlimited number of cache elements.
+        /// max_element_size == 0 means unlimited number of cache elements.
         const bool is_overflow = (main_priority->getSizeLimit() != 0
-                                  && main_priority->getSize(cache_lock) + size - removed_size > main_priority->getSizeLimit())
-            || (main_priority->getElementsLimit() != 0 && queue_size > main_priority->getElementsLimit());
+                                  && (main_priority->getSize(cache_lock) + size - freeable_space > main_priority->getSizeLimit()))
+            || (main_priority->getElementsLimit() != 0
+                && (main_priority->getElementsCount(cache_lock) + 1 - freeable_count > main_priority->getElementsLimit()));
```
Comment (devcrafter) [inline src/Interpreters/Cache/FileCache.cpp]: Please, let's simplify the condition, and probably make it more clean in separate PR (as discussed)
```
freeable_count == 0 && main_priority->getElementsCount() == main_prioirty->getElementsLimit()
```

**Review by devcrafter — APPROVED** [review]
