### PR TITLE
Parse metadata in parallel when loading tables

### LINKED ISSUE #11943: Loading of tables is not parallel in version 20.1+
It hurts if server has millions of tables.

See https://github.com/ClickHouse/ClickHouse/pull/3398
Please add some tests to ensure it won't be broken in future.

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Parse tables metadata in parallel when loading database. This fixes slow server startup when there are large number of tables.

Fixes #11943

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: tests/queries/0_stateless/01193_metadata_loading.sh [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+$CLICKHOUSE_CLIENT -q "CREATE DATABASE $db"
+
+for i in $(seq 1 $threads); do
+  create_tables $i &
+done
+wait
+
+$CLICKHOUSE_CLIENT -q "CREATE TABLE $db.table_merge (i UInt64, d Date, s String, n Nested(i UInt8, f Float32)) ENGINE=Merge('$db', '^table_')"
+#FIXME the following query leads to segfault
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01193_metadata_loading.sh:42]: Maybe create an issue about that?

**Comment by tavplubix** [comment]
`00738_lock_for_inner_table` - seems not related, added to CI Fest

**Comment by alexey-milovidov** [comment]
Ok, though I did not see this test before as flaky.
