### PR TITLE
Print extra info in exception message for "no space left on device"

### LINKED ISSUE #6182: In "no space left on device" exception message, output what filesystem path is used and what total space the fs has.
**Use case**
#6179
Look at the error messages of this test suite:
https://clickhouse-test-reports.s3.yandex.net/6179/2ced6a3adb0229d92d6186590adfe7927fefb523/functional_stateless_tests_(debug).html

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- New Feature

Short description (up to few sentences):
Resolves #6182 and #6252 
Detailed description (optional):

...

### CODE REVIEW

File: dbms/src/Common/Exception.cpp [hunk 1]
```diff
@@ -68,7 +71,66 @@ void tryLogCurrentException(Poco::Logger * logger, const std::string & start_of_
     }
 }
 
-std::string getCurrentExceptionMessage(bool with_stacktrace, bool check_embedded_stacktrace)
+void getEnospcInfoMessage(std::filesystem::path path, std::string & msg)
```
Comment (alexey-milovidov) [inline dbms/src/Common/Exception.cpp]: Don't like `Enospc` in function name.

File: dbms/src/Common/Exception.cpp [hunk 2]
```diff
@@ -68,7 +71,66 @@ void tryLogCurrentException(Poco::Logger * logger, const std::string & start_of_
...
+        else if (auto errno_exception = dynamic_cast<const DB::ErrnoException *>(&e))
+        {
+            if (errno_exception->getErrno() == ENOSPC)
+            {
+                /// Try to extract path from text exception message. Most likely the exception was thrown by
+                /// DB::throwFromErrno("Some message" + filename, ...);
+                /// We suppose "Some message " does not contain '/' and filename is an absolute path starts with '/'.
+                /// throwFromErrno appends ", errno: ..." to the first argument.
+                /// It's ugly hack which may not work correctly. However, getEnospcInfoMessage(...) checks if path exists.
+                size_t likely_path_begin = errno_exception->message().find('/');
```
Comment (alexey-milovidov) [inline dbms/src/Common/Exception.cpp]: That looks very indirect...

File: dbms/src/Storages/MergeTree/DiskSpaceMonitor.h [hunk 3]
```diff
@@ -96,12 +103,17 @@ class DiskSpaceMonitor
 
     using ReservationPtr = std::unique_ptr<Reservation>;
 
-    static UInt64 getUnreservedFreeSpace(const std::string & path)
+    inline static struct statvfs getStatvfs(const std::string & path)
```
Comment (alexey-milovidov) [inline dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: StatVFS to be in style.

File: dbms/src/Storages/MergeTree/DiskSpaceMonitor.h [hunk 4]
```diff
@@ -140,6 +152,52 @@ class DiskSpaceMonitor
         return std::make_unique<Reservation>(size);
     }
 
+    /// Returns mount point of filesystem where absoulte_path (must exists) is located
```
Comment (alexey-milovidov) [inline dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: Typo: must exist.

File: dbms/src/Storages/MergeTree/DiskSpaceMonitor.h [hunk 5]
```diff
@@ -140,6 +152,52 @@ class DiskSpaceMonitor
...
+            device_id = parent_device_id;
+        }
+
+        return absolute_path;
+    }
+
+    /// Returns name of filesystem mounted to mount_point
+    static std::string getFilesystemName(const std::string & mount_point)
+    {
+        auto mounted_filesystems = setmntent("/etc/mtab", "r");
```
Comment (alexey-milovidov) [inline dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: Looks like it should be disabled in FreeBSD and MacOS.

Comment (alexey-milovidov) [inline dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: Error checking?

File: dbms/src/Storages/MergeTree/DiskSpaceMonitor.h [hunk 6]
```diff
@@ -140,6 +152,52 @@ class DiskSpaceMonitor
...
+        mntent fs_info;
+        constexpr size_t buf_size = 4096;     /// The same as buffer used for getmntent in glibc. It can happen that it's not enough
+        char buf[buf_size];
+        while (getmntent_r(mounted_filesystems, &fs_info, buf, buf_size) && fs_info.mnt_dir != mount_point);
```
Comment (alexey-milovidov) [inline dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: If you move semicolon on a new line, it will be better :)

```
while (...)
    ;
```

File: dbms/src/Common/Exception.h [hunk 7]
```diff
@@ -73,6 +75,7 @@ using Exceptions = std::vector<std::exception_ptr>;
 
 std::string errnoToString(int code, int the_errno = errno);
 [[noreturn]] void throwFromErrno(const std::string & s, int code, int the_errno = errno);
+[[noreturn]] void throwFromErrno(const std::string & s, const std::string & path, int code, int the_errno = errno);
```
Comment (alexey-milovidov) [inline dbms/src/Common/Exception.h]: We can use different name for this method for clarity. For example, `throwFromErrnoWithPath`.

File: dbms/src/Common/Exception.h [hunk 8]
```diff
@@ -87,7 +90,8 @@ void tryLogCurrentException(Poco::Logger * logger, const std::string & start_of_
   * check_embedded_stacktrace - if DB::Exception has embedded stacktrace then
   *  only this stack trace will be printed.
   */
-std::string getCurrentExceptionMessage(bool with_stacktrace, bool check_embedded_stacktrace = false);
+std::string getCurrentExceptionMessage(bool with_stacktrace, bool check_embedded_stacktrace = false,
```
Comment (alexey-milovidov) [inline dbms/src/Common/Exception.h]: Maybe always with extra info? What are the downsides?

File: dbms/src/Common/Exception.cpp [hunk 9]
```diff
@@ -68,7 +76,50 @@ void tryLogCurrentException(Poco::Logger * logger, const std::string & start_of_
...
+
+    auto fs = DiskSpaceMonitor::getStatVFS(path);
+    msg += "\nTotal space: "      + formatReadableSizeWithBinarySuffix(fs.f_blocks * fs.f_bsize)
+         + "\nAvailable space: "  + formatReadableSizeWithBinarySuffix(fs.f_bavail * fs.f_bsize)
+         + "\nTotal inodes: "     + formatReadableQuantity(fs.f_files)
+         + "\nAvailable inodes: " + formatReadableQuantity(fs.f_favail);
+
+    auto mount_point = DiskSpaceMonitor::getMountPoint(path).string();
+    msg += "\nMount point: " + mount_point;
+    msg += "\nFilesystem: " + DiskSpaceMonitor::getFilesystemName(mount_point);
```
Comment (alexey-milovidov) [inline dbms/src/Common/Exception.cpp]: Maybe it's better to disable this information (about fs name) on non-Linux than throw exception everytime?

File: dbms/src/Storages/MergeTree/DiskSpaceMonitor.h [hunk 10]
```diff
@@ -140,6 +154,62 @@ class DiskSpaceMonitor
...
+    }
+
+    /// Returns name of filesystem mounted to mount_point
+#if !defined(__linux__)
+[[noreturn]]
+#endif
+    static std::string getFilesystemName([[maybe_unused]] const std::string & mount_point)
+    {
+#if defined(__linux__)
+        auto mounted_filesystems = setmntent("/etc/mtab", "r");
```
Comment (alexey-milovidov) [inline dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: Just in case, we need to check "the internets", is it a good function (never heard about it).

File: dbms/src/Common/Exception.h (hunk 8 above)
Comment (tavplubix) [reply dbms/src/Common/Exception.h]: `getExtraExceptionInfo(...)` may catch an exception (not only if it's not Linux) while trying to collect extra info. In this case it appends the following message to extra info:
`msg += "\nCannot print extra info: " + getCurrentExceptionMessage(false, false, false);`
And `with_extra_info` must be false in this case to avoid infinite recursion.

File: dbms/src/Storages/MergeTree/DiskSpaceMonitor.h (hunk 10 above)
Comment (tavplubix) [reply dbms/src/Storages/MergeTree/DiskSpaceMonitor.h]: It seems to me, there is nothing suspicious:
- `setmntent` opens `/etc/mtab` (or `/etc/fstab`) using `fopen`
- `getmntent_r` parses opened file line-by-line
- `endmntent` calls `fclose`
 
However, `findmnt` uses libmount and `df` uses `read_file_system_list()` from gnulib to parse `/proc/self/mountinfo` instead of `/etc/mtab`.

**Review by alexey-milovidov — APPROVED** [review]
