### PR TITLE
MySQL compatibility: allow to configure String/FixedString BLOB vs TEXT mapping

### LINKED ISSUE #52777: Inconsistency between `String` and `FixedString` type mapping in MySQL compatibility mode.
**Describe the unexpected behaviour**

When using the `use_mysql_types_in_show_columns` setting, implemented in issue #49577, ClickHouse's `String` datatype is mapped to MySQL's `BLOB` datatype. Unfortunately, the QuickSight tool mentioned in the issue does not support this type of columns (https://docs.aws.amazon.com/quicksight/latest/user/supported-data-types.html). As a result, all `String` columns are skipped when a table is added to the dataset.

Also, there is an inconsistency because the `FixedString` type is mapped to the `TEXT` datatype, but `String` and `FixedString` should be mapped at least to the same mysql datatype as there is no any difference of how bytes of text are stored in the clickhouse.

It's a subject for discussion of what datatype they match better, `BLOB` or `TEXT`, but at least Quicksight tool doesn't support `BLOB` columns (but do support `TEXT`).

```
MySQL [voluum]> SHOW FULL COLUMNS IN test;
+----------+---------+------+---------+---------+-------+-----------+---------+------------+
| field    | type    | null | key     | default | extra | collation | comment | privileges |
+----------+---------+------+---------+---------+-------+-----------+---------+------------+
| fixed    | TEXT    |    0 |         | NULL    |       | NULL      |         |            |
| id       | INTEGER |    0 | PRI SOR | NULL    |       | NULL      |         |            |
| variable | BLOB    |    0 |         | NULL    |       | NULL      |         |            |
+----------+---------+------+---------+---------+-------+-----------+---------+------------+
3 rows in set (0.005 sec)
```

**How to reproduce**

- Which ClickHouse server version to use: 23.7
- Which interface to use, if it matters: MySQL
- Non-default settings, if any:
```
SET use_mysql_types_in_show_columns = 1;
```

* `CREATE TABLE` statements for all tables involved

```
CREATE TABLE test (
    id INT NOT NULL PRIMARY KEY,
    variable String(32) NOT NULL,
    fixed FixedString(32) NOT NULL
) ENGINE=MergeTree;
```
* Queries to run that lead to unexpected result

```
SHOW FULL COLUMNS IN test;
```

**Expected behavior**
- `fixed` and `variable` column types should be the same.
- `String` columns should be mapped to the `TEXT` type in order to be supported by Quicksight.

### LINKED ISSUE #53482: MySQL compatibility: BLOB vs TEXT for String types
**Describe the issue**
All the string types are reported as BLOB if `use_mysql_types_in_show_columns` is set to 1. This, unfortunately, causes issues with QuickSight via MySQL interface, as it cannot recognize BLOB columns as strings. For example:

image

As you can see, BLOB (aka LONGVARBINARY, see [the explanation](https://dev.mysql.com/doc/refman/8.0/en/blob.html)) does not work here as expected. However, this works fine with tools such as Looker Studio. 

**How to reproduce**
* Which ClickHouse server version to use: the latest master build
* Which interface to use, if matters: MySQL
* Non-default settings, if any: `users.xml` -> add `<use_mysql_types_in_show_columns>1</use_mysql_types_in_show_columns>` to the default profile.
* Sample data: [commits sample dataset](https://clickhouse.com/docs/en/getting-started/example-datasets/github)
* Queries to run:

```
show full columns from commits;
```

**Preferred solution**
While BLOB is technically the correct type for representing Strings via MySQL interface, a configuration option to switch between `BLOB` and `TEXT` globally reported types for String columns in the `SHOW (FULL) COLUMNS` output will enable us to integrate with QuickSight better.

CC @rschu1ze

### PR DESCRIPTION
**Pull request by slvrtrn**
Resolves #53482
Resolves #52777

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`SHOW COLUMNS` now correctly reports type `FixedString` as `BLOB` if setting `use_mysql_types_in_show_columns` is on. Also added two new settings, `mysql_map_string_to_text_in_show_columns` and `mysql_map_fixed_string_to_text_in_show_columns` to switch the output for types `String` and `FixedString` as `TEXT` or `BLOB`.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 42fc670c2242977219eb541ea1423ab7c3711b9a with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55617/42fc670c2242977219eb541ea1423ab7c3711b9a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6512112230">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55617/42fc670c2242977219eb541ea1423ab7c3711b9a/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

File: src/Core/Settings.h [hunk 1]
```diff
@@ -205,7 +205,9 @@ class IColumn;
     M(Bool, allow_experimental_inverted_index, false, "If it is set to true, allow to use experimental inverted index.", 0) \
     \
     M(UInt64, mysql_max_rows_to_insert, 65536, "The maximum number of rows in MySQL batch insertion of the MySQL storage engine", 0) \
-    M(Bool, use_mysql_types_in_show_columns, false, "Show MySQL types in SHOW COLUMNS and system.columns", 0) \
+    M(Bool, use_mysql_types_in_show_columns, false, "Show native MySQL types in SHOW [FULL] COLUMNS", 0) \
+    M(Bool, mysql_remap_string_as_text_in_show_columns, false, "If enabled, String type will be mapped to TEXT in SHOW [FULL] COLUMNS, BLOB otherwise. Only works if use_mysql_types_in_show_columns is enabled too", 0) \
```
Comment (rschu1ze) [inline src/Core/Settings.h:209]: "Only works" --> "Only takes an effect"

Comment (rschu1ze) [inline src/Core/Settings.h:209]: Could we replace `remap` in the setting names by just `map` and `as` to `to`?

Comment (slvrtrn) [reply src/Core/Settings.h:209]: I specifically avoided using `map` as we have type `Map` to avoid possible misinterpretation. But we can do that.

File: tests/queries/0_stateless/02775_show_columns_mysql_compatibility.sql [hunk 2]
```diff
@@ -78,4 +78,13 @@ SHOW COLUMNS FROM tab SETTINGS use_mysql_types_in_show_columns = 0;
 SELECT '-- SHOW COLUMNS with use_mysql_types_in_show_columns = 1';
 SHOW COLUMNS FROM tab SETTINGS use_mysql_types_in_show_columns = 1;
 
+SELECT '-- SHOW COLUMNS with mysql_remap_string_as_text_in_show_columns = 1';
+SHOW COLUMNS FROM tab SETTINGS mysql_remap_string_as_text_in_show_columns=1;
```
[the remark this answers is not in the document]
Comment (slvrtrn) [reply tests/queries/0_stateless/02775_show_columns_mysql_compatibility.sql:82]: Oh wait, this is odd. For some reason, I thought we had `SET use_mysql_types_in_show_columns=1` in this file. If it works without it, then it is not correct indeed. I will have a look.

File: src/Interpreters/InterpreterShowColumnsQuery.cpp [hunk 3]
```diff
@@ -24,7 +24,10 @@ String InterpreterShowColumnsQuery::getRewrittenQuery()
 {
     const auto & query = query_ptr->as<ASTShowColumnsQuery &>();
 
-    const bool use_mysql_types = getContext()->getSettingsRef().use_mysql_types_in_show_columns;
+    const auto & settings = getContext()->getSettingsRef();
+    const bool use_mysql_types = settings.use_mysql_types_in_show_columns;
+    const bool remap_string_as_text = settings.mysql_map_string_to_text_in_show_columns;
```
Comment (rschu1ze) [inline src/Interpreters/InterpreterShowColumnsQuery.cpp:29]: `remap_` --> `map_`

**Review by rschu1ze — APPROVED** [review]

File: src/Interpreters/InterpreterShowColumnsQuery.cpp (hunk 3 above)
Comment (slvrtrn) [reply src/Interpreters/InterpreterShowColumnsQuery.cpp:29]: Let's change this in one of the follow-ups.

Comment (rschu1ze) [reply src/Interpreters/InterpreterShowColumnsQuery.cpp:29]: Sure, please merge then once all test ran.

Comment (slvrtrn) [reply src/Interpreters/InterpreterShowColumnsQuery.cpp:29]: @rschu1ze, I don't seem to have the necessary permissions to merge.

Comment (rschu1ze) [reply src/Interpreters/InterpreterShowColumnsQuery.cpp:29]: Okay, I can do it.
