### PR TITLE
Enforce saturating conversion for implicit Date to DateTime during index analysis

### LINKED ISSUE #73307: Comparison between Date and Datetime is broken in primary index
**Company or project name**

ClickHouse inc.

**Describe what's wrong**

```
CREATE TABLE test (stamp Date)
ENGINE = MergeTree
ORDER BY stamp;

INSERT INTO TABLE test SELECT '2024-10-30' FROM numbers(100);
INSERT INTO TABLE test SELECT '2024-11-19' FROM numbers(100);
INSERT INTO TABLE test SELECT '2149-06-06' FROM numbers(100);

OPTIMIZE TABLE test FINAL;

SELECT count()
FROM test
WHERE stamp >= parseDateTimeBestEffort('2024-11-01'); --- 0

SELECT count()
FROM test
WHERE stamp >= toDate('2024-11-01'); --- 200 (right answer)
```

https://fiddle.clickhouse.com/02714019-3055-43a4-a6a8-93f7de167f9d

**Does it reproduce on the most recent release?**

Yes, moreover, it almost never worked correctly.

22.8: broken https://fiddle.clickhouse.com/7638e77a-7c21-4f37-93cb-e148554d26ec, result is 0 200
21.4: broken https://fiddle.clickhouse.com/a58bbc8e-1241-46d7-863d-4017abd3d9a7, result is 0 200
21.3: broken https://fiddle.clickhouse.com/488b9375-5d95-433f-901a-9700f0497f9e, result is 100 100
1.1.54394: broken https://fiddle.clickhouse.com/f2198f60-0797-437e-91d0-da858c94a843, result is 0 100

Right answer is 200 200.

Previous attempts to fix similar issue: https://github.com/ClickHouse/ClickHouse/issues/17122 CC @amosbird

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved datetime conversion during index analysis by enforcing saturating behavior for implicit Date to DateTime conversions. This resolves potential index analysis inaccuracies caused by datetime range limitations. This fixes #73307. It also fixes explicit `toDateTime` conversion when `date_time_overflow_behavior = 'ignore'` which is the default value.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 704fe28b965f7b846f5b4695a4ce33c63023fea2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73326/704fe28b965f7b846f5b4695a4ce33c63023fea2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Functions/DateTimeTransforms.h [hunk 1]
```diff
@@ -55,7 +55,7 @@ constexpr time_t MAX_DATETIME64_TIMESTAMP = 10413791999LL;    //  1900-01-01 00:
 constexpr time_t MIN_DATETIME64_TIMESTAMP = -2208988800LL;    //  2299-12-31 23:59:59 UTC
 constexpr time_t MAX_DATETIME_TIMESTAMP = 0xFFFFFFFF;
 constexpr time_t MAX_DATE_TIMESTAMP = 5662310399;       // 2149-06-06 23:59:59 UTC
-constexpr time_t MAX_DATETIME_DAY_NUM =  49710;               // 2106-02-07
+constexpr time_t MAX_DATETIME_DAY_NUM =  49709;         // 2106-02-06 America/Hermosillo
```
Comment (yakov-olkhovskiy) [inline src/Functions/DateTimeTransforms.h:58]: why we reduce it by one day?

Comment (amosbird) [reply src/Functions/DateTimeTransforms.h:58]: Because:

```
SELECT toDateTime(toDate(49710), 'America/Hermosillo')

   ┌─toDateTime(toDate(49710), 'America/Hermosillo')─┐
1. │                             1969-12-31 16:31:44 │
   └─────────────────────────────────────────────────┘

SELECT toDateTime(toDate(49710), 'UTC')

   ┌─toDateTime(toDate(49710), 'UTC')─┐
1. │              2106-02-07 00:00:00 │
   └──────────────────────────────────┘
```

File: tests/queries/0_stateless/03271_date_to_datetime_saturation.reference [hunk 2]
```diff
@@ -0,0 +1,3 @@
+200
+200
+100
```
Comment (Algunenano) [inline tests/queries/0_stateless/03271_date_to_datetime_saturation.reference:3]: This is not ok. It should never return incorrect values.

A couple of requirements:
* This should have way more tests than it has, explicitly testing parts with ranges (before supported Datetime, supported Datetime, after supported Datetime) and its combinations. Also with extreme values in both dates and datetime.
* It's not ok to ever return bad values in index analysis. There are 3 possible alternatives:
  - Support everything (might need a type that's a superset of both Date / DateTime for it to be possible).
  - Throw on invalid values.
  - Ignore index analysis in the part where the cast is lossy, so the part is read anyways.
The only reason to support `ignore` or `saturate` if it leads to incorrect analysis would be to support old queries that used to work incorrectly and where throwing breaks compatibility, but it should not be the default value.

All this is only possible to verify with extensive tests, so that should be introduced with the PR, not as an after thought.

Comment (amosbird) [reply tests/queries/0_stateless/03271_date_to_datetime_saturation.reference:3]: > It should never return incorrect values.

What do you mean by incorrect? The implementation of the overflow behavior or the fact that it overflows? 

And which test is not ok? This one alone
```
select count() from test where toDateTime(stamp) >= parseDateTimeBestEffort('2024-11-01')
settings date_time_overflow_behavior = 'ignore';  -- returns 100
```

or the entire test suite?

Comment (Algunenano) [reply tests/queries/0_stateless/03271_date_to_datetime_saturation.reference:3]: I was talking about only this test with `ignore` but I didn't notice that you had changed the original test and now it's doing DateTime >= DateTime instead of the original Date > DateTime.

My main point is that implicit conversion for index analysis should never lead to skip valid parts. So either the conversion is lossless or, for corner cases that can't be covered, it reads the whole part (maybe with a profile event to count these currently impossible analysis). If that's how it will always work, great.

Let's please add tests with different Date vs DateTime comparison, with and without index analysis (`ORDER BY tuple()` vs `ORDER BY col`), and with lossy vs lossless conversion, extreme values and so on. That way we ensure the results are correct and we can iterate in the future if you decide to improve it somehow with some common supertype.

Comment (amosbird) [reply tests/queries/0_stateless/03271_date_to_datetime_saturation.reference:3]: > implicit conversion for index analysis should never lead to skip valid parts.

The purpose of this PR is to ensure this exactly. And the corner cases are covered in `isFunctionReallyMonotonic`.

> Let's please add tests with different Date vs DateTime comparison, with and without index analysis 

Sure. BTW, there's no need to use `ORDER BY tuple()` here. Traditionally, the `identity` function is used for this purpose.

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 3]
```diff
@@ -1036,6 +1039,24 @@ bool applyFunctionChainToColumn(
     return true;
 }
 
+bool KeyCondition::isFunctionReallyMonotonic(const IFunctionBase & func, const IDataType & arg_type) const
```
Comment (Algunenano) [inline src/Storages/MergeTree/KeyCondition.cpp:1042]: This looks like it should be part of `FunctionConvert::hasInformationAboutMonotonicity()`  or even somehow inside `ToDateTimeMonotonicity`, but not not a custom function in KeyCondition

File: src/Functions/FunctionsConversion.h [hunk 4]
```diff
@@ -2132,7 +2132,11 @@ inline bool isDateTime64(const ColumnsWithTypeAndName & arguments)
     return false;
 }
 
-template <typename ToDataType, typename Name, typename MonotonicityImpl>
+template <
+    typename ToDataType,
+    typename Name,
+    typename MonotonicityImpl,
+    FormatSettings::DateTimeOverflowBehavior template_date_time_overflow_behavior = default_date_time_overflow_behavior>
```
Comment (Algunenano) [inline src/Functions/FunctionsConversion.h:2139]: This doesn't seem to benefit at all from being a template parameter. Have you considered a constructor argument instead?

File: tests/queries/0_stateless/03271_date_to_datetime_saturation.sql [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+create table test (stamp Date) engine MergeTree order by stamp;
+
+insert into test select '2024-10-30' from numbers(100);
+insert into test select '2024-11-19' from numbers(100);
+insert into test select '2149-06-06' from numbers(100);
+
+optimize table test final;
+
+-- implicit toDateTime (always saturate)
+select count() from test where stamp >= parseDateTimeBestEffort('2024-11-01');
```
Comment (Algunenano) [inline tests/queries/0_stateless/03271_date_to_datetime_saturation.sql:12]: Could you please enable `echoOn` for this file? Otherwise matching the query with the reference is quite tiresome

**Review by Algunenano — CHANGES_REQUESTED** [review]

**Comment by Algunenano** [comment]
I'll take over and apply the changes directly

**Comment by amosbird** [comment]
> I'll take over and apply the changes directly

Oops. Apologies for the delay and thanks for taking care of this. I lost track of it earlier.

**Review by Algunenano — APPROVED** [review]
Thanks a lot for handling this, and sorry for the delay
