### PR TITLE
Parallel replicas: better initial replicas failover (2)

### LINKED ISSUE #59652: Experimental feature: "Table '...' doesn't exists" error during scaling out
When the cluster is scaling out, the queries with parallel replicas can give:
```
Code: 60. DB::Exception: Received from c-plum-qa-31-server-gh7k9cp-0.c-plum-qa-31-server-headless.ns-plum-qa-31.svc.cluster.local:9000. DB::Exception: Table default.planes_mercator does not exist. (UNKNOWN_TABLE) (version 24.0.2.54298 (official build))
```
Most likely because Replicated database creating tables with a delay
For comparison, for Distributed tables, we have automatic skipping of nodes where the table does not exist.

### PR DESCRIPTION
**Pull request by devcrafter**
Using historical information regarding replicas availability from cluster for parallel replicas to choose initial set of replicas for query execution (task-based mode). Fixes https://github.com/ClickHouse/ClickHouse/issues/59652 as well

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 82d7b2214407c68b96334d002f01ed68937e07f4 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59501/82d7b2214407c68b96334d002f01ed68937e07f4/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59501/82d7b2214407c68b96334d002f01ed68937e07f4/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by devcrafter** [comment]
First try was here -https://github.com/ClickHouse/ClickHouse/pull/58798. The idea is the same - do not convert replicas into shards. Use cluster as it's. But the implementation is simpler - shuffle connection pools for replicas according to their error status, and first use connection pools w/o errors.

File: src/Common/ProfileEvents.cpp [hunk 1]
```diff
@@ -616,6 +616,8 @@ The server successfully detected this situation and will download merged part fr
     M(InterfacePostgreSQLReceiveBytes, "Number of bytes received through PostgreSQL interfaces") \
     \
     M(ParallelReplicasUsedCount, "Number of replicas used to execute a query with task-based parallel replicas") \
+    M(ParallelReplicasAvailableCount, "Number of replicas available to execute a query with task-based parallel replicas") \
+    M(ParallelReplicasUnavailableCount, "Number of replicas which was chosen, but unavailable, to execute a query with task-based parallel replicas") \
```
Comment (nickitat) [inline src/Common/ProfileEvents.cpp:620]: maybe 

```suggestion
    M(ParallelReplicasUnavailableCount, "Number of replicas which were chosen, but found to be unavailable during the query with task-based parallel replicas") \
```

?

File: src/Interpreters/ClusterProxy/executeQuery.cpp [hunk 2]
```diff
@@ -395,17 +396,18 @@ void executeQueryWithParallelReplicas(
...
         // shard_num is 1-based, but getClusterWithSingleShard expects 0-based index
-        auto single_shard_cluster = not_optimized_cluster->getClusterWithSingleShard(shard_num - 1);
-        // convert cluster to representation expected by parallel replicas
-        new_cluster = single_shard_cluster->getClusterWithReplicasAsShards(settings, settings.max_parallel_replicas);
+        new_cluster = not_optimized_cluster->getClusterWithSingleShard(shard_num - 1);
     }
     else
     {
-        new_cluster = not_optimized_cluster->getClusterWithReplicasAsShards(settings, settings.max_parallel_replicas);
+        if (not_optimized_cluster->getShardCount() > 1)
```
Comment (nickitat) [inline src/Interpreters/ClusterProxy/executeQuery.cpp:403]: minor. maybe remove the surrounding `else` and do the check for `new_cluster`

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 3]
```diff
@@ -399,51 +399,33 @@ void ReadFromParallelRemoteReplicasStep::initializePipeline(QueryPipelineBuilder
...
-        if (shard.isLocal())
-        {
-            IConnections::ReplicaInfo replica_info
-            {
-                .all_replicas_count = all_replicas_count,
-                /// `shard_num` will be equal to the number of the given replica in the cluster (set by `Cluster::getClusterWithReplicasAsShards`).
-                /// we should use this number specifically because efficiency of data distribution by consistent hash depends on it.
-                .number_of_current_replica = shard.shard_num - 1,
-            };
+    chassert(cluster->getShardCount() == 1);
```
Comment (nickitat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:415]: minor. maybe move the check to l.401

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 4]
```diff
@@ -399,51 +399,33 @@ void ReadFromParallelRemoteReplicasStep::initializePipeline(QueryPipelineBuilder
...
+    auto shuffled_pool = shard.pool->getShuffledPools(current_settings);
+    shuffled_pool.resize(all_replicas_count);
```
Comment (nickitat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:417]: not needed?

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 5]
```diff
@@ -399,51 +399,33 @@ void ReadFromParallelRemoteReplicasStep::initializePipeline(QueryPipelineBuilder
...
-        {
-            IConnections::ReplicaInfo replica_info
-            {
-                .all_replicas_count = all_replicas_count,
-                /// `shard_num` will be equal to the number of the given replica in the cluster (set by `Cluster::getClusterWithReplicasAsShards`).
-                /// we should use this number specifically because efficiency of data distribution by consistent hash depends on it.
-                .number_of_current_replica = shard.shard_num - 1,
-            };
+    chassert(cluster->getShardCount() == 1);
+    auto shuffled_pool = shard.pool->getShuffledPools(current_settings);
```
Comment (nickitat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:416]: wouldn't it break consistency of replica numbers assignment?

File: src/QueryPipeline/RemoteQueryExecutor.cpp [hunk 6]
```diff
@@ -62,6 +64,55 @@ RemoteQueryExecutor::RemoteQueryExecutor(
...
+        std::vector<IConnectionPool::Entry> connection_entries;
+        if (!result.entry.isNull() && result.is_usable)
+        {
+            if (extension_ && extension_->parallel_reading_coordinator)
+                ProfileEvents::increment(ProfileEvents::ParallelReplicasAvailableCount);
+
+            connection_entries.emplace_back(std::move(result.entry));
+        }
+
+        auto res = std::make_unique<MultiplexedConnections>(std::move(connection_entries), context->getSettingsRef(), throttler);
```
Comment (nickitat) [inline src/QueryPipeline/RemoteQueryExecutor.cpp:108]:
```suggestion
        auto res = std::make_unique<MultiplexedConnections>(std::move(connection_entries), current_settings, throttler);
```

File: src/Common/ProfileEvents.cpp (hunk 1 above)
Comment (devcrafter) [reply src/Common/ProfileEvents.cpp:620]: Thanks. Will improve

File: src/Processors/QueryPlan/ReadFromRemote.cpp (hunk 4 above)
Comment (devcrafter) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:417]: Needed. The shuffled pool contains pools for all replicas in the cluster, but we need a subset

File: src/Processors/QueryPlan/ReadFromRemote.cpp (hunk 5 above)
Comment (devcrafter) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:416]: It can be if `max_parallel_replicas` >= number of replicas. Need to fix this case

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 7]
```diff
@@ -399,51 +400,44 @@ void ReadFromParallelRemoteReplicasStep::initializePipeline(QueryPipelineBuilder
...
+    else
     {
-        if (current_shard->isLocal())
-        {
-            ++current_shard;
-            continue;
-        }
+        /// try to preserve replicas order if all replicas in cluster are used for query execution
+        /// it's important for data locality during query execution
+        auto priority_func = [](size_t i) { return Priority{static_cast<Int64>(i)}; };
```
Comment (nickitat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:427]: at what point then we will look at availability history (if not inside priority function)?

**Review by nickitat — APPROVED** [review]

File: src/Processors/QueryPlan/ReadFromRemote.cpp (hunk 7 above)
Comment (devcrafter) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:427]: `getShuffledPools()` sorts pools not only according to the `priority` but by several other parameters as well, connectivity `error_count` is among them, see:
https://github.com/ClickHouse/ClickHouse/blob/510f90edf8b70fbc7b5ae11f2b1355ee3150e8a6/src/Common/PoolWithFailoverBase.h#L347-L351

In a healthy cluster, `error_count, slowdown_count` are zeros, `config_priority` usually the same, - in such a case, pools will be shuffled according to the `priority`. So, effectively, here, the pools will not be shuffled
