### PR TITLE
Fix character escaping in the PostgreSQL engine

### LINKED ISSUE #49821: Unable to include single quotes in a PostgreSQL Engine table query.
ClickHouse version: 22.3.19.6
PostgreSQL version: 14.7

When I run queries on a PostgreSQL Engine table that include a single quote in the keyword, I get a syntax error even if it's escaped. I've tried both "''"(two single quotes) and "\\'".

Queries
`select name from table1 where name like '%a''a%';
select name from table1 where name like '%a\'a%';`

Error:
`[07000][1002] std::exception. Code: 1001, type: pqxx::syntax_error, e.what() = ERROR: syntax error at or near "a" LINE 1: ..."name" FROM "table1" WHERE "name" LIKE '%a\'a%') TO ST...`

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix character escaping in the PostgreSQL engine (`\'` -> `''`, `\\` -> `\`). Closes https://github.com/ClickHouse/ClickHouse/issues/49821.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 3c6d140c179c29ce890f190529e29d1e9ec3db8b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53250/3c6d140c179c29ce890f190529e29d1e9ec3db8b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/StoragePostgreSQL.cpp [hunk 1]
```diff
@@ -123,6 +124,10 @@ Pipe StoragePostgreSQL::read(
         column_names_,
         storage_snapshot->metadata->getColumns().getOrdinary(),
         IdentifierQuotingStyle::DoubleQuotes, remote_table_schema, remote_table_name, context_);
+
+    /// Single quotes in PostgreSQL are escaped through repetition
+    boost::replace_all(query, "\\'", "''");
```
Comment (alexey-milovidov) [inline src/Storages/StoragePostgreSQL.cpp:129]: It does not work for this ClickHouse query:

```
SELECT '\\\''
```

it will translate it to the following query:
```
SELECT '\\'''
```

while Postgres will expect the following query:
```
SELECT '\'''
```

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by alexey-milovidov** [comment]
Compare this query in MySQL and Postgres: https://www.db-fiddle.com/f/2finNynPKnTcM7BnWnmZmm/0

**Comment by alexey-milovidov** [comment]
I think it should be our formatter's setting:
```
    IAST::FormatSettings settings(
            out, /*one_line*/ true, /*hilite*/ false,
            /*always_quote_identifiers*/ identifier_quoting_style != IdentifierQuotingStyle::None,
            /*identifier_quoting_style*/ identifier_quoting_style);

    select->format(settings);
```

Let's add string_literal_quoting_style somewhere around.

**Review by alexey-milovidov — APPROVED** [review]
