### PR TITLE
Fix pushdown for join with external table

### LINKED ISSUE #65969: Incorrect optimization when left join postgresql engine with null condition
**Describe what's wrong**

If you do left join a MergeTree Engine table and a PostgreSQL Engine table and add a condition (is null) for the PostgreSQL Engine table to the WHERE condition, the WHERE condition is applied before joining.

**How to reproduce**

> ch version: 24.5.1.1763
> pg version: 12.6

pg table
```
create table public.pg_table
(
    id int,
    name varchar(10)
);

insert into public.pg_table values (1, 'name 1'), (2, 'name 2'), (3, 'name 3');
```

ch tables
```
-- pg_table (PostgreSQL Engine)
create table default.pg_table 
(
    id Int32,
    name String
)
ENGINE = PostgreSQL(PG_NAMED_COLLECTION, table = 'pg_table');

-- ch_table
create table default.ch_table 
(
    id Int32,
    pg_id Int32
)
engine = MergeTree
order by id;

insert into default.ch_table values (1, 1), (2, 2), (3, 3), (4, 1), (5, 2);
```

query
```
select
    t1.id,
    t1.pg_id,
    t2.id AS id_of_pg_table,
    t2.name AS name_of_pg_table
from default.ch_table t1
left outer join default.pg_table t2
on t1.pg_id = t2.id
where name_of_pg_table is null;
```

**Expected behavior**

return nothing.

**Error message and/or stacktrace**

image

**Additional context**

https://clickhousedb.slack.com/archives/CU478UEQZ/p1719802361432549

### PR DESCRIPTION
**Pull request by vdimir**
Fix possible incorrect result for queries joining and filtering table external engine (like PostgreSQL), due to too agressive filter pushdown. Since now, conditions from where section won't be send to external database in case of outer join with external table.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

* Fix possible incorrect result for queries joining and filtering table external engine (like
PostgreSQL), due to too aggressive filter pushdown. Since now, conditions
from where section won't be send to external database in case of outer
join with external table.

close #65969

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 0a7a560e30e18a7815a56814a0bb20f6cb28110b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66402/0a7a560e30e18a7815a56814a0bb20f6cb28110b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
> Builds Pending — 13 of 21 builds are missing. 18/31 artifact groups are OK [Details](https://s3.amazonaws.com/clickhouse-test-reports/66402/7781067ba18ed4817770a804f4407c670dea5550/builds/report.html)

File: src/Storages/transformQueryForExternalDatabaseAnalyzer.cpp [hunk 1]
```diff
@@ -76,7 +93,13 @@ ASTPtr getASTForExternalDatabaseFromQueryTree(const QueryTreeNodePtr & query_tre
     if (union_ast->list_of_selects->children.size() != 1)
         throw Exception(ErrorCodes::UNSUPPORTED_METHOD, "QueryNode AST is not a single ASTSelectQuery, got {}", union_ast->list_of_selects->children.size());
 
-    return union_ast->list_of_selects->children.at(0);
+    ASTPtr select_query = union_ast->list_of_selects->children.at(0);
+    auto * select_query_typed = select_query->as<ASTSelectQuery>();
+    if (!select_query_typed)
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Expected ASTSelectQuery, got {}", select_query ? select_query->formatForErrorMessage() : "nullptr");
+    if (!allow_where)
+        select_query_typed->setExpression(ASTSelectQuery::Expression::WHERE, nullptr);
```
Comment (novikd) [inline src/Storages/transformQueryForExternalDatabaseAnalyzer.cpp:101]: Probably, it's more correct to modify the WHERE filter expression, because it can contain references to both tables. We should leave only conjunctions that are related to the proper table.

Comment (vdimir) [reply src/Storages/transformQueryForExternalDatabaseAnalyzer.cpp:101]: It works like that now, but for OUTER join, we don't want to keep filters for related table either.

```sql

SELECT * FROM ( SELECT arrayJoin([1, 2]) AS a ) AS t1
FULL OUTER JOIN ( SELECT arrayJoin([1, 2]) AS a ) AS t2 ON t1.a = t2.a
WHERE t1.a != 1

   ┌─a─┬─t2.a─┐
1. │ 2 │    2 │
   └───┴──────┘
   
SELECT * FROM ( SELECT arrayJoin([1, 2]) AS a WHERE a != 1 ) AS t1
FULL OUTER JOIN ( SELECT arrayJoin([1, 2]) AS a ) AS t2 ON t1.a = t2.a
WHERE t1.a != 1

   ┌─a─┬─t2.a─┐
1. │ 2 │    2 │
2. │ 0 │    1 │
   └───┴──────┘
```

**Comment by vdimir** [comment]
> Stateless tests (msan) [1/3] — fail: 1, passed: 2245, skipped: 27 [Details](https://s3.amazonaws.com/clickhouse-test-reports/66402/480c5463593fc8997f9810979e87af99143836e4/stateless_tests__msan__[1_3].html)

`01459_manual_write_to_replicas_quorum_detach_attach` https://github.com/ClickHouse/ClickHouse/issues/64652#issuecomment-2232856346
