### PR TITLE
fix flaky test 03237_create_or_replace_view_atomically_with_atomic_engine

### LINKED ISSUE #70319: Test 03237_create_or_replace_view_atomically_with_atomic_engine is flaky
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDMyMzdfY3JlYXRlX29yX3JlcGxhY2Vfdmlld19hdG9taWNhbGx5X3dpdGhfYXRvbWljX2VuZ2luZSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

cc @tuanpach

### PR DESCRIPTION
**Pull request by hanfei1991**
There is no DDLGuard when we get table uuid and storage ptr during executing SELECT queries.
so there could be `drop` / `rename` happening between [get uuid](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L226) and [get storage ptr](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L245)

In this case we should ignore errors like `UNKNOWN_TABLE` / `TABLE_UUID_MISMATCH`, just like test [01502_long_log_tinylog_deadlock_race.sh](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01502_long_log_tinylog_deadlock_race.sh) 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix https://github.com/ClickHouse/ClickHouse/issues/70319

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by evillique — APPROVED** [review]

**Comment by hanfei1991** [comment]
[Test 01169_alter_partition_isolation_stress is flaky](https://github.com/ClickHouse/ClickHouse/issues/70738)

**Comment by hanfei1991** [comment]
@Algunenano As I understand, the `create or replace` is indeed atomic, but `select` is not atomic between [get uuid](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L226) and [get storage ptr](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L245)

**Comment by Algunenano** [comment]
Then that's a bug that should be fixed, right?

**Comment by hanfei1991** [comment]
@Algunenano yes, it should be fixed, I just supressed some errors

**Comment by tuanpach** [comment]
In [JoinedTables::getLeftTableStorage](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L215C1-L246C2), after [table_id = context->resolveStorageID...](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L226), the table might be renamed (or exchanged). So table and DB names in `table_id` are no longer matched when invoking [DatabaseCatalog::instance().getTable](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/JoinedTables.cpp#L245).

I think we can fix it by
1. Skipping `resolveStorageID`, so we fetch the table by DB and table names.
2. Or after `DatabaseCatalog::instance().getTable`, if the error is `TABLE_UUID_MISMATCH `, try to fetch with DB and table names only.

File: tests/queries/0_stateless/03237_create_or_replace_view_atomically_with_atomic_engine.sh [hunk 1]
```diff
@@ -18,7 +19,7 @@ export -f create_or_replace_view_thread;
 function select_view_thread
 {
     for _ in {1..20}; do
-        $CLICKHOUSE_CLIENT --query "SELECT * FROM ${CLICKHOUSE_DATABASE}_db.test_view" > /dev/null
+        $CLICKHOUSE_CLIENT --query "SELECT * FROM ${CLICKHOUSE_DATABASE}_db.test_view FORMAT NULL"  | grep -v -P 'Code: (60|741)'
```
Comment (azat) [inline tests/queries/0_stateless/03237_create_or_replace_view_atomically_with_atomic_engine.sh:22]: BTW this does not fix it at all, since `grep` only stdout

Comment (alexey-milovidov) [reply tests/queries/0_stateless/03237_create_or_replace_view_atomically_with_atomic_engine.sh:22]: @azat, You are totally right, but better to fix it immediately instead of giving me 2.5 months of suffering? https://github.com/ClickHouse/ClickHouse/pull/80412
