### PR TITLE
fix bug in minMap and maxMap with zero values

### LINKED ISSUE #16087: maxMap is removing entries with empty string or zero value
**Describe the unexpected behaviour**
maxMap is removing entries with empty string or zero value.

**How to reproduce**

String array
SELECT maxMap(a, b) from values ('a Array(String), b Array(String)',(['A'],['']),(['B'],['']));

┌─maxMap(a, b) ─┐
│ ([],[])                    │ 
└───────────┘

Numeric array
`SELECT maxMap(a, b) from values ('a Array(String), b Array(UInt64)',(['A'],[0]),(['B'],[0]));

┌─maxMap(a, b) ─┐
│ ([],[])                    │ 
└───────────┘
`
It happens with all versions published.

**Expected behavior**
We expect this to maintain those keys with its value (empty string or zero).

### PR DESCRIPTION
**Pull request by ildus**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make the behaviour of `minMap` and `maxMap` more desireable. It will not skip zero values in the result. Fixes #16087.

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionSumMap.h [hunk 1]
```diff
@@ -56,7 +56,7 @@ struct AggregateFunctionMapData
   * minMap and maxMap share the same idea, but calculate min and max correspondingly.
   */
 
-template <typename T, typename Derived, typename Visitor, bool overflow, bool tuple_argument>
+template <typename T, typename Derived, typename Visitor, bool overflow, bool tuple_argument, bool compact>
```
Comment (Avogar) [inline src/AggregateFunctions/AggregateFunctionSumMap.h:59]: I think it would be better to write a comment on why we need compact.

File: tests/queries/0_stateless/01280_min_map_max_map.sql [hunk 2]
```diff
@@ -31,3 +31,10 @@ select maxMap(val, cnt) from values ('val Array(Date), cnt Array(Int16)',  ([1],
 select maxMap(val, cnt) from values ('val Array(DateTime(\'Europe/Moscow\')), cnt Array(Int32)',  ([1], [1]), ([1], [2]));
 select maxMap(val, cnt) from values ('val Array(Decimal(10, 2)), cnt Array(Int16)',  (['1.01'], [1]), (['1.01'], [2]));
 select maxMap(val, cnt) from values ('val Array(Enum16(\'a\'=1)), cnt Array(Int16)',  (['a'], [1]), (['a'], [2]));
+
+-- bugfix, minMap and maxMap should not remove values with zero and empty strings but this behavior should not affect sumMap
+select minMap(val, cnt) from values ('val Array(UInt64), cnt Array(UInt64)',  ([1], [0]), ([2], [0]));
+select maxMap(val, cnt) from values ('val Array(UInt64), cnt Array(UInt64)',  ([1], [0]), ([2], [0]));
+select minMap(val, cnt) from values ('val Array(String), cnt Array(String)',  (['A'], ['']), (['B'], ['']));
+select minMap(val, cnt) from values ('val Array(String), cnt Array(String)',  (['A'], ['']), (['B'], ['']));
```
Comment (Avogar) [inline tests/queries/0_stateless/01280_min_map_max_map.sql:39]: I guess you wanted to use `maxMap` here

**Review by Avogar — APPROVED** [review]
