### PR TITLE
Fix inserting to temporary tables via gRPC.

### LINKED ISSUE #34347: 21.12 crashed after running gRPC test
It happened a few times that 21.12 crashed when testing JDBC driver and gRPC Java client. Upgrade to 22.1 seemed resolve the issue.
```
2022.02.05 17:51:05.133163 [ 290 ] {} <Fatal> BaseDaemon: ########################################
2022.02.05 17:51:05.133245 [ 290 ] {} <Fatal> BaseDaemon: (version 21.12.3.32 (official build), build id: FA4A7F489F3FF6E3) (from thread 282) (query_id: 81f325bc-c321-4aa6-ba6b-2273ab694d79) Received signal Segmentation fault (11)
2022.02.05 17:51:05.133259 [ 290 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2022.02.05 17:51:05.133275 [ 290 ] {} <Fatal> BaseDaemon: Stack trace: 0x16f33e1d 0x16f3485c 0x12cab511 0x13346201 0x13536cc4 0x13d6a6b8 0x13d6a585 0x13d64224 0xa25a3b7 0xa25ddbd 0x7fa2d06e6609 0x7fa2d060d293
2022.02.05 17:51:05.133322 [ 290 ] {} <Fatal> BaseDaemon: 2. Poco::Net::SocketAddress::family() const @ 0x16f33e1d in /usr/bin/clickhouse
2022.02.05 17:51:05.133335 [ 290 ] {} <Fatal> BaseDaemon: 3. Poco::Net::SocketAddress::operator=(Poco::Net::SocketAddress const&) @ 0x16f3485c in /usr/bin/clickhouse
2022.02.05 17:51:05.133348 [ 290 ] {} <Fatal> BaseDaemon: 4. DB::ClientInfo::operator=(DB::ClientInfo const&) @ 0x12cab511 in /usr/bin/clickhouse
2022.02.05 17:51:05.133359 [ 290 ] {} <Fatal> BaseDaemon: 5. DB::QueryStatus::getInfo(bool, bool, bool) const @ 0x13346201 in /usr/bin/clickhouse
2022.02.05 17:51:05.133368 [ 290 ] {} <Fatal> BaseDaemon: 6. ? @ 0x13536cc4 in /usr/bin/clickhouse
2022.02.05 17:51:05.133377 [ 290 ] {} <Fatal> BaseDaemon: 7. ? @ 0x13d6a6b8 in /usr/bin/clickhouse
2022.02.05 17:51:05.133384 [ 290 ] {} <Fatal> BaseDaemon: 8. ? @ 0x13d6a585 in /usr/bin/clickhouse
2022.02.05 17:51:05.133388 [ 290 ] {} <Fatal> BaseDaemon: 9. ? @ 0x13d64224 in /usr/bin/clickhouse
2022.02.05 17:51:05.133402 [ 290 ] {} <Fatal> BaseDaemon: 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa25a3b7 in /usr/bin/clickhouse
2022.02.05 17:51:05.133409 [ 290 ] {} <Fatal> BaseDaemon: 11. ? @ 0xa25ddbd in /usr/bin/clickhouse
2022.02.05 17:51:05.133418 [ 290 ] {} <Fatal> BaseDaemon: 12. ? @ 0x7fa2d06e6609 in ?
2022.02.05 17:51:05.133425 [ 290 ] {} <Fatal> BaseDaemon: 13. __clone @ 0x7fa2d060d293 in ?
2022.02.05 17:51:05.234791 [ 290 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 5BEBF5792A40F7E345921EDA3698245B. There is no information about the reference checksum.
```

Besides above failure, there are a few more issues I noticed during the test:
1. error like below before crash - might be a client-side issue
  ```
  2022.02.05 17:51:01.120896 [ 270 ] {5d1feb82-586c-4b48-ab93-ac9dcf2b3a88} <Error> grpc: prepare_application_metadata: {"created":"@1644112261.120874665","description":"Unallowed duplicate metadata","file":"../contrib/grpc/src/core/lib/transport/metadata_batch.cc","file_line":104,"key":"grpc-internal-encoding-request","value":"gzip"} (../contrib/grpc/src/core/lib/surface/call.cc:953)
  ```
2. session seems not working properly via grpc
  ```sql
  drop temporary table if exsits my_temp_table;
  create temporary table my_temp_table(a Int8);
  -- below did not work due to table not exist
  insert into my_temp_table values(2)
  ```
3. Session is locked by a concurrent client - happens occasionally on both 21.3 and 21.8
4. INTERNAL: Unable to parse request - happens occasionally on both 21.3 and 21.8

### PR DESCRIPTION
**Pull request by vitlibar**
Changelog category:
- Bug Fix

Changelog entry:
Fix inserting to temporary tables via gRPC. This PR fixes https://github.com/ClickHouse/ClickHouse/issues/34347, issue `#2`.

### CODE REVIEW

**Review by alesapin — COMMENTED** [review]
Can you explain please, why this code is redundant and why it fixed the bug?

File: src/Server/GRPCServer.cpp [hunk 1]
```diff
@@ -990,41 +989,10 @@ namespace
...
-                auto table_id = StorageID::createEmpty();
-
-                if (insert_query->table_id)
-                {
-                    table_id = query_context->resolveStorageID(insert_query->table_id, Context::ResolveOrdinary);
-                }
-                else
-                {
-                    StorageID local_table_id(insert_query->getDatabase(), insert_query->getTable());
-                    table_id = query_context->resolveStorageID(local_table_id, Context::ResolveOrdinary);
```
Comment (vitlibar) [inline src/Server/GRPCServer.cpp:1010]: Here was the bug, because `Context::ResolveOrdinary` doesn't include `Context::ResolveExternal`, i.e. it doesn't resolve temporary and external tables. So to fix the bug it seemed it was enough just to replace `Context::ResolveOrdinary` with `Context::ResolveAll`.

But then I found that this code was probably copied from [InputStreamFromASTInsertQuery.cpp](https://github.com/ClickHouse/ClickHouse/blob/aeac8cb6212ce3658a5ffb99116ddedf3910ac65/src/DataStreams/InputStreamFromASTInsertQuery.cpp#L59-L65) and that file was removed with DataStreams. And now there is no such code for other handlers (tcp, http). Anyway for gRPC we have test [test_grpc_protocol/test.py::test_insert_default_column](https://github.com/ClickHouse/ClickHouse/blob/b2ba0c4320044bca6c98aa304450c869843b6c8a/tests/integration/test_grpc_protocol/test.py#L179) which checks that gRPC can add default columns while inserting.

Comment (vitlibar) [reply src/Server/GRPCServer.cpp:1010]: @KochetovNicolai Сan you check whether `AddingDefaultsTransform` was necessary here?

**Review by alesapin — COMMENTED** [review]
LGTM
