### PR TITLE
Fix ssl handshake error processing

### LINKED ISSUE #67912: `test_accept_invalid_certificate/test.py::test_strict_reject_with_config` has failed
Report: https://s3.amazonaws.com/clickhouse-test-reports/67560/5d0c179ad190dcedf85a32821ebf6d25ec2b53a6/integration_tests__asan__old_analyzer__[4_6].html

### LINKED ISSUE #68254: `test_ssl_cert_authentication/test.py::test_native_wrong_cert` is flaky
[CI DB](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3Rfc3NsX2NlcnRfYXV0aGVudGljYXRpb24vdGVzdC5weTo6dGVzdF9uYXRpdmVfd3JvbmdfY2VydCUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l) - [example](https://s3.amazonaws.com/clickhouse-test-reports/67554/6cde029ed9cd6a22937193e12863974f1fa8f160/integration_tests__aarch64__[6_6].html)

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

fixes flaky test_accept_invalid_certificate/test.py::test_strict_reject_with_config
closes #67912
closes #68254

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit f7cc3e9c59947af5b753b154f5b1b59d26fe67d4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68866/f7cc3e9c59947af5b753b154f5b1b59d26fe67d4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: base/poco/NetSSL_OpenSSL/src/SecureSocketImpl.cpp [hunk 1]
```diff
@@ -311,6 +311,14 @@ int SecureSocketImpl::sendBytes(const void* buffer, int length, int flags)
 	while (mustRetry(rc, remaining_time));
 	if (rc <= 0)
 	{
+		// At this stage we still can have last not yet recieved SSL message containing SSL error
```
Comment (nikitamikhaylov) [inline base/poco/NetSSL_OpenSSL/src/SecureSocketImpl.cpp:314]:
```suggestion
		// At this stage we still can have last not yet received SSL message containing SSL error
```

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by yakov-olkhovskiy** [comment]
should also fix #68254
