### PR TITLE
Correct behaviour with unknown methods

### LINKED ISSUE #29050: Hung in some curl queries
**Describe the unexpected behaviour**
Some curl commands hung while connecting to ClickHouse server.

**How to reproduce**
Try to connect to ClickHouse server using:
`curl 'http://localhost:8123?add_http_cors_header=1' -v -X aaa`

Every word can be used instead of method name. It will hung like it is waiting for something.

**Expected behavior**
Get message about unknown method.

**Error message and/or stacktrace**
If curl command is canceled server have stacktrace
```
2021.09.15 14:57:20.907992 [ 45369 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: aaa, Address: 127.0.0.1:46960, User-Agent: curl/7.68.0, Content Type: , Transfer Encoding: identity, X-Forwarded-For: (none)
HTTP HANDLER
2021.09.15 14:57:20.908251 [ 45369 ] {} <Trace> DynamicQueryHandler: Request URI: /?add_http_cors_header=1
12345METHOD IS aaaUNKOWN 1
DYNAMIC GET QUERY 
2021.09.15 14:57:21.000264 [ 45515 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 624.21 MiB, peak 669.07 MiB, will set to 623.16 MiB (RSS), difference: -1.05 MiB
2021.09.15 14:57:22.406731 [ 45369 ] {6f2f1da6-212c-4246-8e8c-cda1f84426c1} <Debug> executeQuery: (from 127.0.0.1:46960) 
2021.09.15 14:57:22.406989 [ 45369 ] {6f2f1da6-212c-4246-8e8c-cda1f84426c1} <Error> executeQuery: Code: 62. DB::Exception: Empty query. (SYNTAX_ERROR) (version 21.11.1.1) (from 127.0.0.1:46960) (in query: ), Stack trace (when copying this message, always include the lines below):

0. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x132978e2 in /home/illusion/ClickHouse/build/programs/clickhouse
1. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:111: std::exception::exception() @ 0x132978b0 in /home/illusion/ClickHouse/build/programs/clickhouse
2. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x23c8d422 in /home/illusion/ClickHouse/build/programs/clickhouse
3. /home/illusion/ClickHouse/build/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1327928d in /home/illusion/ClickHouse/build/programs/clickhouse
4. /home/illusion/ClickHouse/build/../src/Parsers/parseQuery.cpp:348: DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1ffa1ec2 in /home/illusion/ClickHouse/build/programs/clickhouse
5. /home/illusion/ClickHouse/build/../src/Parsers/parseQuery.cpp:360: DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) @ 0x1ffa1fa6 in /home/illusion/ClickHouse/build/programs/clickhouse
6. /home/illusion/ClickHouse/build/../src/Interpreters/executeQuery.cpp:416: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1eba6cdd in /home/illusion/ClickHouse/build/programs/clickhouse
7. /home/illusion/ClickHouse/build/../src/Interpreters/executeQuery.cpp:1042: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void ()>) @ 0x1ebaa3f9 in /home/illusion/ClickHouse/build/programs/clickhouse
8. /home/illusion/ClickHouse/build/../src/Server/HTTPHandler.cpp:755: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x1f6d7b42 in /home/illusion/ClickHouse/build/programs/clickhouse
9. /home/illusion/ClickHouse/build/../src/Server/HTTPHandler.cpp:883: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1f6d98aa in /home/illusion/ClickHouse/build/programs/clickhouse
10. /home/illusion/ClickHouse/build/../src/Server/HTTP/HTTPServerConnection.cpp:48: DB::HTTPServerConnection::run() @ 0x1f764e99 in /home/illusion/ClickHouse/build/programs/clickhouse
11. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x23bc5a19 in /home/illusion/ClickHouse/build/programs/clickhouse
12. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x23bc6283 in /home/illusion/ClickHouse/build/programs/clickhouse
13. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x23d15e94 in /home/illusion/ClickHouse/build/programs/clickhouse
14. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x23d1297a in /home/illusion/ClickHouse/build/programs/clickhouse
15. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x23d11722 in /home/illusion/ClickHouse/build/programs/clickhouse
16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

HERE
2021.09.15 14:57:22.407556 [ 45369 ] {6f2f1da6-212c-4246-8e8c-cda1f84426c1} <Error> DynamicQueryHandler: Code: 62. DB::Exception: Empty query. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x132978e2 in /home/illusion/ClickHouse/build/programs/clickhouse
1. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:111: std::exception::exception() @ 0x132978b0 in /home/illusion/ClickHouse/build/programs/clickhouse
2. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x23c8d422 in /home/illusion/ClickHouse/build/programs/clickhouse
3. /home/illusion/ClickHouse/build/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1327928d in /home/illusion/ClickHouse/build/programs/clickhouse
4. /home/illusion/ClickHouse/build/../src/Parsers/parseQuery.cpp:348: DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1ffa1ec2 in /home/illusion/ClickHouse/build/programs/clickhouse
5. /home/illusion/ClickHouse/build/../src/Parsers/parseQuery.cpp:360: DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) @ 0x1ffa1fa6 in /home/illusion/ClickHouse/build/programs/clickhouse
6. /home/illusion/ClickHouse/build/../src/Interpreters/executeQuery.cpp:416: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1eba6cdd in /home/illusion/ClickHouse/build/programs/clickhouse
7. /home/illusion/ClickHouse/build/../src/Interpreters/executeQuery.cpp:1042: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void ()>) @ 0x1ebaa3f9 in /home/illusion/ClickHouse/build/programs/clickhouse
8. /home/illusion/ClickHouse/build/../src/Server/HTTPHandler.cpp:755: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x1f6d7b42 in /home/illusion/ClickHouse/build/programs/clickhouse
9. /home/illusion/ClickHouse/build/../src/Server/HTTPHandler.cpp:883: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1f6d98aa in /home/illusion/ClickHouse/build/programs/clickhouse
10. /home/illusion/ClickHouse/build/../src/Server/HTTP/HTTPServerConnection.cpp:48: DB::HTTPServerConnection::run() @ 0x1f764e99 in /home/illusion/ClickHouse/build/programs/clickhouse
11. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x23bc5a19 in /home/illusion/ClickHouse/build/programs/clickhouse
12. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x23bc6283 in /home/illusion/ClickHouse/build/programs/clickhouse
13. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x23d15e94 in /home/illusion/ClickHouse/build/programs/clickhouse
14. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x23d1297a in /home/illusion/ClickHouse/build/programs/clickhouse
15. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x23d11722 in /home/illusion/ClickHouse/build/programs/clickhouse
16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.11.1.1)
2021.09.15 14:57:22.408729 [ 45369 ] {6f2f1da6-212c-4246-8e8c-cda1f84426c1} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 24. DB::Exception: Cannot write to ostream at offset 146. (CANNOT_WRITE_TO_OSTREAM), Stack trace (when copying this message, always include the lines below):

0. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x132978e2 in /home/illusion/ClickHouse/build/programs/clickhouse
1. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:111: std::exception::exception() @ 0x132978b0 in /home/illusion/ClickHouse/build/programs/clickhouse
2. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x23c8d422 in /home/illusion/ClickHouse/build/programs/clickhouse
3. /home/illusion/ClickHouse/build/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1327928d in /home/illusion/ClickHouse/build/programs/clickhouse
4. /home/illusion/ClickHouse/build/../src/IO/WriteBufferFromOStream.cpp:22: DB::WriteBufferFromOStream::nextImpl() @ 0x134363c5 in /home/illusion/ClickHouse/build/programs/clickhouse
5. /home/illusion/ClickHouse/build/../src/IO/WriteBuffer.h:47: DB::WriteBuffer::next() @ 0x13280974 in /home/illusion/ClickHouse/build/programs/clickhouse
6. /home/illusion/ClickHouse/build/../src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:128: DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x1f76e3d1 in /home/illusion/ClickHouse/build/programs/clickhouse
7. /home/illusion/ClickHouse/build/../src/IO/WriteBuffer.h:47: DB::WriteBuffer::next() @ 0x13280974 in /home/illusion/ClickHouse/build/programs/clickhouse
8. /home/illusion/ClickHouse/build/../src/Server/HTTPHandler.cpp:831: DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1f6d8f7d in /home/illusion/ClickHouse/build/programs/clickhouse
9. /home/illusion/ClickHouse/build/../src/Server/HTTPHandler.cpp:901: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1f6d9eda in /home/illusion/ClickHouse/build/programs/clickhouse
10. /home/illusion/ClickHouse/build/../src/Server/HTTP/HTTPServerConnection.cpp:48: DB::HTTPServerConnection::run() @ 0x1f764e99 in /home/illusion/ClickHouse/build/programs/clickhouse
11. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x23bc5a19 in /home/illusion/ClickHouse/build/programs/clickhouse
12. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x23bc6283 in /home/illusion/ClickHouse/build/programs/clickhouse
13. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x23d15e94 in /home/illusion/ClickHouse/build/programs/clickhouse
14. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x23d1297a in /home/illusion/ClickHouse/build/programs/clickhouse
15. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x23d11722 in /home/illusion/ClickHouse/build/programs/clickhouse
16. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
17. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.11.1.1)
2021.09.15 14:57:22.408946 [ 45369 ] {6f2f1da6-212c-4246-8e8c-cda1f84426c1} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.09.15 14:57:22.409987 [ 45369 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, I/O error: Broken pipe, Stack trace (when copying this message, always include the lines below):

0. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:133: std::exception::capture() @ 0x132978e2 in /home/illusion/ClickHouse/build/programs/clickhouse
1. /home/illusion/ClickHouse/build/../contrib/libcxx/include/exception:111: std::exception::exception() @ 0x132978b0 in /home/illusion/ClickHouse/build/programs/clickhouse
2. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x23c8d422 in /home/illusion/ClickHouse/build/programs/clickhouse
3. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Exception.cpp:141: Poco::RuntimeException::RuntimeException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x23c90987 in /home/illusion/ClickHouse/build/programs/clickhouse
4. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Exception.cpp:160: Poco::IOException::IOException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x23c94d07 in /home/illusion/ClickHouse/build/programs/clickhouse
5. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/SocketImpl.cpp:1074: Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x23bbbe30 in /home/illusion/ClickHouse/build/programs/clickhouse
6. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/SocketImpl.cpp:993: Poco::Net::SocketImpl::error(int) @ 0x23bbc4e4 in /home/illusion/ClickHouse/build/programs/clickhouse
7. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/SocketImpl.cpp:332: Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x23bbd0a5 in /home/illusion/ClickHouse/build/programs/clickhouse
8. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/StreamSocketImpl.cpp:63: Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x23bc42e1 in /home/illusion/ClickHouse/build/programs/clickhouse
9. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/StreamSocket.cpp:114: Poco::Net::StreamSocket::sendBytes(void const*, int, int) @ 0x23bc0a32 in /home/illusion/ClickHouse/build/programs/clickhouse
10. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/HTTPSession.cpp:152: Poco::Net::HTTPSession::write(char const*, long) @ 0x23b9ae8e in /home/illusion/ClickHouse/build/programs/clickhouse
11. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/HTTPChunkedStream.cpp:146: Poco::Net::HTTPChunkedStreamBuf::writeToDevice(char const*, long) @ 0x23b8a95a in /home/illusion/ClickHouse/build/programs/clickhouse
12. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/include/Poco/BufferedStreamBuf.h:140: Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::flushBuffer() @ 0x23b8ba4d in /home/illusion/ClickHouse/build/programs/clickhouse
13. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/include/Poco/BufferedStreamBuf.h:110: Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::sync() @ 0x23b8b6b2 in /home/illusion/ClickHouse/build/programs/clickhouse
14. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/HTTPChunkedStream.cpp:54: Poco::Net::HTTPChunkedStreamBuf::close() @ 0x23b8a110 in /home/illusion/ClickHouse/build/programs/clickhouse
15. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/HTTPChunkedStream.cpp:166: Poco::Net::HTTPChunkedIOS::~HTTPChunkedIOS() @ 0x23b8ab1a in /home/illusion/ClickHouse/build/programs/clickhouse
16. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/HTTPChunkedStream.cpp:236: Poco::Net::HTTPChunkedOutputStream::~HTTPChunkedOutputStream() @ 0x23b8b2e1 in /home/illusion/ClickHouse/build/programs/clickhouse
17. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/HTTPChunkedStream.cpp:235: Poco::Net::HTTPChunkedOutputStream::~HTTPChunkedOutputStream() @ 0x23b8b323 in /home/illusion/ClickHouse/build/programs/clickhouse
18. /home/illusion/ClickHouse/build/../contrib/libcxx/include/memory:892: std::__1::allocator<Poco::Net::HTTPChunkedOutputStream>::destroy(Poco::Net::HTTPChunkedOutputStream*) @ 0x1f76aff9 in /home/illusion/ClickHouse/build/programs/clickhouse
19. /home/illusion/ClickHouse/build/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<Poco::Net::HTTPChunkedOutputStream> >::__destroy<Poco::Net::HTTPChunkedOutputStream>(std::__1::integral_constant<bool, true>, std::__1::allocator<Poco::Net::HTTPChunkedOutputStream>&, Poco::Net::HTTPChunkedOutputStream*) @ 0x1f76afbd in /home/illusion/ClickHouse/build/programs/clickhouse
20. /home/illusion/ClickHouse/build/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<Poco::Net::HTTPChunkedOutputStream> >::destroy<Poco::Net::HTTPChunkedOutputStream>(std::__1::allocator<Poco::Net::HTTPChunkedOutputStream>&, Poco::Net::HTTPChunkedOutputStream*) @ 0x1f76af7d in /home/illusion/ClickHouse/build/programs/clickhouse
21. /home/illusion/ClickHouse/build/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<Poco::Net::HTTPChunkedOutputStream, std::__1::allocator<Poco::Net::HTTPChunkedOutputStream> >::__on_zero_shared() @ 0x1f76adce in /home/illusion/ClickHouse/build/programs/clickhouse
22. /home/illusion/ClickHouse/build/../contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x1326db31 in /home/illusion/ClickHouse/build/programs/clickhouse
23. /home/illusion/ClickHouse/build/../contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x1326dad9 in /home/illusion/ClickHouse/build/programs/clickhouse
24. /home/illusion/ClickHouse/build/../contrib/libcxx/include/memory:3213: std::__1::shared_ptr<std::__1::basic_ostream<char, std::__1::char_traits<char> > >::~shared_ptr() @ 0x1f6e1dec in /home/illusion/ClickHouse/build/programs/clickhouse
25. /home/illusion/ClickHouse/build/../src/Server/HTTP/HTTPServerResponse.h:16: DB::HTTPServerResponse::~HTTPServerResponse() @ 0x1f7654fe in /home/illusion/ClickHouse/build/programs/clickhouse
26. /home/illusion/ClickHouse/build/../src/Server/HTTP/HTTPServerConnection.cpp:68: DB::HTTPServerConnection::run() @ 0x1f76502f in /home/illusion/ClickHouse/build/programs/clickhouse
27. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x23bc5a19 in /home/illusion/ClickHouse/build/programs/clickhouse
28. /home/illusion/ClickHouse/build/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x23bc6283 in /home/illusion/ClickHouse/build/programs/clickhouse
29. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x23d15e94 in /home/illusion/ClickHouse/build/programs/clickhouse
30. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x23d1297a in /home/illusion/ClickHouse/build/programs/clickhouse
31. /home/illusion/ClickHouse/build/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x23d11722 in /home/illusion/ClickHouse/build/programs/clickhouse
 (version 21.11.1.1)
```

**Additional context**
`curl 'http://localhost:8123' -v -X aaa` works correctly (returns 501 Not Implemented)

### PR DESCRIPTION
**Pull request by FArthur-cmd**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Correct behaviour with unknown methods for http connection. Solves #29050.

Detailed description / Documentation draft:
Add check for unknown methods.

### CODE REVIEW

**Comment by FArthur-cmd** [comment]
Problem: if method not mentioned, it will fail either. Some tests were not ready for this

**Comment by FArthur-cmd** [comment]
File test_infile.gz was added by mistake (as I remember, tests create files by themselves). So, I delete it.

File: src/Server/HTTP/HTTPServerConnection.cpp [hunk 1]
```diff
@@ -29,6 +30,14 @@ void HTTPServerConnection::run()
             {
                 HTTPServerResponse response(session);
                 HTTPServerRequest request(context, response, session);
+                /// Check method (only supported methods will be processed)
```
Comment (tavplubix) [inline src/Server/HTTP/HTTPServerConnection.cpp:33]: I don't think that we should handle it here. The issue is that default dynamic query handler [is created](https://github.com/ClickHouse/ClickHouse/blob/290a6d273eafcd2b7d7fad8624e7f2d7982a03bf/src/Server/HTTPHandlerFactory.cpp#L182-L184) with incorrect [filter](https://github.com/ClickHouse/ClickHouse/blob/414f470c79eb22b0ca47b82f11625cf80b0231aa/src/Server/HTTPHandlerFactory.h#L106-L114), so we choose this handler for custom http methods and do not fallback to a code that handles unknown/not implemented requests.

**Review by tavplubix — APPROVED** [review]
