### PR TITLE
Handle `rotate_log_storage_interval = 0` gracefully

### LINKED ISSUE #83975: Don't set `rotate_log_storage_interval` to 0
### Describe the bug

Yes, yes, you know it.

### How to reproduce

```xml
<keeper_server>
    ....
    <coordination_settings>
        <rotate_log_storage_interval>0</rotate_log_storage_interval>
    </coordination_settings>
</keeper_server>
```
Start and logical error happens.

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'record.header.index - getStartIndex() <= current_file_description->expectedEntriesCountInLog()'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0.  src/Common/StackTrace.cpp:389: StackTrace::StackTrace() @ 0x0000000013deba24
1.  src/Common/Exception.cpp:55: DB::abortOnFailedAssertion(String const&) @ 0x0000000013d54095
2.  src/Coordination/Changelog.cpp:248: DB::ChangelogWriter::appendRecord(DB::ChangelogRecord&&) @ 0x000000001e374c91
3.  src/Coordination/Changelog.cpp:2191: DB::Changelog::writeThread() @ 0x000000001e3689e3
4.  src/Coordination/Changelog.cpp:1760: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::Changelog::Changelog(std::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::shared_ptr<DB::KeeperContext>)::$_2>(DB::Changelog::Changelog(std::shared_ptr<Poco::Logger>, DB::LogFileSettings, DB::FlushSettings, std::shared_ptr<DB::KeeperContext>)::$_2&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001e371b6b
5.  contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000013e8b186
6.  contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000013e91760
7. start_thread @ 0x00000000000a27f1
8. __clone3 @ 0x0000000000133c9c
```

### PR DESCRIPTION
**Pull request by george-larionov**
Resolves: #83975

Changed the rotate_log_storage_interval parameter type to NonZeroUInt64 in order to enforce a >0 value, since 0 does not make sense for this parameter.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed issue where Keeper setting `rotate_log_storage_interval = 0` would cause ClickHouse to crash. (issue #83975)

### CODE REVIEW

File: src/Coordination/KeeperStateManager.cpp [hunk 1]
```diff
@@ -321,6 +323,11 @@ KeeperStateManager::KeeperStateManager(
     , keeper_context(keeper_context_)
     , logger(getLogger("KeeperStateManager"))
 {
+    if (keeper_context_->getCoordinationSettings()[CoordinationSetting::rotate_log_storage_interval] <= 0)
+    {
+        LOG_FATAL(logger, "Keeper parameter rotate_log_storage_interval must be greater than 0.");
+        std::terminate();
+    }
```
Comment (george-larionov) [inline src/Coordination/KeeperStateManager.cpp]: Instead of terminating, I could catch this case and reset the parameter to the default.

File: src/Coordination/KeeperStateManager.cpp [hunk 2]
```diff
@@ -291,6 +292,7 @@ KeeperStateManager::KeeperStateManager(int server_id_, const std::string & host,
     configuration_wrapper.cluster_config->get_servers().push_back(peer_config);
 }
 
+// Why don't we check for overflow here in the coordination settings the same way we do in KeeperServer?
```
Comment (george-larionov) [inline src/Coordination/KeeperStateManager.cpp]: See https://github.com/ClickHouse/ClickHouse/blob/73e73226799f4044530c326721e4c881501c4caa/src/Coordination/KeeperServer.cpp#L207

File: src/Coordination/KeeperStateManager.cpp [hunk 3]
```diff
@@ -321,6 +323,11 @@ KeeperStateManager::KeeperStateManager(
     , keeper_context(keeper_context_)
     , logger(getLogger("KeeperStateManager"))
 {
+    if (keeper_context_->getCoordinationSettings()[CoordinationSetting::rotate_log_storage_interval] <= 0)
```
Comment (nikitamikhaylov) [inline src/Coordination/KeeperStateManager.cpp]: Just change the type of the `rotate_log_storage_interval` in `CoordinationSettings.cpp` to NonZeroUInt64.

**Review by nikitamikhaylov — DISMISSED** [review]

File: src/Coordination/KeeperStateManager.cpp (hunk 3 above)
Comment (PedroTadim) [reply src/Coordination/KeeperStateManager.cpp]: Just do this.

File: src/Coordination/KeeperStateManager.cpp (hunk 2 above)
Comment (antonio2368) [reply src/Coordination/KeeperStateManager.cpp]: Because we don't assign it to `int32_t`.
CoordinationSettings is our code, in KeeperServer we use `getValueOrMaxInt32AndLogWarning` when assigning to NuRaft params which are mostly `int32_t`.
Here we assign `rotate_log_storage_interval` to our internal settings which also has `uint64_t`.

File: src/Coordination/KeeperStateManager.cpp (hunk 3 above)
Comment (antonio2368) [reply src/Coordination/KeeperStateManager.cpp]: Yes, do this.

Comment (rschu1ze) [reply src/Coordination/KeeperStateManager.cpp]: Yes, that's the way, please.

Comment (george-larionov) [reply src/Coordination/KeeperStateManager.cpp]: Done. I didn't know that was an option :).

File: src/Coordination/CoordinationSettings.cpp [hunk 4]
```diff
@@ -37,7 +37,7 @@ namespace ErrorCodes
     DECLARE(Milliseconds, startup_timeout, 180000, "How much time we will wait until RAFT to start.", 0) \
     DECLARE(Milliseconds, sleep_before_leader_change_ms, 8000, "How much time we will wait before removing leader (so as leader could commit accepted but non-committed commands and they won't be lost -- leader removal is not synchronized with committing)", 0) \
     DECLARE(LogsLevel, raft_logs_level, LogsLevel::information, "Log internal RAFT logs into main server log level. Valid values: 'trace', 'debug', 'information', 'warning', 'error', 'fatal', 'none'", 0) \
-    DECLARE(UInt64, rotate_log_storage_interval, 100000, "How many records will be stored in one log storage file", 0) \
+    DECLARE(NonZeroUInt64, rotate_log_storage_interval, 100000, "How many records will be stored in one log storage file", 0) \
```
Comment (rschu1ze) [inline src/Coordination/CoordinationSettings.cpp:40]: @george-larionov Could you please also grep for this

```cpp
extern const CoordinationSettingsUInt64 rotate_log_storage_interval;
```

and change to

```cpp
extern const CoordinationSettingsNonZeroUInt64 rotate_log_storage_interval;
```

File: src/Coordination/KeeperStateManager.cpp (hunk 2 above)
Comment (george-larionov) [reply src/Coordination/KeeperStateManager.cpp]: Got it, thanks! I didn't notice that detail

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@george-larionov Now let's only adjust the PR message and you are good to go :)

**Comment by nikitamikhaylov** [comment]
We need to write a test.

**Comment by rschu1ze** [comment]
Stateless tests (amd_binary, ParallelReplicas, s3 storage, parallel)
- `Expected JOIN table expression to be table, table function, query or union node` https://github.com/ClickHouse/ClickHouse/issues/81144
