### PR TITLE
Check max_execution_time in the pipeline and pulling executors

### LINKED ISSUE #26554: JOIN + GROUP BY doesn't respect timeouts or KILL requests
**Describe the bug**

Reduced query:

```sql
SELECT * FROM
(
    SELECT a.name as n
    FROM
    (
        SELECT 'aaaa' as name, number FROM system.numbers LIMIT 2000000
    ) AS a,
    (
        SELECT 'aaaa' as name, number FROM system.numbers LIMIT 2000000
    ) as b
    GROUP BY n
)
LIMIT 20
FORMAT JSON
```

If you run this query it is not possible to KILL it or limit its timeout, only to cancel it via Ctrl+C in the client.

```
set max_execution_time = 1;

${QUERY}
```

Doesn't work, the process continues after 1 second.

```
kill query where query_id = '03721910-9db1-4bf0-91e2-b565f373b30b';

KILL QUERY WHERE query_id = '03721910-9db1-4bf0-91e2-b565f373b30b' ASYNC

Query id: 23fb949b-ff87-4382-bbb6-98f0b60b3eaa

┌─kill_status─┬─query_id─────────────────────────────┬─user────┬─query──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ waiting     │ 03721910-9db1-4bf0-91e2-b565f373b30b │ default │ SELECT * FROM
(
    SELECT a.name as n
    FROM
    (
        SELECT 'aaaa' as name, number FROM system.numbers LIMIT 2000000
    ) AS a,
    (
        SELECT 'aaaa' as name, number FROM system.numbers LIMIT 2000000
    ) as b
    GROUP BY n
)
LIMIT 20
FORMAT JSON │
└─────────────┴──────────────────────────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
```

Doesn't stop either.

If you request a SYNC kill it doesn't stop either (I stopped the sync KILL request after ~40 seconds):

```
kill query where query_id = '03721910-9db1-4bf0-91e2-b565f373b30b' sync;

KILL QUERY WHERE query_id = '03721910-9db1-4bf0-91e2-b565f373b30b' SYNC

Query id: 61e87749-02bd-4833-a4e9-8e9311036adc

Cancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 40.252 sec.

```

The only thing that does work is to cancel the request from the client. In this case, since I was using clickhouse-client, Ctrl+C stopped the process almost immediately:

```
Query id: 03721910-9db1-4bf0-91e2-b565f373b30b

Cancelling query.
Query was cancelled.

0 rows in set. Elapsed: 58.908 sec. Processed 2.10 million rows, 16.77 MB (35.58 thousand rows/s., 284.67 KB/s.)

Received exception from server (version 21.9.1):
Code: 394. DB::Exception: Received from localhost:9000. DB::Exception: Query was cancelled. (QUERY_WAS_CANCELLED)
```

**Does it reproduce on recent release?**

Yes, tested in master and 21.6.5.37.

**Expected behavior**

Since Ctrl+C works, I would expect KILL to also stop the query. Ideally `max_execution_time` should work in a similar way too.

**Additional context**

I'm planning on looking into it myself, but any pointers about why it doesn't currently work or how should it behave are appreciated.

### LINKED ISSUE #31657: Flaky 00613_shard_distributed_max_execution_time
From https://github.com/ClickHouse/ClickHouse/pull/31636 CI: https://clickhouse-test-reports.s3.yandex.net/31636/de3fe0e9299effaa2cffec31f0487e327c59103e/functional_stateless_tests_(debug).html#fail1

But also from master ([only 1 failure in the last 60 days there](https://play-ci.clickhouse.com/play?user=play#d2l0aCA3MCBhcyB0ZXN0X25hbWVfbGltaXQKU0VMRUNUCiAgaWRlbnRpdHkoY291bnQoKikgYXMgZmFpbHMpIGFzICJGYWlscyIsCiAgaWRlbnRpdHkoY291bnRJZihjaGVja19zdGFydF90aW1lID4gbm93KCkgLSBpbnRlcnZhbCA3IGRheSkgYXMgcmVjZW50KSBhcyAiUmVjZW50IiwKICBtYXgoY2hlY2tfc3RhcnRfdGltZSkgYXMgIkxhc3QiLAogIGFyZ01heChjaGVja19uYW1lLCBjaGVja19zdGFydF90aW1lKSAiQ2hlY2sgTmFtZSIsCiAgaWYobGVuZ3RoKHRlc3RfbmFtZSkgPCB0ZXN0X25hbWVfbGltaXQsIHRlc3RfbmFtZSwgc3Vic3RyKHRlc3RfbmFtZSwgMSwgdGVzdF9uYW1lX2xpbWl0KSB8fCAnLi4uJykgIlRlc3QgTmFtZSIsCiAgJzxhIGhyZWY9IicgfHwgYXJnTWF4KHJlcG9ydF91cmwsIGNoZWNrX3N0YXJ0X3RpbWUpIHx8ICciPicgfHwgYXJnTWF4KHRlc3Rfc3RhdHVzLCBjaGVja19zdGFydF90aW1lKXx8ICc8L2E+JyAiTGluayB0byBSZXBvcnQiCkZST00gYGdoLWRhdGFgLmNoZWNrcwpXSEVSRQogICAgY2hlY2tfc3RhcnRfdGltZSBiZXR3ZWVuIG5vdygpIC0gaW50ZXJ2YWwgNjAgZGF5IGFuZCBub3coKQogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCB0ZXN0X3N0YXR1cyBub3QgaW4gKCdPSycsICdTS0lQUEVEJywgJycpCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCBjaGVja19uYW1lIE5PVCBMSUtFICclU1FMYW5jZXIlJwogICAgYW5kIGNoZWNrX25hbWUgbm90IGxpa2UgJ1lhbmRleCUnCiAgICBhbmQgY2hlY2tfbmFtZSBub3QgbGlrZSAnVGVzdGZsb3clJwogICAgQU5EICJUZXN0IE5hbWUiID0gJzAwNjEzX3NoYXJkX2Rpc3RyaWJ1dGVkX21heF9leGVjdXRpb25fdGltZScKLS0gSXQgaXMgaW1wb3J0YW50IG5vdCB0byBncm91cCBhbGwgdGVzdHMgd2l0aCBlbXB0eSB0ZXN0X25hbWUgdG9nZXRoZXIsCi0tIHN1Y2ggYXMgQVNUIEZ1enplciBhbmQgUGVyZm9ybWFuY2UuCmdyb3VwIGJ5IGlmKHRlc3RfbmFtZSAhPSAnJywgdGVzdF9uYW1lLCBjaGVja19uYW1lKSBhcyB0ZXN0X25hbWUKb3JkZXIgYnkgcmVjZW50IGRlc2MsIGZhaWxzIGRlc2MK)): https://clickhouse-test-reports.s3.yandex.net/0/b58f8197899cc54bb089c0e2593a3e304cd2234e/functional_stateless_tests_(debug).html

Sample error:
```
2021-10-26 11:53:36 --- /usr/share/clickhouse-test/queries/0_stateless/00613_shard_distributed_max_execution_time.reference	2021-10-26 10:25:48.000000000 -0400
2021-10-26 11:53:36 +++ /tmp/clickhouse-test/0_stateless/00613_shard_distributed_max_execution_time.stdout	2021-10-26 11:53:36.532950517 -0400
2021-10-26 11:53:36 @@ -1,10 +0,0 @@
2021-10-26 11:53:36 -0
2021-10-26 11:53:36 -1
2021-10-26 11:53:36 -2
2021-10-26 11:53:36 -3
2021-10-26 11:53:36 -4
2021-10-26 11:53:36 -5
2021-10-26 11:53:36 -6
2021-10-26 11:53:36 -7
2021-10-26 11:53:36 -8
2021-10-26 11:53:36 -9
2021-10-26 11:53:36 
2021-10-26 11:53:36 
2021-10-26 11:53:36 Database: test_27tunu
```

The test:
```
SET max_execution_time = 1, timeout_overflow_mode = 'break';
SELECT DISTINCT * FROM remote('127.0.0.{2,3}', system.numbers) WHERE number < 10;
```

I think that in an extreme situation (slow machine, slow build, slow universe) both servers might take more than 1 second to send a reply with the first batch of numbers so when the query is cancelled due to a timeout it doesn't have any input.

### PR DESCRIPTION
**Pull request by Algunenano**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve the `max_execution_time` checks. Fixed some cases when timeout checks do not happen and query could run too long.

Detailed description / Documentation draft:
* Adds checks in the pipelines (PipelineExecutor, PullingAsyncPipelineExecutor, PullingPipelineExecutor) to better respect the max_execution_time setting.
* If `timeout_overflow_mode` is set to `throw` (default) the `PipelineExecutor` is the most likely to cancel the query mentioned in #26554.
* If `timeout_overflow_mode` is set to `break` both pulling executors will stop pulling data and finish the query with whatever data was already output.
* It also removes `num_queries_increment` from `QueryStatus` since it wasn't used.

The checks inside of `PipelineExecutor` didn't seem excesive so I don't expect it to affect performance, but let's see what the tests say. Iis a better way or place to control the timeouts? cc @KochetovNicolai 

Closes https://github.com/ClickHouse/ClickHouse/issues/26554 : the KILL part was implemented in https://github.com/ClickHouse/ClickHouse/pull/26675 for 21.9+ and this implements the timeout checks.

Closes https://github.com/ClickHouse/ClickHouse/issues/31657

### CODE REVIEW

**Comment by Algunenano** [comment]
Looking at the failures:
* 02010_lc_native -> Flaky. Reported at https://github.com/ClickHouse/ClickHouse/issues/31653
* 01059_storage_file_compression -> Flaky. https://github.com/ClickHouse/ClickHouse/pull/31265 seems to be working on that
* QueryStatus destructor crash: This has to be my fault
* 00613_shard_distributed_max_execution_time: Likely my fault too
* Performance tests: Changes look related to this change (at least the one with many function calls)
* 00623_replicated_truncate_table_zookeeper_long: Not sure. It might be related to the changes, but it's not waiting for replicas on `TRUNCATE` so I'm not surprised it might fail. It's rare but the failure [does appear in master too ](https://play-ci.clickhouse.com/play?user=play#d2l0aCA3MCBhcyB0ZXN0X25hbWVfbGltaXQKU0VMRUNUCiAgaWRlbnRpdHkoY291bnQoKikgYXMgZmFpbHMpIGFzICJGYWlscyIsCiAgaWRlbnRpdHkoY291bnRJZihjaGVja19zdGFydF90aW1lID4gbm93KCkgLSBpbnRlcnZhbCA3IGRheSkgYXMgcmVjZW50KSBhcyAiUmVjZW50IiwKICBtYXgoY2hlY2tfc3RhcnRfdGltZSkgYXMgIkxhc3QiLAogIGFyZ01heChjaGVja19uYW1lLCBjaGVja19zdGFydF90aW1lKSAiQ2hlY2sgTmFtZSIsCiAgaWYobGVuZ3RoKHRlc3RfbmFtZSkgPCB0ZXN0X25hbWVfbGltaXQsIHRlc3RfbmFtZSwgc3Vic3RyKHRlc3RfbmFtZSwgMSwgdGVzdF9uYW1lX2xpbWl0KSB8fCAnLi4uJykgIlRlc3QgTmFtZSIsCiAgJzxhIGhyZWY9IicgfHwgYXJnTWF4KHJlcG9ydF91cmwsIGNoZWNrX3N0YXJ0X3RpbWUpIHx8ICciPicgfHwgYXJnTWF4KHRlc3Rfc3RhdHVzLCBjaGVja19zdGFydF90aW1lKXx8ICc8L2E+JyAiTGluayB0byBSZXBvcnQiCkZST00gYGdoLWRhdGFgLmNoZWNrcwpXSEVSRQogICAgY2hlY2tfc3RhcnRfdGltZSBiZXR3ZWVuIG5vdygpIC0gaW50ZXJ2YWwgNjAgZGF5IGFuZCBub3coKQogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCB0ZXN0X3N0YXR1cyBub3QgaW4gKCdPSycsICdTS0lQUEVEJywgJycpCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCBjaGVja19uYW1lIE5PVCBMSUtFICclU1FMYW5jZXIlJwogICAgYW5kIGNoZWNrX25hbWUgbm90IGxpa2UgJ1lhbmRleCUnCiAgICBhbmQgY2hlY2tfbmFtZSBub3QgbGlrZSAnVGVzdGZsb3clJwogICAgQU5EICJUZXN0IE5hbWUiID0gJzAwNjIzX3JlcGxpY2F0ZWRfdHJ1bmNhdGVfdGFibGVfem9va2VlcGVyX2xvbmcnCi0tIEl0IGlzIGltcG9ydGFudCBub3QgdG8gZ3JvdXAgYWxsIHRlc3RzIHdpdGggZW1wdHkgdGVzdF9uYW1lIHRvZ2V0aGVyLAotLSBzdWNoIGFzIEFTVCBGdXp6ZXIgYW5kIFBlcmZvcm1hbmNlLgpncm91cCBieSBpZih0ZXN0X25hbWUgIT0gJycsIHRlc3RfbmFtZSwgY2hlY2tfbmFtZSkgYXMgdGVzdF9uYW1lCm9yZGVyIGJ5IHJlY2VudCBkZXNjLCBmYWlscyBkZXNjCg==), that is, the test is flaky

I'm investigating the true failures

**Comment by Algunenano** [comment]
Current failures:
* `02023_storage_filelog`: Flaky (https://github.com/ClickHouse/ClickHouse/pull/30977#issuecomment-970043597)
* Clang tidy: Is drunk. Doesn't make sense to me.
* Performance: I've seen the `reinterpret_as` tests failing in other places but not the other things.

I'll review this tomorrow plus any other thing that appears. Comments are welcome at any time.

File: src/Processors/Executors/PipelineExecutor.cpp [hunk 1]
```diff
@@ -46,6 +44,16 @@ PipelineExecutor::PipelineExecutor(Processors & processors, QueryStatus * elem)
 
         throw;
     }
+    if (process_list_element)
+    {
+        auto settings = process_list_element->context.lock()->getSettings();
```
Comment (azat) [inline src/Processors/Executors/PipelineExecutor.cpp:49]:
```suggestion
        auto settings = process_list_element->getContext()->getSettings();
```

And maybe clang tidy will be fixed by this?

**Comment by Algunenano** [comment]
02008_materialize_column failures because it's broken in master (currently reverted and being reapplied in https://github.com/ClickHouse/ClickHouse/pull/31693)

File: src/Processors/Executors/PullingPipelineExecutor.cpp [hunk 2]
```diff
@@ -44,6 +44,9 @@ bool PullingPipelineExecutor::pull(Chunk & chunk)
     if (!executor)
         executor = std::make_shared<PipelineExecutor>(pipeline.processors, pipeline.process_list_element);
 
+    if (!executor->checkTimeLimit())
```
Comment (KochetovNicolai) [inline src/Processors/Executors/PullingPipelineExecutor.cpp:47]: Note: if we throw exception here, executor is not stopped (until the moment of ~PullingPipelineExecutor)

File: src/Processors/Executors/PipelineExecutor.cpp [hunk 3]
```diff
@@ -46,6 +44,16 @@ PipelineExecutor::PipelineExecutor(Processors & processors, QueryStatus * elem)
...
+        limits.max_execution_time = settings.max_execution_time;
+        overflow_mode = settings.timeout_overflow_mode;
```
Comment (KochetovNicolai) [inline src/Processors/Executors/PipelineExecutor.cpp]: I think it may be more reasonable to add timeout check logic into `process_list_element`.

File: src/Processors/Executors/PullingPipelineExecutor.cpp (hunk 2 above)
Comment (Algunenano) [reply src/Processors/Executors/PullingPipelineExecutor.cpp:47]: I understand that's not an issue, right? If nobody catches the exception the executor destructor will be called, if somebody does then it will need to handle it and eventually the executor will be cancelled.

File: src/Processors/Executors/PipelineExecutor.cpp (hunk 3 above)
Comment (Algunenano) [reply src/Processors/Executors/PipelineExecutor.cpp]: Makes sense to me. I'll add a `checkTimeLimit()` to `process_list_element` and use it from the PipeLineExecutor

**Comment by Algunenano** [comment]
Ey @KochetovNicolai does this need any changes or improvements? I want to build on top of this to be able to cancel scalar subqueries (https://github.com/ClickHouse/ClickHouse/issues/1576) but I'd rather keep things separate as otherwise I end up with large PRs that are hard to review.

File: src/Processors/Executors/PullingPipelineExecutor.cpp (hunk 2 above)
Comment (KochetovNicolai) [reply src/Processors/Executors/PullingPipelineExecutor.cpp:47]: It is still not very cool. E.g. executor itself may continue working (e.g. in case of bug)., and we may wait for a long time in destructor.

File: src/Processors/Executors/PipelineExecutor.cpp [hunk 4]
```diff
@@ -124,10 +128,24 @@ bool PipelineExecutor::executeStep(std::atomic_bool * yield_flag)
...
 
+bool PipelineExecutor::checkTimeLimit()
+{
+    if (process_list_element)
+    {
+        bool continuing = process_list_element->checkTimeLimit();
+        // We call cancel here so that all processors are notified and tasks waken up
+        // so that the "break" is faster and doesn't wait for long events
+        if (!continuing)
+            cancel();
```
Comment (KochetovNicolai) [inline src/Processors/Executors/PipelineExecutor.cpp:139]: well, I don't like we don't call cancel in case of exception from `process_list_element->checkTimeLimit()`.

What can we do:
* add softer check to `process_list_element`, something like `bool isTimeLimitExceeded()` which newer throws
* `PipelineExecutor::checkTimeLimit` uses this `isTimeLimitExceeded` version and just cancel. So, it's like a soft check.
* In other places like `PipelineExecutor::finalizeExecution` we call regular `process_list_element->checkTimeLimit()` and throw exception if needed.

**Comment by KochetovNicolai** [comment]
Sorry for not commenting for so long

**Comment by KochetovNicolai** [comment]
We need just to check time limit for every iteration of executeImpl. But avoid calling `clock_gettime` very often.
Maybe add timer_fd or something. But not in this pr.

File: src/Processors/Executors/PipelineExecutor.cpp (hunk 4 above)
Comment (Algunenano) [reply src/Processors/Executors/PipelineExecutor.cpp:139]: What do you think of having something like:

```c++
bool PipelineExecutor::checkTimeLimitSoft()
{
    try
    {
        return checkTimeLimit();
    }
    catch (...)
    {
        cancel();
        return false;
    }
}
```

Then calling `checkTimeLimitSoft` inside the `PullingPipelineExecutor` and `PullingAsyncPipelineExecutor` and in the `executeStepImpl` loop, and `checkTimeLimit` and the start and end of the execution. I think that fits what you were saying right?

Comment (KochetovNicolai) [reply src/Processors/Executors/PipelineExecutor.cpp:139]: Yes, the idea is the same.
But let's try to avoid `try/catch(...)` with ignoring exception if possible :)

**Review by KochetovNicolai — APPROVED** [review]
