### PR TITLE
Fix KeeperMap concurrent cleanup during table creation

### LINKED ISSUE #73088: `There is a race condition between creation and removal of metadata. It's a bug` in `StorageKeeperMap`
https://s3.amazonaws.com/clickhouse-test-reports/72237/42a27b8fcdd6ab67bde7763b89a58e730d74803c/stress_test__debug_.html

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix KeeperMap concurrent cleanup during table creation.

KeeperMap table creation would sometimes produce a LOGICAL_ERROR when multiple tables try to cleanup same nodes.
It happened because of ABA problem on ephemeral lock node (I used `version` on it which is reset on every recreate)
I added a persistent node which helps with determining if it's safe to delete manually the ephemeral node during retry.

Close https://github.com/ClickHouse/ClickHouse/issues/73088

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, BuzzHouse, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 41fe0ebc1787440b395dd6d76cc50e5f5d6f6bd3 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74568/41fe0ebc1787440b395dd6d76cc50e5f5d6f6bd3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/74568/41fe0ebc1787440b395dd6d76cc50e5f5d6f6bd3/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Storages/StorageKeeperMap.cpp [hunk 1]
```diff
@@ -790,6 +782,7 @@ void StorageKeeperMap::drop()
     ops.emplace_back(zkutil::makeRemoveRequest(zk_tables_path, -1));
     ops.emplace_back(zkutil::makeCreateRequest(zk_dropped_path, "", zkutil::CreateMode::Persistent));
     ops.emplace_back(zkutil::makeCreateRequest(zk_dropped_lock_path, "", zkutil::CreateMode::Ephemeral));
+    ops.emplace_back(zkutil::makeSetRequest(zk_dropped_lock_version_path, toString(getStorageID().uuid), -1));
```
Comment (kssenii) [inline src/Storages/StorageKeeperMap.cpp:785]: maybe `toString(getStorageID().uuid)` -> `toString(storage_id.hasUUID() ? storage_id.uuid : storage_id.getFullTableName())` ?

**Review by kssenii — APPROVED** [review]

File: src/Storages/StorageKeeperMap.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Storages/StorageKeeperMap.cpp:785]: KeeperMap cannot be used without UUID.
But what I can reuse is `table_unique_id` which I set in storage constructor

**Comment by antonio2368** [comment]
`03272_json_to_json_cast_2` - https://github.com/ClickHouse/ClickHouse/issues/74624
`02998_native_parquet_reader` - fixed in https://github.com/ClickHouse/ClickHouse/pull/74534
`02884_create_view_with_sql_security_option` - https://github.com/ClickHouse/ClickHouse/issues/74549

**Comment by clickgapai** [comment]
Hi @antonio2368 @kssenii — while reviewing this PR I found the following:

- **Bug (P1):** KeeperMap CREATE TABLE fails to clean up pre-25.1 leftover nodes missing drop_lock_version ZK path — https://github.com/ClickHouse/ClickHouse/issues/101581

Happy to discuss — close anything that's wrong or already addressed.
