### PR TITLE
Fix stream partitioning in parallel window functions

### LINKED ISSUE #58714: Wrong result in window function starting from 23.11
**Describe what's wrong**

I have following table:
```sql
CREATE TABLE empsalary 
(
    `depname` LowCardinality(String),
    `empno` UInt64,
    `salary` Int32,
    `enroll_date` Date
)
ENGINE = MergeTree
ORDER BY enroll_date;


insert into empsalary values ('develop',11,5200,2007-08-15), ('sales',3,4800,2007-08-01), ('sales',1,5000,2006-10-01), ('sales',4,4800,2007-08-08), ('personnel',2,3900,2006-12-23), ('develop',10,5200,2007-08-01), ('personnel',5,3500,2007-12-10), ('develop',7,4200,2008-01-01), ('develop',8,6000,2006-10-01), ('develop',9,4500,2008-01-01);
```
And I perform following query:
```sql
SELECT * FROM
          (SELECT depname,
                  sum(salary) OVER (PARTITION BY depname order by empno) AS depsalary,
                  min(salary) OVER (PARTITION BY depname, empno order by enroll_date) AS depminsalary
           FROM empsalary)
        WHERE depname = 'sales'
        ORDER BY depname, depsalary
```

I get following expected result:
```
sales	5000	5000
sales	9800	4800
sales	14600	4800
```

If I execute the same query on a distributed table I get wrong result:
```
│ sales   │      4800 │         4800 │
│ sales   │      5000 │         5000 │
│ sales   │      9800 │         4800 │
```

https://github.com/alsugiliazova/clickhouse-setup - **configuration file**

How to reproduce:
```sql
CREATE TABLE empsalary_source ON CLUSTER sharded_cluster
(
    `depname` LowCardinality(String),
    `empno` UInt64,
    `salary` Int32,
    `enroll_date` Date
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/empsalary_source', '{replica}')
ORDER BY enroll_date;


CREATE TABLE empsalary AS empsalary_source
ENGINE = Distributed(sharded_cluster, default, empsalary_source, empno % toUInt8(getMacro('shard')));


insert into empsalary values ('develop',11,5200,2007-08-15), ('sales',3,4800,2007-08-01), ('sales',1,5000,2006-10-01), ('sales',4,4800,2007-08-08), ('personnel',2,3900,2006-12-23), ('develop',10,5200,2007-08-01), ('personnel',5,3500,2007-12-10), ('develop',7,4200,2008-01-01), ('develop',8,6000,2006-10-01), ('develop',9,4500,2008-01-01);


SELECT *
FROM
(
    SELECT
        depname,
        sum(salary) OVER (PARTITION BY depname ORDER BY empno ASC) AS depsalary,
        min(salary) OVER (PARTITION BY depname, empno ORDER BY enroll_date ASC) AS depminsalary
    FROM empsalary
)
WHERE depname = 'sales'
ORDER BY
    depname ASC,
    depsalary ASC
```

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix data stream partitioning for window functions when there are different window descriptions with similar prefixes but different partitioning. Fixes #58714.

### CODE REVIEW

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -2985,7 +2985,15 @@ void InterpreterSelectQuery::executeWindow(QueryPlan & query_plan)
         // has suitable sorting. Also don't create sort steps when there are no
         // columns to sort by, because the sort nodes are confused by this. It
         // happens in case of `over ()`.
-        if (!window.full_sort_description.empty() && (i == 0 || !sortIsPrefix(window, *windows_sorted[i - 1])))
+        // Even if full_sort_description of both windows match, we in case of different
```
Comment (qoega) [inline src/Interpreters/InterpreterSelectQuery.cpp:2988]:
```suggestion
        // Even if full_sort_description of both windows match, in case of different
```

**Review by qoega — APPROVED** [review]
