### PR TITLE
Analyzer: Fix unused projection columns removal optimization

### LINKED ISSUE #66465: selecting columns explectInvalid results returned when using explicit columns names instead of * in SELECT query with NULL rows
version used 
```sql
SELECT version(); -- 24.5.3.5
```

Use case : 
Trying to replicate the **EXCEPT ALL** logic supported by some other DBs like Postgres
Removing intersecting rows (without deleting more rows than that exists in the other table)
```sql
-- THE RESULT CTE RETURNS 1 ROW WITH ALL COLUMN VALUES NULL. WHICH IS SUPPOSED TO BE THE EXPECTED BEHAVIOUR
WITH T1 AS (SELECT 1 A, 1 B UNION ALL SELECT 1 A, 1 B), 
T2 AS (SELECT 1 A, 1 B),
T1_WITH_ROWNUM AS (SELECT A, B, ROW_NUMBER() OVER (PARTITION BY A, B ORDER BY A, B) RNK FROM T1),
T2_WITH_ROWNUM AS (SELECT A, B, ROW_NUMBER() OVER (PARTITION BY A, B ORDER BY A, B) RNK FROM T2),
RESULT AS (SELECT * FROM T1_WITH_ROWNUM EXCEPT SELECT * FROM T2_WITH_ROWNUM)
SELECT * FROM RESULT; -- RETURNS 1 RESULT

  A   B   RNK  
 --- --- ----- 
  1   1   2    
```
```sql
-- HOWEVER UPON EXPLICITLY USING COLUMN NAMES RATHER THAN *,  NO RESULTS IN THE OUTPUT
WITH T1 AS (SELECT 1 A, 1 B UNION ALL SELECT 1 A, 1 B), 
T2 AS (SELECT 1 A, 1 B),
T1_WITH_ROWNUM AS (SELECT A, B, ROW_NUMBER() OVER (PARTITION BY A, B ORDER BY A, B) RNK FROM T1),
T2_WITH_ROWNUM AS (SELECT A, B, ROW_NUMBER() OVER (PARTITION BY A, B ORDER BY A, B) RNK FROM T2),
RESULT AS (SELECT * FROM T1_WITH_ROWNUM EXCEPT SELECT * FROM T2_WITH_ROWNUM)
SELECT A,B FROM RESULT; -- RETURNS NO RESULT
-- RETURNS NO RESULT

-- EXPECTED RESULTED TO BE 
  A   B  
 --- --- 
  1   1  

```

### LINKED ISSUE #73930: Analyzer: EXCEPT clause ignores unused projections in subqueries.
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

> study

**Describe what's wrong**

> count() return 0 when the result has some rows when `except` is used.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).
[https://fiddle.clickhouse.com/9f186eb5-b8a3-460d-9bbb-7424275bc16f](https://fiddle.clickhouse.com/9f186eb5-b8a3-460d-9bbb-7424275bc16f)
**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)
yes, in ClickHouse local version 24.12.1.1417 (official build)
**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use   24.12.1.1417
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result
`select count(a)from(select 1 a,2 b union all select 1,1 except select 1,2);`
**Expected behavior**

> count() return 1.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Do not remove unused projection columns in subqueries in the presence of `EXCEPT` or `INTERSECT` to preserve the correct query result. Fixes #73930. Fixes #66465. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, BuzzHouse, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit e365bd91d88e1160840abbf0529e11d542c73c29 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74577/e365bd91d88e1160840abbf0529e11d542c73c29/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/74577/e365bd91d88e1160840abbf0529e11d542c73c29/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Passes/RemoveUnusedProjectionColumnsPass.cpp [hunk 1]
```diff
@@ -154,6 +154,28 @@ void RemoveUnusedProjectionColumnsPass::run(QueryTreeNodePtr & query_tree_node,
                 if (query_node->isDistinct())
                     continue;
             }
+            else
+            {
+                auto * union_node = query_or_union_node->as<UnionNode>();
+                chassert(union_node != nullptr);
+
+                /// We can't remove unused projections in the case of EXCEPT and INTERSECT
+                /// because it can lead to incorrect query results. Example:
```
Comment (nickitat) [inline src/Analyzer/Passes/RemoveUnusedProjectionColumnsPass.cpp:163]: Could you pls also clarify what and where goes wrong in this case? It's hard to guess how smth might lead to a wrong result when it is "unused".

**Review by nickitat — APPROVED** [review]
