### PR TITLE
Fix overflow in parsing/formatting debug check

### LINKED ISSUE #91974: Logical error: 'Inconsistent AST formatting: the query: (STID: 1941-1bfa)
_Important: This issue was automatically created and is used by CI. Do not modify the issue title. Do not remove issue labels._

CI report: [AST fuzzer (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91943&sha=2e200cf063f347aab1aa4b32c467e56e681d7911&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ0luY29uc2lzdGVudCBBU1QgZm9ybWF0dGluZzogdGhlIHF1ZXJ5OicKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0FTVCBmdXp6ZXIgKGFtZF9kZWJ1ZyknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwKSBPUiBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDApCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
Error:
Logical error: 'Inconsistent AST formatting: the query:
SELECT DISTINCT x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, *, x, x, x, x, x, x, x, x, x, x, x, x, toUInt64(1) NOT IN (1234567890, 2345678901, 3456789012, 4567890123, 5678901234, 6789012345, 78901...
cannot parse query back from SELECT DISTINCT x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, *, x, x, x, x, x, x, x, x, x, x, x, x, toUInt64(1) NOT IN (1234567890, 2345678901, 3456789012, 4567890123, ...
---

Failed query:
SELECT DISTINCT x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, *, x, x, x, x, x, x, x, x, x, x, x, x, toUInt64(1) NOT IN (1234567890, 2345678901, 3456789012, 4567890123, 5678901234, 6789012345, 78901...
---

Reproduce commands (auto-generated; may require manual adjustment):
CREATE TABLE d__fuzz_36 (`a` Array(LowCardinality(Time)), `b` Array(LowCardinality(Nullable(Float64)))) ENGINE = Distributed(test_shard_localhost, currentDatabase(), t)
CREATE TABLE d__fuzz_36 (`a` Array(LowCardinality(Time)), `b` Array(LowCardinality(Nullable(Float64)))) ENGINE = Distributed(test_shard_localhost, currentDatabase(), t)
CREATE TABLE d__fuzz_36 (`a` Nullable(Decimal(38, 28)), `b` Decimal(76, 71)) ENGINE = Distributed(test_cluster_two_shards_localhost, currentDatabase(), t)
CREATE TABLE d__fuzz_36 (`a` Nullable(Decimal(38, 28)), `b` Decimal(76, 71)) ENGINE = Distributed(test_cluster_two_shards_localhost, currentDatabase(), t)
SELECT DISTINCT x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, *, x, x, x, x, x, x, x, x, x, x, x, x, toUInt64(1) NOT IN (1234567890, 2345678901, 3456789012, 4567890123, 5678901234, 6789012345, 78901...
DROP TABLE IF EXISTS d__fuzz_36
DROP TABLE IF EXISTS round
DROP TABLE IF EXISTS remote('127.0.0.2', system, one)
---

Stack trace:
__GI___pthread_kill @ 0x00000000000969fd
raise @ 0x0000000000042476
__ieee754_lgamma_r @ 0x00000000000287f3
src/Common/Exception.cpp:54: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x0000000015c69d3c
src/Common/Exception.cpp:87: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x0000000015c6b18...
src/Common/Exception.cpp:138: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015c6b4a5
src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d60c494
src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d60c013
src/Common/Exception.h:141: DB::Exception::Exception<String&, std::basic_string_view<char, std::char_traits<char>>&>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<s...
src/Interpreters/executeQuery.cpp:1245: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std...
src/Interpreters/executeQuery.cpp:1967: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c23d154
src/Server/TCPHandler.cpp:777: DB::TCPHandler::runImpl() @ 0x000000001fa3df09
src/Server/TCPHandler.cpp:2873: DB::TCPHandler::run() @ 0x000000001fa591e4
base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000025f0650e
base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000025f06b7b
base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000025ea707f
base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000025ea470f
start_thread @ 0x0000000000094ac3
__GI___clone3 @ 0x00000000001268c0
```

### PR DESCRIPTION
**Pull request by george-larionov**
Fixes #91974.
Caused by an overflow in max_query_size when it is adjusted during the debug check.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: src/Interpreters/executeQuery.cpp [hunk 1]
```diff
@@ -1201,7 +1201,14 @@ static BlockIO executeQueryImpl(
                 String formatted1 = format_ast(out_ast);
 
                 /// The query can become more verbose after formatting, so:
-                size_t new_max_query_size = max_query_size > 0 ? (1000 + 2 * max_query_size) : 0;
+                size_t size_t_max = -1;
+                size_t new_max_query_size = 0;
+                if (max_query_size == 0)
+                    new_max_query_size = 0;
```
Comment (alexey-milovidov) [inline src/Interpreters/executeQuery.cpp:1207]: clang-tidy may argue about a redundant store

**Review by alexey-milovidov — APPROVED** [review]
