### PR TITLE
Fix crash in case of iceberg table with mixed ORC/Parquet files

### LINKED ISSUE #88126: Iceberg SEGV with Parquet reader on ORC file?
### Describe the bug

This is confusing. The new Parquet reader is being called on an ORC file.  I think there may be two bugs here?

### How to reproduce

Run:
```sql
CREATE TABLE t0 (c0 String) ENGINE = IcebergLocal(local, format = 'ORC', path = '/var/lib/clickhouse/user_files/lakehouse/t0/');
INSERT INTO TABLE FUNCTION icebergLocal(local, structure = 'c0 String', path = '/var/lib/clickhouse/user_files/lakehouse/t0/') (c0) SELECT c0 FROM generateRandom('c0 String', 8819847341420794659, 1987, 10) LIMIT 1;
INSERT INTO TABLE t0 (c0) SELECT 'back';
SELECT 1 FROM icebergLocal(local, format = 'ORC', structure = 'c0 String', path = '/var/lib/clickhouse/user_files/lakehouse/t0/') tx SETTINGS input_format_parquet_use_native_reader_v3 = 1;
```

### Error message and/or stacktrace

Stack trace:
```
2025.10.06 10:56:08.996586 [ 1883015 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.10.06 10:56:08.996606 [ 1883015 ] {} <Fatal> BaseDaemon: (version 25.10.1.1712 (official build), build id: 7A97684BFAA19E3F5E7EB400C30FEE3EF8D863F6, git hash: 1d861df9948d425d353411dea0ee98971547e975, architecture: x86_64) (from thread 1883731) Received signal 11
2025.10.06 10:56:08.996610 [ 1883015 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2025.10.06 10:56:08.996617 [ 1883015 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2025.10.06 10:56:08.996650 [ 1883015 ] {} <Fatal> BaseDaemon: Stack trace: 0x000060ae4124f6a3 0x000060ae41239e25 0x000060ae40cbc51f 0x000060ae40cbc659 0x000060ae40b10956 0x000060ae40ae5365 0x000060ae40ae5042 0x000060ae40b02450 0x000060ae40af41d8 0x000060ae40af3d8e 0x000060ae40b0b4b4 0x000060ae3b2cc3f7 0x000060ae40ae5365 0x000060ae40ae5042 0x000060ae40b02450 0x000060ae40af41d8 0x000060ae40af47e9 0x000060ae40af5883 0x000060ae35ed0f53 0x000060ae35ed7626 0x000060ae35ece3e6 0x000060ae35ed4e00 0x000076404aea27f1 0x000076404af33b5c
2025.10.06 10:56:08.996664 [ 1883015 ] {} <Fatal> BaseDaemon: ########################################
2025.10.06 10:56:08.996739 [ 1883015 ] {} <Fatal> BaseDaemon: (version 25.10.1.1712 (official build), build id: 7A97684BFAA19E3F5E7EB400C30FEE3EF8D863F6, git hash: 1d861df9948d425d353411dea0ee98971547e975) (from thread 1883731) (query_id: c68c36ee-e32a-4355-910b-010eea5896ec) (query: SELECT 1 FROM icebergLocal(local, format = 'ORC', structure = 'c0 String', path = '/var/lib/clickhouse/user_files/lakehouse/t0/') tx SETTINGS input_format_parquet_use_native_reader_v3 = 1;) Received signal Segmentation fault (11)
2025.10.06 10:56:08.996791 [ 1883015 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2025.10.06 10:56:08.996830 [ 1883015 ] {} <Fatal> BaseDaemon: Stack trace: 0x000060ae4124f6a3 0x000060ae41239e25 0x000060ae40cbc51f 0x000060ae40cbc659 0x000060ae40b10956 0x000060ae40ae5365 0x000060ae40ae5042 0x000060ae40b02450 0x000060ae40af41d8 0x000060ae40af3d8e 0x000060ae40b0b4b4 0x000060ae3b2cc3f7 0x000060ae40ae5365 0x000060ae40ae5042 0x000060ae40b02450 0x000060ae40af41d8 0x000060ae40af47e9 0x000060ae40af5883 0x000060ae35ed0f53 0x000060ae35ed7626 0x000060ae35ece3e6 0x000060ae35ed4e00 0x000076404aea27f1 0x000076404af33b5c
2025.10.06 10:56:09.039529 [ 1883015 ] {} <Fatal> BaseDaemon: 3.0. inlined from contrib/llvm-project/libcxx/include/vector:1418: std::vector<std::pair<unsigned long, std::shared_ptr<DB::KeyCondition>>, std::allocator<std::pair<unsigned long, std::shared_ptr<DB::KeyCondition>>>>::begin[abi:se190107]() const
2025.10.06 10:56:09.039570 [ 1883015 ] {} <Fatal> BaseDaemon: 3. src/Processors/Formats/Impl/Parquet/Reader.cpp:367: DB::Parquet::Reader::prefilterAndInitRowGroups() @ 0x000000001fee26a3
2025.10.06 10:56:09.061744 [ 1883015 ] {} <Fatal> BaseDaemon: 4. src/Processors/Formats/Impl/Parquet/ReadManager.cpp:48: DB::Parquet::ReadManager::init(std::shared_ptr<DB::FormatParserSharedResources>) @ 0x000000001fecce25
2025.10.06 10:56:09.084357 [ 1883015 ] {} <Fatal> BaseDaemon: 5. src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp:84: DB::ParquetV3BlockInputFormat::initializeIfNeeded() @ 0x000000001f94f51f
2025.10.06 10:56:09.109532 [ 1883015 ] {} <Fatal> BaseDaemon: 6. src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp:107: DB::ParquetV3BlockInputFormat::read() @ 0x000000001f94f659
2025.10.06 10:56:09.117171 [ 1883015 ] {} <Fatal> BaseDaemon: 7. src/Processors/Formats/IInputFormat.cpp:29: DB::IInputFormat::generate() @ 0x000000001f7a3956
2025.10.06 10:56:09.126308 [ 1883015 ] {} <Fatal> BaseDaemon: 8. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000001f778365
2025.10.06 10:56:09.134404 [ 1883015 ] {} <Fatal> BaseDaemon: 9. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001f778042
2025.10.06 10:56:09.139072 [ 1883015 ] {} <Fatal> BaseDaemon: 10.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.10.06 10:56:09.139094 [ 1883015 ] {} <Fatal> BaseDaemon: 10. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001f795450
2025.10.06 10:56:09.156228 [ 1883015 ] {} <Fatal> BaseDaemon: 11. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f7871d8
2025.10.06 10:56:09.172701 [ 1883015 ] {} <Fatal> BaseDaemon: 12. src/Processors/Executors/PipelineExecutor.cpp:179: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x000000001f786d8e
2025.10.06 10:56:09.181048 [ 1883015 ] {} <Fatal> BaseDaemon: 13. src/Processors/Executors/PullingPipelineExecutor.cpp:59: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x000000001f79e4b4
2025.10.06 10:56:09.231079 [ 1883015 ] {} <Fatal> BaseDaemon: 14. src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:286: DB::StorageObjectStorageSource::generate() @ 0x0000000019f5f3f7
2025.10.06 10:56:09.239869 [ 1883015 ] {} <Fatal> BaseDaemon: 15. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000001f778365
2025.10.06 10:56:09.248200 [ 1883015 ] {} <Fatal> BaseDaemon: 16. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001f778042
2025.10.06 10:56:09.252710 [ 1883015 ] {} <Fatal> BaseDaemon: 17.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.10.06 10:56:09.252855 [ 1883015 ] {} <Fatal> BaseDaemon: 17. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001f795450
2025.10.06 10:56:09.269421 [ 1883015 ] {} <Fatal> BaseDaemon: 18. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f7871d8
2025.10.06 10:56:09.285775 [ 1883015 ] {} <Fatal> BaseDaemon: 19. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001f7877e9
2025.10.06 10:56:09.304749 [ 1883015 ] {} <Fatal> BaseDaemon: 20.0. inlined from src/Processors/Executors/PipelineExecutor.cpp:565: operator()
2025.10.06 10:56:09.304788 [ 1883015 ] {} <Fatal> BaseDaemon: 20.1. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:se190107]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.10.06 10:56:09.304817 [ 1883015 ] {} <Fatal> BaseDaemon: 20.2. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.10.06 10:56:09.304835 [ 1883015 ] {} <Fatal> BaseDaemon: 20.3. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.10.06 10:56:09.304845 [ 1883015 ] {} <Fatal> BaseDaemon: 20. contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x000000001f788883
2025.10.06 10:56:09.316045 [ 1883015 ] {} <Fatal> BaseDaemon: 21.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.10.06 10:56:09.316069 [ 1883015 ] {} <Fatal> BaseDaemon: 21.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.10.06 10:56:09.316083 [ 1883015 ] {} <Fatal> BaseDaemon: 21. src/Common/ThreadPool.cpp:802: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000014b63f53
2025.10.06 10:56:09.328420 [ 1883015 ] {} <Fatal> BaseDaemon: 22.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
2025.10.06 10:56:09.328459 [ 1883015 ] {} <Fatal> BaseDaemon: 22.1. inlined from contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
2025.10.06 10:56:09.328474 [ 1883015 ] {} <Fatal> BaseDaemon: 22.2. inlined from contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
2025.10.06 10:56:09.328513 [ 1883015 ] {} <Fatal> BaseDaemon: 22. src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000014b6a626
2025.10.06 10:56:09.338651 [ 1883015 ] {} <Fatal> BaseDaemon: 23.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.10.06 10:56:09.338685 [ 1883015 ] {} <Fatal> BaseDaemon: 23.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.10.06 10:56:09.338703 [ 1883015 ] {} <Fatal> BaseDaemon: 23. src/Common/ThreadPool.cpp:812: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000014b613e6
2025.10.06 10:56:09.358714 [ 1883015 ] {} <Fatal> BaseDaemon: 24.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.10.06 10:56:09.358752 [ 1883015 ] {} <Fatal> BaseDaemon: 24.1. inlined from contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.10.06 10:56:09.358805 [ 1883015 ] {} <Fatal> BaseDaemon: 24. contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000014b67e00
2025.10.06 10:56:09.358865 [ 1883015 ] {} <Fatal> BaseDaemon: 25. start_thread @ 0x00000000000a27f1
2025.10.06 10:56:09.358908 [ 1883015 ] {} <Fatal> BaseDaemon: 26. __GI___clone3 @ 0x0000000000133b5c
2025.10.06 10:56:09.576706 [ 1883015 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: F59803038BB4E21D4BDF0059FBCFC1DC)
2025.10.06 10:56:09.588192 [ 1883015 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.10.06 10:56:09.588389 [ 1883015 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, enable_lightweight_update = true, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, parallel_replicas_for_non_replicated_merge_tree = true, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_live_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_qbit_type = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_shared_set_join = true, input_format_parquet_use_native_reader_v3 = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix very rare crash when Iceberg table contains files of mixed format (ORC and Parquet). Fixes #88126.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

Before we had a single initialization of KeyCondition for the whole read. Now we switch to per-file initialization. I don't expect any performance degradation, because opening/reading file is several orders of magnitude slower than analyzing something in WHERE condition.

---

> [!NOTE]
> **Medium Risk**
> Touches filter initialization and Parquet page-level predicate pushdown, which can affect row/column skipping and is exercised across multiple input formats; changes are localized but impact correctness/performance of filtering paths.
> 
> **Overview**
> Fixes a crash when reading Iceberg tables containing mixed ORC and Parquet files by making `FormatFilterInfo` build `key_condition`/**PREWHERE additional columns** with `std::call_once` semantics via `initKeyConditionOnce()`.
> 
> Updates ORC and Parquet input formats to use this new API and removes `FormatFilterInfo::opaque` and the Parquet V3-specific `FilterInfoExt`; Parquet page-level filter pushdown now derives per-column conditions directly from `key_condition` and keeps them alive in `Parquet::Reader`.
> 
> Adds a stateless regression test (`04033_iceberg_orc_parquet_v3_crash`) to ensure the mixed-format Iceberg read no longer segfaults.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 13e3d247ee9a2c17decbf2b80c445c749346578b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.585`

### CODE REVIEW

File: src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp [hunk 1]
```diff
@@ -62,11 +62,6 @@ void ParquetV3BlockInputFormat::initializeIfNeeded()
         format_filter_info->initOnce([&]
             {
                 format_filter_info->initKeyCondition(getPort().getHeader());
-
```
Comment (kssenii) [inline src/Processors/Formats/Impl/ParquetV3BlockInputFormat.cpp:65]: As I see `format_filter_info->initOnce` after this change always does only `format_filter_info->initKeyCondition`, then may be remove `initOnce` and make it `initKeyConditionOnce` so that later noone tries to extend this callback in a similar way and create the same bug again?

**Review by kssenii — APPROVED** [review]
