### PR TITLE
Fix converting types for UNION queries (may produce LOGICAL_ERROR)

### LINKED ISSUE #37569: Null pointer dereference in Aggregator
```
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 22.5.1.2079 (official build), build id: EBBF91C52186EE12) (from thread 46419) (query_id: 51268d18-4093-4de4-b3fa-18f3e7ff3ea9) (query: SELECT avgWeighted(x, y) FROM (SELECT NULL, 255 AS x, 1 AS y UNION ALL SELECT y, NULL AS x, 1 AS y);) Received signal Segmentation fault (11)
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
<Fatal> BaseDaemon: Stack trace: 0xd99865d 0xd998c25 0x155c4d5f 0x155c43f5 0x16ebb800 0x16eb91f6 0x16d18ee8 0x16d0cbfe 0x16d0e4c4 0xb53fc47 0xb54367d 0x7fb28832e609 0x7fb288253163
<Fatal> BaseDaemon: 2. DB::AggregateFunctionNullVariadic<true, true, true>::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const @ 0xd99865d in /usr/bin/clickhouse
<Fatal> BaseDaemon: 3. DB::IAggregateFunctionHelper<DB::AggregateFunctionNullVariadic<true, true, true> >::addBatchSinglePlace(unsigned long, unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0xd998c25 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 4. void DB::Aggregator::executeWithoutKeyImpl<false>(char*&, unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*) const @ 0x155c4d5f in /usr/bin/clickhouse
<Fatal> BaseDaemon: 5. DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) const @ 0x155c43f5 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 6. DB::AggregatingTransform::consume(DB::Chunk) @ 0x16ebb800 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7. DB::AggregatingTransform::work() @ 0x16eb91f6 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8. DB::ExecutionThreadContext::executeTask() @ 0x16d18ee8 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16d0cbfe in /usr/bin/clickhouse
<Fatal> BaseDaemon: 10. ? @ 0x16d0e4c4 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb53fc47 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 12. ? @ 0xb54367d in /usr/bin/clickhouse
<Fatal> BaseDaemon: (version 22.5.1.2079 (official build), build id: EBBF91C52186EE12) (from thread 43826) (query_id: 51268d18-4093-4de4-b3fa-18f3e7ff3ea9) (query: SELECT avgWeighted(x, y) FROM (SELECT NULL, 255 AS x, 1 AS y UNION ALL SELECT y, NULL AS x, 1 AS y);) Received signal Segmentation fault (11)
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
<Fatal> BaseDaemon: 13. ? @ 0x7fb28832e609 in ?
<Fatal> BaseDaemon: Stack trace: 0xd99865d 0xd998c25 0x155c4d5f 0x155c43f5 0x16ebb800 0x16eb91f6 0x16d18ee8 0x16d0cbfe 0x16d0e4c4 0xb53fc47 0xb54367d 0x7fb28832e609 0x7fb288253163
<Fatal> BaseDaemon: 14. clone @ 0x7fb288253163 in ?
<Fatal> BaseDaemon: 2. DB::AggregateFunctionNullVariadic<true, true, true>::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const @ 0xd99865d in /usr/bin/clickhouse
<Fatal> BaseDaemon: 3. DB::IAggregateFunctionHelper<DB::AggregateFunctionNullVariadic<true, true, true> >::addBatchSinglePlace(unsigned long, unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0xd998c25 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 4. void DB::Aggregator::executeWithoutKeyImpl<false>(char*&, unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*) const @ 0x155c4d5f in /usr/bin/clickhouse
<Fatal> BaseDaemon: 5. DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> >, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > > >&, bool&) const @ 0x155c43f5 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 6. DB::AggregatingTransform::consume(DB::Chunk) @ 0x16ebb800 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7. DB::AggregatingTransform::work() @ 0x16eb91f6 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8. DB::ExecutionThreadContext::executeTask() @ 0x16d18ee8 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16d0cbfe in /usr/bin/clickhouse
<Fatal> BaseDaemon: 10. ? @ 0x16d0e4c4 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb53fc47 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 12. ? @ 0xb54367d in /usr/bin/clickhouse
<Fatal> BaseDaemon: 13. ? @ 0x7fb28832e609 in ?
<Fatal> BaseDaemon: 14. clone @ 0x7fb288253163 in ?
<Fatal> BaseDaemon: Calculated checksum of the binary: 725445B106D580F2BC17459FE7679BDC. There is no information about the reference checksum.
<Fatal> BaseDaemon: Calculated checksum of the binary: 725445B106D580F2BC17459FE7679BDC. There is no information about the reference checksum.
<Fatal> Application: Child process was terminated by signal 11.
```

https://s3.amazonaws.com/clickhouse-test-reports/34775/a813f5996e95e424193265bb090ef7a402497d6e/stress_test__undefined__actions_.html
https://s3.amazonaws.com/clickhouse-test-reports/34775/a813f5996e95e424193265bb090ef7a402497d6e/stress_test__debug__actions_.html

Might be related to #35111 cc @azat

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix converting types for UNION queries (may produce LOGICAL_ERROR)

CI founds [1]:

    2022.02.20 15:14:23.969247 [ 492 ] {} <Fatal> BaseDaemon: (version 22.3.1.1, build id: 6082C357CFA6FF99) (from thread 472) (query_id: a5187ff9-962a-4e7c-86f6-8d48850a47d6) (query: SELECT 0., round(avgWeighted(x, y)) FROM (SELECT toDate(toDate('214748364.8', '-922337203.6854775808', '-0.1', NULL) - NULL, 10.000100135803223, '-2147483647'), 255 AS x, -2147483647 AS y UNION ALL SELECT y, NULL AS x, 2147483646 AS y)) Received signal Aborted (6)

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/0/26d0e5438c86e52a145aaaf4cb523c399989a878/fuzzer_astfuzzerdebug,actions//report.html

The problem is that subqueries returns different headers:
- first query  -- x, y
- second query -- y, x

Fixes: #37569
Resubmit: #34775
Cc: @novikd

### CODE REVIEW

**Comment by azat** [comment]
>[Fast test (actions) — Some tests restarted, fail: 1, passed: 3456, skipped: 689](https://s3.amazonaws.com/clickhouse-test-reports/37593/87b8a498c94f09f945654a588d3ea537e37e33a9/fast_test__actions_.html)

- #37597

**Comment by azat** [comment]
>[Stress test (address, actions) — Backward compatibility check: OOM killer (or signal 9) in clickhouse-server.log](https://s3.amazonaws.com/clickhouse-test-reports/37593/2613149f6bf4f242bbbf2c3c8539b5176fd77286/stress_test__address__actions_.html)
>[Stress test (thread, actions) — OOM killer (or signal 9) in clickhouse-server.log](https://s3.amazonaws.com/clickhouse-test-reports/37593/2613149f6bf4f242bbbf2c3c8539b5176fd77286/stress_test__thread__actions_.html)

Issues with keeper shutdown

<details>

```
$ pigz -cd clickhouse-server.stress.log.gz | tail 
2022.05.27 16:17:24.882971 [ 637 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2022.05.27 16:17:24.896749 [ 637 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 4.09 MiB.
2022.05.27 16:17:24.907163 [ 637 ] {} <Debug> Application: Shut down storages.
2022.05.27 16:17:24.907233 [ 637 ] {} <Debug> Application: Waiting for current connections to servers for tables to finish.
2022.05.27 16:17:24.934335 [ 637 ] {} <Information> Application: Closed all listening sockets. Waiting for 1 outstanding connections.
2022.05.27 16:17:29.843491 [ 637 ] {} <Information> Application: Closed connections to servers for tables. But 1 remain. Probably some tables of other users cannot finish their connections after context shutdown.
2022.05.27 16:17:29.843632 [ 637 ] {} <Debug> KeeperDispatcher: Shutting down storage dispatcher
2022.05.27 16:17:34.612616 [ 688 ] {} <Test> virtual Coordination::ZooKeeperRequest::~ZooKeeperRequest(): Processing of request xid=2147483647 took 10000 ms
2022.05.27 16:17:54.612109 [ 3176 ] {} <Debug> KeeperTCPHandler: Session #12 expired
2022.05.27 16:19:59.823038 [ 635 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```

```
Thread 26 (Thread 0x7f1c7703f700 (LWP 708)):
#0  0x000000000b074b2a in __tsan::MemoryAccessImpl(__tsan::ThreadState*, unsigned long, int, bool, bool, unsigned long long*, __tsan::Shadow) ()
#1  0x000000000b08630c in __tsan::MemoryAccessRange(__tsan::ThreadState*, unsigned long, unsigned long, unsigned long, bool) ()
#2  0x000000000b01ff03 in memmove ()
#3  0x000000001bbc8996 in std::__1::__move<long, long> (__first=0xb8600000d83304, __last=<optimized out>, __result=0x7f1c021cd000) at ../contrib/libcxx/include/__algorithm/move.h:57
#4  std::__1::move<long*, long*> (__first=0xb8600000d83304, __last=<optimized out>, __result=0x7f1c021cd000) at ../contrib/libcxx/include/__algorithm/move.h:70
#5  std::__1::vector<long, std::__1::allocator<long> >::erase (this=0x7b1400584c48, __position=...) at ../contrib/libcxx/include/vector:1608
#6  DB::KeeperStorage::clearDeadWatches (this=0x7b5800001ad8, this@entry=0x7b5800001800, session_id=session_id@entry=12) at ../src/Coordination/KeeperStorage.cpp:1228
#7  0x000000001bbc5c55 in DB::KeeperStorage::processRequest (this=0x7b5800001800, zk_request=..., session_id=12, time=1, new_last_zxid=..., check_acl=true) at ../src/Coordination/KeeperStorage.cpp:1122
#8  0x000000001bba06a3 in DB::KeeperStateMachine::commit (this=<optimized out>, log_idx=3549, data=...) at ../src/Coordination/KeeperStateMachine.cpp:143
#9  0x000000001bba6193 in nuraft::state_machine::commit_ext (this=0x7b4c00001f98, params=...) at ../contrib/NuRaft/include/libnuraft/state_machine.hxx:75
#10 0x00000000202c5a55 in nuraft::raft_server::commit_app_log (this=this@entry=0x7b6c00002a18, idx_to_commit=idx_to_commit@entry=3549, le=..., need_to_handle_commit_elem=true, initial_commit_exec=false) at ../contrib/NuRaft/src/handle_commit.cxx:311
#11 0x00000000202c4f98 in nuraft::raft_server::commit_in_bg_exec (this=<optimized out>, this@entry=0x7b6c00002a18, timeout_ms=timeout_ms@entry=0, initial_commit_exec=false) at ../contrib/NuRaft/src/handle_commit.cxx:241
#12 0x00000000202c4613 in nuraft::raft_server::commit_in_bg (this=this@entry=0x7b6c00002a18) at ../contrib/NuRaft/src/handle_commit.cxx:149
...
Thread 28 (Thread 0x7f1c7603d700 (LWP 710)):
#0  0x00007f1d22a6d110 in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f1d22a650a3 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x000000000b0337b0 in pthread_mutex_lock ()
#3  0x00000000221884da in std::__1::__libcpp_mutex_lock (__m=0x7b4c00002088) at ../contrib/libcxx/include/__threading_support:303
#4  std::__1::mutex::lock (this=0x7b4c00002088) at ../contrib/libcxx/src/mutex.cpp:33
#5  0x000000001bba4188 in std::__1::lock_guard<std::__1::mutex>::lock_guard (__m=..., this=<optimized out>) at ../contrib/libcxx/include/__mutex_base:91
#6  DB::KeeperStateMachine::getDeadSessions (this=0x7b4c00001f98) at ../src/Coordination/KeeperStateMachine.cpp:360
#7  0x000000001bb79b4b in DB::KeeperServer::getDeadSessions (this=0x7b4400012700) at ../src/Coordination/KeeperServer.cpp:572
#8  0x000000001bb64d1a in DB::KeeperDispatcher::sessionCleanerTask (this=<optimized out>, this@entry=0x7b640001c218) at ../src/Coordination/KeeperDispatcher.cpp:399
...
Thread 1 (Thread 0x7f1d227148c0 (LWP 637)):
#0  0x00007f1d22a69376 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000b0895e0 in __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) ()
#2  0x000000000b017091 in pthread_cond_wait ()
#3  0x0000000020569d98 in Poco::EventImpl::waitImpl (this=0x7b2000008798) at ../contrib/poco/Foundation/src/Event_POSIX.cpp:106
#4  0x000000001bb636cf in Poco::Event::wait (this=0x7b2000008798) at ../contrib/poco/Foundation/include/Poco/Event.h:97
#5  ThreadFromGlobalPool::join (this=<optimized out>) at ../src/Common/ThreadPool.h:217
#6  DB::KeeperDispatcher::shutdown (this=0x7b640001c218) at ../src/Coordination/KeeperDispatcher.cpp:322
#7  0x0000000019ca8bfc in DB::Context::shutdownKeeperDispatcher (this=<optimized out>) at ../src/Interpreters/Context.cpp:2111
#8  0x000000000b0a979b in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_9::operator()() const (this=0x7ffcde44f0a0) at ../programs/server/Server.cpp:1407
```

</details>

Should be fixed by one of the following:
- #37640
- #37641

File: tests/queries/0_stateless/02227_union_match_by_name.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- Tags: no-backward-compatibility-check:22.5.1.2079
```
Comment (novikd) [inline tests/queries/0_stateless/02227_union_match_by_name.sql:1]: I don't get why it's not backward compatible. This patch should fix LOGICAL_ERROR, but in the issue we got null pointer dereference.

Comment (azat) [reply tests/queries/0_stateless/02227_union_match_by_name.sql:1]: Not only logical error. The order of columns was not correct, and in case of aggregator it may get null pointer dereference.

**Comment by novikd** [comment]
Test failures are unrelated.
