### PR TITLE
Fix incorrect memory around max_untracked_memory

### LINKED ISSUE #82036: Memory Tracking Issues
_This is a placeholder issue for such problems, since I was looking into this multiple times, I will add more info later_

There are 3 types of issues:
- when RSS is higher the `MemoryTracking` metric
  - Don't remember anything existing, but I've seen such cases now
- when `MemoryTracking` is higher then RSS
  - Example of previous fixes/problems
    - https://github.com/ClickHouse/ClickHouse/pull/72603
    - https://github.com/ClickHouse/ClickHouse/pull/73081
- non-jemalloc builds (memory usage under sanitizers)
  - Example of previous fixes/problems
    - https://github.com/ClickHouse/ClickHouse/pull/76143
  - Examples of reports that are still exist:
    - https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=81960&sha=6bac7d1bf40b30eed5cc0e01b74253bdb681c913&name_0=PR&name_1=Stateless%20tests%20%28amd_msan%2C%203%2F4%29
  - Todo
    - [ ] Resubmit https://github.com/ClickHouse/ClickHouse/pull/76388 - #82361

For the (2) case we can gather jemalloc profiles from CI - https://github.com/ClickHouse/ClickHouse/issues/82035

And we have both

If you have some detailed reports, please post them here.

### LINKED ISSUE #82627: After upgrading ClickHouse from version 22.4.2.1 to 25.3.4.190, a memory leak issue occurred. The server memory is not being released, eventually leading to termination by the operating system's OOM Killer.
### Company or project name

_No response_

### Describe what's wrong

memory usage

Image

cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

uname -a
Linux 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

/var/log/message:
kernel: Out of memory: Kill process 61699 (ThreadPool) score 981 or sacrifice child
 kernel: Killed process 251242 (clickhouse-serv), UID 997, total-vm:639397272kB, anon-rss:516638256kB, file-rss:300kB, shmem-rss:0kB

clickhouse-server.err.log:
(version 25.3.4.190 (official build))
2025.06.24 17:14:53.115446 [ 242909 ] {1cac2cd2-5a2b-4a7f-8cf6-c7e713749dd9} <Error> executeQuery: Code: 241. DB::Exception: (total) memory limit exceeded: would use 453.17 GiB (attempt to allocate chunk of 0.00 B bytes), current RSS: 451.23 GiB, maximum: 452.79 GiB. OvercommitTracker decision: Memory overcommit has not freed enough memory: While executing AggregatingTransform. (MEMORY_LIMIT_EXCEEDED) (version 25.3.4.190 (official build))

2025.06.24 17:14:53.186171 [ 242909 ] {1cac2cd2-5a2b-4a7f-8cf6-c7e713749dd9} <Error> DynamicQueryHandler: Code: 241. DB::Exception: (total) memory limit exceeded: would use 453.17 GiB (attempt to allocate chunk of 0.00 B bytes), current RSS: 451.23 GiB, maximum: 452.79 GiB. OvercommitTracker decision: Memory overcommit has not freed enough memory: While executing AggregatingTransform. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f4bfbfb
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009f87f8c
2. DB::Exception::Exception<char const*, char const*, String, String, String, String, String, char const*, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<char const*>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<char const*>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, char const*&&, char const*&&, String&&, String&&, String&&, String&&, String&&, char const*&&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000000f52f1d2
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f52d3e2
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f52ccdb
5. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f52ccdb
6. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000f52ccdb
7. DB::Aggregator::checkLimits(unsigned long, bool&) const @ 0x00000000132476d2
8. DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>>>&, bool&) const @ 0x000000001329ab43
9. DB::AggregatingTransform::work() @ 0x0000000014fe5f18
10. DB::ExecutionThreadContext::executeTask() @ 0x0000000014d868b6
11. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d7a3a4
12. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000014d7cadf
13. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000000f5f59db
14. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000f5fc503
15. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000f5f2d0f
16. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f5f9fda
17. start_thread @ 0x0000000000007e65
18. clone @ 0x00000000000fe88d

Job's origin stack trace:
0. void boost::heap::priority_queue<JobWithPriority, boost::heap::stable<true>, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::emplace<std::function<void ()>, Priority&, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>&, DB::OpenTelemetry::TracingContextOnThread const, bool&, (anonymous namespace)::ScopedDecrement>(std::function<void ()>&&, Priority&, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&, (anonymous namespace)::ScopedDecrement&&) @ 0x000000000f5fac17
1. void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool) @ 0x000000000f5f6db8
2. DB::PipelineExecutor::spawnThreadsImpl() @ 0x0000000014d7bb95
3. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d7a2de
4. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000014d7cadf
5. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000000f5f59db
6. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000f5fc503
7. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000f5f2d0f
8. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f5f9fda
9. start_thread @ 0x0000000000007e65
10. clone @ 0x00000000000fe88d

### Does it reproduce on the most recent release?

Yes

### How to reproduce

 (version 25.3.4.190 (official build))

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### LINKED ISSUE #83352: server stalls every couple of hours
### Company or project name

syncmedia

### Question

Latest clickhouse server version installed in debian x64. no queries running against it on weekends.

I am seeing this in clickhouse-error.log. Not sure what's causing this

2025.07.06 06:59:34.486037 [ 469645 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {698b7bb1-6802-45b9-a4fb-54e624a0bfa7::202507_1283571_1283624_3}: Code: 241. DB::Exception: (total) memory limit exceeded: would use 28.15 GiB (attempt to allocate chunk of 4.33 MiB bytes), current RSS: 2.25 GiB, maximum: 27.70 GiB. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000dad8c08
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000911a81c
2. DB::Exception::Exception<char const*, char const*, String, String, String, String, String, char const*, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<char const*>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<char const*>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, char const*&&, char const*&&, String&&, String&&, String&&, String&&, String&&, char const*&&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000000db3850c
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000db37470
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000db36ffc
5. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000db36ffc
6. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000db36ffc
7. CurrentMemoryTracker::allocImpl(long, bool) @ 0x000000000dab341c
8. Allocator<false, false>::alloc(unsigned long, unsigned long) @ 0x000000000dab08b0
9. DB::Memory<Allocator<false, false>>::alloc(unsigned long) @ 0x000000000db85bb4
10. DB::CompressedWriteBuffer::CompressedWriteBuffer(DB::WriteBuffer&, std::shared_ptr<DB::ICompressionCodec>, unsigned long, bool, unsigned long) @ 0x00000000132c818c
11. void std::__function::__policy_invoker<void (DB::ISerialization::SubstreamPath const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::MergeTreeDataPartWriterCompact::addStreams(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IAST> const&)::$_0, void (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x00000000124fc164
12. DB::SerializationLowCardinality::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x0000000010a46d88
13. DB::MergeTreeDataPartWriterCompact::addStreams(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IAST> const&) @ 0x00000000124f7c14
14. DB::MergeTreeDataPartWriterCompact::MergeTreeDataPartWriterCompact(String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, std::shared_ptr<DB::MergeTreeIndexGranularity>) @ 0x00000000124f7514
15. DB::createMergeTreeDataPartCompactWriter(String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::unordered_map<String, unsigned long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, unsigned long>>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, std::shared_ptr<DB::MergeTreeIndexGranularity>) @ 0x00000000124ea4fc
16. DB::createMergeTreeDataPartWriter(DB::MergeTreeDataPartType, String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::unordered_map<String, unsigned long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, unsigned long>>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, std::shared_ptr<DB::MergeTreeIndexGranularity>) @ 0x000000001240bbfc
17. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::shared_ptr<DB::IMergeTreeDataPart> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnPartStatistics>, std::allocator<std::shared_ptr<DB::ColumnPartStatistics>>> const&, std::shared_ptr<DB::ICompressionCodec>, std::shared_ptr<DB::MergeTreeIndexGranularity>, DB::TransactionID, unsigned long, bool, bool, DB::WriteSettings const&) @ 0x000000001264e07c
18. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x00000000123dc498
19. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x00000000123e383c
20. DB::MergeTask::execute() @ 0x00000000123ebc9c
21. DB::MergePlainMergeTreeTask::executeStep() @ 0x00000000127b9818

### PR DESCRIPTION
**Pull request by azat**
### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix incorrect memory around max_untracked_memory

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

Due to one tiny allocation inside `MemoryTracker` for logs, recursive allocation from `CurrentMemoryTracker` -> `MemoryTracker` -> `CurrentMemoryTracker` is possible, which will lead to double accounting of `untracked_memory` (this is happens after #81694, before the problem was also there, but it just ignores the inner allocation).

Thanks to @filimonov for the provided test - horizontal merges for wide tables with wide parts (`system.metric_log`) for a few minute (3-5) will lead to ~3GiB of memory drift.

And the rule of thumb is - any accounting of per-thread `untracked_memory` should be done **before** going into `MemoryTracker`.

_Note, that this is the simplest possible fix for now (that will be easy to backport), I will do some refactoring and cleanup later._

Fixes: #82036
Fixes: #83352
Fixes: #82627

Refs:
- [Possible stacktrace](https://pastila.nl/?0023a66c/8bfc8e9135a6edb5312d3387408b2264#P1XgWmDuHq4xgrQ2C4azyQ==) (_obtained with extra patch that adds some sanity checks that leads to endless recursion_)

### CODE REVIEW

File: src/Common/CurrentMemoryTracker.cpp [hunk 1]
```diff
@@ -68,18 +68,24 @@ AllocationTrace CurrentMemoryTracker::allocImpl(Int64 size, bool throw_if_memory
...
+            try
+            {
+                Int64 current_untracked_memory = current_thread->untracked_memory;
+                current_thread->untracked_memory = 0;
+                auto res = memory_tracker->allocImpl(current_untracked_memory, throw_if_memory_exceeded);
+                return res;
+            }
+            catch (...)
+            {
+                current_thread->untracked_memory = previous_untracked_memory;
```
Comment (al13n321) [inline src/Common/CurrentMemoryTracker.cpp]: Should it be `+=`, in case `allocImpl` adjusted `untracked_memory` (by doing another alloc/free recursively) before throwing?

**Comment by azat** [comment]
>[Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, 1/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83607&sha=36f774761ff2c96fbb13eb23a5a46a8ff8f9cf37&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%201%2F2%29) — The test runner was terminated unexpectedly

- https://github.com/ClickHouse/ClickHouse/issues/82676

>[Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83607&sha=6d2c6e626f42bfdd3b66f73b354f3a77e7eb632e&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%202%2F2%29) — Failed: 1, Passed: 3926, Skipped: 201

- https://github.com/ClickHouse/ClickHouse/issues/54748

File: src/Common/CurrentMemoryTracker.cpp (hunk 1 above)
Comment (azat) [reply src/Common/CurrentMemoryTracker.cpp]: Hm, you are right assignment is wrong, it should be actually `-= size` I think. Fixed.

Comment (al13n321) [reply src/Common/CurrentMemoryTracker.cpp]: Wait, no, the `-= size` subtracts from ~zero now because of the `current_thread->untracked_memory = 0` inside the `try`? I think `+= previous_untracked_memory` would be correct.

(I.e. we tried to report `previous_untracked_memory + size` allocated bytes to MemoryTracker, but it failed and reported 0 allocated bytes instead. The allocation of size `size` will fail. The remaining `previous_untracked_memory` will need to be reported again.)

Comment (azat) [reply src/Common/CurrentMemoryTracker.cpp]: Yep, you are right! Fixed.

**Review by al13n321 — APPROVED** [review]

**Comment by azat** [comment]
>[Stateless tests (amd_asan, distributed plan, 1/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83607&sha=bc664252b35e3600d72481c30278af0e44e1b9d6&name_0=PR&name_1=Stateless%20tests%20%28amd_asan%2C%20distributed%20plan%2C%201%2F2%29) — Failed: 1, Passed: 4026, Skipped: 77

- `01576_alter_low_cardinality_and_select`

**Comment by azat** [comment]
~~I finally found another issue that I have observed from time to time, this is not that general though, when the user set `max_untracked_memory=0` all previous allocations (up to 4MB) may be lost, since we did not flush it properly, fix - https://github.com/ClickHouse/ClickHouse/pull/83607/commits/3fd3c1375ed35b8f5a03cb6557d55eb721bca3be~~

~~TL;DR; I think now, the total memory tracker should be correct.~~

**Comment by filimonov** [comment]
After the change :| 

image
