### PR TITLE
Fix `optimize_inverse_dictionary_lookup` not working with distributed query

### LINKED ISSUE #93259: 25.12 THERE_IS_NO_COLUMN or NOT_FOUND_COLUMN_IN_BLOCK with dictGet in the SELECT section of a distributed query with LIMIT or GROUP BY
### Company or project name

_No response_

### Describe what's wrong

An exception happens when comparing a dictGet expression with a constant in the SELECT section of a distributed query with LIMIT or GROUP BY:
```
SELECT (dictGet(dict, 'f', dummy) = 12)
FROM remote('localhost,localhost',system.one)
limit 1

Received exception from server (version 25.12.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `in(__table3.dummy, __set_16161166867483335112_9280691039349338112)` in source stream, there are only columns: [in(__table3.dummy, __set_13576357846268788558_4996254765006076933)]. (THERE_IS_NO_COLUMN)

SELECT (dictGet(dict, 'f', dummy) = 12)
FROM remote('localhost,localhost',system.one)
group by all

Received exception from server (version 25.12.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `in(__table3.dummy, __set_16161166867483335112_9280691039349338112)` in source stream, there are only columns: [in(__table3.dummy, __set_13576357846268788558_4996254765006076933)]. (THERE_IS_NO_COLUMN)
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

latest: https://fiddle.clickhouse.com/fc7fd163-c062-4669-9c7e-fa2ff4aa80c3
no problem in 25.11: https://fiddle.clickhouse.com/b6e4092a-9a3e-4d51-8078-452170916089
```
CREATE DICTIONARY dict
(
  id Int64,
  f  Int64
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(QUERY 'SELECT 1 id, 2 f'))
LAYOUT(flat())
lifetime(0);

SELECT (dictGet(dict, 'f', dummy) = 12) as no_limit
FROM remote('localhost,localhost',system.one);

   +-no_limit-+
1. |        0 |
2. |        0 |
   +----------+

SELECT (dictGet(dict, 'f', dummy) in (12)) as limit_and_in
FROM remote('localhost,localhost',system.one)
limit 1;

   +-limit_and_in-+
1. |            0 |
   +--------------+

SELECT (dictGet(dict, 'f', dummy) = 12) as limit_and_no_analyzer
FROM remote('localhost,localhost',system.one)
limit 1
settings enable_analyzer=0;

   +-limit_and_no_analyzer-+
1. |                     0 |
   +-----------------------+

SELECT (dictGet(dict, 'f', dummy) = 12) as limit_and_equals
FROM remote('localhost,localhost',system.one)
limit 1

Received exception from server (version 25.12.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `in(__table3.dummy, __set_16161166867483335112_9280691039349338112)` in source stream, there are only columns: [in(__table3.dummy, __set_13576357846268788558_4996254765006076933)]. (THERE_IS_NO_COLUMN)
(query: SELECT (dictGet(dict, 'f', dummy) = 12) as limit_and_equals
FROM remote('localhost,localhost',system.one)
limit 1
)
```

### Expected behavior

_No response_

### Error message and/or stacktrace

```
Received exception from server (version 25.12.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `in(__table3.dummy, __set_16161166867483335112_9280691039349338112)` in source stream, there are only columns: [in(__table3.dummy, __set_13576357846268788558_4996254765006076933)]. (THERE_IS_NO_COLUMN)
(query: SELECT (dictGet(dict, 'f', dummy) = 12) as limit_and_equals
FROM remote('localhost,localhost',system.one)
limit 1
)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nihalzp**
Currently, the following query does not work:

```sql
CREATE DICTIONARY inverse_dict_lookup_remote_shards
(
  id Int64,
  f  Int64
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(QUERY 'SELECT 1 id, 2 f'))
LAYOUT(flat())
LIFETIME(0);

SET optimize_inverse_dictionary_lookup = 1;
SELECT dictGet('inverse_dict_lookup_remote_shards', 'f', dummy) = 12 AS limit_and_equals
FROM remote('localhost,localhost', system.one)
LIMIT 1;
```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `optimize_inverse_dictionary_lookup` not working with distributed query when key is signed integral type. Closes https://github.com/ClickHouse/ClickHouse/issues/93259.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.431`
- Backported to: `25.12.3.21`

### CODE REVIEW

File: src/Analyzer/Passes/InverseDictionaryLookupPass.cpp [hunk 1]
```diff
@@ -251,6 +251,7 @@ class InverseDictionaryLookupVisitor : public InDepthQueryTreeVisitorWithContext
 
         /// SELECT key_col FROM dictionary(dict_name) WHERE attr_name = const_value
         auto subquery_node = std::make_shared<QueryNode>(Context::createCopy(getContext()));
+        subquery_node->setIsSubquery(true);
```
Comment (nihalzp) [inline src/Analyzer/Passes/InverseDictionaryLookupPass.cpp:263]: This is not needed for this particular bug fix. But this is correct to have.

**Review by KochetovNicolai — APPROVED** [review]
