### PR TITLE
Fix some bad error messages

### LINKED ISSUE #49408: flaky test: 00002_log_and_exception_messages_formatting
https://s3.amazonaws.com/clickhouse-test-reports/49382/332ff058c96a32290f7df2442bf6f613d3ba386d/stateless_tests__release_.html

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/49408

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: src/Functions/parseDateTime.cpp [hunk 1]
```diff
@@ -150,7 +150,7 @@ namespace
             if (text == "bc")
                 throw Exception(ErrorCodes::CANNOT_PARSE_DATETIME, "Era BC exceeds the range of DateTime");
             else if (text != "ad")
-                throw Exception(ErrorCodes::CANNOT_PARSE_DATETIME, "Unknown era {}", text);
+                throw Exception(ErrorCodes::CANNOT_PARSE_DATETIME, "Unknown era {} (expected 'ad' or 'bc')", text);
```
Comment (vmarora) [inline src/Functions/parseDateTime.cpp:153]: "expected 'ad' only"? 

bc is not allowed as per the line above.

Comment (tavplubix) [reply src/Functions/parseDateTime.cpp:153]: Well, technically `bc` is expected too :) Yes, it's not supported, but it's a valid value

**Comment by tavplubix** [comment]
Integration tests (release) [4/4] - https://github.com/ClickHouse/ClickHouse/issues/49400
Stateless tests (release, analyzer) - this check is broken in master
Stateless tests flaky check (asan) - it's expected
Stress test (ubsan) - #49102
