### PR TITLE
Fix bugs when using UDF in join on expression with the old analyzer

### LINKED ISSUE #71382: Explain syntax SEGV
**Describe the bug**
A SEGV may happen with `SET optimize_rewrite_array_exists_to_has = 1` and Explain syntax.

**How to reproduce**
It may take a few tries to reproduce. Run:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = Memory();
SET optimize_rewrite_array_exists_to_has = 1;
EXPLAIN SYNTAX SELECT 1 FROM t0 JOIN t0 y ON (SELECT 1) JOIN t0 z ON 1;
```

UBSAN output:
```
contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702:23: runtime error: member call on misaligned address 0x6567617373656d for type 'std::__shared_weak_count', which requires 8 byte alignment
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bugs when using UDF in join on expression with the old analyzer

Fixes https://github.com/ClickHouse/ClickHouse/issues/71382.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 7bb98cbedde76f5fe0b5bb41e2e7beae06abed42 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72179/7bb98cbedde76f5fe0b5bb41e2e7beae06abed42/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/72179/7bb98cbedde76f5fe0b5bb41e2e7beae06abed42/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

File: src/Parsers/ASTColumnDeclaration.cpp [hunk 1]
```diff
@@ -130,12 +130,25 @@ void ASTColumnDeclaration::formatImpl(const FormatSettings & format_settings, Fo
...
+        if (new_member_ptr != member.get())
+        {
+            if (new_member_ptr)
+                member = new_member_ptr->ptr();
+            else
+                member.reset();
+        }
+    };
+
+    visit_child(default_expression);
```
Comment (vdimir) [inline src/Parsers/ASTColumnDeclaration.cpp:146]: Should we visit each child in such a way in all asts or only in `ASTColumnDeclaration` and `ASTTableJoin` ?

**Review by vdimir — APPROVED** [review]

File: src/Parsers/ASTColumnDeclaration.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Parsers/ASTColumnDeclaration.cpp:146]: This is only necessary when the members are shared pointers (vs naked pointers).

I introduced the old code in `ASTColumnDeclaration` in [a previous PR ](https://github.com/ClickHouse/ClickHouse/pull/71541) and AFAICT it did not cause any issues because the pointer was not modified again, but with `ASTTableJoin` it happened, which is why the issue appeared. `ASTViewTargets` already had this code from before. It will all go away once we remove the old analyzer, which is a huge pain

File: tests/queries/0_stateless/03274_udf_in_join.sh [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+$CLICKHOUSE_CLIENT -q "
+  CREATE VIEW v0 AS SELECT 1 AS c0;
+  CREATE FUNCTION ${CLICKHOUSE_DATABASE}_second AS (x, y) -> y;
+  CREATE FUNCTION ${CLICKHOUSE_DATABASE}_equals AS (x, y) -> x = y;
+  -- SET optimize_rewrite_array_exists_to_has = 1;
```
[the remark this answers is not in the document]
Comment (Algunenano) [reply tests/queries/0_stateless/03274_udf_in_join.sh:11]: OTOH, it should be enabled for this test
