### PR TITLE
Proper buffer flush while handling HTTP queries (avoids std::terminate)

### LINKED ISSUE #26829: <Fatal> Application: Child process was terminated by signal 6.
### version 
ClickHouse 21.3.3.14 with revision 54448, build id: 7C39F44C9AD4D3BA36D74775616894F60A552276
Docker version 18.09.9, build 039a7df9ba
### describe
The cluster with 10 nodes is all deployed in Docker, using the official image, and 6 nodes are stopped at the same time.

Log of one of the stop nodes
```shell
2021.07.27 15:53:32.477674 [ 53 ] {} <Fatal> BaseDaemon: (version 21.3.3.14 (official build), build id: 7C39F44C9AD4D3BA36D74775616894F60A552276) (from thread 9367) Terminate called for uncaught exception:
Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 376, Stack trace (when copying this message, always include the lines below):

0. DB::WriteBufferFromOStream::nextImpl() @ 0x87083a0 in /usr/bin/clickhouse
1. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0xf8db390 in /usr/bin/clickhouse
2. DB::WriteBufferFromHTTPServerResponse::finalize() @ 0xf8db982 in /usr/bin/clickhouse
3. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xf8dc016 in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b776 in /usr/bin/clickhouse
5. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
11. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.3.14 (official build))
2021.07.27 15:53:32.478090 [ 22026 ] {} <Fatal> BaseDaemon: ########################################
2021.07.27 15:53:32.478128 [ 22026 ] {} <Fatal> BaseDaemon: (version 21.3.3.14 (official build), build id: 7C39F44C9AD4D3BA36D74775616894F60A552276) (from thread 8964) (query_id: ea7ebad8-157f-44b7-a04c-caf15341d3e6) Receiv
ed signal Aborted (6)
2021.07.27 15:53:32.478141 [ 22026 ] {} <Fatal> BaseDaemon: 
2021.07.27 15:53:32.478165 [ 22026 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f9f915e218b 0x7f9f915c1859 0x87ca798 0x13ac7d43 0x13ac7cec 0x860e06b 0xf8dc17d 0xf84b776 0xf8d419f 0x11f7d83f 0x11f7f251 0x120b5979 0x120b17da 0x7f
9f91797609 0x7f9f916be293
2021.07.27 15:53:32.478206 [ 22026 ] {} <Fatal> BaseDaemon: 1. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:32.478221 [ 22026 ] {} <Fatal> BaseDaemon: 2. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:32.478243 [ 22026 ] {} <Fatal> BaseDaemon: 3. ? @ 0x87ca798 in /usr/bin/clickhouse
2021.07.27 15:53:32.478252 [ 22026 ] {} <Fatal> BaseDaemon: 4. ? @ 0x13ac7d43 in ?
2021.07.27 15:53:32.478269 [ 22026 ] {} <Fatal> BaseDaemon: 5. std::terminate() @ 0x13ac7cec in ?
2021.07.27 15:53:32.478280 [ 22026 ] {} <Fatal> BaseDaemon: 6. ? @ 0x860e06b in /usr/bin/clickhouse
2021.07.27 15:53:32.478299 [ 22026 ] {} <Fatal> BaseDaemon: 7. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xf8dc17d in /usr/bin/clickhouse
2021.07.27 15:53:32.478314 [ 22026 ] {} <Fatal> BaseDaemon: 8. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b776 in /usr/bin/clickhouse
2021.07.27 15:53:32.478333 [ 22026 ] {} <Fatal> BaseDaemon: 9. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
2021.07.27 15:53:32.478347 [ 22026 ] {} <Fatal> BaseDaemon: 10. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
2021.07.27 15:53:32.478358 [ 22026 ] {} <Fatal> BaseDaemon: 11. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
2021.07.27 15:53:32.478371 [ 22026 ] {} <Fatal> BaseDaemon: 12. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
2021.07.27 15:53:32.478383 [ 22026 ] {} <Fatal> BaseDaemon: 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
2021.07.27 15:53:32.478401 [ 22026 ] {} <Fatal> BaseDaemon: 14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.07.27 15:53:32.478415 [ 22026 ] {} <Fatal> BaseDaemon: 15. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:32.479836 [ 22027 ] {} <Fatal> BaseDaemon: ########################################
2021.07.27 15:53:32.479946 [ 22027 ] {} <Fatal> BaseDaemon: (version 21.3.3.14 (official build), build id: 7C39F44C9AD4D3BA36D74775616894F60A552276) (from thread 9367) (query_id: 8b60c4f0-cbb2-4e14-95c2-b40a2d24f4ed) Receiv
ed signal Aborted (6)
2021.07.27 15:53:32.479996 [ 22027 ] {} <Fatal> BaseDaemon: 
2021.07.27 15:53:32.480082 [ 22027 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f9f915e218b 0x7f9f915c1859 0x87ca798 0x13ac7d43 0x13ac7cec 0x860e06b 0xf8dc17d 0xf84b776 0xf8d419f 0x11f7d83f 0x11f7f251 0x120b5979 0x120b17da 0x7f
9f91797609 0x7f9f916be293
2021.07.27 15:53:32.480580 [ 22027 ] {} <Fatal> BaseDaemon: 1. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:32.480632 [ 22027 ] {} <Fatal> BaseDaemon: 2. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:32.480674 [ 22027 ] {} <Fatal> BaseDaemon: 3. ? @ 0x87ca798 in /usr/bin/clickhouse
2021.07.27 15:53:32.480697 [ 22027 ] {} <Fatal> BaseDaemon: 4. ? @ 0x13ac7d43 in ?
2021.07.27 15:53:32.480738 [ 22027 ] {} <Fatal> BaseDaemon: 5. std::terminate() @ 0x13ac7cec in ?
2021.07.27 15:53:32.480761 [ 22027 ] {} <Fatal> BaseDaemon: 6. ? @ 0x860e06b in /usr/bin/clickhouse
2021.07.27 15:53:32.480789 [ 22027 ] {} <Fatal> BaseDaemon: 7. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xf8dc17d in /usr/bin/clickhouse
2021.07.27 15:53:32.480811 [ 22027 ] {} <Fatal> BaseDaemon: 8. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b776 in /usr/bin/clickhouse
2021.07.27 15:53:32.480832 [ 22027 ] {} <Fatal> BaseDaemon: 9. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
2021.07.27 15:53:32.480854 [ 22027 ] {} <Fatal> BaseDaemon: 10. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
2021.07.27 15:53:32.480873 [ 22027 ] {} <Fatal> BaseDaemon: 11. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
2021.07.27 15:53:32.480895 [ 22027 ] {} <Fatal> BaseDaemon: 12. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
2021.07.27 15:53:32.480929 [ 22027 ] {} <Fatal> BaseDaemon: 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
2021.07.27 15:53:32.480955 [ 22027 ] {} <Fatal> BaseDaemon: 14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.07.27 15:53:32.481005 [ 22027 ] {} <Fatal> BaseDaemon: 15. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:32.482841 [ 7895 ] {440b576c-f0f8-41df-985b-a90aca4391ae} <Information> executeQuery: Read 43948554 rows, 12.27 GiB in 8.725333008 sec., 5036891 rows/sec., 1.41 GiB/sec.
2021.07.27 15:53:32.491216 [ 7895 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, e.displayText() = I/O error: Broken pipe, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11f7622d in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x11f7791a in /usr/bin/clickhouse
2. Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x11f7c8a6 in /usr/bin/clickhouse
3. Poco::Net::HTTPSession::write(char const*, long) @ 0x11f4da83 in /usr/bin/clickhouse
4. Poco::Net::HTTPChunkedIOS::~HTTPChunkedIOS() @ 0x11f37980 in /usr/bin/clickhouse
5. Poco::Net::HTTPChunkedOutputStream::~HTTPChunkedOutputStream() @ 0x11f383ee in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0xf8d4309 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
12. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.3.14 (official build))
```

the other
```shell
2021.07.27 15:53:30.781869 [ 51 ] {} <Fatal> BaseDaemon: (version 21.3.3.14 (official build), build id: 7C39F44C9AD4D3BA36D74775616894F60A552276) (from thread 2052) Terminate called for uncaught exception:
Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 664, Stack trace (when copying this message, always include the lines below):

0. DB::WriteBufferFromOStream::nextImpl() @ 0x87083a0 in /usr/bin/clickhouse
1. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0xf8db390 in /usr/bin/clickhouse
2. DB::WriteBufferFromHTTPServerResponse::finalize() @ 0xf8db982 in /usr/bin/clickhouse
3. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xf8dc016 in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b776 in /usr/bin/clickhouse
5. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
11. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.3.14 (official build))
2021.07.27 15:53:30.782495 [ 3491 ] {} <Fatal> BaseDaemon: ########################################
2021.07.27 15:53:30.782624 [ 3491 ] {} <Fatal> BaseDaemon: (version 21.3.3.14 (official build), build id: 7C39F44C9AD4D3BA36D74775616894F60A552276) (from thread 2052) (query_id: 76cceb75-1d87-4841-898d-bcab4a16d510) Receive
d signal Aborted (6)
2021.07.27 15:53:30.782664 [ 3491 ] {} <Fatal> BaseDaemon: 
2021.07.27 15:53:30.782728 [ 3491 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f184fbbc18b 0x7f184fb9b859 0x87ca798 0x13ac7d43 0x13ac7cec 0x860e06b 0xf8dc17d 0xf84b776 0xf8d419f 0x11f7d83f 0x11f7f251 0x120b5979 0x120b17da 0x7f1
84fd71609 0x7f184fc98293
2021.07.27 15:53:30.782843 [ 3491 ] {} <Fatal> BaseDaemon: 1. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:30.782882 [ 3491 ] {} <Fatal> BaseDaemon: 2. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:30.782911 [ 3491 ] {} <Fatal> BaseDaemon: 3. ? @ 0x87ca798 in /usr/bin/clickhouse
2021.07.27 15:53:30.782927 [ 3491 ] {} <Fatal> BaseDaemon: 4. ? @ 0x13ac7d43 in ?
2021.07.27 15:53:30.782952 [ 3491 ] {} <Fatal> BaseDaemon: 5. std::terminate() @ 0x13ac7cec in ?
2021.07.27 15:53:30.782969 [ 3491 ] {} <Fatal> BaseDaemon: 6. ? @ 0x860e06b in /usr/bin/clickhouse
2021.07.27 15:53:30.783001 [ 3491 ] {} <Fatal> BaseDaemon: 7. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xf8dc17d in /usr/bin/clickhouse
2021.07.27 15:53:30.783025 [ 3491 ] {} <Fatal> BaseDaemon: 8. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b776 in /usr/bin/clickhouse
2021.07.27 15:53:30.783063 [ 3491 ] {} <Fatal> BaseDaemon: 9. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
2021.07.27 15:53:30.783084 [ 3491 ] {} <Fatal> BaseDaemon: 10. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
2021.07.27 15:53:30.783102 [ 3491 ] {} <Fatal> BaseDaemon: 11. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
2021.07.27 15:53:30.783123 [ 3491 ] {} <Fatal> BaseDaemon: 12. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
2021.07.27 15:53:30.783141 [ 3491 ] {} <Fatal> BaseDaemon: 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
2021.07.27 15:53:30.783168 [ 3491 ] {} <Fatal> BaseDaemon: 14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.07.27 15:53:30.783187 [ 3491 ] {} <Fatal> BaseDaemon: 15. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.07.27 15:53:30.888286 [ 3491 ] {} <Fatal> BaseDaemon: Checksum of the binary: 11A63B17AD9F07EA53F49019A0B82E36, integrity check passed.
2021.07.27 15:53:30.888415 [ 3491 ] {} <Information> SentryWriter: Not sending crash report
2021.07.27 15:53:30.938542 [ 2061 ] {4402c092-645d-460d-80f1-4c1a8837e88c} <Information> executeQuery: Read 1 rows, 1.00 B in 0.000678913 sec., 1472 rows/sec., 1.44 KiB/sec.
2021.07.27 15:53:30.998064 [ 2020 ] {e493725b-2c00-4ca3-bd23-b91b4905b7cd} <Error> DynamicQueryHandler: Code: 307, e.displayText() = DB::Exception: Chunk size is too large, Stack trace (when copying this message, always inc
lude the lines below):

0. DB::HTTPChunkedReadBuffer::readChunkHeader() @ 0xf8d69fb in /usr/bin/clickhouse
1. DB::HTTPChunkedReadBuffer::nextImpl() @ 0xf8d6d0b in /usr/bin/clickhouse
2. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0xe716f3c in /usr/bin/clickhouse
3. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0xe7d740c in /usr/bin/clickhouse
4. DB::CompressedReadBuffer::nextImpl() @ 0xe7d6f27 in /usr/bin/clickhouse
5. DB::ConcatReadBuffer::nextImpl() @ 0xe9659be in /usr/bin/clickhouse
6. DB::LimitReadBuffer::nextImpl() @ 0x86a730c in /usr/bin/clickhouse
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf12ff7b in /usr/bin/clickhouse
8. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xf8472fa in /usr/bin/clickhouse
9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84b48e in /usr/bin/clickhouse
10. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
16. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.3.14 (official build))
2021.07.27 15:53:30.998398 [ 2020 ] {e493725b-2c00-4ca3-bd23-b91b4905b7cd} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 246, e.displayText() = DB::Exception: Unexpected data instead of HTTP chunk header, Stack trace (when copying this message, always include the lines below):

0. DB::HTTPChunkedReadBuffer::readChunkHeader() @ 0xf8d69a2 in /usr/bin/clickhouse
1. DB::HTTPChunkedReadBuffer::nextImpl() @ 0xf8d6d0b in /usr/bin/clickhouse
2. DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0xf84a842 in /usr/bin/clickhouse
3. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84bbb5 in /usr/bin/clickhouse
4. DB::HTTPServerConnection::run() @ 0xf8d419f in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x11f7d83f in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x11f7f251 in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x120b5979 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b17da in /usr/bin/clickhouse
9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
10. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.3.14 (official build))
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Proper buffer flush while handling HTTP queries (avoids std::terminate and avoids calling finalize() multiple times). Fixes #26829

Detailed description:
This will avoid possible std::terminate, like in [1]:

  [1]: https://github.com/ClickHouse/ClickHouse/pull/24023#issuecomment-842979875

Cc: @amosbird

*NOTE: the first patch just reduce the scope for the trySendExceptionToClient*

### CODE REVIEW

**Comment by azat** [comment]
[`00429_long_http_bufferization` failed](https://clickhouse-test-reports.s3.yandex.net/28604/1f34fd9a9eaff19fde0199f78b45656ab74f0590/functional_stateless_tests_(release).html#fail1) because `finalize()` called multiple times, fixed that in the last patch of this patch series.

File: src/Server/HTTPHandler.cpp [hunk 1]
```diff
@@ -760,76 +759,84 @@ void HTTPHandler::processQuery(
...
 }
 
 void HTTPHandler::trySendExceptionToClient(
     const std::string & s, int exception_code, HTTPServerRequest & request, HTTPServerResponse & response, Output & used_output)
+try
 {
-    try
+    response.set("X-ClickHouse-Exception-Code", toString<int>(exception_code));
+
+    /// FIXME: make sure that no one else is reading from the same stream at the moment.
```
Comment (amosbird) [inline src/Server/HTTPHandler.cpp:771]: What will happen if there are multiple readers?

**Comment by azat** [comment]
>Integration tests (release) — fail: 3, passed: 1582, flaky: 17
>Integration tests (thread) — fail: 3, passed: 1582, flaky: 15

- flaky `test_MemoryTracking` - #28719
- flaky `test_distributed_load_balancing` - #28723

**Comment by azat** [comment]
@kitaisreal can you take a look one more time please?

File: src/Server/HTTPHandler.cpp (hunk 1 above)
Comment (azat) [reply src/Server/HTTPHandler.cpp:771]: Let's ask @abyss7 (the author of this `FIXME`) ?

**Comment by azat** [comment]
One more case - https://clickhouse-test-reports.s3.yandex.net/0/4204e20f06850a139db9cd17aac5de592a3dfa44/stress_test_(address).html#fail1 (that should be fixed by this patch)

**Comment by azat** [comment]
@kitaisreal friendly ping

**Review by kitaisreal — APPROVED** [review]

**Comment by filimonov** [comment]
Catched that on 21.3. Should it be backported?
