### PR TITLE
Fix read from remote without hedged requests

### LINKED ISSUE #76177: Distributed selects can return incorrect data if use_hedged_requests is disabled
### Company or project name

_No response_

### Describe the unexpected behaviour

If `max_parallel_replicas` is > 1 and `use_hedged_requests` is disabled then distributed tables send selects to all replicas of every shard.

### How to reproduce

```
select name, shard_num, replica_num from system.clusters where name='replicated'

name       | shard_num | replica_num
-----------+-----------+------------
replicated |         1 |           1
replicated |         1 |           2
replicated |         1 |           3

SELECT dummy FROM cluster(replicated, system.one)
settings max_parallel_replicas=1, use_hedged_requests=0

dummy
-----
    0

SELECT dummy FROM cluster(replicated, system.one)
settings max_parallel_replicas=10, use_hedged_requests=0

dummy
-----
    0
    0
    0
```

### Expected behavior

I would expect ClickHouse to return one copy of a dataset even if it sends queries to all replicas.

### Error message and/or stacktrace

_No response_

### Additional context

I ran into this in 25.1 after `max_parallel_replicas` was set to 1000 by default.

### PR DESCRIPTION
**Pull request by korowa**
Closes #76177 

In case of disabled parallel reading from replicas, hedged connections will read from single replica, but when hedged requests are disabled, the query will use `max_parallel_replicas`.

This patch enforces client to use single replica in case of disabled parallel replicas reading with `PoolMode::GET_ONE`, and removes this logic from `HedgedConnections`.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix result duplication when reading from remote with both `use_hedged_requests` and `allow_experimental_parallel_reading_from_replicas` disabled

### CODE REVIEW

File: tests/queries/0_stateless/03444_distributed_wo_hedged_requests.sql [hunk 1]
```diff
@@ -0,0 +1,26 @@
+drop table if exists 03444_local;
+drop table if exists 03444_distr;
+
+create table 03444_local (id UInt32) engine = MergeTree order by id as select * from numbers(100);
+create table 03444_distr (id UInt32) engine = Distributed(test_cluster_one_shard_two_replicas, currentDatabase(), 03444_local);
+
+select 'remote() 1 shard: ' || count()
+from remote('127.0.0.1|127.0.0.2|127.0.0.3', currentDatabase(), 03444_local)
+settings prefer_localhost_replica = 0,
+         use_hedged_requests = 0,
```
Comment (azat) [inline tests/queries/0_stateless/03444_distributed_wo_hedged_requests.sql:10]: Let's also test with and without use_hedged_requests and with and without async_socket_for_remote

**Review by azat — APPROVED** [review]
What a bug.. thank you!

LGTM

**Comment by azat** [comment]
Let's also take a look at this - https://github.com/ClickHouse/ClickHouse/pull/79602
