### PR TITLE
Less strict metadata checks for RMT in Replicated database

### LINKED ISSUE #80296: METADATA_MISMATCH after `ALTER TABLE ADD INDEX` in Database Replicated if replica was offline
### Company or project name

_No response_

### Describe what's wrong

In Database Replicated, if a replica was offline during a `CREATE TABLE ... ENGINE = ReplicatedMergeTree` query and after that we execute `ALTER TABLE ADD INDEX` index, then when the replica becomes online it will get stuck on a create query, it will throw `METADATA_MISMATCH`.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

-

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Perform less strict metadata checks for RMT in the Replicated database. Closes https://github.com/ClickHouse/ClickHouse/issues/80296

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/MergeTree/ReplicatedMergeTreeTableMetadata.cpp [hunk 1]
```diff
@@ -292,7 +320,7 @@ void ReplicatedMergeTreeTableMetadata::checkImmutableFieldsEquals(
         throwTableMetadataMismatch(table_name_for_error_message, "date index column", from_zk.date_column, "", "custom-partitioned");
     }
 
-    if (index_granularity != from_zk.index_granularity)
+    if (check_index_granularity && index_granularity != from_zk.index_granularity)
```
Comment (tuanpach) [inline src/Storages/MergeTree/ReplicatedMergeTreeTableMetadata.cpp:323]: In `checkEquals`, we check `from_zk.index_granularity_bytes_found_in_zk`. Do we need to check it here also?

And if we consider `index_granularity` is immutable, should we remove the similar check in `checkEquals`?

**Review by tuanpach — APPROVED** [review]

**Review by tuanpach — APPROVED** [review]
