### PR TITLE
Fix possible recursive static var initialization (in debug build) due to big allocations check

### LINKED ISSUE #78061: libc++abi: __cxa_guard_acquire detected recursive initialization: do you have a function-local static variable whose initialization depends on that function?
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77841&sha=d509e6a648f0af7260e12d5823ee03a2ba7e6122&name_0=PR&name_1=Stateless%20tests%20%28asan%2C%20flaky%20check%29

```
+ clickhouse-local --max_block_size 8192 --max_memory_usage 10G --max_threads 1 --max_result_rows 0 --max_result_bytes 0 --max_bytes_to_read 0 --path=/var/lib/clickhouse/ -q 'select * from system.error_log into outfile '\''/test_output/error_log.tsv.zst'\'' format TSVWithNamesAndTypes' --only-system-tables --stacktrace -- --zookeeper.implementation=testkeeper
libc++abi: __cxa_guard_acquire detected recursive initialization: do you have a function-local static variable whose initialization depends on that function?
/repo/tests/docker_scripts/stateless_runner.sh: line 452: 12835 Aborted                 clickhouse-local "${args[@]}"
```

And no core file

### PR DESCRIPTION
**Pull request by azat**
CI found some errors like:

    __cxa_guard_acquire detected recursive initialization: do you have a function-local static variable whose initialization depends on that function

The problem was with SymbolIndex.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/78061

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible recursive static var initialization (in debug build) due to big allocations check

### CODE REVIEW

File: src/Common/MemoryTrackerDebugBlockerInThread.h [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+private:
+    static thread_local uint64_t counter;
+};
+#else
+struct MemoryTrackerDebugBlockerInThread
+{
+public:
+    static constexpr bool isEnabled() { return false; }
+    static constexpr bool isBlocked() { return true; }
```
Comment (Michicosun) [inline src/Common/MemoryTrackerDebugBlockerInThread.h:25]:
```suggestion
    static constexpr bool isBlocked() { return false; }
```

File: src/Common/MemoryTrackerDebugBlockerInThread.h [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+{
+public:
+    MemoryTrackerDebugBlockerInThread();
+    ~MemoryTrackerDebugBlockerInThread();
+
+    static bool isBlocked() { return counter > 0; }
+    static constexpr bool isEnabled() { return true; }
+
+private:
+    static thread_local uint64_t counter;
```
Comment (Michicosun) [inline src/Common/MemoryTrackerDebugBlockerInThread.h:18]: It is better to declare this variable in cpp file. Maybe name it `MemoryTrackerDebugBlockerInThreadCounter` wdyt?

**Review by Michicosun — CHANGES_REQUESTED** [review]

File: src/Common/MemoryTrackerDebugBlockerInThread.h (hunk 1 above)
Comment (azat) [reply src/Common/MemoryTrackerDebugBlockerInThread.h:25]: Can you elaborate?

Since in case of `!DEBUG_OR_SANITIZER_BUILD` (**no sanitizers or debug**), then it does not matter since `isEnabled` is `false` anyway, and this `isBlocked` will never be called. I used `true` just to underline that it will not be used in release builds.

File: src/Common/MemoryTrackerDebugBlockerInThread.h (hunk 2 above)
Comment (azat) [reply src/Common/MemoryTrackerDebugBlockerInThread.h:18]: I  did in the same manner as other blockers done (i.e. `MemoryTrackerBlockerInThread`).

Though I like yours suggestion, since this one is different from others, because it is no-op in release builds, and it does not need "hot code path" (`isBlocked` inlined inside header) anyway (and I'm not sure that it is required for others as well, not only because of LTO, but just in general, it is called only each 4MB by default, and it access other thread local variables anyway).

Comment (azat) [reply src/Common/MemoryTrackerDebugBlockerInThread.h]: Done

**Comment by azat** [comment]
Also now there is a test

File: src/Common/MemoryTrackerDebugBlockerInThread.h (hunk 1 above)
Comment (Michicosun) [reply src/Common/MemoryTrackerDebugBlockerInThread.h:20]: I know, I just thought it would be a little clearer if the logic was the completely opposite to the code in the debug build. But okay, let's leave it as is.

**Review by Michicosun — APPROVED** [review]

**Comment by azat** [comment]
CI failures are well known and not related
