### PR TITLE
Revert "Revert "Fix inconsistent formatting of TTL""

### LINKED ISSUE #82828: Inconsistent formatting of TTL
> An example with TTL:
> 
> ```sql
> CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() TTL (materialize(c0));
> ```
> New case? 

 _Originally posted by @PedroTadim in [#82105](https://github.com/ClickHouse/ClickHouse/issues/82105#issuecomment-2991839888)_

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix inconsistent formatting of TTL when it contains a `materialize` function. Closes #82828.

### CODE REVIEW

File: tests/queries/0_stateless/03555_inconsistent_formatting_ttl.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+DROP TABLE IF EXISTS t0;
+CREATE TABLE t0 (c0 Date) ENGINE = MergeTree() ORDER BY () TTL (materialize(c0));
```
Comment (PedroTadim) [inline tests/queries/0_stateless/03555_inconsistent_formatting_ttl.sql:2]: If the TTL is set on the column, it will also work, right?

Comment (alexey-milovidov) [reply tests/queries/0_stateless/03555_inconsistent_formatting_ttl.sql:2]: It should. Although this case is not really important (whether a TTL expression starting with the `materialize` function works or not), the goal here is to avoid "inconsistent parsing".
