### PR TITLE
Fix flaky `02812_from_to_utc_timestamp.sh`

### LINKED ISSUE #72794: Test `02812_from_to_utc_timestamp` is flaky
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDI4MTJfZnJvbV90b191dGNfdGltZXN0YW1wJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

### PR DESCRIPTION
**Pull request by yariks5s**
Fixes #72794

The test becomes flaky because of the randomized flag `--session_timezone Asia/Qostanay` during testing. So we need to set the setting explicitly and not use additional `session_timezone` flags, which can lead this test to be flaky

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 3152f6b74e7870ce2d908f727dd825ce389db1e8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75212/3152f6b74e7870ce2d908f727dd825ce389db1e8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d8a0cf6e81fee2e26c135200d8838bfd8db9dc00/builds/report.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d819a5d0e4c4f9b1fe582ec61689c9a053c045d7/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d8a0cf6e81fee2e26c135200d8838bfd8db9dc00/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/02812_from_to_utc_timestamp.sh [hunk 1]
```diff
@@ -18,15 +18,15 @@ ${CLICKHOUSE_CLIENT} -q "INSERT INTO test_tbl values(2, '2023-03-16 11:22:33', '
 ${CLICKHOUSE_CLIENT} -q "INSERT INTO test_tbl values(3, '2023-03-16 11:22:33', '2023-03-16 11:22:33.123456')"
 $CLICKHOUSE_CLIENT -q "select x, to_utc_timestamp(toDateTime('2023-03-16 11:22:33'), 'Etc/GMT+1'), from_utc_timestamp(toDateTime64('2023-03-16 11:22:33', 3), 'Etc/GMT+1'), to_utc_timestamp(y, 'Asia/Shanghai'), from_utc_timestamp(z, 'Asia/Shanghai') from test_tbl order by x"
 # timestamp convert between DST timezone and UTC
-$CLICKHOUSE_CLIENT "${client_opts[@]}" -q "select to_utc_timestamp(toDateTime('2024-02-24 11:22:33'), 'Europe/Madrid'), from_utc_timestamp(toDateTime('2024-02-24 11:22:33'), 'Europe/Madrid')"
-$CLICKHOUSE_CLIENT "${client_opts[@]}" -q "select to_utc_timestamp(toDateTime('2024-10-24 11:22:33'), 'Europe/Madrid'), from_utc_timestamp(toDateTime('2024-10-24 11:22:33'), 'Europe/Madrid')"
-$CLICKHOUSE_CLIENT "${client_opts[@]}" -q "select to_utc_timestamp(toDateTime('2024-10-24 11:22:33'), 'EST'), from_utc_timestamp(toDateTime('2024-10-24 11:22:33'), 'EST')"
+$CLICKHOUSE_CLIENT -q "select to_utc_timestamp(toDateTime('2024-02-24 11:22:33'), 'Europe/Madrid'), from_utc_timestamp(toDateTime('2024-02-24 11:22:33'), 'Europe/Madrid') ${timezone_setting[@]}"
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/02812_from_to_utc_timestamp.sh:21]: I think randomizing `session_timezone` makes sense, however you are not passing any timezone argument to `toDateTime`. I think the proper way should be:
```suggestion
$CLICKHOUSE_CLIENT -q "select to_utc_timestamp(toDateTime('2024-02-24 11:22:33', 'Europe/Madrid'), 'Europe/Madrid'), from_utc_timestamp(toDateTime('2024-02-24 11:22:33', 'Europe/Madrid'), 'Europe/Madrid')"
```

What do you think?

Comment (yariks5s) [reply tests/queries/0_stateless/02812_from_to_utc_timestamp.sh:21]: We cannot do this:
`Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Function toUTCTimestamp's 1st argument should not have explicit time zone.: In scope SELECT 'leap year:', to_utc_timestamp(toDateTime('2024-02-28 23:22:33', 'Europe/Madrid'), 'EST'), from_utc_timestamp(toDateTime('2024-03-01 00:22:33', 'Europe/Madrid'), 'EST'). (ILLEGAL_TYPE_OF_ARGUMENT)`

**Comment by yariks5s** [comment]
`Stress test (asan) — Killed by signal (in clickhouse-server.log)` - flaky on master

**Review by antaljanosbenjamin — APPROVED** [review]

File: tests/queries/0_stateless/02812_from_to_utc_timestamp.sh [hunk 2]
```diff
@@ -7,8 +7,8 @@ CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 . "$CURDIR"/../shell_config.sh
 
 
-client_opts=(
-  --session_timezone Europe/Moscow
+timezone_setting=(
```
[the remark this answers is not in the document]
Comment (yariks5s) [reply tests/queries/0_stateless/02812_from_to_utc_timestamp.sh:10]: It was previously in .sh, but it makes sense to change it to SQL test, will do it, thanks
