### PR TITLE
clickhouse-local can work without tmp directory

### LINKED ISSUE #12123: clickhouse-local does not work if there is no /tmp directory
```
$ ls -lR

.:
total 1645932
-rwxrwxr-x 1 milovidov milovidov 1685419984 июл  4 00:33 clickhouse
drwxrwxr-x 2 milovidov milovidov       4096 июл  4 00:36 lib
drwxrwxr-x 2 milovidov milovidov       4096 июл  4 00:36 lib64

./lib:
total 3536
-rwxr-xr-x 1 milovidov milovidov 2025032 июл  4 00:36 libc.so.6
-rw-r--r-- 1 milovidov milovidov   18816 июл  4 00:36 libdl.so.2
-rw-r--r-- 1 milovidov milovidov 1369352 июл  4 00:36 libm.so.6
-rwxr-xr-x 1 milovidov milovidov  158288 июл  4 00:36 libpthread.so.0
-rw-r--r-- 1 milovidov milovidov   40040 июл  4 00:36 librt.so.1

./lib64:
total 184
-rwxr-xr-x 1 milovidov milovidov 187376 июл  4 00:36 ld-linux-x86-64.so.2


$ sudo chroot . /clickhouse local --query "SELECT 1"
filesystem error: in temp_directory_path: path "/tmp" is not a directory: Not a directory
```

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If there are no tmp folder in the system (chroot, misconfigutation etc) clickhouse-local will create temporary subfolder in the current directory.

Detailed description / Documentation draft:
Some extra logging added. Fixes  #12123

Before
```
$ TMP=/non-existent-folder-12123 clickhouse-local -q 'SELECT 1'
filesystem error: in temp_directory_path: path "/non-existent-folder-12123" is not a directory: Not a directory
```

After:
```
$ TMP=/non-existent-folder-12123 clickhouse-local -q 'SELECT 1'
1

$ TMP=/asdfasd clickhouse-local -q 'SELECT 1' --logger.console=1 
Logging trace to console
2020.10.23 14:55:45.388044 [ 223 ] {} <Debug> Application: Can not get temporary folder: filesystem error: in temp_directory_path: path "/asdfasd" is not a directory: Not a directory
2020.10.23 14:55:45.390411 [ 223 ] {} <Debug> Application: Will create working directory inside current directory: /
2020.10.23 14:55:45.390540 [ 223 ] {} <Debug> Application: Working directory created: /clickhouse-local-223-1603464945-5194555242134056268
2020.10.23 14:55:45.392250 [ 223 ] {} <Debug> Application: Loading metadata from /clickhouse-local-223-1603464945-5194555242134056268/
2020.10.23 14:55:45.420139 [ 223 ] {} <Information> DatabaseAtomic (system): Total 0 tables and 0 dictionaries.
2020.10.23 14:55:45.420166 [ 223 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2020.10.23 14:55:45.421046 [ 223 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 16 threads
2020.10.23 14:55:45.422479 [ 223 ] {} <Debug> Application: Loaded metadata.
2020.10.23 14:55:45.422692 [ 223 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2020.10.23 14:55:45.422717 [ 223 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, SOURCES ON *.*
2020.10.23 14:55:45.422882 [ 223 ] {a5fb7054-15f3-4b95-9775-90174ae1a086} <Debug> executeQuery: (from 0.0.0.0:0) SELECT 1
2020.10.23 14:55:45.423244 [ 223 ] {a5fb7054-15f3-4b95-9775-90174ae1a086} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2020.10.23 14:55:45.423335 [ 223 ] {a5fb7054-15f3-4b95-9775-90174ae1a086} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
1
2020.10.23 14:55:45.423644 [ 223 ] {a5fb7054-15f3-4b95-9775-90174ae1a086} <Information> executeQuery: Read 1 rows, 1.00 B in 0.000717001 sec., 1394 rows/sec., 1.36 KiB/sec.
2020.10.23 14:55:45.423681 [ 223 ] {a5fb7054-15f3-4b95-9775-90174ae1a086} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2020.10.23 14:55:45.423984 [ 223 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2020.10.23 14:55:45.424182 [ 223 ] {} <Debug> Application: Removing temporary directory: /clickhouse-local-223-1603464945-5194555242134056268
2020.10.23 14:55:45.424556 [ 223 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
```

### CODE REVIEW

File: programs/local/LocalServer.cpp [hunk 1]
```diff
@@ -121,31 +122,52 @@ void LocalServer::tryInitPath()
...
+        /// we just try to pick some free name for our working folder
+        size_t retries = 0;
+
+        while (1)
+        {
+            retries++;
+
+            default_path = parent_folder / fmt::format("clickhouse-local-{}-{}-{}", getpid(), time(nullptr), retries);
+
+            if (!exists(default_path))
```
Comment (akuzm) [inline programs/local/LocalServer.cpp:159]: So two instances can see that a dir doesn't exist and try to create it simultaneously? Better to create in the loop and retry on errors, and also use a random suffix so that all instances don't retry same folders in sequence. The precision of `time` is one second, so this is basically guaranteed to fail.

File: programs/local/LocalServer.cpp [hunk 2]
```diff
@@ -443,18 +465,17 @@ void LocalServer::cleanup()
     // bug.
     if (temporary_directory_to_delete)
     {
-        const auto tmp = std::filesystem::temp_directory_path();
         const auto dir = *temporary_directory_to_delete;
         temporary_directory_to_delete.reset();
 
-        if (!std::filesystem::equivalent(dir.parent_path(), tmp))
+        if (dir.string().find(fmt::format("clickhouse-local-{}", getpid())) == std::string::npos)
```
Comment (akuzm) [inline programs/local/LocalServer.cpp:471]: Maybe we should remove this check altogether? Not sure it's really helpful.

File: src/Interpreters/Context.cpp [hunk 3]
```diff
@@ -2029,10 +2029,13 @@ void Context::reloadConfig() const
 
 void Context::shutdown()
 {
-    for (auto & [disk_name, disk] : getDisksMap())
+    if (shared->merge_tree_disk_selector)
```
Comment (filimonov) [inline src/Interpreters/Context.cpp:2032]: for the record - it was trying to init the disk to shutdown context when an exception was happened before initializing disks. 

```
programs/clickhouse local -q select 1 
Code: 504, e.displayText() = DB::Exception: Unsuccessfull attempt to create working directory: /tmp/clickhouse-local-810185-1603461716-11695049450137462916 exist! (version 20.11.1.1)
terminating with uncaught exception of type DB::Exception: Disk path must ends with '/', but '' doesn't.
Aborted (core dumped)


(gdb) bt
#0  DB::DiskLocal::DiskLocal (this=this@entry=0x7ffff700f218, name_=..., path_=..., keep_free_space_bytes_=0) at ../src/Disks/DiskLocal.h:28
#1  0x00000000092d55be in std::__1::__compressed_pair_elem<DB::DiskLocal, 1, false>::__compressed_pair_elem<char const* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, int&&, 0ul, 1ul, 2ul> (this=this@entry=0x7ffff700f218, __args=...) at ../contrib/libcxx/include/memory:2214
#2  0x00000000092d3cf5 in std::__1::__compressed_pair<std::__1::allocator<DB::DiskLocal>, DB::DiskLocal>::__compressed_pair<std::__1::allocator<DB::DiskLocal>&, char const* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, int&&> (this=0x7ffff700f218, __first_args=..., __second_args=..., __pc=...) at ../contrib/libcxx/include/memory:2298
#3  std::__1::__shared_ptr_emplace<DB::DiskLocal, std::__1::allocator<DB::DiskLocal> >::__shared_ptr_emplace<char const* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> (this=0x7ffff700f200, __args=@0x7fffffffc7bc: 0, __args=@0x7fffffffc7bc: 0, __args=@0x7fffffffc7bc: 0, __a=...) at ../contrib/libcxx/include/memory:3569
#4  std::__1::make_shared<DB::DiskLocal, char const* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> (__args=@0x7fffffffc7bc: 0, 
    __args=@0x7fffffffc7bc: 0, __args=@0x7fffffffc7bc: 0) at ../contrib/libcxx/include/memory:4400
#5  DB::DiskSelector::DiskSelector (this=<optimized out>, config=..., config_prefix=..., context=...) at ../src/Disks/DiskSelector.cpp:43
#6  0x000000000931b9b3 in std::__1::__compressed_pair_elem<DB::DiskSelector, 1, false>::__compressed_pair_elem<Poco::Util::AbstractConfiguration const&, char const* const&, DB::Context const&, 0ul, 1ul, 2ul> (this=this@entry=0x7ffff7004b58, __args=...) at ../contrib/libcxx/include/memory:2214
#7  0x000000000930a449 in std::__1::__compressed_pair<std::__1::allocator<DB::DiskSelector>, DB::DiskSelector>::__compressed_pair<std::__1::allocator<DB::DiskSelector>&, Poco::Util::AbstractConfiguration const&, char const* const&, DB::Context const&> (this=0x7ffff7004b58, __first_args=..., __second_args=..., __pc=...) at ../contrib/libcxx/include/memory:2298
#8  std::__1::__shared_ptr_emplace<DB::DiskSelector, std::__1::allocator<DB::DiskSelector> >::__shared_ptr_emplace<Poco::Util::AbstractConfiguration const&, char const* const&, DB::Context const&> (
    this=0x7ffff7004b40, __args=..., __args=..., __args=..., __a=...) at ../contrib/libcxx/include/memory:3569
#9  std::__1::make_shared<DB::DiskSelector, Poco::Util::AbstractConfiguration const&, char const* const&, DB::Context const&> (__args=..., __args=..., __args=...)
    at ../contrib/libcxx/include/memory:4400
#10 DB::Context::getDiskSelector (this=this@entry=0x7ffff70e2000) at ../src/Interpreters/Context.cpp:1826
#11 0x000000000930a5ff in DB::Context::getDisksMap (this=this@entry=0x7ffff70e2000) at ../src/Interpreters/Context.cpp:1810
#12 0x000000000930c461 in DB::Context::shutdown (this=0x7ffff70e2000) at ../src/Interpreters/Context.cpp:2032
#13 0x000000000482094a in DB::LocalServer::~LocalServer (this=this@entry=0x7fffffffcab8) at ../programs/local/LocalServer.cpp:63
#14 0x0000000004827fe0 in mainEntryClickHouseLocal (argc=<optimized out>, argv=<optimized out>) at ../programs/local/LocalServer.cpp:618
#15 0x0000000004772f13 in main (argc_=<optimized out>, argv_=<optimized out>) at ../programs/main.cpp:400
```

Comment (akuzm) [reply src/Interpreters/Context.cpp:2032]:
```suggestion
    // Disk selector might not be initialized if there was some error during
    // its initialization. Don't try to initialize it again on shutdown.
    if (shared->merge_tree_disk_selector)
```

File: programs/local/LocalServer.cpp [hunk 4]
```diff
@@ -50,6 +51,7 @@ namespace ErrorCodes
     extern const int LOGICAL_ERROR;
```
Comment (akuzm) [inline programs/local/LocalServer.cpp:51]:
```suggestion
```

(style check)
