### PR TITLE
Fix `KeeperMap` create after incomplete drop

### LINKED ISSUE #66862: Test `02911_backup_restore_keeper_map` is flaky
**Describe the bug**

https://s3.amazonaws.com/clickhouse-test-reports/0/7beff2d58291f4a710d17f99828c66b5e50af021/stateless_tests__tsan__s3_storage__%5B2_4%5D.html

**Additional information**

Test failed 2 times on master branch in the past 60 days and 13 times in PRs+master: [report.](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19uYW1lIExJS0UgJ1N0YXRlJScKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgNjAgREFZUwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzIExJS0UgJ0YlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBjaGVja19uYW1lIE5PVCBMSUtFICdTUUxhbmNlciUnCiAgICBBTkQgdGVzdF9uYW1lIElMSUtFICclMDI5MTFfYmFja3VwX3Jlc3RvcmVfa2VlcGVyX21hcCUnCk9SREVSIEJZIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgY2hlY2tfc3RhcnRfdGltZQ==)

**Error message and/or stacktrace**

```
2024-07-22 09:27:33 Reason: having stderror:  
2024-07-22 09:27:33 [b52e32bbbd6f] 2024.07.22 04:27:21.053805 [ 25798 ] {c0e63755-ab59-4b37-8922-c5580140ca52} <Error> BackupsWorker: Failed to restore from backup Disk('backups', 'test_4z9tkly7_02911_keeper_map'): Code: 36. DB::Exception: Cannot create metadata for table, because it is removed concurrently or because of wrong zk_root_path (/test_keeper_map/test_4z9tkly7/test02911): While creating table test_4z9tkly7_02911_keeper_map.`02911_backup_restore_keeper_map1`. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):
2024-07-22 09:27:33 
2024-07-22 09:27:33 0. ./contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x000000001df7e043
2024-07-22 09:27:33 1. ./build_docker/./src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f811195
2024-07-22 09:27:33 2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000073fa3a0
2024-07-22 09:27:33 3. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x0000000007439080
2024-07-22 09:27:33 4. ./build_docker/./src/Storages/StorageKeeperMap.cpp:479: DB::StorageKeeperMap::StorageKeeperMap(std::shared_ptr<DB::Context const>, DB::StorageID const&, DB::StorageInMemoryMetadata const&, bool, std::basic_string_view<char, std::char_traits<char>>, String const&, unsigned long) @ 0x0000000018d6683d
2024-07-22 09:27:33 5. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:0: std::shared_ptr<DB::StorageKeeperMap> std::allocate_shared[abi:v15007]<DB::StorageKeeperMap, std::allocator<DB::StorageKeeperMap>, std::shared_ptr<DB::Context>, DB::StorageID const&, DB::StorageInMemoryMetadata&, bool const&, String&, String&, unsigned long&, void>(std::allocator<DB::StorageKeeperMap> const&, std::shared_ptr<DB::Context>&&, DB::StorageID const&, DB::StorageInMemoryMetadata&, bool const&, String&, String&, unsigned long&) @ 0x0000000018d80b9d
2024-07-22 09:27:33 6. ./build_docker/./src/Storages/StorageKeeperMap.cpp:1292: DB::(anonymous namespace)::create(DB::StorageFactory::Arguments const&) @ 0x0000000018d77314
2024-07-22 09:27:33 7. ./contrib/llvm-project/libcxx/include/__functional/function.h:0: ? @ 0x00000000161ce324
2024-07-22 09:27:33 8. ./build_docker/./src/Storages/StorageFactory.cpp:225: DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel) const @ 0x0000000018cb5ac6
2024-07-22 09:27:33 9. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1552: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x0000000017805ddf
2024-07-22 09:27:33 10. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:0: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x00000000177ff64a
2024-07-22 09:27:33 11. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1875: DB::InterpreterCreateQuery::execute() @ 0x000000001780c3ee
2024-07-22 09:27:33 12. ./build_docker/./src/Databases/DatabasesCommon.cpp:0: DB::DatabaseWithOwnTablesBase::createTableRestoredFromBackup(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::IRestoreCoordination>, unsigned long) @ 0x0000000016df41f3
2024-07-22 09:27:33 13. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::RestorerFromBackup::createTable(DB::QualifiedTableName const&) @ 0x0000000016691188
2024-07-22 09:27:33 14. ./build_docker/./src/Backups/RestorerFromBackup.cpp:871: DB::RestorerFromBackup::createTables() @ 0x0000000016687645
2024-07-22 09:27:33 15. ./build_docker/./src/Backups/RestorerFromBackup.cpp:153: DB::RestorerFromBackup::run(DB::RestorerFromBackup::Mode) @ 0x0000000016682063
2024-07-22 09:27:33 16. ./build_
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix creating KeeperMap table after an incomplete drop.

Should fix `02911_backup_restore_keeper_map` also https://s3.amazonaws.com/clickhouse-test-reports/0/7beff2d58291f4a710d17f99828c66b5e50af021/stateless_tests__tsan__s3_storage__[2_4].html

Fix https://github.com/ClickHouse/ClickHouse/issues/66862

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit c36dde51031e817b20db6773df47a42092f6616b with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66865/c36dde51031e817b20db6773df47a42092f6616b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66806/e74892bfaf4aa98654a6253a34bbeb3f1740de41/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/03208_keepermap_incomplete_data_drop.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+DROP TABLE IF EXISTS 03208_keepermap_test SYNC;
+
+CREATE TABLE 03208_keepermap_test (key UInt64, value UInt64) Engine=KeeperMap('/' || currentDatabase() || '/test03208') PRIMARY KEY(key);
+INSERT INTO 03208_keepermap_test VALUES (1, 11);
+SYSTEM ENABLE FAILPOINT keepermap_fail_drop_data;
+DROP TABLE 03208_keepermap_test;
```
Comment (vitlibar) [inline tests/queries/0_stateless/03208_keepermap_incomplete_data_drop.sql:6]: Shouldn't that `DROP TABLE 03208_keepermap_test` throw an exception?
(because of `SYSTEM ENABLE FAILPOINT keepermap_fail_drop_data`)

File: src/Storages/StorageKeeperMap.cpp [hunk 2]
```diff
@@ -411,18 +417,13 @@ StorageKeeperMap::StorageKeeperMap(
...
-            // tables_path was removed with drop
-            if (code == Coordination::Error::ZNONODE)
-            {
-                LOG_INFO(log, "Metadata nodes were removed by another server, will retry");
-                continue;
-            }
-            else if (code != Coordination::Error::ZOK)
-            {
+            if (code == Coordination::Error::ZOK)
+                return;
```
Comment (vitlibar) [inline src/Storages/StorageKeeperMap.cpp:421]: Thus there are two `returns` from this constructor - the first one is here, and the second one is near the end of the constructor. The second return is used when the first replica is added, and the first return is used when any other replica is added, isn't it? It's not really obvious, if we had comments it would be better.

And it seems you set `table_is_valid = true` only for the second return, but not for the first one. Why?

Comment (antonio2368) [reply src/Storages/StorageKeeperMap.cpp:421]: I will add comments
but in short, when we add new replicas, we successfully created it but we are still not sure if all nodes are okay and that the metadata matches, so we lazily check the table
the lazy check was added to avoid failing attach if there is no ZK connection

but it would make sense to change it and instantly fail to create a table if the table is invalid, I can do it in another PR

File: tests/queries/0_stateless/03208_keepermap_incomplete_data_drop.sql (hunk 1 above)
Comment (antonio2368) [reply tests/queries/0_stateless/03208_keepermap_incomplete_data_drop.sql:6]: yeah you are right, `database_atomic_wait_for_drop_and_detach_synchronously` needs to be `0`
locally I didn't have SYNC drops turned on so I didn't notice it

the reason we didn't get exceptions was because the failpoint is defined with `ONCE` so the drop will only fail the first time and succeed on the subsequent retries

Comment (vitlibar) [reply tests/queries/0_stateless/03208_keepermap_incomplete_data_drop.sql]: Maybe it makes sense to call `DROP TABLE SYNC` and expect an exception in the test, WDYT?
Just in order to make the test more related to the case.

**Review by vitlibar — APPROVED** [review]
