### PR TITLE
Fix comparison between integers and floats in index analysis

### LINKED ISSUE #34493: wrong float comparison with constant for Float32
create table test1 (a Float32,  b Float32 ) engine = MergeTree order by a ;
insert into test1 values (0.1,0.1), (0.2,0.2);
select count() from test1 where b = 0.1;
0 
select count() from test1 where b = toFloat32(0.1);
1
select count() from test1 where a > 0;
0
select count() from test1 where a > 0.0;
2
select count() from test1 where b > 0;
2

version 22.1.3.7

### PR DESCRIPTION
**Pull request by CurtizJ**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix comparison between integers and floats in index analysis. Previously it could lead to skipping some granules for reading by mistake. Fixes #34493.

### CODE REVIEW

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 1]
```diff
@@ -1292,8 +1292,8 @@ bool KeyCondition::tryParseAtomFromAST(const ASTPtr & node, ContextPtr context,
                 key_expr_type_not_null = key_expr_type;
 
             bool cast_not_needed = is_set_const /// Set args are already casted inside Set::createFromAST
-                || ((isNativeNumber(key_expr_type_not_null) || isDateTime(key_expr_type_not_null))
-                    && (isNativeNumber(const_type) || isDateTime(const_type))); /// Numbers and DateTime are accurately compared without cast.
+                || ((isInteger(key_expr_type_not_null) || isDateTime(key_expr_type_not_null))
+                    && (isInteger(const_type) || isDateTime(const_type))); /// Integers and DateTime are accurately compared without cast.
```
Comment (CurtizJ) [inline src/Storages/MergeTree/KeyCondition.cpp:1296]: Without cast for floats for conditions like `float_column > 0` we could get wrong results, because we will create integer range `(0, +inf)` for analysis and it could be optimized to [1, +inf) [here](https://github.com/ClickHouse/ClickHouse/blob/c347438612f70def27a7675bb13faa9ff1de98e8/src/Storages/MergeTree/KeyCondition.h#L103-L135), which is obviously wrong for floats in `(0, 1)`.

**Review by kitaisreal — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
