### PR TITLE
Fix filling of missed subcolumns

### LINKED ISSUE #66173: Wrong query result when `optimize_functions_to_subcolumns=1` after alter table add column Nullable
```sql
create table test (x UInt32) engine=MergeTree order by tuple() settings min_bytes_for_wide_part=1, min_rows_for_wide_part=1;
insert into test select * from numbers(10);
alter table test add column y Nullable(UInt32);
insert into test select number, if(number % 2, NULL, number) from numbers(10);
```

```sql
avogar-dev :) select x from test where y is not null settings optimize_functions_to_subcolumns=1

SELECT x
FROM test
WHERE y IS NOT NULL
SETTINGS optimize_functions_to_subcolumns = 1

Query id: fc4bf54e-f8c6-4613-84db-96055c0df322

    ┌─x─┐
 1. │ 0 │
 2. │ 1 │
 3. │ 2 │
 4. │ 3 │
 5. │ 4 │
 6. │ 5 │
 7. │ 6 │
 8. │ 7 │
 9. │ 8 │
10. │ 9 │
    └───┘
    ┌─x─┐
11. │ 0 │
12. │ 2 │
13. │ 4 │
14. │ 6 │
15. │ 8 │
    └───┘

15 rows in set. Elapsed: 0.004 sec.

avogar-dev :) select x from test where y is not null settings optimize_functions_to_subcolumns=0

SELECT x
FROM test
WHERE y IS NOT NULL
SETTINGS optimize_functions_to_subcolumns = 0

Query id: 20defeb3-3d11-4475-8ae0-10cbfb2f5829

   ┌─x─┐
1. │ 0 │
2. │ 2 │
3. │ 4 │
4. │ 6 │
5. │ 8 │
   └───┘

5 rows in set. Elapsed: 0.004 sec.
```

The result with `optimize_functions_to_subcolumns=1` is wrong. It happens because we don't have `y Nullable(UInt32)` column in the first part and during reading we fill all missing columns with default values. But filling `y.null` subcolumn with default values when `y` column is missing is actually wrong.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed reading of subcolumns after `ALTER ADD COLUMN` query.

Fixes #66173.

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit a2b17b01f9561fd1853851932a2ae77513c49e26 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66243/a2b17b01f9561fd1853851932a2ae77513c49e26/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b710af349958257e7cb9ab57235394d56968a96e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Interpreters/inplaceBlockConversions.cpp [hunk 1]
```diff
@@ -360,7 +378,7 @@ void fillMissingColumns(
         {
             /// We must turn a constant column into a full column because the interpreter could infer
             /// that it is constant everywhere but in some blocks (from other parts) it can be a full column.
-            res_columns[i] = type->createColumnConstWithDefaultValue(num_rows)->convertToFullColumnIfConst();
+            res_columns[i] = createColumnWithDefaultValue(*requested_column->getTypeInStorage(), requested_column->getSubcolumnName(), num_rows);
```
Comment (jkartseva) [inline src/Interpreters/inplaceBlockConversions.cpp:381]: I haven't look at this PR thoroughly because the unit tests are broken.
Looks like errors are related to the column type changes.

**Comment by alexey-milovidov** [comment]
@CurtizJ, tests have failed.

**Review by jkartseva — APPROVED** [review]
LGTM

File: src/Storages/MergeTree/IMergeTreeReader.cpp [hunk 2]
```diff
@@ -138,25 +140,33 @@ void IMergeTreeReader::evaluateMissingDefaults(Block additional_columns, Columns
...
-            if (res_columns[pos] == nullptr)
-                continue;
+            auto name_in_storage = it->getNameInStorage();
 
-            additional_columns.insert({res_columns[pos], name_and_type->type, name_and_type->name});
+            if (full_requested_columns_set.emplace(name_in_storage).second)
+                full_requested_columns.emplace_back(name_in_storage, it->getTypeInStorage());
+
+            if (res_columns[pos])
+                additional_columns.insert({res_columns[pos], it->type, it->name});
```
Comment (antonio2368) [inline src/Storages/MergeTree/IMergeTreeReader.cpp:165]: @CurtizJ should this be
```cpp
additional_columns.insert({res_columns[pos], it->type, name_in_storage});
```

Comment (CurtizJ) [reply src/Storages/MergeTree/IMergeTreeReader.cpp:165]: Almost correct but a bit more complicated: https://github.com/ClickHouse/ClickHouse/pull/70695.
