### PR TITLE
Fix: for `WITH FILL` expression (1) exclude sorting columns not present on current step, (2) inconsistent DAG

### LINKED ISSUE #76976: NOT_FOUND_COLUMN_IN_BLOCK error with new analyzer
### Company or project name

cogniteev

### Describe what's wrong

New query analyzer (enabled  by default) fails to execute a query.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Tested with `24.8.4.13` (version I'm using in production) and `25.1.5.31` (latest release at this time).

The following query:
```sql
WITH
    count(1) AS rows_count
SELECT
    toDate(parseDateTimeBestEffortUSOrZero(toString(fetch_date))) AS fetch_date
FROM
    s3('https://clickhouse-public-datasets.s3.amazonaws.com/youtube/original/files/*.zst', 'JSONLines')
GROUP BY
    fetch_date
ORDER BY
    fetch_date WITH FILL STEP INTERVAL 1 DAY,
    rows_count DESC
LIMIT 1 BY fetch_date
```

Fails with:

```
Received exception from server (version 25.1.5):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column count() in block. There are only columns: toDate(parseDateTimeBestEffortUSOrZero(toString(__table1.fetch_date))). (NOT_FOUND_COLUMN_IN_BLOCK)
```

### Expected behavior

Expect the query to work.

### Error message and/or stacktrace

_No response_

### Additional context

Any one of those actions will "resolve" the error by itself:

- set `allow_experimental_analyzer=0`
- remove `BY fetch_date` in `LIMIT` clause
- remove `WITH FILL STEP` clause
- move `rows_count` in `SELECT` clause

Maybe the cause is related to either https://github.com/ClickHouse/ClickHouse/issues/70356 or https://github.com/ClickHouse/ClickHouse/issues/76121 but I created a new issue because I can reproduce it without distributed table or parallel reading from replicas (although I do use it in my original use case)

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix: `WITH FILL` may fail with NOT_FOUND_COLUMN_IN_BLOCK when sorting column is removed by planer. Similar issue related to inconsistent DAG calculated for INTERPOLATE expression.

closes #76976

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
kind of related issue found in this investigation:
https://github.com/ClickHouse/ClickHouse/issues/77514
but nature is different, so will be handled separately

File: src/Planner/Planner.cpp [hunk 1]
```diff
@@ -760,12 +762,22 @@ void addWithFillStepIfNeeded(QueryPlan & query_plan,
...
 
+    auto sort_description = query_analysis_result.sort_description;
+
+    for (auto it = sort_description.begin(); it != sort_description.end();)
+    {
+        if (header.findByName(it->column_name))
+            ++it;
+        else
+            it = sort_description.erase(it);
+    }
```
Comment (novikd) [inline src/Planner/Planner.cpp:773]: I didn't understand this change. Please add a comment. I don't understand why we modify sort description

Comment (yakov-olkhovskiy) [reply src/Planner/Planner.cpp:773]: `query_analysis_result.sort_description` contains full set of sorting columns, however it is possible that header on some previous steps was optimized and doesn't contain some of the sorting columns already, but `FillingTransform` would assume these columns present in the header. An example of such situation is next query:
```
explain header=1
SELECT number
FROM numbers(10)
ORDER BY
    number ASC WITH FILL STEP 1,
    'aaa' ASC
LIMIT 1 BY number;

Expression (Project names)
Header: number UInt64
  Filling
  Header: __table1.number UInt64
    LimitBy
    Header: __table1.number UInt64
      Expression (Before LIMIT BY)
      Header: __table1.number UInt64
        Sorting (Sorting for ORDER BY)
        Header: __table1.number UInt64
                \'aaa\'_String String
          Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
          Header: __table1.number UInt64
                  \'aaa\'_String String
            ReadFromSystemNumbers
            Header: number UInt64
```

...but probably it's not an appropriate place to calculate `sort_description` - I will move it to the `deduplicateSortDescription` function

**Review by alexey-milovidov — APPROVED** [review]
