### PR TITLE
Fix trash in `TokenExtractor`

### LINKED ISSUE #92576: MemorySanitizer: use-of-uninitialized-value (STID: 1003-358c)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: MemorySanitizer: use-of-uninitialized-value (STID: 1003-358c)
CI report: [BuzzHouse (amd_msan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=1f0c87b97de34e620e89719dc617c451cfcf5162&name_0=MasterCI&name_1=BuzzHouse%20%28amd_msan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdNZW1vcnlTYW5pdGl6ZXI6IHVzZS1vZi11bmluaXRpYWxpemVkLXZhbHVlIChTVElEOiAxMDAzLTM1OGMpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQnV6ekhvdXNlIChhbWRfbXNhbiknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwKSBPUiBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDApCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
Error:
WARNING: MemorySanitizer: use-of-uninitialized-value
---

Stack trace:
#0 0x55a4d80e5746 in CityHash_v1_0_2::CityHash64(char const*, unsigned long) ci/tmp/build/./contrib/cityhash102/src/city.cc:243:1
#1 0x55a4d80e578d in CityHash_v1_0_2::CityHash64WithSeeds(char const*, unsigned long, unsigned long, unsigned long) ci/tmp/build/./contrib/cityhash102/src/city.cc:251:20
#2 0x55a4d80e578d in CityHash_v1_0_2::CityHash64WithSeed(char const*, unsigned long, unsigned long) ci/tmp/build/./contrib/cityhash102/src/city.cc:246:10
#3 0x55a4b76bab86 in DB::BloomFilter::add(char const*, unsigned long) ci/tmp/build/./src/Interpreters/BloomFilter.cpp:79:20
#4 0x55a4b76ac74d in DB::ITokenExtractorHelper<DB::NgramsTokenExtractor>::stringPaddedToBloomFilter(char const*, unsigned long, DB::BloomFilter&) const ci/tmp/build/./src/Interpreters/ITokenExtractor.h:129:26
#5 0x55a4c63c12bb in DB::MergeTreeIndexAggregatorBloomFilterText::update(DB::Block const&, unsigned long*, unsigned long) ci/tmp/build/./src/Storages/MergeTree/MergeTreeIndexBloomFilterText.cpp:139:34
#6 0x55a4c611fe48 in DB::MergeTreeDataPartWriterOnDisk::calculateAndSerializeSkipIndices(DB::Block const&, std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule>> const&) ci/tmp/build/./src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp:287:42
#7 0x55a4c60fffa8 in DB::MergeTreeDataPartWriterCompact::writeDataBlockPrimaryIndexAndSkipIndices(DB::Block const&, std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule>> const&) ci/tmp/build/./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:253:5
#8 0x55a4c610253c in DB::MergeTreeDataPartWriterCompact::fillDataChecksums(DB::MergeTreeDataPartChecksums&) ci/tmp/build/./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:335:9
#9 0x55a4c610598f in DB::MergeTreeDataPartWriterCompact::fillChecksums(DB::MergeTreeDataPartChecksums&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&) ci/tmp/build/./src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:537:9
#10 0x55a4c681e762 in DB::MergedBlockOutputStream::finalizePartAsync(std::__1::shared_ptr<DB::IMergeTreeDataPart> const&, bool, DB::NamesAndTypesList const*, DB::MergeTreeDataPartChecksums*, DB::ColumnsSubstreams*) ci/tmp/build/./src/Storages/MergeTree/MergedBlockOutputStream.cpp:202:13
#11 0x55a4c6211e03 in DB::MergeTreeDataWriter::writeTempPartImpl(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::SourcePartsSetForPatch, std::__1::shared_ptr<DB::Context const>, unsigned long) ci/tmp/build/./src/Storages/MergeTree/MergeTreeDataWriter.cpp:965:27
#12 0x55a4c62023fa in DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>, std::__1::shared_ptr<DB::Context const>) ci/tmp/build/./src/Storages/MergeTree/MergeTreeDataWriter.cpp:632:12
#13 0x55a4c67d7f6d in DB::MergeTreeSink::consume(DB::Chunk&) ci/tmp/build/./src/Storages/MergeTree/MergeTreeSink.cpp:111:25
#14 0x55a4c8c7a1a8 in DB::SinkToStorage::onConsume(DB::Chunk) ci/tmp/build/./src/Processors/Sinks/SinkToStorage.cpp:10:5
#15 0x55a4c882bd18 in DB::ExceptionKeepingTransform::work()::$_1::operator()() const ci/tmp/build/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:135:51
#16 0x55a4c882bd18 in std::__1::__invoke_result_impl<void, DB::ExceptionKeepingTransform::work()::$_1&>::type std::__1::__invoke[abi:ne210105]<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27
#17 0x55a4c882bd18 in void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5
#18 0x55a4c882bd18 in void std::__1::__invoke_r[abi:ne210105]<void, DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10
#19 0x55a4c882bd18 in void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::ExceptionKeepingTransform::work()::$_1>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12
#20 0x55a4c882b4fc in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
#21 0x55a4c882b4fc in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
#22 0x55a4c882b4fc in DB::runStep(std::__1::function<void ()>, std::__1::shared_ptr<DB::ThreadGroup>&) ci/tmp/build/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:104:9
#23 0x55a4c882a5e1 in DB::ExceptionKeepingTransform::work() ci/tmp/build/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:135:34
#24 0x55a4c7e040ab in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53:26
#25 0x55a4c7e040ab in DB::ExecutionThreadContext::executeTask() ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:102:9
#26 0x55a4c7dcb77d in DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::__1::atomic<bool>*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351:26
#27 0x55a4c7dd1a7b in DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:279:5
#28 0x55a4c7dd1a7b in DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0::operator()() const ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:565:17
#29 0x55a4c7dd1a7b in std::__1::__invoke_result_impl<void, DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>::type std::__1::__invoke[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27
#30 0x55a4c7dd1a7b in void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5
#31 0x55a4c7dd1a7b in void std::__1::__invoke_r[abi:ne210105]<void, DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10
#32 0x55a4c7dd1a7b in void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12
#33 0x55a4a0335845 in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
#34 0x55a4a0335845 in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
#35 0x55a4a0335845 in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:801:17
#36 0x55a4a0348e73 in std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h
#37 0x55a4a0348e73 in decltype(auto) std::__1::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<0ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1380:5
#38 0x55a4a0348e73 in decltype(auto) std::__1::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1384:5
#39 0x55a4a0348e73 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13
#40 0x55a4a032df8a in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
#41 0x55a4a032df8a in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
#42 0x55a4a032df8a in ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:811:17
#43 0x55a4a0341914 in std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h
#44 0x55a4a0341914 in void std::__1::__thread_execute[abi:ne210105]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:159:3
#45 0x55a4a0341914 in void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:168:3
#46 0x7f0a23968ac2 in start_thread nptl/pthread_create.c:442:8
#47 0x7f0a239fa8bf  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
The usage of `ngram_bf` index on a non-UTF-8 data led to an uninitialized memory read, with values that could reside in the resulting index structure. Closes #92576.

### CODE REVIEW

File: src/Functions/ngrams.cpp [hunk 1]
```diff
@@ -105,7 +105,7 @@ class FunctionNgrams : public IFunction
             size_t token_start = 0;
             size_t token_length = 0;
 
-            while (cur < data.size() && extractor.nextInString(data.data(), data.size(), &cur, &token_start, &token_length))
+            while (cur < data.size() && extractor.nextInString(data.data(), data.size(), cur, token_start, token_length))
```
Comment (ahmadov) [inline src/Functions/ngrams.cpp:108]: note: we can use `forEachTokenPadded`  to simplify

**Review by ahmadov — APPROVED** [review]

File: src/Functions/ngrams.cpp (hunk 1 above)
Comment (rschu1ze) [reply src/Functions/ngrams.cpp:108]: Let's make a follow-up PR to keep things in this PR simple @ahmadov

File: src/Interpreters/ITokenExtractor.cpp [hunk 2]
```diff
@@ -232,27 +232,28 @@ std::unique_ptr<ITokenExtractor> TokenizerFactory::createTokenizer(
...
-    for (; code_points < n && *token_start + *token_length < length; ++code_points)
+    for (; code_points < n && token_start + token_length < length; ++code_points)
     {
-        size_t sz = UTF8::seqLength(static_cast<UInt8>(data[*token_start + *token_length]));
-        *token_length += sz;
+        size_t sz = UTF8::seqLength(static_cast<UInt8>(data[token_start + token_length]));
+        token_length += sz;
     }
-    *pos += UTF8::seqLength(static_cast<UInt8>(data[*pos]));
+    token_length = std::min(token_length, length - token_start);
```
Comment (rschu1ze) [inline src/Interpreters/ITokenExtractor.cpp:246]: Add a comment `/// protect against invalid UTF-8`?

**Review by rschu1ze — APPROVED** [review]
