### PR TITLE
Fix moving sum segfault

### LINKED ISSUE #13339: Crash in groupArrayMovingSum
```
SELECT groupArrayMovingSum(10)(('pluspl\0s' = 'minusminus') = ('p\0usp\0usp\0usp\0u\0p\0usp\0usp\0usp\0usp\0usp\0usp\0usp\0usp\0usp\0usp\0usp\0us' = '0.0000001025'))                                                                          
FROM remote('127.0.0.{1,2}', numbers('9223372036854775807' = 1))                                                                                                                                                                               
                                                                                                                                                                                                                                               
→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)                                                                                                                                                                                        
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.292963 [ 55324 ] <Fatal> BaseDaemon: ########################################                                                                                                                  
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.293407 [ 55324 ] <Fatal> BaseDaemon: (version 20.7.1.1, build id: 28CBFDAD79B4CE93) (from thread 55203) (query_id: a71092cd-e605-4141-bbe8-2b850f0f7ee8) Received signal Segmentation fault (11
)                                                                                                                                                                                                                                              
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.293653 [ 55324 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.293867 [ 55324 ] <Fatal> BaseDaemon: Stack trace: 0x1ce2f841 0x2dbb684c 0x1c990d89 0x2f735816 0x2f737452 0x2db43438 0x31064064 0x31063998 0x31063049 0x310f5dd3 0x310f5633 0x2db83f37 0x31b6a99
3 0x3145af28 0x31b84a2b 0x3154d179 0x3154cec1 0x3154cd6d 0x3154cd1d 0x3154cced 0x3154a55e 0x1c31274a 0x1c312605 0x31546d17 0x31547f4a 0x31552c85 0x31552a3d 0x31552a01
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.304419 [ 55324 ] <Fatal> BaseDaemon: 4. /home/alesap/code/cpp/ClickHouse/src/AggregateFunctions/AggregateFunctionGroupArrayMoving.h:162: DB::MovingImpl<char8_t, std::__1::integral_constant<bo
ol, true>, DB::MovingSumData<unsigned long> >::deserialize(char*, DB::ReadBuffer&, DB::Arena*) const @ 0x1ce2f841 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.367281 [ 55324 ] <Fatal> BaseDaemon: 5. /home/alesap/code/cpp/ClickHouse/src/DataTypes/DataTypeAggregateFunction.cpp:145: DB::DataTypeAggregateFunction::deserializeBinaryBulk(DB::IColumn&, DB
::ReadBuffer&, unsigned long, double) const @ 0x2dbb684c in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.370356 [ 55324 ] <Fatal> BaseDaemon: 6. /home/alesap/code/cpp/ClickHouse/src/DataTypes/IDataType.h:195: DB::IDataType::deserializeBinaryBulkWithMultipleStreams(DB::IColumn&, unsigned long, DB
::IDataType::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::IDataType::DeserializeBinaryBulkState>&) const @ 0x1c990d89 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.445660 [ 55324 ] <Fatal> BaseDaemon: 7. /home/alesap/code/cpp/ClickHouse/src/DataStreams/NativeBlockInputStream.cpp:83: DB::NativeBlockInputStream::readData(DB::IDataType const&, DB::IColumn&
, DB::ReadBuffer&, unsigned long, double) @ 0x2f735816 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.520836 [ 55324 ] <Fatal> BaseDaemon: 8. /home/alesap/code/cpp/ClickHouse/src/DataStreams/NativeBlockInputStream.cpp:165: DB::NativeBlockInputStream::readImpl() @ 0x2f737452 in /home/alesap/co
de/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.585424 [ 55324 ] <Fatal> BaseDaemon: 9. /home/alesap/code/cpp/ClickHouse/src/DataStreams/IBlockInputStream.cpp:57: DB::IBlockInputStream::read() @ 0x2db43438 in /home/alesap/code/cpp/BuildCH/
programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.667371 [ 55324 ] <Fatal> BaseDaemon: 10. /home/alesap/code/cpp/ClickHouse/src/Client/Connection.cpp:753: DB::Connection::receiveDataImpl(std::__1::shared_ptr<DB::IBlockInputStream>&) @ 0x3106
4064 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.747594 [ 55324 ] <Fatal> BaseDaemon: 11. /home/alesap/code/cpp/ClickHouse/src/Client/Connection.cpp:734: DB::Connection::receiveData() @ 0x31063998 in /home/alesap/code/cpp/BuildCH/programs/c
lickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.828446 [ 55324 ] <Fatal> BaseDaemon: 12. /home/alesap/code/cpp/ClickHouse/src/Client/Connection.cpp:686: DB::Connection::receivePacket() @ 0x31063049 in /home/alesap/code/cpp/BuildCH/programs
/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.909744 [ 55324 ] <Fatal> BaseDaemon: 13. /home/alesap/code/cpp/ClickHouse/src/Client/MultiplexedConnections.cpp:251: DB::MultiplexedConnections::receivePacketUnlocked() @ 0x310f5dd3 in /home/
alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:21.990306 [ 55324 ] <Fatal> BaseDaemon: 14. /home/alesap/code/cpp/ClickHouse/src/Client/MultiplexedConnections.cpp:145: DB::MultiplexedConnections::receivePacket() @ 0x310f5633 in /home/alesap/c
ode/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.050437 [ 55324 ] <Fatal> BaseDaemon: 15. /home/alesap/code/cpp/ClickHouse/src/DataStreams/RemoteQueryExecutor.cpp:186: DB::RemoteQueryExecutor::read() @ 0x2db83f37 in /home/alesap/code/cpp/Bu
ildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.132961 [ 55324 ] <Fatal> BaseDaemon: 16. /home/alesap/code/cpp/ClickHouse/src/Processors/Sources/RemoteSource.cpp:41: DB::RemoteSource::generate() @ 0x31b6a993 in /home/alesap/code/cpp/BuildC
H/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.212045 [ 55324 ] <Fatal> BaseDaemon: 17. /home/alesap/code/cpp/ClickHouse/src/Processors/ISource.cpp:48: DB::ISource::work() @ 0x3145af28 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.297583 [ 55324 ] <Fatal> BaseDaemon: 18. /home/alesap/code/cpp/ClickHouse/src/Processors/Sources/SourceWithProgress.cpp:36: DB::SourceWithProgress::work() @ 0x31b84a2b in /home/alesap/code/cp
p/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.383871 [ 55324 ] <Fatal> BaseDaemon: 19. /home/alesap/code/cpp/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:78: DB::executeJob(DB::IProcessor*) @ 0x3154d179 in /home/alesap/code/c
pp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.468058 [ 55324 ] <Fatal> BaseDaemon: 20. /home/alesap/code/cpp/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:95: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::opera
tor()() const @ 0x3154cec1 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.556121 [ 55324 ] <Fatal> BaseDaemon: 21. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::
Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x3154cd6d in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.640645 [ 55324 ] <Fatal> BaseDaemon: 22. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineE
xecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x3154cd1d in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.723821 [ 55324 ] <Fatal> BaseDaemon: 23. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::Executing
Graph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x3154cced in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.806220 [ 55324 ] <Fatal> BaseDaemon: 24. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph:
:Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x3154a55e in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.812446 [ 55324 ] <Fatal> BaseDaemon: 25. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x1c31274a
in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.818247 [ 55324 ] <Fatal> BaseDaemon: 26. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x1c312605 in /home/alesap/
code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.900320 [ 55324 ] <Fatal> BaseDaemon: 27. /home/alesap/code/cpp/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:556: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long
, std::__1::atomic<bool>*) @ 0x31546d17 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:22.981144 [ 55324 ] <Fatal> BaseDaemon: 28. /home/alesap/code/cpp/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:472: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned
long) @ 0x31547f4a in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:23.063632 [ 55324 ] <Fatal> BaseDaemon: 29. /home/alesap/code/cpp/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:729: DB::PipelineExecutor::executeImpl(unsigned long)::$_4::operator()(
) const @ 0x31552c85 in /home/alesap/code/cpp/BuildCH/programs/clickhouse
[click.sas.yp-c.yandex.net] 2020.08.04 22:08:23.146719 [ 55324 ] <Fatal> BaseDaemon: 30. /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/type_traits:3525: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long):
:$_4 const&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4 const&) @ 0x31552a3d in /home/alesap/code/cpp/BuildCH/programs/clickhouse
```

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix segfault when function `groupArrayMovingSum` deserializes empty state. Fixes #13339.

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionGroupArrayMoving.h [hunk 1]
```diff
@@ -154,12 +154,13 @@ class MovingImpl final
...
-        value.resize(size, arena);
-        buf.read(reinterpret_cast<char *>(value.data()), size * sizeof(value[0]));
-
-        this->data(place).sum = value.back();
+        if (size > 0)
+        {
+            auto & value = this->data(place).value;
+            value.resize(size, arena);
+            buf.read(reinterpret_cast<char *>(value.data()), size * sizeof(value[0]));
+            this->data(place).sum = value.back();
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionGroupArrayMoving.h:162]: Ok.

**Review by alexey-milovidov — APPROVED** [review]
