### PR TITLE
Recognize more addresses as local

### LINKED ISSUE #23504: Make is_local recognize loopback addresses 127.0.1.1
127.0.1.1 is used in ubuntu / debian by default in /etc/hosts for fqdn.

Due to the fact that address don't literally match the address of network interface isLocal fails to detect that address as local.

See
https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution
https://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in

https://github.com/ClickHouse/ClickHouse/blob/51ba12c2c3106d9277bbc223adfe41fdb3e45439/src/Common/isLocalAddress.cpp#L13

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Recognize IPv4 addresses like `127.0.1.1` as local. This is controversial and closes #23504. Michael Filimonov will test this feature.

### CODE REVIEW

File: src/Common/isLocalAddress.cpp [hunk 1]
```diff
@@ -81,10 +82,45 @@ struct NetworkInterfaces
...
+                && digits_union.digits[1] <= 1
+                && digits_union.digits[2] <= 1
+                && digits_union.digits[3] <= 1)
+            {
+                return true;
+            }
+        }
+        else if (address.family() == Poco::Net::AddressFamily::IPv6)
+        {
+            return true;
```
Comment (azat) [inline src/Common/isLocalAddress.cpp:115]: So now any ipv6 address will be treated as local or I missed something?

Comment (azat) [reply src/Common/isLocalAddress.cpp:115]: Sorry, missed the check above.

**Comment by alexey-milovidov** [comment]
I will add a unit test.

**Review by alesapin — APPROVED** [review]
Quite hacky, but OK. It will solve the problem caused by strange Debian's decision.

**Comment by alesapin** [comment]
Fuzzer:
```
$ grep -a 'Fatal' server.log 
2021.05.21 10:51:17.742899 [ 39 ] {} <Fatal> Application: Child process was terminated by signal 6.
```
??

**Comment by alesapin** [comment]
quota_acl
```
2021-05-21 09:36:42 +quota_by_forwarded_ip
2021-05-21 09:36:42 +quota_by_ip
```
hmm

**Comment by alesapin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/24393

**Comment by alesapin** [comment]
No related failures.

File: src/Common/isLocalAddress.cpp [hunk 2]
```diff
@@ -81,10 +81,41 @@ struct NetworkInterfaces
...
+    /** 127.0.0.1 is treat as local address unconditionally.
+      * ::1 is also treat as local address unconditionally.
+      *
+      * 127.0.0.{2..255} are not treat as local addresses, because they are used in tests
+      *  to emulate distributed queries across localhost.
+      *
+      * But 127.{0,1}.{0,1}.{0,1} are treat as local addresses,
+      *  because they are used in Debian for localhost.
+      */
+    if (address.isLoopback())
```
Comment (jhettler) [inline src/Common/isLocalAddress.cpp:93]: Hi @alesapin,
I am afraid this will work only for IP address 127.0.0.1, related to https://pocoproject.org/docs/Poco.Net.IPAddress.html#24435 where documentation says loopback address is 127.0.0.1, otherwise it will never reach the internal part of if statement. I have this trouble in docker environment and I have 127.0.1.1 in /etc/hosts and unfortunately is_local is still 0.

Comment (filimonov) [reply src/Common/isLocalAddress.cpp:93]: Poco source
https://github.com/ClickHouse-Extras/poco/blob/5994506908028612869fee627d68d8212dfe7c1e/Net/src/IPAddressImpl.cpp#L182

So rather poco docs are not in sync, and not clear what is happening in your case

Comment (filimonov) [reply src/Common/isLocalAddress.cpp:93]: BTW - are you sure you use 21.7?

Comment (jhettler) [reply src/Common/isLocalAddress.cpp:93]: Hi @filimonov, sorry i didn't catch the difference between code and docs in poco. Unfortunately no, I am using 21.6.4 - I have clickhouse running in docker and there is no 21.7 docker image at the moment. Once there is 21.7 I will check if it works. 

At the moment I solved it by setting real IP address of the server in /etc/hosts instead of 127.0.1.1 and it works as expected.
