### PR TITLE
Fix logical error in functions greatest/least

### LINKED ISSUE #29334: Logical error in function `greatest`
**Describe the bug**
```
SELECT * FROM system.data_skipping_indices WHERE (table = 'alter_index_test') AND greatest(greatest(NULL, NULL, greatest(greatest(greatest(-2), '9223372036854775806', sleep(1), NULL), NULL), '102.5', NULL), greatest('-9223372036854775808', NULL), greatest(greatest(NULL), NULL, '0.0000065536', NULL)) AND (database = currentDatabase())
```

```
Cannot capture 4 columns because function greatest has 0 arguments.: while executing 'FUNCTION greatest(greatest(-2) :: 8, '9223372036854775806' :: 9, sleep(1) :: 6, NULL : 7) -> greatest(greatest(-2), '9223372036854775806', sleep(1), NULL) Nullable(Nothing) : 14'. (LOGICAL_ERROR)
```

**How to reproduce**
Always reproduced.

### PR DESCRIPTION
**Pull request by Avogar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix Logical error `Cannot capture columns` in functions greatest/least. Closes https://github.com/ClickHouse/ClickHouse/issues/29334

Detailed description / Documentation draft:
...

### CODE REVIEW

File: tests/queries/0_stateless/01822_short_circuit.sql [hunk 1]
```diff
@@ -153,3 +153,6 @@ select number % 2 and toLowCardinality(number) from numbers(5);
 select number % 2 or toLowCardinality(number) from numbers(5);
 select if(toLowCardinality(number) % 2, number, number + 1) from numbers(10);
 select multiIf(toLowCardinality(number) % 2, number, number + 1) from numbers(10);
+
+select 1 and greatest(number % 2, number % 3) from numbers(10);
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01822_short_circuit.sql:157]: It's more convenient to always add new test files instead of appending to old ones.
\- more easy to separate test failures.

**Review by alexey-milovidov — APPROVED** [review]

**Review by kitaisreal — APPROVED** [review]
