### PR TITLE
Fix for issue #40220

### LINKED ISSUE #40220: Wrong error message from table function `remote`
**Use case**

```
clickhouse-cloud :) INSERT INTO github_events SELECT * FROM remoteSecure('test', default.github_events, import_from_cloud, 'xyz')

INSERT INTO github_events SELECT *
FROM remoteSecure('test', default.github_events, import_from_cloud, 'xyz')

Query id: 0aec7802-2980-4eed-8c5f-fac04b290acf


0 rows in set. Elapsed: 0.042 sec. 

Received exception from server (version 22.7.1):
Code: 42. DB::Exception: Received from host.aws.clickhouse.cloud:9440. DB::Exception: Table function 'remote' requires from 2 to 6 parameters: <addresses pattern or cluster name>, <name of remote database>, <name of remote table> [, username[, password], sharding_key]. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)

clickhouse-cloud :) INSERT INTO github_events SELECT * FROM remoteSecure('test', default, github_events, import_from_cloud, 'xyz')

INSERT INTO github_events SELECT *
FROM remoteSecure('test', default, github_events, import_from_cloud, 'xyz')

Query id: 04afbe19-df67-42af-9271-08470fb7dd04


0 rows in set. Elapsed: 0.042 sec. 

Received exception from server (version 22.7.1):
Code: 42. DB::Exception: Received from host.aws.clickhouse.cloud:9440. DB::Exception: Table function 'remote' requires from 2 to 6 parameters: <addresses pattern or cluster name>, <name of remote database>, <name of remote table> [, username[, password], sharding_key]. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)

clickhouse-cloud :) INSERT INTO github_events SELECT * FROM remoteSecure('test', default, github_events, 'import_from_cloud', 'xyz')
```

This happens when the username is not quoted.

### PR DESCRIPTION
**Pull request by jiyoungyoooo**
improve error message for table function remote

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve error message for table function remote. Closes https://github.com/ClickHouse/ClickHouse/issues/40220.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 48b1a0b44f85034d53245d9dd941929378f10d83 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52959/48b1a0b44f85034d53245d9dd941929378f10d83/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/TableFunctions/TableFunctionRemote.cpp [hunk 1]
```diff
@@ -159,7 +159,7 @@ void TableFunctionRemote::parseArguments(const ASTPtr & ast_function, ContextPtr
             {
                 if (arg_num >= args.size())
                 {
-                    throw Exception(help_message, ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
+                    throw Exception(ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH, "Table name is missing");
```
Comment (kssenii) [inline src/TableFunctions/TableFunctionRemote.cpp:162]:
```suggestion
                    throw Exception(ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH, "Table name was not found in function arguments. {}", help_message);
```

File: src/TableFunctions/TableFunctionRemote.cpp [hunk 2]
```diff
@@ -211,7 +211,16 @@ void TableFunctionRemote::parseArguments(const ASTPtr & ast_function, ContextPtr
...
         if (arg_num < args.size())
-            throw Exception(help_message, ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
+        {
+            if (is_cluster_function)
+            {
+                throw Exception(help_message, ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
+            }
+            else
+            {
+                throw Exception(ErrorCodes::BAD_ARGUMENTS, "user and password should be string literal (in single quotes)");
```
Comment (kssenii) [inline src/TableFunctions/TableFunctionRemote.cpp:221]: I'd rather make it a bit differently. Above in line 206
```
            if (arg_num < args.size() && !sharding_key)
            {
                sharding_key = args[arg_num];
                ++arg_num;
            }
```
can be changed to 
```
            if (arg_num < args.size())
            {
                if (sharding_key)
                    throw Exception(ErrorCodes::BAD_ARGUMENTS, "User name and password should be string literals (in single quotes)");
                sharding_key = args[arg_num];
                ++arg_num;
            }
```
because your fix will make incorrect exception message in case user and password were correctly quoted, but the user has added some extra arguments after `sharding_key` argument (in this case it will be correct to print exception message `throw Exception(help_message, ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);` instead of yours).

File: src/TableFunctions/TableFunctionRemote.cpp (hunk 1 above)
Comment (jiyoungyoooo) [reply src/TableFunctions/TableFunctionRemote.cpp]: Applied. Compile error fixed.

**Review by kssenii — APPROVED** [review]
