### PR TITLE
Fix assertion failure in WindowTransform with large PRECEDING offset

### LINKED ISSUE #75852: src/Processors/Transforms/WindowTransform.cpp:883: void DB::WindowTransform::advanceFrameEndRowsOffset(): Assertion `offset_left >= 0' failed.
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=75149&sha=latest&name_0=PR&name_1=AST+fuzzer+%28debug%29

```
2025.02.10 16:14:42.971878 [ 1842 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.02.10 16:14:42.971917 [ 1842 ] {} <Fatal> BaseDaemon: (version 25.2.1.1585, build id: 835E2A7DD4836182D234630FA93FEDB299B0B306, git hash: 6537912f90b6238918924bebd66b8e5574217059, architecture: x86_64) (from thread 922) Received signal 6
2025.02.10 16:14:42.971933 [ 1842 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.02.10 16:14:42.971940 [ 1842 ] {} <Fatal> BaseDaemon:
2025.02.10 16:14:42.971959 [ 1842 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000d0bc0e8 0x000000000d39ff82 0x00007fc11efe3520 0x00007fc11f0379fd 0x00007fc11efe3476 0x00007fc11efc97f3 0x00007fc11efc971b 0x00007fc11efdae96 0x0000000015011819 0x0000000015012d66 0x00000000150150c9 0x0000000014d411af 0x0000000014d366a5 0x0000000014d3693e 0x0000000014d35247 0x0000000014d34c2f 0x0000000014d4406a 0x000000000d14e0ef 0x000000000d153f20 0x00007fc11f035ac3 0x00007fc11f0c7850
2025.02.10 16:14:42.971972 [ 1842 ] {} <Fatal> BaseDaemon: ########################################
2025.02.10 16:14:42.972083 [ 1842 ] {} <Fatal> BaseDaemon: (version 25.2.1.1585, build id: 835E2A7DD4836182D234630FA93FEDB299B0B306, git hash: 6537912f90b6238918924bebd66b8e5574217059) (from thread 922) (query_id: c6084e2b-0c83-4536-96fe-cbdb7b79be7c) (query: SELECT number, p, count(*) OVER (PARTITION BY p ORDER BY number DESC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND 65537 PRECEDING) FROM (SELECT   5, number, intDiv(number, 7) AS p FROM numbers(71)) ORDER BY p ASC NULLS LAST, number DESC NULLS FIRST SETTINGS max_block_size = 2) Received signal Aborted (6)
2025.02.10 16:14:42.972122 [ 1842 ] {} <Fatal> BaseDaemon:
2025.02.10 16:14:42.972138 [ 1842 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000d0bc0e8 0x000000000d39ff82 0x00007fc11efe3520 0x00007fc11f0379fd 0x00007fc11efe3476 0x00007fc11efc97f3 0x00007fc11efc971b 0x00007fc11efdae96 0x0000000015011819 0x0000000015012d66 0x00000000150150c9 0x0000000014d411af 0x0000000014d366a5 0x0000000014d3693e 0x0000000014d35247 0x0000000014d34c2f 0x0000000014d4406a 0x000000000d14e0ef 0x000000000d153f20 0x00007fc11f035ac3 0x00007fc11f0c7850
2025.02.10 16:14:43.001833 [ 1842 ] {} <Fatal> BaseDaemon: 0.0. inlined from /build/src/Common/StackTrace.cpp:381: StackTrace::tryCapture()
2025.02.10 16:14:43.001882 [ 1842 ] {} <Fatal> BaseDaemon: 0. /build/src/Common/StackTrace.cpp:350: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000d0bc0e8
2025.02.10 16:14:43.018267 [ 1842 ] {} <Fatal> BaseDaemon: 1. /build/src/Common/SignalHandlers.cpp:104: signalHandler(int, siginfo_t*, void*) @ 0x000000000d39ff82
2025.02.10 16:14:43.018313 [ 1842 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007fc11efe3520
2025.02.10 16:14:43.018338 [ 1842 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007fc11f0379fd
2025.02.10 16:14:43.018356 [ 1842 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007fc11efe3476
2025.02.10 16:14:43.018382 [ 1842 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007fc11efc97f3
2025.02.10 16:14:43.018405 [ 1842 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007fc11efc971b
2025.02.10 16:14:43.018422 [ 1842 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007fc11efdae96
2025.02.10 16:14:43.073233 [ 1842 ] {} <Fatal> BaseDaemon: 8. /build/src/Processors/Transforms/WindowTransform.cpp:883: DB::WindowTransform::advanceFrameEndRowsOffset() @ 0x0000000015011819
2025.02.10 16:14:43.128326 [ 1842 ] {} <Fatal> BaseDaemon: 9. /build/src/Processors/Transforms/WindowTransform.cpp:1247: DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x0000000015012d66
2025.02.10 16:14:43.187409 [ 1842 ] {} <Fatal> BaseDaemon: 10. /build/src/Processors/Transforms/WindowTransform.cpp:1497: DB::WindowTransform::work() @ 0x00000000150150c9
2025.02.10 16:14:43.193761 [ 1842 ] {} <Fatal> BaseDaemon: 11.0. inlined from /build/src/Processors/Executors/ExecutionThreadContext.cpp:52: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.02.10 16:14:43.193837 [ 1842 ] {} <Fatal> BaseDaemon: 11. /build/src/Processors/Executors/ExecutionThreadContext.cpp:101: DB::ExecutionThreadContext::executeTask() @ 0x0000000014d411af
2025.02.10 16:14:43.210433 [ 1842 ] {} <Fatal> BaseDaemon: 12. /build/src/Processors/Executors/PipelineExecutor.cpp:291: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d366a5
2025.02.10 16:14:43.226343 [ 1842 ] {} <Fatal> BaseDaemon: 13. /build/src/Processors/Executors/PipelineExecutor.cpp:257: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x0000000014d3693e
2025.02.10 16:14:43.239528 [ 1842 ] {} <Fatal> BaseDaemon: 14. /build/src/Processors/Executors/PipelineExecutor.cpp:456: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000014d35247
2025.02.10 16:14:43.253927 [ 1842 ] {} <Fatal> BaseDaemon: 15. /build/src/Processors/Executors/PipelineExecutor.cpp:128: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000014d34c2f
2025.02.10 16:14:43.266060 [ 1842 ] {} <Fatal> BaseDaemon: 16.0. inlined from /build/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
2025.02.10 16:14:43.266124 [ 1842 ] {} <Fatal> BaseDaemon: 16.1. inlined from /build/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109: operator()
2025.02.10 16:14:43.266149 [ 1842 ] {} <Fatal> BaseDaemon: 16.2. inlined from /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:344: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__invoke[abi:se180100]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
2025.02.10 16:14:43.266171 [ 1842 ] {} <Fatal> BaseDaemon: 16.3. inlined from /build/contrib/llvm-project/libcxx/include/tuple:1424: decltype(auto) std::__apply_tuple_impl[abi:se180100]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
2025.02.10 16:14:43.266194 [ 1842 ] {} <Fatal> BaseDaemon: 16.4. inlined from /build/contrib/llvm-project/libcxx/include/tuple:1428: decltype(auto) std::apply[abi:se180100]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
2025.02.10 16:14:43.266225 [ 1842 ] {} <Fatal> BaseDaemon: 16.5. inlined from /build/src/Common/ThreadPool.h:311: operator()
2025.02.10 16:14:43.266252 [ 1842 ] {} <Fatal> BaseDaemon: 16.6. inlined from /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:344: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__invoke[abi:se180100]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
2025.02.10 16:14:43.266294 [ 1842 ] {} <Fatal> BaseDaemon: 16.7. inlined from /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:419: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se180100]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
2025.02.10 16:14:43.266321 [ 1842 ] {} <Fatal> BaseDaemon: 16.8. inlined from /build/contrib/llvm-project/libcxx/include/__functional/function.h:208: ?
2025.02.10 16:14:43.266343 [ 1842 ] {} <Fatal> BaseDaemon: 16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:608: ? @ 0x0000000014d4406a
2025.02.10 16:14:43.277114 [ 1842 ] {} <Fatal> BaseDaemon: 17.0. inlined from /build/contrib/llvm-project/libcxx/include/__functional/function.h:714: ?
2025.02.10 16:14:43.277169 [ 1842 ] {} <Fatal> BaseDaemon: 17.1. inlined from /build/contrib/llvm-project/libcxx/include/__functional/function.h:981: ?
2025.02.10 16:14:43.277201 [ 1842 ] {} <Fatal> BaseDaemon: 17. /build/src/Common/ThreadPool.cpp:785: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000d14e0ef
2025.02.10 16:14:43.297711 [ 1842 ] {} <Fatal> BaseDaemon: 18.0. inlined from /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:312: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se180100]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.02.10 16:14:43.297784 [ 1842 ] {} <Fatal> BaseDaemon: 18.1. inlined from /build/contrib/llvm-project/libcxx/include/__thread/thread.h:193: void std::__thread_execute[abi:se180100]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.02.10 16:14:43.297808 [ 1842 ] {} <Fatal> BaseDaemon: 18. /build/contrib/llvm-project/libcxx/include/__thread/thread.h:202: void* std::__thread_proxy[abi:se180100]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000d153f20
2025.02.10 16:14:43.297840 [ 1842 ] {} <Fatal> BaseDaemon: 19. ? @ 0x00007fc11f035ac3
2025.02.10 16:14:43.297868 [ 1842 ] {} <Fatal> BaseDaemon: 20. ? @ 0x00007fc11f0c7850
2025.02.10 16:14:43.297892 [ 1842 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2025.02.10 16:14:43.578544 [ 1842 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2025.02.10 16:14:43.578751 [ 1842 ] {} <Fatal> BaseDaemon: Changed settings: max_block_size = 2, max_threads = 8, receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, query_plan_join_swap_table = true, max_bytes_before_external_group_by = 0, max_bytes_ratio_before_external_group_by = 0., max_bytes_before_external_sort = 0, max_bytes_ratio_before_external_sort = 0., max_execution_time = 10., join_algorithm = 'parallel_hash', max_memory_usage = 10000000000, send_logs_level = 'fatal', allow_introspection_functions = true, allow_experimental_analyzer = true
2025.02.10 16:14:50.089406 [ 184 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### How to reproduce

I failed to reproduce on fiddle, but still create an issue in case it is has some race
```
SELECT number, p, count(*) OVER (PARTITION BY p ORDER BY number DESC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND 65537 PRECEDING) FROM (SELECT   5, number, intDiv(number, 7) AS p FROM numbers(71)) ORDER BY p ASC NULLS LAST, number DESC NULLS FIRST SETTINGS max_block_size = 2, max_threads = 8, receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, query_plan_join_swap_table = true, max_bytes_before_external_group_by = 0, max_bytes_ratio_before_external_group_by = 0., max_bytes_before_external_sort = 0, max_bytes_ratio_before_external_sort = 0., max_execution_time = 10., join_algorithm = 'parallel_hash', max_memory_usage = 10000000000, send_logs_level = 'fatal', allow_introspection_functions = true, allow_experimental_analyzer = true

```

### Error message and/or stacktrace

```
2025-02-10 16:07:56	 Thread 6 "QueryPullPipeEx" received signal SIGABRT, Aborted.
2025-02-10 16:07:56	 [Switching to Thread 0x7fbe728a6640 (LWP 922)]
2025-02-10 16:07:56	 0x00007fc11f0379fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:07:56	 #0  0x00007fc11f0379fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:07:56	 No symbol table info available.
2025-02-10 16:07:56	 #1  0x00007fc11efe3476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:07:56	 No symbol table info available.
2025-02-10 16:07:56	 #2  0x00007fc11efc97f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:07:56	 No symbol table info available.
2025-02-10 16:07:56	 #3  0x00007fc11efc971b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:07:56	 No symbol table info available.
2025-02-10 16:07:56	 #4  0x00007fc11efdae96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:07:56	 No symbol table info available.
2025-02-10 16:07:56	 #5  0x0000000015011819 in DB::WindowTransform::advanceFrameEndRowsOffset (this=0x7fbe6ccc0c18) at /build/src/Processors/Transforms/WindowTransform.cpp:883
2025-02-10 16:07:56	         moved_row = @0x7fbe72898bc0: {block = 1, row = 0}
2025-02-10 16:07:56	         offset_left = @0x7fbe72898bd0: -65534
2025-02-10 16:07:56	 #6  0x0000000015012d66 in DB::WindowTransform::appendChunk (this=this@entry=0x7fbe6ccc0c18, chunk=...) at /build/src/Processors/Transforms/WindowTransform.cpp:1247
2025-02-10 16:07:56	 No locals.
2025-02-10 16:07:56	 #7  0x00000000150150c9 in DB::WindowTransform::work (this=0x7fbe6ccc0c18) at /build/src/Processors/Transforms/WindowTransform.cpp:1497
2025-02-10 16:07:56	         first_used_block = <optimized out>
2025-02-10 16:07:56	 #8  0x0000000014d411af in DB::executeJob (node=0x7fbe6f860900, read_progress_callback=0x7fbe6a3a5080) at /build/src/Processors/Executors/ExecutionThreadContext.cpp:52
2025-02-10 16:09:32	         exception = {<Poco::Exception> = {<std::exception> = {_vptr$exception = 0x7fbe6f860948, static capacity = 32, frames = {0x1, 0x1000, 0x0, 0x0, 0x7fbe5cc7d000, 0x1000, 0x72898c01, 0xd05ad76 <operator delete(void*, unsigned long)+86>, 0x8, 0x7fbef7c52868, 0x7fbef7c52790, 0xd05ad76 <operator delete(void*, unsigned long)+86>, 0x7fbef7c52870, 0x0, 0x1, 0x7fbe6f860900, 0x7fbef7c52790, 0x14d3b83b <DB::ExecutingGraph::updateNode(unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, AllocatorWithMemoryTracking<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, AllocatorWithMemoryTracking<DB::ExecutingGraph::Node*> > >&)+3995>, 0x8, 0x100f7c526b8, 0x7fbdf7c52701, 0x7fbe6f860948, 0x1, 0x0, 0x0, 0x0, 0x7fbe6cdb0618, 0x7fbe6cdb0620, 0x56d90a5016, 0x7fbe5cfb2c00, 0x0, 0x14d3705a <DB::PipelineExecutor::spawnThreadsImpl()+154>}, size = 0}, _msg = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__s = {__data_ = "\000\000\000\000\000\000\000\000@j\323i\276\177\000\000 \006\333l\276\177", __padding_ = 0x7fbe72898f0f "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __l = {__data_ = 0x0, __size_ = 140455795976768, __cap_ = 140455846807072, __is_long_ = 0}, __r = {__words = {0, 140455795976768, 140455846807072}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, _pNested = 0x7fbef7c52868, _code = 1921617776}, static enable_job_stack_trace = true, static can_use_thread_frame_pointers = false, static callback = {<std::__1::__function::__maybe_derive_from_unary_function<void(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)>> = {<No data fields>}, __f_ = {__buf_ = {__small = '\000' <repeats 15 times>, __large = 0x0}, __invoker_ = {__call_ = 0xd090b40 <std::__1::__function::__policy_invoker<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)>::__call_empty[abi:se180100](std::__1::__function::__policy_storage const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)>}, __policy_ = 0x1af5d1d0 <std::__1::__function::__policy::__create_empty[abi:se180100]()::__policy>}}, static thread_frame_pointers = {frame_pointers = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, remote = 190, error_index = 140455846807072, message_format_string = {static npos = 18446744073709551615, __data_ = 0x0, __size_ = 373008519190}, message_format_string_args = {__begin_ = 0x7fbe5cfb2c00, __end_ = 0x4, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, 0, false>> = {__value_ = 0x1af4cbbb <clock_gettime+27>}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 1, true>> = {<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, capture_thread_frame_pointers = {__begin_ = 0x0, __end_ = 0x7fbe6cdb0618, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2025-02-10 16:09:32	         is_source = <optimized out>
2025-02-10 16:09:32	         read_progress = <optimized out>
2025-02-10 16:09:32	 #9  DB::ExecutionThreadContext::executeTask (this=0x7fbe5cfb2c00) at /build/src/Processors/Executors/ExecutionThreadContext.cpp:101
2025-02-10 16:09:32	         span = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::OpenTelemetry::SpanHolder*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::OpenTelemetry::SpanHolder>, 1, true>> = {<std::__1::default_delete<DB::OpenTelemetry::SpanHolder>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2025-02-10 16:09:32	         execution_time_watch = {<std::__1::__optional_move_assign_base<Stopwatch, true>> = {<std::__1::__optional_copy_assign_base<Stopwatch, true>> = {<std::__1::__optional_move_base<Stopwatch, true>> = {<std::__1::__optional_copy_base<Stopwatch, true>> = {<std::__1::__optional_storage_base<Stopwatch, false>> = {<std::__1::__optional_destruct_base<Stopwatch, true>> = {{__null_state_ = -114 '\216', __val_ = {start_ns = 373008520334, stop_ns = 0, clock_type = 4, is_running = true}}, __engaged_ = true}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2025-02-10 16:09:32	 #10 0x0000000014d366a5 in DB::PipelineExecutor::executeStepImpl (this=this@entry=0x7fbe6cdb0618, thread_num=thread_num@entry=0, yield_flag=yield_flag@entry=0x0) at /build/src/Processors/Executors/PipelineExecutor.cpp:291
2025-02-10 16:11:44	         processing_time_watch = <optimized out>
2025-02-10 16:11:44	         total_time_watch = {start_ns = 373008054765, stop_ns = 0, clock_type = 4, is_running = true}
2025-02-10 16:11:44	         context = @0x7fbe5cfb2c00: {async_tasks = {c = {static __block_size = <optimized out>, __map_ = {__first_ = 0x0, __begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ExecutingGraph::Node***, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ExecutingGraph::Node**>, 1, true>> = {<std::__1::allocator<DB::ExecutingGraph::Node**>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ExecutingGraph::Node**> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, __start_ = 0, __size_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ExecutingGraph::Node*>, 1, true>> = {<std::__1::allocator<DB::ExecutingGraph::Node*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ExecutingGraph::Node*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, has_async_tasks = {<std::__1::__atomic_base<bool, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<bool>> = {__a_value = false}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, condvar = {__cv_ = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}}, mutex = {__m_ = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, wake_flag = false, node = 0x7fbe6f860900, exception = {__ptr_ = 0x0}, read_progress_callback = 0x7fbe6a3a5080, total_time_ns = 0, execution_time_ns = 275076, processing_time_ns = 165037, wait_time_ns = 0, thread_number = 0, profile_processors = true, trace_processors = false, static max_scheduled_local_tasks = 128, num_scheduled_local_tasks = 65}
2025-02-10 16:11:44	         yield = false
2025-02-10 16:11:44	 #11 0x0000000014d3693e in DB::PipelineExecutor::executeSingleThread (this=0xc1, this@entry=0x7fbe6cdb0618, thread_num=922, thread_num@entry=0) at /build/src/Processors/Executors/PipelineExecutor.cpp:257
2025-02-10 16:11:44	         context = <optimized out>
2025-02-10 16:11:44	 #12 0x0000000014d35247 in DB::PipelineExecutor::executeImpl (this=this@entry=0x7fbe6cdb0618, num_threads=num_threads@entry=1, concurrency_control=<optimized out>) at /build/src/Processors/Executors/PipelineExecutor.cpp:456
2025-02-10 16:11:44	         slot = {__ptr_ = 0x7fbe6f845180, __cntrl_ = 0x7fbfde9ff180}
2025-02-10 16:11:44	         finished_flag = false
2025-02-10 16:11:44	         scope_exit445 = {static is_nullable = <optimized out>, function = {finished_flag = @0x7fbe728991f7, this = 0x7fbe6cdb0618}}
2025-02-10 16:11:44	 #13 0x0000000014d34c2f in DB::PipelineExecutor::execute (this=0x7fbe6cdb0618, num_threads=1, concurrency_control=true) at /build/src/Processors/Executors/PipelineExecutor.cpp:128
2025-02-10 16:11:44	         span = {<DB::OpenTelemetry::Span> = {trace_id = {t = {items = {0, 0}}}, span_id = 0, parent_span_id = 0, operation_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fbe728993a7 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, start_time_us = 0, finish_time_us = 0, kind = DB::OpenTelemetry::SpanKind::INTERNAL, attributes = {<std::__1::vector<DB::Field, AllocatorWithMemoryTracking<DB::Field> >> = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::Field*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<AllocatorWithMemoryTracking<DB::Field>, 1, true>> = {<AllocatorWithMemoryTracking<DB::Field>> = {<No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}}, <No data fields>}
2025-02-10 16:11:44	 #14 0x0000000014d4406a in DB::threadFunction (data=..., thread_group=..., num_threads=1, concurrency_control=true) at /build/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83
2025-02-10 16:11:44	         scope_exit75 = {static is_nullable = false, function = {<No data fields>}}
2025-02-10 16:11:44	 #15 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const (this=0x7fbe72899430) at /build/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109
2025-02-10 16:11:44	 No locals.
2025-02-10 16:11:44	 #16 std::__1::__invoke[abi:se180100]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) (__f=...) at /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:344
2025-02-10 16:11:44	 No locals.
2025-02-10 16:11:44	 #17 _ZNSt3__118__apply_tuple_implB8se180100IRZN2DB28PullingAsyncPipelineExecutor4pullERNS1_5ChunkEmE3$_0RNS_5tupleIJEEETpTnmJEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE (__f=..., __t=...) at /build/contrib/llvm-project/libcxx/include/tuple:1424
2025-02-10 16:11:44	 No locals.
2025-02-10 16:11:44	 #18 std::__1::apply[abi:se180100]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) (__f=..., __t=...) at /build/contrib/llvm-project/libcxx/include/tuple:1428
2025-02-10 16:11:44	 No locals.
2025-02-10 16:11:44	 #19 ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}::operator()() (this=<optimized out>) at /build/src/Common/ThreadPool.h:311
2025-02-10 16:11:59	         scope_exit288 = {static is_nullable = false, function = {<No data fields>}}
2025-02-10 16:11:59	         function = {thread_group = {__ptr_ = 0x7fbda7596f18, __cntrl_ = 0x7fbda7596f00}, this = 0x7fbfe3befbc8}
2025-02-10 16:11:59	         thread_status = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, thread_id = 922, os_thread_priority = 0, performance_counters = {counters = 0x7fbe7ba3b800, counters_holder = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::atomic<unsigned long>*, 0, false>> = {__value_ = 0x7fbe7ba3b800}, <std::__1::__compressed_pair_elem<std::__1::default_delete<std::__1::atomic<unsigned long> []>, 1, true>> = {<std::__1::default_delete<std::__1::atomic<unsigned long> []>> = {<No data fields>}, <No data fields>}, <No data fields>}}, parent = {<std::__1::__atomic_base<ProfileEvents::Counters*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<ProfileEvents::Counters*>> = {__a_value = 0x7fbda7596fd0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, trace_profile_events = false, level = VariableContext::Thread, static num_counters = {t = 826}}, current_performance_counters = 0x7fbe72899460, memory_tracker = {amount = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, peak = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, soft_limit = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, hard_limit = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, profiler_limit = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, rss = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, profiler_step = 0, fault_probability = 0, sample_probability = -1, min_allocation_size_bytes = 0, max_allocation_size_bytes = 0, parent = {<std::__1::__atomic_base<MemoryTracker*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<MemoryTracker*>> = {__a_value = 0x7fbda7596ff0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, metric = {<std::__1::__atomic_base<StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<StrongTypedef<unsigned long, CurrentMetrics::MetricTag> >> = {__a_value = {t = 347}}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, description_ptr = {<std::__1::__atomic_base<char const*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<char const*>> = {__a_value = 0x1594469warning: (Internal error: pc 0x1594469 in read in CU, but not in symtab.)
2025-02-10 16:11:59	 warning: (Error: pc 0x1594469 in address map, but not in symtab.)
2025-02-10 16:12:26	  "Thread"}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, max_wait_time = {<std::__1::__atomic_base<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >> = {__a_value = {__rep_ = 0}}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, overcommit_tracker = {<std::__1::__atomic_base<OvercommitTracker*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<OvercommitTracker*>> = {__a_value = 0x0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, log_peak_memory_usage_in_destructor = true, static USAGE_EVENT_NAME = <optimized out>, static PEAK_USAGE_EVENT_NAME = <optimized out>, level = VariableContext::Thread}, untracked_memory = 81232, untracked_memory_limit = 4194304, progress_in = {read_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 71}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, read_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 568}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_rows_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 71}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_bytes_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, elapsed_ns = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}}, progress_out = {read_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, read_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_rows_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_bytes_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, elapsed_ns = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}}, read_resource_link = {queue = 0x0}, write_resource_link = {queue = 0x0}, thread_group = {__ptr_ = 0x7fbda7596f18, __cntrl_ = 0x7fbda7596f00}, global_context = {__ptr_ = 0x7fc11d8f9800, __cntrl_ = 0x7fc11d616a20}, query_context = {__ptr_ = 0x7fbe88d90000, __cntrl_ = 0x7fbeb6a9bb40}, fatal_error_callback = {<std::__1::__function::__maybe_derive_from_unary_function<void()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "\000\242I\213\276\177\000\000\020\377\276\343\277\177\000", __large = 0x7fbe8b49a200}, __invoker_ = {__call_ = 0x14c957a0 <std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se180100]<std::__1::__function::__default_alloc_func<DB::TCPHandler::runImpl()::$_0, void ()> >(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x1b5e5018 <std::__1::__function::__policy::__choose_policy[abi:se180100]<std::__1::__function::__default_alloc_func<DB::TCPHandler::runImpl()::$_0, void ()> >(std::__1::integral_constant<bool, true>)::__policy>}}, local_data = {profile_queue_ptr = {__ptr_ = 0x7fbe6ccbce38, __cntrl_ = 0x7fbe6ccbce20}, logs_queue_ptr = {__ptr_ = 0x7fbe6f8af818, __cntrl_ = 0x7fbe6f8af800}, client_logs_level = DB::LogsLevel::fatal, query_for_logs = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__s = {__data_ = "\000+\330\367\276\177\000\000\030\001\000\000\000\000\000\000 \001\000\000\000\000", __padding_ = 0x7fbe7289964f "\200x[R\266\373u\211\315X\246\016z\276\177", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __l = {__data_ = 0x7fbef7d82b00 "SELECT number, p, count(*) OVER (PARTITION BY p ORDER BY number DESC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND 65537 PRECEDING) FROM (SELECT   5, number, intDiv(number, 7) AS p FROM numbers(71)"..., __size_ = 280, __cap_ = 288, __is_long_ = 1}, __r = {__words = {140458178652928, 280, 9223372036854776096}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, normalized_query_hash = 14810498573540678520, plan_step_index = {__ptr_ = 0x7fbe7a0ea658, __cntrl_ = 0x7fbe7a0ea640}, pipeline_processor_index = {__ptr_ = 0x7fbe6f911398, __cntrl_ = 0x7fbe6f911380}, query_is_canceled_predicate = {<std::__1::__function::__maybe_derive_from_unary_function<bool()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<bool()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "\030oY\247\275\177\000\000lock_siz", __large = 0x7fbda7596f18}, __invoker_ = {__call_ = 0x12f763e0 <std::__1::__function::__policy_invoker<bool ()>::__call_impl[abi:se180100]<std::__1::__function::__default_alloc_func<DB::ThreadGroup::ThreadGroup(std::__1::shared_ptr<DB::Context const>, std::__1::function<void ()>)::$_0, bool ()> >(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x1b5a60b0 <std::__1::__function::__policy::__choose_policy[abi:se180100]<std::__1::__function::__default_alloc_func<DB::ThreadGroup::ThreadGroup(std::__1::shared_ptr<DB::Context const>, std::__1::function<void ()>)::$_0, bool ()> >(std::__1::integral_constant<bool, true>)::__policy>}}}, performance_counters_finalized = false, query_id_from_query_context = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__s = {__data_ = " =\326\367\276\177\000\000$\000\000\000\000\000\000\000(\000\000\000\000\000", __padding_ = 0x7fbe728996b7 "\200\233\253\274\022\313-\006", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __l = {__data_ = 0x7fbef7d63d20 "c6084e2b-0c83-4536-96fe-cbdb7b79be7c", __size_ = 36, __cap_ = 40, __is_long_ = 1}, __r = {__words = {140458178526496, 36, 9223372036854775848}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, query_start_time = {point = {__d_ = {__rep_ = 1739200076229531}}}, query_profiler_real = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::QueryProfilerReal*, 0, false>> = {__value_ = 0x7fbe7ba29820}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::QueryProfilerReal>, 1, true>> = {<std::__1::default_delete<DB::QueryProfilerReal>> = {<No data fields>}, <No data fields>}, <No data fields>}}, query_profiler_cpu = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::QueryProfilerCPU*, 0, false>> = {__value_ = 0x7fbe7ba29740}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::QueryProfilerCPU>, 1, true>> = {<std::__1::default_delete<DB::QueryProfilerCPU>> = {<No data fields>}, <No data fields>}, <No data fields>}}, last_rusage = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::RUsageCounters*, 0, false>> = {__value_ = 0x7fbf3e3bd630}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::RUsageCounters>, 1, true>> = {<std::__1::default_delete<DB::RUsageCounters>> = {<No data fields>}, <No data fields>}, <No data fields>}}, taskstats = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::TasksStatsCounters*, 0, false>> = {__value_ = 0x7fbe6cce3000}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::TasksStatsCounters>, 1, true>> = {<std::__1::default_delete<DB::TasksStatsCounters>> = {<No data fields>}, <No data fields>}, <No data fields>}}, stopwatch = {start_ns = 374073988529, stop_ns = 0, clock_type = 6, is_running = true}, last_performance_counters_update_time = 0, internal_thread = false, deleter = {<std::__1::__function::__maybe_derive_from_unary_function<void()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "P\224\211r\276\177\000\000\000\000\000\000\000\000\000", __large = 0x7fbe72899450}, __invoker_ = {__call_ = 0x12f76480 <std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se180100]<std::__1::__function::__default_alloc_func<DB::ThreadStatus::attachToGroup(std::__1::shared_ptr<DB::ThreadGroup> const&, bool)::$_0, void ()> >(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x1b5a60e0 <std::__1::__function::__policy::__choose_policy[abi:se180100]<std::__1::__function::__default_alloc_func<DB::ThreadStatus::attachToGroup(std::__1::shared_ptr<DB::ThreadGroup> const&, bool)::$_0, void ()> >(std::__1::integral_constant<bool, true>)::__policy>}}, log = {__ptr_ = 0x7fc11d9a7600, __cntrl_ = 0x0}, check_current_thread_on_destruction = true}
2025-02-10 16:12:26	         arguments = <optimized out>
2025-02-10 16:12:26	 #20 std::__1::__invoke[abi:se180100]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) (__f=...) at /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:344
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #21 std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:se180100]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&) (__args=...) at /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:419
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #22 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()>::operator()[abi:se180100]() (this=<optimized out>) at /build/contrib/llvm-project/libcxx/include/__functional/function.h:208
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #23 std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se180100]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>) at /build/contrib/llvm-project/libcxx/include/__functional/function.h:608
2025-02-10 16:12:26	         __f = <optimized out>
2025-02-10 16:12:26	 #24 0x000000000d14e0ef in std::__1::__function::__policy_func<void ()>::operator()[abi:se180100]() const (this=0x7fbe728997b0) at /build/contrib/llvm-project/libcxx/include/__functional/function.h:714
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #25 std::__1::function<void()>::operator() (this=0x7fbe728997b0) at /build/contrib/llvm-project/libcxx/include/__functional/function.h:981
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #26 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (this=0x7fbef7d2ea60) at /build/src/Common/ThreadPool.cpp:785
2025-02-10 16:12:26	         metric_active_pool_threads = {what = <optimized out>, amount = 1}
2025-02-10 16:12:26	         job_data = {<std::__1::__optional_move_assign_base<JobWithPriority, false>> = {<std::__1::__optional_copy_assign_base<JobWithPriority, false>> = {<std::__1::__optional_move_base<JobWithPriority, false>> = {<std::__1::__optional_copy_base<JobWithPriority, false>> = {<std::__1::__optional_storage_base<JobWithPriority, false>> = {<std::__1::__optional_destruct_base<JobWithPriority, false>> = {{__null_state_ = 0 '\000', __val_ = {job = {<std::__1::__function::__maybe_derive_from_unary_function<void()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "\0001\203o\276\177\000\000\000\000\000\000\000\000\000", __large = 0x7fbe6f833100}, __invoker_ = {__call_ = 0x14d43fa0 <std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se180100]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x1b5e83c8 <std::__1::__function::__policy::__choose_policy[abi:se180100]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::integral_constant<bool, false>)::__policy>}}, priority = {value = 0}, metric_increment = {what = 0x1bb3d1a0 <CurrentMetrics::values+592>, amount = 1}, available_threads_decrement = {atomic_var = {<std::__1::__optional_move_assign_base<std::__1::reference_wrapper<std::__1::atomic<long> >, true>> = {<std::__1::__optional_copy_assign_base<std::__1::reference_wrapper<std::__1::atomic<long> >, true>> = {<std::__1::__optional_move_base<std::__1::reference_wrapper<std::__1::atomic<long> >, true>> = {<std::__1::__optional_copy_base<std::__1::reference_wrapper<std::__1::atomic<long> >, true>> = {<std::__1::__optional_storage_base<std::__1::reference_wrapper<std::__1::atomic<long> >, false>> = {<std::__1::__optional_destruct_base<std::__1::reference_wrapper<std::__1::atomic<long> >, true>> = {{__null_state_ = -56 '\310', __val_ = {...}}, __engaged_ = true}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}}, thread_trace_context = {<DB::OpenTelemetry::TracingContext> = {trace_id = {t = {items = {0, 0}}}, span_id = 0, tracestate = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fbe72899827 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, trace_flags = 0 '\000'}, span_log = {__ptr_ = 0x0, __cntrl_ = 0x0}}, frame_pointers = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, enable_job_stack_trace = true, job_create_time = {start_ns = 373007909515, stop_ns = 0, clock_type = 4, is_running = true}}}, __engaged_ = true}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<false, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<false, true>> = {<No data fields>}, <No data fields>}
2025-02-10 16:12:26	         _allocations_flag_prev_val759 = true
2025-02-10 16:12:26	         scope_exit759 = {static is_nullable = <optimized out>, function = {_allocations_flag_prev_val759 = @0x7fbe7289977e}}
2025-02-10 16:12:26	         thread_trace_context = {root_span = {trace_id = {t = {items = {0, 0}}}, span_id = 0, parent_span_id = 0, operation_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fbe728998ef "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, start_time_us = 0, finish_time_us = 0, kind = DB::OpenTelemetry::SpanKind::INTERNAL, attributes = {<std::__1::vector<DB::Field, AllocatorWithMemoryTracking<DB::Field> >> = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::Field*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<AllocatorWithMemoryTracking<DB::Field>, 1, true>> = {<AllocatorWithMemoryTracking<DB::Field>> = {<No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}}, is_context_owner = true}
2025-02-10 16:12:26	         _allocations_flag_prev_val659 = false
2025-02-10 16:12:26	         scope_exit659 = {static is_nullable = <optimized out>, function = {_allocations_flag_prev_val659 = @0x7fbe7289977f}}
2025-02-10 16:12:26	         exception_from_job = {__ptr_ = 0x0}
2025-02-10 16:12:26	         metric_pool_threads = {what = <optimized out>, amount = 1}
2025-02-10 16:12:26	         job_is_done = <optimized out>
2025-02-10 16:12:26	 #27 0x000000000d153f20 in std::__1::__invoke[abi:se180100]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) (__f=<optimized out>, __a0=<optimized out>) at /build/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:312
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #28 std::__1::__thread_execute[abi:se180100]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (__t=...) at /build/contrib/llvm-project/libcxx/include/__thread/thread.h:193
2025-02-10 16:12:26	 No locals.
2025-02-10 16:12:26	 #29 std::__1::__thread_proxy[abi:se180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=<optimized out>) at /build/contrib/llvm-project/libcxx/include/__thread/thread.h:202
2025-02-10 16:12:26	         __p = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>*, 0, false>> = {__value_ = 0x7fbef7d2ea80}, <std::__1::__compressed_pair_elem<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >, 1, true>> = {<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >> = {<No data fields>}, <No data fields>}, <No data fields>}}
2025-02-10 16:12:26	 #30 0x00007fc11f035ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:12:26	 No symbol table info available.
2025-02-10 16:12:26	 #31 0x00007fc11f0c7850 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2025-02-10 16:12:26	 No symbol table info available.
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
When using a window frame with a large PRECEDING offset (e.g., 65537 PRECEDING) combined with small `max_block_size`, the `advanceFrameEndRowsOffset` and `advanceFrameStartRowsOffset` functions could hit an assertion failure: `assert(offset_left >= 0)`.

The issue occurs because `partition_start` can point to a block that has already been freed (the block cleanup code preserves `prev_frame_start.block` but not explicitly `partition_start.block`). When `moveRowNumber` hits `first_block_number` and can't go further back, `offset_left` remains negative. If `partition_start.block < first_block_number`, the comparison `moved_row <= partition_start` incorrectly returns false, and the assertion fires.

The fix adds an additional check: when moving backwards (PRECEDING) and `offset_left < 0`, we treat this as having reached/passed the partition start and clamp appropriately.

Closes #75852

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix assertion failure in WindowTransform with a large PRECEDING offset. Closes #75852.

### Version info
- Merged into: `26.2.1.302`

### CODE REVIEW

File: tests/queries/0_stateless/03822_window_function_large_preceding_offset.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+SELECT
+    number,
+    p,
+    count(*) OVER (PARTITION BY p ORDER BY number DESC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND 65537 PRECEDING)
+FROM (
+    SELECT number, intDiv(number, 7) AS p
+    FROM numbers(71)
+)
+ORDER BY p ASC NULLS LAST, number DESC NULLS FIRST
+SETTINGS max_block_size = 2;
```
Comment (novikd) [inline tests/queries/0_stateless/03822_window_function_large_preceding_offset.sql:14]: Added test does not reproduce the issue
