### PR TITLE
Query cache: Allow to ignore non-deterministic queries

### LINKED ISSUE #56504: Non-deterministic query throws if query_cache is enabled
**Describe the unexpected behaviour**
With version  23.10.1.1, query cache is not working properly, as it throws for non-deterministic queries, instead of not caching and giving results.

**How to reproduce**
* Which ClickHouse server version to use:  23.10.1.1
* Queries to run that lead to unexpected result: Any query of this type: 

SELECT count() FROM <table> WHERE datetime >= now() - INTERVAL 5 minute

**Expected behavior**
The query finishes correctly and results are not cached.

**Error message and/or stacktrace**
Code: 704. DB::Exception: Received from localhost:9000. DB::Exception: Unable to cache the query result because the query contains a non-deterministic function. Use setting `query_cache_store_results_of_queries_with_nondeterministic_functions = 1` to cache the query result regardless. (CANNOT_USE_QUERY_CACHE_WITH_NONDETERMINISTIC_FUNCTIONS)

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes #56504

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Setting `query_cache_store_results_of_queries_with_nondeterministic_functions` (with values `false` or `true`) was marked obsolete. It was replaced by setting `query_cache_nondeterministic_function_handling`, a three-valued enum that controls how the query cache handles queries with non-deterministic functions: a) throw an exception (default behavior), b) save the non-deterministic query result regardless, or c) ignore, i.e. don't throw an exception and don't cache the result.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ed7b4c67a0cd9cad139573e2feb897700b2e01b8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56519/ed7b4c67a0cd9cad139573e2feb897700b2e01b8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6812878266">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56519/ed7b4c67a0cd9cad139573e2feb897700b2e01b8/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Interpreters/executeQuery.cpp [hunk 1]
```diff
@@ -1100,32 +1100,37 @@ static std::tuple<ASTPtr, BlockIO> executeQueryImpl(
...
-                            std::chrono::system_clock::now() + std::chrono::seconds(settings.query_cache_ttl),
-                            settings.query_cache_compress_entries);
-
-                        const size_t num_query_runs = query_cache->recordQueryRun(key);
-                        if (num_query_runs <= settings.query_cache_min_query_runs)
-                        {
-                            LOG_TRACE(&Poco::Logger::get("QueryCache"), "Skipped insert because the query ran {} times but the minimum required number of query runs to cache the query result is {}", num_query_runs, settings.query_cache_min_query_runs);
-                        }
-                        else
+                        if (!ast_contains_nondeterministic_functions || (ast_contains_nondeterministic_functions && nondeterministic_function_handling == QueryCacheNondeterministicFunctionHandling::Save))
```
Comment (kssenii) [inline src/Interpreters/executeQuery.cpp:1109]: it will be equal to:
```suggestion
                        if (!ast_contains_nondeterministic_functions || nondeterministic_function_handling == QueryCacheNondeterministicFunctionHandling::Save)
```

**Review by kssenii — APPROVED** [review]

File: src/Interpreters/executeQuery.cpp (hunk 1 above)
Comment (rschu1ze) [reply src/Interpreters/executeQuery.cpp:1109]: 136 vs. 204 characters, sounds good!
