### PR TITLE
Fix bug with wrong type in Merge table and PREWHERE

### LINKED ISSUE #43324: AST Fuzzer Logical error: 'Unknown numeric column x of type: DB::ColumnNullable'
**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/43285/b13a8d478bb9c1d1e9f333c26acb6b33a22c6d9b/fuzzer_astfuzzerdebug//report.html

Query from stack trace
```
SELECT 9223372036854775807, * FROM foo_merge WHERE and(((Val = 1024) AND (Id = -2)) AND (Val = 2) AND NULL)) 
```

<details>
<summary><b>StackTrace</b></summary>

```
2022.11.16 16:46:23.592316 [ 149 ] {43bf31da-8ff9-4caa-8f86-687f79b3bf79} <Fatal> : Logical error: 'Unknown numeric column x of type: DB::ColumnNullable'.
2022.11.16 16:46:23.593456 [ 413 ] {} <Fatal> BaseDaemon: ########################################
2022.11.16 16:46:23.593699 [ 413 ] {} <Fatal> BaseDaemon: (version 22.11.1.1, build id: D54B903C62E78E058AEDE418469C273EF6BF7B0F) (from thread 149) (query_id: 43bf31da-8ff9-4caa-8f86-687f79b3bf79) (query: SELECT 9223372036854775807, * FROM foo_merge WHERE and(((Val = 1024) AND (Id = -2)) AND (Val = 2) AND NULL)) Received signal Aborted (6)
2022.11.16 16:46:23.593882 [ 413 ] {} <Fatal> BaseDaemon: 
2022.11.16 16:46:23.594104 [ 413 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fac5e07f00b 0x7fac5e05e859 0x20b4e476 0x20b4e535 0x20b4e5e5 0x27911a0d 0x279107f6 0x2790f716 0x2790e636 0x2790d516 0x2790c3f6 0x2790b316 0x2790a236 0x27909116 0x27907ff6 0x27907956 0x278fe484 0x279363e8 0x1821cbd9 0x1821accd 0x26e28606 0x26e296de 0x26e2a5db 0x278991c8 0x27898bca 0x2a64529d 0x2a622cc9 0x29a771d7 0x29a618e1 0x29a5e1d1 0x29d0811e 0x2945507e 0x294541e8 0x2a5e4b75 0x2a60b0df 0x288f4a11 0x28d7b72a 0x28d776c4 0x29f20a34 0x29f30d45 0x2ea84039
2022.11.16 16:46:23.594370 [ 413 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7fac5e07f00b in ?
2022.11.16 16:46:23.594515 [ 413 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7fac5e05e859 in ?
2022.11.16 16:46:23.763114 [ 413 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x20b4e476 in /workspace/clickhouse
2022.11.16 16:46:23.930348 [ 413 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../src/Common/Exception.cpp:63: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&) @ 0x20b4e535 in /workspace/clickhouse
2022.11.16 16:46:24.082168 [ 413 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0x20b4e5e5 in /workspace/clickhouse
2022.11.16 16:46:24.467946 [ 413 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../src/Functions/FunctionsLogical.cpp:413: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x27911a0d in /workspace/clickhouse
2022.11.16 16:46:24.838026 [ 413 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x279107f6 in /workspace/clickhouse
2022.11.16 16:46:25.211511 [ 413 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x2790f716 in /workspace/clickhouse
2022.11.16 16:46:25.578717 [ 413 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x2790e636 in /workspace/clickhouse
2022.11.16 16:46:25.945696 [ 413 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x2790d516 in /workspace/clickhouse
2022.11.16 16:46:26.315308 [ 413 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x2790c3f6 in /workspace/clickhouse
2022.11.16 16:46:26.678447 [ 413 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, signed char, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x2790b316 in /workspace/clickhouse
2022.11.16 16:46:27.045155 [ 413 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, unsigned long, signed char, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x2790a236 in /workspace/clickhouse
2022.11.16 16:46:27.406274 [ 413 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, unsigned int, unsigned long, signed char, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x27909116 in /workspace/clickhouse
2022.11.16 16:46:27.765472 [ 413 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, unsigned short, unsigned int, unsigned long, signed char, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x27907ff6 in /workspace/clickhouse
2022.11.16 16:46:28.125396 [ 413 ] {} <Fatal> BaseDaemon: 19. /build/build_docker/../src/Functions/FunctionsLogical.cpp:398: void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, char8_t, unsigned short, unsigned int, unsigned long, signed char, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x27907956 in /workspace/clickhouse
2022.11.16 16:46:28.531976 [ 413 ] {} <Fatal> BaseDaemon: 20. /build/build_docker/../src/Functions/FunctionsLogical.cpp:447: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::(anonymous namespace)::basicExecuteImpl<DB::FunctionsLogicalDetail::AndImpl>(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>>, unsigned long) @ 0x278fe484 in /workspace/clickhouse
2022.11.16 16:46:28.863687 [ 413 ] {} <Fatal> BaseDaemon: 21. /build/build_docker/../src/Functions/FunctionsLogical.cpp:628: DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x279363e8 in /workspace/clickhouse
2022.11.16 16:46:29.008385 [ 413 ] {} <Fatal> BaseDaemon: 22. /build/build_docker/../src/Functions/IFunction.h:410: DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x1821cbd9 in /workspace/clickhouse
2022.11.16 16:46:29.149301 [ 413 ] {} <Fatal> BaseDaemon: 23. /build/build_docker/../src/Functions/IFunctionAdaptors.h:26: DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x1821accd in /workspace/clickhouse
2022.11.16 16:46:29.308692 [ 413 ] {} <Fatal> BaseDaemon: 24. /build/build_docker/../src/Functions/IFunction.cpp:246: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x26e28606 in /workspace/clickhouse
2022.11.16 16:46:29.468208 [ 413 ] {} <Fatal> BaseDaemon: 25. /build/build_docker/../src/Functions/IFunction.cpp:302: DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x26e296de in /workspace/clickhouse
2022.11.16 16:46:29.628003 [ 413 ] {} <Fatal> BaseDaemon: 26. /build/build_docker/../src/Functions/IFunction.cpp:372: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x26e2a5db in /workspace/clickhouse
2022.11.16 16:46:31.909327 [ 413 ] {} <Fatal> BaseDaemon: 27. /build/build_docker/../src/Interpreters/ActionsDAG.cpp:457: DB::executeActionForHeader(DB::ActionsDAG::Node const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>>) @ 0x278991c8 in /workspace/clickhouse
2022.11.16 16:46:33.317838 [ 413 ] {} <Fatal> BaseDaemon: 28. /build/build_docker/../src/Interpreters/ActionsDAG.cpp:569: DB::ActionsDAG::updateHeader(DB::Block) const @ 0x27898bca in /workspace/clickhouse
2022.11.16 16:46:33.688306 [ 413 ] {} <Fatal> BaseDaemon: 29. /build/build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:617: DB::MergeTreeBaseSelectProcessor::transformHeader(DB::Block, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x2a64529d in /workspace/clickhouse
2022.11.16 16:46:34.441851 [ 413 ] {} <Fatal> BaseDaemon: 30. /build/build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:91: DB::ReadFromMergeTree::ReadFromMergeTree(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>, DB::MergeTreeData const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::StorageSnapshot>, std::__1::shared_ptr<DB::Context const>, unsigned long, unsigned long, bool, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>, Poco::Logger*, std::__1::shared_ptr<DB::MergeTreeDataSelectAnalysisResult>, bool) @ 0x2a622cc9 in /workspace/clickhouse
2022.11.16 16:46:35.400004 [ 413 ] {} <Fatal> BaseDaemon: 31. /build/build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:714: std::__1::__unique_if<DB::ReadFromMergeTree>::__unique_single std::__1::make_unique[abi:v15003]<DB::ReadFromMergeTree, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, DB::MergeTreeData const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long const&, unsigned long const&, bool&, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>&, Poco::Logger* const&, std::__1::shared_ptr<DB::MergeTreeDataSelectAnalysisResult>&, bool&>(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>&&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, DB::MergeTreeData const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long const&, unsigned long const&, bool&, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>&, Poco::Logger* const&, std::__1::shared_ptr<DB::MergeTreeDataSelectAnalysisResult>&, bool&) @ 0x29a771d7 in /workspace/clickhouse
2022.11.16 16:46:36.245660 [ 413 ] {} <Fatal> BaseDaemon: 32. /build/build_docker/../src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:1372: DB::MergeTreeDataSelectExecutor::readFromParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, unsigned long, unsigned long, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>, std::__1::shared_ptr<DB::MergeTreeDataSelectAnalysisResult>, bool) const @ 0x29a618e1 in /workspace/clickhouse
2022.11.16 16:46:37.043226 [ 413 ] {} <Fatal> BaseDaemon: 33. /build/build_docker/../src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:159: DB::MergeTreeDataSelectExecutor::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, unsigned long, unsigned long, DB::QueryProcessingStage::Enum, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, long>>>>, bool) const @ 0x29a5e1d1 in /workspace/clickhouse
2022.11.16 16:46:37.680799 [ 413 ] {} <Fatal> BaseDaemon: 34. /build/build_docker/../src/Storages/StorageMergeTree.cpp:232: DB::StorageMergeTree::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x29d0811e in /workspace/clickhouse
2022.11.16 16:46:38.330391 [ 413 ] {} <Fatal> BaseDaemon: 35. /build/build_docker/../src/Storages/StorageMerge.cpp:562: DB::ReadFromMerge::createSources(std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, DB::QueryProcessingStage::Enum const&, unsigned long, DB::Block const&, std::__1::vector<DB::ReadFromMerge::AliasData, std::__1::allocator<DB::ReadFromMerge::AliasData>> const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IStorage>, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&, std::__1::shared_ptr<DB::Context>, unsigned long, bool) @ 0x2945507e in /workspace/clickhouse
2022.11.16 16:46:39.006729 [ 413 ] {} <Fatal> BaseDaemon: 36. /build/build_docker/../src/Storages/StorageMerge.cpp:460: DB::ReadFromMerge::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x294541e8 in /workspace/clickhouse
2022.11.16 16:46:39.165940 [ 413 ] {} <Fatal> BaseDaemon: 37. /build/build_docker/../src/Processors/QueryPlan/ISourceStep.cpp:16: DB::ISourceStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder>>, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x2a5e4b75 in /workspace/clickhouse
2022.11.16 16:46:39.423626 [ 413 ] {} <Fatal> BaseDaemon: 38. /build/build_docker/../src/Processors/QueryPlan/QueryPlan.cpp:187: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x2a60b0df in /workspace/clickhouse
2022.11.16 16:46:39.763670 [ 413 ] {} <Fatal> BaseDaemon: 39. /build/build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:374: DB::InterpreterSelectWithUnionQuery::execute() @ 0x288f4a11 in /workspace/clickhouse
2022.11.16 16:46:40.173709 [ 413 ] {} <Fatal> BaseDaemon: 40. /build/build_docker/../src/Interpreters/executeQuery.cpp:677: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x28d7b72a in /workspace/clickhouse
2022.11.16 16:46:40.604922 [ 413 ] {} <Fatal> BaseDaemon: 41. /build/build_docker/../src/Interpreters/executeQuery.cpp:1074: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x28d776c4 in /workspace/clickhouse
2022.11.16 16:46:41.034354 [ 413 ] {} <Fatal> BaseDaemon: 42. /build/build_docker/../src/Server/TCPHandler.cpp:374: DB::TCPHandler::runImpl() @ 0x29f20a34 in /workspace/clickhouse
2022.11.16 16:46:41.501095 [ 413 ] {} <Fatal> BaseDaemon: 43. /build/build_docker/../src/Server/TCPHandler.cpp:1902: DB::TCPHandler::run() @ 0x29f30d45 in /workspace/clickhouse
2022.11.16 16:46:41.611133 [ 413 ] {} <Fatal> BaseDaemon: 44. /build/build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x2ea84039 in /workspace/clickhouse
2022.11.16 16:46:41.611379 [ 413 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

</details>

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug with wrong type in Merge table and PREWHERE, close https://github.com/ClickHouse/ClickHouse/issues/43324

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Storages/StorageMerge.cpp [hunk 1]
```diff
@@ -146,8 +146,40 @@ bool StorageMerge::canMoveConditionsToPrewhere() const
...
+            can_move = false;
+
+        if (!can_move)
+            return;
+
+        for (const auto & column : metadata_ptr->getColumns().getAll())
+        {
+            const auto * src_type = column_types[column.name];
+            if (src_type && !src_type->equals(*column.type))
+                can_move = false;
```
Comment (SmitaRKulkarni) [inline src/Storages/StorageMerge.cpp:178]: we can return `if can_move = false` what do you think?

**Review by SmitaRKulkarni — COMMENTED** [review]
Rest all LGTM

File: src/Storages/StorageMerge.cpp (hunk 1 above)
Comment (vdimir) [inline src/Storages/StorageMerge.cpp:178]:
```suggestion
            if (src_type && !src_type->equals(*column.type))
            {
                can_move = false;
                return;
            }
```

**Review by SmitaRKulkarni — APPROVED** [review]

File: src/Storages/StorageMerge.cpp [hunk 2]
```diff
@@ -146,8 +146,43 @@ bool StorageMerge::canMoveConditionsToPrewhere() const
...
     /// will appear after this check and before calling "read" method, the optimized query may fail.
     /// Since it's quite rare case, we just ignore this possibility.
+    const auto & table_doesnt_support_prewhere = getFirstTable([](const auto & table) { return !table->canMoveConditionsToPrewhere(); });
+    bool can_move = (table_doesnt_support_prewhere == nullptr);
 
-    return getFirstTable([](const auto & table) { return !table->canMoveConditionsToPrewhere(); }) == nullptr;
+    if (!can_move)
+        return false;
+
+    if (!getInMemoryMetadataPtr())
```
Comment (azat) [inline src/Storages/StorageMerge.cpp:155]: Hi @vdimir. Is this at all possible? `setInMemoryMetadata` in `StorageMerge` should be enough, no?

Comment (azat) [reply src/Storages/StorageMerge.cpp:155]: I've removed it here - #46454, it also addresses few other issues with PREWHERE for Merge, and this patch makes it possible to use PREWHERE for columns which types is the same, instead of globally disable PREWHERE
