### PR TITLE
Fix bad tests `share_big_sets`, CC @davenger

### LINKED ISSUE #66907: The test `02581_share_big_sets_between_multiple_mutations_tasks_long.sql` consumes a lot of memory.
Picture from our CI Logs Cluster:

Screenshot_20240723_030220

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes https://github.com/ClickHouse/ClickHouse/issues/66907

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 07f642f1cac5253fda7eaa928ca5e659159b6b16 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66908/07f642f1cac5253fda7eaa928ca5e659159b6b16/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/91693daf599bbaeaed5adb8cba257c176628e2be/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/bd9bfc34a932b732e08860abbe76dac10f9ee46b/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/02581_share_big_sets_between_multiple_mutations_tasks_long.sql [hunk 1]
```diff
@@ -18,12 +18,15 @@ SELECT name FROM system.parts WHERE database=currentDatabase() AND table = '0258
...
+ALTER TABLE 02581_trips UPDATE description='6' WHERE id IN (SELECT (number*10 + 6)::UInt32 FROM numbers(10000000)) SETTINGS mutations_sync=0;
+ALTER TABLE 02581_trips DELETE                 WHERE id IN (SELECT (number*10 + 7)::UInt32 FROM numbers(10000000)) SETTINGS mutations_sync=0;
+ALTER TABLE 02581_trips UPDATE description='8' WHERE id IN (SELECT (number*10 + 8)::UInt32 FROM numbers(10000000)) SETTINGS mutations_sync=0;
 SYSTEM START MERGES 02581_trips;
-DELETE FROM 02581_trips WHERE id IN (SELECT (number*10 + 9)::UInt32 FROM numbers(200000000));
+DELETE FROM 02581_trips                        WHERE id IN (SELECT (number*10 + 9)::UInt32 FROM numbers(10000000));
 SELECT count(), _part from 02581_trips WHERE description = '' GROUP BY _part ORDER BY _part;
 
+SYSTEM FLUSH LOGS;
+SELECT DISTINCT peak_memory_usage < 2000000000 ? 'Ok' : toString(tuple(*)) FROM system.part_log WHERE database = currentDatabase() AND event_date >= yesterday() AND table = '02581_trips' AND event_type = 'MutatePart';
```
Comment (davenger) [inline tests/queries/0_stateless/02581_share_big_sets_between_multiple_mutations_tasks_long.sql:30]: The test is aimed to check that a big set that is built for `where in (...)` condition is not created for each part, but is shared between mutations tasks for different parts that run in parallel. But AFAIU `peak_memory_usage` column only includes memory consumption by a single thread that is mutating one part.

So it seems that the check query should be different. I will think a bit and try to come up with a proper check

Comment (davenger) [reply tests/queries/0_stateless/02581_share_big_sets_between_multiple_mutations_tasks_long.sql]: I've modified the check to look at `read_rows` from `system.part_log` and compare it to the size of big set for each mutated part. It should be `>= set size` for the part that builds the set and `<= set size` for those parts that used shared set instead of building it.

Comment (davenger) [reply tests/queries/0_stateless/02581_share_big_sets_between_multiple_mutations_tasks_long.sql]: The approach with `read_rows` didn't work out with old analyzer.
I changed the check to count log messages like `Created Set with 10000000 entries from 10000000 rows in 0.388989187 sec.` and `Got set from cache in 0.388930505 sec.`
