### PR TITLE
Fix cleanup of patch parts in `ReplicatedMergeTree`

### LINKED ISSUE #85094: 03100_lwu_11_with_mutations is flaky
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=7d993424f332826e03464e8093b06829e0417fbf&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%20parallel%29

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed cleanup of patch parts in `ReplicatedMergeTree`. Previously, the result of a lightweight update may temporarily not be visible on the replica until the merged or mutated part that materializes the patch parts is downloaded from another replica.

Fixes #85094.

### CODE REVIEW

**Review by serxa — APPROVED** [review]

File: tests/queries/0_stateless/03100_lwu_40_cleanup_race.sh [hunk 1]
```diff
@@ -0,0 +1,94 @@
+#!/usr/bin/env bash
```
Comment (vitlibar) [inline tests/queries/0_stateless/03100_lwu_40_cleanup_race.sh:1]: This new test seems flaky ([see](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHJlcG9ydF91cmwKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjUtMDgtMDEnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDMxMDBfbHd1XzQwX2NsZWFudXBfcmFjZSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBvcmRlciBieSBjaGVja19zdGFydF90aW1l))
