### PR TITLE
Fix aws region issue in delta-kernel

### LINKED ISSUE #79914: allow_experimental_delta_kernel_rs S3 REGION
### Company or project name

_No response_

### Describe the issue

Hello,

If I understand well, delta kernel is mandatory in order to enjoy partition pruning on delta tables.

However, I don't find any documentation to use this setting properly on S3, being stucked on the following errors :

1. With S3 url

`CREATE TABLE table_ext_partition
ENGINE=DeltaLake('https://mybucket.s3.eu-west-1.amazonaws.com/prefix/','mykey','mysecret')
SETTINGS allow_experimental_delta_kernel_rs=1`

> Code: 742. DB::Exception: Received DeltaLake kernel error ReqwestError: Error interacting with object store: Generic S3 error: Client error with status 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; a non-empty region must be provided in the credential.</Message><RequestId>63NBCZCPMWPGKDQ7</RequestId><HostId>a7uetPyf14E1KGH3om5gob0eU+KrJ+TlUVvIFYN1r3HN5YFORT6K0ASurKoc4roocpDaBxzIPUE=</HostId></Error> (in snapshot). (DELTA_KERNEL_ERROR) (version 25.4.2.31 (official build))

While the region is in the URL ...

2. With S3 uri

`CREATE TABLE table_ext_partition
ENGINE=DeltaLake('s3://mybucket/prefix/','mykey','mysecret')
SETTINGS allow_experimental_delta_kernel_rs=1`

> Code: 742. DB::Exception: Received DeltaLake kernel error ReqwestError: Error interacting with object store: Generic S3 error: Error after 10 retries in 1.85370045s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://s3..amazonaws.com/bucket/prefix/_delta_log/_last_checkpoint) (in snapshot). (DELTA_KERNEL_ERROR) (version 25.4.2.31 (official build))

The region doesn't appear in the URL, While I put it in the config.xml and in the docker environment

By the way, it's working properly without the setting, but no partition pruning on the table of course ...

Any wrong usage from my side ?
Implementation bug ?

Thanks in advance for your help

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix region error in delta-kernel. Fixes https://github.com/ClickHouse/ClickHouse/issues/79914.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by kssenii** [comment]
> Stateless tests 

`03221_insert_timeout_overflow_mode` -- not related to changes

File: src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp [hunk 1]
```diff
@@ -171,11 +173,15 @@ DeltaLake::KernelHelperPtr getKernelHelper(
             const auto & s3_credentials = s3_client->getCredentials();
             const auto & url = s3_conf->getURL();
 
+            auto region = s3_client->getRegion();
+            if (region.empty() || region == Aws::Region::AWS_GLOBAL)
+                region = s3_client->getRegionForBucket(url.bucket, /* force_detect */true);
```
Comment (tuanpach) [inline src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp:178]: Do we need to check if `s3_client->getRegionForBucket` returns an empty?

**Comment by tuanpach** [comment]
Very minor thing, can you put a more descriptive commit message?

File: src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp (hunk 1 above)
Comment (kssenii) [reply src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp:178]: There is `force_detect = true` set in the method, so it can be empty in case we fail to resolve the bucket, then we try to execute without it - therefore I added this check https://github.com/ClickHouse/ClickHouse/pull/81353/files#diff-c7f05ab786c84bd2142143561b572b5a7bb69aa7ef18ffef8c302369fc0eff35R85

Comment (tuanpach) [reply src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp:178]: If `region` is `region == Aws::Region::AWS_GLOBAL` before, and `s3_client->getRegionForBucket` returns an empty string, then `region` value changes from `Aws::Region::AWS_GLOBAL` to empty. Will there be a problem?

Comment (kssenii) [reply src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp:178]: > then region value changes from Aws::Region::AWS_GLOBAL to empty

There is no such region as global, so an empty string is better to allow delta kernel to manage it on its own.

**Review by tuanpach — APPROVED** [review]
