### PR TITLE
fix LDAP in case of many roles on user

### LINKED ISSUE #42276: Not AD authorization because many groups in LDAP memberOf container
**Problem:** 
Some AD users can't log in, they get the error:
`Authentification failed: password is incorrect or there is no user with such name`

Clickhouse version 22.3.2.1

**There is an error in Clickhouse logs:**
`<Error> Access(user directories): from: 10.11.12.13, user: AD_USERNAME: Authentification failed: Code: 532. DB::Exception: Size limit exceeded. (LDAP_ERROR)`

This error occurs for AD users who have many groups in the **memberOf** LDAP container.

**I checked the number of groups for 4 accounts:**

AD_USERNAME_1 - 107 groups - ERROR Authentification failed
AD_USERNAME_2 - 120 groups - ERROR Authentification failed
AD_USERNAME_3 - 54   groups - OK
AD_USERNAME_4 - 38   groups - OK

**I checked the search groups through the Ldapsearch program:**

Ldapsearch gave all 107 groups for the account without errors:
`ldapsearch -H "ldaps://hostname:636" -D 'CN=AD_USERNAME_1,OU=Users,DC=company,DC=corp.DC=net' -b 'DC=company,DC=corp.DC=net' '(&(objectClass=group)(member=CN=AD_USERNAME_1,OU=Groups,DC=company,DC=corp.DC=net))'`

**Probable cause of the error:** 
Clickhouse receives a list of groups which mapping from AD and cannot process a large string/array.

### PR DESCRIPTION
**Pull request by Enmk**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increased the default value of search_limit to 256, and added LDAP server config option to change that to an arbitrary value. Closes: #42276

### CODE REVIEW

File: src/Access/ExternalAuthenticators.cpp [hunk 1]
```diff
@@ -184,6 +187,17 @@ void parseLDAPServer(LDAPClient::Params & params, const Poco::Util::AbstractConf
     }
     else
         params.port = (params.enable_tls == LDAPClient::Params::TLSEnable::YES ? 636 : 389);
+
+    if (has_search_limit)
+    {
+        const auto search_limit = config.getUInt(ldap_server_config + ".search_limit");
+        // Arbitrary large number.
+        // Previously default value was 100, but in practice one client reported to have 120 roles for a user.
+        if (search_limit >= 2048)
```
Comment (traceon) [inline src/Access/ExternalAuthenticators.cpp:196]: `search_limit = 0` would mean no limit. So you probably want to check against that too.

However, I don't think there is any real value in introducing another limit on a manually set limit, only possibility of future problems, similar to the one we are fixing here. I thought `100` is plenty...

File: src/Access/LDAPClient.cpp [hunk 2]
```diff
@@ -26,30 +26,30 @@ namespace ErrorCodes
...
-void LDAPClient::SearchParams::combineHash(std::size_t & seed) const
+void LDAPClient::SearchParams::updateHash(SipHash & hash) const
 {
-    boost::hash_combine(seed, base_dn);
-    boost::hash_combine(seed, static_cast<int>(scope));
-    boost::hash_combine(seed, search_filter);
-    boost::hash_combine(seed, attribute);
+    hash.update(base_dn);
+    hash.update(static_cast<int>(scope));
+    hash.update(search_filter);
```
Comment (alexey-milovidov) [inline src/Access/LDAPClient.cpp:33]: This is wrong, as it can return identical hashes for
('a', 'bc')
and
('ab', 'c')

String length should be mixed as well.

File: src/Common/SipHash.h [hunk 3]
```diff
@@ -182,6 +182,14 @@ class SipHash
         finalize();
         return v0 ^ v1 ^ v2 ^ v3;
     }
+
+    UInt128 get128()
+    {
+        finalize();
+        UInt128 res;
+        get128(res);
```
Comment (alexey-milovidov) [inline src/Common/SipHash.h:190]: Calling `finalize` a second time is wrong.

Comment (alexey-milovidov) [reply src/Common/SipHash.h:190]: Better to avoid modifying this file at all.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/Access/ExternalAuthenticators.cpp (hunk 1 above)
Comment (Enmk) [reply src/Access/ExternalAuthenticators.cpp:196]: BTW, why do you think that having no limit (i.e. `search_limit = 0`) is not a viable option?

Comment (traceon) [reply src/Access/ExternalAuthenticators.cpp]: I just followed your logic as I understood it. If no more than 2048 entries are allowed, even if the server is attempted to be configured to allow more, then unlimited number of entries should also not be allowed.

However, as I said, this additional limit is strange, and I would allow both 0 and >2048 limit to be configured by the administrator.

File: src/Access/LDAPClient.cpp (hunk 2 above)
Comment (Enmk) [reply src/Access/LDAPClient.cpp]: fixed

File: src/Access/LDAPClient.cpp [hunk 4]
```diff
@@ -26,30 +26,30 @@ namespace ErrorCodes
...
 {
-    boost::hash_combine(seed, host);
-    boost::hash_combine(seed, port);
-    boost::hash_combine(seed, bind_dn);
-    boost::hash_combine(seed, user);
-    boost::hash_combine(seed, password);
+    hash.update(host);
+    hash.update(port);
+    hash.update(bind_dn);
+    hash.update(user);
```
[the remark this answers is not in the document]
Comment (Enmk) [reply src/Access/LDAPClient.cpp]: fixed as well

File: src/Access/ExternalAuthenticators.cpp (hunk 1 above)
Comment (Enmk) [reply src/Access/ExternalAuthenticators.cpp]: Removed those checks altogether, whatever integer is set in config is pushed to `params.search_limit`.

**Comment by Enmk** [comment]
There was some weird issue with this PR being reported unmereable by GitHub even after merging master into topic branch several times.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> fatal: unable to access 'https://github.com/ClickHouse/sysroot.git/': Failed to connect to github.com port 443: Connection timed out

GitHub downtime.

**Comment by alexey-milovidov** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/42461/0cfbf30b89f3884865d53bfae599a2eb85b08a9f/stress_test__ubsan_/bc_check_error_messages.txt

https://s3.amazonaws.com/clickhouse-test-reports/42461/0cfbf30b89f3884865d53bfae599a2eb85b08a9f/stress_test__tsan_/bc_check_error_messages.txt

**Comment by alexey-milovidov** [comment]
@lavasser I expect it in the next release 22.12 in December.
