### PR TITLE
Handle signed numeric literals in normalizeQuery

### LINKED ISSUE #57919: `normalizeQuery` and negative numeric literals
**Describe the unexpected behaviour**

... aren't normalized properly:
```
SELECT normalizeQuery('SELECT 1111, 222, -333, 444, -555, -666')

┌─normalizeQuery('SELECT 1111, 222, -333, 444, -555, -666')─┐
│ SELECT ?.., -?.., -?, -?                                  │
└───────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by aiven-sal**
This solution is non-ideal, but it's difficult to achieve
better results using only the Lexer.

Close https://github.com/ClickHouse/ClickHouse/issues/57919

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improved handling of signed numeric literals in normalizeQuery

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit b32149379f7c65c79aa7bfc77dacfcc2623b9d45 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58710/b32149379f7c65c79aa7bfc77dacfcc2623b9d45/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7487367298/job/20392675667">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58710/b32149379f7c65c79aa7bfc77dacfcc2623b9d45/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: tests/queries/0_stateless/01451_normalize_query.sql [hunk 1]
```diff
@@ -23,4 +23,15 @@ SELECT normalizeQuery('SELECT 1, ''xyz11''');
...
+SELECT normalizeQuery('-1, -2, 3');
+SELECT normalizeQuery('1 - 2, 3, 4');
+SELECT normalizeQuery('f(-2, 3)');
+SELECT normalizeQuery('[-1, 2, 3]');
+SELECT normalizeQuery('1 + 2');
+SELECT normalizeQuery('1, +2, 3');
+SELECT normalizeQuery('-1, +2, 3');
+SELECT normalizeQuery('1 + 2, 3, 4');
+SELECT normalizeQuery('f(+2, 3)');
+SELECT normalizeQuery('[+1, 2, 3]');
```
Comment (yariks5s) [inline tests/queries/0_stateless/01451_normalize_query.sql:37]: Can you please also add tests with addition/subtraction somewhere in the middle of the sequence and the end?

**Review by yariks5s — CHANGES_REQUESTED** [review]

**Review by yariks5s — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @aiven-sal @yariks5s — while reviewing this PR I found the following:

- **Bug (P2):** `normalizeQueryToPODArray` silently drops unary `+`/`-` before non-literal tokens after a comma — https://github.com/ClickHouse/ClickHouse/issues/103681

Happy to discuss — close anything that's wrong or already addressed.
