### PR TITLE
domainRFC support ipv6(square brackets) and fix #53179

### LINKED ISSUE #53179: domain() returns empty string for IPv6 and port combination
**How to reproduce**
```
SELECT domain('[2001:db8::1]:80')
FORMAT CSV

                                                                                                                                                                                                                          
""
```

**Expected behavior**
```
SELECT domain('[2001:db8::1]:80')
FORMAT CSV

                                                                                                                                                                                                                          
"2001:db8::1"
```

This should be similar to IPv4  addresses with port numbers. This works as expected on the current version.
```
SELECT domain('1.1.1.1:80')
FORMAT CSV

                                                                                                                                                                                                                          
"1.1.1.1"
```

The behavior should not be different as long as `[]` is used according to [rfc5952 section-6](https://datatracker.ietf.org/doc/html/rfc5952#section-6).

### PR DESCRIPTION
**Pull request by Chen768959**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
domainRFC support ipv6(IP literal within square brackets)

### Documentation entry for user-facing changes
fix #53179
[[RFC3513](https://datatracker.ietf.org/doc/html/rfc3513)] or later, is distinguished by enclosing the IP literal
 within square brackets ("[" and "]").
So our domainRFC (RFC 3986) perhaps should support this.

### CODE REVIEW

File: src/Functions/URL/domain.h [hunk 1]
```diff
@@ -116,6 +125,13 @@ exloop: if ((scheme_end - pos) > 2 && *pos == ':' && *(pos + 1) == '/' && *(pos
             /// registered).
             has_sub_delims = true;
             continue;
+        case ']':
+            if (has_open_bracket)
+            {
+                has_end_bracket = true;
+                goto done;
+            }
+            FMT_FALLTHROUGH;
```
Comment (vdimir) [inline src/Functions/URL/domain.h:134]:
```suggestion
            [[fallthrough]];
```

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 3e325b174dc5506bc211d2dab281af3fc7b8fb65 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53506/3e325b174dc5506bc211d2dab281af3fc7b8fb65/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Functions/URL/domain.h [hunk 2]
```diff
@@ -139,6 +154,8 @@ exloop: if ((scheme_end - pos) > 2 && *pos == ':' && *(pos + 1) == '/' && *(pos
         return std::string_view{};
     if (!has_at_symbol)
         pos = colon_pos ? colon_pos : pos;
+    if (has_open_bracket && has_end_bracket)
```
Comment (vdimir) [inline src/Functions/URL/domain.h:157]: Shouldn't we check something like `has_open_bracket && !has_end_bracket` as well?

File: tests/queries/0_stateless/02845_domain_rfc_support_ipv6.sql [hunk 3]
```diff
@@ -0,0 +1,5 @@
+SELECT domainRFC('[2001:db8::1]:80') FORMAT CSV;
+SELECT domainRFC('[::200]:80') FORMAT CSV;
```
Comment (vdimir) [inline tests/queries/0_stateless/02845_domain_rfc_support_ipv6.sql:2]: Consider adding cases with errors, e.g. with open and not closed bracket, several brackets, empty string within brackets and similar that comes to your mind.

Comment (Chen768959) [reply tests/queries/0_stateless/02845_domain_rfc_support_ipv6.sql:2]: ok

File: src/Functions/URL/domain.h (hunk 2 above)
Comment (Chen768959) [reply src/Functions/URL/domain.h:157]: It is unnecessary. like `has_open_bracket && !has_end_bracket`, due to the presence of `has_open_bracket`,`colon_pos` will always nullptr, the condition` if (has_at_symbol || colon_pos == nullptr) `will always be false, and `dot_pos` will also always be nullptr. When checking and returning the host in `checkAndReturnHost`, it will return an empty string.
I will enhance the test scenarios to cover this case.

Comment (vdimir) [reply src/Functions/URL/domain.h]: @Chen768959 could you please comment on that?

Comment (Chen768959) [reply src/Functions/URL/domain.h]: @vdimir Sure, if `has_open_bracket` (and `!has_end_bracket`),
then `dot_pos` will always be nullptr
(the `logic dot_pos = pos;` for `case : '.'` will never be executed),
so `checkAndReturnHost` will also return `std::string_view{}`. 
So there's no need to check `has_open_bracket && !has_end_bracket`. In this case, it will only return `std::string_view{}`.

**Comment by Chen768959** [comment]
@vdimir I have completed all the modifications, and I believe this pull request is now ready for review. If it's convenient for you, could you please review it again? Thank you. (Regarding the stress test check issue, it doesn't seem to be caused by my code. Should I continue updating the branch to address these issues?)"

**Review by vdimir — APPROVED** [review]
