### PR TITLE
Fix `01782_field_oom (arm_asan, targeted)` flakiness

### LINKED ISSUE #91997: `01782_field_oom (arm_asan, targeted)` is flaky
During CI testing of the changed introduced by https://github.com/ClickHouse/ClickHouse/pull/91568 I started having issues with test `01782_field_oom (arm_asan, targeted)`  -- it was failing with error: `Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.`

Here are some references:

[Stateless tests (arm_asan, targeted)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=b6bfe6ccaa4f7c70fbddc9493f131da9d06a47db&name_0=PR&name_1=Stateless+tests+%28arm_asan%2C+targeted%29) [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMTc4Ml9maWVsZF9vb20nCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdTdGF0ZWxlc3MgdGVzdHMgKGFybV9hc2FuLCB0YXJnZXRlZCknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwKSBPUiBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDApCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

The test was falling with the same error only in https://github.com/ClickHouse/ClickHouse/pull/91568 and in https://github.com/ClickHouse/ClickHouse/pull/90374. 

Why I concluded that it is flaky: I reverted all the changes made by me, leaving only some cosmetic ones to run CI, and the test still failed ([reference to commit](https://github.com/ClickHouse/ClickHouse/pull/91568/commits/b6bfe6ccaa4f7c70fbddc9493f131da9d06a47db) and [CI](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=b6bfe6ccaa4f7c70fbddc9493f131da9d06a47db&name_0=PR)). Also the test was not consistent in its failures -- once the test did not fail, but then I reran the job with this test, and it failed. 

For the last 360 days (since 11.12.25) it was tested in `(arm_asan, targeted)` in only `4` prs, and failed in two of them without any direct relation to the code changed.

### PR DESCRIPTION
**Pull request by rienath**
Closes https://github.com/ClickHouse/ClickHouse/issues/91997. The test runs too long with thread fuzzer, causing client-side timeouts. There are three options:

1. Make `sumMap` faster
2. Reduce `max_memory_usage` to trigger OOM sooner
3. Add `no-flaky-check` to skip tests that use thread fuzzer

For option 1, I created https://github.com/ClickHouse/ClickHouse/issues/92093. However, the optimisation goal there is to eliminate the slow `Field`, which is exactly what this test is designed to trigger OOM in. Option 3 is last resort as we want to preserve this test in flaky checks and stateless targeted job. I verified that OOM still occurs in the intended location (`Field` allocation) with limit of 200MB and went with option 2. 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: tests/queries/0_stateless/01782_field_oom.sql [hunk 1]
```diff
@@ -1,2 +1,4 @@
+-- Tags: no-flaky-check
+-- no-flaky-check: https://github.com/ClickHouse/ClickHouse/issues/91997
```
Comment (Avogar) [inline tests/queries/0_stateless/01782_field_oom.sql]: After reading the PR description I thought you desided to decrease `max_memory_usage` for now, no?

Comment (rienath) [reply tests/queries/0_stateless/01782_field_oom.sql]: Thanks for noting @Avogar, forgot to push the change

**Review by Avogar — APPROVED** [review]

**Comment by rienath** [comment]
[Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92158&sha=f6093c9e2942a06d84a0567dc24028544b29dc8e&name_0=PR&name_1=Stateless+tests+%28amd_binary%2C+old+analyzer%2C+s3+storage%2C+DatabaseReplicated%2C+parallel%29)
* https://github.com/ClickHouse/ClickHouse/issues/91545

[Stateless tests (arm_binary, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92158&sha=f6093c9e2942a06d84a0567dc24028544b29dc8e&name_0=PR&name_1=Stateless+tests+%28arm_binary%2C+parallel%29)
* Fixed in https://github.com/ClickHouse/ClickHouse/pull/92146
