### PR TITLE
[RFC] Fix LOGICAL_ERROR for Log with nested types w/o columns in the SELECT clause

### LINKED ISSUE #21059: Logical error: no information about file (part of nested column) in StorageLog
https://clickhouse-test-reports.s3.yandex.net/20599/0a62f95bbe380abe8d8846ef9690b8a18c6a762b/fuzzer_debug/report.html#fail1

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix LOGICAL_ERROR for Log with nested types w/o columns in the SELECT clause

Detailed description / Documentation draft:
Found with fuzzer [1]:

<details>

    2021.04.04 10:25:46.762596 [ 135 ] {4b6b5de3-d242-4267-910a-76b235467356} <Fatal> : Logical error: 'Logical error: no information about file column%2Ename.size0 in StorageLog'.
    ...
    2021.04.04 10:25:46.763563 [ 44 ] {} <Trace> BaseDaemon: Received signal 6
    2021.04.04 10:25:46.765884 [ 165 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
    2021.04.04 10:25:46.901540 [ 165 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:51: DB::handle_error_code() @ 0x11cc4f16 in /workspace/clickhouse
    2021.04.04 10:25:47.030755 [ 165 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:58: DB::Exception::Exception() @ 0x11cc5025 in /workspace/clickhouse
    2021.04.04 10:25:47.617201 [ 165 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Storages/StorageLog.cpp:183: DB::LogSource::readData()

</details>

  [1]: https://clickhouse-test-reports.s3.yandex.net/22583/69296876005c0fa171c755f8b224e4d58192c402/fuzzer_debug/report.html#fail1

The problem here is that there is no column%2Ename.size0 there is
column.size0 instead, and it seems that reading sizeX file is not enough
in other places, so just filter them out in
ExpressionActions::getSmallestColumn() (fallback method for storages w/o
getColumnSizes() implemented)

Fixes: #21059

### CODE REVIEW

**Review by CurtizJ — APPROVED** [review]
Ok. The main problem is that there are generated non-existing subcolumn's names. I tried to fix it in #21208. But this fix is good as a workaround.

**Comment by CurtizJ** [comment]
Fail of `01475_read_subcolumns` is suspicious, but it's related to unstable behaviour of tests, that use query log.

1. ```<Error> void DB::SystemLog<DB::QueryLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::QueryLogElement]: Code: 60, e.displayText() = DB::Exception: Table test_zgush1.`.inner_id.3c9f3082-4850-447c-87cc-9096e2871f98` (f680c78e-73e1-4b1f-a871-9186c211a2b5) doesn't exist```.
2. `<Error> executeQuery: Code: 159, e.displayText() = DB::Exception: Code: 159, e.displayText() = DB::Exception: Timeout exceeded (60 s) while flushing system log 'DB::QueryLog'`.

**Comment by azat** [comment]
>[Stress test (address) Server failed to start](https://clickhouse-test-reports.s3.yandex.net/22654/42d858b7e5843be490c8a6ebe5b17bbd3da975ed/stress_test_(address).html#fail1)

#22592

File: tests/queries/0_stateless/01800_log_nested.sql [hunk 1]
```diff
@@ -0,0 +1,20 @@
+-- TinyTinyLog
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01800_log_nested.sql:1]: @azat Sorry, what is the point in

TinyTinyLog and StripeStripeLog?

Comment (azat) [reply tests/queries/0_stateless/01800_log_nested.sql:1]: If you are asking about typo, that just a typo.
If the question about "what's the point in testing TinyLog and StripeLog" then then answer is "just in case", have you found some issues with this?

Comment (alexey-milovidov) [reply tests/queries/0_stateless/01800_log_nested.sql:1]: Yes, I'm asking about duplication, why it is named **Tiny** Tiny Log, is there any meaning in that.
Looks like there isn't. Could you please send a PR that fixes this typo?

Comment (alexey-milovidov) [reply tests/queries/0_stateless/01800_log_nested.sql:1]: @CurtizJ You've missed "quite important" issue in review :)

Comment (azat) [reply tests/queries/0_stateless/01800_log_nested.sql:1]: >Could you please send a PR that fixes this typo?

Sure, will put it into the queue and submit with other tests fixes.
