### PR TITLE
Fix skip_unavailable_shards in case of unavailable hosts

### LINKED ISSUE #48728: AGAIN skip_unavailable_shards=1 makes 6 tries if a shard is unavailable
It is happening again.
22.8 and 23.3. are affected.
```
SELECT *
FROM cluster('test_unavailable_shard', system.one)
SETTINGS skip_unavailable_shards = 1, send_logs_level = 'trace'

Query id: d5a5dc35-c7b0-4688-80e9-94423e98ab9b

2023.04.12 19:03:04.669543 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Debug> executeQuery: (from [::1]:45680) select * from cluster('test_unavailable_shard', system.one) settings skip_unavailable_shards=1, send_logs_level='trace' (stage: Complete)
2023.04.12 19:03:04.688746 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> ContextAccess (default): Access granted: REMOTE ON *.*
2023.04.12 19:03:04.689149 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2023.04.12 19:03:04.689184 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.04.12 19:03:04.689230 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> InterpreterSelectQuery: Complete -> Complete
2023.04.12 19:03:04.689632 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> Connection (localhost:1): Connecting. Database: (not specified). User: default
┌─dummy─┐
│     0 │
└───────┘
2023.04.12 19:03:04.732904 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Warning> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (localhost:1). (NETWORK_ERROR) (version 23.3.1.2823 (official build))
2023.04.12 19:03:04.732980 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> Connection (localhost:1): Connecting. Database: (not specified). User: default
2023.04.12 19:03:04.775978 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Warning> HedgedConnectionsFactory: Connection failed at try №2, reason: Code: 210. DB::NetException: Connection refused (localhost:1). (NETWORK_ERROR) (version 23.3.1.2823 (official build))
2023.04.12 19:03:04.776054 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> Connection (localhost:1): Connecting. Database: (not specified). User: default
2023.04.12 19:03:04.824794 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Warning> HedgedConnectionsFactory: Connection failed at try №3, reason: Code: 210. DB::NetException: Connection refused (localhost:1). (NETWORK_ERROR) (version 23.3.1.2823 (official build))
2023.04.12 19:03:04.824941 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> Connection (localhost:1): Connecting. Database: (not specified). User: default
2023.04.12 19:03:04.885624 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Warning> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (localhost:1). (NETWORK_ERROR) (version 23.3.1.2823 (official build))
2023.04.12 19:03:04.885753 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> Connection (localhost:1): Connecting. Database: (not specified). User: default
2023.04.12 19:03:04.944493 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Warning> HedgedConnectionsFactory: Connection failed at try №2, reason: Code: 210. DB::NetException: Connection refused (localhost:1). (NETWORK_ERROR) (version 23.3.1.2823 (official build))
2023.04.12 19:03:04.944582 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Trace> Connection (localhost:1): Connecting. Database: (not specified). User: default
2023.04.12 19:03:04.995784 [ 18373 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Warning> HedgedConnectionsFactory: Connection failed at try №3, reason: Code: 210. DB::NetException: Connection refused (localhost:1). (NETWORK_ERROR) (version 23.3.1.2823 (official build))
2023.04.12 19:03:04.996346 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Debug> executeQuery: Read 1 rows, 1.00 B in 0.326853 sec., 3.059479337806292 rows/sec., 3.06 B/sec.
2023.04.12 19:03:04.996466 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Debug> MemoryTracker: Peak memory usage (for query): 431.31 KiB.
2023.04.12 19:03:04.996477 [ 28138 ] {d5a5dc35-c7b0-4688-80e9-94423e98ab9b} <Debug> TCPHandler: Processed in 0.327207039 sec.
```
The old issue https://github.com/ClickHouse/ClickHouse/issues/26511
The old fix https://github.com/ClickHouse/ClickHouse/pull/26658

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix skip_unavailable_shards in case of unavailable hosts

In #26658 only one excessive connect had been removed, but due to RemoteQueryExecutor will execute query again in read(), there is one more, fix this by correctly mark connection in sendQuery()

But note, that there still will be excessive connections due to separate connections for obtaining structure.

Follow-up for: #26658
Fixes: #48728 (cc @SaltTan @den-crane )

### CODE REVIEW

File: src/QueryPipeline/RemoteQueryExecutor.cpp [hunk 1]
```diff
@@ -216,7 +216,14 @@ void RemoteQueryExecutor::sendQuery(ClientInfo::QueryKind query_kind)
 
     const auto & settings = context->getSettingsRef();
     if (settings.skip_unavailable_shards && 0 == connections->size())
+    {
+        std::lock_guard guard(was_cancelled_mutex);
+        was_cancelled = true;
+        finished = true;
+        sent_query = true;
```
Comment (alexey-milovidov) [inline src/QueryPipeline/RemoteQueryExecutor.cpp:223]:
```suggestion
        /// To avoid sending the query again in the `read` method.
        sent_query = true;
```
