### PR TITLE
Make SHOW CREATE TABLE and DESCRIBE TABLE consistent with TEMPORARY tables

### LINKED ISSUE #14004: SHOW CREATE TABLE and DESCRIBE TABLE are inconsistent with respect to TEMPORARY tables
**Use case**
```
milovidov-desktop :) CREATE TABLE t (hello String) ENGINE = StripeLog

CREATE TABLE t
(
    `hello` String
)
ENGINE = StripeLog

Ok.

0 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) CREATE TEMPORARY TABLE t (world UInt64)

CREATE TEMPORARY TABLE t
(
    `world` UInt64
)

Ok.

0 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SHOW CREATE TABLE t

SHOW CREATE TABLE t

┌─statement────────────────────────────────────────────────────┐
│ CREATE TABLE default.t
(
    `hello` String
)
ENGINE = StripeLog │
└──────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) DESCRIBE TABLE t

DESCRIBE TABLE t

┌─name──┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ world │ UInt64 │              │                    │         │                  │                │
└───────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SHOW CREATE TEMPORARY TABLE t

SHOW CREATE TEMPORARY TABLE t

┌─statement───────────────────────────────────────────────────┐
│ CREATE TEMPORARY TABLE t
(
    `world` UInt64
)
ENGINE = Memory │
└─────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) DESCRIBE TEMPORARY TABLE t

Syntax error: failed at position 26 ('t'):

DESCRIBE TEMPORARY TABLE t

Expected one of: SAMPLE, INTO OUTFILE, SETTINGS, FORMAT, FINAL
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
`SHOW CREATE TABLE t` and `DESCRIBE TABLE t` were inconsistent when both a permanent and a temporary table with the same name existed:
- `SHOW CREATE TABLE t` showed the permanent table (used `ResolveOrdinary`)
- `DESCRIBE TABLE t` showed the temporary table (used `ResolveAll`)

Additionally, `DESCRIBE TEMPORARY TABLE t` was a syntax error while `SHOW CREATE TEMPORARY TABLE t` worked.

This PR fixes both issues:
1. `SHOW CREATE TABLE t` now uses `ResolveAll`, preferring the temporary table when no database is qualified — matching `DESCRIBE TABLE` behavior.
2. `DESCRIBE TEMPORARY TABLE t` is now valid syntax.

Closes https://github.com/ClickHouse/ClickHouse/issues/14004

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
`SHOW CREATE TABLE t` now prefers the temporary table when both a permanent and a temporary table named `t` exist and no database is specified, matching the existing behavior of `DESCRIBE TABLE`. Additionally, `DESCRIBE TEMPORARY TABLE` syntax is now supported.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.5.1.82`

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The Stress test (arm_msan) failure is fixed by https://github.com/ClickHouse/ClickHouse/pull/101239, which should be merged first. After it is merged, please update the branch to include the fix.

**Comment by alexey-milovidov** [comment]
The flaky check failure is fixed in https://github.com/ClickHouse/ClickHouse/pull/102148, let's update the branch.

**Review by alexey-milovidov — COMMENTED** [review]
Excellent. Fantastic!

File: tests/queries/0_stateless/04064_describe_show_create_temporary_table.sql [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+-- when no database is specified.
+SELECT 'SHOW CREATE TABLE (no database qualifier) should show temporary table:';
+SHOW CREATE TABLE t;
+
+SELECT 'DESCRIBE TABLE (no database qualifier) should show temporary table:';
+DESCRIBE TABLE t;
+
+-- DESCRIBE TEMPORARY TABLE should work (was a syntax error before the fix).
+SELECT 'DESCRIBE TEMPORARY TABLE:';
+DESCRIBE TEMPORARY TABLE t;
```
Comment (PedroTadim) [inline tests/queries/0_stateless/04064_describe_show_create_temporary_table.sql:21]: @groeneai  Can you add tests for other commands such as CHECK, OPTIMIZE, and ALTER? We should keep the scoping precedence consistent across every command.
