### PR TITLE
Fix filter pushdown for Parquet and maybe StorageMerge

### LINKED ISSUE #53536: Make KeyCondition usable outside *MergeTree when analyzer is enabled
If I'm reading the code correctly:
 * when analyzer is enabled, `SelectQueryInfo::filter_asts` doesn't have sets, and is probably missing some casts,
 * so, KeyCondition shouldn't use it,
 * instead it should use `SelectQueryInfo::filter_actions_dag`,
 * which is assigned only in ReadFromMergeTree::applyFilters().

So, any code using KeyCondition without a merge tree won't work. Currently that's just StorageHive, which uses KeyCondition to skip files based on their min/max statistics. (I didn't test if it's actually broken with analyzer, so maybe I'm misreading the code and it actually works.) And https://github.com/ClickHouse/ClickHouse/pull/52951 added KeyCondition to Parquet reader (to skip row groups), and I'm not sure how to make it work with analyzer.

What's the intended way for this to work? Should `filter_actions_dag` be built by some non-merge-tree code, before IStorage::read() calls? Or should it be built lazily by whoever needs it first? Should everything work completely differently (e.g. non-merge-tree filter pushdowns shouldn't use KeyCondition?)?

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed Parquet filter pushdown not working with Analyzer.

Situation:
```
/// Analyzer generates unique ColumnIdentifiers like __table1.__partition_id in filter nodes,
/// while key analysis still requires unqualified column names.
```
MergeTree had code to specifically correct for that, but other storages didn't, for some reason. So filter pushdown wasn't working for Parquet and probably ORC and maybe Merge.

Most of the PR is one find-replace. Non-mechanical changes are in `ReadFromMergeTree.cpp`, `SelectQueryInfo.{h,cpp}`, `SourceStepWithFilter.cpp`, and `02841_parquet_filter_pushdown.sql`

Closes https://github.com/ClickHouse/ClickHouse/issues/53536

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit c288dea397fffc9d7336bb1d86601020b5104862 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63642/c288dea397fffc9d7336bb1d86601020b5104862/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

File: tests/queries/0_stateless/02841_parquet_filter_pushdown.sql [hunk 1]
```diff
@@ -8,10 +8,6 @@ set optimize_or_like_chain = 0;
 set max_block_size = 100000;
 set max_insert_threads = 1;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02841_parquet_filter_pushdown.sql:10]: See also `orc_filter_pushdown`

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by al13n321** [comment]
The test failures about `system.zookeeper` are clearly related, but I couldn't reproduce them locally so far. Maybe it needs fast-test-like build with reduced dependencies? Maybe something's different in server config? Maybe fast test passes some important arguments to clickhouse-test?

**Comment by al13n321** [comment]
> Maybe it needs fast-test-like build with reduced dependencies?

Didn't help.

> Maybe fast test passes some important arguments to clickhouse-test?

Didn't help.

> Maybe something's different in server config?

I tried to use tests/config/install.sh to create configs similar to CI, but getting it to work seems hopeless, I ran into a few different errors, the configs seem to be missing things, and it would take a while to follow the code and configs to figure out how exactly CI sets everything up to try to reproduce.

Is there a way to get CI to deploy everything, then pause and let me SSH to it?

**Comment by al13n321** [comment]
In https://github.com/ClickHouse/ClickHouse/pull/58061 is another example where the server takes very different code paths in CI vs locally.

**Comment by al13n321** [comment]
(Ok, reproduced the CI setup by copying the commands from the log in CI (thanks to whoever put a `set +x` there!), found the dumb bug in my code.)
