### PR TITLE
Fix crash in a single-node cluster when reading from Iceberg in split-by-buckets mode

### LINKED ISSUE #90913: Iceberg bucket cluster_table_function_split_granularity out of bounds
### Describe the bug

Easy to reproduce.

### How to reproduce

Create the table in Spark with [spark.py](https://github.com/user-attachments/files/23777754/spark.py). Then, in ClickHouse run:
```sql
CREATE TABLE t0 ENGINE = IcebergLocal(local, path = '/var/lib/clickhouse/user_files/lakehouses/t0/test/t0', format = 'Parquet');
SELECT c0 FROM t0 SETTINGS cluster_table_function_split_granularity = 'bucket';
/*
May require running the SELECT query many times; it seems to be a race condition
assertion !empty() failed: deque::front called on an empty deque
*/
```

### Error message and/or stacktrace

Stack trace of a few threads:
```
contrib/llvm-project/libcxx/include/deque:1553: libc++ Hardening assertion !empty() failed: deque::front called on an empty deque
contrib/llvm-project/libcxx/include/deque:1553: libc++ Hardening assertion !empty() failed: deque::front called on an empty deque
contrib/llvm-project/libcxx/include/deque:1553: libc++ Hardening assertion !empty() failed: deque::front called on an empty deque
contrib/llvm-project/libcxx/include/deque:2296: libc++ Hardening assertion !empty() failed: deque::pop_front called on an empty deque
contrib/llvm-project/libcxx/include/deque:1553: libc++ Hardening assertion !empty() failed: deque::front called on an empty deque
contrib/llvm-project/libcxx/include/deque:1553: libc++ Hardening assertion !empty() failed: deque::front called on an empty deque
2025.11.26 18:12:02.481619 [ 2999197 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.11.26 18:12:02.481748 [ 2999197 ] {} <Fatal> BaseDaemon: (version 25.12.1.179 (official build), build id: 67BDC34BCDDA3E6B2FB28EFAA4ACD6AB7F0D8AC8, git hash: 8b2f7f5bf14b87dfa15ce35255a521d67d1837ea, architecture: x86_64) (from thread 2999929) Received signal 6
2025.11.26 18:12:02.481756 [ 2999197 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.11.26 18:12:02.481758 [ 2999197 ] {} <Fatal> BaseDaemon: 
2025.11.26 18:12:02.481774 [ 2999197 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000720c392a5fee 0x0000720c39245e2e 0x0000720c39228888 0x000057f01fa5871d 0x000057f00f9d8589 0x000057f00fa4dbc2 0x000057f00fa4c1a4 0x000057f00fa4c62a 0x000057f0150ed465 0x000057f0150ed142 0x000057f015108930 0x000057f0150fb458 0x000057f0150fba69 0x000057f0150fcb81 0x000057f00b8271f6 0x000057f00b82d5a6 0x000057f00b824632 0x000057f00b82b140 0x0000720c392a3d64 0x0000720c393373bc
2025.11.26 18:12:02.481776 [ 2999197 ] {} <Fatal> BaseDaemon: ########################################
2025.11.26 18:12:02.481897 [ 2999197 ] {} <Fatal> BaseDaemon: (version 25.12.1.179 (official build), build id: 67BDC34BCDDA3E6B2FB28EFAA4ACD6AB7F0D8AC8, git hash: 8b2f7f5bf14b87dfa15ce35255a521d67d1837ea) (from thread 2999929) (query_id: 48898311-2cbe-4de0-b1d0-344763c097a5) (query: SELECT c0 FROM t0;) Received signal Aborted (6)
2025.11.26 18:12:02.481919 [ 2999197 ] {} <Fatal> BaseDaemon: 
2025.11.26 18:12:02.481964 [ 2999197 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000720c392a5fee 0x0000720c39245e2e 0x0000720c39228888 0x000057f01fa5871d 0x000057f00f9d8589 0x000057f00fa4dbc2 0x000057f00fa4c1a4 0x000057f00fa4c62a 0x000057f0150ed465 0x000057f0150ed142 0x000057f015108930 0x000057f0150fb458 0x000057f0150fba69 0x000057f0150fcb81 0x000057f00b8271f6 0x000057f00b82d5a6 0x000057f00b824632 0x000057f00b82b140 0x0000720c392a3d64 0x0000720c393373bc
2025.11.26 18:12:02.482056 [ 2999197 ] {} <Fatal> BaseDaemon: 3. __pthread_kill @ 0x00000000000a5fee
2025.11.26 18:12:02.482089 [ 2999197 ] {} <Fatal> BaseDaemon: 4. raise @ 0x0000000000045e2e
2025.11.26 18:12:02.482116 [ 2999197 ] {} <Fatal> BaseDaemon: 5. __GI_abort @ 0x0000000000028888
2025.11.26 18:12:02.487038 [ 2999197 ] {} <Fatal> BaseDaemon: 6. contrib/llvm-project/libcxx/src/verbose_abort.cpp:62: ? @ 0x0000000029fcc71d
2025.11.26 18:12:02.503505 [ 2999197 ] {} <Fatal> BaseDaemon: 7.0. inlined from contrib/llvm-project/libcxx/include/deque:1553: std::deque<std::shared_ptr<DB::ObjectInfo>, std::allocator<std::shared_ptr<DB::ObjectInfo>>>::front()
2025.11.26 18:12:02.503533 [ 2999197 ] {} <Fatal> BaseDaemon: 7.1. inlined from contrib/llvm-project/libcxx/include/queue:381: std::queue<std::shared_ptr<DB::ObjectInfo>, std::deque<std::shared_ptr<DB::ObjectInfo>, std::allocator<std::shared_ptr<DB::ObjectInfo>>>>::front[abi:se210105]()
2025.11.26 18:12:02.503551 [ 2999197 ] {} <Fatal> BaseDaemon: 7. src/Storages/ObjectStorage/IObjectIterator.cpp:130: DB::ObjectIteratorSplitByBuckets::next(unsigned long) @ 0x0000000019f4c589
2025.11.26 18:12:02.543383 [ 2999197 ] {} <Fatal> BaseDaemon: 8. src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:482: DB::StorageObjectStorageSource::createReader(unsigned long, std::shared_ptr<DB::IObjectIterator> const&, std::shared_ptr<DB::StorageObjectStorageConfiguration> const&, std::shared_ptr<DB::IObjectStorage> const&, DB::ReadFromFormatInfo&, std::optional<DB::FormatSettings> const&, std::shared_ptr<DB::Context const> const&, DB::SchemaCache*, std::shared_ptr<Poco::Logger> const&, unsigned long, std::shared_ptr<DB::FormatParserSharedResources>, std::shared_ptr<DB::FormatFilterInfo>, bool) @ 0x0000000019fc1bc2
2025.11.26 18:12:02.587199 [ 2999197 ] {} <Fatal> BaseDaemon: 9.0. inlined from src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:446: DB::StorageObjectStorageSource::createReader()
2025.11.26 18:12:02.587232 [ 2999197 ] {} <Fatal> BaseDaemon: 9. src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:282: DB::StorageObjectStorageSource::lazyInitialize() @ 0x0000000019fc01a4
2025.11.26 18:12:02.631251 [ 2999197 ] {} <Fatal> BaseDaemon: 10. src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:290: DB::StorageObjectStorageSource::generate() @ 0x0000000019fc062a
2025.11.26 18:12:02.639791 [ 2999197 ] {} <Fatal> BaseDaemon: 11. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000001f661465
2025.11.26 18:12:02.647137 [ 2999197 ] {} <Fatal> BaseDaemon: 12. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001f661142
2025.11.26 18:12:02.651316 [ 2999197 ] {} <Fatal> BaseDaemon: 13.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.11.26 18:12:02.651339 [ 2999197 ] {} <Fatal> BaseDaemon: 13. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001f67c930
2025.11.26 18:12:02.665726 [ 2999197 ] {} <Fatal> BaseDaemon: 14. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f66f458
2025.11.26 18:12:02.679275 [ 2999197 ] {} <Fatal> BaseDaemon: 15. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001f66fa69
2025.11.26 18:12:02.695234 [ 2999197 ] {} <Fatal> BaseDaemon: 16.0. inlined from src/Processors/Executors/PipelineExecutor.cpp:565: operator()
2025.11.26 18:12:02.695269 [ 2999197 ] {} <Fatal> BaseDaemon: 16.1. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:249: decltype(std::declval<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:se210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.11.26 18:12:02.695291 [ 2999197 ] {} <Fatal> BaseDaemon: 16.2. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.11.26 18:12:02.695307 [ 2999197 ] {} <Fatal> BaseDaemon: 16.3. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: void std::__invoke_r[abi:se210105]<void, DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.11.26 18:12:02.695319 [ 2999197 ] {} <Fatal> BaseDaemon: 16. contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000001f670b81
2025.11.26 18:12:02.705324 [ 2999197 ] {} <Fatal> BaseDaemon: 17.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
2025.11.26 18:12:02.705346 [ 2999197 ] {} <Fatal> BaseDaemon: 17.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
2025.11.26 18:12:02.705358 [ 2999197 ] {} <Fatal> BaseDaemon: 17. src/Common/ThreadPool.cpp:801: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000015d9b1f6
2025.11.26 18:12:02.716210 [ 2999197 ] {} <Fatal> BaseDaemon: 18.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:se210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
2025.11.26 18:12:02.716248 [ 2999197 ] {} <Fatal> BaseDaemon: 18.1. inlined from contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:se210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
2025.11.26 18:12:02.716284 [ 2999197 ] {} <Fatal> BaseDaemon: 18.2. inlined from contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:se210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
2025.11.26 18:12:02.716315 [ 2999197 ] {} <Fatal> BaseDaemon: 18. src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000015da15a6
2025.11.26 18:12:02.725428 [ 2999197 ] {} <Fatal> BaseDaemon: 19.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
2025.11.26 18:12:02.725460 [ 2999197 ] {} <Fatal> BaseDaemon: 19.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
2025.11.26 18:12:02.725492 [ 2999197 ] {} <Fatal> BaseDaemon: 19. src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000015d98632
2025.11.26 18:12:02.743420 [ 2999197 ] {} <Fatal> BaseDaemon: 20.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.11.26 18:12:02.743456 [ 2999197 ] {} <Fatal> BaseDaemon: 20.1. inlined from contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:se210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.11.26 18:12:02.743473 [ 2999197 ] {} <Fatal> BaseDaemon: 20. contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:se210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000015d9f140
2025.11.26 18:12:02.743517 [ 2999197 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00000000000a3d64
2025.11.26 18:12:02.743547 [ 2999197 ] {} <Fatal> BaseDaemon: 22. __GI___clone3 @ 0x00000000001373bc
2025.11.26 18:12:02.970208 [ 2999197 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: EE142DAC37E71F5794509074A7731D11)
2025.11.26 18:12:02.970366 [ 2999197 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.11.26 18:12:02.970565 [ 2999197 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, enable_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, use_skip_indexes = true, use_skip_indexes_on_data_read = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, optimize_use_projections = true, optimize_use_projection_filtering = true, enable_lightweight_update = true, use_query_condition_cache = false, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, query_plan_optimize_lazy_materialization = true, query_plan_max_limit_for_lazy_materialization = 0, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, cluster_for_parallel_replicas = 'cluster0', parallel_replicas_for_non_replicated_merge_tree = true, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, cluster_table_function_split_granularity = 'bucket', allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_qbit_type = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_live_view = true, allow_experimental_shared_set_join = true, allow_experimental_object_type = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash in a single-node cluster when reading from Iceberg in split-by-buckets mode. This closes https://github.com/ClickHouse/ClickHouse/issues/90913#issue-3668583963

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/ObjectStorage/IObjectIterator.cpp [hunk 1]
```diff
@@ -127,6 +127,8 @@ ObjectInfoPtr ObjectIteratorSplitByBuckets::next(size_t id)
         }
     }
 
+    if (pending_objects_info.empty())
+        return {};
```
Comment (divanik) [inline src/Storages/ObjectStorage/IObjectIterator.cpp]: Why can we have pending_objecs_info empty here? 
I have two answers: splitter is null and buffer is empty.
1) I think, that we should fallback and process the whole file if splitter is null, shouldn't we.
2) If buffer is empty, I think we can use query_settings.skip_empty_files to understand if it is ok for us.
Why shouldn't we take a next file/batch for the iteration?

File: tests/integration/test_storage_iceberg_with_spark/test_cluster_table_function.py [hunk 2]
```diff
@@ -294,3 +294,33 @@ def get_buffers_count(func):
...
     if buffers_count_with_splitted_tasks != 0:
         assert buffers_count_with_splitted_tasks > buffers_count_default
+
+@pytest.mark.parametrize("format_version", ["1", "2"])
+@pytest.mark.parametrize("storage_type", ["s3", "azure", "local"])
+def test_bucket_split_single_node(started_cluster_iceberg_with_spark, format_version, storage_type):
+    instance = started_cluster_iceberg_with_spark.instances["node1"]
+    spark = started_cluster_iceberg_with_spark.spark_session
+    TABLE_NAME = (
+        "test_partition_by_"
```
Comment (divanik) [inline tests/integration/test_storage_iceberg_with_spark/test_cluster_table_function.py]: Wrong name

File: tests/integration/test_storage_iceberg_with_spark/test_cluster_table_function.py [hunk 3]
```diff
@@ -294,3 +294,33 @@ def get_buffers_count(func):
     buffers_count_default = get_buffers_count(lambda: instance.query(f"SELECT * FROM {table_function_expr_s3_cluster} ORDER BY ALL SETTINGS input_format_parquet_use_native_reader_v3={input_format_parquet_use_native_reader_v3}, cluster_table_function_buckets_batch_size={cluster_table_function_buckets_batch_size}").strip().split())
     if buffers_count_with_splitted_tasks != 0:
         assert buffers_count_with_splitted_tasks > buffers_count_default
+
+@pytest.mark.parametrize("format_version", ["1", "2"])
```
Comment (divanik) [inline tests/integration/test_storage_iceberg_with_spark/test_cluster_table_function.py]: Could you, please, explain in which place the code you added is triggered by this test?

File: src/Storages/ObjectStorage/IObjectIterator.cpp (hunk 1 above)
Comment (scanhex12) [reply src/Storages/ObjectStorage/IObjectIterator.cpp]: > Why can we have pending_objecs_info empty here?
because parquet can be empty.

both versions are wrong 
> 1. we will get segfault earlier if splitter is null. 
> 2. buffer can't be empty because we have parquet metadata

Comment (divanik) [reply src/Storages/ObjectStorage/IObjectIterator.cpp]: Okay, I understand why buffer can't be empty. So, empty structure is got after applying splitToBuckets function. Should we treat it as an empty files and fail if query_settings.skip_empty_files is False?

File: src/Storages/ObjectStorage/IObjectIterator.cpp [hunk 4]
```diff
@@ -108,22 +108,25 @@ ObjectInfoPtr ObjectIteratorSplitByBuckets::next(size_t id)
         pending_objects_info.pop();
```
Comment (divanik) [inline src/Storages/ObjectStorage/IObjectIterator.cpp]: This if and code is not needed anymore

**Review by divanik — APPROVED** [review]
