### PR TITLE
Preserve aggregation keys order after filter pushdown

### LINKED ISSUE #77917: Logical error: Wrong key in block with `group_by_use_nulls` + `remote` + `QUALIFY`
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=c69c63368fbaabc7abee88bead33b8395c9ae8fa&name_0=MasterCI&name_1=AST%20fuzzer%20%28debug%29

### How to reproduce

Needs a server with asserts (debug)

```
SELECT
    (10 IS NOT NULL, 10, 10, *, 10, *, *, *, *, *, *, *),
    (*, *, isZeroOrNull(10), *, 10, *, *, *, *, *, 10)
FROM remote('127.0.0.{1,2}')
GROUP BY
    (*, *, *, 10, *, materialize(10), *, 10, *, *, *),
    2,
    (assumeNotNull(10) IS NOT NULL, 10, toLowCardinality(10) IS NULL, *, toUInt256(10), *, *, *, *, *, *)
QUALIFY materialize(10)
SETTINGS group_by_use_nulls = true
```

No issues fine with `group_by_use_nulls=false`.
No issues if `remote('127.0.0.{1,2}')` is replaced by `system.one`
No issues if `QUALIFY` is removed

### Error message and/or stacktrace

https://pastila.nl/?00018202/d1552738253c05323901dd30d8f24231#GCmwdODX+vk5bfEEocpFyg==

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
After filter pushdown, if the filter is exactly one of the `group by` keys it moves to the first position and may brake expected order.
Closes #77917

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix logical error after filter pushdown

### CODE REVIEW

File: tests/queries/0_stateless/01798_having_push_down.sql [hunk 1]
```diff
@@ -25,3 +25,7 @@ SELECT sum(c0 = 0), min(c0 + 1), sum(c0 + 2) FROM t_having
 GROUP BY c0 HAVING c0 = 0;
 
 DROP TABLE t_having;
+
```
Comment (nickitat) [inline tests/queries/0_stateless/01798_having_push_down.sql:28]: let's add the original test case too

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp [hunk 2]
```diff
@@ -152,6 +152,14 @@ addNewFilterStepOrThrow(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes,
...
     String split_filter_column_name = split_filter.getOutputs().front()->result_name;
 
+    // If no new columns added, filter just used one of the input columns as-is and moved it to the front, move it back to keep aggregation key in order.
+    if (const auto & input = node.children.at(0)->step->getOutputHeader(); split_filter.getOutputs().size() == input.columns())
+    {
+        auto pos = input.getPositionByName(split_filter_column_name);
+        if (pos != 0)
+            std::rotate(split_filter.getOutputs().begin(), split_filter.getOutputs().begin() + 1, split_filter.getOutputs().begin() + pos + 1);
+    }
+
```
Comment (nickitat) [inline src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:162]: Maybe let's add an explicit check that all columns at the end of the day go in the expected order. Who knows if this bug can also be reproduced with some other query

**Review by nickitat — APPROVED** [review]

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp (hunk 2 above)
Comment (GrigoryPervakov) [reply src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:162]: We have this check, but later and only in debug mode
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/Aggregator.cpp#L342
