### PR TITLE
Check simple dictionary key is native unsigned integer

### LINKED ISSUE #48334: Check primary key type for simple dictionary, to avoid misuse of dictionary tables
**Describe the issue**
The primary key type for simple dictionary should be UInt64, but we never check it. The implicit conversion may cause some problems

**How to reproduce**
```sql
CREATE TABLE test_sample_key_local
(
    `num` Int128, 
    `str` String 
)
ENGINE = Memory

CREATE DICTIONARY test_sample_key_dict
(
    `num` Int128,
    `str` String
)
PRIMARY KEY num
SOURCE(CLICKHOUSE(TABLE 'test_sample_key_local' password 'NTliOGQ3YjRiY2MyNTc4'))
LIFETIME(MIN 0 MAX 300)
LAYOUT(HASHED()); 

insert into test_sample_key_local values (18446744073709551618, '18446744073709551618');

system reload dictionary test_sample_key_dict;

select * from test_sample_key_dict;
┌─num─┬─str──────────────────┐
│   2 │ 18446744073709551618 │
└─────┴──────────────────────┘

```
Users can use this dictionary incorrectly without realizing it.

**Expected behavior**

When create a simple dictionary with  primary key type is not native unsigned integer, throw an exception.  Add a check or not option for compatibility.

### PR DESCRIPTION
**Pull request by lzydmxy**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Check primary key type for simple dictionary is native unsigned integer type
Add  setting `check_dictionary_primary_key ` for compatibility(set `check_dictionary_primary_key =false` to disable checking)

close #48334

### CODE REVIEW

File: src/Core/Settings.h [hunk 1]
```diff
@@ -944,6 +944,7 @@ class IColumn;
     M(Bool, regexp_dict_allow_hyperscan, true, "Allow regexp_tree dictionary using Hyperscan library.", 0) \
     \
     M(Bool, dictionary_use_async_executor, false, "Execute a pipeline for reading from a dictionary with several threads. It's supported only by DIRECT dictionary with CLICKHOUSE source.", 0) \
+    M(Bool, check_sample_dict_key_is_correct, true, "Check primary key type for simple dictionary is Native unsigned integer", 0) \
```
Comment (CurtizJ) [inline src/Core/Settings.h:947]: I think, `check_dictionary_primary_key` is a better name for the setting because it's actually a primary key.

File: src/Dictionaries/getDictionaryConfigurationFromAST.cpp [hunk 2]
```diff
@@ -376,6 +379,26 @@ void buildPrimaryKeyConfiguration(
 
         const ASTDictionaryAttributeDeclaration * dict_attr = (*it)->as<const ASTDictionaryAttributeDeclaration>();
 
+        auto key_type = DataTypeFactory::instance().tryGet(dict_attr->type);
+
+        auto check_sample_dict_key_is_correct = context->getSettings().check_sample_dict_key_is_correct;
```
Comment (CurtizJ) [inline src/Dictionaries/getDictionaryConfigurationFromAST.cpp:384]: It's better to use `getSettingsRef` because `getSettings` makes a copy of the `Settings` struct which is several KBs.

File: src/Core/Settings.h (hunk 1 above)
Comment (lzydmxy) [reply src/Core/Settings.h:947]: `check_dictionary_primary_key` is better, i will change it.

File: src/Dictionaries/getDictionaryConfigurationFromAST.cpp (hunk 2 above)
Comment (lzydmxy) [reply src/Dictionaries/getDictionaryConfigurationFromAST.cpp:384]: ok, thank you for the advice.

**Review by CurtizJ — APPROVED** [review]

**Comment by lzydmxy** [comment]
@CurtizJ  Failed at some tests, and should I update those tests?

**Comment by CurtizJ** [comment]
Yes, please update failed tests.

**Comment by lzydmxy** [comment]
> Yes, please update failed tests.

I update those failed Functional Tests: `02391_hashed_dictionary_shards` `02364_dictionary_datetime_64_attribute_crash` `01160_table_dependencies` `02390_prometheus_ClickHouseStatusInfo_DictionaryStatus` `02525_range_hashed_dictionary_update_field` `01043_dictionary_attribute_properties_values` `01042_system_reload_dictionary_reloads_completely`

I also check those Integration Tests: `test_backup_restore_new` `test_backup_restore_on_cluster` `test_backward_compatibility` `test_dictionaries_access` `test_dictionaries_ddl` `test_dictionaries_dependency` `test_dictionaries_dependency_xml` `test_dictionaries_mysql` `test_dictionaries_postgresql` `test_dictionaries_redis` `test_dictionary_ddl_on_cluster` `test_grant_and_revoke` `test_library_bridge` `test_mask_sensitive_info` `test_range_hashed_dictionary_types` `test_replicated_database` 
And update those Integration Tests: `test_backup_restore_new` `test_backup_restore_on_cluster` `test_backward_compatibility` `test_dictionaries_access` `test_dictionaries_ddl` `test_dictionaries_dependency_xml` `test_mask_sensitive_info` `test_replicated_database`

**Comment by lzydmxy** [comment]
@CurtizJ Hi, I need your help. Task UpgradeCheckMsan failed,  how to deal with it？It seem like I can add config in path `tests/config/users.d`, but I'm not sure~

**Review by CurtizJ — APPROVED** [review]

**Comment by lzydmxy** [comment]
> I'm not 100% sure but looks like it runs queries from the previous release on build from current release and since there were no setting the test fails. It should ok on next PRs after this one will be merged.

Thx for you explanation : )

**Comment by tavplubix** [comment]
@CurtizJ, you forgot to check the failed tests before merging. I have to revert this PR because it breaks tests.
