### PR TITLE
Fix error with duplicate subqueries in FuseFunctionsPass

### LINKED ISSUE #75511: Column identifier __table1.number is already registered. (LOGICAL_ERROR) (optimize_syntax_fuse_functions)
```sql
azat.local$  :) SELECT sum(number) FROM remote('127.0.0.{2,3}', numbers(2)) PREWHERE number GLOBAL IN (SELECT sum(number) FROM numbers(2) GROUP BY number WITH TOTALS) WHERE number GLOBAL IN (SELECT sum(number) FROM numbers(2) GROUP BY number WITH TOTALS) GROUP BY number WITH TOTALS ORDER BY number DESC NULLS FIRST SETTINGS optimize_syntax_fuse_functions=1

SELECT sum(number)
FROM remote('127.0.0.{2,3}', numbers(2))
PREWHERE number GLOBAL IN (
    SELECT sum(number)
    FROM numbers(2)
    GROUP BY number
        WITH TOTALS
)
WHERE number GLOBAL IN (
    SELECT sum(number)
    FROM numbers(2)
    GROUP BY number
        WITH TOTALS
)
GROUP BY number
    WITH TOTALS
ORDER BY number DESC NULLS FIRST
SETTINGS optimize_syntax_fuse_functions = 1

Query id: 72200b13-c00b-4ea6-a252-14a41772da32


Elapsed: 0.003 sec.

Received exception from server (version 25.2.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Column identifier __table1.number is already registered. (LOGICAL_ERROR)
```

CI: https://s3.amazonaws.com/clickhouse-test-reports/75062/5c199052b9235301c7ebb9d3046c35de5f00ed02/ast_fuzzer__debug_.html

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix logical error with duplicate subqueries when `optimize_syntax_fuse_functions` is enabled, close https://github.com/ClickHouse/ClickHouse/issues/75511

### CODE REVIEW

File: src/Analyzer/Passes/FuseFunctionsPass.cpp [hunk 1]
```diff
@@ -64,11 +85,35 @@ class FuseFunctionsVisitor : public InDepthQueryTreeVisitorWithContext<FuseFunct
...
-        argument_to_functions_mapping[argument_nodes[0]].insert(&node);
+        auto argument_with_source = createArgumentWithSource(argument_nodes[0]);
+        if (!argument_with_source)
+            return;
+
+        argument_to_functions_mapping[*argument_with_source].insert(&node);
     }
 
-    /// argument -> list of sum/count/avg functions with this argument
-    QueryTreeNodePtrWithHashMap<std::unordered_set<QueryTreeNodePtr *>> argument_to_functions_mapping;
```
Comment (novikd) [inline src/Analyzer/Passes/FuseFunctionsPass.cpp:71]: I think replacing this map with `QueryTreeNodePtrWithHashMap` would be enough. It will call `isEqual` and the problem will be solved. `CollectColumnSourcesVisitor` seems like overcomplication.

Comment (vdimir) [reply src/Analyzer/Passes/FuseFunctionsPass.cpp:71]: It used to be like that. But it considers identical sub-queries as same trees. However, we do not want to fuse functions across sub-queries. We need here to compare columns with `isEquals`, but with strict comparison of source pointers (e.g. like in validation of group by keys)
