### PR TITLE
Reinitialize DDLWorker state on unexpected errors

### LINKED ISSUE #17991: Useless DDLWorker remains in ClickHouse because of zookeeper failing to initialize
(you don't have to strictly follow this form)

**Describe the bug**
Useless DDLWorker remains in ClickHouse because of zookeeper failing to initialize.
That will cause DDLWorker failing to watch the zookeeper DDL queue normally.
Later, if we perform DDL operations in the cluster, the operation will be hanged.

**How to reproduce**
Configure invalid zookeeper domain name.
* Which ClickHouse server version to use
v20.3.10.75-lts

* Queries to run that lead to unexpected result
```C++
CREATE DATABASE online_smoke ON CLUSTER default_cluster;
```

**Expected behavior**
When Zookeeper fails to initialize normally,we should exit the program.

**Error message and/or stacktrace**
image

**Additional context**
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/DDLWorker.cpp#L1110-L1140

```C++
            if (!Coordination::isHardwareError(e.code))
                throw;  /// A logical error.
```
when we meet  a logical error, the exception throwed will be catched by ThreadPool:
image

I think we should exit the program, when we fail to  initialize `zookeeper`. （But we need to exit the program in a thread, I can not see any code like that）
If there is no problem, I will submit a PR.

### PR DESCRIPTION
**Pull request by weeds085490**
…or in DDLWorker

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In case of unexpected exceptions automatically restart background thread which is responsible for execution of distributed DDL queries. Fixes #17991

### CODE REVIEW

**Comment by weeds085490** [comment]
@alexey-milovidov  Any suggestions about this problem? We encountered this problem in our production environment. PTAL
PTAL

File: src/Interpreters/DDLWorker.cpp [hunk 1]
```diff
@@ -1146,7 +1157,12 @@ void DDLWorker::runMainThread()
         catch (const Coordination::Exception & e)
         {
             if (!Coordination::isHardwareError(e.code))
-                throw;  /// A logical error.
+            {
+                /// A logical error.
+                LOG_ERROR(log, "ZooKeeper error: {}. Failed to start DDLWorker.",getCurrentExceptionMessage(true));
+                reset_state(false);
+                assert(false);  /// Catch such failures in tests with debug build
```
Comment (azat) [inline src/Interpreters/DDLWorker.cpp:1164]: @tavplubix Maybe better to throw `LOGICAL_ERROR`?

Comment (tavplubix) [reply src/Interpreters/DDLWorker.cpp:1164]: The purpose of these changes is to restart DDLWorker thread in case of any unexpected errors. If we throw any exceptions here then server continue works, but DDLWorker doesn't, so all ON CLUSTER queries hang until server is restarted manually.

Comment (azat) [reply src/Interpreters/DDLWorker.cpp:1164]: But `LOGICAL_ERROR` is the same as `assert` - https://github.com/ClickHouse/ClickHouse/blob/8fdaa43b0f9e0dacd83fb3c9dabea67f985c6e79/src/Common/Exception.cpp#L43-L49 (and not only in debug build but under santiziers it will also abort)

Comment (tavplubix) [reply src/Interpreters/DDLWorker.cpp:1164]: > But LOGICAL_ERROR is the same as assert

No, in release builds `assert` does nothing, but `LOGICAL_ERROR` works as usual exception. If we throw any exception here then user have to manually restart ClickHouse to make DDLWorker work.

**Review by tavplubix — APPROVED** [review]
