### PR TITLE
Threshold for dirty allocator pages

### LINKED ISSUE #93380: Improve purging jemalloc data
Current approach, purge jemalloc data when resident memory (according to allocator, including dirty pages) exceeds `max_server_memory_usage`

But this does not work well, i.e.:
- in case allocation itself is big, i.e. > 1GiB (and it is possible)
- or in case there was already some allocations done (within default `dirty_decay_ms=5sec`) and the subsequent allocation will lead to `MEMORY_LIMIT_EXCEEDED`

What we can do is to look at number of "dirty" pages in jemalloc (`stats.arenas.<i>.pdirty` or `jemalloc.arenas.all.pdirty` internal metric) and purge if it exceeds some value, let's say bigger then 10GiB, or bigger then 20% of total memory (`max_server_memory_usage`)

### PR DESCRIPTION
**Pull request by korowa**
### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Force purging of jemalloc arenas in case the ratio of dirty pages size to `max_server_memory_usage` exceeds `memory_worker_purge_dirty_pages_threshold_ratio`

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### Details
Closes #93380.

Make memory worker to be able to preventilvely purge jemalloc arenas, if the size of dirty pages exceeds pre-configured threshold ratio (relatively to `max_server_memory_usage`), even if the process memory is below memory tracker limit.

### Version info
- Merged into: `26.1.1.367`
- Backported to: `25.12.5.18`, `25.10.6.17`, `25.8.16.14`

### CODE REVIEW

File: src/Common/MemoryWorker.cpp [hunk 1]
```diff
@@ -336,7 +343,14 @@ void MemoryWorker::backgroundThread()
             page_cache->autoResize(std::max(resident, total_memory_tracker.get()), total_memory_tracker.getHardLimit());
 
 #if USE_JEMALLOC
-        if (resident > total_memory_tracker.getHardLimit())
+
+        const auto memory_tracker_limit = total_memory_tracker.getHardLimit();
+
+        const bool needs_purge = resident > memory_tracker_limit
+            || (purge_dirty_pages_threshold_ratio > 0
+                && pdirty_mib.getValue() * getPageSize() > memory_tracker_limit * purge_dirty_pages_threshold_ratio);
```
Comment (azat) [inline src/Common/MemoryWorker.cpp]: Can we get size of a jemalloc page? There is definitely a define - `LG_PAGE`, but maybe also something via jemalloc API is available?
Likely right now it matches, but there is no strict requirement for this

File: programs/keeper/Keeper.cpp [hunk 2]
```diff
@@ -396,7 +396,11 @@ try
     });
 
     MemoryWorker memory_worker(
-        config().getUInt64("memory_worker_period_ms", 0), config().getBool("memory_worker_correct_memory_tracker", false), /*use_cgroup*/ true, /*page_cache*/ nullptr);
+        config().getUInt64("memory_worker_period_ms", 0),
+        /*purge_dirty_pages_threshold_ratio*/ 0,
```
Comment (azat) [inline programs/keeper/Keeper.cpp]:
```suggestion
        /*purge_dirty_pages_threshold_ratio=*/ 0,
```

clang-tidy can check comments like this

File: tests/integration/test_dirty_pages_force_purge/test.py [hunk 3]
```diff
@@ -0,0 +1,49 @@
+import time
+
+import pytest
+
+from helpers.cluster import ClickHouseCluster
+
+MALLOC_CONF = "background_thread:false,dirty_decay_ms:-1,muzzy_decay_ms:0,oversize_threshold:0"
```
Comment (azat) [inline tests/integration/test_dirty_pages_force_purge/test.py:10]: Deserves a comment

File: src/Common/MemoryWorker.cpp [hunk 4]
```diff
@@ -321,6 +333,11 @@ void MemoryWorker::backgroundThread()
     std::chrono::milliseconds chrono_period_ms{period_ms};
     [[maybe_unused]] bool first_run = true;
     std::unique_lock lock(mutex);
+
+#if USE_JEMALLOC
+    const auto page_size = pagesize_mib.getValue();
```
Comment (azat) [inline src/Common/MemoryWorker.cpp]: We can get the page size only once, and let's also log it

Comment (korowa) [reply src/Common/MemoryWorker.cpp]: It already was obtained once (outside of thread loop), but anyway I moved it out of here because of logging.

File: src/Common/MemoryWorker.cpp [hunk 5]
```diff
@@ -277,10 +289,13 @@ void MemoryWorker::start()
...
     LOG_INFO(
-        getLogger("MemoryWorker"),
-        "Starting background memory thread with period of {}ms, using {} as source",
+        log,
+        "Starting background memory thread with period of {}ms, using {} as source, purging dirty pages {}{}",
         period_ms,
-        sourceToString(source));
+        sourceToString(source),
+        purge_dirty_pages_threshold_ratio > 0 ? "enabled" : "disabled",
+        purge_dirty_pages_threshold_ratio > 0 ? fmt::format(" (page size: {})", page_size) : "");
```
Comment (azat) [inline src/Common/MemoryWorker.cpp]: Let's log the value of `purge_dirty_pages_threshold_ratio` as well (since we already have logging anyway)

**Review by azat — APPROVED** [review]
