### PR TITLE
Fix indexing in ScatteredBlock::filter

### LINKED ISSUE #84157: Logical Error: Invalid number of rows in Chunk with ANY JOIN
### Describe the bug

From this run: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=00087bbf9cfe5bbb7a231109b447f4ecfb312272&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_ubsan%29

Happens on latest master, time to bisect...

### How to reproduce

Doesn't reproduce always. Run Fiddle: https://fiddle.clickhouse.com/3d57e3bd-0fa7-4a39-a1b5-6897589640de

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'Invalid number of rows in Chunk  Int64(size = 1) UInt8(size = 0) column UInt8 at position 1: expected 1, got 0'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000265d98f2
1. src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014078b26
2. src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cd995ac
3. src/Common/Exception.h:137: DB::Exception::Exception<String, String, unsigned long&, unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, String&&, String&&, unsigned long&, unsigned long&, unsigned long&&) @ 0x000000001e59f644
4. src/Processors/Chunk.cpp:65: DB::Chunk::checkNumRowsIsConsistent() @ 0x000000001e59d667
5. src/Processors/Chunk.cpp:19: DB::Chunk::Chunk(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long) @ 0x000000001e59d4d0
6. src/Processors/Transforms/JoiningTransform.cpp:209: DB::JoiningTransform::transform(DB::Chunk&) @ 0x000000001e86c4cb
7. src/Processors/Transforms/JoiningTransform.cpp:136: DB::JoiningTransform::work() @ 0x000000001e86b9ff
8. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001e5c8510
9. src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001e5bb4c5
10. src/Processors/Executors/PipelineExecutor.cpp:278: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001e5bba29
11. src/Processors/Executors/PipelineExecutor.cpp:561: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001e5bc443
12. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000141bf053
13. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x00000000141c5726
14. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000141bc4e6
15. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000141c2f00
16. start_thread @ 0x00000000000a27f1
17. __clone3 @ 0x0000000000133c9c
```

### LINKED ISSUE #84198: JoiningTransform::transform:  Invalid number of rows in Chunk
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=ff4fc4139a3b074f2fe7708f59a7bd5344509b0d&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_debug%29

### How to reproduce

```
DROP TABLE IF EXISTS test_table_join_1 SYNC;
DROP TABLE IF EXISTS test_table_join_2 SYNC;
DROP TABLE IF EXISTS test_table_join_3 SYNC;

CREATE TABLE test_table_join_1 (`id` UInt8, `value` String) ENGINE = ReplicatedMergeTree('/clickhouse/{database}/test_table_join_1111', 'r1') ORDER BY id SETTINGS index_granularity = 1;
INSERT INTO test_table_join_1 SELECT number, concat('t1_value_', number) FROM numbers(500);

CREATE TABLE test_table_join_2 (`id` UInt16, `value` String) ENGINE = ReplicatedMergeTree('/clickhouse/{database}/test_table_join_21111', 'r1') ORDER BY id SETTINGS index_granularity = 1;
INSERT INTO test_table_join_2 SELECT number, concat('t2_value_', number) FROM numbers(100, 500);

CREATE TABLE test_table_join_3 (`id` UInt64, `value` String) ENGINE = ReplicatedMergeTree('/clickhouse/{database}/test_table_join_31111', 'r1') ORDER BY id SETTINGS index_granularity = 1;
INSERT INTO test_table_join_3 SELECT number, concat('t3_value_', number) FROM numbers(500);

SELECT DISTINCT t3.id AS t3_id, t3.value AS t3_value, t1.id AS t1_id, id AS using_id, t2.value AS t2_value, t2.id AS t2_id, t1.value AS t1_value FROM test_table_join_1 AS t1 ANY INNER JOIN test_table_join_2 AS t2 USING (id) GLOBAL INNER JOIN test_table_join_3 AS t3 USING (id) ORDER BY ALL ASC SETTINGS parallel_replicas_local_plan = 0 settings receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, max_execution_time = 10., max_memory_usage = 10000000000, send_logs_level = 'error', allow_introspection_functions = true, allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 2, cluster_for_parallel_replicas = 'test_cluster_one_shard_three_replicas_localhost', parallel_replicas_mark_segment_size = 1, parallel_replicas_local_plan = false, parallel_replicas_for_cluster_engines = false, allow_experimental_analyzer = true;
```

### Error message and/or stacktrace

```
[Mordor] 2025.07.22 14:19:01.307418 [ 247706 ] {688c8a6e-2283-4461-8ad5-abda9dc5eba3} <Error> executeQuery: Code: 49. DB::Exception: Invalid number of rows in Chunk  UInt16(size = 22) String(size = 22) UInt64(size = 9) String(size = 9) String(size = 9) UInt16(size = 22) column UInt64 at position 2: expected 22, got 9: While executing JoiningTransform. (LOGICAL_ERROR) (version 25.8.1.1) (from 192.168.0.200:48402) (query 10, line 14) (in query: SELECT DISTINCT t3.id AS t3_id, t3.value AS t3_value, t1.id AS t1_id, id AS using_id, t2.value AS t2_value, t2.id AS t2_id, t1.value AS t1_value FROM test_table_join_1 AS t1 ANY INNER JOIN test_table_join_2 AS t2 USING (id) GLOBAL INNER JOIN test_table_join_3 AS t3 USING (id) ORDER BY ALL ASC SETTINGS parallel_replicas_local_plan = 0 settings receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, max_execution_time = 10., max_memory_usage = 10000000000, send_logs_level = 'error', allow_introspection_functions = true, allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 2, cluster_for_parallel_replicas = 'test_cluster_one_shard_three_replicas_localhost', parallel_replicas_mark_segment_size = 1, parallel_replicas_local_plan = false, parallel_replicas_for_cluster_engines = false, allow_experimental_analyzer = true;), Stack trace (when copying this message, always include the lines below):

0. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001fd379b9
1. /mnt/ch/ClickHouse/src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000fafc1ac
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000087ea681
3. /mnt/ch/ClickHouse/src/Common/Exception.h:137: DB::Exception::Exception<String, String, unsigned long&, unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, String&&, String&&, unsigned long&, unsigned long&, unsigned long&&) @ 0x0000000019901f84
4. /mnt/ch/ClickHouse/src/Processors/Chunk.cpp:65: DB::Chunk::checkNumRowsIsConsistent() @ 0x00000000199001a7
5. /mnt/ch/ClickHouse/src/Processors/Chunk.cpp:19: DB::Chunk::Chunk(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long) @ 0x0000000019900053
6. /mnt/ch/ClickHouse/src/Processors/Transforms/JoiningTransform.cpp:209: DB::JoiningTransform::transform(DB::Chunk&) @ 0x0000000019bd4896
7. /mnt/ch/ClickHouse/src/Processors/Transforms/JoiningTransform.cpp:136: DB::JoiningTransform::work() @ 0x0000000019bd39ba
8. /mnt/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001992b092
9. /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001991e8e6
10. /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:278: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001991f8d5
11. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000fc59fd2
12. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000000fc5fdb9
13. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000fc577a3
14. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000fc5dc4f
15. /usr/src/debug/glibc/glibc/nptl/pthread_create.c:448: powl_log_table @ 0x00000000000957eb
16. ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78: __GI___clone3 @ 0x000000000011918c

Received exception from server (version 25.8.1):
Code: 49. DB::Exception: Received from clickhouse-01:49000. DB::Exception: Invalid number of rows in Chunk  UInt16(size = 22) String(size = 22) UInt64(size = 9) String(size = 9) String(size = 9) UInt16(size = 22) column UInt64 at position 2: expected 22, got 9: While executing JoiningTransform. (LOGICAL_ERROR)
(query: SELECT DISTINCT t3.id AS t3_id, t3.value AS t3_value, t1.id AS t1_id, id AS using_id, t2.value AS t2_value, t2.id AS t2_id, t1.value AS t1_value FROM test_table_join_1 AS t1 ANY INNER JOIN test_table_join_2 AS t2 USING (id) GLOBAL INNER JOIN test_table_join_3 AS t3 USING (id) ORDER BY ALL ASC SETTINGS parallel_replicas_local_plan = 0 settings receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, max_execution_time = 10., max_memory_usage = 10000000000, send_logs_level = 'error', allow_introspection_functions = true, allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 2, cluster_for_parallel_replicas = 'test_cluster_one_shard_three_replicas_localhost', parallel_replicas_mark_segment_size = 1, parallel_replicas_local_plan = false, parallel_replicas_for_cluster_engines = false, allow_experimental_analyzer = true;)
```

Does not reproduce with 25.6. Bisecting

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
* Fix possible LOGICAL_ERROR in queries with `parallel_hash` join and thin key columns (like Int16)

(bug in unreleased version)
Close https://github.com/ClickHouse/ClickHouse/issues/84157
Close https://github.com/ClickHouse/ClickHouse/issues/84198

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by nickitat — APPROVED** [review]
How we didn't find it before)
Thanks a lot 👍🏼

File: tests/queries/0_stateless/03573_concurrent_hash_scatter_bug.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
+
```
Comment (nickitat) [inline tests/queries/0_stateless/03573_concurrent_hash_scatter_bug.sql]: just in case, could you pls add this test too
https://fiddle.clickhouse.com/148ae920-cee5-4f4f-803f-c870d6ce2b08
