### PR TITLE
Fix Keeper ephemeral count

### LINKED ISSUE #77757: ClickHouseAsyncMetrics_KeeperEphemeralsCount reports incorrect value
### Describe what's wrong

we are seeing some really weird metrics on keeper ephemeral count

`ClickHouseAsyncMetrics_KeeperEphemeralsCount{container="clickhouse-keeper"}`

this metric is returning a value of 18.4 quintillion 18446744073709552000

any idea what is busted for it to return such a large number?

Might have changed here https://github.com/ClickHouse/ClickHouse/commit/f0e970338454e2a5e09968974ea0850f357ec43e

Image

### Does it reproduce on the most recent release?

Yes

### How to reproduce

CH version 25.2.1.3085

Hit the `/metrics` endpoint on keeper

### Expected behavior

Value should be 0

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Keeper fix: fix ephemeral count in all cases.

Fix https://github.com/ClickHouse/ClickHouse/issues/77757

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Coordination/KeeperSnapshotManager.cpp [hunk 1]
```diff
@@ -443,7 +443,10 @@ void KeeperStorageSnapshot<Storage>::deserialize(SnapshotDeserializationResult<S
                 node.getChildren().reserve(node.stats.numChildren());
 
         if (ephemeral_owner != 0)
+        {
```
Comment (Algunenano) [inline src/Coordination/KeeperSnapshotManager.cpp:446]: I see similar code under ZooKeeperDataReader.cpp::deserializeStorageData. Does that need to be adjusted too?

**Review by Algunenano — COMMENTED** [review]
Why do we keep an external count instead of using `committed_ephemerals->size()`?

**Comment by antonio2368** [comment]
> Why do we keep an external count instead of using committed_ephemerals->size()?

@Algunenano is a map of session to all its ephemeral nodes. I would need to iterate the entire map every time the metric is requested (e.g. async metric would do every second).

File: src/Coordination/KeeperSnapshotManager.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Coordination/KeeperSnapshotManager.cpp:446]: Most likely yes, good catch

Comment (antonio2368) [reply src/Coordination/KeeperSnapshotManager.cpp:446]: It's only a non-critical stat while converted creates a storage from ZK data and dumps a snapshot from it.
So it's not needed there, but just in case, I'll the same change.

**Review by Algunenano — COMMENTED** [review]
> it's a map of session to all its ephemeral nodes. I would need to iterate the entire map every time the metric is requested (e.g. async metric would do every second).

:+1: Looks good. But unit tests aren't happy

**Review by Algunenano — APPROVED** [review]
LGTM.

Out of curiosity: What's the deal with `ephemeralOwner == 0`? What's special about it?

**Comment by antonio2368** [comment]
@Algunenano if `ephemeralOwner` is `0` it means the node is not ephemeral and it can have children.
