### PR TITLE
Analyzer: fix WITH clause resolving

### LINKED ISSUE #48318: [Analyzer] Bad cast in a simple query
**Describe what's wrong**

```
milovidov@milovidov-desktop:~$ clickhouse-local 
ClickHouse local version 23.3.1.2537.

milovidov-desktop :) SET allow_experimental_analyzer = 1

SET allow_experimental_analyzer = 1

Query id: 857ffa3c-786e-4f98-832a-bc100a08dcce

Ok.

0 rows in set. Elapsed: 0.000 sec. 

milovidov-desktop :) WITH
                     
                     -- Input
                     44100 AS sample_frequency
                     , number AS tick
                     , tick / sample_frequency AS time
                     
                     -- Output control
                     , 1 AS master_volume
                     , level -> least(1.0, greatest(-1.0, level)) AS clamp
                     , level -> (clamp(level) * 0x7FFF * master_volume)::Int16 AS output
                     , x -> (x, x) AS mono
                     
                     -- Basic waves
                     , time -> sin(time * 2 * pi()) AS sine_wave
                     , time -> time::UInt64 % 2 * 2 - 1 AS square_wave
                     , time -> (time - floor(time)) * 2 - 1 AS sawtooth_wave
                     , time -> abs(sawtooth_wave(time)) * 2 - 1 AS triangle_wave
                     
                     -- Helpers
                     , (from, to, wave, time) -> from + ((wave(time) + 1) / 2) * (to - from) AS lfo
                     , (from, to, steps, time) -> from + floor((time - floor(time)) * steps) / steps * (to - from) AS step_lfo
                     , (from, to, steps, time) -> exp(step_lfo(log(from), log(to), steps, time)) AS exp_step_lfo
                     
                     -- Noise
                     , time -> cityHash64(time) / 0xFFFFFFFFFFFFFFFF AS uniform_noise
                     , time -> erf(uniform_noise(time)) AS white_noise
                     , time -> cityHash64(time) % 2 ? 1 : -1 AS bernoulli_noise
                     
                     -- Distortion
                     , (x, amount) -> clamp(x * amount) AS clipping
                     , (x, amount) -> clamp(x > 0 ? pow(x, amount) : -pow(-x, amount)) AS power_distortion
                     , (x, amount) -> round(x * exp2(amount)) / exp2(amount) AS bitcrush
                     , (time, sample_frequency) -> round(time * sample_frequency) / sample_frequency AS desample
                     , (time, wave, amount) -> (time - floor(time) < (1 - amount)) ? wave(time * (1 - amount)) : 0 AS thin
                     , (time, wave, amount) -> wave(floor(time) + pow(time - floor(time), amount)) AS skew
                     
                     -- Combining
                     , (a, b, weight) -> a * (1 - weight) + b * weight AS combine
                     
                     -- Envelopes
                     , (time, offset, attack, hold, release) ->
                            time < offset ? 0
                         : (time < offset + attack                  ? ((time - offset) / attack)
                         : (time < offset + attack + hold           ? 1
                         : (time < offset + attack + hold + release ? (offset + attack + hold + release - time) / release
                         : 0))) AS envelope
                     
                     , (bpm, time, offset, attack, hold, release) ->
                         envelope(
                             time * (bpm / 60) - floor(time * (bpm / 60)),
                             offset,
                             attack,
                     WITH
                     
                     -- Input
                     44100 AS sample_frequency
                     , number AS tick
                     , tick / sample_frequency AS time
                     
                     -- Output control
                     , 1 AS master_volume
                     , level -> least(1.0, greatest(-1.0, level)) AS clamp
                     , level -> (clamp(level) * 0x7FFF * master_volume)::Int16 AS output
                     , x -> (x, x) AS mono
                     
                     -- Basic waves
                     , time -> sin(time * 2 * pi()) AS sine_wave
                     , time -> time::UInt64 % 2 * 2 - 1 AS square_wave
                     , time -> (time - floor(time)) * 2 - 1 AS sawtooth_wave
                     , time -> abs(sawtooth_wave(time)) * 2 - 1 AS triangle_wave
                     
                     -- Helpers
                     , (from, to, wave, time) -> from + ((wave(time) + 1) / 2) * (to - from) AS lfo
                     , (from, to, steps, time) -> from + floor((time - floor(time)) * steps) / steps * (to - from) AS step_lfo
                     , (from, to, steps, time) -> exp(step_lfo(log(from), log(to), steps, time)) AS exp_step_lfo
                     
                     -- Noise
                     , time -> cityHash64(time) / 0xFFFFFFFFFFFFFFFF AS uniform_noise
                     , time -> erf(uniform_noise(time)) AS white_noise
                     , time -> cityHash64(time) % 2 ? 1 : -1 AS bernoulli_noise
                     
                     -- Distortion
                     , (x, amount) -> clamp(x * amount) AS clipping
                     , (x, amount) -> clamp(x > 0 ? pow(x, amount) : -pow(-x, amount)) AS power_distortion
                     , (x, amount) -> round(x * exp2(amount)) / exp2(amount) AS bitcrush
                     , (time, sample_frequency) -> round(time * sample_frequency) / sample_frequency AS desample
                     , (time, wave, amount) -> (time - floor(time) < (1 - amount)) ? wave(time * (1 - amount)) : 0 AS thin
                     , (time, wave, amount) -> wave(floor(time) + pow(time - floor(time), amount)) AS skew
                     
                     -- Combining
                     , (a, b, weight) -> a * (1 - weight) + b * weight AS combine
                     
                     -- Envelopes
                     , (time, offset, attack, hold, release) ->
                            time < offset ? 0
                         : (time < offset + attack                  ? ((time - offset) / attack)
                         : (time < offset + attack + hold           ? 1
                         : (time < offset + attack + hold + release ? (offset + attack + hold + release - time) / release
                         : 0))) AS envelope
                     
                     , (bpm, time, offset, attack, hold, release) ->
                         envelope(
                             time * (bpm / 60) - floor(time * (bpm / 60)),
                             offset,
                             attack,
                             hold,
                             release) AS running_envelope
                     
                     -- Sequencers
                     , (sequence, time) -> sequence[1 + time::UInt64 % length(sequence)] AS sequencer
                     
                     -- Delay
                     , (time, wave, delay, decay, count) -> arraySum(n -> wave(time - delay * n) * pow(decay, n), range(count)) AS delay
                     
                     
                     , delay(time, (time -> power_distortion(sine_wave(time * 80 + sine_wave(time * 2)), lfo(0.5, 1, sine_wave, time / 16))
                             * running_envelope(60, time, 0, 0.0, 0.01, 0.1)),
                             0.2, 0.5, 5) AS kick
                     
                     SELECT
                     
                     (output(
                         kick +
                         delay(time, (time ->
                             power_distortion(
                                 sine_wave(time * 50 + 1 * sine_wave(time * 100 + 1/4))
                                     * running_envelope(60, time, 0, 0.01, 0.01, 0.1),
                                 lfo(1, 0.75, triangle_wave, time / 8))),
                             0.2, 0.5, 10)
                         * lfo(0.5, 1, triangle_wave, time / 7)
                     
                         + delay(time, (time ->
                             power_distortion(
                                 sine_wave(time * sequencer([50, 100, 200, 400], time / 2) + 1 * sine_wave(time * sequencer([50, 100, 200], time / 4) + 1/4))
                                     * running_envelope(60, time, 0.5, 0.01, 0.01, 0.1),
                                 lfo(1, 0.75, triangle_wave, time / 8))),
                             0.2, 0.5, 10)
                         * lfo(0.5, 1, triangle_wave, 16 + time / 11)
                     
                         + delay(time, (time ->
                             white_noise(time) * running_envelope(60, time, 0.75, 0.01, 0.01, 0.1)),
                             0.2, 0.5, 10)
                         * lfo(0.5, 1, triangle_wave, 24 + time / 13)
                     
                         + sine_wave(time * 100 + 1 * sine_wave(time * 10 + 1/4))
                             * running_envelope(120, time, 0, 0.01, 0.01, 0.1)
                     ),
                     
                     output(
                         kick +
                         delay(time + 0.01, (time ->
                             power_distortion(
                                 sine_wave(time * 50 + 1 * sine_wave(time * 100 + 1/4))
                                     * running_envelope(60, time, 0, 0.01, 0.01, 0.1),
                                 lfo(1, 0.75, triangle_wave, time / 8))),
                             0.2, 0.5, 10)
                         * lfo(0.5, 1, triangle_wave, time / 7)
                     
                         + delay(time - 0.01, (time ->
                             power_distortion(
                                 sine_wave(time * sequencer([50, 100, 200, 400], time / 2) + 1 * sine_wave(time * sequencer([50, 100, 200], time / 4) + 1/4))
                                     * running_envelope(60, time, 0.5, 0.01, 0.01, 0.1),
                                 lfo(1, 0.75, triangle_wave, time / 8))),
                             0.2, 0.5, 10)
                         * lfo(0.5, 1, triangle_wave, 16 + time / 11)
                     
                         + delay(time + 0.005, (time ->
                             white_noise(time) * running_envelope(60, time, 0.75, 0.01, 0.01, 0.1)),
                             0.2, 0.5, 10)
                         * lfo(0.5, 1, triangle_wave, 24 + time / 13)
                     ))
                     
                     FROM system.numbers;
                     

WITH
    44100 AS sample_frequency,
    number AS tick,
    tick / sample_frequency AS time,
    1 AS master_volume,
    level -> least(1., greatest(-1., level)) AS clamp,
    level -> CAST((clamp(level) * 32767) * master_volume, 'Int16') AS output,
    x -> (x, x) AS mono,
    time -> sin((time * 2) * pi()) AS sine_wave,
    time -> (((CAST(time, 'UInt64') % 2) * 2) - 1) AS square_wave,
    time -> (((time - floor(time)) * 2) - 1) AS sawtooth_wave,
    time -> ((abs(sawtooth_wave(time)) * 2) - 1) AS triangle_wave,
    (from, to, wave, time) -> (from + (((wave(time) + 1) / 2) * (to - from))) AS lfo,
    (from, to, steps, time) -> (from + ((floor((time - floor(time)) * steps) / steps) * (to - from))) AS step_lfo,
    (from, to, steps, time) -> exp(step_lfo(log(from), log(to), steps, time)) AS exp_step_lfo,
    time -> (cityHash64(time) / 18446744073709551615) AS uniform_noise,
    time -> erf(uniform_noise(time)) AS white_noise,
    time -> if(cityHash64(time) % 2, 1, -1) AS bernoulli_noise,
    (x, amount) -> clamp(x * amount) AS clipping,
    (x, amount) -> clamp(if(x > 0, pow(x, amount), -pow(-x, amount))) AS power_distortion,
    (x, amount) -> (round(x * exp2(amount)) / exp2(amount)) AS bitcrush,
    (time, sample_frequency) -> (round(time * sample_frequency) / sample_frequency) AS desample,
    (time, wave, amount) -> if((time - floor(time)) < (1 - amount), wave(time * (1 - amount)), 0) AS thin,
    (time, wave, amount) -> wave(floor(time) + pow(time - floor(time), amount)) AS skew,
    (a, b, weight) -> ((a * (1 - weight)) + (b * weight)) AS combine,
    (time, offset, attack, hold, release) -> if(time < offset, 0, if(time < (offset + attack), (time - offset) / attack, if(time < ((offset + attack) + hold), 1, if(time < (((offset + attack) + hold) + release), ((((offset + attack) + hold) + release) - time) / release, 0)))) AS envelope,
    (bpm, time, offset, attack, hold, release) -> envelope((time * (bpm / 60)) - floor(time * (bpm / 60)), offset, attack, hold, release) AS running_envelope,
    (sequence, time) -> (sequence[1 + (CAST(time, 'UInt64') % length(sequence))]) AS sequencer,
    (time, wave, delay, decay, count) -> arraySum(n -> (wave(time - (delay * n)) * pow(decay, n)), range(count)) AS delay,
    delay(time, time -> (power_distortion(sine_wave((time * 80) + sine_wave(time * 2)), lfo(0.5, 1, sine_wave, time / 16)) * running_envelope(60, time, 0, 0., 0.01, 0.1)), 0.2, 0.5, 5) AS kick
SELECT (output((((kick + (delay(time, time -> power_distortion(sine_wave((time * 50) + (1 * sine_wave((time * 100) + (1 / 4)))) * running_envelope(60, time, 0, 0.01, 0.01, 0.1), lfo(1, 0.75, triangle_wave, time / 8)), 0.2, 0.5, 10) * lfo(0.5, 1, triangle_wave, time / 7))) + (delay(time, time -> power_distortion(sine_wave((time * sequencer([50, 100, 200, 400], time / 2)) + (1 * sine_wave((time * sequencer([50, 100, 200], time / 4)) + (1 / 4)))) * running_envelope(60, time, 0.5, 0.01, 0.01, 0.1), lfo(1, 0.75, triangle_wave, time / 8)), 0.2, 0.5, 10) * lfo(0.5, 1, triangle_wave, 16 + (time / 11)))) + (delay(time, time -> (white_noise(time) * running_envelope(60, time, 0.75, 0.01, 0.01, 0.1)), 0.2, 0.5, 10) * lfo(0.5, 1, triangle_wave, 24 + (time / 13)))) + (sine_wave((time * 100) + (1 * sine_wave((time * 10) + (1 / 4)))) * running_envelope(120, time, 0, 0.01, 0.01, 0.1))), output(((kick + (delay(time + 0.01, time -> power_distortion(sine_wave((time * 50) + (1 * sine_wave((time * 100) + (1 / 4)))) * running_envelope(60, time, 0, 0.01, 0.01, 0.1), lfo(1, 0.75, triangle_wave, time / 8)), 0.2, 0.5, 10) * lfo(0.5, 1, triangle_wave, time / 7))) + (delay(time - 0.01, time -> power_distortion(sine_wave((time * sequencer([50, 100, 200, 400], time / 2)) + (1 * sine_wave((time * sequencer([50, 100, 200], time / 4)) + (1 / 4)))) * running_envelope(60, time, 0.5, 0.01, 0.01, 0.1), lfo(1, 0.75, triangle_wave, time / 8)), 0.2, 0.5, 10) * lfo(0.5, 1, triangle_wave, 16 + (time / 11)))) + (delay(time + 0.005, time -> (white_noise(time) * running_envelope(60, time, 0.75, 0.01, 0.01, 0.1)), 0.2, 0.5, 10) * lfo(0.5, 1, triangle_wave, 24 + (time / 13)))))
FROM system.numbers

Query id: 84d88935-ec0e-4522-b1dc-906c26b0a56b


0 rows in set. Elapsed: 0.203 sec. 

Received exception:
Code: 49. DB::Exception: Bad cast from type DB::ColumnNode to DB::IdentifierNode. (LOGICAL_ERROR)
```

See https://github.com/ClickHouse/NoiSQL

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

This patch removes a separate stage for WITH clause resolving because:
1. It leads to resolving the same expressions several times.
2. The resolving result of WITH clause can't be reused, because pointers in the `IdentifierResolveScope` will still be referring to the initial query tree.
3. After the projection resolution some WITH clause elements that contain lambdas may be in unresolvable state. 

Closes #48318.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 85ba27a2d4b5aa2fc80c90b7393ab327da8e79dc with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52947/85ba27a2d4b5aa2fc80c90b7393ab327da8e79dc/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -6887,13 +6887,12 @@ void QueryAnalyzer::resolveQuery(const QueryTreeNodePtr & query_node, Identifier
...
     }
 
-    std::erase_if(with_nodes, [](const QueryTreeNodePtr & node)
-    {
-        auto * subquery_node = node->as<QueryNode>();
-        auto * union_node = node->as<UnionNode>();
-
-        return (subquery_node && subquery_node->isCTE()) || (union_node && union_node->isCTE());
-    });
+    /** WITH section can be safely removed, because WITH section only can provide aliases to query expressions
```
Comment (vdimir) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:6890]: And everything mentioned already resolved? CTEs registered above and what about regular subqueries with  aliases or constants?

So, we will not have WITH sections after the pass, constants, cte and aliased sub-queries will be substituted?

**Review by vdimir — APPROVED** [review]

File: src/Analyzer/Passes/QueryAnalysisPass.cpp (hunk 1 above)
Comment (novikd) [reply src/Analyzer/Passes/QueryAnalysisPass.cpp:6890]: No, something inside of WITH clause can be unresolved at that point but all the CTEs are registered in the query scope, so it'll be resolved on the first usage.
