### PR TITLE
Fix stress test error with TDigest statistics

### LINKED ISSUE #67742: Logical error: 'Statistics 'tdigest' does not support estimating value of type String'.
https://s3.amazonaws.com/clickhouse-test-reports/67727/fc651cc0c61feb37e9cf104612cc0ac0cd7448e9/ast_fuzzer__ubsan_.html

Revert this: https://github.com/ClickHouse/ClickHouse/pull/59357

### PR DESCRIPTION
**Pull request by rschu1ze**
Resolves #67742

Review note: only https://github.com/ClickHouse/ClickHouse/commit/15d1dbf21f0ea1adeaacac6c44700877ca2fc364 is relevant

This is attempt number 3 to fix the issue, previous attempts:
- https://github.com/ClickHouse/ClickHouse/pull/67858
- https://github.com/ClickHouse/ClickHouse/pull/67013 (<-- in fact, this PR is based on this one)

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by rschu1ze** [comment]
@hanfei1991 Maybe you like to look at this one?

About https://github.com/ClickHouse/ClickHouse/pull/67858#issuecomment-2271267305: The amount of copypasta is minimal for now, we can factorize logic in future if needed.

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 54ba7703b1ccd116dceefe8b0e9c6aca5c24d212 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67930/54ba7703b1ccd116dceefe8b0e9c6aca5c24d212/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67930/54ba7703b1ccd116dceefe8b0e9c6aca5c24d212/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

File: src/Storages/Statistics/StatisticsTDigest.cpp [hunk 1]
```diff
@@ -43,31 +41,35 @@ void StatisticsTDigest::deserialize(ReadBuffer & buf)
 
 Float64 StatisticsTDigest::estimateLess(const Field & val) const
 {
-    auto val_as_float = StatisticsUtils::tryConvertToFloat64(val);
-    if (val_as_float)
-        return t_digest.getCountLessThan(*val_as_float);
-    throw Exception(ErrorCodes::LOGICAL_ERROR, "Statistics 'tdigest' does not support estimating value of type {}", val.getTypeName());
+    Field val_converted = convertFieldToType(val, *data_type);
```
Comment (hanfei1991) [inline src/Storages/Statistics/StatisticsTDigest.cpp:44]: What will happen if `val < '10.5'` but val is int, will `< 10.5` become `< 10`?

Comment (hanfei1991) [reply src/Storages/Statistics/StatisticsTDigest.cpp:44]: or `val < '9999999999999999999999999'` but val is int16

Comment (JackyWoo) [reply src/Storages/Statistics/StatisticsTDigest.cpp:44]: 1. `val_int32 < '10.5'`: the conversion will fail,  but it will never be executed, because the query will fail in the quey plan planning stage which is prior to the optimization stage.
2. `val_int32 < 10.5`: the conversion will get `Null`, which I have fixed here https://github.com/ClickHouse/ClickHouse/pull/67013/commits/aafe498b7f6045e75414c17abecad168aa0efb88 and https://github.com/ClickHouse/ClickHouse/pull/67013/commits/cfaa852af9e94bd25217bfbb690f2d6ad641f3d6
3. `val_int16 < '9999999999999999999999999'` the conversion will get `Null`, also fixed in the previous commits.

Comment (rschu1ze) [reply src/Storages/Statistics/StatisticsTDigest.cpp]: Thanks. I now included the other two commits in this PR.

(Side note: with that, `StatisticsUtils::tryConvertToFloat64` now contains some random-looking special cases, which makes it a time bomb. We really really need to rewrite the tests to check all edge cases systematically, see https://github.com/ClickHouse/ClickHouse/pull/67013#discussion_r1703151496)

Comment (hanfei1991) [reply src/Storages/Statistics/StatisticsTDigest.cpp]: That's why I tried to introduce `TargetType`, but this looks okay to me

**Review by hanfei1991 — APPROVED** [review]
