### PR TITLE
Fix a crash during table loading on startup

### LINKED ISSUE #55767: Caught exception while loading metadata: Code: 393. DB::Exception: There is no query or query context has expired
**Describe what's wrong**

ClickHouse is unable to restart after creating a couple of tables described as in "How to reproduce"

**Does it reproduce on recent release?**

yes - `23.10.1.1063 (revision: 54479, git hash: 1d46ed75db43de34ebe5255d8aa0935017708f58`

**How to reproduce**

1. curl https://clickhouse.com/ | sh
2. ./clickhouse server
3. (from clickhouse client) 
```sql
CREATE TABLE dummy_table_1
(
    `foo` Float64
)
ENGINE = Log AS
SELECT 2;
CREATE TABLE dummy_table_2
(
    `fee` Float64
)
ENGINE = MergeTree
ORDER BY fee AS
SELECT 4;
ALTER TABLE dummy_table_2
    ADD COLUMN `half_fee` Float64 DEFAULT fee / (
        SELECT foo
        FROM dummy_table_1
    );
```
4. stop clickhouse
5. restart clickhouse

* Which ClickHouse server version to use

`23.10.1.1063 (revision: 54479, git hash: 1d46ed75db43de34ebe5255d8aa0935017708f58)`

**Expected behavior**

ClickHouse to restart without crashing.

**Error message and/or stacktrace**

full log capturing all steps above including stop/start

```
$ ./clickhouse server
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
2023.10.18 10:33:38.763925 [ 75808 ] {} <Information> Application: Starting ClickHouse 23.10.1.1063 (revision: 54479, git hash: 1d46ed75db43de34ebe5255d8aa0935017708f58, build id: <unknown>), PID 7382
2023.10.18 10:33:38.764068 [ 75808 ] {} <Information> Application: starting up
2023.10.18 10:33:38.764087 [ 75808 ] {} <Information> Application: OS name: Darwin, version: 23.0.0, architecture: arm64
2023.10.18 10:33:38.769833 [ 75808 ] {} <Information> Application: Available RAM: 32.00 GiB; physical cores: 10; logical cores: 10.
2023.10.18 10:33:38.771181 [ 75808 ] {} <Debug> Application: Set max number of file descriptors to 4294967295 (was 256).
2023.10.18 10:33:38.771193 [ 75808 ] {} <Debug> Application: rlimit on number of threads is 5333
2023.10.18 10:33:38.771196 [ 75808 ] {} <Warning> Context: Maximum number of threads is lower than 30000. There could be problems with handling a lot of simultaneous queries.
2023.10.18 10:33:38.771217 [ 75808 ] {} <Debug> Application: Initializing DateLUT.
2023.10.18 10:33:38.771220 [ 75808 ] {} <Trace> Application: Initialized DateLUT with time zone 'Europe/Rome'.
2023.10.18 10:33:38.771251 [ 75808 ] {} <Debug> Context: Setting up ./tmp/ to store temporary data in it
2023.10.18 10:33:38.771640 [ 75808 ] {} <Debug> Application: Initializing interserver credentials.
2023.10.18 10:33:38.772358 [ 75808 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2023.10.18 10:33:38.772696 [ 75808 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2023.10.18 10:33:38.772977 [ 75808 ] {} <Information> Application: Setting max_server_memory_usage was set to 28.80 GiB (32.00 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2023.10.18 10:33:38.772983 [ 75808 ] {} <Information> Application: Setting merges_mutations_memory_usage_soft_limit was set to 16.00 GiB (32.00 GiB available * 0.50 merges_mutations_memory_usage_to_ram_ratio)
2023.10.18 10:33:38.772986 [ 75808 ] {} <Information> Application: Merges and mutations memory limit is set to 16.00 GiB
2023.10.18 10:33:38.773078 [ 75808 ] {} <Information> BackgroundSchedulePool/BgBufSchPool: Create BackgroundSchedulePool with 16 threads
2023.10.18 10:33:38.773520 [ 75808 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2023.10.18 10:33:38.777874 [ 75808 ] {} <Information> BackgroundSchedulePool/BgMBSchPool: Create BackgroundSchedulePool with 16 threads
2023.10.18 10:33:38.778160 [ 75808 ] {} <Information> BackgroundSchedulePool/BgDistSchPool: Create BackgroundSchedulePool with 16 threads
2023.10.18 10:33:38.778475 [ 75808 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2023.10.18 10:33:38.778964 [ 75808 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2023.10.18 10:33:38.779817 [ 75808 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2023.10.18 10:33:38.780138 [ 75808 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2023.10.18 10:33:38.780759 [ 75808 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2023.10.18 10:33:38.780858 [ 75808 ] {} <Debug> Access(user directories): Added users_xml access storage 'users_xml', path: config.xml
2023.10.18 10:33:38.781378 [ 75808 ] {} <Information> Context: Initialized background executor for merges and mutations with num_threads=16, num_tasks=32, scheduling_policy=round_robin
2023.10.18 10:33:38.781686 [ 75808 ] {} <Information> Context: Initialized background executor for move operations with num_threads=8, num_tasks=8
2023.10.18 10:33:38.781889 [ 75808 ] {} <Information> Context: Initialized background executor for fetches with num_threads=8, num_tasks=8
2023.10.18 10:33:38.782068 [ 75808 ] {} <Information> Context: Initialized background executor for common operations (e.g. clearing old parts) with num_threads=8, num_tasks=8
2023.10.18 10:33:38.782549 [ 75808 ] {} <Information> DNSCacheUpdater: Update period 15 seconds
2023.10.18 10:33:38.782560 [ 75808 ] {} <Information> Application: Loading metadata from ./
2023.10.18 10:33:38.783179 [ 75843 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:33:38.783298 [ 75843 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:33:38.784616 [ 75808 ] {} <Information> DatabaseAtomic (system): Metadata processed, database system has 0 tables and 0 dictionaries in total.
2023.10.18 10:33:38.784625 [ 75808 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 0.000106167 sec
2023.10.18 10:33:38.784644 [ 75808 ] {} <Trace> ReferentialDeps: No tables
2023.10.18 10:33:38.784646 [ 75808 ] {} <Trace> LoadingDeps: No tables
2023.10.18 10:33:38.784715 [ 75808 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2023.10.18 10:33:38.784761 [ 75808 ] {} <Debug> SystemLog: Not creating system.query_log since corresponding section 'query_log' is missing from config
2023.10.18 10:33:38.784776 [ 75808 ] {} <Debug> SystemLog: Not creating system.query_thread_log since corresponding section 'query_thread_log' is missing from config
2023.10.18 10:33:38.784781 [ 75808 ] {} <Debug> SystemLog: Not creating system.part_log since corresponding section 'part_log' is missing from config
2023.10.18 10:33:38.784795 [ 75808 ] {} <Debug> SystemLog: Not creating system.trace_log since corresponding section 'trace_log' is missing from config
2023.10.18 10:33:38.784810 [ 75808 ] {} <Debug> SystemLog: Not creating system.crash_log since corresponding section 'crash_log' is missing from config
2023.10.18 10:33:38.784813 [ 75808 ] {} <Debug> SystemLog: Not creating system.text_log since corresponding section 'text_log' is missing from config
2023.10.18 10:33:38.784829 [ 75808 ] {} <Debug> SystemLog: Not creating system.metric_log since corresponding section 'metric_log' is missing from config
2023.10.18 10:33:38.784844 [ 75808 ] {} <Debug> SystemLog: Not creating system.filesystem_cache_log since corresponding section 'filesystem_cache_log' is missing from config
2023.10.18 10:33:38.784882 [ 75808 ] {} <Debug> SystemLog: Not creating system.filesystem_read_prefetches_log since corresponding section 'filesystem_read_prefetches_log' is missing from config
2023.10.18 10:33:38.784900 [ 75808 ] {} <Debug> SystemLog: Not creating system.asynchronous_metric_log since corresponding section 'asynchronous_metric_log' is missing from config
2023.10.18 10:33:38.784914 [ 75808 ] {} <Debug> SystemLog: Not creating system.opentelemetry_span_log since corresponding section 'opentelemetry_span_log' is missing from config
2023.10.18 10:33:38.784917 [ 75808 ] {} <Debug> SystemLog: Not creating system.query_views_log since corresponding section 'query_views_log' is missing from config
2023.10.18 10:33:38.785061 [ 75808 ] {} <Debug> SystemLog: Not creating system.zookeeper_log since corresponding section 'zookeeper_log' is missing from config
2023.10.18 10:33:38.785078 [ 75808 ] {} <Debug> SystemLog: Not creating system.session_log since corresponding section 'session_log' is missing from config
2023.10.18 10:33:38.785082 [ 75808 ] {} <Debug> SystemLog: Not creating system.transactions_info_log since corresponding section 'transactions_info_log' is missing from config
2023.10.18 10:33:38.785099 [ 75808 ] {} <Debug> SystemLog: Not creating system.processors_profile_log since corresponding section 'processors_profile_log' is missing from config
2023.10.18 10:33:38.785114 [ 75808 ] {} <Debug> SystemLog: Not creating system.asynchronous_insert_log since corresponding section 'asynchronous_insert_log' is missing from config
2023.10.18 10:33:38.785117 [ 75808 ] {} <Debug> SystemLog: Not creating system.backup_log since corresponding section 'backup_log' is missing from config
2023.10.18 10:33:38.795619 [ 75808 ] {} <Information> DatabaseCatalog: Found 0 partially dropped tables. Will load them and retry removal.
2023.10.18 10:33:38.796245 [ 75808 ] {} <Information> DatabaseAtomic (default): Metadata processed, database default has 0 tables and 0 dictionaries in total.
2023.10.18 10:33:38.796258 [ 75808 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 6.4292e-05 sec
2023.10.18 10:33:38.796266 [ 75808 ] {} <Trace> ReferentialDeps: No tables
2023.10.18 10:33:38.796268 [ 75808 ] {} <Trace> LoadingDeps: No tables
2023.10.18 10:33:38.796299 [ 75808 ] {} <Information> DatabaseAtomic (default): Starting up tables.
2023.10.18 10:33:38.796392 [ 75808 ] {} <Information> UserDefinedSQLObjectsLoaderFromDisk: Loading user defined objects from /opt/cases/00006350/user_defined/
2023.10.18 10:33:38.796446 [ 75808 ] {} <Debug> UserDefinedSQLObjectsLoaderFromDisk: User defined objects loaded
2023.10.18 10:33:38.796451 [ 75808 ] {} <Debug> Application: Loaded metadata.
2023.10.18 10:33:38.796455 [ 75808 ] {} <Information> Application: Query Profiler and TraceCollector is only tested on x86_64. It also known to not work under qemu-user.
2023.10.18 10:33:38.796458 [ 75808 ] {} <Information> Application: Query Profiler and TraceCollector are disabled because they require PHDR cache to be created (otherwise the function 'dl_iterate_phdr' is not lock free and not async-signal safe).
2023.10.18 10:33:38.796461 [ 75808 ] {} <Information> Application: TaskStats is not implemented for this OS. IO accounting will be disabled.
2023.10.18 10:33:43.950191 [ 75808 ] {} <Trace> MySQLHandlerFactory: Failed to create SSL context. SSL will be disabled. Error: Poco::Exception. Code: 1000, e.code() = 0, SSL Exception: Configuration error: no certificate file has been specified (version 23.10.1.1063 (official build))
2023.10.18 10:33:43.988015 [ 75808 ] {} <Trace> MySQLHandlerFactory: Failed to read RSA key pair from server certificate. Error: Code: 139. DB::Exception: Certificate file is not set. (NO_ELEMENTS_IN_CONFIG) (version 23.10.1.1063 (official build))
2023.10.18 10:33:43.988050 [ 75808 ] {} <Trace> MySQLHandlerFactory: Generating new RSA key pair.
2023.10.18 10:33:44.149926 [ 75808 ] {} <Trace> MySQLHandlerFactory: Failed to create SSL context. SSL will be disabled. Error: Poco::Exception. Code: 1000, e.code() = 0, SSL Exception: Configuration error: no certificate file has been specified (version 23.10.1.1063 (official build))
2023.10.18 10:33:44.187510 [ 75808 ] {} <Trace> MySQLHandlerFactory: Failed to read RSA key pair from server certificate. Error: Code: 139. DB::Exception: Certificate file is not set. (NO_ELEMENTS_IN_CONFIG) (version 23.10.1.1063 (official build))
2023.10.18 10:33:44.187530 [ 75808 ] {} <Trace> MySQLHandlerFactory: Generating new RSA key pair.
2023.10.18 10:33:44.256325 [ 75808 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2023.10.18 10:33:44.256960 [ 75808 ] {} <Trace> AsynchronousMetrics: Update heavy metrics. Update period 1 sec. Update heavy metrics period 120 sec. Heavy metrics calculation elapsed: 8.625e-06 sec.
2023.10.18 10:33:44.257155 [ 75808 ] {} <Information> Application: Listening for http://[::1]:8123
2023.10.18 10:33:44.257170 [ 75808 ] {} <Information> Application: Listening for native protocol (tcp): [::1]:9000
2023.10.18 10:33:44.257240 [ 75808 ] {} <Information> Application: Listening for MySQL compatibility protocol: [::1]:9004
2023.10.18 10:33:44.257266 [ 75808 ] {} <Information> Application: Listening for http://127.0.0.1:8123
2023.10.18 10:33:44.257277 [ 75808 ] {} <Information> Application: Listening for native protocol (tcp): 127.0.0.1:9000
2023.10.18 10:33:44.257287 [ 75808 ] {} <Information> Application: Listening for MySQL compatibility protocol: 127.0.0.1:9004
2023.10.18 10:33:44.257292 [ 75808 ] {} <Information> Application: Ready for connections.
2023.10.18 10:33:53.789370 [ 75860 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:33:53.789535 [ 75860 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:34:00.787465 [ 75822 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::1]:51076
2023.10.18 10:34:00.787634 [ 75822 ] {} <Debug> TCPHandler: Connected ClickHouse client version 23.2.0, revision: 54461, user: default.
2023.10.18 10:34:00.787687 [ 75822 ] {} <Debug> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Authenticating user 'default' from [::1]:51076
2023.10.18 10:34:00.787699 [ 75822 ] {} <Debug> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2023.10.18 10:34:00.787705 [ 75822 ] {} <Debug> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.10.18 10:34:00.787775 [ 75822 ] {} <Trace> ContextAccess (default): Settings: readonly = 0, allow_ddl = true, allow_introspection_functions = false
2023.10.18 10:34:00.787813 [ 75822 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, displaySecretsInShowAndSelect, INTROSPECTION, SOURCES, CLUSTER ON *.* WITH GRANT OPTION
2023.10.18 10:34:00.787821 [ 75822 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, displaySecretsInShowAndSelect, INTROSPECTION, SOURCES, CLUSTER ON *.* WITH GRANT OPTION
2023.10.18 10:34:00.788717 [ 75822 ] {} <Trace> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.10.18 10:34:00.789009 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Debug> executeQuery: (from [::1]:51076) SELECT * FROM viewIfPermitted(SELECT message FROM system.warnings ELSE null('message String')) (stage: Complete)
2023.10.18 10:34:00.789729 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Trace> ContextAccess (default): Access granted: SELECT(message) ON system.warnings
2023.10.18 10:34:00.789878 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Trace> ContextAccess (default): Access granted: SELECT(message) ON system.warnings
2023.10.18 10:34:00.790008 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.790159 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.790893 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Debug> executeQuery: Read 1 rows, 124.00 B in 0.001955 sec., 511.5089514066496 rows/sec., 61.94 KiB/sec.
2023.10.18 10:34:00.790907 [ 75822 ] {9ee9b909-d809-409f-9579-ff15fed6eb30} <Debug> TCPHandler: Processed in 0.002713583 sec.
2023.10.18 10:34:00.791574 [ 75823 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::1]:51077
2023.10.18 10:34:00.791696 [ 75823 ] {} <Debug> TCPHandler: Connected ClickHouse client version 23.2.0, revision: 54461, user: default.
2023.10.18 10:34:00.791719 [ 75823 ] {} <Debug> TCP-Session: 28a94cf9-3e3f-4f61-b6c9-79aa1f95f697 Authenticating user 'default' from [::1]:51077
2023.10.18 10:34:00.791727 [ 75823 ] {} <Debug> TCP-Session: 28a94cf9-3e3f-4f61-b6c9-79aa1f95f697 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2023.10.18 10:34:00.791734 [ 75823 ] {} <Debug> TCP-Session: 28a94cf9-3e3f-4f61-b6c9-79aa1f95f697 Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.10.18 10:34:00.792043 [ 75823 ] {} <Trace> TCP-Session: 28a94cf9-3e3f-4f61-b6c9-79aa1f95f697 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.10.18 10:34:00.792476 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> executeQuery: (from [::1]:51077) SELECT DISTINCT arrayJoin(extractAll(name, '[\\w_]{2,}')) AS res FROM (SELECT * FROM viewIfPermitted(SELECT name FROM system.functions ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.table_engines ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.formats ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.table_functions ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.data_type_families ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.merge_tree_settings ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.settings ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT cluster FROM system.clusters ELSE null('cluster String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT macro FROM system.macros ELSE null('macro String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT policy_name FROM system.storage_policies ELSE null('policy_name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT concat(func.name, comb.name) AS x FROM system.functions AS func CROSS JOIN system.aggregate_function_combinators AS comb WHERE is_aggregate ELSE null('x String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.databases LIMIT 10000 ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT DISTINCT name FROM system.tables LIMIT 10000 ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT DISTINCT name FROM system.dictionaries LIMIT 10000 ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT DISTINCT name FROM system.columns LIMIT 10000 ELSE null('name String'))) WHERE notEmpty(res) (stage: Complete)
2023.10.18 10:34:00.792902 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.functions
2023.10.18 10:34:00.793011 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.table_engines
2023.10.18 10:34:00.793116 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.formats
2023.10.18 10:34:00.793194 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.table_functions
2023.10.18 10:34:00.793273 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.data_type_families
2023.10.18 10:34:00.793353 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.merge_tree_settings
2023.10.18 10:34:00.793428 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.settings
2023.10.18 10:34:00.793513 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(cluster) ON system.clusters
2023.10.18 10:34:00.793584 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(macro) ON system.macros
2023.10.18 10:34:00.793664 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(policy_name) ON system.storage_policies
2023.10.18 10:34:00.793903 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.aggregate_function_combinators
2023.10.18 10:34:00.793975 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> HashJoin: (0x12f61db98) Datatype: EMPTY, kind: Cross, strictness: Unspecified, right header: comb.name String String(size = 0)
2023.10.18 10:34:00.793981 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> HashJoin: (0x12f61db98) Keys:
2023.10.18 10:34:00.794074 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name, is_aggregate) ON system.functions
2023.10.18 10:34:00.794095 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> HashJoin: (0x12f61db98) Join data is being destroyed, 4096 bytes and 0 rows in hash table
2023.10.18 10:34:00.794187 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.databases
2023.10.18 10:34:00.794288 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.tables
2023.10.18 10:34:00.794382 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.dictionaries
2023.10.18 10:34:00.794466 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.columns
2023.10.18 10:34:00.796041 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.functions
2023.10.18 10:34:00.796503 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Information> EmbeddedDictionaries: Loading dictionaries.
2023.10.18 10:34:00.796534 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Information> EmbeddedDictionaries: Loaded dictionaries.
2023.10.18 10:34:00.861647 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access denied: demangle ON *.*
2023.10.18 10:34:00.981339 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981409 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981549 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.table_engines
2023.10.18 10:34:00.981579 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981724 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981843 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.formats
2023.10.18 10:34:00.981885 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981901 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981953 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.table_functions
2023.10.18 10:34:00.981985 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.981998 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.982045 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.data_type_families
2023.10.18 10:34:00.982095 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.982113 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.982157 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.merge_tree_settings
2023.10.18 10:34:00.982483 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.982502 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.982545 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.settings
2023.10.18 10:34:00.983114 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983131 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983187 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(cluster) ON system.clusters
2023.10.18 10:34:00.983224 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983240 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983282 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(macro) ON system.macros
2023.10.18 10:34:00.983294 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983305 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983348 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(policy_name) ON system.storage_policies
2023.10.18 10:34:00.983377 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> StoragePolicy (default): Storage policy default created, total volumes 1
2023.10.18 10:34:00.983423 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983438 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983563 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.aggregate_function_combinators
2023.10.18 10:34:00.983576 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:00.983591 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> HashJoin: (0x12f621c98) Datatype: EMPTY, kind: Cross, strictness: Unspecified, right header: comb.name String String(size = 0)
2023.10.18 10:34:00.983595 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> HashJoin: (0x12f621c98) Keys:
2023.10.18 10:34:00.983633 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name, is_aggregate) ON system.functions
2023.10.18 10:34:01.045280 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access denied: demangle ON *.*
2023.10.18 10:34:01.163186 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163261 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: Before join block: 'name String String(size = 0), is_aggregate UInt8 UInt8(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0)'
2023.10.18 10:34:01.163367 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: After join block: 'name String String(size = 0), is_aggregate UInt8 UInt8(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0), comb.name String String(size = 0)'
2023.10.18 10:34:01.163432 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163561 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.databases
2023.10.18 10:34:01.163609 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SHOW DATABASES ON *.*
2023.10.18 10:34:01.163675 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163690 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163755 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.tables
2023.10.18 10:34:01.163820 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163835 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163899 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.dictionaries
2023.10.18 10:34:01.163929 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SHOW DICTIONARIES ON *.*
2023.10.18 10:34:01.163953 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.163984 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.164033 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SELECT(name) ON system.columns
2023.10.18 10:34:01.164089 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.164101 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.164117 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:01.164310 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: Before join block: 'is_aggregate UInt8 Const(size = 0, UInt8(size = 1)), name String String(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0)'
2023.10.18 10:34:01.164355 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: After join block: 'is_aggregate UInt8 Const(size = 0, UInt8(size = 1)), name String String(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0), comb.name String String(size = 0)'
2023.10.18 10:34:01.164369 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> QueryPlanOptimizations: Pushed down filter is_aggregate to the Left side of join
2023.10.18 10:34:01.164789 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: Before join block: 'is_aggregate UInt8 Const(size = 0, UInt8(size = 1)), name String String(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0)'
2023.10.18 10:34:01.164818 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: After join block: 'is_aggregate UInt8 Const(size = 0, UInt8(size = 1)), name String String(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0), comb.name String String(size = 0)'
2023.10.18 10:34:01.165173 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: Before join block: 'is_aggregate UInt8 Const(size = 0, UInt8(size = 1)), name String String(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0)'
2023.10.18 10:34:01.165215 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> JoiningTransform: After join block: 'is_aggregate UInt8 Const(size = 0, UInt8(size = 1)), name String String(size = 0), is_deterministic Nullable(UInt8) Nullable(size = 0, UInt8(size = 0), UInt8(size = 0)), case_insensitive UInt8 UInt8(size = 0), alias_to String String(size = 0), create_query String String(size = 0), origin Enum8('System' = 0, 'SQLUserDefined' = 1, 'ExecutableUserDefined' = 2) Int8(size = 0), description String String(size = 0), syntax String String(size = 0), arguments String String(size = 0), returned_value String String(size = 0), examples String String(size = 0), categories String String(size = 0), comb.name String String(size = 0)'
2023.10.18 10:34:01.166842 [ 76303 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SHOW TABLES ON *.*
2023.10.18 10:34:01.166902 [ 76300 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> ContextAccess (default): Access granted: SHOW COLUMNS ON *.*
2023.10.18 10:34:01.168307 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> executeQuery: Read 5958 rows, 709.39 KiB in 0.376045 sec., 15843.848475581379 rows/sec., 1.84 MiB/sec.
2023.10.18 10:34:01.168393 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Trace> HashJoin: (0x12f621c98) Join data is being destroyed, 8448 bytes and 12 rows in hash table
2023.10.18 10:34:01.168496 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> MemoryTracker: Peak memory usage (for query): 16.89 MiB.
2023.10.18 10:34:01.168504 [ 75823 ] {582ca3d8-e710-49cf-a76b-fef37243d8f8} <Debug> TCPHandler: Processed in 0.376527625 sec.
2023.10.18 10:34:01.171778 [ 75823 ] {} <Debug> TCPHandler: Done processing connection.
2023.10.18 10:34:01.171796 [ 75823 ] {} <Debug> TCP-Session: 28a94cf9-3e3f-4f61-b6c9-79aa1f95f697 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.10.18 10:34:01.801392 [ 76288 ] {} <Information> EmbeddedDictionaries: Loading dictionaries.
2023.10.18 10:34:01.801546 [ 76288 ] {} <Information> EmbeddedDictionaries: Loaded dictionaries.
2023.10.18 10:34:08.794888 [ 75864 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:34:08.795017 [ 75864 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:34:14.936927 [ 75822 ] {} <Trace> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.10.18 10:34:14.937156 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Debug> executeQuery: (from [::1]:51076) CREATE TABLE dummy_table_1 (foo Float64) Engine=Log AS SELECT 2; (stage: Complete)
2023.10.18 10:34:14.937258 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON default.dummy_table_1
2023.10.18 10:34:14.938507 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Trace> ContextAccess (default): Access granted: INSERT(foo) ON default.dummy_table_1
2023.10.18 10:34:14.938641 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2023.10.18 10:34:14.938670 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:14.940119 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Debug> executeQuery: Read 1 rows, 1.00 B in 0.003098 sec., 322.78889606197544 rows/sec., 322.79 B/sec.
2023.10.18 10:34:14.940262 [ 75822 ] {0148bf59-b969-48b3-b698-f6334f730f6b} <Debug> TCPHandler: Processed in 0.003481625 sec.
2023.10.18 10:34:19.585224 [ 75822 ] {} <Trace> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.10.18 10:34:19.585387 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Debug> executeQuery: (from [::1]:51076) CREATE TABLE dummy_table_2 (fee Float64) ENGINE=MergeTree() ORDER BY fee AS SELECT 4; (stage: Complete)
2023.10.18 10:34:19.585427 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON default.dummy_table_2
2023.10.18 10:34:19.586981 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Debug> default.dummy_table_2 (3afa71dd-d223-4c91-945e-227f414c58a3): Loading data parts
2023.10.18 10:34:19.587181 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Debug> default.dummy_table_2 (3afa71dd-d223-4c91-945e-227f414c58a3): There are no data parts
2023.10.18 10:34:19.587887 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> ContextAccess (default): Access granted: INSERT(fee) ON default.dummy_table_2
2023.10.18 10:34:19.587966 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2023.10.18 10:34:19.587997 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:19.588428 [ 76295 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> default.dummy_table_2 (3afa71dd-d223-4c91-945e-227f414c58a3): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2023.10.18 10:34:19.588446 [ 76295 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 215.06 GiB.
2023.10.18 10:34:19.589270 [ 76295 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> MergedBlockOutputStream: filled checksums all_1_1_0 (state Temporary)
2023.10.18 10:34:19.590136 [ 76295 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Trace> default.dummy_table_2 (3afa71dd-d223-4c91-945e-227f414c58a3): Renaming temporary part tmp_insert_all_1_1_0 to all_1_1_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2023.10.18 10:34:19.590411 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Debug> executeQuery: Read 1 rows, 1.00 B in 0.005095 sec., 196.27085377821393 rows/sec., 196.27 B/sec.
2023.10.18 10:34:19.590523 [ 75822 ] {dab5b429-54e6-4241-a607-e338eb8d314a} <Debug> TCPHandler: Processed in 0.005446333 sec.
2023.10.18 10:34:23.800058 [ 75844 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:34:23.800209 [ 75844 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:34:31.687991 [ 75822 ] {} <Trace> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.10.18 10:34:31.688212 [ 75822 ] {4b145623-afa3-4ee1-a11e-9e226baafb81} <Debug> executeQuery: (from [::1]:51076) ALTER TABLE dummy_table_2 ADD COLUMN half_fee Float64 DEFAULT (fee / (SELECT foo from dummy_table_1)); (stage: Complete)
2023.10.18 10:34:31.688340 [ 75822 ] {4b145623-afa3-4ee1-a11e-9e226baafb81} <Trace> ContextAccess (default): Access granted: ALTER ADD COLUMN(half_fee) ON default.dummy_table_2
2023.10.18 10:34:31.688590 [ 75822 ] {4b145623-afa3-4ee1-a11e-9e226baafb81} <Trace> ContextAccess (default): Access granted: SELECT(foo) ON default.dummy_table_1
2023.10.18 10:34:31.688645 [ 75822 ] {4b145623-afa3-4ee1-a11e-9e226baafb81} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.10.18 10:34:31.690646 [ 75822 ] {4b145623-afa3-4ee1-a11e-9e226baafb81} <Debug> executeQuery: Read 1 rows, 8.00 B in 0.002562 sec., 390.32006245121 rows/sec., 3.05 KiB/sec.
2023.10.18 10:34:38.805272 [ 75904 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:34:38.805521 [ 75904 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:34:53.809248 [ 75886 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:34:53.809470 [ 75886 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:35:08.812289 [ 75884 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:35:08.812554 [ 75884 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:35:23.812802 [ 75905 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:35:23.813025 [ 75905 ] {} <Debug> DNSResolver: Updated DNS cache
^C2023.10.18 10:35:26.038956 [ 75821 ] {} <Trace> BaseDaemon: Received signal 2
2023.10.18 10:35:26.039100 [ 75821 ] {} <Information> Application: Received termination signal (Interrupt: 2)
2023.10.18 10:35:26.039134 [ 75808 ] {} <Debug> Application: Received termination signal.
2023.10.18 10:35:26.039259 [ 75808 ] {} <Debug> Application: Waiting for current connections to close.
2023.10.18 10:35:27.164278 [ 75808 ] {} <Warning> Application: Closed all listening sockets. Waiting for 1 outstanding connections.
2023.10.18 10:35:31.696431 [ 75822 ] {} <Debug> TCPHandler: Done processing connection.
2023.10.18 10:35:31.696613 [ 75822 ] {} <Debug> TCP-Session: 4f6dabcd-bad6-41e4-b062-af8fd1c5d400 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.10.18 10:35:31.726252 [ 75808 ] {} <Information> Application: Closed connections.
2023.10.18 10:35:31.726358 [ 75808 ] {} <Information> Application: Shutting down storages.
2023.10.18 10:35:31.726376 [ 75808 ] {} <Information> Context: Shutdown disk default
2023.10.18 10:35:31.726387 [ 75808 ] {} <Trace> AsynchronousInsertQueue: Shutting down the asynchronous insertion queue
2023.10.18 10:35:31.726835 [ 75808 ] {} <Trace> AsynchronousInsertQueue: Asynchronous insertion queue finished
2023.10.18 10:35:31.726866 [ 75808 ] {} <Debug> Context: Shutting down dictionaries loader
2023.10.18 10:35:31.726905 [ 75808 ] {} <Debug> Context: Shutting down UDFs loader
2023.10.18 10:35:31.726967 [ 75808 ] {} <Debug> Context: Shutting down another UDFs loader
2023.10.18 10:35:31.726981 [ 75808 ] {} <Trace> Context: Shutting down named sessions
2023.10.18 10:35:31.727002 [ 75808 ] {} <Debug> Context: Shutting down system logs
2023.10.18 10:35:31.727010 [ 75808 ] {} <Trace> Context: Shutting down database catalog
2023.10.18 10:35:31.727027 [ 75808 ] {} <Trace> DatabaseCatalog: Shutting down database INFORMATION_SCHEMA
2023.10.18 10:35:31.727239 [ 75808 ] {} <Trace> DatabaseCatalog: Shutting down database default
2023.10.18 10:35:31.916586 [ 75808 ] {} <Trace> DatabaseCatalog: Shutting down database information_schema
2023.10.18 10:35:31.916713 [ 75808 ] {} <Trace> DatabaseCatalog: Shutting down system databases
2023.10.18 10:35:31.917062 [ 75808 ] {} <Debug> Context: Shutting down merges executor
2023.10.18 10:35:31.917267 [ 75808 ] {} <Debug> Context: Shutting down fetches executor
2023.10.18 10:35:31.917341 [ 75808 ] {} <Debug> Context: Shutting down moves executor
2023.10.18 10:35:31.917461 [ 75808 ] {} <Debug> Context: Shutting down common executor
2023.10.18 10:35:31.917533 [ 75808 ] {} <Trace> Context: Shutting down DDLWorker
2023.10.18 10:35:31.917538 [ 75808 ] {} <Trace> Context: Shutting down caches
2023.10.18 10:35:31.917593 [ 75808 ] {} <Trace> BackgroundSchedulePool/BgBufSchPool: Waiting for threads to finish.
2023.10.18 10:35:31.917700 [ 75808 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2023.10.18 10:35:31.917983 [ 75808 ] {} <Trace> BackgroundSchedulePool/BgDistSchPool: Waiting for threads to finish.
2023.10.18 10:35:31.918088 [ 75808 ] {} <Trace> BackgroundSchedulePool/BgMBSchPool: Waiting for threads to finish.
2023.10.18 10:35:31.918186 [ 75808 ] {} <Debug> Application: Shut down storages.
2023.10.18 10:35:31.918196 [ 75808 ] {} <Debug> Context: Destructing remote fs threadpool reader
2023.10.18 10:35:31.918200 [ 75808 ] {} <Debug> Context: Destructing local fs threadpool reader
2023.10.18 10:35:31.918232 [ 75808 ] {} <Debug> Context: Destructing local fs threadpool reader
2023.10.18 10:35:31.918585 [ 75808 ] {} <Debug> Application: Destroyed global context.
2023.10.18 10:35:31.919007 [ 75808 ] {} <Information> Application: shutting down
2023.10.18 10:35:31.919016 [ 75808 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2023.10.18 10:35:31.919265 [ 75821 ] {} <Trace> BaseDaemon: Received signal -2
2023.10.18 10:35:31.919288 [ 75821 ] {} <Information> BaseDaemon: Stop SignalListener thread
## STOP
## START
$ ./clickhouse server
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
2023.10.18 10:35:41.105864 [ 77945 ] {} <Information> Application: Starting ClickHouse 23.10.1.1063 (revision: 54479, git hash: 1d46ed75db43de34ebe5255d8aa0935017708f58, build id: <unknown>), PID 7931
2023.10.18 10:35:41.105888 [ 77945 ] {} <Information> Application: starting up
2023.10.18 10:35:41.105905 [ 77945 ] {} <Information> Application: OS name: Darwin, version: 23.0.0, architecture: arm64
2023.10.18 10:35:41.107210 [ 77945 ] {} <Information> Application: Available RAM: 32.00 GiB; physical cores: 10; logical cores: 10.
2023.10.18 10:35:41.107935 [ 77945 ] {} <Debug> Application: Set max number of file descriptors to 4294967295 (was 256).
2023.10.18 10:35:41.107943 [ 77945 ] {} <Debug> Application: rlimit on number of threads is 5333
2023.10.18 10:35:41.107946 [ 77945 ] {} <Warning> Context: Maximum number of threads is lower than 30000. There could be problems with handling a lot of simultaneous queries.
2023.10.18 10:35:41.107951 [ 77945 ] {} <Debug> Application: Initializing DateLUT.
2023.10.18 10:35:41.107954 [ 77945 ] {} <Trace> Application: Initialized DateLUT with time zone 'Europe/Rome'.
2023.10.18 10:35:41.107961 [ 77945 ] {} <Debug> Context: Setting up ./tmp/ to store temporary data in it
2023.10.18 10:35:41.108061 [ 77945 ] {} <Debug> Application: Initializing interserver credentials.
2023.10.18 10:35:41.108636 [ 77945 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2023.10.18 10:35:41.108907 [ 77945 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2023.10.18 10:35:41.109123 [ 77945 ] {} <Information> Application: Setting max_server_memory_usage was set to 28.80 GiB (32.00 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2023.10.18 10:35:41.109127 [ 77945 ] {} <Information> Application: Setting merges_mutations_memory_usage_soft_limit was set to 16.00 GiB (32.00 GiB available * 0.50 merges_mutations_memory_usage_to_ram_ratio)
2023.10.18 10:35:41.109130 [ 77945 ] {} <Information> Application: Merges and mutations memory limit is set to 16.00 GiB
2023.10.18 10:35:41.109153 [ 77945 ] {} <Information> BackgroundSchedulePool/BgBufSchPool: Create BackgroundSchedulePool with 16 threads
2023.10.18 10:35:41.109517 [ 77945 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2023.10.18 10:35:41.113123 [ 77945 ] {} <Information> BackgroundSchedulePool/BgMBSchPool: Create BackgroundSchedulePool with 16 threads
2023.10.18 10:35:41.113540 [ 77945 ] {} <Information> BackgroundSchedulePool/BgDistSchPool: Create BackgroundSchedulePool with 16 threads
2023.10.18 10:35:41.114611 [ 77945 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2023.10.18 10:35:41.114653 [ 77945 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2023.10.18 10:35:41.115671 [ 77945 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2023.10.18 10:35:41.115992 [ 77945 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2023.10.18 10:35:41.116418 [ 77945 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2023.10.18 10:35:41.116525 [ 77945 ] {} <Debug> Access(user directories): Added users_xml access storage 'users_xml', path: config.xml
2023.10.18 10:35:41.116848 [ 77945 ] {} <Information> Context: Initialized background executor for merges and mutations with num_threads=16, num_tasks=32, scheduling_policy=round_robin
2023.10.18 10:35:41.116998 [ 77945 ] {} <Information> Context: Initialized background executor for move operations with num_threads=8, num_tasks=8
2023.10.18 10:35:41.117438 [ 77945 ] {} <Information> Context: Initialized background executor for fetches with num_threads=8, num_tasks=8
2023.10.18 10:35:41.117619 [ 77945 ] {} <Information> Context: Initialized background executor for common operations (e.g. clearing old parts) with num_threads=8, num_tasks=8
2023.10.18 10:35:41.117949 [ 77945 ] {} <Information> DNSCacheUpdater: Update period 15 seconds
2023.10.18 10:35:41.117965 [ 77945 ] {} <Information> Application: Loading metadata from ./
2023.10.18 10:35:41.118111 [ 77995 ] {} <Debug> DNSResolver: Updating DNS cache
2023.10.18 10:35:41.118203 [ 77995 ] {} <Debug> DNSResolver: Updated DNS cache
2023.10.18 10:35:41.118511 [ 77945 ] {} <Information> DatabaseAtomic (system): Metadata processed, database system has 0 tables and 0 dictionaries in total.
2023.10.18 10:35:41.118517 [ 77945 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 5.7625e-05 sec
2023.10.18 10:35:41.118521 [ 77945 ] {} <Trace> ReferentialDeps: No tables
2023.10.18 10:35:41.118524 [ 77945 ] {} <Trace> LoadingDeps: No tables
2023.10.18 10:35:41.118542 [ 77945 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2023.10.18 10:35:41.118553 [ 77945 ] {} <Debug> SystemLog: Not creating system.query_log since corresponding section 'query_log' is missing from config
2023.10.18 10:35:41.118563 [ 77945 ] {} <Debug> SystemLog: Not creating system.query_thread_log since corresponding section 'query_thread_log' is missing from config
2023.10.18 10:35:41.118566 [ 77945 ] {} <Debug> SystemLog: Not creating system.part_log since corresponding section 'part_log' is missing from config
2023.10.18 10:35:41.118570 [ 77945 ] {} <Debug> SystemLog: Not creating system.trace_log since corresponding section 'trace_log' is missing from config
2023.10.18 10:35:41.118573 [ 77945 ] {} <Debug> SystemLog: Not creating system.crash_log since corresponding section 'crash_log' is missing from config
2023.10.18 10:35:41.118576 [ 77945 ] {} <Debug> SystemLog: Not creating system.text_log since corresponding section 'text_log' is missing from config
2023.10.18 10:35:41.118621 [ 77945 ] {} <Debug> SystemLog: Not creating system.metric_log since corresponding section 'metric_log' is missing from config
2023.10.18 10:35:41.118626 [ 77945 ] {} <Debug> SystemLog: Not creating system.filesystem_cache_log since corresponding section 'filesystem_cache_log' is missing from config
2023.10.18 10:35:41.118630 [ 77945 ] {} <Debug> SystemLog: Not creating system.filesystem_read_prefetches_log since corresponding section 'filesystem_read_prefetches_log' is missing from config
2023.10.18 10:35:41.118634 [ 77945 ] {} <Debug> SystemLog: Not creating system.asynchronous_metric_log since corresponding section 'asynchronous_metric_log' is missing from config
2023.10.18 10:35:41.118638 [ 77945 ] {} <Debug> SystemLog: Not creating system.opentelemetry_span_log since corresponding section 'opentelemetry_span_log' is missing from config
2023.10.18 10:35:41.118645 [ 77945 ] {} <Debug> SystemLog: Not creating system.query_views_log since corresponding section 'query_views_log' is missing from config
2023.10.18 10:35:41.118648 [ 77945 ] {} <Debug> SystemLog: Not creating system.zookeeper_log since corresponding section 'zookeeper_log' is missing from config
2023.10.18 10:35:41.118652 [ 77945 ] {} <Debug> SystemLog: Not creating system.session_log since corresponding section 'session_log' is missing from config
2023.10.18 10:35:41.118656 [ 77945 ] {} <Debug> SystemLog: Not creating system.transactions_info_log since corresponding section 'transactions_info_log' is missing from config
2023.10.18 10:35:41.118669 [ 77945 ] {} <Debug> SystemLog: Not creating system.processors_profile_log since corresponding section 'processors_profile_log' is missing from config
2023.10.18 10:35:41.118673 [ 77945 ] {} <Debug> SystemLog: Not creating system.asynchronous_insert_log since corresponding section 'asynchronous_insert_log' is missing from config
2023.10.18 10:35:41.118676 [ 77945 ] {} <Debug> SystemLog: Not creating system.backup_log since corresponding section 'backup_log' is missing from config
2023.10.18 10:35:41.127251 [ 77945 ] {} <Information> DatabaseCatalog: Found 0 partially dropped tables. Will load them and retry removal.
2023.10.18 10:35:41.127648 [ 77945 ] {} <Information> DatabaseAtomic (default): Metadata processed, database default has 2 tables and 0 dictionaries in total.
2023.10.18 10:35:41.127655 [ 77945 ] {} <Information> TablesLoader: Parsed metadata of 2 tables in 1 databases in 0.000255417 sec
2023.10.18 10:35:41.127674 [ 77945 ] {} <Trace> ReferentialDeps: Table default.dummy_table_1 has no dependencies (level 0)
2023.10.18 10:35:41.127678 [ 77945 ] {} <Trace> ReferentialDeps: Table default.dummy_table_2 has 1 dependencies: default.dummy_table_1 (level 1)
2023.10.18 10:35:41.127680 [ 77945 ] {} <Trace> LoadingDeps: Table default.dummy_table_2 has no dependencies (level 0)
2023.10.18 10:35:41.127684 [ 77945 ] {} <Trace> LoadingDeps: Table default.dummy_table_1 has no dependencies (level 0)
2023.10.18 10:35:41.127697 [ 77945 ] {} <Information> TablesLoader: Loading 2 tables with dependency level 0
2023.10.18 10:35:41.549975 [ 77945 ] {} <Error> Application: Caught exception while loading metadata: Code: 393. DB::Exception: There is no query or query context has expired: While processing (SELECT foo FROM default.dummy_table_1) AS _subquery1: While processing fee / ((SELECT foo FROM default.dummy_table_1) AS _subquery1) AS half_fee_tmp_alter9831497812304068275: While processing _CAST(fee / ((SELECT foo FROM default.dummy_table_1) AS _subquery1) AS half_fee_tmp_alter9831497812304068275, 'Float64') AS half_fee: default expression and column type are incompatible.: Cannot attach table `default`.`dummy_table_2` from metadata file /opt/cases/00006350/store/b79/b795c520-8335-4e46-ac79-bbee02f954ab/dummy_table_2.sql from query ATTACH TABLE default.dummy_table_2 UUID '3afa71dd-d223-4c91-945e-227f414c58a3' (`fee` Float64, `half_fee` Float64 DEFAULT fee / (SELECT foo FROM default.dummy_table_1)) ENGINE = MergeTree ORDER BY fee SETTINGS index_granularity = 8192. (THERE_IS_NO_QUERY), Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 23.10.1.1063 (official build))
2023.10.18 10:35:41.550117 [ 77945 ] {} <Information> Application: Shutting down storages.
2023.10.18 10:35:41.550124 [ 77945 ] {} <Information> Context: Shutdown disk default
2023.10.18 10:35:41.550135 [ 77945 ] {} <Trace> AsynchronousInsertQueue: Shutting down the asynchronous insertion queue
2023.10.18 10:35:41.550282 [ 77945 ] {} <Trace> AsynchronousInsertQueue: Asynchronous insertion queue finished
2023.10.18 10:35:41.550290 [ 77945 ] {} <Trace> Context: Shutting down named sessions
2023.10.18 10:35:41.550301 [ 77945 ] {} <Debug> Context: Shutting down system logs
2023.10.18 10:35:41.550304 [ 77945 ] {} <Trace> Context: Shutting down database catalog
2023.10.18 10:35:41.550308 [ 77945 ] {} <Trace> DatabaseCatalog: Shutting down database INFORMATION_SCHEMA
2023.10.18 10:35:41.550402 [ 77945 ] {} <Trace> DatabaseCatalog: Shutting down database default
2023.10.18 10:35:41.550409 [ 77945 ] {} <Trace> DatabaseCatalog: Shutting down database information_schema
2023.10.18 10:35:41.550478 [ 77945 ] {} <Trace> DatabaseCatalog: Shutting down system databases
2023.10.18 10:35:41.550786 [ 77945 ] {} <Debug> Context: Shutting down merges executor
2023.10.18 10:35:41.550919 [ 77945 ] {} <Debug> Context: Shutting down fetches executor
2023.10.18 10:35:41.550978 [ 77945 ] {} <Debug> Context: Shutting down moves executor
2023.10.18 10:35:41.551066 [ 77945 ] {} <Debug> Context: Shutting down common executor
2023.10.18 10:35:41.551127 [ 77945 ] {} <Trace> Context: Shutting down DDLWorker
2023.10.18 10:35:41.551132 [ 77945 ] {} <Trace> Context: Shutting down caches
2023.10.18 10:35:41.551188 [ 77945 ] {} <Trace> BackgroundSchedulePool/BgBufSchPool: Waiting for threads to finish.
2023.10.18 10:35:41.551331 [ 77945 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2023.10.18 10:35:41.551662 [ 77945 ] {} <Trace> BackgroundSchedulePool/BgDistSchPool: Waiting for threads to finish.
2023.10.18 10:35:41.551762 [ 77945 ] {} <Trace> BackgroundSchedulePool/BgMBSchPool: Waiting for threads to finish.
2023.10.18 10:35:41.551821 [ 77945 ] {} <Debug> Application: Shut down storages.
2023.10.18 10:35:41.552074 [ 77945 ] {} <Debug> Application: Destroyed global context.
2023.10.18 10:35:41.552733 [ 77945 ] {} <Error> Application: Code: 393. DB::Exception: There is no query or query context has expired: While processing (SELECT foo FROM default.dummy_table_1) AS _subquery1: While processing fee / ((SELECT foo FROM default.dummy_table_1) AS _subquery1) AS half_fee_tmp_alter9831497812304068275: While processing _CAST(fee / ((SELECT foo FROM default.dummy_table_1) AS _subquery1) AS half_fee_tmp_alter9831497812304068275, 'Float64') AS half_fee: default expression and column type are incompatible.: Cannot attach table `default`.`dummy_table_2` from metadata file /opt/cases/00006350/store/b79/b795c520-8335-4e46-ac79-bbee02f954ab/dummy_table_2.sql from query ATTACH TABLE default.dummy_table_2 UUID '3afa71dd-d223-4c91-945e-227f414c58a3' (`fee` Float64, `half_fee` Float64 DEFAULT fee / (SELECT foo FROM default.dummy_table_1)) ENGINE = MergeTree ORDER BY fee SETTINGS index_granularity = 8192. (THERE_IS_NO_QUERY), Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 23.10.1.1063 (official build))
2023.10.18 10:35:41.568256 [ 77945 ] {} <Error> Application: DB::Exception: There is no query or query context has expired: While processing (SELECT foo FROM default.dummy_table_1) AS _subquery1: While processing fee / ((SELECT foo FROM default.dummy_table_1) AS _subquery1) AS half_fee_tmp_alter9831497812304068275: While processing _CAST(fee / ((SELECT foo FROM default.dummy_table_1) AS _subquery1) AS half_fee_tmp_alter9831497812304068275, 'Float64') AS half_fee: default expression and column type are incompatible.: Cannot attach table `default`.`dummy_table_2` from metadata file /opt/cases/00006350/store/b79/b795c520-8335-4e46-ac79-bbee02f954ab/dummy_table_2.sql from query ATTACH TABLE default.dummy_table_2 UUID '3afa71dd-d223-4c91-945e-227f414c58a3' (`fee` Float64, `half_fee` Float64 DEFAULT fee / (SELECT foo FROM default.dummy_table_1)) ENGINE = MergeTree ORDER BY fee SETTINGS index_granularity = 8192
2023.10.18 10:35:41.568279 [ 77945 ] {} <Information> Application: shutting down
2023.10.18 10:35:41.568365 [ 77945 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2023.10.18 10:35:41.568666 [ 77949 ] {} <Trace> BaseDaemon: Received signal -2
2023.10.18 10:35:41.568687 [ 77949 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a crash during table loading on startup. Closes https://github.com/ClickHouse/ClickHouse/issues/55767

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit f3dd317edd52d7300fbb97db2d6777e45d09bdae with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56232/f3dd317edd52d7300fbb97db2d6777e45d09bdae/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6727666874">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56232/f3dd317edd52d7300fbb97db2d6777e45d09bdae/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp [hunk 1]
```diff
@@ -78,16 +78,19 @@ static auto getQueryInterpreter(const ASTSubquery & subquery, ExecuteScalarSubqu
     subquery_settings.extremes = false;
     subquery_context->setSettings(subquery_settings);
 
-    /// When execute `INSERT INTO t WITH ... SELECT ...`, it may lead to `Unknown columns`
-    /// exception with this settings enabled(https://github.com/ClickHouse/ClickHouse/issues/52494).
-    subquery_context->getQueryContext()->setSetting("use_structure_from_insertion_table_in_table_functions", false);
-    if (!data.only_analyze && subquery_context->hasQueryContext())
+    if (subquery_context->hasQueryContext())
```
Comment (vdimir) [inline src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:81]: Is it possible to have non-empty `data.scalars` but no query context? If yes, why do we execute such query on a startup without context?

Comment (evillique) [reply src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:81]: The main problem was in line with `subquery_context->getQueryContext()->setSetting` that used query context without checking if it is even there. Now we add a check for it. Other things did not change

Comment (vdimir) [reply src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:81]: Isn't it a problem in itself that we are executing this code without initialized query context?

**Review by vdimir — APPROVED** [review]
