### PR TITLE
Fix checking grants for SHOW GRANTS

### LINKED ISSUE #19429: RBAC - SHOW GRANTS FOR ALL don't check if user is allowed to see grants
```
laptop-5591 :) SHOW GRANTS;

SHOW GRANTS

Query id: 43b4b2ea-7789-4c2a-8ce8-094e17d27538

┌─GRANTS─────────────────────┐
│ GRANT SELECT ON *.* TO xxx │
└────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec. 

laptop-5591 :) select * from system.grants;

SELECT *
FROM system.grants

Query id: 2e159b46-e94a-4e34-98cd-b8c1c573fcf7


Received exception from server (version 20.13.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: xxx: Not enough privileges. To execute this query it's necessary to have grant SHOW USERS, SHOW ROLES ON *.*. 

0 rows in set. Elapsed: 0.004 sec. 

laptop-5591 :) SHOW GRANTS FOR ALL;

SHOW GRANTS FOR ALL

Query id: 5c10f791-b010-4190-907d-9ff17bccf7be

┌─GRANTS FOR ALL────────────────────────────────┐
│ GRANT ALL ON *.* TO admin WITH GRANT OPTION   │
│ GRANT ALL ON *.* TO default WITH GRANT OPTION │
│ GRANT SELECT ON *.* TO xxx                    │
└───────────────────────────────────────────────┘

3 rows in set. Elapsed: 0.003 sec. 
```

### PR DESCRIPTION
**Pull request by vitlibar**
Changelog category:
- Bug Fix

Changelog entry:
This PR fixes https://github.com/ClickHouse/ClickHouse/issues/19429

### CODE REVIEW

File: src/Interpreters/Access/InterpreterShowGrantsQuery.cpp [hunk 1]
```diff
@@ -135,15 +136,53 @@ QueryPipeline InterpreterShowGrantsQuery::executeImpl()
...
 {
-    const auto & show_query = query_ptr->as<ASTShowGrantsQuery &>();
+    const auto & access = getContext()->getAccess();
     const auto & access_control = getContext()->getAccessControl();
+
+    const auto & show_query = query_ptr->as<ASTShowGrantsQuery &>();
     auto ids = RolesOrUsersSet{*show_query.for_roles, access_control, getContext()->getUserID()}.getMatchingIDs(access_control);
 
+    bool throw_if_access_denied = !show_query.for_roles->all;
+    std::optional<bool> show_users_check_result;
```
Comment (kitaisreal) [inline src/Interpreters/Access/InterpreterShowGrantsQuery.cpp:146]: Not sure why we modify these variables inside lambdas and then return result of them, can't we just call lambda and return result ?
Also these lambdas are almost the same, maybe better to extract into some static method and call with `AccessType` argument ?

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Interpreters/Access/InterpreterShowGrantsQuery.cpp (hunk 1 above)
Comment (vitlibar) [reply src/Interpreters/Access/InterpreterShowGrantsQuery.cpp]: I moved this logic to a separate helper class `CachedAccessChecking`, it seems it looks better now.
Perhaps later I'll use this helper class in some other places too...

**Review by kitaisreal — APPROVED** [review]

File: src/Interpreters/Access/InterpreterShowGrantsQuery.cpp (hunk 1 above)
Comment (kitaisreal) [reply src/Interpreters/Access/InterpreterShowGrantsQuery.cpp]: Agreed. Now much easier to read.
