### PR TITLE
Forbid to create not insertable tables

### LINKED ISSUE #72139: Logical Error: Column description is empty and it can't be built from sample from table
**Describe the bug**
Inserting into a table with just one materialized column, gives logical error.

**How to reproduce**
Run:
https://fiddle.clickhouse.com/e4e22f97-5400-4ada-990b-c5efb63885db

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
Materialized columns are physical, but data can't be inserted into such tables without a Default or Ephemeral column.
It can break clickhouse-client in cases like the linked issue.

Closes #72139

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Forbid the creation of a table without insertable columns.

### CODE REVIEW

File: src/Interpreters/InterpreterCreateQuery.cpp [hunk 1]
```diff
@@ -731,10 +731,20 @@ ColumnsDescription InterpreterCreateQuery::getColumnsDescription(
...
+    bool hasPhysicalColumns = false;
+    bool hasInsertableColumns = false;
+    for (const auto & column : res)
+    {
+        hasPhysicalColumns |= column.default_desc.kind == ColumnDefaultKind::Default || column.default_desc.kind == ColumnDefaultKind::Materialized;
+        hasInsertableColumns |= column.default_desc.kind == ColumnDefaultKind::Default || column.default_desc.kind == ColumnDefaultKind::Ephemeral;
+    }
 
-    if (res.getAllPhysical().empty())
+    if (!hasPhysicalColumns)
```
Comment (nikitamikhaylov) [inline src/Interpreters/InterpreterCreateQuery.cpp]: We should be able to attach them or execute secondary create.

Comment (GrigoryPervakov) [reply src/Interpreters/InterpreterCreateQuery.cpp]: Added check and test

File: tests/queries/0_stateless/03541_table_without_insertable_columns.sql [hunk 2]
```diff
@@ -0,0 +1,12 @@
+-- Tags: no-parallel, no-ordinary-database
+-- Tag no-parallel: static UUID
+-- Tag no-ordinary-database: requires UUID
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03541_table_without_insertable_columns.sql:3]: Why do you need static UUID?

Comment (GrigoryPervakov) [reply tests/queries/0_stateless/03541_table_without_insertable_columns.sql:3]: To test that `ATTACH` query works

Comment (GrigoryPervakov) [reply tests/queries/0_stateless/03541_table_without_insertable_columns.sql:3]: To test attach in Atomic databases

File: src/Interpreters/InterpreterCreateQuery.cpp [hunk 3]
```diff
@@ -731,10 +731,20 @@ ColumnsDescription InterpreterCreateQuery::getColumnsDescription(
...
         throw Exception(ErrorCodes::EMPTY_LIST_OF_COLUMNS_PASSED, "Cannot CREATE table without physical columns");
 
+    if (mode <= LoadingStrictnessLevel::SECONDARY_CREATE && !is_restore_from_backup && !hasInsertableColumns)
```
Comment (mstetsyuk) [inline src/Interpreters/InterpreterCreateQuery.cpp:745]:
```suggestion
    if (mode <= LoadingStrictnessLevel::CREATE && !is_restore_from_backup && !hasInsertableColumns)
```

I think we still want to execute secondary create?

Comment (mstetsyuk) [inline src/Interpreters/InterpreterCreateQuery.cpp]:
```suggestion
    if (mode <= LoadingStrictnessLevel::CREATE && !is_restore_from_backup && !hasInsertableColumns)
```

I assume we still want to be able to execute a secondary create?

Comment (mstetsyuk) [reply src/Interpreters/InterpreterCreateQuery.cpp]: Now that we allow secondary create of such tables, the change should not be backwards incompatible, correct? If so, I suggest we remove the `pr-backwards-incompatible` tag.

**Review by antaljanosbenjamin — APPROVED** [review]

**Review by mstetsyuk — APPROVED** [review]

File: src/Interpreters/InterpreterCreateQuery.cpp (hunk 3 above)
Comment (GrigoryPervakov) [reply src/Interpreters/InterpreterCreateQuery.cpp]: @mstetsyuk 
I have forgotten why I chose `SECONDARY_CREATE` here. It applied during alter table calls, so in such a case it is still possible to create table by deleting all insertable columns.

So I think it's better to revert this to CREATE, restores are handled, a replicated database would check it with CREATE, so all SECONDARY_CREATE on replicas should satisfy the condition.

File: src/Interpreters/InterpreterCreateQuery.cpp [hunk 4]
```diff
@@ -731,10 +731,12 @@ ColumnsDescription InterpreterCreateQuery::getColumnsDescription(
     if (mode <= LoadingStrictnessLevel::SECONDARY_CREATE && !is_restore_from_backup && context_->getSettingsRef()[Setting::flatten_nested])
         res.flattenNested();
 
-
     if (res.getAllPhysical().empty())
         throw Exception(ErrorCodes::EMPTY_LIST_OF_COLUMNS_PASSED, "Cannot CREATE table without physical columns");
 
+    if (mode <= LoadingStrictnessLevel::SECONDARY_CREATE && !is_restore_from_backup && res.getInsertable().empty())
```
Comment (mstetsyuk) [inline src/Interpreters/InterpreterCreateQuery.cpp]: This would still break adding new replicas to the cluster (which would break releases and horizontal scaling), right?

Comment (GrigoryPervakov) [reply src/Interpreters/InterpreterCreateQuery.cpp]: Yes, I forgot to change it back, fixed

File: tests/queries/0_stateless/03541_table_without_insertable_columns.sql [hunk 5]
```diff
@@ -0,0 +1,12 @@
+-- Tags: no-parallel, no-ordinary-database
+-- Tag no-parallel: static UUID
```
Comment (Algunenano) [inline tests/queries/0_stateless/03541_table_without_insertable_columns.sql:2]: You can use `no-flaky-check` instead. The test itself is parallel with any other test, just not with itself.

**Comment by ramazanpolat** [comment]
BUT WHY?

This was a feature, not a bug.

Although it may look like “having a non-insertable table,” that’s not actually the case. You could create a table, insert some data, and then make it non-insertable—which has its own use cases and valid reasons, the first being **freedom to use features as needed.**

This change feels unnecessary from a technical perspective, unintuitive for users, and reduces the overall completeness of the system.

Who would expect to create a table with only materialized columns and then be able to insert data into it?

It made sense to allow creating the table—why not let people use it the way they want?

**Practical use cases**:
* Some may want to **lock down writes** after an initial bootstrap of data.
* Others may use materialized columns to **enforce immutability** without relying on external logic.
* It can serve as a **lightweight safeguard** for preventing accidental inserts or updates.
* It supports **progressive schema evolution**: start with a regular column, insert data, then convert it to materialized once the schema stabilizes.
* For testing or debugging, this flexibility allows reproducing edge cases that would otherwise be impossible.

**Technical arguments**:
* **Consistency with ALTER semantics**: If ALTER TABLE allows converting between types or defaults, it should also allow converting a regular column into a materialized one after data is inserted.
* **Backward compatibility**: This used to work, and removing it silently breaks real-world use cases where people relied on the flexibility.
* **Principle of least surprise**: It’s natural to expect that a column can be promoted to MATERIALIZED after initialization, similar to adding constraints in SQL.
* **No inherent technical blocker**: There’s no fundamental engine limitation preventing this—it worked before. The restriction seems arbitrary.
* **Symmetry**: Since it’s possible to drop or modify a materialized column back into a regular one, the reverse should logically also be allowed.

Previously, it was possible to create a table, insert some data, and then modify a column to be materialized in order to **lock down any further write operations** until explicitly altering the columns again:
```sql
CREATE TABLE t0 ENGINE = Memory() AS SELECT materialize(123)::int AS x;
ALTER TABLE t0 MODIFY COLUMN x MATERIALIZED 0;
SELECT x FROM t0;
```

Now, this is no longer possible.
Even trying to circumvent it by adding a non-materialized column then dropping it is also forbidden.
```
ALTER TABLE t0 ADD COLUMN y int;
ALTER TABLE t0 MODIFY COLUMN x MATERIALIZED 0;
ALTER TABLE t0 DROP COLUMN y;
```

Also, the error message is somewhat misleading:
```
Received exception from server (version 25.8.2):
Code: 90. DB::Exception: Received from localhost:9000. DB::Exception: Cannot CREATE table without insertable columns. (EMPTY_LIST_OF_COLUMNS_PASSED)
(query: ALTER TABLE t0 MODIFY COLUMN x MATERIALIZED 0;)
```
