### PR TITLE
Don't parse beyond the quotes when reading UUIDs

### LINKED ISSUE #44668: Insert fails or succeeds depending on spaces in query string
**Describe what's wrong**
In my database 99.9% of insert queries work OK, but 0.1% fail with strange `DB::Exception: Cannot parse expression of type LowCardinality(String)` issue.

I reduced this to insert of 2 rows on fresh clickhouse instance with newly created table. Each row can be successfully inserted with separate insert in any order.

Investigating this issue leads to discovery that its success depends on adding additional spaces to insert query (with no changes to its data).

The SQL code is:
```
CREATE TABLE default.temp
(                                                                                                                                                                                                                                                        
 `id` UInt64,                                                                                                                                                                                                                                         
 `field1` UUID,       
 `field2` UUID,        
 `field3` Int64,
 `field4` Int64,                
 `field5` LowCardinality(String),
 `field6` FixedString(3),
 `field7` String,
 `field8` Nullable(UUID),
 `event_at` DateTime('UTC'),
 `order_id` Nullable(UUID),
 `identity` LowCardinality(String)
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(event_at)
ORDER BY (field1, event_at, field2, field5, id)
SETTINGS index_granularity = 8192;

-- Next insert query fails.
-- But if you add space instead of any of _ in 'dispatcher'_)_,_
-- this insert succeeds.
INSERT INTO temp (id, field1, field2, field3, field4, field5, field6, field7, field8, event_at, order_id, identity)
VALUES ('1011','1d83904a-c31d-4a6c-bbf0-217656b46444','1d83904a-c31d-4a6c-bbf0-217656b46444',-200,0,'FOO','BAR','','1d83904a-c31d-4a6c-bbf0-217656b46444','2022-12-18 03:14:56','','dispatcher'),('10112222334444','1d83904a-c31d-4a6c-bbf0-217656b46444','1d83904a-c31d-4a6c-bbf0-217656b46444',12300,0,'FOO','BAR','','1d83904a-c31d-4a6c-bbf0-217656b46444','2022-12-17 23:37:18','1d83904a-c31d-4a6c-bbf0-217656b46444','other');

select * from temp;
```

If you add a space to `'dispatcher'),(` part of query, e.g. `'dispatcher'), (` the query succeeds. With no spaces it fail with `DB::Exception: Cannot parse expression of type LowCardinality(String)`.

A link to reproducer: https://fiddle.clickhouse.com/d641646d-b467-49e0-b8d4-518da5af1105

**Does it reproduce on recent release?**

Yes. Locally in `clickhouse/clickhouse-server:22.12.1` docker on Linux x86_64 and in `latest` in fiddler at this moment.

**How to reproduce**

* Original found this in 21.12, but it is reproducible in clickhouse/clickhouse-server:22.12.1
* clichouse-client (originaly found in python aiochclient writing through clickhouse-bulk)
* No non-default settings
* Samples and queries are above.

**Expected behavior**

It is expected to run successfully as 99.9% of such requests and do not depend on adding spaces or newlines to query.

**Error message and/or stacktrace**

From fiddler:
```
Error on processing query: Code: 62. DB::Exception: Cannot parse expression of type LowCardinality(String) here: '1d83904a-c31d-4a6c-bbf0-217656b46444','1d83904a-c31d-4a6c-bbf0-217656b46444',12300,0,'FOO','BAR','','1d83904a-c31d-4a6c-bbf0-217656b46444','2022-12-17 23:37:18: While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (SYNTAX_ERROR) (version 22.12.1.1752 (official build))
(query:
INSERT INTO temp (id, field1, field2, field3, field4, field5, field6, field7, field8, event_at, order_id, identity)
VALUES ('1011','1d83904a-c31d-4a6c-bbf0-217656b46444','1d83904a-c31d-4a6c-bbf0-217656b46444',-200,0,'FOO','BAR','','1d83904a-c31d-4a6c-bbf0-217656b46444','2022-12-18 03:14:56','','dispatcher'),('10112222334444','1d83904a-c31d-4a6c-bbf0-217656b46444','1d83904a-c31d-4a6c-bbf0-217656b46444',12300,0,'FOO','BAR','','1d83904a-c31d-4a6c-bbf0-217656b46444','2022-12-17 23:37:18','1d83904a-c31d-4a6c-bbf0-217656b46444','other');)
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Don't parse beyond the quotes when reading UUIDs

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Closes https://github.com/ClickHouse/ClickHouse/issues/44668

### CODE REVIEW

File: src/DataTypes/Serializations/SerializationUUID.cpp [hunk 1]
```diff
@@ -44,10 +45,11 @@ void SerializationUUID::serializeTextQuoted(const IColumn & column, size_t row_n
 
 void SerializationUUID::deserializeTextQuoted(IColumn & column, ReadBuffer & istr, const FormatSettings &) const
 {
+    std::string quoted_string;
+    readQuotedStringWithSQLStyle(quoted_string, istr);
```
Comment (alexey-milovidov) [inline src/DataTypes/Serializations/SerializationUUID.cpp:49]: This looks wrong, SQL style escaping is unneeded for this method.

File: src/DataTypes/Serializations/SerializationUUID.cpp [hunk 2]
```diff
@@ -44,10 +45,11 @@ void SerializationUUID::serializeTextQuoted(const IColumn & column, size_t row_n
 
 void SerializationUUID::deserializeTextQuoted(IColumn & column, ReadBuffer & istr, const FormatSettings &) const
 {
+    std::string quoted_string;
```
Comment (alexey-milovidov) [inline src/DataTypes/Serializations/SerializationUUID.cpp:48]: Extra allocation.

File: src/DataTypes/Serializations/SerializationUUID.cpp [hunk 3]
```diff
@@ -44,10 +45,11 @@ void SerializationUUID::serializeTextQuoted(const IColumn & column, size_t row_n
...
+    readQuotedStringWithSQLStyle(quoted_string, istr);
     UUID x;
-    assertChar('\'', istr);
-    readText(x, istr);
-    assertChar('\'', istr);
+    ReadBufferFromString parsed_quoted_buffer(quoted_string);
+    readText(x, parsed_quoted_buffer);
```
Comment (alexey-milovidov) [inline src/DataTypes/Serializations/SerializationUUID.cpp:52]: Extra copy.

Comment (Algunenano) [reply src/DataTypes/Serializations/SerializationUUID.cpp:52]: I don't see it. AFAICS `ReadBufferFromString` will read directly from `quoted_string`, right?

File: src/DataTypes/Serializations/SerializationUUID.cpp (hunk 1 above)
Comment (Algunenano) [reply src/DataTypes/Serializations/SerializationUUID.cpp:49]: The following deserialization methods are using the same or a similar approach:
```
SerializationAggregateFunction
SerializationEnum
SerializationFixedString
SerializationObject
SerializationString
```

For example, `SerializationString` uses `readQuotedStringInto<true>` which will use `readAnyQuotedStringInto<'\'',true>`.
OTOH, `readQuotedStringWithSQLStyle` which is `readQuotedStringInto<true>`, so basically the same thing.

If Strings are being escaped, why shouldn't strings that represent UUIDs be escaped too?

File: src/DataTypes/Serializations/SerializationUUID.cpp (hunk 2 above)
Comment (Algunenano) [reply src/DataTypes/Serializations/SerializationUUID.cpp:48]: Yes, it needs somewhere to place the unquoted string. That's assuming we want to deal with quotes (which I thought necessary), otherwise we could look for the next quote, assume that's the end and try to parse the UUID from quote to quote.

**Comment by alexey-milovidov** [comment]
I'm concerned about performance degradation. Let's add a performance test.
Maybe we can use an approach similar to how we parse Date/DateTime?

**Comment by alexey-milovidov** [comment]
Let's look at the fuzzer error.
PS. https://aretestsgreenyet.com/

**Comment by Algunenano** [comment]
> I'm concerned about performance degradation. Let's add a performance test.
> Maybe we can use an approach similar to how we parse Date/DateTime?

My concern was whether Date/Datetime would be affected by the same problem; I didn't expend a lot on them but they seem to not accept quotes on them so they should be ok.

It makes sense to add a performance test. It might lead to a lot of potential changes once I get into that rabbit hole 🤔🤔🤔

**Comment by Algunenano** [comment]
I've also reported the fuzzer issue at https://github.com/ClickHouse/ClickHouse/issues/44695

**Comment by Algunenano** [comment]
Some notes about looking at the performance of parsing UUIDs:

- Adding a test for this isn't simple. Either you add a super long query (bad for size of the repo) or a small query (no noticeable impact since most of the time will be spent in other things), or add an asset for perf tests (like https://github.com/ClickHouse/ClickHouse/blob/4bf1443daecea075ca31de92285b65d0a59b66f5/docker/test/performance-comparison/download.sh#L23) which is out of my control and probably not worth the hassle just for this.

- To test this locally I've generated a file with 100M UUIDs:
```sql
Select * from generateRandom('u UUID') limit 100000000 INTO OUTFILE '/tmp/uuid_100m.values';
```

- Then either read it with clickhouse local or move it to user_files or your server to test. But note this is almost 4GB in size to showcase the slowness.

- Then just read it:
```sql
Select count() FROM file('uuid_100m.values', Values, 'u UUID');
```

- Timings:
  - Master: ~3.6 seconds
  - This PR as is: 6.1 seconds.
  - With further improvements*: 3.2 seconds

So now it's not slower but faster :scream: 

The further improvements include:
- Better UUID parsing from hex in general (not just this case).
- Add a fast path where we look for the end of the field (`'`) and if it's 32 char or 36 char go directly to the parse UUID functions, otherwise go to the slow path.

**Comment by yakov-olkhovskiy** [comment]
The original code seems to me a bit fishy - besides lacking search for quoted end (which this fix solves), it's also lacking any check for hex-correctness - which this fix doesn't solve. I would rather completely rewrite it for byte-by-byte parsing - it shouldn't be (much) slower than this solution and solve all other issues...

File: src/DataTypes/Serializations/SerializationUUID.cpp [hunk 4]
```diff
@@ -44,11 +45,44 @@ void SerializationUUID::serializeTextQuoted(const IColumn & column, size_t row_n
...
+
+    if (!fast)
+    {
+        String quoted_chars;
+        readQuotedStringInto<false>(quoted_chars, istr);
+        ReadBufferFromString parsed_quoted_buffer(quoted_chars);
+        readText(uuid, parsed_quoted_buffer);
+    }
+
+    assert_cast<ColumnUUID &>(column).getData().push_back(std::move(uuid)); /// It's important to do this at the end - for exception safety.
```
Comment (yakov-olkhovskiy) [inline src/DataTypes/Serializations/SerializationUUID.cpp:85]: maybe something like this?
```suggestion
    assertChar('\'', istr);

    UUID uuid;
    char * begin = reinterpret_cast<char *>(&uuid);
    char * pos = begin;
    bool high = true;
    bool delim = false;
    for (size_t n = 0; !istr.eof() && 16 > pos - begin; ++istr.position(), ++n)
    {
        if (*istr.position() == '\'')
            break;
        if (n == 8 && *istr.position() == '-')
        {
            delim = true;
            continue;
        }
        if (delim && (n == 12 || n == 16 || n == 20))
        {
            if (*istr.position() != '-')
                break;
            continue;
        }

        char c = unhex(*istr.position());
        if (c > 0x0f)
            throw ParsingException("Cannot parse UUID", ErrorCodes::CANNOT_PARSE_UUID);

        if (high)
            *pos = c << 4;
        else
        {
            *pos &= c;
            ++pos;
        }
        high = !high;
    }

    if (pos - begin != 16)
        throw ParsingException("Cannot parse UUID", ErrorCodes::CANNOT_PARSE_UUID);

    assertChar('\'', istr);

    assert_cast<ColumnUUID &>(column).getData().push_back(uuid);    /// It's important to do this at the end - for exception safety.
```

Comment (Algunenano) [reply src/DataTypes/Serializations/SerializationUUID.cpp:85]: 2 things:
- Performance of that is really bad. It goes from 3.3 seconds with the PR to 16.605 seconds, so it'd need to be really improved.
- I think it'd need to replace all `readText` / `readCSV` / `readUUIDTextImpl` and other read UUID functions in ReadHelpers, not just this implementation.

Tested with CH local:
```
Select * from generateRandom('u UUID') limit 100000000 INTO OUTFILE '/tmp/uuid_100m.values';
```

And then:
```
Select * from generateRandom('u UUID') limit 100000000 INTO OUTFILE '/tmp/uuid_100m.values';
```

Comment (Algunenano) [reply src/DataTypes/Serializations/SerializationUUID.cpp:85]: Would it make sense to merge this or something equivalent and then work on other PR to improve hex correctness (on all possible input formats of UUID)?

Comment (yakov-olkhovskiy) [reply src/DataTypes/Serializations/SerializationUUID.cpp:85]: wow, 16sec... interesting...
ok, I think it makes sense to merge your variant first

**Review by yakov-olkhovskiy — APPROVED** [review]

File: src/DataTypes/Serializations/SerializationUUID.cpp (hunk 4 above)
Comment (Algunenano) [reply src/DataTypes/Serializations/SerializationUUID.cpp:85]: Updated the comment above because I had pasted the sql to generate the file twice, instead of adding the benchmark query.

One idea about perf: it might be worth having this check only once in `parseUUID` and `parseUUIDWithoutSeparator` (or even in `parseHex`). Verifying that the whole string only includes some characters (0-9a-fA-F) should be much faster if done at once with a known size (as the compiler can and will likely introduce simd operations) rather than doing it char by char.

Comment (yakov-olkhovskiy) [reply src/DataTypes/Serializations/SerializationUUID.cpp:85]: yes, I think it's reasonable solution
Frankly it always was speed against reliability trade off... actually I have such byte-by-byte reader in IPv6 parser - now I'm thinking about improving it also...

**Comment by yakov-olkhovskiy** [comment]
@Algunenano do you want to change something or I can merge it?

**Comment by Algunenano** [comment]
> @Algunenano do you want to change anything or I can merge it?

No. I think it can be merged as is and other improvements can land in other PRs
