### PR TITLE
Fix Bug: DataLake hive catalog url parsing

### LINKED ISSUE #86018: std::exception with bad Hive credentials
### Describe the bug

Easy to reproduce. It seems to be missing input sanitization.

### How to reproduce

Run:

```sql
CREATE DATABASE d0 ENGINE = DataLakeCatalog('myminio', 'mypassword') SETTINGS catalog_type = 'hive', warehouse = 'myware', storage_endpoint = 'http://minio1:9001/d0';
SELECT 1 FROM merge(REGEXP('d0.*'), 't0'); --std::exception
```

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'std::exception. Code: 1001, type: std::invalid_argument, e.what() = stoi: no conversion (version 25.8.1.4768 (official build)), Stack trace:

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::logic_error::logic_error(char const*) @ 0x0000000027c6d434
1. contrib/llvm-project/libcxx/include/stdexcept:139: std::invalid_argument::invalid_argument[abi:se190107](char const*) @ 0x00000000129fbd09
2. contrib/llvm-project/libcxx/include/stdexcept:232: std::__throw_invalid_argument[abi:se190107](char const*) @ 0x0000000027c7325f
3. contrib/llvm-project/libcxx/src/string.cpp:63: long std::(anonymous namespace)::as_integer_helper<long, String, long (*)(char const*, char**, int) noexcept>(String const&, String const&, unsigned long*, int, long (*)(char const*, char**, int) noexcept) @ 0x0000000027c70bd2
4. contrib/llvm-project/libcxx/src/string.cpp:92: std::stoi(String const&, unsigned long*, int) @ 0x0000000027c6d877
5. src/Databases/DataLake/HiveCatalog.cpp:39: DataLake::(anonymous namespace)::parseHostPort(String const&) @ 0x000000001a51d4b7
6. src/Databases/DataLake/HiveCatalog.cpp:46: DataLake::HiveCatalog::HiveCatalog(String const&, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001a51d095
7. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::DatabaseDataLake::getCatalog() const @ 0x000000001a49f34b
8. src/Databases/DataLake/DatabaseDataLake.cpp:465: DB::DatabaseDataLake::getTablesIterator(std::shared_ptr<DB::Context const>, std::function<bool (String const&)> const&, bool) const @ 0x000000001a4a339a
9. src/Storages/StorageMerge.cpp:1414: DB::StorageMerge::DatabaseNameOrRegexp::getDatabaseIterator(String const&, std::shared_ptr<DB::Context const>) const @ 0x000000001e2878b4
10. src/Storages/StorageMerge.cpp:1444: DB::StorageMerge::DatabaseNameOrRegexp::getDatabaseIterators(std::shared_ptr<DB::Context const>) const @ 0x000000001e274eea
11. src/Storages/StorageMerge.cpp:268: DB::StorageMerge::getColumnsDescriptionFromSourceTablesImpl(std::shared_ptr<DB::Context const> const&, DB::StorageMerge::DatabaseNameOrRegexp const&, unsigned long, DB::IStorage const*) @ 0x000000001e2754ba
12. src/Storages/StorageMerge.cpp:208: DB::StorageMerge::getColumnsDescriptionFromSourceTables(std::shared_ptr<DB::Context const> const&) const @ 0x000000001e2742c3
13. src/Storages/StorageMerge.cpp:182: DB::StorageMerge::StorageMerge(DB::StorageID const&, DB::ColumnsDescription const&, String const&, String const&, bool, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001e274a8c
14. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: std::shared_ptr<DB::StorageMerge> std::allocate_shared[abi:se190107]<DB::StorageMerge, std::allocator<DB::StorageMerge>, DB::StorageID, DB::ColumnsDescription, String, String const&, bool const&, String const&, std::shared_ptr<DB::Context const>&, 0>(std::allocator<DB::StorageMerge> const&, DB::StorageID&&, DB::ColumnsDescription&&, String&&, String const&, bool const&, String const&, std::shared_ptr<DB::Context const>&) @ 0x0000000017867fa7
15. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:851: DB::(anonymous namespace)::TableFunctionMerge::executeImpl(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription, bool) const @ 0x0000000017867603
16. src/TableFunctions/ITableFunction.cpp:55: DB::ITableFunction::execute(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription, bool, bool) const @ 0x000000001964db43
17. src/Interpreters/Context.cpp:2615: DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::ITableFunction> const&) @ 0x000000001b08ee26
18. src/Analyzer/Resolve/QueryAnalyzer.cpp:5147: DB::QueryAnalyzer::resolveTableFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&, bool) @ 0x000000001a6d728e
19. src/Analyzer/Resolve/QueryAnalyzer.cpp:5586: DB::QueryAnalyzer::resolveQueryJoinTreeNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&) @ 0x000000001a6ff90d
20. src/Analyzer/Resolve/QueryAnalyzer.cpp:5850: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000001a6cbe45
21. src/Analyzer/Resolve/QueryAnalyzer.cpp:183: DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x000000001a6cadb6
22. src/Analyzer/Resolve/QueryAnalysisPass.cpp:18: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x000000001a6ca3ce
23. src/Analyzer/QueryTreePassManager.cpp:188: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x000000001a72f653
24. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:165: DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x000000001b2f73e7
25. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:182: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001b2f5b6d
26. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::make_unique[abi:se190107]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000001b2f8670
27. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001b284004
28. src/Interpreters/executeQuery.cpp:1496: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001b5ee506
29. src/Interpreters/executeQuery.cpp:1770: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001b5ea0c5
30. src/Server/TCPHandler.cpp:739: DB::TCPHandler::runImpl() @ 0x000000001ef3868f
31. src/Server/TCPHandler.cpp:2740: DB::TCPHandler::run() @ 0x000000001ef52524
```

### PR DESCRIPTION
**Pull request by rajatmohan22**
### Changelog category (leave one):
- Bug Fix 

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

 DataLake hive catalog url parsing with input sanitisation. Closes https://github.com/ClickHouse/ClickHouse/issues/86018

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/DataLake/HiveCatalog.cpp [hunk 1]
```diff
@@ -27,16 +27,41 @@ namespace
 
 std::pair<String, Int32> parseHostPort(const String & url)
 {
-    size_t last_slash = 0;
-    size_t last_points = 0;
-    for (size_t i = 0; i < url.size(); ++i)
+    size_t protocol_sep = url.find("://");
```
Comment (scanhex12) [inline src/Databases/DataLake/HiveCatalog.cpp]: Please add a test (please see `tests/integration/test_database_hms` for more details)

File: tests/integration/test_database_hms/test.py [hunk 2]
```diff
@@ -341,3 +341,116 @@ def record(key):
 
     assert 'aaa\naaa\naaa' == node.query(f"SELECT symbol FROM {CATALOG_NAME}.`{namespace}.{table_name}`").strip()
     assert 'bbb\nbbb\nbbb' == node.query(f"SELECT symbol FROM {CATALOG_NAME}.`{namespace}.{table_name_2}`").strip()
+
+def test_hive_catalog_url_parsing(started_cluster):
```
Comment (scanhex12) [inline tests/integration/test_database_hms/test.py:27]: I think the other tests are unnecessary, just leave this one.

File: tests/integration/test_database_hms/README_hive_catalog_url_parsing_tests.md [hunk 3]
```diff
@@ -0,0 +1,108 @@
+# Hive Catalog URL Parsing Tests
```
Comment (scanhex12) [inline tests/integration/test_database_hms/README_hive_catalog_url_parsing_tests.md]: Thanks for readme, but I think it's also redundant =)

File: tests/integration/test_database_hms/test.py (hunk 2 above)
Comment (rajatmohan22) [reply tests/integration/test_database_hms/test.py:27]: @scanhex12  I have removed all the other functions that test general hms catalog functionality and retained the test which just tests the url input sanitization

**Comment by rajatmohan22** [comment]
@scanhex12 should I remove the test.py integration test too?It seems to be failing and Unit test covers the functionality

**Comment by rajatmohan22** [comment]
@scanhex12 so we had this integration test - test.py that was failing

 The issue was that the test was trying to use this catalog_url setting that the DataLakeCatalog engine dont actually support  it was throwing "Unknown setting 'catalog_url'" error.

Tried to fix it. maybe URL needs to be passed as the first argument to the engine constructor, not as a setting. So instead of SETTINGS catalog_url = 'thrift://hive:9083', it should be DataLakeCatalog('thrift://hive:9083', 'minio', '[HIDDEN]')

any suggestions ?

**Comment by rajatmohan22** [comment]
@scanhex12 also do you want me to retain or get rid of the unit tests?

**Comment by rajatmohan22** [comment]
@scanhex12 all the tests have passed, can we merge?
Let me know if I have to get rid of the unit tests

but I do feel like they are necessary because test_hive_catalog_url_parsing.cpp provides immediate compilation validation and fast feedback during the build whereas  the integration test requires a full hms catalog server to start up

**Comment by rajatmohan22** [comment]
@PedroTadim The CI tests are successful. Can we merge ?

File: src/Databases/DataLake/tests/gtest_hive_catalog_url_parsing.cpp.bak [hunk 4]
```diff
@@ -0,0 +1,160 @@
+#include <Databases/DataLake/HiveCatalog.h>
```
Comment (PedroTadim) [inline src/Databases/DataLake/tests/gtest_hive_catalog_url_parsing.cpp.bak]: What is this file for?

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+    size_t port_end = (slash_pos != String::npos) ? slash_pos : url.size();
+    String port_str = url.substr(colon_pos + 1, port_end - colon_pos - 1);
+
+    if (port_str.empty() || !std::all_of(port_str.begin(), port_str.end(), ::isdigit))
+        throw DB::Exception(DB::ErrorCodes::DATALAKE_DATABASE_ERROR, "Invalid port number: '{}'", port_str);
+
+    try
+    {
+        Int32 port = std::stoi(port_str);
+        if (port <= 0 || port > 65535)
```
Comment (PedroTadim) [inline src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp:46]: Not sure if ports above 65535 is possible?

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+            throw DB::Exception(DB::ErrorCodes::DATALAKE_DATABASE_ERROR, "Port number out of valid range (1-65535): {}", port);
+        return {host, port};
+    }
+    catch (const std::out_of_range&)
+    {
+        throw DB::Exception(DB::ErrorCodes::DATALAKE_DATABASE_ERROR, "Port number too large: {}", port_str);
```
Comment (PedroTadim) [inline src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp]: Here you should throw the exception message

File: src/Databases/DataLake/tests/gtest_hive_catalog_url_parsing.cpp.bak (hunk 4 above)
Comment (rajatmohan22) [reply src/Databases/DataLake/tests/gtest_hive_catalog_url_parsing.cpp.bak]: I'm sorry for that, was moving files from one directory to another and forgot to delete backup

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp (hunk 5 above)
Comment (rajatmohan22) [reply src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp:46]: yes. Not possible. Added it for Input Validation to catch malformed input early

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp (hunk 6 above)
Comment (rajatmohan22) [reply src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp]: now the exception message is - Invalid port number format: {}

**Comment by rajatmohan22** [comment]
@PedroTadim  I have made the relevant changes!

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+class HiveCatalogUrlParsingTest : public ::testing::Test
+{
+protected:
+    void SetUp() override {}
+    void TearDown() override {}
+};
+
+std::pair<String, Int32> testParseHostPort(const String & url)
+{
+    size_t protocol_sep = url.find("://");
```
Comment (PedroTadim) [inline src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp]: Side question: Can we ignore the protocol being used?

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+{
+
+class HiveCatalogUrlParsingTest : public ::testing::Test
+{
+protected:
+    void SetUp() override {}
+    void TearDown() override {}
+};
+
+std::pair<String, Int32> testParseHostPort(const String & url)
```
Comment (PedroTadim) [inline src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp:21]: Don't we parse these URLs in the codebase elsewhere so that we can reuse code from another part or module?

Comment (rajatmohan22) [reply src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp:21]: Oh yes. I grepped and found out we use auto instead of size_t.
I have made those changes here to maintain similar pattern

File: src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp (hunk 7 above)
Comment (rajatmohan22) [reply src/Databases/DataLake/tests/test_hive_catalog_url_parsing.cpp]: Currently we validate the full URL format including protocol (like thrift://hive:9083) to ensure proper HMS catalog connection strings.
But if you prefer a protocol agnostic approach, we can do that as well.

**Comment by rajatmohan22** [comment]
@PedroTadim I have made the changes required do let me know, if anything else needs to be added

**Comment by PedroTadim** [comment]
LGTM!

**Comment by rajatmohan22** [comment]
Hello @PedroTadim 

I dont know why these CI tests keep failing, as far as my research goes this is unrelated to the code changes I made:


S3 Queue test failure - seems to be a documented flaky test issue from February 2024
RabbitMQ connection failures - These are infrastructure anf connection issues unrelated to the code changes
Stateless test exceptions - General test runner issues (?)

**Comment by PedroTadim** [comment]
> Hello @PedroTadim
> 
> I dont know why these CI tests keep failing, as far as my research goes this is unrelated to the code changes I made:
> 
> S3 Queue test failure - seems to be a documented flaky test issue from February 2024 RabbitMQ connection failures - These are infrastructure anf connection issues unrelated to the code changes Stateless test exceptions - General test runner issues (?)

These are flaky tests that we have to fix. You can merge your PR.
