### PR TITLE
Fix wrong database for JOIN w/o explicit database in distributed queries

### LINKED ISSUE #10471: Wrong DB used when Distribute table join Local table
There is a DB named "jrliu_test" I created before.
Then I connect to Clickhouse like this:
`clickhouse-client -m --database=jrliu_test`

Then I execute the followint SQLs:
1. create table "test_table_local"
`CREATE TABLE IF NOT EXISTS jrliu_test.test_table_local ON CLUSTER '{cluster}' (
	join_key String,
	value String
) ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY tuple();`

2. create table "test_table_distribute"
`CREATE TABLE jrliu_test.test_table_distribute ON CLUSTER '{cluster}' AS jrliu_test.test_table_local ENGINE = Distributed('{cluster}', 'jrliu_test', test_table_local);`

3. create table "test_table_join"
`CREATE TABLE IF NOT EXISTS jrliu_test.test_table_join ON CLUSTER '{cluster}' (
	join_key String,
	value String
) ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY tuple();`

4. insert data to "test_table_local" and "test_table_join"
`INSERT INTO jrliu_test.test_table_local FORMAT Values ('key1', 'value1'), ('key2', 'value2');`
`INSERT INTO jrliu_test.test_table_join FORMAT Values ('key1', 'value1'), ('key3', 'value3');`

5. execute query
5.1 execute Local table join Local table
`SELECT * FROM test_table_local as t INNER JOIN test_table_join as j ON t.join_key = j.join_key;`
(This query return result without any errors)
5.2 execute Distribute table join Local table
`SELECT * FROM test_table_distribute as t INNER JOIN test_table_join as j ON t.join_key = j.join_key;`
(This query return error: **_Code: 60, e.displayText() = DB::Exception: Received from clickhouse-stg-af-shard1-replica0:9000. DB::Exception: Table default.test_table_join doesn't exist.. (version 19.14.7.15 (official build))_**)

Table "test_table_join" should be found in "jrliu_test" database but not in "default". 

Server version: 19.14.7.15

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong database for JOIN w/o explicit database in distributed queries (Fixes: #10471)

### CODE REVIEW

File: src/Interpreters/AddDefaultDatabaseVisitor.h [hunk 1]
```diff
@@ -138,13 +154,17 @@ class AddDefaultDatabaseVisitor
...
-            auto qualified_identifier = std::make_shared<ASTTableIdentifier>(database_name, identifier.name());
-            if (!identifier.alias.empty())
-                qualified_identifier->setAlias(identifier.alias);
-            ast = qualified_identifier;
-        }
+        /// Already has database.
+        if (identifier.compound())
+            return;
+        /// There is temporary table with such name, should not be rewritten.
+        if (external_tables.count(identifier.shortName()))
```
Comment (vdimir) [inline src/Interpreters/AddDefaultDatabaseVisitor.h:161]:
```suggestion
        if (external_tables.contains(identifier.shortName()))
```

**Review by vdimir — APPROVED** [review]

File: src/Interpreters/AddDefaultDatabaseVisitor.h (hunk 1 above)
Comment (azat) [reply src/Interpreters/AddDefaultDatabaseVisitor.h:161]: Indeed, looks better, the reason I prefer to use `count` over `contains` is that before I have to remember about arcadia built that has pretty limited c++20 support, and `contains` wasn't supported, but anyway this is not relevant anymore.
