### PR TITLE
Fix postgres database engine possible incompatibility on upgrade

### LINKED ISSUE #36659: SQL creating PostgreSQL engine database incompatible after upgrade from 21.3lts to 22.3lts
**Describe the issue**
I am using Clickhouse 21.3lts and want to upgrade to clickhouse 22.3 lts.  
In Clickhouse 21.3lts,  I am using SQL like this to create a PostgreSQL engine database:
```
create database pg_db_metadata
engine = PostgreSQL('192.168.1.144:5432', 'db_metadata', 'admin', '123456', 1);
```

This will cause  a upgrade failure from clickhouse21.3lts to clickhouse22.3lts

Besides, this SQL will produce an error in Clickhouse 22.3lts.  

Also,  Part **Examples of Use** in doc https://clickhouse.com/docs/en/engines/database-engines/postgresql  will produce an error  when using ClickHouse22.3lts.

**How to reproduce**

1. In clickhouse21.3 lts, 
```
create database pg_db_metadata
engine = PostgreSQL('192.168.1.144:5432', 'db_metadata', 'admin', '123456', 1);
```
2. upgrade from 21.3lts to 22.3lts

**Error message and/or stacktrace**
Caught exception while loading metadata: Code: 170. DB:: Exception: Bad get: has UInt64, requested String: ......

**Additional context**
Backward compatibility.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix PostgreSQL database engine incompatibility on upgrade from 21.3 to 22.3. Closes https://github.com/ClickHouse/ClickHouse/issues/36659.

### CODE REVIEW

File: src/Databases/DatabaseFactory.cpp [hunk 1]
```diff
@@ -335,7 +335,13 @@ DatabasePtr DatabaseFactory::getImpl(const ASTCreateQuery & create, const String
             configuration.password = safeGetLiteralValue<String>(engine_args[3], engine_name);
 
             if (engine_args.size() >= 5)
-                configuration.schema = safeGetLiteralValue<String>(engine_args[4], engine_name);
+            {
+                auto arg_value = engine_args[4]->as<ASTLiteral>()->value;
+                if (arg_value.getType() == Field::Types::Which::String)
+                    configuration.schema = safeGetLiteralValue<String>(engine_args[4], engine_name);
+                else
+                    use_table_cache = safeGetLiteralValue<UInt8>(engine_args[4], engine_name);
```
Comment (antonio2368) [inline src/Databases/DatabaseFactory.cpp:343]: Maybe add a warning message that an old interface is used and that newer version should be preferred?

File: src/Databases/DatabaseFactory.cpp [hunk 2]
```diff
@@ -335,7 +335,13 @@ DatabasePtr DatabaseFactory::getImpl(const ASTCreateQuery & create, const String
...
+            }
         }
 
         if (engine_args.size() >= 6)
```
Comment (antonio2368) [inline src/Databases/DatabaseFactory.cpp:347]: we allow `('address', 'database', 'username', 'password', use_table_cache, use_table_cache)` now.
If you think that's okay I'm fine with it, pointing it out just in case.

**Review by antonio2368 — APPROVED** [review]
