### PR TITLE
Fix misbehavior of key analysis

### LINKED ISSUE #42456: Nested type LowCardinality cannot be inside Nullable type.
There is a difference in behavior between 22.3 and higher LTS version when it comes to the LowCardinality type.

Here are two reproducible examples that work in 22.3 but don't work in the above LTS versions (tried on 22.6, 22.8 and 22.10):

```
DROP TABLE test

create table test
(
Printer LowCardinality(String),
IntervalStart DateTime
)
engine = MergeTree()
PARTITION BY (hiveHash(Printer), toYear(IntervalStart))
ORDER BY (Printer, IntervalStart);

INSERT INTO test VALUES ('printer1', '2006-02-07 06:28:15');

SELECT Printer FROM test WHERE Printer='printer1';

Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Nested type LowCardinality(String) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT)
```

The second example is:

```
SET allow_suspicious_low_cardinality_types = 1;

create table test
(
Printer LowCardinality(UInt32),
IntervalStart DateTime
)
engine = MergeTree()
PARTITION BY (Printer % 128, toYear(IntervalStart))
ORDER BY (Printer, IntervalStart);

INSERT INTO test VALUES (10, '2006-02-07 06:28:15');

SELECT Printer FROM test WHERE Printer=10;

Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Nested type LowCardinality(UInt32) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT)
```

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect key analysis when key types cannot be inside Nullable. This fixes https://github.com/ClickHouse/ClickHouse/issues/42456.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/castColumn.cpp [hunk 1]
```diff
@@ -51,4 +51,14 @@ ColumnPtr castColumnAccurateOrNull(const ColumnWithTypeAndName & arg, const Data
     return castColumn<CastType::accurateOrNull>(arg, type);
 }
 
+ColumnPtr tryCastColumnAccurate(const ColumnWithTypeAndName & arg, const DataTypePtr & type)
+try
```
Comment (alexey-milovidov) [inline src/Interpreters/castColumn.cpp:55]: This introduces exceptions in a normal code path, which we don't allow.

Comment (alexey-milovidov) [reply src/Interpreters/castColumn.cpp:55]: Better to do `castColumnAccurateOrNull` and check for NULL.

Comment (alexey-milovidov) [reply src/Interpreters/castColumn.cpp:55]: But this is exactly what we did before...

Comment (alexey-milovidov) [reply src/Interpreters/castColumn.cpp:55]: We should make `castColumnAccurateOrNull` to work properly for `LowCardinality`.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/Interpreters/castColumn.cpp (hunk 1 above)
Comment (amosbird) [reply src/Interpreters/castColumn.cpp:55]: > We should make `castColumnAccurateOrNull` to work properly for `LowCardinality`.

But what type will it be? And what should we do for Arrays which also cannot be inside Nullable?

Comment (amosbird) [reply src/Interpreters/castColumn.cpp:55]: I guess we should use `castFieldAccurateOrNull` here.

Comment (alexey-milovidov) [reply src/Interpreters/castColumn.cpp:55]: Ok.

Comment (alexey-milovidov) [reply src/Interpreters/castColumn.cpp:55]: Also check `convertFieldToType`.

Comment (amosbird) [reply src/Interpreters/castColumn.cpp:55]: This becomes overly complicated.

1. We cannot use `convertFieldToType` because the Field type system is inaccurate. 
2. We cannot use castFieldAccurateOrNull because some types cannot be inside nullable.
3. We cannot introduce exceptions in a normal code path, because we don't allow.

Now I wonder, why can't we allow every type be inside Nullable?

Related issues:
https://github.com/ClickHouse/ClickHouse/issues/38738
https://github.com/ClickHouse/ClickHouse/issues/37881
https://github.com/ClickHouse/ClickHouse/issues/36894
https://github.com/ClickHouse/ClickHouse/issues/38786
https://github.com/ClickHouse/ClickHouse/issues/31440

and some more issues related with `join_uses_nulls`

Comment (amosbird) [reply src/Interpreters/castColumn.cpp:55]: I'll make `castColumnAccurateOrNull` to work properly for `LowCardinality` so that it fixes the related bug report. It's unlikely that user would use other non-nullable types as primary key. So maybe it's enough.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@amosbird an unrelated bug has been found by fuzzer: #42772

**Comment by filimonov** [comment]
Backport? Same were reported on 22.8
