### PR TITLE
Surrounding SELECT args with parentheses to avoid formatting inconsistency with EXCEPT

### LINKED ISSUE #90925: Inconsistent AST formatting of INSERT SELECT EXCEPT/INTERSECT
CI report: [BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90844&sha=9b729a31af206b6c6898921ece41545186a25091&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ0luY29uc2lzdGVudCBBU1QgZm9ybWF0dGluZzogdGhlIHF1ZXJ5OicKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0J1enpIb3VzZSAoYW1kX2RlYnVnKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAIL [Logical error: 'Inconsistent AST formatting: the query:]
  | Error:
  | Logical error: 'Inconsistent AST formatting: the query:
  | INSERT INTO t13 (c1, c2, c4, c3, c0) (SELECT t1d1.c2 + 'look' AS a0, a0 AS a1, exp10(a1)[2] AS a2, randomPrintableASCII(64), t1d1.c4 AS a4 FROM t9 AS t0d1 PASTE JOIN t9 AS t1d1 QUALIFY CAST('126228532...
  |         w0 AS (),
  |         w1 AS ()) INTERSECT ALL (SELECT map(-inf, CAST('14461152579428909443', 'Int16')) AS a7, a7, tuple(), CAST('10442924752350650183', 'Int64') AS a8, a8)
  | cannot parse query back from INSERT INTO TABLE `t13` (`c1`, `c2`, `c4`, `c3`, `c0`) SELECT ALL `t1d1`.`c2` + 'look' AS `a0`, `a0` AS `a1`, exp10(`a1`)[2] AS `a2`, randomPrintableASCII(64), (`t1d1`.`c4...
  | ---
  | 
  | Failed query:
  | INSERT INTO t13 (c1, c2, c4, c3, c0) (SELECT t1d1.c2 + 'look' AS a0, a0 AS a1, exp10(a1)[2] AS a2, randomPrintableASCII(64), t1d1.c4 AS a4 FROM t9 AS t0d1 PASTE JOIN t9 AS t1d1 QUALIFY CAST('126228532...
  | ---
  | 
  | Stack trace:
  | pthread_kill @ 0x00000000000969fd
  | raise @ 0x0000000000042476
  | __lgamma_r_finite@GLIBC_2.15 @ 0x00000000000287f3
  | src/Common/Exception.cpp:52: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x0000000015c4da3a
  | src/Common/Exception.cpp:85: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x0000000015c4e47...
  | src/Common/Exception.cpp:136: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015c4e7a5
  | src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d9894ce
  | src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d989011
  | src/Common/Exception.h:141: DB::Exception::Exception<String&, std::basic_string_view<char, std::char_traits<char>>&>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<s...
  | src/Interpreters/executeQuery.cpp:1221: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std...
  | src/Interpreters/executeQuery.cpp:1921: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c060052
  | src/Server/TCPHandler.cpp:765: DB::TCPHandler::runImpl() @ 0x000000001f56c2ea
  | src/Server/TCPHandler.cpp:2861: DB::TCPHandler::run() @ 0x000000001f586f64
  | base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000259d7fc7
  | base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000259d85a5
  | base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000025975c7f
  | base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000025973411
  | start_thread @ 0x0000000000094ac3
  | __GI___clone3 @ 0x00000000001268c0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

### PR DESCRIPTION
**Pull request by george-larionov**
Fixes #90925.

The problem is that there are 2 EXCEPTS, and also weird ways of writing SELECT queries, such as `SELECT (*) EXCEPT SELECT 1;`. The original fix for that query was to surround both SELECTs in parentheses, which was done [here](https://github.com/ClickHouse/ClickHouse/pull/79952). Unfortunately this caused the current issue, which is that something like:
`INSERT INTO tab2 SELECT * FROM tab EXCEPT SELECT * FROM tab;`
is formatted as:
`INSERT INTO tab2 (SELECT * FROM tab) EXCEPT (SELECT * FROM tab);`
which cannot be parsed again, since INSERT INTO expects a non-parenthesized SELECT after the table.

My solution is to surround the SELECT args in parentheses instead of the whole select (only for SELECTS that are part of an EXCEPT clause), like so:
`SELECT * EXCEPT SELECT 1` -> `SELECT (*) EXCEPT SELECT (1)`. This keeps this query valid, while not making the above INSERT query invalid.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Version info
- Merged into: `26.1.1.567`

### CODE REVIEW

**Comment by george-larionov** [comment]
Ready for review, test failures are unrelated to changes.

File: src/Parsers/ASTSelectWithUnionQuery.cpp [hunk 1]
```diff
@@ -77,24 +77,22 @@ void ASTSelectWithUnionQuery::formatQueryImpl(WriteBuffer & ostr, const FormatSe
                 << settings.nl_or_ws;
         }
 
-        bool need_parens = false;
-
         /// EXCEPT can be confused with the asterisk modifier:
         /// SELECT * EXCEPT SELECT 1 -- two queries
         /// SELECT * EXCEPT col      -- a modifier for asterisk
-        /// For this reason, add parentheses when formatting any side of EXCEPT.
+        /// For this reason, add parentheses around first args of SELECT when formatting any side of EXCEPT.
```
Comment (nickitat) [inline src/Parsers/ASTSelectWithUnionQuery.cpp]:
```suggestion
        /// For this reason, add parentheses around all args of SELECT when formatting any side of EXCEPT.
```
?

File: src/Parsers/ASTSelectQuery.cpp [hunk 2]
```diff
@@ -77,9 +77,14 @@ void ASTSelectQuery::formatImpl(WriteBuffer & ostr, const FormatSettings & s, Fo
...
+    /// If part of EXCEPT clause, surround SELECT args with parens to avoid formatting inconsistency
+    FormatStateStacked frame_nested = frame;
+    if (part_of_except_clause)
+        frame_nested.surround_each_list_element_with_parens = true;
+
     s.one_line
-        ? select()->format(ostr, s, state, frame)
-        : select()->as<ASTExpressionList &>().formatImplMultiline(ostr, s, state, frame);
+        ? select()->format(ostr, s, state, frame_nested)
+        : select()->as<ASTExpressionList &>().formatImplMultiline(ostr, s, state, frame_nested);
```
Comment (nickitat) [inline src/Parsers/ASTSelectQuery.cpp]:
```suggestion
    {
        /// If part of EXCEPT clause, surround SELECT args with parens to avoid formatting inconsistency
        FormatStateStacked frame_to_format = frame;
        if (part_of_except_clause)
            frame_to_format.surround_each_list_element_with_parens = true;
    
    s.one_line
            ? select()->format(ostr, s, state, frame_to_format)
            : select()->as<ASTExpressionList &>().formatImplMultiline(ostr, s, state, frame_to_format);
    }
```

**Review by nickitat — APPROVED** [review]

**Comment by nickitat** [comment]
@george-larionov it won't merge automatically

**Comment by george-larionov** [comment]
> @george-larionov it won't merge automatically

I was being optimistic :)

**Comment by evillique** [comment]
This PR broke test_shared_catalog in private.

I tried investigating it to figure out where the bug is, but so far I've gotten nowhere in solving it, so to avoid having a broken master, let's revert and continue the investigation in resubmit.

File: src/Parsers/ASTSelectWithUnionQuery.cpp [hunk 3]
```diff
@@ -77,24 +77,22 @@ void ASTSelectWithUnionQuery::formatQueryImpl(WriteBuffer & ostr, const FormatSe
...
-        /// For this reason, add parentheses when formatting any side of EXCEPT.
+        /// For this reason, add parentheses around all args of SELECT when formatting any side of EXCEPT.
         ASTs::const_iterator next = it;
         ++next;
         if ((it != list_of_selects->children.begin() && is_except(get_mode(it)))
             || (next != list_of_selects->children.end() && is_except(get_mode(next))))
-            need_parens = true;
+        {
+            if (auto * select = typeid_cast<ASTSelectQuery *>(it->get()))
+                select->part_of_except_clause = true;
```
Comment (evillique) [inline src/Parsers/ASTSelectWithUnionQuery.cpp:90]: My current suspicion is that, considering we have Visitors who sometimes change the structure of SELECTs, using AST member fields to place temporary formatting info looks incorrect.

Comment (george-larionov) [reply src/Parsers/ASTSelectWithUnionQuery.cpp:90]: Thanks for investigating, I will take a look
