### PR TITLE
Fix ~7 bugs in KeyCondition

### LINKED ISSUE #86696: Different behaviour between tuple IN and list of AND OR
### Company or project name

_No response_

### Question

Why do these operate differently? 

https://fiddle.clickhouse.com/41251762-2b04-4f36-8cd0-dccaef70324e

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed sometimes missing columns in EXPLAIN indexes=1 output. Resolves #86696

### Details
There were quite a few bugs and quirks in printing KeyCondition for EXPLAIN queries:
 * When an RPNElement involves a tuple of multiple columns, only one of those columns was printed. E.g. `(x, y) IN (...)` was printed as `y in ...`, and `pointInPolygon((x, y), ...)` was printed as `x in [...]`.
 * Similarly, only one column of the tuple was included in the `Keys:` list.
 * The way `pointInPolygon` condition was printed seems confusing: `x in [(0, 0), (0, 150), (150, 150), (150, 0), (0, 0)]` - there's no indication that it's a polygon.
 * For monotonic function chain, constant args were printed in reverse order: `plus(minus(x, 1), 10)` turned into `plus(minus(x, 10), 1)`.
 * Function chain for `IN` was not printed at all: `plus(x, 1) in (10)` turned into `x in 1-element set`.

Also non-EXPLAIN bugs:
 * KeyCondition allowed space-filling curve arguments to be wrapped in monotonic functions, but then ignored those functions when checking the condition. Could produce incorrect query results.
 * If a key column is used in the `IN` tuple multiple times, KeyCondition could relax the condition without settings `relaxed` to true. This can probably break partition pruning in some contrived queries.

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Conflicts with https://github.com/ClickHouse/ClickHouse/pull/86971. I think the merge conflicts were quite straightforward.

**Comment by nikitamikhaylov** [comment]
The indentation changed here: https://github.com/ClickHouse/ClickHouse/pull/87543

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 1]
```diff
@@ -3168,22 +3137,23 @@ BoolMask KeyCondition::checkInHyperrectangle(
         else if (element.function == RPNElement::FUNCTION_IN_RANGE
                  || element.function == RPNElement::FUNCTION_NOT_IN_RANGE)
         {
-            if (element.key_column >= hyperrectangle.size())
+            size_t key_column = element.getKeyColumn();
+            if (key_column >= hyperrectangle.size())
             {
                 throw Exception(ErrorCodes::LOGICAL_ERROR,
                                 "Hyperrectangle size is {}, but requested element at posittion {} ({})",
```
Comment (nikitamikhaylov) [inline src/Storages/MergeTree/KeyCondition.cpp]:
```suggestion
                                "Hyperrectangle size is {}, but requested element at position {} ({})",
```

**Review by nikitamikhaylov — APPROVED** [review]
