### PR TITLE
Fix: Invalid number of rows in Chunk column Object

### LINKED ISSUE #51204: AST Fuzzer: Invalid number of rows in Chunk column Object position 2: expected 1, got 0
**Describe the bug**
[A link to the report](https://s3.amazonaws.com/clickhouse-test-reports/0/96b2908f419d3d85f1598df4fe4528e105044534/fuzzer_astfuzzerasan/report.html)

**How to reproduce**
```sql
SELECT '0.02' GROUP BY GROUPING SETS (('6553.6'), (CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')')))
```
Stack
```
2023.06.20 16:07:17.126948 [ 532 ] {b85bf966-e63a-4f6d-a719-9c58db2b59b7} <Fatal> : Logical error: 'Invalid number of rows in Chunk column Object position 2: expected 1, got 0'.
2023.06.20 16:07:17.127761 [ 537 ] {} <Fatal> BaseDaemon: ########################################
2023.06.20 16:07:17.127878 [ 537 ] {} <Fatal> BaseDaemon: (version 23.6.1.1 (official build), build id: B131DB96CDF9195C03C1AAB3E91FDFAF343467C5, git hash: 96b2908f419d3d85f1598df4fe4528e105044534) (from thread 532) (query_id: b85bf966-e63a-4f6d-a719-9c58db2b59b7) (query: SELECT '0.02' GROUP BY GROUPING SETS (('6553.6'), (CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')')))) Received signal Aborted (6)
2023.06.20 16:07:17.127969 [ 537 ] {} <Fatal> BaseDaemon: 
2023.06.20 16:07:17.128049 [ 537 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fd6ce7ea00b 0x00007fd6ce7c9859 0x0000561ecabc0512 0x0000561ecabc13bd 0x0000561eb821ecdb 0x0000561ee218f38f 0x0000561ee290dca0 0x0000561ed366aa1e 0x0000561ee21b04cd 0x0000561ee21fd6ee 0x0000561ee21dfc45 0x0000561ee21e2782 0x0000561ecae69510 0x0000561ecae73bee 0x0000561ecae60b71 0x0000561ecae6d90d 0x00007fd6ce9a1609 0x00007fd6ce8c6133
2023.06.20 16:07:17.128152 [ 537 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x00007fd6ce7ea00b in ?
2023.06.20 16:07:17.128234 [ 537 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007fd6ce7c9859 in ?
2023.06.20 16:07:17.314505 [ 537 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:42: DB::abortOnFailedAssertion(String const&) @ 0x0000000024894512 in /workspace/clickhouse
2023.06.20 16:07:17.499298 [ 537 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/./src/Common/Exception.cpp:65: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
2023.06.20 16:07:17.499428 [ 537 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000248953bd in /workspace/clickhouse
2023.06.20 16:07:27.303958 [ 537 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x0000000011ef2cdb in /workspace/clickhouse
2023.06.20 16:07:27.357832 [ 537 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Processors/Chunk.cpp:73: DB::Chunk::checkNumRowsIsConsistent() @ 0x000000003be6338f in /workspace/clickhouse
2023.06.20 16:07:27.417911 [ 537 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:580: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::data[abi:v15000]() const
2023.06.20 16:07:27.418019 [ 537 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:760: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::__annotate_delete[abi:v15000]() const
2023.06.20 16:07:27.418075 [ 537 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:431: ~vector
2023.06.20 16:07:27.418119 [ 537 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:25: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x000000003c5e1ca0 in /workspace/clickhouse
2023.06.20 16:07:27.569438 [ 537 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__utility/swap.h:35: std::enable_if<is_move_constructible<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value && is_move_assignable<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value, void>::type std::swap[abi:v15000]<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>(COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&)
2023.06.20 16:07:27.569555 [ 537 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:1950: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::swap(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
2023.06.20 16:07:27.569613 [ 537 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/./src/Processors/Chunk.h:64: DB::Chunk::swap(DB::Chunk&)
2023.06.20 16:07:27.569658 [ 537 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x000000002d33ea1e in /workspace/clickhouse
2023.06.20 16:07:27.657666 [ 537 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x000000003be844cd in /workspace/clickhouse
2023.06.20 16:07:27.687805 [ 537 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2023.06.20 16:07:27.687890 [ 537 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x000000003bed16ee in /workspace/clickhouse
2023.06.20 16:07:27.801095 [ 537 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000003beb3c45 in /workspace/clickhouse
2023.06.20 16:07:27.937597 [ 537 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:351: operator()
2023.06.20 16:07:27.937723 [ 537 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.06.20 16:07:27.937792 [ 537 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.06.20 16:07:27.937853 [ 537 ] {} <Fatal> BaseDaemon: 14.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]()
2023.06.20 16:07:27.937899 [ 537 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000003beb6782 in /workspace/clickhouse
2023.06.20 16:07:28.064175 [ 537 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:0: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000024b3d510 in /workspace/clickhouse
2023.06.20 16:07:28.161750 [ 537 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Common/ThreadPool.h:230: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x0000000024b47bee in /workspace/clickhouse
2023.06.20 16:07:28.272016 [ 537 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x0000000024b34b71 in /workspace/clickhouse
2023.06.20 16:07:28.414105 [ 537 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
2023.06.20 16:07:28.414238 [ 537 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.06.20 16:07:28.414289 [ 537 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x0000000024b4190d in /workspace/clickhouse
2023.06.20 16:07:28.414341 [ 537 ] {} <Fatal> BaseDaemon: 19. ? @ 0x00007fd6ce9a1609 in ?
2023.06.20 16:07:28.414391 [ 537 ] {} <Fatal> BaseDaemon: 20. clone @ 0x00007fd6ce8c6133 in ?
2023.06.20 16:07:29.255737 [ 537 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 45D619A4FEBF58697637DC371E0C8650)
2023.06.20 16:07:40.475407 [ 537 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.06.20 16:07:40.475642 [ 537 ] {} <Fatal> BaseDaemon: Changed settings: receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, distributed_product_mode = 'local', table_function_remote_max_addresses = 200, prefer_global_in_and_join = true, max_execution_time = 10., max_memory_usage = 10000000000, enable_optimize_predicate_expression = false, allow_introspection_functions = true, mutations_sync = 1, optimize_functions_to_subcolumns = true, allow_experimental_object_type = true
2023.06.20 16:08:15.041493 [ 151 ] {} <Fatal> Application: Child process was terminated by signal 6.

### PR DESCRIPTION
**Pull request by devcrafter**
Close https://github.com/ClickHouse/ClickHouse/issues/51204

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 2b8238786e4e8f649e3bdffcf4f373dcbe54617e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51296/2b8238786e4e8f649e3bdffcf4f373dcbe54617e/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by devcrafter** [comment]
We're trying to insert default values in the Object column, which doesn't have any subcolumns. From a logical POV, we can't do it
@CurtizJ probably, you have some thoughts regarding it

<pre>
2023.06.27 12:44:13.656739 [ 1063772 ] {fc2ec0f0-ac99-4f08-beee-a41585b72631} <Error> executeQuery: Code: 49. DB::Exception: ColumnObject is inconsistent: it has no subcolumns, but has 1 rows. (LOGICAL_ERROR) (version 23.6.1.1) (from 127.0.0.1:33680) (in query:  SELECT '0.02' GROUP BY GROUPING SETS (('6553.6'), (CAST('{"x" : 1}', 'Object(\'json\')'))) settings max_threads=1), Stack trace (when copying this message, always in
clude the lines below):

0. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x000000001ade4b42 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
1. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x000000001ade4b0d in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
2. /home/ubuntu/git/ClickHouse/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x00000000341f0000 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
3. /home/ubuntu/git/ClickHouse/src/Common/Exception.cpp:90: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000024375aee in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
4. /home/ubuntu/git/ClickHouse/src/Common/Exception.h:54: DB::Exception::Exception(String&&, int, bool) @ 0x000000001add8b2a in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
5. /home/ubuntu/git/ClickHouse/src/Common/Exception.h:81: DB::Exception::Exception<unsigned long const&>(int, FormatStringHelperImpl<std::type_identity<unsigned long const&>::type>, unsigned long const&) @ 0x000000001b563993 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
6. /home/ubuntu/git/ClickHouse/src/Columns/ColumnObject.cpp:630: DB::ColumnObject::checkConsistency() const @ 0x000000002d8a4006 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
<b><i>7. /home/ubuntu/git/ClickHouse/src/Columns/ColumnObject.cpp:729: DB::ColumnObject::insertDefault() @ 0x000000002d8a5cfa in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse</i></b>
8. /home/ubuntu/git/ClickHouse/src/DataTypes/IDataType.cpp:171: DB::IDataType::insertDefaultInto(DB::IColumn&) const @ 0x000000002bce44fd in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
9. /home/ubuntu/git/ClickHouse/src/Processors/QueryPlan/AggregatingStep.cpp:321: DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_0::operator()(std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>) const @ 0x000000002f20a069 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
10. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_0&>()(std::declval<std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>>())) std::__invoke[abi:v15000]<DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSet
tings const&)::$_0&, std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>>(DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_0&, std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>&&) @ 0x000000002f208de9 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
11. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:470: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> std::__invoke_void_return_wrapper<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, false>::__call<DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSetting
s const&)::$_0&, std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>>(DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_0&, std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>&&) @ 0x000000002f208d88 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
12. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_0, std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)>::operator()[abi:v15000]
(std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>&&) @ 0x000000002f208d48 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
13. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> std::__function::__policy_invoker<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)>::__call_impl<std::__function::__default_allo
c_func<DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_0, std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)>>(std::__function::__policy_storage const*, std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>&&) @ 0x000000002f208d13 in /home/ubuntu/git/Cl
ickHouse/debug/programs/clickhouse
14. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)>::operator()[abi:v15000](std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>&&) const @ 0x000000002bb66ee9 in /home/ubuntu/git/Click
House/debug/programs/clickhouse
15. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:0: std::function<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)>::operator()(std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>) const @ 0x000000002bb549e0 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
16. /home/ubuntu/git/ClickHouse/src/QueryPipeline/Pipe.cpp:781: DB::Pipe::transform(std::function<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)> const&, bool) @ 0x000000002bb517a2 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
17. /home/ubuntu/git/ClickHouse/src/QueryPipeline/QueryPipelineBuilder.cpp:167: DB::QueryPipelineBuilder::transform(std::function<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>> (std::vector<DB::OutputPort*, std::allocator<DB::OutputPort*>>)> const&, bool) @ 0x000000002bb7ef1d in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
18. /home/ubuntu/git/ClickHouse/src/Processors/QueryPlan/AggregatingStep.cpp:208: DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x000000002f2059bd in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
19. /home/ubuntu/git/ClickHouse/src/Processors/QueryPlan/ITransformingStep.cpp:0: DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000002f273107 in /home/ubuntu/git/ClickHouse/debug/pr
ograms/clickhouse
20. /home/ubuntu/git/ClickHouse/src/Processors/QueryPlan/QueryPlan.cpp:189: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x000000002f29865f in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
21. /home/ubuntu/git/ClickHouse/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:379: DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000002d14afeb in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
22. /home/ubuntu/git/ClickHouse/src/Interpreters/executeQuery.cpp:723: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000002d608637 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
23. /home/ubuntu/git/ClickHouse/src/Interpreters/executeQuery.cpp:1182: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x000000002d603cc4 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
24. /home/ubuntu/git/ClickHouse/src/Server/TCPHandler.cpp:420: DB::TCPHandler::runImpl() @ 0x000000002eacff0d in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
25. /home/ubuntu/git/ClickHouse/src/Server/TCPHandler.cpp:2043: DB::TCPHandler::run() @ 0x000000002eae1b25 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
26. /home/ubuntu/git/ClickHouse/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000003402bf59 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
27. /home/ubuntu/git/ClickHouse/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000003402c79c in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
28. /home/ubuntu/git/ClickHouse/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x000000003426dab4 in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
29. /home/ubuntu/git/ClickHouse/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000003426a85a in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
30. /home/ubuntu/git/ClickHouse/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000003426955e in /home/ubuntu/git/ClickHouse/debug/programs/clickhouse
31. ? @ 0x00007f7bc9e94b43 in ?
</pre>

File: src/Columns/ColumnObject.cpp [hunk 1]
```diff
@@ -626,6 +626,9 @@ ColumnObject::ColumnObject(Subcolumns && subcolumns_, bool is_nullable_)
 
 void ColumnObject::checkConsistency() const
 {
+    if (num_rows && subcolumns.empty())
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "ColumnObject is inconsistent: it has no subcolumns, but has {} rows", num_rows);
```
Comment (CurtizJ) [inline src/Columns/ColumnObject.cpp:630]: Actually this assertion is wrong because such situation is normal. Consider the following data: `{} {"key1": "value1"}`. In this case we have to insert default value with no subcolumns for first object to preserve correct number of of rows and then to fill first row of subcolumn for `key1` with default value. If there were no subcolumns at the end of processing the dummy subcolum is added because we cannot have empty tuples (see `ColumnObject::finalize`).

**Review by CurtizJ — APPROVED** [review]

**Comment by tavplubix** [comment]
Stateless tests flaky check (asan) — fail: 1
