### PR TITLE
fix a crash when delete a statistics and load it again

### LINKED ISSUE #91206: Another crash in getConditionSelectivityEstimator
### Describe the bug

Seems not related to https://github.com/ClickHouse/ClickHouse/issues/90626, the stack trace is slightly different. cc @hanfei1991 it uses ALTER MODIFY STATISTICS, so maybe related to recent changes there?

### How to reproduce

On a debug build run:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() ORDER BY tuple();
SET query_plan_enable_optimizations = 0;
ALTER TABLE t0 MODIFY STATISTICS c0 TYPE Uniq, CountMin;
INSERT INTO TABLE t0 (c0) VALUES (1);
ALTER TABLE t0 MODIFY STATISTICS c0 TYPE CountMin;
ALTER TABLE t0 APPLY DELETED MASK IN PARTITION ID '1';
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'std::exception. Code: 1001, type: std::length_error, e.what() = vector, Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::logic_error::logic_error(char const*) @ 0x0000000029fe8db4
1. contrib/llvm-project/libcxx/include/stdexcept:154: std::length_error::length_error[abi:se210105](char const*) @ 0x000000000d985fc9
2. contrib/llvm-project/libcxx/include/stdexcept:243: std::__throw_length_error[abi:se210105](char const*) @ 0x000000000d985f5f
3. contrib/llvm-project/libcxx/include/__vector/vector.h:777: ? @ 0x000000000efcd60d
4. contrib/llvm-project/libcxx/include/__vector/vector.h:903: ? @ 0x0000000015cdfa23
5. contrib/llvm-project/libcxx/include/__vector/vector.h:1361: DB::StatisticsCountMinSketch::deserialize(DB::ReadBuffer&) @ 0x000000001f250631
6. src/Storages/Statistics/Statistics.cpp:270: DB::ColumnStatistics::deserialize(DB::ReadBuffer&) @ 0x000000001f24afd1
7. src/Storages/MergeTree/IMergeTreeDataPart.cpp:918: DB::IMergeTreeDataPart::loadStatistics() const @ 0x000000001ed00014
8. src/Storages/MergeTree/MergeTreeData.cpp:847: DB::MergeTreeData::getConditionSelectivityEstimator(DB::RangesInDataParts const&, std::shared_ptr<DB::Context const>) const @ 0x000000001edcbbd7
9. src/Interpreters/InterpreterSelectQuery.cpp:821: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>)::$_0::operator()(bool) const @ 0x000000001bd0f055
10. src/Interpreters/InterpreterSelectQuery.cpp:948: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x000000001bd0ad70
11. src/Interpreters/InterpreterSelectQuery.cpp:505: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x000000001bd0713f
12. src/Interpreters/InterpreterSelectQuery.cpp:346: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryOptions const&) @ 0x000000001bd0da35
13. src/Interpreters/MutationsInterpreter.cpp:1633: DB::MutationsInterpreter::validate() @ 0x000000001bd9f7ce
14. src/Interpreters/InterpreterAlterQuery.cpp:294: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x000000001bc6f579
15. src/Interpreters/InterpreterAlterQuery.cpp:85: DB::InterpreterAlterQuery::execute() @ 0x000000001bc6becd
16. src/Interpreters/executeQuery.cpp:1700: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001c07f5ad
17. src/Interpreters/executeQuery.cpp:1921: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c07a0d2
18. src/Server/TCPHandler.cpp:765: DB::TCPHandler::runImpl() @ 0x000000001f58b46a
19. src/Server/TCPHandler.cpp:2861: DB::TCPHandler::run() @ 0x000000001f5a60e4
20. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000259fbdc7
21. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000259fc3a5
22. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000025999a7f
23. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000025997211
24. ? @ 0x00000000000a3d64
25. __clone3 @ 0x00000000001373bc
 (version 25.12.1.244 (official build))'.
```

### PR DESCRIPTION
**Pull request by hanfei1991**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
fix https://github.com/ClickHouse/ClickHouse/issues/91206
when we create a table with statistics and write someting and drop one statistics, it will crash when we read it again. because we assume the serialize and deserialize will have same types statistics. In this fix, we will check if the current metadata contains the serialized statistics, if not, we make a mock statistics and deserialize only to skip it. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by evillique — APPROVED** [review]

File: tests/queries/0_stateless/03743_fix_estimator_crash.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+-- Tags: no-fasttest
+
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03743_fix_estimator_crash.sql:2]: Can we please add a reference to the solved bug and a brief comment what the test is supposed to test (i.e. expected behavior). Someone reading this in a few weeks from now will be confused otherwise.
