### PR TITLE
Fix dropping named collection in local storage

### LINKED ISSUE #66596: Cannot drop named collection
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

Cannot drop named collection on macOS latest build (24.6.2.17 (official build))

**How to reproduce**

```
yaroslav@Yaroslavs-MacBook-Pro testing % sudo -u yaroslav ./clickhouse-macos client
ClickHouse client version 24.6.2.17 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.6.2.

Warnings:
 * Maximum number of threads is lower than 30000. There could be problems with handling a lot of simultaneous queries.

Yaroslavs-MacBook-Pro.local :) CREATE NAMED COLLECTION `MYSQL_CREDIT_PROCESS_TRANSACTION_DATA` AS
user = 'myusername';

CREATE NAMED COLLECTION MYSQL_CREDIT_PROCESS_TRANSACTION_DATA AS user = 'myusername'

Query id: d08f75d4-a72e-4638-9c83-4941b35a75ca

Ok.

0 rows in set. Elapsed: 0.004 sec.

Yaroslavs-MacBook-Pro.local :) DROP NAMED COLLECTION `MYSQL_CREDIT_PROCESS_TRANSACTION_DATA`

DROP NAMED COLLECTION MYSQL_CREDIT_PROCESS_TRANSACTION_DATA

Query id: 14d1e39e-7578-45d5-a5d3-921cabfe3973


Elapsed: 0.052 sec.

Received exception from server (version 24.6.2):
Code: 669. DB::Exception: Received from localhost:9000. DB::Exception: Cannot remove `MYSQL_CREDIT_PROCESS_TRANSACTION_DATA.sql`, because it doesn't exist. (NAMED_COLLECTION_DOESNT_EXIST)
```

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
It was introduced in https://github.com/ClickHouse/ClickHouse/pull/64574. Closes https://github.com/ClickHouse/ClickHouse/issues/66596.
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix removing named collections in local storage.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by yariks5s — APPROVED** [review]

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 1c52ea4b1a1a820dae6fe931d7029dc061c80482 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66599/1c52ea4b1a1a820dae6fe931d7029dc061c80482/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66586/e8627601b52e28a4d4203cd365cd5e4693e2af57/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Common/NamedCollections/NamedCollectionsMetadataStorage.cpp [hunk 1]
```diff
@@ -150,22 +150,22 @@ class NamedCollectionsMetadataStorage::LocalStorage : public INamedCollectionsSt
...
 
-        fs::rename(tmp_path, getPath(path));
+        fs::rename(tmp_path, getPath(file_name));
     }
 
-    void remove(const std::string & path) override
+    void remove(const std::string & file_name) override
     {
-        if (!removeIfExists(getPath(path)))
+        if (!removeIfExists(file_name))
```
Comment (antaljanosbenjamin) [inline src/Common/NamedCollections/NamedCollectionsMetadataStorage.cpp:158]: This is the bugfix: `getPath` is called also in `removeIfExists`, so no need to call that here.

**Comment by antaljanosbenjamin** [comment]
So there are some questions about why this wasn't caught by any test in our CI. I opened an other [PR](https://github.com/ClickHouse/ClickHouse/pull/66614) to figure that out. Until we figure it out, I don't want add any tests, because it might not test what I want. OTOH I like to get this PR merged as soon as possible, so I swear I tested it locally, but feel free to double check. I will merge this PR without tests, but will add tests in a separare PR.

File: src/Common/NamedCollections/NamedCollectionsMetadataStorage.cpp [hunk 2]
```diff
@@ -150,28 +150,32 @@ class NamedCollectionsMetadataStorage::LocalStorage : public INamedCollectionsSt
...
 
 private:
-    std::string getPath(const std::string & path) const
+    std::string getPath(const std::string & file_name) const
     {
-        return fs::path(root_path) / path;
+        const auto file_name_as_path = fs::path(file_name);
+        if (file_name_as_path.is_absolute())
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Filename {} cannot be an absolute path!", file_name);
+
```
Comment (antaljanosbenjamin) [inline src/Common/NamedCollections/NamedCollectionsMetadataStorage.cpp:177]: I won't write a test because in CI we usually use absolute paths, so it would require a lot of fiddleing. In the other hand @antonio2368 came up with the idea of this extra check. This should be fine and check the issues with absolute paths.

This means:
1. if we use absolute path in config and make a similar mistatke: this check will fail
2. if we don't use absolute in config, then the already existing tests will fail

**Comment by antaljanosbenjamin** [comment]
- Bugfix validation: no new tests
- Perf test of `agg_functions_min_max_any`: no changes there, it is just flaky
- stress test: https://github.com/ClickHouse/ClickHouse/issues/66122
- `01275_parallel_mv` https://github.com/ClickHouse/ClickHouse/issues/66116
