### PR TITLE
Move connection drain from prepare to work

### LINKED ISSUE #60844: A query may stuck in RemoteQueryExecutor::finish()
clickhouse version 23.12.1

**Describe what's wrong**
A distribute query with limit can't finish as expected.
```
SELECT
    main_brand_cd,
    uniqCombined(user_log_acct) AS deal_user_qtty_aggr
FROM app.app_s01_user_ord_det_snapshot_day_cate_1_d
WHERE (dt >= '2023-11-01') AND (dt <= '2023-11-30') 
GROUP BY main_brand_cd
LIMIT 1

Query id: 2d73ba58-de43-471f-902e-c5ce3c18fd19

┌─main_brand_cd─┬─deal_user_qtty_aggr─┐
│ 920842        │                  13 │
└───────────────┴─────────────────────┘
↓ Progress: 686.84 million rows, 57.03 GB (1.29 billion rows/s., 107.09 GB/s.)  98%Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
Query was cancelled.

1 row in set. Elapsed: 0.533 sec. Processed 686.84 million rows, 57.03 GB (1.29 billion rows/s., 107.09 GB/s.)

Received exception from server (version 23.12.1):
Code: 210. DB::Exception: Received from 11.125.128.207:9600. DB::NetException. DB::NetException: Connection reset by peer, while reading from socket (11.125.134.81:9600): while receiving packet from clickhouse-23-0.realtime-data-platform.svc.lf10.n.jd.local:9600. (NETWORK_ERROR)
```
We discovered in the logs that ClickHouse spent a significant amount of time canceling the query. Since we only needed one record, which we had already obtained, we had to cancel the subqueries on the remote nodes.
```
2024.02.26 20:28:01.708731 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-0-1.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:01.843610 [ 77670 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-2-1.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:01.925849 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-1-1.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:02.306126 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-3-1.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:02.533827 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-4-1.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:03.372899 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-5-1.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:04.853902 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-6-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:05.073738 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-7-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:08.081833 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-8-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:14.970718 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-9-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:28.279903 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-10-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:28:54.315204 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-11-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:29:46.016281 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-12-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:29:48.000746 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-14-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:29:49.172231 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-15-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:31:34.127940 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-16-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
2024.02.26 20:31:34.203070 [ 77671 ] {0c2f44d6-7166-4357-b16a-5ef6b94317a0} <Trace> StorageDistributed (app_s01_user_ord_det_snapshot_day_cate_1_d): (clickhouse-17-0.realtime-data-platform.svc.lf06.n.jd.local:9600) Cancelling query because enough data has been read
```
The time interval to cancel the query is increasing. 
Here is  packets being exchanged between initial node(11.62.112.215) and remote node(11.102.65.140).

image

We have noticed that the initial node(11.62.112.215) TCP receive buffers are already full, yet the remote node(11.102.65.140) continues to send, resulting in initial node drops incoming packets and The  remote node(11.102.65.140) retransmits, with exponential backoff.  the initial node(11.62.112.215) should waiting for `EndOfStream` packet from remote node(11.102.65.140).

Normally, when the receiver's buffer is full, a `ZeroWindow` will be replied to prevent the sender from retransmits.
A `ZeroWindow` is never sent may occur when TCP window scaling factor greater than one,  You can see detail in https://blog.cloudflare.com/unbounded-memory-usage-by-tcp-for-receive-buffers-and-how-we-fixed-it/ . 
And fixed by https://github.com/torvalds/linux/commit/b650d953cd391595e536153ce30b4aab385643ac

We have upgraded the operating system and set `tcp_shrink_window` to true, which has allowed queries to be canceled normally.

**The root cause**
Due to problems in TCP, connections are constantly in retransmits. When trying to close these connections in a loop on the initial node, the wait time for each connection to close gets progressively longer due to TCP's exponential backoff, ultimately leading to query timeouts.

**Expected behavior**
Although the root cause is a deficiency in the TCP implementation, we can try our best to avoid triggering this issue. Connection drain is a heavy operation that may take a long time; we can move this operation from prepare to work, allowing us to drain multiple connections in parallel.

### PR DESCRIPTION
**Pull request by lzydmxy**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Move connection drain from prepare to work, and drain multiple connections in parallel.

Resolves https://github.com/ClickHouse/ClickHouse/issues/60844

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 18b17523e403998fdaaedbfb08736de3a20b38a5 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60845/18b17523e403998fdaaedbfb08736de3a20b38a5/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Processors/Sources/RemoteSource.cpp [hunk 1]
```diff
@@ -72,19 +72,33 @@ ISource::Status RemoteSource::prepare()
...
         is_async_state = false;
-        return status;
+        need_drain = true;
+        return Status::Ready;
     }
 
     return status;
 }
 
+void RemoteSource::work()
```
Comment (jsc0218) [inline src/Processors/Sources/RemoteSource.cpp:91]: probably add some comment here why move drain to work from prepare, to facilitate others' understanding.

**Review by jsc0218 — APPROVED** [review]

File: src/Processors/Sources/RemoteSource.cpp (hunk 1 above)
Comment (lzydmxy) [reply src/Processors/Sources/RemoteSource.cpp:91]: okay
