### PR TITLE
Fix for Date/DateTime64 overflow in ORC format

### LINKED ISSUE #70976: Missing error while converting into ORC format?
**Describe the bug**
According to the docs: https://clickhouse.com/docs/en/interfaces/formats#data-types-matching-orc, the `Date` type is not supported in the `ORC` format conversion. The date value is truncated at the moment, but it should throw an error instead.

**How to reproduce**
Run:

```sql
CREATE TABLE t0 (c0 Date) ENGINE = Memory();
INSERT INTO TABLE t0 (c0) VALUES ('2060-01-01');
SELECT * FROM t0; --2060-01-01
INSERT INTO TABLE FUNCTION file('<file path>', 'ORC', 'c0 Date') SELECT c0 FROM t0;
TRUNCATE t0;
INSERT INTO TABLE t0 (c0) FROM INFILE '<file path>' FORMAT ORC;
SELECT * FROM t0; --1970-01-01
```

### LINKED ISSUE #91108: UndefinedBehaviorSanitizer: undefined behavior (STID: 3022-48ca)
CI report: [BuzzHouse (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=03463e4ed9e35985acfaf3be24bc23fab26465af&name_0=MasterCI&name_1=BuzzHouse%20%28amd_ubsan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdVbmRlZmluZWRCZWhhdmlvclNhbml0aXplcjogdW5kZWZpbmVkIGJlaGF2aW9yIChTVElEOiAzMDIyLTQ4Y2EpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQnV6ekhvdXNlIChhbWRfdWJzYW4pJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAIL [UndefinedBehaviorSanitizer: undefined behavior (STID: 3022-48ca)]
  | Error:
  | SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1653:54
  | ---
  | 
  | Stack trace:
  | #0 0x55fb2f3c6e23 in DB::readColumnWithTimestampData(orc::ColumnVectorBatch const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) ci/tmp/build/./src/Proc...
  | #1 0x55fb2f3c6e23 in DB::ORCColumnToCHColumn::readColumnFromORCColumn(orc::ColumnVectorBatch const*, orc::Type const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<cha...
  | #2 0x55fb2f3be5c0 in DB::ORCColumnToCHColumn::orcColumnsToCHChunk(DB::Chunk&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::pa...
  | #3 0x55fb2f3bb9e8 in DB::ORCColumnToCHColumn::orcTableToCHChunk(DB::Chunk&, orc::Type const*, orc::ColumnVectorBatch const*, unsigned long, DB::BlockMissingValues*) ci/tmp/build/./src/Processors/Forma...
  | #4 0x55fb2f3b9c49 in DB::NativeORCBlockInputFormat::read() ci/tmp/build/./src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1114:30
  | #5 0x55fb2f0a0823 in DB::IInputFormat::generate() ci/tmp/build/./src/Processors/Formats/IInputFormat.cpp:33:21
  | #6 0x55fb2f04aa18 in DB::ISource::tryGenerate() ci/tmp/build/./src/Processors/ISource.cpp:144:18
  | #7 0x55fb2f04a174 in DB::ISource::work() ci/tmp/build/./src/Processors/ISource.cpp:110:26
  | #8 0x55fb2f081b0d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53:26
  | #9 0x55fb2f081b0d in DB::ExecutionThreadContext::executeTask() ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:102:9
  | #10 0x55fb2f063fb7 in DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::__1::atomic<bool>*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351:26
  | #11 0x55fb2f0664ae in DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:279:5
  | #12 0x55fb2f0664ae in DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0::operator()() const ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:565:17
  | #13 0x55fb2f0664ae in decltype(std::declval<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__1::__invoke[abi:ne210105]<DB::PipelineExecutor::spawnThreads(...
  | #14 0x55fb2f0664ae in void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecu...
  | #15 0x55fb2f0664ae in void std::__1::__invoke_r[abi:ne210105]<void, DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::__1::shar...
  | #16 0x55fb2f0664ae in void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0>(std::__1::__functio...
  | #17 0x55fb1c3c411f in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
  | #18 0x55fb1c3c411f in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
  | #19 0x55fb1c3c411f in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:801:17
  | #20 0x55fb1c3ccd07 in decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>:...
  | #21 0x55fb1c3ccd07 in decltype(auto) std::__1::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl...
  | #22 0x55fb1c3ccd07 in decltype(auto) std::__1::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGl...
  | #23 0x55fb1c3ccd07 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFrom...
  | #24 0x55fb1c3c14d4 in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
  | #25 0x55fb1c3c14d4 in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
  | #26 0x55fb1c3c14d4 in ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:811:17
  | #27 0x55fb1c3c8ca9 in decltype(*std::declval<ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)()>()()) std::__1:...
  | #28 0x55fb1c3c8ca9 in void std::__1::__thread_execute[abi:ne210105]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1:...
  | #29 0x55fb1c3c8ca9 in void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoo...
  | #30 0x7fe9956ebac2 in start_thread nptl/pthread_create.c:442:8
  | #31 0x7fe99577d8bf  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

### PR DESCRIPTION
**Pull request by yariks5s**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixes an overflow while reading from ORC format for Date and DateTime64 types. Closes #70976

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp [hunk 1]
```diff
@@ -1616,13 +1628,21 @@ static ColumnWithTypeAndName readColumnWithDateData(
...
                 throw Exception(
                     ErrorCodes::VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE,
                     "Input value {} of a column \"{}\" exceeds the range of type Date32",
                     days_num,
                     column_name);
 
+            if (check_date_range && (days_num > DATE_LUT_MAX_DAY_NUM || days_num < 0))
+                throw Exception(
+                    ErrorCodes::VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE,
+                    "Input value {} of a column \"{}\" exceeds the range of type Date, which is [0, {}]",
```
Comment (antaljanosbenjamin) [inline src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1643]: Could you please also add the min max values to the previous error message? Let's have them in the similar way

Comment (yariks5s) [reply src/Processors/Formats/Impl/NativeORCBlockInputFormat.cpp:1643]: Done

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by yariks5s** [comment]
[Integration tests (amd_tsan, 3/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91572&sha=af3c6f33aa10ba7eafdd31f89926bba7e42a6cfc&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+3%2F6%29) -- [flaky](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICd0ZXN0X3N0b3JhZ2VfaWNlYmVyZ193aXRoX3NwYXJrL3Rlc3RfY2x1c3Rlcl90YWJsZV9mdW5jdGlvbi5weTo6dGVzdF9jbHVzdGVyX3RhYmxlX2Z1bmN0aW9uX3NwbGl0X2J5X3Jvd19ncm91cHNbMS0wLXMzLTFdJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnSW50ZWdyYXRpb24gdGVzdHMgKGFtZF90c2FuLCAzLzYpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

[Stateless tests (amd_msan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91572&sha=af3c6f33aa10ba7eafdd31f89926bba7e42a6cfc&name_0=PR&name_1=Stateless+tests+%28amd_msan%2C+parallel%29) -- [1](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMzcwMl9hbHRlcl9jb2x1bW5fdXBkYXRlX2FuZF9kZWxldGVfd2l0aF9zZWNvbmRhcnlfaW5kZXhfZHJvcCcKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0YXRlbGVzcyB0ZXN0cyAoYW1kX21zYW4sIHBhcmFsbGVsKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==), [2](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMDgxNl9sb25nX2NvbmN1cnJlbnRfYWx0ZXJfY29sdW1uJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnU3RhdGVsZXNzIHRlc3RzIChhbWRfbXNhbiwgcGFyYWxsZWwpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

**Comment by yariks5s** [comment]
[Stateless tests (amd_msan, sequential, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91572&sha=latest&name_0=PR&name_1=Stateless+tests+%28amd_msan%2C+sequential%2C+2%2F2%29) -- https://github.com/ClickHouse/ClickHouse/issues/83373
