### PR TITLE
Use Analyzer to generate actions from default expression

### LINKED ISSUE #78902: ExpressionAnalyzer drops expressions because of the alias clash
### Describe the unexpected behaviour

`ExpressionAnalyzer` drops expressions because of the alias clash.
Repro with the `select` query with the old analyzer, but `ExpressionAnalyzer` is used in different parts and could lead to unexpected behavior in other queries even with `enable_analyzer=1`

### How to reproduce

version: since 21.4, probably introduced with #23191
```sql
CREATE TABLE t (_subquery_test Nullable(Int64)) Engine=Memory();
INSERT INTO t VALUES (NULL);

SELECT ifNull(_subquery_test, 7) as _subquery_test FROM t SETTINGS enable_analyzer=0; -- NULL
SELECT ifNull(_subquery_test, 7) as _subquery_test FROM t SETTINGS enable_analyzer=1; -- 7
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

In expressions like
```sql
func(_subquery_1) as _subquery_1
```

1. TreeRewriter(QueryAliasesMatcher) sets prefer_alias_to_column_name=True
2. ExpressionAnalyzer state is initialized with the source column
3. When facing a node with an alias with the same name it considers node as visited
4. Final DAG contains only a column, without wrapping expression

https://fiddle.clickhouse.com/7382f958-f1a6-494e-920a-0c727a358079
This is the second reason for #74621

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
Support creating a default expression using the new analyzer. Fixes 

Related to #78902
Old analyzer, in rare cases, cannot execute valid queries
https://fiddle.clickhouse.com/00614142-12f4-4e1e-9dd7-03d34e8bd8d1

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Require backticks around identifiers with dots in default expressions to prevent them from being parsed as compound identifiers.

### CODE REVIEW

File: src/Interpreters/inplaceBlockConversions.cpp [hunk 1]
```diff
@@ -173,6 +190,53 @@ std::optional<ActionsDAG> createExpressions(
...
+
+    auto execution_context = Context::createCopy(context);
+    auto expression = buildQueryTree(expr_list, execution_context);
+
+    ColumnsDescription fake_column_descriptions(header.getNamesAndTypesList());
+    auto storage = std::make_shared<StorageDummy>(StorageID{"dummy", "dummy"}, fake_column_descriptions);
+    QueryTreeNodePtr fake_table_expression = std::make_shared<TableNode>(storage, execution_context);
+
+    QueryAnalyzer analyzer(false);
+    analyzer.resolveConstantExpression(expression, fake_table_expression, execution_context);
```
Comment (novikd) [inline src/Interpreters/inplaceBlockConversions.cpp]:
```suggestion
    analyzer.resolve(expression, fake_table_expression, execution_context);
```
Because it's not a constant expression

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 2]
```diff
@@ -255,7 +254,11 @@ void QueryAnalyzer::resolveConstantExpression(QueryTreeNodePtr & node, const Que
     }
 
     if (node_type == QueryTreeNodeType::LIST)
+    {
+        QueryExpressionsAliasVisitor visitor(scope.aliases);
+        visitor.visit(node);
         resolveExpressionNodeList(node, scope, false /*allow_lambda_expression*/, false /*allow_table_expression*/);
+    }
```
Comment (novikd) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp]: Move this to QueryAnalyzer::resolve

File: src/Interpreters/inplaceBlockConversions.cpp [hunk 3]
```diff
@@ -173,6 +190,53 @@ std::optional<ActionsDAG> createExpressions(
...
+    else
+        actions.project(result_columns);
+
+    // Output all the rest columns
+    NameSet outputs;
+    for (const auto & output : actions.getOutputs())
+        outputs.insert(output->result_name);
+    for (const auto & input : actions.getInputs())
+        if (!outputs.contains(input->result_name))
+            actions.getOutputs().push_back(input);
```
Comment (novikd) [inline src/Interpreters/inplaceBlockConversions.cpp]: I didn't get why we need it.

**Review by novikd — COMMENTED** [review]
In general LGTM

File: src/Interpreters/inplaceBlockConversions.cpp (hunk 3 above)
Comment (GrigoryPervakov) [reply src/Interpreters/inplaceBlockConversions.cpp]: If some columns don't need/have default expressions, they wouldn't be in outputs, so the resulting header will be different

**Review by novikd — APPROVED** [review]
LGTM

**Comment by GrigoryPervakov** [comment]
Stateless tests: 03552_filesystem_read_prefetches_log: seems to be flaky [ci db](https://play.clickhouse.com/play?user=play#U0VMRUNUIAogICAgY2hlY2tfbmFtZSwKICAgIENvdW50SWYoY2hlY2tfc3RhdHVzPSdmYWlsdXJlJykgZmFpbCwKICAgIENvdW50SWYoY2hlY2tfc3RhdHVzPSdzdWNjZXNzJykgc3VjYywKICAgIGZhaWwgLyAoZmFpbCtzdWNjKSBmYWlsZWQKRlJPTSBjaGVja3MKV0hFUkUgCiAgICB0ZXN0X25hbWU9JzAzNTUyX2ZpbGVzeXN0ZW1fcmVhZF9wcmVmZXRjaGVzX2xvZycKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgNyBEQVlTCkdST1VQIEJZIGNoZWNrX25hbWUKT1JERVIgQlkgZmFpbGVkOw==)

Stress test failed with `Disk does not support WriteMode::Append. (NOT_IMPLEMENTED)` which is unrelated
