### PR TITLE
Fix for index file cidx is unexpectedly long

### LINKED ISSUE #47200: Upgrade check: Index file `primary.cidx` is unexpectedly long (broken part)
https://s3.amazonaws.com/clickhouse-test-reports/47152/fdcbec4fee7df1bb5a51249cef96964b5245c822/stress_test__debug_.html

```
2023.03.03 01:35:43.985393 [ 221299 ] {} <Error> test_metadata_cache.check_part_metadata_cache: while loading part 201806_0_0_0_2 on path data/test_metadata_cache/check_part_metadata_cache/201806_0_0_0_2: Code: 4. DB::Exception: Index file data/test_metadata_cache/check_part_metadata_cache/201806_0_0_0_2/primary.cidx is unexpectedly long. (EXPECTED_END_OF_FILE), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../contrib/llvm-project/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x2326a6be in /usr/bin/clickhouse
1. ./build_docker/../src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x14551458 in /usr/bin/clickhouse
2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&>(int, FormatStringHelperImpl<std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) @ 0xcb6da79 in /usr/bin/clickhouse
3. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:766: DB::IMergeTreeDataPart::loadIndex() @ 0x1ecee3e0 in /usr/bin/clickhouse
4. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:627: DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x1eceb34c in /usr/bin/clickhouse
5. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:0: DB::MergeTreeData::loadDataPart(DB::MergeTreePartInfo const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, std::__1::mutex&) @ 0x1ed9a5c4 in /usr/bin/clickhouse
6. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:1435: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeData::loadDataPartsFromDisk(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, unsigned long, std::__1::queue<std::__1::vector<std::__1::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>, std::__1::allocator<std::__1::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>>>, std::__1::deque<std::__1::vector<std::__1::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>, std::__1::allocator<std::__1::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>>>, std::__1::allocator<std::__1::vector<std::__1::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>, std::__1::allocator<std::__1::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>>>>>>&, std::__1::shared_ptr<DB::MergeTreeSettings const> const&)::$_19, void ()>>(std::__1::__function::__policy_storage const*) @ 0x1ee22e45 in /usr/bin/clickhouse
7. ./build_docker/../base/base/wide_integer_impl.h:786: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x14667791 in /usr/bin/clickhouse
8. ./build_docker/../src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x1466bdf8 in /usr/bin/clickhouse
9. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:717: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x1466bd62 in /usr/bin/clickhouse
10. ./build_docker/../base/base/wide_integer_impl.h:786: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x14664331 in /usr/bin/clickhouse
11. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x14669272 in /usr/bin/clickhouse
12. __tsan_thread_start_func @ 0xc5017a7 in /usr/bin/clickhouse
13. ? @ 0x7fcacc1ce609 in ?

2023.03.03 01:35:43.986723 [ 221299 ] {} <Error> test_metadata_cache.check_part_metadata_cache: Detaching broken part /var/lib/clickhouse/disks/s3/data/test_metadata_cache/check_part_metadata_cache/201806_0_0_0_2 (size: 791.00 B). If it happened after update, it is likely because of backward incompatibility. You need to resolve this manually
```

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
Changelog category (leave one):
* Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md): 
Updated to delete added keys if there is an exception during update of metadata cache closes #47200

### CODE REVIEW

File: src/Storages/MergeTree/PartMetadataManagerWithCache.cpp [hunk 1]
```diff
@@ -117,29 +117,45 @@ void PartMetadataManagerWithCache::updateAll(bool include_projection)
...
-        if (!part->getDataPartStorage().exists(file_name))
-            continue;
-        auto in = part->getDataPartStorage().readFile(file_name, {}, std::nullopt, std::nullopt);
-        readStringUntilEOF(value, *in);
 
-        String key = getKeyFromFilePath(file_path);
-        auto status = cache->put(key, value);
-        if (!status.ok())
+    /// This is used to remove the keys in case of any exception while caching other keys
+    Strings keys_added_to_cache(file_names.size());
```
Comment (alesapin) [inline src/Storages/MergeTree/PartMetadataManagerWithCache.cpp:122]: afair we should create it empty and call .reserve() instead of argument in constructor. Current version will create vector of empty strings.

**Review by alesapin — APPROVED** [review]

File: src/Storages/MergeTree/PartMetadataManagerWithCache.cpp (hunk 1 above)
Comment (SmitaRKulkarni) [reply src/Storages/MergeTree/PartMetadataManagerWithCache.cpp]: sorry my bad. addressed it

**Review by alesapin — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
