### PR TITLE
Fix error in `decodeURLComponent`

### LINKED ISSUE #47435: encodeURLComponent  makes incorrect results for cyrillic characters
**How to reproduce**

```SQL
SELECT
    encodeURLComponent('кликхаус') AS encoded,
    decodeURLComponent(encoded) = 'кликхаус' AS expected_EQ
```

**Actual result**
```
┌─encoded─────────────────────────────────────┬─expected_EQ─┐
│ %a0%A%a0%B%a0%8%a0%A%a1%g5%a0%0%a1%g3%a1%g1 │           0 │
└─────────────────────────────────────────────┴─────────────┘
```

**Expected result**

```
┌─encoded──────────────────────────────────────────┬─expected_EQ─┐
│ %D0%BA%D0%BB%D0%B8%D0%BA%D1%85%D0%B0%D1%83%D1%81 │           1 │
└──────────────────────────────────────────────────┴─────────────┘

```

**Additional context**

```
SELECT version()


┌─version()─┐
│ 23.2.3.17 │
└───────────┘

```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The function `decodeURLComponent` wasn't working at all. This closes #47435. The bug was introduced here: #34607

### CODE REVIEW

File: src/Functions/URL/decodeURLComponent.cpp [hunk 1]
```diff
@@ -14,28 +14,33 @@ namespace ErrorCodes
 static size_t encodeURL(const char * __restrict src, size_t src_size, char * __restrict dst, bool space_as_plus)
 {
     char * dst_pos = dst;
-    for (size_t i = 0; i < src_size; i++)
```
Comment (alexey-milovidov) [inline src/Functions/URL/decodeURLComponent.cpp:17]: We don't allow suffix increments.

File: src/Functions/URL/decodeURLComponent.cpp [hunk 2]
```diff
@@ -14,28 +14,33 @@ namespace ErrorCodes
...
+    for (size_t i = 0; i < src_size; ++i)
     {
         if ((src[i] >= '0' && src[i] <= '9') || (src[i] >= 'a' && src[i] <= 'z') || (src[i] >= 'A' && src[i] <= 'Z')
             || src[i] == '-' || src[i] == '_' || src[i] == '.' || src[i] == '~')
         {
-            *dst_pos++ = src[i];
```
Comment (alexey-milovidov) [inline src/Functions/URL/decodeURLComponent.cpp:22]: We don't allow more than one effect in one statement.

File: src/Functions/URL/decodeURLComponent.cpp [hunk 3]
```diff
@@ -14,28 +14,33 @@ namespace ErrorCodes
...
         else if (src[i] == ' ' && space_as_plus)
         {
-            *dst_pos++ = '+';
+            *dst_pos = '+';
+            ++dst_pos;
         }
         else
         {
-            *dst_pos++ = '%';
-            *dst_pos++ = hexDigitUppercase(src[i] >> 4);
```
Comment (alexey-milovidov) [inline src/Functions/URL/decodeURLComponent.cpp:31]: This is wrong because `char` can be either signed or unsigned.

File: src/Functions/URL/decodeURLComponent.cpp [hunk 4]
```diff
@@ -14,28 +14,33 @@ namespace ErrorCodes
...
-            *dst_pos++ = hexDigitUppercase(src[i] & 0xf);
```
Comment (alexey-milovidov) [inline src/Functions/URL/decodeURLComponent.cpp:32]: This is wrong because it does not use a proper function for that.

File: src/Functions/URL/decodeURLComponent.cpp [hunk 5]
```diff
@@ -14,28 +14,33 @@ namespace ErrorCodes
...
+            dst_pos[0] = '%';
+            ++dst_pos;
+            writeHexByteUppercase(src[i], dst_pos);
+            dst_pos += 2;
         }
     }
-    *dst_pos++ = src[src_size];
```
Comment (alexey-milovidov) [inline src/Functions/URL/decodeURLComponent.cpp:35]: Wrong.

File: src/Functions/URL/decodeURLComponent.cpp [hunk 6]
```diff
@@ -120,10 +125,14 @@ struct CodeURLComponentImpl
         ColumnString::Chars & res_data, ColumnString::Offsets & res_offsets)
     {
         if (code_strategy == encode)
-            //the destination(res_data) string is at most three times the length of the source string
```
Comment (alexey-milovidov) [inline src/Functions/URL/decodeURLComponent.cpp:123]: Missing whitespace.

File: tests/queries/0_stateless/02677_decode_url_component.sql [hunk 7]
```diff
@@ -0,0 +1,5 @@
+SELECT
+    encodeURLComponent('кликхаус') AS encoded,
+    decodeURLComponent(encoded) = 'кликхаус' AS expected_EQ;
+
+SELECT DISTINCT decodeURLComponent(encodeURLComponent(randomString(100) AS x)) = x FROM numbers(100000);
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02677_decode_url_component.sql:5]: Apparently, there was no proper test for this function.
