### PR TITLE
Fix MSan report in `maxIntersections` function

### LINKED ISSUE #43126: Serialization of maxIntersectionsState is broken
Running under MSAN:

```
SELECT
    hex(maxIntersectionsState(start, end))
FROM
    (
        SELECT 1 AS start, 3 as end
         UNION ALL
        SELECT 3 AS start, 5 as end
    );
```

Logs (shortened due to Github limitations):
```
==272977==WARNING: MemorySanitizer: use-of-uninitialized-value
2022.11.10 15:32:18.000235 [ 273270 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 2.45 GiB, peak 2.46 GiB, free memory in arenas 0.00 B, will set to 2.51 GiB (RSS), difference: 64.37 MiB
    #0 0xd7957fe in DB::EncodeToBinaryRepresentation<DB::HexImpl>::tryExecuteString(DB::IColumn const*, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd7957fe) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #1 0xd792e8e in DB::EncodeToBinaryRepresentation<DB::HexImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd792e8e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #2 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #3 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #4 0x40d36dbb in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:302:22
    #5 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #6 0x4425ac55 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) build_msan/./src/Interpreters/ExpressionActions.cpp:607:60
    #7 0x4425ac55 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const build_msan/./src/Interpreters/ExpressionActions.cpp:724:13
    #8 0x4b5028f9 in DB::ExpressionTransform::transform(DB::Chunk&) build_msan/./src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #9 0x3573b84a in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_msan/./src/Processors/ISimpleTransform.h:32:9
    #10 0x4ab8734f in DB::ISimpleTransform::work() build_msan/./src/Processors/ISimpleTransform.cpp:89:9
    #11 0x4ac07f72 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_msan/./src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #12 0x4ac07f72 in DB::ExecutionThreadContext::executeTask() build_msan/./src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #13 0x4abcbac2 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_msan/./src/Processors/Executors/PipelineExecutor.cpp:229:26
    #14 0x4abd28b4 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_msan/./src/Processors/Executors/PipelineExecutor.cpp:195:5
    #15 0x4abd28b4 in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_msan/./src/Processors/Executors/PipelineExecutor.cpp:316:17
    #16 0x4abd28b4 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15003]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_msan/./contrib/libcxx/include/__functional/invoke.h:394:23
    #17 0x4abd28b4 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15003]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_msan/./contrib/libcxx/include/tuple:1789:1
    #18 0x4abd28b4 in decltype(auto) std::__1::apply[abi:v15003]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_msan/./contrib/libcxx/include/tuple:1798:1
    #19 0x4abd28b4 in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_msan/./src/Common/ThreadPool.h:196:13
    #20 0x4abd28b4 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15003]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_msan/./contrib/libcxx/include/__functional/invoke.h:394:23
    #21 0x4abd28b4 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_msan/./contrib/libcxx/include/__functional/invoke.h:479:9
    #22 0x4abd28b4 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15003]() build_msan/./contrib/libcxx/include/__functional/function.h:235:12
    #23 0x4abd28b4 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_msan/./contrib/libcxx/include/__functional/function.h:716:16
    #24 0x28faf78f in std::__1::__function::__policy_func<void ()>::operator()[abi:v15003]() const build_msan/./contrib/libcxx/include/__functional/function.h:848:16
    #25 0x28faf78f in std::__1::function<void ()>::operator()() const build_msan/./contrib/libcxx/include/__functional/function.h:1197:12
    #26 0x28faf78f in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_msan/./src/Common/ThreadPool.cpp:294:17
    #27 0x28fbf30d in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_msan/./src/Common/ThreadPool.cpp:144:73
    #28 0x28fbf30d in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15003]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_msan/./contrib/libcxx/include/__functional/invoke.h:394:23
    #29 0x28fbf30d in void std::__1::__thread_execute[abi:v15003]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_msan/./contrib/libcxx/include/thread:284:5
    #30 0x28fbf30d in void* std::__1::__thread_proxy[abi:v15003]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) build_msan/./contrib/libcxx/include/thread:295:5
    #31 0x7f75e51a58fc in start_thread /usr/src/debug/glibc/nptl/pthread_create.c:442:8
    #32 0x7f75e5227a5f in clone3 /build/glibc/src/glibc/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

  Uninitialized value was stored to memory at
    #0 0xc27a7fc in __msan_memcpy.part.0 crtstuff.c
    #1 0xc3532d5 in DB::WriteBuffer::write(char const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3532d5) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #2 0x42426264 in DB::writeString(char const*, unsigned long, DB::WriteBuffer&) build_msan/./src/IO/WriteHelpers.h:187:9
    #3 0x42426264 in DB::writeString(std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::WriteBuffer&) build_msan/./src/IO/WriteHelpers.h:198:5
    #4 0x42426264 in DB::SerializationAggregateFunction::serializeText(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:144:5
    #5 0xc3375cb in DB::ConvertImplGenericToString<DB::ColumnString>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3375cb) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #6 0xd03590e in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd03590e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #7 0xd033884 in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd033884) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #8 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #9 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #10 0x40d36dbb in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:302:22
    #11 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #12 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #13 0xc3e512e in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::createFunctionAdaptor(std::__1::shared_ptr<DB::IFunction>, std::__1::shared_ptr<DB::IDataType const> const&)::'lambda'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)> >(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3e512e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #14 0xc3050a1 in DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3050a1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #15 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #16 0x40d37050 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:306:18
    #17 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #18 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #19 0x46ed3c04 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::castColumn<(DB::CastType)0>(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::IDataType const> const&) build_msan/./src/Interpreters/castColumn.cpp:35:27
    #20 0x46ed3c04 in DB::castColumn(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::IDataType const> const&) build_msan/./src/Interpreters/castColumn.cpp:41:12
    #21 0xd791ee1 in DB::EncodeToBinaryRepresentation<DB::HexImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd791ee1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #22 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)

  Uninitialized value was stored to memory at
    #0 0xc27a564 in __msan_memmove.part.0 crtstuff.c
    #1 0x42426824 in std::__1::pair<char const*, char*> std::__1::__copy_impl[abi:v15003]<char const, char, void>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:56:5
    #2 0x42426824 in std::__1::pair<char const*, char*> std::__1::__copy[abi:v15003]<char const*, char const*, char*, 0>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:94:18
    #3 0x42426824 in char* std::__1::copy[abi:v15003]<char const*, char*>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:103:10
    #4 0x42426824 in std::__1::enable_if<__is_cpp17_random_access_iterator<char const*>::value, char*>::type std::__1::copy_n[abi:v15003]<char const*, unsigned long, char*>(char const*, unsigned long, char*) build_msan/./contrib/libcxx/include/__algorithm/copy_n.h:61:12
    #5 0x42426824 in std::__1::char_traits<char>::copy(char*, char const*, unsigned long) build_msan/./contrib/libcxx/include/__string/char_traits.h:233:9
    #6 0x42426824 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init_copy_ctor_external(char const*, unsigned long) build_msan/./contrib/libcxx/include/string:2054:3
    #7 0x42426824 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) build_msan/./contrib/libcxx/include/string:2015:9
    #8 0x42426824 in DB::serializeToString(std::__1::shared_ptr<DB::IAggregateFunction const> const&, DB::IColumn const&, unsigned long, unsigned long) build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:115:12
    #9 0x4242612a in DB::SerializationAggregateFunction::serializeText(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:144:17
    #10 0xc3375cb in DB::ConvertImplGenericToString<DB::ColumnString>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3375cb) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #11 0xd03590e in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd03590e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #12 0xd033884 in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd033884) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #13 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #14 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #15 0x40d36dbb in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:302:22
    #16 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #17 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #18 0xc3e512e in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::createFunctionAdaptor(std::__1::shared_ptr<DB::IFunction>, std::__1::shared_ptr<DB::IDataType const> const&)::'lambda'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)> >(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3e512e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #19 0xc3050a1 in DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3050a1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #20 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #21 0x40d37050 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:306:18
    #22 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #23 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #24 0x46ed3c04 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::castColumn<(DB::CastType)0>(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::IDataType const> const&) build_msan/./src/Interpreters/castColumn.cpp:35:27
    #25 0x46ed3c04 in DB::castColumn(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::IDataType const> const&) build_msan/./src/Interpreters/castColumn.cpp:41:12
    #26 0xd791ee1 in DB::EncodeToBinaryRepresentation<DB::HexImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd791ee1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #27 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)

  Uninitialized value was stored to memory at
    #0 0xc27a564 in __msan_memmove.part.0 crtstuff.c
    #1 0x63b3489b in std::__1::pair<char const*, char*> std::__1::__copy_impl[abi:v15003]<char const, char, void>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:56:5
    #2 0x63b3489b in std::__1::pair<char const*, char*> std::__1::__copy[abi:v15003]<char const*, char const*, char*, 0>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:94:18
    #3 0x63b3489b in char* std::__1::copy[abi:v15003]<char const*, char*>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:103:10
    #4 0x63b3489b in std::__1::enable_if<__is_cpp17_random_access_iterator<char const*>::value, char*>::type std::__1::copy_n[abi:v15003]<char const*, unsigned long, char*>(char const*, unsigned long, char*) build_msan/./contrib/libcxx/include/__algorithm/copy_n.h:61:12
    #5 0x63b3489b in std::__1::char_traits<char>::copy(char*, char const*, unsigned long) build_msan/./contrib/libcxx/include/__string/char_traits.h:233:9
    #6 0x63b3489b in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) build_msan/./contrib/libcxx/include/string:2391:9
    #7 0x63b3489b in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char) build_msan/./contrib/libcxx/include/string:2706:13
    #8 0xc352897 in DB::WriteBufferFromVector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::nextImpl() (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc352897) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #9 0xc353205 in DB::WriteBuffer::write(char const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc353205) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #10 0x33fb5d13 in DB::AggregateFunctionIntersectionsMax<char8_t>::serialize(char const*, DB::WriteBuffer&, std::__1::optional<unsigned long>) const build_msan/./src/AggregateFunctions/AggregateFunctionMaxIntersections.h:120:13
    #11 0x42426545 in DB::serializeToString(std::__1::shared_ptr<DB::IAggregateFunction const> const&, DB::IColumn const&, unsigned long, unsigned long) build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:114:15
    #12 0x4242612a in DB::SerializationAggregateFunction::serializeText(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:144:17
    #13 0xc3375cb in DB::ConvertImplGenericToString<DB::ColumnString>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3375cb) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #14 0xd03590e in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd03590e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #15 0xd033884 in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd033884) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #16 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #17 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #18 0x40d36dbb in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:302:22
    #19 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #20 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #21 0xc3e512e in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::createFunctionAdaptor(std::__1::shared_ptr<DB::IFunction>, std::__1::shared_ptr<DB::IDataType const> const&)::'lambda'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)> >(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3e512e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #22 0xc3050a1 in DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3050a1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #23 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #24 0x40d37050 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:306:18
    #25 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16

  Uninitialized value was stored to memory at
    #0 0xc27a564 in __msan_memmove.part.0 crtstuff.c
    #1 0x63b3489b in std::__1::pair<char const*, char*> std::__1::__copy_impl[abi:v15003]<char const, char, void>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:56:5
    #2 0x63b3489b in std::__1::pair<char const*, char*> std::__1::__copy[abi:v15003]<char const*, char const*, char*, 0>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:94:18
    #3 0x63b3489b in char* std::__1::copy[abi:v15003]<char const*, char*>(char const*, char const*, char*) build_msan/./contrib/libcxx/include/__algorithm/copy.h:103:10
    #4 0x63b3489b in std::__1::enable_if<__is_cpp17_random_access_iterator<char const*>::value, char*>::type std::__1::copy_n[abi:v15003]<char const*, unsigned long, char*>(char const*, unsigned long, char*) build_msan/./contrib/libcxx/include/__algorithm/copy_n.h:61:12
    #5 0x63b3489b in std::__1::char_traits<char>::copy(char*, char const*, unsigned long) build_msan/./contrib/libcxx/include/__string/char_traits.h:233:9
    #6 0x63b3489b in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) build_msan/./contrib/libcxx/include/string:2391:9
    #7 0x63b3489b in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char) build_msan/./contrib/libcxx/include/string:2706:13
    #8 0xc352897 in DB::WriteBufferFromVector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::nextImpl() (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc352897) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #9 0xc353205 in DB::WriteBuffer::write(char const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc353205) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #10 0x33fb5d13 in DB::AggregateFunctionIntersectionsMax<char8_t>::serialize(char const*, DB::WriteBuffer&, std::__1::optional<unsigned long>) const build_msan/./src/AggregateFunctions/AggregateFunctionMaxIntersections.h:120:13
    #11 0x42426545 in DB::serializeToString(std::__1::shared_ptr<DB::IAggregateFunction const> const&, DB::IColumn const&, unsigned long, unsigned long) build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:114:15
    #12 0x4242612a in DB::SerializationAggregateFunction::serializeText(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:144:17
    #13 0xc3375cb in DB::ConvertImplGenericToString<DB::ColumnString>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3375cb) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #14 0xd03590e in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd03590e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #15 0xd033884 in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd033884) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #16 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #17 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #18 0x40d36dbb in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:302:22
    #19 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #20 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #21 0xc3e512e in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::createFunctionAdaptor(std::__1::shared_ptr<DB::IFunction>, std::__1::shared_ptr<DB::IDataType const> const&)::'lambda'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)> >(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3e512e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #22 0xc3050a1 in DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3050a1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #23 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #24 0x40d37050 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:306:18
    #25 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16

  Uninitialized value was stored to memory at
    #0 0xc27a7fc in __msan_memcpy.part.0 crtstuff.c
    #1 0xc3532d5 in DB::WriteBuffer::write(char const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3532d5) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #2 0x33fb5d13 in DB::AggregateFunctionIntersectionsMax<char8_t>::serialize(char const*, DB::WriteBuffer&, std::__1::optional<unsigned long>) const build_msan/./src/AggregateFunctions/AggregateFunctionMaxIntersections.h:120:13
    #3 0x42426545 in DB::serializeToString(std::__1::shared_ptr<DB::IAggregateFunction const> const&, DB::IColumn const&, unsigned long, unsigned long) build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:114:15
    #4 0x4242612a in DB::SerializationAggregateFunction::serializeText(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const build_msan/./src/DataTypes/Serializations/SerializationAggregateFunction.cpp:144:17
    #5 0xc3375cb in DB::ConvertImplGenericToString<DB::ColumnString>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3375cb) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #6 0xd03590e in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd03590e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #7 0xd033884 in DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd033884) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #8 0xc2e06b3 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2e06b3) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #9 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #10 0x40d36dbb in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:302:22
    #11 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #12 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #13 0xc3e512e in COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__1::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::FunctionCast<DB::CastInternalName>::createFunctionAdaptor(std::__1::shared_ptr<DB::IFunction>, std::__1::shared_ptr<DB::IDataType const> const&)::'lambda'(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)> >(std::__1::__function::__policy_storage const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3e512e) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #14 0xc3050a1 in DB::ExecutableFunctionCast::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc3050a1) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #15 0x40d34a1c in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:248:15
    #16 0x40d37050 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:306:18
    #17 0x40d3db18 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const build_msan/./src/Functions/IFunction.cpp:372:16
    #18 0xc2deb1c in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2deb1c) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #19 0x46ed3c04 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::castColumn<(DB::CastType)0>(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::IDataType const> const&) build_msan/./src/Interpreters/castColumn.cpp:35:27
    #20 0x46ed3c04 in DB::castColumn(DB::ColumnWithTypeAndName const&, std::__1::shared_ptr<DB::IDataType const> const&) build_msan/./src/Interpreters/castColumn.cpp:41:12

  Uninitialized value was created by a heap allocation
    #0 0xc2bacbe in malloc (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xc2bacbe) (BuildId: a6d5e48376360190dc29974365ebacb36168d622)
    #1 0x28bbbced in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) build_msan/./src/Common/Allocator.h:227:27
    #2 0x20a5bb14 in DB::Arena* std::__1::construct_at[abi:v15003]<DB::Arena, DB::Arena*>(DB::Arena*) multiply.cpp
    #3 0x20a5b4b2 in std::__1::shared_ptr<DB::Arena> std::__1::make_shared[abi:v15003]<DB::Arena, void>() multiply.cpp
    #4 0x4322d1fc in DB::AggregatedDataVariants::AggregatedDataVariants() build_msan/./src/Interpreters/Aggregator.h:669:52
    #5 0x49d2b9ff in DB::AggregatedDataVariants* std::__1::construct_at[abi:v15003]<DB::AggregatedDataVariants, DB::AggregatedDataVariants*>(DB::AggregatedDataVariants*) build_msan/./contrib/libcxx/include/__memory/construct_at.h:35:48
    #6 0x49d2b9ff in void std::__1::allocator_traits<std::__1::allocator<DB::AggregatedDataVariants> >::construct[abi:v15003]<DB::AggregatedDataVariants, void, void>(std::__1::allocator<DB::AggregatedDataVariants>&, DB::AggregatedDataVariants*) build_msan/./contrib/libcxx/include/__memory/allocator_traits.h:298:9
    #7 0x49d2b9ff in std::__1::__shared_ptr_emplace<DB::AggregatedDataVariants, std::__1::allocator<DB::AggregatedDataVariants> >::__shared_ptr_emplace[abi:v15003]<>(std::__1::allocator<DB::AggregatedDataVariants>) build_msan/./contrib/libcxx/include/__memory/shared_ptr.h:292:9
    #8 0x49d2b9ff in std::__1::shared_ptr<DB::AggregatedDataVariants> std::__1::allocate_shared[abi:v15003]<DB::AggregatedDataVariants, std::__1::allocator<DB::AggregatedDataVariants>, void>(std::__1::allocator<DB::AggregatedDataVariants> const&) build_msan/./contrib/libcxx/include/__memory/shared_ptr.h:953:55
    #9 0x49d2b9ff in std::__1::shared_ptr<DB::AggregatedDataVariants> std::__1::make_shared[abi:v15003]<DB::AggregatedDataVariants, void>() build_msan/./contrib/libcxx/include/__memory/shared_ptr.h:962:12
    #10 0x49d2adcc in DB::ManyAggregatedData::ManyAggregatedData(unsigned long) build_msan/./src/Processors/Transforms/AggregatingTransform.h:69:20
    #11 0x49d0fdbf in DB::ManyAggregatedData* std::__1::construct_at[abi:v15003]<DB::ManyAggregatedData, unsigned long, DB::ManyAggregatedData*>(DB::ManyAggregatedData*, unsigned long&&) build_msan/./contrib/libcxx/include/__memory/construct_at.h:35:48
    #12 0x49d0fdbf in void std::__1::allocator_traits<std::__1::allocator<DB::ManyAggregatedData> >::construct[abi:v15003]<DB::ManyAggregatedData, unsigned long, void, void>(std::__1::allocator<DB::ManyAggregatedData>&, DB::ManyAggregatedData*, unsigned long&&) build_msan/./contrib/libcxx/include/__memory/allocator_traits.h:298:9
    #13 0x49d0fdbf in std::__1::__shared_ptr_emplace<DB::ManyAggregatedData, std::__1::allocator<DB::ManyAggregatedData> >::__shared_ptr_emplace[abi:v15003]<unsigned long>(std::__1::allocator<DB::ManyAggregatedData>, unsigned long&&) build_msan/./contrib/libcxx/include/__memory/shared_ptr.h:292:9
    #14 0x49d0fdbf in std::__1::shared_ptr<DB::ManyAggregatedData> std::__1::allocate_shared[abi:v15003]<DB::ManyAggregatedData, std::__1::allocator<DB::ManyAggregatedData>, unsigned long, void>(std::__1::allocator<DB::ManyAggregatedData> const&, unsigned long&&) build_msan/./contrib/libcxx/include/__memory/shared_ptr.h:953:55
    #15 0x49d0fdbf in std::__1::shared_ptr<DB::ManyAggregatedData> std::__1::make_shared[abi:v15003]<DB::ManyAggregatedData, unsigned long, void>(unsigned long&&) build_msan/./contrib/libcxx/include/__memory/shared_ptr.h:962:12
    #16 0x4b9e70f5 in DB::AggregatingStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) build_msan/./src/Processors/QueryPlan/AggregatingStep.cpp:375:26
    #17 0x4bb06d16 in DB::ITransformingStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder> > > >, DB::BuildQueryPipelineSettings const&) build_msan/./src/Processors/QueryPlan/ITransformingStep.cpp:48:9
    #18 0x4bb79c7e in DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) build_msan/./src/Processors/QueryPlan/QueryPlan.cpp:187:47
    #19 0x4621351d in DB::InterpreterSelectWithUnionQuery::execute() build_msan/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:370:31
    #20 0x46f785f7 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_msan/./src/Interpreters/executeQuery.cpp:676:36
    #21 0x46f6c1f2 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_msan/./src/Interpreters/executeQuery.cpp:1073:30
    #22 0x4aa3a9ba in DB::TCPHandler::runImpl() build_msan/./src/Server/TCPHandler.cpp:374:24
    #23 0x4aa873f0 in DB::TCPHandler::run() build_msan/./src/Server/TCPHandler.cpp:1902:9
    #24 0x570fcabd in Poco::Net::TCPServerConnection::start() build_msan/./contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #25 0x570fdf68 in Poco::Net::TCPServerDispatcher::run() build_msan/./contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #26 0x578c4dee in Poco::PooledThread::run() build_msan/./contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #27 0x578bfcc1 in Poco::(anonymous namespace)::RunnableHolder::run() build_msan/./contrib/poco/Foundation/src/Thread.cpp:55:11

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/mnt/ch/ClickHouse/build_msan/programs/clickhouse+0xd7957fe) (BuildId: a6d5e48376360190dc29974365ebacb36168d622) in DB::EncodeToBinaryRepresentation<DB::HexImpl>::tryExecuteString(DB::IColumn const*, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&) const
Exiting
```

The serialization code seems to be attempting to read the memory of a PodArray directly, without taking into account padding or anything else (not sure if needed), that contains std::pairs, which are not guaranteed to be serialized like that.

I'm not sure if this has ever worked as intended as it's not being tested anywhere that I could see.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix MSan report in the `maxIntersections` function. This closes #43126.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
We can implement it slightly better by writing the fields directly, and writing the corresponding amount of zeros also directly.

File: src/AggregateFunctions/AggregateFunctionMaxIntersections.h [hunk 1]
```diff
@@ -117,7 +117,16 @@ class AggregateFunctionIntersectionsMax final
         const auto & value = this->data(place).value;
         size_t size = value.size();
         writeVarUInt(size, buf);
-        buf.write(reinterpret_cast<const char *>(value.data()), size * sizeof(value[0]));
+
+        for (size_t i = 0; i < size; ++i)
+        {
+            /// In this version, pairs were serialized with padding.
+            /// We must ensure that padding bytes are zero-filled.
```
Comment (tavplubix) [inline src/AggregateFunctions/AggregateFunctionMaxIntersections.h:124]: Do we need the same fix for `AggregateFunctionGroupArrayMoving` and `AggregateFunctionGroupArray`?
https://github.com/ClickHouse/ClickHouse/blob/70d1adfe4b7e437a62c59ca44a51fbd186ec7584/src/AggregateFunctions/AggregateFunctionGroupArrayMoving.h#L135
https://github.com/ClickHouse/ClickHouse/blob/70d1adfe4b7e437a62c59ca44a51fbd186ec7584/src/AggregateFunctions/AggregateFunctionGroupArray.h#L265
