### PR TITLE
Fix crash in case of adding a column with type Object(JSON)

### LINKED ISSUE #49944: Segmentation fault when adding a JSON column
Hello everyone

**Describe what's wrong**

So, when I add JSON column with default statement in existing table and try to select data from it I get a clickhouse crash (Segmentation fault)

**Does it reproduce on recent release?**

Yes

**How to reproduce**

```
CREATE TABLE testJson
(
	i Int8,
	jString String
) ENGINE = MergeTree
ORDER BY i;

INSERT INTO testJson (i, jString)
SELECT 1, '{"a":"123"}';

ALTER TABLE testJson ADD COLUMN j2 JSON default jString;

SELECT *
FROM testJson;
```

**Expected behavior**

Adding a JSON column without the Segmentation fault

**Error message and/or stacktrace**

stacktrace from crash_log
2. DB::SerializationNumber<char8_t>::serializeBinary(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const @ 0x8a704c3 in /usr/bin/clickhouse','
3. DB::SerializationTuple::serializeBinary(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const @ 0x12e21c73 in /usr/bin/clickhouse','
4. DB::IRowOutputFormat::write(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) @ 0x14d46043 in /usr/bin/clickhouse','
5. DB::IRowOutputFormat::consume(DB::Chunk) @ 0x14d45d6e in /usr/bin/clickhouse','
6. DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, unsigned long, std::shared_ptr<DB::ThreadGroup> const&) @ 0x14e5637e in /usr/bin/clickhouse','
7. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe48d6d5 in /usr/bin/clickhouse','
8. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe48ff15 in /usr/bin/clickhouse','
9. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe489501 in /usr/bin/clickhouse','
10. ? @ 0xe48ed81 in /usr/bin/clickhouse','
11. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so','
12. clone @ 0xf906f in /usr/lib/x86_64-linux-gnu/libc-2.28.so']	ClickHouse 23.4.1.1943

image

If anyone has problems with starting up clickhouse-server because the error you have to erase from clickhouse metadata the line about added column (and after starting up recreate the table, if its Replicated)

### LINKED ISSUE #56095: Segfaullt after ALTER TABLE ADD COLUMN JSON
Repro steps

```
DROP TABLE IF EXISTS test;

CREATE TABLE test
(
    `Id1` String,
    `Id2` String,
    `timestamp` DateTime64(6),
    `tags` Array(String),
)
ENGINE = MergeTree
PRIMARY KEY (Id1, Id2)
ORDER BY (Id1, Id2, timestamp)
SETTINGS index_granularity = 8192, index_granularity_bytes = 0;

INSERT INTO test SELECT number, number, '2023-10-28 11:11:11.11111', [] FROM numbers(10);
INSERT INTO test SELECT number, number, '2023-10-28 11:11:11.11111', ['a'] FROM numbers(10);
INSERT INTO test SELECT number, number, '2023-10-28 11:11:11.11111', ['b'] FROM numbers(10);
INSERT INTO test SELECT number, number, '2023-10-28 11:11:11.11111', ['c', 'd'] FROM numbers(10);
INSERT INTO test SELECT number, number, '2023-10-28 11:11:11.11111', [] FROM numbers(10);

ALTER TABLE test ADD COLUMN `tags_json` JSON;

OPTIMIZE TABLE test;
```

Stacktrace:
```
* thread #5, name = 'TCPHandler', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000010460e77 clickhouse`std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::SerializationInfo>>, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::SerializationInfo>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::SerializationInfo>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::SerializationInfo>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::SerializationInfo>>>>::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(this=0x00007fff2e19db08, __k="_dummy") const at __hash_table:2338:31
    frame #1: 0x000000001045f6be clickhouse`DB::SerializationInfoTuple::add(DB::SerializationInfo const&) [inlined] std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::SerializationInfo>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::shared_ptr<DB::SerializationInfo>>>>::find[abi:v15000](this=0x00007fff2e19db08 size=6, __k=<unavailable>) const at unordered_map:1445:69
    frame #2: 0x000000001045f6b6 clickhouse`DB::SerializationInfoTuple::add(this=<unavailable>, other=0x00007fff2e19daa8) at SerializationInfoTuple.cpp:63:43
    frame #3: 0x000000001045cad9 clickhouse`DB::SerializationInfoByName::add(this=0x00007fff3b5f15c8, other=<unavailable>) at SerializationInfo.cpp:210:21
    frame #4: 0x0000000011bc7f35 clickhouse`DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare(this=0x00007ffe7990fbf8) at MergeTask.cpp:258:19
    frame #5: 0x0000000011bd5949 clickhouse`bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(std::__1::__function::__policy_storage const*) [inlined] DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(this=<unavailable>)::operator()() const at MergeTask.h:247:32
    frame #6: 0x0000000011bd5944 clickhouse`bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(std::__1::__function::__policy_storage const*) [inlined] decltype(std::declval<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'()&>()()) std::__1::__invoke[abi:v15000]<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'()&>(__f=<unavailable>) at invoke.h:394:23
    frame #7: 0x0000000011bd5944 clickhouse`bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(std::__1::__function::__policy_storage const*) [inlined] bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'()&>(__args=<unavailable>) at invoke.h:470:16
    frame #8: 0x0000000011bd5944 clickhouse`bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(std::__1::__function::__policy_storage const*) [inlined] std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>::operator()[abi:v15000](this=<unavailable>) at function.h:235:12
    frame #9: 0x0000000011bd5944 clickhouse`bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(__buf=<unavailable>) at function.h:716:16
    frame #10: 0x0000000011bcd5ab clickhouse`DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() [inlined] std::__1::__function::__policy_func<bool ()>::operator()[abi:v15000](this=<unavailable>) const at function.h:848:16
    frame #11: 0x0000000011bcd5a8 clickhouse`DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() [inlined] std::__1::function<bool ()>::operator()(this=<unavailable>) const at function.h:1187:12
    frame #12: 0x0000000011bcd5a8 clickhouse`DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute(this=0x00007ffe7990fbf8) at MergeTask.cpp:433:9
    frame #13: 0x0000000011bd10b9 clickhouse`DB::MergeTask::execute(this=0x00007ffe97d41878) at MergeTask.cpp:857:29
    frame #14: 0x0000000011f0b120 clickhouse`DB::MergePlainMergeTreeTask::executeStep(this=0x00007fff30cfa2d8) at MergePlainMergeTreeTask.cpp:57:33
    frame #15: 0x0000000011ee8a08 clickhouse`DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, bool, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, bool) [inlined] DB::executeHere(task=std::__1::shared_ptr<DB::MergePlainMergeTreeTask>::element_type @ 0x00007fff30cfa2d8 strong=2 weak=1) at MergePlainMergeTreeTask.h:104:18
    frame #16: 0x0000000011ee89fc clickhouse`DB::StorageMergeTree::merge(this=0x00007fff2e15bc40, aggressive=<unavailable>, partition_id="", final=<unavailable>, deduplicate=false, deduplicate_by_columns=size=0, cleanup=<unavailable>, txn=nullptr, out_disable_reason="", optimize_skip_merged_partitions=<unavailable>) at StorageMergeTree.cpp:1097:5
    frame #17: 0x0000000011eed2d9 clickhouse`DB::StorageMergeTree::optimize(this=0x00007fff2e15bc40, (null)=<unavailable>, (null)=<unavailable>, partition=nullptr, final=false, deduplicate=false, deduplicate_by_columns=size=0, cleanup=false, local_context=std::__1::shared_ptr<const DB::Context>::element_type @ 0x00007ffefe51b000 strong=4 weak=11) at StorageMergeTree.cpp:1544:14
    frame #18: 0x0000000010ee32a5 clickhouse`DB::InterpreterOptimizeQuery::execute(this=0x00007ffe97e46e60) at InterpreterOptimizeQuery.cpp:82:12
    frame #19: 0x000000001127f278 clickhouse`DB::executeQueryImpl(begin="OPTIMIZE TABLE test;", end=<unavailable>, context=std::__1::shared_ptr<DB::Context>::element_type @ 0x00007ffefe51b000 strong=4 weak=11, internal=false, stage=Complete, istr=0x0000000000000000) at executeQuery.cpp:1096:40
    frame #20: 0x000000001127be0f clickhouse`DB::executeQuery(query="OPTIMIZE TABLE test;", context=nullptr, internal=<unavailable>, stage=Complete) at executeQuery.cpp:1241:30
    frame #21: 0x000000001211504b clickhouse`DB::TCPHandler::runImpl(this=0x00007ffefe4f6000) at TCPHandler.cpp:500:24
    frame #22: 0x0000000012127cf9 clickhouse`DB::TCPHandler::run(this=<unavailable>) at TCPHandler.cpp:2192:9
    frame #23: 0x0000000014861427 clickhouse`Poco::Net::TCPServerConnection::start(this=<unavailable>) at TCPServerConnection.cpp:43:3
    frame #24: 0x000000001486190d clickhouse`Poco::Net::TCPServerDispatcher::run(this=0x00007ffea4015000) at TCPServerDispatcher.cpp:115:20
    frame #25: 0x00000000149a3707 clickhouse`Poco::PooledThread::run(this=0x00007ffff71e3780) at ThreadPool.cpp:188:14
    frame #26: 0x00000000149a1322 clickhouse`Poco::ThreadImpl::runnableEntry(pThread=<unavailable>) at Thread_POSIX.cpp:335:27
    frame #27: 0x00007ffff7c94ac3 libc.so.6`start_thread(arg=<unavailable>) at pthread_create.c:442:8
    frame #28: 0x00007ffff7d26a40 libc.so.6`__clone3 at clone3.S:81

```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Prohibit adding a column with type `Object(JSON)` to an existing table. This closes: https://github.com/ClickHouse/ClickHouse/issues/56095 This closes: https://github.com/ClickHouse/ClickHouse/issues/49944

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 375c8e6304deb28f6dbb118a2b59868023596901 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56307/375c8e6304deb28f6dbb118a2b59868023596901/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6747514725">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56307/375c8e6304deb28f6dbb118a2b59868023596901/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by Algunenano — APPROVED** [review]

**Comment by tavplubix** [comment]
> This closes: https://github.com/ClickHouse/ClickHouse/issues/56095 This closes: https://github.com/ClickHouse/ClickHouse/issues/49944

It does not.

**Comment by Algunenano** [comment]
> It does not.

Considering the feature is experimental, it's going to be replaced, and nobody will try to fix the issue properly I think closing the tickets is ok.

File: src/Storages/AlterCommands.cpp [hunk 1]
```diff
@@ -1151,8 +1156,10 @@ void AlterCommands::validate(const StoragePtr & table, ContextPtr context) const
                 const GetColumnsOptions options(GetColumnsOptions::AllPhysical);
                 const auto old_data_type = all_columns.getColumn(options, column_name).type;
 
-                if (command.data_type->getName().contains("Object")
-                    || old_data_type->getName().contains("Object"))
+                bool new_type_is_object = !!typeid_cast<const DataTypeObject *>(command.data_type.get());
```
Comment (Algunenano) [inline src/Storages/AlterCommands.cpp:1159]: You can do something stupid like:
```
ALTER TABLE testJson
    ADD COLUMN `j2` Tuple(JSON) DEFAULT jString
```

Not sure how that's meant to work, but even with these changes it's still allowed.

**Comment by tavplubix** [comment]
> > It does not.
> 
> Considering the feature is experimental, it's going to be replaced, and nobody will try to fix the issue properly I think closing the tickets is ok.

Yes, and the tickets were already closed with "won't fix", but Nikita reopened them and removed "won't fix" labels, like he's going to fix them for real. But this PR doesn't fix the issues.

File: src/Storages/AlterCommands.cpp (hunk 1 above)
Comment (nikitamikhaylov) [reply src/Storages/AlterCommands.cpp:1159]: Okay, let me traverse the tree of types.

**Comment by nikitamikhaylov** [comment]
@tavplubix We can even deprecate SELECTing from the table if it has JSON columns.

File: src/Storages/AlterCommands.cpp (hunk 1 above)
Comment (nikitamikhaylov) [reply src/Storages/AlterCommands.cpp:1159]: Oh, we already have `hasDynamicSubcolumns`.

**Review by tavplubix — APPROVED** [review]

File: src/Storages/AlterCommands.cpp [hunk 2]
```diff
@@ -1069,6 +1070,13 @@ void AlterCommands::validate(const StoragePtr & table, ContextPtr context) const
         const auto & column_name = command.column_name;
         if (command.type == AlterCommand::ADD_COLUMN)
         {
+            /// FIXME: Adding a new column of type Object(JSON) is broken.
+            /// Looks like there is something around default expression for this column (method `getDefault` is not implemented for the data type Object).
+            /// But after ALTER TABLE ADD COLUMN we need to fill existing rows with something (exactly the default value).
+            /// So we don't allow to do it for now.
+            if (command.data_type && command.data_type->hasDynamicSubcolumns())
```
Comment (tavplubix) [inline src/Storages/AlterCommands.cpp:1077]: How is it possible that it doesn't have data type?

Comment (tavplubix) [reply src/Storages/AlterCommands.cpp:1077]: Ah, it's not: https://github.com/ClickHouse/ClickHouse/blob/64b38ab7e5f0a3a44f7e8d9f55ba71953fb1c683/src/Storages/AlterCommands.cpp#L1090-L1092

Comment (nikitamikhaylov) [reply src/Storages/AlterCommands.cpp:1077]: Looks like it is possible: `ALTER TABLE table2 ADD COLUMN Value2 DEFAULT 'some_string';`

**Comment by nikitamikhaylov** [comment]
Stress tests (tsan) - `Part 7_2_2_0 remains in ZooKeeper after DROP_RANGE 7_0_3_999999999_999999999` - something new for me... Why is it a logical error? Why it is not cleaned from Zookeeper in a background?
