### PR TITLE
Fix cyclic dependency with XML dictionary and StorageDictionary

### LINKED ISSUE #31315: 21.11 unable to start: Cannot attach 1 tables due to cyclic dependencies
21.11.3.6
```
cat /etc/clickhouse-server/node.tsv
1,test

cat /etc/clickhouse-server/node_dictionary.xml
<dictionaries>
    <dictionary>
        <name>node</name>
        <source>
            <file>
                <path>/etc/clickhouse-server/node.tsv</path>
                <format>CSV</format>
            </file>
        </source>
        <lifetime>0</lifetime>
        <layout><flat /></layout>
        <structure>
            <id><name>key</name></id>
            <attribute>
                <name>name</name>
                <type>String</type>
                <null_value></null_value>
            </attribute>
        </structure>
    </dictionary>
</dictionaries>

create table default.node ( key UInt64, name String ) Engine=Dictionary(node);

select * from default.node;
┌─key─┬─name─┐
│   1 │ test │
└─────┴──────┘

/etc/init.d/clickhouse-server restart

<Error> Application: DB::Exception: Cannot attach 1 tables due to cyclic dependencies. See server log for details.
<Information> Application: shutting down
```

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Server might fail to start with `Cannot attach 1 tables due to cyclic dependencies` error if `Dictionary` table looks at XML-dictionary with the same name, it's fixed. Fixes #31315

### CODE REVIEW

File: src/Databases/DDLDependencyVisitor.cpp [hunk 1]
```diff
@@ -20,6 +20,7 @@ TableNamesSet getDependenciesSetFromCreateQuery(ContextPtr global_context, const
     data.global_context = global_context;
     TableLoadingDependenciesVisitor visitor{data};
     visitor.visit(ast);
+    data.dependencies.erase(table);
```
Comment (nikitamikhaylov) [inline src/Databases/DDLDependencyVisitor.cpp:23]: Do I understand correctly that we remove the table itself from its dependencies?

File: src/Databases/TablesLoader.cpp [hunk 2]
```diff
@@ -133,10 +133,14 @@ void TablesLoader::removeUnresolvableDependencies(bool remove_loaded)
...
             return remove_loaded;
-        /// It's XML dictionary. It was loaded before tables and DDL dictionaries.
+        /// It's XML dictionary.
         if (dependency_name.database == metadata.default_database &&
             global_context->getExternalDictionariesLoader().has(dependency_name.table))
-            return remove_loaded;
+        {
+            LOG_WARNING(log, "Tables {} depend on XML dictionary {}, but XML dictionaries are loaded independently."
+                        "Consider converting it to DDL dictionary.", fmt::join(info.dependent_database_objects, ", "), dependency_name);
+            return true;
```
Comment (nikitamikhaylov) [inline src/Databases/TablesLoader.cpp:142]: And the fix is here?

File: src/Databases/DDLDependencyVisitor.cpp (hunk 1 above)
Comment (tavplubix) [reply src/Databases/DDLDependencyVisitor.cpp:23]: Yes, because it does not makes sense and breaks invariants. The problem it that we cannot distinguish XML dictionary from table in default database and that's why table may be added to its dependencies by mistake.

File: src/Databases/TablesLoader.cpp (hunk 2 above)
Comment (tavplubix) [reply src/Databases/TablesLoader.cpp:142]: No, I though that XML dictionaries are loaded before databases, but it was incorrect, so it's better to remove XML dictionaries from dependencies list and print warning, because we cannot control this part of loading order in `TablesLoader`

**Review by nikitamikhaylov — APPROVED** [review]
