### PR TITLE
Fix optimization of disjunctions chain in distributed queries

### LINKED ISSUE #28581: Generated IN clause tuple not compatible in distributed queries
Version 21.8.3

With  `legacy_column_name_of_tuple_literal` set to 0, this query succeeds:

```
SELECT countIf(chi_count, video_level IN ('Video_3', 'Video_4', 'Video_5', 'Video_6', ' Video_7', 'Video_8', 'Video_9')) AS LBR
FROM comcast_xcr_maple.atsec_cdvr_1m
WHERE datetime > (now() - 300)
```

This query fails:

```
SELECT countIf(chi_count, (video_level = 'Video_3') OR (video_level = 'Video_4') OR (video_level = 'Video_5') OR (video_level = 'Video_6') OR (video_level = 'Video_7') OR (video_level = 'Video_8') OR (video_level = 'Video_9')) AS LBR
FROM comcast_xcr_maple.atsec_cdvr_1m
WHERE datetime > (now() - 300)

Received exception from server (version 21.8.3):
Code: 10. DB::Exception: Received from localhost:9440. DB::Exception: Not found column countIf(chi_count, in(video_level, tuple('Video_3', 'Video_4', 'Video_5', 'Video_6', 'Video_7', 'Video_8', 'Video_9'))) in block. There are only columns: countIf(chi_count, in(video_level, ('Video_3', 'Video_4', 'Video_5', 'Video_6', 'Video_7', 'Video_8', 'Video_9'))): While executing Remote. 
```

Both queries work with `legacy_column_name_of_tuple_literal` set to 1.  Presumably whatever code converts the multiple OR statements to a tuple uses the "old" column name and is incompatible with the new approach.

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix transformation of disjunctions chain to `IN` (controlled by settings `optimize_min_equality_disjunction_chain_length`) in distributed queries with settings `legacy_column_name_of_tuple_literal = 0`.

Fixes #28581.

### CODE REVIEW

File: src/Interpreters/LogicalExpressionsOptimizer.cpp [hunk 1]
```diff
@@ -250,14 +247,11 @@ void LogicalExpressionsOptimizer::addInExpression(const DisjunctiveEqualityChain
         equals_expr_lhs = operands[0];
     }
 
-    auto tuple_function = std::make_shared<ASTFunction>();
-    tuple_function->name = "tuple";
-    tuple_function->arguments = value_list;
-    tuple_function->children.push_back(tuple_function->arguments);
+    auto tuple_literal = std::make_shared<ASTLiteral>(std::move(tuple));
```
Comment (novikd) [inline src/Interpreters/LogicalExpressionsOptimizer.cpp:250]: Why do you create `ASTLiteral`? If I'm not mistaken tuple is not a literal.

Comment (CurtizJ) [reply src/Interpreters/LogicalExpressionsOptimizer.cpp:250]: Tuple can be literal, if it's all elements are literals. So, that's a problem, because we create tuple as function, format it in form of `(x1, x2, ..., x_n)` and send query to the remote shard, where this construction is parsed as literal, because all elements are literals.

**Review by novikd — APPROVED** [review]
