### PR TITLE
PR: fix join with materialized view

### LINKED ISSUE #89806: PR: incorrect query result with MV and JOIN
### Company or project name

_No response_

### Describe the unexpected behaviour

Query with JOIN and MV on left side can produce incorrect result

### How to reproduce

```sql
CREATE TABLE n1 (key UInt64, value String) ENGINE = MergeTree ORDER BY key SETTINGS index_granularity=1;

CREATE TABLE n2 (key UInt64, value Int64) ENGINE = MergeTree ORDER BY key SETTINGS index_granularity=1;

CREATE TABLE n1_n2_join (k UInt64, v1 String, v2 Int64) ENGINE = MergeTree ORDER BY k;

CREATE MATERIALIZED VIEW mv TO n1_n2_join
AS SELECT n1.key as k, n1.value as v1, n2.value as v2 from n1 JOIN n2 ON n1.key = n2.key ORDER BY n1.key;

INSERT INTO n2 SELECT number, -number FROM numbers(10);
INSERT INTO n1 SELECT number as key, toString(key) FROM numbers(10) settings enable_parallel_replicas=0;

CREATE TABLE n3 (key UInt64, value String) ENGINE = MergeTree ORDER BY key SETTINGS index_granularity=1;
INSERT INTO n3 SELECT number, toString(number + 100) FROM numbers(10);

SET enable_parallel_replicas=1, max_parallel_replicas=3, cluster_for_parallel_replicas='test_cluster_one_shard_three_replicas_localhost', parallel_replicas_for_non_replicated_merge_tree=1;
SELECT * FROM mv JOIN n3 ON mv.k = n3.key ORDER BY mv.k, n3.key;
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devcrafter**
Closes https://github.com/ClickHouse/ClickHouse/issues/89806

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: src/Storages/StorageMaterializedView.h [hunk 1]
```diff
@@ -27,6 +27,7 @@ class StorageMaterializedView final : public IStorage, WithMutableContext
     std::string getName() const override { return "MaterializedView"; }
     bool isView() const override { return true; }
     bool isRemote() const override;
+    bool isMergeTree() const override { return getTargetTable()->isMergeTree(); }
```
Comment (KochetovNicolai) [inline src/Storages/StorageMaterializedView.h]: It's ok, but as long as there is no comment in IStorage, I don't understand what the semantics of this method are.

In which place is the check used?
Maybe it would be better to implicitely typeidcast to MV in the call-plance?

**Review by KochetovNicolai — APPROVED** [review]

**Review by KochetovNicolai — APPROVED** [review]
