### PR TITLE
Fix reading from async read buffer with direct io

### LINKED ISSUE #39465: `CANNOT_READ_ALL_DATA` with enabled uncompressed cache and direct io (00024_random_counters)
**Describe the bug**
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/0/b4eae948898b103e8ee145c650108da4c80e2a53/stateful_tests__release__actions_.html)

**How to reproduce**
Run test `00024_random_counters.sql` with settings `--use_uncompressed_cache=1 --min_bytes_to_use_direct_io=1`

```
clickhouse-client -q "system drop uncompressed cache" && cat queries/1_stateful/00024_random_counters.sql | clickhouse-client -n --use_uncompressed_cache=1 --min_bytes_to_use_direct_io=1 > /dev/null
Received exception from server (version 22.7.1):
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 25.: (while reading column Sign): (while reading from part ./data/datasets/visits_v1/20140317_20140323_3_4_1/ from mark 204 with max_rows_to_read = 8192): While executing MergeTreeInOrder. (CANNOT_READ_ALL_DATA)
(query: SELECT uniq(UserID), sum(Sign) FROM datasets.visits_v1 WHERE CounterID = 33436573;)
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix rare bug in asynchronous reading (with setting `local_filesystem_read_method='pread_threadpool'`) with enabled `O_DIRECT` (enabled by setting `min_bytes_to_use_direct_io`).

Fixes #39465.

### CODE REVIEW

File: src/IO/AsynchronousReadBufferFromFileDescriptor.cpp [hunk 1]
```diff
@@ -109,7 +112,10 @@ bool AsynchronousReadBufferFromFileDescriptor::nextImpl()
         auto [size, offset] = asyncReadInto(memory.data(), memory.size()).get();
         file_offset_of_buffer_end += size;
 
-        if (size)
```
Comment (CurtizJ) [inline src/IO/AsynchronousReadBufferFromFileDescriptor.cpp:112]: Previously, if we have read data with offset till the end of file, we returned `true` for `nextImpl` call, which could lead to mistakenly returning `false` from `eof()` and unexpected reading after `eof`.

**Review by kssenii — APPROVED** [review]
