### PR TITLE
Fix bugs in show database

### LINKED ISSUE #61262: Fuzzer crash: Formatting of `SHOW CREATE DATABASE`
```
./build_msan/programs/clickhouse 
ClickHouse local version 24.3.1.1.

Mordor :) SHOW DATABASE default

SHOW CREATE DATABASE default

Query id: 45c27d42-a07e-46fe-8ab2-d7a68e49e6c3

2024.03.12 18:14:20.828274 [ 416344 ] {45c27d42-a07e-46fe-8ab2-d7a68e49e6c3} <Fatal> : Logical error: 'table'.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix bugs in show database

2 different bugs:
* Show create database was broken (and crashing) for overlay databases. Now it just outputs `SHOW DATABASE $name`, which is not correct, but it's better.
* Fixes a constant crash of the fuzzer while fuzzing `SHOW DATABASE` queries.

Closes https://github.com/ClickHouse/ClickHouse/issues/61262

### CODE REVIEW

File: src/Parsers/TablePropertiesQueriesASTs.h [hunk 1]
```diff
@@ -85,6 +85,15 @@ using ASTShowCreateDictionaryQuery = ASTQueryWithTableAndOutputImpl<ASTShowCreat
 
 class ASTExistsDatabaseQuery : public ASTQueryWithTableAndOutputImpl<ASTExistsDatabaseQueryIDAndQueryNames>
 {
+public:
+    ASTPtr clone() const override
```
Comment (Algunenano) [inline src/Parsers/TablePropertiesQueriesASTs.h:89]: The fix is not obvious at all because it's technically not here but in the default implementation of ASTQueryWithTableAndOutputImpl::clone. The default implementation does this:

```
auto res = std::make_shared<ASTQueryWithTableAndOutputImpl<AstIDAndQueryNames>>(*this);
```

This means that clone does not create a ASTExistsDatabaseQuery, but a ASTQueryWithTableAndOutputImpl<ASTExistsDatabaseQueryIDAndQueryNames>, which look the same but they are not as they don't have the same virtual pointer table. Later on, when `formatQueryImpl` is called on the cloned AST, we call the function of the base class (and crash) and not the one of the derived class that we intended.

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 15484bedadf62d05fdcaea842ce9d86bdafe57f3 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61269/15484bedadf62d05fdcaea842ce9d86bdafe57f3/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @Algunenano @alexey-milovidov — while reviewing this PR I found the following:

- **Coverage gap:** `ASTShowCreateDatabaseQuery::clone` and `ASTExistsDatabaseQuery::clone` overrides not exercised by any stateless fuzzer test — https://github.com/ClickHouse/ClickHouse/pull/103924

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
