### PR TITLE
Handle unprocessed left blocks in `GraceHashJoin`

### LINKED ISSUE #96510: Grace hash bad result since v25.8
### Describe the bug

When changing the value of `grace_hash_join_initial_buckets`, `grace_join` gives a different result starting on v25.8. cc @vdimir can you look at this?

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/daceae4b-497d-47de-9ba6-3fb24c99810b

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix incorrect result when `grace_hash` algorithm is used with non-equi joins and left block cannot be processed completely because of the size constraints on the join result.

Closes https://github.com/ClickHouse/ClickHouse/issues/96510

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.3.1.25`
- Backported to: `26.2.1.1118`, `26.1.4.23`, `25.12.7.23`, `25.11.10.23`, `25.8.17.33`

### CODE REVIEW

File: src/Interpreters/HashJoin/HashJoinMethods.h [hunk 1]
```diff
@@ -193,7 +193,7 @@ class HashJoinMethods
 
     /// First to collect all matched rows refs by join keys, then filter out rows which are not true in additional filter expression.
     template <typename KeyGetter, typename Map, typename AddedColumns>
-    static size_t joinRightColumnsWithAddtitionalFilter(
+    static size_t joinRightColumnsWithAdditionalFilter(
```
Comment (antaljanosbenjamin) [inline src/Interpreters/HashJoin/HashJoinMethods.h:196]: This is just simple typo fixes, but as I noticed them, thought I will fix them.

**Review by vdimir — APPROVED** [review]
👍 

For reference: bug introduced in https://github.com/ClickHouse/ClickHouse/pull/91664
