### PR TITLE
Fix possible hung/deadlock on query cancellation

### LINKED ISSUE #41001: Lock order inversion in OvercommitTracker
https://s3.amazonaws.com/clickhouse-test-reports/0/8ea7b9c9784f7014dccb4fe0dfd269265126a30d/stress_test__msan_.html

Post-processed traces: https://pastila.nl/?0006a09d/4a3864799d8b23c3998deeefcdca5d8f
Post-processed traces without boring threads: https://pastila.nl/?0006a09d/f342d95a823d513df62d68a5d8a1a50b

Explanation: https://pastila.nl/?000fcc82/3a48f372d3410a8691d50cb5647b2c20

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible hung/deadlock on query cancellation (`KILL QUERY` or server shutdown).

Right due to graceful cancellation of the query, it is possible to hung
accepting new queries or even have a deadlock, this is because
cancellation is done while acquiring ProcessListBase::mutex.

This PR also adds a test, that reproduces the problem.

Fixes: #41001 (cc @tavplubix )
Refs: #41052 (cc @novikd )
Refs: #41343 

_Also note, that I've tried to keep this patch simple, since this is a major problem, that should be backported._

### CODE REVIEW

**Comment by azat** [comment]
>[Integration tests (release) [1/2] — fail: 1, passed: 1030, flaky: 0](https://s3.amazonaws.com/clickhouse-test-reports/41467/61a6e1b0c19280e9ea8ca7200d81e886a2120b4e/integration_tests__release__[1/2].html)

- `test_hive_query/test.py::test_text_count` - #41468

>[Stress test (msan) — check_status.tsv doesn't exists](https://s3.amazonaws.com/clickhouse-test-reports/41467/61a6e1b0c19280e9ea8ca7200d81e886a2120b4e/stress_test__msan_.html)

Job had been killed or something like this:

```
Error: The operation was canceled.
Error: The log was not found. It may have been deleted based on retention settings.
```

File: src/Interpreters/ProcessList.cpp [hunk 1]
```diff
@@ -297,6 +297,13 @@ ProcessListEntry::~ProcessListEntry()
         }
     }
 
+    /// Wait for the query if it is in the cancellation right now.
+    parent.cancelled.cv.wait(lock.lock, [&]()
+    {
+        auto & processes = parent.cancelled.processes;
+        return std::find(processes.begin(), processes.end(), &*it) == processes.end();
+    });
```
Comment (CheSema) [inline src/Interpreters/ProcessList.cpp:305]: Could that method be the member function of CancelledProcesses?

Comment (azat) [reply src/Interpreters/ProcessList.cpp:305]: This looks like a local thing, I don't think that it worth to move it into the CancelledProcesses.
And actually that CancelledProcesses was added only to group related fields together.

File: src/Interpreters/ProcessList.h [hunk 2]
```diff
@@ -331,6 +331,16 @@ class ProcessList : public ProcessListBase
 
     /// List of queries
     Container processes;
+    /// List of queries for which cancellaion is in progress
+    struct CancelledProcesses
+    {
+        using Container = std::list<QueryStatus *>;
+        using Iterator = Container::iterator;
+
+        Container processes;
```
Comment (tavplubix) [inline src/Interpreters/ProcessList.h:340]: Do we really need this list? maybe simply add `is_cancelled` flag to ProcessListEntry?

File: src/Interpreters/ProcessList.cpp [hunk 3]
```diff
@@ -430,12 +437,37 @@ QueryStatus * ProcessList::tryGetProcessListElement(const String & current_query
...
+        cancelled_it = cancelled.processes.insert(cancelled.processes.end(), elem);
+    }
 
-    QueryStatus * elem = tryGetProcessListElement(current_query_id, current_user);
+    SCOPE_EXIT({
+        DENY_ALLOCATIONS_IN_SCOPE;
 
-    if (!elem)
-        return CancellationCode::NotFound;
+        auto lock = unsafeLock();
```
Comment (tavplubix) [inline src/Interpreters/ProcessList.cpp:467]: `unsafeLock` does not block overcommit tracker. On allocations are possible here, but there's a deallocation. Is it possible to enter overcommit tracker on deallocation?

File: src/Interpreters/ProcessList.cpp [hunk 4]
```diff
@@ -430,12 +437,37 @@ QueryStatus * ProcessList::tryGetProcessListElement(const String & current_query
 
 CancellationCode ProcessList::sendCancelToQuery(const String & current_query_id, const String & current_user, bool kill)
 {
-    auto lock = safeLock();
+    QueryStatus * elem;
+    CancelledProcesses::Iterator cancelled_it;
+
+    /// Cancelling the query should be done without the lock.
```
Comment (tavplubix) [inline src/Interpreters/ProcessList.cpp:443]: Similar fix is required for `killAllQueries` to fix https://github.com/ClickHouse/ClickHouse/issues/41001 completely

**Comment by tavplubix** [comment]
Also there's another solution: simply use shared (or intrusive) pointer to QueryStatus

File: src/Interpreters/ProcessList.cpp (hunk 3 above)
Comment (azat) [reply src/Interpreters/ProcessList.cpp:467]: Actually yes, it is better to use `safeLock` here, indeed.

**Comment by azat** [comment]
>Also there's another solution: simply use shared (or intrusive) pointer to QueryStatus

I thought about this, but decided not to, since in this case after destructing `ProcessListEntry` the query will still exist.
Plus who knows, maybe there are other caveats possible...

File: src/Interpreters/ProcessList.h (hunk 2 above)
Comment (azat) [reply src/Interpreters/ProcessList.h:340]: Yep, this will be better and simpler.

**Comment by tavplubix** [comment]
We discussed it with @novikd and decided that this fix is mostly fine, only need to replace the list with flag and update `killAllQueries`

**Comment by azat** [comment]
Also added a ``no-backward-compatibility-check` tag.

**Review by tavplubix — APPROVED** [review]

File: src/Interpreters/ProcessList.cpp [hunk 5]
```diff
@@ -430,23 +433,62 @@ QueryStatus * ProcessList::tryGetProcessListElement(const String & current_query
...
 
 void ProcessList::killAllQueries()
 {
-    auto lock = safeLock();
+    std::list<QueryStatus *> cancelled_processes;
+
+    SCOPE_EXIT({
+        auto lock = safeLock();
+        for (auto & cancelled_process : cancelled_processes)
+            cancelled_process->is_cancelling = false;
```
Comment (novikd) [inline src/Interpreters/ProcessList.cpp:477]: Don't we need to do a `notify_all` here?

File: src/Interpreters/ProcessList.cpp [hunk 6]
```diff
@@ -430,23 +433,62 @@ QueryStatus * ProcessList::tryGetProcessListElement(const String & current_query
...
+    });
 
     return elem->cancelQuery(kill);
 }
 
 
 void ProcessList::killAllQueries()
 {
-    auto lock = safeLock();
+    std::list<QueryStatus *> cancelled_processes;
```
Comment (novikd) [inline src/Interpreters/ProcessList.cpp:472]: Why not a vector?

File: src/Interpreters/ProcessList.cpp (hunk 5 above)
Comment (azat) [reply src/Interpreters/ProcessList.cpp:477]: Indeed, nice catch! Fixed.

File: src/Interpreters/ProcessList.cpp (hunk 6 above)
Comment (azat) [reply src/Interpreters/ProcessList.cpp]: Yep, good idea. Done.

**Comment by filimonov** [comment]
Backport to 22.8? 

BTW: do you know guys why it start happening on 22.8?

**Comment by azat** [comment]
>Do you observe it in production?

I did see this in produciton.

> It's hard to say why it reproduced in 22.8 more often.

I can't say here anything because before that cluster that started experience issues has very old clickhouse verison, and the one that uses 22.8 (almost) do not have massing KILL QUERY and plus it has overcommit tracker disabled.

> There were fixed other problems for ProcessList and OvercommitTracker interop. But anyway I expect it to be super rare because it requires:

Actually not that rare, it is enough to have remote queries and a `KILL` for it.
And for example `chproxy` send `KILL` automatically for queries that exceed specific timeframe.

**Comment by alexey-milovidov** [comment]
@azat this fix is incorrect, moreover, it introduced a race condition.

@novikd 
> Backport to 22.8? Sure

This was a mistake.

**Comment by azat** [comment]
> @azat this fix is incorrect, moreover, it introduced a race condition.

Are you talking about #42346? I don't see how this patch may introduce this problem.

**Comment by tavplubix** [comment]
> Are you talking about #42346? I don't see how this patch may introduce this problem.

I suppose yes, but I don't see it too. Yes, `QueryStatus::cancelQuery` is called without `ProcessListBase::mutex` now, but `BlockIO::onFinish()` and `QueryPipeline::reset()` are called without locking this mutex anyway, so locking it for `QueryStatus::cancelQuery` will not protect from the race condition described in https://github.com/ClickHouse/ClickHouse/issues/42346. But maybe I'm missing something.

**Comment by alexey-milovidov** [comment]
@tavplubix @azat there is another race condition, directly related to this change.

File: src/Interpreters/ProcessList.cpp [hunk 7]
```diff
@@ -430,23 +433,64 @@ QueryStatus * ProcessList::tryGetProcessListElement(const String & current_query
...
+    }
 
-    QueryStatus * elem = tryGetProcessListElement(current_query_id, current_user);
+    SCOPE_EXIT({
+        DENY_ALLOCATIONS_IN_SCOPE;
 
-    if (!elem)
-        return CancellationCode::NotFound;
+        auto lock = unsafeLock();
+        elem->is_cancelling = false;
```
Comment (alexey-milovidov) [inline src/Interpreters/ProcessList.cpp:462]: Race condition in accessing this variable when `elem` is already destroyed.

**Comment by alexey-milovidov** [comment]
It is trivially reproduced by my test.

File: src/Interpreters/ProcessList.cpp (hunk 7 above)
Comment (azat) [reply src/Interpreters/ProcessList.cpp:462]: This should not happen, since dtor should wait, here - https://github.com/ClickHouse/ClickHouse/pull/41467/files#diff-c6034fc738bf184e41e5218132c88c572ee70ff8cad9964cd6a42643009ecf99R300-R301
