### PR TITLE
Fix filter pushdown through legacy JoinStep with join_use_nulls

### LINKED ISSUE #98167: Logical error: Unexpected return type from A. Expected B. Got C. Action: (STID: 1611-3d11)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: Unexpected return type from A. Expected B. Got C. Action: (STID: 1611-3d11)
CI report: [Stress test (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=95590&sha=f121f0768b67dad0ee430402386485d06f8831af&name_0=PR&name_1=Stress%20test%20%28amd_ubsan%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiBVbmV4cGVjdGVkIHJldHVybiB0eXBlIGZyb20gQS4gRXhwZWN0ZWQgQi4gR290IEMuIEFjdGlvbjogKFNUSUQ6IDE2MTEtM2QxMSknCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdTdHJlc3MgdGVzdCAoYW1kX3Vic2FuKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBiYXNlX3JlZiBJTiAoJ21hc3RlcicpKQogICAgQU5EIHRlc3RfY29udGV4dF9yYXcgTElLRSAnJUV4Y2VwdGlvbjolJwpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
Error:
Logical error: 'Unexpected return type from less. Expected Nullable(UInt8). Got UInt8. Action:
FUNCTION less(arrayJoin([3, 4, 5]) : 2, 10 :: 1) -> less(k, 10) Nullable(UInt8) : 0,
input block structure:arrayJoin([3, 4, 5]) UInt8 UInt8(size = 0), 10 UInt8 Const(size = 0, UInt8(size = 1))'.
---

Stack trace:
__pthread_kill @ 0x00000000000969fd
raise @ 0x0000000000042476
__ieee754_lgamma_r @ 0x00000000000287f3
./ci/tmp/build/./src/Common/Exception.cpp:60:5: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x000000001f97541d
./ci/tmp/build/./src/Common/Exception.cpp:93:13: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000001f97623f
./ci/tmp/build/./src/Common/Exception.cpp:146:19: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001f9765b2
./src/Common/Exception.h:171:100: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000001415eca3
./src/Common/Exception.h:57:54: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000001415e241
./src/Common/Exception.h:189:77: DB::Exception::Exception<String, String, String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&, String&&, String&&) @ 0x0000000017acf877
./ci/tmp/build/./src/Interpreters/ExpressionActions.cpp:695:27: DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool, bool, bool) @ 0x0000000028c7e2d5
./ci/tmp/build/./src/Interpreters/ExpressionActions.cpp:835:13: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const @ 0x0000000028c7ba27
./ci/tmp/build/./src/Interpreters/ExpressionActions.cpp:881:5: DB::ExpressionActions::execute(DB::Block&, bool, bool) const @ 0x0000000028c7e6ff
./ci/tmp/build/./src/Processors/Transforms/FilterTransform.cpp:88:21: DB::FilterTransform::FilterTransform(std::shared_ptr<DB::Block const>, std::shared_ptr<DB::ExpressionActions>, String, bool, bool, std::shared_ptr<std::atomic<unsigned long>>, std::optional<std::pair<unsigned long, String>>) @ 0x000000002f3a3802
./contrib/llvm-project/libcxx/include/__memory/construct_at.h:38:49: DB::FilterTransform* std::construct_at[abi:fe210105]<DB::FilterTransform, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t, std::optional<std::pair<unsigned long, String>>&, DB::FilterTransform*>(DB::FilterTransform*, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t&&, std::optional<std::pair<unsigned long, String>>&) @ 0x000000002f78c81e
inlined from ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:46: DB::FilterTransform* std::__construct_at[abi:fe210105]<DB::FilterTransform, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t, std::optional<std::pair<unsigned long, String>>&, DB::FilterTransform*>(DB::FilterTransform*, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t&&, std::optional<std::pair<unsigned long, String>>&)
inlined from ./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:302: void std::allocator_traits<std::allocator<DB::FilterTransform>>::construct[abi:fe210105]<DB::FilterTransform, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t, std::optional<std::pair<unsigned long, String>>&, 0>(std::allocator<DB::FilterTransform>&, DB::FilterTransform*, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t&&, std::optional<std::pair<unsigned long, String>>&)
inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:162: __shared_ptr_emplace<const std::shared_ptr<const DB::Block> &, std::shared_ptr<DB::ExpressionActions> &, std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, bool &, bool &, std::nullptr_t, std::optional<std::pair<unsigned long, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > &, std::allocator<DB::FilterTransform>, 0>
./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:736:10: std::shared_ptr<DB::FilterTransform> std::allocate_shared[abi:fe210105]<DB::FilterTransform, std::allocator<DB::FilterTransform>, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t, std::optional<std::pair<unsigned long, String>>&, 0>(std::allocator<DB::FilterTransform> const&, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t&&, std::optional<std::pair<unsigned long, String>>&) @ 0x000000002f78c612
inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:744: std::shared_ptr<DB::FilterTransform> std::make_shared[abi:fe210105]<DB::FilterTransform, std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t, std::optional<std::pair<unsigned long, String>>&, 0>(std::shared_ptr<DB::Block const> const&, std::shared_ptr<DB::ExpressionActions>&, String&, bool&, bool&, std::nullptr_t&&, std::optional<std::pair<unsigned long, String>>&)
inlined from ./ci/tmp/build/./src/Processors/QueryPlan/FilterStep.cpp:170: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType>::type std::__invoke[abi:fe210105]<DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType>(DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType&&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:334: std::shared_ptr<DB::IProcessor> std::__invoke_void_return_wrapper<std::shared_ptr<DB::IProcessor>, false>::__call[abi:fe210105]<DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType>(DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType&&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: std::shared_ptr<DB::IProcessor> std::__invoke_r[abi:fe210105]<std::shared_ptr<DB::IProcessor>, DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType>(DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&)::$_1&, std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType&&)
./contrib/llvm-project/libcxx/include/__functional/function.h:450:10: ? @ 0x000000002f78a225
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
./ci/tmp/build/./src/QueryPipeline/Pipe.cpp:589:12: DB::Pipe::addSimpleTransform(std::function<std::shared_ptr<DB::IProcessor> (std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType)> const&)::$_0::operator()(DB::OutputPort*&, DB::Pipe::StreamType) const @ 0x0000000027484114
./ci/tmp/build/./src/QueryPipeline/Pipe.cpp:628:9: DB::Pipe::addSimpleTransform(std::function<std::shared_ptr<DB::IProcessor> (std::shared_ptr<DB::Block const> const&, DB::Pipe::StreamType)> const&) @ 0x0000000027483ecb
./ci/tmp/build/./src/Processors/QueryPlan/FilterStep.cpp:167:14: DB::FilterStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x000000002f78721d
./ci/tmp/build/./src/Processors/QueryPlan/ITransformingStep.cpp:21:9: DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000002f79d1e4
./ci/tmp/build/./src/Processors/QueryPlan/QueryPlan.cpp:209:47: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000002f7fa2e4
./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:396:31: DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000028e983b7
./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1751:40: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x00000000292da700
./ci/tmp/build/./src/Interpreters/executeQuery.cpp:2076:11: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000292d4ae3
./ci/tmp/build/./src/Server/TCPHandler.cpp:788:68: DB::TCPHandler::runImpl() @ 0x000000002edf541c
./ci/tmp/build/./src/Server/TCPHandler.cpp:2912:9: DB::TCPHandler::run() @ 0x000000002ee19f9c
./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3: Poco::Net::TCPServerConnection::start() @ 0x0000000034f39ecc
./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:42: Poco::Net::TCPServerDispatcher::run() @ 0x0000000034f3a7b0
./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14: Poco::PooledThread::run() @ 0x0000000034ec255a
./base/poco/Foundation/src/Thread_POSIX.cpp:341:27: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000034ebec53
start_thread @ 0x0000000000094ac3
__clone3 @ 0x00000000001268c0
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
## Summary
- Fix exception "Unexpected return type from `less`. Expected `Nullable(UInt8)`. Got `UInt8`" that occurs when filter pushdown moves a filter expression through a legacy `JoinStep` with `join_use_nulls` enabled
- Restore the type equality check in `get_available_columns_for_filter` specifically for the legacy `JoinStep` path, which was inadvertently removed in #95968
- The `JoinStepLogical` path is unaffected — it has its own type adjustment mechanism via `fix_predicate_for_join_logical_step`

Closes #98167

CI report: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=ededb4c6063844d24eee5d3023dfe17912307ffa&name_0=MasterCI&name_1=Stress%20test%20%28azure%2C%20amd_msan%29

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by alexey-milovidov — COMMENTED** [review]
A straightforward fix - just inhibit the optimization in certain cases for the obsolete legacy JOIN step.

File: tests/queries/0_stateless/03835_filter_pushdown_join_use_nulls_legacy.sql [hunk 1]
```diff
@@ -0,0 +1,15 @@
+-- Regression test: filter pushdown through legacy JoinStep with join_use_nulls
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/03835_filter_pushdown_join_use_nulls_legacy.sql:1]: Does not reproduce.

Comment (alexey-milovidov) [reply tests/queries/0_stateless/03835_filter_pushdown_join_use_nulls_legacy.sql:1]: Now it does.
