### PR TITLE
Fix 77452

### LINKED ISSUE #77452: `02597_projection_materialize_and_replication` is flaky
### Describe the bug

[in PR](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76813&sha=latest&name_0=PR&name_1=Stateless+tests+%28release%2C+old+analyzer%2C+s3%2C+DatabaseReplicated%2C+1%2F2%29&name_2=02597_projection_materialize_and_replication) and in [master](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=39632ec1cec643ac223587602b86c3daeb1dce82&name_0=MasterCI&name_1=Stateless%20tests%20%28release%2C%20old%20analyzer%2C%20s3%2C%20DatabaseReplicated%2C%201%2F2%29)

```
2025-03-10 16:16:42 Reason: return code: 70
2025-03-10 16:16:42 The query succeeded but the server error '36' was expected (query: ALTER TABLE test DROP PROJECTION d_order SETTINGS mutations_sync = 2; --{serverError BAD_ARGUMENTS}).
2025-03-10 16:16:42 Received exception from server (version 25.3.1):
2025-03-10 16:16:42 Code: 582. DB::Exception: Received from localhost:9000. DB::Exception: There is no projection d_order in table. (NO_SUCH_PROJECTION_IN_TABLE)
2025-03-10 16:16:42 (query: ALTER TABLE test DROP PROJECTION d_order SETTINGS mutations_sync = 2;)
2025-03-10 16:16:42 , result:
2025-03-10 16:16:42
2025-03-10 16:16:42
2025-03-10 16:16:42
2025-03-10 16:16:42 stdout:
2025-03-10 16:16:42
2025-03-10 16:16:42
2025-03-10 16:16:42 Settings used in the test: --max_insert_threads 12 --group_by_two_level_threshold 1 --group_by_two_level_threshold_bytes 1838944 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 12871955 --max_read_buffer_size 546392 --prefer_localhost_replica 1 --max_block_size 28761 --max_joined_block_size_rows 29211 --max_threads 3 --optimize_append_index 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 1 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 7 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 46578670 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 16Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_aggregate_expressions 1 --compile_sort_description 1 --merge_tree_coarse_index_granularity 29 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 430315949 --min_compress_block_size 1249724 --max_compress_block_size 2598771 --merge_tree_compact_parts_min_granules_to_multibuffer_read 14 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 2313779 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 0 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone America/Hermosillo --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.39 --prefer_external_sort_block_bytes 100000000 --cross_join_min_rows_to_compress 1 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 0 --max_parsing_threads 1 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 0 --query_plan_join_swap_table auto --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_query_condition_cache 1 --max_bytes_before_external_sort 10737418240 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0
2025-03-10 16:16:42
2025-03-10 16:16:42 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 453736797 --index_granularity_bytes 19769481 --merge_max_block_size 1835 --index_granularity 31091 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 85655 --primary_key_compress_block_size 50584 --replace_long_file_name_to_hash 0 --max_file_name_length 110 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 90507366 --compact_parts_max_granules_to_buffer 168 --compact_parts_merge_max_bytes_to_prefetch_part 30340711 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 70 --old_parts_lifetime 480 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0
2025-03-10 16:16:42
2025-03-10 16:16:42 Database: test_1c9yyeyq
```

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by PedroTadim**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes
Fix test flakiness. The client didn't wait for `ALTER ADD PROJECTION` before attempting to drop it.

Closes https://github.com/ClickHouse/ClickHouse/issues/77452

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by Algunenano** [comment]
> @[PedroTadim](https://github.com/PedroTadim) PedroTadim enabled auto-merge [1 hour ago](https://github.com/ClickHouse/ClickHouse/pull/78904#event-17190961889)

Please, describe the PR / fix properly and wait for review

File: tests/queries/0_stateless/02597_projection_materialize_and_replication.sql [hunk 1]
```diff
@@ -14,13 +14,20 @@ set mutations_sync=0;
 
 ALTER TABLE test UPDATE d = d || toString(sleepEachRow(0.3)) where 1;
 
-ALTER TABLE test ADD PROJECTION d_order ( SELECT min(c_id) GROUP BY `d`);
-ALTER TABLE test MATERIALIZE PROJECTION d_order;
-ALTER TABLE test DROP PROJECTION d_order SETTINGS mutations_sync = 2; --{serverError BAD_ARGUMENTS}
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/02597_projection_materialize_and_replication.sql:19]: Based on the [PR](https://github.com/ClickHouse/ClickHouse/pull/50181/files#diff-2001369ec75a93211af30ee6dc47c9903e9a3171f5085ca24db8ebbe386860bb) that introduced this test this exception is the gist of the test. Removing it basically makes the tests useless.

Comment (antaljanosbenjamin) [reply tests/queries/0_stateless/02597_projection_materialize_and_replication.sql]: After talking in private we discussed that these changes might lead to a test that is not checking anymore what is was meant to check. Therefore we had two options:
1. remove the test
2. try to make it less flaky

We opted for no2 by increasing the length of the mutation. Hopefully this will reduce the flakyness of the tests. Theoretically it can still fail, but hopefully the increase runtime of the mutation will reduce its flakyness very close to zero (it failed 0 times out of 100 in flaky test check). The length of the test increased to 30 seconds in worst case, but unfortunately we couldn't come up with a better solution.

**Review by antaljanosbenjamin — APPROVED** [review]
