### PR TITLE
Fix parallel formatting and progress flicker in clickhouse-client

### LINKED ISSUE #30872: Progress bar is flickering when saving result to file.
If you execute this query in interactive mode of `clickhouse-client`:

```
SELECT WatchID::Int64, JavaEnable, toValidUTF8(Title), GoodEvent, EventTime, EventDate, CounterID::Int32, ClientIP::Int32, RegionID::Int32, UserID::Int64, CounterClass, OS, UserAgent, toValidUTF8(URL), toValidUTF8(Referer), Refresh, RefererCategoryID::Int16, RefererRegionID::Int32, URLCategoryID::Int16, URLRegionID::Int32, ResolutionWidth::Int16, ResolutionHeight::Int16, ResolutionDepth, FlashMajor, FlashMinor, FlashMinor2, NetMajor, NetMinor, UserAgentMajor::Int16, UserAgentMinor, CookieEnable, JavascriptEnable, IsMobile, MobilePhone, toValidUTF8(MobilePhoneModel), toValidUTF8(Params), IPNetworkID::Int32, TraficSourceID, SearchEngineID::Int16, toValidUTF8(SearchPhrase), AdvEngineID, IsArtifical, WindowClientWidth::Int16, WindowClientHeight::Int16, ClientTimeZone, ClientEventTime, SilverlightVersion1, SilverlightVersion2, SilverlightVersion3::Int32, SilverlightVersion4::Int16, toValidUTF8(PageCharset), CodeVersion::Int32, IsLink, IsDownload, IsNotBounce, FUniqID::Int64, toValidUTF8(OriginalURL), HID::Int32, IsOldCounter, IsEvent, IsParameter, DontCountHits, WithHash, HitColor, LocalEventTime, Age, Sex, Income, Interests::Int16, Robotness, RemoteIP::Int32, WindowName, OpenerName, HistoryLength, BrowserLanguage, BrowserCountry, toValidUTF8(SocialNetwork), toValidUTF8(SocialAction), HTTPError, SendTiming, DNSTiming, ConnectTiming, ResponseStartTiming, ResponseEndTiming, FetchTiming, SocialSourceNetworkID, toValidUTF8(SocialSourcePage), ParamPrice, toValidUTF8(ParamOrderID), ParamCurrency, ParamCurrencyID::Int16, OpenstatServiceName, OpenstatCampaignID, OpenstatAdID, OpenstatSourceID, UTMSource, UTMMedium, UTMCampaign, UTMContent, UTMTerm, FromTag, HasGCLID, RefererHash::Int64, URLHash::Int64, CLID::Int32
FROM hits_100m_obfuscated
INTO OUTFILE 'dump.csv'
FORMAT CSV
```

progress bar is displaying only occasionally and instantly cleared.

### LINKED ISSUE #30873: Looks like parallel formatting is not activated.
**Describe the situation**

```
SELECT * FROM test.hits INTO OUTFILE 'dump.csv' FORMAT CSV

8873898 rows in set. Elapsed: 32.487 sec. Processed 8.87 million rows, 8.46 GB (273.15 thousand rows/s., 260.42 MB/s.)
```

is bounded by single CPU core. Too slow :(

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Queries with `INTO OUTFILE` in `clickhouse-client` will use multiple threads. Fix the issue with flickering progress-bar when using `INTO OUTFILE`. This closes #30873. This closes #30872.

After:
```
milovidov@milovidov-desktop:~/work/ClickHouse/tests/queries/0_stateless$ clickhouse-client 
ClickHouse client version 21.11.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.11.1 revision 54450.

milovidov-desktop :) SELECT * FROM test.hits INTO OUTFILE 'hits.csv' FORMAT CSV

SELECT *
FROM test.hits
INTO OUTFILE 'hits.csv'
FORMAT CSV

Query id: d9b4b2d2-2d29-4ed9-aa87-35994af1ad37


8873898 rows in set. Elapsed: 8.522 sec. Processed 8.87 million rows, 8.46 GB (1.04 million rows/s., 992.84 MB/s.)

milovidov-desktop :) Bye.
```

Before:
```
milovidov@milovidov-desktop:~/work/ClickHouse/tests/queries/0_stateless$ ../../../programs/server/clickhouse-21.10 client
ClickHouse client version 21.10.3.38 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.11.1 revision 54450.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

milovidov-desktop :) SELECT * FROM test.hits INTO OUTFILE 'hits.csv' FORMAT CSV

SELECT *
FROM test.hits
INTO OUTFILE 'hits.csv'
FORMAT CSV

Query id: 24aef9c5-f156-4a26-a221-2d5526bfb842


8873898 rows in set. Elapsed: 33.057 sec. Processed 8.87 million rows, 8.46 GB (268.44 thousand rows/s., 255.94 MB/s.)

milovidov-desktop :) Bye.
```

### CODE REVIEW

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -328,12 +339,16 @@ void ClientBase::initBlockOutputStream(const Block & block, ASTPtr parsed_query)
 
         String current_format = format;
 
+        select_into_file = false;
+
         /// The query can specify output format or output file.
         /// FIXME: try to prettify this cast using `as<>()`
         if (const auto * query_with_output = dynamic_cast<const ASTQueryWithOutput *>(parsed_query.get()))
```
Comment (nikitamikhaylov) [inline src/Client/ClientBase.cpp:346]: Maybe also fix this? :)

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Client/ClientBase.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply src/Client/ClientBase.cpp:346]: Most likely it's not possible, because `as` is `typeid_cast`, not `dynamic_cast`.
Let's remove the comment.
