### PR TITLE
Fix an incorrect filter pushdown to an external database

### LINKED ISSUE #71423: SQLite query with wrong result
**Describe the bug**
A count(*) query on a right join with an SQLite table gives wrong result.

**How to reproduce**
In SQLite run:
```sql
CREATE TABLE t1(c0 INT,c1 INT);
```
Then in Clickhouse:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = Memory();
CREATE TABLE t1 (c0 Int, c1 Int) ENGINE = SQLite('<path to SQLite db>', 't1');
INSERT INTO TABLE t0 (c0) VALUES (1);
INSERT INTO TABLE t1 (c0, c1) VALUES (-3, 0), (1, 0), (-2, 0);
SELECT count() FROM t0 JOIN t0 tx ON tx.c0 = t0.c0 RIGHT JOIN t1 ON t1.c1 = t0.c0 WHERE t0.c0 < 1 OR tx.c0 IS NULL;
-- outputs 2, but should be 3
```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
That's what I see in logs. The query: `SELECT "c0", "c1" FROM "t1" WHERE "c0" < 1` to the SQLite seems incorrect. It, in fact, did a filter push down to a table t1 when the filter should have applied to a table t0.
This happens because `transformQueryForExternalDatabase` function just copies WHERE from the original query.
```
2025.01.31 03:02:48.867647 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Debug> executeQuery: (from [::1]:39400) (comment: 03325_sqlite_join_wrong_answer.sh) (query 1, line 1) SELECT * FROM test_i4qsz34e.t0 tx RIGHT JOIN test_i4qsz34e.t1 ty ON ty.c1 = tx.c0 WHERE tx.c0 < 1; (stage: Complete)
2025.01.31 03:02:48.868068 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> Planner: Query to stage Complete
2025.01.31 03:02:48.868203 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> StorageSQLite (t1): Query: SELECT "c0", "c1" FROM "t1" WHERE "c0" < 1
2025.01.31 03:02:48.868317 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> HashJoin: Keys: [(__table1.c0) = (__table2.c1)], datatype: EMPTY, kind: Right, strictness: All, right header: __table2.c0 Int32 Int32(size = 0), __table2.c1 Int32 Int32(size = 0)
2025.01.31 03:02:48.868352 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> JoiningTransform: Before join block: '__table1.c0 Int32 Int32(size = 0)'
2025.01.31 03:02:48.868386 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> JoiningTransform: After join block: '__table1.c0 Int32 Int32(size = 0), __table2.c0 Int32 Int32(size = 0), __table2.c1 Int32 Int32(size = 0)'
2025.01.31 03:02:48.868408 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> Planner: Query from stage FetchColumns to stage Complete
2025.01.31 03:02:48.868535 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Trace> optimizeJoinLegacy: Left table estimation: 1, right table estimation: unknown
2025.01.31 03:02:48.869208 [ 43666 ] {637628db-86fe-4f14-a04a-a4716189bab2} <Debug> executeQuery: Read 3 rows, 20.00 B in 0.001732 sec., 1732.1016166281754 rows/sec., 11.28 KiB/sec.
```

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed behavior when ClickHouse may erroneously do a filter pushdown to an external database like PostgreSQL, MySQL, or SQLite. This closes: https://github.com/ClickHouse/ClickHouse/issues/71423

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 051e640f78e5e01c61ddbd850d10a2dfa6df488c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75320/051e640f78e5e01c61ddbd850d10a2dfa6df488c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c4755ae6f973f326e2b5e5effcd8982835bea8d1/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs <a href="https://github.com/ClickHouse/ClickBench/">ClickBench</a> with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a0b28d570f346f429e32ba789ab076ebac5fc201/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a0b28d570f346f429e32ba789ab076ebac5fc201/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c4755ae6f973f326e2b5e5effcd8982835bea8d1/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c4755ae6f973f326e2b5e5effcd8982835bea8d1/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/88ddc3c17d397a7ccdb23bf7878bae7b0a5c9935/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a0b28d570f346f429e32ba789ab076ebac5fc201/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a0b28d570f346f429e32ba789ab076ebac5fc201/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Performance Comparison</td><td>Measure changes in query performance. The performance test report is described in detail <a href="https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison#how-to-read-the-report">here</a>. In square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a0b28d570f346f429e32ba789ab076ebac5fc201/performance_comparison__release__[1_4]/report.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/a0b28d570f346f429e32ba789ab076ebac5fc201/unit_tests__asan_.html">✅ success</a></td></tr>
<tr><td>Upgrade check</td><td>Runs stress tests on server version from last release and then tries to upgrade it to the version from the PR. It checks if the new server can successfully startup without any errors, crashes or sanitizer asserts</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/75275/08baba2e0446714fde56a92a9c0ced60f84b390b/upgrade_check__debug_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by PedroTadim** [comment]
I only see a test. Are there no changes in the source code?

File: tests/queries/0_stateless/03325_sqlite_join_wrong_answer.sh [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+chmod ugo+w "${DB_PATH}"
+
+${CLICKHOUSE_CLIENT} --query="CREATE TABLE ${CLICKHOUSE_DATABASE}.t0 (c0 Int) ENGINE = Memory();"
+${CLICKHOUSE_CLIENT} --query="CREATE TABLE ${CLICKHOUSE_DATABASE}.t1 (c0 Int, c1 Int) ENGINE = SQLite('${DB_PATH}', 't1');";
+${CLICKHOUSE_CLIENT} --query="CREATE TABLE ${CLICKHOUSE_DATABASE}.t2 (c0 Int, c1 Int) ENGINE = Memory();";
+${CLICKHOUSE_CLIENT} --query="INSERT INTO TABLE ${CLICKHOUSE_DATABASE}.t0 (c0) VALUES (1);"
+${CLICKHOUSE_CLIENT} --query="INSERT INTO TABLE ${CLICKHOUSE_DATABASE}.t1 (c0, c1) VALUES (-3, 0), (1, 0), (-2, 0);";
+${CLICKHOUSE_CLIENT} --query="INSERT INTO TABLE ${CLICKHOUSE_DATABASE}.t2 (c0, c1) VALUES (-3, 0), (1, 0), (-2, 0);";
+
+${CLICKHOUSE_CLIENT} --query="SELECT count() FROM ${CLICKHOUSE_DATABASE}.t0 tx RIGHT JOIN ${CLICKHOUSE_DATABASE}.t1 ty ON ty.c1 = tx.c0 WHERE tx.c0 < 1;"
```
Comment (vdimir) [inline tests/queries/0_stateless/03325_sqlite_join_wrong_answer.sh:21]: Let's also add a testcase with several JOINs and external database on different positions in join tree

File: src/Analyzer/Utils.h [hunk 2]
```diff
@@ -160,4 +160,14 @@ QueryTreeNodePtr buildSubqueryToReadColumnsFromTableExpression(const NamesAndTyp
...
 
 
+bool hasUnknownColumn(
+    const QueryTreeNodePtr & node,
+    QueryTreeNodePtr replacement_table_expression);
+
+void replaceFilterExpression(
+    QueryTreeNodePtr & expression,
+    const QueryTreeNodePtr & replacement_table_expression,
+    const ContextPtr & context);
```
Comment (vdimir) [inline src/Analyzer/Utils.h:170]: Nitpick: better naming

```suggestion
/// Removes filter expressions that reference columns from table expressions other than `allowed_table_expression`
void removeUnknownFilterExpressions(
    QueryTreeNodePtr & expression,
    const QueryTreeNodePtr & allowed_table_expression,
    const ContextPtr & context);
```

**Review by vdimir — APPROVED** [review]

File: src/Analyzer/Utils.cpp [hunk 3]
```diff
@@ -975,4 +975,103 @@ QueryTreeNodePtr buildSubqueryToReadColumnsFromTableExpression(const QueryTreeNo
...
+
+        switch (current->getNodeType())
+        {
+            case QueryTreeNodeType::CONSTANT:
+                break;
+            case QueryTreeNodeType::COLUMN:
+            {
+                auto * column_node = current->as<ColumnNode>();
+                auto source = column_node->getColumnSourceOrNull();
+                if (source && table_expression && !source->isEqual(*table_expression))
```
Comment (novikd) [inline src/Analyzer/Utils.cpp:994]: This is a bug and it leads to a `LOGICAL_ERROR`: https://github.com/ClickHouse/ClickHouse/issues/82092

1. `table_expression` should never be `nullptr`.
2. If `source` is `nullptr`, the function must return `true`, because the source table expression was replaced.

Comment (nikitamikhaylov) [reply src/Analyzer/Utils.cpp:994]: Thank you!
