### PR TITLE
convert timestamp and  timestamptz data types to DateTime64 in postgres engine

### LINKED ISSUE #26216: timestamp format should convert to DateTime64 not DateTime  in postgres engine
**Describe the unexpected behaviour**
currently data format name started with `timestamp`(timestamp/timestamptz) all converted to DateTime in postgres engine, this will losing precision of millisecond and microsecond, so they should be regarded as DtateTime64 data format

**Expected behavior**

they should be regarded as DtateTime64 data format

### PR DESCRIPTION
**Pull request by jasine**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

convert timestamp and  timestamptz data types to DateTime64 in postgres engine

Detailed description / Documentation draft:

currently data format name started with timestamp(timestamp/timestamptz) all converted to DateTime in postgres engine, this will losing precision of millisecond and microsecond, so they should be regarded as DtateTime64 data format and it is backward compatible

Closes #26216.

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

File: src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp [hunk 1]
```diff
@@ -327,6 +327,16 @@ ASTPtr StorageMaterializedPostgreSQL::getColumnDeclaration(const DataTypePtr & d
             return make_decimal_expression("Decimal256");
     }
 
+    if (which.isDateTime64())
+    {
+        auto ast_expression = std::make_shared<ASTFunction>();
```
Comment (kssenii) [inline src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp:332]: Thanks for adding that for Materialized storage :+1:

File: src/Core/PostgreSQL/insertPostgreSQLValue.cpp [hunk 2]
```diff
@@ -102,7 +103,16 @@ void insertPostgreSQLValue(
             assert_cast<ColumnUInt32 &>(column).insertValue(time);
             break;
         }
-        case ExternalResultDescription::ValueType::vtDateTime64:[[fallthrough]];
+        case ExternalResultDescription::ValueType::vtDateTime64:
+        {
+            ReadBufferFromString in(value);
+            DateTime64 time = 0;
+            readDateTime64Text(time, 6, in, assert_cast<const DataTypeDateTime64 *>(data_type.get())->getTimeZone());
+            if (time < 0)
```
Comment (kitaisreal) [inline src/Core/PostgreSQL/insertPostgreSQLValue.cpp:111]: Why is this necessary ?

**Review by kitaisreal — APPROVED** [review]

**Review by kssenii — APPROVED** [review]
