### PR TITLE
Fix a bug with s3_plain_rewritable storage when used with projections

### LINKED ISSUE #70258: Projection x plain_rewritable not working together
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

Agnostic

**Describe what's wrong**

Error when querying a table with projections and plain_rewritable disk.
The issue happens with clickhouse local version 24.10.1.329.

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

The following error happens with clickhouse local version 24.10.1.329.
Here is how to reproduce it:

```sql
create table test_proj_001 (
    timestamp DateTime64(3, 'UTC'),
    number UInt64,
    blob String,

    INDEX timestamp timestamp TYPE minmax GRANULARITY 1,

    PROJECTION min_max_number (
        SELECT
            min(number), 
            max(number)
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(timestamp)
ORDER BY (timestamp)
SETTINGS disk = disk(
    type=s3,
    endpoint='**********************',
    use_environment_credentials=1,
    metadata_type=plain_rewritable
);

insert into test_proj_001 values (now(), 1, 'abc'), (now()-interval 1 day, 2, 'def')
```

Then some query work ok:

```
:) select count(*) from test_proj_001

SELECT count(*)
FROM test_proj_001

Query id: c719a2ba-fd78-4ebb-aa35-f28a1092aa0a

   ┌─count()─┐
1. │       2 │
   └─────────┘

1 row in set. Elapsed: 0.003 sec.
```

Or:

```
:) select * from test_proj_001

SELECT *
FROM test_proj_001

Query id: 71acc183-1ed3-4555-895e-e2750f8ddc1c

   ┌───────────────timestamp─┬─number─┬─blob─┐
1. │ 2024-10-01 08:48:41.000 │      2 │ def  │
2. │ 2024-10-02 08:48:41.000 │      1 │ abc  │
   └─────────────────────────┴────────┴──────┘

2 rows in set. Elapsed: 0.084 sec
```

But query that could make use of the projection fail:

```
:) select max(number) from test_proj_001

SELECT max(number)
FROM test_proj_001

Query id: 8ce40cea-8763-4f42-9858-634cf3890a50


Elapsed: 0.085 sec.

Received exception:
Code: 246. DB::Exception: Empty marks file 'test_proj_001/data/default/test_proj_001/202410_1_1_0/min_max_number.proj/data.cmrk3': 0, must be: 80: (while reading from part test_proj_001/data/default/test_proj_001/202410_1_1_0/min_max_number.proj/ in table default.test_proj_001 located on disk __tmp_internal_132222126954221991566785453547750829663 of type s3, from mark 0 with max_rows_to_read = 1): While executing MergeTreeSelect(pool: PrefetchedReadPool, algorithm: Thread). (CORRUPTED_DATA)
```

**Expected behavior**

I expect the query to run without error, and to make use of the projection.
BTW, I listed all files on the object store and see nothing that looks like a projection part.

**Error message and/or stacktrace**

```
Code: 246. DB::Exception: Empty marks file 'test_proj_001/data/default/test_proj_001/202410_1_1_0/min_max_number.proj/data.cmrk3': 0, must be: 80: (while reading from part test_proj_001/data/default/test_proj_001/202410_1_1_0/min_max_number.proj/ in table default.test_proj_001 located on disk __tmp_internal_132222126954221991566785453547750829663 of type s3, from mark 0 with max_rows_to_read = 1): While executing MergeTreeSelect(pool: PrefetchedReadPool, algorithm: Thread). (CORRUPTED_DATA)
```

**Additional context**

> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by sberss**
This PR fixes a bug with `s3_plain_rewritable` storage, where metadata objects in S3 referencing projections are not updated when the parent directory is moved (i.e. from `.../tmp_insert_all_.../` to `.../all_.../`). The projection parts are effectively lost and this makes any queries that hit the projection completely broken.

**Steps to reproduce**

Add the following storage configuration:
```
<storage_configuration>
    <disks>
        <s3_plain_rewritable>
            <type>s3_plain_rewritable</type>
            <endpoint>...</endpoint>
            <use_environment_credentials>1</use_environment_credentials>
        </s3_plain_rewritable>
    </disks>
    <policies>
        <s3_plain_rewritable>
            <volumes>
                <main>
                    <disk>s3_plain_rewritable</disk>
                </main>
            </volumes>
        </s3_plain_rewritable>
    </policies>
</storage_configuration>
```

Then the following series of SQL commands will land you in a broken state.
```
foo :) CREATE TABLE foo (x UInt32, y UInt32, PROJECTION prj_y (SELECT x, y ORDER BY y)) ENGINE MergeTree() PRIMARY KEY x SETTINGS storage_policy='s3_plain_rewritable';

CREATE TABLE foo
(
    `x` UInt32,
    `y` UInt32,
    PROJECTION prj_y
    (
        SELECT
            x,
            y
        ORDER BY y
    )
)
ENGINE = MergeTree
PRIMARY KEY x
SETTINGS storage_policy = 's3_plain_rewritable'

Query id: 1a2028e8-1823-4a6c-8c93-885c07803f62

Ok.

0 rows in set. Elapsed: 0.162 sec.

foo :) INSERT INTO foo SELECT rand(), rand() FROM system.numbers LIMIT 10000000;

INSERT INTO foo SELECT
    rand(),
    rand()
FROM system.numbers
LIMIT 10000000

Query id: 60586879-afeb-464c-9988-5333c417be33

Ok.

0 rows in set. Elapsed: 4.824 sec. Processed 10.00 million rows, 80.00 MB (2.07 million rows/s., 16.58 MB/s.)
Peak memory usage: 85.05 MiB.

foo :) SELECT *
FROM foo
LIMIT 1
;

SELECT *
FROM foo
LIMIT 1

Query id: b717261c-4a39-458b-97f7-dd3d48cb4073

   ┌────x─┬────y─┐
1. │ 5979 │ 5979 │
   └──────┴──────┘

1 row in set. Elapsed: 0.081 sec. Processed 8.19 thousand rows, 65.54 KB (100.96 thousand rows/s., 807.67 KB/s.)
Peak memory usage: 179.24 KiB.

foo :) select * from foo where y=5979;

SELECT *
FROM foo
WHERE y = 5979

Query id: 93cc3be7-c8b7-4037-a709-23ff628cd5d5


Elapsed: 0.131 sec.

Received exception from server (version 25.6.1):
Code: 107. DB::Exception: Received from localhost:9000. DB::Exception: File store/995/99595d79-576d-42ca-8e82-7111734121bb/all_1_1_0/prj_y.proj/data.cmrk4 does not exist on PlainRewritableS3ObjectStorage: (while reading from part sbe/store/995/99595d79-576d-42ca-8e82-7111734121bb/all_1_1_0/prj_y.proj/ in table default.foo (99595d79-576d-42ca-8e82-7111734121bb) located on disk s3_plain_rewritable of type s3, from mark 0 with max_rows_to_read = 8192, offset = 0): While executing MergeTreeSelect(pool: PrefetchedReadPool, algorithm: Thread). (FILE_DOESNT_EXIST)
```

Looking at the metadata in S3, we can see that there is a mismatch between the path written to the metadata, and the path ClickHouse is looking for. This is because `store/995/99595d79-576d-42ca-8e82-7111734121bb/tmp_insert_all_1_1_0/` was correctly updated to `store/995/99595d79-576d-42ca-8e82-7111734121bb/all_1_1_0/`, but the projection was missed.

```
...
ksfdmlrbrottlzmdbuubakexfbxjhjbp/prefix.path: store/995/99595d79-576d-42ca-8e82-7111734121bb/all_1_1_0/
...
vattbntzyvdikgorkatcfkkmvgxnxuqi/prefix.path: store/995/99595d79-576d-42ca-8e82-7111734121bb/tmp_insert_all_1_1_0/prj_y.proj/
...
```

The fix in this PR iterates and moves all subdirectories when moving a directory in `MetadataStorageFromPlainObjectStorageMoveDirectoryOperation`, to ensure projections are not missed.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implement support for `s3_plain_rewritable` storage with projections. In previous versions, metadata objects in S3 referencing projections would not get updated when moved. Closes #70258

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
This is not a critical bugfix.

**Comment by sberss** [comment]
> This is not a critical bugfix.

OK - have updated.

**Comment by sberss** [comment]
I don't think these CI errors are actually related to this change - looks like a lot of failures trying to allocate a port. Is there a way to rerun?

**Comment by jkartseva** [comment]
Please convert the repro scenario into a test case.

File: src/Disks/ObjectStorages/MetadataStorageFromPlainObjectStorageOperations.cpp [hunk 1]
```diff
@@ -183,18 +183,24 @@ void MetadataStorageFromPlainObjectStorageMoveDirectoryOperation::execute(std::u
...
+        fiu_do_on(FailPoints::plain_object_storage_write_fail_on_directory_move,
+        {
+            throw Exception(ErrorCodes::FAULT_INJECTED, "Injecting fault when moving from '{}' to '{}'", path_from, path_to);
+        });
+
+        write_buf->finalize();
+
+        /// parent_path() removes the trailing '/'.
+        path_map.moveDirectory((path_from / subdir).parent_path(), (path_to / subdir).parent_path());
+    }
```
Comment (jkartseva) [inline src/Disks/ObjectStorages/MetadataStorageFromPlainObjectStorageOperations.cpp]: `MetadataStorageFromPlainObjectStorageMoveDirectoryOperation::undo` should also be changed to revert to the previous state if rollback is triggered, but this is not very important; I can follow up separately.

Comment (jkartseva) [reply src/Disks/ObjectStorages/MetadataStorageFromPlainObjectStorageOperations.cpp]: A `LOG_TEST` message that a subdirectory was moved might be useful.

**Review by jkartseva — APPROVED** [review]
Looks good.

I tested the fix by adding a projection in the integration [test](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_s3_plain_rewritable/test.py#L60-L66) and ensuring that the state is valid after server restart: that projection is listed in `system.projections`, and that the tests pass.
  
A note to self:`ALTER TABLE ... PROJECTON` operation return `SUPPORT_IS_DISABLED`, I believe this restriction may be removed (not in this PR).

File: src/Disks/ObjectStorages/MetadataStorageFromPlainObjectStorageOperations.cpp (hunk 1 above)
Comment (sberss) [reply src/Disks/ObjectStorages/MetadataStorageFromPlainObjectStorageOperations.cpp]: I've added a `LOG_TEST` to log when a directory is moved. I also tidied up the function a bit to stop repeating `(path_from / subdir)` and `(path_to / subdir)` everywhere.
