### PR TITLE
Fix arraySlice with null args.

### LINKED ISSUE #29890: Logical error: Invalid number of rows in Chunk column Array(Array(Nothing))
https://clickhouse-test-reports.s3.yandex.net/29804/90cc63aecd37ffe7a3f6497b462be55540bc70a5/fuzzer_debug/report.html#fail1

```
2021.10.08 00:59:13.283176 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> executeQuery: (from [::1]:59180) SELECT max((SELECT sumState(number) FROM numbers(65535)) * NULL, arraySlice([arraySlice([], -2)], materialize((SELECT sumState(number) FROM numbers(10)) * NULL), NULL), blockSize()), min(finalizeAggregation(materialize((SELECT sumState(number) FROM numbers(1))) * NULL), blockSize()), any(ignore(*)) FROM tab_00484
2021.10.08 00:59:13.285929 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.10.08 00:59:13.288301 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.10.08 00:59:13.291858 [ 351 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> AggregatingTransform: Aggregating
2021.10.08 00:59:13.291983 [ 351 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Aggregation method: without_key
2021.10.08 00:59:13.293000 [ 351 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> AggregatingTransform: Aggregated. 65535 to 1 rows (from 511.99 KiB) in 0.003243095 sec. (20207548.653 rows/sec., 154.17 MiB/sec.)
2021.10.08 00:59:13.293110 [ 351 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Merging aggregated data
2021.10.08 00:59:13.293968 [ 351 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> PipelineExecutor: Thread finished. Total time: 0.002733168 sec. Execution time: 0.002129194 sec. Processing time: 0.00058313 sec. Wait time: 2.0844e-05 sec.
2021.10.08 00:59:13.295614 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.10.08 00:59:13.297993 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.10.08 00:59:13.300893 [ 350 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> AggregatingTransform: Aggregating
2021.10.08 00:59:13.300971 [ 350 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Aggregation method: without_key
2021.10.08 00:59:13.301163 [ 350 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> AggregatingTransform: Aggregated. 10 to 1 rows (from 80.00 B) in 0.001730908 sec. (5777.315 rows/sec., 45.14 KiB/sec.)
2021.10.08 00:59:13.301243 [ 350 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Merging aggregated data
2021.10.08 00:59:13.302027 [ 350 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> PipelineExecutor: Thread finished. Total time: 0.00126323 sec. Execution time: 0.00079094 sec. Processing time: 0.000456435 sec. Wait time: 1.5855e-05 sec.
2021.10.08 00:59:13.303592 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.10.08 00:59:13.305982 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.10.08 00:59:13.309076 [ 333 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> AggregatingTransform: Aggregating
2021.10.08 00:59:13.309176 [ 333 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Aggregation method: without_key
2021.10.08 00:59:13.309376 [ 333 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> AggregatingTransform: Aggregated. 1 to 1 rows (from 8.00 B) in 0.001849616 sec. (540.653 rows/sec., 4.22 KiB/sec.)
2021.10.08 00:59:13.309456 [ 333 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Merging aggregated data
2021.10.08 00:59:13.310257 [ 333 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> PipelineExecutor: Thread finished. Total time: 0.001323103 sec. Execution time: 0.00082264 sec. Processing time: 0.000484761 sec. Wait time: 1.5702e-05 sec.
2021.10.08 00:59:13.322069 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> ContextAccess (default): Access granted: SELECT(date, x, s) ON default.tab_00484
2021.10.08 00:59:13.322739 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.10.08 00:59:13.329917 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> default.tab_00484 (79afac16-d944-43de-b9af-ac16d944a3de) (SelectExecutor): Key condition: unknown
2021.10.08 00:59:13.338422 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> default.tab_00484 (79afac16-d944-43de-b9af-ac16d944a3de) (SelectExecutor): MinMax index condition: unknown
2021.10.08 00:59:13.338890 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> default.tab_00484 (79afac16-d944-43de-b9af-ac16d944a3de) (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 1/1 marks by primary key, 1 marks to read from 1 ranges
2021.10.08 00:59:13.339326 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Debug> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20211008_1_1_0, approx. 8192 rows starting from 0
2021.10.08 00:59:13.341567 [ 136 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Trace> Aggregator: Compile expression any()(UInt8) 0 
2021.10.08 00:59:13.447830 [ 135 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #1
2021.10.08 00:59:13.654722 [ 183 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 3471
2021.10.08 00:59:13.746169 [ 182 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:13.753232 [ 182 ] {} <Trace> system.text_log (9cd0c0bd-4d25-4f18-9cd0-c0bd4d25bf18): Renaming temporary part tmp_insert_202110_461_461_0 to 202110_461_461_0.
2021.10.08 00:59:13.768806 [ 352 ] {f483911f-89e8-47b6-b594-3da29e8b832b} <Fatal> : Logical error: 'Invalid number of rows in Chunk column Array(Array(Nothing)) position 1: expected 8192, got 1'.
2021.10.08 00:59:13.769800 [ 40 ] {} <Trace> BaseDaemon: Received signal 6
2021.10.08 00:59:13.770734 [ 356 ] {} <Fatal> BaseDaemon: ########################################
2021.10.08 00:59:13.771067 [ 356 ] {} <Fatal> BaseDaemon: (version 21.11.1.8340, build id: FABB7A7D67748FCF81AAD13FD7F3B2E48F1571BC) (from thread 352) (query_id: f483911f-89e8-47b6-b594-3da29e8b832b) Received signal Aborted (6)
2021.10.08 00:59:13.771310 [ 356 ] {} <Fatal> BaseDaemon: 
2021.10.08 00:59:13.771560 [ 356 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f851dc3918b 0x7f851dc18859 0x14e372b8 0x14e373c2 0x22956852 0x22956ea5 0x22d00e20 0x1e52ac02 0x2295fa5b 0x229d6019 0x229d5f7f 0x229d5f1d 0x229d5edd 0x229d5eb5 0x229d5e7d 0x14e83866 0x14e82955 0x229d4925 0x229d52a5 0x229d320b 0x229d24d3 0x229f2ee1 0x229f2e00 0x229f2d7d 0x229f2d21 0x229f2c32 0x229f2b1b 0x229f29dd 0x229f299d 0x229f2975 0x229f2940 0x14e83866 0x14e82955 0x14ead90f 0x14eb4ac4 0x14eb4a3d 0x14eb4965 0x14eb42a2 0x7f851ddff609 0x7f851dd15293
2021.10.08 00:59:13.771935 [ 356 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.08 00:59:13.772095 [ 356 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.08 00:59:13.868759 [ 356 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:53: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0x14e372b8 in /workspace/clickhouse
2021.10.08 00:59:13.947698 [ 183 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:13.954389 [ 356 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:60: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x14e373c2 in /workspace/clickhouse
2021.10.08 00:59:14.024403 [ 183 ] {} <Trace> system.metric_log (30092398-77c5-4ef1-b009-239877c53ef1): Renaming temporary part tmp_insert_202110_439_439_0 to 202110_439_439_0.
2021.10.08 00:59:14.060775 [ 183 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 3471
2021.10.08 00:59:14.076021 [ 356 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Processors/Chunk.cpp:72: DB::Chunk::checkNumRowsIsConsistent() @ 0x22956852 in /workspace/clickhouse
2021.10.08 00:59:14.192992 [ 356 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Processors/Chunk.cpp:57: DB::Chunk::setColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long) @ 0x22956ea5 in /workspace/clickhouse
2021.10.08 00:59:14.309203 [ 356 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:25: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x22d00e20 in /workspace/clickhouse
2021.10.08 00:59:14.475803 [ 356 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:38: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x1e52ac02 in /workspace/clickhouse
2021.10.08 00:59:14.607274 [ 356 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x2295fa5b in /workspace/clickhouse
2021.10.08 00:59:14.697087 [ 179 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 17 entries to flush up to offset 25221
2021.10.08 00:59:14.731117 [ 179 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:14.741709 [ 179 ] {} <Trace> system.query_thread_log (f35797ef-3835-4ad0-b357-97ef3835ead0): Renaming temporary part tmp_insert_202110_390_390_0 to 202110_390_390_0.
2021.10.08 00:59:14.742313 [ 204 ] {} <Debug> system.query_thread_log (f35797ef-3835-4ad0-b357-97ef3835ead0) (MergerMutator): Selected 6 parts from 202110_345_385_8 to 202110_390_390_0
2021.10.08 00:59:14.742576 [ 204 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:14.743140 [ 101 ] {} <Debug> MergeTask::PrepareStage: Merging 6 parts: from 202110_345_385_8 to 202110_390_390_0 into Compact
2021.10.08 00:59:14.744477 [ 101 ] {} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2021.10.08 00:59:14.745363 [ 179 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log up to offset 25221
2021.10.08 00:59:14.745638 [ 101 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_345_385_8, total 1493 rows starting from the beginning of the part
2021.10.08 00:59:14.749752 [ 101 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_386_386_0, total 41 rows starting from the beginning of the part
2021.10.08 00:59:14.753840 [ 101 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_387_387_0, total 42 rows starting from the beginning of the part
2021.10.08 00:59:14.757926 [ 101 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_388_388_0, total 12 rows starting from the beginning of the part
2021.10.08 00:59:14.761924 [ 101 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_389_389_0, total 14 rows starting from the beginning of the part
2021.10.08 00:59:14.783837 [ 101 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_390_390_0, total 17 rows starting from the beginning of the part
2021.10.08 00:59:14.851460 [ 101 ] {} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 1619 rows, containing 44 columns (44 merged, 0 gathered) in 0.108573939 sec., 14911.497316128505 rows/sec., 15.57 MiB/sec.
2021.10.08 00:59:14.864160 [ 356 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:88: DB::executeJob(DB::IProcessor*) @ 0x229d6019 in /workspace/clickhouse
2021.10.08 00:59:14.870426 [ 101 ] {} <Trace> system.query_thread_log (f35797ef-3835-4ad0-b357-97ef3835ead0): Renaming temporary part tmp_merge_202110_345_390_9 to 202110_345_390_9.
2021.10.08 00:59:14.871135 [ 101 ] {} <Trace> system.query_thread_log (f35797ef-3835-4ad0-b357-97ef3835ead0) (MergerMutator): Merged 6 parts: from 202110_345_385_8 to 202110_390_390_0
2021.10.08 00:59:14.873230 [ 101 ] {} <Debug> MemoryTracker: Peak memory usage Mutate/Merge: 4.03 MiB.
2021.10.08 00:59:15.000263 [ 319 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 813.55 MiB, peak 3.09 GiB, will set to 862.45 MiB (RSS), difference: 48.90 MiB
2021.10.08 00:59:15.097659 [ 356 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:105: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const @ 0x229d5f7f in /workspace/clickhouse
2021.10.08 00:59:15.343681 [ 356 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x229d5f1d in /workspace/clickhouse
2021.10.08 00:59:15.576566 [ 356 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x229d5edd in /workspace/clickhouse
2021.10.08 00:59:15.812081 [ 356 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()>::operator()() @ 0x229d5eb5 in /workspace/clickhouse
2021.10.08 00:59:16.047573 [ 356 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x229d5e7d in /workspace/clickhouse
2021.10.08 00:59:16.095417 [ 356 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x14e83866 in /workspace/clickhouse
2021.10.08 00:59:16.140002 [ 356 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const @ 0x14e82955 in /workspace/clickhouse
2021.10.08 00:59:16.357288 [ 356 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:602: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x229d4925 in /workspace/clickhouse
2021.10.08 00:59:16.575915 [ 356 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:487: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0x229d52a5 in /workspace/clickhouse
2021.10.08 00:59:16.770047 [ 356 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:826: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x229d320b in /workspace/clickhouse
2021.10.08 00:59:16.986333 [ 356 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:407: DB::PipelineExecutor::execute(unsigned long) @ 0x229d24d3 in /workspace/clickhouse
2021.10.08 00:59:17.000304 [ 319 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 862.45 MiB, peak 3.09 GiB, will set to 863.98 MiB (RSS), difference: 1.53 MiB
2021.10.08 00:59:17.144548 [ 356 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:85: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0x229f2ee1 in /workspace/clickhouse
2021.10.08 00:59:17.302879 [ 356 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:113: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const @ 0x229f2e00 in /workspace/clickhouse
2021.10.08 00:59:17.338431 [ 181 ] {} <Trace> SystemLog (system.trace_log): Flushing system log, 21 entries to flush up to offset 23038
2021.10.08 00:59:17.351251 [ 181 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:17.355336 [ 181 ] {} <Trace> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be): Renaming temporary part tmp_insert_202110_463_463_0 to 202110_463_463_0.
2021.10.08 00:59:17.355823 [ 227 ] {} <Debug> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be) (MergerMutator): Selected 2 parts from 202110_1_458_254 to 202110_459_459_0
2021.10.08 00:59:17.355999 [ 227 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:17.356354 [ 107 ] {} <Debug> MergeTask::PrepareStage: Merging 2 parts: from 202110_1_458_254 to 202110_459_459_0 into Compact
2021.10.08 00:59:17.356678 [ 181 ] {} <Trace> SystemLog (system.trace_log): Flushed system log up to offset 23038
2021.10.08 00:59:17.356944 [ 107 ] {} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2021.10.08 00:59:17.357425 [ 107 ] {} <Debug> MergeTreeSequentialSource: Reading 4 marks from part 202110_1_458_254, total 22900 rows starting from the beginning of the part
2021.10.08 00:59:17.359088 [ 107 ] {} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202110_459_459_0, total 29 rows starting from the beginning of the part
2021.10.08 00:59:17.452267 [ 100 ] {} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 22929 rows, containing 10 columns (10 merged, 0 gathered) in 0.096017688 sec., 238799.75114585136 rows/sec., 85.77 MiB/sec.
2021.10.08 00:59:17.461700 [ 356 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x229f2d7d in /workspace/clickhouse
2021.10.08 00:59:17.475395 [ 100 ] {} <Trace> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be): Renaming temporary part tmp_merge_202110_1_459_255 to 202110_1_459_255.
2021.10.08 00:59:17.475826 [ 100 ] {} <Trace> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be) (MergerMutator): Merged 2 parts: from 202110_1_458_254 to 202110_459_459_0
2021.10.08 00:59:17.476974 [ 100 ] {} <Debug> MemoryTracker: Peak memory usage Mutate/Merge: 17.70 MiB.
2021.10.08 00:59:17.580039 [ 131 ] {} <Trace> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be): Found 2 old parts to remove.
2021.10.08 00:59:17.580185 [ 131 ] {} <Debug> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be): Removing part from filesystem 202110_1_394_190
2021.10.08 00:59:17.581130 [ 131 ] {} <Debug> system.trace_log (8ffce5a6-2b20-41be-8ffc-e5a62b2071be): Removing part from filesystem 202110_395_395_0
2021.10.08 00:59:17.606997 [ 184 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 7469 entries to flush up to offset 3706888
2021.10.08 00:59:17.619507 [ 356 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415: decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) @ 0x229f2d21 in /workspace/clickhouse
2021.10.08 00:59:17.634497 [ 184 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 755.10 GiB.
2021.10.08 00:59:17.641237 [ 184 ] {} <Trace> system.asynchronous_metric_log (f5f68d9e-ac13-4fca-b5f6-8d9eac135fca): Renaming temporary part tmp_insert_202110_494_494_0 to 202110_494_494_0.
2021.10.08 00:59:17.642502 [ 184 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 3706888
2021.10.08 00:59:17.776392 [ 356 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424: decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) @ 0x229f2c32 in /workspace/clickhouse
2021.10.08 00:59:17.916626 [ 356 ] {} <Fatal> BaseDaemon: 30. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() @ 0x229f2b1b in /workspace/clickhouse
2021.10.08 00:59:18.075566 [ 356 ] {} <Fatal> BaseDaemon: 31. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) @ 0x229f29dd in /workspace/clickhouse
2021.10.08 00:59:18.230352 [ 356 ] {} <Fatal> BaseDaemon: 32. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&...) @ 0x229f299d in /workspace/clickhouse
2021.10.08 00:59:18.385081 [ 356 ] {} <Fatal> BaseDaemon: 33. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()() @ 0x229f2975 in /workspace/clickhouse
2021.10.08 00:59:18.539383 [ 356 ] {} <Fatal> BaseDaemon: 34. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x229f2940 in /workspace/clickhouse
2021.10.08 00:59:18.585901 [ 356 ] {} <Fatal> BaseDaemon: 35. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x14e83866 in /workspace/clickhouse
2021.10.08 00:59:18.629291 [ 356 ] {} <Fatal> BaseDaemon: 36. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const @ 0x14e82955 in /workspace/clickhouse
2021.10.08 00:59:18.702258 [ 356 ] {} <Fatal> BaseDaemon: 37. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:274: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x14ead90f in /workspace/clickhouse
2021.10.08 00:59:18.792283 [ 356 ] {} <Fatal> BaseDaemon: 38. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:139: void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const @ 0x14eb4ac4 in /workspace/clickhouse
2021.10.08 00:59:18.887547 [ 356 ] {} <Fatal> BaseDaemon: 39. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<void>(fp)(std::__1::forward<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(fp0)...)) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...) @ 0x14eb4a3d in /workspace/clickhouse
2021.10.08 00:59:18.982547 [ 356 ] {} <Fatal> BaseDaemon: 40. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:281: void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) @ 0x14eb4965 in /workspace/clickhouse
2021.10.08 00:59:19.080242 [ 356 ] {} <Fatal> BaseDaemon: 41. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x14eb42a2 in /workspace/clickhouse
2021.10.08 00:59:19.080681 [ 356 ] {} <Fatal> BaseDaemon: 42. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.10.08 00:59:19.081112 [ 356 ] {} <Fatal> BaseDaemon: 43. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

Can re related to #28966, but it looks different.

cc: @KochetovNicolai

### PR DESCRIPTION
**Pull request by KochetovNicolai**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #29890

### CODE REVIEW

File: src/Functions/array/arraySlice.cpp [hunk 1]
```diff
@@ -102,7 +102,7 @@ class FunctionArraySlice : public IFunction
         {
             if (!length_column || length_column->onlyNull())
             {
-                return array_column;
+                return arguments[0].column;
```
Comment (alexey-milovidov) [inline src/Functions/array/arraySlice.cpp:105]: Ok. This avoids extracting the contents of the const column.

**Review by alexey-milovidov — APPROVED** [review]
