### PR TITLE
Fix skip indexes with expression with literals in analyzer

### LINKED ISSUE #73784: Some SKIP indexes types don't work when expression contains functions with literals
Examples:
```sql
CREATE TABLE test
(
    `x` Int64,
    INDEX idx1 CAST(x, 'String') TYPE bloom_filter GRANULARITY 1,
    INDEX idx2 CAST(x, 'String') TYPE minmax GRANULARITY 1,
    INDEX idx3 CAST(x, 'String') TYPE set(0) GRANULARITY 1,
    INDEX idx4 CAST(x, 'String') TYPE ngrambf_v1(4, 16000, 2, 0) GRANULARITY 1,
    INDEX idx5 CAST(x, 'String') TYPE tokenbf_v1(16000, 2, 0) GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY tuple();
INSERT INTO test SELECT number FROM numbers(1000000);
EXPLAIN indexes = 1 SELECT * FROM test WHERE CAST(x, 'String') = '100'
```

```
   ┌─explain────────────────────────────────────────────────────────┐
1. │ Expression ((Project names + Projection))                      │
2. │   Filter ((WHERE + Change column names to column identifiers)) │
3. │     ReadFromMergeTree (default.test)                           │
4. │     Indexes:                                                   │
5. │       Skip                                                     │
6. │         Name: idx2                                             │
7. │         Description: minmax GRANULARITY 1                      │
8. │         Parts: 1/1                                             │
9. │         Granules: 1/123                                        │
   └────────────────────────────────────────────────────────────────┘
```

As we can see, only `minmax` actually works in this case.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix not working skip indexes with expression with literals in analyzer and remove trivial casts during indexes analysis.

Closes https://github.com/ClickHouse/ClickHouse/issues/73784

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by novikd — APPROVED** [review]
LGTM

File: src/Storages/MergeTree/MergeTreeIndexUtils.cpp [hunk 1]
```diff
@@ -44,4 +47,104 @@ ASTPtr buildFilterNode(const ASTPtr & select_query, ASTs additional_filters)
...
+            break;
+        }
+        case (ActionsDAG::ActionType::COLUMN):
+        {
+            String name;
+            if (const auto * column_const = typeid_cast<const ColumnConst *>(node.column.get());
+                column_const && column_const->getDataType() != TypeIndex::Function)
+            {
+                /// Re-generate column name for constant.
+                name = ASTLiteral(column_const->getField()).getColumnName();
```
Comment (novikd) [inline src/Storages/MergeTree/MergeTreeIndexUtils.cpp:94]: Is it hard to compare actual constants in the index analysis instead of generating a new name for it? It may be slow for big constants.

Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergeTreeIndexUtils.cpp:94]: Apparently in PK analysis (and in secondary index analysis as well, I guess) we compare expressions by name. So that there are lookups like `plus(x, 42)` where the full expression name is important.

Ideally, we should be able to do deep comparison (as we do for projection analysis), or at least calculate a hash from the subtree. But  it would require to re-implement a lot of code.
