### PR TITLE
Fix sending replicated columns as external data in remote query

### LINKED ISSUE #90361: Logical error: 'Bad cast from type DB::ColumnReplicated to DB::ColumnNullable'
### Describe the bug

From here: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=d17efdc97247b10ac5de81da7934d8cbd5f3b901&name_0=MasterCI&name_1=AST+fuzzer+%28amd_ubsan%29

### How to reproduce

With `test_cluster_one_shard_three_replicas_localhost` setup from testing, run:
```sql
SET enable_parallel_replicas = 1, cluster_for_parallel_replicas = 'test_cluster_one_shard_three_replicas_localhost';
CREATE TABLE t0 (c0 String, c1 Nullable(String)) ENGINE = MergeTree ORDER BY tuple();
CREATE TABLE t1 (c0 String, c1 Nullable(String)) ENGINE = ReplicatedMergeTree('/clickhouse/{database}/t1', '1') ORDER BY tuple();
INSERT INTO t0 (c0, c1) VALUES ('a', 'a');
INSERT INTO t1 (c0, c1) VALUES ('a', 'a');
SELECT 1 FROM t1 GLOBAL JOIN (SELECT c1 FROM t0 ARRAY JOIN [1]) s ON t1.c0 = s.c1;
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Bad cast from type DB::ColumnReplicated to DB::ColumnNullable'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000024e10d72
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015071ee9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d62820e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d627d51
4. src/Common/Exception.h:141: DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000d6260f6
5. src/Common/assert_cast.h:48: DB::ColumnNullable const& assert_cast<DB::ColumnNullable const&, DB::IColumn const&>(DB::IColumn const&) @ 0x000000000ea8d80e
6. src/DataTypes/Serializations/SerializationNullable.cpp:32: DB::SerializationNullable::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x000000001a092152
7. src/DataTypes/Serializations/ISerialization.cpp:185: DB::ISerialization::enumerateStreams(std::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::shared_ptr<DB::IDataType const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) const @ 0x000000001a011bff
8. src/Interpreters/inplaceBlockConversions.cpp:302: DB::fillMissingColumns(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long, DB::NamesAndTypesList const&, DB::NamesAndTypesList const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const>) @ 0x000000001b44dbb3
9. src/Processors/QueryPlan/ReadFromMemoryStorageStep.cpp:78: DB::MemorySource::generate() @ 0x000000001f103341
10. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000001eb79fe5
11. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001eb79cc2
12. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001eb954b0
13. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001eb87fd8
14. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001eb885e9
15. src/Processors/Executors/PipelineExecutor.cpp:565: void std::__function::__policy_func<void ()>::__call_func[abi:se210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0>(std::__function::__policy_storage const*) @ 0x000000001eb89701
16. contrib/llvm-project/libcxx/include/__functional/function.h:508: ? @ 0x00000000151becb6
17. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x00000000151c5066
18. contrib/llvm-project/libcxx/include/__functional/function.h:508: ? @ 0x00000000151bc0f2
19. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: void* std::__thread_proxy[abi:se210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000151c2c00
20. ? @ 0x00000000000a3d64
21. __GI___clone3 @ 0x00000000001373bc
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix possible crash during remote query with `ARRAY JOIN` inside `IN` and enabled `enable_lazy_columns_replication` setting. Resolves https://github.com/ClickHouse/ClickHouse/issues/90361

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Interpreters/inplaceBlockConversions.cpp [hunk 1]
```diff
@@ -423,10 +425,11 @@ void fillMissingColumns(
         const auto * array_type = typeid_cast<const DataTypeArray *>(requested_column->type.get());
         if (array_type && !offsets_columns.empty())
         {
-            num_dimensions = array_type->getNumberOfDimensions();
+            num_dimensions = getNumberOfDimensions(*array_type);
             current_offsets.resize(num_dimensions);
 
-            auto serialization = IDataType::getSerialization(*requested_column);
+            auto serialization_info = requested_column->type->getSerializationInfo(*res_columns[i]);
```
Comment (nikitamikhaylov) [inline src/Interpreters/inplaceBlockConversions.cpp]: Tests showed that a `type` might be nullptr.

Comment (Avogar) [reply src/Interpreters/inplaceBlockConversions.cpp]: It's actually `res_columns[i]` might be `nullptr`, I added a check for that

Comment (nikitamikhaylov) [reply src/Interpreters/inplaceBlockConversions.cpp]: Now it says that `res_columns` might not contain the index `i`...

**Comment by Avogar** [comment]
[Integration tests (amd_binary, 5/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=2d5b5a71b59f7083f7134908eca8c1ace1d1c72a&name_0=PR&name_1=Integration+tests+%28amd_binary%2C+5%2F5%29) - https://github.com/ClickHouse/ClickHouse/issues/90507
[AST fuzzer (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=2d5b5a71b59f7083f7134908eca8c1ace1d1c72a&name_0=PR&name_1=AST+fuzzer+%28amd_ubsan%29) - https://github.com/ClickHouse/ClickHouse/issues/86924
[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=2d5b5a71b59f7083f7134908eca8c1ace1d1c72a&name_0=PR&name_1=BuzzHouse+%28amd_debug%29) - https://github.com/ClickHouse/ClickHouse/issues/89924
[BuzzHouse (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=2d5b5a71b59f7083f7134908eca8c1ace1d1c72a&name_0=PR&name_1=BuzzHouse+%28arm_asan%29) - https://github.com/ClickHouse/ClickHouse/issues/83883
[BuzzHouse (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=2d5b5a71b59f7083f7134908eca8c1ace1d1c72a&name_0=PR&name_1=BuzzHouse+%28amd_tsan%29) - internal error

**Comment by Avogar** [comment]
New test failed in the Sync, investigating

**Comment by Avogar** [comment]
[Build (amd_compat)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=43dff1dfc90f8cf463369736b7789b54204bfcf5&name_0=PR&name_1=Build+%28amd_compat%29) - https://github.com/ClickHouse/ClickHouse/issues/90492
[Stress test (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=43dff1dfc90f8cf463369736b7789b54204bfcf5&name_0=PR&name_1=Stress+test+%28amd_debug%29) - https://github.com/ClickHouse/ClickHouse/issues/87016
[BuzzHouse (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89997&sha=43dff1dfc90f8cf463369736b7789b54204bfcf5&name_0=PR&name_1=BuzzHouse+%28amd_ubsan%29) - https://github.com/ClickHouse/ClickHouse/issues/88900
