### PR TITLE
fix possible datarace while setting s3queue_disable_streaming

### LINKED ISSUE #82668: datarace in test_storage_s3_queue/test_5.py::test_disable_streaming
report https://s3.amazonaws.com/clickhouse-test-reports/PRs/80237/44050fe765c3fd391bfd2efba62d99877aad8fe7//integration_tests_tsan_3_6/integration_run_test_storage_s3_queue_test_5_py_0.log

`global_context->setServerSetting` and `getServerSetting` is not thread safe, we should add an interface like `setS3QueueDisableStreaming`

### PR DESCRIPTION
**Pull request by bharatnc**
Follow up for https://github.com/ClickHouse/ClickHouse/pull/82515. Looks like a possible datarace can happen while setting the value without holding a mutex. Introduce getter and setter for this setting similar to other settings.

Closes: https://github.com/ClickHouse/ClickHouse/issues/82668

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by kssenii — APPROVED** [review]
Thanks

File: src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -4645,6 +4647,18 @@ void Context::setOSCPUOverloadSettings(double min_os_cpu_wait_time_ratio_to_drop
     shared->max_os_cpu_wait_time_ratio_to_drop_connection = max_os_cpu_wait_time_ratio_to_drop_connection;
 }
 
+bool Context::getS3QueueDisableStreaming() const
```
Comment (kssenii) [inline src/Interpreters/Context.cpp:4665]: Though after this change `getServerSetting()` does not work. And therefore the test `test_storage_s3_queue/test_5.py::test_disable_streaming` fails, but it seems nice to still be able to see the value of the setting via query, so it seems ok to have these setter and getter but modify server_settings inside instead? The race with getServerSetting should not happen, as I see this https://github.com/ClickHouse/ClickHouse/blob/3e8c0549307463d60ba44b6e3ffdaf414df820c4/src/Core/ServerSettings.cpp#L1177-L1179 and I did add the setting to this list.

Comment (bharatnc) [reply src/Interpreters/Context.cpp:4665]: > but modify server_settings inside instead?

Sorry, I didn't get this, can you explain?
> so it seems ok to have these setter and getter 

Are you referring that we keep the new getter and setter that I'm adding in this PR (`getS3QueueDisableStreaming` & `setS3QueueDisableStreaming`) or the ones  `Context::getServerSettings()` and `Context::setServerSettings()`?

Comment (bharatnc) [reply src/Interpreters/Context.cpp:4665]: nvm, I get it now. I will keep`getS3QueueDisableStreaming` & `setS3QueueDisableStreaming` but make them work with  `shared->server_settings` so that `getServerSettings()` will work again.

**Comment by bharatnc** [comment]
* [Integration tests (asan, old analyzer, 4/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82695&sha=af9c677aa818fb7a1583556e3de802c86ff56d2c&name_0=PR&name_1=Integration%20tests%20%28asan%2C%20old%20analyzer%2C%204%2F6%29) — Job timeout expired, fail: 0, passed: 600 - https://github.com/ClickHouse/ClickHouse/issues/82674
* [Stateless tests (amd_debug, AsyncInsert, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82695&sha=af9c677aa818fb7a1583556e3de802c86ff56d2c&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20AsyncInsert%2C%20s3%20storage%29) — Failed: 1, Passed: 7758, Skipped: 386 - https://github.com/ClickHouse/ClickHouse/issues/82792

File: src/Interpreters/Context.cpp (hunk 1 above)
Comment (bharatnc) [reply src/Interpreters/Context.cpp:4665]: fixed in [af9c677](https://github.com/ClickHouse/ClickHouse/pull/82695/commits/af9c677aa818fb7a1583556e3de802c86ff56d2c)
