### PR TITLE
Fix behaviour of quantileDeterministic function

### LINKED ISSUE #20480: quantileDeterministic and friends are not deterministic
**Describe the bug**
I've found that quantileDeterministic and relevant functions are not deterministic

On 21.2.3 release:
```sql
SELECT medianDeterministic(oid, oid) FROM ztf.dr4_meta

┌─medianDeterministic(oid, oid)─┐
│               686709400040570 │
└───────────────────────────────┘

SELECT medianDeterministic(oid, oid) FROM ztf.dr4_meta

┌─medianDeterministic(oid, oid)─┐
│               686315850035097 │
└───────────────────────────────┘

SELECT medianDeterministic(oid, oid) FROM ztf.dr4_meta

┌─medianDeterministic(oid, oid)─┐
│               686316400060683 │
└───────────────────────────────┘
```

**Does it reproduce on recent release?**
Yes

**How to reproduce**
* Which ClickHouse server version to use: 21.2.3
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE dr4_meta
(
    `oid` UInt64 CODEC(Delta(8), LZ4),
    `nobs` UInt16 CODEC(T64, LZ4),
    `ngoodobs` UInt16 CODEC(T64, LZ4),
    `filter` UInt8 CODEC(T64, LZ4),
    `fieldid` UInt16 CODEC(T64, LZ4),
    `rcid` UInt8,
    `ra` Float64,
    `dec` Float64,
    `h3index10` UInt64,
    `durgood` Float64,
    `mingoodmag` Float32,
    `maxgoodmag` Float32,
    `meangoodmag` Float32
)
ENGINE = MergeTree()
ORDER BY oid
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
[100GB tar](https://drive.google.com/file/d/1lRqzJx650MrTuY8SGfMTO9E_5U8xldL-/view?usp=sharing) of dr4_meta table

**Additional context**
20.6.4.1 works fine and always return `686316400060683`, while current version returns this or some other values. If `max_threads=1` is applied current version always returns `686709400040570`

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the possibility of non-deterministic behaviour of the `quantileDeterministic` function and similar. This closes #20480.

### CODE REVIEW

File: src/AggregateFunctions/ReservoirSamplerDeterministic.h [hunk 1]
```diff
@@ -220,10 +217,19 @@ class ReservoirSamplerDeterministic
...
     {
+        if (!good(hash))
+            return;
+
         /// Make a room for plus one element.
         while (samples.size() >= max_sample_size)
+        {
             setSkipDegree(skip_degree + 1);
 
+            /// Still good?
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/ReservoirSamplerDeterministic.h:228]: This is the fix.

In previous version, the value is not being filtered after coarsening, so one excessive value can appear in the final reservoir.

File: src/AggregateFunctions/ReservoirSamplerDeterministic.h [hunk 2]
```diff
@@ -59,9 +59,10 @@ template <typename T,
     ReservoirSamplerDeterministicOnEmpty OnEmpty = ReservoirSamplerDeterministicOnEmpty::THROW>
 class ReservoirSamplerDeterministic
 {
-    bool good(const UInt32 hash)
+private:
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/ReservoirSamplerDeterministic.h:62]: This is old code (circa 2014), it also contains strange decisions and mistakes. E.g. `total_values` is calculated and serialized but not used.

**Comment by alexey-milovidov** [comment]
> Functional stateless tests flaky check (address) — fail: 66, passed: 234 

This is fine.
