### PR TITLE
Read only required VIEW columns on the shards

### LINKED ISSUE #81718: Query to remote table with enable_analyzer=1 try to read all table from remote or Distributed, instead of executing query remotely
### Company or project name

bitquery

### Describe the situation

Query to remote table with enable_analyzer=1 try to read all table from remote or Distributed, instead of executing query remotely

Compare execution of a query:

```
charch37 :) SELECT max(`Block_Date`) AS `_Date_0`, count() AS `count()` FROM remote('chstrm36', 'eth', 'dex_trades_tx', 'default', '[PWD]') SETTINGS enable_analyzer=0

SELECT
    max(Block_Date) AS _Date_0,
    count() AS `count()`
FROM remote('chstrm36', 'eth', 'dex_trades_tx', 'default', '[PWD]')
         SETTINGS enable_analyzer = 0

Query id: ea088f8d-1dca-4deb-a8ef-513f86bce214

    ┌────_Date_0─┬───count()─┐
1. │ 2025-06-12 │ 394548119 │
   └────────────┴───────────┘

1 row in set. Elapsed: 5.044 sec. Processed 395.86 million rows, 794.61 MB (78.48 million rows/s., 157.54 MB/s.)
    Peak memory usage: 1.04 GiB.

    charch37 :) SELECT max(`Block_Date`) AS `_Date_0`, count() AS `count()` FROM remote('chstrm36', 'eth', 'dex_trades_tx', 'default', '[PWD]') SETTINGS enable_analyzer=1

SELECT
    max(Block_Date) AS _Date_0,
    count() AS `count()`
FROM remote('chstrm36', 'eth', 'dex_trades_tx', 'default', '[PWD]')
         SETTINGS enable_analyzer = 1

Query id: d0e5543e-413f-436e-a02f-4127f52dc582

Cancelling query.
Query was cancelled.

0 rows in set. Elapsed: 45.494 sec. Processed 28.98 million rows, 80.72 GB (636.94 thousand rows/s., 1.77 GB/s.)
    Peak memory usage: 4.47 GiB.
```

Same happens with using Distributed table.

Difference in huge: note the amount of disk read on the second case, and the query take so long that i can not wait for it

### Which ClickHouse versions are affected?

25.3.3.42

### How to reproduce

1. create remote table 
2. query with remote() with analyser on and off and compare 

### Expected performance

Perfomance exected be the same with analyzer ON

### Additional context

1. when same query executed locally on server , where remote table located, it s executed OK
2. when Distributed query executed locally on server , where remote table located, it s executed OK

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix performance degradation with the enabled analyzer when secondary queries always read all columns from the VIEWs. Fixes https://github.com/ClickHouse/ClickHouse/issues/81718.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Analyzer/QueryTreePassManager.cpp [hunk 1]
```diff
@@ -193,8 +193,12 @@ void QueryTreePassManager::run(QueryTreeNodePtr query_tree_node)
 
 void QueryTreePassManager::runOnlyResolve(QueryTreeNodePtr query_tree_node)
 {
-    // Run only QueryAnalysisPass and GroupingFunctionsResolvePass passes.
-    run(query_tree_node, 3);
+    // Run only query tree passes that doesn't affect output header:
```
Comment (KochetovNicolai) [inline src/Analyzer/QueryTreePassManager.cpp:196]: Maybe we can even have a special case for MV

**Review by KochetovNicolai — APPROVED** [review]

**Comment by novikd** [comment]
> [Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83036&sha=c5c54e99a287c11fdaae63181f59f7a8e14cf553&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%202%2F2%29) — Failed: 0, Passed: 3899, Ski

https://github.com/ClickHouse/ClickHouse/issues/74734
