### PR TITLE
MaterializedMySQL: Fix the infinite loop in ReadBuffer::read

### LINKED ISSUE #33549: infinite loop in MaterializeMySQL replicaton
**Describe what's wrong**
When I do incremental replication from MySQL to ClickHouse by using MaterializeMySQL. Then I drop database from MySQL side first  , and then drop from ClickHouse side. The drop op will hang there.
I print the stacktrace and find the readOneBinlogEvent is not return. and DB::ReadBuffer::readStrict is in an infinite loop.

**Does it reproduce on recent release?**
I use V21.8.9.13-lts

**How to reproduce**
create a database in MySQL side , and replicate (do incremental replication ) it to ClickHouse for a while. and then drop it from MySQL side first, and then drop it from clickhouse side.

* Which ClickHouse server version to use
* V21.8.9.13-lts

**Error message and/or stacktrace**

```
#0  DB::ReadBuffer::readStrict (this=<optimized out>, to=<optimized out>, n=0) at ../src/IO/ReadBuffer.h:185
#1  0x000000000dcd439a in DB::MySQLBinlogEventReadBuffer::nextImpl (this=0x7fee251ea540) at ../src/IO/MySQLBinlogEventReadBuffer.cpp:49
#2  0x000000000778dca4 in DB::ReadBuffer::next (this=this@entry=0x7fee251ea540) at ../src/IO/ReadBuffer.h:62
#3  0x000000000778dd88 in eof (this=0x7fee251ea540) at ../src/IO/ReadBuffer.h:175
#4  DB::ReadBuffer::read (this=0x7fee251ea540, to=0x7fee251ea1fc "", n=4) at ../src/IO/ReadBuffer.h:170
#5  0x00000000077a8c59 in DB::ReadBuffer::readStrict (this=<optimized out>, to=<optimized out>, n=4) at ../src/IO/ReadBuffer.h:184
#6  0x000000000d5c3096 in DB::MySQLReplication::readBigEndianStrict (payload=..., to=to@entry=0x7fee251ea1fc "", n=4) at ../src/Core/MySQL/MySQLReplication.h:38
#7  0x000000000d5c4403 in _ZZN2DB16MySQLReplication9RowsEvent8parseRowERNS_10ReadBufferERN5boost14dynamic_bitsetImNSt3__19allocatorImEEEEENKUlmmT_E0_clINS_7DecimalIN4wide7integerILm256EiEEEEEEDammSB_.constprop.0 () at ../src/Core/MySQL/MySQLReplication.cpp:634
#8  0x000000000d5c4634 in operator()<DB::MySQLReplication::RowsEvent::parseRow(DB::ReadBuffer&, DB::MySQLReplication::Bitmap&)::<lambda(size_t, size_t, auto:9)> >(size_t, size_t, const struct {...} &) (precision=precision@entry=576460752303423488, scale=scale@entry=8, function=..., __closure=<optimized out>) at ../src/Core/MySQL/MySQLReplication.cpp:589
#9  0x000000000d5c79db in DB::MySQLReplication::RowsEvent::parseRow(DB::ReadBuffer&, boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >&) ()
    at ../src/Core/MySQL/MySQLReplication.cpp:676
#10 0x000000000d5c87fb in DB::MySQLReplication::RowsEvent::parseImpl (this=0x7fee358b3718, payload=...) at ../src/Core/MySQL/MySQLReplication.cpp:404
#11 0x000000000d5c8c74 in DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) () at ../src/Core/MySQL/MySQLReplication.cpp:1063
#12 0x000000000daedab2 in DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) () at ../src/Core/MySQL/IMySQLReadPacket.cpp:20
#13 0x000000000d5cc736 in DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) () at ../src/Core/MySQL/PacketEndpoint.cpp:49
#14 0x000000000d5be1fe in DB::MySQLClient::readOneBinlogEvent (this=this@entry=0x7fee359fa310, milliseconds=<optimized out>) at ../src/Core/MySQL/MySQLClient.cpp:175
#15 0x000000000cd94ee1 in DB::MaterializeMySQLSyncThread::synchronization() () at ../src/Databases/MySQL/MaterializeMySQLSyncThread.cpp:238
#16 0x000000000cd9510d in _ZZN20ThreadFromGlobalPoolC4IZN2DB26MaterializeMySQLSyncThread20startSynchronizationEvEUlvE_JEEEOT_DpOT0_ENUlvE_clEv () at ../src/Common/ThreadPool.h:166
#17 0x00000000077d8d9d in ThreadPoolImpl<std::__1::thread>::worker (this=0x7feff12a6f00, thread_it=...) at ../src/Common/ThreadPool.cpp:228
#18 0x00000000077d908c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#3}::operator()() 
```

I have debuged it and found something wrong. But I don't know how to handle this situation.

In IO/MySQLBinlogEventReadBuffer.cpp:49
```
else
    {
        for (size_t index = 0; index < checksum_buff_size - checksum_buff_limit; ++index)
            checksum_buf[index] = checksum_buf[checksum_buff_limit + index];

        checksum_buff_size -= checksum_buff_limit;
        size_t read_bytes = checksum_signature_length - checksum_buff_size;
        in.readStrict(checksum_buf + checksum_buff_size, read_bytes);   /// Minimum checksum_signature_length bytes
        checksum_buff_size = checksum_buff_limit = checksum_signature_length;
    }
```
 the read_bytes  is 0, should I return false here if the read_bytes  is 0?

### PR DESCRIPTION
**Pull request by valbok**
This fixes https://github.com/ClickHouse/ClickHouse/issues/33549

The infinite loop caused because sometimes the pos of ReadBuffer overflows the end.

It happens f.e. when `MySQLPacketPayloadReadBuffer::nextImpl` might return empty buffer, since `in.nextIfAtEnd();` could not read more bytes and thus no bytes available (pos == end). 
It might happen when a network error or the connection to MySQL was closed or killed. This leads to empty `working_buffer` but successful returning (`return true;`) from the func. 
And check `if (in.eof())` from `MySQLBinlogEventReadBuffer::nextImpl()` fails and also causes empty its `working_buffer` and successful return.

At the end `payload.ignore(1)` and `payload.read(c)` produces the infinite loop since it is not eof() and ++pos overflows the end of the buffer.
**When pos > end, it is never eof() since avaliable() always > 0**

Should be tested by `test_mysql_kill*` from test_materialized_mysql_database/test.py

Details:
`MySQLClient` calls `MySQLFlavor::readPayload(ReadBufferFromPocoSocket)` where the flow is
`MySQLBinlogEventReadBuffer` -> `MySQLPacketPayloadReadBuffer` -> `ReadBufferFromPocoSocket`

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fixed the infinite loop in ReadBuffer when the pos overflows the end of the buffer in MaterializedMySQL.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit a547cb57bc309862b2f6149486393f268ab64d02 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52621/a547cb57bc309862b2f6149486393f268ab64d02/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/IO/ReadBuffer.h [hunk 1]
```diff
@@ -115,7 +115,7 @@ class ReadBuffer : public BufferBase
 
     void ignore(size_t n)
     {
-        while (n != 0 && !eof())
+        while (n != 0 && !eof() && pos < working_buffer.end())
```
Comment (alexey-milovidov) [inline src/IO/ReadBuffer.h:118]: This modification looks strange, most likely unneeded.
Are the modifications in MaterializedMySQL enough?

Comment (valbok) [reply src/IO/ReadBuffer.h:118]: Technically this is not needed, https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/ReadBuffer.h#L77 this assert should notify when impl returns nothing. Interesting why we don't see this assert...
Also found some failed tests locally, converted to draft to test.

**Comment by valbok** [comment]
OptimizeDateOrDateTimeConverterWithPreimagePass.cpp:51:10: error: unused member function 'visitImpl'

**Comment by valbok** [comment]
test_storage_azure_blob_storage/test.py::test_read_from_not_existing_container not related

**Comment by valbok** [comment]
test_storage_kafka failed, not related to PR

**Comment by valbok** [comment]
@kssenii

File: src/IO/MySQLBinlogEventReadBuffer.cpp [hunk 2]
```diff
@@ -51,7 +51,8 @@ bool MySQLBinlogEventReadBuffer::nextImpl()
         checksum_buff_size = checksum_buff_limit = checksum_signature_length;
     }
 
-    if (in.eof())
+    /// Check also available bytes after eof() to prevent empty working_buffer
+    if (in.eof() || !in.hasPendingData())
```
Comment (kssenii) [inline src/IO/MySQLBinlogEventReadBuffer.cpp:55]: this change looks pointless because https://github.com/ClickHouse/ClickHouse/blob/c556ad96f6631b18613b8463c1bf1f3ab9965a06/src/IO/ReadBuffer.h#L103-L106
and it should be impossible that `hasPendingData() == false` after `next()` returned `true` (otherwise it is a bug in read buffer).

So looks like the fix in `src/IO/MySQLPacketPayloadReadBuffer.cpp` is enough to fix the issue.

Comment (valbok) [reply src/IO/MySQLBinlogEventReadBuffer.cpp:55]: It is correct, but together with first fix for `ReadBuffer.h`, what would happen if `MySQLBinlogEventReadBuffer` would be used with different buffer, not `MySQLPacketPayloadReadBuffer` ? Also finally `ReadBuffer::next()` has assert to prevent empty buffers from its impl, which requires the impl to be more correct.

Comment (kssenii) [reply src/IO/MySQLBinlogEventReadBuffer.cpp:55]: >  what would happen if MySQLBinlogEventReadBuffer would be used with different buffer, not MySQLPacketPayloadReadBuffer ? 

then if this another buffer returns `true` from `next()`, but in fact `working_buffer.empty()`, then this buffer has a bug and it should be fixed. This check in `MySQLBinlogEventReadBuffer.cpp` will just hide the bug.

**Review by kssenii — APPROVED** [review]

**Comment by valbok** [comment]
thanks
