### PR TITLE
Fix possible error 'URI contains invalid characters' in s3 table function

### LINKED ISSUE #54345: S3 URI parsing broken in v23.8.1
**Describe what's wrong**
Clickhouse returns the following error while using s3 function when URI contains special character like space

> Poco::Exception. Code: 1000, e.code() = 0, Bad URI syntax: URI contains invalid characters (version 23.8.1.2992 (official build))

The same query with that specific URI works in *23.7.3*

**Does it reproduce on recent release?**

**v23.8.1**

**Enable crash reporting**
N/A

**How to reproduce**

Run the below query 

> SELECT * FROM s3('https://mybucket.s3.us-west-2.amazonaws.com/MyPrefix/BU%20-%20UNIT%20-%201/*.parquet', '****', '*****') LIMIT 200

**Expected behavior**

Query should be executed without any error

**Error message and/or stacktrace**

`2023.09.06 07:55:15.852136 [ 418 ] {ae85c0cf-40a9-4ecf-9070-8f729f43d9f0} <Error> DynamicQueryHandler: Poco::Exception. Code: 1000, e.code() = 0, Bad URI syntax: URI contains invalid characters, Stack trace (when copying this message, always include the lines below):

0. Poco::URI::parse(String const&) @ 0x0000000015c4baeb in /opt/bitnami/clickhouse/bin/clickhouse
1. Poco::URI::URI(String const&, bool) @ 0x0000000015c4a387 in /opt/bitnami/clickhouse/bin/clickhouse
2. DB::TableFunctionS3::parseArgumentsImpl(absl::lts_20211102::InlinedVector<std::shared_ptr<DB::IAST>, 7ul, std::allocator<std::shared_ptr<DB::IAST>>>&, std::shared_ptr<DB::Context const> const&) @ 0x000000001098a72f in /opt/bitnami/clickhouse/bin/clickhouse
3. DB::TableFunctionS3::parseArguments(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>) @ 0x000000001098ba51 in /opt/bitnami/clickhouse/bin/clickhouse
4. DB::TableFunctionFactory::get(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>) const @ 0x0000000010bfdcf4 in /opt/bitnami/clickhouse/bin/clickhouse
5. DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, DB::ASTSelectQuery const*) @ 0x00000000116174ee in /opt/bitnami/clickhouse/bin/clickhouse
6. DB::JoinedTables::getLeftTableStorage() @ 0x0000000011f9e556 in /opt/bitnami/clickhouse/bin/clickhouse
7. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x0000000011eaa22c in /opt/bitnami/clickhouse/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000011f5c408 in /opt/bitnami/clickhouse/bin/clickhouse
9. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000011e647be in /opt/bitnami/clickhouse/bin/clickhouse
10. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000122a576a in /opt/bitnami/clickhouse/bin/clickhouse
11. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x00000000122a8e11 in /opt/bitnami/clickhouse/bin/clickhouse
12. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x00000000130b2d4f in /opt/bitnami/clickhouse/bin/clickhouse
13. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000130b7629 in /opt/bitnami/clickhouse/bin/clickhouse
14. DB::HTTPServerConnection::run() @ 0x0000000013127fd2 in /opt/bitnami/clickhouse/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x0000000015b10374 in /opt/bitnami/clickhouse/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b11571 in /opt/bitnami/clickhouse/bin/clickhouse
17. Poco::PooledThread::run() @ 0x0000000015c47da7 in /opt/bitnami/clickhouse/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c4607c in /opt/bitnami/clickhouse/bin/clickhouse
19. start_thread @ 0x0000000000007ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
20. ? @ 0x00000000000fba2f in /lib/x86_64-linux-gnu/libc-2.31.so
 (version 23.8.1.2992 (official build))`

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible error 'URI contains invalid characters' in s3 table function. Closes https://github.com/ClickHouse/ClickHouse/issues/54345

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/TableFunctions/TableFunctionS3.cpp [hunk 1]
```diff
@@ -176,12 +177,12 @@ void TableFunctionS3::parseArgumentsImpl(ASTs & args, const ContextPtr & context
...
         configuration.auth_settings.no_sign_request = no_sign_request;
+
+        if (configuration.format == "auto")
+            configuration.format = FormatFactory::instance().getFormatFromFileName(Poco::URI(url).getPath(), true);
     }
 
     configuration.keys = {configuration.url.key};
-
-    if (configuration.format == "auto")
-        configuration.format = FormatFactory::instance().getFormatFromFileName(Poco::URI(configuration.url.uri.getPath()).getPath(), true);
```
Comment (Avogar) [inline src/TableFunctions/TableFunctionS3.cpp:184]: The problem was here in `Poco::URI(configuration.url.uri.getPath()).getPath()`. Initially it was a workaround to extract correct filename from url with query parameters, because S3::URI encoded `?` symbol. Now I just use initial url here, so nothing is encoded and `getPath()` method returns path without query parameters

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit ab101eaff8ff36aa31c50bf3c20e2e4e23fe571a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54373/ab101eaff8ff36aa31c50bf3c20e2e4e23fe571a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by antonio2368 — APPROVED** [review]
