### PR TITLE
Versioning of aggregate function states

### LINKED ISSUE #12552: Versioning of AggregateFunction states.
**Use case**

Sometimes we have to change serialization format of AggregateFunction states due to bugs or inefficiencies. It should not compromise backward compatibility.

Currently we do it only in exceptional cases:

When this aggregate function is released just recently and rarely used. And we have to put a warning about backward compatibility in changelog.

Sometimes we just miss changes by mistake.

**Proposal**

Methods `IAggregateFunction::serialize`, `IAggregateFunction::deserialize` will take additional argument with version. These methods have to support serialization and deserialization with all known versions.

When user creates a data type `AggregateFunction(...)`, e.g. `AggregateFunction(avg, UInt64)`, we transform it adding parameter with version at front with the most recent version, e.g. `AggregateFunction(v1, avg, UInt64)`.

The user will see the data type with version number in SHOW CREATE TABLE, DESCRIBE TABLE, etc.

When data type `AggregateFunction(...)` without version is already specified in table definition or in serialization formats (Native), version 0 is assumed implicitly.

When sending data to the client with native protocol, the revision of the client is taken into account. `IAggregateFunction` should have a method to determine the maximum supported version according to the client revision. The version of `AggregateFunction` is changed that way. If `AggregateFunction` data type will have version zero, it is not printed in data type name.

**Scenarios**

1. Server sends data to old client. Should work seamless.
2. Server sends data to old client that is actually another server that initiated distributed query. Should work seamless.
3. We have a table with columns of AggregateFunction data type stored inside; then upgraded the server and continue to read and write to that table. Should work seamless.
4. We have a table with columns of AggregateFunction data type stored inside; then upgraded the server and continue to read and write to that table. Then downgraded the server and continued to read and write to that table. Should work seamless.
5. We have created dump in format TSVWithNamesAndTypes, CSVWithNamesAndTypes, etc. on old server, then trying to upload it to new server. Should work seamless.
6. We have created dump in format without data types (like TSV, RowBinary) on old server. Then trying to upload it to new server. It may require user to explicitly specify version in data type when creating a table.

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/12552. Allow versioning of aggregate function states.

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionSumMap.h [hunk 1]
```diff
@@ -250,35 +264,86 @@ class AggregateFunctionMapBase : public IAggregateFunctionDataHelper<
...
+            version = getDefaultVersion();
+
         const auto & merged_maps = this->data(place).merged_maps;
         size_t size = merged_maps.size();
         writeVarUInt(size, buf);
 
+        std::function<void(size_t, const Array &)> serialize;
+        switch (*version)
+        {
+            case 0:
```
Comment (kssenii) [inline src/AggregateFunctions/AggregateFunctionSumMap.h:279]: This could be a fix for https://github.com/ClickHouse/ClickHouse/issues/16587#issuecomment-726713143, but not sure for now - it will require to add some more if conditions to make this fix fully correct, but this will slow down the serialization. So it will be moved to some new "testing" aggregate function just for tests if nothing good comes to mind.

File: src/AggregateFunctions/AggregateFunctionSumMap.h [hunk 2]
```diff
@@ -250,35 +264,86 @@ class AggregateFunctionMapBase : public IAggregateFunctionDataHelper<
...
+            }
+            case 1:
+            {
+                serialize = [&](size_t col_idx, const Array & values)
+                {
+                    const auto & type = values_types[col_idx];
+                    if (!type->isNullable())
+                        type->promoteNumericType()->getDefaultSerialization()->serializeBinary(values[col_idx], buf);
+                    else
+                        values_serializations[col_idx]->serializeBinary(values[col_idx], buf);
```
Comment (CurtizJ) [inline src/AggregateFunctions/AggregateFunctionSumMap.h:292]: I think, it's better to create promoted serialization in constructor, because it's quite slow to promote type and create serialization for each row.

File: src/AggregateFunctions/AggregateFunctionSumMap.h [hunk 3]
```diff
@@ -250,35 +264,86 @@ class AggregateFunctionMapBase : public IAggregateFunctionDataHelper<
...
+            }
+            case 1:
+            {
+                deserialize = [&](size_t col_idx, Array & values)
+                {
+                    const auto & type = values_types[col_idx];
+                    if (!type->isNullable())
+                        type->promoteNumericType()->getDefaultSerialization()->deserializeBinary(values[col_idx], buf);
+                    else
+                        values_serializations[col_idx]->deserializeBinary(values[col_idx], buf);
```
Comment (CurtizJ) [inline src/AggregateFunctions/AggregateFunctionSumMap.h:331]: The same as for `serialize`.

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 4]
```diff
@@ -1047,9 +1055,10 @@ void IMergeTreeDataPart::loadColumns(bool require)
     else
     {
         loaded_columns.readText(*volume->getDisk()->readFile(path));
+        loaded_from_disk = true;
     }
 
-    setColumns(loaded_columns);
+    setColumns(loaded_columns, loaded_from_disk);
```
Comment (CurtizJ) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:1061]: I'd prefer to modify columns right here instead of introducing flag in `setColumns`.

File: src/AggregateFunctions/AggregateFunctionSumMap.h (hunk 2 above)
Comment (CurtizJ) [reply src/AggregateFunctions/AggregateFunctionSumMap.h:292]: Also we can do it for `Nullable` too. `removeNullable` -> `promoteNumericType` -> `makeNullable`.

File: src/AggregateFunctions/AggregateFunctionSumMap.h [hunk 5]
```diff
@@ -85,6 +87,18 @@ class AggregateFunctionMapBase : public IAggregateFunctionDataHelper<
             values_serializations.emplace_back(type->getDefaultSerialization());
     }
 
+    bool isVersioned() const override { return true; }
+
+    size_t getDefaultVersion() const override { return 1; }
+
+    size_t getVersionFromRevision(size_t revision) const override
+    {
+        if (revision >= 54448)
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/AggregateFunctions/AggregateFunctionSumMap.h:112]: something like `AGGREGATE_FUNCTION_SUM_MAP_VERSION_0_REVISION=54448`?

File: src/DataStreams/NativeBlockOutputStream.cpp [hunk 6]
```diff
@@ -123,7 +131,7 @@ void NativeBlockOutputStream::write(const Block & block)
 
         /// Data
         if (rows)    /// Zero items of data is always represented as zero number of bytes.
-            writeData(*column.type, column.column, ostr, 0, 0);
+            writeData(*column.type, column.column, ostr, 0, 0, client_revision);
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/DataStreams/NativeBlockOutputStream.cpp]: Looks fixed now:
https://github.com/ClickHouse/ClickHouse/blob/08d60a7754a40625a8cb6e21d4fc04d98778baeb/src/Formats/NativeWriter.cpp#L117-L130

File: src/AggregateFunctions/AggregateFunctionSumMap.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (CurtizJ) [reply src/AggregateFunctions/AggregateFunctionSumMap.h:112]: Ok, you can put in `AggregateFunctionSumMap`.

**Review by CurtizJ — APPROVED** [review]
