### PR TITLE
More types in ASOF JOIN

### LINKED ISSUE #7896: ASOF join Date type is not supported.
> should be one of the data types: UInt32, UInt64, Float32, Float64, Date, and DateTime

`Code: 169. DB::Exception: Received from 192.168.99.100:9091. DB::Exception: ASOF join not supported for typeUInt16`

When I changed my field for `asof_condition` to `Datetime` my query worked.

In the code, I found no mentioning of the Date type. Lokes like the documentation goes a bit ahead or the type was forgotten.

```
        asof_type = AsofRowRefs::getTypeSize(asof_column, asof_size);
        if (!asof_type)
        {
            std::string msg = "ASOF join not supported for type";
            msg += asof_column->getFamilyName();
            throw Exception(msg, ErrorCodes::BAD_TYPE_OF_FIELD);
        }
```

[RowRefs.cpp](https://github.com/ClickHouse/ClickHouse/blob/3ceeb95145430ce24302b94a03004c5b37e9a1c7/dbms/src/Interpreters/RowRefs.cpp#L17)

```
void callWithType(AsofRowRefs::Type which, F && f)
{
    switch (which)
    {
        case AsofRowRefs::Type::key32:  return f(UInt32());
        case AsofRowRefs::Type::key64:  return f(UInt64());
        case AsofRowRefs::Type::keyf32: return f(Float32());
        case AsofRowRefs::Type::keyf64: return f(Float64());
    }

    __builtin_unreachable();
}

}


AsofRowRefs::AsofRowRefs(Type type)
{
    auto call = [&](const auto & t)
    {
      using T = std::decay_t<decltype(t)>;
      using LookupType = typename Entry<T>::LookupType;
      lookups = std::make_unique<LookupType>();
    };

    callWithType(type, call);
}
```

Sorry for the poorly written issue report.

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support (U)Int8, (U)Int16, Date in ASOF JOIN.

Closes #7896

### CODE REVIEW

File: src/Interpreters/RowRefs.cpp [hunk 1]
```diff
@@ -96,52 +102,56 @@ const RowRef * AsofRowRefs::findAsof(Type type, ASOF::Inequality inequality, con
...
-    }
-    else if (typeid_cast<const ColumnDecimal<Decimal64> *>(asof_column))
-    {
-        size = sizeof(Decimal64);
-        return Type::keyDecimal64;
-    }
-    else if (typeid_cast<const ColumnDecimal<Decimal128> *>(asof_column))
+    TypeIndex idx = columnVectorDataType(asof_column);
+    if (idx == TypeIndex::Nothing)
+        idx = columnDecimalDataType(asof_column);
```
Comment (nikitamikhaylov) [inline src/Interpreters/RowRefs.cpp:109]: Maybe better to make a function like `getDataType` ?

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Interpreters/RowRefs.cpp (hunk 1 above)
Comment (4ertus2) [reply src/Interpreters/RowRefs.cpp:109]: If you're talking about `IColumn::getDataType()`, it's a good idea. But I do not want to change all columns files in this PR.
