### PR TITLE
Fix type mismatch issue when using LowCardinality keys in joinGet

### LINKED ISSUE #21114: Type mismatch in joinGet key 0: found type LowCardinality(String), while the needed type is String
**Describe the issue**
joinGet logic changed in version 20.10 Is it expected?

**How to reproduce**
```sql
5a3c7fc52a80 :) select version()
┌─version()─┐
│ 20.10.7.4 │
└───────────┘

CREATE TABLE join_tbl
(
    `id` String,
    `name` String
)
ENGINE = Join(ANY, LEFT, id)

Ok.

5a3c7fc52a80 :) SELECT joinGet('join_tbl', 'name', toLowCardinality('string'))

Received exception from server (version 20.10.7):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Type mismatch in joinGet key 0: found type LowCardinality(String), while the needed type is String. 

0 rows in set. Elapsed: 0.001 sec. 

```

**Workaround**
cast `LowCardinality` type to plain type like this
```sql
SELECT joinGet('join_tbl', 'name', CAST(toLowCardinality('string'), 'String'))

┌─joinGet('join_tbl', 'name', CAST(toLowCardinality('string'), 'String'))─┐
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

```

**Additional context**
version 20.9 not affected.

```sql
7eb3ee648dd4 :) select version()
:-] 

┌─version()─┐
│ 20.9.7.11 │
└──────┘

CREATE TABLE join_tbl
(
    `id` String,
    `name` String
)
ENGINE = Join(ANY, LEFT, id)

Ok.

7eb3ee648dd4 :) SELECT joinGet('join_tbl', 'name', toLowCardinality('string'))

SELECT joinGet('join_tbl', 'name', toLowCardinality('string'))

┌─joinGet('join_tbl', 'name', toLowCardinality('string'))─┐
│                                                         │
└────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

```

Also join `lowCardinality(String)` and `String` for `MergeTree` tables ok on both versions
```sql

CREATE TABLE lc_test
(
    `id` LowCardinality(String)
)
ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY id

CREATE TABLE test
(
    `id` String
)
ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY id

SELECT *
FROM test
INNER JOIN lc_test ON test.id = lc_test.id

Ok.

0 rows in set. Elapsed: 0.002 sec. 
```

---
same behavior as 20.10 on 21.2

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix type mismatch issue when using LowCardinality keys in joinGet. This fixes https://github.com/ClickHouse/ClickHouse/issues/21114

Detailed description / Documentation draft:

.

### CODE REVIEW

File: src/Interpreters/HashJoin.cpp [hunk 1]
```diff
@@ -1232,8 +1232,8 @@ DataTypePtr HashJoin::joinGetCheckAndGetReturnType(const DataTypes & data_types,
     {
         const auto & left_type_origin = data_types[i];
         const auto & [c2, right_type_origin, right_name] = right_table_keys.safeGetByPosition(i);
-        auto left_type = removeNullable(left_type_origin);
-        auto right_type = removeNullable(right_type_origin);
+        auto left_type = removeLowCardinality(removeNullable(left_type_origin));
```
Comment (vdimir) [inline src/Interpreters/HashJoin.cpp:1235]: Can we use `recursiveRemoveLowCardinality` here like in type check for regular join?

https://github.com/ClickHouse/ClickHouse/blob/427e5f295cf0f88fc1ea0de2722f016d0998cfc7/src/Interpreters/join_common.cpp#L233

Comment (amosbird) [reply src/Interpreters/HashJoin.cpp:1235]: Ah, yes.

**Review by vdimir — APPROVED** [review]
