### PR TITLE
make arrayCompact behave as other higher-order functions

### LINKED ISSUE #34010: arrayCompact: higher-order ?
**Describe the unexpected behaviour**

Current implementation of arrayCompact does not behave as other higher-order functions: it accepts lambda function as its first argument, but then it compacts array returned by lambda, not original array (see below for example).

**How to reproduce**
* Which ClickHouse server version to use

Any modern

* Queries to run that lead to unexpected result

select arrayCompact(x -> x.2 , groupArray(tuple(number, intDiv(number, 3) % 3))) from numbers(10);

**Expected behavior**

arrayCompact shall follow normal higher-order functons way and use results of lambda function ([0,0,0,1,1,1,2,2,2,0]) to compact original array ([(0,0),(1,0),(2,0),(3,1),(4,1),(5,1),(6,2),(7,2),(8,2),(9,0)]) into [(0,0),(3,1),(6,2),(9,0)]

**Additional context**

Use case: timeseries (time, value) with lots of repeated values that shall be compacted into (first time, value) when value repeats.

### PR DESCRIPTION
**Pull request by snar**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make arrayCompact behave as other higher-order functions: perform compaction not of
lambda function results but on original array. If you using nontrivial lambda functions
in arrayCompact you may restore old behaviour by wrapping arrayCompact arguments into
arrayMap. Closes #34010 #18535 #14778.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Functions/array/arrayCompact.cpp [hunk 1]
```diff
@@ -60,23 +57,22 @@ struct ArrayCompactImpl
...
                 /// For the rest of elements, insert if the element is different from the previous.
                 ++src_pos;
                 ++res_pos;
                 for (; src_pos < src_offset; ++src_pos)
                 {
-                    if (!bitEquals(src_values[src_pos], src_values[src_pos - 1]))
+                    if (!bitEquals(check_values[src_pos], check_values[src_pos - 1]))
                     {
-                        res_values[res_pos] = src_values[src_pos];
+                        res_values_column->insertFrom(src_values, src_pos);
```
Comment (CurtizJ) [inline src/Functions/array/arrayCompact.cpp:69]: I think, it's worth to make  a specialization for `Array` of integers and operate over arrays as it was before and avoid virtual call in a loop in that case. It makes sense, because `arrayCompact` with single `Array` of integers has been slowed down.

`clickhouse benchmark <<< "select arrayCompact(range(number % 1000)) from numbers(100000) format Null" --cumulative`

In your PR:
```
localhost:9000, queries 62, QPS: 4.360, RPS: 571169.982, MiB/s: 4.358, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.204 sec.	
10.000%		0.212 sec.	
20.000%		0.215 sec.	
30.000%		0.217 sec.	
40.000%		0.219 sec.	
50.000%		0.222 sec.	
60.000%		0.227 sec.	
70.000%		0.239 sec.	
80.000%		0.245 sec.	
90.000%		0.253 sec.	
95.000%		0.261 sec.	
99.000%		0.281 sec.	
99.900%		0.301 sec.	
99.990%		0.301 sec.
```

In master:

```
localhost:9000, queries 133, QPS: 13.072, RPS: 1712517.749, MiB/s: 13.065, result RPS: 0.000, result MiB/s: 0.000.

0.000%		0.051 sec.	
10.000%		0.053 sec.	
20.000%		0.054 sec.	
30.000%		0.054 sec.	
40.000%		0.055 sec.	
50.000%		0.056 sec.	
60.000%		0.057 sec.	
70.000%		0.060 sec.	
80.000%		0.135 sec.	
90.000%		0.138 sec.	
95.000%		0.140 sec.	
99.000%		0.143 sec.	
99.900%		0.155 sec.	
99.990%		0.155 sec.
```

**Review by CurtizJ — APPROVED** [review]
