### PR TITLE
Don't allow adaptive_write_buffer_initial_size set to 0

### LINKED ISSUE #81045: SerializationString Crash after DROP/ADD the same column
### Company or project name

_No response_

### Describe what's wrong

It seems with schemas that use column names with dot and type Array after DROP/ADD column, ClickHouse may crash unexpectedly with signal 11. 

If it was related with flatten_nested I just tested both scenarions with and without flatten_nested set, and the same crash

Maybe related? https://github.com/ClickHouse/ClickHouse/pull/66243

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
CREATE TABLE test_flatten_nested_crash
(
    `id` UInt64,
    `tenant` String,
    `arr.id` Array(Nullable(UInt64)),
    `arr.name` Array(Nullable(String)),
    `arr.nested` Array(Tuple(a String, b Float64))
)
ENGINE = MergeTree
ORDER BY (id)
SETTINGS index_granularity = 8192

INSERT INTO test_flatten_nested_crash
SELECT * FROM generateRandom(
    '`id` UInt64,
    `tenant` String,
    `arr.id` Array(Nullable(UInt64)),
    `arr.name` Array(Nullable(String)),
    `arr.nested` Array(Tuple(a String, b Float64))', 1, 10
) LIMIT 1000000;

SELECT arr.nested FROM test_flatten_nested_crash LIMIT 10000;

ALTER TABLE test_flatten_nested_crash DROP COLUMN `arr.nested`; -- Works

ALTER TABLE test_flatten_nested_crash ADD COLUMN `arr.nested` Array(Tuple(a String, b Float64));

SELECT arr.nested FROM test_flatten_nested_crash LIMIT 10000; -- Crash
```

### Expected behavior

_No response_

### Error message and/or stacktrace

```
025.05.30 09:45:53.670631 [ 796 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.05.30 09:45:53.670668 [ 796 ] {} <Fatal> BaseDaemon: (version 24.12.6.70 (official build), build id: FFDA1CA7B4252C3AD27E1640C404E475B78BB2AA, git hash: 834cccbc6e8c7f0db21ec500394c3a567b83482f, architecture: x86_64) (from thread 77) Received signal 11
2025.05.30 09:45:53.670685 [ 796 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2025.05.30 09:45:53.670695 [ 796 ] {} <Fatal> BaseDaemon: Address: 0x1. Access: read. Address not mapped to object.
2025.05.30 09:45:53.670705 [ 796 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000dac20b5 0x000075674933c520 0x0000000008e8a08c 0x00000000113fbedf 0x0000000011386da6 0x0000000011411340 0x0000000011390cfd 0x000000001374af3d 0x000000001370f3d8 0x00000000136f6662 0x0000000013711738 0x000000001664eba7 0x000000001664f039 0x000000001661b95c 0x0000000016619efd 0x000075674938eac3 0x000075674941fa04
2025.05.30 09:45:53.670721 [ 796 ] {} <Fatal> BaseDaemon: ########################################
2025.05.30 09:45:53.670759 [ 796 ] {} <Fatal> BaseDaemon: (version 24.12.6.70 (official build), build id: FFDA1CA7B4252C3AD27E1640C404E475B78BB2AA, git hash: 834cccbc6e8c7f0db21ec500394c3a567b83482f) (from thread 77) (query_id: 1838b41a-b179-436d-bb81-fcbf97367629) (query: SELECT arr.nested FROM test_flatten_nested_crash LIMIT 10000;) Received signal Segmentation fault (11)
2025.05.30 09:45:53.670774 [ 796 ] {} <Fatal> BaseDaemon: Address: 0x1. Access: read. Address not mapped to object.
2025.05.30 09:45:53.670785 [ 796 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000dac20b5 0x000075674933c520 0x0000000008e8a08c 0x00000000113fbedf 0x0000000011386da6 0x0000000011411340 0x0000000011390cfd 0x000000001374af3d 0x000000001370f3d8 0x00000000136f6662 0x0000000013711738 0x000000001664eba7 0x000000001664f039 0x000000001661b95c 0x0000000016619efd 0x000075674938eac3 0x000075674941fa04
2025.05.30 09:45:53.670833 [ 796 ] {} <Fatal> BaseDaemon: 0. signalHandler(int, siginfo_t*, void*) @ 0x000000000dac20b5
2025.05.30 09:45:53.670848 [ 796 ] {} <Fatal> BaseDaemon: 1. ? @ 0x000075674933c520
2025.05.30 09:45:53.670875 [ 796 ] {} <Fatal> BaseDaemon: 2. _Z11typeid_castIRKN2DB12ColumnStringEKNS0_7IColumnEQsr3stdE14is_reference_vIT_EES6_RT0_ @ 0x0000000008e8a08c
2025.05.30 09:45:53.670929 [ 796 ] {} <Fatal> BaseDaemon: 3. DB::SerializationString::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const @ 0x00000000113fbedf
2025.05.30 09:45:53.670975 [ 796 ] {} <Fatal> BaseDaemon: 4. DB::ISerialization::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0x0000000011386da6
2025.05.30 09:45:53.671010 [ 796 ] {} <Fatal> BaseDaemon: 5. DB::SerializationTuple::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0x0000000011411340
2025.05.30 09:45:53.671049 [ 796 ] {} <Fatal> BaseDaemon: 6. DB::SerializationArray::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0x0000000011390cfd
2025.05.30 09:45:53.671088 [ 796 ] {} <Fatal> BaseDaemon: 7. DB::NativeWriter::write(DB::Block const&) @ 0x000000001374af3d
2025.05.30 09:45:53.671130 [ 796 ] {} <Fatal> BaseDaemon: 8. DB::TCPHandler::sendData(DB::QueryState&, DB::Block const&) @ 0x000000001370f3d8
2025.05.30 09:45:53.671168 [ 796 ] {} <Fatal> BaseDaemon: 9. DB::TCPHandler::runImpl() @ 0x00000000136f6662
2025.05.30 09:45:53.671214 [ 796 ] {} <Fatal> BaseDaemon: 10. DB::TCPHandler::run() @ 0x0000000013711738
2025.05.30 09:45:53.671254 [ 796 ] {} <Fatal> BaseDaemon: 11. Poco::Net::TCPServerConnection::start() @ 0x000000001664eba7
2025.05.30 09:45:53.671286 [ 796 ] {} <Fatal> BaseDaemon: 12. Poco::Net::TCPServerDispatcher::run() @ 0x000000001664f039
2025.05.30 09:45:53.671327 [ 796 ] {} <Fatal> BaseDaemon: 13. Poco::PooledThread::run() @ 0x000000001661b95c
2025.05.30 09:45:53.671375 [ 796 ] {} <Fatal> BaseDaemon: 14. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000016619efd
2025.05.30 09:45:53.671417 [ 796 ] {} <Fatal> BaseDaemon: 15. ? @ 0x000075674938eac3
2025.05.30 09:45:53.671445 [ 796 ] {} <Fatal> BaseDaemon: 16. ? @ 0x000075674941fa04
2025.05.30 09:45:53.764564 [ 796 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 4A22C7E2D6319D515E214E96A5B0E99B)
2025.05.30 09:45:53.764750 [ 796 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PedroTadim**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...
Don't allow adaptive_write_buffer_initial_size set to 0

### Documentation entry for user-facing changes

Add test for https://github.com/ClickHouse/ClickHouse/issues/81045. It's fixed on the current master.

Closes https://github.com/ClickHouse/ClickHouse/issues/81045
Closes https://github.com/ClickHouse/ClickHouse/issues/90696

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03742_test_flattened_crash.sql [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    '`id` UInt64,
+    `tenant` String,
+    `arr.id` Array(Nullable(UInt64)),
+    `arr.name` Array(Nullable(String)),
+    `arr.nested` Array(Tuple(a String, b Float64))', 1, 10
+) LIMIT 1000000;
+SELECT arr.nested FROM test_flatten_nested_crash ORDER BY arr.nested LIMIT 10000;
+ALTER TABLE test_flatten_nested_crash DROP COLUMN `arr.nested`;
+ALTER TABLE test_flatten_nested_crash ADD COLUMN `arr.nested` Array(Tuple(a String, b Float64));
+SELECT arr.nested FROM test_flatten_nested_crash ORDER BY arr.nested LIMIT 10000;
```
Comment (GrigoryPervakov) [inline tests/queries/0_stateless/03742_test_flattened_crash.sql]: Do we need the first SELECT to test the crash?
It reproduces the issue with `LIMIT 1` too https://fiddle.clickhouse.com/338f6902-431e-4f91-9b10-2370ccf9bb48
It feels a bit too much to commit 20k lines of random output 😄

**Review by GrigoryPervakov — APPROVED** [review]
