### PR TITLE
Revert "Revert "Revert "Revert "make d-tor Finalizer more obvious""""

### LINKED ISSUE #73015: materialized_views_ignore_errors does the wrong thing
Repro:
https://github.com/ClickHouse/ClickHouse/pull/66441

The errors in that PR have the same root cause https://github.com/ClickHouse/ClickHouse/pull/72898

Unexpected behaviour:
When error happen on the source table it is muted as nothing happened. `Ok` is returned to the client.

Should be:
Errors in the source table have to fail the query.

### PR DESCRIPTION
**Pull request by CheSema**
Reverts ClickHouse/ClickHouse#72882
It just 3 attempt. The first is https://github.com/ClickHouse/ClickHouse/pull/72395

Fixes https://github.com/ClickHouse/ClickHouse/issues/73015

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 689a1544380682ffe82960c8aa5c9ee097a88fc8 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72898/689a1544380682ffe82960c8aa5c9ee097a88fc8/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/0f6c9b6a59772b47c08ddf5a8faa3329e06330db/docs_check.html">✅ success</a></td></tr>
<tr><td>Fast test</td><td>Normally this is the first check that is ran for a PR. It builds ClickHouse and runs most of <a href="https://clickhouse.com/docs/en/development/tests#functional-tests">stateless functional tests</a>, omitting some. If it fails, further checks are not started until it is fixed. Look at the report to see which tests fail, then reproduce the failure locally as described <a href="https://clickhouse.com/docs/en/development/tests#functional-test-locally">here</a></td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/fast_test.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4721890f63b619890a21c13a47415a1482a4b0fe/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Processors/Transforms/buildPushingToViewsChain.cpp [hunk 1]
```diff
@@ -223,6 +225,7 @@ class FinalizingViewsTransform final : public IProcessor
 /// Generates one chain part for every view in buildPushingToViewsChain
 std::optional<Chain> generateViewChain(
     ContextPtr context,
+    size_t view_level,
```
Comment (Michicosun) [inline src/Processors/Transforms/buildPushingToViewsChain.cpp:228]: Now the chain for a materialized view will be generated with view_level = 0 in any case, because `InterpreterInsertQuery` is used to generate the chain. 

Which means that for materialized views, this setting will be ignored. We probably need to include the level in the interpreter as well....

**Review by Michicosun — CHANGES_REQUESTED** [review]

**Review by Michicosun — APPROVED** [review]
LGTM

`test_storage_s3_queue/test.py::test_alter_settings` - seems to be flaky in master.
`Stress test (msan)` - looks like https://github.com/ClickHouse/ClickHouse/issues/72557
