### PR TITLE
Fix crash in add attribute

### LINKED ISSUE #87516: Potential crash in OpenTelemetry::Span::addAttribute()
### Company or project name

_No response_

### Describe what's wrong

It's possible to get Fatal error in `src/Common/OpenTelemetryTraceContext.cpp:31: DB::OpenTelemetry::Span::addAttribute` called from `DB::OpenTelemetry::TracingContextHolder::~TracingContextHolder()`.

The trouble is in `noexcept` without try-catch inside:
```
bool Span::addAttribute(std::string_view name, UInt64 value) noexcept
{
    if (!this->isTraceEnabled() || name.empty())             // <-- THROWS HERE (according to trace line)
        return false;

    return addAttributeImpl(name, toString(value));
}
```

### Does it reproduce on the most recent release?

No

### How to reproduce

Trigger exceptions in `new()` in test cases.

### Expected behavior

_No response_

### Error message and/or stacktrace

```
2025.09.23 13:08:34.153858 [ 14588 ] {} <Fatal> BaseDaemon: 1. ./build/./src/Common/SignalHandlers.cpp:106: signalHandler(int, siginfo_t*, void*) @ 0x000000000cef9a6d
2025.09.23 13:08:34.153858 [ 14587 ] {} <Fatal> BaseDaemon: 1. ./build/./src/Common/SignalHandlers.cpp:106: signalHandler(int, siginfo_t*, void*) @ 0x000000000cef9a6d
2025.09.23 13:08:34.162733 [ 14588 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007f91090b4520
2025.09.23 13:08:34.162738 [ 14587 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007f91090b4520
2025.09.23 13:08:34.162745 [ 14588 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007f91091089fd
2025.09.23 13:08:34.162750 [ 14587 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007f91091089fd
2025.09.23 13:08:34.162757 [ 14588 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f91090b4476
2025.09.23 13:08:34.162792 [ 14587 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f91090b4476
2025.09.23 13:08:34.162796 [ 14588 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f910909a7f3
2025.09.23 13:08:34.162815 [ 14587 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f910909a7f3
2025.09.23 13:08:34.170089 [ 14587 ] {} <Fatal> BaseDaemon: 6. ./build/./contrib/llvm-project/libcxxabi/src/abort_message.cpp:78: ? @ 0x000000001848b666
2025.09.23 13:08:34.170089 [ 14588 ] {} <Fatal> BaseDaemon: 6. ./build/./contrib/llvm-project/libcxxabi/src/abort_message.cpp:78: ? @ 0x000000001848b666
2025.09.23 13:08:34.194974 [ 14587 ] {} <Fatal> BaseDaemon: 7. ./build/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:67: std::__terminate(void (*)()) @ 0x00000000184a5727
2025.09.23 13:08:34.194974 [ 14588 ] {} <Fatal> BaseDaemon: 7. ./build/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:67: std::__terminate(void (*)()) @ 0x00000000184a5727
2025.09.23 13:08:34.197052 [ 14587 ] {} <Fatal> BaseDaemon: 8. ./build/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:88: std::terminate() @ 0x00000000184a5698
2025.09.23 13:08:34.197108 [ 14588 ] {} <Fatal> BaseDaemon: 8. ./build/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:88: std::terminate() @ 0x00000000184a5698
2025.09.23 13:08:43.449083 [ 14587 ] {} <Fatal> BaseDaemon: 9. ? @ 0x00000000074e43db
2025.09.23 13:08:43.449083 [ 14588 ] {} <Fatal> BaseDaemon: 9. ? @ 0x00000000074e43db
2025.09.23 13:08:43.524011 [ 14588 ] {} <Fatal> BaseDaemon: 10.0. inlined from ./build/./src/Common/OpenTelemetryTraceContext.cpp:31: DB::OpenTelemetry::Span::addAttribute(std::basic_string_view<char, std::char_traits<char>>, unsigned long)
2025.09.23 13:08:43.524011 [ 14587 ] {} <Fatal> BaseDaemon: 10.0. inlined from ./build/./src/Common/OpenTelemetryTraceContext.cpp:31: DB::OpenTelemetry::Span::addAttribute(std::basic_string_view<char, std::char_traits<char>>, unsigned long)
2025.09.23 13:08:43.524058 [ 14588 ] {} <Fatal> BaseDaemon: 10. ./build/./src/Common/OpenTelemetryTraceContext.cpp:393: DB::OpenTelemetry::TracingContextHolder::~TracingContextHolder() @ 0x000000000ccb0687
2025.09.23 13:08:43.524078 [ 14587 ] {} <Fatal> BaseDaemon: 10. ./build/./src/Common/OpenTelemetryTraceContext.cpp:393: DB::OpenTelemetry::TracingContextHolder::~TracingContextHolder() @ 0x000000000ccb0687
2025.09.23 13:08:43.539396 [ 14587 ] {} <Fatal> BaseDaemon: 11. ./build/./src/Common/ThreadPool.cpp:852: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000cca649e
2025.09.23 13:08:43.547307 [ 14588 ] {} <Fatal> BaseDaemon: 11. ./build/./src/Common/ThreadPool.cpp:852: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000cca649e
2025.09.23 13:08:43.554580 [ 14587 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.09.23 13:08:43.554631 [ 14587 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:ne190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.09.23 13:08:43.554640 [ 14587 ] {} <Fatal> BaseDaemon: 12. ./contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000ccab83b
2025.09.23 13:08:43.554691 [ 14587 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007f9109106ac3
2025.09.23 13:08:43.554697 [ 14587 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f91091988c0
2025.09.23 13:08:43.554744 [ 14587 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2025.09.23 13:08:43.572110 [ 14588 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.09.23 13:08:43.572171 [ 14588 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:ne190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.09.23 13:08:43.572186 [ 14588 ] {} <Fatal> BaseDaemon: 12. ./contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000ccab83b
2025.09.23 13:08:43.572211 [ 14588 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007f9109106ac3
2025.09.23 13:08:43.572219 [ 14588 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f91091988c0
2025.09.23 13:08:43.572229 [ 14588 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2025.09.23 13:08:43.724127 [ 14587 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2025.09.23 13:08:43.724490 [ 14588 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
```

### Additional context

It's not official build that triggers some crashes more frequently

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Details

Fixes https://github.com/ClickHouse/ClickHouse/issues/87516

### CODE REVIEW

File: src/Common/OpenTelemetryTraceContext.h [hunk 1]
```diff
@@ -71,7 +72,22 @@ struct Span
...
-    bool addAttributeImpl(std::string_view name, std::string_view value) noexcept;
+    template <class T>
+    bool addAttributeImpl(std::string_view name, T value) noexcept
+    {
+        try
+        {
+            if constexpr (std::is_same_v<T, std::string_view> || std::is_same_v<T, String> || std::is_same_v<T, const char *>)
+                this->attributes.push_back(Tuple{name, std::move(value)});
+            else
+                this->attributes.push_back(Tuple{name, toString(value)});
```
Comment (Avogar) [inline src/Common/OpenTelemetryTraceContext.h:83]: Can you explain how old code led to crash? As we create a new `String` object inside `Field` here (inside `Tuple`), it should be ok to pass temporary `String` object to `addAttributeImpl` even if it has `std::string_view` argument type. Or it's not?

Comment (serxa) [reply src/Common/OpenTelemetryTraceContext.h:83]: This is now in try-block, previously, if toString() allocated memory, and this led to an exception thrown in noexcept functions

**Review by Avogar — APPROVED** [review]
