### PR TITLE
PR: avoid waiting for unused replicas if reading is scheduled completely

### LINKED ISSUE #61663: Query with parallel replicas fails if replica is unresponsive during handshake
**Describe the unexpected behaviour**
Query with parallel replicas fails by timeout if replica is not responsive during handshake

**Expected behavior**
Query should succeed

**Error message and/or stacktrace**
Example:
https://pastila.nl/?000fdfdd/3f8bc0bc93edea5f65d0a42bece1e619#Irbksv017YDbVdf6MiDn3A==

### PR DESCRIPTION
**Pull request by devcrafter**
Closes https://github.com/ClickHouse/ClickHouse/issues/61663

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Parallel replicas: avoid waiting for slow unused replicas if all read tasks have been assigned to other replicas 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 1]
```diff
@@ -907,14 +909,34 @@ Pipes ReadFromParallelRemoteReplicasStep::addPipes(ASTPtr ast, const Header & ou
...
+            replica_info.number_of_current_replica,
+            pools_to_use[i]->getAddress());
+
+        Pipe pipe = createPipeForSingeReplica(pools_to_use[i], ast, replica_info, out_header);
+        remote_sources.emplace(replica_info.number_of_current_replica, pipe.getProcessors().front());
+        pipes.emplace_back(std::move(pipe));
     }
 
+    coordinator->setReadCompletedCallback(
+        [sources = std::move(remote_sources)](std::set<size_t> used_replicas)
```
Comment (davenger) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:924]:
```suggestion
        [sources = std::move(remote_sources)](const std::set<size_t> & used_replicas)
```

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 2]
```diff
@@ -1087,17 +1116,60 @@ ParallelReadResponse ParallelReplicasReadingCoordinator::handleRequest(ParallelR
...
+        if (!response.finish)
+        {
+            chassert(!is_reading_completed);
+
+            if (replicas_used.insert(replica_num).second)
+                ProfileEvents::increment(ProfileEvents::ParallelReplicasUsedCount);
+        }
+        else
+        {
+            if (isReadingCompleted())
```
Comment (nickitat) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:1146]: maybe makes sense to check if `is_reading_completed` is already `true` to avoid calling `isReadingCompleted()`.

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 3]
```diff
@@ -1087,17 +1116,60 @@ ParallelReadResponse ParallelReplicasReadingCoordinator::handleRequest(ParallelR
...
+            {
+                reading_assignment_has_been_completed = !is_reading_completed.exchange(true);
+                replicas_to_exclude = replicas_used;
+                // exclude itself from canceling
+                replicas_to_exclude.insert(replica_num);
```
Comment (nickitat) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp]: i'm not quite getting this logic. could you elaborate it a bit pls? and do we really need to create a local `replicas_to_exclude` that has almost the same content as `replicas_used` per se?

File: tests/queries/0_stateless/02233_set_enable_with_statement_cte_perf.sql [hunk 4]
```diff
@@ -1,3 +1,6 @@
+-- Tags: no-parallel-replicas
+-- no-parallel-replicas: for 3d query, read_rows in query_log sometimes differs for some reason, check later
```
Comment (devcrafter) [inline tests/queries/0_stateless/02233_set_enable_with_statement_cte_perf.sql]: change comment

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp (hunk 2 above)
Comment (devcrafter) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:1146]: It's done on line 1122

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp (hunk 3 above)
Comment (devcrafter) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp]: This is necessary due to suboptimal pr protocol if replica is taking last reading task.
The current protocol requires additional round-trip to finish reading for a replica, i.e., (1) packet with ranges to read and finish = false and (2) empty packet with finish=true.
So, there is a case when replica N will ask for their first task, but all tasks have already been assigned. It means that replicas N will not be in `replicas_used` set, but it shouldn't be included in replicas for cancelling.

Comment (devcrafter) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp]: Added a comment

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 5]
```diff
@@ -846,6 +853,25 @@ ParallelReadResponse DefaultCoordinator::handleRequest(ParallelReadRequest reque
     return response;
 }
 
+bool DefaultCoordinator::isReadingCompleted() const
```
Comment (nickitat) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:856]: what about the case, when we finish the query without reading all the available granules? e.g. `select * from t limit 10`.

Comment (devcrafter) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:856]: Replicas which was able to some tasks will be not be cancelled with new mechanism. They will finish their execution due to enough data processed and send cancel packet. So, looks cancelling in logs for query `select * from t limit` for a test I've added to simulate this case, see `03532_pr_unused_query_cancelling_with_limit.sql`
```
2025.06.06 19:02:27.049280 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 0 assigned to address 127.0.0.2:9000                                                                                                                                
2025.06.06 19:02:27.049294 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 1 assigned to address 127.0.0.3:9000                                                                                                                                
2025.06.06 19:02:27.049300 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 2 assigned to address 127.0.0.4:9000                                                                                                                                
2025.06.06 19:02:27.049305 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 3 assigned to address 127.0.0.5:9000                                                                                                                                
2025.06.06 19:02:27.049311 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 4 assigned to address 127.0.0.6:9000                                                                                                                                
2025.06.06 19:02:27.049317 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 5 assigned to address 127.0.0.7:9000                                                                                                                                
2025.06.06 19:02:27.049322 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 6 assigned to address 127.0.0.8:9000                                                                                                                                
2025.06.06 19:02:27.049328 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 7 assigned to address 127.0.0.1:9000                                                                                                                                
2025.06.06 19:02:27.049333 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 8 assigned to address 127.0.0.9:9000                                                                                                                                
2025.06.06 19:02:27.049339 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 9 assigned to address 127.0.0.10:9000                                                                                                                               
2025.06.06 19:02:27.049345 [ 218352 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ReadFromParallelRemoteReplicasStep: Replica number 10 assigned to address 127.0.0.11:1234                                                                                                                              
...
2025.06.06 19:02:27.057512 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ParallelReplicasReadingCoordinator: Using snapshot from replica num 0
2025.06.06 19:02:27.057520 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Initial request: replica 0, mode Default, 1 parts: [part all_1_1_0 with ranges [(0, 1)]]
2025.06.06 19:02:27.057533 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Reading state is fully initialized: part all_1_1_0 with ranges [(0, 1)] in replicas [0], mark_segment_size: 128
2025.06.06 19:02:27.057540 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Received initial requests: 1 Replicas count: 11
2025.06.06 19:02:27.057544 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Total rows to read: 1000
2025.06.06 19:02:27.057572 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Handling request from replica 0, minimal marks size is 9, request count 1
2025.06.06 19:02:27.057592 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Going to respond to replica 0 with 1 parts: [part all_1_1_0 with ranges [(0, 1)]]. Finish: false; mine_marks=0, stolen_by_hash=0, stolen_rest=1
2025.06.06 19:02:27.057617 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Initial request: replica 1, mode Default, 1 parts: [part all_1_1_0 with ranges [(0, 1)]]
2025.06.06 19:02:27.057622 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Received initial requests: 2 Replicas count: 11
2025.06.06 19:02:27.057634 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Handling request from replica 1, minimal marks size is 9, request count 1
2025.06.06 19:02:27.057639 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> DefaultCoordinator: Going to respond to replica 1 with 0 parts: []. Finish: true; mine_marks=0, stolen_by_hash=0, stolen_rest=0
2025.06.06 19:02:27.057645 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Debug> ParallelReplicasReadingCoordinator: All ranges for reading has been assigned to replicas. Cancelling execution for unused replicas. Used replicas: 0, 1
...
2025.06.06 19:02:27.057942 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.10:9000) Cancelling query
2025.06.06 19:02:27.057972 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.9:9000) Cancelling query
2025.06.06 19:02:27.057999 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.1:9000) Cancelling query
2025.06.06 19:02:27.058032 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.8:9000) Cancelling query
2025.06.06 19:02:27.058060 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.7:9000) Cancelling query
2025.06.06 19:02:27.058081 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.6:9000) Cancelling query
2025.06.06 19:02:27.058106 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.5:9000) Cancelling query
2025.06.06 19:02:27.058137 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.4:9000) Cancelling query
...
2025.06.06 19:02:27.058227 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.3:9000) Cancelling query because enough data has been read
2025.06.06 19:02:27.058337 [ 219104 ] {a253fb49-1e27-4609-83a4-82779c6c0332} <Trace> ReadFromParallelRemoteReplicasStep: (127.0.0.2:9000) Cancelling query because enough data has been read
```

Comment (devcrafter) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:856]: Just FYI, cancelling for replica 1 can be excessive since it didn't read anything and send empty block. And, AFAIU, since we haven't got EndOfStream yet, we send Cancel packet - which looks controversial but not related to the change.

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 6]
```diff
@@ -1147,7 +1147,11 @@ ParallelReadResponse ParallelReplicasReadingCoordinator::handleRequest(ParallelR
             {
                 reading_assignment_has_been_completed = !is_reading_completed.exchange(true);
                 replicas_to_exclude = replicas_used;
-                // exclude itself from canceling
+                // Exclude itself from canceling. Reason:
+                // the current protocol requires additional round-trip to finish reading for a replica,
+                // i.e., (1) packet with ranges to read and finish = false and (2) empty packet with finish=true.
+                // So, when replica N will ask for their first task, but all tasks have already been assigned,
+                // the replica N will not be in replicas_used set, but it should excluded from cancelling.
```
Comment (nickitat) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp]:
```suggestion
                // the replica N will not be in replicas_used set, but it should be excluded from cancellation.
```

**Review by nickitat — APPROVED** [review]
