### PR TITLE
Speed up Decimal comparison

### LINKED ISSUE #28192: DateTime64 (Decimal64) comparsion much slower than UInt64 or DateTime
**Describe the situation**
Equality, non-equality conditions over DateTime64 column.
Not sure about how decimal values being stored on disk / in memory, but when we do compare column and literal, we can convert literal value to the same precise as decimal column and just compare bit's like in UInt64, so decimal datatype shouldn't have any impact for performance.

**How to reproduce**
Clickhouse version 21.8

```
SELECT count()
FROM numbers_mt(10000000000)
WHERE materialize(toDateTime64(1000000, 3)) = toDateTime64(1000000, 3)

┌─────count()─┐
│ 10000000000 │
└─────────────┘

1 rows in set. Elapsed: 1.679 sec. Processed 10.00 billion rows, 80.00 GB (5.95 billion rows/s., 47.64 GB/s.)

SELECT count()
FROM numbers_mt(10000000000)
WHERE materialize(toDecimal64(toDateTime64(1000000, 3), 3)) = toDecimal64(toDateTime64(1000000, 3), 3)

Query id: 98b50c04-9067-4d6c-9ae2-346f9a64d8d6

┌─────count()─┐
│ 10000000000 │
└─────────────┘

1 rows in set. Elapsed: 1.812 sec. Processed 10.00 billion rows, 80.00 GB (5.52 billion rows/s., 44.16 GB/s.)


SELECT count()
FROM numbers_mt(10000000000)
WHERE materialize(toUInt64(toDateTime64(1000000, 3))) = toUInt64(toDateTime64(1000000, 3))

┌─────count()─┐
│ 10000000000 │
└─────────────┘

1 rows in set. Elapsed: 0.975 sec. Processed 10.00 billion rows, 80.00 GB (10.26 billion rows/s., 82.06 GB/s.)


SELECT count()
FROM numbers_mt(10000000000)
WHERE materialize(toDateTime(1000000)) = toDateTime(1000000)

┌─────count()─┐
│ 10000000000 │
└─────────────┘

1 rows in set. Elapsed: 0.508 sec. Processed 10.00 billion rows, 80.00 GB (19.70 billion rows/s., 157.57 GB/s.)
```

**Expected performance**
DateTime64 compare with literal would have at least half of DateTime performance or the same as UInt64.

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Improved performance of Decimal comparison operations. Resolves https://github.com/ClickHouse/ClickHouse/issues/28192.

https://pastila.nl/?0202858e/0ff4fbde7e3d8d0d80b158a82ce6d93f#G4y8HbLIRvg3Y23lCHpYMQ==

### CODE REVIEW

File: src/Columns/ColumnDecimal.cpp [hunk 1]
```diff
@@ -1,3 +1,4 @@
+#include <algorithm>
```
Comment (thevar1able) [inline src/Columns/ColumnDecimal.cpp]: Includes should be reordered.

**Comment by thevar1able** [comment]
>[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90153&sha=7843c9a8ebc5067ab8a48d64f9419edc15fb4adb&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)

https://github.com/ClickHouse/ClickHouse/issues/89924

**Comment by thevar1able** [comment]
`x86_64`
image

`aarch64`
image

There are also 10-20% improvements across tests that touch Decimals.

File: src/Columns/ColumnDecimal.cpp [hunk 2]
```diff
@@ -471,15 +473,19 @@ ColumnPtr ColumnDecimal<T>::replicate(const IColumn::Offsets & offsets) const
 
     typename Self::Container & res_data = res->getData();
     res_data.reserve_exact(offsets.back());
+    res_data.resize(offsets.back());
+
+    const T *src = data.data();
+    T *dst = res_data.data();
```
Comment (alexey-milovidov) [inline src/Columns/ColumnDecimal.cpp]:
```suggestion
    const T * src = data.data();
    T * dst = res_data.data();
```

**Review by alexey-milovidov — APPROVED** [review]

File: src/Columns/ColumnDecimal.cpp [hunk 3]
```diff
@@ -471,15 +473,19 @@ ColumnPtr ColumnDecimal<T>::replicate(const IColumn::Offsets & offsets) const
 
     typename Self::Container & res_data = res->getData();
     res_data.reserve_exact(offsets.back());
+    res_data.resize(offsets.back());
```
Comment (nihalzp) [inline src/Columns/ColumnDecimal.cpp]: I think we can combine both of them via single method call `resize_exact`.

```cpp
    template <typename ... TAllocatorParams>
    void resize_exact(size_t n, TAllocatorParams &&... allocator_params) /// NOLINT
    {
        reserve_exact(n, std::forward<TAllocatorParams>(allocator_params)...);
        resize_assume_reserved(n);
    }
```

**Review by nihalzp — APPROVED** [review]

**Comment by thevar1able** [comment]
I have a feeling `resize_exact()` causes up to 30% regression in `rand` tests for `aarch64`; the regression is not there for commits before https://github.com/ClickHouse/ClickHouse/pull/90153/commits/0a15a518cac9357056cfd7f4f15384b4b1b0b2f3.

I'm going to validate on `aarch64` host and revert if confirmed.

**Comment by thevar1able** [comment]
https://pastila.nl/?0021c946/bc466bdfadcf4ea6ddc514c9edf54e81#htvFG+627rkgg47wfVm1Dw==
https://pastila.nl/?0011f067/af1d55ea69b5cdb798143771567a22de#XCaWeAY/1bPxLn553xC9uA==

I see no meaningful performance degradation here.
