### PR TITLE
Better exception messages in input formats

### LINKED ISSUE #57024: Parallel parsing prevents the diagnostic info about the file name with parse errors
https://pastila.nl/?00d9fbeb/f39311c89f2014ccb831d971b6094ccf#k2MyBBHoFWMbMEguYden2Q==

https://www.backblaze.com/cloud-storage/resources/hard-drive-test-data

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/57024

### CODE REVIEW

File: src/Common/Exception.h [hunk 1]
```diff
@@ -194,43 +194,6 @@ class ErrnoException : public Exception
     const char * className() const noexcept override { return "DB::ErrnoException"; }
 };
 
-
-/// Special class of exceptions, used mostly in ParallelParsingInputFormat for
-/// more convenient calculation of problem line number.
-class ParsingException : public Exception
```
Comment (Avogar) [inline src/Common/Exception.h:200]: It was used only in IRowInputFormat and ParallelParsingInputFormat for adding actual line number to the exception message. Now we don't need separate excpetion class for it

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 7e392eec50cc8f576ad1890cdcf59d5c1e0594e6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57053/7e392eec50cc8f576ad1890cdcf59d5c1e0594e6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6944340136">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57053/7e392eec50cc8f576ad1890cdcf59d5c1e0594e6/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
Need to fix the tests

File: src/Processors/Formats/IRowInputFormat.cpp [hunk 2]
```diff
@@ -148,6 +142,8 @@ Chunk IRowInputFormat::generate()
                     }
                 }
 
+                ++total_rows;
```
Comment (Avogar) [inline src/Processors/Formats/IRowInputFormat.cpp:145]: Moved afrer calling `readRow` so it will be 0 in the first `readRow` call, it's more convinient than 1

**Review by antonio2368 — APPROVED** [review]
