### PR TITLE
Query Cache: Consider identical queries against different databases as different

### LINKED ISSUE #64136: Query cache is not isolated across different databases
Tested on 24.3.2.23 (official build).

**Describe the unexpected behaviour**
Query cache is used for the same tables created in different databases when no database alias is used.

**How to reproduce**

Prepare debug environment and data:

```
CREATE DATABASE test ENGINE = Atomic;

CREATE TABLE default.test
(
    `a` UInt64,
    `b` UUID,
    `c` UInt32 DEFAULT xxHash32(b),
    `d` DateTime,
    `error_count` UInt8,
    INDEX idx_error error_count TYPE minmax GRANULARITY 1
)
ENGINE = ReplacingMergeTree(d)
PARTITION BY toYYYYMM(d)
ORDER BY (a, c)
TTL d + toIntervalMonth(1)
SETTINGS index_granularity = 6, ttl_only_drop_parts = 1;

CREATE TABLE test.test AS default.test;

INSERT INTO test.test SELECT number, generateUUIDv4(), number, '2024-05-20 14:00:00'::DateTime, 2 FROM numbers(10e7);

ALTER TABLE default.test ATTACH PARTITION '202405' FROM test.test;
```

Now test query cache:

```
USE default;

SELECT a % 100 ids, max(b) uuids, sum(error_count) ec FROM test GROUP BY ids ORDER BY ids SETTINGS use_query_cache=1;

100 rows in set. Elapsed: 11.742 sec. Processed 75.49 million rows, 1.89 GB (6.43 million rows/s., 160.73 MB/s.)

SELECT * FROM system.query_cache;
      ┌─query───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─result_size─┬─stale─┬─shared─┬─compressed─┬──────────expires_at─┬────────────key_hash─┐
1. │ SELECT a % 100 AS ids, max(b) AS uuids, sum(error_count) AS ec FROM test GROUP BY ids ORDER BY ids ASC SETTINGS use_query_cache = 1 │        3328 │     0 │      0 │          1 │ 2024-05-20 14:09:44 │ 5831134195536845086 │
   └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴───────┴────────┴────────────┴─────────────────────┴─────────────────────┘

USE test;

SELECT a % 100 ids, max(b) uuids, sum(error_count) ec FROM test GROUP BY ids ORDER BY ids SETTINGS use_query_cache=1;

100 rows in set. Elapsed: 0.001 sec.

SELECT * FROM system.query_cache;
   
┌─query───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─result_size─┬─stale─┬─shared─┬─compressed─┬──────────expires_at─┬────────────key_hash─┐
1. │ SELECT a % 100 AS ids, max(b) AS uuids, sum(error_count) AS ec FROM test GROUP BY ids ORDER BY ids ASC SETTINGS use_query_cache = 1 │        3328 │     0 │      0 │          1 │ 2024-05-20 14:09:44 │ 5831134195536845086 │
   └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴───────┴────────┴────────────┴─────────────────────┴─────────────────────┘

```

**Expected behavior**
I expect the query cache to be aware that I'm selecting the data from another table (same table name in another database).

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes #64136

Consider:

```sql
CREATE DATABASE db1;
CREATE DATABASE db2;

CREATE TABLE db1.tab(a UInt64, PRIMARY KEY a);
CREATE TABLE db2.tab(a UInt64, PRIMARY KEY a);

INSERT INTO db1.tab values(1);
INSERT INTO db2.tab values(2);

USE db1;
SELECT * FROM tab SETTINGS use_query_cache=1;

USE db2;
SELECT * FROM tab SETTINGS use_query_cache=1; -- should return 2 but returns 1
```

To disambiguate identical queries against different databases (e.g. `db1`, `db2`), we now incorporate the current database name into the AST hash which is used as the key in the query cache.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The query cache now considers two identical queries against different databases as different. The previous behavior could be used to bypass missing privileges to read from a table.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

File: src/Interpreters/Cache/QueryCache.cpp [hunk 1]
```diff
@@ -186,17 +202,15 @@ String queryStringFromAST(ASTPtr ast)
 
 }
 
-/// Hashing of ASTs must consider aliases (issue #56258)
-static constexpr bool ignore_aliases = false;
-
 QueryCache::Key::Key(
     ASTPtr ast_,
+    String current_database,
```
Comment (Algunenano) [inline src/Interpreters/Cache/QueryCache.cpp:207]: Should we also hash the settings used? The results and header might change depending on the settings used (in the query, the session, etc).

Comment (rschu1ze) [reply src/Interpreters/Cache/QueryCache.cpp:207]: Yes, that's a good idea.

But, allow me to do that separately as a follow-up. I want to downport the current PR as it fixes a security issue. Unhashed settings "only" pose a correctness issue.

File: src/Interpreters/Cache/QueryCache.cpp [hunk 2]
```diff
@@ -177,6 +177,22 @@ ASTPtr removeQueryCacheSettings(ASTPtr ast)
...
+    ast = removeQueryCacheSettings(ast);
+
+    /// Hash the AST, it must consider aliases (issue #56258)
+    constexpr bool ignore_aliases = false;
+    IAST::Hash ast_hash = ast->getTreeHash(ignore_aliases);
+
+    /// Also hash the database specified via SQL `USE db`, otherwise identifiers in same query (AST) may mean different columns in different tables (issue #64136)
+    IAST::Hash cur_database_hash = CityHash_v1_0_2::CityHash128(current_database.data(), current_database.size());
+    UInt64 low_combined = ast_hash.low64 ^ cur_database_hash.low64;
+    UInt64 high_combined = ast_hash.high64 ^ cur_database_hash.high64;
```
[the remark this answers is not in the document]
Comment (rschu1ze) [reply src/Interpreters/Cache/QueryCache.cpp:191]: Yeah, that's more elegant ;-)

**Review by kssenii — APPROVED** [review]

File: src/Interpreters/Cache/QueryCache.cpp (hunk 1 above)
Comment (rschu1ze) [reply src/Interpreters/Cache/QueryCache.cpp]: https://github.com/ClickHouse/ClickHouse/pull/64205

File: tests/queries/0_stateless/02494_query_cache_use_database.sql [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+CREATE TABLE db2.tab(a UInt64, PRIMARY KEY a);
+
+INSERT INTO db1.tab values(1);
+INSERT INTO db2.tab values(2);
+
+USE db1;
+SELECT * FROM tab SETTINGS use_query_cache=1;
+
+USE db2;
+SELECT * FROM tab SETTINGS use_query_cache=1;
```
Comment (saimarpaka) [inline tests/queries/0_stateless/02494_query_cache_use_database.sql:25]: would this work for cases where the database is set via the connection string ? snippet from java client
```
ClickHouseNode.builder()
			.host(host)
			.port(ClickHouseProtocol.HTTP, port)
			.options(Map.of(ClickHouseClientOption.SSL.getKey(), "true"))
			.database(db) <-- this
			.credentials(credentials)
			.build();
```

Comment (rschu1ze) [reply tests/queries/0_stateless/02494_query_cache_use_database.sql:25]: I don't have Java locally set up, but I would assume it would work.

It would be cool if you could check what

```sql
SELECT currentDatabase();
```

returns after running your snippet.

Comment (den-crane) [reply tests/queries/0_stateless/02494_query_cache_use_database.sql:25]: java does this HTTP request

```
curl 'localhost:8123/?database=test&query=select+currentDatabase()&use_query_cache=1&query_cache_nondeterministic_function_handling=save'
test

curl 'localhost:8123/?database=default&query=select+currentDatabase()&use_query_cache=1&query_cache_nondeterministic_function_handling=save'
test
```

Comment (saimarpaka) [reply tests/queries/0_stateless/02494_query_cache_use_database.sql:25]: > I don't have Java locally set up, but I would assume it would work.
> 
> It would be cool if you could check what
> 
> ```sql
> SELECT currentDatabase();
> ```
> 
> returns after running your snippet.

yep returns the selected database from the query. lgtm

**Comment by rschu1ze** [comment]
CI makes it pretty much impossible to get the simplest fixes merged. Very frustrating.
