### PR TITLE
Fix aggregate functions optimisation in AggregateFunctionsArithmericOperationsPass

### LINKED ISSUE #43257: Aggregation result is incorrect using new analyzer
Query:
```sql
SELECT round(avg(log(2) * number), 6) AS k FROM numbers(10000000)
GROUP BY (number % 2) * (number % 3), number % 3, number % 2
HAVING avg(log(2) * number) > 3465735.3 ORDER BY k
SETTINGS allow_experimental_analyzer=1, optimize_group_by_function_keys=0;
```
Output:
```
Ok.

0 rows in set. Elapsed: 0.079 sec. Processed 10.01 million rows, 80.06 MB (127.02 million rows/s., 1.02 GB/s.)
```

Query:
```sql
SELECT round(avg(log(2) * number), 6) AS k FROM numbers(10000000)
GROUP BY (number % 2) * (number % 3), number % 3, number % 2
HAVING avg(log(2) * number) > 3465735.3 ORDER BY k
SETTINGS allow_experimental_analyzer=0, optimize_group_by_function_keys=0;
```

Output:
```
┌──────────────k─┐
│   3465735.9028 │
│   3465735.9028 │
│ 3465736.595947 │
└────────────────┘

3 rows in set. Elapsed: 0.085 sec. Processed 10.01 million rows, 80.06 MB (117.56 million rows/s., 940.52 MB/s.)
```

cc @kitaisreal

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Closes #43257.

cc @kitaisreal

### CODE REVIEW

File: src/Analyzer/Passes/AggregateFunctionsArithmericOperationsPass.cpp [hunk 1]
```diff
@@ -132,8 +133,9 @@ class AggregateFunctionsArithmericOperationsVisitor : public InDepthQueryTreeVis
             if (!function_name_if_constant_is_negative.empty() &&
                 right_argument_constant_value_literal < zeroField(right_argument_constant_value_literal))
             {
-                resolveAggregateFunctionNode(*aggregate_function_node, function_name_if_constant_is_negative);
+                lower_function_name = function_name_if_constant_is_negative;
             }
+            resolveAggregateFunctionNode(*aggregate_function_node, inner_function_arguments_nodes[0], function_name_if_constant_is_negative);
 
             auto inner_function = aggregate_function_arguments_nodes[0];
```
Comment (novikd) [inline src/Analyzer/Passes/AggregateFunctionsArithmericOperationsPass.cpp:140]: I'm not sure, but probably this function should be resolved again too because it's argument type may be changed.

**Comment by kitaisreal** [comment]
@novikd need to merge with master, and then fix conflicts.

File: src/Analyzer/Passes/AggregateFunctionsArithmericOperationsPass.cpp (hunk 1 above)
Comment (kitaisreal) [reply src/Analyzer/Passes/AggregateFunctionsArithmericOperationsPass.cpp:141]: I will double check it in https://github.com/ClickHouse/ClickHouse/pull/44013.

**Review by kitaisreal — APPROVED** [review]
