### PR TITLE
Fix joinGet crash with LowCardinality types

### LINKED ISSUE #15214: joinGet crash for LowCardinality string
```
SELECT joinGet('join_test', 'b', toLowCardinality('hellohellohellohell\0hellohell\0hellohellohellohellohellohell\0hellohell\0hellohellohellohellohellohell\0hellohell\0hellohellohellohellohellohell\0hellohell\0hellohello'), 1)
2020.09.24 10:23:59.446092 [ 36297 ] {} <Fatal> BaseDaemon: (version 20.10.1.1, build id: 20CB5097C4D54CF8) (from thread 20215) (query_id: 8a514d47-b48f-45c4-866f-eb0fec698ba1) Received signal Segmentation fault (11)                       
2020.09.24 10:23:59.446251 [ 36297 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.                                                                                                                 
2020.09.24 10:23:59.446405 [ 36297 ] {} <Fatal> BaseDaemon: Stack trace: 0x1171e65c 0x1172ee49 0x117229d7 0x18527323 0x18526ed3 0x18871e72 0x1887a3c6 0x1887548a 0x18872447 0x188596fb 0x1886b0a6 0x1885970d 0x188507cd 0x18853d6e 0x188569a6 0x1859f90b 0x1859c854 0x1859949b 0x1859836c 0x18898f41 0x18897a8d 0x184c2a45 0x184c196f 0x18aa1ebe 0x18aa108a 0x19400656 0x19409168 0x1d0b5a3c                                                                                                  
2020.09.24 10:23:59.452433 [ 36297 ] {} <Fatal> BaseDaemon: 4. /home/alesap/code/cpp/ClickHouse/src/Functions/IFunction.cpp:636: DB::FunctionOverloadResolverAdaptor::getReturnType(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x1171e65c in /home/alesap/code/cpp/BuildCH/programs/clickhouse                                                                                                                              
...
```
Very easy to reproduce.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix instance crash when using joinGet with LowCardinality types. This fixes https://github.com/ClickHouse/ClickHouse/issues/15214 

Detailed description / Documentation draft:

Null.

### CODE REVIEW

File: tests/queries/0_stateless/01400_join_get_with_multi_keys.sql [hunk 1]
```diff
@@ -6,4 +6,6 @@ INSERT INTO test_joinGet VALUES ('ab', '1', 0.1), ('ab', '2', 0.2), ('cd', '3',
 
 SELECT joinGet(test_joinGet, 'c', 'ab', '1');
 
+SELECT joinGet(join_test, 'b', toLowCardinality('hellohellohellohell\0hellohell\0hellohellohellohellohellohell\0hellohell\0hellohellohellohellohellohell\0hellohell\0hellohellohellohellohellohell\0hellohell\0hellohello'), 1); -- { serverError 60 }
```
Comment (alesapin) [inline tests/queries/0_stateless/01400_join_get_with_multi_keys.sql:9]: Maybe add a positive test that it actually works for LowCardinality?

Comment (amosbird) [reply tests/queries/0_stateless/01400_join_get_with_multi_keys.sql]: done

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Test failure not related to changes (fixing in master).
