### PR TITLE
Better exceptions when invalid constraint is used

### LINKED ISSUE #74910: BAD_TYPE_OF_FIELD error on query without decimal values?
### Describe the bug

Run the Fiddle and this strange error happens:
```
DB::Exception: Cannot compare DB::DecimalField<DB::Decimal<long>> with std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>. (BAD_TYPE_OF_FIELD)
(query: SELECT 1 FROM t0 WHERE t0.c0 = t0.c0;)
```

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/51105132-676b-458c-bc14-149af2d60a4c

The last version without error is 24.2: https://fiddle.clickhouse.com/0e16501b-1671-4a83-8be8-bc351cc7a3d1

### Error message and/or stacktrace

Stack trace:
```
<Error> TCPHandler: Code: 169. DB::Exception: Cannot compare std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> with DB::DecimalField<DB::Decimal<long>>. (BAD_TYPE_OF_FIELD), Stack trace (when copying this message, always include the lines below):

0. std::exception::exception[abi:ne180100]() @ 0x000000001973b214
1. base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x000000003a8080a0
2. src/Common/Exception.cpp:105: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002644cf0b
3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000195dacd6
4. bool DB::FieldVisitorAccurateLess::operator()<String, DB::DecimalField<DB::Decimal<long>>>(String const&, DB::DecimalField<DB::Decimal<long>> const&) const @ 0x000000001c159fd5
5. auto DB::Field::dispatch<auto DB::applyVisitor<DB::FieldVisitorAccurateLess, DB::Field const&, DB::Field const&>(DB::FieldVisitorAccurateLess&&, DB::Field const&, DB::Field const&)::'lambda'(DB::FieldVisitorAccurateLess&), DB::Field const&>(DB::FieldVisitorAccurateLess&&, DB::Field const&) @ 0x00000000203ad912
6. src/Common/FieldVisitors.h:31: DB::ComparisonGraph<std::shared_ptr<DB::IQueryTreeNode>>::buildGraphFromNodesGraph(DB::ComparisonGraph<std::shared_ptr<DB::IQueryTreeNode>>::Graph const&) @ 0x00000000328380a4
7. src/Interpreters/ComparisonGraph.cpp:268: DB::ComparisonGraph<std::shared_ptr<DB::IQueryTreeNode>>::ComparisonGraph(std::vector<std::shared_ptr<DB::IQueryTreeNode>, std::allocator<std::shared_ptr<DB::IQueryTreeNode>>> const&, std::shared_ptr<DB::Context const>) @ 0x00000000328357fb
8. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:597: DB::ConstraintsDescription::getQueryTreeData(std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IQueryTreeNode> const&) const @ 0x000000003535ab17
9. src/Analyzer/Passes/ConvertQueryToCNFPass.cpp:668: DB::(anonymous namespace)::ConvertQueryToCNFVisitor::enterImpl(std::shared_ptr<DB::IQueryTreeNode>&)::'lambda'(std::shared_ptr<DB::IQueryTreeNode>&)::operator()(std::shared_ptr<DB::IQueryTreeNode>&) const @ 0x000000003281b88d
10. src/Analyzer/Passes/ConvertQueryToCNFPass.cpp:737: DB::InDepthQueryTreeVisitorWithContext<DB::(anonymous namespace)::ConvertQueryToCNFVisitor>::visit(std::shared_ptr<DB::IQueryTreeNode>&) @ 0x0000000032819383
11. src/Analyzer/Passes/ConvertQueryToCNFPass.cpp:755: DB::ConvertLogicalExpressionToCNFPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x0000000032818e0d
12. src/Analyzer/QueryTreePassManager.cpp:184: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x00000000327f4439
13. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:149: DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x0000000032d9d9d0
14. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:167: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000032d9b457
15. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:597: std::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::make_unique[abi:ne180100]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x0000000032da058e
16. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:292: std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__function::__policy_invoker<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl[abi:ne180100]<std::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) @ 0x0000000032d9ff05
17. contrib/llvm-project/libcxx/include/__functional/function.h:714: ? @ 0x0000000032ce830f
18. src/Interpreters/executeQuery.cpp:1390: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000332affd1
19. src/Interpreters/executeQuery.cpp:1620: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000332aac4e
20. src/Server/TCPHandler.cpp:658: DB::TCPHandler::runImpl() @ 0x00000000366a36fc
21. src/Server/TCPHandler.cpp:2625: DB::TCPHandler::run() @ 0x00000000366d1d8e
22. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000003a932122
23. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000003a932df2
24. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000003a89cd37
25. base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000003a89876e
26. ? @ 0x00007ffff7ca1e2e
27. ? @ 0x00007ffff7d33a4c
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Close https://github.com/ClickHouse/ClickHouse/issues/74910

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/ComparisonGraph.cpp [hunk 1]
```diff
@@ -144,9 +146,52 @@ const auto & getArguments(const FunctionNode * function)
...
+    try
+    {
+        return applyVisitor(FieldVisitorAccurateLess{}, lhs, rhs);
+    }
+    catch (const DB::Exception & e)
+    {
+        if (e.code() == ErrorCodes::BAD_TYPE_OF_FIELD)
+            throw Exception(
+                ErrorCodes::TYPE_MISMATCH,
+                "Trying to compare constants of incompatible type ({} and {}), please verify that table constraints are "
```
Comment (kssenii) [inline src/Interpreters/ComparisonGraph.cpp:160]:
```suggestion
                "Trying to compare constants of incompatible types ({} and {}), please verify that table constraints are "
```

File: src/Interpreters/ComparisonGraph.cpp [hunk 2]
```diff
@@ -144,9 +146,52 @@ const auto & getArguments(const FunctionNode * function)
...
+    try
+    {
+        return applyVisitor(FieldVisitorAccurateEquals{}, lhs, rhs);
+    }
+    catch (const DB::Exception & e)
+    {
+        if (e.code() == ErrorCodes::BAD_TYPE_OF_FIELD)
+            throw Exception(
+                ErrorCodes::TYPE_MISMATCH,
+                "Trying to compare constants of incompatible type ({} and {}), please verify that table constraints are "
```
Comment (kssenii) [inline src/Interpreters/ComparisonGraph.cpp:186]:
```suggestion
                "Trying to compare constants of incompatible types ({} and {}), please verify that table constraints are "
```

**Review by kssenii — APPROVED** [review]
