### PR TITLE
transform: correctly handle default column with multiple rows

### LINKED ISSUE #53187: Conditionals in CASE statements sometimes produce wrong results
**How to reproduce**

```
ClickHouse client version 23.7.1.1.
Connecting to localhost:9000 as user ymirlink.
Connected to ClickHouse server version 23.7.1 revision 54464.

:) SELECT  CAST(1, 'Nullable(String)') v1,
        CAST(number, 'String') v2,
        CASE 'x'
          WHEN 'y' THEN 0
          ELSE v1 = v2
        END cond1,
        v1 = v2 cond2

  FROM numbers(2)
FORMAT JSONCompact
;


SELECT
    CAST(1, 'Nullable(String)') AS v1,
    CAST(number, 'String') AS v2,
    caseWithExpression('x', 'y', 0, v1 = v2) AS cond1,
    v1 = v2 AS cond2
FROM numbers(2)
FORMAT JSONCompact

Query id: 7d0377c3-5c03-4953-893d-78d0808ceced

{
        "meta":
        [
                {
                        "name": "v1",
                        "type": "Nullable(String)"
                },
                {
                        "name": "v2",
                        "type": "String"
                },
                {
                        "name": "cond1",
                        "type": "Nullable(UInt8)"
                },
                {
                        "name": "cond2",
                        "type": "Nullable(UInt8)"
                }
        ],

        "data":
        [
                ["1", "0", 0, 0],
                ["1", "1", 0, 1]
        ],

        "rows": 2,

        "rows_before_limit_at_least": 2,

        "statistics":
        {
                "elapsed": 0.003158283,
                "rows_read": 2,
                "bytes_read": 16
        }
}

2 rows in set. Elapsed: 0.003 sec.
```

**Expected behavior**

`cond1` and `cond2` should always have the same value.

### PR DESCRIPTION
**Pull request by aiven-sal**
Close #53187 

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Correctly handle default column with multiple rows in transform

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 90e485957a825cb6491debacb5487ad3436e195c with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53742/90e485957a825cb6491debacb5487ad3436e195c/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Functions/transform.cpp [hunk 1]
```diff
@@ -163,7 +163,16 @@ namespace
 
             ColumnPtr default_non_const;
             if (!cache.default_column && arguments.size() == 4)
+            {
                 default_non_const = castColumn(arguments[3], result_type);
+                if (in->size() > default_non_const->size())
+                {
+                    throw Exception(
```
Comment (alexey-milovidov) [inline src/Functions/transform.cpp:170]: If columns in a blog are of different sizes, it is LOGICAL_ERROR, not BAD_ARGUMENTS (because a user cannot make it).
