### PR TITLE
Fix failing assertion while altering column comment of KeeperMap

### LINKED ISSUE #88077: Assertion `!ddl_worker || !ddl_worker->isCurrentlyActive() || txn' failure
### Describe the bug

Easy to reproduce.

### How to reproduce

With [config.txt](https://github.com/user-attachments/files/22682131/config.txt) for config.xml, run:
```sql
CREATE DATABASE d0 ENGINE = Replicated('/clickhouse/path/d0', '{shard}', '{replica}');
CREATE TABLE d0.t0 (c0 Int) ENGINE = KeeperMap('/k0', 1) PRIMARY KEY (c0);
ALTER TABLE d0.t0 COMMENT COLUMN c0 'a';
/*
src/Databases/DatabaseReplicated.cpp:2109:
virtual void DB::DatabaseReplicated::commitAlterTable(const StorageID &, const String &, const String &, const String &, ContextPtr):
Assertion `!ddl_worker || !ddl_worker->isCurrentlyActive() || txn' failed
*/
```

### Error message and/or stacktrace

Stack trace:
```
clickhouse: src/Databases/DatabaseReplicated.cpp:2109: virtual void DB::DatabaseReplicated::commitAlterTable(const StorageID &, const String &, const String &, const String &, ContextPtr): Assertion `!ddl_worker || !ddl_worker->isCurrentlyActive() || txn' failed.
2025.10.03 13:54:09.372162 [ 1065048 ] {} <Trace> BaseDaemon: Received signal 6
2025.10.03 13:54:09.372222 [ 1065048 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.10.03 13:54:09.372238 [ 1065048 ] {} <Fatal> BaseDaemon: (version 25.10.1.1587 (official build), build id: BC2FC5EC31E70AEC75D81392D187650C2EDDDCFA, git hash: 59d18f406d9ef99bbf400184fd0ba47a84381bec, architecture: x86_64) (from thread 1065050) Received signal 6
2025.10.03 13:54:09.372248 [ 1065048 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.10.03 13:54:09.372249 [ 1065048 ] {} <Fatal> BaseDaemon: 
2025.10.03 13:54:09.372264 [ 1065048 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007479a1ea49bd 0x00007479a1e4579e 0x00007479a1e288cd 0x00007479a1e28830 0x000059071ca3f2d3 0x000059071ca03f91 0x00005907206939a7 0x000059071d84b133 0x000059071d847fcd 0x000059071dc31382 0x000059071dc2b032 0x00005907214ee58e 0x0000590721507ea4 0x0000590729601c87 0x0000590729602265 0x00005907295a13ff 0x000059072959ead1 0x00007479a1ea27f1 0x00007479a1f33b5c
2025.10.03 13:54:09.372274 [ 1065048 ] {} <Fatal> BaseDaemon: ########################################
2025.10.03 13:54:09.372340 [ 1065048 ] {} <Fatal> BaseDaemon: (version 25.10.1.1587 (official build), build id: BC2FC5EC31E70AEC75D81392D187650C2EDDDCFA, git hash: 59d18f406d9ef99bbf400184fd0ba47a84381bec) (from thread 1065050) (query_id: 8de693c0-87b1-45e6-a1b1-3c462a322dbf) (query: ALTER TABLE d0.t0 COMMENT COLUMN c0 'a';) Received signal Aborted (6)
2025.10.03 13:54:09.372368 [ 1065048 ] {} <Fatal> BaseDaemon: 
2025.10.03 13:54:09.372397 [ 1065048 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007479a1ea49bd 0x00007479a1e4579e 0x00007479a1e288cd 0x00007479a1e28830 0x000059071ca3f2d3 0x000059071ca03f91 0x00005907206939a7 0x000059071d84b133 0x000059071d847fcd 0x000059071dc31382 0x000059071dc2b032 0x00005907214ee58e 0x0000590721507ea4 0x0000590729601c87 0x0000590729602265 0x00005907295a13ff 0x000059072959ead1 0x00007479a1ea27f1 0x00007479a1f33b5c
2025.10.03 13:54:09.372452 [ 1065048 ] {} <Fatal> BaseDaemon: 3. __pthread_kill @ 0x00000000000a49bd
2025.10.03 13:54:09.372481 [ 1065048 ] {} <Fatal> BaseDaemon: 4. raise @ 0x000000000004579e
2025.10.03 13:54:09.372511 [ 1065048 ] {} <Fatal> BaseDaemon: 5. abort @ 0x00000000000288cd
2025.10.03 13:54:09.372539 [ 1065048 ] {} <Fatal> BaseDaemon: 6. __GI___assert_perror_fail @ 0x0000000000028830
2025.10.03 13:54:09.450430 [ 1065048 ] {} <Fatal> BaseDaemon: 7. src/Databases/DatabaseReplicated.cpp:2109: DB::DatabaseReplicated::commitAlterTable(DB::StorageID const&, String const&, String const&, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001ac032d3
2025.10.03 13:54:09.482969 [ 1065048 ] {} <Fatal> BaseDaemon: 8. src/Databases/DatabaseOrdinary.cpp:671: DB::DatabaseOrdinary::alterTable(std::shared_ptr<DB::Context const>, DB::StorageID const&, DB::StorageInMemoryMetadata const&, bool) @ 0x000000001abc7f91
2025.10.03 13:54:09.516807 [ 1065048 ] {} <Fatal> BaseDaemon: 9. src/Storages/IStorage.cpp:246: DB::IStorage::alter(DB::AlterCommands const&, std::shared_ptr<DB::Context const>, std::unique_lock<std::timed_mutex>&) @ 0x000000001e8579a7
2025.10.03 13:54:09.543032 [ 1065048 ] {} <Fatal> BaseDaemon: 10. src/Interpreters/InterpreterAlterQuery.cpp:254: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x000000001ba0f133
2025.10.03 13:54:09.567380 [ 1065048 ] {} <Fatal> BaseDaemon: 11. src/Interpreters/InterpreterAlterQuery.cpp:82: DB::InterpreterAlterQuery::execute() @ 0x000000001ba0bfcd
2025.10.03 13:54:09.607562 [ 1065048 ] {} <Fatal> BaseDaemon: 12. src/Interpreters/executeQuery.cpp:1603: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x000000001bdf5382
2025.10.03 13:54:09.655500 [ 1065048 ] {} <Fatal> BaseDaemon: 13. src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001bdef032
2025.10.03 13:54:09.691428 [ 1065048 ] {} <Fatal> BaseDaemon: 14. src/Server/TCPHandler.cpp:743: DB::TCPHandler::runImpl() @ 0x000000001f6b258e
2025.10.03 13:54:09.748838 [ 1065048 ] {} <Fatal> BaseDaemon: 15. src/Server/TCPHandler.cpp:2754: DB::TCPHandler::run() @ 0x000000001f6cbea4
2025.10.03 13:54:09.752837 [ 1065048 ] {} <Fatal> BaseDaemon: 16. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000277c5c87
2025.10.03 13:54:09.757431 [ 1065048 ] {} <Fatal> BaseDaemon: 17. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000277c6265
2025.10.03 13:54:09.762004 [ 1065048 ] {} <Fatal> BaseDaemon: 18. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000277653ff
2025.10.03 13:54:09.766497 [ 1065048 ] {} <Fatal> BaseDaemon: 19. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000027762ad1
2025.10.03 13:54:09.766526 [ 1065048 ] {} <Fatal> BaseDaemon: 20. start_thread @ 0x00000000000a27f1
2025.10.03 13:54:09.766548 [ 1065048 ] {} <Fatal> BaseDaemon: 21. __clone3 @ 0x0000000000133b5c
2025.10.03 13:54:09.984317 [ 1065048 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: B97F1B3CCD91DAFB40FA60D979E802FE)
2025.10.03 13:54:09.995423 [ 1065048 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.10.03 13:54:09.995611 [ 1065048 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, enable_lightweight_update = true, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, parallel_replicas_for_non_replicated_merge_tree = true, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_live_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_qbit_type = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_shared_set_join = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by korowa**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

* Make `ALTER COLUMN ... COMMENT` commands for KeeperMap tables replicated so they are committed to Replicated database metadata and propagated across all replicas. Closes #88077 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/DatabaseReplicated.cpp [hunk 1]
```diff
@@ -2331,8 +2331,13 @@ bool DatabaseReplicated::shouldReplicateQuery(const ContextPtr & query_context,
...
     {
-        if (alter->isAttachAlter() || alter->isFetchAlter() || alter->isDropPartitionAlter()
-            || is_keeper_map_table(query_ptr) || alter->isFreezeAlter() || alter->isUnlockSnapshot())
+        if (alter->isAttachAlter() || alter->isFetchAlter() || alter->isDropPartitionAlter() || alter->isFreezeAlter()
+            || alter->isUnlockSnapshot())
+            return false;
+
+        // Allowed ALTER operation on KeeperMap still should be replicated
+        // to update metadata on all nodes and commit it to database metadata
+        if (is_keeper_map_table(query_ptr) && !alter->isCommentAlter())
```
Comment (vdimir) [inline src/Databases/DatabaseReplicated.cpp:2340]: Can't we have any other operations that changes table metadata and needs to be replicated?

Comment (korowa) [reply src/Databases/DatabaseReplicated.cpp:2340]: No, this is the only DDL operation allowed for the Keeper (and in general for IStorage)

**Comment by korowa** [comment]
I'll fix the test to make it pass bugfix validation check (the assertion is performed only in debug builds).

**Review by vdimir — APPROVED** [review]
Thanks for taking the time to improve the project!
