### PR TITLE
Fix read in order optimization of COLLATE is present #22379

### LINKED ISSUE #22379: ORDER BY column_name COLLATE does not work for primary keys
(you don't have to strictly follow this form)

**Describe the bug**
When using `ORDER BY column_name COLLATE 'en'`, `COLLATE` is ignored if `column_name` is the primary key
 
**How to reproduce**
* version 21.1.2
* `CREATE TABLE` statements for all tables involved:
```
CREATE TABLE test.test_collation
(
    `v` String,
    `v2` String
)
ENGINE = MergeTree
ORDER BY v
SETTINGS index_granularity = 8192
```
* Sample data:
```
insert into test.test_collation values ('A', 'A')
insert into test.test_collation values ('B', 'B')
insert into test.test_collation values ('C', 'C')
insert into test.test_collation values ('a', 'a')
insert into test.test_collation values ('b', 'b')
insert into test.test_collation values ('c', 'c')
```
* Queries to run that lead to unexpected result
Primary key
```
SELECT *
FROM test.test_collation
ORDER BY v ASC COLLATE 'en'

Query id: fa84ae7a-abe7-4886-99cd-eba7ad5d5fc4

┌─v─┬─v2─┐
│ A │ A  │
│ B │ B  │
│ C │ C  │
│ a │ a  │
│ b │ b  │
│ c │ c  │
└───┴────┘
```
Separate column
```
SELECT *
FROM test.test_collation
ORDER BY v2 ASC COLLATE 'en'

Query id: 04401f85-3cb2-442c-8c89-e3328d1615cd

┌─v─┬─v2─┐
│ a │ a  │
│ A │ A  │
│ b │ b  │
│ B │ B  │
│ c │ c  │
│ C │ C  │
└───┴────┘
```

**Expected behavior**
Both of these queries to return the rows in the same order

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`ORDER BY` with `COLLATE` was not working correctly if the column is in primary key (or is a monotonic function of it) and the setting `optimize_read_in_order` is not turned off. This closes #22379. Workaround for older versions: turn the setting `optimize_read_in_order` off.

### CODE REVIEW

File: src/Storages/ReadInOrderOptimizer.cpp [hunk 1]
```diff
@@ -55,13 +55,18 @@ InputOrderInfoPtr ReadInOrderOptimizer::getInputOrder(const StorageMetadataPtr &
         ///  or in some simple cases when order key element is wrapped into monotonic function.
         auto apply_order_judge = [&] (const ExpressionActions::Actions & actions, const String & sort_column)
         {
+            /// If required order depend on collation, it cannot be matched with primary key order.
+            /// Because primary keys cannot have collations.
+            if (required_sort_description[i].collator)
```
Comment (alexey-milovidov) [inline src/Storages/ReadInOrderOptimizer.cpp:60]: This.

**Review by CurtizJ — APPROVED** [review]

**Comment by CurtizJ** [comment]
Fast test: `executeQuery: Code: 344, e.displayText() = DB::Exception: Collations support is disabled, because ClickHouse was built without ICU library`
