### PR TITLE
Fix wrong result type of comparison functions with Tuple(Dynamic) and String

### LINKED ISSUE #80645: Dynamic type: Unexpected return type from equals
### Describe the bug

Source issue https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80611&sha=108e0d06f1ed95a4074579b287a163894690a05b&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29

### How to reproduce

Simplified to:
```
SET enable_dynamic_type=1;
DROP TABLE IF EXISTS t1__fuzz_44;
CREATE TABLE t1__fuzz_44 (`id` Int256, `s1` Dynamic(max_types = 15), `s2` Nullable(UInt256)) ORDER BY id;
INSERT INTO t1__fuzz_44 FORMAT Values (1, 'a', 'b'), (2, 'c', 'd'), (3, 'e', null);
SELECT id FROM t1__fuzz_44 WHERE '(\'a\',null)' = (s1, NULL IS NOT NULL) GROUP BY 1;
```

### Error message and/or stacktrace

```
2025.05.21 18:53:12.121053 [ 400182 ] {d1689d7b-41f3-4779-9dcf-3971373c6588} <Error> executeQuery: Code: 49. DB::Exception: Unexpected return type from equals. Expected UInt8. Got Nullable(UInt8). Action:
FUNCTION equals('(\'a\',null)'_String :: 1, tuple(__table1.s1, _CAST(0_UInt8, 'UInt8'_String)) :: 3) -> equals('(\'a\',null)'_String, tuple(__table1.s1, _CAST(0_UInt8, 'UInt8'_String))) UInt8 : 2,
input block structure:'(\'a\',null)'_String String Const(size = 0, String(size = 1)), tuple(__table1.s1, _CAST(0_UInt8, 'UInt8'_String)) Tuple(Dynamic(max_types=15), UInt8) Tuple(size = 0, Dynamic(size = 0, Variant(size = 0, UInt8(size = 0), UInt64(size = 0), String(size = 0))), UInt8(size = 0)): while executing 'FUNCTION equals('(\'a\',null)'_String :: 1, tuple(__table1.s1, _CAST(0_UInt8, 'UInt8'_String)) :: 3) -> equals('(\'a\',null)'_String, tuple(__table1.s1, _CAST(0_UInt8, 'UInt8'_String))) UInt8 : 2': While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder). (LOGICAL_ERROR) (version 25.6.1.1) (from 192.168.1.200:46182) (query 5, line 5) (in query: SELECT id FROM t1__fuzz_44 WHERE '(\'a\',null)' = (s1, NULL IS NOT NULL) GROUP BY 1;), Stack trace (when copying this message, always include the lines below):

0. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001959af52
1. /mnt/ch/ClickHouse/src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e8ce807
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000834c9dc
3. DB::Exception::Exception<String, String, String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&, String&&, String&&) @ 0x0000000009fbe0e7
4. /mnt/ch/ClickHouse/src/Interpreters/ExpressionActions.cpp:645: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const @ 0x0000000013a910d6
5. /mnt/ch/ClickHouse/src/Interpreters/ExpressionActions.cpp:827: DB::ExpressionActions::execute(DB::Block&, bool, bool) const @ 0x0000000013a9174c
6. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeRangeReader.cpp:826: DB::MergeTreeRangeReader::MergeTreeRangeReader(DB::IMergeTreeReader*, DB::Block, DB::PrewhereExprStep const*, std::shared_ptr<DB::ReadStepPerformanceCounters>, bool) @ 0x00000000158a5938
7. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::MergeTreeRangeReader* std::construct_at[abi:ne190107]<DB::MergeTreeRangeReader, DB::IMergeTreeReader*, DB::Block const, DB::PrewhereExprStep*, std::shared_ptr<DB::ReadStepPerformanceCounters>, bool, DB::MergeTreeRangeReader*>(DB::MergeTreeRangeReader*, DB::IMergeTreeReader*&&, DB::Block const&&, DB::PrewhereExprStep*&&, std::shared_ptr<DB::ReadStepPerformanceCounters>&&, bool&&) @ 0x00000000158c5526
8. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__memory/construct_at.h:49: DB::MergeTreeReadTask::createReadersChain(DB::MergeTreeReadTask::Readers const&, DB::PrewhereExprInfo const&, DB::ReadStepsPerformanceCounters&) @ 0x00000000158c3635
9. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeReadTask.cpp:124: DB::MergeTreeReadTask::initializeReadersChain(DB::PrewhereExprInfo const&, DB::ReadStepsPerformanceCounters&) @ 0x00000000158c3d5d
10. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:277: DB::MergeTreeSelectProcessor::initializeReadersChain() @ 0x00000000158cdc6d
11. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:220: DB::MergeTreeSelectProcessor::read() @ 0x00000000158cd258
12. /mnt/ch/ClickHouse/src/Storages/MergeTree/MergeTreeSource.cpp:229: DB::MergeTreeSource::tryGenerate() @ 0x000000001639a928
13. /mnt/ch/ClickHouse/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x0000000015e81b55
14. /mnt/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x0000000015e9cf61
15. /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:304: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000015e91b39
16. /mnt/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:274: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000015e9284f
17. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000ea2b3cc
18. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000000ea30c34
19. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000ea28c56
20. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000ea2ee0e
21. ? @ 0x00007e2d14b9d7eb
```

Does not happen if I replace the Dynamic type with String.

It seems it's present since 24.10, https://fiddle.clickhouse.com/ebb78dbf-aafd-4574-bdb1-ab2d24abe6be, but ok in 24.9

cc @Avogar

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong result type of comparison functions with Tuple(Dynamic) and String that led to logical error.

Closes https://github.com/ClickHouse/ClickHouse/issues/80645

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by Algunenano — APPROVED** [review]

**Comment by Avogar** [comment]
[Stateless tests (debug, distributed plan, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80728&sha=7c692b6bbbfc64e47749dd3b08e3b6f3d85975a4&name_0=PR&name_1=Stateless%20tests%20%28debug%2C%20distributed%20plan%2C%20s3%20storage%29) - https://github.com/ClickHouse/ClickHouse/issues/80811
[Stateless tests (release, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80728&sha=7c692b6bbbfc64e47749dd3b08e3b6f3d85975a4&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20ParallelReplicas%2C%20s3%20storage%29) - https://github.com/ClickHouse/ClickHouse/issues/65382

File: src/Functions/FunctionsComparison.h [hunk 1]
```diff
@@ -1244,7 +1244,7 @@ class FunctionComparison : public IFunction
                                                    {nullptr, right_tuple->getElements()[i], ""}};
                     element_type = func->build(args)->getResultType();
                 }
-                has_nullable = has_nullable || element_type->isNullable();
+                has_nullable = has_nullable || element_type->isNullable() || isDynamic(element_type);
```
Comment (alexey-milovidov) [inline src/Functions/FunctionsComparison.h:1247]: The code looks weird, why don't add a method like `canContainNulls`?
