### PR TITLE
Use insertion columns for INFILE schema inference

### LINKED ISSUE #71050: INSERT INTO FUNCTION seems to ignore column list
**Describe the bug**
By issuing an `ALTER TABLE ... MODIFY COLUMN ... FIRST` before, the inserts go to the wrong columns.

**How to reproduce**
Run:

```sql
CREATE TABLE t0 (c0 Int, c1 Int) ENGINE = Memory();
ALTER TABLE t0 MODIFY COLUMN c1 Int FIRST;
INSERT INTO TABLE t0 (c0, c1) VALUES (1, 2);
SELECT c0, c1 FROM t0; --1, 2
INSERT INTO TABLE FUNCTION file('<path to file>', 'CSV', 'c0 Int, c1 Int') SELECT c0, c1 FROM t0;
TRUNCATE t0;
INSERT INTO TABLE t0 (c0, c1) FROM INFILE '<path to file>' FORMAT CSV;
SELECT c0, c1 FROM t0; --2, 1
```

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
Take columns order during client data streaming from insertion columns.
Closes #71050

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Use insertion columns for INFILE schema inference

### CODE REVIEW

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -1902,6 +1903,19 @@ void ClientBase::sendData(Block & sample, const ColumnsDescription & columns_des
...
         }
 
+        if (parsed_insert_query->columns)
+        {
+            auto columns = processColumnTransformers(columns_for_storage_file, parsed_insert_query->columns, client_context->getCurrentDatabase(), client_context->getInsertionTable());
+            ColumnsDescription reordered_description{};
+            for (const auto & col_name : columns->children)
+            {
+                auto col = columns_for_storage_file.get(col_name->getColumnName());
+                reordered_description.add(col);
```
Comment (jkartseva) [inline src/Client/ClientBase.cpp:1913]: nit: add(std::move(col))

File: src/Client/ClientBase.cpp [hunk 2]
```diff
@@ -1902,6 +1903,19 @@ void ClientBase::sendData(Block & sample, const ColumnsDescription & columns_des
...
+            }
+
+            columns_for_storage_file = reordered_description;
```
Comment (jkartseva) [inline src/Client/ClientBase.cpp:1916]: same, std::move(reordered_description)

File: src/Interpreters/processColumnTransformers.h [hunk 3]
```diff
@@ -1,7 +1,9 @@
 #pragma once
 
 #include <Parsers/IAST_fwd.h>
+#include <Storages/ColumnsDescription.h>
 #include <Storages/IStorage_fwd.h>
+#include <Interpreters/StorageID.h>
```
Comment (jkartseva) [inline src/Interpreters/processColumnTransformers.h:6]: It is possible to use a forward declaration and move includes to '*.cpp':
```
class ColumnsDescription;
struct StorageID;
```

File: src/Interpreters/processColumnTransformers.h [hunk 4]
```diff
@@ -16,4 +18,10 @@ ASTPtr processColumnTransformers(
         const StorageMetadataPtr & metadata_snapshot,
         ASTPtr query_columns);
 
+ASTPtr processColumnTransformers(
+        const ColumnsDescription & columns,
+        ASTPtr query_columns,
+        const String & current_database,
+        const StorageID & table_id);
```
Comment (jkartseva) [inline src/Interpreters/processColumnTransformers.h:25]: nit: let's reorder the parameters for readability, matching the first function overload:
```
const String & current_database,
const StorageID & table_id,
const ColumnsDescription & columns,
ASTPtr query_columns
```

**Review by jkartseva — APPROVED** [review]
LGTM with minor nits.
