### PR TITLE
Replace domain IP types (IPv4, IPv6) with native

### LINKED ISSUE #14567: Bad comparison of IPv6 to String: toIPv6('::1') != '::1'
```
:) select toIPv6('::1') = '::1'

┌─equals(toIPv6('::1'), '::1')─┐
│                            0 │
└──────────────────────────────┘
```

Not sure what's going on. It does some implicit cast, but somehow casts to a wrong type? I would expect an error about implicit cast since we don't do them often, or at least that they compare as equal.

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

closes #14567

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
IPv6 is not yet fully operational - parser isn't working properly...

**Review by yakov-olkhovskiy — COMMENTED** [review]
NOTE: this comment is outdated...

@alexey-milovidov BTW I'm not completely sure this is correct - probably it needs the same std::is_copy_constructible enabler for type U as above for type T (it will be a template template parameter I guess..)

File: src/IO/ReadHelpers.h [hunk 1]
```diff
@@ -833,6 +837,87 @@ inline bool tryReadUUIDText(UUID & uuid, ReadBuffer & buf)
     return readUUIDTextImpl<bool>(uuid, buf);
 }
 
+template <typename ReturnType = void>
+inline ReturnType readIPv4TextImpl(IPv4 & ip, ReadBuffer & buf)
+{
+    const char * end = parseIPv4(buf.position(), buf.position() + buf.available(), reinterpret_cast<unsigned char *>(&ip.toUnderType()));
```
Comment (CurtizJ) [inline src/IO/ReadHelpers.h:843]: It's not completely correct. If string with ip is on the border of buffer it won't be parsed correctly.

File: src/IO/ReadHelpers.h [hunk 2]
```diff
@@ -833,6 +837,87 @@ inline bool tryReadUUIDText(UUID & uuid, ReadBuffer & buf)
...
+{
+    return readIPv4TextImpl<bool>(ip, buf);
+}
+
+template <typename ReturnType = void>
+inline ReturnType readIPv6TextImpl(IPv6 & ip, ReadBuffer & buf)
+{
+    unsigned char * p = reinterpret_cast<unsigned char *>(ip.toUnderType().items);
+
+    const char * end = parseIPv4(buf.position(), buf.position() + buf.available(), p);
```
Comment (CurtizJ) [inline src/IO/ReadHelpers.h:872]: The same as with `IPv4`.

File: src/IO/WriteHelpers.cpp [hunk 3]
```diff
@@ -34,6 +36,79 @@ void formatUUID(std::reverse_iterator<const UInt8 *> src16, UInt8 * dst36)
     formatHex(src16 + 2, &dst36[24], 6);
 }
 
+/** Further we want to generate constexpr array of strings with sizes from sequence of unsigned ints [0..N)
+ *  in order to use this arrey for fast conversion of unsigned integers to strings
+ */
```
Comment (CurtizJ) [inline src/IO/WriteHelpers.cpp:41]: There is the same predefined [table] in (https://github.com/ClickHouse/clickhouse-private/blob/2b3cb810cd791a7409d5bc27878fcccb71ad5d69/src/Common/formatIPv6.cpp#L13) `formatIPv6.cpp`. I think it's better to leave only one implementation. But I'm not sure which one is better: explicit or generated one.

File: src/Interpreters/convertFieldToType.cpp [hunk 4]
```diff
@@ -249,6 +249,25 @@ Field convertFieldToTypeImpl(const Field & src, const IDataType & type, const ID
         /// Already in needed type.
         return src;
     }
+    else if (which_type.isIPv4() && src.getType() == Field::Types::IPv4)
+    {
+        /// Already in needed type.
+        return src;
+    }
```
Comment (CurtizJ) [inline src/Interpreters/convertFieldToType.cpp:256]: Maybe add a conversion from integer fields?

**Review by CurtizJ — COMMENTED** [review]
Looks like all changes are backward compatible, right? But please could you add tests for backward compatibility. You can add an integration test in which you can run nodes with different versions. There are some [examples](https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration/test_backward_compatibility).

**Comment by yakov-olkhovskiy** [comment]
@CurtizJ 
>Looks like all changes are backward compatible, right?

we have some incompatibilities here - I will say couple words on Thursday's meeting so we can estimate possible impact

File: src/Processors/Formats/IRowInputFormat.cpp [hunk 5]
```diff
@@ -44,7 +46,9 @@ bool isParseError(int code)
         || code == ErrorCodes::TOO_LARGE_STRING_SIZE
         || code == ErrorCodes::ARGUMENT_OUT_OF_BOUND       /// For Decimals
         || code == ErrorCodes::INCORRECT_DATA              /// For some ReadHelpers
-        || code == ErrorCodes::CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING;
+        || code == ErrorCodes::CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING
+        || code == ErrorCodes::CANNOT_PARSE_IPV4
+        || code == ErrorCodes::CANNOT_PARSE_IPV6;
```
[the remark this answers is not in the document]
Comment (yakov-olkhovskiy) [reply src/Processors/Formats/IRowInputFormat.cpp:51]: not sure regarding this - HTTP processing doesn't contain `ErrorCodes::CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING` - which was an error code for parsing IPv4 and IPv6 previously - so adding them there will change the behavior...

File: src/Functions/FunctionsBinaryRepresentation.cpp [hunk 6]
```diff
@@ -546,6 +550,88 @@ class EncodeToBinaryRepresentation : public IFunction
             return false;
         }
     }
+
+    bool tryExecuteIPv6(const IColumn * col, ColumnPtr & col_res) const
```
[the remark this answers is not in the document]
Comment (yakov-olkhovskiy) [reply src/Functions/FunctionsBinaryRepresentation.cpp:554]: don't think so - they work with different types and implementations are different too

File: src/Functions/FunctionsCodingIP.h [hunk 7]
```diff
@@ -44,10 +50,78 @@ namespace detail
...
+                {
+                    auto col_res = ColumnFixedString::create(string_column);
+
+                    if constexpr (exception_mode == IPStringToNumExceptionMode::Null)
+                    {
+                        col_null_map_to = ColumnUInt8::create(column_size, false);
+                        if (null_map)
+                            memcpy(col_null_map_to->getData().data(), null_map->data(), column_size);
+                        return ColumnNullable::create(std::move(col_res), std::move(col_null_map_to));
+                    }
```
[the remark this answers is not in the document]
Comment (yakov-olkhovskiy) [reply src/Functions/FunctionsCodingIP.h:69]: no, it depends on `ToColumn` type making it impossible to unify these blocks

File: src/IO/ReadHelpers.h (hunk 1 above)
Comment (yakov-olkhovskiy) [reply src/IO/ReadHelpers.h:843]: what do you mean "ip is on the border of buffer"?

File: src/Processors/Formats/IRowInputFormat.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (CurtizJ) [reply src/Processors/Formats/IRowInputFormat.cpp:51]: `CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING` also should be in HTTP handler because we shouldn't return 5xx code for that error.

File: src/Interpreters/convertFieldToType.cpp (hunk 4 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/convertFieldToType.cpp:256]: I would rather not - the accurate conversion is only possible to type UInt32 and larger - such limitation is not obvious in implicit context.

File: src/IO/ReadHelpers.h (hunk 1 above)
Comment (yakov-olkhovskiy) [reply src/IO/ReadHelpers.h:843]: buffer always contains complete literal at least - how else would you treat let's say "127.0.0.1"? maybe it's "127.0.0.100"...

Comment (CurtizJ) [reply src/IO/ReadHelpers.h:843]: > buffer always contains complete literal at least

But how is it guaranteed? This function is used inside serialization and there are no literals. You can have arbitrary text sequence and exactly this function have to extract value from raw data (like `readIntText`).

Comment (yakov-olkhovskiy) [reply src/IO/ReadHelpers.h:843]: apparently it is guaranteed by an expression parser which calls this function - `readIntTextImpl` does exactly the same - reads text until not eof and convertible to number

Comment (CurtizJ) [reply src/IO/ReadHelpers.h:843]: It's guaranteed by expression parser, but it's not guaranteed in other places where this function may be called.

> readIntTextImpl does exactly the same

No. It reads until `eof` or until parsing will knowly fail (non-digit char or overflow). Wherein `eof` calls `ReadBuffer::next()`,  which request more data if we reached the end of working buffer.

In general this test shall pass:
```sql
DROP TABLE IF EXISTS test_file_ip;

CREATE TABLE test_file_ip
(
    `id` UInt32,
    `ip` IPv4,
    `s` String
)
ENGINE = File(JSONEachRow, 'test_file_ip.json');

SET engine_file_truncate_on_insert = 1;
INSERT INTO test_file_ip VALUES(1, toIPv4('190.1.5.64'), 'foo');

SELECT *
FROM file('test_file_ip.json', 'JSONEachRow', 'id UInt32, ip IPv4, s String')
SETTINGS input_format_parallel_parsing = 0;

SELECT *
FROM file('test_file_ip.json', 'JSONEachRow', 'id UInt32, ip IPv4, s String')
SETTINGS input_format_parallel_parsing = 0, max_read_buffer_size = 4;

```

and return

```
1       190.1.5.64      foo
1       190.1.5.64      foo
```

Now it returns:
```
1       190.1.5.64      foo
Received exception from server (version 22.12.1):
Code: 671. DB::Exception: Received from localhost:9000. DB::ParsingException. DB::ParsingException: Cannot parse IPv4 19: (while reading the value of key ip): While executing JSONEachRowRowInputFormat: While executing File: (in file/uri /home/ubuntu/data22/user_files/test_file_ip.json): (at row 1)
. (NAMED_COLLECTION_IS_IMMUTABLE)
(query: SELECT *
FROM file('test_file_ip.json', 'JSONEachRow', 'id UInt32, ip IPv4, s String')
SETTINGS input_format_parallel_parsing = 0, max_read_buffer_size = 4;)
```

Comment (yakov-olkhovskiy) [reply src/IO/ReadHelpers.h:843]: oh, I missed this eof() functionality... will fix it, thanks

**Comment by yakov-olkhovskiy** [comment]
@CurtizJ I rewrote parser completely, sorry :) it's quite convoluted, though I added comments to make it easier to follow

**Comment by yakov-olkhovskiy** [comment]
@CurtizJ I think it's time to merge this PR, could you please approve? Regarding incompatibilities we talked before - I think all of them were removed, so there is nothing to mention in changelog.

**Review by CurtizJ — APPROVED** [review]

**Comment by CurtizJ** [comment]
Test failures are not related to this PR.

**Comment by kolya7k** [comment]
This commit will produce regression errors while trying to insert UInt32 as IPv4 without ::UInt32 like
INSERT INTO stats_logins (player_id, ip, time) VALUES (52471021, 2319771222, 1675099213);
