### PR TITLE
Fix materialized views with `optimize_functions_to_subcolumns`

### LINKED ISSUE #68904: DB::Exception: Not found column Attributes.keys in block NOT_FOUND_COLUMN_IN_BLOCK
**Describe the unexpected behaviour**
I am using clickhouse (24.9.1).  It looks like the latest release broke the materialized view which used to work fine in 24.3 release.
"DB::Exception: Not found column Attributes.keys in block"

**How to reproduce**
```
CREATE TABLE mydb.rawtable
(
  `Id` UInt64 CODEC(Delta(8), ZSTD(1)),
  `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
  `MetricName` LowCardinality(String) CODEC(ZSTD(1)),
  `TimeUnix` DateTime CODEC(Delta(8), ZSTD(1))
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(TimeUnix)
ORDER BY (MetricName, Attributes, toUnixTimestamp(TimeUnix))

CREATE MATERIALIZED VIEW mydb.raw_to_attributes_mv TO mydb.attributes
(
  `Id` UInt64,
  `MetricName` LowCardinality(String),
  `TimeUnix` DateTime,
  `AttributeKeys` Array(LowCardinality(String)),
  `AttributeValues` Array(String)
)
AS SELECT
  Id,
  MetricName,
  toStartOfDay(TimeUnix) AS TimeUnix,
  mapKeys(Attributes) AS AttributeKeys,
  mapValues(Attributes) AS AttributeValues
FROM mydb.rawtable

CREATE TABLE mydb.attributes
(
  `Id` UInt64 CODEC(Delta(8), ZSTD(1)),
  `MetricName` LowCardinality(String) CODEC(ZSTD(1)),
  `TimeUnix` DateTime CODEC(Delta(8), ZSTD(1)),
  `AttributeKeys` Array(LowCardinality(String)) CODEC(ZSTD(1)),
  `AttributeValues` Array(String) CODEC(ZSTD(1))
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(TimeUnix)
ORDER BY (MetricName, Id, TimeUnix) 
```

* Which ClickHouse server version to use
24.9.1

* Queries to run that lead to unexpected result

insert into rawtable values (1, {'key1': 'value1', 'key2': 'value2'}, 'm1', now())

**Expected behavior**
This used to work in 24.5. 

**Error message and/or stacktrace**
DB::Exception: Not found column Attributes.keys in block. There are only columns: Id, Attributes, MetricName, TimeUnix: while pushing to view mydb.raw_to_attributes_mv. (NOT_FOUND_COLUMN_IN_BLOCK)

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed writing to Materialized Views with enabled setting `optimize_functions_to_subcolumns`.

Fixes #68904.

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit c7d0d790e2b37bcd91f5e147d775e656bf3d22a7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68951/c7d0d790e2b37bcd91f5e147d775e656bf3d22a7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/68951/c7d0d790e2b37bcd91f5e147d775e656bf3d22a7/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Passes/FunctionToSubcolumnsPass.cpp [hunk 1]
```diff
@@ -232,6 +232,10 @@ std::tuple<FunctionNode *, ColumnNode *, TableNode *> getTypedNodesForOptimizati
     const auto & storage_snapshot = table_node->getStorageSnapshot();
     auto column = first_argument_column_node->getColumn();
 
+    auto view_source = context->getViewSource();
+    if (view_source && view_source->getStorageID().getFullNameNotQuoted() == storage->getStorageID().getFullNameNotQuoted())
+        return {};
+
```
Comment (nikitamikhaylov) [inline src/Analyzer/Passes/FunctionToSubcolumnsPass.cpp:238]: Let's add a comment, because this is not obvious.

**Review by nikitamikhaylov — APPROVED** [review]
