### PR TITLE
fix test 03322_materialized_view_ignore_errors_ur

### LINKED ISSUE #91245: Test `03322_materialized_view_ignore_errors_url` is flaky
https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMzMyMl9tYXRlcmlhbGl6ZWRfdmlld19pZ25vcmVfZXJyb3JzX3VybCcKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0YXRlbGVzcyB0ZXN0cyAoYW1kX2RlYnVnLCBBc3luY0luc2VydCwgczMgc3RvcmFnZSwgcGFyYWxsZWwpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK

Example: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90630&sha=32f47c46ef05dd8c19250c779d115e3df7b2a0ab&name_0=PR&name_1=Stateless+tests+%28amd_debug%2C+AsyncInsert%2C+s3+storage%2C+parallel%29&name_1=Stateless+tests+%28amd_debug%2C+AsyncInsert%2C+s3+storage%2C+parallel%29&name_2=Tests

```
2025-11-27 11:07:54 Reason: result differs with reference:  
2025-11-27 11:07:54 --- /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03322_materialized_view_ignore_errors_url.reference	2025-11-27 10:58:06.794396131 +0100
2025-11-27 11:07:54 +++ /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03322_materialized_view_ignore_errors_url.stdout	2025-11-27 11:07:54.620028245 +0100
2025-11-27 11:07:54 @@ -1,2 +1 @@
2025-11-27 11:07:54 -1
2025-11-27 11:07:54  2
2025-11-27 11:07:54 
```

@CheSema as an expert in pushing to materialized views, maybe you have ideas?

### PR DESCRIPTION
**Pull request by CheSema**
Fixes https://github.com/ClickHouse/ClickHouse/issues/91245

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03322_materialized_view_ignore_errors_url.sql [hunk 1]
```diff
@@ -12,7 +12,8 @@ INSERT INTO src SETTINGS materialized_views_ignore_errors = 0 VALUES (1); -- { s
 
 INSERT INTO src SETTINGS materialized_views_ignore_errors = 1 VALUES (2);
 
-SELECT * FROM src ORDER BY x;
+--- value 2 should be in src, value 1 could be in src
+SELECT * FROM src ORDER BY x WHERE x = 2;
```
Comment (Avogar) [inline tests/queries/0_stateless/03322_materialized_view_ignore_errors_url.sql]:
```suggestion
SELECT * FROM src WHERE x = 2;
```
