### PR TITLE
Fix uniqExact incorrect result with ROLLUP/CUBE

### LINKED ISSUE #86931: Incorrect results with `GROUP BY WITH ROLLUP` and `uniqExact` under specific column values
### Company or project name

_No response_

### Describe the unexpected behaviour

Using `uniqExact` with `GROUP BY WITH ROLLUP` sometimes produces incorrect results (occasionally “blinking” between the correct and incorrect value). The incorrect value always matches the summary row.

Observations:
- Modifying the column used for grouping (either in SQL, e.g. +1 or `toString`, or before inserting data into the database) makes the bug disappear (at least on the sample dataset).
- Replacing `uniqExact` with `uniq` or removing `WITH ROLLUP` also makes the bug disappear.
- Between versions (from 25.6 to 25.8) the behavior varied slightly (e.g. in one version the results were “blinking,” while in another they were consistently incorrect).

### Which ClickHouse versions are affected?

25.6.1+ (I've checked every minor version from 25.1 to 25.8)

### How to reproduce

**Version:** v25.8.2.29
**Schema**:
```
CREATE DATABASE reproduction
ENGINE = Atomic;

CREATE TABLE reproduction.tree_nodes
(
    `date` Date,
    `c1` LowCardinality(String),
    `c2` UInt32,
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(date)
ORDER BY (date, c1, c2)
SETTINGS index_granularity = 8192;

CREATE TABLE reproduction.hits
(
    `date` Date,
    `c1` LowCardinality(String),
    `c2` Nullable(UInt32),
    `c3` UInt32,
    `c4` UInt32,
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(date)
ORDER BY (date, c1, c3)
SETTINGS index_granularity = 8192;
```

**Sample data**
[tree_nodes.csv.gz](https://github.com/user-attachments/files/22254670/reproduction.factorized.tree_nodes.csv.gz)
[hits.csv.gz](https://github.com/user-attachments/files/22254669/reproduction.factorized.hits.csv.gz)

**Query**
```
SELECT
    nt,
    uniqExact(filtered.c2) AS result
FROM
(
    SELECT
        date,
        if((date, c4) IN (
            SELECT DISTINCT
                date,
                c2
            FROM reproduction.tree_nodes
        ), c4, NULL) AS nt,
        c2
    FROM reproduction.hits
    WHERE c1 IN ['p1']
) AS filtered
GROUP BY nt
    WITH ROLLUP
```

### Expected behavior

The result for `nt = 1071106` should always be equal to `143254`.

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed possible incorrect result of `uniqExact` function with `ROLLUP` and `CUBE` modifiers.

---

Closes: #86931

### CODE REVIEW

File: tests/queries/0_stateless/03611_uniqExact_bug.sql
Comment (den-crane) [inline tests/queries/0_stateless/03611_uniqExact_bug.sql:1]: You can slightly beautify it with `WITH` :)

```
create table test(c1 Int64, c2 Int64)
Engine=MergeTree ORDER BY c2 AS  
WITH gen as 
  (SELECT xxHash32(number)   % 1000000 / 1000000 AS u1,
          xxHash32(number+12345) % 1000000 / 1000000 AS u2
   FROM numbers(1e6))
SELECT
    1071106,
    5+abs(1 + 151703 * (sqrt(-2 * log(u1)) * cos(2 * pi() * u2)))
FROM gen
union all
SELECT
    1071102,
    8+abs(1 + 151693 * (sqrt(-2 * log(u1)) * cos(2 * pi() * u2)))
FROM gen
```

File: src/AggregateFunctions/UniqExactSet.h [hunk 1]
```diff
@@ -243,10 +244,27 @@ class UniqExactSet
...
     const SingleLevelSet & asSingleLevel() const { return single_level_set; }
 
-    TwoLevelSet & asTwoLevel() { return *two_level_set; }
+    TwoLevelSet & asTwoLevel()
+    {
+        doDeepCopyIfNeeded();
+        return *two_level_set;
+    }
+
     const TwoLevelSet & asTwoLevel() const { return *two_level_set; }
```
Comment (SmitaRKulkarni) [inline src/AggregateFunctions/UniqExactSet.h:254]: @nickitat Does it make sense to also call `doDeepCopyIfNeeded` here too ?

**Review by SmitaRKulkarni — APPROVED** [review]
Rest all LGTM

**Review by nickitat — COMMENTED** [review]
I've added a new runtime if on the hot path, need to fix that before merging

**Comment by adrian17** [comment]
Hey, to be sure: the regression originally came from an optimization PR https://github.com/ClickHouse/ClickHouse/pull/79971 , and this - I'm assuming - partially cancels it? Should I expect the final performance of `uniqExact` with `rollup`s to be about same as before the regression, or better (just not as good as with the broken optimization), or worse? There were no benchmarks done on this unlike in https://github.com/ClickHouse/ClickHouse/pull/79971#issue-3049044741 .

**Comment by nickitat** [comment]
> Should I expect the final performance of uniqExact with rollups to be about same as before the regression

yes

> here were no benchmarks done

performance tests run automatically, you can find them [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87014&sha=dd10a3c6e4f20c315862083cd8e00a060e488e97&name_0=PR)
