### PR TITLE
No longer print time on hidden query

### LINKED ISSUE #91532: When I run `clickhouse-local` with the `--time` option and an input table, it outputs the time twice.
### Company or project name

ClickHouse

### Describe the unexpected behaviour

It happens because it runs a hidden query that creates a temporary table first. The time for this hidden query should also be hidden.

### Which ClickHouse versions are affected?

25.11

### How to reproduce

```
milovidov@Alekseis-MacBook-Pro Downloads % ch --time --query "*" <<< "test"
0.008
test
0.002
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by colesmith54**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Temporarily sets the print-time-to-stderr flag to false while processing the initial query. Closes #91532.

### CODE REVIEW

File: programs/local/LocalServer.cpp [hunk 1]
```diff
@@ -693,8 +693,15 @@ try
     connect();
 
     if (!table_name.empty())
+    {
+        bool orig_print_time_to_stderr = getClientConfiguration().getBool("print-time-to-stderr", false);
```
Comment (alexey-milovidov) [inline programs/local/LocalServer.cpp:698]: Missing comments.

**Review by alexey-milovidov — APPROVED** [review]
