### PR TITLE
Properly fix GCS when HMAC is used

### LINKED ISSUE #49195: GCS remote storage not working
When trying to use GCS as a remote disk we're getting the following error on start time. It's a clean installation from master:

```
2023.04.26 15:58:37.783837 [ 8125391 ] {} <Information> AWSClient: Response status: 400, Bad Request
2023.04.26 15:58:37.784129 [ 8125391 ] {} <Information> AWSClient: AWSErrorMarshaller: Encountered Unknown AWSError 'MalformedSecurityHeader': Your request has a malformed header.
2023.04.26 15:58:37.784211 [ 8125391 ] {} <Information> AWSClient: AWSXmlClient: HTTP response code: 400
Resolved remote host IP address: 142.250.200.80:443
Request ID:
Exception name: MalformedSecurityHeader
Error message: Unable to parse ExceptionName: MalformedSecurityHeader Message: Your request has a malformed header.
7 response headers:
alt-svc : h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
connection : close
content-length : 276
content-type : application/xml; charset=UTF-8
date : Wed, 26 Apr 2023 13:58:37 GMT
server : UploadServer
x-guploader-uploadid : ADPycdsPvXPSvOiHmc9xrGLTlm2sQJmyHr9Jc2lUS7-3E6so0vDaUVukRfr4Ya0JOwpnT31w2--gLCg0oPVwrLvsCNNUHw
2023.04.26 15:58:37.891542 [ 8125391 ] {} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
```

Reverting to previous versions solves the issues, looks like the issue was introduced in https://github.com/ClickHouse/ClickHouse/pull/48981

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Correctly modify GCS requests when `HMAC` key is used.

Fix https://github.com/ClickHouse/ClickHouse/issues/49195

cc @Algunenano @vitlibar 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 8c91dbdfc6290ede79039db22a213ac1bdff6f2b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49390/8c91dbdfc6290ede79039db22a213ac1bdff6f2b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by Algunenano** [comment]
I've done a couple of quick tests with GCS (setting up an s3 disk and reading a parquet file) with this PR and didn't see any problem so far.

File: src/IO/S3/Client.cpp [hunk 1]
```diff
@@ -421,9 +456,23 @@ Client::doRequest(const RequestType & request, RequestFn request_fn) const
     throw Exception(ErrorCodes::TOO_MANY_REDIRECTS, "Too many redirects");
 }
 
-ProviderType Client::getProviderType() const
+bool Client::supportsMultiPartCopy() const
 {
-    return provider_type;
+    return provider_type != ProviderType::GCS;
+}
```
Comment (jrdi) [inline src/IO/S3/Client.cpp:462]: Nitpicking: Unrelated to this PR but worth understanding some implications when using GCS. Why do we disable multipart upload in GCS? I thought this was already supported and the "only" missing big difference between GCS and S3 was the multi-delete.

> This page discusses XML API multipart uploads in Cloud Storage. This upload method uploads files in parts and then assembles them into a single object using a final request. XML API multipart uploads are compatible with Amazon S3 multipart uploads.

https://cloud.google.com/storage/docs/multipart-uploads

Comment (antonio2368) [reply src/IO/S3/Client.cpp:462]: We don't disable multipart upload but multipart **native copy**.
This is not supported by GCS so we have to try to do single part **native copy** and if it fails fallback to upload instead of multipart native copy as we do for AWS.
You can read some things left to do in the previous PR description https://github.com/ClickHouse/ClickHouse/pull/48981

The only difference is that GCS support team confirmed that they don't have a limit of 5GB for a single part native copy so we will probably remove the limit if GCS is used.
Additional problem is the need to [compose](https://cloud.google.com/storage/docs/xml-api/put-object-compose) a file uploaded with multi part upload before it can be copied natively but it returns 503 in some cases. This was also confirmed to be a problem on their side but I prepared a PR for it and will push it once it's resolved.

Comment (antonio2368) [reply src/IO/S3/Client.cpp:462]: Until all the improvements are made it's important to be aware that backup **could** be slower than AWS in some cases.

Comment (jrdi) [reply src/IO/S3/Client.cpp:462]: Great, thank you @antonio2368!

**Review by vitlibar — APPROVED** [review]

File: src/IO/S3/ProviderType.h [hunk 2]
```diff
@@ -19,9 +19,13 @@ enum class ProviderType : uint8_t
 
 std::string_view toString(ProviderType provider_type);
 
-bool supportsMultiPartCopy(ProviderType provider_type);
+enum class ApiMode : uint8_t
+{
+    AWS,
+    GCS
```
Comment (vitlibar) [inline src/IO/S3/ProviderType.h:25]: Can you please provide some comments about the enum and its constants?

Comment (antonio2368) [reply src/IO/S3/ProviderType.h:37]: done

File: src/IO/S3/Client.cpp (hunk 1 above)
Comment (azat) [reply src/IO/S3/Client.cpp:462]: @antonio2368 maybe worth to auto-detect this feature, like `DeleteObjects`?
https://github.com/ClickHouse/ClickHouse/blob/353791b2dd9e7f309f2a4b300c701cd32c1bf9df/src/Disks/ObjectStorages/S3/registerDiskS3.cpp#L41

Since there can be other provides that will not support some features.

Comment (antonio2368) [reply src/IO/S3/Client.cpp:462]: yes, that sounds like a better solution
maybe combine it and do it if the provider type is UNKNOWN because we already know best on URL for AWS and GCS
