### PR TITLE
Fix incorrect free space accounting for least_used JBOD policy

### LINKED ISSUE #47415: What's the time of disk swifting  to another in least_used disk policy
HI:
        We configed 2 disk in a volume and the load_balance is least_used.Our db have only mergetree engine table and
observed that the disk switch is performed only when one disk is about 50G more than the remaining space of the other disk. But I see the source code of clickhouse, when  reserve new part, it will compare the unreserved space between two disks and chose new disk. So I think the disk switch should‘t be so slowly. What's the  exact condition or time when the write switch from one disk to another?
        The following graph shows free space of our two disk that ClickHouse is writing:

image

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect free space accounting for `least_used` JBOD policy

Before least_used fails to detect when the disk started to have more
space, it works only when the disk starts to have less space.

The reason for this is that it uses priority_queue, and once the disk
goes at the bottom of the queue, free space will not be updated for it
until it will be selected again.

Follow-up for: #36686 (cc @serxa )
Fixes: #47415

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit c2ede069e9f1a7a7f9880bb0b22e8e2a0f5ca88b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56030/c2ede069e9f1a7a7f9880bb0b22e8e2a0f5ca88b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6646118296">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56030/c2ede069e9f1a7a7f9880bb0b22e8e2a0f5ca88b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by den-crane** [comment]
I believe the problem exists even if Clickhouse uses a disk.
Least_Used does not detect that a disk got free space because a table was truncated or a merge has finished and has returned reserved space.

File: src/Disks/VolumeJBOD.cpp [hunk 1]
```diff
@@ -76,6 +76,7 @@ VolumeJBOD::VolumeJBOD(
     perform_ttl_move_on_insert = config.getBool(config_prefix + ".perform_ttl_move_on_insert", true);
 
     are_merges_avoided = config.getBool(config_prefix + ".prefer_not_to_merge", false);
+    least_used_ttl_ms = config.getUInt64(config_prefix + ".least_used_ttl_ms", 60);
```
Comment (vitaliyf) [inline src/Disks/VolumeJBOD.cpp:79]: If it's `_ms` then should the default value be 60000 if you meant 60 seconds?

Comment (azat) [reply src/Disks/VolumeJBOD.cpp]: Yep, nice catch, thanks.

**Comment by azat** [comment]
@den-crane you are indeed right, and actually even reservations is not 100% accurate, so eventually even without removing data from disks you likely will have problems.

**Comment by serxa** [comment]
Is it really worth introducing a new setting? Maybe some good constant would be enough?

File: src/Disks/VolumeJBOD.cpp [hunk 2]
```diff
@@ -101,6 +102,11 @@ DiskPtr VolumeJBOD::getDisk(size_t /* index */) const
         case VolumeLoadBalancing::LEAST_USED:
         {
             std::lock_guard lock(mutex);
+            if (!least_used_ttl_ms || least_used_update_watch.elapsedMilliseconds() >= least_used_ttl_ms)
+            {
+                disks_by_size = LeastUsedDisksQueue(disks.begin(), disks.end());
+                least_used_update_watch.restart();
```
Comment (serxa) [inline src/Disks/VolumeJBOD.cpp:108]: Feel like a small repetition of the same logic and below. Let's extract it into a method.

**Comment by azat** [comment]
>Is it really worth introducing a new setting? Maybe some good constant would be enough?

I would prefer to keep it, because at least for tests it make sense to turn it off (set to zero).
Actually, in case of few disks only caching this values is not that important, it became more of a problem when you have multiple of them.

File: src/Disks/VolumeJBOD.cpp (hunk 2 above)
Comment (azat) [reply src/Disks/VolumeJBOD.cpp:108]: The problem is that it requires mutex, and TSA does not understand the it is held in the outer scope, so you can't write something like this:

```patch
bool VolumeJBOD::updateDisksSizesIfExpired(std::lock_guard<std::mutex> &) const
{
    if (!least_used_ttl_ms || least_used_update_watch.elapsedMilliseconds() >= least_used_ttl_ms)
    {
        disks_by_size = LeastUsedDisksQueue(disks.begin(), disks.end());
        least_used_update_watch.restart();
        return true;
    }
    return false;
}
````

It could be done by a) removing TSA annotation and b) re-holding the lock, but I doubt that this complexity worth it. @serxa What do you think?

Comment (serxa) [reply src/Disks/VolumeJBOD.cpp:108]: Ufff... TSA makes us do weird stuff... Okay, let's keep it is!

**Comment by serxa** [comment]
Suspicious. Might it be related? https://s3.amazonaws.com/clickhouse-test-reports/56030/331f661322ee0b12ec41cec8cba36b9973a6aa5a/integration_tests_flaky_check__asan_.html

**Comment by azat** [comment]
It should not be, since the server even did not started, looks like 900 seconds is not enough to pull the images...

But let's restart the CI just in case.

**Comment by den-crane** [comment]
BTW, I tested it manually, works perfectly, as expected least_used_ttl_ms=60 and least_used_ttl_ms=0

**Comment by azat** [comment]
> Integration tests (asan) [3/6] — fail: 2, passed: 294
> Integration tests (asan, analyzer) [3/6] — fail: 2, passed: 291
> Integration tests (release) [3/4] — fail: 2, passed: 608
> Integration tests (release) [4/4] — fail: 1, passed: 636
> Integration tests (tsan) [3/6] — fail: 2, passed: 294

- `test_format_schema_on_server` - https://github.com/ClickHouse/ClickHouse/pull/56116
- `test_delayed_replica_failover/test.py::test` - flaky

>Stateless tests (ubsan) [1/2] — Some queries hung, fail: 1, passed: 2852, skipped: 25

- `01104_distributed_numbers_test` - flaky
