### PR TITLE
Avoid msan issues on Time parsing

### LINKED ISSUE #82477: MSAN use-of-uninitialized-value on toTime function
### Describe the bug

From this run: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=3f9ed5e33d5c130721d88f9987713bf83462fa12&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_msan%29

### How to reproduce

On a MSAN build run:

```sql
SELECT toTime('default', 1) SETTINGS use_legacy_to_time = false;
```

### Error message and/or stacktrace

Stack trace:

```
==2804647==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x555586f723b0 in void DB::readTimeTextImpl<void>(DB::Time64&, unsigned int, DB::ReadBuffer&, DateLUTImpl const&, char const*, char const*) (clickhouse+0x31a1e3b0) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #1 0x555587a4013c in DB::readTime64Text(DB::Time64&, unsigned int, DB::ReadBuffer&, DateLUTImpl const&) ci/tmp/build/./src/IO/ReadHelpers.h:1440:5
    #2 0x555587a4013c in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::detail::ConvertThroughParsing<DB::DataTypeString, DB::DataTypeTime64, DB::detail::NameToTime, (DB::detail::ConvertFromStringExceptionMode)0, (DB::detail::ConvertFromStringParsingMode)0>::execute<unsigned int>(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, std::__1::shared_ptr<DB::Context const> const&, unsigned int) ci/tmp/build/./src/Functions/FunctionsConversion.h:1324:25
    #3 0x555587a3f030 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::detail::ConvertImpl<DB::DataTypeString, DB::DataTypeTime64, DB::detail::NameToTime, (DB::FormatSettings::DateTimeOverflowBehavior)0>::execute<unsigned int>(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, DB::detail::BehaviourOnErrorFromString, std::__1::shared_ptr<DB::Context const> const&, unsigned int) ci/tmp/build/./src/Functions/FunctionsConversion.h:2078:25
    #4 0x555587a15365 in bool DB::detail::FunctionConvert<DB::DataTypeTime, DB::detail::NameToTime, DB::detail::ToDateTimeMonotonicity<DB::DataTypeTime>>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, DB::detail::BehaviourOnErrorFromString)::operator()<DB::TypePair<DB::DataTypeString, DB::DataTypeTime64>>(auto const&, DB::detail::BehaviourOnErrorFromString) const ci/tmp/build/./src/Functions/FunctionsConversion.h:2998:41
    #5 0x5555879af05d in bool DB::callOnIndexAndDataType<DB::DataTypeTime64, DB::detail::FunctionConvert<DB::DataTypeTime, DB::detail::NameToTime, DB::detail::ToDateTimeMonotonicity<DB::DataTypeTime>>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, DB::detail::BehaviourOnErrorFromString)&, DB::detail::BehaviourOnErrorFromString>(DB::TypeIndex, DB::detail::FunctionConvert<DB::DataTypeTime, DB::detail::NameToTime, DB::detail::ToDateTimeMonotonicity<DB::DataTypeTime>>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, DB::detail::BehaviourOnErrorFromString)&, DB::detail::BehaviourOnErrorFromString&&) ci/tmp/build/./src/Core/callOnTypeIndex.h:290:48
    #6 0x5555879af05d in DB::detail::FunctionConvert<DB::DataTypeTime, DB::detail::NameToTime, DB::detail::ToDateTimeMonotonicity<DB::DataTypeTime>>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const ci/tmp/build/./src/Functions/FunctionsConversion.h:3098:26
    #7 0x5555879ad801 in DB::detail::FunctionConvert<DB::DataTypeTime, DB::detail::NameToTime, DB::detail::ToDateTimeMonotonicity<DB::DataTypeTime>>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const ci/tmp/build/./src/Functions/FunctionsConversion.h:2896:20
    #8 0x55555e7c6d41 in DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (clickhouse+0x9272d41) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #9 0x555586719c1a in DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const ci/tmp/build/./src/Functions/IFunctionAdaptors.cpp:16:22
    #10 0x555586706402 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (clickhouse+0x311b2402) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #11 0x555586705251 in DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (clickhouse+0x311b1251) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #12 0x5555867062d2 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (clickhouse+0x311b22d2) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #13 0x55558670b4fc in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (clickhouse+0x311b74fc) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #14 0x555586710765 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (clickhouse+0x311bc765) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #15 0x55558ad70b21 in DB::QueryAnalyzer::resolveFunction(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3656:47
    #16 0x55558ad0908f in DB::QueryAnalyzer::resolveExpressionNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:3930:46
    #17 0x55558ad05e79 in DB::QueryAnalyzer::resolveExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:4081:49
    #18 0x55558adac03f in DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:4405:40
    #19 0x55558acefa55 in DB::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:5764:30
    #20 0x55558acebc81 in DB::QueryAnalyzer::resolve(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::IQueryTreeNode> const&, std::__1::shared_ptr<DB::Context const>) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:181:13
    #21 0x55558acea398 in DB::QueryAnalysisPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>&, std::__1::shared_ptr<DB::Context const>) ci/tmp/build/./src/Analyzer/Resolve/QueryAnalysisPass.cpp:18:14
    #22 0x55558ae6d878 in DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) ci/tmp/build/./src/Analyzer/QueryTreePassManager.cpp:187:20
    #23 0x55558dea9763 in DB::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::shared_ptr<DB::IStorage> const&) ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:165:33
    #24 0x55558dea248d in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:182:18
    #25 0x55558deac9d1 in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:ne190107]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634:30
    #26 0x55558deac512 in DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0::operator()(DB::InterpreterFactory::Arguments const&) const ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:307:16
    #27 0x55558deac512 in decltype(std::declval<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&>()(std::declval<DB::InterpreterFactory::Arguments const&>())) std::__1::__invoke[abi:ne190107]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25
    #28 0x55558deac512 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>>, false>::__call[abi:ne190107]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:216:12
    #29 0x55558deac512 in std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:ne190107](DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12
    #30 0x55558deac512 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl[abi:ne190107]<std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12
    #31 0x55558dd1340e in std::__1::__function::__policy_func<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:ne190107](DB::InterpreterFactory::Arguments const&) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12
    #32 0x55558dd1340e in std::__1::function<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()(DB::InterpreterFactory::Arguments const&) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10
    #33 0x55558dd1340e in DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) ci/tmp/build/./src/Interpreters/InterpreterFactory.cpp:393:12
    #34 0x55558e9c7cac in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::__1::shared_ptr<DB::IAST>&) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1455:66
    #35 0x55558e9ba1eb in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1715:11
    #36 0x555596333a8a in DB::TCPHandler::runImpl() ci/tmp/build/./src/Server/TCPHandler.cpp:721:68
    #37 0x55559639eb50 in DB::TCPHandler::run() ci/tmp/build/./src/Server/TCPHandler.cpp:2727:9
    #38 0x55559ca7205f in Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3
    #39 0x55559ca72f91 in Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38
    #40 0x55559c94b799 in Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14
    #41 0x55559c9485ad in Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11
    #42 0x55559c945130 in Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #43 0x7ffff7ca2ef0 in start_thread nptl/pthread_create.c:448:8
    #44 0x7ffff7d3445b in __GI___clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

  Uninitialized value was created by a heap allocation
    #0 0x55555e754e72 in malloc (clickhouse+0x9200e72) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #1 0x5555791781f8 in void* (anonymous namespace)::allocNoTrack<false, false>(unsigned long, unsigned long) ci/tmp/build/./src/Common/Allocator.cpp:111:19
    #2 0x5555791781f8 in Allocator<false, false>::alloc(unsigned long, unsigned long) ci/tmp/build/./src/Common/Allocator.cpp:167:18
    #3 0x55555e7d79d1 in void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long) (clickhouse+0x92839d1) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77)
    #4 0x55558dabfd86 in DB::ColumnString::insert(DB::Field const&) ci/tmp/build/./src/Columns/ColumnString.h:141:15
    #5 0x555589bceed8 in DB::IDataType::createColumnConst(unsigned long, DB::Field const&) const ci/tmp/build/./src/DataTypes/IDataType.cpp:76:13
    #6 0x55558a9909fa in DB::ConstantValue::ConstantValue(DB::Field const&, std::__1::shared_ptr<DB::IDataType const>) ci/tmp/build/./src/Analyzer/ConstantValue.h:20:30
    #7 0x55558a9909fa in DB::ConstantNode::ConstantNode(DB::Field, std::__1::shared_ptr<DB::IDataType const>) ci/tmp/build/./src/Analyzer/ConstantNode.cpp:46:20
    #8 0x55558a990ebc in DB::ConstantNode::ConstantNode(DB::Field) ci/tmp/build/./src/Analyzer/ConstantNode.cpp:50:7
    #9 0x55558ac8666e in DB::ConstantNode* std::__1::construct_at[abi:ne190107]<DB::ConstantNode, DB::Field const&, DB::ConstantNode*>(DB::ConstantNode*, DB::Field const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:41:46
    #10 0x55558ac8666e in DB::ConstantNode* std::__1::__construct_at[abi:ne190107]<DB::ConstantNode, DB::Field const&, DB::ConstantNode*>(DB::ConstantNode*, DB::Field const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:49:10
    #11 0x55558ac8666e in void std::__1::allocator_traits<std::__1::allocator<DB::ConstantNode>>::construct[abi:ne190107]<DB::ConstantNode, DB::Field const&, void, 0>(std::__1::allocator<DB::ConstantNode>&, DB::ConstantNode*, DB::Field const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:328:5
    #12 0x55558ac8666e in std::__1::__shared_ptr_emplace<DB::ConstantNode, std::__1::allocator<DB::ConstantNode>>::__shared_ptr_emplace[abi:ne190107]<DB::Field const&, std::__1::allocator<DB::ConstantNode>, 0>(std::__1::allocator<DB::ConstantNode>, DB::Field const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:264:5
    #13 0x55558ac8666e in std::__1::shared_ptr<DB::ConstantNode> std::__1::allocate_shared[abi:ne190107]<DB::ConstantNode, std::__1::allocator<DB::ConstantNode>, DB::Field const&, 0>(std::__1::allocator<DB::ConstantNode> const&, DB::Field const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:843:51
    #14 0x55558ac4707a in std::__1::shared_ptr<DB::ConstantNode> std::__1::make_shared[abi:ne190107]<DB::ConstantNode, DB::Field const&, 0>(DB::Field const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:851:10
    #15 0x55558ac4707a in DB::(anonymous namespace)::QueryTreeBuilder::buildExpression(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:627:22
    #16 0x55558ac48eaf in DB::(anonymous namespace)::QueryTreeBuilder::buildExpression(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:701:76
    #17 0x55558ac43f1b in DB::(anonymous namespace)::QueryTreeBuilder::buildExpressionList(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:588:32
    #18 0x55558ac57355 in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:339:51
    #19 0x55558ac41ca9 in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectOrUnionExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:163:22
    #20 0x55558ac4d460 in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectWithUnionExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:181:16
    #21 0x55558ac419a1 in DB::(anonymous namespace)::QueryTreeBuilder::buildSelectOrUnionExpression(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&) const ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:159:22
    #22 0x55558ac3e821 in DB::(anonymous namespace)::QueryTreeBuilder::buildQueryTreeNode(std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context const>) ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:141:27
    #23 0x55558ac3e821 in DB::buildQueryTree(std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context const>) ci/tmp/build/./src/Analyzer/QueryTreeBuilder.cpp:1160:20
    #24 0x55558dea918d in DB::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::shared_ptr<DB::IStorage> const&) ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:153:23
    #25 0x55558dea248d in DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:182:18
    #26 0x55558deac9d1 in std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:ne190107]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634:30
    #27 0x55558deac512 in DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0::operator()(DB::InterpreterFactory::Arguments const&) const ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:307:16
    #28 0x55558deac512 in decltype(std::declval<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&>()(std::declval<DB::InterpreterFactory::Arguments const&>())) std::__1::__invoke[abi:ne190107]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25
    #29 0x55558deac512 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>>, false>::__call[abi:ne190107]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:216:12
    #30 0x55558deac512 in std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::operator()[abi:ne190107](DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12
    #31 0x55558deac512 in std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl[abi:ne190107]<std::__1::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::__1::unique_ptr<DB::IInterpreter, std::__1::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12

SUMMARY: MemorySanitizer: use-of-uninitialized-value (clickhouse+0x31a1e3b0) (BuildId: 6f9cbd44e989587eddc3dabd161ec182d9d41f77) in void DB::readTimeTextImpl<void>(DB::Time64&, unsigned int, DB::ReadBuffer&, DateLUTImpl const&, char const*, char const*)
```

### PR DESCRIPTION
**Pull request by yariks5s**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes cases where parsing of Time could cause msan issues. This fixes: https://github.com/ClickHouse/ClickHouse/issues/82477

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/IO/ReadHelpers.h [hunk 1]
```diff
@@ -1323,40 +1345,78 @@ inline ReturnType readDateTimeTextImpl(DateTime64 & datetime64, UInt32 scale, Re
...
+        }
+        catch (const DB::Exception & e)
+        {
+            // Check if we can continue with fractional part parsing
+            if (buf.eof() || *buf.position() != '.')
             {
-                if (buf.eof() || *buf.position() != '.')
-                    throw;
+                // Reset buffer position to initial state before throwing
+                buf.position() = initial_position;
```
Comment (Avogar) [inline src/IO/ReadHelpers.h]: Why do we need to reset it to the initial position here? And if we reload data in buffer during `readTimeTextImpl` `initial_position` might become invalid, or no?

File: src/IO/ReadHelpers.h [hunk 2]
```diff
@@ -1323,40 +1345,78 @@ inline ReturnType readDateTimeTextImpl(DateTime64 & datetime64, UInt32 scale, Re
...
+    {
+        auto ok = readTimeTextImpl<ReturnType, true>(whole, buf, date_lut, allowed_date_delimiters, allowed_time_delimiters);
+        parse_success = ok;
+        if (!ok && (buf.eof() || *buf.position() != '.'))
         {
-            auto ok = readTimeTextImpl<ReturnType, true>(whole, buf, date_lut, allowed_date_delimiters, allowed_time_delimiters);
-            if (!ok && (buf.eof() || *buf.position() != '.'))
-                return ReturnType(false);
+            // reset buffer position to initial state
+            buf.position() = initial_position;
```
Comment (Avogar) [inline src/IO/ReadHelpers.h]: The same question here

File: src/IO/ReadHelpers.h (hunk 1 above)
Comment (yariks5s) [reply src/IO/ReadHelpers.h]: I wanted to have a possibility to address used buffer on throw, but as soon as we don't really need it now, I will remove these concerning parts.

**Review by Avogar — APPROVED** [review]

**Comment by yariks5s** [comment]
[Stateless tests (amd_binary, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82514&sha=2d4c80fffc3463878d242fe8f5685a2c6dc2e461&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%29) - https://github.com/ClickHouse/ClickHouse/issues/80811

[Integration tests (release, 3/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82514&sha=2d4c80fffc3463878d242fe8f5685a2c6dc2e461&name_0=PR&name_1=Integration%20tests%20%28release%2C%203%2F4%29) - https://github.com/ClickHouse/ClickHouse/issues/82750

[Integration tests (asan, old analyzer, 4/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82514&sha=2d4c80fffc3463878d242fe8f5685a2c6dc2e461&name_0=PR&name_1=Integration%20tests%20%28asan%2C%20old%20analyzer%2C%204%2F6%29) — Job timeout expired -- https://github.com/ClickHouse/ClickHouse/issues/82674

[Upgrade check (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82514&sha=2d4c80fffc3463878d242fe8f5685a2c6dc2e461&name_0=PR&name_1=Upgrade%20check%20%28amd_debug%29) -- not related setting, failing on master
