### PR TITLE
Fix crash when Merge table wraps Distributed with distributed_group_by_no_merge=1

### LINKED ISSUE #75604: Logical error: 'Queries with distributed_group_by_no_merge=1 should be processed to Complete stage'.
```
CREATE TABLE first_table_lr (`id` String, `id2` String) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{database}/test_03080/alter', 'r1') ORDER BY id;
CREATE TABLE first_table (`id` String, `id2` String) ENGINE = Distributed('test_shard_localhost', currentDatabase(), 'first_table_lr');
CREATE TABLE two_tables (`id` String, `id2` String) ENGINE = Merge(currentDatabase(), '^(first_table)$');

CREATE TABLE second_table_lr (`id` String, `id2` String) ENGINE = MergeTree ORDER BY id;
CREATE TABLE second_table (`id` String, `id2` String) ENGINE = Distributed('test_shard_localhost', currentDatabase(), 'second_table_lr');

insert into first_table_lr values ('foo', 'bar');
insert into second_table_lr values ('foo', 'bar');
```

```

SET max_block_size = 1048576, max_threads = 2, receive_timeout = 10., receive_data_timeout_ms = 10000, s3_truncate_on_insert = true, distributed_foreground_insert = true, allow_suspicious_low_cardinality_types = true, group_by_two_level_threshold = 1, group_by_two_level_threshold_bytes = 50000000, distributed_group_by_no_merge = 1, optimize_skip_unused_shards = true, force_optimize_skip_unused_shards = 2, force_optimize_skip_unused_shards_nesting = 1, log_queries = true, insert_quorum = 1, table_function_remote_max_addresses = 200, final = true, max_rows_to_read = 5001, max_bytes_before_external_group_by = 100000000, max_bytes_ratio_before_external_group_by = 0., min_external_sort_block_bytes = 10485760, max_bytes_before_external_sort = 33554432, max_bytes_ratio_before_external_sort = 0., max_execution_time = 10., max_bytes_in_join = 10000000, join_algorithm = 'partial_merge', default_max_bytes_in_join = 0, max_memory_usage = 410000000, send_logs_level = 'fatal', allow_introspection_functions = true, default_table_engine = 'MergeTree', optimize_if_chain_to_multiif = true, optimize_use_projections = true, optimize_use_implicit_projections = true, allow_deprecated_database_ordinary = true, parallelize_output_from_storages = true, allow_create_index_without_type = true, create_index_ignore_unique = true, allow_experimental_analyzer = true, output_format_decimal_trailing_zeros = true, output_format_write_statistics = false;

SELECT count() FROM two_tables AS s GLOBAL ANY INNER JOIN second_table AS f USING (id) WHERE f.id2 GLOBAL IN (SELECT id2 FROM second_table GROUP BY id2);
```

```
2025.02.05 14:16:22.757918 [ 194 ] {97b96354-ca22-4631-9866-82042c9bd0f7} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. /build/contrib/llvm-project/libcxx/include/__exception/exception.h:106: Poco::Exception::Exception(String const&, int) @ 0x0000000018a8af12
1. /build/src/Common/Exception.cpp:106: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000ce16d59
2. /build/src/Common/Exception.h:105: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007741a0c
3. /build/src/Common/Exception.h:123: DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000077449eb
4. /build/src/Storages/StorageDistributed.cpp:483: DB::StorageDistributed::getQueryProcessingStage(std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&) const @ 0x0000000013d61475
5. /build/src/Storages/StorageMerge.cpp:1134: DB::ReadFromMerge::createPlanForTable(std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, DB::QueryProcessingStage::Enum, unsigned long, std::tuple<String, std::shared_ptr<DB::IStorage>, std::shared_ptr<DB::RWLockImpl::LockHolderImpl>, String> const&, std::vector<String, std::allocator<String>> const&>
6. /build/src/Storages/StorageMerge.cpp:707: DB::ReadFromMerge::createChildrenPlans(DB::SelectQueryInfo&) const @ 0x0000000013e3e2d9
7. /build/src/Storages/StorageMerge.cpp:567: DB::ReadFromMerge::filterTablesAndCreateChildrenPlans() @ 0x0000000013e3abb7
8. /build/src/Storages/StorageMerge.cpp:1581: DB::ReadFromMerge::applyFilters(DB::ActionDAGNodes) @ 0x0000000013e48e7f
9. /build/src/Processors/QueryPlan/SourceStepWithFilter.h:39: DB::SourceStepWithFilterBase::applyFilters() @ 0x0000000014ebc33d
10. /build/src/Processors/QueryPlan/Optimizations/optimizePrimaryKeyConditionAndLimit.cpp:50: DB::QueryPlanOptimizations::optimizePrimaryKeyConditionAndLimit(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>> const&) @ 0x0000000014ebc1dd
11. /build/src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:119: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000014ebac93
12. /build/src/Processors/QueryPlan/QueryPlan.cpp:490: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x0000000014e19580
13. /build/src/Processors/QueryPlan/QueryPlan.cpp:175: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x0000000014e18e87
14. /build/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:274: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x00000000129d5311
15. /build/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:241: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x00000000129d509e
16. /build/src/Interpreters/executeQuery.cpp:1455: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x0000000012d0c2aa
17. /build/src/Interpreters/executeQuery.cpp:1621: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000012d07c6b
18. /build/src/Server/TCPHandler.cpp:662: DB::TCPHandler::runImpl() @ 0x0000000014921f7d
19. /build/src/Server/TCPHandler.cpp:2624: DB::TCPHandler::run() @ 0x000000001493a119
20. /build/base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000018b30427
21. /build/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000018b308fe
22. /build/base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000018adb732
23. /build/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000018ad9323
24. ? @ 0x00007fbdeb2d2ac3
25. ? @ 0x00007fbdeb364850
```

Previous: https://github.com/ClickHouse/ClickHouse/issues/65205
CI: https://s3.amazonaws.com/clickhouse-test-reports/75477/fb72fd6d35652cd5e7ffa8e14d363c7ae8931c89/ast_fuzzer__debug_.html

### PR DESCRIPTION
**Pull request by groeneai**
When a `Merge` table (or the `merge()` table function) references multiple underlying tables, and one of them is a `Distributed` table, queries crash with a `LOGICAL_ERROR` if `distributed_group_by_no_merge=1` is set:

```
Logical error: 'Queries with distributed_group_by_no_merge=1 should be processed to Complete stage'
```

**Root cause:** `StorageMerge::getQueryProcessingStage()` caps the processing stage to `WithMergeableState` when there are multiple underlying tables (line 415). When `createPlanForTable()` then calls `StorageDistributed::getQueryProcessingStage()` with this capped `to_stage=WithMergeableState`, the assertion at line 516 fires because it requires `to_stage == Complete`.

**Fix:** The assertion was too strict. With `distributed_group_by_no_merge=1`, each shard processes the full query independently and the initiator concatenates results. `StorageDistributed` can always return `Complete` regardless of the requested `to_stage` — the caller (`StorageMerge`) correctly handles `storage_stage > processed_stage` via the condition at line 1273.

**Reproducer (from issue):**
```sql
CREATE TABLE t30 (c0 Int) ENGINE = MergeTree() ORDER BY c0;
CREATE TABLE t31 (c0 Int) ENGINE = Distributed('test_shard_localhost', currentDatabase(), 't30');
CREATE TABLE t32 (c0 Int) ENGINE = Memory;
SELECT 1 FROM merge(currentDatabase(), '^t3[12]$') SETTINGS distributed_group_by_no_merge = 1;
-- Crashes with LOGICAL_ERROR
```

Closes #75604

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash (`LOGICAL_ERROR`) when querying a `Merge` table (or `merge()` table function) that wraps multiple tables including a `Distributed` table, with `distributed_group_by_no_merge=1` enabled.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.671`

### CODE REVIEW

File: src/Storages/StorageDistributed.cpp [hunk 1]
```diff
@@ -512,9 +512,13 @@ QueryProcessingStage::Enum StorageDistributed::getQueryProcessingStage(
...
-            throw Exception(
-                ErrorCodes::LOGICAL_ERROR, "Queries with distributed_group_by_no_merge=1 should be processed to Complete stage");
+        ///
+        /// We always return Complete here regardless of to_stage, because with
+        /// distributed_group_by_no_merge=1 each shard processes the full query
+        /// independently and the initiator just concatenates results.
+        /// The caller may request a lower stage (e.g. StorageMerge passes
+        /// WithMergeableState when it wraps multiple tables), but that's fine —
+        /// the caller handles storage_stage > processed_stage correctly.
         return QueryProcessingStage::Complete;
```
Comment (azat) [inline src/Storages/StorageDistributed.cpp:522]: This is not enough, Merge also should be aware - https://github.com/ClickHouse/ClickHouse/pull/105330

Comment (groeneai) [reply src/Storages/StorageDistributed.cpp:522]: Agreed, my fix only covered same-type aggregates (count, sum) where the WithMergeableState and Complete column types coincide. Your follow-up correctly handles the remaining nested-Merge case where state-bearing aggregates (uniqExact, avg, groupArray, ...) hit CANNOT_CONVERT_TYPE.

Both halves look right:
1. StorageMerge single-table branch capping at WithMergeableState mirrors the multi-table cap on the same line.
2. std::max(to_stage, Complete) in StorageDistributed avoids silently downgrading WithMergeableStateAfterAggregation(/AndLimit) callers, which my original Complete return swallowed.

Test 04256 is a strict superset of 04064. Happy to help review #105330.

FYI: 01227_distributed_merge_global_in_primary_key just failed on your distributed-plan CI jobs. It looks like a pre-existing flake on that build family: 5 hits on #102192, 2 hits on #100226 over 30 days, 0 on master. Probably not yours.
