### PR TITLE
Fix possible crash during shutting down background pools

### LINKED ISSUE #80066: BackgroundSchedulePoolTaskInfo::deactivate() May report use-after-free issue if the owning pool is already destroyed
### Company or project name

Conviva

### Describe what's wrong

```cpp
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
=================================================================
==8==ERROR: AddressSanitizer: heap-use-after-free on address 0x5060000ad2a8 at pc 0x55865fc3c659 bp 0x7ffe965cf680 sp 0x7ffe965cf678
READ of size 8 at 0x5060000ad2a8 thread T0
    #0 0x55865fc3c658 in std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>* std::__1::__tree_next_iter[abi:ne190107]<std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>*, std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:196:12
    #1 0x55865fc3c658 in std::__1::__tree_iterator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*, long>::operator++[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:745:9
    #2 0x55865fc3c658 in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::__remove_node_pointer(std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:1911:3
    #3 0x55865fc3c658 in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::erase(std::__1::__tree_const_iterator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*, long>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:2041:28
    #4 0x55865fc2f61a in std::__1::multimap<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>, std::__1::less<Poco::Timestamp>, std::__1::allocator<std::__1::pair<Poco::Timestamp const, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::erase[abi:ne190107](std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*, long>>) ci/tmp/build/./contrib/llvm-project/libcxx/include/map:1890:71
    #5 0x55865fc2f61a in DB::BackgroundSchedulePool::cancelDelayedTask(DB::BackgroundSchedulePoolTaskInfo&, std::__1::lock_guard<std::__1::mutex>&) ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:273:23
    #6 0x55865fc2f61a in DB::BackgroundSchedulePoolTaskInfo::deactivate() ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:62:14
    #7 0x55865fc3ce09 in DB::BackgroundSchedulePoolTaskHolder::~BackgroundSchedulePoolTaskHolder() ci/tmp/build/./src/Core/BackgroundSchedulePoolTaskHolder.cpp:19:20
    #8 0x558660b4d671 in DB::DiskLocalCheckThread::~DiskLocalCheckThread() ci/tmp/build/./src/Disks/DiskLocalCheckThread.h:15:7
    #9 0x558660b4d671 in std::__1::default_delete<DB::DiskLocalCheckThread>::operator()[abi:ne190107](DB::DiskLocalCheckThread*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #10 0x558660b4d671 in std::__1::unique_ptr<DB::DiskLocalCheckThread, std::__1::default_delete<DB::DiskLocalCheckThread>>::reset[abi:ne190107](DB::DiskLocalCheckThread*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #11 0x558660b4d671 in std::__1::unique_ptr<DB::DiskLocalCheckThread, std::__1::default_delete<DB::DiskLocalCheckThread>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #12 0x558660b4d671 in DB::DiskLocal::~DiskLocal() ci/tmp/build/./src/Disks/DiskLocal.h:16:7
    #13 0x5586487b1592 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, void*>*) filesystem.cpp
    #14 0x5586487b14f1 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, void*>*) filesystem.cpp
    #15 0x558654a5d519 in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #16 0x558654a5d519 in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #17 0x558654a5d519 in std::__1::shared_ptr<DB::DiskSelector>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #18 0x558654a5d519 in DB::KeeperContext::~KeeperContext() ci/tmp/build/./src/Coordination/KeeperContext.h:32:7
    #19 0x558669a4c82b in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #20 0x558669a4c82b in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #21 0x558669a4c82b in std::__1::shared_ptr<DB::KeeperContext>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #22 0x558669a4c82b in DB::IKeeperStateMachine::~IKeeperStateMachine() ci/tmp/build/./src/Coordination/KeeperStateMachine.h:23:7
    #23 0x5586699579aa in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #24 0x5586699579aa in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #25 0x5586699579aa in std::__1::shared_ptr<DB::IKeeperStateMachine>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #26 0x5586699579aa in DB::KeeperServer::~KeeperServer() ci/tmp/build/./src/Coordination/KeeperServer.h:21:7
    #27 0x558669944613 in std::__1::default_delete<DB::KeeperServer>::operator()[abi:ne190107](DB::KeeperServer*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #28 0x558669944613 in std::__1::unique_ptr<DB::KeeperServer, std::__1::default_delete<DB::KeeperServer>>::reset[abi:ne190107](DB::KeeperServer*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #29 0x558669944613 in std::__1::unique_ptr<DB::KeeperServer, std::__1::default_delete<DB::KeeperServer>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #30 0x558669944613 in DB::KeeperDispatcher::~KeeperDispatcher() ci/tmp/build/./src/Coordination/KeeperDispatcher.cpp:658:1
    #31 0x558654924c0f in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #32 0x558654924c0f in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #33 0x558654924c0f in std::__1::shared_ptr<DB::KeeperDispatcher>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #34 0x558654924c0f in DB::KeeperTCPHandlerFactory::~KeeperTCPHandlerFactory() ci/tmp/build/./src/Server/KeeperTCPHandlerFactory.h:15:7
    #35 0x558654924c0f in DB::KeeperTCPHandlerFactory::~KeeperTCPHandlerFactory() ci/tmp/build/./src/Server/KeeperTCPHandlerFactory.h:15:7
    #36 0x55866859ff47 in Poco::ReleasePolicy<DB::TCPServerConnectionFactory>::release(DB::TCPServerConnectionFactory*) ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:58:9
    #37 0x55866859ff47 in Poco::SharedPtr<DB::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<DB::TCPServerConnectionFactory>>::release() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:296:13
    #38 0x55866859ff47 in Poco::SharedPtr<DB::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<DB::TCPServerConnectionFactory>>::~SharedPtr() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:129:13
    #39 0x55866859ff47 in DB::TCPServerConnectionFactoryImpl::~TCPServerConnectionFactoryImpl() ci/tmp/build/./src/Server/TCPServer.cpp:8:7
    #40 0x55866859ff47 in DB::TCPServerConnectionFactoryImpl::~TCPServerConnectionFactoryImpl() ci/tmp/build/./src/Server/TCPServer.cpp:8:7
    #41 0x558670ce8075 in Poco::ReleasePolicy<Poco::Net::TCPServerConnectionFactory>::release(Poco::Net::TCPServerConnectionFactory*) ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:58:9
    #42 0x558670ce8075 in Poco::SharedPtr<Poco::Net::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Net::TCPServerConnectionFactory>>::release() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:296:13
    #43 0x558670ce8075 in Poco::SharedPtr<Poco::Net::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Net::TCPServerConnectionFactory>>::~SharedPtr() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:129:13
    #44 0x558670ce8075 in Poco::Net::TCPServerDispatcher::~TCPServerDispatcher() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:79:1
    #45 0x558670ce81ed in Poco::Net::TCPServerDispatcher::~TCPServerDispatcher() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:78:1
    #46 0x558670ce6a0f in Poco::Net::TCPServer::~TCPServer() ci/tmp/build/./base/poco/Net/src/TCPServer.cpp:91:23
    #47 0x55866859fc53 in DB::TCPServer::~TCPServer() ci/tmp/build/./src/Server/TCPServer.h:31:7
    #48 0x55866859fc53 in DB::TCPServer::~TCPServer() ci/tmp/build/./src/Server/TCPServer.h:31:7
    #49 0x558668539195 in std::__1::default_delete<DB::TCPServer>::operator()[abi:ne190107](DB::TCPServer*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #50 0x558668539195 in std::__1::unique_ptr<DB::TCPServer, std::__1::default_delete<DB::TCPServer>>::reset[abi:ne190107](DB::TCPServer*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #51 0x558668539195 in std::__1::unique_ptr<DB::TCPServer, std::__1::default_delete<DB::TCPServer>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #52 0x558668539195 in DB::ProtocolServerAdapter::TCPServerAdapterImpl::~TCPServerAdapterImpl() ci/tmp/build/./src/Server/ProtocolServerAdapter.cpp:15:46
    #53 0x558668539195 in DB::ProtocolServerAdapter::TCPServerAdapterImpl::~TCPServerAdapterImpl() ci/tmp/build/./src/Server/ProtocolServerAdapter.cpp:15:46
    #54 0x558654d287c7 in std::__1::default_delete<DB::ProtocolServerAdapter::Impl>::operator()[abi:ne190107](DB::ProtocolServerAdapter::Impl*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #55 0x558654d287c7 in std::__1::unique_ptr<DB::ProtocolServerAdapter::Impl, std::__1::default_delete<DB::ProtocolServerAdapter::Impl>>::reset[abi:ne190107](DB::ProtocolServerAdapter::Impl*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #56 0x558654d287c7 in std::__1::unique_ptr<DB::ProtocolServerAdapter::Impl, std::__1::default_delete<DB::ProtocolServerAdapter::Impl>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #57 0x558654d287c7 in DB::ProtocolServerAdapter::~ProtocolServerAdapter() ci/tmp/build/./src/Server/ProtocolServerAdapter.h:18:7
    #58 0x558654d287c7 in void std::__1::__destroy_at[abi:ne190107]<DB::ProtocolServerAdapter, 0>(DB::ProtocolServerAdapter*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11
    #59 0x558654d287c7 in void std::__1::allocator_traits<std::__1::allocator<DB::ProtocolServerAdapter>>::destroy[abi:ne190107]<DB::ProtocolServerAdapter, void, 0>(std::__1::allocator<DB::ProtocolServerAdapter>&, DB::ProtocolServerAdapter*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5
    #60 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::__base_destruct_at_end[abi:ne190107](DB::ProtocolServerAdapter*) ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:985:7
    #61 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::__clear[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:979:5
    #62 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::__destroy_vector::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:530:16
    #63 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::~vector[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:541:67
    #64 0x558654d287c7 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./programs/server/Server.cpp:2759:1
    #65 0x558670d48a36 in Poco::Util::Application::run() ci/tmp/build/./base/poco/Util/src/Application.cpp:315:8
    #66 0x558654cfee79 in DB::Server::run() ci/tmp/build/./programs/server/Server.cpp:589:25
    #67 0x558654cf9fd8 in mainEntryClickHouseServer(int, char**) ci/tmp/build/./programs/server/Server.cpp:386:20
    #68 0x558643f928be in main ci/tmp/build/./programs/main.cpp:304:21
    #69 0x7f2d48d17d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #70 0x7f2d48d17e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #71 0x558643ebb02d in _start (/usr/bin/clickhouse+0xc22e02d) (BuildId: 4e009075232461e9244f6f3c6f9fd65b0aa9835a)

0x5060000ad2a8 is located 8 bytes inside of 56-byte region [0x5060000ad2a0,0x5060000ad2d8)
freed by thread T0 here:
    #0 0x558643f8f622 in operator delete(void*, unsigned long) (/usr/bin/clickhouse+0xc302622) (BuildId: 4e009075232461e9244f6f3c6f9fd65b0aa9835a)
    #1 0x55865fc3aa31 in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:1538:5
    #2 0x55865fc3584e in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::~__tree() ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:1532:3
    #3 0x55865fc3584e in std::__1::multimap<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>, std::__1::less<Poco::Timestamp>, std::__1::allocator<std::__1::pair<Poco::Timestamp const, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::~multimap[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/map:1810:117
    #4 0x55865fc3584e in DB::BackgroundSchedulePool::~BackgroundSchedulePool() ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:233:1
    #5 0x55866276b518 in std::__1::default_delete<DB::BackgroundSchedulePool>::operator()[abi:ne190107](DB::BackgroundSchedulePool*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #6 0x55866276b518 in std::__1::unique_ptr<DB::BackgroundSchedulePool, std::__1::default_delete<DB::BackgroundSchedulePool>>::reset[abi:ne190107](DB::BackgroundSchedulePool*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #7 0x55866276b518 in DB::ContextSharedPart::shutdown() ci/tmp/build/./src/Interpreters/Context.cpp:913:30
    #8 0x558654d5aa61 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_3::operator()() const ci/tmp/build/./programs/server/Server.cpp:1225:5
    #9 0x558654d5aa61 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_3>::invoke() ci/tmp/build/./base/base/../base/scope_guard.h:101:9
    #10 0x558654d286b2 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_3>::~BasicScopeGuard() ci/tmp/build/./base/base/../base/scope_guard.h:50:26
    #11 0x558654d286b2 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./programs/server/Server.cpp:2759:1
    #12 0x558670d48a36 in Poco::Util::Application::run() ci/tmp/build/./base/poco/Util/src/Application.cpp:315:8
    #13 0x558654cfee79 in DB::Server::run() ci/tmp/build/./programs/server/Server.cpp:589:25
    #14 0x558654cf9fd8 in mainEntryClickHouseServer(int, char**) ci/tmp/build/./programs/server/Server.cpp:386:20
    #15 0x558643f928be in main ci/tmp/build/./programs/main.cpp:304:21
    #16 0x7f2d48d17d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)

```
When I enabled the DiskLocalCheckThread, the triggered CI/CD reports above `use-after-free` error.

The error happened because:
1. The `BackgroundSchedulePool::~BackgroundSchedulePool()` are de-constructed by `ContextSharedPart::shutdown()`
2. When `DiskLocalCheckThread` is deconstructed, it will try to de-activate the `BackgroundSchedulePoolTaskInfo` of it and will call `BackgroundSchedulePool::cancelDelayedTask()` to cancel the delayed task.
3. Since the owning `BackgroundSchedulePool` is already deconstructed and the `BackgroundSchedulePoolTaskInfo` is just holding a bare pointer of `BackgroundSchedulePool` instance, so `BackgroundSchedulePoolTaskInfo::deactivate()` will report `use-after-free` error in below code:
```cpp
void BackgroundSchedulePoolTaskInfo::deactivate()
{
    std::lock_guard lock_exec(exec_mutex);
    std::lock_guard lock_schedule(schedule_mutex);

    if (deactivated)
        return;

    deactivated = true;
    scheduled = false;
    if (delayed)
        pool.cancelDelayedTask(*this, lock_schedule); // pool is already freed, report use-after-free error
}
```

### Does it reproduce on the most recent release?

No

### How to reproduce

When enabled 

### Expected behavior

_No response_

### Error message and/or stacktrace

```shell
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
=================================================================
==8==ERROR: AddressSanitizer: heap-use-after-free on address 0x5060000ad2a8 at pc 0x55865fc3c659 bp 0x7ffe965cf680 sp 0x7ffe965cf678
READ of size 8 at 0x5060000ad2a8 thread T0
    #0 0x55865fc3c658 in std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>* std::__1::__tree_next_iter[abi:ne190107]<std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>*, std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:196:12
    #1 0x55865fc3c658 in std::__1::__tree_iterator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*, long>::operator++[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:745:9
    #2 0x55865fc3c658 in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::__remove_node_pointer(std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:1911:3
    #3 0x55865fc3c658 in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::erase(std::__1::__tree_const_iterator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*, long>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:2041:28
    #4 0x55865fc2f61a in std::__1::multimap<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>, std::__1::less<Poco::Timestamp>, std::__1::allocator<std::__1::pair<Poco::Timestamp const, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::erase[abi:ne190107](std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*, long>>) ci/tmp/build/./contrib/llvm-project/libcxx/include/map:1890:71
    #5 0x55865fc2f61a in DB::BackgroundSchedulePool::cancelDelayedTask(DB::BackgroundSchedulePoolTaskInfo&, std::__1::lock_guard<std::__1::mutex>&) ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:273:23
    #6 0x55865fc2f61a in DB::BackgroundSchedulePoolTaskInfo::deactivate() ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:62:14
    #7 0x55865fc3ce09 in DB::BackgroundSchedulePoolTaskHolder::~BackgroundSchedulePoolTaskHolder() ci/tmp/build/./src/Core/BackgroundSchedulePoolTaskHolder.cpp:19:20
    #8 0x558660b4d671 in DB::DiskLocalCheckThread::~DiskLocalCheckThread() ci/tmp/build/./src/Disks/DiskLocalCheckThread.h:15:7
    #9 0x558660b4d671 in std::__1::default_delete<DB::DiskLocalCheckThread>::operator()[abi:ne190107](DB::DiskLocalCheckThread*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #10 0x558660b4d671 in std::__1::unique_ptr<DB::DiskLocalCheckThread, std::__1::default_delete<DB::DiskLocalCheckThread>>::reset[abi:ne190107](DB::DiskLocalCheckThread*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #11 0x558660b4d671 in std::__1::unique_ptr<DB::DiskLocalCheckThread, std::__1::default_delete<DB::DiskLocalCheckThread>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #12 0x558660b4d671 in DB::DiskLocal::~DiskLocal() ci/tmp/build/./src/Disks/DiskLocal.h:16:7
    #13 0x5586487b1592 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, void*>*) filesystem.cpp
    #14 0x5586487b14f1 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::shared_ptr<DB::IDisk>>, void*>*) filesystem.cpp
    #15 0x558654a5d519 in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #16 0x558654a5d519 in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #17 0x558654a5d519 in std::__1::shared_ptr<DB::DiskSelector>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #18 0x558654a5d519 in DB::KeeperContext::~KeeperContext() ci/tmp/build/./src/Coordination/KeeperContext.h:32:7
    #19 0x558669a4c82b in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #20 0x558669a4c82b in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #21 0x558669a4c82b in std::__1::shared_ptr<DB::KeeperContext>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #22 0x558669a4c82b in DB::IKeeperStateMachine::~IKeeperStateMachine() ci/tmp/build/./src/Coordination/KeeperStateMachine.h:23:7
    #23 0x5586699579aa in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #24 0x5586699579aa in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #25 0x5586699579aa in std::__1::shared_ptr<DB::IKeeperStateMachine>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #26 0x5586699579aa in DB::KeeperServer::~KeeperServer() ci/tmp/build/./src/Coordination/KeeperServer.h:21:7
    #27 0x558669944613 in std::__1::default_delete<DB::KeeperServer>::operator()[abi:ne190107](DB::KeeperServer*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #28 0x558669944613 in std::__1::unique_ptr<DB::KeeperServer, std::__1::default_delete<DB::KeeperServer>>::reset[abi:ne190107](DB::KeeperServer*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #29 0x558669944613 in std::__1::unique_ptr<DB::KeeperServer, std::__1::default_delete<DB::KeeperServer>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #30 0x558669944613 in DB::KeeperDispatcher::~KeeperDispatcher() ci/tmp/build/./src/Coordination/KeeperDispatcher.cpp:658:1
    #31 0x558654924c0f in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #32 0x558654924c0f in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #33 0x558654924c0f in std::__1::shared_ptr<DB::KeeperDispatcher>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #34 0x558654924c0f in DB::KeeperTCPHandlerFactory::~KeeperTCPHandlerFactory() ci/tmp/build/./src/Server/KeeperTCPHandlerFactory.h:15:7
    #35 0x558654924c0f in DB::KeeperTCPHandlerFactory::~KeeperTCPHandlerFactory() ci/tmp/build/./src/Server/KeeperTCPHandlerFactory.h:15:7
    #36 0x55866859ff47 in Poco::ReleasePolicy<DB::TCPServerConnectionFactory>::release(DB::TCPServerConnectionFactory*) ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:58:9
    #37 0x55866859ff47 in Poco::SharedPtr<DB::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<DB::TCPServerConnectionFactory>>::release() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:296:13
    #38 0x55866859ff47 in Poco::SharedPtr<DB::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<DB::TCPServerConnectionFactory>>::~SharedPtr() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:129:13
    #39 0x55866859ff47 in DB::TCPServerConnectionFactoryImpl::~TCPServerConnectionFactoryImpl() ci/tmp/build/./src/Server/TCPServer.cpp:8:7
    #40 0x55866859ff47 in DB::TCPServerConnectionFactoryImpl::~TCPServerConnectionFactoryImpl() ci/tmp/build/./src/Server/TCPServer.cpp:8:7
    #41 0x558670ce8075 in Poco::ReleasePolicy<Poco::Net::TCPServerConnectionFactory>::release(Poco::Net::TCPServerConnectionFactory*) ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:58:9
    #42 0x558670ce8075 in Poco::SharedPtr<Poco::Net::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Net::TCPServerConnectionFactory>>::release() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:296:13
    #43 0x558670ce8075 in Poco::SharedPtr<Poco::Net::TCPServerConnectionFactory, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Net::TCPServerConnectionFactory>>::~SharedPtr() ci/tmp/build/./base/poco/Foundation/include/Poco/SharedPtr.h:129:13
    #44 0x558670ce8075 in Poco::Net::TCPServerDispatcher::~TCPServerDispatcher() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:79:1
    #45 0x558670ce81ed in Poco::Net::TCPServerDispatcher::~TCPServerDispatcher() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:78:1
    #46 0x558670ce6a0f in Poco::Net::TCPServer::~TCPServer() ci/tmp/build/./base/poco/Net/src/TCPServer.cpp:91:23
    #47 0x55866859fc53 in DB::TCPServer::~TCPServer() ci/tmp/build/./src/Server/TCPServer.h:31:7
    #48 0x55866859fc53 in DB::TCPServer::~TCPServer() ci/tmp/build/./src/Server/TCPServer.h:31:7
    #49 0x558668539195 in std::__1::default_delete<DB::TCPServer>::operator()[abi:ne190107](DB::TCPServer*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #50 0x558668539195 in std::__1::unique_ptr<DB::TCPServer, std::__1::default_delete<DB::TCPServer>>::reset[abi:ne190107](DB::TCPServer*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #51 0x558668539195 in std::__1::unique_ptr<DB::TCPServer, std::__1::default_delete<DB::TCPServer>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #52 0x558668539195 in DB::ProtocolServerAdapter::TCPServerAdapterImpl::~TCPServerAdapterImpl() ci/tmp/build/./src/Server/ProtocolServerAdapter.cpp:15:46
    #53 0x558668539195 in DB::ProtocolServerAdapter::TCPServerAdapterImpl::~TCPServerAdapterImpl() ci/tmp/build/./src/Server/ProtocolServerAdapter.cpp:15:46
    #54 0x558654d287c7 in std::__1::default_delete<DB::ProtocolServerAdapter::Impl>::operator()[abi:ne190107](DB::ProtocolServerAdapter::Impl*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #55 0x558654d287c7 in std::__1::unique_ptr<DB::ProtocolServerAdapter::Impl, std::__1::default_delete<DB::ProtocolServerAdapter::Impl>>::reset[abi:ne190107](DB::ProtocolServerAdapter::Impl*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #56 0x558654d287c7 in std::__1::unique_ptr<DB::ProtocolServerAdapter::Impl, std::__1::default_delete<DB::ProtocolServerAdapter::Impl>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #57 0x558654d287c7 in DB::ProtocolServerAdapter::~ProtocolServerAdapter() ci/tmp/build/./src/Server/ProtocolServerAdapter.h:18:7
    #58 0x558654d287c7 in void std::__1::__destroy_at[abi:ne190107]<DB::ProtocolServerAdapter, 0>(DB::ProtocolServerAdapter*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11
    #59 0x558654d287c7 in void std::__1::allocator_traits<std::__1::allocator<DB::ProtocolServerAdapter>>::destroy[abi:ne190107]<DB::ProtocolServerAdapter, void, 0>(std::__1::allocator<DB::ProtocolServerAdapter>&, DB::ProtocolServerAdapter*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5
    #60 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::__base_destruct_at_end[abi:ne190107](DB::ProtocolServerAdapter*) ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:985:7
    #61 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::__clear[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:979:5
    #62 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::__destroy_vector::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:530:16
    #63 0x558654d287c7 in std::__1::vector<DB::ProtocolServerAdapter, std::__1::allocator<DB::ProtocolServerAdapter>>::~vector[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:541:67
    #64 0x558654d287c7 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./programs/server/Server.cpp:2759:1
    #65 0x558670d48a36 in Poco::Util::Application::run() ci/tmp/build/./base/poco/Util/src/Application.cpp:315:8
    #66 0x558654cfee79 in DB::Server::run() ci/tmp/build/./programs/server/Server.cpp:589:25
    #67 0x558654cf9fd8 in mainEntryClickHouseServer(int, char**) ci/tmp/build/./programs/server/Server.cpp:386:20
    #68 0x558643f928be in main ci/tmp/build/./programs/main.cpp:304:21
    #69 0x7f2d48d17d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #70 0x7f2d48d17e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #71 0x558643ebb02d in _start (/usr/bin/clickhouse+0xc22e02d) (BuildId: 4e009075232461e9244f6f3c6f9fd65b0aa9835a)

0x5060000ad2a8 is located 8 bytes inside of 56-byte region [0x5060000ad2a0,0x5060000ad2d8)
freed by thread T0 here:
    #0 0x558643f8f622 in operator delete(void*, unsigned long) (/usr/bin/clickhouse+0xc302622) (BuildId: 4e009075232461e9244f6f3c6f9fd65b0aa9835a)
    #1 0x55865fc3aa31 in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, void*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:1538:5
    #2 0x55865fc3584e in std::__1::__tree<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::__map_value_compare<Poco::Timestamp, std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>, std::__1::less<Poco::Timestamp>, true>, std::__1::allocator<std::__1::__value_type<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::~__tree() ci/tmp/build/./contrib/llvm-project/libcxx/include/__tree:1532:3
    #3 0x55865fc3584e in std::__1::multimap<Poco::Timestamp, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>, std::__1::less<Poco::Timestamp>, std::__1::allocator<std::__1::pair<Poco::Timestamp const, std::__1::shared_ptr<DB::BackgroundSchedulePoolTaskInfo>>>>::~multimap[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/map:1810:117
    #4 0x55865fc3584e in DB::BackgroundSchedulePool::~BackgroundSchedulePool() ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:233:1
    #5 0x55866276b518 in std::__1::default_delete<DB::BackgroundSchedulePool>::operator()[abi:ne190107](DB::BackgroundSchedulePool*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #6 0x55866276b518 in std::__1::unique_ptr<DB::BackgroundSchedulePool, std::__1::default_delete<DB::BackgroundSchedulePool>>::reset[abi:ne190107](DB::BackgroundSchedulePool*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #7 0x55866276b518 in DB::ContextSharedPart::shutdown() ci/tmp/build/./src/Interpreters/Context.cpp:913:30
    #8 0x558654d5aa61 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_3::operator()() const ci/tmp/build/./programs/server/Server.cpp:1225:5
    #9 0x558654d5aa61 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_3>::invoke() ci/tmp/build/./base/base/../base/scope_guard.h:101:9
    #10 0x558654d286b2 in BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_3>::~BasicScopeGuard() ci/tmp/build/./base/base/../base/scope_guard.h:50:26
    #11 0x558654d286b2 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./programs/server/Server.cpp:2759:1
    #12 0x558670d48a36 in Poco::Util::Application::run() ci/tmp/build/./base/poco/Util/src/Application.cpp:315:8
    #13 0x558654cfee79 in DB::Server::run() ci/tmp/build/./programs/server/Server.cpp:589:25
    #14 0x558654cf9fd8 in mainEntryClickHouseServer(int, char**) ci/tmp/build/./programs/server/Server.cpp:386:20
    #15 0x558643f928be in main ci/tmp/build/./programs/main.cpp:304:21
    #16 0x7f2d48d17d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible crash during shutting down background pools (`background_.*pool_size`)

There are multiple issues in the BackgroundSchedulePool, due to
BackgroundSchedulePoolTaskInfo holds raw reference to the pool, which is
wrong for multiple reasons, and there is no way to fix it properly
because we do not track all tasks in the BackgroundSchedulePool (even
inactive), and eventually this may lead to crash (during server
shutdown of background pools).

There were multiple attempts to fix it:

- #80069

  - It introduces deadlock [1]
  - And a UB due to usuing foreach and erase inside
  - But the main reason is that it does not fix all the issues, i.e.
    active() after the pool has been destroyed still leads to UB

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/PRs/81398/c07d7ee6eb7c3d1d0c65649ea4b57f881571599c//stress_test_amd_debug/gdb.log

- previous version of this patch set

  - Introduces lock order inversion [2] and [3], since I tried the
    apprach that #80069 was been using - clean all jobs in the
    destructor of the pool

  - But, when it came to the test I found out that while
    clickhouse-server may use this pool correctly it is hard to do so
    without knowing how to, so after this I converted the
    raw reference of the BackgroundSchedulePool in
    BackgroundSchedulePoolTaskInfo to weak_ptr, to avoid any UBs

  [2]: https://s3.amazonaws.com/clickhouse-test-reports/PRs/81473/a0f20c2ad7efc19d698ceb0281e0a122ebef457e//stress_test_amd_tsan/stderr.log
  [3]: https://s3.amazonaws.com/clickhouse-test-reports/PRs/81473/6404951bfb5156b00a4aa5302d1c0ca8272a2c56//stress_test_amd_tsan/stderr.log

Also I've encapsulated the BackgroundSchedulePool and
BackgroundSchedulePoolTaskInfo more, to avoid any misuse.

Fixes: #80066 (cc @serxa @VicoWu)

### CODE REVIEW

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
A test?

**Comment by alexey-milovidov** [comment]
I've also preventively reverted #81481

**Comment by azat** [comment]
>A test?

Add a unit test

File: src/Core/BackgroundSchedulePool.cpp [hunk 1]
```diff
@@ -170,6 +195,15 @@ Coordination::WatchCallback BackgroundSchedulePoolTaskInfo::getWatchCallback()
 }
 
 
+///
+/// BackgroundSchedulePool
+///
+
+BackgroundSchedulePoolPtr BackgroundSchedulePool::create(size_t size, CurrentMetrics::Metric tasks_metric, CurrentMetrics::Metric size_metric, const char *thread_name)
```
Comment (serxa) [inline src/Core/BackgroundSchedulePool.cpp]: Minor. Style.
```suggestion
BackgroundSchedulePoolPtr BackgroundSchedulePool::create(size_t size, CurrentMetrics::Metric tasks_metric, CurrentMetrics::Metric size_metric, const char * thread_name)
```

**Review by serxa — APPROVED** [review]
Thanks for fixing it properly!

File: src/Core/BackgroundSchedulePool.cpp (hunk 1 above)
Comment (azat) [reply src/Core/BackgroundSchedulePool.cpp]: Thanks. It came from the copy-paste of arguments from ctor, fixed all the occurrences

**Comment by azat** [comment]
@alexey-milovidov changes requests blocks from merging, PTAL

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Two more problems:
1. The BugFix check in the CI does not use unit tests. Need to ask @maxknv to fix it.
2. The stateless check failed sporadically due to some infrastructure problem. While we can tolerate this, let's think about external contributors who will be confused. Again, @maxknv should fix it.

**Comment by maxknv** [comment]
> Two more problems:
> 
> 1. The BugFix check in the CI does not use unit tests. Need to ask @maxknv to fix it.

I think with unit tests it's only possible to check that they were added. Or how do you suggest validating that a new unit test covers a problem?

> 2. The stateless check failed sporadically due to some infrastructure problem. While we can tolerate this, let's think about external contributors who will be confused. Again, @maxknv should fix it.
I see this one, it's not infrastructural
```
+ sudo -E -u clickhouse /usr/bin/clickhouse-server --config /etc/clickhouse-server/config.xml --daemon --pid-file /var/run/clickhouse-server/clickhouse-server.pid
==439==LeakSanitizer has encountered a fatal error.
==439==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==439==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
INFO:root:Run failed, exit code 1
INFO:root:Files in result folder ['run.log']
Run action failed for: [Stateless tests (asan, distributed plan, 2/2)] with exit code [1]
Run action done for: [Stateless tests (asan, distributed plan, 2/2)]
{}
ERROR: Run failed with exit code [1]
=== Run script finished ===
```

**Comment by alexey-milovidov** [comment]
> I think with unit tests it's only possible to check that they were added.

Yes - added or modified unit test - fulfill the BugFix check.

**Comment by alexey-milovidov** [comment]
> LeakSanitizer has encountered a fatal error.

Ok, and we should fix it. If it's not yours, ask your team lead, @alesapin

**Comment by azat** [comment]
>==439==LeakSanitizer has encountered a fatal error.

This is some issue with LSan itself I think, if someone will have a reproducer I will take a look, post it please to this issue - https://github.com/ClickHouse/ClickHouse/issues/81858
