### PR TITLE
Fix ON CLUSTER with Replicated database cluster

### LINKED ISSUE #41299: "drop partition on 'replicated database cluster' sql" only executed on the local node,not distributed to the replicated database cluster.
# ClickHouse Cluster
Clickhouse cluster with 2 shards and 1 replicas built with docker-compose.

docker-compose: [clickhouse-drop-cluster-partition-test](https://github.com/ygrzjh/clickhouse-drop-cluster-partition-test)

Clickhouse version: `22.8.1.2097` ~ `22.8.5.29`

Cluster xml config
```xml
<clickhouse>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
</clickhouse>
```

## Test it
Symptom: drop partition on replicated database cluster sql(e.g: `ALTER TABLE demo.test ON CLUSTER 'demo' DROP PARTITION '0';`) only executed on the local clickhouse node,not distributed to the replicated database cluster.

- Crate demo replicated database
```sql
-- Crate demo replicated database
set allow_experimental_database_replicated = 1;
CREATE DATABASE demo on cluster 'default'
ENGINE = Replicated('/clickhouse/default/demo', '{shard}', '{replica}');
```

- Query Clusters Info
```sql
-- System Clusters Info
SELECT *
FROM system.clusters
```
> Query Result:
```
┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name────┬─host_address─┬─port─┬─is_local─┬─user────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┐
│ default │         1 │            1 │           1 │ clickhouse01 │ 172.23.0.11  │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ default │         2 │            1 │           1 │ clickhouse02 │ 172.23.0.12  │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
│ demo    │         1 │            1 │           1 │ clickhouse01 │ 172.23.0.11  │ 9000 │        0 │ default │                  │            0 │               0 │                       0 │
│ demo    │         2 │            1 │           1 │ clickhouse02 │ 172.23.0.12  │ 9000 │        1 │ default │                  │            0 │               0 │                       0 │
└─────────┴───────────┴──────────────┴─────────────┴──────────────┴──────────────┴──────┴──────────┴─────────┴──────────────────┴──────────────┴─────────────────┴─────────────────────────┘
```

- Create ReplicatedMergeTree engine table and init data
```sql
-- Create ReplicatedMergeTree engine table
CREATE TABLE demo.test
(
    `number` UInt64
)
ENGINE = ReplicatedMergeTree()
PARTITION BY (`number`%2)
ORDER BY `number`;
-- Create Distributed table
CREATE TABLE demo.test_all AS demo.test
ENGINE = Distributed('demo', 'demo', 'test');
-- node1 insert test data
INSERT INTO demo.test SELECT *  FROM numbers(0,10);
-- node2 insert test data
INSERT INTO demo.test SELECT *  FROM numbers(10,10);
```

- Query test table parts
```sql
-- Query test table parts
SELECT
    hostname(),
    partition,
    name
FROM cluster('default', 'system', 'parts')
WHERE (database = 'demo') AND (table = 'test');
```
> Query Result:
```text
┌─hostname()───┬─partition─┬─name────┐
│ clickhouse01 │ 0         │ 0_0_0_0 │
│ clickhouse01 │ 1         │ 1_0_0_0 │
└──────────────┴───────────┴─────────┘
┌─hostname()───┬─partition─┬─name────┐
│ clickhouse02 │ 0         │ 0_0_0_0 │
│ clickhouse02 │ 1         │ 1_0_0_0 │
└──────────────┴───────────┴─────────┘
```

- Drop test part on replicated database cluster
```sql
-- Drop test table part on cluster
ALTER TABLE demo.test ON CLUSTER 'demo' DROP PARTITION '0';

/*
clickhouse01 :) ALTER TABLE demo.test ON CLUSTER 'demo' DROP PARTITION '0';

ALTER TABLE demo.test ON CLUSTER demo
    DROP PARTITION '0'

Query id: 66ec1017-742f-4487-9162-ef2e29663431

Ok.

0 rows in set. Elapsed: 0.033 sec.
*/
```
> Drop Query Result(clickhouse02 part 0 not deleted.):
```text
┌─hostname()───┬─partition─┬─name────┐
│ clickhouse01 │ 1         │ 1_0_0_0 │
└──────────────┴───────────┴─────────┘
┌─hostname()───┬─partition─┬─name────┐
│ clickhouse02 │ 0         │ 0_0_0_0 │
│ clickhouse02 │ 1         │ 1_0_0_0 │
└──────────────┴───────────┴─────────┘
```

- Drop test part on default cluster
```sql
-- Drop test part on default cluster
ALTER TABLE demo.test ON CLUSTER 'default' DROP PARTITION '1';

/*
clickhouse01 :) ALTER TABLE demo.test ON CLUSTER 'default' DROP PARTITION '1';
  
ALTER TABLE demo.test ON CLUSTER default
DROP PARTITION '1'

Query id: 76dbaaa1-6b74-4a40-a607-8d123f6202f4

┌─host─────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ clickhouse01 │ 9000 │      0 │       │                   1 │                0 │
│ clickhouse02 │ 9000 │      0 │       │                   0 │                0 │
└──────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.119 sec.
*/
```
> Drop Query Result(part 1 all shards deleted.):
```text
┌─hostname()───┬─partition─┬─name────┐
│ clickhouse02 │ 0         │ 0_0_0_0 │
└──────────────┴───────────┴─────────┘
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Since 22.8 `ON CLUSTER` clause is ignored if database is `Replicated` and cluster name and database name are the same. Because of this `DROP PARTITION ON CLUSTER` worked unexpected way with `Replicated`. It's fixed, now `ON CLUSTER` clause is ignored only for queries that are replicated on database level. Fixes https://github.com/ClickHouse/ClickHouse/issues/41299

This PR also contains changes from https://github.com/ClickHouse/ClickHouse/pull/41325 to avoid conflicts

### CODE REVIEW

File: src/Interpreters/InterpreterCreateIndexQuery.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ BlockIO InterpreterCreateIndexQuery::execute()
     query_ptr->as<ASTCreateIndexQuery &>().setDatabase(table_id.database_name);
 
     DatabasePtr database = DatabaseCatalog::instance().getDatabase(table_id.database_name);
-    if (typeid_cast<DatabaseReplicated *>(database.get()) && !current_context->getClientInfo().is_replicated_database_internal)
+    if (database->shouldReplicateQuery(getContext(), query_ptr))
```
Comment (antonio2368) [inline src/Interpreters/InterpreterCreateIndexQuery.cpp:41]: I get that it's cleaner but to me, the assumption that "if this passes it's a DatabaseReplicated" isn't that obvious.
What about having 
```
if (auto * replicated = typeid_cast<DatabaseReplicated *>(database.get());
    replicated && replicated->shouldReplicateQuery())
    ....
```
and not have `shouldReplicateQuery` as virtual?

File: src/Interpreters/InterpreterCreateQuery.cpp [hunk 2]
```diff
@@ -1001,27 +1001,27 @@ BlockIO InterpreterCreateQuery::createTable(ASTCreateQuery & create)
     String current_database = getContext()->getCurrentDatabase();
     auto database_name = create.database ? create.getDatabase() : current_database;
 
+    DDLGuardPtr ddl_guard;
```
Comment (antonio2368) [inline src/Interpreters/InterpreterCreateQuery.cpp:1004]: you can move this to line 1023

**Review by antonio2368 — APPROVED** [review]
LGTM, comments are open for discussion.

File: src/Interpreters/InterpreterCreateIndexQuery.cpp (hunk 1 above)
Comment (tavplubix) [reply src/Interpreters/InterpreterCreateIndexQuery.cpp:41]: Maybe just rename `shouldReplicateQuery` to something more clear like `shouldExecuteThroughDistributedDDLQueue` and make `tryEnqueueReplicatedDDL` virtual too?

File: src/Interpreters/InterpreterCreateQuery.cpp (hunk 2 above)
Comment (tavplubix) [reply src/Interpreters/InterpreterCreateQuery.cpp:1004]: No, I cannot, because this lock must be held after the scope between lines 1008 and 1050 ends

File: src/Interpreters/InterpreterCreateIndexQuery.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Interpreters/InterpreterCreateIndexQuery.cpp:41]: > make `tryEnqueueReplicatedDDL` virtual too

This is also okay with me, no need for rename with it.
I just didn't like the mix of having check virtual and then the actual enqueue requires cast.

File: src/Interpreters/InterpreterCreateQuery.cpp (hunk 2 above)
Comment (antonio2368) [reply src/Interpreters/InterpreterCreateQuery.cpp:1004]: Ah got confused with indentations.

**Review by antonio2368 — APPROVED** [review]

**Comment by tavplubix** [comment]
CI is completely broken in master :angry: :

AST fuzzer (msan)  - https://github.com/ClickHouse/ClickHouse/issues/40237
Integration tests (release) [1/2] - test_hive_query is known to be flaky
Stateless tests (debug) [3/3] - 01233_check_table_with_metadata_cache is too slow for debug build. It [slowed down](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgcm91bmQoYXZnKHRlc3RfZHVyYXRpb25fbXMvMTAwMCkpIGFzIHRkLCBncm91cFVuaXFBcnJheUlmKHB1bGxfcmVxdWVzdF9udW1iZXIsIHRlc3RfZHVyYXRpb25fbXMgPiA1MDAwMDApLCBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjItMDYtMDEnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcwMTIzM19jaGVja190YWJsZV93aXRoX21ldGFkYXRhX2NhY2hlJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdPSycpIGFuZCBjaGVja19uYW1lIGlsaWtlICclZGVidWclJyBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==) after https://github.com/ClickHouse/ClickHouse/pull/39039, let's disable random settings - https://github.com/ClickHouse/ClickHouse/pull/41509
Stateless tests (release) - 02417_load_marks_async is still flaky, but Kseniia is trying to fix it
Stateless tests (release, DatabaseReplicated) [2/2] - https://github.com/ClickHouse/ClickHouse/pull/41436
Stateless tests (tsan, s3 storage) [1/3] - 00632_get_sample_block_cache is too slow with tsan/debug and s3 - https://github.com/ClickHouse/ClickHouse/pull/41253
