### PR TITLE
Fix assert during insert into vector similarity index in presence of other skipping indexes

### LINKED ISSUE #71381: [Experimental] Insert into table with vector similarity index and other index throws `Expected data type Array(Float*)`
**Describe what's wrong**

When using vector similarity indexes / approximate nearest neighbor search indexes with other index types (like set, full_search), `Code: 49. DB::Exception: Expected data type Array(Float*)` is thrown during inserts.

**Does it reproduce on the most recent release?**

Yes, tried `24.9.2.42-alpine` and `head-alpine`.

**How to reproduce**
https://fiddle.clickhouse.com/033646dc-2f4e-4d7e-9c30-10cc44d74739
https://fiddle.clickhouse.com/321f51e6-ca88-4e41-bf61-a1d59041a5ba
```SQL
SET allow_experimental_vector_similarity_index = 1;
SET allow_experimental_full_text_index = 1;

CREATE TABLE IF NOT EXISTS embeddings_table
(
  value String,
  embedding Array(Float32),
  INDEX ann_idx embedding TYPE vector_similarity('hnsw', 'cosineDistance'),
  INDEX inv_idx value TYPE full_text()
  -- or INDEX set_idx value TYPE set(100) GRANULARITY 100                                   
)
ENGINE = MergeTree()                                          
ORDER BY tuple();

INSERT INTO embeddings_table (value, embedding) VALUES ('doc content', [0.0]);

```

**Expected behavior**

I should be able to use both indexes on the same table.

**Error message and/or stacktrace**

```
Code: 49. DB::Exception: Expected data type Array(Float*). (LOGICAL_ERROR) (version 24.11.1.643 (official build))
```

### PR DESCRIPTION
**Pull request by rschu1ze**
Resolves #71381

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp [hunk 1]
```diff
@@ -347,53 +347,58 @@ void MergeTreeIndexAggregatorVectorSimilarity::update(const Block & block, size_
     if (index_sample_block.columns() > 1)
         throw Exception(ErrorCodes::LOGICAL_ERROR, "Expected block with single column");
 
-    const String & index_column_name = index_sample_block.getByPosition(0).name;
```
Comment (rschu1ze) [inline src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:350]: Problem was that l. 350 and l. 385 assumed that the first column in the insert-data-block contains a vector similarity index. Made the logic consistent with the other skipping indexes which resolves the issue.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 0cc8626279fefc6ceae0a806b4e326ea0a354476 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71457/0cc8626279fefc6ceae0a806b4e326ea0a354476/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71457/0cc8626279fefc6ceae0a806b4e326ea0a354476/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp [hunk 2]
```diff
@@ -382,7 +384,7 @@ void MergeTreeIndexAggregatorVectorSimilarity::update(const Block & block, size_
     if (index->size() + rows > std::numeric_limits<UInt32>::max())
         throw Exception(ErrorCodes::INCORRECT_DATA, "Size of vector similarity index would exceed 4 billion entries");
 
-    DataTypePtr data_type = block.getDataTypes()[0];
```
Comment (rschu1ze) [inline src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:385]: This was the problem.

Comment (novikd) [reply src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:385]: Is the data type in `block` possible to be different? Why not to use `block.getByName(index_column_name).type`?

**Review by novikd — COMMENTED** [review]
In general LGTM

File: src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp (hunk 2 above)
Comment (rschu1ze) [reply src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:385]: Changed to `block.getByName(index_column_name).type`.

In theory, `block` and `index_sample_block` could have different data types but the other skipping indexes also don't check, so I think it is only a theoretical risk.

File: tests/queries/0_stateless/02354_vector_search_bugs.sql [hunk 3]
```diff
@@ -117,3 +117,18 @@ CREATE TABLE tab(id Int32, vec Array(Float32)) ENGINE = MergeTree ORDER BY id SE
...
+  vec Array(Float32),
+  INDEX ann_idx vec TYPE vector_similarity('hnsw', 'cosineDistance'),
+  INDEX set_idx val TYPE set(100)
+)
+ENGINE = MergeTree()
+ORDER BY tuple();
+
+INSERT INTO tab VALUES ('hello world', [0.0]);
+
+DROP TABLE tab;
```
Comment (novikd) [inline tests/queries/0_stateless/02354_vector_search_bugs.sql:134]: Let's also move the test to a separate file

Comment (rschu1ze) [reply tests/queries/0_stateless/02354_vector_search_bugs.sql:134]: Can do but since this file is already a conglomerate of unrelated tests, I better split it into separate tests.

**Review by novikd — APPROVED** [review]
