### PR TITLE
Remove FuseSumCountAggregatesVisitor

### LINKED ISSUE #45439: Crash in aggregation with `optimize_fuse_sum_count_avg `
**Describe the bug**
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/45418/65a71b4431fbe8125d908a01bff4fb9a81e87207/fuzzer_astfuzzerubsan/report.html)

**How to reproduce**
```sql
SET optimize_syntax_fuse_functions = 1;
SET optimize_fuse_sum_count_avg = 1;

DROP TABLE IF EXISTS fuse_tbl__fuzz_1;

CREATE TABLE fuse_tbl__fuzz_1 (`a` Int8, `b` Nullable(Int8)) ENGINE = Log;
INSERT INTO fuse_tbl__fuzz_1 VALUES (1, 1), (2, 2), (NULL, 3);

SELECT sum(b), count(b) FROM (SELECT x AS b FROM (SELECT sum(b) AS x FROM fuse_tbl__fuzz_1 GROUP BY a));
```

```
2023.01.19 15:09:44.733177 [ 3526561 ] <Fatal> BaseDaemon: ########################################
2023.01.19 15:09:44.733226 [ 3526561 ] <Fatal> BaseDaemon: (version 22.13.1.1, build id: B8D39CB26435A2CFB7AA5B320A3970CCCD22ACCC) (from thread 3526512) (query_id: 283591e9-4208-4312-b2e5-768bcc08cf9b) (query: SELECT sum(b), count(b) FROM (SELECT x AS b FROM (SELECT sum(b) AS x FROM fuse_tbl__fuzz_1 GROUP BY a));) Received signal Segmentation fault (11)
2023.01.19 15:09:44.733250 [ 3526561 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.01.19 15:09:44.733268 [ 3526561 ] <Fatal> BaseDaemon: Stack trace: 0x110e16e5 0x110decd0 0x1358277e 0x15c9101f 0x15c167d8 0x1740b0f6 0x1740946b 0x1728231a 0x17278bbb 0x17279f49 0x10f2d039 0x10f2fe2e 0x7fddc644a609 0x7fddc636f163
2023.01.19 15:09:44.767112 [ 3526561 ] <Fatal> BaseDaemon: 3. ./build_clang/./src/AggregateFunctions/AggregateFunctionSum.h:125: void DB::AggregateFunctionSumData<long>::addManyConditionalInternalImplAVX2<long, true>(long const*, char8_t const*, unsigned long, unsigned long) @ 0x110e16e5 in /usr/local/bin/clickhouse
2023.01.19 15:09:44.799613 [ 3526561 ] <Fatal> BaseDaemon: 4. ./build_clang/./src/AggregateFunctions/AggregateFunctionAvg.h:302: DB::AggregateFunctionAvg<long>::addBatchSinglePlaceNotNull(unsigned long, unsigned long, char*, DB::IColumn const**, char8_t const*, DB::Arena*, long) const @ 0x110decd0 in /usr/local/bin/clickhouse
2023.01.19 15:09:44.820420 [ 3526561 ] <Fatal> BaseDaemon: 5. ./build_clang/./src/AggregateFunctions/AggregateFunctionNull.h:364: DB::AggregateFunctionNullUnary<false, false>::addBatchSinglePlace(unsigned long, unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0x1358277e in /usr/local/bin/clickhouse
2023.01.19 15:09:45.130604 [ 3526561 ] <Fatal> BaseDaemon: 6.1. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/vector:537: std::__1::vector<DB::IAggregateFunction const*, std::__1::allocator<DB::IAggregateFunction const*>>::size[abi:v15000]() const
2023.01.19 15:09:45.130631 [ 3526561 ] <Fatal> BaseDaemon: 6. ./build_clang/./src/Interpreters/Aggregator.cpp:1317: void DB::Aggregator::executeWithoutKeyImpl<false>(char*&, unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*) const @ 0x15c9101f in /usr/local/bin/clickhouse
2023.01.19 15:09:45.432888 [ 3526561 ] <Fatal> BaseDaemon: 7. ./build_clang/./src/Interpreters/Aggregator.cpp:1544: DB::Aggregator::executeOnBlock(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>>&, std::__1::vector<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>>, std::__1::allocator<std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>>>>&, bool&) const @ 0x15c167d8 in /usr/local/bin/clickhouse
2023.01.19 15:09:45.461557 [ 3526561 ] <Fatal> BaseDaemon: 8. ./build_clang/./src/Processors/Transforms/AggregatingTransform.cpp:0: DB::AggregatingTransform::consume(DB::Chunk) @ 0x1740b0f6 in /usr/local/bin/clickhouse
2023.01.19 15:09:45.487178 [ 3526561 ] <Fatal> BaseDaemon: 9.1. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
2023.01.19 15:09:45.487200 [ 3526561 ] <Fatal> BaseDaemon: 9.2. inlined from ./build_clang/./src/Processors/Chunk.h:32: ~Chunk
2023.01.19 15:09:45.487211 [ 3526561 ] <Fatal> BaseDaemon: 9. ./build_clang/./src/Processors/Transforms/AggregatingTransform.cpp:492: DB::AggregatingTransform::work() @ 0x1740946b in /usr/local/bin/clickhouse
2023.01.19 15:09:45.490371 [ 3526561 ] <Fatal> BaseDaemon: 10.1. inlined from ./build_clang/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2023.01.19 15:09:45.490391 [ 3526561 ] <Fatal> BaseDaemon: 10. ./build_clang/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x1728231a in /usr/local/bin/clickhouse
2023.01.19 15:09:45.500795 [ 3526561 ] <Fatal> BaseDaemon: 11. ./build_clang/./src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x17278bbb in /usr/local/bin/clickhouse
2023.01.19 15:09:45.512172 [ 3526561 ] <Fatal> BaseDaemon: 12.1. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: operator()
2023.01.19 15:09:45.512195 [ 3526561 ] <Fatal> BaseDaemon: 12.2. inlined from ./build_clang/./base/base/../base/scope_guard.h:99: BasicScopeGuard<DB::PipelineExecutor::spawnThreads()::$_0::operator()() const::'lambda'()>::invoke()
2023.01.19 15:09:45.512203 [ 3526561 ] <Fatal> BaseDaemon: 12.3. inlined from ./build_clang/./base/base/../base/scope_guard.h:48: ~BasicScopeGuard
2023.01.19 15:09:45.512224 [ 3526561 ] <Fatal> BaseDaemon: 12.4. inlined from ./build_clang/./src/Processors/Executors/PipelineExecutor.cpp:328: operator()
2023.01.19 15:09:45.512258 [ 3526561 ] <Fatal> BaseDaemon: 12.5. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.01.19 15:09:45.512275 [ 3526561 ] <Fatal> BaseDaemon: 12.6. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
2023.01.19 15:09:45.512292 [ 3526561 ] <Fatal> BaseDaemon: 12.7. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&)
2023.01.19 15:09:45.512315 [ 3526561 ] <Fatal> BaseDaemon: 12.8. inlined from ./build_clang/./src/Common/ThreadPool.h:196: operator()
2023.01.19 15:09:45.512354 [ 3526561 ] <Fatal> BaseDaemon: 12.9. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&)
2023.01.19 15:09:45.512392 [ 3526561 ] <Fatal> BaseDaemon: 12.10. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&)
2023.01.19 15:09:45.512428 [ 3526561 ] <Fatal> BaseDaemon: 12.11. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]()
2023.01.19 15:09:45.512467 [ 3526561 ] <Fatal> BaseDaemon: 12. ./build_clang/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x17279f49 in /usr/local/bin/clickhouse
2023.01.19 15:09:45.520292 [ 3526561 ] <Fatal> BaseDaemon: 13.1. inlined from ./build_clang/./base/base/../base/wide_integer_impl.h:786: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2023.01.19 15:09:45.520317 [ 3526561 ] <Fatal> BaseDaemon: 13.2. inlined from ./build_clang/./base/base/../base/wide_integer_impl.h:1453: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2023.01.19 15:09:45.520342 [ 3526561 ] <Fatal> BaseDaemon: 13.3. inlined from ./build_clang/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2023.01.19 15:09:45.520377 [ 3526561 ] <Fatal> BaseDaemon: 13.4. inlined from ./build_clang/./src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
2023.01.19 15:09:45.520405 [ 3526561 ] <Fatal> BaseDaemon: 13. ./build_clang/./src/Common/ThreadPool.cpp:297: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x10f2d039 in /usr/local/bin/clickhouse
2023.01.19 15:09:45.530155 [ 3526561 ] <Fatal> BaseDaemon: 14.1. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>::reset[abi:v15000](std::__1::__thread_struct*)
2023.01.19 15:09:45.530177 [ 3526561 ] <Fatal> BaseDaemon: 14.2. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.01.19 15:09:45.530206 [ 3526561 ] <Fatal> BaseDaemon: 14.3. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
2023.01.19 15:09:45.530232 [ 3526561 ] <Fatal> BaseDaemon: 14.4. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
2023.01.19 15:09:45.530266 [ 3526561 ] <Fatal> BaseDaemon: 14.5. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>*) const
2023.01.19 15:09:45.530295 [ 3526561 ] <Fatal> BaseDaemon: 14.6. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>*)
2023.01.19 15:09:45.530334 [ 3526561 ] <Fatal> BaseDaemon: 14.7. inlined from ./build_clang/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.01.19 15:09:45.530366 [ 3526561 ] <Fatal> BaseDaemon: 14. ./build_clang/./contrib/llvm-project/libcxx/include/thread:297: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x10f2fe2e in /usr/local/bin/clickhouse
2023.01.19 15:09:45.530404 [ 3526561 ] <Fatal> BaseDaemon: 15. ? @ 0x7fddc644a609 in ?
2023.01.19 15:09:45.530436 [ 3526561 ] <Fatal> BaseDaemon: 16. __clone @ 0x7fddc636f163 in ?
2023.01.19 15:09:45.530459 [ 3526561 ] <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove AST-based optimization `optimize_fuse_sum_count_avg`, close https://github.com/ClickHouse/ClickHouse/issues/45439

Continuation of https://github.com/ClickHouse/ClickHouse/pull/44713

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Core/Settings.h [hunk 1]
```diff
@@ -528,8 +528,7 @@ class IColumn;
     M(Bool, allow_non_metadata_alters, true, "Allow to execute alters which affects not only tables metadata, but also data on disk", 0) \
     M(Bool, enable_global_with_statement, true, "Propagate WITH statements to UNION queries and all subqueries", 0) \
     M(Bool, aggregate_functions_null_for_empty, false, "Rewrite all aggregate functions in a query, adding -OrNull suffix to them", 0) \
-    M(Bool, optimize_syntax_fuse_functions, false, "Not ready for production, do not use. Allow apply syntax optimisation: fuse aggregate functions", 0) \
-    M(Bool, optimize_fuse_sum_count_avg, false, "Replace calls of functions `sum`, `avg`, `count` with identical arguments into one `sumCount`", 0) \
+    M(Bool, optimize_syntax_fuse_functions, false, "Allow apply fuse aggregating function. Available only with `allow_experimental_analyzer`", 0) \
```
Comment (CurtizJ) [inline src/Core/Settings.h:531]: Now the name is a bit confusing because it's not a syntax optimization anymore, but ok because we don't have aliases for settings and we can't easily change their names.

**Review by CurtizJ — APPROVED** [review]
