### PR TITLE
Fix analyzer: only interpolate expression should be used for DAG

### LINKED ISSUE #62464: Use of INTERPOLATE triggers "Not found column" in 24.3 in some cases
**Describe the issue**

A request using `WITH FILL ... INTERPOLATE` triggers a "Not found column" error for a column that exists. This works with 23.12. This does not work with 24.3.2. This works with 23.12.

**How to reproduce**

Using this table:

```sql
CREATE TABLE default.flows_1m0s
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `SamplingRate` UInt64,
    `ExporterAddress` LowCardinality(IPv6),
    `ExporterName` LowCardinality(String),
    `ExporterGroup` LowCardinality(String),
    `ExporterRole` LowCardinality(String),
    `ExporterSite` LowCardinality(String),
    `ExporterRegion` LowCardinality(String),
    `ExporterTenant` LowCardinality(String),
    `SrcAS` UInt32,
    `DstAS` UInt32,
    `SrcNetName` LowCardinality(String),
    `DstNetName` LowCardinality(String),
    `SrcNetRole` LowCardinality(String),
    `DstNetRole` LowCardinality(String),
    `SrcNetSite` LowCardinality(String),
    `DstNetSite` LowCardinality(String),
    `SrcNetRegion` LowCardinality(String),
    `DstNetRegion` LowCardinality(String),
    `SrcNetTenant` LowCardinality(String),
    `DstNetTenant` LowCardinality(String),
    `SrcCountry` FixedString(2),
    `DstCountry` FixedString(2),
    `SrcGeoCity` LowCardinality(String),
    `DstGeoCity` LowCardinality(String),
    `SrcGeoState` LowCardinality(String),
    `DstGeoState` LowCardinality(String),
    `Dst1stAS` UInt32,
    `Dst2ndAS` UInt32,
    `Dst3rdAS` UInt32,
    `InIfName` LowCardinality(String),
    `OutIfName` LowCardinality(String),
    `InIfDescription` LowCardinality(String),
    `OutIfDescription` LowCardinality(String),
    `InIfSpeed` UInt32,
    `OutIfSpeed` UInt32,
    `InIfConnectivity` LowCardinality(String),
    `OutIfConnectivity` LowCardinality(String),
    `InIfProvider` LowCardinality(String),
    `OutIfProvider` LowCardinality(String),
    `InIfBoundary` Enum8('undefined' = 0, 'external' = 1, 'internal' = 2),
    `OutIfBoundary` Enum8('undefined' = 0, 'external' = 1, 'internal' = 2),
    `EType` UInt32,
    `Proto` UInt32,
    `Bytes` UInt64 CODEC(T64, LZ4),
    `Packets` UInt64 CODEC(T64, LZ4),
    `PacketSize` UInt64 ALIAS intDiv(Bytes, Packets),
    `PacketSizeBucket` LowCardinality(String) ALIAS multiIf(PacketSize < 64, '0-63', PacketSize < 128, '64-127', PacketSize < 256, '128-255', PacketSize < 512, '256-511', PacketSize < 768, '512-767', PacketSize < 1024, '768-1023', PacketSize < 1280, '1024-1279', PacketSize < 1501, '1280-1500', PacketSize < 2048, '1501-2047', PacketSize < 3072, '2048-3071', PacketSize < 4096, '3072-4095', PacketSize < 8192, '4096-8191', PacketSize < 10240, '8192-10239', PacketSize < 16384, '10240-16383', PacketSize < 32768, '16384-32767', PacketSize < 65536, '32768-65535', '65536-Inf'),
    `ForwardingStatus` UInt32
)
ENGINE = SummingMergeTree((Bytes, Packets))
PARTITION BY toYYYYMMDDhhmmss(toStartOfInterval(TimeReceived, toIntervalSecond(12096)))
PRIMARY KEY (TimeReceived, ExporterAddress, EType, Proto, InIfName, SrcAS, ForwardingStatus, OutIfName, DstAS, SamplingRate)
ORDER BY (TimeReceived, ExporterAddress, EType, Proto, InIfName, SrcAS, ForwardingStatus, OutIfName, DstAS, SamplingRate, SrcNetName, DstNetName, SrcNetRole, DstNetRole, SrcNetSite, DstNetSite, SrcNetRegion, DstNetRegion, SrcNetTenant, DstNetTenant, SrcCountry, DstCountry, SrcGeoCity, DstGeoCity, SrcGeoState, DstGeoState, Dst1stAS, Dst2ndAS, Dst3rdAS)
TTL TimeReceived + toIntervalSecond(604800)
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1
```

And this query:

```sql
SELECT
    TimeReceived AS time,
    [toString(SrcAS)] AS dimensions
FROM flows_1m0s
WHERE (TimeReceived >= toDateTime('2024-04-09 14:27:00', 'UTC')) AND (TimeReceived <= toDateTime('2024-04-09 20:27:00', 'UTC'))
GROUP BY
    time,
    dimensions
ORDER BY time ASC WITH FILL FROM toDateTime('2024-04-09 14:27:00', 'UTC') TO toDateTime('2024-04-09 20:27:00', 'UTC') + toIntervalSecond(1) STEP 60
INTERPOLATE ( dimensions AS ['Other'] )
```

This triggers the following error:

```
Received exception from server (version 24.3.2):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column __table1.SrcAS: in block __table1.TimeReceived DateTime UInt32(size = 0), array(__table1.SrcAS) Array(UInt32) Array(size = 0, UInt64(size = 0), UInt32(size = 0)). (NOT_FOUND_COLUMN_IN_BLOCK)
```

Removing `INTERPOLATE` makes it work. Also, not using an array for `dimensions` also works:

```sql
SELECT
    TimeReceived AS time,
    toString(SrcAS) AS dimensions
FROM flows_1m0s
WHERE (TimeReceived >= toDateTime('2024-04-09 14:27:00', 'UTC')) AND (TimeReceived <= toDateTime('2024-04-09 20:27:00', 'UTC'))
GROUP BY
    time,
    dimensions
ORDER BY time ASC WITH FILL FROM toDateTime('2024-04-09 14:27:00', 'UTC') TO toDateTime('2024-04-09 20:27:00', 'UTC') + toIntervalSecond(1) STEP 60
INTERPOLATE ( dimensions AS 'Other' )
```

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix analyzer: "Not found column" error is fixed when using INTERPOLATE

closes #62464

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 79b3f52dc5189d6def125cf5ed9b1fb2e37267e4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64096/79b3f52dc5189d6def125cf5ed9b1fb2e37267e4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

File: src/Planner/PlannerExpressionAnalysis.cpp [hunk 1]
```diff
@@ -439,20 +441,30 @@ SortAnalysisResult analyzeSort(const QueryNode & query_node,
...
+        std::unordered_set<std::string_view> aggregation_keys;
+
+        auto projection_expression_dag = std::make_shared<ActionsDAG>();
+        for (const auto & node : query_node.getProjection())
+            actions_visitor.visit(projection_expression_dag, node);
+        for (const auto & node : projection_expression_dag->getNodes())
+            aggregation_keys.insert(node.result_name);
+
+        if (aggregation_analysis_result_optional)
+            aggregation_keys.insert(aggregation_analysis_result_optional->aggregation_keys.begin(), aggregation_analysis_result_optional->aggregation_keys.end());
```
Comment (novikd) [inline src/Planner/PlannerExpressionAnalysis.cpp:465]: Why do we need it?

File: src/Planner/PlannerExpressionAnalysis.cpp [hunk 2]
```diff
@@ -467,6 +479,12 @@ SortAnalysisResult analyzeSort(const QueryNode & query_node,
                 input_node_it = it;
             }
 
+            if (aggregation_analysis_result_optional)
+                if (!aggregation_keys.contains(node.result_name))
+                    throw Exception(ErrorCodes::NOT_AN_AGGREGATE,
+                        "Column {} is not under aggregate function and not in GROUP BY keys. In query {}",
```
Comment (novikd) [inline src/Planner/PlannerExpressionAnalysis.cpp:485]: This check is done in QueryAnalysisPass. Why do you add it here>

File: src/Planner/PlannerExpressionAnalysis.cpp (hunk 1 above)
Comment (yakov-olkhovskiy) [reply src/Planner/PlannerExpressionAnalysis.cpp:465]: for SELECT with aggregation in `INTERPOLATE` expression we only can use aggregated columns - here we assume that all columns in projection are aggregated (else it will throw exception on different stage of analysis), also we can use aggregated columns from `GROUP BY` expression - it can include some columns not present in projection.

File: src/Planner/PlannerExpressionAnalysis.cpp (hunk 2 above)
Comment (yakov-olkhovskiy) [reply src/Planner/PlannerExpressionAnalysis.cpp:485]: consider next select:
```
SELECT n, number+5 AS inter FROM (
   SELECT toFloat32(number % 10) AS n, number, number*2 AS mn
   FROM numbers(10) WHERE number % 3 = 1
) GROUP BY n, inter ORDER BY n WITH FILL FROM 0 TO 5.51 STEP 0.5 INTERPOLATE (inter AS mn * 2);
```
column `mn` is required for calculation, however it's not under any aggregation and will be missing ending up with exception (when without this interception):
```
Code: 10. DB::Exception: Not found column __table1.mn: in block __table1.n Float32 Float32(size = 0), plus(__table1.number, 5_UInt8) UInt64 UInt64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK)
```
here:
https://github.com/ClickHouse/ClickHouse/blob/fix-analyzer-interpolate/src/Interpreters/ActionsDAG.cpp#L824

this exception while correct, yet absolutely not clear - so we intercept this situation early and generate correct exception:
```
Code: 215. DB::Exception: Column __table1.mn is not under aggregate function and not in GROUP BY keys. In query SELECT n, number + 5 AS inter FROM (SELECT toFloat32(number % 10) AS n, number, number * 2 AS mn FROM numbers(10) WHERE
 (number % 3) = 1) GROUP BY n, inter ORDER BY n ASC WITH FILL FROM 0 TO 5.51 STEP 0.5 INTERPOLATE ( inter AS mn * 2 ). (NOT_AN_AGGREGATE)
```

Comment (novikd) [reply src/Planner/PlannerExpressionAnalysis.cpp:485]: Thanks for the explanation. Now I understand the error, but I still think the fix is wrong. The issue is located here:
https://github.com/ClickHouse/ClickHouse/blob/9fb8c8263f85322f3ae3b190a60110226a6f9e56/src/Analyzer/ValidationUtils.cpp#L83-L84

Validation visitor should also check INTERPOLATE expressions.

**Comment by novikd** [comment]
@yakov-olkhovskiy I updated the PR to fix validation in `ValidationUtils.cpp`.

File: src/Analyzer/ValidationUtils.cpp [hunk 3]
```diff
@@ -276,6 +276,9 @@ void validateAggregates(const QueryTreeNodePtr & query_node, AggregatesValidatio
         if (query_node_typed.hasOrderBy())
             validate_group_by_columns_visitor.visit(query_node_typed.getOrderByNode());
 
+        if (query_node_typed.hasInterpolate())
+            validate_group_by_columns_visitor.visit(query_node_typed.getInterpolate());
```
Comment (yakov-olkhovskiy) [inline src/Analyzer/ValidationUtils.cpp:280]: @novikd I suspect it's not correct - for `INTERPOLATE (inter AS mn * 2)` - `getInterpolate()` returns left side (`inter`) - it's just a placeholder - the calculated expression is the right side (`mn * 2`) - returned by `getInterpolateExpression()`
```suggestion
            validate_group_by_columns_visitor.visit(query_node_typed.getInterpolateExpression());
```

Comment (novikd) [reply src/Analyzer/ValidationUtils.cpp:280]: No, my change is correct because here `QueryNode::getInterpolate()` is called and this method returns `InterpolateNode`. As you can see, the test passed.

You confused it with `InterpolateNode::getExpression()`.

Comment (yakov-olkhovskiy) [reply src/Analyzer/ValidationUtils.cpp:280]: oh, right, I confused it...
