### PR TITLE
Fix minor hiliting issues in clickhouse-format

### LINKED ISSUE #45668: clickhouse-format doesn't hilite some identifiers
Hey!

1. In this query the `identifier` is not hilited — is it intended behaviour? I think it should either be hilited as an identifier, or an alias.
```
$ ./clickhouse-format --hilite --query "with identifier as (select * from table) select * from table"
WITH identifier AS
    (
        SELECT *
        FROM table
    )
```
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTWithElement.cpp#L21

image

2. And also there's another identifier output without being hilited, but I cannot come up with the query which corresponds to this code - any help?
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTWithAlias.cpp#L23

3. There seems to be an inconsistensy of manually applied hilite, as it's never removed within this if:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTFunction.cpp#L585

### PR DESCRIPTION
**Pull request by murfel**
### Description
Fixes #45668. Added tests to confirm issues existed and are fixed correctly.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Minor hiliting issues fixed in clickhouse-format.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by murfel** [comment]
I cannot come up with a query that would print `ATTACH ROW POLICY` from [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/Access/ASTCreateRowPolicyQuery.cpp#L153).

`ALTER ROW POLICY name ON table` works fine, but `ATTACH` apparently isn't a correct query.

**Comment by murfel** [comment]
I couldn't come up with queries for 5 issues from here:
https://github.com/ClickHouse/ClickHouse/issues/45668

I've added a confused emoji on those. 
image



I'll need a `can-be-tested` label.

I'm not very experienced with gtest, would appreciate suggestions on how to group tests better.

How to test my PR: the idea was to add tests that break in the first commit, and add fixes in the following commits. Then it would have been enough to checkout the first commit, make sure that the tests break, then checkout the last commit and make sure that the tests pass. However, I had to redo some tests, so now the latest version of the tests is in the last commit.

So now you need to reset everything but the tests file to master, in order to confirm that the tests were indeed failing.

**Comment by rschu1ze** [comment]
Added label 'can be tested', looking closer into the PR now.

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 1]
```diff
@@ -0,0 +1,303 @@
...
+
+    ASSERT_PRED2(are_equal_with_hilites, expected.str(), write_buffer.str());
+}
+
+TEST(FormatHiliting, SimpleSelect)
+{
+    std::string query = "select * from table";
+
+    std::stringstream expected;
+    expected << keyword("SELECT ") << "* " << keyword("FROM ") << identifier("table");
```
Comment (rschu1ze) [inline src/Parsers/tests/gtest_format_hiliting.cpp:224]: Sure that the space after `SELECT` should be highlighted as well? (it will make no visual difference but still looks wrong)

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 2]
```diff
@@ -0,0 +1,303 @@
...
+    {
+        std::stringstream left;
+        left << DB::IAST::hilite_keyword << "keyword" << " long" << DB::IAST::hilite_none;
+        std::stringstream right;
+        right << DB::IAST::hilite_keyword << "keyword" << DB::IAST::hilite_none << " " << DB::IAST::hilite_keyword << "long";
+        ASSERT_PRED2(are_equal_with_hilites, left.str(), right.str());
+    }
+}
+
+void compare(const std::string & query, const std::stringstream & expected)
```
Comment (rschu1ze) [inline src/Parsers/tests/gtest_format_hiliting.cpp:205]: Minor: ClickHouse provides typedef `String` which is a bit shorter than `std::string`. Alternatively use a `std::string_view` (which is conceptually a non-owning view to a string and can be passed as is, e.g. `void compare(std::string_view query, ...)`).

**Comment by rschu1ze** [comment]
Wondering if the unit test covers all SELECTs in #45668?

File: src/Parsers/ASTDictionaryAttributeDeclaration.cpp [hunk 3]
```diff
@@ -66,6 +66,8 @@ void ASTDictionaryAttributeDeclaration::formatImpl(const FormatSettings & settin
 
     if (is_object_id)
         settings.ostr << ' ' << (settings.hilite ? hilite_keyword : "") << "IS_OBJECT_ID";
+
+    settings.ostr << (settings.hilite ? hilite_none : "");
```
[the remark this answers is not in the document]
Comment (murfel) [reply src/Parsers/ASTDictionaryAttributeDeclaration.cpp:70]: I'll fix these cases for consistency, but plenty of code doesn't keep the consistency. It won't matter anyway once I merge my refactoring in #45649, and I'm only fixing these issues to be able to regression tests on my refactoring PR.

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 1 above)
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:224]: I won't be fixing this, as it is here for user convenience, and it is how it's used everywhere in `formatImpl` overrides. There are hundreds of such cases, and adding space as a separate token in each of them would be inconvenient.

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 2 above)
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:205]: Using String, as parseQuery requires a String, not std::string_view.

**Comment by murfel** [comment]
> Wondering if the unit test covers all SELECTs in #45668?

They don't. Please kindly take a look at my first comment on this issue.

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 4]
```diff
@@ -0,0 +1,303 @@
...
+        if (!std::isspace(*left_it) && left_hilite != right_hilite)
+            return false;
+
+        // Consume one character.
+        left_it++;
+        right_it++;
+    }
+}
+
+TEST(FormatHiliting, MetaTestConsumeHilites)
```
[the remark this answers is not in the document]
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:141]: Yes :) And let's discuss this in the above comment.

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 5]
```diff
@@ -0,0 +1,303 @@
...
+        DB::IAST::hilite_keyword,
+        DB::IAST::hilite_identifier,
+        DB::IAST::hilite_function,
+        DB::IAST::hilite_operator,
+        DB::IAST::hilite_alias,
+        DB::IAST::hilite_substitution,
+        DB::IAST::hilite_none
+    };
+
+[[maybe_unused]] const char * consume_hilites(const char ** it)
```
[the remark this answers is not in the document]
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:59]: I agree with the idea to keep the tests simple, but I'm not sure how to achieve the same results without the extra comparison logic.

There's no way to compare that the hilites match without writing a custom comparator.

E.g. one string has a space character hilited, the other one doesn't, and both are in accordance with the correct behaviour.

It would be infeasible to impose the invariant that e.g. whitespace shouldn't be hilited and each starting hilite should end with the ending hilite `hilite_none`. It would require me to refactor all formatImpl overrides, to ensure this invariant holds.

Also, I'm going to use this or similar code to regression-test my formatImpl refactoring #45649: I'm going to compare that the visible hiliting didn't change.

The most I can offer is to rewrite `are_equal_with_hilites_removed` since it's 1) unnecessary copies the string and 2) could possibly be implemented simpler. I'm just still not sure how to simplify it, thinking of throwing some `<algorithm>` function.

**Comment by murfel** [comment]
Fixed on my end - please take a look again.

File: src/Parsers/ASTWithAlias.cpp [hunk 6]
```diff
@@ -20,7 +20,9 @@ void ASTWithAlias::formatImpl(const FormatSettings & settings, FormatState & sta
     /// This is needed because the query can become extraordinary large after substitution of aliases.
     if (!alias.empty() && !state.printed_asts_with_alias.emplace(frame.current_select, alias, getTreeHash()).second)
     {
+        settings.ostr << (settings.hilite ? IAST::hilite_identifier : "");
```
[the remark this answers is not in the document]
Comment (rschu1ze) [reply src/Parsers/ASTWithAlias.cpp:23]: I see, thanks.

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 1 above)
Comment (rschu1ze) [reply src/Parsers/tests/gtest_format_hiliting.cpp:224]: Okay, didn't know the funny formatting would be so prevalent 😄 Fine with me to keep things as is. I just would have expected that AstSELECT's `formatImpl()` (conceptually) only hilites `SELECT` and that the caller (... whichever AST type that is - maybe AstQuery but I don't have much clue here) adds the spaces to the output.

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 7]
```diff
@@ -0,0 +1,303 @@
...
+{
+    const char * last_hilite = nullptr;
+    while (true)
+    {
+        bool changed_hilite = false;
+        for (const char * hilite : HILITES)
+        {
+            if (std::string_view(*it).starts_with(hilite))
```
Comment (rschu1ze) [inline src/Parsers/tests/gtest_format_hiliting.cpp:67]: (Unrelated fun fact and just FYI: all of this magic works only because [since C++11](https://en.cppreference.com/w/cpp/string/basic_string) the internal data of a string (l. 216) is guaranteed to be NULL-terminated.)

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 8]
```diff
@@ -0,0 +1,303 @@
...
+            {
+                *it += strlen(hilite);
```
Comment (rschu1ze) [inline src/Parsers/tests/gtest_format_hiliting.cpp:69]: For your big refactoring: We could store the hilite strings in IAST as std::string_view, e.g.

```cpp
static constexpr std::string_view IAST::hilite_none = "\033[0m";
```

This will enable to call `.size()` on them w/o having to resort to a rather unaesthetic C function (l. 69).

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (rschu1ze) [reply src/Parsers/tests/gtest_format_hiliting.cpp:59]: I guess our notions of "hiliting equality" is different, I am in the bit-by-bit equality camp (to make developer life easy) whereas you lean to the "logical" equality camp. It is fine with me to go for logical equality.

Perhaps you could at least add a few code comments about the motivation for the "fuzzy" comparison, in case future readers wonder. And perhaps about the invariants.

**Comment by rschu1ze** [comment]
> > Bugfix validate check — Changed tests don't reproduce the bug
> 
> How do I register my tests which reproduce the bug?

Didn't find that failure in the CI but perhaps I looked in the wrong place. If it reoccurs, please share the link to it, thanks.

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 9]
```diff
@@ -0,0 +1,303 @@
...
+        }
+        if (!changed_hilite)
+            break;
+    }
+    return last_hilite;
+}
+
+std::string remove_hilites(const std::string_view & string)
+{
+    const char * it = string.begin();
```
[the remark this answers is not in the document]
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:82]: Renamed into ptr, as pos could be confused with index.

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 7 above)
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:67]: Yay, some good design!

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 8 above)
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:69]: Ah, nice observation, I'll see if I'll be able to fit it in, thank you!

Comment (rschu1ze) [reply src/Parsers/tests/gtest_format_hiliting.cpp]: True.

About performance: I'd say anything that does not run in a hot loop is not (obviously) performance critical. I doubt that the number of formatted queries per second is a reasonable metric. And `std::string_view` is really only a pointer + size and as fast (if not faster for things like `.size()`) than a plain `const char *`.

File: src/Parsers/ASTFunction.cpp [hunk 10]
```diff
@@ -691,12 +691,15 @@ void ASTFunction::formatImplWithoutAlias(const FormatSettings & settings, Format
     {
         std::string nl_or_nothing = settings.one_line ? "" : "\n";
         std::string indent_str = settings.one_line ? "" : std::string(4u * frame.indent, ' ');
-        settings.ostr << (settings.hilite ? hilite_function : "") << name << "(" << nl_or_nothing;
+        settings.ostr << (settings.hilite ? hilite_function : "") << name << (settings.hilite ? hilite_none : "");
+        settings.ostr << (settings.hilite ? hilite_function : "") << "(" << (settings.hilite ? hilite_nano : "");
```
Comment (rschu1ze) [inline src/Parsers/ASTFunction.cpp:695]: hilite_nano?

**Review by rschu1ze — APPROVED** [review]

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 11]
```diff
@@ -0,0 +1,302 @@
...
+
+#include <Parsers/IAST.h>
+#include <Parsers/ParserQuery.h>
+#include <Parsers/parseQuery.h>
+#include <gtest/gtest.h>
+#include <Common/StackTrace.h>
+
+String hilite(const String & s, const char * hilite_type)
+{
+    std::stringstream ss;
```
[the remark this answers is not in the document]
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:11]: Oops, I was accidentally hit by Java's StringBuilder nostalgia.

[the remark this answers is not in the document]
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp:11]: One downside is it's no longer possible to chain multiple statements within one line, but it's no big deal. Fixed.

File: src/Parsers/ASTFunction.cpp (hunk 10 above)
Comment (murfel) [reply src/Parsers/ASTFunction.cpp]: Well now you know my favourite text editor :smile:

**Comment by murfel** [comment]
Errr. I only wanted to sync with the main, so that the pipeline would run.

What I did:
- Went to my github repo fork, https://github.com/murfel/ClickHouse/, and clicked Sync fork.
- In CLion, selected `Merge origin/master into `format-hiliting-fix`, then pushed.

Then it offered a dialogue like 'Blah blah merge is strictly recommended. Merge? Rebase? Cancel?', I chose Merge thinking it means resolving merge conflicts locally, but apparently it didn't.

Would you have any idea what happened and could you kindly help me untangle myself?

**Comment by murfel** [comment]
Errr. I only wanted to sync with the main, so that the pipeline would run.

What I did:

Went to my github repo fork, https://github.com/murfel/ClickHouse/, and clicked Sync fork.
In CLion, selected Merge origin/master into format-hiliting-fix`, then pushed.
Then it offered a dialogue like 'Blah blah merge is strictly recommended. Merge? Rebase? Cancel?', I chose Merge thinking it means resolving merge conflicts locally, but apparently it didn't.

Would you have any idea what happened and could you kindly help me untangle myself?

**Comment by rschu1ze** [comment]
Try that:
- Don't panic.
- Identify the commit/commits of your previous work. E.g. if I go to https://github.com/ClickHouse/ClickHouse/pull/47610/commits, I find most of the existing "useful" commits. If they exist remotely, it means they are not lost.
- Reset your local "format-hiliting-fix" branch to the state of branch "master" via `git reset --hard origin/master`
- Then cherry pick the existing commits one-by-one into your local branch (use `git cherry-pick`). This will restore the existing state of work
- Push the local "format-hiliting-fix" branch to GitHub. You will need to use the `--force` option with `git push` because the branch was constructed from scratch.

**Comment by murfel** [comment]
Except that I need to fix the submodules now. I have some troubles with submodules going on and on in all my PR. I think I somehow accidentally updated some submodules in my fork's main branch.

Any idea how to fix that? I don't see any submodule changes in the diff.

File: src/Parsers/tests/gtest_format_hiliting.cpp (hunk 8 above)
Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp]: Agree, formatted queries per second doesn't make sense.

Comment (murfel) [reply src/Parsers/tests/gtest_format_hiliting.cpp]: Why do you suggest having it as a std::string_view rather than just std::string?

**Comment by rschu1ze** [comment]
> I don't see any submodule changes in the diff.

Yeah, that's unintuitive but expected. Uncommitted changes in a submodule (usually caused by accidentally touching a file) don't appear in `git diff/status` of the top-level repository (= ClickHouse). It is however also possible to commit changes in submodules and then do another commit in the top-level repository. In that case, `git status` shows something like
```
--- a/contrib/llvm-project
+++ b/contrib/llvm-project
@@ -1 +1 @@
-Subproject commit 4bfaeb31dd0ef13f025221f93c138974a3e0a22a
+Subproject commit 6a97aa988a918c4fd08c3638732f362daa885a63
```

Anyways, this PR is clean with respect to changed submodules. To remove all submodule changes from your local repository, you could use `git fi` from my dotfiles (see [here](https://github.com/rschu1ze/dotfiles/blob/ec72f40688ed47fcef28385c5c14e128e2b5ce6a/.config/git/config#L26)).

**Comment by rschu1ze** [comment]
(please mark this PR as ready-for-review and remove "WIP" from the title, once you feel confident it can go in, thanks)

**Comment by murfel** [comment]
> > I don't see any submodule changes in the diff.
> 
> Yeah, that's unintuitive but expected. Uncommitted changes in a submodule (usually caused by accidentally touching a file) don't appear in `git diff/status` of the top-level repository (= ClickHouse). It is however also possible to commit changes in submodules and then do another commit in the top-level repository. In that case, `git status` shows something like
> 
> ```
> --- a/contrib/llvm-project
> +++ b/contrib/llvm-project
> @@ -1 +1 @@
> -Subproject commit 4bfaeb31dd0ef13f025221f93c138974a3e0a22a
> +Subproject commit 6a97aa988a918c4fd08c3638732f362daa885a63
> ```
> 
> Anyways, this PR is clean with respect to changed submodules. To remove all submodule changes from your local repository, you could use `git fi` from my dotfiles (see [here](https://github.com/rschu1ze/dotfiles/blob/ec72f40688ed47fcef28385c5c14e128e2b5ce6a/.config/git/config#L26)).

Ah, right, I just saw a big red `submodule changed` label and my primal brain filtered out the 'removed' part. Thank you for sharing your aliases!

**Comment by murfel** [comment]
> (please mark this PR as ready-for-review and remove "WIP" from the title, once you feel confident it can go in, thanks)

Yep, I just want to do some more things. I want to assert that hilites end with `hilites_none` (otherwise your terminal will stay hilited after clickhouse format has been executed already).

And I'll need to decide the future of the comparator code, as I also need to use it in my refactoring to run on all `tests/queries/0_stateless` queries with before/after clickhouse format to make sure my refactoring didn't change behaviour. So I'm thinking of having it as a separate compile unit.

**Comment by murfel** [comment]
@rschu1ze re failing test "Bugfix validate check — Changed tests don't reproduce the bug"

image

Is there a way I can register my newly added tests to make this failure go away?

File: utils/hilite_comparator/HiliteComparator.h [hunk 12]
```diff
@@ -0,0 +1,107 @@
+#pragma once
+
+#include <IAST.h>
+
+namespace HiliteComparator {
+
+std::vector<const char *> HILITES =
+    {
+        DB::IAST::hilite_keyword,
```
Comment (murfel) [inline utils/hilite_comparator/HiliteComparator.h:9]: Funny enough, DB is hilited my by editor as found, while IAST as not found

**Review by murfel — COMMENTED** [review]
I'm extracting the hilite comparator into a separate utility so that I could either import it as a header into tests (this PR) or use it as a CLI utility (which I will add later) in bash tests in my refactoring PR.

However, I'm a bit lost in CMakeLists configs, as I'm not sure how to build it and link it to the gtest. Any help on that?

File: src/Parsers/tests/gtest_format_hiliting.cpp [hunk 13]
```diff
@@ -6,6 +6,8 @@
 #include <gtest/gtest.h>
 #include <Common/StackTrace.h>
 
+#include <utils/hilite_comparator/HiliteComparator.h>
```
[the remark this answers is not in the document]
Comment (rschu1ze) [reply src/Parsers/tests/gtest_format_hiliting.cpp:9]: I'll check locally what is wrong. For now, I can only say that linking *executable* `hilite_comparator` (utils/hilite_comparator/CMakeLists.txt)  to executable `unit_tests_dbms` (src/CMakeLists.txt) doesn't look right.

**Comment by Felixoid** [comment]
The bugfix checks if there's a bug in the master, that would fail with new or changed tests in the PR.

@vdimir do you have, maybe, thoughts regarding improving this place?

**Comment by rschu1ze** [comment]
@murfel I fixed the build, in particular
1. hilite_comparator is now a library (against which your standalone-tool may link against later) instead an executable
2. I moved implementation from the header to the source file and vice versa (something was odd with that).

**Comment by vdimir** [comment]
Bugfix validate check checks only stateless and integration tests against master.
We can ignore it if tests are hard to add, failure is unstable, or another kind of test is added (unit test in this case).

@Felixoid I think we can add some explicit message to make it clear in which cases it may fail, so it's up to the reviewer to check whether tests are added or not needed. Also, we can force green check if any unit tests are changed.

**Comment by murfel** [comment]
@rschu1ze thank you for the help with the build! (Among the other types of help!)

The PR is now ready to be reviewed, I don't have any plans to add anything else.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Approved, thanks. Will merge once builds/tests are green.

Only pushed a smallish commit which uses a dark magic globbing macro to build the new utility library. Had to move "gest_hilite_comparator.cpp" one subdirectory deeper so it would not be accidentally be globbed as well.

**Comment by murfel** [comment]
> Approved, thanks. Will merge once builds/tests are green.
> 
> Only pushed a smallish commit which uses a dark magic globbing macro to build the new utility library. Had to move "gest_hilite_comparator.cpp" one subdirectory deeper so it would not be accidentally be globbed as well.

Thank you for the review and your input!
