### PR TITLE
Fix resolving dynamic subcolumns in analyzer

### LINKED ISSUE #65995: `Dynamic` data type does not leverage subcolumns optimization with analyzer
**Describe the situation**
Consider the following example:

```sql
SET allow_experimental_dynamic_type = 1;

DROP TABLE IF EXISTS test_dynamic;

CREATE TABLE test_dynamic (id UInt64, d Dynamic) ENGINE = MergeTree ORDER BY id SETTINGS min_bytes_for_wide_part = 0;

INSERT INTO test_dynamic VALUES (1, 'foo'), (2, 1111), (3, [1, 2, 3]);
```

Let's check the query tree for query:

```sql
EXPLAIN QUERY TREE dump_ast = 1
SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 1;

Query id: 07ee983c-ebd4-4fba-bcc3-b9f90d7e0072

    ┌─explain───────────────────────────────────────────────────────────────────────────────────────────────────┐
 1. │ QUERY id: 0                                                                                               │
 2. │   PROJECTION COLUMNS                                                                                      │
 3. │     id UInt64                                                                                             │
 4. │     d.String Nullable(String)                                                                             │
 5. │   PROJECTION                                                                                              │
 6. │     LIST id: 1, nodes: 2                                                                                  │
 7. │       COLUMN id: 2, column_name: id, result_type: UInt64, source_id: 3                                    │
 8. │       FUNCTION id: 4, function_name: getSubcolumn, function_type: ordinary, result_type: Nullable(String) │
 9. │         ARGUMENTS                                                                                         │
10. │           LIST id: 5, nodes: 2                                                                            │
11. │             COLUMN id: 6, column_name: d, result_type: Dynamic, source_id: 3                              │
12. │             CONSTANT id: 7, constant_value: 'String', constant_value_type: String                         │
13. │   JOIN TREE                                                                                               │
14. │     TABLE id: 3, alias: __table1, table_name: default.test_dynamic                                        │
15. │                                                                                                           │
16. │ SELECT                                                                                                    │
17. │     __table1.id AS id,                                                                                    │
18. │     getSubcolumn(__table1.d, 'String') AS `d.String`                                                      │
19. │ FROM default.test_dynamic AS __table1                                                                     │
    └───────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Note that `d.String` is substituted to `getSubcolumn(__table1.d, 'String')`. That means that the full column `d` will be read and subcolumn will be extracted instead of reading subcolumn`d.String` directly.

With old analyzer it works as expected:
```sql
EXPLAIN SYNTAX 
SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 0;

   ┌─explain──────────────────────────────────┐
1. │ SELECT d.String                          │
2. │ FROM test_dynamic                        │
3. │ SETTINGS allow_experimental_analyzer = 0 │
   └──────────────────────────────────────────┘
```

Let's also check profile events for open files:
```sql
SYSTEM DROP MARK CACHE;
SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 1;

SYSTEM DROP MARK CACHE;
SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 0;

SELECT
    query,
    ProfileEvents['FileOpen']
FROM system.query_log
WHERE (type = 2) AND (query LIKE 'SELECT d.String%')
ORDER BY event_time_microseconds DESC
LIMIT 2;
   ┌─query───────────────────────────────────────────────────────────────────────┬─arrayElement(ProfileEvents, 'FileOpen')─┐
1. │ SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 0; │                                       6 │
   └─────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────┘
   ┌─query───────────────────────────────────────────────────────────────────────┬─arrayElement(ProfileEvents, 'FileOpen')─┐
2. │ SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 1; │                                      12 │
   └─────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix resolving dynamic subcolumns in analyzer, avoid reading the whole column on dynamic subcolumn reading.

Closes https://github.com/ClickHouse/ClickHouse/issues/65995

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 2f083fd1a709dd236ffaf37a7a059cafef8c4a41 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66004/2f083fd1a709dd236ffaf37a7a059cafef8c4a41/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/03040_dynamic_type_alters_1.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@ CLICKHOUSE_LOG_COMMENT=
 # shellcheck source=../shell_config.sh
 . "$CUR_DIR"/../shell_config.sh
 
-CH_CLIENT="$CLICKHOUSE_CLIENT --allow_experimental_dynamic_type=1 --allow_experimental_variant_type=1 --use_variant_as_common_type=1 --allow_experimental_analyzer=1"
+CH_CLIENT="$CLICKHOUSE_CLIENT --allow_experimental_dynamic_type=1 --allow_experimental_variant_type=1 --use_variant_as_common_type=1 --allow_experimental_analyzer=0"
```
Comment (novikd) [inline tests/queries/0_stateless/03040_dynamic_type_alters_1.sh:10]: Why? You make a fix in analyzer but disable it in the test

File: tests/queries/0_stateless/03040_dynamic_type_alters_1.reference [hunk 2]
```diff
@@ -30,16 +30,16 @@ alter modify column 1
 0	0	\N	\N	\N	\N	\N
 1	1	\N	\N	\N	\N	\N
 2	2	\N	\N	\N	\N	\N
-3	3	3	3	\N	\N	\N
```
Comment (novikd) [inline tests/queries/0_stateless/03040_dynamic_type_alters_1.reference:33]: Why has the order of the result columns changed? I don't see any changes related to that.

File: tests/queries/0_stateless/03198_dynamic_read_subcolumns.sql [hunk 3]
```diff
@@ -0,0 +1,20 @@
+-- Tags: no-random-settings
+
+SET allow_experimental_dynamic_type = 1;
+DROP TABLE IF EXISTS test_dynamic;
+CREATE TABLE test_dynamic (id UInt64, d Dynamic) ENGINE = MergeTree ORDER BY id SETTINGS min_bytes_for_wide_part = 0;
+INSERT INTO test_dynamic VALUES (1, 'foo'), (2, 1111), (3, [1, 2, 3]);
+SYSTEM DROP MARK CACHE;
+SELECT d.String FROM test_dynamic SETTINGS allow_experimental_analyzer = 1;
```
Comment (novikd) [inline tests/queries/0_stateless/03198_dynamic_read_subcolumns.sql:8]: I also suggest adding a test query with `EXPLAIN QUERY TREE`.

File: tests/queries/0_stateless/03040_dynamic_type_alters_1.sh (hunk 1 above)
Comment (Avogar) [reply tests/queries/0_stateless/03040_dynamic_type_alters_1.sh:10]: It was added by mistake during testing. Thanks for noticing

File: tests/queries/0_stateless/03040_dynamic_type_alters_1.reference (hunk 2 above)
Comment (Avogar) [reply tests/queries/0_stateless/03040_dynamic_type_alters_1.reference:33]: The order didn't change, the actual output changed. It's now the same as with old analyzer.
The actual problem is how mutations of Dynamic column is handled in Memory engine. I will fix it in a separate PR. I didn't notice this probleb before because of the bug this PR fixes.

Comment (Avogar) [reply tests/queries/0_stateless/03040_dynamic_type_alters_1.reference:33]: https://github.com/ClickHouse/ClickHouse/pull/66066

**Review by novikd — APPROVED** [review]

File: tests/queries/0_stateless/03036_dynamic_read_subcolumns.sh [hunk 4]
```diff
@@ -7,7 +7,7 @@ CLICKHOUSE_LOG_COMMENT=
 # shellcheck source=../shell_config.sh
 . "$CUR_DIR"/../shell_config.sh
 
-CH_CLIENT="$CLICKHOUSE_CLIENT --allow_experimental_variant_type=1 --use_variant_as_common_type=1 --allow_experimental_dynamic_type=1"
+CH_CLIENT="$CLICKHOUSE_CLIENT --allow_experimental_variant_type=1 --use_variant_as_common_type=1 --allow_experimental_dynamic_type=1 optimize_functions_to_subcolumns=0"
```
Comment (Avogar) [inline tests/queries/0_stateless/03036_dynamic_read_subcolumns.sh:10]: We enabled `optimize_functions_to_subcolumns` by default recently. But `Variant` and `Dynamic` don't support `null` subcolumn and it leads to failed queries with `isNull(variant.UInt64)/isNull(dynamic.UInt64)`. I will fix it in a separate PR

Comment (Avogar) [reply tests/queries/0_stateless/03036_dynamic_read_subcolumns.sh]: https://github.com/ClickHouse/ClickHouse/pull/66178
