### PR TITLE
Fixes for Replicated database

### LINKED ISSUE #33747: TRUNCATE TABLE in Replicated DB if multiple partitions exist raises exception: Cannot add ZooKeeper operation because query is executed
### Version
21.12.3.32

### Details
Create Replicated DB
```
CREATE DATABASE IF NOT EXISTS test ON CLUSTER 'test_shard_localhost'
ENGINE = Replicated('/clickhouse/{cluster}/db/test', '{shard}', '{replica}') ;
```

Create Table in Replicated DB
```
CREATE TABLE IF NOT EXISTS test.events
(
    event_day Date,
    event_id String
)
ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/{uuid}/{shard}', '{replica}')
PARTITION BY (toYYYYMM(event_day))
ORDER BY (event_day);
```

Try to insert data and do truncate.  
If adding data that fits into one partition => truncate works OK:
```
INSERT INTO test.events(event_day, event_id)
VALUES 
	(toDate('2021-01-01'), 'e1');

TRUNCATE TABLE test.events;
```

If adding data that fits multiple partitions => truncate fails, only first partition removed:
[clickhouse-server.err.log](https://github.com/ClickHouse/ClickHouse/files/7891425/clickhouse-server.err.log)

```
INSERT INTO test.events(event_day, event_id)
VALUES 
	(toDate('2021-01-01'), 'e1'),
	(toDate('2022-01-01'), 'e2');

TRUNCATE TABLE test.events;
 => exception
 DB::Exception: Cannot add ZooKeeper operation because query is executed. It's a bug. (LOGICAL_ERROR)

SELECT * from system.parts 
WHERE database = 'test' and table ='events';  
=> 1 part left still, if trying additional TRUNCATE statements - those would fail also

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed logical error on `TRUNCATE` query in `Replicated` database. Fixes #33747. 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/DDLWorker.cpp [hunk 1]
```diff
@@ -715,6 +715,8 @@ bool DDLWorker::tryExecuteQueryOnLeaderReplica(
     if (zookeeper->exists(is_executed_path, nullptr, event))
     {
         LOG_DEBUG(log, "Task {} has already been executed by replica ({}) of the same shard.", task.entry_name, zookeeper->get(is_executed_path));
+        if (auto op = task.getOpToUpdateLogPointer())
```
Comment (nikitamikhaylov) [inline src/Interpreters/DDLWorker.cpp:718]: Curious about why do we need this if? The condition will always be true

File: src/Parsers/ASTSystemQuery.cpp [hunk 2]
```diff
@@ -181,6 +181,10 @@ void ASTSystemQuery::formatImpl(const FormatSettings & settings, FormatState &,
         else if (!disk.empty())
             print_identifier(disk);
     }
+    else if (type == Type::SYNC_DATABASE_REPLICA)
+    {
+        print_identifier(database->as<ASTIdentifier>()->name());
```
Comment (nikitamikhaylov) [inline src/Parsers/ASTSystemQuery.cpp:186]: Nice catch. I didn't think of it myself previously

**Review by nikitamikhaylov — APPROVED** [review]
