### PR TITLE
Fix stacktraces on MacOS

### LINKED ISSUE #53653: No stack trace on error on macOS w/Apple Silicon
**Describe what's wrong**

Upon handling an exception, ClickHouse fails to collect the stack trace.

For the sake of example, I opened two terminals: one with `clickhouse server` and one with `clickhouse client`.
On the client side, I executed

```
lihava-mbp.local :) select throwIf(1)

SELECT throwIf(1)

Query id: efb8fc2f-851a-402c-a8e1-174d901b2a98

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.8.1 revision 54465.

↙ Progress: 1.00 rows, 1.00 B (9.47 rows/s., 9.47 B/s.)
0 rows in set. Elapsed: 0.106 sec.

Received exception from server (version 23.8.1):
Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(1 :: 0) -> throwIf(1) UInt8 : 1'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO)
```

On the server I'm seeing these log messages:

```
2023.08.21 21:16:48.703584 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Debug> executeQuery: (from [::1]:50012) select throwIf(1) (stage: Complete)
2023.08.21 21:16:48.703749 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2023.08.21 21:16:48.703781 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.08.21 21:16:49.001595 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Error> executeQuery: Code: 395. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(1 :: 0) -> throwIf(1) UInt8 : 1'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO) (version 23.8.1.1) (from [::1]:50012) (in query: select throwIf(1)), Stack trace (when copying this message, always include the lines below):

<Empty trace>

2023.08.21 21:16:49.001631 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Error> TCPHandler: Code: 395. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(1 :: 0) -> throwIf(1) UInt8 : 1'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO), Stack trace (when copying this message, always include the lines below):

<Empty trace>

2023.08.21 21:16:49.001675 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Debug> TCPHandler: Processed in 0.29836775 sec.
2023.08.21 21:16:49.001704 [ 57290 ] {efb8fc2f-851a-402c-a8e1-174d901b2a98} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
```

**Does it reproduce on recent release?**

I reproduced this on:
- `master` branch
-  [v23.3.9.55-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.3.9.55-lts)

**How to reproduce**

* Run anything that throws, like `select throwIf(1)` and see the logs on the server

**Expected behavior**

Non-empty stack trace

**Error message and/or stacktrace**

Empty :)

**Additional context**

Additionally, I reproduced this issue on the VM with macOS 13.4.1.
I **could not reproduce this** on macOS 13.5 with Intel processor.
I also could not reproduce this on Ubuntu Server ARM, so the problem seems to be specific to macOS on Apple Silicon

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix stack unwinding on MacOS. This closes https://github.com/ClickHouse/ClickHouse/issues/53653

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit f416f4dc514ace21493f4ab5a7c65e9fcc0953bb with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59690/f416f4dc514ace21493f4ab5a7c65e9fcc0953bb/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59690/f416f4dc514ace21493f4ab5a7c65e9fcc0953bb/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nikitamikhaylov** [comment]
Previously ClickHouse binary natively compiled on MacOS was writing lot of errors like 
```
libunwind: malformed __unwind_info at 0x112A73C54 bad second level page
```
whereas cross-compiled binary just had empty traces.
I looked into the LLDB source code and found out that it uses `backtrace` function from MacOS SDK (somewhat like libc or system library). ClickHouse already depends on it, so this change won't make anything any worse
```
❯ otool -L ./clickhouse
./clickhouse:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2202.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

With this patch I was able to get stacktraces like this: 
```
❯ ./clickhouse local --stacktrace -q "SELECT throwIf(1)"
Code: 395. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(1 :: 0) -> throwIf(1) UInt8 : 1'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO), Stack trace (when copying this message, always include the lines below):

0. std::exception::capture()
1. std::exception::exception[abi:v15000]()
2. Poco::Exception::Exception(String const&, int)
3. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)
4. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)
5. DB::Exception::Exception(String&&, int, bool)
6. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&)
7. COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::(anonymous namespace)::FunctionThrowIf::execute<char8_t>(DB::IColumn const*, std::optional<String> const&, std::optional<int> const&) const
8. DB::(anonymous namespace)::FunctionThrowIf::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const
9. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const
10. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
11. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
12. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const
13. DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool)
14. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const
15. DB::ExpressionTransform::transform(DB::Chunk&)
16. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&)
17. DB::ISimpleTransform::work()
18. DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
19. DB::ExecutionThreadContext::executeTask()
20. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*)
21. DB::PipelineExecutor::executeSingleThread(unsigned long)
22. DB::PipelineExecutor::executeImpl(unsigned long, bool)
23. DB::PipelineExecutor::execute(unsigned long, bool)
24. DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
25. DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0::operator()() const
26. decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&>()()) std::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&)
27. decltype(auto) std::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&, std::tuple<>&, std::__tuple_indices<>)
28. decltype(auto) std::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&, std::tuple<>&)
29. ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&&)::'lambda'()::operator()()
30. decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0>()()) std::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&&)
31. void std::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long long)::$_0&&)::'lambda'()&)
```

File: contrib/libunwind-cmake/unwind-override.c [hunk 1]
```diff
@@ -1,6 +1,10 @@
 #include <libunwind.h>
 
+#if defined(__APPLE__)
+int backtrace(void ** buffer, int size);
```
Comment (alexey-milovidov) [inline contrib/libunwind-cmake/unwind-override.c:4]: Missing comments.

File: src/Common/StackTrace.cpp [hunk 2]
```diff
@@ -24,6 +24,11 @@
 
 #include "config.h"
 
+
+#if defined(__APPLE__)
+#include "execinfo.h"
```
Comment (alexey-milovidov) [inline src/Common/StackTrace.cpp:29]: Missing comments.

File: src/Common/StackTrace.cpp [hunk 3]
```diff
@@ -267,12 +272,45 @@ void StackTrace::forEachFrame(
...
+    };
+
+    char** strs = ::backtrace_symbols(frame_pointers.data(), static_cast<int>(size));
+
     for (size_t i = offset; i < size; ++i)
     {
         StackTrace::Frame current_frame;
         current_frame.virtual_addr = frame_pointers[i];
+        auto splitted = split_by_whitespace(strs[i]);
+        assert(splitted.size() >= 6);
```
Comment (alexey-milovidov) [inline src/Common/StackTrace.cpp:308]: Missing comments about "6".

File: src/Common/StackTrace.cpp [hunk 4]
```diff
@@ -267,12 +272,45 @@ void StackTrace::forEachFrame(
...
+        current_frame.symbol = splitted[3];
```
Comment (alexey-milovidov) [inline src/Common/StackTrace.cpp:309]: Missing comments.

File: src/Common/StackTrace.cpp [hunk 5]
```diff
@@ -306,7 +344,11 @@ StackTrace::StackTrace(const ucontext_t & signal_context)
 
 void StackTrace::tryCapture()
 {
+#ifdef __APPLE__
+    size = ::backtrace(frame_pointers.data(), capacity);
```
Comment (alexey-milovidov) [inline src/Common/StackTrace.cpp:348]: Most likely, it is not async-signal safe, hence cannot be used.

File: contrib/libunwind-cmake/unwind-override.c [hunk 6]
```diff
@@ -1,6 +1,10 @@
...
+#else
 int backtrace(void ** buffer, int size)
 {
     return unw_backtrace(buffer, size);
```
Comment (alexey-milovidov) [inline contrib/libunwind-cmake/unwind-override.c:8]: Why exactly it doesn't work on Macintosh?

File: src/Common/StackTrace.cpp (hunk 5 above)
Comment (nikitamikhaylov) [reply src/Common/StackTrace.cpp:348]: Indeed, random page says it is not async-signal safe https://forums.developer.apple.com/forums/thread/113742

But maybe it is still Ok for synchronous unwinding like exceptions?

File: contrib/libunwind-cmake/unwind-override.c (hunk 6 above)
Comment (nikitamikhaylov) [reply contrib/libunwind-cmake/unwind-override.c:8]: `unw_backtrace` is a function from libunwind, but I would love `backtrace` to be used from dynamically linked library. 

Moreover `exception` header from libcxx in our contrib was patched to use `unw_backtrace` and thus libunwind, so I patched it to use `backtrace`.

File: src/Common/StackTrace.cpp (hunk 5 above)
Comment (alexey-milovidov) [reply src/Common/StackTrace.cpp:348]: Yes, totally ok for exceptions, not ok for crashes.

File: contrib/libunwind-cmake/unwind-override.c (hunk 6 above)
Comment (alexey-milovidov) [reply contrib/libunwind-cmake/unwind-override.c:8]: It is prohibitive on Linux with glibc.
glibc uses an idiotic implementation: - it locates a .so at runtime and does dlopen.

It also does not work on Musl.

But I thought that it could be acceptable on Mac.

File: src/Common/StackTrace.cpp (hunk 5 above)
Comment (nikitamikhaylov) [reply src/Common/StackTrace.cpp:364]: Profiler is not working on MacOS due to the lack of PHDR cache. So this will be used only for exceptions and places where you write `StackTrace()::toString()`.

File: src/Common/StackTrace.cpp (hunk 3 above)
Comment (nikitamikhaylov) [reply src/Common/StackTrace.cpp]: I wrote the comment, but will also paste it here. The `backtrace_symbols` returns you an array of strings in format like below. The symbol name is mangled and we need to split everything to be able to demangle it. 
```
(lldb) run local -q "SELECT throwIf(1)"
Process 9100 launched: '/Users/nikitamikhaylov/ClickHouse/ClickHouse/build/programs/clickhouse' (arm64)
0   clickhouse                          0x0000000100028024 _ZNSt9exception7captureEv + 36
1   clickhouse                          0x0000000100027ff0 _ZNSt9exceptionC2B6v15000Ev + 48
2   clickhouse                          0x0000000118c11144 _ZN4Poco9ExceptionC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEi + 36
3   clickhouse                          0x000000010843663c _ZN2DB9ExceptionC2EONS0_13MessageMaskedEib + 60
4   clickhouse                          0x00000001084367a0 _ZN2DB9ExceptionC1EONS0_13MessageMaskedEib + 64
5   clickhouse                          0x0000000100013434 _ZN2DB9ExceptionC1EONSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEib + 84
6   clickhouse                          0x000000010001330c _ZN2DB9ExceptionC1IJNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEEi22FormatStringHelperImplIJDpNS2_13type_identityIT_E4typeEEEDpOSB_ + 300
7   clickhouse                          0x0000000106c5cd08 _ZNK2DB12_GLOBAL__N_115FunctionThrowIf7executeIDuEEN3COWINS_7IColumnEE13immutable_ptrIS4_EEPKS4_RKNSt3__18optionalINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEEEERKNSB_IiEE + 456
8   clickhouse                          0x0000000106c5bb98 _ZNK2DB12_GLOBAL__N_115FunctionThrowIf11executeImplERKNSt3__16vectorINS_21ColumnWithTypeAndNameENS2_9allocatorIS4_EEEERKNS2_10shared_ptrIKNS_9IDataTypeEEEm + 1272
9   clickhouse                          0x000000010001654c _ZNK2DB35FunctionToExecutableFunctionAdaptor11executeImplERKNSt3__16vectorINS_21ColumnWithTypeAndNameENS1_9allocatorIS3_EEEERKNS1_10shared_ptrIKNS_9IDataTypeEEEm + 76
10  clickhouse                          0x000000010f44fb94 _ZNK2DB19IExecutableFunction35executeWithoutLowCardinalityColumnsERKNSt3__16vectorINS_21ColumnWithTypeAndNameENS1_9allocatorIS3_EEEERKNS1_10shared_ptrIKNS_9IDataTypeEEEmb + 628
11  clickhouse                          0x000000010f450ae8 _ZNK2DB19IExecutableFunction27executeWithoutSparseColumnsERKNSt3__16vectorINS_21ColumnWithTypeAndNameENS1_9allocatorIS3_EEEERKNS1_10shared_ptrIKNS_9IDataTypeEEEmb + 1640
12  clickhouse                          0x000000010f451ac8 _ZNK2DB19IExecutableFunction7executeERKNSt3__16vectorINS_21ColumnWithTypeAndNameENS1_9allocatorIS3_EEEERKNS1_10shared_ptrIKNS_9IDataTypeEEEmb + 1448
13  clickhouse                          0x00000001124f80b0 _ZN2DBL13executeActionERKNS_17ExpressionActions6ActionERNS_12_GLOBAL__N_116ExecutionContextEb + 1232
14  clickhouse                          0x00000001124f7310 _ZNK2DB17ExpressionActions7executeERNS_5BlockERmb + 720
15  clickhouse                          0x0000000115ffb4a8 _ZN2DB19ExpressionTransform9transformERNS_5ChunkE + 136
16  clickhouse                          0x000000010bf5e9ec _ZN2DB16ISimpleTransform9transformERNS_5ChunkES2_ + 44
17  clickhouse                          0x0000000115917624 _ZN2DB16ISimpleTransform4workEv + 100
18  clickhouse                          0x0000000115958d2c _ZN2DBL10executeJobEPNS_14ExecutingGraph4NodeEPNS_20ReadProgressCallbackE + 44
19  clickhouse                          0x0000000115958a5c _ZN2DB22ExecutionThreadContext11executeTaskEv + 284
20  clickhouse                          0x00000001159624f0 _ZN2DB16PipelineExecutor15executeStepImplEmPNSt3__16atomicIbEE + 336
21  clickhouse                          0x000000011596296c _ZN2DB16PipelineExecutor19executeSingleThreadEm + 44
22  clickhouse                          0x00000001159615c8 _ZN2DB16PipelineExecutor11executeImplEmb + 232
23  clickhouse                          0x0000000115960d70 _ZN2DB16PipelineExecutor7executeEmb + 176
24  clickhouse                          0x000000011597a4e8 _ZN2DBL14threadFunctionERNS_28PullingAsyncPipelineExecutor4DataENSt3__110shared_ptrINS_11ThreadGroupEEEmb + 296
25  clickhouse                          0x000000011597a37c _ZZN2DB28PullingAsyncPipelineExecutor4pullERNS_5ChunkEyENK3$_0clEv + 124
26  clickhouse                          0x000000011597a2d8 _ZNSt3__18__invokeB6v15000IRZN2DB28PullingAsyncPipelineExecutor4pullERNS1_5ChunkEyE3$_0JEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOS7_DpOS8_ + 24
27  clickhouse                          0x000000011597a29c _ZNSt3__118__apply_tuple_implB6v15000IRZN2DB28PullingAsyncPipelineExecutor4pullERNS1_5ChunkEyE3$_0RNS_5tupleIJEEEJEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE + 28
28  clickhouse                          0x000000011597a1a0 _ZNSt3__15applyB6v15000IRZN2DB28PullingAsyncPipelineExecutor4pullERNS1_5ChunkEyE3$_0RNS_5tupleIJEEEEEDcOT_OT0_ + 32
29  clickhouse                          0x000000011597a0ac _ZZN24ThreadFromGlobalPoolImplILb1EEC1IZN2DB28PullingAsyncPipelineExecutor4pullERNS2_5ChunkEyE3$_0JEEEOT_DpOT0_ENUlvE_clEv + 140
30  clickhouse                          0x0000000115979ff8 _ZNSt3__18__invokeB6v15000IRZN24ThreadFromGlobalPoolImplILb1EEC1IZN2DB28PullingAsyncPipelineExecutor4pullERNS4_5ChunkEyE3$_0JEEEOT_DpOT0_EUlvE_JEEEDTclclsr3stdE7declvalIS9_EEspclsr3stdE7declvalISB_EEEESA_SD_ + 24
31  clickhouse                          0x0000000115979fb8 _ZNSt3__128__invoke_void_return_wrapperIvLb1EE6__callIJRZN24ThreadFromGlobalPoolImplILb1EEC1IZN2DB28PullingAsyncPipelineExecutor4pullERNS6_5ChunkEyE3$_0JEEEOT_DpOT0_EUlvE_EEEvDpOT_ + 24
Code: 395. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(1 :: 0) -> throwIf(1) UInt8 : 1'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO)
```

**Review by alesapin — APPROVED** [review]
