### PR TITLE
Fixed type conversion from Date/Date32 to DateTime64 when querying with DateTime64 index

### LINKED ISSUE #40707: DateTime64 and today()
```sql
SELECT today()
┌────today()─┐
│ 2022-08-27 │
└────────────┘

CREATE TABLE data (timestamp DateTime64) ENGINE MergeTree
PARTITION BY toYYYYMMDD(timestamp) ORDER BY (timestamp);

INSERT INTO data  SELECT today();
SELECT * FROM data;
┌───────────────timestamp─┐
│ 2022-08-27 00:00:00.000 │
└─────────────────────────┘

SELECT COUNT() FROM data WHERE timestamp <= today();
┌─count()─┐
│       0 │  -- expected 1
└─────────┘

SELECT COUNT() FROM data WHERE timestamp <= '2022-08-27';
┌─count()─┐
│       1 │
└─────────┘

SELECT COUNT() FROM data WHERE timestamp <= toDateTime(today());
┌─count()─┐
│       1 │
└─────────┘

SELECT COUNT() FROM data WHERE identity(timestamp) <= today();
┌─count()─┐
│       1 │
└─────────┘

```

### PR DESCRIPTION
**Pull request by lucas-tubi**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fixed type conversion from Date/Date32 to DateTime64 when querying with DateTime64 index

### Documentation entry for user-facing changes

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

Fixed https://github.com/ClickHouse/ClickHouse/issues/40707

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 864ba0602925da15acacc74ffb686dd1f4ca4165 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50280/864ba0602925da15acacc74ffb686dd1f4ca4165/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Interpreters/convertFieldToType.cpp [hunk 1]
```diff
@@ -192,6 +192,16 @@ Field convertFieldToTypeImpl(const Field & src, const IDataType & type, const ID
     {
         return static_cast<const DataTypeDateTime &>(type).getTimeZone().fromDayNum(DayNum(src.get<Int32>()));
     }
+    else if (which_type.isDateTime64() && which_from_type.isDate())
+    {
+        const auto value = static_cast<const DataTypeDateTime64 &>(type).getTimeZone().fromDayNum(DayNum(src.get<UInt64>()));
+        return DecimalUtils::decimalFromComponentsWithMultiplier<DateTime64>(value, 0, 1);
```
Comment (Enmk) [inline src/Interpreters/convertFieldToType.cpp:198]: it looks like you need to use `DecimalBase::getScaleMultiplier()` instead of `1` here and below. Otherwise the produced returned value is always as if it was made for `DateTime64(1)`.

**Comment by lucas-tubi** [comment]
@Enmk thanks for your update. your pr has been merged.

File: src/Interpreters/convertFieldToType.cpp [hunk 2]
```diff
@@ -192,6 +192,22 @@ Field convertFieldToTypeImpl(const Field & src, const IDataType & type, const ID
     {
         return static_cast<const DataTypeDateTime &>(type).getTimeZone().fromDayNum(DayNum(src.get<Int32>()));
```
Comment (lucas-tubi) [inline src/Interpreters/convertFieldToType.cpp:193]: should we replace `DayNum` with `ExtendedDayNum` here as well?

**Review by evillique — APPROVED** [review]

**Comment by UnamedRus** [comment]
Can we backport it to 23.3 may be?

Query return wrong result on lts release?
