### PR TITLE
A few more parquet fixes

### LINKED ISSUE #87306: Code: 117. DB::Exception: Dictionary page size out of bounds when reading a Parquet file with input_format_parquet_use_native_reader_v3
### Company or project name

got this error when reading this Parquet file (iris_file.parquet) in 25.8.1

```
clickhouse-local --query "select * from file('iris_file.parquet','Parquet') limit 1 format CSVWithNames  settings input_format_parquet_use_native_reader_v3 = 1"
"sepal.length","sepal.width","petal.length","petal.width","variety"
Code: 117. DB::Exception: Dictionary page size out of bounds: 39 > 26: read stage: MainData: column: variety: (in file/uri /iris.parquet): While executing ParquetV3BlockInputFormat: While executing File. (INCORRECT_DATA)
```

### Describe what's wrong

it works with input_format_parquet_use_native_reader_v3 = 0 but not input_format_parquet_use_native_reader_v3 = 1, so probably a regression

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```
clickhouse-local --query "select * from file('iris_file.parquet','Parquet') limit 1 format CSVWithNames  settings input_format_parquet_use_native_reader_v3 = 1"
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
In parquet writer, emit `created_by` string in correct format, e.g. `ClickHouse version 25.10.1 (build 5b1dfb14925db8901a4e9202cd5d63c11ecfbb9f)` instead of `ClickHouse v25.9.1.1-testing`.
Fix parquet reader compatibility with bad files written by old parquet-mr.

---

This PR is stacked on top of https://github.com/ClickHouse/ClickHouse/pull/87600 , review only commits starting from "A few more parquet fixes".

Closes https://github.com/ClickHouse/ClickHouse/issues/87306

* Workaround for files written by old duckdb with incorrect data_page_offset.
* Make parquet writer emit `created_by` string in correct format (according to `parquet.thrift`): `ClickHouse version 25.10.1 (build 5b1dfb14925db8901a4e9202cd5d63c11ecfbb9f)` instead of `ClickHouse v25.9.1.1-testing`.
* In the old parquet reader, unbreak a workaround for another workaround to allow reading bad files written by old parquet-mr.
* Fixed `clickhouse-test` failing if `diff` output is not valid utf8.
* Replaced `00900_long_parquet_load.sh` with `00900_long_parquet_load_2.sh` that:
  * Doesn't use an additional python script and arrow's parquet-reader tool (which is broken: https://github.com/ClickHouse/arrow/pull/72 ).
  * Picks up newly added files automatically without needing to do some manual steps which no one knows about.
  * Doesn't double the number of files in `data_parquet/`.
  * Is simpler.
  * But: the `.reference` file needs to be updated whenever a file is added to `data_parquet/` or schema inference logic changes.

### CODE REVIEW

File: src/Formats/SchemaInferenceUtils.cpp [hunk 1]
```diff
@@ -1644,6 +1644,11 @@ static DataTypePtr adjustNullableRecursively(DataTypePtr type, bool make_nullabl
     if (type->hasCustomName())
         return makeNullableSafe(type);
 
+    /// Leave named compound types unchanged.
+    /// E.g. don't turn `Point` into `Tuple(Nullable(Float64), Nullable(Float64))`.
+    if (type->hasCustomName())
+        return makeNullableSafe(type);
+
```
Comment (rienath) [inline src/Formats/SchemaInferenceUtils.cpp]: This is a duplicate of the previous few lines

File: src/Processors/Formats/Impl/Parquet/Reader.cpp [hunk 2]
```diff
@@ -212,6 +212,33 @@ parq::FileMetaData Reader::readFileMetaData(Prefetcher & prefetcher)
...
+            {
+                if (!col.__isset.offset_index_offset && col.meta_data.__isset.dictionary_page_offset)
+                {
+                    col.meta_data.data_page_offset = col.meta_data.dictionary_page_offset;
+                    col.meta_data.__isset.dictionary_page_offset = false;
+                    col.meta_data.dictionary_page_offset = 0;
+                }
+            }
+        }
+    }
```
Comment (rienath) [inline src/Processors/Formats/Impl/Parquet/Reader.cpp:240]: Pure curiosity: do we have to support all parquet files generated by broken writers of the past or we are selective?

File: src/Processors/Formats/Impl/Parquet/Reader.cpp [hunk 3]
```diff
@@ -212,6 +212,33 @@ parq::FileMetaData Reader::readFileMetaData(Prefetcher & prefetcher)
...
+    ///      present. Instead, data_page_offset points to the dictionary page.
+    ///  (2) Old DuckDB versions (<= 0.10.2) wrote incorrect data_page_offset when dictionary is
+    ///      present.
+    /// We work around (1) in initializePage by allowing dictionary page in place of data page.
+    /// We work around (2) here by converting it to case (1):
+    ///   data_page_offset = dictionary_page_offset
+    ///   dictionary_page_offset.reset()
+    /// Note: newer versions of DuckDB include version number in the `created_by` string, so this
+    /// `if` only applies to relatively old versions.
+    if (file_metadata.created_by == "DuckDB")
```
Comment (rienath) [inline src/Processors/Formats/Impl/Parquet/Reader.cpp:226]: Is there a test for this?

Comment (rienath) [inline src/Processors/Formats/Impl/Parquet/Reader.cpp:226]: But was this fixed in later versions that include number? If yes, it would be clearer if this was mentioned. If no, maybe we should use `.starts_with(...)` instead

File: tests/queries/0_stateless/00900_long_parquet_load_2.sh [hunk 4]
```diff
@@ -0,0 +1,53 @@
+#!/usr/bin/env bash
+# Tags: long, no-fasttest, no-asan, no-msan, no-tsan
```
Comment (rienath) [inline tests/queries/0_stateless/00900_long_parquet_load_2.sh:2]: Any motivation to avoid asan, msan and tsan? I only see benefits

File: tests/queries/0_stateless/00900_long_parquet_load_2.sh [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+
+# set -x
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+DATA_DIR=$CUR_DIR/data_parquet
+
+# TODO: Known issues to investigate:
```
Comment (rienath) [inline tests/queries/0_stateless/00900_long_parquet_load_2.sh]: Let's keep using `TODO [parquet]` as in the other PRs for consistency and to make it easier to find todo's later

File: tests/queries/0_stateless/00900_long_parquet_load_2.sh [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+for NAME in $(find "$DATA_DIR"/*.parquet -print0 | xargs -0 -n 1 basename | LC_ALL=C sort | grep -vFf <(printf '%s\n' "${EXCLUDE[@]}")); do
+    echo "=== Try load data from $NAME"
+
+    SCHEMA=`${CLICKHOUSE_LOCAL} --query="DESC file('$DATA_DIR/$NAME')"`
+
+    # We want to read the file once and get both a hash of the whole data and a sample of a few
+    # pseudorandomly chosen rows. We use a dummy GROUP BY WITH TOTALS for that.
+    # (Maybe the unnecessary GROUP BY could be expensive if there are lots of rows, but these test
+    #  files don't have lots of rows or they would be too big to check into git.)
+    # TODO: Delete the input_format_parquet_enable_json_parsing=0 when cityHash64 supports JSON:
```
Comment (rienath) [inline tests/queries/0_stateless/00900_long_parquet_load_2.sh]: Here too

File: tests/queries/0_stateless/data_parquet/userdata1.parquet.columns [hunk 7]
```diff
@@ -1 +0,0 @@
-`registration_dttm` Nullable(Int64), `id` Nullable(Int32), `first_name` Nullable(String), `last_name` Nullable(String), `email` Nullable(String), `gender` Nullable(String), `ip_address` Nullable(String), `cc` Nullable(String), `country` Nullable(String), `birthdate` Nullable(String), `salary` Nullable(Float64), `title` Nullable(String), `comments` Nullable(String)
```
Comment (rienath) [inline tests/queries/0_stateless/data_parquet/userdata1.parquet.columns:1]: By deleting all these files, aren't we deleting a large number of tests that we had?

**Review by rienath — COMMENTED** [review]
Thanks for the wait, here's the review. One minor general comment: Parquet improvements deserve to be in the changelog. Let's change the category

File: src/Processors/Formats/Impl/Parquet/Reader.cpp (hunk 2 above)
Comment (al13n321) [reply src/Processors/Formats/Impl/Parquet/Reader.cpp:240]: People run into it and report issues, I think we should maximize compatibility when it's not complex. The (1) is from out preexisting tests, the (2) is from a recently reported issue with a file from some collection of test files for parquet format (apparently old, but the web page didn't have a date, so it was natural for the reader to assume that it's legit).

File: src/Processors/Formats/Impl/Parquet/Reader.cpp (hunk 3 above)
Comment (al13n321) [reply src/Processors/Formats/Impl/Parquet/Reader.cpp:226]: Yes, `iris.parquet` loaded by `00900_long_parquet_load_2.sh`.

File: tests/queries/0_stateless/00900_long_parquet_load_2.sh (hunk 4 above)
Comment (al13n321) [reply tests/queries/0_stateless/00900_long_parquet_load_2.sh:2]: The test is too slow.

File: tests/queries/0_stateless/data_parquet/userdata1.parquet.columns (hunk 7 above)
Comment (al13n321) [reply tests/queries/0_stateless/data_parquet/userdata1.parquet.columns:1]: The test now directly looks for `.parquet` files (and uses schema inference) without needing `.column` files next to them.

**Review by rienath — COMMENTED** [review]
LGTM. Let's merge https://github.com/ClickHouse/ClickHouse/pull/87600, check the CI for this and merge

**Review by rienath — APPROVED** [review]

File: tests/queries/0_stateless/00900_long_parquet_load_2.sh [hunk 8]
```diff
@@ -0,0 +1,52 @@
+#!/usr/bin/env bash
```
Comment (vitlibar) [inline tests/queries/0_stateless/00900_long_parquet_load_2.sh:1]: This test seems flaky, see [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMDkwMF9sb25nX3BhcnF1ZXRfbG9hZF8yJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnTm9uZScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==).

Comment (azat) [reply tests/queries/0_stateless/00900_long_parquet_load_2.sh:1]: https://github.com/ClickHouse/ClickHouse/issues/89363

Comment (azat) [reply tests/queries/0_stateless/00900_long_parquet_load_2.sh:1]: https://github.com/ClickHouse/ClickHouse/pull/89383
