### PR TITLE
Fix error in addMonths with floating point argument

### LINKED ISSUE #11377: addMonths: Field::get: assertion failed
```
SELECT addMonths(materialize(toDateTime('2017-11-05 08:07:47')), 1.)
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When adding floating point number of intervals to date/datetime, the result may be calculated incorrectly. This fixes #11377.

Detailed description:

It is rounded to integer.
You may consider more sophisticated logic but it's way more difficult (say add 1.5 months).

### CODE REVIEW

File: src/Functions/FunctionDateOrDateTimeAddInterval.h [hunk 1]
```diff
@@ -324,13 +324,16 @@ struct DateTimeAddIntervalImpl
             const IColumn & delta_column = *block.getByPosition(arguments[1]).column;
 
             if (const auto * delta_const_column = typeid_cast<const ColumnConst *>(&delta_column))
-                op.vectorConstant(sources->getData(), col_to->getData(), delta_const_column->getField().get<Int64>(), time_zone);
+                op.vectorConstant(sources->getData(), col_to->getData(), delta_const_column->getInt(0), time_zone);
```
Comment (alexey-milovidov) [inline src/Functions/FunctionDateOrDateTimeAddInterval.h:327]: Bugfix is in this line.

**Review by akuzm — APPROVED** [review]
