### PR TITLE
Fix ALTER column with column names with dots

### LINKED ISSUE #37907: MODIFY ALTER Column AFTER works incorrectly with column names that contain dots
I experienced a bug with MODIFY COLUMN when trying to change column order in table that contains columns with dots in their titles. As a result, column locates after wrong column.

Clickhouse Version: 22.1.3.7

**How to reproduce**

1. Creating table:
```
CREATE TABLE ModifyAfterBug
(
    id String,
    `abc.3` String,
    `abc.2` String,
    `abc` String
)
    ENGINE MergeTree()
    ORDER BY id
    PRIMARY KEY id;
```
2.  Checking column order:  
`describe table ModifyAfterBug`

| name | type | default\_type | default\_expression | comment | codec\_expression | ttl\_expression |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| id | String |  |  |  |  |  |
| abc.3 | String |  |  |  |  |  |
| abc.2 | String |  |  |  |  |  |
| abc | String |  |  |  |  |  |

3. Checking if AFTER works with `id` column, got expected result
```
ALTER TABLE ModifyAfterBug
    MODIFY COLUMN `abc.2` String AFTER `id`;
```
`describe table ModifyAfterBug;`

| name | type | default\_type | default\_expression | comment | codec\_expression | ttl\_expression |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| id | String |  |  |  |  |  |
| abc.2 | String |  |  |  |  |  |
| abc.3 | String |  |  |  |  |  |
| abc | String |  |  |  |  |  |

4. Checking if AFTER works with `abc` column, got unexpected result
```
ALTER TABLE ModifyAfterBug
    MODIFY COLUMN `abc.2` String AFTER abc;
```

| name | type | default\_type | default\_expression | comment | codec\_expression | ttl\_expression |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| id | String |  |  |  |  |  |
| abc.3 | String |  |  |  |  |  |
| abc.2 | String |  |  |  |  |  |
| abc | String |  |  |  |  |  |

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect work of MODIFY ALTER Column with column names that contain dots. Closes https://github.com/ClickHouse/ClickHouse/issues/37907

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Storages/ColumnsDescription.cpp [hunk 1]
```diff
@@ -173,16 +173,14 @@ static auto getNameRange(const ColumnsDescription::ColumnsContainer & columns, c
...
-        if (begin->name == name_without_dot)
-            return std::make_pair(begin, std::next(begin));
-
-        if (startsWith(begin->name, name_with_dot))
-            break;
+        if (it->name == name_without_dot)
+            return std::make_pair(it, std::next(it));
     }
 
+    auto begin = std::find_if(columns.begin(), columns.end(), [&](const auto & column){ return startsWith(column.name, name_with_dot); });
```
Comment (alesapin) [inline src/Storages/ColumnsDescription.cpp:182]: Maybe just return previous code, but assign `begin` before `break`?

Comment (Avogar) [reply src/Storages/ColumnsDescription.cpp:182]: > but assign begin before break

What do you mean?
The problem was in that we can have column with name `name_without_dot` and columns that start with `name_with_dot`. So first we need to check if we have column with name `name_without_dot` and if not - check if we have names that start with `name_with_dot`. Previously we could stop searching name `name_without_dot` because we found name that starts with `name_with_dot`, and it caused bugs

Comment (alesapin) [reply src/Storages/ColumnsDescription.cpp:182]: Clear to me now, but maybe add this to comments.

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Integration: `No space left on device`
