### PR TITLE
Fix crash in unknown catalog type

### LINKED ISSUE #88819: Crash on SHOW TABLES FROM DataLakeCatalog database if catalog_type is not specified
### Company or project name

_No response_

### Describe what's wrong
Crash on `SHOW TABLES FROM` DataLakeCatalog database if catalog_type is not specified.
```
CREATE DATABASE datalake
ENGINE = DataLakeCatalog('http://ice-rest-catalog:5000', admin, password)
SETTINGS storage_endpoint = 'http://minio:9000/warehouse', warehouse = 'd'

Query id: 74dc873d-416e-41f9-9aac-df280c6911ed

Ok.

0 rows in set. Elapsed: 0.026 sec. 

clickhouse1 :) show tables from datalake

SHOW TABLES FROM datalake

Query id: 8bc97f2c-c0bf-475c-afe3-a0d8a3f97a01

[clickhouse1] 2025.10.20 23:49:23.875444 [ 36 ] <Fatal> BaseDaemon: ########################################
[clickhouse1] 2025.10.20 23:49:23.875546 [ 36 ] <Fatal> BaseDaemon: (version 25.8.10.7 (official build), build id: 56195F97A6E10AC78F683C99CA2D8F027C56F3C0, git hash: 02ec3a1ea1e08fb18d2d9638f00b2b557fa1cc1c) (from thread 43) (query_id: 8bc97f2c-c0bf-475c-afe3-a0d8a3f97a01) (query: show tables from datalake) Received signal Segmentation fault (11)
[clickhouse1] 2025.10.20 23:49:23.875599 [ 36 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
[clickhouse1] 2025.10.20 23:49:23.875642 [ 36 ] <Fatal> BaseDaemon: Stack trace: 0x000000001718b3b9 0x00000000158301e0 0x000000001583a83a 0x000000001a14e8eb 0x000000001a14c61f 0x000000001a046d63 0x0000000017faa716 0x0000000017faa1de 0x0000000018379b92 0x0000000018371e0b 0x00000000183dde25 0x0000000018379b92 0x0000000018371e0b 0x0000000019a4b78a 0x0000000019a6d7d9 0x000000001ef90207 0x000000001ef90699 0x000000001ef56cc7 0x000000001ef550c1 0x00007671f04a4ac3 0x00007671f05368c0
[clickhouse1] 2025.10.20 23:49:23.875771 [ 36 ] <Fatal> BaseDaemon: 2. DB::DatabaseDataLake::getLightweightTablesIterator(std::shared_ptr<DB::Context const>, std::function<bool (String const&)> const&, bool, bool) const @ 0x000000001718b3b9
[clickhouse1] 2025.10.20 23:49:23.875836 [ 36 ] <Fatal> BaseDaemon: 3. DB::detail::getFilteredTables(DB::ActionsDAG::Node const*, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::Context const>, bool) @ 0x00000000158301e0
[clickhouse1] 2025.10.20 23:49:23.875881 [ 36 ] <Fatal> BaseDaemon: 4. DB::ReadFromSystemTables::applyFilters(DB::ActionDAGNodes) @ 0x000000001583a83a
[clickhouse1] 2025.10.20 23:49:23.875940 [ 36 ] <Fatal> BaseDaemon: 5. DB::QueryPlanOptimizations::optimizePrimaryKeyConditionAndLimit(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>> const&) @ 0x000000001a14e8eb
[clickhouse1] 2025.10.20 23:49:23.876013 [ 36 ] <Fatal> BaseDaemon: 6. DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&) @ 0x000000001a14c61f
[clickhouse1] 2025.10.20 23:49:23.876061 [ 36 ] <Fatal> BaseDaemon: 7. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001a046d63
[clickhouse1] 2025.10.20 23:49:23.876110 [ 36 ] <Fatal> BaseDaemon: 8. DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x0000000017faa716
[clickhouse1] 2025.10.20 23:49:23.876145 [ 36 ] <Fatal> BaseDaemon: 9. DB::InterpreterSelectQueryAnalyzer::execute() @ 0x0000000017faa1de
[clickhouse1] 2025.10.20 23:49:23.876209 [ 36 ] <Fatal> BaseDaemon: 10. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018379b92
[clickhouse1] 2025.10.20 23:49:23.876265 [ 36 ] <Fatal> BaseDaemon: 11. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018371e0b
[clickhouse1] 2025.10.20 23:49:23.876310 [ 36 ] <Fatal> BaseDaemon: 12. DB::InterpreterShowTablesQuery::execute() @ 0x00000000183dde25
[clickhouse1] 2025.10.20 23:49:23.876362 [ 36 ] <Fatal> BaseDaemon: 13. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018379b92
[clickhouse1] 2025.10.20 23:49:23.876403 [ 36 ] <Fatal> BaseDaemon: 14. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018371e0b
[clickhouse1] 2025.10.20 23:49:23.876459 [ 36 ] <Fatal> BaseDaemon: 15. DB::TCPHandler::runImpl() @ 0x0000000019a4b78a
[clickhouse1] 2025.10.20 23:49:23.876501 [ 36 ] <Fatal> BaseDaemon: 16. DB::TCPHandler::run() @ 0x0000000019a6d7d9
[clickhouse1] 2025.10.20 23:49:23.876557 [ 36 ] <Fatal> BaseDaemon: 17. Poco::Net::TCPServerConnection::start() @ 0x000000001ef90207
[clickhouse1] 2025.10.20 23:49:23.876621 [ 36 ] <Fatal> BaseDaemon: 18. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef90699
[clickhouse1] 2025.10.20 23:49:23.876655 [ 36 ] <Fatal> BaseDaemon: 19. Poco::PooledThread::run() @ 0x000000001ef56cc7
[clickhouse1] 2025.10.20 23:49:23.876700 [ 36 ] <Fatal> BaseDaemon: 20. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef550c1
[clickhouse1] 2025.10.20 23:49:23.876788 [ 36 ] <Fatal> BaseDaemon: 21. ? @ 0x0000000000094ac3
[clickhouse1] 2025.10.20 23:49:23.876839 [ 36 ] <Fatal> BaseDaemon: 22. ? @ 0x00000000001268c0
[clickhouse1] 2025.10.20 23:49:24.048315 [ 36 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: F8D1DCA09AF2A47697409D15C10A70A0)
[clickhouse1] 2025.10.20 23:49:24.048492 [ 36 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[clickhouse1] 2025.10.20 23:49:24.048638 [ 36 ] <Fatal> BaseDaemon: Changed settings: use_uncompressed_cache = false, load_balancing = 'random', max_memory_usage = 10000000000, parallel_replicas_for_cluster_engines = false, allow_experimental_database_iceberg = true
Error on processing query: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, 127.0.0.1, local address: 127.0.0.1:48762. (ATTEMPT_TO_READ_AFTER_EOF) (version 25.8.10.7 (official build))

Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
CREATE DATABASE datalake
ENGINE = DataLakeCatalog('http://ice-rest-catalog:5000', admin, password)
SETTINGS storage_endpoint = 'http://minio:9000/warehouse', warehouse = 'd'
```
```sql
SHOW TABLES FROM datalake
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash in unknown catalog type. Resolves #88819

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/DataLake/DatabaseDataLake.cpp [hunk 1]
```diff
@@ -117,6 +117,9 @@ void DatabaseDataLake::validateSettings()
 
 std::shared_ptr<DataLake::ICatalog> DatabaseDataLake::getCatalog() const
 {
+    if (settings[DatabaseDataLakeSetting::catalog_type].value == DatabaseDataLakeCatalogType::NONE)
+        throw Exception(ErrorCodes::BAD_ARGUMENTS, "Unspecified catalog type");
+
```
Comment (divanik) [inline src/Databases/DataLake/DatabaseDataLake.cpp:123]: Put this logic to the switch condition below

File: src/Databases/DataLake/DatabaseDataLake.cpp
Comment (divanik) [inline src/Databases/DataLake/DatabaseDataLake.cpp:1]: In function getConfiguration you should throw a logical error if catalog type is None (it can't be None logically)

File: src/Databases/DataLake/DatabaseDataLake.cpp (hunk 1 above)
Comment (scanhex12) [reply src/Databases/DataLake/DatabaseDataLake.cpp:123]: For what? We have only one case here, it will look strange

File: src/Databases/DataLake/DatabaseDataLake.cpp
Comment (scanhex12) [reply src/Databases/DataLake/DatabaseDataLake.cpp:1]: This is unnecessary - we call getConfiguration only in tryGetTableImpl, but in this method we call getCatalog first

File: src/Databases/DataLake/DatabaseDataLake.cpp (hunk 1 above)
Comment (divanik) [reply src/Databases/DataLake/DatabaseDataLake.cpp:123]: Ok, as you wish

File: src/Databases/DataLake/DatabaseDataLake.cpp
Comment (divanik) [reply src/Databases/DataLake/DatabaseDataLake.cpp:1]: Hm, it is unnecessary now, but I mean that it is extra check for the future for similar cases

Comment (divanik) [reply src/Databases/DataLake/DatabaseDataLake.cpp:1]: I don't like the fact that we have a switch which exits normally when the value is not expected to exist. Let's either remove the branch of this switch and put the logical error to default, or just put a logical error as I suggested

**Review by divanik — APPROVED** [review]
