### PR TITLE
Fix union distinct

### LINKED ISSUE #27578: Incorrect count optimization with UNION DISTINCT
ClickHouse chooses a column to calculate `count`, and then UNION DISTINCT collapses the result set.
```
SELECT *
FROM system.databases
UNION DISTINCT
SELECT *
FROM system.databases

┌─name───┬─engine─────┬─data_path────────────────────────┬─metadata_path────────────────────────┬─uuid─────────────────────────────────┐
│ dict   │ Dictionary │ /var/lib/clickhouse/             │                                      │ 00000000-0000-0000-0000-000000000000 │
│ dw     │ Ordinary   │ /var/lib/clickhouse/data/dw/     │ /var/lib/clickhouse/metadata/dw/     │ 00000000-0000-0000-0000-000000000000 │
│ lf     │ Ordinary   │ /var/lib/clickhouse/data/lf/     │ /var/lib/clickhouse/metadata/lf/     │ 00000000-0000-0000-0000-000000000000 │
│ system │ Ordinary   │ /var/lib/clickhouse/data/system/ │ /var/lib/clickhouse/metadata/system/ │ 00000000-0000-0000-0000-000000000000 │
│ test   │ Ordinary   │ /var/lib/clickhouse/data/test/   │ /var/lib/clickhouse/metadata/test/   │ 00000000-0000-0000-0000-000000000000 │
└────────┴────────────┴──────────────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┘

5 rows in set. Elapsed: 0.002 sec.

SELECT count()
FROM
(
    SELECT *
    FROM system.databases
    UNION DISTINCT
    SELECT *
    FROM system.databases
)

┌─count()─┐
│       1 │
└─────────┘
```
ClickHouse chooses the `uuid` column to calculate `count`.
```
<Trace> ContextAccess (default): Access granted: SELECT(uuid) ON system.databases
<Trace> ContextAccess (default): Access granted: SELECT(uuid) ON system.databases
```

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix column filtering with union distinct in subquery. Closes https://github.com/ClickHouse/ClickHouse/issues/27578.

### CODE REVIEW

File: tests/queries/0_stateless/02008_test_union_distinct_in_subquery.sql [hunk 1]
```diff
@@ -0,0 +1,10 @@
+DROP DATABASE IF EXISTS db1;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02008_test_union_distinct_in_subquery.sql:1]: Maybe write another test - without different databases?

**Comment by alexey-milovidov** [comment]
Maybe add a test with a sequence with both UNION ALL and UNION DISTINCT and SELECT * in every of the elements.
I wonder what will happen when in one element the list of columns is filtered and in other elements is not.

File: tests/queries/skip_list.json [hunk 2]
```diff
@@ -507,6 +507,7 @@
         "01532_execute_merges_on_single_replica", /// static zk path
         "01530_drop_database_atomic_sync", /// creates database
         "02001_add_default_database_to_system_users", ///create user
-        "02002_row_level_filter_bug" ///create user
+        "02002_row_level_filter_bug", ///create user
+        "02008_test_union_distinct_in_subquery" /// create database
```
Comment (alexey-milovidov) [inline tests/queries/skip_list.json:511]: Now it can be removed from this list.

**Review by alexey-milovidov — APPROVED** [review]
