### PR TITLE
Fix crash on nested `QBit` deserialization

### LINKED ISSUE #91326: Crash on nested `QBit` deserialization
### Problem 

Found by libfuzzer [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=4547ca835e99ff419616cb220f4c56a1ee04dc66&name_0=NightlyFuzzers&name_1=libFuzzer%20tests&name_1=libFuzzer%20tests) (see `data_type_deserialization_fuzzer`). Likely, it creates a malformed byte stream that can deserialize into illegal nested `QBit`. While this cannot be created through normal ClickHouse operations, it can be crafted externally and sent to the server for deserialization.

### Stack Trace
```cpp
==1781== ERROR: libFuzzer: deadly signal
/usr/bin/llvm-symbolizer-19: error: 'linux-vdso.so.1': No such file or directory
    #0 0xabaaa8f0ec70 in __sanitizer_print_stack_trace (/fuzzers/data_type_deserialization_fuzzer+0x11bbec70) (BuildId: 0bbfba577c56ed5b632dfc832f428a9cfd8d107a)
    #1 0xabaabfdf5c90 in fuzzer::PrintStackTrace() ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0xabaabfde082c in fuzzer::Fuzzer::CrashCallback() ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:231:3
    #3 0xff18381798f4  (linux-vdso.so.1+0x8f4) (BuildId: d2d515465437461394f3c49b47dcfe228e7ef1f7)
    #4 0xff1837fb2005  (/lib/aarch64-linux-gnu/libc.so.6+0x82005) (BuildId: 034c9554b03099fc969ae2528ea6fd26286057d8)
    #5 0xff1837f6a838 in gsignal (/lib/aarch64-linux-gnu/libc.so.6+0x3a838) (BuildId: 034c9554b03099fc969ae2528ea6fd26286057d8)
    #6 0xff1837f57130 in abort (/lib/aarch64-linux-gnu/libc.so.6+0x27130) (BuildId: 034c9554b03099fc969ae2528ea6fd26286057d8)
    #7 0xabaac948793c in DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, void* const*, unsigned long, unsigned long) ci/tmp/build/./src/Common/Exception.cpp:52:5
    #8 0xabaac94895a4 in DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&) ci/tmp/build/./src/Common/Exception.cpp:85:13
    #9 0xabaac9489b6c in DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) ci/tmp/build/./src/Common/Exception.cpp:136:19
    #10 0xabaaa8f43e00 in DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool) ci/tmp/build/./src/Common/Exception.h:123:100
    #11 0xabaaa8f41dd0 in DB::Exception::Exception(PreformattedMessage&&, int) ci/tmp/build/./src/Common/Exception.h:58:54
    #12 0xabaab075a130 in DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, FormatStringHelperImpl<std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) ci/tmp/build/./src/Common/Exception.h:141:77
    #13 0xabaab075a130 in DB::IDataType::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/IDataType.cpp:115:11
    #14 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #15 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #16 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #17 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #18 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #19 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #20 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #21 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #22 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #23 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #24 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #25 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #26 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #27 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #28 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #29 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #30 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #31 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #32 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #33 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #34 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #35 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #36 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #37 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #38 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #39 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #40 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #41 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #42 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #43 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #44 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #45 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #46 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #47 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #48 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #49 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #50 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #51 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #52 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #53 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #54 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #55 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #56 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #57 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #58 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #59 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #60 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #61 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #62 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #63 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #64 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #65 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #66 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #67 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #68 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #69 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #70 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #71 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #72 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #73 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #74 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #75 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #76 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #77 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #78 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #79 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #80 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #81 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #82 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #83 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #84 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #85 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #86 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #87 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #88 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #89 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #90 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #91 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #92 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #93 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #94 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #95 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #96 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #97 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #98 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #99 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #100 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #101 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #102 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #103 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #104 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #105 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #106 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #107 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #108 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #109 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #110 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #111 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #112 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #113 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #114 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #115 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #116 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #117 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #118 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #119 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #120 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #121 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #122 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #123 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #124 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #125 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #126 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #127 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #128 0xabaab065d2c8 in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #129 0xabaab065d2c8 in DB::DataTypeQBit::getSizeOfValueInMemory() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:42:62
    #130 0xabaab065ad4c in DB::DataTypeQBit::getElementSize() const ci/tmp/build/./src/DataTypes/DataTypeQBit.h:40:62
    #131 0xabaab065ad4c in DB::DataTypeQBit::getNestedType() const ci/tmp/build/./src/DataTypes/DataTypeQBit.cpp:63:35
    #132 0xabaab065b450 in DB::DataTypeQBit::doGetDefaultSerialization() const ci/tmp/build/./src/DataTypes/DataTypeQBit.cpp:74:48
    #133 0xabaab075c7f4 in DB::IDataType::getDefaultSerialization(std::__1::shared_ptr<DB::ISerialization const>) const ci/tmp/build/./src/DataTypes/IDataType.cpp:311:12
    #134 0xabaab08c2738 in DB::SerializationDynamic::deserializeBinary(DB::Field&, DB::ReadBuffer&, DB::FormatSettings const&) const ci/tmp/build/./src/DataTypes/Serializations/SerializationDynamic.cpp:690:17
    #135 0xabaab0a480e4 in DB::SerializationObject::deserializeBinary(DB::Field&, DB::ReadBuffer&, DB::FormatSettings const&) const ci/tmp/build/./src/DataTypes/Serializations/SerializationObject.cpp
    #136 0xabaaa8f3a0f8 in LLVMFuzzerTestOneInput ci/tmp/build/./src/DataTypes/fuzzers/data_type_deserialization_fuzzer.cpp:75:42
    #137 0xabaabfde3e50 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:619:13
    #138 0xabaabfde2d34 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:516:7
    #139 0xabaabfde64d4 in fuzzer::Fuzzer::MutateAndTestOne() ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:765:19
    #140 0xabaabfde8830 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:910:5
    #141 0xabaabfdcdc20 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:916:6
    #142 0xabaabfdc4674 in main ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #143 0xff1837f573fc  (/lib/aarch64-linux-gnu/libc.so.6+0x273fc) (BuildId: 034c9554b03099fc969ae2528ea6fd26286057d8)
```

### PR DESCRIPTION
**Pull request by rienath**
It is not possible to have `QBit` within `QBit`. But, as `libfuzzer` has found [[1](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=4f998ad3f12c99c272982b3e81867c63d28f8afb&name_0=NightlyFuzzers&name_1=libFuzzer%20tests&name_1=libFuzzer%20tests), [2](https://s3.amazonaws.com/clickhouse-test-reports/REFs/master/4f998ad3f12c99c272982b3e81867c63d28f8afb//libfuzzer_tests/data_type_deserialization_fuzzer/out.txt)], it is possible to manually craft a byte stream that would deserialize into `QBit(QBit(...), d)` and send it to ClickHouse. It would then crash. Resolves https://github.com/ClickHouse/ClickHouse/issues/91326

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix a crash when maliciously crafted byte streams deserialize into nested QBit types, which should be impossible but could be exploited to crash the server.

### CODE REVIEW

File: src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp [hunk 1]
```diff
@@ -11,22 +11,12 @@
...
+    auto float32_type = DataTypeFactory::instance().get("Float32");
+    auto qbit_type_float32 = std::static_pointer_cast<DataTypeQBit>(std::make_shared<DataTypeQBit>(float32_type, 5));
+    auto serialization_float32 = qbit_type_float32->getDefaultSerialization();
 
-    std::shared_ptr<DataTypeQBit> qbit_type_float32;
-    SerializationPtr serialization_float32;
-};
-
-TEST_F(QBitSerializationTest, FieldBinarySerializationFloat32)
-{
```
Comment (rienath) [inline src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp:29]: Doesn't relate to this PR. Just saw that the test can be nicer and fixed it

File: src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp [hunk 2]
```diff
@@ -4,29 +4,35 @@
...
 #include <IO/ReadBufferFromString.h>
 #include <IO/WriteBufferFromString.h>
+#include <Common/ErrorCodes.h>
 
 #include <base/types.h>
 #include <gtest/gtest.h>
 
 
-using namespace DB;
+#define EXPECT_THROW_ERROR_CODE(statement, expected_exception, expected_code) \
```
Comment (thevar1able) [inline src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp:13]: Maybe we should move the macro from [here](https://github.com/clickhouse/clickhouse/blob/master/src/IO/tests/gtest_memory_resize.cpp#L6-L17) to some header?

**Review by thevar1able — APPROVED** [review]

File: src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp (hunk 2 above)
Comment (rienath) [reply src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp:13]: Good idea! One option is to have `gtest_serialization.h` in the same folder. Another is to have some general gtest header somewhere in the repo, especially considering the same macro already exists in [`src/IO/tests/gtest_memory_resize.cpp`](https://github.com/ClickHouse/ClickHouse/blob/784c253e7426e76e725c666fc98fbcd416972ba1/src/IO/tests/gtest_memory_resize.cpp#L6). Do you, by any chance, know if such header already exists and, if not, what the right place for it would be?

Comment (rienath) [reply src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp:13]: I've checked various `gtest` headers and couldn't find one where this macro would fit. And, on the second thought, I am not sure creating one more header is optimal given code duplication is minimal and that it would only contain this macro. Please let me know if I am missing something @thevar1able

Comment (rienath) [reply src/DataTypes/Serializations/tests/gtest_qbit_serialization.cpp:13]: Discussed privately, decided to leave it as is

**Comment by rienath** [comment]
[Stateless tests (amd_msan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91313&sha=bf1dbce7645bf1cc09a39b9443c724a6960533ca&name_0=PR&name_1=Stateless+tests+%28amd_msan%2C+parallel%29)
* https://github.com/ClickHouse/ClickHouse/issues/90683

[Integration tests (amd_tsan, 2/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91313&sha=bf1dbce7645bf1cc09a39b9443c724a6960533ca&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+2%2F6%29)
* https://github.com/ClickHouse/ClickHouse/issues/91391

[AST fuzzer (amd_msan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91313&sha=bf1dbce7645bf1cc09a39b9443c724a6960533ca&name_0=PR&name_1=AST+fuzzer+%28amd_msan%29)
* https://github.com/ClickHouse/ClickHouse/issues/90748


[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91313&sha=bf1dbce7645bf1cc09a39b9443c724a6960533ca&name_0=PR&name_1=BuzzHouse+%28amd_debug%29)
* `Logical error: 'Inconsistent AST formatting'` with no `QBit` involved
