### PR TITLE
Fix primary.idx corruption after delete mutation

### LINKED ISSUE #9019: Broken indicies and inconsistent queries results
Hi! 

After updating Clickhouse from 19.13.1.11 version to 20.1.3.7 and when we run queries like this:

```
select courseId, uniqExact(learnerId) from entities_attempts_distributed group by courseId order by courseId
```
and 
```
select uniqExact(learnerId) from entities_attempts_distributed where courseId = 41
``` 
we have different results. For example first query returns 21500 unique values for courseId = 41 and second query returns 3500 unique values for courseId = 41.

If we change second query to 
```
select uniqExact(learnerId) from entities_attempts_distributed where identity(courseId) = 41
``` 
we have same result with first query. So, it's possible that in some moment table indicies was corrupted.

We have ReplicatedMergeTree table with structure:

```
CREATE TABLE cursometr.entities_attempts_replicated (`learnerId` UInt64, `courseId` UInt64, `actorId` UInt64, `entityIri` String, `startedAt` DateTime, `attemptNumber` UInt16, `attemptLearningNumber` UInt16, `attemptRepeatingNumber` UInt16, `attemptBeforePassedNumber` UInt16, `attemptAfterPassedNumber` UInt16, `endedAt` DateTime, `passed` UInt8, `success` UInt8, `learning` UInt8, `repeating` UInt8, `beforePassed` UInt8, `afterPassed` UInt8, `result` Float32, `durationTotal` UInt32, `durationLearning` UInt32, `durationRepeating` UInt32, `durationBeforePassed` UInt32, `durationAfterPassed` UInt32, `reject` UInt8, `version` DateTime, `hash` UInt64, `queryId` UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/cursometr/{shard}/entities_attempts', '{replica}') PARTITION BY toStartOfDay(version) ORDER BY (courseId, learnerId, hash, entityIri) SETTINGS index_granularity = 8192
```

Inserts in this table performs via temporary table with same structure. When data successfully inserted in temporary table we move partitions to main table `entities_attempts_replicated` with query 
```
alter table entities_attempts_replicated attach partition $partition from $temp_table_name
```
When partitions successfully moved to main table we drop temporary table.

Sometimes we run queries to delete old data by column `hash`. To perform consistent mutation we collect list of actual hashes and insert them into memory table. Query looks like 
```
alter table entities_attempts_replicated delete where hash not in (select hash from $temporary_hashes_table)
```

So, we don't know at which moment data corrupts, but we can try to make step-by-step reproducing manual if needed.

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug in `ALTER DELETE` mutations which leads to index corruption. This fixes #9019 and #8982. Additionally fix extremely rare race conditions in `ReplicatedMergeTree` `ALTER` queries.

### CODE REVIEW

**Comment by alesapin** [comment]
Unit tests — Segmentation fault  -- already fixed on master, not related to changes.

**Comment by akuzm** [comment]
Did you find out why the order of rows changes? Theoretically, when reading sequentially in a single thread, it should be the same.

File: dbms/src/Interpreters/MutationsInterpreter.cpp [hunk 1]
```diff
@@ -525,6 +526,39 @@ ASTPtr MutationsInterpreter::prepareInterpreterSelectQuery(std::vector<Stage> &
...
+    {
+        ASTPtr dummy;
+
+        ASTPtr key_expr;
+        if (metadata.primary_key_ast)
+            key_expr = metadata.primary_key_ast;
+        else
+            key_expr = metadata.order_by_ast;
+
+        bool empty = false;
```
Comment (akuzm) [inline dbms/src/Interpreters/MutationsInterpreter.cpp]: What does this check for, something like `order by tuple()`? Can we just remove this check and pass the order by always, or does it break something? Btw I found that `order by tuple()` doesn't seem to work, because `tuple` requires at least one argument, but `order by 1` does.

Comment (alesapin) [reply dbms/src/Interpreters/MutationsInterpreter.cpp]: Yes we cannot order by `tuple()` and in this case we don't need order by at all.

**Comment by alesapin** [comment]
> Did you find out why the order of rows changes? Theoretically, when reading sequentially in a single thread, it should be the same.

Still not, but I'll try to find the next week. Anyway, when we use `InterpreterSelectQuery` and want to preserve order we have to add `ORDER BY`. We don't provide any guarantees even in a single-threaded case, and if "ordered" behavior was changed unintentionally `ORDER BY` is still required.

**Comment by tavplubix** [comment]
Backport conflict in 19.17
