### PR TITLE
Fix UBSan failure on non-aligned PODArray null pointer

### LINKED ISSUE #80136: `Misaligned pointer use` on on aarch64
```
(lldb) bt
* thread #3, name = 'clickhouse', stop reason = Misaligned pointer use
  * frame #0: 0x0000aaaac4de6cdc clickhouse`__ubsan_on_report
    frame #1: 0x0000aaaac4de2448 clickhouse`__ubsan::Diag::~Diag() + 260
    frame #2: 0x0000aaaac4de3aa0 clickhouse`handleTypeMismatchImpl(__ubsan::TypeMismatchData*, unsigned long, __ubsan::ReportOptions) + 996
    frame #3: 0x0000aaaac4de3b18 clickhouse`__ubsan_handle_type_mismatch_v1_abort + 44
    frame #4: 0x0000aaaac57b1978 clickhouse`DB::ColumnString::insertDefault() [inlined] DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>::back(this=<unavailable>) at PODArray.h:390:31
    frame #5: 0x0000aaaac57b195c clickhouse`DB::ColumnString::insertDefault(this=<unavailable>) at ColumnString.h:246:35
    frame #6: 0x0000aaaad2f17bfc clickhouse`DB::StorageSystemFunctions::fillData(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, std::__1::shared_ptr<DB::Context const>, DB::ActionsDAG::Node const*, std::__1::vector<char8_t, std::__1::allocator<char8_t>>) const [inlined] void DB::(anonymous namespace)::fillRow<DB::FunctionFactory>(res_columns=size=13, name="hasAll", is_aggregate=0, create_query="", function_origin=SYSTEM, factory=0x0000aaaaec0fa0e0) at StorageSystemFunctions.cpp:50:33
    frame #7: 0x0000aaaad2f178bc clickhouse`DB::StorageSystemFunctions::fillData(this=<unavailable>, res_columns=size=13, context=std::__1::shared_ptr<const DB::Context>::element_type @ 0x0000fffff013d840 strong=5 weak=2, (null)=<unavailable>, (null)=<unavailable>) const at StorageSystemFunctions.cpp:129:9
    frame #8: 0x0000aaaad2ee82b4 clickhouse`DB::ReadFromSystemOneBlock::initializePipeline(this=0x0000fffff0133920, pipeline=0x0000fffff030d610, (null)=<unavailable>) at IStorageSystemOneBlock.cpp:86:14
    frame #9: 0x0000aaaadb811804 clickhouse`DB::ISourceStep::updatePipeline(this=0x0000fffff0133920, (null)=<unavailable>, settings=0x0000fffff64e7128) at ISourceStep.cpp:20:5
    frame #10: 0x0000aaaadb85771c clickhouse`DB::QueryPlan::buildQueryPipeline(this=0x0000fffff0036e38, optimization_settings=<unavailable>, build_pipeline_settings=0x0000fffff64e7128, do_optimize=<unavailable>) at QueryPlan.cpp:199:47
    frame #11: 0x0000aaaad7c5cec0 clickhouse`DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline(this=0x0000fffff0036d90) at InterpreterSelectQueryAnalyzer.cpp:289:34
    frame #12: 0x0000aaaad7c5cb74 clickhouse`DB::InterpreterSelectQueryAnalyzer::execute(this=0x0000fffff0036d90) at InterpreterSelectQueryAnalyzer.cpp:256:29
    frame #13: 0x0000aaaad805db70 clickhouse`DB::executeQueryImpl(begin=<unavailable>, end=<unavailable>, context=std::__1::shared_ptr<DB::Context>::element_type @ 0x0000fffff0008fc0 strong=3 weak=57, flags=<unavailable>, stage=Complete, istr=0x0000000000000000, out_ast=std::__1::shared_ptr<DB::IAST>::element_type @ 0x0000fffff0027998 strong=2 weak=2) at executeQuery.cpp:1522:40
    frame #14: 0x0000aaaad8057eb8 clickhouse`DB::executeQuery(query=<unavailable>, context=std::__1::shared_ptr<DB::Context>::element_type @ 0x0000fffff0008fc0 strong=3 weak=57, flags=(internal = false, distributed_backup_restore = false), stage=Complete) at executeQuery.cpp:1714:11
    frame #15: 0x0000aaaadac0c778 clickhouse`DB::LocalConnection::sendQuery(this=0x0000fffff0002770, (null)=<unavailable>, query="SELECT DISTINCT arrayJoin(extractAll(name, '[\\\\w_]{2,}')) AS res FROM (SELECT * FROM viewIfPermitted(SELECT name FROM system.functions ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.table_engines ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.formats ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.table_functions ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.data_type_families ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.merge_tree_settings ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.settings ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT keyword FROM system.keywords ELSE null('keyword String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT concat(func.name, comb.name) AS x FROM system.functions AS func CROSS JOIN system.agg"..., query_parameters=size=0, query_id="", stage=2, (null)=<unavailable>, client_info=<unavailable>, (null)=<unavailable>, (null)=<unavailable>, process_progress_callback=function<void (const DB::Progress &)> @ 0x0000fffff64ea510) at LocalConnection.cpp:263:21
    frame #16: 0x0000aaaadac2fdd4 clickhouse`DB::Suggest::fetch(this=0x0000ffffffffe0c8, connection=0x0000fffff0002770, timeouts=0x0000aaaaec83af58, query="SELECT DISTINCT arrayJoin(extractAll(name, '[\\\\w_]{2,}')) AS res FROM (SELECT * FROM viewIfPermitted(SELECT name FROM system.functions ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.table_engines ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.formats ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.table_functions ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.data_type_families ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.merge_tree_settings ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT name FROM system.settings ELSE null('name String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT keyword FROM system.keywords ELSE null('keyword String')) UNION ALL SELECT * FROM viewIfPermitted(SELECT concat(func.name, comb.name) AS x FROM system.functions AS func CROSS JOIN system.agg"..., client_info=0x0000aaaaec864708) at Suggest.cpp:165:16
    frame #17: 0x0000aaaadac325e4 clickhouse`void DB::Suggest::load<DB::LocalConnection>(this=0x0000aaaaec83ae48)::'lambda'()::operator()() const at Suggest.cpp:103:17
    frame #18: 0x0000aaaadac32398 clickhouse`void* std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void DB::Suggest::load<DB::LocalConnection>(std::__1::shared_ptr<DB::Context const>, DB::ConnectionParameters const&, int, bool)::'lambda'()>>(void*) [inlined] decltype(std::declval<void DB::Suggest::load<DB::LocalConnection>(std::__1::shared_ptr<DB::Context const>, DB::ConnectionParameters const&, int, bool)::'lambda'()>()()) std::__1::__invoke[abi:se190107]<void DB::Suggest::load<DB::LocalConnection>(std::__1::shared_ptr<DB::Context const>, DB::ConnectionParameters const&, int, bool)::'lambda'()>(__f=<unavailable>) at invoke.h:149:25
    frame #19: 0x0000aaaadac32394 clickhouse`void* std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void DB::Suggest::load<DB::LocalConnection>(std::__1::shared_ptr<DB::Context const>, DB::ConnectionParameters const&, int, bool)::'lambda'()>>(void*) [inlined] void std::__1::__thread_execute[abi:se190107]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void DB::Suggest::load<DB::LocalConnection>(std::__1::shared_ptr<DB::Context const>, DB::ConnectionParameters const&, int, bool)::'lambda'()>(__t=<unavailable>, (null)=<unavailable>) at thread.h:192:3
    frame #20: 0x0000aaaadac32390 clickhouse`void* std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void DB::Suggest::load<DB::LocalConnection>(std::__1::shared_ptr<DB::Context const>, DB::ConnectionParameters const&, int, bool)::'lambda'()>>(__vp=<unavailable>) at thread.h:201:3
    frame #21: 0x0000fffff7df4b30 libc.so.6`start_thread(arg=0x0000fffff64eb380) at pthread_create.c:447:8
    frame #22: 0x0000fffff7e5d88c libc.so.6`thread_start at clone3.S:76
```

### Repro:

- Make a debug build with UBSan on aarch64
- `programs/clickhouse local`

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/80136

### CODE REVIEW

File: src/Common/PODArray.h [hunk 1]
```diff
@@ -92,11 +93,12 @@ class PODArrayBase : private boost::noncopyable, private TAllocator    /// empty
     /// Round padding up to an whole number of elements to simplify arithmetic.
     static constexpr size_t pad_right = integerRoundUp(pad_right_, ELEMENT_SIZE);
     /// pad_left is also rounded up to 16 bytes to maintain alignment of allocated memory.
-    static constexpr size_t pad_left = integerRoundUp(integerRoundUp(pad_left_, ELEMENT_SIZE), 16);
+    static constexpr size_t pad_left = integerRoundUp(pad_left_, std::lcm(ELEMENT_SIZE, 16));
```
Comment (alexey-milovidov) [inline src/Common/PODArray.h:96]: It's difficult to understand, for what values of ELEMENT_SIZE there is a difference?

**Review by alexey-milovidov — APPROVED** [review]
Can we add an isolated .sql test for this?

File: src/Common/PODArray.h (hunk 1 above)
Comment (thevar1able) [reply src/Common/PODArray.h:96]: 24, 40 and 88 from what I see in build failures without that fix.

**Comment by thevar1able** [comment]
>Can we add an isolated .sql test for this?

I don't see how.
Running `clickhouse-client` or `clickhouse-local` with UBSan on aarch64 would have caught it.

**Comment by rschu1ze** [comment]
We should still add a tests. Maybe one fine day, the CI will run UBSan/ARM and then we'll check that.

**Comment by thevar1able** [comment]
At least we have a `static_assert` now.
