### PR TITLE
Do not allow SETTINGS after FORMAT for INSERT queries

### LINKED ISSUE #20343: INSERT SELECT: SETTINGS clause after FORMAT can lead to parsing issues
I send protobuf messages (Protobuf format) to ClickHouse  via Python(3.8.1). On some messages I receive exceptions 'unrecognized tokens' which aren't expected. The odd thing is that exception's appearance depends on the context of protobuf messages (and especially with negative integers). It will be shown in the examples below.

Serialize messages via google.protobuf(3.13.0), add length which is calculated via the same module.
These messages were serialized by me and I can deserialize it by Python means, so I assume that they are correct. 

I use clickhouse 20.11.4.13 (yandex/clickhouse-server:20.11 docker image). Also I tried to use clickhouse-server:21.2.2.8 and there is the same error.

It doesn't look like problem in protobuf serializing because the very first time when I received such errors were with messages, which were serialized by Java client.

The following statements were produced by `show create table` commands in `clickhouse-client`:
```
CREATE TABLE arbitrary_db.some_entrypoint
(
    `field_1` String,
    `field_2` Int64,
    `field_3` Int32,
    `field_4` Int32,
    `field_5` Int32,
    `field_6` String,
    `field_7` String,
    `field_8` String,
    `field_9` String,
    `field_10` Int32,
    `field_11` Int32,
    `field_12` Nullable(Int32),
    `field_13` Nullable(Int32),
    `field_14` String,
    `field_16_field_18` Nullable(Int32),
    `field_16_field_19` Nullable(Int32),
    `field_16_field_20` Nullable(String),
    `field_16_field_21` Nullable(String),
    `field_16_field_22` Nullable(String),
    `field_16_field_23` Nullable(String),
    `field_16_field_24` Nullable(String),
    `field_16_field_25` Nullable(String),
    `field_16_field_266` Nullable(String),
    `field_16_field_27` Nullable(String),
    `field_16_field_28` Nullable(String),
    `field_17_field_29` Nullable(Int32),
    `field_17_field_30` Nullable(String),
    `field_17_field_31` Nullable(Int32),
    `field_17_field_32` Nullable(Int32),
    `field_17_field_33` Nullable(Int32),
    `field_17_field_34` Nullable(Int32),
    `field_17_field_35` Nullable(String),
    `field_17_field_36` Nullable(String),
    `field_17_field_37` Nullable(String),
    `field_17_field_38` Nullable(String),
    `field_17_field_39` Nullable(Int64),
    `field_17_field_40` Nullable(Int64),
    `field_17_field_41` Nullable(String)
)
ENGINE = Null() 

CREATE TABLE arbitrary_db.some_aggregation
(
    `final_6` String,
    `final_7` String,
    `final_8` String,
    `max_final_2` AggregateFunction(max, Int64),
    `min_final_2` AggregateFunction(min, Int64)
)
ENGINE = AggregatingMergeTree()
PRIMARY KEY (final_6, final_7, final_8)
ORDER BY (final_6, final_7, final_8)
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW arbitrary_db.some_aggregation_mv TO arbitrary_db.some_aggregation
(
    `final_6` String,
    `final_7` String,
    `final_8` String,
    `max_final_2` AggregateFunction(max, Int64),
    `min_final_2` AggregateFunction(min, Int64)
) AS
SELECT
    field_6 AS final_6,
    field_7 AS final_7,
    field_8 AS final_8,
    maxState(field_2) AS max_final_2,
    minState(field_2) AS min_final_2
FROM arbitrary_db.some_entrypoint
WHERE (((field_8 != '') AND (field_7 != '')) OR ((field_8 != '') AND (field_6 != '')) OR ((field_7 != '') AND (field_6 != ''))) AND (field_2 > 0)
GROUP BY
    field_6,
    field_7,
    field_8
ORDER BY
    field_6 ASC,
    field_7 ASC,
    field_8 ASC
```

**Error message**
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 177 ('') (line 2, col 2): ����:	123456789B
                                                                                                                                          87654322342�
                                                                                                                                                       �̣������. Unrecognized token (version 20.11.4.13 (official build))

**Examples of input and output**

```
field_2: 1606918072
field_7: "123456789"
field_8: "87654322342"
field_17 {
  field_31: -1062672876
  field_33: 4
  field_34: 6
}

b'0\x10\xb8\xbf\x9e\xfe\x05:\t123456789B\x0b87654322342\xaa\x06\x0f \x94\xcc\xa3\x85\xfc\xff\xff\xff\xff\x010\x048\x06'
RESPONSE TEXT 
STATUS CODE 200
```

Remaining only negative value in the submessage leads to an exception.
```
field_2: 1606918072
field_7: "123456789"
field_8: "87654322342"
field_17 {
  field_31: -1062672876
}

b',\x10\xb8\xbf\x9e\xfe\x05:\t123456789B\x0b87654322342\xaa\x06\x0b \x94\xcc\xa3\x85\xfc\xff\xff\xff\xff\x01'
RESPONSE TEXT Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 177 ('') (line 2, col 2): ����:	123456789B
                                                                                                                                          87654322342�
                                                                                                                                                       �̣������. Unrecognized token (version 20.11.4.13 (official build))

STATUS CODE 400
```

The same message as previous but without one field (`field_7`) from main message.
```
field_2: 1606918072
field_8: "87654322342"
field_17 {
  field_31: -1062672876
}

b'!\x10\xb8\xbf\x9e\xfe\x05B\x0b87654322342\xaa\x06\x0b \x94\xcc\xa3\x85\xfc\xff\xff\xff\xff\x01'
RESPONSE TEXT 
STATUS CODE 200
```

Returned `field_7` and made `field_31` value positive.
```
field_2: 1606918072
field_7: "123456789"
field_8: "87654322342"
field_17 {
  field_31: 1062672876
}

b"'\x10\xb8\xbf\x9e\xfe\x05:\t123456789B\x0b87654322342\xaa\x06\x06 \xec\xb3\xdc\xfa\x03"
RESPONSE TEXT 
STATUS CODE 200
```

I also tried to skip broken messages via ` input_format_allow_errors_num=10`, `input_format_allow_errors_ratio=1` options to INSERT query but it didn't get me desired results.

In attachments you can find code snippets that I used to reproduce the unexpected behaviour (.py files, requirements for python, .proto files and compiled from it .py files).

[issue.zip](https://github.com/ClickHouse/ClickHouse/files/5967432/issue.zip)

### LINKED ISSUE #35100: Bug in INSERT INTO table FORMAT RowBinary SETTINGS ...
Simple way to reproduce it.

* Create a table:
```sql
create table idtable (id Int64) ENGINE = Memory();
```

* Insert into that table using RowBinary (`INSERT INTO idtable FORMAT RowBinary SETTINGS insert_deduplicate=0, max_partitions_per_insert_block=10`):

```bash
clickhouse local --query "Select '286508'::Int64 as id format RowBinary" \
| curl --data-binary @- "http://localhost:8123?query=INSERT%20INTO%20idtable%20FORMAT%20RowBinary%20SETTINGS%20insert_deduplicate%3D0%2C%20max_partitions_per_insert_block%3D10" --output -
```

An error is raised:
```
2022.03.07 17:18:11.362890 [ 365398 ] {07066665-fb62-4904-9b84-0b8ae512358b} <Error> DynamicQueryHandler: Code: 62. DB::Exception: Syntax error: failed at position 106 ('') (line 2, col 3): . Unrecognized token: ''. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. ./build_debug/./contrib/libcxx/include/exception:133: std::exception::capture() @ 0x171df362 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
1. ./build_debug/./contrib/libcxx/include/exception:111: std::exception::exception() @ 0x171df330 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
2. ./build_debug/./contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2d26e520 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
3. ./build_debug/./src/Common/Exception.cpp:56: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x171b5fdb in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
4. ./build_debug/./src/Parsers/parseQuery.cpp:348: DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x28cee7d2 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
5. ./build_debug/./src/Parsers/parseQuery.cpp:360: DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) @ 0x28cee8f3 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
6. ./build_debug/./src/Interpreters/executeQuery.cpp:428: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x2741b248 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
7. ./build_debug/./src/Interpreters/executeQuery.cpp:1055: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x2741ef3d in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
8. ./build_debug/./src/Server/HTTPHandler.cpp:821: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x2825cc97 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
9. ./build_debug/./src/Server/HTTPHandler.cpp:959: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x2825f8ff in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
10. ./build_debug/./src/Server/HTTP/HTTPServerConnection.cpp:65: DB::HTTPServerConnection::run() @ 0x283098e1 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
11. ./build_debug/./contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x2d091eb9 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
12. ./build_debug/./contrib/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x2d0926d9 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
13. ./build_debug/./contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x2d302ae1 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
14. ./build_debug/./contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x2d2ff15a in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
15. ./build_debug/./contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x2d2fde14 in /mnt/ch/ClickHouse/build_debug/programs/clickhouse
16. ? @ 0x7f968ccf05c2 in ?
17. __clone @ 0x7f968cd75584 in ?
 (version 22.3.1.1)
```

Note that by "sheer luck" (aka the bug), the binary value of that payload starts with a comma (`,`)
```
clickhouse local --query "Select '286508'::Int64 as id format RowBinary" | xxd
00000000: 2c5f 0400 0000 0000                      ,_......
```

This confuses the parser. It's thinking that after the 2 settings there is another setting, while in fact there is only data:
```
INSERT INTO idtable FORMAT RowBinary SETTINGS insert_deduplicate=0, max_partitions_per_insert_block=10 ,_
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not allow SETTINGS after FORMAT for INSERT queries (there is compatibility setting `parser_settings_after_format_compact` to accept such queries, but it is turned OFF by default)

Parsing SETTINGS after FORMAT, that has been introduced in [1], can
interpret SETTING as some values, which is misleading.

  [1]: https://github.com/ClickHouse/ClickHouse/pull/4174/files#diff-ba7bd0657630b1cd94cf6ed364bd857338096f49f66dc82918438d6745753775R106

Note, that we are touching only INSERT queries, not SELECT, since this
is a backward incompatible change, and in case of modifying SELECT it
can break too much.

Fixes: #35100
Fixes: #20343
Cc: @alexey-milovidov

### CODE REVIEW

**Comment by azat** [comment]
>[Style Check (actions) — Check style failed](https://s3.amazonaws.com/clickhouse-test-reports/35883/e6ba60d2422126250fef32ec24abd54fd6f2f15f/style_check__actions_/style_output.txt)

- Likely broken in #35858

File: src/Parsers/ParserInsertQuery.cpp [hunk 1]
```diff
@@ -133,6 +133,20 @@ bool ParserInsertQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
...
+        ParserSetQuery parser_settings(true);
+        if (!parser_settings.parse(pos, settings_ast, expected))
+            return false;
+
+        /// We should move data pointer after all settings, in case of:
+        /// - INSERT SELECT
+        /// - INSERT WATCH
+        before_values = pos;
+    }
+
```
Comment (vitlibar) [inline src/Parsers/ParserInsertQuery.cpp:149]: We can write `Pos before_values = pos;` here to assign `before_values` in only one place

File: src/Parsers/ASTInsertQuery.cpp [hunk 2]
```diff
@@ -86,33 +86,41 @@ void ASTInsertQuery::formatImpl(const FormatSettings & settings, FormatState & s
             settings.ostr << (settings.hilite ? hilite_keyword : "") << " COMPRESSION " << (settings.hilite ? hilite_none : "") << compression->as<ASTLiteral &>().value.safeGet<std::string>();
     }
 
+    if (settings_ast)
+    {
+        settings.ostr << (settings.hilite ? hilite_keyword : "") << settings.nl_or_ws << "SETTINGS " << (settings.hilite ? hilite_none : "");
+        settings_ast->formatImpl(settings, state, frame);
+        settings.ostr << settings.nl_or_ws;
```
Comment (vitlibar) [inline src/Parsers/ASTInsertQuery.cpp:93]: It seems if we replace this line with

```
space = settings.nl_or_ws
```

then the conditions below 
```
        if (!settings_ast)
            settings.ostr << ' ';
```

will turn into just `settings.ostr << space`

File: src/Parsers/ParserInsertQuery.cpp (hunk 1 above)
Comment (azat) [reply src/Parsers/ParserInsertQuery.cpp:149]: Right, thanks.

File: src/Parsers/ASTInsertQuery.cpp (hunk 2 above)
Comment (azat) [reply src/Parsers/ASTInsertQuery.cpp:93]: This will break compatibility for INSERT w/o SETTINGS formatted in oneline, but I got the idea, will simplify the code.

**Review by vitlibar — APPROVED** [review]

**Comment by azat** [comment]
>[Stateless tests flaky check (address, actions) — Timeout, fail: 0, passed: 2161](https://s3.amazonaws.com/clickhouse-test-reports/35883/261106544d1c26330f56310983f92037d545fdb4/stateless_tests_flaky_check__address__actions_.html)

Timeout - OK, no failures

File: src/Parsers/ParserQuery.h [hunk 3]
```diff
@@ -10,12 +10,21 @@ class ParserQuery : public IParserBase
...
-    explicit ParserQuery(const char * end_) : end(end_) {}
+    /// For tests/examples.
+    explicit ParserQuery(const char * end_)
+        : end(end_)
+    {}
+    /// For production parser.
+    explicit ParserQuery(const char * end_, const ParserSettings & parser_settings_)
+        : end(end_)
+        , parser_settings(parser_settings_)
+    {}
```
Comment (vitlibar) [inline src/Parsers/ParserQuery.h:27]: Looks very strange, why do you need to change so common classes?
I thought you were going to just check your new setting `parse_settings_after_format` in `ParserInsertQuery` and that's all

Comment (azat) [reply src/Parsers/ParserQuery.h:27]: But how would you pass this setting to `ParserInsertQuery`?
Entrypoint for the parsing is - `ParserQuery`

File: src/Parsers/ParserQuery.h [hunk 4]
```diff
@@ -10,12 +10,21 @@ class ParserQuery : public IParserBase
...
     const char * getName() const override { return "Query"; }
     bool parseImpl(Pos & pos, ASTPtr & node, Expected & expected) override;
 
 public:
-    explicit ParserQuery(const char * end_) : end(end_) {}
+    /// For tests/examples.
+    explicit ParserQuery(const char * end_)
+        : end(end_)
+    {}
+    /// For production parser.
```
Comment (vitlibar) [inline src/Parsers/ParserQuery.h:23]: We can join both those versions to a single constructor

```
explicit ParserQuery(const char * end_, const ParserSettings & parser_settings_ = {})
```

File: src/Parsers/IParser.h [hunk 5]
```diff
@@ -49,6 +49,13 @@ struct Expected
 };
 
 
+/** Parser settings (for compatibility mostly)
+  */
+struct ParserSettings
+{
+    bool parser_settings_after_format_compact = false;
```
Comment (vitlibar) [inline src/Parsers/IParser.h:56]: It seems the name `allow_settings_after_format_in_insert` is shorter and clearer.

File: src/Parsers/ParserQuery.h (hunk 3 above)
Comment (vitlibar) [reply src/Parsers/ParserQuery.h:27]: Probably it's better not to use the structure and just pass the parameter to constructors?

Comment (vitlibar) [reply src/Parsers/ParserQuery.h:27]: Probably it's better not to use the structure and just pass the parameter to constructors?

Comment (azat) [reply src/Parsers/ParserQuery.h:27]: I would prefer to keep structure, it is always easier to extend structure then arguments.
But if you have strong objections, then OK, I can replace it with the variable.

File: src/Parsers/IParser.h (hunk 5 above)
Comment (azat) [reply src/Parsers/IParser.h:56]: Yep, thanks, will rename.
