### PR TITLE
Fix azure native copy setting

### LINKED ISSUE #78964: Implement fallback from native copy to read/write objects for Azure
We have this fallback for S3: https://github.com/ClickHouse/ClickHouse/pull/77401. Need to implement the same for Azure.

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix applying use_native_copy and allow_azure_native_copy setting for azure blob storage and updated to use native copy only when credentials match resolves #78964

Implementation details:
1 . For applying use_native_copy setting from config setting, I have implemented it similar to s3, it will store settings in a map with url/connection_string/endpoint as key and settings as value. This is stored in Context. 
2. `allow_azure_native_copy` if used overrides the config setting `use_native_copy` (as in s3)
3. There is no easy comparison of credentials in azure, so used our wrapper classes to compare if we are using same auth or not. Only drawback is ConnectionString is treated as different auth method. So for example we have 2 disks with same auth one is specified with url setting and another with connection string, they will be treated as different authentication. But this is safe fallback to non-native copy method. But makes implementation clean. (even on azure sdk connection string is handled separately)

cc @vitlibar @kssenii @alesapin @CurtizJ @vinay92-ch 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by SmitaRKulkarni** [comment]
[Integration tests (asan, flaky check)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79561&sha=a02c31c1d0629fa6da2709e12a324fd58d213b42&name_0=PR&name_1=Integration%20tests%20%28asan%2C%20flaky%20check%29) - expected to fail as previous backup exists, we do see all tests pass first time.

Unrelated fails: 
[Stateless tests (asan, distributed plan, 1/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79561&sha=a02c31c1d0629fa6da2709e12a324fd58d213b42&name_0=PR&name_1=Stateless%20tests%20%28asan%2C%20distributed%20plan%2C%201%2F2%29) - 
docker: Error response from daemon: Conflict. The container name "/func-tester" is already in use by container "c5f6ba3296e7ae6ed4022e391f89bdb3282aa129b9b931095754fd65091d66f7". You have to remove (or rename) that container to be able to reuse that name.

[AST fuzzer (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79561&sha=a02c31c1d0629fa6da2709e12a324fd58d213b42&name_0=PR&name_1=AST+fuzzer+%28amd_debug%29) - Logical error: 'Cannot find the original scope of the column'.

[AST fuzzer (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79561&sha=a02c31c1d0629fa6da2709e12a324fd58d213b42&name_0=PR&name_1=AST+fuzzer+%28amd_ubsan%29) - Logical error: 'Replica 1 decided to read in Default mode, not in WithOrder. This is a bug'.

File: src/Backups/RestoreSettings.h [hunk 1]
```diff
@@ -128,6 +128,8 @@ struct RestoreSettings
     /// If not set, then S3 native copy will be allowed only if the source and destination credentials are the same.
     std::optional<bool> allow_s3_native_copy;
 
+    bool allow_azure_native_copy = true;
```
[the remark this answers is not in the document]
Comment (SmitaRKulkarni) [reply src/Backups/RestoreSettings.h:131]: Based on the description here (https://github.com/ClickHouse/ClickHouse/pull/77401) , for azure native copy is not supported if credentials dont match so it would be the same as 'auto' right ? 
So right now, setting it true only uses native copy if credentials match. Please let me know if I am missing something

[the remark this answers is not in the document]
Comment (vitlibar) [reply src/Backups/RestoreSettings.h:131]: ok

File: src/IO/AzureBlobStorage/copyAzureBlobStorageFile.cpp [hunk 2]
```diff
@@ -347,11 +347,12 @@ void copyAzureBlobStorageFile(
     const String & dest_blob,
     std::shared_ptr<const AzureBlobStorage::RequestSettings> settings,
     const ReadSettings & read_settings,
+    bool same_credentials,
     ThreadPoolCallbackRunnerUnsafe<void> schedule)
 {
     auto log = getLogger("copyAzureBlobStorageFile");
 
-    if (settings->use_native_copy)
+    if (settings->use_native_copy && same_credentials)
```
Comment (vitlibar) [inline src/IO/AzureBlobStorage/copyAzureBlobStorageFile.cpp:355]: We can improve logging a bit.

When we investigate incidents it's usually better to see in the logs
```
"Copying Blob: {} from Container: {}, native copy is disabled"
```
or
```
Copying Blob: {} from Container: {}, native copy is disabled because of different credentials
```
instead of
```
"Reading from Container: {}, Blob: {}"
```

File: src/Backups/BackupIO_AzureBlobStorage.cpp [hunk 3]
```diff
@@ -103,6 +104,7 @@ void BackupReaderAzureBlobStorage::copyFileToDisk(const String & path_in_backup,
                 /* dest_path */ dst_blob_path[0],
                 settings,
                 read_settings,
+                connection_params.auth_method == destination_disk->getObjectStorage()->getAzureBlobStorageAuthMethod(),
```
[the remark this answers is not in the document]
Comment (SmitaRKulkarni) [reply src/Backups/BackupIO_AzureBlobStorage.cpp]: addressed it

File: src/Backups/RestoreSettings.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (vitlibar) [reply src/Backups/RestoreSettings.h:131]: Please add some comment in the code about it.

File: src/Disks/ObjectStorages/AzureBlobStorage/AzureBlobStorageCommon.h [hunk 4]
```diff
@@ -154,12 +154,29 @@ std::unique_ptr<ContainerClient> getContainerClient(const ConnectionParams & par
...
 std::unique_ptr<RequestSettings> getRequestSettings(const Settings & query_settings);
-std::unique_ptr<RequestSettings> getRequestSettingsForBackup(const Settings & query_settings, bool use_native_copy);
-std::unique_ptr<RequestSettings> getRequestSettings(const Poco::Util::AbstractConfiguration & config, const String & config_prefix, ContextPtr context);
+std::unique_ptr<RequestSettings> getRequestSettingsForBackup(ContextPtr context, String endpoint, bool use_native_copy);
+std::unique_ptr<RequestSettings> getRequestSettings(const Poco::Util::AbstractConfiguration & config, const String & config_prefix, const Settings & settings_ref);
 
 }
 
-}
+class AzureSettingsByEndpoint
```
Comment (vitlibar) [inline src/Disks/ObjectStorages/AzureBlobStorage/AzureBlobStorageCommon.h:165]: Please add a comment for this class.

File: src/Backups/BackupIO_AzureBlobStorage.cpp [hunk 5]
```diff
@@ -26,6 +26,47 @@ namespace ErrorCodes
     extern const int LOGICAL_ERROR;
 }
 
+
+static bool compareAuthMethod (AzureBlobStorage::AuthMethod auth_method_a, AzureBlobStorage::AuthMethod auth_method_b)
```
Comment (vitlibar) [inline src/Backups/BackupIO_AzureBlobStorage.cpp:30]: Please add a comment for this function.

**Review by vitlibar — APPROVED** [review]

File: src/Backups/BackupIO_AzureBlobStorage.cpp (hunk 5 above)
Comment (SmitaRKulkarni) [reply src/Backups/BackupIO_AzureBlobStorage.cpp:30]: addressed it

File: src/IO/AzureBlobStorage/copyAzureBlobStorageFile.cpp (hunk 2 above)
Comment (SmitaRKulkarni) [reply src/IO/AzureBlobStorage/copyAzureBlobStorageFile.cpp:361]: addressed it

**Comment by SmitaRKulkarni** [comment]
Unrelated fails
[Performance Comparison (amd_release,master_head,3/3)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79561&sha=7ba22db1b0f0faa22e1abaafb489ca9cbd63335a&name_0=PR&name_1=Performance%20Comparison%20%28amd_release%2Cmaster_head%2C3%2F3%29)
