### PR TITLE
Fix segfault in signal handler for Keeper

### LINKED ISSUE #56195: Segmentation fault with clickhouse-keeper
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

version 23.9.2.56 (official build), build id: 76109A79FA62B9BC630A6C39438DEA7D28147B68, git hash: a1bf3f1de55abf2354dc498ffbee270be043d633

I use as dedicated keeper instance with specific configuration and process.

> You have to provide the following information whenever possible.

Repeated Segmentation fault with clickhouse-keeper after I change the IP address of the server.
- I change the system IP address, restart network to apply the change.
- Redeploy all clickhouse-keeper config with the new IP address
- Redeploy all clickhouse-config config with the new IP address
- All clickhouse-keeper server are restarted

By the way, I don't understand why vote is "rejected by quorum". I have 3 servers and the 2 server are uo and running, the keeper cluster works fine. The third server is "rejected by quorum"

I try to erase directory `/var/lib/clickhouse-keeper/` and restart. I don't observe any change.

```
2023.11.01 11:30:00.404736 [ 191770 ] {} <Warning> RaftInstance: Election timeout, initiate leader election
2023.11.01 11:30:00.404832 [ 191770 ] {} <Information> RaftInstance: [PRIORITY] decay, target 1 -> 1, mine 1
2023.11.01 11:30:00.404901 [ 191770 ] {} <Information> RaftInstance: [ELECTION TIMEOUT] current role: candidate, log last term 0, state term 0, target p 1, my p 1, hb dead, pre-vote NOT done
2023.11.01 11:30:00.404957 [ 191770 ] {} <Information> RaftInstance: [PRE-VOTE INIT] my id 2, my role candidate, term 0, log idx 0, log term 0, priority (target 1 / mine 1)
2023.11.01 11:30:00.406459 [ 191773 ] {} <Information> RaftInstance: [PRE-VOTE RESP] peer 3 (X), term 0, resp term 0, my role candidate, dead 1, live 1, abandoned 0, num voting members 3, quorum 2
2023.11.01 11:30:00.406578 [ 191772 ] {} <Information> RaftInstance: [PRE-VOTE RESP] peer 1 (X), term 0, resp term 0, my role candidate, dead 1, live 2, abandoned 0, num voting members 3, quorum 2
2023.11.01 11:30:00.406645 [ 191772 ] {} <Warning> RaftInstance: [PRE-VOTE] rejected by quorum, count 9
```

After stracing other keeper server, I observe other keeper servers trying to connect to old IP address. Maybe this address stored in other place ?

**solution**

It seems two keeper server are leader at the same time. I kill one of them. I reset configuration and I restart it.
I do same things on the "coredump" server, and it restart without error.

I submit the issue, because a segfault is an anormal beahviour. But, solving the problem is not a priority forme ;-)

It seems I do not loose anything on my clickhouse cluster ! very good job for haigh avalaibility and reliability !

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:

Sent to `https://6f33034cfe684dd7a3ab9875e57b1c8d@o388870.ingest.sentry.io/5226277`
At ~ "Wed Nov  1 10:22:02 UTC 2023"

**Error message and/or stacktrace**

just an extract

```
2023.11.01 11:21:04.500648 [ 189979 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.11.01 11:21:04.500774 [ 189979 ] {} <Fatal> BaseDaemon: (version 23.9.2.56 (official build), build id: 76109A79FA62B9BC630A6C39438DEA7D28147B68, git hash: a1bf3f1de55abf2354dc498ffbee270be043d633) (from thread 189978) Received signal 11
2023.11.01 11:21:04.500848 [ 189979 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.11.01 11:21:04.500893 [ 189979 ] {} <Fatal> BaseDaemon: Address: 0x120. Access: read. Address not mapped to object.
2023.11.01 11:21:04.500948 [ 189979 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000ca122ae 0x000000000ca0ccf5 0x00007feffd8d01ca 0x00007feffd53ce73
2023.11.01 11:21:04.500988 [ 189979 ] {} <Fatal> BaseDaemon: ########################################
2023.11.01 11:21:04.501021 [ 189979 ] {} <Fatal> BaseDaemon: (version 23.9.2.56 (official build), build id: 76109A79FA62B9BC630A6C39438DEA7D28147B68, git hash: a1bf3f1de55abf2354dc498ffbee270be043d633) (from thread 189978) (no query) Received signal Segmentation fault (11)
2023.11.01 11:21:04.501056 [ 189979 ] {} <Fatal> BaseDaemon: Address: 0x120. Access: read. Address not mapped to object.
2023.11.01 11:21:04.501085 [ 189979 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000ca122ae 0x000000000ca0ccf5 0x00007feffd8d01ca 0x00007feffd53ce73
2023.11.01 11:21:04.501210 [ 189979 ] {} <Fatal> BaseDaemon: 2. SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, std::vector<std::array<void*, 45ul>, std::allocator<std::array<void*, 45ul>>> const&, unsigned int, DB::ThreadStatus*) const @ 0x000000000ca122ae in /usr/bin/clickhouse
2023.11.01 11:21:04.501292 [ 189979 ] {} <Fatal> BaseDaemon: 3. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, SignalListener::run()::'lambda'()>>(void*) @ 0x000000000ca0ccf5 in /usr/bin/clickhouse
2023.11.01 11:21:04.501375 [ 189979 ] {} <Fatal> BaseDaemon: 4. start_thread @ 0x00000000000081ca in /usr/lib64/libpthread-2.28.so
2023.11.01 11:21:04.501464 [ 189979 ] {} <Fatal> BaseDaemon: 5. clone @ 0x0000000000039e73 in /usr/lib64/libc-2.28.so
2023.11.01 11:21:04.938753 [ 189979 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 3A99FBFAA2DA54D46975E9ABC04E53E0)
2023.11.01 11:21:04.939453 [ 189980 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.11.01 11:21:04.939576 [ 189980 ] {} <Fatal> BaseDaemon: (version 23.9.2.56 (official build), build id: 76109A79FA62B9BC630A6C39438DEA7D28147B68, git hash: a1bf3f1de55abf2354dc498ffbee270be043d633) (from thread 189979) Received signal 11
2023.11.01 11:21:04.939643 [ 189980 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.11.01 11:21:04.939706 [ 189980 ] {} <Fatal> BaseDaemon: Address: 0x120. Access: read. Address not mapped to object.
2023.11.01 11:21:04.939796 [ 189980 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000ca122ae 0x000000000ca0ccf5 0x00007feffd8d01ca 0x00007feffd53ce73
2023.11.01 11:21:04.939872 [ 189980 ] {} <Fatal> BaseDaemon: ########################################
2023.11.01 11:21:04.939943 [ 189980 ] {} <Fatal> BaseDaemon: (version 23.9.2.56 (official build), build id: 76109A79FA62B9BC630A6C39438DEA7D28147B68, git hash: a1bf3f1de55abf2354dc498ffbee270be043d633) (from thread 189979) (no query) Received signal Segmentation fault (11)
2023.11.01 11:21:04.940013 [ 189980 ] {} <Fatal> BaseDaemon: Address: 0x120. Access: read. Address not mapped to object.
2023.11.01 11:21:04.940067 [ 189980 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000ca122ae 0x000000000ca0ccf5 0x00007feffd8d01ca 0x00007feffd53ce73
2023.11.01 11:21:04.940256 [ 189980 ] {} <Fatal> BaseDaemon: 2. SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, std::vector<std::array<void*, 45ul>, std::allocator<std::array<void*, 45ul>>> const&, unsigned int, DB::ThreadStatus*) const @ 0x000000000ca122ae in /usr/bin/clickhouse
2023.11.01 11:21:04.940393 [ 189980 ] {} <Fatal> BaseDaemon: 3. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, SignalListener::run()::'lambda'()>>(void*) @ 0x000000000ca0ccf5 in /usr/bin/clickhouse
2023.11.01 11:21:04.940530 [ 189980 ] {} <Fatal> BaseDaemon: 4. start_thread @ 0x00000000000081ca in /usr/lib64/libpthread-2.28.so
2023.11.01 11:21:04.940657 [ 189980 ] {} <Fatal> BaseDaemon: 5. clone @ 0x0000000000039e73 in /usr/lib64/libc-2.28.so
2023.11.01 11:21:05.398895 [ 189980 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 3A99FBFAA2DA54D46975E9ABC04E53E0)
```

** I Add strace captured during the problem**

[trace.tgz](https://github.com/ClickHouse/ClickHouse/files/13225873/trace.tgz)

** this is a GDB backtrace **

```
#0  0x00007fb21252facf in raise () from /lib64/libc.so.6
#1  0x00007fb212502ea5 in abort () from /lib64/libc.so.6
#2  0x000000001393d5a6 in DB::KeeperStateManager::system_exit(int) ()
#3  0x0000000015badca2 in nuraft::raft_server::send_reconnect_request() ()
#4  0x0000000015bdc183 in nuraft::raft_server::handle_prevote_resp(nuraft::resp_msg&) ()
#5  0x0000000015ba5c95 in nuraft::raft_server::handle_peer_resp(std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&) ()
#6  0x0000000015b41a39 in nuraft::cmd_result<std::__1::shared_ptr<nuraft::resp_msg>, std::__1::shared_ptr<nuraft::rpc_exception> >::set_result(std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&, nuraft::cmd_result_code) ()
#7  0x0000000015b4120b in nuraft::peer::handle_rpc_result(std::__1::shared_ptr<nuraft::peer>, std::__1::shared_ptr<nuraft::rpc_client>, std::__1::shared_ptr<nuraft::req_msg>&, std::__1::shared_ptr<nuraft::cmd_result<std::__1::shared_ptr<nuraft::resp_msg>, std::__1::shared_ptr<nuraft::rpc_exception> > >&, std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&) ()
#8  0x0000000015b42d3e in void std::__1::__function::__policy_invoker<void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)>::__call_impl<std::__1::__function::__default_alloc_func<std::__1::__bind<void (nuraft::peer::*)(std::__1::shared_ptr<nuraft::peer>, std::__1::shared_ptr<nuraft::rpc_client>, std::__1::shared_ptr<nuraft::req_msg>&, std::__1::shared_ptr<nuraft::cmd_result<std::__1::shared_ptr<nuraft::resp_msg>, std::__1::shared_ptr<nuraft::rpc_exception> > >&, std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&), nuraft::peer*, std::__1::shared_ptr<nuraft::peer>&, std::__1::shared_ptr<nuraft::rpc_client>&, std::__1::shared_ptr<nuraft::req_msg>&, std::__1::shared_ptr<nuraft::cmd_result<std::__1::shared_ptr<nuraft::resp_msg>, std::__1::shared_ptr<nuraft::rpc_exception> > >&, std::__1::placeholders::__ph<1> const&, std::__1::placeholders::__ph<2> const&>, void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)> >(std::__1::__function::__policy_storage const*, std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&) ()
#9  0x0000000015b7286e in nuraft::asio_rpc_client::response_read(std::__1::shared_ptr<nuraft::req_msg>&, std::__1::function<void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)>&, std::__1::shared_ptr<nuraft::buffer>&, std::__1::error_code, unsigned long) ()
#10 0x0000000015b79172 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::any_io_executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, std::__1::__bind<void (nuraft::asio_rpc_client::*)(std::__1::shared_ptr<nuraft::req_msg>&, std::__1::function<void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)>&, std::__1::shared_ptr<nuraft::buffer>&, std::__1::error_code, unsigned long), std::__1::shared_ptr<nuraft::asio_rpc_client>&, std::__1::shared_ptr<nuraft::req_msg>&, std::__1::function<void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)>&, std::__1::shared_ptr<nuraft::buffer>&, std::__1::placeholders::__ph<1> const&, std::__1::placeholders::__ph<2> const&> >::operator()(boost::system::error_code, unsigned long, int) ()
#11 0x0000000015b79d01 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::any_io_executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, std::__1::__bind<void (nuraft::asio_rpc_client::*)(std::__1::shared_ptr<nuraft::req_msg>&, std::__1::function<void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)>&, std::__1::shared_ptr<nuraft::buffer>&, std::__1::error_code, unsigned long), std::__1::shared_ptr<nuraft::asio_rpc_client>&, std::__1::shared_ptr<nuraft::req_msg>&, std::__1::function<void (std::__1::shared_ptr<nuraft::resp_msg>&, std::__1::shared_ptr<nuraft::rpc_exception>&)>&, std::__1::shared_ptr<nuraft::buffer>&, std::__1::placeholders::__ph<1> const&, std::__1::placeholders::__ph<2> const&> >, boost::asio::any_io_executor>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
#12 0x0000000015b4d014 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#13 0x0000000015b45881 in nuraft::asio_service_impl::worker_entry() ()
#14 0x0000000015b5307a in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (nuraft::asio_service_impl::*)(), nuraft::asio_service_impl*> > >(void*) ()
#15 0x00007fb2128ae1ca in start_thread () from /lib64/libpthread.so.0
#16 0x00007fb21251ae73 in clone () from /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix segfault in signal handler for Keeper.

Fix https://github.com/ClickHouse/ClickHouse/issues/56195

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -3430,7 +3430,8 @@ void Context::initializeTraceCollector()
 /// Call after unexpected crash happen.
 void Context::handleCrash() const TSA_NO_THREAD_SAFETY_ANALYSIS
 {
-    shared->system_logs->handleCrash();
+    if (shared->system_logs)
```
Comment (vdimir) [inline src/Interpreters/Context.cpp:3433]: Since it's possible that `shared->system_logs` is being initialized we can have a race here, that's why `TSA_NO_THREAD_SAFETY_ANALYSIS` are used, am I right? But I suppose we cannot get segfault, because `shared->system_logs` is only set once from nullptr to value during initialization.

**Review by vdimir — APPROVED** [review]

File: src/Interpreters/Context.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Interpreters/Context.cpp:3433]: > Since it's possible that shared->system_logs is being initialized we can have a race here, that's why TSA_NO_THREAD_SAFETY_ANALYSIS are used, am I right?

Yes, but we never initialize it for Keeper so it should be okay
