### PR TITLE
Fix AST error for Nothing type in null-safe comparison

### LINKED ISSUE #84870: Unknown numeric column of type: DB::ColumnNothing
```sql
SELECT * WHERE materialize(0) AND (less(NULL IS NULL, 0) >= less(materialize(0), NULL)) GROUP BY NULL, toUInt256(0) >= greater(materialize(toNullable(NULL)), 0 IS NOT NULL),                   * HAVING (toNullable(0), NULL < lessOrEquals(isNullable(0), NULL IS NULL)) >= (toNullable(0), assumeNotNull(materialize(NULL)) <= greater(assumeNotNull(0), NULL))
```

CI: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84734&sha=latest&name_0=PR&name_1=AST+fuzzer+%28amd_debug%29

### LINKED ISSUE #91821: [fuzzer] isNotDistinctFrom crashes with “Expected UInt8. Got Nothing” on assumeNotNull(materialize(NULL)) in filter
### Describe the bug

assumeNotNull(materialize(NULL)) yields a ColumnNothing.

isNotDistinctFrom (null-safe comparator) builds its comparator with result type UInt8 but receives ColumnNothing and propagates it, leading to the runtime type check failure (executeAction sees Nothing instead of UInt8).

Expected result: a valid UInt8 filter (likely all 0) or a clean, typed empty result—no logical error.

### How to reproduce

```SELECT * FROM system.one WHERE isNotDistinctFrom(assumeNotNull(materialize(NULL)), 1);```

http://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91431&sha=2c87d97a664c2b2757e96e022608f6c2f24c37bb&name_0=PR&name_1=AST+fuzzer+%28amd_ubsan%29

### Error message and/or stacktrace

Unexpected return type from isNotDistinctFrom. Expected UInt8. Got Nothing.

### LINKED ISSUE #91834: Logical error: 'Unknown numeric column x of type: DB::ColumnNothing'
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: Unknown numeric column of type: A (STID: 0250-04e2)

--
CI report: [AST fuzzer (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92095&sha=ab92989263f0aa9cee04b8d9489d4a855f6fc044&name_0=PR&name_1=AST%20fuzzer%20%28arm_asan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiBVbmtub3duIG51bWVyaWMgY29sdW1uIHggb2YgdHlwZTogQScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0FTVCBmdXp6ZXIgKGFybV9hc2FuKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

### Company or project name

_No response_

### Describe what's wrong

Failed here: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90490&sha=d5ddf49376476ba98fe4e83dc6f3023103150c35&name_0=PR&name_1=AST+fuzzer+%28amd_msan%29

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Fails on head: https://fiddle.clickhouse.com/874bde72-9986-4717-8831-7e8db961deb1

### Expected behavior

Not to fail with LOGICAL_ERROR.

### Error message and/or stacktrace

```
Stack trace:
__GI___pthread_kill @ 0x00000000000969fd
raise @ 0x0000000000042476
__lgamma_r_finite @ 0x00000000000287f3
src/Common/Exception.cpp:54: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x000000002b4f3fc7
src/Common/Exception.cpp:87: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000002b4f624a
src/Common/Exception.cpp:138: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002b4f6ca3
DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000a897dee
DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000a896abf
void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x0000000039bcd795
void DB::(anonymous namespace)::TypedExecutorInvoker<DB::FunctionsLogicalDetail::AndImpl, char8_t, unsigned short, unsigned int, unsigned long, _BitInt(8), short, int, long, float, double>::apply<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>>(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x0000000039b4d35d
DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000039da27f3
src/Functions/IFunctionAdaptors.cpp:10: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000399b279b
DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000003999cd07
DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a19fd
DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a849b
DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a6ea4
DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a953f
DB::FunctionComparison<DB::EqualsOp, DB::NameEquals, true>::executeTupleEqualityImpl(std::shared_ptr<DB::IFunctionOverloadResolver>, std::shared_ptr<DB::IFunctionOverloadResolver>, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, unsigned long, unsigned long) const @ 0x000000001be875a9
DB::FunctionComparison<DB::EqualsOp, DB::NameEquals, true>::executeTupleImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, unsigned long, unsigned long) const @ 0x000000001be85c80
DB::FunctionComparison<DB::EqualsOp, DB::NameEquals, true>::executeTuple(std::shared_ptr<DB::IDataType const> const&, DB::ColumnWithTypeAndName const&, DB::ColumnWithTypeAndName const&, unsigned long) const @ 0x000000001bed437f
DB::FunctionComparison<DB::EqualsOp, DB::NameEquals, true>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001be8e8bb
src/Functions/IFunctionAdaptors.cpp:10: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000399b279b
DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000003999cd07
DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a19fd
DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a849b
DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a6ea4
DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a953f
DB::FunctionsNullSafeCmp<DB::NameFunctionIsNotDistinctFrom, (DB::NullSafeCmpMode)0, DB::EqualsOp, DB::NameEquals>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001be8ae75
DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000a893762
src/Functions/IFunctionAdaptors.cpp:16: DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000399b289b
DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000003999cb83
DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a19fd
DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a849b
DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000399a6ea4
src/Interpreters/ActionsDAG.cpp:895: DB::executeActionForPartialResult(DB::ActionsDAG::Node const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>, unsigned long, bool) @ 0x000000003eee1a63
src/Interpreters/ActionsDAG.cpp:1103: DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, DB::PartialEvaluationParameters) @ 0x000000003eeda099
src/Interpreters/ActionsDAG.cpp:995: DB::ActionsDAG::updateHeader(DB::Block const&) const @ 0x000000003eed6ead
src/Processors/Transforms/FilterTransform.cpp:52: DB::FilterTransform::transformHeader(DB::Block const&, DB::ActionsDAG const*, String const&, bool) @ 0x000000005287e468
src/Processors/QueryPlan/FilterStep.cpp:127: DB::FilterStep::FilterStep(std::shared_ptr<DB::Block const> const&, DB::ActionsDAG, String, bool) @ 0x00000000530d37db
./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:759: std::unique_ptr<DB::FilterStep, std::default_delete<DB::FilterStep>> std::make_unique[abi:ne210105]<DB::FilterStep, std::shared_ptr<DB::Block const> const&, DB::ActionsDAG, String&, bool&, 0>(std::shared_ptr<DB::Block const> const&, DB::ActionsDAG&&, String&, bool&) @ 0x000000004008e3ea
src/Planner/Planner.cpp:557: void DB::(anonymous namespace)::addFilterStep<6ul>(std::shared_ptr<DB::PlannerContext> const&, DB::QueryPlan&, DB::FilterAnalysisResult&, DB::SelectQueryOptions const&, char const (&) [6ul], std::unordered_set<std::shared_ptr<DB::FutureSet>, std::hash<std::shared_ptr<DB::FutureSet>>, std::equal_to<std::shared_ptr<DB::FutureSet>>, std::allocator<std::shared_ptr<DB::FutureSet>>>&)
src/Planner/Planner.cpp:1956: DB::Planner::buildPlanForQueryNode() @ 0x00000000400432d0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yariks5s**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixes an error where we have a null-safe comparison involving the Nothing type. Closes https://github.com/ClickHouse/ClickHouse/issues/91834. Closes https://github.com/ClickHouse/ClickHouse/issues/84870. Closes https://github.com/ClickHouse/ClickHouse/issues/91821.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03757_nothing_null_safe_comparison.sql [hunk 1]
```diff
@@ -0,0 +1,20 @@
+-- Fixes bug: https://github.com/ClickHouse/ClickHouse/issues/91834
```
Comment (nihalzp) [inline tests/queries/0_stateless/03757_nothing_null_safe_comparison.sql:1]: I think using `-- { echoOn }` at the top would make reading .reference output bit easier as some of the queries return no rows and some return 1 and it is not immediately clear which output belongs to which query.

File: src/Functions/FunctionsNullSafeCmp.h [hunk 2]
```diff
@@ -152,6 +152,21 @@ class FunctionsNullSafeCmp : public IFunction
                     : type_and_name_right_col);
         }
 
+        // To address: Nothing type comparison
+        // Nothing represents an absence of any value, similar to NULL.
+        // Nothing <=> Nothing should return true (both represent absence)
```
Comment (nihalzp) [inline src/Functions/FunctionsNullSafeCmp.h]: > // Nothing <=> Nothing should return true (both represent absence)

Based on the comment, I was expecting the following queries to work.

```sql
SELECT 1 WHERE (assumeNotNull(NULL) <=> assumeNotNull(NULL));
Code: 44. DB::Exception: Cannot create non-empty column with type Nothing: In scope SELECT 1 WHERE assumeNotNull(NULL) <=> assumeNotNull(NULL). (ILLEGAL_COLUMN)
```

```sql
SELECT 1 WHERE (assumeNotNull(materialize(NULL)) <=> assumeNotNull(materialize(NULL)));
Code: 44. DB::Exception: Cannot create non-empty column with type Nothing: while executing 'FUNCTION assumeNotNull(materialize(_CAST(NULL_Nullable(Nothing), 'Nullable(Nothing)'_String)) :: 2) -> assumeNotNull(materialize(_CAST(NULL_Nullable(Nothing), 'Nullable(Nothing)'_String))) Nothing : 1'. (ILLEGAL_COLUMN)
```

I think that for the `Nothing` type we should return `DataTypeNothing` by using the default implementation for `Nothing`, because that's how other functions handle it; though I am not 100% sure since this function is supposed to be null-safe. However, because `NULL` (i.e., `Nullable(Nothing)`) is different from `Nothing`, as long as `<=>` works for `NULL`s, I don't think `<=>` needs to work for `Nothing`.

**Review by nihalzp — COMMENTED** [review]
The following issue should also be resolved by this fix.

- https://github.com/clickhouse/clickhouse/issues/91821

File: src/Functions/FunctionsNullSafeCmp.h (hunk 2 above)
Comment (yariks5s) [reply src/Functions/FunctionsNullSafeCmp.h]: The errors you're getting in your queries are not from the comparison operator, but from `assumeNotNull`:

```
SELECT assumeNotNull(NULL)

Received exception from server (version 25.12.1):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create non-empty column with type Nothing: In scope SELECT assumeNotNull(NULL). (ILLEGAL_COLUMN)
```

So these queries most probably should not succeed.

Comment (yariks5s) [reply src/Functions/FunctionsNullSafeCmp.h]: Also, enabling defaultImplementationForNothing is not helping with the initial problem I was fixing

Comment (nihalzp) [reply src/Functions/FunctionsNullSafeCmp.h]: Only turning `defaultImplementationForNothing` to `true` is not enough because the input type is `Tuple(Nothing, ..)` instead of `Nothing`. I think the cleanest solution could be that,
- `defaultImplementationForNothing()` to `true`
- Inside `getReturnTypeImpl()`, if type is `Tuple`, we go inside and check if any of the element is `Nothing` or not. If `Nothing`, then we return `DataTypeNothing`.

This should be enough I think. No need to change anything in `executeImpl`. Then, we should get good exception like `ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER` for queries like 
```sql
SELECT 1 WHERE (assumeNotNull(materialize(NULL)), 1) <=> (1, 1);
```

Comment (yariks5s) [reply src/Functions/FunctionsNullSafeCmp.h]: Agree, I've pushed the commit with changes.

Comment (alexey-milovidov) [reply src/Functions/FunctionsNullSafeCmp.h]: `assumeNotNull(NULL)` is ill-defined and it should throw an exception for `Nullable(Nothing)`.
For a NULL value of type Nullable of non-bottom types, it is implementation-defined.

Comment (nihalzp) [reply src/Functions/FunctionsNullSafeCmp.h]: Yes, after the latest changes, we now throw exception for case of `assumeNotNull(Nullable(Nothing))`.

**Review by nihalzp — APPROVED** [review]

**Comment by yariks5s** [comment]
[Stateless tests (amd_msan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91884&sha=af141fd95232cd3bc89fc63d17d62d390ebcbc83&name_0=PR&name_1=Stateless+tests+%28amd_msan%2C+parallel%29) -- timeout

[Integration tests (arm_binary, distributed plan, 4/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91884&sha=af141fd95232cd3bc89fc63d17d62d390ebcbc83&name_0=PR&name_1=Integration+tests+%28arm_binary%2C+distributed+plan%2C+4%2F4%29) -- bug with already existing table, should be already fixed

[Integration tests (amd_tsan, 4/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91884&sha=af141fd95232cd3bc89fc63d17d62d390ebcbc83&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+4%2F6%29) -- https://github.com/ClickHouse/ClickHouse/issues/85664
