### PR TITLE
Fix assertion in bloom filter index

### LINKED ISSUE #40099: Logical error: 'Invalid Field get from type Null to type UInt64' in bloom filter
**How to reproduce**
```sql
SET allow_suspicious_low_cardinality_types = 1;

DROP TABLE IF EXISTS bftest__fuzz_21;

CREATE TABLE bftest__fuzz_21
(
    `k` LowCardinality(Int8),
    `y` Array(Int8) DEFAULT x,
    `x` Array(UInt8),
    INDEX ix1 x TYPE bloom_filter GRANULARITY 3
)
ENGINE = MergeTree
ORDER BY k;

INSERT INTO bftest__fuzz_21 (k, x) SELECT
    number,
    arrayMap(i -> (rand64() % 565656), range(10))
FROM numbers(1000);

SELECT count() FROM bftest__fuzz_21 WHERE hasAll(x, [42, -42]);
```

```
2022.08.11 03:12:06.528850 [ 2541331 ] {5b6b953a-d88f-4816-800f-6af5cd95421c} <Fatal> : Logical error: 'Invalid Field get from type Null to type UInt64'.
2022.08.11 03:12:06.529685 [ 2541328 ] {} <Trace> BaseDaemon: Received signal 6
2022.08.11 03:12:06.530359 [ 2541616 ] {} <Fatal> BaseDaemon: ########################################
2022.08.11 03:12:06.530660 [ 2541616 ] {} <Fatal> BaseDaemon: (version 22.8.1.1 (official build), build id: B7F0FF29F1059780) (from thread 2541331) (query_id: 5b6b953a-d88f-4816-800f-6af5cd95421c) (query: SELECT count() FROM bftest__fuzz_21 WHERE hasAll(x, [42, -42]);) Received signal Aborted (6)
2022.08.11 03:12:06.530880 [ 2541616 ] {} <Fatal> BaseDaemon:
2022.08.11 03:12:06.531124 [ 2541616 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f8966b5a03b 0x7f8966b39859 0x17168fb6 0x17169075 0x17169125 0x1731132e 0x19403166 0x1b6eb7bd 0x263ff035 0x27a85945 0x284a1ccf 0x284a0e07 0x284a09d3 0x284a5938 0x284a58b6 0x284a5851 0x284a57cc 0x284a5754 0x284cbe7a 0x284cacb0 0x284ca910 0x284a5c94 0x2849f834 0x28497193 0x28496ef0 0x28496b5f 0x28496946 0x2849494d 0x28493998 0x2842efab 0x28fdb572 0x28fda0cf 0x28fdbd8d 0x28fdbf3b 0x28f95695 0x28fbc000 0x273a22b1 0x277fbb17 0x277f8344 0x288d1d66 0x288e1c25
2022.08.11 03:12:06.531378 [ 2541616 ] {} <Fatal> BaseDaemon: 4. raise in ?
2022.08.11 03:12:06.531488 [ 2541616 ] {} <Fatal> BaseDaemon: 5. abort in ?
2022.08.11 03:12:06.624359 [ 2541616 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /usr/bin/clickhouse
2022.08.11 03:12:06.716830 [ 2541616 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../src/Common/Exception.cpp:63: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) in /usr/bin/clickhouse
2022.08.11 03:12:06.794950 [ 2541616 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
2022.08.11 03:12:08.451962 [ 2541616 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../src/Core/Field.h:838: DB::NearestFieldTypeImpl<std::__1::decay<char8_t>::type, void>::Type& DB::Field::get<char8_t>() in /usr/bin/clickhouse
2022.08.11 03:12:09.000280 [ 2541468 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.40 GiB, peak 1.40 GiB, will set to 1.43 GiB (RSS), difference: 36.82 MiB
2022.08.11 03:12:09.161333 [ 2541616 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Core/Field.h:429: auto const& DB::Field::get<char8_t>() const in /usr/bin/clickhouse
2022.08.11 03:12:09.299471 [ 2541616 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Core/Field.h:888: char8_t DB::get<char8_t>(DB::Field const&) in /usr/bin/clickhouse
2022.08.11 03:12:09.669271 [ 2541616 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../src/Columns/ColumnVector.h:304: DB::ColumnVector<char8_t>::insert(DB::Field const&) in /usr/bin/clickhouse
2022.08.11 03:12:09.897558 [ 2541616 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../src/Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp:558: DB::MergeTreeIndexConditionBloomFilter::traverseASTEquals(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::IDataType const> const&, DB::Field const&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&, std::__1::shared_ptr<DB::IAST> const&) in /usr/bin/clickhouse
2022.08.11 03:12:10.000262 [ 2541468 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.43 GiB, peak 1.43 GiB, will set to 1.53 GiB (RSS), difference: 93.09 MiB
2022.08.11 03:12:10.122826 [ 2541616 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../src/Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp:299: DB::MergeTreeIndexConditionBloomFilter::traverseFunction(std::__1::shared_ptr<DB::IAST> const&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&, std::__1::shared_ptr<DB::IAST> const&) in /usr/bin/clickhouse
2022.08.11 03:12:10.340862 [ 2541330 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #2
2022.08.11 03:12:10.347824 [ 2541616 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../src/Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp:255: DB::MergeTreeIndexConditionBloomFilter::traverseAtomAST(std::__1::shared_ptr<DB::IAST> const&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) in /usr/bin/clickhouse
2022.08.11 03:12:10.682069 [ 2541616 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../src/Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp:113: auto DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3::operator()<std::__1::shared_ptr<DB::IAST> const, std::__1::shared_ptr<DB::Context const>, DB::Block, DB::MergeTreeIndexConditionBloomFilter::RPNElement>(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) const in /usr/bin/clickhouse
2022.08.11 03:12:11.000260 [ 2541468 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.53 GiB, peak 1.53 GiB, will set to 1.53 GiB (RSS), difference: 2.42 MiB
2022.08.11 03:12:11.022188 [ 2541616 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3&>(fp)(static_cast<std::__1::shared_ptr<DB::IAST> const&>(fp0), static_cast<std::__1::shared_ptr<DB::Context const>>(fp0), static_cast<DB::Block&>(fp0), static_cast<DB::MergeTreeIndexConditionBloomFilter::RPNElement&>(fp0))) std::__1::__invoke<DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&>(DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>&&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) in /usr/bin/clickhouse
2022.08.11 03:12:11.356611 [ 2541616 ] {} <Fatal> BaseDaemon: 19. /build/build_docker/../contrib/libcxx/include/__functional/invoke.h:30: bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&>(DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>&&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) in /usr/bin/clickhouse
2022.08.11 03:12:11.691110 [ 2541616 ] {} <Fatal> BaseDaemon: 20. /build/build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3, bool (std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&)>::operator()(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>&&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) in /usr/bin/clickhouse
2022.08.11 03:12:12.000260 [ 2541468 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 1.53 GiB, peak 1.53 GiB, will set to 1.53 GiB (RSS), difference: 2.44 MiB
2022.08.11 03:12:12.026338 [ 2541616 ] {} <Fatal> BaseDaemon: 21. /build/build_docker/../contrib/libcxx/include/__functional/function.h:711: bool std::__1::__function::__policy_invoker<bool (std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long)::$_3, bool (std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&)> >(std::__1::__function::__policy_storage const*, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>&&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) in /usr/bin/clickhouse
2022.08.11 03:12:12.367854 [ 2541616 ] {} <Fatal> BaseDaemon: 22. /build/build_docker/../contrib/libcxx/include/__functional/function.h:843: std::__1::__function::__policy_func<bool (std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&)>::operator()(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>&&, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) const in /usr/bin/clickhouse
2022.08.11 03:12:12.708338 [ 2541616 ] {} <Fatal> BaseDaemon: 23. /build/build_docker/../contrib/libcxx/include/__functional/function.h:1184: std::__1::function<bool (std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&)>::operator()(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&) const in /usr/bin/clickhouse
2022.08.11 03:12:13.047339 [ 2541616 ] {} <Fatal> BaseDaemon: 24. /build/build_docker/../src/Storages/MergeTree/RPNBuilder.h:82: DB::RPNBuilder<DB::MergeTreeIndexConditionBloomFilter::RPNElement>::traverseAST(std::__1::shared_ptr<DB::IAST> const&) in /usr/bin/clickhouse
2022.08.11 03:12:13.271870 [ 2541616 ] {} <Fatal> BaseDaemon: 25. /build/build_docker/../src/Storages/MergeTree/RPNBuilder.h:37: DB::RPNBuilder<DB::MergeTreeIndexConditionBloomFilter::RPNElement>::RPNBuilder(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, std::__1::function<bool (std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::Block&, DB::MergeTreeIndexConditionBloomFilter::RPNElement&)> const&) in /usr/bin/clickhouse
2022.08.11 03:12:13.483676 [ 2541616 ] {} <Fatal> BaseDaemon: 26. /build/build_docker/../src/Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp:114: DB::MergeTreeIndexConditionBloomFilter::MergeTreeIndexConditionBloomFilter(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, DB::Block const&, unsigned long) in /usr/bin/clickhouse
2022.08.11 03:12:13.638278 [ 2541616 ] {} <Fatal> BaseDaemon: 27. /build/build_docker/../contrib/libcxx/include/__memory/construct_at.h:38: DB::MergeTreeIndexConditionBloomFilter* std::__1::construct_at<DB::MergeTreeIndexConditionBloomFilter, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&, DB::MergeTreeIndexConditionBloomFilter*>(DB::MergeTreeIndexConditionBloomFilter*, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&) in /usr/bin/clickhouse
2022.08.11 03:12:13.790731 [ 2541616 ] {} <Fatal> BaseDaemon: 28. /build/build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:302: void std::__1::allocator_traits<std::__1::allocator<DB::MergeTreeIndexConditionBloomFilter> >::construct<DB::MergeTreeIndexConditionBloomFilter, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&, void, void>(std::__1::allocator<DB::MergeTreeIndexConditionBloomFilter>&, DB::MergeTreeIndexConditionBloomFilter*, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&) in /usr/bin/clickhouse
2022.08.11 03:12:13.943037 [ 2541616 ] {} <Fatal> BaseDaemon: 29. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:293: std::__1::__shared_ptr_emplace<DB::MergeTreeIndexConditionBloomFilter, std::__1::allocator<DB::MergeTreeIndexConditionBloomFilter> >::__shared_ptr_emplace<DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&>(std::__1::allocator<DB::MergeTreeIndexConditionBloomFilter>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&) in /usr/bin/clickhouse
2022.08.11 03:12:14.096882 [ 2541616 ] {} <Fatal> BaseDaemon: 30. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:954: std::__1::shared_ptr<DB::MergeTreeIndexConditionBloomFilter> std::__1::allocate_shared<DB::MergeTreeIndexConditionBloomFilter, std::__1::allocator<DB::MergeTreeIndexConditionBloomFilter>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&, void>(std::__1::allocator<DB::MergeTreeIndexConditionBloomFilter> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&) in /usr/bin/clickhouse
2022.08.11 03:12:14.243510 [ 2541616 ] {} <Fatal> BaseDaemon: 31. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:963: std::__1::shared_ptr<DB::MergeTreeIndexConditionBloomFilter> std::__1::make_shared<DB::MergeTreeIndexConditionBloomFilter, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&, void>(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>&, DB::Block const&, unsigned long const&) in /usr/bin/clickhouse
2022.08.11 03:12:14.379671 [ 2541616 ] {} <Fatal> BaseDaemon: 32. /build/build_docker/../src/Storages/MergeTree/MergeTreeIndexBloomFilter.cpp:76: DB::MergeTreeIndexBloomFilter::createIndexCondition(DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse
2022.08.11 03:12:15.010721 [ 2541616 ] {} <Fatal> BaseDaemon: 33. /build/build_docker/../src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:915: DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >&&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const> const&, DB::KeyCondition const&, DB::MergeTreeReaderSettings const&, Poco::Logger*, unsigned long, std::__1::vector<DB::ReadFromMergeTree::IndexStat, std::__1::allocator<DB::ReadFromMergeTree::IndexStat> >&, bool) in /usr/bin/clickhouse
2022.08.11 03:12:15.509153 [ 2541616 ] {} <Fatal> BaseDaemon: 34. /build/build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:966: DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::shared_ptr<DB::ActionsDAG> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::Context const>, unsigned int, std::__1::shared_ptr<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > >, DB::MergeTreeData const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, Poco::Logger*) in /usr/bin/clickhouse
2022.08.11 03:12:16.006159 [ 2541616 ] {} <Fatal> BaseDaemon: 35. /build/build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:835: DB::ReadFromMergeTree::selectRangesToRead(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >) const in /usr/bin/clickhouse
2022.08.11 03:12:16.502883 [ 2541616 ] {} <Fatal> BaseDaemon: 36. /build/build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:1045: DB::ReadFromMergeTree::getAnalysisResult() const in /usr/bin/clickhouse
2022.08.11 03:12:16.971319 [ 2541616 ] {} <Fatal> BaseDaemon: 37. /build/build_docker/../src/Processors/QueryPlan/ReadFromMergeTree.cpp:0: DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) in /usr/bin/clickhouse
2022.08.11 03:12:17.093883 [ 2541616 ] {} <Fatal> BaseDaemon: 38. /build/build_docker/../src/Processors/QueryPlan/ISourceStep.cpp:16: DB::ISourceStep::updatePipeline(std::__1::vector<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPipelineBuilder, std::__1::default_delete<DB::QueryPipelineBuilder> > > >, DB::BuildQueryPipelineSettings const&) in /usr/bin/clickhouse
2022.08.11 03:12:17.271959 [ 2541616 ] {} <Fatal> BaseDaemon: 39. /build/build_docker/../src/Processors/QueryPlan/QueryPlan.cpp:187: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) in /usr/bin/clickhouse
2022.08.11 03:12:17.521363 [ 2541616 ] {} <Fatal> BaseDaemon: 40. /build/build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:370: DB::InterpreterSelectWithUnionQuery::execute() in /usr/bin/clickhouse
2022.08.11 03:12:17.835238 [ 2541616 ] {} <Fatal> BaseDaemon: 41. /build/build_docker/../src/Interpreters/executeQuery.cpp:694: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) in /usr/bin/clickhouse
2022.08.11 03:12:18.166707 [ 2541616 ] {} <Fatal> BaseDaemon: 42. /build/build_docker/../src/Interpreters/executeQuery.cpp:1085: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) in /usr/bin/clickhouse
2022.08.11 03:12:18.482551 [ 2541616 ] {} <Fatal> BaseDaemon: 43. /build/build_docker/../src/Server/TCPHandler.cpp:338: DB::TCPHandler::runImpl() in /usr/bin/clickhouse
2022.08.11 03:12:18.826774 [ 2541616 ] {} <Fatal> BaseDaemon: 44. /build/build_docker/../src/Server/TCPHandler.cpp:1838: DB::TCPHandler::run() in /usr/bin/clickhouse
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #40099

### CODE REVIEW

File: tests/queries/0_stateless/02456_bloom_filter_assert.sql.j2 [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+{% if 'UInt' in type -%}
+    SELECT count() FROM bftest__fuzz_21 WHERE hasAll(x, [42, -42]) SETTINGS use_skip_indexes=1;
+    SELECT count() FROM bftest__fuzz_21 WHERE hasAll(x, [42, -42]) SETTINGS use_skip_indexes=1, force_data_skipping_indices='ix1'; -- { serverError INDEX_NOT_USED }
+{% else -%}
+    SELECT count() FROM bftest__fuzz_21 WHERE hasAll(x, [42, -42]) SETTINGS use_skip_indexes=1, force_data_skipping_indices='ix1';
+{% endif -%}
+
+DROP TABLE IF EXISTS bftest__fuzz_21;
+
+{% endfor -%}
```
Comment (kitaisreal) [inline tests/queries/0_stateless/02456_bloom_filter_assert.sql.j2:28]: Need to add new line.

**Review by kitaisreal — APPROVED** [review]

**Comment by CurtizJ** [comment]
One of stress tests: #42095.
