### PR TITLE
Fix schema inference for table function s3

### LINKED ISSUE #34177: `s3` table function does not work without format or structure arguments
**Describe the unexpected behaviour**

```
ip-172-31-0-100.eu-central-1.compute.internal :) SELECT count() FROM s3('s3://clickhouse-public-datasets/hits.native.zst')

SELECT count()
FROM s3('s3://clickhouse-public-datasets/hits.native.zst')

Query id: 4cbfafb3-3dcf-46c5-b107-d179e3560f6a


0 rows in set. Elapsed: 0.013 sec. 

Received exception:
Code: 42. DB::Exception: The signature of table function s3 could be the following:
 - url, format
 - url, format, structure
 - url, format, structure, compression_method
 - url, access_key_id, secret_access_key, format, structure
 - url, access_key_id, secret_access_key, format, structure, compression_method. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)

ip-172-31-0-100.eu-central-1.compute.internal :) SELECT count() FROM s3('s3://clickhouse-public-datasets/hits.native.zst', Native)

SELECT count()
FROM s3('s3://clickhouse-public-datasets/hits.native.zst', Native)

Query id: ef149fbc-2085-4f79-9836-0cb0d53c9768


0 rows in set. Elapsed: 0.001 sec. 

Received exception:
Code: 42. DB::Exception: The signature of table function s3 could be the following:
 - url, format
 - url, format, structure
 - url, format, structure, compression_method
 - url, access_key_id, secret_access_key, format, structure
 - url, access_key_id, secret_access_key, format, structure, compression_method. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)
```

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix schema inference for table runction s3

Closes https://github.com/ClickHouse/ClickHouse/issues/34177

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

File: src/TableFunctions/TableFunctionS3.cpp [hunk 1]
```diff
@@ -29,9 +29,11 @@ void TableFunctionS3::parseArguments(const ASTPtr & ast_function, ContextPtr con
 
     const auto message = fmt::format(
         "The signature of table function {} could be the following:\n" \
+        " - url\n"
         " - url, format\n" \
         " - url, format, structure\n" \
         " - url, format, structure, compression_method\n" \
+        " - url, access_key_id, secret_access_key, format\n"
```
Comment (alexey-milovidov) [inline src/TableFunctions/TableFunctionS3.cpp:36]: And `url, access_key_id, secret_access_key`?

**Review by alexey-milovidov — APPROVED** [review]

File: src/TableFunctions/TableFunctionS3.cpp (hunk 1 above)
Comment (Avogar) [reply src/TableFunctions/TableFunctionS3.cpp:36]: Didn't support it, because we need to defferentiate it with `url, format, structure`, because both signatures have 3 arguments. But it's easy to do it, will implement it.

**Comment by alexey-milovidov** [comment]
@mergifyio update
