### PR TITLE
Fix potentially unsafe call in signal handler

### LINKED ISSUE #76548: Job stack traces reporting in signal handler is not safe.
### Company or project name

CH

### Describe the unexpected behaviour

Function `Exception::getThreadFramePointers()` returns copy of `std::vector<>` which calls to `operator new()` which is unsafe in signal handler:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/SignalHandlers.cpp#L118

Issue was introduced by #67173 and not fully fixed by #76191 and by #76446

### How to reproduce

was caught here:
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76363&sha=13bdda96a3451743d9f2fb5e6ba93b314b4376cb&name_0=PR&name_1=Integration+tests+%28tsan%2C+6%2F6%29&name_2=test_storage_s3_queue%2Ftest.py%3A%3Atest_upgrade_3

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix potentially unsafe call in signal handler.

closes #76548

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
cc @nickitat @antonio2368

File: src/Common/Exception.h [hunk 1]
```diff
@@ -96,6 +96,7 @@ class Exception : public Poco::Exception
         ThreadFramePointersBase frame_pointers;
     };
     static thread_local ThreadFramePointers thread_frame_pointers;
+    static ThreadFramePointersBase dummy_frame_pointers;
```
Comment (nickitat) [inline src/Common/Exception.h:99]: const?

Comment (yakov-olkhovskiy) [reply src/Common/Exception.h:99]: yeah... just doing it on the fly...

**Review by nikitamikhaylov — APPROVED** [review]
