### PR TITLE
getauxval: Avoid crash under sanitizer re-exec due to high ASLR entropy

### LINKED ISSUE #64086: TSan/MSan builds failures
### TSan

```
May 17 18:34:12 FAILED: contrib/arrow-cmake/orc_proto.pb.h contrib/arrow-cmake/orc_proto.pb.cc /build/build_docker/contrib/arrow-cmake/orc_proto.pb.h /build/build_docker/contrib/arrow-cmake/orc_proto.pb.cc 
May 17 18:34:12 cd /build/build_docker/contrib/arrow-cmake && /build/build_docker/contrib/google-protobuf-cmake/protoc -I /build/contrib/orc/c++/../proto --cpp_out="/build/build_docker/contrib/arrow-cmake" /build/contrib/orc/c++/../proto/orc_proto.proto
May 17 18:34:12 ThreadSanitizer: CHECK failed: tsan_platform_linux.cpp:282 "((personality(old_personality | ADDR_NO_RANDOMIZE))) != ((-1))" (0xffffffffffffffff, 0xffffffffffffffff) (tid=123304)
May 17 18:34:12 Segmentation fault (core dumped)
```

### MSan

```
May 17 18:31:34 [3061/12202] Generating orc_proto.pb.h, orc_proto.pb.cc
May 17 18:31:34 FAILED: contrib/arrow-cmake/orc_proto.pb.h contrib/arrow-cmake/orc_proto.pb.cc /build/build_docker/contrib/arrow-cmake/orc_proto.pb.h /build/build_docker/contrib/arrow-cmake/orc_proto.pb.cc 
May 17 18:31:34 cd /build/build_docker/contrib/arrow-cmake && /build/build_docker/contrib/google-protobuf-cmake/protoc -I /build/contrib/orc/c++/../proto --cpp_out="/build/build_docker/contrib/arrow-cmake" /build/contrib/orc/c++/../proto/orc_proto.proto
May 17 18:31:34 FATAL: Code 0x603049277240 is out of application range. Non-PIE build?
May 17 18:31:34 FATAL: MemorySanitizer can not mmap the shadow memory.
May 17 18:31:34 FATAL: Make sure to compile with -fPIE and to link with -pie.
May 17 18:31:34 FATAL: Disabling ASLR is known to cause this error.
May 17 18:31:34 FATAL: If running under GDB, try 'set disable-randomization off'.
May 17 18:31:34 ==110628==Process memory map follows:
May 17 18:31:34 	0x603049036000-0x60304925a000	/build/build_docker/contrib/google-protobuf-cmake/protoc
May 17 18:31:34 	0x60304925a000-0x60304a10a000	/build/build_docker/contrib/google-protobuf-cmake/protoc
May 17 18:31:34 	0x60304a10a000-0x60304a121000	/build/build_docker/contrib/google-protobuf-cmake/protoc
May 17 18:31:34 	0x60304a121000-0x60304a128000	/build/build_docker/contrib/google-protobuf-cmake/protoc
May 17 18:31:34 	0x60304a128000-0x60304bb14000	
May 17 18:31:34 	0x7e0b4d700000-0x7e0b4d800000	
May 17 18:31:34 	0x7e0b4d900000-0x7e0b4da00000	
May 17 18:31:34 	0x7e0b4db00000-0x7e0b4dc00000	
May 17 18:31:34 	0x7e0b4dd00000-0x7e0b4de00000	
May 17 18:31:34 	0x7e0b4dee3000-0x7e0b4e291000	
May 17 18:31:34 	0x7e0b4e291000-0x7e0b4e292000	/usr/lib/x86_64-linux-gnu/libdl.so.2
May 17 18:31:34 	0x7e0b4e292000-0x7e0b4e293000	/usr/lib/x86_64-linux-gnu/libdl.so.2
May 17 18:31:34 	0x7e0b4e293000-0x7e0b4e294000	/usr/lib/x86_64-linux-gnu/libdl.so.2
May 17 18:31:34 	0x7e0b4e294000-0x7e0b4e295000	/usr/lib/x86_64-linux-gnu/libdl.so.2
May 17 18:31:34 	0x7e0b4e295000-0x7e0b4e296000	/usr/lib/x86_64-linux-gnu/libdl.so.2
May 17 18:31:34 	0x7e0b4e296000-0x7e0b4e297000	/usr/lib/x86_64-linux-gnu/librt.so.1
May 17 18:31:34 	0x7e0b4e297000-0x7e0b4e298000	/usr/lib/x86_64-linux-gnu/librt.so.1
May 17 18:31:34 	0x7e0b4e298000-0x7e0b4e299000	/usr/lib/x86_64-linux-gnu/librt.so.1
May 17 18:31:34 	0x7e0b4e299000-0x7e0b4e29a000	/usr/lib/x86_64-linux-gnu/librt.so.1
May 17 18:31:34 	0x7e0b4e29a000-0x7e0b4e29b000	/usr/lib/x86_64-linux-gnu/librt.so.1
May 17 18:31:34 	0x7e0b4e29b000-0x7e0b4e2a9000	/usr/lib/x86_64-linux-gnu/libm.so.6
May 17 18:31:34 	0x7e0b4e2a9000-0x7e0b4e325000	/usr/lib/x86_64-linux-gnu/libm.so.6
May 17 18:31:34 	0x7e0b4e325000-0x7e0b4e380000	/usr/lib/x86_64-linux-gnu/libm.so.6
May 17 18:31:34 	0x7e0b4e380000-0x7e0b4e381000	/usr/lib/x86_64-linux-gnu/libm.so.6
May 17 18:31:34 	0x7e0b4e381000-0x7e0b4e382000	/usr/lib/x86_64-linux-gnu/libm.so.6
May 17 18:31:34 	0x7e0b4e382000-0x7e0b4e3aa000	/usr/lib/x86_64-linux-gnu/libc.so.6
May 17 18:31:34 	0x7e0b4e3aa000-0x7e0b4e53f000	/usr/lib/x86_64-linux-gnu/libc.so.6
May 17 18:31:34 	0x7e0b4e53f000-0x7e0b4e597000	/usr/lib/x86_64-linux-gnu/libc.so.6
May 17 18:31:34 	0x7e0b4e597000-0x7e0b4e598000	/usr/lib/x86_64-linux-gnu/libc.so.6
May 17 18:31:34 	0x7e0b4e598000-0x7e0b4e59c000	/usr/lib/x86_64-linux-gnu/libc.so.6
May 17 18:31:34 	0x7e0b4e59c000-0x7e0b4e59e000	/usr/lib/x86_64-linux-gnu/libc.so.6
May 17 18:31:34 	0x7e0b4e59e000-0x7e0b4e5ab000	
May 17 18:31:34 	0x7e0b4e5ab000-0x7e0b4e5ac000	/usr/lib/x86_64-linux-gnu/libpthread.so.0
May 17 18:31:34 	0x7e0b4e5ac000-0x7e0b4e5ad000	/usr/lib/x86_64-linux-gnu/libpthread.so.0
May 17 18:31:34 	0x7e0b4e5ad000-0x7e0b4e5ae000	/usr/lib/x86_64-linux-gnu/libpthread.so.0
May 17 18:31:34 	0x7e0b4e5ae000-0x7e0b4e5af000	/usr/lib/x86_64-linux-gnu/libpthread.so.0
May 17 18:31:34 	0x7e0b4e5af000-0x7e0b4e5b0000	/usr/lib/x86_64-linux-gnu/libpthread.so.0
May 17 18:31:34 	0x7e0b4e5b1000-0x7e0b4e5b7000	
May 17 18:31:34 	0x7e0b4e5b7000-0x7e0b4e5b9000	/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
May 17 18:31:34 	0x7e0b4e5b9000-0x7e0b4e5e3000	/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
May 17 18:31:34 	0x7e0b4e5e3000-0x7e0b4e5ee000	/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
May 17 18:31:34 	0x7e0b4e5ee000-0x7e0b4e5ef000	
May 17 18:31:34 	0x7e0b4e5ef000-0x7e0b4e5f1000	/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
May 17 18:31:34 	0x7e0b4e5f1000-0x7e0b4e5f3000	/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
May 17 18:31:34 	0x7ffd73396000-0x7ffd733b7000	[stack]
May 17 18:31:34 	0x7ffd733c1000-0x7ffd733c5000	[vvar]
May 17 18:31:34 	0x7ffd733c5000-0x7ffd733c7000	[vdso]
May 17 18:31:34 	0xffffffffff600000-0xffffffffff601000	[vsyscall]
May 17 18:31:34 ==110628==End of process memory map.
```

It looks like ASLR related, though not sure it pops up only now, maybe there was some changes on CI?

CI: https://s3.amazonaws.com/clickhouse-test-reports/64058/5ad98e88a254c6c9bc67af52b43702356d6c3950/clickhouse_build_check/report.html
Play: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSByZXBvcnRfdXJsIExJS0UgJyVjbGlja2hvdXNlX2J1aWxkX2NoZWNrJScKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMyBEQVkKICAgIGFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIGNoZWNrX3N0YXR1cyBub3QgaW4gKCdzdWNjZXNzJywgJ3BlbmRpbmcnKQpPUkRFUiBCWSBjaGVja19zdGFydF90aW1l

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- getauxval: Avoid crash under sanitizer re-exec due to high ASLR entropy

More detailed explanation in the code itself.

Closes https://github.com/ClickHouse/ClickHouse/issues/64086

Closes https://github.com/ClickHouse/ClickHouse/pull/67005 (Different alternative asking people of disable ASLR via cmake)
Closes https://github.com/ClickHouse/ClickHouse/pull/67073 (Don't use a custom getauxval for sanitizer builds)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit e4b50c18c2c1918905bf44a8e1183f0cddd5a811 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67081/e4b50c18c2c1918905bf44a8e1183f0cddd5a811/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67065/4ab4b6729224806e7d34f1bee91a21dcd1818e8f/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: base/glibc-compatibility/musl/getauxval.c [hunk 1]
```diff
@@ -75,6 +75,44 @@ unsigned long NO_SANITIZE_THREAD __getauxval_procfs(unsigned long type)
...
+    /// #7 0x73dc05dd7ea3 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:343:6
+    /// #8 0x5622c0d6b7cd in _start (./ClickHouse/build_msan/contrib/google-protobuf-cmake/protoc+0x22c7cd) (BuildId: 6411d3c88b898ba3f7d49760555977d3e61f0741)
+
+    /// The source of the issue above is that, at this point in time during __msan_init, we can't really do much as
+    /// most global variables aren't initialized or available yet, so we we can't initiate the auxiliary vector.
+    /// Normal glibc / musl getauxval doesn't have this problem since they initiate their auxval vector at the very
+    /// start of __libc_start_main (just keeping track of argv+argc+1), but we don't have such option (otherwise
+    // this complexity of reading "/proc/self/auxv" or using __environ would not be necessary).
+
+    /// To avoid this crashes on the re-exec call (see above how it would fail when creating `aux`, and it we used
```
Comment (davenger) [inline base/glibc-compatibility/musl/getauxval.c:107]:
```suggestion
    /// most global variables aren't initialized or available yet, so we can't initiate the auxiliary vector.
    /// Normal glibc / musl getauxval doesn't have this problem since they initiate their auxval vector at the very
    /// start of __libc_start_main (just keeping track of argv+argc+1), but we don't have such option (otherwise
    // this complexity of reading "/proc/self/auxv" or using __environ would not be necessary).

    /// To avoid this crashes on the re-exec call (see above how it would fail when creating `aux`, and if we used
```

**Comment by davenger** [comment]
The explanation sounds reasonable to me

**Review by davenger — APPROVED** [review]

**Comment by Algunenano** [comment]
GLIBC dependency is kept to 2.4:
```
objdump -T clickhouse_msan_patched | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -u
2.2.5
2.3
2.3.2
2.3.3
2.3.4
2.4
```
