### PR TITLE
Parse CRLF with TSV files

### LINKED ISSUE #56257: Add a setting to parse crlf with Tab separated CSV (TSV?!) files
Not sure if this is a feature or usability, so feel free to re-label. 

I have a tab separated file with windows line endings, which means it doesn't work correctly with any of the TSV formats. It will process with the CSV ones:

```
FROM file(
     'data/Stock Histories.zip :: {NASDAQ,NYSE}.txt', 
     CSVWithNames
)
SELECT *, _file
ORDER BY rand()
LIMIT 10;
```

But then every field is inside one row and I have to do a split on tab to separate them.

@alexey-milovidov said maybe we could add a setting:

> TSV does not have quoting, and escaping of \r is not mandatory, so the interpretation of crlf will be ambiguous if you have a binary string.
> We can add it under a setting…

### PR DESCRIPTION
**Pull request by Blargian**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
User can now parse CRLF with TSV format using a setting `input_format_tsv_crlf_end_of_line`. Closes #56257.

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

### Description of changes made
- added boolean setting called `input_format_tsv_crlf_end_of_line`
- added template parameter `bool support_crlf` to `readEscapedStringInto` and `readEscapedStringIntoImpl` as well as to `readTSVField`
- Rather than modifying `readEscapedString` I added a new function `readEscapedStringCRLF`, the reasoning behind this being that `readEscapedString` is used in many other places in the code base.
- Modified `readEscapedStringIntoImpl` to parse Fields correctly in the case that `support_crlf` is true.
- Modified `checkForCarriageReturn` and `skipRowEndDelimiter` so that exceptions are not thrown with crlf

I used the attached data set for testing and used `unix2dos data_small.tsv` and `dos2unix data_small.tsv` to convert back and forth between line ending types to test
https://gist.github.com/Blargian/0e36a74519d9c52ed0d0fba13ce5fc78

### CODE REVIEW

**Comment by Avogar** [comment]
I will take a look when I am back from vacation next week

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 3476d4f75321024340808a386d9723f232f30965 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59747/3476d4f75321024340808a386d9723f232f30965/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by Blargian** [comment]
@Avogar is there a way to check what is causing the A Sync check to fail? I don't see any logs or further details on this one when I follow the link from the robot-clickhouse comment - link seems broken.

**Comment by Avogar** [comment]
A Sync is a special internal check for developers, I will fix it, don't worry about it

File: src/IO/ReadHelpers.cpp [hunk 1]
```diff
@@ -530,25 +536,39 @@ void readEscapedStringIntoImpl(Vector & s, ReadBuffer & buf)
...
 
 void readEscapedString(String & s, ReadBuffer & buf)
 {
     s.clear();
-    readEscapedStringInto(s, buf);
+    readEscapedStringInto<String,false>(s, buf);
+}
+
+template<bool support_crlf>
+void readEscapedStringCRLF(String & s, ReadBuffer & buf)
```
Comment (Avogar) [inline src/IO/ReadHelpers.cpp:559]: I think `readEscapedStringCRLF` function should not be template and always use `support_crlf=true`. This function is supposed to be used only in cases when we need support for CRLF, in other cases `readEscapedString` function should be used

File: src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp [hunk 2]
```diff
@@ -22,9 +24,13 @@ namespace ErrorCodes
 
 /** Check for a common error case - usage of Windows line feed.
   */
+template<bool supports_crlf>
 static void checkForCarriageReturn(ReadBuffer & in)
```
Comment (Avogar) [inline src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp:28]: We just should not call this check if `format_settings.tsv.crlf_end_of_line_input`

Comment (Avogar) [reply src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp:28]: Also we can modify the exception message and say that the user can enable new setting to read such data

File: src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp [hunk 3]
```diff
@@ -89,30 +95,34 @@ void TabSeparatedFormatReader::skipFieldDelimiter()
...
 {
     String field;
+    bool support_crlf = format_settings.tsv.crlf_end_of_line_input;
     if (is_raw)
         readString(field, *buf);
     else
     {
         if constexpr (read_string)
-            readEscapedString(field, *buf);
+            support_crlf ? readEscapedStringCRLF<true>(field, *buf) : readEscapedStringCRLF<false>(field, *buf);
```
Comment (Avogar) [inline src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp:123]:
```suggestion
            support_crlf ? readEscapedStringCRLF(field, *buf) : readEscapedString(field, *buf);
```
Let's make `readEscapedStringCRLF` not template and use this

File: src/IO/ReadHelpers.h [hunk 4]
```diff
@@ -1895,6 +1898,7 @@ bool tryReadQuotedField(String & s, ReadBuffer & buf);
 void readJSONField(String & s, ReadBuffer & buf);
 bool tryReadJSONField(String & s, ReadBuffer & buf);
 
+template<bool support_crlf>
 void readTSVField(String & s, ReadBuffer & buf);
```
Comment (Avogar) [inline src/IO/ReadHelpers.h:1902]: Let's make 2 non-template functions `readTSVField` and `readTSVFieldCRLF` and make template `readTSVFieldImpl` implementation in .cpp file. It will look much better imho

File: src/DataTypes/Serializations/SerializationFixedString.cpp [hunk 5]
```diff
@@ -183,14 +185,17 @@ static inline bool tryRead(const SerializationFixedString & self, IColumn & colu
 }
 
 
-void SerializationFixedString::deserializeTextEscaped(IColumn & column, ReadBuffer & istr, const FormatSettings &) const
+void SerializationFixedString::deserializeTextEscaped(IColumn & column, ReadBuffer & istr, const FormatSettings & settings) const
```
Comment (Avogar) [inline src/DataTypes/Serializations/SerializationFixedString.cpp:188]: You should also check for all `deserializeTextEscaped` methods in all serializations, not only for String/FixedString, they all can use `readEscapedStringInto` or have own implementation relying only on  `\n` at the end

File: src/IO/ReadHelpers.cpp [hunk 6]
```diff
@@ -1955,10 +1982,26 @@ bool tryReadJSONField(String & s, ReadBuffer & buf)
...
 }
 
+template<bool supports_crlf>
+void readTSVFieldImpl(String & s, ReadBuffer & buf)
+{
+    if constexpr (supports_crlf)
+        readEscapedStringIntoImpl<String, false, false>(s, buf);
+    else
+        readEscapedStringIntoImpl<String, false, true>(s, buf);
+}
```
Comment (Avogar) [inline src/IO/ReadHelpers.cpp:1992]: Actually, as `readTSVFieldImpl` just calls coresponding `readEscapedStringIntoImpl` we can remove it and just use corresponding `readEscapedStringIntoImpl` in `readTSVField/readTSVFieldCRLF`.

File: src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp [hunk 7]
```diff
@@ -89,30 +92,35 @@ void TabSeparatedFormatReader::skipFieldDelimiter()
...
 void TabSeparatedFormatReader::skipRowEndDelimiter()
 {
+    bool supports_crlf = format_settings.tsv.crlf_end_of_line_input;
     if (buf->eof())
         return;
-
+    if (supports_crlf && first_row==false)
+    {
+        ++buf->position();
+    }
```
Comment (Avogar) [inline src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp:101]: We don't check that we actually have `\r` here. Better to do:
```c++
void TabSeparatedFormatReader::skipRowEndDelimiter()
{
    if (buf->eof())
        return;

    if (format_settings.tsv.crlf_end_of_line_input)
    {
        if (*buf.position == '\r')
            ++buf->position();
    }
    else if (unlikely(first_row))
    {
        checkForCarriageReturn(*buf);
        first_row = false;
    }

    assertChar('\n', *buf);
}
```

File: src/DataTypes/Serializations/SerializationFixedString.cpp (hunk 5 above)
Comment (Blargian) [reply src/DataTypes/Serializations/SerializationFixedString.cpp:188]: does that include serializations like `serializationBool`? I see it calls `deserializeTextEscaped` but with it's own implementation, without any calls to `readEscapedStringInto`.

https://github.com/ClickHouse/ClickHouse/blob/5d6bc6f566f09d1cd2ecf414bbb74222ffffa6bd/src/DataTypes/Serializations/SerializationBool.cpp#L241-L247

**Comment by Blargian** [comment]
@Avogar as an aside, I'm still trying to 100% understand serialization in ClickHouse on a conceptual level. I understand serialization as being about 'flattening' (maybe the wrong word) objects into streams of bits or characters so that they can be moved easier from one place to another. So these functions are all deserializing data from the `ReadBuffer` into columns. Does that mean that serialize functions will serialize data from Columns to `WriteBuffer` in the reverse process? (eg InputFormats would work with deserialize methods while OutputFormats would work with serialize?). 

- Is it only `ReadBuffer`/`WriteBuffer` where deserialization/serializing is happening, or to other objects too?

and lastly, formats seem to store serializations to index: https://github.com/ClickHouse/ClickHouse/blob/5d6bc6f566f09d1cd2ecf414bbb74222ffffa6bd/src/Processors/Formats/Impl/JSONEachRowRowInputFormat.cpp#L136
I haven't been able to yet figure out where the serializations for each index get added to this `serializations` array

File: src/DataTypes/Serializations/SerializationNullable.cpp [hunk 8]
```diff
@@ -319,13 +319,23 @@ ReturnType deserializeTextEscapedAndRawImpl(IColumn & column, ReadBuffer & istr,
...
+                buf.position() = pos;
+                return false;
+            }
+            else
+            {
+                if (checkString(null_representation, buf) && (*buf.position() == '\t' || *buf.position() == '\n'))
+                    return true;
+                buf.position() = pos;
+                return false;
+            }
```
Comment (Avogar) [inline src/DataTypes/Serializations/SerializationNullable.cpp:338]:
```suggestion
            if (checkString(null_representation, buf) && (*buf.position() == '\t' || *buf.position() == '\n' || (settings.tsv.crlf_end_of_line_input && *buf.position() == '\r')))
                return true;
            buf.position() = pos;
            return false;
```

File: src/DataTypes/Serializations/SerializationNullable.cpp [hunk 9]
```diff
@@ -319,13 +319,23 @@ ReturnType deserializeTextEscapedAndRawImpl(IColumn & column, ReadBuffer & istr,
     /// Check if we have enough data in buffer to check if it's a null.
     if (istr.available() > null_representation.size())
     {
-        auto check_for_null = [&null_representation](ReadBuffer & buf)
+        auto check_for_null = [&null_representation, settings](ReadBuffer & buf)
```
Comment (Avogar) [inline src/DataTypes/Serializations/SerializationNullable.cpp:322]:
```suggestion
        auto check_for_null = [&null_representation, &settings](ReadBuffer & buf)
```

File: src/DataTypes/Serializations/SerializationNullable.cpp [hunk 10]
```diff
@@ -334,14 +344,22 @@ ReturnType deserializeTextEscapedAndRawImpl(IColumn & column, ReadBuffer & istr,
     /// Use PeekableReadBuffer to make a checkpoint before checking null
     /// representation and rollback if check was failed.
     PeekableReadBuffer peekable_buf(istr, true);
-    auto check_for_null = [&null_representation](ReadBuffer & buf_)
+    auto check_for_null = [&null_representation, settings](ReadBuffer & buf_)
```
Comment (Avogar) [inline src/DataTypes/Serializations/SerializationNullable.cpp:347]:
```suggestion
    auto check_for_null = [&null_representation, &settings](ReadBuffer & buf_)
```

File: src/DataTypes/Serializations/SerializationNullable.cpp [hunk 11]
```diff
@@ -334,14 +344,22 @@ ReturnType deserializeTextEscapedAndRawImpl(IColumn & column, ReadBuffer & istr,
...
+        if (settings.tsv.crlf_end_of_line_input)
+        {
+            if (checkString(null_representation, buf) && (buf.eof() || *buf.position() == '\t' || *buf.position() == '\n' || *buf.position() == '\r'))
+                return true;
+        }
+        else
+        {
+            if (checkString(null_representation, buf) && (buf.eof() || *buf.position() == '\t' || *buf.position() == '\n'))
+                return true;
+        }
```
Comment (Avogar) [inline src/DataTypes/Serializations/SerializationNullable.cpp:362]:
```suggestion
        if (checkString(null_representation, buf) && (buf.eof() || *buf.position() == '\t' || *buf.position() == '\n' || (settings.tsv.crlf_end_of_line_input && *buf.position() == '\r')))
            return true;
```

File: src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp
Comment (Avogar) [inline src/Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp:1]: There are several places in this file where we need to add checks for `\r`:
`TabSeparatedFormatReader::readField` when we create `at_last_column_line_end`
`TabSeparatedFormatReader::parseFieldDelimiterWithDiagnosticInfo/parseRowEndWithDiagnosticInfo` when we check for end of row for better diagnositc info in case of errors
`TabSeparatedFormatReader::checkForEndOfRow()`

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Let's fix builds and merge it

**Comment by Blargian** [comment]
@Avogar I think we may have missed a less obvious one in `ParallelBlockInputFormat`. I can't reproduce the failing test locally exactly as it is on the server because of this line:

```
USER_FILES_PATH=$($CLICKHOUSE_CLIENT_BINARY --query "select _path,_file from file('nonexist.txt', 'CSV', 'val1 char')" 2>&1 | grep Exception | awk '{gsub("/nonexist.txt","",$9); print $9}')
```
but if I substitute it for my local user_files path then I get the following error:

```response
Code: 117. DB::Exception: Received from localhost:9000. DB::Exception: 
You have carriage return (\r, 0x0D, ASCII 13) at end of first row.
It's like your input data has DOS/Windows style line separators, that are illegal in TabSeparated format. You must transform your file to Unix format.
But if you really need carriage return at end of string value of last column, you need to escape it as \r.: (while reading header): (in file/uri /home/shaun/Desktop/ClickHouse/user_files/02973_parse_crlf_with_tsv_files_test_data_with_crlf.tsv): While executing ParallelParsingBlockInputFormat: While executing File. (INCORRECT_DATA)
(query: SELECT * FROM file(02973_parse_crlf_with_tsv_files_test_data_with_crlf.tsv, 'TabSeparated', 'SearchTerm String, Date Date, Hits UInt32') SETTINGS input_format_tsv_crlf_end_of_line = 1;)
```
so I assume this is the problem. Do you know where in `ParallelParsingInputFormat` we might be checking for `\n` - it's not immediately obvious to me when stepping through the code where this check takes place for this format.

**Comment by Blargian** [comment]
@Avogar sorry for the delay - fast tests is fixed now, seems like build-package-asan is failing on an LLVM out of memory issue:

```
Mar 08 23:09:11 1.	<eof> parser at end of file
Mar 08 23:09:11 2.	Code generation
Mar 08 23:09:11 LLVM ERROR: out of memory
Mar 08 23:09:11 Allocation failed
Mar 08 23:09:11 sccache: Compiler killed by signal 6
Mar 08 23:09:29 [10615/12724] Building CXX object src/CMakeFiles/dbms.dir/Columns/ColumnVector.cpp.o
Mar 08 23:09:29 ninja: build stopped: subcommand failed.
```

**Comment by Avogar** [comment]
I actually don't understand why build fails in file that wasn't changed in this PR... Let me as my colleagues

File: src/Formats/FormatSettings.h [hunk 12]
```diff
@@ -362,7 +362,8 @@ struct FormatSettings
         bool try_detect_header = true;
         bool skip_trailing_empty_lines = false;
         bool allow_variable_number_of_columns = false;
-    } tsv{};
+        bool crlf_end_of_line_input = false;
+    } tsv;
```
Comment (Avogar) [inline src/Formats/FormatSettings.h:366]:
```suggestion
    } tsv{};
```

Found the reason
