### PR TITLE
Fix parsing JSON/Dynamic/Variant values from HTTP parameters

### LINKED ISSUE #88925: JSON parameter binding infers different numeric types than JSON literal casting
### Company or project name

_No response_

### Describe what's wrong

When creating a JSON object from a query parameter, ClickHouse infers numeric types differently than when parsing the same JSON literal with ::Json. This causes semantically identical JSON objects to compare as unequal.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```
curl 'http://localhost:8123/?param_x=%7B%22a%22%3A1%7D'   -d "SELECT {x:Json} as j1, '{\"a\":1}'::Json as j2, j1 = j2 as equals, JSONAllPathsWithTypes(j1), JSONAllPathsWithTypes(j2)"
{"a":1}	{"a":1}	0	{'a':'Int8'}	{'a':'Int64'}
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix parsing JSON/Dynamic/Variant values from HTTP parameters. Resolves #88925

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/ReplaceQueryParameterVisitor.cpp [hunk 1]
```diff
@@ -129,9 +151,9 @@ void ReplaceQueryParameterVisitor::visitQueryParameter(ASTPtr & ast)
             value, type_name, ast_param.name, read_buffer.count(), value.size(), value.substr(0, read_buffer.count()));
 
     Field literal;
-    /// If data type has custom serialization, we should use CAST from String,
-    /// because CAST from field may not work correctly (for example for type IPv6).
-    if (data_type->getCustomSerialization())
+    /// For some data types we should use CAST from String,
+    /// because CAST from field may not work correctly (for example for type IPv6, JSON, Dynamic, etc).
+    if (needCastFromString(data_type))
```
Comment (alexey-milovidov) [inline src/Interpreters/ReplaceQueryParameterVisitor.cpp]: One question - if we will always cast from a string, what will be wrong?

**Review by alexey-milovidov — APPROVED** [review]

File: src/Interpreters/ReplaceQueryParameterVisitor.cpp (hunk 1 above)
Comment (Avogar) [reply src/Interpreters/ReplaceQueryParameterVisitor.cpp]: Also thought about it, let's change it to always cast from a string and check if any test will fail

**Comment by Avogar** [comment]
[Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90430&sha=23455e175493a16b4e08aabd15c204205497e9a7&name_0=PR&name_1=Stateless+tests+%28amd_binary%2C+old+analyzer%2C+s3+storage%2C+DatabaseReplicated%2C+parallel%29) - https://github.com/ClickHouse/ClickHouse/issues/91027
[Stateless tests (amd_tsan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90430&sha=23455e175493a16b4e08aabd15c204205497e9a7&name_0=PR&name_1=Stateless+tests+%28amd_tsan%2C+parallel%29) - https://github.com/ClickHouse/ClickHouse/issues/87583
[Integration tests (amd_asan, db disk, old analyzer, 6/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90430&sha=23455e175493a16b4e08aabd15c204205497e9a7&name_0=PR&name_1=Integration+tests+%28amd_asan%2C+db+disk%2C+old+analyzer%2C+6%2F6%29) - https://github.com/ClickHouse/ClickHouse/issues/90662
[Integration tests (arm_binary, distributed plan, 4/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90430&sha=23455e175493a16b4e08aabd15c204205497e9a7&name_0=PR&name_1=Integration+tests+%28arm_binary%2C+distributed+plan%2C+4%2F4%29) - https://github.com/ClickHouse/ClickHouse/issues/91028
[Integration tests (amd_tsan, 2/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90430&sha=23455e175493a16b4e08aabd15c204205497e9a7&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+2%2F6%29) - https://github.com/ClickHouse/ClickHouse/issues/88931

**Comment by clickgapai** [comment]
Hi @Avogar @alexey-milovidov — while reviewing this PR I found the following:

- **Bug (P2):** needCastFromString routes Map-containing-Dynamic/Variant/Object params through unsupported CAST-from-String, throwing TYPE_MISMATCH on previously-working queries — https://github.com/ClickHouse/ClickHouse/issues/109662

Happy to discuss — close anything that's wrong or already addressed.
