### PR TITLE
Reload certificate chain during certificate reload

### LINKED ISSUE #47734: Hot reload ssl cert with different issuer
Hi! I'm using Ubuntu 20.04.4 LTS, Clickhouse 23.1.3 revision 54461.
I encountered
```
2023.03.15 08:54:43.412456 [ 67614 ] {} <Error> ServerErrorHandler: Code: 210. DB::NetException: SSL Exception: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE, while reading from socket ([::ffff:xxx.xxx.xxx.xxx]:58520). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xddb0df5 in /usr/bin/clickhouse
1. ? @ 0x132aff9e in /usr/bin/clickhouse
2. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x132afbbc in /usr/bin/clickhouse
3. DB::HTTPServerRequest::readRequest(DB::ReadBuffer&) @ 0x14696890 in /usr/bin/clickhouse
4. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x14695f9e in /usr/bin/clickhouse
5. DB::HTTPServerConnection::run() @ 0x1469486f in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1753e2f4 in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x1753fc9b in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x176cf0a7 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x176ccadd in /usr/bin/clickhouse
10. ? @ 0x7f858ba4c609 in ?
11. __clone @ 0x7f858b971133 in ?
--
2023.03.15 09:14:41.449816 [ 153386 ] {} <Error> ServerErrorHandler: Code: 210. DB::NetException: SSL Exception: error:10000418:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNKNOWN_CA, while reading from socket ([::ffff:xxx.xxx.xxx.xxx]:50898). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xddb0df5 in /usr/bin/clickhouse
1. ? @ 0x132aff9e in /usr/bin/clickhouse
2. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x132afbbc in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0x14676238 in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0x1468b8d9 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x1753e2f4 in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x1753fc9b in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x176cf0a7 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x176ccadd in /usr/bin/clickhouse
9. ? @ 0x7f858ba4c609 in ?
10. __clone @ 0x7f858b971133 in ?
 (version 23.1.3.5 (official build))
```
when all 3 blocks 
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
inside the file `<certificateFile>` changed (instead of signing a cert that'd expire later, we changed the issuer).  
I'd need to restart clickhouse to make ports using SSL work again.  

relates to https://github.com/ClickHouse/ClickHouse/issues/15764

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reload certificate chain during certificate reload

Fixes #47734

### CODE REVIEW

File: src/Server/CertificateReloader.cpp [hunk 1]
```diff
@@ -30,8 +30,22 @@ int CertificateReloader::setCertificate(SSL * ssl)
...
+    ret = SSL_clear_chain_certs(ssl);
+    if (!ret)
+        return ret;
+    ret = SSL_use_certificate(ssl, const_cast<X509 *>(current->certs_chain[0].certificate()));
+    if (!ret)
+        return ret;
+    for (auto cert = current->certs_chain.begin() + 1; cert != current->certs_chain.end(); cert++) {
+        ret = SSL_add1_chain_cert(ssl, const_cast<X509 *>(cert->certificate()));
+        if (!ret)
+        return ret;
```
Comment (nickitat) [inline src/Server/CertificateReloader.cpp:46]:
```suggestion
            return ret;
```

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 89e42f3e434dc78e506bb28f9ab3f0b24705e506 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61671/89e42f3e434dc78e506bb28f9ab3f0b24705e506/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

File: src/Server/CertificateReloader.cpp [hunk 2]
```diff
@@ -23,24 +23,39 @@ int callSetCertificate(SSL * ssl, [[maybe_unused]] void * arg)
 }
 
 
+#define LOG_ERROR_RETURN(err, msg) do                             \
```
Comment (nickitat) [inline src/Server/CertificateReloader.cpp:26]: macros are not cool. consider this syntax e.g.

``` cpp
if (auto err = foo(); err != 1)
{
    LOG_ERROR(...);
    return -1;
}
```

**Review by nickitat — APPROVED** [review]
