### PR TITLE
Fix cache related logical error in stress tests

### LINKED ISSUE #53009: Logical error: Operation `completePartAndResetDownloader` can be done only by downloader
https://s3.amazonaws.com/clickhouse-test-reports/52956/141a3df727dba39c20546141e57c3c202c5c9d2b/stress_test__msan_.html

```
 [ 2327 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Fatal> : Logical error: \'Operation `completePartAndResetDownloader` can be done only by downloader. (CallerId: None:2327, downloader id: 85955690-c5dd-4e15-a182-8a8b7ddb4248:2327)\'.
 [ 1741 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 2327 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Fatal> : Logical error: \'Operation `completePartAndResetDownloader` can be done only by downloader. (CallerId: None:2327, downloader id: 85955690-c5dd-4e15-a182-8a8b7ddb4248:2327)\'.
 [ 1741 ] {} <Fatal> Application: Child process was terminated by signal 6.

2023-08-03 15:42:39 Thread 449 "LoadMarksThread" received signal SIGABRT, Aborted.
2023-08-03 15:42:39 [Switching to Thread 0x7fac1e35e640 (LWP 2327)]
2023-08-03 15:42:39 0x00007faed7900a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2023-08-03 15:42:39 #0  0x00007faed7900a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2023-08-03 15:42:39 No symbol table info available.
2023-08-03 15:42:39 #1  0x00007faed78ac476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2023-08-03 15:42:40 No symbol table info available.
2023-08-03 15:42:40 #2  0x00007faed78927f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2023-08-03 15:42:40 No symbol table info available.
2023-08-03 15:42:40 #3  0x0000555d28535c2a in DB::abortOnFailedAssertion (description=...) at ./src/Common/Exception.cpp:50
2023-08-03 15:42:40         always_false = false
2023-08-03 15:42:40 #4  0x0000555d28536c60 in DB::handle_error_code (msg=..., code=49, trace=..., remote=<optimized out>) at ./src/Common/Exception.cpp:62
2023-08-03 15:42:40 No locals.
2023-08-03 15:42:40 #5  DB::Exception::Exception (this=0x714000670080, msg_masked=..., code=49, remote_=<optimized out>) at ./src/Common/Exception.cpp:96
2023-08-03 15:42:40 No locals.
2023-08-03 15:42:40 #6  0x0000555d4231e35e in DB::Exception::Exception (this=0x714000670080, msg=..., code=49, remote_=false) at ./src/Common/Exception.h:63
2023-08-03 15:42:40 No locals.
2023-08-03 15:42:40 #7  DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> (this=this@entry=0x714000670080, code=49, fmt=..., args=..., args=..., args=...) at ./src/Common/Exception.h:91
2023-08-03 15:42:40 No locals.
2023-08-03 15:42:40 #8  0x0000555d42308201 in DB::FileSegment::assertIsDownloaderUnlocked (this=this@entry=0x7120008b5198, operation=..., lock=...) at ./src/Interpreters/Cache/FileSegment.cpp:275
2023-08-03 15:42:40         caller = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x3233323a656e6f4e <error: Cannot access memory at address 0x3233323a656e6f4e>, __size_ = 55, __cap_ = 648612204529876501, __is_long_ = 0}, __s = {__data_ = "None:2327\000\000\000\000\000\000\000\025~\374\017]U", __padding_ = 0x7fac1e353a2f "\tH:5\036\254/", __size_ = 9 '\t', __is_long_ = 0 '\000'}, __r = {__words = {3617290152099868494, 55, 648612204529876501}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}
2023-08-03 15:42:40         current_downloader = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x703001a32890 "85955690-c5dd-4e15-a182-8a8b7ddb4248:2327", __size_ = 41, __cap_ = 48, __is_long_ = 1}, __s = {__data_ = "\220(\243\001\060p\000\000)\000\000\000\000\000\000\000\060\000\000\000\000\000", __padding_ = 0x7fac1e353a5f "\200\250", <incomplete sequence \307>, __size_ = 0 '\000', __is_long_ = 1 '\001'}, __r = {__words = {123351488211088, 41, 9223372036854775856}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}
2023-08-03 15:42:40 #9  0x0000555d4231344f in DB::FileSegment::completePartAndResetDownloader (this=0x7120008b5198) at ./src/Interpreters/Cache/FileSegment.cpp:578
2023-08-03 15:42:41         lock = {<std::__1::unique_lock<std::__1::mutex>> = {__m_ = 0x7120008b5230, __owns_ = true}, <No data fields>}
2023-08-03 15:42:41         scope_exit575 = {static is_nullable = <optimized out>, function = {this = 0x7120008b5198}}
2023-08-03 15:42:41 #10 0x0000555d3cf8e7e8 in DB::CachedOnDiskReadBufferFromFile::nextImplStep (this=0x7160006d0818) at ./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:1068
2023-08-03 15:42:45         scope_exit842 = {static is_nullable = <optimized out>, function = {this = 0x7160006d0818, implementation_buffer_can_be_reused = @0x7fac1e35424f, original_buffer_size = @0x7fac1e353e48}}
2023-08-03 15:42:45         original_buffer_size = <optimized out>
2023-08-03 15:42:45         implementation_buffer_can_be_reused = <optimized out>
2023-08-03 15:42:45         file_segment = @0x7120008b5198: {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, file_key = {key = {items = {4484006320064497688, 7459527825102855961}}}, segment_range = {left = 0, right = 50}, segment_kind = DB::FileSegmentKind::Regular, is_unbound = false, download_state = {<std::__1::__atomic_base<DB::FileSegment::State, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<DB::FileSegment::State>> = {__a_value = DB::FileSegment::State::DOWNLOADING}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, downloader_id = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x703001b19dd0 "85955690-c5dd-4e15-a182-8a8b7ddb4248:2327", __size_ = 41, __cap_ = 48, __is_long_ = 1}, __s = {__data_ = "Н\261\001\060p\000\000)\000\000\000\000\000\000\000\060\000\000\000\000\000", __padding_ = 0x7120008b51df "\200", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __r = {__words = {123351489158608, 41, 9223372036854775856}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, remote_file_reader = {__ptr_ = 0x71a0005e2000, __cntrl_ = 0x702000573d40}, cache_writer = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::WriteBufferFromFile*, 0, false>> = {__value_ = 0x70a000915640}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::WriteBufferFromFile>, 1, true>> = {<std::__1::default_delete<DB::WriteBufferFromFile>> = {<No data fields>}, <No data fields>}, <No data fields>}}, downloaded_size = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 51}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, reserved_size = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 51}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, download_mutex = {__m_ = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, segment_guard = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, mutex = {__m_ = {__data = {__lock = 1, __count = 0, __owner = 2327, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = "\001\000\000\000\000\000\000\000\027\t\000\000\001", '\000' <repeats 26 times>, __align = 1}}}, key_metadata = {__ptr_ = 0x70c0004e9558, __cntrl_ = 0x70c0004e9540}, queue_iterator = {__ptr_ = 0x70300116a2b8, __cntrl_ = 0x70300116a2a0}, cache = 0x7120001dc598, cv = {__cv_ = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}}, log = 0x7040019fdc40, hits_count = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, ref_count = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, metric_increment = {what = 0x555d5d7aaf88 <CurrentMetrics::values+1480>, amount = 1}}
2023-08-03 15:42:45         current_read_range = <optimized out>
2023-08-03 15:42:45         result = <optimized out>
2023-08-03 15:42:45         size = 51
2023-08-03 15:42:45         needed_to_predownload = 0
2023-08-03 15:42:45         download_current_segment = <optimized out>
2023-08-03 15:42:45 #11 0x0000555d3cf88253 in DB::CachedOnDiskReadBufferFromFile::nextImpl (this=0x6ce) at ./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:784
2023-08-03 15:42:45         e = <optimized out>
2023-08-03 15:42:45 #12 0x0000555d3cf692d2 in DB::ReadBuffer::next (this=<optimized out>) at ./src/IO/ReadBuffer.h:71
2023-08-03 15:42:45         res = <optimized out>
2023-08-03 15:42:45 #13 DB::ReadBufferFromRemoteFSGather::readImpl (this=this@entry=0x715000950380) at ./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:224
2023-08-03 15:42:46         swap = {b1 = @0x715000950388, b2 = @0x7160006d0820}
2023-08-03 15:42:46         result = <optimized out>
2023-08-03 15:42:46 #14 0x0000555d3cf6743a in DB::ReadBufferFromRemoteFSGather::nextImpl (this=0x715000950380) at ./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:180
2023-08-03 15:42:46 No locals.
2023-08-03 15:42:46 #15 DB::ReadBufferFromRemoteFSGather::readInto (this=0x715000950380, data=<optimized out>, size=<optimized out>, offset=<optimized out>, ignore=<optimized out>) at ./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:131
2023-08-03 15:42:46         result = <optimized out>
2023-08-03 15:42:46 #16 0x0000555d3cf60402 in DB::AsynchronousBoundedReadBuffer::nextImpl (this=0x715000950600) at ./src/Disks/IO/AsynchronousBoundedReadBuffer.cpp:188
2023-08-03 15:42:46         watch = {event = {t = 379}, watch = {start_ns = 16818720974517, stop_ns = 0, clock_type = 1, is_running = true}}
2023-08-03 15:42:46         size = <optimized out>
2023-08-03 15:42:46         offset = <optimized out>
2023-08-03 15:42:46         bytes_read = <optimized out>
2023-08-03 15:42:46 #17 0x0000555d3e17ec65 in DB::ReadBuffer::next (this=0x715000950600) at ./src/IO/ReadBuffer.h:71
2023-08-03 15:42:46         res = <optimized out>
2023-08-03 15:42:46 #18 DB::ReadBuffer::eof (this=0x715000950600) at ./src/IO/ReadBuffer.h:105
2023-08-03 15:42:46 No locals.
2023-08-03 15:42:46 #19 DB::CompressedReadBufferBase::readCompressedData (this=0x70d000356a60, size_decompressed=@0x7fac1e354750: 0, size_compressed_without_checksum=@0x7fac1e354708: 32, always_copy=false) at ./src/Compression/CompressedReadBufferBase.cpp:159
2023-08-03 15:42:46         header_size = <optimized out>
2023-08-03 15:42:46         additional_size_at_the_end_of_buffer = <optimized out>
2023-08-03 15:42:46 #20 0x0000555d3e1859f7 in DB::CompressedReadBufferFromFile::nextImpl (this=0x70d000356a60) at ./src/Compression/CompressedReadBufferFromFile.cpp:22
2023-08-03 15:42:46         size_decompressed = 0
2023-08-03 15:42:46         size_compressed_without_checksum = 32
2023-08-03 15:42:46         additional_size_at_the_end_of_buffer = <optimized out>
2023-08-03 15:42:46 #21 0x0000555d3e185f8d in non-virtual thunk to DB::CompressedReadBufferFromFile::nextImpl() ()
2023-08-03 15:42:46         MALLOC_MIN_ALIGNMENT = 8
2023-08-03 15:42:46         std::__1::memory_order_relaxed = std::__1::memory_order::relaxed
2023-08-03 15:42:46         max_int_width = 20
2023-08-03 15:42:46         fmt::v8::detail::invalid_code_point = 4294967295
2023-08-03 15:42:46         impl::digits = "00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899"
2023-08-03 15:42:46         boost::optional_ns::in_place_init = <optimized out>
2023-08-03 15:42:46         boost::optional_ns::in_place_init_if = <optimized out>
2023-08-03 15:42:46         fmt::v8::align::right = fmt::v8::align::right
2023-08-03 15:42:46         std::__1::__mo_acquire = std::__1::__mo_acquire
2023-08-03 15:42:46         std::__1::__libcpp_numeric_limits<unsigned long, true>::__max = 18446744073709551615
2023-08-03 15:42:46         std::__1::__libcpp_numeric_limits<long, true>::__max = 9223372036854775807
2023-08-03 15:42:46         std::__1::__libcpp_numeric_limits<int, true>::__max = 2147483647
2023-08-03 15:42:46         std::__1::__libcpp_numeric_limits<char, true>::__max = 127 '\177'
2023-08-03 15:42:46         fmt::v8::detail::float_format::general = fmt::v8::detail::float_format::general
2023-08-03 15:42:46         std::__1::round_indeterminate = std::__1::round_indeterminate
...
2023-08-03 15:42:46 #22 0x0000555d44ccc844 in DB::ReadBuffer::next (this=<optimized out>) at ./src/IO/ReadBuffer.h:71
2023-08-03 15:42:46         res = <optimized out>
2023-08-03 15:42:46 #23 DB::ReadBuffer::eof (this=<optimized out>) at ./src/IO/ReadBuffer.h:105
2023-08-03 15:42:46 No locals.
2023-08-03 15:42:46 #24 DB::MergeTreeMarksLoader::loadMarksImpl (this=this@entry=0x7170029fe960) at ./src/Storages/MergeTree/MergeTreeMarksLoader.cpp:154
2023-08-03 15:42:53         granularity = <optimized out>
2023-08-03 15:42:53         i = <optimized out>
2023-08-03 15:42:53         temporarily_disable_memory_tracker = {static counter = 1, static level = VariableContext::User, previous_level = VariableContext::Global}
2023-08-03 15:42:53         data_part_storage = {__ptr_ = 0x708000a56a98, __cntrl_ = 0x708000a56a80}
2023-08-03 15:42:53         plain_marks = {<DB::PODArrayBase<16ul, 4096ul, Allocator<false, false>, 0ul, 0ul>> = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, <Allocator<false, false>> = {static clear_memory = false, static mmap_flags = 34}, static pad_right = <optimized out>, static pad_left = 0, static null = <optimized out>, c_start = 0x7020002130c0 "/var/lib/clickhouse/disks/s3/", c_end = 0x7020002130e0 "ProfileEvent_KeeperListRequest", c_end_of_storage = 0x7020002130e0 "ProfileEvent_KeeperListRequest"}, <No data fields>}
2023-08-03 15:42:53         buffer = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::ReadBufferFromFileBase*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::ReadBufferFromFileBase>, 1, true>> = {<std::__1::default_delete<DB::ReadBufferFromFileBase>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2023-08-03 15:42:53         reader = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::ReadBuffer*, 0, false>> = {__value_ = 0x70d000356aa8}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::ReadBuffer>, 1, true>> = {<std::__1::default_delete<DB::ReadBuffer>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2023-08-03 15:42:53         mark_size = <optimized out>
2023-08-03 15:42:53         expected_uncompressed_size = <optimized out>
2023-08-03 15:42:53         file_size = <optimized out>
2023-08-03 15:42:53         res = <optimized out>
2023-08-03 15:42:53 #25 0x0000555d44cc9b7d in DB::MergeTreeMarksLoader::loadMarks()::$_0::operator()() const (this=<optimized out>) at ./src/Storages/MergeTree/MergeTreeMarksLoader.cpp:192
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #26 DB::CacheBase<wide::integer<128ul, unsigned int>, DB::MarksInCompressedFile, UInt128TrivialHash, DB::MarksWeightFunction>::getOrSet<DB::MergeTreeMarksLoader::loadMarks()::$_0&>(wide::integer<128ul, unsigned int> const&, DB::MergeTreeMarksLoader::loadMarks()::$_0&) (this=0x709000014c88, key=..., load_func=...) at ./src/Common/CacheBase.h:148
2023-08-03 15:42:55         token_holder = {key = 0x7fac1e354c10, token = {__ptr_ = 0x70700146a378, __cntrl_ = 0x70700146a360}, cleaned_up = false}
2023-08-03 15:42:55         token_lock = {__m_ = @0x70700146a378}
2023-08-03 15:42:55         cache_lock = {__m_ = @0x0}
2023-08-03 15:42:55         token = 0x70700146a378
2023-08-03 15:42:55         result = <optimized out>
2023-08-03 15:42:55         token_it = <optimized out>
2023-08-03 15:42:55         cache_lock = <optimized out>
2023-08-03 15:42:55         val = <optimized out>
2023-08-03 15:42:55         token = <optimized out>
2023-08-03 15:42:55 #27 DB::MarkCache::getOrSet<DB::MergeTreeMarksLoader::loadMarks()::$_0&>(wide::integer<128ul, unsigned int> const&, DB::MergeTreeMarksLoader::loadMarks()::$_0&) (this=0x709000014c88, key=..., load=...) at ./src/Storages/MarkCache.h:65
2023-08-03 15:42:55         result = {first = {__ptr_ = 0x706000ef0dc0, __cntrl_ = 0x56}, second = 96}
2023-08-03 15:42:55 #28 DB::MergeTreeMarksLoader::loadMarks (this=this@entry=0x7170029fe960) at ./src/Storages/MergeTree/MergeTreeMarksLoader.cpp:193
2023-08-03 15:42:55         callback = {this = 0x7170029fe960}
2023-08-03 15:42:55         key = {items = {14881488857485163021, 2030030253964066468}}
2023-08-03 15:42:55         data_part_storage = {__ptr_ = 0x708000a56a98, __cntrl_ = 0x708000a56a80}
2023-08-03 15:42:55         loaded_marks = <optimized out>
2023-08-03 15:42:55 #29 0x0000555d44cd0e42 in DB::MergeTreeMarksLoader::loadMarksAsync()::$_0::operator()() const (this=<optimized out>) at ./src/Storages/MergeTree/MergeTreeMarksLoader.cpp:220
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #30 DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#1}::operator()() (this=<optimized out>) at ./src/Interpreters/threadPoolCallbackRunner.h:42
2023-08-03 15:42:55         scope_exit38 = {static is_nullable = false, function = {<No data fields>}}
2023-08-03 15:42:55 #31 std::__1::__invoke[abi:v15000]<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#1}&>(DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#1}&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #32 std::__1::__packaged_task_func<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#1}, std::__1::allocator<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#1}>, std::__1::shared_ptr<DB::MarksInCompressedFile> ()>::operator()() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/future:1694
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #33 0x0000555d44cd82e1 in std::__1::__packaged_task_function<std::__1::shared_ptr<DB::MarksInCompressedFile> ()>::operator()() const (this=0x706000834620) at ./contrib/llvm-project/libcxx/include/future:1876
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #34 std::__1::packaged_task<std::__1::shared_ptr<DB::MarksInCompressedFile> ()>::operator()() (this=0x706000834620) at ./contrib/llvm-project/libcxx/include/future:1953
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #35 0x0000555d44cd116e in DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}::operator()() const (this=<optimized out>) at ./src/Interpreters/threadPoolCallbackRunner.h:50
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #36 std::__1::__invoke[abi:v15000]<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}&>(DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #37 std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}&>(DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}&) (__args=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #38 std::__1::__function::__default_alloc_func<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}, void ()>::operator()[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #39 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
2023-08-03 15:42:55         __f = 0x7faed7900a7c <pthread_kill+300>
2023-08-03 15:42:55 #40 0x0000555d2886bab3 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7fac1e355138) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #41 std::__1::function<void ()>::operator()() const (this=0x7fac1e355138) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
2023-08-03 15:42:55 No locals.
2023-08-03 15:42:55 #42 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker (this=this@entry=0x7110002d0000, thread_it=thread_it@entry=...) at ./src/Common/ThreadPool.cpp:427
2023-08-03 15:42:56         metric_active_pool_threads = {what = 0x555d5d7aac28 <CurrentMetrics::values+616>, amount = 1}
2023-08-03 15:42:56         parent_thread_trace_context = {<DB::OpenTelemetry::TracingContext> = {trace_id = {t = {items = {0, 0}}}, span_id = 0, tracestate = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fac1e355087 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, trace_flags = 0 '\000'}, span_log = {__ptr_ = 0x0, __cntrl_ = 0x0}}
2023-08-03 15:42:56         thread_frame_pointers = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2023-08-03 15:42:56         job = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "\220,R\000\020p\000\000\214$\251E]U\000", __large = 0x701000522c90}, __invoker_ = {__call_ = 0x555d44cd1140 <std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}, void ()> >(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x555d5b744b90 <std::__1::__function::__policy::__choose_policy[abi:v15000]<std::__1::__function::__default_alloc_func<DB::threadPoolCallbackRunner<std::__1::shared_ptr<DB::MarksInCompressedFile>, DB::MergeTreeMarksLoader::loadMarksAsync()::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::{lambda(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)#1}::operator()(DB::MergeTreeMarksLoader::loadMarksAsync()::$_0&&, Priority)::{lambda()#2}, void ()> >(std::__1::integral_constant<bool, false>)::__policy_>}}
2023-08-03 15:42:56         thread_trace_context = {root_span = {trace_id = {t = {items = {0, 0}}}, span_id = 0, parent_span_id = 0, operation_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fac1e354f57 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, start_time_us = 0, finish_time_us = 0, kind = DB::OpenTelemetry::INTERNAL, attributes = {<std::__1::vector<DB::Field, AllocatorWithMemoryTracking<DB::Field> >> = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::Field*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<AllocatorWithMemoryTracking<DB::Field>, 1, true>> = {<AllocatorWithMemoryTracking<DB::Field>> = {<No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}}, is_context_owner = true}
2023-08-03 15:42:56         metric_pool_threads = {what = 0x555d5d7aac20 <CurrentMetrics::values+608>, amount = 1}
2023-08-03 15:42:56         exception_from_job = {__ptr_ = 0x0}
2023-08-03 15:42:56         job_is_done = false
2023-08-03 15:42:56 #43 0x0000555d28877893 in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=<optimized out>) at ./src/Common/ThreadPool.cpp:180
2023-08-03 15:42:56 No locals.
2023-08-03 15:42:56 #44 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-08-03 15:42:56 No locals.
2023-08-03 15:42:56 #45 std::__1::__apply_tuple_impl[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1789
2023-08-03 15:42:56 No locals.
2023-08-03 15:42:56 #46 std::__1::apply[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1798
2023-08-03 15:42:56 No locals.
2023-08-03 15:42:56 #47 ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}::operator()() (this=<optimized out>) at ./src/Common/ThreadPool.h:242
2023-08-03 15:43:03         scope_exit230 = {static is_nullable = false, function = {my_state = @0x7030004c2b70}}...
2023-08-03 15:43:07         function = {this = 0x7110002d0000, it = {__ptr_ = 0x7020002716c0}}
2023-08-03 15:43:07         arguments = <optimized out>
2023-08-03 15:43:07 #48 0x0000555d2887773f in std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #49 std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}&) (__args=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #50 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}, void ()>::operator()[abi:v15000]() (this=0x6ce) at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #51 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
2023-08-03 15:43:07         __f = 0x6ce
2023-08-03 15:43:07 #52 0x0000555d288624bb in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7fac1e355758) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #53 std::__1::function<void ()>::operator()() const (this=0x7fac1e355758) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #54 ThreadPoolImpl<std::__1::thread>::worker (this=0x7110000049c0, thread_it=...) at ./src/Common/ThreadPool.cpp:427
2023-08-03 15:43:07         metric_active_pool_threads = {what = 0x555d5d7aabd8 <CurrentMetrics::values+536>, amount = 1}
2023-08-03 15:43:07         parent_thread_trace_context = {<DB::OpenTelemetry::TracingContext> = {trace_id = {t = {items = {0, 0}}}, span_id = 0, tracestate = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fac1e3556bf "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, trace_flags = 0 '\000'}, span_log = {__ptr_ = 0x0, __cntrl_ = 0x0}}
2023-08-03 15:43:07         thread_frame_pointers = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2023-08-03 15:43:07         job = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "p+L\000\060p\000\000\251&\254E]U\000", __large = 0x7030004c2b70}, __invoker_ = {__call_ = 0x555d28877720 <std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x555d5b232fa8 <std::__1::__function::__policy::__choose_policy[abi:v15000]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}, void ()> >(std::__1::integral_constant<bool, false>)::__policy_>}}
2023-08-03 15:43:07         thread_trace_context = {root_span = {trace_id = {t = {items = {0, 0}}}, span_id = 0, parent_span_id = 0, operation_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7fac1e355587 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, start_time_us = 0, finish_time_us = 0, kind = DB::OpenTelemetry::INTERNAL, attributes = {<std::__1::vector<DB::Field, AllocatorWithMemoryTracking<DB::Field> >> = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::Field*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<AllocatorWithMemoryTracking<DB::Field>, 1, true>> = {<AllocatorWithMemoryTracking<DB::Field>> = {<No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}}, is_context_owner = true}
2023-08-03 15:43:07         metric_pool_threads = {what = 0x555d5d7aabd0 <CurrentMetrics::values+528>, amount = 1}
2023-08-03 15:43:07         exception_from_job = {__ptr_ = 0x0}
2023-08-03 15:43:07         job_is_done = false
2023-08-03 15:43:07 #55 0x0000555d288710cb in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=<optimized out>) at ./src/Common/ThreadPool.cpp:180
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #56 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #57 std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at ./contrib/llvm-project/libcxx/include/thread:284
2023-08-03 15:43:07 No locals.
2023-08-03 15:43:07 #58 std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(void*) (__vp=0x702000244d20) at ./contrib/llvm-project/libcxx/include/thread:295
2023-08-03 15:43:07         __p = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ./src/Common/ThreadPool.cpp:180:42)> *, 0, false>> = {__value_ = 0x702000244d20}, <std::__1::__compressed_pair_elem<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ./src/Common/ThreadPool.cpp:180:42)> >, 1, true>> = {<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ./src/Common/ThreadPool.cpp:180:42)> >> = {<No data fields>}, <No data fields>}, <No data fields>}}
2023-08-03 15:43:07 #59 0x00007faed78feb43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-08-03 15:43:07 No symbol table info available.
2023-08-03 15:43:07 #60 0x00007faed7990a00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2023-08-03 15:43:07 No symbol table info available.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes logical error "Operation completePartAndResetDownloader can be done only by downloader".
Closes https://github.com/ClickHouse/ClickHouse/issues/53009.

The error happens because query context expires after query received and error, but `MergeTreeMarkLoader` was still active because it was asynchronously started and was not destroyed before query context expires, but cache was checking for `CurrentThread::getQueryContext() != nullptr`:
```
2023.08.03 15:42:38.458269 [ 2501 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Debug> executeQuery: (from [::1]:45546) (comment: 01018_ddl_dictionaries_concurrent_requrests.sh) SELECT * FROM database_for_dict.dict1 FORMAT Null; (stage: Complete)
2023.08.03 15:42:38.879561 [ 2501 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Error> executeQuery: Code: 36. DB::Exception: external dictionary '9eb3cbff-87f8-44df-b8b1-e4c630182ead' not found. (BAD_ARGUMENTS) (version 23.8.1.1) (from [::1]:45546) (comment: 01018_ddl_dictionaries_concurrent_requrests.sh) (in query: SELECT * FROM database_for_dict.dict1 FORMAT Null;), Stack trace (when copying this message, always include the lines below):
2023.08.03 15:42:38.886933 [ 2501 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Error> TCPHandler: Code: 36. DB::Exception: external dictionary '9eb3cbff-87f8-44df-b8b1-e4c630182ead' not found. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):
2023.08.03 15:42:38.887530 [ 2501 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Debug> TCPHandler: Processed in 0.438897431 sec.
2023.08.03 15:42:39.226399 [ 2327 ] {85955690-c5dd-4e15-a182-8a8b7ddb4248} <Fatal> : Logical error: 'Operation `completePartAndResetDownloader` can be done only by downloader. (CallerId: None:2327, downloader id: 85955690-c5dd-4e15-a182-8a8b7ddb4248:2327)'.

```

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 12ed37e99a0c17b65002c14cac5347862e22f256 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53047/12ed37e99a0c17b65002c14cac5347862e22f256/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Interpreters/Cache/FileSegment.cpp [hunk 1]
```diff
@@ -186,9 +186,7 @@ bool FileSegment::isDownloaded() const
 
 String FileSegment::getCallerId()
 {
-    if (!CurrentThread::isInitialized()
-        || !CurrentThread::get().getQueryContext()
```
Comment (antonio2368) [inline src/Interpreters/Cache/FileSegment.cpp:190]: was there any specific reason for adding it initially?

**Review by antonio2368 — APPROVED** [review]
