### PR TITLE
Make rabbitmq nack broken messages

### LINKED ISSUE #45350: RabbitMq Storage Engine should NACK messages if exception is thrown during processing
The RabbitMq storage engine should NACK consumed messages if an exception is thrown during the processing of the messages. This allows broken messages to be deadlettered in Rabbitmq allowing monitoring, rectification, retries and other routing strategies in the event of failure.

The simplest use case is that if a MatView pointing to the rabbitmq table fails to successfully insert into the target table, the messages corresponding to that insert is NACKed.

## How to reproduce

**Schema Setup**
```
CREATE TABLE userQueue 
(
    userId String
)   
ENGINE = RabbitMQ 
SETTINGS 
    rabbitmq_host_port = 'localhost:5672',
    rabbitmq_exchange_name = 'user',
    rabbitmq_exchange_type = 'topic',
    rabbitmq_routing_key_list = 'all',
    rabbitmq_format = 'JSONEachRow',
    rabbitmq_queue_base = 'user-clickhouse',
    rabbitmq_flush_interval_ms=60000,
    rabbitmq_max_block_size=200,
    rabbitmq_queue_consume=true;

CREATE TABLE user 
(
    userId UInt32
)
ENGINE = MergeTree
PRIMARY KEY (userId)
ORDER BY (userId)
SETTINGS 
    index_granularity = 8192;


CREATE MATERIALIZED VIEW userMatView TO user
AS
SELECT
    userId 
FROM userQueue;
```

**Publish message to queue above**

image

**Exception Thrown**

```
<Error> void DB::StorageRabbitMQ::streamingToViewsFunc(): Code: 6. DB::Exception: Cannot parse string 'sam.shiles' as UInt32: syntax error at begin of string. Note: there are toUInt32OrZero and toUInt32OrNull functions, which returns zero/NULL instead of throwing exception.: while converting source column userId to destination column userId: while executing 'FUNCTION _CAST(userId :: 0, UInt32 :: 1) -> _CAST(userId, UInt32) UInt32 : 2': while pushing to view default.userMatView (32dbf733-c76b-414e-9c64-7f660541a7fb). (CANNOT_PARSE_TEXT), Stack trace (when copying this message, always include the lines below):
```

## Expected vs Actual Behavior

**Actual**

Message is ACKed as if it was successfully processed.

**Expected**

Message is NACKed and, if a dlx is configured on the queue, dead lettered.

**Additional Context** 

I suppose the difficulty here is that when the fix for flush interval and max block size is implemented (https://github.com/ClickHouse/ClickHouse/pull/44404) then you’ll not be able to easily tell which messages to NACK and which to message to ACK as you’ll be inserting in a batch. 

I'm not familiar enough with how CH works best for optimised ingest/write performance but I understand the advice is to batch inserts. Given that, I'd assumed that when the flush interval passes or max block size is reached then the rabbit engine would flush its buffer as a batch and that batch would either totally succeed or totally fail. If that's true, then you would have two options 1) on succeed, ack all messages that were flushed. 2) on fail, nack all messages that were flushed. If instead you get a mixed/partial result from the flush that indicates which items in the batch worked and which failed and reference/Id for the originating messages, then that makes things much easier. Hopefully it's that second scenario.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make rabbitmq nack broken messages. Closes https://github.com/ClickHouse/ClickHouse/issues/45350.

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [x]  Stateless tests
- [x]  Stateful tests
- [x]  Stress tests
- [x]  Unit tests
- [x]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 4d57aaebb1057d717e8df3830131ace76e5e2fe6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60312/4d57aaebb1057d717e8df3830131ace76e5e2fe6/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60312/4d57aaebb1057d717e8df3830131ace76e5e2fe6/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Storages/RabbitMQ/RabbitMQSource.cpp [hunk 1]
```diff
@@ -168,23 +168,39 @@ Chunk RabbitMQSource::generateImpl()
...
         exception_message.reset();
         size_t new_rows = 0;
 
         if (consumer->hasPendingMessages())
         {
+            /// A buffer containing a single RabbitMQ message.
             if (auto buf = consumer->consume())
+            {
                 new_rows = executor.execute(*buf);
+                chassert(new_rows == 1);
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Storages/RabbitMQ/RabbitMQSource.cpp:185]: No

File: tests/integration/test_storage_rabbitmq/test.py [hunk 2]
```diff
@@ -3648,3 +3648,98 @@ def on_consume(channel, method, properties, body):
...
+
+    attempt = 0
+    rows = 0
+    while attempt < 500:
+        rows = int(instance.query("SELECT count() FROM test.data"))
+        if rows == num_rows:
+            break
+        attempt += 1
+
+    assert rows == num_rows
```
[the remark this answers is not in the document]
Comment (kssenii) [reply tests/integration/test_storage_rabbitmq/test.py:3726]: Better to add a `time.sleep(1)` instead in between operations, forgot about need, in other rabbitmq it is almost always added

File: src/Storages/RabbitMQ/RabbitMQConsumer.cpp [hunk 3]
```diff
@@ -106,6 +106,18 @@ bool RabbitMQConsumer::ackMessages(const CommitInfo & commit_info)
     if (commit_info.channel_id != channel_id)
         return false;
 
+    for (const auto & delivery_tag : commit_info.failed_delivery_tags)
+    {
+        if (consumer_channel->reject(delivery_tag))
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Storages/RabbitMQ/RabbitMQConsumer.cpp:111]: it is not need because it is only for acked messages

File: src/Storages/RabbitMQ/RabbitMQSource.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (antaljanosbenjamin) [reply src/Storages/RabbitMQ/RabbitMQSource.cpp:185]: Then why do we have a for loop later on like `for (size_t i = 0; i < new_rows; ++i)`?

**Review by antaljanosbenjamin — APPROVED** [review]

**Review by kssenii — COMMENTED** [review]
(Trying to fix OOMs in rabbit tests)

**Comment by kssenii** [comment]
> (Trying to fix OOMs in rabbit tests)

All the OOMs were because I mistakingly set `channel_id = consumer.getChannelID()` instead of `message.channel_id` in the first commit of this PR [4d57aae](https://github.com/ClickHouse/ClickHouse/pull/60312/commits/4d57aaebb1057d717e8df3830131ace76e5e2fe6) (https://github.com/ClickHouse/ClickHouse/pull/60312/commits/4d57aaebb1057d717e8df3830131ace76e5e2fe6#diff-b15f3aac5c3af7fb9dceed818793a3b7cb68d0e053b818ae0cfd2948480e25faR171-R172)
Now all tests pass...

File: src/Storages/RabbitMQ/RabbitMQConsumer.cpp [hunk 4]
```diff
@@ -119,23 +133,33 @@ bool RabbitMQConsumer::ackMessages(const CommitInfo & commit_info)
...
+    }
 
     return false;
 }
 
 bool RabbitMQConsumer::nackMessages(const CommitInfo & commit_info)
 {
     if (state != State::OK)
+    {
+        LOG_TEST(log, "State is {}, will not ack messages", magic_enum::enum_name(state.load(std::memory_order_relaxed)));
```
Comment (antaljanosbenjamin) [inline src/Storages/RabbitMQ/RabbitMQConsumer.cpp:152]:
```suggestion
        LOG_TEST(log, "State is {}, will not nack messages", magic_enum::enum_name(state.load(std::memory_order_relaxed)));
```

File: src/Storages/RabbitMQ/RabbitMQConsumer.cpp [hunk 5]
```diff
@@ -119,23 +133,33 @@ bool RabbitMQConsumer::ackMessages(const CommitInfo & commit_info)
...
         return false;
+    }
 
     /// Nothing to nack.
     if (!commit_info.delivery_tag || commit_info.delivery_tag <= last_commited_delivery_tag)
+    {
+        LOG_TEST(log, "Delivery tag is {}, last committed delivery tag: {}, Will not ack messages",
```
Comment (antaljanosbenjamin) [inline src/Storages/RabbitMQ/RabbitMQConsumer.cpp:159]:
```suggestion
        LOG_TEST(log, "Delivery tag is {}, last committed delivery tag: {}, Will not nack messages",
```

File: src/Storages/RabbitMQ/StorageRabbitMQ.h [hunk 6]
```diff
@@ -77,6 +77,8 @@ class StorageRabbitMQ final: public IStorage, WithContext
     void incrementReader();
     void decrementReader();
 
+    LoggerPtr log;
```
Comment (antaljanosbenjamin) [inline src/Storages/RabbitMQ/StorageRabbitMQ.h:80]: Have you thought about keeping `log` as a private member and pass it separately to the ctor of `RabbitMQSource`? I think it slightly better, because we don't expose anything and the source doesn't have to know which logger it should use. However I have no strong opinion on this, probably I wouldn't have commented on this would be the only comment.

File: src/Storages/RabbitMQ/RabbitMQSource.cpp [hunk 7]
```diff
@@ -261,7 +288,6 @@ Chunk RabbitMQSource::generateImpl()
     for (auto & column : virtual_columns)
         result_columns.push_back(std::move(column));
 
-    commit_info = current_commit_info;
```
Comment (antaljanosbenjamin) [inline src/Storages/RabbitMQ/RabbitMQSource.cpp:264]: One more question: is `commit_info.failed_delivery_tags` are cleaned up amywhere? Isn't it a problem if we don't clean them up?

File: src/Storages/RabbitMQ/StorageRabbitMQ.h (hunk 6 above)
Comment (kssenii) [reply src/Storages/RabbitMQ/StorageRabbitMQ.h:80]: Yes, it is better not to move log to public, I was just being a bit lazy.

File: src/Storages/RabbitMQ/RabbitMQSource.cpp (hunk 7 above)
Comment (kssenii) [reply src/Storages/RabbitMQ/RabbitMQSource.cpp:264]: `commit_info` is a property of Source, not Consumer, Consumer is reused for reading while the Source is one time usage, e.g. we read and then ack/nack, after ack/nack we do not use the Source anymore, so it should not matter if we clear `commit_info` or not.

**Review by antaljanosbenjamin — APPROVED** [review]
