### PR TITLE
RabbitMQ: allow user to define specific queue settings, its own exchange, user-managed queues; add cleanup on drop table

### LINKED ISSUE #21757: RabbitMQ engine works incorrectly with queue which contains messages
Hi!
I made a table with RabbitMQ engine which connects to an existing queue and saves messages from it to table through materialized view. If the queue was empty before connecting then every new message is stored in table successfully, but if there were messages in the queue then only the last one is stored and others just disappear.

```SQL
CREATE TABLE queue (
	log String
) ENGINE = RabbitMQ SETTINGS ..., rabbitmq_exchange_type = 'topic', rabbitmq_format = 'JSONAsString';


CREATE MATERIALIZED VIEW consumer TO general AS
SELECT
   ...
FROM queue;
```

Do you have any idea what this can be about? It seems to me that this is  a bug in engine or view. 

Thanks!

ClickHouse 21.2.5.5

### LINKED ISSUE #23737: rabbitmq - how to change x-max-length for queues created by CH ?
rabbitmq - how to change x-max-length for queues created by CH ?
 
by default it looks like this: 
image

thank you!

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to add specific queue settings via table settng `rabbitmq_queue_settings_list`. (Closes https://github.com/ClickHouse/ClickHouse/issues/23737 and https://github.com/ClickHouse/ClickHouse/issues/23918). Allow user to control all RabbitMQ setup: if table setting `rabbitmq_queue_consume` is set to `1` - RabbitMQ table engine will only connect to specified queue and will not perform any RabbitMQ consumer-side setup like declaring exchange, queues, bindings. (Closes https://github.com/ClickHouse/ClickHouse/issues/21757). Add proper cleanup when RabbitMQ table is dropped - delete queues, which the table has declared and all bound exchanges - if they were created by the table.

### CODE REVIEW

File: src/Storages/RabbitMQ/StorageRabbitMQ.cpp [hunk 1]
```diff
@@ -450,23 +458,52 @@ void StorageRabbitMQ::bindQueue(size_t queue_id)
...
+    {
+        for (const auto & setting : queue_settings_list)
+        {
+            Strings setting_values;
+            splitInto<'='>(setting_values, setting);
+            assert(setting_values.size() == 2);
+            String key = setting_values[0], value = setting_values[1];
+
+            std::unordered_set<String> integer_settings = {"x-max-length", "x-max-length-bytes", "x-message-ttl", "x-expires", "x-priority", "x-max-priority"};
+            std::unordered_set<String> string_settings = {"x-overflow", "x-dead-letter-exchange", "x-queue-type"};
```
Comment (Avogar) [inline src/Storages/RabbitMQ/StorageRabbitMQ.cpp:472]: Do we really need to create these sets every iteration in a loop?

File: src/Storages/RabbitMQ/StorageRabbitMQ.cpp [hunk 2]
```diff
@@ -450,23 +458,52 @@ void StorageRabbitMQ::bindQueue(size_t queue_id)
...
+
+            if (integer_settings.find(key) != integer_settings.end())
```
Comment (Avogar) [inline src/Storages/RabbitMQ/StorageRabbitMQ.cpp:474]: Since C++20 sets have method `contains` to simplify this check.

File: src/Storages/RabbitMQ/StorageRabbitMQ.cpp (hunk 1 above)
Comment (kssenii) [reply src/Storages/RabbitMQ/StorageRabbitMQ.cpp:472]: oh, yes, thank you.

File: src/Storages/RabbitMQ/StorageRabbitMQ.cpp [hunk 3]
```diff
@@ -450,23 +458,52 @@ void StorageRabbitMQ::bindQueue(size_t queue_id)
...
+        queue_settings["x-max-length"] = queue_size;
+    }
+    if (!queue_settings.contains("x-dead-letter-exchange") && !deadletter_exchange.empty())
+    {
         queue_settings["x-dead-letter-exchange"] = deadletter_exchange;
-    else
+    }
+    else if (!queue_settings.contains("x-overflow"))
+    {
+        /// Define x-overflow only if there is not x-dead-letter-exchange, because it will overwrite the expected behaviour.
```
Comment (Avogar) [inline src/Storages/RabbitMQ/StorageRabbitMQ.cpp:494]: But we will define x-overflow if queue_settings contains x-dead-letter-exchange. Or I missed something?

Comment (kssenii) [reply src/Storages/RabbitMQ/StorageRabbitMQ.cpp:496]: Then probably it is intentional. Setting `x-dead-letter-exchange` has some cases, when it changes behaviour of rabbitmq queue and `x-overflow` is one of them, so it also makes sence to have `x-overflow` and `x-dead-letter-exchange` settings at the same time.
But by default, when there are no user-defined settings, there can be a separare setting in table settings `dead-letter-exchange` (it was added before the ability to add queue settings) so if it was added, there should be no overriding behaviour - that is what this comment is about.

Comment (Avogar) [reply src/Storages/RabbitMQ/StorageRabbitMQ.cpp:496]: I am not sure that having two different ways to set `x-dead-letter-exchange` setting is good idea. What do you think?

Comment (kssenii) [reply src/Storages/RabbitMQ/StorageRabbitMQ.cpp:496]: I agree, but I was not sure it is ok to delete settings which existed for a long time.. But I think I'll delete it, I doubt it was used.

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Test failures are not related.
