### PR TITLE
Correct implementation of AggregateState comparison

### LINKED ISSUE #42408: Failed assertion in casting AggregateFunction states.
```
SELECT CAST(x, 'AggregateFunction(sum, Decimal(50, 10))') FROM (SELECT arrayReduce('sumState', [toDecimal256('0.0000010.000001', 10)]) AS x) GROUP BY x
```

```
clickhouse: /home/milovidov/work/ClickHouse/src/AggregateFunctions/IAggregateFunction.cpp:73: virtual bool DB::IAggregateFunction::haveSameStateRepresentationImpl(const DB::IAggregateFunction &) const: Assertion `res == (getStateType()->getName() == rhs.getStateType()->getName())' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix rarely invalid cast of aggregate state types with complex types such as Decimal. This fixes https://github.com/ClickHouse/ClickHouse/issues/42408

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

File: src/AggregateFunctions/IAggregateFunction.cpp [hunk 1]
```diff
@@ -67,11 +70,7 @@ bool IAggregateFunction::haveSameStateRepresentation(const IAggregateFunction &
 
 bool IAggregateFunction::haveSameStateRepresentationImpl(const IAggregateFunction & rhs) const
 {
-    bool res = getName() == rhs.getName()
-        && parameters == rhs.parameters
-        && haveEqualArgumentTypes(rhs);
-    assert(res == (getStateType()->getName() == rhs.getStateType()->getName()));
-    return res;
+    return getStateType()->equals(*rhs.getStateType());
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/IAggregateFunction.cpp:73]: Thank you! Now it works as it is supposed to work!
