### PR TITLE
Fix test "02875_show_functions.sh"

### LINKED ISSUE #82897: `02875_show_functions` is flaky
[CI DB](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBsaWtlICclMDI4NzVfc2hvd19mdW5jdGlvbnMlJwogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPiB0b2RheSgpIC0gSU5URVJWQUwgMTAgREFZCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l)

```
2025-06-28 05:56:48 Reason: result differs with reference:  
2025-06-28 05:56:48 --- /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02875_show_functions.reference	2025-06-28 05:33:32.179071660 +1100
2025-06-28 05:56:48 +++ /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02875_show_functions.stdout	2025-06-28 05:56:48.552977315 +1100
2025-06-28 05:56:48 @@ -0,0 +1 @@
2025-06-28 05:56:48 +Files /dev/fd/63 and /dev/fd/62 differ
2025-06-28 05:56:48 
2025-06-28 05:56:48 
2025-06-28 05:56:48 /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/test_hb3qll1a/02875_show_functions.sh.debuglog:
2025-06-28 05:56:48 + [2025-06-28 05:56:46] [:7] diff -q /dev/fd/63 /dev/fd/62
2025-06-28 05:56:48 ++ [2025-06-28 05:56:46] [:7] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_hb3qll1a --log_comment 02875_show_functions.sh --max_insert_threads 1 --group_by_two_level_threshold 814065 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 0 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 5412659 --max_read_buffer_size 875095 --prefer_localhost_replica 0 --max_block_size 14860 --max_joined_block_size_rows 66530 --max_threads 1 --optimize_append_index 0 --use_hedged_requests 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 1 --optimize_read_in_order 0 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 62 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 1033756 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 16Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 0 --merge_tree_coarse_index_granularity 18 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 1964761335 --min_compress_block_size 528861 --max_compress_block_size 3089203 --merge_tree_compact_parts_min_granules_to_multibuffer_read 89 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 3780971 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone Africa/Juba --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.24 --prefer_external_sort_block_bytes 0 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 0 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 0 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 0 --query_plan_join_swap_table false --enable_vertical_final 0 --optimize_extract_common_expressions 0 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.0 --max_bytes_ratio_before_external_group_by 0.18 --use_skip_indexes_if_final_exact_mode 1 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 7717848484 --index_granularity_bytes 25002739 --merge_max_block_size 20244 --index_granularity 31285 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 45480 --primary_key_compress_block_size 10695 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 339870972 --compact_parts_max_bytes_to_buffer 263771062 --compact_parts_max_granules_to_buffer 48 --compact_parts_merge_max_bytes_to_prefetch_part 32035211 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 250 --prewarm_mark_cache 0 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 0 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02875_show_functions.stderr-fatal -q 'SELECT * from system.functions'
2025-06-28 05:56:48 ++ [2025-06-28 05:56:46] [:7] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_hb3qll1a --log_comment 02875_show_functions.sh --max_insert_threads 1 --group_by_two_level_threshold 814065 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 0 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 5412659 --max_read_buffer_size 875095 --prefer_localhost_replica 0 --max_block_size 14860 --max_joined_block_size_rows 66530 --max_threads 1 --optimize_append_index 0 --use_hedged_requests 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 1 --optimize_read_in_order 0 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 62 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 1033756 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 16Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 0 --merge_tree_coarse_index_granularity 18 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 1964761335 --min_compress_block_size 528861 --max_compress_block_size 3089203 --merge_tree_compact_parts_min_granules_to_multibuffer_read 89 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 3780971 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone Africa/Juba --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.24 --prefer_external_sort_block_bytes 0 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 0 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 0 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 0 --query_plan_join_swap_table false --enable_vertical_final 0 --optimize_extract_common_expressions 0 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.0 --max_bytes_ratio_before_external_group_by 0.18 --use_skip_indexes_if_final_exact_mode 1 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 7717848484 --index_granularity_bytes 25002739 --merge_max_block_size 20244 --index_granularity 31285 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 45480 --primary_key_compress_block_size 10695 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 339870972 --compact_parts_max_bytes_to_buffer 263771062 --compact_parts_max_granules_to_buffer 48 --compact_parts_merge_max_bytes_to_prefetch_part 32035211 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 250 --prewarm_mark_cache 0 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 0 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02875_show_functions.stderr-fatal -q 'SHOW FUNCTIONS'
2025-06-28 05:56:48 + [2025-06-28 05:56:47] [:10] diff -q /dev/fd/63 /dev/fd/62
2025-06-28 05:56:48 ++ [2025-06-28 05:56:47] [:10] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_hb3qll1a --log_comment 02875_show_functions.sh --max_insert_threads 1 --group_by_two_level_threshold 814065 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 0 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 5412659 --max_read_buffer_size 875095 --prefer_localhost_replica 0 --max_block_size 14860 --max_joined_block_size_rows 66530 --max_threads 1 --optimize_append_index 0 --use_hedged_requests 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 1 --optimize_read_in_order 0 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 62 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 1033756 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 16Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 0 --merge_tree_coarse_index_granularity 18 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 1964761335 --min_compress_block_size 528861 --max_compress_block_size 3089203 --merge_tree_compact_parts_min_granules_to_multibuffer_read 89 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 3780971 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone Africa/Juba --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.24 --prefer_external_sort_block_bytes 0 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 0 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 0 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 0 --query_plan_join_swap_table false --enable_vertical_final 0 --optimize_extract_common_expressions 0 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.0 --max_bytes_ratio_before_external_group_by 0.18 --use_skip_indexes_if_final_exact_mode 1 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 7717848484 --index_granularity_bytes 25002739 --merge_max_block_size 20244 --index_granularity 31285 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 45480 --primary_key_compress_block_size 10695 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 339870972 --compact_parts_max_bytes_to_buffer 263771062 --compact_parts_max_granules_to_buffer 48 --compact_parts_merge_max_bytes_to_prefetch_part 32035211 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 250 --prewarm_mark_cache 0 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 0 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02875_show_functions.stderr-fatal -q 'SELECT * FROM system.functions WHERE name ILIKE '\''quantile%'\'''
2025-06-28 05:56:48 ++ [2025-06-28 05:56:47] [:10] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_hb3qll1a --log_comment 02875_show_functions.sh --max_insert_threads 1 --group_by_two_level_threshold 814065 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 0 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 5412659 --max_read_buffer_size 875095 --prefer_localhost_replica 0 --max_block_size 14860 --max_joined_block_size_rows 66530 --max_threads 1 --optimize_append_index 0 --use_hedged_requests 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 1 --optimize_read_in_order 0 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 62 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 1033756 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 16Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 0 --merge_tree_coarse_index_granularity 18 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 1964761335 --min_compress_block_size 528861 --max_compress_block_size 3089203 --merge_tree_compact_parts_mi
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

Closes #82897.

### CODE REVIEW

File: tests/queries/0_stateless/02875_show_functions.sh [hunk 1]
```diff
@@ -1,14 +1,16 @@
 #!/usr/bin/env bash
+# Tags: no-parallel
+# Because other tests may create UDFs
```
Comment (Algunenano) [inline tests/queries/0_stateless/02875_show_functions.sh]: Can we use clickhouse local instead and keep it parallel?

Comment (alexey-milovidov) [reply tests/queries/0_stateless/02875_show_functions.sh]: Thanks, this will be much better!

**Review by Algunenano — APPROVED** [review]
