### PR TITLE
Speed-up `DISTINCT` window aggregates and fix `sumDistinct` computation bug

### LINKED ISSUE #52253: sumDistinct in window function the result is wrong
When I use sumDistinct in window function the result is wrong.
For example：
```SQL
 CREATE TABLE t1 ( `ID` UInt64, `col1` Int64) ENGINE = MergeTree ORDER BY ID;
 insert into events(ID, col1) select number, number % 3 from numbers(10);
 insert into events(ID, col1) select number, number % 3 from numbers(8);
select ID, col1, sum(Distinct(ID)) OVER (partition by col1) from events ORDER BY col1;
```

### LINKED ISSUE #79792: Slow distinct aggregate window function
### Company or project name

ClickHouse employee 😄 

### Describe the unexpected behaviour

A distinct aggregate over a window function in ClickHouse becomes very slow compared to other analytical databases. Maybe an optimization is missing?

### How to reproduce

Run:

```sql
SELECT avg(DISTINCT number) OVER () FROM numbers(0, 100000);
```

### Expected behavior

It shouldn't take several minutes, but some seconds at most.

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nihalzp**
**Performance:**
```SQL
SELECT avg(DISTINCT number) OVER () FROM numbers(0, 100_000);
```
This query used to run for several minutes; it now finishes in 0.031 sec.

**Bug Fix:**
```SQL
SELECT number, sum(DISTINCT number) OVER () FROM numbers(10);
```
It previously returned incorrect results; this bug is now fixed.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make `DISTINCT` window aggregates run in linear time and fix a bug in `sumDistinct`. Closes #79792. Closes #52253.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by nihalzp** [comment]
@alexey-milovidov The PR is ready for review.

The only failed test (`DB::Exception: Timeout exceeded`) is the performance test I added, which times out on the master branch as expected because the `DISTINCT` combinator runs in $O(n^2)$ there.

**Comment by alexey-milovidov** [comment]
Thanks for the implementation, looks great :+1: 
I will check the code and run a few queries...

**Comment by alexey-milovidov** [comment]
Thanks! The algorithm is non-obvious, but everything works flawlessly.

The only problem - we have to maintain compatibility between different ClickHouse versions (if they work together on a cluster to run distributed queries), so the old serialized states can still be read by the new version. We use "aggregate function versioning" for this purpose. See the `version` parameter in the methods, and its usage in other aggregate functions.

It's ok if deserializing the previous state produces invalid results in some cases (as it does not have enough information), but it should not lead to an error.

**Comment by alexey-milovidov** [comment]
I've also checked these queries, you can add them to the test:

`WITH arrayReduce('sumDistinctState', [1 + number, 2, 3]) AS a, arrayReduce('sumDistinctState', [2 + number, 3, 4]) AS b SELECT finalizeAggregation(a), finalizeAggregation(b), finalizeAggregation(a + b), finalizeAggregation(a * 2), finalizeAggregation(b * 2) FROM numbers(10)`

`WITH intHash64(number) % 10 AS x SELECT x, sumDistinct(x) OVER (ORDER BY number ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS a, sumDistinct(x) OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS b FROM numbers(10)`

**Comment by alexey-milovidov** [comment]
I still don't understand the algorithm.

What if we make the state of a -Distinct aggregate function as follows:
- the state of the nested aggregate function;
- the set of all values.

When merging, we take the values from the rhs set and add those that are not present in our set. The nested state of the rhs is not used while merging.

For serialization and deserialization, we only use the sets of values, so it is compatible with the previous implementation.

Having the state of the nested aggregate function in place lets us quickly obtain the final value.

**Comment by nihalzp** [comment]
@alexey-milovidov 

Thank you for your thorough review.

You are right. My algorithm fails to consider the compatibility requirement. I will be more mindful of it.

I've tried to implemented your idea — please let me know if this is the solution you proposed. This version maintains backward compatibility.

File: src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h [hunk 1]
```diff
@@ -176,12 +212,16 @@ class AggregateFunctionDistinct final : public IAggregateFunctionDataHelper<Data
 
     void add(AggregateDataPtr __restrict place, const IColumn ** columns, size_t row_num, Arena * arena) const override
     {
-        this->data(place).add(columns, arguments_num, row_num, arena);
+        auto argument_columns = prepareArgumentColumns();
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h:215]: I'm afraid this is slow.

Why don't we check the existence in the set, and if the element doesn't exist, reuse the `columns` to add it to the nested data?

File: src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h [hunk 2]
```diff
@@ -176,12 +212,16 @@ class AggregateFunctionDistinct final : public IAggregateFunctionDataHelper<Data
...
+        this->data(place).add(columns, arguments_num, row_num, argument_columns, arena);
+        addToNested(place, argument_columns, arena);
     }
 
     void merge(AggregateDataPtr __restrict place, ConstAggregateDataPtr rhs, Arena * arena) const override
     {
-        this->data(place).merge(this->data(rhs), arena);
+        auto argument_columns = prepareArgumentColumns();
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h:222]: For `merge` it is alright, though.

**Comment by nihalzp** [comment]
@alexey-milovidov 

The integration and stateless tests fails are unrelated. The performance test fail is expected.

File: src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h [hunk 3]
```diff
@@ -20,59 +20,53 @@ struct AggregateFunctionDistinctSingleNumericData
...
     {
-        set.merge(rhs.set);
-    }
+        const auto & vec = assert_cast<const ColumnVector<T> &>(*columns[0]).getData();
+        const T value = vec[row_num];
 
-    void serialize(WriteBuffer & buf) const
-    {
-        set.write(buf);
+        if (!history.contains(value))
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h:33]: Here we will do a lookup twice. Can we use the return value of the insert method?

Comment (nihalzp) [reply src/AggregateFunctions/Combinators/AggregateFunctionDistinct.h]: Good catch. I've optimized this and the other similar spots as well.

**Comment by nihalzp** [comment]
@alexey-milovidov The integration and stateless tests fails are unrelated. The performance test fail is expected.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@nihalzp, this query crashes:

`SELECT DISTINCT  '(forward, head, A->B)', id, sequenceNextNodeDistinct('forward', 'head', 4)(dt, action, action = 'A', toNullable(1 IS NOT NULL) AND (NOT toNullable(isNullable(1)))) IGNORE NULLS AS next_node FROM test_sequenceNextNode__fuzz_0 GROUP BY * WITH ROLLUP WITH TOTALS ORDER BY ALL ASC NULLS LAST`

**Comment by nihalzp** [comment]
@alexey-milovidov It should be okay now.

**Comment by alexey-milovidov** [comment]
@nihalzp, still there is an assertion failure in debug build: https://pastila.nl/?0000efc9/13710e16f3b9aec3453722e411a5cc7a#ETP5fOq1KwXwXofJpeVzhA==

**Comment by alexey-milovidov** [comment]
@nihalzp, let's continue - it's very close to being merged!

**Comment by nihalzp** [comment]
@alexey-milovidov 
The problem is that `src/AggregateFunctions/AggregateFunctionsMinMax.cpp` is expecting null-terminated string. (line 59, then `src/AggregateFunctions/SingleValueData.cpp` line 1246, then line 1090).

For example, the following query is crashing for me in Debug build but it does not involve `Distinct`:

```sql
SELECT min(toDecimalString(
            77 IS NOT NULL,
            isZeroOrNull(toNullable(1) IS NOT NULL)
        )) FROM numbers(3);
```

The root problem seems to be that `IColumn` single value data string is not null-terminated (as mentioned in `src/AggregateFunctions/SingleValueData.cpp` line 1083).

**Comment by nihalzp** [comment]
I am not sure whether it will break compatibility with other part of the codebase, but we can solve the issue by null terminating the string during `toDecimalString`.

**Comment by nihalzp** [comment]
@alexey-milovidov I think it is fixed now.

The issue was that when precision is `0` for `toDecimalString`, the output was not null terminated. After the fix, the query seems to be working as expected.

**Comment by nihalzp** [comment]
@alexey-milovidov The stateless test failure seems unrelated, and the performance comparison failure is expected.

**Comment by alexey-milovidov** [comment]
Thanks, this is a great finding! Thank you so much for fixing it :tada:

**Comment by alexey-milovidov** [comment]
@nihalzp, could you please send a message to milovidov@clickhouse.com?
I didn't find your email or LinkedIn.

**Comment by nihalzp** [comment]
> @nihalzp, could you please send a message to [milovidov@clickhouse.com](mailto:milovidov@clickhouse.com)? I didn't find your email or LinkedIn.

@alexey-milovidov Okay, sent you a message via email.
