### PR TITLE
Fix multiple issues with memory tracking

### LINKED ISSUE #14560: A query from `generateRandom` function may lead to OOM
**Describe the bug**
`SELECT i FROM generateRandom('i Array(Int8)', 1048575, 10, 1048577) LIMIT 1048575`

Memory limit should be respected.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the case when memory can be overallocated regardless to the limit. This closes #14560

### CODE REVIEW

File: src/Common/MemoryTracker.cpp [hunk 1]
```diff
@@ -86,12 +90,15 @@ void MemoryTracker::alloc(Int64 size)
...
     Int64 current_profiler_limit = profiler_limit.load(std::memory_order_relaxed);
 
-    /// Cap the limit to the total_memory_tracker, since it may include some drift.
+    /// Cap the limit to the total_memory_tracker, since it may include some drift
+    /// for user-level memory tracker.
     ///
     /// And since total_memory_tracker is reset to the process resident
     /// memory peridically (in AsynchronousMetrics::update()), any limit can be
     /// capped to it, to avoid possible drift.
-    if (unlikely(current_hard_limit && will_be > current_hard_limit))
```
Comment (alexey-milovidov) [inline src/Common/MemoryTracker.cpp:94]: This code was very fragile and may lead to allocation over the limit.

File: src/Common/MemoryTracker.cpp [hunk 2]
```diff
@@ -104,10 +111,8 @@ void MemoryTracker::alloc(Int64 size)
     std::bernoulli_distribution fault(fault_probability);
     if (unlikely(fault_probability && fault(thread_local_rng)))
     {
-        free(size);
```
Comment (alexey-milovidov) [inline src/Common/MemoryTracker.cpp:107]: This code was incorrect as we don't need to recursively subtract from the chain of memory trackers here (we did not increased the memory tracked by parent memory tracker).

File: src/Common/MemoryTracker.cpp [hunk 3]
```diff
@@ -298,11 +303,3 @@ namespace CurrentMemoryTracker
         }
     }
 }
-
-DB::SimpleActionLock getCurrentMemoryTrackerActionLock()
```
Comment (alexey-milovidov) [inline src/Common/MemoryTracker.cpp:302]: This code was wrong, because it disables memory tracking for all threads.
When one thread is throwing exception, another thread was being able to overallocate, presenting the race condition.

I did not find any cases when this type of cancelling is needed.

**Comment by alexey-milovidov** [comment]
Integration test `test_multiple_disks` - bad test, @excitoon

File: src/Common/MemoryTracker.cpp [hunk 4]
```diff
@@ -151,6 +155,7 @@ void MemoryTracker::alloc(Int64 size)
             << " (attempt to allocate chunk of " << size << " bytes)"
             << ", maximum: " << formatReadableSizeWithBinarySuffix(current_hard_limit);
 
+        amount.fetch_sub(size, std::memory_order_relaxed);
```
Comment (azat) [inline src/Common/MemoryTracker.cpp:158]: free had been replaced with subtraction from amount for proper accounting in parent tracker?

Comment (alexey-milovidov) [reply src/Common/MemoryTracker.cpp:158]: Yes (I commented it in this PR above), otherwise we erroneously subtract from parent, but we did not add anything yet.
