### PR TITLE
Avoid using Field in aggregation functions for types Dynamic/Variant/JSON

### LINKED ISSUE #78692: argMax produces wrong output for Dynamic columns
### Company or project name

_No response_

### Describe what's wrong

Clickhouse Version: `25.3.1.724`

**Reproduction SQL:**

```
SET enable_dynamic_type = 1;

CREATE TABLE IF NOT EXISTS "dataset_cells"
(
    dataset_id UUID,
    dataset_row_id UUID,
    variable_id UUID,
    value Dynamic, 
    created_at DateTime64(9) DEFAULT now64(9),
)
ENGINE = ReplacingMergeTree
ORDER BY (dataset_id, variable_id, dataset_row_id, created_at);

INSERT INTO dataset_cells (dataset_id, dataset_row_id, variable_id, value) VALUES('962ce6f6-38d5-4bc8-91f6-2fce91b26e40', 'b95768ba-3fa1-4a3a-81de-77b8c6ca1354', 'e87164a9-1e42-4125-a28c-3a95eb989568', 94::Int64);
INSERT INTO dataset_cells (dataset_id, dataset_row_id, variable_id, value) VALUES('962ce6f6-38d5-4bc8-91f6-2fce91b26e40', '13c4d632-4877-4d76-8162-926641fe4bf0', 'e87164a9-1e42-4125-a28c-3a95eb989568', 400::Int64);

SELECT 
    dataset_id,
    dataset_row_id,
    variable_id,
    argMax(value, created_at) as value,
    max(created_at)
FROM dataset_cells
GROUP BY dataset_id, dataset_row_id, variable_id
```

**Observed behavior:**

Image

- Instead of `400`, the value being produced by `argMax` is `-112` which is not in any of the data.
- This does not happen if we remove `dataset_id` or `variable_id` from the table (both of those columns stay constant between the two rows).

**Expected behavior:**
- The `-112` should be `400`

**Notes:**

If you run the following query, where we cast the dynamic column to `Int64`, it works as expected:
```
SELECT 
    dataset_id,
    dataset_row_id,
    variable_id,
    argMax(value::Int64, created_at) as value,
    max(created_at)
FROM dataset_cells
GROUP BY dataset_id, dataset_row_id, variable_id
```
This is not an option because I don't know the type being stored.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

SET enable_dynamic_type = 1;

CREATE TABLE IF NOT EXISTS "dataset_cells"
(
    dataset_id UUID,
    dataset_row_id UUID,
    variable_id UUID,
    value Dynamic, 
    created_at DateTime64(9) DEFAULT now64(9),
)
ENGINE = ReplacingMergeTree
ORDER BY (dataset_id, variable_id, dataset_row_id, created_at);

INSERT INTO dataset_cells (dataset_id, dataset_row_id, variable_id, value) VALUES('962ce6f6-38d5-4bc8-91f6-2fce91b26e40', 'b95768ba-3fa1-4a3a-81de-77b8c6ca1354', 'e87164a9-1e42-4125-a28c-3a95eb989568', 94::Int64);
INSERT INTO dataset_cells (dataset_id, dataset_row_id, variable_id, value) VALUES('962ce6f6-38d5-4bc8-91f6-2fce91b26e40', '13c4d632-4877-4d76-8162-926641fe4bf0', 'e87164a9-1e42-4125-a28c-3a95eb989568', 400::Int64);

SELECT 
    dataset_id,
    dataset_row_id,
    variable_id,
    argMax(value, created_at) as value,
    max(created_at)
FROM dataset_cells
GROUP BY dataset_id, dataset_row_id, variable_id

### Expected behavior

- The `-112` should be `400`

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Try to use IColumn instead of Field in SingleValueDataGeneric. It fixes the incorrect return values for some aggregate functions like `argMax` for types `Dynamic/Variant/JSON`.

Closes https://github.com/ClickHouse/ClickHouse/issues/78692

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by Avogar** [comment]
Doesn't work well, the performance withe the Field is better because creating IColumn for storing single row allocates more memory

**Comment by Avogar** [comment]
Let's try another way

File: src/AggregateFunctions/SingleValueData.cpp [hunk 1]
```diff
@@ -1420,8 +1421,137 @@ bool SingleValueDataGeneric::setIfGreater(const SingleValueDataBase & other, Are
...
+    auto const & to = assert_cast<const Self &>(other);
+    return has() && to.has() && !to.value->compareAt(0, 0, *value, -1);
+}
+
+void SingleValueDataGenericWithColumn::set(const IColumn & column, size_t row_num, Arena *)
+{
+    auto new_value = column.cloneEmpty();
+    new_value->reserve(1);
+    new_value->insertFrom(column, row_num);
+    value = recursiveRemoveSparse(std::move(new_value));
```
Comment (divanik) [inline src/AggregateFunctions/SingleValueData.cpp:1473]: Why do we have recursiveRemoveSparse here?

**Review by divanik — COMMENTED** [review]
No issues, a couple of small questions

File: src/AggregateFunctions/SingleValueData.cpp [hunk 2]
```diff
@@ -1420,8 +1421,137 @@ bool SingleValueDataGeneric::setIfGreater(const SingleValueDataBase & other, Are
...
+}
+
+void SingleValueDataGenericWithColumn::read(ReadBuffer & buf, const ISerialization & serialization, const DataTypePtr & type, Arena *)
+{
+    bool is_not_null;
+    readBinary(is_not_null, buf);
+
+    if (is_not_null)
+    {
+        auto new_value = type->createColumn();
```
[the remark this answers is not in the document]
Comment (Avogar) [reply src/AggregateFunctions/SingleValueData.cpp:1450]: Because it might be unitialized here. Or if you mean why can't we use `value = type->createColumn()` then it's because `value` has type `ColumnPtr` which is immutable and here `new_value` is `MutableColumnPtr`. We need mutable column here to be able to insert into it.

File: src/AggregateFunctions/SingleValueData.cpp (hunk 1 above)
Comment (Avogar) [reply src/AggregateFunctions/SingleValueData.cpp:1473]: Because we don't want to deal with ColumnSparse here, we want to store value in the original column. Here in `set` we can propogate column that was read from MergeTree table and it can be ColumnSparse.

**Review by divanik — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @Avogar @divanik — while reviewing this PR I found the following:

- **Bug (P0):** Server SEGFAULT in `SingleValueDataGenericWithColumn::read` for `singleValueOrNull(JSON)` because `result_type` (`Nullable(JSON)`) is passed instead of `value_type` (`JSON`) — https://github.com/ClickHouse/ClickHouse/issues/103630

Happy to discuss — close anything that's wrong or already addressed.
