### PR TITLE
Fix logical error when fetched part has newer metadata version than table

### LINKED ISSUE #67799: Logical error: 'Part -2_0_26_2_47 with metadata version 13 contains column h that is absent in table test with metadata version 12'.
https://s3.amazonaws.com/clickhouse-test-reports/67654/8cb2e308f41638ebb6ba7fddbd4f0bf89d4d612e/stateless_tests__ubsan__[2_2].html
There is no stack trace in server log unfortunately.
Logs: https://pastila.nl/?0022f928/547d3ad353a548e48bad6ba15b980ad9#jBY1EIM5RhuFlAIkhwAEhQ==

### PR DESCRIPTION
**Pull request by alexey-milovidov**
When a part is fetched from another replica that has already processed an `ALTER ADD COLUMN`, the part may have a higher metadata version than the local table schema. Previously this would throw a `LOGICAL_ERROR` exception because the code only handled the case where `part_metadata_version < table_metadata_version` (assuming the column was dropped).

This fix handles the case where `part_metadata_version > table_metadata_version` by logging a warning and keeping the column in the output part. The column was legitimately added via ALTER on another replica and will be added to this replica's table schema once the ALTER is processed locally.

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/67799

### Version info
- Merged into: `26.2.1.379`

### CODE REVIEW

File: src/Storages/MergeTree/MutateTask.cpp [hunk 1]
```diff
@@ -388,10 +388,25 @@ static void splitAndModifyMutationCommands(
...
                     /// StorageMergeTree does not have metadata version
                     if (part->storage.supportsReplication())
-                        throw Exception(ErrorCodes::LOGICAL_ERROR, "Part {} with metadata version {} contains column {} that is absent "
-                                        "in table {} with metadata version {}",
-                                        part->name, part_metadata_version, column.name,
+                    {
+                        /// When part has higher metadata version than the table, it means the part was fetched from another replica
+                        /// that already processed an ALTER ADD COLUMN. The column will be added to this replica's table schema
+                        /// once the ALTER is processed locally. We should keep the column in the output part.
+                        if (part_metadata_version > table_metadata_version)
```
Comment (alesapin) [inline src/Storages/MergeTree/MutateTask.cpp:395]: @alexey-milovidov Mutation shouldn't be executed ahead of corresponding metadata change. This situation shouldn't be possible and must throw LOGICAL ERROR. The code you added will lead data loss of freshly inserted column.
