### PR TITLE
Fix crash in Iceberg + Avro when only virtual columns are read

### LINKED ISSUE #88238: Iceberg out-of-bounds access on Avro file
### Describe the bug

This may be a duplicate of an existing issue. Didn't find any with the same stack trace.

### How to reproduce

Run:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = IcebergLocal(local, path = '/var/lib/clickhouse/user_files/lakehouses/t0');
INSERT INTO TABLE FUNCTION icebergLocal(local, path = '/var/lib/clickhouse/user_files/lakehouses/t0', format = 'Avro', structure = 'c0 Int') (c0) VALUES (1);
SELECT 1 FROM icebergLocal(local, structure = 'c0 Int', path = '/var/lib/clickhouse/user_files/lakehouses/t0') tx JOIN icebergLocal(local, structure = 'c0 Int', format = 'Avro', path = '/var/lib/clickhouse/user_files/lakehouses/t0') ty ON TRUE WHERE tx._row_number SETTINGS input_format_parquet_use_native_reader_v3 = 1, optimize_count_from_files = 0;
```

### Error message and/or stacktrace

Stack trace:
```
[ip-172-31-18-156] 2025.10.08 12:39:16.779854 [ 3912737 ] <Fatal> BaseDaemon: ########################################
[ip-172-31-18-156] 2025.10.08 12:39:16.779929 [ 3912737 ] <Fatal> BaseDaemon: (version 25.10.1.1945 (official build), build id: 925CE58814F3C6D8152B32052767C234634FDC74, git hash: 11350d949aa8f7d03c1c6a7e6639509358a5d985) (from thread 3913482) (query_id: f34ed8c6-37bd-4f97-8b36-3bc9bd377431) (query: SELECT 1 FROM icebergLocal(local, structure = 'c0 Int', path = '/var/lib/clickhouse/user_files/lakehouses/t0') tx JOIN icebergLocal(local, structure = 'c0 Int', format = 'Avro', path = '/var/lib/clickhouse/user_files/lakehouses/t0') ty ON TRUE WHERE tx._row_number;) Received signal Aborted (6)
[ip-172-31-18-156] 2025.10.08 12:39:16.779961 [ 3912737 ] <Fatal> BaseDaemon: 
[ip-172-31-18-156] 2025.10.08 12:39:16.779993 [ 3912737 ] <Fatal> BaseDaemon: Stack trace: 0x0000727bdc6a49bd 0x0000727bdc64579e 0x0000727bdc6288cd 0x00005f353de6245d 0x00005f3534e442c8 0x00005f3534e44641 0x00005f3534e66f05 0x00005f3534e01c56 0x00005f3534dd6665 0x00005f3534dd6342 0x00005f3534df3750 0x00005f3534de54d8 0x00005f3534de508e 0x00005f3534dfc7b4 0x00005f352f5b0cb7 0x00005f3534dd6665 0x00005f3534dd6342 0x00005f3534df3750 0x00005f3534de54d8 0x00005f3534de5ae9 0x00005f3534de6b83 0x00005f352a1b2f53 0x00005f352a1b9626 0x00005f352a1b03e6 0x00005f352a1b6e00 0x0000727bdc6a27f1 0x0000727bdc733b5c
[ip-172-31-18-156] 2025.10.08 12:39:16.780060 [ 3912737 ] <Fatal> BaseDaemon: 3. __GI___pthread_kill @ 0x00000000000a49bd
[ip-172-31-18-156] 2025.10.08 12:39:16.780095 [ 3912737 ] <Fatal> BaseDaemon: 4. __GI_raise @ 0x000000000004579e
[ip-172-31-18-156] 2025.10.08 12:39:16.780123 [ 3912737 ] <Fatal> BaseDaemon: 5. abort @ 0x00000000000288cd
[ip-172-31-18-156] 2025.10.08 12:39:16.785323 [ 3912737 ] <Fatal> BaseDaemon: 6. contrib/llvm-project/libcxx/src/verbose_abort.cpp:74: ? @ 0x000000002881945d
[ip-172-31-18-156] 2025.10.08 12:39:16.858979 [ 3912737 ] <Fatal> BaseDaemon: 7.0. inlined from contrib/llvm-project/libcxx/include/vector:1436: std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>::operator[][abi:se190107](unsigned long)
[ip-172-31-18-156] 2025.10.08 12:39:16.859029 [ 3912737 ] <Fatal> BaseDaemon: 7. src/Processors/Formats/Impl/AvroRowInputFormat.cpp:1002: DB::AvroDeserializer::deserializeRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, avro::Decoder&, DB::RowReadExtension&) const @ 0x000000001f7fb2c8
[ip-172-31-18-156] 2025.10.08 12:39:16.925957 [ 3912737 ] <Fatal> BaseDaemon: 8. src/Processors/Formats/Impl/AvroRowInputFormat.cpp:1032: DB::AvroRowInputFormat::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x000000001f7fb641
[ip-172-31-18-156] 2025.10.08 12:39:16.935346 [ 3912737 ] <Fatal> BaseDaemon: 9. src/Processors/Formats/IRowInputFormat.cpp:146: DB::IRowInputFormat::read() @ 0x000000001f81df05
[ip-172-31-18-156] 2025.10.08 12:39:16.942959 [ 3912737 ] <Fatal> BaseDaemon: 10. src/Processors/Formats/IInputFormat.cpp:29: DB::IInputFormat::generate() @ 0x000000001f7b8c56
[ip-172-31-18-156] 2025.10.08 12:39:16.951895 [ 3912737 ] <Fatal> BaseDaemon: 11. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000001f78d665
[ip-172-31-18-156] 2025.10.08 12:39:16.959955 [ 3912737 ] <Fatal> BaseDaemon: 12. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001f78d342
[ip-172-31-18-156] 2025.10.08 12:39:16.964590 [ 3912737 ] <Fatal> BaseDaemon: 13.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
[ip-172-31-18-156] 2025.10.08 12:39:16.964615 [ 3912737 ] <Fatal> BaseDaemon: 13. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001f7aa750
[ip-172-31-18-156] 2025.10.08 12:39:16.981636 [ 3912737 ] <Fatal> BaseDaemon: 14. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f79c4d8
[ip-172-31-18-156] 2025.10.08 12:39:16.997978 [ 3912737 ] <Fatal> BaseDaemon: 15. src/Processors/Executors/PipelineExecutor.cpp:179: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x000000001f79c08e
[ip-172-31-18-156] 2025.10.08 12:39:17.006277 [ 3912737 ] <Fatal> BaseDaemon: 16. src/Processors/Executors/PullingPipelineExecutor.cpp:59: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x000000001f7b37b4
[ip-172-31-18-156] 2025.10.08 12:39:17.056258 [ 3912737 ] <Fatal> BaseDaemon: 17. src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:286: DB::StorageObjectStorageSource::generate() @ 0x0000000019f67cb7
[ip-172-31-18-156] 2025.10.08 12:39:17.064925 [ 3912737 ] <Fatal> BaseDaemon: 18. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x000000001f78d665
[ip-172-31-18-156] 2025.10.08 12:39:17.073007 [ 3912737 ] <Fatal> BaseDaemon: 19. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001f78d342
[ip-172-31-18-156] 2025.10.08 12:39:17.077394 [ 3912737 ] <Fatal> BaseDaemon: 20.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
[ip-172-31-18-156] 2025.10.08 12:39:17.077422 [ 3912737 ] <Fatal> BaseDaemon: 20. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001f7aa750
[ip-172-31-18-156] 2025.10.08 12:39:17.093807 [ 3912737 ] <Fatal> BaseDaemon: 21. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f79c4d8
[ip-172-31-18-156] 2025.10.08 12:39:17.109692 [ 3912737 ] <Fatal> BaseDaemon: 22. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001f79cae9
[ip-172-31-18-156] 2025.10.08 12:39:17.128418 [ 3912737 ] <Fatal> BaseDaemon: 23.0. inlined from src/Processors/Executors/PipelineExecutor.cpp:565: operator()
[ip-172-31-18-156] 2025.10.08 12:39:17.128454 [ 3912737 ] <Fatal> BaseDaemon: 23.1. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:se190107]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[ip-172-31-18-156] 2025.10.08 12:39:17.128476 [ 3912737 ] <Fatal> BaseDaemon: 23.2. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[ip-172-31-18-156] 2025.10.08 12:39:17.128486 [ 3912737 ] <Fatal> BaseDaemon: 23.3. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
[ip-172-31-18-156] 2025.10.08 12:39:17.128491 [ 3912737 ] <Fatal> BaseDaemon: 23. contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x000000001f79db83
[ip-172-31-18-156] 2025.10.08 12:39:17.139530 [ 3912737 ] <Fatal> BaseDaemon: 24.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[ip-172-31-18-156] 2025.10.08 12:39:17.139556 [ 3912737 ] <Fatal> BaseDaemon: 24.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[ip-172-31-18-156] 2025.10.08 12:39:17.139597 [ 3912737 ] <Fatal> BaseDaemon: 24. src/Common/ThreadPool.cpp:802: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000014b69f53
[ip-172-31-18-156] 2025.10.08 12:39:17.151780 [ 3912737 ] <Fatal> BaseDaemon: 25.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
[ip-172-31-18-156] 2025.10.08 12:39:17.151828 [ 3912737 ] <Fatal> BaseDaemon: 25.1. inlined from contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
[ip-172-31-18-156] 2025.10.08 12:39:17.151857 [ 3912737 ] <Fatal> BaseDaemon: 25.2. inlined from contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
[ip-172-31-18-156] 2025.10.08 12:39:17.151889 [ 3912737 ] <Fatal> BaseDaemon: 25. src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000014b70626
[ip-172-31-18-156] 2025.10.08 12:39:17.161992 [ 3912737 ] <Fatal> BaseDaemon: 26.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[ip-172-31-18-156] 2025.10.08 12:39:17.162030 [ 3912737 ] <Fatal> BaseDaemon: 26.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[ip-172-31-18-156] 2025.10.08 12:39:17.162041 [ 3912737 ] <Fatal> BaseDaemon: 26. src/Common/ThreadPool.cpp:812: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000014b673e6
[ip-172-31-18-156] 2025.10.08 12:39:17.182132 [ 3912737 ] <Fatal> BaseDaemon: 27.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
[ip-172-31-18-156] 2025.10.08 12:39:17.182178 [ 3912737 ] <Fatal> BaseDaemon: 27.1. inlined from contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
[ip-172-31-18-156] 2025.10.08 12:39:17.182190 [ 3912737 ] <Fatal> BaseDaemon: 27. contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000014b6de00
[ip-172-31-18-156] 2025.10.08 12:39:17.182208 [ 3912737 ] <Fatal> BaseDaemon: 28. start_thread @ 0x00000000000a27f1
[ip-172-31-18-156] 2025.10.08 12:39:17.182226 [ 3912737 ] <Fatal> BaseDaemon: 29. __clone3 @ 0x0000000000133b5c
[ip-172-31-18-156] 2025.10.08 12:39:17.399732 [ 3912737 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 13B4E0F3BAE38EFB10C46EDC981DFABE)
[ip-172-31-18-156] 2025.10.08 12:39:17.829897 [ 3912737 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[ip-172-31-18-156] 2025.10.08 12:39:17.830045 [ 3912737 ] <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, optimize_count_from_files = false, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, enable_lightweight_update = true, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, query_plan_use_new_logical_join_step = false, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_live_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_qbit_type = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_shared_set_join = true, input_format_parquet_use_native_reader_v3 = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix out of bounds error when user tries to query only virtual columns from Iceberg table with Avro format for data. It's super rare scenario so not marking it as critical. Fixes #88238.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

This PR is written with help from Claude Code.

---

> [!NOTE]
> **Medium Risk**
> Touches file-like storage read planning and the `optimize_count_from_files` fast path; incorrect gating or row-number metadata propagation could affect query correctness for `_row_number`/count queries across File/URL/ObjectStorage engines.
> 
> **Overview**
> Fixes `_row_number` handling for file-like storages by **propagating per-chunk row-number offsets**: `IRowInputFormat::read()` now attaches `ChunkInfoRowNumbers` to both normal chunks and `need_only_count` chunks so virtual `_row_number` can be derived safely.
> 
> Disables the `optimize_count_from_files` shortcut when **row-dependent virtual columns** (currently `_row_number`) are requested via a new `VirtualColumnUtils::hasRowDependentVirtualColumns()` check, preventing count-only reads from being used when row parsing is required.
> 
> Makes `prepareReadingFromFormat()` always pick a smallest physical column when *only virtual columns* are selected (avoids empty-read edge cases), and adds stateless tests covering Iceberg+Avro and CSV `_row_number` queries (including parallel parsing) for File/URL/S3.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit b9561bb746216db7f819cd216393d3cae13b7b7f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.556`

### CODE REVIEW

File: tests/queries/0_stateless/03916_iceberg_avro_row_number_crash.reference
Comment (alesapin) [inline tests/queries/0_stateless/03916_iceberg_avro_row_number_crash.reference]: Is it correct answer for `SELECT _row_number` with single row in table? I don't think so.

File: src/Processors/Formats/IRowInputFormat.cpp [hunk 1]
```diff
@@ -139,19 +127,19 @@ Chunk IRowInputFormat::read()
             }
             total_rows += num_rows;
             approx_bytes_read_for_chunk = getDataOffsetMaybeCompressed(getReadBuffer()) - chunk_start_offset;
-            return getChunkForCount(num_rows);
+            auto chunk = getChunkForCount(num_rows);
+            chunk.getChunkInfos().add(std::make_shared<ChunkInfoRowNumbers>(total_rows_before_read));
```
Comment (alesapin) [inline src/Processors/Formats/IRowInputFormat.cpp:144]: I'm not sure it worth it :(

**Review by alesapin — COMMENTED** [review]
Really not sure about changes in IRowInputFormat

File: tests/queries/0_stateless/03917_row_number_csv_file.sql
Comment (alesapin) [inline tests/queries/0_stateless/03917_row_number_csv_file.sql]:
```suggestion
CREATE TABLE test_csv_row_number (a UInt32, b String) ENGINE = File('CSV', '${CLICKHOUSE_DATABASE}/data.csv');
```

Comment (alesapin) [inline tests/queries/0_stateless/03917_row_number_csv_file.sql]:
```suggestion
CREATE TABLE test_csv_row_number (a UInt32, b String) ENGINE = File(CSV);
```

Comment (alesapin) [inline tests/queries/0_stateless/03917_row_number_csv_file.sql]:
```suggestion
-- Tags: no-parallel
-- Test _row_number virtual column for CSV format with and without parallel parsing
```

File: src/Storages/VirtualColumnUtils.cpp [hunk 2]
```diff
@@ -411,7 +410,6 @@ void addRequestedFileLikeStorageVirtualsToChunk(
                 chunk.addColumn(ColumnNullable::create(std::move(column), std::move(null_map)));
                 return;
             }
-#endif
```
[the remark this answers is not in the document]
Comment (alesapin) [reply src/Storages/VirtualColumnUtils.cpp:417]: Completely wrong.

**Review by Avogar — APPROVED** [review]

File: tests/queries/0_stateless/03917_row_number_csv_file.sql
Comment (alesapin) [inline tests/queries/0_stateless/03917_row_number_csv_file.sql]:
```suggestion
DROP TABLE test_csv_row_number SYNC;
```

Comment (alesapin) [inline tests/queries/0_stateless/03917_row_number_csv_file.sql]:
```suggestion
DROP TABLE IF EXISTS test_csv_row_number SYNC;
```
