### PR TITLE
Fix: data race in TCPHandler on socket timeouts settings

### LINKED ISSUE #64053: ThreadSanitizer: data race: DB::TimeoutSetter::~TimeoutSetter()
https://s3.amazonaws.com/clickhouse-test-reports/0/68bff50c9d2573d7f515ba720e3b9904fb87bcbd/stress_test__azure__tsan_.html

```
WARNING: ThreadSanitizer: data race (pid=3239)
  Write of size 8 at 0x720c02096f88 by thread T910:
    #0 Poco::Timespan::operator=(Poco::Timespan const&) build_docker/./base/poco/Foundation/src/Timespan.cpp:61:8 (clickhouse+0x1d119b68) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #1 Poco::Net::SocketImpl::setReceiveTimeout(Poco::Timespan const&) build_docker/./base/poco/Net/src/SocketImpl.cpp:557:15 (clickhouse+0x1cf0fa67) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #2 Poco::Net::Socket::setReceiveTimeout(Poco::Timespan const&) build_docker/./base/poco/Net/include/Poco/Net/Socket.h:422:17 (clickhouse+0x192c96a7) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #3 DB::TimeoutSetter::reset() build_docker/./src/IO/TimeoutSetter.cpp:56:12 (clickhouse+0x192c96a7)
    #4 DB::TimeoutSetter::~TimeoutSetter() build_docker/./src/IO/TimeoutSetter.cpp:37:9 (clickhouse+0x192c96a7)
    #5 std::__1::default_delete<DB::TimeoutSetter>::operator()[abi:v15000](DB::TimeoutSetter*) const build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5 (clickhouse+0x1943255d) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #6 std::__1::unique_ptr<DB::TimeoutSetter, std::__1::default_delete<DB::TimeoutSetter>>::reset[abi:v15000](DB::TimeoutSetter*) build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7 (clickhouse+0x1943255d)
    #7 DB::TCPHandler::runImpl()::$_2::operator()() const build_docker/./src/Server/TCPHandler.cpp:368:13 (clickhouse+0x1943255d)
    #8 BasicScopeGuard<DB::TCPHandler::runImpl()::$_2>::invoke() build_docker/./base/base/../base/scope_guard.h:101:9 (clickhouse+0x1943255d)
    #9 BasicScopeGuard<DB::TCPHandler::runImpl()::$_2>::~BasicScopeGuard() build_docker/./base/base/../base/scope_guard.h:50:26 (clickhouse+0x1943255d)
    #10 DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:611:9 (clickhouse+0x19423f7c) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #11 DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2341:9 (clickhouse+0x194416c7) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #12 Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1cf17da2) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #13 Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1cf18611) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #14 Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14 (clickhouse+0x1d116d26) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #15 Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x1d11506f) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
    #16 Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27 (clickhouse+0x1d113549) (BuildId: 5a36b42d00c5f99a59f6b74de2b2be8c923472ae)
```

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
TSAN report: https://pastila.nl/?00058334/7adb989784cc8958247f901e9ee3bdec#+YHPzK829YOPhwXO15Ensg==

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

closes #64053

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by yakov-olkhovskiy** [comment]
@kssenii could you please take a look - it's similar to your recent fix https://github.com/ClickHouse/ClickHouse/pull/65744

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 08229390dfa3263853662e0f39fa393f61b95a44 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67341/08229390dfa3263853662e0f39fa393f61b95a44/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/512797a2476491cd836dc565c0af8fac0a5e21e3/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by antaljanosbenjamin** [comment]
I tried to review it, but I am not confident enough in my knowledge to say the final verdict about this PR.

File: src/Server/TCPHandler.cpp [hunk 1]
```diff
@@ -366,7 +366,10 @@ void TCPHandler::runImpl()
         try
         {
             /// If a user passed query-local timeouts, reset socket to initial state at the end of the query
-            SCOPE_EXIT({state.timeout_setter.reset();});
+            SCOPE_EXIT({
+                std::scoped_lock lock(in_mutex, out_mutex);
+                state.timeout_setter.reset();
```
Comment (kssenii) [inline src/Server/TCPHandler.cpp:371]: May be better to just move this `state.timeout_setter.reset()` after this try-catch block and after `state.io.onException();` in the catches? When we would do `state.io.onException()` - we reset the pipeline so the race would not longer happen (storageS3cluster reading threads will be finished on pipeline reset). I guess this race happens only in case when exception is thrown in the `try` code? Because otherwise we will not exit the `try` code unless pipeline is finished, e.g. the race would not happen as well.

Comment (yakov-olkhovskiy) [reply src/Server/TCPHandler.cpp:371]: Please correct me if I'm wrong on the next assumptions.
Technically data race condition happens whenever data is written concurrently without either explicit or implicit memory barrier. It doesn't depend on actual events of concurrency - it's enough to have a concurrent code running on different threads. Thread sanitizer detects actual events, not potential condition - because of this ad-hoc solution which can fix triggered thread sanitizer, do not solve the issue of race condition itself - some other piece of code can easily retrigger sanitizer.
So, regarding this particular case, if these assumptions are correct, maybe it worth fixing the general issue and not a special scenario.

Comment (kssenii) [reply src/Server/TCPHandler.cpp:371]: My proposal also fixes the general case scenario. `in` cannot be used concurrently, but it can now be used by either this TCPHandler thread or by callbacks we set inside this try block. So this is where we have potential data race. But if we finish the pipeline (for example, by calling state.io.onException() in case of exception or by exhausting it by reaching isCompleted) then such race is not possible to happen. There is no other possible data race case on `in` AFAIK.

File: src/Server/TCPHandler.cpp [hunk 2]
```diff
@@ -779,6 +782,8 @@ void TCPHandler::extractConnectionSettingsFromContext(const ContextPtr & context
 
 bool TCPHandler::readDataNext()
 {
+    std::scoped_lock lock(in_mutex);
```
Comment (kssenii) [inline src/Server/TCPHandler.cpp:785]: The linked data race report happens with `DB::TCPHandler::receiveReadTaskResponseAssumeLocked`, it does not go through `readDataNext`, but uses `in` directly, so this will not fix the issue.

Comment (yakov-olkhovskiy) [reply src/Server/TCPHandler.cpp:785]: yes, missed this nuance

File: src/Server/TCPHandler.cpp [hunk 3]
```diff
@@ -630,6 +627,8 @@ void TCPHandler::runImpl()
             state.io.onException();
             exception.reset(e.clone());
 
+            state.timeout_setter.reset();
```
[the remark this answers is not in the document]
Comment (yakov-olkhovskiy) [reply src/Server/TCPHandler.cpp:630]: > Though state.reset() will not be reset in case of is_interserver_mode because we rethrow the exception in this case before resetting the state... So I think better to also reset the timeout right after the last catch of this try block

we rethrow in case of `is_interserver_mode` AND `AUTHENTICATION_FAILED` - which means we don't need to reset after last catch, I guess?

[the remark this answers is not in the document]
Comment (kssenii) [reply src/Server/TCPHandler.cpp:633]: Yes indeed

**Review by kssenii — APPROVED** [review]
