### PR TITLE
Fix error with batch aggregation and -Array combinator

### LINKED ISSUE #13705: A bug in GROUP BY in version 20.7 (unreleased)
**Describe the bug**
```
SELECT number % 100 AS k, sumArray(emptyArrayUInt8()) AS v FROM numbers(10) GROUP BY k
```
Fails under ASan.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Not for changelog. Fix error with batch aggregation and -Array combinator. This fixes #13705.

### CODE REVIEW

File: src/AggregateFunctions/IAggregateFunction.h [hunk 1]
```diff
@@ -388,13 +388,14 @@ class IAggregateFunctionDataHelper : public IAggregateFunctionHelper<Derived>
         {
             for (size_t j = 0; j < UNROLL_COUNT; ++j)
             {
-                if (has_data[j * 256 + k])
+                size_t idx = j * 256 + k;
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/IAggregateFunction.h:391]: These changes are non significant.

File: src/Interpreters/Aggregator.cpp [hunk 2]
```diff
@@ -629,7 +642,7 @@ void NO_INLINE Aggregator::executeOnIntervalWithoutKeyImpl(
 
 
 void Aggregator::prepareAggregateInstructions(Columns columns, AggregateColumns & aggregate_columns, Columns & materialized_columns,
-                                              AggregateFunctionInstructions & aggregate_functions_instructions, NestedColumnsHolder & nested_columns_holder)
+    AggregateFunctionInstructions & aggregate_functions_instructions, NestedColumnsHolder & nested_columns_holder)
```
Comment (alexey-milovidov) [inline src/Interpreters/Aggregator.cpp:645]: These changes are non significant.

File: src/Interpreters/Aggregator.cpp [hunk 3]
```diff
@@ -534,22 +533,36 @@ void NO_INLINE Aggregator::executeImplBatch(
...
-                inst->batch_arguments,
-                aggregates_pool);
+            if (inst->offsets)
+            {
+                has_arrays = true;
+                break;
+            }
+        }
+
+        if (!has_arrays)
```
Comment (alexey-milovidov) [inline src/Interpreters/Aggregator.cpp:547]: This is significant line.

**Comment by alexey-milovidov** [comment]
> Error response from daemon: Get https://registry-1.docker.io/v2/yandex/clickhouse-binary-builder/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Ayandex%2Fclickhouse-binary-builder%3Apull&service=registry.docker.io: EOF

**Comment by alexey-milovidov** [comment]
Integration test - see https://github.com/ClickHouse/ClickHouse/pull/13721
