### PR TITLE
Fix EXISTS not respecting LIMIT and OFFSET in subqueries

### LINKED ISSUE #88722: Regression on EXISTS operator with LIMIT and OFFSET
### Describe the bug

Happens since v25.8.

### How to reproduce

On v25.7: https://fiddle.clickhouse.com/00df07a5-d199-4471-ad95-a8035fdee92e --correct

From v25.8: https://fiddle.clickhouse.com/01415b8f-f0bf-4c0c-a7f0-b8f0ef8c6574 --wrong

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by andriibeee**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fixes a bug where EXISTS would ignore LIMIT and OFFSET clauses in subqueries, causing incorrect results when the subquery returned no rows due to an offset or a zero limit.
Closes #88722.

- [ ] Documentation is written (mandatory for new features)

---

> [!NOTE]
> **Medium Risk**
> Touches EXISTS query-plan optimization by changing when `LimitStep` is stripped, which can alter execution plans and result emptiness semantics for subqueries with `OFFSET`/`LIMIT 0`. Scope is small but in planner/execution path.
> 
> **Overview**
> Fixes a bug where `EXISTS` could return true even when a subquery became empty due to `LIMIT/OFFSET`.
> 
> `optimizePlanForExists` now only removes a `LimitStep` when it cannot affect emptiness (requires `OFFSET = 0` and `LIMIT > 0`); otherwise it keeps the limit in the plan. `LimitStep` exposes `getOffset()` to support this check, and a new stateless regression test covers `EXISTS` with `LIMIT`, `OFFSET`, and `LIMIT 0` edge cases.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit a9376a143f3dd593955d3785403f7d7465493408. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.652`

### CODE REVIEW

File: src/Planner/Utils.cpp [hunk 1]
```diff
@@ -657,13 +657,14 @@ bool optimizePlanForExists(QueryPlan & query_plan)
...
         }
-        if (typeid_cast<LimitStep *>(node->step.get()))
+        if (auto * limit_step = typeid_cast<LimitStep *>(node->step.get()))
         {
-            /// TODO: Support LimitStep in decorrelation process.
-            /// For now, we just remove it, because it only increases the number of rows in the result.
-            /// It doesn't affect the result of correlated subquery.
-            node = node->children[0];
-            continue;
+            if (limit_step->getOffset() == 0 && limit_step->getLimit() > 0)
```
Comment (alexey-milovidov) [inline src/Planner/Utils.cpp:662]: We lost the important comment here.

File: src/Planner/Utils.cpp [hunk 2]
```diff
@@ -657,13 +657,14 @@ bool optimizePlanForExists(QueryPlan & query_plan)
...
+            {
+                node = node->children[0];
```
Comment (alexey-milovidov) [inline src/Planner/Utils.cpp:667]: Btw, I don't understand the original logic here.

File: src/Planner/Utils.cpp (hunk 1 above)
Comment (novikd) [reply src/Planner/Utils.cpp:662]: Agree, it is better to keep the comment

File: src/Planner/Utils.cpp (hunk 2 above)
Comment (novikd) [reply src/Planner/Utils.cpp:667]: Currently, `LimitStep` is not supported by the decorrelation process, because the limit should be applied per subquery input.

However, if we have `EXISTS` subquery, we just need to know if the result set is empty or not for the corresponding subquery inputs. This means we can remove `LimitStep` (if offset is `0`) and the result of `EXISTS` will still be correct.

**Review by novikd — APPROVED** [review]
LGTM, but let's keep the comment

**Comment by zlareb1** [comment]
@andriibeee @alexey-milovidov @novikd this caused regression https://github.com/ClickHouse/ClickHouse/issues/99524
