### PR TITLE
Fix several critical bugs around ThreadPoolCallbackRunnerLocal usage

### LINKED ISSUE #95739: stack-use-after-scope in MergeTreeIndexVectorSimilarity.cpp
```
==4817==ERROR: AddressSanitizer: stack-use-after-scope on address 0xfb4850649b90 at pc 0xab580c911b34 bp 0xfb4990ab3170 sp 0xfb4990ab3168
READ of size 8 at 0xfb4850649b90 thread T1017 (VectorSimIndex)
    #0 0xab580c911b30 in void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'(unsigned long, unsigned long)::operator()(unsigned long, unsigned long) const ci/tmp/build/./src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:331:52
    #1 0xab580c911b30 in void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()::operator()() const ci/tmp/build/./src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:360:71
    #2 0xab580c911b30 in std::__1::__invoke_result_impl<void, void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&>::type std::__1::__invoke[abi:ne210105]<void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&>(void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27
    #3 0xab580c911b30 in void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&>(void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5
    #4 0xab580c911b30 in void std::__1::__invoke_r[abi:ne210105]<void, void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&>(void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10
    #5 0xab580c911b30 in void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<void DB::(anonymous namespace)::updateImpl<DB::ColumnVector<float>>(DB::ColumnArray const*, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, std::__1::shared_ptr<DB::USearchIndexWithSerialization>&, unsigned long, unsigned long)::'lambda'()>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12
    #6 0xab57fb2e3c58 in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
    #7 0xab57fb2e3c58 in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
    #8 0xab57fb2e3c58 in void DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::__1::function<void ()>>::executeCallback<std::__1::function<void ()>>(std::__1::promise<void>&, std::__1::function<void ()>&&, std::__1::shared_ptr<DB::ThreadGroup>, DB::ThreadName) ci/tmp/build/./src/Common/threadPoolCallbackRunner.h:141:17
    #9 0xab57fb2e36f0 in DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::__1::function<void ()>>::enqueueAndGiveOwnership(std::__1::function<void ()>&&, Priority, std::__1::optional<unsigned long>)::'lambda'()::operator()() ci/tmp/build/./src/Common/threadPoolCallbackRunner.h:193:13
    #10 0xab57f7d510bc in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
    #11 0xab57f7d510bc in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
    #12 0xab57f7d510bc in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:801:17
    #13 0xab57f7d5ca18 in std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h
    #14 0xab57f7d5ca18 in decltype(auto) std::__1::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<0ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1380:5
    #15 0xab57f7d5ca18 in decltype(auto) std::__1::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1384:5
    #16 0xab57f7d5ca18 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13
    #17 0xab57f7d4bf38 in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
    #18 0xab57f7d4bf38 in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
    #19 0xab57f7d4bf38 in ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:811:17
    #20 0xab57f7d58e2c in std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h
    #21 0xab57f7d58e2c in void std::__1::__thread_execute[abi:ne210105]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:159:3
    #22 0xab57f7d58e2c in void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:168:3
    #23 0xab57e8d64524 in asan_thread_start(void*) crtstuff.c
    #24 0xff5042010394 in start_thread nptl/pthread_create.c:442:8
    #25 0xff5042079e98  misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:79

Address 0xfb4850649b90 is located in stack of thread T1167 (QueryPipelineEx) at offset 912 in frame
    #0 0xab580c90a08c in DB::MergeTreeIndexAggregatorVectorSimilarity::update(DB::Block const&, unsigned long*, unsigned long) ci/tmp/build/./src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp:369

  This frame has 28 object(s):
    [32, 56) 'agg.tmp'
    [96, 128) 'agg.tmp' (line 364)
    [160, 200) 'runner' (line 328)
    [240, 264) 'add_vector_to_index' (line 329)
    [304, 336) 'ref.tmp' (line 360)
    [368, 392) 'agg.tmp'
    [432, 464) 'agg.tmp' (line 364)
    [496, 536) 'runner' (line 328)
    [576, 600) 'add_vector_to_index' (line 329)
    [640, 672) 'ref.tmp' (line 360)
    [704, 728) 'agg.tmp'
    [768, 800) 'agg.tmp' (line 364)
    [832, 872) 'runner' (line 328)
    [912, 936) 'add_vector_to_index' (line 329) <== Memory access at offset 912 is inside this variable
    [976, 1008) 'ref.tmp' (line 360)
    [1040, 1072) 'agg.tmp'
    [1104, 1112) 'ref.tmp' (line 371)
    [1136, 1168) 'agg.tmp'
    [1200, 1204) 'ref.tmp' (line 382)
    [1216, 1248) 'agg.tmp'
    [1280, 1288) 'column_cut' (line 390)
    [1312, 1344) 'agg.tmp'
    [1376, 1408) 'agg.tmp'
    [1440, 1448) 'dimensions_inserted' (line 402)
    [1472, 1504) 'agg.tmp'
    [1536, 1568) 'agg.tmp'
    [1600, 1632) 'agg.tmp'
    [1664, 1696) 'agg.tmp'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
```

Cc @rschu1ze

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix several critical bugs around ThreadPoolCallbackRunnerLocal usage

This PR addresses critical memory safety bugs around `ThreadPoolCallbackRunnerLocal` usage throughout the codebase. The code issue is that when lambdas capture local variables by reference (`[&]`) and an exception occurs during the enqueue loop, stack unwinding happens before the destructor's `waitForAllToFinish()` is called, causing use-after-scope bugs when worker threads access destroyed stack variables.

Fixes https://github.com/ClickHouse/ClickHouse/issues/95739
I'll do the same for the usages in private too

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.2.1.513`

### CODE REVIEW

File: src/Backups/BackupEntriesCollector.cpp [hunk 1]
```diff
@@ -801,11 +801,13 @@ void BackupEntriesCollector::makeBackupEntriesForTablesData()
         return;
 
     ThreadPoolCallbackRunnerLocal<void> runner(threadpool, ThreadName::BACKUP_COLLECTOR);
-    for (const auto & table_name : table_infos | boost::adaptors::map_keys)
+    /// Using a lambda with references is fine, since it only uses `this` and `it.first` which is part of table_infos (`this`)
+    /// So they will outlive runner even if an exception is thrown
+    for (const auto & it : table_infos)
```
Comment (Algunenano) [inline src/Backups/BackupEntriesCollector.cpp:806]: This was fine, but I changed it so it was clear where the ownership comes from. Having `operator|` with boost made things more complex to understand

File: src/Databases/DataLake/RestCatalog.cpp [hunk 2]
```diff
@@ -389,30 +389,34 @@ bool RestCatalog::empty() const
...
-
     DB::Names tables;
     std::mutex mutex;
 
-    auto execute_for_each_namespace = [&](const std::string & current_namespace)
     {
-        runner.enqueueAndKeepTrack(
-        [=, &tables, &mutex, this]
+        /// Ensure tables and mutex (capture by reference) outlive runner
+        DB::ThreadPoolCallbackRunnerLocal<void> runner(pool, DB::ThreadName::DATALAKE_REST_CATALOG);
```
Comment (Algunenano) [inline src/Databases/DataLake/RestCatalog.cpp:397]: This fixes a critical bug. `tables` and `mutex` had a shorter live than runner, so in case of an exception they would be destroyed before `~runner` was called.

File: src/Disks/DiskObjectStorage/MetadataStorages/PlainRewritable/MetadataStorageFromPlainRewritableObjectStorage.cpp [hunk 3]
```diff
@@ -118,6 +117,7 @@ void MetadataStorageFromPlainRewritableObjectStorage::load(bool is_initial_load,
         }
     }
 
+    ThreadPoolCallbackRunnerLocal<void> runner(pool, ThreadName::PLAIN_REWRITABLE_META_LOAD);
```
Comment (Algunenano) [inline src/Disks/DiskObjectStorage/MetadataStorages/PlainRewritable/MetadataStorageFromPlainRewritableObjectStorage.cpp:120]: This also fixes another critical issue. Log was used by reference but it had a shorter life span than runner

File: src/Disks/DiskObjectStorage/MetadataStorages/PlainRewritable/MetadataStorageFromPlainRewritableObjectStorage.cpp [hunk 4]
```diff
@@ -149,6 +149,13 @@ void MetadataStorageFromPlainRewritableObjectStorage::load(bool is_initial_load,
...
             }
 
+            /// Passing by reference:
+            /// log: Created before runner, so it will be destroyed after
+            /// settings: Same as log
+            /// remove_layout: Same
+            /// remote_layout_mutex: Same
+            /// In any case we have a try {} catch (...) around runner usage, so exceptions will call runner.waitForAllToFinish() first
+            /// Thus the order of destruction of the variables is not important
             runner.enqueueAndKeepTrack([remote_path, object_path = file->getPath(), metadata = file->metadata, &log, &settings, this, &remote_layout, &remote_layout_mutex]
```
Comment (Algunenano) [inline src/Disks/DiskObjectStorage/MetadataStorages/PlainRewritable/MetadataStorageFromPlainRewritableObjectStorage.cpp:159]: Same than above

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 5]
```diff
@@ -2971,22 +2979,27 @@ void MergeTreeData::prewarmCaches(ThreadPool & pool, MarkCachePtr mark_cache, Pr
         columns_to_prewarm_marks = getColumnsToPrewarmMarks(*getSettings(), metadata_snaphost->getColumns().getAllPhysical());
     }
 
-    /// Allocate runner on stack after all used local variables to make its destructor
-    /// is called first and all tasks stopped before local variables are being destroyed.
-    ThreadPoolCallbackRunnerLocal<void> runner(pool, ThreadName::MERGETREE_PREWARM_CACHE);
-
+    /// Created first, so it outlives runner
```
Comment (Algunenano) [inline src/Storages/MergeTree/MergeTreeData.cpp:2984]: Another critical issue here. `enough_space` would be destroyed before `runner`

File: src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp [hunk 6]
```diff
@@ -354,9 +353,11 @@ void updateImpl(const ColumnArray * column_array, const ColumnArray::Offsets & c
 
     size_t index_size = index->size();
 
+    ThreadPoolCallbackRunnerLocal<void> runner(thread_pool, ThreadName::MERGETREE_VECTOR_SIM_INDEX);
     for (size_t row = 0; row < rows; ++row)
     {
         auto key = static_cast<USearchIndex::vector_key_t>(index_size + row);
+        /// Passing add_vector_to_index by refence is safe because it outlives the runner
```
Comment (Algunenano) [inline src/Storages/MergeTree/MergeTreeIndexVectorSimilarity.cpp]: Another critical issue. This one closes https://github.com/ClickHouse/ClickHouse/issues/95739

File: src/Storages/StorageDistributed.cpp [hunk 7]
```diff
@@ -1431,6 +1431,9 @@ void StorageDistributed::initializeFromDisk()
 
     const auto & disks = data_volume->getDisks();
 
+    const auto & paths = getDataPaths();
```
Comment (Algunenano) [inline src/Storages/StorageDistributed.cpp:1434]: Another critical issue here. These variables would be destroyed before runner in case of an exception

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 8]
```diff
@@ -7866,11 +7866,13 @@ void StorageReplicatedMergeTree::fetchPartition(
 
         missing_parts.clear();
 
+        std::mutex missing_parts_mutex; /// Must be created before runner, so it outlives it
```
Comment (Algunenano) [inline src/Storages/StorageReplicatedMergeTree.cpp:7959]: And another one. The mutex needs to outlive fetch_partition_runner
