### PR TITLE
s3queue: fix retries after failed insert

### LINKED ISSUE #70951: S3Queue Failed files stuck in Processing state forever
**Describe what's wrong**

If some file got status Failed (bc of exception returned from MV)
On retries, it just stuck in `Processing` stage forever. 

```
2024-10-20 14:45P:50:058045 [389] {} <Test> StorageObjectStorageQueue(..): Updating state of type=...object... from Failed to Processing
2024-10-20 14:45P:50:058072 [389] {} <Test> StorageObjectStorageQueue(..): File type=...object... has state `Processing`: will not process (processing id version: None)
```

**Does it reproduce on the most recent release?**

Yes, 24.8

**Additional context**

https://github.com/ClickHouse/ClickHouse/blob/fc31ec4404a319607893c8d2012317822f3fe964/src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp#L217

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix retries on failed insert in storage S3(Azure)Queue. Closes https://github.com/ClickHouse/ClickHouse/issues/70951.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [x]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit b6ef1991bfba4239aa2e7bc28271472cb2cbb9b3 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73546/b6ef1991bfba4239aa2e7bc28271472cb2cbb9b3/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/73546/b6ef1991bfba4239aa2e7bc28271472cb2cbb9b3/style_check.html">❌ failure</a></td></tr>
<tbody>
</table>

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp [hunk 1]
```diff
@@ -225,9 +225,12 @@ bool ObjectStorageQueueIFileMetadata::setProcessing()
     auto state = file_status->state.load();
     if (state == FileStatus::State::Processing
         || state == FileStatus::State::Processed
-        || (state == FileStatus::State::Failed && file_status->retries >= max_loading_retries))
+        || (state == FileStatus::State::Failed
+            && file_status->retries
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp:229]: I'm not sure I understand this part, would it be same as checking if `max_loading_retries` is not 0?

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp [hunk 2]
```diff
@@ -322,6 +322,13 @@ void ObjectStorageQueueIFileMetadata::setFailed(const std::string & exception_me
             throw;
         }
     }
+    else
+    {
+        resetProcessing();
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp:327]: I don't see `resetProcessingImpl` implemented for `ObjectStorageQueueOrderedFileMetadata` :eyes:

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueSource.cpp [hunk 3]
```diff
@@ -503,6 +503,9 @@ Chunk ObjectStorageQueueSource::generateImpl()
         auto file_metadata = object_info->file_metadata;
         auto file_status = file_metadata->getFileStatus();
         const auto & path = reader.getObjectInfo()->getPath();
+        last_started_file = file_metadata;
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueSource.cpp:506]: why don't we push instantly to `processed_files`?
In which case do we have it set but not present in `processed_files`?

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp (hunk 2 above)
Comment (kssenii) [reply src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp:327]: Good point

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp [hunk 4]
```diff
@@ -260,13 +264,74 @@ void ObjectStorageQueueIFileMetadata::resetProcessing()
...
+            "No processing id version set, but state is `Processing` ({})",
+            node_metadata.toString());
+    }
+
+    size_t check_processing_id_path_idx = 0;
+    size_t remove_processing_id_path_idx = 1;
+    size_t remove_processing_path_idx = 2;
+
+    Coordination::Requests requests;
+    requests.push_back(zkutil::makeCheckRequest(processing_node_id_path, processing_id_version.value()));
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp:284]: why do you need this check? Remove will fail if it doesn't exist

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp [hunk 5]
```diff
@@ -141,19 +131,13 @@ void ObjectStorageQueueUnorderedFileMetadata::setProcessedImpl(bool remove_proce
...
         request_index[REMOVE_PROCESSING_ID_PATH] = 1;
         request_index[REMOVE_PROCESSING_PATH] = 2;
-
-        if (!remove_processing_nodes_only)
-            request_index[SET_PROCESSED_PATH] = 3;
-    }
-    else if (!remove_processing_nodes_only)
-    {
-        request_index[SET_PROCESSED_PATH] = 0;
+        request_index[SET_PROCESSED_PATH] = 3;
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp:134]: Why you set it here if you will set it to something else right after :confused:

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp [hunk 6]
```diff
@@ -141,19 +131,13 @@ void ObjectStorageQueueUnorderedFileMetadata::setProcessedImpl(bool remove_proce
         request_index[CHECK_PROCESSING_ID_PATH] = 0;
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp:131]: on l125 same comment about unclear check request

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp (hunk 5 above)
Comment (kssenii) [reply src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp:134]: that was accidental - removed `remove_processing_nodes_only` too quickly without properly looking

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp (hunk 4 above)
Comment (kssenii) [reply src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp:284]: Yes, it needs to be removed

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp [hunk 7]
```diff
@@ -260,13 +264,51 @@ void ObjectStorageQueueIFileMetadata::resetProcessing()
...
+            log, "Processing node no longer exists ({}) "
+            "while setting file as non-retriable failed. "
+            "This could be as a result of expired keeper session. "
+            "Cannot set file as failed, will retry.",
+            processing_node_path);
+        chassert(false);
+        return;
+    }
+
+    auto exception = zkutil::KeeperMultiException(code, requests, responses);
```
Comment (antonio2368) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueIFileMetadata.cpp:307]: maybe prefer using `getFailedOpIndex` and directly call `requests[failed_op_idx]->getPath()`
creating an entire `exception` object just to extract a path seems overkill and it confused me

**Review by antonio2368 — APPROVED** [review]

**Comment by kssenii** [comment]
> Integration tests

test_kafka_bad_messages
test_async_insert_adaptive_busy_timeout
