### PR TITLE
Fix `00933_test_fix_extra_seek_on_compressed_cache` in releases.

### LINKED ISSUE #43544: Test `00933_test_fix_extra_seek_on_compressed_cache` is flaky
Example: https://s3.amazonaws.com/clickhouse-test-reports/0/481b9face12511b559ef021e1b032427547dabd7/stateless_tests__asan_.html

https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTA2LTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJTAwOTMzX3Rlc3RfZml4X2V4dHJhX3NlZWtfb25fY29tcHJlc3NlZF9jYWNoZSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

It's interesting that in release branches and backport PRs it fail much more often than in master and ordinary PRs

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Example: https://s3.amazonaws.com/clickhouse-test-reports/47471/a910973a7a265c6a8ce933bc8e19136a0d5eef03/stateless_tests__asan_.html

This closes #43544.

### CODE REVIEW

File: tests/queries/0_stateless/02286_drop_filesystem_cache.sh [hunk 1]
```diff
@@ -16,7 +16,7 @@ for STORAGE_POLICY in 's3_cache' 'local_cache'; do
                                    ORDER BY key
                                    SETTINGS storage_policy='$STORAGE_POLICY', min_bytes_for_wide_part = 10485760"
 
-    $CLICKHOUSE_CLIENT --query "SYSTEM STOP MERGES"
+    $CLICKHOUSE_CLIENT --query "SYSTEM STOP MERGES test_02286"
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02286_drop_filesystem_cache.sh:19]: Here is the error.

**Review by davenger — APPROVED** [review]
