### PR TITLE
Optimising has(), indexOf(), and countEqual() for Array(LowCardinality(T)) and constant right arguments

### LINKED ISSUE #6005: Arrays of LowCardinality are not optimized for function calculations
Arrays of LowCardinality Strings do not use LowCardinality optimisations for string operations.

```
create table test_lc_array (
 s LowCardinality(String),
 a Array(LowCardinality(String)) default array(s)
) Engine = MergeTree 
PARTITION BY tuple()
ORDER BY tuple()
;

insert into test_lc_array (s)
select concat('qwertyuiopasdfghjkl', toString(number%10))
from numbers(100000000)
;  

select count() from test_lc_array where s = 'qwertyuiopasdfghjkl0';

1 rows in set. Elapsed: 0.200 sec. Processed 100.00 million rows, 100.46 MB (501.07 million rows/s., 503.36 MB/s.) 
<Debug> MemoryTracker: Peak memory usage (for query): 2.04 MiB.

select count() from test_lc_array where a[1] = 'qwertyuiopasdfghjkl0';

1 rows in set. Elapsed: 2.033 sec. Processed 100.00 million rows, 900.46 MB (49.19 million rows/s., 442.93 MB/s.) 
<Debug> MemoryTracker: Peak memory usage (for query): 16.74 MiB.

select count() from test_lc_array where has(a, 'qwertyuiopasdfghjkl0');

1 rows in set. Elapsed: 1.136 sec. Processed 100.00 million rows, 900.46 MB (88.06 million rows/s., 792.97 MB/s.) 
 <Debug> MemoryTracker: Peak memory usage (for query): 10.99 MiB.

select count() from test_lc_array where indexOf(a, 'qwertyuiopasdfghjkl0')>0;

1 rows in set. Elapsed: 1.211 sec. Processed 100.00 million rows, 900.46 MB (82.60 million rows/s., 743.81 MB/s.) 
<Debug> MemoryTracker: Peak memory usage (for query): 12.74 MiB.
```

### LINKED ISSUE #10880: Array(LowCardinality(String)) has() function slower
hello,

I store the  exp_id list in an Array using Array(LowCardinality(String)) for our A/B test 。 
example exps  array data:  ['zeyudu_rec_6096_1','default','zeyudu_rec_6096_2','zeyudu_rec_6096_3',....]
     
My Query:
```
SELECT
    multiIf(has(exps_lowcard, 'zeyudu_rec_6096_1'), 'control', has(exps_lowcard, 'zeyudu_rec_6096_2'), '6096_2', 'other') AS expr_model_v20,
    SUM(multiIf(windowType = 'CLICK', ((((4 * hasFollow) + hasLike) + hasComment) + (4 * hasShare)) + hasCollect, NULL) * SampleWeight) AS `SUM(ces)`
FROM default.explore_feed_bitmap
GROUP BY expr_model_v20
```

result:  1.1E rows  taken 34 seconds

I make anther test : 
       I manage  an  external exp_id dictionay and then store the exp_id list  like  [1001,3001,4002,6001,6002.....]  
 
test query:
```
SELECT
    multiIf(has(exps_array, 6001), 'control', has(exps_array, 6002), '6002', 'other') AS expr_model_v20,
    SUM(multiIf(windowType = 'CLICK', ((((4 * hasFollow) + hasLike) + hasComment) + (4 * hasShare)) + hasCollect, NULL) * SampleWeight) AS `SUM(ces)`
FROM default.explore_feed_bitmap
GROUP BY expr_model_v20
```
result: 1.1E rows  taken 3.2 seconds ,  

clickhouser version: 19.17.4.11  

can you help check this issue. I think the LowCardinality Array should has the close performance with an Array stores Int。  

If you need more information,  I will update .

thanks
johnny

### LINKED ISSUE #13392: countEqual: PODArray.h:342: Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) ... failed
```
SELECT countEqual(materialize([null AS x, 1]), materialize(x))

clickhouse-server: /home/akuzm/ch2/ch/src/Common/PODArray.h:342: const T &DB::PODArray<char8_t, 4096, Allocator<false, false>, 15, 16>::operator[](ssize_t) const [T = char8_t, initial_bytes = 4096, TAllocator = Allocator<false, false>, pad_right_ = 15, pad_left_ = 16]: Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))' failed.
2020.08.06 00:27:42.648640 [ 444733 ] {} <Trace> BaseDaemon: Received signal 6
2020.08.06 00:27:42.658561 [ 444825 ] {} <Fatal> BaseDaemon: ########################################
2020.08.06 00:27:42.664533 [ 444825 ] {} <Fatal> BaseDaemon: (version 20.7.1.1, build id: D3FC167BA205D4A1) (from thread 444804) (query_id: 88d7de8e-f9c7-42cd-a1ee-3057cebde663) Received signal Aborted (6)
2020.08.06 00:27:42.664869 [ 444825 ] {} <Fatal> BaseDaemon: 
2020.08.06 00:27:42.665424 [ 444825 ] {} <Fatal> BaseDaemon: Stack trace: 0x7efdd8c3d18b 0x7efdd8c1c859 0x7efdd8c1c729 0x7efdd8c2df36 0x7efdd787723d 0x7efdd292852f 0x7efdc45426d0 0x7efdc4541b75 0x7efdc44b2f97 0x7efdc44b088a 0x7efdc44b00bf 0x7efdd28aea2f 0x7efdd30deffb 0x7efdd30e00cd 0x7efdcb964483 0x7efdcb967bb3 0x7efdc73de9dc 0x7efdca060035 0x7efdc7ea3eea 0x7efdc7ce632c 0x7efdc7ce628f 0x7efdc7ce624d 0x7efdc7ce61fd 0x7efdc7ce61cd 0x7efdc7ce531e 0x7efddd3a78c5 0x7efddd3a7865 0x7efdc7ce3c35
2020.08.06 00:27:42.666139 [ 444825 ] {} <Fatal> BaseDaemon: 4. /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.06 00:27:42.666653 [ 444825 ] {} <Fatal> BaseDaemon: 5. /build/glibc-YYA7BZ/glibc-2.31/stdlib/abort.c:81: __GI_abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.06 00:27:42.667310 [ 444825 ] {} <Fatal> BaseDaemon: 6. /build/glibc-YYA7BZ/glibc-2.31/intl/loadmsgcat.c:509: _nl_load_domain.cold @ 0x25729 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.06 00:27:42.674461 [ 444825 ] {} <Fatal> BaseDaemon: 7. ? @ 0x36f36 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.06 00:27:42.678103 [ 444825 ] {} <Fatal> BaseDaemon: 8. /home/akuzm/ch2/ch/src/Common/PODArray.h:0: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>::operator[](long) const @ 0x25bd23d in /home/akuzm/ch2/build-clang10/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so
2020.08.06 00:27:42.686531 [ 444825 ] {} <Fatal> BaseDaemon: 9. /home/akuzm/ch2/ch/src/Columns/ColumnVector.h:190: DB::ColumnVector<char8_t>::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x292a52f in /home/akuzm/ch2/build-clang10/src/Functions/libclickhouse_functionsd.so
2020.08.06 00:27:42.731203 [ 444825 ] {} <Fatal> BaseDaemon: 10. /home/akuzm/ch2/ch/src/Functions/array/arrayIndex.h:511: DB::ArrayIndexGenericImpl<DB::IndexCount, false>::vectorCase4(DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) @ 0x8606d0 in /home/akuzm/ch2/build-clang10/src/Functions/array/libclickhouse_functions_arrayd.so
2020.08.06 00:27:42.767709 [ 444825 ] {} <Fatal> BaseDaemon: 11. /home/akuzm/ch2/ch/src/Functions/array/arrayIndex.h:0: DB::ArrayIndexGenericImpl<DB::IndexCount, false>::vector(DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x85fb75 in /home/akuzm/ch2/build-clang10/src/Functions/array/libclickhouse_functions_arrayd.so
2020.08.06 00:27:42.779483 [ 444825 ] {} <Fatal> BaseDaemon: 12. /home/akuzm/ch2/ch/src/Functions/array/arrayIndex.h:841: DB::FunctionArrayIndex<DB::IndexCount, DB::NameCountEqual>::executeGeneric(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const @ 0x7d0f97 in /home/akuzm/ch2/build-clang10/src/Functions/array/libclickhouse_functions_arrayd.so
2020.08.06 00:27:42.783997 [ 444825 ] {} <Fatal> BaseDaemon: 13. /home/akuzm/ch2/ch/src/Functions/array/arrayIndex.h:990: DB::FunctionArrayIndex<DB::IndexCount, DB::NameCountEqual>::perform(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const @ 0x7ce88a in /home/akuzm/ch2/build-clang10/src/Functions/array/libclickhouse_functions_arrayd.so
2020.08.06 00:27:42.798702 [ 444825 ] {} <Fatal> BaseDaemon: 14. /home/akuzm/ch2/ch/src/Functions/array/arrayIndex.h:977: DB::FunctionArrayIndex<DB::IndexCount, DB::NameCountEqual>::executeImpl(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) const @ 0x7ce0bf in /home/akuzm/ch2/build-clang10/src/Functions/array/libclickhouse_functions_arrayd.so
2020.08.06 00:27:42.799962 [ 444825 ] {} <Fatal> BaseDaemon: 15. /home/akuzm/ch2/ch/src/Functions/IFunctionAdaptors.h:152: DB::DefaultExecutable::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) @ 0x28b0a2f in /home/akuzm/ch2/build-clang10/src/Functions/libclickhouse_functionsd.so
2020.08.06 00:27:42.803910 [ 444825 ] {} <Fatal> BaseDaemon: 16. /home/akuzm/ch2/ch/src/Functions/IFunction.cpp:326: DB::ExecutableFunctionAdaptor::executeWithoutLowCardinalityColumns(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) @ 0x30e0ffb in /home/akuzm/ch2/build-clang10/src/Functions/libclickhouse_functionsd.so
2020.08.06 00:27:42.817062 [ 444825 ] {} <Fatal> BaseDaemon: 17. /home/akuzm/ch2/ch/src/Functions/IFunction.cpp:486: DB::ExecutableFunctionAdaptor::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) @ 0x30e20cd in /home/akuzm/ch2/build-clang10/src/Functions/libclickhouse_functionsd.so
2020.08.06 00:27:42.823957 [ 444825 ] {} <Fatal> BaseDaemon: 18. /home/akuzm/ch2/ch/src/Interpreters/ExpressionActions.cpp:365: DB::ExpressionAction::execute(DB::Block&, bool) const @ 0x122c483 in /home/akuzm/ch2/build-clang10/src/libclickhouse_interpretersd.so
2020.08.06 00:27:42.826630 [ 444825 ] {} <Fatal> BaseDaemon: 19. /home/akuzm/ch2/ch/src/Interpreters/ExpressionActions.cpp:684: DB::ExpressionActions::execute(DB::Block&, bool) const @ 0x122fbb3 in /home/akuzm/ch2/build-clang10/src/libclickhouse_interpretersd.so
2020.08.06 00:27:42.827838 [ 444825 ] {} <Fatal> BaseDaemon: 20. /home/akuzm/ch2/ch/src/Processors/Transforms/ExpressionTransform.cpp:41: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x25e9dc in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_transformsd.so
2020.08.06 00:27:42.846966 [ 444825 ] {} <Fatal> BaseDaemon: 21. /home/akuzm/ch2/ch/src/Processors/ISimpleTransform.h:43: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0xa96035 in /home/akuzm/ch2/build-clang10/src/libclickhouse_storagesd.so
2020.08.06 00:27:42.847879 [ 444825 ] {} <Fatal> BaseDaemon: 22. /home/akuzm/ch2/ch/src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x18eeea in /home/akuzm/ch2/build-clang10/src/libclickhouse_processorsd.so
2020.08.06 00:27:42.855219 [ 444825 ] {} <Fatal> BaseDaemon: 23. /home/akuzm/ch2/ch/src/Processors/Executors/PipelineExecutor.cpp:78: DB::executeJob(DB::IProcessor*) @ 0x13132c in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
2020.08.06 00:27:42.856128 [ 444825 ] {} <Fatal> BaseDaemon: 24. /home/akuzm/ch2/ch/src/Processors/Executors/PipelineExecutor.cpp:95: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const @ 0x13128f in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
2020.08.06 00:27:42.857007 [ 444825 ] {} <Fatal> BaseDaemon: 25. /home/akuzm/ch2/ch/contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x13124d in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
2020.08.06 00:27:42.857881 [ 444825 ] {} <Fatal> BaseDaemon: 26. /home/akuzm/ch2/ch/contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1311fd in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
2020.08.06 00:27:42.858739 [ 444825 ] {} <Fatal> BaseDaemon: 27. /home/akuzm/ch2/ch/contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x1311cd in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
2020.08.06 00:27:42.859589 [ 444825 ] {} <Fatal> BaseDaemon: 28. /home/akuzm/ch2/ch/contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x13031e in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
2020.08.06 00:27:42.863662 [ 444825 ] {} <Fatal> BaseDaemon: 29. /home/akuzm/ch2/ch/contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x1d68c5 in /home/akuzm/ch2/build-clang10/programs/server/libclickhouse-server-libd.so
2020.08.06 00:27:42.867753 [ 444825 ] {} <Fatal> BaseDaemon: 30. /home/akuzm/ch2/ch/contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x1d6865 in /home/akuzm/ch2/build-clang10/programs/server/libclickhouse-server-libd.so
2020.08.06 00:27:42.868542 [ 444825 ] {} <Fatal> BaseDaemon: 31. /home/akuzm/ch2/ch/src/Processors/Executors/PipelineExecutor.cpp:559: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x12ec35 in /home/akuzm/ch2/build-clang10/src/libclickhouse_processors_executorsd.so
```

### LINKED ISSUE #13576: Bad cast from type DB::ColumnNothing to DB::ColumnString
```
SELECT has(materialize(['bbbbbb\0b', NULL]), materialize(NULL))

[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.009029 [ 254 ] <Fatal> BaseDaemon: ########################################
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.009462 [ 254 ] <Fatal> BaseDaemon: (version 20.8.1.4327, build id: 3F5D7E4E592D8D67) (from thread 252) (query_id: 4102f664-45a8-4755-9523-045562b22768) Received signal Aborted (6)
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.009632 [ 254 ] <Fatal> BaseDaemon: 
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.009835 [ 254 ] <Fatal> BaseDaemon: Stack trace: 0x7f7d5e357f47 0x7f7d5e3598b1 0x7f7d5e34942a 0x7f7d5e3494a2 0x17f2f9f1 0x1819a044 0x1f4a88b0 0x1d57338c 0x1d572855 0x1d4e7fa7 0x1d4e594a 0x1d4e51ad 0x195235bf 0x1958b19b 0x1958c27d 0x1fa9dcc1 0x1faa1453 0x20bd17cc 0x20288a55 0x20948eca 0x209a54ac 0x209a540f 0x209a53cd 0x209a537d 0x209a534d 0x209a44ae 0x17f52735 0x17f51655
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.010205 [ 254 ] <Fatal> BaseDaemon: 4. /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51: raise @ 0x3ef47 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.010499 [ 254 ] <Fatal> BaseDaemon: 5. /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81: __GI_abort @ 0x408b1 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.010732 [ 254 ] <Fatal> BaseDaemon: 6. /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89: __assert_fail_base @ 0x3042a in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.011171 [ 254 ] <Fatal> BaseDaemon: 7. ? @ 0x304a2 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.011551 [ 254 ] <Fatal> BaseDaemon: 8. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:48: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x17f2f9f1 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.014577 [ 254 ] <Fatal> BaseDaemon: 9. /build/obj-x86_64-linux-gnu/../src/Common/assert_cast.h:47: DB::ColumnString const& assert_cast<DB::ColumnString const&, DB::IColumn const&>(DB::IColumn const&) @ 0x1819a044 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.055259 [ 254 ] <Fatal> BaseDaemon: 10. /build/obj-x86_64-linux-gnu/../src/Columns/ColumnString.h:223: DB::ColumnString::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x1f4a88b0 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.087783 [ 254 ] <Fatal> BaseDaemon: 11. /build/obj-x86_64-linux-gnu/../src/Functions/array/arrayIndex.h:511: DB::ArrayIndexGenericImpl<DB::IndexToOne, false>::vectorCase4(DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) @ 0x1d57338c in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.121014 [ 254 ] <Fatal> BaseDaemon: 12. /build/obj-x86_64-linux-gnu/../src/Functions/array/arrayIndex.h:0: DB::ArrayIndexGenericImpl<DB::IndexToOne, false>::vector(DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x1d572855 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.147898 [ 254 ] <Fatal> BaseDaemon: 13. /build/obj-x86_64-linux-gnu/../src/Functions/array/arrayIndex.h:841: DB::FunctionArrayIndex<DB::IndexToOne, DB::NameHas>::executeGeneric(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const @ 0x1d4e7fa7 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.173993 [ 254 ] <Fatal> BaseDaemon: 14. /build/obj-x86_64-linux-gnu/../src/Functions/array/arrayIndex.h:990: DB::FunctionArrayIndex<DB::IndexToOne, DB::NameHas>::perform(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const @ 0x1d4e594a in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.200296 [ 254 ] <Fatal> BaseDaemon: 15. /build/obj-x86_64-linux-gnu/../src/Functions/array/arrayIndex.h:977: DB::FunctionArrayIndex<DB::IndexToOne, DB::NameHas>::executeImpl(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) const @ 0x1d4e51ad in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.206417 [ 254 ] <Fatal> BaseDaemon: 16. /build/obj-x86_64-linux-gnu/../src/Functions/IFunctionAdaptors.h:152: DB::DefaultExecutable::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) @ 0x195235bf in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.212449 [ 254 ] <Fatal> BaseDaemon: 17. /build/obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:326: DB::ExecutableFunctionAdaptor::executeWithoutLowCardinalityColumns(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) @ 0x1958b19b in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.217997 [ 254 ] <Fatal> BaseDaemon: 18. /build/obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:486: DB::ExecutableFunctionAdaptor::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) @ 0x1958c27d in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.258414 [ 254 ] <Fatal> BaseDaemon: 19. /build/obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:365: DB::ExpressionAction::execute(DB::Block&, bool) const @ 0x1fa9dcc1 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.300618 [ 254 ] <Fatal> BaseDaemon: 20. /build/obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:684: DB::ExpressionActions::execute(DB::Block&, bool) const @ 0x1faa1453 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.353500 [ 254 ] <Fatal> BaseDaemon: 21. /build/obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:41: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x20bd17cc in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.400610 [ 254 ] <Fatal> BaseDaemon: 22. /build/obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:43: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x20288a55 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.449961 [ 254 ] <Fatal> BaseDaemon: 23. /build/obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x20948eca in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.498091 [ 254 ] <Fatal> BaseDaemon: 24. /build/obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:78: DB::executeJob(DB::IProcessor*) @ 0x209a54ac in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.548950 [ 254 ] <Fatal> BaseDaemon: 25. /build/obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:95: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const @ 0x209a540f in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.599582 [ 254 ] <Fatal> BaseDaemon: 26. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x209a53cd in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.651028 [ 254 ] <Fatal> BaseDaemon: 27. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x209a537d in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.701525 [ 254 ] <Fatal> BaseDaemon: 28. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x209a534d in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.753390 [ 254 ] <Fatal> BaseDaemon: 29. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x209a44ae in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.754032 [ 254 ] <Fatal> BaseDaemon: 30. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x17f52735 in /workspace/clickhouse
[linux-ubuntu-14-04-trusty] 2020.08.10 03:22:06.754411 [ 254 ] <Fatal> BaseDaemon: 31. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x17f51655 in /workspace/clickhouse
Error on processing query: SELECT has(materialize(['bbbbbb\0b', NULL]), materialize(NULL))

```

https://clickhouse-test-reports.s3.yandex.net/13495/3b9f5a827c5ee1d8c5376a8948ecf97516092978/fuzzer/fuzzer.log

### LINKED ISSUE #13917: Bad cast from type DB::ColumnNothing to DB::ColumnString assertion failed
```sql
SELECT [100, NULL, 1048575, 0.5, NULL, NULL], has(materialize(['', NULL, '', '', '']), materialize(NULL))
```
```bash
2020.08.20 14:48:08.253558 [ 35345 ] {9e364f20-0959-4230-abea-beff566d9286} <Error> : Logical error: 'Bad cast from type DB::ColumnNothing to DB::ColumnString'.
clickhouse: ../src/Common/Exception.cpp:45: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
2020.08.20 14:48:08.254004 [ 35241 ] {} <Trace> BaseDaemon: Received signal 6
2020.08.20 14:48:08.254358 [ 35502 ] {} <Fatal> BaseDaemon: ########################################
2020.08.20 14:48:08.254717 [ 35502 ] {} <Fatal> BaseDaemon: (version 20.8.1.1, build id: 8924309CF00424A4) (from thread 35345) (query_id: 9e364f20-0959-4230-abea-beff566d9286) Received signal Aborted (6)
2020.08.20 14:48:08.254923 [ 35502 ] {} <Fatal> BaseDaemon: 
2020.08.20 14:48:08.255094 [ 35502 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fda15ec218b 0x7fda15ea1859 0x7fda15ea1729 0x7fda15eb2f36 0x183349f1 0x1859d444 0x1f96ae60 0x1d987f5c 0x1d987425 0x1d8fcb77 0x1d8fa51a 0x1d8f9d7d 0x1993540f 0x1999cfcb 0x1999e0ad 0x1ffa9a41 0x1ffad1d3 0x210fdb9c 0x207a9d55 0x20e722a8 0x20ed236c 0x20ed22cf 0x20ed228d 0x20ed223d 0x20ed220d 0x20ed136e 0x18357735 0x18356655
2020.08.20 14:48:08.256857 [ 35502 ] {} <Fatal> BaseDaemon: 4. /build/glibc-YYA7BZ/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x4618b in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.20 14:48:08.257419 [ 35502 ] {} <Fatal> BaseDaemon: 5. /build/glibc-YYA7BZ/glibc-2.31/stdlib/abort.c:81: abort @ 0x25859 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.20 14:48:08.258151 [ 35502 ] {} <Fatal> BaseDaemon: 6. /build/glibc-YYA7BZ/glibc-2.31/intl/loadmsgcat.c:509: _nl_load_domain.cold @ 0x25729 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.20 14:48:08.258492 [ 35502 ] {} <Fatal> BaseDaemon: 7. ? @ 0x36f36 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
2020.08.20 14:48:08.258754 [ 35502 ] {} <Fatal> BaseDaemon: 8. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Common/Exception.cpp:48: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x183349f1 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.260954 [ 35502 ] {} <Fatal> BaseDaemon: 9. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Common/assert_cast.h:47: DB::ColumnString const& assert_cast<DB::ColumnString const&, DB::IColumn const&>(DB::IColumn const&) @ 0x1859d444 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.292489 [ 35502 ] {} <Fatal> BaseDaemon: 10. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Columns/ColumnString.h:223: DB::ColumnString::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x1f96ae60 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.317481 [ 35502 ] {} <Fatal> BaseDaemon: 11. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/array/arrayIndex.h:511: DB::ArrayIndexGenericImpl<DB::IndexToOne, false>::vectorCase4(DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) @ 0x1d987f5c in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.342336 [ 35502 ] {} <Fatal> BaseDaemon: 12. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/array/arrayIndex.h:0: DB::ArrayIndexGenericImpl<DB::IndexToOne, false>::vector(DB::IColumn const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x1d987425 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.362049 [ 35502 ] {} <Fatal> BaseDaemon: 13. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/array/arrayIndex.h:841: DB::FunctionArrayIndex<DB::IndexToOne, DB::NameHas>::executeGeneric(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const @ 0x1d8fcb77 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.381610 [ 35502 ] {} <Fatal> BaseDaemon: 14. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/array/arrayIndex.h:990: DB::FunctionArrayIndex<DB::IndexToOne, DB::NameHas>::perform(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const @ 0x1d8fa51a in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.401617 [ 35502 ] {} <Fatal> BaseDaemon: 15. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/array/arrayIndex.h:977: DB::FunctionArrayIndex<DB::IndexToOne, DB::NameHas>::executeImpl(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) const @ 0x1d8f9d7d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.406696 [ 35502 ] {} <Fatal> BaseDaemon: 16. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/IFunctionAdaptors.h:152: DB::DefaultExecutable::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long) @ 0x1993540f in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.411046 [ 35502 ] {} <Fatal> BaseDaemon: 17. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/IFunction.cpp:326: DB::ExecutableFunctionAdaptor::executeWithoutLowCardinalityColumns(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) @ 0x1999cfcb in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.415358 [ 35502 ] {} <Fatal> BaseDaemon: 18. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Functions/IFunction.cpp:486: DB::ExecutableFunctionAdaptor::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) @ 0x1999e0ad in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.445813 [ 35502 ] {} <Fatal> BaseDaemon: 19. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Interpreters/ExpressionActions.cpp:365: DB::ExpressionAction::execute(DB::Block&, bool) const @ 0x1ffa9a41 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.476374 [ 35502 ] {} <Fatal> BaseDaemon: 20. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Interpreters/ExpressionActions.cpp:684: DB::ExpressionActions::execute(DB::Block&, bool) const @ 0x1ffad1d3 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.515426 [ 35502 ] {} <Fatal> BaseDaemon: 21. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Transforms/ExpressionTransform.cpp:41: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x210fdb9c in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.551551 [ 35502 ] {} <Fatal> BaseDaemon: 22. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/ISimpleTransform.h:43: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x207a9d55 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.589600 [ 35502 ] {} <Fatal> BaseDaemon: 23. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x20e722a8 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.627165 [ 35502 ] {} <Fatal> BaseDaemon: 24. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:78: DB::executeJob(DB::IProcessor*) @ 0x20ed236c in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.664775 [ 35502 ] {} <Fatal> BaseDaemon: 25. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../src/Processors/Executors/PipelineExecutor.cpp:95: DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const @ 0x20ed22cf in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.703204 [ 35502 ] {} <Fatal> BaseDaemon: 26. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/type_traits:3519: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x20ed228d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.741536 [ 35502 ] {} <Fatal> BaseDaemon: 27. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x20ed223d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.780169 [ 35502 ] {} <Fatal> BaseDaemon: 28. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:1540: std::__1::__function::__alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x20ed220d in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.818795 [ 35502 ] {} <Fatal> BaseDaemon: 29. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0>, void ()>::operator()() @ 0x20ed136e in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.819258 [ 35502 ] {} <Fatal> BaseDaemon: 30. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:1867: std::__1::__function::__value_func<void ()>::operator()() const @ 0x18357735 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
2020.08.20 14:48:08.819909 [ 35502 ] {} <Fatal> BaseDaemon: 31. /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/../contrib/libcxx/include/functional:2473: std::__1::function<void ()>::operator()() const @ 0x18356655 in /home/jakalletti/ClickHouse/ClickHouse/build-clang-debug/programs/clickhouse
```
From https://clickhouse-test-reports.s3.yandex.net/13624/00fde75e2bd00a9d1fcba81c5442f07d5aab3612/fuzzer/fuzzer.log#fail1

### PR DESCRIPTION
**Pull request by myrrc**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize `has()`, `indexOf()` and `countEqual()` functions for `Array(LowCardinality(T))` and constant right arguments.

The `arrayIndex.h` holding aforementioned functions doesn't have the specialization for `Array(LowCardinality(T))` arguments, so they are converted to ordinary columns, which disables the ability to search in their dictionary (useful for constant right arguments). 

Also fixes the unsigned insert/select bug, see the test (inserting -1 into unsigned columns) for detail.

Resolves #6005
Resolves #13392
Resolves #13917
Resolves #10880
Resolves #13576

### CODE REVIEW

**Comment by myrrc** [comment]
Known caveats (why this PR is still a draft):
The LC column we receive is const, so we cant' call `ReverseIndex::getInsertionPoint` as it modifies the index if it's not present.
So I added the[ const](https://github.com/ClickHouse/ClickHouse/pull/12550/files#diff-afa36e4dc3bd7bc4fea86a88ff11d1e3R524) method which throws on such condition. 
The problem is, it happens pretty often, and I think there must be another way to do that.

File: src/Columns/ReverseIndex.h [hunk 1]
```diff
@@ -325,9 +325,16 @@ class ReverseIndex
     static constexpr bool use_saved_hash = !is_numeric_column;
 
     UInt64 insert(const StringRef & data);
+
+    /// If index is not built, builds it.
     UInt64 getInsertionPoint(const StringRef & data);
+
+    /// Returns the found index if the #index is built, otherwise, searches for it linearly.
```
Comment (Enmk) [inline src/Columns/ReverseIndex.h:332]: Not true, it only does a hash-based lookup

File: src/Functions/array/arrayIndex.h [hunk 2]
```diff
@@ -45,8 +53,13 @@ struct IndexCount
...
 };
 
+/**
+ * Impls -- how to perform the search depending on the arguments data types.
+ * They usually provide methods @e vector (for processing ordinary columns), @e vector_const (for processing
+ * ConstColumn s), and @e vectorVector for processing vectors of vectors.
+ */
 
-template <typename T, typename U, typename IndexConv>
+template <class Initial, class Result, class ConcreteAction, bool ResizeRes = true>
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:62]: Imo, it could be a bit better to give template parameters more descriptive names:
Initial -> LhsValueType
Result -> RhsValueType
ResizeRes -> ResizeResultColumn

File: src/Functions/array/arrayIndex.h [hunk 3]
```diff
@@ -55,9 +68,23 @@ struct ArrayIndexNumImpl
...
+
+    static Initial extract(const IColumn & a, size_t i)
+    {
+        if constexpr (std::is_same_v<Initial, Float32>)
+            return a.getFloat32(i);
+        if constexpr (std::is_same_v<Initial, Float64>)
+            return a.getFloat64(i);
+        if constexpr (is_signed_v<Initial>)
+            return a.getInt(i);
+        return a.getUInt(i);
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:86]: Please make sure that there is no way to instantiate `extract` with `Initial` = `String`

File: src/Functions/array/arrayIndex.h [hunk 4]
```diff
@@ -574,94 +624,247 @@ struct ArrayIndexGenericNullImpl
...
+            col_array_nested_lc = checkAndGetColumn<ColumnLowCardinality>(
+                    &col_array_nested_nullable->getNestedColumn());
+
+            if (!col_array_nested_lc)
+                return false;
         }
 
-        const auto item_arg = block.getByPosition(arguments[1]).column.get();
+        auto col_res = ResultColumnType::create();
+        col_res->getData().resize_fill(col_array->getOffsets().size()); /// fill with default values
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:818]: IMO there is very little sense in pre-filling data with default (zero) values since we are going to overwrite those anyway in `ArrayIndexNumImpl::vectorCaseX`
Also that (with `ArrayIndexNumImpl`'s template parameter `ResizeRes`) add needless complexity.

**Review by Enmk — CHANGES_REQUESTED** [review]
Needs a better changelog entry, like: 
> optimized has(), indexOf(), and countEqual() for columns of `Array(LowCardinality(X))` types (where `X` can be `Nullable` or any other combination of types).

Needs some tests: stateless SQL-tests and performance-tests
There are also some questionable constructs here and there, please see comments inline.

File: src/Functions/array/arrayIndex.h [hunk 5]
```diff
@@ -574,94 +624,247 @@ struct ArrayIndexGenericNullImpl
...
-    DataTypePtr data_type1 = removeNullable(type1);
-
-    return ((isNativeNumber(data_type0) || isEnum(data_type0)) && isNativeNumber(data_type1))
-        || data_type0->equals(*data_type1);
+    /**
+     * Possible cases for #arg and #array_inner_type:
+     * 1. T
+     * 2. LC(T)
+     * 3. N(T)
+     * 4. N(LC(T)) -- quite strange, rarely found but possible.
```
Comment (KochetovNicolai) [inline src/Functions/array/arrayIndex.h:637]: This is not possible. `DataTypeLowCardinality::canBeInsideNullable()` returns `false` and this is checked in `DataTypeNullable::DataTypeNullable`.

File: src/Functions/array/arrayIndex.h [hunk 6]
```diff
@@ -574,94 +624,247 @@ struct ArrayIndexGenericNullImpl
...
+    using ResultType = typename ConcreteAction::ResultType;
+    using ResultColumnType = ColumnVector<ResultType>;
+
+    /**
+     * The Array's internal data type may be quite tricky (containing a Nullable type somewhere). To process the 
+     * Nullable types correctly, for each data type specialisation we provide two null maps (one for the data and one 
+     * for the items). By convention they are passed as the third and the fourth argument, respectively 
+     * (counting from 1).
+     *
+     * @return {nullptr, nullptr} if there are less then 3 arguments.
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:676]: typo th**e**n instead of th**a**n

File: src/Functions/array/arrayIndex.h [hunk 7]
```diff
@@ -574,94 +624,247 @@ struct ArrayIndexGenericNullImpl
...
+     * @return {null_map_data, nullptr} if there are three arguments
+     * @return {nullptr, null_map_item} if there are four arguments but the third is missing.
+     * @return {null_map_data, null_map_item} if there are four arguments.
+     */
+    std::pair<
+        const PaddedPODArray<UInt8> *,
+        const PaddedPODArray<UInt8> *>
+        nullMapsBuilder(const Block& block, const ColumnNumbers & arguments) const noexcept
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:684]: Why is it 'builder' if it doesn't build anything? at most, it 'gets' or 'extracts''

File: src/Functions/array/arrayIndex.h [hunk 8]
```diff
@@ -574,94 +624,247 @@ struct ArrayIndexGenericNullImpl
...
             return false;
 
         auto col_res = ResultColumnType::create();
 
-        /// Null maps of the 1st and second function arguments,
-        /// if it applies.
-        const PaddedPODArray<UInt8> * null_map_data = nullptr;
-        const PaddedPODArray<UInt8> * null_map_item = nullptr;
+        const auto [null_map_data, null_map_item] = nullMapsBuilder(block, arguments);
+        const IColumn* item_arg = block.getByPosition(arguments[1]).column.get();
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:741]: also, it is quite irritating to have multiple names for same thing.
e.g. in indexOf(haystack, needle)
* haystack is called: array and data, 
* needle is called: arg, item, rhs, value.

Could you please peek one?

File: src/Functions/array/arrayIndex.h [hunk 9]
```diff
@@ -574,94 +624,247 @@ struct ArrayIndexGenericNullImpl
...
+            }
+
+            const StringRef elem = col_arg->getDataAt(i);
+            const std::optional<UInt64> value_index = col_array_nested_lc->getDictionary().getOrFindIndex(elem);
+
+            if (!value_index)
+                continue; /// position already zeroed out
+
+            ArrayIndexNumImpl<
+                /* Initial data type -- DB::ReverseIndex index */ UInt64,
```
Comment (Enmk) [inline src/Functions/array/arrayIndex.h:848]: This form of annotating template parameters looks alien to the codebase, I mostly see something like:
```
Type, /* comment */
```

rather than
```
/* comment */ Type, 
```

File: src/Columns/ColumnUnique.h [hunk 10]
```diff
@@ -109,16 +108,30 @@ class ColumnUnique final : public COWHelper<IColumnUnique, ColumnUnique<ColumnTy
         return false;
     }
 
-    const UInt64 * tryGetSavedHash() const override { return index.tryGetSavedHash(); }
+    const UInt64 * tryGetSavedHash() const override { return reverse_index.tryGetSavedHash(); }
 
     UInt128 getHash() const override { return hash.getHash(*getRawColumnPtr()); }
 
-private:
+    inline std::optional<UInt64> getOrFindIndex(const StringRef& value) const override
```
[the remark this answers is not in the document]
Comment (myrrc) [reply src/Columns/ColumnUnique.h:115]: It's the same as the `reverse_index`'s value type.

File: src/Columns/ReverseIndex.h (hunk 1 above)
Comment (myrrc) [reply src/Columns/ReverseIndex.h:332]: Yup, forgot to replace the comment.

File: src/Functions/array/arrayIndex.h (hunk 3 above)
Comment (myrrc) [reply src/Functions/array/arrayIndex.h:86]: It's the *NumImpl, so it's a pre-condition to invoke it with integral `Initial` and `Result` template parameters only.

File: src/Functions/array/arrayIndex.h (hunk 4 above)
Comment (myrrc) [reply src/Functions/array/arrayIndex.h:818]: Ok, agree.

File: src/Functions/array/arrayIndex.h (hunk 8 above)
Comment (myrrc) [reply src/Functions/array/arrayIndex.h:741]: It's the original author's decision, not mine.

File: src/Functions/array/arrayIndex.h (hunk 5 above)
Comment (myrrc) [reply src/Functions/array/arrayIndex.h:637]: Thanks for the hint.

File: base/common/StringRef.h [hunk 11]
```diff
@@ -20,17 +20,22 @@
...
+ */
 struct StringRef
 {
     const char * data = nullptr;
     size_t size = 0;
 
+    /// Non-constexpr due to reinterpret_cast.
     template <typename CharT, typename = std::enable_if_t<sizeof(CharT) == 1>>
-    constexpr StringRef(const CharT * data_, size_t size_) : data(reinterpret_cast<const char *>(data_)), size(size_) {}
+    StringRef(const CharT * data_, size_t size_) : data(reinterpret_cast<const char *>(data_)), size(size_) {}
```
Comment (Enmk) [inline base/common/StringRef.h:33]: Why not `constexpr` anymore ?

Comment (myrrc) [reply base/common/StringRef.h:33]: reinterpret_cast is not constexpr.

**Comment by myrrc** [comment]
Also there is a linked PR #12751 that may result in a CI false negative test

**Comment by Akazz** [comment]
0f5b089 emits a completely unrelated test failure in 00933_test_fix_extra_seek_on_compressed_cache

**Review by Akazz — APPROVED** [review]

**Comment by filimonov** [comment]
I was interested in perf test results, but it looks like all of them "Performance Pending — Started" what is happening with them / with CI?

**Comment by alexey-milovidov** [comment]
Enqueued, waiting for the free server to run.

**Comment by Akazz** [comment]
It turned out that Performance test `TIMEOUT` was due to incorrect syntax in the newly added test queries!
As for `01413_rows_events` test failures after commit 059a3dc, i'm at my wit's end here. @myrrc Need to investigate.

**Comment by Akazz** [comment]
After some digging in a DRAMATIC slowdown in `array_index_low_cardinality.xml` performance test has been discovered. Run time increase is so substantial, that it prevents the whole "Performance Test" from completing in due time causing TIMEOUT for its CI task.

**Comment by myrrc** [comment]
Looks like the current implementation with a non-constant right argument produces a 1k-10k times slower result (with speed about 10kb/sec), so one should either fallback to the default implementation if the right argument is non-constant (thus providing a speedup with const right-hand arguments) or mutate the column and build its index while iterating over the values.

**Comment by Akazz** [comment]
JFYI: `test_storage_rabbitmq/test.py::test_rabbitmq_many_materialized_views` from integration tests "flaps"

**Comment by myrrc** [comment]
Merging this PR would also resolve #13392

**Comment by myrrc** [comment]
Resolves #13917

**Review by alexey-milovidov — APPROVED** [review]

**Comment by abyss7** [comment]
Added regression for queries like:

`SELECT * FROM table WHERE has(['a', 'b'], low_cardinality_string_column)`

With exception:

> Types of array and 2nd argument of function "has" must be identical up to nullability, cardinality, numeric types, or Enum and numeric type. Passed: Array(String) and LowCardinality(String)

**Comment by alex-zaitsev** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/16038 ?
@myrrc, could you check?

> Probably added regression for queries like:
> 
> `SELECT * FROM table WHERE has(['a', 'b'], low_cardinality_string_column)`
