### PR TITLE
Fix logical error with empty ARRAY JOIN from COLUMNS()

### LINKED ISSUE #88059: Logical Error: No arrays to join
### Describe the bug

Easy to reproduce. Only happens with the new analyzer enabled.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/1778a6bd-e260-48ce-a870-695bd4c023b4

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'No arrays to join'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000002770f272
1. src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014a22ca9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d31830e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d317d11
4. src/Common/Exception.h:141: DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000d324d36
5. src/Interpreters/ArrayJoinAction.cpp:70: DB::ArrayJoinAction::ArrayJoinAction(std::vector<String, std::allocator<String>> const&, bool, bool, unsigned long) @ 0x000000001b6e9dab
6. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::ArrayJoinStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x000000001fc5f8a5
7. src/Processors/QueryPlan/ITransformingStep.cpp:21: DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000001fca8028
8. src/Processors/QueryPlan/QueryPlan.cpp:207: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001fce0c34
9. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x000000001bad6fa9
10. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001bad6cdc
11. src/Interpreters/executeQuery.cpp:1603: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x000000001bdf5382
12. src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001bdef032
13. src/Server/TCPHandler.cpp:743: DB::TCPHandler::runImpl() @ 0x000000001f6b258e
14. src/Server/TCPHandler.cpp:2754: DB::TCPHandler::run() @ 0x000000001f6cbea4
15. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000277c5c87
16. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000277c6265
17. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000277653ff
18. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000027762ad1
19. start_thread @ 0x00000000000a27f1
20. __clone3 @ 0x0000000000133b5c
```

### PR DESCRIPTION
**Pull request by xiaohuanlin**
Fix #88059 . When COLUMNS() transformer resolves to empty list, array join expressions become empty, causing "No arrays to join" error at execution stage. Add validation after resolving COLUMNS to ensure at least one expression remains.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix logical error when ARRAY JOIN COLUMNS() matches no columns in new analyzer.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: tests/queries/0_stateless/03646_array_join_empty.sql [hunk 1]
```diff
@@ -0,0 +1,18 @@
+SET allow_experimental_analyzer = 1;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/03646_array_join_empty.sql]:
```suggestion
SET enable_analyzer = 1;
```

**Review by novikd — APPROVED** [review]
