### PR TITLE
Throw exception when xml user profile does not exist

### LINKED ISSUE #26086: When using XML/YAML based user configuration if profile or quota is not defined then default ones are used
Previously (until RBAC was introduced) users were not allowed to connect to ClickHouse if user definition referenced a non-existing profile/quota. `DB::Exception: There is no profile 'does_not_exist' in configuration file..`

After RBAC was introduced this behavior changed and now users can connect and they are assigned default profile. This is unexpected and is easy to make mistakes (eg typos) that would give users more privileges than expected (allow_ddl, readonly).

cc @vitlibar

### PR DESCRIPTION
**Pull request by nvartolomei**
Closes #26086

cc @vitlibar 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Access/SettingsProfileElement.h [hunk 1]
```diff
@@ -19,6 +19,10 @@ class AccessControl;
 struct SettingsProfileElement
 {
     std::optional<UUID> parent_profile;
+    /// parent_profile_xml_name is set only when users are configured via XML
+    /// and is used for user-friendly error messages.
+    std::optional<String> parent_profile_xml_name;
```
Comment (vitlibar) [inline src/Access/SettingsProfileElement.h:24]: `SettingsProfileElement` is used not only with `users.xml`, so it seems it would be better to check that all parent profiles exist in `parseSettingsProfiles()` in UsersConfigAccessStorage, without introducing this new field.

Comment (vitlibar) [reply src/Access/SettingsProfileElement.h:24]: For example we can make a set of all profile names in `parseSettingsProfiles()` first and then pass this set to `parseSettingsProfile()`.

**Comment by nvartolomei** [comment]
Where do we store the information about broken profile chain to report in
back to user in that case?

Also, we’d need to update the parsing code a bit to allow verifying
references from users to profiles as well.

**Comment by vitlibar** [comment]
> Where do we store the information about broken profile chain to report in back to user in that case?

We could make a set of the names of all profiles in this users.xml before parsing users or profiles and use this set to validate parent profiles while we're parsing users and profiles. This issue with wrong names of profiles is related to parsing of `users.xml` so the solution in my opinion should probably live near the parsing code.

**Review by vitlibar — APPROVED** [review]

**Comment by nvartolomei** [comment]
@vitlibar not this will prevent server from starting at all with wrong config? :/ I forgot to push the test there and looks like I deleted it now. But, the old behaviour was to throw exception at connect/query time.

**Comment by vitlibar** [comment]
> @vitlibar not this will prevent server from starting at all with wrong config? :/

Yes, but other errors in users.xml could stop server on start anyway
