### PR TITLE
Check hash function at table creation

### LINKED ISSUE #822: Hash functions should be checked at table creation, not at sampling time
It is possible to create a table within a non-UInt hash column (i.e. MD5) and insert data, although at query time it complains:

```
ENGINE = MergeTree(normdate,MD5(id), (created_at, id,MD5(id)),8192);
...
Code: 59. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Invalid sampling column type in storage parameters: FixedString(16). Must be unsigned integer type..
```
This probably will be better to check at creation time.

### PR DESCRIPTION
**Pull request by zxc111**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Check hash function at table creation, not at sampling.
Add settings in MergeTreeSettings, if someone create a table with incorrect sampling column but sampling never be used, disable this settings for starting the server without exception.

closes #822

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -125,12 +128,37 @@ namespace ErrorCodes
...
     if (!pk_sample_block.has(metadata.sampling_key.column_names[0]) && !allow_sampling_expression_not_in_primary_key)
         throw Exception("Sampling expression must be present in the primary key", ErrorCodes::BAD_ARGUMENTS);
+
+    if (!check_sample_column_is_correct)
+        return;
+
+    const auto & sampling_key = metadata.getSamplingKey();
+    DataTypePtr sampling_column_type = sampling_key.data_types[0];
+
+    RelativeSize size_of_universum = 0;
```
Comment (CurtizJ) [inline src/Storages/MergeTree/MergeTreeData.cpp:144]: There is no need to create `RelativeSize` object. You can use just `bool` flag.

**Review by CurtizJ — APPROVED** [review]

**Comment by CurtizJ** [comment]
@zxc111 It's better not to explicitly create database in functional tests. Instead `clickhouse-test` script creates a database with random name before run and uses it as default database for queries.

**Comment by gyuton** [comment]
Internal documentation ticket: DOCSUP-11657.
