### PR TITLE
Fix crash in REFRESHABLE MV in case of ALTER after incorrect shutdown

### LINKED ISSUE #78103: Invalid access in MaterializedView/RefreshTask
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78091&sha=602680543079682e66dcd9c6d128995d2e007a4b&name_0=PR&name_1=Stress%20test%20%28tsan%29

```
 [ 74364 ] {} <Fatal> BaseDaemon: Address: 0x178. Access: read. Address not mapped to object.
 [ 74364 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005567c723d2fd 0x00005567c7675b04 0x00005567bedf37a6 0x00005567bedf3cfb 0x00007f5009ae6520 0x00005567cd637901 0x00005567d1fecf97 0x00005567d11d6f0d 0x00005567ceed1523 0x00005567ceecece3 0x00005567cf4467ba 0x00005567cf4413cf 0x00005567d220c585 0x00005567d22332e8 0x00005567d75a4da3 0x00005567d75a5612 0x00005567d7519883 0x00005567d7517c30 0x00005567d7515fea 0x00005567bedeb428 0x00007f5009b38ac3 0x00007f5009bca850
 [ 74364 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./build_docker/./src/Common/StackTrace.cpp:386: StackTrace::tryCapture()
 [ 74364 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:355: StackTrace::StackTrace(ucontext_t const&) @ 0x0000000010b5f2fd
 [ 74364 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/SignalHandlers.cpp:106: signalHandler(int, siginfo_t*, void*) @ 0x0000000010f97b04
 [ 74364 ] {} <Fatal> BaseDaemon: 2. __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, int, __sanitizer::__sanitizer_siginfo*, void*) @ 0x00000000087157a6
 [ 74364 ] {} <Fatal> BaseDaemon: 3. sighandler(int, __sanitizer::__sanitizer_siginfo*, void*) @ 0x0000000008715cfb
 [ 74364 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f5009ae6520
 [ 74364 ] {} <Fatal> BaseDaemon: 5.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:1480: std::weak_ptr<DB::Context>::lock() const
 [ 74364 ] {} <Fatal> BaseDaemon: 5. ./src/Interpreters/Context_fwd.h:41: DB::WithContextImpl<std::shared_ptr<DB::Context>>::getContext() const @ 0x0000000016f59901
 [ 74364 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Storages/MaterializedView/RefreshTask.cpp:240: DB::RefreshTask::alterRefreshParams(DB::ASTRefreshStrategy const&) @ 0x000000001b90ef97
 [ 74364 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Storages/StorageMaterializedView.cpp:681: DB::StorageMaterializedView::alter(DB::AlterCommands const&, std::shared_ptr<DB::Context const>, std::unique_lock<std::timed_mutex>&) @ 0x000000001aaf8f0d
 [ 74364 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Interpreters/InterpreterAlterQuery.cpp:217: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x00000000187f3523
 [ 74364 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Interpreters/InterpreterAlterQuery.cpp:78: DB::InterpreterAlterQuery::execute() @ 0x00000000187f0ce3
 [ 74364 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Interpreters/executeQuery.cpp:1458: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x0000000018d687ba
 [ 74364 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Interpreters/executeQuery.cpp:1625: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018d633cf
 [ 74364 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Server/TCPHandler.cpp:665: DB::TCPHandler::runImpl() @ 0x000000001bb2e585
 [ 74364 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Server/TCPHandler.cpp:2630: DB::TCPHandler::run() @ 0x000000001bb552e8
 [ 74364 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000020ec6da3
 [ 74364 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000020ec7612
 [ 74364 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000020e3b883
 [ 74364 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./base/poco/Foundation/src/Thread.cpp:45: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x0000000020e39c30
 [ 74364 ] {} <Fatal> BaseDaemon: 18. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000020e37fea
 [ 74364 ] {} <Fatal> BaseDaemon: 19. __tsan_thread_start_func @ 0x000000000870d428
 [ 74364 ] {} <Fatal> BaseDaemon: 20. ? @ 0x00007f5009b38ac3
 [ 74364 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00007f5009bca850
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash in REFRESHABLE MV in case of ALTER after incorrect shutdown

The problem is that in case of incorrect shutdown, i.e.:

    2025.04.03 22:42:03.620982 [ 14841 ] {632881cd-4918-414c-a2ed-27bb6beee664} <Error> executeQuery: Code: 219. DB::Exception: New table appeared in database being dropped or detached. Try again. (DATABASE_NOT_EMPTY) (version 25.4.1.1) (from [::1]:37582) (comment: 03258_refreshable_mv_misc.sh) (query 1, line 2) (in query: drop database test_15_03258;), Stack trace (when copying this message, always include the lines below):

    0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000020b619a0
    1. ./ci/tmp/build/./src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000010bd82d4
    2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000086edcc0
    3. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000086fc67a
    4. ./ci/tmp/build/./src/Interpreters/DatabaseCatalog.cpp:615: DB::DatabaseCatalog::detachDatabase(std::shared_ptr<DB::Context const>, String const&, bool, bool) @ 0x00000000180a72d7
    5. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:535: DB::InterpreterDropQuery::executeToDatabaseImpl(DB::ASTDropQuery const&, std::shared_ptr<DB::IDatabase>&, std::vector<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, std::allocator<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>>>&) @ 0x00000000186c1105
    6. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:364: DB::InterpreterDropQuery::executeToDatabase(DB::ASTDropQuery const&) @ 0x00000000186bbe78
    7. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:100: DB::InterpreterDropQuery::executeSingleDropQuery(std::shared_ptr<DB::IAST> const&) @ 0x00000000186bae97
    8. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:73: DB::InterpreterDropQuery::execute() @ 0x00000000186baab0
    9. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1458: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x0000000018be45da
    10. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1625: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018bdf1ef
    11. ./ci/tmp/build/./src/Server/TCPHandler.cpp:665: DB::TCPHandler::runImpl() @ 0x000000001b9cb665
    12. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2630: DB::TCPHandler::run() @ 0x000000001b9f23c8
    13. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000020c71da3
    14. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000020c72612
    15. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000020be7cc3
    16. ./ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x0000000020be6070
    17. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000020be442a
    18. __tsan_thread_start_func @ 0x0000000008661428
    19. ? @ 0x00007f396f9fdac3
    20. ? @ 0x00007f396fa8f850

The table will still exist, but the view will be NULL due to shutdown() had been called already.

And after this any ALTER of it will lead to crash.

So fix this by checking the `view` under mutex.

P.S. I've looked through other places and it is either called under refreshTask() (which should not be called after shutdown()) or already has check for `view` under mutex.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/78103

### CODE REVIEW

File: src/Storages/MaterializedView/RefreshTask.cpp [hunk 1]
```diff
@@ -216,28 +216,28 @@ void RefreshTask::checkAlterIsPossible(const DB::ASTRefreshStrategy & new_strate
...
+        refresh_settings.applyChanges(new_strategy.settings->changes);
 
-        refresh_settings = {};
-        if (new_strategy.settings != nullptr)
-            refresh_settings.applyChanges(new_strategy.settings->changes);
-    }
     /// In case refresh period changed.
-    view->getContext()->getRefreshSet().notifyDependents(view->getStorageID());
+    if (view)
+        view->getContext()->getRefreshSet().notifyDependents(view->getStorageID());
```
Comment (al13n321) [inline src/Storages/MaterializedView/RefreshTask.cpp:240]: Are you sure it's ok to lock RefreshSet::mutex while holding RefreshTask::mutex, i.e. that they're never locked in the opposite order? It seems so, but it also seems easy to avoid relying on it here: call `getRefreshSet()` and `getStorageID()` with mutex locked, then unlock and call `notifyDependents`.

Comment (al13n321) [reply src/Storages/MaterializedView/RefreshTask.cpp:240]: Ah, the problem is not RefreshSet, it's other RefreshTask mutexes (through notifyDependents -> RefreshTask::notify). It's maybe possible to ALTER two tables to depend on each other, then have them notify each other at the same time and deadlock trying to lock the two mutexes in different order. So please move the call out of the lock.

Comment (azat) [reply src/Storages/MaterializedView/RefreshTask.cpp]: Good point. Indeed, I came to the same conclusion that lock-order-inversion may happen. Fixed.

Note: I have to use global context, since `getRefreshSet` returns a reference, and RefreshSet is not copyable (and should not), but this should be safe, since it is anyway shared.

**Review by al13n321 — APPROVED** [review]

**Comment by azat** [comment]
>[Stress test (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78858&sha=4bb71b982a46a8e5af9bf9e61d27813d48f1d0be&name_0=PR&name_1=Stress%20test%20%28amd_debug%29) — Killed by signal (in clickhouse-server.log)

- https://github.com/ClickHouse/ClickHouse/issues/64936
