### PR TITLE
Disable parallel run for `01923_network_receive_time_metric_insert.sh`

### LINKED ISSUE #67432: Test `01923_network_receive_time_metric_insert` has failed
https://s3.amazonaws.com/clickhouse-test-reports/0/ef51c94a92b668666c49e2178b3def018b7f4d4f/stateless_tests__msan__[2_4].html

### PR DESCRIPTION
**Pull request by jkartseva**
#67432 

If run in parallel, several tests contribute to the value of the `NetworkReceiveElapsedMicroseconds` profile event. This may lead to flakiness because the query log merely flushes the difference between two snapshots regardless of which query has contributed. 

Another reason for flakiness may be the time difference between the input stream creation and the start of the insert (described in https://github.com/ClickHouse/ClickHouse/issues/66921). I'd like to try disabling parallel runs before decreasing the rate.

https://s3.amazonaws.com/clickhouse-test-reports/0/ef51c94a92b668666c49e2178b3def018b7f4d4f/stateless_tests__msan__%5B2_4%5D.html

```
% grep 01923_network_receive_time_metric_insert.sh  ~/Downloads/clickhouse-server\ \(27\).log
2024.07.30 04:17:26.091186 [ 6569 ] {} <Trace> DynamicQueryHandler: Request URI: /?query=SELECT+%27Running+test+stateless%2F01923_network_receive_time_metric_insert.sh+from+pid%3D2163%27&database=system&connect_timeout=30&receive_timeout=30&send_timeout=30&http_connection_timeout=30&http_receive_timeout=30&http_send_timeout=30&output_format_parallel_formatting=0
2024.07.30 04:17:26.107919 [ 6569 ] {c0a40da8-cd1a-449b-b90e-8d343b1836df} <Debug> executeQuery: (from [::1]:53658) SELECT 'Running test stateless/01923_network_receive_time_metric_insert.sh from pid=2163'  (stage: Complete)
2024.07.30 04:17:26.138972 [ 6579 ] {} <Trace> DynamicQueryHandler: Request URI: /?query=CREATE+DATABASE+IF+NOT+EXISTS+test_81xbjfo7&database=system&connect_timeout=30&receive_timeout=30&send_timeout=30&http_connection_timeout=30&http_receive_timeout=30&http_send_timeout=30&output_format_parallel_formatting=0&log_comment=01923_network_receive_time_metric_insert.sh
2024.07.30 04:17:26.152159 [ 6579 ] {5bdf58c4-dd1d-425b-966f-c736b98f8f57} <Debug> executeQuery: (from [::1]:53664) (comment: 01923_network_receive_time_metric_insert.sh) CREATE DATABASE IF NOT EXISTS test_81xbjfo7  (stage: Complete)
2024.07.30 04:17:30.475298 [ 6982 ] {a6136972-a6fe-4c26-a4ae-cf2eb71a404f} <Debug> executeQuery: (from [::1]:51988) (comment: 01923_network_receive_time_metric_insert.sh) DROP TABLE IF EXISTS t; (stage: Complete)
2024.07.30 04:17:30.615294 [ 6982 ] {9d1f8bd8-fd39-47fa-94af-349389389721} <Debug> executeQuery: (from [::1]:51988) (comment: 01923_network_receive_time_metric_insert.sh) CREATE TABLE t (x UInt64) ENGINE = Memory; (stage: Complete)
2024.07.30 04:17:43.807880 [ 7628 ] {054c016e-8395-41c7-9594-0540eb6d2399} <Debug> executeQuery: (from [::1]:51320) (comment: 01923_network_receive_time_metric_insert.sh) INSERT INTO t FORMAT TSV (stage: Complete)
2024.07.30 04:17:45.502056 [ 7538 ] {269911d8-75c3-4321-ad0b-d3b42bf2d870} <Debug> executeQuery: (from [::1]:51460) (comment: 01923_network_receive_time_metric_insert.sh) SYSTEM FLUSH LOGS; (stage: Complete)
2024.07.30 04:17:54.851304 [ 7538 ] {aa4f8752-7578-4360-b8ef-587a270ca235} <Debug> executeQuery: (from [::1]:51460) (comment: 01923_network_receive_time_metric_insert.sh) WITH ProfileEvents['NetworkReceiveElapsedMicroseconds'] AS time SELECT time >= 1000000 ? 1 : time FROM system.query_log WHERE current_database = currentDatabase() AND query_kind = 'Insert' AND event_date >= yesterday() AND type = 2 ORDER BY event_time DESC LIMIT 1; (stage: Complete)
2024.07.30 04:17:56.046744 [ 6676 ] {b5d0ee4d-9f6a-479f-9770-6422e73cd53b} <Debug> executeQuery: (from [::1]:38038) (comment: 01923_network_receive_time_metric_insert.sh) DROP TABLE t (stage: Complete)
```
(The time difference between the beginning of table creation and the beginning of inserts is `13s`)

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

File: tests/queries/0_stateless/01923_network_receive_time_metric_insert.sh [hunk 1]
```diff
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
-# Tags: no-fasttest
+# Tags: no-fasttest, no-parallel
 # Tag no-fasttest: needs pv
+# Tags: no-parallel: reads from a system table
```
Comment (pamarcos) [inline tests/queries/0_stateless/01923_network_receive_time_metric_insert.sh:4]: I think here you meant to type`Tag` instead of `Tags`. Otherwise, it'd follow the same syntax as the first line which sets the tags to be applied, not the description of why the tag is included

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 79598e338267c62c2f9bd9c40814cb03210fa531 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67492/79598e338267c62c2f9bd9c40814cb03210fa531/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/dea79dc2bbcdb7ffc33b6b2e535e898eda16eab4/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/34ddcdcc641546685c141c1bab5e48e8cd85ab43/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/01923_network_receive_time_metric_insert.sh (hunk 1 above)
Comment (jkartseva) [reply tests/queries/0_stateless/01923_network_receive_time_metric_insert.sh]: fixed, thanks

**Review by pamarcos — APPROVED** [review]
