### PR TITLE
Stop removing UTF-8 BOM in RowBinary format

### LINKED ISSUE #37420: Some UInt64 values cannot be inserted in RowBinary format over HTTP
> You have to provide the following information whenever possible.

Some values of `UInt64` cannot be inserted in the `RowBinary` format using HTTP, although most values are inserted fine.

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

On the latest available on the docker hub, `22.1.3 revision 54455`.

**How to reproduce**

1. Create a table:
```sql
CREATE TABLE some(no UInt64) ENGINE = MergeTree ORDER BY no;
```

2. Now write `1653178571234567890`:
```
echo -en '\xd2\x66\xb9\xd0\x26\x45\xf1\x16' | curl -v --data-binary @- 'http://127.0.0.1:8123/?query=INSERT%20INTO%20some(no)%20FORMAT%20RowBinary'
```
```
*   Trying 127.0.0.1:8123...
* Connected to 127.0.0.1 (127.0.0.1) port 8123 (#0)
> POST /?query=INSERT%20INTO%20some(no)%20FORMAT%20RowBinary HTTP/1.1
> Host: 127.0.0.1:8123
> User-Agent: curl/7.83.0
> Accept: */*
> Content-Length: 8
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sun, 22 May 2022 00:53:08 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: 4f17bcf5935b
< Transfer-Encoding: chunked
< Keep-Alive: timeout=3
< X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}
<
* Connection #0 to host 127.0.0.1 left intact
```

Works fine.

3. Now write `1651760768976141295`:
```
echo -en '\xef\xbb\xbf\x00\xab\x3b\xec\x16' | curl -v --data-binary @- 'http://127.0.0.1:8123/?query=INSERT%20INTO%20some(no)%20FORMAT%20RowBinary'
```
```
*   Trying 127.0.0.1:8123...
* Connected to 127.0.0.1 (127.0.0.1) port 8123 (#0)
> POST /?query=INSERT%20INTO%20some(no)%20FORMAT%20RowBinary HTTP/1.1
> Host: 127.0.0.1:8123
> User-Agent: curl/7.83.0
> Accept: */*
> Content-Length: 8
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Sun, 22 May 2022 00:54:26 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: 4f17bcf5935b
< Transfer-Encoding: chunked
< X-ClickHouse-Exception-Code: 33
< Keep-Alive: timeout=3
< X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}
<
Code: 33. DB::Exception: Cannot read all data. Bytes read: 5. Bytes expected: 8.: (at row 1)
: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 22.1.3.7 (official build))
* Connection #0 to host 127.0.0.1 left intact
```

### PR DESCRIPTION
**Pull request by loyd**
Fixes #37420

Now it disables BOM removal for the `RowBinary` format totally. It's possible to detect some special cases (e.g. starting with `String`), but I haven't found similar exceptions in other input formats, should I add it?

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
```
Stop removing UTF-8 BOM in RowBinary format. [#37428](https://github.com/ClickHouse/ClickHouse/pull/37428) ([Paul Loyd](https://github.com/loyd)).
```

### CODE REVIEW

File: src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ void RowInputFormatWithNamesAndTypes::readPrefix()
     if (getCurrentUnitNumber() != 0)
         return;
 
-    if (with_names || with_types || data_types.at(0)->textCanContainOnlyValidUTF8())
+    if (with_names || with_types)
```
Comment (alexey-milovidov) [inline src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp:41]: Yes, RowBinary format should not remove BOM, because it is binary, not text.

But the logic of this change looks incorrect. You should somehow check that the format is binary. Currently, it is checking something else.

CSV and TSV should skip BOMs.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp (hunk 1 above)
Comment (loyd) [reply src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp:41]: I thought this code is only for `RowBinary*`, my bad.

I haven't found anything useful in `format_settings` to distinguish binary formats, so added an explicit `is_binary` argument.

File: src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp [hunk 2]
```diff
@@ -38,10 +40,9 @@ void RowInputFormatWithNamesAndTypes::readPrefix()
     if (getCurrentUnitNumber() != 0)
         return;
 
-    if (with_names || with_types || data_types.at(0)->textCanContainOnlyValidUTF8())
+    /// Search and remove BOM only in textual formats (CSV, TSV etc), not in binary ones (RowBinary*).
```
Comment (alexey-milovidov) [inline src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp:43]: It should not be matched if the text format can start with a value that can contain not only valid UTF-8 characters.

Example: String, FixedString.

```
(with_names || with_types || data_types.at(0)->textCanContainOnlyValidUTF8()
```

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]

**Review by Avogar — APPROVED** [review]
