### PR TITLE
Try to parse DataType arguments as another nested type

### LINKED ISSUE #15587: Named tuple inside array data type specification can't be parsed
```
$ clickhouse client
ClickHouse client version 20.10.1.1-arcadia.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.10.1 revision 54441.

max42-dev.sas.yp-c.yandex.net :) create table T(f Array(Tuple(key String, value UInt8))) engine = Log()

Syntax error: failed at position 34 ('String'):

create table T(f Array(Tuple(key String, value UInt8))) engine = Log()

Expected one of: LIKE, GLOBAL NOT IN, AS, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, Comma, alias, IN, ILIKE, Dot, NOT ILIKE, NOT, Arrow, NOT IN, token, GLOBAL IN

max42-dev.sas.yp-c.yandex.net :) create table T(f Array(Tuple(String, UInt8))) engine = Log()                  

CREATE TABLE T
(
    `f` Array(Tuple(String, UInt8))
)
ENGINE = Log()

Ok.

0 rows in set. Elapsed: 0.008 sec. 

max42-dev.sas.yp-c.yandex.net :) create table T2(f Tuple(key String, value UInt8)) engine = Log()

CREATE TABLE T2
(
    `f` Tuple(    key String,     value UInt8)
)
ENGINE = Log()

Ok.

0 rows in set. Elapsed: 0.005 sec. 
```

If I understand correctly, DataType parser allows parsing of nested-like data type specifications (i.e. Typename(f1 T1, f2 T2, ...)) only at the top-level. It makes impossible to enclose named tuple into any kind of other structure, like Array or another Tuple. 

Such option is needed for proper interoperability with third-party applications which impose such data types.

### PR DESCRIPTION
**Pull request by abyss7**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add support for nested data types (like named tuple) as sub-types. Fixes #15587

### CODE REVIEW

File: src/Parsers/ParserDataType.cpp [hunk 1]
```diff
@@ -78,14 +80,24 @@ bool ParserDataType::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
...
-    ParserList args_parser(std::make_unique<ParserExpression>(), std::make_unique<ParserToken>(TokenType::Comma));
     ASTPtr expr_list_args;
 
-    if (!args_parser.parse(pos, expr_list_args, expected))
-        return false;
-    if (pos->type != TokenType::ClosingRoundBracket)
-        return false;
-    ++pos;
+    ParserList args_parser_nested(std::make_unique<ParserNestedTable>(), std::make_unique<ParserToken>(TokenType::Comma), false);
+    if (args_parser_nested.parse(pos, expr_list_args, expected))
```
Comment (tavplubix) [inline src/Parsers/ParserDataType.cpp:86]: Do we need to support mixed arguments list with `NestedTable` and `Expression`? I mean something like 
`Tuple(Tuple(key String, value String)), FixedString(16))`
where `Tuple(key String, value String)` cannot be parsed as `Expression` and `FixedString(16)` cannot be parsed as `NestedTable`.

Comment (zlobober) [reply src/Parsers/ParserDataType.cpp:86]: This is the case for CHYT, we have arbitrarily compound and mixed types.

**Review by tavplubix — APPROVED** [review]
