### PR TITLE
Fix bad test `01036_no_superfluous_dict_reload_on_create_database`

### LINKED ISSUE #67388: Test `01036_no_superfluous_dict_reload_on_create_database` has failed
https://s3.amazonaws.com/clickhouse-test-reports/67324/86f8fa5efbfd0c7bfe3f00ff37b85b2efe17cfe5/stateless_tests__debug__s3_storage__[1_2].html

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes #67388.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Review by davenger — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 064fe8c3f551a634f50543f1cfadd164f08173d4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67390/064fe8c3f551a634f50543f1cfadd164f08173d4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67363/4488d65fe91b58f72fec7536a8f8314aa3deec38/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/581e3e2f862fed28a456f21f3e9ba7a04f2c80d4/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/01018_ddl_dictionaries_select.sql [hunk 1]
```diff
@@ -139,6 +139,6 @@ SELECT {CLICKHOUSE_DATABASE:String} || '.dict3' as n, dictGet(n, 'some_column',
 
 DROP TABLE {CLICKHOUSE_DATABASE:Identifier}.table_for_dict;
 
-SYSTEM RELOAD DICTIONARIES; -- {serverError UNKNOWN_TABLE}
+SYSTEM RELOAD DICTIONARY {CLICKHOUSE_DATABASE:Identifier}.dict3; -- {serverError UNKNOWN_TABLE}
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/01018_ddl_dictionaries_select.sql:142]: What about other tests which use `SYSTEM RELOAD DICTIONARIES` ? I see `01018_dictionaries_from_dictionaries.sql` and `02179_dict_reload_on_cluster.sql`.

Comment (alexey-milovidov) [reply tests/queries/0_stateless/01018_ddl_dictionaries_select.sql:142]: I checked all of them.
