### PR TITLE
Fix skipping of some mutations

### LINKED ISSUE #17882: Is it a bug when number of ast elements >  max_expanded_ast_elements if there are many mutations.
I am reading clickhouse mutation code. In StorageMergeTree->selectPartsToMutate() function, there is a check 
`if (current_ast_elements + commands_size >= max_ast_elements)
                break;`

I think if there are many mutations then the check result will be true, so that it will skip the remaining mutations.
But the new part's mutation is set to the last one in mutation map, and it does not apply the remaining mutations actually.
`new_part_info.mutation = current_mutations_by_version.rbegin()->first;`

Then the new part will miss the remaining mutations in future mutation job.

I think it's wrong here. Am I right?

If it is right, I will submit a PR

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`MergeTree` table engine might silently skip some mutations if there are too many running mutations or in case of high memory consumption, it's fixed. Fixes #17882

Detailed description / Documentation draft:
Found in #24258

### CODE REVIEW

**Comment by alesapin** [comment]
@Mergifyio update

**Review by CurtizJ — APPROVED** [review]

File: src/Storages/StorageMergeTree.cpp [hunk 1]
```diff
@@ -943,8 +948,10 @@ std::shared_ptr<MergeMutateSelectedEntry> StorageMergeTree::selectPartsToMutate(
 
             current_ast_elements += commands_size;
             commands->insert(commands->end(), it->second.commands.begin(), it->second.commands.end());
+            last_mutation_to_apply = it;
         }
 
+        assert(commands->empty() == (last_mutation_to_apply == mutations_end_it));
```
Comment (alesapin) [inline src/Storages/StorageMergeTree.cpp:954]: Very complex assert :)
