### PR TITLE
Try fix 'Directory tmp_merge_<part_name>' already exists

### LINKED ISSUE #29616: Temporary directory for merged part already exist
https://clickhouse-test-reports.s3.yandex.net/29602/5de80a057fad28ea6b847772b1b3c23fda17b7d8/functional_stateless_tests_(release,_wide_parts_enabled).html#fail1

```
2021-10-01 15:24:10 00993_system_parts_race_condition_drop_zookeeper:                       [ FAIL ] 457.50 sec. - having stderror: 
2021-10-01 15:24:10 [6159e324f136] 2021.10.01 15:24:07.628355 [ 7880 ] {c0be8997-5b0e-44bc-ac55-798d367ffd37} <Error> InterpreterSystemQuery: SYNC REPLICA test_azebrg.alter_table_1 (1903d83c-7184-4ad8-9903-d83c71841ad8): Timed out!
2021-10-01 15:24:10 [6159e324f136] 2021.10.01 15:24:07.628641 [ 7880 ] {c0be8997-5b0e-44bc-ac55-798d367ffd37} <Error> executeQuery: Code: 159. DB::Exception: SYNC REPLICA test_azebrg.alter_table_1 (1903d83c-7184-4ad8-9903-d83c71841ad8): command timed out. See the 'receive_timeout' setting. (TIMEOUT_EXCEEDED) (version 21.11.1.8265) (from [::1]:41856) (comment: '/usr/share/clickhouse-test/queries/0_stateless/00993_system_parts_race_condition_drop_zookeeper.sh') (in query: SYSTEM SYNC REPLICA alter_table_1), Stack trace (when copying this message, always include the lines below):
2021-10-01 15:24:10 
2021-10-01 15:24:10 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9528ed4 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 1. DB::InterpreterSystemQuery::syncReplica(DB::ASTSystemQuery&) @ 0x1142c73e in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 2. DB::InterpreterSystemQuery::execute() @ 0x11426ee5 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 3. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x1163ca69 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 4. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1163a9f3 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 5. DB::TCPHandler::runImpl() @ 0x11f82324 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 6. DB::TCPHandler::run() @ 0x11f91239 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 7. Poco::Net::TCPServerConnection::start() @ 0x14bb1def in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 8. Poco::Net::TCPServerDispatcher::run() @ 0x14bb41e1 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 9. Poco::PooledThread::run() @ 0x14cc8989 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 10. Poco::ThreadImpl::runnableEntry(void*) @ 0x14cc60c0 in /usr/lib/debug/.build-id/97/659433c706eeb9bc1b9cfa879289b90bb497df.debug
2021-10-01 15:24:10 11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-10-01 15:24:10 12. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021-10-01 15:24:10 
2021-10-01 15:24:10 Received exception from server (version 21.11.1):
2021-10-01 15:24:10 Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: SYNC REPLICA test_azebrg.alter_table_1 (1903d83c-7184-4ad8-9903-d83c71841ad8): command timed out. See the 'receive_timeout' setting. (TIMEOUT_EXCEEDED)
2021-10-01 15:24:10 (query: SYSTEM SYNC REPLICA alter_table_1)
2021-10-01 15:24:10 
2021-10-01 15:24:10 
2021-10-01 15:24:10 stdout:
2021-10-01 15:24:10 sync failed, queue:	default	alter_table_1	r_1	0	queue-0000000252	MERGE_PARTS	2021-10-01 15:16:34	0	r_7	-4_0_3_1_2	['-4_0_0_0_2','-4_1_1_0_2','-4_3_3_0']	0	0	5008	Code: 84. DB::Exception: Directory /var/lib/clickhouse/store/190/1903d83c-7184-4ad8-9903-d83c71841ad8/tmp_merge_-4_0_3_1_2/ already exists. (DIRECTORY_ALREADY_EXISTS) (version 21.11.1.8265)	2021-10-01 15:24:06	0		1970-01-01 09:00:00	REGULAR
2021-10-01 15:24:10 Replication did not hang: synced all replicas of alter_table_
2021-10-01 15:24:10 Consistency: 1
2021-10-01 15:24:10 
2021-10-01 15:24:10 
2021-10-01 15:24:10 Database: test_azebrg
```

### LINKED ISSUE #31843: The problem of data part merging while using zero copy replication
I use zero copy replication by HDFS for test ,  replicas create table use the same storage_policy so they will use the same data on HDFS, the directory is shared. But now, I met a problem, the data part merge cannot be done? 
I understand replicas should use shared directory on HDFS, but why data part cannot be merged?  Is my operation wrong？

`2021.11.24 20:14:58.443628 [ 48666 ] {} default.hits_v1_1116_1 (2cf38cbb-8471-4d06-acf3-8cbb84711d06): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 84. DB::Exception: Directory /home/disk7/zcy/hdfs-ck/data-01/data/disks/hdfs1/store/2cf/2cf38cbb-8471-4d06-acf3-8cbb84711d06/tmp_merge_201403_6_11_1/ already exists. (DIRECTORY_ALREADY_EXISTS), Stack trace (when copying this message, always include the lines below):

Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int) @ 0x12dc58ec in ?
DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x9616ada in ?
DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeListElement&, std::__1::shared_ptrDB::RWLockImpl::LockHolderImpl&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_deleteDB::IReservation > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > const&, DB::MergeTreeData::MergingParams const&, DB::IMergeTreeDataPart const*, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0x1099e802 in ?
DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) @ 0x107483d8 in ?
DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x1073cae9 in ?
bool std::__1::__function::__policy_invoker<bool (std::__1::shared_ptrDB::ReplicatedMergeTreeLogEntry&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptrDB::ReplicatedMergeTreeQueue::SelectedEntry)::$_14, bool (std::__1::shared_ptrDB::ReplicatedMergeTreeLogEntry&)> >(std::__1::__function::__policy_storage const*, std::__1::shared_ptrDB::ReplicatedMergeTreeLogEntry&) @ 0x107c2bbf in ?
DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptrzkutil::ZooKeeper ()>, std::__1::shared_ptrDB::ReplicatedMergeTreeLogEntry&, std::__1::function<bool (std::__1::shared_ptrDB::ReplicatedMergeTreeLogEntry&)>) @ 0x10ab85a9 in ?
DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptrDB::ReplicatedMergeTreeQueue::SelectedEntry) @ 0x10773ebd in ?
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x108ddcf6 in ?
ThreadPoolImpl::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x964c28b in ?
ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()>(void&&, void ThreadPoolImpl::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x964d8ff in ?
ThreadPoolImplstd::__1::thread::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x964a9ab in ?
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ThreadPoolImplstd::__1::thread::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()> >(void*) @ 0x964cad3 in ?
start_thread @ 0x318b207851 in ?
__clone @ 0x318aee767d in ?
(version 21.10.2.1)`

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Some replication queue entries might hang for `temporary_directories_lifetime` (1 day by default) with `Directory tmp_merge_<part_name>` or `Part ... (state Deleting) already exists, but it will be deleted soon` or similar error. It's fixed. Fixes #29616.

Detailed description / Documentation draft:
Probably fixes #31843.
It happens because of race condition on part removal:
1. We are trying to commit some merged part to zk, but fail for some reason (another race condition or connection loss)
2. This part becomes `Outdated` (with `is_temp == false`, directory name is just part name), cleanup thread will try to remove it.
3. Another thread tries to execute log entry again and creates temporary part (with `is_temp == true` and directory name `tmp_merge_<part_name>`), but fails to add it it active set due to `Part ... (state Deleting) already exists`
4. It tries to remove temporary part (in dtor), but fails to rename it to `tmp_delete_<part_name>`, because directory exists, because cleanup thread is removing `Outdated` part with the same name.
5. It ignores the exception, exits dtor and leaves `tmp_merge_<part_name>` directory on disk, nobody (except `clearOldTemporaryDirectories`) will retry removal, because part is temporary and `MergeTreeDataPart` object does exist anymore.

Probably we should refactor parts removal mechanism, because it has became quite complex and fragile with all the flags (`is_temp`, `keep_shared_data`, `force_keep_shared_data`), special states (`DeleteOnDestroy`), `IDisk` interface and projections.

### CODE REVIEW

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 1]
```diff
@@ -1150,13 +1159,13 @@ void IMergeTreeDataPart::remove() const
       */
 
     fs::path from = fs::path(storage.relative_data_path) / relative_path;
-    fs::path to = fs::path(storage.relative_data_path) / ("delete_tmp_" + name);
+    fs::path to = fs::path(storage.relative_data_path) / ("delete_tmp_" + relative_path);
```
Comment (tavplubix) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:1162]: The fix is here

**Comment by alesapin** [comment]
Wow, my favorite method changed.

**Comment by tavplubix** [comment]
Integration tests (asan, actions) - `Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
Stress tests - memory limit

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 2]
```diff
@@ -424,53 +424,60 @@ void IMergeTreeDataPart::setColumns(const NamesAndTypesList & new_columns)
...
+        else
+            remove();
+
+        if (state == State::DeleteOnDestroy)
         {
-            tryLogCurrentException(__PRETTY_FUNCTION__);
+            LOG_TRACE(storage.log, "Removed part from old location {}", path);
         }
     }
+    catch (...)
```
Comment (alesapin) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:470]: Probably for remote disks we have to add smart retries in future (some exception codes can be retried).

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 3]
```diff
@@ -424,53 +424,60 @@ void IMergeTreeDataPart::setColumns(const NamesAndTypesList & new_columns)
...
-                remove();
+        }
 
-            if (state == State::DeleteOnDestroy)
-            {
-                LOG_TRACE(storage.log, "Removed part from old location {}", path);
-            }
+        if (parent_part)
+        {
+            std::optional<bool> keep_shared_data = keepSharedDataInDecoupledStorage();
```
Comment (alesapin) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:457]: Obscure code for me, but Ok.

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp (hunk 1 above)
Comment (alesapin) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:1168]: Maybe add a comment? So now we will have something like `delete_tmp_tmp_merge_<part_name>` or `delete_tmp_tmp_fetch_<part_name>` instead of `delete_tmp_<part_name>`?

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 4]
```diff
@@ -424,53 +424,60 @@ void IMergeTreeDataPart::setColumns(const NamesAndTypesList & new_columns)
...
+            if (!keep_shared_data.has_value())
```
Comment (alesapin) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:458]: What does it mean....?

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 5]
```diff
@@ -2274,8 +2272,6 @@ void StorageReplicatedMergeTree::executeClonePartFromShard(const LogEntry & entr
         };
 
         part = get_part();
-        // The fetched part is valuable and should not be cleaned like a temp part.
-        part->is_temp = false;
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:2278]: Probably we shouldn't remove this.

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp (hunk 4 above)
Comment (tavplubix) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:458]: I failed to understand the logic around `force_keep_shared_data`

**Comment by tavplubix** [comment]
Fast test - `01053_window_view_proc_hop_to_now` and `01054_window_view_proc_tumble_to` are flaky, cc: @kssenii, @Vxider

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by Vxider** [comment]
> Fast test - `01053_window_view_proc_hop_to_now` and `01054_window_view_proc_tumble_to` are flaky

I think it might caused by system freezing, and the `SELECT sleep(3)` is not enough to get the results. I could try to rewrite these flaky tests by using  the`.sh` test, and retries in loop to fetch the results instead of sleep. For now, we can disable these tests if possible.

**Review by alesapin — APPROVED** [review]
