### PR TITLE
better CTE and with global

### LINKED ISSUE #17378: Can't find column after renaming a table twice with "WITH" clause and "AS" clause
**Describe the bug**
A clear and concise description of what works not as it is supposed to.
After I use both "WITH" and "AS" to rename a table twice, it seems that the Clickhouse can't find columns in the table correctly.

**How to reproduce**
My ClickHouse version is 20.12.1.1.

Create Table Statement is :
```
CREATE TABLE tpcds.item
(
    `i_item_sk` Int64,
    `i_item_id` String,
    `i_rec_start_date` Nullable(Date),
    `i_rec_end_date` Nullable(Date),
    `i_item_desc` Nullable(String),
    `i_current_price` Nullable(Float32),
    `i_wholesale_cost` Nullable(Float32),
    `i_brand_id` Nullable(Int64),
    `i_brand` Nullable(String),
    `i_class_id` Nullable(Int64),
    `i_class` Nullable(String),
    `i_category_id` Nullable(Int64),
    `i_category` Nullable(String),
    `i_manufact_id` Nullable(Int64),
    `i_manufact` Nullable(String),
    `i_size` Nullable(String),
    `i_formulation` Nullable(String),
    `i_color` Nullable(String),
    `i_units` Nullable(String),
    `i_container` Nullable(String),
    `i_manager_id` Nullable(Int64),
    `i_product_name` Nullable(String)
)
ENGINE = MergeTree()
ORDER BY i_item_sk
SETTINGS index_granularity = 8192;
```
You can insert one row of sample data with
```
INSERT INTO tpcds.item
(i_item_sk, i_item_id, i_rec_start_date, i_rec_end_date, i_item_desc, i_current_price, i_wholesale_cost, i_brand_id, i_brand, i_class_id, i_class, i_category_id, i_category, i_manufact_id, i_manufact, i_size, i_formulation, i_color, i_units, i_container, i_manager_id, i_product_name)
VALUES(1, 'AAAAAAAABAAAAAAA', '1997-10-27', NULL, 'ncdlsnndfjnsa', 27.02, 23.23, 5003002, 'exportischolar #2', 3, 'pop', 5, 'Music', 52, 'ableanti', 'N/A', '3663peru009490160959', 'spring', 'Tsp', 'Unknown', 6, 'ought');
```

In my case "item" is a table, and "i_brand" is a column in that table.
After I run the following SQL:
```
with it as 
(
	select * from item
)
select i.i_brand from it i;
```

I get error `Missing columns: 'i.i_brand' ........"

**Expected behavior**
I expect my sql should output the original table correctly.

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Allow CTE to be further aliased. Propagate CSE to subqueries in the same level when `enable_global_with_statement = 1`. This fixes https://github.com/ClickHouse/ClickHouse/issues/17378 . This fixes https://github.com/ClickHouse/ClickHouse/pull/16575#issuecomment-753416235 .

Detailed description / Documentation draft:

.

### CODE REVIEW

**Comment by amosbird** [comment]
Test failure doesn't look like related

```
2021-01-02 12:42:05 01133_max_result_rows:                                                  [ FAIL ] 0.80 sec. - result differs with reference:
2021-01-02 12:42:05 --- /usr/share/clickhouse-test/queries/0_stateless/01133_max_result_rows.reference	2021-01-02 10:31:04.000000000 +0300
2021-01-02 12:42:05 +++ /tmp/clickhouse-test/0_stateless/01133_max_result_rows.stdout	2021-01-02 12:42:05.133011030 +0300
2021-01-02 12:42:05 @@ -4,20 +4,6 @@
2021-01-02 12:42:05  3
2021-01-02 12:42:05  4
2021-01-02 12:42:05  5
2021-01-02 12:42:05 -6
2021-01-02 12:42:05 -7
2021-01-02 12:42:05 -8
2021-01-02 12:42:05 -9
2021-01-02 12:42:05 -10
2021-01-02 12:42:05 -11
2021-01-02 12:42:05 -12
2021-01-02 12:42:05 -13
2021-01-02 12:42:05 -14
2021-01-02 12:42:05 -15
2021-01-02 12:42:05 -16
2021-01-02 12:42:05 -17
2021-01-02 12:42:05 -18
2021-01-02 12:42:05 -19
2021-01-02 12:42:05  0
2021-01-02 12:42:05  1
2021-01-02 12:42:05  2
```

**Comment by alexey-milovidov** [comment]
See also https://github.com/ClickHouse/ClickHouse/pull/18705#issuecomment-753719969

**Comment by amosbird** [comment]
> See also [#18705 (comment)](https://github.com/ClickHouse/ClickHouse/pull/18705#issuecomment-753719969)

Ah, it's broken after union distinct refactoring. I've fixed it and also enables the `enable_global_with_statement` by default to test.

**Comment by alexey-milovidov** [comment]
For some reason all `test_materialize_mysql_database` have failed.

File: src/Parsers/ASTSubquery.h [hunk 1]
```diff
@@ -12,6 +12,8 @@ namespace DB
 class ASTSubquery : public ASTWithAlias
 {
 public:
+    std::string cte_name;
```
Comment (alexey-milovidov) [inline src/Parsers/ASTSubquery.h:15]: Missing comment.

File: tests/queries/0_stateless/01515_with_global_and_with_propagation.sql [hunk 2]
```diff
@@ -1,13 +1,15 @@
...
-EXPLAIN SYNTAX WITH 1 AS x SELECT * FROM (SELECT x);
-EXPLAIN SYNTAX WITH 1 AS x SELECT *, x FROM (WITH 2 AS x SELECT x AS y);
-EXPLAIN SYNTAX WITH 1 AS x SELECT x UNION ALL SELECT x;
-EXPLAIN SYNTAX WITH 1 AS x SELECT x UNION ALL WITH 2 AS x SELECT x;
+explain syntax with 1 as x select x;
+explain syntax with 1 as x select * from (select x);
+explain syntax with 1 as x select *, x from (with 2 as x select x as y);
+explain syntax with 1 as x select x union all select x;
+explain syntax with 1 as x select x union all with 2 as x select x;
+explain syntax with 5 as q1, x as (select number + 100 as b, number as a from numbers(10) where number > q1) select * from x;
```
Comment (azat) [inline tests/queries/0_stateless/01515_with_global_and_with_propagation.sql:15]: Right now the following query will lead to endless recursion and eventually fails due to memory limits:

```sql
SELECT *
FROM 
(
    WITH
        
        (
            SELECT 1
        ) AS r1,
        
        (
            SELECT 2
        ) AS r2,
        
        (
            SELECT 3
        ) AS r3
    SELECT 10
)
SETTINGS max_ast_elements = 1000, max_memory_usage = '10Mi'
```

And this is because of `ExecuteScalarSubqueriesMatcher`, that visits AST and create `InterpreterSelectQuery` for each subquery (`ASTSubquery`), while `ApplyWithAliasVisitor` will create more each time.

So how about the following patch?

```patch
$ git di src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp
diff --git a/src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp b/src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp
index b3e8af90f2..4a6ec3505c 100644
--- a/src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp
+++ b/src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp
@@ -92,6 +92,12 @@ void ExecuteScalarSubqueriesMatcher::visit(const ASTSubquery & subquery, ASTPtr
         Settings subquery_settings = data.context.getSettings();
         subquery_settings.max_result_rows = 1;
         subquery_settings.extremes = false;
+        /// Otherwise ApplyWithAliasVisitor will be applied and this will
+        /// create new nodes in AST over and over and lead to endless recursion,
+        /// which eventually lead to one of the following errors:
+        /// - Memory limit exceeded
+        /// - AST too big
+        subquery_settings.enable_global_with_statement = false;
         subquery_context.setSettings(subquery_settings);
 
         ASTPtr subquery_select = subquery.children.at(0);
```

Also not that there is also `DB::JoinedTables::resolveTables` that will create `InterpreterSelectQuery`, and so it will also expand aliases one more time, which is pointless.

So maybe it is worth disabling `enable_global_with_statement` once `ApplyWithAliasVisitor` was applied (with changed=false)? Since there are also other places where interpreter will be created multiple times.

Comment (amosbird) [reply tests/queries/0_stateless/01515_with_global_and_with_propagation.sql:15]: Yeah, I'm fixing this and other related issues. Thanks for the suggestion. Actually we can just disable with propagation when `subquery_depth` is not zero.

**Comment by amosbird** [comment]
all `test_materialize_mysql_database` are still failing. @zhang2014 perhaps you can help...

**Comment by zhang2014** [comment]
> all test_materialize_mysql_database are still failing. @zhang2014 perhaps you can help...


fixes in  https://github.com/ClickHouse/ClickHouse/pull/19344

**Comment by alexey-milovidov** [comment]
Let's merge / rebase with master to rerun tests.

**Comment by amosbird** [comment]
fuzzer error looks real

https://clickhouse-test-reports.s3.yandex.net/18684/5998383a3b16a33c95dd71b3dd30614a0fbf5741/fuzzer_ubsan/report.html#fail1

```
SELECT gcd(-9223372036854775808, 1024)

Error on processing query 'SELECT gcd(-9223372036854775808, 1024)': Code: 32, e.displayText() = DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, Stack trace (when copying this message, always include the lines below):

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1c18c972 in /workspace/clickhouse
1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:56: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xe3d2eda in /workspace/clickhouse
2. ./obj-x86_64-linux-gnu/../src/IO/VarInt.h:0: DB::throwReadAfterEOF() @ 0xe3ec8bb in /workspace/clickhouse
3. ./obj-x86_64-linux-gnu/../src/IO/VarInt.h:133: void DB::readVarUIntImpl<false>(unsigned long&, DB::ReadBuffer&) @ 0xe41998f in /workspace/clickhouse
4. ./obj-x86_64-linux-gnu/../src/Client/Connection.cpp:0: DB::Connection::receivePacket(std::__1::function<void (Poco::Net::Socket&)>) @ 0x1b20a726 in /workspace/clickhouse
5. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::receiveAndProcessPacket(bool) @ 0xe4e729a in /workspace/clickhouse
6. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::receiveResult() @ 0xe4edda2 in /workspace/clickhouse
7. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::processOrdinaryQuery() @ 0xe4d78b8 in /workspace/clickhouse
8. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::processParsedSingleQuery() @ 0xe4d3857 in /workspace/clickhouse
9. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::processWithFuzzing(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe4cdd49 in /workspace/clickhouse
10. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::processMultiQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe4cfc90 in /workspace/clickhouse
11. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::nonInteractive()::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xe4f1e71 in /workspace/clickhouse
12. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::nonInteractive() @ 0xe4c1a9f in /workspace/clickhouse
13. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:715: DB::Client::mainImpl() @ 0xe4ba2cd in /workspace/clickhouse
14. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xe4b36bb in /workspace/clickhouse
15. ./obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x1c11719a in /workspace/clickhouse
16. ./obj-x86_64-linux-gnu/../programs/client/Client.cpp:0: mainEntryClickHouseClient(int, char**) @ 0xe4a6f84 in /workspace/clickhouse
17. ./obj-x86_64-linux-gnu/../programs/main.cpp:0: main @ 0xe3c6f14 in /workspace/clickhouse
18. __libc_start_main @ 0x270b3 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
19. _start @ 0xe3a502e in /workspace/clickhouse
 (version 21.2.1.5803)
```

**Comment by azat** [comment]
> fuzzer error looks real
> https://clickhouse-test-reports.s3.yandex.net/18684/5998383a3b16a33c95dd71b3dd30614a0fbf5741/fuzzer_ubsan/report.html#fail1

Should be fixed in #19532

**Review by alexey-milovidov — APPROVED** [review]
