### PR TITLE
Make parallel reading from several kafka consumers work again

### LINKED ISSUE #35153: kafka_num_consumers setting doesn't work without kafka_thread_per_consumer
I have Kafka engine table, MV and destination MT table.
Kafka table create query:
```
CREATE TABLE abc.Kafka_TestSource (...) 
ENGINE = Kafka 
SETTINGS kafka_broker_list = '...'
, format_avro_schema_registry_url = '...'
, kafka_topic_list = '...'
, kafka_group_name = 'Test_KafkaToCH'
, kafka_format = 'AvroConfluent'
, kafka_num_consumers = 1
, kafka_thread_per_consumer = 0
```

Due to Grafana consumer group stats dashboard it reads the topic with average speed ~11k records per second.
I recreate Kafka table with `kafka_num_consumers = 9` (kafka topic has 9 partitions) and it still reads with the same speed ~11k rps, **system.metrics** also shows that only 1 pool is being used:
```
SELECT
    m.metric,
    m.value
FROM system.metrics AS m
WHERE m.metric LIKE 'Background%'

Query id: 831a9285-e91b-45a4-8a1b-6b536d6860fe

┌─metric──────────────────────────────────┬─value─┐
│ BackgroundMergesAndMutationsPoolTask    │     4 │
│ BackgroundFetchesPoolTask               │     0 │
│ BackgroundCommonPoolTask                │     0 │
│ BackgroundMovePoolTask                  │     0 │
│ BackgroundSchedulePoolTask              │     0 │
│ BackgroundBufferFlushSchedulePoolTask   │     0 │
│ BackgroundDistributedSchedulePoolTask   │     0 │
│ BackgroundMessageBrokerSchedulePoolTask │     1 │
└─────────────────────────────────────────┴───────┘
```

If I set `kafka_thread_per_consumer = 1` then **BackgroundMessageBrokerSchedulePoolTask** in **system.metrics** raises up to 9 and read speed in Grafana raises up to 100 records per second:
pic
1. `kafka_num_consumers = 1, kafka_thread_per_consumer = 0`
2. `kafka_num_consumers = 9, kafka_thread_per_consumer = 0`
3. `kafka_num_consumers = 9, kafka_thread_per_consumer = 1`

Why `kafka_num_consumers` doesn't work without `kafka_thread_per_consumer`?

ClickHouse 21.11.4.14.

### PR DESCRIPTION
**Pull request by filimonov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix reading from `Kafka` tables when `kafka_num_consumers > 1` and `kafka_thread_per_consumer = 0`. Returns parallel & multithreaded reading, accidentally broken in 21.11. Closes #35153.

It was accidentally broken in #29491 (v21.11). Lack of parallel reading breaks some of the important Kafka invariants and leads to performance degradation and a lot of strange issues. For example, the first consumer will get all partitions, and/or some of the consumers will be used rarely, and will be entering/leaving the consumer group (if one of the consumers doesn't do a poll for 60 sec it gets kicked off from the consumer group), etc.

/cc @KochetovNicolai

### CODE REVIEW

File: src/Storages/Kafka/StorageKafka.cpp [hunk 1]
```diff
@@ -664,6 +664,11 @@ bool StorageKafka::streamToViews()
     size_t rows = 0;
     {
         block_io.pipeline.complete(std::move(pipe));
+
+        // we need to read all consumers in parallel (sequential read may lead to situation
+        // when some of consumers are not used, and will break some Kafka consumer invariants)
+        block_io.pipeline.setNumThreads(stream_count);
+
         block_io.pipeline.setProgressCallback([&](const Progress & progress) { rows += progress.read_rows.load(); });
```
Comment (ucasfl) [inline src/Storages/Kafka/StorageKafka.cpp:672]: `rows` should be an atomic variable, otherwise, it may lead to data race, see #36015.

Comment (ucasfl) [inline src/Storages/Kafka/StorageKafka.cpp:672]: `rows` should be an atomic variable, otherwise, it may lead to data race, see #36015.

Comment (ucasfl) [inline src/Storages/Kafka/StorageKafka.cpp:672]: rows should be an atomic variable now, otherwise, it may lead to data race, see https://github.com/ClickHouse/ClickHouse/pull/36015.

Comment (KochetovNicolai) [reply src/Storages/Kafka/StorageKafka.cpp:672]: agree, let's change it :)

**Review by KochetovNicolai — APPROVED** [review]
