### PR TITLE
fix: protobuf: serde: exception bypass for canonical repeated nested

### LINKED ISSUE #41971: PROTOBUF_FIELD_NOT_REPEATED when ingesting from Kafka
**Describe what's wrong**

With a protobuf schema using a repeated message, setting up Kafka to use this schema to import into a table leads to the `PROTOBUF_FIELD_NOT_REPEATED` error. This does not happen when ingesting from `clickhouse-client`.

**Does it reproduce on recent release?**

Reproduced on 22.8.5.29.

**How to reproduce**

Using the 22.8 Docker image:
1. put `flow-3.proto` in `/var/lib/clickhouse/format_schemas`
2. create the Kafka table and one consumer, no need to get messages from Kafka

```protobuf
syntax = "proto3";
package decoder;

message FlowMessagev3 {
  uint64 TimeReceived = 2;
  repeated LargeCommunity DstLargeCommunities = 37;
  message LargeCommunity {
    uint32 ASN = 1;
    uint32 LocalData1 = 2;
    uint32 LocalData2 = 3;
  }
}
```

```sql
CREATE TABLE default.flows_3_raw
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `DstLargeCommunities.ASN` Array(UInt32),
    `DstLargeCommunities.LocalData1` Array(UInt32),
    `DstLargeCommunities.LocalData2` Array(UInt32)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:9092', kafka_topic_list = 'flows-v3', kafka_group_name = 'clickhouse', kafka_format = 'Protobuf', kafka_schema = 'flow-3.proto:FlowMessagev3', kafka_num_consumers = 1, kafka_thread_per_consumer = 1

CREATE TABLE default.flows
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `DstLargeCommunities.ASN` Array(UInt32),
    `DstLargeCommunities.LocalData1` Array(UInt32),
    `DstLargeCommunities.LocalData2` Array(UInt32)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDDhhmmss(toStartOfInterval(TimeReceived, toIntervalSecond(25920)))
ORDER BY TimeReceived
TTL TimeReceived + toIntervalSecond(1296000)
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW default.flows_3_raw_consumer TO default.flows
AS SELECT * FROM default.flows_3_raw
```

Then, check `system.errors`. I get:

```
name:               PROTOBUF_FIELD_NOT_REPEATED
code:               437
value:              440
last_error_time:    2022-09-30 13:20:34
last_error_message: The field 'decoder.FlowMessagev3.LargeCommunity.ASN' must be repeated in the protobuf schema to match the column `ASN`
last_error_trace:   [171727226,366135675,366093641,366067646,366064173,366058066,366045826,366464972,366468882,364681438,337788230,337801743,364844405,364843206,364960586,364912827,364908569,364908061,364902892,337747165,337739135,333703256,333713718,333717100,172520264,172533085,140334772680201,140334771781939]
remote:             0
```

**Expected behavior**

No error in `system.errors`.

**Additional context**

It should be noted that sending messages work, including when they have a `DstLargeCommunity` field. They appear in the `flows` table without any issue.

cc @lesandie

### PR DESCRIPTION
**Pull request by hileef**
### Disclaimer

- I have very little CPP experience, please feel free to make any and all constructive feedback to improve this proposal
- I picked the "bugfix" category because I interpret the extraneous entries in `system.errors` when processing a "canonical"/"valid" proto/schema to be incorrect behaviour. Please correct it if necessary.

### On Semantics

The current potobuf serde implementation will always internally generate `PROTOBUF_FIELD_NOT_REPEATED`
when de/serializing such a canonical example : 

```proto
syntax = "proto3";

message A {
  repeated B v = 20;
  message B {
    uint32 x = 21;
    uint32 y = 22;
  }
}
```

```sql
CREATE TABLE example (
    `v.x` Array(UInt32),
    `v.y` Array(UInt32)
)
```

↘️  This PR essentially proposes to change the control flow a bit, such that :

WHEN the proto field we are mapping into is `repeated` ,
AND when the matching columns are nested and of type Array,
THEN we attempt to serialize via `ProtobufSerializerFlattenedNestedAsArrayOfNestedMessages` **_first_**,
RATHER THAN first going through the try/catch, throwing PROTOBUF_FIELD_NOT_REPEATED and catching it.

In the case where I am missing some use case and/or possible situtation where this control flow would be faulty,
please do comment / let me know, ideally with example proto/sql such that it can be turned into a new test and the implementation adapted 🙏 

### On Performance

I discovered this behaviour when investigating the performance of a cluster a colleage was running benchmarks on, where he would be consuming complex protobuf messages with the Kafka engine. Since clickhouse currently does not appear to re-use the generated de/serializer impl ( according to #59482 ), I realized that this try/catch flow behaviour was **_tanking_** performance, with a huge amount of CPU time spent in `libunwind`. Incidentally, we were generating _millions_ of `PROTOBUF_FIELD_NOT_REPEATED` in the `system.errors` table.

Screenshot 2024-07-17 at 01 44 00

### CC

- @vincentbernat per #41971
- @filimonov per #65297 
- @jkuklis for helping me with my junior cpp level

---

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Bypass try/catch flow when de/serializing nested repeated protobuf to nested columns ( fixes #41971 )

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

File: src/Formats/ProtobufSerializer.cpp [hunk 1]
```diff
@@ -3322,125 +3322,139 @@ namespace
                     }
                 }
 
+                /// Complex case: one or more columns are serialized as a nested message.
                 for (const auto & [field_descriptor, suffix] : field_descriptors_with_suffixes)
                 {
-                    if (!suffix.empty())
+                    if (suffix.empty())
+                        continue;
```
Comment (hileef) [inline src/Formats/ProtobufSerializer.cpp:3329]: This specific change is not required per se, but it arguably brings all relevant code paths into the diff.
If it may help the review, we can get rid of that 🙏

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit df482bbbba1461733b47a0edcfcc85767975c64f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69556/df482bbbba1461733b47a0edcfcc85767975c64f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/69432/6f9d1631e26bbb0263962c6d50c65e9ee2be561a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by Avogar** [comment]
@hileef Hi! Thank you for the PR, I will take a look at the code. Can you please fix style check first?
It complains that file `03234_proto_simple_nested_repeated_noexception.reference` is executable (reference files should be just text files) and style issue in file `ProtobufSerializer.cpp:3366` (no space after `for`)

**Comment by hileef** [comment]
Hello @Avogar , I'll get on that as soon as possible ( a bit later today ) 👍 Thank for the help 🙂

**Comment by hileef** [comment]
After fixing the style issues, I took the liberty of slightly adapting the test in order to properly work with the testing system ( format_schemas dir not automatically present , no formats in fasttest , use correct test DB ). If these changes are incorrect, please let me know.

At this point, the tests added in this PR do work, however I'm not sure why the remaining CI checks fail, and am looking forward to help on the topic :slightly_smiling_face: :pray:

**Comment by hileef** [comment]
I attempted the test `02490_benchmark_max_consecutive_errors` ( from [this CI run](https://s3.amazonaws.com/clickhouse-test-reports/69556/167196bdd20631d104a09a73e7b71c679edc5e85/stateless_tests__msan__%5B2_4%5D.html) )  on my local build of this branch,
and the test appeared to pass .... maybe this could be related to differences between the CI environment and my local setup ? 🤔 

In any case, the other test failures appear related to timeouts, so I'd be very interested in possibly relaunching the CI jobs that failed to check if they fail again 🙏

**Comment by Avogar** [comment]
`02490_benchmark_max_consecutive_errors ` test failure is not related to the chagnes, this test is flaky: https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMjQ5MF9iZW5jaG1hcmtfbWF4X2NvbnNlY3V0aXZlX2Vycm9ycycgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK
I will create a separate issue for it, don't worry about this test

**Comment by hileef** [comment]
Alright ! Thanks for letting me know and for the exploration URL, I didn't know this was publicly available 🙂 

Looking forward to hearing from you again once you've had an opportunity to review the code and/or
if you have some additional remarks on the other CI checks 🙏

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Looks good, thank you!
