### PR TITLE
MySQL binary protocol implementation for initial support of Tableau Online

### LINKED ISSUE #51103: MySQL compatibility: command \x16 is not implemented
When connecting Tableau to ClickHouse via MySQL interface, the following error is raised:

```
Code: 48. DB::Exception: Command \x16; is not implemented. (NOT_IMPLEMENTED) (version 23.6.1.518 (official build))
```

**How to reproduce**
* Which ClickHouse server version to use: latest head (23.6.1.518)
* Which interface to use, if matters: MySQL

**Error message and/or stacktrace**
```
2023.06.16 18:44:57.889906 [ 45 ] {} <Debug> MySQLHandler: Authentication for user default succeeded.
2023.06.16 18:44:57.889921 [ 45 ] {} <Debug> MYSQL-Session: f9042e6d-73b6-4e37-8955-0d66e881371c Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.06.16 18:44:57.890075 [ 45 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2023.06.16 18:44:57.890123 [ 45 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, displaySecretsInShowAndSelect, INTROSPECTION, SOURCES, CLUSTER ON *.* WITH GRANT OPTION
2023.06.16 18:44:57.890152 [ 45 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, displaySecretsInShowAndSelect, INTROSPECTION, SOURCES, CLUSTER ON *.* WITH GRANT OPTION
2023.06.16 18:44:57.890201 [ 45 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2023.06.16 18:44:57.890217 [ 45 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, displaySecretsInShowAndSelect, INTROSPECTION, SOURCES, CLUSTER ON *.* WITH GRANT OPTION
2023.06.16 18:44:57.890233 [ 45 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, displaySecretsInShowAndSelect, INTROSPECTION, SOURCES, CLUSTER ON *.* WITH GRANT OPTION
2023.06.16 18:44:57.932017 [ 45 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 0.
2023.06.16 18:44:57.973862 [ 45 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 0.
2023.06.16 18:44:58.015656 [ 45 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 0.
2023.06.16 18:44:58.015778 [ 45 ] {} <Debug> MYSQL-Session: f9042e6d-73b6-4e37-8955-0d66e881371c Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.06.16 18:44:58.015945 [ 45 ] {mysql:0:b52bbd39-c7e1-48f8-9d22-0d6f7d8882f0} <Debug> executeQuery: Query span trace_id for opentelemetry log: 00000000-0000-0000-0000-000000000000
2023.06.16 18:44:58.016092 [ 45 ] {mysql:0:b52bbd39-c7e1-48f8-9d22-0d6f7d8882f0} <Debug> executeQuery: (from 34.246.62.141:48070) SET SQL_AUTO_IS_NULL = 0 (stage: Complete)
2023.06.16 18:44:58.016352 [ 45 ] {mysql:0:b52bbd39-c7e1-48f8-9d22-0d6f7d8882f0} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2023.06.16 18:44:58.060260 [ 45 ] {} <Debug> MySQLHandler: Received command: 22. Connection id: 0.
2023.06.16 18:44:58.060656 [ 45 ] {} <Error> MySQLHandler: MySQLHandler: Cannot read packet: : Code: 48. DB::Exception: Command  is not implemented. (NOT_IMPLEMENTED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e37ca35 in /usr/bin/clickhouse
1. ? @ 0x000000000e586a30 in /usr/bin/clickhouse
2. DB::MySQLHandler::run() @ 0x0000000014d06ab7 in /usr/bin/clickhouse
3. Poco::Net::TCPServerConnection::start() @ 0x0000000017cb0574 in /usr/bin/clickhouse
4. Poco::Net::TCPServerDispatcher::run() @ 0x0000000017cb1791 in /usr/bin/clickhouse
5. Poco::PooledThread::run() @ 0x0000000017e2e547 in /usr/bin/clickhouse
6. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017e2bf7c in /usr/bin/clickhouse
7. ? @ 0x00007f090944f609 in ?
8. clone @ 0x00007f0909374133 in ?
 (version 23.6.1.518 (official build))
2023.06.16 18:44:58.103488 [ 45 ] {} <Debug> MySQLHandler: Received command: 1. Connection id: 0.
2023.06.16 18:44:58.919658 [ 45 ] {} <Trace> MySQLHandlerFactory: MySQL connection. Id: 1. Address: 34.246.62.141:42171
2023.06.16 18:44:58.919876 [ 45 ] {} <Trace> MySQLHandler: Sent handshake
2023.06.16 18:44:58.961150 [ 45 ] {} <Trace> MySQLHandler: payload size: 91
2023.06.16 18:44:58.961244 [ 45 ] {} <Trace> MySQLHandler: Capabilities: 431923853, max_packet_size: 1073741824, character_set: 255, user: default, auth_response length: 20, database: default, auth_plugin_name: mysql_native_password
2023.06.16 18:44:58.961376 [ 45 ] {} <Debug> MYSQL-Session: 191b7671-5e3e-4a84-a3af-67bb0eaabdbc Authenticating user 'default' from 34.246.62.141:42171
2023.06.16 18:44:58.961414 [ 45 ] {} <Debug> MYSQL-Session: 191b7671-5e3e-4a84-a3af-67bb0eaabdbc Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2023.06.16 18:44:58.961427 [ 45 ] {} <Debug> MySQLHandler: Authentication for user default succeeded.
2023.06.16 18:44:58.961442 [ 45 ] {} <Debug> MYSQL-Session: 191b7671-5e3e-4a84-a3af-67bb0eaabdbc Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2023.06.16 18:44:59.002641 [ 45 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 1.
2023.06.16 18:44:59.043873 [ 45 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 1.
2023.06.16 18:44:59.085114 [ 45 ] {} <Debug> MySQLHandler: Received command: 3. Connection id: 1.
2023.06.16 18:44:59.085229 [ 45 ] {} <Debug> MYSQL-Session: 191b7671-5e3e-4a84-a3af-67bb0eaabdbc Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.06.16 18:44:59.085341 [ 45 ] {mysql:1:b25fa4f1-1a22-4eed-8956-1a746dde0e27} <Debug> executeQuery: Query span trace_id for opentelemetry log: 00000000-0000-0000-0000-000000000000
2023.06.16 18:44:59.085457 [ 45 ] {mysql:1:b25fa4f1-1a22-4eed-8956-1a746dde0e27} <Debug> executeQuery: (from 34.246.62.141:42171) SET SQL_AUTO_IS_NULL = 0 (stage: Complete)
2023.06.16 18:44:59.085695 [ 45 ] {mysql:1:b25fa4f1-1a22-4eed-8956-1a746dde0e27} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2023.06.16 18:44:59.129101 [ 45 ] {} <Debug> MySQLHandler: Received command: 22. Connection id: 1.
2023.06.16 18:44:59.129286 [ 45 ] {} <Error> MySQLHandler: MySQLHandler: Cannot read packet: : Code: 48. DB::Exception: Command  is not implemented. (NOT_IMPLEMENTED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e37ca35 in /usr/bin/clickhouse
1. ? @ 0x000000000e586a30 in /usr/bin/clickhouse
2. DB::MySQLHandler::run() @ 0x0000000014d06ab7 in /usr/bin/clickhouse
3. Poco::Net::TCPServerConnection::start() @ 0x0000000017cb0574 in /usr/bin/clickhouse
4. Poco::Net::TCPServerDispatcher::run() @ 0x0000000017cb1791 in /usr/bin/clickhouse
5. Poco::PooledThread::run() @ 0x0000000017e2e547 in /usr/bin/clickhouse
6. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017e2bf7c in /usr/bin/clickhouse
7. ? @ 0x00007f090944f609 in ?
8. clone @ 0x00007f0909374133 in ?
 (version 23.6.1.518 (official build))
2023.06.16 18:44:59.171703 [ 45 ] {} <Debug> MySQLHandler: Received command: 1. Connection id: 1.
2023.06.16 18:45:01.249571 [ 96 ] {} <Debug> DNSResolver: Updating DNS cache
2023.06.16 18:45:01.249652 [ 96 ] {} <Debug> DNSResolver: Updated DNS cache
2023.06.16 18:45:01.260270 [ 286 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 4 entries to flush up to offset 4
2023.06.16 18:45:01.261644 [ 286 ] {} <Debug> SystemLog (system.query_log): Will use existing table system.query_log for QueryLog
2023.06.16 18:45:01.265807 [ 286 ] {} <Trace> system.query_log (3da47ab5-5f3d-4bdc-b81d-bc6b8bd7e41d): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2023.06.16 18:45:01.265877 [ 286 ] {} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 16.68 GiB.
2023.06.16 18:45:01.271013 [ 286 ] {} <Trace> MergedBlockOutputStream: filled checksums 20230616_1_1_0 (state Temporary)
2023.06.16 18:45:01.271594 [ 286 ] {} <Trace> system.query_log (3da47ab5-5f3d-4bdc-b81d-bc6b8bd7e41d): Renaming temporary part tmp_insert_20230616_1_1_0 to 20230616_4_4_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2023.06.16 18:45:01.272024 [ 286 ] {} <Trace> SystemLog (system.query_log): Flushed system log up to offset 4
```

### PR DESCRIPTION
**Pull request by slvrtrn**
Resolves #51103.

This PR allows connecting to Tableau Online, discovering the tables, and fetching the data. 

Tableau Online wraps everything into prepared statements, even the simplest `SELECT`s. However, it does not add the parameters to bind - everything is hardcoded into the query. The current MySQL interface implementation was missing binary protocol implementation, as well as `COM_STMT_PREPARE`, `COM_STMT_EXECUTE`, and `COM_STMT_CLOSE` handlers. This PR addresses this. 

Please note: the prepared statements implementation is pretty minimal, we do not support arguments binding yet, it is not required in this particular Tableau online use case. It will be implemented as a follow-up if necessary after extensive testing of Tableau Online in case we discover issues.

I also tweaked `SHOW COLUMNS` a bit as it did not 100% match the MySQL spec.

Corner cases of Decimal128 with precision > 65 or scale > 30 were also addressed, as this is the maximum according to [the spec](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html).

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The MySQL interface gained a minimal implementation of prepared statements, just enough to allow a connection from Tableau Online to ClickHouse via the MySQL connector.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 8483d1c701c56db00296ea5ad712e35f527c0579 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54115/8483d1c701c56db00296ea5ad712e35f527c0579/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
</table>

File: src/Interpreters/InterpreterShowColumnsQuery.cpp [hunk 1]
```diff
@@ -37,7 +37,7 @@ String InterpreterShowColumnsQuery::getRewrittenQuery()
 SELECT
     name AS field,
     type AS type,
-    startsWith(type, 'Nullable') AS null,
+    if(startsWith(type, 'Nullable'), 'YES', 'NO') AS `null`,
```
Comment (slvrtrn) [inline src/Interpreters/InterpreterShowColumnsQuery.cpp:40]: Style check does not like this particular line as it seems

File: src/Core/MySQL/PacketsProtocolText.h [hunk 2]
```diff
@@ -116,16 +116,29 @@ class ColumnDefinition : public IMySQLWritePacket, public IMySQLReadPacket
...
+        String name_,
+        uint16_t character_set_,
+        uint32_t column_length_,
+        ColumnType column_type_,
+        uint16_t flags_,
+        uint8_t decimals_);
 };
 
-ColumnDefinition getColumnDefinition(const String & column_name, const TypeIndex index);
+ColumnDefinition getColumnDefinition(const String & column_name, const DataTypePtr & data_type);
```
Comment (slvrtrn) [inline src/Core/MySQL/PacketsProtocolText.h:141]: will revert the formatting for this file

File: src/Core/MySQL/PacketsPreparedStatements.h [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+    {
+        // https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html#sect_protocol_com_stmt_prepare_response_ok
+        class PrepareStatementResponseOK : public IMySQLWritePacket
+        {
+        public:
+            uint8_t status = 0x00;
+            uint32_t statement_id;
+            uint16_t num_columns;
+            uint16_t num_params;
+            uint8_t reserved_1 = 0;
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsPreparedStatements.h:19]: `const uint8_t ...`

File: src/Core/MySQL/PacketsPreparedStatements.h [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+
+#include <Core/MySQL/IMySQLWritePacket.h>
+
+namespace DB
+{
+namespace MySQLProtocol
+{
+    namespace PreparedStatements
+    {
+        // https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html#sect_protocol_com_stmt_prepare_response_ok
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsPreparedStatements.h:11]: The referenced page contains:

```
if (packet_lenght > 12) {
--
int<2> | warning_count | Number of warnings
if capabilities & CLIENT_OPTIONAL_RESULTSET_METADATA {
int<1> | metadata_follows | Flag specifying if metadata are skipped or not. See enum_resultset_metadata
} – CLIENT_OPTIONAL_RESULTSET_METADATA {
} – packet_lenght > 12
```

In other words, field "warnings_count" is described as conditional (only if package_length > 12). What is "package_length" in this context and is it always > 12? Asking because we currently always send "warning_count".

File: src/Core/MySQL/PacketsPreparedStatements.cpp [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+
+namespace DB
+{
+namespace MySQLProtocol
+{
+    namespace PreparedStatements
+    {
+        size_t PrepareStatementResponseOK::getPayloadSize() const
+        {
+            return 13;
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsPreparedStatements.cpp:13]: I count 12 bytes (l. 18ff).

EDIT: Ah, with l. 24, it is 13 indeed. To make this more clear, maybe:

```cpp
static const auto resultset_metadata_none = '\n';
buffer.write(reinterpret_cast<const char *>(&resultset_metadata_none), 1);
```

Comment (rschu1ze) [reply src/Core/MySQL/PacketsPreparedStatements.cpp:13]: Btw., looking at the [docs](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html#sect_protocol_com_stmt_prepare_response_ok), the variable should actually be called `metadata_follows`.

File: src/Core/MySQL/PacketsProtocolText.cpp [hunk 6]
```diff
@@ -131,16 +134,25 @@ void ColumnDefinition::writePayloadImpl(WriteBuffer & buffer) const
...
     int flags = 0;
+    uint8_t decimals = 0;
+    TypeIndex type_index = data_type->getTypeId();
     switch (type_index)
     {
         case TypeIndex::UInt8:
-            column_type = ColumnType::MYSQL_TYPE_TINY;
-            flags = ColumnDefinitionFlags::BINARY_FLAG | ColumnDefinitionFlags::UNSIGNED_FLAG;
+            if (data_type->getName() == "Bool")
+            {
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolText.cpp:148]: (cosmetic: let's omit `{` and `}` for single-line if statements)

File: src/Core/MySQL/PacketsProtocolText.cpp [hunk 7]
```diff
@@ -131,16 +134,25 @@ void ColumnDefinition::writePayloadImpl(WriteBuffer & buffer) const
...
+                column_type = ColumnType::MYSQL_TYPE_BIT;
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolText.cpp:149]: Just curious: MySQL has the `BIT` type only since v8.0. Before that, one had to use `BOOL`/`BOOLEAN`. The latter are aliases of TINYINT, i.e. 1 byte integers. That's also what "Bool" is in ClickHouse. But what is `BIT` physically in MySQL? I had some trouble finding out. If it is a 64-bit value (and it seems at least so), then `BOOL`/`BOOLEAN` would probably better fits.

File: src/Core/MySQL/PacketsProtocolText.cpp [hunk 8]
```diff
@@ -173,30 +185,52 @@ ColumnDefinition getColumnDefinition(const String & column_name, const TypeIndex
...
             break;
         case TypeIndex::DateTime:
             column_type = ColumnType::MYSQL_TYPE_DATETIME;
             flags = ColumnDefinitionFlags::BINARY_FLAG;
             break;
-        case TypeIndex::String:
-        case TypeIndex::FixedString:
-            column_type = ColumnType::MYSQL_TYPE_STRING;
-            charset = CharacterSet::utf8_general_ci;
+        case TypeIndex::DateTime64:
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolText.cpp:204]:
```cpp
case TypeIndex::DateTime:
case TypeIndex::DateTime64:
            column_type = ColumnType::MYSQL_TYPE_DATETIME;
            flags = ColumnDefinitionFlags::BINARY_FLAG;
            break;
```

File: src/Core/MySQL/PacketsProtocolText.cpp [hunk 9]
```diff
@@ -173,30 +185,52 @@ ColumnDefinition getColumnDefinition(const String & column_name, const TypeIndex
...
+                column_type = ColumnType::MYSQL_TYPE_STRING;
+                charset = CharacterSet::utf8_general_ci;
+            }
+            else
+            {
+                column_type = ColumnType::MYSQL_TYPE_DECIMAL;
+                flags = ColumnDefinitionFlags::BINARY_FLAG;
+            }
             break;
+        }
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolText.cpp:227]: The reader wonders why `TypeIndex::Decimal256` is not handled. According to [CH docs](https://clickhouse.com/docs/en/sql-reference/data-types/decimal), the minimum scale is 39 and therefore outside of MySQL's accepted range (l. 214).

File: docs/en/sql-reference/statements/show.md [hunk 10]
```diff
@@ -208,7 +208,7 @@ The optional keyword `FULL` causes the output to include the collation, comment
 The statement produces a result table with the following structure:
 - field - The name of the column (String)
 - type - The column data type (String)
-- null - If the column data type is Nullable (UInt8)
+- null - `YES` if the column data type is Nullable, `NO` otherwise (UInt8)
```
Comment (slvrtrn) [inline docs/en/sql-reference/statements/show.md:211]: it's TEXT now I think (not UInt8)

File: src/Core/MySQL/PacketsProtocolText.cpp [hunk 11]
```diff
@@ -173,30 +185,52 @@ ColumnDefinition getColumnDefinition(const String & column_name, const TypeIndex
...
+            column_type = ColumnType::MYSQL_TYPE_DATETIME;
+            flags = ColumnDefinitionFlags::BINARY_FLAG;
+            break;
+        case TypeIndex::Decimal32:
+        case TypeIndex::Decimal64:
+            column_type = ColumnType::MYSQL_TYPE_DECIMAL;
+            flags = ColumnDefinitionFlags::BINARY_FLAG;
+            break;
+        case TypeIndex::Decimal128: {
+            // MySQL Decimal has max 65 precision and 30 scale
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolText.cpp:214]: I find proof of "max 65 precision" [here](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html) but the same page doesn't say the max scale is 30. Is there documented evidence of the latter?

File: docs/en/sql-reference/statements/show.md (hunk 10 above)
Comment (rschu1ze) [reply docs/en/sql-reference/statements/show.md:211]: It's actually `String` in ClickHouse lingo. Please just change it.

**Review by rschu1ze — COMMENTED** [review]
More comments are coming. Just dumping the first batch.

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 12]
```diff
@@ -0,0 +1,363 @@
...
+namespace DB
+{
+
+namespace MySQLProtocol
+{
+
+    namespace ProtocolBinary
+    {
+        ResultSetRow::ResultSetRow(
+            const Serializations & serializations_, const DataTypes & data_types_, const Columns & columns_, int row_num_)
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:30]: In C++, you generally want to keep
- the order of (initialized) member variables in the class declaration (header file),
- the order of constructor parameters (l. 30) and
- the order in the initialization list (l. 31)

the same. Deviating from this rule opens the door to subtle bugs.

File: src/Core/MySQL/PacketsProtocolBinary.h [hunk 13]
```diff
@@ -0,0 +1,45 @@
...
+
+        protected:
+            int row_num;
+            const Columns & columns;
+            const DataTypes & data_types;
+            const Serializations & serializations;
+
+            std::vector<String> serialized = std::vector<String>(columns.size());
+
+            size_t null_bitmap_size = (columns.size() + 7 + 2) / 8;
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.h:31]: It is not exactly clear where the constants come from. Maybe add a comment or a reference to the MySQL protocol docs.

Comment (rschu1ze) [reply src/Core/MySQL/PacketsProtocolBinary.h:31]: And should a "null bitmap" not have a NULL entry per row? So one would expect that the size depends on sth like `columns[0]->size()`.

EDIT: Perhaps it is because the class describes a single *row*? In that case, `null_bitmap` is a strange name. Maybe just `null_columns`.

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 14]
```diff
@@ -0,0 +1,363 @@
...
+                DataTypePtr data_type = removeLowCardinality(removeNullable((data_types[i])));
+                TypeIndex type_index = data_type->getTypeId();
+                switch (type_index)
+                {
+                    case TypeIndex::Int8:
+                        payload_size += 1;
+                        break;
+                    case TypeIndex::UInt8:
+                        if (data_type->getName() == "Bool")
+                        {
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:56]: (see my other comment about `BIT` vs. `BOOL`)

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 15]
```diff
@@ -0,0 +1,363 @@
...
+                    case TypeIndex::UInt32:
+                    case TypeIndex::Float32:
+                        payload_size += 4;
+                        break;
+                    case TypeIndex::Int64:
+                    case TypeIndex::UInt64:
+                    case TypeIndex::Float64:
+                        payload_size += 8;
+                        break;
+                    case TypeIndex::Date: {
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:78]:
```cpp
case TypeIndex::Date:
case TypeIndex::Date32: {
                        payload_size += 5;
                        break;
```

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 16]
```diff
@@ -0,0 +1,363 @@
...
+                        payload_size += 5;
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:79]: So why does Date / Date32 have 5 bytes?

EDIT: Ah, I see. Maybe rewrite to `payload_size += 1 + 4; // date byte count + date

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 17]
```diff
@@ -0,0 +1,363 @@
...
+                if (col->isNullAt(row_num))
+                {
+                    continue;
+                }
+
+                DataTypePtr data_type = removeLowCardinality(removeNullable((data_types[i])));
+                TypeIndex type_index = data_type->getTypeId();
+                switch (type_index)
+                {
+                    case TypeIndex::UInt8: {
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:168]: Could we retain the same order of cases in this method as in the constructor? UInt8, Int8, UInt16, Int16, ...

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 18]
```diff
@@ -0,0 +1,363 @@
...
+                        UInt8 value = assert_cast<const ColumnVector<UInt8> &>(*col).getData()[row_num];
+                        if (data_type->getName() == "Bool")
+                        {
+                            buffer.write(static_cast<char>(1));
+                        }
+                        buffer.write(reinterpret_cast<char *>(&value), 1);
+                        break;
+                    }
+                    case TypeIndex::UInt16: {
+                        UInt16 value = assert_cast<const ColumnVector<UInt16> &>(*col).getData()[row_num];
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:178]: We are casting `*col` to the specific column implementation of the corresponding type (e.g. `ColumnVector<UInt16>`). That is okay.

But: This only works if `col` is not of low-cardinality (`ColumnLowCardinality`), or nullable (ColumnNullable), sparse (ColumnSparse) or const (ColumnConst) type. These classes are (possibly chained) wrappers around the actual column structure. In l. 164, we are stripping the low-cardinality and nullness of the *datatype* away, but we would need to do something equivalent for `col`.  Check e.g. `recursiveRemoveSparse()` (Columns/ColumnSparse.h), etc.

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 19]
```diff
@@ -0,0 +1,363 @@
...
+                    case TypeIndex::Float64: {
+                        Float64 value = assert_cast<const ColumnVector<Float64> &>(*col).getData()[row_num];
+                        buffer.write(reinterpret_cast<char *>(&value), 8);
+                        break;
+                    }
+                    case TypeIndex::Date: {
+                        UInt16 value = assert_cast<const ColumnVector<UInt16> &>(*col).getData()[row_num];
+                        LocalDate ld = LocalDate(DayNum(value));
+                        buffer.write(static_cast<char>(4)); // bytes_following
+                        auto year = ld.year();
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:226]: Whenever dealing with bits and bytes in C++ and not mere glue code, it is recommended to write out the actual types (e.g. `unsigned short` in l. 226) instead of `auto`.

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 20]
```diff
@@ -0,0 +1,363 @@
...
+                        buffer.write(reinterpret_cast<const char *>(&year), 2);
+                        buffer.write(reinterpret_cast<const char *>(&month), 1);
+                        buffer.write(reinterpret_cast<const char *>(&day), 1);
+                        break;
+                    }
+                    case TypeIndex::DateTime: {
+                        UInt32 value = assert_cast<const ColumnVector<UInt32> &>(*col).getData()[row_num];
+                        String timezone = getDateTimeTimezone(*data_type);
+                        LocalDateTime ldt = LocalDateTime(value, DateLUT::instance(timezone));
+                        int year = ldt.year();
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:250]: `ldt.year()` returns `unsigned short`, not `int`. Same in below lines.

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 21]
```diff
@@ -0,0 +1,363 @@
...
+                        int month = ldt.month();
+                        int day = ldt.day();
+                        int hour = ldt.hour();
+                        int minute = ldt.minute();
+                        int second = ldt.second();
+                        bool has_time = !(hour == 0 && minute == 0 && second == 0);
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:256]: That's interesting. DateTimes in ClickHouse are never "timeless", i.e. there is no distinction of values with hour/minute/second = 0 from values where these components are != 0. Does it really make a difference in MySQL?

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 22]
```diff
@@ -0,0 +1,363 @@
...
+                        {
+                            payload_size += 8;
+                        }
+                        else
+                        {
+                            payload_size += 5;
+                        }
+                        break;
+                    }
+                    default:
```
Comment (rschu1ze) [inline src/Core/MySQL/PacketsProtocolBinary.cpp:142]: Should there be a handler for Decimal?

**Review by rschu1ze — COMMENTED** [review]
Second batch of comments.

File: src/Server/MySQLHandler.cpp [hunk 23]
```diff
@@ -371,6 +384,79 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+    payload.readStrict(reinterpret_cast<char *>(&statement_id), 4);
+
+    if (!prepared_statements_map.contains(statement_id))
+    {
+        LOG_ERROR(log, "Could not find prepared statement with id {}", statement_id);
+        packet_endpoint->sendPacket(ERRPacket(), true);
+        return;
+    }
+
+    // Temporary workaround as we work only with queries that do not bind any parameters atm
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:441]: Not sure but should we put in an assert or check somewhere that throws an exception when someone tries to run a prepared statement with actual parameters. Better safe than sorry.

File: src/Server/MySQLHandler.h [hunk 24]
```diff
@@ -76,6 +82,10 @@ class MySQLHandler : public Poco::Net::TCPServerConnection
     using Replacements = std::unordered_map<std::string, ReplacementFn>;
     Replacements replacements;
 
+    uint32_t current_prepared_statement_id = 0;
+    using PreparedStatementsMap = std::unordered_map<uint32_t, String>;
+    PreparedStatementsMap prepared_statements_map;
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.h:87]: Just `prepared_statements`

File: src/Server/MySQLHandler.h [hunk 25]
```diff
@@ -76,6 +82,10 @@ class MySQLHandler : public Poco::Net::TCPServerConnection
     using Replacements = std::unordered_map<std::string, ReplacementFn>;
     Replacements replacements;
 
+    uint32_t current_prepared_statement_id = 0;
+    using PreparedStatementsMap = std::unordered_map<uint32_t, String>;
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.h:86]: \+ `/// statement_id --> statement`

File: src/Server/MySQLHandler.cpp [hunk 26]
```diff
@@ -371,6 +384,79 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+    ReadBufferFromString com_query_payload(prepared_statements_map.at(statement_id));
+    MySQLHandler::comQuery(com_query_payload, true);
+};
+
+void MySQLHandler::comStmtClose(ReadBuffer & payload)
+{
+    uint32_t statement_id;
+    payload.readStrict(reinterpret_cast<char *>(&statement_id), 4);
+
+    if (prepared_statements_map.contains(statement_id))
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:451]: Does access to the map need synchronization? (i.e. some mutex?). I mean even if it is local to a single MySQLHandler, I would not risk races (due to network package delays or whatever).

File: src/Server/MySQLHandler.cpp [hunk 27]
```diff
@@ -371,6 +384,79 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
     }
 }
 
+void MySQLHandler::comStmtPrepare(DB::ReadBuffer & payload)
+{
+    if (prepared_statements_map.size() > 10000) /// Shouldn't happen in reality as COM_STMT_CLOSE cleans up the elements
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:389]: Let's make this a constant:

```cpp
static constexpr auto MAX_PREPARED_STATEMENTS = 10'000;
if (prepared_statements_map.size() > MAX_PREPARED_STATEMENTS)
```

File: src/Server/MySQLHandler.cpp [hunk 28]
```diff
@@ -371,6 +384,79 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+        prepared_statements_map.clear();
+        packet_endpoint->sendPacket(ERRPacket(), true);
+        return;
+    }
+
+    String query;
+    readStringUntilEOF(query, payload);
+
+    uint32_t statement_id = current_prepared_statement_id;
+    if (current_prepared_statement_id == std::numeric_limits<uint32_t>::max())
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:402]: It will wrap around automatically if it's the max possible value minus one, no need for l. 402-407.

**Review by rschu1ze — COMMENTED** [review]
Dumping the 3rd batch of comments. More tomorrow.

File: src/Core/MySQL/PacketsPreparedStatements.cpp [hunk 29]
```diff
@@ -0,0 +1,34 @@
+#include <Core/MySQL/PacketsPreparedStatements.h>
+#include <IO/WriteHelpers.h>
+#include <Common/logger_useful.h>
+
+namespace DB
+{
+namespace MySQLProtocol
+{
+    namespace PreparedStatements
```
[the remark this answers is not in the document]
Comment (slvrtrn) [reply src/Core/MySQL/PacketsPreparedStatements.cpp:9]: Can I configure clang-format to do that for me somehow? I'd prefer to have it that way as well. However, with clang-format config from the root, it keeps shifting the third one to the right.

File: src/Core/MySQL/PacketsProtocolText.cpp (hunk 7 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolText.cpp:149]: I think we can use TINYINT for that as well. I will check.

File: src/Core/MySQL/PacketsPreparedStatements.cpp (hunk 5 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsPreparedStatements.cpp:13]: I think I can make it more clear by defining it as a sum with comments on what each portion of bytes represents.

File: src/Core/MySQL/PacketsProtocolBinary.h (hunk 13 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.h:31]: `null_bitmap` is just how it's named in [the doc](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_binary_resultset.html#sect_protocol_binary_resultset_row). I think we will introduce even more confusion if we change the name.

File: src/Core/MySQL/PacketsProtocolBinary.cpp (hunk 16 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.cpp:79]: Yes, I will rewrite all of these calculations to a more explicit sum instead, with additional commentaries. That's how Go MySQL driver does it actually. It will be better for understanding.

File: src/Core/MySQL/PacketsProtocolBinary.cpp (hunk 18 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.cpp:178]: LowCardinality and Nullable are removed prior to that, so I assumed it should always work as intended.

File: src/Core/MySQL/PacketsProtocolBinary.cpp (hunk 21 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.cpp:256]: Yes, as it supports packet compression in binary (if I understand the question correctly).

> Type to store a MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME and MYSQL_TYPE_TIMESTAMP fields in the binary protocol.
>
> To save space the packet can be compressed:
>
> if year, month, day, hour, minutes, seconds and microseconds are all 0, length is 0 and no other field is sent.
> if hour, seconds and microseconds are all 0, length is 4 and no other field is sent.
> if microseconds is 0, length is 7 and micro_seconds is not sent.
> otherwise the length is 11

File: src/Core/MySQL/PacketsProtocolBinary.cpp (hunk 22 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.cpp:142]: Actually, no, cause it is just a string(lenenc) handled by the default case. Maybe I should add a comment about that.

File: src/Core/MySQL/PacketsProtocolBinary.cpp [hunk 30]
```diff
@@ -0,0 +1,363 @@
...
+                            payload_size += 5;
+                        }
+                        break;
+                    }
+                    case TypeIndex::DateTime64: {
+                        const auto * date_time_type = typeid_cast<const DataTypeDateTime64 *>(data_type.get());
+                        UInt32 scale = date_time_type->getScale();
+
+                        static constexpr UInt32 MaxScale = DecimalUtils::max_precision<DateTime64>;
+                        scale = scale > MaxScale ? MaxScale : scale;
```
[the remark this answers is not in the document]
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.cpp:106]: Fair enough. This is a copy-pasta from the serialization internals.

File: src/DataTypes/DataTypesDecimal.cpp [hunk 31]
```diff
@@ -31,6 +31,12 @@ std::string DataTypeDecimal<T>::doGetName() const
 template <is_decimal T>
 std::string DataTypeDecimal<T>::getSQLCompatibleName() const
 {
+    /// See https://dev.mysql.com/doc/refman/8.0/en/precision-math-decimal-characteristics.html
+    /// DECIMAL(M,D)
+    /// M is the maximum number of digits (the precision). It has a range of 1 to 65.
+    /// D is the number of digits to the right of the decimal point (the scale). It has a range of 0 to 30 and must be no larger than M.
+    if (this->precision > 65 || this->scale > 30)
+        return "TEXT";
```
[the remark this answers is not in the document]
Comment (slvrtrn) [reply src/DataTypes/DataTypesDecimal.cpp:39]: This is complicated. QuickSight, for example, won't like it: https://github.com/ClickHouse/ClickHouse/issues/53482

File: src/Server/MySQLHandler.cpp (hunk 26 above)
Comment (slvrtrn) [reply src/Server/MySQLHandler.cpp:451]: This is a good one. I assumed that we should not have race conditions here due to 1 MySQLHandler/thread. Will wrap it 👍

File: docker/test/integration/mysql_java_client/PreparedStatementsTest.java [hunk 32]
```diff
@@ -0,0 +1,177 @@
...
+            conn.close();
+        } catch (Exception e) {
+            e.printStackTrace();
+            System.exit(1);
+        }
+    }
+
+    private static void testSimpleDataTypes(Connection conn) throws SQLException {
+        System.out.println("### testSimpleDataTypes");
+        ResultSet rs = conn.prepareStatement("SELECT * FROM ps_simple_data_types").executeQuery();
```
[the remark this answers is not in the document]
Comment (slvrtrn) [reply docker/test/integration/mysql_java_client/PreparedStatementsTest.java:60]: This is it: https://github.com/ClickHouse/ClickHouse/blob/17cb6a8e3f0fa8c8f3c65834e968282aef2a343c/tests/integration/test_mysql_protocol/prepared_statements_test.sql

Here's how we read it: https://github.com/ClickHouse/ClickHouse/pull/54115/files#diff-58dd244b6eaf31eb920fcd27651cd8e6ffe6c9cc614e812c6a1a4958bcbb0678R812-R818

File: src/Storages/System/InformationSchema/schemata.sql [hunk 33]
```diff
@@ -1,26 +1,33 @@
...
-) AS
-SELECT
-    name AS catalog_name,
-    name AS schema_name,
-    'default' AS schema_owner,
-    NULL AS default_character_set_catalog,
-    NULL AS default_character_set_schema,
-    NULL AS default_character_set_name,
-    NULL AS sql_path
+    (
```
Comment (rschu1ze) [inline src/Storages/System/InformationSchema/schemata.sql:2]: Thoughts about the changes in `information_schema`:
- even if needed by Tableau Online, they are technically independent of the binary protocol implementation, and should be pushed as a separate PR
- [Our docs](https://clickhouse.com/docs/en/operations/system-tables/information_schema) do not mention that columns in `information_schema.schemata` can be accessed both in a lower-case and an upper-case form (`catalog_name` vs. `CATALOG_NAME`). It has been like that before your PR, but now is a good time to correct this.
- Upper-case name were previously implemented using alias columns ([docs](https://clickhouse.com/docs/en/sql-reference/statements/create/table#alias)). This had the specific effect that `SELECT *` excluded them, which is the behavior one would intuitively expect. This PR makes `SELECT *` show every column twice - unbeautiful, to be honest. What was the reason for that? Does Tableau Online execute `SELECT *` and expect uppercase column names? A less invasive alternative would be to retain the alias expressions in the view definition but somehow teach Tableau Online to apply setting `asteriks_include_alias_columns`. This will achieve the same behavior as this PR does.

File: src/Storages/System/InformationSchema/tables.sql [hunk 34]
```diff
@@ -1,17 +1,35 @@
...
+     `TABLE_SCHEMA` String,
+     `TABLE_NAME` String,
+     `TABLE_TYPE` String,
+     `TABLE_COMMENT` String,
+     `TABLE_COLLATION` String
+        ) AS
+SELECT database             AS `table_catalog`,
+       database             AS `table_schema`,
+       name                 AS `table_name`,
+       comment              AS `table_comment`,
```
Comment (rschu1ze) [inline src/Storages/System/InformationSchema/tables.sql:19]: Thoughts:
- Looking at [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/information-schema-tables-table.html), their version of `INFORMATION_SCHEMA.TABLES` includes many more fields. Your PR merely adds `table_comment` and `table_collation`. Wondering that Tableau Online does not complain while there are still missing fields?
- Let's keep fields `comment` and `table_type` in l. 6/7 and l. 19-26 in the same order.
- Please don't forget to document the new fields [here](https://clickhouse.com/docs/en/operations/system-tables/information_schema#columns), respectively update the type of existing fields.
- Same issue exists with alias expressions vs. duplicated columns as in `INFORMATION_SCHEMA.SCHEMATA`.
- Hardcoding the table collation as `utf8mb4_0900_ai_ci` is weird. 1. ClickHouse has no per-column/per-table/per-schema collations. We can surely hardcode something Unicode-like but then let's display something more generic, e.g. just `utf8` - assuming Tableau Online does not expect exactly `utf8mb4_0900_ai_ci`.

File: tests/integration/test_mysql_protocol/prepared_statements_test.sql [hunk 35]
```diff
@@ -0,0 +1,127 @@
+CREATE TABLE ps_simple_data_types
```
Comment (rschu1ze) [inline tests/integration/test_mysql_protocol/prepared_statements_test.sql:1]: Let's add either `DROP TABLE ps_simple_data_types` before l. 1 (to remove remnants) OR replace `CREATE TABLE [...]` by `CREATE OR REPLACE TABLE [...]`

File: tests/integration/test_mysql_protocol/prepared_statements_test.sql [hunk 36]
```diff
@@ -0,0 +1,127 @@
...
+    nlc LowCardinality(Nullable(String))
+) ENGINE MergeTree ORDER BY s;
+
+INSERT INTO ps_string_types
+VALUES ('foo', 'bar', 'qaz', 'qux'),
+       ('42', NULL, 'test', NULL);
+
+CREATE TABLE ps_decimal_types
+(
+    d32         Decimal(9, 2),
```
Comment (rschu1ze) [inline tests/integration/test_mysql_protocol/prepared_statements_test.sql:45]: You probably want to use aliases of Decimal (e.g. Decimal32) instead of `Decimal(9,2)` for better readability. https://clickhouse.com/docs/en/sql-reference/data-types/decimal

File: src/Core/MySQL/PacketsPreparedStatements.cpp (hunk 29 above)
[the remark this answers is not in the document]
Comment (slvrtrn) [reply src/Core/MySQL/PacketsPreparedStatements.cpp:9]: it should be set in the project .clang-format like:

```yaml
NamespaceIndentation: None
RemoveBracesLLVM: true
```

File: src/Core/MySQL/PacketsProtocolText.cpp (hunk 7 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolText.cpp:149]: It should work at least since MySQL 5.7: https://dev.mysql.com/doc/refman/5.7/en/bit-type.html

SO suggests it is this way since at least 2008: https://stackoverflow.com/a/290253/4575540

File: src/Core/MySQL/PacketsProtocolBinary.cpp (hunk 14 above)
Comment (slvrtrn) [reply src/Core/MySQL/PacketsProtocolBinary.cpp:56]: Isn't this one coming from ClickHouse itself?

File: src/Server/MySQLHandler.cpp (hunk 23 above)
Comment (slvrtrn) [reply src/Server/MySQLHandler.cpp:441]: for this, we need to parse the actual parameters from the incoming packet, and it has not been implemented yet...

File: src/Storages/System/InformationSchema/schemata.sql (hunk 33 above)
Comment (slvrtrn) [reply src/Storages/System/InformationSchema/schemata.sql]: I will create a new PR for information_schema changes. I reverted the changes for now.

File: src/Server/MySQLHandler.h [hunk 37]
```diff
@@ -76,6 +88,10 @@ class MySQLHandler : public Poco::Net::TCPServerConnection
     using Replacements = std::unordered_map<std::string, ReplacementFn>;
     Replacements replacements;
 
+    std::mutex prepared_statements_mutex;
+    UInt32 current_prepared_statement_id = 0;
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.h:92]: Let's add `TSA_GUARDED_BY(prepared_statements_mutex)` behind l. 92 and l. 93. This enables Thread Safety Analysis (TSA) which is a compiler extension (kind of) that checks if synchronization is implemented properly.

File: src/Server/MySQLHandler.cpp [hunk 38]
```diff
@@ -371,6 +384,81 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+    }
+
+    prepared_statements.emplace(statement_id, statement);
+    return std::make_pair(true, statement_id);
+};
+
+void MySQLHandler::erasePreparedStatement(UInt32 statement_id)
+{
+    std::lock_guard<std::mutex> lock(prepared_statements_mutex);
+    if (prepared_statements.contains(statement_id))
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:458]: No need for `.contains()`, `erase()` doesn't complain if the given element is not contained.

File: src/Server/MySQLHandler.cpp [hunk 39]
```diff
@@ -371,6 +384,81 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+            log,
+            "Failed to store a new statement `{}` with id {}; it is already taken by `{}`",
+            statement,
+            statement_id,
+            prepared_statements.at(statement_id));
+        return std::make_pair(false, 0);
+    }
+
+    prepared_statements.emplace(statement_id, statement);
+    return std::make_pair(true, statement_id);
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:452]: `return {true, statement_id};` (semantic sugar)

(similar syntax can be used above)

File: src/Server/MySQLHandler.cpp [hunk 40]
```diff
@@ -371,6 +384,81 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+    static constexpr size_t MAX_PREPARED_STATEMENTS = 10'000;
+    std::lock_guard<std::mutex> lock(prepared_statements_mutex);
+    if (prepared_statements.size() > MAX_PREPARED_STATEMENTS) /// Shouldn't happen in reality as COM_STMT_CLOSE cleans up the elements
+    {
+        LOG_ERROR(log, "Too many prepared statements");
+        current_prepared_statement_id = 0;
+        prepared_statements.clear();
+        return std::make_pair(false, 0);
+    }
+    uint32_t statement_id = current_prepared_statement_id++;
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:436]: Legit statement, but for simplicity, something like this is preferred:

```cpp
uint32_t statement_id = current_prepared_statement_id;
++current_prepared_statement_id;
```

File: src/Server/MySQLHandler.cpp [hunk 41]
```diff
@@ -371,6 +384,81 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
...
+    else
+        packet_endpoint->sendPacket(ERRPacket(), true);
+}
+
+void MySQLHandler::comStmtExecute(ReadBuffer & payload)
+{
+    uint32_t statement_id;
+    payload.readStrict(reinterpret_cast<char *>(&statement_id), 4);
+
+    if (!prepared_statements.contains(statement_id))
```
Comment (rschu1ze) [inline src/Server/MySQLHandler.cpp:403]: `prepared_statements` must safely only be used under the mutex. My other comment suggests TSA. It would make the compiler scream and cry about this.

**Review by rschu1ze — APPROVED** [review]
Lgtm, thanks.

Kindly look at the remaining (mostly small) comments, we can submit afterwards.

File: src/Core/MySQL/PacketsProtocolBinary.cpp (hunk 18 above)
Comment (rschu1ze) [reply src/Core/MySQL/PacketsProtocolBinary.cpp]: They are only removed from the data type, not from the actual data. I am pretty sure this will go boom, please try it out.

**Review by rschu1ze — APPROVED** [review]

**Review by rschu1ze — APPROVED** [review]

**Comment by MaceWindu** [comment]
Is it possible to disable this feature using CH option? It introduce several protocol violations making it unusable (I will try to fill found issues if they are not reported yet) as client library now switch to binary protocol

**Comment by rschu1ze** [comment]
@MaceWindu No, it is not possible to disable the binary protocol as it an integral part of the MySQL wire protocol. If you run into problems due to this PR, kindly open an [issue](https://github.com/ClickHouse/ClickHouse/issues), ideally with a small example that doesn't work.
