### PR TITLE
Fix if function with NULLs

### LINKED ISSUE #9253: Wrong function results on typed Nullable. Inconsistent with results on Nullable(Nothing)
**Describe the bug or unexpected behaviour**
Clickhouse version 19.14.7.15
set  join_use_nulls = 1 
sql
```
SELECT
    k,
    b_num,
    isNull(b_num),
    if(b_num = 0, -1, b_num),
    if(isNull(b_num), -1, b_num),
    b_str,
    isNull(b_str),
    empty(b_str),
    if(isNull(b_str), 'Others', b_str),
    if(empty(b_str), 'Others', b_str)
FROM
(
    SELECT
        number AS k,
        toInt8(number) AS a_num,
        toString(number) AS a_str
    FROM system.numbers
    LIMIT 10
)
LEFT JOIN
(
    SELECT
        number AS k,
        toInt8(number) AS b_num,
        toString(number) AS b_str
    FROM system.numbers
    LIMIT 5, 10
) USING (k)
ORDER BY k ASC
```

Returned columns
` if(equals(b_num, 0), -1, b_num)`
 and 
`if(empty(b_str), 'Others', b_str)`
  are not correct.

Returned result detail
```
┌─k─┬─b_num─┬─isNull(b_num)─┬─if(equals(b_num, 0), -1, b_num)─┬─if(isNull(b_num), -1, b_num)─┬─b_str─┬─isNull(b_str)─┬─empty(b_str)─┬─if(isNull(b_str), 'Others', b_str)─┬─if(empty(b_str), 'Others', b_str)─┐
│ 0 │  ᴺᵁᴸᴸ │             1 │                              -1 │                           -1 │ ᴺᵁᴸᴸ  │             1 │         ᴺᵁᴸᴸ │ Others                             │ Others                            │
│ 1 │  ᴺᵁᴸᴸ │             1 │                              -1 │                           -1 │ ᴺᵁᴸᴸ  │             1 │         ᴺᵁᴸᴸ │ Others                             │ Others                            │
│ 2 │  ᴺᵁᴸᴸ │             1 │                              -1 │                           -1 │ ᴺᵁᴸᴸ  │             1 │         ᴺᵁᴸᴸ │ Others                             │ Others                            │
│ 3 │  ᴺᵁᴸᴸ │             1 │                              -1 │                           -1 │ ᴺᵁᴸᴸ  │             1 │         ᴺᵁᴸᴸ │ Others                             │ Others                            │
│ 4 │  ᴺᵁᴸᴸ │             1 │                              -1 │                           -1 │ ᴺᵁᴸᴸ  │             1 │         ᴺᵁᴸᴸ │ Others                             │ Others                            │
│ 5 │     5 │             0 │                               5 │                            5 │ 5     │             0 │            0 │ 5                                  │ 5                                 │
│ 6 │     6 │             0 │                               6 │                            6 │ 6     │             0 │            0 │ 6                                  │ 6                                 │
│ 7 │     7 │             0 │                               7 │                            7 │ 7     │             0 │            0 │ 7                                  │ 7                                 │
│ 8 │     8 │             0 │                               8 │                            8 │ 8     │             0 │            0 │ 8                                  │ 8                                 │
│ 9 │     9 │             0 │                               9 │                            9 │ 9     │             0 │            0 │ 9                                  │ 9                                 │
└───┴───────┴───────────────┴─────────────────────────────────┴──────────────────────────────┴───────┴───────────────┴──────────────┴────────────────────────────────────┴───────────────────────────────────┘
 ```

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong result for `if()` with NULLs in condition.

Detailed description / Documentation draft:
It also contains some improvements in case when `if` condition is ColumnConst.

Closes #9253

### CODE REVIEW

File: src/Columns/IColumn.h [hunk 1]
```diff
@@ -225,6 +225,12 @@ class IColumn : public COW<IColumn>
     using Filter = PaddedPODArray<UInt8>;
     virtual Ptr filter(const Filter & filt, ssize_t result_size_hint) const = 0;
 
+    /// Replace elements that match the filter with defaults. If inverted replaces not matched elements.
+    virtual Ptr setDefaults(const Filter &, bool /*inverted*/) const
```
Comment (KochetovNicolai) [inline src/Columns/IColumn.h:229]: This method is not used. Can we remove it?

Comment (4ertus2) [reply src/Columns/IColumn.h:229]: Look at `ColumnNullable::getNestedColumnCopy()`. We need zero UInt8 values if we get nested column from nullable column in cases where NULL equivalent to zero. In this PR it called from `if` over Nullable. There we change conditional column with nested one.

Comment (KochetovNicolai) [reply src/Columns/IColumn.h:229]: Ok.
Probably, we can use logical `and` function with nested column and null mask?
I just don't like the fact that this function is not implemented for most of the columns. Also it doesn't speed up anything.

File: src/Columns/ColumnNullable.h [hunk 2]
```diff
@@ -121,6 +121,7 @@ class ColumnNullable final : public COWHelper<IColumn, ColumnNullable>
     const IColumn & getNestedColumn() const { return *nested_column; }
 
     const ColumnPtr & getNestedColumnPtr() const { return nested_column; }
+    ColumnPtr getNestedColumnCopy() const;
```
Comment (KochetovNicolai) [inline src/Columns/ColumnNullable.h:124]: Comment is needed.
It is not obvious why it is not just `IColumn::mutate()` or `cloneResized` (because we replace nulls to zeroes).
And (why) it works only for numbers.

File: src/Functions/if.cpp [hunk 3]
```diff
@@ -656,30 +656,83 @@ class FunctionIf : public FunctionIfBase</*null_is_false=*/false>
...
+        if (const auto * nullable = checkAndGetColumn<ColumnNullable>(*not_const_condition))
         {
+            ColumnPtr new_cond_column = nullable->getNestedColumnPtr();
+            size_t column_size = arg_cond.column->size();
+
+            if (cond_is_null) /// Nullable(Nothing)
+                new_cond_column = ColumnConst::create(ColumnUInt8::create(1, 0), column_size);
+            else if (checkAndGetColumn<ColumnUInt8>(*new_cond_column))
+            {
+                new_cond_column = nullable->getNestedColumnCopy(); /// zero NULLs in ColumnUInt8
```
Comment (KochetovNicolai) [inline src/Functions/if.cpp:717]: If we know that column is `Nullable(UInt8)`, we can write simple loop which calculates logical `and` even right here.
Is it always true, btw?

Comment (KochetovNicolai) [reply src/Functions/if.cpp:717]: > Is it always true, btw?

It seems to be so.

**Review by KochetovNicolai — CHANGES_REQUESTED** [review]
Generally it's ok. But I would like to remove new method from `IColumn`

File: src/Functions/if.cpp (hunk 3 above)
Comment (4ertus2) [reply src/Functions/if.cpp]: The source column is const here. It's not clear if we could change nested column inplace. I've created inplace `ColumnVector::applyZeroMap()` instead of `getNestedColumnCopy()`. We could make optimisation for Uint8 with logical `and` later. It think there would be not much profit of optimisation here cause we cannot avoid column copy.

Comment (KochetovNicolai) [reply src/Functions/if.cpp]: We *almost* can avoid copying.
Right now we can call `IColumn::mutate()` for filter, and if it has `ref_count = 1`, it won't be copied.
The only problem that we have not information if we need this column later. And functions can't change arguments in block in current interface.

**Review by KochetovNicolai — APPROVED** [review]

File: src/Functions/if.cpp (hunk 3 above)
Comment (4ertus2) [reply src/Functions/if.cpp]: Yup, there's posibility to change but it's dangerous cause contradicts the function interface. There're no such guaranties here.

**Comment by filimonov** [comment]
Backport to 20.3 is needed
