### PR TITLE
Fix: integer overflow in configuration settings.

### LINKED ISSUE #83374: Cache expiration overflow
### Describe the bug

Easy to reproduce.

### How to reproduce

With UBSAN, use these server settings:

```xml
<access_control_improvements>
    <role_cache_expiration_time_seconds>2147483647</role_cache_expiration_time_seconds>
</access_control_improvements>
```

### Error message and/or stacktrace

Stack trace:

```
src/Access/RoleCache.cpp:60:70: runtime error: signed integer overflow: 2147483647 * 1000 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/Access/RoleCache.cpp:60:70 
2025.07.07 08:31:26.707657 [ 2411142 ] {} <Trace> BaseDaemon: Received signal -3
2025.07.07 08:31:26.707760 [ 2411773 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.07.07 08:31:26.707782 [ 2411773 ] {} <Fatal> BaseDaemon: (version 25.7.1.2566 (official build), build id: 80F3F5C05DC732C70598AF6CC3EA96A32CFF63DF, git hash: c3ff0f14707b859ff99f05aba642bef42b255451, architecture: x86_64) (from thread 2411136) Received signal -3
2025.07.07 08:31:26.707791 [ 2411773 ] {} <Fatal> BaseDaemon: Signal description: sanitizer trap
2025.07.07 08:31:26.707792 [ 2411773 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2025.07.07 08:31:26.707801 [ 2411773 ] {} <Fatal> BaseDaemon: Stack trace: 0x000063596e7c0c43 0x0000635975ff166b 0x00006359604fcd30 0x00006359605075c7 0x000063597720f88b 0x0000635977076f27 0x000063596ebc9f9b 0x0000635984f4b77b 0x000063596ebaea5b 0x000063596ebaab2c 0x000063596050e1e1 0x00007b3b9542a338 0x00007b3b9542a3fb 0x00006359604f302e
2025.07.07 08:31:26.707806 [ 2411773 ] {} <Fatal> BaseDaemon: ########################################
2025.07.07 08:31:26.707812 [ 2411773 ] {} <Fatal> BaseDaemon: (version 25.7.1.2566 (official build), build id: 80F3F5C05DC732C70598AF6CC3EA96A32CFF63DF, git hash: c3ff0f14707b859ff99f05aba642bef42b255451) (from thread 2411136) (no query) Received signal sanitizer trap (-3)
2025.07.07 08:31:26.707814 [ 2411773 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2025.07.07 08:31:26.707816 [ 2411773 ] {} <Fatal> BaseDaemon: Stack trace: 0x000063596e7c0c43 0x0000635975ff166b 0x00006359604fcd30 0x00006359605075c7 0x000063597720f88b 0x0000635977076f27 0x000063596ebc9f9b 0x0000635984f4b77b 0x000063596ebaea5b 0x000063596ebaab2c 0x000063596050e1e1 0x00007b3b9542a338 0x00007b3b9542a3fb 0x00006359604f302e
2025.07.07 08:31:26.718509 [ 2411773 ] {} <Fatal> BaseDaemon: 0.0. inlined from ci/tmp/build/./src/Common/StackTrace.cpp:389: StackTrace::tryCapture()
2025.07.07 08:31:26.718524 [ 2411773 ] {} <Fatal> BaseDaemon: 0. ci/tmp/build/./src/Common/StackTrace.cpp:61: StackTrace::StackTrace() @ 0x0000000027c86c43
2025.07.07 08:31:26.734878 [ 2411773 ] {} <Fatal> BaseDaemon: 1. ci/tmp/build/./src/Common/SignalHandlers.cpp:212: sanitizerDeathCallback() @ 0x000000002f4b766b
2025.07.07 08:31:26.787982 [ 2411773 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x00000000199c2d30
2025.07.07 08:31:26.817412 [ 2411773 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00000000199cd5c7
2025.07.07 08:31:26.843192 [ 2411773 ] {} <Fatal> BaseDaemon: 4. ci/tmp/build/./src/Access/RoleCache.cpp:60: ? @ 0x00000000306d588b
2025.07.07 08:31:26.872721 [ 2411773 ] {} <Fatal> BaseDaemon: 5.0. inlined from contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::RoleCache>::__unique_single std::make_unique[abi:ne190107]<DB::RoleCache, DB::AccessControl&, int>(DB::AccessControl&, int&&)
2025.07.07 08:31:26.872737 [ 2411773 ] {} <Fatal> BaseDaemon: 5. ci/tmp/build/./src/Access/AccessControl.cpp:315: DB::AccessControl::setupFromMainConfig(Poco::Util::AbstractConfiguration const&, String const&, std::function<std::shared_ptr<zkutil::ZooKeeper> ()> const&) @ 0x000000003053cf27
2025.07.07 08:31:26.913640 [ 2411773 ] {} <Fatal> BaseDaemon: 6. ci/tmp/build/./programs/server/Server.cpp:2331: DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000002808ff9b
2025.07.07 08:31:26.921628 [ 2411773 ] {} <Fatal> BaseDaemon: 7. ci/tmp/build/./base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x000000003e41177b
2025.07.07 08:31:26.980127 [ 2411773 ] {} <Fatal> BaseDaemon: 8. ci/tmp/build/./programs/server/Server.cpp:607: DB::Server::run() @ 0x0000000028074a5b
2025.07.07 08:31:27.036667 [ 2411773 ] {} <Fatal> BaseDaemon: 9. ci/tmp/build/./programs/server/Server.cpp:394: mainEntryClickHouseServer(int, char**) @ 0x0000000028070b2c
2025.07.07 08:31:27.041390 [ 2411773 ] {} <Fatal> BaseDaemon: 10. ci/tmp/build/./programs/main.cpp:340: main @ 0x00000000199d41e1
2025.07.07 08:31:27.041421 [ 2411773 ] {} <Fatal> BaseDaemon: 11. __libc_start_call_main @ 0x000000000002a338
2025.07.07 08:31:27.041440 [ 2411773 ] {} <Fatal> BaseDaemon: 12. __libc_start_main_alias_2 @ 0x000000000002a3fb
2025.07.07 08:31:27.070878 [ 2411773 ] {} <Fatal> BaseDaemon: 13. _start @ 0x00000000199b902e
2025.07.07 08:31:27.368010 [ 2411773 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 47C1C6FDB5FE04A9BE07AA10A85601D1)
```

### PR DESCRIPTION
**Pull request by wushap**
Resolves: #83374

### Changelog category (leave one):
- Bug Fix (fix integer overflow in configuration settings)

### Changelog entry (a [user-readable short description](../docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Resolve minor integer overflow in configuration of setting `role_cache_expiration_time_seconds` (issue #83374).

### CODE REVIEW

File: src/Access/RoleCache.cpp [hunk 1]
```diff
@@ -57,7 +57,7 @@ namespace
 
 
 RoleCache::RoleCache(const AccessControl & access_control_, int expiration_time_seconds)
-    : access_control(access_control_), cache(expiration_time_seconds * 1000 /* 10 minutes by default*/)
+    : access_control(access_control_), cache(std::min(INT_MAX / 1000, expiration_time_seconds) * 1000 /* 10 minutes by default*/)
```
Comment (nickitat) [inline src/Access/RoleCache.cpp]: cache accepts int64, all we need to do is to make sure that `expiration_time_seconds * 1000` is int64 instead of int. e.g. replace it with ``expiration_time_seconds * 1000ll`

Comment (wushap) [reply src/Access/RoleCache.cpp]: done

**Review by nickitat — APPROVED** [review]

**Comment by wushap** [comment]
@nickitat It seems a label is required for this pr to run CI.

**Comment by wushap** [comment]
The CI failure is not related to this change.
