### PR TITLE
Fix boundaries of candidate ranges in findPKRangesForFinalAfterSkipIndexImpl

### LINKED ISSUE #82598: Test 03244_skip_index_in_final_query_with_pk_rescan failure
Test failed in this job -

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82493&sha=2a8ad3edd085d8cd43735934975aa12d72b132df&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%29

```
2025-06-24 21:52:17 Reason: result differs with reference:  
2025-06-24 21:52:17 --- /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03244_skip_index_in_final_query_with_pk_rescan.reference	2025-06-24 21:33:21.105266066 +0200
2025-06-24 21:52:17 +++ /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03244_skip_index_in_final_query_with_pk_rescan.stdout	2025-06-24 21:52:17.405616027 +0200
2025-06-24 21:52:17 @@ -1,12 +1,12 @@
2025-06-24 21:52:17  Next 4 queries should return 0 rows and the 5th query should return 1 row
2025-06-24 21:52:17  0
2025-06-24 21:52:17  0
2025-06-24 21:52:17  0
2025-06-24 21:52:17  0
2025-06-24 21:52:17  1
2025-06-24 21:52:17  Next 4 queries should return 0 rows and the 5th query should return 1 row
2025-06-24 21:52:17 -0
2025-06-24 21:52:17 -0
2025-06-24 21:52:17 -0
2025-06-24 21:52:17 -0
2025-06-24 21:52:17 +1
2025-06-24 21:52:17 +1
2025-06-24 21:52:17 +1
2025-06-24 21:52:17 +1
2025-06-24 21:52:17  1
2025-06-24 21:52:17 
2025-06-24 21:52:17 
2025-06-24 21:52:17 Settings used in the test: --max_insert_threads 2 --group_by_two_level_threshold 832940 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 7050894 --max_read_buffer_size 991481 --prefer_localhost_replica 1 --max_block_size 28781 --max_joined_block_size_rows 93131 --max_threads 3 --optimize_append_index 1 --use_hedged_requests 1 --optimize_if_chain_to_multiif 0 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 0 --optimize_or_like_chain 0 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 62 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 19830029 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 5808910781 --min_bytes_to_use_mmap_io 5261159912 --local_filesystem_read_method pread --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 5 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 16Mi --filesystem_prefetch_step_marks 0 --filesystem_prefetch_step_bytes 0 --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 0 --merge_tree_coarse_index_granularity 32 --optimize_distinct_in_order 0 --max_bytes_before_remerge_sort 2427214123 --min_compress_block_size 2810801 --max_compress_block_size 3032665 --merge_tree_compact_parts_min_granules_to_multibuffer_read 88 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 9749550 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 3 --session_timezone Africa/Khartoum --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.45 --prefer_external_sort_block_bytes 1 --cross_join_min_rows_to_compress 1 --cross_join_min_bytes_to_compress 100000000 --min_external_table_block_size_bytes 0 --max_parsing_threads 1 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 1 --query_plan_join_swap_table true --enable_vertical_final 1 --optimize_extract_common_expressions 1 --use_query_condition_cache 1 --secondary_indices_enable_bulk_filtering 0 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.19 --max_bytes_ratio_before_external_group_by 0.0 --use_skip_indexes_if_final_exact_mode 1
2025-06-24 21:52:17 
2025-06-24 21:52:17 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 7588676657 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 7488288438 --index_granularity_bytes 1875250 --merge_max_block_size 6132 --index_granularity 915 --min_bytes_for_wide_part 0 --marks_compress_block_size 9225 --primary_key_compress_block_size 82675 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 43049064 --compact_parts_max_bytes_to_buffer 404140885 --compact_parts_max_granules_to_buffer 129 --compact_parts_merge_max_bytes_to_prefetch_part 26885053 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 1 --enable_block_number_column 0 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1
2025-06-24 21:52:17 
2025-06-24 21:52:17 Database: test_vgrie1hp
```

### PR DESCRIPTION
**Pull request by shankar-iyer**
Resolves https://github.com/ClickHouse/ClickHouse/issues/82598 and https://github.com/ClickHouse/ClickHouse/issues/82792 and #83215 . Correctly identify the starting range for intersection check by using `findRightmostMarkLessThanValueInRange`() to reach one range before the lower bound. Check and exclude the final mark / range of a part from read list. 

This PR is a re-revert (https://github.com/ClickHouse/ClickHouse/pull/82667 -> https://github.com/ClickHouse/ClickHouse/pull/82853) including an additional fix for issue https://github.com/ClickHouse/ClickHouse/issues/82792.

Test added for testing corner-cases and no issues seen in 10000 local runs (of `03244_skip_index_in_final_query*` and `02201_use_skip_indexes_if_final`  )

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Setting `use_skip_indexes_if_final_exact_mode` optimization (introduced in 25.6) could fail to select a relevant candidate range depending upon `MergeTree` engine settings / data distribution. That has been resolved now.

### CODE REVIEW

**Comment by shankar-iyer** [comment]
Marking it draft, hopefully clean CI run.

**Comment by shankar-iyer** [comment]
Only failure in **Stress test (amd_tsan)** is https://github.com/ClickHouse/ClickHouse/issues/82614
```
[ 26418 ] {6aa807ce-d70b-4830-9f62-5b72c7e18333} <Fatal> : Logical error: \'!pool\'.
 [ 26418 ] {6aa807ce-d70b-4830-9f62-5b72c7e18333} <Fatal> : Stack trace (when copying this message, always include the lines below):
 [ 175499 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 175499 ] {} <Fatal> BaseDaemon: (version 25.7.1.1, build id: 05722A367464D44DC5175CFAA7B2163C689DD5F7, git hash: 1f126899d9d9609e5c4ac3019af8feac2d29fbab, architecture: x86_64) (from thread 26418) Received signal 6
 [ 175499 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 175499 ] {} <Fatal> BaseDaemon: 
 [ 175499 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f9d9cf219fd 0x00007f9d9cecd476 0x00007f9d9ceb37f3 0x000055cdeafab267 0x000055cdf4aae99c 0x000055cdf4aaedf7 0x000055cdf6f9b9b1 0x000055ce0085d115 0x000055ce0a2418a1 0x000055ce00851917 0x000055ce0085996b 0x000055ce0061b515 0x000055ce005e5858 0x000055ce005e53eb 0x000055ce0060c5f2 0x000055ce005fb519 0x000055ce005fa895 0x000055ce00613887 0x000055cdfaba2417 0x000055ce005e5858 0x000055ce005e53eb 0x000055ce0060c5f2 0x000055ce005fb519 0x000055ce005fc714 0x000055cdf4c5c87b 0x000055cdf4c64ec1 0x000055cdf4c64de2 0x000055cdf4c58e23 0x000055cdf4c61b7c 0x000055cdeafa4428 0x00007f9d9cf1fac3 0x00007f9d9cfb1850
 [ 175499 ] {} <Fatal> BaseDaemon: ########################################
 [ 175499 ] {} <Fatal> BaseDaemon: (version 25.7.1.1, build id: 05722A367464D44DC5175CFAA7B2163C689DD5F7, git hash: 1f126899d9d9609e5c4ac3019af8feac2d29fbab) (from thread 26418) (query_id: 6aa807ce-d70b-4830-9f62-5b72c7e18333) (query: SELECT * FROM icebergS3(s3_conn, filename=\'merged_several_tables_test\', SETTINGS iceberg_recent_metadata_file_by_last_updated_ms_field = true) ORDER BY id;) Received signal Aborted (6)
 [ 175499 ] {} <Fatal> BaseDaemon: 
 [ 175499 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f9d9cf219fd 0x00007f9d9cecd476 0x00007f9d9ceb37f3 0x000055cdeafab267 0x000055cdf4aae99c 0x000055cdf4aaedf7 0x000055cdf6f9b9b1 0x000055ce0085d115 0x000055ce0a2418a1 0x000055ce00851917 0x000055ce0085996b 0x000055ce0061b515 0x000055ce005e5858 0x000055ce005e53eb 0x000055ce0060c5f2 0x000055ce005fb519 0x000055ce005fa895 0x000055ce00613887 0x000055cdfaba2417 0x000055ce005e5858 0x000055ce005e53eb 0x000055ce0060c5f2 0x000055ce005fb519 0x000055ce005fc714 0x000055cdf4c5c87b 0x000055cdf4c64ec1 0x000055cdf4c64de2 0x000055cdf4c58e23 0x000055cdf4c61b7c 0x000055cdeafa4428 0x00007f9d9cf1fac3 0x00007f9d9cfb1850
 [ 175499 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00000000000969fd
 [ 175499 ] {} <Fatal> BaseDaemon: 6. ? @ 0x0000000000042476
 [ 175499 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00000000000287f3
 [ 175499 ] {} <Fatal> BaseDaemon: 8. __interceptor_abort @ 0x0000000008bf5267
 [ 175499 ] {} <Fatal> BaseDaemon: 9. ./ci/tmp/build/./src/Common/Exception.cpp:50: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x00000000126f899c
 [ 175499 ] {} <Fatal> BaseDaemon: 10. ./ci/tmp/build/./src/Common/Exception.cpp:56: DB::abortOnFailedAssertion(String const&) @ 0x00000000126f8df7
 [ 175499 ] {} <Fatal> BaseDaemon: 11. ./ci/tmp/build/./src/Common/threadPoolCallbackRunner.cpp:17: DB::ThreadPoolCallbackRunnerFast::initThreadPool(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, unsigned long, String, std::shared_ptr<DB::ThreadGroup>) @ 0x0000000014be59b1
 [ 175499 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./ci/tmp/build/./src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp:615: operator()
 [ 175499 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0>()()) std::__invoke[abi:ne190107]<DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0>(DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0&&)
 [ 175499 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./contrib/llvm-project/libcxx/include/__mutex/once_flag.h:97: void std::__call_once_param<std::tuple<DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0&&>>::__execute[abi:ne190107]<>(std::__tuple_indices<...>)
 [ 175499 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./contrib/llvm-project/libcxx/include/__mutex/once_flag.h:91: std::__call_once_param<std::tuple<DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0&&>>::operator()[abi:ne190107]()
 [ 175499 ] {} <Fatal> BaseDaemon: 12. ./contrib/llvm-project/libcxx/include/__mutex/once_flag.h:118: void std::__call_once_proxy[abi:ne190107]<std::tuple<DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0&&>>(void*) @ 0x000000001e4a7115
 [ 175499 ] {} <Fatal> BaseDaemon: 13. ./ci/tmp/build/./contrib/llvm-project/libcxx/src/call_once.cpp:57: std::__call_once(unsigned long volatile&, void*, void (*)(void*)) @ 0x0000000027e8b8a1
 [ 175499 ] {} <Fatal> BaseDaemon: 14.0. inlined from ./contrib/llvm-project/libcxx/include/__mutex/once_flag.h:131: void std::call_once[abi:ne190107]<DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0>(std::once_flag&, DB::ParquetBlockInputFormat::initializeIfNeeded()::$_0&&)
 [ 175499 ] {} <Fatal> BaseDaemon: 14. ./ci/tmp/build/./src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp:610: DB::ParquetBlockInputFormat::initializeIfNeeded() @ 0x000000001e49b917
 [ 175499 ] {} <Fatal> BaseDaemon: 15. ./ci/tmp/build/./src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp:1093: DB::ParquetBlockInputFormat::read() @ 0x000000001e4a396b
 [ 175499 ] {} <Fatal> BaseDaemon: 16. ./ci/tmp/build/./src/Processors/Formats/IInputFormat.cpp:18: DB::IInputFormat::generate() @ 0x000000001e265515
```

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 1]
```diff
@@ -985,16 +985,18 @@ RangesInDataParts findPKRangesForFinalAfterSkipIndexImpl(RangesInDataParts & ran
...
-            continue; /// no intersection possible in this part
-        if (candidates_start.value() > 0)
-            candidates_start = candidates_start.value() - 1;
+            candidates_start = 0;
 
         auto candidates_end = index_access.findLeftmostMarkGreaterThanValueInRange(part_index, selected_upper_bound.value, MarkRange{0, index_granularity->getMarksCountWithoutFinal() + 1}, false);
         if (!candidates_end)
             candidates_end = index_granularity->getMarksCountWithoutFinal();
+        if (candidates_end != 0) /// Come back by 1 because we are now 1 past the upper bound or at the final mark
+            candidates_end = candidates_end.value() - 1;
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp:999]: I'm not sure about this. But if `!candidates_end` was true, is it really correct to skip the last mark here (the end was already pointing to the actual last mark, not the final mark)?

Comment (shankar-iyer) [reply src/Processors/QueryPlan/PartsSplitter.cpp:999]: Good point! The for loop uses condition `range_begin <= candidates_end.value()`, thus the mark at `candidates_end` after decrement will also be included for read. The actual last mark will not be skipped by this logic 

e.g if `getMarkCountsWithoutFinal`() returns 5 and `candidates_start` is 0, then we have to read mark numbers 0,1,2,3,4 of the part.

**Review by nickitat — APPROVED** [review]

**Comment by shankar-iyer** [comment]
Just testing a bit more before merging, no issues found.
