### PR TITLE
Fix inconsistent formatting of table functions that have the same name as operators

### LINKED ISSUE #81977: Inconsistent AST formatting: `AND(...)` vs `AND (...)`
`SELECT x(SELECT * AND (16) AND 1)`

```
2025.06.17 00:15:43.151240 [ 4056258 ] {760dafbc-765c-44e5-86c0-62c7c0a9bbde} <Fatal> : Logical error: 'Inconsistent AST formatting: the query:
SELECT x((SELECT * AND(16)) AND 1)
Was parsed and formatted back as:
SELECT x((SELECT * AND 16) AND 1)'.
```

### LINKED ISSUE #82834: Inconsistent formatting of arrays
> My final case for now:
> 
> 
> 
> ```sql
> 
> SELECT -[(1)];
> 
> ```
> 
> ```
> 
> Logical error: 'Inconsistent AST formatting: the query:
> 
> SELECT -[1]
> 
> Was parsed and formatted back as:
> 
> SELECT -([1])'.
> 
> ```
> 
> After these examples get fixed, I can test the remaining from my stash. 

 _Originally posted by @PedroTadim in [#68296](https://github.com/ClickHouse/ClickHouse/issues/68296#issuecomment-2288666355)_

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In previous versions, queries with table functions named the same way as the implementation functions for operators were formatted inconsistently. Closes #81601. Closes #81977. Closes #82834. Closes #82835. EXPLAIN SYNTAX queries will not format operators - the new behavior better reflects the purpose of explaining syntax. `clickhouse-format`, `formatQuery`, and similar will not format functions as operators if the query contained them in a functional form.

### CODE REVIEW

File: tests/queries/0_stateless/03552_inconsistent_formatting_operator_as_table_function.sql [hunk 1]
```diff
@@ -0,0 +1,15 @@
+SELECT * FROM globalIn('a', 1); -- { serverError UNKNOWN_FUNCTION }
+SELECT * FROM plus(1, 2); -- { serverError UNKNOWN_FUNCTION }
+SELECT * FROM negate(x); -- { serverError UNKNOWN_FUNCTION }
+
+SELECT not((SELECT * AND(16)) AND 1);
+
+SELECT (1,1) c0, (1,(1)) c0; -- { serverError MULTIPLE_EXPRESSIONS_FOR_ALIAS }
+SELECT -[(1)]; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
```
Comment (PedroTadim) [inline tests/queries/0_stateless/03552_inconsistent_formatting_operator_as_table_function.sql:7]: Isn't this statement valid?

Comment (alexey-milovidov) [reply tests/queries/0_stateless/03552_inconsistent_formatting_operator_as_table_function.sql:7]: Yes, we can't negate arrays.

**Comment by alexey-milovidov** [comment]
It's totally ok if EXPLAIN SYNTAX does not format operators. Actually it is even closer to the meaning of the word "syntax".

File: tests/queries/0_stateless/03552_inconsistent_formatting_operator_as_table_function.sql (hunk 1 above)
Comment (PedroTadim) [reply tests/queries/0_stateless/03552_inconsistent_formatting_operator_as_table_function.sql:7]: I was confused. The arrayMap function has to be used to negate an array.

**Comment by KochetovNicolai** [comment]
I still want to make it more consistent in a way that if AST was parsed as operator, we can keep an operator in formatted query.
Also, this way, fewer tests are failing (and formatting looks nicer, I think).

**Comment by KochetovNicolai** [comment]
> [Remove MaterializedMySQL](https://github.com/ClickHouse/ClickHouse/pull/82825/commits/1698d1f578e3a111e125c5f0583d122edc9b93b0)

> [Remove KQL](https://github.com/ClickHouse/ClickHouse/pull/82825/commits/525de91fe7300d6bd866d6425373fb6d362e05e5)

That's quite radical.

**Comment by yakov-olkhovskiy** [comment]
let's remove KQL tests for now - I'll add `explain` to it and rewrite with query tree so it would not depend on formatting

**Comment by alexey-milovidov** [comment]
LGTM
