### PR TITLE
Quick fix for aggregation pipeline

### LINKED ISSUE #35096: Aggregation over aggregation is single threaded
Test (timing from r5d.12xlarge)

```sql
DROP TABLE IF EXISTS test.threading2;

CREATE TABLE test.threading2(
    ac UInt64,
    start_date Date,
    wg Float32,
    n UInt16,
    s UInt32
)
Engine = MergeTree
ORDER BY (start_date, ac, n, s)


INSERT INTO test.threading2
SELECT
    rand(1) % 20000000 as ac,
    addDays(toDate('2022-01-01'),rand(2) % 8) as start_date,
    toFloat32(1) as wg,
    rand(3) % 400 as n,
    rand(4) % 20000 as s
FROM numbers_mt(50000000);
```

### option 1 - problematic

```sql
SELECT s, n, sum(wgr) AS REACH
FROM
(
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09')
    GROUP BY ac, s, n
)
GROUP BY s,n
ORDER BY REACH DESC
LIMIT 10;

--- 10 rows in set. Elapsed: 4.421 sec. Processed 50.00 million rows, 1.00 GB (11.31 million rows/s., 226.22 MB/s.)
```

### option 2: optimized via UNION ALL inside

```sql
SELECT s, n, sum(wgr) AS REACH
FROM
(
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 0)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 1)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 2)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 3)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 4)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 5)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 6)
    GROUP BY ac, s, n
    UNION ALL
    SELECT AVG(wg) AS wgr, ac, s, n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09') AND ((ac % 8) = 7)
    GROUP BY ac, s, n
)
GROUP BY s,n
ORDER BY REACH DESC
LIMIT 10;

-- 10 rows in set. Elapsed: 2.057 sec. Processed 400.00 million rows, 8.00 GB (194.50 million rows/s., 3.89 GB/s.)
```

### option 3: optimized by converting subquery to a temporary table

```sql
CREATE TEMPORARY TABLE threading2_temp AS
SELECT AVG(wg) AS wgr, ac, s, n
FROM test.threading2
WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09')
GROUP BY ac, s, n;
-- 0 rows in set. Elapsed: 1.198 sec. Processed 50.00 million rows, 1.00 GB (41.74 million rows/s., 834.81 MB/s.)

SELECT s, n, sum(wgr) AS REACH
FROM threading2_temp
GROUP BY s, n
ORDER BY REACH DESC
LIMIT 10;
-- 10 rows in set. Elapsed: 0.702 sec. Processed 50.00 million rows, 700.00 MB (71.22 million rows/s., 997.07 MB/s.)
```

You can see here that option 1 (which is the most natural) is about 2 times slower than 2 others (manual optimizations).

The reason is visible in the explain pipeline:

```sql
EXPLAIN PIPELINE header = 1
SELECT
    s,
    n,
    sum(wgr) AS REACH
FROM
(
    SELECT
        AVG(wg) AS wgr,
        ac,
        s,
        n
    FROM test.threading2
    WHERE (start_date >= '2022-01-01') AND (start_date < '2022-01-09')
    GROUP BY
        ac,
        s,
        n
)
GROUP BY
    s,
    n
ORDER BY REACH DESC
LIMIT 10
```

```
┌─explain─────────────────────────────────────────────────────────────────────────────────┐
│ (Expression)                                                                            │
│ ExpressionTransform                                                                     │
│ Header: s UInt32: s UInt32 UInt32(size = 0)                                             │
│         n UInt16: n UInt16 UInt16(size = 0)                                             │
│         REACH Float64: REACH Float64 Float64(size = 0)                                  │
│   (Limit)                                                                               │
│   Limit                                                                                 │
│   Header: s UInt32: s UInt32 UInt32(size = 0)                                           │
│           n UInt16: n UInt16 UInt16(size = 0)                                           │
│           sum(wgr) Float64: sum(wgr) Float64 Float64(size = 0)                          │
│     (MergingSorted)                                                                     │
│       (MergeSorting)                                                                    │
│       MergeSortingTransform                                                             │
│       Header: s UInt32: s UInt32 UInt32(size = 0)                                       │
│               n UInt16: n UInt16 UInt16(size = 0)                                       │
│               sum(wgr) Float64: sum(wgr) Float64 Float64(size = 0)                      │
│         (PartialSorting)                                                                │
│         LimitsCheckingTransform                                                         │
│         Header: s UInt32: s UInt32 UInt32(size = 0)                                     │
│                 n UInt16: n UInt16 UInt16(size = 0)                                     │
│                 sum(wgr) Float64: sum(wgr) Float64 Float64(size = 0)                    │
│           PartialSortingTransform                                                       │
│           Header: s UInt32: s UInt32 UInt32(size = 0)                                   │
│                   n UInt16: n UInt16 UInt16(size = 0)                                   │
│                   sum(wgr) Float64: sum(wgr) Float64 Float64(size = 0)                  │
│             (Expression)                                                                │
│             ExpressionTransform                                                         │
│             Header: s UInt32: s UInt32 UInt32(size = 0)                                 │
│                     n UInt16: n UInt16 UInt16(size = 0)                                 │
│                     sum(wgr) Float64: sum(wgr) Float64 Float64(size = 0)                │
│               (Aggregating)                                                             │
│               AggregatingTransform                                                      │
│               Header: s UInt32: s UInt32 UInt32(size = 0)                               │
│                       n UInt16: n UInt16 UInt16(size = 0)                               │
│                       sum(wgr) Float64: sum(wgr) Float64 Float64(size = 0)              │
│                 (Expression)                                                            │
│                 ExpressionTransform                                                     │
│                 Header: wgr Float64: wgr Float64 Float64(size = 0)                      │
│                         s UInt32: s UInt32 UInt32(size = 0)                             │
│                         n UInt16: n UInt16 UInt16(size = 0)                             │
│                   (Aggregating)                                                         │
│                   Resize 24 → 1                                                         │   <-- it is finalization of the inner group by, all steps above run in a single thread mode
│                   Header: ac UInt64: ac UInt64 UInt64(size = 0)                         │
│                           s UInt32: s UInt32 UInt32(size = 0)                           │
│                           n UInt16: n UInt16 UInt16(size = 0)                           │
│                           avg(wg) Float64: avg(wg) Float64 Float64(size = 0)            │
│                     AggregatingTransform × 24                                           │
│                     Header: ac UInt64: ac UInt64 UInt64(size = 0)                       │
│                             s UInt32: s UInt32 UInt32(size = 0)                         │
│                             n UInt16: n UInt16 UInt16(size = 0)                         │
│                             avg(wg) Float64: avg(wg) Float64 Float64(size = 0)          │
│                       StrictResize 24 → 24                                              │
│                       Header × 24 : ac UInt64: ac UInt64 UInt64(size = 0)               │
│                                      wg Float32: wg Float32 Float32(size = 0)           │
│                                      n UInt16: n UInt16 UInt16(size = 0)                │
│                                      s UInt32: s UInt32 UInt32(size = 0)                │
│                         (Expression)                                                    │
│                         ExpressionTransform × 24                                        │
│                         Header: ac UInt64: ac UInt64 UInt64(size = 0)                   │
│                                 wg Float32: wg Float32 Float32(size = 0)                │
│                                 n UInt16: n UInt16 UInt16(size = 0)                     │
│                                 s UInt32: s UInt32 UInt32(size = 0)                     │
│                           (Filter)                                                      │
│                           FilterTransform × 24                                          │
│                           Header: ac UInt64: ac UInt64 UInt64(size = 0)                 │
│                                   wg Float32: wg Float32 Float32(size = 0)              │
│                                   n UInt16: n UInt16 UInt16(size = 0)                   │
│                                   s UInt32: s UInt32 UInt32(size = 0)                   │
│                             (SettingQuotaAndLimits)                                     │
│                               (ReadFromMergeTree)                                       │
│                               MergeTreeThread × 24 0 → 1                                │
│                               Header: ac UInt64: ac UInt64 UInt64(size = 0)             │
│                                       start_date Date: start_date Date UInt16(size = 0) │
│                                       wg Float32: wg Float32 Float32(size = 0)          │
│                                       n UInt16: n UInt16 UInt16(size = 0)               │
│                                       s UInt32: s UInt32 UInt32(size = 0)               │
└─────────────────────────────────────────────────────────────────────────────────────────┘
```

The inner query at its final stages does `Resize 24 → 1` and the outer query works in a single thread mode. 

Option 2 allows to parrallelize is by having several subqueries, each producing a single stream which can be processed by a separate thread later.

With temporary table - it get read in parallel by many threads.

### LINKED ISSUE #37034: how to improve merging performance
max merging buckets：
` Merging partially aggregated blocks (bucket = 253)` 
lowest thread：
`Merged partially aggregated blocks. 263623 rows, 13.04 MiB. in 9.085304823 sec. (29016.418 rows/sec., 1.44 MiB/sec.)`

sql is nested query like select xxx from (select xxx from table where xxx group by a,b,c) group by a,b

inner sql defined a projection agg can be hit ; 
read rows can be reduced from 4.07 billion rows to 1.21 billion rows；

but cost  only reduced by 10s+
unused projection:
`235130 rows in set. Elapsed: 107.195 sec. Processed 4.07 billion rows, 180.64 GB (37.95 million rows/s., 1.69 GB/s.)`

use projection：
`235130 rows in set. Elapsed: 97.016 sec. Processed 1.21 billion rows, 103.66 GB (12.47 million rows/s., 1.07 GB/s.)`

how to improve merging performance；thanks；

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Increased parallelism of query plan steps executed after aggregation.

perf tests: [1](https://s3.amazonaws.com/clickhouse-test-reports/38295/c1376a10fbea6a7e71f52c0f2617e0a5d8399123/performance_comparison_[3/4]/report.html) [2](https://s3.amazonaws.com/clickhouse-test-reports/38295/c1376a10fbea6a7e71f52c0f2617e0a5d8399123/performance_comparison_[4/4]/report.html)

closes: #35096

### CODE REVIEW

File: src/Processors/QueryPlan/AggregatingStep.cpp [hunk 1]
```diff
@@ -353,7 +357,10 @@ void AggregatingStep::transformPipeline(QueryPipelineBuilder & pipeline, const B
             return std::make_shared<AggregatingTransform>(header, transform_params, many_data, counter++, merge_threads, temporary_data_merge_threads);
         });
 
-        pipeline.resize(1);
+        // Needed for GroupingAggregatedTransform in distributed case. Strictly speaking, we should also check that `distributed_aggregation_memory_efficient` will be used.
+        const bool should_has_one_output_stream
```
Comment (alexey-milovidov) [inline src/Processors/QueryPlan/AggregatingStep.cpp:361]: should has -> should have

File: tests/queries/0_stateless/02343_aggregation_pipeline.sql [hunk 2]
```diff
@@ -0,0 +1,9 @@
+-- { echoOn }
+
+explain pipeline select * from (select * from numbers_mt(1e8) group by number) group by number settings max_threads = 16;
+
+explain pipeline select * from (select * from numbers_mt(1e8) group by number) order by number settings max_threads = 16;
+
+explain pipeline select number from remote('127.0.0.{1,2,3}', system, numbers_mt) group by number settings max_threads = 16, prefer_localhost_replica = 1, distributed_aggregation_memory_efficient = 1;
+
+explain pipeline select number from remote('127.0.0.{1,2,3}', system, numbers_mt) group by number settings max_threads = 16, prefer_localhost_replica = 1, distributed_aggregation_memory_efficient = 0;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02343_aggregation_pipeline.sql:9]: Let's also add a performance test.

**Comment by alexey-milovidov** [comment]
If it's a performance improvement, please mark it as a performance improvement for changelog.

**Review by KochetovNicolai — APPROVED** [review]

File: src/Processors/QueryPlan/AggregatingStep.h [hunk 3]
```diff
@@ -65,6 +66,10 @@ class AggregatingStep : public ITransformingStep
     InputOrderInfoPtr group_by_info;
     SortDescription group_by_sort_description;
 
+    /// Used to determine, should we resize pipeline to 1 at the end.
```
Comment (devcrafter) [inline src/Processors/QueryPlan/AggregatingStep.h:69]:
```suggestion
    /// It determines if we should resize pipeline to 1 at the end.
```

File: src/Processors/QueryPlan/AggregatingStep.cpp [hunk 4]
```diff
@@ -351,7 +353,8 @@ void AggregatingStep::transformPipeline(QueryPipelineBuilder & pipeline, const B
             return std::make_shared<AggregatingTransform>(header, transform_params, many_data, counter++, merge_threads, temporary_data_merge_threads);
         });
 
-        pipeline.resize(1);
+        /// No need to do this in case of aggregating in order, since AIO don't use two-level hash tables and thus returns only buckets with bucket_number = -1.
```
Comment (devcrafter) [inline src/Processors/QueryPlan/AggregatingStep.cpp:356]: "No need to do _this_ ..." - what `this` refers to here?

**Review by devcrafter — COMMENTED** [review]
Just suggestions regarding comments

File: src/Processors/QueryPlan/AggregatingStep.cpp (hunk 4 above)
Comment (nickitat) [inline src/Processors/QueryPlan/AggregatingStep.cpp:356]:
```suggestion
        /// We add the explicit resize here, but not in case of aggregating in order, since AIO don't use two-level hash tables and thus returns only buckets with bucket_number = -1.
```

File: src/Processors/QueryPlan/AggregatingStep.h (hunk 3 above)
Comment (nickitat) [inline src/Processors/QueryPlan/AggregatingStep.h:69]:
```suggestion
    /// It determines if we should resize pipeline to 1 at the end.
```

**Comment by nickitat** [comment]
problems spotted by the fuzzer should be fixed in #38449

**Comment by nickitat** [comment]
> @nickitat, is there a chance it could make `02112_with_fill_interval` flaky? It's flaky since 2022-06-29 00:00:00 UTC: https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJTAyMTEyX3dpdGhfZmlsbF9pbnRlcnZhbCUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

FillingTransform gets the same single stream of data in new pipeline, so I don't see how it may affect him. but I see locally that the test indeed became way more flaky. I will try to find the reason.

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 5]
```diff
@@ -1619,7 +1620,8 @@ static void executeMergeAggregatedImpl(
         final,
         settings.distributed_aggregation_memory_efficient && is_remote_storage,
         settings.max_threads,
-        settings.aggregation_memory_efficient_merge_threads);
+        settings.aggregation_memory_efficient_merge_threads,
+        should_produce_results_in_order_of_bucket_number);
```
Comment (nudles) [inline src/Interpreters/InterpreterSelectQuery.cpp:1624]: Hi @nickitat , would MergingAggregatedStep always perform the final aggregation? If yes, then would should_produce_results_in_order_of_bucket_number always be false, because to_stage!= QueryProcessingStage::WithMergeableState? Could you kindly explain a bit? Thank you!

Comment (nickitat) [reply src/Interpreters/InterpreterSelectQuery.cpp:1624]: Hi @nudles! There are might be several `MergingAggregatedStep`-s in a single query, because you may execute distributed aggregation over distributed tables. refer to [this](https://github.com/nickitat/ClickHouse/blob/5ae86e406df132d75f110651c42faffd54e6f31a/tests/queries/0_stateless/02343_aggregation_pipeline.reference#L102-L127) pipeline e.g. the first one returns [single](https://github.com/nickitat/ClickHouse/blob/5ae86e406df132d75f110651c42faffd54e6f31a/tests/queries/0_stateless/02343_aggregation_pipeline.reference#L113) stream of data, while the final merging returns [multiple](https://github.com/nickitat/ClickHouse/blob/5ae86e406df132d75f110651c42faffd54e6f31a/tests/queries/0_stateless/02343_aggregation_pipeline.reference#L106) streams.

Comment (nudles) [reply src/Interpreters/InterpreterSelectQuery.cpp:1624]: Hi @nickitat, thank you for the detailed explanation! One more question: is my following understanding correct?
If the `final` parameter of [MergingAggregatedStep (or AggregatingStep)](https://github.com/nickitat/ClickHouse/blob/5ae86e406df132d75f110651c42faffd54e6f31a/src/Processors/QueryPlan/MergingAggregatedStep.h#L19) is true, then to_stage is not WithMergeableState and therefore `should_produce_results_in_order_of_bucket_number=false`.

Comment (nickitat) [reply src/Interpreters/InterpreterSelectQuery.cpp:1624]: yes, it is correct

Comment (nudles) [reply src/Interpreters/InterpreterSelectQuery.cpp:1624]: Hi @nickitat , then can I use `should_produce_results_in_order_of_bucket_number= !final && settings.distributed_aggregation_memory_efficient` inside `MergingAggregatedStep` and `AggregatingStep` to eliminate passing the parameter `should_produce_results_in_order_of_bucket_number` to the constructor?

Comment (nickitat) [reply src/Interpreters/InterpreterSelectQuery.cpp:1624]: likely, yes. it worth trying not only to make code cleaner but also because we have one [place](https://github.com/ClickHouse/ClickHouse/blob/193cd1b3b2abcc13857f8660aa6995cac00b47c7/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L395) where we potentially build pipeline sub-optimally. maybe we will be able to remove [this](https://github.com/ClickHouse/ClickHouse/blob/193cd1b3b2abcc13857f8660aa6995cac00b47c7/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L457) unconditional resize.
we would be grateful if you make a pr.
