### PR TITLE
fix: fix cannot config server level throttling from zookeeper

### LINKED ISSUE #73964: max_remote_read_network_bandwidth_for_server cannot work with loading config from ZooKeeper
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

> Put your company name or project description here

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
latest master branch

Reproduce step:
1. create s3 table and insert data: 
```sql
CREATE TABLE default.test_bandwidth
(
    `id` UInt64
)
ENGINE = MergeTree
ORDER BY id
SETTINGS storage_policy = 's3_main', index_granularity = 8192;

insert into test_bandwidth select number from system.numbers limit 10000;
```

2. add from keeper in config.xml:
```
<include from_zk="/clickhouse/user-define"/>
```

3. create node in keeper:
```
create "/clickhouse/user-define" "<max_remote_read_network_bandwidth_for_server>128</max_remote_read_network_bandwidth_for_server>" PERSISTENT
```

4. restart clickhouse server and run sql:
```
select * from test_bandwidth;
```

And I found the query was not limited by max_remote_read_network_bandwidth_for_server

If I added max_remote_read_network_bandwidth_for_server in config.xml and it worked

**Expected behavior**

Query should be limited by max_remote_read_network_bandwidth_for_server.

I found it is because max_remote_read_network_bandwidth_for_server is set in setApplicationType. But in server.cpp, ClickHouse calls setApplicationType before loading the config from Zookeeper. Maybe we can split configureServerWideThrottling from setApplicationType and call it after loading the config from Zookeeper?

### PR DESCRIPTION
**Pull request by JiaQiTang98**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow configuring server-level throttling when the configuration is overridden in Keeper. Closes #73964.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit a04d226fd2902b1e347163d96795756b53c55f6a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74066/a04d226fd2902b1e347163d96795756b53c55f6a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/5eaad6a95417f62e5dcf6c4b06abcdf2e40e399c/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Interpreters/Context.h [hunk 1]
```diff
@@ -1470,6 +1470,7 @@ class Context: public ContextData, public std::enable_shared_from_this<Context>
 
     /// Throttling
 public:
+    void configureServerWideThrottling();
```
Comment (alexey-milovidov) [inline src/Interpreters/Context.h:1684]:
```suggestion
    /// Does not hold the lock, should be called once at the startup.
    void configureServerWideThrottling();
```

**Review by alexey-milovidov — APPROVED** [review]
