### PR TITLE
Fix index analysis with tuples and `IN`

### LINKED ISSUE #39704: IN operator is not working with tuples
**Describe what's wrong**

When adding new values to IN operator with tuples, result set is reduced.

<br class="Apple-interchange-newline">

**Does it reproduce on recent release?**

Probably not working since v22.4.2.1-stable
Still not working on v22.7.1.2484-stable

<br class="Apple-interchange-newline">

**How to reproduce**

```
CREATE TABLE ISSUE_EXAMPLE
(
    `THIRDPARTY_ID` String,
    `THIRDPARTY_USER_ID` String,
    `PLATFORM` LowCardinality(String),
    `DATE` Date
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(DATE)
ORDER BY (PLATFORM, THIRDPARTY_USER_ID, THIRDPARTY_ID)
SETTINGS storage_policy = 'nvme', index_granularity = 2048
```

```
INSERT INTO ISSUE_EXAMPLE VALUES ('17843212264024828', 238040827, 'insta', '2014-07-30'), ('17862693304001575', 238040827, 'insta', '2016-07-09')
```

```
SELECT *
FROM ISSUE_EXAMPLE
WHERE (PLATFORM, THIRDPARTY_USER_ID) IN (('insta', '238040827'))
```
That query returns 2 rows

```
SELECT *
FROM ISSUE_EXAMPLE
WHERE (PLATFORM, THIRDPARTY_USER_ID) IN (('insta', '238040827'), ('insta', '22606518861'))
```
That query returns 0 rows instead of 2. Adding new value to IN should not reduce result set.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong index analysis with tuples and operator `IN`, which could lead to wrong query result.

Fixes #39704.

### CODE REVIEW

File: src/Interpreters/Set.cpp [hunk 1]
```diff
@@ -430,8 +430,9 @@ MergeTreeSetIndex::MergeTreeSetIndex(const Columns & set_elements, std::vector<K
     SortDescription sort_description;
     for (size_t i = 0; i < tuple_size; ++i)
     {
-        block_to_sort.insert({ordered_set[i], nullptr, ordered_set[i]->getName()});
-        sort_description.emplace_back(ordered_set[i]->getName(), 1, 1);
+        String column_name = "_" + toString(i);
```
Comment (alexey-milovidov) [inline src/Interpreters/Set.cpp:433]: LGTM, but I don't understand, what was the problem?

**Review by alexey-milovidov — APPROVED** [review]

File: src/Interpreters/Set.cpp (hunk 1 above)
Comment (CurtizJ) [reply src/Interpreters/Set.cpp:433]: `ordered_set[i]` is a `ColumnPtr` and `getName` is not unique obviously. In result we could get wrong sorting of block.

Comment (azat) [reply src/Interpreters/Set.cpp:433]: Maybe also add an assert to `sortBlock`? Seems that it should not have duplicated columns in `description` they should be filtered out before.

Comment (CurtizJ) [reply src/Interpreters/Set.cpp:433]: I'm not sure that it's a good assertion, because sort description with duplicated columns is a valid sort description and removing them is just an optimization. I'd prefer to add such assertion to `Block`, since duplicated columns break the invariant and make behaviour of `Block::getByName` undefined. But as I remember it's can't be done now, because we can have blocks with duplicated columns during analysis of query.

**Comment by CurtizJ** [comment]
Integration tests: `ERROR: for replica3  Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Stateless tests (thread) - hung in tests with tsan is known.
