### PR TITLE
Fix inserts to distributed tables in case of change of native protocol

### LINKED ISSUE #34091: unknown serialization kind on distributed table
**Describe the unexpected behaviour**
After upgraded to ClickHouse 22.1.3 revision 54455,when using distributed table to insert data,errors occured in log.

**How to reproduce**
Version:ClickHouse 22.1.3.7

**Expected behavior**
After upgraded to ClickHouse 22.1.3 revision 54455,when using distributed table to insert data,errors occured in log.
Cluster's ClickHouse version are the same,22.1.3.7.

**Error message and/or stacktrace**
2022.01.28 18:39:41.098174 [ 80700 ] {} <Error> XXX.YYYY.DirectoryMonitor: Code: 246. DB::Exception: Unknown serialization kind 99: While sending /clickhouse/store/4db/4db5491f-555c-4c9d-8db5-491f555cbc9d/shard7_replica1/1571210.bin. (CORRUPTED_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::SerializationInfo::deserializeFromKindsBinary(DB::ReadBuffer&) @ 0x1326c09c in /usr/bin/clickhouse
2. DB::NativeReader::read() @ 0x14826428 in /usr/bin/clickhouse
3. ? @ 0x14195913 in /usr/bin/clickhouse
4. DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1419391a in /usr/bin/clickhouse
5. DB::StorageDistributedDirectoryMonitor::run() @ 0x1418fa78 in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12f8470e in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0x12f870a7 in /usr/bin/clickhouse
8. ? @ 0x12f88170 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa86f4b7 in /usr/bin/clickhouse
10. ? @ 0xa872ebd in /usr/bin/clickhouse
11. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.1.3.7 (official build))

### PR DESCRIPTION
**Pull request by CurtizJ**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix inserts to distributed tables in case of change of native protocol. The last change was in the version version 22.1, so there may be some failures of inserts to distributed tables after upgrade to that version.

Fixes #34091.

### CODE REVIEW

File: src/QueryPipeline/RemoteInserter.cpp [hunk 1]
```diff
@@ -34,6 +34,8 @@ RemoteInserter::RemoteInserter(
             = CurrentThread::get().thread_trace_context;
     }
 
+    server_revision = connection.getServerRevision(timeouts);
```
Comment (novikd) [inline src/QueryPipeline/RemoteInserter.cpp:37]: Move to [member initializer list](https://github.com/ClickHouse/ClickHouse/pull/34132/files#diff-57e439597c788d196efd2024e3e1a99113e82b6b4ecf9f03fbf09b43a759d03dL27)

File: src/Storages/Distributed/DirectoryMonitor.cpp [hunk 2]
```diff
@@ -188,7 +188,7 @@ namespace
 
             if (header_buf.hasPendingData())
             {
-                NativeReader header_block_in(header_buf, DBMS_TCP_PROTOCOL_VERSION);
+                NativeReader header_block_in(header_buf, distributed_header.revision);
                 distributed_header.block_header = header_block_in.read();
                 if (!distributed_header.block_header)
                     throw Exception(ErrorCodes::CANNOT_READ_ALL_DATA, "Cannot read header from the {} batch", in.getFileName());
```
Comment (novikd) [inline src/Storages/Distributed/DirectoryMonitor.cpp:194]: Maybe add protocol version to the exception message?

**Review by novikd — APPROVED** [review]
