### PR TITLE
Fix: UB in Thread Profile Events 

### LINKED ISSUE #91454: UndefinedBehaviorSanitizer: undefined behavior (STID: 4443-51fd)
CI report: [BuzzHouse (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=a3d2c26aa5d6226b4830fa4652d8c5f505f376bb&name_0=MasterCI&name_1=BuzzHouse%20%28amd_ubsan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdVbmRlZmluZWRCZWhhdmlvclNhbml0aXplcjogdW5kZWZpbmVkIGJlaGF2aW9yIChTVElEOiA0NDQzLTUxZmQpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQnV6ekhvdXNlIChhbWRfdWJzYW4pJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
Error:
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadProfileEvents.cpp:564:13
---

Stack trace:
#0 0x55c3ac2fa3c4 in DB::PerfEventsCounters::finalizeProfileEvents(ProfileEvents::Counters&) ci/tmp/build/./src/Common/ThreadProfileEvents.cpp:564:13
#1 0x55c3b8825645 in DB::ThreadStatus::finalizePerformanceCounters() ci/tmp/build/./src/Interpreters/ThreadStatusExt.cpp:557:33
#2 0x55c3b8824fd0 in DB::ThreadStatus::detachFromGroup() ci/tmp/build/./src/Interpreters/ThreadStatusExt.cpp:398:5
#3 0x55c3b88234f1 in DB::CurrentThread::detachFromGroupIfNotDetached() ci/tmp/build/./src/Interpreters/ThreadStatusExt.cpp:742:21
#4 0x55c3b88234f1 in DB::ThreadGroupSwitcher::~ThreadGroupSwitcher() ci/tmp/build/./src/Interpreters/ThreadStatusExt.cpp:282:9
#5 0x55c3afcabe82 in void DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::__1::function<void ()>>::executeCallback<std::__1::function<void ()>>(std:...
#6 0x55c3afcabbb6 in DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::__1::function<void ()>>::operator()(std::__1::function<void ()>&&, Priority, st...
#7 0x55c3ac3c79df in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
#8 0x55c3ac3c79df in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
#9 0x55c3ac3c79df in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:801:17
#10 0x55c3ac3d05c7 in decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>:...
#11 0x55c3ac3d05c7 in decltype(auto) std::__1::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl...
#12 0x55c3ac3d05c7 in decltype(auto) std::__1::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGl...
#13 0x55c3ac3d05c7 in ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFrom...
#14 0x55c3ac3c4d94 in std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12
#15 0x55c3ac3c4d94 in std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10
#16 0x55c3ac3c4d94 in ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:811:17
#17 0x55c3ac3cc569 in decltype(*std::declval<ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)()>()()) std::__1:...
#18 0x55c3ac3cc569 in void std::__1::__thread_execute[abi:ne210105]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1:...
#19 0x55c3ac3cc569 in void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoo...
#20 0x7fa823b42ac2 in start_thread nptl/pthread_create.c:442:8
#21 0x7fa823bd48bf  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### PR DESCRIPTION
**Pull request by Fgrtue**
Fixes [#91200](https://github.com/ClickHouse/ClickHouse/issues/91200) and Fixes [#91454](https://github.com/ClickHouse/ClickHouse/issues/91454)

How it happens: Buzz House runs queries on `amd_ubsan` build and finds overflow error in `ThreadProfileEvents.cpp:564`, when we are computing `delta`.

Fix: the primary expression is `(current_value.value - previous_value.value) * enabled / std::max(1.f, float(running))`. First, we cast each expression's logical part into `Float64`. Then we do the multiplication (`Float64 * Float64 -> Float64`), which allows us to get rid of overflow. Then we use a special safe function to check is the result will be overflown after casting to `UInt64`.

How to reproduce: When I run BuzzHouse locally using the same build and the queries from [BuzzHouse amd_ubsan #89815](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89815&sha=692e3af840b8c8c571187cb851e938f8f1e3cbf4&name_0=PR&name_1=BuzzHouse+%28amd_ubsan%29) and [BuzzHouse amd_ubsan #91454](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=a3d2c26aa5d6226b4830fa4652d8c5f505f376bb&name_0=MasterCI&name_1=BuzzHouse%20%28amd_ubsan%29), I am unable to reproduce the error. The only way was to run the BuzzHouse test for `amd_ubsan` in the CI process.

cc @KochetovNicolai 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by PedroTadim** [comment]
That is not the solution. As you can see the CI failed on the same line again: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=b7f3d6e9373053fbead6dfe24a61b68cde13ece0&name_0=PR&name_1=BuzzHouse%20%28amd_ubsan%29 The issue is `(current_value.value - previous_value.value) * enabled / std::max(1.f, float(running))` produces a value larger than UInt64 max possible value. A solution would be to check if the resulting floating-point is larger than ULONG_MAX, set ULONG_MAX as the result.

File: src/Common/ThreadProfileEvents.cpp [hunk 1]
```diff
@@ -560,8 +562,24 @@ void PerfEventsCounters::finalizeProfileEvents(ProfileEvents::Counters & profile
         // deltas from old values.
         const auto enabled = current_value.time_enabled - previous_value.time_enabled;
         const auto running = current_value.time_running - previous_value.time_running;
-        const UInt64 delta = static_cast<UInt64>(
-            (current_value.value - previous_value.value) * enabled / std::max(1.f, float(running)));
+        const auto difference_current_previous = static_cast<Float64>(current_value.value) - static_cast<Float64>(previous_value.value);
+
+        if (difference_current_previous < 0)
+        {
+            LOG_WARNING(getLogger("PerfEvents"),
```
Comment (PedroTadim) [inline src/Common/ThreadProfileEvents.cpp]: This warning was not issued before. If the value decreases, is there an issue?

File: src/Common/ThreadProfileEvents.cpp [hunk 2]
```diff
@@ -560,8 +562,24 @@ void PerfEventsCounters::finalizeProfileEvents(ProfileEvents::Counters & profile
         // deltas from old values.
         const auto enabled = current_value.time_enabled - previous_value.time_enabled;
         const auto running = current_value.time_running - previous_value.time_running;
-        const UInt64 delta = static_cast<UInt64>(
-            (current_value.value - previous_value.value) * enabled / std::max(1.f, float(running)));
+        const auto difference_current_previous = static_cast<Float64>(current_value.value) - static_cast<Float64>(previous_value.value);
```
Comment (PedroTadim) [inline src/Common/ThreadProfileEvents.cpp]: The larger UInt64 values may not fit into Float64, maybe it should check this.

File: src/Common/ThreadProfileEvents.cpp (hunk 1 above)
Comment (Fgrtue) [reply src/Common/ThreadProfileEvents.cpp]: Normally this should not be the case, since performance counters must grow. In the end of the function we only increment the values, so if the previous became larger than the current, there is definitely something off. 

However, I deleted it in the next version, since this behavior is not justified.

File: src/Common/ThreadProfileEvents.cpp (hunk 2 above)
Comment (Fgrtue) [reply src/Common/ThreadProfileEvents.cpp]: I think in this case it is better to go with the primary implementation, and cast the value to `Float64` after subtraction.

File: src/Common/ThreadProfileEvents.cpp [hunk 3]
```diff
@@ -560,8 +562,15 @@ void PerfEventsCounters::finalizeProfileEvents(ProfileEvents::Counters & profile
...
-        const UInt64 delta = static_cast<UInt64>(
-            (current_value.value - previous_value.value) * enabled / std::max(1.f, float(running)));
+        const auto difference_current_previous = static_cast<Float64>(current_value.value - previous_value.value);
+        const auto multiplexing_scale_factor = static_cast<Float64>(enabled) / std::max(1., static_cast<Float64>(running));
+        const auto scaled_time = multiplexing_scale_factor * difference_current_previous;
+
+        UInt64 delta;
+        if (!accurate::convertNumeric<Float64, UInt64, false>(scaled_time, delta))
+        {
+            delta = 0;
```
Comment (PedroTadim) [inline src/Common/ThreadProfileEvents.cpp]: Last question. Why set the delta to 0 if it can't be converted? This indicates the value remained unchanged.

Comment (Fgrtue) [reply src/Common/ThreadProfileEvents.cpp]: This was done so that we don't pollute metrics. Otherwise the value `std::numeric_limits::max` will be propagated to all add this value to other counters (also unsigned integers), leading to modulo addition. This will mess up the metrics, so the user will see them going up, and then down -- this probably will be only more confusing and would be more difficult to comprehend.

**Review by PedroTadim — APPROVED** [review]

**Comment by PedroTadim** [comment]
Small comment. Split "Fixes #91200 and #91454" into "Fixes #91200" and "Fixes #91454" so GitHub can detect both issues and close them.

**Comment by Fgrtue** [comment]
[Stateless Test (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=2574d362c66bb209a34d69915721914ce2c89ab7&name_0=PR&name_1=Stateless+tests+%28arm_asan%2C+targeted%29&name_2=Tests)
Failed test `01782_field_oom` -- timeout error. The test seems unrelated to my pr, additionally, the first failure with the same error was before [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90374&sha=6be755884d4fae97a3aa1b353735182d955be9f2&name_0=PR&name_1=Stateless+tests+%28arm_asan%2C+targeted%29&name_1=Stateless+tests+%28arm_asan%2C+targeted%29&name_2=Tests)

[Stateless Test (amd_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=2574d362c66bb209a34d69915721914ce2c89ab7&name_0=PR&name_1=Stateless+tests+%28amd_asan%2C+distributed+plan%2C+parallel%2C+2%2F2%29&name_2=Tests)

Test `03702_alter_column_update_and_delete_with_secondary_index_rebuild` seems to be working after retry `retry_ok`. Also failed on master before. Therefore is flaky.

[Integration test (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=2574d362c66bb209a34d69915721914ce2c89ab7&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+1%2F6%29) 

Existing issue regarding this test: https://github.com/ClickHouse/ClickHouse/issues/88775

[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=2574d362c66bb209a34d69915721914ce2c89ab7&name_0=PR&name_1=BuzzHouse+%28amd_debug%29)

Error: `Logical error: Inconsistent AST formatting`.  Failed on master before [see here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91167&sha=b504c2ceef434ec8f80f43f989f3db897a01ea38&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29&name_1=BuzzHouse%20%28amd_debug%29).

**Review by PedroTadim — APPROVED** [review]

**Comment by Fgrtue** [comment]
[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=5b7b80ae033fcb82582eec36b7e2ddf656592537&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29) [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICd0ZXN0X2FjY2VwdF9pbnZhbGlkX2NlcnRpZmljYXRlL3Rlc3QucHk6OnRlc3Rfc3RyaWN0X3JlamVjdF93aXRoX2NvbmZpZycKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0ludGVncmF0aW9uIHRlc3RzIChhbWRfYXNhbiwgZGIgZGlzaywgb2xkIGFuYWx5emVyLCAzLzYpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

* https://github.com/ClickHouse/ClickHouse/issues/91667

[Integration tests (amd_asan, db disk, old analyzer, 3/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91568&sha=5b7b80ae033fcb82582eec36b7e2ddf656592537&name_0=PR&name_1=Integration%20tests%20%28amd_asan%2C%20db%20disk%2C%20old%20analyzer%2C%203%2F6%29) [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ0luY29uc2lzdGVudCBBU1QgZm9ybWF0dGluZzogdGhlIHF1ZXJ5OicKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0J1enpIb3VzZSAoYW1kX2RlYnVnKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

- https://github.com/ClickHouse/ClickHouse/issues/91974

Finally, throughout the check I found another flaky test, which did not fall in the final commit, however it failed before multiple times 

- https://github.com/ClickHouse/ClickHouse/issues/91997
