### PR TITLE
Make local object storage work consistently with s3 object storage, fix problem with append, make it configurable as independent storage

### LINKED ISSUE #48465: `LocalObjectStorage` corrupts data
https://s3.amazonaws.com/clickhouse-test-reports/47307/c59d7a4bb3831a470d6f8668f5a66080da62fee1/stress_test__debug_/fatal_messages.txt

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.565735 [ 21939 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.567419 [ 21939 ] {} <Fatal> BaseDaemon: (version 23.4.1.1, build id: F61B0136645528B00FC955570578C39F2A231470) (from thread 1745) (no query) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568164 [ 21939 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568411 [ 21939 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f348f6fe00b 0x7f348f6dd859 0x7f348f6dd729 0x7f348f6eefd6 0x2be534d1 0x2bf6bcce 0x2bf69a55 0x2bf692a8 0x2bf71e69 0x2c3eabbd 0x29e12f61 0x29e12a62 0x29e1a758 0x29e1a735 0x29e1a715 0x29e1a6f5 0x29e1a6bd 0x2226f6d6 0x2226ebd5 0x2937d2dd 0x2937f746 0x293807b8 0x29380795 0x29380779 0x293806dd 0x29380600 0x29380575 0x29380555 0x29380535 0x29380500 0x2226f6d6 0x2226ebd5 0x22362f09 0x2236a6c4 0x2236a675 0x2236a59d 0x2236a082 0x7f348f8b5609 0x7f348f7da133
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568651 [ 21939 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f348f6fe00b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568792 [ 21939 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f348f6dd859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568932 [ 21939 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f348f6dd729 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.569076 [ 21939 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f348f6eefd6 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:28.173055 [ 21939 ] {} <Fatal> BaseDaemon: 8. /build/src/Storages/MergeTree/IMergeTreeDataPart.cpp:0: DB::IMergeTreeDataPart::remove() @ 0x2be534d1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:30.316475 [ 21939 ] {} <Fatal> BaseDaemon: 9. /build/src/Storages/MergeTree/MergeTreeData.cpp:2292: DB::MergeTreeData::clearPartsFromFilesystemImpl(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*)::$_29::operator()() const @ 0x2bf6bcce in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:31.335538 [ 21939 ] {} <Fatal> BaseDaemon: 10. /build/src/Storages/MergeTree/MergeTreeData.cpp:2300: DB::MergeTreeData::clearPartsFromFilesystemImpl(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*) @ 0x2bf69a55 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:32.451100 [ 21939 ] {} <Fatal> BaseDaemon: 11. /build/src/Storages/MergeTree/MergeTreeData.cpp:2265: DB::MergeTreeData::clearPartsFromFilesystem(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, bool, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*) @ 0x2bf692a8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:33.521054 [ 21939 ] {} <Fatal> BaseDaemon: 12. /build/src/Storages/MergeTree/MergeTreeData.cpp:2662: DB::MergeTreeData::dropAllData() @ 0x2bf71e69 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:34.303915 [ 21939 ] {} <Fatal> BaseDaemon: 13. /build/src/Storages/StorageMergeTree.cpp:301: DB::StorageMergeTree::drop() @ 0x2c3eabbd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:34.894148 [ 21939 ] {} <Fatal> BaseDaemon: 14. /build/src/Interpreters/DatabaseCatalog.cpp:0: DB::DatabaseCatalog::dropTableFinally(DB::DatabaseCatalog::TableMarkedAsDropped const&) @ 0x29e12f61 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:35.241088 [ 21939 ] {} <Fatal> BaseDaemon: 15. /build/src/Interpreters/DatabaseCatalog.cpp:1076: DB::DatabaseCatalog::dropTableDataTask() @ 0x29e12a62 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:35.618683 [ 21939 ] {} <Fatal> BaseDaemon: 16. /build/src/Interpreters/DatabaseCatalog.cpp:176: DB::DatabaseCatalog::createBackgroundTasks()::$_4::operator()() const @ 0x29e1a758 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:36.054058 [ 21939 ] {} <Fatal> BaseDaemon: 17. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::DatabaseCatalog::createBackgroundTasks()::$_4&>()()) std::__invoke[abi:v15000]<DB::DatabaseCatalog::createBackgroundTasks()::$_4&>(DB::DatabaseCatalog::createBackgroundTasks()::$_4&) @ 0x29e1a735 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:36.435510 [ 21939 ] {} <Fatal> BaseDaemon: 18. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<DB::DatabaseCatalog::createBackgroundTasks()::$_4&>(DB::DatabaseCatalog::createBackgroundTasks()::$_4&) @ 0x29e1a715 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:36.825310 [ 21939 ] {} <Fatal> BaseDaemon: 19. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::DatabaseCatalog::createBackgroundTasks()::$_4, void ()>::operator()[abi:v15000]() @ 0x29e1a6f5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.211942 [ 21939 ] {} <Fatal> BaseDaemon: 20. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::DatabaseCatalog::createBackgroundTasks()::$_4, void ()>>(std::__function::__policy_storage const*) @ 0x29e1a6bd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.280672 [ 21939 ] {} <Fatal> BaseDaemon: 21. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x2226f6d6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.364422 [ 21939 ] {} <Fatal> BaseDaemon: 22. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x2226ebd5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.455603 [ 21939 ] {} <Fatal> BaseDaemon: 23. /build/src/Core/BackgroundSchedulePool.cpp:100: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2937d2dd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.571021 [ 21939 ] {} <Fatal> BaseDaemon: 24. /build/src/Core/BackgroundSchedulePool.cpp:282: DB::BackgroundSchedulePool::threadFunction() @ 0x2937f746 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.668202 [ 21939 ] {} <Fatal> BaseDaemon: 25. /build/src/Core/BackgroundSchedulePool.cpp:161: DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1::operator()() const @ 0x293807b8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.762945 [ 21939 ] {} <Fatal> BaseDaemon: 26. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&>()()) std::__invoke[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&) @ 0x29380795 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.878386 [ 21939 ] {} <Fatal> BaseDaemon: 27. /build/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&, std::__tuple_indices<>) @ 0x29380779 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.976371 [ 21939 ] {} <Fatal> BaseDaemon: 28. /build/contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&) @ 0x293806dd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.051012 [ 21939 ] {} <Fatal> BaseDaemon: 29. /build/src/Common/ThreadPool.h:227: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()::operator()() @ 0x29380600 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.146782 [ 21939 ] {} <Fatal> BaseDaemon: 30. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>()()) std::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&) @ 0x29380575 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.242223 [ 21939 ] {} <Fatal> BaseDaemon: 31. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()&) @ 0x29380555 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.335605 [ 21939 ] {} <Fatal> BaseDaemon: 32. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>::operator()[abi:v15000]() @ 0x29380535 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.430608 [ 21939 ] {} <Fatal> BaseDaemon: 33. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x29380500 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.501374 [ 21939 ] {} <Fatal> BaseDaemon: 34. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x2226f6d6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.562552 [ 21939 ] {} <Fatal> BaseDaemon: 35. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x2226ebd5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.663955 [ 21939 ] {} <Fatal> BaseDaemon: 36. /build/src/Common/ThreadPool.cpp:396: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x22362f09 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.764426 [ 21939 ] {} <Fatal> BaseDaemon: 37. /build/src/Common/ThreadPool.cpp:180: void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()::operator()() const @ 0x2236a6c4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.876006 [ 21939 ] {} <Fatal> BaseDaemon: 38. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<void>()()) std::__invoke[abi:v15000]<void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&) @ 0x2236a675 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.980545 [ 21939 ] {} <Fatal> BaseDaemon: 39. /build/contrib/llvm-project/libcxx/include/thread:285: void std::__thread_execute[abi:v15000]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(std::tuple<void, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>&, std::__tuple_indices<>) @ 0x2236a59d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.083840 [ 21939 ] {} <Fatal> BaseDaemon: 40. /build/contrib/llvm-project/libcxx/include/thread:295: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x2236a082 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.083997 [ 21939 ] {} <Fatal> BaseDaemon: 41. ? @ 0x7f348f8b5609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.084159 [ 21939 ] {} <Fatal> BaseDaemon: 42. clone @ 0x7f348f7da133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.084303 [ 21939 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make local object storage work consistently with s3 object storage, fix problem with append (closes https://github.com/ClickHouse/ClickHouse/issues/48465), make it configurable as independent storage. The change is backward incompatible because cache on top of local object storage is not incompatible to previous versions.

### CODE REVIEW

File: tests/queries/0_stateless/02344_show_caches.reference [hunk 1]
```diff
@@ -1,14 +0,0 @@
-cached_azure
```
Comment (kssenii) [inline tests/queries/0_stateless/02344_show_caches.reference:1]: removed this test because it is impossible to make it not flaky with custom nested disk configuration which I used in test tests/queries/0_stateless/02714_local_object_storage.sql

File: src/Disks/ObjectStorages/Cached/CachedObjectStorage.cpp [hunk 2]
```diff
@@ -86,45 +86,8 @@ std::unique_ptr<ReadBufferFromFileBase> CachedObjectStorage::readObjects( /// NO
...
-        return std::make_unique<CachedOnDiskReadBufferFromFile>(
-            path,
-            key,
-            cache,
-            implementation_buffer_creator,
-            modified_read_settings,
-            CurrentThread::isInitialized() && CurrentThread::get().getQueryContext() ? std::string(CurrentThread::getQueryId()) : "",
-            file_size.value(),
-            /* allow_seeks */true,
-            /* use_external_buffer */false);
```
Comment (kssenii) [inline src/Disks/ObjectStorages/Cached/CachedObjectStorage.cpp:126]: Removed this code because it is not needed when local object storage works the same way as s3 object storage (and in this PR is starts to), as cache is added on the different layer.

File: src/Disks/DiskLocal.cpp [hunk 3]
```diff
@@ -54,53 +51,6 @@ std::mutex DiskLocal::reservation_mutex;
 
 using DiskLocalPtr = std::shared_ptr<DiskLocal>;
 
-static void loadDiskLocalConfig(const String & name,
```
Comment (kssenii) [inline src/Disks/DiskLocal.cpp:57]: this code is just moved to a separate file, see `src/Disks/loadLocalDiskConfig.cpp`

**Review by KochetovNicolai — APPROVED** [review]

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit fbdccbd25fb90b4be63a747a59f9eb147acf972f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/48791/fbdccbd25fb90b4be63a747a59f9eb147acf972f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Disks/IDisk.h [hunk 4]
```diff
@@ -367,7 +367,13 @@ class IDisk : public Space
     /// Actually it's a part of IDiskRemote implementation but we have so
     /// complex hierarchy of disks (with decorators), so we cannot even
     /// dynamic_cast some pointer to IDisk to pointer to IDiskRemote.
-    virtual MetadataStoragePtr getMetadataStorage() = 0;
+    virtual MetadataStoragePtr getMetadataStorage()
```
Comment (alesapin) [inline src/Disks/IDisk.h:370]: Why we have implementation now?

File: src/Disks/ObjectStorages/Cached/CachedObjectStorage.cpp [hunk 5]
```diff
@@ -59,7 +59,7 @@ ReadSettings CachedObjectStorage::patchSettings(const ReadSettings & read_settin
     if (!canUseReadThroughCache())
         modified_settings.read_from_filesystem_cache_if_exists_otherwise_bypass_cache = true;
 
-    return IObjectStorage::patchSettings(modified_settings);
+    return object_storage->patchSettings(modified_settings);
```
Comment (alesapin) [inline src/Disks/ObjectStorages/Cached/CachedObjectStorage.cpp:62]: So it was a bug before this change?

File: src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp [hunk 6]
```diff
@@ -140,16 +168,10 @@ ObjectMetadata LocalObjectStorage::getObjectMetadata(const std::string & /* path
...
-    /// Same logic as in DiskLocal.
-    if (object_from.absolute_path.ends_with('/'))
-        from = from.parent_path();
-    if (fs::is_directory(from))
-        to /= from.filename();
-
-    fs::copy(from, to, fs::copy_options::recursive | fs::copy_options::overwrite_existing);
+    auto in = readObject(object_from);
+    auto out = writeObject(object_to, WriteMode::Rewrite);
+    copyData(*in, *out);
```
Comment (alesapin) [inline src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp:173]: Why we need to read/write? Why we cannot copy blob from `object_from` to `object_to`?

File: src/Disks/IDisk.cpp [hunk 7]
```diff
@@ -7,9 +7,6 @@
 #include <Common/logger_useful.h>
 #include <Common/setThreadName.h>
 #include <Core/ServerUUID.h>
-#include <Disks/ObjectStorages/MetadataStorageFromDisk.h>
-#include <Disks/ObjectStorages/FakeMetadataStorageFromDisk.h>
```
Comment (alesapin) [inline src/Disks/IDisk.cpp:11]: Maybe we can remove whole `FakeMetadataStorageFromDisk` now?

File: src/Disks/ObjectStorages/Cached/CachedObjectStorage.cpp (hunk 5 above)
Comment (kssenii) [reply src/Disks/ObjectStorages/Cached/CachedObjectStorage.cpp:62]: Not really, it did not affect anything, when readObjects is passed to inner object storage (s3) it will apply it's own patch settings for its read.

File: src/Disks/IDisk.h (hunk 4 above)
Comment (kssenii) [reply src/Disks/IDisk.h:370]: because no need to require implementation of this method from all disks, only from DiskObjectStorage, so it is ok to throw NOT_IMPLEMENTED here.

File: src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp (hunk 6 above)
Comment (kssenii) [reply src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp:173]: because the point is to not use std::filesystem::copy (for https://github.com/ClickHouse/ClickHouse/issues/42337)

File: src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp [hunk 8]
```diff
@@ -85,23 +97,39 @@ std::unique_ptr<ReadBufferFromFileBase> LocalObjectStorage::readObject( /// NOLI
...
+    FinalizeCallback && finalize_callback,
     size_t buf_size,
     const WriteSettings & /* write_settings */)
 {
-    const auto & path = object.absolute_path;
-    int flags = (mode == WriteMode::Append) ? (O_APPEND | O_CREAT | O_WRONLY) : -1;
-    LOG_TEST(log, "Write object: {}", path);
-    return std::make_unique<WriteBufferFromFile>(path, buf_size, flags);
+    if (mode != WriteMode::Rewrite)
+        throw Exception(ErrorCodes::BAD_ARGUMENTS, "LocalObjectStorage doesn't support append to files");
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp:127]: same as in S3ObjectStorage, they are consistent now.

File: src/Disks/ObjectStorages/S3/S3ObjectStorage.cpp [hunk 9]
```diff
@@ -146,7 +144,8 @@ std::unique_ptr<ReadBufferFromFileBase> S3ObjectStorage::readObjects( /// NOLINT
     if (read_settings.remote_fs_method == RemoteFSReadMethod::threadpool)
     {
         auto & reader = getThreadPoolReader();
-        return std::make_unique<AsynchronousReadIndirectBufferFromRemoteFS>(reader, disk_read_settings, std::move(s3_impl));
+        return std::make_unique<AsynchronousReadIndirectBufferFromRemoteFS>(
+            reader, disk_read_settings, std::move(s3_impl), disk_read_settings.remote_read_min_bytes_for_seek);
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Disks/ObjectStorages/S3/S3ObjectStorage.cpp:148]: I fixed it in https://github.com/ClickHouse/ClickHouse/pull/49426, so let's ignore for now.

File: src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp [hunk 10]
```diff
@@ -47,30 +50,39 @@ std::unique_ptr<ReadBufferFromFileBase> LocalObjectStorage::readObjects( /// NOL
     std::optional<size_t> read_hint,
     std::optional<size_t> file_size) const
 {
-    if (objects.size() != 1)
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Disks/ObjectStorages/Local/LocalObjectStorage.cpp:50]: No, append is not banned, it is now implemented same as in s3, which means that here `objects.size() != 1` in case append was made.

File: src/Disks/IDisk.cpp (hunk 7 above)
Comment (kssenii) [reply src/Disks/IDisk.cpp:11]: Indeed!

File: src/Disks/ObjectStorages/StoredObject.h [hunk 11]
```diff
@@ -18,31 +18,14 @@ struct StoredObject
 
     uint64_t bytes_size = 0;
 
-    std::string getPathKeyForCache() const;
-
     const std::string & getMappedPath() const;
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Disks/ObjectStorages/StoredObject.h:21]: > Why we have getter for mapped path and don't have getter for absolute path? 

fixed

> Maybe it should be const

copy assignment operator does not work then

File: src/Disks/ObjectStorages/Local/LocalObjectStorage.h [hunk 12]
```diff
@@ -77,14 +77,12 @@ class LocalObjectStorage : public IObjectStorage
         const std::string & config_prefix,
         ContextPtr context) override;
 
-    bool supportsAppend() const override { return true; }
-
-    std::string generateBlobNameForPath(const std::string & path) override { return path; }
-
-    std::string getUniqueId(const std::string & path) const override;
+    std::string generateBlobNameForPath(const std::string & path) override;
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Disks/ObjectStorages/Local/LocalObjectStorage.h:80]: Ok

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Need to address stress test failure, rest is LGTM
