### PR TITLE
Projection Index Step 1: Support _part_offset in normal projections

### LINKED ISSUE #74853: ALTER column on temporary table with projection forever stuck
### Describe the bug

This is an issue and I can't get the stack trace somehow. Also, while the ALTER statement is stuck, querying the `system.mutations` table from another client gets stuck too.

A side note. A projection gets accepted with either a GROUP BY or ORDER BY clause, but if I run this: https://fiddle.clickhouse.com/df18b861-0baf-40f2-bdae-3b72c4022f9e, the error message `DB::Exception: ORDER BY cannot be empty` is misleading, because it can be empty.

### How to reproduce

Run:

```sql
CREATE TEMPORARY TABLE t0 (c0 Int, c1 Int, PROJECTION p0 (SELECT c0 GROUP BY c0)) ENGINE = MergeTree() ORDER BY tuple();
ALTER TABLE t0 CLEAR COLUMN c0; --stuck
```
Then from another client try:
```sql
SELECT * FROM system.mutations; --stuck
```

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to specify `_part_offset` in normal projection. This is the first step to build projection index. It can be used with #58224 and can help improve https://github.com/ClickHouse/ClickHouse/pull/63207

This PR also adds some part-level constant virtual columns to projection metadata such as `_part`, `_partition_id`, etc.

This PR also adds `mergeTreeProjection` table function to read from projection parts directly. It is used for introspection.

This PR also uses a better way to construct projection metadata without relying on `TemporaryTableHolder`. This closes https://github.com/ClickHouse/ClickHouse/issues/74853. (Issue is too minor to warrant a dedicated bugfix PR on its own, but worth addressing while we're modifying related code)

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by UnamedRus** [comment]
> This PR also adds mergeTreeProjection table function to read from projection parts directly. It is used for introspection.

TBH, there is actually requests/cases when people want to read projection data directly.

**Comment by EmeraldShift** [comment]
In the example query:
```
SELECT
    count()
FROM events
WHERE (_part, _part_offset) IN (
    SELECT _part, _part_offset
    FROM events
    WHERE user_id = 42
)
```
what happens if there's a merge between executing the inner `SELECT` and the outer one? Could it return a `_part` that is not in the new merged table, and then the results are incomplete? I thought if the two queries used different snapshots than this wouldn't work. I'd be very happy to be wrong! If it means that this query will just work once this is merged, then I'm super excited!

**Comment by amosbird** [comment]
> what happens if there's a merge between executing the inner SELECT and the outer one? 

It currently uses different snapshots, which can lead to the expected issues. This will be addressed in the next phase of the projection index, where we will avoid relying on subqueries to index rows during queries.

File: src/Storages/MergeTree/MergeTreeSequentialSource.cpp [hunk 1]
```diff
@@ -214,8 +216,32 @@ try
...
+            {
+                /// Parent part
+
+                result_column = result_column->convertToFullColumnIfSparse();
+                auto & column = result_column->assumeMutableRef();
+                auto & offset_data = assert_cast<ColumnUInt64 &>(column).getData();
+                for (auto & offset : offset_data)
+                    offset += read_task_info->starting_offset;
+            }
+        }
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: This part looks good, but can we add a comment about what we do with the `_part_offset` value here?

Also, it might be a bit confusing that for the projection part  `_part_offset` is a position in the source part, but not inside the projection. Maybe we can have a different name for it? E.g. `_parent_part_offset` or `_source_part_offset`. (They can be visible and different for `mergeTreeProjection` table function, but automatically renamed `_parent_part_offset -> _part_offset` on select if the projection was used).

Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: > Also, it might be a bit confusing that for the projection part `_part_offset` is a position in the source part, but not inside the projection

Actually, I feel the opposite. In normal projections, all columns are derived from `SELECT .. FROM <source_part>`. So `SELECT _part_offset` being based on the source part feels consistent with the rest. Also, it wouldn't really make sense to support a `_part_offset` that refers to a position within the projection part itself...

File: src/Storages/MergeTree/MergeTreeData.h [hunk 2]
```diff
@@ -1802,6 +1806,8 @@ class MergeTreeData : public IStorage, public WithMutableContext
 
     mutable TemporaryParts temporary_parts;
 
+    MultiVersionVirtualsDescriptionPtr projection_virtuals;
```
[the remark this answers is not in the document]
Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeData.h:1809]: Not really. `_part_offset` isn't virtual in projections. All supported ones are part level constants.

File: src/Storages/MergeTree/MergeTreeSequentialSource.cpp (hunk 1 above)
Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: > If we store some null value in mapping, it could mean that the row was replaced, and we can filter it out.

Yeah, it's possible. But it would require deliberate design of the FOR encoding to distinguish and handle those null values correctly.

File: src/Storages/MergeTree/MergedPartOffsets.h [hunk 3]
```diff
@@ -0,0 +1,271 @@
...
+    /// Determines which part each offset belongs to and maintains mapping to new _part_offset.
+    void insert(const UInt64 * begin_cumulated_offset, const UInt64 * end_cumulated_offset)
+    {
+        for (const UInt64 * it = begin_cumulated_offset; it != end_cumulated_offset; ++it)
+        {
+            /// Find which original part this cumulated offset belongs to
+            size_t part_idx = 0;
+            while (part_idx < num_parts - 1)
+            {
+                if (starting_offsets[part_idx + 1] > *it)
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergedPartOffsets.h:199]: I was thinking about how to avoid iterating in a loop here.
One option is to encode part number into source part offsets somehow (e.g. for the part with the number `i` out of `N` we can encode as `value * N + i`).

But maybe, actually, we can use two virtual columns: `_part_num` and `_part_offset`? It seems to be relatively cheap, as (if I understand correctly) `_part_num` would exist only in currently processing chunks, and the only overhead is an additional shuffling (for sorting).

Comment (amosbird) [reply src/Storages/MergeTree/MergedPartOffsets.h:199]: I think it's possible to reuse `_part_index`. Will try to optimize and see how it goes.

File: src/Storages/ProjectionsDescription.h [hunk 4]
```diff
@@ -94,7 +97,7 @@ struct ProjectionDescription
 
     bool isPrimaryKeyColumnPossiblyWrappedInFunctions(const ASTPtr & node) const;
 
-    Block calculate(const Block & block, ContextPtr context) const;
+    Block calculate(const Block & block, ContextPtr context, const IColumnPermutation * perm_ptr = nullptr) const;
```
Comment (KochetovNicolai) [inline src/Storages/ProjectionsDescription.h:100]: I don't fully understand what is `perm_ptr` here and where it is used.
Can you add a comment, please?

Comment (amosbird) [reply src/Storages/ProjectionsDescription.h:100]: Sure. It's to correctly generate `_part_offset` column in projection during insertion.

File: src/Storages/MergeTree/MergedPartOffsets.h (hunk 3 above)
Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergedPartOffsets.h:199]: We can do it in the next PR. Not a blocker for merging.

File: src/Storages/MergeTree/MergeTreeSequentialSource.cpp (hunk 1 above)
Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: I see.

Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: > It makes sense for mergeTreeProjection function; in the same way as it makes sense for the normal table: I can use it for debugging projection. If one day _parent_part_offset is incorrectly written, I could (potentially) figure out in which row in the projection part it was.

For this purpose, maybe we can introduce `_projection_part_offset` column instead? It's just a bit weird to do that `_part_offset` -> `_parent_part_offset` mapping around projection query analysis.

> When I read the random part of MergeTask.cpp, I don't understand right away what _part_offset means.

If that only affects code reading, I'll try to add more comments. TBH, this makes implementation easier and cleaner...

Comment (alesapin) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: To me it looks much clearer to have `_part_offset` as a non-physical virtual column for all data parts (no matter parent part of projection part) and `_source_part_offset` as a physical virtual column only for projection parts. Naming is not important, but it's clear enough, that these two columns are significantly different.
`_source_part_offset`:
1. May exist only in project part
2. Stored on disk, i.e. physical
3. Points to the row in a **different data part**.
`_part_offset`:
1. Exists in both projection parts and parent parts
2. Not stored on disk, pure virtual
3. Just a number of row in this data part.

Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeSequentialSource.cpp:244]: Ok. Let's spare a dedicated name for this column, i.e. if a table is created with column `_parent_part_offset` or physical `_part_offset`, we will not allow creating projections with `_part_offset`.

**Comment by amosbird** [comment]
test_keeper_auth/test.py::test_partial_auth[get_genuine_zk] https://github.com/ClickHouse/ClickHouse/issues/78981

test_storage_rabbitmq/test.py::test_rabbitmq_tsv_with_delimiter https://github.com/ClickHouse/ClickHouse/issues/71049

I cannot find report for TSan crash in 01154_move_partition_long, but it exists in many other PR's CI runs too.

**Review by KochetovNicolai — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Fuzzer: 
```
SELECT (1 OR (isNullable(1) OR ((1 OR (8 OR (toNullable(8) IS NULL) OR 1 OR 8 OR isZeroOrNull(materialize(8))) OR 1 OR (NOT 19)) < 0) OR 8)) < 0, json.a.r.:`Array(JSON)`.^b, *, NOT isNullable(materialize(76)) FROM test PREWHERE (NOT 19) OR 1 OR ((1 OR (8 OR (0 <= ((toLowCardinality(8) OR 1 OR 8 OR (8 IS NULL)) OR 1 OR (NOT 19) OR toNullable(1))))) >= 0) QUALIFY materialize(19) ORDER BY 4 ASC, id DESC NULLS LAST FORMAT `Null`
```
not related.

**Comment by EmeraldShift** [comment]
I'm seeing some strange behavior with a projection containing `_part_offset` when parts are merged. It looks like the `_parent_part_offset` column stays equal to the original offset before the merge, while `_part` has the expected behavior of changing to the new higher-level part. See [fiddle](https://fiddle.clickhouse.com/7d4a9766-22e8-4e53-9bf6-1ca78a83ee57):
```
CREATE TABLE t (id UInt32, projection by_id (select _part_offset order by id)) ENGINE=MergeTree ORDER BY tuple();

-- Insert a lot of rows so background merges happen automatically
INSERT INTO t WITH 100000000 AS n SELECT n - number FROM numbers(n);

CREATE OR REPLACE VIEW TableUsingProjection AS
SELECT *, _part, _part_offset FROM t WHERE (_part, _part_offset) IN (SELECT (_part, _part_offset) FROM t WHERE id = 1);
CREATE OR REPLACE VIEW IntrospectProjection AS
SELECT *, _part FROM mergeTreeProjection(currentDatabase(), t, by_id) WHERE id = 1;

-- Before some automatic merges
SELECT * FROM TableUsingProjection;
SELECT * FROM IntrospectProjection;

-- Give some time for merges (non-determinstic)
SELECT sleep(3);

-- After some automatic merges
SELECT * FROM TableUsingProjection;
SELECT * FROM IntrospectProjection;
```
it's not guaranteed due to timing of merges, but I saw a result like this:
```
   +-id-+-_part-------+-_part_offset-+
1. |  1 | all_90_90_0 |      1036182 |
   +----+-------------+--------------+
   +-id-+-_parent_part_offset-+-_part-------+
1. |  1 |             1036182 | all_90_90_0 |
   +----+---------------------+-------------+
   +-sleep(3)-+
1. |        0 |
   +----------+
   +------id-+-_part-------+-_part_offset-+
1. | 5559766 | all_85_90_1 |      1036182 |
   +---------+-------------+--------------+
   +-id-+-_parent_part_offset-+-_part-------+
1. |  1 |             1036182 | all_85_90_1 |
   +----+---------------------+-------------+
```

Notably, I cannot reproduce the problem using `OPTIMIZE TABLE t FINAL` to force merges. When I do this, the `_parent_part_offset` column correctly updates to the new offset.

Is this expected given the current in-progress state of projection indexes?

**Comment by amosbird** [comment]
@EmeraldShift  The issue stems from MergeTree tables that lack a sorting key. While optimizations are intended for this case, they haven't been fully implemented yet. I’ll address it later this week.

**Comment by EmeraldShift** [comment]
Oh, interesting. I hadn't considered using `tuple()` for testing would change the behavior. For what it's worth, I'm not planning on using any unsorted tables in production. I'll keep playing around with tables with a sort key.

**Comment by amosbird** [comment]
@EmeraldShift Fixed in #81188.
