### PR TITLE
Do not merge over a gap with outdated undeleted parts

### LINKED ISSUE #44439: Logical error: intersects previous part
Appears in https://s3.amazonaws.com/clickhouse-test-reports/0/6ace8f13dbae6e9533c23f3a8b74c38a6bc6c540/stress_test__ubsan_.html

<details> 
<summary> Trace </summary>

```
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.331707 [ 444812 ] {} <Fatal> : Logical error: 'Part 77_14_14_0 intersects previous part 77_1_15_1'.
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.332042 [ 445391 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.332091 [ 445391 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: FDE5575847097E822FE11DEDB8FCEC8079853E93) (from thread 444812) (no query) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.332123 [ 445391 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.332166 [ 445391 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f2e70c7800b 0x7f2e70c57859 0x2143b703 0x2143ba0f 0x214b147f 0x2e4c61f3 0x2e782b9a 0x2e786ac3 0x2e2c5ca5 0x2bd92e21 0x2bd95057 0x2bd95a6d 0x2154671a 0x2154a0c4 0x7f2e70e2f609 0x7f2e70d54133
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.332190 [ 445391 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7f2e70c7800b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.332202 [ 445391 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f2e70c57859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.418161 [ 445391 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x2143b703 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.439252 [ 445391 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x2143ba0f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.453407 [ 445391 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.453433 [ 445391 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.453442 [ 445391 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/../src/Common/Exception.h:32: ~MessageMasked
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.453450 [ 445391 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/../src/Common/Exception.h:41: Exception
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:30.453459 [ 445391 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x214b147f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:39.446988 [ 445391 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:299: DB::MergeTreeDataMergerMutator::selectPartsToMerge(std::__1::shared_ptr<DB::FutureMergedMutatedPart>, bool, unsigned long, std::__1::function<bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)> const&, bool, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*) @ 0x2e4c61f3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:40.580831 [ 445391 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/StorageMergeTree.cpp:833: DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*) @ 0x2e782b9a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:40.932267 [ 445391 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:616: shared_ptr
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:41.743733 [ 445391 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:723: std::__1::shared_ptr<DB::MergeMutateSelectedEntry>::operator=[abi:v15000](std::__1::shared_ptr<DB::MergeMutateSelectedEntry>&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:41.743757 [ 445391 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/StorageMergeTree.cpp:1125: DB::StorageMergeTree::scheduleDataProcessingJob(DB::BackgroundJobsAssignee&) @ 0x2e786ac3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:41.775677 [ 445391 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/MergeTree/BackgroundJobsAssignee.cpp:0: DB::BackgroundJobsAssignee::threadFunc() @ 0x2e2c5ca5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:41.887969 [ 445391 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:0: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2bd92e21 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:42.792000 [ 445391 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: DB::BackgroundSchedulePool::threadFunction() @ 0x2bd95057 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:42.807387 [ 445391 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.683495 [ 445391 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.683721 [ 445391 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.683741 [ 445391 ] {} <Fatal> BaseDaemon: 14.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>::operator()[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.683756 [ 445391 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2bd95a6d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.698743 [ 445391 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.698769 [ 445391 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.698780 [ 445391 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x2154671a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.714553 [ 445391 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x2154a0c4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.714583 [ 445391 ] {} <Fatal> BaseDaemon: 17. ? @ 0x7f2e70e2f609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:43.714599 [ 445391 ] {} <Fatal> BaseDaemon: 18. __clone @ 0x7f2e70d54133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:18:44.021781 [ 445391 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 6B147015A22AE43B54E74D027A986673)
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.20 15:19:35.067118 [ 444632 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

</details>

What happened:
- there was 15 parts: 77_1_1_0 .... 77_15_15_0
- part 77_13_13_0 has been dropped and replaced with 77_13_13_1
- 77_13_13_1 was going to be dropped as empty part.
  - 77_13_13_1 became outdated but still present on the disk
- mutation started and cover all parts from 1 to 15 with a gap inside, 13_13 is outdated
- 77_1_15_1 is committed as a result of mutation
- server has been restarted
- 77_1_15_1 has been loaded as active part
- 77_13_13_1 has been loaded as active part also, this is a bug, that triggered following error
- 77_14_14_0 has been loaded as active part
- 77_13_13_1 has been deleted as empty, 77_1_15_1 and 77_14_14_0 are left as active
- MergeTreeDataMergerMutator::selectPartsToMerge has a validation for parts, it fails when tries to merge that set of parts with incorrect message

There are 3 problems:

1. Mutation made a part over a gap with the name 77_1_15_1, 77_13_13_1 was in the gap as outdated. They both have level 
      - do not cover a gap with outdated part with part with the same level, make a split at that point.
2. Server after restart went too far, it didn't fail on loading parts stage. 
      - it should fail earlier.
3. MergeTreeDataMergerMutator::selectPartsToMerge  could have better check with correct message

### PR DESCRIPTION
**Pull request by CheSema**
Fixes https://github.com/ClickHouse/ClickHouse/issues/44439

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by CheSema** [comment]
One more problem have found.
Empty parts wasn't be able to be deleting in clearEmptyParts. The ptr has been saved to parts. This leads to unpredicted life time of empty parts.
Changed it. Now they are deleted with respect of old_parts_lifetime.

File: tests/queries/0_stateless/00976_system_stop_ttl_merges.sh [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+$CLICKHOUSE_CLIENT --query "insert into ttl values (toDateTime('2000-10-10 00:00:00'), 1), (toDateTime('2000-10-10 00:00:00'), 2);"
+$CLICKHOUSE_CLIENT --query "insert into ttl values (toDateTime('2100-10-10 00:00:00'), 3), (toDateTime('2100-10-10 00:00:00'), 4);"
+
+$CLICKHOUSE_CLIENT --query "optimize table ttl partition 10 final;"
+$CLICKHOUSE_CLIENT --query "select * from ttl order by d, a;"
+
+$CLICKHOUSE_CLIENT --query "system start ttl merges ttl;"
+$CLICKHOUSE_CLIENT --query "optimize table ttl partition 10 final;"
+
+wait_for_merges_done ttl
```
Comment (tavplubix) [inline tests/queries/0_stateless/00976_system_stop_ttl_merges.sh:25]: OPTIMIZE query is synchronous by default, we don't need to wait for merges

Comment (CheSema) [reply tests/queries/0_stateless/00976_system_stop_ttl_merges.sh:25]: > OPTIMIZE query is synchronous by default, we don't need to wait for merges

Here is the explanation what is happening.
https://github.com/ClickHouse/ClickHouse/issues/44982
In a short version
- optimize final failes due to concurrent background merge
- next request is concurrent with background merge and sees data before that merge

Comment (tavplubix) [reply tests/queries/0_stateless/00976_system_stop_ttl_merges.sh:25]: But there are no concurrent background merges in 00976_system_stop_ttl_merges (afaik)

Comment (tavplubix) [reply tests/queries/0_stateless/00976_system_stop_ttl_merges.sh:25]: Also it's not enough to check `system.merges` as `wait_for_merges_done` does anyway.

**Comment by CheSema** [comment]
All tests are good in previous build except test_partition/test.py::test_detached_part_dir_exists and test_partition/test.py::test_attach_check_all_parts.
Fixed them at recent commit.

**Comment by CheSema** [comment]
I have checked. That after rework of loading tables parts there is some checks present for parts consistency.
So, loadDataParts throws "Logical error: 'Part all_3_3_1 intersects previous part all_1_4_1. It is a bug!'." in that case.

**Comment by CheSema** [comment]
test_system_merges/test.py::test_mutation_simple[replicated] -- flacky

https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X211dGF0aW9uX3NpbXBsZVtyZXBsaWNhdGVkXSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

File: src/Storages/StorageMergeTree.cpp [hunk 2]
```diff
@@ -816,9 +816,47 @@ MergeMutateSelectedEntryPtr StorageMergeTree::selectPartsToMerge(
...
+            if (disable_reason)
+                *disable_reason = "Some parts contains differ projections";
+            return false;
+        }
+
+        auto maxPossibleLevel = getMaxLevelInBetween(left, right);
+        if (maxPossibleLevel > std::max(left->info.level, right->info.level))
+        {
+            if (disable_reason)
+                *disable_reason = fmt::format("There is a part in a gap between two active parts ({}, {}) with merge level {} higher than this active parts have", left->name, right->name, maxPossibleLevel);
```
Comment (tavplubix) [inline src/Storages/StorageMergeTree.cpp:855]:
```suggestion
                *disable_reason = fmt::format("There is an outdated part in a gap between two active parts ({}, {}) with merge level {} higher than these active parts have", left->name, right->name, maxPossibleLevel);
```

**Review by tavplubix — APPROVED** [review]

File: src/Storages/StorageMergeTree.cpp [hunk 3]
```diff
@@ -1097,6 +1134,30 @@ MergeMutateSelectedEntryPtr StorageMergeTree::selectPartsToMutate(
...
+{
+    auto parts_lock = lockParts();
+
+    auto begin = data_parts_by_info.find(left->info);
+    if (begin == data_parts_by_info.end())
+        return 0;
+
+    auto end = data_parts_by_info.find(right->info);
+    if (end == data_parts_by_info.end())
+        return 0;
```
[the remark this answers is not in the document]
Comment (CheSema) [reply src/Storages/StorageMergeTree.cpp:1147]: Actually never. But I checked result just in case. 
Lets I change it to the LOGICAL_ERROR.

File: tests/queries/0_stateless/01451_detach_drop_part.sql [hunk 4]
```diff
@@ -1,6 +1,6 @@
 DROP TABLE IF EXISTS mt_01451;
 
-CREATE TABLE mt_01451 (v UInt8) ENGINE = MergeTree() order by tuple();
+CREATE TABLE mt_01451 (v UInt8) ENGINE = MergeTree() order by tuple() SETTINGS old_parts_lifetime=0;
```
[the remark this answers is not in the document]
Comment (tavplubix) [reply tests/queries/0_stateless/01451_detach_drop_part.sql:3]: > And that call removes parts

It does not if some part's refcount is not 1, for example, due to a parallel `select * from system.parts` from another test, so it looks fragile. But I guess we can keep it as is for now.

**Review by tavplubix — APPROVED** [review]

File: src/Storages/StorageMergeTree.h [hunk 5]
```diff
@@ -216,8 +216,8 @@ class StorageMergeTree final : public MergeTreeData
     /// Returns the maximum level of all outdated parts in a range (left; right), or 0 in case if empty range.
     /// Merges have to be aware of the outdated part's levels inside designated merge range.
     /// When two parts all_1_1_0, all_3_3_0 are merged into all_1_3_1, the gap between those parts have to be verified.
-    /// There should not be an unactive part all_1_1_1. Otherwise it is imposible to load parts after restart, they intersects.
-    /// Therefore this function is used in merge predicate in order to prevent merges over the gaps with hight level outdated parts.
+    /// There should not be an unactive part all_1_1_1. Otherwise it is impossible to load parts after restart, they intersects.
+    /// Therefore this function is used in merge predicate in order to prevent merges over the gaps with height level outdated parts.
```
Comment (tavplubix) [inline src/Storages/StorageMergeTree.h:220]: Did you mean "high"?

Comment (CheSema) [reply src/Storages/StorageMergeTree.h:220]: Oh each :(

**Comment by CheSema** [comment]
test_cluster_copier/test.py::test_copy_month_to_week_partition_with_recovering
Flaky test
https://github.com/ClickHouse/ClickHouse/issues/30399

test_backup_restore_on_cluster/test_disallow_concurrency.py::test_concurrent_restores_on_different_node
Flaky new test
https://github.com/ClickHouse/ClickHouse/pull/45072#issuecomment-1399227123

**Comment by RinChanNOWWW** [comment]
> One more problem have found. Empty parts wasn't be able to be deleting in clearEmptyParts. The ptr has been saved to parts. This leads to unpredicted life time of empty parts. Changed it. Now they are deleted with respect of old_parts_lifetime.

Hello, can you explain more detail about this problem? Why can't we clear empty parts immediately (set `remove_time`to 0)?
