### PR TITLE
Fix TZ variable with file path prefix causing timezone error

### LINKED ISSUE #86495: clickhouse-client fails to switch to server time zone if TZ points to file
### Company or project name

_No response_

### Describe what's wrong

In my environment, `TZ=:/etc/localtime`, which is precisely the example in https://sourceware.org/glibc/manual/latest/html_node/TZ-Variable.html.  Unfortunately, `clickhouse-client` is unable to cope with this setting:
```
$ export TZ=:/etc/localtime
$ ./clickhouse-client -s -u default --password
ClickHouse client version 25.8.1.5101 (official build).
Password for user (default):
Connecting to localhost:9440 as user default.
Connected to ClickHouse server version 25.8.1.

Warning: could not switch to server time zone: UTC, reason: Code: 36. DB::Exception: Cannot load time zone /etc/localtime. (BAD_ARGUMENTS) (version 25.8.1.5101 (official build))
Proceeding with local time zone.

Code: 36. DB::Exception: Cannot load time zone /etc/localtime. (BAD_ARGUMENTS)
```
The problem can be avoided with `unset TZ`:
```
$ unset TZ
$ ./clickhouse-client -s -u default --password --format=pretty -q 'SELECT serverTimeZone()'
Password for user (default):
   ┏━━━━━━━━━━━━━━━━━━┓
   ┃ serverTimeZone() ┃
   ┡━━━━━━━━━━━━━━━━━━┩
1. │ UTC              │
   └──────────────────┘
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

- Server version: 25.8.1.5101
- Server timezone:
```
<clickhouse>
  <timezone>UTC</timezone>
</clickhouse>
```
- Client version: 25.8.1.5101
- No client configuration file
- Run:
```
export TZ=:/etc/localtime
./clickhouse-client -s -u default --password
```

### Expected behavior

The client should be able to set the time zone to UTC (the server setting).

### Error message and/or stacktrace

```
$ ./clickhouse-client -s -u default --password --verbose --stacktrace
ClickHouse client version 25.8.1.5101 (official build).
Password for user (default):
Connecting to localhost:9440 as user default.
Connected to ClickHouse server version 25.8.1.

Warning: could not switch to server time zone: UTC, reason: Code: 36. DB::Exception: Cannot load time zone /etc/localtime. (BAD_ARGUMENTS) (version 25.8.1.5101 (official build))
Proceeding with local time zone.

Code: 36. DB::Exception: Cannot load time zone /etc/localtime. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001339f11f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c84c4ce
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c84bf80
3. DB::Exception::Exception<std::basic_string_view<char, std::char_traits<char>>&>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type>, std::basic_string_view<char, std::char_traits<char>>&) @ 0x000000000cf98a6b
4. DateLUTImpl::DateLUTImpl(std::basic_string_view<char, std::char_traits<char>>) @ 0x000000001338b6dd
5. DateLUT::getImplementation(std::basic_string_view<char, std::char_traits<char>>) const @ 0x00000000133870e8
6. DateLUT::DateLUT() @ 0x0000000013388b17
7. DateLUT::instance() @ 0x0000000013386ef5
8. DB::ClientBase::runInteractive() @ 0x000000001981ab65
9. DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x000000001362ce23
10. Poco::Util::Application::run() @ 0x000000001ef20366
11. mainEntryClickHouseClient(int, char**) @ 0x000000001363ad3d
12. main @ 0x000000000c8442fd
13. __libc_start_main @ 0x000000000003a7e5
14. _start @ 0x00000000074e402e


$
```

### Additional context

_No response_

### Version info
- Resolved by: #99000
- Merged into: `26.3.1.735`

### PR DESCRIPTION
**Pull request by Onyx2406**
Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):
Fixed `clickhouse-client` failing to switch timezone when `TZ` environment variable uses POSIX file path syntax (e.g. `TZ=:/etc/localtime`).

Documentation entry for user-facing changes
- [ ] Documentation is not required (bug fix)

---

## What this PR does

When `TZ=:/etc/localtime` (POSIX standard format), `clickhouse-client` fails with:
```
Cannot load time zone /etc/localtime. (BAD_ARGUMENTS)
```

### Root cause

`DateLUT.cpp` correctly strips the leading `:` from the TZ value but then uses the remaining file path (`/etc/localtime`) as the timezone **name**. At line 99, `tz_name` (which is `"/etc/localtime"`) is returned instead of the resolved timezone name from the file's location in the timezone database.

When TZ is unset, the same `/etc/localtime` file is used but `tz_name` is empty, so the code correctly resolves the timezone from the relative path (e.g., `UTC`, `America/New_York`).

### Fix (6 insertions, 1 file)

When the TZ value after stripping `:` starts with `/` (it's a file path, not a timezone name), don't set `tz_name`. This lets the existing path resolution logic at line 99 derive the correct timezone name from the file's position relative to the timezone database — the same logic used when TZ is unset.

### Test plan

- [ ] CI (full test suite)
- Manual: `export TZ=:/etc/localtime && clickhouse-client` should connect without timezone error

Fixes #86495

---

> [!NOTE]
> **Low Risk**
> Small, targeted change to timezone resolution when `TZ` is set to an absolute file path; it reuses existing resolution logic and adds coverage via a simple stateless test.
> 
> **Overview**
> Fixes default timezone detection so that when `TZ` uses POSIX file-path syntax (e.g. `TZ=:/etc/localtime`), the absolute path is **not** treated as a timezone *name*, allowing the timezone to be derived from the tzdata database as intended.
> 
> Adds a stateless test (`04041_tz_file_path_colon_prefix`) that runs `clickhouse-local` with `TZ=:/etc/localtime` and verifies it succeeds.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6d84784ea155d50e3804d15c19d2b01edaed6523. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.735`

### CODE REVIEW

File: src/Common/DateLUT.cpp [hunk 1]
```diff
@@ -61,7 +61,12 @@ std::string determineDefaultTimeZone()
             ++tz_env_var;
 
         tz_file_path = tz_env_var;
-        tz_name = tz_env_var;
+
+        /// If TZ points to a file path (e.g. TZ=:/etc/localtime per POSIX),
+        /// don't use the path as the timezone name — let it be resolved from
+        /// the file's location relative to the timezone database. See #86495.
+        if (*tz_env_var != '/')
```
Comment (alexey-milovidov) [inline src/Common/DateLUT.cpp]:
```suggestion
        if (tz_env_var[0] != '/')
```

**Review by alexey-milovidov — APPROVED** [review]
Perfect.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
The LLVM Coverage job failure in this PR is caused by a bug introduced in #96738 — the job crashes when a PR has no C++ source code changes. The fix is in #99032. Since this branch is in a fork, I can't merge it directly — please merge master once #99032 lands, or cherry-pick the fix. cc @alexbakharew
