### PR TITLE
Fix TSan "unlock of an unlocked mutex" in CHECK TABLE for ReplicatedMergeTree

### LINKED ISSUE #87916: ThreadSanitizer: unlock of an unlocked mutex in test_check_table/test.py
### Describe the bug

Integration tests:
test_check_table/test.py::test_check_replicated_does_not_block_shutdown[ReplicatedMergeTree]
[report](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86543&sha=9c59bb4d571cc8efd3dc9e18f9dbfb3c7f0ee622&name_0=PR&name_1=Integration%20tests%20%28amd_tsan%2C%204%2F6%29&name_2=test_check_table%2Ftest.py%3A%3Atest_check_replicated_does_not_block_shutdown%5BReplicatedMergeTree%5D) 
It seems it's appeared due to a specific test order, and it's reproducible on rerun on this branch 
```
E Exception: Sanitizer assert found for instance ==================
E WARNING: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) (pid=8)
E #0 pthread_mutex_unlock (clickhouse+0x923a72e) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #1 std::__1::__libcpp_mutex_unlock[abi:ne190107](pthread_mutex_t*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/support/pthread.h:103:10 (clickhouse+0x2ca30659) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #2 std::__1::mutex::unlock() ci/tmp/build/./contrib/llvm-project/libcxx/src/mutex.cpp:37:12 (clickhouse+0x2ca30659)
E #3 std::__1::unique_lock::~unique_lock[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__mutex/unique_lock.h:65:13 (clickhouse+0x2153b0d9) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #4 DB::StorageReplicatedMergeTree::DataValidationTasks::~DataValidationTasks() ci/tmp/build/./src/Storages/StorageReplicatedMergeTree.h:1014:12 (clickhouse+0x2153b0d9)
E #5 DB::StorageReplicatedMergeTree::DataValidationTasks::~DataValidationTasks() ci/tmp/build/./src/Storages/StorageReplicatedMergeTree.h:1014:12 (clickhouse+0x2153b0d9)
E #6 std::__1::default_delete::operator()[abi:ne190107](DB::StorageReplicatedMergeTree::DataValidationTasks*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5 (clickhouse+0x21556475) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #7 std::__1::__shared_ptr_pointer, std::__1::allocator>::__on_zero_shared() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:227:3 (clickhouse+0x21556475)
E #8 std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7 (clickhouse+0x1cc340e4) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #9 std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25 (clickhouse+0x1cc340e4)
E #10 std::__1::shared_ptr::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17 (clickhouse+0x1cc340e4)
E #11 DB::(anonymous namespace)::TableCheckTask::~TableCheckTask() ci/tmp/build/./src/Interpreters/InterpreterCheckQuery.cpp:105:7 (clickhouse+0x1cc340e4)
E #12 void std::__1::__destroy_at[abi:ne190107](DB::(anonymous namespace)::TableCheckTask*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11 (clickhouse+0x1cc33ea8) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #13 void std::__1::allocator_traits>::destroy[abi:ne190107](std::__1::allocator&, DB::(anonymous namespace)::TableCheckTask*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5 (clickhouse+0x1cc33ea8)
E #14 void std::__1::__shared_ptr_emplace>::__on_zero_shared_impl[abi:ne190107], 0>() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:283:5 (clickhouse+0x1cc33ea8)
E #15 std::__1::__shared_ptr_emplace>::__on_zero_shared() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:286:78 (clickhouse+0x1cc33ea8)
E #16 std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7 (clickhouse+0x1cc39725) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #17 std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25 (clickhouse+0x1cc39725)
E #18 std::__1::shared_ptr::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17 (clickhouse+0x1cc39725)
E #19 DB::(anonymous namespace)::TableCheckWorkerProcessor::transform(DB::Chunk&) ci/tmp/build/./src/Interpreters/InterpreterCheckQuery.cpp:330:5 (clickhouse+0x1cc39725)
E #20 DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) ci/tmp/build/./src/Processors/ISimpleTransform.h:33:9 (clickhouse+0x17309076) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #21 DB::ISimpleTransform::work() ci/tmp/build/./src/Processors/ISimpleTransform.cpp:98:9 (clickhouse+0x226fd3c7) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #22 DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53:26 (clickhouse+0x227298d1) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #23 DB::ExecutionThreadContext::executeTask() ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:102:9 (clickhouse+0x227298d1)
E #24 DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::__1::atomic*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351:26 (clickhouse+0x227162d7) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #25 DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:279:5 (clickhouse+0x227183a3) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #26 DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr)::$_0::operator()() const ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:565:17 (clickhouse+0x227183a3)
E #27 decltype(std::declval)::$_0&>()()) std::__1::__invoke[abi:ne190107])::$_0&>(DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x227183a3)
E #28 void std::__1::__invoke_void_return_wrapper::__call[abi:ne190107])::$_0&>(DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224:5 (clickhouse+0x227183a3)
E #29 std::__1::__function::__default_alloc_func)::$_0, void ()>::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12 (clickhouse+0x227183a3)
E #30 void std::__1::__function::__policy_invoker::__call_impl[abi:ne190107])::$_0, void ()>>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12 (clickhouse+0x227183a3)
E #31 std::__1::__function::__policy_func::operator()[abi:ne190107]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12 (clickhouse+0x138b095a) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #32 std::__1::function::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10 (clickhouse+0x138b095a)
E #33 ThreadPoolImpl>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:802:17 (clickhouse+0x138b095a)
E #34 decltype(*std::declval>::ThreadFromThreadPool*&>().*std::declval>::ThreadFromThreadPool::*&)()>()()) std::__1::__invoke[abi:ne190107]>::ThreadFromThreadPool::*&)(), ThreadPoolImpl>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&)(), ThreadPoolImpl>::ThreadFromThreadPool*&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117:25 (clickhouse+0x138b93c4) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #35 decltype(auto) std::__1::__apply_tuple_impl[abi:ne190107]>::ThreadFromThreadPool::*&)(), std::__1::tuple>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&)(), std::__1::tuple>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<0ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1354:5 (clickhouse+0x138b93c4)
E #36 decltype(auto) std::__1::apply[abi:ne190107]>::ThreadFromThreadPool::*&)(), std::__1::tuple>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&)(), std::__1::tuple>::ThreadFromThreadPool*>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1358:5 (clickhouse+0x138b93c4)
E #37 ThreadFromGlobalPoolImpl::ThreadFromGlobalPoolImpl>::ThreadFromThreadPool::*)(), ThreadPoolImpl>::ThreadFromThreadPool*>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13 (clickhouse+0x138b93c4)
E #38 decltype(std::declval>::ThreadFromThreadPool::*)()>()(std::declval>::ThreadFromThreadPool*>())) std::__1::__invoke[abi:ne190107]::ThreadFromGlobalPoolImpl>::ThreadFromThreadPool::*)(), ThreadPoolImpl>::ThreadFromThreadPool*>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&)::'lambda'()&>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x138b92e1) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #39 void std::__1::__invoke_void_return_wrapper::__call[abi:ne190107]::ThreadFromGlobalPoolImpl>::ThreadFromThreadPool::*)(), ThreadPoolImpl>::ThreadFromThreadPool*>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&)::'lambda'()&>(ThreadFromGlobalPoolImpl::ThreadFromGlobalPoolImpl>::ThreadFromThreadPool::*)(), ThreadPoolImpl>::ThreadFromThreadPool*>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224:5 (clickhouse+0x138b92e1)
E #40 std::__1::__function::__default_alloc_func::ThreadFromGlobalPoolImpl>::ThreadFromThreadPool::*)(), ThreadPoolImpl>::ThreadFromThreadPool*>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&)::'lambda'(), void ()>::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12 (clickhouse+0x138b92e1)
E #41 void std::__1::__function::__policy_invoker::__call_impl[abi:ne190107]::ThreadFromGlobalPoolImpl>::ThreadFromThreadPool::*)(), ThreadPoolImpl>::ThreadFromThreadPool*>(void (ThreadPoolImpl>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12 (clickhouse+0x138b92e1)
E #42 std::__1::__function::__policy_func::operator()[abi:ne190107]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12 (clickhouse+0x138ace22) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #43 std::__1::function::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10 (clickhouse+0x138ace22)
E #44 ThreadPoolImpl::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:812:17 (clickhouse+0x138ace22)
E #45 decltype(*std::declval::ThreadFromThreadPool*>().*std::declval::ThreadFromThreadPool::*)()>()()) std::__1::__invoke[abi:ne190107]::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*, void>(void (ThreadPoolImpl::ThreadFromThreadPool::*&&)(), ThreadPoolImpl::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117:25 (clickhouse+0x138b5edb) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #46 void std::__1::__thread_execute[abi:ne190107]>, void (ThreadPoolImpl::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*, 2ul>(std::__1::tuple>, void (ThreadPoolImpl::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:192:3 (clickhouse+0x138b5edb)
E #47 void* std::__1::__thread_proxy[abi:ne190107]>, void (ThreadPoolImpl::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:201:3 (clickhouse+0x138b5edb)
E
E Location is heap block of size 208 at 0x7234000581b0 allocated by thread T5:
E #0 operator new(unsigned long) (clickhouse+0x92ba042) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #1 DB::BackgroundSchedulePool::createTask(std::__1::basic_string, std::__1::allocator> const&, std::__1::function const&) ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:309:49 (clickhouse+0x1a6b5d70) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #2 DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&) ci/tmp/build/./src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:41:52 (clickhouse+0x2201d8d0) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #3 DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(DB::TableZnodeInfo const&, DB::LoadingStrictnessLevel, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr, std::__1::basic_string, std::__1::allocator> const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr>, bool, DB::ZooKeeperRetriesInfo const&) ci/tmp/build/./src/Storages/StorageReplicatedMergeTree.cpp:418:7 (clickhouse+0x2138caa3) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #4 DB::StorageReplicatedMergeTree* std::__1::construct_at[abi:ne190107], std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>, bool&, DB::ZooKeeperRetriesInfo&, DB::StorageReplicatedMergeTree*>(DB::StorageReplicatedMergeTree*, DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>&&, bool&, DB::ZooKeeperRetriesInfo&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:41:46 (clickhouse+0x220f36ac) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #5 DB::StorageReplicatedMergeTree* std::__1::__construct_at[abi:ne190107], std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>, bool&, DB::ZooKeeperRetriesInfo&, DB::StorageReplicatedMergeTree*>(DB::StorageReplicatedMergeTree*, DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>&&, bool&, DB::ZooKeeperRetriesInfo&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:49:10 (clickhouse+0x220f36ac)
E #6 void std::__1::allocator_traits>::construct[abi:ne190107], std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>, bool&, DB::ZooKeeperRetriesInfo&, void, 0>(std::__1::allocator&, DB::StorageReplicatedMergeTree*, DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>&&, bool&, DB::ZooKeeperRetriesInfo&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:328:5 (clickhouse+0x220f36ac)
E #7 std::__1::__shared_ptr_emplace>::__shared_ptr_emplace[abi:ne190107], std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>, bool&, DB::ZooKeeperRetriesInfo&, std::__1::allocator, 0>(std::__1::allocator, DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>&&, bool&, DB::ZooKeeperRetriesInfo&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:264:5 (clickhouse+0x220f36ac)
E #8 std::__1::shared_ptr std::__1::allocate_shared[abi:ne190107], DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>, bool&, DB::ZooKeeperRetriesInfo&, 0>(std::__1::allocator const&, DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>&&, bool&, DB::ZooKeeperRetriesInfo&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:843:51 (clickhouse+0x220f36ac)
E #9 std::__1::shared_ptr std::__1::make_shared[abi:ne190107], std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>, bool&, DB::ZooKeeperRetriesInfo&, 0>(DB::TableZnodeInfo&, DB::LoadingStrictnessLevel const&, DB::StorageID const&, std::__1::basic_string, std::__1::allocator> const&, DB::StorageInMemoryMetadata&, std::__1::shared_ptr&, std::__1::basic_string, std::__1::allocator>&, DB::MergeTreeData::MergingParams&, std::__1::unique_ptr>&&, bool&, DB::ZooKeeperRetriesInfo&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:851:10 (clickhouse+0x220ef9de) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #10 DB::create(DB::StorageFactory::Arguments const&) ci/tmp/build/./src/Storages/MergeTree/registerStorageMergeTree.cpp:884:16 (clickhouse+0x220ef9de)
E #11 decltype(std::declval (*&)(DB::StorageFactory::Arguments const&)>()(std::declval())) std::__1::__invoke[abi:ne190107] (*&)(DB::StorageFactory::Arguments const&), DB::StorageFactory::Arguments const&>(std::__1::shared_ptr (*&)(DB::StorageFactory::Arguments const&), DB::StorageFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x1a1a7023) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #12 std::__1::shared_ptr std::__1::__invoke_void_return_wrapper, false>::__call[abi:ne190107] (*&)(DB::StorageFactory::Arguments const&), DB::StorageFactory::Arguments const&>(std::__1::shared_ptr (*&)(DB::StorageFactory::Arguments const&), DB::StorageFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:216:12 (clickhouse+0x1a1a7023)
E #13 std::__1::__function::__default_alloc_func (*)(DB::StorageFactory::Arguments const&), std::__1::shared_ptr (DB::StorageFactory::Arguments const&)>::operator()[abi:ne190107](DB::StorageFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12 (clickhouse+0x1a1a7023)
E #14 std::__1::shared_ptr std::__1::__function::__policy_invoker (DB::StorageFactory::Arguments const&)>::__call_impl[abi:ne190107] (*)(DB::StorageFactory::Arguments const&), std::__1::shared_ptr (DB::StorageFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12 (clickhouse+0x1a1a7023)
E #15 std::__1::__function::__policy_func (DB::StorageFactory::Arguments const&)>::operator()[abi:ne190107](DB::StorageFactory::Arguments const&) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12 (clickhouse+0x211fcb25) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #16 std::__1::function (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10 (clickhouse+0x211fcb25)
E #17 DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string, std::__1::allocator> const&, std::__1::shared_ptr, std::__1::shared_ptr, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel, bool) const ci/tmp/build/./src/Storages/StorageFactory.cpp:242:16 (clickhouse+0x211fcb25)
E #18 DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::__1::unique_ptr>&, DB::LoadingStrictnessLevel) ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:1982:42 (clickhouse+0x1c62d036) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #19 DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:1752:20 (clickhouse+0x1c623b58) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #20 DB::InterpreterCreateQuery::execute() ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:2377:12 (clickhouse+0x1c63459a) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #21 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::__1::unique_ptr>&, std::__1::shared_ptr&, std::__1::shared_ptr, std::__1::function) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1603:40 (clickhouse+0x1cba2540) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #22 DB::executeQuery(std::__1::basic_string, std::__1::allocator> const&, std::__1::shared_ptr, DB::QueryFlags, DB::QueryProcessingStage::Enum) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1812:11 (clickhouse+0x1cb9c2cd) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #23 DB::TCPHandler::runImpl() ci/tmp/build/./src/Server/TCPHandler.cpp:743:68 (clickhouse+0x225cf0b4) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #24 DB::TCPHandler::run() ci/tmp/build/./src/Server/TCPHandler.cpp:2754:9 (clickhouse+0x225f8027) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #25 Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3 (clickhouse+0x2b4e5ba2) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #26 Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38 (clickhouse+0x2b4e6471) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #27 Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14 (clickhouse+0x2b455090) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #28 Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x2b45326f) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #29 Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:341:27 (clickhouse+0x2b4514c9) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E
E Mutex M0 (0x723400058220) created at:
E #0 pthread_mutex_lock (clickhouse+0x923a1ce) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #1 std::__1::__libcpp_mutex_lock[abi:ne190107](pthread_mutex_t*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/support/pthread.h:95:10 (clickhouse+0x2ca30599) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #2 std::__1::mutex::lock() ci/tmp/build/./contrib/llvm-project/libcxx/src/mutex.cpp:29:12 (clickhouse+0x2ca30599)
E #3 std::__1::lock_guard::lock_guard[abi:ne190107](std::__1::mutex&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__mutex/lock_guard.h:33:10 (clickhouse+0x1a6b062c) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #4 DB::BackgroundSchedulePoolTaskInfo::execute(DB::BackgroundSchedulePool&) ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:123:21 (clickhouse+0x1a6b062c)
E #5 DB::BackgroundSchedulePool::threadFunction() ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:427:19 (clickhouse+0x1a6b60c2) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #6 DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1::operator()() const ci/tmp/build/./src/Core/BackgroundSchedulePool.cpp:230:79 (clickhouse+0x1a6b8310) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #7 decltype(std::declval, StrongTypedef, char const*)::$_1&>()()) std::__1::__invoke[abi:ne190107], StrongTypedef, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x1a6b8310)
E #8 decltype(auto) std::__1::__apply_tuple_impl[abi:ne190107], StrongTypedef, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1354:5 (clickhouse+0x1a6b8310)
E #9 decltype(auto) std::__1::apply[abi:ne190107], StrongTypedef, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&, std::__1::tuple<>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1358:5 (clickhouse+0x1a6b8310)
E #10 ThreadFromGlobalPoolImpl::ThreadFromGlobalPoolImpl, StrongTypedef, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13 (clickhouse+0x1a6b8310)
E #11 decltype(std::declval, StrongTypedef, char const*)::$_1>()()) std::__1::__invoke[abi:ne190107]::ThreadFromGlobalPoolImpl, StrongTypedef, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x1a6b8310)
E #12 void std::__1::__invoke_void_return_wrapper::__call[abi:ne190107]::ThreadFromGlobalPoolImpl, StrongTypedef, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&)::'lambda'()&>(ThreadFromGlobalPoolImpl::ThreadFromGlobalPoolImpl, StrongTypedef, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224:5 (clickhouse+0x1a6b8310)
E #13 std::__1::__function::__default_alloc_func::ThreadFromGlobalPoolImpl, StrongTypedef, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&)::'lambda'(), void ()>::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12 (clickhouse+0x1a6b8310)
E #14 void std::__1::__function::__policy_invoker::__call_impl[abi:ne190107]::ThreadFromGlobalPoolImpl, StrongTypedef, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, StrongTypedef, StrongTypedef, char const*)::$_1&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12 (clickhouse+0x1a6b8310)
E #15 std::__1::__function::__policy_func::operator()[abi:ne190107]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12 (clickhouse+0x138ace22) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #16 std::__1::function::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10 (clickhouse+0x138ace22)
E #17 ThreadPoolImpl::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:812:17 (clickhouse+0x138ace22)
E #18 decltype(*std::declval::ThreadFromThreadPool*>().*std::declval::ThreadFromThreadPool::*)()>()()) std::__1::__invoke[abi:ne190107]::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*, void>(void (ThreadPoolImpl::ThreadFromThreadPool::*&&)(), ThreadPoolImpl::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117:25 (clickhouse+0x138b5edb) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #19 void std::__1::__thread_execute[abi:ne190107]>, void (ThreadPoolImpl::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*, 2ul>(std::__1::tuple>, void (ThreadPoolImpl::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:192:3 (clickhouse+0x138b5edb)
E #20 void* std::__1::__thread_proxy[abi:ne190107]>, void (ThreadPoolImpl::ThreadFromThreadPool::*)(), ThreadPoolImpl::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:201:3 (clickhouse+0x138b5edb)
E
E Thread T5 'TCPHandler' (tid=14, running) created by main thread at:
E #0 pthread_create (clickhouse+0x92384c1) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #1 Poco::ThreadImpl::startImpl(Poco::SharedPtr>) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:203:7 (clickhouse+0x2b450d87) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #2 Poco::Thread::start(Poco::Runnable&) ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:118:2 (clickhouse+0x2b452b6f) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #3 Poco::PooledThread::start() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:91:10 (clickhouse+0x2b4555fe) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #4 Poco::ThreadPool::ThreadPool(int, int, int, int, unsigned long, unsigned long) ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:258:12 (clickhouse+0x2b4555fe)
E #5 DB::Server::main(std::__1::vector, std::__1::allocator>, std::__1::allocator, std::__1::allocator>>> const&) ci/tmp/build/./programs/server/Server.cpp:1246:22 (clickhouse+0x13b51dc3) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #6 Poco::Util::Application::run() ci/tmp/build/./base/poco/Util/src/Application.cpp:315:8 (clickhouse+0x2b51d8be) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #7 DB::Server::run() ci/tmp/build/./programs/server/Server.cpp:630:25 (clickhouse+0x13b47b96) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #8 Poco::Util::ServerApplication::run(int, char**) ci/tmp/build/./base/poco/Util/src/ServerApplication.cpp:131:9 (clickhouse+0x2b53b460) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #9 mainEntryClickHouseServer(int, char**) ci/tmp/build/./programs/server/Server.cpp:417:20 (clickhouse+0x13b4464c) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E #10 main ci/tmp/build/./programs/main.cpp:380:21 (clickhouse+0x92bcb64) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd)
E
E SUMMARY: ThreadSanitizer: unlock of an unlocked mutex (or by a wrong thread) (/usr/bin/clickhouse+0x923a72e) (BuildId: 72f335c68b9c2bb72e029ff6e6216f76b7c5d5bd) in pthread_mutex_unlock
E ==================
```

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by alexey-milovidov**
> The `DataValidationTasks` struct stored a `std::unique_lock<std::mutex>` holding a lock on `BackgroundSchedulePoolTaskInfo::exec_mutex`. This caused a ThreadSanitizer warning because:

> 1. Thread A acquires the lock via `pausePartsCheck()` -> `getExecLock()`
> 2. `DataValidationTasks` is stored in a `shared_ptr` and copied to worker threads during parallel CHECK TABLE execution (via `TableCheckTask`)
> 3. When the last reference is destroyed (potentially on Thread B), the `unique_lock` destructor tries to unlock the mutex
> 4. pthread mutexes must be unlocked by the same thread that locked them, causing the TSan error "unlock of an unlocked mutex (or by a wrong thread)"

> The fix replaces `pausePartsCheck()` (which returned a `unique_lock`) with `temporaryPause()` which returns a new `TemporaryPause` RAII guard. This guard uses `deactivate()` to pause the background task and `activateAndSchedule()` in its destructor to resume it. Both operations are thread-safe and can be called from any thread, eliminating the thread-affinity issue.

> Changes:
> - Add `getTaskInfoPtr()` to `BackgroundSchedulePoolTaskHolder`
> - Add `TemporaryPause` class to `ReplicatedMergeTreePartCheckThread`
> - Remove `pausePartsCheck()` and replace all usages with `temporaryPause()`
> - Update `DataValidationTasks` to use `TemporaryPause` instead of `unique_lock`

Fixes #87916

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Version info
- Merged into: `26.1.1.663`

### CODE REVIEW

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp [hunk 1]
```diff
@@ -77,10 +77,28 @@ void ReplicatedMergeTreePartCheckThread::enqueuePart(const String & name, time_t
     task->schedule();
 }
 
-std::unique_lock<std::mutex> ReplicatedMergeTreePartCheckThread::pausePartsCheck()
+ReplicatedMergeTreePartCheckThread::TemporaryPause::TemporaryPause(BackgroundSchedulePoolTaskInfoPtr task_)
+    : task(std::move(task_))
 {
-    /// Wait for running tasks to finish and temporarily stop checking
-    return task->getExecLock();
```
Comment (azat) [inline src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp]: We could mark `getExecLock` as private then

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp [hunk 2]
```diff
@@ -77,10 +77,28 @@ void ReplicatedMergeTreePartCheckThread::enqueuePart(const String & name, time_t
...
+    if (task)
+        task->activateAndSchedule();
+}
+
+ReplicatedMergeTreePartCheckThread::TemporaryPause ReplicatedMergeTreePartCheckThread::temporaryPause()
+{
+    /// deactivate() waits for any running task execution to finish
+    /// and prevents new executions from starting.
+    /// This is safe to call from any thread.
+    task->deactivate();
```
Comment (antonio2368) [inline src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:98]: I don't think this is same and works as intendend.
`ReplicatedMergeTreePartCheckThread::run` calls `task->schedule` which will instantly add the task again before releasing the `exec_mutex`.

https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/BackgroundSchedulePool.cpp#L213

This is causing [issues in CI](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=480847b303815c820a149b63711820069a2921c5&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%2C%20sequential%29&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%2C%20sequential%29).

Comment (antonio2368) [reply src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:98]: Seems like it does check for `deactivated` before proceeding with execution of function 🤔

Comment (antonio2368) [reply src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:98]: Okay, I think I figured it out.
If we have 2 threads executing DROP_RANGE, it will activate the task when it finishes, even though the second DROP_RANGE still didn't finish.
