### PR TITLE
Fix transfer query to MySQL compatible query

### LINKED ISSUE #52654: error when select from postgresql() where 1=1 and (id=id)
CH 22.8.12.45

When trying to query postgresql function with condition WHERE 1=1 and (id=id) (generated query) ch generates query with wrong syntax for postgres.

Any query to postgres:
```sql
select * from postgresql(...)
where 1=1 and id=id 

```

Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: pqxx::sql_error: ERROR:  argument of AND must be type boolean, not type integer
LINE 1: ...column" FROM "table" WHERE 1 AND ("id...

It's same issue as #33152 but when condition (which ch can not optimize) added provided fix is not working

### LINKED ISSUE #56729: clickhouse adapts to postgresql
When I use the ch table and the table imported by the PostgreSql table (pg_algo_input_customer) engine as views, I filter the fields in pg_algo_input_customer. Clickhouse embedded the condition in the pg_algo_input_customer table sql as where 1, but the syntax of where 1 is not supported in pgsql, how do I make this view sql valid using the pg table engine?

The sql statement：
       select date, customer, level
       from pg_algo_input_customer
       where level != 'ZZ'.

The view contains the 'level' above, And when i used 'level' column, ch embeds 'and 1' into sql: WHERE ("level" != 'ZZ') AND 1), then throw this error 'std::exception. Code: 1001, type: pqxx::sql_error, e.what() = ERROR: argument of AND must be type boolean, not type integer'.
image

```[tasklist]
### Tasks
```

### LINKED ISSUE #57253: _shard_num bug fix
Create a table based on engine PostgreSQL like this 

```
'CREATE TABLE IF NOT EXISTS xxx
(
xxxx
) ENGINE = PostgreSQL(own_pg, table='xxx');'
```
When I exec this sql , it will be transfered like below:
Clickhouse : 
```
SELECT * FROM proxy.sys_nic WHERE  mode !=100 and type=0 and name!='' and _shard_num in (1) ORDER BY _shard_num,name LIMIT 20;
```
Postgres receive:
 ```
SELECT "id", "type", "mode", "state", "name", "nick_name", "description", "speed", "mac", "pci_no", "exist", "create_by", "create_time", "update_by", "update_time" 
 FROM "sys_nic" WHERE ("mode" != 100) AND ("type" = 0) AND 1
```
So, Postgres will report a error :  The argument to AND must be of type boolean, not of type integer,because of  PG can't recognize **and 1**

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix transfer query to MySQL compatible query. Fixes #57253. Fixes #52654. Fixes #56729.

For example, we have query 
```sql
SELECT
toDate(toDateTime('2023-11-0) AS day_,
toDateTime('2023-11-08 10:00) AS hour_,
k1  t
where  (day_ = toDate(toDateTime('2023-11-08 10:00:00'))) AND 
 (hour_ = toDateTime('2023-11-08 10:00:00'))  and k1 > 1;
```
After replace constant, it become:
```sql
SELECT
toDate(toDateTime('2023-11-0) AS day_,
toDateTime('2023-11-08 10:00) AS hour_,
k1  t
where  1 and 1 and k1 > 1;
```

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 399d61b222b2a9b9a082569a2dc29c64c8a14c87 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56456/399d61b222b2a9b9a082569a2dc29c64c8a14c87/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6797655050">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56456/399d61b222b2a9b9a082569a2dc29c64c8a14c87/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Storages/transformQueryForExternalDatabase.cpp [hunk 1]
```diff
@@ -288,6 +315,10 @@ String transformQueryForExternalDatabaseImpl(
     {
         replaceConstantExpressions(original_where, context, available_columns);
 
+        /// Replace like WHERE 1 AND 1 to WHRE 1 = 1 AND 1 = 1
```
Comment (CheSema) [inline src/Storages/transformQueryForExternalDatabase.cpp:318]:
```suggestion
        /// Replace like WHERE 1 AND 1 to WHERE 1 = 1 AND 1 = 1
```
