### PR TITLE
fixing multiple joins with using and join_use_nulls

### LINKED ISSUE #92173: Wrong type with multiple joins with using and join_use_nulls
### Company or project name

_No response_

### Describe what's wrong

Issue reproduced when queries from `03716_multiple_joins_using_top_level_identifier` run with `join_use_nulls`

### Does it reproduce on the most recent release?

Yes

### How to reproduce

See `03716_multiple_joins_using_top_level_identifier`

Basically root-cause related to that fact that we resolve `t2.id` differently when we have one and two joins:

https://fiddle.clickhouse.com/2045e8da-2c59-416a-a96b-f722ecb2afe5

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
* Fix logical error for queries with multiple JOINs with `USING` clause and `join_use_nulls`.

Close [#92173](https://github.com/ClickHouse/ClickHouse/issues/92173)

### CODE REVIEW

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 1]
```diff
@@ -3086,11 +3081,19 @@ ProjectionNames QueryAnalyzer::resolveSortNodeList(QueryTreeNodePtr & sort_node_
...
 
-        if (auto * sort_column_list_node = sort_node.getExpression()->as<ListNode>())
+        sort_expression_projection_names = resolveExpressionNode(sort_expression, scope, false /*allow_lambda_expression*/, false /*allow_table_expression*/);
+
+        if (auto * sort_column_list_node = sort_expression->as<ListNode>())
         {
             size_t sort_column_list_node_size = sort_column_list_node->getNodes().size();
+            if (sort_column_list_node_size != 1 && is_order_by_asterisk)
+            {
+                throw Exception(ErrorCodes::NOT_IMPLEMENTED, "Expression ORDER BY {} is not supported, matcher expression can only contain single column",
```
Comment (vdimir) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:3094]: Not related to the fix, just came across unclear error message and improved it

**Review by Avogar — APPROVED** [review]
