### PR TITLE
Prevent dictionary's ACL bypass via dictionary() table function

### LINKED ISSUE #54962: non-granted dictionary can be accessed through table function
## Problem
**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

A user with `CREATE TEMPORARY TABLE ON *.*` can read any dictionary. Even those which will raise `ACCESS_DENIED` when accesses through `dictGet`

##  Steps to reproduce
Clickhouse version `23.8.2`
As `admin` user
```
CREATE DICTIONARY dict
(
    id UInt64,
    value String
)
PRIMARY KEY id
SOURCE(NULL())
LAYOUT(FLAT())
LIFETIME(MIN 0 MAX 1000);

CREATE USER user NOT IDENTIFIED;
grant CREATE TEMPORARY TABLE ON *.* to user;
```
As user `user`
```
select dictGet(dict, 'value', 1); // ACCESS_DENIED
select * from dictionary(dict); // OK
```

## Expected behavior
The same access checks should apply for select `dictGet` and `select * from dictionary`

### PR DESCRIPTION
**Pull request by aiven-sal**
Close #54962

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
dictGet permission now also regulate dictionaries access via dictionary() table function

### CODE REVIEW

File: src/TableFunctions/TableFunctionDictionary.cpp [hunk 1]
```diff
@@ -78,6 +80,7 @@ ColumnsDescription TableFunctionDictionary::getActualTableStructure(ContextPtr c
 StoragePtr TableFunctionDictionary::executeImpl(
     const ASTPtr &, ContextPtr context, const std::string & table_name, ColumnsDescription, bool is_insert_query) const
 {
+    context->checkAccess(AccessType::dictGet, getDatabaseName(), table_name);
```
Comment (vitlibar) [inline src/TableFunctions/TableFunctionDictionary.cpp:83]: Could you please add a simple test for that?

**Review by vitlibar — APPROVED** [review]
