### PR TITLE
Fix error in parseDateTimeBestEffort

### LINKED ISSUE #13362: parseDateTime64BestEffort can not parse timestamp correct
(you don't have to strictly follow this form)

i use parseDateTime64BestEffort function to parse string to datetime.
i have met a stranger situation.
when i use : 
```
select parseDateTime64BestEffortOrNull('1596538462') from test_file_1_tmp limit 1;
```
result:
```
 2020-08-04 18:55:26.000
```
when i use ：
```
select parseDateTime64BestEffortOrNull(time) , time from test_file_1_tmp ;
```
result:
```
│               2020-07-18 10:00:00.000 │ 2020-07-18 10:00    │
│               2020-01-01 00:00:00.000 │ 2020                │
│               2020-08-01 00:00:00.000 │ 202008              │
│               2020-09-01 00:00:00.000 │ 2020-09             │
│               2020-10-01 00:00:00.000 │ 2020/10             │
│               2020-11-01 00:00:00.000 │ 20201101            │
│               2020-12-01 00:00:00.000 │ 2020-12-01          │
│               2020-02-01 00:00:00.000 │ 2020/02/01          │
│                                  ᴺᵁᴸᴸ │ 202003012200        │
│               2020-07-28 22:00:00.000 │ 2020/07/28 22:00    │
│               2020-04-01 22:00:55.000 │ 20200401220055      │
│               2020-07-28 22:00:22.000 │ 2020/07/28 22:00:22 │
│               2020-07-18 10:00:22.000 │ 2020-07-18 10:00:22 │
**│               2071-02-19 20:54:44.000 │ **1596538462**          │**
```

the function `parseDateTime64BestEffortOrNull` show different result in two querys.
how can i get the correct result of  `parseDateTime64BestEffortOrNull('1596538462')` ?

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix error in `parseDateTimeBestEffort` function when unix timestamp was passed as an argument. This fixes #13362.

### CODE REVIEW

File: src/IO/parseDateTimeBestEffort.cpp [hunk 1]
```diff
@@ -104,6 +104,7 @@ ReturnType parseDateTimeBestEffortImpl(
             return false;
     };
 
+    res = 0;
```
Comment (alexey-milovidov) [inline src/IO/parseDateTimeBestEffort.cpp:107]: The only relevant line.

File: src/Common/BitHelpers.h [hunk 2]
```diff
@@ -11,6 +12,7 @@
   */
 inline unsigned int bitScanReverse(unsigned int x)
 {
+    assert(x != 0);
```
Comment (alexey-milovidov) [inline src/Common/BitHelpers.h:15]: This is unrelated.
