### PR TITLE
Fix analyzer: fix miltiIf short circuit with constant arguments

### LINKED ISSUE #72714: Short circuit evaluation doesn't work with constant arguments
**Describe what's wrong**

```sql
WITH test AS (SELECT 0 AS number) SELECT if(number = 0, 0, intDiv(100, number)) FROM test

Received exception from server (version 24.12.1):
Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Division by zero. (ILLEGAL_DIVISION)
```

```sql
WITH 0 AS n SELECT multiIf(n = 0, 0, intDiv(100, n))

Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Division by zero: In scope WITH 0 AS n SELECT multiIf(n = 0, 0, intDiv(100, n)). (ILLEGAL_DIVISION)
```

```sql
WITH 0 AS n SELECT if(n = 0, 0, intDiv(100, n))

   ┌─0─┐
1. │ 0 │
   └───┘
```

**Additional context**

It happens because of constant folding that doesn't respect short circuit functions in [analyzer](https://github.com/ClickHouse/ClickHouse/blob/2ecc690b9363b6964167826f177c5c290ccfc382/src/Analyzer/Resolve/QueryAnalyzer.cpp#L3508-L3525) and in [actions dag](https://github.com/ClickHouse/ClickHouse/blob/2ecc690b9363b6964167826f177c5c290ccfc382/src/Interpreters/ActionsDAG.cpp#L329-L345). Interesting that it works for function `if` in some cases because this this special case is [handled](https://github.com/ClickHouse/ClickHouse/blob/2ecc690b9363b6964167826f177c5c290ccfc382/src/Analyzer/Resolve/QueryAnalyzer.cpp#L2822) in analyzer.

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `multiIf` with constant arguments and short-circuit evaluation. Closes #72714

### CODE REVIEW

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 1]
```diff
@@ -3776,7 +3883,16 @@ ProjectionNames QueryAnalyzer::resolveFunction(QueryTreeNodePtr & node, Identifi
                 size_t num_rows = 1;
                 if (!argument_columns.empty())
                     num_rows = argument_columns.front().column->size();
-                column = executable_function->execute(argument_columns, result_type, num_rows, true);
+
+                if (do_not_execute)
```
Comment (KochetovNicolai) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp]: disable_constant_folding

**Review by yariks5s — APPROVED** [review]

File: src/Analyzer/Resolve/resolveFunction.cpp [hunk 2]
```diff
@@ -1195,7 +1310,16 @@ ProjectionNames QueryAnalyzer::resolveFunction(QueryTreeNodePtr & node, Identifi
                 size_t num_rows = 1;
                 if (!argument_columns.empty())
                     num_rows = argument_columns.front().column->size();
-                column = executable_function->execute(argument_columns, result_type, num_rows, true);
+
+                if (disable_constant_folding)
+                {
+                    if (isNothing(result_type))
+                        column = ColumnConst::create(ColumnNothing::create(1), 1);
```
Comment (yariks5s) [inline src/Analyzer/Resolve/resolveFunction.cpp]: Should we do
```suggestion
                        column = ColumnConst::create(ColumnNothing::create(1), num_rows);
```

I'm not sure about it, just asking your opinion

File: src/Analyzer/Resolve/resolveFunction.cpp [hunk 3]
```diff
@@ -247,49 +249,162 @@ ProjectionNames QueryAnalyzer::resolveFunction(QueryTreeNodePtr & node, Identifi
...
+                        second_argument_projection_names[0];
+
+                    auto multi_if_function = std::make_shared<FunctionNode>("multiIf");
+                    for (size_t n = 2; n < if_function_arguments.size(); ++n)
+                        multi_if_function->getArguments().getNodes().push_back(std::move(if_function_arguments[n]));
+                    node = std::move(multi_if_function);
+                    auto result_projection_names = resolveFunction(node, scope);
+
+                    if (if_function_arguments[1]->getNodeType() != QueryTreeNodeType::IDENTIFIER &&
+                        node->getResultType()->equals(*if_function_arguments[1]->getResultType()))
```
Comment (yariks5s) [inline src/Analyzer/Resolve/resolveFunction.cpp]: Should it be like this?
```suggestion
                        !node->getResultType()->equals(*if_function_arguments[1]->getResultType()))
```

Comparing with l 348-349

File: src/Analyzer/Resolve/resolveFunction.cpp [hunk 4]
```diff
@@ -247,49 +249,162 @@ ProjectionNames QueryAnalyzer::resolveFunction(QueryTreeNodePtr & node, Identifi
...
-            }
+                disable_constant_folding = current_do_not_execute;
 
-            if (apply_constant_if_optimization)
-            {
-                auto result_projection_names = resolveExpressionNode(constant_if_result_node,
+                auto dead_branch_argument_projection_name =
+                    possibly_invalid_argument_node->getNodeType() == QueryTreeNodeType::IDENTIFIER ?
+                        possibly_invalid_argument_node->as<IdentifierNode>()->getIdentifier().getFullName() :
+                        dead_branch_argument_projection_names[0];
```
Comment (yariks5s) [inline src/Analyzer/Resolve/resolveFunction.cpp:317]: Looks like we can `resolveExpressionNode` only when the dead branch is not an Identifier?

Comment (yakov-olkhovskiy) [reply src/Analyzer/Resolve/resolveFunction.cpp:317]: we just propagate identifier because on previous step we turned off resolution with `disable_constant_folding = true` so identifier is not resolved

File: src/Analyzer/Resolve/resolveFunction.cpp (hunk 2 above)
Comment (yakov-olkhovskiy) [reply src/Analyzer/Resolve/resolveFunction.cpp]: yes

File: src/Analyzer/Resolve/resolveFunction.cpp (hunk 3 above)
Comment (yakov-olkhovskiy) [reply src/Analyzer/Resolve/resolveFunction.cpp]: yes

**Comment by Algunenano** [comment]
This PR introduced a crash () and many fuzzer reports: 

https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=5397c58d5a5a4fc68dfa6922b0ae6b29fcbc38d4&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_ubsan%29&name_1=AST%20fuzzer%20%28amd_ubsan%29
```
:) SELECT and(1, and(and(materialize(toLowCardinality(1)), 1, assumeNotNull(3)), 1, and(isNullable(3), assumeNotNull(3), 1)), isNullable(*), isNullable(toLowCardinality(3)), isNullable(NULL)), toTypeName(res), and(and(and(1, and(isNullable(3), 3, isNull(1), and(materialize(1), isNullable(toLowCardinality(toLowCardinality(3)))), 1), isNull(materialize(3))), 3), *, isNotNull(toNullable(1)), 1), if(0, toFixedString('str_1', number % 3, 5), [1, 2, 3]) AS res

SELECT
    and(1, and(and(materialize(toLowCardinality(1)), 1, assumeNotNull(3)), 1, and(isNullable(3), assumeNotNull(3), 1)), isNullable(*), isNullable(toLowCardinality(3)), isNullable(NULL)),
    toTypeName(res),
    and(and(and(1, and(isNullable(3), 3, isNull(1), and(materialize(1), isNullable(toLowCardinality(toLowCardinality(3)))), 1), isNull(materialize(3))), 3), *, isNotNull(toNullable(1)), 1),
    if(0, toFixedString('str_1', number % 3, 5), [1, 2, 3]) AS res

Query id: 91a5e416-dea4-45c7-a8d8-c5a4305ba5ac

2025.11.17 16:10:10.993769 [ 449945 ] {} <Trace> LOCAL-Session-a5a2b4d3-726c-412f-ac10-53a006ce8675: a5a2b4d3-726c-412f-ac10-53a006ce8675 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2025.11.17 16:10:10.993982 [ 449945 ] {91a5e416-dea4-45c7-a8d8-c5a4305ba5ac} <Debug> executeQuery: (from 0.0.0.0:0, user: ) (query 1, line 1) SELECT and(1, and(and(materialize(toLowCardinality(1)), 1, assumeNotNull(3)), 1, and(isNullable(3), assumeNotNull(3), 1)), isNullable(*), isNullable(toLowCardinality(3)), isNullable(NULL)), toTypeName(res), and(and(and(1, and(isNullable(3), 3, isNull(1), and(materialize(1), isNullable(toLowCardinality(toLowCardinality(3)))), 1), isNull(materialize(3))), 3), *, isNotNull(toNullable(1)), 1), if(0, toFixedString('str_1', number % 3, 5), [1, 2, 3]) AS res (stage: Complete)
2025.11.17 16:10:11.022058 [ 449945 ] {91a5e416-dea4-45c7-a8d8-c5a4305ba5ac} <Error> executeQuery: Code: 49. DB::Exception: Expression nodes list expected 1 projection names. Actual: 0. (LOGICAL_ERROR) (version 25.11.1.3094) (from 0.0.0.0:0) (query 1, line 1) (in query: SELECT and(1, and(and(materialize(toLowCardinality(1)), 1, assumeNotNull(3)), 1, and(isNullable(3), assumeNotNull(3), 1)), isNullable(*), isNullable(toLowCardinality(3)), isNullable(NULL)), toTypeName(res), and(and(and(1, and(isNullable(3), 3, isNull(1), and(materialize(1), isNullable(toLowCardinality(toLowCardinality(3)))), 1), isNull(materialize(3))), 3), *, isNotNull(toNullable(1)), 1), if(0, toFixedString('str_1', number % 3, 5), [1, 2, 3]) AS res), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013e2235f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c905a0e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c905400
3. DB::Exception::Exception<unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, unsigned long&, unsigned long&&) @ 0x000000000c939eeb
4. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46645
5. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e5dd5
6. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
7. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46040
8. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e5dd5
9. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
10. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e2129
11. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
12. DB::QueryAnalyzer::tryResolveIdentifierFromAliases(DB::IdentifierLookup const&, DB::IdentifierResolveScope&, DB::IdentifierResolveContext) @ 0x0000000017f53aff
13. DB::QueryAnalyzer::tryResolveIdentifier(DB::IdentifierLookup const&, DB::IdentifierResolveScope&, DB::IdentifierResolveContext) @ 0x0000000017f55443
14. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f471dc
15. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46040
16. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e5dd5
17. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
18. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46040
19. DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x0000000017f6bca7
20. DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x0000000017f3c54e
21. DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x0000000017f39d6a
22. DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x0000000017f393a4
23. DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>&) @ 0x0000000017f905a3
24. DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) (.llvm.3622051785615563015) @ 0x0000000018aeffbb
25. DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000018aedeaa
26. std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__function::__policy_func<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_func[abi:ne210105]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0>(std::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) (.llvm.3622051785615563015) @ 0x0000000018af1522
27. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000018a6223c
28. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x0000000018eba8b3
29. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018eb4e73
30. DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool, std::vector<String, std::allocator<String>> const&, std::function<void (DB::Progress const&)>) @ 0x000000001a4bb683
31. DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001a432694

2025.11.17 16:10:11.022174 [ 449945 ] {91a5e416-dea4-45c7-a8d8-c5a4305ba5ac} <Error> ForcedCriticalErrorsLogger: Code: 49. DB::Exception: Expression nodes list expected 1 projection names. Actual: 0. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013e2235f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c905a0e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c905400
3. DB::Exception::Exception<unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, unsigned long&, unsigned long&&) @ 0x000000000c939eeb
4. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46645
5. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e5dd5
6. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
7. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46040
8. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e5dd5
9. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
10. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e2129
11. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
12. DB::QueryAnalyzer::tryResolveIdentifierFromAliases(DB::IdentifierLookup const&, DB::IdentifierResolveScope&, DB::IdentifierResolveContext) @ 0x0000000017f53aff
13. DB::QueryAnalyzer::tryResolveIdentifier(DB::IdentifierLookup const&, DB::IdentifierResolveScope&, DB::IdentifierResolveContext) @ 0x0000000017f55443
14. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f471dc
15. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46040
16. DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000181e5dd5
17. DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x0000000017f46b80
18. DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x0000000017f46040
19. DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x0000000017f6bca7
20. DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x0000000017f3c54e
21. DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x0000000017f39d6a
22. DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x0000000017f393a4
23. DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>&) @ 0x0000000017f905a3
24. DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) (.llvm.3622051785615563015) @ 0x0000000018aeffbb
25. DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000018aedeaa
26. std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__function::__policy_func<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_func[abi:ne210105]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0>(std::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) (.llvm.3622051785615563015) @ 0x0000000018af1522
27. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000018a6223c
28. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x0000000018eba8b3
29. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018eb4e73
30. DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool, std::vector<String, std::allocator<String>> const&, std::function<void (DB::Progress const&)>) @ 0x000000001a4bb683
31. DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001a432694


Elapsed: 0.029 sec. 

Received exception:
Code: 49. DB::Exception: Expression nodes list expected 1 projection names. Actual: 0. (LOGICAL_ERROR)
```
