### PR TITLE
Fix: logical error in grace hash join

### LINKED ISSUE #51703: Logical error: 'Broken buckets. its size(5) is not power of 2'.
https://s3.amazonaws.com/clickhouse-test-reports/0/a8e0dbf1d32b23cb4f6a81dbcf6dede35316d183/stress_test__tsan_.html

```
 [ 23523 ] {1287f52a-b279-4ca0-ac8f-6770b18db8ca} <Fatal> : Logical error: \'Broken buckets. its size(5) is not power of 2\'.
 [ 27219 ] {} <Fatal> BaseDaemon: ########################################
 [ 27219 ] {} <Fatal> BaseDaemon: (version 23.7.1.1 (official build), build id: C4C042E1BA38FC371C46B8D905A87E5EBA49DCCB, git hash: a8e0dbf1d32b23cb4f6a81dbcf6dede35316d183) (from thread 23523) (query_id: 1287f52a-b279-4ca0-ac8f-6770b18db8ca) (query: SELECT t1.key, t2.key, t1.s, empty(t2.s) FROM t1
 [ 27219 ] {} <Fatal> BaseDaemon: 
 [ 27219 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f3c43352a7c 0x00007f3c432fe476 0x00007f3c432e47f3 0x000055d6fb57f8a3 0x000055d70394f689 0x000055d70394ff60 0x000055d6fd3b0c6d 0x000055d70cb0c32d 0x000055d70cb0a829 0x000055d70efc458d 0x000055d70ec7c472 0x000055d70ec6f27f 0x000055d70ec70271 0x0000
 [ 27219 ] {} <Fatal> BaseDaemon: 5. pthread_kill @ 0x00007f3c43352a7c in ?
 [ 27219 ] {} <Fatal> BaseDaemon: 6. raise @ 0x00007f3c432fe476 in ?
 [ 27219 ] {} <Fatal> BaseDaemon: 7. abort @ 0x00007f3c432e47f3 in ?
 [ 27219 ] {} <Fatal> BaseDaemon: 8. abort @ 0x000000000dcd48a3 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Common/Exception.cpp:0: DB::abortOnFailedAssertion(String const&) @ 0x00000000160a4689 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/./src/Common/Exception.cpp:66: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
 [ 27219 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000160a4f60 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 11. DB::Exception::Exception<unsigned long>(int, FormatStringHelperImpl<std::type_identity<unsigned long>::type>, unsigned long&&) @ 0x000000000fb05c6d in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Interpreters/GraceHashJoin.cpp:644: DB::GraceHashJoin::addJoinedBlockImpl(DB::Block) @ 0x000000001f26132d in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Interpreters/GraceHashJoin.cpp:0: DB::GraceHashJoin::addJoinedBlock(DB::Block const&, bool) @ 0x000000001f25f829 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Processors/Transforms/JoiningTransform.cpp:308: DB::FillingRightJoinSideTransform::work() @ 0x000000002171958d in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/list:588: std::__list_imp<DB::ExecutingGraph::Edge, std::allocator<DB::ExecutingGraph::Edge>>::__sz[abi:v15000]() const
 [ 27219 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/list:616: std::__list_imp<DB::ExecutingGraph::Edge, std::allocator<DB::ExecutingGraph::Edge>>::empty[abi:v15000]() const
 [ 27219 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/list:918: std::list<DB::ExecutingGraph::Edge, std::allocator<DB::ExecutingGraph::Edge>>::empty[abi:v15000]() const
 [ 27219 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
 [ 27219 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x00000000213d1472 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000213c427f in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:351: operator()
 [ 27219 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spaw
 [ 27219 ] {} <Fatal> BaseDaemon: 17.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
 [ 27219 ] {} <Fatal> BaseDaemon: 17.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]()
 [ 27219 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_st
 [ 27219 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 27219 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 27219 ] {} <Fatal> BaseDaemon: 18.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 27219 ] {} <Fatal> BaseDaemon: 18.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 27219 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Common/ThreadPool.cpp:429: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x00000000161cccd2 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::\'lambda0\'()>(v
 [ 27219 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:717: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<Thr
 [ 27219 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 27219 ] {} <Fatal> BaseDaemon: 21.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 27219 ] {} <Fatal> BaseDaemon: 21.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 27219 ] {} <Fatal> BaseDaemon: 21.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 27219 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./src/Common/ThreadPool.cpp:429: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x00000000161c89c7 in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 22.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
 [ 27219 ] {} <Fatal> BaseDaemon: 22.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 27219 ] {} <Fatal> BaseDaemon: 22.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
 [ 27219 ] {} <Fatal> BaseDaemon: 22.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
 [ 27219 ] {} <Fatal> BaseDaemon: 22.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(st
 [ 27219 ] {} <Fatal> BaseDaemon: 22.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::
 [ 27219 ] {} <Fatal> BaseDaemon: 22.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 27219 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function
 [ 27219 ] {} <Fatal> BaseDaemon: 23. __tsan_thread_start_func @ 0x000000000dccddef in /usr/bin/clickhouse
 [ 27219 ] {} <Fatal> BaseDaemon: 24. ? @ 0x00007f3c43350b43 in ?
 [ 27219 ] {} <Fatal> BaseDaemon: 25. ? @ 0x00007f3c433e2a00 in ?
 [ 27219 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: CA682D1A7B965E8377C92CB5C2D42A27)
 [ 1713 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/51703

Root cause: number of buckets could become inconsistent if exception was thrown during new buckets creation

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by zhanglistar** [comment]
Check this, already fixed. https://github.com/ClickHouse/ClickHouse/pull/51382

**Comment by lgbo-ustc** [comment]
This exception is expected.  There is a certain probalitiy memory allocate failured under stress tests. This make the buckets rehashing fail, and remain the buckets vector in a invalid size.

**Comment by lgbo-ustc** [comment]
@devcrafter I think rewirte `rehashBuckets` may be better. Add the new buckets into `GraceHashJoin::buckets` only when all of them are created.

**Comment by devcrafter** [comment]
> @devcrafter I think rewirte `rehashBuckets` may be better. Add the new buckets into `GraceHashJoin::buckets` only when all of them are created.
> 
> And we will see the memory allocate exception instead of the invalid bucket size exception. it's more clear.

Thanks for suggestion. Yes, it's a much more clear approach. Done in [30be0ab](https://github.com/ClickHouse/ClickHouse/pull/51737/commits/30be0ab4a8af7247a12c94076cd17834f712b9d9)

File: src/Interpreters/GraceHashJoin.cpp [hunk 1]
```diff
@@ -356,52 +353,66 @@ bool GraceHashJoin::hasMemoryOverflow(const InMemoryJoinPtr & hash_join_) const
...
 {
-    // There could be exceptions from createStream, In ci tests
-    // there is a certain probability of failure in allocating memory, see memory_tracker_fault_probability.
-    // It may terminate this thread and leave a broken hash_join, and another thread cores when it tries to
-    // use the broken hash_join. So we print an exception message here to help debug.
-    try
-    {
-        auto & left_file = tmp_data->createStream(left_sample_block);
-        auto & right_file = tmp_data->createStream(prepareRightBlock(right_sample_block));
+    // Exception can be thrown in number of cases:
```
Comment (vdimir) [inline src/Interpreters/GraceHashJoin.cpp:385]: If an exception is thrown, won't the query be cancelled? Do we see an inconsistent state of `buckets` because of another thread accessing it when the exception has already been thrown (and the mutex released), but before the query was cancelled?

Comment (devcrafter) [reply src/Interpreters/GraceHashJoin.cpp:385]: Yes, that's what I see if intentionally add exception in `addBuckets()` while creating new buckets

Comment (devcrafter) [reply src/Interpreters/GraceHashJoin.cpp:385]: Expanded part of `02273_full_sort_join.sql.j2` for grace join:
https://pastila.nl/?00b6056d/cde7c624db96e692a69ef05cc0132f95

Traces for grace hash join with an intentionally added exception when trying to create 5th bucket:
https://pastila.nl/?022538cf/c96e4cb05f99476123270f2ccad3fcdf

Intentionally added exception in log:
```
... <Error> GraceHashJoin: Can't create bucket 4 due to error: Code: 290. DB::Exception: Too many buckets. (LIMIT_EXCEEDED) (version 23.7.1.1)
2
````

Comment (lgbo-ustc) [reply src/Interpreters/GraceHashJoin.cpp:385]: The exception is catch and thrown in `PipelineExecutor` asynchronously. I think before the exception is really throw out, other threads still have chance to run and trigger this exception.

File: src/Interpreters/GraceHashJoin.cpp [hunk 2]
```diff
@@ -356,52 +353,66 @@ bool GraceHashJoin::hasMemoryOverflow(const InMemoryJoinPtr & hash_join_) const
...
-    {
-        LOG_ERROR(&Poco::Logger::get("GraceHashJoin"), "Can't create bucket. current buckets size: {}", destination.size());
-        throw;
-    }
+            BucketPtr new_bucket = std::make_shared<FileBucket>(current_size + i, left_file, right_file, log);
+            tmp_buckets.emplace_back(std::move(new_bucket));
+        }
+        catch (...)
+        {
+            LOG_ERROR(
```
Comment (vdimir) [inline src/Interpreters/GraceHashJoin.cpp:405]: Do we need this log? The exception raised by `throw;` below should reach the user and we will see it.

**Review by vdimir — APPROVED** [review]

File: src/Interpreters/GraceHashJoin.cpp (hunk 2 above)
Comment (devcrafter) [reply src/Interpreters/GraceHashJoin.cpp:405]: I guess a couple of points:
(1) The exception will not contain the context of the error in an explicit way (can't create bucket), only implicitly as part of callstack.
(2) Without this logging, the log will contain only one exception. But with it, the log will contain all of them, which provide additional information that it happened in different threads.
