### PR TITLE
Fix multiple issues with arrayMin and arrayMax

### LINKED ISSUE #68895: LOGICAL_ERROR: `Unexpected return type from arrayMax`
```
select arrayMax(x -> toFixedString('.', 1), [])

SELECT arrayMax(x -> toFixedString('.', 1), [])

Query id: 8b6b02e5-7598-46aa-afe6-da68ae9fce69

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.9.1.


Elapsed: 0.075 sec. 

Received exception from server (version 24.9.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected return type from arrayMax. Expected FixedString(1). Got Nothing. Action:
FUNCTION arrayMax(x Nothing -> _CAST('.'_FixedString(1), 'FixedString(1)'_String) :: 3, _CAST([]_Array(Nothing), 'Array(Nothing)'_String) :: 2) -> arrayMax(x Nothing -> _CAST('.'_FixedString(1), 'FixedString(1)'_String), _CAST([]_Array(Nothing), 'Array(Nothing)'_String)) FixedString(1) : 1,
input block structure:x Nothing -> _CAST('.'_FixedString(1), 'FixedString(1)'_String) Function(Nothing -> FixedString(1)) Function(size = 1), _CAST([]_Array(Nothing), 'Array(Nothing)'_String) Array(Nothing) Const(size = 1, Array(size = 1, UInt64(size = 1), Nothing(size = 0))): while executing 'FUNCTION arrayMax(x Nothing -> _CAST('.'_FixedString(1), 'FixedString(1)'_String) :: 3, _CAST([]_Array(Nothing), 'Array(Nothing)'_String) :: 2) -> arrayMax(x Nothing -> _CAST('.'_FixedString(1), 'FixedString(1)'_String), _CAST([]_Array(Nothing), 'Array(Nothing)'_String)) FixedString(1) : 1'. (LOGICAL_ERROR)

```

https://s3.amazonaws.com/clickhouse-test-reports/68744/0e136ded28dc1191dd344500d031f43d7a5750e2/ast_fuzzer__ubsan_.html

### LINKED ISSUE #69600: arrayMax / arrayMin with a function parameter not working anymore
ClickHouse 24.8.2.3

Examples
========

This taken from the documentation:

```
SELECT arrayMax(x -> (-x), [1, 2, 4]) AS res;
```

returns the error:

```
Code: 49. DB::Exception: Unexpected return type from arrayMax. Expected Int16. Got UInt8. Action: FUNCTION arrayMax(__lambda :: 1, [1, 2, 4] :: 0) -> arrayMax(lambda(tuple(x), negate(x)), [1, 2, 4]) Int16 : 3, input block structure:__lambda Function(UInt8 -> Int16) Function(size = 1), [1, 2, 4] Array(UInt8) Const(size = 1, Array(size = 1, UInt64(size = 1), UInt8(size = 3))): while executing 'FUNCTION arrayMax(__lambda :: 1, [1, 2, 4] :: 0) -> arrayMax(lambda(tuple(x), negate(x)), [1, 2, 4]) Int16 : 3'. (LOGICAL_ERROR) (version 24.8.2.3 (official build)) 
```
But the error persists event with this:
```
SELECT arrayMax(x -> toUInt16(-x), [1, 2, 4]) AS res;
```

This other that used to work too:
```
select arrayMax(x -> x.1, [(1, 'a'), (0, 'b')])
```

now fails with

```
Code: 49. DB::Exception: Unexpected return type from arrayMax. Expected UInt8. Got Tuple(UInt8, String).
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix multiple issues with arrayMin and arrayMax

Closes https://github.com/ClickHouse/ClickHouse/issues/68895
Closes https://github.com/ClickHouse/ClickHouse/issues/69600
Also fixes some other crashes that were detected in https://github.com/ClickHouse/ClickHouse/pull/69640
References https://github.com/ClickHouse/ClickHouse/pull/65455 (removes that code completely, which was extremely buggy and out of place)
Affects / to be backported to 24.7+ only 
Note that the code is pretty similar to what we do for max/min/argMax/argMin to calculate the index of the smallest/largest value.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit a2c79e069009f6bbfb2228df0264fd3df97daffe with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70207/a2c79e069009f6bbfb2228df0264fd3df97daffe/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70160/2f4518fa66d4baa425fa6ef8479cb8f6debb369d/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Functions/array/arrayAggregation.cpp [hunk 1]
```diff
@@ -152,9 +152,77 @@ struct ArrayAggregateImpl
         return result;
     }
 
+    template <AggregateOperation op = aggregate_operation>
+    requires(op == AggregateOperation::min || op == AggregateOperation::max)
+    static bool executeMinOrMax(const ColumnPtr & mapped, const ColumnArray::Offsets & offsets, ColumnPtr & res_ptr)
```
Comment (nickitat) [inline src/Functions/array/arrayAggregation.cpp:157]: we never return false

File: src/Functions/array/arrayAggregation.cpp [hunk 2]
```diff
@@ -360,74 +409,41 @@ struct ArrayAggregateImpl
...
+                executeType<Decimal64>(mapped, offsets, res) ||
+                executeType<Decimal128>(mapped, offsets, res) ||
+                executeType<Decimal256>(mapped, offsets, res) ||
+                executeType<DateTime64>(mapped, offsets, res))
+            {
+                return res;
+            }
+        }
+
+        throw Exception(ErrorCodes::ILLEGAL_COLUMN, "Unexpected column for arraySum: {}", mapped->getName());
```
Comment (nickitat) [inline src/Functions/array/arrayAggregation.cpp:446]: judging by `AggregateOperation` enumerators it doesn't have to be `sum`

File: src/Functions/array/arrayAggregation.cpp [hunk 3]
```diff
@@ -152,9 +152,77 @@ struct ArrayAggregateImpl
...
+            res_ptr = std::move(res_column);
+            return true;
+        }
+
+        MutableColumnPtr res_column = mapped->cloneEmpty();
+        static constexpr int nan_null_direction_hint = aggregate_operation == AggregateOperation::min ? 1 : -1;
+
+        if (offsets.size() == 1 && offsets[0] != 0)
+        {
+            /// Fast path: Use permutation (which in some cases is optimized) to find the extreme value
```
Comment (nickitat) [inline src/Functions/array/arrayAggregation.cpp:173]: will we still have o(arr_size) in cases where it is not optimised?

File: src/Functions/array/arrayAggregation.cpp (hunk 2 above)
Comment (Algunenano) [reply src/Functions/array/arrayAggregation.cpp:446]: Yes, it's broken and incorrect, but fixing it would require 10+ changes and makes it impossible to backport the fix.

File: src/Functions/array/arrayAggregation.cpp (hunk 3 above)
Comment (Algunenano) [reply src/Functions/array/arrayAggregation.cpp:173]: Yes, but that was still the case (it didn't get worse).

I could implement a similar approach as `executeType` done for the other functions but that a) requires declaring all optimizable types and a default implementation (such as this) with b) many templates and compilation time and c) I'd rather implement it in the permutation itself (accept begin and end) as it'd help improving many other cases, like min/max/argMin/argMax, etc where we have the same issue (for sparse columns for example).

Maybe it makes sense to remove the fast path for now, but it also helps as a reminder of a possible optimization.

File: src/Functions/array/arrayAggregation.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Functions/array/arrayAggregation.cpp:157]: +1 Initially I thought there was some cases where it might be impossible to implement it, but since all types implement getPermutation and compareAt it never fails AFAICT. It's the same as `ORDER BY column::{type}`. I'll change it

File: src/Functions/array/arrayAggregation.cpp (hunk 3 above)
Comment (nickitat) [reply src/Functions/array/arrayAggregation.cpp:173]: i don't quite understand how. get permutation should be nlogn in general case.

Comment (Algunenano) [reply src/Functions/array/arrayAggregation.cpp:173]: Yes, but it can be o(n) when limit is 1. And it can be implemented with avx2:

https://github.com/ClickHouse/ClickHouse/blob/c15699e32d1168f292eca290ed45ab1eaa137da9/src/Columns/ColumnVector.cpp#L227-L246

Maybe I should just introduce a `getMinIndex(start, end)` for columns and use that instead (in another PR). I'll remove the code for now and leave it permutation-less for now

**Review by nickitat — APPROVED** [review]
