### PR TITLE
Fix prewhere in MaterializeMySQL

### LINKED ISSUE #22432: Ошибка ClickHouse Code: 10, e.displayText() = DB::Exception: Not found column equals(catalog_id, 1041) in block
Имеется Materialized база, данные реплицируюся нормально, в базе данные есть

Если выполнить запрос

```
SELECT 
    DISTINCT P.id, 
    P.name, 
    P.catalog_id
FROM products P 
WHERE 
    P.name ILIKE '%Легкие%'
```

То получим результат:

`   |name                                                                                                |catalog_id|brand_id|
---|----------------------------------------------------------------------------------------------------|----------|--------|
915|Подвеска "Легкие"                                                                                   |      5287|   15837|
990|Кроссовки/Кроссовки текстильные/Кроссовки женские летние/кроссовки легкие/Кроссовки спортивные      |      1053|   24390|
781|Брюки женские / Брюки прямые / Легкие брюки на резинке                                              |      1041|    1176|`

Но если в запрос добавить AND catalog_id = N

```
SELECT 
    DISTINCT P.id, 
    P.name, 
    P.catalog_id
FROM products P 
WHERE 
    P.name ILIKE '%Легкие%' AND P.catalog_id = 5287;
```

Или же так:

```
SELECT 
    DISTINCT P.id, 
    P.name, 
    P.catalog_id,
    P.brand_id 
FROM products P 
WHERE 
    P.catalog_id = 5287 AND P.brand_id = 15837;
```

То получаю ошибки

```
SQL Error [10]: ClickHouse exception, code: 10, Code: 10, e.displayText() = DB::Exception: Not found column equals(catalog_id, 5287) in block: while executing 'INPUT : 1 -> equals(catalog_id, 5287) UInt8 : 1' (version 21.3.4.25 (official build))
```

```
SQL Error [10]: ClickHouse exception, code: 10, Code: 10, e.displayText() = DB::Exception: Not found column equals(brand_id, 15837) in block: while executing 'INPUT : 0 -> equals(brand_id, 15837) UInt8 : 0' (version 21.3.4.25 (official build))
```

Почему так происходит? как выйти из этой ситуации?

Структура
```
CREATE TABLE analyzer.products
(

    `id` Int32,

    `product_id` Int32,

    `catalog_id` Int32,

    `brand_id` Int32,

    `name` Nullable(String),

    `description` Nullable(String),

    `supplier` Nullable(String),

    `marketplace` String,

    `letter` String,

    `isNew` UInt8,

    `isSoldOut` UInt8,

    `created` DateTime,

    `updated` DateTime,

    `_sign` Int8 MATERIALIZED 1,

    `_version` UInt64 MATERIALIZED 1
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY intDiv(id,
 4294967)
ORDER BY (product_id,
 catalog_id,
 brand_id,
 letter,
 updated,
 id)
SETTINGS index_granularity = 8192
```

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `Not found column` error when selecting from `MaterializeMySQL` with condition on key column.
Fixes #22432

Detailed description / Documentation draft:
Also fixes `Can't connect to MySQL server` error on `MaterializeMySQL` creation due to incorrect parsing of host and port

### CODE REVIEW

**Comment by tavplubix** [comment]
AST fuzzer (MSan) - `==43==ERROR: MemorySanitizer: allocator is out of memory trying to allocate 0x2000 bytes`
Functional stateless tests (thread) - race in ZlibDeflatingWriteBuffer, already fixed in master
Integration tests - test_storage_hdfs - unrelated
SQLancer test - looks like #23029
Yandex synchronization check - was broken in master

File: src/Storages/StorageMaterializeMySQL.cpp [hunk 1]
```diff
@@ -92,7 +92,7 @@ Pipe StorageMaterializeMySQL::read(
     {
         Block pipe_header = pipe.getHeader();
         auto syntax = TreeRewriter(context).analyze(expressions, pipe_header.getNamesAndTypesList());
-        ExpressionActionsPtr expression_actions = ExpressionAnalyzer(expressions, syntax, context).getActions(true);
+        ExpressionActionsPtr expression_actions = ExpressionAnalyzer(expressions, syntax, context).getActions(true, false);
```
Comment (akuzm) [inline src/Storages/StorageMaterializeMySQL.cpp:95]:
```suggestion
        ExpressionActionsPtr expression_actions = ExpressionAnalyzer(expressions, syntax, context).getActions(true /* add_aliases */, false /* project_result */);
```

Not that it becomes more clear, but at least the next level of unclear...

By the way, what would it mean for a filter transform to "project result"? Our use of "projection" is a misnomer, I think we use it to refer to a final rename of columns performed at some latest stage of query execution. Can FilterTransform do this rename as well?

**Review by akuzm — APPROVED** [review]

File: src/Storages/StorageMaterializeMySQL.cpp (hunk 1 above)
Comment (tavplubix) [reply src/Storages/StorageMaterializeMySQL.cpp:95]: AFAIK `project_result` means "leave only result columns of `expressions` in block, remove other columns (including columns with intermediate results of some subexpressions)". Since we added all required columns into `expressions`, we can expect that it will work fine with `project_result = true`. But `StorageMergeTree::read(require_columns_name, ...)` may return some extra columns for `PREWHERE` (for example, `equals(brand_id, 15837)` from the linked issue) even if nobody asks for such columns. Interpreter does not explicitly add these columns into `require_columns_name`, but expects that `read(...)` will understand somehow that it must returns special columns for `PREWHERE` in addition to required columns... 

Seems like it's not possible to make this code more clear without rewriting everything around `PREWHERE`.

**Comment by tavplubix** [comment]
ClickHouse build check - `Build failed without build log. It's inner CI problem.`
