### PR TITLE
Fix several `RENAME COLUMN` bugs.

### LINKED ISSUE #34342: Mutations may fail when coalesced together
**Describe what's wrong**

The following example should succeed. If merges are not stopped and each mutation is given opportunity to complete, then no errors arise. However, they fail when ClickHouse decides to coalesce them and run in a single task.

**How to reproduce**

```sql
CREATE TABLE t
(
    `v` DateTime,
    `v1` DateTime
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(v)
ORDER BY tuple()
SETTINGS min_bytes_for_wide_part = 0;

INSERT INTO t VALUES (1,1);
SYSTEM STOP MERGES;
ALTER TABLE t RENAME COLUMN v1 to v2; -- this blocks, start a new client/connection for the next query
ALTER TABLE t UPDATE v2 = 1 WHERE 1 = 1;
SYSTEM START MERGES;
```

```sql
SELECT *
FROM system.mutations

Query id: 3c225cd0-a5ba-4395-80e5-4a272446b5d2

┌─database─┬─table─┬─mutation_id────┬─command───────────────────┬─────────create_time─┬─block_numbers.partition_id─┬─block_numbers.number─┬─parts_to_do_names─┬─parts_to_do─┬─is_done─┬─latest_failed_part─┬────latest_fail_time─┬─latest_fail_reason─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ default  │ t     │ mutation_2.txt │ RENAME COLUMN v1 TO v2    │ 2022-02-05 21:19:11 │ ['']                       │ [2]                  │ ['197001_1_1_0']  │           1 │       0 │ 197001_1_1_0       │ 2022-02-05 21:19:23 │ Code: 246. DB::Exception: Bad size of marks file '/var/lib/clickhouse/store/366/3668606c-16fe-4e35-8a4e-3b2bd9def292/197001_1_1_0/v1.mrk2': 0, must be: 48: While executing MergeTreeInOrder. (CORRUPTED_DATA) (version 22.1.3.7 (official build)) │
│ default  │ t     │ mutation_3.txt │ UPDATE v2 = 1 WHERE 1 = 1 │ 2022-02-05 21:19:16 │ ['']                       │ [3]                  │ ['197001_1_1_0']  │           1 │       0 │ 197001_1_1_0       │ 2022-02-05 21:19:23 │ Code: 246. DB::Exception: Bad size of marks file '/var/lib/clickhouse/store/366/3668606c-16fe-4e35-8a4e-3b2bd9def292/197001_1_1_0/v1.mrk2': 0, must be: 48: While executing MergeTreeInOrder. (CORRUPTED_DATA) (version 22.1.3.7 (official build)) │
└──────────┴───────┴────────────────┴───────────────────────────┴─────────────────────┴────────────────────────────┴──────────────────────┴───────────────────┴─────────────┴─────────┴────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

and logs

```
2022.02.05 21:19:28.592575 [ 73 ] {3668606c-16fe-4e35-8a4e-3b2bd9def292::197001_1_1_0_3} <Error> default.t (3668606c-16fe-4e35-8a4e-3b2bd9def292): Cannot quickly remove directory /var/lib/clickhouse/store/366/3668606c-16fe-4e35-8a4e-3b2bd9def292/delete_tmp_tmp_mut_197001_1_1_0_3 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/366/3668606c-16fe-4e35-8a4e-3b2bd9def292/delete_tmp_tmp_mut_197001_1_1_0_3/v1.bin, errno: 2, strerror: No such file or directory. (CANNOT_UNLINK) (version 22.1.3.7 (official build))
```

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix several rare bugs with `ALTER TABLE .. RENAME COLUMN` query. Fixes #34342. Attention: Here, we add a file into data parts -- `metadata_version.txt`. It shouldn't affect anything related to backward compatibility. In case of any issues, removing this file from the disk is completely safe. Also, the logic of `ALTER TABLE RENAME COLUMN` changed. So if you want to use different versions and execute the `RENAME COLUMN` query, you can get errors in logs like `Checksums don't match`. Again it doesn't lead to any issues except redundant work, but messages can be scary.

### CODE REVIEW

**Comment by qoega** [comment]
Context? Is it one of hung check failures in stress?

**Comment by alesapin** [comment]
Context: we have a bug and need to fix it.

File: tests/queries/0_stateless/01281_alter_rename_and_other_renames.sql [hunk 1]
```diff
@@ -1,6 +1,6 @@
 DROP TABLE IF EXISTS rename_table_multiple;
 
-CREATE TABLE rename_table_multiple (key Int32, value1 String, value2 Int32) ENGINE = MergeTree ORDER BY tuple();
+CREATE TABLE rename_table_multiple (key Int32, value1 String, value2 Int32) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_bytes_for_wide_part=0;
```
Comment (alesapin) [inline tests/queries/0_stateless/01281_alter_rename_and_other_renames.sql:3]: This test was wrong, because it intended to check rename with wide parts.

File: src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp [hunk 2]
```diff
@@ -1754,19 +1755,36 @@ ReplicatedMergeTreeMergePredicate ReplicatedMergeTreeQueue::getMergePredicate(zk
...
-        if (mutation_version > part_version && mutation_status->entry->alter_version != -1)
-            return mutation_status->entry->commands;
+    Int64 part_metadata_version = part->getMetadataVersion();
+    std::map<int64_t, MutationCommands> result;
+    /// Here we return mutation commands for part which has bigger mutation version than part mutation version.
+    /// Please note, we don't use getDataVersion(). It's because these alter commands are used for in-fly conversions
+    /// of part's metadata. It mean that even if we have mutation with version X and part with data version X+10, but
+    /// without mutation version part can still have wrong metadata and we have to apply this change on-fly if needed.
+
+    for (auto [mutation_version, mutation_status] : in_partition->second | std::views::reverse)
```
Comment (alesapin) [inline src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1772]:
```suggestion
    for (const auto & [mutation_version, mutation_status] : in_partition->second | std::views::reverse)
```

**Comment by alesapin** [comment]
Really, I cannot explain it. Looks like `ALTER RENAME COLUMN` was completely broken in quite trivial cases. However we had a lot of tests (some of them complex and some of them are even for concurrency) and they all were able to pass. But simple sequence of several RENAMEs could lead to data corruption.....

And if I'm trying to change anything related to renames some test fails. Now I hope tests should pass, and maybe I'll refactor this...

File: tests/queries/0_stateless/02555_davengers_rename_chain.sql [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+ORDER BY tuple()
+SETTINGS min_bytes_for_wide_part = 10000000;
+
+INSERT INTO wrong_metadata_compact VALUES (1, 2, 3);
+
+SYSTEM STOP MERGES wrong_metadata_compact;
+
+ALTER TABLE wrong_metadata_compact RENAME COLUMN a TO a1, RENAME COLUMN b to b1 SETTINGS replication_alter_partitions_sync = 0;
+
+SELECT sleep(1) FORMAT Null;
```
Comment (alesapin) [inline tests/queries/0_stateless/02555_davengers_rename_chain.sql:64]: need to rewrite this test

File: tests/queries/0_stateless/02361_fsync_profile_events.sh [hunk 4]
```diff
@@ -44,8 +44,8 @@ for i in {1..100}; do
     ")"
 
     # Non retriable errors
-    if [[ $FileSync -ne 7 ]]; then
-        echo "FileSync: $FileSync != 11" >&2
```
Comment (alesapin) [inline tests/queries/0_stateless/02361_fsync_profile_events.sh:48]: image

File: src/Storages/MutationCommands.h [hunk 5]
```diff
@@ -79,6 +82,8 @@ class MutationCommands : public std::vector<MutationCommand>
     void readText(ReadBuffer & in);
     std::string toString() const;
     bool hasNonEmptyMutationCommands() const;
+
+    bool containBarrierCommand() const;
```
Comment (alesapin) [inline src/Storages/MutationCommands.h:86]:
```suggestion
    /// These set of commands contain barrier command and shouldn't
    /// stick with other commands. Commands from one set have already been validated
    /// to be executed without issues on the creation state.
    bool containBarrierCommand() const;
```

**Comment by alesapin** [comment]
Okay, what I've fixed here:
### Initial race found in production: When the user executes `ALTER TABLE ... RENAME COLUMN x TO y` for ReplicatedMergeTree we do the following:
1) Allocate the block number in each partition.
2) Create mutation entry in `/mutations`.
3) Create `ALTER_METADATA` entry in replication log.
Imagine that we have a single partition (`all`), and we allocated a block number 77 in this partition. All parts with smaller block numbers must be mutated: column `x` must be renamed on disk to `y`. Immediately after that (before execution of `ALTER_METADATA [x -> y]`), the user makes a new `INSERT`, which produces part `all_78_78_0`. This part will still have column `x` instead of `y`, but it will not be mutated since its data version (78) is bigger than the mutation number (77). And now we have no idea what to do with columns for this part. They are just different from the table; no mutation is assigned to this part. 
We have precisely the same behavior for all other types of alters with `ALTER_METADATA`. Still, it's not an issue because we can always deduce conversion for new parts based on schema diff (like if we have `String` in a table and `UInt64` in part for column `column1` let's add in-flight `cast(column1 as String)` during any read operation from this part). After the merge, which should happen soon for the fresh part, the schema will be alright.
But we cannot use this approach for `RENAME COLUMN` and even cannot use some heuristics approach. Imagine we have two alters:
`ALTER TABLE ... RENAME COLUMN a TO a1, RENAME COLUMN b TO b1`.
`ALTER TABLE ... RENAME COLUMN a1 TO b, RENAME COLUMN b1 TO a`
And we have part with columns `a` and `b`. In this case, it would be impossible to guess do we have to apply these alters or maybe we don't. But these operations are not idempotent.

To resolve this issue, I've added an additional file to the part: `metadata_version.txt`. This file contains a single value with the version of the metadata which was in the table when this part was written to disk. With this info, we can always understand which commands we need to apply to part during reading or mutation. This file is maintained properly only in ReplicatedMergeTree. For ordinary MergeTree, it's also written but always contains zero.

### Incorrect order of hardlinks for renames on disk or missed renames on disk.
For wide parts, we execute renames in the following way `RENAME a TO b`:
1) hardlink source_part/a.bin to destination_part/b.bin
2) hardlink source_part/a.mrk to destination_part/b.mrk
Image that now we have some kind of transitive rename like `RENAME a TO  b, RENAME b TO c`. In this case, it's impossible to execute it the same way:
1) hardlink source_part/a.bin to destination_part/b.bin
2) hardlink source_part/a.mrk to destination_part/b.mrk
3) hardlink source_part/b.bin to destination_part/c.bin (oops, `source_part/b.bin` doesn't exist)
4) hardlink source_part/b.mrk to destination_part/c.mrk
I've fixed this, and now we squash such transitive renames into a single step. There was also a sub-issue in that we did these hardlinks in an unordered way (putting commands into hashmap). 

### Race condition in mutations in ordinary merge tree.
When we execute mutation, we always expect that our `StorageInMemoryMetadataPtr` is equal or fresher than our commands. But unfortunately, there was a race condition that allowed it to get stale in memory metadata.

**Comment by alesapin** [comment]
Who break replicated DB tests?

File: src/Storages/MergeTree/AlterConversions.h [hunk 6]
```diff
@@ -14,11 +14,22 @@ namespace DB
...
 struct AlterConversions
 {
+    struct RenamePair
+    {
+        std::string rename_to;
+        std::string rename_from;
+    };
     /// Rename map new_name -> old_name
-    std::unordered_map<std::string, std::string> rename_map;
+    std::vector<RenamePair> rename_map;
```
Comment (CurtizJ) [inline src/Storages/MergeTree/AlterConversions.h:23]: Why replaced by `std::vector`?

File: src/Storages/MergeTree/MutateTask.cpp [hunk 7]
```diff
@@ -141,13 +164,57 @@ static void splitMutationCommands(
...
+    }
+}
+
+/// It's legal to squash renames because commands with rename are always "barrier"
+/// and executed separately from other types of commands.
+static MutationCommands squashRenamesInCommands(const MutationCommands & commands)
+{
+    NameToNameMap squashed_renames;
+    for (const auto & command : commands)
+    {
```
Comment (CurtizJ) [inline src/Storages/MergeTree/MutateTask.cpp:191]: Maybe add an assert that command is actually is a `RENAME`?

File: src/Storages/MergeTree/MutateTask.cpp [hunk 8]
```diff
@@ -141,13 +164,57 @@ static void splitMutationCommands(
...
+        for (const auto & [rename_to, rename_from] : alter_conversions.rename_map)
+        {
+            for_file_renames.push_back({.type = MutationCommand::Type::RENAME_COLUMN, .column_name = rename_from, .rename_to = rename_to});
+        }
+    }
+}
+
+/// It's legal to squash renames because commands with rename are always "barrier"
+/// and executed separately from other types of commands.
+static MutationCommands squashRenamesInCommands(const MutationCommands & commands)
```
Comment (CurtizJ) [inline src/Storages/MergeTree/MutateTask.cpp:187]: Does it really make sense? As I understand from your [code](https://github.com/ClickHouse/ClickHouse/blob/1683cd5d6fedbf5b388f0d5275062b37ea0c3c10/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L1848-L1861) renames cannot be squashed together even with renames from another alter and transitive renames in one alter are not [allowed](https://github.com/ClickHouse/ClickHouse/blob/0f182f61641adadcbdd028c4e31b2ae3b5a24fbf/src/Storages/AlterCommands.cpp#L1217-L1228) https://github.com/ClickHouse/ClickHouse/blob/1683cd5d6fedbf5b388f0d5275062b37ea0c3c10/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L1848-L1861.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It breaks `web` tables. Please resubmit with a test for `web` tables.

**Comment by alesapin** [comment]
@alexey-milovidov Any clues? What is web-tables? I know nothing about them. We have disk web, but not web tables. BTW, @CurtizJ comments were valuable; I need to fix them. I just was sick previous week.
