### PR TITLE
Tests: Fix timeouts handling in case of github timeout termination and clickhouse-test hang when server die

### LINKED ISSUE #66000: No artifacts on CI in case of Check timeout expired for fasttest
Consider the following run - https://s3.amazonaws.com/clickhouse-test-reports/65984/b25a58cd85a7e3c22154b9e054c4f454d0b92b53/fast_test.html

It failed with "timeout 2400s is exceeded", and does not publish any artifacts, the problem with fast test is that it is different, the container builds the clickhouse itself.

But there is possible room for improvement:
- [ ] expand `fast_test_check.py` to kill the docker container and gather all the logs
- [ ] fix `clickhouse-test` - AFAIR this wrapper uses timeouts everywhere and it should not hang, and 40mins should be enough, the problem is that in that run it just hunged (maybe because of gdb? not sure)
- [ ] and likely `clickhouse-test` did not report all the failed tests

### PR DESCRIPTION
**Pull request by fm4v**
1. Add timeouts that are slightly shorter than github's timeouts to stop clickhouse-test before github's limits are reached.
2. In cases where clickhouse-server dies, clickhouse-test can sometimes hang indefinitely. Fix this by removing the queue in clickhouse-tests.

Closes: https://github.com/ClickHouse/ClickHouse/issues/66000
Fixes empty reports: 
https://s3.amazonaws.com/clickhouse-test-reports/65984/b25a58cd85a7e3c22154b9e054c4f454d0b92b53/fast_test.html
https://s3.amazonaws.com/clickhouse-test-reports/65979/4f66a6651afc9f655c820fedf6a6163fc4942fe9/fast_test.html

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix problem when github terminate instances by timeout and artifacts are not collected and full test report is not generated.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit b88be7260f6ce1eda9b949e1aa297eea5a2a110f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66036/b88be7260f6ce1eda9b949e1aa297eea5a2a110f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: tests/clickhouse-test [hunk 1]
```diff
@@ -360,39 +358,6 @@ def clickhouse_execute_json(
...
-            # send, this thread will die, and you will get
-            # ConnectionRefusedError error for any access to "restarted_tests"
-            # variable.
-            restarted_tests = [*restarted_tests]
-
-            # send signal to all processes in group to avoid hung check triggering
-            # (to avoid terminating clickhouse-test itself, the signal should be ignored)
-            signal.signal(signal.SIGTERM, signal.SIG_IGN)
-            os.killpg(os.getpgid(os.getpid()), signal.SIGTERM)
-            signal.signal(signal.SIGTERM, signal.SIG_DFL)
```
Comment (azat) [inline tests/clickhouse-test:393]: Hm, this part looks useful (see also for some comments https://github.com/ClickHouse/ClickHouse/pull/58213)

In a nutshell this should avoid leaving left overs when the clickhouse-test terminated, since there are bunch of .sh tests that could do tricky things

File: docker/test/stateless/run.sh [hunk 2]
```diff
@@ -262,14 +265,15 @@ function run_tests()
 
 export -f run_tests
 
+TIMEOUT=$((${MAX_RUN_TIME} - 200))
```
Comment (azat) [inline docker/test/stateless/run.sh:268]: Let's put a comment that 200 seconds should be enough to do all the after-tests jobs (gather artifacts)

**Review by azat — COMMENTED** [review]
I like the idea of simplify `clickhouse-test`!

File: docker/test/stateless/run.sh (hunk 2 above)
Comment (fm4v) [reply docker/test/stateless/run.sh]: Done

File: tests/clickhouse-test (hunk 1 above)
Comment (fm4v) [reply tests/clickhouse-test:393]: I've returned it. After checking the PR i didn't see any leftovers locally after clickhouse-server or process termination

Comment (azat) [reply tests/clickhouse-test:393]: You should run some tricky test, some `.sh` test, to see them (for instance the one that called stress or similar, that has loop in background + wait)

File: tests/clickhouse-test [hunk 3]
```diff
@@ -360,37 +358,12 @@ def clickhouse_execute_json(
...
 
-class Terminated(KeyboardInterrupt):
-    pass
-
-
-def signal_handler(sig, frame):
-    raise Terminated(f"Terminated with {sig} signal")
-
-
 def stop_tests():
```
Comment (azat) [inline tests/clickhouse-test:361]: Also, maybe we should call it from signal handler? Or it will be handled gracefully and called from other parts of the code?

**Comment by azat** [comment]
While you are here, maybe you can add a global `except KeyboardInterrupt`, so that you will not see useless python's traceback on SIGINT, and instead, SIGINT should wait all running tests, but do not start anything new. Subsequent SIGINT should terminate it without waiting for current tests (but killing them)

But maybe it worth to do in a separate PR

File: docker/test/stateless/run.sh [hunk 4]
```diff
@@ -262,14 +265,17 @@ function run_tests()
...
 if [ "$NUM_TRIES" -gt "1" ]; then
     # We don't run tests with Ordinary database in PRs, only in master.
     # So run new/changed tests with Ordinary at least once in flaky check.
-    timeout_with_logging "$MAX_RUN_TIME" bash -c 'NUM_TRIES=1; USE_DATABASE_ORDINARY=1; run_tests' \
+    timeout_with_logging "$TIMEOUT" bash -c 'NUM_TRIES=1; USE_DATABASE_ORDINARY=1; run_tests' \
       | sed 's/All tests have finished//' | sed 's/No tests were run//' ||:
 fi
 
-timeout_with_logging "$MAX_RUN_TIME" bash -c run_tests ||:
+timeout_with_logging "$TIMEOUT" bash -c run_tests ||:
```
Comment (azat) [inline docker/test/stateless/run.sh:278]: I don't see that this helps here - https://s3.amazonaws.com/clickhouse-test-reports/66311/076d2bb960a797c6fb25fcf0d3e390b3d695de46/stateless_tests__debug__[2_2].html

Can you please take a look why?

Comment (fm4v) [reply docker/test/stateless/run.sh:278]: Please rebase, timeout is decreased and works

Comment (azat) [reply docker/test/stateless/run.sh:278]: Where? I don't see any $TIMEOUT adjustments apart from this PR

Comment (fm4v) [reply docker/test/stateless/run.sh:278]: https://github.com/ClickHouse/ClickHouse/commit/4a56c601b2b4ec364f808b25d6e9d9adfd4d3ce2

Comment (azat) [reply docker/test/stateless/run.sh:278]: How about this one https://s3.amazonaws.com/clickhouse-test-reports/66439/669ce7cd40881a075fe473027e6668d13683c840/stateful_tests__tsan_.html?

Comment (fm4v) [reply docker/test/stateless/run.sh:278]: There is no change for stateful tests because they use `stateful/run.sh`, which has a larger timeout. I will fix that as well.
