### PR TITLE
Fix assertion in `MergeTreePrefetchedReadPool::startPrefetches`

### LINKED ISSUE #78287: Assertion error on mergetree pool prefetch
### Describe the bug

The reproducible is rather large: [issue.txt](https://github.com/user-attachments/files/19465292/issue.txt) Run the file on the client with `--ignore-error`. Use `test_cluster_two_shards` remote server setup from testing.

On the SELECT query, this assertion is hit:
```
void DB::MergeTreePrefetchedReadPool::startPrefetches(): Assertion `prefetch_queue.top().task->priority == highest_priority' failed
```

### How to reproduce

Run [issue.txt](https://github.com/user-attachments/files/19465292/issue.txt) 

### Error message and/or stacktrace

Stack trace:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=0) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c4519e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c28902 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7c2881e in __assert_fail_base (fmt=0x7ffff7dde2a0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=warning: (Internal error: pc 0x5555599cf8d8 in read in CU, but not in symtab.)
#6  0x00007ffff7c3b7c7 in __assert_fail (assertion=warning: (Internal error: pc 0x5555599cf8d8 in read in CU, but not in symtab.)
#7  0x000055556c3533ee in DB::MergeTreePrefetchedReadPool::startPrefetches (this=this@entry=0x7ffeb434d518) at src/Storages/MergeTree/MergeTreePrefetchedReadPool.cpp:165
#8  0x000055556c35344d in DB::MergeTreePrefetchedReadPool::getTask (this=0x7ffeb434d518, task_idx=0, previous_task=0x0) at src/Storages/MergeTree/MergeTreePrefetchedReadPool.cpp:194
#9  0x000055556b9253a0 in DB::MergeTreeSelectProcessor::read (this=0x7ffeb42f7900) at src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:199
#10 0x000055556c34e5a9 in DB::MergeTreeSource::tryGenerate (this=0x7ffeb4340618) at src/Storages/MergeTree/MergeTreeSource.cpp:229
#11 0x000055556be11787 in DB::ISource::work (this=0x7ffeb4340618) at src/Processors/ISource.cpp:108
#12 0x000055556be2c44f in DB::executeJob (node=0x7ffeb43ad700, read_progress_callback=0x7ffd2dd30280) at src/Processors/Executors/ExecutionThreadContext.cpp:53
#13 DB::ExecutionThreadContext::executeTask (this=0x7ffd296aad00) at src/Processors/Executors/ExecutionThreadContext.cpp:102
#14 0x000055556be21545 in DB::PipelineExecutor::executeStepImpl (this=this@entry=0x7ffd4438fc18, thread_num=<optimized out>, yield_flag=yield_flag@entry=0x0) at src/Processors/Executors/PipelineExecutor.cpp:296
#15 0x000055556be217fe in DB::PipelineExecutor::executeSingleThread (this=0x3be9a9, this@entry=0x7ffd4438fc18, thread_num=3927281) at src/Processors/Executors/PipelineExecutor.cpp:262
#16 0x000055556be2227f in DB::PipelineExecutor::spawnThreadsImpl()::$_0::operator()() const (this=0x7ffe1cdd1620) at src/Processors/Executors/PipelineExecutor.cpp:416
#17 std::__1::__invoke[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl()::$_0&>(DB::PipelineExecutor::spawnThreadsImpl()::$_0&) (__f=...) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149
#18 std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl()::$_0&>(DB::PipelineExecutor::spawnThreadsImpl()::$_0&) (__args=...)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224
#19 std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()>::operator()[abi:se190107]() (this=0x7ffe1cdd1620) at contrib/llvm-project/libcxx/include/__functional/function.h:210
#20 std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()> >(std::__1::__function::__policy_storage const*) (
    __buf=<optimized out>) at contrib/llvm-project/libcxx/include/__functional/function.h:610
#21 0x0000555565136ef3 in std::__1::__function::__policy_func<void ()>::operator()[abi:se190107]() const (this=0x7ffd34deec20) at contrib/llvm-project/libcxx/include/__functional/function.h:716
#22 std::__1::function<void()>::operator() (this=0x7ffd34deec20) at contrib/llvm-project/libcxx/include/__functional/function.h:989
#23 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::worker (this=this@entry=0x7ffe1cdd1590) at src/Common/ThreadPool.cpp:799
#24 0x000055556513cd62 in std::__1::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*&, , void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*&) (__f=<optimized out>, __a0=<optimized out>)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#25 std::__1::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&, std::__1::__tuple_indices<0ul>) (
    __f=<optimized out>, __t=...) at contrib/llvm-project/libcxx/include/tuple:1354
#26 std::__1::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&) (__f=<optimized out>, __t=...)
    at contrib/llvm-project/libcxx/include/tuple:1358
#27 ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*&&)::{lambda()#1}::operator()() (this=0x7ffd296ab3c0)
    at src/Common/ThreadPool.h:312
#28 0x0000555565134632 in std::__1::__function::__policy_func<void ()>::operator()[abi:se190107]() const (this=0x7ffd34def210) at contrib/llvm-project/libcxx/include/__functional/function.h:716
#29 std::__1::function<void()>::operator() (this=0x7ffd34def210) at contrib/llvm-project/libcxx/include/__functional/function.h:989
#30 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (this=0x7ffd442ffc00) at src/Common/ThreadPool.cpp:809
#31 0x000055556513a920 in std::__1::__invoke[abi:se190107]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) (__f=<optimized out>, __a0=<optimized out>) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#32 std::__1::__thread_execute[abi:se190107]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (__t=...) at contrib/llvm-project/libcxx/include/__thread/thread.h:192
#33 std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=<optimized out>) at contrib/llvm-project/libcxx/include/__thread/thread.h:201
#34 0x00007ffff7ca1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#35 0x00007ffff7d33a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
The assertion checked that the top of `prefetch_queue` had a priority equal to `highest_priority`, but not all tasks are prefetched — some are skipped due to `filesystem_prefetch_max_memory_usage` or prefetch count limits. When the first tasks of all threads are skipped, the top of the queue has a higher priority value, violating the `==` assertion.

Closes #78287

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Version info
- Merged into: `26.2.1.350`

### CODE REVIEW

File: tests/queries/0_stateless/03823_prefetched_read_pool_priority_assertion.sql [hunk 1]
```diff
@@ -0,0 +1,21 @@
+-- Regression test for https://github.com/ClickHouse/ClickHouse/issues/78287
+-- The assertion in `MergeTreePrefetchedReadPool::startPrefetches` could fail
+-- when `filesystem_prefetch_max_memory_usage` is low enough that the first tasks
+-- of all threads are skipped for prefetching, so the top of the prefetch queue
+-- has a priority higher than the initial (highest) priority.
```
Comment (nickitat) [inline tests/queries/0_stateless/03823_prefetched_read_pool_priority_assertion.sql]: IMHO, no comment is better than an AI attempt to explain you stuff 

```suggestion
-- Regression test for https://github.com/ClickHouse/ClickHouse/issues/78287
```

File: src/Storages/MergeTree/MergeTreePrefetchedReadPool.cpp [hunk 2]
```diff
@@ -181,7 +181,9 @@ void MergeTreePrefetchedReadPool::startPrefetches()
 
     [[maybe_unused]] TaskHolder prev;
     [[maybe_unused]] const Priority highest_priority{reader_settings.read_settings.priority.value + 1};
-    assert(prefetch_queue.top().task->priority == highest_priority);
+    /// Not all tasks are necessarily prefetched: some may be skipped due to memory or prefetch count limits.
+    /// So the top of the queue may have a priority higher than `highest_priority`.
```
Comment (nickitat) [inline src/Storages/MergeTree/MergeTreePrefetchedReadPool.cpp]:
```suggestion
    /// Due to the difference in `estimated_memory_usage_for_single_prefetch` for different parts (column sizes might be different), it might happen that for the given thread, task number N won't fit in the prefetch memory limit, but the next task will.
    /// So the top of the queue may have a priority higher than `highest_priority`.
```

**Review by nickitat — APPROVED** [review]
