### PR TITLE
Fix WITH FILL with NaN keys

### LINKED ISSUE #69261: Query taking forever to run
**Company or project name**

Clickhouse employee :smile: 

**Describe what's wrong**

The query: 
```sql
SELECT nan ORDER BY 1 WITH FILL;
```
takes forever to run. I can't place a Fiddle link because it doesn't finish running.

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

Run the query above.

**Expected behavior**

It shouldn't hang forever.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix non-cancellable queries containing WITH FILL with NaN keys. This closes #69261.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit bf5e68f334f6128e1e440b047ef90ef311e22861 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69845/bf5e68f334f6128e1e440b047ef90ef311e22861/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/14cb02a18ce43f27c2e340d05451aaff3e13617a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Interpreters/FillingRow.cpp [hunk 1]
```diff
@@ -16,6 +16,10 @@ bool less(const Field & lhs, const Field & rhs, int direction)
 
 bool equals(const Field & lhs, const Field & rhs)
 {
+    /// This will treat NaNs as equal
+    if (lhs.getType() == rhs.getType())
```
Comment (antonio2368) [inline src/Interpreters/FillingRow.cpp:20]: should we rather extend `FieldVisitorAccurateEquals` and use `FloatCompareHelper` if both values are floats?

Comment (alexey-milovidov) [reply src/Interpreters/FillingRow.cpp:20]: I checked the code, and this was my concern as well. I thought that FieldVisitorAccurateEquals tries to compare exactly as the underlying values compare. But I'm not sure if it is needed. So - simple change first...

**Review by antonio2368 — APPROVED** [review]
