### PR TITLE
Fix `arrayFilter` function not working with `Nothing` return type for new analyzer

### LINKED ISSUE #73849: Analyzer: Cannot insert element into Nothing
```sql
SELECT arrayFilter(x->x=1, []);

┌─arrayFilter(lambda(tuple(x), equals(x, 1)), [])─┐
│ []                                              │
└─────────────────────────────────────────────────┘


SELECT arrayFilter(x->x is not null, []);

DB::Exception: Cannot insert element into Nothing: In scope x -> (x IS NOT NULL). (NOT_IMPLEMENTED)
```

https://fiddle.clickhouse.com/6bd9a06a-d844-4db3-acf8-93a84d691f1c

### PR DESCRIPTION
**Pull request by nihalzp**
Currently the following query does not work for new analyzer, but should:

```sql
SELECT arrayFilter(x -> (x IS NOT NULL), []);
```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `arrayFilter` function not working when using empty array and `isNull` function. Closes https://github.com/ClickHouse/ClickHouse/issues/73849.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Functions/isNotNull.cpp [hunk 1]
```diff
@@ -47,6 +47,11 @@ class FunctionIsNotNull : public IFunction
         if (!use_analyzer)
             return nullptr;
 
+        /// SELECT arrayFilter(x -> (x IS NOT NULL), []) can trigger `defaultImplementationForNothing()`
+        /// which will give return type Nothing. We cannot create constant column of type Nothing so return nullptr.
```
Comment (antaljanosbenjamin) [inline src/Functions/isNotNull.cpp:51]: Shouldn't we instead make sure the result type is not nothing? I think that is not correct. I might be wrong, so please let me know if I miss something.

Comment (nihalzp) [reply src/Functions/isNotNull.cpp:51]: I think that because the `isNull` function has `useDefaultImplementationForNothing()` returning `true`, it is expected to get `result_type` as `Nothing` if any of the input arguments is `Nothing`. The implementation of `IFunctionOverloadResolver::getReturnTypeWithoutLowCardinality` returns `std::make_shared<DataTypeNothing>()` if any of the input arguments has type `Nothing`. The return type of `IFunctionOverloadResolver::getReturnTypeWithoutLowCardinality` is ultimately used as the `result_type` of the function call `getConstantResultForNonConstArguments`. 

This is the case for `SELECT arrayFilter(x -> (x IS NOT NULL), [])` because `[]` has type `Array(Nothing)`; as a result, the input argument to `isNull` function will be `Nothing`.

Comment (antaljanosbenjamin) [reply src/Functions/isNotNull.cpp:51]: So after reading your comment and code it became clear:
 - `getConstantResultForNonConstArguments` is only called during query analysis. Returning `nullptr` means that the function cannot be converted into a constant.
 - during actual execution, the return value will be returned by `defaultImplementationForNothing`, therefore there won't be any difference in expected return type and the actual return type.

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @nihalzp @antaljanosbenjamin — while reviewing this PR I found the following:

- **Bug (P1):** `FunctionComparison::getConstantResultForNonConstArguments` missing `isNothing(result_type)` guard — same bug class as PR fix — https://github.com/ClickHouse/ClickHouse/issues/102858

Happy to discuss — close anything that's wrong or already addressed.
