### PR TITLE
Fixed rare incorrect marking of a data part as broken and detaching it after `DETACH/ATTACH TABLE` query.

### LINKED ISSUE #99395: No such part error after detaching two tables
### Describe the bug

Only happens since v26.2.

### How to reproduce

v26.2 empty (error): https://fiddle.clickhouse.com/59a6c7ee-485a-4f88-8864-3b252ff8d51c
v26.1 no error: https://fiddle.clickhouse.com/6680d113-131d-478b-8158-5c58f085d899

### Error message and/or stacktrace

The detailed error:
```
<Error> default.t0 (3297091c-51f4-4a77-9fbf-093874414307): Part /var/libstore/329/3297091c-51f4-4a77-9fbf-093874414307/all_1_1_0/ is broken and needs manual correction. Reason: Code: 107. DB::ErrnoException: Cannot open file /var/libstore/329/3297091c-51f4-4a77-9fbf-093874414307/all_1_1_0/partition.dat: , errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113:14: Poco::Exception::Exception(String&&, int) @ 0x0000000026b0cd73
1. src/Common/Exception.cpp:139:7: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001621b3a9
2. src/Common/Exception.h:171:100: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000e272994
3. src/Common/Exception.h:57:54: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000e272491
4. src/Common/ErrnoException.h:42:11: DB::ErrnoException::ErrnoException<String const&>(int, int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x0000000016327a07
5. src/Common/ErrnoException.h:57:18: void DB::ErrnoException::throwFromPath<String const&>(int, String const&, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x00000000163278c2
6. src/IO/OpenedFile.cpp:34:9: ? @ 0x000000001a7c4db0
7. src/IO/OpenedFile.cpp:42:9: DB::OpenedFile::getFD() const @ 0x000000001a7c4de2
8. src/IO/ReadBufferFromFile.h:101:20: DB::ReadBufferFromFilePReadWithDescriptorsCache::ReadBufferFromFilePReadWithDescriptorsCache(String const&, unsigned long, int, char*, unsigned long, std::optional<unsigned long>, std::shared_ptr<DB::IThrottler>) @ 0x000000001a7bd697
9. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:773:30: DB::createReadBufferFromFileBase(String const&, DB::ReadSettings const&, std::optional<unsigned long>, std::optional<unsigned long>, int, char*, bool)::$_1::operator()(unsigned long, unsigned long, int) const @ 0x000000001a7bccac
10. src/Disks/IO/createReadBufferFromFileBase.cpp:239:15: DB::createReadBufferFromFileBase(String const&, DB::ReadSettings const&, std::optional<unsigned long>, std::optional<unsigned long>, int, char*, bool) @ 0x000000001a7bc56b
11. src/Disks/DiskLocal.cpp:372:12: DB::DiskLocal::readFile(String const&, DB::ReadSettings const&, std::optional<unsigned long>) const @ 0x000000001b8237b1
12. src/Storages/MergeTree/DataPartStorageOnDiskFull.cpp:130:31: DB::DataPartStorageOnDiskFull::readFile(String const&, DB::ReadSettings const&, std::optional<unsigned long>) const @ 0x000000001f7ebddb
13. src/Storages/MergeTree/IMergeTreeDataPart.cpp:3079:37: DB::IMergeTreeDataPart::readFile(String const&) const @ 0x000000001f81c46d
14. src/Storages/MergeTree/MergeTreePartition.cpp:407:22: DB::MergeTreePartition::load(DB::IMergeTreeDataPart const&) @ 0x000000001fafd517
15. src/Storages/MergeTree/IMergeTreeDataPart.cpp:1638:19: DB::IMergeTreeDataPart::loadPartitionAndMinMaxIndex() @ 0x000000001f82fd32
16. src/Storages/MergeTree/IMergeTreeDataPart.cpp:1159:9: DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool, bool) @ 0x000000001f82b765
17. src/Storages/MergeTree/MergeTreeData.cpp:1976:19: DB::MergeTreeData::loadDataPart(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, DB::SharedMutex&) @ 0x000000001f920665
18. src/Storages/MergeTree/MergeTreeData.cpp:2122:20: DB::MergeTreeData::loadDataPartWithRetries(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, DB::SharedMutex&, unsigned long, unsigned long, unsigned long) @ 0x000000001f92615f
19. src/Storages/MergeTree/MergeTreeData.cpp:2186:28: void std::__function::__policy_func<void ()>::__call_func[abi:se210105]<DB::MergeTreeData::loadDataPartsFromDisk(std::vector<std::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>, std::allocator<std::shared_ptr<DB::MergeTreeData::PartLoadingTree::Node>>>&)::$_0>(std::__function::__policy_storage const*) @ 0x000000001f9c328e
20. contrib/llvm-project/libcxx/include/__functional/function.h:508:12: ? @ 0x0000000017db34ca
21. src/Common/threadPoolCallbackRunner.h:222:13: DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::function<void ()>>::enqueueAndGiveOwnership(std::function<void ()>&&, Priority, std::optional<unsigned long>)::'lambda'()::operator()() @ 0x0000000017db32a1
22. contrib/llvm-project/libcxx/include/__functional/function.h:508:12: ? @ 0x00000000163b11f9
23. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x00000000163b781f
24. contrib/llvm-project/libcxx/include/__functional/function.h:508:12: ? @ 0x00000000163ae603
25. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: void* std::__thread_proxy[abi:se210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000163b54ce
26. start_thread @ 0x000000000009caa4
27. __clone3 @ 0x0000000000129c6c
 (version 26.3.1.644 (official build))
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed rare incorrect marking of a data part as broken and detaching it after `DETACH/ATTACH TABLE` query.

Fixes #99395.

### Version info
- Merged into: `26.3.1.749`
- Backported to: `26.2.6.6`

### CODE REVIEW

File: tests/queries/0_stateless/04041_attach_table_no_partition_key_metadata_cache.sql [hunk 1]
```diff
@@ -0,0 +1,17 @@
+DROP TABLE IF EXISTS t0;
+DROP TABLE IF EXISTS t1;
+
+SET enable_shared_storage_snapshot_in_query = 1;
```
Comment (PedroTadim) [inline tests/queries/0_stateless/04041_attach_table_no_partition_key_metadata_cache.sql:4]: Should it be tested with this setting disabled as well?

Comment (CurtizJ) [reply tests/queries/0_stateless/04041_attach_table_no_partition_key_metadata_cache.sql:4]: Added
