### PR TITLE
Better MySQL compatibility

### LINKED ISSUE #50957: MySQL interface sends SQLSTATE 00000 instead of HY000 for failed queries
Server: docker image clickhouse/clickhouse-server:23.5-alpine
Client: mysql --version mysql  Ver 8.0.33-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

Server config:
```
<clickhouse>
    <mysql_port>3306</mysql_port>
</clickhouse>
```

1. I connect to clickhouse with a mysql client:
```
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 23.5.1.3174-ClickHouse 
```

2. I execute an invalid query:
```
mysql> select foo bar;
ERROR 47 (00000): Code: 47. DB::Exception: Missing columns: 'foo' while processing query: 'SELECT foo AS bar', required columns: 'foo'. (UNKNOWN_IDENTIFIER) (version 23.5.1.3174 (official build))
```
=> the query failed, server response indicates error code 47 with SQLSTATE 00000.

3. By definition, the first two characters of an SQLSTATE value indicate the error class (https://dev.mysql.com/doc/refman/8.0/en/error-message-elements.html). Class = '00' indicates success.

=> So many client libraries such as PHP's pdo_mysql treat the **failed** query as a **successful** query.

From my understanding of the MySQL documentation, "HY000" should be used instead of "00000", but I'm not a mysql core expert and the final decision is up to you.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make the error code in the MySQL wire protocol compatible with MySQL. Continuation of #56831. Closes #50957.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 480c233a41bed738db7881a20e77f6c379f5dc2d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73948/480c233a41bed738db7881a20e77f6c379f5dc2d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/ccd0ede944185928eab30758fc390c39d3bcab2d/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Server/MySQLHandler.cpp [hunk 1]
```diff
@@ -170,6 +170,30 @@ static String killConnectionIdReplacementQuery(const String & query)
...
+  * Apparently, they decide to allocate alphanumeric characters for some meaning,
+  * then split their range (0..9A..Z) to some intervals for the system, user, and other categories,
+  * and the letter H appeared to be the first in some category.
+  *
+  * Also, the letter Y is chosen, because it is the highest, but someone afraid to took letter Z,
+  * and decided that the second highest letter is good enough.
+  *
+  * This will forever remind us about the mistakes made by previous generations of software engineers.
+  */
+static constexpr const char * mysql_error_code = "HY000";
```
Comment (yakov-olkhovskiy) [inline src/Server/MySQLHandler.cpp:194]: 😂

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by yakov-olkhovskiy** [comment]
...there is a couple other tests requires update:
test_mysql_protocol/test.py::test_mysql_client
test_mysql_protocol/test.py::test_mysql_client_exception
