### PR TITLE
all s3-blobs removed when merge aborted, remove part from failed fetch without unlock keper

### LINKED ISSUE #49385: Some blobs are not removed from s3
In test test_cache_with_full_disk_space
```
2023.04.27 08:14:18.347288 [ 209 ] {d3e4f537-6565-4ad5-a19e-ba8b7ea1cb9c::all_1_6_1} <Debug> MergeTask::PrepareStage: Merging 6 parts: from all_1_1_0 to all_6_6_0 into Wi
de with storage Full

...

2023.04.27 08:14:20.116772 [ 12 ] {203d8b67-d2b0-4bc5-8fba-5e26bd5ee7cb} <Debug> executeQuery: (from 172.16.1.1:45528) DROP TABLE IF EXISTS s3_test NO DELAY (stage: Complete)

...

2023.04.27 08:14:20.402136 [ 209 ] {} <Trace> default.s3_test (d3e4f537-6565-4ad5-a19e-ba8b7ea1cb9c): Part all_1_6_1 in temporary state can be removed without unlocking shared state
```

That is bad :(
CH started merge. Table is dropped during the merge. The part is temporary. It is deleted by parts destructor. But no s3 data deleted.

Recent changes are done here by me.
https://github.com/ClickHouse/ClickHouse/pull/43866

And now I'm not sure that those changes are correct. 
When part is about to call d-tor in temporary state, 3 followed option exist:
- Replicated table. If the part is created within download process, than s3 data has to stay intact.
- Replicated table. If the part is created as a result of merge, it consists new data, no one except this replica owns that s3 data, s3 data has to be deleted.
- Not replicated table. s3 data has to be deleted.

_Originally posted by @CheSema in https://github.com/ClickHouse/ClickHouse/issues/48860#issuecomment-1525390367_

### PR DESCRIPTION
**Pull request by CheSema**
Fixes https://github.com/ClickHouse/ClickHouse/issues/49385

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
That changes help CH to determine if the temporary part could be deleted without unlocking remote blobs in keeper and if so, it determines should remote blobs be preserved or not.
For example in case of any error in merging process which happened strictly before any attempt to commit it to the keeper, the temporary part has to be just deleted with remote blobs.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit c35114b01776f1f63812e25086661d03d03cab6a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49432/c35114b01776f1f63812e25086661d03d03cab6a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by CheSema** [comment]
I was curious why test test_merge_canceled_by_s3_errors_when_move passes. 
During the move the new part is definitly broken and not commited due to error from s3. The part's files left in directory MOVING_DIR_NAME. 
The answer is: during drop table all files from MOVING_DIR_NAME are dropped within the linked blobs on s3.
https://github.com/ClickHouse/ClickHouse/blob/89caf40840ed5995cc2c0d6a62cb5f10ddb49db8/src/Storages/MergeTree/MergeTreeData.cpp#L2848

**Comment by CheSema** [comment]
ClickHouse Stateless Tests
01710_projection_aggregation_in_order flaks
https://github.com/ClickHouse/ClickHouse/issues/49552

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -8263,6 +8263,29 @@ StorageReplicatedMergeTree::unlockSharedData(const IMergeTreeDataPart & part, co
...
     }
 
+    if (part.getState() == MergeTreeDataPartState::Temporary && part.is_temp)
+    {
+        /// Part {} is in temporary state and has it_temp flag. it means that it is under construction.
+        /// That path hasn't been added to active set, no commit procedure has begun.
+        /// The metadata files is about to delete now.
+        /// However remote data might be shared and has to be unlocked in the keper before removing.
+        /// Actually there is some cases when it is clear without keper:
+        /// When the part has been fetched then remote data has to be  preserved, part doesn't own it.
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:8273]:
```suggestion
        /// When the part has been fetched then remote data has to be preserved, part doesn't own it.
```

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 2]
```diff
@@ -8263,6 +8263,29 @@ StorageReplicatedMergeTree::unlockSharedData(const IMergeTreeDataPart & part, co
...
+        /// When the part has been merged then remote data can to removed, part own it.
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:8274]:
```suggestion
        /// When the part has been merged then remote data can be removed, part owns it.
```

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 3]
```diff
@@ -8263,6 +8263,29 @@ StorageReplicatedMergeTree::unlockSharedData(const IMergeTreeDataPart & part, co
...
+        /// In opposition, when the part has been mutated in generally it hardlinks the files.
+        /// Therefore remote data is shared, it has to be unlocked in the keper.
+
+        std::lock_guard lock(currently_fetching_parts_mutex);
+        if (!currently_fetching_parts.contains(part.name))
+        {
+            LOG_TRACE(log, "Part {} is temporary result of failed fetch."
+                           "Remove it without unlocking shared state preserving shared data.", part.name);
+            return std::make_pair(false, NameSet{});
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:8283]: AFAIU, `false` means "blobs cannot be removed", you probably meant `true`

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 4]
```diff
@@ -8263,6 +8263,29 @@ StorageReplicatedMergeTree::unlockSharedData(const IMergeTreeDataPart & part, co
...
+        /// The metadata files is about to delete now.
+        /// However remote data might be shared and has to be unlocked in the keper before removing.
+        /// Actually there is some cases when it is clear without keper:
+        /// When the part has been fetched then remote data has to be  preserved, part doesn't own it.
+        /// When the part has been merged then remote data can to removed, part own it.
+        /// In opposition, when the part has been mutated in generally it hardlinks the files.
+        /// Therefore remote data is shared, it has to be unlocked in the keper.
+
+        std::lock_guard lock(currently_fetching_parts_mutex);
+        if (!currently_fetching_parts.contains(part.name))
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:8279]: I'm not sure that it's reliable enough because `unlockSharedData` may be called from part's dtor. It's hard to understand in which scope we call this dtor due to shared pointers. Can it be called after removing part from `currently_fetching_parts`? I would prefer a flag that indicates that blobs were just written and can be safely removed

File: src/Storages/StorageReplicatedMergeTree.cpp (hunk 3 above)
Comment (CheSema) [reply src/Storages/StorageReplicatedMergeTree.cpp:8283]: No. I meant 
`if (currently_fetching_parts.contains(part.name))`

Comment (CheSema) [reply src/Storages/StorageReplicatedMergeTree.cpp:8283]: It is bad that there is no sensitive test. I need to add such.

**Comment by CheSema** [comment]
There is interesting fails at 56f291771873961b5cf0d512622db632e411a99b commit.
https://s3.amazonaws.com/clickhouse-test-reports/49432/56f291771873961b5cf0d512622db632e411a99b/stateless_tests__debug__s3_storage__[1_6].html

Logs like 
`2023-05-06 21:28:52 [a96b99611a3d] 2023.05.06 21:28:51.925581 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Warning> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Node with parent zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1893adb7-a7a6-49bf-8045-0ad8128b8152/202305_2_2_0/test_bdw_nboqjepgigdyjbbntaqojqndlmltt for part 202305_2_2_0 doesn't exist (part was unlocked before), refuse to remove blobs`

https://pastila.nl/?006c1488/e8222a21bdd8f2dbb00ebec20239687d

That is happenning when new part is being inserted. At commit deduplication found out that that part is `already exists locally as part 20230506_20230506_0_0_0; ignoring it.` After that part is destroing. And that process leads to such confusing logs, when CH can't decide delete blobs or nor.

```
2023.05.06 21:28:51.920393 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Trace> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Part 20230506_20230506_2_2_0 local references is zero, will check blobs can be removed in zookeeper
2023.05.06 21:28:51.921596 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Trace> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Remove zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1893adb7-a7a6-49bf-8045-0ad8128b8152/202305_2_2_0/test_bdw_nboqjepgigdyjbbntaqojqndlmltt/r1 for part 202305_2_2_0
2023.05.06 21:28:51.922823 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Information> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Lock on path /clickhouse/zero_copy/zero_copy_s3/1893adb7-a7a6-49bf-8045-0ad8128b8152/202305_2_2_0/test_bdw_nboqjepgigdyjbbntaqojqndlmltt/r1 for part 202305_2_2_0 doesn't exist, but we don't have mutation parent, can remove blobs
2023.05.06 21:28:51.923363 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Trace> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): No more children left for for /clickhouse/zero_copy/zero_copy_s3/1893adb7-a7a6-49bf-8045-0ad8128b8152/202305_2_2_0/test_bdw_nboqjepgigdyjbbntaqojqndlmltt, will try to remove the whole node
2023.05.06 21:28:51.924383 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Trace> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Node with parent zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1893adb7-a7a6-49bf-8045-0ad8128b8152/202305_2_2_0/test_bdw_nboqjepgigdyjbbntaqojqndlmltt for part 202305_2_2_0 with id test_bdw_nboqjepgigdyjbbntaqojqndlmltt doesn't exist
2023.05.06 21:28:51.925581 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Warning> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Node with parent zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1893adb7-a7a6-49bf-8045-0ad8128b8152/202305_2_2_0/test_bdw_nboqjepgigdyjbbntaqojqndlmltt for part 202305_2_2_0 doesn't exist (part was unlocked before), refuse to remove blobs
2023.05.06 21:28:51.925923 [ 664 ] {2a0b83a1-44be-4679-8f23-6d449331f70a} <Trace> test_8ds2895c.primary_key (1893adb7-a7a6-49bf-8045-0ad8128b8152): Blobs of part 20230506_20230506_2_2_0 cannot be removed
```

That not Ok, I think.
To address this I made 08bfc8f58d8e3823df215e1c8239a028a04a9a26 commit here. But I think unlockSharedData has to deal with that cases if them occurs.
 CC @tavplubix what do you think?

File: src/Storages/MergeTree/DataPartsExchange.cpp [hunk 5]
```diff
@@ -919,6 +919,7 @@ MergeTreeData::MutableDataPartPtr Fetcher::downloadPartToDisk(
 
         new_data_part->version.setCreationTID(Tx::PrehistoricTID, nullptr);
         new_data_part->is_temp = true;
+        new_data_part->remove_tmp_policy = IMergeTreeDataPart::BlobsRemovalPolicyForTemporaryParts::PRESERVE_BLOBS;
```
Comment (tavplubix) [inline src/Storages/MergeTree/DataPartsExchange.cpp:922]: Please add a comment

File: src/Storages/MergeTree/IMergeTreeDataPart.h [hunk 6]
```diff
@@ -218,6 +218,16 @@ class IMergeTreeDataPart : public std::enable_shared_from_this<IMergeTreeDataPar
     /// FIXME Why do we need this flag? What's difference from Temporary and DeleteOnDestroy state? Can we get rid of this?
     bool is_temp = false;
 
+    enum class BlobsRemovalPolicyForTemporaryParts
+    {
+        ASK_KEEPER,
+        REMOVE_BLOBS,
+        PRESERVE_BLOBS,
```
Comment (tavplubix) [inline src/Storages/MergeTree/IMergeTreeDataPart.h:225]: It would be great to add a comment that explains why we need different behavior here, like:
 - ASK_KEEPER - unlock shared data in ZooKeeper, as usual
 - REMOVE_BLOBS - sometimes we know for sure that we have just written new blobs and other replicas have not seen them yet, so we can safely remove these blobs if we fail to commit a new part (and there's nothing to unlock in ZooKeeper if the part was temporary). It avoids leaving some garbage on S3
 - PRESERVE_BLOBS - ...

**Review by tavplubix — APPROVED** [review]
