### PR TITLE
Fix for `Too large size (A) passed to allocator`

### LINKED ISSUE #92043: Logical error: Too large size (A) passed to allocator. It indicates an error. (STID: 1367-2382)
_Important: This issue was automatically created and is used by CI. Do not modify the issue title. Do not remove issue labels._

CI report: [AST fuzzer (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=ed0005e86693ef2409e105a182aa07d415996c3a&name_0=MasterCI&name_1=AST%20fuzzer%20%28arm_asan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiBUb28gbGFyZ2Ugc2l6ZSAoQSkgcGFzc2VkIHRvIGFsbG9jYXRvci4gSXQgaW5kaWNhdGVzIGFuIGVycm9yLicKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0FTVCBmdXp6ZXIgKGFybV9hc2FuKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
Error:
Logical error: 'Too large size (13744632839234567997) passed to allocator. It indicates an error.'.
---

Failed query:
SELECT DISTINCT kafkaMurmurHash(24, toNullable('a-little-bit-long-string'), 24, *), * FROM numbers(10) AS left ANY RIGHT JOIN (SELECT concat('str', number) AS str, number AS x, arrayJoin(range(number)...
---

Reproduce commands (auto-generated; may require manual adjustment):
SELECT DISTINCT kafkaMurmurHash(24, toNullable('a-little-bit-long-string'), 24, *), * FROM numbers(10) AS left ANY RIGHT JOIN (SELECT concat('str', number) AS str, number AS x, arrayJoin(range(number)...
---

Stack trace:
__pthread_kill_implementation @ 0x0000000000082009
__GI_raise @ 0x000000000003a83c
abort @ 0x0000000000027134
src/Common/Exception.cpp:54: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x000000001dc24ab4
src/Common/Exception.cpp:87: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000001dc25f5...
src/Common/Exception.cpp:138: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001dc26514
DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000f10f05c
DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000f10e38c
DB::Exception::Exception<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x000000000fa31e60
src/Common/Allocator.cpp:113: (anonymous namespace)::checkSize(unsigned long)
src/Common/Allocator.cpp:153: Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) @ 0x000000001dbb2704
void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::reallocPowerOfTwoElements<>(unsigned long) @ 0x000000000f11cc30
inlined from ./src/Common/PODArray.h:243: void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::reserve<>(unsigned long)
inlined from ./src/Common/PODArray.h:256: void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long)
./src/Columns/ColumnString.h:174: DB::ColumnString::doInsertFrom(DB::IColumn const&, unsigned long) @ 0x0000000030e3e840
inlined from ./src/Columns/IColumn.h:227: DB::IColumn::insertFrom(DB::IColumn const&, unsigned long)
src/Interpreters/HashJoin/AddedColumns.cpp:258: DB::AddedColumns<false>::appendFromBlock(DB::RowRef const*, bool) @ 0x000000002c3502f4
inlined from ./src/Interpreters/HashJoin/KnownRowsHolder.h:133: void DB::addFoundRowAll<TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, DB::RowRefList, HashCRC32<unsigned long>, HashTab...
inlined from ./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:435: void DB::processMatch<(DB::JoinKind)2, (DB::JoinStrictness)2, true, false, DB::HashJoin::MapsTemplate<DB::RowRefList>, TwoLevelHashM...
./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:529: unsigned long DB::HashJoinMethods<(DB::JoinKind)2, (DB::JoinStrictness)2, DB::HashJoin::MapsTemplate<DB::RowRefList>>::joinRightColumns<DB::Colum...
inlined from ./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:565: unsigned long DB::HashJoinMethods<(DB::JoinKind)2, (DB::JoinStrictness)2, DB::HashJoin::MapsTemplate<DB::RowRefList>>::joinRightColu...
./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:343: unsigned long DB::HashJoinMethods<(DB::JoinKind)2, (DB::JoinStrictness)2, DB::HashJoin::MapsTemplate<DB::RowRefList>>::joinRightColumnsSwitchMult...
inlined from ./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:289: unsigned long DB::HashJoinMethods<(DB::JoinKind)2, (DB::JoinStrictness)2, DB::HashJoin::MapsTemplate<DB::RowRefList>>::joinRightColu...
./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:271: unsigned long DB::HashJoinMethods<(DB::JoinKind)2, (DB::JoinStrictness)2, DB::HashJoin::MapsTemplate<DB::RowRefList>>::switchJoinRightColumns<DB:...
./src/Interpreters/HashJoin/HashJoinMethodsImpl.h:112: DB::HashJoinMethods<(DB::JoinKind)2, (DB::JoinStrictness)2, DB::HashJoin::MapsTemplate<DB::RowRefList>>::joinBlockImpl(DB::HashJoin const&, DB::S...
src/Interpreters/HashJoin/HashJoin.cpp:1246: operator()<std::integral_constant<DB::JoinKind, (DB::JoinKind)2>, std::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)2>, std::vector<const DB::...
inlined from ./src/Interpreters/joinDispatch.h:161: operator()<std::integral_constant<int, 19> >
./base/base/../base/constexpr_helpers.h:18: bool func_wrapper<bool DB::joinDispatch<std::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsT...
inlined from ./base/base/../base/constexpr_helpers.h:24: bool static_for_impl<int, 0, bool DB::joinDispatch<std::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefLi...
./base/base/../base/constexpr_helpers.h:31: bool static_for<0, 24, bool DB::joinDispatch<std::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::...
inlined from ./src/Interpreters/joinDispatch.h:133: bool DB::joinDispatch<std::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<st...
src/Interpreters/HashJoin/HashJoin.cpp:1237: DB::HashJoin::joinScatteredBlock(DB::ScatteredBlock) @ 0x000000002bc0d35c
src/Interpreters/ConcurrentHashJoin.cpp:364: DB::ConcurrentHashJoinResult::next() @ 0x000000002ae63ce0
src/Processors/Transforms/JoiningTransform.cpp:232: DB::JoiningTransform::readExecute(DB::Chunk&) @ 0x00000000339e6cd8
src/Processors/Transforms/JoiningTransform.cpp:213: DB::JoiningTransform::transform(DB::Chunk&) @ 0x00000000339e607c
src/Processors/Transforms/JoiningTransform.cpp:138: DB::JoiningTransform::work() @ 0x00000000339e5098
src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x0000000033443510
src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x0000000033428490
src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*)
src/Processors/Executors/PipelineExecutor.cpp:565: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>::type std::_...
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::shared_p...
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: void std::__invoke_r[abi:ne210105]<void, DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB...
./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000003342ac6c
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Common/ThreadPool.cpp:801: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000001decb180
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: std::__invoke_result_impl<void, void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), T...
inlined from ./contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*...
inlined from ./contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tu...
./src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<T...
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000001dec5ffc
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: std::__invoke_result_impl<void, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>:...
inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:ne210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, voi...
./contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:ne210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (...
asan_thread_start(void*) @ 0x000000000f0bd1a8
start_thread @ 0x0000000000080398
thread_start @ 0x00000000000e9e9c
```

### PR DESCRIPTION
**Pull request by yariks5s**
## Linked issues
- fixes https://github.com/ClickHouse/clickhouse-core-incidents/issues/1566
- fixes https://github.com/ClickHouse/clickhouse-core-incidents/issues/1708

### Changelog category (leave one):
- Critical Bug Fix

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixes a logical error `Too large size (A) passed to allocator` while executing JOINs. Closes https://github.com/ClickHouse/ClickHouse/issues/92043

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03764_join_nothing_type_column_crash.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+-- Test for bug https://github.com/ClickHouse/ClickHouse/issues/92043
+SELECT DISTINCT kafkaMurmurHash(*) FROM numbers(10) y ANY RIGHT JOIN (SELECT concat('str', number) str, arrayJoin(range(number)) i, number FROM numbers(10)) AS z ON y.number = z.number;
```
Comment (vdimir) [inline tests/queries/0_stateless/03764_join_nothing_type_column_crash.sql]: Should we also add ORDER BY to avoid non-deterministic result order?

**Review by vdimir — APPROVED** [review]

File: tests/queries/0_stateless/03764_join_nothing_type_column_crash.sql (hunk 1 above)
Comment (vdimir) [reply tests/queries/0_stateless/03764_join_nothing_type_column_crash.sql]: Let's also mark as critical bugfix and backport

Comment (yariks5s) [reply tests/queries/0_stateless/03764_join_nothing_type_column_crash.sql]: Done

**Comment by yariks5s** [comment]
Tests failed because of https://github.com/ClickHouse/ClickHouse/issues/92670, https://github.com/ClickHouse/ClickHouse/issues/89823, https://github.com/ClickHouse/ClickHouse/issues/92633

**Comment by npakeer** [comment]
@yariks5s Looks like backport for 25.12 not merged. It looks like we need it to fix https://github.com/ClickHouse/clickhouse-core-incidents/issues/1708

Is it okay to merge  https://github.com/ClickHouse/clickhouse-private/pull/56194 ?
