### PR TITLE
Fix crash in REPLACE PARTITION when source table is dropped concurrently

### LINKED ISSUE #91989: SIGSEGV in IMergeTreeDataPart::clearCaches during executeReplaceRange (ReplicatedMergeTree)
### Company or project name

_No response_

### Describe what's wrong

We have been experiencing a high volume of crashes (SIGSEGV) on a cluster running ClickHouse version `25.3.5.42`. We have collected 51 crash reports across multiple hosts, all pointing to the same root cause during `ReplicatedMergeTree` background operations. The crashes tend to occur on a replica in a region that is not receiving writes, but is replicating data from a region receiving writes.

The crash occurs during the execution of `StorageReplicatedMergeTree::executeReplaceRange`. When a `MergeTreeDataPartWide` object is destroyed (via `~MergeTreeDataPartWide`), it calls `removeIfNeeded` -> `clearCaches`.

Inside `clearCaches`, the process crashes via two distinct paths. Both paths indicate that the Data Part is attempting to access the parent `MergeTreeData` (Table/Storage) object or its Context to invalidate caches, but the parent object appears to be invalid or already destroyed.

This crash occurs during rapid bursts of:

1. Insert into a temp table partition
2. Move the partition to a live table
3. Drop the partition from the temp table

```
        ALTER TABLE {destination_table}
        REPLACE PARTITION '{partition}'
        FROM {source_table}
```

Followed quickly by

```
        ALTER TABLE {source_table}
        DROP PARTITION '{partition}'
        SETTINGS alter_sync=2;
```

We have mitigated the crash by putting a `SYNC REPLICA LIGHTWEIGHT` between the two operations (and other operations that surround it, ie creating the temp table, inserting into it).

### Does it reproduce on the most recent release?

Unknown

### How to reproduce

**ClickHouse Version**
25.3.5.42

**Environment**
Linux / Kubernetes

### Expected behavior

_No response_

### Error message and/or stacktrace

**Stack Trace - Variant A (Accessing PrimaryIndexCache)**
This is the most frequent crash path. The SegFault occurs when accessing `getPrimaryIndexCache()` on the storage object.

```text
0. signalHandler(int, siginfo_t*, void*) @ 0x000000000f903eb7
1. ? @ 0x00007fb1bea34520
2. DB::MergeTreeData::getPrimaryIndexCache() const @ 0x000000001466d065
3. DB::IMergeTreeDataPart::clearCaches() @ 0x00000000145874bd
4. DB::IMergeTreeDataPart::removeIfNeeded() @ 0x0000000014587819
5. DB::MergeTreeDataPartWide::~MergeTreeDataPartWide() @ 0x000000001473d890
6. std::__shared_ptr_emplace<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription, std::allocator<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription>>::__on_zero_shared() (.1c8661b157e1c7c3f9bf8081b7f931ac) @ 0x00000000142b201a
7. std::vector<std::shared_ptr<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription>, std::allocator<std::shared_ptr<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription>>>::~vector[abi:ne190107]() @ 0x00000000141b43c1
8. DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&) @ 0x00000000141900fe
9. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x0000000014178f73
10. bool std::__function::__policy_invoker<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::StorageReplicatedMergeTree::processQueueEntry(std::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)::$_1, bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>>(std::__function::__policy_storage const*, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&) @ 0x00000000142b2a7c
11. DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x0000000014998cc7
12. DB::StorageReplicatedMergeTree::processQueueEntry(std::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x00000000141cdd3c
13. DB::ExecutableLambdaAdapter::executeStep() @ 0x000000001457cf52
14. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction() @ 0x000000001463ddf1
15. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000000f65a65b
16. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000f661183
17. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000f65798f
18. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f65ec5a
19. ? @ 0x00007fb1bea86ac3
20. ? @ 0x00007fb1beb17a04
```

**Stack Trace - Variant B (Accessing Context)**
In this variant, the crash occurs when `clearCaches` attempts to retrieve the `Context` from the storage object.

```text
0. signalHandler(int, siginfo_t*, void*) @ 0x000000000f903eb7
1. ? @ 0x00007bef1c382520
2. DB::WithContextImpl<std::shared_ptr<DB::Context>>::getContext() const @ 0x0000000012634ed1
3. DB::IMergeTreeDataPart::clearCaches() @ 0x0000000014587399
4. DB::IMergeTreeDataPart::removeIfNeeded() @ 0x0000000014587819
5. DB::MergeTreeDataPartWide::~MergeTreeDataPartWide() @ 0x000000001473d890
6. std::__shared_ptr_emplace<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription, std::allocator<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription>>::__on_zero_shared() (.1c8661b157e1c7c3f9bf8081b7f931ac) @ 0x00000000142b201a
7. std::vector<std::shared_ptr<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription>, std::allocator<std::shared_ptr<DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&)::PartDescription>>>::~vector[abi:ne190107]() @ 0x00000000141b43c1
8. DB::StorageReplicatedMergeTree::executeReplaceRange(DB::ReplicatedMergeTreeLogEntry&) @ 0x00000000141900fe
9. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x0000000014178f73
10. bool std::__function::__policy_invoker<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::StorageReplicatedMergeTree::processQueueEntry(std::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)::$_1, bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>>(std::__function::__policy_storage const*, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&) @ 0x00000000142b2a7c
11. DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x0000000014998cc7
12. DB::StorageReplicatedMergeTree::processQueueEntry(std::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x00000000141cdd3c
13. DB::ExecutableLambdaAdapter::executeStep() @ 0x000000001457cf52
14. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction() @ 0x000000001463ddf1
15. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000000f65a65b
16. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000f661183
17. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000f65798f
18. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f65ec5a
19. ? @ 0x00007bef1c3d4ac3
20. ? @ 0x00007bef1c465a04
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash in ReplicatedMergeTree when source table is dropped during REPLACE PARTITION query.

---

Closes https://github.com/ClickHouse/ClickHouse/issues/91989

I reproduced it manually with a sleep, but couldn't reproduce with integration test. I guess the timing is tight. After the fix there's nowhere to put a sleep/failpoint.

### CODE REVIEW

File: src/Storages/MergeTree/IMergeTreeDataPart.h [hunk 1]
```diff
@@ -70,6 +70,8 @@ enum class DataPartRemovalState : uint8_t
 };
 
 /// Description of the data part.
+/// Warning: `IStorage` must outlive all its `IMergeTreeDataPart`s. Whenever you hold a
+///          MergeTreeDataPartPtr you must also hold the corresponding StoragePtr.
```
Comment (tiandiwonder) [inline src/Storages/MergeTree/IMergeTreeDataPart.h]: How can we avoid the issue? Is it possible to add a check?

**Review by alexey-milovidov — APPROVED** [review]
