### PR TITLE
Fix WHERE 1=0 for external databases query

### LINKED ISSUE #33152: error when select from postgresql() where 1=0
CH 21.11.8.4

When trying to query postgresql function with condition WHERE 1=0 (common case for Tableau when it's trying to get query metadata) ch generates query with wrong syntax for postgres.
 
Any query to postgres:

```
select * from postgresql(...)
where 1=0
std::exception. Code: 1001, type: pqxx::sql_error, e.what() = ERROR: argument of WHERE must be type boolean, not type integer
```
tcpdump shows that 1=0 transforms into 0
image

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix WHERE 1=0 for external databases query. Closes https://github.com/ClickHouse/ClickHouse/issues/33152.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: src/Storages/transformQueryForExternalDatabase.cpp [hunk 1]
```diff
@@ -306,6 +306,18 @@ String transformQueryForExternalDatabase(
         throw Exception("Query contains non-compatible expressions (and external_table_strict_query=true)", ErrorCodes::INCORRECT_QUERY);
     }
 
+    auto * literal_expr = typeid_cast<ASTLiteral *>(original_where.get());
+    UInt64 value;
+    if (literal_expr && literal_expr->value.tryGet<UInt64>(value) && (value == 0 || value == 1))
+    {
+        /// WHERE 1 -> WHERE 1=1, WHERE 0 -> WHERE 1=0.
```
Comment (tavplubix) [inline src/Storages/transformQueryForExternalDatabase.cpp:313]: Ok, but what about, for example, `WHERE 42`?

Comment (kssenii) [reply src/Storages/transformQueryForExternalDatabase.cpp:313]: It will also work with this code (checked). Because at this point `WHERE expr=constant` will be either `0` or `1`.

**Comment by kssenii** [comment]
> ClickHouse special build check (actions) — 6/7 builds are OK

Not related to changes:
```
Dec 27 14:33:00 /build/build_docker/../programs/server/Server.cpp:573:17: error: 'emplace_back' is called inside a loop; consider pre-allocating the container capacity before the loop [performance-inefficient-vector-operation,-warnings-as-errors]
Dec 27 14:33:00                 metrics.emplace_back(ProtocolServerMetrics{server.getPortName(), server.currentThreads()});
Dec 27 14:33:00                 ^
Dec 27 14:33:00 114587 warnings generated.
```

> Integration tests (thread, actions) [1/4] — fail: 29
Integration tests (thread, actions) [2/4] — fail: 1

Mostly docker issues:
```
            compose.service.pull: Pulling azurite1 (mcr.microsoft.com/azure-storage/azurite:)...
E               compose.cli.verbose_proxy.proxy_callable: docker pull <- ('mcr.microsoft.com/azure-storage/azurite', tag='latest', stream=True, platform=None)
E               compose.cli.errors.log_api_error: Get "https://mcr.microsoft.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
