### PR TITLE
Weaken check for sparse columns in Block

### LINKED ISSUE #61738: Merges failing due to block structure mismatch from projection on aggregatedmergetree
**Describe what's wrong**

version: 24.1.2.5

Merges are failing with this aggregated merge tree schema. Also wondering if there is a different way of going about the projection.

example table schema:
```sql
CREATE TABLE tracing.otel_traces_aggregated_trace_id_ts_local
(
    `trace_id` String,
    `request_id` AggregateFunction(argMin, String, DateTime64(3)),
    `start` SimpleAggregateFunction(min, DateTime64(3)),
    `end` SimpleAggregateFunction(max, DateTime64(3)),
    PROJECTION projection_traces_by_id
    (
        SELECT
          trace_id,
          finalizeAggregation(request_id) AS _request_id
        ORDER BY finalizeAggregation(request_id)
    )
)
ENGINE = AggregatingMergeTree
PARTITION BY toStartOfDay(start)
ORDER BY trace_id
```

merges fail with:
```
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different columns:
finalizeAggregation(request_id) String String(size = 8192)
finalizeAggregation(request_id) String Sparse(size = 8192, String(size = 1), UInt64(size = 0)). (AMBIGUOUS_COLUMN_NAME), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c800f1b in /usr/bin/clickhouse
1. DB::Exception::Exception<std::basic_string_view<char, std::char_traits<char>>&, String, String>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type, std::type_identity<String>::type, std::type_identity<String>::type>, std::basic_string_view<char, std::char_traits<char>>&, String&&, String&&) @ 0x0000000010526e8a in /usr/bin/clickhouse
2. void DB::onError<void, std::basic_string_view<char, std::char_traits<char>>&, String, String>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type, std::type_identity<String>::type, std::type_identity<String>::type>, std::basic_string_view<char, std::char_traits<char>>&, String&&, String&&) @ 0x0000000010526d2e in /usr/bin/clickhouse
3. void DB::checkColumnStructure<void>(DB::ColumnWithTypeAndName const&, DB::ColumnWithTypeAndName const&, std::basic_string_view<char, std::char_traits<char>>, bool, int) (.llvm.8893857084970946537) @ 0x0000000010521323 in /usr/bin/clickhouse
4. DB::Block::insert(DB::ColumnWithTypeAndName) @ 0x000000001052173f in /usr/bin/clickhouse
5. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x0000000010d3e61e in /usr/bin/clickhouse
6. DB::ExpressionTransform::transform(DB::Chunk&) @ 0x0000000012bff813 in /usr/bin/clickhouse
7. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x000000000e7ccef0 in /usr/bin/clickhouse
8. DB::ISimpleTransform::work() @ 0x0000000012977af2 in /usr/bin/clickhouse
9. DB::ExecutionThreadContext::executeTask() @ 0x000000001299371a in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001298a170 in /usr/bin/clickhouse
11. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000012989928 in /usr/bin/clickhouse
12. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x0000000012998017 in /usr/bin/clickhouse
13. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x00000000129981d3 in /usr/bin/clickhouse
14. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x000000001233b6f2 in /usr/bin/clickhouse
15. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x000000001233b64b in /usr/bin/clickhouse
16. DB::MergeTask::execute() @ 0x0000000012340d99 in /usr/bin/clickhouse
17. bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTask::MergeProjectionsStage::subtasks::'lambda0'(), bool ()>>(std::__function::__policy_storage const*) @ 0x000000001234536d in /usr/bin/clickhouse
18. DB::MergeTask::MergeProjectionsStage::execute() @ 0x00000000123413ab in /usr/bin/clickhouse
19. DB::MergeTask::execute() @ 0x0000000012340d99 in /usr/bin/clickhouse
20. DB::MergePlainMergeTreeTask::executeStep() @ 0x0000000012723517 in /usr/bin/clickhouse
21. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x00000000123532c4 in /usr/bin/clickhouse
22. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c8eb0c1 in /usr/bin/clickhouse
23. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c8ee8fa in /usr/bin/clickhouse
24. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c8ed6fe in /usr/bin/clickhouse
25. ? @ 0x0000784f86d93609
26. ? @ 0x0000784f86cb8353
27. ```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed error `Block structure mismatch` in several cases with tables with sparse columns.

Fixes #61738.

### CODE REVIEW

File: tests/queries/0_stateless/03121_analyzer_filed_redefenition_in_subquery.sql [hunk 1]
```diff
@@ -28,12 +28,11 @@ FROM
 );
 
 -- query 3
--- it works with old analyzer
```
Comment (CurtizJ) [inline tests/queries/0_stateless/03121_analyzer_filed_redefenition_in_subquery.sql:31]: If it works with old analyzer, maybe it should work with new as well.

**Comment by nikitamikhaylov** [comment]
Bugfix validation check looks broken, it failed with `[with NOT_OK] Nothing to run`. While the test indeed reproduces bug on the recent master: https://fiddle.clickhouse.com/f16b8f72-49a8-4fe5-b5ce-8939879c7bf0

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
The reason for the failure is that old version is unable to start. 
```
2025.04.24 03:58:20.605221 [ 440 ] {} <Error> Application: Code: 115. DB::Exception: Unknown setting 'allow_dynamic_cache_resize'. (UNKNOWN_SETTING), Stack trace (when copying this message, always include the lines below):

0. ./ci/tmp/build/./src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f2be35b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009c73bec
2. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x0000000009c7390b
3. ./ci/tmp/build/./src/Core/BaseSettings.cpp:53: DB::BaseSettingsHelpers::throwSettingNotFound(std::basic_string_view<char, std::char_traits<char>>) @ 0x000000001215b2c3
4. ./src/Core/BaseSettings.h:629: DB::BaseSettings<DB::FileCacheSettingsTraits>::set(std::basic_string_view<char, std::char_traits<char>>, DB::Field const&) @ 0x000000001364cbf4
5. ./ci/tmp/build/./src/Interpreters/Cache/FileCacheSettings.cpp:172: DB::FileCacheSettings::loadFromConfig(Poco::Util::AbstractConfiguration const&, String const&, bool) @ 0x0000000013651536
6. ./ci/tmp/build/./src/Disks/ObjectStorages/Cached/registerDiskCache.cpp:56: std::shared_ptr<DB::IDisk> std::__function::__policy_invoker<std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::registerDiskCache(DB::DiskFactory&, bool)::$_0, std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool)>>(std::__function::__policy_storage const*, String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>&&, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&, bool, bool) (.llvm.10038708880327519270) @ 0x00000000127668d0
7. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012722f74
8. ./ci/tmp/build/./src/Disks/DiskSelector.cpp:55: DB::DiskSelector::initialize(Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::function<bool (Poco::Util::AbstractConfiguration const&, String const&, String const&)>) @ 0x000000001274b262
9. ./ci/tmp/build/./src/Interpreters/Context.cpp:5152: DB::Context::getDiskSelector(std::lock_guard<std::mutex>&) const @ 0x0000000012fed5bd
10. ./ci/tmp/build/./src/Interpreters/Context.cpp:5136: DB::Context::getDisksMap(std::lock_guard<std::mutex>&) const @ 0x0000000012fed9d6
11. ./ci/tmp/build/./src/Interpreters/Context.cpp:5131: DB::Context::getDatabaseDisk() const @ 0x0000000012fc1a63
12. ./ci/tmp/build/./src/Databases/DatabasesCommon.cpp:349: DB::DatabaseWithOwnTablesBase::DatabaseWithOwnTablesBase(String const&, String const&, std::shared_ptr<DB::Context const>) @ 0x0000000012620d9b
13. ./ci/tmp/build/./src/Databases/DatabaseMemory.cpp:24: DB::DatabaseMemory::DatabaseMemory(String const&, std::shared_ptr<DB::Context const>) @ 0x00000000125a66a8
14. ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::DatabaseCatalog::initializeAndLoadTemporaryDatabase() @ 0x00000000130bde2d
15. ./ci/tmp/build/./programs/server/Server.cpp:2436: DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000f5e0cb1
16. ./ci/tmp/build/./base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x000000001802d986
17. ./ci/tmp/build/./programs/server/Server.cpp:592: DB::Server::run() @ 0x000000000f5cb290
18. ./ci/tmp/build/./programs/server/Server.cpp:389: mainEntryClickHouseServer(int, char**) @ 0x000000000f5c83d3
19. ./ci/tmp/build/./programs/main.cpp:295: main @ 0x0000000009c6f601
20. ? @ 0x00007f776a739d90
21. ? @ 0x00007f776a739e40
22. _start @ 0x000000000698002e
 (version 25.4.1.2934 (official build))
```
