### PR TITLE
Fix sparseGram tokenizer bug in hasAny/AllTokens and tokens functions

### LINKED ISSUE #89605: Segmentation fault with `hasAllTokens` and `sparseGrams` without direct read optimizatimization
### Company or project name

_No response_

### Describe what's wrong

Running a text index query, with `sparseGrams` tokenization, with `query_plan_direct_read_from_text_index=0`, crashes.

Fiddle: https://fiddle.clickhouse.com/67de3ab8-265c-4799-81fa-9a65d51b3994
```
SET allow_experimental_full_text_index;

DROP TABLE IF EXISTS logs;
CREATE TABLE logs
(
  message String,
  INDEX ix_text_message message TYPE text(tokenizer='sparseGrams')
)
ENGINE = MergeTree
ORDER BY message
AS SELECT *
FROM url('https://raw.githubusercontent.com/dwyl/english-words/refs/heads/master/words_alpha.txt');

SELECT *
FROM logs
WHERE hasAllTokens(message, sparseGrams('zymosimeter'))
SETTINGS use_skip_indexes_on_data_read=1, query_plan_direct_read_from_text_index=0;
```

### Does it reproduce on the most recent release?

No

### How to reproduce

Version: head = 25.11.1.1444 (in fiddle), also 25.11.1.1156 (official build, downloaded from CI)

The crash also reproduces with `use_skip_indexes_on_data_read=0`, so it seems independent of streaming skip indexes.

It does *not* reproduce with `query_plan_direct_read_from_text_index=1`.

It does *not* reproduce with `splitByNonAlpha` or `ngrams(3)` tokenizers, either.

### Expected behavior

I expect to retrieve a single matching row, `zymosimeter`, and this happens when streaming skip indexes is enabled.

### Error message and/or stacktrace

From the top of Fiddle:
```
[81cf17506463] 2025.11.05 21:34:31.859232 [ 81 ] <Fatal> BaseDaemon: ########################################
[81cf17506463] 2025.11.05 21:34:31.859324 [ 81 ] <Fatal> BaseDaemon: (version 25.11.1.1444 (official build), build id: F66EE4D00E541E166C8090E2C0509EF87B518B31, git hash: 0c274f208fcbd413277aba90ecacaf440096a491) (from thread 773) (query_id: 5cbcbafd-c441-4c02-8b07-e21514b9dde6) (query: SELECT *
FROM logs
WHERE hasAllTokens(message, sparseGrams('zymosimeter'))
SETTINGS use_skip_indexes_on_data_read=1, query_plan_direct_read_from_text_index=0;) Received signal Segmentation fault (11)
[81cf17506463] 2025.11.05 21:34:31.859396 [ 81 ] <Fatal> BaseDaemon: Address: 0x729b5ebf4000. Access: read. Attempted access has violated the permissions assigned to the memory area.
[81cf17506463] 2025.11.05 21:34:31.859442 [ 81 ] <Fatal> BaseDaemon: Stack trace: 0x000000001faffb9a 0x000000001faffac7 0x000000001a04e801 0x000000001a045dce 0x000000001a044e7d 0x0000000016b079fa 0x0000000016aff835 0x0000000016b00d5e 0x0000000016b0262a 0x0000000016b01ed7 0x0000000018a2d099 0x000000001aaeb1e1 0x000000001aaeb0d4 0x000000001652d393 0x000000001a7e73da 0x000000001a808582 0x000000001a7fa99b 0x000000001a7fe703 0x0000000013feeaeb 0x0000000013ff5f66 0x0000000013feba12 0x0000000013ff369a 0x0000729d6ad96ac3 0x0000729d6ae27a74
[81cf17506463] 2025.11.05 21:34:31.859521 [ 81 ] <Fatal> BaseDaemon: 2. absl::lts_20250512::hash_internal::LowLevelHashLenGt32(void const*, unsigned long, unsigned long, unsigned long const*) @ 0x000000001faffb9a
[81cf17506463] 2025.11.05 21:34:31.859580 [ 81 ] <Fatal> BaseDaemon: 3. absl::lts_20250512::hash_internal::MixingHashState::CombineLargeContiguousImpl64(unsigned long, unsigned char const*, unsigned long) @ 0x000000001faffac7
[81cf17506463] 2025.11.05 21:34:31.859645 [ 81 ] <Fatal> BaseDaemon: 4. absl::lts_20250512::container_internal::raw_hash_set<absl::lts_20250512::container_internal::FlatHashMapPolicy<String, unsigned long>, absl::lts_20250512::container_internal::StringHash, absl::lts_20250512::container_internal::StringEq, std::allocator<std::pair<String const, unsigned long>>>::iterator absl::lts_20250512::container_internal::raw_hash_set<absl::lts_20250512::container_internal::FlatHashMapPolicy<String, unsigned long>, absl::lts_20250512::container_internal::StringHash, absl::lts_20250512::container_internal::StringEq, std::allocator<std::pair<String const, unsigned long>>>::find<std::basic_string_view<char, std::char_traits<char>>>(std::basic_string_view<char, std::char_traits<char>> const&) @ 0x000000001a04e801
[81cf17506463] 2025.11.05 21:34:31.859721 [ 81 ] <Fatal> BaseDaemon: 5. void DB::(anonymous namespace)::execute<DB::traits::HasAllTokensTraits>(COW<DB::IColumn>::immutable_ptr<DB::IColumn>, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&, unsigned long, DB::ITokenExtractor const*, absl::lts_20250512::flat_hash_map<String, unsigned long, absl::lts_20250512::container_internal::StringHash, absl::lts_20250512::container_internal::StringEq, std::allocator<std::pair<String const, unsigned long>>> const&) @ 0x000000001a045dce
[81cf17506463] 2025.11.05 21:34:31.859773 [ 81 ] <Fatal> BaseDaemon: 6. DB::FunctionHasAnyAllTokens<DB::traits::HasAllTokensTraits>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001a044e7d
[81cf17506463] 2025.11.05 21:34:31.859826 [ 81 ] <Fatal> BaseDaemon: 7. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000016b079fa
[81cf17506463] 2025.11.05 21:34:31.859874 [ 81 ] <Fatal> BaseDaemon: 8. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000016aff835
[81cf17506463] 2025.11.05 21:34:31.859914 [ 81 ] <Fatal> BaseDaemon: 9. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000016b00d5e
[81cf17506463] 2025.11.05 21:34:31.859961 [ 81 ] <Fatal> BaseDaemon: 10. DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000016b0262a
[81cf17506463] 2025.11.05 21:34:31.860008 [ 81 ] <Fatal> BaseDaemon: 11. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000016b01ed7
[81cf17506463] 2025.11.05 21:34:31.860060 [ 81 ] <Fatal> BaseDaemon: 12. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const @ 0x0000000018a2d099
[81cf17506463] 2025.11.05 21:34:31.860127 [ 81 ] <Fatal> BaseDaemon: 13. DB::FilterTransform::doTransform(DB::Chunk&) @ 0x000000001aaeb1e1
[81cf17506463] 2025.11.05 21:34:31.860174 [ 81 ] <Fatal> BaseDaemon: 14. DB::FilterTransform::transform(DB::Chunk&) @ 0x000000001aaeb0d4
[81cf17506463] 2025.11.05 21:34:31.860230 [ 81 ] <Fatal> BaseDaemon: 15. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x000000001652d393
[81cf17506463] 2025.11.05 21:34:31.860279 [ 81 ] <Fatal> BaseDaemon: 16. DB::ISimpleTransform::work() @ 0x000000001a7e73da
[81cf17506463] 2025.11.05 21:34:31.860325 [ 81 ] <Fatal> BaseDaemon: 17. DB::ExecutionThreadContext::executeTask() @ 0x000000001a808582
[81cf17506463] 2025.11.05 21:34:31.860398 [ 81 ] <Fatal> BaseDaemon: 18. DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001a7fa99b
[81cf17506463] 2025.11.05 21:34:31.860446 [ 81 ] <Fatal> BaseDaemon: 19. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001a7fe703
[81cf17506463] 2025.11.05 21:34:31.860494 [ 81 ] <Fatal> BaseDaemon: 20. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000013feeaeb
[81cf17506463] 2025.11.05 21:34:31.860550 [ 81 ] <Fatal> BaseDaemon: 21. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013ff5f66
[81cf17506463] 2025.11.05 21:34:31.860595 [ 81 ] <Fatal> BaseDaemon: 22. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013feba12
[81cf17506463] 2025.11.05 21:34:31.860642 [ 81 ] <Fatal> BaseDaemon: 23. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000013ff369a
[81cf17506463] 2025.11.05 21:34:31.860694 [ 81 ] <Fatal> BaseDaemon: 24. ? @ 0x0000000000094ac3
[81cf17506463] 2025.11.05 21:34:31.860738 [ 81 ] <Fatal> BaseDaemon: 25. ? @ 0x0000000000125a74
[81cf17506463] 2025.11.05 21:34:32.034914 [ 81 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: AB2753EF293EB15CEB49CC456D198B98)
[81cf17506463] 2025.11.05 21:34:33.136425 [ 81 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[81cf17506463] 2025.11.05 21:34:33.136770 [ 81 ] <Fatal> BaseDaemon: Changed settings: use_skip_indexes_on_data_read = true, allow_experimental_full_text_index = true, query_plan_direct_read_from_text_index = false, output_format_pretty_color = 0, output_format_pretty_grid_charset = 'ASCII'
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ahmadov**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix `hasAnyTokens`, `hasAllTokens` and `tokens` functions concurrent executions with the `sparseGrams` tokenizer. Resolves #89605

### Details

The bug is only limited to the `sparseGram` tokenizer. The sparseGram tokenizer stores an internal state which is modified during the execution.

This led to an error when the functions are running concurrently, because the internal state of the sparseGram tokenizer is not thread-safe.

This change fixes that by cloning the sparseGram tokenizer for each function call to avoid sharing an internal state between runs.

Fixes #89605

### CODE REVIEW

**Comment by EmeraldShift** [comment]
I don't know much about this implementation of `sparseGrams`, so I'm curious: why does it need a mutable internal state? Is the copying of that state any concern for memory usage?

**Comment by PedroTadim** [comment]
Should this PR be backported?

**Review by george-larionov — APPROVED** [review]
It LGTM as a temporary fix while we decide how to fix the underlying issue.

**Comment by george-larionov** [comment]
> Should this PR be backported?

Surprisingly there seems to be no issue in [25.10](https://fiddle.clickhouse.com/4461a44b-1fcf-4259-a41b-87c0bb262009) and in 25.9 sparseGrams was not allowed as a tokenizer (i think it didn't exist). So I think no backport needed. @ahmadov ?

**Comment by ahmadov** [comment]
> > Should this PR be backported?
> 
> Surprisingly there seems to be no issue in [25.10](https://fiddle.clickhouse.com/4461a44b-1fcf-4259-a41b-87c0bb262009) and in 25.9 sparseGrams was not allowed as a tokenizer (i think it didn't exist). So I think no backport needed. @ahmadov ?

@george-larionov that's interesting, it does not show any result with 25.10, but there should a [single match](https://fiddle.clickhouse.com/cdc64093-0366-4b27-8762-5e52b08b3c57). But I managed to reproduce with the `tokens` function in 25.10: https://fiddle.clickhouse.com/af12cfb9-a92f-414a-b4bd-0fa8ac5ee965

However, if I set the concurrency limit to 1, it does not produce the error anymore: https://fiddle.clickhouse.com/9495b543-a1b1-470a-a0ca-c6d536e0c7f8

**Comment by ahmadov** [comment]
> Should this PR be backported?

@PedroTadim 25.10 is already released and the full-text index is still an experimental feature. So, I'm not totally sure if we need to patch the release version. Did you have the similar experience with other experimental features?

File: src/Functions/tokens.cpp [hunk 1]
```diff
@@ -112,10 +112,26 @@ class ExecutableFunctionTokens : public IExecutableFunction
         if (input_rows_count == 0)
             return ColumnArray::create(std::move(col_result), std::move(col_offsets));
 
-        if (const auto * column_string = checkAndGetColumn<ColumnString>(col_input.get()))
-            executeImpl(*token_extractor, *column_string, *col_offsets, input_rows_count, *col_result);
-        else if (const auto * column_fixed_string = checkAndGetColumn<ColumnFixedString>(col_input.get()))
-            executeImpl(*token_extractor, *column_fixed_string, *col_offsets, input_rows_count, *col_result);
+        const auto execute_with_tokenizer = [&](const ITokenExtractor & extractor)
```
Comment (Ergus) [inline src/Functions/tokens.cpp]: We will expand the logics of this `execute_with_tokenizer` very soon, so please make this a real function to not obscure the code of `executeImpl`. (This will also avoid the lambda ;p)

File: src/Functions/tokens.cpp [hunk 2]
```diff
@@ -112,10 +112,26 @@ class ExecutableFunctionTokens : public IExecutableFunction
...
+        {
+            if (const auto * column_string = checkAndGetColumn<ColumnString>(col_input.get()))
+                executeImpl(extractor, *column_string, *col_offsets, input_rows_count, *col_result);
+            else if (const auto * column_fixed_string = checkAndGetColumn<ColumnFixedString>(col_input.get()))
+                executeImpl(extractor, *column_fixed_string, *col_offsets, input_rows_count, *col_result);
+        };
+
+        if (token_extractor->getType() == ITokenExtractor::Type::SparseGram)
```
Comment (Ergus) [inline src/Functions/tokens.cpp:115]: It is not a suggestion, but a comment to consider.

If the `clone()` operation is not intended to be expensive, we could always copy the tokenizer locally and save the if-else logic. The idea behind it is that any tokenizer "expensive to clone" probably will store an internal state and will require this same logics right?

Of course keeping this comment for the future.

**Review by Ergus — APPROVED** [review]
Just added a comment

**Comment by ahmadov** [comment]
Stataless test failed build: https://github.com/ClickHouse/ClickHouse/issues/89106

**Comment by rschu1ze** [comment]
Thanks for fixing this. The fix copies the internal state once per processed chunk ... which is relatively expensive as SparseGramsImpl is quite large. There are two alternatives:

- Instantiate hasAny/AllTokens and hasTokens once per query thread (right now, the same function object exists per query). That's a bigger refactoring of the query execution and it would only benefit the few text search functions with tha sparse grams tokenizer (all other SQL functions are stateless, the UUIDv7 functions are the only exception I could find).
- Add optional locking to SparseGramTokenExtractor. Since this is a low-level function, this would be conceptually quite ugly. It would also mean that tokenization is now single-threaded regardless max_threads.

Long story short, in my view we can keep this PR as is (George [mentioned](https://github.com/ClickHouse/ClickHouse/pull/89665#pullrequestreview-3435184895) it is a workaround).

**Comment by Ergus** [comment]
If it is possible to do it per/thread and still get correct results, the most efficient approach will be to use a static thread local copy. It will be copied only once per thread and the execution will stay lock-free

**Comment by rschu1ze** [comment]
Hmm, this will probably cause wrong results (not sure). Anyways, let's not overoptimize as long as we don't see sparseGrams as a hotspot in a CPU profile.
