### PR TITLE
Fix Iceberg mutation crash: unwrap LowCardinality/Nullable before Avro serialization

### LINKED ISSUE #101916: Iceberg Logical error: 'Bad cast from type DB::ColumnLowCardinality to DB::ColumnString'
### Describe the bug

Easy to reproduce. cc @Desel72 could this be related to recent changes?

### How to reproduce

```sql
CREATE TABLE t0 (c0 Int) ENGINE = IcebergLocal(local, path = '/var/lib/clickhouse/user_files/lakehouses/t0', format = 'Avro');
INSERT INTO TABLE t0 (c0) VALUES (1);
ALTER TABLE t0 UPDATE c0 = 1 WHERE TRUE;
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Bad cast from type DB::ColumnLowCardinality to DB::ColumnString'.
<Fatal> : Format string: 'Bad cast from type {} to {}'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113:14: Poco::Exception::Exception(String&&, int) @ 0x000000002349f0f3
1. src/Common/Exception.cpp:139:7: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137c4ae9
2. src/Common/Exception.h:171:100: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c7805d4
3. src/Common/Exception.h:57:54: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c7800d1
4. src/Common/Exception.h:189:77: DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000c77e606
5. src/Common/assert_cast.cpp:15:11: throwBadAssertCast(std::type_info const&, std::type_info const&) @ 0x00000000138defa7
6. src/Common/assert_cast.h:43:5: void std::__function::__policy_func<void (DB::IColumn const&, unsigned long, avro::Encoder&)>::__call_func[abi:se210105]<DB::AvroSerializer::createSchemaWithSerializeFn(std::shared_ptr<DB::IDataType const> const&, unsigned long&, String const&)::$_15>(std::__function::__policy_storage const*, DB::IColumn const&, unsigned long, avro::Encoder&) @ 0x000000001c677388
7. contrib/llvm-project/libcxx/include/__functional/function.h:508:12: ? @ 0x000000001c67327f
8. src/Processors/Formats/Impl/AvroRowOutputFormat.cpp:601:16: DB::AvroRowOutputFormat::write(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) @ 0x000000001c673909
9. src/Processors/Formats/IRowOutputFormat.cpp:33:9: DB::IRowOutputFormat::consume(DB::Chunk) @ 0x000000001c612ecc
10. src/Processors/Formats/IOutputFormat.cpp:153:5: DB::IOutputFormat::write(DB::Block const&) @ 0x000000001c60f72f
11. src/Storages/ObjectStorage/DataLakes/Iceberg/Mutations.cpp:241:53: DB::Iceberg::writeDataFiles(DB::MutationCommands const&, std::shared_ptr<DB::Context const>, std::shared_ptr<DB::StorageInMemoryMetadata const>, DB::StorageID, std::shared_ptr<DB::IObjectStorage>, String, DB::FileNamesGenerator&, DB::Iceberg::IcebergPathResolver const&, std::optional<DB::FormatSettings> const&, std::optional<DB::ChunkPartitioner>&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object>>) @ 0x00000000171af655
12. src/Storages/ObjectStorage/DataLakes/Iceberg/Mutations.cpp:611:31: DB::Iceberg::mutate(DB::MutationCommands const&, std::shared_ptr<DB::Context const>, std::shared_ptr<DB::StorageInMemoryMetadata const>, DB::StorageID, std::shared_ptr<DB::IObjectStorage>, DB::DataLakeStorageSettings const&, DB::Iceberg::PersistentTableComponents const&, String const&, std::optional<DB::FormatSettings> const&, std::shared_ptr<DataLake::ICatalog>) @ 0x00000000171ac241
13. src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp:586:5: DB::IcebergMetadata::mutate(DB::MutationCommands const&, std::shared_ptr<DB::StorageObjectStorageConfiguration>, std::shared_ptr<DB::Context const>, DB::StorageID const&, std::shared_ptr<DB::StorageInMemoryMetadata const>, std::shared_ptr<DataLake::ICatalog>, std::optional<DB::FormatSettings> const&) @ 0x000000001713280c
14. src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h:154:27: DB::DataLakeConfiguration<DB::StorageLocalConfiguration, DB::IcebergMetadata>::mutate(DB::MutationCommands const&, std::shared_ptr<DB::Context const>, DB::StorageID const&, std::shared_ptr<DB::StorageInMemoryMetadata const>, std::shared_ptr<DataLake::ICatalog>, std::optional<DB::FormatSettings> const&) @ 0x000000001570a976
15. src/Storages/ObjectStorage/StorageObjectStorage.cpp:781:20: DB::StorageObjectStorage::mutate(DB::MutationCommands const&, std::shared_ptr<DB::Context const>) @ 0x0000000016fdd4c7
16. src/Interpreters/InterpreterAlterQuery.cpp:303:24: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x0000000018ad73c1
17. src/Interpreters/InterpreterAlterQuery.cpp:345:16: DB::InterpreterAlterQuery::execute() @ 0x0000000018ad346e
18. src/Interpreters/executeQuery.cpp:1815:40: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x0000000018ee1178
19. src/Interpreters/executeQuery.cpp:2203:11: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018edb1e3
20. src/Server/TCPHandler.cpp:823:68: DB::TCPHandler::runImpl() @ 0x000000001c4e6eb8
21. src/Server/TCPHandler.cpp:2974:9: DB::TCPHandler::run() @ 0x000000001c503fe4
22. base/poco/Net/src/TCPServerConnection.cpp:40:3: Poco::Net::TCPServerConnection::start() @ 0x000000002350658e
23. base/poco/Net/src/TCPServerDispatcher.cpp:115:42: Poco::Net::TCPServerDispatcher::run() @ 0x0000000023506ad2
24. base/poco/Foundation/src/ThreadPool.cpp:205:14: Poco::PooledThread::run() @ 0x00000000234d147f
25. base/poco/Foundation/src/Thread_POSIX.cpp:341:27: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000234cf8cf
26. start_thread @ 0x000000000009caa4
27. clone3 @ 0x0000000000129c6c
```

### PR DESCRIPTION
**Pull request by Daedalus-Icarus**
The position delete file writer in Iceberg mutations crashed because virtual columns `_iceberg_metadata_file_path` (`LowCardinality(String)`) and `_row_number` (`Nullable(Int64)`) arrived from the pipeline with wrapper types, but the Avro serializer was built from a sample block with plain `String` and `Int64`. The `assert_cast` inside the serializer then failed.

Unwrap `LowCardinality` from `_iceberg_metadata_file_path` and `Nullable` from `_row_number` in the DELETE path. Also strip `LowCardinality` from data blocks in the UPDATE path via `getNonVirtualColumns`.

Closes https://github.com/ClickHouse/ClickHouse/issues/101916

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash in `IcebergLocal` `ALTER TABLE ... UPDATE` when using Avro format, caused by `LowCardinality`/`Nullable` wrapper types not being unwrapped before serialization.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

No documentation changes needed — this is a bug fix.

### Version info
- Merged into: `26.4.1.873`

### CODE REVIEW

**Comment by Desel72** [comment]
Hi @PedroTadim Can you review this PR?

File: src/Storages/ObjectStorage/DataLakes/Iceberg/Mutations.cpp [hunk 1]
```diff
@@ -278,7 +295,9 @@ static std::optional<WriteDataFilesResult> writeDataFiles(
             if (block.rows() == 0)
                 continue;
 
-            auto data_block = getNonVirtualColumns(block);
+            /// Strip virtual columns and unwrap LowCardinality to ensure the
+            /// block types are compatible with the Avro serializer schema.
+            auto data_block = getNonVirtualColumns(block, /*remove_low_cardinality=*/ true);
```
Comment (alesapin) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/Mutations.cpp:300]: Not sure that it's the only place we need to fix this way, but LGTM

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Unit tests are impossible to investigate now, fix is pending, overriding.

**Comment by Desel72** [comment]
Thanks @alesapin
