### PR TITLE
Disallow arrayjoin in mutations

### LINKED ISSUE #42637: `arrayJoin` in mutation can lead to logical error `Trying to get non existing mark 2, while size is 2`
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/42463/4645d465b12013d99d88956020034cbfa47d9455/fuzzer_astfuzzerubsan//server.log

**How to reproduce**
```
CREATE TABLE test_wide_nested (`id` Int, `info.id` Array(Int), `info.name` Array(String), `info.age` Array(Int)) ENGINE = MergeTree ORDER BY tuple() SETTINGS min_bytes_for_wide_part = 0

INSERT INTO test_wide_nested SELECT number, [number, number + 1], ['aa', 'bb'], [number, number * 2] FROM numbers(5)

ALTER TABLE test_wide_nested UPDATE `info.id` = [100, 200, 300], `info.age` = [10, 20, 30], `info.name` = ['a', 'b', 'c'] WHERE arrayJoin([100, -2147483647, NULL]) = id
```

(note: it is not instantly reproducible, needs more investigation)

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
Changelog category (leave one):
* Bug-fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disallow arrayjoin in mutations closes #42637
Implementation:
* Added a new parameter to ActionsVisitor::Data disallow_arrayjoin, which is set by MutationsIterator when it appends expression.
* ActionsVisitor uses disallow_arrayjoin and throws error when its used with mutations. Testing:
* Added test for the same 02504_disallow_arrayjoin_in_mutations.sql.

### CODE REVIEW

File: src/Interpreters/MutationsInterpreter.cpp [hunk 1]
```diff
@@ -861,7 +861,7 @@ ASTPtr MutationsInterpreter::prepareInterpreterSelectQuery(std::vector<Stage> &
         {
             if (!actions_chain.steps.empty())
                 actions_chain.addStep();
-            stage.analyzer->appendExpression(actions_chain, ast, dry_run);
+            stage.analyzer->appendExpression(actions_chain, ast, dry_run, true /* disallow_arrayJoin */);
```
Comment (KochetovNicolai) [inline src/Interpreters/MutationsInterpreter.cpp:864]: I would prefer not to add a new flag to ExpressionAnalyzer.
There is a method `ActionsDAG::hasArrayJoin`.
I would rather add this check to `MutationsInterpreter::addStreamsForLaterStages`. There is an inner loop where we iterate over all stages, we can add a check there.

Comment (SmitaRKulkarni) [reply src/Interpreters/MutationsInterpreter.cpp]: this approach is indeed better. addressed it, thanks.

**Review by KochetovNicolai — APPROVED** [review]
