### PR TITLE
Fix crash in index definition containing sql udf

### LINKED ISSUE #62134: Crash on CREATE TABLE with index using sql udf
schemas of objects
```
CREATE FUNCTION test_func_1 AS (a, b, c) -> ((a + b) + c);

CREATE TABLE default.t4_2
(
  `col1` Int64 NOT NULL COMMENT 'test',
  `col2` Float64 NOT NULL,
  `col3` Int64 NOT NULL,
  INDEX ind4 test_func_1(col1, col3, col1) TYPE set(51) GRANULARITY 5
)
ENGINE = MergeTree
ORDER BY col1
SETTINGS index_granularity = 8192;
```

when i try create table with index, which call user function server is fall while create table

ClickHouse version 23.12.2.59

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

- Fix crash on `CREATE TABLE` with `INDEX` containing SQL UDF in expression, close https://github.com/ClickHouse/ClickHouse/issues/62134

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 076c140569f662147ee335838dc9e0e449c21aff with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62225/076c140569f662147ee335838dc9e0e449c21aff/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
> Stateful tests (release, ParallelReplicas) — fail: 1, passed: 129, skipped: 5 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62225/2c569b0d4645c1945bc420fb70160c331d81e51b/stateful_tests__release__parallelreplicas_.html)

`00065_loyalty_with_storage_join` https://github.com/ClickHouse/ClickHouse/issues/62252

> Stateless tests (msan) [1/6] — fail: 1, passed: 1028, skipped: 6 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62225/2c569b0d4645c1945bc420fb70160c331d81e51b/stateless_tests__msan__[1_6].html)

? `02735_parquet_encoder` timed out (but normally test duration is [reasonable](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHF1YW50aWxlcygwLjUsMC45LDAuOTkpKHJvdW5kKHRlc3RfZHVyYXRpb25fbXMgLyAxMDAwLCAyKSkgYXMgZHVyCiAgICBGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDcgREFZCiAgICBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwIE9SIG5vdCBvbmx5X21hc3RlcikKICAgIEFORCBjaGVja19uYW1lIGxpa2UgICclbXNhbiUnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMjczNV9wYXJxdWV0X2VuY29kZXIlJwoKKQo=))

> Stateless tests (release) — fail: 1, passed: 6293, skipped: 11 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62225/2c569b0d4645c1945bc420fb70160c331d81e51b/stateless_tests__release_.html)

https://github.com/ClickHouse/ClickHouse/issues/57418

File: src/Interpreters/InterpreterCreateIndexQuery.cpp [hunk 1]
```diff
@@ -39,12 +39,12 @@ BlockIO InterpreterCreateIndexQuery::execute()
...
     }
     // Noop if allow_create_index_without_type = true. throw otherwise
-    if (!create_index.index_decl->as<ASTIndexDeclaration>()->type)
+    if (!create_index.index_decl->as<ASTIndexDeclaration>()->getType())
     {
         if (!current_context->getSettingsRef().allow_create_index_without_type)
         {
             throw Exception(ErrorCodes::INCORRECT_QUERY, "CREATE INDEX without TYPE is forbidden."
-                " SET allow_create_index_without_type=1 to ignore this statements.");
+                " SET allow_create_index_without_type=1 to ignore this statements");
```
Comment (novikd) [inline src/Interpreters/InterpreterCreateIndexQuery.cpp:47]: Why did you remove the period?

**Review by novikd — APPROVED** [review]
LGTM

File: src/Interpreters/InterpreterCreateIndexQuery.cpp (hunk 1 above)
Comment (vdimir) [reply src/Interpreters/InterpreterCreateIndexQuery.cpp:47]: Generally we do need to put in errors, because some context may be added to the message, and period is added anyway:

```
:) CREATE INDEX idx_tab1_0 on tab1 (col0);

CREATE INDEX idx_tab1_0 ON tab1 col0 GRANULARITY 1

Query id: 526b2cfd-aff6-4ad4-8309-ad312ef5aed2


Elapsed: 0.001 sec. 

Received exception from server (version 24.4.1):
Code: 80. DB::Exception: Received from localhost:9000. DB::Exception: CREATE INDEX without TYPE is forbidden. SET allow_create_index_without_type=1 to ignore this statements.. (INCORRECT_QUERY)
```
