### PR TITLE
Fix unit test `FindSymbols.RunTimeNeedle` on ARM

### LINKED ISSUE #73011: Failure in Unit tests running on ARM
```
2024-12-10T11:42:57.9472113Z src/Common/tests/gtest_find_symbols.cpp:141: Failure
2024-12-10T11:42:57.9472777Z Expected: find_first_symbols(long_haystack, SearchSymbols("ABCDEFIJKLMNOPQRSTUVWXYZacfghijkmnpqstuvxz")) throws an exception.
2024-12-10T11:42:57.9473366Z   Actual: it doesn't.
2024-12-10T11:42:57.9473501Z 
2024-12-10T11:42:57.9473613Z [  FAILED  ] FindSymbols.RunTimeNeedle (0 ms)
```

ARM+ASAN test binary can be found in this [report](https://clickhouse-builds.s3.amazonaws.com/reports/json.html?PR=72422&sha=06c956f2bd4e5226c5c044cb2d0c3a859d0f585c&name_0=PR&name_1=Build+%28arm_asan%29&name_2=Unit+Tests)

### PR DESCRIPTION
**Pull request by harishisnow**
Resolves #73011

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 537b0047d84fb9b002984a6117d79001e66f47cf with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75182/537b0047d84fb9b002984a6117d79001e66f47cf/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d99795b7636b6542a860ef2144283943d9f882f8/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: base/base/find_symbols.h [hunk 1]
```diff
@@ -59,6 +61,12 @@ struct SearchSymbols
         memcpy(tmp_safety_buffer, str.data(), str.size());
 
         simd_vector = _mm_loadu_si128(reinterpret_cast<const __m128i *>(tmp_safety_buffer));
+#endif
+#if defined(__aarch64__) && defined(__ARM_NEON)
```
Comment (rschu1ze) [inline base/base/find_symbols.h:65]: The failing unit test does this:

```cpp
// Assert big haystack is not accepted and exception is thrown
ASSERT_ANY_THROW(find_first_symbols(long_haystack, SearchSymbols("ABCDEFIJKLMNOPQRSTUVWXYZacfghijkmnpqstuvxz")));
```

and it expects to get the exception in l. 56 (ASSERT_TNY_THROW).

Thoughts:
- l. 56 is there because of l. 61. No similar memcpy happens in the ARM case, why then throw an exception for too-long SearchSymbols?
- If we apply the suggested fix for ARM, that would still not fix RISC-V, LoongArch and whateverelse !x86 / !ARM architectures.

I think it's better to rephrase the unit test code to something like this

```cpp
#if defined (__SSE4_2__)
// (*)
ASSERT_ANY_THROW(find_first_symbols(long_haystack, SearchSymbols("ABCDEFIJKLMNOPQRSTUVWXYZacfghijkmnpqstuvxz")));
#else
find_first_symbols(long_haystack, SearchSymbols("ABCDEFIJKLMNOPQRSTUVWXYZacfghijkmnpqstuvxz")); /// <-- (**)
```

(*) Here goes a comment why SSE4.2 has special handling
(**) Would be nice to validate the returned result here.

Btw., I don't like the `tmp_safety_buffer` thing (l. 61) and the size check at all (it makes the code less portable) but it probably exists for alignment reasons.

Comment (harishisnow) [reply base/base/find_symbols.h:65]: Thanks for the comments! 
I will take a look and make the necessary changes.

Comment (harishisnow) [reply base/base/find_symbols.h]: I have incorporated the review comments, please review!

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
ClickHouse Integration tests (tsan) [3/6]:
- test_storage_nats/test.py::test_row_based_formats: #75400

**Comment by harishisnow** [comment]
Thanks for the suggestions/inputs and help!
