### PR TITLE
Fix 'Cannot read from file:' while running client in a background

### LINKED ISSUE #47636: run INSERT INTO t values in background error CANNOT_READ_FROM_FILE_DESCRIPTOR
clickhouse version:22.8
system:ubuntu20.04

create table t (a int) engine=MergeTree order by a;
quit
nohup clickhouse client -q 'insert into t values(1)'

check nohup.out:
Code: 74. DB::ErrnoException: Cannot read from file: (fd = 0), errno: 9, strerror: Bad file descriptor: (in query: insert into t values(1)). (CANNOT_READ_FROM_FILE_DESCRIPTOR)

Looks like: run insert values x in background but cannot get x.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix error 'Cannot read from file' during insert query in client unning in a background. Closes https://github.com/ClickHouse/ClickHouse/issues/47636

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit ffa9c54bb0404fd05d6496028460b9b43825bd15 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55976/ffa9c54bb0404fd05d6496028460b9b43825bd15/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6627746661">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55976/ffa9c54bb0404fd05d6496028460b9b43825bd15/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -1474,6 +1475,23 @@ void ClientBase::processInsertQuery(const String & query_to_execute, ASTPtr pars
     }
 }
 
+namespace
+{
+    bool isStdinNotEmptyAndValid(ReadBufferFromFileDescriptor & std_in)
```
Comment (SmitaRKulkarni) [inline src/Client/ClientBase.cpp:1480]: Maybe we should add the check here as well 
https://github.com/ClickHouse/ClickHouse/blob/a9960a146535b976a69939f53190a1d941a4f698/src/Client/ClientBase.cpp#L1438  ?

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM
