### PR TITLE
Fix `TopK`/`TopKWeighted` merging

### LINKED ISSUE #73507: AggregatingMergeTree topK merging across buckets has unexpected results
**Company or project name**
Company is on Clickhouse Cloud (LangChain). 

**Describe the unexpected behaviour**
TopK not merging correctly across different aggregation buckets when using AggregatedMergeTree.  

**How to reproduce**
https://fiddle.clickhouse.com/9b4a0d4f-9ec4-4689-8b75-392a0ccdb7bb

```
CREATE TABLE topk_test
(
    tenant_id UUID,
    hour DateTime,
    top_items AggregateFunction(topK(10), String)
)
ENGINE = AggregatingMergeTree()
ORDER BY (tenant_id, hour);


INSERT INTO topk_test
SELECT
    '00000000-0000-0000-0000-000000000000' AS tenant_id,
    toDateTime('2024-12-14 06:00:00') AS hour,
    topKState(10)(item)
FROM (
    SELECT arrayJoin(['a','a','a','b','b','b','c','c','c','d','d','e','e']) AS item
);

INSERT INTO topk_test
SELECT
    '00000000-0000-0000-0000-000000000000' AS tenant_id,
    toDateTime('2024-12-14 07:00:00') AS hour,
    topKState(10)(item)
FROM (
    SELECT arrayJoin(['f','f','f','g','g','g','h','h','h','d','d','e','e']) AS item
);

INSERT INTO topk_test_4
SELECT
    '00000000-0000-0000-0000-000000000000' AS tenant_id,
    toDateTime('2024-12-14 08:00:00') AS hour,
    topKState(10)(item)
FROM (
    SELECT arrayJoin(['i','i','i','j','j','j','k','k','k','d','d','e','e']) AS item
);

INSERT INTO topk_test
SELECT
    '00000000-0000-0000-0000-000000000000' AS tenant_id,
    toDateTime('2024-12-14 09:00:00') AS hour,
    topKState(10)(item)
FROM (
    SELECT arrayJoin(['l','l','l','m','m','m','n','n','n','d','d','e','e']) AS item
);

INSERT INTO topk_test
SELECT
    '00000000-0000-0000-0000-000000000000' AS tenant_id,
    toDateTime('2024-12-14 10:00:00') AS hour,
    topKState(10)(item)
FROM (
    SELECT arrayJoin(['z','z','z','w','w','w','y','y','y','d','d','e','e']) AS item
);

INSERT INTO topk_test
SELECT
    '00000000-0000-0000-0000-000000000000' AS tenant_id,
    toDateTime('2024-12-14 11:00:00') AS hour,
    topKState(10)(item)
FROM (
    SELECT arrayJoin(['i','i','i','j','j','j','k','k','k','d','d','e','e']) AS item
);

SELECT
    hour,
    topKMerge(10)(top_items) AS top3
FROM topk_test
WHERE tenant_id = '00000000-0000-0000-0000-000000000000'
GROUP BY hour
ORDER BY hour;

-- global merge: this is wrong
SELECT
    topKMerge(10)(top_items) AS global_top3
FROM topk_test
WHERE tenant_id = '00000000-0000-0000-0000-000000000000';
```

**Expected behavior**
For the global merge, shouldShould merge the topK stats correctly, global top 3 should be:  ['d', 'e', _]

**Additional context**
Trying to improve performance for topK stats -  currently this is calculated via raw table but performance is not good for large datasets. So trying to move to aggregate this and bucket it per hour using AggregatedMergeTree and then query the aggregated table. However, that requires merging across time periods.

### PR DESCRIPTION
**Pull request by athre0z**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry:

Fixed incorrect state merging for `TopK` / `TopKWeighted` functions that would cause excessive error values even when capacity was not exhausted.

---

Resolves #73507

The capacity is used here

https://github.com/ClickHouse/ClickHouse/blob/d2697c0ea112fd2b86bb65249801cbec1862991c/src/Common/SpaceSaving.h#L211-L234

to determine whether the `TopK` function was previously at capacity. If the TopK is full, the merge code will add the value of the smallest entry as error to all records that aren't present in LHS. 

However, in the previous code this was buggy because TopK instances created via deserialization would have their capacity set to the size, not the actual capacity of the TopK function as specified on the function. This would then in turn cause error to be added even if the TopK bucket was not in fact previously at capacity.

### CODE REVIEW

File: tests/queries/0_stateless/03448_topk_merging.reference [hunk 1]
```diff
@@ -0,0 +1,39 @@
+6	a	30	0
```
Comment (athre0z) [inline tests/queries/0_stateless/03448_topk_merging.reference:1]: Output without the patch:

```
6       a       30      0
6       b       30      0
6       c       30      0
6       d       20      0
6       e       20      0
8       i       30      0
8       j       30      0
8       k       30      0
8       d       20      0
8       e       20      0
9       l       30      0
9       m       30      0
9       n       30      0
9       d       20      0
9       e       20      0
10      w       30      0
10      y       30      0
10      z       30      0
10      d       20      0
10      e       20      0
11      i       30      0
11      j       30      0
11      k       30      0
11      d       20      0
11      e       20      0
a       110     80
b       110     80
c       110     80
d       100     0
e       100     0
i       100     40
j       100     40
k       100     40
l       70      40
m       70      40
n       70      40
w       50      20
y       50      20
z       50      20
```

File: tests/queries/0_stateless/03448_topk_merging.sql [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+);
+
+SELECT * FROM (
+    SELECT
+        foo,
+        untuple(arrayJoin(topKWeightedMerge(100, 3, 'counts')(top_items))) AS top
+    FROM topk_test
+    GROUP BY foo
+)
+ORDER BY foo, top.count DESC, top.item;
```
Comment (athre0z) [inline tests/queries/0_stateless/03448_topk_merging.sql:57]: For some reason the problem doesn't reproduce even without the path if this query isn't executed before the final one. Perhaps something caching related that affects how merging is invoked? Not sure.

File: src/AggregateFunctions/AggregateFunctionTopK.cpp [hunk 3]
```diff
@@ -279,7 +279,7 @@ class AggregateFunctionTopKGeneric final
                 size,
                 getName(),
                 TOP_K_MAX_SIZE);
-        set.resize(size);
+        set.resize(std::max(size_t(reserved), size));
```
Comment (nickitat) [inline src/AggregateFunctions/AggregateFunctionTopK.cpp:282]: Seems to be too much, tests fail because of OOMs.
Maybe `set.resize(std::min(size + 1, reserved));`?

Comment (athre0z) [reply src/AggregateFunctions/AggregateFunctionTopK.cpp]: Ah yeah, that's a better idea than my patch in general. Changed accordingly, let's see how it goes this time. :)

**Review by nickitat — APPROVED** [review]
