### PR TITLE
Fix text index crash #90609

### LINKED ISSUE #90609: Full text search index SEGV
### Describe the bug

Happens on current master. Seen here: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90372&sha=0caa90a398f087b399c0059543e51aff5eb5e63e&name_0=PR&name_1=AST+fuzzer+%28amd_debug%29

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/43bdadbb-c60e-475a-a4cb-564cc73bce1d

### Error message and/or stacktrace

Stack trace:
```
2025.11.21 16:18:58.336130 [ 3620533 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.11.21 16:18:58.336173 [ 3620533 ] {} <Fatal> BaseDaemon: (version 25.11.1.591 (official build), build id: 82EBBAAA53945132060AE35A1A10BADB7394193B, git hash: 52088e1a55a2949ba9dae8748ff6c8cdc3e0e043, architecture: x86_64) (from thread 3620535) Received signal 11
2025.11.21 16:18:58.336182 [ 3620533 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2025.11.21 16:18:58.336187 [ 3620533 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2025.11.21 16:18:58.336202 [ 3620533 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005bf157319f0c 0x00005bf15a62eec5 0x00005bf159f23e82 0x00005bf156a2c6f9 0x00005bf156a21cef 0x00005bf156a03581 0x00005bf1569ffb30 0x00005bf157328350 0x00005bf1572a00c3 0x00005bf15729dd7f 0x00005bf153625009 0x00005bf1553f144a 0x00005bf1570860e6 0x00005bf15672754b 0x00005bf1567435b9 0x00005bf15671ba94 0x00005bf156721a81 0x00005bf156720e23 0x00005bf1569c48e8 0x00005bf156721b48 0x00005bf15671bbe5 0x00005bf15671a9f6 0x00005bf156719f90 0x00005bf15677140a 0x00005bf157327506 0x00005bf157325d78 0x00005bf157328830 0x00005bf1572ae52b 0x00005bf157669038 0x00005bf1576641d2 0x00005bf15accfdea 0x00005bf15aceaa64 0x00005bf16111a887 0x00005bf16111ae65 0x00005bf1610b853f 0x00005bf1610b5cd1 0x0000794bf0ca3d64 0x0000794bf0d373bc
2025.11.21 16:18:58.336204 [ 3620533 ] {} <Fatal> BaseDaemon: ########################################
2025.11.21 16:18:58.336276 [ 3620533 ] {} <Fatal> BaseDaemon: (version 25.11.1.591 (official build), build id: 82EBBAAA53945132060AE35A1A10BADB7394193B, git hash: 52088e1a55a2949ba9dae8748ff6c8cdc3e0e043) (from thread 3620535) (query_id: b65d98ac-c3cc-4263-8077-fe22b838421a) (query: SELECT 1
FROM
(
    SELECT *
    FROM (
        EXPLAIN actions = 1
        SELECT text
        FROM t0
        WHERE hasAnyTokens(text, ['Alick'])
        SETTINGS use_skip_indexes_on_data_read = 1
    )
)
PREWHERE (EXPLAIN actions = 1
    SELECT 1
    FROM t0
    PREWHERE hasAllTokens(text, ['Alick'])
) = '1';) Received signal Segmentation fault (11)
2025.11.21 16:18:58.336297 [ 3620533 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2025.11.21 16:18:58.336322 [ 3620533 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005bf157319f0c 0x00005bf15a62eec5 0x00005bf159f23e82 0x00005bf156a2c6f9 0x00005bf156a21cef 0x00005bf156a03581 0x00005bf1569ffb30 0x00005bf157328350 0x00005bf1572a00c3 0x00005bf15729dd7f 0x00005bf153625009 0x00005bf1553f144a 0x00005bf1570860e6 0x00005bf15672754b 0x00005bf1567435b9 0x00005bf15671ba94 0x00005bf156721a81 0x00005bf156720e23 0x00005bf1569c48e8 0x00005bf156721b48 0x00005bf15671bbe5 0x00005bf15671a9f6 0x00005bf156719f90 0x00005bf15677140a 0x00005bf157327506 0x00005bf157325d78 0x00005bf157328830 0x00005bf1572ae52b 0x00005bf157669038 0x00005bf1576641d2 0x00005bf15accfdea 0x00005bf15aceaa64 0x00005bf16111a887 0x00005bf16111ae65 0x00005bf1610b853f 0x00005bf1610b5cd1 0x0000794bf0ca3d64 0x0000794bf0d373bc
2025.11.21 16:18:58.415012 [ 3620533 ] {} <Fatal> BaseDaemon: 3. src/Common/assert_cast.h:39: DB::MergeTreeData::SnapshotData const& assert_cast<DB::MergeTreeData::SnapshotData const&, DB::StorageSnapshot::Data&>(DB::StorageSnapshot::Data&) @ 0x000000001bc94f0c
2025.11.21 16:18:58.466090 [ 3620533 ] {} <Fatal> BaseDaemon: 4. src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:180: DB::MergeTreeDataSelectExecutor::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const>, unsigned long, unsigned long, std::shared_ptr<std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>> const>, bool) const @ 0x000000001efa9ec5
2025.11.21 16:18:58.529843 [ 3620533 ] {} <Fatal> BaseDaemon: 5. src/Storages/StorageMergeTree.cpp:331: DB::StorageMergeTree::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x000000001e89ee82
2025.11.21 16:18:58.603777 [ 3620533 ] {} <Fatal> BaseDaemon: 6. src/Planner/PlannerJoinTree.cpp:1049: DB::(anonymous namespace)::buildQueryPlanForTableExpression(std::shared_ptr<DB::IQueryTreeNode>, std::shared_ptr<DB::IQueryTreeNode> const&, DB::SelectQueryInfo const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::PlannerContext>&, bool, bool) @ 0x000000001b3a76f9
2025.11.21 16:18:58.680495 [ 3620533 ] {} <Fatal> BaseDaemon: 7. src/Planner/PlannerJoinTree.cpp:2529: DB::buildJoinTreeQueryPlan(std::shared_ptr<DB::IQueryTreeNode> const&, DB::SelectQueryInfo const&, DB::SelectQueryOptions&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&, std::shared_ptr<DB::PlannerContext>&) @ 0x000000001b39ccef
2025.11.21 16:18:58.721588 [ 3620533 ] {} <Fatal> BaseDaemon: 8. src/Planner/Planner.cpp:1890: DB::Planner::buildPlanForQueryNode() @ 0x000000001b37e581
2025.11.21 16:18:58.758342 [ 3620533 ] {} <Fatal> BaseDaemon: 9. src/Planner/Planner.cpp:1661: DB::Planner::buildQueryPlanIfNeeded() @ 0x000000001b37ab30
2025.11.21 16:18:58.775322 [ 3620533 ] {} <Fatal> BaseDaemon: 10. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:275: DB::InterpreterSelectQueryAnalyzer::extractQueryPlan() && @ 0x000000001bca3350
2025.11.21 16:18:58.800610 [ 3620533 ] {} <Fatal> BaseDaemon: 11. src/Interpreters/InterpreterExplainQuery.cpp:573: DB::InterpreterExplainQuery::executeImpl() @ 0x000000001bc1b0c3
2025.11.21 16:18:58.824499 [ 3620533 ] {} <Fatal> BaseDaemon: 12. src/Interpreters/InterpreterExplainQuery.cpp:144: DB::InterpreterExplainQuery::execute() @ 0x000000001bc18d7f
2025.11.21 16:18:58.843023 [ 3620533 ] {} <Fatal> BaseDaemon: 13. src/TableFunctions/TableFunctionExplain.cpp:183: DB::(anonymous namespace)::TableFunctionExplain::executeImpl(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription, bool) const @ 0x0000000017fa0009
2025.11.21 16:18:58.866227 [ 3620533 ] {} <Fatal> BaseDaemon: 14. src/TableFunctions/ITableFunction.cpp:57: DB::ITableFunction::execute(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription, bool, bool) const @ 0x0000000019d6c44a
2025.11.21 16:18:58.980565 [ 3620533 ] {} <Fatal> BaseDaemon: 15. src/Interpreters/Context.cpp:2696: DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::ITableFunction> const&) @ 0x000000001ba010e6
2025.11.21 16:18:59.035926 [ 3620533 ] {} <Fatal> BaseDaemon: 16. src/Analyzer/Resolve/QueryAnalyzer.cpp:4059: DB::QueryAnalyzer::resolveTableFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&, bool) @ 0x000000001b0a254b
2025.11.21 16:18:59.095869 [ 3620533 ] {} <Fatal> BaseDaemon: 17. src/Analyzer/Resolve/QueryAnalyzer.cpp:4565: DB::QueryAnalyzer::resolveQueryJoinTreeNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&) @ 0x000000001b0be5b9
2025.11.21 16:18:59.152323 [ 3620533 ] {} <Fatal> BaseDaemon: 18. src/Analyzer/Resolve/QueryAnalyzer.cpp:4829: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000001b096a94
2025.11.21 16:18:59.204374 [ 3620533 ] {} <Fatal> BaseDaemon: 19. src/Analyzer/Resolve/QueryAnalyzer.cpp:2922: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000001b09ca81
2025.11.21 16:18:59.255652 [ 3620533 ] {} <Fatal> BaseDaemon: 20. src/Analyzer/Resolve/QueryAnalyzer.cpp:3041: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x000000001b09be23
2025.11.21 16:18:59.277709 [ 3620533 ] {} <Fatal> BaseDaemon: 21. src/Analyzer/Resolve/resolveFunction.cpp:537: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x000000001b33f8e8
2025.11.21 16:18:59.329758 [ 3620533 ] {} <Fatal> BaseDaemon: 22. src/Analyzer/Resolve/QueryAnalyzer.cpp:2890: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000001b09cb48
2025.11.21 16:18:59.386159 [ 3620533 ] {} <Fatal> BaseDaemon: 23. src/Analyzer/Resolve/QueryAnalyzer.cpp:4848: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000001b096be5
2025.11.21 16:18:59.435821 [ 3620533 ] {} <Fatal> BaseDaemon: 24. src/Analyzer/Resolve/QueryAnalyzer.cpp:138: DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x000000001b0959f6
2025.11.21 16:18:59.437705 [ 3620533 ] {} <Fatal> BaseDaemon: 25. src/Analyzer/Resolve/QueryAnalysisPass.cpp:18: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x000000001b094f90
2025.11.21 16:18:59.443874 [ 3620533 ] {} <Fatal> BaseDaemon: 26. src/Analyzer/QueryTreePassManager.cpp:193: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>&) @ 0x000000001b0ec40a
2025.11.21 16:18:59.463029 [ 3620533 ] {} <Fatal> BaseDaemon: 27. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:165: DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x000000001bca2506
2025.11.21 16:18:59.478856 [ 3620533 ] {} <Fatal> BaseDaemon: 28. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:182: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001bca0d78
2025.11.21 16:18:59.497719 [ 3620533 ] {} <Fatal> BaseDaemon: 29. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:759: std::unique_ptr<DB::InterpreterSelectQueryAnalyzer, std::default_delete<DB::InterpreterSelectQueryAnalyzer>> std::make_unique[abi:se210105]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, 0>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000001bca3830
2025.11.21 16:18:59.503830 [ 3620533 ] {} <Fatal> BaseDaemon: 30.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
2025.11.21 16:18:59.503857 [ 3620533 ] {} <Fatal> BaseDaemon: 30.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
2025.11.21 16:18:59.503865 [ 3620533 ] {} <Fatal> BaseDaemon: 30. src/Interpreters/InterpreterFactory.cpp:398: DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x000000001bc2952b
2025.11.21 16:18:59.542284 [ 3620533 ] {} <Fatal> BaseDaemon: 31. src/Interpreters/executeQuery.cpp:1634: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001bfe4038
2025.11.21 16:18:59.589877 [ 3620533 ] {} <Fatal> BaseDaemon: 32. src/Interpreters/executeQuery.cpp:1925: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001bfdf1d2
2025.11.21 16:18:59.620763 [ 3620533 ] {} <Fatal> BaseDaemon: 33. src/Server/TCPHandler.cpp:765: DB::TCPHandler::runImpl() @ 0x000000001f64adea
2025.11.21 16:18:59.672897 [ 3620533 ] {} <Fatal> BaseDaemon: 34. src/Server/TCPHandler.cpp:2861: DB::TCPHandler::run() @ 0x000000001f665a64
2025.11.21 16:18:59.675974 [ 3620533 ] {} <Fatal> BaseDaemon: 35. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000025a95887
2025.11.21 16:18:59.679782 [ 3620533 ] {} <Fatal> BaseDaemon: 36. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000025a95e65
2025.11.21 16:18:59.683628 [ 3620533 ] {} <Fatal> BaseDaemon: 37. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000025a3353f
2025.11.21 16:18:59.687480 [ 3620533 ] {} <Fatal> BaseDaemon: 38. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000025a30cd1
2025.11.21 16:18:59.687518 [ 3620533 ] {} <Fatal> BaseDaemon: 39. ? @ 0x00000000000a3d64
2025.11.21 16:18:59.687539 [ 3620533 ] {} <Fatal> BaseDaemon: 40. __GI___clone3 @ 0x00000000001373bc
2025.11.21 16:18:59.913355 [ 3620533 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 9BA384C4B7E7808B8EFDF3A1407DC4C7)
2025.11.21 16:18:59.913499 [ 3620533 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.11.21 16:18:59.913712 [ 3620533 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, use_skip_indexes = true, use_skip_indexes_on_data_read = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, optimize_use_projections = true, optimize_use_projection_filtering = true, enable_lightweight_update = true, use_query_condition_cache = false, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, query_plan_optimize_lazy_materialization = true, query_plan_max_limit_for_lazy_materialization = 0, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, cluster_for_parallel_replicas = 'cluster0', parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_qbit_type = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_live_view = true, allow_experimental_shared_set_join = true, allow_experimental_object_type = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by ahmadov**
Closes #90609

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by ahmadov** [comment]
Converting into a draft PR because the issue still occurs on ASan build on ARM: https://github.com/ClickHouse/ClickHouse/issues/90609#issuecomment-3656399401

**Comment by rschu1ze** [comment]
I think this PR conflicts with #91518. Can we wait till the v3 index is merged?

**Comment by ahmadov** [comment]
> I think this PR conflicts with #91518. Can we wait till the v3 index is merged?

I briefly skimmed the PR today (not fully reviewed yet), but as far as I understand they are different. Text index v3 mainly changes how the merge is performed but this is related to the text index reader task (which is not changed in the PR).
However, it is a good point we might need to re-test it again once the text index v3 is merged. I'll wait until it's merged and start the full review soon :)

**Comment by rschu1ze** [comment]
Stateless tests (amd_binary, ParallelReplicas, s3 storage, parallel):
- 02319_lightweight_delete_on_merge_tree https://github.com/ClickHouse/ClickHouse/issues/92633

 Stateless tests (amd_msan, parallel):
- 02126_dist_desc https://github.com/ClickHouse/ClickHouse/issues/85100
- 01070_exception_code_in_query_log_table and 03143_benchmark_query_id_prefix fallout of the former

Stateless tests (amd_debug, distributed plan, s3 storage, parallel)
- 02319_lightweight_delete_on_merge_tree https://github.com/ClickHouse/ClickHouse/issues/92633

BuzzHouse issues are unrelated too

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 1]
```diff
@@ -3696,8 +3696,7 @@ void ReadFromMergeTree::createReadTasksForTextIndex(const UsefulSkipIndexes & sk
     storage_snapshot = std::make_shared<StorageSnapshot>(
         storage_snapshot->storage,
         storage_snapshot->metadata,
-        std::move(new_virtual_columns),
-        std::move(storage_snapshot->data));
+        std::move(new_virtual_columns));
```
Comment (Ergus) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:3699]: It was missing here a brief explication about how this solved the issue or at least an explication in the PR description about what was causing it and how it solved the issue.

**Review by Ergus — COMMENTED** [review]
So far the fix is fine.
