### PR TITLE
Fix possible uncaught exception during distributed query cancellation

### LINKED ISSUE #59169: `DB::ErrnoException: Cannot remove descriptor from epoll: , errno: 2, strerror: No such file or directory. (EPOLL_ERROR)` (in `HedgedConnections::disconnect()`)
https://s3.amazonaws.com/clickhouse-test-reports/59116/dec93dabde1049d13ab4b92c4e65e91ae89f97c8/stress_test__msan_.html

```
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.698453 [ 2777 ] {} <Fatal> BaseDaemon: (version 24.1.1.1 (official build), build id: 2218EAFE122C99EE34E4E27313B6926D260779FF, git hash: f2bad692e2835c58807daba0d4fa21eb4f440c1d) (from thread 3689) Terminate called for uncaught exception:
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.698820 [ 2777 ] {} <Fatal> BaseDaemon: Code: 573. DB::ErrnoException: Cannot remove descriptor from epoll: , errno: 2, strerror: No such file or directory. (EPOLL_ERROR), Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.703834 [ 2777 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.704044 [ 2777 ] {} <Fatal> BaseDaemon: 0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x00000000402a9569 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.706726 [ 2777 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002004bd53 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.710004 [ 2777 ] {} <Fatal> BaseDaemon: 2. ./contrib/llvm-project/libcxx/include/string:1499: DB::ErrnoException::ErrnoException<char const (&) [36]>(int, char const (&) [36]) @ 0x00000000201601f4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.711396 [ 2777 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/Common/Epoll.cpp:58: DB::Epoll::remove(int) @ 0x000000003443ac83 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.711530 [ 2777 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Client/HedgedConnections.cpp:222: DB::HedgedConnections::disconnect() @ 0x000000003b9b3750 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.711682 [ 2777 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/QueryPipeline/RemoteQueryExecutor.cpp:0: DB::RemoteQueryExecutor::~RemoteQueryExecutor() @ 0x00000000343ead4e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.712443 [ 2777 ] {} <Fatal> BaseDaemon: 6. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:313: std::__shared_ptr_emplace<DB::RemoteQueryExecutor, std::allocator<DB::RemoteQueryExecutor>>::__on_zero_shared() @ 0x00000000207198cd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.712576 [ 2777 ] {} <Fatal> BaseDaemon: 7. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::RemoteSource::~RemoteSource() @ 0x000000003ca9e4b8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717099 [ 2777 ] {} <Fatal> BaseDaemon: 8. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:313: std::__shared_ptr_emplace<DB::RemoteSource, std::allocator<DB::RemoteSource>>::__on_zero_shared() @ 0x000000002071a12d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717240 [ 2777 ] {} <Fatal> BaseDaemon: 9. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() @ 0x0000000034375ca8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717332 [ 2777 ] {} <Fatal> BaseDaemon: 10. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::QueryPipeline::~QueryPipeline() @ 0x000000003437fe33 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717424 [ 2777 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/QueryPipeline/QueryPipeline.cpp:666: DB::QueryPipeline::reset() @ 0x0000000034394e7d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717539 [ 2777 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/QueryPipeline/BlockIO.cpp:68: DB::BlockIO::onException() @ 0x0000000034343046 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717630 [ 2777 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Server/TCPHandler.cpp:610: DB::TCPHandler::runImpl() @ 0x000000003bc8a824 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717794 [ 2777 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Server/TCPHandler.cpp:2298: DB::TCPHandler::run() @ 0x000000003bcd8e1c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717924 [ 2777 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000003ff57660 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.717995 [ 2777 ] {} <Fatal> BaseDaemon: 16. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: Poco::Net::TCPServerDispatcher::run() @ 0x000000003ff584c2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.718069 [ 2777 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x00000000403dc5a6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.718121 [ 2777 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x00000000403d936e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.731697 [ 2777 ] {} <Fatal> BaseDaemon: 19. ./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000403d6252 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.731830 [ 2777 ] {} <Fatal> BaseDaemon: 20. ? @ 0x00007f5d53b2dac3
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.732006 [ 2777 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00007f5d53bbf660
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 12:56:01.732075 [ 2777 ] {} <Fatal> BaseDaemon:  (version 24.1.1.1 (official build))
/var/log/clickhouse-server/clickhouse-server.err.log:2024.01.24 13:09:34.436143 [ 2775 ] {} <Fatal> Application: Child process was terminated by signal 6.
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.698453 [ 2777 ] {} <Fatal> BaseDaemon: (version 24.1.1.1 (official build), build id: 2218EAFE122C99EE34E4E27313B6926D260779FF, git hash: f2bad692e2835c58807daba0d4fa21eb4f440c1d) (from thread 3689) Terminate called for uncaught exception:
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.698820 [ 2777 ] {} <Fatal> BaseDaemon: Code: 573. DB::ErrnoException: Cannot remove descriptor from epoll: , errno: 2, strerror: No such file or directory. (EPOLL_ERROR), Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.703834 [ 2777 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.704044 [ 2777 ] {} <Fatal> BaseDaemon: 0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x00000000402a9569 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.706726 [ 2777 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002004bd53 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.710004 [ 2777 ] {} <Fatal> BaseDaemon: 2. ./contrib/llvm-project/libcxx/include/string:1499: DB::ErrnoException::ErrnoException<char const (&) [36]>(int, char const (&) [36]) @ 0x00000000201601f4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.711396 [ 2777 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/Common/Epoll.cpp:58: DB::Epoll::remove(int) @ 0x000000003443ac83 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.711530 [ 2777 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Client/HedgedConnections.cpp:222: DB::HedgedConnections::disconnect() @ 0x000000003b9b3750 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.711682 [ 2777 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/QueryPipeline/RemoteQueryExecutor.cpp:0: DB::RemoteQueryExecutor::~RemoteQueryExecutor() @ 0x00000000343ead4e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.712443 [ 2777 ] {} <Fatal> BaseDaemon: 6. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:313: std::__shared_ptr_emplace<DB::RemoteQueryExecutor, std::allocator<DB::RemoteQueryExecutor>>::__on_zero_shared() @ 0x00000000207198cd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.712576 [ 2777 ] {} <Fatal> BaseDaemon: 7. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::RemoteSource::~RemoteSource() @ 0x000000003ca9e4b8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717099 [ 2777 ] {} <Fatal> BaseDaemon: 8. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:313: std::__shared_ptr_emplace<DB::RemoteSource, std::allocator<DB::RemoteSource>>::__on_zero_shared() @ 0x000000002071a12d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717240 [ 2777 ] {} <Fatal> BaseDaemon: 9. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() @ 0x0000000034375ca8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717332 [ 2777 ] {} <Fatal> BaseDaemon: 10. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::QueryPipeline::~QueryPipeline() @ 0x000000003437fe33 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717424 [ 2777 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/QueryPipeline/QueryPipeline.cpp:666: DB::QueryPipeline::reset() @ 0x0000000034394e7d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717539 [ 2777 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/QueryPipeline/BlockIO.cpp:68: DB::BlockIO::onException() @ 0x0000000034343046 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717630 [ 2777 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Server/TCPHandler.cpp:610: DB::TCPHandler::runImpl() @ 0x000000003bc8a824 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717794 [ 2777 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Server/TCPHandler.cpp:2298: DB::TCPHandler::run() @ 0x000000003bcd8e1c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717924 [ 2777 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000003ff57660 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.717995 [ 2777 ] {} <Fatal> BaseDaemon: 16. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: Poco::Net::TCPServerDispatcher::run() @ 0x000000003ff584c2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.718069 [ 2777 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x00000000403dc5a6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.718121 [ 2777 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x00000000403d936e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.731697 [ 2777 ] {} <Fatal> BaseDaemon: 19. ./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000403d6252 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.731830 [ 2777 ] {} <Fatal> BaseDaemon: 20. ? @ 0x00007f5d53b2dac3
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.732006 [ 2777 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00007f5d53bbf660
/var/log/clickhouse-server/clickhouse-server.stress.log:2024.01.24 12:56:01.732075 [ 2777 ] {} <Fatal> BaseDaemon:  (version 24.1.1.1 (official build))
```

cc @Avogar

### PR DESCRIPTION
**Pull request by azat**
Cancellation of distributed queries may throw (i.e. some timeout), and in case of pipeline had not been properly created properly (EXCEPTION_BEFORE_START) cancel will not be sent, so cancellation will be done from dtor and will throw.

<details>

<summary>stacktrace</summary>

```
<Fatal> BaseDaemon: (version 23.9.2.56 (official build), build id: 76109A79FA62B9BC630A6C39438DEA7D28147B68, git hash: a1bf3f1de55abf2354dc498ffbee270be043d633) (from thread 51895) Terminate called for uncaught exception:
<Fatal> BaseDaemon: Code: 209. DB::NetException: Timeout exceeded while reading from socket (socket (10.61.1.50:9000), receive timeout 20000 ms). (SOCKET_TIMEOUT), Stack trace (when copying this message, always include the lines below):
<Fatal> BaseDaemon:
<Fatal> BaseDaemon: 0. ./build_docker/./src/Common/Exception.cpp:98: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c741d97 in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String const&>(int, String const&) @ 0x000000001148ace7 in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 2. ./build_docker/./src/QueryPipeline/RemoteQueryExecutorReadContext.cpp:101: DB::RemoteQueryExecutorReadContext::checkTimeout(bool) @ 0x000000001148a70a in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 3. ./build_docker/./src/Common/Fiber.h:42: DB::RemoteQueryExecutorReadContext::cancelBefore() @ 0x000000001148aded in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 4. ./build_docker/./src/Common/Fiber.h:27: DB::AsyncTaskExecutor::cancel() @ 0x000000001148969d in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 5. ./build_docker/./src/QueryPipeline/RemoteQueryExecutor.cpp:169: DB::RemoteQueryExecutor::~RemoteQueryExecutor() @ 0x000000001147a9d0 in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 6. ./build_docker/./contrib/llvm-project/libcxx/src/include/atomic_support.h:74: std::__shared_ptr_emplace<DB::RemoteSource, std::allocator<DB::RemoteSource>>::__on_zero_shared() @ 0x000000000c94a4a1 in /usr/lib/debug/usr/bin/clickhou

<Fatal> BaseDaemon: 7. ./build_docker/./contrib/llvm-project/libcxx/src/include/atomic_support.h:74: std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::
or<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() @ 0x00000000114603a1 in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 8. ./build_docker/./contrib/llvm-project/libcxx/src/include/atomic_support.h:74: DB::QueryPipeline::~QueryPipeline() @ 0x000000001146347a in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 9. ./build_docker/./src/QueryPipeline/QueryPipeline.cpp:709: DB::QueryPipeline::reset() @ 0x0000000011468f78 in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 10. ./build_docker/./src/Interpreters/executeQuery.cpp:1427: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001249aa8b in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 11. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:818: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x00000000132bddb4 in /usr/lib/debug/usr/bin/clickhouse.debug
<Fatal> BaseDaemon: 12. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000132c23a4 in /usr/lib/debug/usr/bin/clickhouse.debug
```

</details>

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible uncaught exception during distributed query cancellation. Closes https://github.com/ClickHouse/ClickHouse/issues/59169

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 3108a988dea5807a177bb0e02489bbf9da2c0aa7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59487/3108a988dea5807a177bb0e02489bbf9da2c0aa7/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59487/3108a988dea5807a177bb0e02489bbf9da2c0aa7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
https://github.com/ClickHouse/ClickHouse/pull/59480

**Comment by Avogar** [comment]
I will close my PR, let's merge this one

File: src/QueryPipeline/RemoteQueryExecutor.cpp [hunk 1]
```diff
@@ -182,7 +182,19 @@ RemoteQueryExecutor::~RemoteQueryExecutor()
     {
         /// Set was_cancelled, so the query won't be sent after creating connections.
         was_cancelled = true;
-        read_context->cancel();
+
+        /// Cancellation may throw (i.e. some timeout), and in case of pipeline
+        /// had not been properly created properly (EXCEPTION_BEFORE_START)
+        /// cancel will not be sent, so cancellation will be done from dtor and
+        /// will throw.
+        try
```
Comment (Avogar) [inline src/QueryPipeline/RemoteQueryExecutor.cpp:190]: `        connections->disconnect();` below also may throw, let's add `try/catch` there also

**Comment by azat** [comment]
>Almost the same time https://github.com/ClickHouse/ClickHouse/pull/59480 :)

And even almost in the same time :)

File: src/QueryPipeline/RemoteQueryExecutor.cpp (hunk 1 above)
Comment (azat) [reply src/QueryPipeline/RemoteQueryExecutor.cpp:190]: Make sense, done.

**Review by jsc0218 — APPROVED** [review]

**Review by Avogar — APPROVED** [review]
