### PR TITLE
Fix flaky 02561_null_as_default_more_formats

### LINKED ISSUE #49177: 02561_null_as_default_more_formats is flaky
`Code: 75. DB::ErrnoException: Cannot write to file (fd = 1), errno: 32, strerror: Broken pipe`

https://s3.amazonaws.com/clickhouse-test-reports/0/0972fa2f6c4642d03fcc776bbf49ba966c9a91df/stateless_tests__ubsan__[2/2].html
https://s3.amazonaws.com/clickhouse-test-reports/0/8529876505f1a6677587681c6abef5c4475c2257/stateless_tests__ubsan__[2/2].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMjU2MV9udWxsX2FzX2RlZmF1bHRfbW9yZV9mb3JtYXRzJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/49177

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: tests/queries/0_stateless/02561_null_as_default_more_formats.sh [hunk 1]
```diff
@@ -7,15 +7,19 @@ CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
 $CLICKHOUSE_CLIENT -q "drop table if exists test"
 $CLICKHOUSE_CLIENT -q "create table test (x UInt64 default 42, y UInt64, z LowCardinality(String) default '42') engine=Memory";
+uid=$RANDOM$RANDOM
```
Comment (Avogar) [inline tests/queries/0_stateless/02561_null_as_default_more_formats.sh:10]: Maybe use `$CLICKHOUSE_TEST_UNIQUE_NAME`?

**Review by Avogar — APPROVED** [review]

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit df1d16a165f421b366e8422523ec7cbb3ef85771 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51001/df1d16a165f421b366e8422523ec7cbb3ef85771/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: tests/queries/0_stateless/02561_null_as_default_more_formats.sh (hunk 1 above)
Comment (devcrafter) [reply tests/queries/0_stateless/02561_null_as_default_more_formats.sh:10]: Of course. Didn't know that there is such variable.
