### PR TITLE
Fix rankCorr size overflow

### LINKED ISSUE #42012: rankCorr wrong result
rankCorr returns huge number (-17.543489999420327 for my case). It should be between -1 and 1.
clickhouse version: 22.8.5.29

test data are located at (oneDrive share, 150M):
https://1drv.ms/u/s!AuNxjqg2JayilU2PtuLTicBa662Z?e=ofy3ZG

simply create a table, import the csv, and then select the rankCorr to reproduce the bug
```
create table yg.testData(a Float32,b Float32 ) engine=MergeTree order by a
```
```
select rankCorr(a,b) from yg.testData
```

For reference, I also used pandas to calculate the rankCorr, the result is -0.018601.

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix rankCorr size overflow

When the length of columns is huge, size_t overflow:
```sql
SELECT round(rankCorr(number, -number))
FROM numbers(5000000)

┌─round(rankCorr(number, negate(number)))─┐
│                                     -16 │
└─────────────────────────────────────────┘
```

May close #42012

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionRankCorrelation.h [hunk 1]
```diff
@@ -32,7 +32,7 @@ struct RankCorrelationData : public StatisticalSample<Float64, Float64>
         std::tie(ranks_y, std::ignore) = computeRanksAndTieCorrection(this->y);
 
         /// Sizes can be non-equal due to skipped NaNs.
-        const auto size = std::min(this->size_x, this->size_y);
+        const Float32 size = static_cast<Float32>(std::min(this->size_x, this->size_y));
```
Comment (evillique) [inline src/AggregateFunctions/AggregateFunctionRankCorrelation.h:35]: I think that if we were to use Float in this case - it is better to use Float64 :)
```suggestion
        const Float64 size = static_cast<Float64>(std::min(this->size_x, this->size_y));
```

**Review by alexey-milovidov — APPROVED** [review]

**Review by evillique — APPROVED** [review]
