### PR TITLE
[CI Fest] Fix `02597_column_update_tricy_expression_and_replication`

### LINKED ISSUE #67444: Stateless test `02597_column_update_tricy_expression_and_replication` is flaky with DatabaseReplicated
Link: https://s3.amazonaws.com/clickhouse-test-reports/67392/c2a40940dbc6a2bac3623bef2ac56bc842d837fd/stateless_tests__release__old_analyzer__s3__databasereplicated__[2_4].html

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes https://github.com/ClickHouse/ClickHouse/issues/67444

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [x]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit a3cbfb262f539f8ec56270803371d6d07c1ba49e with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67873/a3cbfb262f539f8ec56270803371d6d07c1ba49e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/67873/a3cbfb262f539f8ec56270803371d6d07c1ba49e/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.sql [hunk 1]
```diff
@@ -6,23 +6,23 @@ CREATE TABLE test (
...
-set mutations_sync=0;
+SET mutations_sync=0;
+SYSTEM ENABLE FAILPOINT infinite_sleep;
 
 ALTER TABLE test UPDATE d = d + sleepEachRow(0.3) where 1;
 
 ALTER TABLE test ADD COLUMN x UInt32 default 0;
 ALTER TABLE test UPDATE d = x + 1 where 1;
+
+SYSTEM DISABLE FAILPOINT infinite_sleep;
```
Comment (alesapin) [inline tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.sql:19]: Shouldn't we do it after the next query because now small race is still possible.

File: tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.sql [hunk 2]
```diff
@@ -6,23 +6,23 @@ CREATE TABLE test (
...
 ORDER BY (c_id, p_id);
 
-INSERT INTO test SELECT '1', '11', '111' FROM numbers(3);
+INSERT INTO test SELECT '1', '11', '111' FROM numbers(5);
 
-INSERT INTO test SELECT '2', '22', '22' FROM numbers(3);
-
-set mutations_sync=0;
+SET mutations_sync=0;
+SYSTEM ENABLE FAILPOINT infinite_sleep;
```
Comment (alesapin) [inline tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.sql:12]: Now this test should be Tags: no-parallel

File: tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.sql (hunk 1 above)
Comment (thevar1able) [reply tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.sql:19]: `mutation_sync=2` blocks execution flow. Let's rewrite in bash.

File: tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.python [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+client.query("INSERT INTO test SELECT '1', '11', '111' FROM numbers(5)")
+client.query("SYSTEM ENABLE FAILPOINT infinite_sleep")
+client.query(
+    "ALTER TABLE test UPDATE d = d + sleepEachRow(0.3) where 1 SETTINGS mutations_sync=0"
+)
+client.query("ALTER TABLE test ADD COLUMN x UInt32 default 0 SETTINGS mutations_sync=0")
+client.query("ALTER TABLE test UPDATE d = x + 1 where 1 SETTINGS mutations_sync=0")
+
+q = Queue()
+t = Thread(target=attempt_mutation, args=(q,))
```
Comment (alesapin) [inline tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.python:52]: Not required, but a very simple approach we use everywhere:
```
from multiprocessing.dummy import Pool
def drop_projection():
    # do what you want

p = Pool(2)
p.apply_async(drop_projection)
```

**Review by alesapin — COMMENTED** [review]
Didn't get why is it in python without any need, but Ok, if you want.

File: tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.python (hunk 3 above)
Comment (thevar1able) [reply tests/queries/0_stateless/02597_column_update_tricky_expression_and_replication.python:52]: I think `threading` is enough, no need for a separate process.

**Review by alesapin — APPROVED** [review]
