### PR TITLE
DatabaseIceberg: hide catalog credential settings

### LINKED ISSUE #74559: Iceberg Database engine doesn't hide `catalog_credential` settings from system.databases
**Describe the unexpected behaviour**
The `catalog_credential` setting of an Iceberg database is not hidden from `system.databases` or `SHOW CREATE DATABASE`.

**How to reproduce**
* Create an Iceberg Database with catalog credentials:
```
CREATE DATABASE test
ENGINE = Iceberg('https://some.catalog.api.host/api/catalog')
SETTINGS catalog_type = 'rest', warehouse = 'test', catalog_credential = 'some_client_id:some_client_secret'
```
* Run `SHOW CREATE DATABASE test`

**Expected behavior**
Similar to how the `PostgreSQL` engine does this, the Iceberg engine should not return `some_client_id:some_client_secret` in plain text, but instead show something like `[hidden]`

**Error message and/or stacktrace**
No error, but the full database creation statement as above is returned with credentials in plain text.

**Additional context**
Since the Iceberg implementation is still pretty much WIP, I wasn't sure whether this is "unexpected behaviour" or rather "unfinished code". Please feel free to adjust.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Hide catalog credential settings in database engine `Iceberg`. Closes https://github.com/ClickHouse/ClickHouse/issues/74559

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 77280c7587f4547c3976eee80896f1ba4eb1ae22 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75080/77280c7587f4547c3976eee80896f1ba4eb1ae22/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Parsers/ASTSetQuery.cpp [hunk 1]
```diff
@@ -81,10 +81,30 @@ void ASTSetQuery::formatImpl(WriteBuffer & ostr, const FormatSettings & format,
...
+        auto format_if_secret = [&]() -> bool
+        {
+            CustomType custom;
+            if (change.value.tryGet<CustomType>(custom) && custom.isSecret())
+            {
+                ostr << " = " << custom.toString(/* show_secrets */false);
+                return true;
+            }
+
+            if (state.create_engine_name == "Iceberg")
```
Comment (antaljanosbenjamin) [inline src/Parsers/ASTSetQuery.cpp:94]: My only issue with this is it is really easy to change the engine name while missing to change this one. As this is a security motivated change, I think it would be nice to make it safer. However I know that we cannot linkd `dbms` to parsers, and specifying a constant in the parser just because of this seems silly. It also doesn't solve the issue of introducing/renaming settings or just adding new ones.

All in all I don't know how to make it stricter, but maybe it worth to add a comment to DatabaseIceberg and the settings about this quirk, so at least if somebody reads the comment while adding/renaming a setting or renaming the database, they can catch this.

Comment (kssenii) [reply src/Parsers/ASTSetQuery.cpp:94]: Also for engine arguments it is done in a similar way https://github.com/ClickHouse/ClickHouse/blob/d99795b7636b6542a860ef2144283943d9f882f8/src/Parsers/FunctionSecretArgumentsFinder.h#L103-L108
so I guess it should be ok as is, as we already do this

**Review by antaljanosbenjamin — APPROVED** [review]
