### PR TITLE
Fix segfault during Kerberos initialization

### LINKED ISSUE #56073: Segmentation fault on start or kafka table creation
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

We use jaeger collector and try to send traces using kafka as a buffer

We use kafka with sasl auth, it is definitely up and accessible from CH host

Whenever i restart server with correct kafka config and there is a table that listens to kafka - server crashes

It doesn't matter if there is any data in kafka topic (tried both with and without - same result)

**Does it reproduce on recent release?**

Yes

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
Tried on server versions 22.11.1.1360 and 23.9.2.56

* Which interface to use, if matters
I used clickhouse-client

* Non-default settings, if any
Server config (keytab file and kerberos principal are definitely fine, as they are used in other places):
```
<clickhouse>
    <kafka>
      <debug>all</debug>
      <security_protocol>SASL_SSL</security_protocol>
      <sasl_mechanism>GSSAPI</sasl_mechanism>
      <sasl_kerberos_keytab>/etc/clickhouse-server/key-filename.keytab</sasl_kerberos_keytab>
      <sasl_kerberos_principal>kerberos@principal.com</sasl_kerberos_principal>
    </kafka>
</clickhouse>
```
* `CREATE TABLE` statements for all tables involved
Command i use to create table(brokers are up, their ports are accessible, topic exists):
```
CREATE TABLE kafka (key UInt64, value UInt64)
    ENGINE = Kafka
    SETTINGS 
        kafka_broker_list = 'broker1:port,broker2:port',
        kafka_topic_list = 'topic_name',
        kafka_group_name = 'group_name',
        kafka_format = 'JSONEachRow',
        kafka_max_block_size = 1048576;
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
Doesn't matter
* Queries to run that lead to unexpected result
Not needed

**Expected behavior**

Working CH server with kafka connection or error message

**Error message and/or stacktrace**

```
Received signal Segmentation fault (11)
[server-name] 2023.10.27 08:30:31.623462 [ 3148874 ] <Fatal> BaseDaemon: Address: 0x37. Access: read. Address not mapped to object.
[server-name] 2023.10.27 08:30:31.623520 [ 3148874 ] <Fatal> BaseDaemon: Stack trace: 0x0000000016dafd49 0x000000001106025e 0x000000001105ad67 0x0000000010da4252 0x0000000010da152b 0x0000000011ebf47c 0x0000000011eb723f 0x0000000011ec469e 0x0000000012496116 0x000000001249181c 0x00000000133197ec 0x000000001332bc79 0x0000000015d0eb14 0x0000000015d0fd11 0x0000000015e1b367 0x0000000015e195fc 0x00007f0b59a011cf 0x00007f0b5966ddd3
[server-name] 2023.10.27 08:30:31.629998 [ 3148874 ] <Fatal> BaseDaemon: 2. krb5_free_cred_contents @ 0x0000000016dafd49 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.630188 [ 3148874 ] <Fatal> BaseDaemon: 3. (anonymous namespace)::KerberosInit::~KerberosInit() (.llvm.1207451943512575562) @ 0x000000001106025e in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.630307 [ 3148874 ] <Fatal> BaseDaemon: 4. kerberosInit(String const&, String const&, String const&) @ 0x000000001105ad67 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.639862 [ 3148874 ] <Fatal> BaseDaemon: 5. DB::StorageKafka::updateConfiguration(cppkafka::Configuration&, std::shared_ptr<std::weak_ptr<DB::KafkaConsumer>>) @ 0x0000000010da4252 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.640036 [ 3148874 ] <Fatal> BaseDaemon: 6. DB::StorageKafka::startup() @ 0x0000000010da152b in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.640104 [ 3148874 ] <Fatal> BaseDaemon: 7. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&) @ 0x0000000011ebf47c in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646183 [ 3148874 ] <Fatal> BaseDaemon: 8. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000011eb723f in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646325 [ 3148874 ] <Fatal> BaseDaemon: 9. DB::InterpreterCreateQuery::execute() @ 0x0000000011ec469e in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646400 [ 3148874 ] <Fatal> BaseDaemon: 10. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000012496116 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646464 [ 3148874 ] <Fatal> BaseDaemon: 11. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x000000001249181c in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646527 [ 3148874 ] <Fatal> BaseDaemon: 12. DB::TCPHandler::runImpl() @ 0x00000000133197ec in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646608 [ 3148874 ] <Fatal> BaseDaemon: 13. DB::TCPHandler::run() @ 0x000000001332bc79 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646661 [ 3148874 ] <Fatal> BaseDaemon: 14. Poco::Net::TCPServerConnection::start() @ 0x0000000015d0eb14 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646712 [ 3148874 ] <Fatal> BaseDaemon: 15. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015d0fd11 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646779 [ 3148874 ] <Fatal> BaseDaemon: 16. Poco::PooledThread::run() @ 0x0000000015e1b367 in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646837 [ 3148874 ] <Fatal> BaseDaemon: 17. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e195fc in /usr/bin/clickhouse
[server-name] 2023.10.27 08:30:31.646898 [ 3148874 ] <Fatal> BaseDaemon: 18. start_thread @ 0x00000000000081cf in /usr/lib64/libpthread-2.28.so
[server-name] 2023.10.27 08:30:31.646964 [ 3148874 ] <Fatal> BaseDaemon: 19. clone @ 0x0000000000039dd3 in /usr/lib64/libc-2.28.so
[server-name] 2023.10.27 08:30:31.872475 [ 3148874 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 3A99FBFAA2DA54D46975E9ABC04E53E0)
[server-name] 2023.10.27 08:30:31.872824 [ 3148874 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[server-name] 2023.10.27 08:30:31.872972 [ 3148874 ] <Fatal> BaseDaemon: No settings were changed
```
**Additional context**

> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a segfault caused by a thrown exception in Kerberos initialization during the creation of the Kafka table. Closes https://github.com/ClickHouse/ClickHouse/issues/56073.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 88c43b5bbd3cbc0fb9e825e5a9aecd221fc2bd31 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56401/88c43b5bbd3cbc0fb9e825e5a9aecd221fc2bd31/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6778221032">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56401/88c43b5bbd3cbc0fb9e825e5a9aecd221fc2bd31/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Access/KerberosInit.cpp [hunk 1]
```diff
@@ -61,6 +62,11 @@ String KerberosInit::fmtError(krb5_error_code code) const
     return fmt_error;
 }
 
+KerberosInit::KerberosInit()
+{
+    memset(&my_creds, 0, sizeof(my_creds));
```
Comment (devcrafter) [inline src/Access/KerberosInit.cpp:67]: It'd make sense to zero `k5` structure [here](https://github.com/ClickHouse/ClickHouse/pull/56401/files#diff-6afc5f08ac58fa52e17ac2052c0bb16b49a07e1e92f419cbcaf727be9b62e1a6R44) as well

**Review by devcrafter — APPROVED** [review]

File: src/Access/KerberosInit.cpp (hunk 1 above)
Comment (evillique) [reply src/Access/KerberosInit.cpp]: I looked into it and `{}` value initialization actually fills the struct with zeroes ([cppref](https://en.cppreference.com/w/cpp/language/value_initialization)), so I did similar thing with `my_creds`

**Comment by evillique** [comment]
Tests:
- Integration tests (release) [4/4]: https://github.com/ClickHouse/ClickHouse/issues/54502
- Integration tests (tsan) [6/6]: https://github.com/ClickHouse/ClickHouse/issues/56043
- Stateless tests (release, DatabaseReplicated) [4/4]: https://github.com/ClickHouse/ClickHouse/issues/56682
- Stateless tests (release, s3 storage) [2/2]: https://github.com/ClickHouse/ClickHouse/issues/56683
