### PR TITLE
DETACH TABLE PERMANENTLY

### LINKED ISSUE #13850: "use DETACH DICTIONARY query"
```
DROP TABLE test_dict


Received exception from server (version 20.7.1):
Code: 520. DB::Exception: Received from localhost:9000. DB::Exception: Cannot detach dictionary `default.test_dict` as table, use DETACH DICTIONARY query. 
```

Message should be:
```
Cannot drop/detach dictionary `default.test_dict` as table, use DROP/DETACH DICTIONARY query
```

And/or: is it ok that it tries to DETACH dict as regular table and exception came from DETACH? Maybe the check should happen earlier?

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Introduce `DETACH TABLE/VIEW ... PERMANENTLY` syntax, so that after restarting the table does not reappear back automatically (only by explicit request). The table can still be attached back using the short syntax ATTACH TABLE.  Implements #5555. Fixes #13850.

Detailed description / Documentation draft:

### Why needed?
* It may be some cold data (backup) on remote/slow disk that only needs to be connected when explicitly requested (you don't want them to be loaded at server start).
* It may be some kind of MV that you want to deactivate or a Kafka table that you want to turn off temporarily, and so that it does not turn on by accident as a result of a server restart.

### How implemented:
DETACH ... PERMANENTLY works like regular DETACH but additionally creates the flag file (xxx.sql.detached)
which is checked during tables loading, and the tables with that flag will not be reattached at the time of ClickHouse initialization.

`SHOW CREATE TABLE` will also show permanently detached tables.

### Extra options: 
* `ATTACH EPHEMERAL` (attaching a table temporary without creating a normal metadata file or maybe with creating .sql_detached). Abandoned, can break some invariants. Can be added later.
* `DETACH DATABASE PERMANENTLY`. Can be added later.
* `DETACH DICTIONARY PERMANENTLY`. The use-case is not clear, can be added later.

### CODE REVIEW

File: src/Databases/DatabaseOnDisk.cpp [hunk 1]
```diff
@@ -213,8 +218,47 @@ void DatabaseOnDisk::commitCreateTable(const ASTCreateQuery & query, const Stora
...
         throw;
     }
+
+    try
+    {
+        /// If the table was detached permanently we will have a file with
+        /// .sql_detached suffix, which is not needed anymore since we attached the table back
+        auto table_metadata_file_detached = Poco::File(table_metadata_path + detached_suffix);
+        if (table_metadata_file_detached.exists())
+            table_metadata_file_detached.remove();
```
Comment (tavplubix) [inline src/Databases/DatabaseOnDisk.cpp:228]: I'm not sure if it's a good idea to silently remove metadata file of permanently detached table. It leaves garbage in `data/` or `store/` directory if permanently detached table has some data on disk. For `Atomic` databases we can use `DatabaseCatalog::enqueueDroppedTableCleanup(...)` to drop it correctly. But maybe just throw an exception if permanently detached table with the same name already exists?

File: src/Databases/DatabaseOnDisk.cpp [hunk 2]
```diff
@@ -213,8 +218,47 @@ void DatabaseOnDisk::commitCreateTable(const ASTCreateQuery & query, const Stora
...
+    /// This is possible for Lazy database.
+    if (!table)
+        return;
+
+    String table_metadata_path = getObjectMetadataPath(table_name);
+    String table_metadata_path_detached = table_metadata_path + detached_suffix;
+
+    try
+    {
+        /// it will silently overwrite the file if exists, and it's ok
```
Comment (tavplubix) [inline src/Databases/DatabaseOnDisk.cpp:250]: Maybe use `renameNoReplace(...)`?

File: src/Databases/DatabaseOnDisk.cpp (hunk 1 above)
Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:228]: Actually right now i did it this way that the ATTACH table becomes normal again and .sql file is recreated back, so `.sql_detached` is not needed anymore (recreating SQL file is a bit safer than renaming it back, because creating happen in stages to prevent races). 

I guess what you are talking is smth like 'ATTACH EPHEMERAL' - i.e. if the table was detached permanently, the attach doesn't return the table to a normal state, it just gets loaded one-time (but will not be loaded with server start).

File: src/Databases/DatabaseOnDisk.cpp (hunk 2 above)
Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:250]: Actually, the `sql_detached` should not exist in normal circumstances. And if it was existing I guess the best what we can do is just overwrite it (it's either the same, either some obsolete version of the schema). From what I've understood  `renameNoReplace` does a bit different thing.

File: src/Databases/DatabaseOnDisk.cpp (hunk 1 above)
Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:228]: I was thinking about that `ATTACH EPHEMERAL` (it's quite a logical extension of `DETACH PERMANENTLY`), but it seems it may introduce some extra states of the tables which will be harder to follow and will need to break some of the existing invariants (like 'attached table always have own SQL file').

Let's keep it simpler for now and if needed we can add that.

File: src/Databases/DatabaseOnDisk.cpp [hunk 3]
```diff
@@ -213,8 +218,47 @@ void DatabaseOnDisk::commitCreateTable(const ASTCreateQuery & query, const Stora
...
+        LOG_WARNING(log, getCurrentExceptionMessage(__PRETTY_FUNCTION__));
+    }
+}
+
+void DatabaseOnDisk::detachTablePermanently(const String & table_name)
+{
+    StoragePtr table = detachTable(table_name);
+
+    /// This is possible for Lazy database.
+    if (!table)
```
Comment (tavplubix) [inline src/Databases/DatabaseOnDisk.cpp:242]: But `table` is not actually used below, maybe we can just remove this `if`, so `DETACH PERMANENTLY` will work for `Lazy` db?

File: src/Databases/DatabaseOnDisk.cpp (hunk 1 above)
Comment (tavplubix) [reply src/Databases/DatabaseOnDisk.cpp:228]:
```
create database db engine=Atomic;
use db;

-- creates test.sql and store/xxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
create table test (n int) engine=MergeTree order by n; 

-- writes data into store/xxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
insert into test select * from numbers(1000000);

-- renames test.sql to test.sql_detached
detach table test permanently; 

-- creates test.sql with new UUID and store/yyy/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy/
-- removes test.sql_detached, but not store/xxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
create table test (n int) engine=MergeTree order by n;
-- now data from store/xxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/ can be removed only manually
```

File: src/Databases/DatabaseOnDisk.cpp (hunk 2 above)
Comment (tavplubix) [reply src/Databases/DatabaseOnDisk.cpp:250]:
```
create table test (n int) engine=MergeTree order by n;
detach table test permanently; 
create table test2 (s String) engine=Log;
rename table test2 to test;

-- overwrites previous test.sql_detached
detach table test permanently;
```

**Comment by tavplubix** [comment]
I think it should not be possible to create table with the same name as some permanently detached one has

**Comment by tavplubix** [comment]
Also it would be great to support `DETACH TABLE ... PERMANENTLY` for `MySQL` database engine, because `DatabaseConnectionMySQL::dropTable(...)` actually detaches table permanently.

File: src/Databases/DatabaseOnDisk.cpp (hunk 1 above)
Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:228]: footgun

:) 

Isn't it possible already with normal detach?

Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:228]: It's not... 
```
Received exception from server (version 20.12.1):
Code: 521. DB::Exception: Received from localhost:9000. DB::Exception: Cannot rename /var/lib/clickhouse/store/78e/78ed63b2-169a-444d-88c7-b77b60f7bfbc/test.sql.tmp to /var/lib/clickhouse/store/78e/78ed63b2-169a-444d-88c7-b77b60f7bfbc/test.sql because the second path already exists, errno: 17, strerror: File exists. 
```

Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:223]: I've added some extra checks, see 
https://github.com/ClickHouse/ClickHouse/pull/17642/commits/d9a710db774abd3c0b8b6c104829235866408b21
(will add some tests in a while)

I think that at that moment when table was already attached and has new metadata file (with .SQL extension) it's too late to do something smart with .sql_detached and the best we can do is just remove that file.

File: src/Databases/DatabaseOnDisk.cpp (hunk 2 above)
Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp:245]: Even in that case - we can't reattach the original table back (it's name was taken by newer table), so keeping the original .sql_detached file will be not very useful.

added a checks to prevent reusing the table name while it's detached, I think that should be ok now (will add your test).

**Comment by filimonov** [comment]
> I think it should not be possible to create table with the same name as some permanently detached one has

+1. I think that should prevent that. https://github.com/ClickHouse/ClickHouse/pull/17642/commits/d9a710db774abd3c0b8b6c104829235866408b21

WIll add tests...

**Comment by filimonov** [comment]
> Also it would be great to support `DETACH TABLE ... PERMANENTLY` for `MySQL` database engine, because `DatabaseConnectionMySQL::dropTable(...)` actually detaches table permanently.

Indeed. Added that, I will NOT add tests (a bit cumbersome), and since now dropTable uses detachTablePermanently i guess we can consider it as covered.

File: src/Databases/DatabaseOnDisk.cpp (hunk 3 above)
Comment (filimonov) [reply src/Databases/DatabaseOnDisk.cpp]: ok. removed, will add some simple test.

File: src/Databases/DatabaseOnDisk.cpp [hunk 4]
```diff
@@ -297,6 +292,43 @@ void DatabaseOnDisk::dropTable(const Context & context, const String & table_nam
     Poco::File(table_metadata_path_drop).remove();
 }
 
+
+/// will throw when the table exists (in active / detached / detached permanently form) and we try to do to wrong create
```
Comment (filimonov) [inline src/Databases/DatabaseOnDisk.cpp:292]: and we try <cencored> :)

File: src/Databases/DatabaseOnDisk.cpp [hunk 5]
```diff
@@ -299,6 +374,9 @@ void DatabaseOnDisk::renameTable(
         if (from_atomic_to_ordinary)
             create.uuid = UUIDHelpers::Nil;
 
+        if (auto * target_db = dynamic_cast<DatabaseOnDisk *>(&to_database))
+            target_db->checkMetadataFilenameAvailability(to_table_name);
```
Comment (filimonov) [inline src/Databases/DatabaseOnDisk.cpp:378]: that fixes the bug - see test 1603.

**Review by tavplubix — APPROVED** [review]

File: tests/queries/0_stateless/01600_detach_permanently.sh [hunk 6]
```diff
@@ -0,0 +1,125 @@
+#!/usr/bin/env bash
+
+CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+. "$CURDIR"/../shell_config.sh
+
+## tests with real clickhouse restart would be a bit to heavy,
+## to ensure the table will not reappear back clickhose-local is enough.
```
[the remark this answers is not in the document]
Comment (filimonov) [reply tests/queries/0_stateless/01600_detach_permanently.sh:7]: Yeah, i've reinvited that wheel in the 01601 test :) For some reason that idea didn't come to my mind at the beginining... But since the goal (creating the test) is archived, i would keep it as is.

**Comment by tavplubix** [comment]
AST fuzzer - #18190
