### PR TITLE
Fix deadlock in system.text_log

### LINKED ISSUE #19874: Deadlock is possible if system.text_log is enabled.
**Describe the bug**
```
| | | | | | | | | 5    0x000000000e3a5ec1 in DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) ()
| | | | | | | | | | 2    0x000000000e3aadc6 in DB::logQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context const&, bool) ()
| | | | | | | | | | | 2    0x000000000887a195 in DB::OwnSplitChannel::log(Poco::Message const&) ()
| | | | | | | | | | | | 2    0x000000000887a7fa in DB::OwnSplitChannel::logSplit(Poco::Message const&) ()
| | | | | | | | | | | | | 2    0x000000000887acb6 in DB::SystemLog<DB::TextLogElement>::add(DB::TextLogElement const&) ()
| | | | | | | | | | | | | | 1    0x0000000011976246 in std::__1::mutex::lock() ()
| | | | | | | | | | | | | | | 1    0x00000000087495a1 in pthread_mutex_lock ()
| | | | | | | | | | | | | | | | 1    0x00007f074da790a3 in __GI___pthread_mutex_lock at ../nptl/pthread_mutex_lock.c:80
| | | | | | | | | | | | | | | | | 1    __lll_lock_wait at lowlevellock.c:52
| | | | | | | | | | | | | 2    0x000000000887ae28 in DB::SystemLog<DB::TextLogElement>::add(DB::TextLogElement const&) ()
| | | | | | | | | | | | | | 1    0x000000000887c62c in void std::__1::vector<DB::TextLogElement, std::__1::allocator<DB::TextLogElement> >::__push_back_slow_path<DB::TextLogElement const&>(DB::TextLogElement const&) ()
| | | | | | | | | | | | | | | 1    0x00000000087156fb in operator new(unsigned long) ()
| | | | | | | | | | | | | | | | 1    0x0000000008727744 in MemoryTracker::alloc(long) ()
| | | | | | | | | | | | | | | | | 1    0x000000000872727c in MemoryTracker::logMemoryUsage(long) const ()
| | | | | | | | | | | | | | | | | | 1    0x000000000887a195 in DB::OwnSplitChannel::log(Poco::Message const&) ()
| | | | | | | | | | | | | | | | | | | 1    0x000000000887a7fa in DB::OwnSplitChannel::logSplit(Poco::Message const&) ()
| | | | | | | | | | | | | | | | | | | | 1    0x000000000887acb6 in DB::SystemLog<DB::TextLogElement>::add(DB::TextLogElement const&) ()
| | | | | | | | | | | | | | | | | | | | | 1    0x0000000011976246 in std::__1::mutex::lock() ()
| | | | | | | | | | | | | | | | | | | | | | 1    0x00000000087495a1 in pthread_mutex_lock ()
| | | | | | | | | | | | | | | | | | | | | | | 1    0x00007f074da790a3 in __GI___pthread_mutex_lock at ../nptl/pthread_mutex_lock.c:80
| | | | | | | | | | | | | | | | | | | | | | | | 1    __lll_lock_wait at lowlevellock.c:52
```

**How to reproduce**
```
clickhouse-benchmark -i 1000000 -c16 --secure --query "SELECT 1"
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Deadlock was possible if system.text_log is enabled. This fixes #19874.

### CODE REVIEW

File: src/Interpreters/SystemLog.h [hunk 1]
```diff
@@ -229,9 +230,18 @@ void SystemLog<LogElement>::startup()
 }
 
 
+static thread_local bool recursive_add_call = false;
+
 template <typename LogElement>
 void SystemLog<LogElement>::add(const LogElement & element)
 {
+    /// It is possible that the method will be called recursively.
```
Comment (alesapin) [inline src/Interpreters/SystemLog.h:238]: But how is it possible? Inner logging inside text_log itself? This comment doesn't help at all.

Comment (alexey-milovidov) [reply src/Interpreters/SystemLog.h:238]: std::vector::push_back -> operator new -> MemoryTracker::alloc -> MemoryTracker::logPeakMemoryUsage -> logger -> SystemLog<TextLog>::add

**Comment by alexey-milovidov** [comment]
@azat FYI this appeared after a change that `MemoryTracker::BlockerInThread` stopped to block total memory tracker.

File: src/Interpreters/SystemLog.h [hunk 2]
```diff
@@ -229,9 +230,18 @@ void SystemLog<LogElement>::startup()
...
+    /// Better to drop these events to avoid complications.
+    if (recursive_add_call)
+        return;
+    recursive_add_call = true;
+    SCOPE_EXIT({ recursive_add_call = false; });
```
Comment (azat) [inline src/Interpreters/SystemLog.h:243]: Why not simply `MemoryTracker::BlockerInThread temporarily_disable_memory_tracker(VariableContext::Global)` ?

Comment (alexey-milovidov) [reply src/Interpreters/SystemLog.h:243]: Current solution is more generic - it will avoid all possible recursive function calls.
Also total memory will be accounted correctly.
