### PR TITLE
Better exception for non existing tables for data lakes

### LINKED ISSUE #81211: SHOW CREATE TABLE shows confusing error for missing Iceberg/Glue tables
### Describe the improvement

When using SHOW CREATE TABLE with a Glue or Iceberg catalog, ClickHouse returns a low-level error if the table doesn’t exist.

Example:  

I have a database with the DataLakeCatalog engine named `datalake`, configured to use the REST catalog.

```sql
USE datalake;
SHOW CREATE TABLE `iceberg.name1`;
```
```
Code: 86. DB::Exception: Received from localhost:9000. DB::HTTPException. DB::HTTPException: Received error from remote server http://rest-catalog:8181/v1/namespaces/iceberg/tables/name1. HTTP status code: 404 'Not Found', body length: 100 bytes, body: '{"error":{"message":"Table does not exist: iceberg.name1","type":"NoSuchTableException","code":404}}'. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER)
```
Expected behavior — same as regular ClickHouse tables:
```
Code: 390. DB::Exception: Received from localhost:9000. DB::Exception: Table `iceberg.name1` doesn't exist. (CANNOT_GET_CREATE_TABLE_QUERY)
```

With Glue catalog, the message is also unclear:
```
Code: 736. DB::Exception: Received from localhost:9000. DB::Exception: Exception calling GetTable for table iceberg.name1: Unable to find Glue table "name1" in DB "iceberg", catalog "None". (DATALAKE_DATABASE_ERROR)
```
It would be great if all catalog types returned a consistent and user-friendly message when a table is missing.

Thanks!

### Which ClickHouse versions are affected?

All versions where database DataLakeCatalog is supported.

### How to reproduce

1. Create database DataLakeCatalog.
2. Run `SHOW CREATE TABLE` on a non-existent table in that database.

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now database Datalake throw more convenient exception. Fixes #81211.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/DataLake/DatabaseDataLake.cpp [hunk 1]
```diff
@@ -596,7 +597,12 @@ ASTPtr DatabaseDataLake::getCreateTableQueryImpl(
     auto table_metadata = DataLake::TableMetadata().withLocation().withSchema();
 
     const auto [namespace_name, table_name] = parseTableName(name);
-    catalog->getTableMetadata(namespace_name, table_name, table_metadata);
+
+    if (!catalog->tryGetTableMetadata(namespace_name, table_name, table_metadata))
```
Comment (kssenii) [inline src/Databases/DataLake/DatabaseDataLake.cpp:601]: Why not leave it as `catalog->getTableMetadata` as it will also throw a good exception message since this PR?

Comment (alesapin) [reply src/Databases/DataLake/DatabaseDataLake.cpp:601]: For RestCatalog it will not.

**Review by kssenii — APPROVED** [review]

**Comment by alesapin** [comment]
`02160_client_autocomplete_parse_query` fixed in https://github.com/ClickHouse/ClickHouse/issues/81893

**Comment by alesapin** [comment]
Fuzzer https://github.com/ClickHouse/ClickHouse/issues/81144

**Comment by alesapin** [comment]
Sync is green, fixed manually

**Comment by tavplubix** [comment]
> Sync is green

It was not green actually
