### PR TITLE
Fix: remove redundant distinct with window functions

### LINKED ISSUE #62820: Exception Cannot find column if make select distinct from view and view contains window function and group by
If the view contains a grouping and a windowing function, querying with distinct results in an error.

CREATE TABLE default.t
(
    `id` Int32,
    `val` Nullable(Float64),
    `dt` Nullable(DateTime64(6)),
    `type` Nullable(Int32)
)
ENGINE = MergeTree
ORDER BY id

CREATE VIEW default.t_v
AS SELECT
    t1.type AS type,
    sum(t1.val) AS sval,
    toStartOfDay(t1.dt) AS sday,
    anyLast(sum(t1.val)) OVER w
FROM default.t AS t1
GROUP BY
    type,
    t1.dt
WINDOW w AS (PARTITION BY type ORDER BY dt ASC ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)

SELECT DISTINCT type
FROM t_v

Received exception from server (version 24.3.2):
Code: 47. DB::Exception: Received from 84.201.141.233:9000. DB::Exception: Cannot find column anyLast(sum(__table1.val)) OVER (PARTITION BY __table1.type ORDER BY __table1.dt ASC ROWS BETWEEN UNBOUNDED PRECEDING AND 1_UInt8 PRECEDING) in ActionsDAG result. (UNKNOWN_IDENTIFIER)

Example in fiddle
https://fiddle.clickhouse.com/f3f2dac4-183d-4748-85ae-9b25452684c9

The problem is also reproduced on new installations and in 24.1.8.22

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`query_plan_remove_redundant_distinct` can break queries with WINDOW FUNCTIONS (with `allow_experimental_analyzer` is on). Fixes #62820

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

<details>

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit a7898c85b806a036a1337403006e2fdaa7c95f31 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63776/a7898c85b806a036a1337403006e2fdaa7c95f31/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Processors/QueryPlan/Optimizations/removeRedundantDistinct.cpp [hunk 1]
```diff
@@ -163,6 +171,12 @@ namespace
                 break;
             }
 
+            if (typeid_cast<const WindowStep *>(current_step))
```
Comment (devcrafter) [inline src/Processors/QueryPlan/Optimizations/removeRedundantDistinct.cpp:174]: Add comment

**Review by KochetovNicolai — APPROVED** [review]
