### PR TITLE
Do not optimize GROUP BY functions that shadow their arguments

### LINKED ISSUE #37032: `Not found column` in distributed query with aggregation and alias
Hi,
There is a problem with toString in version 22.3lts.

```sql
select toString(dummy) as dummy
 from clusterAllReplicas(cluster,system,one)
 group by dummy;
DB::Exception: Not found column dummy in block. There are only columns: toString(dummy): While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK)
```
version:  all release tag in 22.3 lts

Thanks

### PR DESCRIPTION
**Pull request by tonickkozlov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not optimise functions in GROUP BY statements if they shadow one of the table columns or expressions.
Fixes https://github.com/ClickHouse/ClickHouse/issues/37032

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by tonickkozlov** [comment]
@azat please take a look if you have a moment: this change is ready for review, thanks!

File: src/Interpreters/TreeOptimizer.cpp [hunk 1]
```diff
@@ -153,6 +153,17 @@ void optimizeGroupBy(ASTSelectQuery * select_query, ContextPtr context)
                     continue;
                 }
             }
+            /// don't optimise functions that shadow any of it's arguments:
+            /// https://github.com/ClickHouse/ClickHouse/issues/37032
+            if (std::any_of(
+                    function->arguments->children.begin(),
+                    function->arguments->children.end(),
+                    [&function](const ASTPtr & arg) { return function->alias == arg->getAliasOrColumnName(); }))
```
Comment (azat) [inline src/Interpreters/TreeOptimizer.cpp:161]: This will not work for functions inside functions, I guess you need to write a visitor here:

```sql
SELECT toString(dummy+0) as dummy FROM remote('127.{1,1}', 'system.one') GROUP BY dummy;
Code: 43. DB::Exception: Illegal types String and UInt8 of arguments of function plus: While processing (toString(dummy + 0) AS dummy) + 0. (ILLEGAL_TYPE_OF_ARGUMENT)
```

Comment (tonickkozlov) [reply src/Interpreters/TreeOptimizer.cpp]: Thanks for the catch @azat . Submitted a fix, please take a look.

**Comment by tonickkozlov** [comment]
Stress test is failing on backward compatibility check - error seems to be related. Could I please get some help figuring out what the failure is and how to repro it in my local environment? Thank you!

**Comment by tonickkozlov** [comment]
Also I'm a bit surprised by the fact that my previous change (the one without the visitor) was passing all checks.

**Comment by azat** [comment]
>Stress test is failing on backward compatibility check - error seems to be related. Could I please get some help figuring out what the failure is and how to repro it in my local environment?

It is not related to your change, I will take a look (since this that was my change - #39299)

>Also I'm a bit surprised by the fact that my previous change (the one without the visitor) was passing all checks.

Well, because there was no such test on CI.

File: src/Interpreters/TreeOptimizer.cpp [hunk 2]
```diff
@@ -153,6 +154,19 @@ void optimizeGroupBy(ASTSelectQuery * select_query, ContextPtr context)
                     continue;
                 }
             }
+            /// don't optimise functions that shadow any of it's arguments:
+            /// https://github.com/ClickHouse/ClickHouse/issues/37032
```
Comment (azat) [inline src/Interpreters/TreeOptimizer.cpp:158]: It is better to give an example here instead of just a link to the issue

File: src/Interpreters/FunctionMaskingArgumentCheckVisitor.h [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+{
+
+/// Checks from bottom to top if a function's alias shadows the name
+/// of one of it's arguments
+class FunctionMaskingArgumentCheckMatcher
+{
+public:
+    struct Data
+    {
+        String alias;
```
Comment (azat) [inline src/Interpreters/FunctionMaskingArgumentCheckVisitor.h:19]: Minor but you can use `const String &` here.

**Review by azat — COMMENTED** [review]
LGTM, and now some one from the official team should take a look.

**Comment by tonickkozlov** [comment]
@alexey-milovidov could you or someone from the team take a look please? Appreciate it!

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql [hunk 4]
```diff
@@ -0,0 +1,5 @@
+SET prefer_localhost_replica=0;
+SELECT toString(dummy) as dummy FROM remote('127.{1,1}', 'system.one') GROUP BY dummy;
+SELECT toString(dummy+1) as dummy FROM remote('127.{1,1}', 'system.one') GROUP BY dummy;
+SELECT toString((toInt8(dummy)+2) * (toInt8(dummy)+2)) as dummy FROM remote('127.{1,1}', system.one) GROUP BY dummy;
+SELECT round(number % 3) AS number FROM remote('127.{1,1}', numbers(20)) GROUP BY number ORDER BY number ASC;
```
Comment (devcrafter) [inline tests/queries/0_stateless/02352_grouby_shadows_arg.sql:5]: just FYI this query worked before the fix

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql [hunk 5]
```diff
@@ -0,0 +1,5 @@
+SET prefer_localhost_replica=0;
+SELECT toString(dummy) as dummy FROM remote('127.{1,1}', 'system.one') GROUP BY dummy;
```
Comment (devcrafter) [inline tests/queries/0_stateless/02352_grouby_shadows_arg.sql:2]: Please add `-- { echoOn }`, so reference file will contain query and corresponding result

File: src/Interpreters/FunctionMaskingArgumentCheckVisitor.h [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+#include <DataTypes/Serializations/ISerialization.h>
+#include <Interpreters/InDepthNodeVisitor.h>
+#include <Parsers/ASTFunction.h>
+#include <Parsers/ASTIdentifier.h>
+
+namespace DB
+{
+
+/// Checks from bottom to top if a function's alias shadows the name
+/// of one of it's arguments
```
Comment (devcrafter) [inline src/Interpreters/FunctionMaskingArgumentCheckVisitor.h:13]: It'd be nice to have simplest query example here

**Review by devcrafter — COMMENTED** [review]
Looks good, please fix the comments, and we can merge

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql (hunk 4 above)
Comment (tonickkozlov) [reply tests/queries/0_stateless/02352_grouby_shadows_arg.sql:5]: It did, just making sure we fix the desired behaviour in the test as well.

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql [hunk 7]
```diff
@@ -0,0 +1,5 @@
+SET prefer_localhost_replica=0;
```
[the remark this answers is not in the document]
Comment (tonickkozlov) [reply tests/queries/0_stateless/02352_grouby_shadows_arg.sql:1]: The bug only appears in distributed queries that go through the network.  This setting seems like the quickest way to reproduce that.
My understanding is without the setting CH optimizes the `remote` call and replaces it with a local query plan.

**Comment by tonickkozlov** [comment]
> Looks good, please fix the comments, and we can merge

Thanks for your review @devcrafter . Addressed your comments, please take another look.

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql (hunk 7 above)
[the remark this answers is not in the document]
Comment (devcrafter) [reply tests/queries/0_stateless/02352_grouby_shadows_arg.sql:1]: I guess that this PR fixes the following error as well:
```sql
SELECT toString(dummy) AS dummy
FROM remote('127.{1,1}', 'system.one')
GROUP BY dummy
SETTINGS prefer_localhost_replica = 1
...
Received exception from server (version 22.8.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `dummy` in source stream, there are only columns: [toString(dummy)]. (THERE_IS_NO_COLUMN)
```

Would you mind to check?

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql [hunk 8]
```diff
@@ -0,0 +1,5 @@
...
+SELECT toString(dummy) as dummy FROM remote('127.{1,1}', 'system.one') GROUP BY dummy; -- { echoOn }
```
Comment (devcrafter) [inline tests/queries/0_stateless/02352_grouby_shadows_arg.sql:2]: Sorry, I probably need to be more clear. Please add it once before queries:
```suggestion
-- { echoOn }
SELECT toString(dummy) as dummy FROM remote('127.{1,1}', 'system.one') GROUP BY dummy;
```
It's useful to get more readable `reference` files. And use `-- { echoOff }` when echoing is not necessary any more. Typically, it's test clean-up queries like`DROP TABLE`

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql (hunk 7 above)
[the remark this answers is not in the document]
Comment (tonickkozlov) [reply tests/queries/0_stateless/02352_grouby_shadows_arg.sql:1]: Verified, it does fix this error as well.

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql (hunk 8 above)
Comment (tonickkozlov) [reply tests/queries/0_stateless/02352_grouby_shadows_arg.sql]: Thanks for explaining, didn't know this annotation existed. Updated the test now.

File: tests/queries/0_stateless/02352_grouby_shadows_arg.sql (hunk 7 above)
[the remark this answers is not in the document]
Comment (devcrafter) [reply tests/queries/0_stateless/02352_grouby_shadows_arg.sql:1]: It should mean that this setting can be omitted (it'll be randomized, see [settings randomizer](https://github.com/ClickHouse/ClickHouse/blob/f150966f1028ffeef44f61bd8c5c2f170183cd36/tests/clickhouse-test#L421)), or we can execute the same queries with different setting values.

**Review by devcrafter — APPROVED** [review]
LGTM, let's wait for tests
