### PR TITLE
Fix unexpected errors in system.errors after join

### LINKED ISSUE #51487: system.errors contains errors about UNKNOWN_IDENTIFIER but result of query correcntly returns
**Describe what's wrong**

https://fiddle.clickhouse.com/c84cacb1-52da-48e2-9847-b9c825822adf
```sql
SELECT *
FROM
(
    SELECT *
    FROM system.numbers
    LIMIT 2
) AS n1
INNER JOIN
(
    SELECT *
    FROM system.numbers
    LIMIT 2
) AS n2 ON n1.number = n2.number
FORMAT Vertical;
```
return good result

but
```sql
SELECT * FROM system.errors FORMAT Vertical;

Row 1:
──────
name:               UNKNOWN_IDENTIFIER
code:               47
value:              1
last_error_time:    2023-06-27 14:14:10
last_error_message: Missing columns: 'n2.number' 'number' while processing query: 'number = n2.number', required columns: 'number' 'n2.number' 'number' 'n2.number'
last_error_trace:   [238324885,142758764,333694553,333731958,334242974,333710837,330390322,330372317,331033798,331024595,330082110,334346583,334332846,348996900,349085817,398655028,398659665,400219399,400209724,140092740037443,140092740631476]
remote:             0
```

Doesn't reproduce with analyzer

https://fiddle.clickhouse.com/3460c127-cf5b-451d-9b17-1b3948e9cc99

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix unexpected errors in `system.errors` after join, close https://github.com/ClickHouse/ClickHouse/issues/51487

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: src/Interpreters/TreeRewriter.cpp [hunk 1]
```diff
@@ -604,15 +604,13 @@ std::optional<bool> tryEvaluateConstCondition(ASTPtr expr, ContextPtr context)
 
     Field eval_res;
     DataTypePtr eval_res_type;
-    try
     {
-        std::tie(eval_res, eval_res_type) = evaluateConstantExpression(expr, context);
-    }
-    catch (DB::Exception &)
-    {
-        /// not a constant expression
```
Comment (alexey-milovidov) [inline src/Interpreters/TreeRewriter.cpp:613]: Thank you! This type of code is always wrong because there can be a memory limit exception, fault injection, or anything else.

Interesting how we can prevent having this code in other places.
