### PR TITLE
Fix possible crash for SELECT from Merge table

### LINKED ISSUE #41269: Clickhouse got stuck and had thrown a coredump
Clickhouse got stuck and had thrown a coredump
Optimize table process has been started there before the fail

**Does it reproduce on recent release?**

v22.3.6.5-lts

**Error message and/or stacktrace**

https://pastila.nl/?00ea0713/9ad972e00fde60564ff00853050fcc1d

Can't provide the coredump file for NDA reason, but ready to analyse it

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible crash in `SELECT` from `Merge` table with enabled `optimize_monotonous_functions_in_order_by` setting. Fixes #41269

### CODE REVIEW

File: src/Interpreters/MonotonicityCheckVisitor.h [hunk 1]
```diff
@@ -70,6 +70,9 @@ class MonotonicityCheckMatcher
             if (!pos)
                 return false;
 
+            if (*pos >= tables.size())
```
Comment (alexey-milovidov) [inline src/Interpreters/MonotonicityCheckVisitor.h:73]: I don't understand the code.
Why one of the previous functions can return invalid "pos"?

Comment (KochetovNicolai) [reply src/Interpreters/MonotonicityCheckVisitor.h:73]: Because `IdentifierSemantic::getMembership` returns a position stored in AST. This position happened to be invalid while we were trying to re-analyze a part of AST somewhere from StorageMerge.

Comment (KochetovNicolai) [reply src/Interpreters/MonotonicityCheckVisitor.h:73]: Basically I hope that we remove IdentifierSemantic after Analyzer is merged. It is vary hard to use it reliably.

**Review by alexey-milovidov — APPROVED** [review]
LGTM.
Write this directly in a comment in the code.

**Comment by KochetovNicolai** [comment]
Style Check is ok, merging.
