### PR TITLE
Distinguish Array and Tuple field types when creating from array of Fields.

### LINKED ISSUE #7176: Tuples can be used in ORDER BY but cannot be directly compared when engine is MergeTree
To reproduce: server 19.14.3.3 with CLI client.
```
2177cc704f03 :) CREATE TABLE T2( a Tuple(DateTime, Int32)) ENGINE = MergeTree() ORDER BY a;

CREATE TABLE T2
(
    `a` Tuple(DateTime, Int32)
)
ENGINE = MergeTree()
ORDER BY a

Ok.

0 rows in set. Elapsed: 0.006 sec.

2177cc704f03 :) INSERT INTO T2 (a) VALUES (('2018-01-01 00:00:00', 1));

INSERT INTO T2 (a) VALUES

Ok.

1 rows in set. Elapsed: 0.003 sec.

2177cc704f03 :) SELECT * FROM T2 WHERE a < tuple(toDateTime('2019-01-01 00:00:00'), 0);

SELECT *
FROM T2
WHERE a < (toDateTime('2019-01-01 00:00:00'), 0)

Received exception from server (version 19.14.3):
Code: 169. DB::Exception: Received from localhost:9000. DB::Exception: Cannot compare std::vector<DB::Field, std::allocator<DB::Field> > with StrongTypedef<std::vector<DB::Field, std::allocator<DB::Field> >, DB::TupleTag>.

0 rows in set. Elapsed: 0.004 sec.
```

Interestingly enough, when engine is Memory, everything works.

### PR DESCRIPTION
**Pull request by akuzm**
Category (leave one):
- Build/Testing/Packaging Improvement

Short description (up to few sentences):
Fix some issues in Fields found by MemorySanitizer.

Requires #7212
Fixes #7176

### CODE REVIEW

File: dbms/src/Core/Field.h [hunk 1]
```diff
@@ -34,9 +34,23 @@ template <typename T>
 using NearestFieldType = typename NearestFieldTypeImpl<T>::Type;
 
 class Field;
-using Array = std::vector<Field>;
-using TupleBackend = std::vector<Field>;
```
Comment (alesapin) [inline dbms/src/Core/Field.h]: Why we needed this before? It seems very confusing and bug-prone.

Comment (akuzm) [reply dbms/src/Core/Field.h]: TupleBackend definition looks redundant, but otherwise it's the same thing that I'm doing: have strong typedefs for Array and Tuple fields so that the correct type is deduced by the Field constructor. Actually I'm not even changing this, just renaming: the only place where I changed behavior is in convertFieldToTypeImpl: it won't return Array fields for a Tuple type anymore. Had to re-read this PR to realize what is going on :)

Not sure, maybe it's better to throw away these types and just specify the Field type explicitly.

**Comment by akuzm** [comment]
Can't reproduce the ubsan failure locally even on the deb package from the CI. Rebased to master hoping that it'll go away.
