### PR TITLE
Fix terribly low performance of `LineAsString` format

### LINKED ISSUE #34303: `ProfileEvents::increment` can be in top if you run a query with huge number of threads.
**Describe the situation**
https://markify.dev/p/zfrQMV2/text

**How to reproduce**
On aws `c5ad.24xlarge` run a query:

```
SET max_memory_usage = '100G', max_threads = 1000, max_insert_threads = 96

INSERT INTO wikistat WITH
    parseDateTimeBestEffort(extract(toLowCardinality(_path), 'pageviews-([\\d\\-]+)\\.gz$')) AS time,
    splitByChar(' ', line) AS values,
    splitByChar('.', values[1]) AS projects
SELECT
    time,
    projects[1] AS project,
    projects[2] AS subproject,
    values[2] AS path,
    CAST(values[3], 'UInt64') AS hits
FROM s3('https://....s3.eu-central-1.amazonaws.com/wikistat/original/*.gz', '...', '...', LineAsString, auto)
WHERE length(values) >= 3
```

Performance is not bad (22 million rows are inserted per second) but can be better.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improve performance of `LineAsString` format. This closes #34303.

### CODE REVIEW

File: src/Processors/Formats/Impl/LineAsStringRowInputFormat.cpp [hunk 1]
```diff
@@ -27,28 +31,16 @@ void LineAsStringRowInputFormat::resetParser()
...
 {
-    DB::Memory<> object;
-
-    char * pos = in->position();
-    bool need_more_data = true;
+    ColumnString & column_string = assert_cast<ColumnString &>(column);
+    auto & chars = column_string.getChars();
+    auto & offsets = column_string.getOffsets();
 
-    while (loadAtPosition(*in, object, pos) && need_more_data)
```
Comment (alexey-milovidov) [inline src/Processors/Formats/Impl/LineAsStringRowInputFormat.cpp:35]: Extra allocation and copying.

File: src/Processors/Formats/Impl/LineAsStringRowInputFormat.cpp [hunk 2]
```diff
@@ -14,7 +16,9 @@ namespace ErrorCodes
 LineAsStringRowInputFormat::LineAsStringRowInputFormat(const Block & header_, ReadBuffer & in_, Params params_) :
     IRowInputFormat(header_, in_, std::move(params_))
 {
-    if (header_.columns() > 1 || header_.getDataTypes()[0]->getTypeId() != TypeIndex::String)
```
Comment (alexey-milovidov) [inline src/Processors/Formats/Impl/LineAsStringRowInputFormat.cpp:17]: And this was also wrong.

**Review by kitaisreal — APPROVED** [review]
