### PR TITLE
Cancel merges before acquiring lock for truncate

### LINKED ISSUE #34302: TRUNCATE TABLE does not cancel merges
**Describe the situation**

```
ip-172-31-22-38.eu-central-1.compute.internal :) TRUNCATE wikistat

TRUNCATE TABLE wikistat

Query id: 3a045ee6-201c-4551-9bc1-3cda53376ec2


0 rows in set. Elapsed: 120.008 sec. 

Received exception from server (version 22.2.1):
Code: 473. DB::Exception: Received from localhost:9000. DB::Exception: WRITE locking attempt on "default.wikistat" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. (DEADLOCK_AVOIDED)

ip-172-31-22-38.eu-central-1.compute.internal :) TRUNCATE wikistat

TRUNCATE TABLE wikistat

Query id: 4fae1b33-c9cb-45de-8ff2-140d9cba3aa2

Ok.

0 rows in set. Elapsed: 31.647 sec. 

ip-172-31-22-38.eu-central-1.compute.internal :)
```

```
┌─arrayJoin(arrayMap(lambda(tuple(x), demangle(addressToSymbol(x))), trace))─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                                                                                                            │
│ std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)                            │
│ DB::RWLockImpl::getLock(DB::RWLockImpl::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&)                                     │
│ DB::IStorage::tryLockTimed(std::__1::shared_ptr<DB::RWLockImpl> const&, DB::RWLockImpl::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) const │
│ DB::IStorage::lockExclusively(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&)                                                     │
│ DB::InterpreterDropQuery::executeToTableImpl(std::__1::shared_ptr<DB::Context const>, DB::ASTDropQuery&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&)                                            │
│ DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&)                                                                                                                                                                                                │
│ DB::InterpreterDropQuery::execute()                                                                                                                                                                                                                        │
│ DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)                                                                                                                   │
│ DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum)                                                                    │
│ DB::TCPHandler::runImpl()                                                                                                                                                                                                                                  │
│ DB::TCPHandler::run()                                                                                                                                                                                                                                      │
│ Poco::Net::TCPServerConnection::start()                                                                                                                                                                                                                    │
│ Poco::Net::TCPServerDispatcher::run()                                                                                                                                                                                                                      │
│ Poco::PooledThread::run()                                                                                                                                                                                                                                  │
│ Poco::ThreadImpl::runnableEntry(void*)
```

### PR DESCRIPTION
**Pull request by tavplubix**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Cancel merges before acquiring table lock for `TRUNCATE` query to avoid `DEADLOCK_AVOIDED` error in some cases. Fixes  #34302

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Review by alesapin — APPROVED** [review]

File: src/Interpreters/InterpreterDropQuery.cpp [hunk 1]
```diff
@@ -202,7 +206,15 @@ BlockIO InterpreterDropQuery::executeToTableImpl(ContextPtr context_, ASTDropQue
 
             table->checkTableCanBeDropped();
 
-            auto table_lock = table->lockExclusively(context_->getCurrentQueryId(), context_->getSettingsRef().lock_acquire_timeout);
+            TableExclusiveLockHolder table_lock;
+            /// We don't need this lock for ReplicatedMergeTree
+            if (!table->supportsReplication())
+            {
+                /// And for simple MergeTree we can stop merges before acquiring the lock
+                auto merges_blocker = table->getActionLock(ActionLocks::PartsMerge);
```
Comment (Algunenano) [inline src/Interpreters/InterpreterDropQuery.cpp:214]: This code looks incorrect. The locks go out of scope immediately, so truncate() is being called without holding them, right?

Comment (tavplubix) [reply src/Interpreters/InterpreterDropQuery.cpp:214]: Yep, it's incorrect, will be fixed in https://github.com/ClickHouse/ClickHouse/pull/41145
