### PR TITLE
Fix insert LC to TinyLog

### LINKED ISSUE #18629: Logical error: Got empty stream for DataTypeLowCardinality keys
```
milovidov-desktop :) CREATE TABLE perf_lc_num(　        num UInt8,　        arr Array(LowCardinality(Int64)) default [num]　        ) ENGINE = TinyLog

CREATE TABLE perf_lc_num
(
    `num` UInt8,
    `arr` Array(LowCardinality(Int64)) DEFAULT [num]
)
ENGINE = TinyLog

Query id: e95f9a71-5795-4dea-8d80-4729fc8016b9

Ok.

0 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) INSERT INTO perf_lc_num (num)
:-]         SELECT toUInt8(number)
:-]         FROM numbers(100000000)

INSERT INTO perf_lc_num (num) SELECT toUInt8(number)
FROM numbers(100000000)

Query id: 1101fd75-a545-4809-acb5-8afa2fae80c0


Received exception from server (version 20.13.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Got empty stream for DataTypeLowCardinality keys.: While executing SinkToOutputStream. 

0 rows in set. Elapsed: 0.045 sec. 

milovidov-desktop :) INSERT INTO perf_lc_num (num)　        SELECT toUInt8(number)　        FROM numbers(100000000)

INSERT INTO perf_lc_num (num) SELECT toUInt8(number)
FROM numbers(100000000)

Query id: 0ad8532a-5c6e-4590-84cd-7e00759d152d


Received exception from server (version 20.13.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Got empty stream for DataTypeLowCardinality keys.: While executing SinkToOutputStream. 

0 rows in set. Elapsed: 0.033 sec.
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix inserting of `LowCardinality` column to table with `TinyLog` engine. Fixes #18629

### CODE REVIEW

File: tests/queries/0_stateless/01651_lc_insert_tiny_log.sql [hunk 1]
```diff
@@ -0,0 +1,15 @@
+drop table if exists perf_lc_num;
+
+CREATE TABLE perf_lc_num(　        num UInt8,　        arr Array(LowCardinality(Int64)) default [num]　        ) ENGINE = TinyLog;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01651_lc_insert_tiny_log.sql:3]: Maybe copy-paste this test for Log, StripeLog - just in case?

File: src/Storages/StorageTinyLog.cpp [hunk 2]
```diff
@@ -294,11 +294,15 @@ IDataType::OutputStreamGetter TinyLogBlockOutputStream::createStreamGetter(
 void TinyLogBlockOutputStream::writeData(const String & name, const IDataType & type, const IColumn & column, WrittenStreams & written_streams)
 {
     IDataType::SerializeBinaryBulkSettings settings;
-    settings.getter = createStreamGetter(name, written_streams);
 
     if (serialize_states.count(name) == 0)
+    {
+        WrittenStreams prefix_written_streams;
```
Comment (alexey-milovidov) [inline src/Storages/StorageTinyLog.cpp:300]: Could you please add a comment - many people will read this code as an example...

File: tests/queries/0_stateless/01651_lc_insert_tiny_log.sql (hunk 1 above)
Comment (KochetovNicolai) [reply tests/queries/0_stateless/01651_lc_insert_tiny_log.sql:3]: Done

File: src/Storages/StorageTinyLog.cpp (hunk 2 above)
Comment (KochetovNicolai) [reply src/Storages/StorageTinyLog.cpp:302]: Added

**Review by alexey-milovidov — APPROVED** [review]
