### PR TITLE
Fix some uncaught exceptions (in SCOPE_EXIT) under memory pressure

### LINKED ISSUE #22689: Stress test: uncaught exception during parallel parsing
```
2021.04.05 20:49:10.082954 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Debug> executeQuery: (from [::1]:51658, using production parser) (comment: '/usr/share/clickhouse-test/queries/1_stateful/00159_parallel_formatting_tsv_and_friends.sh') SELECT ClientEventTime as a, MobilePhoneModel as b, ClientIP6 as c FROM test.hits ORDER BY a, b, c Format TSVWithNames
2021.04.05 20:49:10.091259 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Trace> ContextAccess (default): Access granted: SELECT(ClientIP6, MobilePhoneModel, ClientEventTime) ON test.hits
2021.04.05 20:49:10.094967 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Debug> datasets.hits_v1 (SelectExecutor): Key condition: unknown
2021.04.05 20:49:10.095099 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Debug> datasets.hits_v1 (SelectExecutor): MinMax index condition: unknown
2021.04.05 20:49:10.095227 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Debug> datasets.hits_v1 (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 1084/1084 marks by primary key, 1084 marks to read from 1 ranges
2021.04.05 20:49:10.100902 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Trace> datasets.hits_v1 (SelectExecutor): Reading approx. 8880128 rows with 16 streams
2021.04.05 20:49:10.121053 [ 1314 ] {5987bc0d-37d1-45de-a47a-74f619c71384} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.04.05 20:50:46.591282 [ 281535 ] {} <Fatal> BaseDaemon: (version 21.5.1.6459, build id: 3729226FDEE1A5EB03D263744F831B2B36380024) (from thread 194400) (query_id: 5987bc0d-37d1-45de-a47a-74f619c71384) Received signal Aborted (6)
2021.04.05 20:50:11.649486 [ 288 ] {} <Fatal> BaseDaemon: (version 21.5.1.6459, build id: 3729226FDEE1A5EB03D263744F831B2B36380024) (from thread 194400) Terminate called for uncaught exception:
2021.04.05 20:50:46.566545 [ 281535 ] {} <Fatal> BaseDaemon: ########################################
2021.04.05 20:50:46.591282 [ 281535 ] {} <Fatal> BaseDaemon: (version 21.5.1.6459, build id: 3729226FDEE1A5EB03D263744F831B2B36380024) (from thread 194400) (query_id: 5987bc0d-37d1-45de-a47a-74f619c71384) Received signal Aborted (6)
2021.04.05 20:50:46.592646 [ 281535 ] {} <Fatal> BaseDaemon: 
2021.04.05 20:50:46.593657 [ 281535 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f11cf2aa18b 0x7f11cf289859 0x98ba6fe 0x43ed5049 0x43ed4e83 0x914c4b9 0x317f2cfc 0x939aa67 0x93a90e8 0x7f11cf45f609 0x7f11cf386293
2021.04.05 20:50:46.596305 [ 281535 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.05 20:50:46.597348 [ 281535 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.04.05 20:50:47.823631 [ 281535 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:410: terminate_handler() @ 0x98ba6fe in /usr/bin/clickhouse
2021.04.05 20:50:47.842634 [ 281535 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x43ed5049 in /usr/bin/clickhouse
2021.04.05 20:50:47.865359 [ 281535 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_handlers.cpp:82: std::terminate() @ 0x43ed4e83 in /usr/bin/clickhouse
2021.04.05 20:51:12.396412 [ 286 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix some uncaught exceptions (in SCOPE_EXIT) under memory pressure

Detailed description:
Found with fuzzer [1]:

<details>

    <Fatal> BaseDaemon: (version 21.5.1.6440, build id: 3B097C902DDAA35688D90750552ED499DC5D10A0) (from thread 8012) Terminate called for uncaught exception:
    Code: 241, e.displayText() = DB::Exception: Memory limit (for user) exceeded: would use 153.51 MiB (attempt to allocate chunk of 4194368 bytes), maximum: 150.00 MiB, Stack trace (when copying this message, always include the lines below):

    0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x26fdcdd9 in /usr/bin/clickhouse
    1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xad0df02 in /usr/bin/clickhouse
    2. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/string:1444: DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xacc7bef in /usr/bin/clickhouse
    3. ./obj-x86_64-linux-gnu/../src/Common/MemoryTracker.cpp:219: MemoryTracker::alloc(long) @ 0xacc65eb in /usr/bin/clickhouse
    4. ./obj-x86_64-linux-gnu/../src/Common/MemoryTracker.cpp:0: MemoryTracker::alloc(long) @ 0xacc5dad in /usr/bin/clickhouse
    5. ./obj-x86_64-linux-gnu/../src/Common/MemoryTracker.cpp:0: MemoryTracker::alloc(long) @ 0xacc5dad in /usr/bin/clickhouse
    6. ./obj-x86_64-linux-gnu/../src/Common/AllocatorWithMemoryTracking.h:35: AllocatorWithMemoryTracking<DB::Field>::allocate(unsigned long) @ 0xad0a2fe in /usr/bin/clickhouse
    7. void std::__1::vector<DB::Field, AllocatorWithMemoryTracking<DB::Field> >::__push_back_slow_path<DB::Field>(DB::Field&&) @ 0x11712a51 in /usr/bin/clickhouse
    8. ./obj-x86_64-linux-gnu/../src/Interpreters/ThreadStatusExt.cpp:356: DB::ThreadStatus::detachQuery(bool, bool) @ 0x1f5d5237 in /usr/bin/clickhouse
    9. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x20c488e6 in /usr/bin/clickhouse
    10. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xad9f6cc in /usr/bin/clickhouse
    11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xada8264 in /usr/bin/clickhouse
    12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
    13. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
     (version 21.5.1.6440)

</details>

  [1]: https://clickhouse-test-reports.s3.yandex.net/22583/69296876005c0fa171c755f8b224e4d58192c402/stress_test_(address).html#fail1

Fixes: #22689

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: base/ext/scope_guard_safe.h [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    catch (...)                                      \
+    {                                                \
+        tryLogCurrentException(__PRETTY_FUNCTION__); \
+    }                                                \
+)
+
+/// Same as SCOPE_EXIT() but:
+/// - block the MEMORY_LIMIT_EXCEEDED errors,
+/// - try/catch/tryLogCurrentException any exceptions.
+#define SCOPE_EXIT_MEMORY_SAFE(...) SCOPE_EXIT(                   \
```
Comment (amosbird) [inline base/ext/scope_guard_safe.h:22]: How should we choose these variants? Perhaps we can put some when-to-use example in the comment.

**Comment by alexey-milovidov** [comment]
Could you please merge with master?

File: base/ext/scope_guard_safe.h (hunk 1 above)
Comment (azat) [reply base/ext/scope_guard_safe.h:22]: Hm, I though that describing what they do is enough, OK, will try to give a sensible comment.

Comment (azat) [reply base/ext/scope_guard_safe.h:56]: Done, I hope that it will bring some clarification.

**Comment by azat** [comment]
>Could you please merge with master?

Done
