### PR TITLE
Fix possible terminate called for uncaught exception in some places

### LINKED ISSUE #48910: Terminate called for uncaught exception in WriteBuffer* desctuctors
- [ ] https://s3.amazonaws.com/clickhouse-test-reports/0/0dab82c420df1961f3832fc07cf52efa046a4eb2/stress_test__asan_.html

<details>
<summary>Stack Trace</summary>

```
[ 1808 ] {} <Fatal> BaseDaemon: (version 23.4.1.1 (official build), build id: C53F661579DB077BDBAEC35E01E8716AC464C57D) (from thread 35742) Terminate called for uncaught exception:
 [ 1808 ] {} <Fatal> BaseDaemon: Code: 210. DB::NetException: Connection reset by peer, while writing to socket (127.0.0.1:43346 -> 127.0.0.2:9000). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):
 [ 1808 ] {} <Fatal> BaseDaemon: 
 [ 1808 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x3f1e256c in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x20cfdd4a in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 2. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, St
 [ 1808 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/IO/WriteBufferFromPocoSocket.cpp:67: DB::WriteBufferFromPocoSocket::nextImpl() @ 0x337e3171 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 4. DB::WriteBuffer::finalizeImpl() @ 0x1251f3a6 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 5. DB::WriteBuffer::finalize() @ 0xf6ee4c3 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/IO/WriteBufferFromPocoSocket.cpp:98: DB::WriteBufferFromPocoSocket::~WriteBufferFromPocoSocket() @ 0x337e4215 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::Connection::disconnect() @ 0x36d2d36b in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Client/HedgedConnections.cpp:0: DB::HedgedConnections::finishProcessReplica(DB::HedgedConnections::ReplicaState&, bool) @ 0x36d7c7ea in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Client/HedgedConnections.cpp:0: DB::HedgedConnections::disconnect() @ 0x36d7c3e5 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::RemoteQueryExecutor::~RemoteQueryExecutor() @ 0x30ef8fb3 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::RemoteSource::~RemoteSource() @ 0x378fb8b6 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::~vector[abi:v15000]() @ 0x2fd7780d in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::QueryPipeline::~QueryPipeline() @ 0x30ebc0f3 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/QueryPipeline/QueryPipeline.cpp:618: DB::QueryPipeline::reset() @ 0x30ec9bc0 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Server/TCPHandler.cpp:515: DB::TCPHandler::runImpl() @ 0x36fbfe4f in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Server/TCPHandler.cpp:2038: DB::TCPHandler::run() @ 0x36ff263b in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x3ee4516f in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x3ee45ec5 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x3f2ed49c in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x3f2e69ad in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 21. ? @ 0x7f059ce4a609 in ?
 [ 1808 ] {} <Fatal> BaseDaemon: 22. clone @ 0x7f059cd6f133 in ?
 [ 1808 ] {} <Fatal> BaseDaemon:  (version 23.4.1.1 (official build))
 [ 76134 ] {} <Fatal> BaseDaemon: ########################################
 [ 76134 ] {} <Fatal> BaseDaemon: (version 23.4.1.1 (official build), build id: C53F661579DB077BDBAEC35E01E8716AC464C57D) (from thread 35742) (query_id: test_9_hash_table_sizes_stats_32135373) (query: -- size_hint = 1000005 despite the presence of limit --
 [ 76134 ] {} <Fatal> BaseDaemon: 
 [ 76134 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f059cc9300b 0x7f059cc72859 0x213b4f75 0x47027988 0x4702789d 0xf69787b 0x337e42ca 0x36d2d36b 0x36d7c7ea 0x36d7c3e5 0x30ef8fb3 0x378fb8b6 0x2fd7780d 0x30ebc0f3 0x30ec9bc0 0x36fbfe4f 0x36ff263b 0x3ee4516f 0x3ee45ec5 0x3f2ed49c 0x3f2e69ad 0x7f059ce4a609 
 [ 76134 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f059cc9300b in ?
 [ 76134 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f059cc72859 in ?
 [ 76134 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
 [ 76134 ] {} <Fatal> BaseDaemon: 5.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:968: String::size[abi:v15000]() const
 [ 76134 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Daemon/BaseDaemon.cpp:479: terminate_handler() @ 0x213b4f75 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x47027988 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/./contrib/llvm-project/libcxxabi/../libcxx/src/include/atomic_support.h:74: void (*std::(anonymous namespace)::__libcpp_atomic_load[abi:v15000]<void (*)()>(void (* const*)(), int))()
 [ 76134 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:49: std::get_terminate()
 [ 76134 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:92: std::terminate() @ 0x4702789d in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 8. ? @ 0xf69787b in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 9. ? @ 0x337e42ca in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_weak_count::__release_shared[abi:v15000]()
 [ 76134 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
 [ 76134 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:723: std::shared_ptr<DB::WriteBuffer>::operator=[abi:v15000](std::shared_ptr<DB::WriteBuffer>&&)
 [ 76134 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Client/Connection.cpp:215: DB::Connection::disconnect() @ 0x36d2d36b in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Client/HedgedConnections.cpp:0: DB::HedgedConnections::finishProcessReplica(DB::HedgedConnections::ReplicaState&, bool) @ 0x36d7c7ea in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Client/HedgedConnections.cpp:0: DB::HedgedConnections::disconnect() @ 0x36d7c3e5 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
 [ 76134 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:2333: ~basic_string
 [ 76134 ] {} <Fatal> BaseDaemon: 13.3. inlined from ./build_docker/./src/Interpreters/StorageID.h:32: ~StorageID
 [ 76134 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/QueryPipeline/RemoteQueryExecutor.cpp:159: DB::RemoteQueryExecutor::~RemoteQueryExecutor() @ 0x30ef8fb3 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_weak_count::__release_shared[abi:v15000]()
 [ 76134 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
 [ 76134 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Processors/Sources/RemoteSource.cpp:29: DB::RemoteSource::~RemoteSource() @ 0x378fb8b6 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_weak_count::__release_shared[abi:v15000]()
 [ 76134 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
 [ 76134 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63: void std::__destroy_at[abi:v15000]<std::shared_ptr<DB::IProcessor>, 0>(std::shared_ptr<DB::IProcessor>*)
 [ 76134 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:88: void std::destroy_at[abi:v15000]<std::shared_ptr<DB::IProcessor>, 0>(std::shared_ptr<DB::IProcessor>*)
 [ 76134 ] {} <Fatal> BaseDaemon: 15.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317: void std::allocator_traits<std::allocator<std::shared_ptr<DB::IProcessor>>>::destroy[abi:v15000]<std::shared_ptr<DB::IProcessor>, void, void>(std::allocator<std:
 [ 76134 ] {} <Fatal> BaseDaemon: 15.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:833: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__base_destruct_at_end[abi:v15000](std::shared_ptr<DB::IProcessor>*)
 [ 76134 ] {} <Fatal> BaseDaemon: 15.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:827: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__clear[abi:v15000]()
 [ 76134 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./contrib/llvm-project/libcxx/include/vector:436: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::~vector[abi:v15000]() @ 0x2fd7780d in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_weak_count::__release_shared[abi:v15000]()
 [ 76134 ] {} <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
 [ 76134 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/QueryPipeline/QueryPipeline.cpp:42: DB::QueryPipeline::~QueryPipeline() @ 0x30ebc0f3 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/QueryPipeline/QueryPipeline.cpp:618: DB::QueryPipeline::reset() @ 0x30ec9bc0 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Server/TCPHandler.cpp:515: DB::TCPHandler::runImpl() @ 0x36fbfe4f in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Server/TCPHandler.cpp:2038: DB::TCPHandler::run() @ 0x36ff263b in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x3ee4516f in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<Poco::Net::TCPServerConnection>::operator()[abi:v15000](Poco::Net::TCPServerConnection*) const
 [ 76134 ] {} <Fatal> BaseDaemon: 21.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
 [ 76134 ] {} <Fatal> BaseDaemon: 21.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 76134 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x3ee45ec5 in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x3f2ed49c in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::get()
 [ 76134 ] {} <Fatal> BaseDaemon: 23.2. inlined from ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::assign(Poco::Runnable*)
 [ 76134 ] {} <Fatal> BaseDaemon: 23.3. inlined from ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:180: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::operator=(Poco::Runnable*)
 [ 76134 ] {} <Fatal> BaseDaemon: 23. ./build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x3f2e69ad in /usr/bin/clickhouse
 [ 76134 ] {} <Fatal> BaseDaemon: 24. ? @ 0x7f059ce4a609 in ?
 [ 76134 ] {} <Fatal> BaseDaemon: 25. clone @ 0x7f059cd6f133 in ?
 [ 76134 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: A9A408025BDCC04E3A5414C71436450C)
 [ 1805 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 1808 ] {} <Fatal> BaseDaemon: (version 23.4.1.1 (official build), build id: C53F661579DB077BDBAEC35E01E8716AC464C57D) (from thread 35742) Terminate called for uncaught exception:
 [ 1808 ] {} <Fatal> BaseDaemon: Code: 210. DB::NetException: Connection reset by peer, while writing to socket (127.0.0.1:43346 -> 127.0.0.2:9000). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):
 [ 1808 ] {} <Fatal> BaseDaemon: 
 [ 1808 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x3f1e256c in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x20cfdd4a in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 2. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, St
 [ 1808 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/IO/WriteBufferFromPocoSocket.cpp:67: DB::WriteBufferFromPocoSocket::nextImpl() @ 0x337e3171 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 4. DB::WriteBuffer::finalizeImpl() @ 0x1251f3a6 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 5. DB::WriteBuffer::finalize() @ 0xf6ee4c3 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/IO/WriteBufferFromPocoSocket.cpp:98: DB::WriteBufferFromPocoSocket::~WriteBufferFromPocoSocket() @ 0x337e4215 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::Connection::disconnect() @ 0x36d2d36b in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Client/HedgedConnections.cpp:0: DB::HedgedConnections::finishProcessReplica(DB::HedgedConnections::ReplicaState&, bool) @ 0x36d7c7ea in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Client/HedgedConnections.cpp:0: DB::HedgedConnections::disconnect() @ 0x36d7c3e5 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::RemoteQueryExecutor::~RemoteQueryExecutor() @ 0x30ef8fb3 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::RemoteSource::~RemoteSource() @ 0x378fb8b6 in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::~vector[abi:v15000]() @ 0x2fd7780d in /usr/bin/clickhouse
 [ 1808 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: DB::QueryPipeline::~QueryPipeline() @ 0x30ebc0f3 in /usr/bin/clickhouse

```

</details>

It looks like an uncaught exception in the destructor, but the root cause is unclear. Why hasn't it failed before?

https://github.com/ClickHouse/ClickHouse/blob/d5fd0c4664a2a96feaaefe6db793e9a49818cf39/src/IO/WriteBufferFromPocoSocket.cpp#L95-L98

Probably it's expected to be finalized before desctuctor is called.

- [ ] Another similar case with WriteBufferFromHTTPServerResponse https://s3.amazonaws.com/clickhouse-test-reports/0/ba5ca15c408025ea33be44583ec0ddcc3f7c26d9/stress_test__ubsan_.html

- [ ] And `<Error> WriteBufferFromS3: WriteBufferFromS3 is not finalized in destructor. It's a bug` here https://s3.amazonaws.com/clickhouse-test-reports/0/2728ce29791fcafa00b1367b7f1431bde3c3a8e4/stress_test__debug_.html

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible terminate called for uncaught exception in some places. Closes https://github.com/ClickHouse/ClickHouse/issues/48910.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Client/Connection.cpp [hunk 1]
```diff
@@ -232,12 +232,27 @@ void Connection::disconnect()
...
+    {
+        // finalize() can write to socket and throw an exception.
+        out->finalize();
+    }
+    catch (...)
+    {
+        /// Don't throw an exception here, it will leave Connection in invalid state.
+        finalize_exception = std::current_exception();
+    }
+    out = nullptr;
```
Comment (novikd) [inline src/Client/Connection.cpp:246]: Maybe better to wrap `socket` with some RAII structure?

Comment (Avogar) [reply src/Client/Connection.cpp:246]: I don't see how it will help. Can you share more what do you mean?

Comment (novikd) [reply src/Client/Connection.cpp:246]: Instead of writing try..catch you can have a class that will call `close()` in the destructor. Or maybe since we have Poco code in the base now, we can add `close()` to the socket destructor.

Comment (Avogar) [reply src/Client/Connection.cpp:246]: But there is not problem with socket. The problem is with `WriteBufferToPocoSocket`. It calls `finalize()` in destructor and can throw an exception (so we can get terminate because of it). So, I call finalize() explicitly. And another problem is that in case of exception in `out->finalize();` we can leave `Connection` in invalid state (because after `out = nullptr;` there is still some work/cleaning, not only closing socket), so we should catch exception from `finalize` and throw it later. I don't see how we can avoid try/catch here.

Comment (novikd) [reply src/Client/Connection.cpp:246]: Why don't you want to handle this exception in `~WriteBufferFromPocoSocket`? It's used in other places and can potentially cause termination there.

Comment (novikd) [reply src/Client/Connection.cpp]: I just don't like that this solution won't cover all the cases when `WriteBufferFromPocoSocket` is used. Handling the exception inside of `WriteBufferFromPocoSocket ` would be a better general solution.

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 20007504a7d475274e07e46a0f4c27e577cad43f with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49112/20007504a7d475274e07e46a0f4c27e577cad43f/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by novikd — APPROVED** [review]
