### PR TITLE
Unify toDate[32] cast implementation, support wide ints casts

### LINKED ISSUE #71531: Bad integer converted into Date32
**Describe the bug**
Inserting a negative integer value as the default value for a Date32 column converts it to the maximum possible date value, but in the output of an ORDER BY ASC query, it shows first.

**How to reproduce**
Run:
https://fiddle.clickhouse.com/8f5b4e53-fa81-4a24-a7bb-c67c5d3b8c99

### LINKED ISSUE #86799: Bad conversion from int to Date32
### Describe the bug

A large integer is not well converted to Date32.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/0cb36faa-b25f-4c80-a3e1-69200b21a00a

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
Closes: #71531 #86799

Fixes 3 issues
- toDate32(Int16) doesn't normalize negative values as Int32/64 do
- Use the same cast logic for the wide integers and bfloat16
- Wrong cast in the serializer leads to integer overflow, so values lower than the limit are printed as maximal instead of minimal

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description]
Makes the same behaviour of `toDate` and `toDate32` for all numeric types.
Fixes Date32 underflow check during cast from int16.

### CODE REVIEW

File: src/Functions/FunctionsConversion.h [hunk 1]
```diff
@@ -255,128 +255,78 @@ struct ToTimeImpl
...
+requires is_arithmetic_v<FromType>
+struct ToDateTransformFromSecondsOrDays
 {
     static constexpr auto name = "toDate";
 
     static NO_SANITIZE_UNDEFINED UInt16 execute(const FromType & from, const DateLUTImpl & time_zone)
     {
-        if constexpr (date_time_overflow_behavior == FormatSettings::DateTimeOverflowBehavior::Throw)
+        constexpr bool overflow_throw = date_time_overflow_behavior == FormatSettings::DateTimeOverflowBehavior::Throw;
+        if constexpr (overflow_throw && std::numeric_limits<FromType>::max() >= MAX_DATETIME_TIMESTAMP)
```
Comment (Avogar) [inline src/Functions/FunctionsConversion.h]:
```suggestion
        if constexpr (overflow_throw && std::numeric_limits<FromType>::max() > MAX_DATETIME_TIMESTAMP)
```

If max is equal to `MAX_DATETIME_TIMESTAMP` next comparison `from > MAX_DATETIME_TIMESTAMP` is always false

File: src/Functions/FunctionsConversion.h [hunk 2]
```diff
@@ -255,128 +255,78 @@ struct ToTimeImpl
...
         {
             if (from > MAX_DATETIME_TIMESTAMP) [[unlikely]]
-                throw Exception(ErrorCodes::VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE, "Value {} is out of bounds of type Date", from);
+                throw Exception(ErrorCodes::VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE, "Value {} is out of bounds of type Date", static_cast<Int64>(from));
```
Comment (Avogar) [inline src/Functions/FunctionsConversion.h:269]: Should these queries throw an exception?
```sql
:) select toDate(materialize(18446744073709551615)::UInt64) settings date_time_overflow_behavior='throw'

   ┌─toDate(CAST(⋯ 'UInt64'))─┐
1. │               2149-06-06 │
   └──────────────────────────┘

:) select toDate32(materialize(18446744073709551615)::UInt64) settings date_time_overflow_behavior='throw'

   ┌─toDate32(CAS⋯ 'UInt64'))─┐
1. │               1969-12-31 │
   └──────────────────────────┘

:) select toDateTime(materialize(18446744073709551615)::UInt64) settings date_time_overflow_behavior='throw'

   ┌─toDateTime(C⋯ 'UInt64'))─┐
1. │      2106-02-07 06:28:15 │
   └──────────────────────────┘
```

File: src/Functions/FunctionsConversion.h [hunk 3]
```diff
@@ -255,128 +255,78 @@ struct ToTimeImpl
...
+                    return 0;
+            }
 
-template <typename FromType, FormatSettings::DateTimeOverflowBehavior date_time_overflow_behavior>
-struct ToDateTransform8Or16Signed
-{
-    static constexpr auto name = "toDate";
+        /// if value is smaller (or equal) than maximum day value for Date, than treat it as day num,
+        /// otherwise treat it as unix timestamp. This is a bit weird, but we leave this behavior.
+        if constexpr (std::numeric_limits<FromType>::max() >= DATE_LUT_MAX_DAY_NUM)
```
Comment (Avogar) [inline src/Functions/FunctionsConversion.h]:
```suggestion
        if constexpr (std::numeric_limits<FromType>::max() > DATE_LUT_MAX_DAY_NUM)
```

File: src/Functions/FunctionsConversion.h [hunk 4]
```diff
@@ -255,128 +255,78 @@ struct ToTimeImpl
...
-        }
+        if constexpr (overflow_throw && std::numeric_limits<FromType>::max() > MAX_DATETIME64_TIMESTAMP)
+            if (from > MAX_DATETIME64_TIMESTAMP) [[unlikely]]
+                throw Exception(ErrorCodes::VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE, "Timestamp value {} is out of bounds of type Date32", static_cast<Int64>(from));
 
-        if (from < daynum_min_offset)
-            return daynum_min_offset;
+        if constexpr (std::numeric_limits<FromType>::max() >= DATE_LUT_MAX_EXTEND_DAY_NUM)
+            if (from >= DATE_LUT_MAX_EXTEND_DAY_NUM)
+                return time_zone.toDayNum(std::min(time_t(Int64(from)), time_t(MAX_DATETIME64_TIMESTAMP)));
```
Comment (Avogar) [inline src/Functions/FunctionsConversion.h:323]:
```suggestion
        if constexpr (std::numeric_limits<FromType>::max() > DATE_LUT_MAX_EXTEND_DAY_NUM)
            if (from > DATE_LUT_MAX_EXTEND_DAY_NUM)
                return time_zone.toDayNum(std::min(time_t(Int64(from)), time_t(MAX_DATETIME64_TIMESTAMP)));
```

For consistency

File: src/Functions/FunctionsConversion.h (hunk 2 above)
Comment (GrigoryPervakov) [reply src/Functions/FunctionsConversion.h:269]: I have kept the old behavior, so this setting doesn't work for these functions.
`date_time_overflow_behavior` is always set to `default_date_time_overflow_behavior`==`Ignore`
For me it also feels like a bug, but I decided to keep the behaviour. ([code](https://github.com/ClickHouse/ClickHouse/blame/master/src/Functions/FunctionsConversion.h#L1566))

File: src/Functions/FunctionsConversion.h (hunk 4 above)
Comment (GrigoryPervakov) [reply src/Functions/FunctionsConversion.h:323]: It is a valid check
DATE_LUT_MAX_DAY_NUM is a valid value for Date type, but
DATE_LUT_MAX_EXTEND_DAY_NUM is already overflowed(at least that is what I see here)
https://fiddle.clickhouse.com/e68ffb8d-6de6-42d7-8133-282b7f263081

**Review by Avogar — APPROVED** [review]

**Comment by GrigoryPervakov** [comment]
01111_create_drop_replicated_db_stress - another repro of #85774
03036_test_parquet_bloom_filter_push_down and test_memory_context_in_trace_log - seems to be unrelated
