### PR TITLE
Prevent recursive WINDOW analysis

### LINKED ISSUE #83131: Possible error downgrade with new analyzer
### Describe the bug

An invalid nested window function seems to give a better error with the old analyzer than the new one. Could the new one be improved to be on the same level?

### How to reproduce

For old analyzer: https://fiddle.clickhouse.com/bafdf922-c41b-4b43-a2a9-c266f6a061d1
/*
DB::Exception: Received from localhost:9000. DB::Exception: Window function min(1) OVER (w0) is found in WINDOW in query: 
While processing min(1) OVER (w0). (ILLEGAL_AGGREGATION)
*/
For new analyzer: https://fiddle.clickhouse.com/57fa2b7d-b6c5-4031-a523-1c1d05f5e3d4
/*
DB::Exception: Stack size too large. Stack address: 0x79a7a4bdf000, 
frame address: 0x79a7a4fdedc0, stack size: 4194880, 
maximum stack size: 8388608. (TOO_DEEP_RECURSION)
*/

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix infinite recursive analysis of invalid `WINDOW` definitions. Fixes #83131.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Analyzer/Resolve/QueryAnalyzer.h [hunk 1]
```diff
@@ -264,6 +265,9 @@ class QueryAnalyzer
     /// CTEs that are currently in resolve process
     QueryTreeNodePtrWithHashSet ctes_in_resolve_process;
 
+    /// Window definitions that are currently in resolve process
+    std::unordered_set<IQueryTreeNode *> windows_in_resolve_process;
```
Comment (vdimir) [inline src/Analyzer/Resolve/QueryAnalyzer.h:269]: Shouldn't we put it into `scope`? But it's probably only relevant when a subquery is used in a window definition (if we allow that), and as it cannot see the window defined in the parent scope should be fine

**Review by vdimir — APPROVED** [review]
