### PR TITLE
Fix crash in client due to connection left in disconnected state after bad INSERT

### LINKED ISSUE #83123: Client crash due to disconnected connection after failed INSERT
### Describe the bug

From this run: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=c1e504e1c8bf2e4c5088a25904ad44c23ed964d8&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_debug%29

### How to reproduce

I can try to reduce the script, but it's long.

### Error message and/or stacktrace

```
########## Short fault info ############
(version 25.7.1.2048 (official build), build id: D86D4017F95A7BB95E4223C08A9E12A29E691816, git hash: c1e504e1c8bf2e4c5088a25904ad44c23ed964d8, architecture: x86_64) (from thread 2296) Received signal 11
Signal description: Segmentation fault
Address: 0x20. Access: read. Address not mapped to object.
Stack trace: 0x000055618926a422 0x0000556189243e44 0x0000556189241cf3 0x000055618923b0ed 0x00005561800d5963 0x00005561800d5f5e 0x0000556189245e3f 0x0000556189247230 0x000055618924f738 0x00005561800bf022 0x0000556191270e31 0x00005561800ca4a6 0x0000556178f70ea7 0x00007f71d47c0d90 0x00007f71d47c0e40 0x0000556178f6202e
########################################
(version 25.7.1.2048 (official build), build id: D86D4017F95A7BB95E4223C08A9E12A29E691816, git hash: c1e504e1c8bf2e4c5088a25904ad44c23ed964d8) (from thread 2296) (no query) Received signal Segmentation fault (11)
Address: 0x20. Access: read. Address not mapped to object.
Stack trace: 0x000055618926a422 0x0000556189243e44 0x0000556189241cf3 0x000055618923b0ed 0x00005561800d5963 0x00005561800d5f5e 0x0000556189245e3f 0x0000556189247230 0x000055618924f738 0x00005561800bf022 0x0000556191270e31 0x00005561800ca4a6 0x0000556178f70ea7 0x00007f71d47c0d90 0x00007f71d47c0e40 0x0000556178f6202e
3.0. inlined from /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/IO/BufferBase.h:40: DB::BufferBase::Buffer::end() const
3.1. inlined from /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/IO/VarInt.h:93: DB::readVarUInt(unsigned long&, DB::ReadBuffer&)
3. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/Connection.cpp:1307: DB::Connection::receivePacket() @ 0x000000001cce8422
4. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:2072: DB::ClientBase::receiveEndOfQuery() @ 0x000000001ccc1e44
5. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:1786: DB::ClientBase::processInsertQuery(String, std::shared_ptr<DB::IAST>) @ 0x000000001ccbfcf3
6. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:2243: DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001ccb90ed
7. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/client/FuzzLoop.cpp:107: DB::Client::processASTFuzzerStep(String const&, std::shared_ptr<DB::IAST> const&) @ 0x0000000013b53963
8. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/client/FuzzLoop.cpp:334: DB::Client::processWithASTFuzzer(std::basic_string_view<char, std::char_traits<char>>) @ 0x0000000013b53f5e
9. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:2590: DB::ClientBase::executeMultiQuery(String const&) @ 0x000000001ccc3e3f
10. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:3412: DB::ClientBase::processMultiQueryFromFile(String const&) @ 0x000000001ccc5230
11. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:3429: DB::ClientBase::runNonInteractive() @ 0x000000001cccd738
12. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/client/Client.cpp:403: DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000013b3d022
13. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x0000000024ceee31
14. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/client/Client.cpp:1139: mainEntryClickHouseClient(int, char**) @ 0x0000000013b484a6
15. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/main.cpp:340: main @ 0x000000000c9eeea7
16. __libc_start_call_main @ 0x0000000000029d90
17. __libc_start_main_alias_2 @ 0x0000000000029e40
18. _start @ 0x000000000c9e002e
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash in client due to connection left in disconnected state after bad INSERT

Fixes: https://github.com/ClickHouse/ClickHouse/issues/83123
Fixes: https://github.com/ClickHouse/ClickHouse/issues/82933

### CODE REVIEW

File: tests/queries/0_stateless/03554_connection_crash.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+DROP TABLE IF EXISTS t1;
+
+CREATE TABLE t0 (c0 JSON) ENGINE = MergeTree() PRIMARY KEY tuple();
+CREATE TABLE t1 (c0 Bool, c1 FixedString(42)) ENGINE = Buffer(currentDatabase(), t0, 71, 5, 379, 74, 221, 238, 858, 34, 55);
+SET min_insert_block_size_bytes = 4;
+INSERT INTO TABLE t1 (c0, c1) SETTINGS optimize_trivial_insert_select = 1 SELECT c0, c1 FROM generateRandom('c0 Bool, c1 FixedString(42)', 9090224004680416777, 6350, 9) LIMIT 187;
+SET input_format_max_block_size_bytes = 4, min_insert_block_size_rows = 32, min_insert_block_size_bytes = 0;
+INSERT INTO TABLE FUNCTION file('$path', 'CSV', 'c1 FixedString(42), c0 Bool') SELECT c1, c0 FROM t1 FINAL;
+INSERT INTO TABLE t1 (c1, c0) FROM INFILE '$path' FORMAT CSV; -- { serverError TYPE_MISMATCH }
+INSERT INTO TABLE t1 (c1, c0) VALUES ('move', TRUE); -- { clientError ATTEMPT_TO_READ_AFTER_EOF }
```
Comment (PedroTadim) [inline tests/queries/0_stateless/03554_connection_crash.sh]: Quick question. Why is the client left disconnected here? Shouldn't this insert succeed?

Comment (azat) [reply tests/queries/0_stateless/03554_connection_crash.sh]: That was due to non deterministic test, that depends on how previous INSERT finished, if it leaves the connection in a broken state then it will be EOF, otherwise it will successfully insert data.

Anyway this has been fixed to make it deterministic, and now it also fixes another issue.

But I will appreciate help to improve the test

File: src/Client/ClientBase.cpp [hunk 2]
```diff
@@ -2105,9 +2108,25 @@ bool ClientBase::receiveEndOfQuery()
...
 {
+    if (!connection->isConnected())
+    {
+        error_stream << "Cannot send Cancel due to connection is lost";
+        if (exception_ptr)
+        {
+            error_stream << ": ";
+            error_stream << getExceptionMessage(exception_ptr, /*with_stacktrace=*/ true);
+        }
+        error_stream << '\n';
```
Comment (tuanpach) [inline src/Client/ClientBase.cpp:2121]: Should we `return` here if the connection is lost?

Comment (azat) [reply src/Client/ClientBase.cpp:2121]: Nice catch, thanks! Fixed.

**Review by tuanpach — APPROVED** [review]

**Comment by azat** [comment]
>[Stress test (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83253&sha=cde53aea3d2dd2e04d50c78133adb1402116ccf1&name_0=PR&name_1=Stress%20test%20%28arm_asan%29) — Killed by signal (in clickhouse-server.log)

- https://github.com/ClickHouse/ClickHouse/issues/77233
