### PR TITLE
chdig: fix leftovers on the screen, crash after edit query in editor and update to 25.8.1

### LINKED ISSUE #138: Leftovers on the screen after invoking external programs (skim, vim, ...)
I thought that I've fixed it in #128, but I still see some problems

### LINKED ISSUE #144: Crash during spawning editor (in clickhouse builtin build)
```
Core was generated by `programs/chdig -b 24hour'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000004 in ?? ()
[Current thread is 1 (Thread 0x7ffff7e64d00 (LWP 14621))]
(gdb) bt
#0  0x0000000000000004 in ?? ()
#1  0x00007fffffff5d64 in ?? ()
#2  0x000000000000007f in ?? ()
#3  0x0000555574b671c0 in ?? () at posix_spawn.c:99
#4  0x0000000274b671c0 in ?? ()
#5  0x0000555574048cbc in tcache_gc_small (tsd=0x7fffe4c03060, tcache_slow=0x7fffe4c03160, tcache=0x7fffe4c254a0, szind=<optimized out>) at tcache.c:148
#6  tcache_event (tsd=0x7fffe4c03060) at tcache.c:193
#7  0x0000555574b672a4 in posix_spawn (res=0x4111, res@entry=0x7fffffff62f8, path=0x7fffffff5d80 "", path@entry=0x7fffe4c03060 "nvim", fa=0x7ffff7d1a866 <clone+54>, fa@entry=0x7fffffff6370, attr=0x7fffe4c03060, attr@entry=0x7fffffff6010, argv=0x3997, argv@entry=0x7fffe4c254a0,
    envp=envp@entry=0x7fffffffc1f8) at posix_spawn.c:106
#8  0x0000555574b63bba in posix_spawnp (res=0x7fffffff62f8, file=0x7fffe4c03060 "nvim", fa=0x7fffffff6370, attr=0x7fffffff61a0, argv=0x7fffe4c254a0, envp=0x7fffffffc1f8) at glibc-compatibility.c:332
#9  0x00005555651e620e in std::sys::process::unix::common::Command::posix_spawn () at unix.rs:796
#10 std::sys::process::unix::common::Command::spawn () at unix.rs:71
#11 0x00005555651d9364 in std::process::Command::spawn () at process.rs:1045
#12 0x0000555564a82eb4 in chdig::utils::edit_query ()
#13 0x0000555564b74926 in chdig::view::processes_view::ProcessesView::new::{{closure}} ()
#14 0x0000555564aa9a04 in chdig::interpreter::context::Context::add_view_action::{{closure}} ()
#15 0x0000555564a931cf in cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::on_event ()
#16 0x0000555564afd98d in cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::on_event ()
#17 0x0000555564b9b836 in cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::on_event ()
#18 0x0000555565178f20 in <cursive_core::views::dialog::Dialog as cursive_core::view::view_trait::View>::on_event ()
#19 0x00005555651723a2 in <cursive_core::views::linear_layout::LinearLayout as cursive_core::view::view_trait::View>::on_event ()
#20 0x0000555564afd7ee in cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::on_event ()
#21 0x00005555651723a2 in <cursive_core::views::linear_layout::LinearLayout as cursive_core::view::view_trait::View>::on_event ()
#22 0x0000555565189d6b in <cursive_core::views::circular_focus::CircularFocus<T> as cursive_core::view::view_wrapper::ViewWrapper>::wrap_on_event ()
#23 0x000055556517d3e1 in <cursive_core::views::stack_view::StackView as cursive_core::view::view_trait::View>::on_event ()
#24 0x000055556518c4b6 in <cursive_core::views::on_event_view::OnEventView<T> as cursive_core::view::view_wrapper::ViewWrapper>::wrap_on_event ()
#25 0x000055556518f146 in cursive_core::cursive_root::Cursive::on_event ()
#26 0x0000555564a05cfc in cursive_core::cursive_run::CursiveRunner<C>::run ()
#27 0x0000555564af3348 in chdig::bin::chdig_main_async::{{closure}} ()
#28 0x0000555564b14b19 in tokio::runtime::scheduler::current_thread::CoreGuard::block_on ()
#29 0x0000555564ae093c in tokio::runtime::context::runtime::enter_runtime ()
#30 0x0000555564a6a773 in tokio::runtime::runtime::Runtime::block_on ()
#31 0x0000555564a0367f in chdig_main ()
#32 0x000055555dd88622 in main (argc_=<optimized out>, argv_=<optimized out>) at main.cpp:381
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
chdig: fix leftovers on the screen, fix crash after edit query in editor, search in `PATH` for `EDITOR`, update to [25.8.1](https://github.com/azat/chdig/releases/tag/v25.8.1)

There was internal problems in ClickHouse in `glibc-compatiblity` layer, 1024 stack is not enough to run `posix_spawn` and also `posix_swawnp` did not look at `PATH` for binary.

Fixes: https://github.com/azat/chdig/issues/138
Fixes: https://github.com/azat/chdig/issues/144
Refs: https://github.com/ClickHouse/rust_vendor/pull/45

### CODE REVIEW

File: base/glibc-compatibility/spawn.h [hunk 1]
```diff
@@ -6,11 +6,16 @@ extern "C" {
...
+#include <bits/types/sigset_t.h>
+
+#define POSIX_SPAWN_SETSIGMASK		0x08
 
 typedef struct {
 	int __flags;
 	pid_t __pgrp;
-	sigset_t __def, __mask;
+	sigset_t __sd;
+	sigset_t __ss;
```
Comment (thevar1able) [inline base/glibc-compatibility/spawn.h:18]: Could you please elaborate on changes in this file?

Comment (azat) [reply base/glibc-compatibility/spawn.h:18]: The `posix_spawnattr_t` that is defined in this header is differs from the system wide impementation it has `__fn` (used as part of padding, this is OK), that is set in `glibc-compatbility.c` in `posix_spawnp`, and it calls `posix_spawn`, but, `base/glibc-compatibility/musl/posix_spawn.c` knows nothing about this field.

So, I need to match all used fields with the system wide version to make it common

And due to this and too small stack `posix_spawnp` (`p` stands for search in `PATH`) never worked, while `chdig` uses it, so I fixed it.

Comment (thevar1able) [reply base/glibc-compatibility/spawn.h:18]: Ok so this is just a bump to the latest interface, if I got it right.

>And due to this and too small stack

What is the issue with stack size exactly? Which thing needs to have it increased 16x times?

Comment (azat) [reply base/glibc-compatibility/spawn.h:18]: >Ok so this is just a bump to latest interface, if I got it right.

Yes

>What is the issue with stack size exactly? Which thing needs to have it increased 16x times?

Smaller stack overflows - https://github.com/azat/chdig/issues/144

**Review by thevar1able — APPROVED** [review]
