### PR TITLE
fix WindowNode to ast window node conversion

### LINKED ISSUE #78461: Named windows in `view(...)` cause bad cast exception
### Company or project name

_No response_

### Describe what's wrong

When using a named window in a subquery inside `view(...)`, ClickHouse throws a `Bad cast` exception. The same query without `view(...)` executes correctly.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

✅ Query without `view(...)` works fine:
```sql
SELECT row_number() OVER w
FROM numbers(3)
WINDOW w AS ()
```
**Result:**
```
┌─row_number() OVER w─┐
│                   1 │
│                   2 │
│                   3 │
└─────────────────────┘
```

❌ Query wrapped in `view(...)` fails:
```sql
SELECT *
FROM view(
    SELECT row_number() OVER w
    FROM numbers(10)
    WINDOW w AS ()
)
```
**Error:**
```
Received exception from server (version 25.3.2):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ASTWindowDefinition to DB::ASTWindowListElement. (LOGICAL_ERROR)
```

### Expected behavior

Query should execute correctly and return results, same as without `view(...)`.

### Error message and/or stacktrace

Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ASTWindowDefinition to DB::ASTWindowListElement. (LOGICAL_ERROR)

### Additional context

Unnamed windows work fine inside view():

```sql
SELECT *
FROM view(
    SELECT row_number() OVER ()
    FROM numbers(3)
)
```

✅ Returns expected result.

With analyzer disabled (`SET allow_experimental_analyzer = 0`) all works as expected.

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
Named Windows are expected to be wrapped by ASTWindowListElement, but the current conversion puts the definition directly into the list. 
This breaks table function resolution if it takes a subquery as an argument and the subquery uses window functions.

Closes: #78461

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the logical error in the nested functions with named windows

### CODE REVIEW

File: src/Analyzer/ListNode.cpp [hunk 1]
```diff
@@ -62,7 +63,21 @@ ASTPtr ListNode::toASTImpl(const ConvertToASTOptions & options) const
...
+
+        // Named window should be wrapped in ASTWindowListElement with name.
+        if (children_ast->as<ASTWindowDefinition>())
+        {
+            auto window_list_node = std::make_shared<ASTWindowListElement>();
+            window_list_node->name = children[i]->getAlias();
+            window_list_node->children.push_back(children_ast);
+            window_list_node->definition = window_list_node->children.back();
+            children_ast = window_list_node;
+        }
```
Comment (novikd) [inline src/Analyzer/ListNode.cpp:77]: Am I correct that this may happen only for named windows? Let's then fix it in the `WindowNode::toAST`.
Let's wrap `ASTWindowDefinition` with `ASTWindowListElement` if `WindowNode` has an alias.

**Comment by novikd** [comment]
Seems like I broke something...

File: src/Analyzer/ListNode.cpp (hunk 1 above)
Comment (novikd) [reply src/Analyzer/ListNode.cpp]: I prefer removing the alias from WindowNode during query analysis. Thanks for the help with debugging.

**Review by novikd — APPROVED** [review]

**Comment by GrigoryPervakov** [comment]
Test failure is unrelated #81065
