### PR TITLE
Fix delta-kernel with http based endpoints, fix NOSIGN

### LINKED ISSUE #78124: Failed to use new allow_experimental_delta_kernel_rs flag
### Company or project name

_No response_

### Describe the unexpected behaviour

```sql
SELECT
*
FROM deltaLake(
        'https://clickhouse-public-datasets.s3.amazonaws.com/delta_lake/hits/', SETTINGS allow_experimental_delta_kernel_rs = 1)
     limit 10
```
Doesn't work

Getting:
```
Code: 742. DB::Exception: Received DeltaLake kernel error ReqwestError: Error interacting with object store: Generic S3 error: Received redirect without LOCATION, this normally indicates an incorrectly configured region (in snapshot). (DELTA_KERNEL_ERROR) (version 25.3.1.2703 (official build))
```

Running on my own tables getting:
```
Code: 48. DB::Exception: Unsupported complex data type: 140131940957952. (NOT_IMPLEMENTED) (version 25.3.1.2703 (official build))
```

### How to reproduce

```sql
SELECT
*
FROM deltaLake(
        'https://clickhouse-public-datasets.s3.amazonaws.com/delta_lake/hits/', SETTINGS allow_experimental_delta_kernel_rs = 1)
     limit 10
```

### Expected behavior

Should work as without the allow_experimental_delta_kernel_rs flag

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix DeltaLake table engine with delta-kernel implementation being used with http based endpoints, fix NOSIGN. Closes https://github.com/ClickHouse/ClickHouse/issues/78124.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp [hunk 1]
```diff
@@ -23,14 +28,20 @@ class S3KernelHelper final : public IKernelHelper
...
         , access_key_id(access_key_id_)
         , secret_access_key(secret_access_key_)
         , region(region_)
         , token(token_)
+        , no_sign(no_sign_)
         , table_location(getTableLocation(url_))
     {
+        /// Check if user didn't mention any region
+        /// Same as in S3/Client.cpp
+        if (url.endpoint.substr(11) == "amazonaws.com")
```
Comment (alesapin) [inline src/Storages/ObjectStorage/DataLakes/DeltaLake/KernelHelper.cpp:43]: Let's add an example of endpoint and what we are cutting off.

**Comment by kssenii** [comment]
> Intregration tests

test_storage_rabbitmq

**Review by alesapin — APPROVED** [review]

**Comment by kssenii** [comment]
> Integration tests

test_storage_rabbitmq
