### PR TITLE
Fix usage of non-materialized skip indexes

### LINKED ISSUE #32292: Query that uses skip index fails if index is not materialized
```sql
CREATE TABLE t ( a UInt32) ENGINE = MergeTree ORDER BY tuple();

INSERT INTO t VALUES (1);

ALTER TABLE t ADD INDEX ind (a) TYPE set(1) GRANULARITY 1;

SELECT count() FROM t WHERE a = 1;

Received exception from server (version 21.11.5):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in file_size: No such file or directory [./store/402/402d2274-1310-43f7-802d-22741310f3f7/all_1_1_0_2/skp_idx_ind.mrk3]. (STD_EXCEPTION)
```

**Does it reproduce on recent release?**

Reproduces on 21.11 and master.

**Expected behavior**

Index should be skipped if it doesn't exist in part.

> Add any other context about the problem here.

Most likely introduced in #27250.

### PR DESCRIPTION
**Pull request by CurtizJ**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix failures in queries that are trying to use skipping indices, which are not materialized yet. Fixes #32292 and #30343.

### CODE REVIEW

File: tests/queries/0_stateless/02131_skip_index_not_materialized.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
+DROP TABLE IF EXISTS t_index_non_materialized;
+
+CREATE TABLE t_index_non_materialized (a UInt32) ENGINE = MergeTree ORDER BY tuple();
+
+INSERT INTO t_index_non_materialized VALUES (1);
+
+ALTER TABLE t_index_non_materialized ADD INDEX ind (a) TYPE set(1) GRANULARITY 1;
```
Comment (azat) [inline tests/queries/0_stateless/02131_skip_index_not_materialized.sql:7]: Nice catch! Worth adding a check for minmax index too? (since it is a separate code branch)

**Comment by Zhile** [comment]
Please help to backport this fix to 21.11. Thanks.

File: tests/queries/0_stateless/02131_skip_index_not_materialized.sql (hunk 1 above)
Comment (CurtizJ) [reply tests/queries/0_stateless/02131_skip_index_not_materialized.sql]: There already exists a check https://github.com/ClickHouse/ClickHouse/blob/4e6bf2456c8caa3fc718b537d64ae1b44d6e2ab7/src/Storages/MergeTree/MergeTreeIndexMinMax.cpp#L216-L223

 Added it to test.

Comment (azat) [reply tests/queries/0_stateless/02131_skip_index_not_materialized.sql]: >There already exists a check

Yep, I meant adding it to test (since those branches can be modified independently)

**Review by kitaisreal — APPROVED** [review]

**Comment by Zhile** [comment]
@CurtizJ  can this be merged？

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
There are failing tests. This PR will be merged after either author (@CurtizJ) or reviewer (@kitaisreal) will check and investigate the failures of the tests. If PR has failing tests, it cannot be merged as is.

**Comment by CurtizJ** [comment]
Stress test: `Logical error: 'Chunk should have AggregatedChunkInfo in GroupingAggregatedTransform.'.` #30692
