### PR TITLE
Fix stress test (assertion 'key_metadata.lock()')

### LINKED ISSUE #49513: Assertion failed: key_metadata.lock()
https://s3.amazonaws.com/clickhouse-test-reports/0/36f8fcdfaf4d7b9fb84fe8f7e958a3c742f0307f/stress_test__ubsan_.html

```
[ 26524 ] {519d7b82-f25a-4c89-98b1-38de40889898} <Fatal> : Logical error: \'key_metadata.lock()\'.
 [ 38666 ] {} <Fatal> BaseDaemon: ########################################
 [ 38666 ] {} <Fatal> BaseDaemon: (version 23.5.1.1 (official build), build id: 0251248BB13401837E512A154BB04E8D706CBB9C) (from thread 26524) (query_id: 519d7b82-f25a-4c89-98b1-38de40889898) (query: SELECT sum(DISTINCT sipHash64(decodeXMLComponent(Title) AS decoded)) FROM test.hits WHERE Title != de
 [ 38666 ] {} <Fatal> BaseDaemon: 
 [ 38666 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fd0a369e00b 0x7fd0a367d859 0x560acbb204e8 0x560ad8c46135 0x560ad7561aca 0x560ad75640d6 0x560ad756ce1c 0x560ad756c82f 0x560ac0e2fb19 0x560ad755b476 0x560ad755a179 0x560ad7559f77 0x560ad7586242 0x560ac0e2fb19 0x560ad757a112 0x560ac0e2fb19 0x560ad70fec9
 [ 38666 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7fd0a369e00b in ?
 [ 38666 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7fd0a367d859 in ?
 [ 38666 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(String const&) @ 0x353db4e8 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
 [ 38666 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:2333: ~basic_string
 [ 38666 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Interpreters/Cache/FileSegment.cpp:201: DB::FileSegment::getOrSetDownloader() @ 0x42501135 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:0: DB::CachedOnDiskReadBufferFromFile::getReadBufferForFileSegment(DB::FileSegment&) @ 0x40e1caca in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:388: DB::CachedOnDiskReadBufferFromFile::getImplementationBuffer(DB::FileSegment&) @ 0x40e1f0d6 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:835: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x40e27e1c in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:770: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x40e2782f in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 11. DB::ReadBuffer::next() @ 0x2a6eab19 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:0: DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x40e16476 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:150: DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x40e15179 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:106: DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) @ 0x40e14f77 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Disks/IO/ReadIndirectBufferFromRemoteFS.cpp:100: DB::ReadIndirectBufferFromRemoteFS::nextImpl() @ 0x40e41242 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 16. DB::ReadBuffer::next() @ 0x2a6eab19 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/IO/ReadBufferFromFileDecorator.cpp:50: DB::ReadBufferFromFileDecorator::nextImpl() @ 0x40e35112 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 18. DB::ReadBuffer::next() @ 0x2a6eab19 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Compression/CompressedReadBufferBase.cpp:159: DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x409b9c92 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./src/Compression/CompressedReadBufferFromFile.cpp:22: DB::CompressedReadBufferFromFile::nextImpl() @ 0x409be191 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 21. DB::ReadBuffer::next() @ 0x2a6eab19 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./src/DataTypes/Serializations/SerializationString.cpp:157: void DB::deserializeBinarySSE2<1>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::ReadB
 [ 38666 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./build_docker/./contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:140: intrusive_ptr<DB::IColumn>
 [ 38666 ] {} <Fatal> BaseDaemon: 23.2. inlined from ./build_docker/./src/Common/COW.h:144: immutable_ptr<DB::IColumn>
 [ 38666 ] {} <Fatal> BaseDaemon: 23. ./build_docker/./src/DataTypes/Serializations/ISerialization.cpp:133: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<D
 [ 38666 ] {} <Fatal> BaseDaemon: 24. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:0: DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, 
 [ 38666 ] {} <Fatal> BaseDaemon: 25. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:157: DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB:
 [ 38666 ] {} <Fatal> BaseDaemon: 26. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:106: DB::MergeTreeRangeReader::DelayedStream::readRows(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x4
 [ 38666 ] {} <Fatal> BaseDaemon: 27. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:178: DB::MergeTreeRangeReader::DelayedStream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x434f7ceb in /usr
 [ 38666 ] {} <Fatal> BaseDaemon: 28.1. inlined from ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.h:122: DB::MergeTreeRangeReader::DelayedStream::isFinished() const
 [ 38666 ] {} <Fatal> BaseDaemon: 28. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:292: DB::MergeTreeRangeReader::Stream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x434f85d2 in /usr/bin/cl
 [ 38666 ] {} <Fatal> BaseDaemon: 29. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::startReadingChain(unsigned long, DB::MarkRanges&) @ 0x43504248 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 30. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, DB::MarkRanges&) @ 0x43501d1c in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 31. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:402: DB::IMergeTreeSelectAlgorithm::readFromPartImpl() @ 0x434f2428 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 32. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:445: DB::IMergeTreeSelectAlgorithm::readFromPart() @ 0x434f2f3b in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 33. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:166: DB::IMergeTreeSelectAlgorithm::read() @ 0x434ee685 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 34. ./build_docker/./src/Storages/MergeTree/MergeTreeSource.cpp:0: DB::MergeTreeSource::tryGenerate() @ 0x441ba6fe in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 35.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/optional:344: std::__optional_storage_base<DB::Chunk, false>::has_value[abi:v15000]() const
 [ 38666 ] {} <Fatal> BaseDaemon: 35.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/optional:998: std::optional<DB::Chunk>::operator bool[abi:v15000]() const
 [ 38666 ] {} <Fatal> BaseDaemon: 35. ./build_docker/./src/Processors/ISource.cpp:94: DB::ISource::work() @ 0x439b4597 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 36.1. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
 [ 38666 ] {} <Fatal> BaseDaemon: 36. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x439db1a2 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 37. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x439cb023 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 38.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: std::shared_ptr<DB::ThreadGroup>::operator bool[abi:v15000]() const
 [ 38666 ] {} <Fatal> BaseDaemon: 38.2. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:332: operator()
 [ 38666 ] {} <Fatal> BaseDaemon: 38.3. inlined from ./build_docker/./base/base/../base/scope_guard.h:99: BasicScopeGuard<DB::PipelineExecutor::spawnThreads()::$_0::operator()() const::\'lambda\'()>::invoke()
 [ 38666 ] {} <Fatal> BaseDaemon: 38.4. inlined from ./build_docker/./base/base/../base/scope_guard.h:48: ~BasicScopeGuard
 [ 38666 ] {} <Fatal> BaseDaemon: 38.5. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:351: operator()
 [ 38666 ] {} <Fatal> BaseDaemon: 38.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spaw
 [ 38666 ] {} <Fatal> BaseDaemon: 38.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
 [ 38666 ] {} <Fatal> BaseDaemon: 38.8. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]()
 [ 38666 ] {} <Fatal> BaseDaemon: 38. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_st
 [ 38666 ] {} <Fatal> BaseDaemon: 39.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:789: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 38666 ] {} <Fatal> BaseDaemon: 39.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1456: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 38666 ] {} <Fatal> BaseDaemon: 39.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 38666 ] {} <Fatal> BaseDaemon: 39.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 38666 ] {} <Fatal> BaseDaemon: 39. ./build_docker/./src/Common/ThreadPool.cpp:415: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x354fded8 in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 40. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::\'lambda0\'()>(void&
 [ 38666 ] {} <Fatal> BaseDaemon: 41.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:789: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 38666 ] {} <Fatal> BaseDaemon: 41.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1456: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 38666 ] {} <Fatal> BaseDaemon: 41.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 38666 ] {} <Fatal> BaseDaemon: 41.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 38666 ] {} <Fatal> BaseDaemon: 41. ./build_docker/./src/Common/ThreadPool.cpp:415: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x354fbb8f in /usr/bin/clickhouse
 [ 38666 ] {} <Fatal> BaseDaemon: 42. ./build_docker/./src/Common/ThreadPool.cpp:0: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, st
 [ 38666 ] {} <Fatal> BaseDaemon: 43. ? @ 0x7fd0a3855609 in ?
 [ 38666 ] {} <Fatal> BaseDaemon: 44. __clone @ 0x7fd0a377a133 in ?
 [ 38666 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: D97E000BD833F8AACDFCCF98A10B9002)
 [ 1665 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/49513.

### CODE REVIEW

File: src/Interpreters/Cache/Metadata.h [hunk 1]
```diff
@@ -12,6 +12,48 @@ class CleanupQueue;
 using CleanupQueuePtr = std::shared_ptr<CleanupQueue>;
 
 
+struct CacheMetadata : public std::unordered_map<FileCacheKey, KeyMetadataPtr>, private boost::noncopyable
```
Comment (kssenii) [inline src/Interpreters/Cache/Metadata.h:15]: Nothing is changed here, I just moved it before the `KeyMetadata` class to be able to write `friend void CacheMetadata::doCleanup()`

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 1050754432f723148ae9601cb7463b2c7ab799a1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49554/1050754432f723148ae9601cb7463b2c7ab799a1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]
