### PR TITLE
Query cache: ignore results of queries against system tables

### LINKED ISSUE #59071: Query cache must know which system tables are deterministic and which ones are not
**How to reproduce**

```
SET use_query_cache=true;

SELECT * FROM system.processes; -- (A)

SELECT * FROM system.processes; -- (B) Note that this SELECT shows the same information as (A) -
                                -- for example query id and so on - instead of the actual information
                                -- about processes
```

The issue happens because the first result of the query `SELECT * FROM system.processes` is cached in the query cache and then used the second time. The issue was found in https://github.com/ClickHouse/ClickHouse/pull/59041.

So we need to make the code understand that any select from `system.processes` must not be cached. And for other system tables which are known to non-deterministic it's the same.

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes #59071

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The query cache now no longer caches results of queries against system tables (`system.*`, `information_schema.*`, `INFORMATION_SCHEMA.*`).

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit a68b9206e04e205d66a89ea312ed219181719771 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62376/a68b9206e04e205d66a89ea312ed219181719771/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Interpreters/Cache/QueryCache.cpp [hunk 1]
```diff
@@ -52,7 +54,40 @@ struct HasNonDeterministicFunctionsMatcher
...
+    };
+
+    static bool needChildVisit(const ASTPtr &, const ASTPtr &) { return true; }
+
+    static void visit(const ASTPtr & node, Data & data)
+    {
+        if (data.has_system_tables)
+            return;
+
+        if (const auto * identifier = node->as<ASTTableIdentifier>())
```
Comment (kssenii) [inline src/Interpreters/Cache/QueryCache.cpp:72]: Probably something like select from `clusterAllReplicas(default, 'system.processes')` will not work here as  'system.query_log' is a `ASTLiteral` or in case ``clusterAllReplicas(default, system.processes)`` it will be `ASTIdentifier`.  Or (I do not know but may be) if the query has `clusterAllReplicas` it is anyway not put into query cache?

**Review by kssenii — APPROVED** [review]

File: src/Interpreters/Cache/QueryCache.cpp (hunk 1 above)
Comment (rschu1ze) [reply src/Interpreters/Cache/QueryCache.cpp]: Good point, thanks! I changed the code a bit so that these cases are now correctly handled.

File: docs/en/operations/settings/settings.md [hunk 2]
```diff
@@ -1689,6 +1689,18 @@ Possible values:
...
+
+Controls how the [query cache](../query-cache.md) handles `SELECT` queries against system tables, i.e. tables in databases `system.*` and `information_schema.*`.
+
+Possible values:
+
+- `'throw'` - Throw an exception and don't cache the query result.
+- `'save'` - Cache the query result.
+- `'ignore'` - Don't cache the query result and don't throw an exception.
+
+Default value: `throw`.
```
Comment (kssenii) [inline docs/en/operations/settings/settings.md:1702]: btw why default value is `throw`? this seems to be backward incompatible at least, may be better `ignore`?

Comment (rschu1ze) [reply docs/en/operations/settings/settings.md:1702]: Yes, `throw` is backward incompatible (for an edge case) but it seems the most natural default setting.

Imagine this:
- By default, the query cache is disabled. To use it, one must run a query like this: `SELECT [...] SETTINGS use_query_cache = 1`.
- Users who do this expect that the query result is actually cached (because they explicitly enabled the query cache).
- With setting `ignore`, the query will be executed but the result will  *silently* not be cached. As a user, I would be surprised.

I guess if the query cache was on by default, then setting `ignore` would be okay.

So let's go for the principle of least surprise. `throw` is also consistent with the behavior that happens if the query contains non-deterministic functions (setting `query_cache_nondeterministic_function_handling`).

Comment (kssenii) [reply docs/en/operations/settings/settings.md:1702]: Ok. It just seemed that many users might have query cache enabled by default for all queries. For them it might become a surprise that some queries will start to throw errors. Or someone will enable it by default in the future - same, e.g. he'll have to find out that he'll also need to change another setting. 

Your reasoning also makes sense and I do not have a strong opinion here on what is better, so agreeing with yours.

File: src/Interpreters/Cache/QueryCache.cpp [hunk 3]
```diff
@@ -52,7 +56,51 @@ struct HasNonDeterministicFunctionsMatcher
...
+            const auto & value = literal->value; /// (*)
+            database_table = applyVisitor(FieldVisitorDump(), value);
+        }
+
+        /// (*) returns table in quotes, so we can't use .starts_with() for matching
+        static const re2::RE2 is_system_table(String(DatabaseCatalog::TEMPORARY_DATABASE)
+                                    + "|" + DatabaseCatalog::SYSTEM_DATABASE
+                                    + "|" + DatabaseCatalog::INFORMATION_SCHEMA
+                                    + "|" + DatabaseCatalog::INFORMATION_SCHEMA_UPPERCASE);
+        data.has_system_tables = re2::RE2::PartialMatch(database_table, is_system_table);
```
Comment (kssenii) [inline src/Interpreters/Cache/QueryCache.cpp:98]: seems it will work incorrectly if for example a table name contains a word "system" ? Looks like quite a common case. Should we better use something like `parseDatabaseAndTableName` here to distinguish between table and database? (similar to `Parsers/parseDatabaseAndTableName.cpp` but for string, or may be there is some function like there somewhere else idk)

Comment (rschu1ze) [reply src/Interpreters/Cache/QueryCache.cpp:98]: Makes sense, thanks. Done.

**Review by kssenii — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @rschu1ze @kssenii — while reviewing this PR I found the following:

- **Bug (P2):** `HasSystemTablesMatcher` `ASTIdentifier` branch flags any compound column reference whose first part equals a predefined database (`system`, `INFORMATION_SCHEMA`) — https://github.com/ClickHouse/ClickHouse/issues/104039

Happy to discuss — close anything that's wrong or already addressed.
