### PR TITLE
Optimize ReplacingMergeTree is_deleted FINAL queries by adding a filter expression transform 

### LINKED ISSUE #65180: FINAL on table with is_deleted works 10-30 times slower than expected
**Problem**
I have two identical **ReplacingMergeTree** tables with identical data except that one table uses the `is_deleted` table option and the other does not. The queries that use the table with `is_deleted` option work much slower than queries that use table without `is_deleted` option but filter deleted rows explicitly. 

In other words,  `SELECT count(*) FROM table_with_is_deleted FINAL` work much slower than `SELECT count(*) FROM table_without_is_deleted WHERE deleted = 0`

**Observations**

1. The output of EXPLAIN is the same
2. For  CH 24.5, in system.query_log, I see the slow queries use the following functions: `['and', 'not', 'notIn', 'equals', 'greater', 'tuple', 'CAST']`, fast queries use `['notIn', 'and', 'equals']`. For CH 24.2 it is `['equals', 'not', 'and', 'greater', 'tuple', 'CAST']` and `['equals', 'and']` respectively. 
3. In query profile, slow queries read much more data
4. If I run ClickHouse in Docker with bind mounts on MacOS M1, then both queries are slow, `is_deleted` does not make any difference. 
5. Queries on tables with `is_deleted` option on ClickHouse CH 24.5 are 20% slower than the same queries in CH 24.4.
6. It does not matter if tables are optimized i.e. have just one part or not optimized, but have the same number of active parts.

**How to reproduce**
* Which ClickHouse server version to use
 CH 24.2, 24.4, 24.5 
* Which interface to use, if matters
HTTP 
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE table_with_is_deleted
(
    `school_year_id` UInt32,
    `district_id` UInt32,
    `student_id` UInt32,
    `assessment_id` UInt32,
    `value` Int32,
    `etl_timestamp` Int64,
    `deleted` UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(etl_timestamp, deleted)
ORDER BY (school_year_id, district_id, student_id, assessment_id);

CREATE TABLE table_without_is_deleted
(
    `school_year_id` UInt32,
    `district_id` UInt32,
    `student_id` UInt32,
    `assessment_id` UInt32,
    `value` Int32,
    `etl_timestamp` Int64,
    `deleted` UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(etl_timestamp)
ORDER BY (school_year_id, district_id, student_id, assessment_id);
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance
`select count(*) from table_without_is_deleted FINAL where school_year_id = 1 and district_id = 1 and deleted = 0;` 
`select count(*) from table_with_is_deleted FINAL where school_year_id = 1 and district_id = 1;`
`select count(*) from table_without_is_deleted FINAL where deleted = 0;` 
`select count(*) from table_with_is_deleted FINAL;`

### PR DESCRIPTION
**Pull request by shankar-iyer**
Resolves https://github.com/ClickHouse/ClickHouse/issues/65180 and https://github.com/ClickHouse/ClickHouse/issues/69164. 

Currently, all ranges in a query with `FINAL` clause on a `ReplacingMergeTree` table with `is_deleted` column have to be processed by FINAL merge transform.

Add a `FilterTransform` correspdoning to `is_deleted = 0` for parts & ranges thus enabling parallel processing and skip `FINAL` Merge transform. The parts & ranges that  qualify are 1) Partitions with only a single `part` when `do_not_merge_across_partitions_select_final`  is `True`  2) Non-intersecting ranges identified by the existing _split ranges into intersecting/non-intersecting_ optimization.

Performance example : [Link](https://github.com/ClickHouse/ClickHouse/issues/65180#issuecomment-3367787144)

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description]
- SELECT query with `FINAL` clause on.a `ReplacingMergeTree` table with the `is_deleted` column now executes faster because of improved parallelization from 2 existing optimizations : 1) `do_not_merge_across_partitions_select_final`  optimization for partitions of the table that have only a single `part` 2) Split other selected ranges of the table into `intersecting / non-intersecting` and only intersecting ranges have to pass through FINAL merging transform.

### CODE REVIEW

File: tests/queries/0_stateless/02490_replacing_merge_tree_is_deleted_column_transform_opt.sql [hunk 1]
```diff
@@ -0,0 +1,72 @@
+-- Test for https://github.com/ClickHouse/ClickHouse/pull/76978
```
Comment (SmitaRKulkarni) [inline tests/queries/0_stateless/02490_replacing_merge_tree_is_deleted_column_transform_opt.sql]: @shankar-iyer Maybe makes sense to add performance test? What do you think?

**Review by SmitaRKulkarni — APPROVED** [review]
Rest all LGTM

File: tests/queries/0_stateless/02490_replacing_merge_tree_is_deleted_column_transform_opt.sql (hunk 1 above)
Comment (shankar-iyer) [reply tests/queries/0_stateless/02490_replacing_merge_tree_is_deleted_column_transform_opt.sql]: ack, will do in a follow on PR. Test `replacing_final_non_intersecting.xml` looks to be a good reference.

**Comment by shankar-iyer** [comment]
Previous CI run was 100% green! But latest CI run has some integration test failures, verified that they are unrelated to the PR (`test_ytsaurus` and `test_insert_into_distributed`) : https://github.com/ClickHouse/ClickHouse/pull/88259
