### PR TITLE
Use FixedString for PostgreSQL's types that have a fixed length

### LINKED ISSUE #77303: Add support for fixed-size strings from PostgreSQL
I realized trying to reproduce an incident related to https://github.com/ClickHouse/ClickHouse/issues/61705 that we always fall back to type `String`, even when the sized is fixed.

So, for `CHARACTER(20)`, `CHAR(20)` or  `BPCHAR(20)` we always use `String` instead of the more correct `FixedString(20)`

### PR DESCRIPTION
**Pull request by pamarcos**
### Changelog category (leave one):
- Improvement

Use FixedString for PostgreSQL's CHARACTER, CHAR and BPCHAR

Close https://github.com/ClickHouse/ClickHouse/issues/77303

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Use FixedString for PostgreSQL's CHARACTER, CHAR and BPCHAR

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

https://github.com/ClickHouse/clickhouse-docs/pull/3489

### CODE REVIEW

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp [hunk 1]
```diff
@@ -135,8 +136,27 @@ static DataTypePtr convertPostgreSQLDataType(String & type, Fn<void()> auto && r
         }
     }
 
+    /// If the type is not mapped so far, assume it's some sort of String
     if (!res)
-        res = std::make_shared<DataTypeString>();
+    {
+        if (type.ends_with(')'))
```
Comment (Algunenano) [inline src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:142]: `geometry(Point, 4326)` would like a word

Comment (Algunenano) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:142]: We need a better way than using parenthesis

Comment (pamarcos) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:140]: I'll leave it then to the original implementation that I had where I was checking that the type started with `character`. I thought moving it down here would make it more flexible for some other way of specifying strings with particular sizes, but I see it could bring more trouble than anything.

This is the commit [`050f74a` (#77304)](https://github.com/ClickHouse/ClickHouse/pull/77304/commits/050f74a85fe6c8c1dd331e64d3694d5269edcaae)

Comment (Algunenano) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:140]: But this is again not correct -> https://www.postgresql.org/docs/current/datatype-character.html

`character(n), char(n), bpchar(n)` are fixed strings.
`character varying(n), varchar(n)` are variable length with limit (so they should not be matched to CH's FixedString).

Let's hardcode good assumptions instead of using conditionals

Comment (pamarcos) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:140]: >character(n), char(n), bpchar(n) are fixed strings.
>Let's hardcode good assumptions instead of using conditionals

Roger, all those 3 can be filtered by checking if the type starts with `character(`.

**Review by Algunenano — COMMENTED** [review]
Can we please add tests, both ways, for the conversions with incomplete / padded strings? It seems padding will be different and might affect results.

**Comment by pamarcos** [comment]
> Can we please add tests, both ways, for the conversions with incomplete / padded strings? It seems padding will be different and might affect results.

Sure. I also noticed my changes broke [test_postgresql_replica_database_engine_1/test.py::test_different_data_types](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77304&sha=e8be6a98f164be03e90f863df3df979a0a103b7f&name_0=PR&name_1=Integration+tests+%28release%2C+4%2F4%29&name_2=test_postgresql_replica_database_engine_1%2Ftest.py%3A%3Atest_different_data_types). I'm also checking that out

File: src/Core/PostgreSQLProtocol.cpp [hunk 2]
```diff
@@ -28,6 +28,8 @@ ColumnTypeSpec convertTypeIndexToPostgresColumnTypeSpec(TypeIndex type_index)
             return {ColumnType::FLOAT8, 8};
 
         case TypeIndex::FixedString:
+            return {ColumnType::BPCHAR, -1};
```
Comment (pamarcos) [inline src/Core/PostgreSQLProtocol.cpp:31]: This is not strictly needed for this particular PR, but I thought we'd rather have the proper `ColumnType` anyways

File: src/Storages/StoragePostgreSQL.cpp [hunk 3]
```diff
@@ -216,6 +221,63 @@ void StoragePostgreSQL::read(
...
+{
+    /// pqxx throws an error when trying to ingest fixed-size strings padded with \0:
+    /// pqxx::data_exception: Failure during '[END COPY]': ERROR:  invalid byte sequence for encoding "UTF8": 0x00
+    auto non_nullable_type = removeNullable(data_type);
+    auto non_nullable_column = removeNullable(column);
+    if (isFixedString(non_nullable_type) && !data_type->getCustomSerialization())
+    {
+        auto n = assert_cast<const DataTypeFixedString &>(*non_nullable_type).getN();
+        auto custom_desc = std::make_unique<DataTypeCustomDesc>(std::make_unique<DataTypeCustomFixedName>(fmt::format("FixedString({})", n)), std::make_shared<SerializationPostgreSQLFixedString>(n));
+        DataTypeFactory::instance().setCustom(data_type, std::move(custom_desc));
```
Comment (pamarcos) [inline src/Storages/StoragePostgreSQL.cpp:278]: Changing the serialization for this type is the less ugly way and the best abstraction that I found to workaround this. In order to make it work, I had to create a new `setCustom` to in `DataTypeFactory` because it's a private method of `IDataType`

File: src/DataTypes/DataTypeFactory.h [hunk 4]
```diff
@@ -35,6 +35,7 @@ class DataTypeFactory final : private boost::noncopyable, public IFactoryWithAli
     DataTypePtr get(const ASTPtr & ast) const;
     DataTypePtr getCustom(DataTypeCustomDescPtr customization) const;
     DataTypePtr getCustom(const String & base_name, DataTypeCustomDescPtr customization) const;
+    void setCustom(DataTypePtr & type, DataTypeCustomDescPtr customization) const;
```
Comment (Algunenano) [inline src/DataTypes/DataTypeFactory.h:38]: This is extremely confusing for 2 reasons:
* It's only using DataTypeFactory because it's a friend of IDataType.
* It could be static. It's not modifying and does not need the global DataTypeFactory instance.

File: src/Storages/StoragePostgreSQL.cpp [hunk 5]
```diff
@@ -216,6 +221,63 @@ void StoragePostgreSQL::read(
...
+        {
+            data = reinterpret_cast<const char *>(
+                &assert_cast<const ColumnFixedString *>(nested_column)->getChars()[size * row_num]);
+        }
+        else if (isString(column_type))
+            data = assert_cast<const ColumnString &>(column).getDataAt(row_num).data;
+        else
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Can't serialize type {} as a FixedString", nested_column->getName());
+
+        /// Write only the amount of UTF-8 characters actually used. PostgreSQL complains if we pass
```
Comment (Algunenano) [inline src/Storages/StoragePostgreSQL.cpp:253]: What will happen if the FixedString contains '\0' naturally? For example `'1\03'::FixedString(3)`

File: src/DataTypes/DataTypeFactory.h (hunk 4 above)
Comment (pamarcos) [reply src/DataTypes/DataTypeFactory.h]: Alright, I agree it can be confusing. Fixed in [`8c0a5ad` (#77304)](https://github.com/ClickHouse/ClickHouse/pull/77304/commits/8c0a5add179432f65187e77497f14a2b3389e1b0)

But I guess the same could be said for `getCustom`->`get`->`getImpl`->`tryParseQuery`/`parseQuery`

File: src/Storages/StoragePostgreSQL.cpp (hunk 5 above)
Comment (pamarcos) [reply src/Storages/StoragePostgreSQL.cpp:252]: That's a good point. PostgreSQL's strings do not accept intermediate \0 for strings, so we cannot really do a 1:1 conversion. We have 2 options here: either we throw a failure because of that:

```
pqxx::data_exception: Failure during '[END COPY]': ERROR:  invalid byte sequence for encoding "UTF8": 0x00
```

Or we convert any intermediate `\0` to a whitespace, which is what I did at [`c9bf83a` (#77304)](https://github.com/ClickHouse/ClickHouse/pull/77304/commits/c9bf83af398e403531d60f9fab6f22abbaa4bf8a)

**Review by Algunenano — APPROVED** [review]
