### PR TITLE
Fix: add necessary type conversion in lagInFrame and leadInFrame

### LINKED ISSUE #62449: Use-of-uninitialized-value in `NativeWriter`
https://s3.amazonaws.com/clickhouse-test-reports/62421/9a08f1ddd6f414097a6bf00f1159924d4a14b4e4/ast_fuzzer__msan_.html

```
==164==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55d8f61dff38 in Poco::Net::SocketImpl::sendBytes(void const*, int, int) build_docker/./base/poco/Net/src/SocketImpl.cpp:292:8
    #1 0x55d8f61efef1 in Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) build_docker/./base/poco/Net/src/StreamSocketImpl.cpp:63:23
    #2 0x55d8d730863b in DB::WriteBufferFromPocoSocket::socketSendBytesImpl(char const*, unsigned long) build_docker/./src/IO/WriteBufferFromPocoSocket.cpp:69:30
    #3 0x55d8d730adf1 in DB::WriteBufferFromPocoSocket::nextImpl() build_docker/./src/IO/WriteBufferFromPocoSocket.cpp:154:19
    #4 0x55d8f20d9dfd in DB::WriteBuffer::next() build_docker/./src/IO/WriteBuffer.h:53:13
    #5 0x55d8f20d9dfd in DB::TCPHandler::sendData(DB::Block const&) build_docker/./src/Server/TCPHandler.cpp:2206:37
    #6 0x55d8f20d2225 in DB::TCPHandler::processOrdinaryQuery() build_docker/./src/Server/TCPHandler.cpp:1055:21
    #7 0x55d8f20b246d in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:539:17
    #8 0x55d8f20fcd91 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2329:9
    #9 0x55d8f61f281f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #10 0x55d8f61f36a0 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #11 0x55d8f667aae5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #12 0x55d8f66778ad in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #13 0x55d8f6674791 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #14 0x7f9c85276ac2 in start_thread nptl/pthread_create.c:442:8
    #15 0x7f9c8530884f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

  Uninitialized value was stored to memory at
    #0 0x55d8c003caca in __msan_memcpy (/workspace/clickhouse+0x7b44aca) (BuildId: ec48f9fea32dfe94c3e5f6c8afcd082b4e11f2f8)
    #1 0x55d8c00f1c47 in DB::WriteBuffer::write(char const*, unsigned long) (/workspace/clickhouse+0x7bf9c47) (BuildId: ec48f9fea32dfe94c3e5f6c8afcd082b4e11f2f8)
    #2 0x55d8f21871d2 in void DB::writePODBinary<char8_t>(char8_t const&, DB::WriteBuffer&) build_docker/./src/IO/WriteHelpers.h:83:9
    #3 0x55d8f21871d2 in void DB::writeBinary<char8_t>(char8_t const&, DB::WriteBuffer&) build_docker/./src/IO/WriteHelpers.h:1026:59
    #4 0x55d8f21871d2 in DB::NativeWriter::write(DB::Block const&) build_docker/./src/Formats/NativeWriter.cpp:152:13
    #5 0x55d8f20d9d52 in DB::TCPHandler::sendData(DB::Block const&) build_docker/./src/Server/TCPHandler.cpp:2205:26
    #6 0x55d8f20d1969 in DB::TCPHandler::processOrdinaryQuery() build_docker/./src/Server/TCPHandler.cpp:1011:13
    #7 0x55d8f20b246d in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp:539:17
    #8 0x55d8f20fcd91 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2329:9
    #9 0x55d8f61f281f in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #10 0x55d8f61f36a0 in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #11 0x55d8f667aae5 in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #12 0x55d8f66778ad in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #13 0x55d8f6674791 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #14 0x7f9c85276ac2 in start_thread nptl/pthread_create.c:442:8

  Uninitialized value was created by an allocation of 'ref.tmp119' in the stack frame
    #0 0x55d8f21871a3 in DB::NativeWriter::write(DB::Block const&) build_docker/./src/Formats/NativeWriter.cpp:152:25

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/./base/poco/Net/src/SocketImpl.cpp:292:8 in Poco::Net::SocketImpl::sendBytes(void const*, int, int)
```

-----

**Looks like it complains about `has_custom`, but there's no way it could be not initialized, so it's weird**

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add proper type conversion to lagInFrame and leadInFrame window functions - fixes msan test

closes #62449

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 7612060d232a24dbd721597c8e33cd1f556cddd6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67091/7612060d232a24dbd721597c8e33cd1f556cddd6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — CHANGES_REQUESTED** [review]
This isn't just a fix, it's also breaking change that seems to decrease usability greatly.

For example:
```
SELECT
    date,
    close,
    lagInFrame(close, 1, 10) OVER (ORDER BY date ASC) AS previous_day_close,
    COALESCE(ROUND(close - previous_day_close, 2)) AS delta,
    COALESCE(ROUND((delta / previous_day_close) * 100, 2)) AS percent_change
FROM stock_prices
ORDER BY date DESC
```

Will now return:
```
Code: 36. DB::Exception: Argument type 'Float32' and the default value type 'UInt8' are different. (BAD_ARGUMENTS)
```

Let's give it another thought and consider other alternatives please.

**Comment by yakov-olkhovskiy** [comment]
@Algunenano in debug such kind of query produces logical error I mentioned in the issue:
```
SELECT
    date,
    close,                                                                                                                                                                      lagInFrame(close, 1, 10) OVER (ORDER BY date ASC) AS previous_day_close,                                                                                                    COALESCE(ROUND(close - previous_day_close, 2)) AS delta,
    COALESCE(ROUND((delta / previous_day_close) * 100, 2)) AS percent_change
FROM stock_prices
ORDER BY date DESC

Query id: e59b2010-b472-4c1e-98a9-84d9b873c39b

2024.07.25 15:23:52.311501 [ 253112 ] {e59b2010-b472-4c1e-98a9-84d9b873c39b} <Fatal> : Logical error: 'Invalid Field get from type UInt64 to type Float64'.
```
so it shouldn't work, and it works in release only by virtue of type punning
basically for how it is implemented now it is a proper fix I think - the question of to allow different types here is a completely different question

**Comment by yakov-olkhovskiy** [comment]
...this whole function is just awful
https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/Field.h#L870-L893
I understand why we must have it, but it easily the source of really bad hard to investigate bugs...

**Comment by yakov-olkhovskiy** [comment]
...I will try to reconcile some maybe compatible types - like nullables or/and NULL... if possible without invoking type punning...

File: src/Processors/Transforms/WindowTransform.cpp [hunk 1]
```diff
@@ -2388,6 +2398,16 @@ struct WindowFunctionLagLeadInFrame final : public WindowFunction
...
+        {
+            throw Exception(ErrorCodes::TOO_MANY_ARGUMENTS_FOR_FUNCTION,
+                "Function '{}' accepts at most 3 arguments, {} given",
+                name, argument_types.size());
+        }
+
+        if (argument_types[0]->equals(*argument_types[2]))
+            return;
+
         const auto supertype = getLeastSupertype(DataTypes{argument_types[0], argument_types[2]});
```
Comment (Algunenano) [inline src/Processors/Transforms/WindowTransform.cpp:2411]: Not related to the changes, but `getLeastSupertype` throws an error itself (by default) so we miss a better error message with function name .

Comment (Algunenano) [reply src/Processors/Transforms/WindowTransform.cpp:2411]: Another issue:
```
SELECT lagInFrame(CAST(number, 'UInt64'), 2, NULL) OVER w
FROM numbers(50)
WINDOW w AS (PARTITION BY number % 20 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)

Code: 36. DB::Exception: The supertype 'Nullable(UInt64)' for the argument type 'UInt64' and the default value type 'Nullable(Nothing)' is not the same as the argument type. (BAD_ARGUMENTS) (version 24.8.1.1) (from 0.0.0.0:0) (in query: SELECT lagInFrame(number::UInt64, 2, NULL) OVER w FROM numbers(50) WINDOW w AS (PARTITION BY number % 20 rows between unbounded preceding and unbounded following);), Stack trace (when copying this message, always include the lines below):
```

I would expect this to work since the docs say `Value to return if calculated row exceeds the boundaries of the window frame. (Optional - null by default).`, so I was expecting NULL to just be ignored. Also not introduced here.

**Review by Algunenano — APPROVED** [review]
Really nice solution. I've left minor comments about things that were already broken / unexpected, but we can improve them in a different PR

File: src/Processors/Transforms/WindowTransform.cpp (hunk 1 above)
Comment (yakov-olkhovskiy) [reply src/Processors/Transforms/WindowTransform.cpp:2411]: Regarding getLeastSupertype - agree, will fix it.
Regarding default null - I would rather argue that doc is wrong - by default it's a default value for the column value type, so exception is correct, and doc requires a fix.
