### PR TITLE
fix reinterpretAsFixedString for UUID

### LINKED ISSUE #24029: reinterpretAsFixedString for UUID stopped working
**Describe the bug**
The following statement started to return an error.
```
SELECT reinterpretAsFixedString(toUUID('61f0c404-5cb3-11e7-907b-a6006ad3dba0'))
```

**Does it reproduce on recent release?**
Current master 

**How to reproduce**
```
    Description
      Received exception from server (version 21.6.1):
    Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Cannot reinterpret UUID as FixedString because it is not fixed size and contiguous in memory: While processing hex(encrypt('aes-128-ecb', reinterpretAsFixedString(toUUID('61f0c404-5cb3-11e7-907b-a6006ad3dba0')), '1111111111111111')).
```

**Expected behavior**
```
ClickHouse client version 21.6.1.6689 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.6.1 revision 54448.

user-host :) SELECT reinterpretAsFixedString(toUUID('61f0c404-5cb3-11e7-907b-a6006ad3dba0'))

SELECT reinterpretAsFixedString(toUUID('61f0c404-5cb3-11e7-907b-a6006ad3dba0'))

Query id: fe58828e-6290-4f97-bd80-9589de123de3

┌─reinterpretAsFixedString(toUUID('61f0c404-5cb3-11e7-907b-a6006ad3dba0'))─┐
│ ��\��a���j�{�                                                                     │
└──────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.005 sec. 

user-host :)
```

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix `reinterpretAsFixedString` for UUID. Closes #24029.

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

File: src/Functions/reinterpretAs.cpp [hunk 1]
```diff
@@ -75,9 +75,9 @@ class FunctionReinterpret : public IFunction
 
         if (result_reinterpret_type.isFixedString())
         {
-            if (!from_type->isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion())
-                throw Exception("Cannot reinterpret " + from_type->getName() +
-                    " as FixedString because it is not fixed size and contiguous in memory",
+            if (!from_type->isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion() && !WhichDataType{from_type}.isUUID())
```
Comment (kitaisreal) [inline src/Functions/reinterpretAs.cpp:78]: Update isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion for UUID to return true.

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Functions/reinterpretAs.cpp (hunk 1 above)
Comment (ucasFL) [reply src/Functions/reinterpretAs.cpp]: Ok.

**Review by kitaisreal — APPROVED** [review]
