### PR TITLE
Fix: respect skip_unavailable_shards with parallel replicas

### LINKED ISSUE #53594: Parallel replicas with distributed queries mistakenly skipping unavailable shards.
When you run a query with `allow_experimental_parallel_reading_from_replicas`, it should silently skip unavailable replicas, but shouldn't skip unavailable shards (when no replicas for a shard is available), unless it is explicitly turned on by the `skip_unavailable_shards` setting.

For example, a cluster with multiple shards, each of one replica appears when you query `FROM clusterAllReplicas(...)`

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/53594

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 750f67eb50fdaf118b3112611ef82e6e6beb56e2 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/53904/750f67eb50fdaf118b3112611ef82e6e6beb56e2/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -468,12 +468,6 @@ InterpreterSelectQuery::InterpreterSelectQuery(
         }
     }
 
-    /// Set skip_unavailable_shards to true only if it wasn't disabled explicitly
```
Comment (vdimir) [inline src/Interpreters/InterpreterSelectQuery.cpp:471]: What was changed since putting this comment? Was it done by mistake?

**Review by vdimir — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Initially all this change was introduced in https://github.com/ClickHouse/ClickHouse/pull/50293 
And it is needed because method `needToSkipUnavailableShard()`checks whether setting `skip_unavailable_shards` is enabled. 

All the tests are green, but unfortunately I think there is a hidden issue inside the code. Let's remind ourselves: 
- Each replica sends the `InitialAllRangesAnnounecement` to the coordinator
- And not to block reading until all the replicas will send this announcement we allow replicas to read from ranges they told about.
- After all replicas sent the announcement we postprocess them (calculate some consistent hashes, etc.) 

The problem here that it seems Coordinator will wait forever for unavailable replica (because we don't delete it from the state properly) and the reading process is inefficient.

File: src/Interpreters/InterpreterSelectQuery.cpp (hunk 1 above)
Comment (devcrafter) [reply src/Interpreters/InterpreterSelectQuery.cpp:471]: This check doesn't consider whether parallel replicas will be actually used or not. And the parallel replicas will not be used with `clusterAllReplicas()` since it considers each replica as a shard with 1 replica in it, i.e. not applicable for parallel replicas

**Review by nikitamikhaylov — APPROVED** [review]
