### PR TITLE
Fix ARRAY JOIN with Distributed.

### LINKED ISSUE #62043: Array join not working on distributed tables
Since version 24.3.1.2672 it is not possible anymore to join an array on a distributed table.

**How to reproduce**
```
CREATE TABLE IF NOT EXISTS default.arrays_test on cluster datascience_cluster
(
    s String,
    arr Array(UInt8)
) 
ENGINE =ReplicatedMergeTree('/clickhouse-final/tables/{shard}/{database}/{table}/{uuid}', '{replica}')
ORDER BY (s)
SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS default.arrays_test_distributed ON CLUSTER datascience_cluster
    AS default.arrays_test
ENGINE = Distributed('datascience_cluster', 'default', 'arrays_test', rand());


INSERT INTO default.arrays_test_distributed
VALUES ('Hello', [1,2]), ('World', [3,4,5]), ('Goodbye', []);


SELECT s, arr, a
FROM default.arrays_test_distributed
ARRAY JOIN arr AS a
WHERE a < 3;
```

* Which ClickHouse server version to use
24.3.1.2672

**Expected behavior**

I would expect to get following result, as I get I from the same query on a cluster with version 24.2.2.71

|s |arr   | a |
|------|------|------|
|Hello   |  [1,2] | 1  |
|Hello   |  [1,2]	| 2 |

**Error message and/or stacktrace**
```
SQL Error [179] [07000]: Code: 179. DB::Exception: ARRAY JOIN expression __table2.arr AS a with duplicate alias a. In scope SELECT __table2.s AS s, __table2.arr AS arr, a AS a FROM default.arrays_test AS __table2 ARRAY JOIN __table2.arr AS a WHERE a < 3. (MULTIPLE_EXPRESSIONS_FOR_ALIAS) (version 24.3.1.2672 (official build))
, server ClickHouseNode [uri=http://xxxxxxxxxxxxxxx:8123/default, options={socket_timeout=300000,use_server_time_zone=false,connect_timeout=50000,use_time_zone=false}]@1152851345
```

**Additional context**
The same query is working on an clickhouse instance with version 24.2.2.71

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `duplicate alias` error for distributed queries with `ARRAY JOIN`

Fixes #62043
Aliases in `ARRAY JOIN` are no longer treated as expression aliases. They are treated as columns generated by the `ARRAY JOIN` table expression.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 57f087bdbced1cc4c1969115a2a9a977fe0ffd7a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64226/57f087bdbced1cc4c1969115a2a9a977fe0ffd7a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -3889,12 +3893,39 @@ QueryTreeNodePtr QueryAnalyzer::tryResolveIdentifierFromArrayJoin(const Identifi
...
+            continue;
+
+        if (identifier_view.empty())
         {
             auto array_join_column = std::make_shared<ColumnNode>(array_join_column_expression_typed.getColumn(),
                 array_join_column_expression_typed.getColumnSource());
             return array_join_column;
         }
+
+        auto compound_expr = tryResolveIdentifierFromCompoundExpression(
```
Comment (novikd) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:3919]: Please, add a comment

**Review by novikd — APPROVED** [review]
