### PR TITLE
Fix partition pruning with binary monotonic function by second arg.

### LINKED ISSUE #71941: 24.7+: Broken query by partition pruning
Repro:
```
CREATE TABLE tt
(
    `id` Int64,
    `ts` DateTime
)
ENGINE = MergeTree()
ORDER BY dateTrunc('hour', ts)
SETTINGS index_granularity = 8192;

INSERT INTO tt VALUES (1, '2024-11-14 00:00:00'), (2, '2024-11-14 00:00:00');

SELECT id
FROM tt
PREWHERE ts BETWEEN toDateTime(1731506400) AND toDateTime(1731594420);
```

```
Received exception from server (version 24.11.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type String of 1st argument of function toStartOfInterval, expected a Date, Date32, DateTime or DateTime64. (ILLEGAL_TYPE_OF_ARGUMENT)
(query: SELECT id
FROM tt
PREWHERE ts BETWEEN toDateTime(1731506400) AND toDateTime(1731594420);)
```

Worked fine until https://github.com/ClickHouse/ClickHouse/pull/65335. Fails since then

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `Illegal type` error for `MergeTree` tables with binary monotonic function in `ORDER BY` when the first argument is constant. Fixes #71941

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

File: tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql [hunk 1]
```diff
@@ -0,0 +1,15 @@
+CREATE TABLE tt
```
Comment (Algunenano) [inline tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql:1]:
```suggestion
DROP TABLE IF EXISTS tt;

CREATE TABLE tt
```

Comment (Algunenano) [reply tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql:1]: Let's add DROP at start and end.

File: tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+ENGINE = MergeTree()
+ORDER BY dateTrunc('hour', ts)
+SETTINGS index_granularity = 8192;
+
+INSERT INTO tt VALUES (1, '2024-11-14 00:00:00'), (2, '2024-11-14 00:00:00');
+
+SELECT id
+FROM tt
+PREWHERE ts BETWEEN toDateTime(1731506400) AND toDateTime(1731594420);
+
```
Comment (Algunenano) [inline tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql:15]: Let's assert via log, explain indexes or read/discarded granules that the key is used.

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 3]
```diff
@@ -1005,7 +1007,7 @@ bool applyFunctionChainToColumn(
         if (func->getArgumentTypes().empty())
             return false;
 
-        auto argument_type = func->getArgumentTypes()[0];
+        auto argument_type = getArgumentTypeOfMonotonicFunction(*func);
```
Comment (Algunenano) [inline src/Storages/MergeTree/KeyCondition.cpp:1010]: It might make sense to capture possible exceptions on `func->execute`, log them and continue the query without pruning.

Comment (KochetovNicolai) [reply src/Storages/MergeTree/KeyCondition.cpp:1010]: I would prefer to avoid shuch a logic here. It will hide the bug.
Overall, there is a lot of complicated logic in KeyCondition, mostly not skippable.

File: tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql (hunk 1 above)
Comment (KochetovNicolai) [reply tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql:1]: I don't understand why we need it; it only makes the test longer.

Comment (Algunenano) [reply tests/queries/0_stateless/03272_partition_pruning_monotonic_func_bug.sql:2]: Because some people, mostly Alexey, run the sql tests directly via clickhouse-client instead of using `clickhouse-test`.
