### PR TITLE
to #35128_add_mysql_error__detail

### LINKED ISSUE #35128: MySQL errors are unclear if password / user are incorrect.
```sql
apt-get install mysql-server

create database db;
create table db.test(a Int);

CREATE USER 'myuser'@'%' IDENTIFIED BY 'mypass';
GRANT ALL ON *.* TO 'myuser'@'%';
FLUSH PRIVILEGES;
```

mysql client shows different error messages in case the wrong password/user VS host:port
```
# mysql -h 127.0.0.1 -u myuser --password=mypass1
ERROR 1045 (28000): Access denied for user 'myuser'@'localhost' (using password: YES)

mysql -h 127.0.0.1 --port 9999 -u myuser --password=mypass
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:9999' (111)
```

clickhouse shows the same error message

```
select * from mysql('127.0.0.1', 'db', 'test', 'myuser1', 'mypass');
DB::Exception: Exception: Connections to all replicas failed: db@127.0.0.1:3306 as user myuser1. (POCO_EXCEPTION)


select * from mysql('127.0.0.1:9999', 'db', 'test', 'myuser', 'mypass');
DB::Exception: Exception: Connections to all replicas failed: db@127.0.0.1:9999 as user myuser. (POCO_EXCEPTION
```

### PR DESCRIPTION
**Pull request by zzsmdfj**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added better error messages in case of connection failed to MySQL. Closes #35128.

### CODE REVIEW

File: src/Common/mysqlxx/PoolWithFailover.cpp [hunk 1]
```diff
@@ -160,6 +161,7 @@ PoolWithFailover::Entry PoolWithFailover::get()
                     }
 
                     app.logger().warning("Connection to " + pool->getDescription() + " failed: " + e.displayText());
+                    error_detail =  e.displayText();
```
Comment (kitaisreal) [inline src/Common/mysqlxx/PoolWithFailover.cpp:164]: This error detail will bind only to one replica, if user tries to connect to 3 replicas and all of them will produce different errors it will be hard to understand which error belongs to which replica. I suggest to bind error_detail to replica, and then in result error output them together.
Also need to output MySQL error code check mysqld_error.h.

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Common/mysqlxx/PoolWithFailover.cpp (hunk 1 above)
Comment (zzsmdfj) [reply src/Common/mysqlxx/PoolWithFailover.cpp]: thanks. I fixed and try to be consistent with MySQL error.

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Mergifyio update
