### PR TITLE
Fix rabbitmq engine performance issues

### LINKED ISSUE #62525: Highload CPU
**Describe the situation**
When using the RabbitMQ engine, there is a highload CPU. Even in the simplest scenario, the CPU load increases by more than 20 percent.

**How to reproduce**
```sql
CREATE TABLE test_order_queue
(
 id UInt32
)
ENGINE = RabbitMQ SETTINGS rabbitmq_host_port = '***', rabbitmq_exchange_name = 'monolith', rabbitmq_exchange_type = 'direct', rabbitmq_routing_key_list = 'non-existent', rabbitmq_format = 'JSONEachRow';

CREATE TABLEtest_order (
    id UInt32
) ENGINE = MergeTree()
ORDER BY id;

CREATE MATERIALIZED VIEW test_order_mv TO test_order AS
SELECT
    id AS id
FROM report.test_order_queue;

```  

* Queries to run that lead to slow performance. Data sent to queue. `{"id": 6}`
* ClickHouse server version to use. `23.8.12.13`
* Used Managed Service for ClickHouse by Yandex Cloud

### PR DESCRIPTION
**Pull request by jaapieaapie1**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed excessive RabbitMQ table engine CPU usage

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

Closes #62525 #50692 and #53401 

Before:
screenshot-2026-04-14_21-32-10

After:
screenshot-2026-04-14_21-30-30

Ofcourse verified that all functionality stays in tact and it still recovers from errors like disconnections from rabbitmq.

### Version info
- Merged into: `26.4.1.1015`
- Backported to: `26.3.10.45`

### CODE REVIEW

File: src/Storages/RabbitMQ/RabbitMQHandler.cpp [hunk 1]
```diff
@@ -40,7 +40,10 @@ void RabbitMQHandler::startLoop()
     loop_running.store(true);
 
     while (loop_state.load() == Loop::RUN)
-        uv_run(loop, UV_RUN_NOWAIT);
+    {
+        if (!uv_run(loop, UV_RUN_ONCE))
```
Comment (nikitamikhaylov) [inline src/Storages/RabbitMQ/RabbitMQHandler.cpp]: It seems calling `std::this_thread::yield();` when the `uv_run` return 0 is a better option, because the return value tells you whether the loop still has pending work (!= 0) or is fully drained (== 0).

File: src/Storages/RabbitMQ/RabbitMQHandler.cpp [hunk 2]
```diff
@@ -40,7 +41,10 @@ void RabbitMQHandler::startLoop()
...
```
Comment (nikitamikhaylov) [inline src/Storages/RabbitMQ/RabbitMQHandler.cpp]: And we can return `UV_RUN_NOWAIT`

**Comment by nikitamikhaylov** [comment]
Let's fix tests.

**Comment by jaapieaapie1** [comment]
@nikitamikhaylov the remaining test failure seems unrelated or a random failure?

**Review by kssenii — APPROVED** [review]

File: tests/integration/test_storage_rabbitmq/test_shutdown.py [hunk 3]
```diff
@@ -225,6 +225,107 @@ def test_attach_detach_rabbitmq_with_materialized_view(started_cluster):
...
+            rabbitmq_format = 'JSONEachRow',
+            rabbitmq_username = 'root',
+            rabbitmq_password = 'clickhouse',
+            rabbitmq_flush_interval_ms = 100,
+            rabbitmq_max_block_size = 100
+    """
+    )
+
+    # Wait for the connection to be established and the loop to start running.
+    time.sleep(10)
```
Comment (kssenii) [inline tests/integration/test_storage_rabbitmq/test_shutdown.py]: Let's add a loop instead of sleep to make it more robust

Comment (jaapieaapie1) [reply tests/integration/test_storage_rabbitmq/test_shutdown.py]: I don't think the sleep is actually necessary anymore because of the wait for logs beneath it. removed.

**Comment by jaapieaapie1** [comment]
Failing test seems unrelated/flaky

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
Thank you for the fix!

**Comment by clickgapai** [comment]
Hi — this PR may need backporting to `26.3` (LTS), `26.2`, `26.1`, `25.8` (LTS), but no backport label was found.

**Affected code:** `RabbitMQHandler::startLoop` busy-spinning with `uv_run(UV_RUN_NOWAIT)` and `RabbitMQHandler::stopLoop` conflating blocking/non-blocking loop stop semantics — core code present in all supported branches.

**Why:** The busy-spinning CPU waste in `RabbitMQHandler::startLoop` has existed since the RabbitMQ engine was introduced in 2020, predating all supported branches. The fix is minimal (adding `yield` + method split) and safe. Users on all supported branches experience 20%+ unnecessary CPU load when using RabbitMQ tables.

If this should be backported, consider adding `pr-must-backport` or a version-specific label (e.g. `v26.3-must-backport`). Ignore this if backporting is not applicable.

**Comment by jaapieaapie1** [comment]
@kssenii could you add backport labels? If you agree with this needing backporting.
