### PR TITLE
Fix bug in `reverseUTF8`

### LINKED ISSUE #88913: reverseUTF8() reverses bytes instead of UTF-8 code points causing corruption
### Describe what's wrong

The `reverseUTF8()` function currently reverses raw bytes rather than UTF-8 code points. This leads to corrupted output for multi-byte characters (such as emojis).

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Using ClickHouse version: `version 25.6.2`

`SELECT hex(reverseUTF8('🇬🇧🌈')) AS reverse_hex`

Output: `reverse_hex:      888C9FF0A7879FF0AC879FF0`

### Expected behavior

Expected output: 
'🌈🇧🇬' -> hex:`F09F8C88F09F87A7F09F87AC`

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix bug in the function `reverseUTF8`. In previous versions, it mistakenly reversed the bytes of UTF-8 code points of length 4. This closes #88913.

### CODE REVIEW

File: tests/queries/0_stateless/03699_reverse_utf8.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- The function reverses the sequence of UTF-8 code points (that is different from bytes or full characters):
+
+SELECT reverseUTF8('привіт');
```
Comment (PedroTadim) [inline tests/queries/0_stateless/03699_reverse_utf8.sql:3]: Do the examples cover 2, 3, and 4-byte characters?

**Review by Algunenano — APPROVED** [review]
LGTM. The existing conditions are a bit confusing (I was expecting <= to better see bits comparison) but it looks good and the fix is obvious. Nice

**Comment by alexey-milovidov** [comment]
Thanks for the clue. This sounds strange:
```
if (data[j] < 0xBF)
```

File: src/Functions/reverseUTF8.cpp [hunk 2]
```diff
@@ -46,7 +46,7 @@ struct ReverseUTF8Impl
             ColumnString::Offset j = prev_offset;
             while (j < offsets[i])
             {
-                if (data[j] < 0xBF)
+                if (data[j] < 0xC0)
```
Comment (Algunenano) [inline src/Functions/reverseUTF8.cpp:49]: LGTM. Technically this should be `0x80` and we should ignore anything in the shape `10XXXXXX` as those are continuation bytes inside a multibyte character. But it seems fine to simply treat them as 1-byte characters instead of throwing, which would be ok too.
