### PR TITLE
Fix column not found for push down with join

### LINKED ISSUE #39505: 22.7 Not found column in block with a join and a filter on a UInt8 column
```
SELECT deleted
FROM
(
    SELECT
        1 AS deleted,
        '' AS a,
        '' AS b
) AS q
INNER JOIN
(
    SELECT
        '' AS a,
        '' AS c
) AS s USING (a)
WHERE deleted AND (b = c)

Query id: 5efc7f50-bf5a-4e1a-86e7-68b2d3f1ff93

0 rows in set. Elapsed: 0.764 sec.

Received exception from server (version 22.7.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column deleted in block. (NOT_FOUND_COLUMN_IN_BLOCK)

ClickHouse client version 22.6.3.35 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.6.3 revision 54455.

SELECT deleted
FROM
(
    SELECT
        1 AS deleted,
        '' AS a,
        '' AS b
) AS q
INNER JOIN
(
    SELECT
        '' AS a,
        '' AS c
) AS s USING (a)
WHERE deleted AND (b = c)

Query id: b9031e85-8822-493c-ad84-2885b336fc8d

┌─deleted─┐
│       1 │
└─────────┘
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix "column not found" error for push down with join, close https://github.com/ClickHouse/ClickHouse/issues/39505

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp [hunk 1]
```diff
@@ -42,11 +42,18 @@ static bool filterColumnIsNotAmongAggregatesArguments(const AggregateDescription
     return true;
 }
 
-static size_t
-tryAddNewFilterStep(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes, const Names & allowed_inputs,
-                    bool can_remove_filter = true, size_t child_idx = 0)
+static void checkChildrenSize(QueryPlan::Node * child_node, size_t child_idx )
+{
+    auto & child = child_node->step;
+    if (child_idx >= child->getInputStreams().size() || child_idx >= child_node->children.size())
```
Comment (devcrafter) [inline src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:48]: What if children are empty?

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp [hunk 2]
```diff
@@ -118,6 +130,15 @@ tryAddNewFilterStep(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes, con
     return 3;
 }
 
+static size_t
+tryAddNewFilterStep(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes, const Names & allowed_inputs,
+                    bool can_remove_filter = true)
+{
+    if (auto split_filter = splitFilter(parent_node, allowed_inputs, 0))
+        return tryAddNewFilterStep(parent_node, nodes, std::move(split_filter), can_remove_filter, 0);
```
Comment (devcrafter) [inline src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:138]: There is no need for `move`, `tryAddNewFilterStep()` should just accept `const &` on shared ptr.

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp [hunk 3]
```diff
@@ -248,12 +269,24 @@ size_t tryPushDownFilter(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes
                 allowed_keys.push_back(name);
             }
 
-            const bool can_remove_filter
-                = std::find(source_columns.begin(), source_columns.end(), filter->getFilterColumnName()) == source_columns.end();
-            size_t updated_steps = tryAddNewFilterStep(parent_node, nodes, allowed_keys, can_remove_filter, is_left ? 0 : 1);
+            ActionsDAGPtr split_filter = splitFilter(parent_node, allowed_keys, is_left ? 0 : 1);
```
Comment (devcrafter) [inline src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:272]:
```suggestion
            const auto child_idx = is_left ? 0 : 1;
            ActionsDAGPtr split_filter = splitFilter(parent_node, allowed_keys, child_idx);
```

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp [hunk 4]
```diff
@@ -248,12 +269,24 @@ size_t tryPushDownFilter(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes
...
+             *
+             * Example:
+             * A filter expression is `a AND b = c`, but `b` and `c` belong to another side of the join and not in `allowed_keys`, so the final split filter is just `a`.
+             * In this case `a` can be in `source_columns` but not `and(a, equals(b, c))`.
+             *
+             * New filter column is the first one.
+             */
+            const String & split_filter_column_name = split_filter->getIndex().front()->result_name;
+            bool can_remove_filter = source_columns.end() == std::find(source_columns.begin(), source_columns.end(), split_filter_column_name);
+            size_t updated_steps = tryAddNewFilterStep(parent_node, nodes, split_filter, can_remove_filter, is_left ? 0 : 1);
```
Comment (devcrafter) [inline src/Processors/QueryPlan/Optimizations/filterPushDown.cpp:286]:
```suggestion
            const size_t updated_steps = tryAddNewFilterStep(parent_node, nodes, split_filter, can_remove_filter, child_idx);
```

File: tests/queries/0_stateless/02367_join_pushdown_column_not_found.sql [hunk 5]
```diff
@@ -0,0 +1,9 @@
+SELECT deleted
```
Comment (devcrafter) [inline tests/queries/0_stateless/02367_join_pushdown_column_not_found.sql:1]: It'd be nice to have a test with more than one pushed down conditions, for right side and both as well (left and right)

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp (hunk 1 above)
Comment (vdimir) [reply src/Processors/QueryPlan/Optimizations/filterPushDown.cpp]: Changed to pass expected child number `child_num` instead of index and added comment

File: src/Processors/QueryPlan/Optimizations/filterPushDown.cpp [hunk 6]
```diff
@@ -56,23 +63,28 @@ tryAddNewFilterStep(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes, con
...
+tryAddNewFilterStep(QueryPlan::Node * parent_node, QueryPlan::Nodes & nodes, ActionsDAGPtr split_filter,
+                    bool can_remove_filter = true, size_t child_idx = 0)
+{
+    QueryPlan::Node * child_node = parent_node->children.front();
+    checkChildrenSize(child_node, child_idx);
+
+    auto & parent = parent_node->step;
+    auto & child = child_node->step;
+
+    auto * filter = static_cast<FilterStep *>(parent.get());
```
[the remark this answers is not in the document]
Comment (vdimir) [reply src/Processors/QueryPlan/Optimizations/filterPushDown.cpp]: Changed to `assert_cast` we have checked type with `typeid_cast` in the beginning of `tryPushDownFilter`

https://github.com/ClickHouse/ClickHouse/blob/298fb2431da4a1ee85495d63557d405d9fe21339/src/Processors/QueryPlan/Optimizations/filterPushDown.cpp#L152-L155

File: tests/queries/0_stateless/02367_join_pushdown_column_not_found.sql (hunk 5 above)
Comment (vdimir) [reply tests/queries/0_stateless/02367_join_pushdown_column_not_found.sql]: Added check for different algorithms https://github.com/ClickHouse/ClickHouse/blob/298fb2431da4a1ee85495d63557d405d9fe21339/tests/queries/0_stateless/02367_join_pushdown_column_not_found.sql.j2#L1

Comment (devcrafter) [reply tests/queries/0_stateless/02367_join_pushdown_column_not_found.sql]: Thanks. But it doesn't check right side of join
