### PR TITLE
Update parseQuery.cpp (fix problem with "insert into select" with PostgreSQL interface)

### LINKED ISSUE #72938: Crash in Mac OS over postgresql interface
postregsql interface, mac os

SQL:
```
insert into "stocks" ("assortment_id", "branch_id", "stock", "store_id", "updated", "is_deleted") select "assortment_id", "branch_id", "stock", "store_id", "updated", true as is_deleted from "stocks" where "updated" < 2024-12-09 14:09:36.226 and "is_deleted" = 0
```

```
2024.12.09 16:01:34.162320 [ 39469741 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.12.09 16:01:34.162507 [ 39469741 ] {} <Fatal> BaseDaemon: (version 24.12.1.552 (official build), build id: , git hash: bc79653eedb596c1694471ba20bb8b740301032a, architecture: arm64) (from thread 39468724) Received signal 11
2024.12.09 16:01:34.162579 [ 39469741 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault: 11
2024.12.09 16:01:34.162621 [ 39469741 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: <not available on Darwin>. Attempted access has violated the permissions assigned to the memory area.
2024.12.09 16:01:34.162672 [ 39469741 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000010f0e39a0
2024.12.09 16:01:34.162710 [ 39469741 ] {} <Fatal> BaseDaemon: ########################################
2024.12.09 16:01:34.162750 [ 39469741 ] {} <Fatal> BaseDaemon: (version 24.12.1.552 (official build), build id: , git hash: bc79653eedb596c1694471ba20bb8b740301032a) (from thread 39468724) (no query) Received signal Segmentation fault: 11 (11)
2024.12.09 16:01:34.162787 [ 39469741 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: <not available on Darwin>. Attempted access has violated the permissions assigned to the memory area.
2024.12.09 16:01:34.162821 [ 39469741 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000010f0e39a0
2024.12.09 16:01:34.169938 [ 39469741 ] {} <Fatal> BaseDaemon: 0. DB::splitMultipartQuery(String const&, std::vector<String, std::allocator<String>>&, unsigned long, unsigned long, unsigned long, bool, bool) @ 0x000000010f0e39a0
2024.12.09 16:01:34.173722 [ 39469741 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2024.12.09 16:01:38.170478 [ 39468720 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

### PR DESCRIPTION
**Pull request by ArtemYurov**
Resolves #72938 

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash with query `INSERT INTO SELECT` over PostgreSQL interface on macOS (issue #72938)

### CODE REVIEW

**Comment by jsc0218** [comment]
A test is needed to pass the ci for the bug category.

**Comment by ArtemYurov** [comment]
> A test is needed to pass the ci for the bug category.

How to do it?

**Comment by jsc0218** [comment]
> > A test is needed to pass the ci for the bug category.
> 
> How to do it?

You can reference the file [here](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_postgresql_database_engine/test.py) to generate a test at least for postgres interface.

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 27ea35d000d04fa5a5789cf2e3a2eb04fa204653 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74231/27ea35d000d04fa5a5789cf2e3a2eb04fa204653/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b3b9000d9504bea9d0af637a1a09e7a622d40cc8/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by ArtemYurov** [comment]
> > > A test is needed to pass the ci for the bug category.
> > 
> > 
> > How to do it?
> 
> You can reference the file [here](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_postgresql_database_engine/test.py) to generate a test at least for postgres interface.

ready

```
default=> CREATE DATABASE x; USE x; CREATE TABLE table1 (column UInt32) ENGINE = Memory; INSERT INTO table1 VALUES (0), (1), (5); CREATE TABLE table2 (column UInt32) ENGINE = Memory; INSERT INTO table2 SELECT * FROM table1; DROP DATABASE x; 
SELECT 0
SELECT 0
SELECT 0
INSERT 0 0
SELECT 0
INSERT 0 0
SELECT 0
default=> 
```

**Comment by ArtemYurov** [comment]
> yes, but need some python style change according to the CI here.

I used the same style as the rest of the code. Does this mean that you need to change the entire file’s style?

**Comment by jsc0218** [comment]
You can see it from the prompt [here](https://s3.amazonaws.com/clickhouse-test-reports/74231/5d185be026182552eebacd3b1ff4d7056c45f9d8/style_check.html), just the code you changed.

**Comment by ArtemYurov** [comment]
also how to to add this fix to version 24?

File: src/Parsers/parseQuery.cpp [hunk 1]
```diff
@@ -467,7 +467,7 @@ std::pair<const char *, bool> splitMultipartQuery(
 
         ast = parseQueryAndMovePosition(parser, pos, end, "", true, max_query_size, max_parser_depth, max_parser_backtracks);
 
-        if (ASTInsertQuery * insert = getInsertAST(ast))
+        if (ASTInsertQuery * insert = getInsertAST(ast); insert && insert->data)
```
Comment (rschu1ze) [inline src/Parsers/parseQuery.cpp:470]: This is a central location in the code which (I think) is executed by all interfaces, not only Postgres.

Does the issue reproduce with "normal" queries as well? If so, we can write a standard SQL-based test instead of a integration test.

Comment (ArtemYurov) [reply src/Parsers/parseQuery.cpp:470]: i only tried this advice from #72938
i am not tested it with other interfaces

Comment (jsc0218) [reply src/Parsers/parseQuery.cpp:470]: I think it is okay to have the code here. The added code just acts as a guardian, and no logic change for the following code.

**Comment by jsc0218** [comment]
@ArtemYurov could you update with the master once, as I am not sure test_async_metrics_in_cgroup is relevant or not?

**Comment by jsc0218** [comment]
blocked by [02125_many_mutations](https://github.com/ClickHouse/ClickHouse/issues/65589)

**Comment by jsc0218** [comment]
@ArtemYurov Would you mind to update with master once again? Looks like the failed test has been fixed. Which version do you want to fix? 24.10, 24.11 or else?

**Comment by ArtemYurov** [comment]
Ready

24.12 is ok
