### PR TITLE
Parallel replicas. Part [2]

### LINKED ISSUE #34527: Double output while using allow_experimental_parallel_reading_from_replicas=1
How to reproduce: run test 00124_shard_distributed_with_many_replicas.sql with different values of setting `allow_experimental_parallel_reading_from_replicas` 
```
ch-client --allow_experimental_parallel_reading_from_replicas=0 -nmT < 00124_shard_distributed_with_many_replicas.sql
1	2015-01-01	1	foo
2	2015-02-01	2	bar
3	2015-03-01	3	foo
4	2015-04-01	4	bar
5	2015-05-01	5	foo
```

```
ch-client --allow_experimental_parallel_reading_from_replicas=1 -nmT < 00124_shard_distributed_with_many_replicas.sql
1	2015-01-01	1	foo
1	2015-01-01	1	foo
2	2015-02-01	2	bar
2	2015-02-01	2	bar
3	2015-03-01	3	foo
3	2015-03-01	3	foo
4	2015-04-01	4	bar
4	2015-04-01	4	bar
5	2015-05-01	5	foo
5	2015-05-01	5	foo
```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rewrote the code around marks distribution and the overall coordination of the reading in order to achieve the maximum performance improvement. This closes #34527.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/ClusterProxy/executeQuery.cpp [hunk 1]
```diff
@@ -236,103 +246,75 @@ void executeQueryWithParallelReplicas(
...
-            plans.emplace_back(std::move(remote_plan));
-        }
-    }
-
-    if (plans.empty())
-        throw Exception(ErrorCodes::LOGICAL_ERROR, "No plans were generated for reading from Distributed. This is a bug");
-
-    if (plans.size() == 1)
+    if (not_optimized_cluster->getShardsInfo().size() != 1)
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Cluster for parallel replicas should consist only from one shard");
```
Comment (KochetovNicolai) [inline src/Interpreters/ClusterProxy/executeQuery.cpp:253]: Probably not a LOGICAL_ERROR, but user's error.
Please, add a number of shards to the exception message.

File: src/Interpreters/ClusterProxy/executeQuery.cpp [hunk 2]
```diff
@@ -236,103 +246,75 @@ void executeQueryWithParallelReplicas(
...
+    auto coordinator = std::make_shared<ParallelReplicasReadingCoordinator>(all_replicas_count);
+    auto remote_plan = std::make_unique<QueryPlan>();
+    auto plans = std::vector<QueryPlanPtr>();
+
+    /// This is a little bit weird, but we construct an "empty" coordinator without
+    /// any specified reading/coordination method (like Default, InOrder, InReverseOrder)
+    /// Because we will understand it later during QueryPlan optimization
+    /// So we place a reference to the coordinator to some common plane like QueryInfo
+    /// to then tell it about the reading method we chose.
+    query_info.coordinator = coordinator;
```
Comment (KochetovNicolai) [inline src/Interpreters/ClusterProxy/executeQuery.cpp:270]: Possible, start with Default and change to InOrder/InReverseOrder when optimization is applied?
But looks ok geenrally

File: src/Interpreters/Context.cpp [hunk 3]
```diff
@@ -3464,6 +3464,20 @@ void Context::setMergeTreeReadTaskCallback(MergeTreeReadTaskCallback && callback
     merge_tree_read_task_callback = callback;
 }
 
+
+MergeTreeAllRangesCallback Context::getMergeTreeAllRangesCallback() const
+{
+    if (!merge_tree_all_ranges_callback.has_value())
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Next task callback for is not set for query {}", getInitialQueryId());
```
Comment (KochetovNicolai) [inline src/Interpreters/Context.cpp:3471]: It is something wrong with this error message.

File: src/Interpreters/InterpreterInsertQuery.cpp [hunk 4]
```diff
@@ -285,7 +285,7 @@ Chain InterpreterInsertQuery::buildChainImpl(
 
     /// Do not squash blocks if it is a sync INSERT into Distributed, since it lead to double bufferization on client and server side.
     /// Client-side bufferization might cause excessive timeouts (especially in case of big blocks).
-    if (!(settings.insert_distributed_sync && table->isRemote()) && !async_insert && !no_squash && !(query && query->watch))
+    if (!(settings.insert_distributed_sync && table->isRemote(context_ptr)) && !async_insert && !no_squash && !(query && query->watch))
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterInsertQuery.cpp:288]: According to the comment, this is only relevant to insert into distributed. Not relevant for parallel replicas.
(passing context to isRemote method unacceptable).

File: src/Interpreters/InterpreterInsertQuery.cpp [hunk 5]
```diff
@@ -332,7 +332,7 @@ BlockIO InterpreterInsertQuery::execute()
     if (!query.table_function)
         getContext()->checkAccess(AccessType::INSERT, query.table_id, query_sample_block.getNames());
 
-    if (query.select && table->isRemote() && settings.parallel_distributed_insert_select)
+    if (query.select && table->isRemote(getContext()) && settings.parallel_distributed_insert_select)
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterInsertQuery.cpp:335]: Not relevant for parallel replicas as well

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 6]
```diff
@@ -160,7 +161,7 @@ FilterDAGInfoPtr generateFilterActions(
     table_expr->children.push_back(table_expr->database_and_table_name);
 
     /// Using separate expression analyzer to prevent any possible alias injection
-    auto syntax_result = TreeRewriter(context).analyzeSelect(query_ast, TreeRewriterResult({}, storage, storage_snapshot));
+    auto syntax_result = TreeRewriter(context).analyzeSelect(query_ast, TreeRewriterResult(context, {}, storage, storage_snapshot));
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterSelectQuery.cpp:164]: :(

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 7]
```diff
@@ -446,6 +447,9 @@ InterpreterSelectQuery::InterpreterSelectQuery(
         }
     }
 
+    if (joined_tables.tablesCount() > 1 && settings.allow_experimental_parallel_reading_from_replicas)
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterSelectQuery.cpp:450]: Not a good solution. It's better to automatically disable parallel replicas for JOIN. Or we couldn't enable it by default.

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 8]
```diff
@@ -1865,14 +1869,16 @@ void InterpreterSelectQuery::addEmptySourceToQueryPlan(
...
 
-void InterpreterSelectQuery::setMergeTreeReadTaskCallbackAndClientInfo(MergeTreeReadTaskCallback && callback)
+void InterpreterSelectQuery::setMergeTreeReadTaskCallbackAndClientInfo(MergeTreeAllRangesCallback && all_callback, MergeTreeReadTaskCallback && callback)
 {
     context->getClientInfo().collaborate_with_initiator = true;
+    context->setMergeTreeAllRangesCallback(std::move(all_callback));
     context->setMergeTreeReadTaskCallback(std::move(callback));
 }
 
 void InterpreterSelectQuery::setProperClientInfo(size_t replica_num, size_t replica_count)
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterSelectQuery.cpp:1879]: This method name is confusing. Maybe something like `enableParallelReplicas`

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 9]
```diff
@@ -2164,7 +2170,7 @@ void InterpreterSelectQuery::executeFetchColumns(QueryProcessingStage::Enum proc
      *  instead of max_threads, max_distributed_connections is used.
      */
     bool is_remote = false;
-    if (storage && storage->isRemote())
+    if (storage && storage->isRemote(context))
     {
         is_remote = true;
         max_threads_execute_query = max_streams = settings.max_distributed_connections;
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterSelectQuery.cpp:2176]: This is relevant to parallel replicas.
Interesting thing is that `Distributed` ignores max_streams in `read` method (so probably `max_distributed_connections` is useless?), and this is only used for `merge_threads` value at AggregatingStep (and I don't understand why not max_threads). It looks like we can make `max_streams` local.

File: src/Interpreters/TreeRewriter.cpp [hunk 10]
```diff
@@ -1030,16 +1030,18 @@ using RewriteShardNumVisitor = InDepthNodeVisitor<RewriteShardNum, true>;
...
     bool add_special)
-    : storage(storage_)
+    : WithContext(context_)
+    , storage(storage_)
     , storage_snapshot(storage_snapshot_)
     , source_columns(source_columns_)
 {
     collectSourceColumns(add_special);
-    is_remote_storage = storage && storage->isRemote();
+    is_remote_storage = storage && storage->isRemote(getContext());
```
Comment (KochetovNicolai) [inline src/Interpreters/TreeRewriter.cpp:1044]: I tried to find all the places where `is_remote_storage` is used:
* Tree optimizer, `optimizeMonotonousFunctionsInOrderBy`. There is a comment that we can't get the sorting key from the underlying table of distributed. But in case of parallel replicas,  I think, we can assume it's the same as in local replica.
* `TreeRewriterResult::collectUsedColumns`, to check if there is a virtual column `_shard_num`. I think we can assume there is no such column for parallel replicas.
* Inside InterpreterSelectQuery, analyze, `context->setDistributed`. But looks like it's only used for functions like `hostName()` to get different results from different shards/replicas. I think we can skip it for now for parallel replicas from MergeTree (and enable it later if needed).
* Inside ExpressionAnalyzer, to build subqueries for IN or GLOBAL IN. I suppose it's also ok for now to ignore GLOBAL IN for parallel replicas for now. As for IN, we avoid creating sets for Distributed tables. But it's actually ok to create a set earlier for parallel replicas cause there 100% should be a local replica, and a set for local replica should be built. And we won't build it a second time (it's better to check, but we shouldn't).

So, looks like all these cases are really only for Distributed. So I would vote to remove context from here).

File: src/Planner/CollectTableExpressionData.cpp [hunk 11]
```diff
@@ -96,12 +96,12 @@ void collectTableExpressionData(QueryTreeNodePtr & query_node, PlannerContext &
 
         if (auto * table_node = table_expression_node->as<TableNode>())
         {
-            bool storage_is_remote = table_node->getStorage()->isRemote();
+            bool storage_is_remote = table_node->getStorage()->isRemote(planner_context.getQueryContext());
```
Comment (KochetovNicolai) [inline src/Planner/CollectTableExpressionData.cpp:99]: I tried to find out where `isRemote()` is used for a new analyzer. Looks like it is not used yet, cause distributed processing is not written. But I hope it would be similar to what we have currently.

File: src/Storages/StorageMergeTree.h [hunk 12]
```diff
@@ -58,6 +58,8 @@ class StorageMergeTree final : public MergeTreeData
 
     bool supportsTransactions() const override { return true; }
 
+    bool isRemote([[ maybe_unused ]] ContextPtr local_context) const override { return local_context->getSettingsRef().allow_experimental_parallel_reading_from_replicas && !local_context->getClientInfo().collaborate_with_initiator; }
```
Comment (KochetovNicolai) [inline src/Storages/StorageMergeTree.h:61]: I think we'd better have a separate flag `supportRemoteReading()` or something like this.
Will call it only inside InterpreterSelectQuery, and `isRemote` will mean only Distributed storage. It seem to be safer.

Comment (KochetovNicolai) [reply src/Storages/StorageMergeTree.h:61]: Also, we won't need to specify `context`. Can check this condition on the single caller side in InterpreterSelectQuery

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 13]
```diff
@@ -1267,6 +1356,17 @@ void ReadFromMergeTree::initializePipeline(QueryPipelineBuilder & pipeline, cons
 
     const auto & input_order_info = query_info.getInputOrderInfo();
 
+    /// Construct a proper coordinator
+    if (input_order_info && is_parallel_reading_from_replicas && context->getClientInfo().interface == ClientInfo::Interface::LOCAL)
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:1360]: Condition `context->getClientInfo().interface == ClientInfo::Interface::LOCAL` is unclear. Please, add a comment.

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 14]
```diff
@@ -104,7 +105,7 @@ ReadFromRemote::ReadFromRemote(
     Poco::Logger * log_,
     UInt32 shard_count_,
     std::shared_ptr<const StorageLimitsList> storage_limits_)
-    : ISourceStep(DataStream{.header = std::move(header_)})
+    : ISourceStep(DataStream{.header = header_})
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:108]: why?

File: src/Storages/MergeTree/MergeTreeParallelReplicasSelectProcessor.h [hunk 15]
```diff
@@ -0,0 +1,52 @@
...
+
+#include <memory>
+
+namespace DB
+{
+
+class MergeTreeReadPoolParallelReplicas;
+using MergeTreeReadPoolParallelReplicasPtr = std::shared_ptr<MergeTreeReadPoolParallelReplicas>;
+
+class MergeTreeParallelReplicasSelectProcessor final : public IMergeTreeSelectAlgorithm
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeParallelReplicasSelectProcessor.h:13]: What's the difference with `MergeTreeThreadSelectAlgorithm`? Now, the only change I see is a different pool

File: src/Storages/MergeTree/MergeTreeReadPoolParallelReplicas.h [hunk 16]
```diff
@@ -0,0 +1,129 @@
...
+#include <condition_variable>
+#include <mutex>
+#include <memory>
+
+namespace DB
+{
+
+
+/// Weird class with copy-paste from original read pool
+class MergeTreeReadPoolParallelReplicas :  private boost::noncopyable
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeReadPoolParallelReplicas.h:22]: Would be good to see what's the difference with an ordinary pool.
Now, looks like a lot of code was copy-pasted.

**Review by KochetovNicolai — CHANGES_REQUESTED** [review]
Everything else generally looks ok.
I did not check what changes were done in ParallelReplicasReadingCoordinator yet, but this is an isolated code.

Interesting to understand if we handle compatibility correctly. But it's ok to completely brake it here.

File: src/Storages/MergeTree/MergeTreeReadPoolParallelReplicas.h (hunk 16 above)
Comment (nikitamikhaylov) [reply src/Storages/MergeTree/MergeTreeReadPoolParallelReplicas.h:22]: This pool doesn't split all the tasks. Everything it does - just collect the info about all the parts for further usage and act like a proxy for requests to coordinator. It could be done inside ordinary pool, but I guess it will make the code completely unreadable. For isolation purposes I decided to create a separate class.

File: src/Storages/MergeTree/MergeTreeParallelReplicasSelectProcessor.h (hunk 15 above)
Comment (nikitamikhaylov) [reply src/Storages/MergeTree/MergeTreeParallelReplicasSelectProcessor.h:13]: You're right, there is no difference and we can unify them. Initially it was done not to mix together the old code and a new one, but I can beautify it somehow.

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp (hunk 13 above)
Comment (nikitamikhaylov) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp:1360]: It means that we read from local replica

File: src/Storages/StorageMergeTree.h (hunk 12 above)
Comment (nikitamikhaylov) [reply src/Storages/StorageMergeTree.h:61]: Yes, this is an ugly solution and has to be redone.

**Comment by nikitamikhaylov** [comment]
For now we will a pipeline like this for distributed reading. Reason - we have to respect both Remote source and local replica and constantly answering for "coordination" packets coming from the outside. 

graphviz (3)

File: src/Interpreters/ClusterProxy/executeQuery.cpp (hunk 2 above)
Comment (nikitamikhaylov) [reply src/Interpreters/ClusterProxy/executeQuery.cpp:270]: Coordinator class is just an interface. It stores an Impl object inside and creates it lazily. It doesn't make sense to create a Default Impl here.

File: tests/performance/memory_bound_merging.xml [hunk 17]
```diff
@@ -11,7 +11,5 @@
 
   <query>select avg(a) from remote('127.0.0.{{1,2}}', default, t_mbm) group by a format Null</query>
 
-  <query>select * from remote('127.0.0.{{1,2}}', default, t_mbm) group by a format Null settings allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 2, use_hedged_requests = 0</query>
```
Comment (nikitamikhaylov) [inline tests/performance/memory_bound_merging.xml:14]: Deleted this test, because Distributed table is no longer needed, but we don't have any cluster in config for performance-comparison test (cluster spec is still required)

File: src/Client/Connection.cpp [hunk 18]
```diff
@@ -33,6 +33,7 @@
 #include <pcg_random.hpp>
 #include <base/scope_guard.h>
 
+#include "Interpreters/Context.h"
```
Comment (KochetovNicolai) [inline src/Client/Connection.cpp:36]: Probably this incude is not needed anymore

File: src/Interpreters/InterpreterSelectQuery.h [hunk 19]
```diff
@@ -16,6 +16,7 @@
 #include <QueryPipeline/Pipe.h>
 
 #include <Columns/FilterDescription.h>
+#include "Storages/MergeTree/RequestResponse.h"
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterSelectQuery.h:19]: I thins this is also not needed anymore

File: src/QueryPipeline/QueryPipelineBuilder.cpp [hunk 20]
```diff
@@ -618,6 +619,31 @@ void QueryPipelineBuilder::setProgressCallback(ProgressCallback callback)
...
+void QueryPipelineBuilder::connectDependencies()
+{
+    std::vector<RemoteSource *> input_dependencies;
+    std::vector<ReadFromMergeTreeDependencyTransform *> output_dependencies;
+
+    for (auto & processor : *pipe.getProcessorsPtr())
+    {
+        if (auto * remote_dependency = dynamic_cast<RemoteSource *>(processor.get()); remote_dependency)
+            input_dependencies.emplace_back(remote_dependency);
+        if (auto * merge_tree_dependency = dynamic_cast<ReadFromMergeTreeDependencyTransform *>(processor.get()); merge_tree_dependency)
```
Comment (KochetovNicolai) [inline src/QueryPipeline/QueryPipelineBuilder.cpp:631]: maybe make `RemoteSource` and `ReadFromMergeTreeDependencyTransform` final classes, and use typeid_cast here ...

File: src/QueryPipeline/QueryPipelineBuilder.cpp [hunk 21]
```diff
@@ -618,6 +619,31 @@ void QueryPipelineBuilder::setProgressCallback(ProgressCallback callback)
...
+            output_dependencies.emplace_back(merge_tree_dependency);
+    }
+
+    if (input_dependencies.empty() || output_dependencies.empty())
```
Comment (KochetovNicolai) [inline src/QueryPipeline/QueryPipelineBuilder.cpp:635]: Maybe also after check , additionally check that both are not empty, just in case

File: src/QueryPipeline/QueryPipelineBuilder.cpp [hunk 22]
```diff
@@ -618,6 +619,31 @@ void QueryPipelineBuilder::setProgressCallback(ProgressCallback callback)
     progress_callback = callback;
 }
 
+void QueryPipelineBuilder::connectDependencies()
```
Comment (KochetovNicolai) [inline src/QueryPipeline/QueryPipelineBuilder.cpp:622]: lgtm, but please add a comment

File: src/QueryPipeline/RemoteQueryExecutor.h [hunk 23]
```diff
@@ -94,12 +94,18 @@ class RemoteQueryExecutor
     /// Query is resent to a replica, the query itself can be modified.
     std::atomic<bool> resent_query { false };
 
+    struct ParallelReplicasToken {};
+    struct Nothing {};
+    using ReadResult = std::variant<Block, ParallelReplicasToken, int, Nothing>;
```
Comment (KochetovNicolai) [inline src/QueryPipeline/RemoteQueryExecutor.h:99]: I think this is ok.

But, probably, a bit better to make EnumClass + struct ...

Comment (KochetovNicolai) [reply src/QueryPipeline/RemoteQueryExecutor.h:99]: Maybe we also need a status like `Cancelled` or `Finished`.
Previously it was empty Block

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 24]
```diff
@@ -6807,6 +6809,12 @@ QueryProcessingStage::Enum MergeTreeData::getQueryProcessingStage(
     const StorageSnapshotPtr & storage_snapshot,
     SelectQueryInfo & query_info) const
 {
+    if (query_context->getClientInfo().collaborate_with_initiator)
+        return QueryProcessingStage::Enum::FetchColumns;
+
+    if (query_context->getSettingsRef().allow_experimental_parallel_reading_from_replicas && !query_context->getClientInfo().collaborate_with_initiator)
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeData.cpp:6815]: I think here we also need to check `to_stage >= WithMergeableState`.
`to_stage` here is a stage up to which we want to execute a query. In theory it can be `FetchColumns`

File: src/Storages/MergeTree/MergeTreeData.h [hunk 25]
```diff
@@ -610,7 +610,7 @@ class MergeTreeData : public IStorage, public WithMutableContext
         }
 
         /// It's safe to get name of any part
-        const String & getPartName() const { return part->name; }
+        const String & getPartNameV1() const { return part->name; }
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeData.h:613]: Did not understand why this is needed ...

File: src/Storages/MergeTree/MergeTreePartInfo.cpp [hunk 26]
```diff
@@ -253,6 +253,33 @@ String MergeTreePartInfo::getPartNameV0(DayNum left_date, DayNum right_date) con
     return wb.str();
 }
 
+void MergeTreePartInfo::serialize(WriteBuffer & out) const
+{
+    writeStringBinary(partition_id, out);
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreePartInfo.cpp:258]: consider adding a version here. Just in case we will need to add something else

File: src/Storages/MergeTree/MergeTreeData.h (hunk 25 above)
Comment (nikitamikhaylov) [reply src/Storages/MergeTree/MergeTreeData.h:613]: Oops, I just replaced all usages...

File: src/Storages/MergeTree/MergeTreeReadPoolParallelReplicas.h [hunk 27]
```diff
@@ -0,0 +1,129 @@
...
+
+#include <condition_variable>
+#include <mutex>
+#include <memory>
+
+namespace DB
+{
+
+
+/// Weird class with copy-paste from original read pool
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeReadPoolParallelReplicas.h:21]: :(

File: src/Storages/StorageMergeTree.cpp [hunk 28]
```diff
@@ -211,9 +214,40 @@ void StorageMergeTree::read(
     if (enable_parallel_reading)
         LOG_TRACE(log, "Parallel reading from replicas enabled: {}", enable_parallel_reading);
 
-    if (auto plan = reader.read(
-        column_names, storage_snapshot, query_info, local_context, max_block_size, num_streams, processed_stage, nullptr, enable_parallel_reading))
-        query_plan = std::move(*plan);
+    const auto & settings = local_context->getSettingsRef();
+    bool parallel_replicas = settings.max_parallel_replicas > 1 && settings.allow_experimental_parallel_reading_from_replicas && !settings.use_hedged_requests && !local_context->getClientInfo().collaborate_with_initiator;
```
Comment (KochetovNicolai) [inline src/Storages/StorageMergeTree.cpp:218]: Context::canUseParallelReplicas()?

File: src/Storages/StorageMergeTree.h [hunk 29]
```diff
@@ -58,6 +58,8 @@ class StorageMergeTree final : public MergeTreeData
 
     bool supportsTransactions() const override { return true; }
 
+    bool isRemote() const override { return false; }
```
Comment (KochetovNicolai) [inline src/Storages/StorageMergeTree.h:61]: Remove?

File: src/Processors/Sources/RemoteSource.h [hunk 30]
```diff
@@ -26,6 +27,8 @@ class RemoteSource : public ISource
     Status prepare() override;
     String getName() const override { return "Remote"; }
 
+    void connectToScheduler(ResizeProcessor & scheduler);
```
Comment (KochetovNicolai) [inline src/Processors/Sources/RemoteSource.h:30]: Let's maybe replace resize_processor to `InputPort &` ? And remove `getFreeInputPortIfAny`

File: src/Processors/Transforms/RemoteDependencyTransform.h [hunk 31]
```diff
@@ -0,0 +1,36 @@
...
+    explicit ReadFromMergeTreeDependencyTransform(const Block & header);
+
+    String getName() const override { return "ReadFromMergeTreeDependency"; }
+    Status prepare() override;
+
+    InputPort & getInputPort() { assert(data_port); return *data_port; }
+    InputPort & getDependencyPort() { assert(dependency_port); return *dependency_port; }
+    OutputPort & getOutputPort() { return outputs.front(); }
+
+    void connectToScheduler(ResizeProcessor & scheduler);
```
Comment (KochetovNicolai) [inline src/Processors/Transforms/RemoteDependencyTransform.h:23]: Let's maybe replace resize_processor to `OutputPort &` ? And remove `ResizeProcessor::getFreeOutputPortIfAny`

**Review by KochetovNicolai — APPROVED** [review]
Generally LGTM. (I did not read ParallelReplicasReadingCoordinator attentively)

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 32]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
-    PartToRead::PartAndProjectionNames part_and_projection
-    {
-        .part = request.part_name,
-        .projection = request.projection_name
-    };
+        /// We have the same part - add the info about presence on current replica to it
+        if (the_same_it != all_parts_to_read.end())
+        {
+            the_same_it->replicas.insert(announcement.replica_num);
+            continue;
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:165]: do this before `covering_or_the_same_it` so you don't do search unnecessarily.

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 33]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
+    for (const auto & part : container)
     {
-        case PartSegments::IntersectionResult::REJECT:
+        if (std::find(part->replicas.begin(), part->replicas.end(), replica_num) == part->replicas.end())
+        {
+            LOG_TEST(log, "Not found part {} on replica {}", part->description.info.getPartNameV1(), replica_num);
+            continue;
+        }
+
+        if (current_mark_size >= min_number_of_marks)
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:255]: switch checks, do cheaper first

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 34]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
         {
-            LOG_TRACE(log, "Request rejected in {} ns: {}", watch.elapsed(), request_description);
-            return {.denied = true, .mark_ranges = {}};
+            LOG_TEST(log, "Current mark size {} is bigger than min_number_marks {}", current_mark_size, min_number_of_marks);
+            continue;
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:258]: shouldn't this be break? we never decrease `current_mark_size`

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 35]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
+            auto range = part->description.ranges.front();
+
+            if (range.getNumberOfMarks() > min_number_of_marks)
+            {
+                auto new_range = range;
+                range.begin += min_number_of_marks;
+                new_range.end = new_range.begin + min_number_of_marks;
+
+                part->description.ranges.front() = range;
+
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:283]:
```suggestion
            auto & range = part->description.ranges.front();

            if (range.getNumberOfMarks() > min_number_of_marks)
            {
                auto new_range = range;
                range.begin += min_number_of_marks;
                new_range.end = new_range.begin + min_number_of_marks;
```

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 36]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
+            .info = part->description.info,
+            .ranges = {},
+        });
+
+        while (!part->description.ranges.empty() && current_mark_size < min_number_of_marks)
         {
-            auto marks_it = partition_reading.mark_ranges_in_part.find(part_and_projection);
+            auto range = part->description.ranges.front();
+
+            if (range.getNumberOfMarks() > min_number_of_marks)
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:276]: why do we cap marks number based on `min_number_of_marks`?

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 37]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
+    for (const auto & part: announcement.description)
+    {
+        auto covering_or_the_same_it = std::find_if(all_parts_to_read.begin(), all_parts_to_read.end(),
+            [&part] (const Part & other) { return other.description.info.contains(part.info) ||  part.info.contains(other.description.info); });
+
+        auto the_same_it = std::find_if(all_parts_to_read.begin(), all_parts_to_read.end(),
+            [&part] (const Part & other) { return other.description.info == part.info; });
+
+        /// We have the same part - add the info about presence on current replica to it
+        if (the_same_it != all_parts_to_read.end())
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:378]: same comment as above for the order of checks

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 38]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
+
+                current_mark_size += global_part_it->description.ranges.back().getNumberOfMarks();
+                part.ranges.emplace_front(global_part_it->description.ranges.back());
+                global_part_it->description.ranges.pop_back();
+            }
+        }
 
-            LOG_TRACE(log, "Request accepted in {} ns: {}", watch.elapsed(), request_description);
-            return {.denied = false, .mark_ranges = std::move(request.mark_ranges)};
+        if (mode == CoordinationMode::WithOrder)
```
Comment (antonio2368) [inline src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:455]:
```suggestion
        else if constexpr (mode == CoordinationMode::WithOrder)
```

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 39]
```diff
@@ -4565,11 +4568,39 @@ void StorageReplicatedMergeTree::read(
         return;
     }
 
-    if (auto plan = reader.read(
-        column_names, storage_snapshot, query_info, local_context,
-        max_block_size, num_streams, processed_stage, nullptr, enable_parallel_reading))
+    const auto & settings = local_context->getSettingsRef();
+    bool parallel_replicas = settings.max_parallel_replicas > 1 && settings.allow_experimental_parallel_reading_from_replicas && !settings.use_hedged_requests && !local_context->getClientInfo().collaborate_with_initiator;
```
Comment (antonio2368) [inline src/Storages/StorageReplicatedMergeTree.cpp:4572]: Context::canUseParallelReplicas()

**Review by antonio2368 — COMMENTED** [review]
I have some questions about different situations and if they were tested:

Is a local replica requirement? What if this is used without local replica?
How does it behave if `max_parallel_replicas` is larger than number of replicas? Same for less than number of replicas.

File: src/QueryPipeline/QueryPipelineBuilder.cpp (hunk 21 above)
Comment (nikitamikhaylov) [reply src/QueryPipeline/QueryPipelineBuilder.cpp:635]: This is not necessary as I understand. After this check we are sure that they are both not empty, because otherwise...

**Comment by nikitamikhaylov** [comment]
Local replica is required, because with its help we understand how we want to read - InOrder, ReverseOrder or with Pool.
If the number of requested replicas (let it be N) is less than available then we will use first N replicas to execute a query. Possible it would be better to use a random ones. If this N is bigger than we have available - we will just use the maximum available number (honestly, there was a bug there which I fixed. Thanks for pointing it out!)

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 40]
```diff
@@ -173,30 +185,108 @@ ReadFromMergeTree::ReadFromMergeTree(
...
+        /// Set the approximate number of rows for the first source only
+        /// In case of parallel processing on replicas do not set approximate rows at all.
+        /// Because the value will be identical on every replicas and will be accounted
+        /// multiple times (settings.max_parallel_replicas times more)
+        if (i == 0 && !client_info.collaborate_with_initiator)
+            source->addTotalRowsApprox(total_rows);
+
+        pipes.emplace_back(std::move(source));
+
+        if (is_parallel_reading_from_replicas && context->getClientInfo().interface == ClientInfo::Interface::LOCAL)
```
[the remark this answers is not in the document]
Comment (nikitamikhaylov) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp:249]: Yes, this seems to be excess and we don't need it.

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 41]
```diff
@@ -173,30 +185,108 @@ ReadFromMergeTree::ReadFromMergeTree(
...
+
+        auto source = std::make_shared<MergeTreeSource>(std::move(algorithm));
+
+        /// Set the approximate number of rows for the first source only
+        /// In case of parallel processing on replicas do not set approximate rows at all.
+        /// Because the value will be identical on every replicas and will be accounted
+        /// multiple times (settings.max_parallel_replicas times more)
+        if (i == 0 && !client_info.collaborate_with_initiator)
+            source->addTotalRowsApprox(total_rows);
+
```
[the remark this answers is not in the document]
Comment (nikitamikhaylov) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp:246]: Oops, this part is not needed in `readFromPool` method - actually it was added in previous iteration.

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 42]
```diff
@@ -312,28 +317,33 @@ void ReadFromParallelRemoteReplicasStep::enforceAggregationInOrder()
 void ReadFromParallelRemoteReplicasStep::initializePipeline(QueryPipelineBuilder & pipeline, const BuildQueryPipelineSettings &)
 {
     Pipes pipes;
-
     const Settings & current_settings = context->getSettingsRef();
     auto timeouts = ConnectionTimeouts::getTCPTimeoutsWithFailover(current_settings);
 
-    for (size_t replica_num = 0; replica_num < shard.shard_info.getAllNodeCount(); ++replica_num)
+    size_t replica_num = 0;
+    while (pipes.size() != current_settings.max_parallel_replicas - 1)
```
[the remark this answers is not in the document]
Comment (nikitamikhaylov) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:324]: This is needed, because the value of the setting `max_parallel_replicas` could be less than the total number of replicas in a shard. And we have to pick only remote replicas with remote addresses. This loop is a little bit difficult to read, yes...

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp [hunk 43]
```diff
@@ -27,115 +110,429 @@ class ParallelReplicasReadingCoordinator::Impl
...
 {
     return pimpl->handleRequest(std::move(request));
 }
 
-ParallelReplicasReadingCoordinator::ParallelReplicasReadingCoordinator()
+void ParallelReplicasReadingCoordinator::setMode(CoordinationMode mode_)
 {
-    pimpl = std::make_unique<ParallelReplicasReadingCoordinator::Impl>();
+    mode = mode_;
+    initialize();
```
[the remark this answers is not in the document]
Comment (nikitamikhaylov) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:510]: I think this is a good idea!

File: src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp (hunk 36 above)
Comment (nikitamikhaylov) [reply src/Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp:276]: We don't really cap, here we just check whether we can add the whole range `[a, b)` to the set or do we have to take a bite and split this range. For example for the full scan we will have just one big range for the whole part and of course we want to parallelise it.

File: src/Storages/MergeTree/MergeTreeParallelReplicasSelectProcessor.h (hunk 15 above)
Comment (nikitamikhaylov) [reply src/Storages/MergeTree/MergeTreeParallelReplicasSelectProcessor.h]: Deleted it.

**Comment by nikitamikhaylov** [comment]
ClangTidy failure with Keeper Changelog - known.

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 44]
```diff
@@ -448,6 +448,16 @@ InterpreterSelectQuery::InterpreterSelectQuery(
         }
     }
 
+    /// FIXME: Memory bound aggregation may cause another reading algorithm to be used on remote replicas
+    if (settings.allow_experimental_parallel_reading_from_replicas && settings.enable_memory_bound_merging_of_aggregation_results)
+        context->setSetting("enable_memory_bound_merging_of_aggregation_results", false);
```
Comment (antonio2368) [inline src/Interpreters/InterpreterSelectQuery.cpp:453]: shouldn't the same comment apply as for the Joins? you're disabling memory_bound_merging for all queries if `allow_experimental_parallel_reading_from_replicas` is enabled.

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 45]
```diff
@@ -173,30 +183,107 @@ ReadFromMergeTree::ReadFromMergeTree(
...
+            data, storage_snapshot, use_uncompressed_cache,
+            prewhere_info, actions_settings, reader_settings, virt_column_names);
+
+        auto source = std::make_shared<MergeTreeSource>(std::move(algorithm));
+
+        /// Set the approximate number of rows for the first source only
+        /// In case of parallel processing on replicas do not set approximate rows at all.
+        /// Because the value will be identical on every replicas and will be accounted
+        /// multiple times (settings.max_parallel_replicas times more)
+        if (i == 0 && !client_info.collaborate_with_initiator)
```
Comment (antonio2368) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:240]:
```suggestion
        if (i == 0 && !client_info.collaborate_with_initiator)
```
again do you need the check ` !client_info.collaborate_with_initiator`?
The method is called `readFromPoolParallelReplicas` so can you end up here if parallel replicas are not used?

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 46]
```diff
@@ -534,7 +602,41 @@ Pipe ReadFromMergeTree::spreadMarkRangesAmongStreamsWithOrder(
...
+        {
+            .all_callback = all_ranges_callback.value(),
+            .callback = read_task_callback.value(),
+            .count_participating_replicas = client_info.count_participating_replicas,
+            .number_of_current_replica = client_info.number_of_current_replica,
+            .colums_to_read = column_names
+        };
+
+        /// We have a special logic for local replica. It has to read less data, because in some cases it should
+        /// merge states of aggregate functions or do some other important stuff other than reading from Disk.
```
Comment (antonio2368) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:627]: Just curious, did you observe improvement in all cases when local replica has lower mark count?

File: src/QueryPipeline/RemoteQueryExecutor.cpp [hunk 47]
```diff
@@ -1,3 +1,4 @@
+#include <variant>
```
Comment (antonio2368) [inline src/QueryPipeline/RemoteQueryExecutor.cpp:1]:
```suggestion
```
I assume

File: src/QueryPipeline/RemoteQueryExecutor.h [hunk 48]
```diff
@@ -94,12 +94,60 @@ class RemoteQueryExecutor
     /// Query is resent to a replica, the query itself can be modified.
     std::atomic<bool> resent_query { false };
 
+    struct ReadResult
+    {
+      enum class Type
```
Comment (antonio2368) [inline src/QueryPipeline/RemoteQueryExecutor.h:99]:
```suggestion
      enum class Type : uint8_t
```

File: src/QueryPipeline/RemoteQueryExecutor.h [hunk 49]
```diff
@@ -94,12 +94,60 @@ class RemoteQueryExecutor
...
+      int getFileDescriptor() const
+      {
+        chassert(type == Type::FileDescriptor);
+        return fd;
+      }
+
+      Type type;
+      Block block;
+      int fd{-1};
+    };
```
Comment (antonio2368) [inline src/QueryPipeline/RemoteQueryExecutor.h:141]: 2 space indent is used here for some reason

**Review by antonio2368 — APPROVED** [review]

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp (hunk 45 above)
Comment (nikitamikhaylov) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp:240]: It means that we are reading with parallel replicas and we are on initiator node (local one). We need this to report total rows only one instead of N times.

Comment (antonio2368) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp:240]: Got confused by the comment then (/// In case of **parallel processing on replicas** do not set approximate rows at all.)

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp (hunk 46 above)
Comment (nikitamikhaylov) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp:627]: This is what need to be done while I will test it more. I guess there will be some improvement, because local replica has to both read and constantly answer to incoming requests.

File: src/Interpreters/InterpreterSelectQuery.cpp (hunk 44 above)
Comment (nikitamikhaylov) [reply src/Interpreters/InterpreterSelectQuery.cpp:453]: Discussed in DM, this is a temporary solution, because I faced with a bug which will be resolved with https://github.com/ClickHouse/ClickHouse/pull/45892

File: src/QueryPipeline/RemoteQueryExecutor.h (hunk 49 above)
Comment (nikitamikhaylov) [reply src/QueryPipeline/RemoteQueryExecutor.h]: Now it should be better
