### PR TITLE
Fix IN clause coercion for BFloat16

### LINKED ISSUE #78754: IN clause fails for BFloat16 due to type mismatch with array
### Company or project name

_No response_

### Describe what's wrong

`IN` clause fails with `toBFloat16(...)` while working fine with `toFloat64(...)` and `toFloat32(...)` for the same input values.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Run the following queries:

```
SELECT toFloat64(1) IN [1, 2, 3];   -- returns 1
SELECT toFloat32(1) IN [1, 2, 3];   -- returns 1
SELECT toBFloat16(1) IN [1, 2, 3];  -- throws
```

[Link](https://fiddle.clickhouse.com/395a083d-477a-4af7-acf7-3c4d5aea95d8) to reproduce. 

### Expected behavior

All three expressions should return 1. Type coercion should match `toBFloat16(1)` with the array [1, 2, 3] just like it does for `Float32` and `Float64`.

### Error message and/or stacktrace

```
Received exception from server (version 25.3.2):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Type mismatch in IN or VALUES section. Expected: BFloat16. Got: UInt64. (TYPE_MISMATCH)
(query: SELECT toBFloat16(1) IN [1, 2, 3];)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rienath**
Using `BFloat16` in an `IN` clause (e.g., `SELECT toBFloat16(1) IN [1, 2, 3];`) now returns the expected result instead of a type mismatch error, aligning its behaviour with that of `Float32` and `Float64`. Extends tests to catch any regressions.

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `IN` clause type coercion for `BFloat16` (i.e. `SELECT toBFloat16(1) IN [1, 2, 3];` now returns `1`). Closes #78754.

### Documentation entry for user-facing changes
- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: base/base/BFloat16.h [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #include <bit>
 #include <base/types.h>
 #include <base/defines.h>
+#include <fmt/format.h>
```
Comment (Algunenano) [inline base/base/BFloat16.h:6]: Please do not include fmt in such a common header. Create a different header and use that were necessary instead

Comment (rienath) [reply base/base/BFloat16.h]: @Michicosun Thanks for the suggestion. Done

**Review by Michicosun — APPROVED** [review]
