### PR TITLE
Analyzer: Fix crash on window resolve

### LINKED ISSUE #53718: ClickHouse Server v23.7.4.5 crashed by a SELECT statement with allow_experimental_analyzer enabled ("SELECT 1 WINDOW ...")
**Describe the bug**
ClickHouse Server v23.7.4.5 crashed by a SELECT statement with allow_experimental_analyzer enabled.
It was found by an in-development fuzzer of WINGFUZZ.

**How to reproduce**
The SQL statement to reproduce:
```sql
SELECT 1 WINDOW x AS ( PARTITION BY x )  SETTINGS allow_experimental_analyzer = 1 ;
```
It can be reproduced on the official docker image. (`clickhouse/clickhouse-server:head` (version 23.8.1.2413) and `clickhouse/clickhouse-server:latest` (version 23.7.4.5)).

The log traced by ClickHouse Server:
```
SELECT 1
WINDOW x AS (PARTITION BY x)
SETTINGS allow_experimental_analyzer = 1

Query id: 840148ee-451f-4379-b5e3-ad4ce8678ed4

[8af69c367457] 2023.08.23 07:54:07.366367 [ 347 ] <Fatal> BaseDaemon: ########################################
[8af69c367457] 2023.08.23 07:54:07.366402 [ 347 ] <Fatal> BaseDaemon: (version 23.8.1.2413 (official build), build id: 4DCA66DD83B2161C82851B4655CD14334A08D535, git hash: 926533306c5969b77571e66163a6930cfce1cf86) (from thread 48) (query_id: 840148ee-451f-4379-b5e3-ad4ce8678ed4) (query: SELECT 1 WINDOW x AS ( PARTITION BY x )  SETTINGS allow_experimental_analyzer = 1 ;) Received signal Segmentation fault (11)
[8af69c367457] 2023.08.23 07:54:07.366419 [ 347 ] <Fatal> BaseDaemon: Address: 0x7fffd2030fa8. Access: write. Attempted access has violated the permissions assigned to the memory area.
[8af69c367457] 2023.08.23 07:54:07.366430 [ 347 ] <Fatal> BaseDaemon: Stack trace: 0x0000000011cadf40 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58 0x0000000011cadf58
[8af69c367457] 2023.08.23 07:54:07.366503 [ 347 ] <Fatal> BaseDaemon: 2. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf40 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366532 [ 347 ] <Fatal> BaseDaemon: 3. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366564 [ 347 ] <Fatal> BaseDaemon: 4. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366596 [ 347 ] <Fatal> BaseDaemon: 5. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366628 [ 347 ] <Fatal> BaseDaemon: 6. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366655 [ 347 ] <Fatal> BaseDaemon: 7. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366686 [ 347 ] <Fatal> BaseDaemon: 8. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366709 [ 347 ] <Fatal> BaseDaemon: 9. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366739 [ 347 ] <Fatal> BaseDaemon: 10. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366775 [ 347 ] <Fatal> BaseDaemon: 11. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366820 [ 347 ] <Fatal> BaseDaemon: 12. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366851 [ 347 ] <Fatal> BaseDaemon: 13. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366874 [ 347 ] <Fatal> BaseDaemon: 14. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366900 [ 347 ] <Fatal> BaseDaemon: 15. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366927 [ 347 ] <Fatal> BaseDaemon: 16. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366955 [ 347 ] <Fatal> BaseDaemon: 17. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.366986 [ 347 ] <Fatal> BaseDaemon: 18. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367015 [ 347 ] <Fatal> BaseDaemon: 19. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367047 [ 347 ] <Fatal> BaseDaemon: 20. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367075 [ 347 ] <Fatal> BaseDaemon: 21. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367104 [ 347 ] <Fatal> BaseDaemon: 22. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367137 [ 347 ] <Fatal> BaseDaemon: 23. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367158 [ 347 ] <Fatal> BaseDaemon: 24. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367187 [ 347 ] <Fatal> BaseDaemon: 25. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367228 [ 347 ] <Fatal> BaseDaemon: 26. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367254 [ 347 ] <Fatal> BaseDaemon: 27. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367282 [ 347 ] <Fatal> BaseDaemon: 28. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367304 [ 347 ] <Fatal> BaseDaemon: 29. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367336 [ 347 ] <Fatal> BaseDaemon: 30. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367363 [ 347 ] <Fatal> BaseDaemon: 31. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367389 [ 347 ] <Fatal> BaseDaemon: 32. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367428 [ 347 ] <Fatal> BaseDaemon: 33. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367453 [ 347 ] <Fatal> BaseDaemon: 34. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367480 [ 347 ] <Fatal> BaseDaemon: 35. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367510 [ 347 ] <Fatal> BaseDaemon: 36. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367543 [ 347 ] <Fatal> BaseDaemon: 37. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367570 [ 347 ] <Fatal> BaseDaemon: 38. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367591 [ 347 ] <Fatal> BaseDaemon: 39. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367628 [ 347 ] <Fatal> BaseDaemon: 40. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367661 [ 347 ] <Fatal> BaseDaemon: 41. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367693 [ 347 ] <Fatal> BaseDaemon: 42. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367721 [ 347 ] <Fatal> BaseDaemon: 43. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.367742 [ 347 ] <Fatal> BaseDaemon: 44. DB::InDepthQueryTreeVisitor<DB::(anonymous namespace)::CollectWindowFunctionNodeVisitor, true>::visit(std::shared_ptr<DB::IQueryTreeNode> const&) (.llvm.17465951882029437719) @ 0x0000000011cadf58 in /usr/bin/clickhouse
[8af69c367457] 2023.08.23 07:54:07.519317 [ 347 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: F37F4F1F1F05354DFEECD70FAB61DC73)
[8af69c367457] 2023.08.23 07:54:07.519650 [ 347 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[8af69c367457] 2023.08.23 07:54:07.519774 [ 347 ] <Fatal> BaseDaemon: Changed settings: allow_experimental_analyzer = true
```

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix crash if WINDOW definition contains window name. Fix #53718.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 7cc4b8b1ae2caf1af82eab3206e5ce97e8ac71c7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56055/7cc4b8b1ae2caf1af82eab3206e5ce97e8ac71c7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6657477868">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56055/7cc4b8b1ae2caf1af82eab3206e5ce97e8ac71c7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -970,6 +970,10 @@ class QueryExpressionsAliasVisitor : public InDepthQueryTreeVisitor<QueryExpress
         if (!node->hasAlias())
             return;
 
+        // We don't should not resolve expressions to WindowNode
```
Comment (nikitamikhaylov) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:973]:
```suggestion
        // We should not resolve expressions to WindowNode
```
