### PR TITLE
Fix backquoting in dictionary ddl

### LINKED ISSUE #9619: CREATE DICTIONARY source odbc where clause bad escape character
I create new odbc dictionary using DDL:

```
CREATE DICTIONARY clickhouse_rock  (
    col1 UInt32, 
    col2 UInt16, 
    col3 UInt32
  ) PRIMARY KEY col1
SOURCE(ODBC(HOST localhost DB 'clickhouse' TABLE 'test' CONNECTION_STRING 'DSN=postgresql' where 'date_column = ''2016-01-01''::date'))
LAYOUT(COMPLEX_KEY_HASHED())
LIFETIME(MIN 30000 MAX 36000)
```
Then I try to refresh it 

`SYSTEM RELOAD DICTIONARY clickhouse_rock;`

and got:

```
Received exception from server (version 20.1.3):
Code: 86. DB::Exception: Received from localhost:9000. DB::Exception: Received error from remote server /?connection_string=DSN%3Dclickhouse_pg&columns=columns%20format%20version%3A%201%0A3%20columns%3A%0A%60apnr%60%20UInt32%0A%60ibnr%60%20UInt16%0A%60inwr%60%20UInt32%0A&max_block_size=8192. HTTP status code: 500 Internal Server Error, body: ▒
                                               Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = ODBC handle exception: Failed to get number of columns: Connection:Not applicable
Server:clickhouse_pg
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = HY000
Native Error Code = 1
ERROR:  syntax error at or near "\" at character 106;
No query has been executed with that handle

0. 0x3d1eacc ?  in /usr/bin/clickhouse-odbc-bridge
1. 0x3e55bb9 ?  in /usr/bin/clickhouse-odbc-bridge
2. 0x3dcb6f9 ?  in /usr/bin/clickhouse-odbc-bridge
3. 0x3de19c0 ?  in /usr/bin/clickhouse-odbc-bridge
4. 0x72b56a ?  in /usr/bin/clickhouse-odbc-bridge
5. 0x3de7d37 ?  in /usr/bin/clickhouse-odbc-bridge
6. 0x3de82d7 ?  in /usr/bin/clickhouse-odbc-bridge
7. 0x3eb5cc3 ?  in /usr/bin/clickhouse-odbc-bridge
8. 0x3eb1fbf ?  in /usr/bin/clickhouse-odbc-bridge
9. 0x3eb08d7 ?  in /usr/bin/clickhouse-odbc-bridge
10. 0x7feb6f ?  in /usr/bin/clickhouse-odbc-bridge
11. 0x7f0e87 ?  in /usr/bin/clickhouse-odbc-bridge
12. 0x310189c ?  in /usr/bin/clickhouse-odbc-bridge
13. 0x31038b7 ?  in /usr/bin/clickhouse-odbc-bridge
14. 0x30fe71d ?  in /usr/bin/clickhouse-odbc-bridge
15. 0x3d871af ?  in /usr/bin/clickhouse-odbc-bridge
16. 0x3d83d38 ?  in /usr/bin/clickhouse-odbc-bridge
17. 0x3d855d9 ?  in /usr/bin/clickhouse-odbc-bridge
18. 0x7dd5 start_thread  in /usr/lib64/libpthread-2.17.so
19. 0xfdf6d __clone  in /usr/lib64/libc-2.17.so
 (version 20.1.3.7 (official build)).

0 rows in set. Elapsed: 0.096 sec.

```
In PostgreSQL logs the statement is:

```
< 2020-03-12 09:54:58 CET 5e69f806.79c0 realyota [unknown] 127.0.0.1 31168 >ERROR:  syntax error at or near "\" at character 106
< 2020-03-12 09:54:58 CET 5e69f806.79c0 realyota [unknown] 127.0.0.1 31168 >STATEMENT:  SELECT "col1", "col2", "col3" FROM "clickhouse"."test" WHERE date_column = \'2016-01-01\'::date;
```

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug in backquoting in external dictionaries DDL. Fixes #9619.

### CODE REVIEW

File: dbms/src/Dictionaries/getDictionaryConfigurationFromAST.cpp [hunk 1]
```diff
@@ -34,8 +35,12 @@ using NamesToTypeNames = std::unordered_map<std::string, std::string>;
 String getUnescapedFieldString(const Field & field)
 {
     String string = applyVisitor(FieldVisitorToString(), field);
+
     if (!string.empty() && string.front() == '\'' && string.back() == '\'')
-        return string.substr(1, string.size() - 2);
+        string = string.substr(1, string.size() - 2);
+
+    /// Backqouting will be performed on dictionary providers side
+    boost::replace_all(string, "\\'", "'");
```
Comment (alexey-milovidov) [inline dbms/src/Dictionaries/getDictionaryConfigurationFromAST.cpp]: It doesn't look like unescape function, because it does not unescapes backslashes.

Comment (alesapin) [reply dbms/src/Dictionaries/getDictionaryConfigurationFromAST.cpp]: > I struggle to prove that this code is correct.
> 
> What kind of escaping do you want to implement? Maybe you can use the function `readStringEscaped` for this purpose?

I'm trying to read part of dictionary Source expression from Field. There may be simple strings like ip-address `'127.0.0.1'` or parts of SQL expressions, like `'WHERE x = \'123\''`. Seems like I need `readQuotedString`.

Comment (alexey-milovidov) [reply dbms/src/Dictionaries/getDictionaryConfigurationFromAST.cpp]: Sorry, but
```
    String string = applyVisitor(FieldVisitorToString(), field);
    if (string.front() == '\'')
    {
        String result;
        ReadBufferFromString buf(string);
        readQuotedString(result, buf);
        return result;
    }
    return string;
```

it looks bogus. You converting field to string then converting it back.
The value of field already contains unquoted string if it's a string literal.
Just check the type and you're done.

**Review by alexey-milovidov — APPROVED** [review]
