### PR TITLE
Fix `sumCountOrDefault` aggregate function with one or more `Nullable` argument not being able to read older serialized states after introduction of `Nullable(Tuple)`

### LINKED ISSUE #100882: sumCountOrDefault/sumCountOrNull with Nullable argument: backward-incompatible serialization format change after Nullable(Tuple) introduction
### Summary

`sumCountOrDefault(Nullable(UInt8))` and `sumCountOrNull(Nullable(UInt8))` produce an 11-byte state (with a leading Null flag byte) instead of the pre-`Nullable(Tuple)` 10-byte state. Old 10-byte states stored in `AggregatingMergeTree` tables or materialized views fail to deserialize with `ATTEMPT_TO_READ_AFTER_EOF` after upgrade.

PR #100826 fixed the same issue for `sumCountIf`, `sumCountDistinct`, and `sumCountDistinctIf`, but missed the `OrDefault`/`OrNull` combinators.

### Steps to Reproduce

```sql
-- Show state size difference: Nullable gets an extra leading byte
SELECT 'non_nullable' AS type, length(hex(sumCountOrDefaultState(x)))/2 AS bytes, hex(sumCountOrDefaultState(x)) AS state
FROM (SELECT number::UInt8 AS x FROM numbers(5))
UNION ALL
SELECT 'nullable', length(hex(sumCountOrDefaultState(x)))/2, hex(sumCountOrDefaultState(x))
FROM (SELECT number::Nullable(UInt8) AS x FROM numbers(5));

-- Old 10-byte state (pre-Nullable(Tuple) format) fails to deserialize
SELECT finalizeAggregation(CAST(unhex('0A000000000000000501'), 'AggregateFunction(sumCountOrDefault, Nullable(UInt8))'));
```

### Actual Result

```
non_nullable  10  0A000000000000000501
nullable      11  010A000000000000000501   ← extra leading 01 byte

Code: 32. DB::Exception: Attempt to read after eof. (ATTEMPT_TO_READ_AFTER_EOF)
```

### Expected Result

```
non_nullable  10  0A000000000000000501
nullable      10  0A000000000000000501   ← same format

(10,5)   ← old state deserializes correctly
```

### Root Cause

For `sumCountOrDefault(Nullable(UInt8))`, the Null combinator wraps the entire `OrFill(sumCount)` chain:

```
Null combinator         ← getOwnNullAdapter missing here
  └── OrFill combinator
        └── sumCount
```

`AggregateFunctionOrFill` does not implement `getOwnNullAdapter`, so the Null combinator falls back to its default `<true, true>` adapter, which prepends a 1-byte flag to the state.

PR #100826 fixed this for `AggregateFunctionDistinct` by adding `getOwnNullAdapter` that checks for `sumCount` as the nested function and returns `AggregateFunctionNullUnary<false, false>`. The same fix is needed for `AggregateFunctionOrFill`.

### Impact

Any `AggregatingMergeTree` table or materialized view storing `AggregateFunction(sumCountOrDefault, Nullable(UInt8))` states written before `Nullable(Tuple)` was introduced will fail to read or merge those states after upgrade.

### PR DESCRIPTION
**Pull request by nihalzp**
### `OrDefault` combinator:

Only single-argument aggregate function, `sumCount` is affected:

```sql
SELECT finalizeAggregation(CAST(unhex('0A000000000000000501'), 
'AggregateFunction(sumCountOrDefault, Nullable(UInt8))'));  -- throws error
```

`OrNull` is not affected because `sumCountOrNull` was not even possible before introduction of `Nullable(Tuple)` so no backward compatibility to preserve.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `sumCountOrDefault` aggregate function with one or more `Nullable` argument not being able to read older serialized states after introduction of `Nullable(Tuple)`. Closes https://github.com/ClickHouse/ClickHouse/issues/100882.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.363`
- Backported to: `26.3.3.6`, `26.2.7.5`, `26.1.8.3`

### CODE REVIEW

**Review by azat — APPROVED** [review]

File: src/AggregateFunctions/Combinators/AggregateFunctionOrFill.h [hunk 1]
```diff
@@ -324,6 +325,32 @@ class AggregateFunctionOrFill final : public IAggregateFunctionHelper<AggregateF
...
+        const Array & params,
+        const AggregateFunctionProperties & /*properties*/) const override
+    {
+        if constexpr (!UseNull) /// OrDefault only
+        {
+            if (nested_function->getName() == "sumCount")
+                return std::make_shared<AggregateFunctionNullUnary<false, false>>(nested_function_, arguments, params);
+        }
+        return nullptr;
+    }
```
Comment (azat) [inline src/AggregateFunctions/Combinators/AggregateFunctionOrFill.h:353]: BTW WDYT about putting all this special treatmeants of `sumCount` into the null combinator instead?

Comment (nihalzp) [reply src/AggregateFunctions/Combinators/AggregateFunctionOrFill.h:353]: Yes, it can be done in practice. However, I am not a big fan of it. Doing so would invert the current design: `getOwnNullAdapter` exists precisely to let each aggregate function define its own null handling. Moving this logic into the null combinator would indirectly duplicate that responsibility while increasing coupling. Additionally, as the null combinator sees the wrapped combinator (e.g., `sumCountDistinctIf`) as its `nested_function`, so it would need to unwrap the combinator chain to discover `sumCount` inside and doing so could be tricky and bug-prone. Even though the current approach has a little duplication, it is easier to reason about.

Comment (azat) [reply src/AggregateFunctions/Combinators/AggregateFunctionOrFill.h:353]: Make sense (I thought about this only to concentrate all this fixes in one place, but I'm fine with current approach)
