### PR TITLE
Fix uncaught exception in InterserverIOHTTPHandler

### LINKED ISSUE #22046: Uncaught exception in WriteBufferFromHTTPServerResponse.cpp
**How to reproduce**
https://clickhouse-test-reports.s3.yandex.net/0/78c56b891383288cf3a893139e796fc87476412e/stress_test_(debug).html

**Error message and/or stacktrace**
```
2021.03.19 18:11:31.553554 [ 276 ] {} <Fatal> BaseDaemon: (version 21.4.1.6293 (official build), build id: 859E400E1C65C4702FE491420741DD8B58190002) (from thread 17469) Terminate called for uncaught exception:
2021.03.19 18:11:31.698961 [ 80145 ] {} <Fatal> BaseDaemon: ########################################
2021.03.19 18:11:31.699903 [ 80145 ] {} <Fatal> BaseDaemon: (version 21.4.1.6293 (official build), build id: 859E400E1C65C4702FE491420741DD8B58190002) (from thread 17469) (no query) Received signal Aborted (6)
2021.03.19 18:11:31.712523 [ 80145 ] {} <Fatal> BaseDaemon: 
2021.03.19 18:11:31.712778 [ 80145 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f2b3b19e18b 0x7f2b3b17d859 0x11bf0c24 0x21e9b462 0x21e9b3a2 0x119440cf 0x1be77038 0x1bddd7c9 0x1bddd79d 0x1bddd76d 0x1bddd525 0x119490ed 0x1194908f 0x1bdd75fc 0x1bdf6bd5 0x1bdf653f 0x1be6d689 0x1f908b4c 0x1f909350 0x1fa45af3 0x1fa4297d 0x1fa41808 0x7f2b3b353609 0x7f2b3b27a293
2021.03.19 18:11:31.713591 [ 80145 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.03.19 18:11:31.713825 [ 80145 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.03.19 18:11:32.396951 [ 80145 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:435: terminate_handler() @ 0x11bf0c24 in /usr/bin/clickhouse
2021.03.19 18:11:32.511904 [ 80145 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_handlers.cpp:59: std::__terminate(void (*)()) @ 0x21e9b462 in /usr/bin/clickhouse
2021.03.19 18:11:32.614075 [ 80145 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_handlers.cpp:89: std::terminate() @ 0x21e9b3a2 in /usr/bin/clickhouse
2021.03.19 18:11:43.686790 [ 80145 ] {} <Fatal> BaseDaemon: 9. ? @ 0x119440cf in /usr/bin/clickhouse
2021.03.19 18:11:43.831215 [ 80145 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:201: ? @ 0x1be77038 in /usr/bin/clickhouse
2021.03.19 18:11:44.743193 [ 80145 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:892: std::__1::allocator<DB::WriteBufferFromHTTPServerResponse>::destroy(DB::WriteBufferFromHTTPServerResponse*) @ 0x1bddd7c9 in /usr/bin/clickhouse
2021.03.19 18:11:45.283905 [ 80145 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:541: void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferFromHTTPServerResponse> >::__destroy<DB::WriteBufferFromHTTPServerResponse>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::WriteBufferFromHTTPServerResponse>&, DB::WriteBufferFromHTTPServerResponse*) @ 0x1bddd79d in /usr/bin/clickhouse
2021.03.19 18:11:45.805233 [ 80145 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<DB::WriteBufferFromHTTPServerResponse> >::destroy<DB::WriteBufferFromHTTPServerResponse>(std::__1::allocator<DB::WriteBufferFromHTTPServerResponse>&, DB::WriteBufferFromHTTPServerResponse*) @ 0x1bddd76d in /usr/bin/clickhouse
2021.03.19 18:11:46.351371 [ 80145 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2611: std::__1::__shared_ptr_emplace<DB::WriteBufferFromHTTPServerResponse, std::__1::allocator<DB::WriteBufferFromHTTPServerResponse> >::__on_zero_shared() @ 0x1bddd525 in /usr/bin/clickhouse
2021.03.19 18:11:46.579263 [ 80145 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2476: std::__1::__shared_count::__release_shared() @ 0x119490ed in /usr/bin/clickhouse
2021.03.19 18:11:46.790912 [ 80145 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2517: std::__1::__shared_weak_count::__release_shared() @ 0x1194908f in /usr/bin/clickhouse
2021.03.19 18:11:47.277990 [ 80145 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3213: std::__1::shared_ptr<DB::WriteBufferFromHTTPServerResponse>::~shared_ptr() @ 0x1bdd75fc in /usr/bin/clickhouse
2021.03.19 18:11:47.649213 [ 80145 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../src/Server/InterserverIOHTTPHandler.h:34: DB::InterserverIOHTTPHandler::Output::~Output() @ 0x1bdf6bd5 in /usr/bin/clickhouse
2021.03.19 18:11:47.921556 [ 80145 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Server/InterserverIOHTTPHandler.cpp:154: DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1bdf653f in /usr/bin/clickhouse
2021.03.19 18:11:48.167299 [ 80145 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Server/HTTP/HTTPServerConnection.cpp:48: DB::HTTPServerConnection::run() @ 0x1be6d689 in /usr/bin/clickhouse
2021.03.19 18:11:48.262424 [ 80145 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x1f908b4c in /usr/bin/clickhouse
2021.03.19 18:11:48.416253 [ 80145 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:113: Poco::Net::TCPServerDispatcher::run() @ 0x1f909350 in /usr/bin/clickhouse
2021.03.19 18:11:48.586800 [ 80145 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x1fa45af3 in /usr/bin/clickhouse
2021.03.19 18:11:48.737683 [ 80145 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x1fa4297d in /usr/bin/clickhouse
2021.03.19 18:11:49.178522 [ 80145 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x1fa41808 in /usr/bin/clickhouse
2021.03.19 18:11:49.178785 [ 80145 ] {} <Fatal> BaseDaemon: 26. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.03.19 18:11:49.178975 [ 80145 ] {} <Fatal> BaseDaemon: 27. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.03.19 18:11:50.333544 [ 80145 ] {} <Fatal> BaseDaemon: Checksum of the binary: 90D89256F0C44AD22CDAF28455F993EC, integrity check passed.
2021.03.19 18:11:54.457906 [ 274 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### LINKED ISSUE #22067: Uncaught DB::Exception: Cannot write to ostream
**Describe the bug**
We have clickhouse-server going down now and then when inserting large amounts of data via clickhouse-client with an uncaught exception: "Terminate called for uncaught exception:#012Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 7937". I see there are several PRs (#20464, #20981, #21305) trying to fix this kind of errors, but it looks like not all corner cases are handled. From the code, `finalize()` will just re-throw any nested exception and it will end up unhandled in the HTTP server.

**Does it reproduce on recent release?**
21.3.2.5

**How to reproduce**
* Which ClickHouse server version to use
21.3.2.5

**Expected behavior**
The error must not be fatal.

**Error message and/or stacktrace**
```
2021.03.24 03:46:09.707694 [ 23124 ] {} <Fatal> BaseDaemon: (version 21.3.2.5, build id: 293C622C5C9ED35A848F4B84070256EB217A812D) (from thread 64876) Terminate called for uncaught exception:#012Code: 24, e.displayText() = DB::Exception: Cannot write to ostream at offset 7937, Stack trace (when copying this message, always include the lines below):#012#0120. DB::WriteBufferFromOStream::nextImpl() @ 0x8a46fc0 in /usr/bin/clickhouse#0121. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0xfccb800 in /usr/bin/clickhouse#0122. DB::WriteBufferFromHTTPServerResponse::finalize() @ 0xfccbdf2 in /usr/bin/clickhouse#0123. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xfccc486 in /usr/bin/clickhouse#0124. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfc4c32a in /usr/bin/clickhouse#0125. DB::HTTPServerConnection::run() @ 0xfcc460f in /usr/bin/clickhouse#0126. Poco::Net::TCPServerConnection::start() @ 0x1236ec7f in /usr/bin/clickhouse#0127. Poco::Net::TCPServerDispatcher::run() @ 0x12370691 in /usr/bin/clickhouse#0128. Poco::PooledThread::run() @ 0x124a6db9 in /usr/bin/clickhouse#0129. Poco::ThreadImpl::runnableEntry(void*) @ 0x124a2c1a in /usr/bin/clickhouse#01210. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so#01211. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so#012 (version 21.3.2.5)
2021.03.24 03:46:09.726762 [ 71381 ] {} <Fatal> BaseDaemon: ########################################
2021.03.24 03:46:09.726927 [ 71381 ] {} <Fatal> BaseDaemon: (version 21.3.2.5, build id: 293C622C5C9ED35A848F4B84070256EB217A812D) (from thread 64876) (no query) Received signal Aborted (6)
2021.03.24 03:46:09.726944 [ 71381 ] {} <Fatal> BaseDaemon: 
2021.03.24 03:46:09.726965 [ 71381 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fd6225807bb 0x7fd62256b535 0x8b093b8 0x13eb9163 0x13eb910c 0x894cf5b 0xfccc5ed 0xfc4c32a 0xfcc460f 0x1236ec7f 0x12370691 0x124a6db9 0x124a2c1a 0x7fd622711fa3 0x7fd6226424cf
2021.03.24 03:46:09.727074 [ 71381 ] {} <Fatal> BaseDaemon: 1. raise @ 0x377bb in /usr/lib/x86_64-linux-gnu/libc-2.28.so
2021.03.24 03:46:09.727085 [ 71381 ] {} <Fatal> BaseDaemon: 2. abort @ 0x22535 in /usr/lib/x86_64-linux-gnu/libc-2.28.so
2021.03.24 03:46:09.727163 [ 71381 ] {} <Fatal> BaseDaemon: 3. ? @ 0x8b093b8 in /usr/bin/clickhouse
2021.03.24 03:46:09.727246 [ 71381 ] {} <Fatal> BaseDaemon: 4. ? @ 0x13eb9163 in ?
2021.03.24 03:46:09.727278 [ 71381 ] {} <Fatal> BaseDaemon: 5. std::terminate() @ 0x13eb910c in ?
2021.03.24 03:46:09.727358 [ 71381 ] {} <Fatal> BaseDaemon: 6. ? @ 0x894cf5b in /usr/bin/clickhouse
2021.03.24 03:46:09.727382 [ 71381 ] {} <Fatal> BaseDaemon: 7. DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0xfccc5ed in /usr/bin/clickhouse
2021.03.24 03:46:09.727406 [ 71381 ] {} <Fatal> BaseDaemon: 8. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfc4c32a in /usr/bin/clickhouse
2021.03.24 03:46:09.727432 [ 71381 ] {} <Fatal> BaseDaemon: 9. DB::HTTPServerConnection::run() @ 0xfcc460f in /usr/bin/clickhouse
2021.03.24 03:46:09.727448 [ 71381 ] {} <Fatal> BaseDaemon: 10. Poco::Net::TCPServerConnection::start() @ 0x1236ec7f in /usr/bin/clickhouse
2021.03.24 03:46:09.727457 [ 71381 ] {} <Fatal> BaseDaemon: 11. Poco::Net::TCPServerDispatcher::run() @ 0x12370691 in /usr/bin/clickhouse
2021.03.24 03:46:09.727469 [ 71381 ] {} <Fatal> BaseDaemon: 12. Poco::PooledThread::run() @ 0x124a6db9 in /usr/bin/clickhouse
2021.03.24 03:46:09.727479 [ 71381 ] {} <Fatal> BaseDaemon: 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x124a2c1a in /usr/bin/clickhouse
2021.03.24 03:46:09.727497 [ 71381 ] {} <Fatal> BaseDaemon: 14. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
2021.03.24 03:46:09.727508 [ 71381 ] {} <Fatal> BaseDaemon: 15. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
2021.03.24 03:46:09.840498 [ 71381 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: DCFE6F75B6E72B76D731FF6621C84A85. There is no information about the reference checksum.
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix uncaught exception in InterserverIOHTTPHandler

Fixes: #22046
Fixes: #22067

### CODE REVIEW

File: src/Server/InterserverIOHTTPHandler.cpp [hunk 1]
```diff
@@ -116,6 +117,7 @@ void InterserverIOHTTPHandler::handleRequest(HTTPServerRequest & request, HTTPSe
         if (auto [message, success] = checkAuthentication(request); success)
         {
             processQuery(request, response, used_output);
```
Comment (alexey-milovidov) [inline src/Server/InterserverIOHTTPHandler.cpp:119]: What if exception will be thrown from this line?
Then finalize will not be called.

Comment (azat) [reply src/Server/InterserverIOHTTPHandler.cpp:119]: It will, there is a catch section

https://github.com/ClickHouse/ClickHouse/blob/40a99b7431e49aba57a30c1b73a200776fba3cc0/src/Server/InterserverIOHTTPHandler.cpp#L114-L153

**Comment by alexey-milovidov** [comment]
> test_materialize_mysql_database

Bad test, @BohuTANG @zhang2014
