### PR TITLE
Fix crash with enabled `optimize_functions_to_subcolumns`

### LINKED ISSUE #35505: The fuzzer error
(you don't have to strictly follow this form)

**Describe the bug**
A link to the report: https://s3.amazonaws.com/clickhouse-test-reports/35466/d81c58b5d9be45ac69c3859b5cbe97080711f6d9/fuzzer_astfuzzerubsan,actions//report.html
The commit: https://github.com/ClickHouse/ClickHouse/commit/d81c58b5d9be45ac69c3859b5cbe97080711f6d9

### PR DESCRIPTION
**Pull request by CurtizJ**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #35505.

### CODE REVIEW

File: src/Interpreters/TreeOptimizer.cpp [hunk 1]
```diff
@@ -740,8 +743,8 @@ void TreeOptimizer::apply(ASTPtr & query, TreeRewriterResult & result,
     if (!select_query)
         throw Exception("Select analyze for not select asts.", ErrorCodes::LOGICAL_ERROR);
 
-    if (settings.optimize_functions_to_subcolumns && result.storage_snapshot && result.storage->supportsSubcolumns())
-        optimizeFunctionsToSubcolumns(query, result.storage_snapshot->metadata);
+    if (settings.optimize_functions_to_subcolumns)
```
Comment (kitaisreal) [inline src/Interpreters/TreeOptimizer.cpp:746]: Why `storage_snapshot` is not null, but `storage` is null ? In other places we assume that they both not null.

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Interpreters/TreeOptimizer.cpp (hunk 1 above)
Comment (CurtizJ) [reply src/Interpreters/TreeOptimizer.cpp]: You are right. I found the root cause.

**Review by kitaisreal — APPROVED** [review]
