### PR TITLE
Prevent a bug in AWS S3

### LINKED ISSUE #47679: SIGSEGV while uploading to S3 for part > INT_MAX
Reproducer:

```sql
INSERT INTO FUNCTION s3('https://test.s3.us-east-1.amazonaws.com/clickhouse/test.csv', '', '', 'TSV')
SETTINGS s3_truncate_on_insert = 1, s3_max_single_part_upload_size = '10Gi'
SELECT repeat('a', 1024)
FROM numbers((pow(2, 30) * 5) / 1024)
SETTINGS s3_truncate_on_insert = 1, s3_max_single_part_upload_size = '10Gi'
```

Note, that usually it is not a problem since multi part upload is used, but when you turn it OFF you can see the problem.

And the problem is the `stringstream::gcount` breaks `stringstream` when it holds more the `INT_MAX`

Here is a patch in llvm-project - https://reviews.llvm.org/D146294

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If a user set `max_single_part_upload_size` to a very large value, it can lead to a crash due to a bug in the AWS S3 SDK. This fixes #47679.

Note: no tests will be provided for this issue.

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

File: src/Storages/StorageS3Settings.cpp [hunk 1]
```diff
@@ -77,6 +77,12 @@ void S3Settings::RequestSettings::PartUploadSettings::updateFromSettingsImpl(con
 
     if (!if_changed || settings.s3_max_single_part_upload_size.changed)
         max_single_part_upload_size = settings.s3_max_single_part_upload_size;
+
+    /// AWS S3 SDK library has a bug. It is using std::*stream (which is a major offense).
+    /// LLVM libc++ has a bug. It does not allow std::*stream to work for large strings.
+
+    if (max_single_part_upload_size >= 2_GiB)
+        throw Exception(ErrorCodes::INVALID_SETTING_VALUE, "Uploading parts of 2 GiB or larger is not supported due to a bug in AWS and LLVM. Lower the value of `s3_max_single_part_upload_size` setting.");
```
Comment (antonio2368) [inline src/Storages/StorageS3Settings.cpp:85]: just noticed there is `validate` function for this, auto merge already triggered 🥲
