### PR TITLE
Fix read of StorageFile with virtual columns

### LINKED ISSUE #39907: Logical error: Invalid number of columns in chunk pushed to OutputPort (when selecting only virtual columns from File)
```
SELECT
    _file,
    _path
FROM file('exists.csv', 'CSVWithNames')

Query id: 8bff0d32-cad0-4832-907a-be39f13ac49c


0 rows in set. Elapsed: 0.099 sec.

Received exception from server (version 22.7.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Invalid number of columns in chunk pushed to OutputPort. Expected 2, found 4
Header: _path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))), _file LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1)))
Chunk:  ColumnLowCardinality(size = 7385, UInt8(size = 7385), ColumnUnique(size = 1, String(size = 1))) ColumnLowCardinality(size = 7385, UInt8(size = 7385), ColumnUnique(size = 1, String(size = 1))) ColumnLowCardinality(size = 7385, UInt8(size = 7385), ColumnUnique(size = 2, String(size = 2))) ColumnLowCardinality(size = 7385, UInt8(size = 7385), ColumnUnique(size = 2, String(size = 2)))
. (LOGICAL_ERROR)
```

Version 22.7.1.2484

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix read of StorageFile with virtual columns. Closes #39907.

### CODE REVIEW

File: src/Storages/StorageFile.cpp [hunk 1]
```diff
@@ -693,13 +677,30 @@ Pipe StorageFile::read(
...
+            if (fetch_columns.empty())
+                fetch_columns.push_back(ExpressionActions::getSmallestColumn(storage_snapshot->metadata->getColumns().getAllPhysical()));
+            columns_description = storage_snapshot->getDescriptionForColumns(fetch_columns);
+            block_for_format = storage_snapshot->getSampleBlockForColumns(columns_description.getNamesOfPhysical());
+        }
+        else
+        {
+            columns_description = storage_snapshot->metadata->getColumns();
+            block_for_format = storage_snapshot->getSampleBlockForColumns(columns_description.getNamesOfPhysical());
+        }
```
Comment (kssenii) [inline src/Storages/StorageFile.cpp:703]:
```suggestion
            columns_description = storage_snapshot->getDescriptionForColumns(fetch_columns);
        }
        else
        {
            columns_description = storage_snapshot->metadata->getColumns();
        }
        
        block_for_format = storage_snapshot->getSampleBlockForColumns(columns_description.getNamesOfPhysical());
```

**Review by kssenii — APPROVED** [review]
