### PR TITLE
Fix mutation fail of StorageMemory

### LINKED ISSUE #24274: Mutation of StorageMemory with more than one block will fail when max_threads > 1
How to reproduce:

```sql
VM-16-2-centos :) create table mem_test(a Int64, b Int64) engine = Memory

CREATE TABLE mem_test
(
    `a` Int64,
    `b` Int64
)
ENGINE = Memory

Query id: fb8d3ab7-6e69-410d-b5e3-9891c8604a9c

Ok.

0 rows in set. Elapsed: 0.004 sec. 
VM-16-2-centos :) set max_block_size = 3

SET max_block_size = 3

Query id: 6803f260-4893-4f0b-91cf-fc5d5670ce7c

Ok.

0 rows in set. Elapsed: 0.001 sec.

VM-16-2-centos :) insert into mem_test select number, number from numbers(100)

INSERT INTO mem_test SELECT
    number,
    number
FROM numbers(100)

Query id: 19f11e21-4b76-4015-ac05-99732facee6a

Ok.

0 rows in set. Elapsed: 0.002 sec.
VM-16-2-centos :) alter table mem_test update  a = 0 where b = 99

ALTER TABLE mem_test
    UPDATE a = 0 WHERE b = 99

Query id: a9d72960-7c86-4195-b739-7148fea99c10

Ok.

0 rows in set. Elapsed: 0.001 sec. 

VM-16-2-centos :) select * from mem_test format Null

SELECT *
FROM mem_test
FORMAT Null

Query id: 413f4d7e-cca9-4523-aedb-f9673bc515cb


0 rows in set. Elapsed: 0.011 sec. 

Received exception from server (version 21.6.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Invalid number of rows in Chunk column Int64 position 1: expected 1, got 3: While executing Memory. 


```

### PR DESCRIPTION
**Pull request by ucasfl**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Set `max_threads = 1` to fix mutation fail of StorageMemory. Closes #24274.

Detailed description / Documentation draft:

When `max_threads > 1`, the returning order of blocks is uncentain, leads to mutation fail.

### CODE REVIEW

**Review by alesapin — APPROVED** [review]
Maybe we have to move this code into the interpreter...

File: src/Storages/StorageMemory.cpp [hunk 1]
```diff
@@ -262,7 +262,13 @@ void StorageMemory::mutate(const MutationCommands & commands, ContextPtr context
...
     auto storage = getStorageID();
     auto storage_ptr = DatabaseCatalog::instance().getTable(storage, context);
-    auto interpreter = std::make_unique<MutationsInterpreter>(storage_ptr, metadata_snapshot, commands, context, true);
+
+    auto new_settings = context->getSettings();
+    new_settings.max_threads = 1;
+    auto new_context = Context::createCopy(context);
+    new_context->setSettings(new_settings);
+
+    auto interpreter = std::make_unique<MutationsInterpreter>(storage_ptr, metadata_snapshot, commands, new_context, true);
```
Comment (kitaisreal) [inline src/Storages/StorageMemory.cpp:271]: @ucasFL can't we fix that without copying context and changing max threads ?

**Comment by alesapin** [comment]
@ucasFL  Let's tune settings like in MergeTree https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L1184-L1186

**Review by kitaisreal — APPROVED** [review]

**Comment by ucasFL** [comment]
> @ucasFL Let's tune settings like in MergeTree https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp#L1184-L1186

OK.

**Comment by alesapin** [comment]
@ucasFL What about `max_streams_to_max_threads_ratio`?

**Comment by alesapin** [comment]
No related failures
