### PR TITLE
clickhouse-local - fix issue with stuck queries 

### LINKED ISSUE #80687: Drop view stuck
### Describe the bug

This seems to happen since v24.12 with `--local`. I can't reproduce it in v24.10

### How to reproduce

Run on ClickHouse local:
```sql
CREATE VIEW v0 AS (SELECT 1 AS c0);
DROP VIEW v0 SYNC; --stuck
```

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by bharatnc**
With `clickhouse-local` `DROP VIEW` type queries seem to get stuck and it looks like the behavior changed after  https://github.com/ClickHouse/ClickHouse/pull/71722. It works if you provide `--path`:
```
./clickhouse local --path="/tmp/foo"
ClickHouse local version 25.6.1.1.

:) CREATE VIEW v0 AS (SELECT 1 AS c0);

CREATE VIEW v0
AS SELECT 1 AS c0

Query id: a473d29b-7889-433b-a912-cd6612bf048d

Ok.

0 rows in set. Elapsed: 0.043 sec. 

:) DROP VIEW v0 SYNC;

DROP VIEW v0 SYNC

Query id: 7abcab02-65e1-4930-b420-683168878993

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```

However it should also work even without `--path` and in temporary mode.  It looks like the issue is the drop query is stuck in `waitTableFinallyDropped` as the [background tasks](https://github.com/ClickHouse/ClickHouse/blob/58662b65cffc49de75173764f7377dae6ad526c2/programs/local/LocalServer.cpp#L951-L953) are probably not initialized properly: https://pastila.clickhouse.com/?000fbbfb/79a95452dd365a5b3382bd77720d6ef8#BHprmQiol3rnR5+XKDS67g==.

It seems like these kinds of DDL queries relay on background tasks to be initialized. So, initialize the background tasks in temporary mode (no `--path`) but skip if `--only-system-tables` is requested.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix issues with `clickhouse-local` involving stuck `DROP VIEW ` queries. 

Closes: https://github.com/ClickHouse/ClickHouse/issues/80687

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: programs/local/LocalServer.cpp [hunk 1]
```diff
@@ -967,6 +967,14 @@ void LocalServer::processConfig()
         attachSystemTablesServer(global_context, *createMemoryDatabaseIfNotExists(global_context, DatabaseCatalog::SYSTEM_DATABASE), false);
         attachInformationSchema(global_context, *createMemoryDatabaseIfNotExists(global_context, DatabaseCatalog::INFORMATION_SCHEMA));
         attachInformationSchema(global_context, *createMemoryDatabaseIfNotExists(global_context, DatabaseCatalog::INFORMATION_SCHEMA_UPPERCASE));
+
+        // Background tasks are required for DDL operations like DROP VIEW SYNC, even in temporary mode (no --path).
+        // Only skip if --only-system-tables is requested.
+        if (!getClientConfiguration().has("only-system-tables"))
```
Comment (kssenii) [inline programs/local/LocalServer.cpp]: We are currently also inside a `!getClientConfiguration().has("no-system-tables")` condition (see line 965), looks like we should also add it to `else` after it.

Comment (bharatnc) [reply programs/local/LocalServer.cpp]: Yeah, makes sense. Made the fix, now it should work correctly with both `--only-system-tables` and `--no-system-tables`.

**Review by kssenii — APPROVED** [review]
