### PR TITLE
Fix insertion of complex JSONs with nested arrays to columns of type `Object`.

### LINKED ISSUE #35960: Error in insert to the column of type `Object`
**How to reproduce**

```
clickhouse-client -q "create table t_json(obj JSON) engine = Memory" --allow_experimental_object_type 1
```

Create a file with the following data:

```json
{
    "key_1":[
        {
            "key_2":100,
            "key_3": [
                {
                    "key_7":257,
                    "key_4":[{"key_5":-2}]
                }
            ]
        },
        {
            "key_2":65536
        }
    ]
}
```

The insertion fails:
```
cat some.json | clickhouse-client -q "insert into t_json format JSONAsObject"

Received exception from server (version 22.4.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: offsets_column has data inconsistent with nested_column. (LOGICAL_ERROR)
(query: insert into t_json format JSONAsObject)
```

### LINKED ISSUE #35996: Insert with JSONAsObject format fails with NUMBER_OF_DIMENSIONS_MISMATHED error
**How to reproduce**

It works as expected:
```
clickhouse-client --allow_experimental_object_type 1 \
  -q "create table json_1 (o JSON) ENGINE = MergeTree ORDER BY tuple()"

cat - <<EOF | clickhouse-client -q "insert into json_1 format JSONAsObject"  
{"a": {"b": 1, "c": [{"d": 10, "e": [31]}, {"d": 20, "e": [63, 127]}]}}  
{"a": {"b": 2, "c": []}}  
EOF
```

Renaming the a.c.d field to a.c.f clickhouse-client fails:
```
clickhouse-client --allow_experimental_object_type 1 \
  -q "create table json_2 (o JSON) ENGINE = MergeTree ORDER BY tuple()"

cat - <<EOF | clickhouse-client -q "insert into json_2 format JSONAsObject"
{"a": {"b": 1, "c": [{"f": 10, "e": [31]}, {"f": 20, "e": [63, 127]}]}}
{"a": {"b": 2, "c": []}}
EOF
Code: 645. DB::Exception: Dimension of types mismatched between inserted value and column. Dimension of value: 1. Dimension of column: 2: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from stdin: (in query: insert into json_test format JSONAsObject). (NUMBER_OF_DIMENSIONS_MISMATHED)
```

Tested versions:
22.3.2.1
22.4.1.1

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix insertion of complex JSONs with nested arrays to columns of type `Object`. 

Fixes #35996.
Fixes #35960.

### CODE REVIEW

File: src/DataTypes/Serializations/JSONDataParser.cpp [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+    {
+        const auto & [key, value] = *it;
+        ctx.builder.append(key, false);
+        traverse(value, ctx);
+        ctx.builder.popBack();
+    }
+}
+
+template <typename ParserImpl>
+void JSONDataParser<ParserImpl>::traverseArray(const JSONArray & array, ParseContext & ctx)
```
Comment (yakov-olkhovskiy) [inline src/DataTypes/Serializations/JSONDataParser.cpp:71]: name 'array' is different from declaration - compilation warning:
```
Apr 21 19:20:05 ../src/DataTypes/Serializations/JSONDataParser.h:51:10: error: function 'DB::JSONDataParser::traverseArray' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
Apr 21 19:20:05     void traverseArray(const JSONArray & object, ParseContext & ctx);
Apr 21 19:20:05          ^
Apr 21 19:20:05 /build/build_docker/../src/DataTypes/Serializations/JSONDataParser.cpp:71:34: note: the definition seen here
Apr 21 19:20:05 void JSONDataParser<ParserImpl>::traverseArray(const JSONArray & array, ParseContext & ctx)
Apr 21 19:20:05                                  ^
Apr 21 19:20:05 /build/build_docker/../src/DataTypes/Serializations/JSONDataParser.h:51:10: note: differing parameters are named here: ('object'), in definition: ('array')
Apr 21 19:20:05     void traverseArray(const JSONArray & object, ParseContext & ctx);
Apr 21 19:20:05          ^                               ~~~~~~
Apr 21 19:20:05                                          array
Apr 21 19:20:05 90935 warnings generated.
Apr 21 19:20:05 Suppressed 91054 warnings (90933 in non-user code, 120 NOLINT, 1 with check filters).
Apr 21 19:20:05 Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Apr 21 19:20:05 1 warning treated as error
```

File: src/DataTypes/ObjectUtils.cpp [hunk 2]
```diff
@@ -698,4 +698,33 @@ void finalizeObjectColumns(MutableColumns & columns)
...
+    {
+        size_t current_dimensions = applyVisitor(*this, x[i]);
+        if (!dimensions)
+            dimensions = current_dimensions;
+        else
+            dimensions = std::max(*dimensions, current_dimensions);
+    }
+
+    return 1 + dimensions.value_or(0);
+}
```
Comment (yakov-olkhovskiy) [inline src/DataTypes/ObjectUtils.cpp:728]: as I understand using optional is solely to avoid calling max on the first iteration? not sure it worth this complication, besides optional itself adds overhead...
```
size_t FieldVisitorToNumberOfDimensions::operator()(const Array & x) const
{
    const size_t size = x.size();
    size_t dimensions = 0;

    for (size_t i = 0; i < size; ++i)
        dimensions = std::max(dimensions, applyVisitor(*this, x[i]));

    return 1 + dimensions;
}
```

**Review by yakov-olkhovskiy — APPROVED** [review]
I'm approving now, but look my note regarding visitor recursion above.

**Review by yakov-olkhovskiy — APPROVED** [review]

**Comment by CurtizJ** [comment]
@Mergifyio update

**Comment by CurtizJ** [comment]
`ClickHouse Stress Test (debug, Actions)` - #36789
`ClickHouse Stress Test (memory, Actions)`  and `ClickHouse Stress Test (thread, Actions)` - I don't know, unrelated.

**Comment by chrootweili** [comment]
When will this pr backport to older version?
