### PR TITLE
fs cache: remove file from opened file cache immediately when evicting file

### LINKED ISSUE #50468: Logical error: 'Read unexpected size. ...'
https://s3.amazonaws.com/clickhouse-test-reports/0/0c15a2ddc66e1cabf31537a85e77ae255610c955/stress_test__ubsan_/fatal_messages.txt

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove file from opened file cache when evicting file. Closes https://github.com/ClickHouse/ClickHouse/issues/50468.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit b56d1602e841663f073c6f53a06e848b89c9214e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51596/b56d1602e841663f073c6f53a06e848b89c9214e/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Interpreters/Cache/Metadata.cpp [hunk 1]
```diff
@@ -406,6 +406,11 @@ KeyMetadata::iterator LockedKey::removeFileSegment(size_t offset, const FileSegm
     if (exists)
     {
         fs::remove(path);
+
+        int flags = file_segment->getFlagsForLocalRead();
```
Comment (nikitamikhaylov) [inline src/Interpreters/Cache/Metadata.cpp:410]: A comment is needed.
