### PR TITLE
Handle alias expressions in the TTL description format

### LINKED ISSUE #88306: Even more inconsistent AST formatting
### Describe the bug

There was an inconsistent AST formatting issue with the `materialize` function, but it was closed, I think.

### How to reproduce

Run:
```sql
CREATE TABLE t0(c0 Int) ENGINE = MergeTree() ORDER BY tuple() TTL greater(materialize(2), 1);
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Inconsistent AST formatting: the query:
CREATE TABLE t0 (`c0` Int) ENGINE = MergeTree ORDER BY tuple() TTL materialize(2) > 1
cannot parse query back from CREATE TABLE t0(c0 Int) ENGINE = MergeTree() ORDER BY tuple() TTL greater(materialize(2), 1);'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000240d1af2
1. src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014a325e9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d32930e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d328d11
4. src/Common/Exception.h:141: DB::Exception::Exception<String&, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, String&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000001aa507f6
5. src/Interpreters/executeQuery.cpp:1130: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x000000001aa47edc
6. src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001aa3f8b2
7. src/Server/TCPHandler.cpp:743: DB::TCPHandler::runImpl() @ 0x000000001e30e06e
8. src/Server/TCPHandler.cpp:2754: DB::TCPHandler::run() @ 0x000000001e3279a4
9. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000024188507
10. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000024188ae5
11. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000024127c7f
12. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000024125351
13. start_thread @ 0x00000000000a27f1
14. __GI___clone3 @ 0x0000000000133b5c
```

### PR DESCRIPTION
**Pull request by ahmadov**
The alias expression should be wrapped by a paranthesis.

Fixes #88306

### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by ahmadov** [comment]
* Stateless tests (amd_debug, distributed plan, s3 storage, sequential): https://github.com/ClickHouse/ClickHouse/issues/80315
* Integration tests (arm_binary, distributed plan, 2/4): https://github.com/ClickHouse/ClickHouse/issues/90840
* Integration tests (amd_tsan, 1/6): https://github.com/ClickHouse/ClickHouse/issues/88775
* BuzzHouse (amd_debug):https://github.com/ClickHouse/ClickHouse/issues/91542

File: tests/queries/0_stateless/00933_ttl_formatting.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+--- Tests for Github issue 88306
```
Comment (vdimir) [inline tests/queries/0_stateless/00933_ttl_formatting.sql:1]: @ahmadov
Normally we name tests sequentially, so the number of this test `00933_*` looks like a pretty old test, while it was added recently. It's not a big problem, but it may be a bit confusing (for example, for a flaky test you might identify whether it's old or new by its number). You can use the script https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/add-test to create a test with the proper number.
