### PR TITLE
disallow zero value for max_insert_block_size

### LINKED ISSUE #31367: max_insert_block_size=0 makes an insert to insert 0 rows
```bash
drop table if exists trg;
create table trg(A Int64, S String) Engine=MergeTree order by A;

clickhouse-client -q \
      'select toInt64(number) A, toString(number) S from numbers(1000) format TSV' > t.tsv

clickhouse-client --max_insert_block_size=0  -q 'insert into trg format TSV' <t.tsv

select count() from trg;
┌─count()─┐
│       0 │
└─────────┘
```

### LINKED ISSUE #83620: max_insert_block_size = 0
### Describe the bug

You know the deal. I could create the PR for this one. Fails since v25.2

### How to reproduce

Run the Fiddle: https://fiddle.clickhouse.com/303f92c8-bdc5-41ca-a720-f9704d215a1a

### Error message and/or stacktrace

Stack trace:

```
Logical error: 'Unread data in PeekableReadBuffer will be lost. Most likely it's a bug.'.
Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000024bff3d2
1. src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013a12546
2. src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000ca6c4cc
3. src/Common/Exception.h:137: DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000ca75f16
4. src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:641: DB::ValuesBlockInputFormat::readSuffix() @ 0x000000001d16ab77
5. src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:172: DB::ValuesBlockInputFormat::read() @ 0x000000001d169e55
6. src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x000000001cf46fd6
7. src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x000000001cf22365
8. src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000001cf22052
9. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001cf3d110
10. src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001cf31754
11. src/Processors/Executors/PipelineExecutor.cpp:276: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001cf31b09
12. src/Processors/Executors/PipelineExecutor.cpp:508: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001cf303a3
13. src/Processors/Executors/PipelineExecutor.cpp:135: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001cf2faff
14. src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001cf41334
15. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000013b48e86
16. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000013b4f460
17. start_thread @ 0x00000000000a2ef1
18. __GI___clone3 @ 0x000000000013445c
```

### PR DESCRIPTION
**Pull request by bharatnc**
Disallow zero value for `max_insert_block_size` as it could cause logical error. 

Closes: https://github.com/ClickHouse/ClickHouse/issues/83620
Closes: https://github.com/ClickHouse/ClickHouse/issues/31367

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Disallow zero value for max_insert_block_size as it could cause logical error.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by GrigoryPervakov — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

**Comment by bharatnc** [comment]
Test failures not related:

- [Stateless tests (amd_tsan, s3 storage, 2/3)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83688&sha=0c277c453fd4da7ad636aed4fbf5dd2943f7139e&name_0=PR&name_1=Stateless%20tests%20%28amd_tsan%2C%20s3%20storage%2C%202%2F3%29) — Failed: 1, Passed: 2636, Skipped: 121 - `02561_null_as_default_more_formats` - https://github.com/ClickHouse/ClickHouse/issues/83756

File: tests/queries/0_stateless/03560_validate_max_insert_block_size.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+DROP TABLE IF EXISTS t;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03560_validate_max_insert_block_size.sql:3]: As a general rule, we want people to understand what the test is about at a high level _without_ having them read the whole thing (In this case, it is just a few lines so it's okay).

Therefore, please add a brief comment about the test purpose on top, alternatively a reference to the GitHub issues.

Comment (bharatnc) [reply tests/queries/0_stateless/03560_validate_max_insert_block_size.sql:3]: Sure, I'll add.

Comment (bharatnc) [reply tests/queries/0_stateless/03560_validate_max_insert_block_size.sql:3]: Added a reference to the github issue.
