### PR TITLE
ISSUES-16605 fix without returning affected rows when insert select query in MySQL handler

### LINKED ISSUE #16605: ClickHouse doesn't return affected rows via MySQL protocol for INSERT queries after 20.5+
**Describe the bug**
ClickHouse doesn't return affected rows via MySQL protocol for INSERT queries after 20.5+

**How to reproduce**
i create clear docker-compose environment for reproduce behavior MySQL + clickhouse + php + python
https://gist.github.com/Slach/aa67440ce856a3a53f64f92eeddfbc1b

**Queries to run that lead to unexpected result**
```
INSERT INTO default.t1(n) SELECT * FROM numbers(1000)
```

**Expected behavior**
MySQL protocol shall return affected rows field for INSERT queries (it works successful in 20.3 and 20.4)
image

**Actual behavior**
image

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Return number of affected rows for INSERT queries via MySQL protocol. Previously ClickHouse used to always return 0, it's fixed.
Fixes #16605

### CODE REVIEW

**Comment by tavplubix** [comment]
Integration tests (thread) - failure is related, data race on `affected_rows`: https://gist.github.com/tavplubix/638666056d7a067b8938eb4cccb6a128
Seems like we can just make it atomic.

File: src/Server/MySQLHandler.cpp [hunk 1]
```diff
@@ -328,6 +328,9 @@ void MySQLHandler::comQuery(ReadBuffer & payload)
 
         Context query_context = connection_context;
 
+        size_t affected_rows = 0;
+        query_context.setProgressCallback([&](const Progress & progress) { affected_rows += progress.written_rows; });
```
Comment (tavplubix) [inline src/Server/MySQLHandler.cpp:332]: Is it possible that `connection_context` already have some progress callback? Maybe do something similar to [this](https://github.com/ClickHouse/ClickHouse/blob/55d05c95bfcd43c9b094da5ff389d7be1f0ad365/src/Server/HTTPHandler.cpp#L584)?

**Review by tavplubix — APPROVED** [review]

**Comment by zhang2014** [comment]
Performance — 5 errors, 5 too long, 2 faster, 72 unstable - unrelated
```
The test 'materialized_view_parallel_insert' is too slow to run as a whole. Investigate whether the create and fill queries can be sped up
Some query of the test 'materialized_view_parallel_insert' is too slow to run. See the all queries report
The test 'parallel_insert' is too slow to run as a whole. Investigate whether the create and fill queries can be sped up
Some query of the test 'parallel_insert' is too slow to run. See the all queries report
The test 'array_index_low_cardinality_numbers' is too slow to run as a whole. Investigate whether the create and fill queries can be sped up
```

Integration tests (asan) — fail: 1, not started: 0, passed: 946, error: 0  - unrelated
```
    test_odbc_interaction/test.py::test_postgres_odbc_hached_dictionary_with_schema
```
Integration tests (release) — fail: 2, not started: 0, passed: 945, error: 0 - unrelated
```
    test_storage_s3/test.py::test_custom_auth_headers
    test_odbc_interaction/test.py::test_postgres_odbc_hached_dictionary_with_schema
```
