### PR TITLE
Fix processAndOptimizeTextIndexFunctions when `query_plan_merge_expressions = 0`

### LINKED ISSUE #100879: 02346_text_index_bug89605 gives wrong result with `query_plan_merge_expressions = 0`
### Describe the bug

Found while debugging here https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=100874&sha=fd8dcaed8e980cfd7d899020b2eb7d2cecf964fb&name_0=PR&name_1=Stateless+tests+%28arm_binary%2C+parallel%29 cc @CurtizJ @Ergus @ahmadov 

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/0a1c42c0-3bca-479d-be6c-9416f2ca2098

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by Ergus**
In this case ExpressionStep is directly above ReadFromMergeTree, and we need to handle that.

Fixes: #100879

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.379`

### CODE REVIEW

File: src/Processors/QueryPlan/Optimizations/optimizeDirectReadFromTextIndex.cpp [hunk 1]
```diff
@@ -688,21 +690,53 @@ void processAndOptimizeTextIndexFunctions(const Stack & stack, QueryPlan::Nodes
...
+
+    const auto * result_filter_node = processAndOptimizeTextIndexDAG(*read_from_merge_tree_step, composed, text_index_read_infos, filter_column_name, direct_read_from_text_index && !optimized);
 
     if (!result_filter_node)
         return;
 
     bool removes_filter_column = filter_step->removesFilterColumn();
     auto new_filter_column_name = result_filter_node->result_name;
-    filter_node->step = std::make_unique<FilterStep>(read_from_merge_tree_step->getOutputHeader(), filter_dag.clone(), new_filter_column_name, removes_filter_column);
+    filter_node->step = std::make_unique<FilterStep>(frame.node->step->getOutputHeader(), std::move(composed), new_filter_column_name, removes_filter_column);
```
Comment (george-larionov) [inline src/Processors/QueryPlan/Optimizations/optimizeDirectReadFromTextIndex.cpp]: I think `read_from_merge_tree_step->getOutputHeader()` is cleaner, unless I missed something

**Review by george-larionov — APPROVED** [review]
It looks good to me overall, just a minor comment and probably we need to mark it as backport needed.

File: src/Processors/QueryPlan/Optimizations/optimizeDirectReadFromTextIndex.cpp (hunk 1 above)
Comment (Ergus) [reply src/Processors/QueryPlan/Optimizations/optimizeDirectReadFromTextIndex.cpp]: You are right. It is a leftover from some of the approaches I tried in between to fix this.

File: src/Processors/QueryPlan/Optimizations/optimizeDirectReadFromTextIndex.cpp [hunk 2]
```diff
@@ -688,21 +690,53 @@ void processAndOptimizeTextIndexFunctions(const Stack & stack, QueryPlan::Nodes
...
+    ///
+    /// After composing, those inputs become ALIAS("__table1.msg") → INPUT("msg"), and getColumnName() follows the alias back to the
+    /// physical name. With merge_expressions = 1 the loop is a no-op since expression_steps is empty.
+    const String & filter_column_name = filter_step->getFilterColumnName();
+
+    /// expression_steps is bottom-up (index 0 = closest to ReadFromMergeTree, back() = closest to FilterStep),
+    /// so iterate in reverse to build merge(bottom, merge(..., merge(top, filter_dag)...)).
+    ActionsDAG composed = filter_step->getExpression().clone();
+    for (auto * step : expression_steps | std::views::reverse)
+        composed = ActionsDAG::merge(step->getExpression().clone(), std::move(composed));
```
[the remark this answers is not in the document]
Comment (Ergus) [reply src/Processors/QueryPlan/Optimizations/optimizeDirectReadFromTextIndex.cpp:729]: In practice expression_steps has at most one element (the column-renaming step inserted by the new query analyzer when query_plan_merge_expressions = 0).

**Comment by rschu1ze** [comment]
@Ergus I know you put in some work into this PR. At the same time, `Groene CI` (the AI CI fixing bot) started to suppress similar failures caused by `query_plan_merge_expressions = 0` in other tests by pinning the setting to `= 1` at the beginning of the test, see [here](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Apr+is%3Aopen+query_plan_merge_expressions). The thing is that `query_plan_merge_expressions` is an expert-level setting (see Core/Settings.cpp) and stuff is expected to break if it's disabled. In practice, customers wouldn't disable the setting. I think the bot is right. Therefore, we can save the extra complexity in optimizeDirectReadFromTextIndex.cpp and simply pin the setting in the test. Wdyt?
