### PR TITLE
Column declaration: [NOT] NULL right after type

### LINKED ISSUE #35889: Wrong order of NOT NULL data type modifier and DEFAULT.
**Describe the unexpected behaviour**

```
:) CREATE TEMPORARY TABLE test (x INT NOT NULL DEFAULT 1)

Syntax error: failed at position 52 ('DEFAULT') (line 3, col 22):

CREATE TEMPORARY TABLE test
(
    `x` INT NOT NULL DEFAULT 1
                     ^
)

Expected one of: COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket
```

But this query succeeded:

```
:) CREATE TEMPORARY TABLE test (x INT DEFAULT 1 NOT NULL)

CREATE TEMPORARY TABLE test
(
    `x` INT NOT NULL DEFAULT 1
)
```

### LINKED ISSUE #37229: Column declaration: [NOT] NULL right after type
Execution of this query
```
create table t (c1 int(11) DEFAULT 1 NULL) engine=MergeTree order by tuple()
```
will return parsed query
```
CREATE TABLE t
(
     `c1` int NULL DEFAULT 1
)
ENGINE = MergeTree
ORDER BY tuple()
```
In the parsed query, NULL comes before DEFAULT, in the initial - other way around.
If I try to execute the parsed query, I’ll get the following error:
```
Syntax error: failed at position 36 ('DEFAULT') (line 3, col 19):

CREATE TABLE t
(
    `c1` int NULL DEFAULT 1
)
ENGINE = MergeTree
ORDER BY tuple()

Expected one of: COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket
```
This is confusing. 
See also discussion in #37087

Considerations:
(1) considering simplification of migration from other databases (see, for example, #37178) probably it makes sense to keep support for old column declaration, - MySQL supports both ways: `NULL DEFAULT 1` and `DEFAULT 1 NULL`, even `COMMENT '1' NULL` which we don't support. This way it'll keep the change backward compatible
(2) from another side ... I guess ... there is no target to support all variants of different syntax. It's not desirable to complicate parser implementation just for this reason

### PR DESCRIPTION
**Pull request by devcrafter**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
allows providing `NULL`/`NOT NULL` right after type in column declaration

Fixes #37229 
Fixes #35889

### CODE REVIEW

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.reference [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+create table, column +type +NULL +DEFAULT
+id	Nullable(Int32)	DEFAULT	1			
+create table, column +type +NOT NULL +DEFAULT
+id	Int32	DEFAULT	1			
+create table, column +type +DEFAULT +NULL
+id	Nullable(Int32)	DEFAULT	1			
+create table, column +type +DEFAULT +NOT NULL
+id	Int32	DEFAULT	1			
+create table, column -type +NULL +DEFAULT
+id	UInt8	DEFAULT	1
```
Comment (devcrafter) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.reference:14]: Here, type should be nullable, i.e. `Nullable(Int8)` instead of just `Int8`

I guess the issue is that in interpreter, we check if a column is nullable _only_ if type is present for the column. But here, only the default expression is provided

See https://github.com/ClickHouse/ClickHouse/blob/dea1706d4e65572a23636483bb8800f3c733a460/src/Interpreters/InterpreterCreateQuery.cpp#L478

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.reference [hunk 2]
```diff
@@ -0,0 +1,20 @@
+create table, column +type +NULL
```
Comment (devcrafter) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.reference:1]: To-do: check/enrich the test with `ALTER COLUMN`/`MODIFY COLUMN`

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql [hunk 3]
```diff
@@ -0,0 +1,51 @@
+select 'create table, column +type +NULL';
+DROP TABLE IF EXISTS null_before SYNC;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:2]: Not really related but I didn't know about SYNC. It is undocumented at https://clickhouse.com/docs/en/sql-reference/statements/drop. Would be cool if you could add a brief note to the documentation too.

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+CREATE TABLE null_before (id INT NULL) ENGINE=MergeTree() ORDER BY tuple();
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:3]: Also not really related, but in https://clickhouse.com/docs/en/sql-reference/statements/create/table the documentation says that the type of a column is optional:

```
CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [NULL|NOT NULL] [DEFAULT|MATERIALIZED|EPHEMERAL|ALIAS expr1] [compression_codec] [TTL expr1],
    name2 [type2] [NULL|NOT NULL] [DEFAULT|MATERIALIZED|EPHEMERAL|ALIAS expr2] [compression_codec] [TTL expr2],
    ...
) ENGINE = engine
```

--> ```[type1]``` and ```[type2]```

Trying a CREATE TABLE statement w/o column types doesn't work. Would be cool if you could also fix that, while at it.

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+DESCRIBE TABLE null_before;
+
+select 'create table, column +type +NOT NULL +DEFAULT';
+DROP TABLE IF EXISTS null_before SYNC;
+CREATE TABLE null_before (id INT NOT NULL DEFAULT 1) ENGINE=MergeTree() ORDER BY tuple();
+DESCRIBE TABLE null_before;
+
+select 'create table, column +type +DEFAULT +NULL';
+DROP TABLE IF EXISTS null_before SYNC;
+CREATE TABLE null_before (id INT DEFAULT 1 NULL) ENGINE=MergeTree() ORDER BY tuple();
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:23]: Going back to the column specification in the documentation which I referenced above:

`name1 [type1] [NULL|NOT NULL] [DEFAULT|MATERIALIZED|EPHEMERAL|ALIAS expr1] [compression_codec] [TTL expr1],`

It states that (NOT) NULL must precede DEFAULT. So either the documentation is now wrong or the implementation allows for undocumented syntax ^^

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+DESCRIBE TABLE null_before;
+
+select 'create table, column +type +DEFAULT +NOT NULL';
+DROP TABLE IF EXISTS null_before SYNC;
+CREATE TABLE null_before (id INT DEFAULT 1 NOT NULL) ENGINE=MergeTree() ORDER BY tuple();
+DESCRIBE TABLE null_before;
+
+select 'create table, column -type +NULL +DEFAULT';
+DROP TABLE IF EXISTS null_before SYNC;
+CREATE TABLE null_before (id NULL DEFAULT 1) ENGINE=MergeTree() ORDER BY tuple();
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:33]: Uh, do we really want to allow column specifications without type?

File: src/Parsers/ParserCreateQuery.h [hunk 7]
```diff
@@ -105,9 +105,9 @@ class IParserColumnDeclaration : public IParserBase
 
     bool parseImpl(Pos & pos, ASTPtr & node, Expected & expected) override;
 
-    bool require_type = true;
-    bool allow_null_modifiers = false;
-    bool check_keywords_after_name = false;
+    const bool require_type = true;
```
Comment (rschu1ze) [inline src/Parsers/ParserCreateQuery.h:108]: Default values for bools are unneeded as all members are initialized in the ctor in l. 93ff.

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql (hunk 3 above)
Comment (devcrafter) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:2]: You can create an issue for documentation

File: src/Parsers/ParserCreateQuery.h (hunk 7 above)
Comment (devcrafter) [reply src/Parsers/ParserCreateQuery.h:108]: I consider that it's better to always initialize to avoid uninitialized members in case the constructor will change or new added

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql (hunk 5 above)
Comment (devcrafter) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:23]: See #37087 #35889

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql (hunk 6 above)
Comment (devcrafter) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:33]: My observation is that documentation and implementation regarding column declaration are contradictory. See #37087, also considerations in #37229. I'd rather consider what make sense and execute correspondingly

@tavplubix I'd appreciate for an opinion

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql (hunk 4 above)
Comment (devcrafter) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:3]: Either type or default value expression should be there

Comment (tavplubix) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:3]: Column type is optional if default expression is specified. Type is deduced from the default expression in this case. AFAIK there's nothing to fix.

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql (hunk 6 above)
Comment (tavplubix) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:33]: Column specifications without explicit type still make sense

Comment (rschu1ze) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:33]: Ah, the documentation says so already: "If the default expression is defined, the column type is optional. If there isn’t an explicitly defined type, the default expression type is used." Okay then.

Comment (devcrafter) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:33]: BTW, it doesn't work currently on master:
```sql
:) CREATE TABLE null_before (id NULL DEFAULT 1) ENGINE=MergeTree() ORDER BY tuple()

CREATE TABLE null_before
(
    `id` NULL DEFAULT 1
)
ENGINE = MergeTree
ORDER BY tuple()

Received exception from server (version 22.6.1):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unknown data type family: NULL. (UNKNOWN_TYPE)
```

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.reference (hunk 2 above)
Comment (devcrafter) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.reference:1]: NULL modifier is not allowed in `ATLER/MODIFY COLUMN` queries

File: tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+
+select 'alter column, NULL modifier is not allowed';
+DROP TABLE IF EXISTS null_before SYNC;
+CREATE TABLE null_before (id INT NOT NULL) ENGINE=MergeTree() ORDER BY tuple();
+ALTER TABLE null_before ALTER COLUMN id TYPE INT NULL; -- { clientError SYNTAX_ERROR }
+
+select 'modify column, NULL modifier is not allowed';
+DROP TABLE IF EXISTS null_before SYNC;
+CREATE TABLE null_before (id INT NOT NULL) ENGINE=MergeTree() ORDER BY tuple();
+ALTER TABLE null_before MODIFY COLUMN id NULL DEFAULT 1; -- { serverError UNKNOWN_TYPE }
```
Comment (devcrafter) [inline tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:59]: I wonder why it's not client error and not `SYNTAX_ERROR`

Comment (tavplubix) [reply tests/queries/0_stateless/02302_column_decl_null_before_defaul_value.sql:59]: It's a bit unexpected, but I think it's not necessary to fix.

**Review by rschu1ze — APPROVED** [review]

**Comment by filimonov** [comment]
It seems we're missing the support for the same in ALTERs 

https://fiddle.clickhouse.com/6e389d37-4334-4ca2-b0e5-7a852841b872

**Comment by rschu1ze** [comment]
@filimonov Thanks for the info. GitHub shows a funny message above the comment box and I agree with it 😄

image
