### PR TITLE
Fix rollback of Dynamic column on parsing failure

### LINKED ISSUE #82051: Logical error: Bad cast from type DB::ColumnCheckpoint to DB::ColumnCheckpointWithNested
### Describe the bug

Failing since v25.3. Easy to reproduce. Related to the Dynamic type?

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/4ca165d7-4e2c-4a99-bada-96be28733c7e

### Error message and/or stacktrace

Stack trace:

```
Logical error: 'Bad cast from type DB::ColumnCheckpoint to DB::ColumnCheckpointWithNested'.
Stack trace (when copying this message, always include the lines below):

0. src/contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::exception::exception[abi:se190107]() @ 0x000000001ad8b4b4
1. src/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x000000003c8af080
2. src/src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000267c882b
3. src/src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000001ad87176
4. src/src/Common/Exception.h:137: DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000001ad842af
5. src/src/Common/assert_cast.h:48: DB::ColumnCheckpointWithNested const& assert_cast<DB::ColumnCheckpointWithNested const&, DB::ColumnCheckpoint const&>(DB::ColumnCheckpoint const&) @ 0x00000000324395ae
6. src/src/Columns/ColumnArray.cpp:406: DB::ColumnArray::rollback(DB::ColumnCheckpoint const&) @ 0x0000000032423db3
7. src/src/Columns/ColumnDynamic.cpp:1066: DB::ColumnDynamic::rollback(DB::ColumnCheckpoint const&) @ 0x00000000325db8e4
8. src/src/Columns/ColumnTuple.cpp:308: DB::ColumnTuple::rollback(DB::ColumnCheckpoint const&) @ 0x0000000032763384
9. src/src/Processors/Formats/IRowInputFormat.cpp:219: DB::IRowInputFormat::read() @ 0x00000000343048dd
10. src/src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x00000000342331c4
11. src/src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x00000000341f04b9
12. src/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x00000000341efd84
13. src/src/Processors/Formats/Impl/ParallelParsingInputFormat.h:180: DB::ParallelParsingInputFormat::InternalParser::getChunk() @ 0x000000003455f9a3
14. src/src/Processors/Formats/Impl/ParallelParsingInputFormat.cpp:95: DB::ParallelParsingInputFormat::parserThreadFunction(std::shared_ptr<DB::ThreadGroup>, unsigned long) @ 0x000000003455cba3
15. src/src/Processors/Formats/Impl/ParallelParsingInputFormat.h:294: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::ParallelParsingInputFormat::scheduleParserThreadForUnitWithNumber(unsigned long)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000034560e6c
16. src/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000269b45a3
17. src/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x00000000269bd06a
18. src/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000269b147a
19. src/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000269b939f
20. start_thread @ 0x00000000000a2ef1
21. __GI___clone3 @ 0x000000000013445c
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix rollback of Dynamic column on parsing failure

Closes https://github.com/ClickHouse/ClickHouse/issues/82051

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Columns/ColumnDynamic.cpp [hunk 1]
```diff
@@ -1021,54 +1021,63 @@ ColumnPtr ColumnDynamic::compress(bool force_compression) const
...
-    for (size_t i = 0; i < nested.size(); ++i)
-        variants[i]->rollback(*nested[i]);
-
-    /// Keep the structure of variant as is but rollback
-    /// to 0 variants that are not in the checkpoint.
-    for (size_t i = nested.size(); i < variants.size(); ++i)
-        variants[i] = variants[i]->cloneEmpty();
+    for (const auto & [name, discr] : variant_info.variant_name_to_discriminator)
+    {
+        auto it = variants_checkpoints.find(name);
```
Comment (antaljanosbenjamin) [inline src/Columns/ColumnDynamic.cpp:1059]: I guess the issue arose because "after extension the order of variant types (and so their discriminators) can change" (from the inline docs of column variant), right?

**Review by antaljanosbenjamin — APPROVED** [review]

File: src/Columns/ColumnDynamic.cpp (hunk 1 above)
Comment (Avogar) [reply src/Columns/ColumnDynamic.cpp:1059]: Not exactly. The extension of a Variant happens in a way to preserve local order of columns to avoid discriminators rewrite (so global order of variants is changing, but local in the ColumnVariant is not).
But there is a problem that in `SerializationMap` in case of an error during parsing we use `column->cut()`:
https://github.com/ClickHouse/ClickHouse/blob/090cb5a4fddd5f8202689bb0fcb6108f3c5314d9/src/DataTypes/Serializations/SerializationMap.cpp#L208
And there we clone empty column and do `insertRangeFrom`. And in this case local order will be changed because when we clone empty Variant column we use global order as local (because we don't have discriminators and nothing is needed to rewrite)

Comment (Avogar) [reply src/Columns/ColumnDynamic.cpp:1059]: I also want to change this code of Map rollback because it's inefficient, but also just in case decided to change the Dynamic rollback to a safer version.

**Comment by Avogar** [comment]
`Integration tests (tsan, 1/6) (pull_request)` - https://github.com/ClickHouse/ClickHouse/issues/84384
`CH Inc sync` - CI internal issues
