### PR TITLE
Disable logical expression optimizer for expression with aliases.

### LINKED ISSUE #45789: MULTIPLE_EXPRESSIONS_FOR_ALIAS on the 23.1.2
Since the latest release (23.1.2), we started to have "MULTIPLE_EXPRESSION_FOR_ALIAS" errors when executing queries. 
The table is distributed and I'm using the zero replication feature.
This behaviour is not reproductible on the 22.12 on the same condition (distributed table + zero replication).

**Describe what's wrong**

I'm not able to reproduce on a simple example but the following query failed. 

```sql
  WITH       
        ((position(path, '/a') > 0) AND (NOT (position(path, 'a') > 0))) OR (path = '/b') OR (path = '/b/') as alias1
    SELECT
        max(alias1)
    FROM mytable
    WHERE (myid = 1259)
```
I'm not familiar with an intern optimiser of the query but in the error output, the condition has been optimized. 

**Does it reproduce on recent release?**

23.1.2

**Enable crash reporting**

I cannot 

**How to reproduce**

I was not able to reproduce it locally. 

**Expected behavior**

The SQL expression must not raise an alias expression error.

**Error message and/or stacktrace**

```sql
Received exception from server (version 23.1.2):
Code: 179. DB::Exception: Received from localhost:9000. DB::Exception: Different expressions with the same alias alias1:
((position(path, '/a') > 0) AND (NOT (position(path, 'a') > 0))) OR ((path IN ('/b', '/b/')) AS alias1) AS alias1
and
path IN ('/b', '/b/') AS alias1
: While processing ((position(path, '/a') > 0) AND (NOT (position(path, 'a') > 0))) OR ((path IN ('/b', '/b/')) AS alias1) AS alias1. (MULTIPLE_EXPRESSIONS_FOR_ALIAS)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
Never use it with optimize_min_equality_disjunction_chain_length=0

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Disable logical expression optimizer for expression with aliases. Never use it with `optimize_min_equality_disjunction_chain_length=0`. Fixes #45789

### CODE REVIEW

File: src/Interpreters/LogicalExpressionsOptimizer.cpp [hunk 1]
```diff
@@ -119,7 +119,7 @@ void LogicalExpressionsOptimizer::collectDisjunctiveEqualityChains()
         bool found_chain = false;
 
         auto * function = to_node->as<ASTFunction>();
-        if (function && function->name == "or" && function->children.size() == 1)
+        if (function && function->alias.empty() && function->name == "or" && function->children.size() == 1)
```
Comment (alexey-milovidov) [inline src/Interpreters/LogicalExpressionsOptimizer.cpp:122]: Missing a comment.
