### PR TITLE
Docker: better clickhouse-server  entrypoint

### LINKED ISSUE #10183: clickhouse-server docker initdb script sourcing ignores errors
Investigating some flaky builds we found that the initdb script doesn't check errors or issue retries for failed migrations:

https://github.com/ClickHouse/ClickHouse/blob/0ecfede695638a9565eb6815bf1772d7ea5445bc/docker/server/entrypoint.sh#L84-L100

Occasionally on our CI, the clickhouse client connection to zookeeper unexpectedly closes, which in turn causes the initial migration script to fail silently.

Zookeeper issues aside, I believe that the script should at least be checking that the migrations applied successfully (return code from clickhouse-client is 0).

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Docker image: several improvements for clickhouse-server entrypoint.

Detailed description / Documentation draft:
1) detect if folders are accessible instead of checking owners (which can vary and do vary)
2) die fast in the case when the config is not readable
3) die on errors (fixes https://github.com/ClickHouse/ClickHouse/issues/10183 )
4) use the same entrypoint for ubuntu-based and alpine-based containers:
    - rewrite `wget` a readiness check to be compatible with alpine
    - add bash to alpine 
    - autodetect `gosu` vs `su-exec`
4) nullglob to skip '*' in the empty folder
5) shellcheck fixes.

Images with those changes are available here

filimonovq/clickhouse-server:21.1.1.5643
filimonovq/clickhouse-server:21.1.1.5643-alpine

P.S. maybe we should start publishing alpine-based images?

### CODE REVIEW

File: docker/server/entrypoint.sh [hunk 1]
```diff
@@ -90,21 +105,22 @@ fi
...
-        echo >&2 'ClickHouse init process failed.'
-        exit 1
-    fi
-
-    if [ ! -z "$CLICKHOUSE_PASSWORD" ]; then
-        printf -v WITH_PASSWORD '%s %q' "--password" "$CLICKHOUSE_PASSWORD"
-    fi
+    # will try to send ping clickhouse via http_port (max 12 retries by default, with 1 sec timeout and 1 sec delay between retries)
+    tries=${CLICKHOUSE_INIT_TIMEOUT:-12}
+    while ! wget --spider -T 1 -q "http://127.0.0.1:$HTTP_PORT/ping" 2>/dev/null; do
```
Comment (stigsb) [inline docker/server/entrypoint.sh:114]: Probably don't need `--spider` option anymore now?

Comment (filimonov) [reply docker/server/entrypoint.sh:114]: Well `--spider` just means 'it will not download the pages, just check that they are there'. We still don't need to store 'ok' responce in some file, so i think we can leave it. Alternative is to redirect output to stderr/stdout/ or `/dev/null`.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
> P.S. maybe we should start publishing alpine-based images?

@filimonov Is there any reasons to not use it by default?

**Comment by filimonov** [comment]
Compatibility issues. 

1) Some people (may be even some CI tools) can build their own containers based on the official own relying on the ubuntu commands and features which work differently on alpine. 

For example imagine they install some odbc drivers using `apt-get` commands. 

2) Also (ust came to my mind right now) - uid of clickhouse user differs in alpine and in clickhouse. 
``` 
docker run -it filimonovq/clickhouse-server:21.1.1.5643 bash
root@d6b4c588d7cf:/# id clickhouse
uid=999(clickhouse) gid=999(clickhouse) groups=999(clickhouse)

docker run -it filimonovq/clickhouse-server:21.1.1.5643-alpine bash
bash-5.0# id clickhouse 
uid=100(clickhouse) gid=1000(clickhouse) groups=1000(clickhouse),1000(clickhouse)
```
That is not critical but maybe a bad surprise https://github.com/ClickHouse/ClickHouse/issues/18927#issuecomment-760049719

BTW - maybe we should create clickhouse user in the Dockerfile with fixed uid/gid ahead / before deb installallation will to it and will pick 'some' free uid for the user automatically?  

UPD1. Others do that - see:
https://github.com/docker-library/postgres/blob/03e769531fff4c97cb755e4a608b24935ceeee27/13/Dockerfile#L14-L18
https://github.com/docker-library/mysql/blob/b0a0e546712534b30ac13e8b2829f23654facbc5/8.0/Dockerfile.debian#L9-L10

UPD2. I will send one more PR fixing that.

**Comment by alexey-milovidov** [comment]
> Some people (may be even some CI tools)

We can keep scripts for Ubuntu container but publish Alpine container as the official.

> BTW - maybe we should create clickhouse user in the Dockerfile with fixed uid/gid ahead / before deb installallation

Yes, we can tune `Install.cpp` for it.

**Comment by filimonov** [comment]
One more thing to change - it prepare clickhouse-client image for alpine (BTW - as for me that separate client image is a bit useless, as you can use clickhouse-server for everything).

**Comment by alexey-milovidov** [comment]
Yes, and we can rename it to just `clickhouse`.

**Comment by filimonov** [comment]
p.2 : https://github.com/ClickHouse/ClickHouse/pull/19096
