### PR TITLE
Check what would be broken if do not add all the identifiers to functions map.

### LINKED ISSUE #63205: Cyclic aliases for identifier in valid query
This query works:
```
WITH path('clickhouse.com/a/b/c') AS x
SELECT x AS path2
```

But it doesn't work if the alias is `path`:

```
WITH path('clickhouse.com/a/b/c') AS x
SELECT x AS path

Query id: 65fef495-2e6f-4eaf-820a-252d8cfa45ad


Elapsed: 0.000 sec. 

Received exception:
Code: 174. DB::Exception: Cyclic aliases for identifier 'path'. In scope WITH path('clickhouse.com/a/b/c') AS x SELECT x AS path. (CYCLIC_ALIASES)
```

Works fine with the old analyzer:
```
WITH path('clickhouse.com/a/b/c') AS x
SELECT x AS path2
SETTINGS allow_experimental_analyzer = 0

Query id: 6a1cfe5f-7e2e-4e36-92d6-12aa7ecdf9ed

   ┌─path2──┐
1. │ /a/b/c │
   └────────┘

1 row in set. Elapsed: 0.000 sec.
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix an `Cyclic aliases` error for cyclic aliases of different type (expression and function)

Fixes #63205

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit b82eeeee88b521f5a4beb4a20006a452f0c0bb35 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63993/b82eeeee88b521f5a4beb4a20006a452f0c0bb35/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -586,6 +585,82 @@ class ExpressionsStack
...
+    std::unordered_map<std::string, QueryTreeNodePtr> & getAliasMap(IdentifierLookupContext lookup_context)
+    {
+        switch (lookup_context)
+        {
+            case IdentifierLookupContext::EXPRESSION: return *alias_name_to_expression_node;
+            case IdentifierLookupContext::FUNCTION: return alias_name_to_lambda_node;
+            case IdentifierLookupContext::TABLE_EXPRESSION: return alias_name_to_table_expression_node;
+        }
+
+        UNREACHABLE();
```
Comment (Algunenano) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:618]: I'd suggest trusting the compiler here or throwing LOGICAL_ERROR. See https://github.com/ClickHouse/ClickHouse/pull/64035

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 2]
```diff
@@ -471,7 +471,6 @@ struct TableExpressionData
         return buffer.str();
     }
 };
-
```
Comment (novikd) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:474]: Accidental change?

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 3]
```diff
@@ -586,6 +585,82 @@ class ExpressionsStack
...
+        {
+            auto jt = transitive_aliases.find(*key);
+            if (jt == transitive_aliases.end())
+                return {};
+
+            key = &(getKey(jt->second, find_option));
+            it = alias_map.find(*key);
+        }
+
+        return &it->second;
```
Comment (novikd) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:654]:
```suggestion
        if (it != alias_map.end())
            return &it->second;

        if (lookup.lookup_context == IdentifierLookupContext::TABLE_EXPRESSION)
            return {};

        while (it == alias_map.end())
        {
            auto jt = transitive_aliases.find(*key);
            if (jt == transitive_aliases.end())
                return {};

            key = &(getKey(jt->second, find_option));
            it = alias_map.find(*key);
        }

        return &it->second;
```

Comment (novikd) [reply src/Analyzer/Passes/QueryAnalysisPass.cpp:654]: Also, I think there could be problems with the loop in the query like:
```sql
WITH
 a as b,
 b as c,
 c as a,
SELECT a;
```
It's better to check.

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 4]
```diff
@@ -2857,23 +2919,29 @@ QueryTreeNodePtr QueryAnalyzer::tryResolveIdentifierFromAliases(const Identifier
...
+    if (it == nullptr)
         return {};
 
-    if (!it->second)
+    QueryTreeNodePtr & alias_node = *it;
+
+    if (!alias_node)
         throw Exception(ErrorCodes::LOGICAL_ERROR,
             "Node with alias {} is not valid. In scope {}",
             identifier_bind_part,
```
Comment (novikd) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:2947]: I think it's better to move this check inside of `ScopeAliases` and make `ScopeAliases::find` return `QueryTreeNodePtr` instead of `QueryTreeNodePtr *`. This line checks that the alias map is filled with correct data.

**Review by novikd — COMMENTED** [review]
In general LGTM. It's better to remove the commented code, `QueryAnalysisPass.cpp` is already quite big.

File: src/Analyzer/Passes/QueryAnalysisPass.cpp (hunk 4 above)
Comment (KochetovNicolai) [reply src/Analyzer/Passes/QueryAnalysisPass.cpp:2950]: I don't know how to do it properly:
* There is a place where it's possible to not find the alias: https://github.com/ClickHouse/ClickHouse/blob/51afec49107864e97eb36f9e5760efd1e11bfea8/src/Analyzer/Passes/QueryAnalysisPass.cpp#L4198-L4204
* We can replace alias node to resolved one later https://github.com/ClickHouse/ClickHouse/blob/51afec49107864e97eb36f9e5760efd1e11bfea8/src/Analyzer/Passes/QueryAnalysisPass.cpp#L2987

So I can't return `QueryTreeNodePtr` because it won't be possible to update the alias map, and I can't use `QueryTreeNodePtr &` because it's ok to not find an alias, and I can't use `std::optional<QueryTreeNodePtr &>` because this is not supported.
