### PR TITLE
Fix masking sensitive data in system.functions

### LINKED ISSUE #94145: query_masking_rules do not apply to system.functions — sensitive data in UDF definitions remains visible
### Company or project name

_No response_

### Question

I'm using query_masking_rules to hide arguments of encryption/decryption functions (e.g., decrypt(...)) in logs, and it works correctly in system.query_log — the arguments are replaced as expected.

However, I noticed that the same masking does not apply to the create_query column in system.functions. When a user-defined function (UDF) contains calls like decrypt('aes-128-ecb', ..., 'secret_key'), the full definition — including secrets

This creates a security concern: even if query logging is masked, any user with access to system.functions can see raw secrets embedded in UDF bodies

We’re considering moving secrets out of UDF bodies (e.g., into dictionaries or config files), but it would be helpful to know if this limitation is intentional or if masking in metadata views could be supported in the future.

Environment: ClickHouse version 25.12.2.54

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix masking sensitive data in `system.functions`.

Closes https://github.com/ClickHouse/ClickHouse/issues/94145.

### Version info
- Merged into: `26.1.1.607`

### CODE REVIEW

File: tests/queries/0_stateless/03792_udf_masking_sensitive_data.sh [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+# Tags: no-fasttest
+# encrypt functions don't exist in the fasttest build
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+TEST_ENCRYPT_FUNC="test_encrypt_func_${CLICKHOUSE_DATABASE}"
+TEST_DECRYPT_FUNC="test_decrypt_func_${CLICKHOUSE_DATABASE}"
+KEY="TOPSECRET-TOPSECRET-TOPSECRET---"
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03792_udf_masking_sensitive_data.sh:11]: This is probably my lack of knowledge, but could you please explain where is the rule defined which hides `TOPSECRET-TOPSECRET-TOPSECRET---`? I see this rule:
```
<regexp>TOPSECRET.TOPSECRET</regexp>
<replace>[hidden]</replace>
```

But I don't understand how does this replaces all three of the `TOPSECRET` in one go to `[HIDDEN]`.

**Review by antaljanosbenjamin — COMMENTED** [review]
Please make the changelog category at least a bugfix, but maybe even critical bugfix.

Not for changelog is too relaxed for this I think.

File: tests/queries/0_stateless/03792_udf_masking_sensitive_data.sh (hunk 1 above)
Comment (alexey-milovidov) [reply tests/queries/0_stateless/03792_udf_masking_sensitive_data.sh:11]: @antaljanosbenjamin, these are two different things:

1. Query masking rules - a set of preconfigured regular expressions that apply to server logs.
2. Hiding sensitive parameters such pass passwords in table functions and encryption keys in encryption functions.

This is №2.

**Review by alexey-milovidov — APPROVED** [review]

File: tests/queries/0_stateless/03792_udf_masking_sensitive_data.sh (hunk 1 above)
Comment (vitlibar) [reply tests/queries/0_stateless/03792_udf_masking_sensitive_data.sh:11]: Yes, in this case it detects that the function name is `encrypt()` or `decrypt()` and masks its arguments except the first one whatever they are ([see](https://github.com/ClickHouse/ClickHouse/blob/51656c540eaae7169d4ae5f09f5d698b07de75b4/src/Parsers/FunctionSecretArgumentsFinder.h#L136-L142)).
