### PR TITLE
Analyzer: ConstantNode optimization.

### LINKED ISSUE #72880: Performance issue with analyzer.
How to reproduce:
```sql
WITH (
        SELECT arrayResize([1], 1000000)
    ) AS arr
SELECT length(arr)

Query id: 60eaa526-a0e3-4a56-a54b-75f0e26c6606

   ┌─length(arr)─┐
1. │     1000000 │
   └─────────────┘

1 row in set. Elapsed: 0.967 sec. 

SET allow_experimental_analyzer = 0

Query id: 357f9028-abdf-4d1d-9875-69e4ac0f2af7

Ok.

0 rows in set. Elapsed: 0.001 sec.

WITH (
        SELECT arrayResize([1], 1000000)
    ) AS arr
SELECT length(arr)

Query id: e35bd81a-36cd-427c-aeec-916ff20cb7c6

   ┌─length(arr)─┐
1. │     1000000 │
   └─────────────┘

1 row in set. Elapsed: 0.011 sec.
```

Flamegraph shows:
image

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):
Optimization for large value in ConstantNode. Closes #72880.

### Details
Closes #72880

### CODE REVIEW

File: src/Core/Settings.cpp [hunk 1]
```diff
@@ -6980,6 +6980,16 @@ Applied only for subquery depth = 0. Subqueries and INSERT INTO ... SELECT are n
 If the top-level construct is UNION, 'ORDER BY rand()' is injected into all children independently.
 Only useful for testing and development (missing ORDER BY is a source of non-deterministic query results).
     )", 0) \
+    DECLARE(Int64, optimize_const_name_size, 256, R"(
+Replace with scalar and use hash as a name for large constants (size is estimated by name length).
```
Comment (alexey-milovidov) [inline src/Core/Settings.cpp]:
```suggestion
Replace with scalar and use hash as a name for large constants (size is estimated by the name length).
```

**Review by KochetovNicolai — APPROVED** [review]
