### PR TITLE
fix cpu usage metric in client

### LINKED ISSUE #38756: CPU metric in clickhouse-client is wrong
CPU usage is misreported.

Currently "0 CPU" means "no CPU metric received in the previous ProfileEvents packet". But there can be many ProfileEvents packets and only a few with CPU increment.

That's why the CPU metric shows something weird like:
```
0
0
0
0
0
1234
0
0
0
...
```

This is unbearable, and the CPU metric should be either fixed or removed altogether.

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The CPU usage metric in clickhouse-client will be displayed in a better way. Fixes #38756.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by serxa** [comment]
fixes #38756

File: src/Common/EventRateMeter.h [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+#include <base/types.h>
+#include <algorithm>
+#include <cmath>
+#include <cassert>
+
+namespace DB
+{
+
+/// Event count measurement with exponential smoothing intended for computing time derivatives
+class EventRateMeter {
```
Comment (alexey-milovidov) [inline src/Common/EventRateMeter.h:13]: Maybe reuse Common/ExponentialSmoothedCounter.h?

Comment (serxa) [reply src/Common/EventRateMeter.h:13]: Nice, I did not know we have it and it is even better generalised! Let me think how to use it inside EventRateMeter. My implementation is almost the same, but has small advantage at start - it will converge faster due to expression in denominator inside `rate()`. But anyway I think we can combine all that.

Comment (serxa) [reply src/Common/EventRateMeter.h:18]: done

**Review by novikd — APPROVED** [review]
