### PR TITLE
Relocate the binary before other threads are started

### LINKED ISSUE #88539: Performance tests: Startup stuck in `Application: Will remap executable in memory`
Multiple PRs with unrelated changes where the servers fail to be available. The last log line they have is:
```
2025.10.14 16:15:04.761751 [ 735 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2025.10.14 16:15:04.761943 [ 735 ] {} <Information> StatusFile: Writing pid 735 to /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/perf_wd/db0/status
2025.10.14 16:15:05.046845 [ 735 ] {} <Information> Application: Integrity check of the executable successfully passed (checksum: DB6D157FBC364F943C2A46B9C74D1D27)
2025.10.14 16:15:05.046873 [ 735 ] {} <Debug> Application: Will remap executable in memory.
```

Note that we would expect to see something like:
```
2025.10.14 16:43:30.730057 [ 1489 ] {} <Information> Application: Integrity check of the executable successfully passed (checksum: 9B1D6F07ED2448F34BE6DEAD34F630AC)
2025.10.14 16:43:30.730084 [ 1489 ] {} <Debug> Application: Will remap executable in memory.
2025.10.14 16:43:31.015256 [ 1489 ] {} <Debug> Application: The code (395.74 MiB) in memory has been successfully remapped.
2025.10.14 16:43:31.015287 [ 1489 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/perf_wd/left/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Relocate the binary before other threads are started

If the global profiler was on and it run during the relocation of the binary it would crash. We want to keep the global profiler for all threads (except those who opt-out, like async loggers) so we can relocate the binary earlier in the process. The one drawback I see is that the config is not fully read (from keeper for example), but this option is meant only for performance tests and LTO so it seems ok.

Closes https://github.com/ClickHouse/ClickHouse/issues/88539

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

File: programs/server/Server.cpp [hunk 1]
```diff
@@ -1028,9 +1028,53 @@ try
 #endif
 
     Stopwatch startup_watch;
-
     Poco::Logger * log = &logger();
 
+#if defined(OS_LINUX)
+    std::string executable_path = getExecutablePath();
+    /// Remap before creating other threads (like TraceCollector or anything that might collect traces) to prevent crashing when
```
Comment (azat) [inline programs/server/Server.cpp]: >crashing when

when? :)

File: programs/server/Server.cpp [hunk 2]
```diff
@@ -1028,9 +1028,54 @@ try
...
+    /// the code section of the executable is moved while they collect traces
```
Comment (antonio2368) [inline programs/server/Server.cpp]: it's not just collecting traces, but threads shouldn't do anything while remap is running.

**Comment by Algunenano** [comment]
It happened in the left server (which does not have the fix): `left/server.log`
```
.937643 [ 735 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2025.10.15 18:21:09.937687 [ 735 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2025.10.15 18:21:09.937697 [ 735 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2025.10.15 18:21:09.938882 [ 735 ] {} <Information> StatusFile: Writing pid 735 to /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/perf_wd/db0/status
2025.10.15 18:21:10.129220 [ 735 ] {} <Information> Application: Integrity check of the executable successfully passed (checksum: 0710F4AE2371F53B308E3E838B453EEA)
2025.10.15 18:21:10.129253 [ 735 ] {} <Debug> Application: Will remap executable in memory.
```
