### PR TITLE
Collect stack traces from job's scheduling and print along with exception's stack trace.

### LINKED ISSUE #18203: Collect stack traces from the place of thread creation and print along with other stack traces.
**Use case**
Stack trace should looks like this:
```
0. /home/milovidov/work/ClickHouse/build/../contrib/libcxx/include/exception:129: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10462adc in /home/milovidov/work/ClickHouse/build/programs/clickhouse
1. /home/milovidov/work/ClickHouse/build/../src/Common/Exception.cpp:55: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x85c5a8d in /home/milovidov/work/ClickHouse/build/programs/clickhouse
2. DB::(anonymous namespace)::FunctionThrowIf::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xc0c63a1 in /home/milovidov/work/ClickHouse/build/programs/clickhouse

...

Thread TID was created from here:
0. /home/milovidov/work/ClickHouse/build/../contrib/libcxx/include/exception:129: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10462adc in /home/milovidov/work/ClickHouse/build/programs/clickhouse
...

Thread TID was created from here:
0. /home/milovidov/work/ClickHouse/build/../contrib/libcxx/include/exception:129: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10462adc in /home/milovidov/work/ClickHouse/build/programs/clickhouse
...
```

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

closes #18203

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit be17a817929ea7fef4a68ac108f89a65f0e21827 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51349/be17a817929ea7fef4a68ac108f89a65f0e21827/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by yakov-olkhovskiy** [comment]
Current behavior example:
```
ubuntu@ip-172-31-42-195:~/ClickHouse-stack/build_debug$ programs/clickhouse local --stacktrace
ClickHouse local version 23.6.1.1.
ip-172-31-42-195.us-east-2.compute.internal :) select throwIf(number) from numbers_mt(100000000)

SELECT throwIf(number)
FROM numbers_mt(100000000)

Query id: fe785849-ee71-4562-a844-ba83f87e9c62

0 rows in set. Elapsed: 1.189 sec.

Received exception:
Code: 395. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(number :: 0) -> throwIf(number) UInt8 : 1'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO), Stack trace (when copying this message, always include the lines below):

0. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x000000001ae37f42 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
1. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x000000001ae37f0d in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
2. /home/ubuntu/ClickHouse-stack/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x00000000344353e0 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
3. /home/ubuntu/ClickHouse-stack/src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000024589b4e in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
4. /home/ubuntu/ClickHouse-stack/src/Common/Exception.h:61: DB::Exception::Exception(String&&, int, bool) @ 0x000000001ae299ca in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
5. /home/ubuntu/ClickHouse-stack/src/Common/Exception.h:89: DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000001ae29893 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
6. /home/ubuntu/ClickHouse-stack/src/Functions/throwIf.cpp:140: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::(anonymous namespace)::FunctionThrowIf::execute<unsigned long>(DB::IColumn const*, std::optional<String> const&, std::optional<int> const&) const @ 0x00000000224a24e3 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
7. /home/ubuntu/ClickHouse-stack/src/Functions/throwIf.cpp:107: DB::(anonymous namespace)::FunctionThrowIf::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000224a0a56 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
8. /home/ubuntu/ClickHouse-stack/src/Functions/IFunctionAdaptors.h:21: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001ae2bfed in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
9. /home/ubuntu/ClickHouse-stack/src/Functions/IFunction.cpp:247: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000002b513e7a in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
10. /home/ubuntu/ClickHouse-stack/src/Functions/IFunction.cpp:302: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000002b514f06 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
11. /home/ubuntu/ClickHouse-stack/src/Functions/IFunction.cpp:374: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000002b515df5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
12. /home/ubuntu/ClickHouse-stack/src/Interpreters/ExpressionActions.cpp:613: DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) @ 0x000000002c462a51 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
13. /home/ubuntu/ClickHouse-stack/src/Interpreters/ExpressionActions.cpp:730: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x000000002c461e6d in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
14. /home/ubuntu/ClickHouse-stack/src/Processors/Transforms/ExpressionTransform.cpp:23: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x000000002f1e4fc4 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
15. /home/ubuntu/ClickHouse-stack/src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x00000000284e1be2 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
16. /home/ubuntu/ClickHouse-stack/src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x000000002ed2abf2 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
17. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x000000002ed65bc3 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
18. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x000000002ed65900 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
19. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000002ed4a4e1 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
20. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PipelineExecutor.cpp:221: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000002ed4a7f7 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
21. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PipelineExecutor.cpp:343: DB::PipelineExecutor::spawnThreads()::$_0::operator()() const @ 0x000000002ed4b7d8 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
22. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) @ 0x000000002ed4b735 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
23. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) @ 0x000000002ed4b715 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
24. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]() @ 0x000000002ed4b6f5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
25. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000002ed4b6c0 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
26. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x00000000245e37b6 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
27. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x00000000245e2cb5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
28. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:423: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x00000000246ecbc7 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
29. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:180: void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()::operator()() const @ 0x00000000246f7424 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
30. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<void>()()) std::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()&>(void&&) @ 0x00000000246f73f5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
31. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()&, std::tuple<>&>(void&&, std::tuple<>&, std::__tuple_indices<>) @ 0x00000000246f73d9 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse

Job's origin stack trace:
0. /home/ubuntu/ClickHouse-stack/src/Common/StackTrace.cpp:291: StackTrace::tryCapture() @ 0x00000000245c128a in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
1. /home/ubuntu/ClickHouse-stack/src/Common/StackTrace.h:49: StackTrace::StackTrace() @ 0x000000002459c87c in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
2. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.h:140: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::JobWithPriority::JobWithPriority(std::function<void ()>, Priority, DB::OpenTelemetry::TracingContextOnThread const&, bool) @ 0x00000000246ec557 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
3. /home/ubuntu/ClickHouse-stack/contrib/boost/boost/heap/detail/stable_heap.hpp:230: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::JobWithPriority boost::heap::detail::heap_base<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::JobWithPriority, std::less<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::JobWithPriority>, false, unsigned long, false>::make_node<std::function<void ()>, Priority&, DB::OpenTelemetry::TracingContextOnThread const, bool>(std::function<void ()>&&, Priority&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&&) @ 0x00000000246f784b in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
4. /home/ubuntu/ClickHouse-stack/contrib/boost/boost/heap/priority_queue.hpp:260: void boost::heap::priority_queue<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::JobWithPriority, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::emplace<std::function<void ()>, Priority&, DB::OpenTelemetry::TracingContextOnThread const, bool>(std::function<void ()>&&, Priority&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&&) @ 0x00000000246f632d in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
5. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:189: void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool) @ 0x00000000246eaf59 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
6. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:238: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleOrThrowOnError(std::function<void ()>, Priority) @ 0x00000000246ea7f5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
7. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PipelineExecutor.cpp:330: DB::PipelineExecutor::spawnThreads() @ 0x000000002ed4b19b in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
8. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PipelineExecutor.cpp:372: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x000000002ed49776 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
9. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PipelineExecutor.cpp:113: DB::PipelineExecutor::execute(unsigned long) @ 0x000000002ed48de0 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
10. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long) @ 0x000000002ed6ca7a in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
11. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const @ 0x000000002ed6c920 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
12. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x000000002ed6c8b5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
13. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<>) @ 0x000000002ed6c899 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
14. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&) @ 0x000000002ed6c7fd in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
15. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.h:239: ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() @ 0x000000002ed6c702 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
16. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) @ 0x000000002ed6c675 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
17. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) @ 0x000000002ed6c655 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
18. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() @ 0x000000002ed6c635 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
19. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000002ed6c600 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
20. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x00000000245e37b6 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
21. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x00000000245e2cb5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
22. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:423: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x00000000246e9527 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
23. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:180: void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()::operator()() const @ 0x00000000246f1764 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
24. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<void>()()) std::__invoke[abi:v15000]<void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&) @ 0x00000000246f1715 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
25. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/thread:285: void std::__thread_execute[abi:v15000]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(std::tuple<void, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>&, std::__tuple_indices<>) @ 0x00000000246f163d in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
26. /home/ubuntu/ClickHouse-stack/contrib/llvm-project/libcxx/include/thread:295: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x00000000246f1122 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
27. ? @ 0x00007f202aa94b43 in ?
28. ? @ 0x00007f202ab26a00 in ?

Job's origin stack trace:
0. /home/ubuntu/ClickHouse-stack/src/Common/StackTrace.cpp:291: StackTrace::tryCapture() @ 0x00000000245c128a in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
1. /home/ubuntu/ClickHouse-stack/src/Common/StackTrace.h:49: StackTrace::StackTrace() @ 0x000000002459c87c in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
2. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.h:140: ThreadPoolImpl<std::thread>::JobWithPriority::JobWithPriority(std::function<void ()>, Priority, DB::OpenTelemetry::TracingContextOnThread const&, bool) @ 0x00000000246e8dd7 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
3. /home/ubuntu/ClickHouse-stack/contrib/boost/boost/heap/detail/stable_heap.hpp:230: ThreadPoolImpl<std::thread>::JobWithPriority boost::heap::detail::heap_base<ThreadPoolImpl<std::thread>::JobWithPriority, std::less<ThreadPoolImpl<std::thread>::JobWithPriority>, false, unsigned long, false>::make_node<std::function<void ()>, Priority&, DB::OpenTelemetry::TracingContextOnThread const, bool>(std::function<void ()>&&, Priority&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&&) @ 0x00000000246f1b6b in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
4. /home/ubuntu/ClickHouse-stack/contrib/boost/boost/heap/priority_queue.hpp:260: void boost::heap::priority_queue<ThreadPoolImpl<std::thread>::JobWithPriority, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::emplace<std::function<void ()>, Priority&, DB::OpenTelemetry::TracingContextOnThread const, bool>(std::function<void ()>&&, Priority&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&&) @ 0x00000000246f086d in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
5. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:189: void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool) @ 0x00000000246e7719 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
6. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.cpp:250: ThreadPoolImpl<std::thread>::scheduleOrThrow(std::function<void ()>, Priority, unsigned long, bool) @ 0x00000000246e8109 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
7. /home/ubuntu/ClickHouse-stack/src/Common/ThreadPool.h:219: ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) @ 0x000000002ed6b753 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
8. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:114: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long) @ 0x000000002ed6b414 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
9. /home/ubuntu/ClickHouse-stack/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:152: DB::PullingAsyncPipelineExecutor::pull(DB::Block&, unsigned long) @ 0x000000002ed6b849 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
10. /home/ubuntu/ClickHouse-stack/src/Client/LocalConnection.cpp:212: DB::LocalConnection::pullBlock(DB::Block&) @ 0x000000002ebabbf2 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
11. /home/ubuntu/ClickHouse-stack/src/Client/LocalConnection.cpp:369: DB::LocalConnection::pollImpl() @ 0x000000002ebaca31 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
12. /home/ubuntu/ClickHouse-stack/src/Client/LocalConnection.cpp:271: DB::LocalConnection::poll(unsigned long) @ 0x000000002ebabfdb in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
13. /home/ubuntu/ClickHouse-stack/src/Client/ClientBase.cpp:976: DB::ClientBase::receiveResult(std::shared_ptr<DB::IAST>, int, bool) @ 0x000000002eb19e92 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
14. /home/ubuntu/ClickHouse-stack/src/Client/ClientBase.cpp:900: DB::ClientBase::processOrdinaryQuery(String const&, std::shared_ptr<DB::IAST>) @ 0x000000002eb19453 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
15. /home/ubuntu/ClickHouse-stack/src/Client/ClientBase.cpp:1707: DB::ClientBase::processParsedSingleQuery(String const&, String const&, std::shared_ptr<DB::IAST>, std::optional<bool>, bool) @ 0x000000002eb185d3 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
16. /home/ubuntu/ClickHouse-stack/src/Client/ClientBase.cpp:1971: DB::ClientBase::executeMultiQuery(String const&) @ 0x000000002eb20937 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
17. /home/ubuntu/ClickHouse-stack/src/Client/ClientBase.cpp:2116: DB::ClientBase::processQueryText(String const&) @ 0x000000002eb21d96 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
18. /home/ubuntu/ClickHouse-stack/src/Client/ClientBase.cpp:2399: DB::ClientBase::runNonInteractive() @ 0x000000002eb24307 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
19. /home/ubuntu/ClickHouse-stack/programs/local/LocalServer.cpp:497: DB::LocalServer::main(std::vector<String, std::allocator<String>> const&) @ 0x00000000247c625c in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
20. /home/ubuntu/ClickHouse-stack/base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x000000003428c3a5 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
21. /home/ubuntu/ClickHouse-stack/programs/local/LocalServer.cpp:861: mainEntryClickHouseLocal(int, char**) @ 0x00000000247cc469 in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
22. /home/ubuntu/ClickHouse-stack/programs/main.cpp:487: main @ 0x000000001ae18a2a in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
23. ? @ 0x00007f202aa29d90 in ?
24. __libc_start_main @ 0x00007f202aa29e40 in ?
25. _start @ 0x000000001ae185ae in /home/ubuntu/ClickHouse-stack/build_debug/programs/clickhouse
```

File: src/Common/Exception.cpp [hunk 1]
```diff
@@ -185,6 +200,8 @@ Exception::FramePointers Exception::getStackFramePointers() const
     return frame_pointers;
 }
 
+thread_local std::vector<StackTrace::FramePointers> Exception::thread_frame_pointers = {};
```
Comment (alexey-milovidov) [inline src/Common/Exception.cpp:203]: A comment will be helpful.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Can we also add it to Basedaemon (fatal errors handler)?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
It works! https://s3.amazonaws.com/clickhouse-test-reports/51349/cc3d27c0a30e40532541324b100f2584327b5ba3/fuzzer_astfuzzerdebug/report.html

**Comment by alexey-milovidov** [comment]
There are a few slower queries - let's validate if they are related.
Also, let's introduce a query-level setting to enable/disable origin tracking.

**Review by alexey-milovidov — APPROVED** [review]
