### PR TITLE
Check if default DB exists after authorization

### LINKED ISSUE #71097: Client should refuse to connect to a database that does not exist.
**How to reproduce**

```
milovidov@milovidov-pc:~$ clickhouse-client --database upyachka
ClickHouse client version 24.11.1.1.
Connecting to database upyachka at localhost:9000 as user default.
Connected to ClickHouse server version 24.11.1.

Cannot load data for command line suggestions: Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Database upyachka does not exist. (UNKNOWN_DATABASE) (version 24.11.1.1)
milovidov-pc :) Bye.
```

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Check if default DB is present after authorization. Fixes #71097

```
➜  llvm-project git:(llvmorg-19.1.2) clickhouse client --database ddddd
ClickHouse client version 24.9.1.3278 (official build).
Connecting to database ddddd at localhost:9000 as user default.
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Database ddddd does not exist. (UNKNOWN_DATABASE)
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit ab46e9b1794ae864b9c19139d24058573bf9ff11 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71140/ab46e9b1794ae864b9c19139d24058573bf9ff11/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/c82cf25b3e5864bcc153cbe45adb8c6527e1ec6e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Server/TCPHandler.cpp [hunk 1]
```diff
@@ -1671,11 +1673,15 @@ void TCPHandler::receiveHello()
...
         auto cred = SshCredentials(user, signature, prepare_string_for_ssh_validation(user, challenge));
         session->authenticate(cred, getClientAddress(client_info));
+        if (!default_database.empty())
+            DatabaseCatalog::instance().assertDatabaseExists(default_database);
         return;
     }
 #endif
 
     session->authenticate(user, password, getClientAddress(client_info));
+    if (!default_database.empty())
```
Comment (evillique) [inline src/Server/TCPHandler.cpp:1683]: I think it is better to add this check in a single place, for example after `receiveHello();` in `TCPHandler::runImpl()`

**Review by evillique — APPROVED** [review]

**Comment by thevar1able** [comment]
`00653_verification_monotonic_data_load` https://github.com/ClickHouse/ClickHouse/pull/71135
