### PR TITLE
Fix msan crash from 22517

### LINKED ISSUE #22517: ASan report in ExecuteScalarSubqueriesMatcher
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/22475/2952cb296de0145a458d08dcd55365b0165c0248/fuzzer_asan/server.log

**How to reproduce**
```
SELECT x FROM (SELECT dummy AS x, plus(ignore(ignore(ignore(ignore('-922337203.6854775808', ignore(NULL)), ArrLen = 256, ignore(100, Arr.C3, ignore(NULL), (SELECT 10.000100135803223, count(*) FROM system.time_zones) > NULL)))), dummy, 65535) AS dummy ORDER BY ignore(-2) ASC, identity(x) DESC NULLS FIRST) FORMAT Null
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix some fuzzed msan crash. Fixes #22517

### CODE REVIEW

File: src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp [hunk 1]
```diff
@@ -157,18 +157,21 @@ void ExecuteScalarSubqueriesMatcher::visit(const ASTSubquery & subquery, ASTPtr
     if (data.only_analyze || !settings.enable_scalar_subquery_optimization || worthConvertingToLiteral(scalar)
         || !data.getContext()->hasQueryContext())
     {
+        auto alias = subquery.alias;
```
Comment (vdimir) [inline src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:160]: It's unclear how what problem is solved. Don't we copy data at both cases?

Comment (alexey-milovidov) [reply src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:160]: I'm also wondering :)

Is it use after free?

Comment (KochetovNicolai) [reply src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:160]: It may be surprising, but `subquery` and `ast` point to the same object. When we move `std::move(ast)` below (and, likely, destroy), `subquery` points to removed object.

Comment (alexey-milovidov) [reply src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:160]: Let's add a comment...

**Review by alexey-milovidov — APPROVED** [review]
