### PR TITLE
Fix undefined behaviour on NaN comparison in ArgMin/ArgMax

### LINKED ISSUE #77699: AST fuzzer failed in DB::SingleValueDataFixed<double>::getSmallestIndexNotNullIf
Test: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77608&sha=f8f2309ae06bce7408c2c6c45687a540fd8f69de&name_0=PR&name_1=AST%20fuzzer%20%28debug%29

Stack trace: https://pastila.nl/?00154041/d0819739c0674814056b78fd92b68599#QlGfOEAbMUQ4pK9aAfTYQw==

```
2025-03-17 05:36:16	 Thread 720 (Thread 0x7f4f04400640 (LWP 1016) "QueryPipelineEx"):
2025-03-17 05:36:16	 #0  0x00007f521c6b29fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2025-03-17 05:36:16	 No symbol table info available.
2025-03-17 05:36:16	 #1  0x00007f521c65e476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2025-03-17 05:36:16	 No symbol table info available.
2025-03-17 05:36:16	 #2  0x00007f521c6447f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2025-03-17 05:36:16	 No symbol table info available.
2025-03-17 05:36:16	 #3  0x000055bb4e8ef165 in DB::SingleValueDataFixed<double>::getSmallestIndexNotNullIf (this=<optimized out>, column=..., null_map=0x7f4f0d9cab40 "", if_map=0x0, row_begin=<optimized out>, row_end=1) at /build/src/AggregateFunctions/SingleValueData.cpp:499
2025-03-17 05:36:16	         opt = <optimized out>
2025-03-17 05:36:16	         vec = @0x7f50debf17c0: {<COWHelper<DB::IColumnHelper<DB::ColumnVector<double>, DB::ColumnFixedSizeHelper>, DB::ColumnVector<double> >> = {<DB::IColumnHelper<DB::ColumnVector<double>, DB::ColumnFixedSizeHelper>> = {<DB::ColumnFixedSizeHelper> = {<DB::IColumn> = {<COW<DB::IColumn>> = {<boost::sp_adl_block::intrusive_ref_counter<DB::IColumn, boost::sp_adl_block::thread_safe_counter>> = {m_ref_counter = {value_ = 2}}, <No data fields>}, _vptr$IColumn = 0x55bb5d846210 <vtable for DB::ColumnVector<double>+16>}, <No data fields>}, <No data fields>}, <No data fields>}, data = {<DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>> = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, <Allocator<false, false>> = {static clear_memory = 127}, static pad_right = 64, static pad_left = 64, static null = <optimized out>, c_start = 0x7f4f0fd14840 "", c_end = 0x7f4f0fd14848 "", c_end_of_storage = 0x7f4f0fd148c0 "", mprotected = false}, <No data fields>}}
2025-03-17 05:36:16	         vec_data = @0x7f50debf17d0: {<DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>> = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, <Allocator<false, false>> = {static clear_memory = 127}, static pad_right = 64, static pad_left = 64, static null = <optimized out>, c_start = 0x7f4f0fd14840 "", c_end = 0x7f4f0fd14848 "", c_end_of_storage = 0x7f4f0fd148c0 "", mprotected = false}, <No data fields>}
2025-03-17 05:36:16	 #4  0x000055bb4e9cfa5b in DB::(anonymous namespace)::AggregateFunctionArgMinMax<DB::(anonymous namespace)::AggregateFunctionArgMinMaxDataGeneric<DB::SingleValueDataFixed<double> >, true>::addBatchSinglePlaceNotNull (this=<optimized out>, row_begin=139977350389520, row_end=139977544517696, place=0x7f4f0fc44008 "0\204Q]\273U", columns=0x7f4f043f2110, null_map=0x7f4f0d9cab40 "", arena=0x7f50d5d6bfa0, if_argument_pos=-1) at /build/src/AggregateFunctions/AggregateFunctionsArgMinArgMax.cpp:201
2025-03-17 05:36:16	         idx = {<std::__1::__optional_move_assign_base<unsigned long, true>> = {<std::__1::__optional_copy_assign_base<unsigned long, true>> = {<std::__1::__optional_move_base<unsigned long, true>> = {<std::__1::__optional_copy_base<unsigned long, true>> = {<std::__1::__optional_storage_base<unsigned long, false>> = {<std::__1::__optional_destruct_base<unsigned long, true>> = {{__null_state_ = 0 '\000', __val_ = <optimized out>}, __engaged_ = false}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2025-03-17 05:36:16	 #5  0x000055bb4f6afafa in DB::AggregateFunctionNullVariadic<true, true>::addBatchSinglePlace (this=0x7f4eb5d6c718, row_begin=<optimized out>, row_end=6, place=<optimized out>, columns=<optimized out>, arena=<optimized out>, if_argument_pos=<optimized out>) at /build/src/AggregateFunctions/Combinators/AggregateFunctionNull.h:580
2025-03-17 05:36:16	         nullable_filters = {__begin_ = 0x7f4f0fc23720, __end_ = 0x7f4f0fc23728, __end_cap_ = {<std::__1::__compressed_pair_elem<char8_t const**, 0, false>> = {__value_ = 0x7f4f0fc23728}, <std::__1::__compressed_pair_elem<std::__1::allocator<char8_t const*>, 1, true>> = {<std::__1::allocator<char8_t const*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char8_t const*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2025-03-17 05:36:16	         nested_columns = {storage_ = {static kOptimalInlinedSize = 5, metadata_ = {<absl::container_internal::internal_compressed_tuple::CompressedTupleImpl<absl::container_internal::CompressedTuple<std::__1::allocator<DB::IColumn const*>, unsigned long>, std::__1::integer_sequence<unsigned long, 0ul, 1ul>, true>> = {<absl::container_internal::internal_compressed_tuple::uses_inheritance> = {<No data fields>}, <absl::container_internal::internal_compressed_tuple::Storage<std::__1::allocator<DB::IColumn const*>, 0ul, true>> = {<std::__1::allocator<DB::IColumn const*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::IColumn const*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <absl::container_internal::internal_compressed_tuple::Storage<unsigned long, 1ul, false>> = {value = 4}, <No data fields>}, <No data fields>}, data_ = {allocated = {allocated_data = 0x7f4f0e8ffe80, allocated_capacity = 139985311176640}, inlined = {inlined_data = "\200\376\217\016O\177\000\000\300\027\277\336P\177\000\000\001\000\000\000\000\000\000\000\374\225\246M\273U\000\000(7\302\017O\177\000"}}}}
2025-03-17 05:36:16	         final_flags_ptr = 0x7f4f0d9cab40 ""
2025-03-17 05:36:16	         final_flags = {__ptr_ = {<std::__1::__compressed_pair_elem<char8_t*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<char8_t []>, 1, true>> = {<std::__1::default_delete<char8_t []>> = {<No data fields>}, <No data fields>}, <No data fields>}}
2025-03-17 05:36:16	         found_one = <optimized out>

```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix undefined behaviour on NaN comparison in ArgMin/ArgMax

I could not reproduce a bad behaviour, but it was pure luck as UNREACHABLE was helping us greatly. Marking it as critical because of it.

Closes https://github.com/ClickHouse/ClickHouse/issues/77699

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by thevar1able — APPROVED** [review]

File: src/AggregateFunctions/SingleValueData.cpp [hunk 1]
```diff
@@ -466,22 +468,40 @@ std::optional<size_t> SingleValueDataFixed<T>::getSmallestIndexNotNullIf(
...
-                return opt;
+                return std::nullopt;
+            T smallest = *opt;
             for (size_t i = row_begin; i < row_end; i++)
             {
-                if (!null_map[i] && vec_data[i] == *opt)
-                    return {i};
+                if constexpr (is_floating_point<T>)
+                {
+                    if (!null_map[i] && std::memcmp(&vec_data[i], &smallest, sizeof(T)) == 0)
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/SingleValueData.cpp:477]: How does `std::memcmp(&vec_data[i], &smallest, sizeof(T)) == 0` work with BFloat16? I'm not sure that it is POD because there were some fixes with that regard recently: https://github.com/ClickHouse/ClickHouse/pull/77290

Comment (alexey-milovidov) [reply src/AggregateFunctions/SingleValueData.cpp:477]: It works ok.

Comment (Algunenano) [reply src/AggregateFunctions/SingleValueData.cpp:477]: I'll add a static_assert to confirm
