### PR TITLE
Fix Nullable String to Enum conversion.

### LINKED ISSUE #14435: Hot to fix "Last column should be ColumnNullable"
Clickhouse Version 20.7.2.30
Interface: HTTP (in case that matters)

We are using a column of type Enum8 to store data. The data is imported from a file to a buffer table and then bulk inserted into the final table. In the sample code, `t_enum` is the final table and `t_source` is the temporary table.

```sql
CREATE TABLE t_enum
(
    x Enum8('hello' = 1, 'world' = 2)
)
ENGINE = TinyLog;

CREATE TABLE t_source
(
    x Nullable(String)
)
ENGINE = TinyLog;

INSERT INTO t_source (x) VALUES ('hello');

INSERT INTO t_enum(x)
SELECT x from t_source
WHERE x in ('hello', 'world')
```

During Bulk Insert (last statement) the following error occurs: `e.displayText() = DB::Exception: Last column should be ColumnNullable: while converting source column x to destination column x (version 20.7.2.30 (official build))`

The error can be fixed by making `t_enum.x` a `Nullable(Enum8())`. But our application expects the field to not be null. Adding a check for `x is not null` in the insert statement does not help.

How do I fix the issue?

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix a bug when converting Nullable String to Enum. Introduced by https://github.com/ClickHouse/ClickHouse/pull/12745 . This fixes https://github.com/ClickHouse/ClickHouse/issues/14435 .

cc @azat . `nullable_col` can be missing when converting to non-nullable and there is no need to refer to the original column.

### CODE REVIEW

File: tests/queries/0_stateless/01490_nullable_string_to_enum.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+CREATE TABLE t_enum(x Enum8('hello' = 1, 'world' = 2)) ENGINE = TinyLog;
+CREATE TABLE t_source(x Nullable(String)) ENGINE = TinyLog;
+
+INSERT INTO t_source (x) VALUES ('hello');
+INSERT INTO t_enum(x) SELECT x from t_source WHERE x in ('hello', 'world');
+SELECT * FROM t_enum;
+
+DROP TABLE IF EXISTS t_enum;
+DROP TABLE IF EXISTS t_source;
```
Comment (azat) [inline tests/queries/0_stateless/01490_nullable_string_to_enum.sql:12]: Can this test just use `CAST`? i.e.

```sql
SELECT CAST(CAST('Hello' AS Nullable(String)) AS Enum8('Hello' = 1));
```

Also maybe it worth just add one more case to `01402_cast_nullable_string_to_enum`?
Since there are also some other related cases.

Comment (amosbird) [reply tests/queries/0_stateless/01490_nullable_string_to_enum.sql:12]: Your test case looks cleaner. I'll add it while keeping the old one. I didn't find `01402_cast_nullable_string_to_enum` and yeah, these tests should be placed together.

**Review by alexey-milovidov — APPROVED** [review]
LGTM.

The test is also Ok for me.

**Comment by alexey-milovidov** [comment]
Performance test - @4ertus2.
