### PR TITLE
Fix corner cases in vertical merges with ReplacingMergeTree

### LINKED ISSUE #23365: Vertical merges fails on granule/block size check
**Describe the bug**
Vertical merges seems to be fed with a granule bigger by 1 rows than granularity size, and fails with the following error : 
```
2021.04.20 09:59:56.027482 [ 10195 ] {} <Error> database.table_local (813d322c-c51c-47f4-baa7-6c0b90bbab9e): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Incomplete granules are not allowed while blocks are granules size. Mark number 4665 (rows 4096), rows written in last mark 0, rows to write in last mark from block 1 (from row 4096), total marks currently 4666, Stack trace (when copying this message, always include the lines below):#012#0120. DB::Exception::Exception<unsigned long&, unsigned long, unsigned long&, unsigned long&, unsigned long&, unsigned long>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&, unsigned long&&, unsigned long&, unsigned long&, unsigned long&, unsigned long&&) @ 0xfa5c975 in /usr/bin/clickhouse#0121. DB::MergeTreeDataPartWriterWide::shiftCurrentMark(std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule> > const&) @ 0xfa5c863 in /usr/bin/clickhouse#0122. DB::MergeTreeDataPartWriterWide::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0xfa5d31f in /usr/bin/clickhouse#0123. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xfa153c9 in /usr/bin/clickhouse#0124. DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) @ 0xf7d6917 in /usr/bin/clickhouse#0125. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xf7cb862 in /usr/bin/clickhouse#0126. ? @ 0xf83cd7f in /usr/bin/clickhouse#0127. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xfb7d0f8 in /usr/bin/clickhouse#0128. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0xf7f514d in /usr/bin/clickhouse#0129. ? @ 0xf963667 in /usr/bin/clickhouse#01210. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x89916ff in /usr/bin/clickhouse#01211. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x899367f in /usr/bin/clickhouse#01212. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x898edef in /usr/bin/clickhouse#01213. ? @ 0x8992733 in /usr/bin/clickhouse#01214. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so#01215. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so#012 (version 21.3.4.25)
``` 

The table engine is ReplicatedReplacingMergeTree
with  SETTINGS storage_policy = 'jbod_policy_1', index_granularity = 4096, merge_max_block_size = 4096, index_granularity_bytes = 41943040 

The error is clearly deterministic, and will fail to merge in a loop. 
**Does it reproduce on recent release?**
21.3.4.25 

The merge information : 
``` elapsed:                     32.740309772
progress:                    0.17199233946890857
num_parts:                   6
source_part_names:           ['31_975_975_0','31_976_976_0','31_977_977_0','31_978_978_0','31_979_979_0','31_980_980_0']
result_part_name:            31_975_980_1
source_part_paths:           ['/disk13/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_975_975_0/','/disk7/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_976_976_0/','/disk4/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_977_977_0/','/disk5/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_978_978_0/','/disk15/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_979_979_0/','/disk10/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_980_980_0/']
result_part_path:            /disk5/clickhouse/store/813/813d322c-c51c-47f4-baa7-6c0b90bbab9e/31_975_980_1/
partition_id:                31
is_mutation:                 0
total_size_bytes_compressed: 1286881212
total_size_marks:            4672
bytes_read_uncompressed:     1955818184
rows_read:                   8898560
bytes_written_uncompressed:  1947119248
rows_written:                8857600
columns_written:             0
memory_usage:                79808173
thread_id:                   9976
merge_type:                  REGULAR
merge_algorithm:             Vertical
```

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix corner cases in vertical merges with `ReplacingMergeTree`. In rare cases they could lead to fails of merges with exceptions like `Incomplete granules are not allowed while blocks are granules size`.

Fixes #23365.

### CODE REVIEW

File: src/Processors/Merges/Algorithms/ReplacingSortedAlgorithm.cpp [hunk 1]
```diff
@@ -93,6 +93,10 @@ IMergingAlgorithm::Status ReplacingSortedAlgorithm::merge()
         }
     }
 
+    /// If have enough rows, return block, because it prohibited to overflow requested number of rows.
+    if (merged_data.hasEnoughRows())
+        return Status(merged_data.pull());
+
```
Comment (CurtizJ) [inline src/Processors/Merges/Algorithms/ReplacingSortedAlgorithm.cpp:99]: This fixes `Incomplete granules are not allowed while blocks are granules size`.

File: src/DataStreams/ColumnGathererStream.cpp [hunk 2]
```diff
@@ -53,7 +53,7 @@ ColumnGathererStream::ColumnGathererStream(
 Block ColumnGathererStream::readImpl()
 {
     /// Special case: single source and there are no skipped rows
-    if (children.size() == 1 && row_sources_buf.eof())
+    if (children.size() == 1 && row_sources_buf.eof() && !source_to_fully_copy)
```
Comment (CurtizJ) [inline src/DataStreams/ColumnGathererStream.cpp:56]: This fixes `Written 8191 elements of column value, but 8192 rows of PK columns.`

File: tests/queries/0_stateless/00926_adaptive_index_granularity_replacing_merge_tree.reference [hunk 3]
```diff
@@ -1,7 +1,7 @@
 4
 4
 8
-7
+8
```
Comment (CurtizJ) [inline tests/queries/0_stateless/00926_adaptive_index_granularity_replacing_merge_tree.reference:4]: Change of test is ok, because it checks number of written marks. Actually it should be 8. Horizontal merge also creates 8 marks in that case.

File: tests/queries/0_stateless/01825_replacing_vertical_merge.sql [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+DROP TABLE IF EXISTS replacing_table;
+
+CREATE TABLE replacing_table (a UInt32, b UInt32, c UInt32)
+ENGINE = ReplacingMergeTree ORDER BY a
+SETTINGS vertical_merge_algorithm_min_rows_to_activate = 1,
+    vertical_merge_algorithm_min_columns_to_activate = 1,
+    index_granularity = 16,
+    min_bytes_for_wide_part = 0,
+    merge_max_block_size = 16;
```
Comment (akuzm) [inline tests/queries/0_stateless/01825_replacing_vertical_merge.sql:11]: Should it also have `SYSTEM STOP MERGES replacing_table` here? I'm not sure if the parts from the next two inserts can be merged in background...

Comment (CurtizJ) [reply tests/queries/0_stateless/01825_replacing_vertical_merge.sql:11]: Yes, we can add it to be sure.

**Review by alexey-milovidov — APPROVED** [review]
