### PR TITLE
Fix logical error in cross join reordering

### LINKED ISSUE #89409: LOGICAL_ERROR "Join restriction violated"
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89380&sha=c6474d13bdc68e14314f66bc8c7fa1dd476051b0&name_0=PR&name_1=Upgrade%20check%20%28amd_tsan%29&name_1=Upgrade%20check%20%28amd_tsan%29

```
[ 52158 ] {b080c9dd-9d1f-4439-a408-86a6f9fbc054} <Fatal> : Logical error: \'Join restriction violated\'.
 [ 52158 ] {b080c9dd-9d1f-4439-a408-86a6f9fbc054} <Fatal> : Stack trace (when copying this message, always include the lines below):
 [ 4923 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 4923 ] {} <Fatal> BaseDaemon: (version 25.10.1.3832 (official build), build id: 45E84B04E418D6507C86CB91B5011CB334F3E8F3, git hash: f95c1af632a1c4fb9c69a501d05ae04a393b8f81, architecture: x86_64) (from thread 52158) Received signal 6
 [ 4923 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 4923 ] {} <Fatal> BaseDaemon: 
 [ 4923 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f86feb259fd 0x00007f86fead1476 0x00007f86feab77f3 0x0000000013c3bbbf 0x0000000013c3cb7f 0x000000000c8902ce 0x000000000c88fd80 0x000000000c8a012b 0x000000001abeb61d 0x000000001abee4a0 0x000000001abd5253 0x000000001abd3e0f 0x000000001abde8df 0x000000001ab85966 0x000000001aa77d6e 0x000000001aa77005 0x0000000018938999 0x000000001893845e 0x0000000018d0de04 0x0000000018d07c33 0x000000001a46c6f7 0x000000001a48ec99 0x000000001f54aa87 0x000000001f54af19 0x000000001f5116c7 0x000000001f50fac1 0x00007f86feb23ac3 0x00007f86febb58c0
 [ 4923 ] {} <Fatal> BaseDaemon: ########################################
 [ 4923 ] {} <Fatal> BaseDaemon: (version 25.10.1.3832 (official build), build id: 45E84B04E418D6507C86CB91B5011CB334F3E8F3, git hash: f95c1af632a1c4fb9c69a501d05ae04a393b8f81) (from thread 52158) (query_id: b080c9dd-9d1f-4439-a408-86a6f9fbc054) (query: SELECT *
 [ 4923 ] {} <Fatal> BaseDaemon: 
 [ 4923 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f86feb259fd 0x00007f86fead1476 0x00007f86feab77f3 0x0000000013c3bbbf 0x0000000013c3cb7f 0x000000000c8902ce 0x000000000c88fd80 0x000000000c8a012b 0x000000001abeb61d 0x000000001abee4a0 0x000000001abd5253 0x000000001abd3e0f 0x000000001abde8df 0x000000001ab85966 0x000000001aa77d6e 0x000000001aa77005 0x0000000018938999 0x000000001893845e 0x0000000018d0de04 0x0000000018d07c33 0x000000001a46c6f7 0x000000001a48ec99 0x000000001f54aa87 0x000000001f54af19 0x000000001f5116c7 0x000000001f50fac1 0x00007f86feb23ac3 0x00007f86febb58c0
 [ 4923 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00000000000969fd
 [ 4923 ] {} <Fatal> BaseDaemon: 3. ? @ 0x0000000000042476
 [ 4923 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00000000000287f3
 [ 4923 ] {} <Fatal> BaseDaemon: 5. ./ci/tmp/build/./src/Common/Exception.cpp:52: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x0000000013c3bbbf
 [ 4923 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./ci/tmp/build/./src/Common/Exception.cpp:85: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&)
 [ 4923 ] {} <Fatal> BaseDaemon: 6. ./ci/tmp/build/./src/Common/Exception.cpp:136: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013c3cb7f
 [ 4923 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c8902ce
 [ 4923 ] {} <Fatal> BaseDaemon: 8. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c88fd80
 [ 4923 ] {} <Fatal> BaseDaemon: 9. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000c8a012b
 [ 4923 ] {} <Fatal> BaseDaemon: 10. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/joinOrder.cpp:316: DB::JoinOrderOptimizer::solveGreedy() @ 0x000000001abeb61d
 [ 4923 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/joinOrder.cpp:195: DB::JoinOrderOptimizer::solve()
 [ 4923 ] {} <Fatal> BaseDaemon: 11. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/joinOrder.cpp:406: DB::optimizeJoinOrder(DB::QueryGraph) @ 0x000000001abee4a0
 [ 4923 ] {} <Fatal> BaseDaemon: 12. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeJoin.cpp:752: DB::QueryPlanOptimizations::chooseJoinOrder(DB::QueryPlanOptimizations::QueryGraphBuilder, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::JoinStrictness) @ 0x000000001abd5253
 [ 4923 ] {} <Fatal> BaseDaemon: 13. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeJoin.cpp:1103: DB::QueryPlanOptimizations::optimizeJoinLogicalImpl(DB::JoinStepLogical*, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlanOptimizationSettings const&) @ 0x000000001abd3e0f
 [ 4923 ] {} <Fatal> BaseDaemon: 14. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeJoin.cpp:1068: DB::QueryPlanOptimizations::optimizeJoinLogical(DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlanOptimizationSettings const&) @ 0x000000001abde8df
 [ 4923 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:224: operator()<DB::QueryPlan::Node>
 [ 4923 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:138: void DB::QueryPlanOptimizations::traverseQueryPlan<DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_2, DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_3>(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>>&, DB::QueryPlan::Node&, DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_2&&, DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_3&&)
 [ 4923 ] {} <Fatal> BaseDaemon: 15. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:221: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&) @ 0x000000001ab85966
 [ 4923 ] {} <Fatal> BaseDaemon: 16. ./ci/tmp/build/./src/Processors/QueryPlan/QueryPlan.cpp:506: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001aa77d6e
 [ 4923 ] {} <Fatal> BaseDaemon: 17. ./ci/tmp/build/./src/Processors/QueryPlan/QueryPlan.cpp:180: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001aa77005
 [ 4923 ] {} <Fatal> BaseDaemon: 18. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x0000000018938999
 [ 4923 ] {} <Fatal> BaseDaemon: 19. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001893845e
 [ 4923 ] {} <Fatal> BaseDaemon: 20. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1603: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x0000000018d0de04
 [ 4923 ] {} <Fatal> BaseDaemon: 21. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018d07c33
 [ 4923 ] {} <Fatal> BaseDaemon: 22. ./ci/tmp/build/./src/Server/TCPHandler.cpp:744: DB::TCPHandler::runImpl() @ 0x000000001a46c6f7
 [ 4923 ] {} <Fatal> BaseDaemon: 23. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2836: DB::TCPHandler::run() @ 0x000000001a48ec99
 [ 4923 ] {} <Fatal> BaseDaemon: 24. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000001f54aa87
 [ 4923 ] {} <Fatal> BaseDaemon: 25. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000001f54af19
 [ 4923 ] {} <Fatal> BaseDaemon: 26. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000001f5116c7
 [ 4923 ] {} <Fatal> BaseDaemon: 27. ./base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001f50fac1
 [ 4923 ] {} <Fatal> BaseDaemon: 28. ? @ 0x0000000000094ac3
 [ 4923 ] {} <Fatal> BaseDaemon: 29. ? @ 0x00000000001268c0
 [ 4923 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: D2257C9B518D9C600C5C2E86DADFFBCB)
 [ 4923 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
 [ 4923 ] {} <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 2161155, max_compress_block_size = 2162678, max_block_size = 74232, min_external_table_block_size_bytes = 1, max_joined_block_size_rows = 88489, joined_block_split_single_row = true, max_insert_threads = 1, max_threads = 2, max_parsing_threads = 1, max_read_buffer_size = 557212, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, use_hedged_requests = false, idle_connection_timeout = 36000, s3_max_get_rps = 1000000, s3_max_get_burst = 2000000, s3_max_put_rps = 1000000, s3_max_put_burst = 2000000, s3_check_objects_after_upload = true, use_uncompressed_cache = true, max_remote_read_network_bandwidth = 1000000000000, max_remote_write_network_bandwidth = 1000000000000, max_local_read_bandwidth = 1000000000000, max_local_write_bandwidth = 1000000000000, stream_like_engine_allow_direct_select = true, enable_multiple_prewhere_read_steps = false, replication_wait_for_inactive_replica_timeout = 30, compile_expressions = false, min_count_to_compile_expression = 0, min_count_to_compile_aggregate_expression = 0, min_count_to_compile_sort_description = 0, group_by_two_level_threshold = 492846, group_by_two_level_threshold_bytes = 1, enable_memory_bound_merging_of_aggregation_results = false, allow_nonconst_timezone_arguments = true, input_format_parallel_parsing = false, min_chunk_bytes_for_parallel_parsing = 14577429, output_format_parallel_formatting = false, merge_tree_coarse_index_granularity = 17, min_bytes_to_use_direct_io = 10737418240, min_bytes_to_use_mmap_io = 1, use_skip_indexes_if_final = false, use_skip_indexes_if_final_exact_mode = false, log_queries = true, insert_quorum_timeout = 60000, table_function_remote_max_addresses = 200, merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0.23000000417232513, http_response_buffer_size = 9482978, fsync_metadata = true, join_use_nulls = true, join_output_by_rowlist_perkey_rows_threshold = 370, query_plan_optimize_join_order_limit = 55, http_send_timeout = 60., http_receive_timeout = 60., use_index_for_in_with_subqueries_max_values = 1000000000, opentelemetry_start_trace_probability = 0.10000000149011612, enable_vertical_final = false, max_rows_to_read = 20000000, max_bytes_to_read = 1000000000000, max_bytes_to_read_leaf = 1000000000000, max_rows_to_group_by = 10000000000, max_bytes_before_external_group_by = 10737418240, max_bytes_ratio_before_external_group_by = 0., max_rows_to_sort = 10000000000, max_bytes_to_sort = 10000000000, prefer_external_sort_block_bytes = 0, max_bytes_ratio_before_external_sort = 0., max_bytes_before_remerge_sort = 2728215322, max_result_rows = 1000000000, max_result_bytes = 1000000000, max_execution_time = 60., max_execution_speed = 100000000000, max_execution_speed_bytes = 10000000000000, timeout_before_checking_execution_speed = 300., max_estimated_execution_time = 600., max_columns_to_read = 20000, max_temporary_columns = 
 [ 4921 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 52158 ] {b080c9dd-9d1f-4439-a408-86a6f9fbc054} <Fatal> : Logical error: \'Join restriction violated\'.
 [ 52158 ] {b080c9dd-9d1f-4439-a408-86a6f9fbc054} <Fatal> : Stack trace (when copying this message, always include the lines below):
 [ 4923 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 4923 ] {} <Fatal> BaseDaemon: (version 25.10.1.3832 (official build), build id: 45E84B04E418D6507C86CB91B5011CB334F3E8F3, git hash: f95c1af632a1c4fb9c69a501d05ae04a393b8f81, architecture: x86_64) (from thread 52158) Received signal 6
 [ 4923 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 4923 ] {} <Fatal> BaseDaemon: 
 [ 4923 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f86feb259fd 0x00007f86fead1476 0x00007f86feab77f3 0x0000000013c3bbbf 0x0000000013c3cb7f 0x000000000c8902ce 0x000000000c88fd80 0x000000000c8a012b 0x000000001abeb61d 0x000000001abee4a0 0x000000001abd5253 0x000000001abd3e0f 0x000000001abde8df 0x000000001ab85966 0x000000001aa77d6e 0x000000001aa77005 0x0000000018938999 0x000000001893845e 0x0000000018d0de04 0x0000000018d07c33 0x000000001a46c6f7 0x000000001a48ec99 0x000000001f54aa87 0x000000001f54af19 0x000000001f5116c7 0x000000001f50fac1 0x00007f86feb23ac3 0x00007f86febb58c0
 [ 4923 ] {} <Fatal> BaseDaemon: ########################################
 [ 4923 ] {} <Fatal> BaseDaemon: (version 25.10.1.3832 (official build), build id: 45E84B04E418D6507C86CB91B5011CB334F3E8F3, git hash: f95c1af632a1c4fb9c69a501d05ae04a393b8f81) (from thread 52158) (query_id: b080c9dd-9d1f-4439-a408-86a6f9fbc054) (query: SELECT *
 [ 4923 ] {} <Fatal> BaseDaemon: 
 [ 4923 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f86feb259fd 0x00007f86fead1476 0x00007f86feab77f3 0x0000000013c3bbbf 0x0000000013c3cb7f 0x000000000c8902ce 0x000000000c88fd80 0x000000000c8a012b 0x000000001abeb61d 0x000000001abee4a0 0x000000001abd5253 0x000000001abd3e0f 0x000000001abde8df 0x000000001ab85966 0x000000001aa77d6e 0x000000001aa77005 0x0000000018938999 0x000000001893845e 0x0000000018d0de04 0x0000000018d07c33 0x000000001a46c6f7 0x000000001a48ec99 0x000000001f54aa87 0x000000001f54af19 0x000000001f5116c7 0x000000001f50fac1 0x00007f86feb23ac3 0x00007f86febb58c0
 [ 4923 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00000000000969fd
 [ 4923 ] {} <Fatal> BaseDaemon: 3. ? @ 0x0000000000042476
 [ 4923 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00000000000287f3
 [ 4923 ] {} <Fatal> BaseDaemon: 5. ./ci/tmp/build/./src/Common/Exception.cpp:52: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x0000000013c3bbbf
 [ 4923 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./ci/tmp/build/./src/Common/Exception.cpp:85: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&)
 [ 4923 ] {} <Fatal> BaseDaemon: 6. ./ci/tmp/build/./src/Common/Exception.cpp:136: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013c3cb7f
 [ 4923 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c8902ce
 [ 4923 ] {} <Fatal> BaseDaemon: 8. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c88fd80
 [ 4923 ] {} <Fatal> BaseDaemon: 9. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000c8a012b
 [ 4923 ] {} <Fatal> BaseDaemon: 10. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/joinOrder.cpp:316: DB::JoinOrderOptimizer::solveGreedy() @ 0x000000001abeb61d
 [ 4923 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/joinOrder.cpp:195: DB::JoinOrderOptimizer::solve()
 [ 4923 ] {} <Fatal> BaseDaemon: 11. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/joinOrder.cpp:406: DB::optimizeJoinOrder(DB::QueryGraph) @ 0x000000001abee4a0
 [ 4923 ] {} <Fatal> BaseDaemon: 12. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeJoin.cpp:752: DB::QueryPlanOptimizations::chooseJoinOrder(DB::QueryPlanOptimizations::QueryGraphBuilder, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::JoinStrictness) @ 0x000000001abd5253
 [ 4923 ] {} <Fatal> BaseDaemon: 13. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeJoin.cpp:1103: DB::QueryPlanOptimizations::optimizeJoinLogicalImpl(DB::JoinStepLogical*, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlanOptimizationSettings const&) @ 0x000000001abd3e0f
 [ 4923 ] {} <Fatal> BaseDaemon: 14. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeJoin.cpp:1068: DB::QueryPlanOptimizations::optimizeJoinLogical(DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlanOptimizationSettings const&) @ 0x000000001abde8df
 [ 4923 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:224: operator()<DB::QueryPlan::Node>
 [ 4923 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:138: void DB::QueryPlanOptimizations::traverseQueryPlan<DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_2, DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_3>(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>>&, DB::QueryPlan::Node&, DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_2&&, DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&)::$_3&&)
 [ 4923 ] {} <Fatal> BaseDaemon: 15. ./ci/tmp/build/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:221: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&) @ 0x000000001ab85966
 [ 4923 ] {} <Fatal> BaseDaemon: 16. ./ci/tmp/build/./src/Processors/QueryPlan/QueryPlan.cpp:506: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001aa77d6e
 [ 4923 ] {} <Fatal> BaseDaemon: 17. ./ci/tmp/build/./src/Processors/QueryPlan/QueryPlan.cpp:180: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001aa77005
 [ 4923 ] {} <Fatal> BaseDaemon: 18. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x0000000018938999
 [ 4923 ] {} <Fatal> BaseDaemon: 19. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001893845e
 [ 4923 ] {} <Fatal> BaseDaemon: 20. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1603: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x0000000018d0de04
 [ 4923 ] {} <Fatal> BaseDaemon: 21. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018d07c33
 [ 4923 ] {} <Fatal> BaseDaemon: 22. ./ci/tmp/build/./src/Server/TCPHandler.cpp:744: DB::TCPHandler::runImpl() @ 0x000000001a46c6f7
 [ 4923 ] {} <Fatal> BaseDaemon: 23. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2836: DB::TCPHandler::run() @ 0x000000001a48ec99
 [ 4923 ] {} <Fatal> BaseDaemon: 24. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000001f54aa87
 [ 4923 ] {} <Fatal> BaseDaemon: 25. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000001f54af19
 [ 4923 ] {} <Fatal> BaseDaemon: 26. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000001f5116c7
 [ 4923 ] {} <Fatal> BaseDaemon: 27. ./base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001f50fac1
 [ 4923 ] {} <Fatal> BaseDaemon: 28. ? @ 0x0000000000094ac3
 [ 4923 ] {} <Fatal> BaseDaemon: 29. ? @ 0x00000000001268c0
 [ 4923 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: D2257C9B518D9C600C5C2E86DADFFBCB)
 [ 4923 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
 [ 4923 ] {} <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 2161155, max_compress_block_size = 2162678, max_block_size = 74232, min_external_table_block_size_bytes = 1, max_joined_block_size_rows = 88489, joined_block_split_single_row = true, max_insert_threads = 1, max_threads = 2, max_parsing_threads = 1, max_read_buffer_size = 557212, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, use_hedged_requests = false, idle_connection_timeout = 36000, s3_max_get_rps = 1000000, s3_max_get_burst = 2000000, s3_max_put_rps = 1000000, s3_max_put_burst = 2000000, s3_check_objects_after_upload = true, use_uncompressed_cache = true, max_remote_read_network_bandwidth = 1000000000000, max_remote_write_network_bandwidth = 1000000000000, max_local_read_bandwidth = 1000000000000, max_local_write_bandwidth = 1000000000000, stream_like_engine_allow_direct_select = true, enable_multiple_prewhere_read_steps = false, replication_wait_for_inactive_replica_timeout = 30, compile_expressions = false, min_count_to_compile_expression = 0, min_count_to_compile_aggregate_expression = 0, min_count_to_compile_sort_description = 0, group_by_two_level_threshold = 492846, group_by_two_level_threshold_bytes = 1, enable_memory_bound_merging_of_aggregation_results = false, allow_nonconst_timezone_arguments = true, input_format_parallel_parsing = false, min_chunk_bytes_for_parallel_parsing = 14577429, output_format_parallel_formatting = false, merge_tree_coarse_index_granularity = 17, min_bytes_to_use_direct_io = 10737418240, min_bytes_to_use_mmap_io = 1, use_skip_indexes_if_final = false, use_skip_indexes_if_final_exact_mode = false, log_queries = true, insert_quorum_timeout = 60000, table_function_remote_max_addresses = 200, merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0.23000000417232513, http_response_buffer_size = 9482978, fsync_metadata = true, join_use_nulls = true, join_output_by_rowlist_perkey_rows_threshold = 370, query_plan_optimize_join_order_limit = 55, http_send_timeout = 60., http_receive_timeout = 60., use_index_for_in_with_subqueries_max_values = 1000000000, opentelemetry_start_trace_probability = 0.10000000149011612, enable_vertical_final = false, max_rows_to_read = 20000000, max_bytes_to_read = 1000000000000, max_bytes_to_read_leaf = 1000000000000, max_rows_to_group_by = 10000000000, max_bytes_before_external_group_by = 10737418240, max_bytes_ratio_before_external_group_by = 0., max_rows_to_sort = 10000000000, max_bytes_to_sort = 10000000000, prefer_external_sort_block_bytes = 0, max_bytes_ratio_before_external_sort = 0., max_bytes_before_remerge_sort = 2728215322, max_result_rows = 1000000000, max_result_bytes = 1000000000, max_execution_time = 60., max_execution_speed = 100000000000, max_execution_speed_bytes = 10000000000000, timeout_before_checking_execution_speed = 300., max_estimated_execution_time = 600., max_columns_to_read = 20000, max_temporary_columns = 
 [ 4921 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

* Fix logical error in cross join reordering when query_plan_optimize_join_order_limit > 1, Close https://github.com/ClickHouse/ClickHouse/issues/89409

### Details

Followup for https://github.com/ClickHouse/ClickHouse/pull/88151

### CODE REVIEW

**Review by davenger — APPROVED** [review]

**Comment by devcrafter** [comment]
[Stateless tests (amd_binary, ParallelReplicas, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88286&sha=5ac7bec84bafa8fe1bfb1baecfd45402e0861e09&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%2C%20parallel%29) - should be fixed by https://github.com/ClickHouse/ClickHouse/pull/88465

File: tests/queries/0_stateless/03644_join_order_mixed_comma_and_left.sql [hunk 1]
```diff
@@ -1,3 +1,5 @@
+SET enable_parallel_replicas = 0;
```
Comment (devcrafter) [inline tests/queries/0_stateless/03644_join_order_mixed_comma_and_left.sql]: Please don't do this. Having the test in blacklist should be enough. I'll exclude the test from blacklist as soon as #88465 will be merged (or wait until it merged - trying to do this today)

File: tests/parallel_replicas_blacklist.txt [hunk 2]
```diff
@@ -138,6 +138,7 @@
 01010_partial_merge_join
 02789_filesystem_cache_alignment
 03325_sqlite_join_wrong_answer
+03644_join_order_mixed_comma_and_left
```
Comment (vdimir) [inline tests/parallel_replicas_blacklist.txt]:
```suggestion
```

File: tests/queries/0_stateless/03644_join_order_mixed_comma_and_left.sql [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+
```
Comment (vdimir) [inline tests/queries/0_stateless/03644_join_order_mixed_comma_and_left.sql]:
```suggestion
```

File: tests/queries/0_stateless/03644_join_order_mixed_comma_and_left.sql [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+INSERT INTO n2 SELECT number FROM numbers(4);
+SELECT * FROM n1, n2 LEFT JOIN n3 ON n1.number = n3.number ORDER BY n1.number, n2.number, n3.number;
+
+INSERT INTO n3 SELECT number FROM numbers(4);
+SELECT * FROM n1, n2 LEFT JOIN n3 ON n1.number = n3.number ORDER BY n1.number, n2.number, n3.number;
+
+
+
+
```
Comment (vdimir) [inline tests/queries/0_stateless/03644_join_order_mixed_comma_and_left.sql]:
```suggestion
```

**Comment by vdimir** [comment]
> [Stateless tests (amd_debug, AsyncInsert, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88286&sha=5de832f481cfb7a17e7eb75e52ad03affec0a512&name_0=PR&name_1=Stateless+tests+%28amd_debug%2C+AsyncInsert%2C+s3+storage%2C+parallel%29)
> [Stateless tests (amd_ubsan, sequential)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88286&sha=5de832f481cfb7a17e7eb75e52ad03affec0a512&name_0=PR&name_1=Stateless+tests+%28amd_ubsan%2C+sequential%29)

`02572_materialized_views_ignore_errors` and `02346_text_index_hits` are flaky

> [Docker keeper image](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88286&sha=5de832f481cfb7a17e7eb75e52ad03affec0a512&name_0=PR&name_1=Docker+keeper+image)

**Comment by clickgapai** [comment]
Hi @vdimir @davenger — while reviewing this PR I found the following:

- **Bug (P0):** `buildQueryGraph` CROSS `join_kinds[0]` overwrites RIGHT JOIN constraint, silently converting RIGHT to INNER — https://github.com/ClickHouse/ClickHouse/issues/103030

Happy to discuss — close anything that's wrong or already addressed.
