### PR TITLE
KeyCondition IN function support different types

### LINKED ISSUE #48936: Analyzer: Subquery filter not using primary key
**Describe the unexpected behaviour**

When using a subquery to filter a table the primary/sorting key is not being used.

**How to reproduce**

This is happening in CH 23.3 but also reproduced in master:

```sql
SELECT version()

┌─version()─┐
│ 23.8.1.1  │
└───────────┘
```

The minimum reproducible script:

```sql
DROP TABLE IF EXISTS test;

CREATE TABLE test.test
ENGINE = MergeTree
ORDER BY (pk1, pk2)
SETTINGS index_granularity = 8
AS
SELECT
    10 pk1,
    number pk2,
    'test_' || toString(number) str
FROM numbers(20);

EXPLAIN indexes = 1
SELECT *
FROM test.test
WHERE pk1 <= 10 AND (pk2 IN (5))
SETTINGS allow_experimental_analyzer = 1;

EXPLAIN indexes = 1
SELECT *
FROM test.test
WHERE pk1 <= 10 AND (pk2 IN (SELECT 5))
SETTINGS allow_experimental_analyzer = 1;

EXPLAIN indexes = 1
SELECT *
FROM test.test
WHERE pk1 <= 10 AND (pk2 IN (SELECT number FROM numbers(5, 1)))
SETTINGS allow_experimental_analyzer = 1;
```

When filtering by a subquery, the filter is not being used. See both query plans:

```sql
┌─explain─────────────────────────────────────────────────────────────┐
│ Expression ((Project names + Projection))                           │
│   Expression (Change column names to column identifiers)            │
│     ReadFromMergeTree (test.test)                                   │
│     Indexes:                                                        │
│       PrimaryKey                                                    │
│         Keys:                                                       │
│           pk1                                                       │
│           pk2                                                       │ <= pk2 being used
│         Condition: and((pk1 in (-Inf, 10]), (pk2 in 1-element set)) │
│         Parts: 1/1                                                  │
│         Granules: 1/3                                               │
└─────────────────────────────────────────────────────────────────────┘
┌─explain─────────────────────────────────────────────────────────────────────────────────────┐
│ CreatingSets (Create sets before main query execution)                                      │
│   Expression ((Project names + Projection))                                                 │
│     Expression (Change column names to column identifiers)                                  │
│       ReadFromMergeTree (test.test)                                                         │
│       Indexes:                                                                              │
│         PrimaryKey                                                                          │
│           Keys:                                                                             │
│             pk1                                                                             │ <= pk2 is gone
│           Condition: (pk1 in (-Inf, 10])                                                    │
│           Parts: 1/1                                                                        │
│           Granules: 3/3                                                                     │
│   CreatingSet (Create set for subquery)                                                     │
│     Expression ((Project names + (Projection + Change column names to column identifiers))) │
│       ReadFromStorage (SystemOne)                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────┘

┌─explain───────────────────────────────────────────────────────────────┐
│ CreatingSets (Create sets before main query execution)                │
│   Expression ((Project names + Projection))                           │
│     Expression (Change column names to column identifiers)            │
│       ReadFromMergeTree (test.test)                                   │
│       Indexes:                                                        │
│         PrimaryKey                                                    │
│           Keys:                                                       │
│             pk1                                                       │
│             pk2                                                       │
│           Condition: and((pk1 in (-Inf, 10]), (pk2 in 1-element set)) │
│           Parts: 1/1                                                  │
│           Granules: 1/3                                               │
└───────────────────────────────────────────────────────────────────────┘
```

I have used `SELECT 5` as subquery for simplicity reasons but this reproduces with any kind of subquery.

**Expected behavior**

When using a subquery I'd expect sorting keys to be used also. In real scenarios this is causing reading more data than expected.

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow to use primary key for IN function where primary key column types are different from `IN` function right side column types. Example: `SELECT id FROM test_table WHERE id IN (SELECT '5')`. Closes #48936.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 82c5915674a21aad2e0df72bc39d0ecd5a0ca8bd with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54544/82c5915674a21aad2e0df72bc39d0ecd5a0ca8bd/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/MergeTree/RPNBuilder.cpp [hunk 1]
```diff
@@ -351,64 +351,6 @@ FutureSetPtr RPNBuilderTreeNode::tryGetPreparedSet(const DataTypes & data_types)
     return nullptr;
 }
 
-FutureSetPtr RPNBuilderTreeNode::tryGetPreparedSet(
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/RPNBuilder.cpp:354]: I am really happy that this part of code is removed :)

File: src/DataTypes/Utils.cpp [hunk 2]
```diff
@@ -0,0 +1,228 @@
...
+                    continue;
+
+                return false;
+            }
+            case TypeIndex::Nullable:
+            {
+                if (rhs_type_was_nullable)
+                {
+                    const auto & lhs_type_nullable = assert_cast<const DataTypeNullable &>(*lhs_type);
+                    return canBeSafelyCasted(lhs_type_nullable.getNestedType(), rhs_type);
```
Comment (KochetovNicolai) [inline src/DataTypes/Utils.cpp:127]: This is not correct because the stack may not be empty.
Looks like `Map(Nullable(x), y)` is always equal `Map(Nullable(x), z)` now.

Btw I think we can always use recursion here. A ton of other code uses it to traverse types.

File: src/DataTypes/Utils.cpp [hunk 3]
```diff
@@ -0,0 +1,228 @@
...
+            case TypeIndex::Int8:
+            case TypeIndex::Int16:
+            case TypeIndex::Int32:
+            case TypeIndex::Int64:
+            case TypeIndex::Int128:
+            case TypeIndex::Int256: {
+                if (rhs_which_type.isInt())
+                    return rhs_type->getSizeOfValueInMemory() >= lhs_type->getSizeOfValueInMemory();
+
+                if (rhs_which_type.isString())
```
Comment (KochetovNicolai) [inline src/DataTypes/Utils.cpp:57]: Maybe check `rhs_which_type.isString()` in the beginning and remove all this duplicating checks?

**Review by KochetovNicolai — CHANGES_REQUESTED** [review]
Looks good except for the tiny bug in `canBeSafelyCasted`

File: src/DataTypes/Utils.cpp (hunk 3 above)
Comment (kitaisreal) [reply src/DataTypes/Utils.cpp:57]: It seems that for such complex functions it is better to make each case self contained, and avoid generalization, so we can avoid errors if we will want to add new cases.

File: src/DataTypes/Utils.cpp (hunk 2 above)
Comment (kitaisreal) [reply src/DataTypes/Utils.cpp:127]: Updated.

**Review by KochetovNicolai — APPROVED** [review]
