### PR TITLE
Fix segfault in `groupConcat` merge with malformed serialized state

### LINKED ISSUE #93026: Segfault in `groupConcatMerge` when deserialising malformed aggregate state
### Problem

This query would return different results and if run enough times, would crash

```sql
SELECT hex(groupConcatMerge(',', 10)(state))
FROM
(
    SELECT CAST(unhex('0258590180e09bfeffffffffff0180809cfeffffffffff01'), 'AggregateFunction(groupConcat(\',\', 10), String)') AS state
)
```

### Stack trace

```cpp
2025.12.24 19:02:38.479963 [ 3391135 ] {} <Fatal> ClientBase: ########## Short fault info ############
2025.12.24 19:02:38.479998 [ 3391135 ] {} <Fatal> ClientBase: (version 26.1.1.1, build id: 91474C8CE7E61CDC5A080435FBCA6E3D3862A537, git hash: b63ef1a720c9b3894445a43188128e9a2ebff618, architecture: x86_64) (from thread 3391682) Received signal 11
2025.12.24 19:02:38.480002 [ 3391135 ] {} <Fatal> ClientBase: Signal description: Segmentation fault
2025.12.24 19:02:38.480007 [ 3391135 ] {} <Fatal> ClientBase: Address: 0x768f17872038. Access: read. Address not mapped to object.
2025.12.24 19:02:38.480016 [ 3391135 ] {} <Fatal> ClientBase: Stack trace: 0x00005f6ce3541471 0x00005f6cd35cd1ce 0x00005f6cd4f5382b 0x00005f6cd81d737c 0x00005f6cd81d881e 0x00005f6cdc40889c 0x00005f6cdc405c13 0x00005f6cdc1a9899 0x00005f6cdc19d452 0x00005f6cdc19e903 0x00005f6cd2dbcc4d 0x00005f6cd2dc1fa6 0x00005f6cd2dba7f6 0x00005f6cd2dc03bb 0x000076910a49caa4 0x000076910a529c6c
2025.12.24 19:02:38.480019 [ 3391135 ] {} <Fatal> ClientBase: ########################################
2025.12.24 19:02:38.480096 [ 3391135 ] {} <Fatal> ClientBase: (version 26.1.1.1, build id: 91474C8CE7E61CDC5A080435FBCA6E3D3862A537, git hash: b63ef1a720c9b3894445a43188128e9a2ebff618) (from thread 3391682) (query_id: e1b92866-9487-4f48-ab26-c5af5d90beaf) (query: SELECT hex(groupConcatMerge(',', 10)(state))
FROM
(
    SELECT CAST(unhex('0258590180e09bfeffffffffff0180809cfeffffffffff01'), 'AggregateFunction(groupConcat(\',\', 10), String)') AS state
)) Received signal Segmentation fault (11)
2025.12.24 19:02:38.480116 [ 3391135 ] {} <Fatal> ClientBase: Address: 0x768f17872038. Access: read. Address not mapped to object.
2025.12.24 19:02:38.480145 [ 3391135 ] {} <Fatal> ClientBase: Stack trace: 0x00005f6ce3541471 0x00005f6cd35cd1ce 0x00005f6cd4f5382b 0x00005f6cd81d737c 0x00005f6cd81d881e 0x00005f6cdc40889c 0x00005f6cdc405c13 0x00005f6cdc1a9899 0x00005f6cdc19d452 0x00005f6cdc19e903 0x00005f6cd2dbcc4d 0x00005f6cd2dc1fa6 0x00005f6cd2dba7f6 0x00005f6cd2dc03bb 0x000076910a49caa4 0x000076910a529c6c
2025.12.24 19:02:38.481189 [ 3391135 ] {} <Fatal> ClientBase: 3.0. inlined from ./base/glibc-compatibility/memcpy/memcpy.h:195: inline_memcpy(void*, void const*, unsigned long)
2025.12.24 19:02:38.481216 [ 3391135 ] {} <Fatal> ClientBase: 3. ./build-release/./base/glibc-compatibility/memcpy/memcpy.cpp:6: memcpy @ 0x000000002238e471
2025.12.24 19:02:38.492308 [ 3391135 ] {} <Fatal> ClientBase: 4.0. inlined from ./build-release/./src/AggregateFunctions/AggregateFunctionGroupConcat.cpp:29: DB::GroupConcatDataBase::insertChar(char const*, unsigned long, DB::Arena*)
2025.12.24 19:02:38.492325 [ 3391135 ] {} <Fatal> ClientBase: 4. ./build-release/./src/AggregateFunctions/AggregateFunctionGroupConcat.cpp:128: DB::GroupConcatImpl<true>::merge(char*, char const*, DB::Arena*) const @ 0x000000001241a1ce
2025.12.24 19:02:38.497446 [ 3391135 ] {} <Fatal> ClientBase: 5.0. inlined from ./build-release/./src/AggregateFunctions/Combinators/AggregateFunctionMerge.cpp:18: DB::AggregateFunctionMerge::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const
2025.12.24 19:02:38.497486 [ 3391135 ] {} <Fatal> ClientBase: 5. ./src/AggregateFunctions/IAggregateFunction.h:564: DB::IAggregateFunctionHelper<DB::AggregateFunctionMerge>::addBatchSinglePlace(unsigned long, unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0x0000000013da082b
[ip-172-31-28-2] 2025.12.24 19:02:38.480019 [ 3391135 ] <Fatal> ClientBase: ########################################
[ip-172-31-28-2] 2025.12.24 19:02:38.480096 [ 3391135 ] <Fatal> ClientBase: (version 26.1.1.1, build id: 91474C8CE7E61CDC5A080435FBCA6E3D3862A537, git hash: b63ef1a720c9b3894445a43188128e9a2ebff618) (from thread 3391682) (query_id: e1b92866-9487-4f48-ab26-c5af5d90beaf) (query: SELECT hex(groupConcatMerge(',', 10)(state))
FROM
(
    SELECT CAST(unhex('0258590180e09bfeffffffffff0180809cfeffffffffff01'), 'AggregateFunction(groupConcat(\',\', 10), String)') AS state
)) Received signal Segmentation fault (11)
[ip-172-31-28-2] 2025.12.24 19:02:38.480116 [ 3391135 ] <Fatal> ClientBase: Address: 0x768f17872038. Access: read. Address not mapped to object.
[ip-172-31-28-2] 2025.12.24 19:02:38.480145 [ 3391135 ] <Fatal> ClientBase: Stack trace: 0x00005f6ce3541471 0x00005f6cd35cd1ce 0x00005f6cd4f5382b 0x00005f6cd81d737c 0x00005f6cd81d881e 0x00005f6cdc40889c 0x00005f6cdc405c13 0x00005f6cdc1a9899 0x00005f6cdc19d452 0x00005f6cdc19e903 0x00005f6cd2dbcc4d 0x00005f6cd2dc1fa6 0x00005f6cd2dba7f6 0x00005f6cd2dc03bb 0x000076910a49caa4 0x000076910a529c6c
[ip-172-31-28-2] 2025.12.24 19:02:38.481189 [ 3391135 ] <Fatal> ClientBase: 3.0. inlined from ./base/glibc-compatibility/memcpy/memcpy.h:195: inline_memcpy(void*, void const*, unsigned long)
[ip-172-31-28-2] 2025.12.24 19:02:38.481216 [ 3391135 ] <Fatal> ClientBase: 3. ./build-release/./base/glibc-compatibility/memcpy/memcpy.cpp:6: memcpy @ 0x000000002238e471
[ip-172-31-28-2] 2025.12.24 19:02:38.492308 [ 3391135 ] <Fatal> ClientBase: 4.0. inlined from ./build-release/./src/AggregateFunctions/AggregateFunctionGroupConcat.cpp:29: DB::GroupConcatDataBase::insertChar(char const*, unsigned long, DB::Arena*)
[ip-172-31-28-2] 2025.12.24 19:02:38.492325 [ 3391135 ] <Fatal> ClientBase: 4. ./build-release/./src/AggregateFunctions/AggregateFunctionGroupConcat.cpp:128: DB::GroupConcatImpl<true>::merge(char*, char const*, DB::Arena*) const @ 0x000000001241a1ce
[ip-172-31-28-2] 2025.12.24 19:02:38.497446 [ 3391135 ] <Fatal> ClientBase: 5.0. inlined from ./build-release/./src/AggregateFunctions/Combinators/AggregateFunctionMerge.cpp:18: DB::AggregateFunctionMerge::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const
[ip-172-31-28-2] 2025.12.24 19:02:38.497486 [ 3391135 ] <Fatal> ClientBase: 5. ./src/AggregateFunctions/IAggregateFunction.h:564: DB::IAggregateFunctionHelper<DB::AggregateFunctionMerge>::addBatchSinglePlace(unsigned long, unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0x0000000013da082b
↙ Progress: 1.00 rows, 1.00 B (3.31 rows/s., 3.31 B/s.)  99%    2025.12.24 19:02:38.787391 [ 3391135 ] {} <Fatal> ClientBase: 6.0. inlined from ./build-release/./src/Interpreters/Aggregator.cpp:0: DB::Aggregator::addBatchSinglePlace(unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*, DB::Arena*)
2025.12.24 19:02:38.787439 [ 3391135 ] {} <Fatal> ClientBase: 6. ./build-release/./src/Interpreters/Aggregator.cpp:1535: DB::Aggregator::executeWithoutKeyImpl(char*&, unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*, bool) const @ 0x000000001702437c
[ip-172-31-28-2] 2025.12.24 19:02:38.787391 [ 3391135 ] <Fatal> ClientBase: 6.0. inlined from ./build-release/./src/Interpreters/Aggregator.cpp:0: DB::Aggregator::addBatchSinglePlace(unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*, DB::Arena*)
[ip-172-31-28-2] 2025.12.24 19:02:38.787439 [ 3391135 ] <Fatal> ClientBase: 6. ./build-release/./src/Interpreters/Aggregator.cpp:1535: DB::Aggregator::executeWithoutKeyImpl(char*&, unsigned long, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, DB::Arena*, bool) const @ 0x000000001702437c
↖ Progress: 1.00 rows, 1.00 B (1.99 rows/s., 1.99 B/s.)  99%    2025.12.24 19:02:39.074610 [ 3391135 ] {} <Fatal> ClientBase: 7. ./build-release/./src/Interpreters/Aggregator.cpp:1802: DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>>>&, bool&) const @ 0x000000001702581e
[ip-172-31-28-2] 2025.12.24 19:02:39.074610 [ 3391135 ] <Fatal> ClientBase: 7. ./build-release/./src/Interpreters/Aggregator.cpp:1802: DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>>>&, bool&) const @ 0x000000001702581e
2025.12.24 19:02:39.093373 [ 3391135 ] {} <Fatal> ClientBase: 8. ./build-release/./src/Processors/Transforms/AggregatingTransform.cpp:904: DB::AggregatingTransform::consume(DB::Chunk) @ 0x000000001b25589c
2025.12.24 19:02:39.109878 [ 3391135 ] {} <Fatal> ClientBase: 9. ./build-release/./src/Processors/Transforms/AggregatingTransform.cpp:862: DB::AggregatingTransform::work() @ 0x000000001b252c13
2025.12.24 19:02:39.113062 [ 3391135 ] {} <Fatal> ClientBase: 10.0. inlined from ./build-release/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.12.24 19:02:39.113076 [ 3391135 ] {} <Fatal> ClientBase: 10. ./build-release/./src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001aff6899
2025.12.24 19:02:39.123748 [ 3391135 ] {} <Fatal> ClientBase: 11. ./build-release/./src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001afea452
2025.12.24 19:02:39.135563 [ 3391135 ] {} <Fatal> ClientBase: 12.0. inlined from ./build-release/./src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*)
2025.12.24 19:02:39.135588 [ 3391135 ] {} <Fatal> ClientBase: 12.1. inlined from ./build-release/./src/Processors/Executors/PipelineExecutor.cpp:565: operator()
2025.12.24 19:02:39.135608 [ 3391135 ] {} <Fatal> ClientBase: 12.2. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:249: decltype(std::declval<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.12.24 19:02:39.135616 [ 3391135 ] {} <Fatal> ClientBase: 12.3. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.12.24 19:02:39.135625 [ 3391135 ] {} <Fatal> ClientBase: 12.4. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: void std::__invoke_r[abi:ne210105]<void, DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.12.24 19:02:39.135644 [ 3391135 ] {} <Fatal> ClientBase: 12. ./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000001afeb903
2025.12.24 19:02:39.144840 [ 3391135 ] {} <Fatal> ClientBase: 13.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
2025.12.24 19:02:39.144879 [ 3391135 ] {} <Fatal> ClientBase: 13.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
2025.12.24 19:02:39.144884 [ 3391135 ] {} <Fatal> ClientBase: 13. ./build-release/./src/Common/ThreadPool.cpp:801: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000011c09c4d
2025.12.24 19:02:39.151814 [ 3391135 ] {} <Fatal> ClientBase: 14.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
2025.12.24 19:02:39.151843 [ 3391135 ] {} <Fatal> ClientBase: 14.1. inlined from ./contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
2025.12.24 19:02:39.151871 [ 3391135 ] {} <Fatal> ClientBase: 14.2. inlined from ./contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
2025.12.24 19:02:39.151901 [ 3391135 ] {} <Fatal> ClientBase: 14. ./src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000011c0efa6
2025.12.24 19:02:39.158865 [ 3391135 ] {} <Fatal> ClientBase: 15.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
2025.12.24 19:02:39.158884 [ 3391135 ] {} <Fatal> ClientBase: 15.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
2025.12.24 19:02:39.158904 [ 3391135 ] {} <Fatal> ClientBase: 15. ./build-release/./src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000011c077f6
2025.12.24 19:02:39.172163 [ 3391135 ] {} <Fatal> ClientBase: 16.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.12.24 19:02:39.172208 [ 3391135 ] {} <Fatal> ClientBase: 16.1. inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:ne210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.12.24 19:02:39.172215 [ 3391135 ] {} <Fatal> ClientBase: 16. ./contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:ne210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000011c0d3bb
2025.12.24 19:02:39.172288 [ 3391135 ] {} <Fatal> ClientBase: 17. start_thread @ 0x000000000009caa4
2025.12.24 19:02:39.172322 [ 3391135 ] {} <Fatal> ClientBase: 18. __GI___clone3 @ 0x0000000000129c6c
2025.12.24 19:02:39.172539 [ 3391135 ] {} <Fatal> ClientBase: Changed settings: allow_introspection_functions = true, serialize_query_plan = false, storage_file_read_method = 'mmap', parallel_replicas_for_cluster_engines = false, implicit_select = true
[ip-172-31-28-2] 2025.12.24 19:02:39.093373 [ 3391135 ] <Fatal> ClientBase: 8. ./build-release/./src/Processors/Transforms/AggregatingTransform.cpp:904: DB::AggregatingTransform::consume(DB::Chunk) @ 0x000000001b25589c
[ip-172-31-28-2] 2025.12.24 19:02:39.109878 [ 3391135 ] <Fatal> ClientBase: 9. ./build-release/./src/Processors/Transforms/AggregatingTransform.cpp:862: DB::AggregatingTransform::work() @ 0x000000001b252c13
[ip-172-31-28-2] 2025.12.24 19:02:39.113062 [ 3391135 ] <Fatal> ClientBase: 10.0. inlined from ./build-release/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
[ip-172-31-28-2] 2025.12.24 19:02:39.113076 [ 3391135 ] <Fatal> ClientBase: 10. ./build-release/./src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001aff6899
[ip-172-31-28-2] 2025.12.24 19:02:39.123748 [ 3391135 ] <Fatal> ClientBase: 11. ./build-release/./src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001afea452
[ip-172-31-28-2] 2025.12.24 19:02:39.135563 [ 3391135 ] <Fatal> ClientBase: 12.0. inlined from ./build-release/./src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*)
[ip-172-31-28-2] 2025.12.24 19:02:39.135588 [ 3391135 ] <Fatal> ClientBase: 12.1. inlined from ./build-release/./src/Processors/Executors/PipelineExecutor.cpp:565: operator()
[ip-172-31-28-2] 2025.12.24 19:02:39.135608 [ 3391135 ] <Fatal> ClientBase: 12.2. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:249: decltype(std::declval<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[ip-172-31-28-2] 2025.12.24 19:02:39.135616 [ 3391135 ] <Fatal> ClientBase: 12.3. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[ip-172-31-28-2] 2025.12.24 19:02:39.135625 [ 3391135 ] <Fatal> ClientBase: 12.4. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: void std::__invoke_r[abi:ne210105]<void, DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[ip-172-31-28-2] 2025.12.24 19:02:39.135644 [ 3391135 ] <Fatal> ClientBase: 12. ./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000001afeb903
[ip-172-31-28-2] 2025.12.24 19:02:39.144840 [ 3391135 ] <Fatal> ClientBase: 13.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
[ip-172-31-28-2] 2025.12.24 19:02:39.144879 [ 3391135 ] <Fatal> ClientBase: 13.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
[ip-172-31-28-2] 2025.12.24 19:02:39.144884 [ 3391135 ] <Fatal> ClientBase: 13. ./build-release/./src/Common/ThreadPool.cpp:801: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000011c09c4d
[ip-172-31-28-2] 2025.12.24 19:02:39.151814 [ 3391135 ] <Fatal> ClientBase: 14.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
[ip-172-31-28-2] 2025.12.24 19:02:39.151843 [ 3391135 ] <Fatal> ClientBase: 14.1. inlined from ./contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
[ip-172-31-28-2] 2025.12.24 19:02:39.151871 [ 3391135 ] <Fatal> ClientBase: 14.2. inlined from ./contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
[ip-172-31-28-2] 2025.12.24 19:02:39.151901 [ 3391135 ] <Fatal> ClientBase: 14. ./src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000011c0efa6
[ip-172-31-28-2] 2025.12.24 19:02:39.158865 [ 3391135 ] <Fatal> ClientBase: 15.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
[ip-172-31-28-2] 2025.12.24 19:02:39.158884 [ 3391135 ] <Fatal> ClientBase: 15.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
[ip-172-31-28-2] 2025.12.24 19:02:39.158904 [ 3391135 ] <Fatal> ClientBase: 15. ./build-release/./src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000011c077f6
[ip-172-31-28-2] 2025.12.24 19:02:39.172163 [ 3391135 ] <Fatal> ClientBase: 16.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
[ip-172-31-28-2] 2025.12.24 19:02:39.172208 [ 3391135 ] <Fatal> ClientBase: 16.1. inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:ne210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
[ip-172-31-28-2] 2025.12.24 19:02:39.172215 [ 3391135 ] <Fatal> ClientBase: 16. ./contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:ne210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000011c0d3bb
[ip-172-31-28-2] 2025.12.24 19:02:39.172288 [ 3391135 ] <Fatal> ClientBase: 17. start_thread @ 0x000000000009caa4
[ip-172-31-28-2] 2025.12.24 19:02:39.172322 [ 3391135 ] <Fatal> ClientBase: 18. __GI___clone3 @ 0x0000000000129c6c
[ip-172-31-28-2] 2025.12.24 19:02:39.172539 [ 3391135 ] <Fatal> ClientBase: Changed settings: allow_introspection_functions = true, serialize_query_plan = false, storage_file_read_method = 'mmap', parallel_replicas_for_cluster_engines = false, implicit_select = true
↗ Progress: 1.00 rows, 1.00 B (0.26 rows/s., 0.26 B/s.)  99%    Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by rienath**
## Linked issues
- fixes https://github.com/ClickHouse/clickhouse-core-incidents/issues/1154

Closes #93026 

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash when deserialising malformed `groupConcat` aggregate state with out-of-bounds offsets.

### CODE REVIEW

**Review by nihalzp — COMMENTED** [review]
The following query is crashing. This is a different problem because it contains non-monotonic offsets.

```sql
SELECT hex(groupConcatMerge(',', 10)(state))
FROM
(
    SELECT CAST(unhex('0141010100'), 'AggregateFunction(groupConcat(\',\', 10), String)') AS state
);
```

I have also applied your changes from https://github.com/ClickHouse/ClickHouse/pull/93426.

File: src/AggregateFunctions/AggregateFunctionGroupConcat.cpp [hunk 1]
```diff
@@ -173,8 +173,16 @@ void GroupConcatImpl<has_limit>::deserialize(AggregateDataPtr __restrict place,
...
-        for (auto & offset : cur_data.offsets)
-            readVarUInt(offset, buf);
+        for (size_t i = 0; i < cur_data.offsets.size(); ++i)
+        {
+            readVarUInt(cur_data.offsets[i], buf);
+
+            if (cur_data.offsets[i] > cur_data.data_size)
+                throw Exception(ErrorCodes::BAD_ARGUMENTS, "Invalid offset {} in groupConcat state: exceeds data size {}", cur_data.offsets[i], cur_data.data_size);
+
+            if (cur_data.offsets[i] < cur_data.offsets[i - 1])
```
Comment (nihalzp) [inline src/AggregateFunctions/AggregateFunctionGroupConcat.cpp]:
```suggestion
            if (i != 0 && cur_data.offsets[i] < cur_data.offsets[i - 1])
```

**Comment by nihalzp** [comment]
To be robust, I think we can also add a check to make sure last offset is equal to `cur_data.data_size` if `cur_data.num_rows != 0`.

**Review by nihalzp — APPROVED** [review]
