### PR TITLE
Fix inconsistent AST formatting

### LINKED ISSUE #85075: More inconsistent AST formatting
### Describe the bug

Easy to reproduce, cc @alexey-milovidov 

### How to reproduce

Run:

```sql
SELECT position(1 = ANY(SELECT 1), 1);
```

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'Inconsistent AST formatting: the query:
SELECT position(1 IN (SELECT 1), 1)
cannot parse query back from SELECT position(1 = ANY(SELECT 1), 1);'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000265ff8f2
1. src/Common/Exception.cpp:116: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000140b8866
2. src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cda15ac
3. src/Common/Exception.h:137: DB::Exception::Exception<String&, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, String&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000001b33b276
4. src/Interpreters/executeQuery.cpp:1096: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001b332daf
5. src/Interpreters/executeQuery.cpp:1770: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001b32a385
6. src/Server/TCPHandler.cpp:739: DB::TCPHandler::runImpl() @ 0x000000001e5c380f
7. src/Server/TCPHandler.cpp:2740: DB::TCPHandler::run() @ 0x000000001e5dd6a4
8. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000266b61c7
9. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000266b67a5
10. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000002665597f
11. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000026653051
12. start_thread @ 0x00000000000a27f1
13. __clone3 @ 0x0000000000133c9c
```

### PR DESCRIPTION
**Pull request by Felixoid**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Surround operators `IN`, `NOT IN` with parentheses. Fixes https://github.com/ClickHouse/ClickHouse/issues/85075

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Felixoid** [comment]
@alexey-milovidov, PTAL after the latest changes. Is it still fine?

File: src/Parsers/ASTFunction.cpp [hunk 1]
```diff
@@ -432,15 +432,21 @@ void ASTFunction::formatImplWithoutAlias(WriteBuffer & ostr, const FormatSetting
 
             if (auto it = std::ranges::find(operators, name, &FunctionOperatorMapping::function_name); it != operators.end())
             {
-                if (frame.need_parens)
+                /// IN operators need extra parentheses to avoid parsing ambiguity when used as function arguments.
+                /// The parser cannot handle IN inside multi-argument function calls without parentheses.
+                /// Example: position(1 IN (SELECT 1), 2) must be formatted as position((1 IN (SELECT 1)), 2)
```
Comment (alexey-milovidov) [inline src/Parsers/ASTFunction.cpp:437]: The ambiguity appears only for the `position` function, as it allows the syntax sugar "position(a IN b)". Maybe such a drastic change is unnecessary?

**Review by alexey-milovidov — APPROVED** [review]
The change LGTM.

File: src/Parsers/ASTFunction.cpp (hunk 1 above)
Comment (Felixoid) [reply src/Parsers/ASTFunction.cpp:437]:
```
SELECT position('asdasdd', 'a')

Query id: cbde25d0-5c23-42cd-b02b-c6afcf6ef9b3

   ┌─position('asdasdd', 'a')─┐
1. │                        1 │
   └──────────────────────────┘

SELECT position((1, 2, 3), 1)

Query id: 5909991b-87b9-4f76-acb3-90a2d9423e3f


Elapsed: 0.060 sec.

Received exception:
Code: 43. DB::Exception: Illegal type Tuple(UInt8, UInt8, UInt8) of argument of function position: In scope SELECT position((1, 2, 3), 1). (ILLEGAL_TYPE_OF_ARGUMENT)

SELECT position(1 in (1,2,3), 2)

Expected one of: token, DoubleColon, ClosingRoundBracket, OR, AND, IS NOT DISTINCT FROM, IS DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, identifier
```

oh well... thanks, that's a good hint on where to look

Comment (Felixoid) [reply src/Parsers/ASTFunction.cpp:437]: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92225&sha=4de9eb332a878e518f2d1a074a59c5d19f70899a&name_0=PR&name_1=Stateless+tests+%28amd_debug%2C+parallel%29&name_2=Tests

It looks like fixing it in the `position` is less reliable:

```
clickhouse-server.err.log:2025.12.17 11:15:29.795265 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Suspicious part of the AST: ExpressionList: SELECT position(1 IN (SELECT 1), 2) AS pos
clickhouse-server.err.log:2025.12.17 11:15:29.795311 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Suspicious part of the AST: SelectQuery: SELECT position(1 IN (SELECT 1), 2) AS pos
clickhouse-server.err.log:2025.12.17 11:15:29.795340 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Suspicious part of the AST: ExpressionList: position(1 IN (SELECT 1), 2) AS pos
clickhouse-server.err.log:2025.12.17 11:15:29.795399 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Suspicious part of the AST: Function_position: position(1 IN (SELECT 1), 2) AS pos
clickhouse-server.err.log:2025.12.17 11:15:29.795421 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Suspicious part of the AST: ExpressionList: 1 IN (SELECT 1), 2
clickhouse-server.err.log:2025.12.17 11:15:29.795440 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Suspicious part of the AST: Function_in: 1 IN (SELECT 1)
clickhouse-server.err.log:2025.12.17 11:15:29.795460 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> executeQuery: Cannot find formatted child in the formatted query: 1, (SELECT 1)
clickhouse-server.err.log:2025.12.17 11:15:29.795525 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> : Logical error: 'Inconsistent AST formatting in Function_in: the query:
clickhouse-server.err.log:2025.12.17 11:15:29.795546 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> : Format string: 'Inconsistent AST formatting in {}: the query:
clickhouse-server.err.log:2025.12.17 11:15:29.816777 [ 4725 ] {f3b96d15-8192-4dce-8601-b3f329ee3fb6} <Fatal> : Stack trace (when copying this message, always include the lines below)
```

I'll stick to the surrounding `A IN B` in parentheses inside functions for consistency. It feels safer this way

**Comment by Felixoid** [comment]
`Install` test is fixed in https://github.com/ClickHouse/ClickHouse/pull/92387
