### PR TITLE
fix #33798

### LINKED ISSUE #33798: optimize_functions_to_subcolumns count(null_column) doesn't use alias for column name
**Describe what's wrong**

In case of using `optimize_functions_to_subcolumns` ClickHouse doesn't use alias for column name.

**How to reproduce**

ClickHouse 21.13

```
CREATE TABLE test
(
    `key` UInt32,
    `value` Nullable(UInt32)
)
ENGINE = MergeTree
ORDER BY key

INSERT INTO test SELECT
    number,
    NULL
FROM numbers(10000000);


SELECT count(value) AS a
FROM test
SETTINGS optimize_functions_to_subcolumns = 0

┌─a─┐
│ 0 │
└───┘

1 rows in set. Elapsed: 0.028 sec. Processed 32.50 million rows, 162.52 MB (1.15 billion rows/s., 5.74 GB/s.)

SELECT count(value) AS a
FROM test
SETTINGS optimize_functions_to_subcolumns = 1

┌─sum(not(value.null))─┐
│                    0 │
└──────────────────────┘

1 rows in set. Elapsed: 0.032 sec. Processed 32.50 million rows, 32.50 MB (1.00 billion rows/s., 1.00 GB/s.)
```

**Expected behavior**

ClickHouse should use alias name.

### PR DESCRIPTION
**Pull request by qieqieplus**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix missing alias after function is optimized to subcolumn when setting `optimize_functions_to_subcolumns` is enabled. Closes #33798.

### CODE REVIEW

File: tests/queries/0_stateless/02116_tuple_element.sql [hunk 1]
```diff
@@ -14,6 +14,8 @@ EXPLAIN SYNTAX SELECT tupleElement(t1, 2) FROM t_tuple_element;
 SELECT tupleElement(t1, 'a') FROM t_tuple_element;
 EXPLAIN SYNTAX SELECT tupleElement(t1, 'a') FROM t_tuple_element;
 
+SELECT tupleElement(t1, 1) AS t10 FROM t_tuple_element FORMAT TSVWithNames;
```
Comment (kitaisreal) [inline tests/queries/0_stateless/02116_tuple_element.sql:17]: @qieqieplus fix looks valid. We prefer to not modify old tests, better to create new ones. Also could you please add test like `SELECT tupleElement(t1, 1) AS t10, t10 FROM t_tuple_element FORMAT TSVWithNames;`. Just want to be sure that alias will work.

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: tests/queries/0_stateless/02116_tuple_element.sql (hunk 1 above)
Comment (qieqieplus) [reply tests/queries/0_stateless/02116_tuple_element.sql]: Thanks for review, I made changes as requested.

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Mergifyio update.
