### PR TITLE
Fix a logical error in MergeTreeDeduplicationLog for a table with S3 plain disk.

### LINKED ISSUE #86189: Logical error: 'current_writer != nullptr'
### Describe the bug

Nasty setup with 2 disks with different metadata types.

### How to reproduce

Setup minio running with `tests/docker_scripts/setup_minio.sh stateless` then use this config for the server:
```xml
<storage_configuration>
    <disks>
        <disk0>
            <type>object_storage</type>
            <object_storage_type>s3</object_storage_type>
            <metadata_type>plain</metadata_type>
            <endpoint>http://localhost:11111/test/data0</endpoint>
            <access_key_id>clickhouse</access_key_id>
            <secret_access_key>clickhouse</secret_access_key>
        </disk0>
        <disk1>
            <type>object_storage</type>
            <object_storage_type>s3</object_storage_type>
            <metadata_type>local</metadata_type>
            <endpoint>http://localhost:11111/test/data1</endpoint>
            <access_key_id>clickhouse</access_key_id>
            <secret_access_key>clickhouse</secret_access_key>
        </disk1>
    </disks>
    <policies>
        <policy0>
            <volumes>
                <volume0>
                    <disk>disk0</disk>
                    <disk>disk1</disk>
                </volume0>
            </volumes>
        </policy0>
    </policies>
</storage_configuration>
```
Run:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() ORDER BY tuple() SETTINGS non_replicated_deduplication_window = 2, storage_policy = 'policy0';
INSERT INTO TABLE t0 (c0) VALUES (1); --Logical error
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'current_writer != nullptr'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. src/Common/StackTrace.cpp:389: StackTrace::StackTrace() @ 0x0000000014463be4
1. src/Common/Exception.cpp:56: DB::abortOnFailedAssertion(String const&) @ 0x00000000143bd395
2. src/Storages/MergeTree/MergeTreeDeduplicationLog.cpp:246: DB::MergeTreeDeduplicationLog::addPart(String const&, DB::MergeTreePartInfo const&) @ 0x000000001eaf6399
3. src/Storages/MergeTree/MergeTreeSink.cpp:239: DB::MergeTreeSink::commitPart(std::shared_ptr<DB::IMergeTreeDataPart>&, String const&) @ 0x000000001ec383a5
4. src/Storages/MergeTree/MergeTreeSink.cpp:199: DB::MergeTreeSink::finishDelayedChunk() @ 0x000000001ec37f65
5. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001f44cdc3
6. src/Processors/Transforms/ExceptionKeepingTransform.cpp:172: DB::ExceptionKeepingTransform::work() @ 0x000000001f44c97d
7. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001f1ac790
8. src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f19f4c5
9. src/Processors/Executors/PipelineExecutor.cpp:179: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x000000001f19ec0e
10. src/Processors/Executors/PushingPipelineExecutor.cpp:131: DB::PushingPipelineExecutor::finish() @ 0x000000001f1b8a1f
11. src/Server/TCPHandler.cpp:1205: DB::TCPHandler::processInsertQuery(DB::QueryState&) @ 0x000000001f0cc9b6
12. src/Server/TCPHandler.cpp:748: DB::TCPHandler::runImpl() @ 0x000000001f0c17b3
13. src/Server/TCPHandler.cpp:2740: DB::TCPHandler::run() @ 0x000000001f0db524
14. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000272afd07
15. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000272b02e5
16. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000002724f4bf
17. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000002724cb91
18. start_thread @ 0x00000000000a27f1
19. __clone3 @ 0x0000000000133c9c
```

### PR DESCRIPTION
**Pull request by tuanpach**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

In MergeTreeDeduplicationLog::load, if the disk is a storage object with Plain metadata, skip the check for logs_dir existence.
Because `Plain` metadata does not have the concept of directories.

Closes https://github.com/ClickHouse/ClickHouse/issues/86189

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/config/config.d/storage_conf_03755.xml [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+                    <volume0>
+                        <disk>disk_03755_0</disk>
+                    </volume0>
+                    <volume1>
+                        <disk>disk_03755_1</disk>
+                    </volume1>
+                </volumes>
+            </policy_03755>
+        </policies>
+    </storage_configuration>
```
Comment (bharatnc) [inline tests/config/config.d/storage_conf_03755.xml:33]: It looks like the tests fail currently due to unknown storage policy. I think you might need one more block after the `<storage_configuration>` for defining the storage_policy for merge_tree or something similar:
```
    <merge_tree>
        <storage_policy>policy_03755</storage_policy>
    </merge_tree>
```

Comment (tuanpach) [reply tests/config/config.d/storage_conf_03755.xml:33]: I have to install the config file. Just pushed the update.

**Review by bharatnc — APPROVED** [review]
