### PR TITLE
Fix a bug with projections and the `aggregate_functions_null_for_empty` setting

### LINKED ISSUE #41647: select max(date) from test_date always return -127593672
**Describe the unexpected behaviour**
max(date) and min(date) always return the same negative value: -127593672

**How to reproduce**
ClickHouse version: Docker -- clickhouse/clickhouse-server:22.6.8.35-alpine
Architecture: linux/arm64

```
MySQL [test]> create table test_date (
  date Int32,
  hour Int32
  ) ENGINE = MergeTree ORDER BY (date);
    ->     ->     -> Query OK, 0 rows affected (0.01 sec)
```
```
MySQL [test]> insert into test_date values(20220920, 1);
Query OK, 1 row affected (0.00 sec)
```
```
MySQL [test]> select max(date) from test_date;
+-----------------+
| maxOrNull(date) |
+-----------------+
| -127593672      |
+-----------------+
1 row in set (0.00 sec)
```
```
MySQL [test]> select max(hour) from test_date;
+-----------------+
| maxOrNull(hour) |
+-----------------+
| 1               |
+-----------------+
1 row in set (0.00 sec)
```
**Expected behavior**
I expect it to return ``20220920``.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug with projections and the `aggregate_functions_null_for_empty` setting. This bug is very rare and appears only if you enable the `aggregate_functions_null_for_empty` setting in the server's config. This closes #41647.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp [hunk 1]
```diff
@@ -176,6 +176,11 @@ QueryPlanPtr MergeTreeDataSelectExecutor::read(
                 "No projection is used when allow_experimental_projection_optimization = 1 and force_optimize_projection = 1",
                 ErrorCodes::PROJECTION_NOT_USED);
 
+        if (settings.force_optimize_projection && settings.aggregate_functions_null_for_empty)
```
Comment (amosbird) [inline src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:179]: This part looks useless.

Comment (alexey-milovidov) [reply src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:179]: Why useless?

I treat it this way: if a user requested "force_optimize_projection" it should know if the optimization is not applied.

Comment (amosbird) [reply src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:179]: > if a user requested "force_optimize_projection" it should know if the optimization is not applied.

The exception thrown a few lines above carries such meaning exactly.

If there is some projection define in the table, and for any reason (like `aggregate_functions_null_for_empty = true`) it cannot be used, the exception will be thrown.

The setting was to mimic the behavior of `force_primary_key`, which has the description: `Throw an exception if there is primary key in a table, and it is not used.`. However, I just did a quick test and found that it will throw even when table doesn't have primary key. Not sure whether we should change the description or the behavior.

Comment (alexey-milovidov) [reply src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:179]: > However, I just did a quick test and found that it will throw even when table doesn't have primary key. Not sure whether we should change the description or the behavior.

Better to change the behavior. (Don't throw if no primary key)

**Comment by amosbird** [comment]
LGTM.

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM
