### PR TITLE
Try to fix flaky 02455_one_row_from_csv_memory_usage

### LINKED ISSUE #48688: Flaky test `02455_one_row_from_csv_memory_usage`
Link: https://s3.amazonaws.com/clickhouse-test-reports/48666/165edd332e58c280808a842331d9f6a9934dfa59/stateless_tests__ubsan__[2/2].html

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

This test seems to be flaky after #48525. Closes #48688.

cc @devcrafter

### CODE REVIEW

**Review by qoega — APPROVED** [review]

File: tests/queries/0_stateless/02455_one_row_from_csv_memory_usage.sh [hunk 1]
```diff
@@ -9,7 +8,7 @@ USER_FILES_PATH=$($CLICKHOUSE_CLIENT --query "select _path,_file from file('none
 
 cp "$CUR_DIR"/data_csv/10m_rows.csv.xz $USER_FILES_PATH/
 
-${CLICKHOUSE_CLIENT} --query="SELECT * FROM file('10m_rows.csv.xz' , 'CSVWithNames') order by identifier, number, name, surname, birthday LIMIT 1 settings max_memory_usage=1000000000"
-${CLICKHOUSE_CLIENT} --query="SELECT * FROM file('10m_rows.csv.xz' , 'CSVWithNames') order by identifier, number, name, surname, birthday LIMIT 1 settings max_memory_usage=100000000"
+${CLICKHOUSE_CLIENT} --query="SELECT * FROM file('10m_rows.csv.xz' , 'CSVWithNames') order by identifier, number, name, surname, birthday LIMIT 1 settings max_threads=1, max_memory_usage=1000000000"
+${CLICKHOUSE_CLIENT} --query="SELECT * FROM file('10m_rows.csv.xz' , 'CSVWithNames') order by identifier, number, name, surname, birthday LIMIT 1 settings max_threads=1, max_memory_usage=100000000"
 
 rm $USER_FILES_PATH/10m_rows.csv.xz
```
Comment (novikd) [inline tests/queries/0_stateless/02455_one_row_from_csv_memory_usage.sh:14]:
```suggestion
```

Comment (devcrafter) [reply tests/queries/0_stateless/02455_one_row_from_csv_memory_usage.sh]: Flaky check is failed because the test is run in parallel. Just return `# Tags: no-parallel` back
