### PR TITLE
validate mergetree setting merge_max_block_size

### LINKED ISSUE #81586: Don't set merge_max_block_size to 0
### Describe the bug

or merges will fail.

### How to reproduce

Run:

```sql
CREATE TABLE t0 (c0 Map(String,Decimal(15,4)), c1 Nullable(String), c2 Nullable(String)) ENGINE = MergeTree() ORDER BY tuple() SETTINGS merge_max_block_size = 0;
INSERT INTO TABLE t0 (c0, c1, c2) SELECT c0, c1, c2 FROM generateRandom('c0 Map(String,Decimal(15,4)), c1 Nullable(String), c2 Nullable(String)', 12283889378209237759, 5091, 3) LIMIT 23;
INSERT INTO TABLE t0 (c0, c2, c1) SELECT c0, c2, c1 FROM generateRandom('c0 Map(String,Decimal(15,4)), c2 Nullable(String), c1 Nullable(String)', 13304632379905240303, 7037, 1) LIMIT 69;
INSERT INTO TABLE t0 (c1, c2, c0) VALUES ('c1', '', map('is',98694028951.59, '名字',-890.096, '名字',-8342020.90, b'101',83458.0, x'c328',-117530137.24, '😀',-48345565751.706)), (b'100', '😀', map(',',-2.541, 'can',-3641070.65, 'is',16.551, b'100',1405752897.0, 'c1',5768.3, ',',187738.343, '10',-63610522950.982)), ('be', 'use', map()), (b'100', '', map()), (NULL, '😀', map()), (NULL, b'10001', map('c1',-66.2080, '11',215513.6, b'10001',17359.7825, '名字',-879039.7, 'c0',9962.16, '1',-12277975.8, b'101',-66145930679.45, '兄弟姐妹',76.4296, 'said',-80.601)), ('said', 'use', map(b'101',-139946550.7354, 'said',-191447364.0, '\n',-9029.333, '11',-638.282, 'said',128632787.6, '😀😀😀😀',2828.7)), (' ', '兄弟姐妹', map('\n',-870364.3187, '😀😀😀😀',-97098.659, 'can',-14059653337.262, x'e28228',-59583311.995, '1000',-9227054665.2, 'use',-3534678.39, 'is',-907285.03)), ('be', b'10001', map(x'ff',7421663.9925, 'is',-157950.842, ',',-84742969.393, b'101',-31408678.54, '1000',2.6725, 'said',-4615089827.94, 'c1',-750514.5664)), ('名字', '', map(x'ff',-7121416.953)), (' ', b'10001', map(b'10001',-28447243.317, b'10001',4874128007.2479, x'c328',648257.7, '😀😀😀😀',-36761924.0, 'said',8671.5899, x'c328',53.302, 'are',462.3581)), (',', 'c0', map('are',-1475783.1603, b'101',-1.7, 'said',-8357.5, 'were',-1408150.48, '名字',-64791.40, 'can',5010182630.145, '兄弟姐妹',-143270428.6, '1000',173626095.867, x'c328',15447765.804, 'can',-7357.98)), (NULL, 'c0', map('is',-976478.10, '0',-619870.0, 'c0',-34604479.2, 'were',33.10, 'can',86226226631.316, 'said',-1.2, 'is',256.847)), ('said', b'10001', map(b'10001',-800.689, 'had',-44236385606.2, '1000',-827.9991, '😀😀😀😀',644031.139, '1000',8603472149.734, '11',382433717.13)), (b'10001', NULL, map('are',-38.13, '😀😀😀😀',-20006420701.8518, b'10001',3499.220, '10',-46770.30, ' ',8391.8621)), ('名字', 'use', map(b'10001',-434406.362, '😀',65115741875.501, '名字',-858056.566, b'10001',5365138469.1455)), (b'10001', '兄弟姐妹', map(x'e28228',83766290537.861, 'had',8947.07, '10',952924831.92, 'can',173.581, '11',15163.402, '0',-29340.0023, '名字',-1926.9794, ' ',5313.115, 'said',-78833458.850, b'10001',71894503959.4050)), ('was', 'use', map('11',-4532.066, '',48450309.571, 'is',8642.6, 'c1',-184.9, '兄弟姐妹',21147.04)), ('had', 'said', map('1',721135247.4, '1',-91236389972.36, '10',-703.2343, '😀😀😀😀',-124.0444, 'have',-1.5, ' ',49.8194)), ('名字', '兄弟姐妹', map('are',-562.860, '1000',1422147.948, '名字',829.336, '0',-6255606.148)), (x'c328', 'are', map('were',-73.4, '10',91271.2116, 'c0',28672270.8297, 'use',-24983674.83)), ('名字', 'use', map(b'101',1762.48, '1000',-193.7, '名字',254.88, 'is',78875232674.72, 'have',-571107581.70, '-1',-9301421784.5, 'are',93147726.13, '\n',-675496119.81)), (',', 'c0', map()), (x'c328', 'are', map(x'ff',-227203.521, 'can',91226.66, ' ',7470365.09, '兄弟姐妹',-11240603.7, 'c0',-636.7011, 'be',-159494529.30)), ('be', 'use', map(b'10001',-544.3, '1000',1205.482, '1000',31681727.3, 'can',539190.5, '😀😀😀😀',2706644336.8046, 'was',-746.651, '0',1.5)), ('was', '', map('c0',13.0, '0',45.17, ',',-5.48, b'100',-1363.64, 'is',4516498104.9689, x'c328',40917301216.703)), ('c1', 'are', map('1',-198091684.1394, '😀',7335.5235, 'use',-35234.004, b'101',-57.91, '0',5479076.48, 'can',-4205546.3052, 'have',6891593.135, '',-1073.34, '0',2928102422.054)), ('1000', b'10001', map('c1',6656649.0, 'c0',6642718757.21, b'100',-3895530.5421, '0',2.9129, x'ff',-36.14)), ('10', '0', map(b'100',890.14, '1000',658319119.92, 'c0',-20830386.5816)), ('was', 'use', map('1',5.01, 'said',-10890691.72, 'had',-583863.6)), ('10', '0', map('名字',-4.5679, '',-181593369.233, '兄弟姐妹',9055.7, '😀😀😀😀',-25525432920.10, b'101',9.7705, 'c1',19390814508.015, 'be',3200198753.31, x'e28228',-22711361.06)), ('1000', 'c1', map()), (b'100', '', map(b'100',-7097812.2899, 'said',9632271.60, '10',-6805060.24, 'was',-95754484291.1079, 'is',-14513418010.529, '\n',-85125.040, '名字',34900867.2, 'c1',-443642.2304, '1',14783.0867)), (x'e28228', '', map('are',8866812320.67, '11',-49331069.6, '10',92585824222.9729, 'had',-262.5830, '1000',-3.1, '\n',-3867299614.0, ' ',2306.624, '😀',8280708.6, '😀😀😀😀',-49699574683.02)), (b'10001', '0', map('1000',-47223052.0925, 'c0',81.8, 'are',-14.8, '😀😀😀😀',129683740.1, 'had',1147.5873, '名字',26743.53, 'said',-17293818304.2563, 'have',758097495.8257)), ('😀', 'c1', map()), (b'10001', '', map(' ',-862765786.905, b'101',-68421545744.2, '1',4849.7, '兄弟姐妹',37.1304, '\n',8505.460, 'are',42104048.6, '1000',671.1240)), ('10', '', map('had',61543628.8553, '11',-54339342507.637, b'101',186.1, ' ',718.7406, x'c328',-6989.09, 'be',582374959.1, x'c328',-5283.521, 'c1',-115.0583)), ('名字', 'c0', map('were',-4758047452.12, '😀😀😀😀',-595.11, '10',790.481, 'c1',7563.4859, '😀',4261.0121, '1',477.347, 'c0',-7.7959, x'e28228',-8653979547.4, '10',561.740, 'is',3305544.18)), ('are', 'c1', map('11',-8.417, ' ',9614357.92, 'said',-3820.534, 'is',-18087.2695)), ('had', 'use', map('had',-2.35, 'c1',4765934321.550, 'said',-71607029.3)), ('said', '😀', map('are',88012.251, ' ',82057650.712)), ('名字', 'c1', map(',',2334.31, '\n',-250685702.5, x'e28228',78637.111, '-1',74.1, 'had',-597.75, 'be',5081.2, 'c0',-295532530.973, '😀',-51963017206.36, b'100',-2939616786.7920)), ('1000', '0', map('were',-691.0, '-1',3172.27, 'have',-9884.630, '\n',-2.537, ',',-781068.7, 'said',84020.68, 'are',-834.4, ',',-47.4936)), ('😀', '兄弟姐妹', map('1000',9775479157.5417, x'e28228',-1132871.2449, 'is',-3978303950.88, '11',-377012.344, '\n',-28278821.34, 'were',432395359.6)), ('-1', '', map('have',-1477874.80, x'ff',2516767449.25, ',',182977.10, '10',11026158021.11, ',',54854442.729, 'are',1386.78, 'c1',71.01, '兄弟姐妹',13.5, 'c1',-16192011.3965, '\n',41095634682.96)), (x'ff', b'10001', map('-1',-30983.1, '\n',-925650294.7, '0',50.4)), ('be', 'c1', map()), (' ', NULL, map('can',-53475.4119, '',-40262.4, 'were',11.4)), ('1000', '', map('名字',-89.699)), ('c1', 'are', map('c0',-619.9, 'use',570.32, '-1',-5405273636.44, '1000',43041025.7, 'can',-10.601, ' ',44946720336.3921, '10',-32531.504, 'was',-71013225208.42)), (NULL, 'use', map('is',-555939754.8, ' ',2541842.86, 'said',72192722.2644, '0',5878.9, 'said',224768354.34, 'had',142649101.415)), ('be', 'said', map('兄弟姐妹',-58.91, '😀😀😀😀',9387040.6765, '11',-1.5, 'was',-58.7, 'use',7622.446)), (x'ff', '', map('be',73428772.0266, b'10001',-4329.32, ',',-7.770, '\n',342444.1925, '11',-6572584.623, '\n',9412.0583, ',',74718683612.1590)), ('had', 'use', map('1000',155.262, 'c0',4.6271, ',',-19339707858.4967, b'10001',-12527659012.2926)), ('are', '0', map()), ('1000', b'10001', map(',',5561.3601, '😀',911960480.38, b'10001',4.966, b'10001',-61.569, '\n',5493.868, '😀😀😀😀',2435376010.826, 'have',-42858352.22)), ('-1', 'said', map('😀😀😀😀',-15.875)), (x'c328', 'c1', map()), (',', '兄弟姐妹', map('11',4474974.709, '10',-510468050.0, 'use',-2740.40, 'had',2187.05, 'have',19119183269.0, b'10001',130494919.6304, 'be',607086954.4196)), ('10', '兄弟姐妹', map('had',-1376937.04, 'had',9187689605.580, 'had',5420.7309, 'be',-953648965.0890)), (x'ff', '😀', map('can',-12336628559.7, x'c328',16157.6, 'is',8007505.36, 'use',-438115339.0839, '0',5459884847.2, 'c0',14400.56)), (',', '0', map('兄弟姐妹',-13.2, 'be',863251.3, '0',10.7, x'c328',77724.1, 'was',-537133941.1, 'be',8346.64, b'100',-9.609, 'is',-2.9582, '0',5806.1757)), ('had', '兄弟姐妹', map('',59966671.2526, 'c1',-93.6, '1000',4.67, '10',73982.5816, 'be',20.1, 'are',23663.507)), ('1000', '', map('😀',14999.0, b'101',9.89, '-1',46715233411.052, '-1',8577.47, 'c1',-7994569168.1)), (x'ff', 'are', map('are',-264905.9, '😀😀😀😀',92.807, x'e28228',-7.9)), (b'100', 'use', map('is',-3673.1050, '-1',3998012498.3, 'be',56488548091.09, 'c1',732.43, b'10001',7429702357.0905, '-1',78349808.8722, '名字',96453535283.5866, 'were',7464375384.99, 'were',51257001.55, '1000',117.880)), (b'10001', b'10001', map('10',-52960.299, x'ff',71.3, 'c0',69316.326, 'c1',-5996.495, ' ',-6.09)), ('said', 'use', map('have',33752277387.267, '',-98606184.2, 'have',32188235.751, '-1',741.5, 'can',10023657.0017)), ('said', '', map('0',-9595.7, '1',250488725.76, x'ff',-837303858.96)), (b'10001', 'said', map('-1',-2206271.4, '😀😀😀😀',57141476223.8, '兄弟姐妹',-768267177.267, 'be',75323616.8929, 'be',53395037735.5826, 'are',4.28, 'had',-135425.738, 'had',77.64)), (x'e28228', 'are', map(x'ff',-94591191978.296, 'is',5633186114.4183, x'ff',-977512023.56));
INSERT INTO TABLE t0 (c1, c0, c2) VALUES (x'c328', map('are',-124973410.560, 'had',-39767686.9, b'100',-41290.154, '\n',-96968.65, '1000',-300999.2, 'use',-3.244), 'c0'), (b'10001', map(x'ff',-363505664.174, ' ',37.30, 'can',-559333.6, '\n',74992444.1860), 'use'), ('-1', map('c0',-9378132410.99, '😀😀😀😀',595.070, x'e28228',-11.0, ' ',-4613669180.006, b'100',-3155502879.890), 'c0'), (x'e28228', map('😀',-523.4), '0'), (',', map('10',88.441, 'c0',-8648635423.12), 'said'), ('名字', map(x'e28228',-66.3218, '名字',-1993182.8900, '0',-434.3, b'10001',30.8131, '1',7518669.9, 'is',32908.1974), 'are'), (x'ff', map(x'ff',-4.373, b'101',93875485.3, 'are',-7.79, 'are',-9472.4, 'said',4942351.4917), 'c0'), ('had', map('😀😀😀😀',72.6436), '0'), ('c1', map('',1497308583.3, 'c0',3262.317, 'is',7040041381.6207, b'10001',13.97, 'is',-8411323.56, b'101',4448552.199, 'were',-25546074.5, '\n',1986286606.9, '10',-37619037.29), 'use'), ('was', map('have',-58489658.14, x'ff',7401797.4), 'c0'), ('are', map('have',860.581, ',',-345.8, 'said',2.797, 'had',-18.697), 'c1'), ('c1', map('兄弟姐妹',1640750.5147, 'can',165.8, '-1',14641828.0), b'10001'), ('was', map(), '兄弟姐妹'), ('said', map('\n',36508854446.7216, b'100',-67.2, '0',43550783.9), 'use'), ('😀', map('be',137.85, 'is',8793534.443, x'e28228',-42311.03, '1',43040852952.27), '兄弟姐妹'), (',', map('use',9.0, 'be',1874442700.69, ',',-818.45, '1000',-23.9, 'was',5464552864.414), '兄弟姐妹'), (',', map('-1',1385.26, x'c328',91744.13, ' ',-868.652, x'ff',-186.08, '兄弟姐妹',-7590.927, '10',61330506267.309, 'are',1571902402.198, 'were',-1.4256), '0'), ('😀', map('c1',433.68, b'100',-93151968366.35, '😀😀😀😀',84225883.309, '-1',11.26), 'c1'), (',', map('use',75.15, 'c1',6304.549, b'100',184891100.31, '\n',-5635.7, 'use',115969298.6868, '1',-2079.1681, 'are',1866304.8162, ' ',-184.9992, 'c0',926888.91, 'had',2.6264), '0'), ('had', map('be',1105.4987, 'said',13.506, 'had',-1925.907, 'is',2177318.14, 'c0',1008.9, '',6400690.0), 'said'), (',', map('',5515930619.217, '\n',-1357872.947, '兄弟姐妹',23.9), 'are'), ('10', map('😀',-50040804634.9350, '11',-3990176741.9935, b'10001',-67277.7), 'c0'), (NULL, map('😀',-89534014.88, b'100',-5376695918.290, x'c328',447311948.5317, 'was',257559.127), '0');
INSERT INTO TABLE t0 (c1, c0, c2) VALUES ('名字', map('名字',-17374452389.91, '兄弟姐妹',315.35, 'c0',25491288.295, '1',802.05, '10',-590.38, 'c0',-1313057.42, '11',-30366563.4841, '😀',-1255999778.1, b'100',439.817, 'was',-48.868), '兄弟姐妹'), (x'e28228', map('c1',-30662360.9, '',-6398072843.24, 'said',-2.6, 'have',274697.9452, '名字',-14.82, 'was',8382150865.7, '11',-17772.18), 'c0'), (x'ff', map('1000',-11808.206), 'use'), ('had', map('can',-7.701, '0',14.9, 'is',5.59, x'e28228',6969130.16, '0',-6536336415.5561, 'have',-92082.02, 'have',-8.41, b'10001',-1206393.556, '1000',-32261.2, x'e28228',-144.103), '兄弟姐妹'), ('is', map('be',2.53, b'100',7588.30, '10',-75472.5008, 'can',-4.8, ',',-66.108, 'were',141.8579), '0'), ('had', map('said',92070277.8072, 'are',-10308694817.32), 'c0'), ('are', map(b'10001',-4638975561.1006, ',',1167.2029, 'can',-90.8, '兄弟姐妹',31531.2430), 'are'), (x'ff', map('兄弟姐妹',787034978.2188, '\n',-239.8051, x'e28228',139682.1, 'c1',1675.16), ''), ('said', map('are',3560.7, 'had',421164606.17, '😀😀😀😀',985081174.8), 'are'), (x'ff', map('was',195922274.4, 'had',23817017781.95, '0',-52634885.03, b'10001',-38290829169.142, b'10001',4723901.2, '😀',546.0066, '-1',8.312, x'e28228',-549.5, 'can',-182686.7, 'c1',1.9), 'c1'), (x'c328', map('1',-2712.08), 'c1'), ('😀', map('had',-33809632.816, 'use',-62008.6749, x'c328',-524862.708, b'10001',-9169042.49, x'e28228',-5675.8, ' ',-9472247781.08, '名字',4209.5, 'be',-57.5), '😀'), (x'e28228', map(), NULL), (b'100', map('were',-91.15, '😀',-86.901, '1000',4258931.0), 'c1'), ('名字', map('c0',20159478.53, b'10001',5068826.898, '1000',6608663904.0195, b'10001',-979.4821, 'were',1931515941.257, b'100',11.913, 'use',-9156204943.4688), '😀'), ('was', map('10',-6166.426, '1',-846133.2907, 'said',87.00, 'be',4218657476.2), '0'), ('名字', map(x'e28228',5.519, '10',17.0, x'ff',-4028050445.2556, '\n',-1442.39), b'10001'), ('had', map('are',-16424076.482, x'c328',-15.6, '',-27.8458, 'use',6648641.08, x'e28228',-977.105, '',81058368.6060, x'c328',-37362155082.6446, b'101',-1.582, '1000',10423243.8107, 'can',1720147487.6745), 'are'), ('is', map('1',73832925.8, 'had',-91364159.09, '\n',-9081.255, '0',-40112834369.251, 'can',16148.4496), b'10001'), ('😀', map('c1',7265462.4, 'c1',5798.198, 'be',-25438775.6503, 'use',-49998363953.19), 'use'), (x'ff', map(b'10001',64230012.1028, '\n',-84565.77, b'10001',-1685054261.8713, 'be',1.3), b'10001'), (NULL, map('兄弟姐妹',8438.1422, '\n',-902.0931, '0',1326212657.4583, '名字',-2437.991, b'10001',-733294506.3, '11',96279456677.79, '\n',397.7), 'c0'), (',', map('c1',3814.04, 'was',343320919.1, '',73661026758.5882, b'10001',-47276.016, 'had',1276261342.8, '-1',9.595, x'e28228',-2.534), NULL), ('名字', map('',-27409.15, 'can',7.58, '\n',4370890098.994, 'are',872.481), NULL), ('are', map(x'e28228',3364625062.535), '兄弟姐妹'), ('😀', map('兄弟姐妹',-2892747.2, '名字',-39321608927.7, 'is',13735180267.733, 'is',236017.750, '\n',-4029.0, '10',5036187573.120, '名字',-29520791204.81), '😀'), ('said', map('be',155.14, 'was',-485820.2245, 'be',315813.58, '0',964.405, 'was',-14544849.3), '兄弟姐妹'), (NULL, map(), 'said'), ('be', map('said',9647960.053, x'e28228',9623224640.36, '10',-93.0374, b'10001',-755103.4, '😀',20014925.6289, '兄弟姐妹',-36704917045.7, '😀',-97121.645, '1000',580412.510), b'10001'), ('is', map('be',-7911.458, 'be',7.1006, 'be',68.2, ',',5499272020.5, 'were',-6511.26), 'are'), (',', map('-1',-65421849066.3496, 'were',-16040693351.74, 'said',-48906631.596, 'use',-9094.12, '名字',-1343720.761, 'said',6586328.5984, '😀',2192729.2), 'said'), ('10', map('10',-44.9, '😀',64549.9, 'c0',6.465, '0',-65560545.0, 'are',-563638917.12, '11',-936026.14), b'10001'), ('said', map(' ',8585184667.5879, '😀😀😀😀',-7522.7559, 'said',-395980571.686, 'is',12.2, '\n',-37462.6), 'said'), ('are', map('was',-4622.770, 'were',-36556260373.87, 'had',6853.1564, '名字',69804570.33, '1000',77735390.60, x'ff',-1060.985, '10',2668918.78, b'10001',3270490.7, 'be',12.39, x'ff',1449653702.753), NULL), ('had', map('c1',-74119.8811, 'had',23.907, 'are',-809.208, 'c0',-747.1047, 'use',4281645.7, 'have',-925842088.4, b'100',-9492126.364), '😀'), ('😀', map(b'100',7186123.69, x'ff',-885880.684, 'can',6081524.7348, '0',7351363.5435, 'were',774027.8, '\n',8094325048.5566, x'ff',-136655105.675, 'were',5182.15), 'c1'), (b'100', map(x'c328',1362794.2296, 'use',-74551481332.607, x'c328',-30022495.61, b'100',-767994196.2, b'10001',-5.971), '兄弟姐妹'), ('are', map('c1',49.2, 'had',-108048502.5), 'c0'), ('1000', map('are',9904.6833), '0'), (b'10001', map(), 'are'), ('said', map(x'ff',43.5, b'101',-68821.5866, '10',-7446865.181, ' ',-8.82), b'10001'), ('said', map('is',45383.6, '10',3119.1, ' ',-660883088.6098, 'is',-75438.4, '',3035253059.7497, b'101',-61.74, '0',-77008084.9), '兄弟姐妹'), ('is', map('were',-4441079998.354, x'ff',36214377.80, x'e28228',-658.41, '\n',3372.68, 'have',15727756282.18), NULL), (x'ff', map('is',32557429.4, x'e28228',6112.42, 'c1',22.75), '0'), (' ', map('兄弟姐妹',23147.20, x'ff',-2707.477, '\n',221.4, '😀',408959.84, '',-183141.9337), '兄弟姐妹'), (x'c328', map('had',-1442.7066, '0',489830238.63, 'are',636691.91), ''), (x'c328', map(b'101',-5581.1, 'had',-895.857, '10',88.5, 'had',4704314923.546), '0');
INSERT INTO TABLE t0 (c0, c2, c1) VALUES (map('11',244.319, 'have',3503.8346, x'ff',8.2, '-1',-11069.49, 'c0',-518.236), '😀', 'c1'), (map('be',17762445132.76, 'c1',995.6570, '-1',3.3), NULL, b'100'), (map(b'101',10873890892.3), '兄弟姐妹', 'be'), (map('-1',10183.05, ' ',182.840, 'was',67189064.22, '-1',-8986000.1110, '0',-4640679.17, ' ',1585719.37, 'c0',2236996966.8774), '', 'are'), (map(b'100',85166401033.381, '兄弟姐妹',474.01, 'c0',-9664.3, ' ',-6.11, b'10001',-14085759493.776, '10',-3.2), '', 'said'), (map('are',-16726647.8802, 'are',1.4, 'c1',-121818.807, '1000',73515184143.24, 'be',-64581791119.43, 'be',881.0080, '-1',-70331.42, 'can',-2317.699), 'said', '-1'), (map('c1',-74.87, 'was',6.112), '0', 'are'), (map(' ',-5925.68, 'be',-87.8, x'e28228',-178613.17, '兄弟姐妹',35449856523.247, x'e28228',4.05, 'said',-9.68), '兄弟姐妹', 'had'), (map(), 'are', x'c328'), (map(), b'10001', b'10001'), (map('名字',25.2, 'had',-43559829.885, '10',-92542.71, 'can',-899397182.830, 'have',78.2, '1000',-9010385464.2, 'have',820.94, 'had',738226.9683, '名字',-32309.60), '', x'ff'), (map('',12.8867, 'can',33143159613.1, 'is',1.44, '1',-9.44, b'101',-592775721.63), '', 'are'), (map(x'ff',-7274778066.17, 'use',-57452700.8189, 'c0',-120.159, 'were',-9.45, 'c1',1493.4, '😀',-684307.850, 'be',165.5, '',-7215702739.331, 'said',77834669789.327), 'c1', 'be'), (map(b'101',95.780, ' ',-1.78, '名字',26965.41, '😀😀😀😀',-2973070820.745), b'10001', '😀'), (map('c0',1746.62), '0', '😀'), (map(), 'are', 'be'), (map('0',-77660949.83), 'c0', 'had'), (map('',473.5698, b'100',4124976687.3, x'ff',736932643.39, '😀',15875928.2956, '\n',751024864.50, b'101',1864398449.6, '11',102339715.9254, x'e28228',-668370899.80, '\n',71514879732.78), '', '-1'), (map('have',9060777.1998, 'was',9.13, '0',-343198.572, 'are',-47640974.6, ' ',2871709.1271, 'was',-51586.1, '10',-353733.9, '1',105.649, 'had',66641313366.135), 'said', ','), (map(',',83706.3388, 'use',-26346389490.35, 'are',82.4, x'e28228',-6208263557.62, 'be',-1.418, '0',-36755.04, 'is',-802999.21, '兄弟姐妹',-8283.917, '😀',-197254.1855, 'had',-16430.1), 'use', 'was'), (map('10',-47758820116.7710, '10',7.1951, 'said',-62354.0, 'c1',71669.49, 'are',-64970181652.7, '😀',17.9320, 'be',-57195459581.4, '\n',-263.8891), 'use', '1000'), (map('is',31.9, '😀',-847.8173, '',-43539.1, 'c0',-5337809474.968, 'said',-788798.1), 'use', x'c328'), (map('have',825.0923, '😀',20283587.35, b'10001',788111.93), 'said', 'had'), (map(), '', '名字'), (map('were',167.7281, '\n',7834011453.1907, '1',7533498.645, x'c328',1.3, 'c1',-54609.6308), '0', ','), (map('1',66613107.709, 'were',4924285307.9, 'had',811.031, 'c1',1.1, '😀😀😀😀',114.959, 'have',14865.7183, 'was',-585.6, 'use',-97.1, b'101',92549323.169), 'c0', NULL), (map(x'e28228',87.193, '😀😀😀😀',1179014.1, b'101',-13777.3, b'101',-1.974, '\n',412895.4384, '-1',-5183167.31), 'c0', '名字'), (map('said',82604959.8), 'c0', 'is'), (map('was',76.13, 'c1',-60516835849.78), 'c0', b'10001'), (map(' ',264.81, '1',8855888657.3751, ',',-496300668.8515, '10',4671.91, x'c328',-9334095242.50, 'c0',-2925693.4), 'c0', b'10001'), (map(b'101',76.6), 'c1', '-1'), (map('c1',-374795.6, x'ff',-4.1183, 'had',67.3, 'were',6387688773.0, 'were',-543.74, 'said',-32.2, '11',447994662.90), b'10001', x'c328'), (map('c0',1239796.357, x'e28228',-6986573734.5), '0', b'10001'), (map('0',-7.9, 'said',35571.027, ',',121668.6, '-1',-2905844552.7, x'e28228',-91525530404.3, b'101',-387657715.167, 'use',613924.51), 'c1', '😀'), (map('said',-5251321.1, b'10001',-5318808.258, '10',-4.7, b'10001',-20801161.9285, '😀',-647.389, '0',-86220101.31), b'10001', b'100'), (map('0',-2752675.3536, '😀',513364.2302, b'100',1828590704.46, '',8167100.9977, '10',1.6113, 'use',8.9, 'use',-2949.582, '\n',2173755.035), 'use', 'said'), (map('have',8.503, 'were',-5252.3, '-1',6206017.70, b'101',3373848.7, b'100',-200601285.5593, b'10001',-10459741.9540, '兄弟姐妹',38127682520.75, b'10001',-77986056851.8222, b'10001',-4.0636), '0', NULL), (map('10',137129379.36, 'are',-9835361398.26, 'is',8527.27), 'c1', 'had'), (map(' ',-52883247720.55, x'c328',23293872356.696, b'10001',-187736.13, 'have',9137267488.301), 'c0', '名字'), (map('11',-22881346831.165, ',',-994571500.736, '名字',14696706383.7, '10',-103854.418, '😀😀😀😀',66779468345.2165, 'is',-172.5, 'c1',541514941.2, '\n',-91420.136, 'is',87515403.3082), 'are', 'said'), (map('0',1110799489.2, '10',869546632.8, b'10001',30552443616.5613), 'said', '-1'), (map('1000',98804607494.5, 'use',-76.2, '1000',-10656.67, x'ff',161179678.7, 'have',-87635.4859, 'had',9.32, '😀😀😀😀',53.0, 'is',-396049.5), 'c1', '名字'), (map('is',-896965.368, '😀',8.4522, '11',8390503074.67, 'was',-31734.9, b'101',-139.958, 'can',7044818.90, 'can',11132777.21), 'c0', '10'), (map('兄弟姐妹',-91001879544.47, ' ',-48.4, b'100',-8.296, b'10001',24111367.254, 'c0',499836.2, '😀',-41154.2, '😀',-6495137101.1), 'said', 'c1'), (map('be',-37689090893.5, 'had',-52061501568.94, '0',3.396, '0',-6279378132.1648), 'c0', '名字'), (map(x'ff',-7191101.2, '😀😀😀😀',-201230284.595, ' ',-37744335.15, '11',-42.95, 'was',720.93, '0',16405451673.5, 'be',-8307771802.3, 'said',605185.3, 'said',3974.525, '',-1490383013.6415), 'c0', 'are'), (map('',11924.990, 'be',2642189759.03, '名字',47787233.49, 'are',-80.09, 'is',313833454.4, x'c328',8010891.4020, '\n',-267619.0721, 'c1',5570187.9), b'10001', ','), (map('had',-1.7, '',431.7), 'use', 'c1'), (map('c0',-69890.03, '\n',-58608.992, x'ff',-16912.8, '11',94559336.0212, b'101',-908.6270, b'10001',461294.60), '😀', 'said'), (map('😀😀😀😀',2806.3, 'use',-45699.3, '1',60.742), b'10001', '10'), (map(',',69900579928.08, 'can',613.3191, b'101',-36374399.647, x'e28228',-7535609.2, '名字',8663381693.497, ' ',74.241, b'100',35529012.0, 'use',53103.11), '0', 'said'), (map(x'c328',-42.922, b'101',678.421, x'e28228',-265706.85, 'can',-13546798214.661, x'e28228',-2123743622.542, 'have',-18060409.0), '兄弟姐妹', 'said'), (map(x'c328',-8.79, 'can',1615106290.280, '11',-848955.2, b'101',5100.33), '', b'100'), (map(' ',-9.7378, x'ff',43.8), b'10001', NULL), (map('\n',-625969898.57, b'100',-5614.0062, '名字',-1516.07), 'c0', 'said'), (map('-1',-8857931314.813, b'10001',12880.4955, 'are',45811439.686, x'ff',-13.4, 'was',5.5029, 'is',-60.6, x'c328',99.7780, '😀',9704.20, '\n',-697.00), '😀', '-1'), (map('have',-4900.0514, 'were',332994721.580, 'are',-78.0, 'have',57.835, '名字',-64.7145, 'have',42.5), 'c0', ','), (map(x'ff',86811755.286, '10',-1781.4, 'can',-3754992.34, x'e28228',-402736.102, b'100',139.4, '😀',-81.89, '\n',-19434052559.4, b'101',-75797406.5618), 'use', '😀'), (map('-1',368.1689, x'c328',-6215379.596), '0', b'100'), (map('10',-681117492.6, '兄弟姐妹',763137.3, 'are',139810950.6825, '\n',24888.2, 'can',-4167792.61, '1',-61425927744.1199), 'use', '1000'), (map('had',-145.321, '名字',14.40, 'can',6767064652.46, 'are',1332516.1, 'said',-928286029.0788, x'ff',-4897644.0131, '兄弟姐妹',596547.2960), '😀', x'e28228'), (map('said',87.6, '😀😀😀😀',457165545.606, x'e28228',-56627572.2, b'101',1935.7, 'can',-9695.47, b'10001',-1867095039.3361, 'can',9163209694.391, x'c328',978.57, '😀😀😀😀',-4956890.5), '兄弟姐妹', 'c1'), (map('c0',30.23, 'were',1618513823.18, '1000',188.11, 'said',9353670.5894, '-1',7820517.0), 'said', '10'), (map(), 'c0', b'10001'), (map(b'10001',2377.2030, 'were',406310649.37, '1',-77451721464.1, 'had',10.336, 'c1',4518.6256, 'were',13434246.0398, 'can',1868698019.04), '兄弟姐妹', '名字'), (map('10',-634.9, ' ',74.8, 'are',420148124.14, ' ',9738453.828, 'were',97.3088, ' ',2.32), '兄弟姐妹', '1000'), (map('c1',22819301.8, b'10001',54.91, '😀',5734857.4376, 'c0',-9939356910.0), 'use', 'had'), (map('兄弟姐妹',-49923.5616, 'were',19593555.0383, '',-63325.402, 'can',-1006617.0, '😀😀😀😀',8194917484.0), 'use', 'are'), (map('were',5056133.487, x'ff',65794.28, 'c0',365101.5), 'c0', 'be'), (map('said',-89.1916, ' ',-19302.9910, 'said',-9609221.6342, '-1',-1961208.9, '1000',688460.363, 'c0',-36124122097.02, 'had',899155273.35, ',',8228871344.854, 'were',-74170.454), '兄弟姐妹', 'be'), (map('be',9159.86, 'can',-17329.0200, ',',-7016462567.5758, 'can',-9329168.1999, x'e28228',-190017.9, '1',794.847, '-1',741030944.12, 'were',230242.5641), '0', 'is'), (map('use',-909.241, '0',199429.6, 'was',64056415.9105, '1000',5089542932.091, b'10001',979.1, x'ff',-78264645.3, 'use',-83099448506.0), '😀', 'is'), (map('兄弟姐妹',647.2, ',',-454799115.64, 'have',-1411471692.159), b'10001', x'ff'), (map(b'100',-708509789.3208, 'use',-655622187.133, '',-7973.2, ' ',-289281.3), 'are', 'is'), (map('be',613326.0813, b'101',-34669.380, b'100',9732110.2, 'are',-900311062.3823, x'e28228',7366020687.189), '0', 'is'), (map('had',29865.756, b'100',9.9, '10',-470396820.8, 'were',-92.799, x'ff',-4111341426.786), '0', 'is'), (map('兄弟姐妹',3721.1, '😀😀😀😀',-3.414, 'have',-95.448, 'are',-46678879593.432, 'is',-81321840351.7, 'c1',1205.50, '-1',822.32, b'101',481276.09, 'had',93297952.26, 'is',-3622085518.9), 'said', b'10001'), (map('have',474626.627, 'is',11250.06, 'have',16.704, '-1',-1166.63, x'c328',433.99, 'were',33022161.30, x'e28228',5.0, x'ff',9537368933.12, x'e28228',3.4), '😀', ' '), (map('have',9277604.42, 'were',33582889552.046), 'are', 'be'), (map(x'e28228',39.3727, '😀😀😀😀',56.639, '😀',-99828619971.7, '😀',-577.42, 'were',-7.9641, 'are',-4295.9, '1000',-6129414410.6654), b'10001', '1000'), (map('can',-4.90, 'c1',90.75, 'use',2977545977.670, x'ff',2.36, 'is',-1.48, x'ff',47459.2541, '11',-687.6, 'use',-746208.69, b'10001',2159.7615, x'ff',-15.5), 'use', b'10001'), (map('兄弟姐妹',-3.974, '1000',15.753, '名字',-54.333), NULL, '10'), (map(x'ff',-74.208, b'100',-98739.27), '0', '-1'), (map('were',93.32, b'10001',-84260511.41, x'c328',-68645712322.6, '0',-5335523137.79, '1000',91049.362, 'was',13201815958.73, 'can',-21883691992.0430, 'c1',642.2956, 'had',-92800240.1804), b'10001', 'is'), (map(b'10001',-646166634.20, 'was',811743029.62, '兄弟姐妹',979.2168, 'had',94.3, 'were',-9493001.60), 'said', 'are'), (map('c1',9013.8028, 'have',50051.0796, 'use',-22928370871.99, ',',305312.862, b'100',584.30, '0',-1792.0243), '', x'ff'), (map('0',797.701, '1',271314.6, '兄弟姐妹',4951507269.4302), '兄弟姐妹', x'e28228'), (map(x'ff',731531216.76, '名字',58438.41, 'said',-440337.71, x'e28228',-573839.795, x'e28228',-1481.2), 'c1', 'had'), (map('😀',6253620.06, 'are',-103507976.7, '兄弟姐妹',-41.103, 'are',172940892.5, x'ff',9904354070.2885, '-1',1.8389, 'is',1.8), '😀', '名字'), (map('be',-112.5393, 'have',5938612.2665, 'had',-79946565.47, ',',-1.10, 'are',-5.6, 'are',33628.8), '0', x'ff'), (map(), 'use', NULL), (map('',8309.9160, b'101',14.130, 'is',6400385662.490, '-1',-174.600), NULL, '😀'), (map('were',78144724.01, b'100',3.4290, x'e28228',334.710, ' ',7052953015.149, 'was',80214.263, x'e28228',464353.51), '', 'is'), (map('use',391145276.5, 'had',-27927701.9, x'c328',-9204311.8, '0',-15988.6, '😀😀😀😀',14891661.48, '\n',694.8211), 'use', 'was'), (map('are',126.2911, '',1633091.02, 'is',-44901.8, b'10001',-692.5946, x'ff',-24743081.2, ' ',62376.8, '1',1806202.5, b'101',124.8, x'e28228',871654175.4), 'use', '-1'), (map('were',-1382231.091, 'is',146.7, '1000',-52421.2862, 'is',156319842.9, '😀',-72.5322), '0', 'c1');
INSERT INTO TABLE t0 (c0, c2, c1) VALUES (map(), 'use', '1000'), (map('0',23032.0244, b'100',-8809869.44, ' ',105723.1848, b'10001',-32417041280.24), NULL, NULL), (map(b'100',931568.9431), 'c1', 'are'), (map('名字',-458.7, 'are',6359.237, b'101',-64095645.068, b'101',1.5448, '名字',56.0, ',',-15754664700.6569, ' ',8486.5128, 'c0',-35773.7, '😀',-5603.7, 'c1',-49098366872.60), 'use', ','), (map('1000',648.1, '',353510498.2, 'have',-2.088, '兄弟姐妹',14.1), '0', '名字'), (map('have',-1.7, b'101',59.56, '兄弟姐妹',5335.125), b'10001', b'100'), (map(), 'use', ' '), (map('\n',56074075.626, ' ',5729453609.004, 'were',-9851.7556, '兄弟姐妹',-330.492, '\n',-9422855.6961, b'100',669801914.091, b'101',151776.4), 'are', b'100'), (map(',',-94.8542, '😀😀😀😀',1802771.62, b'101',-2069391136.800, '😀😀😀😀',-3290.75, '名字',997151807.7, 'were',-15549.654, 'use',1.6893, '😀😀😀😀',-696.70), 'are', 'be'), (map(',',8878411800.5, 'can',936.74, ' ',-56646646.2, b'100',-95129580.4, '10',67696.8865, 'were',50879954.01, 'c1',-97.1692, '1000',79545223.0698), '😀', 'c1'), (map('名字',786.3169), 'said', ','), (map('have',30.3728), '兄弟姐妹', 'be'), (map(b'100',-5422.31, x'c328',9.637, '\n',4730789.4757, 'are',-65.92, '',9124894908.5210, 'were',4.68, 'c0',-1.5599, '名字',4822.85, '兄弟姐妹',-50383.596, 'use',478097.993), 'use', 'is'), (map(b'10001',-42041060990.712, 'have',-8.8, '😀😀😀😀',-62.83), 'said', '-1'), (map('c1',-842.4645, '1000',59.6, x'ff',2904857960.0, 'be',6294.1, '😀',4.2555, 'were',2913.585, '1',-5567655438.887), NULL, 'be'), (map('be',89075673700.105, 'c1',17406.9080, 'can',-863849414.6), 'are', 'had'), (map('c0',-10241099.4568, 'use',-16961.859, x'e28228',-35.724, 'was',-5186168201.9, ',',1541700.9322, 'be',992133.5, 'c1',-8346862.80, '',80.9), 'use', x'c328'), (map(x'e28228',24315813.2, b'101',16140311219.0135, b'10001',129.7037, '1',840955.681, 'is',1158427.151, x'e28228',161734868.9050, '😀😀😀😀',22192570282.291, 'can',-2039942.71, 'c0',6.4845, '-1',7986544.308), '兄弟姐妹', 'had'), (map('0',22765061652.2, x'c328',-180088.4), '', '😀'), (map('use',627608000.8415, 'be',-80944480.1, '兄弟姐妹',4685176.48, 'can',19686.01, '😀',-8.8200, 'use',13.8, 'had',-9799911.4, b'100',-2373087814.5234, x'c328',841269725.240), 'said', '-1'), (map('11',8386641.0105, '😀',405373948.7236, 'c1',-558588.61), 'use', ','), (map(x'c328',1.8715, b'10001',-17451.423, 'c0',28488925.492, 'be',-172745.1242, 'is',786755.1599), '😀', '10'), (map('are',-55887271.62, '11',-7473199.24, ',',27406.056, 'were',-39577751751.412, x'ff',-19582909.195, 'is',6.96, '10',-33.0, '',-961.761, 'have',137.95, 'c1',-783363.24), '0', 'was'), (map('are',40.4266, '兄弟姐妹',510043381.43, 'use',4.9, x'ff',102530.850, 'said',149.399, 'is',-2445006860.857, '兄弟姐妹',61893742679.35), '0', x'e28228'), (map(b'10001',-322452485.4007, b'10001',-6290155.1082, '\n',-2214.47, 'can',56554187330.94, x'ff',-2.3, x'c328',8571335.506, 'have',93.1, b'10001',-84048.9), '0', '-1'), (map('11',-82737998119.2, 'be',4136908.066, 'is',-1920911.2, '名字',63.2, '',132.7, 'can',-950039811.6258, x'c328',1.10), b'10001', x'c328'), (map('😀',-663670.326, '\n',480500.067, b'10001',-76144905.801), '0', '名字'), (map(b'10001',-3014854.25, 'c1',-663242.621, '-1',18.7523, 'can',-99345071720.2758, '1000',45701045.011, 'were',-3347197670.8, '1',5950972.4722, 'be',-7928574873.5, x'c328',6.008, 'had',23468192633.1900), 'c0', '1000'), (map('said',1987806901.7091, ' ',186.9037, 'use',31.404), '', b'10001'), (map(' ',-4726696276.0, '',772.7, x'ff',7287349693.6, '😀',48023073218.9196, 'are',58.1275, x'ff',4810.63), 'c0', 'be'), (map('10',50.337, '兄弟姐妹',-2930293212.90, x'ff',3620.5, 'had',-69309521.6952, x'ff',633.549, 'are',174489466.2907, 'is',-75771625.053), 'c0', 'is'), (map(), '0', x'ff'), (map('is',61757.57, 'be',813.2, '10',746344.87, 'c1',7784558505.5, b'101',-182.686, '兄弟姐妹',10956957135.8046, x'c328',-5385.0, '11',2698951170.0856, b'100',754139.2147), b'10001', 'c1'), (map(x'ff',4487582.487), 'are', '1000'), (map('1000',-9.1, '0',-70689652.70, '',-18.8, b'10001',-91.03, 'c1',-3.0445, '11',-205897.2181, '11',25.3441, 'can',-723.78), b'10001', '😀'), (map('1000',73308739472.4, 'use',47469292904.9, 'are',289136403.9527, 'can',-950462.175, x'ff',3563831.36, '1000',176520776.705, x'ff',8386347054.0, 'are',-84412268579.37, 'c0',-17605041215.72, x'ff',2486751.7), b'10001', '-1'), (map('have',-90469092339.3491), '', NULL), (map('10',-9.54, 'are',7536.0, '0',7.0367, '😀',891426.2605, '10',2608352302.51), 'are', '1000'), (map('-1',75340659304.600, 'were',-22835283.913, '0',-88.4183, '10',19082913003.299, '11',23572.035, '0',-68369.44), 'said', x'e28228'), (map(x'ff',53733.177, 'is',-3521.864, 'c1',-24044159267.01, 'was',-13235.18, '1',235.05), NULL, '😀'), (map('c0',72460582363.21, x'ff',91638756.76, x'c328',-5690589089.709, 'is',-35300.14), '', 'are'), (map(), '0', 'c1'), (map(x'ff',-30.7, 'said',6175439.34, '0',-87809.6494, 'were',720.3, 'was',40748.880, 'c1',-132954.2072, '😀',632190080.66, '10',-69193.502, 'use',-1513.16, '\n',-16757.4167), 'c0', x'e28228'), (map(' ',15.638, '10',-1883399.46, 'be',31.6364, x'ff',-4387.5360, '名字',31807967930.0293, '😀😀😀😀',965847.6, 'had',77.1, '名字',-327037641.0561), '😀', 'c1'), (map(), 'c1', 'is'), (map(b'100',26.770, 'be',79160555.5170, ',',-65099904.0, 'said',-6743.8, b'101',7047.81, 'is',5441200.5507), '0', b'100'), (map('were',8673321.26, '1',-29362870.788, x'e28228',392533.8, 'use',-6740.328, '名字',7896.3507), NULL, x'e28228'), (map(' ',21.4013, 'be',-1270785.644, ',',-27372861.5268, '1000',-10.0, '11',-69454.7, '\n',482746942.2492), 'are', x'c328'), (map('1',-32.377, 'be',-74.649, '11',334085835.7, 'had',-75495644.3, '0',-8.2, '\n',-1394.204, x'ff',639859.281), 'are', 'are'), (map(x'ff',384.39, x'e28228',-1.69), '兄弟姐妹', b'100'), (map(',',50818440264.045, '名字',-29014365550.167, 'can',-363777.86, x'ff',58881999565.02, '😀😀😀😀',-3224267181.48, '名字',979579068.9063, 'is',71482554.34, 'can',-13232.090), 'are', '😀'), (map('c1',17.47, x'c328',679940168.4430, b'101',-7080577368.1, '\n',19701.376), '😀', x'c328'), (map('can',160265573.0, 'c1',73618993.246, '0',-9282303634.2369, '1000',8559253.862, '10',200.9, 'use',69829.02, 'can',7267203.3, 'be',-295177101.1752, 'had',20941809226.72), '兄弟姐妹', '1000'), (map(x'c328',-5.8421, x'e28228',-181975921.09, x'ff',22000.3498, '',6715115.320, '0',20386.43), '', b'10001'), (map('were',825046.3528, 'was',-182723.2, b'101',73038.22, 'is',-7.4121, b'100',-52279315376.057), '', ','), (map(b'10001',-84537100.4836, 'be',486137.72, 'said',-78018253693.4, '\n',5384.76, 'have',-159705.669, '1',71678.27, b'100',-39151406030.187, 'have',7830956131.78), '兄弟姐妹', '10'), (map('10',9340.354, 'had',-52021722.71, '10',6.1, '兄弟姐妹',78106.0069), '0', b'100'), (map('10',-50342246.194, 'was',-1013.2664, 'had',-6169.59, '名字',69391110231.0601, 'are',-3684096045.43, 'had',420.13, b'101',378040.046, '1000',1927.5719), 'c0', 'c1'), (map('11',-307928184.78, '😀😀😀😀',-46121.0), b'10001', ','), (map('said',-90999.4, '😀😀😀😀',-80374654918.1250, 'had',-523.6769, 'are',4.64, 'was',-52.2, '名字',-3689.35, '兄弟姐妹',-12725914661.775, '兄弟姐妹',-14074.38), '0', 'is'), (map(), 'said', 'had'), (map('😀',-7102.1517, 'have',4199382.7, b'10001',-65185.25, 'have',-722533.9492, '0',17155775052.8, '1000',7059080.8, '1000',150.4464, '😀😀😀😀',618889.664), 'are', x'c328'), (map(x'e28228',1863519.610, 'use',85176.42), NULL, x'e28228'), (map('',-15.0496, 'are',2477957.552, 'were',-98.6706, '0',-12670547.620, '-1',97.687, 'were',77415549031.6, 'is',-22780041334.93, x'c328',76674544.121, '',-95441493.6, 'use',-67210.587), b'10001', '-1'), (map(b'101',-29616500.0, x'ff',56902347.62, 'are',92012.2230, b'101',8432.895), b'10001', x'c328');
TRUNCATE t0; --hangs
```

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by bharatnc**
Add validation to ensure that `merge_max_block_size` is > 0.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add validation for mergetree setting `merge_max_block_size` to ensure that it's non zero.

Closes: https://github.com/ClickHouse/ClickHouse/issues/81586

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeSettings.cpp [hunk 1]
```diff
@@ -2063,6 +2063,13 @@ void MergeTreeSettingsImpl::sanityCheck(size_t background_pool_tasks, bool allow
             index_granularity.value);
     }
 
+    if (merge_max_block_size < 1)
```
Comment (tuanpach) [inline src/Storages/MergeTree/MergeTreeSettings.cpp]: I think we can declare the type to be `NonZeroUInt64`. The field might have validation only.

Besides, if we check it here, can we use `merge_max_block_size == 0` or `merge_max_block_size <= 0` instead?

Comment (bharatnc) [reply src/Storages/MergeTree/MergeTreeSettings.cpp]: I made the fix to check for `merge_max_block_size <= 0`. Good point about `NonZeroUInt64`, I've now switched to use that. I'll see if the tests need fix in other places.

**Review by tuanpach — APPROVED** [review]

**Comment by bharatnc** [comment]
Test failure [AST fuzzer (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=81693&sha=16f7eb6b3da69c0767dc714d0730ce4ce564563e&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29) `— Logical error: 'Replica 1 decided to read in Default mode, not in WithOrder...` not related, bunch of other errors in [cidb](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICdMb2dpY2FsIGVycm9yOiBcJ1JlcGxpY2EgMSBkZWNpZGVkIHRvIHJlYWQgaW4gRGVmYXVsdCBtb2RlJyBBUyBuYW1lX3N1YnN0ciwKICAgIDkwIEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJywgJ0ludGVncmF0aW9uIHRlc3RzIChhc2FuKSBbMS8zXScsICdTdGF0ZWxlc3MgdGVzdHMgKHRzYW4pIFsxLzNdJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=).
