### PR TITLE
Fix bad test `01042_system_reload_dictionary_reloads_completely`

### LINKED ISSUE #67143: A test `01042_system_reload_dictionary_reloads_completely` has failed
See https://github.com/ClickHouse/ClickHouse/pull/66811

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

CC @azat
Closes https://github.com/ClickHouse/ClickHouse/issues/67143.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

File: tests/queries/0_stateless/01042_system_reload_dictionary_reloads_completely.sh [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
+# Tags: no-random-settings
+# Dictionaries are updated using the server time.
 
 CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 # shellcheck source=../shell_config.sh
 . "$CURDIR"/../shell_config.sh
 
 set -e -o pipefail
 
-# NOTE: dictionaries TTLs works with server timezone, so session_timeout cannot be used
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01042_system_reload_dictionary_reloads_completely.sh:9]: Typo: `session_timeout` -> `session_timezone`

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 4e1afb9c4d30ffb217fe3ee1ced586eefeffaa76 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66811/4e1afb9c4d30ffb217fe3ee1ced586eefeffaa76/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/66792/42ba3229b5484ebe29f4191cd5672433ba1f6588/docs_check.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/0c394d99b98d6cc1e4982ebda9335a53dd8a4a94/unit_tests__release_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by alexey-milovidov** [comment]
Needs #66785
