### PR TITLE
Fix distributed array join by nested

### LINKED ISSUE #64755: Distributed query fails with allow_experimental_analyzer and array join
https://fiddle.clickhouse.com/80cfeb73-a252-4032-9a52-c8734d7e8dd0

```sql
create table hourly(
  hour datetime,
  `metric.names` Array(String),
  `metric.values` Array(Int64)
) Engine=Memory
as select '2020-01-01', ['a', 'b'], [1,2];

set allow_experimental_analyzer=0;

SELECT
     toDate(hour) AS day,
     `metric.names`,
     sum(`metric.values`)
FROM remote('127.0.0.{1,2}', default, hourly)
ARRAY JOIN metric
GROUP BY
     day,
     `metric.names`
format PrettyCompactMonoBlock;

   +--------day-+-metric.names-+-sum(metric.values)-+
1. | 2020-01-01 | b            |                  4 |
2. | 2020-01-01 | a            |                  2 |
   +------------+--------------+--------------------+

set allow_experimental_analyzer=1;

SELECT
     toDate(hour) AS day,
     `metric.names`,
     sum(`metric.values`) 
FROM default.hourly
ARRAY JOIN metric
GROUP BY
     day,
     `metric.names`
format PrettyCompactMonoBlock;

   +--------day-+-metric.names-+-sum(metric.values)-+
1. | 2020-01-01 | b            |                  2 |
2. | 2020-01-01 | a            |                  1 |
   +------------+--------------+--------------------+


SELECT
     toDate(hour) AS day,
     `metric.names`,
     sum(`metric.values`)
FROM remote('127.0.0.{1,2}', default, hourly)
ARRAY JOIN metric
GROUP BY
     day,
     `metric.names`
format PrettyCompactMonoBlock;

DB::Exception: Cannot find column `tupleElement(__table1.metric, 'names'_String)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `Cannot find column` in distributed query with `ARRAY JOIN` by `Nested` column. Fixes #64755

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 1d77cda70b2db1041a89f7bf7537e96795084dae with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64801/1d77cda70b2db1041a89f7bf7537e96795084dae/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/ArrayJoinNode.cpp [hunk 1]
```diff
@@ -64,7 +65,12 @@ ASTPtr ArrayJoinNode::toASTImpl(const ConvertToASTOptions & options) const
 
         auto * column_node = array_join_expression->as<ColumnNode>();
         if (column_node && column_node->getExpression())
-            array_join_expression_ast = column_node->getExpression()->toAST(options);
+        {
+            if (const auto * function_node = column_node->getExpression()->as<FunctionNode>(); function_node && function_node->getFunctionName() == "nested")
+                array_join_expression_ast = array_join_expression->toAST(options);
+            else
+                array_join_expression_ast = column_node->getExpression()->toAST(options);
```
Comment (novikd) [inline src/Analyzer/ArrayJoinNode.cpp:72]: Please add a comment (maybe as a separate PR)

**Review by novikd — APPROVED** [review]
