### PR TITLE
s3queue: fix logical error "Cannot unregister: table uuid is not registered"

### LINKED ISSUE #78285: DB::Exception: Cannot unregister: table 'UUID' is not registered. (LOGICAL_ERROR)
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78266&sha=2349a12fc805b8b12cfc7b758f5bbf345da0c13f&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20old%20analyzer%2C%20s3%2C%20DatabaseReplicated%2C%201%2F2%29

```
/var/log/clickhouse-server/clickhouse-server2.err.log:2025.03.26 13:32:37.060311 [ 124128 ] {} <Error> void DB::ObjectStorageQueueMetadataFactory::remove(const std::string &, const StorageID &): Code: 49. DB::Exception: Cannot unregister: table \'6a689cea-e4ed-4d7a-8c4a-1878dae4fa56\' is not registered. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In storage S3Queue fix logical error "Cannot unregister: table uuid is not registered". Closes https://github.com/ClickHouse/ClickHouse/issues/78285.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueMetadata.cpp [hunk 1]
```diff
@@ -687,63 +686,145 @@ size_t ObjectStorageQueueMetadata::unregisterActive(const StorageID & storage_id
...
-            auto info = Info::deserialize(elem);
-            if (info == self)
-                found = true;
+            if (remove_metadata_if_no_registered && count == 0)
+            {
+                LOG_TRACE(log, "Removing all metadata in keeper by path: {}", zookeeper_path.string());
+                if (supports_remove_recursive)
+                {
+                    requests.push_back(zkutil::makeCheckRequest(registry_path, stat.version));
+                    requests.push_back(zkutil::makeRemoveRecursiveRequest(zookeeper_path, -1));
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueMetadata.cpp:763]: The main fix of this PR is here: `makeRemoveRecursiveRequest` which removes `zookeeper_path` (e.g. all s3queue metadata in keeper) in the same keeper transaction with check for `registry_path`'s version. Because another table could try to register concurrently and before this change there would be race between checking metadata `count` (ref count), seeing it is equal to `0` and removing all metadata recursively while some other table could have registered in the middle.

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueMetadata.cpp [hunk 2]
```diff
@@ -687,63 +686,145 @@ size_t ObjectStorageQueueMetadata::unregisterActive(const StorageID & storage_id
...
+        bool supports_remove_recursive = true;
+        zkutil::ZooKeeperPtr zk_client;
+
+        try
         {
-            LOG_WARNING(log, "Cannot unregister: registry does not exist");
-            chassert(false);
-            return 0;
-        }
+            zk_client = getZooKeeper();
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueMetadata.cpp:720]: Here part of old code was just moved inside try-catch, because `trySet/tryGet` actually throw an exception in case of "keeper session expired error" instead of returning the error code like for other error types, therefore this error was not retried before.

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueMetadata.cpp [hunk 3]
```diff
@@ -687,63 +698,145 @@ size_t ObjectStorageQueueMetadata::unregisterActive(const StorageID & storage_id
...
+                try
+                {
+                    zk_client->removeRecursive(zookeeper_path);
+                }
+                catch (const zkutil::KeeperMultiException & e)
+                {
+                    if (Coordination::isHardwareError(e.code))
+                    {
+                        LOG_TEST(log, "Lost connection to zookeeper, will retry");
+                        continue;
```
Comment (jkartseva) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueMetadata.cpp:815]: Is the idea that the `drop_lock_path` node is being removed in the `EphemeralNodeHolder()` destructor when `drop_lock` goes out of scope? I don't usually work with Zookeeper, so I'm asking.
If an exception occurs during `zk_client->removeRecursive(zookeeper_path);`, and the loop is retried, do we still want to remove the ephemeral node in the error path? There is `setAlreadyRemoved()` method that makes it no-op.

**Review by jkartseva — APPROVED** [review]
Looks good. I left a couple of questions.

**Comment by kssenii** [comment]
> [Stateless tests (release, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78541&sha=f5a876bd9319ab372673e18c87891441298795c0&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20ParallelReplicas%2C%20s3%20storage%29)
Stateless tests (release, ParallelReplicas, s3 storage) — fail: 1

03229_query_condition_cache_profile_events
