### PR TITLE
Make functions `least` and `greatest` ignore NULL arguments

### LINKED ISSUE #65039: LEAST/GREATEST return null if present
**Describe the unexpected behaviour**
Should return 1 for `SELECT LEAST(1, 2, null);` 

**How to reproduce**
`SELECT LEAST(1, 2, null);` 

* Which ClickHouse server version to use:
24.5

* Queries to run that lead to unexpected result
`SELECT LEAST(1, 2, null);` 
`SELECT greatest(1, 2, null)`

**Expected behavior**
Should return 1 or 2 like PostgreSQL/DuckBD

### PR DESCRIPTION
**Pull request by KevinyhZou**
Fixes #65039

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Functions `greatest` and `least` now ignore NULL input values, whereas they previously returned NULL if one of the arguments was NULL. For example, `SELECT greatest(1, 2, NULL)` now returns 2. This makes the behavior compatible with PostgreSQL.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 96ad1d749cb5bb2b65b0bba91691b29398e301e6 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65519/96ad1d749cb5bb2b65b0bba91691b29398e301e6/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Cloud fork sync (only for ClickHouse Inc. employees)</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Functions/FunctionBinaryArithmetic.h [hunk 1]
```diff
@@ -565,20 +590,49 @@ struct DecimalBinaryOperation
...
-                        scale_a);
+                if constexpr (is_compare)
+                {
+                    for (size_t i = 0; i < size; ++i)
+                        c[i] = applyScaled<true>(
+                            static_cast<NativeResultType>(unwrap<op_case, OpCase::LeftConstant>(a, i)),
+                            static_cast<NativeResultType>(unwrap<op_case, OpCase::RightConstant>(b, i)),
+                            scale_a,
+                            left_nullmap && ((*left_nullmap)[i]),
+                            right_nullmap && ((*right_nullmap)[i]));
```
Comment (superdiaodiao) [inline src/Functions/FunctionBinaryArithmetic.h:601]: Could we use a lambda func to process most of logic so that the below three part would be more clean?

Comment (KevinyhZou) [reply src/Functions/FunctionBinaryArithmetic.h]: done

File: tests/queries/0_stateless/03174_least_greatest_for_null.sql [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+drop table if exists test2;
+
+create table test1(id UInt32, x1 Nullable(Float64), x2 Nullable(Int32)) Engine=MergeTree order by id;
+create table test2(id UInt32, x1 Nullable(Decimal32(5)), x2 Nullable(Decimal64(5))) Engine=MergeTree order by id;
+
+insert into test1 values(1, 2, 3), (2, 3, NULL), (3, NULL, NULL);
+insert into test2 values(1, 2, 3), (2, 3, NULL), (3, NULL, NULL);
+
+select greatest(x1, x2), greatest(x1, x2, NULL), greatest(x1, x2, 4), greatest(x1, NULL, 4), greatest(x1, NULL, NULL), greatest(NULL, NULL, NULL) from test1;
+select least(x1, x2), least(x1, x2, NULL), least(x1, x2, 4), least(x1, NULL, 4), least(x1, NULL, NULL), least(NULL, NULL, NULL) from test1;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_for_null.sql:11]: Some extra whitespaces after the commas would be helpful to align the `greatest` and `least` functions in l. 10 and 11.

File: tests/queries/0_stateless/03174_least_greatest_for_null.sql [hunk 3]
```diff
@@ -0,0 +1,17 @@
+drop table if exists test1;
+drop table if exists test2;
+
+create table test1(id UInt32, x1 Nullable(Float64), x2 Nullable(Int32)) Engine=MergeTree order by id;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_for_null.sql:4]: Instead of generic names `test1` and `test2`, what about `tab` (as base case` and `tab_decimal`?

File: tests/queries/0_stateless/03174_least_greatest_for_null.sql [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+create table test2(id UInt32, x1 Nullable(Decimal32(5)), x2 Nullable(Decimal64(5))) Engine=MergeTree order by id;
+
+insert into test1 values(1, 2, 3), (2, 3, NULL), (3, NULL, NULL);
+insert into test2 values(1, 2, 3), (2, 3, NULL), (3, NULL, NULL);
+
+select greatest(x1, x2), greatest(x1, x2, NULL), greatest(x1, x2, 4), greatest(x1, NULL, 4), greatest(x1, NULL, NULL), greatest(NULL, NULL, NULL) from test1;
+select least(x1, x2), least(x1, x2, NULL), least(x1, x2, 4), least(x1, NULL, 4), least(x1, NULL, NULL), least(NULL, NULL, NULL) from test1;
+select greatest(x1, x2), greatest(x1, x2, NULL), greatest(x1, x2, 4), greatest(x1, NULL, 4), greatest(x1, NULL, NULL), greatest(NULL, NULL, NULL) from test2;
+select least(x1, x2), least(x1, x2, NULL), least(x1, x2, 4), least(x1, NULL, 4), least(x1, NULL, NULL), least(NULL, NULL, NULL) from test2;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_for_null.sql:13]: For readability, please put in newlines after l. 11 and l. 13.

File: tests/queries/0_stateless/03174_least_greatest_for_null.sql [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+select greatest(1,2,NULL), least(1,2,NULL);
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_for_null.sql:14]: Nit: \+ spaces after comma.

File: tests/queries/0_stateless/03174_least_greatest_for_null.sql [hunk 6]
```diff
@@ -0,0 +1,17 @@
+drop table if exists test1;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_for_null.sql:1]: Future readers will appreciate a one-line comment what the test is testing. (Asking because the test name could mean many things and the test doesn't have comments otherwise)

File: src/Functions/FunctionBinaryArithmetic.h [hunk 7]
```diff
@@ -527,8 +566,8 @@ struct StringReduceOperationImpl
     }
 };
 
-template <typename A, typename B, typename Op, typename ResultType = typename Op::ResultType>
-struct BinaryOperationImpl : BinaryOperation<A, B, Op, ResultType> { };
+template <typename A, typename B, typename Op, typename ResultType = typename Op::ResultType, bool is_compare=false>
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:569]: Nit: \+ spaces around `=`. (same in other places)

File: src/Functions/FunctionBinaryArithmetic.h [hunk 8]
```diff
@@ -246,34 +246,46 @@ enum class OpCase : uint8_t
 constexpr const auto & undec(const auto & x) { return x; }
 constexpr const auto & undec(const is_decimal auto & x) { return x.value; }
 
-template <typename A, typename B, typename Op, typename OpResultType = typename Op::ResultType>
+template <typename A, typename B, typename Op, typename OpResultType = typename Op::ResultType, bool is_compare=false>
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:249]: Do we need to encode the special case handling into the generic template interface? Such special case handling tends to accumulate over time and at some point the code becomes unmaintainable.

In places where we need to distinguish based on the operator type, we should instead check in-place, similar to this

```cpp
static constexpr bool is_compare = IsOperation<Op>::greatest || IsOperation<Op>::least;
```

(basically what you added elsewhere)

File: src/Functions/FunctionBinaryArithmetic.h [hunk 9]
```diff
@@ -246,34 +246,46 @@ enum class OpCase : uint8_t
...
     using ResultType = OpResultType;
     static const constexpr bool allow_fixed_string = false;
     static const constexpr bool allow_string_integer = false;
 
     template <OpCase op_case>
-    static void NO_INLINE process(const A * __restrict a, const B * __restrict b, ResultType * __restrict c, size_t size, const NullMap * right_nullmap = nullptr)
+    static void NO_INLINE process(const A * __restrict a, const B * __restrict b, ResultType * __restrict c, size_t size, const NullMap * left_nullmap = nullptr, const NullMap * right_nullmap = nullptr, NullMap * result_nullmap = nullptr)
     {
-        if constexpr (op_case == OpCase::RightConstant)
+        if constexpr (!is_compare)
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:259]: Please add a comment that states why we need special handling for `least` and `greatest`, otherwise future readers will have no idea.

File: src/Functions/FunctionBinaryArithmetic.h [hunk 10]
```diff
@@ -2278,7 +2376,27 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
                 }
             };
 
-            return executeImpl2(new_arguments, result_type, input_rows_count, right_nullmap);
+            return executeImpl2(new_arguments, result_type, input_rows_count, nullptr, right_nullmap);
+        }
+
+        if (is_compare && (left_argument.type->isNullable() || right_argument.type->isNullable()))
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:2382]: Needs a comment why `least` and `greatest` deserve special handling.

**Comment by KevinyhZou** [comment]
I have simplified the code of `FunctionBinaryArithmetic.h`, could you help to review at this ?

File: src/Functions/FunctionBinaryArithmetic.h [hunk 11]
```diff
@@ -2220,6 +2290,11 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
             return executeTupleNumberOperator(arguments, result_type, input_rows_count, function_builder);
         }
 
+        /// Special case when the function is least or greatest
+        if constexpr (is_compare)
+        {
+            return executeComparsion(arguments, result_type, input_rows_count);
+        }
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:2297]: Nit: Please keep the newline before l. 2298.

File: src/Functions/FunctionBinaryArithmetic.h [hunk 12]
```diff
@@ -2220,6 +2290,11 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
             return executeTupleNumberOperator(arguments, result_type, input_rows_count, function_builder);
         }
 
+        /// Special case when the function is least or greatest
+        if constexpr (is_compare)
+        {
+            return executeComparsion(arguments, result_type, input_rows_count);
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:2296]: `Comparsion` --> `Comparison`

File: src/Functions/FunctionBinaryArithmetic.h [hunk 13]
```diff
@@ -1328,6 +1330,65 @@ class FunctionBinaryArithmetic : public IFunction
         return function->execute(new_arguments, result_type, input_rows_count);
     }
 
+    ColumnPtr executeComparsion(const ColumnsWithTypeAndName & arguments, const DataTypePtr & result_type, size_t input_rows_count) const
+    {
+        bool args_have_nulls = false;
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:1335]: The code in l. 1335 - 1390 is probably copypasta from elsewhere in this file. Kindly add a comment that explains the reader _why_ a special case was implemented.

File: tests/queries/0_stateless/03174_least_greatest_input_has_nulls.sql [hunk 14]
```diff
@@ -0,0 +1,19 @@
...
+
+select greatest(x1, x2), greatest(x1, x2, NULL), greatest(x1, x2, 4), greatest(x1, NULL, 4), greatest(x1, NULL, NULL), greatest(NULL, NULL, NULL) from tab_base_case;
+select least(x1, x2),    least(x1, x2, NULL),    least(x1, x2, 4),    least(x1, NULL, 4),    least(x1, NULL, NULL),    least(NULL, NULL, NULL)    from tab_base_case;
+
+select greatest(x1, x2), greatest(x1, x2, NULL), greatest(x1, x2, 4), greatest(x1, NULL, 4), greatest(x1, NULL, NULL), greatest(NULL, NULL, NULL) from tab_decimal;
+select least(x1, x2),    least(x1, x2, NULL),    least(x1, x2, 4),    least(x1, NULL, 4),    least(x1, NULL, NULL),    least(NULL, NULL, NULL)    from tab_decimal;
+select greatest(1, 2, NULL),  least(1, 2, NULL);
+
+drop table tab_base_case;
+drop table tab_decimal;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_input_has_nulls.sql:19]: Kindly update the documentation for the new behavior:

docs/en/sql-reference/functions/other-functions.md

**Comment by KevinyhZou** [comment]
done

**Comment by KevinyhZou** [comment]
could you help to review this ? @rschu1ze

**Comment by rschu1ze** [comment]
Everyone is fixing CI tests, expect delay, sorry.
(I'll also be on a trip next week and then on vacation, so expect some delay on top of the delay, sorry)

**Comment by rschu1ze** [comment]
This is still on my list of PRs-to-review.

**Comment by KevinyhZou** [comment]
could you help to review this ? @rschu1ze

File: src/Functions/LeastGreatestGeneric.h [hunk 15]
```diff
@@ -114,6 +125,24 @@ class LeastGreatestOverloadResolver : public IFunctionOverloadResolver
         if (arguments.size() == 2 && isNumber(removeNullable(arguments[0].type)) && isNumber(removeNullable(arguments[1].type)))
             return std::make_unique<FunctionToFunctionBaseAdaptor>(SpecializedFunction::create(context), argument_types, return_type);
 
+        /// In sql query like `least(x, NULL)` or `greatest(x, NULL)`, which has constant NULL arguments, will make the return type is only null.
+        /// In such case, we should reconstruct the return type based on the not only null input arguments.
```
Comment (rschu1ze) [inline src/Functions/LeastGreatestGeneric.h:129]: I am surprised that nothing needs to be changed in function `getReturnTypeImpl` (l. 152ff).

File: src/Functions/LeastGreatestGeneric.h [hunk 16]
```diff
@@ -114,6 +125,24 @@ class LeastGreatestOverloadResolver : public IFunctionOverloadResolver
         if (arguments.size() == 2 && isNumber(removeNullable(arguments[0].type)) && isNumber(removeNullable(arguments[1].type)))
             return std::make_unique<FunctionToFunctionBaseAdaptor>(SpecializedFunction::create(context), argument_types, return_type);
 
+        /// In sql query like `least(x, NULL)` or `greatest(x, NULL)`, which has constant NULL arguments, will make the return type is only null.
```
Comment (rschu1ze) [inline src/Functions/LeastGreatestGeneric.h:128]: Please replace the comment in l. 128/129 by this:

```
/// If one of the arguments is NULL (const or non-const), result_type will be `Nullable(Nothing)`.
/// It is incorrect to return this, instead infer the result_type from the non-NULL arguments.
```

File: src/Functions/LeastGreatestGeneric.h [hunk 17]
```diff
@@ -114,6 +125,24 @@ class LeastGreatestOverloadResolver : public IFunctionOverloadResolver
...
+            DataTypes not_only_null_types;
+            for (const auto & argument_type : argument_types)
+            {
+                if (!argument_type->onlyNull())
+                    not_only_null_types.push_back(argument_type);
+            }
+            if (!not_only_null_types.empty())
+            {
+                const DataTypePtr & result_type = removeLowCardinality(getLeastSupertype(not_only_null_types));
+                return std::make_unique<FunctionToFunctionBaseAdaptor>(
```
Comment (rschu1ze) [inline src/Functions/LeastGreatestGeneric.h:141]: This copy-pastes l. 146. Can we instead please add 'DateTypePtr return_type_copy = return_type;' after l. 120 and only modify 'return_type_copy' in l. 140, delete l. 141, and change l. 146 from 'return_type' to 'return_type_copy'?

File: src/Functions/LeastGreatestGeneric.h [hunk 18]
```diff
@@ -53,27 +53,39 @@ class FunctionLeastGreatestGeneric : public IFunction
         if (1 == num_arguments)
             return arguments[0].column;
 
-        Columns converted_columns(num_arguments);
+        Columns converted_columns;
+        /// Remove the only null column, not need to compare
```
Comment (rschu1ze) [inline src/Functions/LeastGreatestGeneric.h:57]: Please replace l. 57-65 by

```cpp
        for (size_t arg = 0; arg < num_arguments; ++arg)
        {
            if (arguments[arg].type->onlyNull())
                continue;
            auto converted_col = castColumn(arguments[arg], result_type)->convertToFullColumnIfConst();
            converted_columns.emplace_back(converted_col);
        }
```

File: src/Functions/LeastGreatestGeneric.h [hunk 19]
```diff
@@ -53,27 +53,39 @@ class FunctionLeastGreatestGeneric : public IFunction
...
         auto result_column = result_type->createColumn();
         result_column->reserve(input_rows_count);
 
         for (size_t row_num = 0; row_num < input_rows_count; ++row_num)
         {
             size_t best_arg = 0;
-            for (size_t arg = 1; arg < num_arguments; ++arg)
+            for (size_t arg = 1; arg < converted_columns.size(); ++arg)
             {
-                auto cmp_result = converted_columns[arg]->compareAt(row_num, row_num, *converted_columns[best_arg], 1);
```
Comment (rschu1ze) [inline src/Functions/LeastGreatestGeneric.h:68]: Since you duplicated l. 68 into calls with last argument = `1` and `-1` ... are you saying that the code was _incorrect_  before?

File: src/Functions/FunctionBinaryArithmetic.h [hunk 20]
```diff
@@ -43,6 +43,7 @@
 #include <Functions/IFunction.h>
 #include <Functions/IsOperation.h>
 #include <Functions/castTypeToEither.h>
+#include <Functions/LeastGreatestGeneric.h>
```
Comment (rschu1ze) [inline src/Functions/FunctionBinaryArithmetic.h:46]: Lots of stuff was changed in FunctionBinaryArithmetic. I did not review it. As far as I understand, the only way how we may run into FunctionBinaryArithmetic is via

```cpp
/// More efficient specialization for two numeric arguments.
        if (arguments.size() == 2 && isNumber(removeNullable(arguments[0].type)) && isNumber(removeNullable(arguments[1].type)))
            return std::make_unique<FunctionToFunctionBaseAdaptor>(SpecializedFunction::create(context), argument_types, return_type);
```

in LeastGreatestGeneric.h. Is that correct? (otherwise, we would execute the generic implementation in LeastGreatestGeneric.h, as far as I see).

I actually think we should revert all changes in FunctinoBinaryArithmetic.h. The file is already too big, too complex, compiles too long, and we should avoid adding more complexity. In other words, if one of the arguments is NULL, always run the generic code. Yes, one very special case will not have a specialized implementation but I doubt that anyone will notice or complain about.

File: src/Functions/LeastGreatestGeneric.h (hunk 19 above)
Comment (KevinyhZou) [reply src/Functions/LeastGreatestGeneric.h:68]: Yes, it is incorrect to always set the `nan_direction_hint` to be 1 at the `compareAt` function when encounter the null input, as we can see at the functions comments
```
 * If one of element's value is NaN or NULLs, then:
    * - if nan_direction_hint == -1, NaN and NULLs are considered as least than everything other;
    * - if nan_direction_hint ==  1, NaN and NULLs are considered as greatest than everything other.
```
So it we always set the value as 1, the NULL input  would be consider as greatest value, and will lead to wrong result of `greatest` function.

File: src/Functions/FunctionBinaryArithmetic.h (hunk 20 above)
Comment (KevinyhZou) [reply src/Functions/FunctionBinaryArithmetic.h:47]: Yes, I have removed the changs from `FunctionBinaryArithmetic.h` and remove the changes of pr : https://github.com/ClickHouse/ClickHouse/pull/64668, which lead to the nullable input need to be handled in `FunctionBinaryArithmetic`

File: src/Functions/LeastGreatestGeneric.h (hunk 15 above)
Comment (KevinyhZou) [reply src/Functions/LeastGreatestGeneric.h]: It seems this can be simply resolved by set `useDefaultImplementationForNulls` as `false` to `LeastGreatestOverloadResolver`. And the codes of l.128 ~ l.141 is not needed now.

File: tests/queries/0_stateless/03174_least_greatest_ignore_null_input_values.reference [hunk 21]
```diff
@@ -0,0 +1,21 @@
+Test with one const argument
+\N	\N
+Test with two const arguments
+1	1
+1	1
+1.0	1.0
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03174_least_greatest_ignore_null_input_values.reference:6]: @KevinyhZou I changed the float 1.0 to 1.1 in the .sql test and in this .reference file. Since I don't have permission to push directly to your repository (I am getting a "Permission denied error - 403") I could not do the change using a proper text editor on the command line. Instead, I made change in GitHub's web UI. And that messed up tabs and whitespaces in the expected result file, sorry! (CI will complain)

Would you please run the test locally, re-generate the expected results and push once more? Thanks.

**Comment by rschu1ze** [comment]
After your fixes, the PR is in _much_ better shape, thanks.

Final question: Was tests/performance/least_greatest.xml deleted by accident or intentionally?

**Comment by KevinyhZou** [comment]
`tests/performance/least_greatest.xml` was introduced by pr: https://github.com/ClickHouse/ClickHouse/pull/64668, and now this pr's changes are removed, so we delete this file.
