### PR TITLE
Fix race in cached buffer

### LINKED ISSUE #35901: Data race in `CachedReadBufferFromRemoteFS`
https://s3.amazonaws.com/clickhouse-test-reports/0/d9e5ca21195a2689725488ff2519ff2233f1bbd3/stateful_tests__thread__actions_.html

```
==================
WARNING: ThreadSanitizer: data race (pid=648)
  Write of size 8 at 0x7b600134b0a0 by thread T600:
    #0 DB::ReadBufferFromS3::nextImpl() build_docker/../src/IO/ReadBufferFromS3.cpp:152:12 (clickhouse+0x195056cc)
    #1 DB::ReadBuffer::next() build_docker/../src/IO/ReadBuffer.h:85:20 (clickhouse+0x194f9104)
    #2 DB::ReadBuffer::eof() build_docker/../src/IO/ReadBuffer.h:119:38 (clickhouse+0x194f9104)
    #3 DB::CachedReadBufferFromRemoteFS::predownload(std::__1::shared_ptr<DB::FileSegment>&) build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:397:65 (clickhouse+0x194f9104)
    #4 DB::CachedReadBufferFromRemoteFS::nextImplStep() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:627:9 (clickhouse+0x194faa4b)
    #5 DB::CachedReadBufferFromRemoteFS::nextImpl() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:547:16 (clickhouse+0x194fa2fd)
    #6 DB::ReadBuffer::next() build_docker/../src/IO/ReadBuffer.h:85:20 (clickhouse+0x194f3d90)
    #7 DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:203:31 (clickhouse+0x194f3d90)
    #8 DB::ReadBufferFromRemoteFSGather::nextImpl() build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:155:13 (clickhouse+0x194f3916)
    #9 DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:109:19 (clickhouse+0x194f35d6)
    #10 DB::ThreadPoolRemoteFSReader::RemoteFSFileDescriptor::readInto(char*, unsigned long, unsigned long, unsigned long) build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:33:20 (clickhouse+0x194f1d2b)
    #11 DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0::operator()() const build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:75:36 (clickhouse+0x194f1d2b)
    #12 decltype(static_cast<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&>(fp)()) std::__1::__invoke<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f1d2b)
    #13 std::__1::__packaged_task_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0, std::__1::allocator<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0>, DB::IAsynchronousReader::Result ()>::operator()() build_docker/../contrib/libcxx/include/future:1688:12 (clickhouse+0x194f1d2b)
    #14 std::__1::__packaged_task_function<DB::IAsynchronousReader::Result ()>::operator()() const build_docker/../contrib/libcxx/include/future:1870:12 (clickhouse+0x18d8f88e)
    #15 std::__1::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() build_docker/../contrib/libcxx/include/future:1961:24 (clickhouse+0x18d8f88e)
    #16 DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1::operator()() const build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:98:34 (clickhouse+0x194f1e8c)
    #17 decltype(static_cast<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(fp)()) std::__1::__invoke<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f1e8c)
    #18 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x194f1e8c)
    #19 std::__1::__function::__default_alloc_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1, void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x194f1e8c)
    #20 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1, void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x194f1e8c)
    #21 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb291597)
    #22 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb291597)
    #23 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb291597)
    #24 void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb293df8)
    #25 decltype(static_cast<void>(fp)()) std::__1::__invoke_constexpr<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0xb293df8)
    #26 decltype(auto) std::__1::__apply_tuple_impl<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0xb293df8)
    #27 decltype(auto) std::__1::apply<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0xb293df8)
    #28 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0xb293df8)
    #29 decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb293ca1)
    #30 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0xb293ca1)
    #31 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0xb293ca1)
    #32 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0xb293ca1)
    #33 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb28ebcd)
    #34 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb28ebcd)
ThreadSanitizer: memory flush check RSS=23015 LAST=22989 LIMIT=46080
ThreadSanitizer: memory flush check RSS=23015 LAST=22989 LIMIT=46080
    #35 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb28ebcd)
    #36 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb292410)
    #37 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb292410)
    #38 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xb292410)
    #39 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xb292410)

  Previous read of size 8 at 0x7b600134b0a0 by thread T375:
    #0 DB::ReadBufferFromS3::getRemainingReadRange() const build_docker/../src/IO/ReadBufferFromS3.cpp:243:46 (clickhouse+0x19506ac4)
    #1 DB::CachedReadBufferFromRemoteFS::getInfoForLog() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:807:47 (clickhouse+0x194fce29)
    #2 DB::CachedReadBufferFromRemoteFS::nextImplStep()::$_0::operator()() const build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:569:5 (clickhouse+0x194fc7cd)
    #3 basic_scope_guard<DB::CachedReadBufferFromRemoteFS::nextImplStep()::$_0>::invoke() build_docker/../base/base/../base/scope_guard.h:94:9 (clickhouse+0x194fc7cd)
    #4 basic_scope_guard<DB::CachedReadBufferFromRemoteFS::nextImplStep()::$_0>::~basic_scope_guard() build_docker/../base/base/../base/scope_guard.h:44:28 (clickhouse+0x194fc7cd)
    #5 DB::CachedReadBufferFromRemoteFS::nextImplStep() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:744:1 (clickhouse+0x194fbf01)
    #6 DB::CachedReadBufferFromRemoteFS::nextImpl() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:547:16 (clickhouse+0x194fa2fd)
    #7 DB::ReadBuffer::next() build_docker/../src/IO/ReadBuffer.h:85:20 (clickhouse+0x194f3d90)
    #8 DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:203:31 (clickhouse+0x194f3d90)
    #9 DB::ReadBufferFromRemoteFSGather::nextImpl() build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:155:13 (clickhouse+0x194f3916)
    #10 DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:109:19 (clickhouse+0x194f35d6)
ThreadSanitizer: memory flush check RSS=111 LAST=111 LIMIT=46080
    #11 DB::ThreadPoolRemoteFSReader::RemoteFSFileDescriptor::readInto(char*, unsigned long, unsigned long, unsigned long) build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:33:20 (clickhouse+0x194f1d2b)
    #12 DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0::operator()() const build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:75:36 (clickhouse+0x194f1d2b)
    #13 decltype(static_cast<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&>(fp)()) std::__1::__invoke<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f1d2b)
    #14 std::__1::__packaged_task_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0, std::__1::allocator<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0>, DB::IAsynchronousReader::Result ()>::operator()() build_docker/../contrib/libcxx/include/future:1688:12 (clickhouse+0x194f1d2b)
    #15 std::__1::__packaged_task_function<DB::IAsynchronousReader::Result ()>::operator()() const build_docker/../contrib/libcxx/include/future:1870:12 (clickhouse+0x18d8f88e)
    #16 std::__1::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() build_docker/../contrib/libcxx/include/future:1961:24 (clickhouse+0x18d8f88e)
    #17 DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1::operator()() const build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:98:34 (clickhouse+0x194f1e8c)
    #18 decltype(static_cast<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(fp)()) std::__1::__invoke<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f1e8c)
    #19 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x194f1e8c)
    #20 std::__1::__function::__default_alloc_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1, void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x194f1e8c)
    #21 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1, void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x194f1e8c)
    #22 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb291597)
    #23 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb291597)
    #24 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb291597)
    #25 void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb293df8)
    #26 decltype(static_cast<void>(fp)()) std::__1::__invoke_constexpr<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0xb293df8)
    #27 decltype(auto) std::__1::__apply_tuple_impl<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0xb293df8)
    #28 decltype(auto) std::__1::apply<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0xb293df8)
    #29 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0xb293df8)
    #30 decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb293ca1)
    #31 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0xb293ca1)
    #32 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0xb293ca1)
    #33 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0xb293ca1)
    #34 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb28ebcd)
    #35 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb28ebcd)
    #36 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb28ebcd)
    #37 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb292410)
    #38 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb292410)
    #39 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xb292410)
    #40 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xb292410)

  Location is heap block of size 912 at 0x7b600134b000 allocated by thread T375:
    #0 operator new(unsigned long) <null> (clickhouse+0xb1bb518)
    #1 std::__1::__unique_if<DB::ReadBufferFromS3>::__unique_single std::__1::make_unique<DB::ReadBufferFromS3, std::__1::shared_ptr<Aws::S3::S3Client>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::__fs::filesystem::path, unsigned long&, DB::ReadSettings&, bool, int, unsigned long&, bool>(std::__1::shared_ptr<Aws::S3::S3Client>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::__fs::filesystem::path&&, unsigned long&, DB::ReadSettings&, bool&&, int&&, unsigned long&, bool&&) build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:725:28 (clickhouse+0x194f5296)
    #2 DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0::operator()() const build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:45:16 (clickhouse+0x194f27a8)
    #3 decltype(static_cast<DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0&>(fp)()) std::__1::__invoke<DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0&>(DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f46c2)
    #4 std::__1::shared_ptr<DB::SeekableReadBuffer> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::SeekableReadBuffer>, false>::__call<DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0&>(DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/__functional/invoke.h:30:16 (clickhouse+0x194f46c2)
    #5 std::__1::__function::__default_alloc_func<DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0, std::__1::shared_ptr<DB::SeekableReadBuffer> ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x194f46c2)
    #6 std::__1::shared_ptr<DB::SeekableReadBuffer> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::SeekableReadBuffer> ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ReadBufferFromS3Gather::createImplementationBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)::$_0, std::__1::shared_ptr<DB::SeekableReadBuffer> ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x194f46c2)
    #7 std::__1::__function::__policy_func<std::__1::shared_ptr<DB::SeekableReadBuffer> ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0x194f66d7)
    #8 std::__1::function<std::__1::shared_ptr<DB::SeekableReadBuffer> ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0x194f66d7)
    #9 DB::CachedReadBufferFromRemoteFS::getRemoteFSReadBuffer(std::__1::shared_ptr<DB::FileSegment>&, DB::CachedReadBufferFromRemoteFS::ReadType) build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:100:40 (clickhouse+0x194f66d7)
    #10 DB::CachedReadBufferFromRemoteFS::getReadBufferForFileSegment(std::__1::shared_ptr<DB::FileSegment>&) build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:146:32 (clickhouse+0x194f6c95)
    #11 DB::CachedReadBufferFromRemoteFS::getImplementationBuffer(std::__1::shared_ptr<DB::FileSegment>&) build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:284:41 (clickhouse+0x194f7667)
    #12 DB::CachedReadBufferFromRemoteFS::nextImplStep() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:606:33 (clickhouse+0x194fa4c4)
    #13 DB::CachedReadBufferFromRemoteFS::nextImpl() build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.cpp:547:16 (clickhouse+0x194fa2fd)
    #14 DB::ReadBuffer::next() build_docker/../src/IO/ReadBuffer.h:85:20 (clickhouse+0x194f3d90)
    #15 DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:203:31 (clickhouse+0x194f3d90)
    #16 DB::ReadBufferFromRemoteFSGather::nextImpl() build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:155:13 (clickhouse+0x194f3916)
    #17 DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:109:19 (clickhouse+0x194f35d6)
    #18 DB::ThreadPoolRemoteFSReader::RemoteFSFileDescriptor::readInto(char*, unsigned long, unsigned long, unsigned long) build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:33:20 (clickhouse+0x194f1d2b)
    #19 DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0::operator()() const build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:75:36 (clickhouse+0x194f1d2b)
    #20 decltype(static_cast<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&>(fp)()) std::__1::__invoke<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f1d2b)
    #21 std::__1::__packaged_task_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0, std::__1::allocator<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0>, DB::IAsynchronousReader::Result ()>::operator()() build_docker/../contrib/libcxx/include/future:1688:12 (clickhouse+0x194f1d2b)
    #22 std::__1::__packaged_task_function<DB::IAsynchronousReader::Result ()>::operator()() const build_docker/../contrib/libcxx/include/future:1870:12 (clickhouse+0x18d8f88e)
    #23 std::__1::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() build_docker/../contrib/libcxx/include/future:1961:24 (clickhouse+0x18d8f88e)
    #24 DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1::operator()() const build_docker/../src/Disks/IO/ThreadPoolRemoteFSReader.cpp:98:34 (clickhouse+0x194f1e8c)
    #25 decltype(static_cast<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(fp)()) std::__1::__invoke<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x194f1e8c)
    #26 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&>(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x194f1e8c)
    #27 std::__1::__function::__default_alloc_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1, void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x194f1e8c)
    #28 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_1, void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x194f1e8c)
    #29 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb291597)
    #30 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb291597)
    #31 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb291597)
    #32 void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb293df8)
    #33 decltype(static_cast<void>(fp)()) std::__1::__invoke_constexpr<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0xb293df8)
    #34 decltype(auto) std::__1::__apply_tuple_impl<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0xb293df8)
    #35 decltype(auto) std::__1::apply<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0xb293df8)
    #36 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0xb293df8)
    #37 decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb293ca1)
    #38 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0xb293ca1)
    #39 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0xb293ca1)
    #40 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0xb293ca1)
    #41 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb28ebcd)
    #42 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb28ebcd)
    #43 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb28ebcd)
    #44 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb292410)
    #45 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb292410)
    #46 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xb292410)
    #47 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xb292410)

  Thread T600 'VFSRead' (tid=2189, running) created by thread T315 at:
    #0 pthread_create <null> (clickhouse+0xb1467dd)
    #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10 (clickhouse+0xb291ec0)
    #2 std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16 (clickhouse+0xb291ec0)
    #3 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) build_docker/../src/Common/ThreadPool.cpp:142:35 (clickhouse+0xb28d1f4)
    #4 ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) build_docker/../src/Common/ThreadPool.cpp:174:5 (clickhouse+0xb28db27)
    #5 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../src/Common/ThreadPool.h:169:38 (clickhouse+0x1afbeac7)
    #6 ThreadFromGlobalPool* std::__1::construct_at<ThreadFromGlobalPool, DB::PipelineExecutor::executeImpl(unsigned long)::$_1, ThreadFromGlobalPool*>(ThreadFromGlobalPool*, DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/__memory/construct_at.h:38:50 (clickhouse+0x1afbeac7)
    #7 void std::__1::allocator_traits<std::__1::allocator<ThreadFromGlobalPool> >::construct<ThreadFromGlobalPool, DB::PipelineExecutor::executeImpl(unsigned long)::$_1, void, void>(std::__1::allocator<ThreadFromGlobalPool>&, ThreadFromGlobalPool*, DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:298:9 (clickhouse+0x1afbeac7)
    #8 void std::__1::vector<ThreadFromGlobalPool, std::__1::allocator<ThreadFromGlobalPool> >::__construct_one_at_end<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/vector:778:5 (clickhouse+0x1afbcc84)
    #9 ThreadFromGlobalPool& std::__1::vector<ThreadFromGlobalPool, std::__1::allocator<ThreadFromGlobalPool> >::emplace_back<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/vector:1577:9 (clickhouse+0x1afbcc84)
    #10 DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:295:21 (clickhouse+0x1afbcc84)
    #11 DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:84:9 (clickhouse+0x1afbc978)
    #12 DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:78:24 (clickhouse+0x1afcfcc3)
    #13 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105:13 (clickhouse+0x1afcfcc3)
    #14 decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0x1afcfcc3)
    #15 decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0x1afcfcc3)
    #16 decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0x1afcfcc3)
    #17 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0x1afcfcc3)
    #18 decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x1afcfcc3)
    #19 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x1afcfcc3)
    #20 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x1afcfcc3)
    #21 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x1afcfcc3)
    #22 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb28ebcd)
    #23 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb28ebcd)
    #24 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb28ebcd)
    #25 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb292410)
    #26 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb292410)
    #27 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xb292410)
    #28 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xb292410)

  Thread T375 'VFSRead' (tid=1079, running) created by thread T347 at:
    #0 pthread_create <null> (clickhouse+0xb1467dd)
    #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10 (clickhouse+0xb291ec0)
    #2 std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16 (clickhouse+0xb291ec0)
    #3 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) build_docker/../src/Common/ThreadPool.cpp:142:35 (clickhouse+0xb28d1f4)
    #4 ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) build_docker/../src/Common/ThreadPool.cpp:174:5 (clickhouse+0xb28db27)
    #5 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../src/Common/ThreadPool.h:169:38 (clickhouse+0x1afbeac7)
    #6 ThreadFromGlobalPool* std::__1::construct_at<ThreadFromGlobalPool, DB::PipelineExecutor::executeImpl(unsigned long)::$_1, ThreadFromGlobalPool*>(ThreadFromGlobalPool*, DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/__memory/construct_at.h:38:50 (clickhouse+0x1afbeac7)
    #7 void std::__1::allocator_traits<std::__1::allocator<ThreadFromGlobalPool> >::construct<ThreadFromGlobalPool, DB::PipelineExecutor::executeImpl(unsigned long)::$_1, void, void>(std::__1::allocator<ThreadFromGlobalPool>&, ThreadFromGlobalPool*, DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:298:9 (clickhouse+0x1afbeac7)
    #8 void std::__1::vector<ThreadFromGlobalPool, std::__1::allocator<ThreadFromGlobalPool> >::__construct_one_at_end<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/vector:778:5 (clickhouse+0x1afbcc84)
    #9 ThreadFromGlobalPool& std::__1::vector<ThreadFromGlobalPool, std::__1::allocator<ThreadFromGlobalPool> >::emplace_back<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) build_docker/../contrib/libcxx/include/vector:1577:9 (clickhouse+0x1afbcc84)
    #10 DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:295:21 (clickhouse+0x1afbcc84)
    #11 DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:84:9 (clickhouse+0x1afbc978)
    #12 DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:78:24 (clickhouse+0x1afcfcc3)
    #13 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105:13 (clickhouse+0x1afcfcc3)
    #14 decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0x1afcfcc3)
    #15 decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0x1afcfcc3)
    #16 decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0x1afcfcc3)
    #17 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0x1afcfcc3)
    #18 decltype(static_cast<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x1afcfcc3)
    #19 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x1afcfcc3)
    #20 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x1afcfcc3)
    #21 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x1afcfcc3)
    #22 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xb28ebcd)
    #23 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xb28ebcd)
    #24 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:277:17 (clickhouse+0xb28ebcd)
    #25 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:142:73 (clickhouse+0xb292410)
    #26 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xb292410)
ThreadSanitizer: memory flush check RSS=23101 LAST=23015 LIMIT=46080
ThreadSanitizer: memory flush check RSS=23101 LAST=23015 LIMIT=46080
    #27 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xb292410)
    #28 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xb292410)

SUMMARY: ThreadSanitizer: data race build_docker/../src/IO/ReadBufferFromS3.cpp:152:12 in DB::ReadBufferFromS3::nextImpl()
==================
```

cc: @kssenii

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/35901.

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]
A bit weird to have the ReadBuffer partially thread-safe, but it's just for logging so it's okay.

**Comment by kssenii** [comment]
Yes, though it is even less than logging -- this method is only used to add some additional info into exception message, very useful for debug.

File: src/IO/ReadBufferFromS3.h [hunk 1]
```diff
@@ -33,8 +33,11 @@ class ReadBufferFromS3 : public SeekableReadBufferWithSize
     String key;
     UInt64 max_single_read_retries;
 
-    off_t offset = 0;
-    off_t read_until_position = 0;
+    /// These variables are atomic because they can be used for `logging only`
+    /// (where it is not important to get consistent result)
+    /// from separate thread other than the one which uses the buffer for s3 reading.
+    std::atomic<off_t> offset = 0;
```
Comment (azat) [inline src/IO/ReadBufferFromS3.h:39]: But why it cannot race with other fieds? In other words why the race can happens only with logging?

Comment (kssenii) [reply src/IO/ReadBufferFromS3.h:39]: > But why it cannot race with other fieds?

But why it should, if other fields are not accessed concurrently?
This is the only place, where buffer field is accessed concurrently, which I know is not good, but it is used only for adding info to exception message and it saved me a lot with debugging some errors, so I would rather not remove it.

Comment (azat) [reply src/IO/ReadBufferFromS3.h:39]: I'm looking at `nextImplStep`, and trying to understand why for the same `implementation_buffer` only `getRemainingReadRange()` can be called concurrently.

AFAICS one thread was downloading, while another, concurrently, was waiting for the download to be finished, and it should not call anything on this `implementation_buffer`, no?
I guess some exception can lead to this? Or what did I miss?

Comment (kssenii) [reply src/IO/ReadBufferFromS3.h:39]: The concurrency can be in the following case:

file is still being downloaded by someone, but we do not necessarily wait for the full download if we know that some part of it, which we need, is already downloaded:
https://github.com/ClickHouse/ClickHouse/blob/e3d8da26b77da09feabbda332fe7e6ad56fa203e/src/Disks/IO/CachedReadBufferFromRemoteFS.cpp#L198-L210

Then `getRemainingReadRange()` is only used in case of an exception from `nextImpl` and it's result is added to exception message. So here is a race on remaining read range, because someone can still be downloading. This race is ok because it is just for debug and better understanding of the current exception.

Comment (azat) [reply src/IO/ReadBufferFromS3.h:39]: Ok, thanks.

So, AFAIU it is only possible if `getImplementationBuffer` will fail, and so `implementation_buffer` will not be updated?

Comment (kssenii) [reply src/IO/ReadBufferFromS3.h:39]: > is only possible if getImplementationBuffer will fail

no, it can succeed, `implementation_buffer` will be updated. Then if any exception happens within `nextImplStep` it will be caught in `nextImpl` and a cache info message is appended to exception message.

Comment (azat) [reply src/IO/ReadBufferFromS3.h:39]: But if it will update `implementation_buffer`, then it will be an instance of `ReadBufferFromFile`, not `ReadBufferFromS3` there the race is.

Comment (kssenii) [reply src/IO/ReadBufferFromS3.h:39]: Actually not, because the case I described is not applied to `ReadBufferFromFile` as it is not shared between file segments like `ReadBufferFromS3`.
