### PR TITLE
Fix `0 rows in set` on `INSERT ... SELECT`

### LINKED ISSUE #47800: Parallel distributed INSERT SELECT prints `0 rows in set`
**Describe the issue**

```
SET parallel_distributed_insert_select = 1;
SET max_threads = 32, max_insert_threads = 32;

INSERT INTO github_events_smt SELECT *
FROM s3Cluster('default', 'https://clickhouse-public-datasets.s3.amazonaws.com/github_events/partitioned_json/*.gz', 'JSONEachRow', ' `file_time` DateTime,\n    `event_type` Enum8(\'CommitCommentEvent\' = 1, \'CreateEvent\' = 2, \'DeleteEvent\' = 3, \'ForkEvent\' = 4, \'GollumEvent\' = 5, \'IssueCommentEvent\' = 6, \'IssuesEvent\' = 7, \'MemberEvent\' = 8, \'PublicEvent\' = 9, \'PullRequestEvent\' = 10, \'PullRequestReviewCommentEvent\' = 11, \'PushEvent\' = 12, \'ReleaseEvent\' = 13, \'SponsorshipEvent\' = 14, \'WatchEvent\' = 15, \'GistEvent\' = 16, \'FollowEvent\' = 17, \'DownloadEvent\' = 18, \'PullRequestReviewEvent\' = 19, \'ForkApplyEvent\' = 20, \'Event\' = 21, \'TeamAddEvent\' = 22),\n    `actor_login` LowCardinality(String),\n    `repo_name` LowCardinality(String),\n    `created_at` DateTime,\n    `updated_at` DateTime,\n    `action` Enum8(\'none\' = 0, \'created\' = 1, \'added\' = 2, \'edited\' = 3, \'deleted\' = 4, \'opened\' = 5, \'closed\' = 6, \'reopened\' = 7, \'assigned\' = 8, \'unassigned\' = 9, \'labeled\' = 10, \'unlabeled\' = 11, \'review_requested\' = 12, \'review_request_removed\' = 13, \'synchronize\' = 14, \'started\' = 15, \'published\' = 16, \'update\' = 17, \'create\' = 18, \'fork\' = 19, \'merged\' = 20),\n    `comment_id` UInt64,\n    `body` String,\n    `path` String,\n    `position` Int32,\n    `line` Int32,\n    `ref` LowCardinality(String),\n    `ref_type` Enum8(\'none\' = 0, \'branch\' = 1, \'tag\' = 2, \'repository\' = 3, \'unknown\' = 4),\n    `creator_user_login` LowCardinality(String),\n    `number` UInt32,\n    `title` String,\n    `labels` Array(LowCardinality(String)),\n    `state` Enum8(\'none\' = 0, \'open\' = 1, \'closed\' = 2),\n    `locked` UInt8,\n    `assignee` LowCardinality(String),\n    `assignees` Array(LowCardinality(String)),\n    `comments` UInt32,\n    `author_association` Enum8(\'NONE\' = 0, \'CONTRIBUTOR\' = 1, \'OWNER\' = 2, \'COLLABORATOR\' = 3, \'MEMBER\' = 4, \'MANNEQUIN\' = 5),\n    `closed_at` DateTime,\n    `merged_at` DateTime,\n    `merge_commit_sha` String,\n    `requested_reviewers` Array(LowCardinality(String)),\n    `requested_teams` Array(LowCardinality(String)),\n    `head_ref` LowCardinality(String),\n    `head_sha` String,\n    `base_ref` LowCardinality(String),\n    `base_sha` String,\n    `merged` UInt8,\n    `mergeable` UInt8,\n    `rebaseable` UInt8,\n    `mergeable_state` Enum8(\'unknown\' = 0, \'dirty\' = 1, \'clean\' = 2, \'unstable\' = 3, \'draft\' = 4),\n    `merged_by` LowCardinality(String),\n    `review_comments` UInt32,\n    `maintainer_can_modify` UInt8,\n    `commits` UInt32,\n    `additions` UInt32,\n    `deletions` UInt32,\n    `changed_files` UInt32,\n    `diff_hunk` String,\n    `original_position` UInt32,\n    `commit_id` String,\n    `original_commit_id` String,\n    `push_size` UInt32,\n    `push_distinct_size` UInt32,\n    `member_login` LowCardinality(String),\n    `release_tag_name` String,\n    `release_name` String,\n    `review_state` Enum8(\'none\' = 0, \'approved\' = 1, \'changes_requested\' = 2, \'commented\' = 3, \'dismissed\' = 4, \'pending\' = 5) ')

0 rows in set. Elapsed: 778.468 sec. Processed 4.61 billion rows, 2.48 TB (5.93 million rows/s., 3.18 GB/s.)
```

### PR DESCRIPTION
**Pull request by aaaengel**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fixed `0 rows in set` appearance after `INSERT INTO ... SELECT` query. Closes #47800

### CODE REVIEW

**Comment by aaaengel** [comment]
Oh, client requires `--processed-rows` flag to pass my test. Otherwise I have no idea, how to get number of processed rows from batch mode clickhouse client.

**Comment by alexey-milovidov** [comment]
It's pointless to use `expect` with this test, a usual `.sh` test should be good enough.

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -1369,7 +1369,7 @@ void ClientBase::onProgress(const Progress & value)
         // Just a keep-alive update.
         return;
     }
-
+    processed_rows += value.written_rows;
```
Comment (rienath) [inline src/Client/ClientBase.cpp]: Why not update processed rows for every `onProgress` call  and have it before the above if statement?

**Comment by rienath** [comment]
Since I changed all the lines in this PR, maybe we need one more review. @CheSema, could you help?

File: src/Client/ClientBase.cpp (hunk 1 above)
Comment (rienath) [reply src/Client/ClientBase.cpp]: I fixed it

File: src/Client/ClientBase.cpp [hunk 2]
```diff
@@ -1364,6 +1364,8 @@ bool ClientBase::receiveAndProcessPacket(ASTPtr parsed_query, bool cancelled_)
 
 void ClientBase::onProgress(const Progress & value)
 {
+    processed_rows += value.written_rows;
```
Comment (CheSema) [inline src/Client/ClientBase.cpp]: `ClientBase::processed_rows` counts read OR written bytes which client knows. Usually client accounts inserted and selected rows. But indeed client does not see stats from insert-select query.

Progress packet is optional. Server does not obligated to send it.  But that packet is allowed to be send on insert and select queries. I suspect in that case you would double count.

Also server could send several packages with progress and it contains absolute nubmers, in that case you would count a square.

But this all have to be validated. I might be wrong here.

**Review by rienath — COMMENTED** [review]
@CheSema I have separated the `processed_rows` into block and progress tracking to prevent double counting scenario that you described. I don't think the square scenario is possible because `sendProgress()` calls `fetchValuesAndResetPiecewiseAtomically()` that does `res.read_rows = read_rows.fetch_and(0)`, which 0s out values every time it sends progress report. So we send deltas, not absolute values. Could you please take a look when you have time?

**Review by CheSema — APPROVED** [review]

**Comment by rienath** [comment]
[Stateless tests (amd_asan, distributed plan, sequential)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79462&sha=43c1ad5d6db1b8dc62d8742e05ea6d815693d51c&name_0=PR&name_1=Stateless%20tests%20%28amd_asan%2C%20distributed%20plan%2C%20sequential%29)
* https://github.com/ClickHouse/ClickHouse/issues/89721

[Upgrade check (amd_msan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79462&sha=43c1ad5d6db1b8dc62d8742e05ea6d815693d51c&name_0=PR&name_1=Upgrade%20check%20%28amd_msan%29)
* Was fixed https://github.com/ClickHouse/ClickHouse/issues/89409
