### PR TITLE
Validate SummungMergeTree columns to sum are not in sort key, fix partition key validation. Fix auto resolve of summing cols.

### LINKED ISSUE #76866: Logical error: Sort order of blocks violated for column
### Describe the bug

I can't reproduce it on Fiddle, so I am leaving the reproducible steps on my local setup with the current master on debug build.

### How to reproduce

Run:

```sql
CREATE TABLE t0 (c0 Int, c1 Bool) ENGINE = SummingMergeTree((c0)) ORDER BY (c0 % 41963);
INSERT INTO TABLE t0 (c1, c0) VALUES (TRUE, 81615314);
INSERT INTO TABLE t0 (c1, c0) VALUES (TRUE, 187022644);
INSERT INTO TABLE t0 (c0, c1) VALUES (-395997223, FALSE);
INSERT INTO TABLE t0 (c0, c1) VALUES (724680820, TRUE);
INSERT INTO TABLE t0 (c1, c0) VALUES (TRUE, -206182759);
INSERT INTO TABLE t0 (c0, c1) VALUES (1840266799, FALSE), (511836162, TRUE), (1472754845, FALSE), (-629147868, TRUE);
SELECT * FROM t0 FINAL;
```

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'Sort order of blocks violated for column number 1, left: Int64_13451, right: Int64_-11452. Chunk 0, rows read 5.'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:106: Poco::Exception::Exception(String const&, int) @ 0x000000001a701f72
1. src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000f8645f9
2. src/Common/Exception.h:114: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000009e7d8ac
3. src/Common/Exception.h:132: DB::Exception::Exception<unsigned long&, String, String, unsigned long&, unsigned long&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<String>::type>, unsigned long&, String&&, String&&, unsigned long&, unsigned long&, String&&) @ 0x00000000167a4759
4. src/Processors/Transforms/CheckSortedTransform.cpp:45: DB::CheckSortedTransform::transform(DB::Chunk&)::$_0::operator()(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) const @ 0x00000000167a44b8
5. src/Processors/Transforms/CheckSortedTransform.cpp:73: DB::CheckSortedTransform::transform(DB::Chunk&) @ 0x00000000167a401c
6. src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x00000000116c75b3
7. src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x0000000016545560
8. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001656282f
9. src/Processors/Executors/PipelineExecutor.cpp:296: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000016557925
10. src/Processors/Executors/PipelineExecutor.cpp:170: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000016556ec7
11. src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x00000000165661fc
12. src/Processors/Executors/PullingPipelineExecutor.cpp:65: DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x0000000016566358
13. src/Storages/MergeTree/MergeTask.cpp:880: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() const @ 0x0000000015e7ef02
14. src/Storages/MergeTree/MergeTask.cpp:710: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x0000000015e7d759
15. src/Storages/MergeTree/MergeTask.cpp:1484: DB::MergeTask::execute() @ 0x0000000015e83b2a
16. src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:57: DB::MergePlainMergeTreeTask::executeStep() @ 0x0000000016223465
17. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:318: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x0000000015ea4510
18. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:363: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000015ea4e53
19. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000f927973
20. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000000f92d763
21. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000000f9250b2
22. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000f92b320
23. ? @ 0x00007ffff7ca1e2e
24. ? @ 0x00007ffff7d33a4c
```

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
Closes: #76866

Except mentioned issue, it fixes cases like, when merged rows end up in the wrong partition.
```sql
CREATE TABLE t (key Int32, val Int32) Engine=SummingMergeTree PARTITION BY (key % 2) ORDER BY (key + 0);
INSERT INTO t VALUES (1, 1), (1, 2), (2, 3);
SELECT key % 2, _partition_id FROM t;
```

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Enhance SummingMergeTree validation to skip aggregation for columns used in partition or sort keys.

### Documentation entry for user-facing changes
- [*] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by den-crane** [comment]
BTW it possible to use `SimpleAggregateFunction` 
https://fiddle.clickhouse.com/6e0087d5-1aee-4758-a870-badae7795d01
It also should be forbidden

```sql
CREATE TABLE t0 (c0 SimpleAggregateFunction(sum, Int64)) 
  ENGINE = SummingMergeTree() ORDER BY (c0%1);

INSERT INTO TABLE t0 (c0) VALUES (2),(1),(2);

OPTIMIZE TABLE t0 FINAL;

SELECT * FROM t0;

┌─c0─┐
│  5 │
└────┘
```

**Comment by den-crane** [comment]
Ah, the same issue with AggregatingMergeTree

https://fiddle.clickhouse.com/86457454-d0f1-4ee9-aa6b-92557feb7b3f

```sql
CREATE TABLE t0 (c0 SimpleAggregateFunction(sum, Int64)) 
  ENGINE = AggregatingMergeTree() ORDER BY (c0%1);

INSERT INTO TABLE t0 (c0) VALUES (2),(1),(2);

OPTIMIZE TABLE t0 FINAL;

SELECT * FROM t0;


 ┌─c0─┐
 │  5 │
 └────┘
```

**Comment by GrigoryPervakov** [comment]
> BTW it's possible to use `SimpleAggregateFunction` https://fiddle.clickhouse.com/6e0087d5-1aee-4758-a870-badae7795d01 It also should be forbidden
> 
> ```sql
> CREATE TABLE t0 (c0 SimpleAggregateFunction(sum, Int64)) 
>   ENGINE = SummingMergeTree() ORDER BY (c0%1);
> 
> INSERT INTO TABLE t0 (c0) VALUES (2),(1),(2);
> 
> OPTIMIZE TABLE t0 FINAL;
> 
> SELECT * FROM t0;
> 
> ┌─c0─┐
> │  5 │
> └────┘
> ```
> 
> * [SummingMergeTree yields incorrect results in case of `ORDER BY ( func( ) )` #57818](https://github.com/ClickHouse/ClickHouse/issues/57818)
> * [Confusing SummingMergeTree query #72043](https://github.com/ClickHouse/ClickHouse/issues/72043)
> * [SummingMergeTree different result #74383](https://github.com/ClickHouse/ClickHouse/issues/74383)

This one works fine after the patch, it returns single line 2 as expected

**Comment by den-crane** [comment]
>This one works fine after the patch, it returns single line 2 as expected

No, no, no. It should be forbidden `{ serverError BAD_ARGUMENTS }`

**Comment by GrigoryPervakov** [comment]
> No, no, no. It should be forbidden `{ serverError BAD_ARGUMENTS }`

I am not sure, it's a different check on column comparability, wrapping it with expression casts it to the comparable type, and then it seems to work fine. With that patch in such case, SummingMergeTree won't mistakenly aggregate it, so despite it being a strange choice for the sorting key, it should work ok

**Comment by den-crane** [comment]
OK. Fine. From my POV there is no difference:

```
CREATE TABLE t0 (c0 SimpleAggregateFunction(sum, Int64)) ENGINE = SummingMergeTree() ORDER BY (c0%1);

CREATE TABLE t0 (c0 Int64) ENGINE = SummingMergeTree() ORDER BY (c0%1);
```
67782060_3007442132604299_7656372958578868224_n

**Comment by GrigoryPervakov** [comment]
> OK. Fine. From my POV there is no difference:
> 
> ```
> CREATE TABLE t0 (c0 SimpleAggregateFunction(sum, Int64)) ENGINE = SummingMergeTree() ORDER BY (c0%1);
> 
> CREATE TABLE t0 (c0 Int64) ENGINE = SummingMergeTree() ORDER BY (c0%1);
> ```

From my POV too, and both are valid and behave equally. The only difference is that in the second case, you can use SumMerge on c0 in a select query.

SimpleAggregateFunction won't be ~~magically~~ changed by merge, so rows. would be in the right order

**Comment by den-crane** [comment]
>SimpleAggregateFunction won't be magically changed by merge, so rows. would be in the right order

It obviously leads to a corruption of a Primary Key and must be forbidden.

```
select * from t0 where c0 = 9945;
0 rows in set. Elapsed: 0.005 sec.

select * from t0 where identity(c0) = 9945;
   ┌───c0─┐
1. │ 9945 │
   └──────┘
```

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -1232,6 +1235,21 @@ void MergeTreeData::MergingParams::check(const StorageInMemoryMetadata & metadat
...
+
+        /// Check that summing columns are not in sorting key.
+        if (!allow_summing_columns_in_partition_or_order_key && metadata.isSortingKeyDefined())
+        {
+            auto sorting_key_columns = metadata.getSortingKey().expression->getRequiredColumns();
+
+            Names names_intersection;
+            std::set_intersection(columns_to_sum.begin(), columns_to_sum.end(),
+                                  sorting_key_columns.begin(), sorting_key_columns.end(),
+                                  std::back_inserter(names_intersection));
```
Comment (jkartseva) [inline src/Storages/MergeTree/MergeTreeData.cpp:1247]: Are both `columns_to_sum` and `sorting_key_columns` ranges sorted to use `std::set_intersection`?

In the above snippet, sorting is applied to check for duplicates:
```
        auto columns_to_sum_copy = columns_to_sum;
        std::sort(columns_to_sum_copy.begin(), columns_to_sum_copy.end());
        if (const auto it = std::adjacent_find(columns_to_sum_copy.begin(), columns_to_sum_copy.end()); it != columns_to_sum_copy.end())
            throw Exception(ErrorCodes::BAD_ARGUMENTS, "Column {} is listed multiple times in the list of columns to sum", *it);
  ```
  This implies that `columns_to_sum_copy` may not be sorted.
 
We should use `columns_to_sum_copy` instead of `columns_to_sum`, and it's probably worth renaming it to `columns_to_sum_sorted`.
The type of `sorting_key_columns` is a vector of strings, I'm not sure about the ordering.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/Names.h#L13

Comment (GrigoryPervakov) [reply src/Storages/MergeTree/MergeTreeData.cpp:1247]: It's also not working for existing partition key validation https://fiddle.clickhouse.com/3db966f5-79e6-47b9-a9e9-70bcb06e28ca

**Review by jkartseva — APPROVED** [review]
Looks good.

**Comment by clickgapai** [comment]
Hi @GrigoryPervakov @jkartseva — while reviewing this PR I found the following:

- **Coverage gap:** Add test: `SummingMergeTree` merge with expression-based PARTITION/ORDER keys never exercises the new `expression->getRequiredColumns()` exclusion list — https://github.com/ClickHouse/ClickHouse/pull/103763

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
