### PR TITLE
Some fixes for ReplicatedMergeTree

### LINKED ISSUE #40957: DB::ReplicatedMergeTreeQueue::createLogEntriesToFetchBrokenParts encounter error Code: 84. DB::Exception: Directory already exists and is not empty.
Our clickhouse is encountering error:
```
2022.09.02 20:46:03.548731 [ 549 ] {7f8a252c-6df9-430e-a46d-21d4e7705bf6} <Warning> ClusterProxy::SelectStreamFactory: Local replica of shard 1 is stale (delay: 1662151563s.)
2022.09.02 20:46:35.876197 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (ReplicatedMergeTreeRestartingThread): Table was in readonly mode. Will try to activate it.
2022.09.02 20:46:35.958054 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958083 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try1 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958097 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try2 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958109 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try3 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958122 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try4 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958135 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try5 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958147 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try6 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958160 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try7 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958173 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try8 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.958185 [ 178 ] {} <Warning> bagdb.pipeline_jobs_lo (6d2e1e13-aea4-4e86-ad2e-1e13aea4be86): Directory covered-by-broken_202209_14216_15635_615_try9 (to detach to) already exists. Will detach to directory with '_tryN' suffix.
2022.09.02 20:46:35.962149 [ 178 ] {} <Error> bagdb.pipeline_jobs_lo (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Code: 84. DB::Exception: Directory /var/lib/clickhouse/store/6d2/6d2e1e13-aea4-4e86-ad2e-1e13aea4be86/detached/covered-by-broken_202209_14216_15635_615_try9 already exists and is not empty. (DIRECTORY_ALREADY_EXISTS), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a20fa in /usr/bin/clickhouse
1. DB::localBackup(std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::optional<unsigned long>, bool) @ 0x16ddc380 in /usr/bin/clickhouse
2. DB::IMergeTreeDataPart::makeCloneInDetached(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) const @ 0x16b1a545 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::removePartAndEnqueueFetch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x168e3093 in /usr/bin/clickhouse
4. DB::ReplicatedMergeTreeQueue::createLogEntriesToFetchBrokenParts() @ 0x16d7a24b in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreeRestartingThread::tryStartup() @ 0x16dbb4f0 in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x16db2045 in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x16dafd5e in /usr/bin/clickhouse
8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15569778 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePool::threadFunction() @ 0x1556ca36 in /usr/bin/clickhouse
10. ? @ 0x1556d8ae in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb94d577 in /usr/bin/clickhouse
12. ? @ 0xb95099d in /usr/bin/clickhouse
13. ? @ 0x7fc6e142a609 in ?
14. __clone @ 0x7fc6e1351293 in ?
 (version 22.6.3.35 (official build))
```
Please advise how to recover from this kind of error.

### LINKED ISSUE #41768: intersecting parts in bc_check
https://s3.amazonaws.com/clickhouse-test-reports/41011/c53f463d2d1cb06d4c7a9e0e5b5e657415296c04/stress_test__msan_/bc_check_fatal_messages.txt

```
<Fatal> : Logical error: 'Part 9_8_15_1 intersects previous part 9_0_8_999999999_999999999. It is a bug or a result of manual intervention in the ZooKeeper data.'.
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 22.10.1.1, build id: 922DA16F9FA46E90FC24BCAA153C53C61D16D41B) (from thread 438358) (no query) Received signal Aborted (6)
<Fatal> BaseDaemon: 
<Fatal> BaseDaemon: Stack trace: 0x7f5bf5cc300b 0x7f5bf5ca2859 0xbb98af5 0xbb99093 0x161a3249 0x4393989f 0x4444a32e 0x44446bfd 0x4450bb45 0x44508d86 0x4450688a 0x44519de9 0x3cbdc6f3 0x3cbe5719 0x3cbe7748 0xbd68e11 0xbd75ce3 0x7f5bf5e7a609 0x7f5bf5d9f133
<Fatal> BaseDaemon: 4. raise @ 0x7f5bf5cc300b in ?
<Fatal> BaseDaemon: 5. abort @ 0x7f5bf5ca2859 in ?
<Fatal> : Logical error: 'Part 9_8_15_1 intersects previous part 9_0_8_999999999_999999999. It is a bug or a result of manual intervention in the ZooKeeper data.'.
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 22.10.1.1, build id: 922DA16F9FA46E90FC24BCAA153C53C61D16D41B) (from thread 438304) (no query) Received signal Aborted (6)
<Fatal> BaseDaemon: 
<Fatal> BaseDaemon: Stack trace: 0x7f5bf5cc300b 0x7f5bf5ca2859 0xbb98af5 0xbb99093 0x161a3249 0x4393989f 0x4444a32e 0x44446bfd 0x4450bb45 0x44508d86 0x4450688a 0x44519de9 0x3cbdc6f3 0x3cbe5719 0x3cbe7748 0xbd68e11 0xbd75ce3 0x7f5bf5e7a609 0x7f5bf5d9f133
<Fatal> BaseDaemon: 4. raise @ 0x7f5bf5cc300b in ?
<Fatal> BaseDaemon: 5. abort @ 0x7f5bf5ca2859 in ?
<Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xbb98af5 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:40: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xbb98af5 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../src/Common/Exception.cpp:0: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)
<Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xbb99093 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../src/Common/Exception.cpp:0: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&)
<Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xbb99093 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../contrib/libcxx/include/string:1445: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
<Fatal> BaseDaemon: 8.2. inlined from ./build_docker/../contrib/libcxx/include/string:2231: ~basic_string
<Fatal> BaseDaemon: 8. ./build_docker/../src/Common/Exception.h:37: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x161a3249 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) @ 0x4393989f in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../contrib/libcxx/include/string:1445: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
<Fatal> BaseDaemon: 8.2. inlined from ./build_docker/../contrib/libcxx/include/string:2231: ~basic_string
<Fatal> BaseDaemon: 8. ./build_docker/../src/Common/Exception.h:37: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x161a3249 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) @ 0x4393989f in /usr/bin/clickhouse
<Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::insertUnlocked(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> const&, std::__1::optional<long>&, std::__1::lock_guard<std::__1::mutex>&) @ 0x4444a32e in /usr/bin/clickhouse
<Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::insertUnlocked(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> const&, std::__1::optional<long>&, std::__1::lock_guard<std::__1::mutex>&) @ 0x4444a32e in /usr/bin/clickhouse
<Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::load(std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x44446bfd in /usr/bin/clickhouse
<Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::load(std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x44446bfd in /usr/bin/clickhouse/var/log/clickhouse-server/clickhouse-server.backward.clean.log:2022.09.25 19:41:20.280278 [ 438358 ] {} <Fatal> : Logical error: 'Part 9_8_15_1 intersects previous part 9_0_8_999999999_999999999. It is a bug or a result of manual intervention in the ZooKeeper data.'.
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed "Directory already exists and is not empty" error on detaching broken part that might prevent `ReplicatedMergeTree` table from starting replication. Fixes https://github.com/ClickHouse/ClickHouse/issues/40957

Also it probably fixes https://github.com/ClickHouse/ClickHouse/issues/41768 

Depends on https://github.com/ClickHouse/ClickHouse/pull/41945

### CODE REVIEW

File: src/Storages/MergeTree/DataPartStorageOnDisk.cpp [hunk 1]
```diff
@@ -406,27 +406,87 @@ void DataPartStorageOnDisk::clearDirectory(
...
+            return {};
+        }
+
         LOG_WARNING(log, "Directory {} (to detach to) already exists. Will detach to directory with '_tryN' suffix.", res);
     }
 
     return res;
 }
 
+bool DataPartStorageOnDisk::looksLikeBrokenDetachedPartHasTheSameContent(const String & detached_part_path,
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/DataPartStorageOnDisk.cpp:441]: Now it's my favorite function name!

Comment (tavplubix) [reply src/Storages/MergeTree/DataPartStorageOnDisk.cpp:441]: Cool, my favorite is `MergeTreeData::removePartsInRangeFromWorkingSetAndGetPartsToRemoveFromZooKeeper`

File: src/Storages/MergeTree/IDataPartStorage.h [hunk 2]
```diff
@@ -129,7 +129,11 @@ class IDataPartStorage
 
     /// Get a name like 'prefix_partdir_tryN' which does not exist in a root dir.
     /// TODO: remove it.
-    virtual std::string getRelativePathForPrefix(Poco::Logger * log, const String & prefix, bool detached) const = 0;
+    virtual std::optional<String> getRelativePathForPrefix(Poco::Logger * log, const String & prefix, bool detached, bool broken) const = 0;
+
+    virtual bool looksLikeBrokenDetachedPartHasTheSameContent(const String & detached_part_path,
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/IDataPartStorage.h:134]: I would better remove this function from `IDataPartStorage.h` iface, only keep it in `DataPartStorageOnDisk`.
Also, comment is needed.

File: src/Storages/MergeTree/IDataPartStorage.h [hunk 3]
```diff
@@ -129,7 +129,11 @@ class IDataPartStorage
 
     /// Get a name like 'prefix_partdir_tryN' which does not exist in a root dir.
     /// TODO: remove it.
-    virtual std::string getRelativePathForPrefix(Poco::Logger * log, const String & prefix, bool detached) const = 0;
+    virtual std::optional<String> getRelativePathForPrefix(Poco::Logger * log, const String & prefix, bool detached, bool broken) const = 0;
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/IDataPartStorage.h:132]: Please, add a comment what should be the semantic for `std::nullopt`. E.g. what we gonna do with it :)

File: src/Storages/MergeTree/IDataPartStorage.h (hunk 2 above)
Comment (tavplubix) [reply src/Storages/MergeTree/IDataPartStorage.h:134]: Initially I tried to add this function to `IMergeTreeDataPart` instead of `IDataPartStorage`, but it's impossible because we have disk there.

File: src/Storages/MergeTree/IDataPartStorage.h (hunk 3 above)
Comment (KochetovNicolai) [reply src/Storages/MergeTree/IDataPartStorage.h:132]: Also not clear what combination of detached/broken is possible.
Maybe replace two this flags to Enum?

**Review by KochetovNicolai — APPROVED** [review]
LGTM, the idea is clear

File: src/Storages/MergeTree/IDataPartStorage.h (hunk 3 above)
Comment (tavplubix) [reply src/Storages/MergeTree/IDataPartStorage.h:132]: But we also have `getRelativePathForDetachedPart` and it has only one flag (`broken`). We can use enum for `getRelativePathForPrefix`, but for `getRelativePathForDetachedPart` we have two options:
 - pass enum instead of flag too, but it will not be clear which values of enum are possible
 - keep one flag and convert it to enum, but I don't like mixing enum and flags

So both options look bad

**Comment by tavplubix** [comment]
Integration tests (release) [2/2] - https://github.com/ClickHouse/ClickHouse/pull/42535
Stress test (msan) - too slow `MergeTreeData::clearOldPartsFromFilesystem` on shutdown

**Comment by baolinhuang** [comment]
This fix is incomplete. The metadata_version.txt file is deleted during covered-by-broken clone. As a result, looksLikeBrokenDetachedPartHasTheSameContent finds differences during part comparison.

https://github.com/ClickHouse/ClickHouse/pull/68584
