### PR TITLE
Fix Buffer's offsets mismatch logical error in stress test

### LINKED ISSUE #45408: Logical error: 'Buffer's offsets mismatch.
https://s3.amazonaws.com/clickhouse-test-reports/0/88ba1b0b85bb438c201f4d2ad6c0a5eefb08dee0/stress_test__ubsan_.html

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:04:40.544962 [ 10740 ] {562696dc-38f5-40df-a97d-1429c8714820} <Fatal> : Logical error: 'Buffer's offsets mismatch. Cached buffer offset: 0, current_write_offset: 0 implementation buffer offset: -40183, implementation buffer remaining range: [0:100178], file segment info: File segment: [0, 100178], key: 3af7e2579e62d53277e3dc7142bcfef2, state: DOWNLOADING, downloaded size: 0, reserved size: 40183, downloader id: 562696dc-38f5-40df-a97d-1429c8714820:10740, current write offset: 0, first non-downloaded offset: 0, caller id: 562696dc-38f5-40df-a97d-1429c8714820:10740, detached: 0, kind: Regular'.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.593359 [ 206181 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.593406 [ 206181 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: 7FEAABF56AD21964BD7B67B40D112677861D1D83) (from thread 10740) (query_id: 562696dc-38f5-40df-a97d-1429c8714820) (query: select queryID() from (SELECT * FROM test_02226 LIMIT 10) limit 1) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.593432 [ 206181 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.593503 [ 206181 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f634327700b 0x7f6343256859 0x22029463 0x2202976f 0x2cf9fea1 0x2cf8ee8e 0x2cf975d2 0x2cf96f05 0x176639d6 0x2cb3a663 0x2cb3e02b 0x2ce42268 0x2cdd2be8 0x2f2c734d 0x2f2c6047 0x30099f36 0x3009a08b 0x3009aa52 0x300a5c7e 0x300a3777 0x3008f4a8 0x3008ff95 0x3008c8a2 0x300c1881 0x2f95eb3f 0x2f98689f 0x2f97605b 0x2f975896 0x2f97564a 0x2f98b15f 0x221336da 0x22137124 0x7f634342e609 0x7f6343353133
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.593554 [ 206181 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f634327700b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.593578 [ 206181 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f6343256859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.633294 [ 206181 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x22029463 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.664624 [ 206181 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x2202976f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.684566 [ 206181 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.684604 [ 206181 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.684617 [ 206181 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/../src/Common/Exception.h:32: ~MessageMasked
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.684631 [ 206181 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/../src/Common/Exception.h:41: Exception
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.684645 [ 206181 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<unsigned long&, unsigned long&, long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<unsigned long&>::type, fmt::v8::type_identity<unsigned long&>::type, fmt::v8::type_identity<long>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, unsigned long&, unsigned long&, long&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x2cf9fea1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.703071 [ 206181 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:456: DB::CachedOnDiskReadBufferFromFile::getImplementationBuffer(std::__1::shared_ptr<DB::FileSegment>&) @ 0x2cf8ee8e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.718376 [ 206181 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:827: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x2cf975d2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:14.739577 [ 206181 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:766: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x2cf96f05 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.418290 [ 206181 ] {} <Fatal> BaseDaemon: 11. DB::ReadBuffer::next() @ 0x176639d6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.428573 [ 206181 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Compression/CompressedReadBufferBase.cpp:210: DB::CompressedReadBufferBase::readCompressedDataBlockForAsynchronous(unsigned long&, unsigned long&) @ 0x2cb3a663 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.438171 [ 206181 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Compression/CompressedReadBufferFromFile.cpp:111: DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x2cb3e02b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.461696 [ 206181 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/DataTypes/Serializations/SerializationNumber.cpp:155: DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x2ce42268 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.477474 [ 206181 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:140: intrusive_ptr<DB::IColumn>
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.477510 [ 206181 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/../src/Common/COW.h:144: immutable_ptr<DB::IColumn>
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.477539 [ 206181 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/DataTypes/Serializations/ISerialization.cpp:133: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x2cdd2be8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.500008 [ 206181 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:0: DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, unsigned long, unsigned long, bool) @ 0x2f2c734d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.522424 [ 206181 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:185: DB::MergeTreeReaderCompact::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x2f2c6047 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.547261 [ 206181 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:105: DB::MergeTreeRangeReader::DelayedStream::readRows(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x30099f36 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.571526 [ 206181 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:177: DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x3009a08b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.596248 [ 206181 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.h:121: DB::MergeTreeRangeReader::DelayedStream::isFinished() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.596281 [ 206181 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:290: DB::MergeTreeRangeReader::Stream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x3009aa52 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.623990 [ 206181 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) @ 0x300a5c7e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.647257 [ 206181 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) @ 0x300a3777 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.688741 [ 206181 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:404: DB::IMergeTreeSelectAlgorithm::readFromPartImpl() @ 0x3008f4a8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.729473 [ 206181 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:447: DB::IMergeTreeSelectAlgorithm::readFromPart() @ 0x3008ff95 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.769006 [ 206181 ] {} <Fatal> BaseDaemon: 25. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:224: DB::IMergeTreeSelectAlgorithm::read() @ 0x3008c8a2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.785224 [ 206181 ] {} <Fatal> BaseDaemon: 26. ./build_docker/../src/Storages/MergeTree/MergeTreeSource.cpp:214: DB::MergeTreeSource::tryGenerate() @ 0x300c1881 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.799824 [ 206181 ] {} <Fatal> BaseDaemon: 27.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:344: std::__1::__optional_storage_base<DB::Chunk, false>::has_value[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.799855 [ 206181 ] {} <Fatal> BaseDaemon: 27.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:998: std::__1::optional<DB::Chunk>::operator bool[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.799868 [ 206181 ] {} <Fatal> BaseDaemon: 27. ./build_docker/../src/Processors/ISource.cpp:94: DB::ISource::work() @ 0x2f95eb3f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.806989 [ 206181 ] {} <Fatal> BaseDaemon: 28.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.807016 [ 206181 ] {} <Fatal> BaseDaemon: 28. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2f98689f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.825916 [ 206181 ] {} <Fatal> BaseDaemon: 29. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2f97605b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.843035 [ 206181 ] {} <Fatal> BaseDaemon: 30. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2f975896 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.861378 [ 206181 ] {} <Fatal> BaseDaemon: 31.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph>>::operator->[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.861409 [ 206181 ] {} <Fatal> BaseDaemon: 31. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:93: DB::PipelineExecutor::execute(unsigned long) @ 0x2f97564a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879366 [ 206181 ] {} <Fatal> BaseDaemon: 32.1. inlined from ./build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879395 [ 206181 ] {} <Fatal> BaseDaemon: 32.2. inlined from ./build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:111: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879417 [ 206181 ] {} <Fatal> BaseDaemon: 32.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879437 [ 206181 ] {} <Fatal> BaseDaemon: 32.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879454 [ 206181 ] {} <Fatal> BaseDaemon: 32.5. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879468 [ 206181 ] {} <Fatal> BaseDaemon: 32.6. inlined from ./build_docker/../src/Common/ThreadPool.h:196: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879489 [ 206181 ] {} <Fatal> BaseDaemon: 32.7. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879511 [ 206181 ] {} <Fatal> BaseDaemon: 32.8. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879538 [ 206181 ] {} <Fatal> BaseDaemon: 32.9. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.879552 [ 206181 ] {} <Fatal> BaseDaemon: 32. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2f98b15f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.891125 [ 206181 ] {} <Fatal> BaseDaemon: 33.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.891147 [ 206181 ] {} <Fatal> BaseDaemon: 33.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.891160 [ 206181 ] {} <Fatal> BaseDaemon: 33. ./build_docker/../src/Common/ThreadPool.cpp:297: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x221336da in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.905042 [ 206181 ] {} <Fatal> BaseDaemon: 34. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x22137124 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.905068 [ 206181 ] {} <Fatal> BaseDaemon: 35. ? @ 0x7f634342e609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:18.905083 [ 206181 ] {} <Fatal> BaseDaemon: 36. clone @ 0x7f6343353133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:05:19.206451 [ 206181 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: FBB20F6C39F0A6BF4835715A5068FE8E)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.16 21:10:13.061837 [ 1578 ] {} <Fatal> Application: Child process was terminated by signal 6.
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:04:40.544962 [ 10740 ] {562696dc-38f5-40df-a97d-1429c8714820} <Fatal> : Logical error: 'Buffer's offsets mismatch. Cached buffer offset: 0, current_write_offset: 0 implementation buffer offset: -40183, implementation buffer remaining range: [0:100178], file segment info: File segment: [0, 100178], key: 3af7e2579e62d53277e3dc7142bcfef2, state: DOWNLOADING, downloaded size: 0, reserved size: 40183, downloader id: 562696dc-38f5-40df-a97d-1429c8714820:10740, current write offset: 0, first non-downloaded offset: 0, caller id: 562696dc-38f5-40df-a97d-1429c8714820:10740, detached: 0, kind: Regular'.
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.593359 [ 206181 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.593406 [ 206181 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: 7FEAABF56AD21964BD7B67B40D112677861D1D83) (from thread 10740) (query_id: 562696dc-38f5-40df-a97d-1429c8714820) (query: select queryID() from (SELECT * FROM test_02226 LIMIT 10) limit 1) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.593432 [ 206181 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.593503 [ 206181 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f634327700b 0x7f6343256859 0x22029463 0x2202976f 0x2cf9fea1 0x2cf8ee8e 0x2cf975d2 0x2cf96f05 0x176639d6 0x2cb3a663 0x2cb3e02b 0x2ce42268 0x2cdd2be8 0x2f2c734d 0x2f2c6047 0x30099f36 0x3009a08b 0x3009aa52 0x300a5c7e 0x300a3777 0x3008f4a8 0x3008ff95 0x3008c8a2 0x300c1881 0x2f95eb3f 0x2f98689f 0x2f97605b 0x2f975896 0x2f97564a 0x2f98b15f 0x221336da 0x22137124 0x7f634342e609 0x7f6343353133
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.593554 [ 206181 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f634327700b in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.593578 [ 206181 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f6343256859 in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.633294 [ 206181 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x22029463 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.664624 [ 206181 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x2202976f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.684566 [ 206181 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.684604 [ 206181 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.684617 [ 206181 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/../src/Common/Exception.h:32: ~MessageMasked
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.684631 [ 206181 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/../src/Common/Exception.h:41: Exception
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.684645 [ 206181 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<unsigned long&, unsigned long&, long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<unsigned long&>::type, fmt::v8::type_identity<unsigned long&>::type, fmt::v8::type_identity<long>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, unsigned long&, unsigned long&, long&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x2cf9fea1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.703071 [ 206181 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:456: DB::CachedOnDiskReadBufferFromFile::getImplementationBuffer(std::__1::shared_ptr<DB::FileSegment>&) @ 0x2cf8ee8e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.718376 [ 206181 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:827: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x2cf975d2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:14.739577 [ 206181 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:766: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x2cf96f05 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.418290 [ 206181 ] {} <Fatal> BaseDaemon: 11. DB::ReadBuffer::next() @ 0x176639d6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.428573 [ 206181 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Compression/CompressedReadBufferBase.cpp:210: DB::CompressedReadBufferBase::readCompressedDataBlockForAsynchronous(unsigned long&, unsigned long&) @ 0x2cb3a663 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.438171 [ 206181 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Compression/CompressedReadBufferFromFile.cpp:111: DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x2cb3e02b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.461696 [ 206181 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/DataTypes/Serializations/SerializationNumber.cpp:155: DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x2ce42268 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.477474 [ 206181 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:140: intrusive_ptr<DB::IColumn>
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.477510 [ 206181 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/../src/Common/COW.h:144: immutable_ptr<DB::IColumn>
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.477539 [ 206181 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/DataTypes/Serializations/ISerialization.cpp:133: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x2cdd2be8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.500008 [ 206181 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:0: DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, unsigned long, unsigned long, bool) @ 0x2f2c734d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.522424 [ 206181 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderCompact.cpp:185: DB::MergeTreeReaderCompact::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x2f2c6047 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.547261 [ 206181 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:105: DB::MergeTreeRangeReader::DelayedStream::readRows(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x30099f36 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.571526 [ 206181 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:177: DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x3009a08b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.596248 [ 206181 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.h:121: DB::MergeTreeRangeReader::DelayedStream::isFinished() const
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.596281 [ 206181 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:290: DB::MergeTreeRangeReader::Stream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x3009aa52 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.623990 [ 206181 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) @ 0x300a5c7e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.647257 [ 206181 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) @ 0x300a3777 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.688741 [ 206181 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:404: DB::IMergeTreeSelectAlgorithm::readFromPartImpl() @ 0x3008f4a8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.729473 [ 206181 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:447: DB::IMergeTreeSelectAlgorithm::readFromPart() @ 0x3008ff95 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.769006 [ 206181 ] {} <Fatal> BaseDaemon: 25. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:224: DB::IMergeTreeSelectAlgorithm::read() @ 0x3008c8a2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.785224 [ 206181 ] {} <Fatal> BaseDaemon: 26. ./build_docker/../src/Storages/MergeTree/MergeTreeSource.cpp:214: DB::MergeTreeSource::tryGenerate() @ 0x300c1881 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.799824 [ 206181 ] {} <Fatal> BaseDaemon: 27.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:344: std::__1::__optional_storage_base<DB::Chunk, false>::has_value[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.799855 [ 206181 ] {} <Fatal> BaseDaemon: 27.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:998: std::__1::optional<DB::Chunk>::operator bool[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.799868 [ 206181 ] {} <Fatal> BaseDaemon: 27. ./build_docker/../src/Processors/ISource.cpp:94: DB::ISource::work() @ 0x2f95eb3f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.806989 [ 206181 ] {} <Fatal> BaseDaemon: 28.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.807016 [ 206181 ] {} <Fatal> BaseDaemon: 28. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2f98689f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.825916 [ 206181 ] {} <Fatal> BaseDaemon: 29. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2f97605b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.843035 [ 206181 ] {} <Fatal> BaseDaemon: 30. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2f975896 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.861378 [ 206181 ] {} <Fatal> BaseDaemon: 31.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph>>::operator->[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.861409 [ 206181 ] {} <Fatal> BaseDaemon: 31. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:93: DB::PipelineExecutor::execute(unsigned long) @ 0x2f97564a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879366 [ 206181 ] {} <Fatal> BaseDaemon: 32.1. inlined from ./build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879395 [ 206181 ] {} <Fatal> BaseDaemon: 32.2. inlined from ./build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:111: operator()
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879417 [ 206181 ] {} <Fatal> BaseDaemon: 32.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879437 [ 206181 ] {} <Fatal> BaseDaemon: 32.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879454 [ 206181 ] {} <Fatal> BaseDaemon: 32.5. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879468 [ 206181 ] {} <Fatal> BaseDaemon: 32.6. inlined from ./build_docker/../src/Common/ThreadPool.h:196: operator()
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879489 [ 206181 ] {} <Fatal> BaseDaemon: 32.7. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879511 [ 206181 ] {} <Fatal> BaseDaemon: 32.8. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879538 [ 206181 ] {} <Fatal> BaseDaemon: 32.9. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.879552 [ 206181 ] {} <Fatal> BaseDaemon: 32. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2f98b15f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.891125 [ 206181 ] {} <Fatal> BaseDaemon: 33.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.891147 [ 206181 ] {} <Fatal> BaseDaemon: 33.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.891160 [ 206181 ] {} <Fatal> BaseDaemon: 33. ./build_docker/../src/Common/ThreadPool.cpp:297: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x221336da in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.905042 [ 206181 ] {} <Fatal> BaseDaemon: 34. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x22137124 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.905068 [ 206181 ] {} <Fatal> BaseDaemon: 35. ? @ 0x7f634342e609 in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:18.905083 [ 206181 ] {} <Fatal> BaseDaemon: 36. clone @ 0x7f6343353133 in ?
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:05:19.206451 [ 206181 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: FBB20F6C39F0A6BF4835715A5068FE8E)
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.16 21:10:13.061837 [ 1578 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

I mark this PR as not-for-changelog, because this error is related to cache over some local disk, which was implemented for testing and is not likely to be used anywhere.

Closes https://github.com/ClickHouse/ClickHouse/issues/45408.

### CODE REVIEW

File: src/IO/BoundedReadBuffer.cpp [hunk 1]
```diff
@@ -64,7 +68,7 @@ off_t BoundedReadBuffer::seek(off_t off, int whence)
     auto result = impl->seek(off, whence);
     swap(*impl);
 
-    file_offset_of_buffer_end = result;
+    file_offset_of_buffer_end = impl->getFileOffsetOfBufferEnd();
```
Comment (kssenii) [inline src/IO/BoundedReadBuffer.cpp:71]: fix is in this line

**Comment by kssenii** [comment]
> Stress test (tsan) — Sanitizer assert (in stderr.log)

```
WARNING: ThreadSanitizer: data race (pid=1546)
  Write of size 8 at 0x7b6402690878 by thread T890:
    #0 DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool)::'lambda'()::operator()() const build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:725:34 (clickhouse+0x1f157bf4) (BuildId: 5c127a9323d546e37605a3841b5ce0e3f17df0e4)
    #1 void DB::ZooKeeperRetriesControl::retryLoop<DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool)::'lambda'(), DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool)::'lambda0'()>(DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool)::'lambda'()&&, DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool)::'lambda0'()&&) build_docker/../src/Storages/MergeTree/ZooKeeperRetries.h:53:17 (clickhouse+0x1f142d87) (BuildId: 5c127a9323d546e37605a3841b5ce0e3f17df0e4)
```
https://github.com/ClickHouse/ClickHouse/issues/45158

**Review by Avogar — APPROVED** [review]
