### PR TITLE
Fix a query with duplicating cycling alias.

### LINKED ISSUE #63320: Error in ClickHouse query: Multiple expressions for alias.
When executing the following query in ClickHouse version 24.4.1.2088:
```
SELECT toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc,
sum(impressions) AS Impressions,
sum(clicks) AS Clicks,
sum(revenue) AS Revenue
FROM test_table
WHERE time_stamp_utc >= toDateTime('2024-04-25 00:00:00')
AND time_stamp_utc < toDateTime('2024-05-02 00:00:00')
GROUP BY toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc
ORDER BY Impressions DESC
LIMIT 1000;
```

I encountered the following error:
```
Code: 179. DB::Exception: Received from localhost:9000. DB::Exception: 
Multiple expressions toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc and toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc for alias time_stamp_utc.
In scope SELECT toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc, sum(impressions) AS Impressions, sum(clicks) AS Clicks, sum(revenue) AS Revenue FROM test_table WHERE (time_stamp_utc >= toDateTime('2024-04-25 00:00:00')) AND (time_stamp_utc < toDateTime('2024-05-02 00:00:00')) GROUP BY time_stamp_utc ORDER BY Impressions DESC LIMIT 1000. 
(MULTIPLE_EXPRESSIONS_FOR_ALIAS)
```

### Additional Information
- This query works as expected in ClickHouse version 24.2.3.70 but fails with the described error in version 24.4.1.2088.

### Table Schema
```
CREATE TABLE test_table(
    time_stamp_utc DateTime,
    impressions UInt32,
    clicks UInt32,
    revenue Float32,
) ENGINE = MergeTree
ORDER BY time_stamp_utc;
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a query with a duplicating cycling alias. Fixes #63320

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 6a6688169aff02ed724f5a9763fde7ae3e234650 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63791/6a6688169aff02ed724f5a9763fde7ae3e234650/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -8212,6 +8212,10 @@ void QueryAnalyzer::resolveQuery(const QueryTreeNodePtr & query_node, Identifier
     {
         auto node = node_with_duplicated_alias;
         auto node_alias = node->getAlias();
+
+        /// Add current alias to non cached set, because in case of cyclic alias identifier should not be substituted from cache.
+        /// See 02896_cyclic_aliases_crash.
+        scope.non_cached_identifier_lookups_during_expression_resolve.insert({Identifier{node_alias}, IdentifierLookupContext::EXPRESSION});
```
Comment (novikd) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:8218]: Resolve caching introduces a lot of problems, it's interesting if it has a big performance impact. Maybe we should try to disable it at all in a separate PR and check perf tests. WDYT?

**Review by novikd — APPROVED** [review]
LGTM

File: src/Analyzer/Passes/QueryAnalysisPass.cpp (hunk 1 above)
Comment (KochetovNicolai) [reply src/Analyzer/Passes/QueryAnalysisPass.cpp:8218]: Resolve caching is kind of ok, cause it caches by raw ptr...
Identifier lookup cache is hard to support because it is not aware of the context, and we need to care about cyclic aliases
Alias cache (especially since we store the resolved and unresolved tree in the same map) is scary, and makes our query tree a DAG.
