### PR TITLE
Fix flaky test 00417_kill_query

### LINKED ISSUE #50910: 00417_kill_query is flaky
https://s3.amazonaws.com/clickhouse-test-reports/50405/002c15823c26c3e0c577a4dd8ec8f319b3120a78/stateless_tests__debug__[3_5].html

```
2023-06-13 09:50:42 --- /usr/share/clickhouse-test/queries/0_stateless/00417_kill_query.reference	2023-06-13 09:29:33.443223192 +0600
2023-06-13 09:50:42 +++ /tmp/clickhouse-test/0_stateless/00417_kill_query.stdout	2023-06-13 09:50:42.648019112 +0600
2023-06-13 09:50:42 @@ -1,2 +1 @@
2023-06-13 09:50:42  SELECT sleep(1) FROM system.numbers LIMIT 4
2023-06-13 09:50:42 -SELECT sleep(1) FROM system.numbers LIMIT 5
2023-06-13 09:50:42 
2023-06-13 09:50:42 
2023-06-13 09:50:42 Settings used in the test: --max_insert_threads=8 --group_by_two_level_threshold=1 --group_by_two_level_threshold_bytes=1 --distributed_aggregation_memory_efficient=0 --fsync_metadata=1 --output_format_parallel_formatting=1 --input_format_parallel_parsing=0 --min_chunk_bytes_for_parallel_parsing=6780425 --max_read_buffer_size=709649 --prefer_localhost_replica=0 --max_block_size=35710 --max_threads=58 --optimize_or_like_chain=1 --optimize_read_in_order=1 --enable_multiple_prewhere_read_steps=0 --read_in_order_two_level_merge_threshold=23 --optimize_aggregation_in_order=1 --aggregation_in_order_max_block_bytes=24320792 --min_compress_block_size=2172114 --max_compress_block_size=1598415 --use_uncompressed_cache=0 --min_bytes_to_use_direct_io=1 --min_bytes_to_use_mmap_io=10737418240 --local_filesystem_read_method=mmap --remote_filesystem_read_method=read --local_filesystem_read_prefetch=0 --remote_filesystem_read_prefetch=1 --allow_prefetched_read_pool_for_remote_filesystem=0 --filesystem_prefetch_max_memory_usage=64Mi --filesystem_prefetches_limit=10 --filesystem_prefetch_min_bytes_for_single_read_task=16Mi --filesystem_prefetch_step_marks=50 --filesystem_prefetch_step_bytes=0 --compile_expressions=1 --compile_aggregate_expressions=0 --compile_sort_description=0 --merge_tree_coarse_index_granularity=9 --optimize_distinct_in_order=1 --optimize_sorting_by_input_stream_properties=1 --http_response_buffer_size=8964026 --http_wait_end_of_query=True --enable_memory_bound_merging_of_aggregation_results=1
2023-06-13 09:50:42 
2023-06-13 09:50:42 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization=1.0 --prefer_fetch_merged_part_size_threshold=1108824689 --vertical_merge_algorithm_min_rows_to_activate=1000000 --vertical_merge_algorithm_min_columns_to_activate=100 --allow_vertical_merges_from_compact_to_wide_parts=1 --min_merge_bytes_to_use_direct_io=5862978293 --index_granularity_bytes=6157372 --merge_max_block_size=11709 --index_granularity=48824 --min_bytes_for_wide_part=0 --marks_compress_block_size=27864 --primary_key_compress_block_size=18792
2023-06-13 09:50:42 
2023-06-13 09:50:42 Database: test_q6h398so
```

https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA1LTAyJyBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMDQxN19raWxsX3F1ZXJ5JScgYW5kIHN0YXR1cyA9PSAnRkFJTCcKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZSBkZXNj

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/50910

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit d98776b70850f140494bc5e799219877f50124ca with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51522/d98776b70850f140494bc5e799219877f50124ca/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by qoega — APPROVED** [review]

File: tests/queries/0_stateless/00417_kill_query.sh [hunk 1]
```diff
@@ -9,13 +9,13 @@ CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
 QUERY_FIELND_NUM=4
 
-$CLICKHOUSE_CLIENT --max_block_size=1 -q "SELECT sleep(1) FROM system.numbers LIMIT 4" &>/dev/null &
+$CLICKHOUSE_CLIENT --max_block_size=1 -q "SELECT sleep(1) FROM system.numbers LIMIT 30" &>/dev/null &
 sleep 1
 $CLICKHOUSE_CLIENT -q "KILL QUERY WHERE current_database = '${CLICKHOUSE_DATABASE}' and query LIKE 'SELECT sleep(%' AND (elapsed >= 0.) SYNC" | cut -f $QUERY_FIELND_NUM
 
-$CLICKHOUSE_CLIENT --max_block_size=1 -q "SELECT sleep(1) FROM system.numbers LIMIT 5" &>/dev/null &
+$CLICKHOUSE_CLIENT --max_block_size=1 -q "SELECT sleep(1) FROM system.numbers LIMIT 31" &>/dev/null &
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/00417_kill_query.sh:16]: Add a comment explaining why 31.

**Review by alexey-milovidov — APPROVED** [review]
