### PR TITLE
WriteBufferFromS3: fix data race on deque

### LINKED ISSUE #93185: data-race for WriteBufferFromS3::multipart_tags
https://pastila.nl/?000a0cfa/941f8fa869c17913ec906a7622627b77#VwF77u74h8yupEv1Grv1Ug==GCM

```
WARNING: ThreadSanitizer: data race (pid=305)
  Read of size 8 at 0x725c01f7f130 by thread T686:
    #0 std::__1::__split_buffer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*>>::begin[abi:ne210105]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__split_buffer:114:91 (clickhouse+0x1d9b763d) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #1 std::__1::deque<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::operator[](unsigned long) ci/tmp/build/./contrib/llvm-project/libcxx/include/deque:1524:21 (clickhouse+0x1d9b763d)
    #2 DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0::operator()() const ci/tmp/build/./src/IO/WriteBufferFromS3.cpp:604:9 (clickhouse+0x1d9b763d)
    #3 std::__1::__invoke_result_impl<void, DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&>::type std::__1::__invoke[abi:ne210105]<DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&>(DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x1d9b763d)
    #4 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&>(DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5 (clickhouse+0x1d9b763d)
    #5 void std::__1::__invoke_r[abi:ne210105]<void, DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&>(DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10 (clickhouse+0x1d9b763d)
    #6 void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&)::$_0>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12 (clickhouse+0x1d9b763d)
    #7 std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12 (clickhouse+0x1d5c3ec8) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #8 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10 (clickhouse+0x1d5c3ec8)
    #9 DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0::operator()() ci/tmp/build/./src/Common/ThreadPoolTaskTracker.cpp:130:9 (clickhouse+0x1d5c3ec8)
    #10 std::__1::__invoke_result_impl<void, DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&>::type std::__1::__invoke[abi:ne210105]<DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&>(DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x1d5c3ec8)
    #11 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&>(DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5 (clickhouse+0x1d5c3ec8)
    #12 void std::__1::__invoke_r[abi:ne210105]<void, DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&>(DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10 (clickhouse+0x1d5c3ec8)
    #13 void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::TaskTracker::add(std::__1::function<void ()>&&)::$_0>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12 (clickhouse+0x1d5c3ec8)
    #14 std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12 (clickhouse+0x18f8f84b) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #15 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10 (clickhouse+0x18f8f84b)
    #16 std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda'()::operator()() ci/tmp/build/./src/Common/threadPoolCallbackRunner.h:46:20 (clickhouse+0x18f8f84b)
    #17 std::__1::__invoke_result_impl<void, std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda'()&>::type std::__1::__invoke[abi:ne210105]<std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda'()&>(std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x18f8f84b)
    #18 std::__1::__packaged_task_func<std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda'(), std::__1::allocator<std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda'()>, void ()>::operator()() ci/tmp/build/./contrib/llvm-project/libcxx/include/future:1450:10 (clickhouse+0x18f8f79d) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #19 std::__1::__packaged_task_function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/future:1601:10 (clickhouse+0x18f8fb54) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #20 std::__1::packaged_task<void ()>::operator()() ci/tmp/build/./contrib/llvm-project/libcxx/include/future:1762:5 (clickhouse+0x18f8fb54)
    #21 std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()::operator()() const ci/tmp/build/./src/Common/threadPoolCallbackRunner.h:53:70 (clickhouse+0x18f8fa6c) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #22 std::__1::__invoke_result_impl<void, std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&>::type std::__1::__invoke[abi:ne210105]<std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&>(std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x18f8fa6c)
    #23 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&>(std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5 (clickhouse+0x18f8fa6c)
    #24 void std::__1::__invoke_r[abi:ne210105]<void, std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&>(std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10 (clickhouse+0x18f8fa6c)
    #25 void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<std::__1::function<std::__1::future<void> (std::__1::function<void ()>&&, Priority)> DB::threadPoolCallbackRunnerUnsafe<void, std::__1::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, DB::ThreadName)::'lambda'(std::__1::function<void ()>&&, Priority)::operator()(std::__1::function<void ()>&&, Priority)::'lambda0'()>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12 (clickhouse+0x18f8fa6c)
    #26 std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12 (clickhouse+0x166a01a4) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #27 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10 (clickhouse+0x166a01a4)
    #28 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:801:17 (clickhouse+0x166a01a4)
    #29 std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h (clickhouse+0x166a96c4) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #30 decltype(auto) std::__1::__apply_tuple_impl[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<0ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1380:5 (clickhouse+0x166a96c4)
    #31 decltype(auto) std::__1::apply[abi:ne210105]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1384:5 (clickhouse+0x166a96c4)
    #32 ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13 (clickhouse+0x166a96c4)
    #33 std::__1::__invoke_result_impl<void, ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()&>::type std::__1::__invoke[abi:ne210105]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x166a95e1) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #34 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5 (clickhouse+0x166a95e1)
    #35 void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*std::__1::__invoke_r[abi:ne210105]<void, ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&))() ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10 (clickhouse+0x166a95e1)
    #36 void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12 (clickhouse+0x166a95e1)
    #37 std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12 (clickhouse+0x1669c0b0) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #38 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10 (clickhouse+0x1669c0b0)
    #39 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:811:17 (clickhouse+0x1669c0b0)
    #40 std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h (clickhouse+0x166a619b) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #41 void std::__1::__thread_execute[abi:ne210105]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:159:3 (clickhouse+0x166a619b)
    #42 void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:168:3 (clickhouse+0x166a619b)

  Previous write of size 8 at 0x725c01f7f130 by thread T4358:
    #0 std::__1::enable_if<is_move_constructible<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>**>::value && is_move_assignable<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>**>::value, void>::type std::__1::swap[abi:ne210105]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>**>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>**&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>**&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__utility/swap.h:44:7 (clickhouse+0x167e2f37) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #1 std::__1::deque<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::__add_back_capacity() ci/tmp/build/./contrib/llvm-project/libcxx/include/deque:2208:5 (clickhouse+0x167e2f37)
    #2 std::__1::deque<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::push_back(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/deque:1605:5 (clickhouse+0x1d9b3c9f) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #3 DB::WriteBufferFromS3::writePart(DB::WriteBufferFromS3::PartData&&) ci/tmp/build/./src/IO/WriteBufferFromS3.cpp:532:20 (clickhouse+0x1d9b3c9f)
    #4 DB::WriteBufferFromS3::writeMultipartUpload() ci/tmp/build/./src/IO/WriteBufferFromS3.cpp:402:9 (clickhouse+0x1d9a589b) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #5 DB::WriteBufferFromS3::nextImpl() ci/tmp/build/./src/IO/WriteBufferFromS3.cpp:154:9 (clickhouse+0x1d9a4ed7) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #6 DB::WriteBuffer::next() ci/tmp/build/./src/IO/WriteBuffer.h:53:13 (clickhouse+0x9cb3cdb) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #7 DB::WriteBuffer::nextIfAtEnd() ci/tmp/build/./src/IO/WriteBuffer.h:85:13 (clickhouse+0x1663f82e) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #8 DB::WriteBuffer::write(char const*, unsigned long) ci/tmp/build/./src/IO/WriteBuffer.cpp:53:9 (clickhouse+0x1663f82e)
    #9 DB::ParallelFormattingOutputFormat::collectorThreadFunction(std::__1::shared_ptr<DB::ThreadGroup> const&) ci/tmp/build/./src/Processors/Formats/Impl/ParallelFormattingOutputFormat.cpp:156:21 (clickhouse+0x26da489e) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #10 DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()::operator()() const ci/tmp/build/./src/Processors/Formats/Impl/ParallelFormattingOutputFormat.h:109:13 (clickhouse+0x26a46b64) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #11 std::__1::__invoke_result_impl<void, DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&>::type std::__1::__invoke[abi:ne210105]<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x26a46b64)
    #12 decltype(auto) std::__1::__apply_tuple_impl[abi:ne210105]<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&, std::__1::tuple<>&>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1380:5 (clickhouse+0x26a46b64)
    #13 decltype(auto) std::__1::apply[abi:ne210105]<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&, std::__1::tuple<>&>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&, std::__1::tuple<>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1384:5 (clickhouse+0x26a46b64)
    #14 ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13 (clickhouse+0x26a46b64)
    #15 std::__1::__invoke_result_impl<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()&>::type std::__1::__invoke[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87:27 (clickhouse+0x26a46a61) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #16 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342:5 (clickhouse+0x26a46a61)
    #17 DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'() std::__1::__invoke_r[abi:ne210105]<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()&>() ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348:10 (clickhouse+0x26a46a61)
    #18 void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'()>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:450:12 (clickhouse+0x26a46a61)
    #19 std::__1::__function::__policy_func<void ()>::operator()[abi:ne210105]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:508:12 (clickhouse+0x1669c0b0) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #20 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:772:10 (clickhouse+0x1669c0b0)
    #21 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:811:17 (clickhouse+0x1669c0b0)
    #22 std::__1::__invoke_result_impl<void, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>::type std::__1::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h (clickhouse+0x166a619b) (BuildId: cbe05338573794eb80b4f44283e8ca86a7a9c87b)
    #23 void std::__1::__thread_execute[abi:ne210105]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:159:3 (clickhouse+0x166a619b)
    #24 void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:168:3 (clickhouse+0x166a619b)
```

Cc @CheSema

### PR DESCRIPTION
**Pull request by CheSema**
Fix https://github.com/ClickHouse/ClickHouse/issues/93185

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/IO/WriteBufferFromS3.cpp [hunk 1]
```diff
@@ -529,7 +529,9 @@ void WriteBufferFromS3::writePart(WriteBufferFromS3::PartData && data)
         return;
     }
 
+    /// all iterators are invalidated after push_back, so we create part_tag reference after push_back
```
Comment (azat) [inline src/IO/WriteBufferFromS3.cpp]: If you are writing about iterations invalidation, worth to write about that references are not invalidated in deque as well? Since this is important to make things works here

Also, this is the only reason for using deque here over vector?

Comment (CheSema) [reply src/IO/WriteBufferFromS3.cpp]: Updated the comment.

> Also, this is the only reason for using deque here over vector?

Yes.

File: src/IO/WriteBufferFromS3.cpp [hunk 2]
```diff
@@ -529,7 +529,10 @@ void WriteBufferFromS3::writePart(WriteBufferFromS3::PartData && data)
         return;
     }
 
+    /// all iterators are invalidated after push_back,
+    // so we create part_tag reference after push_back as the reference will not be invalidated
```
Comment (azat) [inline src/IO/WriteBufferFromS3.cpp]:
```suggestion
    /// so we create part_tag reference after push_back as the reference will not be invalidated
```

**Review by azat — APPROVED** [review]
