### PR TITLE
Analyzer materialized view IN with CTE fix

### LINKED ISSUE #65598: Insert error for materialized views with multiple CTEs
**Describe what's wrong**

We recently update from CH version ClickHouse 24.4.1.2088 to ClickHouse 24.5.3.5 and figured out the inserts on source tables with attached materialized view with multiple CTEs  result in an ' Not found column' error

We expect that the insert is accepted without errer as in the pervious version.

**How to reproduce**

You can reproduce the error via:
```
 CREATE TABLE mv_test
(
    `id` UInt64,
    `ref_id` UInt64,
    `final_id` Nullable(UInt64),
    `display` String
)
ENGINE = Log;

CREATE TABLE mv_test_target
(
    `id` UInt64,
    `ref_id` UInt64,
    `final_id` Nullable(UInt64),
    `display` String
)
ENGINE = Log;

CREATE MATERIALIZED VIEW mv_test_mv TO mv_test_target
(
    `id` UInt64,
    `ref_id` UInt64,
    `final_id` Nullable(UInt64),
    `display` String
)
AS WITH
    tester AS
    (
        SELECT
            id,
            ref_id,
            final_id,
            display
        FROM mv_test
    ),
    id_set AS
    (
        SELECT
            display,
            max(id) AS max_id
        FROM mv_test
        GROUP BY display
    )
SELECT *
FROM tester
WHERE id IN (
    SELECT max_id
    FROM id_set
);

insert into mv_test ( id, ref_id, display) values ( 1, 2, 'test');
```

On my test system this results in an 
```
Code: 10. DB::Exception: Not found column __table1.max_id: in block : while pushing to view default.mv_test_mv (eb544596-a97b-4c95-89af-4d8c6fc2c77a). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.5.3.5 (official build)
```

**Does it reproduce on the most recent release?**
Tested in version ClickHouse 24.5.3.5

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Analyzer fix when query inside materialized view uses IN with CTE. Closes #65598.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 530c04413eaf2839fb3fbdef3619628916e63405 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71538/530c04413eaf2839fb3fbdef3619628916e63405/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 1]
```diff
@@ -2958,27 +2958,28 @@ ProjectionNames QueryAnalyzer::resolveFunction(QueryTreeNodePtr & node, Identifi
...
+                    if (auto * query_node = table_expression->as<QueryNode>())
+                        table_expression = extractLeftTableExpression(query_node->getJoinTree());
+                    else if (auto * union_node = table_expression->as<UnionNode>())
+                        table_expression = union_node->getQueries().getNodes().at(0);
+                    else
+                        break;
+                }
 
-                if (table_expression)
+                auto * table_expression_table_node = table_expression->as<TableNode>();
```
Comment (novikd) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:2974]: `table_expression` can be `nullptr` at this point. Let's move the check before cast.

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 2]
```diff
@@ -2958,27 +2958,28 @@ ProjectionNames QueryAnalyzer::resolveFunction(QueryTreeNodePtr & node, Identifi
...
+                if (table_expression_table_node &&
+                    table_expression_table_node->getStorageID().getFullNameNotQuoted() == storage->getStorageID().getFullNameNotQuoted())
                 {
-                    if (auto * query_table_node = table_expression->as<TableNode>())
-                    {
-                        if (query_table_node->getStorageID().getFullNameNotQuoted() == storage->getStorageID().getFullNameNotQuoted())
-                        {
-                            auto replacement_table_expression = std::make_shared<TableNode>(storage, scope.context);
-                            if (std::optional<TableExpressionModifiers> table_expression_modifiers = query_table_node->getTableExpressionModifiers())
```
Comment (novikd) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:2973]: What about table expression modifier?

Comment (kitaisreal) [reply src/Analyzer/Resolve/QueryAnalyzer.cpp:2973]: During `clone` we copy table expression modifiers. It is better to use `clone` here, because if later we will add some property to table node `clone` will handle copy of them automatically.

File: src/Analyzer/Resolve/QueryAnalyzer.cpp (hunk 1 above)
Comment (kitaisreal) [reply src/Analyzer/Resolve/QueryAnalyzer.cpp]: Updated.

**Review by novikd — APPROVED** [review]
LGTM
