### PR TITLE
Do not load inactive parts at startup

### LINKED ISSUE #4699: Speed up loading of data parts at startup.
1. Do not load inactive data parts that are old enough (they will be deleted nevertheless). But still use them if we need to repair broken part at startup. Delete old inactive data parts at startup.

2. Use multiple threads for loading data parts to mitigate latency.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not load inactive parts at startup of `MergeTree` tables.

Resolves #4699.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Most likely it won't work with transactions now. Will fix it later.

File: src/Storages/MergeTree/MergeTreeData.h [hunk 1]
```diff
@@ -1329,12 +1329,41 @@ class MergeTreeData : public IStorage, public WithMutableContext
     /// Returns default settings for storage with possible changes from global config.
     virtual std::unique_ptr<MergeTreeSettings> getDefaultSettings() const = 0;
 
+    class PartLoadingTree
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeData.h:1332]: Missing comments.

**Comment by CurtizJ** [comment]
I had to remove [test](https://github.com/ClickHouse/ClickHouse/blob/c65be55da106da0945fee621617c961fc8722ec6/tests/queries/0_stateless/02482_load_parts_parition_commands.sh) since it doesn't work well because of #37664.

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 2]
```diff
@@ -4163,6 +4356,11 @@ Pipe MergeTreeData::alterPartition(
     const PartitionCommands & commands,
     ContextPtr query_context)
 {
+    /// Wait for loading of outdated parts
+    /// because partition commands (DROP, MOVE, etc.)
+    /// must be applied to all parts on disk.
+    waitForOutdatedPartsToBeLoaded();
```
Comment (tavplubix) [inline src/Storages/MergeTree/MergeTreeData.cpp:4362]: `alterPartition()` will not be called from `execureDropRange`/`executeReplaceRange`, need to add this call there as well

Comment (tavplubix) [reply src/Storages/MergeTree/MergeTreeData.cpp:4362]: It's easy to forget to call it, so let's add `assert(outdated_data_parts_loading_finished)` to `removePartsInRangeFromWorkingSetAndGetPartsToRemoveFromZooKeeper` (it's my favorite method name, btw)

**Comment by qoega** [comment]
Sanitizer assert (in stderr.log) looks related
https://s3.amazonaws.com/clickhouse-test-reports/42181/8d2788445befc456c39cc13aac1c4250be5a014d/stress_test__msan_/stderr.log

File: src/Storages/MergeTree/MergeTreeData.h [hunk 3]
```diff
@@ -1314,6 +1315,76 @@ class MergeTreeData : public IStorage, public WithMutableContext
...
+
+        /// Traverses a tree and call @func on each node.
+        /// If recursive is false traverses only the top level.
+        template <typename Func>
+        void traverse(bool recursive, Func && func);
+
+    private:
+        /// NOTE: Parts should be added in descending order of their levels
+        /// because rearranging tree to the new root is not supported.
+        void add(const MergeTreePartInfo & info, const String & name, const DiskPtr & disk);
```
[the remark this answers is not in the document]
Comment (CurtizJ) [reply src/Storages/MergeTree/MergeTreeData.h:1390]: To do it we need to save previous added node. I'm not sure whether it's worth it, because `add` is private method, which is used only in `build` which sorts nodes.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests (tsan) [2/6] failure **is related**, see https://github.com/ClickHouse/ClickHouse/issues/44929#issuecomment-1380945885

**Comment by CurtizJ** [comment]
All checks are green.
