### PR TITLE
fix lowcardinality on group by of any model

### LINKED ISSUE #34500: group by column(LowCardinality) crash in 'any' model
version:  v21.8.14.5-lts
reproduce:
```
create database if not exists d_group_by_lowcardinality;

drop table if exists d_group_by_lowcardinality.t_group_by_lowcardinality;
create table if not exists d_group_by_lowcardinality.t_group_by_lowcardinality(p_date Date, val LowCardinality(Nullable(String)))
engine=MergeTree() partition by p_date order by tuple();

insert into d_group_by_lowcardinality.t_group_by_lowcardinality select today() as p_date, toString(number/5) as val from numbers(10000);
insert into d_group_by_lowcardinality.t_group_by_lowcardinality select today() as p_date, Null as val from numbers(100);

select val, avg(toUInt32(val)) from d_group_by_lowcardinality.t_group_by_lowcardinality group by val limit 10 settings max_threads=1, max_rows_to_group_by=100, group_by_overflow_mode='any' format Null;

drop table if exists d_group_by_lowcardinality.t_group_by_lowcardinality;
drop database if exists d_group_by_lowcardinality;
```
some crash log:
```
[9c30c96270b6] 2022.02.10 12:22:42.421080 [ 25499 ] <Fatal> BaseDaemon: ########################################                                                                               
[9c30c96270b6] 2022.02.10 12:22:42.438473 [ 25499 ] <Fatal> BaseDaemon: (version 22.1.3.1, build id: AE4FF1FC8784CB9E7B68B8204E52B52566D6D843) (from thread 24614) (query_id: 1bb2c351-2c14-4066-ba2d-7eafea07859e)Received signal Aborted (6)
[9c30c96270b6] 2022.02.10 12:22:42.438767 [ 25499 ] <Fatal> BaseDaemon:                                                                                                                               [9c30c96270b6] 2022.02.10 12:22:42.439062 [ 25499 ] <Fatal> BaseDaemon: Stack trace: 0x7f89584d1d22 0x7f89584bb862 0x7f89584bb747 0x7f89584ca616 0x7f895475c1bf 0x7f89394b6354 0x7f89395b503f 0x7f89394387cb 0x7f89393e3ff1 0x7f89328b8a9d 0x7f89328b6a69 0x7f893332e326 0x7f893332e202 0x7f8933335d55 0x7f8933336064 0x7f89333350ec 0x7f89333345a5 0x7f893334b5b0 0x7f893334b4ad 0x7f893334b41d 0x7f893334b3c1 0x7f893334b2d2 0x7f893334b172 0x7f893334affd 0x7f893334afbd 0x7f893334af95 0x7f893334af60 0x7f895ae73166 0x7f895ae68e15 0x7f895ae68766 0x7f895ae6fcd1 0x7f895ae6fc3d 0x7f895ae6fb65 0x7f895ae6f42f 0x7f8958837259 0x7f89585935e3                                                                                                                                                                        [9c30c96270b6] 2022.02.10 12:22:44.074333 [ 25499 ] <Fatal> BaseDaemon: 4. gsignal @ 0x92c6d22 in /root/freedomDR/ClickHouse/build_debug/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so
[9c30c96270b6] 2022.02.10 12:22:44.299749 [ 25499 ] <Fatal> BaseDaemon: 5. abort @ 0x92b0862 in /root/freedomDR/ClickHouse/build_debug/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so  
[9c30c96270b6] 2022.02.10 12:22:44.522865 [ 25499 ] <Fatal> BaseDaemon: 6. ? @ 0x92b0747 in /root/freedomDR/ClickHouse/build_debug/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so      
[9c30c96270b6] 2022.02.10 12:22:44.748240 [ 25499 ] <Fatal> BaseDaemon: 7. ? @ 0x92bf616 in /root/freedomDR/ClickHouse/build_debug/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so      
[9c30c96270b6] 2022.02.10 12:22:45.050277 [ 25499 ] <Fatal> BaseDaemon: 8. ./build_debug/./base/base/../base/StringRef.h:39: StringRef::StringRef<char8_t, void>(char8_t const*, unsigned long) @ 0x55511bf in /root/freedomDR/ClickHouse/build_debug/src/AggregateFunctions/libclickhouse_aggregate_functionsd.so                                                                                       
[9c30c96270b6] 2022.02.10 12:22:46.244445 [ 25499 ] <Fatal> BaseDaemon: 9. ./build_debug/./src/Common/ColumnsHashing.h:94: DB::ColumnsHashing::HashMethodString<PairNoInit<StringRef, char*>, char*, true, true, false>::getKeyHolder(long, DB::Arena&) const @ 0x190b354 in /root/freedomDR/ClickHouse/build_debug/src/libclickhouse_interpretersd.so                                                      
[9c30c96270b6] 2022.02.10 12:22:46.740614 [ 25499 ] <Fatal> BaseDaemon: 10.1. inlined from ./build_debug/./src/Common/ColumnsHashingImpl.h:164: DB::ColumnsHashing::columns_hashing_impl::FindResultImpl<char*, false> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodString<PairNoInit<StringRef, char*>, char*, true, true, false>, PairNoInit<StringRef, char*>, char*, true, false>::findKey<DB::AggregationDataWithNullKey<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, HashTableGrower<8ul>, Allocator<true, true> > > >(DB::AggregationDataWithNullKey<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, HashTableGrower<8ul>, Allocator<true, true> > >&, unsigned long, DB::Arena&)
```
It is like call getKeyHolder crash (should use HashMethodSingleLowCardinalityColumn::getKeyHolder ). I can't fix it. Does anyone have ideas?

### PR DESCRIPTION
**Pull request by freedomDR**
Changelog category (leave one):
- Bug Fix 

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
add HashMethodSingleLowCardinalityColumn::findKey, avoid crash.

Fixes #34500

### CODE REVIEW

**Comment by kitaisreal** [comment]
@Mergifyio update

**Comment by freedomDR** [comment]
emmmm， I visit some fail task. message is 'table is not exists', how can I  fix it?

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
+create database if not exists d_group_by_lowcardinality;
```
Comment (azat) [inline tests/queries/0_stateless/02180_group_by_lowcardinality.sql:1]: >emmmm， I visit some fail task. message is 'table is not exists', how can I fix it?

The problem is that the test is running in parallel and some of runs may remove table in parallel.

You can fix this by simply removing creating database (and using qualified db.table names in the tests), since each test already have it's own random database.

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+drop table if exists d_group_by_lowcardinality.t_group_by_lowcardinality;
+create table if not exists d_group_by_lowcardinality.t_group_by_lowcardinality(p_date Date, val LowCardinality(Nullable(String))) 
+engine=MergeTree() partition by p_date order by tuple();
+
+insert into d_group_by_lowcardinality.t_group_by_lowcardinality select today() as p_date, toString(number/5) as val from numbers(10000);
+insert into d_group_by_lowcardinality.t_group_by_lowcardinality select today() as p_date, Null as val from numbers(100);
+
+select val, avg(toUInt32(val)) from d_group_by_lowcardinality.t_group_by_lowcardinality group by val limit 10 settings max_threads=1, max_rows_to_group_by=100, group_by_overflow_mode='any' format Null;
```
Comment (azat) [inline tests/queries/0_stateless/02180_group_by_lowcardinality.sql:10]: Maybe it worth checking the result?

**Comment by azat** [comment]
>add HashMethodSingleLowCardinalityColumn::findKey, avoid crash.

This changelog entry is not very easy to understand for regular user, maybe something like this will be better?

>Avoid crash in case of `GROUP BY` `LowCardinality` column and `group_by_overflow_mode='any'`

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql (hunk 1 above)
Comment (freedomDR) [reply tests/queries/0_stateless/02180_group_by_lowcardinality.sql:1]: ok. I try to do it.

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql (hunk 2 above)
Comment (freedomDR) [reply tests/queries/0_stateless/02180_group_by_lowcardinality.sql:10]: image
The result is possible different in tests.

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql (hunk 1 above)
Comment (azat) [reply tests/queries/0_stateless/02180_group_by_lowcardinality.sql]: You forgot to remove qualified table names, i.e .`s/d_group_by_lowcardinality.t_group_by_lowcardinality/t_group_by_lowcardinality`

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql (hunk 2 above)
Comment (azat) [reply tests/queries/0_stateless/02180_group_by_lowcardinality.sql:7]: It should be consistent in this case (`max_threads=1` should be enough to make it consistent)

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql (hunk 1 above)
Comment (freedomDR) [reply tests/queries/0_stateless/02180_group_by_lowcardinality.sql]: .... ok.

File: tests/queries/0_stateless/02180_group_by_lowcardinality.sql (hunk 2 above)
Comment (freedomDR) [reply tests/queries/0_stateless/02180_group_by_lowcardinality.sql:7]: got it. thanks

**Comment by freedomDR** [comment]
if I should ignore failed tests?

**Comment by azat** [comment]
>if I should ignore failed tests?

Test failures looks unrelated to your changes, now you need to wait until @kitaisreal (or someone who can accept this change) will take a look

**Comment by alexey-milovidov** [comment]
See #34550 and #34492.

File: src/Common/ColumnsHashing.h [hunk 3]
```diff
@@ -378,6 +378,22 @@ struct HashMethodSingleLowCardinalityColumn : public SingleColumnMethod
             return EmplaceResult(inserted);
     }
 
+    template <typename Data>
+    ALWAYS_INLINE FindResult findKey(Data & data, size_t row_, Arena & pool)
```
Comment (kitaisreal) [inline src/Common/ColumnsHashing.h:382]: This implementation does not use `saved_hash`, and `visit_cache`, actually below there is right method `findFromRow`, but probably functions signatures were changed and now it is not used.
In FindResult offsets where added here https://github.com/ClickHouse/ClickHouse/pull/20079/files, and `findFromRow` seems a bit outdated, we need to rename method to `findKey` and then fix compile time issues.
I am not sure that I get it right:
```c++
template <typename Data>
    ALWAYS_INLINE FindResult findKey(Data & data, size_t row_, Arena & pool)
    {
        size_t row = getIndexAt(row_);

        if (is_nullable && row == 0)
        {
            if constexpr (has_mapped)
                return FindResult(data.hasNullKeyData() ? &data.getNullKeyData() : nullptr, data.hasNullKeyData(), 0);
            else
                return FindResult(data.hasNullKeyData(), 0);
        }

        if (visit_cache[row] != VisitValue::Empty)
        {
            if constexpr (has_mapped)
                return FindResult(&mapped_cache[row], visit_cache[row] == VisitValue::Found, 0);
            else
                return FindResult(visit_cache[row] == VisitValue::Found, 0);
        }

        auto key_holder = getKeyHolder(row_, pool);

        typename Data::LookupResult it;

        if (saved_hash)
            it = data.find(keyHolderGetKey(key_holder), saved_hash[row]);
        else
            it = data.find(keyHolderGetKey(key_holder));

        bool found = it;
        visit_cache[row] = found ? VisitValue::Found : VisitValue::NotFound;

        if constexpr (has_mapped)
        {
            if (found)
                mapped_cache[row] = it->getMapped();
        }

        size_t offset = 0;

        if constexpr (FindResult::has_offset)
            offset = found ? data.offsetInternal(it) : 0;

        if constexpr (has_mapped)
            return FindResult(&mapped_cache[row], found, offset);
        else
            return FindResult(found, offset);
    }
```

**Review by kitaisreal — CHANGES_REQUESTED** [review]

**Review by kitaisreal — APPROVED** [review]
Need to wait for style check and then merge.
