### PR TITLE
Safe logic for incorrect MergeTreeSettings

### LINKED ISSUE #10897: The user may accidentially set background pool size lower than `number_of_free_entries_in_pool_to_execute_mutation` and it will prevent ALTERs to process.
Hello,

I upgrade to Clickhouse c811e1f0d0c439b74843770082569aa7fd5f9743 (master 2 days ago) and I'm facing lot of problems (https://github.com/ClickHouse/ClickHouse/issues/10892) .

For example:

```bash
CREATE DATABASE tb1
CREATE TABLE tb1.collection_ops_SUITE(`string` Nullable(String),`int` Nullable(Int64),`timestamp` DateTime,`created_at` DateTime) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY (timestamp)
INSERT INTO tb1.collection_ops_SUITE(`created_at`,`timestamp`,`int`,`string`) VALUES (1589395126,1589395126,1,'str'),(1589395126,1589395126,2,'str')
ALTER TABLE tb1.collection_ops_SUITE DROP COLUMN `int`
```

Running following queries with HTTP client or tabbix will hang forever in the ALTER table.

In logs I see:

```
2020.05.13 18:44:13.557064 [ 2579621 ] {00000000-0000-4000-8000-000000000000} <Information> tb1.collection_ops_SUITE: Added mutation: mutation_2.txt
2020.05.13 18:44:13.557266 [ 2579621 ] {00000000-0000-4000-8000-000000000000} <Information> tb1.collection_ops_SUITE: Waiting mutation: mutation_2.txt
```

Then nothing more

Silviu

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Protect from the cases when user may set `background_pool_size` to value lower than `number_of_free_entries_in_pool_to_execute_mutation` or `number_of_free_entries_in_pool_to_lower_max_size_of_merge`. In these cases ALTERs won't work or the maximum size of merge will be too limited. Saturate values instead. This closes #10897.

Draft because there is a chance to add integration test.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp [hunk 1]
```diff
@@ -195,7 +199,8 @@ UInt64 MergeTreeDataMergerMutator::getMaxSourcePartSizeForMutation()
     UInt64 disk_space = data.getStoragePolicy()->getMaxUnreservedFreeSpace();
 
     /// Allow mutations only if there are enough threads, leave free threads for merges else
-    if (background_pool_size - busy_threads_in_pool >= data_settings->number_of_free_entries_in_pool_to_execute_mutation)
+    if (busy_threads_in_pool <= 1
```
Comment (nikitamikhaylov) [inline src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:202]: What will be in case if `background_pool_size` is too lower than `number_of_free_entries_in_pool_to_execute_mutation`? I think that we will execute mutation with a few threads in pool (and we will use the **whole** pool), so it will be processed significantly slower that usually and we won't be able to execute any merges or other mutations for a period of time. If there are many inserts, it will  lead to `too many parts` error maybe.

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:202]: I'll merge this because it makes things better...

Comment (alexey-milovidov) [reply src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:202]: @nikitamikhaylov #13153
