### PR TITLE
Stricter checks when attaching/detaching threads to groups

### LINKED ISSUE #59114: Segmentation fault in ProfileEvents::getProfileEvents
A segmentation fault in `ProfileEvents::getProfileEvents` was found in https://s3.amazonaws.com/clickhouse-test-reports/59041/0aa6164294c9b9ff0906c049a67059c7aef3c111/stateless_tests__msan__%5B1_6%5D.html

```
2024.01.22 04:30:17.290140 [ 730 ] {} <Trace> BaseDaemon: Received signal 11
2024.01.22 04:30:17.360166 [ 10144 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.01.22 04:30:17.505345 [ 10144 ] {} <Fatal> BaseDaemon: (version 24.1.1.1 (official build), build id: ED7CD1DBDE83A5B63B5B11AB0FDB6CFA92422554, git hash: 6f3124acdb3c8fc02a02ef242abc34b463f284fe) (from thread 2667) Received signal 11
2024.01.22 04:30:17.536995 [ 10144 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.01.22 04:30:17.543632 [ 10144 ] {} <Fatal> BaseDaemon: Address: 0x68. Access: read. Address not mapped to object.
2024.01.22 04:30:17.545715 [ 10144 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000561412c5e2fe 0x00005614170d1bec 0x00005614170bd370 0x000056141709aa3f 0x00005614170ebddc 0x000056141b365e20 0x000056141b366c82 0x000056141b7ead66 0x000056141b7e7b2e 0x000056141b7e4a12 0x00007f9a463b9ac3 0x00007f9a4644a814
2024.01.22 04:30:17.548279 [ 10144 ] {} <Fatal> BaseDaemon: ########################################
2024.01.22 04:30:17.548439 [ 10144 ] {} <Fatal> BaseDaemon: (version 24.1.1.1 (official build), build id: ED7CD1DBDE83A5B63B5B11AB0FDB6CFA92422554, git hash: 6f3124acdb3c8fc02a02ef242abc34b463f284fe) (from thread 2667) (no query) Received signal Segmentation fault (11)
2024.01.22 04:30:17.548576 [ 10144 ] {} <Fatal> BaseDaemon: Address: 0x68. Access: read. Address not mapped to object.
2024.01.22 04:30:17.549923 [ 10144 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000561412c5e2fe 0x00005614170d1bec 0x00005614170bd370 0x000056141709aa3f 0x00005614170ebddc 0x000056141b365e20 0x000056141b366c82 0x000056141b7ead66 0x000056141b7e7b2e 0x000056141b7e4a12 0x00007f9a463b9ac3 0x00007f9a4644a814
2024.01.22 04:30:18.255842 [ 10144 ] {} <Fatal> BaseDaemon: 4.0. inlined from ./contrib/llvm-project/libcxx/include/atomic:958: long std::__cxx_atomic_load[abi:v15000]<long>(std::__cxx_atomic_base_impl<long> const*, std::memory_order)
2024.01.22 04:30:18.255996 [ 10144 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./contrib/llvm-project/libcxx/include/atomic:1588: std::__atomic_base<long, false>::load[abi:v15000](std::memory_order) const
2024.01.22 04:30:18.256068 [ 10144 ] {} <Fatal> BaseDaemon: 4.2. inlined from ./src/Common/MemoryTracker.h:122: MemoryTracker::get() const
2024.01.22 04:30:18.256172 [ 10144 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Interpreters/ProfileEventsExt.cpp:130: ProfileEvents::getProfileEvents(String const&, std::shared_ptr<ConcurrentBoundedQueue<DB::Block>>, DB::Block&, std::unordered_map<unsigned long, ProfileEvents::Counters::Snapshot, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, ProfileEvents::Counters::Snapshot>>>&) @ 0x00000000378152fe in /usr/bin/clickhouse
2024.01.22 04:30:19.914138 [ 10144 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::sendProfileEvents() @ 0x000000003bc88bec in /usr/bin/clickhouse
2024.01.22 04:30:21.079919 [ 10144 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::processOrdinaryQueryWithProcessors() @ 0x000000003bc74370 in /usr/bin/clickhouse
2024.01.22 04:30:21.991421 [ 10144 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x000000003bc51a3f in /usr/bin/clickhouse
2024.01.22 04:30:23.490417 [ 10144 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Server/TCPHandler.cpp:2298: DB::TCPHandler::run() @ 0x000000003bca2ddc in /usr/bin/clickhouse
2024.01.22 04:30:23.540259 [ 10144 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x000000003ff1ce20 in /usr/bin/clickhouse
2024.01.22 04:30:23.622804 [ 10144 ] {} <Fatal> BaseDaemon: 10.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2024.01.22 04:30:23.622873 [ 10144 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2024.01.22 04:30:23.622918 [ 10144 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x000000003ff1dc82 in /usr/bin/clickhouse
2024.01.22 04:30:23.714626 [ 10144 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x00000000403a1d66 in /usr/bin/clickhouse
2024.01.22 04:30:23.808973 [ 10144 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000004039eb2e in /usr/bin/clickhouse
2024.01.22 04:30:23.890526 [ 10144 ] {} <Fatal> BaseDaemon: 13. ./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000004039ba12 in /usr/bin/clickhouse
2024.01.22 04:30:23.890573 [ 10144 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f9a463b9ac3
2024.01.22 04:30:23.890601 [ 10144 ] {} <Fatal> BaseDaemon: 15. ? @ 0x00007f9a4644a814
```

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/59114

In https://s3.amazonaws.com/clickhouse-test-reports/74014/dcdccd54f13e74c5018f6d40e5a4caa77858dc22/stress_test__debug_.html `CurrentThread::getGroup()` returned nullptr when called from `TCPHandler::processOrdinaryQuery`. This means that calls to `CurrentThread::attachToGroup`/`detachFromGroupIfNotDetached` are not properly nested: someone detached a thread that they didn't attach. (The thread is expected to be attached to a group because the caller of `processOrdinaryQuery` holds a QueryScope for the duration of the call.)

Almost all calls to `CurrentThread::attachToGroupIfDetached`/`detachFromGroupIfNotDetached` follow this pattern that looks incorrect:
```
    auto thread_func = [thread_group = CurrentThread::getGroup()]
    {
        SCOPE_EXIT_SAFE(
            if (thread_group)
                CurrentThread::detachFromGroupIfNotDetached();
        );

        if (thread_group)
            CurrentThread::attachToGroupIfDetached(thread_group);

        ...
    };
```
If the thread is already attached to a group, it'll end up detached after this function returns. Normally such `thread_func` is immediately scheduled on a thread pool; then the thread shouldn't be already attached to a group (... or so I'm assuming; there were no asserts about this, so CI on this PR may prove this analysis wrong). But some code sites sometimes call such function directly, e.g. `Aggregator::prepareBlocksAndFillTwoLevelImpl`. AFAICT, this would incorrectly detach the thread from the thread group. I'm guessing this is what caused these test failures (but I didn't try to reproduce this and don't have an explanation for why the crash happens so rarely.)

This PR replaces this pattern with a more correct one, with a bunch of asserts, wrapped in a RAII thing.

Most changes are mechanical. Most substantial ones are in `ThreadStatus.h`, `ThreadStatusExt.cpp`, and `ProfileEventsExt.cpp`.

### CODE REVIEW

**Review by antonio2368 — APPROVED** [review]

**Comment by al13n321** [comment]
(The new checks fail in CI, investigating.)

File: src/Interpreters/ThreadStatusExt.cpp [hunk 1]
```diff
@@ -170,22 +170,74 @@ void ThreadGroup::attachInternalProfileEventsQueue(const InternalProfileEventsQu
...
+    {
+        /// Unexpected. For caller's convenience avoid throwing exceptions.
+        DB::tryLogCurrentException(__PRETTY_FUNCTION__);
+        thread_group = nullptr;
+        prev_thread_group = nullptr;
+    }
 }
 
-ThreadGroupSwitcher::~ThreadGroupSwitcher()
+ThreadGroupSwitcher::~ThreadGroupSwitcher() noexcept
```
Comment (azat) [inline src/Interpreters/ThreadStatusExt.cpp:214]: Destructors are `noexcept` by default (AFAIR since C++11)

**Review by azat — APPROVED** [review]
LGTM

But, AFAICS it should not affect incorrect tracking of **total** memory tracker?

File: src/Interpreters/ThreadStatusExt.cpp (hunk 1 above)
Comment (azat) [inline src/Interpreters/ThreadStatusExt.cpp:214]:
```suggestion
ThreadGroupSwitcher::~ThreadGroupSwitcher()
```

File: src/Common/ThreadStatus.h [hunk 2]
```diff
@@ -141,17 +141,31 @@ class ThreadGroup
...
-    explicit ThreadGroupSwitcher(ThreadGroupPtr thread_group);
-    ~ThreadGroupSwitcher();
+    /// If thread_group_ is nullptr or equal to current thread group, does nothing.
+    /// allow_existing_group:
+    ///  * If false, asserts that the thread is not already attached to a different group.
+    ///    Use this when running a task in a thread pool.
+    ///  * If true, remembers the current group and restores it in destructor.
+    /// If thread_name is not empty, calls setThreadName along the way; should be at most 15 bytes long.
+    explicit ThreadGroupSwitcher(ThreadGroupPtr thread_group_, const char * thread_name, bool allow_existing_group = false) noexcept;
+    ~ThreadGroupSwitcher() noexcept;
```
Comment (azat) [inline src/Common/ThreadStatus.h:163]:
```suggestion
    ~ThreadGroupSwitcher();
```

**Comment by azat** [comment]
>but at least one leaky instance didn't use polygon dictionary (if I checked correctly), so it can't be the whole story.

I mean that even if the `current_thread` was wrong, it should fallback to `total_memory_tracker` and account **total** memory correctly

**Comment by al13n321** [comment]
Ah, you're right, I didn't notice the fallback in `getMemoryTracker()`, so this is fully unrelated to the memory tracking problem we're seeing.

**Comment by al13n321** [comment]
Flaky tests: https://github.com/ClickHouse/ClickHouse/issues/75961 , https://github.com/ClickHouse/ClickHouse/issues/74703 , https://github.com/ClickHouse/ClickHouse/issues/75520
