### PR TITLE
Fix mistake in greatCircleAngle

### LINKED ISSUE #19769: greatCircleAngle is very inaccurate
**Describe the bug**
`greatCircleAngle` function is very inaccurate for some arguments. Examples:

```
┌─greatCircleAngle(0, 45, 0.1, 45.1)─┐
│                         0.13063148 │
└────────────────────────────────────┘
But must be 0.1224388

┌─greatCircleAngle(0, 45, 1, 45)─┐
│                      0.8408964 │
└────────────────────────────────┘
Must be 0.7071023

┌─greatCircleAngle(0, 45, 1, 45.1)─┐
│                       0.84645635 │
└──────────────────────────────────┘
Must be 0.7135268
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The function `greatCircleAngle` returned inaccurate results in previous versions. This closes #19769.

### CODE REVIEW

File: src/Functions/greatCircleDistance.cpp [hunk 1]
```diff
@@ -95,7 +95,7 @@ void geodistInit()
 
         sphere_metric_meters_lut[i] = static_cast<float>(sqr((EARTH_DIAMETER * PI / 360) * cos(latitude)));
 
-        sphere_metric_lut[i] = cosf(latitude);
+        sphere_metric_lut[i] = sqr(cosf(latitude));
```
Comment (hombit) [inline src/Functions/greatCircleDistance.cpp:98]: Should it be `sqrf`?

Comment (alexey-milovidov) [reply src/Functions/greatCircleDistance.cpp]: Ok.

**Comment by hombit** [comment]
Thank you, looks good for me!
