### PR TITLE
Fix memory leak while pushing to MVs w/o query context (from Kafka/...)

### LINKED ISSUE #36367: When I use Kafka table: there might be a memory leak after upgrading to version 22.3.3
We use clickhosue version 21.12.2.17 before.It works well

But we found that after upgrade to 22.3.3, the memory of clickhouse used grow up daily .

I don't know if this is a memory overflow

here is the promethues metric 'ClickHouseMetrics_MemoryTracking'  duration last 15days

image

and I restarted cknode1 at 4.14 ,you can see it come down and rising again.

And here is some sql and result I have run for diagnosis。

image

image

image

image

we use dict and MaterializedView . no living view.

we have tried  'system drop mark cache '  and change 'max_bytes_before_external_group_by' to '6g'.Not work

Is there anyting else  I can do?

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix memory leak while pushing to MVs w/o query context (from Kafka/...)

Patchset description:
- Avoid leaking of ThreadGroupStatus::finished_threads_counters_memory
- WriteBufferFromS3: remove unused ThreadGroupStatus
- Avoid using of ThreadGroupStatus of the MainThreadStatus
- Fix possible missing detachQuery() in case of exception in readers
- Fix memory leak while pushing to MVs w/o query context (from Kafka/...)

*You will find more details in the commit descriptions*

This is the [pdf](https://github.com/ClickHouse/ClickHouse/files/9440552/profile2.focus.pdf) jemalloc report before this patch series, for the 500MVs case, with this patches the memory usage does not goes beyond ~750MiB.

Fixes: #36367 (cc @kitaisreal @den-crane @lichenglin @yakov-olkhovskiy )

### CODE REVIEW

**Comment by azat** [comment]
>skip mergeable check

To ignore style check, due to #40733

File: src/Disks/IO/ThreadPoolReader.cpp [hunk 1]
```diff
@@ -200,9 +200,9 @@ std::future<IAsynchronousReader::Result> ThreadPoolReader::submit(Request reques
 
     ProfileEvents::increment(ProfileEvents::ThreadPoolReaderPageCacheMiss);
 
-    ThreadGroupStatusPtr running_group = CurrentThread::isInitialized() && CurrentThread::get().getThreadGroup()
-            ? CurrentThread::get().getThreadGroup()
-            : MainThreadStatus::getInstance().getThreadGroup();
+    ThreadGroupStatusPtr running_group;
+    if (CurrentThread::isInitialized() && CurrentThread::get().getThreadGroup())
```
Comment (kitaisreal) [inline src/Disks/IO/ThreadPoolReader.cpp:204]: I am not familiar with this place. Why do not we use deleter below ?
```
if (query_context)
    thread_status.attachQueryContext(query_context);
if (running_group)
    thread_status.attachQuery(running_group);
```
If exception will be thrown somewhere between attach and detach will we leak something ?
```
if (running_group)
    thread_status.detachQuery();
```

File: src/Disks/IO/ThreadPoolRemoteFSReader.cpp [hunk 2]
```diff
@@ -40,9 +40,9 @@ ThreadPoolRemoteFSReader::ThreadPoolRemoteFSReader(size_t pool_size, size_t queu
 
 std::future<IAsynchronousReader::Result> ThreadPoolRemoteFSReader::submit(Request request)
 {
-    ThreadGroupStatusPtr running_group = CurrentThread::isInitialized() && CurrentThread::get().getThreadGroup()
-            ? CurrentThread::get().getThreadGroup()
-            : MainThreadStatus::getInstance().getThreadGroup();
+    ThreadGroupStatusPtr running_group;
+    if (CurrentThread::isInitialized() && CurrentThread::get().getThreadGroup())
```
Comment (kitaisreal) [inline src/Disks/IO/ThreadPoolRemoteFSReader.cpp:44]: Same question as above.

File: src/Interpreters/ThreadStatusExt.cpp [hunk 3]
```diff
@@ -406,6 +406,11 @@ void ThreadStatus::detachQuery(bool exit_if_already_detached, bool thread_exits)
     query_context.reset();
     thread_trace_context.trace_id = 0;
     thread_trace_context.span_id = 0;
+
+    /// Avoid leaking of ThreadGroupStatus::finished_threads_counters_memory
+    /// (this is in case someone uses system thread but did not call getProfileEventsCountersAndMemoryForThreads())
+    thread_group->getProfileEventsCountersAndMemoryForThreads();
```
Comment (kitaisreal) [inline src/Interpreters/ThreadStatusExt.cpp:412]: Need to rename `getProfileEventsCountersAndMemoryForThreads` in something like `getProfileEventsCountersAndMemoryForThreads`, because it is unexpected that get method will cleanup something.

File: src/Processors/Transforms/buildPushingToViewsChain.cpp [hunk 4]
```diff
@@ -238,29 +238,30 @@ Chain buildPushingToViewsChain(
...
+        auto * original_thread = current_thread;
+        SCOPE_EXIT({ current_thread = original_thread; });
+
+        std::unique_ptr<ThreadStatus> view_thread_status_ptr = std::make_unique<ThreadStatus>();
+        /// Disable query profiler for this ThreadStatus since the running (main query) thread should already have one
+        /// If we didn't disable it, then we could end up with N + 1 (N = number of dependencies) profilers which means
+        /// N times more interruptions
+        view_thread_status_ptr->disableProfiling();
+        /// view_thread_status_ptr will be moved later (on and on), so need to capture raw pointer.
+        view_thread_status_ptr->deleter = [thread_status = view_thread_status_ptr.get(), running_group]
```
Comment (kitaisreal) [inline src/Processors/Transforms/buildPushingToViewsChain.cpp:260]: Great catch. Why do we not always detachQuery in destructor ? It seems like here, we catch raw pointer to ourselves and use detach manually.

**Review by kitaisreal — CHANGES_REQUESTED** [review]
Changes looks good. Need to clarify some questions.

File: src/Disks/IO/ThreadPoolReader.cpp (hunk 1 above)
Comment (azat) [reply src/Disks/IO/ThreadPoolReader.cpp:204]: >If exception will be thrown somewhere between attach and detach will we leak something ?

You are right.

>I am not familiar with this place. Why do not we use deleter below ?

I will use `SCOPE_EXIT` here instead.

*`deleter` is not a common thing to use in a code base, however it is required in `buildPushingToViewsChain()` because it should capture some pointers*

File: src/Processors/Transforms/buildPushingToViewsChain.cpp (hunk 4 above)
Comment (azat) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:260]: >Great catch. Why do we not always detachQuery in destructor ? It seems like here, we catch raw pointer to ourselves and use detach manually.

Usually we do, see `CurrentThread::initializeQuery` and friends, however this place uses pretty low level code (for ClickHouse source base).

I will take a look later on all of this, and maybe will come up with some more safe and generic approach.
But for now it is better to keep this patch small, to make it easy to backport.

File: src/Interpreters/ThreadStatusExt.cpp (hunk 3 above)
Comment (azat) [reply src/Interpreters/ThreadStatusExt.cpp:412]: Egh, seems that you made a typo here, I will rename it to `resetProfileEventsCountersAndMemoryForThreads`

P.S. Usually I'm trying to keep bug fixes patches as small as possible to avoid possible conflicts during backporting.

**Review by kitaisreal — APPROVED** [review]
Good explanations. Lets not rename any methods, only fix leaks and backport it.
We can rename methods in separate pull request.

**Comment by azat** [comment]
>Lets not rename any methods, only fix leaks and backport it

Great.

Rebased (reorganize patches to separate them more logically) and updated the pull request description (remove some details that regular user do not need, and left this details in the commit descriptions for careful reader).

**Review by kitaisreal — APPROVED** [review]

**Comment by kitaisreal** [comment]
Test failures are unrelated.

**Comment by Algunenano** [comment]
I see that the 22.3 backport PR is still open (https://github.com/ClickHouse/ClickHouse/pull/40901) but while the backport to 22.8, 22.7 and 22.6 is done already. Is there something missing we can help with to get it to that LTS too?

**Comment by kitaisreal** [comment]
@Algunenano there is issues with crash in tests that is related to changes. ThreadPoolRemoteFSReader submit crash https://s3.amazonaws.com/clickhouse-test-reports/40901/8b70f9c77412a25bd597a816a420df7025a352d1/stateful_tests__debug__actions_.html.

**Comment by kitaisreal** [comment]
@Algunenano it seems that it was typo, lets wait builds and merge.
