### PR TITLE
Trivial optimization: do not rewrite count(if()) to countIf if CAST is required

### LINKED ISSUE #78564: `count(if(cond, expr, null))` is slower after applying RewriteAggregateFunctionWithIfPass
### Company or project name

BIGO

### Describe the situation

``` sql 
set optimize_rewrite_aggregate_function_with_if = false;
select count(if(rand() % 2 = 0, 1, null)) from numbers(1000000000); 
1 row in set. Elapsed: 1.560 sec. Processed 1.00 billion rows, 8.00 GB (640.82 million rows/s., 5.13 GB/s.)
1 row in set. Elapsed: 1.576 sec. Processed 1.00 billion rows, 8.00 GB (634.34 million rows/s., 5.07 GB/s.)
1 row in set. Elapsed: 1.559 sec. Processed 1.00 billion rows, 8.00 GB (641.51 million rows/s., 5.13 GB/s.)

set optimize_rewrite_aggregate_function_with_if = true;
select count(if(rand() % 2 = 0, 1, null)) from numbers(1000000000); 
1 row in set. Elapsed: 1.685 sec. Processed 1.00 billion rows, 8.00 GB (593.52 million rows/s., 4.75 GB/s.)
1 row in set. Elapsed: 1.614 sec. Processed 1.00 billion rows, 8.00 GB (619.58 million rows/s., 4.96 GB/s.)
1 row in set. Elapsed: 1.553 sec. Processed 1.00 billion rows, 8.00 GB (643.88 million rows/s., 5.15 GB/s.)

select countIf(rand() % 2 = 0) from numbers(1000000000);
1 row in set. Elapsed: 1.299 sec. Processed 1.00 billion rows, 8.00 GB (770.02 million rows/s., 6.16 GB/s.)
1 row in set. Elapsed: 1.332 sec. Processed 1.00 billion rows, 8.00 GB (750.76 million rows/s., 6.01 GB/s.)
1 row in set. Elapsed: 1.385 sec. Processed 1.00 billion rows, 8.00 GB (722.02 million rows/s., 5.78 GB/s.)
``` 

For other aggregate functions, refer to https://github.com/apache/incubator-gluten/issues/9176#issue-2959319657

### How to reproduce

no

### Expected performance

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Trivial optimization: do not rewrite count(if()) to countIf if CAST is required. Close  https://github.com/ClickHouse/ClickHouse/issues/78564

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Analyzer/Passes/RewriteAggregateFunctionWithIfPass.cpp [hunk 1]
```diff
@@ -74,7 +74,13 @@ class RewriteAggregateFunctionWithIfVisitor : public InDepthQueryTreeVisitorWith
 
                 /// We need to preserve the output type from if()
                 if (if_arguments_nodes[1]->getResultType()->getName() != if_node->getResultType()->getName())
+                {
+                    /// For count, adding an extra cast is too heavy for the benefit.
```
Comment (Algunenano) [inline src/Analyzer/Passes/RewriteAggregateFunctionWithIfPass.cpp:78]: Can't we just not add the cast? The return type of count() is the same either way, right?

Comment (taiyang-li) [reply src/Analyzer/Passes/RewriteAggregateFunctionWithIfPass.cpp:78]: Good idea! It doesn't change return type of count() whether cast is added or not.

**Comment by Algunenano** [comment]
* CH Inc sync: Already reported
* Perf: Around 10% improvement.
* Integration tests (aarch64, 2/4): https://github.com/ClickHouse/ClickHouse/issues/71049
* Stateless tests (msan, 3/4): https://github.com/ClickHouse/ClickHouse/issues/66116
* AST fuzzer (amd_ubsan): https://github.com/ClickHouse/ClickHouse/issues/78907
