### PR TITLE
Fix progress stats for async insert queries

### LINKED ISSUE #99758: Statistics for insert not recorded since 26.2
### Company or project name

_No response_

### Describe what's wrong

Hi,
since 26.2 statistics for INSERT are not saved. Everything is filled with zeros
Related with ansible-collections/community.clickhouse#177
26.1 
```
query_duration_ms:                      1
read_rows:                              3
read_bytes:                             35
written_rows:                           3
written_bytes:                          35
result_rows:                            3
result_bytes:                           35

```
26.2
```
query_duration_ms:                      53
read_rows:                              0
read_bytes:                             0
written_rows:                           0
written_bytes:                          0
result_rows:                            0
result_bytes:                           0
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Create table and then insert dummy data.
```

host :) CREATE TABLE test_table_1 (x String) ENGINE = Memory

CREATE TABLE test_table_1
(
    `x` String
)
ENGINE = Memory

Query id: d047199f-41ff-4f73-bb60-c7e1cf022cb4

Ok.

0 rows in set. Elapsed: 0.029 sec. 

host :) insert into test_table_1 values ('one'), ('two'), ('three')

INSERT INTO test_table_1 FORMAT Values

Query id: 0fd9991a-a2ed-42e7-803b-0e0209a0f31a

Ok.

0 rows in set. Elapsed: 0.054 sec. 
```
The same for 26.2
```
host :) insert into test_table_1 values ('one'), ('two'), ('three')

INSERT INTO test_table_1 FORMAT Values

Query id: 0883e9dc-0489-41f1-a8ca-ed5c0048b7ef

Ok.

3 rows in set. Elapsed: 0.002 sec. 

```
Same behaviour with ptyhon clickhouse-driver

### Expected behavior

Save statistics for insert queries

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CheSema**
Since `async_insert` defaults to `true`, INSERT queries go through the async insert path where the actual flush happens in a background thread with a separate query context. The original client query's `ProcessListElement` was never updated with write statistics, causing `written_rows`, `read_rows`, `result_rows` (and their byte counterparts) to be zeros in both the client output and `query_log`.

The fix communicates per-entry written rows/bytes from the background flush thread back to the waiting client via the `Entry` future (changed from `std::future<void>` to `std::future<WriteResult>`). After the future resolves, both the TCP and HTTP paths update the original query's `ProcessListElement` progress, which feeds into `query_log` and the client progress protocol.

Closes #99758

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix async insert queries reporting zero `written_rows`, `read_rows`, and `result_rows` in `query_log` and client output.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.417`
- Backported to: `26.3.3.12`, `26.2.7.10`

### CODE REVIEW

File: src/Interpreters/AsynchronousInsertQueue.cpp [hunk 1]
```diff
@@ -1161,7 +1170,13 @@ try
...
         {
             if (!entry->isFinished())
-                entry->finish();
+            {
+                auto it = per_entry_write_results.find(entry.get());
+                if (it != per_entry_write_results.end())
+                    entry->finish(it->second);
+                else
+                    entry->finish();
+            }
```
Comment (Michicosun) [inline src/Interpreters/AsynchronousInsertQueue.cpp]: Why is it possible that this map will not have this entry at this point?

File: src/Processors/Sources/WaitForAsyncInsertSource.h [hunk 2]
```diff
@@ -37,13 +45,45 @@ class WaitForAsyncInsertSource : public ISource, WithContext
...
+            Progress write_progress;
+            write_progress.written_rows = write_result.written_rows;
+            write_progress.written_bytes = write_result.written_bytes;
+            process_list_elem->updateProgressOut(write_progress);
+
+            /// For INSERT queries, read_rows/read_bytes should also reflect
+            /// the data that was parsed.
+            Progress read_progress;
+            read_progress.read_rows = write_result.written_rows;
+            read_progress.read_bytes = write_result.written_bytes;
```
Comment (Michicosun) [inline src/Processors/Sources/WaitForAsyncInsertSource.h]: That does not seem correct for arbitrary formats

Comment (CheSema) [reply src/Processors/Sources/WaitForAsyncInsertSource.h]: Actually I measure the rows and bytes which come from the user in the insert, this I use to set progress for both read and write. And for read it is precise, but for write it is not, but well enough.

File: src/Interpreters/AsynchronousInsertQueue.cpp (hunk 1 above)
Comment (CheSema) [reply src/Interpreters/AsynchronousInsertQueue.cpp]: it is not possible, I changed to the chassert.

File: src/Processors/Sources/WaitForAsyncInsertSource.h (hunk 2 above)
Comment (CheSema) [reply src/Processors/Sources/WaitForAsyncInsertSource.h]: I did a renames to clarify that

**Review by Michicosun — APPROVED** [review]
