### PR TITLE
Fix std::out_of_range when reading from Buffer table with sample

### LINKED ISSUE #99134: Logical error: 'std::exception. Code: 1001, type: std::out_of_range, e.what() = vector (version 26.3.1.535 (official build)), Stack trace: (STID: None)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: 'std::exception. Code: 1001, type: std::out_of_range, e.what() = vector (version 26.3.1.535 (official build)), Stack trace: (STID: None)
CI report: [AST fuzzer (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=b98e6439e85adb6ec2f37ff558a6bbad33bec618&name_0=MasterCI&name_1=AST%20fuzzer%20%28amd_debug%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ3N0ZDo6ZXhjZXB0aW9uLiBDb2RlOiAxMDAxLCB0eXBlOiBzdGQ6Om91dF9vZl9yYW5nZSwgZS53aGF0KCkgPSB2ZWN0b3IgKHZlcnNpb24gMjYuMy4xLjUzNSAob2ZmaWNpYWwgYnVpbGQpKSwgU3RhY2sgdHJhY2U6IChTVElEOiBOb25lKScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0FTVCBmdXp6ZXIgKGFtZF9kZWJ1ZyknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciA9IDAgT1IgYmFzZV9yZWYgSU4gKCcnLCAnbWFzdGVyJykpCiAgICBBTkQgdGVzdF9jb250ZXh0X3JhdyBMSUtFICclQ29kZTolJwpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
Error:
Logical error: 'std::exception. Code: 1001, type: std::out_of_range, e.what() = vector (version 26.3.1.535 (official build)), Stack trace:

0. /ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113:14: std::logic_error::logic_error(char const*) @ 0x000000002cb26834
1. /ClickHouse/contrib/llvm-project/libcxx/include/stdexcept:165:66: std::out_of_range::out_of_range[abi:se210105](char const*) @ 0x000000000e254d89
2. /ClickHouse/contrib/llvm-project/libcxx/include/stdexcept:251:9: std::__throw_out_of_range[abi:se210105](char const*) @ 0x000000000e254d1f
3. /ClickHouse/contrib/llvm-project/libcxx/include/__vector/vector.h:779:79: ? @ 0x0000000010973dcd
4. /ClickHouse/contrib/llvm-project/libcxx/include/__vector/vector.h:420:7: DB::MergeTreeDataSelectExecutor::getSampling(DB::SelectQueryInfo const&, DB::NamesAndTypesList, DB::RangesInDataParts const&, DB::KeyCondition&, DB::MergeTreeData const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, std::shared_ptr<Poco::Logger>) @ 0x000000001fa11d0f
5. /ClickHouse/src/Processors/QueryPlan/ReadFromMergeTree.cpp:2421:23: DB::ReadFromMergeTree::selectRangesToRead(DB::RangesInDataParts const&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::optional<DB::VectorSearchParameters> const&, std::optional<DB::TopKFilterInfo> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const>, unsigned long, std::shared_ptr<std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>> const>, DB::MergeTreeData const&, std::shared_ptr<DB::MergeTreeSettings const> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<Poco::Logger>, std::optional<DB::ReadFromMergeTree::Indexes>&, bool, bool, bool, bool) @ 0x000000002078c54a
6. /ClickHouse/src/Processors/QueryPlan/ReadFromMergeTree.cpp:1882:27: DB::ReadFromMergeTree::selectRangesToRead(bool) const @ 0x000000002078ab84
7. /ClickHouse/src/Processors/QueryPlan/ReadFromMergeTree.cpp:2919:31: DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x000000002079a180
---

Failed query:
SELECT count(toUInt64(1)) FROM b1_01361 SAMPLE 1 / 10 LIMIT 100
---

Reproduce commands (auto-generated; may require manual adjustment):
CREATE TABLE b1_01361 AS t1_01361 ENGINE = Buffer(currentDatabase(), t1_01361, 1, 0, 0, 1, 1, 1, 1);
SELECT count(toUInt64(1)) FROM b1_01361 SAMPLE 1 / 10 LIMIT 100;
DROP TABLE IF EXISTS b1_01361;
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash on usage of Buffer table with SAMPLE when destination does not support it.

### Documentation entry for user-facing changes

Closes https://github.com/ClickHouse/ClickHouse/issues/99134

- [ ] Documentation is written (mandatory for new features)

---

> [!NOTE]
> **Low Risk**
> Low risk bug fix that adds a guard and a regression test; behavior changes only when `SAMPLE` is used on tables without a sampling key, now returning a clear `SAMPLING_NOT_SUPPORTED` error instead of potentially crashing.
> 
> **Overview**
> Prevents a crash when executing `SAMPLE` against a MergeTree-backed `Buffer` table whose destination MergeTree has no `SAMPLE BY` key.
> 
> `MergeTreeDataSelectExecutor::getSampling()` now explicitly checks `metadata_snapshot->hasSamplingKey()` before accessing the sampling key and throws `ErrorCodes::SAMPLING_NOT_SUPPORTED` with a clear message when absent.
> 
> Adds a stateless regression test covering the failing Buffer+MergeTree case (expects `SAMPLING_NOT_SUPPORTED`) and confirms `SAMPLE` still works for Buffer tables without a destination table (in-memory only).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit f5aec3e1dc628053456d489e4fb495f0bca7240f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.605`

### CODE REVIEW

File: src/Storages/StorageBuffer.h [hunk 1]
```diff
@@ -109,7 +109,16 @@ friend class BufferSink;
...
-    bool supportsSampling() const override { return true; }
+    bool supportsSampling() const override
+    {
+        /// During reads, Buffer queries both the in-memory buffers and the destination table simultaneously.
+        /// Sampling on the buffer part is handled probabilistically (no sampling key required).
+        /// Sampling on the destination part requires the destination to have a sampling key.
+        /// If there is no destination, only the buffer is read, so sampling is always supported.
+        if (auto destination = getDestinationTable())
+            return destination->supportsSampling();
+        return true;
```
Comment (azat) [inline src/Storages/StorageBuffer.h]: Hm, is the following possible?

`SELECT * FROM buffer`:
- `getSampling()` == `return true` -- because underlying table supports sampling
- then another thread re-create table w/o sampling, in the middle of that SELECT
- then `StorageBuffer::read` calls `getDestinationTable` again and got table that does not support it

I think so. Then we need a check in `MergeTreeDataSelectExecutor::getSampling`

File: tests/queries/0_stateless/04034_buffer_sample_no_sampling_key.sql [hunk 2]
```diff
@@ -0,0 +1,22 @@
+-- Regression test for https://github.com/ClickHouse/ClickHouse/issues/99134
+-- SAMPLE on a Buffer table backed by a MergeTree without SAMPLE BY used to crash the server.
+
+DROP TABLE IF EXISTS t0;
+DROP TABLE IF EXISTS t1;
+
+CREATE TABLE t0 (c0 Int) ENGINE = MergeTree ORDER BY tuple();
```
Comment (azat) [inline tests/queries/0_stateless/04034_buffer_sample_no_sampling_key.sql:7]: I think it also make sense to test Buffer over MergeTree table with sampling, just in case

**Review by azat — APPROVED** [review]
BTW do we have the same problem for i.e. views?

File: tests/queries/0_stateless/04034_buffer_sample_no_sampling_key.sql (hunk 2 above)
Comment (kssenii) [reply tests/queries/0_stateless/04034_buffer_sample_no_sampling_key.sql:7]: I see there is such test already https://github.com/ClickHouse/ClickHouse/blob/f8a8eb2edecb023024ae3b719a4749dcef2ee62c/tests/queries/0_stateless/00061_storage_buffer.sql#L5-L12
