### PR TITLE
Fix incorrect virtual_parts after part corruption

### LINKED ISSUE #19593: CH forgot about several parts
20.9.7.
During a merge a part was detached by ReplicatedMergeTreePartCheckThread as broken.
CH wasn't able to recover the part because the table only has one replica (later I attached the part back successfully though).
Because of that the NEW (not created yet) part got marked as 'lost forever' (unexpected behaviour), which lead to another unexpected behaviour when we needed to drop a column from the table.

The details:

A merge was scheduled:
```
2021.01.19 22:51:20.987159 [ 9711 ] {} <Trace> db.table: Created log entry /clickhouse/tables/14/table/log/log-0000198617 for merge 20210119_254_293_2
2021.01.19 22:51:20.988217 [ 9709 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000198617 - log-0000198617
2021.01.19 22:51:20.994938 [ 9709 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2021.01.19 22:51:20.995006 [ 9730 ] {} <Trace> db.table: Executing log entry to merge parts 20210119_254_261_1, 20210119_262_267_1, 20210119_268_273_1, 20210119_274_279_1, 20210119_280_285_1, 20210119_286_291_1, 20210119_292_292_0, 20210119_293_293_0 to 20210119_254_293_2
2021.01.19 22:51:20.995057 [ 9730 ] {} <Debug> DiskLocal: Reserving 8.71 GiB on disk `default`, having unreserved 5.82 TiB.
2021.01.19 22:51:20.995081 [ 9730 ] {} <Debug> db.table (MergerMutator): Merging 8 parts: from 20210119_254_261_1 to 20210119_293_293_0 into Wide
2021.01.19 22:51:20.995464 [ 9730 ] {} <Debug> db.table (MergerMutator): Selected MergeAlgorithm: Vertical
2021.01.19 22:51:21.011655 [ 9730 ] {} <Trace> MergeTreeSequentialSource: Reading 1069 marks from part 20210119_254_261_1, total 8752897 rows starting from the beginning of the part
```
It was reading data when another thread started checking a part:
```
2021.01.19 22:52:15.724000 [ 9730 ] {} <Trace> MergeTreeSequentialSource: Reading 1069 marks from part 20210119_254_261_1, total 8752897 rows starting from the beginning of the part, column floor

2021.01.19 22:52:16.211682 [ 9758 ] {} <Warning> db.table (ReplicatedMergeTreePartCheckThread): Checking part 20210119_254_261_1
2021.01.19 22:52:16.212705 [ 9758 ] {} <Warning> db.table (ReplicatedMergeTreePartCheckThread): Checking data of part 20210119_254_261_1.
```
The merging thread 9730 failed:
```
2021.01.19 22:52:16.406541 [ 9730 ] {} <Error> db.table: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 40, e.displayText() = DB::Exception: Checksum doesn't match: corrupted data. Reference: aedfece83e71a6af9ab401e8c70fe7bd. Actual: 6db5d49e651b5b6ad63b9244e50db5ca. Size of compressed block: 11405: (while reading column floor_price): (while reading from part /var/lib/clickhouse/data/db/table/20210119_254_261_1/ from mark 938 with max_rows_to_read = 8192): While executing MergeTreeSequentialSource: Cannot fetch required block. Stream PipelineExecuting, part 0, Stack trace (when copying this message, always include the lines below)
```
The checking thread 9758 detached the part:
```
2021.01.19 22:52:17.780119 [ 9758 ] {} <Error> db.table (ReplicatedMergeTreePartCheckThread): Part 20210119_254_261_1 looks broken. Removing it and queueing a fetch.
2021.01.19 22:52:17.789749 [ 9758 ] {} <Information> db.table: Renaming 20210119_254_261_1 to broken20210119_254_261_1 and forgiving it.
2021.01.19 22:52:17.790296 [ 9758 ] {} <Trace> db.table (ReplicatedMergeTreePartCheckThread): Execution took 1578 ms.
```
Another thread started the merge again, but one part was missing, so the thread marked as lost the NEW part, 20210119_254_293_2 (as well as the detached part)
```
2021.01.19 22:52:27.473582 [ 9727 ] {} <Trace> db.table: Executing log entry to merge parts 20210119_254_261_1, 20210119_262_267_1, 20210119_268_273_1, 20210119_274_279_1, 20210119_280_285_1, 20210119_286_291_1, 20210119_292_292_0, 20210119_293_293_0 to 20210119_254_293_2
2021.01.19 22:52:27.473605 [ 9727 ] {} <Debug> db.table: Don't have all parts for merge 20210119_254_293_2; will try to fetch it instead
2021.01.19 22:52:27.474010 [ 9740 ] {} <Warning> db.table (ReplicatedMergeTreePartCheckThread): Checking part 20210119_254_293_2
2021.01.19 22:52:27.474032 [ 9727 ] {} <Information> db.table: DB::Exception: No active replica has part 20210119_254_293_2 or covering part
2021.01.19 22:52:27.474408 [ 9740 ] {} <Warning> db.table (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 20210119_254_293_2.
2021.01.19 22:52:27.475311 [ 9740 ] {} <Error> db.table (ReplicatedMergeTreePartCheckThread): No replica has part covering 20210119_254_293_2 and a merge is impossible: we didn't find a smaller part with the same max block.
2021.01.19 22:52:27.481798 [ 9740 ] {} <Error> db.table (ReplicatedMergeTreePartCheckThread): Part 20210119_254_293_2 is lost forever.

2021.01.19 22:52:27.794690 [ 9740 ] {} <Warning> db.table (ReplicatedMergeTreePartCheckThread): Checking part 20210119_254_261_1
2021.01.19 22:52:27.794700 [ 9720 ] {} <Information> db.table: DB::Exception: No active replica has part 20210119_254_261_1 or covering part
2021.01.19 22:52:27.795130 [ 9740 ] {} <Warning> db.table (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 20210119_254_261_1.
2021.01.19 22:52:27.796030 [ 9740 ] {} <Error> db.table (ReplicatedMergeTreePartCheckThread): No replica has part covering 20210119_254_261_1 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2021.01.19 22:52:27.803382 [ 9740 ] {} <Error> db.table (ReplicatedMergeTreePartCheckThread): Part 20210119_254_261_1 is lost forever.
```
A few days later a mutation skipped the parts that were supposed to be merged with the 'broken' part (20210119_262_267_1, 20210119_268_273_1, 20210119_274_279_1, 20210119_280_285_1, 20210119_286_291_1, 20210119_292_292_0, 20210119_293_293_0):
```
2021.01.25 09:12:38.455858 [ 31330 ] {1c262294-4fe9-4e4b-acec-ca3c42a1b7ec} <Debug> executeQuery: (from [::1]:48234) alter table db.table drop column bba7dt
2021.01.25 09:12:39.874691 [ 9734 ] {} <Information> db.table (ReplicatedMergeTreeQueue): Loading 1 mutation entries: 0000000013 - 0000000013
2021.01.25 09:12:39.891032 [ 9734 ] {} <Trace> db.table (ReplicatedMergeTreeQueue): Adding mutation 0000000013 for partition 20210119 for all block numbers less than 480
...
2021.01.25 09:13:15.696975 [ 9734 ] {} <Trace> db.table: Created log entry for mutation 20210119_0_216_3_480
2021.01.25 09:13:15.734053 [ 9713 ] {} <Trace> db.table: Created log entry for mutation 20210119_217_253_2_480
!!!! skipped parts should have been here
2021.01.25 09:13:15.749085 [ 9711 ] {} <Trace> db.table: Created log entry for mutation 20210119_294_328_2_480
2021.01.25 09:13:15.760000 [ 9742 ] {} <Trace> db.table: Created log entry for mutation 20210119_329_363_2_480
...
2021.01.25 09:13:24.553450 [ 9740 ] {} <Trace> db.table: Created log entry for mutation 20210125_19_19_0_20
```
After that the mutation got stuck with parts_to_do=8.
Here is the list of parts in ZooKeeper at the time:
```
name                   | ctime              
-----------------------+--------------------
20210119_0_216_3_480   | 2021-01-25 09:13:16
20210119_217_253_2_480 | 2021-01-25 09:13:16
20210119_262_267_1     | 2021-01-19 17:50:13
20210119_268_273_1     | 2021-01-19 18:06:43
20210119_274_279_1     | 2021-01-19 18:17:58
20210119_280_285_1     | 2021-01-19 18:33:07
20210119_286_291_1     | 2021-01-19 18:50:02
20210119_292_292_0     | 2021-01-19 18:50:29
20210119_293_293_0     | 2021-01-19 18:51:15
20210119_294_328_2_480 | 2021-01-25 09:13:16
20210119_329_363_2_480 | 2021-01-25 09:13:16
```
After a few hours I restarted the table:
```
2021.01.25 14:28:15.850433 [ 1378 ] {2839b9af-2fa8-42bb-ab06-d806fb18644e} <Debug> executeQuery: (from [::1]:45158) system restart replica db.table
```
As a result the ALTER got interrupted.
```
2021.01.25 14:28:16.649570 [ 31330 ] {1c262294-4fe9-4e4b-acec-ca3c42a1b7ec} <Trace> db.table (ReplicatedMergeTreeRestartingThread): Restarting thread finished
2021.01.25 14:28:16.649593 [ 31330 ] {1c262294-4fe9-4e4b-acec-ca3c42a1b7ec} <Trace> db.table (ReplicatedMergeTreeRestartingThread): Waiting for threads to finish
2021.01.25 14:28:16.649598 [ 31330 ] {1c262294-4fe9-4e4b-acec-ca3c42a1b7ec} <Trace> db.table (ReplicatedMergeTreeRestartingThread): Threads finished
2021.01.25 14:28:16.710937 [ 31330 ] {1c262294-4fe9-4e4b-acec-ca3c42a1b7ec} <Error> executeQuery: Code: 341, e.displayText() = DB::Exception: Mutation is not finished because table shutdown was called. It will be done after table restart. (version 20.9.7.11 (off
icial build)) (from [::1]:48234) (in query: alter table db.table drop column bba7dt
```
The mutation found 7 parts. MergerMutator found them as well. They were merged then mutated.
```
2021.01.25 14:28:28.230124 [ 9734 ] {} <Trace> db.table (ReplicatedMergeTreeQueue): Mutation 0000000013 is not done yet because 7 parts to mutate suddenly appeared.
2021.01.25 14:28:28.233083 [ 9709 ] {} <Debug> db.table (MergerMutator): Selected 7 parts from 20210119_262_267_1 to 20210119_293_293_0
2021.01.25 14:28:28.239167 [ 9709 ] {} <Trace> db.table: Created log entry /clickhouse/tables/14/table/log/log-0000202318 for merge 20210119_262_293_2
2021.01.25 14:28:28.239294 [ 9757 ] {} <Trace> db.table (ReplicatedMergeTreeQueue): Mutation 0000000013 is not done yet because 7 parts to mutate suddenly appeared.
2021.01.25 14:28:28.241162 [ 9758 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000202318 - log-0000202318
2021.01.25 14:28:28.246171 [ 9758 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
...
2021.01.25 14:39:17.698423 [ 9729 ] {} <Trace> db.table: Renaming temporary part tmp_merge_20210119_262_293_2 to 20210119_262_293_2.
2021.01.25 14:39:17.698466 [ 9729 ] {} <Trace> db.table (MergerMutator): Merged 7 parts: from 20210119_262_267_1 to 20210119_293_293_0
2021.01.25 14:39:17.715249 [ 9711 ] {} <Trace> db.table: Created log entry for mutation 20210119_262_293_2_480
2021.01.25 14:39:17.716625 [ 9732 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000202319 - log-0000202319
2021.01.25 14:39:17.720744 [ 9732 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2021.01.25 14:39:17.720815 [ 9725 ] {} <Trace> db.table: Executing log entry to mutate part 20210119_262_293_2 to 20210119_262_293_2_480
2021.01.25 14:39:17.720839 [ 9725 ] {} <Debug> DiskLocal: Reserving 6.83 GiB on disk `default`, having unreserved 5.88 TiB.
2021.01.25 14:39:17.721298 [ 9725 ] {} <Trace> db.table (MergerMutator): Mutating part 20210119_262_293_2 to mutation version 480
2021.01.25 14:39:17.738997 [ 9725 ] {} <Trace> db.table: Renaming temporary part tmp_mut_20210119_262_293_2_480 to 20210119_262_293_2_480.
2021.01.25 14:39:17.744894 [ 9740 ] {} <Trace> db.table (ReplicatedMergeTreeQueue): Will check if mutation 0000000013 is done
2021.01.25 14:39:17.744931 [ 9740 ] {} <Debug> db.table (ReplicatedMergeTreeQueue): Trying to finalize 1 mutations
2021.01.25 14:39:17.758855 [ 9740 ] {} <Trace> db.table (ReplicatedMergeTreeQueue): Mutation 0000000013 is done
2021.01.25 14:39:17.758878 [ 9740 ] {} <Trace> db.table (ReplicatedMergeTreeQueue): Finishing data alter with version 53 for entry 0000000013
```
Happy end :)

### PR DESCRIPTION
**Pull request by alesapin**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix rare bug when some replicated operations (like mutation) cannot process some parts after data corruption. Fixes #19593.

### CODE REVIEW

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp [hunk 1]
```diff
@@ -160,21 +161,48 @@ void ReplicatedMergeTreePartCheckThread::searchForMissingPart(const String & par
         not_found_msg = "smaller parts with either the same min block or the same max block.";
     LOG_ERROR(log, "No replica has part covering {} and a merge is impossible: we didn't find {}", part_name, not_found_msg);
 
-    ProfileEvents::increment(ProfileEvents::ReplicatedPartChecksFailed);
+    return MissingPartSearchResult::LostForever;
+}
+
+void ReplicatedMergeTreePartCheckThread::searchForMissingPartAndFetchIfPossible(const String & part_name)
```
Comment (alesapin) [inline src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:167]: Some improvements in the part checker allowed me to write the test.

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp [hunk 2]
```diff
@@ -160,21 +161,48 @@ void ReplicatedMergeTreePartCheckThread::searchForMissingPart(const String & par
...
-    ProfileEvents::increment(ProfileEvents::ReplicatedDataLoss);
+    ProfileEvents::increment(ProfileEvents::ReplicatedPartChecksFailed);
+
+    if (missing_part_search_result == MissingPartSearchResult::LostForever)
+    {
+        /// Is it in the replication queue? If there is - delete, because the task can not be processed.
+        if (!storage.queue.remove(zookeeper, part_name))
+        {
+            /// The part was not in our queue. Why did it happen?
+            LOG_ERROR(log, "Missing part {} is not in our queue.", part_name);
```
Comment (alesapin) [inline src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:197]: Add logical error

**Review by alexey-milovidov — APPROVED** [review]

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp [hunk 3]
```diff
@@ -194,7 +195,7 @@ void ReplicatedMergeTreePartCheckThread::searchForMissingPartAndFetchIfPossible(
         if (!storage.queue.remove(zookeeper, part_name))
         {
             /// The part was not in our queue. Why did it happen?
-            LOG_ERROR(log, "Missing part {} is not in our queue.", part_name);
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Missing part {} is not in our queue.", part_name);
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:198]: Do we this exception it in release build? It will stuck the queue.

Comment (alesapin) [reply src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:198]: Yes, possibly too dangerous.

Comment (alesapin) [reply src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:198]: However, this exception will be thrown in the checker thread and it will not affect the queue.

**Comment by alexey-milovidov** [comment]
> AST fuzzer (debug) — Received signal 11 

https://github.com/ClickHouse/ClickHouse/pull/19736/

**Comment by alexey-milovidov** [comment]
> AST fuzzer (TSan) 

#19704

**Comment by alexey-milovidov** [comment]
> AST fuzzer (MSan)

https://github.com/ClickHouse/ClickHouse/issues/19756

**Comment by alesapin** [comment]
Another bug in part checker, need investigation:
```
2021.01.28 13:08:37.187183 [ 16157 ] {} <Information> test_nj731q.r3 (1c125c4e-9a4e-413c-bdf9-6cf859870a91): DB::Exception: No active replica has part all_114_114_0 or covering part
2021.01.28 13:08:37.187275 [ 189 ] {} <Warning> test_nj731q.r3 (ReplicatedMergeTreePartCheckThread): Checking part all_114_114_0
2021.01.28 13:08:37.187482 [ 189 ] {} <Warning> test_nj731q.r3 (ReplicatedMergeTreePartCheckThread): We have part all_0_114_19 covering part all_114_114_0
2021.01.28 13:08:37.187536 [ 194 ] {} <Trace> test_nj731q.r3 (ReplicatedMergeTreeQueue): Not executing log entry queue-0000000116 for part all_113_113_0 because it is covered by part all_0_114_19 that is currently executing.
2021.01.28 13:08:37.187555 [ 11113 ] {} <Trace> test_nj731q.r3 (1c125c4e-9a4e-413c-bdf9-6cf859870a91): Found local part all_0_114_19 with the same checksums as all_0_114_19
2021.01.28 13:08:37.187709 [ 194 ] {} <Trace> test_nj731q.r3 (ReplicatedMergeTreeQueue): Not executing log entry queue-0000000117 for part all_114_114_0 because it is covered by part all_0_114_19 that is currently executing.
2021.01.28 13:08:37.187810 [ 11113 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 18.64 GiB.
2021.01.28 13:08:37.187976 [ 16030 ] {} <Debug> test_nj731q.r3 (1c125c4e-9a4e-413c-bdf9-6cf859870a91): Skipping action for part all_115_115_0 because part all_115_115_0 already exists.
2021.01.28 13:08:37.187988 [ 11113 ] {} <Debug> test_nj731q.r3 (1c125c4e-9a4e-413c-bdf9-6cf859870a91): Cloning part /var/lib/clickhouse/store/1c1/1c125c4e-9a4e-413c-bdf9-6cf859870a91/all_0_114_19/ to /var/lib/clickhouse/store/1c1/1c125c4e-
9a4e-413c-bdf9-6cf859870a91/tmp_clone_all_0_114_19
2021.01.28 13:08:37.189306 [ 187 ] {} <Trace> test_nj731q.r3 (ReplicatedMergeTreeQueue): Not executing log entry queue-0000000116 for part all_113_113_0 because it is covered by part all_0_114_19 that is currently executing.
2021.01.28 13:08:37.189474 [ 187 ] {} <Trace> test_nj731q.r3 (ReplicatedMergeTreeQueue): Not executing log entry queue-0000000117 for part all_114_114_0 because it is covered by part all_0_114_19 that is currently executing.
2021.01.28 13:08:37.189888 [ 11113 ] {} <Trace> test_nj731q.r3 (1c125c4e-9a4e-413c-bdf9-6cf859870a91): Renaming temporary part tmp_clone_all_0_114_19 to all_0_114_19.
2021.01.28 13:08:37.191579 [ 11113 ] {} <Error> test_nj731q.r3 (1c125c4e-9a4e-413c-bdf9-6cf859870a91): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::St
orageReplicatedMergeTree::LogEntryPtr &) const: Code: 235, e.displayText() = DB::Exception: Part all_0_114_19 (state Committed) already exists, Stack trace (when copying this message, always include the lines below):

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x16118afb in /usr/bin/clickhouse
1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:56: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8c856ee in /usr/bin/clickhouse
2. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/MergeTreeData.cpp:1982: DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >*) @ 0x132b0698 in /usr/bin/clickhouse
3. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__mutex_base:141: DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) @ 0x132b163b in /usr/bin/clickhouse
4. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:463: DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x130c973e in /usr/bin/clickhouse
5. ./obj-x86_64-linux-gnu/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x130c4589 in /usr/bin/clickhouse
6. ./obj-x86_64-linux-gnu/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x130b1c90 in /usr/bin/clickhouse
7. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: bool std::__1::__function::__policy_invoker<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)::$_15, bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)> >(std::__1::__function::__policy_storage const*, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&) @ 0x1310ee04 in /usr/bin/clickhouse
8. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1385: DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x1346d577 in /usr/bin/clickhouse
9. ./obj-x86_64-linux-gnu/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x130d7ca6 in /usr/bin/clickhouse
10. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2090: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageReplicatedMergeTree::getDataProcessingJob()::$_16, void ()> >(std::__1::__function::__policy_storage const*) @ 0x1310f8f9 in /usr/bin/clickhouse
11. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/BackgroundJobsExecutor.cpp:103: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::IBackgroundJobExecutor::jobExecutingTask()::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x13246996 in /usr/bin/clickhouse
12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2210: ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8caac81 in /usr/bin/clickhouse
13. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x8cad9a1 in /usr/bin/clickhouse
14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2090: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x8cad902 in /usr/bin/clickhouse
15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2210: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8ca85a6 in /usr/bin/clickhouse
16. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0x8cac249 in /usr/bin/clickhouse
17. __tsan_thread_start_func @ 0x8bbb7ad in /usr/bin/clickhouse
18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.2.1.5832)

```

**Comment by alesapin** [comment]
Oh, no it's OK, we just need to reduce `old_parts_lifetime` in test.

**Comment by alesapin** [comment]
```
                /// It's possible in rare case:
                /// 1) We have tried to execute merge but don't have all source parts
                /// 2) So we tried to fetch the already merged part, but this part doesn't exist yet (nobody merged it yet)
                /// 3) We asked part checked thread to try to find this part
                /// 4) This time we fetched all source parts for merge and started merge
                /// 5) Checker thread found this part on another replica and decided to add fetch for it
                /// 6) Our merge successfully finished and committed part
                /// 7) Now we have fetch that will never finish because we already have this part
```

**Comment by alesapin** [comment]
```$ zgrep -a 'Fatal' clickhouse-server.log
2021.01.25 14:56:30.252699 [ 270 ] {} <Fatal> Application: Child process was terminated by signal 11.
```
???

**Comment by alexey-milovidov** [comment]
@alesapin See the `main.log`.

**Comment by alesapin** [comment]
> @alesapin See the `main.log`.

It's in  Functional stateless tests (ANTLR debug) :(

**Comment by alesapin** [comment]
```
2021.01.29 14:13:25.486254 [ 186 ] {} <Fatal> : Logical error: 'Missing part 7_117_117_0 is not in our queue.'.
2021.01.29 14:13:25.487441 [ 70975 ] {} <Fatal> BaseDaemon: ########################################
2021.01.29 14:13:25.487592 [ 70975 ] {} <Fatal> BaseDaemon: (version 21.2.1.5845, build id: DC45960B74485E4B611429B704E6355721A70D67) (from thread 186) (no query) Received signal Aborted (6)
2021.01.29 14:13:25.487691 [ 70975 ] {} <Fatal> BaseDaemon: 
2021.01.29 14:13:25.487842 [ 70975 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fa646b7618b 0x7fa646b55859 0x10cb0396 0x10cb0453 0x10da08d1 0x1abeae01 0x1abebb58 0x1abef4ca 0x1abeff58 0x1abeff1d 0x1abefeed 0x1abefec5 0x1abefe9d 0x10cf0219 0x10cef535 0x199c644a 0x199ca5c6 0x199c8310 0x199c9338 0x199c930d 0x199c92d1 0x199c9212 0x199c9117 0x199c904d 0x199c901d 0x199c8ff5 0x199c8fd0 0x10cf0219
2021.01.29 14:13:25.488061 [ 70975 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.01.29 14:13:25.488186 [ 70975 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.01.29 14:13:25.488426 [ 70975 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:50: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10cb0396 in /usr/bin/clickhouse
2021.01.29 14:13:25.488621 [ 70975 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10cb0453 in /usr/bin/clickhouse
2021.01.29 14:13:25.489321 [ 70975 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Common/Exception.h:38: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10da08d1 in /usr/bin/clickhouse
2021.01.29 14:13:25.544652 [ 70975 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:200: DB::ReplicatedMergeTreePartCheckThread::searchForMissingPartAndFetchIfPossible(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) @ 0x1abeae01 in /usr/bin/clickhouse
2021.01.29 14:13:25.592461 [ 70975 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:245: DB::ReplicatedMergeTreePartCheckThread::checkPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1abebb58 in /usr/bin/clickhouse
2021.01.29 14:13:25.640241 [ 70975 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:393: DB::ReplicatedMergeTreePartCheckThread::run() @ 0x1abef4ca in /usr/bin/clickhouse
2021.01.29 14:13:25.687416 [ 70975 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:32: DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0::operator()() const @ 0x1abeff58 in /usr/bin/clickhouse
2021.01.29 14:13:25.732492 [ 70975 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0&>(fp)()) std::__1::__invoke<DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0&>(DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0&) @ 0x1abeff1d in /usr/bin/clickhouse
2021.01.29 14:13:25.777820 [ 70975 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0&>(DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0&) @ 0x1abefeed in /usr/bin/clickhouse
2021.01.29 14:13:25.822900 [ 70975 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0, void ()>::operator()() @ 0x1abefec5 in /usr/bin/clickhouse
2021.01.29 14:13:25.868264 [ 70975 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ReplicatedMergeTreePartCheckThread::ReplicatedMergeTreePartCheckThread(DB::StorageReplicatedMergeTree&)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x1abefe9d in /usr/bin/clickhouse
2021.01.29 14:13:25.868707 [ 70975 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x10cf0219 in /usr/bin/clickhouse
2021.01.29 14:13:25.868970 [ 70975 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const @ 0x10cef535 in /usr/bin/clickhouse
2021.01.29 14:13:25.903462 [ 70975 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Core/BackgroundSchedulePool.cpp:106: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x199c644a in /usr/bin/clickhouse
2021.01.29 14:13:25.938746 [ 70975 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Core/BackgroundSchedulePool.cpp:19: DB::TaskNotification::execute() @ 0x199ca5c6 in /usr/bin/clickhouse
2021.01.29 14:13:25.975020 [ 70975 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Core/BackgroundSchedulePool.cpp:265: DB::BackgroundSchedulePool::threadFunction() @ 0x199c8310 in /usr/bin/clickhouse
2021.01.29 14:13:26.010555 [ 70975 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../src/Core/BackgroundSchedulePool.cpp:161: DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1::operator()() const @ 0x199c9338 in /usr/bin/clickhouse
2021.01.29 14:13:26.046154 [ 70975 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&) @ 0x199c930d in /usr/bin/clickhouse
2021.01.29 14:13:26.081730 [ 70975 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415: decltype(auto) std::__1::__apply_tuple_impl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) @ 0x199c92d1 in /usr/bin/clickhouse
2021.01.29 14:13:26.116118 [ 70975 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424: decltype(auto) std::__1::apply<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&) @ 0x199c9212 in /usr/bin/clickhouse
2021.01.29 14:13:26.150455 [ 70975 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:178: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()::operator()() @ 0x199c9117 in /usr/bin/clickhouse
2021.01.29 14:13:26.184379 [ 70975 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) @ 0x199c904d in /usr/bin/clickhouse
2021.01.29 14:13:26.219351 [ 70975 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&...) @ 0x199c901d in /usr/bin/clickhouse
2021.01.29 14:13:26.255209 [ 70975 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()>::operator()() @ 0x199c8ff5 in /usr/bin/clickhouse
2021.01.29 14:13:26.291920 [ 70975 ] {} <Fatal> BaseDaemon: 30. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x199c8fd0 in /usr/bin/clickhouse
2021.01.29 14:13:26.292369 [ 70975 ] {} <Fatal> BaseDaemon: 31. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x10cf0219 in /usr/bin/clickhouse
2021.01.29 14:13:27.289790 [ 70975 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 8585FF309114FD2F9A831E454BC9C46F. There is no information about the reference checksum.
2021.01.29 14:13:37.241160 [ 154 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Comment by alesapin** [comment]
Happened after the table drop.

**Comment by alesapin** [comment]
Part checker is ideologically broken. It doesn't have any synchronization with queue or storage, the error happens in the following situation:
```
2021.01.29 14:13:24.280226 [ 13135 ] {} <Information> test_kstf0r.alter_table2 (676e6206-9f17-45f2-8083-8aef54f29f8e): DB::Exception: No active replica has part 7_117_117_0 or covering part
2021.01.29 14:13:24.508363 [ 182 ] {} <Warning> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): Checking part 7_117_117_0
2021.01.29 14:13:24.508778 [ 182 ] {} <Warning> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 7_117_117_0 or covering part.
2021.01.29 14:13:24.530997 [ 182 ] {} <Error> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): No replica has part covering 7_117_117_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2021.01.29 14:13:24.536228 [ 182 ] {} <Error> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): Part 7_117_117_0 is lost forever.
2021.01.29 14:13:24.536662 [ 13393 ] {} <Information> test_kstf0r.alter_table2 (676e6206-9f17-45f2-8083-8aef54f29f8e): DB::Exception: No active replica has part 7_117_117_0 or covering part
2021.01.29 14:13:25.473550 [ 186 ] {} <Warning> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): Checking part 7_117_117_0
2021.01.29 14:13:25.474006 [ 186 ] {} <Warning> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 7_117_117_0 or covering part.
2021.01.29 14:13:25.485931 [ 186 ] {} <Error> test_kstf0r.alter_table2 (ReplicatedMergeTreePartCheckThread): No replica has part covering 7_117_117_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2021.01.29 14:13:25.486254 [ 186 ] {} <Fatal> : Logical error: 'Missing part 7_117_117_0 is not in our queue.'.
```

The important lines are:
```
# fetch tries to execute one more time after an unsuccessful previous fetch.
(ReplicatedMergeTreePartCheckThread): Part 7_117_117_0 is lost forever. <--- part checker removing fetch from the queue
# fetch still executing, but removed from the queue by part checker
DB::Exception: No active replica has part 7_117_117_0 or covering part <-- fetch fails and queuing part checker to check 7_117_117_0
# fetch removed and is not in the queue
(ReplicatedMergeTreePartCheckThread): Checking part 7_117_117_0 <-- part checker check part which is not in the queue
Logical error: 'Missing part 7_117_117_0 is not in our queue.'  <--- ooops
```

**Comment by alesapin** [comment]
Finally fixed.
