### PR TITLE
Fix nullable primary key in final

### LINKED ISSUE #54156: ILLEGAL_TYPE_OF_ARGUMENT allow_nullable_key + final
https://fiddle.clickhouse.com/796d6997-b571-4e4f-aede-1e18f670ec6f

```sql
CREATE TABLE t
(
    d Nullable(Date),
    f1 Nullable(String),
    f2 Nullable(String),
    c Nullable(Int64)
)
ENGINE = ReplacingMergeTree()
ORDER BY (f1, f2, d)
SETTINGS allow_nullable_key = 1;

insert into t select today() d, 
  [number%999999, null][number%2] f1,  
  ['x', null][number%2] f2, 
  [number, null][number%2] c 
from numbers(1000000);

SELECT date_trunc('month', d), SUM( c )  
FROM t FINAL WHERE f2 = 'x' GROUP BY 1;

Received exception from server (version 23.7.5):
Code: 43. DB::Exception: Received from localhost:9000. 
DB::Exception: Illegal types of arguments (Date, UInt16) of function greater: 
While processing NOT ((f1, f2, d) > ('203217', 'x', 19600)). (ILLEGAL_TYPE_OF_ARGUMENT)
```

cc @amosbird

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect primary key analysis in FINAL queries when nullable primary key is used. This fixes #54156 .

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit ccfb28064a2d541d8ce543a71e60a8801d78ed27 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54164/ccfb28064a2d541d8ce543a71e60a8801d78ed27/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by amosbird** [comment]
> Integration tests (tsan) [5/6] — fail: 2, passed: 448

https://github.com/ClickHouse/ClickHouse/issues/53323

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 1]
```diff
@@ -212,23 +234,50 @@ ASTs buildFilters(const KeyDescription & primary_key, const std::vector<Values>
...
+            if (type->isNullable())
+                pk_ast = makeASTFunction("assumeNotNull", pk_ast);
+
+            pks_ast.push_back(std::move(pk_ast));
+            values_ast.push_back(std::move(component_ast));
         }
-        ASTPtr values_as_tuple = makeASTFunction("tuple", value_ast->children);
+
+        /// Always true.
+        if (pks_ast.empty())
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp:276]: I'd add a test case when this branch is taken

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 2]
```diff
@@ -212,23 +234,50 @@ ASTs buildFilters(const KeyDescription & primary_key, const std::vector<Values>
...
             // So we need an explicit Cast for them.
-            if (isColumnedAsNumber(types.at(i)->getTypeId()) && !isNumber(types.at(i)->getTypeId()))
-                component_ast = makeASTFunction("cast", std::move(component_ast), std::make_shared<ASTLiteral>(types.at(i)->getName()));
-            value_ast->children.push_back(std::move(component_ast));
+            if (isColumnedAsNumber(decayed_type->getTypeId()) && !isNumber(decayed_type->getTypeId()))
+                component_ast = makeASTFunction("cast", std::move(component_ast), std::make_shared<ASTLiteral>(decayed_type->getName()));
+
+            // If PK is nullable, null mask is used for comparison.
+            // Transform the AST into assumeNotNull(pk) so that the result type is not-nullable.
+            if (type->isNullable())
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp:268]: imo with only a single branch for `type->isNullable()` it would be easier to read

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 3]
```diff
@@ -212,23 +234,50 @@ ASTs buildFilters(const KeyDescription & primary_key, const std::vector<Values>
...
+
+            // If PK is nullable, prepend a null mask column for > comparison.
+            if (type->isNullable())
+            {
+                pks_ast.push_back(makeASTFunction("isNull", pk_ast));
+                values_ast.push_back(std::make_shared<ASTLiteral>(0));
+            }
+
+            ASTPtr component_ast = std::make_shared<ASTLiteral>(values[i]);
+            auto decayed_type = removeNullable(removeLowCardinality(primary_key.data_types.at(i)));
```
[the remark this answers is not in the document]
Comment (amosbird) [reply src/Processors/QueryPlan/PartsSplitter.cpp:260]: It's used for the same purpose of `removeNullable` so that the following `isColumnedAsNumber` check will work correctly.

File: src/Processors/QueryPlan/PartsSplitter.cpp (hunk 1 above)
Comment (amosbird) [reply src/Processors/QueryPlan/PartsSplitter.cpp:276]: Yes. Good idea :)

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 4]
```diff
@@ -212,23 +234,50 @@ ASTs buildFilters(const KeyDescription & primary_key, const std::vector<Values>
...
+            // Transform the AST into assumeNotNull(pk) so that the result type is not-nullable.
+            if (type->isNullable())
+                pk_ast = makeASTFunction("assumeNotNull", pk_ast);
+
+            pks_ast.push_back(std::move(pk_ast));
+            values_ast.push_back(std::move(component_ast));
         }
-        ASTPtr values_as_tuple = makeASTFunction("tuple", value_ast->children);
+
+        /// Always true.
```
[the remark this answers is not in the document]
Comment (amosbird) [reply src/Processors/QueryPlan/PartsSplitter.cpp:275]: Heh, actually it's always false.

**Review by nickitat — APPROVED** [review]

**Comment by nickitat** [comment]
Integration tests (release) [3/4] - test_global_overcommit_tracker/test.py::test_global_overcommit
Upgrade check (tsan) - #48474
