### PR TITLE
Fix shard join optimization when primary key is in reverse order

### LINKED ISSUE #88512: Logical error: 'Intersecting mark ranges are not allowed, it is a bug! First range (0, 11), second range (0, 256)'
### Describe the bug

Seems to happen with ORDER BY DESC only.

### How to reproduce

Run:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() ORDER BY (c0 DESC) SETTINGS index_granularity = 1, allow_experimental_reverse_key = 1;
INSERT INTO TABLE t0 (c0) SELECT c0 FROM generateRandom('c0 Int', 7285072819366316109, 1, 1) LIMIT 10;
SELECT 1 FROM t0 JOIN t0 tx USING (c0) SETTINGS query_plan_join_shard_by_pk_ranges = 1;
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Intersecting mark ranges are not allowed, it is a bug! First range (0, 11), second range (0, 256)'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000024107ff2
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014a61ca9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d35830e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d357d11
4. src/Common/Exception.h:141: DB::Exception::Exception<unsigned long const&, unsigned long const&, unsigned long const&, unsigned long const&>(int, FormatStringHelperImpl<std::type_identity<unsigned long const&>::type, std::type_identity<unsigned long const&>::type, std::type_identity<unsigned long const&>::type, std::type_identity<unsigned long const&>::type>, unsigned long const&, unsigned long const&, unsigned long const&, unsigned long const&) @ 0x000000001db6c0f6
5. src/Storages/MergeTree/MarkRange.cpp:44: DB::MarkRange::operator<(DB::MarkRange const&) const @ 0x000000001db6ace0
6. contrib/llvm-project/libcxx/include/__algorithm/comp.h:40: void std::__introsort<std::_ClassicAlgPolicy, std::__less<void, void>&, DB::MarkRange*, false>(DB::MarkRange*, DB::MarkRange*, std::__less<void, void>&, std::iterator_traits<DB::MarkRange*>::difference_type, bool) @ 0x000000001db6c3df
7. contrib/llvm-project/libcxx/include/__algorithm/sort.h:928: DB::assertSortedAndNonIntersecting(DB::MarkRanges const&) @ 0x000000001db6b318
8. src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:147: DB::MergeTreeReadPoolBase::fillPerPartInfos(DB::Settings const&) @ 0x000000001e9ddf26
9. src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:61: DB::MergeTreeReadPoolBase::MergeTreeReadPoolBase(DB::RangesInDataParts&&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>, std::unordered_map<String, DB::IndexReadTask, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::IndexReadTask>>> const&, std::shared_ptr<DB::StorageSnapshot> const&, std::shared_ptr<DB::FilterDAGInfo> const&, std::shared_ptr<DB::PrewhereInfo> const&, DB::ExpressionActionsSettings const&, DB::MergeTreeReaderSettings const&, std::vector<String, std::allocator<String>> const&, DB::MergeTreeReadPoolBase::PoolSettings const&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001e9ddaab
10. src/Storages/MergeTree/MergeTreeReadPoolInOrder.cpp:27: DB::MergeTreeReadPoolInOrder::MergeTreeReadPoolInOrder(bool, DB::MergeTreeReadType, DB::RangesInDataParts, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>, std::unordered_map<String, DB::IndexReadTask, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::IndexReadTask>>> const&, std::shared_ptr<DB::StorageSnapshot> const&, std::shared_ptr<DB::FilterDAGInfo> const&, std::shared_ptr<DB::PrewhereInfo> const&, DB::ExpressionActionsSettings const&, DB::MergeTreeReaderSettings const&, std::vector<String, std::allocator<String>> const&, DB::MergeTreeReadPoolBase::PoolSettings const&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001ea0f025
11. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::MergeTreeReadPoolInOrder* std::construct_at[abi:se190107]<DB::MergeTreeReadPoolInOrder, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::unordered_map<String, DB::IndexReadTask, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::IndexReadTask>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::FilterDAGInfo>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&, DB::MergeTreeReadPoolInOrder*>(DB::MergeTreeReadPoolInOrder*, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::unordered_map<String, DB::IndexReadTask, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::IndexReadTask>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::FilterDAGInfo>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&) @ 0x000000001e9cbc03
12. contrib/llvm-project/libcxx/include/__memory/construct_at.h:49: DB::ReadFromMergeTree::readInOrder(DB::RangesInDataParts, std::shared_ptr<DB::MergeTreeIndexBuildContext> const&, std::vector<String, std::allocator<String>>, DB::MergeTreeReadPoolBase::PoolSettings, DB::MergeTreeReadType, unsigned long) @ 0x000000001e99c86f
13. src/Processors/QueryPlan/ReadFromMergeTree.cpp:779: DB::ReadFromMergeTree::read(DB::RangesInDataParts, std::shared_ptr<DB::MergeTreeIndexBuildContext> const&, std::vector<String, std::allocator<String>>, DB::MergeTreeReadType, unsigned long, unsigned long, bool) @ 0x000000001e99e5d0
14. src/Processors/QueryPlan/ReadFromMergeTree.cpp:961: DB::Pipe std::__function::__policy_invoker<DB::Pipe (DB::RangesInDataParts)>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::ReadFromMergeTree::readByLayers(DB::RangesInDataParts const&, DB::SplitPartsByRanges, std::shared_ptr<DB::MergeTreeIndexBuildContext> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::InputOrderInfo const> const&)::$_1, DB::Pipe (DB::RangesInDataParts)>>(std::__function::__policy_storage const*, DB::RangesInDataParts&&) @ 0x000000001e9c11d8
15. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001e9f31aa
16. src/Processors/QueryPlan/ReadFromMergeTree.cpp:972: DB::ReadFromMergeTree::readByLayers(DB::RangesInDataParts const&, DB::SplitPartsByRanges, std::shared_ptr<DB::MergeTreeIndexBuildContext> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::InputOrderInfo const> const&) @ 0x000000001e99f698
17. src/Processors/QueryPlan/ReadFromMergeTree.cpp:2552: DB::ReadFromMergeTree::spreadMarkRanges(DB::RangesInDataParts&&, std::shared_ptr<DB::MergeTreeIndexBuildContext> const&, unsigned long, DB::ReadFromMergeTree::AnalysisResult&, std::optional<DB::ActionsDAG>&) @ 0x000000001e9b360f
18. src/Processors/QueryPlan/ReadFromMergeTree.cpp:2775: DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x000000001e9b5be7
19. src/Processors/QueryPlan/ISourceStep.cpp:20: DB::ISourceStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000001e93715b
20. src/Processors/QueryPlan/QueryPlan.cpp:207: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001e9700b4
21. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x000000001a7645e9
22. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001a76431c
23. src/Interpreters/executeQuery.cpp:1603: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x000000001aa84042
24. src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001aa7dcb2
25. src/Server/TCPHandler.cpp:743: DB::TCPHandler::runImpl() @ 0x000000001e3428ee
26. src/Server/TCPHandler.cpp:2754: DB::TCPHandler::run() @ 0x000000001e35c224
27. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000241bea07
28. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000241befe5
29. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000002415e17f
30. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000002415b851
31. ? @ 0x0000000000094ac3
```

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed incorrect sharding in `JOIN` optimization when the primary key is sorted in descending order. Resolves #88512.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Details

This PR fixes incorrect sharding in `JOIN` optimization when the primary key is sorted in descending order.

Additionally, this PR adds several debugging helper methods and fixes minor typos and style issues, organized into a separate commit.

Resolves #88512

### CODE REVIEW

File: src/Common/blockDumper.h [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+#include <base/types.h>
+
+namespace DB
+{
+
+class Block;
+class Chunk;
+
+String dumpBlockToJSON(const Block & block);
+String dumpChunkToJSON(const Chunk & chunk, const Block & header);
```
Comment (KochetovNicolai) [inline src/Common/blockDumper.h]: * Let's add `WriteBuffer` version
* Let's add a comment.
* I remember there was a common file for debug printing of different stuff, but I can't find it quickly.

File: src/Processors/QueryPlan/Optimizations/optimizeJoinByShards.cpp [hunk 2]
```diff
@@ -126,8 +126,25 @@ JoinStep::PrimaryKeySharding findCommonPrimaryKeyPrefixByJoinKey(
 
     JoinStep::PrimaryKeySharding sharding;
 
+    bool first = true;
     for (size_t pos = 0; pos < lhs_pk_colum_names.size() && pos < rhs_pk_colum_names.size(); ++pos)
     {
+        bool ldesc = (pos < lhs_pk.reverse_flags.size()) ? lhs_pk.reverse_flags[pos] : false;
+        bool rdesc = (pos < rhs_pk.reverse_flags.size()) ? rhs_pk.reverse_flags[pos] : false;
+        if (ldesc != rdesc)
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/Optimizations/optimizeJoinByShards.cpp:134]: Technically, it's possible to support PKs with a different sorting order.
For now, this small fix is better.

File: src/Processors/Transforms/FilterSortedStreamByRange.cpp [hunk 3]
```diff
@@ -0,0 +1,51 @@
+#include <Processors/Transforms/FilterSortedStreamByRange.h>
+
+#include <Columns/IColumn.h>
+#include <Interpreters/ExpressionActions.h>
+
+namespace DB
+{
+
+FilterSortedStreamByRange::FilterSortedStreamByRange(
```
Comment (KochetovNicolai) [inline src/Processors/Transforms/FilterSortedStreamByRange.cpp:9]: It's a bit tricky to catch. Is there any code change together with moving?

File: src/Common/blockDumper.h (hunk 1 above)
Comment (amosbird) [reply src/Common/blockDumper.h]: > I remember there was a common file for debug printing of different stuff, but I can't find it quickly.

That's iostream_debug_helper which got removed in https://github.com/ClickHouse/ClickHouse/pull/64777

**Review by KochetovNicolai — APPROVED** [review]
Overall LGTM. Please fix fasttests with the changed plan step description.

File: src/Processors/QueryPlan/Optimizations/optimizeJoinByShards.cpp (hunk 2 above)
Comment (amosbird) [reply src/Processors/QueryPlan/Optimizations/optimizeJoinByShards.cpp:134]: > Technically, it's possible to support PKs with a different sorting order.

That will require some quite complex stuff to extend `splitIntersectingPartsRangesIntoLayers`.

File: src/Processors/Transforms/FilterSortedStreamByRange.cpp (hunk 3 above)
Comment (amosbird) [reply src/Processors/Transforms/FilterSortedStreamByRange.cpp:9]: Nope. It's separated to debug this issue so that changing this file won't need to recompile PartSplitter.

**Review by KochetovNicolai — APPROVED** [review]
