### PR TITLE
resolve race in getCSNAndAssert

### LINKED ISSUE #44046: Race in getCSNAndAssert which lead to Logical error: Trying to get CSN for too old TID
Function [getCSNAndAssert](https://github.com/CheSema/ClickHouse/blob/master/src/Interpreters/TransactionVersionMetadata.cpp#L23) looks like
```
1 -- TransactionLog::getCSN(tid_hash);
2 -- csn.load();
3 -- TransactionLog::assertTIDIsNotOutdated(*tid);
4 -- return Tx::UnknownCSN;
```

The race is between 3 and 4. At this place part is able to be commited (see call finalizeCommittedTransaction), CSN is written to Kepper and to the part. Also runUpdatingThread is able to be executed right after, read CSN from commited tx, set new tail_ptr.

Good news this do not lead to isolation break. In release build isVisible returns UnknownCSN which is Ok. Because transaction which called it has to have its start_csn greater that commited_csn in that case.

<details>

<summary> Trace: </summary>

```
2022.12.07 15:47:59.226528 [ 712 ] {} <Fatal> : Logical error: 'Trying to get CSN for too old TID (8596, 41, 78a7c595-d45f-46ed-b876-e310ab94d030), current tail_ptr is 8615, probably it's a bug'.
2022.12.07 15:47:59.228538 [ 184909 ] {} <Fatal> BaseDaemon: ########################################
2022.12.07 15:47:59.228943 [ 184909 ] {} <Fatal> BaseDaemon: (version 22.12.1.1, build id: 6C80C8294ABE73FE243173F669B57D96C9F16AC0) (from thread 712) (no query) Received signal Aborted (6)
2022.12.07 15:47:59.229468 [ 184909 ] {} <Fatal> BaseDaemon: 
2022.12.07 15:47:59.229907 [ 184909 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f2ba419c00b 0x7f2ba417b859 0x1f74149b 0x1f741bbb 0x31df1a53 0x31de88dd 0x31e035d6 0x34120a41 0x33b23029 0x340ecd9a 0x340f3bf4 0x3375bcfe 0x2e67d2b9 0x2e682bba 0x2e684417 0x1f96350d 0x1f96d6a0 0x7f2ba4353609 0x7f2ba4278133
2022.12.07 15:47:59.231121 [ 184909 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7f2ba419c00b in ?
2022.12.07 15:47:59.231848 [ 184909 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f2ba417b859 in ?
2022.12.07 15:47:59.621882 [ 184909 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1f74149b in /usr/bin/clickhouse
2022.12.07 15:48:00.359756 [ 184909 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../src/Common/Exception.cpp:64: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&)
2022.12.07 15:48:00.384186 [ 184909 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x1f741bbb in /usr/bin/clickhouse
2022.12.07 15:48:01.789701 [ 184909 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
2022.12.07 15:48:01.803363 [ 184909 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
2022.12.07 15:48:01.810967 [ 184909 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/../src/Common/Exception.h:32: ~MessageMasked
2022.12.07 15:48:01.812412 [ 184909 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/../src/Common/Exception.h:41: Exception
2022.12.07 15:48:01.823267 [ 184909 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<DB::TransactionID const&, unsigned long&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<DB::TransactionID const&>::type, fmt::v8::type_identity<unsigned long&>::type>, DB::TransactionID const&, unsigned long&) @ 0x31df1a53 in /usr/bin/clickhouse
2022.12.07 15:48:03.034098 [ 184909 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Interpreters/TransactionLog.cpp:576: DB::TransactionLog::assertTIDIsNotOutdated(DB::TransactionID const&) @ 0x31de88dd in /usr/bin/clickhouse
2022.12.07 15:48:03.581353 [ 184909 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../src/Interpreters/TransactionVersionMetadata.cpp:0: DB::getCSNAndAssert(unsigned long, std::__1::atomic<unsigned long>&, DB::TransactionID const*)
2022.12.07 15:48:03.587281 [ 184909 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Interpreters/TransactionVersionMetadata.cpp:220: DB::VersionMetadata::isVisible(unsigned long, DB::TransactionID) @ 0x31e035d6 in /usr/bin/clickhouse
2022.12.07 15:48:07.050605 [ 184909 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../src/Storages/StorageMergeTree.cpp:816: operator()
2022.12.07 15:48:07.051472 [ 184909 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1&>()(std::declval<std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&>(), std::declval<std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&>(), std::declval<DB::MergeTreeTransaction const*>(), std::declval<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*>())) std::__1::__invoke[abi:v15000]<DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*>(DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*&&)
2022.12.07 15:48:07.052394 [ 184909 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:470: bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*>(DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*&&)
2022.12.07 15:48:07.052936 [ 184909 ] {} <Fatal> BaseDaemon: 10.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1, bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)>::operator()[abi:v15000](std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*&&)
2022.12.07 15:48:07.053345 [ 184909 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: bool std::__1::__function::__policy_invoker<bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*)::$_1, bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)>>(std::__1::__function::__policy_storage const*, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*) @ 0x34120a41 in /usr/bin/clickhouse
2022.12.07 15:48:07.672206 [ 184909 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:259: DB::MergeTreeDataMergerMutator::selectPartsToMerge(std::__1::shared_ptr<DB::FutureMergedMutatedPart>, bool, unsigned long, std::__1::function<bool (std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeTransaction const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)> const&, bool, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*) @ 0x33b23029 in /usr/bin/clickhouse
2022.12.07 15:48:09.172346 [ 184909 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Storages/StorageMergeTree.cpp:854: DB::StorageMergeTree::selectPartsToMerge(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::__1::unique_lock<std::__1::mutex>&, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, DB::SelectPartsDecision*) @ 0x340ecd9a in /usr/bin/clickhouse
2022.12.07 15:48:10.487830 [ 184909 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Storages/StorageMergeTree.cpp:1146: DB::StorageMergeTree::scheduleDataProcessingJob(DB::BackgroundJobsAssignee&) @ 0x340f3bf4 in /usr/bin/clickhouse
2022.12.07 15:48:10.643154 [ 184909 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Storages/MergeTree/BackgroundJobsAssignee.cpp:129: DB::BackgroundJobsAssignee::threadFunc() @ 0x3375bcfe in /usr/bin/clickhouse
2022.12.07 15:48:11.009816 [ 184909 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:0: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2e67d2b9 in /usr/bin/clickhouse
2022.12.07 15:48:11.235130 [ 184909 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: DB::BackgroundSchedulePool::threadFunction() @ 0x2e682bba in /usr/bin/clickhouse
2022.12.07 15:48:11.978362 [ 184909 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/../src/Common/ThreadPool.h:197: operator()
2022.12.07 15:48:11.981261 [ 184909 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)
2022.12.07 15:48:11.982628 [ 184909 ] {} <Fatal> BaseDaemon: 17.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&)
2022.12.07 15:48:11.983913 [ 184909 ] {} <Fatal> BaseDaemon: 17.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>::operator()[abi:v15000]()
2022.12.07 15:48:11.985085 [ 184909 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2e684417 in /usr/bin/clickhouse
2022.12.07 15:48:12.283353 [ 184909 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../base/base/wide_integer_impl.h:774: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2022.12.07 15:48:12.283631 [ 184909 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/../base/base/wide_integer_impl.h:1441: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2022.12.07 15:48:12.286795 [ 184909 ] {} <Fatal> BaseDaemon: 18.3. inlined from ./build_docker/../base/base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2022.12.07 15:48:12.287057 [ 184909 ] {} <Fatal> BaseDaemon: 18.4. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
2022.12.07 15:48:12.287379 [ 184909 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x1f96350d in /usr/bin/clickhouse
2022.12.07 15:48:12.911261 [ 184909 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>*)
2022.12.07 15:48:12.915299 [ 184909 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2022.12.07 15:48:12.922392 [ 184909 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../contrib/llvm-project/libcxx/include/thread:297: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x1f96d6a0 in /usr/bin/clickhouse
2022.12.07 15:48:12.930892 [ 184909 ] {} <Fatal> BaseDaemon: 20. ? @ 0x7f2ba4353609 in ?
2022.12.07 15:48:12.932506 [ 184909 ] {} <Fatal> BaseDaemon: 21. clone @ 0x7f2ba4278133 in ?
2022.12.07 15:48:12.932917 [ 184909 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2022.12.07 15:48:20.179876 [ 645 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

</details>

_Originally posted by @alesapin in https://github.com/ClickHouse/ClickHouse/issues/44018#issuecomment-1342539796_

### PR DESCRIPTION
**Pull request by CheSema**
Fixes https://github.com/ClickHouse/ClickHouse/issues/44046
Description see in the issue https://github.com/ClickHouse/ClickHouse/issues/44046

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by CheSema** [comment]
AST Fuzzer segfault (nullptr access) in ColumnToPolygonsConverter<...>::convert(): https://github.com/ClickHouse/ClickHouse/issues/45355

File: src/Interpreters/TransactionLog.cpp [hunk 1]
```diff
@@ -534,36 +534,64 @@ MergeTreeTransactionPtr TransactionLog::tryGetRunningTransaction(const TIDHash &
...
+            return it->second.csn;
+    }
+
+    /// Usually commit csn checked by load memory with memory_order_relaxed option just for performance improvements
+    /// If fast loading fails than getCSN is called.
+    /// There is a race possible, transaction could be committed concurrently. Right before getCSN has been called. In that case tid_to_csn has no tid_hash but commit csn is set.
+    /// In order to be sure, commit csn has to be loaded with memory_order_seq_cst after lookup at tid_to_csn
+    if (failback_with_strict_load_csn)
+        if (CSN maybe_csn = failback_with_strict_load_csn->load())
+            return maybe_csn;
```
Comment (tavplubix) [inline src/Interpreters/TransactionLog.cpp:571]: Actually it's not required. This may happen only if the transaction was committed after we checked `failback_with_strict_load_csn` the first time. However, usually we need a CSN to compare it with something, e.g. with a snapshot. But the snapshot was taken before we checked `failback_with_strict_load_csn` the first time. Therefore, the snapshot was taken before the transaction was committed. So there's not much difference between returning `UnknownCSN` and the actual CSN of the transaction in this case. 

But we can keep this code just in case.

File: src/Interpreters/TransactionLog.cpp [hunk 2]
```diff
@@ -534,36 +534,64 @@ MergeTreeTransactionPtr TransactionLog::tryGetRunningTransaction(const TIDHash &
...
 
     return Tx::UnknownCSN;
 }
 
-void TransactionLog::assertTIDIsNotOutdated(const TransactionID & tid)
+CSN TransactionLog::getCSNAndAssert(const TransactionID & tid, std::atomic<CSN> & failback_with_strict_load_csn)
+{
+    /// failback_with_strict_load_csn is not provided to getCSN
+    /// Becaose it would be checked after assertTIDIsNotOutdated
```
Comment (tavplubix) [inline src/Interpreters/TransactionLog.cpp:579]:
```suggestion
    /// Because it would be checked after assertTIDIsNotOutdated
```

File: src/Interpreters/TransactionLog.cpp [hunk 3]
```diff
@@ -534,36 +534,64 @@ MergeTreeTransactionPtr TransactionLog::tryGetRunningTransaction(const TIDHash &
...
+    if (CSN maybe_csn = getCSN(tid))
+        return maybe_csn;
+
+    assertTIDIsNotOutdated(tid, &failback_with_strict_load_csn);
+
+   /// If transaction is not an outdated then it mayght be already committed
```
Comment (tavplubix) [inline src/Interpreters/TransactionLog.cpp:585]:
```suggestion
   /// If transaction is not outdated then it might be already committed
```

File: src/Interpreters/TransactionLog.cpp [hunk 4]
```diff
@@ -573,6 +601,14 @@ void TransactionLog::assertTIDIsNotOutdated(const TransactionID & tid)
     if (tail <= tid.start_csn)
         return;
 
+    /// At this point of execution tail is lesser that tid.start_csn
+    /// This mean that transaction is either outdated or just has been committed concurrently and the tail moved forward.
+    /// If the second case takes palece transaction's commit csn has to be set.
```
Comment (tavplubix) [inline src/Interpreters/TransactionLog.cpp:606]:
```suggestion
    /// If the second case takes place transaction's commit csn has to be set.
```

**Review by tavplubix — APPROVED** [review]

File: src/Interpreters/TransactionVersionMetadata.cpp [hunk 5]
```diff
@@ -229,7 +209,7 @@ bool VersionMetadata::isVisible(CSN snapshot_version, TransactionID current_tid)
 
     if (removal_lock)
     {
-        removal = getCSNAndAssert(removal_lock, removal_csn);
+        removal = TransactionLog::getCSN(removal_lock, &removal_csn);
```
[the remark this answers is not in the document]
Comment (CheSema) [reply src/Interpreters/TransactionVersionMetadata.cpp:212]: Opps. Nice catch. 
Definitely AndAssert.

[the remark this answers is not in the document]
Comment (CheSema) [reply src/Interpreters/TransactionVersionMetadata.cpp:212]: Rechecked it. Actually no. Just get. Without assert. Here we have only hash of removal log. Old code did no assert if tx_id is null ptr. 

'inline static CSN getCSNAndAssert(TIDHash tid_hash, std::atomic<CSN> & csn, const TransactionID * tid = nullptr)
{
....
if (tid)
        TransactionLog::assertTIDIsNotOutdated(*tid);
....
}
'

**Comment by CheSema** [comment]
test_s3_cluster/test.py::test_parallel_distributed_insert_select_with_schema_inference -- https://github.com/ClickHouse/ClickHouse/pull/46488
