### PR TITLE
Fix joinGetOrNull with not-nullable columns

### LINKED ISSUE #24261: Could you please kindly accept my question about joinGetOrNull - my query does not response.
hi.
query not response !!

[Script-129.txt](https://github.com/ClickHouse/ClickHouse/files/6503753/Script-129.txt)

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix joinGetOrNull with not-nullable columns. This fixes https://github.com/ClickHouse/ClickHouse/issues/24261

Detailed description / Documentation draft:

.

### CODE REVIEW

**Comment by vdimir** [comment]
@mergifyio update

**Review by vdimir — APPROVED** [review]

File: src/Interpreters/HashJoin.cpp [hunk 1]
```diff
@@ -749,8 +750,25 @@ class AddedColumns
         if constexpr (has_defaults)
             applyLazyDefaults();
 
-        for (size_t j = 0, size = right_indexes.size(); j < size; ++j)
-            columns[j]->insertFrom(*block.getByPosition(right_indexes[j]).column, row_num);
+        if (is_join_get)
```
Comment (vdimir) [inline src/Interpreters/HashJoin.cpp:753]: Maybe it can be `constexpr` like `has_defaults`, but I suppose it won't significantly affect performance
