### PR TITLE
Fixes for storage `S3Queue`

### LINKED ISSUE #54998: S3Queue is producing 1k+ ListBlob calls per second
**Describe the unexpected behaviour**
I have a S3Queue table like so:
```sql
CREATE TABLE events_queue (
  `Timestamp` DateTime64(9),
  `SchemaVersion` LowCardinality(String),
  `EventId` String,
  `FullName_Name` LowCardinality(String),
  `FullName_Namespace` LowCardinality(String),
  `Entity_Id` String,
  `Entity_Type` LowCardinality(String),
  `EventData` String
)
ENGINE = S3Queue('[redacted]', '[redacted]', '[redacted]', 'Parquet')
PARTITION BY toYYYYMMDD(`Timestamp`)
ORDER BY (`Timestamp`, `EventId`)
PRIMARY KEY (`Timestamp`, `EventId`)
SETTINGS
  mode = 'unordered',
  keeper_path = '/clickhouse/playfab_s3',
  after_processing = 'delete',
  s3queue_polling_size=5;
 ```

Streaming import works fine, but checking billing on AWS, I see that my egress charges are abnormally high, as well as the number of requests made per second are abnormally high. It looks like ClickHouse is generating thousands of ListBlob calls per second, even though it shouldn't. 

**How to reproduce**
* Which ClickHouse server version to use: 23.8.2
* Create a table with an S3Queue engine
* Watch as the amount of requests made skyrocket 🚀 

**Expected behavior**
ClickHouse should be polling at a more reasonable rate - leaving an S3Queue running for 3 days racked us up nearly $100+ in egress / transaction fees. This is an absurd amount of requests to be making per second and almost amounts to a DoS attack.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Rewrited storage S3Queue completely: changed the way we keep information in zookeeper which allows to make less zookeeper requests, added caching of zookeeper state in cases when we know the state will not change, improved the polling from s3 process to make it less aggressive, changed the way ttl and max set for trached files is maintained, now it is a background process. Added `system.s3queue` and `system.s3queue_log` tables.
Closes https://github.com/ClickHouse/ClickHouse/issues/54998.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 87b9150b8412066d01720fdee0b62fd8172698f1 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54422/87b9150b8412066d01720fdee0b62fd8172698f1/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 1]
```diff
@@ -28,326 +42,875 @@ namespace
...
+    node_metadata.processing_id = getRandomASCIIString(10);
 
-bool S3QueueFilesMetadata::setFileFailed(const String & file_path, const String & exception_message)
+    Coordination::Requests requests;
+
+    requests.push_back(zkutil::makeCreateRequest(zookeeper_processed_path / node_name, "", zkutil::CreateMode::Persistent));
+    requests.push_back(zkutil::makeRemoveRequest(zookeeper_processed_path / node_name, -1));
+
+    requests.push_back(zkutil::makeCreateRequest(zookeeper_failed_path / node_name, "", zkutil::CreateMode::Persistent));
+    requests.push_back(zkutil::makeRemoveRequest(zookeeper_failed_path / node_name, -1));
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:334]: We can use `CheckNotExists` to check if path does not exist if this feature in keeper is enabled. We have function `addCheckNotExistsRequest` for this:
https://github.com/ClickHouse/ClickHouse/blob/eeff98f3a31ffeb13c6e592efd2059bb053298af/src/Common/ZooKeeper/ZooKeeper.h#L723-L737

Comment (kssenii) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:334]: I used it, but in commit https://github.com/ClickHouse/ClickHouse/pull/54422/commits/0ddee6ad6c2d201534761944ce182ac529194837 I reverted back to not using it. Because I need to return different value depending on `responses`, but with `addCheckNotExistsRequest` responses size differs (depending on feature support), and this added complication on checking responses (as I do two `addCheckNotExistsRequest` and in row and then some other request) . So I decided not to use this method as it makes it more complicated to further process the result.

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 2]
```diff
@@ -28,326 +42,875 @@ namespace
...
+    try
     {
-        case S3QueueMode::UNORDERED:
+        if (!zk_client->expired())
         {
-            processed_and_failed_files.merge(getUnorderedProcessedFiles());
-            break;
+            /// Is is possible that we created an ephemeral processing node
+            /// but session expired and someone other created an ephemeral processing node.
+            /// To avoid deleting this new node, check processing_id.
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:706]: I didn't quite understand when it's possible. Can you explain with more details?

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 3]
```diff
@@ -28,326 +42,875 @@ namespace
...
+    {
+        std::string name;
+        NodeMetadata metadata;
+    };
+    auto node_cmp = [](const Node & a, const Node & b)
+    {
+        if (a.metadata.last_processed_timestamp == b.metadata.last_processed_timestamp)
+            return a.metadata.file_path < b.metadata.file_path;
+        else
+            return a.metadata.last_processed_timestamp < b.metadata.last_processed_timestamp;
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:820]: I think we can simply use `std::tie` here
```suggestion
        return std::tie(a.metadata.last_processed_timestamp, a.metadata.file_path) < std::tie(b.metadata.last_processed_timestamp, b.metadata.file_path);
```

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 4]
```diff
@@ -28,326 +42,875 @@ namespace
...
+    {
+        WriteBufferFromOwnString wb;
+        for (const auto & [node, metadata] : sorted_nodes)
+            wb << fmt::format("Node: {}, path: {}, timestamp: {};\n", node, metadata.file_path, metadata.last_processed_timestamp);
+        return wb.str();
+    };
+    LOG_TEST(log, "Checking node limits (max size: {}, max age: {}) for {}", max_set_size, max_set_age_sec, get_nodes_str());
+
+    size_t nodes_to_remove = check_nodes_limit && nodes_limit_exceeded ? nodes.size() - max_set_size : 0;
+    for  (const auto & node : sorted_nodes)
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:857]:
```suggestion
    for (const auto & node : sorted_nodes)
```

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp (hunk 2 above)
Comment (kssenii) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:706]: Let' say we have `clickhouse-server1` and `clickhouse-server2`, create `S3Queue` table on both servers pointing to the same keeper path. Let's say server 1 started processing `file1`, but got keeper session expired before finishing. Expired session leads to expiration of ephemeral "processing" node. Server 2 sees that there is no "processing" nor "failed" nor "processed" node for `file1`, so it will create a "processing" node itself. Then server1 restores keeper connection, it knows from memory that it was processing `file1` and did not finish. So it try to finalize it with either "failed" or "finished" state. But it will be incorrect if the described scenario.

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 5]
```diff
@@ -28,326 +42,875 @@ namespace
...
+    auto node_cmp = [](const Node & a, const Node & b)
+    {
+        if (a.metadata.last_processed_timestamp == b.metadata.last_processed_timestamp)
+            return a.metadata.file_path < b.metadata.file_path;
+        else
+            return a.metadata.last_processed_timestamp < b.metadata.last_processed_timestamp;
+    };
+
+    /// Ordered in ascending order of timestamps.
+    std::multiset<Node, decltype(node_cmp)> sorted_nodes(node_cmp);
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:824]: Why `multiset`?

File: src/Storages/S3Queue/S3QueueSource.h [hunk 6]
```diff
@@ -2,125 +2,101 @@
...
-        std::shared_ptr<IIterator> file_iterator_,
+        const Block & header_,
+        std::unique_ptr<StorageS3Source> internal_source_,
         std::shared_ptr<S3QueueFilesMetadata> files_metadata_,
         const S3QueueAction & action_,
-        size_t download_thread_num);
+        RemoveFileFunc remove_file_func_,
+        const NamesAndTypesList & requested_virtual_columns_,
+        ContextPtr context_,
+        const std::atomic<bool> &  shutdown_called_,
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueSource.h:68]:
```suggestion
        const std::atomic<bool> & shutdown_called_,
```

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 7]
```diff
@@ -28,326 +42,875 @@ namespace
...
+                    LOG_WARNING(log, "Cannot remove {} since processing id changed: {} -> {}",
+                                zk_node_path, processing_id, node_metadata.processing_id);
+            }
+            else
+                LOG_DEBUG(log, "Cannot remove {}, node doesn't exist, "
+                          "probably because of session expiration", zk_node_path);
+
+            /// TODO: this actually would mean that we already processed (or partially processed)
+            /// the data but another thread will try processing it again and data can be duplicated.
+            /// This can be solved via persistenly saving last processed offset in the file.
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:737]: Saving offsets won't work for formats with metadata like Parquet/ORC/Arrow/Avro, because we cannot just start reading from some offset in file

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 8]
```diff
@@ -28,326 +42,875 @@ namespace
...
+                    "this could be a result of expired zookeeper session", path);
+        return;
+    }
+
+    /// So file is retriable.
+    /// Let's do an optimization here.
+    /// Instead of creating a persistent /failed/node_hash node
+    /// we create a persistent /failed/node_hash.retriable node.
+    /// This allows us to make less zookeeper requests as we avoid checking
+    /// the number of already done retries in trySetFileAsProcessing.
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:607]: Maybe I missed something but I don't see where we process retriable files in `trySetFileAsProcessing`

Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:607]: AFAIU, In case when we succeded after some retry, we don't delete nodes `/failed/node_hash.retriable`, so they can accumulate there and comsume some memory in keeper.

File: src/Storages/S3Queue/S3QueueSource.cpp [hunk 9]
```diff
@@ -218,61 +118,86 @@ String StorageS3QueueSource::getName() const
...
+        }
+
+        if (shutdown_called)
+        {
+            if (processed_rows_from_file)
+            {
+                /// We could delay shutdown until files, which already started processing before the shutdown, finished.
+                /// But if files are big and `s3queue_processing_threads_num` is not small, it can take a significant time.
+                /// Anyway we cannot do anything in case of SIGTERM, so destination table must anyway support deduplication,
+                /// so here we will rely on it here as well.
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueSource.cpp:139]: Also in case of exception during parsing we could already insert some data into destination table and after retries there will be duplications. We should defenitely add a note about it in the documentation. And I don't think we can solve it by saving file offsets that we processed because of formats with metadata and random access like Parquet/ORC/Arrow. Maybe we can store processed rows for each file and when we start reading the file again, we can skip already processed rows by just ignoring them here after `reader->pull()` (also in future we can add optimization for it and add method skipRows(size_t rows) for input formats because most formats can skip rows fast enough). Or combine both methods (saving offset and saving processed rows) and use one of them depending on format (like, for CSV/TSV/JSONEachRow/etc we can save offset and start reading from it, and for Parquet/ORC/etc we can save previrously read rows and skip them before returning blocks (and for such formats skipping rows can be optimized using their metadata).

File: src/Storages/S3Queue/S3QueueSource.cpp [hunk 10]
```diff
@@ -218,61 +118,86 @@ String StorageS3QueueSource::getName() const
...
+                LOG_TEST(log, "Read {} rows from file: {}", chunk.getNumRows(), reader.getPath());
+
+                file_status->processed_rows += chunk.getNumRows();
+                processed_rows_from_file += chunk.getNumRows();
+
+                VirtualColumnUtils::addRequestedPathAndFileVirtualsToChunk(chunk, requested_virtual_columns, reader.getPath());
+                return chunk;
             }
         }
         catch (const Exception & e)
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueSource.cpp:170]: I think we should catch all exceptions, not only `DB::Exception` here

File: src/Storages/S3Queue/StorageS3Queue.cpp [hunk 11]
```diff
@@ -174,83 +194,69 @@ Pipe StorageS3Queue::read(
...
+    const StorageSnapshotPtr & storage_snapshot,
+    ASTPtr query,
+    size_t max_block_size,
+    ContextPtr local_context)
 {
-    if (task)
-        task->holder->activateAndSchedule();
-}
+    auto configuration_snapshot = updateConfigurationAndGetCopy(local_context);
+    auto file_iterator = createFileIterator(local_context, query);
```
Comment (Avogar) [inline src/Storages/S3Queue/StorageS3Queue.cpp:226]: I see we create a separate file oterator for each source. So all sources will iterate through the same files and coordinate through ZK. I think it will be more optimal to share single file iterator across all sources, it will reduce the amount of requests to ZK for the same files

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp [hunk 12]
```diff
@@ -28,326 +42,875 @@ namespace
...
+        if (exists)
+        {
+            if (!res.empty())
+            {
+                auto metadata = NodeMetadata::fromString(res);
+                if (metadata.file_path >= path)
+                {
+                    /// Here we get in the case that maximum processed file is bigger than ours.
+                    /// This is possible to achieve in case of parallel processing
+                    /// but for local processing we explicitly disable parallel mode and do everything in a single thread
```
Comment (Avogar) [inline src/Storages/S3Queue/S3QueueFilesMetadata.cpp:516]: Can we also create two S3Queue storages with the same zk path on one instance?

Comment (Avogar) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:516]: Do we have other problems except retries with parallel processing in Ordered mode? 
If only retries, maybe instead of setting `s3queue_processing_threads_num` always to 1, we can set it to 1 only if retries were enabled? Or even throw an exception if retries are enabled in Ordered mode with a message that it can be broken in distributed scenario (and allow to force retries with ordered mode, so we will set threads_num to 1 and won't care about distributed case). Or maybe you already know how to solve this problem and we can just keep it as is and fix later.

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp (hunk 2 above)
Comment (Avogar) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:706]: So we need to think about deduplication here. If I understood correctly, the solution is to modify read offset in zk (or read number of rows, see my comments below) after each read block in source, so if we cannot modify it because of session expired, we don't insert this block. Right?

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp (hunk 12 above)
Comment (kssenii) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:516]: > Or maybe you already know how to solve this problem and we can just keep it as is and fix later.

Yeah, I have an idea. I think this can be solved if ordered mode was implemented as a combo of ordered and unordered modes. Let's say there is a setting `processing_window`, equal to for, example, 100. This window defines a range of files. Within this window we process files in parallel and do not process any other files until all files within this window are marked as either failed or processed. While we process a window of files we keep track of them in keeper like we track files in unordered mode. But once the full window is processed, we change the information in keeper to contain only max_processed_file (what we aim to do in ordered mode).

> Do we have other problems except retries with parallel processing in Ordered mode?

If server got terminated with SIGABRT and we did not finish processing file `file1`, but another thread already processed `file2`, then on restart we'll think we already processed `file1` (even though we didn't). But this issue can be also solved by my idea described above.

File: src/Storages/S3Queue/S3QueueSource.cpp (hunk 9 above)
Comment (kssenii) [reply src/Storages/S3Queue/S3QueueSource.cpp:139]: > Maybe we can store processed rows for each file and when we start reading the file again, we can skip already processed rows by just ignoring them here after reader->pull() (also in future we can add optimization for it and add method skipRows(size_t rows) for input formats because most formats can skip rows fast enough). 

Good idea. Though if we update processed rows count in keeper for every block, it will result in too many keeper requests...

> We should defenitely add a note about it in the documentation. 

Will do 👌🏻 .

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp (hunk 2 above)
Comment (kssenii) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:711]: Yeah, also there is a case that if we will update the counter in keeper after we read the block and before we pushed the block to mv, then there could be an exception during push and we get incorrect state in keeper, then to make things even worse - keeper session expires - so we cannot fix keeper state without a potential race with another server having s3queue starting processing the same file, so it is again not straightforward what to do here.

So (at least for now) I'd better document that the user is strongly recommended to use destination table of S3Queue MV with table engine which supports deduplication. Then occasional duplicated is not a problem.

File: src/Storages/S3Queue/S3QueueFilesMetadata.cpp (hunk 12 above)
Comment (kssenii) [reply src/Storages/S3Queue/S3QueueFilesMetadata.cpp:517]: > Yeah, I have an idea. ...

Started implementing it. I think it will be better to be put in a separate PR, after this one is merged, for easier review.

**Review by Avogar — APPROVED** [review]

**Comment by kssenii** [comment]
> Integration tests (asan, analyzer) [1/6] — fail: 3

test_zookeeper_config
test_postgresql_replica_database_engine_2 - https://github.com/ClickHouse/ClickHouse/pull/55772

> Integration tests (release) [4/4] — fail: 1

test_delayed_replica_failover/test.py::test

> Integration tests (tsan) [1/6] — fail: 1

test_postgresql_replica_database_engine_2 - https://github.com/ClickHouse/ClickHouse/pull/55772

> Stateless tests (release, analyzer) — fail: 1

02479_race_condition_between_insert_and_droppin_mv
00992_system_parts_race_condition_zookeeper_long

**Comment by kssenii** [comment]
> Integration tests (release) [4/4] — fail: 1

test_delayed_replica_failover/test.py::test

> Stateless tests (release, DatabaseReplicated) [4/4] — fail: 1

00385_storage_file_and_clickhouse-local_app_long

> Stateless tests (release, analyzer) — fail: 1

02479_race_condition_between_insert_and_droppin_mv
