### PR TITLE
Fix lost parameters of aggregate functions

### LINKED ISSUE #26196: 21.5.8, 21.6 & 21.7 break *Array aggregation types
Updating existing table to 21.6 and 21.7 breaks *Array aggregation types. The table contains mater view with the following column

````
strings AggregateFunction(topKArray(10), Array(String)),
````

When trying to insert into the table I get the following error:

```
Conversion from AggregateFunction(topKArray, Array(String)) to AggregateFunction(topKArray(10), Array(String)) is not supported
```

As you see the type has changed from `topKArray(10)` to `topKArray`. I can update the mater view schema to use the new type and the problem goes away, but it is not clear whether this change was intentional because only `*Array` agg functions are affected.

It is the same with `groupUniqArrayArray` and even worse, because I can't cast `groupUniqArrayArray(1000)` to `groupUniqArrayArray`:

```
MODIFY COLUMN strings AggregateFunction(groupUniqArrayArray, Array(String))

Conversion from AggregateFunction(groupUniqArrayArray(1000), Array(String)) to AggregateFunction(groupUniqArrayArray, Array(String)) is not supported
```

The last working version is 21.5.7.9. The next 21.5.8 version is broken.

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Aggregate function parameters might be lost when applying some combinators causing exceptions like `Conversion from AggregateFunction(topKArray, Array(String)) to AggregateFunction(topKArray(10), Array(String)) is not supported`. It's fixed. Fixes #26196 and  #26433

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

**Comment by qoega** [comment]
Fuzzer fail seems relevant

File: src/AggregateFunctions/AggregateFunctionMerge.h [hunk 1]
```diff
@@ -29,15 +29,19 @@ class AggregateFunctionMerge final : public IAggregateFunctionHelper<AggregateFu
...
 
         if (!data_type || data_type->getFunctionName() != nested_func->getName())
-            throw Exception("Illegal type " + argument->getName() + " of argument for aggregate function " + getName(),
-                ErrorCodes::ILLEGAL_TYPE_OF_ARGUMENT);
+            throw Exception(ErrorCodes::ILLEGAL_TYPE_OF_ARGUMENT, "Illegal type {} of argument for aggregate function {}",
+                            argument->getName(), getName());
+
+        if (data_type->getParameters() != getParameters())
+            throw Exception(ErrorCodes::ILLEGAL_TYPE_OF_ARGUMENT, "Illegal type {} of argument for aggregate function {}: "
+                            "parameters mismatch", argument->getName(), getName());
```
Comment (tavplubix) [inline src/AggregateFunctions/AggregateFunctionMerge.h:44]: I'm not sure that it will not break backward compatibility in some obscure way

**Comment by tavplubix** [comment]
> Fuzzer fail seems relevant

Actually it's not, new test has found another issue. Fix: #26847
