### PR TITLE
Fix function `hasAllTokens` with empty array argument

### LINKED ISSUE #93315: Logical error: Bad cast from type A to B (STID: 4101-53dc)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: Bad cast from type A to B (STID: 4101-53dc)
CI report: [BuzzHouse (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=6c780e307c9eb38cb4878f1d3477222bd0bf0e10&name_0=MasterCI&name_1=BuzzHouse%20%28amd_ubsan%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiBCYWQgY2FzdCBmcm9tIHR5cGUgQSB0byBCIChTVElEOiA0MTAxLTUzZGMpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQnV6ekhvdXNlIChhbWRfdWJzYW4pJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBBTkQgaGVhZF9yZWYgPSAnbWFzdGVyJykgT1IgKHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCBBTkQgYmFzZV9yZWYgPSAnJykpCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
Error:
Logical error: 'Bad cast from type DB::ColumnNothing to DB::ColumnString'.
---

Stack trace:
pthread_kill@@GLIBC_2.34 @ 0x00000000000969fd
raise @ 0x0000000000042476
__lgamma_r_finite @ 0x00000000000287f3
src/Common/Exception.cpp:57: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x00000000203000dd
src/Common/Exception.cpp:90: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x0000000020300eff
src/Common/Exception.cpp:143: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000020301272
./src/Common/Exception.h:172: DB::Exception::Exception(String&&, int, String, bool) @ 0x0000000013e89ce3
./src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000013e89281
./src/Common/Exception.h:190: DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x0000000013e885ef
./src/Common/typeid_cast.h:31: T typeid_cast<DB::ColumnString const&, DB::IColumn const>(DB::IColumn const&) @ 0x00000000155c12e4
inlined from ./src/Columns/IColumn.h:835: DB::ColumnString const& DB::checkAndGetColumn<DB::ColumnString>(DB::IColumn const&)
src/Functions/hasAnyAllTokens.cpp:391: DB::FunctionHasAnyAllTokens<DB::traits::HasAllTokensTraits>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000002e9a8f32
./src/Functions/IFunction.h:446: DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000013e87a0f
src/Functions/IFunctionAdaptors.cpp:16: DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000261c1d57
src/Functions/IFunction.cpp:351: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000261b75a5
src/Functions/IFunction.cpp:177: DB::IExecutableFunction::defaultImplementationForConstantArguments(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000261b6e84
src/Functions/IFunction.cpp:343: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000261b755a
src/Functions/IFunction.cpp:426: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000261b9288
src/Functions/IFunction.cpp:565: DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000261bad9c
src/Functions/IFunction.cpp:474: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000261ba309
src/Analyzer/Resolve/resolveFunction.cpp:1440: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x0000000028661b8c
src/Analyzer/Resolve/QueryAnalyzer.cpp:2895: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x00000000282e3c95
src/Analyzer/Resolve/QueryAnalyzer.cpp:3046: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x00000000282e305a
src/Analyzer/Resolve/resolveFunction.cpp:673: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x000000002865c906
src/Analyzer/Resolve/QueryAnalyzer.cpp:2895: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x00000000282e3c95
src/Analyzer/Resolve/QueryAnalyzer.cpp:3046: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x00000000282e305a
src/Analyzer/Resolve/QueryAnalyzer.cpp:3378: DB::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000283093e9
src/Analyzer/Resolve/QueryAnalyzer.cpp:4849: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x00000000282dc079
src/Analyzer/Resolve/QueryAnalyzer.cpp:138: DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x00000000282da9b8
src/Analyzer/Resolve/QueryAnalysisPass.cpp:18: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x00000000282d9fd4
src/Analyzer/QueryTreePassManager.cpp:194: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>&) @ 0x00000000283594ec
src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:170: DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x0000000029448aae
src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:184: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000029446b19
./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:759: std::unique_ptr<DB::InterpreterSelectQueryAnalyzer, std::default_delete<DB::InterpreterSelectQueryAnalyzer>> std::make_unique[abi:ne210105]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, 0>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000002944e493
src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:393: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>::type std::__invoke[abi:ne210105]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:334: std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__invoke_void_return_wrapper<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>>, false>::__call[abi:ne210105]<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__invoke_r[abi:ne210105]<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>>, DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&>(DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0&, DB::InterpreterFactory::Arguments const&)
./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000002944deeb
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Interpreters/InterpreterFactory.cpp:408: DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x00000000293df581
src/Interpreters/executeQuery.cpp:1670: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000002986acea
src/Interpreters/executeQuery.cpp:1955: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000298660c7
src/Server/TCPHandler.cpp:774: DB::TCPHandler::runImpl() @ 0x000000002f1d00c2
src/Server/TCPHandler.cpp:2867: DB::TCPHandler::run() @ 0x000000002f1f331c
base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000034e474cc
base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000034e47ddc
base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000034dd0bf4
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed handling of empty array as a second argument in `hasAllTokens` and `hasAnyTokens` functions.

Fixes #93315.

### CODE REVIEW

File: tests/queries/0_stateless/03780_has_all_tokens_empty_array.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
+SET enable_full_text_index = 1;
+
+SELECT sum(hasAllTokens('', ''));
```
Comment (CurtizJ) [inline tests/queries/0_stateless/03780_has_all_tokens_empty_array.sql:3]: It is wrong BTW. It should return 1, but I don't want to touch it in this PR.

**Review by Ergus — APPROVED** [review]
Thanks for the quick fix
