### PR TITLE
Fix deserialization of variant discriminators with basic format in compact parts

### LINKED ISSUE #78468: Assertion error with `use_compact_variant_discriminators_serialization = 0` and Variant type
### Describe the bug

This issue requires a few medium sized inserts to reproduce and a Debug build.

### How to reproduce

Run statements from: [issue.txt](https://github.com/user-attachments/files/19535578/issue.txt) The SELECT will trigger:
```
clickhouse: src/Common/PODArray.h:385:
const T &DB::PODArray<unsigned long, 4096, Allocator<false, false>, 63, 64>::operator[](ssize_t) const [T = unsigned long, initial_bytes = 4096, TAllocator = Allocator<false, false>, pad_right_ = 63, pad_left_ = 64]: Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))' failed.
```

### Error message and/or stacktrace

Stack trace:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=0) at nptl/pthread_kill.c:44
#1  __pthread_kill_internal (threadid=<optimized out>, signo=6) at nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at nptl/pthread_kill.c:89
#3  0x00007ffff7c4519e in __GI_raise (sig=sig@entry=6) at .sysdeps/posix/raise.c:26
#4  0x00007ffff7c28902 in __GI_abort () at stdlib/abort.c:79
#5  0x00007ffff7c2881e in __assert_fail_base (fmt=0x7ffff7dde2a0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=warning: (Internal error: pc 0x55555939b4ce in read in CU, but not in symtab.)
    at assert/assert.c:96
#6  0x00007ffff7c3b7c7 in __assert_fail (assertion=warning: (Internal error: pc 0x55555939b4ce in read in CU, but not in symtab.)
    at assert/assert.c:105
#7  0x000055556ae289bc in DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>::operator[] (this=<optimized out>, n=<optimized out>) at src/Common/PODArray.h:385
#8  DB::ColumnString::doInsertFrom (this=0x7ffd387780a0, src_=..., n=18446744073709551520) at src/Columns/ColumnString.h:162
#9  0x000055556c12a4d9 in DB::IColumn::insertFrom (this=0x7ffd69f16600, src=..., n=8193) at src/Columns/IColumn.h:199
#10 DB::AggregatingSortedAlgorithm::AggregatingMergedData::startGroup (this=this@entry=0x7ffeb35988c0, raw_columns=..., row=8193)
    at src/Processors/Merges/Algorithms/AggregatingSortedAlgorithm.cpp:174
#11 0x000055556c12bb3c in DB::AggregatingSortedAlgorithm::merge (this=0x7ffeb35986f8) at src/Processors/Merges/Algorithms/AggregatingSortedAlgorithm.cpp:324
#12 0x000055556b6d45ff in DB::IMergingTransform<DB::AggregatingSortedAlgorithm>::work (this=0x7ffeb3598518) at src/Processors/Merges/IMergingTransform.h:137
#13 0x000055556bdb852f in DB::executeJob (node=0x7ffeb354ea00, read_progress_callback=0x7ffeb3547750) at src/Processors/Executors/ExecutionThreadContext.cpp:53
#14 DB::ExecutionThreadContext::executeTask (this=0x7ffd48efb100) at src/Processors/Executors/ExecutionThreadContext.cpp:102
#15 0x000055556bdad625 in DB::PipelineExecutor::executeStepImpl (this=this@entry=0x7ffeb358b418, thread_num=<optimized out>, yield_flag=yield_flag@entry=0x0)
    at src/Processors/Executors/PipelineExecutor.cpp:296
#16 0x000055556bdad8de in DB::PipelineExecutor::executeSingleThread (this=0x19954b, this@entry=0x7ffeb358b418, thread_num=1677460)
    at src/Processors/Executors/PipelineExecutor.cpp:262
#17 0x000055556bdae35f in DB::PipelineExecutor::spawnThreadsImpl()::$_0::operator()() const (this=0x7ffd5f5fdae0) at src/Processors/Executors/PipelineExecutor.cpp:416
#18 std::__1::__invoke[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl()::$_0&>(DB::PipelineExecutor::spawnThreadsImpl()::$_0&) (__f=...)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149
#19 std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl()::$_0&>(DB::PipelineExecutor::spawnThreadsImpl()::$_0&) (__args=...)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224
#20 std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()>::operator()[abi:se190107]() (this=0x7ffd5f5fdae0)
    at contrib/llvm-project/libcxx/include/__functional/function.h:210
#21 std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl()::$_0, void ()> >(std::__1::__function::__policy_storage const*) (
    __buf=<optimized out>) at contrib/llvm-project/libcxx/include/__functional/function.h:610
#22 0x0000555565294973 in std::__1::__function::__policy_func<void ()>::operator()[abi:se190107]() const (this=0x7ffd331efc20)
    at contrib/llvm-project/libcxx/include/__functional/function.h:716
#23 std::__1::function<void()>::operator() (this=0x7ffd331efc20) at contrib/llvm-project/libcxx/include/__functional/function.h:989
#24 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::worker (this=this@entry=0x7ffd5f5fdab0) at src/Common/ThreadPool.cpp:799
#25 0x000055556529a7e2 in std::__1::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*&, , void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*&) (__f=<optimized out>, __a0=<optimized out>)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#26 std::__1::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&, std::__1::__tuple_indices<0ul>) (
    __f=<optimized out>, __t=...) at contrib/llvm-project/libcxx/include/tuple:1354
#27 std::__1::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&)(), std::__1::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>&) (__f=<optimized out>, __t=...)
    at contrib/llvm-project/libcxx/include/tuple:1358
#28 ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::ThreadFromThreadPool*&&)::{lambda()#1}::operator()() (this=0x7ffd48efd080)
    at src/Common/ThreadPool.h:312
#29 0x00005555652920b2 in std::__1::__function::__policy_func<void ()>::operator()[abi:se190107]() const (this=0x7ffd331f0210)
    at contrib/llvm-project/libcxx/include/__functional/function.h:716
#30 std::__1::function<void()>::operator() (this=0x7ffd331f0210) at contrib/llvm-project/libcxx/include/__functional/function.h:989
#31 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (this=0x7ffd5524b680) at src/Common/ThreadPool.cpp:809
#32 0x00005555652983a0 in std::__1::__invoke[abi:se190107]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) (__f=<optimized out>, __a0=<optimized out>)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#33 std::__1::__thread_execute[abi:se190107]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (__t=...) at contrib/llvm-project/libcxx/include/__thread/thread.h:192
#34 std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=<optimized out>) at contrib/llvm-project/libcxx/include/__thread/thread.h:201
#35 0x00007ffff7ca1e2e in start_thread (arg=<optimized out>) at nptl/pthread_create.c:447
#36 0x00007ffff7d33a4c in __GI___clone3 () at .sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix deserialization of variant discriminators with basic format in compact parts. It was introduced in https://github.com/ClickHouse/ClickHouse/pull/55518.

Closes https://github.com/ClickHouse/ClickHouse/issues/78468

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/DataTypes/Serializations/SerializationVariant.cpp [hunk 1]
```diff
@@ -452,12 +452,15 @@ void SerializationVariant::deserializeBinaryBulkWithMultipleStreams(
     {
         variant_state = checkAndGetState<DeserializeBinaryBulkStateVariant>(state);
         auto * discriminators_state = checkAndGetState<DeserializeBinaryBulkStateVariantDiscriminators>(variant_state->discriminators_state);
+        /// Now we are sure that discriminators are not in cache and we can save the size of discriminators now to know how
+        /// many discriminators were actually deserialized to iterate over them later to calculate limits for variants.
+        variant_state->num_rows_read = col.getLocalDiscriminatorsPtr()->size();
```
Comment (divanik) [inline src/DataTypes/Serializations/SerializationVariant.cpp:457]: Why could variant_state->num_rows_read != col.getLocalDiscriminatorsPtr()->size() before? Are state and column not maintained consistently to each over?

Comment (Avogar) [reply src/DataTypes/Serializations/SerializationVariant.cpp:457]: It can happein in Compact parts. There we serialize each granule of the data independently and create new deserialization states per each granule. But we can use the same column with data for multiple granules with different limit/offset values.
So when we serialize data from the middle of the column and have newly created deserialization state `variant_state->num_rows_read` will be 0.

**Review by divanik — APPROVED** [review]
