### PR TITLE
Fix materialised postgres `table overrides` for partition by, etc

### LINKED ISSUE #35048: MaterializedPostgreSQL Table OVERRIDE
Is the table override actually working for PARTITION BY?
Any attempt like:
**create database db
engine =MaterializedPostgreSQL ('ip:port,'pg_db','use','password')
SETTINGS materialized_postgresql_schema_list ='schema'
TABLE OVERRIDE table1 (partition by toYYYYMMDD(timestamp));**

while not giving any error in the logfiles, it doesn't create the partitions for the ch table either.
By the look of it while writing the table structure, the TABLE OVERRIDE is not considered.

__ATTACH TABLE _ UUID '399f1793-1006-4767-91a8-b6c9240bc118'
(
col1 Nullable(Int64),
col2 DateTime64(6),
col3 Int32,
_sign Int8 MATERIALIZED 1,
_version UInt64 MATERIALIZED 1
)
ENGINE = ReplacingMergeTree(version)
ORDER BY (col2, col3)
SETTINGS index_granularity = 8192_

On postgres side it doesn't matter if the table to be replicated is partitioned or not.

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix materialised postgres `table overrides` for partition by, etc. Closes https://github.com/ClickHouse/ClickHouse/issues/35048.

### CODE REVIEW

File: src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp [hunk 1]
```diff
@@ -502,6 +500,9 @@ ASTPtr StorageMaterializedPostgreSQL::getCreateNestedTableQuery(
 
     create_table_query->set(create_table_query->storage, storage);
 
+    if (table_override)
+        applyTableOverrideToCreateQuery(*table_override, create_table_query.get());
```
Comment (tavplubix) [inline src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp:504]: Hm, seems like it's possible to override `_sign` and `_version` columns now :)
But it's ok if user will get some strange error on attempt to do it.

**Review by tavplubix — APPROVED** [review]

File: src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp (hunk 1 above)
Comment (kssenii) [reply src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp:516]: Added a check for it.
