### PR TITLE
Fix lost blobs after dropping a replica with broken detached parts

### LINKED ISSUE #57985: CI/s3: The specified key does not exist between 2 different tables
Report: https://s3.amazonaws.com/clickhouse-test-reports/57895/1e8397f437eda15a432f4e70ed0e563c07a20bfe/stateless_tests__tsan__s3_storage__[1_5].html

If I look into the cache by path `test/rjr/cexuyczxgttyhlaxwjjtigfmterhb`:

```
$ grep "test/rjr/cexuyczxgttyhlaxwjjtigfmterhb" clickhouse-server.log
2023.12.16 00:51:02.423057 [ 1261 ] {} <Debug> S3ObjectStorage: Objects with paths [test/vpl/nskzxxkwdwrqxpcbqtarxgjbutmxf, test/opy/odkodqeqxludphrtzelcwymrayduk, test/cky/hbrdfzaupykmjpepyicfxkyxlyubc, test/ptw/obnzkodjkrsqwwghwfnmnlppslmoa, test/ppr/djdzvdrrjxafiekckcarteyyiumki, test/pjo/xmskflgpkmtebsnsyvslqunpufmeg, test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, test/frl/kkbculglnyrrjbbxpmlxtgixhvhmz, test/hts/yxqmccvafadzoznybdiqgvqzudomk, test/xtv/xmeqfktjoikxrvssevmbgybznicxk, test/ddr/cptsakagmyqlgvvhrakjlxvfkagge, test/szc/foyspigvwldppaajihnkrxmrnygiw, test/nxq/grmvsbfsvuxhqcvrvdxbbyatbxnxt, test/wri/flodwekgwxeikfjlcqcmexmpkntlf, test/whs/lyxrdwjdurldrqparqgejxlwgvyqa, test/lhv/bltxdvylipgqxndmebfczoerthkxt, test/bjp/qgvrfpuplohldkakezblmrofkgmxi] were removed from S3
2023.12.16 00:51:03.132739 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> ReadBufferFromS3: Caught exception while reading S3 object. Bucket: test, Key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, Version: Latest, Offset: 0, Attempt: 1/4, Message: The specified key does not exist.
2023.12.16 00:51:03.263653 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Error> executeQuery: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, current write offset: 0, caller id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/019/0190e826-e367-42af-9ef0-f49fbfd62e73/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR) (version 23.12.1.1) (from [::1]:55778) (comment: 01079_parallel_alter_detach_table_zookeeper.sh) (in query: SELECT SUM(toUInt64(value1)) > 1725 FROM concurrent_alter_detach_2), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:03.328568 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Error> TCPHandler: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, current write offset: 0, caller id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/019/0190e826-e367-42af-9ef0-f49fbfd62e73/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:05.674279 [ 7727 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Debug> ReadBufferFromS3: Caught exception while reading S3 object. Bucket: test, Key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, Version: Latest, Offset: 0, Attempt: 1/4, Message: The specified key does not exist.
2023.12.16 00:51:05.677074 [ 67566 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Error> executeQuery: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, current write offset: 0, caller id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/726/7266a5d7-1810-49ea-bafa-df2983068e25/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_3 (7266a5d7-1810-49ea-bafa-df2983068e25) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR) (version 23.12.1.1) (from [::1]:55820) (comment: 01079_parallel_alter_detach_table_zookeeper.sh) (in query: SELECT SUM(toUInt64(value1)) > 1725 FROM concurrent_alter_detach_3), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:05.688686 [ 67566 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Error> TCPHandler: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, current write offset: 0, caller id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/726/7266a5d7-1810-49ea-bafa-df2983068e25/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_3 (7266a5d7-1810-49ea-bafa-df2983068e25) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:08.505506 [ 29380 ] {} <Debug> S3ObjectStorage: Objects with paths [test/pjo/xmskflgpkmtebsnsyvslqunpufmeg, test/ppr/djdzvdrrjxafiekckcarteyyiumki, test/bjp/qgvrfpuplohldkakezblmrofkgmxi, test/frl/kkbculglnyrrjbbxpmlxtgixhvhmz, test/lhv/bltxdvylipgqxndmebfczoerthkxt, test/opy/odkodqeqxludphrtzelcwymrayduk, test/ptw/obnzkodjkrsqwwghwfnmnlppslmoa, test/ddr/cptsakagmyqlgvvhrakjlxvfkagge, test/nxq/grmvsbfsvuxhqcvrvdxbbyatbxnxt, test/hts/yxqmccvafadzoznybdiqgvqzudomk, test/xtv/xmeqfktjoikxrvssevmbgybznicxk, test/whs/lyxrdwjdurldrqparqgejxlwgvyqa, test/wri/flodwekgwxeikfjlcqcmexmpkntlf, test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, test/cky/hbrdfzaupykmjpepyicfxkyxlyubc, test/szc/foyspigvwldppaajihnkrxmrnygiw, test/vpl/nskzxxkwdwrqxpcbqtarxgjbutmxf] were removed from S3
```

By key (`da366c44d09c6c63acd59f389dc76a96`):
```

$ grep da366c44d09c6c63acd59f389dc76a96 clickhouse-server.log
2023.12.16 00:51:02.413412 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: da366c44d09c6c63acd59f389dc76a96, offset: 0, size: 181
2023.12.16 00:51:02.413512 [ 1261 ] {} <Debug> CacheMetadata: Key da366c44d09c6c63acd59f389dc76a96 is removed from metadata
2023.12.16 00:51:03.133234 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> CacheMetadata: Remove from cache. Key: da366c44d09c6c63acd59f389dc76a96, offset: 0, size: 0
2023.12.16 00:51:03.133334 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> CacheMetadata: Submitting key da366c44d09c6c63acd59f389dc76a96 for removal
2023.12.16 00:51:03.133534 [ 803 ] {} <Debug> CacheMetadata: Key da366c44d09c6c63acd59f389dc76a96 is removed from metadata
2023.12.16 00:51:03.263653 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Error> executeQuery: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, current write offset: 0, caller id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/019/0190e826-e367-42af-9ef0-f49fbfd62e73/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR) (version 23.12.1.1) (from [::1]:55778) (comment: 01079_parallel_alter_detach_table_zookeeper.sh) (in query: SELECT SUM(toUInt64(value1)) > 1725 FROM concurrent_alter_detach_2), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:03.328568 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Error> TCPHandler: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, current write offset: 0, caller id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/019/0190e826-e367-42af-9ef0-f49fbfd62e73/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:05.674632 [ 7727 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Debug> CacheMetadata: Remove from cache. Key: da366c44d09c6c63acd59f389dc76a96, offset: 0, size: 0
2023.12.16 00:51:05.674687 [ 7727 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Debug> CacheMetadata: Submitting key da366c44d09c6c63acd59f389dc76a96 for removal
2023.12.16 00:51:05.674798 [ 803 ] {} <Debug> CacheMetadata: Key da366c44d09c6c63acd59f389dc76a96 is removed from metadata
2023.12.16 00:51:05.677074 [ 67566 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Error> executeQuery: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, current write offset: 0, caller id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/726/7266a5d7-1810-49ea-bafa-df2983068e25/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_3 (7266a5d7-1810-49ea-bafa-df2983068e25) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR) (version 23.12.1.1) (from [::1]:55820) (comment: 01079_parallel_alter_detach_table_zookeeper.sh) (in query: SELECT SUM(toUInt64(value1)) > 1725 FROM concurrent_alter_detach_3), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:05.688686 [ 67566 ] {4d873c0d-34d1-47fc-9955-12f66023f193} <Error> TCPHandler: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, current write offset: 0, caller id: 4d873c0d-34d1-47fc-9955-12f66023f193:7727, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/726/7266a5d7-1810-49ea-bafa-df2983068e25/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_3 (7266a5d7-1810-49ea-bafa-df2983068e25) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR), Stack trace (when copying this message, always include the lines below):
```

Looking at the background drops that affected this key I get this:

```
#### Background drop

2023.12.16 00:51:01.515638 [ 1261 ] {} <Information> DatabaseCatalog: Have 2 tables in drop queue (0 of them are in use), will try drop test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4)
2023.12.16 00:51:01.516373 [ 1261 ] {} <Trace> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: waiting for locks.
2023.12.16 00:51:01.516991 [ 1261 ] {} <Trace> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: removing data parts (count 155) from filesystem.
2023.12.16 00:51:01.517182 [ 1261 ] {} <Debug> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Removing 155 parts from filesystem (concurrently): Parts: [all_0_0_0, all_0_0_0_2, all_0_0_0_5, all_0_8_1_5, all_0_8_1_9, all_0_14_2_9, all_0_14_2_16, all_0_20_3_16, all_0_20_3_21, all_0_26_4_31, all_0_36_5_32, all_0_42_6_44, all_0_48_7_44, all_0_48_7_52, all_0_54_8_52, all_0_54_8_57, all_0_54_8_60, all_0_69_10_60, all_0_69_10_72, all_0_75_11_72, all_0_80_12_72, all_0_80_12_82, all_0_80_12_86, all_0_88_13_86, all_0_88_13_89, all_0_102_14_89, all_0_102_14_103, all_0_102_14_107, all_0_102_14_114, all_0_117_15_114, all_1_1_0, all_1_1_0_2, all_1_1_0_5, all_3_3_0, all_3_3_0_5, all_4_4_0, all_4_4_0_5, all_6_6_0, all_7_7_0, all_8_8_0, all_10_10_0, all_11_11_0, all_12_12_0, all_13_13_0, all_14_14_0, all_15_15_0, all_15_15_0_16, all_17_17_0, all_18_18_0, all_19_19_0, all_20_20_0, all_22_22_0, all_23_23_0, all_24_24_0, all_25_25_0, all_26_26_0, all_27_27_0, all_27_27_0_31, all_28_28_0_31, all_29_29_0_31, all_30_30_0_31, all_33_33_0, all_34_34_0, all_35_35_0, all_36_36_0, all_37_37_0, all_38_38_0, all_39_39_0, all_40_40_0, all_42_42_0, all_43_43_0_44, all_45_45_0, all_46_46_0, all_47_47_0, all_48_48_0, all_49_49_0, all_49_49_0_52, all_50_50_0, all_50_50_0_52, all_51_51_0, all_51_51_0_52, all_53_53_0, all_54_54_0, all_55_55_0, all_55_55_0_57, all_55_55_0_60, all_56_56_0, all_56_56_0_57, all_56_56_0_60, all_58_58_0, all_58_58_0_60, all_59_59_0, all_59_59_0_60, all_61_61_0, all_62_62_0, all_63_63_0, all_64_64_0, all_65_65_0, all_70_70_0, all_70_70_0_72, all_71_71_0, all_71_71_0_72, all_73_73_0, all_74_74_0, all_75_75_0, all_76_76_0, all_77_77_0, all_78_78_0, all_79_79_0, all_80_80_0, all_81_81_0, all_81_81_0_82, all_81_81_0_86, all_83_83_0, all_83_83_0_86, all_84_84_0, all_84_84_0_86, all_85_85_0, all_85_85_0_86, all_87_87_0, all_88_88_0, all_91_91_0, all_91_98_1, all_92_92_0, all_95_95_0, all_96_96_0, all_97_97_0, all_98_98_0, all_99_99_0, all_100_100_0, all_101_101_0, all_102_102_0, all_104_104_0, all_104_104_0_107, all_104_110_1_107, all_104_110_1_114, all_105_105_0, all_105_105_0_107, all_106_106_0, all_106_106_0_107, all_108_108_0, all_109_109_0, all_110_110_0, all_111_111_0, all_111_111_0_114, all_112_112_0, all_112_112_0_114, all_113_113_0, all_113_113_0_114, all_115_115_0, all_116_116_0, all_117_117_0, all_118_118_0, all_119_119_0, all_120_120_0]
2023.12.16 00:51:01.517734 [ 1261 ] {} <Debug> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Block range all_0_117_999999999_999999999 contained 152 parts, it was split into 8 independent subranges after excluding 1 top-level parts
2023.12.16 00:51:01.518160 [ 1261 ] {} <Debug> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Block range all_0_102_999999999_999999999 contained 131 parts, it was split into 6 independent subranges after excluding 4 top-level parts
2023.12.16 00:51:01.518842 [ 1261 ] {} <Debug> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Block range all_0_88_999999999_999999999 contained 116 parts, it was split into 7 independent subranges after excluding 2 top-level parts
2023.12.16 00:51:01.519495 [ 1261 ] {} <Debug> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Block range all_0_80_999999999_999999999 contained 103 parts, it was split into 6 independent subranges after excluding 3 top-level parts
2023.12.16 00:51:01.520218 [ 1261 ] {} <Trace> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Will remove 10 big parts separately: all_0_80_12_72, all_0_80_12_82, all_0_80_12_86, all_0_88_13_86, all_0_88_13_89, all_0_102_14_89, all_0_102_14_103, all_0_102_14_107, all_0_102_14_114, all_0_117_15_114
2023.12.16 00:51:02.400904 [ 1261 ] {} <Trace> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: removing all data parts from memory.
2023.12.16 00:51:02.401277 [ 1261 ] {} <Information> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: clearing temporary directories
2023.12.16 00:51:02.401733 [ 1261 ] {} <Information> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: remove format_version.txt, detached, moving and write ahead logs
2023.12.16 00:51:02.402200 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: a16138c026b9bf71e29151ec9d2f974f, offset: 0, size: 1
2023.12.16 00:51:02.402390 [ 1261 ] {} <Debug> CacheMetadata: Key a16138c026b9bf71e29151ec9d2f974f is removed from metadata
2023.12.16 00:51:02.405756 [ 1261 ] {} <Debug> S3ObjectStorage: Objects with paths [test/mzh/wchcipcejrukrwspuqvwrchsbbmwg] were removed from S3
2023.12.16 00:51:02.412030 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: ad97b2c855e15e50d0a60fcdc1f94f82, offset: 0, size: 2
2023.12.16 00:51:02.412259 [ 1261 ] {} <Debug> CacheMetadata: Key ad97b2c855e15e50d0a60fcdc1f94f82 is removed from metadata
2023.12.16 00:51:02.412548 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: 265a29789068c288e6506f4848812d2b, offset: 0, size: 3
2023.12.16 00:51:02.412664 [ 1261 ] {} <Debug> CacheMetadata: Key 265a29789068c288e6506f4848812d2b is removed from metadata
2023.12.16 00:51:02.412845 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: 26b69925e760a3f78b3787d7724a7b33, offset: 0, size: 185
2023.12.16 00:51:02.412981 [ 1261 ] {} <Debug> CacheMetadata: Key 26b69925e760a3f78b3787d7724a7b33 is removed from metadata
2023.12.16 00:51:02.413162 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: 58f23cb9fb78e7d68d3e68052efac911, offset: 0, size: 81
2023.12.16 00:51:02.413259 [ 1261 ] {} <Debug> CacheMetadata: Key 58f23cb9fb78e7d68d3e68052efac911 is removed from metadata
2023.12.16 00:51:02.413412 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: da366c44d09c6c63acd59f389dc76a96, offset: 0, size: 181
2023.12.16 00:51:02.413512 [ 1261 ] {} <Debug> CacheMetadata: Key da366c44d09c6c63acd59f389dc76a96 is removed from metadata
2023.12.16 00:51:02.413692 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: 62dd88e579d0699d86efc2a864911e0c, offset: 0, size: 221
2023.12.16 00:51:02.413784 [ 1261 ] {} <Debug> CacheMetadata: Key 62dd88e579d0699d86efc2a864911e0c is removed from metadata
2023.12.16 00:51:02.413968 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: 4c6b73e633b5aabe8d40381802132f99, offset: 0, size: 10
2023.12.16 00:51:02.414089 [ 1261 ] {} <Debug> CacheMetadata: Key 4c6b73e633b5aabe8d40381802132f99 is removed from metadata
2023.12.16 00:51:02.414265 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: dd59d529d886bdf1dbd697f401a902e5, offset: 0, size: 242
2023.12.16 00:51:02.414364 [ 1261 ] {} <Debug> CacheMetadata: Key dd59d529d886bdf1dbd697f401a902e5 is removed from metadata
2023.12.16 00:51:02.414550 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: 5437037b4399d807e825eadd9175aa2e, offset: 0, size: 188
2023.12.16 00:51:02.414669 [ 1261 ] {} <Debug> CacheMetadata: Key 5437037b4399d807e825eadd9175aa2e is removed from metadata
2023.12.16 00:51:02.414856 [ 1261 ] {} <Debug> CacheMetadata: Remove from cache. Key: b5ef75e2891233da10547fc64a8cea70, offset: 0, size: 568
2023.12.16 00:51:02.414962 [ 1261 ] {} <Debug> CacheMetadata: Key b5ef75e2891233da10547fc64a8cea70 is removed from metadata
2023.12.16 00:51:02.423057 [ 1261 ] {} <Debug> S3ObjectStorage: Objects with paths [test/vpl/nskzxxkwdwrqxpcbqtarxgjbutmxf, test/opy/odkodqeqxludphrtzelcwymrayduk, test/cky/hbrdfzaupykmjpepyicfxkyxlyubc, test/ptw/obnzkodjkrsqwwghwfnmnlppslmoa, test/ppr/djdzvdrrjxafiekckcarteyyiumki, test/pjo/xmskflgpkmtebsnsyvslqunpufmeg, test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, test/frl/kkbculglnyrrjbbxpmlxtgixhvhmz, test/hts/yxqmccvafadzoznybdiqgvqzudomk, test/xtv/xmeqfktjoikxrvssevmbgybznicxk, test/ddr/cptsakagmyqlgvvhrakjlxvfkagge, test/szc/foyspigvwldppaajihnkrxmrnygiw, test/nxq/grmvsbfsvuxhqcvrvdxbbyatbxnxt, test/wri/flodwekgwxeikfjlcqcmexmpkntlf, test/whs/lyxrdwjdurldrqparqgejxlwgvyqa, test/lhv/bltxdvylipgqxndmebfczoerthkxt, test/bjp/qgvrfpuplohldkakezblmrofkgmxi] were removed from S3
2023.12.16 00:51:02.423233 [ 1261 ] {} <Debug> RemoveRecursiveObjectStorageOperation: Recursively remove path store/53f/53f44673-c673-4696-98ce-18927bd350c4/detached: metadata and objects were removed for [ignored_all_0_117_15_114/metadata_version.txt, ignored_all_0_117_15_114/key.cmrk2, ignored_all_0_117_15_114/value2.sparse.idx.cmrk2, ignored_all_0_117_15_114/count.txt, ignored_all_0_117_15_114/key.sparse.idx.cmrk2, ignored_all_0_117_15_114/columns.txt, ignored_all_0_117_15_114/value1.cmrk2, ignored_all_0_117_15_114/key.sparse.idx.bin, ignored_all_0_117_15_114/value2.sparse.idx.bin, ignored_all_0_117_15_114/serialization.json, ignored_all_0_117_15_114/value2.cmrk2, ignored_all_0_117_15_114/default_compression_codec.txt, ignored_all_0_117_15_114/primary.cidx, ignored_all_0_117_15_114/value1.bin, ignored_all_0_117_15_114/checksums.txt, ignored_all_0_117_15_114/value2.bin, ignored_all_0_117_15_114/key.bin], only metadata were removed for [].
2023.12.16 00:51:02.423524 [ 1261 ] {} <Information> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: removing table directory recursive to cleanup garbage
2023.12.16 00:51:02.423750 [ 1261 ] {} <Debug> RemoveRecursiveObjectStorageOperation: Recursively remove path store/53f/53f44673-c673-4696-98ce-18927bd350c4/: metadata and objects were removed for [], only metadata were removed for [].
2023.12.16 00:51:02.423812 [ 1261 ] {} <Trace> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): dropAllData: done.
2023.12.16 00:51:02.636843 [ 1261 ] {} <Information> test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4): Removing replica /clickhouse/tables/01079_parallel_alter_detach_table_zookeeper_test_hozy8xwx/concurrent_alter_detach/replicas/1, marking it as lost
2023.12.16 00:51:02.675855 [ 1261 ] {} <Information> DatabaseCatalog: Removing metadata /var/lib/clickhouse/metadata_dropped/test_hozy8xwx.concurrent_alter_detach_1.53f44673-c673-4696-98ce-18927bd350c4.sql of dropped table test_hozy8xwx.concurrent_alter_detach_1 (53f44673-c673-4696-98ce-18927bd350c4)
2023.12.16 00:51:02.677714 [ 1261 ] {} <Trace> DatabaseCatalog: Execution took 1162 ms.
2023.12.16 00:51:02.677837 [ 1261 ] {} <Trace> DatabaseCatalog: Not found any suitable tables to drop, still have 1 tables in drop queue (0 of them are in use). Will check again after 22 seconds
```

And this is from the query:
```
$ grep 41f9eb63-9308-47d0-9cb2-6b49e3b128cb clickhouse-server.log
2023.12.16 00:51:03.109548 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> executeQuery: (from [::1]:55778) (comment: 01079_parallel_alter_detach_table_zookeeper.sh) SELECT SUM(toUInt64(value1)) > 1725 FROM concurrent_alter_detach_2 (stage: Complete)
2023.12.16 00:51:03.113252 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> ContextAccess (default): Access granted: SELECT(value1) ON test_hozy8xwx.concurrent_alter_detach_2
2023.12.16 00:51:03.113795 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.12.16 00:51:03.118177 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) (SelectExecutor): Key condition: unknown
2023.12.16 00:51:03.119167 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) (SelectExecutor): Selected 4/4 parts by partition key, 4 parts by primary key, 98/98 marks by primary key, 98 marks to read from 4 ranges
2023.12.16 00:51:03.119309 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) (SelectExecutor): Spreading mark ranges among streams (default reading)
2023.12.16 00:51:03.119875 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> MergeTreeReadPool: min_marks_for_concurrent_read=76
2023.12.16 00:51:03.121341 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) (SelectExecutor): Reading approx. 146 rows with 4 streams
2023.12.16 00:51:03.131246 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Information> AWSClient: Response status: 404, Not Found
2023.12.16 00:51:03.131369 [ 56640 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> AggregatingTransform: Aggregating
2023.12.16 00:51:03.131511 [ 56640 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> Aggregator: An entry for key=18241280736330186552 found in cache: sum_of_sizes=2, median_size=1
2023.12.16 00:51:03.131534 [ 56569 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> AggregatingTransform: Aggregating
2023.12.16 00:51:03.131580 [ 56640 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> Aggregator: Aggregation method: without_key
2023.12.16 00:51:03.131630 [ 56569 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> Aggregator: An entry for key=18241280736330186552 found in cache: sum_of_sizes=2, median_size=1
2023.12.16 00:51:03.131708 [ 56569 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> Aggregator: Aggregation method: without_key
2023.12.16 00:51:03.131697 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Information> AWSClient: AWSErrorMarshaller: Encountered AWSError 'NoSuchKey': The specified key does not exist.
2023.12.16 00:51:03.131880 [ 56640 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> AggregatingTransform: Aggregated. 1 to 1 rows (from 8.00 B) in 0.009417569 sec. (106.185 rows/sec., 849.48 B/sec.)
2023.12.16 00:51:03.132001 [ 56569 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> AggregatingTransform: Aggregated. 1 to 1 rows (from 8.00 B) in 0.009595389 sec. (104.217 rows/sec., 833.73 B/sec.)
2023.12.16 00:51:03.132034 [ 56573 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> AggregatingTransform: Aggregating
2023.12.16 00:51:03.132034 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Information> AWSClient: AWSXmlClient: HTTP response code: 404
2023.12.16 00:51:03.132120 [ 56573 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> Aggregator: An entry for key=18241280736330186552 found in cache: sum_of_sizes=2, median_size=1
2023.12.16 00:51:03.132168 [ 56573 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> Aggregator: Aggregation method: without_key
2023.12.16 00:51:03.132305 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2023.12.16 00:51:03.132374 [ 56573 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> AggregatingTransform: Aggregated. 1 to 1 rows (from 8.00 B) in 0.00989772 sec. (101.033 rows/sec., 808.27 B/sec.)
2023.12.16 00:51:03.132739 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> ReadBufferFromS3: Caught exception while reading S3 object. Bucket: test, Key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, Version: Latest, Offset: 0, Attempt: 1/4, Message: The specified key does not exist.
2023.12.16 00:51:03.133234 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> CacheMetadata: Remove from cache. Key: da366c44d09c6c63acd59f389dc76a96, offset: 0, size: 0
2023.12.16 00:51:03.133334 [ 3137 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Debug> CacheMetadata: Submitting key da366c44d09c6c63acd59f389dc76a96 for removal
2023.12.16 00:51:03.133915 [ 56607 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Trace> test_hozy8xwx.concurrent_alter_detach_2 (ReplicatedMergeTreePartCheckThread): Enqueueing all_0_117_15_114 for check after after 0s
2023.12.16 00:51:03.263653 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Error> executeQuery: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, current write offset: 0, caller id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/019/0190e826-e367-42af-9ef0-f49fbfd62e73/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR) (version 23.12.1.1) (from [::1]:55778) (comment: 01079_parallel_alter_detach_table_zookeeper.sh) (in query: SELECT SUM(toUInt64(value1)) > 1725 FROM concurrent_alter_detach_2), Stack trace (when copying this message, always include the lines below):
2023.12.16 00:51:03.328568 [ 67566 ] {41f9eb63-9308-47d0-9cb2-6b49e3b128cb} <Error> TCPHandler: Code: 499. DB::Exception: The specified key does not exist.: while reading key: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, from bucket: test: Cache info: Buffer path: test/rjr/cexuyczxgttyhlaxwjjtigfmterhb, hash key: da366c44d09c6c63acd59f389dc76a96, file_offset_of_buffer_end: 0, read_until_position: 181, internal buffer end: 0, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, file segment info: File segment: [0, 180], key: da366c44d09c6c63acd59f389dc76a96, state: DOWNLOADING, downloaded size: 0, reserved size: 0, downloader id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, current write offset: 0, caller id: 41f9eb63-9308-47d0-9cb2-6b49e3b128cb:3137, kind: Regular, unbound: 0: (while reading column value1): (while reading from part /var/lib/clickhouse/disks/s3/store/019/0190e826-e367-42af-9ef0-f49fbfd62e73/all_0_117_15_114/ in table test_hozy8xwx.concurrent_alter_detach_2 (0190e826-e367-42af-9ef0-f49fbfd62e73) located on disk s3 of type s3, from mark 0 with max_rows_to_read = 143): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (S3_ERROR), Stack trace (when copying this message, always include the lines below):
```

There is an odd thing I'm not understanding:
* The background drop is working on data dropped from `concurrent_alter_detach_1`.
* The query is accessing a different table `concurrent_alter_detach_2`.

AFAICS in the test, the tables are independent and don't share anything. Either I'm missing something (likely), or there was a clash in the hash (unlikely).

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a bug in zero-copy-replication (an experimental feature) that could lead to `The specified key does not exist` error and data loss. It could happen when dropping a replica with broken or unexpected/ignored detached parts. Fixes https://github.com/ClickHouse/ClickHouse/issues/57985

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 852f397a97a8af0aecf8408cde065eb0dd99a52d with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58333/852f397a97a8af0aecf8408cde065eb0dd99a52d/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58333/852f397a97a8af0aecf8408cde065eb0dd99a52d/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: tests/queries/0_stateless/02488_zero_copy_detached_parts_drop_table.sh [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+$CLICKHOUSE_CLIENT --insert_keeper_fault_injection_probability=0 -q "insert into rmt2 values (42)"
+$CLICKHOUSE_CLIENT -q "system sync replica rmt1"
+
+path=$($CLICKHOUSE_CLIENT -q "select path from system.parts where database='$CLICKHOUSE_DATABASE' and table='rmt2' and name='all_0_0_0'")
+# ensure that path is absolute before removing
+$CLICKHOUSE_CLIENT -q "select throwIf(substring('$path', 1, 1) != '/', 'Path is relative: $path')" || exit
+rm -f $path/n.bin
+
+$CLICKHOUSE_CLIENT -q "detach table rmt2 sync"
+$CLICKHOUSE_CLIENT --send_logs_level='fatal' -q "attach table rmt2"
```
Comment (Algunenano) [inline tests/queries/0_stateless/02488_zero_copy_detached_parts_drop_table.sh:22]: Do you need `insert_keeper_fault_injection_probability=0` here as well? RMT part attach follows the same code as insert

Comment (tavplubix) [reply tests/queries/0_stateless/02488_zero_copy_detached_parts_drop_table.sh:22]: no, it's attach table, not attach part

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Test failed :(

**Comment by alesapin** [comment]
`test_quorum_inserts/test.py::test_insert_quorum_with_drop_partition[False]` failure looks suspicious but changes in PR unrelated to DROP PARITION or INSERTS at all.

**Comment by tavplubix** [comment]
> `test_quorum_inserts/test.py::test_insert_quorum_with_drop_partition[False]` failure looks suspicious but changes in PR unrelated to DROP PARITION or INSERTS at all.

Looks like a rare race condition between `cleanLastPartNode` and `updateQuorum` that can make SELECTs with `select_sequential_consistency` fail if a part was dropped. I tried to fix it a while ago, but it appeared to be too complex
