### PR TITLE
Do not throw exception on connection with incorrect iceberg database 

### LINKED ISSUE #81156: When a `DataLakeCatalog` database is misconfigured, I get an exception immediately upon connecting to the ClickHouse client
### Describe the unexpected behaviour

I create database with DataLakeCatalog engine
```sql
CREATE DATABASE datalake                                                     
ENGINE = DataLakeCatalog                                                     
SETTINGS catalog_type = 'glue', auth_header = '[HIDDEN]', region = 'us-east-1' 
```
I forgot so specify credentials, and I soon as I connect to clickhouse-client I get an exception, even though I didn't query this database yet.

`clickhouse-client`

```
ClickHouse client version 25.6.1.1176 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 25.6.1.

Warnings:
 * Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.

clickhouse1 :) Cannot load data for command line suggestions: Code: 736. DB::Exception: Received from localhost:9000. DB::Exception: Exception calling GetTables Missing Authentication Token. (DATALAKE_DATABASE_ERROR) (version 25.6.1.1176 (official build))
```

### Which ClickHouse versions are affected?

25.6

### Expected behavior

I expect not to see an exception as soon as I log in.

### Error message and/or stacktrace

`
Cannot load data for command line suggestions: Code: 736. DB::Exception: Received from localhost:9000. DB::Exception: Exception calling GetTables Missing Authentication Token. (DATALAKE_DATABASE_ERROR) (version 25.6.1.1176 (official build))
`
or

`
Cannot load data for command line suggestions: Code: 736. DB::Exception: Received from localhost:9000. DB::Exception: Exception calling GetTables The security token included in the request is invalid.. (DATALAKE_DATABASE_ERROR) (version 25.6.1.1176 (official build))
`

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This closes https://github.com/ClickHouse/ClickHouse/issues/81156
Same "feature" in Postgres - https://github.com/ClickHouse/ClickHouse/blob/3470af8f5e8a2b4035f33e769828707430655665/src/Databases/PostgreSQL/DatabasePostgreSQL.cpp#L126

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/DataLake/DatabaseDataLake.cpp [hunk 1]
```diff
@@ -516,7 +516,17 @@ DatabaseTablesIteratorPtr DatabaseDataLake::getLightweightTablesIterator(
...
     Tables tables;
     auto catalog = getCatalog();
-    const auto iceberg_tables = catalog->getTables();
+    DB::Names iceberg_tables = {};
+
+    /// Do not throw here, because this might be, for example, a query to system.tables.
+    /// It must not fail on case of some datalake error.
+    try
+    {
+        iceberg_tables = catalog->getTables();
```
Comment (alesapin) [inline src/Databases/DataLake/DatabaseDataLake.cpp:536]: Do we need the same in `DatabaseDataLake::getTablesIterator`?

**Review by alesapin — APPROVED** [review]

File: src/Databases/DataLake/DatabaseDataLake.cpp [hunk 2]
```diff
@@ -516,7 +516,17 @@ DatabaseTablesIteratorPtr DatabaseDataLake::getLightweightTablesIterator(
...
+    }
+    catch (...)
+    {
```
Comment (alesapin) [inline src/Databases/DataLake/DatabaseDataLake.cpp:539]: Let's at least log this error
