### PR TITLE
Fix using subqueries in row policy filters

### LINKED ISSUE #32463: Subqueries inside expressions for row policies.
problem with this query:

```sql
drop table if exists test.row_policy 

create table test.row_policy Engine = Memory
as 
select now() as d,'test' as s

select *
from test.row_policy


CREATE ROW POLICY filter ON test.row_policy USING ( s in  ( 'test') ) TO ALL;

select * from test.row_policy -- [ok] return 1 record 

DROP ROW POLICY IF EXISTS filter ON test.row_policy;

CREATE ROW POLICY filter ON test.row_policy USING ( s in  (select 'test') ) TO ALL;

select * from test.row_policy -- [problem] return 0 record 

```

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix using subqueries in row policy filters. This PR fixes https://github.com/ClickHouse/ClickHouse/issues/32463

### CODE REVIEW

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -155,7 +156,7 @@ FilterDAGInfoPtr generateFilterActions(
 
     /// Using separate expression analyzer to prevent any possible alias injection
     auto syntax_result = TreeRewriter(context).analyzeSelect(query_ast, TreeRewriterResult({}, storage, storage_snapshot));
-    SelectQueryExpressionAnalyzer analyzer(query_ast, syntax_result, context, metadata_snapshot);
+    SelectQueryExpressionAnalyzer analyzer(query_ast, syntax_result, context, metadata_snapshot, {}, false, {}, prepared_sets);
```
Comment (vitlibar) [inline src/Interpreters/InterpreterSelectQuery.cpp:159]: @KochetovNicolai I'm not 100% sure this is the right fix, but it seems it fixes the issue.

File: tests/integration/test_row_policy/test.py [hunk 2]
```diff
@@ -867,3 +867,26 @@ def test_policy_on_distributed_table_via_role():
...
+
+    node.query("CREATE TABLE table_1 (x int, y int) ENGINE = MergeTree ORDER BY tuple()")
+    node.query("INSERT INTO table_1 SELECT number, number * number FROM numbers(10)")
+
+    node.query("CREATE TABLE table_2 (a int) ENGINE=MergeTree ORDER BY tuple()")
+    node.query("INSERT INTO table_2 VALUES (3), (5)")
+
+    node.query("CREATE ROW POLICY filter_1 ON table_1 USING x IN (SELECT a FROM table_2) TO ALL")
+    
+    assert node.query("SELECT * FROM table_1") == TSV([[3, 9], [5, 25]])
```
Comment (vitlibar) [inline tests/integration/test_row_policy/test.py:888]: Without my fix this SELECT produced an empty result.

File: src/Interpreters/InterpreterSelectQuery.cpp (hunk 1 above)
Comment (KochetovNicolai) [reply src/Interpreters/InterpreterSelectQuery.cpp:159]: Looks ok to me

**Review by KochetovNicolai — APPROVED** [review]
