### PR TITLE
Fix bug with _size of archives in s3 table function

### LINKED ISSUE #65944: When processing archives on S3, make the `_size` virtual column relate to the size of the file, not a whole archive, to make it consistent with archives on the local filesystem.
A part of a big issue about further improvements of archives S3 usage

### PR DESCRIPTION
**Pull request by divanik**
Closes https://github.com/ClickHouse/ClickHouse/issues/65944

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Column _size in s3 engine and s3 table function denotes the size of a file inside the archive, not a size of the archive itself

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [x]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit f2244853164906cbf6faf186b7f3782ccc504d5a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65993/f2244853164906cbf6faf186b7f3782ccc504d5a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65993/f2244853164906cbf6faf186b7f3782ccc504d5a/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Storages/ObjectStorage/StorageObjectStorageSource.cpp [hunk 1]
```diff
@@ -196,13 +196,12 @@ Chunk StorageObjectStorageSource::generate()
...
-                    .size = object_info->metadata->size_bytes,
-                    .filename = &filename,
-                    .last_modified = object_info->metadata->last_modified
-                });
+                chunk,
+                read_from_format_info.requested_virtual_columns,
+                {.path = getUniqueStoragePathIdentifier(*configuration, *object_info, false),
+                 .size = object_info->isArchive() ? object_info->fileSizeInArchive() : object_info->metadata->size_bytes,
+                 .filename = &filename,
+                 .last_modified = object_info->metadata->last_modified});
```
Comment (antonio2368) [inline src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:204]: old formatting was better IMO

**Review by antonio2368 — APPROVED** [review]

**Comment by divanik** [comment]
#Closes 65944
