### PR TITLE
Fix strange and wrong code around DateTime64

### LINKED ISSUE #11374: Received signal Floating point exception (8).
```
WITH toDateTime64('2019-09-16 19:20:12.3456789102019-09-16 19:20:12.345678910', 0) AS dt64
SELECT dt64
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix potential floating point exception when parsing DateTime64. This fixes #11374.

### CODE REVIEW

File: src/DataTypes/DataTypeDateTime64.cpp [hunk 1]
```diff
@@ -20,19 +20,34 @@
...
     : DataTypeDecimalBase<DateTime64>(DecimalUtils::maxPrecision<DateTime64>(), scale_),
       TimezoneMixin(time_zone_name)
 {
+    if (scale > max_scale)
+        throw Exception("Scale " + std::to_string(scale) + " is too large for DateTime64. Maximum is up to nanoseconds (9).",
+            ErrorCodes::ARGUMENT_OUT_OF_BOUND);
 }
 
 DataTypeDateTime64::DataTypeDateTime64(UInt32 scale_, const TimezoneMixin & time_zone_info)
-    : DataTypeDecimalBase<DateTime64>(DecimalUtils::maxPrecision<DateTime64>() - scale_, scale_),
```
Comment (alexey-milovidov) [inline src/DataTypes/DataTypeDateTime64.cpp:33]: This is very strange and ridiculous. Maybe this constructor is not used at all?

File: src/DataTypes/DataTypeDecimalBase.h [hunk 2]
```diff
@@ -72,7 +72,7 @@ class DataTypeDecimalBase : public DataTypeWithSimpleSerialization
     {
         if (unlikely(precision < 1 || precision > maxPrecision()))
             throw Exception("Precision " + std::to_string(precision) + " is out of bounds", ErrorCodes::ARGUMENT_OUT_OF_BOUND);
-        if (unlikely(scale < 0 || static_cast<UInt32>(scale) > maxPrecision()))
+        if (unlikely(scale > maxPrecision()))
```
Comment (alexey-milovidov) [inline src/DataTypes/DataTypeDecimalBase.h:75]: This was strange code from @4ertus2 
Also I'm surprised that tautological comparison is not detected by compiler.

File: src/IO/ReadHelpers.h [hunk 3]
```diff
@@ -297,28 +301,51 @@ ReturnType readIntTextImpl(T & x, ReadBuffer & buf)
...
+            {
                 if constexpr (check_overflow == ReadIntTextCheckOverflow::CHECK_OVERFLOW)
                 {
-                    // perform relativelly slow overflow check only when number of decimal digits so far is close to the max for given type.
-                    if (buf.count() - initial_pos >= std::numeric_limits<T>::max_digits10)
+                    /// Perform relativelly slow overflow check only when
+                    /// number of decimal digits so far is close to the max for given type.
+                    /// Example: 20 * 10 will overflow Int8.
+
+                    if (buf.count() - initial_pos + 1 >= std::numeric_limits<T>::max_digits10)
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:311]: Look at this `+ 1`.

File: src/IO/ReadHelpers.h [hunk 4]
```diff
@@ -297,28 +301,51 @@ ReturnType readIntTextImpl(T & x, ReadBuffer & buf)
...
                     {
-                        if (common::mulOverflow(res, static_cast<decltype(res)>(10), res)
-                            || common::addOverflow(res, static_cast<decltype(res)>(*buf.position() - '0'), res))
+                        T signed_res = res;
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:313]: We must check for overflow inside (possibly) signed data type.

File: src/IO/ReadHelpers.h [hunk 5]
```diff
@@ -297,28 +301,51 @@ ReturnType readIntTextImpl(T & x, ReadBuffer & buf)
...
                 {
-                    // perform relativelly slow overflow check only when number of decimal digits so far is close to the max for given type.
-                    if (buf.count() - initial_pos >= std::numeric_limits<T>::max_digits10)
+                    /// Perform relativelly slow overflow check only when
+                    /// number of decimal digits so far is close to the max for given type.
+                    /// Example: 20 * 10 will overflow Int8.
+
+                    if (buf.count() - initial_pos + 1 >= std::numeric_limits<T>::max_digits10)
                     {
-                        if (common::mulOverflow(res, static_cast<decltype(res)>(10), res)
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:305]: This `decltype` is ugly.

File: src/IO/ReadHelpers.h [hunk 6]
```diff
@@ -297,28 +301,51 @@ ReturnType readIntTextImpl(T & x, ReadBuffer & buf)
...
                 break;
+            }
             default:
                 goto end;
         }
         ++buf.position();
     }
 
 end:
-    x = negative ? -res : res;
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:321]: And we must check for overflow here.

File: src/IO/ReadHelpers.h [hunk 7]
```diff
@@ -658,35 +685,34 @@ inline ReturnType readDateTimeTextImpl(DateTime64 & datetime64, UInt32 scale, Re
         return ReturnType(false);
     }
 
-    DB::DecimalUtils::DecimalComponents<DateTime64::NativeType> c{static_cast<DateTime64::NativeType>(whole), 0};
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:661]: `c` is bad name for variable.

File: src/IO/ReadHelpers.h [hunk 8]
```diff
@@ -658,35 +685,34 @@ inline ReturnType readDateTimeTextImpl(DateTime64 & datetime64, UInt32 scale, Re
...
+    DB::DecimalUtils::DecimalComponents<DateTime64::NativeType> components{static_cast<DateTime64::NativeType>(whole), 0};
 
     if (!buf.eof() && *buf.position() == '.')
     {
-        buf.ignore(1); // skip separator
-        const auto pos_before_fractional = buf.count();
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:666]: This is absolutely wrong.
Mind `+123` or `+1---23`.

File: src/IO/ReadHelpers.h [hunk 9]
```diff
@@ -658,35 +685,34 @@ inline ReturnType readDateTimeTextImpl(DateTime64 & datetime64, UInt32 scale, Re
...
-        const auto fractional_length = static_cast<Int32>(buf.count() - pos_before_fractional);
-        if (const auto adjust_scale = static_cast<Int32>(scale) - fractional_length; adjust_scale > 0)
+        /// Read digits, up to 'scale' positions.
+        for (size_t i = 0; i < scale; ++i)
         {
-            c.fractional *= common::exp10_i64(adjust_scale);
-        }
-        else if (adjust_scale < 0)
-        {
-            c.fractional /= common::exp10_i64(-1 * adjust_scale);
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:685]: `adjust_scale` can appear too big.
For example, if 
scale is 0 
and we have parsed
1111111111111111111
then we will have to divide by
10000000000000000000
that does not fit in Int64
and buffer overflow happens.

(this is the main reason for the bug)

Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:685]: Writing `-1 * x` is strange, we can write just `-x`.

File: src/IO/ReadHelpers.h [hunk 10]
```diff
@@ -658,35 +685,34 @@ inline ReturnType readDateTimeTextImpl(DateTime64 & datetime64, UInt32 scale, Re
...
     }
 
-    DB::DecimalUtils::DecimalComponents<DateTime64::NativeType> c{static_cast<DateTime64::NativeType>(whole), 0};
+    DB::DecimalUtils::DecimalComponents<DateTime64::NativeType> components{static_cast<DateTime64::NativeType>(whole), 0};
 
     if (!buf.eof() && *buf.position() == '.')
     {
-        buf.ignore(1); // skip separator
-        const auto pos_before_fractional = buf.count();
-        if (!tryReadIntText<ReadIntTextCheckOverflow::CHECK_OVERFLOW>(c.fractional, buf))
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.h:667]: This is also wrong, because we don't need to parse integer (like `-123`).
We just need to parse a stream of digits (like `001`).

**Comment by alexey-milovidov** [comment]
@Enmk I highlighted all the bugs in comments.

**Comment by qoega** [comment]
Relevant tests: 
```
[ RUN      ] data_type/LeastSuperTypeTest.getLeastSupertype/20
unknown file: Failure
C++ exception with description "Scale 12 is too large for DateTime64. Maximum is up to nanoseconds (9)." thrown in SetUp().
[  FAILED  ] data_type/LeastSuperTypeTest.getLeastSupertype/20, where GetParam() = TypesTestCase{"DateTime DateTime64(12)", "DateTime64(8)"} (0 ms)
[ RUN      ] data_type/LeastSuperTypeTest.getLeastSupertype/21
unknown file: Failure
C++ exception with description "Scale 15 is too large for DateTime64. Maximum is up to nanoseconds (9)." thrown in SetUp().
[  FAILED  ] data_type/LeastSuperTypeTest.getLeastSupertype/21, where GetParam() = TypesTestCase{"Date DateTime64(15)", "DateTime64(13)"} (1 ms)
```

**Comment by alexey-milovidov** [comment]
No surprise: unit test is wrong, getLeastSuperType implementation is also wrong.

**Comment by alexey-milovidov** [comment]
I will also add a functional test to demonstrate what code was totally and absolutely wrong.
