### PR TITLE
Disable explicit column definitions in Alias

### LINKED ISSUE #88426: Block structure mismatch in function connect between RemovingSparseTransform and MergeTreeSink stream: different types (Alias storage)
CI: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88381&sha=latest&name_0=PR&name_1=AST+fuzzer+%28amd_tsan%29

```
CREATE TABLE source_table (`id` UInt32, `value` String) ENGINE = MergeTree ORDER BY id;
CREATE TABLE alias_4__fuzz_45 (`id` Array(Int8), `value` Array(Array(UInt256)), `status` UInt32) ENGINE = Alias('source_table');
INSERT INTO alias_4__fuzz_45 FORMAT Values (1, []);
```

```
Code: 49. DB::Exception: Block structure mismatch in function connect between RemovingSparseTransform and MergeTreeSink stream: different number of columns:
id Array(Int8) Array(size = 0, UInt64(size = 0), Int8(size = 0)), value Array(Array(UInt256)) Array(size = 0, UInt64(size = 0), Array(size = 0, UInt64(size = 0), UInt256(size = 0))), status UInt32 UInt32(size = 0)
id UInt32 UInt32(size = 0), value String String(size = 0). (LOGICAL_ERROR)
```

### PR DESCRIPTION
**Pull request by nauu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix #88426 
1. Disallow explicit column definitions in Alias and columns are automatically load from the target table. 
This ensures that the alias always matches the target table's schema.
2. Proxy more methods from the IStorage

### CODE REVIEW

**Comment by nauu** [comment]
Some tests failed seem unrelated

File: src/Storages/StorageAlias.cpp [hunk 1]
```diff
@@ -250,15 +251,20 @@ void registerStorageAlias(StorageFactory & factory)
...
-                StorageID(target_database, target_table), local_context);
-            columns = target_storage->getInMemoryMetadataPtr()->getColumns();
+            throw Exception(ErrorCodes::BAD_ARGUMENTS,
+                "Storage Alias does not support explicit column definitions");
         }
 
+        // Get columns from target table
+        auto target_storage = DatabaseCatalog::instance().getTable(
+            StorageID(target_database, target_table), local_context);
+        ColumnsDescription columns = target_storage->getInMemoryMetadataPtr()->getColumns();
```
Comment (azat) [inline src/Storages/StorageAlias.cpp]: Hm, so we still hold the target storage columns? But underlying table can be ALTERed

Comment (azat) [reply src/Storages/StorageAlias.cpp]: ~~And we also support `ALTER` for `Alias`, this is also a problem.~~

Comment (nauu) [reply src/Storages/StorageAlias.cpp]: Let me test what happens when someone Alter the target table bypassing Alias intentionally

Comment (azat) [reply src/Storages/StorageAlias.cpp]: And let's add such test

Comment (azat) [reply src/Storages/StorageAlias.cpp]: The problem right now is that you may `ALTER` target table, but if you `ALTER` alias table, then it will alter both, so there is no way to sync those two after target table has been changed.

So I guess we do not need to have own metadata for alias, and override `StorageAlias::getInMemoryMetadataPtr` and `getInMemoryMetadata` to always return `getTargetTable()->getInMemoryMetadataPtr()`

Comment (nauu) [reply src/Storages/StorageAlias.cpp]: Alias now no longer hold the target storage columns

File: src/Storages/StorageAlias.cpp [hunk 2]
```diff
@@ -179,6 +171,59 @@ void StorageAlias::mutate(const MutationCommands & commands, ContextPtr local_co
...
+}
+
+void StorageAlias::updateExternalDynamicMetadataIfExists(ContextPtr local_context)
+{
+    getTargetTable()->updateExternalDynamicMetadataIfExists(local_context);
+}
+
+std::optional<QueryPipeline> StorageAlias::distributedWrite(const ASTInsertQuery & query, ContextPtr local_context)
+{
+    return getTargetTable()->distributedWrite(query, local_context);
```
Comment (azat) [inline src/Storages/StorageAlias.cpp]: Why we don't check permissions i.e. here?
Maybe `getTargetTable(std::optional<AccessType>)` will be a better interface?
If `nullopt` - do not check, otherwise do `checkAccess`

File: src/Interpreters/InterpreterRenameQuery.cpp [hunk 3]
```diff
@@ -140,6 +140,15 @@ BlockIO InterpreterRenameQuery::executeToTables(const ASTRenameQuery & rename, c
 
         if (exchange_tables)
         {
+            auto from_table = database_catalog.tryGetTable(from_table_id, getContext());
```
Comment (azat) [inline src/Interpreters/InterpreterRenameQuery.cpp]: Please add a good comment with an explanation of why it is not supported.

Comment (nauu) [reply src/Interpreters/InterpreterRenameQuery.cpp]: exchange between aliases make things too complicated? It doesn't store data, so If someone want to switch A/B, should just do it directly on the target. like the distributed table

Comment (azat) [reply src/Interpreters/InterpreterRenameQuery.cpp]: Complicated how?

Comment (nauu) [reply src/Interpreters/InterpreterRenameQuery.cpp]: what scenarios do we need to exchange alias? AFAIU we can directly rename it

Comment (azat) [reply src/Interpreters/InterpreterRenameQuery.cpp]: `EXCHANGE` is a very basic thing that should just work, the less special cases there - the better

So:
- If you have any examples why this should be done, let's describe them in the comment
- If not, let's remove this part.

Comment (nauu) [reply src/Interpreters/InterpreterRenameQuery.cpp]: removed

File: src/Storages/StorageAlias.cpp (hunk 2 above)
Comment (nauu) [reply src/Storages/StorageAlias.cpp]: added permission check

Comment (azat) [reply src/Storages/StorageAlias.cpp]: Looks like everything is safe now, but I'm still slightly worrying that we don't have explicit permissions check,  via `getTargetTable`:

>Maybe getTargetTable(std::optional<AccessType>) will be a better interface?
If nullopt - do not check, otherwise do checkAccess

**Review by azat — APPROVED** [review]

File: src/Storages/StorageAlias.cpp (hunk 2 above)
Comment (nauu) [reply src/Storages/StorageAlias.cpp]: now we have explicit permissions check on the interface

File: src/Storages/StorageAlias.h [hunk 4]
```diff
@@ -2,26 +2,33 @@
...
 #include <Storages/IStorage.h>
 #include <Interpreters/DatabaseCatalog.h>
+#include <Access/Common/AccessType.h>
+#include <optional>
 
 
 namespace DB
 {
 
+struct TargetAccess
```
Comment (azat) [inline src/Storages/StorageAlias.h]: Can be moved into the `StorageAlias`

**Review by azat — APPROVED** [review]

File: src/Storages/StorageAlias.h (hunk 4 above)
Comment (nauu) [reply src/Storages/StorageAlias.h]: done

**Comment by nauu** [comment]
@azat some tests failed seem unrelated , can we merge it?
