### PR TITLE
Fix reading subcolumns from Merge engine

### LINKED ISSUE #78719: Engine=Merge does not support JSON type attributes
### Company or project name

_No response_

### Describe the unexpected behaviour

JSON attributes are always NULL:

```
SELECT json.a.b, json.a.g, json.c, json.d FROM merge_test;

SELECT
    json.a.b,
    json.a.g,
    json.c,
    json.d
FROM merge_test

Query id: 518137e8-5eff-47fe-b6db-c91edeaf0f24

   ┌─json.a.b─┬─json.a.g─┬─json.c─┬─json.d─┐
1. │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ   │ ᴺᵁᴸᴸ   │
2. │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ   │ ᴺᵁᴸᴸ   │
3. │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ   │ ᴺᵁᴸᴸ   │
   └──────────┴──────────┴────────┴────────┘

```

### How to reproduce

Create tables:

```
CREATE TABLE test (json JSON) ENGINE = Memory;
CREATE TABLE merge_test (json JSON) ENGINE = Merge(currentDatabase(), '^test$');
INSERT INTO test VALUES ('{"a" : {"b" : 42, "g" : 42.42}, "c" : [1, 2, 3], "d" : "2020-01-01"}'), ('{"f" : "Hello, World!", "d" : "2020-01-02"}'), ('{"a" : {"b" : 43, "e" : 10, "g" : 43.43}, "c" : [4, 5, 6]}');
```

Run the query:

```
SELECT
    json.a.b,
    json.a.g,
    json.c,
    json.d
FROM merge_test
```

### Expected behavior

Should return the same result as:

```
SELECT
    json.a.b,
    json.a.g,
    json.c,
    json.d
FROM test

SELECT
    json.a.b,
    json.a.g,
    json.c,
    json.d
FROM test

Query id: b3f5b35f-75cb-42c9-afde-f5074fb5c235

   ┌─json.a.b─┬─json.a.g─┬─json.c──┬─json.d─────┐
1. │ 42       │ 42.42    │ [1,2,3] │ 2020-01-01 │
2. │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ    │ 2020-01-02 │
3. │ 43       │ 43.43    │ [4,5,6] │ ᴺᵁᴸᴸ       │
   └──────────┴──────────┴─────────┴────────────┘
```

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix reading subcolumns from Merge engine.

Closes https://github.com/ClickHouse/ClickHouse/issues/78719.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03457_merge_engine_subcolumns.sql [hunk 1]
```diff
@@ -0,0 +1,36 @@
+drop table if exists test1;
+drop table if exists test2;
+drop table if exists test_merge;
+
+create table test1 (x UInt64, t Tuple(a UInt32, b UInt32), y String) engine=Memory;
```
Comment (divanik) [inline tests/queries/0_stateless/03457_merge_engine_subcolumns.sql:5]: If not difficult, could you create a bit different schemas (like add two columns with different names to each table) to check if change behaves with nulls correctly?

**Review by divanik — APPROVED** [review]

**Review by divanik — APPROVED** [review]

File: tests/queries/0_stateless/03457_merge_engine_subcolumns.sql (hunk 1 above)
Comment (Avogar) [reply tests/queries/0_stateless/03457_merge_engine_subcolumns.sql:5]: > to check if change behaves with nulls correctly?

What do you mean by that?

There are still some problems with Merge engine that I didn't fix here:
```sql
create table test1(x UInt64, y UInt64) engine=Memory;
create table test2(x UInt64, z UInt64) engine=Memory;
insert into test1 select 1, 2;
insert into test2 select 3, 4;
```

```sql
select * from test_merge;

   ┌─x─┬─y─┬─z─┐
1. │ 1 │ 2 │ 0 │
2. │ 3 │ 0 │ 4 │
   └───┴───┴───┘
```

```sql
select z from test_merge

   ┌─z─┐
1. │ 4 │
2. │ 1 │
   └───┘
```

I believe in the second query we should get `4` and `0` (as default value). I will try to fix it in a separate PR. Here I wanted to fix only reading of subcolumns

Comment (divanik) [reply tests/queries/0_stateless/03457_merge_engine_subcolumns.sql:5]: Ok, it seems it doesn't behave with default values correctly even without sub columns, so this is indeed an unrelated bug

Comment (SaltTan) [reply tests/queries/0_stateless/03457_merge_engine_subcolumns.sql:5]: FYI
* https://github.com/ClickHouse/ClickHouse/issues/76746
