### PR TITLE
Fix possible overestimate memory tracking

### LINKED ISSUE #71511: Wrong MemoryTracking values prevents merges
**Describe the unexpected behaviour**
Merges fail with `MEMORY_LIMIT_EXCEEDED` error. MemoryTracking indicates unrealistic memory usage. Extending memory either via swap or via physical RAM up to 32GB does nothing with it.

**How to reproduce**
Checked ClickHouse server versions:  24.9.1.3278, 24.9.2.42. 
RabbitMQ engine is used with low insert rate (less than 2RPM) into ReplicatedMergeTree and ReplicatedSummingMergeTree materialized views and no queries.
If `max_server_memory_usage_to_ram_ratio` is set, ClickHouse will stop merges after a few hours due to `MEMORY_LIMIT_EXCEEDED` error. With disabled memory limit it works as expected, except for `MemoryTracking` metric. Real memory consumption ("resident" in htop) is less than 550MB. `MemoryTracking` shows hundreds of gigabytes and continues to grow. 

```
SELECT formatReadableSize(value)
FROM system.metrics
WHERE metric = 'MemoryTracking' 
FORMAT Pretty;
   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
   ┃ formatReadableSize(value) ┃
   ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
1. │ 263.32 GiB                │
   └───────────────────────────┘
```

```
SELECT formatReadableSize(sum(t.allocations * t.size) - sum(t.deallocations * t.size))
FROM system.jemalloc_bins t
FORMAT Pretty;
   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
   ┃ formatReadableSize(minus(sum(multiply(allocations, size)), sum(multiply(deallocations, size)))) ┃
   ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
1. │ 199.22 MiB                                                                                      │
   └─────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Error message and/or stacktrace**
```
<Error> a1be084d-9ee0-4360-b7c1-e24d0f28132a::all_0_6121_2581 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 241. DB::Exception: Memory limit (total) exceeded: would use 73.10 GiB (attempt to allocate chunk of 4819411 bytes), current RSS 212.56 MiB, maximum: 14.03 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d66ad9b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e75b2c
2. DB::Exception::Exception<char const*, char const*, String, long&, String, String, char const*, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<char const*>::type, std::type_identity<String>::type, std::type_identity<long&>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<char const*>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, char const*&&, char const*&&, String&&, long&, String&&, String&&, char const*&&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x000000000d689064
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000d68818d
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000d687cb1
5. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000d687cb1
6. MemoryTracker::allocImpl(long, bool, MemoryTracker*, double) @ 0x000000000d687cb1
7. Allocator<false, false>::alloc(unsigned long, unsigned long) @ 0x000000000d63c1b0
8. DB::Memory<Allocator<false, false>>::alloc(unsigned long) @ 0x000000000d6ce995
9. DB::WriteBufferFromFileDescriptor::WriteBufferFromFileDescriptor(int, unsigned long, char*, std::shared_ptr<DB::Throttler>, unsigned long, String, bool, unsigned long) @ 0x000000000d6f4ac1
10. DB::WriteBufferFromFile::WriteBufferFromFile(String const&, unsigned long, int, std::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long, bool, unsigned long) @ 0x000000000d815b4f
11. DB::DiskLocal::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x00000000111156f3
12. DB::DataPartStorageOnDiskFull::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x0000000012992953
13. DB::MergeTreeDataPartWriterOnDisk::Stream<false>::Stream(String const&, std::shared_ptr<DB::IDataPartStorage> const&, String const&, String const&, String const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, DB::WriteSettings const&) @ 0x0000000012b5caf6
14. void std::__function::__policy_invoker<void (DB::ISerialization::SubstreamPath const&)>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IAST> const&)::$_0, void (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x0000000012b6c4f7
15. DB::ISerialization::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x0000000010ebb9d0
16. DB::ISerialization::enumerateStreams(std::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::shared_ptr<DB::IDataType const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) const @ 0x0000000010ebbc88
17. DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IAST> const&) @ 0x0000000012b6445f
18. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnStatistics>, std::allocator<std::shared_ptr<DB::ColumnStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x0000000012b6425f
19. DB::createMergeTreeDataPartWriter(DB::MergeTreeDataPartType, String const&, String const&, std::unordered_map<String, std::shared_ptr<DB::ISerialization const>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization const>>>> const&, std::shared_ptr<DB::IDataPartStorage>, DB::MergeTreeIndexGranularityInfo const&, std::shared_ptr<DB::MergeTreeSettings const> const&, DB::NamesAndTypesList const&, std::unordered_map<String, unsigned long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, unsigned long>>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::VirtualColumnsDescription const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnStatistics>, std::allocator<std::shared_ptr<DB::ColumnStatistics>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x0000000012b5a67b
20. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::shared_ptr<DB::IMergeTreeDataPart> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::vector<std::shared_ptr<DB::ColumnStatistics>, std::allocator<std::shared_ptr<DB::ColumnStatistics>>> const&, std::shared_ptr<DB::ICompressionCodec>, DB::TransactionID, bool, bool, DB::WriteSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x0000000012cada3b
21. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x0000000012a4060c
22. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x0000000012a472ce
23. DB::MergeTask::execute() @ 0x0000000012a4ff22
24. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000012d23bc0
25. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000012a6f99d
26. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000d740b38
27. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000d745c71
28. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000d74409f
29. ? @ 0x00007ff1e3ec5ac3
30. ? @ 0x00007ff1e3f57850
 (version 24.9.2.42 (official build))
```

### LINKED ISSUE #71906: Server memory usage increases gradually after upgrading from 24.7 to 24.10.
I have the MEMORY_LIMITE_EXCEEDED issue. The issue persists after upgrading the ClickHouse version from 24.7 to 24.10.

`Code: 241. DB::Exception: Memory limit (total) exceeded: would use 201.33 GiB (attempt to allocate chunk of 5171232 bytes), current RSS 6.25 GiB, maximum: 201.33 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker. (MEMORY_LIMIT_EXCEEDED) (version 24.10.1.2812 (official build))`

image
The graph used Prometheus' clickhouse_memory_tracking metric.
Graph was initialized when Clickhouse server restarted. Gradually it rises again afterwards. I'm restarting the server after a period of time.

I'm using the Kafka engine to consume the message and then using the MaterializedView engine to collect data in the MergeTree table.
There are about 200 such Kafka engines on this server.
It is inferred that memory leaks occur in the process of inserting data.

```
SELECT
    name,
    value
FROM system.metrics
WHERE name ILIKE '%background%'

    ┌─name────────────────────────────────────────┬─value─┐
 1. │ BackgroundMergesAndMutationsPoolTask        │     1 │
 2. │ BackgroundMergesAndMutationsPoolSize        │    64 │
 3. │ BackgroundFetchesPoolTask                   │     0 │
 4. │ BackgroundFetchesPoolSize                   │    64 │
 5. │ BackgroundCommonPoolTask                    │     0 │
 6. │ BackgroundCommonPoolSize                    │    16 │
 7. │ BackgroundMovePoolTask                      │     0 │
 8. │ BackgroundMovePoolSize                      │    16 │
 9. │ BackgroundSchedulePoolTask                  │     1 │
10. │ BackgroundSchedulePoolSize                  │   512 │
11. │ BackgroundBufferFlushSchedulePoolTask       │     0 │
12. │ BackgroundBufferFlushSchedulePoolSize       │    16 │
13. │ BackgroundDistributedSchedulePoolTask       │     0 │
14. │ BackgroundDistributedSchedulePoolSize       │   512 │
15. │ BackgroundMessageBrokerSchedulePoolTask     │   922 │
16. │ BackgroundMessageBrokerSchedulePoolSize     │  2000 │
17. │ TablesLoaderBackgroundThreads               │     0 │
18. │ TablesLoaderBackgroundThreadsActive         │     0 │
19. │ TablesLoaderBackgroundThreadsScheduled      │     0 │
20. │ MergeTreeBackgroundExecutorThreads          │    64 │
21. │ MergeTreeBackgroundExecutorThreadsActive    │    64 │
22. │ MergeTreeBackgroundExecutorThreadsScheduled │    64 │
23. │ KafkaBackgroundReads                        │   922 │
    └─────────────────────────────────────────────┴───────┘
```

The server's background pool settings are the same as above, and the pool size is sufficient.

May I know the cause?

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible overestimate memory tracking (difference between `MemoryTracking` and `MemoryResident` kept growing)

Before this patch the untracked_memory was dumped before reseting the current_thread which could lead to leaking some of untracked_memory in `ThreadStatus::detachFromGroup` [1].

In particular I found that the local_data (which is 136 bytes) can be "leaked" that way.

  [1]: https://github.com/ClickHouse/ClickHouse/blob/8999fdd95ea98fa083133d5cdf64ee149cd7f864/src/Interpreters/ThreadStatusExt.cpp#L292-L306

This pops up on one of clusters where I noticed that the difference between MemoryTracking and MemoryResident keeps growing over the time. the difference grows ~200KiB per second - 16.5GiB per day.

That cluster has tons MVs triggered from Buffer/Distributed (i.e. no query context), and this is indeed is the reason for leaking local_data, since in this case there is no thread group in the query, and it is created explicitly in `InterpreterInsertQuery::buildChain` [2].

  [2]: https://github.com/ClickHouse/ClickHouse/blob/20ccb638ba00103f116855afbc473950ef2b867b/src/Interpreters/InterpreterInsertQuery.cpp#L321

Fixes: #71511
Fixes: #71906
_Example of stacktrace: https://gist.github.com/azat/96a015046ebe72ddcb59bc89ca91a20e_

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 88bf43724c6a9d70da6af34f12a5b0d52a86c79a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73081/88bf43724c6a9d70da6af34f12a5b0d52a86c79a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/787cf7db896201bbecb3b5ae2e5d7b96082e925a/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by niki-timofe — APPROVED** [review]

File: src/Common/ThreadStatus.cpp [hunk 1]
```diff
@@ -228,6 +226,9 @@ ThreadStatus::~ThreadStatus()
 
     chassert(!check_current_thread_on_destruction || current_thread == this);
 
+    /// Flush untracked_memory **before** switching the current_thread (to avoid losing untracked_memory)
```
Comment (Algunenano) [inline src/Common/ThreadStatus.cpp:229]: This comment is quite confusing as is. It should say something like `Flush untracked_memory **after** calling deleter()`, right?

Comment (Algunenano) [inline src/Common/ThreadStatus.cpp:229]:
```suggestion
    /// Flush untracked_memory **right before** switching the current_thread to avoid losing untracked_memory in deleter (detachFromGroup)
```
