### PR TITLE
Fix flaky 00156_max_execution_speed_sample_merge

### LINKED ISSUE #92641: Flaky test: 00156_max_execution_speed_sample_merge
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: 00156_max_execution_speed_sample_merge
Failure reason: DB::Exception: Estimated query execution time (827.38894 seconds) is too long
CI report: [Stateless tests (arm_binary, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92372&sha=b05cc66744836302d69f3929cc8f3b953d8f3089&name_0=PR&name_1=Stateless%20tests%20%28arm_binary%2C%20parallel%29)

CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMDE1Nl9tYXhfZXhlY3V0aW9uX3NwZWVkX3NhbXBsZV9tZXJnZScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0YXRlbGVzcyB0ZXN0cyAoYXJtX2JpbmFyeSwgcGFyYWxsZWwpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
2025-12-17 07:47:09 Reason: return code:  160
2025-12-17 07:47:09 [2b0c76c57283] 2025.12.17 06:47:08.815163 [ 427673 ] {109d6427-4bd4-41ac-a56f-1e98f960dcf5} <Error> executeQuery: Code: 160. DB::Exception: Estimated query execution time (827.38894 seconds) is too long. Maximum: 600. Estimated rows to process: 8374186 (51819 read in 5.11984 seconds): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (TOO_SLOW) (version 25.12.1.597) (from [::1]:34520) (comment: 00156_max_execution_speed_sample_merge.sql-test_j70s5lt7) (query 5, line 8) (in query: SELECT count() FROM test.hits_s3 SAMPLE 1 / 2;), Stack trace (when copying this message, always include the lines below):
2025-12-17 07:47:09 
2025-12-17 07:47:09 0. ./ci/tmp/build/./base/poco/Foundation/src/Exception.cpp:28: Poco::Exception::Exception(String const&, int) @ 0x000000001e5e0eb8
2025-12-17 07:47:09 1. ./ci/tmp/build/./src/Common/Exception.cpp:131: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000010e32a8c
2025-12-17 07:47:09 2. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000ab3ca58
2025-12-17 07:47:09 3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000ab3c56c
2025-12-17 07:47:09 4. ./src/Common/Exception.h:141: DB::Exception::Exception<double&, int, unsigned long&, unsigned long&, double&>(int, FormatStringHelperImpl<std::type_identity<double&>::type, std::type_identity<int>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<double&>::type>, double&, int&&, unsigned long&, unsigned long&, double&) @ 0x000000001587a628
2025-12-17 07:47:09 5. ./ci/tmp/build/./src/QueryPipeline/ExecutionSpeedLimits.cpp:87: DB::ExecutionSpeedLimits::throttle(unsigned long, unsigned long, unsigned long, unsigned long, DB::OverflowMode) const @ 0x000000001587a238
2025-12-17 07:47:09 6. ./ci/tmp/build/./src/QueryPipeline/ReadProgressCallback.cpp:107: DB::ReadProgressCallback::onProgress(unsigned long, unsigned long, std::list<DB::StorageLimits, std::allocator<DB::StorageLimits>> const&) @ 0x0000000015879b7c
2025-12-17 07:47:09 7. ./ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:68: DB::ExecutionThreadContext::executeTask() @ 0x0000000019a9b998
2025-12-17 07:47:09 8. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x0000000019a8f6ec
2025-12-17 07:47:09 9. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000019a8edc0
2025-12-17 07:47:09 10. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000019a8e9c8
2025-12-17 07:47:09 11. ./ci/tmp/build/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_func<void ()>::__call_func[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()>(std::__function::__policy_storage const*) @ 0x0000000019aa3ad0
2025-12-17 07:47:09 12. ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ? @ 0x0000000010f68dac
2025-12-17 07:47:09 13. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: void* std::__thread_proxy[abi:ne210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000010f6e148
2025-12-17 07:47:09 14. ? @ 0x0000000000080398
2025-12-17 07:47:09 15. ? @ 0x00000000000e9e9c
2025-12-17 07:47:09 
2025-12-17 07:47:09 Received exception from server (version 25.12.1):
2025-12-17 07:47:09 Code: 160. DB::Exception: Received from localhost:9000. DB::Exception: Estimated query execution time (827.38894 seconds) is too long. Maximum: 600. Estimated rows to process: 8374186 (51819 read in 5.11984 seconds): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (TOO_SLOW)
2025-12-17 07:47:09 (query: SELECT count() FROM test.hits_s3 SAMPLE 1 / 2;)
2025-12-17 07:47:09 , result:
2025-12-17 07:47:09 
2025-12-17 07:47:09 
2025-12-17 07:47:09 
2025-12-17 07:47:09 stdout:
2025-12-17 07:47:09 
2025-12-17 07:47:09 
2025-12-17 07:47:09 Settings used in the test: --max_insert_threads 1 --group_by_two_level_threshold 1 --group_by_two_level_threshold_bytes 25088267 --distributed_aggregation_memory_efficient 0 --fsync_metadata 0 --output_format_parallel_formatting 0 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 12339174 --max_read_buffer_size 713065 --prefer_localhost_replica 1 --max_block_size 51819 --max_joined_block_size_rows 19288 --joined_block_split_single_row 0 --join_output_by_rowlist_perkey_rows_threshold 484 --max_threads 1 --optimize_append_index 0 --use_hedged_requests 0 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 34 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 38091693 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 3712255485 --min_bytes_to_use_mmap_io 1 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 10 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 0 --filesystem_prefetch_step_bytes 0 --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 1 --merge_tree_coarse_index_granularity 7 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 2945970738 --min_compress_block_size 2702285 --max_compress_block_size 2284099 --merge_tree_compact_parts_min_granules_to_multibuffer_read 36 --optimize_sorting_by_input_stream_properties 0 --http_response_buffer_size 5654774 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 3 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone America/Mazatlan --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.48 --prefer_external_sort_block_bytes 100000000 --cross_join_min_rows_to_compress 1 --cross_join_min_bytes_to_compress 0 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 0 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 0 --query_plan_join_swap_table auto --enable_vertical_final 1 --optimize_extract_common_expressions 1 --use_async_executor_for_materialized_views 1 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 0 --use_skip_indexes_on_data_read 1 --optimize_rewrite_like_perfect_affix 1 --input_format_parquet_use_native_reader_v3 0 --enable_lazy_columns_replication 1 --allow_special_serialization_kinds_in_output_formats 0 --max_bytes_before_external_sort 0 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0.0 --max_bytes_ratio_before_external_group_by 0.0 --use_skip_indexes_if_final_exact_mode 0
2025-12-17 07:47:09 
2025-12-17 07:47:09 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 6559083929 --vertical_merge_algorithm_min_rows_to_activate 334223 --vertical_merge_algorithm_min_columns_to_activate 90 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 10521124118 --index_granularity_bytes 28721010 --merge_max_block_size 164 --index_granularity 47736 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 32677 --primary_key_compress_block_size 66241 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 339766741 --compact_parts_max_granules_to_buffer 106 --compact_parts_merge_max_bytes_to_prefetch_part 18880279 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 62 --old_parts_lifetime 17 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --object_serialization_version v3 --object_shared_data_serialization_version map_with_buckets --object_shared_data_serialization_version_for_zero_level_parts map --object_shared_data_buckets_for_compact_part 24 --object_shared_data_buckets_for_wide_part 24 --dynamic_serialization_version v3 --serialization_info_version with_types --string_serialization_version single_stream --nullable_serialization_version allow_sparse --enable_shared_storage_snapshot_in_query 1
2025-12-17 07:47:09 
2025-12-17 07:47:09 Database: test_j70s5lt7
```

### PR DESCRIPTION
**Pull request by arsenmuk**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry:
Closes #92641

### Version info
- Merged into: `26.1.1.626`

### CODE REVIEW

**Review by tuanpach — DISMISSED** [review]

**Comment by tuanpach** [comment]
Some settings might slow down the query:

max_block_size=10319, max_threads=1 are too small
remote_filesystem_read_prefetch=0 - Prefetching is disabled.

I think we can increase `max_threads`, `max_block_size`, and enable `remote_filesystem_read_prefetch`. E.g:
```
SET max_threads = 8;
SET max_block_size = 65536;
SET remote_filesystem_read_prefetch = 1;
```
Not sure if it can help.

**Comment by arsenmuk** [comment]
> Some settings might slow down the query:
> ...

@tuanpach thanks for taking a look. I root caused why it was flapping originally, there were two main reasons:
- minio.s3 been hanging sometimes
- selection of 1/2 of test.hits_s3 was large-ish, and with s3 hanging both led to 1min+ timings

EDITED: I changed data source to be a simple tiny synthetic table, which shouldn't stuck or flap anymore. Also exclusion of sanitizers which I originally planned to rely on, is not longer necessary.

File: tests/queries/0_stateless/00156_max_execution_speed_sample_merge.sql [hunk 1]
```diff
@@ -1,18 +1,31 @@
...
-SELECT count() FROM test.hits_s3 SAMPLE 1 / 2;
+SELECT * FROM t00156_max_execution_speed_sample_merge WHERE sleepEachRow(0.1) == 0 FORMAT Null;
 INSERT INTO times SELECT now();
 
 SELECT max(t) - min(t) >= 1 FROM times;
 TRUNCATE TABLE times;
 
 INSERT INTO times SELECT now();
-SELECT count() FROM merge(test, '^hits_s3$') SAMPLE 1 / 2;
+SELECT * FROM t00156_max_execution_speed_sample_merge WHERE sleepEachRow(0.1) == 0 FORMAT Null;
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/00156_max_execution_speed_sample_merge.sql:28]: This definitely changed the test by lacking `merge` storage. @arsenmuk will create a PR to fix this.

Comment (arsenmuk) [reply tests/queries/0_stateless/00156_max_execution_speed_sample_merge.sql:28]: My secret strategy to fight with flakiness - just to test something else😆

It's fixed now - https://github.com/ClickHouse/ClickHouse/pull/100441
