### PR TITLE
Fix max parser depth

### LINKED ISSUE #10283: clickhouse-client segfaults on a long query
The query is like `select coalesce(null, coalesce(null, ....repeat 1000x...., 1) ... )`:

```
$ { printf "select "; for x in {1..1000}; do printf "coalesce(null, "; done; printf "1"; for x in {1..1000}; do printf ")"; done; } | clickhouse-client
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the issue with limiting maximum recursion depth in parser in certain cases. This fixes #10283 This fix may introduce minor incompatibility: long and deep queries via clickhouse-client may refuse to work, and you should adjust settings `max_query_size` and `max_parser_depth` accordingly.

### CODE REVIEW

File: src/Interpreters/tests/logical_expressions_optimizer.cpp [hunk 1]
```diff
@@ -1,295 +0,0 @@
-#include <Parsers/ASTSelectQuery.h>
```
Comment (alexey-milovidov) [inline src/Interpreters/tests/logical_expressions_optimizer.cpp:1]: Old non-automated test was deleted.

**Review by akuzm — APPROVED** [review]
The default parameter strikes again. I'm surprised we have so many parser calls.

**Comment by alexey-milovidov** [comment]
FYI clang-tidy has an option to prohibit default parameters at all. But it's too hard to enforce in our code base. Currently we have turned on an option to prohibit default parameters in virtual methods.
