### PR TITLE
Fix TTL column validation in ALTER MODIFY ORDER BY

### LINKED ISSUE #84442: `ALTER MODIFY ORDER BY` does not check if the new column has TTL
### Company or project name

ClickHouse Inc.

### Describe what's wrong

`ALTER TABLE ADD COLUMN` with_ttl `String TTL event_time + toIntervalDay(30), MODIFY ORDER BY (..., with_ttl)` works and breaks the `clickhouse-server` completely.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

https://fiddle.clickhouse.com/ad972e7d-aa00-450b-8fe5-79531f797031 - broken in 24.11
https://fiddle.clickhouse.com/3f7adaa2-ee51-4173-9012-3f8028aec672 - broken in the latest release
https://fiddle.clickhouse.com/6923a88d-1910-44bd-bb9c-4cd46ea369d2 - broken in master

### Expected behavior

`ALTER` shouldn't allow the wrong TTL

### Error message and/or stacktrace

```
Received exception from server (version 25.8.1):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Trying to set TTL for key column destination_address. (ILLEGAL_COLUMN)
(query: ATTACH TABLE test_break_ddl;)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiaohuanlin**
Fixes #84442
- Add TTL column validation in checkTTLExpressions()
- Check both old and new metadata for TTL constraints in sorting keys
- Add test case to verify TTL columns are rejected in ORDER BY

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
- Fix ALTER MODIFY ORDER BY not validating TTL columns in sorting keys. TTL columns are now properly rejected when used in ORDER BY clauses during ALTER operations, preventing potential table corruption.

### CODE REVIEW

**Comment by xiaohuanlin** [comment]
1. 00002_log_and_exception_messages_formatting: `DB::Exception: avro::Exception: Cannot read compressed data, expected at least 4 bytes, got 0.`
2. 00816_long_concurrent_alter_column: `Timeout`
3. 01825_new_type_json_ghdata_insert_select: Difference between two json strings.
```
2025-07-28 04:22:08 -('payload.commits',['Array(JSON(max_dynamic_types=16, max_dynamic_paths=25))','Array(Nullable(String))'])
2025-07-28 04:22:08 +('payload.commits',['Array(JSON(max_dynamic_types=16, max_dynamic_paths=25))'])
```

I have no idea how to fix these problems. Could you help me? Locally, the second and third tests pass, and the first test shows a different message: 
```
| 2025-07-29 08:17:20 [01adb4dc380b] 2025.07.29 03:17:20.675256 [ 1542 ] {021d8374-e92c-4aea-9e0c-ed4f40f13628} <Error> executeQuery: Code: 125. DB::Exception: Scalar subquery returned empty result of type Tuple(LowCardinality(String), UInt64) which cannot be Nullable. (INCORRECT_RESULT_OF_SCALAR_SUBQUERY) (version 25.8.1.1) (from 127.0.0.1:57000) (comment: 00002_log_and_exception_messages_formatting.sql) (query 17, line 248) (in query: -- Same as above for Error
```

**Comment by Felixoid** [comment]
The [00002_log_and_exception_messages_formatting](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMDAwMl9sb2dfYW5kX2V4Y2VwdGlvbl9tZXNzYWdlc19mb3JtYXR0aW5nJyBBUyBuYW1lX3N1YnN0ciwKICAgIDkwIEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJywgJ0ludGVncmF0aW9uIHRlc3RzIChhc2FuKSBbMS8zXScsICdTdGF0ZWxlc3MgdGVzdHMgKHRzYW4pIFsxLzNdJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=) is broken in master

[00816_long_concurrent_alter_column](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMDgxNl9sb25nX2NvbmN1cnJlbnRfYWx0ZXJfY29sdW1uJyBBUyBuYW1lX3N1YnN0ciwKICAgIDkwIEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJywgJ0ludGVncmF0aW9uIHRlc3RzIChhc2FuKSBbMS8zXScsICdTdGF0ZWxlc3MgdGVzdHMgKHRzYW4pIFsxLzNdJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=) fails exactly the same way in another PR. Looks like it's recently broken, but I am not sure yet

[01825_new_type_json_ghdata_insert_select](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMTgyNV9uZXdfdHlwZV9qc29uX2doZGF0YV9pbnNlcnRfc2VsZWN0JyBBUyBuYW1lX3N1YnN0ciwKICAgIDkwIEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJywgJ0ludGVncmF0aW9uIHRlc3RzIChhc2FuKSBbMS8zXScsICdTdGF0ZWxlc3MgdGVzdHMgKHRzYW4pIFsxLzNdJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=) is broken as well.

These failures are highly unlikely to be related to the changes.

And the building error is being addressed in the https://github.com/ClickHouse/ClickHouse/pull/84674

File: tests/queries/0_stateless/03578_ttl_column_in_order_by_validation.sql [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ENGINE = ReplacingMergeTree()
+PARTITION BY event_date
+ORDER BY (id, event_date, event_time);
+
+ALTER TABLE test_break_ddl
+    ADD COLUMN `source_address` String TTL event_time + toIntervalDay(30) AFTER event_time,
+    ADD COLUMN `destination_address` String TTL event_time + toIntervalDay(30) AFTER source_address,
+    MODIFY ORDER BY (id, event_date, event_time, source_address, destination_address); -- { serverError ILLEGAL_COLUMN }
+
+DROP TABLE IF EXISTS test_break_ddl;
```
Comment (Felixoid) [inline tests/queries/0_stateless/03578_ttl_column_in_order_by_validation.sql]:
```suggestion
DROP TABLE IF EXISTS test_break_ddl;

```

Thanks for the fix! A nit thing to fix `noeol` and restart CI

**Review by Felixoid — APPROVED** [review]

**Comment by xiaohuanlin** [comment]
@Felixoid Thanks for the update. However, I still see some failed tests. Do they pass occasionally?

**Comment by Felixoid** [comment]
All failures are known:

LOGICAL_ERROR for 03208_multiple_joins_with_storage_join https://github.com/ClickHouse/ClickHouse/issues/74360
00002_log_and_exception_messages_formatting https://github.com/ClickHouse/ClickHouse/issues/84642
Dying stress tests https://github.com/ClickHouse/ClickHouse/issues/84669
flaky integration test https://github.com/ClickHouse/ClickHouse/issues/84847


Thanks a lot, I am merging it

**Comment by Felixoid** [comment]
Every release has this fix included. Thank you once again.
