### PR TITLE
Fix index corruption in merges with compact parts.

### LINKED ISSUE #10487: Couple of broken parts appear per day without any log indication
**Describe the bug**
Parts are broken either due to upgrade or switching to compact mode. No logs associated with timestamp of those parts is available, they are only identified on startup of clickhouse (and if number of broken parts exceed limit, they block the table initialization). 

**How to reproduce**
Currently unclear, random parts are broken across days, and when clickhouse is restarted it gives error. 
Two things that may have caused it:
- System was upgraded from 19.17.6.36 to 20.3.7, then 20.3.8 (both had issue)
- min_rows_for_wide_part was configured to 90000 (average insert size is 50k rows, maximum 100-150k rows)

* 20.3.7, 20.3.8
* Data loading is being made using clickhouse-client
* min_rows_for_wide_part - but it's unclear that problem is due to that. It's worth noting that all broken parts were compact. However, there were many other compact parts that were not broken. 
* all of broken parts fail with same error: "path/primary.idx is unexpectedly long"
* Not caused by any specific external event, no correlation to kernel or clickhouse logs. 

**Expected behavior**
There shall be no broken parts. 

**Error message and/or stacktrace**

table/schema has been anonimized. 

```

2020.04.24 10:58:16.110142 [ 177089 ] {} <Error> DB::MergeTreeData::loadDataParts(bool)::<lambda()>: Code: 4, e.displayText() = DB::Exception: Index file /datadisk/data/SCHEMA/table_name/20200420-22-0_1084805_1084810_2/primary.idx is unexpectedly long, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10542450 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4272d in /usr/bin/clickhouse
2. ? @ 0xd8cf004 in /usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0xd8ca19d in /usr/bin/clickhouse
4. ? @ 0xd8fbba2 in /usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8f6792b in /usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const @ 0x8f68608 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f667eb in /usr/bin/clickhouse
8. ? @ 0x8f64c33 in /usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfe8cd in /usr/lib64/libc-2.17.so
 (version 20.3.8.53 (official build))
2020.04.24 10:58:16.110191 [ 177089 ] {} <Error> SCHEMA.table_name: Part /datadisk/data/SCHEMA/table_name/20200420-22-0_1084805_1084810_2 is broken. Looking for parts to replace it.
2020.04.24 10:58:16.111045 [ 177089 ] {} <Error> SCHEMA.table_name: Detaching broken part /datadisk/data/SCHEMA/table_name/20200420-22-0_1084805_1084810_2 because it covers less than 2 parts. You need to resolve this manually 
```

Anonymized DDL of the table. 
[clickhouse-issue-10487.sql.txt](https://github.com/ClickHouse/ClickHouse/files/4531010/clickhouse-issue-10487.sql.txt)

**Additional context**
Currently it's not so clear on how to reproduce the problem.

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix index corruption, which may accur in some cases after merge compact parts into another compact part.

Detailed description / Documentation draft:
In compact parts when we write block, that it is smaller `index_granularity` more than 2 times, we append it to previous granule. `index_offset` should be increased in that case, because otherwise extra index row could be written.

Fixes #10487.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp [hunk 1]
```diff
@@ -163,6 +166,49 @@ void MergeTreeDataPartWriterCompact::finishDataSerialization(IMergeTreeDataPart:
     stream.reset();
 }
 
+void fillIndexGranularityImpl(
```
Comment (alesapin) [inline src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:169]: static or anonymous namespace?

File: src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp [hunk 2]
```diff
@@ -163,6 +166,49 @@ void MergeTreeDataPartWriterCompact::finishDataSerialization(IMergeTreeDataPart:
...
+        }
+        else
+        {
+            index_granularity.appendMark(index_granularity_for_block);
+        }
+    }
+
+    /// Primary index shouldn't be written, if there was no granule added
+    if (initial_marks_count == index_granularity.getMarksCount())
+        index_offset = std::max(index_offset, rows_in_block);
```
Comment (alesapin) [inline src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:200]: I don't understand why it helps :( Very complicated logic of `index_offset` update.

Comment (CurtizJ) [reply src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:200]: It helps, because [here](https://github.com/ClickHouse/ClickHouse/blob/d952e5aba22586f94db89705e452a8266506c209/src/Storages/MergeTree/IMergeTreeDataPartWriter.cpp#L228) we won't run loop. But I agree, that it's became too complicated. I'll try to rewrite this part of code.

**Review by alesapin — APPROVED** [review]
LGTM.
