### PR TITLE
Fix empty Tuple permutation with limit

### LINKED ISSUE #86369: SIZES_OF_COLUMNS_DOESNT_MATCH with empty tuple on order by key
### Describe the bug

Happens since v25.3

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/45c446aa-4b67-46bd-a0b8-da09ea60837b

### Error message and/or stacktrace

Stack trace:

```
<Error> TCPHandler: Code: 9. DB::Exception: Size of permutation doesn't match size of column. (SIZES_OF_COLUMNS_DOESNT_MATCH), Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000002730ef32
1. ci/tmp/build/./src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000144149a9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d0370ce
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d036ad1
4. src/Common/Exception.h:141: DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000d042db6
5. ci/tmp/build/./src/Columns/ColumnTuple.cpp:435: DB::ColumnTuple::permute(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, unsigned long) const @ 0x000000001dfca6cb
6. ci/tmp/build/./src/Columns/ColumnVariant.cpp:1067: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ColumnVariant::indexImpl<unsigned long>(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, unsigned long) const @ 0x000000001e0b1f2c
7. src/Columns/ColumnsCommon.h:125: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::selectIndexImpl<DB::ColumnVariant>(DB::ColumnVariant const&, DB::IColumn const&, unsigned long) @ 0x000000001e0aca62
8. ci/tmp/build/./src/Columns/ColumnVariant.cpp:1026: DB::ColumnVariant::index(DB::IColumn const&, unsigned long) const @ 0x000000001e0a703e
9. ci/tmp/build/./src/Columns/ColumnArray.cpp:954: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ColumnArray::indexImpl<unsigned long>(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, unsigned long) const @ 0x000000001ddfc19f
10. src/Columns/ColumnsCommon.h:136: DB::ColumnArray::permute(DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, unsigned long) const @ 0x000000001ddf8112
11. ci/tmp/build/./src/Interpreters/sortBlock.cpp:359: DB::sortBlock(DB::Block&, DB::SortDescription const&, unsigned long, DB::IColumn::PermutationSortStability) @ 0x000000001b82a103
12. ci/tmp/build/./src/Processors/Transforms/PartialSortingTransform.cpp:137: DB::PartialSortingTransform::transform(DB::Chunk&) @ 0x000000001f4df2aa
13. src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x0000000017cdb913
14. ci/tmp/build/./src/Processors/ISimpleTransform.cpp:98: DB::ISimpleTransform::work() @ 0x000000001f1ea60a
15. ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001f209510
16. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f1fc245
17. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:278: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001f1fc7a9
18. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:598: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001f1face1
19. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001f1fa3ff
20. ci/tmp/build/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001f211764
21. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001455e766
22. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000014565180
23. start_thread @ 0x00000000000a27f1
24. __GI___clone3 @ 0x0000000000133c9c
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix empty Tuple permutation with limit.

Closes https://github.com/ClickHouse/ClickHouse/issues/86369

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03613_empty_tuple_permute_with_limit.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+SELECT 1 FROM numbers(3) ORDER BY [1, tuple(1)]  FETCH FIRST 1 ROW ONLY SETTINGS allow_suspicious_types_in_order_by = 1, use_variant_as_common_type = 1;
```
Comment (devcrafter) [inline tests/queries/0_stateless/03613_empty_tuple_permute_with_limit.sql]: The fiddle in bug report contains a slightly different query (with empty tuple())
```suggestion
SELECT 1 FROM numbers(3) ORDER BY [1, ()] OFFSET 1 ROWS FETCH FIRST 1 ROW ONLY SETTINGS allow_suspicious_types_in_order_by = 1, use_variant_as_common_type = 1;
```

Comment (Avogar) [reply tests/queries/0_stateless/03613_empty_tuple_permute_with_limit.sql]: Rightm messed up queries during testing, thanks for noticing!

**Comment by Avogar** [comment]
[Stateless tests (amd_tsan, parallel, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86828&sha=60cc8ca62091b02aa19eeb253ab7bbf79ab74de8&name_0=PR&name_1=Stateless+tests+%28amd_tsan%2C+parallel%2C+2%2F2%29) - test `03293_tty_binary_confirmation` failed due to timeout, it's a very rare failre (there are no such failures for last few months), so I don't think we need to create an issue for it for now.
[Stress test (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86828&sha=60cc8ca62091b02aa19eeb253ab7bbf79ab74de8&name_0=PR&name_1=Stress+test+%28arm_asan%29) - https://github.com/ClickHouse/ClickHouse/issues/84186

**Review by devcrafter — APPROVED** [review]
