### PR TITLE
Fix SummingMergeTree incorrectly summing Bool columns

### LINKED ISSUE #39965: SummingMergeTree may sum bool type and may make an incoherent filtering
**Describe the unexpected behaviour**
When using a table with a `SummingMergeTree` engine, and using a `Bool` type on a field outside the `ORDER BY`, a potential incoherent filtering may happens for the final user.

**How to reproduce**
Reproduced with ClickHouse server version 22.7.2 revision 54457.

```
CREATE TABLE foo
(
    `id` UInt32,
    `had_even_value` Bool
)
ENGINE = SummingMergeTree
ORDER BY id;

INSERT INTO foo (id, had_even_value) SELECT
    1,
    number % 2
FROM system.numbers
LIMIT 10;

SELECT *
FROM foo;

Query id: 7b3ca77c-888e-4e00-b99d-4f1258def76d

┌─id─┬─had_even_value─┐
│  1 │ true           │
└────┴────────────────┘

1 row in set. Elapsed: 0.002 sec. 

SELECT *
FROM foo
WHERE had_even_value = true;

Query id: efa02b94-a39b-4550-b170-aeac3dbf3d18

Ok.

0 rows in set. Elapsed: 0.004 sec. 

SELECT *
FROM foo
WHERE had_even_value != true

Query id: 2ee700df-3a3f-44f3-b159-da46eb9b52e2

┌─id─┬─had_even_value─┐
│  1 │ true           │
└────┴────────────────┘


SELECT toUInt8(had_even_value)
FROM foo

Query id: e15341f9-8c21-4ff6-a556-a72bd3100a66

┌─toUInt8(had_even_value)─┐
│                       5 │
└─────────────────────────┘

1 row in set. Elapsed: 0.003 sec. 
```

**Expected behavior**
Concerning the filtering part, I think than most of the users will still expect than if we filter a field to `true` regardless his underlying implementation and whatever the operator we use.

However, concerning the internal representation in a `SummingMergeTree` for a `Bool` type is a different question and I don't have a "convenient" solution for it. Has summing a value is a potential correct behavior, but as not summing at all may be as well as it's a type who may only accept two values.

### PR DESCRIPTION
**Pull request by Onyx2406**
### Changelog category (leave one):
- Bug Fix

### Changelog entry
SummingMergeTree no longer sums Bool (and other domain type) columns. Bool values are kept as-is instead of being arithmetically summed.

Fixes #39965

### What this PR does

**The bug:** `Bool` is a domain type over `UInt8`. Since `DataTypeNumber<UInt8>::isSummable()` returned `true`, SummingMergeTree arithmetically summed Bool values. For example, `true + true + false = 3`, which is not a valid Bool. This caused broken filtering:

```sql
SELECT * FROM table WHERE flag = true;  -- returns 0 rows
SELECT * FROM table WHERE flag != true; -- returns the row with value 3
```

As noted by @alexey-milovidov: "Should be easy to improve, see `IDataType.h::isSummable()`"

**The fix (1 line):** Change `DataTypeNumber::isSummable()` from `return true` to `return !this->hasCustomName()`. Domain types (Bool, IPv4, IPv6) set a custom name via the domain registration system. If a numeric type has a custom name, it carries semantic meaning that makes arithmetic summation invalid:
- `Bool`: true/false logic, not arithmetic
- `IPv4`: network addresses, not numbers
- `IPv6`: same

Regular numeric types (`UInt8`, `UInt32`, `Float64`, etc.) don't have custom names, so they remain summable.

**Also fixes** the IPv4 summation issue mentioned in the same issue thread by @YiuRULE.

### Test Plan

- [x] New stateless test verifying Bool column stays valid after SummingMergeTree OPTIMIZE
- [ ] CI (full test suite)

### Documentation entry for user-facing changes

- [x] Documentation is not required (bug fix restoring expected behavior)

---

> [!NOTE]
> **Medium Risk**
> Changes how `isSummable()` is computed for all `DataTypeNumber` instances with custom names, which can alter merge results for domain types (e.g., Bool/IPv4/IPv6) in `SummingMergeTree`/related merges. Low implementation complexity, but impacts data aggregation semantics and could change query results for existing tables.
> 
> **Overview**
> Fixes `DataTypeNumber::isSummable()` to return false for custom-named numeric domain types (via `hasCustomName()`), so `SummingMergeTree` no longer arithmetically sums columns like `Bool` when implicit summing columns are used.
> 
> Adds a stateless regression test that creates a `SummingMergeTree` table with a `Bool` flag, merges rows, and asserts the flag remains a valid boolean (first value) while regular numeric columns are still summed.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6497a19c392f86f034e105a69cac4525178f2d4a. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]
This is perfect, thank you!

File: tests/queries/0_stateless/04033_summingmergetree_bool_not_summable.sql [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+DROP TABLE IF EXISTS test_summing_bool;
+
+CREATE TABLE test_summing_bool
+(
+    `id` UInt32,
+    `count` UInt64,
+    `flag` Bool
+)
+ENGINE = SummingMergeTree(count)
```
[the remark this answers is not in the document]
Comment (alexey-milovidov) [reply tests/queries/0_stateless/04033_summingmergetree_bool_not_summable.sql]: Yes, cursor is right here. Please correct the test.

**Review by alexey-milovidov — APPROVED** [review]

File: src/DataTypes/DataTypesNumber.h [hunk 2]
```diff
@@ -24,7 +24,7 @@ class DataTypeNumber final : public DataTypeNumberBase<T>
     bool equals(const IDataType & rhs) const override { return typeid(rhs) == typeid(*this); }
 
     bool canBeUsedAsVersion() const override { return true; }
-    bool isSummable() const override { return true; }
+    bool isSummable() const override { return !this->hasCustomName(); }
```
Comment (alexey-milovidov) [inline src/DataTypes/DataTypesNumber.h:29]: Missing a comment explaining this change.

Comment (alexey-milovidov) [inline src/DataTypes/DataTypesNumber.h:29]:
```suggestion
    /// Custom data types with numeric representations are not necessarily summable.
    /// For example, the `Bool` type isn't.
    bool isSummable() const override { return !this->hasCustomName(); }
```

**Review by alexey-milovidov — APPROVED** [review]

**Comment by fm4v** [comment]
This was reverted: https://github.com/ClickHouse/ClickHouse/pull/106729
