### PR TITLE
Disable collecting job stack traces by default

### LINKED ISSUE #76112: Performance regression at recent versions (starting 24.11)
### Company or project name

_No response_

### Describe what's wrong

Hey,
After upgrading from 24.7 to 24.12 or 25.01, we've seen a major performance regression in multiple queries. We tried to pinpoint the exact version where we see the regression from, and it looks like upgrading from 24.10 to 24.11 causes the issue.
 
Here's an example query affected by the regression:
```
 
SELECT COUNT()
FROM dbname.dist_Table
WHERE Column1 LIKE '%SampleText%'
```
In version 24.10 this query processes 77.2B rows in 70 seconds, while in 24.11 it takes 159 seconds (over two times slower).
 
The table definition is:
```
CREATE TABLE dbname.local_Table
(
`Column2` String,
`Column3` DateTime64(3),
`Column4` DateTime64(3),
`Column5` Int32,
`Column6` UUID,
`Column7` Int32,
`Column1` String,
`Column8` DateTime64(3),
`Column9` DateTime64(3),
`Column10` Int64,
`Column11` String,
`Column12` String,
`Column13` String,
`Column14` Int32,
`Column15` String,
`Column16` String,
`Column17` Bool,
`Column18` Bool
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/3d89e983-d0c9-42a8-854c-ef681d2c704b/{shard}', '{replica}')
PARTITION BY toYYYYMM(Column3)
ORDER BY (Column5, Column3)
SETTINGS index_granularity = 8192
 
CREATE TABLE dist_Table AS local_table ENGINE=Distributed('{cluster}', dbname, local_Table, rand());
```
 
The servers are running RHEL 8.6, has 2x  Xeon Gold 6148 CPU's,  and 1.5TB RAM each.
 
Here are the logs from v24.10 (fast execution):
```
Query id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0
 
Connecting to srvL002.domain.com:9000 as user sa.
Connected to ClickHouse server version 24.10.4.
 
ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.
 
[srvl002.domain.com] 2025.02.08 20:37:47.870239 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> executeQuery: (from 192.168.1.29:52839, user: sa) SELECT COUNT() FROM dbname.dist_Table WHERE Column1 LIKE '%SampleText%' (stage: Complete)
[srvl002.domain.com] 2025.02.08 20:37:47.871690 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl002.domain.com] 2025.02.08 20:37:47.872110 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl002.domain.com] 2025.02.08 20:37:47.891432 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 108/108 parts by partition key, 108 parts by primary key, 1125006/1125006 marks by primary key, 1125006 marks to read from 108 ranges
[srvl002.domain.com] 2025.02.08 20:37:47.893020 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8785002100 rows with 40 streams
[srvl002.domain.com] 2025.02.08 20:37:47.900975 [ 2035606 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL006.domain.com:9000): Sent data for 2 scalars, total 2 rows in 5.9388e-05 sec., 33054 rows/sec., 68.00 B (1.07 MiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.32 MiB/sec.)
[srvl006.domain.com] 2025.02.08 20:37:47.901237 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> executeQuery: (from 192.162.3.15:37252, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl002.domain.com] 2025.02.08 20:37:47.901843 [ 2035475 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL004.domain.com:9000): Sent data for 2 scalars, total 2 rows in 6.8931e-05 sec., 28481 rows/sec., 68.00 B (945.14 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.01 MiB/sec.)
[srvl002.domain.com] 2025.02.08 20:37:47.902686 [ 2038281 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL012.domain.com:9000): Sent data for 2 scalars, total 2 rows in 5.6749e-05 sec., 34674 rows/sec., 68.00 B (1.12 MiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.44 MiB/sec.)
[srvl004.domain.com] 2025.02.08 20:37:47.902258 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> executeQuery: (from 192.162.3.15:37434, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl012.domain.com] 2025.02.08 20:37:47.903394 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> executeQuery: (from 192.162.3.15:35434, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl002.domain.com] 2025.02.08 20:37:47.906580 [ 2038266 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL007.domain.com:9000): Sent data for 2 scalars, total 2 rows in 9.4789e-05 sec., 20595 rows/sec., 68.00 B (682.59 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (1.45 MiB/sec.)
[srvl002.domain.com] 2025.02.08 20:37:47.907067 [ 2037437 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL005.domain.com:9000): Sent data for 2 scalars, total 2 rows in 0.000174735 sec., 11354 rows/sec., 68.00 B (376.76 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (819.47 KiB/sec.)
[srvl002.domain.com] 2025.02.08 20:37:47.907365 [ 2038288 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL019.domain.com:9000): Sent data for 2 scalars, total 2 rows in 8.0564e-05 sec., 24522 rows/sec., 68.00 B (813.83 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (1.73 MiB/sec.)
[srvl002.domain.com] 2025.02.08 20:37:47.909685 [ 2035803 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Connection (srvL018.domain.com:9000): Sent data for 2 scalars, total 2 rows in 9.8172e-05 sec., 20151 rows/sec., 68.00 B (666.11 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (1.41 MiB/sec.)
[srvl007.domain.com] 2025.02.08 20:37:47.907072 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> executeQuery: (from 192.162.3.15:57066, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl005.domain.com] 2025.02.08 20:37:47.907348 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> executeQuery: (from 192.162.3.15:39062, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl018.domain.com] 2025.02.08 20:37:47.910412 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> executeQuery: (from 192.162.3.15:41628, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl019.domain.com] 2025.02.08 20:37:47.908110 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> executeQuery: (from 192.162.3.15:43296, user: cluster, initial_query_id: a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl006.domain.com] 2025.02.08 20:37:47.902244 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl006.domain.com] 2025.02.08 20:37:47.902611 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl006.domain.com] 2025.02.08 20:37:47.903984 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 114/114 parts by partition key, 114 parts by primary key, 1146183/1146183 marks by primary key, 1146183 marks to read from 114 ranges
[srvl006.domain.com] 2025.02.08 20:37:47.905884 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8952356746 rows with 40 streams
[srvl004.domain.com] 2025.02.08 20:37:47.903215 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl004.domain.com] 2025.02.08 20:37:47.903660 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl004.domain.com] 2025.02.08 20:37:47.922696 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 108/108 parts by partition key, 108 parts by primary key, 1125304/1125304 marks by primary key, 1125304 marks to read from 108 ranges
[srvl004.domain.com] 2025.02.08 20:37:47.924276 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8784816696 rows with 40 streams
[srvl005.domain.com] 2025.02.08 20:37:47.908254 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl005.domain.com] 2025.02.08 20:37:47.908660 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl005.domain.com] 2025.02.08 20:37:47.922964 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 108/108 parts by partition key, 108 parts by primary key, 1145835/1145835 marks by primary key, 1145835 marks to read from 108 ranges
[srvl005.domain.com] 2025.02.08 20:37:47.924675 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8952528996 rows with 40 streams
[srvl019.domain.com] 2025.02.08 20:37:47.909058 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl019.domain.com] 2025.02.08 20:37:47.909445 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl019.domain.com] 2025.02.08 20:37:47.924204 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 204/204 parts by partition key, 204 parts by primary key, 1345937/1345937 marks by primary key, 1345937 marks to read from 204 ranges
[srvl019.domain.com] 2025.02.08 20:37:47.926770 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 10609449427 rows with 40 streams
[srvl012.domain.com] 2025.02.08 20:37:47.904657 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl012.domain.com] 2025.02.08 20:37:47.905043 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl012.domain.com] 2025.02.08 20:37:47.927375 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 199/199 parts by partition key, 199 parts by primary key, 1345764/1345764 marks by primary key, 1345764 marks to read from 199 ranges
[srvl012.domain.com] 2025.02.08 20:37:47.929982 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 10610034999 rows with 40 streams
[srvl007.domain.com] 2025.02.08 20:37:47.908177 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl007.domain.com] 2025.02.08 20:37:47.908584 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl007.domain.com] 2025.02.08 20:37:47.931223 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 175/175 parts by partition key, 175 parts by primary key, 1266782/1266782 marks by primary key, 1266782 marks to read from 175 ranges
[srvl007.domain.com] 2025.02.08 20:37:47.933677 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 9963764352 rows with 40 streams
[srvl018.domain.com] 2025.02.08 20:37:47.911454 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl018.domain.com] 2025.02.08 20:37:47.911734 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl018.domain.com] 2025.02.08 20:37:47.934910 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 200/200 parts by partition key, 200 parts by primary key, 1345809/1345809 marks by primary key, 1345809 marks to read from 200 ranges
[srvl018.domain.com] 2025.02.08 20:37:47.936806 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 10609298929 rows with 40 streams
[srvl012.domain.com] 2025.02.08 20:38:23.780011 [ 15161 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> MemoryTracker: Current memory usage (total): 4.00 GiB.
[srvl012.domain.com] 2025.02.08 20:38:27.504700 [ 15166 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> MemoryTracker: Current memory usage (total): 5.00 GiB.
[srvl006.domain.com] 2025.02.08 20:38:41.139516 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> executeQuery: Read 8952356746 rows, 1.12 TiB in 53.238273 sec., 168156407.81585833 rows/sec., 21.46 GiB/sec.
[srvl006.domain.com] 2025.02.08 20:38:41.140535 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> MemoryTracker: Peak memory usage (for query): 764.16 MiB.
[srvl006.domain.com] 2025.02.08 20:38:41.140577 [ 944535 ] {fe25b336-8775-405d-ab2d-9a45e65bce27} <Debug> TCPHandler: Processed in 53.239173916 sec.
[srvl004.domain.com] 2025.02.08 20:38:43.138010 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> executeQuery: Read 8784816696 rows, 1.09 TiB in 55.23575 sec., 159042227.1083492 rows/sec., 20.23 GiB/sec.
[srvl004.domain.com] 2025.02.08 20:38:43.139096 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> MemoryTracker: Peak memory usage (for query): 775.66 MiB.
[srvl004.domain.com] 2025.02.08 20:38:43.139135 [ 3358420 ] {30782c79-4970-4242-9587-406ebc9b8775} <Debug> TCPHandler: Processed in 55.236495694 sec.
[srvl012.domain.com] 2025.02.08 20:38:48.901686 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> executeQuery: Read 10610034999 rows, 1.28 TiB in 60.998312 sec., 173939813.26893112 rows/sec., 21.42 GiB/sec.
[srvl012.domain.com] 2025.02.08 20:38:48.903468 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> MemoryTracker: Peak memory usage (for query): 875.31 MiB.
[srvl012.domain.com] 2025.02.08 20:38:48.903512 [ 15859 ] {1a9afec3-cea6-407a-9b0a-6d9e2cc0bf06} <Debug> TCPHandler: Processed in 61.000231483 sec.
[srvl018.domain.com] 2025.02.08 20:38:50.915858 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> executeQuery: Read 10609298929 rows, 1.28 TiB in 63.005428 sec., 168387062.28612557 rows/sec., 20.73 GiB/sec.
[srvl018.domain.com] 2025.02.08 20:38:50.917244 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> MemoryTracker: Peak memory usage (for query): 865.31 MiB.
[srvl018.domain.com] 2025.02.08 20:38:50.917297 [ 3996896 ] {935c070c-4b49-423d-9363-4259196803da} <Debug> TCPHandler: Processed in 63.006399868 sec.
[srvl007.domain.com] 2025.02.08 20:38:51.203639 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> executeQuery: Read 9963764352 rows, 1.21 TiB in 63.296583 sec., 157413937.36846742 rows/sec., 19.55 GiB/sec.
[srvl007.domain.com] 2025.02.08 20:38:51.204840 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> MemoryTracker: Peak memory usage (for query): 828.16 MiB.
[srvl007.domain.com] 2025.02.08 20:38:51.204882 [ 4102571 ] {fe5f6cb6-c46f-4847-a202-cc52806e578b} <Debug> TCPHandler: Processed in 63.297486189 sec.
[srvl019.domain.com] 2025.02.08 20:38:54.900440 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> executeQuery: Read 10609449427 rows, 1.28 TiB in 66.9923 sec., 158368191.9713161 rows/sec., 19.50 GiB/sec.
[srvl019.domain.com] 2025.02.08 20:38:54.901593 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> MemoryTracker: Peak memory usage (for query): 871.46 MiB.
[srvl019.domain.com] 2025.02.08 20:38:54.901633 [ 447911 ] {0333cef1-d42f-448b-a8eb-cba919bacd15} <Debug> TCPHandler: Processed in 66.993078103 sec.
[srvl005.domain.com] 2025.02.08 20:38:57.540484 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> executeQuery: Read 8952528996 rows, 1.12 TiB in 69.633107 sec., 128567133.9640209 rows/sec., 16.41 GiB/sec.
[srvl005.domain.com] 2025.02.08 20:38:57.541675 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> MemoryTracker: Peak memory usage (for query): 773.91 MiB.
[srvl005.domain.com] 2025.02.08 20:38:57.541731 [ 4121314 ] {1163e3f5-915c-4dd5-b7c0-8c3d1dfbe84d} <Debug> TCPHandler: Processed in 69.633703795 sec.
[srvl002.domain.com] 2025.02.08 20:38:57.542611 [ 2037437 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> Aggregator: Merged partially aggregated blocks for bucket #-1. Got 1 rows, 8.00 B from 8 source rows in 3.3163e-05 sec. (30154.087 rows/sec., 235.58 KiB/sec.)
[srvl002.domain.com] 2025.02.08 20:38:57.543960 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> executeQuery: Read 77267252245 rows, 9.45 TiB in 69.67371 sec., 1108987195.3854618 rows/sec., 138.88 GiB/sec.
[srvl002.domain.com] 2025.02.08 20:38:57.546294 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> MemoryTracker: Peak memory usage (for query): 738.47 MiB.
[srvl002.domain.com] 2025.02.08 20:38:57.546368 [ 2038306 ] {a1c0fd11-91a3-4df4-b52a-0e1f9d2027d0} <Debug> TCPHandler: Processed in 69.675396444 sec.
   ┌───count()─┐
1. │ 290312992 │ -- 290.31 million
   └───────────┘
 
1 row in set. Elapsed: 69.673 sec. Processed 77.27 billion rows, 10.39 TB (1.11 billion rows/s., 149.12 GB/s.)
Peak memory usage: 875.31 MiB.
```
EXPLAIN PIPELINE (for the fast execution):
```
EXPLAIN PIPELINE
SELECT COUNT()
FROM dbname.dist_Table
WHERE Column1 LIKE '%SampleText%'
 
Query id: 437c7853-9b1e-4ccc-9563-dd8f7fcfc436
 
[srvl002.domain.com] 2025.02.08 20:40:17.328382 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> executeQuery: (from 192.168.1.29:52839, user: sa) explain pipeline SELECT COUNT() FROM dbname.dist_Table WHERE Column1 LIKE '%SampleText%' (stage: Complete)
[srvl002.domain.com] 2025.02.08 20:40:17.329850 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl002.domain.com] 2025.02.08 20:40:17.329967 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl002.domain.com] 2025.02.08 20:40:17.331431 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 110/110 parts by partition key, 110 parts by primary key, 1125008/1125008 marks by primary key, 1125008 marks to read from 110 ranges
[srvl002.domain.com] 2025.02.08 20:40:17.332956 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8785006865 rows with 40 streams
[srvl002.domain.com] 2025.02.08 20:40:17.335129 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> executeQuery: Read 20 rows, 874.00 B in 0.006821 sec., 2932.1213898255387 rows/sec., 125.13 KiB/sec.
[srvl002.domain.com] 2025.02.08 20:40:17.335232 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> MemoryTracker: Peak memory usage (for query): 473.61 KiB.
[srvl002.domain.com] 2025.02.08 20:40:17.335250 [ 2038306 ] {437c7853-9b1e-4ccc-9563-dd8f7fcfc436} <Debug> TCPHandler: Processed in 0.007261819 sec.
    ┌─explain───────────────────────────────────────────────────────────────────────────────┐
 1. │ (Expression)                                                                          │
 2. │ ExpressionTransform × 40                                                              │
 3. │   (MergingAggregated)                                                                 │
 4. │   Resize 1 → 40                                                                       │
 5. │     SortingAggregatedTransform 40 → 1                                                 │
 6. │       MergingAggregatedBucketTransform × 40                                           │
 7. │         Resize 1 → 40                                                                 │
 8. │           GroupingAggregatedTransform 8 → 1                                           │
 9. │             (Union)                                                                   │
1. │               (Aggregating)                                                           │
2. │               Resize 40 → 1                                                           │
3. │                 AggregatingTransform × 40                                             │
4. │                   StrictResize 40 → 40                                                │
5. │                     (Expression)                                                      │
6. │                     ExpressionTransform × 40                                          │
7. │                       (Filter)                                                        │
8. │                       FilterTransform × 40                                            │
9. │                         (ReadFromMergeTree)                                           │
10. │                         MergeTreeSelect(pool: ReadPool, algorithm: Thread) × 40 0 → 1 │
11. │               (ReadFromRemote)                                                        │
    └───────────────────────────────────────────────────────────────────────────────────────┘
 
20 rows in set. Elapsed: 0.007 sec.
```
 
Here are the logs from 24.11 (slow):
```
Query id: 8410dda4-61c1-48dc-90be-1797a5df9c5d
 
[srvl002.domain.com] 2025.02.08 20:11:55.990513 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> executeQuery: (from 192.168.1.29:51558, user: sa) SELECT COUNT() FROM dbname.dist_Table WHERE Column1 LIKE '%SampleText%' (stage: Complete)
[srvl002.domain.com] 2025.02.08 20:11:55.992133 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl002.domain.com] 2025.02.08 20:11:55.992435 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl002.domain.com] 2025.02.08 20:11:55.997166 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 108/108 parts by partition key, 108 parts by primary key, 1124907/1124907 marks by primary key, 1124907 marks to read from 108 ranges
[srvl002.domain.com] 2025.02.08 20:11:55.998847 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8784241151 rows with 40 streams
[srvl002.domain.com] 2025.02.08 20:11:56.004485 [ 2032926 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL019.domain.com:9000): Sent data for 2 scalars, total 2 rows in 6.496e-05 sec., 30573 rows/sec., 68.00 B (1014.53 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.15 MiB/sec.)
[srvl019.domain.com] 2025.02.08 20:11:56.005009 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> executeQuery: (from 192.168.3.15:43586, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl002.domain.com] 2025.02.08 20:11:56.007985 [ 2032972 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL007.domain.com:9000): Sent data for 2 scalars, total 2 rows in 8.7035e-05 sec., 22771 rows/sec., 68.00 B (754.87 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (1.60 MiB/sec.)
[srvl002.domain.com] 2025.02.08 20:11:56.008015 [ 2029890 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL004.domain.com:9000): Sent data for 2 scalars, total 2 rows in 5.4948e-05 sec., 35884 rows/sec., 68.00 B (1.16 MiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.53 MiB/sec.)
[srvl002.domain.com] 2025.02.08 20:11:56.010562 [ 2032888 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL006.domain.com:9000): Sent data for 2 scalars, total 2 rows in 5.9077e-05 sec., 33396 rows/sec., 68.00 B (1.08 MiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.35 MiB/sec.)
[srvl004.domain.com] 2025.02.08 20:11:56.008351 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> executeQuery: (from 192.168.3.15:37632, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl002.domain.com] 2025.02.08 20:11:56.011279 [ 2030137 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL005.domain.com:9000): Sent data for 2 scalars, total 2 rows in 6.3629e-05 sec., 31029 rows/sec., 68.00 B (1.01 MiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.19 MiB/sec.)
[srvl006.domain.com] 2025.02.08 20:11:56.011005 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> executeQuery: (from 192.168.3.15:42460, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl002.domain.com] 2025.02.08 20:11:56.012761 [ 2030142 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL012.domain.com:9000): Sent data for 2 scalars, total 2 rows in 8.0753e-05 sec., 24523 rows/sec., 68.00 B (813.88 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (1.73 MiB/sec.)
[srvl005.domain.com] 2025.02.08 20:11:56.011810 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> executeQuery: (from 192.168.3.15:46508, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl002.domain.com] 2025.02.08 20:11:56.014426 [ 2030118 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Connection (srvL018.domain.com:9000): Sent data for 2 scalars, total 2 rows in 6.7623e-05 sec., 29241 rows/sec., 68.00 B (970.37 KiB/sec.), compressed 0.4594594594594595 times to 148.00 B (2.06 MiB/sec.)
[srvl012.domain.com] 2025.02.08 20:11:56.013297 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> executeQuery: (from 192.168.3.15:49886, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl007.domain.com] 2025.02.08 20:11:56.008272 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> executeQuery: (from 192.168.3.15:55986, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl018.domain.com] 2025.02.08 20:11:56.014666 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> executeQuery: (from 192.168.3.15:51210, user: cluster, initial_query_id: 8410dda4-61c1-48dc-90be-1797a5df9c5d) SELECT count() FROM `dbname`.`local_Table` WHERE `Column1` LIKE '%SampleText%' (stage: WithMergeableState)
[srvl004.domain.com] 2025.02.08 20:11:56.009291 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl004.domain.com] 2025.02.08 20:11:56.009589 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl004.domain.com] 2025.02.08 20:11:56.014366 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 109/109 parts by partition key, 109 parts by primary key, 1125202/1125202 marks by primary key, 1125202 marks to read from 109 ranges
[srvl004.domain.com] 2025.02.08 20:11:56.016481 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8784055387 rows with 40 streams
[srvl005.domain.com] 2025.02.08 20:11:56.012834 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl005.domain.com] 2025.02.08 20:11:56.013146 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl005.domain.com] 2025.02.08 20:11:56.018120 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 104/104 parts by partition key, 104 parts by primary key, 1145733/1145733 marks by primary key, 1145733 marks to read from 104 ranges
[srvl005.domain.com] 2025.02.08 20:11:56.019582 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8951766574 rows with 40 streams
[srvl019.domain.com] 2025.02.08 20:11:56.006111 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl019.domain.com] 2025.02.08 20:11:56.008136 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl019.domain.com] 2025.02.08 20:11:56.014884 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 204/204 parts by partition key, 204 parts by primary key, 1345840/1345840 marks by primary key, 1345840 marks to read from 204 ranges
[srvl019.domain.com] 2025.02.08 20:11:56.019763 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 10608686662 rows with 40 streams
[srvl006.domain.com] 2025.02.08 20:11:56.011988 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl006.domain.com] 2025.02.08 20:11:56.012328 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl006.domain.com] 2025.02.08 20:11:56.016690 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 113/113 parts by partition key, 113 parts by primary key, 1146083/1146083 marks by primary key, 1146083 marks to read from 113 ranges
[srvl006.domain.com] 2025.02.08 20:11:56.017956 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 8951594354 rows with 40 streams
[srvl007.domain.com] 2025.02.08 20:11:56.009314 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl007.domain.com] 2025.02.08 20:11:56.009772 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl007.domain.com] 2025.02.08 20:11:56.016037 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 178/178 parts by partition key, 178 parts by primary key, 1266682/1266682 marks by primary key, 1266682 marks to read from 178 ranges
[srvl007.domain.com] 2025.02.08 20:11:56.018372 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 9963002580 rows with 40 streams
[srvl018.domain.com] 2025.02.08 20:11:56.015592 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl018.domain.com] 2025.02.08 20:11:56.016150 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl018.domain.com] 2025.02.08 20:11:56.022915 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 201/201 parts by partition key, 201 parts by primary key, 1345708/1345708 marks by primary key, 1345708 marks to read from 201 ranges
[srvl018.domain.com] 2025.02.08 20:11:56.026474 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 10608537485 rows with 40 streams
[srvl012.domain.com] 2025.02.08 20:11:56.014583 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Key condition: unknown
[srvl012.domain.com] 2025.02.08 20:11:56.015114 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): MinMax index condition: unknown
[srvl012.domain.com] 2025.02.08 20:11:56.024057 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Selected 202/202 parts by partition key, 202 parts by primary key, 1345667/1345667 marks by primary key, 1345667 marks to read from 202 ranges
[srvl012.domain.com] 2025.02.08 20:11:56.027823 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> dbname.local_Table (3d89e983-d0c9-42a8-854c-ef681d2c704b) (SelectExecutor): Reading approx. 10609273078 rows with 40 streams
[srvl018.domain.com] 2025.02.08 20:13:23.100108 [ 3993737 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl019.domain.com] 2025.02.08 20:13:23.395667 [ 444611 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl002.domain.com] 2025.02.08 20:13:24.277521 [ 2032939 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl004.domain.com] 2025.02.08 20:13:26.407045 [ 3352430 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl018.domain.com] 2025.02.08 20:13:27.084046 [ 3993748 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> MemoryTracker: (total) current memory usage: 4.00 GiB.
[srvl006.domain.com] 2025.02.08 20:13:27.301972 [ 941554 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl012.domain.com] 2025.02.08 20:13:28.049002 [ 12645 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl005.domain.com] 2025.02.08 20:13:31.511021 [ 4114766 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl007.domain.com] 2025.02.08 20:13:39.371402 [ 4098295 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> MemoryTracker: Query current memory usage: 1.00 GiB.
[srvl004.domain.com] 2025.02.08 20:14:08.989677 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> executeQuery: Read 8784055387 rows, 1.09 TiB in 132.981258 sec., 66054837.494468585 rows/sec., 8.40 GiB/sec.
[srvl004.domain.com] 2025.02.08 20:14:08.990927 [ 3354650 ] {e635bd87-87af-449c-8e18-777bb0e4cbd7} <Debug> MemoryTracker: Query peak memory usage: 1.35 GiB.
[srvl006.domain.com] 2025.02.08 20:14:09.008357 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> executeQuery: Read 8951594354 rows, 1.12 TiB in 132.997333 sec., 67306570.3806256 rows/sec., 8.59 GiB/sec.
[srvl006.domain.com] 2025.02.08 20:14:09.009304 [ 939306 ] {0f2f4d74-a01c-4515-b4d8-5f2ad11fa82b} <Debug> MemoryTracker: Query peak memory usage: 1.39 GiB.
[srvl005.domain.com] 2025.02.08 20:14:13.854442 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> executeQuery: Read 8951766574 rows, 1.12 TiB in 137.842586 sec., 64941951.78549537 rows/sec., 8.29 GiB/sec.
[srvl005.domain.com] 2025.02.08 20:14:13.856247 [ 4116302 ] {fc35cec7-6785-467a-a806-9201dfea61e9} <Debug> MemoryTracker: Query peak memory usage: 1.38 GiB.
[srvl018.domain.com] 2025.02.08 20:14:23.435558 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> executeQuery: Read 10608537485 rows, 1.28 TiB in 147.420849 sec., 71960903.47437899 rows/sec., 8.86 GiB/sec.
[srvl018.domain.com] 2025.02.08 20:14:23.436859 [ 3992629 ] {1905fe52-b82c-432c-a66b-ebbd10d4d587} <Debug> MemoryTracker: Query peak memory usage: 1.56 GiB.
[srvl012.domain.com] 2025.02.08 20:14:28.773073 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> executeQuery: Read 10609273078 rows, 1.28 TiB in 152.7598 sec., 69450687.14413084 rows/sec., 8.55 GiB/sec.
[srvl012.domain.com] 2025.02.08 20:14:28.774483 [ 10451 ] {0c85f18a-f28d-4f3a-a777-97a641629689} <Debug> MemoryTracker: Query peak memory usage: 1.57 GiB.
[srvl019.domain.com] 2025.02.08 20:14:30.921351 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> executeQuery: Read 10608686662 rows, 1.28 TiB in 154.916294 sec., 68480121.67138468 rows/sec., 8.43 GiB/sec.
[srvl019.domain.com] 2025.02.08 20:14:30.922520 [ 442355 ] {1ec557b9-8130-463e-9b73-075873f1cfd2} <Debug> MemoryTracker: Query peak memory usage: 1.56 GiB.
[srvl007.domain.com] 2025.02.08 20:14:35.041690 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> executeQuery: Read 9963002580 rows, 1.21 TiB in 159.033381 sec., 62647241.210321754 rows/sec., 7.78 GiB/sec.
[srvl007.domain.com] 2025.02.08 20:14:35.043200 [ 4096026 ] {c9abf8ca-00ef-4a81-95d9-f4cd102ff7f8} <Debug> MemoryTracker: Query peak memory usage: 1.49 GiB.
[srvl002.domain.com] 2025.02.08 20:14:35.043695 [ 2032972 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> Aggregator: Merged partially aggregated blocks for bucket #-1. Got 1 rows, 8.00 B from 8 source rows in 3.1243e-05 sec. (32007.170 rows/sec., 250.06 KiB/sec.)
[srvl002.domain.com] 2025.02.08 20:14:35.045110 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> executeQuery: Read 77261157271 rows, 9.45 TiB in 159.054602 sec., 485752416.46261835 rows/sec., 60.83 GiB/sec.
[srvl002.domain.com] 2025.02.08 20:14:35.047191 [ 2031230 ] {8410dda4-61c1-48dc-90be-1797a5df9c5d} <Debug> MemoryTracker: Query peak memory usage: 1.33 GiB.
   ┌───count()─┐
1. │ 290312283 │ -- 290.31 million
   └───────────┘
 
1 row in set. Elapsed: 159.052 sec. Processed 77.26 billion rows, 10.39 TB (485.76 million rows/s., 65.32 GB/s.)
Peak memory usage: 1.57 GiB.
```
EXPLAIN PIPELINE (slow)
```
    ┌─explain───────────────────────────────────────────────────────────────────────────────┐
 1. │ (Expression)                                                                          │
 2. │ ExpressionTransform × 40                                                              │
 3. │   (MergingAggregated)                                                                 │
 4. │   Resize 1 → 40                                                                       │
 5. │     SortingAggregatedTransform 40 → 1                                                 │
 6. │       MergingAggregatedBucketTransform × 40                                           │
 7. │         Resize 1 → 40                                                                 │
 8. │           GroupingAggregatedTransform 8 → 1                                           │
 9. │             (Union)                                                                   │
1. │               (Aggregating)                                                           │
2. │               Resize 40 → 1                                                           │
3. │                 AggregatingTransform × 40                                             │
4. │                   StrictResize 40 → 40                                                │
5. │                     (Expression)                                                      │
6. │                     ExpressionTransform × 40                                          │
7. │                       (Filter)                                                        │
8. │                       FilterTransform × 40                                            │
9. │                         (ReadFromMergeTree)                                           │
10. │                         MergeTreeSelect(pool: ReadPool, algorithm: Thread) × 40 0 → 1 │
11. │               (ReadFromRemote)                                                        │
    └───────────────────────────────────────────────────────────────────────────────────────┘
 
```
EXPLAIN ACTIONS (slow)
```
    ┌─explain──────────────────────────────────────────────────────────────────────────────────────────────────┐
 1. │ Expression ((Projection + Before ORDER BY))                                                              │
 2. │ Actions: INPUT :: 0 -> count() UInt64 : 0                                                                │
 3. │ Positions: 0                                                                                             │
 4. │   MergingAggregated                                                                                      │
 5. │   Keys:                                                                                                  │
 6. │   Aggregates:                                                                                            │
 7. │       count()                                                                                            │
 8. │         Function: count() → UInt64                                                                       │
 9. │         Arguments: none                                                                                  │
12. │     Union                                                                                                │
13. │       Aggregating                                                                                        │
14. │       Keys:                                                                                              │
15. │       Aggregates:                                                                                        │
16. │           count()                                                                                        │
17. │             Function: count() → UInt64                                                                   │
18. │             Arguments: none                                                                              │
19. │       Skip merging: 0                                                                                    │
20. │         Expression (Before GROUP BY)                                                                     │
21. │         Positions:                                                                                       │
22. │           Filter (WHERE)                                                                                 │
23. │           Filter column: like(Column1, '%SampleText%') (removed)                                            │
24. │           Actions: INPUT : 0 -> Column1 String : 0                                                      │
25. │                    COLUMN Const(String) -> '%SampleText%' String : 1                                         │
26. │                    FUNCTION like(Column1 :: 0, '%SampleText%' :: 1) -> like(Column1, '%SampleText%') UInt8 : 2 │
27. │           Positions: 2                                                                                   │
28. │             ReadFromMergeTree (dbname.local_Table)                                            │
29. │             ReadType: Default                                                                            │
30. │             Parts: 106                                                                                   │
31. │             Granules: 1124915                                                                            │
32. │       ReadFromRemote (Read from remote replica)                                                          │
    └──────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
 
Thanks for your help.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

-

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes: #76112

### CODE REVIEW

File: src/Core/SettingsChangesHistory.cpp [hunk 1]
```diff
@@ -250,7 +251,7 @@ const VersionToSettingsChangesMap & getSettingsChangesHistory()
         addSettingsChanges(settings_changes_history, "24.11",
         {
             {"validate_mutation_query", false, true, "New setting to validate mutation queries by default."},
-            {"enable_job_stack_trace", false, true, "Enable by default collecting stack traces from job's scheduling."},
+            {"enable_job_stack_trace", false, false, "Enables collecting stack traces from job's scheduling. Disabled by default to avoid performance overhead."},
```
Comment (yakov-olkhovskiy) [inline src/Core/SettingsChangesHistory.cpp:254]: why we do this?

Comment (nickitat) [reply src/Core/SettingsChangesHistory.cpp:254]: Actually I just followed this example: https://github.com/ClickHouse/ClickHouse/pull/70833/files

**Review by yakov-olkhovskiy — APPROVED** [review]
