### PR TITLE
Try to avoid calculation of scalar subqueries for CREATE TABLE.

### LINKED ISSUE #59795: Slow materialized view creation if it contains a heavy query introduced in version 24.1
**Describe the unexpected behaviour**
Version 24.1 introduced a regression which manifests itself as taking a long time to create materialized view with a heavy query probably because of analyzing this query. Possibly related to https://github.com/ClickHouse/ClickHouse/pull/57855

image
image

**How to reproduce**
```
create table source(type String) engine=MergeTree order by type;

create view v_heavy as
with nums as (select number from numbers(1e5))
select count(*) n from (select number from numbers(1e5) n1 cross join nums);

create table target1(type String) engine=MergeTree order by type;
create table target2(type String) engine=MergeTree order by type;

create materialized view vm_target1 to target1 as select * from source where type='one';
-- this statement takes a long time in 24.1
create materialized view vm_target2 to target2 as select * from source where type='two' and (select n from v_heavy)>0;
```

**Expected behavior**
Creation of a materialized view should not take the same time as the query it contains.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid calculation of scalar subqueries for `CREATE TABLE`. Fixes https://github.com/ClickHouse/ClickHouse/issues/59795 and https://github.com/ClickHouse/ClickHouse/issues/59930. Attempt to re-implement https://github.com/ClickHouse/ClickHouse/pull/57855

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit dd458932c94103bafedb2e6a389171a3d5e54ddd with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60464/dd458932c94103bafedb2e6a389171a3d5e54ddd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60464/dd458932c94103bafedb2e6a389171a3d5e54ddd/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by antaljanosbenjamin — APPROVED** [review]
I do not have extensive knowledge about how we deal with contant expressions, but all the changes seems reasonable and the new tests are aimed to test the functionality that the fix supposed to fix, so seems okay.

File: tests/queries/0_stateless/02116_tuple_element.sql [hunk 1]
```diff
@@ -19,7 +19,7 @@ SELECT tupleElement(t1) FROM t_tuple_element; -- { serverError NUMBER_OF_ARGUMEN
 SELECT tupleElement(t1, 'b') FROM t_tuple_element; -- { serverError NOT_FOUND_COLUMN_IN_BLOCK, UNKNOWN_IDENTIFIER }
 SELECT tupleElement(t1, 0) FROM t_tuple_element; -- { serverError ILLEGAL_INDEX, NOT_FOUND_COLUMN_IN_BLOCK }
 SELECT tupleElement(t1, 3) FROM t_tuple_element; -- { serverError ILLEGAL_INDEX, NOT_FOUND_COLUMN_IN_BLOCK }
-SELECT tupleElement(t1, materialize('a')) FROM t_tuple_element; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
+SELECT tupleElement(t1, materialize('a')) FROM t_tuple_element; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT, 10 }
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/02116_tuple_element.sql:22]:
```suggestion
SELECT tupleElement(t1, materialize('a')) FROM t_tuple_element; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT, NOT_FOUND_COLUMN_IN_BLOCK }
```
I would prefer writing out error names instead of pure numbers only, it gives better readability.

File: tests/queries/0_stateless/02116_tuple_element.sql [hunk 2]
```diff
@@ -31,7 +31,7 @@ SELECT tupleElement(t2) FROM t_tuple_element; -- { serverError NUMBER_OF_ARGUMEN
 SELECT tupleElement(t2, 'a') FROM t_tuple_element; -- { serverError NOT_FOUND_COLUMN_IN_BLOCK, UNKNOWN_IDENTIFIER }
 SELECT tupleElement(t2, 0) FROM t_tuple_element; -- { serverError ILLEGAL_INDEX, NOT_FOUND_COLUMN_IN_BLOCK }
 SELECT tupleElement(t2, 3) FROM t_tuple_element; -- { serverError ILLEGAL_INDEX, NOT_FOUND_COLUMN_IN_BLOCK }
-SELECT tupleElement(t2, materialize(1)) FROM t_tuple_element; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
+SELECT tupleElement(t2, materialize(1)) FROM t_tuple_element; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT, 10 }
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/02116_tuple_element.sql:34]:
```suggestion
SELECT tupleElement(t2, materialize(1)) FROM t_tuple_element; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT, NOT_FOUND_COLUMN_IN_BLOCK }
```

Same here.
