### PR TITLE
Try batching requests in Keeper more aggressively

### LINKED ISSUE #35712: Session expired (Session expired). (KEEPER_EXCEPTION) - (ClickHouse Keeper)
**Describe what's wrong**
I am trying to migrate Apache  Zookeeper into ClickHouse Keeper but am running into Session expired KEEPER_EXCEPTION while doing a bunch of table creations that which I did not run into when running Apache Zookeeper.

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

Yes, this is happening on v.22.3.2.2

**Enable crash reporting**
Cannot do this unfortunately due to running within a restricted network.

**How to reproduce**

* Which ClickHouse server version to use:
  * `v.22.3.2.2`
* Which interface to use, if matters:
  * Exception happened during deployment of migrations with https://github.com/golang-migrate/migrate which uses the native TCP interface
* Non-default settings, if any
  * No non-default settings in ClickHouse Keeper same settings in ClickHouse as with working Apache Zookeeper
* `CREATE TABLE` statements for all tables involved
   * Migrations include creation of more than 50 tables and it fails on different tables each time. The table creation works without issue with Apache Zookeeper 
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
  * Did not manage to ingest data before this error appeared.
* Queries to run that lead to unexpected result
  * Running a bunch of `CREATE TABLE ON CLUSTER` statements with ReplicatedMergeTree engine in quick succession caused the error but it fails at different points each time.

**Expected behavior**

Same behavior as Apache Zookeeper, i.e. be able to run the 50+ CREATE TABLE statements with schema migration tool without exception. 

**Error message and/or stacktrace**

**ClickHouse Server Stacktrace Expand below**

<details>
<summary>ClickHouse Server - Click to expand!</summary>
<p>

```
2022.03.29 09:33:32.443156 [ 11097 ] {} <Error> ZooKeeperClient: Code: 210. DB::NetException: Connection reset by peer, while reading from socket (172.27.100.113:2181). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x13d53721 in /usr/bin/clickhouse
2. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0xa53a279 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::receiveEvent() @ 0x158d2e4a in /usr/bin/clickhouse
4. Coordination::ZooKeeper::receiveThread() @ 0x158d266c in /usr/bin/clickhouse
5. ? @ 0x158d8290 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
7. ? @ 0xa58881d in /usr/bin/clickhouse
8. ? @ 0x7f39f01dd609 in ?
9. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.443738 [ 11068 ] {} <Error> ZooKeeperClient: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (172.27.100.113:2181). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x14187eca in /usr/bin/clickhouse
2. Coordination::ZooKeeperRequest::write(DB::WriteBuffer&) const @ 0x158b86cf in /usr/bin/clickhouse
3. Coordination::ZooKeeper::sendThread() @ 0x158d192d in /usr/bin/clickhouse
4. ? @ 0x158d7e90 in /usr/bin/clickhouse
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
6. ? @ 0xa58881d in /usr/bin/clickhouse
7. ? @ 0x7f39f01dd609 in ?
8. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.444243 [ 11097 ] {} <Error> ZooKeeperClient: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::NetException::NetException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1649742c in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x164aaf24 in /usr/bin/clickhouse
2. Poco::Net::SocketImpl::shutdown() @ 0x164ac6bc in /usr/bin/clickhouse
3. Coordination::ZooKeeper::finalize(bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x158cd51e in /usr/bin/clickhouse
4. Coordination::ZooKeeper::receiveThread() @ 0x158d2d8a in /usr/bin/clickhouse
5. ? @ 0x158d8290 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
7. ? @ 0xa58881d in /usr/bin/clickhouse
8. ? @ 0x7f39f01dd609 in ?
9. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.444761 [ 10954 ] {} <Error> system.schema_migrations (8f170f09-7d14-4460-be02-940223c18c81): void DB::StorageReplicatedMergeTree::mutationsUpdatingTask(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::list(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::ListResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x158d652e in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryGetChildrenNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15890b7c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::getChildrenImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15890520 in /usr/bin/clickhouse
7. zkutil::ZooKeeper::tryGetChildrenWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15891217 in /usr/bin/clickhouse
8. zkutil::ZooKeeper::getChildrenWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15891125 in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeQueue::updateMutations(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1506d2be in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::mutationsUpdatingTask() @ 0x14bd614d in /usr/bin/clickhouse
11. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13b2dbae in /usr/bin/clickhouse
12. DB::BackgroundSchedulePool::threadFunction() @ 0x13b30527 in /usr/bin/clickhouse
13. ? @ 0x13b31530 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
15. ? @ 0xa58881d in /usr/bin/clickhouse
16. ? @ 0x7f39f01dd609 in ?
17. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.445050 [ 10932 ] {} <Error> idd_shard.ingest (0a6808d7-9470-4c23-a2ed-9dbb5f4eebee): void DB::StorageReplicatedMergeTree::mutationsUpdatingTask(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::list(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::ListResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x158d652e in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryGetChildrenNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15890b7c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::getChildrenImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15890520 in /usr/bin/clickhouse
7. zkutil::ZooKeeper::tryGetChildrenWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15891217 in /usr/bin/clickhouse
8. zkutil::ZooKeeper::getChildrenWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15891125 in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeQueue::updateMutations(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1506d2be in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::mutationsUpdatingTask() @ 0x14bd614d in /usr/bin/clickhouse
11. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13b2dbae in /usr/bin/clickhouse
12. DB::BackgroundSchedulePool::threadFunction() @ 0x13b30527 in /usr/bin/clickhouse
13. ? @ 0x13b31530 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
15. ? @ 0xa58881d in /usr/bin/clickhouse
16. ? @ 0x7f39f01dd609 in ?
17. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.444821 [ 10963 ] {} <Error> system.schema_migrations (8f170f09-7d14-4460-be02-940223c18c81): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::GetResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x158d5b0e in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryGetNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15893c7c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::getImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15893620 in /usr/bin/clickhouse
7. zkutil::ZooKeeper::tryGetWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::Error*) @ 0x1589449c in /usr/bin/clickhouse
8. zkutil::ZooKeeper::tryGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&, Coordination::Error*) @ 0x158941a7 in /usr/bin/clickhouse
9. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x15893f5a in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x15066a65 in /usr/bin/clickhouse
11. DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x14bd5d7f in /usr/bin/clickhouse
12. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13b2dbae in /usr/bin/clickhouse
13. DB::BackgroundSchedulePool::threadFunction() @ 0x13b30527 in /usr/bin/clickhouse
14. ? @ 0x13b31530 in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
16. ? @ 0xa58881d in /usr/bin/clickhouse
17. ? @ 0x7f39f01dd609 in ?
18. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.445409 [ 11001 ] {} <Warning> system.schema_migrations (ReplicatedMergeTreeRestartingThread): ZooKeeper session has expired. Switching to a new session.
2022.03.29 09:33:32.445739 [ 11001 ] {} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Cannot remove /clickhouse/tables/8f170f09-7d14-4460-be02-940223c18c81/01/replicas/dev-ch01/is_active: : Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::function<void (Coordination::RemoveResponse const&)>) @ 0x158d51a0 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryRemoveNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15892704 in /usr/bin/clickhouse
6. zkutil::ZooKeeper::removeImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15892225 in /usr/bin/clickhouse
7. zkutil::EphemeralNodeHolder::~EphemeralNodeHolder() @ 0xa664cc3 in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::partialShutdown(bool) @ 0x1509d95d in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x15096d48 in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x150951de in /usr/bin/clickhouse
11. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13b2dbae in /usr/bin/clickhouse
12. DB::BackgroundSchedulePool::threadFunction() @ 0x13b30527 in /usr/bin/clickhouse
13. ? @ 0x13b31530 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
15. ? @ 0xa58881d in /usr/bin/clickhouse
16. ? @ 0x7f39f01dd609 in ?
17. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.446322 [ 11059 ] {802a129d-39da-4f92-88c8-76e7673df3c3} <Error> executeQuery: Code: 999. Coordination::Exception: Connection loss. (KEEPER_EXCEPTION) (version 22.3.2.1) (from 0.0.0.0:0) (in query: /* ddl_entry=query-0000000262 */ CREATE TABLE IF NOT EXISTS idd_shard.acap_configs UUID 'a1cc46dc-f181-4498-878b-710b48f8d207' (`apv_autopilot_enabled` Nullable(Boolean), `apv_camera_name` Nullable(String) CODEC(ZSTD(9)), `apv_pan_kd` Nullable(Float64) CODEC(ZSTD(9)), `apv_pan_ki` Nullable(Float64) CODEC(ZSTD(9)), `apv_pan_kp` Nullable(Float64) CODEC(ZSTD(9)), `apv_return_to_home_enabled` Nullable(Boolean), `apv_return_to_home_timeout` Nullable(Int64) CODEC(ZSTD(9)), `apv_switch_object` Nullable(Boolean), `apv_tilt_kd` Nullable(Float64) CODEC(ZSTD(9)), `apv_tilt_ki` Nullable(Float64) CODEC(ZSTD(9)), `apv_tilt_kp` Nullable(Float64) CODEC(ZSTD(9)), `apv_time_per_object` Nullable(Int64) CODEC(ZSTD(9)), `dad_detection_enabled` Nullable(Boolean), `dad_detection_mode` Nullable(Int64) CODEC(ZSTD(9)), `dad_minimum_threshold` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_control_enabled` Nullable(Boolean), `dad_ptz_control_timeout` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_pan_calibration` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_tilt_position` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_zoom_position` Nullable(Int64) CODEC(ZSTD(9)), `dad_schedule_id` Nullable(String) CODEC(ZSTD(9)), `dad_threshold` Nullable(Int64) CODEC(ZSTD(9)), `idd_reason` Nullable(String) CODEC(ZSTD(9)), `vms_view_mode` Nullable(String) CODEC(ZSTD(9)), `idd_acap_version` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `agent_id` String DEFAULT 'unknown' CODEC(ZSTD(9)), `boot_id` String DEFAULT 'unknown' CODEC(ZSTD(9)), `custom_data` String DEFAULT '' CODEC(ZSTD(9)), `data` String DEFAULT '' CODEC(ZSTD(9)), `env` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `feature_diff` String DEFAULT '' CODEC(ZSTD(9)), `firmware_version` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `hardware_id` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `origin_path` String DEFAULT 'unknown' CODEC(ZSTD(9)), `partition` String DEFAULT 'unknown' CODEC(ZSTD(9)), `product_name` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `serial_number` String DEFAULT 'unknown' CODEC(ZSTD(9)), `site_id` String DEFAULT 'unknown' CODEC(ZSTD(9)), `timestamp` DateTime CODEC(DoubleDelta, ZSTD(9)), `uptime` Nullable(UInt64) CODEC(DoubleDelta, ZSTD(9))) ENGINE = ReplicatedMergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY (product_name, serial_number, boot_id, timestamp)), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error) @ 0x158894de in /usr/bin/clickhouse
3. zkutil::ZooKeeper::tryMulti(std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request> > > const&, std::__1::vector<std::__1::shared_ptr<Coordination::Response>, std::__1::allocator<std::__1::shared_ptr<Coordination::Response> > >&) @ 0x15895b02 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::createTableIfNotExists(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x14b75b71 in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool) @ 0x14b6f3e2 in /usr/bin/clickhouse
6. ? @ 0x150d1456 in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x14adb1da in /usr/bin/clickhouse
8. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x1442ea79 in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x144298cd in /usr/bin/clickhouse
10. DB::InterpreterCreateQuery::execute() @ 0x14431fcb in /usr/bin/clickhouse
11. ? @ 0x148d0c9a in /usr/bin/clickhouse
12. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x148d3fca in /usr/bin/clickhouse
13. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1412cbce in /usr/bin/clickhouse
14. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1412b572 in /usr/bin/clickhouse
15. DB::DDLWorker::scheduleTasks(bool) @ 0x141292e3 in /usr/bin/clickhouse
16. DB::DDLWorker::runMainThread() @ 0x14122ec5 in /usr/bin/clickhouse
17. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x141370b7 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
19. ? @ 0xa58881d in /usr/bin/clickhouse
20. ? @ 0x7f39f01dd609 in ?
21. clone @ 0x7f39f0104293 in ?

2022.03.29 09:33:32.446575 [ 11059 ] {802a129d-39da-4f92-88c8-76e7673df3c3} <Error> DDLWorker: Query CREATE TABLE IF NOT EXISTS idd_shard.acap_configs UUID 'a1cc46dc-f181-4498-878b-710b48f8d207' (`apv_autopilot_enabled` Nullable(Boolean), `apv_camera_name` Nullable(String) CODEC(ZSTD(9)), `apv_pan_kd` Nullable(Float64) CODEC(ZSTD(9)), `apv_pan_ki` Nullable(Float64) CODEC(ZSTD(9)), `apv_pan_kp` Nullable(Float64) CODEC(ZSTD(9)), `apv_return_to_home_enabled` Nullable(Boolean), `apv_return_to_home_timeout` Nullable(Int64) CODEC(ZSTD(9)), `apv_switch_object` Nullable(Boolean), `apv_tilt_kd` Nullable(Float64) CODEC(ZSTD(9)), `apv_tilt_ki` Nullable(Float64) CODEC(ZSTD(9)), `apv_tilt_kp` Nullable(Float64) CODEC(ZSTD(9)), `apv_time_per_object` Nullable(Int64) CODEC(ZSTD(9)), `dad_detection_enabled` Nullable(Boolean), `dad_detection_mode` Nullable(Int64) CODEC(ZSTD(9)), `dad_minimum_threshold` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_control_enabled` Nullable(Boolean), `dad_ptz_control_timeout` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_pan_calibration` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_tilt_position` Nullable(Int64) CODEC(ZSTD(9)), `dad_ptz_zoom_position` Nullable(Int64) CODEC(ZSTD(9)), `dad_schedule_id` Nullable(String) CODEC(ZSTD(9)), `dad_threshold` Nullable(Int64) CODEC(ZSTD(9)), `idd_reason` Nullable(String) CODEC(ZSTD(9)), `vms_view_mode` Nullable(String) CODEC(ZSTD(9)), `idd_acap_version` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `agent_id` String DEFAULT 'unknown' CODEC(ZSTD(9)), `boot_id` String DEFAULT 'unknown' CODEC(ZSTD(9)), `custom_data` String DEFAULT '' CODEC(ZSTD(9)), `data` String DEFAULT '' CODEC(ZSTD(9)), `env` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `feature_diff` String DEFAULT '' CODEC(ZSTD(9)), `firmware_version` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `hardware_id` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `origin_path` String DEFAULT 'unknown' CODEC(ZSTD(9)), `partition` String DEFAULT 'unknown' CODEC(ZSTD(9)), `product_name` LowCardinality(String) DEFAULT 'unknown' CODEC(ZSTD(9)), `serial_number` String DEFAULT 'unknown' CODEC(ZSTD(9)), `site_id` String DEFAULT 'unknown' CODEC(ZSTD(9)), `timestamp` DateTime CODEC(DoubleDelta, ZSTD(9)), `uptime` Nullable(UInt64) CODEC(DoubleDelta, ZSTD(9))) ENGINE = ReplicatedMergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY (product_name, serial_number, boot_id, timestamp) wasn't finished successfully: Code: 999. Coordination::Exception: Connection loss. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error) @ 0x158894de in /usr/bin/clickhouse
3. zkutil::ZooKeeper::tryMulti(std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request> > > const&, std::__1::vector<std::__1::shared_ptr<Coordination::Response>, std::__1::allocator<std::__1::shared_ptr<Coordination::Response> > >&) @ 0x15895b02 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::createTableIfNotExists(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x14b75b71 in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool) @ 0x14b6f3e2 in /usr/bin/clickhouse
6. ? @ 0x150d1456 in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x14adb1da in /usr/bin/clickhouse
8. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x1442ea79 in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x144298cd in /usr/bin/clickhouse
10. DB::InterpreterCreateQuery::execute() @ 0x14431fcb in /usr/bin/clickhouse
11. ? @ 0x148d0c9a in /usr/bin/clickhouse
12. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x148d3fca in /usr/bin/clickhouse
13. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1412cbce in /usr/bin/clickhouse
14. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1412b572 in /usr/bin/clickhouse
15. DB::DDLWorker::scheduleTasks(bool) @ 0x141292e3 in /usr/bin/clickhouse
16. DB::DDLWorker::runMainThread() @ 0x14122ec5 in /usr/bin/clickhouse
17. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x141370b7 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
19. ? @ 0xa58881d in /usr/bin/clickhouse
20. ? @ 0x7f39f01dd609 in ?
21. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.446931 [ 11059 ] {} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Cannot remove /clickhouse/task_queue/ddl/query-0000000262/active/dev%2Dch01%2Ese%2Eaxis%2Ecom:9000: : Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::function<void (Coordination::RemoveResponse const&)>) @ 0x158d51a0 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryRemoveNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15892704 in /usr/bin/clickhouse
6. zkutil::ZooKeeper::removeImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15892225 in /usr/bin/clickhouse
7. zkutil::EphemeralNodeHolder::~EphemeralNodeHolder() @ 0xa664cc3 in /usr/bin/clickhouse
8. std::__1::shared_ptr<zkutil::EphemeralNodeHolder>::~shared_ptr() @ 0xa63b213 in /usr/bin/clickhouse
9. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1412c1a1 in /usr/bin/clickhouse
10. DB::DDLWorker::scheduleTasks(bool) @ 0x141292e3 in /usr/bin/clickhouse
11. DB::DDLWorker::runMainThread() @ 0x14122ec5 in /usr/bin/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x141370b7 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
14. ? @ 0xa58881d in /usr/bin/clickhouse
15. ? @ 0x7f39f01dd609 in ?
16. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.446097 [ 11024 ] {} <Error> idd_shard.ingest (0a6808d7-9470-4c23-a2ed-9dbb5f4eebee): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::GetResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x158d5b0e in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryGetNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15893c7c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::getImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15893620 in /usr/bin/clickhouse
7. zkutil::ZooKeeper::tryGetWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>, Coordination::Error*) @ 0x1589449c in /usr/bin/clickhouse
8. zkutil::ZooKeeper::tryGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&, Coordination::Error*) @ 0x158941a7 in /usr/bin/clickhouse
9. zkutil::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x15893f5a in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x15066a65 in /usr/bin/clickhouse
11. DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x14bd5d7f in /usr/bin/clickhouse
12. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13b2dbae in /usr/bin/clickhouse
13. DB::BackgroundSchedulePool::threadFunction() @ 0x13b30527 in /usr/bin/clickhouse
14. ? @ 0x13b31530 in /usr/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
16. ? @ 0xa58881d in /usr/bin/clickhouse
17. ? @ 0x7f39f01dd609 in ?
18. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.447360 [ 10971 ] {} <Warning> idd_shard.ingest (ReplicatedMergeTreeRestartingThread): ZooKeeper session has expired. Switching to a new session.
2022.03.29 09:33:32.447667 [ 10971 ] {} <Error> zkutil::EphemeralNodeHolder::~EphemeralNodeHolder(): Cannot remove /clickhouse/tables/0a6808d7-9470-4c23-a2ed-9dbb5f4eebee/01/replicas/dev-ch01/is_active: : Code: 999. Coordination::Exception: Session expired (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::function<void (Coordination::RemoveResponse const&)>) @ 0x158d51a0 in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryRemoveNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15892704 in /usr/bin/clickhouse
6. zkutil::ZooKeeper::removeImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15892225 in /usr/bin/clickhouse
7. zkutil::EphemeralNodeHolder::~EphemeralNodeHolder() @ 0xa664cc3 in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::partialShutdown(bool) @ 0x1509d95d in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x15096d48 in /usr/bin/clickhouse
10. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x150951de in /usr/bin/clickhouse
11. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13b2dbae in /usr/bin/clickhouse
12. DB::BackgroundSchedulePool::threadFunction() @ 0x13b30527 in /usr/bin/clickhouse
13. ? @ 0x13b31530 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
15. ? @ 0xa58881d in /usr/bin/clickhouse
16. ? @ 0x7f39f01dd609 in ?
17. clone @ 0x7f39f0104293 in ?
  (version 22.3.2.1)
2022.03.29 09:33:32.527510 [ 10859 ] {acb6eb85-6d86-4e50-b606-c72df59970c6} <Error> executeQuery: Code: 999. Coordination::Exception: Session expired (Session expired): While executing DDLQueryStatus. (KEEPER_EXCEPTION) (version 22.3.2.1) (from [::ffff:172.27.100.1]:42050) (in query: -- Create underlying tables on each node for acap_configs
  CREATE TABLE IF NOT EXISTS idd_shard.acap_configs ON CLUSTER '{cluster}' ( -- Metric Columns
  apv_autopilot_enabled Nullable(Boolean), apv_camera_name Nullable(String) Codec(ZSTD(9)), apv_pan_kd Nullable(Float64) Codec(ZSTD(9)), apv_pan_ki Nullable(Float64) Codec(ZSTD(9)), apv_pan_kp Nullable(Float64) Codec(ZSTD(9)), apv_return_to_home_enabled Nullable(Boolean), apv_return_to_home_timeout Nullable(Int64) Codec(ZSTD(9)), apv_switch_object Nullable(Boolean), apv_tilt_kd Nullable(Float64) Codec(ZSTD(9)), apv_tilt_ki Nullable(Float64) Codec(ZSTD(9)), apv_tilt_kp Nullable(Float64) Codec(ZSTD(9)), apv_time_per_object Nullable(Int64) Codec(ZSTD(9)), dad_detection_enabled Nullable(Boolean), dad_detection_mode Nullable(Int64) Codec(ZSTD(9)), dad_minimum_threshold Nullable(Int64) Codec(ZSTD(9)), dad_ptz_control_enabled Nullable(Boolean), dad_ptz_control_timeout Nullable(Int64) Codec(ZSTD(9)), dad_ptz_pan_calibration Nullable(Int64) Codec(ZSTD(9)), dad_ptz_tilt_position Nullable(Int64) Codec(ZSTD(9)), dad_ptz_zoom_position Nullable(Int64) Codec(ZSTD(9)), dad_schedule_id Nullable(String) Codec(ZSTD(9)), dad_threshold Nullable(Int64) Codec(ZSTD(9)), idd_reason Nullable(String) Codec(ZSTD(9)), vms_view_mode Nullable(String) Codec(ZSTD(9)), -- Target Columns
  idd_acap_version LowCardinality(String) DEFAULT 'unknown' Codec(ZSTD(9)), agent_id String DEFAULT 'unknown' Codec(ZSTD(9)), boot_id String DEFAULT 'unknown' Codec(ZSTD(9)), custom_data String DEFAULT '' Codec(ZSTD(9)), data String DEFAULT '' Codec(ZSTD(9)), env LowCardinality(String) DEFAULT 'unknown' Codec(ZSTD(9)), feature_diff String DEFAULT '' Codec(ZSTD(9)), firmware_version LowCardinality(String) DEFAULT 'unknown' Codec(ZSTD(9)), hardware_id LowCardinality(String) DEFAULT 'unknown' Codec(ZSTD(9)), origin_path String DEFAULT 'unknown' Codec(ZSTD(9)), partition String DEFAULT 'unknown' Codec(ZSTD(9)), product_name LowCardinality(String) DEFAULT 'unknown' Codec(ZSTD(9)), serial_number String DEFAULT 'unknown' Codec(ZSTD(9)), site_id String DEFAULT 'unknown' Codec(ZSTD(9)), timestamp DateTime Codec(DoubleDelta, ZSTD(9)), uptime Nullable(UInt64) Codec(DoubleDelta, ZSTD(9)) ) ENGINE = ReplicatedMergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY ( product_name, serial_number, boot_id, timestamp );), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::ExistsResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x158d564e in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryExistsNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1589307c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::existsImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15892ada in /usr/bin/clickhouse
7. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1589352e in /usr/bin/clickhouse
8. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x15893415 in /usr/bin/clickhouse
9. DB::DDLQueryStatusSource::generate() @ 0x148c8c7c in /usr/bin/clickhouse
10. DB::ISource::tryGenerate() @ 0x1548cdf5 in /usr/bin/clickhouse
11. DB::ISource::work() @ 0x1548c9ba in /usr/bin/clickhouse
12. DB::SourceWithProgress::work() @ 0x156e4282 in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x154ad143 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x154a0b9e in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1549feeb in /usr/bin/clickhouse
16. DB::PipelineExecutor::execute(unsigned long) @ 0x1549f7b8 in /usr/bin/clickhouse
17. ? @ 0x154b0f8d in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
19. ? @ 0xa58881d in /usr/bin/clickhouse
20. ? @ 0x7f39f01dd609 in ?
21. clone @ 0x7f39f0104293 in ?

2022.03.29 09:33:32.529826 [ 10859 ] {acb6eb85-6d86-4e50-b606-c72df59970c6} <Error> TCPHandler: Code: 999. DB::Exception: Session expired (Session expired): While executing DDLQueryStatus. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x15888eb5 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x158891f6 in /usr/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x158d45d9 in /usr/bin/clickhouse
4. Coordination::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::ExistsResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x158d564e in /usr/bin/clickhouse
5. zkutil::ZooKeeper::asyncTryExistsNoThrow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1589307c in /usr/bin/clickhouse
6. zkutil::ZooKeeper::existsImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x15892ada in /usr/bin/clickhouse
7. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x1589352e in /usr/bin/clickhouse
8. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) @ 0x15893415 in /usr/bin/clickhouse
9. DB::DDLQueryStatusSource::generate() @ 0x148c8c7c in /usr/bin/clickhouse
10. DB::ISource::tryGenerate() @ 0x1548cdf5 in /usr/bin/clickhouse
11. DB::ISource::work() @ 0x1548c9ba in /usr/bin/clickhouse
12. DB::SourceWithProgress::work() @ 0x156e4282 in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x154ad143 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x154a0b9e in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1549feeb in /usr/bin/clickhouse
16. DB::PipelineExecutor::execute(unsigned long) @ 0x1549f7b8 in /usr/bin/clickhouse
17. ? @ 0x154b0f8d in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
19. ? @ 0xa58881d in /usr/bin/clickhouse
20. ? @ 0x7f39f01dd609 in ?
21. clone @ 0x7f39f0104293 in ?
```
</p>
</details>

**Additional context**

This error appeared after I resolved #35707 by manually editing `/etc/hosts` file to avoid the initial

```
DB::Exception: Mixing loopback and non-local hostnames
```

I am running 3 VMs with ClickHouse Keeper and 3 VMs with ClickHouse Server.

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Keeper improvement: requests are batched more often. The batching can be controlled with the new setting `max_requests_quick_batch_size`.

Trying to fix https://github.com/ClickHouse/ClickHouse/issues/35712
At one point, CH will send a lot of write requests at once. 
For example, in the case of https://gist.github.com/Slach/179dd9283ff16e2e2a1ca1e597bb64f6, after 10k rows, CH will send around 7k Multi request at the same time.
Keeper will process them 1 by 1 sequentially, not starting the next Multi request until the previous is processed by Raft. The delay will accumulate after some time, producing operation timeout.

The solution would be to try and batch more aggressively so we process requests in bulk. The problem would be getting the batch size right.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Coordination/KeeperDispatcher.cpp [hunk 1]
```diff
@@ -83,10 +83,11 @@ void KeeperDispatcher::requestThread()
                 {
                     current_batch.emplace_back(request);
 
+                    bool quick_batch_done = false;
                     /// Waiting until previous append will be successful, or batch is big enough
                     /// has_result == false && get_result_code == OK means that our request still not processed.
                     /// Sometimes NuRaft set errorcode without setting result, so we check both here.
-                    while (prev_result && (!prev_result->has_result() && prev_result->get_result_code() == nuraft::cmd_result_code::OK) && current_batch.size() <= max_batch_size)
+                    while ((!quick_batch_done && current_batch.size() < 10) || (prev_result && (!prev_result->has_result() && prev_result->get_result_code() == nuraft::cmd_result_code::OK) && current_batch.size() <= max_batch_size))
```
Comment (antonio2368) [inline src/Coordination/KeeperDispatcher.cpp:90]: The `10` should be a setting, need to figure out a reasonable default.

File: src/Coordination/CoordinationSettings.h [hunk 2]
```diff
@@ -37,7 +37,9 @@ struct Settings;
     M(UInt64, snapshots_to_keep, 3, "How many compressed snapshots to keep on disk", 0) \
     M(UInt64, stale_log_gap, 10000, "When node became stale and should receive snapshots from leader", 0) \
     M(UInt64, fresh_log_gap, 200, "When node became fresh", 0) \
-    M(UInt64, max_requests_batch_size, 100, "Max size of batch in requests count before it will be sent to RAFT", 0) \
+    M(UInt64, max_request_queue_size, 100000, "Maximum number of request that can be in queue for processing", 0) \
+    M(UInt64, max_requests_batch_size, 100, "Max size of batch of requests that can be sent to RAFT", 0) \
+    M(UInt64, max_requests_quick_batch_size, 10, "Maz size of batch of requests to try to get before proceeding with RAFT. Keeper will not wait for requests but take only requests that are already in queue" , 0) \
```
Comment (devcrafter) [inline src/Coordination/CoordinationSettings.h:42]:
```suggestion
    M(UInt64, max_requests_quick_batch_size, 10, "Max size of batch of requests to try to get before proceeding with RAFT. Keeper will not wait for requests but take only requests that are already in queue" , 0) \
```

File: src/Common/ConcurrentBoundedQueue.h [hunk 3]
```diff
@@ -138,11 +138,29 @@ class ConcurrentBoundedQueue
...
     }
 
+    /// Returns false if queue is empty.
+    [[nodiscard]] bool tryPop(T & x)
+    {
+        // we don't use popImpl to avoid CV wait
+        {
+            std::lock_guard queue_lock(queue_mutex);
+
+            if (queue.empty())
```
Comment (devcrafter) [inline src/Common/ConcurrentBoundedQueue.h:153]: `popImpl()` checks `is_finished`, should it be done here as well?

Comment (antonio2368) [reply src/Common/ConcurrentBoundedQueue.h:153]: `is_finished` is checked because `popImpl` waits on CV. We don't have a need for it because the `tryPop` without timeout will just check the queue under lock and instantly return. 
Notice also how `popImpl` will still return results even when the `is_finished` is set to `true` so we have the same behaviour but without using CV.

**Comment by antonio2368** [comment]
What's also important is that it has no negative effect on performance.
`YCSB` shows how performance for the single sequential client isn't affected, and there are some performance increases for multiple clients or single multithreaded clients like internal CH client.

File: src/Coordination/KeeperDispatcher.cpp [hunk 4]
```diff
@@ -83,30 +84,40 @@ void KeeperDispatcher::requestThread()
...
                         }
 
-                        if (shutdown_called)
-                            break;
+                        return false;
+                    };
+
+                    /// If we have enough requests in queue, we will try to batch at least max_quick_batch_size of them.
+                    size_t max_quick_batch_size = coordination_settings->max_requests_quick_batch_size;
+                    while (!shutdown_called && !has_read_request && current_batch.size() < max_quick_batch_size && try_get_request())
```
Comment (devcrafter) [inline src/Coordination/KeeperDispatcher.cpp:107]: Let's move try_get_request() to the loop body

File: src/Coordination/KeeperDispatcher.cpp [hunk 5]
```diff
@@ -83,30 +84,40 @@ void KeeperDispatcher::requestThread()
                 {
                     current_batch.emplace_back(request);
 
-                    /// Waiting until previous append will be successful, or batch is big enough
-                    /// has_result == false && get_result_code == OK means that our request still not processed.
-                    /// Sometimes NuRaft set errorcode without setting result, so we check both here.
-                    while (prev_result && (!prev_result->has_result() && prev_result->get_result_code() == nuraft::cmd_result_code::OK) && current_batch.size() <= max_batch_size)
+                    const auto try_get_request = [&]
```
Comment (devcrafter) [inline src/Coordination/KeeperDispatcher.cpp:87]: Probably, it'd be more natural to have `request` as in/out parameter in the lambda. Up to you.

File: src/Coordination/KeeperDispatcher.cpp (hunk 4 above)
Comment (devcrafter) [inline src/Coordination/KeeperDispatcher.cpp:107]: Logically, there is a caveat here, - if some requests are batched and then there are no incoming requests, we'll stay in this loop and hold the requests in `current_batch`.

File: src/Coordination/KeeperDispatcher.cpp (hunk 5 above)
Comment (antonio2368) [reply src/Coordination/KeeperDispatcher.cpp:87]: Yeah, but we don't use it instantly in the places where this function is called and if everything else is already captured don't see a reason to have `request` be different.

**Review by devcrafter — APPROVED** [review]
LGTM
