### PR TITLE
CSV unquoted nulls and default values

### LINKED ISSUE #5990: load data with CSVWithNames or TabSeparatedWithNames got error when two columns  continuous  null
I'm using clickhouse 19.9.2.4 , my csv file data like : 
business_id,dates,goods_id,tbill_code,membership_card_id,fact_new_card_id,atc1_new,atc2_new,atc3_new,atc4_new,goods_name,sex,age,birthdays,is_subscribe_wx,subscribe_time,subscribe_store,activate_time,activate_store,first_buy_date,paid_in_amt,profit
12501,2018-02-21,1062069,hnhys_PZ1A2500351654,801159913,801159913,OTC,儿科用药,儿童胃肠道用药,儿童消化不良/厌食,健儿清解液,2,NULL,NULL,0,NULL,A10U,NULL,A10U,2017-11-27,19.800000,8.300000

when I try to load data with CSVWithNames , I got error :  
Column 0,   name: business_id,        type: String,         parsed text: "12501"
Column 1,   name: dates,              type: String,         parsed text: "2018-02-21"
Column 2,   name: goods_id,           type: String,         parsed text: "1062069"
Column 3,   name: tbill_code,         type: String,         parsed text: "hnhys_PZ1A2500351654"
Column 4,   name: membership_card_id, type: String,         parsed text: "801159913"
Column 5,   name: fact_new_card_id,   type: String,         parsed text: "801159913"
Column 6,   name: atc1_new,           type: String,         parsed text: "OTC"
Column 7,   name: atc2_new,           type: String,         parsed text: "儿科用药"
Column 8,   name: atc3_new,           type: String,         parsed text: "儿童胃肠道用药"
Column 9,   name: atc4_new,           type: String,         parsed text: "儿童消化不良/厌食"
Column 10,  name: goods_name,         type: String,         parsed text: "健儿清解液"
Column 11,  name: sex,                type: UInt32,         parsed text: "2"
Column 12,  name: age,                type: UInt32,         ERROR: text "NULL,NULL," is not like UInt32

what should I do ?

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to few sentences):
Fixes #5990

Detailed description (optional):
For CSV input format:
- consider unquoted `NULL` literal as `\N` (if setting `format_csv_unquoted_null_literal_as_null=1`)
- initialize null fields with default values if data type of this field is not nullable (if setting `input_format_null_as_default=1`)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Should we rename `format_csv_unquoted_null_literal_as_null`
to `input_format_csv_unquoted_null_literal_as_null`
to have a chance to introduce a setting
`output_format_csv_unquoted_null_literal_as_null`
to write NULLs as NULL?

File: dbms/src/DataTypes/DataTypeNullable.cpp [hunk 1]
```diff
@@ -272,9 +272,58 @@ void DataTypeNullable::serializeTextCSV(const IColumn & column, size_t row_num,
...
-    safeDeserialize(column,
-        [&istr] { return checkStringByFirstCharacterAndAssertTheRest("\\N", istr); },
-        [this, &settings, &istr] (IColumn & nested) { nested_data_type->deserializeAsTextCSV(nested, istr, settings); });
+    constexpr char const * null_literal = "NULL";
+    constexpr size_t len = 4;
+    size_t null_prefix_len = 0;
+
+    auto check_for_null = [&istr, &settings, &null_prefix_len]
+    {
+        if (checkStringByFirstCharacterAndAssertTheRest("\\N", istr))
```
Comment (alexey-milovidov) [inline dbms/src/DataTypes/DataTypeNullable.cpp]: Is it Ok?

Comment (alexey-milovidov) [reply dbms/src/DataTypes/DataTypeNullable.cpp]: Ok.

**Comment by tavplubix** [comment]
> Should we rename `format_csv_unquoted_null_literal_as_null`
> to `input_format_csv_unquoted_null_literal_as_null`
> to have a chance to introduce a setting
> `output_format_csv_unquoted_null_literal_as_null`
> to write NULLs as NULL?

We can use `format_csv_unquoted_null_literal_as_null` for input and output (like `format_csv_delimiter`), but it may be inconvenient if user wants to read nulls as `\N` or `NULL` and write nulls as `\N`.

**Comment by alexey-milovidov** [comment]
> We can use format_csv_unquoted_null_literal_as_null for input and output (like format_csv_delimiter), but it may be inconvenient if user wants to read nulls as \N or NULL and write nulls as \N.

Let's split.

File: dbms/src/DataTypes/DataTypeNullable.cpp [hunk 2]
```diff
@@ -272,9 +272,58 @@ void DataTypeNullable::serializeTextCSV(const IColumn & column, size_t row_num,
...
+            /// so we need to prepend extracted characters (rare case)
+            ReadBufferFromMemory prepend(null_literal, null_prefix_len);
+            ConcatReadBuffer buf(prepend, istr);
+            nested_data_type->deserializeAsTextCSV(nested, buf, settings);
+
+            /// Check if all extracted characters was read by nested parser and update buffer position
+            if (null_prefix_len < buf.count())
+                istr.position() = buf.position();
+            else if (null_prefix_len > buf.count())
+                throw DB::Exception("Some characters were extracted from buffer, but nested parser did not read them",
```
Comment (alexey-milovidov) [inline dbms/src/DataTypes/DataTypeNullable.cpp]: Can this happen if there is something like `NU` in a place of numeric data type?
(and buffer is split in the middle of `NU`)
What will be the error message for the user?

**Comment by alexey-milovidov** [comment]
> 00411_long_accurate_number_comparison

Will be fixed after merge with master.

File: docs/en/operations/settings/settings.md [hunk 3]
```diff
@@ -211,6 +211,11 @@ Possible values:
 
 Default value: 0.
 
+## input_format_null_as_default {#settings-input_format_null_as_default}
```
Comment (alexey-milovidov) [inline docs/en/operations/settings/settings.md]: Shouldn't it be `input_format_csv_null_as_default`?

Suppose we want to implement similar logic to `TSV`. But in TSV it's much more dangerous, because there is no way to unambiguate from NULL and a String with 'NULL' value. But still usable (e.g. user has only numeric fields in a table). And this gives the motivation to allow the user to enable this logic separately for CSV and TSV.

File: dbms/tests/queries/0_stateless/00301_csv.sh [hunk 4]
```diff
@@ -24,5 +24,17 @@ echo '"2016-01-01 01:02:03","1"
 1502792101,"3"
 99999,"4"' | $CLICKHOUSE_CLIENT --query="INSERT INTO csv FORMAT CSV";
 
+echo '\N, \N' | $CLICKHOUSE_CLIENT --input_format_null_as_default=1 --query="INSERT INTO csv FORMAT CSV";
```
Comment (alexey-milovidov) [inline dbms/tests/queries/0_stateless/00301_csv.sh]: Better to make a separate test.

Comment (alexey-milovidov) [reply dbms/tests/queries/0_stateless/00301_csv.sh]: And we should have a test case with complex defaults.

File: docs/en/operations/settings/settings.md (hunk 3 above)
Comment (tavplubix) [reply docs/en/operations/settings/settings.md]: This setting is about replacing nulls with default values for non-nullable data types (#2633 and #6033), not about parsing `NULL` as `\N` (`input_format_null_as_default` and `input_format_csv_unquoted_null_literal_as_null` are independent). Should we add a separate setting `*_null_as_default` for each format?

Comment (alexey-milovidov) [reply docs/en/operations/settings/settings.md]: No. It's fine :)

File: dbms/src/DataTypes/DataTypeNullable.cpp (hunk 2 above)
Comment (tavplubix) [reply dbms/src/DataTypes/DataTypeNullable.cpp]: It can (also it can happen if `format_csv_delimiter` = `U` or `L`). I've changed the error message to print some diagnostic info.
