### PR TITLE
[ISSUE-76752] Allow UInt128 Conversion to IPv6 

### LINKED ISSUE #76752: Allow UInt128 (and Other Numeric Data Types) Conversion to IPv6
### Company or project name

Independent

### Describe the unexpected behaviour

`IPv6` can be converted to `UInt128`, however, it is not possible to convert `UInt128` to `IPv6`. This is especially needed when you're doing IPv6 arithmatics.

IPv4 supports numeric to IPv4 conversion and IPv4 to numeric conversion. Since IPv6 uses `UIn128` datatype, it should support same behaviour as well.

Integer to IPv6 Conversion:

```sql
SELECT toIPv4(4335);
/* 0.0.16.239 */

SELECT toIPv6(4335);
/* Expected */
/* ::10ef */
/* Actual */
/* Code: 48. DB::Exception: Conversion between numeric types and IPv6 is not supported. Probably the passed IPv6 is unquoted: In scope SELECT toIPv6(4335). (NOT_IMPLEMENTED) (version 25.2.1.1726 (official build)) */

```

IPv6 to UInt128 Conversion is permitted. However, the bitAnd operation returns a `UInt128` which _can not_ be converted to IPv6 wih

```sql

/* This works */
SELECT toIPv4(bitAnd(toIPv4('1.2.3.4'), toIPv4('1.4.1.1')))
/* 1.0.1.0 */

/* This doesn't work - It should work */
SELECT toIPv6(bitAnd(toIPv6('ffff:fff3:1fff:2fff:0000:0000:0000:0000'), toIPv6('f5f6:ffff:f32f:61ff:0000:0000:0000:0000')));
/* Code: 48. DB::Exception: Conversion between numeric types and IPv6 is not supported. Probably the passed IPv6 is unquoted: In scope SELECT toIPv6(bitAnd(toIPv6('ffff:fff3:1fff:2fff:0000:0000:0000:0000'), toIPv6('f5f6:ffff:f32f:61ff:0000:0000:0000:0000'))). (NOT_IMPLEMENTED) (version 25.2.1.1726 (official build)) */

```

The behaviour should be similar to `FixedString(16)`. This works as expected since they're bytes.

```sql
SELECT IPv6NumToString(bitAnd(IPv6StringToNum('ffff:fff3:1fff:2fff:0000:0000:0000:0000'), IPv6StringToNum('f5f6:ffff:f32f:61ff:0000:0000:0000:0000')));
/*	f5f6:fff3:132f:21ff:: */

```

### How to reproduce

```sql
SELECT toIPv4(4335);
SELECT toIPv6(4335);

SELECT toIPv4(bitAnd(toIPv4('1.2.3.4'), toIPv4('1.4.1.1')))
SELECT toIPv6(bitAnd(toIPv6('ffff:fff3:1fff:2fff:0000:0000:0000:0000'), toIPv6('f5f6:ffff:f32f:61ff:0000:0000:0000:0000')));
```

### Expected behavior

The `toIPv6` function should support reading numeric data types and return IPv6 data type.

### Error message and/or stacktrace

_No response_

### Additional context

Source: https://github.com/ClickHouse/ClickHouse/blob/faca41af119fe5958fec0c7618b8106cf581839b/src/Functions/FunctionsConversion.h#L1728-L1734

### PR DESCRIPTION
**Pull request by muzammilar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Adding Support for Converting UInt128 to IPv6. This allows the `bitAnd` operation and arithmatics for IPv6 and conversion back to IPv6. Closes https://github.com/ClickHouse/ClickHouse/issues/76752. This allows the result from `bitAnd` operation on IPv6 to be converted back to IPv6, as well. See: https://github.com/ClickHouse/ClickHouse/pull/57707

### Documentation entry for user-facing changes

- `toIPv6` documentation has been updated

### CODE REVIEW

File: src/Functions/FunctionsConversion.h [hunk 1]
```diff
@@ -1705,12 +1705,22 @@ struct ConvertImpl
...
                     vec_to[i].items[1] = std::byteswap(vec_from[i].toUnderType().items[0]);
                     vec_to[i].items[0] = std::byteswap(vec_from[i].toUnderType().items[1]);
                 }
+                else if constexpr (std::is_same_v<FromDataType, DataTypeUInt128> && std::is_same_v<ToDataType, DataTypeIPv6>)
+                {
+                    static_assert(
+                        std::is_same_v<DataTypeUInt128::FieldType, DataTypeIPv6::FieldType::UnderlyingType>,
+                        "IPv6 and UInt128 types must be same");
+
+                    // static_cast<ToFieldType>(static_cast<IPv4::UnderlyingType>(vec_from[i]))
```
Comment (muzammilar) [inline src/Functions/FunctionsConversion.h:1720]: ``

Comment (muzammilar) [inline src/Functions/FunctionsConversion.h:1720]:
```suggestion
```

File: src/Functions/FunctionsConversion.h [hunk 2]
```diff
@@ -1705,12 +1705,21 @@ struct ConvertImpl
...
                     vec_to[i].items[1] = std::byteswap(vec_from[i].toUnderType().items[0]);
                     vec_to[i].items[0] = std::byteswap(vec_from[i].toUnderType().items[1]);
                 }
+                else if constexpr (std::is_same_v<FromDataType, DataTypeUInt128> && std::is_same_v<ToDataType, DataTypeIPv6>)
+                {
+                    static_assert(
+                        std::is_same_v<DataTypeUInt128::FieldType, DataTypeIPv6::FieldType::UnderlyingType>,
+                        "IPv6 and UInt128 types must be same");
+
+                    vec_to[i].toUnderType().items[1] = std::byteswap(vec_from[i].items[0]);
```
Comment (alexey-milovidov) [inline src/Functions/FunctionsConversion.h:1720]: I'm not sure about this.

**Comment by alexey-milovidov** [comment]
Also, add a test that

`SELECT toIPv6(1512366075204170938810683009357704959::UInt128) = '0123:4567:89ab:cdef:8899:aabb:ccdd:eeff'::IPv6`

File: src/Functions/FunctionsConversion.h (hunk 2 above)
Comment (muzammilar) [reply src/Functions/FunctionsConversion.h:1720]: I wasn't sure about this either, initially. I actually copied this from here: https://github.com/ClickHouse/ClickHouse/pull/76928/files#diff-2859e9a878020ac61a5586d7413871dfc37b790071c191bc1fe3f091ee56370eR1711-R1712

After my testing, I realized that IPv6 in clickhouse is stored in 16 bytes as UInt128 big-endian, so we need to reverse the byte order from UInt128's default (at least little-endian for linux).
https://clickhouse.com/docs/sql-reference/data-types/ipv6

I added a few more tests to catch the byte order issues, as well

**Comment by muzammilar** [comment]
> Also, add a test that
> 
> `SELECT toIPv6(1512366075204170938810683009357704959::UInt128) = '0123:4567:89ab:cdef:8899:aabb:ccdd:eeff'::IPv6`

Done!

IPv6 has different endianness from  UInt128's, so it has to be reversed.
https://clickhouse.com/docs/sql-reference/data-types/ipv6

**Review by alexey-milovidov — APPROVED** [review]

**Comment by muzammilar** [comment]
@alexey-milovidov I've tried rebasing and testing but I'm not sure this function is causing some of the test to fail. Most of the failures seem tangential from this pull, I think.

**Comment by muzammilar** [comment]
@alexey-milovidov would it be possible to merge it please? I don't have merge permissions.
