### PR TITLE
Fix column not found with residual condition in JOIN ON

### LINKED ISSUE #88635: NOT_FOUND_COLUMN_IN_BLOCK with query_plan_use_new_logical_join_step
### Describe the bug

Easy to reproduce.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/d36f2ba3-e13a-4dd6-97fa-67a98193ea97

### Error message and/or stacktrace

Stack trace:
```
<Error> TCPHandler: Code: 10. DB::Exception: Not found column __join_result_dummy in block. There are only columns: __table1.c0. (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000241d1572
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014aa46e9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d38d30e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d38cd11
4. src/Common/Exception.h:141: DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000e270c36
5. src/Core/Block.cpp:409: DB::Block::getPositionByName(String const&, bool) const @ 0x0000000019348863
6. src/Core/Block.cpp:348: DB::Block::getByName(String const&, bool) const @ 0x0000000019348709
7. src/Processors/QueryPlan/Optimizations/convertJoinToIn.cpp:192: DB::QueryPlanOptimizations::tryConvertJoinToIn(DB::QueryPlan::Node*, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlanOptimizations::Optimization::ExtraSettings const&) @ 0x000000001eb80053
8. src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:103: DB::QueryPlanOptimizations::optimizeTreeFirstPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x000000001eb21af4
9. src/Processors/QueryPlan/QueryPlan.cpp:505: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001ea3950a
10. src/Processors/QueryPlan/QueryPlan.cpp:180: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001ea38dc0
11. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x000000001a81cbe9
12. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001a81c91c
13. src/Interpreters/executeQuery.cpp:1603: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x000000001ab3c702
14. src/Interpreters/executeQuery.cpp:1812: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001ab36372
15. src/Server/TCPHandler.cpp:744: DB::TCPHandler::runImpl() @ 0x000000001e409cae
16. src/Server/TCPHandler.cpp:2818: DB::TCPHandler::run() @ 0x000000001e423a24
17. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000024287f87
18. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000024288565
19. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000242276ff
20. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000024224dd1
21. start_thread @ 0x00000000000a27f1
22. __GI___clone3 @ 0x0000000000133b5c
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix 'column not found' error with query_plan_use_logical_join_step=0 and residual condition in JOIN ON. Resolves #88635

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by nickitat — APPROVED** [review]

File: tests/queries/0_stateless/03721_join_residual_condition_bug_88635.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+SELECT 1 FROM numbers(3) tx
```
Comment (vdimir) [inline tests/queries/0_stateless/03721_join_residual_condition_bug_88635.sql:3]:
```suggestion
SET enable_analyzer = 1;

SELECT 1 FROM numbers(3) tx
```
