### PR TITLE
Pretty formats: display column names in footer if the table is long.

### LINKED ISSUE #65035: Pretty formats: if the table is long, display column names also in the footer.
For example,

```
   ┌─status─────┬─sum(rows_processed)─┐
1. │ Failed     │         43631271314 │
2. │ Processed  │        284673840204 │
3. │ Processing │          6755465755 │
   └────────────┴─────────────────────┘
```

if there are many records (the threshold should be controlled by the setting), it should look like:
```
     ┌─status─────┬─sum(rows_processed)─┐
  1. │ Failed     │         43631271314 │
  2. │ Processed  │        284673840204 │
...
999. │ Processing │          6755465755 │
     └─status─────┴─sum(rows_processed)─┘
```

### PR DESCRIPTION
**Pull request by Blargian**
Adds a setting `output_format_pretty_display_footer_column_names` to display column names in a table footer when the number of rows is more than or equal to the value controlled by `output_format_pretty_display_footer_column_names_min_rows`. 

Closes [#65035](https://github.com/ClickHouse/ClickHouse/issues/65035)

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added a setting `output_format_pretty_display_footer_column_names` which when enabled displays column names at the end of the table for long tables (50 rows by default), with the threshold value for minimum number of rows controlled by `output_format_pretty_display_footer_column_names_min_rows`.  

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/Formats/Impl/PrettyBlockOutputFormat.cpp [hunk 1]
```diff
@@ -239,43 +256,47 @@ void PrettyBlockOutputFormat::writeChunk(const Chunk & chunk, PortKind port_kind
     }
 
     /// Names
-    writeCString(grid_symbols.bold_bar, out);
-    writeCString(" ", out);
-    for (size_t i = 0; i < num_columns; ++i)
+    auto write_names = [&]() -> void
```
Comment (Blargian) [inline src/Processors/Formats/Impl/PrettyBlockOutputFormat.cpp:259]: This part of the code can be reused in the footer so I have made it a lambda which gets called again later in the code if the setting is true.

File: src/Processors/Formats/Impl/PrettySpaceBlockOutputFormat.cpp [hunk 2]
```diff
@@ -36,39 +36,43 @@ void PrettySpaceBlockOutputFormat::writeChunk(const Chunk & chunk, PortKind port
     if (format_settings.pretty.output_format_pretty_row_numbers)
         writeString(String(row_number_width, ' '), out);
     /// Names
-    for (size_t i = 0; i < num_columns; ++i)
+    auto write_names = [&]() -> void
```
Comment (Blargian) [inline src/Processors/Formats/Impl/PrettySpaceBlockOutputFormat.cpp:39]: Code can be reused in the footer so have made it a lambda

File: src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp [hunk 3]
```diff
@@ -57,7 +57,8 @@ PrettyCompactBlockOutputFormat::PrettyCompactBlockOutputFormat(WriteBuffer & out
 void PrettyCompactBlockOutputFormat::writeHeader(
     const Block & block,
     const Widths & max_widths,
-    const Widths & name_widths)
+    const Widths & name_widths,
+    const bool write_footer)
```
Comment (Blargian) [inline src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp:61]: The footer and header only have a few differences. I wanted to template this function as `writeHeader<is_footer>` and add a `if constexpr` check, but it's simpler to add a new parameter here otherwise I need to make changes in both .cpp and .h files. 

When something needs to change for the footer it is found under `if (write_footer)`

File: src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.h [hunk 4]
```diff
@@ -17,7 +17,7 @@ class PrettyCompactBlockOutputFormat : public PrettyBlockOutputFormat
     String getName() const override { return "PrettyCompactBlockOutputFormat"; }
 
 private:
-    void writeHeader(const Block & block, const Widths & max_widths, const Widths & name_widths);
+    void writeHeader(const Block & block, const Widths & max_widths, const Widths & name_widths, const bool write_footer);
```
Comment (Blargian) [inline src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.h:20]: see above comment

File: docs/en/interfaces/formats.md [hunk 5]
```diff
@@ -1490,6 +1490,7 @@ Differs from [PrettySpaceNoEscapes](#prettyspacenoescapes) in that up to 10,000
 - [output_format_pretty_color](/docs/en/operations/settings/settings-formats.md/#output_format_pretty_color) - use ANSI escape sequences to paint colors in Pretty formats. Default value - `true`.
 - [output_format_pretty_grid_charset](/docs/en/operations/settings/settings-formats.md/#output_format_pretty_grid_charset) - Charset for printing grid borders. Available charsets: ASCII, UTF-8. Default value - `UTF-8`.
 - [output_format_pretty_row_numbers](/docs/en/operations/settings/settings-formats.md/#output_format_pretty_row_numbers) - Add row numbers before each row for pretty output format. Default value - `true`.
+- [output_format_pretty_display_footer_column_names](/docs/en/operations/settings/settings-formats.md/#output_format_pretty_display_footer_column_names) - Display column names in the footer if there are more than 1000 rows. Default value - `false`.
```
Comment (alexey-milovidov) [inline docs/en/interfaces/formats.md:1493]: Let's also make a setting for a threshold:

`output_format_pretty_display_footer_column_names_min_rows`

and make it just 50 by default.

Also, enable `output_format_pretty_display_footer_column_names` by default.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 37e03ef320c63022d727a7c6cf201131f6e20731 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65144/37e03ef320c63022d727a7c6cf201131f6e20731/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp (hunk 3 above)
Comment (alexey-milovidov) [reply src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp:61]: Yes, and a regular function argument is better than a template :+1:

**Comment by alexey-milovidov** [comment]
```
Jun 14 02:58:18 /build/src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.h:20:98: error: parameter 'write_footer' is const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions [readability-avoid-const-params-in-decls,-warnings-as-errors]
Jun 14 02:58:18    20 |     void writeHeader(const Block & block, const Widths & max_widths, const Widths & name_widths, const bool write_footer);
Jun 14 02:58:18       |                                                                                                  ^~~~~
```

**Review by Avogar — APPROVED** [review]
Looks great, thank you!

**Comment by clickgapai** [comment]
Hi @Blargian @Avogar — while reviewing this PR I found the following:

- **Bug (P3):** Footer decision uses per-chunk row count instead of cumulative total — https://github.com/ClickHouse/ClickHouse/issues/104508

Happy to discuss — close anything that's wrong or already addressed.
