### PR TITLE
Fix rare deadlock at shutdown of BackgroundSchedulePool

### LINKED ISSUE #18891: clickhouse-local cannot shutdown correctly.
**How to reproduce**
```
for i in {1..1000}; do echo 'Hello, world!' | clickhouse-local --query "SELECT * FROM table" --structure 's String' | wc -c; done
```

This script hangs.

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed very rare deadlock at shutdown

Detailed description / Documentation draft:
Fixes #18891.

### CODE REVIEW

File: src/Core/BackgroundSchedulePool.cpp [hunk 1]
```diff
@@ -250,7 +250,16 @@ void BackgroundSchedulePool::threadFunction()
...
+        /// We have to wait with timeout to prevent very rare deadlock, caused by the following race condition:
+        /// 1. Background thread N: threadFunction(): checks for shutdown (it's false)
+        /// 2. Main thread: ~BackgroundSchedulePool(): sets shutdown to true, calls queue.wakeUpAll(), it triggers
+        ///    all existing Poco::Events inside Poco::NotificationQueue which background threads are waiting on.
+        /// 3. Background thread N: threadFunction(): calls queue.waitDequeueNotification(), it creates
+        ///    new Poco::Event inside Poco::NotificationQueue and starts to wait on it
+        /// Background thread N will never be woken up.
+        /// TODO Do we really need Poco::NotificationQueue? Why not to use std::queue + mutex + condvar or maybe even DB::ThreadPool?
+        constexpr size_t wait_timeout_ms = 500;
+        if (Poco::AutoPtr<Poco::Notification> notification = queue.waitDequeueNotification(wait_timeout_ms))
```
Comment (azat) [inline src/Core/BackgroundSchedulePool.cpp:262]: Superior wake-up doesn't looks good, and indeed convar looks better to me
