### PR TITLE
Try fix `02023_storage_filelog`

### LINKED ISSUE #84372: Test `02023_storage_filelog` is flaky
### Describe the bug

https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDIwMjNfc3RvcmFnZV9maWxlbG9nJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes: #84372

### CODE REVIEW

File: tests/queries/0_stateless/02023_storage_filelog.sh [hunk 1]
```diff
@@ -39,6 +39,8 @@ mv ${USER_FILES_PATH}/${CLICKHOUSE_TEST_UNIQUE_NAME}/b.txt ${USER_FILES_PATH}/${
 
 rm ${USER_FILES_PATH}/${CLICKHOUSE_TEST_UNIQUE_NAME}/d.txt
 
+sleep 2
```
Comment (nickitat) [inline tests/queries/0_stateless/02023_storage_filelog.sh:42]: I understand shit about how this feature works, but what I do understand is that I get similar output to these two failures 
* https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82807&sha=164f1794b318f4affe0677b473f56fb0b751294a&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%2C%20parallel%29
* https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84323&sha=783b64bbd61b3fca611c85a7393e13aa528521f2&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_debug%2C%20parallel%29

If I reorder the `rm` above with the following `select`

And the second type of failure 
* https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84087&sha=2e2cbe22a9bdc0ab54a5e67ec115b9221f7952e5&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%2C%20parallel%29

Happens if I reorder the `truncate` below with the `select` that follows it.

So, I assume there is some race between receiving/processing fs events and queries we send to the server.

**Review by yariks5s — APPROVED** [review]
