### PR TITLE
Avoid writing to finalized buffer in File-like storages

### LINKED ISSUE #62962: ParquetBlockOutputFormat/ParquetBlockOutputFormat: Cannot write to finalized buffer
https://s3.amazonaws.com/clickhouse-test-reports/62908/f0462efb73511944704471eb77e3c7ceb7502364/stress_test__asan_.html

```
 [ 13157 ] {12bf8a4f-1d01-4b62-a4e0-132c0609d685} <Fatal> : Logical error: \'Cannot write to finalized buffer\'.
 [ 3274 ] {} <Fatal> Application: Child process was terminated by signal 6.


2024-04-25 00:32:49 Thread 1152 "QueryPipelineEx" received signal SIGABRT, Aborted.
2024-04-25 00:32:49 [Switching to Thread 0x7f13ebaf9640 (LWP 13157)]
2024-04-25 00:32:49 0x00007f1ac367f9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-25 00:32:49 #0  0x00007f1ac367f9fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #1  0x00007f1ac362b476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #2  0x00007f1ac36117f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #3  0x000055e2786574b5 in DB::abortOnFailedAssertion (description=...) at ./build_docker/./src/Common/Exception.cpp:44
2024-04-25 00:32:49 No locals.
2024-04-25 00:32:49 #4  0x000055e27865925e in DB::handle_error_code (msg=..., trace=..., code=<optimized out>, remote=<optimized out>) at ./build_docker/./src/Common/Exception.cpp:61
2024-04-25 00:32:49 No locals.
2024-04-25 00:32:49 #5  DB::Exception::Exception (this=0x516003494200, msg_masked=..., code=<optimized out>, remote_=<optimized out>) at ./build_docker/./src/Common/Exception.cpp:105
2024-04-25 00:32:49 No locals.
2024-04-25 00:32:49 #6  0x000055e2666e908a in DB::Exception::Exception(PreformattedMessage&&, int) ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #7  0x000055e26670feb4 in DB::Exception::Exception<>(int, FormatStringHelperImpl<>) ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #8  0x000055e28e77a677 in DB::WriteBuffer::write (this=0x5130032ab740, from=0x521010572100 "\025\004\031\374j5", n=3217) at ./src/IO/WriteBuffer.h:82
2024-04-25 00:32:49         bytes_copied = <optimized out>
2024-04-25 00:32:49 #9  DB::ArrowBufferedOutputStream::Write (this=0x507000c3e518, data=<optimized out>, length=<optimized out>) at ./build_docker/./src/Processors/Formats/Impl/ArrowBufferedStreams.cpp:47
2024-04-25 00:32:49 No locals.
2024-04-25 00:32:49 #10 0x000055e297cc3c35 in long parquet::ThriftSerializer::Serialize<parquet::format::FileMetaData>(parquet::format::FileMetaData const*, arrow::io::OutputStream*, std::__1::shared_ptr<parquet::Encryptor> const&) ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #11 0x000055e297ca6d53 in parquet::FileMetaData::FileMetaDataImpl::WriteTo(arrow::io::OutputStream*, std::__1::shared_ptr<parquet::Encryptor> const&) const ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #12 0x000055e297b9c8c8 in parquet::WriteFileMetaData(parquet::FileMetaData const&, arrow::io::OutputStream*) ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #13 0x000055e297ba2978 in parquet::FileSerializer::Close() ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #14 0x000055e297b9b3e8 in parquet::ParquetFileWriter::~ParquetFileWriter() ()
2024-04-25 00:32:49 No symbol table info available.
2024-04-25 00:32:49 #15 0x000055e29792ec6d in parquet::arrow::FileWriterImpl::~FileWriterImpl() ()
2024-04-25 00:32:50 No symbol table info available.
2024-04-25 00:32:50 #16 0x000055e29792edae in parquet::arrow::FileWriterImpl::~FileWriterImpl() ()
2024-04-25 00:32:53 No symbol table info available.
2024-04-25 00:32:53 #17 0x000055e28ec16de9 in std::__1::default_delete<parquet::arrow::FileWriter>::operator()[abi:v15000](parquet::arrow::FileWriter*) const (this=<optimized out>, __ptr=0xccc) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48
2024-04-25 00:32:57 No locals.
2024-04-25 00:32:57 #18 std::__1::unique_ptr<parquet::arrow::FileWriter, std::__1::default_delete<parquet::arrow::FileWriter> >::reset[abi:v15000](parquet::arrow::FileWriter*) (this=<optimized out>, __p=0x0) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305
2024-04-25 00:33:00         __tmp = 0xccc
2024-04-25 00:33:00 #19 std::__1::unique_ptr<parquet::arrow::FileWriter, std::__1::default_delete<parquet::arrow::FileWriter> >::~unique_ptr[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #20 DB::ParquetBlockOutputFormat::~ParquetBlockOutputFormat (this=0x51d00366c898) at ./build_docker/./src/Processors/Formats/Impl/ParquetBlockOutputFormat.cpp:114
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #21 0x000055e28ca6d8d1 in std::__1::__shared_count::__release_shared[abi:v15000]() (this=0x51d00366c880) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #22 std::__1::__shared_weak_count::__release_shared[abi:v15000]() (this=0x51d00366c880) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #23 std::__1::shared_ptr<DB::IOutputFormat>::~shared_ptr[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #24 std::__1::shared_ptr<DB::IOutputFormat>::reset[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:768
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #25 DB::StorageURLSink::release (this=this@entry=0x51400340fa58) at ./build_docker/./src/Storages/StorageURL.cpp:618
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #26 0x000055e28ca6d524 in DB::StorageURLSink::finalize (this=this@entry=0x51400340fa58) at ./build_docker/./src/Storages/StorageURL.cpp:611
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #27 0x000055e28ca6d401 in DB::StorageURLSink::onCancel (this=0x51400340fa58) at ./build_docker/./src/Storages/StorageURL.cpp:573
2024-04-25 00:33:00         lock = {__m_ = @0x51400340fbd0}
2024-04-25 00:33:00 #28 0x000055e28e6dc0c8 in DB::IProcessor::cancel (this=0xccc) at ./src/Processors/IProcessor.h:245
2024-04-25 00:33:00         already_cancelled = <optimized out>
2024-04-25 00:33:00 #29 DB::ExecutingGraph::cancel (this=<optimized out>, cancel_all_processors=<optimized out>) at ./build_docker/./src/Processors/Executors/ExecutingGraph.cpp:420
2024-04-25 00:33:00         processor = 0xccc
2024-04-25 00:33:00         proc = 57
2024-04-25 00:33:00         guard = {__m_ = @0x5130034fb6a8}
2024-04-25 00:33:00         num_processors = <optimized out>
2024-04-25 00:33:00         exception_ptr = {__ptr_ = 0x0}
2024-04-25 00:33:00 #30 0x000055e28e6ce1aa in DB::PipelineExecutor::cancel (this=0x514002d0a858) at ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:83
2024-04-25 00:33:00 No locals.
2024-04-25 00:33:00 #31 DB::PipelineExecutor::executeStepImpl (this=0x514002d0a858, thread_num=<optimized out>, yield_flag=0x0) at ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:274
2024-04-25 00:33:02         context = @0x511003853280: {async_tasks = {c = {<std::__1::__deque_base<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> >> = {static __block_size = <optimized out>, __map_ = {__first_ = 0x0, __begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ExecutingGraph::Node***, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ExecutingGraph::Node**>, 1, true>> = {<std::__1::allocator<DB::ExecutingGraph::Node**>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ExecutingGraph::Node**> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, __start_ = 0, __size_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = 0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ExecutingGraph::Node*>, 1, true>> = {<std::__1::allocator<DB::ExecutingGraph::Node*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ExecutingGraph::Node*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}}, has_async_tasks = {<std::__1::__atomic_base<bool, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<bool>> = {__a_value = false}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, condvar = {__cv_ = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}}, mutex = {__m_ = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, wake_flag = true, node = 0x51100473a000, exception = {__ptr_ = 0x0}, read_progress_callback = 0x50b0017824e0, thread_number = 0, profile_processors = true, trace_processors = false, static max_scheduled_local_tasks = 128, num_scheduled_local_tasks = 11}
2024-04-25 00:33:02         yield = false
2024-04-25 00:33:02         queue = <optimized out>
2024-04-25 00:33:02         async_queue = <optimized out>
2024-04-25 00:33:02 #32 DB::PipelineExecutor::executeSingleThread (this=0x514002d0a858, thread_num=<optimized out>) at ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:239
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #33 0x000055e28e6cf386 in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const (this=<optimized out>) at ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:373
2024-04-25 00:33:02         scope_exit365 = {static is_nullable = false, function = {<No data fields>}}
2024-04-25 00:33:02 #34 std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #35 std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) (__args=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #36 std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]() (this=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:235
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #37 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>) at ./contrib/llvm-project/libcxx/include/__functional/function.h:716
2024-04-25 00:33:02         __f = <optimized out>
2024-04-25 00:33:02 #38 0x000055e278889c3b in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7f13eac9dc60) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #39 std::__1::function<void ()>::operator()() const (this=0x7f13eac9dc60) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #40 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::worker (this=0x512002895340, thread_it=...) at ./build_docker/./src/Common/ThreadPool.cpp:458
2024-04-25 00:33:02         metric_active_pool_threads = {what = <optimized out>, amount = 1}
2024-04-25 00:33:02         job_data = {<std::__1::__optional_move_assign_base<JobWithPriority, false>> = {<std::__1::__optional_copy_assign_base<JobWithPriority, false>> = {<std::__1::__optional_move_base<JobWithPriority, false>> = {<std::__1::__optional_copy_base<JobWithPriority, false>> = {<std::__1::__optional_storage_base<JobWithPriority, false>> = {<std::__1::__optional_destruct_base<JobWithPriority, false>> = {{__null_state_ = -48 '\320', __val_ = {job = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = {-48 '\320', <optimized out> <repeats 15 times>}, __large = <optimized out>}, __invoker_ = {__call_ = <optimized out>}, __policy_ = <optimized out>}}, priority = {value = <optimized out>}, metric_increment = {what = <optimized out>, amount = <optimized out>}, thread_trace_context = {<DB::OpenTelemetry::TracingContext> = {trace_id = {t = {items = {<optimized out>, <optimized out>}}}, span_id = <optimized out>, tracestate = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = <optimized out>, __size_ = <optimized out>, __cap_ = <optimized out>, __is_long_ = <optimized out>}, __s = {__data_ = {<optimized out> <repeats 23 times>}, __padding_ = 0x0, __size_ = <optimized out>, __is_long_ = <optimized out>}, __r = {__words = {<optimized out>, <optimized out>, <optimized out>}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, trace_flags = <optimized out>}, span_log = {__ptr_ = <optimized out>, __cntrl_ = <optimized out>}}, frame_pointers = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, enable_job_stack_trace = <optimized out>}}, __engaged_ = true}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<false, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<false, true>> = {<No data fields>}, <No data fields>}
2024-04-25 00:33:02         thread_trace_context = <optimized out>
2024-04-25 00:33:02         exception_from_job = {__ptr_ = 0x0}
2024-04-25 00:33:02         metric_pool_threads = {what = 0x55e29f9d9658 <CurrentMetrics::values+1496>, amount = 1}
2024-04-25 00:33:02         job_is_done = false
2024-04-25 00:33:02 #41 0x000055e27889371d in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=<optimized out>) at ./build_docker/./src/Common/ThreadPool.cpp:220
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #42 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #43 std::__1::__apply_tuple_impl[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&, std::__1::__tuple_indices<>) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1789
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #44 std::__1::apply[abi:v15000]<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&, std::__1::tuple<>&) (__f=..., __t=...) at ./contrib/llvm-project/libcxx/include/tuple:1798
2024-04-25 00:33:02 No locals.
2024-04-25 00:33:02 #45 ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true> >::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&)::{lambda()#1}::operator()() (this=<optimized out>) at ./src/Common/ThreadPool.h:246
2024-04-25 00:33:03         scope_exit228 = {static is_nullable = false, function = {my_state = @0x5060034745c0}}
2024-04-25 00:33:03         function = {this = 0x512002895340, it = {__ptr_ = 0x503000aa04a0}}
2024-04-25 00:33:03         arguments = <optimized out>
2024-04-25 00:33:03         thread_status = <optimized out>
2024-04-25 00:33:03 #46 0x000055e2788818cd in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const (this=0x7f13eabf9060) at ./contrib/llvm-project/libcxx/include/__functional/function.h:848
2024-04-25 00:33:03 No locals.
2024-04-25 00:33:03 #47 std::__1::function<void ()>::operator()() const (this=0x7f13eabf9060) at ./contrib/llvm-project/libcxx/include/__functional/function.h:1187
2024-04-25 00:33:03 No locals.
2024-04-25 00:33:03 #48 ThreadPoolImpl<std::__1::thread>::worker (this=0x5120000223c0, thread_it=...) at ./build_docker/./src/Common/ThreadPool.cpp:458
2024-04-25 00:33:03         metric_active_pool_threads = {what = <optimized out>, amount = 1}
2024-04-25 00:33:03         job_data = {<std::__1::__optional_move_assign_base<JobWithPriority, false>> = {<std::__1::__optional_copy_assign_base<JobWithPriority, false>> = {<std::__1::__optional_move_base<JobWithPriority, false>> = {<std::__1::__optional_copy_base<JobWithPriority, false>> = {<std::__1::__optional_storage_base<JobWithPriority, false>> = {<std::__1::__optional_destruct_base<JobWithPriority, false>> = {{__null_state_ = -64 '\300', __val_ = {job = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = {-64 '\300', <optimized out> <repeats 15 times>}, __large = <optimized out>}, __invoker_ = {__call_ = <optimized out>}, __policy_ = <optimized out>}}, priority = {value = <optimized out>}, metric_increment = {what = <optimized out>, amount = <optimized out>}, thread_trace_context = {<DB::OpenTelemetry::TracingContext> = {trace_id = {t = {items = {<optimized out>, <optimized out>}}}, span_id = <optimized out>, tracestate = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = <optimized out>, __size_ = <optimized out>, __cap_ = <optimized out>, __is_long_ = <optimized out>}, __s = {__data_ = {<optimized out> <repeats 23 times>}, __padding_ = 0x0, __size_ = <optimized out>, __is_long_ = <optimized out>}, __r = {__words = {<optimized out>, <optimized out>, <optimized out>}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, trace_flags = <optimized out>}, span_log = {__ptr_ = <optimized out>, __cntrl_ = <optimized out>}}, frame_pointers = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::array<void*, 45ul>*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::array<void*, 45ul> >, 1, true>> = {<std::__1::allocator<std::__1::array<void*, 45ul> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::array<void*, 45ul> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, enable_job_stack_trace = <optimized out>}}, __engaged_ = true}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<false, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<false, true>> = {<No data fields>}, <No data fields>}
2024-04-25 00:33:03         thread_trace_context = <optimized out>
2024-04-25 00:33:03         exception_from_job = {__ptr_ = 0x0}
2024-04-25 00:33:03         metric_pool_threads = {what = 0x55e29f9d9290 <CurrentMetrics::values+528>, amount = 1}
2024-04-25 00:33:03         job_is_done = <optimized out>
2024-04-25 00:33:03 #49 0x000055e27888ed4d in ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}::operator()() const (this=<optimized out>) at ./build_docker/./src/Common/ThreadPool.cpp:220
2024-04-25 00:33:03 No locals.
2024-04-25 00:33:03 #50 std::__1::__invoke[abi:v15000]<ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}&&) (__f=...) at ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394
2024-04-25 00:33:03 No locals.
2024-04-25 00:33:03 #51 std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}>&, std::__1::__tuple_indices<>) (__t=...) at ./contrib/llvm-project/libcxx/include/thread:284
2024-04-25 00:33:03 No locals.
2024-04-25 00:33:03 #52 std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::{lambda()#2}> >(void*) (__vp=<optimized out>) at ./contrib/llvm-project/libcxx/include/thread:295
2024-04-25 00:33:03         __p = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ./src/Common/ThreadPool.cpp:220:42)> *, 0, false>> = {__value_ = 0x5030011fd940}, <std::__1::__compressed_pair_elem<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ./src/Common/ThreadPool.cpp:220:42)> >, 1, true>> = {<std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ./src/Common/ThreadPool.cpp:220:42)> >> = {<No data fields>}, <No data fields>}, <No data fields>}}
2024-04-25 00:33:03 #53 0x000055e26669965b in asan_thread_start(void*) ()
2024-04-25 00:33:03 No symbol table info available.
2024-04-25 00:33:03 #54 0x00007f1ac367dac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-25 00:33:03 No symbol table info available.
2024-04-25 00:33:03 #55 0x00007f1ac370f850 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-25 00:33:03 No symbol table info available.
2024-04-25 00:33:03 
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid writing to finalized buffer in File-like storages

Closes https://github.com/ClickHouse/ClickHouse/issues/62962.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 5f7683f3914b0270ada6334c87410780074b71fd with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65063/5f7683f3914b0270ada6334c87410780074b71fd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Storages/ObjectStorage/StorageObjectStorageSink.cpp [hunk 1]
```diff
@@ -83,20 +83,21 @@ void StorageObjectStorageSink::finalize()
...
     }
+
+    write_buf->finalize();
 }
 
 void StorageObjectStorageSink::release()
 {
     writer.reset();
-    write_buf.reset();
+    write_buf->finalize();
```
Comment (kssenii) [inline src/Storages/ObjectStorage/StorageObjectStorageSink.cpp:100]: I assume finalize() was not called here on purpose https://github.com/ClickHouse/ClickHouse/commit/2c018f5261553dd6106639f22c148fbdd61d8fc4#diff-a118e043f3175929dbe8a96c6dcc7db80e31ddae5581f29b4286eb9e2d9d925d

Comment (Avogar) [reply src/Storages/ObjectStorage/StorageObjectStorageSink.cpp:100]: I was confused because StorageFile and StorageURL had `finalize()` in the same place (and before StorageObject only StorageS3 didn't have `finalize()`). I am still not 100% sure that it's safe to just call `.reset()` here as we still can call finalize in destructor. Let me check the write buffers that could be used, maybe it's actually safe and we can use `.reset()` in all such places

Comment (kssenii) [reply src/Storages/ObjectStorage/StorageObjectStorageSink.cpp:100]: > and before StorageObject only StorageS3 didn't have finalize()

Yeah I also noticed that during refactoring (this finalize() was also there for `StorageAzure`) and changed it the same way, but it resulted in failing s3 tests

**Review by kssenii — APPROVED** [review]
