### PR TITLE
Fix materialised pg syncTables

### LINKED ISSUE #49586: When I use MaterializedPostgreSQL, it stops working after synchronizing the full amount of data
After synchronizing all the existing data, it stopped working. 
When PostgreSQL has incremental data, ClickHouse does not synchronize updates.
Then I query the slot status (SELECT * FROM pg_replication_slots;), active is false.

- version
```
clickhouse: 22.5
postgres: 13
```
- sql

```
CREATE DATABASE test_copy
ENGINE = MaterializedPostgreSQL('192.168.0.3:5432', 'testdb', 'bigdata_user', 'bigdata_user')
SETTINGS materialized_postgresql_tables_list_with_schema = 1,
materialized_postgresql_allow_automatic_update = 1,  (parameters added after the first failed attempt)
materialized_postgresql_schema='public',
materialized_postgresql_max_block_size=4096,   (parameters added after the first failed attempt)
materialized_postgresql_tables_list ='crypto_deposit,crypto_withdraw';
```

- trace log
```
2023.05.06 05:54:58.908227 [ 37 ] {} <Debug> TCP-Session: de682465-6a96-4aea-8d1f-6862a02bbba0 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2023.05.06 05:54:58.908419 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Debug> executeQuery: (from 127.0.0.1:34658) CREATE DATABASE test_copy ENGINE = MaterializedPostgreSQL('192.168.0.3:5432', 'testdb', 'bigdata_user', 'bigdata_user') SETTINGS materialized_postgresql_tables_list_with_schema = 1, materialized_postgresql_allow_automatic_update = 1, materialized_postgresql_schema='public', materialized_postgresql_max_block_size=4096, materialized_postgresql_tables_list ='crypto_deposit,crypto_withdraw';
2023.05.06 05:54:58.908460 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Trace> ContextAccess (default): Access granted: CREATE DATABASE ON test_copy.*
2023.05.06 05:54:58.908472 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Trace> ContextAccess (default): Access granted: POSTGRES ON *.*
2023.05.06 05:54:58.910860 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Information> DatabaseMaterializedPostgreSQL (test_copy): Metadata processed, database test_copy has 0 tables and 0 dictionaries in total.
2023.05.06 05:54:58.910875 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Information> TablesLoader: Parsed metadata of 0 tables in 1 databases in 5.3627e-05 sec
2023.05.06 05:54:58.910887 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Information> TablesLoader: Loading 0 tables with 0 dependency level
2023.05.06 05:54:58.910895 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Information> DatabaseMaterializedPostgreSQL (test_copy): Starting up tables.
2023.05.06 05:54:58.910969 [ 37 ] {c4145813-f552-4f44-b046-25019ee33213} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2023.05.06 05:54:58.911024 [ 37 ] {} <Debug> TCPHandler: Processed in 0.002851022 sec.
2023.05.06 05:54:58.921041 [ 97 ] {} <Debug> PostgreSQLConnection: New connection to 192.168.0.3:5432
2023.05.06 05:54:58.922535 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Publication exists: false, is attach: false
2023.05.06 05:54:58.922642 [ 97 ] {} <Trace> DatabaseMaterializedPostgreSQL (test_copy): Loaded 2 tables. Starting synchronization
2023.05.06 05:54:58.930749 [ 97 ] {} <Debug> PostgreSQLConnection: New connection to 192.168.0.3:5432
2023.05.06 05:54:58.938795 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Created publication test_copy_ch_publication with tables list: "public"."crypto_deposit","public"."crypto_withdraw"
2023.05.06 05:54:58.940002 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Starting tables sync load
2023.05.06 05:54:58.955942 [ 97 ] {} <Trace> PostgreSQLReplicationHandler: Created replication slot: test_copy_ch_replication_slot, start lsn: 8E9/4018D50, snapshot: 0000003A-0006EF7C-1
2023.05.06 05:54:58.963992 [ 97 ] {} <Debug> PostgreSQLConnection: New connection to 192.168.0.3:5432
2023.05.06 05:54:58.964897 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Loading PostgreSQL table testdb."public"."crypto_withdraw"
2023.05.06 05:54:58.968183 [ 97 ] {} <Debug> StorageMaterializedPostgreSQL(testdb.crypto_withdraw): Creating clickhouse table for postgresql table test_copy.crypto_withdraw
2023.05.06 05:54:58.970978 [ 97 ] {} <Debug> test_copy.crypto_withdraw (9e8a2b28-ab47-4bcd-9d88-fd686177ea67): Loading data parts
2023.05.06 05:54:58.971070 [ 97 ] {} <Debug> test_copy.crypto_withdraw (9e8a2b28-ab47-4bcd-9d88-fd686177ea67): There are no data parts
2023.05.06 05:54:58.975018 [ 97 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 28.75 GiB.
2023.05.06 05:54:58.975503 [ 97 ] {} <Trace> MergedBlockOutputStream: filled checksums all_1_1_0 (state Temporary)
2023.05.06 05:54:58.975894 [ 97 ] {} <Trace> test_copy.crypto_withdraw (9e8a2b28-ab47-4bcd-9d88-fd686177ea67): Renaming temporary part tmp_insert_all_1_1_0 to all_1_1_0.
2023.05.06 05:54:58.976105 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Loaded table test_copy.crypto_withdraw (uuid: 9e8a2b28-ab47-4bcd-9d88-fd686177ea67)
2023.05.06 05:54:58.977485 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Loading PostgreSQL table testdb."public"."crypto_deposit"
2023.05.06 05:54:58.979051 [ 97 ] {} <Debug> StorageMaterializedPostgreSQL(testdb.crypto_deposit): Creating clickhouse table for postgresql table test_copy.crypto_deposit
2023.05.06 05:54:58.981695 [ 97 ] {} <Debug> test_copy.crypto_deposit (4c7512d1-3462-40a7-9b58-be592ccaa1b3): Loading data parts
2023.05.06 05:54:58.981778 [ 97 ] {} <Debug> test_copy.crypto_deposit (4c7512d1-3462-40a7-9b58-be592ccaa1b3): There are no data parts
2023.05.06 05:54:58.987095 [ 97 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 28.75 GiB.
2023.05.06 05:54:58.987479 [ 97 ] {} <Trace> MergedBlockOutputStream: filled checksums all_1_1_0 (state Temporary)
2023.05.06 05:54:58.987814 [ 97 ] {} <Trace> test_copy.crypto_deposit (4c7512d1-3462-40a7-9b58-be592ccaa1b3): Renaming temporary part tmp_insert_all_1_1_0 to all_1_1_0.
2023.05.06 05:54:58.988017 [ 97 ] {} <Debug> PostgreSQLReplicationHandler: Loaded table test_copy.crypto_deposit (uuid: 4c7512d1-3462-40a7-9b58-be592ccaa1b3)
2023.05.06 05:54:58.989699 [ 97 ] {} <Trace> PostgreSQLReplicaConsumer(testdb): Advanced LSN up to: 9796887612752
2023.05.06 05:54:58.989713 [ 97 ] {} <Trace> PostgreSQLReplicaConsumer(testdb): Starting replication. LSN: 9796887612752 (last: 9796887612752)
2023.05.06 05:54:58.989778 [ 97 ] {} <Trace> StorageMaterializedPostgreSQL: New buffer for table test_copy.crypto_withdraw (9e8a2b28-ab47-4bcd-9d88-fd686177ea67), number of attributes: 21, number if columns: 23, structure: id Int64 Int64(size = 1), org_id Int64 Int64(size = 1), user_id Int64 Int64(size = 1), account_id Int64 Int64(size = 1), currency_id Int32 Int32(size = 1), chain_id Int32 Int32(size = 1), amount Decimal(38, 18) Decimal128(size = 1), source_account_id Int64 Int64(size = 1), source_address String String(size = 1), source_tag Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), destination_address String String(size = 1), destination_tag Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), confirmations Int16 Int16(size = 1), ip String String(size = 1), fee Decimal(38, 18) Decimal128(size = 1), state Int16 Int16(size = 1), reason Nullable(Int16) Nullable(size = 1, Int16(size = 1), UInt8(size = 1)), txid Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), workflow_id Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), create_time Int64 Int64(size = 1), update_time Int64 Int64(size = 1), _sign Int8 Int8(size = 1), _version UInt64 UInt64(size = 1)
2023.05.06 05:54:58.989837 [ 97 ] {} <Trace> StorageMaterializedPostgreSQL: New buffer for table test_copy.crypto_deposit (4c7512d1-3462-40a7-9b58-be592ccaa1b3), number of attributes: 20, number if columns: 22, structure: id Int64 Int64(size = 1), org_id Int64 Int64(size = 1), user_id Int64 Int64(size = 1), chain_id Int32 Int32(size = 1), currency_id Int32 Int32(size = 1), account_id Int64 Int64(size = 1), amount Decimal(38, 18) Decimal128(size = 1), source_address String String(size = 1), source_tag Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), destination_address String String(size = 1), destination_tag Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), confirmations Int32 Int32(size = 1), state Int16 Int16(size = 1), reason Nullable(Int16) Nullable(size = 1, Int16(size = 1), UInt8(size = 1)), txid String String(size = 1), workflow_id Nullable(String) Nullable(size = 1, String(size = 1), UInt8(size = 1)), received_time Int64 Int64(size = 1), confirm_time Int64 Int64(size = 1), create_time Int64 Int64(size = 1), update_time Int64 Int64(size = 1), _sign Int8 Int8(size = 1), _version UInt64 UInt64(size = 1)
2023.05.06 05:54:58.991448 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:54:58.991466 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 2000 ms
2023.05.06 05:54:58.997824 [ 203 ] {} <Debug> PostgreSQLConnection: New connection to 192.168.0.3:5432
2023.05.06 05:54:59.992903 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:54:59.992928 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 4000 ms
2023.05.06 05:55:01.998634 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:55:01.998658 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 8000 ms
2023.05.06 05:55:04.295287 [ 86 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 2 entries to flush up to offset 10
2023.05.06 05:55:04.296784 [ 86 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 28.75 GiB.
2023.05.06 05:55:04.297501 [ 86 ] {} <Trace> MergedBlockOutputStream: filled checksums 202305_4_4_0 (state Temporary)
2023.05.06 05:55:04.298141 [ 86 ] {} <Trace> system.query_log (ac1d472a-1c9c-4e98-b017-391477676f6c): Renaming temporary part tmp_insert_202305_4_4_0 to 202305_295879_295879_0.
2023.05.06 05:55:04.298567 [ 86 ] {} <Trace> SystemLog (system.query_log): Flushed system log up to offset 10
2023.05.06 05:55:06.003961 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:55:06.003989 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:55:11.928997 [ 101 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:55:11.929605 [ 101 ] {} <Debug> DNSResolver: Updated DNS cache
2023.05.06 05:55:14.009144 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:55:14.009171 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:55:26.519972 [ 150 ] {} <Debug> system.query_log (ac1d472a-1c9c-4e98-b017-391477676f6c) (MergerMutator): Selected 5 parts from 202305_295867_295875_2 to 202305_295879_295879_0
2023.05.06 05:55:26.520011 [ 150 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 28.75 GiB.
2023.05.06 05:55:26.520130 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTask::PrepareStage: Merging 5 parts: from 202305_295867_295875_2 to 202305_295879_295879_0 into Compact
2023.05.06 05:55:26.520298 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2023.05.06 05:55:26.520409 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202305_295867_295875_2, total 38 rows starting from the beginning of the part
2023.05.06 05:55:26.520764 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202305_295876_295876_0, total 4 rows starting from the beginning of the part
2023.05.06 05:55:26.521053 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202305_295877_295877_0, total 2 rows starting from the beginning of the part
2023.05.06 05:55:26.521362 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202305_295878_295878_0, total 2 rows starting from the beginning of the part
2023.05.06 05:55:26.521662 [ 43 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202305_295879_295879_0, total 2 rows starting from the beginning of the part
2023.05.06 05:55:26.524335 [ 57 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 48 rows, containing 68 columns (68 merged, 0 gathered) in 0.004253746 sec., 11284.171645415594 rows/sec., 16.35 MiB/sec.
2023.05.06 05:55:26.524787 [ 54 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Trace> MergedBlockOutputStream: filled checksums 202305_295867_295879_3 (state Temporary)
2023.05.06 05:55:26.525538 [ 54 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Trace> system.query_log (ac1d472a-1c9c-4e98-b017-391477676f6c): Renaming temporary part tmp_merge_202305_295867_295879_3 to 202305_295867_295879_3.
2023.05.06 05:55:26.525673 [ 54 ] {ac1d472a-1c9c-4e98-b017-391477676f6c::202305_295867_295879_3} <Trace> system.query_log (ac1d472a-1c9c-4e98-b017-391477676f6c) (MergerMutator): Merged 5 parts: from 202305_295867_295875_2 to 202305_295879_295879_0
2023.05.06 05:55:26.525816 [ 54 ] {} <Debug> MemoryTracker: Peak memory usage Mutate/Merge: 4.11 MiB.
2023.05.06 05:55:26.929689 [ 194 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:55:26.930406 [ 194 ] {} <Debug> DNSResolver: Updated DNS cache
2023.05.06 05:55:30.031215 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:55:30.031241 [ 214 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:55:41.930491 [ 125 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:55:41.931193 [ 125 ] {} <Debug> DNSResolver: Updated DNS cache
2023.05.06 05:55:46.055659 [ 208 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:55:46.055687 [ 208 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:55:56.931284 [ 142 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:55:56.931978 [ 142 ] {} <Debug> DNSResolver: Updated DNS cache
2023.05.06 05:56:02.068241 [ 156 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:56:02.068272 [ 156 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:56:11.932070 [ 192 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:56:11.932753 [ 192 ] {} <Debug> DNSResolver: Updated DNS cache
2023.05.06 05:56:12.000292 [ 219 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2023.05.06 05:56:18.082928 [ 156 ] {} <Debug> PostgreSQLConnection: New connection to 192.168.0.3:5432
2023.05.06 05:56:18.082949 [ 156 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:56:18.082959 [ 156 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:56:26.932842 [ 146 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:56:26.933515 [ 146 ] {} <Debug> DNSResolver: Updated DNS cache
2023.05.06 05:56:34.095699 [ 135 ] {} <Debug> PostgreSQLReplicationHandler: checking for skipped tables: 0
2023.05.06 05:56:34.095726 [ 135 ] {} <Debug> PostgreSQLReplicationHandler: Scheduling replication thread: after 16000 ms
2023.05.06 05:56:41.933601 [ 198 ] {} <Debug> DNSResolver: Updating DNS cache
2023.05.06 05:56:41.934383 [ 198 ] {} <Debug> DNSResolver: Updated DNS cache
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect synchronisation after error occurred during sync of memory buffer to tables. Closes https://github.com/ClickHouse/ClickHouse/issues/49586.

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit 383fc06761f81bee735ec22692a2d506ca78c01e with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49698/383fc06761f81bee735ec22692a2d506ca78c01e/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by leeson1995** [comment]
@alesapin @KochetovNicolai  pls cc~

**Comment by alexey-milovidov** [comment]
Tests have failed.

File: src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp [hunk 1]
```diff
@@ -587,10 +589,17 @@ void MaterializedPostgreSQLConsumer::syncTables()
...
             }
         }
-        catch (...)
+        catch (DB::Exception & e)
         {
-            tryLogCurrentException(__PRETTY_FUNCTION__);
+            if (e.code() == ErrorCodes::TOO_MANY_PARTS)
+            {
+                /// Retry this buffer later.
+                storage_data.buffer.columns = result_rows.mutateColumns();
```
Comment (tavplubix) [inline src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:597]: Should we retry some other errors, for example, `MEMORY_LIMIT_EXCEEDED`?

**Review by tavplubix — APPROVED** [review]

File: src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp (hunk 1 above)
Comment (tavplubix) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:597]: > it will be anyway retried, just on a different level

So what's the difference between these levels and why should we retry `TOO_MANY_PARTS` on this level?

Comment (kssenii) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:597]: in this loop we sync changes for several tables, they all lie in range (last_commited_lsn, final_commit_lsn], each change corresponds to some number in this range, so we could successfully sync changes for one table with a change with bigger LSN, but failed to sync a change with lower LSN, so we cannot commit only successful changes as the LSNs are mixed between different tables. As LSN is always the same for each change and is equal to version column of ReplacingMergeTree table, then double insertion of the same record will be deduplicated. But here for too many parts I just wanted to avoid this extra work as error is retriable easily and can happen often.

Comment (kssenii) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:597]: ah no, this was a mistake, because of this `if`, other errors will not be retried now 🥺

Comment (kssenii) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:597]: https://github.com/ClickHouse/ClickHouse/pull/52381
yes, it was incorrect to add this check only for `too_many_parts` the buffer will be cleared for other failures and we will just get empty columns on next retry, while actually there was an error. I was mistaken because forgot about these lines: https://github.com/ClickHouse/ClickHouse/pull/49698/files#diff-99ffe321e146d9061ab12679d2ef9316b5349dcb87b372d1be3efc888f4722b8R754-R757
- here we will make a commit for final lsn...
