### PR TITLE
Fix Keeper snapshot size in `mntr`

### LINKED ISSUE #50314: Keeper metric `latest_snapshot_size` is always 0
```
# echo mntr | nc localhost 2181
...
zk_latest_snapshot_size 0
...
```

```
# ls -la /var/lib/clickhouse/coordination/snapshots/
-rw-rw---- 1 clickhouse clickhouse 60111 May 24 06:20 snapshot_291756.bin.zstd
-rw-rw---- 1 clickhouse clickhouse 60275 May 25 18:40 snapshot_304698.bin.zstd
-rw-rw---- 1 clickhouse clickhouse 60182 May 26 16:44 snapshot_307234.bin.zstd
```
**Describe what's wrong**

latest_snapshot_size is always returned as 0 although snapshots are happening

**Does it reproduce on recent release?**

Yes

**Expected behavior**

I expected it to return the uncompressed size of the latest snapshot

**Additional context**

This metric is populated [from `latest_snapshot_buf` variable](https://github.com/ClickHouse/ClickHouse/blob/6b7e2a00411a0eb556c447bde13e8e2217eacb20/src/Coordination/KeeperStateMachine.cpp#L708-L714). It seems like the bug got introduced as part of https://github.com/ClickHouse/ClickHouse/pull/34584

cc @alesapin @antonio2368

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Keeper fix: return correct value for `zk_latest_snapshot_size` in `mntr` command 

Fix https://github.com/ClickHouse/ClickHouse/issues/50314

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: Integration Tests
- [ ]  Exclude: Stateless tests
- [ ]  Exclude: Stateful tests
- [ ]  Exclude: Performance tests
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with Aarch64
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 9d30a7f056ea68cc2a11974bcecf93da95bbc753 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64784/9d30a7f056ea68cc2a11974bcecf93da95bbc753/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Coordination/KeeperStateMachine.cpp [hunk 1]
```diff
@@ -862,12 +862,16 @@ uint64_t KeeperStateMachine::getKeyArenaSize() const
...
 {
     std::lock_guard lock(snapshots_lock);
-    if (latest_snapshot_buf)
-        return latest_snapshot_buf->size();
-    return 0;
+    if (latest_snapshot_info.disk == nullptr)
+        return 0;
+
+    if (!latest_snapshot_info.size.has_value())
+        latest_snapshot_info.size = latest_snapshot_info.disk->getFileSize(latest_snapshot_info.path);
```
Comment (davenger) [inline src/Coordination/KeeperStateMachine.cpp:872]: This call to `getFileSize()` will be done under `snapshots_lock`, and it could occasionally slow down others who grab this lock.
No sure if this a big deal. WDYT?

Comment (antonio2368) [reply src/Coordination/KeeperStateMachine.cpp:872]: Yeah, I wouldn't say it's a big deal because the lock is taken only for reading/writing/applying snapshot which are all much heavier operations than fetching size.
Also they are not done that often + the size is cached.

Comment (antonio2368) [reply src/Coordination/KeeperStateMachine.cpp:872]: But I can minimize it by storing `latest_snapshot_info` inside a `std::shared_ptr` and making size `atomic`.
It's okay if we return a size for a snapshot that become old 1ms before.

Comment (antonio2368) [reply src/Coordination/KeeperStateMachine.cpp]: okay this escalated a bit, turned it mini refactor...

**Review by davenger — APPROVED** [review]
