### PR TITLE
Fix segfault in `OpenSSLInitializer`

### LINKED ISSUE #79092: Segmentation fault with `curl https://clickhouse.com/ | sh` on Amazon Linux 2023
We're using `curl https://clickhouse.com/ | sh` to generate documentation from system tables. The script that does this started failing recently during Vercel builds. Vercel is [using Amazon Linux 2023](https://vercel.com/docs/builds/build-image).

Steps to reproduce:

```
docker run --rm -it amazonlinux:2023.2.20231011.0 sh

sh-5.2# curl https://clickhouse.com/ | sh
sh-5.2# ./clickhouse local
Decompressing the binary....
Segmentation fault
```

### Operating system

amazonlinux:2023.2.20231011.0

### CMake version

-

### Ninja version

-

### Compiler name and version

-

### Full cmake and/or ninja output

-

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix segfault in `OpenSSLInitializer`. Closes https://github.com/ClickHouse/ClickHouse/issues/79092

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: programs/keeper/keeper_main.cpp [hunk 1]
```diff
@@ -154,6 +154,7 @@ __attribute__((constructor(0))) void init_je_malloc_message()
 #endif
 
 /// OpenSSL early initialization.
+/// Must be ran after EnvironmentChecks.cpp, as OpenSSL uses SSSE3.
```
Comment (rschu1ze) [inline programs/keeper/keeper_main.cpp:157]: @thevar1able

The comment seems a bit confusing to me.

1. We better reference "202" and "the pre-main initialization in EnvironmentChecks" in l. 157
2. More importantly, is there evidence that OpenSSL _requires_ SSE3? (perhaps some SSE3 instructions are used in the assembly files that are included by contrib/openssl-cmake/CMakeLists.txt). Asking because the "amd_compat" build in CI ([example](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79097&sha=latest&name_0=PR&name_1=Build+%28amd_compat%29)) builds with `-DNO_SSE3_OR_HIGHER=1` (build log) and which _would_ break OpenSSL if it needed SSE3.

File: src/Common/Crypto/OpenSSLInitializer.cpp [hunk 2]
```diff
@@ -34,17 +31,29 @@ void OpenSSLInitializer::initialize()
 #if USE_SSL
     if (ref_count++ == 0)
     {
-        int basic_init = OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, nullptr);
-        if (!basic_init)
-            throw Exception(ErrorCodes::OPENSSL_ERROR, "Failed to initialize OpenSSL.");
+        /// Loading OpenSSL config only if it is set explicitly.
+        ///
+        /// 'legacy' provider may be disabled in system config,
```
Comment (rschu1ze) [inline src/Common/Crypto/OpenSSLInitializer.cpp:36]: Two questions:

- `Server::main` has this code

```cpp
if (config().has("opensslconf"))
{
    std::string opensslconf_path = config().getString("opensslconf");
    setenv("OPENSSL_CONF", opensslconf_path.c_str(), true); /// NOLINT
}
else
{
    const String config_path = config().getString("config-file", "config.xml");
    const auto config_dir = std::filesystem::path{config_path}.replace_filename("openssl.conf");
    setenv("OPENSSL_CONF", config_dir.c_str(), true); /// NOLINT
}
```

but since we are now initializing OpenSSL before `main`, the modified `OPENSSL_CONF` takes no effect (as far as I see).

- What is the point of supporting the system-wide OpenSSL config file at all? It seems like another source of subtle runtime problems and I don't know of any other external config file which ClickHouse respects besides its own config files.

Comment (thevar1able) [reply src/Common/Crypto/OpenSSLInitializer.cpp:36]: https://github.com/ClickHouse/ClickHouse/pull/79132
