### PR TITLE
Prepare the introduction of more keeper faults

### LINKED ISSUE #50465: [23.4.2.11] [Keeper] LOGICAL_ERROR: There is no failed OpResult
Report: https://s3.amazonaws.com/clickhouse-test-reports/50441/459ac548ea37eaa14a3f2971af155857f7bf6759/upgrade_check__debug_.html

Exception:
```
2023.06.02 00:15:52.216849 [ 5109 ] {dc4ffe2e-5381-4f54-9dd8-fdcbc4a8fed8} <Error> executeQuery: Code: 49. DB::Exception: There is no failed OpResult. (LOGICAL_ERROR) (version 23.4.2.11 (official build)) (from [::1]:48098) (comment: 01154_move_partition_long.sh) (in query: INSERT INTO dst_2 SELECT * FROM generateRandom('p UInt64, k UInt64, v UInt64') LIMIT 16), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/lib/debug/usr/bin/clickhouse.debug
1. DB::Exception::Exception<char const (&) [28], void>(int, char const (&) [28]) @ 0x8df6536 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./src/Common/ZooKeeper/ZooKeeper.cpp:0: zkutil::getFailedOpIndex(Coordination::Error, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x152c5f66 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./src/Common/ZooKeeper/ZooKeeper.cpp:1196: zkutil::KeeperMultiException::KeeperMultiException(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x152c6246 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/./src/Common/ZooKeeper/ZooKeeper.cpp:1214: zkutil::KeeperMultiException::check(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x152bafd2 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./src/Storages/MergeTree/EphemeralLockInZooKeeper.cpp:86: std::optional<DB::EphemeralLockInZooKeeper> DB::createEphemeralLockInZooKeeper<String>(String const&, String const&, std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, String const&) @ 0x1477be8d in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: std::optional<DB::EphemeralLockInZooKeeper> DB::StorageReplicatedMergeTree::allocateBlockNumber<String>(String const&, std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, String const&, String const&) const @ 0x143581f4 in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::shared_ptr<DB::IMergeTreeDataPart>&, String const&, unsigned long, bool)::'lambda'()::operator()() const @ 0x14b27284 in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:815: DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::shared_ptr<DB::IMergeTreeDataPart>&, String const&, unsigned long, bool) @ 0x14b1a648 in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/./contrib/llvm-project/libcxx/include/vector:434: DB::ReplicatedMergeTreeSinkImpl<false>::finishDelayedChunk(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) @ 0x14b1719e in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/./contrib/llvm-project/libcxx/include/vector:951: DB::ReplicatedMergeTreeSinkImpl<false>::consume(DB::Chunk) @ 0x14b1521f in /usr/lib/debug/usr/bin/clickhouse.debug
11. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::SinkToStorage::onConsume(DB::Chunk) @ 0x150123e2 in /usr/lib/debug/usr/bin/clickhouse.debug
12. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x14f46fcb in /usr/lib/debug/usr/bin/clickhouse.debug
13. ./build_docker/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x14f46d19 in /usr/lib/debug/usr/bin/clickhouse.debug
14. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:818: DB::ExceptionKeepingTransform::work() @ 0x14f465ff in /usr/lib/debug/usr/bin/clickhouse.debug
15. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x14d3aa6a in /usr/lib/debug/usr/bin/clickhouse.debug
16. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14d3073b in /usr/lib/debug/usr/bin/clickhouse.debug
17. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14d2fab6 in /usr/lib/debug/usr/bin/clickhouse.debug
18. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: DB::PipelineExecutor::execute(unsigned long) @ 0x14d2f751 in /usr/lib/debug/usr/bin/clickhouse.debug
19. ./build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x14d2e5ad in /usr/lib/debug/usr/bin/clickhouse.debug
20. ./build_docker/./base/base/../base/wide_integer_impl.h:789: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe48c2a1 in /usr/lib/debug/usr/bin/clickhouse.debug
21. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0xe491b21 in /usr/lib/debug/usr/bin/clickhouse.debug
22. ? @ 0x7f3d24c28609 in ?
23. clone @ 0x7f3d24b4d133 in ?
```

The query and the table seem pretty simple:
```

CREATE TABLE dst_2 (`p` UInt64, `k` UInt64, `v` UInt64) ENGINE = ReplicatedMergeTree('/test/01154_move_partition_long_test_7/dst', '2') PARTITION BY p % 10 ORDER BY k SETTINGS index_granularity = 11948, min_bytes_for_wide_part = 28744506, ratio_of_defaults_for_sparse_serialization = 1., merge_max_block_size = 992, prefer_fetch_merged_part_size_threshold = 10235505529, vertical_merge_algorithm_min_rows_to_activate = 1000000, vertical_merge_algorithm_min_columns_to_activate = 1, min_merge_bytes_to_use_direct_io = 10737418240, index_granularity_bytes = 10063407, allow_vertical_merges_from_compact_to_wide_parts = false, marks_compress_block_size = 96959, primary_key_compress_block_size = 14835;

INSERT INTO dst_2 SELECT * FROM generateRandom('p UInt64, k UInt64, v UInt64') LIMIT 16;
```

Note that **this is the "old" version of the upgrade check**, `23.4.2.11`, not master.

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Prepares the introduction of more keeper faults

Longer details:
* Refactors ZooKeeperWithFaultInjection to prepare to introduce it in more places:
  * Implementation goes to the .cpp file.
  * Adds a bunch of new methods with faults to be used in replicated merge tree
  * Temporarily maintains the tracking of ephemeral nodes created with a faulty keeper. In the future, once "everything" handles retries this should removed in favor of force a session reload, which is what happens in a real environment.
  * Introduces faults in async functions too via promises.

* It reworks how part_committed_locally_but_zookeeper (old) / resolve_uncertain_commit_stage (less old) worked so that we can keep retrying in case the ZK session failed when committing. Before the uncertain stage could only be resolved if ZK failed after write (and in that case everything was good) but it wouldn't recover it data wasn't written to keeper. Now it recovers both cases.

* Fixes an issue found related with ephemeral nodes cleaning up in backups fault and changes the name (`handleEphemeralNodeExistence` ->  `deleteEphemeralNodeIfContentMatches`) to avoid further confusions. I included in this PR since changing the name and introducing faults is what leads to noticing the problem and enables fixing them only once (and not twice, one in a different PR and another time in the refactor)

AFAICS. Closes https://github.com/ClickHouse/ClickHouse/issues/50465 as it removed the special handling of tryMulti() responses

cc @devcrafter

### CODE REVIEW

**Comment by Algunenano** [comment]
It seems I will need to bring more commits from https://github.com/ClickHouse/ClickHouse/pull/56389. As the tests run in parallel, the moment you enable more faults (some ops had some disabled, and the refactor got rid of that) they all clash with each other more frequently so you see the lack of proper recovery more often, e.g. the `part_committed_locally_but_zookeeper` thingy.

**Comment by Algunenano** [comment]
* Fixed broken debug build. I'm not sure why it compiled in other builds when I used `ch_assert` vs `chassert`
* The commit "fixing" 00509_extended_storage_definition_syntax_zookeeper wasn't necessary as, in the end, it wasn't unrelated. OPTIMIZE failed because there were inserts on the fly because of dangling ephemeral nodes due to keeper faults. After fixing that it does not fail

**Comment by Algunenano** [comment]
Errors:
* `AST fuzzer (asan)` -> Related. Bug in ZooKeeperWithFaultInjection::exists logger.
* `Integration tests (asan) [1/4]` -> PG leak -> https://github.com/ClickHouse/ClickHouse/issues/56627
* `Integration tests (release) [2/4] ` -> test_backup_restore_on_cluster/test_concurrency.py::test_create_or_drop_tables_during_backup[Replicated-ReplicatedMergeTree]. Looks related to retries or extra faults added, having a look
* `Stateless tests (debug) [2/5]` -> `01280_ttl_where_group_by`. Flaky
* `Stateless tests (debug, s3 storage) [3/6]` ->  `01280_ttl_where_group_by` again
* `Stateless tests (release, analyzer)`. `01287_max_execution_speed` and `01600_parts_states_metrics_long` which are flaky with the analyzer.
* `Stateless tests (tsan, s3 storage) [2/5] ` ->  `01280_ttl_where_group_by` again

**Comment by Algunenano** [comment]
Failures:
* `Stateless tests (debug, s3 storage) [3/6]` -> 01280_ttl_where_group_by. Unrelated
* `Stress test (debug)` -> https://github.com/ClickHouse/ClickHouse/issues/57127. Unrelated

File: src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp [hunk 1]
```diff
@@ -952,32 +923,47 @@ std::pair<std::vector<String>, bool> ReplicatedMergeTreeSinkImpl<async_insert>::
...
-
-            /// if all retries will be exhausted by accessing zookeeper on fresh retry -> we'll add committed part to queue in the action
-            /// here lambda capture part name, it's ok since we'll not generate new one for this insert,
-            /// see comments around 'part_committed_locally_but_zookeeper' flag
-            retries_ctl.actionAfterLastFailedRetry(
-                [&my_storage = storage, part_name = part->name]
-                {
-                    my_storage.enqueuePartForCheck(part_name, MAX_AGE_OF_LOCAL_PART_THAT_WASNT_ADDED_TO_ZOOKEEPER);
-                });
+            LOG_TRACE(
```
Comment (Algunenano) [inline src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:926]: @tavplubix Do you mind having a look at this changes, specially checking that `rename_part_to_temporary();` in the case where the data wasn't written to keeper (to retry) is safe? Thanks!

File: src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp [hunk 2]
```diff
@@ -952,32 +923,47 @@ std::pair<std::vector<String>, bool> ReplicatedMergeTreeSinkImpl<async_insert>::
...
+            /// `/blocks/`, and it can not be inserted again.
+            new_retry_controller.actionAfterLastFailedRetry([&]
+            {
+                transaction.commit();
+                storage.enqueuePartForCheck(part->name, MAX_AGE_OF_LOCAL_PART_THAT_WASNT_ADDED_TO_ZOOKEEPER);
+                throw Exception(ErrorCodes::UNKNOWN_STATUS_OF_INSERT,
+                        "Unknown status of part {} (Reason: {}). Data was written locally but we don't know the status in keeper. It will be verified in ~{} seconds.",
+                        part->name, multi_code, MAX_AGE_OF_LOCAL_PART_THAT_WASNT_ADDED_TO_ZOOKEEPER);
+            });
+            new_retry_controller.requestUnconditionalRetry();
```
Comment (devcrafter) [inline src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:942]: Probably comment why calling `requestUnconditionalRetry ()` is necessary? afaiu, to guarantee that `actionAfterLastFailedRetry` is called in case no retries left

**Review by devcrafter — APPROVED** [review]
LGTM with comments

File: src/Common/ZooKeeper/ZooKeeper.h [hunk 3]
```diff
@@ -194,6 +195,8 @@ struct MultiReadResponses
 /// Methods with names not starting at try- raise KeeperException on any error.
 class ZooKeeper
 {
+    friend class DB::ZooKeeperWithFaultInjection;
```
[the remark this answers is not in the document]
Comment (Algunenano) [reply src/Common/ZooKeeper/ZooKeeper.h:198]: :+1:

File: src/Backups/RestoreCoordinationRemote.cpp [hunk 4]
```diff
@@ -43,11 +44,9 @@ RestoreCoordinationRemote::RestoreCoordinationRemote(
             if (my_is_internal)
             {
                 String alive_node_path = my_zookeeper_path + "/stage/alive|" + my_current_host;
+                zk->deleteEphemeralNodeIfContentMatches(alive_node_path, "");
```
[the remark this answers is not in the document]
Comment (Algunenano) [reply src/Backups/RestoreCoordinationRemote.cpp]: I would rather not hide it for now. In some places the ephemeral node is created as part of a transaction and in other places we might not want to automatically recreate the ephemeral node. It also introduces extra round trips that are not necessary if you are not recovering from an error (one to check, one to remove or waiting for a long time for it to be removed).

I'll refactor it a bit

**Comment by Algunenano** [comment]
Working on rebasing the PR after the fix for zero-copy locks

**Comment by Algunenano** [comment]
Reimplemented ZK retries to `tryMulti` both for before and after failures on top of @CheSema 's recent changes. So far so good. I had to recover `rollbackPartsToTemporaryState`

**Comment by Algunenano** [comment]
Everything green except `Integration tests (asan) [4/4]` which failed because of `test_postgresql_replica_database_engine_1/test.py::test_many_concurrent_queries` which I don't see how it can be related.

Marking it as ready again after the last changes. cc @devcrafter in case you want to review the latest changes before merging

**Comment by Algunenano** [comment]
Need to rebase on top of [57764](https://github.com/ClickHouse/ClickHouse/pull/57764) which fixes some of the same problems found and fixed in this PR

**Comment by tavplubix** [comment]
> test_postgresql_replica_database_engine_1/test.py::test_many_concurrent_queries which I don't see how it can be related.

Even if it's not related, let's not ignore it. We can start with using [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X3Bvc3RncmVzcWxfcmVwbGljYV9kYXRhYmFzZV9lbmdpbmVfMScgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK) to find when it started to fail. And it helps to find the reason quite easily: https://github.com/ClickHouse/ClickHouse/pull/57568#issuecomment-1854518149

**Comment by Algunenano** [comment]
The new failures appeared with the merge with master and they look related. Need to investigate more, but I took master's way of improving ZK retries on backup coordination instead of the one in this PR so most likely the problem is there.

**Comment by Algunenano** [comment]
Failures:
* `Integration tests (asan) [3/4]` -> test_storage_hdfs/test.py::test_write_table. Fixed in https://github.com/ClickHouse/ClickHouse/pull/55370
* `Integration tests (asan) [4/4] ` -> `test_storage_azure_blob_storage/test_cluster.py::test_unset_skip_unavailable_shards` -> Fixed in https://github.com/ClickHouse/ClickHouse/pull/57895
* `Integration tests (release) [4/4]` -> `test_storage_azure_blob_storage/test_cluster.py::test_unset_skip_unavailable_shards` -> Fixed in https://github.com/ClickHouse/ClickHouse/pull/57895
* `Stateless tests (aarch64) ` -> `00002_log_and_exception_messages_formatting`. I'll have a look in a different PR as it's not related to the changes.

I would love to not have to rebase this again :wink:

**Comment by devcrafter** [comment]
> I would love to not have to rebase this again 😉

It'd be nice to understand what has changed from latest review

**Comment by Algunenano** [comment]
> It'd be nice to understand what has changed from latest review

The last 2 rebases:

* https://github.com/ClickHouse/ClickHouse/pull/56917/commits/9d8d5dfdf63a526510fe4915f85897c68f98df3a + https://github.com/ClickHouse/ClickHouse/pull/56917/commits/923c3b7b32ea70d77e4e54ade201b2464e0f334d -> Reimplemented retries in RMTSink (commit) when the connection to ZK fails on tryMulti(). This had been already implemented but it was discovered that old retries weren't handling zero copy nodes correctly and the function was refactored completely, so retries had to be introduced again.

* Last one -> https://github.com/ClickHouse/ClickHouse/pull/56917/commits/3200933144fb3ab4e0d8ec5ce78d0ff9e5d528a6 -> Removes any changes vs master under `src/Backups` as the ones I had introduced have been also introduced in different PRs in the meantime.

File: src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp [hunk 5]
```diff
@@ -914,14 +892,60 @@ std::pair<std::vector<String>, bool> ReplicatedMergeTreeSinkImpl<async_insert>::
...
+                transaction.commit();
+                storage.enqueuePartForCheck(part->name, MAX_AGE_OF_LOCAL_PART_THAT_WASNT_ADDED_TO_ZOOKEEPER);
+                throw Exception(ErrorCodes::UNKNOWN_STATUS_OF_INSERT,
+                        "Unknown status of part {} (Reason: {}). Data was written locally but we don't know the status in keeper. "
+                        "The status will be verified automatically in ~{} seconds (the part will be kept if present in keeper or dropped if not)",
+                        part->name, multi_code, MAX_AGE_OF_LOCAL_PART_THAT_WASNT_ADDED_TO_ZOOKEEPER);
+            });
+
+            /// Independently of how many retries we had left we want to do at least one check of this inner retry
+            /// at least once so a) we try to verify at least once if metadata was written and b) we set the proper
```
Comment (devcrafter) [inline src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:914]: It's too many "at least once"

File: src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp [hunk 6]
```diff
@@ -1019,22 +1038,6 @@ std::pair<std::vector<String>, bool> ReplicatedMergeTreeSinkImpl<async_insert>::
     {
         zookeeper->setKeeper(storage.getZooKeeper());
```
Comment (devcrafter) [inline src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:1039]: I'm not sure about moving this block to `lock and commit` stage. Probably, you could explain

**Review by devcrafter — APPROVED** [review]
@Algunenano My comments are mostly minor, except probably https://github.com/ClickHouse/ClickHouse/pull/56917#discussion_r1428261563. But if you think it's fine, please feel free to fix comments in follow-up PR

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 7]
```diff
@@ -6339,6 +6358,24 @@ MergeTreeData::Transaction::Transaction(MergeTreeData & data_, MergeTreeTransact
         data.transactions_enabled.store(true);
 }
 
+void MergeTreeData::Transaction::rollbackPartsToTemporaryState()
+{
+    if (!isEmpty())
+    {
+        WriteBufferFromOwnString buf;
```
[the remark this answers is not in the document]
Comment (Algunenano) [reply src/Storages/MergeTree/MergeTreeData.cpp:6365]: I recovered the code by reverting partially the commit that removed it and kept it as-is for simplicity, but it could be improved / iterated in the future.

File: src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp (hunk 6 above)
Comment (Algunenano) [reply src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:1039]: I moved it because the table being in read only only matters when we are going to add a new part/commit to ZK. If we only have checks left (for example in `resolve_duplicate_stage`) it doesn't make sense to not continue verifying because the table is stopped, as we can still return a proper response to the client.

A similar thing will happen for quorum for example (but it's not in this PR to keep in more concise).  It's ok to check for quorum if the write succeeded but the table was set in read only after that.

**Comment by Algunenano** [comment]
Failures:
* AST fuzzer (ubsan) -> https://github.com/ClickHouse/ClickHouse/issues/57705
* Stateless tests (debug) [3/5]
  * `01508_partition_pruning_long`. It seems the queries just took too long and the test reached the 10m limit before finishing them all.
  * `01414_mutations_and_errors_zookeeper`: The mutation was cancelled internally (due to large sleep) before it was killed externally, so the log message is missing.
* `Upgrade check (debug)`: I see a OOM Kill in stress.log and I see a logical error in gdb.log but I can't see if they are related or what binary and data was being run. This test is really hard to debug/understand in general (https://github.com/ClickHouse/ClickHouse/issues/57981)
