### PR TITLE
Fix signed integer overflow for nth_value() window function

### LINKED ISSUE #28001: Window functions: signed integer overflow.
https://clickhouse-test-reports.s3.yandex.net/0/624cb43f7f85b576dc2831e20623a5cf5b878792/fuzzer_ubsan/report.html

```
SELECT max(intDiv(1048575, NULL)) OVER (ORDER BY mod(number, 1024) DESC NULLS LAST RANGE BETWEEN 1 PRECEDING AND CURRENT ROW), 0, number, nth_value(toNullable(number), -9223372036854775808) OVER w AS firstValue, nth_value(toNullable(number), NULL) OVER w AS thridValue FROM numbers(1) WINDOW w AS (ORDER BY number ASC)
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix signed integer overflow for nth_value() window function

Detailed description / Documentation draft:
CI report [1]:

    ../src/Processors/Transforms/WindowTransform.cpp:1699:54: runtime error: signed integer overflow: -9223372036854775808 - 1 cannot be represented in type 'long' Received signal -3 Received signal Unknown signal (-3)

In query:

```sql

    SELECT
        number,
        nth_value(number, 2147483648) OVER w,
        anyOrNull(number) OVER (ORDER BY -2147483648 - intDiv(number, 1024) DESC NULLS FIRST, number DESC ROWS BETWEEN 65535 FOLLOWING AND UNBOUNDED FOLLOWING),
        nth_value(number, 65537) OVER w AS firstValue,
        nth_value(number, -9223372036854775808) OVER w AS secondValue,
        nth_value(number, 1048576) OVER w AS thirdValue
    FROM numbers(1)
    WINDOW w AS (ORDER BY number DESC)
    ORDER BY number DESC

```

  [1]: https://clickhouse-test-reports.s3.yandex.net/28532/7623af5513e12aa8dfa1bee963caffe00185c31a/fuzzer_ubsan/report.html#fail1

Cc: @akuzm 
Fixes: #28001

### CODE REVIEW

File: src/Processors/Transforms/WindowTransform.cpp [hunk 1]
```diff
@@ -1696,22 +1696,16 @@ struct WindowFunctionNthValue final : public WindowFunction
 
         int64_t offset = (*current_block.input_columns[
                 workspace.argument_column_indices[1]])[
-            transform->current_row.row].get<Int64>() - 1;
+            transform->current_row.row].get<Int64>();
 
-        if (offset < 0)
+        if (offset > INT_MAX || offset <= 0)
```
Comment (alexey-milovidov) [inline src/Processors/Transforms/WindowTransform.cpp:1701]: Why INT_MAX while we have int64?

Comment (alexey-milovidov) [reply src/Processors/Transforms/WindowTransform.cpp:1701]: We still can have more than 2bn rows in a block.

Comment (azat) [reply src/Processors/Transforms/WindowTransform.cpp:1701]: Yes, initially this is not my code, but I guess it was done as some sort of soft limit.
Maybe @akuzm or @ryzuo can comment on this?
In the mean time I will increase it.

Comment (azat) [reply src/Processors/Transforms/WindowTransform.cpp:1701]: Also lagInFrame/leadInFrame has the same limits, after d9ad06bd6d3

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
>Stress test (address) — Killed by signal (in clickhouse-server.log)

#28604
