### PR TITLE
Fix data race in ProfileEvents::Counters::setParent().

### LINKED ISSUE #60376: Data-race in ProfileEvents for parent
CI: https://s3.amazonaws.com/clickhouse-test-reports/60196/0cb6f205d7fa8a4b790879eae8d0ce4ae03cabc4/stress_test__tsan_.html

```
WARNING: ThreadSanitizer: data race (pid=3172)
  Write of size 8 at 0x7b50002c0c70 by thread T1119 (mutexes: write M0):
    #0 ProfileEvents::Counters::setParent(ProfileEvents::Counters*) build_docker/./src/Common/ProfileEvents.h:119:20 (clickhouse+0x187defa2) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #1 DB::ProcessList::insert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::IAST const*, std::__1::shared_ptr<DB::Context>, unsigned long) build_docker/./src/Interpreters/ProcessList.cpp:207:48 (clickhouse+0x187defa2)
    #2 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/./src/Interpreters/executeQuery.cpp:893:60 (clickhouse+0x18be68ef) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #3 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&)>) build_docker/./src/Interpreters/executeQuery.cpp:1427:34 (clickhouse+0x18bedebb) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #4 DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) build_docker/./src/Interpreters/DDLWorker.cpp:497:9 (clickhouse+0x17736fb3) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #5 DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) build_docker/./src/Interpreters/DDLWorker.cpp:661:17 (clickhouse+0x17734934) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #6 DB::DatabaseReplicatedDDLWorker::tryEnqueueAndExecuteEntry(DB::DDLLogEntry&, std::__1::shared_ptr<DB::Context const>) build_docker/./src/Databases/DatabaseReplicatedWorker.cpp:286:5 (clickhouse+0x1730e841) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #7 DB::DatabaseReplicated::tryEnqueueReplicatedDDL(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::QueryFlags) build_docker/./src/Databases/DatabaseReplicated.cpp:784:36 (clickhouse+0x172dfe1a) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #8 DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1292:26 (clickhouse+0x18187d4c) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #9 DB::InterpreterCreateQuery::execute() build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1787:16 (clickhouse+0x18195048) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #10 DB::DatabaseWithOwnTablesBase::createTableRestoredFromBackup(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IRestoreCoordination>, unsigned long) build_docker/./src/Databases/DatabasesCommon.cpp:391:17 (clickhouse+0x17319d72) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #11 DB::DatabaseReplicated::createTableRestoredFromBackup(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IRestoreCoordination>, unsigned long) build_docker/./src/Databases/DatabaseReplicated.cpp:1603:25 (clickhouse+0x172f9195) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #12 DB::RestorerFromBackup::createTable(DB::QualifiedTableName const&) build_docker/./src/Backups/RestorerFromBackup.cpp:746:19 (clickhouse+0x16b9aefa) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #13 DB::RestorerFromBackup::createTables() build_docker/./src/Backups/RestorerFromBackup.cpp:708:9 (clickhouse+0x16b916c6) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #14 DB::RestorerFromBackup::run(DB::RestorerFromBackup::Mode) build_docker/./src/Backups/RestorerFromBackup.cpp:132:5 (clickhouse+0x16b8c45a) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #15 DB::BackupsWorker::doRestore(std::__1::shared_ptr<DB::ASTBackupQuery> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::BackupInfo const&, DB::RestoreSettings, std::__1::shared_ptr<DB::IRestoreCoordination>, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::ThreadGroup>, bool) build_docker/./src/Backups/BackupsWorker.cpp:1015:47 (clickhouse+0x16b0d9f5) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #16 DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0::operator()() const build_docker/./src/Backups/BackupsWorker.cpp:871:21 (clickhouse+0x16b1327d) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #17 decltype(std::declval<DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0&>(DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x16b1327d)
    #18 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0&>(DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x16b1327d)
    #19 std::__1::__function::__default_alloc_func<DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0, void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x16b1327d)
    #20 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::BackupsWorker::startRestoring(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>)::$_0, void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x16b1327d)
    #21 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0xf68fe0e) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #22 std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0xf68fe0e)
    #23 ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) build_docker/./src/Common/ThreadPool.cpp:455:13 (clickhouse+0xf68fe0e)
    #24 void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:217:73 (clickhouse+0xf6941dc) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #25 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0xf6941dc)
    #26 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0xf6941dc)
    #27 decltype(auto) std::__1::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0xf6941dc)
    #28 ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:223:13 (clickhouse+0xf6941dc)
    #29 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0xf694141) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #30 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0xf694141)
    #31 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0xf694141)
    #32 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0xf694141)
    #33 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0xf68c0ee) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #34 std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0xf68c0ee)
    #35 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:455:13 (clickhouse+0xf68c0ee)
    #36 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:217:73 (clickhouse+0xf691fb1) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #37 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0xf691fb1)
    #38 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0xf691fb1)
    #39 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0xf691fb1)

  Previous read of size 8 at 0x7b50002c0c70 by thread T770:
    #0 ProfileEvents::Counters::increment(StrongTypedef<unsigned long, ProfileEvents::EventTag>, unsigned long) build_docker/./src/Common/ProfileEvents.cpp:768:28 (clickhouse+0xf5d6138) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #1 ProfileEvents::increment(StrongTypedef<unsigned long, ProfileEvents::EventTag>, unsigned long) build_docker/./src/Common/ProfileEvents.cpp:751:43 (clickhouse+0xf5d6138)
    #2 DB::ContextSharedMutex::lockSharedImpl() build_docker/./src/Interpreters/Context.cpp:775:5 (clickhouse+0x1765cb55) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #3 DB::SharedMutexHelper<DB::ContextSharedMutex, DB::SharedMutex>::lock_shared() build_docker/./src/Common/SharedMutexHelper.h:65:39 (clickhouse+0x17685f0c) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #4 DB::SharedLockGuard<DB::ContextSharedMutex>::SharedLockGuard(DB::ContextSharedMutex&) build_docker/./src/Common/SharedLockGuard.h:19:98 (clickhouse+0x17685f0c)
    #5 DB::Context::getQueryLog() const build_docker/./src/Interpreters/Context.cpp:3724:21 (clickhouse+0x17685f0c)
    #6 DB::logQueryFinish(DB::QueryLogElement&, std::__1::shared_ptr<DB::Context> const&, std::__1::shared_ptr<DB::IAST> const&, DB::QueryPipeline const&, bool, std::__1::shared_ptr<DB::OpenTelemetry::SpanHolder>, DB::QueryCache::Usage, bool) build_docker/./src/Interpreters/executeQuery.cpp:419:43 (clickhouse+0x18be0f43) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #7 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:1254:17 (clickhouse+0x18bf34e3) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #8 decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x18bf34e3)
    #9 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x18bf34e3)
    #10 std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x18bf34e3)
    #11 void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_1, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x18bf34e3)
    #12 std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x16fcccdb) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #13 std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x16fcccdb)
    #14 DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9 (clickhouse+0x16fcccdb)
    #15 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&)>) build_docker/./src/Interpreters/executeQuery.cpp:1548:13 (clickhouse+0x18bee812) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #16 DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) build_docker/./src/Interpreters/DDLWorker.cpp:497:9 (clickhouse+0x17736fb3) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #17 DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) build_docker/./src/Interpreters/DDLWorker.cpp:661:17 (clickhouse+0x17734934) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #18 DB::DDLWorker::scheduleTasks(bool) build_docker/./src/Interpreters/DDLWorker.cpp:439:13 (clickhouse+0x177322c5) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #19 DB::DDLWorker::runMainThread() build_docker/./src/Interpreters/DDLWorker.cpp:1147:13 (clickhouse+0x1772b188) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #20 decltype(*std::declval<DB::DDLWorker*&>().*std::declval<void (DB::DDLWorker::*&)()>()()) std::__1::__invoke[abi:v15000]<void (DB::DDLWorker::*&)(), DB::DDLWorker*&, void>(void (DB::DDLWorker::*&)(), DB::DDLWorker*&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:359:23 (clickhouse+0x17745abf) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #21 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<void (DB::DDLWorker::*&)(), std::__1::tuple<DB::DDLWorker*>&, 0ul>(void (DB::DDLWorker::*&)(), std::__1::tuple<DB::DDLWorker*>&, std::__1::__tuple_indices<0ul>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0x17745abf)
    #22 decltype(auto) std::__1::apply[abi:v15000]<void (DB::DDLWorker::*&)(), std::__1::tuple<DB::DDLWorker*>&>(void (DB::DDLWorker::*&)(), std::__1::tuple<DB::DDLWorker*>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0x17745abf)
    #23 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:223:13 (clickhouse+0x17745abf)
    #24 decltype(std::declval<void (DB::DDLWorker::*)()>()(std::declval<DB::DDLWorker*>())) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()&>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x17745a01) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #25 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x17745a01)
    #26 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x17745a01)
    #27 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x17745a01)
    #28 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0xf68c0ee) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #29 std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0xf68c0ee)
    #30 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:455:13 (clickhouse+0xf68c0ee)
    #31 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:217:73 (clickhouse+0xf691fb1) (BuildId: 6595c03b432cc92007e0f4124a57364d4571d69d)
    #32 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0xf691fb1)
    #33 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0xf691fb1)
    #34 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0xf691fb1)

```

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix data race in `ProfileEvents::Counters::setParent()`. This PR fixes https://github.com/ClickHouse/ClickHouse/issues/60376

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit d78c3d4cba9986bbbec1029a74f3468ba8a79b28 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/72518/d78c3d4cba9986bbbec1029a74f3468ba8a79b28/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e3e6905638251e93a249322801002bdc9c132b22/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by evillique — APPROVED** [review]

File: src/Common/ProfileEvents.h [hunk 1]
```diff
@@ -60,7 +60,7 @@ namespace ProfileEvents
         Counter * counters = nullptr;
         std::unique_ptr<Counter[]> counters_holder;
         /// Used to propagate increments
-        Counters * parent = nullptr;
```
Comment (vitlibar) [inline src/Common/ProfileEvents.h:63]: This `parent` field is assigned in [ProcessList::insert()](https://github.com/ClickHouse/ClickHouse/blob/e3e6905638251e93a249322801002bdc9c132b22/src/Interpreters/ProcessList.cpp#L251-L252) similar to how it is done for `MemoryTracker`, and the `parent` field in `MemoryTracker` is atomic, so I think we can do the `parent` field atomic for `Counters` too.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by vitlibar** [comment]
I think it's better to backport this PR - it's rather small and fixes a data race which happens quite often in our release builds.
