### PR TITLE
Fix GROUP BY (const CTE) in distributed queries.

### LINKED ISSUE #64498: THERE_IS_NO_COLUMN for CTE constant and clusterAllReplicas
Minimized example:
```
WITH (
        SELECT dummy AS x
        FROM system.one
    ) AS y
SELECT
    y,
    min(dummy)
FROM clusterAllReplicas(default, system.one)
GROUP BY y
SETTINGS allow_experimental_analyzer = 1

Query id: e89f3c36-8eba-4362-8398-c786998cac5f


Elapsed: 0.048 sec.

Received exception from server (version 24.5.1):
Code: 8. DB::Exception: Received from k7t4owurbs.eu-west-1.aws.clickhouse-staging.com:9440. DB::Exception: Cannot find column `_CAST(0_Nullable(UInt8), 'Nullable(UInt8)'_String)` in source stream, there are only columns: [min(__table1.dummy)]. (THERE_IS_NO_COLUMN)

clickhouse-cloud :) WITH (select dummy as x from system.one) AS y select y, min(dummy) from clusterAllReplicas(default, system.one) GROUP BY y SETTINGS allow_experimental_analyzer=0

WITH (
        SELECT dummy AS x
        FROM system.one
    ) AS y
SELECT
    y,
    min(dummy)
FROM clusterAllReplicas(default, system.one)
GROUP BY y
SETTINGS allow_experimental_analyzer = 0

Query id: a81dc4f4-c443-4c4a-a7c4-0599c2a1751a

   ┌─y─┬─min(dummy)─┐
1. │ 0 │          0 │
   └───┴────────────┘

1 row in set. Elapsed: 0.007 sec.


SELECT version()

Query id: 08eca7f4-b121-405b-a7ef-7b0e09457657

   ┌─version()────┐
1. │ 24.5.1.22560 │
   └──────────────┘
```

cc: @Algunenano

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix an error `Cannot find column` in distributed queries with constant CTE in the `GROUP BY` key.

Closes: https://github.com/ClickHouse/ClickHouse/issues/64498

### CODE REVIEW

File: src/Planner/PlannerExpressionAnalysis.cpp [hunk 1]
```diff
@@ -64,6 +64,10 @@ bool isDeterministicConstant(const ConstantNode & root)
         const auto * node = nodes.top();
         nodes.pop();
 
+        if (node->getNodeType() == QueryTreeNodeType::QUERY)
+            /// Allow scalar subqueries and IN; we send them to all the shards.
```
Comment (Algunenano) [inline src/Planner/PlannerExpressionAnalysis.cpp:68]: Sorry for my lack of knowledge about the context: Does this mean that we send the result of the scalar subquery / result of IN, or that we send the subquery themselves?

And another thing, but it depends on the previous response: would it make sense to change the name of the function (if we send the subquery itself)? At this point I only know it has to do with distributed queries because I've seen other related changes so maybe it could be more clear or we could add some comments to the function itself to explain what is used for? Thanks!

**Review by Algunenano — APPROVED** [review]

File: src/Planner/PlannerExpressionAnalysis.cpp (hunk 1 above)
Comment (novikd) [reply src/Planner/PlannerExpressionAnalysis.cpp:68]: I also don't understand this change. It sounds strange that we treat scalar subquery as a **deterministic** constant.

Comment (KochetovNicolai) [reply src/Planner/PlannerExpressionAnalysis.cpp:68]: This function is used to check whether the constant values is the same for all the replicas/shards. If the constant was calculated from the result of scalar subquery, or the constant was calculated as `const_expr IN set`, it would be the same : we send the result of scalar subqueries in the protocol.

Please, opt for the better function name.
