### PR TITLE
Optimize RowBinary input format

### LINKED ISSUE #63805: Slow `RowBinary` format
**How to reproduce**

```
$ head -c 1000000000 /dev/urandom > data1.bin

$ clickhouse-local --time --structure 'x UInt8' --query "INSERT INTO FUNCTION null('x UInt8') FORMAT RowBinary" < data1.bin
0.000
29.361
```

```
  30,11%  QueryPullPipeEx  clickhouse         [.] DB::RowInputFormatWithNamesAndTypes::readRow                                                                                                                                         ▒
  11,92%  QueryPullPipeEx  clickhouse         [.] DB::IRowInputFormat::read                                                                                                                                                            ▒
   9,40%  QueryPullPipeEx  clickhouse         [.] DB::FormatWithNamesAndTypesReader::allowVariableNumberOfColumns                                                                                                                      ▒
   8,28%  QueryPullPipeEx  clickhouse         [.] DB::SerializationNumber<char8_t>::deserializeBinary                                                                                                                                  ◆
   7,38%  QueryPullPipeEx  clickhouse         [.] DB::FormatWithNamesAndTypesReader::checkForSuffix                                                                                                                                    ▒
   6,15%  QueryPullPipeEx  clickhouse         [.] DB::BinaryFormatReader<false>::readField                                                                                                                                             ▒
   5,11%  QueryPullPipeEx  clickhouse         [.] DB::ReadBuffer::readStrict                                                                                                                                                           ▒
   4,84%  QueryPullPipeEx  clickhouse         [.] DB::ColumnVector<char8_t>::size                                                                                                                                                      ▒
   3,76%  QueryPullPipeEx  clickhouse         [.] DB::ColumnMapping::insertDefaultsForNotSeenColumns                                                                                                                                   ▒
   3,75%  QueryPullPipeEx  clickhouse         [.] DB::FormatWithNamesAndTypesReader::skipRowBetweenDelimiter                                                                                                                           ▒
   2,17%  QueryPullPipeEx  clickhouse         [.] DB::FormatWithNamesAndTypesReader::skipRowEndDelimiter                                                                                                                               ▒
   1,55%  QueryPullPipeEx  clickhouse         [.] DB::FormatWithNamesAndTypesReader::skipRowStartDelimiter                                                                                                                             ▒
   1,42%  QueryPullPipeEx  clickhouse         [.] DB::RowInputFormatWithDiagnosticInfo::updateDiagnosticInfo                                                                                                                           ▒
   0,80%  QueryPullPipeEx  clickhouse         [.] memcpy                                                                                                                                                                               ▒
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimize RowBinary input format. Closes https://github.com/ClickHouse/ClickHouse/issues/63805

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by Avogar** [comment]
Data:
```
$ head -c 1000000000 /dev/urandom > data1.bin
```

Before:
```
$ clickhouse local --time --structure 'x UInt8' --query "INSERT INTO FUNCTION null('x UInt8') FORMAT RowBinary" < data1.bin
0.000
35.727
```

Now:
```
clickhouse local --time --structure 'x UInt8' --query "INSERT INTO FUNCTION null('x UInt8') FORMAT RowBinary" < data1.bin
0.000
16.991
```

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit deccae2d8ac306954a2349bd930baa344e99aa09 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65059/deccae2d8ac306954a2349bd930baa344e99aa09/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Processors/Formats/Impl/BinaryRowInputFormat.cpp [hunk 1]
```diff
@@ -23,10 +23,44 @@ BinaryRowInputFormat<with_defaults>::BinaryRowInputFormat(ReadBuffer & in_, cons
         with_names_,
         with_types_,
         format_settings_,
-        std::make_unique<BinaryFormatReader<with_defaults>>(in_, format_settings_))
+        std::make_unique<BinaryFormatReader<with_defaults>>(in_, format_settings_)), binary_reader(assert_cast<BinaryFormatReader<with_defaults> *>(format_reader.get()))
 {
 }
 
+template <bool with_defaults>
+bool BinaryRowInputFormat<with_defaults>::readRow(DB::MutableColumns & columns, DB::RowReadExtension & ext)
```
Comment (Avogar) [inline src/Processors/Formats/Impl/BinaryRowInputFormat.cpp:31]: `RowInputFormatWithNamesAndTypes::readRow` makes some virtual calls and checks that are unnecessary for `RowBinary` format.

**Review by alexey-milovidov — APPROVED** [review]
