### PR TITLE
Fixes for temporary files settings and metrics

### LINKED ISSUE #90174: Flaky 03514_grace_hash_join_logical_error (Failed to reserve ... bytes for temporary file)
Test `03514_grace_hash_join_logical_error` fails when randomizaiton for `temporary_files_buffer_size` is enabled (#88917)

Failures look like this:

<details><summary>Details</summary>
<p>

```
2025-11-03 06:46:01 [6e0b3c01543c] 2025.11.03 12:46:00.994236 [ 123327 ] {d7b1de4f-4595-44e2-8585-19ba562ed7f6} <Error> executeQuery: Code: 243. DB::Exception: Failed to reserve 1762 bytes for temporary file: reason cannot evict enough space (non-releasable count: 382, non-releasable size: 429495302, releasable count: 1, releasable size: 213, background download elements: 0), Regular hold 23.00 MiB, can release 213.00 B; Ephemeral hold 386.60 MiB, can release 0.00 B; (segment info: File segment: [0, 1053675], key: 8a406be3d7b44f6a1e80bbdf973b4085, state: PARTIALLY_DOWNLOADED_NO_CONTINUATION, downloaded size: 1051914, reserved size: 1051914, downloader id: d7b1de4f-4595-44e2-8585-19ba562ed7f6:30602, current write offset: 1051914, caller id: d7b1de4f-4595-44e2-8585-19ba562ed7f6:30602, kind: Ephemeral, unbound: 1): While executing FillingRightJoinSide. (NOT_ENOUGH_SPACE) (version 25.11.1.986) (from [::1]:47784) (comment: 03514_grace_hash_join_logical_error.sql-test_3lcfofld) (query 4, line 8) (in query: SELECT `__table1`.`A` AS `A`, `__table1`.`B` AS `B`, `__table1`.`S` AS `S`, `__table2`.`A` AS `b.A`, `__table2`.`B` AS `b.B`, `__table2`.`S` AS `b.S` FROM `test_3lcfofld`.`A` AS `__table1` ALL INNER JOIN `test_3lcfofld`.`A` AS `__table2` ON `__table1`.`A` = `__table2`.`A` LIMIT _CAST(1, 'UInt64')), Stack trace (when copying this message, always include the lines below):
2025-11-03 06:46:01 
2025-11-03 06:46:01 0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001ed0b472
2025-11-03 06:46:01 1. ./ci/tmp/build/./src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001066585e
2025-11-03 06:46:01 2. DB::Exception::Exception(String&&, int, String, bool) @ 0x00000000094e174e
2025-11-03 06:46:01 3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000094e1340
2025-11-03 06:46:01 4. ./src/Common/Exception.h:141: DB::Exception::Exception<unsigned long&, char const*, String&, String&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<char const*>::type, std::type_identity<String&>::type, std::type_identity<String&>::type, std::type_identity<String>::type>, unsigned long&, char const*&&, String&, String&, String&&) @ 0x00000000166dd779
2025-11-03 06:46:01 5. ./ci/tmp/build/./src/Interpreters/Cache/WriteBufferToFileSegment.cpp:93: DB::WriteBufferToFileSegment::nextImpl() @ 0x00000000166dcb2f
2025-11-03 06:46:01 6. DB::WriteBuffer::next() @ 0x00000000094edd5e
2025-11-03 06:46:01 7. ./src/IO/WriteBuffer.h:85: DB::WriteBuffer::write(char const*, unsigned long) @ 0x00000000107657c0
2025-11-03 06:46:01 8. ./ci/tmp/build/./src/Compression/CompressedWriteBuffer.cpp:60: DB::CompressedWriteBuffer::nextImpl() @ 0x000000001a80266a
2025-11-03 06:46:01 9. DB::WriteBuffer::next() @ 0x00000000094edd5e
2025-11-03 06:46:01 10. ./ci/tmp/build/./src/Interpreters/TemporaryDataOnDisk.cpp:404: DB::TemporaryDataBuffer::nextImpl() @ 0x00000000164f5b67
2025-11-03 06:46:01 11. DB::WriteBuffer::next() @ 0x00000000094edd5e
2025-11-03 06:46:01 12. ./src/IO/WriteBuffer.h:85: DB::WriteBuffer::write(char const*, unsigned long) @ 0x00000000107657c0
2025-11-03 06:46:01 13. ./ci/tmp/build/./src/DataTypes/Serializations/SerializationString.cpp:139: DB::SerializationString::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const @ 0x00000000152d2dce
2025-11-03 06:46:01 14. ./ci/tmp/build/./src/DataTypes/Serializations/ISerialization.cpp:212: DB::ISerialization::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0x00000000151cb534
2025-11-03 06:46:01 15. ./ci/tmp/build/./src/Formats/NativeWriter.cpp:101: DB::NativeWriter::writeData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, std::optional<DB::FormatSettings> const&, unsigned long, unsigned long, unsigned long) @ 0x0000000019bd372a
2025-11-03 06:46:01 16. ./ci/tmp/build/./src/Formats/NativeWriter.cpp:219: DB::NativeWriter::write(DB::Block const&) @ 0x0000000019bd4482
2025-11-03 06:46:01 17. ./ci/tmp/build/./src/Interpreters/GraceHashJoin.cpp:186: DB::GraceHashJoin::FileBucket::addBlockImpl(DB::Block const&, DB::TemporaryBlockStreamHolder&, std::unique_lock<std::mutex>&) @ 0x0000000016186990
2025-11-03 06:46:01 18. ./ci/tmp/build/./src/Interpreters/GraceHashJoin.cpp:150: void DB::(anonymous namespace)::flushBlocksToBuckets<(DB::JoinTableSide)1>(std::vector<DB::Block, std::allocator<DB::Block>>&, std::vector<std::shared_ptr<DB::GraceHashJoin::FileBucket>, std::allocator<std::shared_ptr<DB::GraceHashJoin::FileBucket>>> const&, unsigned long) @ 0x0000000016183c58
2025-11-03 06:46:01 19. ./ci/tmp/build/./src/Interpreters/GraceHashJoin.cpp:695: DB::GraceHashJoin::addBlockToJoinImpl(DB::Block) @ 0x000000001617e126
2025-11-03 06:46:01 20. ./ci/tmp/build/./src/Interpreters/GraceHashJoin.cpp:304: DB::GraceHashJoin::addBlockToJoin(DB::Block const&, bool) @ 0x000000001617dd04
2025-11-03 06:46:01 21. ./ci/tmp/build/./src/Processors/Transforms/JoiningTransform.cpp:318: DB::FillingRightJoinSideTransform::work() @ 0x0000000019ea7165
2025-11-03 06:46:01 22. ./ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x0000000019c20559
2025-11-03 06:46:01 23. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x0000000019c13dd2
2025-11-03 06:46:01 24. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000019c1339a
2025-11-03 06:46:01 25. ./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000019c12feb
2025-11-03 06:46:01 26. ./ci/tmp/build/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000019c2811c
2025-11-03 06:46:01 27. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000107a5660
2025-11-03 06:46:01 28. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000107ab47b
2025-11-03 06:46:01 29. ? @ 0x0000000000094ac3
2025-11-03 06:46:01 30. ? @ 0x00000000001268c0
2025-11-03 06:46:01 
```

</p>
</details>

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
External aggregation/sorting/join now respect query setting temporary_files_codec in all contexts. Fixed missing profile events for grace hash join

Close https://github.com/ClickHouse/ClickHouse/issues/90174 (no issue there, we just cannot randomize `temporary_files_buffer_size` a lot, since in test run with s3 setup we have only 1G tmp storage and with small buffer size we flush a lot)

### CODE REVIEW

File: tests/clickhouse-test [hunk 1]
```diff
@@ -1174,6 +1174,7 @@ class SettingsRandomizer:
         "input_format_parquet_use_native_reader_v3": lambda: min(1, random.randint(0, 5)),
         "enable_lazy_columns_replication": lambda: random.randint(0, 1),
         "allow_special_serialization_kinds_in_output_formats": lambda: random.randint(0, 1),
+        "temporary_files_buffer_size": lambda: random.randint(1 * 1024 * 1024, 2 * 1024 * 1024),
```
Comment (vdimir) [inline tests/clickhouse-test]:
```suggestion
        # "temporary_files_buffer_size": lambda: random.randint(1 * 1024 * 1024, 2 * 1024 * 1024),
```

File: tests/queries/0_stateless/03772_temporary_files_codec.sql [hunk 2]
```diff
@@ -0,0 +1,76 @@
+SET max_bytes_before_external_sort = '1M';
```
Comment (vdimir) [inline tests/queries/0_stateless/03772_temporary_files_codec.sql:2]:
```suggestion
-- Tags: long
SET max_bytes_before_external_sort = '1M';
```

**Comment by vdimir** [comment]
> [Integration tests (amd_binary, 4/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92388&sha=efea52302ec55392c6826e549c27e3cc878a1401&name_0=PR&name_1=Integration%20tests%20%28amd_binary%2C%204%2F5%29) 		failure 		
> 	test_merge_tree_s3/test.py::test_merge_canceled_by_s3_errors[node-broken_s3] 	FAIL 		IGNORED

`#87560`

File: src/Planner/Planner.cpp [hunk 3]
```diff
@@ -585,6 +587,9 @@ Aggregator::Params getAggregatorParams(const PlannerContextPtr & planner_context
             aggregate_description.argument_names.clear();
     }
 
+    auto tmp_data_scope = query_context->getTempDataOnDisk();
+    if (tmp_data_scope)
+        tmp_data_scope = tmp_data_scope->childScope({}, settings[Setting::temporary_files_buffer_size], settings[Setting::temporary_files_codec]);
```
Comment (kssenii) [inline src/Planner/Planner.cpp]:
```suggestion
        tmp_data_scope = tmp_data_scope->childScope(/* metrics */{}, settings[Setting::temporary_files_buffer_size], settings[Setting::temporary_files_codec]);
```

File: tests/clickhouse-test [hunk 4]
```diff
@@ -1174,6 +1174,7 @@ class SettingsRandomizer:
         "input_format_parquet_use_native_reader_v3": lambda: min(1, random.randint(0, 5)),
         "enable_lazy_columns_replication": lambda: random.randint(0, 1),
         "allow_special_serialization_kinds_in_output_formats": lambda: random.randint(0, 1),
+        # "temporary_files_buffer_size": lambda: random.randint(1 * 1024 * 1024, 2 * 1024 * 1024),
```
Comment (kssenii) [inline tests/clickhouse-test]: Why commented?

Comment (vdimir) [reply tests/clickhouse-test]: It turned out that even that range causes issues, so some tests can fail. In fact, for many files, memory consumption can be 2x with a 2MB buffer. Maybe we can use a smaller range.
```suggestion
        "temporary_files_buffer_size": lambda: random.randint(800 * 1024, 1200 * 1024),
```

**Review by kssenii — APPROVED** [review]
