### PR TITLE
Fix no shared id during drop for the fourth time

### LINKED ISSUE #45224: Stress: DROP TABLE may hang with zero-copy replication brecause of `table_shared_id`
https://s3.amazonaws.com/clickhouse-test-reports/45212/68f747ed3239e2c13653f1996e08176c4a7488db/stress_test__msan_.html

```
Found hung queries in processlist:
[
    {
        "is_initial_query": 1,
        "user": "default",
        "query_id": "d0c27e8b-16cd-4807-bcde-d35f2a5b021a",
        "address": "::1",
        "port": 38398,
        "initial_user": "default",
        "initial_query_id": "d0c27e8b-16cd-4807-bcde-d35f2a5b021a",
        "initial_address": "::1",
        "initial_port": 38398,
        "interface": 1,
        "os_user": "",
        "client_hostname": "6b025e2eb803",
        "client_name": "ClickHouse",
        "client_revision": "54461",
        "client_version_major": "22",
        "client_version_minor": "13",
        "client_version_patch": "1",
        "http_method": 0,
        "http_user_agent": "",
        "http_referer": "",
        "forwarded_for": "",
        "quota_key": "",
        "distributed_depth": "0",
        "elapsed": 20301.73261,
        "is_cancelled": 0,
        "is_all_data_sent": 0,
        "read_rows": "0",
        "read_bytes": "0",
        "total_rows_approx": "0",
        "written_rows": "0",
        "written_bytes": "0",
        "memory_usage": "0",
        "peak_memory_usage": "0",
        "query": "DROP TABLE IF EXISTS replica_01108_3",
        "thread_ids": [
            "3212"
        ],
        "ProfileEvents": {
            "Query": "1",
            "ReplicaPartialShutdown": "1",
            "ContextLock": "7"
        },
        "Settings": {
            "max_block_size": "19650",
            "max_threads": "36",
            "max_read_buffer_size": "553648",
            "connect_timeout_with_failover_ms": "2000",
            "connect_timeout_with_failover_secure_ms": "3000",
            "idle_connection_timeout": "36000",
            "s3_check_objects_after_upload": "1",
            "stream_like_engine_allow_direct_select": "1",
            "replication_wait_for_inactive_replica_timeout": "30",
            "compile_sort_description": "0",
            "distributed_aggregation_memory_efficient": "0",
            "group_by_use_nulls": "1",
            "input_format_parallel_parsing": "0",
            "min_chunk_bytes_for_parallel_parsing": "8291042",
            "output_format_parallel_formatting": "0",
            "merge_tree_coarse_index_granularity": "18",
            "min_bytes_to_use_direct_io": "572551339",
            "log_queries": "1",
            "insert_quorum_timeout": "60000",
            "fsync_metadata": "0",
            "join_use_nulls": "1",
            "http_send_timeout": "60",
            "http_receive_timeout": "60",
            "opentelemetry_start_trace_probability": "0.1",
            "join_algorithm": "parallel_hash",
            "max_memory_usage": "10000000000",
            "max_memory_usage_for_user": "22091091148",
            "max_untracked_memory": "1048576",
            "memory_profiler_step": "1048576",
            "log_comment": "01108_restart_replicas_rename_deadlock_zookeeper.sh",
            "send_logs_level": "warning",
            "prefer_localhost_replica": "0",
            "aggregation_in_order_max_block_bytes": "18915547",
            "read_in_order_two_level_merge_threshold": "38",
            "database_atomic_wait_for_drop_and_detach_synchronously": "1",
            "local_filesystem_read_method": "pread",
            "remote_filesystem_read_method": "read",
            "remote_filesystem_read_prefetch": "0",
            "async_insert_busy_timeout_ms": "5000",
            "enable_filesystem_cache": "1",
            "enable_filesystem_cache_on_write_operations": "1",
            "load_marks_asynchronously": "1",
            "allow_deprecated_database_ordinary": "1",
            "optimize_distinct_in_order": "0",
            "optimize_sorting_by_input_stream_properties": "0",
            "insert_keeper_max_retries": "20",
            "insert_keeper_fault_injection_probability": "0.01"
        },
        "current_database": "test_1"
    }
]
```

```
    ~/ch/logs  rg -Faz "d0c27e8b-16cd-4807-bcde-d35f2a5b021a" clickhouse-server.stress.log.zst                                                                                                 INT ✘ 
482143:2023.01.12 11:38:24.768902 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Debug> executeQuery: (from [::1]:38398) (comment: 01108_restart_replicas_rename_deadlock_zookeeper.sh) DROP TABLE IF EXISTS replica_01108_3 (stage: Complete)
482144:2023.01.12 11:38:24.769381 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Trace> ContextAccess (default): Access granted: DROP TABLE ON test_1.replica_01108_3
482161:2023.01.12 11:38:24.772732 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Information> test_1.replica_01108_2_tmp (ReplicatedMergeTreeAttachThread): Attach thread finished
482168:2023.01.12 11:38:24.777430 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Trace> test_1.replica_01108_2_tmp (ReplicatedMergeTreeRestartingThread): Restarting thread finished
482170:2023.01.12 11:38:24.777509 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Waiting for threads to finish
482172:2023.01.12 11:38:24.777601 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Threads finished
482175:2023.01.12 11:38:24.777662 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Trace> test_1.replica_01108_2_tmp (PartMovesBetweenShardsOrchestrator): PartMovesBetweenShardsOrchestrator thread finished
482183:2023.01.12 11:38:24.778007 [ 3212 ] {d0c27e8b-16cd-4807-bcde-d35f2a5b021a} <Debug> DatabaseCatalog: Waiting for table d67e1c48-bd8e-4683-a716-72014fb0ce8c to be finally dropped
```

```
    ~/ch/logs  rg -Faz "d67e1c48-bd8e-4683-a716-72014fb0ce8c" clickhouse-server.stress.log.zst | tail -30                                                                                      1|0 ✔ 
2023.01.12 12:12:14.509757 [ 1772 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Got candidate ID d67e1c48-bd8e-4683-a716-72014fb0ce8c, will try to create it in ZooKeeper on path /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id
2023.01.12 12:12:14.511489 [ 1772 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Failed to remove all parts, all count 1, removed 0
2023.01.12 12:12:14.511704 [ 1772 ] {} <Warning> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: got exception removing parts from disk, removing successfully removed parts from memory.
2023.01.12 12:12:14.512398 [ 1772 ] {} <Error> DatabaseCatalog: Cannot drop table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c). Will retry later.: Code: 999. Coordination::Exception: No node, path: /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
2023.01.12 12:12:33.451308 [ 1777 ] {} <Information> DatabaseCatalog: Have 1 tables in drop queue (0 of them are in use), will try drop test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c)
2023.01.12 12:12:33.470613 [ 1777 ] {} <Information> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Removing replica /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/replicas/replica, marking it as lost
2023.01.12 12:12:33.472291 [ 1777 ] {} <Information> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Removing replica /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/replicas/replica does not exist
2023.01.12 12:12:33.472502 [ 1777 ] {} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: waiting for locks.
2023.01.12 12:12:33.472690 [ 1777 ] {} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: removing data parts (count 1) from filesystem.
2023.01.12 12:12:33.472868 [ 1777 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Removing 1 parts from filesystem (serially): Parts: [all_0_0_0]
2023.01.12 12:12:33.473503 [ 1777 ] {} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Part all_0_0_0 local references is zero, will check blobs can be removed in zookeeper
2023.01.12 12:12:33.477077 [ 1777 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Creating shared ID for table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c)
2023.01.12 12:12:33.479304 [ 1777 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Shared ID for table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c) doesn't exist in ZooKeeper on path /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id
2023.01.12 12:12:33.479524 [ 1777 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Got candidate ID d67e1c48-bd8e-4683-a716-72014fb0ce8c, will try to create it in ZooKeeper on path /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id
2023.01.12 12:12:33.481213 [ 1777 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Failed to remove all parts, all count 1, removed 0
2023.01.12 12:12:33.481435 [ 1777 ] {} <Warning> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: got exception removing parts from disk, removing successfully removed parts from memory.
2023.01.12 12:12:33.482161 [ 1777 ] {} <Error> DatabaseCatalog: Cannot drop table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c). Will retry later.: Code: 999. Coordination::Exception: No node, path: /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
2023.01.12 12:12:38.482988 [ 1688 ] {} <Information> DatabaseCatalog: Have 1 tables in drop queue (0 of them are in use), will try drop test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c)
2023.01.12 12:12:38.485834 [ 1688 ] {} <Information> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Removing replica /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/replicas/replica, marking it as lost
2023.01.12 12:12:38.488383 [ 1688 ] {} <Information> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Removing replica /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/replicas/replica does not exist
2023.01.12 12:12:38.488587 [ 1688 ] {} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: waiting for locks.
2023.01.12 12:12:38.488790 [ 1688 ] {} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: removing data parts (count 1) from filesystem.
2023.01.12 12:12:38.488980 [ 1688 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Removing 1 parts from filesystem (serially): Parts: [all_0_0_0]
2023.01.12 12:12:38.489676 [ 1688 ] {} <Trace> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Part all_0_0_0 local references is zero, will check blobs can be removed in zookeeper
2023.01.12 12:12:38.491576 [ 1688 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Creating shared ID for table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c)
2023.01.12 12:12:38.493873 [ 1688 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Shared ID for table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c) doesn't exist in ZooKeeper on path /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id
2023.01.12 12:12:38.494097 [ 1688 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Got candidate ID d67e1c48-bd8e-4683-a716-72014fb0ce8c, will try to create it in ZooKeeper on path /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id
2023.01.12 12:12:38.495666 [ 1688 ] {} <Debug> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): Failed to remove all parts, all count 1, removed 0
2023.01.12 12:12:38.495876 [ 1688 ] {} <Warning> test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c): dropAllData: got exception removing parts from disk, removing successfully removed parts from memory.
2023.01.12 12:12:38.496567 [ 1688 ] {} <Error> DatabaseCatalog: Cannot drop table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c). Will retry later.: Code: 999. Coordination::Exception: No node, path: /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
    ~/ch/logs  rg -A30 -Faz "2023.01.12 12:11:44.426706 [ 1753 ] {} <Error> DatabaseCatalog" clickhouse-server.stress.log.zst                                                                      ✔ 
5327656:2023.01.12 12:11:44.426706 [ 1753 ] {} <Error> DatabaseCatalog: Cannot drop table test_1.replica_01108_3 (d67e1c48-bd8e-4683-a716-72014fb0ce8c). Will retry later.: Code: 999. Coordination::Exception: No node, path: /clickhouse/tables/01108_restart_replicas_rename_deadlock_zookeeper_test_1/replica_01108_1/table_shared_id. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
5327657-
5327658-0. ./build_docker/../contrib/llvm-project/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x5774b4a9 in /usr/bin/clickhouse
5327659-1. ./build_docker/../src/Common/Exception.cpp:0: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x2970edf3 in /usr/bin/clickhouse
5327660-2. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, Coordination::Error, int) @ 0x4cb313ba in /usr/bin/clickhouse
5327661-3. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x4cb32d91 in /usr/bin/clickhouse
5327662-4. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::createTableSharedID() const @ 0x491b9a23 in /usr/bin/clickhouse
5327663-5. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::getTableSharedID() const @ 0x4944ff2e in /usr/bin/clickhouse
5327664-6. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::unlockSharedData(DB::IMergeTreeDataPart const&, std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) const @ 0x4946346b in /usr/bin/clickhouse
5327665-7. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:0: DB::StorageReplicatedMergeTree::unlockSharedData(DB::IMergeTreeDataPart const&) const @ 0x492aa08a in /usr/bin/clickhouse
5327666-8. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:1610: DB::IMergeTreeDataPart::canRemovePart() const @ 0x49dc3dff in /usr/bin/clickhouse
5327667-9. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:1656: DB::CanRemoveDescription std::__1::__function::__policy_invoker<DB::CanRemoveDescription ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::IMergeTreeDataPart::remove()::$_7, DB::CanRemoveDescription ()>>(std::__1::__function::__policy_storage const*) @ 0x49dd59fd in /usr/bin/clickhouse
5327668-10. ./build_docker/../contrib/llvm-project/libcxx/include/optional:285: DB::DataPartStorageOnDisk::remove(std::__1::function<DB::CanRemoveDescription ()>&&, DB::MergeTreeDataPartChecksums const&, std::__1::list<DB::IDataPartStorage::ProjectionChecksums, std::__1::allocator<DB::IDataPartStorage::ProjectionChecksums>>, bool, DB::MergeTreeDataPartState, Poco::Logger*) @ 0x49c75cb6 in /usr/bin/clickhouse
5327669-11. ./build_docker/../contrib/llvm-project/libcxx/include/list:616: DB::IMergeTreeDataPart::remove() @ 0x49d8b2d6 in /usr/bin/clickhouse
5327670-12. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::MergeTreeData::clearPartsFromFilesystemImpl(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*)::$_22::operator()() const @ 0x49fa9971 in /usr/bin/clickhouse
5327671-13. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::MergeTreeData::clearPartsFromFilesystemImpl(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*) @ 0x49fa390e in /usr/bin/clickhouse
5327672-14. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:1951: DB::MergeTreeData::clearPartsFromFilesystem(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>> const&, bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*) @ 0x49fa23bf in /usr/bin/clickhouse
5327673-15. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:0: DB::MergeTreeData::dropAllData() @ 0x49fc14fd in /usr/bin/clickhouse
5327674-16. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:912: DB::StorageReplicatedMergeTree::drop() @ 0x491dacff in /usr/bin/clickhouse
5327675-17. ./build_docker/../src/Interpreters/DatabaseCatalog.cpp:0: DB::DatabaseCatalog::dropTableFinally(DB::DatabaseCatalog::TableMarkedAsDropped const&) @ 0x43c65d31 in /usr/bin/clickhouse
5327676-18. ./build_docker/../src/Interpreters/DatabaseCatalog.cpp:0: DB::DatabaseCatalog::dropTableDataTask() @ 0x43c64af0 in /usr/bin/clickhouse
5327677-19. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:717: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::DatabaseCatalog::loadDatabases()::$_3, void ()>>(std::__1::__function::__policy_storage const*) @ 0x43c7a449 in /usr/bin/clickhouse
5327678-20. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:0: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x42221073 in /usr/bin/clickhouse
5327679-21. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: DB::BackgroundSchedulePool::threadFunction() @ 0x4222b285 in /usr/bin/clickhouse
5327680-22. ./build_docker/../src/Common/ThreadPool.h:197: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x4222d745 in /usr/bin/clickhouse
5327681-23. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x29a70f2d in /usr/bin/clickhouse
5327682-24. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x29a7f0a3 in /usr/bin/clickhouse
5327683-25. ? @ 0x7f326df9e609 in ?
5327684-26. clone @ 0x7f326dec3133 in ?
5327685- (version 22.13.1.1)

```

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes #45224.

### CODE REVIEW

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -7951,6 +7937,10 @@ void StorageReplicatedMergeTree::createTableSharedID() const
             id = zookeeper->get(zookeeper_table_id_path);
             LOG_DEBUG(log, "Shared ID on path {} concurrently created, will set ID {}", zookeeper_table_id_path, id);
         }
+        else if (code == Coordination::Error::ZNONODE) /// table completely dropped, we can choose any id we want
+        {
+            LOG_DEBUG(log, "Table was completely drop, we can use anything as ID (will use {})", id);
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:7942]: Why do we need an id if the table is completely dropped? What are we going to unlock in `unlockSharedDataByID` in this case?

Comment (alesapin) [reply src/Storages/StorageReplicatedMergeTree.cpp:7942]: We will just check that this ID doesn't exist in ZK and assume parts unlocked, but I'm not 100% sure...

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 2]
```diff
@@ -7970,6 +7965,10 @@ void StorageReplicatedMergeTree::createTableSharedID() const
...
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:7970]: Let's return Nil in this case

**Review by tavplubix — APPROVED** [review]

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 3]
```diff
@@ -8111,6 +8111,13 @@ StorageReplicatedMergeTree::unlockSharedData(const IMergeTreeDataPart & part, co
         return std::make_pair(true, NameSet{});
     }
 
+    auto shared_id = getTableSharedID();
+    if (shared_id == toString(UUIDHelpers::Nil))
+    {
+        LOG_TRACE(log, "Part {} blobs can be rem)oved, because table {} comletely dropped", part.name, getStorageID().getNameForLogs());
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:8117]:
```suggestion
        LOG_TRACE(log, "Part {} blobs can be removed, because table {} comletely dropped", part.name, getStorageID().getNameForLogs());
```

**Comment by tavplubix** [comment]
Integration tests (release) [4/4] - looks like https://github.com/ClickHouse/ClickHouse/issues/44862
Stress test (debug) - https://github.com/ClickHouse/ClickHouse/pull/45691
Stress test (ubsan)  - reportLogStats - fixed in https://github.com/ClickHouse/ClickHouse/pull/45527
