### PR TITLE
ColumnVector: re-enable AVX512_VBMI/AVX512_VBMI2 optimized filter and index

### LINKED ISSUE #41745: TargetSpecific::AVX512VBMI::vectorIndexImpl: undefined-behavior + heap-buffer-overflow
heap-buffer-overflow (report https://s3.amazonaws.com/clickhouse-test-reports/41653/cc6776fc5d54a19c49af55219dfcada1e15ac9b9/fuzzer_astfuzzerasan//report.html):
```
=================================================================
==139==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030002ff30f at pc 0x00003073cc30 bp 0x7f5589fb58a0 sp 0x7f5589fb5898
READ of size 1 at 0x6030002ff30f thread T30 (MergeMutate)
    #0 0x3073cc2f in void DB::TargetSpecific::AVX512VBMI::vectorIndexImpl<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&) build_docker/../src/Columns/ColumnVector.h:407:1
    #1 0x307345be in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ColumnVector<char8_t>::indexImpl<char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long) const build_docker/../src/Columns/ColumnVector.h:530:13
    #2 0x305d87c0 in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::selectIndexImpl<DB::ColumnVector<char8_t>>(DB::ColumnVector<char8_t> const&, DB::IColumn const&, unsigned long) build_docker/../src/Columns/ColumnsCommon.h:119:32
    #3 0x305d85ed in DB::ColumnVector<char8_t>::index(DB::IColumn const&, unsigned long) const build_docker/../src/Columns/ColumnVector.cpp:687:12
    #4 0x30474511 in DB::ColumnLowCardinality::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnLowCardinality.cpp:201:53
    #5 0x301c8d00 in DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnArray.cpp:527:15
    #6 0x31a16b73 in DB::MergeTreeDataPartWriterCompact::ColumnsBuffer::add(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&&) build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:376:37
    #7 0x31a16b73 in DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:158:20
    #8 0x31cd8276 in DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:308:13
    #9 0x31cd8276 in DB::MergedBlockOutputStream::write(DB::Block const&) build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:56:5
    #10 0x31807529 in DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() build_docker/../src/Storages/MergeTree/MergeTask.cpp:382:64
    #11 0x31807258 in std::__1::__function::__policy_func<bool ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #12 0x31807258 in std::__1::function<bool ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #13 0x31807258 in DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() build_docker/../src/Storages/MergeTree/MergeTask.cpp:366:9
    #14 0x31812cd6 in DB::MergeTask::execute() build_docker/../src/Storages/MergeTree/MergeTask.cpp:769:29
    #15 0x31f8ee2a in DB::MergePlainMergeTreeTask::executeStep() build_docker/../src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:47:33
    #16 0x3183be67 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:137:42
    #17 0x3183f495 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:259:13
    #18 0xdf3a6df in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #19 0xdf3a6df in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #20 0xdf3a6df in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #21 0xdf4442c in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #22 0xdf4442c in decltype(static_cast<void>(fp)()) std::__1::__invoke_constexpr<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #23 0xdf4442c in decltype(auto) std::__1::__apply_tuple_impl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #24 0xdf4442c in decltype(auto) std::__1::apply<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #25 0xdf4442c in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #26 0xdf4442c in decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #27 0xdf345df in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #28 0xdf345df in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #29 0xdf345df in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #30 0xdf3e0cc in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #31 0xdf3e0cc in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #32 0xdf3e0cc in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #33 0xdf3e0cc in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #34 0x7f56b5a4d608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #35 0x7f56b5972132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x6030002ff30f is located 0 bytes to the right of 31-byte region [0x6030002ff2f0,0x6030002ff30f)
allocated by thread T30 (MergeMutate) here:
    #0 0xdcd412e in malloc (/workspace/clickhouse+0xdcd412e) (BuildId: 8a237203bfc190b0611523cac9422c6feef605df)
    #1 0xde32417 in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:227:27
    #2 0xdee7c8e in Allocator<false, false>::alloc(unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:96:16
    #3 0xdee7c8e in void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc<>(unsigned long) build_docker/../src/Common/PODArray.h:134:65
    #4 0x2cebb297 in DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc_for_num_elements(unsigned long) build_docker/../src/Common/PODArray.h:128:9
    #5 0x2cebb297 in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>::PODArray(unsigned long) build_docker/../src/Common/PODArray.h:344:15
    #6 0x2cebb297 in DB::ColumnVector<char8_t>::ColumnVector(unsigned long) build_docker/../src/Columns/ColumnVector.h:137:45
    #7 0x2cebb297 in COW<DB::IColumn>::mutable_ptr<DB::ColumnVector<char8_t>> COWHelper<DB::ColumnVectorHelper, DB::ColumnVector<char8_t>>::create<unsigned long const&>(unsigned long const&) build_docker/../src/Common/COW.h:284:71
    #8 0x2cebb297 in COW<DB::IColumn>::mutable_ptr<DB::IColumn> DB::ColumnUnique<DB::ColumnString>::uniqueInsertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)::'lambda'(auto)::operator()<char8_t>(auto) const build_docker/../src/Columns/ColumnUnique.h:607:30
    #9 0x2ceb5e59 in DB::ColumnUnique<DB::ColumnString>::uniqueInsertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnUnique.h:616:28
    #10 0x30474492 in DB::ColumnLowCardinality::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnLowCardinality.cpp:200:62
    #11 0x301c8d00 in DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnArray.cpp:527:15
    #12 0x31a16b73 in DB::MergeTreeDataPartWriterCompact::ColumnsBuffer::add(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&&) build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:376:37
    #13 0x31a16b73 in DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:158:20
    #14 0x31cd8276 in DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:308:13
    #15 0x31cd8276 in DB::MergedBlockOutputStream::write(DB::Block const&) build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:56:5
    #16 0x31807529 in DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() build_docker/../src/Storages/MergeTree/MergeTask.cpp:382:64
    #17 0x31807258 in std::__1::__function::__policy_func<bool ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #18 0x31807258 in std::__1::function<bool ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #19 0x31807258 in DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() build_docker/../src/Storages/MergeTree/MergeTask.cpp:366:9
    #20 0x31812cd6 in DB::MergeTask::execute() build_docker/../src/Storages/MergeTree/MergeTask.cpp:769:29
    #21 0x31f8ee2a in DB::MergePlainMergeTreeTask::executeStep() build_docker/../src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:47:33
    #22 0x3183be67 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:137:42
    #23 0x3183f495 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:259:13
    #24 0xdf3a6df in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #25 0xdf3a6df in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #26 0xdf3a6df in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #27 0xdf4442c in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #28 0xdf4442c in decltype(static_cast<void>(fp)()) std::__1::__invoke_constexpr<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #29 0xdf4442c in decltype(auto) std::__1::__apply_tuple_impl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #30 0xdf4442c in decltype(auto) std::__1::apply<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #31 0xdf4442c in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #32 0xdf4442c in decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #33 0xdf345df in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #34 0xdf345df in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #35 0xdf345df in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #36 0xdf3e0cc in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #37 0xdf3e0cc in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #38 0xdf3e0cc in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #39 0xdf3e0cc in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #40 0x7f56b5a4d608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8

Thread T30 (MergeMutate) created by T0 here:
    #0 0xdcbcfdc in pthread_create (/workspace/clickhouse+0xdcbcfdc) (BuildId: 8a237203bfc190b0611523cac9422c6feef605df)
    #1 0xdf3cf54 in std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10
    #2 0xdf3cf54 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16
    #3 0xdf311ab in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:144:35
    #4 0xdf433c7 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long, bool) build_docker/../src/Common/ThreadPool.cpp:180:5
    #5 0xdf433c7 in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../src/Common/ThreadPool.h:176:38
    #6 0xdf36c42 in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:144:35
    #7 0xdf3637b in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleOrThrowOnError(std::__1::function<void ()>, int) build_docker/../src/Common/ThreadPool.cpp:168:5
    #8 0x318370ba in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::MergeTreeBackgroundExecutor(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long, unsigned long, unsigned long) build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.h:185:18
    #9 0x2e283dd2 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>* std::__1::construct_at<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>, char const (&) [12], unsigned long&, unsigned long, unsigned long const&, DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>*>(DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>*, char const (&) [12], unsigned long&, unsigned long&&, unsigned long const&) build_docker/../contrib/libcxx/include/__memory/construct_at.h:38:50
    #10 0x2e2228c6 in void std::__1::allocator_traits<std::__1::allocator<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>>>::construct<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>, char const (&) [12], unsigned long&, unsigned long, unsigned long const&, void, void>(std::__1::allocator<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>>&, DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>*, char const (&) [12], unsigned long&, unsigned long&&, unsigned long const&) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:298:9
    #11 0x2e2228c6 in std::__1::__shared_ptr_emplace<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>, std::__1::allocator<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>>>::__shared_ptr_emplace<char const (&) [12], unsigned long&, unsigned long, unsigned long const&>(std::__1::allocator<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>>, char const (&) [12], unsigned long&, unsigned long&&, unsigned long const&) build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:293:9
    #12 0x2e2228c6 in std::__1::shared_ptr<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>> std::__1::allocate_shared<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>, std::__1::allocator<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>>, char const (&) [12], unsigned long&, unsigned long, unsigned long const&, void>(std::__1::allocator<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>> const&, char const (&) [12], unsigned long&, unsigned long&&, unsigned long const&) build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:954:55
    #13 0x2e2228c6 in std::__1::shared_ptr<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>> std::__1::make_shared<DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>, char const (&) [12], unsigned long&, unsigned long, unsigned long const&, void>(char const (&) [12], unsigned long&, unsigned long&&, unsigned long const&) build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:963:12
    #14 0x2e2228c6 in DB::Context::initializeBackgroundExecutorsIfNeeded() build_docker/../src/Interpreters/Context.cpp:3315:37
    #15 0xdd3f75c in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) build_docker/../programs/server/Server.cpp:1414:21
    #16 0x392a9be6 in Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8
    #17 0xdd1e65f in DB::Server::run() build_docker/../programs/server/Server.cpp:466:25
    #18 0x392ed398 in Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #19 0xdd1740f in mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:181:20
    #20 0xdd11f1a in main build_docker/../programs/main.cpp:480:12
    #21 0x7f56b5877082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow build_docker/../src/Columns/ColumnVector.h:407:1 in void DB::TargetSpecific::AVX512VBMI::vectorIndexImpl<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&)
Shadow bytes around the buggy address:
  0x0c0680057e10: 00 00 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680057e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680057e30: fa fa fa fa fa fa fa fa fa fa 00 00 00 00 fa fa
  0x0c0680057e40: 00 00 00 00 fa fa fa fa fa fa fa fa fd fd fd fd
  0x0c0680057e50: fa fa fd fd fd fd fa fa fd fd fd fd fa fa 00 00
=>0x0c0680057e60: 00[07]fa fa fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c0680057e70: fa fa fa fa fa fa 00 00 00 00 fa fa fa fa fa fa
  0x0c0680057e80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680057e90: fa fa fa fa fa fa fa fa fa fa 00 00 00 07 fa fa
  0x0c0680057ea0: fa fa fa fa fa fa fa fa fa fa fa fa 00 00 00 00
  0x0c0680057eb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==139==ABORTING
```
UB (https://s3.amazonaws.com/clickhouse-test-reports/41653/cc6776fc5d54a19c49af55219dfcada1e15ac9b9/fuzzer_astfuzzerubsan//report.html):
```
    #0 0x2b5c6784 in void DB::TargetSpecific::AVX512VBMI::vectorIndexImpl<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&) build_docker/../src/Columns/ColumnVector.h:407:1
    #1 0x2b5c5c7c in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ColumnVector<char8_t>::indexImpl<char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long) const build_docker/../src/Columns/ColumnVector.h:530:13
    #2 0x2b4ee6ec in COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::selectIndexImpl<DB::ColumnVector<char8_t>>(DB::ColumnVector<char8_t> const&, DB::IColumn const&, unsigned long) build_docker/../src/Columns/ColumnsCommon.h:119:32
    #3 0x2b4ee56d in DB::ColumnVector<char8_t>::index(DB::IColumn const&, unsigned long) const build_docker/../src/Columns/ColumnVector.cpp:687:12
    #4 0x2b4265fb in DB::ColumnLowCardinality::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnLowCardinality.cpp:201:53
    #5 0x2b29c656 in DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/../src/Columns/ColumnArray.cpp:527:15
    #6 0x2be9abf6 in DB::MergeTreeDataPartWriterCompact::ColumnsBuffer::add(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&&) build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:376:37
    #7 0x2be9a24a in DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:158:20
    #8 0x2bff061b in DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:308:13
    #9 0x2bd834c8 in DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() build_docker/../src/Storages/MergeTree/MergeTask.cpp:382:64
    #10 0x2bd82fb1 in std::__1::__function::__policy_func<bool ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #11 0x2bd82fb1 in std::__1::function<bool ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #12 0x2bd82fb1 in DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() build_docker/../src/Storages/MergeTree/MergeTask.cpp:366:9
    #13 0x2bd8ec24 in DB::MergeTask::execute() build_docker/../src/Storages/MergeTree/MergeTask.cpp:769:29
    #14 0x2c137b70 in DB::MergePlainMergeTreeTask::executeStep() build_docker/../src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:47:33
    #15 0x2bdb0283 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:137:42
    #16 0x2bdb1610 in DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:259:13
    #17 0x157b1fd2 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #18 0x157b1fd2 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #19 0x157b1fd2 in ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #20 0x157b60ee in void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #21 0x157b60ee in decltype(static_cast<void>(fp)()) std::__1::__invoke_constexpr<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(void&&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #22 0x157b60ee in decltype(auto) std::__1::__apply_tuple_impl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #23 0x157b60ee in decltype(auto) std::__1::apply<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(void&&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #24 0x157b60ee in ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #25 0x157aff12 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #26 0x157aff12 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #27 0x157aff12 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #28 0x157b3d43 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #29 0x157b3d43 in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #30 0x157b3d43 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #31 0x157b3d43 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #32 0x7f0dec72d608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #33 0x7f0dec652132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### LINKED ISSUE #41751: Segmentation fault during merge
Job link:
https://s3.amazonaws.com/clickhouse-test-reports/41206/3283cdb3d16f82332d69e59ede155f0ebe0d2423/fast_test.html

```
2022.09.25 09:17:16.348081 [ 18364 ] {} <Trace> BaseDaemon: Received signal 11
2022.09.25 09:17:16.348307 [ 82194 ] {} <Fatal> BaseDaemon: ########################################
2022.09.25 09:17:16.348359 [ 82194 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: 0E465175F503D2168B2F7CA8BA9AA647E96BFC17) (from thread 18435) (query_id: eb98d989-1234-448e-a9d2-94d33462af72::202209_1_133_39) (query: ) Received signal Segmentation fault (11)
2022.09.25 09:17:16.348378 [ 82194 ] {} <Fatal> BaseDaemon: Address: 0x7fdfbb42b000 Access: read. Attempted access has violated the permissions assigned to the memory area.
2022.09.25 09:17:16.348392 [ 82194 ] {} <Fatal> BaseDaemon: Stack trace: 0xfef8077 0xfef7f2e 0xfe80f8a 0xfe80f09 0xfe15a2e 0xfd3a5d3 0x10396cb9 0x10457bb7 0x102fa9e2 0x102fa90b 0x102fe3da 0x10522a72 0x1030b87b 0x1030c605 0x6f8585e 0x6f88297 0x6f83c9e 0x6f869ae 0x7fe0596e7609 0x7fe059970133
2022.09.25 09:17:16.474106 [ 82194 ] {} <Fatal> BaseDaemon: 3. /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnVector.h:407: void DB::TargetSpecific::AVX512VBMI::vectorIndexImpl<DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0xfef8077 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.550068 [ 82194 ] {} <Fatal> BaseDaemon: 4. /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnVector.h:530: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::ColumnVector<char8_t>::indexImpl<char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, unsigned long) const @ 0xfef7f2e in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.675758 [ 82194 ] {} <Fatal> BaseDaemon: 5. /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnsCommon.h:129: COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::selectIndexImpl<DB::ColumnVector<char8_t> >(DB::ColumnVector<char8_t> const&, DB::IColumn const&, unsigned long) @ 0xfe80f8a in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.743581 [ 82194 ] {} <Fatal> BaseDaemon: 6. /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnVector.cpp:687: DB::ColumnVector<char8_t>::index(DB::IColumn const&, unsigned long) const @ 0xfe80f09 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.758309 [ 82194 ] {} <Fatal> BaseDaemon: 7. /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnLowCardinality.cpp:201: DB::ColumnLowCardinality::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) @ 0xfe15a2e in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.790730 [ 82194 ] {} <Fatal> BaseDaemon: 8.1. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:200: boost::intrusive_ptr<DB::IColumn const>::operator->() const
2022.09.25 09:17:16.790744 [ 82194 ] {} <Fatal> BaseDaemon: 8.2. inlined from /fasttest-workspace/build/../../ClickHouse/src/Common/COW.h:214: COW<DB::IColumn>::chameleon_ptr<DB::IColumn>::operator*()
2022.09.25 09:17:16.790751 [ 82194 ] {} <Fatal> BaseDaemon: 8.3. inlined from /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnArray.h:131: DB::ColumnArray::getOffsets()
2022.09.25 09:17:16.790759 [ 82194 ] {} <Fatal> BaseDaemon: 8. /fasttest-workspace/build/../../ClickHouse/src/Columns/ColumnArray.cpp:529: DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) @ 0xfd3a5d3 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.801712 [ 82194 ] {} <Fatal> BaseDaemon: 9.1. inlined from /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:375: DB::MergeTreeDataPartWriterCompact::ColumnsBuffer::add(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&&)
2022.09.25 09:17:16.801724 [ 82194 ] {} <Fatal> BaseDaemon: 9. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp:158: DB::MergeTreeDataPartWriterCompact::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x10396cb9 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.813658 [ 82194 ] {} <Fatal> BaseDaemon: 10.1. inlined from /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergedBlockOutputStream.cpp:309: DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*)
2022.09.25 09:17:16.813673 [ 82194 ] {} <Fatal> BaseDaemon: 10. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergedBlockOutputStream.cpp:56: DB::MergedBlockOutputStream::write(DB::Block const&) @ 0x10457bb7 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.859479 [ 82194 ] {} <Fatal> BaseDaemon: 11. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTask.cpp:384: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x102fa9e2 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.902096 [ 82194 ] {} <Fatal> BaseDaemon: 12.1. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__functional/function.h:843: std::__1::__function::__policy_func<bool ()>::operator()() const
2022.09.25 09:17:16.902109 [ 82194 ] {} <Fatal> BaseDaemon: 12.2. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__functional/function.h:1184: std::__1::function<bool ()>::operator()() const
2022.09.25 09:17:16.902115 [ 82194 ] {} <Fatal> BaseDaemon: 12. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTask.cpp:366: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x102fa90b in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.952567 [ 82194 ] {} <Fatal> BaseDaemon: 13. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTask.cpp:0: DB::MergeTask::execute() @ 0x102fe3da in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.959377 [ 82194 ] {} <Fatal> BaseDaemon: 14. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:0: DB::MergePlainMergeTreeTask::executeStep() @ 0x10522a72 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.969752 [ 82194 ] {} <Fatal> BaseDaemon: 15. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:137: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x1030b87b in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.976232 [ 82194 ] {} <Fatal> BaseDaemon: 16.1. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
2022.09.25 09:17:16.979944 [ 82194 ] {} <Fatal> BaseDaemon: 16. /fasttest-workspace/build/../../ClickHouse/src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:260: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x1030c605 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.987209 [ 82194 ] {} <Fatal> BaseDaemon: 17.1. inlined from /fasttest-workspace/build/../../ClickHouse/base/base/wide_integer_impl.h:772: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int> >(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2022.09.25 09:17:16.987226 [ 82194 ] {} <Fatal> BaseDaemon: 17.2. inlined from /fasttest-workspace/build/../../ClickHouse/base/base/wide_integer_impl.h:1439: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2022.09.25 09:17:16.987235 [ 82194 ] {} <Fatal> BaseDaemon: 17.3. inlined from /fasttest-workspace/build/../../ClickHouse/base/base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2022.09.25 09:17:16.987243 [ 82194 ] {} <Fatal> BaseDaemon: 17.4. inlined from /fasttest-workspace/build/../../ClickHouse/src/Common/OpenTelemetryTraceContext.h:37: DB::OpenTelemetry::Span::isTraceEnabled() const
2022.09.25 09:17:16.987248 [ 82194 ] {} <Fatal> BaseDaemon: 17. /fasttest-workspace/build/../../ClickHouse/src/Common/ThreadPool.cpp:296: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x6f8585e in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:16.998032 [ 82194 ] {} <Fatal> BaseDaemon: 18.1. inlined from /fasttest-workspace/build/../../ClickHouse/src/Common/ThreadPool.cpp:0: operator()
2022.09.25 09:17:16.998050 [ 82194 ] {} <Fatal> BaseDaemon: 18. /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/type_traits:3640: decltype(static_cast<void>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()&>(void&&) @ 0x6f88297 in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:17.004288 [ 82194 ] {} <Fatal> BaseDaemon: 19.1. inlined from /fasttest-workspace/build/../../ClickHouse/base/base/wide_integer_impl.h:772: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int> >(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2022.09.25 09:17:17.004302 [ 82194 ] {} <Fatal> BaseDaemon: 19.2. inlined from /fasttest-workspace/build/../../ClickHouse/base/base/wide_integer_impl.h:1439: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2022.09.25 09:17:17.004308 [ 82194 ] {} <Fatal> BaseDaemon: 19.3. inlined from /fasttest-workspace/build/../../ClickHouse/base/base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2022.09.25 09:17:17.004314 [ 82194 ] {} <Fatal> BaseDaemon: 19.4. inlined from /fasttest-workspace/build/../../ClickHouse/src/Common/OpenTelemetryTraceContext.h:37: DB::OpenTelemetry::Span::isTraceEnabled() const
2022.09.25 09:17:17.004318 [ 82194 ] {} <Fatal> BaseDaemon: 19. /fasttest-workspace/build/../../ClickHouse/src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x6f83c9e in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:17.012066 [ 82194 ] {} <Fatal> BaseDaemon: 20.1. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__memory/unique_ptr.h:312: std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >::reset(std::__1::__thread_struct*)
2022.09.25 09:17:17.012084 [ 82194 ] {} <Fatal> BaseDaemon: 20.2. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__memory/unique_ptr.h:269: ~unique_ptr
2022.09.25 09:17:17.012093 [ 82194 ] {} <Fatal> BaseDaemon: 20.3. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/tuple:210: ~__tuple_leaf
2022.09.25 09:17:17.012100 [ 82194 ] {} <Fatal> BaseDaemon: 20.4. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/tuple:470: ~tuple
2022.09.25 09:17:17.012111 [ 82194 ] {} <Fatal> BaseDaemon: 20.5. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__memory/unique_ptr.h:54: std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >::operator()(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>*) const
2022.09.25 09:17:17.012122 [ 82194 ] {} <Fatal> BaseDaemon: 20.6. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__memory/unique_ptr.h:315: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> > >::reset(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>*)
2022.09.25 09:17:17.012129 [ 82194 ] {} <Fatal> BaseDaemon: 20.7. inlined from /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/__memory/unique_ptr.h:269: ~unique_ptr
2022.09.25 09:17:17.012139 [ 82194 ] {} <Fatal> BaseDaemon: 20. /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/thread:295: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x6f869ae in /fasttest-workspace/build/programs/clickhouse
2022.09.25 09:17:17.012148 [ 82194 ] {} <Fatal> BaseDaemon: 21. ? @ 0x7fe0596e7609 in ?
2022.09.25 09:17:17.012153 [ 82194 ] {} <Fatal> BaseDaemon: 22. clone @ 0x7fe059970133 in ?
2022.09.25 09:17:17.095311 [ 82194 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: 14A66DB8AB4F6A11ACFD089F5CC3FDD4)
```

### PR DESCRIPTION
**Pull request by guowangy**
This PR re-enable AVX512_VBMI optimized index and AVX512_VBMI2 optimized filter.

Also Fixed https://github.com/ClickHouse/ClickHouse/issues/41745, fixed https://github.com/ClickHouse/ClickHouse/issues/41751. When `limit == 0`, we should just return. Otherwise, it will meet:
1. undefined behavior for right shift with 64: `__mmask64 last_mask = MASK64 >> (64 - data_size);`
2. heap overflow when loading table from `data_pos`.
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Need to also undo these two PRs in this PR: https://github.com/ClickHouse/ClickHouse/pull/41797 https://github.com/ClickHouse/ClickHouse/pull/41752

**Comment by alexey-milovidov** [comment]
@nickitat is on vacation till the end of the week, but he will help next week.

@guowangy sorry for somewhat chaotic reverts :) But we actually need this optimization, it is really great!
Let's make it to production!

**Comment by guowangy** [comment]
@alexey-milovidov 
I was also on vacation :) Sorry for late response. 
I will continue to work on this PR later.

**Comment by guowangy** [comment]
@alexey-milovidov @nickitat
PR is ready, would you please help to review.
Thanks

File: src/Columns/ColumnVector.h [hunk 1]
```diff
@@ -391,6 +395,127 @@ class ColumnVector final : public COWHelper<ColumnVectorHelper, ColumnVector<T>>
...
+            __m512i vidx = _mm512_maskz_loadu_epi8(tail_mask, indexes_pos + pos);
+            __m512i tmp1 = _mm512_permutex2var_epi8(table1, vidx, table2);
+            __m512i tmp2 = _mm512_permutex2var_epi8(table3, vidx, table4);
+            __mmask64 msb = _mm512_movepi8_mask(vidx);
+            __m512i out = _mm512_mask_blend_epi8(msb, tmp1, tmp2);
+            _mm512_mask_storeu_epi8(res_pos + pos, tail_mask, out);
+        }
+    }
+}
+);
```
Comment (nickitat) [inline src/Columns/ColumnVector.h:517]: how much data past the end of the array we could write? say, `data_size == 1`, we have 15 bytes of padding to the right (because elements have size of 1-byte) and we write 64 bytes at a time. looks like potential segfault on these other 48 bytes, am I missing smth?

Comment (guowangy) [reply src/Columns/ColumnVector.h:517]: For `Container & data`, we need to load it into register. If the `data_size == 1`, we use *mask* load (L425-427), to make sure we will not read across boundary, only 1 bytes loaded:
```
        /// one single mask load for table size <= 64
        __mmask64 last_mask = MASK64 >> (64 - data_size);
        __m512i table1 = _mm512_maskz_loadu_epi8(last_mask, data_pos);
```

For `Container & res_data`, we need to store into memory. Let's say if `limit == 1`, we use *mask* store (L461-467) to make sure not to write across boundary, here only 1 bytes stored to `res_data`:
```
        /// tail handling
        if (limit > limit64)
        {
            __mmask64 tail_mask = MASK64 >> (limit64 + 64 - limit);
            __m512i vidx = _mm512_maskz_loadu_epi8(tail_mask, indexes_pos + pos);
            __m512i out = _mm512_permutexvar_epi8(vidx, table1);
            _mm512_mask_storeu_epi8(res_pos + pos, tail_mask, out);
        }
```

File: src/Columns/ColumnVector.cpp [hunk 2]
```diff
@@ -471,6 +477,128 @@ void ColumnVector<T>::insertRangeFrom(const IColumn & src, size_t start, size_t
...
+        _mm512_mask_compressstoreu_epi8(dst, static_cast<__mmask64>(mask), vsrc);
+    else if constexpr (ELEMENT_WIDTH == 2)
+        _mm512_mask_compressstoreu_epi16(dst, static_cast<__mmask32>(mask), vsrc);
+    else if constexpr (ELEMENT_WIDTH == 4)
+        _mm512_mask_compressstoreu_epi32(dst, static_cast<__mmask16>(mask), vsrc);
+    else if constexpr (ELEMENT_WIDTH == 8)
+        _mm512_mask_compressstoreu_epi64(dst, static_cast<__mmask8>(mask), vsrc);
+}
+
+template <typename T, typename Container, size_t SIMD_BYTES>
```
[the remark this answers is not in the document]
Comment (guowangy) [reply src/Columns/ColumnVector.cpp:545]: Yes, the using of `BYTES` is confusing. Actually it refer to elements, not bytes.
Good suggestion.

**Review by nickitat — APPROVED** [review]

**Comment by nickitat** [comment]
`Stateless tests (debug) [2/3]` - https://github.com/ClickHouse/ClickHouse/issues/42629
