### PR TITLE
Respect command-line overrides when reloading configuration

### LINKED ISSUE #80294: Some extra configuration from the command-line arguments are not applied for the server
### Company or project name

ClickHouse

### Describe the unexpected behaviour

`clickhouse-server -- --logger.level information` - is ineffective.

### How to reproduce

^

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Respect command-line overrides when reloading configuration. Closes #80294.

### Version info
- Merged into: `26.2.1.810`

### CODE REVIEW

File: programs/server/Server.cpp [hunk 1]
```diff
@@ -1862,12 +1862,17 @@ try
...
         std::move(main_config_zk_node_cache),
         main_config_zk_changed_event,
-        [&](ConfigurationPtr config, bool initial_loading)
+        [&](ConfigurationPtr loaded_config, bool initial_loading)
         {
-            Settings::checkNoSettingNamesAtTopLevel(*config, config_path);
+            config().add(loaded_config, "default", PRIO_DEFAULT, false);
+            auto previous_config = config().find("default");
+            chassert(previous_config);
+            config().removeConfiguration(previous_config);
```
Comment (azat) [inline programs/server/Server.cpp]: Is this thread-safe?

I guess there can be a race with i.e. callback for `setStartServersCallback` (and maybe something else)

@amosbird suggested a good approach here - #71452

**Comment by alexey-milovidov** [comment]
@azat, might be okay now.

File: base/poco/Util/include/Poco/Util/LayeredConfiguration.h [hunk 2]
```diff
@@ -150,6 +150,13 @@ namespace Util
         /// Does nothing if the given configuration is not part of the
         /// LayeredConfiguration.
 
+        void replaceByLabel(const std::string & label, AbstractConfiguration * pNewConfig, int priority, bool shared);
```
Comment (azat) [inline base/poco/Util/include/Poco/Util/LayeredConfiguration.h]: I guess more natural name will be just `replace` (as for `add`, there is specializations with `label` and without)

**Review by azat — COMMENTED** [review]
Looks good (once the sanitizers errors will be fixed)

Do we need the same fix in case of zk includes as in https://github.com/ClickHouse/ClickHouse/pull/71452/changes#r1830319029 ?

Let's also copy tests from it

**Review by azat — APPROVED** [review]
