### PR TITLE
Analyzer: Fix validateAggregates for tables with different aliases

### LINKED ISSUE #62137: Broken SQLLancer reports with new analyzer
Many reports for both `TLPGroupBy` and `TLPHaving`.

Sample: https://s3.amazonaws.com/clickhouse-test-reports/0/c297e72a4d3a68dbc4f4fb3581e3780f065f8c29/sqlancer__release_.html

It might be that some other error messages need to be ignored (`NOT_FOUND_COLUMN_IN_BLOCK`), but it needs to be reviewed to verify if they are valid queries in CH or not  (and if not why not)

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

close https://github.com/ClickHouse/ClickHouse/issues/62137

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit b8df7c26258b0b448ee81f1b2ec963a55eb2e8bf with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62346/b8df7c26258b0b448ee81f1b2ec963a55eb2e8bf/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/ColumnNode.cpp [hunk 1]
```diff
@@ -73,7 +73,9 @@ void ColumnNode::dumpTreeImpl(WriteBuffer & buffer, FormatState & state, size_t
 bool ColumnNode::isEqualImpl(const IQueryTreeNode & rhs) const
 {
     const auto & rhs_typed = assert_cast<const ColumnNode &>(rhs);
-    return column == rhs_typed.column;
+    auto src = getColumnSourceOrNull();
+    auto rhs_src = rhs_typed.getColumnSourceOrNull();
+    return column == rhs_typed.column && (src && rhs_src && src->isEqual(*rhs_src));
```
Comment (kitaisreal) [inline src/Analyzer/ColumnNode.cpp:78]: It should not be done manually, `isEqualImpl` need to compare only internal state.
From code documentation:
```
/** Subclass must compare its internal state with rhs node internal state and do not compare children or weak pointers to other
  * query tree nodes.
  */
virtual bool isEqualImpl(const IQueryTreeNode & rhs) const = 0;
```
This was implemented that way, because it is possible to have recursive cycles during comparison of weak pointers.
For example column node is inside lambda, and lambda is column node source.

It is done properly in IQueryTreeNode.h `isEqual` method.

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Analyzer/ColumnNode.cpp (hunk 1 above)
Comment (vdimir) [reply src/Analyzer/ColumnNode.cpp]: Maybe we can just always compare aliases for TableNode? Because when we have `table` and `table as t1` in query tree normally it indicates that it's a different reads from the same table

File: src/Analyzer/ValidationUtils.cpp [hunk 2]
```diff
@@ -134,15 +134,70 @@ class ValidateGroupByColumnsVisitor : public ConstInDepthQueryTreeVisitor<Valida
     }
 
 private:
+
+    static bool areColumnSourcesEqual(const QueryTreeNodePtr & lhs, const QueryTreeNodePtr & rhs)
```
Comment (novikd) [inline src/Analyzer/ValidationUtils.cpp:138]: Let's remove this function, instead I propose to add a new flag `compare_column_sources` into `CompareOptions` and use it in `ColumnNode::isEqualImpl`.

File: src/Analyzer/ColumnNode.cpp (hunk 1 above)
Comment (novikd) [reply src/Analyzer/ColumnNode.cpp]: I suppose we don't need to call `isEqual` for column sources. We can just compare where these pointers refer to.

**Comment by vdimir** [comment]
> Stateless tests (tsan, s3 storage) [3/5] — Invalid check_status.tsv [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__tsan__s3_storage__[3_5].html)
> AST fuzzer (ubsan) — /build/contrib/llvm-project/libcxx/include/stdlib.h:112:25: runtime error: negation of -9223372036854775808 cannot be represented in type... [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/ast_fuzzer__ubsan_.html)
> Stateless tests (coverage) [2/6] — fail: 1, passed: 1073, skipped: 3 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__coverage__[2_6].html)
> Stateless tests (debug) [1/5] — fail: 2, passed: 1259, skipped: 16 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__debug__[1_5].html)
> Stateless tests (debug) [2/5] — fail: 2, passed: 1204, skipped: 12 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__debug__[2_5].html)
> Stateless tests (debug) [3/5] — Tests are not finished, fail: 3, passed: 1136, skipped: 17 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__debug__[3_5].html)
> Stateless tests (debug) [4/5] — fail: 2, passed: 1246, skipped: 19 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__debug__[4_5].html)
> Stateless tests (debug, s3 storage) [6/6] — fail: 2, passed: 997, skipped: 17 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__debug__s3_storage__[6_6].html)
> Stateless tests (tsan) [3/5] — fail: 2, passed: 1318, skipped: 27 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__tsan__[3_5].html)
> Stateless tests (tsan, s3 storage) [1/5] — fail: 2, passed: 1293, skipped: 23 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stateless_tests__tsan__s3_storage__[1_5].html)
> Stress test (asan) — Killed by signal (in clickhouse-server.log) [Details](https://s3.amazonaws.com/clickhouse-test-reports/62346/aeca94105beadcf4dd28ec1c3b76fa63416fb74e/stress_test__asan_.html)

`Not keeper outcome`

**Comment by clickgapai** [comment]
Hi @vdimir — while reviewing this PR I found the following:

- **Coverage gap:** `areColumnSourcesEqual` recursive descent through `FunctionNode` children untested — https://github.com/ClickHouse/ClickHouse/pull/104029

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
