### PR TITLE
Attach data parts in the original order

### LINKED ISSUE #71009: ReplacingMergeTree depends on the order of part attachment
When attaching a partition, parts are attached in an unspecifing order. If the order of the parts is violated, ReplacingMergeTree might lose data. I have written a test to reproduce this scenario.

Reason:

To get the list of detached parts, the following function is used:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeData.cpp#L6446

This function uses an iterator to traverse the directory for the local disk:
```cpp
disk->iterateDirectory(detached_path)
```
This iterator is a wrapper around the standard:
```cpp
fs::directory_iterator entry
```
And its order is unspecified - The iteration order is unspecified

https://en.cppreference.com/w/cpp/filesystem/directory_iterator

Solution:
I suggest providing guaranteed order for part attachment for some engines (ReplacingMergeTree).

What do you think?

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Attaching parts of MergeTree tables will be performed in their block order, which is important for special merging algorithms, such as ReplacingMergeTree. This closes #71009.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -6799,6 +6799,20 @@ MergeTreeData::MutableDataPartsVector MergeTreeData::tryLoadPartsToAttach(const
...
+        {
+            String containing_part = active_parts.getContainingPart(part_info.dir_name);
+            return containing_part.empty();
+        });
+
+        std::sort(detached_parts.begin(), detached_parts.end(), [&](const auto & a, const auto & b)
+        {
+            MergeTreePartInfo info_a = MergeTreePartInfo::fromPartName(active_parts.getContainingPart(a), format_version);
+            MergeTreePartInfo info_b = MergeTreePartInfo::fromPartName(active_parts.getContainingPart(b), format_version);
+            return a < b;
```
Comment (evillique) [inline src/Storages/MergeTree/MergeTreeData.cpp:6813]: Probably meant to be this
```suggestion
            return info_a < info_b;
```

**Review by evillique — APPROVED** [review]
