### PR TITLE
Date time timezone fix

### LINKED ISSUE #24128: TimeZone is ignored in function if with Date and DateTime
```
qoega-dev.sas.yp-c.yandex.net :) SELECT toDate('2000-01-01') < toDateTime('2000-01-01 00:00:01', 'Europe/Moscow');

SELECT toDate('2000-01-01') < toDateTime('2000-01-01 00:00:01', 'Europe/Moscow')

Query id: baf63ad5-1893-401c-9728-63bd5c295df1

┌─less(toDate('2000-01-01'), toDateTime('2000-01-01 00:00:01', 'Europe/Moscow'))─┐
│                                                                              0 │
└────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec.

qoega-dev.sas.yp-c.yandex.net :) SELECT toDate('2000-01-01') < toDateTime('2000-01-01 00:00:01');

SELECT toDate('2000-01-01') < toDateTime('2000-01-01 00:00:01')

Query id: c2136446-a3a0-4567-a94e-68f40dc1f158

┌─less(toDate('2000-01-01'), toDateTime('2000-01-01 00:00:01'))─┐
│                                                             1 │
└───────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec.
```

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`CAST` from `Date` to `DateTime` (or `DateTime64`) was not using the timezone of the `DateTime` type. It can also affect the comparison between `Date` and `DateTime`. Inference of the common type for `Date` and `DateTime` also was not using the corresponding timezone. It affected the results of function `if` and array construction. Closes #24128.

### CODE REVIEW

File: src/DataTypes/getLeastSupertype.cpp [hunk 1]
```diff
@@ -288,21 +288,34 @@ DataTypePtr getLeastSupertype(const DataTypes & types)
                     ErrorCodes::NO_COMMON_TYPE);
 
             if (have_datetime64 == 0)
+            {
+                for (const auto & t : types)
+                {
+                    if (const auto * data_type = typeid_cast<const DataTypeDateTime *>(t.get()))
+                        return std::make_shared<DataTypeDateTime>(data_type->getTimeZone().getTimeZone());
```
Comment (alexey-milovidov) [inline src/DataTypes/getLeastSupertype.cpp:295]: We can simply return `t`, no need to construct a new object.

File: src/DataTypes/getLeastSupertype.cpp [hunk 2]
```diff
@@ -288,21 +288,34 @@ DataTypePtr getLeastSupertype(const DataTypes & types)
                     ErrorCodes::NO_COMMON_TYPE);
 
             if (have_datetime64 == 0)
+            {
+                for (const auto & t : types)
+                {
+                    if (const auto * data_type = typeid_cast<const DataTypeDateTime *>(t.get()))
```
Comment (alexey-milovidov) [inline src/DataTypes/getLeastSupertype.cpp:294]: Then we can avoid typeid_cast :)

File: src/DataTypes/getLeastSupertype.cpp [hunk 3]
```diff
@@ -288,21 +288,34 @@ DataTypePtr getLeastSupertype(const DataTypes & types)
...
+                    {
+                        max_scale_date_time = dt64;
                         max_scale = scale;
+                    }
                 }
             }
 
-            return std::make_shared<DataTypeDateTime64>(max_scale);
+            assert(max_scale_date_time);
+            return std::make_shared<DataTypeDateTime64>(max_scale, max_scale_date_time->getTimeZone().getTimeZone());
```
Comment (alexey-milovidov) [inline src/DataTypes/getLeastSupertype.cpp:318]: .

**Comment by alexey-milovidov** [comment]
Only a few changes required...

File: tests/queries/0_stateless/01926_date_date_supertype.sql [hunk 4]
```diff
@@ -0,0 +1,3 @@
+SELECT toTypeName([toDate('2000-01-01'), toDateTime('2000-01-01', 'Europe/Moscow')]);
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01926_date_date_supertype.sql:1]: Also add `if` and `CAST`.
