### PR TITLE
Fix wrong column nullability in StoreageJoin

### LINKED ISSUE #44940: Logical error: 'Block structure mismatch: in HashJoin
```
Logical error: 'Block structure mismatch: [x Nullable(UInt32) Nullable(size = 0, UInt32(size = 0), UInt8(size = 0)), s LowCardinality(Nullable(String)) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1)))] != [x Nullable(UInt32) Nullable(size = 6, UInt32(size = 6), UInt8(size = 6)), s LowCardinality(String) ColumnLowCardinality(size = 6, UInt8(size = 6), ColumnUnique(size = 7, String(size = 7)))]'.

```

https://s3.amazonaws.com/clickhouse-test-reports/44917/d06ac2d468abd1dc2f0c027f03c7c6553a335200/fuzzer_astfuzzerdebug/report.html

```
2023.01.04 22:54:23.047975 [ 415 ] {6ad50ca9-e9ba-497d-b3fa-a51ae9379bb5} <Fatal> : Logical error: 'Block structure mismatch: [x Nullable(UInt32) Nullable(size = 0, UInt32(size = 0), UInt8(size = 0)), s LowCardinality(Nullable(String)) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1)))] != [x Nullable(UInt32) Nullable(size = 6, UInt32(size = 6), UInt8(size = 6)), s LowCardinality(String) ColumnLowCardinality(size = 6, UInt8(size = 6), ColumnUnique(size = 7, String(size = 7)))]'. 2023.01.04 22:54:23.049147 [ 422 ] {} <Fatal> BaseDaemon: ######################################## 2023.01.04 22:54:23.049379 [ 422 ] {} <Fatal> BaseDaemon: (version 22.13.1.1, build id: 39C5D6EE4AD9279A6F1B6B2257FAF5FC76DC2319) (from thread 415) (query_id: 6ad50ca9-e9ba-497d-b3fa-a51ae9379bb5) (query: SELECT * FROM t1__fuzz_8 FULL OUTER JOIN full_join__fuzz_4 USING (x) ORDER BY x DESC, str ASC, s ASC NULLS LAST) Received signal Aborted (6) 2023.01.04 22:54:23.049592 [ 422 ] {} <Fatal> BaseDaemon:  2023.01.04 22:54:23.049826 [ 422 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fdc7587b00b 0x7fdc7585a859 0x211f3556 0x211f3615 0x211f3765 0x187d852a 0x18f19fd2 0x28d7e7b3 0x28dd08cf 0x28ddb080 0x28fc6e0f 0x28fc3e31 0x28fba82f 0x28fb9a36 0x291ecd6f 0x28fb94b1 0x28fb9439 0x28da4ff9 0x28da49df 0x28da47f5 0x28d0319f 0x28d0305f 0x2b810f23 0x2b810c8e 0x2b81059d 0x2b41d703 0x2b41d406 0x2b3fc021 0x2b3fc337 0x2b3fb318 0x2b3faa38 0x2b4241da 0x2b424080 0x2b424015 0x2b423ff9 0x2b423f5d 0x2b423e62 0x2b423dd5 0x2b423db5 0x2b423d95 0x2b423d60 2023.01.04 22:54:23.050112 [ 422 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7fdc7587b00b in ? 2023.01.04 22:54:23.050265 [ 422 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7fdc7585a859 in ? 2023.01.04 22:54:23.155197 [ 422 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x211f3556 in /workspace/clickhouse 2023.01.04 22:54:23.258868 [ 422 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../src/Common/Exception.cpp:64: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&) @ 0x211f3615 in /workspace/clickhouse 2023.01.04 22:54:23.349910 [ 422 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x211f3765 in /workspace/clickhouse 2023.01.04 22:54:23.452274 [ 422 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../src/Common/Exception.h:41: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0x187d852a in /workspace/clickhouse 2023.01.04 22:54:23.585890 [ 422 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x18f19fd2 in /workspace/clickhouse 2023.01.04 22:54:24.830776 [ 422 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Interpreters/HashJoin.cpp:895: DB::(anonymous namespace)::AddedColumns::assertBlockEqualsStructureUpToLowCard(DB::Block const&, DB::Block const&) @ 0x28d7e7b3 in /workspace/clickhouse 2023.01.04 22:54:26.085202 [ 422 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Interpreters/HashJoin.cpp:914: void DB::(anonymous namespace)::AddedColumns::appendFromBlock<false>(DB::Block const&, unsigned long) @ 0x28dd08cf in /workspace/clickhouse 2023.01.04 22:54:26.986690 [ 422 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../src/Interpreters/HashJoin.cpp:1134: void DB::(anonymous namespace)::addFoundRowAll<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false>(HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::mapped_type const&, DB::(anonymous namespace)::AddedColumns&, unsigned long&, DB::(anonymous namespace)::KnownRowsHolder<false>&, DB::JoinStuff::JoinUsedFlags*) @ 0x28ddb080 in /workspace/clickhouse 2023.01.04 22:54:28.157152 [ 422 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../src/Interpreters/HashJoin.cpp:1229: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumns<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, true, false>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) @ 0x28fc6e0f in /workspace/clickhouse 2023.01.04 22:54:29.307906 [ 422 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../src/Interpreters/HashJoin.cpp:0: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumnsSwitchMultipleDisjuncts<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, true>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) @ 0x28fc3e31 in /workspace/clickhouse 2023.01.04 22:54:30.458837 [ 422 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../src/Interpreters/HashJoin.cpp:1340: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumnsSwitchNullability<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) @ 0x28fba82f in /workspace/clickhouse 2023.01.04 22:54:31.603507 [ 422 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../src/Interpreters/HashJoin.cpp:1388: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::switchJoinRightColumns<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>(std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::HashJoin::Type, DB::JoinStuff::JoinUsedFlags&) @ 0x28fb9a36 in /workspace/clickhouse 2023.01.04 22:54:32.918046 [ 422 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../src/Interpreters/HashJoin.cpp:1442: void DB::HashJoin::joinBlockImpl<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>(DB::Block&, DB::Block const&, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>> const&, bool) const @ 0x291ecd6f in /workspace/clickhouse 2023.01.04 22:54:34.219658 [ 422 ] {} <Fatal> BaseDaemon: 19. /build/build_docker/../src/Interpreters/HashJoin.cpp:1709: auto DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4::operator()<std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)3>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)3>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>>>(std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)3>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)3>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>>&) const @ 0x28fb94b1 in /workspace/clickhouse 2023.01.04 22:54:35.519300 [ 422 ] {} <Fatal> BaseDaemon: 20. /build/build_docker/../src/Interpreters/joinDispatch.h:121: auto bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)::operator()<std::__1::integral_constant<int, 14>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>) const @ 0x28fb9439 in /workspace/clickhouse 2023.01.04 22:54:36.768606 [ 422 ] {} <Fatal> BaseDaemon: 21. /build/build_docker/../base/base/constexpr_helpers.h:18: bool func_wrapper<bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), std::__1::integral_constant<int, 14>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) @ 0x28da4ff9 in /workspace/clickhouse 2023.01.04 22:54:38.017252 [ 422 ] {} <Fatal> BaseDaemon: 22. /build/build_docker/../base/base/constexpr_helpers.h:24: bool static_for_impl<int, 0, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&, std::__1::integer_sequence<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>) @ 0x28da49df in /workspace/clickhouse 2023.01.04 22:54:39.265608 [ 422 ] {} <Fatal> BaseDaemon: 23. /build/build_docker/../base/base/constexpr_helpers.h:31: bool static_for<0, 24, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&) @ 0x28da47f5 in /workspace/clickhouse 2023.01.04 22:54:40.617587 [ 422 ] {} <Fatal> BaseDaemon: 24. /build/build_docker/../src/Interpreters/joinDispatch.h:106: bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) @ 0x28d0319f in /workspace/clickhouse 2023.01.04 22:54:41.776146 [ 422 ] {} <Fatal> BaseDaemon: 25. /build/build_docker/../src/Interpreters/HashJoin.cpp:1706: DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&) @ 0x28d0305f in /workspace/clickhouse 2023.01.04 22:54:41.866872 [ 422 ] {} <Fatal> BaseDaemon: 26. /build/build_docker/../src/Processors/Transforms/JoiningTransform.cpp:207: DB::JoiningTransform::readExecute(DB::Chunk&) @ 0x2b810f23 in /workspace/clickhouse 2023.01.04 22:54:41.957501 [ 422 ] {} <Fatal> BaseDaemon: 27. /build/build_docker/../src/Processors/Transforms/JoiningTransform.cpp:191: DB::JoiningTransform::transform(DB::Chunk&) @ 0x2b810c8e in /workspace/clickhouse 2023.01.04 22:54:42.047136 [ 422 ] {} <Fatal> BaseDaemon: 28. /build/build_docker/../src/Processors/Transforms/JoiningTransform.cpp:125: DB::JoiningTransform::work() @ 0x2b81059d in /workspace/clickhouse 2023.01.04 22:54:42.085818 [ 422 ] {} <Fatal> BaseDaemon: 29. /build/build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x2b41d703 in /workspace/clickhouse 2023.01.04 22:54:42.120937 [ 422 ] {} <Fatal> BaseDaemon: 30. /build/build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2b41d406 in /workspace/clickhouse 2023.01.04 22:54:42.225085 [ 422 ] {} <Fatal> BaseDaemon: 31. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2b3fc021 in /workspace/clickhouse 2023.01.04 22:54:42.328663 [ 422 ] {} <Fatal> BaseDaemon: 32. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x2b3fc337 in /workspace/clickhouse 2023.01.04 22:54:42.423262 [ 422 ] {} <Fatal> BaseDaemon: 33. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:372: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2b3fb318 in /workspace/clickhouse 2023.01.04 22:54:42.525793 [ 422 ] {} <Fatal> BaseDaemon: 34. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:90: DB::PipelineExecutor::execute(unsigned long) @ 0x2b3faa38 in /workspace/clickhouse 2023.01.04 22:54:42.622642 [ 422 ] {} <Fatal> BaseDaemon: 35. /build/build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0x2b4241da in /workspace/clickhouse 2023.01.04 22:54:42.718251 [ 422 ] {} <Fatal> BaseDaemon: 36. /build/build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const @ 0x2b424080 in /workspace/clickhouse 2023.01.04 22:54:42.814869 [ 422 ] {} <Fatal> BaseDaemon: 37. /build/build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x2b424015 in /workspace/clickhouse 2023.01.04 22:54:42.911845 [ 422 ] {} <Fatal> BaseDaemon: 38. /build/build_docker/../contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) @ 0x2b423ff9 in /workspace/clickhouse 2023.01.04 22:54:43.008994 [ 422 ] {} <Fatal> BaseDaemon: 39. /build/build_docker/../contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) @ 0x2b423f5d in /workspace/clickhouse 2023.01.04 22:54:45.328221 [ 140 ] {} <Fatal> Application: Child process was terminated by signal 6.

AST Fuzzer for PR [#44917](https://github.com/ClickHouse/ClickHouse/pull/44917) @ d06ac2d468abd1dc2f0c027f03c7c6553a335200
[run.log](https://s3.amazonaws.com/clickhouse-test-reports/44917/d06ac2d468abd1dc2f0c027f03c7c6553a335200/fuzzer_astfuzzerdebug/run.log) [fuzzer.log](https://s3.amazonaws.com/clickhouse-test-reports/44917/d06ac2d468abd1dc2f0c027f03c7c6553a335200/fuzzer_astfuzzerdebug/fuzzer.log) [server.log.gz](https://s3.amazonaws.com/clickhouse-test-reports/44917/d06ac2d468abd1dc2f0c027f03c7c6553a335200/fuzzer_astfuzzerdebug/server.log.gz) [main.log](https://s3.amazonaws.com/clickhouse-test-reports/44917/d06ac2d468abd1dc2f0c027f03c7c6553a335200/fuzzer_astfuzzerdebug/main.log) [core.gz](https://s3.amazonaws.com/clickhouse-test-reports/44917/d06ac2d468abd1dc2f0c027f03c7c6553a335200/fuzzer_astfuzzerdebug/core.gz)

Test name	Test status	Description
AST Fuzzer	failure	Logical error: 'Block structure mismatch: [x Nullable(UInt32) Nullable(size = 0, UInt32(size = 0), UInt8(size = 0)), s LowCardinality(Nullable(String)) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1)))] != [x Nullable(UInt32) Nullable(size = 6, UInt32(size = 6), UInt8(size = 6)), s LowCardinality(String) ColumnLowCardinality(size = 6, UInt8(size = 6), ColumnUnique(size = 7, String(size = 7)))]'.
Received signal 6
Received signal Aborted (6)
2023.01.04 22:54:23.047975 [ 415 ] {6ad50ca9-e9ba-497d-b3fa-a51ae9379bb5} <Fatal> : Logical error: 'Block structure mismatch: [x Nullable(UInt32) Nullable(size = 0, UInt32(size = 0), UInt8(size = 0)), s LowCardinality(Nullable(String)) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1)))] != [x Nullable(UInt32) Nullable(size = 6, UInt32(size = 6), UInt8(size = 6)), s LowCardinality(String) ColumnLowCardinality(size = 6, UInt8(size = 6), ColumnUnique(size = 7, String(size = 7)))]'.
2023.01.04 22:54:23.049147 [ 422 ] {} <Fatal> BaseDaemon: ########################################
2023.01.04 22:54:23.049379 [ 422 ] {} <Fatal> BaseDaemon: (version 22.13.1.1, build id: 39C5D6EE4AD9279A6F1B6B2257FAF5FC76DC2319) (from thread 415) (query_id: 6ad50ca9-e9ba-497d-b3fa-a51ae9379bb5) (query: SELECT * FROM t1__fuzz_8 FULL OUTER JOIN full_join__fuzz_4 USING (x) ORDER BY x DESC, str ASC, s ASC NULLS LAST) Received signal Aborted (6)
2023.01.04 22:54:23.049592 [ 422 ] {} <Fatal> BaseDaemon: 
2023.01.04 22:54:23.049826 [ 422 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fdc7587b00b 0x7fdc7585a859 0x211f3556 0x211f3615 0x211f3765 0x187d852a 0x18f19fd2 0x28d7e7b3 0x28dd08cf 0x28ddb080 0x28fc6e0f 0x28fc3e31 0x28fba82f 0x28fb9a36 0x291ecd6f 0x28fb94b1 0x28fb9439 0x28da4ff9 0x28da49df 0x28da47f5 0x28d0319f 0x28d0305f 0x2b810f23 0x2b810c8e 0x2b81059d 0x2b41d703 0x2b41d406 0x2b3fc021 0x2b3fc337 0x2b3fb318 0x2b3faa38 0x2b4241da 0x2b424080 0x2b424015 0x2b423ff9 0x2b423f5d 0x2b423e62 0x2b423dd5 0x2b423db5 0x2b423d95 0x2b423d60
2023.01.04 22:54:23.050112 [ 422 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7fdc7587b00b in ?
2023.01.04 22:54:23.050265 [ 422 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7fdc7585a859 in ?
2023.01.04 22:54:23.155197 [ 422 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x211f3556 in /workspace/clickhouse
2023.01.04 22:54:23.258868 [ 422 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../src/Common/Exception.cpp:64: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&) @ 0x211f3615 in /workspace/clickhouse
2023.01.04 22:54:23.349910 [ 422 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x211f3765 in /workspace/clickhouse
2023.01.04 22:54:23.452274 [ 422 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../src/Common/Exception.h:41: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0x187d852a in /workspace/clickhouse
2023.01.04 22:54:23.585890 [ 422 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x18f19fd2 in /workspace/clickhouse
2023.01.04 22:54:24.830776 [ 422 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../src/Interpreters/HashJoin.cpp:895: DB::(anonymous namespace)::AddedColumns::assertBlockEqualsStructureUpToLowCard(DB::Block const&, DB::Block const&) @ 0x28d7e7b3 in /workspace/clickhouse
2023.01.04 22:54:26.085202 [ 422 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../src/Interpreters/HashJoin.cpp:914: void DB::(anonymous namespace)::AddedColumns::appendFromBlock<false>(DB::Block const&, unsigned long) @ 0x28dd08cf in /workspace/clickhouse
2023.01.04 22:54:26.986690 [ 422 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../src/Interpreters/HashJoin.cpp:1134: void DB::(anonymous namespace)::addFoundRowAll<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false>(HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::mapped_type const&, DB::(anonymous namespace)::AddedColumns&, unsigned long&, DB::(anonymous namespace)::KnownRowsHolder<false>&, DB::JoinStuff::JoinUsedFlags*) @ 0x28ddb080 in /workspace/clickhouse
2023.01.04 22:54:28.157152 [ 422 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../src/Interpreters/HashJoin.cpp:1229: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumns<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, true, false>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) @ 0x28fc6e0f in /workspace/clickhouse
2023.01.04 22:54:29.307906 [ 422 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../src/Interpreters/HashJoin.cpp:0: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumnsSwitchMultipleDisjuncts<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, true>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) @ 0x28fc3e31 in /workspace/clickhouse
2023.01.04 22:54:30.458837 [ 422 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../src/Interpreters/HashJoin.cpp:1340: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumnsSwitchNullability<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) @ 0x28fba82f in /workspace/clickhouse
2023.01.04 22:54:31.603507 [ 422 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../src/Interpreters/HashJoin.cpp:1388: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::switchJoinRightColumns<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>(std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::HashJoin::Type, DB::JoinStuff::JoinUsedFlags&) @ 0x28fb9a36 in /workspace/clickhouse
2023.01.04 22:54:32.918046 [ 422 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../src/Interpreters/HashJoin.cpp:1442: void DB::HashJoin::joinBlockImpl<(DB::JoinKind)3, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>(DB::Block&, DB::Block const&, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>> const&, bool) const @ 0x291ecd6f in /workspace/clickhouse
2023.01.04 22:54:34.219658 [ 422 ] {} <Fatal> BaseDaemon: 19. /build/build_docker/../src/Interpreters/HashJoin.cpp:1709: auto DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4::operator()<std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)3>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)3>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>>>(std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)3>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)3>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>>&) const @ 0x28fb94b1 in /workspace/clickhouse
2023.01.04 22:54:35.519300 [ 422 ] {} <Fatal> BaseDaemon: 20. /build/build_docker/../src/Interpreters/joinDispatch.h:121: auto bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)::operator()<std::__1::integral_constant<int, 14>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>) const @ 0x28fb9439 in /workspace/clickhouse
2023.01.04 22:54:36.768606 [ 422 ] {} <Fatal> BaseDaemon: 21. /build/build_docker/../base/base/constexpr_helpers.h:18: bool func_wrapper<bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), std::__1::integral_constant<int, 14>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) @ 0x28da4ff9 in /workspace/clickhouse
2023.01.04 22:54:38.017252 [ 422 ] {} <Fatal> BaseDaemon: 22. /build/build_docker/../base/base/constexpr_helpers.h:24: bool static_for_impl<int, 0, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&, std::__1::integer_sequence<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>) @ 0x28da49df in /workspace/clickhouse
2023.01.04 22:54:39.265608 [ 422 ] {} <Fatal> BaseDaemon: 23. /build/build_docker/../base/base/constexpr_helpers.h:31: bool static_for<0, 24, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&) @ 0x28da47f5 in /workspace/clickhouse
2023.01.04 22:54:40.617587 [ 422 ] {} <Fatal> BaseDaemon: 24. /build/build_docker/../src/Interpreters/joinDispatch.h:106: bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) @ 0x28d0319f in /workspace/clickhouse
2023.01.04 22:54:41.776146 [ 422 ] {} <Fatal> BaseDaemon: 25. /build/build_docker/../src/Interpreters/HashJoin.cpp:1706: DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&) @ 0x28d0305f in /workspace/clickhouse
2023.01.04 22:54:41.866872 [ 422 ] {} <Fatal> BaseDaemon: 26. /build/build_docker/../src/Processors/Transforms/JoiningTransform.cpp:207: DB::JoiningTransform::readExecute(DB::Chunk&) @ 0x2b810f23 in /workspace/clickhouse
2023.01.04 22:54:41.957501 [ 422 ] {} <Fatal> BaseDaemon: 27. /build/build_docker/../src/Processors/Transforms/JoiningTransform.cpp:191: DB::JoiningTransform::transform(DB::Chunk&) @ 0x2b810c8e in /workspace/clickhouse
2023.01.04 22:54:42.047136 [ 422 ] {} <Fatal> BaseDaemon: 28. /build/build_docker/../src/Processors/Transforms/JoiningTransform.cpp:125: DB::JoiningTransform::work() @ 0x2b81059d in /workspace/clickhouse
2023.01.04 22:54:42.085818 [ 422 ] {} <Fatal> BaseDaemon: 29. /build/build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) @ 0x2b41d703 in /workspace/clickhouse
2023.01.04 22:54:42.120937 [ 422 ] {} <Fatal> BaseDaemon: 30. /build/build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2b41d406 in /workspace/clickhouse
2023.01.04 22:54:42.225085 [ 422 ] {} <Fatal> BaseDaemon: 31. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2b3fc021 in /workspace/clickhouse
2023.01.04 22:54:42.328663 [ 422 ] {} <Fatal> BaseDaemon: 32. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x2b3fc337 in /workspace/clickhouse
2023.01.04 22:54:42.423262 [ 422 ] {} <Fatal> BaseDaemon: 33. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:372: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2b3fb318 in /workspace/clickhouse
2023.01.04 22:54:42.525793 [ 422 ] {} <Fatal> BaseDaemon: 34. /build/build_docker/../src/Processors/Executors/PipelineExecutor.cpp:90: DB::PipelineExecutor::execute(unsigned long) @ 0x2b3faa38 in /workspace/clickhouse
2023.01.04 22:54:42.622642 [ 422 ] {} <Fatal> BaseDaemon: 35. /build/build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0x2b4241da in /workspace/clickhouse
2023.01.04 22:54:42.718251 [ 422 ] {} <Fatal> BaseDaemon: 36. /build/build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const @ 0x2b424080 in /workspace/clickhouse
2023.01.04 22:54:42.814869 [ 422 ] {} <Fatal> BaseDaemon: 37. /build/build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x2b424015 in /workspace/clickhouse
2023.01.04 22:54:42.911845 [ 422 ] {} <Fatal> BaseDaemon: 38. /build/build_docker/../contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) @ 0x2b423ff9 in /workspace/clickhouse
2023.01.04 22:54:43.008994 [ 422 ] {} <Fatal> BaseDaemon: 39. /build/build_docker/../contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) @ 0x2b423f5d in /workspace/clickhouse
2023.01.04 22:54:45.328221 [ 140 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong column nullability in StoreageJoin, close https://github.com/ClickHouse/ClickHouse/issues/44940

### Documentation entry for user-facing changes

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/TableJoin.cpp [hunk 1]
```diff
@@ -458,16 +458,6 @@ TableJoin::createConvertingActions(
                 LOG_DEBUG(&Poco::Logger::get("TableJoin"), "{} JOIN converting actions: empty", side);
                 return;
             }
-            auto format_cols = [](const auto & cols) -> std::string
```
Comment (vdimir) [inline src/Interpreters/TableJoin.cpp:461]: Same log message was printed twice (probably appeared during merging conflicts)

**Comment by Avogar** [comment]
Can we make a test?

**Comment by vdimir** [comment]
> Can we make a test?

Sure, I've just forgot to commit it, thank you.

**Review by Avogar — APPROVED** [review]

**Comment by vdimir** [comment]
> Bugfix validate check — Changed tests don't reproduce the bug [Details](https://s3.amazonaws.com/clickhouse-test-reports/45184/f9240a8f903f0e8e9df399520f5c0dc4a7957586/bugfix_validate_check.html)

Check is performed only on debug build, but this check uses asan

https://github.com/ClickHouse/ClickHouse/blob/a927ecfe04ec08c7fa99460bc48860dbf8ee2a1d/src/Interpreters/HashJoin.cpp#L912-L917
