### PR TITLE
DNS cache: Add option to drop elements after several consecutive failures

### LINKED ISSUE #26711: DNS Resolver polluting the logs
**Describe the bug**

If a hostname used is invalid, the dns resolver will keep throwing errors in each update after the server is restarted.

**Does it reproduce on recent release?**

Yes

**How to reproduce**

Run `01946_test_wrong_host_name_access` and keep an eye on the logs after.  In each refresh you will see an error like this although the user was already deleted:

```
2021.07.22 17:39:03.783264 [ 694783 ] {} <Debug> DNSResolver: Updating DNS cache
2021.07.22 17:39:03.808051 [ 694783 ] {} <Error> DNSResolver: Cannot resolve host (non.existing.host.name), error 0: non.existing.host.name.
2021.07.22 17:39:03.808244 [ 694783 ] {} <Error> bool DB::DNSResolver::updateCacheImpl(UpdateF &&, ElemsT &&, const DB::String &) [UpdateF = bool (DB::DNSResolver::*)(const std::string &), ElemsT = std::unordered_set<std::string> &]: Code: 198. DB::Exception: Not found address of host: non.existing.host.name. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):

0. /mnt/ch/ClickHouse/contrib/poco/Foundation/src/Exception.cpp:28: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x11733a in /mnt/ch/ClickHouse/build/contrib/poco-cmake/Foundation/lib_poco_foundation.so
1. /mnt/ch/ClickHouse/src/Common/Exception.cpp:59: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x11216e in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
2. /mnt/ch/ClickHouse/src/Common/DNSResolver.cpp:0: DB::resolveIPAddressImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xffe53 in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
3. /mnt/ch/ClickHouse/contrib/libcxx/include/__mutex_base:91: std::__1::vector<Poco::Net::IPAddress, std::__1::allocator<Poco::Net::IPAddress> > SimpleCache<std::__1::vector<Poco::Net::IPAddress, std::__1::allocator<Poco::Net::IPAddress> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), &(DB::resolveIPAddressImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))>::operator()<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x100a54 in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
4. /mnt/ch/ClickHouse/contrib/libcxx/include/memory:1627: DB::DNSResolver::updateHost(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x102779 in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
5. /mnt/ch/ClickHouse/src/Common/DNSResolver.cpp:262: bool DB::DNSResolver::updateCacheImpl<bool (DB::DNSResolver::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&>(bool (DB::DNSResolver::*&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x102f5f in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
6. /mnt/ch/ClickHouse/contrib/libcxx/include/string:1444: DB::DNSResolver::updateCache() @ 0x10206b in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
7. /mnt/ch/ClickHouse/src/Interpreters/DNSCacheUpdater.cpp:23: DB::DNSCacheUpdater::run() @ 0x946033 in /mnt/ch/ClickHouse/build/src/libclickhouse_interpreters.so
8. /mnt/ch/ClickHouse/contrib/libcxx/include/functional:0: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xc2c88 in /mnt/ch/ClickHouse/build/src/libclickhouse_core.so
9. /mnt/ch/ClickHouse/contrib/poco/Foundation/include/Poco/AtomicCounter.h:314: DB::BackgroundSchedulePool::threadFunction() @ 0xc4695 in /mnt/ch/ClickHouse/build/src/libclickhouse_core.so
10. /mnt/ch/ClickHouse/src/Core/BackgroundSchedulePool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xc4caa in /mnt/ch/ClickHouse/build/src/libclickhouse_core.so
11. /mnt/ch/ClickHouse/contrib/libcxx/include/functional:2210: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x16726e in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
12. /mnt/ch/ClickHouse/contrib/libcxx/include/memory:1655: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x1697c9 in /mnt/ch/ClickHouse/build/src/libclickhouse_common_io.so
13. start_thread @ 0x9259 in /usr/lib/libpthread-2.33.so
14. __clone @ 0xfe5e3 in /usr/lib/libc-2.33.so
 (version 21.9.1.1)
2021.07.22 17:39:03.808439 [ 694783 ] {} <Debug> DNSResolver: Updated DNS cache
```

**Expected behavior**

The element should be removed from the cache on error, so it's only shown once (or when accessing it again), but not in every refresh.

### LINKED ISSUE #29624: DNSError profile event doesn't increment after 21.9 during DNS error failure
**Describe what's wrong**
`DNSError` profile event doesn't increment after 21.9 during DNS error failure

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

yes, it reproduce on official docker image 21.9, and doesn't reproduce on 21.8

**How to reproduce**
- create cluster with 2 nodes which represents by DNS name in system.cluster
- replace /etc/resolv.conf on `node-0-0` (change nameserver for example), and make `node-0-1` is unresolved on `node-0-0`
- run on `node-0-0` 
```sql
SYSTEM DROP DNS CACHE; SELECT count() FROM cluster('cluster-name',system.metrics)
```
- run on `node-0-0` 
```sql
SELECT sum(ProfileEvent_DNSError) FROM system.metric_log
```

**Expected behavior**
Returned error, increment DNSError profile event counter and flush it into system.events and system.metric_log

**Actual behavior**
on 21.9, only system.errors code=198 `DNS_ERROR` increments `value`, system.events doesnt' increments

**Additional context**
there is our internal e2e monitoring test logs

SUCCESS from 21.8
```
               179ms              [bash] bash# kubectl exec --namespace=test -n test chi-test-cluster-for-alerts-default-0-0-0 -c clickhouse-pod -- clickhouse-client --echo -mn -q "SYSTEM DROP DNS CACHE; SELECT count() FROM cluster('all-sharded',system.metrics)"
               316ms              [bash] SYSTEM DROP DNS CACHE;
            1s 117ms              [bash] SELECT count() FROM cluster('all-sharded',system.metrics)
            1s 934ms              [bash] Received exception from server (version 21.8.8):
            1s 934ms              [bash] Code: 279. DB::Exception: Received from localhost:9000. DB::Exception: All connection tries failed. Log:
            1s 934ms              [bash]
            1s 935ms              [bash] Code: 210, e.displayText() = DB::NetException: Host not found: chi-test-cluster-for-alerts-default-0-1 (chi-test-cluster-for-alerts-default-0-1:9000) (version 21.8.8.29 (official build))
            1s 935ms              [bash] Code: 210, e.displayText() = DB::NetException: Host not found: chi-test-cluster-for-alerts-default-0-1 (chi-test-cluster-for-alerts-default-0-1:9000) (version 21.8.8.29 (official build))
            1s 935ms              [bash] Code: 210, e.displayText() = DB::NetException: Host not found: chi-test-cluster-for-alerts-default-0-1 (chi-test-cluster-for-alerts-default-0-1:9000) (version 21.8.8.29 (official build))
            1s 935ms              [bash]
            1s 935ms              [bash] : While executing Remote.
            1s 939ms              [bash] command terminated with exit code 23
            1s 942ms              [bash] bash# echo $?
            1s 943ms              [bash] 23
            1s 943ms              [bash] bash#
```
there is non zero counter flueshed
```            
            1s 945ms              [bash] bash# kubectl exec --namespace=test -n test chi-test-cluster-for-alerts-default-0-0-0 -c clickhouse-pod -- clickhouse-client --echo -mn -q "SELECT sum(ProfileEvent_DNSError) FROM system.metric_log"
             2s 96ms              [bash] SELECT sum(ProfileEvent_DNSError) FROM system.metric_log
            2s 100ms              [bash] 3
            2s 110ms              [bash] bash# echo $?
            2s 110ms              [bash] 0
```

FAILED from 21.9
different error code
```
              3m 49s              [bash] bash# kubectl exec --namespace=test -n test chi-test-cluster-for-alerts-default-0-0-0 -c clickhouse-pod -- clickhouse-client --echo -mn -q "SYSTEM DROP DNS CACHE; SELECT count() FROM cluster('all-sharded',system.metrics)"
              3m 49s              [bash] SYSTEM DROP DNS CACHE;
              3m 55s              [bash] SELECT count() FROM cluster('all-sharded',system.metrics)
              3m 55s              [bash] Received exception from server (version 21.9.4):
              3m 55s              [bash] Code: 198. DB::Exception: Received from localhost:9000. DB::Exception: Not found address of host: chi-test-cluster-for-alerts-default-0-1: While executing Remote. (DNS_ERROR)
              3m 55s              [bash] command terminated with exit code 198
              3m 55s              [bash] bash# echo $?
              3m 55s              [bash] 198
              3m 55s              [bash] bash#
```

different  DNSError behavior              
```
              3m 55s              [bash] bash# kubectl exec --namespace=test -n test chi-test-cluster-for-alerts-default-0-0-0 -c clickhouse-pod -- clickhouse-client --echo -mn -q "SELECT sum(ProfileEvent_DNSError) FROM system.metric_log;SELECT * FROM system.events WHERE event='DNSError' FORMAT Vertical; SELECT * FROM system.errors FORMAT Vertical"
              3m 55s              [bash] SELECT sum(ProfileEvent_DNSError) FROM system.metric_log;
              3m 55s              [bash] 0
              3m 55s              [bash] SELECT * FROM system.events WHERE event='DNSError' FORMAT Vertical;
              3m 55s              [bash] SELECT * FROM system.errors WHERE name='DNS_ERROR' FORMAT Vertical 
              3m 55s              [bash] Row 1:
              3m 55s              [bash] ──────
              3m 55s              [bash] name:               DNS_ERROR
              3m 55s              [bash] code:               198
              3m 55s              [bash] value:              120
              3m 55s              [bash] last_error_time:    2021-10-01 13:40:11
              3m 55s              [bash] last_error_message: Not found address of host: chi-test-cluster-for-alerts-default-0-1
              3m 55s              [bash] last_error_trace:   [154575226,155292345,155295895,155299725,292355997,292470903,292476068,292480622]
              3m 55s              [bash] remote:             0              
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Add `dns_max_consecutive_failures` setting to stop re-resolving cached DNS entries after a number of consecutive failures (5 by default).

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

It also improves logging since resolveIPAddressImpl was raising a different exception than the one expected (`DB::exception` vs `Poco::Net::DNSException`).

Note that I've decided to return true on update() when an entry is removed. This will trigger a cluster config reload (same behaviour as when an ip changes). 

Closes https://github.com/ClickHouse/ClickHouse/issues/26711
Closes https://github.com/ClickHouse/ClickHouse/issues/29624

### CODE REVIEW

**Comment by Algunenano** [comment]
Fixed the python style.

The docs seem broken in master, no idea why:
```
 python3.8 docs/tools/build.py --lang=en
INFO:root:Building website
INFO:root:Processing build/yandex_75d07a6cd96f49df.html
INFO:root:Processing build/google419fbd824d7ff97d.html
INFO:root:Processing build/404.html
INFO:root:Processing build/yandex_fffaa30ee00426bb.html
INFO:root:Processing build/index.html
INFO:root:Processing build/careers/index.html
INFO:root:Processing build/company/index.html
INFO:root:Processing build/benchmark/hardware/index.html
INFO:root:Processing build/benchmark/dbms/index.html
INFO:root:Processing build/support/case/index.html
INFO:root:Processing build/support/agreement/index.html
INFO:root:Processing build/support/policy/index.html
INFO:root:Processing build/legal/trademark-policy/index.html
INFO:root:Processing build/thank-you/index.html
INFO:root:Building en docs
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('Overview', 'hidden-71853c6197a6a7f222db0f1978c7cb232b87c5ee', 'Distinctive Features', 'Performance', 'History', 'Adopters')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('hidden-ebee0c0dd4c34a325a6082c6c18a1b954af5a4e4', 'Example Datasets', 'Installation', 'Tutorial', 'Playground')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('Introduction', 'GitHub Events', 'Web Analytics Data', 'Recipes Dataset', 'Star Schema Benchmark', 'WikiStat', 'Terabyte Click Logs from Criteo', 'AMPLab Big Data Benchmark', 'Brown University Benchmark', 'New York Taxi Data', 'OpenSky', 'UK Property Price Paid', 'Cell Towers', 'Menus', 'OnTime')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('Introduction', 'Command-Line Client', 'Native Interface (TCP)', 'HTTP Interface', 'gRPC Interface', 'MySQL Interface', 'Input and Output Formats', 'JDBC Driver', 'ODBC Driver', 'C++ Client Library', 'Third-Party')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('Third-Party Interfaces', 'Client Libraries', 'Integrations', 'Visual Interfaces', 'Proxies')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('hidden-35e41ae48409be55e0b740912b5ff02e0de9d27b', 'Table Engines', 'Database Engines')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('Integrations', 'Introduction', 'MergeTree Family', 'Log Family', 'Special')
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('Table Engines for Integrations', 'ODBC', 'JDBC', 'Hive', 'MySQL', 'MongoDB', 'HDFS', 'S3', 'SQLite', 'Kafka', 'EmbeddedRocksDB', 'RabbitMQ', 'PostgreSQL', 'ExternalDistributed', 'MaterializedPostgreSQL')
...
...
WARNING:mkdocs.config:Config value: 'nav'. Warning: Expected nav to be a list, got dict with keys ('2022', '2021', '2020', '2019', '2018', '2017')
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/ch/ClickHouse/docs/tools/build.py", line 125, in build_for_lang
    cfg = config.load_config(**raw_config)
  File "/home/raul/.local/lib/python3.8/site-packages/mkdocs/config/base.py", line 240, in load_config
    raise exceptions.Abort(
mkdocs.exceptions.Abort: Aborted with 48 Configuration Warnings in 'strict' mode!
```

File: src/Common/DNSResolver.cpp [hunk 1]
```diff
@@ -142,6 +142,9 @@ static String reverseResolveImpl(const Poco::Net::IPAddress & address)
 
 struct DNSResolver::Impl
 {
+    using HostWithConsecutiveFailures = std::unordered_map<String, UInt8>;
+    using AddressWithConsecutiveFailures = std::unordered_map<Poco::Net::IPAddress, UInt8>;
```
Comment (tavplubix) [inline src/Common/DNSResolver.cpp:146]: Should we throw an exception if `dns_max_consecutive_failures` is greater than 255?

File: src/Common/DNSResolver.cpp [hunk 2]
```diff
@@ -246,38 +249,69 @@ String DNSResolver::getHostName()
...
         {
-            tryLogCurrentException(__PRETTY_FUNCTION__);
+            tryLogCurrentException(log, __PRETTY_FUNCTION__);
         }
     }
 
     if (!lost_elems.empty())
-        LOG_INFO(log, fmt::runtime(log_msg), lost_elems);
+        LOG_INFO(log, fmt::runtime(notfound_log_msg), lost_elems);
+    if (elements_to_drop.size())
```
Comment (tavplubix) [inline src/Common/DNSResolver.cpp:297]: It makes sense to decrement failure counters and do not remove elements if `elements_to_drop.size() == elems.size()`. It may happen if DNS is not available for some reason and ClickHouse may stop working if DNS is not available and cache is cleared. However, trivial condition like `elements_to_drop.size() == elems.size()` will not work correctly, because names like `localhost` are resolved successfully even when DNS is not available. So I'm not sure what it the best solution, probably current one is ok.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Yep, documentation is broken, but I have no idea either. Maybe @rfraposa can help.

**Comment by rfraposa** [comment]
Good point. I need to update the `docs_check.py` script. Let me take a look

File: src/Common/DNSResolver.cpp [hunk 3]
```diff
@@ -118,7 +118,7 @@ static DNSResolver::IPAddresses resolveIPAddressImpl(const std::string & host)
     }
     catch (const Poco::Net::DNSException & e)
     {
-        LOG_ERROR(&Poco::Logger::get("DNSResolver"), "Cannot resolve host ({}), error {}: {}.", host, e.code(), e.message());
+        LOG_ERROR(&Poco::Logger::get("DNSResolver"), "Cannot resolve host ({}), error {}: {}.", host, e.code(), e.name());
         addresses.clear();
     }
```
[the remark this answers is not in the document]
Comment (Algunenano) [reply src/Common/DNSResolver.cpp:123]: It is done in the update process but it wasn't caught before because the exceptions where different. We can move it here and / or add a test

File: src/Common/DNSResolver.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Common/DNSResolver.cpp:146]: Great point. Initially I was using a static 5 so I used UInt8 but this should be a UInt32 to match the config. Then there is no need to throw

File: src/Common/DNSResolver.cpp (hunk 2 above)
Comment (Algunenano) [reply src/Common/DNSResolver.cpp:297]: In the default scenario it's 15 seconds * 5 times so more than a minute without DNS to flush the cache. I think it's unlikely and even if it happens it means they will be deleted and added again (either because they are part of a cluster or a query) so I don't think it's a big deal

Comment (tavplubix) [reply src/Common/DNSResolver.cpp:297]: Yeah, it's totally fine if it was a temporary short-time failure, elements will just be added again. But I mean that if DNS stops working at all then ClickHouse cluster will stop working too in 75 seconds. On the other hand, if you have a kind of Epic DNS Failure (I've seen some at Yandex) then broken ClickHouse is the least of your problems... So current solution looks ok for now.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests (asan, actions) [1/3] - `test_storage_postgresql_replica/test.py::test_abrupt_server_restart_while_heavy_replication` - Timeout, cc: @kssenii
Stress test (address, actions) - crash in `02248_nullable_custom_types_to_string`, incorrect version in `no-backward-compatibility-check` tag - #36008

Docs Check (actions) - recent changes in docs were reverted, let's try to restart - @Mergifyio update

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Ok, according to https://github.com/ClickHouse/ClickHouse/actions DocsCheck and DocsReleaseCheck are completely broken in master. Let's merge as is, because the changes in this PR looks fine.
