### PR TITLE
Avoid using Field for non-aggregated columns in SummingMergeTree

### LINKED ISSUE #78482: Corrupted SummingMergeTree table with Dynamic type
### Describe the bug

This issue has been around for a while. I guess the Dynamic type shouldn't be allowed in SummingMergeTree columns?

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/50002ecd-9097-4609-97f6-9176e04b9b58

### Error message and/or stacktrace

Stack trace:

```
<Error> TCPHandler: Code: 246. DB::Exception: SummingSortedAlgorithm failed to read row 1 of column 0 (c0): While executing SummingSortedTransform. (CORRUPTED_DATA), Stack trace (when copying this message, always include the lines below):

0. std::exception::exception[abi:ne190107]() @ 0x0000000017ab4ab4
1. base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x000000003563b1c0
2. src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000023b21b2b
3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000017968316
4. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x00000000179670af
5. src/Processors/Merges/Algorithms/SummingSortedAlgorithm.cpp:464: DB::SummingSortedAlgorithm::SummingMergedData::startGroup(std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*>>&, unsigned long) @ 0x0000000031fbff38
6. src/Processors/Merges/Algorithms/SummingSortedAlgorithm.cpp:762: DB::SummingSortedAlgorithm::merge() @ 0x0000000031fc6a35
7. src/Processors/Merges/IMergingTransform.h:137: DB::IMergingTransform<DB::SummingSortedAlgorithm>::work() @ 0x0000000030a656c4
8. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000003166cb0e
9. src/Processors/Executors/PipelineExecutor.cpp:296: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000003165803f
10. src/Processors/Executors/PipelineExecutor.cpp:262: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000031657205
11. src/Processors/Executors/PipelineExecutor.cpp:128: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000031656c0a
12. src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000031671b17
13. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000023cfd1ef
14. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000023d04e8a
15. ? @ 0x00007ffff7ca1e2e
16. ? @ 0x00007ffff7d33a4c
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid using Field for non-aggregated columns in SummingMergeTree. It could lead to unexpected errors with Dynamic/Variant types used in SummingMergeTree.

Closes https://github.com/ClickHouse/ClickHouse/issues/78482

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/q.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+set max_threads=1;
```
Comment (nikitamikhaylov) [inline tests/q.sql:1]: `tests/q.sql`? Shouldn't it be inside `tests/queries/0_stateless`?

Comment (Avogar) [reply tests/q.sql:1]: Oops, those test are not from this PR... How did I not notice it... Thanks

**Review by nikitamikhaylov — APPROVED** [review]
I'd better rewritten these functions completely not to use Fields at all, but seems not quite reasonable for the fix.

**Comment by Avogar** [comment]
[Stress test (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79051&sha=d690865aff2d9c6f7927838ddbc4f5276604e25d&name_0=PR&name_1=Stress%20test%20%28amd_debug%29) - https://github.com/ClickHouse/ClickHouse/issues/80123
