### PR TITLE
setting to use Variant data type during schema inference

### LINKED ISSUE #62814: Add a setting to use Variant data type during schema inference when column/array has values with different types
Examples:
```
:) select arr, toTypeName(arr) from format('JSONEachRow', '{"arr" : [1, "Hello", {"a" : 32}]}')
   ┌─arr──────────────┬─toTypeName(arr)────────────────────────────────────────────────────┐
1. │ (1,'Hello',(32)) │ Tuple(Nullable(Int64), Nullable(String), Tuple(a Nullable(Int64))) │
   └──────────────────┴────────────────────────────────────────────────────────────────────┘
```

Instead, it can be `Array(Variant(Int64, String, Tuple(a Nullable(Int64))))`.

```
:) select x, toTypeName(x) from format('JSONEachRow', '{"x" : 42}, {"x" : "Hello"}')

   ┌─x─────┬─toTypeName(x)────┐
1. │ 42    │ Nullable(String) │
2. │ Hello │ Nullable(String) │
   └───────┴──────────────────┘
```

It can be `Variant(Int64, String)`.

```
:) select x, toTypeName(x) from format('JSONEachRow', '{"x" : [1, 2, 3]}, {"x" : {"a" : 42}}')

Received exception:
Code: 636. DB::Exception: The table structure cannot be extracted from a JSONEachRow format file. Error:
Code: 53. DB::Exception: Automatically defined type Tuple(a Int64) for column 'x' in row 1 differs from type defined by previous rows: Array(Int64). You can specify the type for this column using setting schema_inference_hints. (TYPE_MISMATCH) (version 24.4.1.1).
You can specify the structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)

```

It can be `Variant(Array(Int64), Tuple(a Int64))`

### PR DESCRIPTION
**Pull request by Blargian**
Closes #62814. Adds setting `input_format_try_infer_variants`. 

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Adds a setting `input_format_try_infer_variants` which allows Variant type to be inferred during schema inference for text formats when there is more than one possible type for column/array elements.

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 467366af990215e11b4b0309b90b3e6d9ebca5fd with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63798/467366af990215e11b4b0309b90b3e6d9ebca5fd/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Maybe `input_format_json_infer_variant_from_multi_type_array`?

**Comment by Blargian** [comment]
@Avogar mostly working, except for the first example you gave `Array(Variant(Int64, String, Tuple(a Nullable(Int64))))` I am getting instead `Array(Variant(Int64, String, Tuple(a Int64)))` - I still need to fix that.

File: src/Core/Settings.h [hunk 1]
```diff
@@ -1066,6 +1066,7 @@ class IColumn;
     M(Bool, input_format_json_defaults_for_missing_elements_in_named_tuple, true, "Insert default value in named tuple element if it's missing in json object", 0) \
     M(Bool, input_format_json_throw_on_bad_escape_sequence, true, "Throw an exception if JSON string contains bad escape sequence in JSON input formats. If disabled, bad escape sequences will remain as is in the data", 0) \
     M(Bool, input_format_json_ignore_unnecessary_fields, true, "Ignore unnecessary fields and not parse them. Enabling this may not throw exceptions on json strings of invalid format or with duplicated fields", 0) \
+    M(Bool, input_format_json_infer_variant_from_multi_type_array, false, "Try to infer variant type rather than tuple when column/array has multiple", 0) \
```
Comment (Avogar) [inline src/Core/Settings.h:1069]:
```suggestion
    M(Bool, input_format_try_infer_variants, false, "Try to infer Variant type in text formats when there are more than one possible type for column/array element", 0) \
```

Let's do it not only for JSON arrays, but for all text input formats in all cases when there are multiple types for single column.

For example in CSV format:
```csv
1,Hello World!
2,"[1,2,3]"
3,"2020-01-01"
```
We will infer columns `c1 Int64, c2 Variant(String, Array(Nullable(Int64)), Date)`.

File: src/Formats/SchemaInferenceUtils.cpp [hunk 2]
```diff
@@ -649,6 +666,11 @@ namespace
 
             /// Check settings specific for JSON formats.
 
+            if (settings.json.infer_variant_from_multi_type_array)
+            {
+                transformVariant(data_types, type_indexes);
+            }
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:672]: This check sholuld be the last one in this method, not the first one. We could change the data types in other methods below. And we should do it not only for JSON but for all types

File: src/Formats/SchemaInferenceUtils.cpp [hunk 3]
```diff
@@ -307,6 +308,22 @@ namespace
         type_indexes.erase(TypeIndex::UInt64);
     }
 
+    /// if setting input_format_json_infer_variant_from_multi_type_array is true
+    /// and nested types are not equal then we convert to type variant.
+    void transformVariant(DataTypes & data_types, TypeIndexesSet & type_indexes)
+    {
+        auto variant_type = std::make_shared<DataTypeVariant>(data_types);
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:315]: We should check if types are not the same before transforming it to `Variang`

File: src/Formats/SchemaInferenceUtils.cpp [hunk 4]
```diff
@@ -307,6 +308,22 @@ namespace
...
+        /// replace separate types with a single variant type
+        data_types.clear();
+        type_indexes.clear();
+        data_types.push_back(variant_type);
+        type_indexes.insert(TypeIndex::Variant);
+
+        /// make the second type variant as well
+        data_types.push_back(variant_type);
+        type_indexes.insert(TypeIndex::Variant);
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:324]: We might have any number of types, not only 2. We should iterate over `data_types` and replace each type with `Variant`

File: src/Formats/SchemaInferenceUtils.cpp [hunk 5]
```diff
@@ -677,6 +699,11 @@ namespace
             if constexpr (!is_json)
                 return;
 
+            if (settings.json.infer_variant_from_multi_type_array)
+            {
+                transformVariant(data_types, type_indexes);
+            }
+
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:706]: The same, this transformation should be the last one

File: src/Formats/SchemaInferenceUtils.cpp [hunk 6]
```diff
@@ -1482,6 +1517,20 @@ DataTypePtr makeNullableRecursively(DataTypePtr type)
...
     }
 
+    if (which.isVariant())
+    {
+        const auto * variant_type = assert_cast<const DataTypeVariant *>(type.get());
+        DataTypes nested_types;
+        for (const auto & nested_type: variant_type->getVariants())
+        {
+            /// unlike tuple or array, here we do not want to make any of the variants nullable
+            /// so we do not call makeNullableRecursively
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:1527]: We don't want to make variants Nullable, but we want to make nested types inside variants Nullable. For example, `Array(UInt64)` -> `Array(Nullable(UInt64))`. So, we should call `makeNullableRecursively` when `!nested_type->lowCardinality() && nested_type->haveSubtypes()`

File: src/Core/Settings.h (hunk 1 above)
Comment (Blargian) [reply src/Core/Settings.h]: @Avogar sorry for the delay! I've pushed the latest changes now. At the moment having a little trouble figuring out how to properly infer variant for other formats as well. For `SELECT c1, toTypeName(c1), c2, toTypeName(c2) FROM format('CSV', '1,Hello World!\n2,"[1,2,3]"\n3,"2020-01-01"\n') FORMAT Pretty;` when I step through the code with debugger I can see it hitting the variant transformation but in the end `Nullable(String)` gets inferred still.

File: src/Formats/SchemaInferenceUtils.cpp [hunk 7]
```diff
@@ -307,6 +318,54 @@ namespace
         type_indexes.erase(TypeIndex::UInt64);
     }
 
+    /// if setting 'try_infer_variant' is true then we convert to type variant.
+    void transformVariant(DataTypes & data_types, TypeIndexesSet & type_indexes)
+    {
+        auto typesAreEqual = checkIfTypesAreEqual(data_types);
+        auto typesContainVariant = checkIfTypesContainVariant(data_types);
+        if (typesAreEqual)
+            return;
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:327]:
```suggestion
        auto types_are_equal = checkIfTypesAreEqual(data_types);
        auto types_contain_variant = checkIfTypesContainVariant(data_types);
        if (types_are_equal)
            return;
```
We don't use `camelCase` for variable names

File: src/Formats/SchemaInferenceUtils.cpp [hunk 8]
```diff
@@ -307,6 +318,54 @@ namespace
...
+
+        DataTypes new_data_types;
+        TypeIndexesSet new_type_indexes;
+        std::shared_ptr<DataTypeVariant> variant_type;
+
+        /// extract the nested types of variant and make a new variant with the nested types and the other type.
+        /// eg. Type 1: variant<String, Array>, Type 2: Date -> variant<String, Array, Date>.
+        if (typesContainVariant)
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:335]:
```suggestion
        if (checkIfTypesContainVariant(data_types))
```

File: src/Formats/SchemaInferenceUtils.cpp [hunk 9]
```diff
@@ -307,6 +318,54 @@ namespace
...
+        {
+            DataTypes extracted_types;
+            for (size_t i=0; i<data_types.size(); i++)
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:338]:
```suggestion
            for (size_t i = 0; i < data_types.size(); i++)
```

File: src/Formats/SchemaInferenceUtils.cpp (hunk 8 above)
Comment (Avogar) [reply src/Formats/SchemaInferenceUtils.cpp:335]: Actually, I think we don't need this check `checkIfTypesContainVariant` and 2 branches. We can do it in one loop. Also we could have more than 1 Variant type and we should handle it:
```c++
DataTypes variant_types;
for (const auto & type : data_types)
{
    if (const auto * variant_type = typeid_cast<const DataTypeVariant *>(type.get()))
    {
        const auto & current_variants = variant_type->getVariants();
        variant_types.insert(variant_types.end(), current_variants.begin(), current_variants.end())
    }
    else
    {
        variant_types.push_back(type);
    }
}

variant_type = std::make_shared<DataTypeVariant>(variant_types);
```

File: src/Formats/SchemaInferenceUtils.cpp [hunk 10]
```diff
@@ -307,6 +318,54 @@ namespace
...
+        {
+            new_data_types.push_back(variant_type);
+            new_type_indexes.insert(TypeIndex::Variant);
+            i++;
+        }
+
+        data_types.clear();
+        type_indexes.clear();
+        data_types = new_data_types;
+        type_indexes = new_type_indexes;
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:366]:
```suggestion
        for (auto & type : data_types)
            type = variant_type;
        type_indexes = {TypeIndex::Variant};
```

File: src/Formats/SchemaInferenceUtils.cpp [hunk 11]
```diff
@@ -644,6 +703,9 @@ namespace
             if (settings.try_infer_dates || settings.try_infer_datetimes)
                 transformDatesAndDateTimes(data_types, type_indexes);
 
+            if (settings.try_infer_variant)
+                transformVariant(data_types, type_indexes);
+
             if constexpr (!is_json)
                 return;
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:710]:
```suggestion
            if constexpr (!is_json)
            {
                if (settings.try_infer_variant)
                    transformVariant(data_types, type_indexes);
                return;
            }
```

File: src/Formats/SchemaInferenceUtils.cpp [hunk 12]
```diff
@@ -674,6 +740,9 @@ namespace
             /// If there is at least one non Nothing type, change all Nothing types to it.
             transformNothingComplexTypes(data_types, type_indexes);
 
+            if (settings.try_infer_variant)
+                transformVariant(data_types, type_indexes);
+
             if constexpr (!is_json)
                 return;
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:747]:
```suggestion
            if constexpr (!is_json)
            {
                if (settings.try_infer_variant)
                    transformVariant(data_types, type_indexes);
                return;
            }
```

File: src/Formats/SchemaInferenceUtils.cpp [hunk 13]
```diff
@@ -1482,6 +1562,22 @@ DataTypePtr makeNullableRecursively(DataTypePtr type)
...
 
+    if (which.isVariant())
+    {
+        const auto * variant_type = assert_cast<const DataTypeVariant *>(type.get());
+        DataTypes nested_types;
+        for (const auto & nested_type: variant_type->getVariants())
+        {
+            auto is_low_cardinality = nested_type->lowCardinality();
+            auto has_sub_types = nested_type->haveSubtypes();
+            if (!is_low_cardinality && has_sub_types)
```
Comment (Avogar) [inline src/Formats/SchemaInferenceUtils.cpp:1573]:
```suggestion
            if (!nested_type->lowCardinality() && nested_type->haveSubtypes())
```
Condition is quite small, no need to create extra bool variables for each part

File: src/Core/SettingsChangesHistory.h [hunk 14]
```diff
@@ -111,6 +111,8 @@ static const std::map<ClickHouseVersion, SettingsChangesHistory::SettingsChanges
               {"http_max_chunk_size", 0, 0, "Internal limitation"},
               {"prefer_external_sort_block_bytes", 0, DEFAULT_BLOCK_SIZE * 256, "Prefer maximum block bytes for external sort, reduce the memory usage during merging."},
               {"input_format_force_null_for_omitted_fields", false, false, "Disable type-defaults for omitted fields when needed"},
+              {"output_format_pretty_preserve_border_for_multiline_string", 1, 1, "Applies better rendering for multiline strings."},
```
Comment (Avogar) [inline src/Core/SettingsChangesHistory.h:114]: I guess it was added by mistake or bad conflict resolution. Please, remove it

File: src/Formats/SchemaInferenceUtils.cpp (hunk 13 above)
Comment (Blargian) [reply src/Formats/SchemaInferenceUtils.cpp:1573]: @Avogar I split them up here because the `&&` operator seems to have a [short circuit behaviour](https://stackoverflow.com/questions/5211961/how-does-c-handle-short-circuit-evaluation) in C++. For `if (!nested_type->lowCardinality() && nested_type->haveSubtypes())`  if `lowCardinality()` evaluates false then `haveSubtypes()` won't get checked. 

But probably there is a less ugly looking way to get around this problem.

Comment (Avogar) [reply src/Formats/SchemaInferenceUtils.cpp:1544]: > if lowCardinality() evaluates false then haveSubtypes() won't get checked.

It's actually the other way, when `lowCardinality()` evaluates true, `!lowCardinality()` will be false and `haveSubtypes()` won't be called. But what is the problem with it? It's totally ok and expected.

Comment (Blargian) [reply src/Formats/SchemaInferenceUtils.cpp:1544]: Yes, you are right

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
`Stateful tests (asan) — Tests are not finished, fail: 1, passed: 130, skipped: 1` - https://github.com/ClickHouse/ClickHouse/issues/57508

**Comment by Avogar** [comment]
Every time I want to merge this PR there is a conflict in the `SettingsChangesHistory` ...
Sorry for that, will try to merge soon
