### PR TITLE
Fix aggregate function combinator `-If` with `Nullable` filter argument

### LINKED ISSUE #27073: Invalid sumIf behavior with nullable arguments
**Describe the bug**

`sumIf` returns incorrect results in some cases with Nullable arguments.

**How to reproduce**

* Which ClickHouse server version to use
Latest master/arcadia version

* Queries to run that lead to unexpected result
```sql
:) select sumIf(toFloat64OrZero(b), a = 0) as r1, sumIf(cast(b as Float), a = 0) as r2, sum(if(a = 0, toFloat64OrZero(b), 0)) as r3 from (select arrayJoin([1, 2, 3, NULL]) as a, toNullable('10.0') as b)

SELECT
    sumIf(toFloat64OrZero(b), a = 0) AS r1,
    sumIf(CAST(b, 'Float'), a = 0) AS r2,
    sum(if(a = 0, toFloat64OrZero(b), 0)) AS r3
FROM
(
    SELECT
        arrayJoin([1, 2, 3, NULL]) AS a,
        toNullable('10.0') AS b
)

Query id: 2e4e320d-e52a-4514-bc6f-118485558191

┌─r1─┬─r2─┬─r3─┐
│ 10 │  0 │  0 │
└────┴────┴────┘
```
**Expected behavior**

All results are 0.

**Additional context**

It breaks when null values in Nullable column are compared with `assumeNotNull` from this column.
It also only breaks when first argument is Nullable too.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Aggregate function combinator `-If` did not correctly process `Nullable` filter argument. This closes #27073.

CC @Algunenano

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 1]
```diff
@@ -40,28 +40,6 @@ class AggregateFunctionCombinatorIf final : public IAggregateFunctionCombinator
     }
 };
 
-/** Given an array of flags, checks if it's all zeros
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:43]: @Algunenano it's strange that this code was faster than `memoryIsByte` or `memoryIsZero`. The statement about `require allocating memory` is wrong, because `memcmp` does not allocate memory.

Nevertheless, even if this code is faster, it is a duplicate, and you should edit `memoryIsZero` and `memoryIsByte` instead.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 2]
```diff
@@ -136,28 +126,36 @@ class AggregateFunctionIfNullUnary final
         const IColumn * columns_param[] = {&column->getNestedColumn()};
 
         const IColumn * filter_column = columns[num_arguments - 1];
-        if (const ColumnNullable * nullable_column = typeid_cast<const ColumnNullable *>(filter_column))
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:139]: Expensive cast in inner loop - not good.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 3]
```diff
@@ -136,28 +126,36 @@ class AggregateFunctionIfNullUnary final
...
-            filter_column = nullable_column->getNestedColumnPtr().get();
-        if constexpr (result_is_nullable)
+
+        const UInt8 * filter_values = nullptr;
+        const UInt8 * filter_null_map = nullptr;
+
+        if (filter_is_nullable)
         {
-            /// We need to check if there is work to do as otherwise setting the flag would be a mistake,
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:143]: I did not understand it, something strange.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 4]
```diff
@@ -136,28 +126,36 @@ class AggregateFunctionIfNullUnary final
...
+
         /// Combine the 2 flag arrays so we can call a simplified version (one check vs 2)
         /// Note that now the null map will contain 0 if not null and not filtered, or 1 for null or filtered (or both)
-        const auto * filter_flags = assert_cast<const ColumnUInt8 *>(filter_column)->getData().data();
+
         auto final_nulls = std::make_unique<UInt8[]>(batch_size);
-        for (size_t i = 0; i < batch_size; ++i)
-            final_nulls[i] = (!!null_map[i]) | (!filter_flags[i]);
+
+        if (filter_null_map)
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:147]: Here is the fix.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 5]
```diff
@@ -367,10 +365,14 @@ AggregateFunctionPtr AggregateFunctionIf::getOwnNullAdapter(
     const AggregateFunctionPtr & nested_function, const DataTypes & arguments,
     const Array & params, const AggregateFunctionProperties & properties) const
 {
-    bool return_type_is_nullable = !properties.returns_default_when_only_null && getReturnType()->canBeInsideNullable();
-    size_t nullable_size = std::count_if(arguments.begin(), arguments.end(), [](const auto & element) { return element->isNullable(); });
-    return_type_is_nullable &= nullable_size != 1 || !arguments.back()->isNullable();   /// If only condition is nullable. we should non-nullable type.
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:372]: The code was extremely difficult to read.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 6]
```diff
@@ -380,7 +382,7 @@ AggregateFunctionPtr AggregateFunctionIf::getOwnNullAdapter(
         }
         else
         {
-            if (serialize_flag)
+            if (need_to_serialize_flag)
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:385]: I have renamed the variable, because the old name was atrocious.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 7]
```diff
@@ -105,17 +102,10 @@ class AggregateFunctionIfNullUnary final
         , name(name_)
     {
         if (num_arguments == 0)
-            throw Exception("Aggregate function " + getName() + " require at least one argument",
-                ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
-    }
-
-    static inline bool singleFilter(const IColumn ** columns, size_t row_num, size_t num_arguments)
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:112]: This function was public for no reason.

File: src/AggregateFunctions/AggregateFunctionFactory.cpp [hunk 8]
```diff
@@ -70,22 +70,22 @@ static DataTypes convertLowCardinalityTypesToNested(const DataTypes & types)
 AggregateFunctionPtr AggregateFunctionFactory::get(
     const String & name, const DataTypes & argument_types, const Array & parameters, AggregateFunctionProperties & out_properties) const
 {
-    auto type_without_low_cardinality = convertLowCardinalityTypesToNested(argument_types);
+    auto types_without_low_cardinality = convertLowCardinalityTypesToNested(argument_types);
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionFactory.cpp:73]: Also renamed the variable, because the old name was wrong.

File: src/AggregateFunctions/AggregateFunctionIf.cpp (hunk 1 above)
Comment (Algunenano) [reply src/AggregateFunctions/AggregateFunctionIf.cpp:43]: At that point I didn't know about `memoryIsZero` and `memoryIsByte`. I think I saw it a few weeks ago and thought that I should have used that instead.

I think (some time has passed so I don't remember what I was thinking) that by `require allocating memory` I meant that to do a memcmp you need something (an array full of 0's) to compare against and creating that requires an allocation (in heap or in the stack).

In any case, yes, it should use `memoryIsZero` and it performance is worse then move add the unrolled version there.

File: src/AggregateFunctions/AggregateFunctionIf.cpp (hunk 3 above)
Comment (Algunenano) [reply src/AggregateFunctions/AggregateFunctionIf.cpp:143]: I think this was trying to fix the bug (or a similar one) in a different place. I needed to check if the filter had any values to check because otherwise a) there is no work to do and b) the result, for nullable types, should be NULL. The problem came from using `null_map` and not `final_nulls` to do the check though.

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 9]
```diff
@@ -136,28 +126,36 @@ class AggregateFunctionIfNullUnary final
...
+        else
+            for (size_t i = 0; i < batch_size; ++i)
+                final_nulls[i] = (!!null_map[i]) | (!filter_values[i]);
 
         this->nested_function->addBatchSinglePlaceNotNull(
             batch_size, this->nestedPlace(place), columns_param, final_nulls.get(), arena, -1);
 
         if constexpr (result_is_nullable)
-            if (!memoryIsByte(null_map, batch_size, 1))
+            if (!memoryIsByte(final_nulls.get(), batch_size, 1))
```
Comment (Algunenano) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:158]: Does it make sense to move the nested function call here? It seems like we could avoid it in some cases since we are going to ignore the result, right?

**Review by Algunenano — COMMENTED** [review]
One thing I'm surprised by is that the fix is only present in `addBatchSinglePlace` but the bug was already there before the function gained this implementation. Shouldn't there be a similar fix in the `add` function?

File: src/AggregateFunctions/AggregateFunctionIf.cpp [hunk 10]
```diff
@@ -92,8 +71,26 @@ class AggregateFunctionIfNullUnary final
...
+    {
+        const IColumn * filter_column = columns[num_arguments - 1];
+
+        if (filter_is_nullable)
+        {
+            const ColumnNullable * nullable_column = assert_cast<const ColumnNullable *>(filter_column);
+            filter_column = nullable_column->getNestedColumnPtr().get();
+            const UInt8 * filter_null_map = nullable_column->getNullMapData().data();
+
+            return assert_cast<const ColumnUInt8 &>(*filter_column).getData()[row_num] && !filter_null_map[row_num];
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionIf.cpp:85]: Here is the fix for `add` function.

File: src/AggregateFunctions/AggregateFunctionIf.cpp (hunk 9 above)
Comment (alexey-milovidov) [reply src/AggregateFunctions/AggregateFunctionIf.cpp:156]: 58bb1ffecf

**Comment by alexey-milovidov** [comment]
No difference in perf tests.

File: src/AggregateFunctions/AggregateFunctionIf.cpp (hunk 9 above)
Comment (Algunenano) [reply src/AggregateFunctions/AggregateFunctionIf.cpp:156]: ❤️
