### PR TITLE
Clickhouse-local fixes

### LINKED ISSUE #39395: Clickhouse local doesn't come up with --config-file option
I am unable to start the Clickhouse-local with --config-file option , However clickhouse-server is running with same configuration xml files.

I am getting below error :
image

After debugging , It seems that Clickhouse-local is searching for "<users_config>" in config() and if not , setting the user_config_path to config.xml. Since config.xml doesn't have any user related storage info, throwing error.
https://github.com/ClickHouse/ClickHouse/blob/master/programs/local/LocalServer.cpp#L328

Adding <users_config> in config.xml loaded the user configuration successfully , However it fails with default database exists error. Since Clickhouse-local already creates default database as part of DatabaseMemory and try to create database again here.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/loadMetadata.cpp#L89
image

PS: , In clickhouse-server, CH automatically searches for user.xml in same path as in config.xml. There is no constraint with <users_config> tag .

### PR DESCRIPTION
**Pull request by HeenaBansal2009**
### Changelog category (leave one):
- Not for changelog 

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This PR fixes #39395 where Clickhouse-local doesn't come up with --config-file option . However Clickhouse-server starts with same configuration without error.

### CODE REVIEW

File: programs/local/LocalServer.cpp [hunk 1]
```diff
@@ -323,12 +323,30 @@ void LocalServer::setupUsers()
...
-    if (config().has("users_config") || config().has("config-file") || fs::exists("config.xml"))
+    if (config().has("config-file") || fs::exists("config.xml"))
     {
-        const auto users_config_path = config().getString("users_config", config().getString("config-file", "config.xml"));
-        ConfigProcessor config_processor(users_config_path);
-        const auto loaded_config = config_processor.loadConfig();
-        users_config = loaded_config.configuration;
+        String config_path = config().getString("config-file","");
+        bool has_user_directories = config().has("user_directories");
+        const auto config_dir = std::filesystem::path{config_path}.remove_filename().string();
```
Comment (kssenii) [inline programs/local/LocalServer.cpp:330]: why remove_filename?

File: programs/local/LocalServer.cpp [hunk 2]
```diff
@@ -323,12 +323,30 @@ void LocalServer::setupUsers()
...
+        String users_config_path = config().getString("users_config","");
```
Comment (kssenii) [inline programs/local/LocalServer.cpp:331]:
```suggestion
        String users_config_path = config().getString("users_config", "");
```

File: programs/local/LocalServer.cpp [hunk 3]
```diff
@@ -323,12 +323,30 @@ void LocalServer::setupUsers()
...
+        {
+            if (users_config_path.empty())
+            {
+                if (!has_user_directories)
+                    users_config_path = config_path;
+            }
+            if (has_user_directories)
+                users_config_path = config().getString("user_directories.users_xml.path","");
+
+            if (std::filesystem::path{users_config_path}.is_relative() && std::filesystem::exists(config_dir + users_config_path))
```
Comment (kssenii) [inline programs/local/LocalServer.cpp:344]:
```suggestion
            if (fs::path{users_config_path}.is_relative() && fs::exists(fs::path(config_dir) / users_config_path))
```
lets add `namespace fs = std::filesystem` on top of this file

File: programs/local/LocalServer.cpp [hunk 4]
```diff
@@ -323,12 +323,30 @@ void LocalServer::setupUsers()
...
+                users_config_path = config_dir + users_config_path;
```
Comment (kssenii) [inline programs/local/LocalServer.cpp:345]:
```suggestion
                users_config_path = fs::path(config_dir) / users_config_path;
```

File: programs/local/LocalServer.cpp [hunk 5]
```diff
@@ -323,12 +323,30 @@ void LocalServer::setupUsers()
...
+            users_config = getConfigurationFromXMLString(minimal_default_user_xml);
+        else
+        {
+            if (users_config_path.empty())
+            {
+                if (!has_user_directories)
+                    users_config_path = config_path;
+            }
+            if (has_user_directories)
+                users_config_path = config().getString("user_directories.users_xml.path","");
```
Comment (kssenii) [inline programs/local/LocalServer.cpp:342]:
```suggestion
                users_config_path = config().getString("user_directories.users_xml.path", "");
```

File: programs/local/LocalServer.cpp (hunk 3 above)
Comment (kssenii) [inline programs/local/LocalServer.cpp:344]: Also looks like in this line it is possible that `users_config_path` is and empty string. Then it will work incorrectly.

File: programs/local/LocalServer.cpp (hunk 5 above)
Comment (kssenii) [inline programs/local/LocalServer.cpp:342]: Looks a little inconsistent, may be like this?
```suggestion
            if (users_config_path.empty())
            {
                if (has_user_directories)
                    users_config_path = config().getString("user_directories.users_xml.path","");
                else
                    users_config_path = config_path;
            }
```

File: programs/local/LocalServer.cpp [hunk 6]
```diff
@@ -323,12 +323,30 @@ void LocalServer::setupUsers()
...
-        const auto users_config_path = config().getString("users_config", config().getString("config-file", "config.xml"));
-        ConfigProcessor config_processor(users_config_path);
-        const auto loaded_config = config_processor.loadConfig();
-        users_config = loaded_config.configuration;
+        String config_path = config().getString("config-file","");
+        bool has_user_directories = config().has("user_directories");
+        const auto config_dir = std::filesystem::path{config_path}.remove_filename().string();
+        String users_config_path = config().getString("users_config","");
+        if (users_config_path.empty() && !has_user_directories)
+            users_config = getConfigurationFromXMLString(minimal_default_user_xml);
```
Comment (kssenii) [inline programs/local/LocalServer.cpp:333]: why not just like this?
```suggestion
        if (users_config_path.empty())
            users_config = getConfigurationFromXMLString(minimal_default_user_xml);
```

File: programs/local/LocalServer.cpp [hunk 7]
```diff
@@ -575,7 +593,8 @@ void LocalServer::processConfig()
       * Otherwise, metadata of temporary File(format, EXPLICIT_PATH) tables will pollute metadata/ directory;
       *  if such tables will not be dropped, clickhouse-server will not be able to load them due to security reasons.
       */
-    std::string default_database = config().getString("default_database", "_local");
+    std::string default_database = config().getString("default_database", "");
+    default_database = default_database + "_local";
```
[the remark this answers is not in the document]
Comment (HeenaBansal2009) [reply programs/local/LocalServer.cpp:597]: hmm,  The cases when current_database is default. Since default database is already exist, it throws error " default database is already exists"?
 It fails with default database exists error. Since Clickhouse-local already creates default daItabase as part of DatabaseMemory and try to create database again here.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/loadMetadata.cpp#L89
image

File: programs/local/LocalServer.cpp (hunk 1 above)
Comment (HeenaBansal2009) [reply programs/local/LocalServer.cpp:330]: We want to extract the directory path from the config-file path . Not using remove_filename() will return the config-file path which is something /etc/clickhouse-server/config.xml , However we need only /etc/clickhouse-server.
Please correct me if I am wrong.

File: programs/local/LocalServer.cpp (hunk 3 above)
Comment (HeenaBansal2009) [reply programs/local/LocalServer.cpp:344]: user_config_path cannot be empty considering the top if condition :
if (config().has("config-file") || fs::exists("config.xml"))

File: programs/local/LocalServer.cpp (hunk 6 above)
Comment (HeenaBansal2009) [reply programs/local/LocalServer.cpp:333]: hmm.. if user defined config-file option but config file doesn't have  <users_config> and <users_directories> Then we are  good to define minimal_default_user . 
OR 
--config-option is not defined i.e.. config().has("config-file", "") is empty , then also we should add minimal_default_user.
Please correct me if I am wrong .

**Comment by HeenaBansal2009** [comment]
@kssenii , Please suggest on above comments.

File: programs/local/LocalServer.cpp (hunk 3 above)
Comment (kssenii) [reply programs/local/LocalServer.cpp:344]: It can still be empty, at least because of the line `users_config_path = config().getString("user_directories.users_xml.path","");` -- it is not checked that the value exists. 

Let's rewrite the code like this:
```
if (config().has("config-file") || fs::exists("config.xml"))
    {
        String config_path = config().getString("config-file", "");
        bool has_user_directories = config().has("user_directories");
        const auto config_dir = std::filesystem::path{config_path}.remove_filename().string();
        String users_config_path = config().getString("users_config", "");

        if (users_config_path.empty() && has_user_directories)
        {
            users_config_path = config().getString("user_directories.users_xml.path");
            if (fs::path(users_config_path).is_relative()
                 && fs::exists(fs::path(config_dir) / users_config_path))
            users_config_path = fs::path(config_dir) / users_config_path;
        }

        if (users_config_path.empty())
        {
            users_config = getConfigurationFromXMLString(minimal_default_user_xml);
        } 
        else 
        {
            ConfigProcessor config_processor(users_config_path);
            const auto loaded_config = config_processor.loadConfig();
            users_config = loaded_config.configuration;
        }
    }
    else
        users_config = getConfigurationFromXMLString(minimal_default_user_xml);
```

**Review by kssenii — APPROVED** [review]

**Comment by HeenaBansal2009** [comment]
@kssenii , stress testcase failure and integration testcase failure doesn't seems related to this PR. 
Are we good to merge this PR?
