### PR TITLE
Do not materialize column after eliminating filter when ColumnConst comes from the inputs

### LINKED ISSUE #90569: Logical error: 'Block structure mismatch in after optimizationremoveUnusedColumns stream: different columns:
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90545&sha=ded0094e164affd03747e0fcb26b3160baa5ced8&name_0=PR&name_1=AST+fuzzer+%28amd_debug%29

How to reproduce:
```sql
SELECT *
FROM
(
    SELECT materialize(toUInt256(2))
    UNION ALL
    SELECT DISTINCT 1

)
GROUP BY
    ignore(lessOrEquals(18, isNotNull(toLowCardinality(10)))),
    1
HAVING ignore(isZeroOrNull(5))
```

```
2025.11.21 13:08:38.014720 [ 1117453 ] {642bf7c5-b7d9-437a-a3b3-4b354cf815ac} <Fatal> : Logical error: 'Block structure mismatch in after optimizationremoveUnusedColumns stream: different columns:
ignore(_CAST(0_UInt8, 'UInt8'_String)) UInt8 Const(size = 0, UInt8(size = 1))
ignore(_CAST(0_UInt8, 'UInt8'_String)) UInt8 UInt8(size = 0)'.
2025.11.21 13:08:38.215858 [ 1117453 ] {642bf7c5-b7d9-437a-a3b3-4b354cf815ac} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000259de972
1. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015bea469
2. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d913c4e
3. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d913791
4. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.h:141: DB::Exception::Exception<std::basic_string_view<char, std::char_traits<char>>&, String, String>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type, std::type_identity<String>::type, std::type_identity<String>::type>, std::basic_string_view<char, std::char_traits<char>>&, String&&, String&&) @ 0x000000001a76ae76
5. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Core/Block.cpp:44: void DB::onError<void, std::basic_string_view<char, std::char_traits<char>>&, String, String>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type, std::type_identity<String>::type, std::type_identity<String>::type>, std::basic_string_view<char, std::char_traits<char>>&, String&&, String&&) @ 0x000000001a76898a
6. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Core/Block.cpp:105: void DB::checkColumnStructure<void>(DB::ColumnWithTypeAndName const&, DB::ColumnWithTypeAndName const&, std::basic_string_view<char, std::char_traits<char>>, bool, int) @ 0x000000001a75ea65
7. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Core/Block.cpp:155: void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::basic_string_view<char, std::char_traits<char>>, bool) @ 0x000000001a76659d
8. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:26: DB::(anonymous namespace)::checkHeaders(DB::QueryPlan::Node const&, std::basic_string_view<char, std::char_traits<char>>, unsigned long) @ 0x000000001fd83cdf
9. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:126: DB::QueryPlanOptimizations::optimizeTreeFirstPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x000000001fd832d9
10. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Processors/QueryPlan/QueryPlan.cpp:576: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001fca2bca
11. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Processors/QueryPlan/QueryPlan.cpp:180: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001fca2500
12. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x000000001bca37e5
13. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001bca34dc
14. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/executeQuery.cpp:1703: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001bfe4fcd
15. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/executeQuery.cpp:1925: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001bfdf9d2
16. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/LocalConnection.cpp:272: DB::LocalConnection::sendQuery(DB::ConnectionTimeouts const&, String const&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>> const&, String const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool, std::vector<String, std::allocator<String>> const&, std::function<void (DB::Progress const&)>) @ 0x000000001f514a4f
17. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:1288: DB::ClientBase::processOrdinaryQuery(String, std::shared_ptr<DB::IAST>) @ 0x000000001f49613b
18. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:2338: DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared_ptr<DB::IAST>, bool&, unsigned long) @ 0x000000001f4944dd
19. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:2715: DB::ClientBase::executeMultiQuery(String const&) @ 0x000000001f49ffc4
20. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:2956: DB::ClientBase::processQueryText(String const&) @ 0x000000001f4a110a
21. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Client/ClientBase.cpp:3666: DB::ClientBase::runInteractive() @ 0x000000001f4aa7db
22. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/local/LocalServer.cpp:0: DB::LocalServer::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000015f036bc
23. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x0000000025abc6b1
24. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/local/LocalServer.cpp:1242: mainEntryClickHouseLocal(int, char**) @ 0x0000000015f138ac
25. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/main.cpp:380: main @ 0x000000000d906372
26. __ieee754_pow @ 0x0000000000029d90
27. __libc_start_main_impl @ 0x0000000000029e40
28. _start @ 0x000000000d8f746e
```

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
The bug is not released with 25.11, so I think no changelog is necessary. Fixes https://github.com/ClickHouse/ClickHouse/issues/90569

The issue was that the predicate node itself might not have the const column, but the column in the resulting block is const, e.g.: the column passed through from the inputs.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/ActionsDAG.h [hunk 1]
```diff
@@ -442,6 +442,7 @@ class ActionsDAG
     /// columns will be transformed like `x, y, z` -> `z > 0, z, x, y` -(remove filter)-> `z, x, y`.
     /// To avoid it, add inputs from `all_inputs` list,
     /// so actions `x, y, z -> z > 0, x, y, z` -(remove filter)-> `x, y, z` will not change columns order.
+    ///
```
Comment (antaljanosbenjamin) [inline src/Interpreters/ActionsDAG.h]:
```suggestion
```

File: tests/queries/0_stateless/03727_block_structure_mismatch_after_filter_push_down.sql [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+FROM
+(
+    SELECT materialize(toUInt256(2))
+    UNION ALL
+    SELECT DISTINCT 1
+)
+GROUP BY
+    ignore(lessOrEquals(18, isNotNull(toLowCardinality(10)))),
+    1
+HAVING ignore(isZeroOrNull(5));
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03727_block_structure_mismatch_after_filter_push_down.sql]:
```suggestion
HAVING ignore(isZeroOrNull(5));

```

**Review by scanhex12 — APPROVED** [review]

File: src/Interpreters/ActionsDAG.h (hunk 1 above)
Comment (antaljanosbenjamin) [reply src/Interpreters/ActionsDAG.h]: I wanted to remove this, but messed it up. It doesn't worth running CI once more, so I will the PR as is. Will remove this in another PR.

Comment (antaljanosbenjamin) [reply src/Interpreters/ActionsDAG.h]: Actually the private CI is failed for something CI related, let's run it again.
