### PR TITLE
PR: fix inconsistent reading mode with read-in-order optimizations

### LINKED ISSUE #75961: Parallel replicas: logical error: Replica 0 decided to read in Default mode, not in WithOrder. This is a bug
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=75953&sha=latest&name_0=PR&name_1=Stress+test+%28msan%29&name_2=Fatal+message+in+clickhouse-server.log+%28see+fatal_messages.txt%29

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/75961 

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
For some queries executed with parallel replicas, reading in order optimization(s) could be applied on initiator while can't be applied on remote nodes. It leads to different reading modes used by parallel replicas coordinator (on initiator) and on remoted nodes, which is a logical error

### CODE REVIEW

File: src/Processors/QueryPlan/Optimizations/optimizeTree.cpp [hunk 1]
```diff
@@ -185,6 +188,34 @@ void optimizeTreeSecondPass(const QueryPlanOptimizationSettings & optimization_s
...
+            continue;
+        }
+        if (auto * read_from_local = typeid_cast<ReadFromLocalParallelReplicaStep*>(frame.node->step.get()))
+        {
+            auto local_plan = read_from_local->extractQueryPlan();
+            local_plan->optimize(optimization_settings);
+            if (optimization_settings.merge_expressions)
+                local_plan->mergeExpressions();
+
+            query_plan.replaceNode(frame.node, std::move(local_plan));
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/Optimizations/optimizeTree.cpp]: I would better make a static function `replaceNode(QueryPlan::Node * node, QueryPlan::Nodes & nodes)`, and remove the current one from QueryPlan iface.

File: src/Processors/QueryPlan/QueryPlan.cpp [hunk 2]
```diff
@@ -703,4 +704,31 @@ QueryPlan QueryPlan::clone() const
...
+    const auto & plan_header = plan->getCurrentHeader();
+
+    if (!blocksHaveEqualStructure(header, plan_header))
+    {
+        auto converting_dag = ActionsDAG::makeConvertingActions(
+            plan_header.getColumnsWithTypeAndName(), header.getColumnsWithTypeAndName(), ActionsDAG::MatchColumnsMode::Name);
+
+        auto expression = std::make_unique<ExpressionStep>(plan_header, std::move(converting_dag));
+        plan->addStep(std::move(expression));
+    }
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/QueryPlan.cpp:723]: Looks a bit specific to `ReadFromLocalParallelReplicaStep`.
Another option is to add `ExpressionStep` to query plan (if needed), and only then call replaceNode

File: src/Processors/QueryPlan/QueryPlan.cpp [hunk 3]
```diff
@@ -703,4 +704,31 @@ QueryPlan QueryPlan::clone() const
...
+    node->children = plan->getRootNode()->children;
+
+    max_threads = std::max(max_threads, plan->max_threads);
+    resources = std::move(plan->resources);
+}
+
+void QueryPlan::mergeExpressions()
+{
+    QueryPlanOptimizations::tryMergeExpressions(getRootNode(), nodes, {});
+}
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/QueryPlan.cpp]: This is also a bit strange. Do we need both mergeExpressions and tryMergeExpressions?
(I would remove tryMergeExpressions from QueryPlan as well)

**Review by KochetovNicolai — APPROVED** [review]
Overall looks good.

File: src/Processors/QueryPlan/QueryPlan.cpp (hunk 3 above)
Comment (devcrafter) [reply src/Processors/QueryPlan/QueryPlan.cpp]: The optimization need to access to `nodes` which is possible only from inside QueryPlan. All optimization is called from`QueryPlan::optimize()`, just this time we need only to apply the specific optimization

File: src/Processors/QueryPlan/Optimizations/optimizeTree.cpp (hunk 1 above)
Comment (devcrafter) [reply src/Processors/QueryPlan/Optimizations/optimizeTree.cpp]: Here we need access to `nodes` private member of QueryPlan, therefore it's a member of QueryPlan

Comment (KochetovNicolai) [reply src/Processors/QueryPlan/Optimizations/optimizeTree.cpp]:
```
void optimizeTreeSecondPass(
    const QueryPlanOptimizationSettings & optimization_settings, QueryPlan::Node & root, QueryPlan::Nodes & nodes, QueryPlan & query_plan)
```
nodes here are nodes from QueryPlan

Comment (devcrafter) [reply src/Processors/QueryPlan/Optimizations/optimizeTree.cpp]: I mean access to `nodes` of another QueryPlan
