### PR TITLE
Fix INSERT VALUES parsing of quoted Map/Array/Tuple without falling back to SQL parser

### LINKED ISSUE #97300: Using strings when inserting values for Map causes significant CPU consumption and slows down insertion
### Company or project name

_No response_

### Describe the situation

When INSERT with VALUES is performed for Map from String, there is a significant drop in performance and CPU consumption. This nuance is not described in the documentation and no errors occur.

### Which ClickHouse versions are affected?

[26.1.2.11](https://hub.docker.com/layers/clickhouse/clickhouse-server/26.1.2.11/images/sha256-699374f7c51b6fb53459a0bf68b0155dc8cee33b6bd41d5cefe8e55a63efb242)

### How to reproduce

```sql
CREATE TABLE tab (m Map(String, Float32)) ENGINE=Memory;
```

```sql
INSERT INTO tab VALUES
({'key1':1,'key2':10}),
({'key1':2,'key2':20}),
({'key1':2,'key2':20}),
({'key1':3,'key2':20}),
({'key1':4,'key2':20}),
({'key1':5,'key2':20}),
({'key1':6,'key2':20}),
({'key1':7,'key2':20}),
({'key1':8,'key2':20}),
({'key1':9,'key2':30});
```

<details>

<summary>Profile events</summary>

```json
{'Query': 1, 'InsertQuery': 1, 'InitialQuery': 1, 'IOBufferAllocs': 2, 'IOBufferAllocBytes': 2097278, 'FunctionExecute': 1, 'NetworkSendElapsedMicroseconds': 128, 'NetworkSendBytes': 792, 'GlobalThreadPoolLockWaitMicroseconds': 53, 'GlobalThreadPoolJobs': 12, 'LocalThreadPoolExpansions': 12, 'LocalThreadPoolShrinks': 12, 'LocalThreadPoolThreadCreationMicroseconds': 464, 'LocalThreadPoolLockWaitMicroseconds': 2, 'LocalThreadPoolJobs': 12, 'InsertedRows': 10, 'InsertedBytes': 400, 'SelectedRows': 10, 'SelectedBytes': 400, 'ContextLock': 16, 'RWLockAcquiredReadLocks': 2, 'RealTimeMicroseconds': 14955, 'UserTimeMicroseconds': 7458, 'SystemTimeMicroseconds': 579, 'SoftPageFaults': 6, 'OSCPUWaitMicroseconds': 133, 'OSCPUVirtualTimeMicroseconds': 8032, 'OSReadChars': 5519, 'OSWriteChars': 8, 'LogDebug': 3, 'LogError': 12, 'LoggerElapsedNanoseconds': 648252, 'InterfaceHTTPSendBytes': 792, 'ConcurrencyControlSlotsGranted': 1, 'ConcurrencyControlSlotsAcquired': 11, 'ConcurrencyControlSlotsAcquiredNonCompeting': 1, 'AsyncLoggingFileLogTotalMessages': 15, 'AsyncLoggingErrorFileLogTotalMessages': 12, 'AsyncLoggingTextLogTotalMessages': 15}
```

</details>

```sql
INSERT INTO tab VALUES
('{\'key1\':1, \'key2\':10}'),
('{\'key1\':2, \'key2\':10}'),
('{\'key1\':3, \'key2\':10}'),
('{\'key1\':4, \'key2\':10}'),
('{\'key1\':5, \'key2\':10}'),
('{\'key1\':6, \'key2\':10}'),
('{\'key1\':7, \'key2\':10}'),
('{\'key1\':8, \'key2\':10}'),
('{\'key1\':9, \'key2\':10}'),
('{\'key1\':10, \'key2\':10}');
```

<details>

<summary>Profile events</summary>

```json
{'Query': 1, 'InsertQuery': 1, 'InitialQuery': 1, 'IOBufferAllocs': 2, 'IOBufferAllocBytes': 2097278, 'FunctionExecute': 1, 'NetworkSendElapsedMicroseconds': 153, 'NetworkSendBytes': 793, 'GlobalThreadPoolLockWaitMicroseconds': 22, 'GlobalThreadPoolJobs': 12, 'LocalThreadPoolExpansions': 12, 'LocalThreadPoolShrinks': 12, 'LocalThreadPoolThreadCreationMicroseconds': 171, 'LocalThreadPoolLockWaitMicroseconds': 1, 'LocalThreadPoolJobs': 12, 'InsertedRows': 10, 'InsertedBytes': 400, 'SelectedRows': 10, 'SelectedBytes': 400, 'ContextLock': 16, 'RWLockAcquiredReadLocks': 2, 'RWLockReadersWaitMilliseconds': 1, 'RealTimeMicroseconds': 228454, 'UserTimeMicroseconds': 23999, 'SystemTimeMicroseconds': 1674, 'SoftPageFaults': 1, 'OSCPUWaitMicroseconds': 116, 'OSCPUVirtualTimeMicroseconds': 25665, 'OSReadChars': 5946, 'OSWriteChars': 8, 'LogDebug': 3, 'LogError': 12, 'LoggerElapsedNanoseconds': 696998, 'InterfaceHTTPSendBytes': 793, 'ConcurrencyControlSlotsGranted': 1, 'ConcurrencyControlSlotsAcquired': 11, 'ConcurrencyControlSlotsAcquiredNonCompeting': 1, 'AsyncLoggingFileLogTotalMessages': 15, 'AsyncLoggingErrorFileLogTotalMessages': 12, 'AsyncLoggingTextLogTotalMessages': 15}
```

</details>

### Expected performance

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jh0x**
Fixes https://github.com/ClickHouse/ClickHouse/issues/97300

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Improve performance  in `INSERT VALUES` for `Map`, `Array`, and `Tuple` columns when values are passed as escaped strings (e.g. `'{\'key\':1}'`), avoiding unnecessary fallback to the SQL expression parser

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.815`

### CODE REVIEW

File: src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp
Comment (george-larionov) [inline src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: Do you mind cleaning this up? I know it is old code, but it doesn't seem like the extra bool variable is needed, we can just check the output of the function.

File: src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp [hunk 1]
```diff
@@ -325,9 +328,52 @@ bool ValuesBlockInputFormat::tryReadValue(IColumn & column, size_t column_idx)
...
+        {
+            WhichDataType which(removeNullable(removeLowCardinality(types[column_idx])));
+            if (which.isMap() || which.isArray() || which.isTuple())
+            {
+                bool parsed_string = false;
+                String string_value;
+                try
+                {
+                    readQuotedStringWithSQLStyle(string_value, *buf);
+                    //skipWhitespaceIfAny(*buf);
```
Comment (george-larionov) [inline src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: please remove this line

File: src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp [hunk 2]
```diff
@@ -325,9 +328,52 @@ bool ValuesBlockInputFormat::tryReadValue(IColumn & column, size_t column_idx)
...
+        if (!buf->eof() && *buf->position() == '\'')
+        {
+            WhichDataType which(removeNullable(removeLowCardinality(types[column_idx])));
+            if (which.isMap() || which.isArray() || which.isTuple())
+            {
+                bool parsed_string = false;
+                String string_value;
+                try
+                {
+                    readQuotedStringWithSQLStyle(string_value, *buf);
```
Comment (george-larionov) [inline src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: I believe we could instead use tryReadQuotedStringWithSQLStyle (which returns a bool instead of throwing) and get rid of the extra try/catch

File: src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp
Comment (george-larionov) [inline src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: I guess this is also extra since assertDelimiterAfterValue calls checkDelimiterAfterValue which already calls this func

File: src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp [hunk 3]
```diff
@@ -325,9 +328,52 @@ bool ValuesBlockInputFormat::tryReadValue(IColumn & column, size_t column_idx)
...
+                    {
+                        ReadBufferFromString in_buffer(string_value);
+                        serializations[column_idx]->deserializeWholeText(column, in_buffer, format_settings);
+                        return true;
+                    }
+                    catch (...)
+                    {
+                        if (column.size() > size_before)
+                            column.popBack(column.size() - size_before);
+                    }
```
Comment (george-larionov) [inline src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: This try/catch could also be replaced with [tryDeserializeWholeText](https://github.com/ClickHouse/ClickHouse/blob/master/src/DataTypes/Serializations/ISerialization.cpp#L599) which also handles the popBack. Something like:

```suggestion
                        ReadBufferFromString in_buffer(string_value);
                        if(serializations[column_idx]->tryDeserializeWholeText(column, in_buffer, format_settings))
                            return true;
```

File: tests/queries/0_stateless/04071_insert_values_string_to_complex_type.sql
Comment (george-larionov) [inline tests/queries/0_stateless/04071_insert_values_string_to_complex_type.sql:1]: I think most of these tests should be run with `SET input_format_values_interpret_expressions = 0;`. Otherwise we are just testing the old functionality (which is good, it doesn't seem we have existing tests for these cases). However it would still be nice to test both paths.

**Review by george-larionov — CHANGES_REQUESTED** [review]
Thanks again for the contribution, it looks good overall but I left some comments mostly about making the code more succinct and updating the tests.

**Review by george-larionov — APPROVED** [review]
Looks very nice now, thanks! Let's see what the tests say.

**Comment by george-larionov** [comment]
The test failure is unrelated, but I made an attempt at fixing it [here](https://github.com/ClickHouse/ClickHouse/pull/102427).
