### PR TITLE
Fix bad cast

### LINKED ISSUE #25447: Bad cast from ColumnString to ColumnNullable
**Describe the bug**
https://clickhouse-test-reports.s3.yandex.net/25409/8d4ccb40de5a956cc412df58698176c3e9c0488c/fuzzer_debug/report.html#fail1

**How to reproduce**
```
SELECT '7', 'xyz', * FROM (SELECT NULL AS `'xyz'`)
```

```
../src/Common/assert_cast.h:50:12: runtime error: downcast of address 0x7ff1cc2e6ee0 which does not point to an object of type 'const DB::ColumnNullable'
0x7ff1cc2e6ee0: note: object is of type 'DB::ColumnString'
 00 00 00 00  50 3b 35 0a 00 00 00 00  03 00 00 00 00 00 00 00  80 3b 0d c4 f4 7f 00 00  88 3b 0d c4
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::ColumnString'
```

### LINKED ISSUE #26914: Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<char8_t>
```
SELECT
    ignore(ignore(ignore(ignore(NULL), '0.1'), 1.1920928955078125e-7, 'xyz', NULL)),
    'xyz',
    *
FROM
(
    SELECT NULL AS `'xyz'`
)

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.9.1 revision 54449.

┌─ignore(ignore(ignore(ignore(NULL), '0.1'), 1.1920928955078125e-7, 'xyz', NULL))─┬─'xyz'─┬─'xyz'─┐
│                                                                               0 │ xyz   │ ᴺᵁᴸᴸ  │
└─────────────────────────────────────────────────────────────────────────────────┴───────┴───────┘
Logical error: 'Bad cast from type DB::ColumnVector<unsigned int> to DB::ColumnVector<char8_t>'.
Aborted (core dumped)
```
https://clickhouse-test-reports.s3.yandex.net/26716/f35e6eee19b57a89e1105b5fa2ccefb583c02f9f/fuzzer_ubsan/report.html#fail1

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the issue that in case of some sophisticated query with column aliases identical to the names of expressions, bad cast may happen. This fixes #25447. This fixes #26914. This fix may introduce backward incompatibility: if there are different expressions with identical names, exception will be thrown. It may break some rare cases when `enable_optimize_predicate_expression` is set.

### CODE REVIEW

**Comment by CurtizJ** [comment]
Maybe we can try to use boost::multi_index for container of block?

**Comment by alexey-milovidov** [comment]
That's a good idea.

**Comment by alexey-milovidov** [comment]
@azat Maybe I need your help with `distributed_optimize_skip_select_on_unused_shards` test.
The logic looks very complicated for me.

File: src/Interpreters/evaluateConstantExpression.cpp [hunk 1]
```diff
@@ -368,7 +369,30 @@ std::optional<Blocks> evaluateExpressionOverConstantCondition(const ASTPtr & nod
...
+
+            for (const auto & elem : conjunct)
+            {
+                if (!block.has(elem.name))
+                {
+                    block.insert(elem);
+                }
+                else
+                {
+                    /// Conjunction of condition on column equality to distinct values can never be satisfied.
```
Comment (azat) [inline src/Interpreters/evaluateConstantExpression.cpp:382]: @alexey-milovidov the behavior had been changed because of this hunk.

```
SELECT count(*) FROM remote('127.{1,2}', system.one, dummy) WHERE dummy = 1 AND dummy = 0 SETTINGS optimize_skip_unused_shards=1;
```

Without:

```sql
[p1.azat] 2021.07.24 06:41:06.482136 [ 3871 ] {ba1a6a15-576f-4883-9a4c-e81e60bab557} <Debug> StorageDistributed (remote): Skipping irrelevant shards - the query will be sent to the following 
shards of the cluster (shard numbers): [2]
```

With this patch:

```sql
[p1.azat] 2021.07.24 06:37:01.399750 [ 22034 ] {0aa22c9f-63e8-4630-b951-0d0b76a02c10} <Debug> StorageDistributed (remote): Skipping irrelevant shards - the query will be sent to the following shards of the cluster (shard numbers): []
```

So there are zero shards to send the query, hence nothing more is done.
Such queries does not looks like real user queries, so maybe we should not try to optimize them, or return any node if zero is returned, what do you think?

Comment (alexey-milovidov) [reply src/Interpreters/evaluateConstantExpression.cpp:382]: > So there are zero shards to send the query, hence nothing more is done.

But the implementation for zero shards is wrong.
SELECT count() ... without GROUP BY returns empty set instead of value 0.

**Comment by vdimir** [comment]
@alexey-milovidov 

Commit [`a0ed37e` (#26639)](https://github.com/ClickHouse/ClickHouse/pull/26639/commits/a0ed37e04e0a2b4550f0676254a7c348a43db670) should fix `01064_pm_all_join_const_and_nullable`.

Error occurred because in some cases join materialize contants, in some not, but in `ExpressionActionsChain::JoinStep` it wasn't considered and column returned as is. I suppose it should be ok not to consider column constness here at all and return only type and name of columns.

(Also discussed with @KochetovNicolai)

**Comment by alexey-milovidov** [comment]
Thank you!

Now only two tests remaining... Maybe @azat can help.

**Comment by azat** [comment]
>Now only two tests remaining... Maybe @azat can help.

Ok, sure. It will be great if someone can take a look at #26466 before, to avoid possible conflicts with the patch for empty shards.

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@azat 

```
01951_distributed_push_down_limit | FAIL |  
00754_distributed_optimize_skip_select_on_unused_shards_with_prewhere | FAIL |  
00754_distributed_optimize_skip_select_on_unused_shards | FAIL |  
```

Still failing.

**Comment by azat** [comment]
@alexey-milovidov Right, because I haven't submitted any fix yet, but here it is - #27427 (I was waiting for you to merge #27424)

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
@azat 

> 00754_distributed_optimize_skip_select_on_unused_shards_with_prewhere

File: src/Interpreters/evaluateConstantExpression.cpp [hunk 2]
```diff
@@ -368,7 +369,30 @@ std::optional<Blocks> evaluateExpressionOverConstantCondition(const ASTPtr & nod
...
+
+                    const ColumnWithTypeAndName & prev = block.getByName(elem.name);
+
+                    if (isColumnConst(*prev.column) && isColumnConst(*elem.column))
+                    {
+                        Field prev_value = assert_cast<const ColumnConst &>(*prev.column).getField();
+                        Field curr_value = assert_cast<const ColumnConst &>(*elem.column).getField();
+
+                        if (prev_value != curr_value)
+                            return Blocks{};
```
Comment (azat) [inline src/Interpreters/evaluateConstantExpression.cpp:392]: @alexey-milovidov the problem here, you cannot simply check one of conjunct and return, you need to check all of them since they are OR'ed.

TL;DR;

The reason this had been reproduced is that InterpreterSelectQuery [joins WHERE with PREWHERE](https://github.com/ClickHouse/ClickHouse/blob/bb4c11cd27d463a92bb4458b7df270db7d84c78f/src/Interpreters/InterpreterSelectQuery.cpp#L431-L436)

And `optimize_skip_unused_shards` [join them again](https://github.com/ClickHouse/ClickHouse/blob/bb4c11cd27d463a92bb4458b7df270db7d84c78f/src/Storages/StorageDistributed.cpp#L1100)

So eventually you will get the following filter `(a = 0 OR a = 1) AND ((a = 0 OR a = 1) AND (b = 0 OR b = 1))`

Which will have the following dnf:

```
        conjunct:
                a = 0
                a = 0
                b = 0
        conjunct:
                a = 0
                a = 0
                b = 1
        conjunct:
                a = 0
                a = 1 <!-- here it will return empty Blocks{} while it should not
                b = 0
        conjunct:
                a = 0
                a = 1
                b = 1
        conjunct:
                a = 1
                a = 0
                b = 0
        conjunct:
                a = 1
                a = 0
                b = 1
        conjunct:
                a = 1
                a = 1
                b = 0
        conjunct:
                a = 1
                a = 1
                b = 1
```

Something like the [this](https://gist.githubusercontent.com/azat/77537536e39612979bfa60881f740570/raw/051fea993a23b68ebcbb86b694ff5c448d96e0c9/0001-Fix-always-false-check-in-evaluateConstantExpression.patch) should work (just an POC).

**Comment by alexey-milovidov** [comment]
Only one test remains...

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by alexey-milovidov** [comment]
It is more important to merge this pull request: it fixes potential vulnerabilities due to memory-unsafe code, in comparison to preserving the behaviour of some rare queries with ambiguous columns.

**Comment by alexey-milovidov** [comment]
Only integration tests remain...

**Comment by KochetovNicolai** [comment]
test_mutations_with_merge_background_task 
```
2021.08.18 00:12:49.902686 [ 165 ] {} <Error> auto DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::(anonymous class)::operator()() const: Code: 352. DB::Exception: Column name in Block cannot be empty: while executing 'FUNCTION and(equals(1, 1) :: 1, in(toUInt32(b), 1) :: 0) -> and(equals(1, 1), in(toUInt32(b), 1)) UInt8 : 2'. (AMBIGUOUS_COLUMN_NAME), Stack trace (when copying this message, always include the lines below):

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18d75e5b in /usr/bin/clickhouse
1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:59: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x991131c in /usr/bin/clickhouse
2. ./obj-x86_64-linux-gnu/../src/Core/Block.cpp:0: DB::Block::insert(DB::ColumnWithTypeAndName) @ 0x1407e9f5 in /usr/bin/clickhouse
3. DB::(anonymous namespace)::FunctionIn<false, false, true, false>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x112cfae2 in /usr/bin/clickhouse
4. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcbaf870 in /usr/bin/clickhouse
5. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:0: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13ef74b9 in /usr/bin/clickhouse
6. ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13ef7c67 in /usr/bin/clickhouse
7. DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0xcbaeea2 in /usr/bin/clickhouse
8. ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: DB::ColumnFunction::reduce() const @ 0x1502a3b9 in /usr/bin/clickhouse
9. ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: DB::maskedExecute(DB::ColumnWithTypeAndName&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::MaskInfo const&) @ 0x151a75fc in /usr/bin/clickhouse
10. DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeShortCircuit(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0xd3146e4 in /usr/bin/clickhouse
11. DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xd311aaf in /usr/bin/clickhouse
12. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcbaf870 in /usr/bin/clickhouse
13. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:0: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13ef74b9 in /usr/bin/clickhouse
14. ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13ef7b26 in /usr/bin/clickhouse
15. ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x1461b6f1 in /usr/bin/clickhouse
16. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/FilterTransform.cpp:0: DB::FilterTransform::transform(DB::Chunk&) @ 0x15b80e8b in /usr/bin/clickhouse
17. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3933: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x11bdb6d7 in /usr/bin/clickhouse
18. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x159720d4 in /usr/bin/clickhouse
19. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:108: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x159c21a5 in /usr/bin/clickhouse
20. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:0: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x159c0032 in /usr/bin/clickhouse
21. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1006: DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x159be6f9 in /usr/bin/clickhouse
22. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PullingPipelineExecutor.cpp:37: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x159ce88b in /usr/bin/clickhouse
23. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PullingPipelineExecutor.cpp:48: DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x159cec01 in /usr/bin/clickhouse
24. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutingBlockInputStream.cpp:0: DB::PipelineExecutingBlockInputStream::readImpl() @ 0x159ba1d8 in /usr/bin/clickhouse
25. ./obj-x86_64-linux-gnu/../src/DataStreams/IBlockInputStream.cpp:0: DB::IBlockInputStream::read() @ 0x142855fa in /usr/bin/clickhouse
26. ./obj-x86_64-linux-gnu/../src/Interpreters/MutationsInterpreter.cpp:0: DB::isStorageTouchedByMutations(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<DB::MutationCommand, std::__1::allocator<DB::MutationCommand> > const&, std::__1::shared_ptr<DB::Context>) @ 0x14d4aa52 in /usr/bin/clickhouse
27. ./obj-x86_64-linux-gnu/../src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp:0: DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MutationCommands const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x15640cac in /usr/bin/clickhouse
28. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3935: DB::StorageMergeTree::mutateSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x1582a5d2 in /usr/bin/clickhouse
29. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageMergeTree::scheduleDataProcessingJob(DB::IBackgroundJobExecutor&)::$_5, bool ()> >(std::__1::__function::__policy_storage const*) @ 0x158367af in /usr/bin/clickhouse
30. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x15545587 in /usr/bin/clickhouse
31. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2210: ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x993ee08 in /usr/bin/clickhouse
 (version 21.9.1.7798)
```

**Comment by KochetovNicolai** [comment]
Ok, now all the tests are fixed.

**Comment by mbtolou** [comment]
2021.08.29 01:11:54.136847 [ 7979 ] {} <Error> auto DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::(anonymous class)::operator()() const: Code: 236, e.displayText() = DB::Exception: Cancelled merging parts, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8f9557a in /usr/bin/clickhouse
1. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeData::MergingParams const&, DB::IMergeTreeDataPart const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x10cfc4e7 in /usr/bin/clickhouse
2. DB::StorageMergeTree::mergeSelectedParts(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x10ec5d04 in /usr/bin/clickhouse
3. ? @ 0x10ed5bd7 in /usr/bin/clickhouse
4. ? @ 0x10c1c9f7 in /usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8fd8f18 in /usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x8fdaabf in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8fd61ff in /usr/bin/clickhouse
8. ? @ 0x8fd9ae3 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdf6d in /usr/lib64/libc-2.17.so
 (version 21.8.4.51 (official build))

**Comment by IVitamin-C** [comment]
hi @alexey-milovidov 
21.8 This sql can be executed successfully！
`SELECT
    _shard_num AS shard_num,
    sum(1) as rows
FROM cluster({cluster}, test, table_name)
GROUP BY shard_num`
21.12 This sql execution failed
DB::Exception: Cannot find column `_shard_num` in source stream, there are only columns: [shard_num, count()].
Needs to be modified to
`
SELECT
    _shard_num AS shard_num,
    sum(1) as rows
FROM cluster({cluster}, test, table_name)
GROUP BY _shard_num
`
This will be an incompatible change, you can fix it like _shard_num and other virtual columns.
thanks

**Comment by alexey-milovidov** [comment]
We can ask @azat, he is the author of `_shard_num` feature. It is implemented in quite hacky way.

**Comment by azat** [comment]
Right, _shard_num is pretty special column that can be interpreted differently on shards and on initiator, and there were lots of quirks in #16947
This particular case will be fixed by https://github.com/ClickHouse/ClickHouse/pull/16947/commits/e450ac2f0c8a4296d95f19430bb04369133b405a.

But actually right now there is another implementation that is less hacky, shardNum from @amosbird, added in #27020
So you can rewrite you query to `SELECT shardNum() AS shard_num, sum(1) as rows FROM cluster({cluster}, test, table_name) GROUP BY shard_num` and it will work.

And actually there should not be two ways to archive the same, so #33392 should fix it.
