### PR TITLE
Fix MaterializeMySQL SYNC failure when modify binlog_checksum

### LINKED ISSUE #15883: to create MaterializeMySQL engin wasn't finished successfully
The first few completed tables can be queried normally

`
2020.10.13 09:14:48.751772 [ 23597 ] {} <Error> MaterializeMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(hd_db, eqs_hd) B wasn't finished successfully: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 102 ('B'): B. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always include the lines below):

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0xe922219 in /usr/bin/clickhouse
1. ? @ 0xdeb61b7 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdeb5dbd in /usr/bin/clickhouse
3. ? @ 0xdaf5594 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0xdaf1752 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaeeaac in /usr/bin/clickhouse
6. ? @ 0xdb0acbd in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8375d in /usr/bin/clickhouse
8. ? @ 0x7b87273 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.10.1.4881 (official build))
`

after that，all tables can not be queried

2020.10.13 09:19:10.930722 [ 24253 ] {} <Error> MaterializeMySQLSyncThread: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 13. Bytes expected: 14., Stack trace (when copying this message, always include the lines below):

### LINKED ISSUE #16923: MaterializeMySQL while query got error.
MaterializeMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(bear, clickhouse) B wasn't finished successfully: Code: 62, 
e.displayText() = DB::Exception: Syntax error: failed at position 105 ('B'): B. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY,
 DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query,
 Stack trace (when copying this message, always include the lines below):

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, 
unsigned long, unsigned long) @ 0xe937819 in /usr/bin/clickhouse
1. ? @ 0xdec81b7 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
3. ? @ 0xdaff0e4 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0xdafb2a2 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf85fc in /usr/bin/clickhouse
6. ? @ 0xdb1480d in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
8. ? @ 0x7b8d153 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.10.3.30 (official build))
2020.11.12 17:37:57.583104 [ 25151 ] {} <Error> MaterializeMySQLSyncThread: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 105 ('B'): B. Expected one of: 
RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trac
e (when copying this message, always include the lines below):

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0xe937819 in /usr/bin/clickhouse
1. ? @ 0xdec81b7 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
3. ? @ 0xdaff0e4 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0xdafb2a2 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf85fc in /usr/bin/clickhouse
6. ? @ 0xdb1480d in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
8. ? @ 0x7b8d153 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.10.3.30 (official build))
2020.11.12 17:37:57.583469 [ 25151 ] {} <Error> MaterializeMySQLSyncThread: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 5., Stack trace (when copying this message, always include the lines below):

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fixes #16923 fixes #15883
Fix MaterializeMySQL SYNC failure when the modify MySQL binlog_checksum

### CODE REVIEW

**Comment by zhang2014** [comment]
CC @tavplubix

**Comment by zhang2014** [comment]
Stress test (thread) — Sanitizer assert (in stderr.log) - unrelated

File: src/IO/MySQLBinlogEventReadBuffer.cpp [hunk 1]
```diff
@@ -4,9 +4,12 @@
...
 
-MySQLBinlogEventReadBuffer::MySQLBinlogEventReadBuffer(ReadBuffer & in_)
-    : ReadBuffer(nullptr, 0, 0), in(in_)
+MySQLBinlogEventReadBuffer::MySQLBinlogEventReadBuffer(ReadBuffer & in_, size_t checksum_signature_length_)
+    : ReadBuffer(nullptr, 0, 0), in(in_), checksum_signature_length(checksum_signature_length_)
 {
+    if (checksum_signature_length)
+        checksum_buf = new char[checksum_signature_length];
+
     nextIfAtEnd();
```
Comment (tavplubix) [inline src/IO/MySQLBinlogEventReadBuffer.cpp:13]: `nextIfAtEnd()` may throw an exception, it will lead to memory leak. Since size of checksum is small and limited, we can just rename `CHECKSUM_CRC32_SIGNATURE_LENGTH` to `MAX_CHECKSUM_SIGNATURE_LENGTH` and use `char checksum_buf[MAX_CHECKSUM_SIGNATURE_LENGTH];` as before, without dynamic allocations. If `checksum_signature_length_` is greater then buffer size, throw `LOGICAL_ERROR`.

**Comment by tavplubix** [comment]
Everything else LGTM

File: src/IO/MySQLBinlogEventReadBuffer.cpp (hunk 1 above)
Comment (zhang2014) [reply src/IO/MySQLBinlogEventReadBuffer.cpp]: Done.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
AST fuzzer - #13281
ClickHouse build check - OOM, known issue
Functional stateless tests (ubsan) - 01247_optimize_distributed_group_by_sharding_key - flacky, known issue

Marker check - :(
Let's restart tests
