### PR TITLE
Fix recalculation of skip indexes and projections in `ALTER DELETE` queries

### LINKED ISSUE #52433: Skip index is not affected by alter delete. Too many marks in file.
master

```
create table tab (x UInt32, y String, Index i y type minmax granularity 3) engine = MergeTree order by tuple();
insert into tab select number, toString(number) from numbers(8192 * 10);
alter table tab delete where x < 8192;
select x from tab where y in (4, 5);
```

```
SELECT x
FROM tab
WHERE y IN (4, 5)

Query id: 81971d0e-73f5-4b03-a0ab-dce83c252a04


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 23.7.1):
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Too many marks in file skp_idx_i.cmrk3, marks expected 3 (bytes size 72). (CANNOT_READ_ALL_DATA)
```

Index is just hard-linked.

```
$ hexdump /home/ubuntu/test/clickhouse/store/085/085ca165-85ef-4671-9233-d81dd6a0c727/all_1_1_0_2/skp_idx_i.idx2 
0000000 2c5f fce7 d50c 7003 ddfc 5ff7 bab9 9bed
0000010 3282 0000 2b00 0000 f100 0104 0430 3939
0000020 3939 3205 3534 3637 3405 3139 3135 0006
0000030 3271 3705 3733 3732 0006 3870 3805 3931
0000040 3931                                   
0000042
$ hexdump /home/ubuntu/test/clickhouse/store/085/085ca165-85ef-4671-9233-d81dd6a0c727/all_1_1_0/skp_idx_i.idx2 
0000000 2c5f fce7 d50c 7003 ddfc 5ff7 bab9 9bed
0000010 3282 0000 2b00 0000 f100 0104 0430 3939
0000020 3939 3205 3534 3637 3405 3139 3135 0006
0000030 3271 3705 3733 3732 0006 3870 3805 3931
0000040 3931                                   
0000042
$ stat /home/ubuntu/test/clickhouse/store/085/085ca165-85ef-4671-9233-d81dd6a0c727/all_1_1_0/skp_idx_i.idx2 
  File: /home/ubuntu/test/clickhouse/store/085/085ca165-85ef-4671-9233-d81dd6a0c727/all_1_1_0/skp_idx_i.idx2
  Size: 66        	Blocks: 8          IO Block: 4096   regular file
Device: 10301h/66305d	Inode: 529521      Links: 3
Access: (0640/-rw-r-----)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2023-07-21 14:56:21.679980867 +0000
Modify: 2023-07-21 14:52:53.161683317 +0000
Change: 2023-07-21 14:55:03.580622408 +0000
 Birth: -
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed recalculation of skip indexes and projections in `ALTER DELETE` queries

Fixes #52433.

### CODE REVIEW

File: src/Interpreters/MutationsInterpreter.cpp [hunk 1]
```diff
@@ -861,30 +878,44 @@ void MutationsInterpreter::prepare(bool dry_run)
...
+
+        const auto & projection_cols = projection.required_columns;
+        bool changed = std::any_of(
+            projection_cols.begin(),
+            projection_cols.end(),
+            [&](const auto & col) { return updated_columns.contains(col) || changed_columns.contains(col); });
+
+        if (changed)
+            materialized_projections.insert(projection.name);
     }
```
Comment (CurtizJ) [inline src/Interpreters/MutationsInterpreter.cpp:919]: Actually the fix is here.

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit fbe9f8d0f653cedd30640c42968df1ac8cf78dff with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52530/fbe9f8d0f653cedd30640c42968df1ac8cf78dff/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/MergeTree/MutateTask.cpp [hunk 2]
```diff
@@ -85,6 +86,41 @@ static void splitAndModifyMutationCommands(
 
                 if (command.type == MutationCommand::Type::MATERIALIZE_COLUMN)
                     mutated_columns.emplace(command.column_name);
+
+                if (command.type == MutationCommand::Type::MATERIALIZE_INDEX)
```
Comment (amosbird) [inline src/Storages/MergeTree/MutateTask.cpp:90]: I thought there can be some noop materialization of indices and projections (unchanged). In that case we should not read dependent columns.

Comment (CurtizJ) [reply src/Storages/MergeTree/MutateTask.cpp]: This code is needed in case of when `isFullPartStorage(part) == false` which is not a case now. I've removed this code.

**Comment by canhld94** [comment]
Hi @CurtizJ can I know the status of this PR?

**Comment by CurtizJ** [comment]
@canhld94 

> Can I know the status of this PR?

It's ready for review and hopefully will be merged soon

File: src/Interpreters/MutationsInterpreter.cpp [hunk 3]
```diff
@@ -533,13 +539,24 @@ void MutationsInterpreter::prepare(bool dry_run)
...
+    StorageInMemoryMetadata::HasDependencyCallback has_dependency =
+        [&](const String & name, ColumnDependency::Kind kind)
+    {
+        if (kind == ColumnDependency::PROJECTION)
+            return source.hasProjection(name);
+
+        if (kind == ColumnDependency::SKIP_INDEX)
+            return source.hasSecondaryIndex(name);
+
+        return true;
```
Comment (alesapin) [inline src/Interpreters/MutationsInterpreter.cpp:551]: Why `true` by default?

**Review by alesapin — APPROVED** [review]

File: src/Interpreters/MutationsInterpreter.cpp (hunk 3 above)
Comment (CurtizJ) [reply src/Interpreters/MutationsInterpreter.cpp:551]: Because for other dependencies it's always true.
