### PR TITLE
Fix logical error in defaultProfiles function

### LINKED ISSUE #72958: Logical Error: No user in current context, it's a bug
**Describe the bug**
Calling `defaultRoles()` function inside a projection.

**How to reproduce**
Run: https://fiddle.clickhouse.com/aff007d7-9d06-4900-a287-63cf11588159

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a logical error when calling `defaultProfiles()` function inside a projection.

Closes https://github.com/ClickHouse/ClickHouse/issues/72958

### CODE REVIEW

File: src/Functions/currentProfiles.cpp [hunk 1]
```diff
@@ -80,9 +80,16 @@ namespace
...
-                case Kind::enabledProfiles: profile_ids = context->getEnabledProfiles(); break;
-                case Kind::defaultProfiles: profile_ids = context->getUser()->settings.toProfileIDs(); break;
+                case Kind::currentProfiles:
+                    profile_ids = context->getCurrentProfiles();
+                    break;
+                case Kind::enabledProfiles:
+                    profile_ids = context->getEnabledProfiles();
+                    break;
+                case Kind::defaultProfiles:
+                    if (context->getUserID())
```
Comment (vitlibar) [inline src/Functions/currentProfiles.cpp:90]: It seems more logical to check here `context->tryGetUser()` and not `context->getUserID()`.

**Review by vitlibar — APPROVED** [review]
