### PR TITLE
Better handling of fatal errors

### LINKED ISSUE #37889: use-of-uninitialized-value in DB::TCPHandler
https://s3.amazonaws.com/clickhouse-test-reports/37853/d4f0e8d4c2069f12fd71106830b330c8af2d1182/stress_test__memory__actions_/stderr.log
```
==687==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x42dde7c7 in DB::TCPHandler::sendLogs() build_docker/../src/Server/TCPHandler.cpp:1740:9
    #1 0x42e0374f in DB::TCPHandler::runImpl()::$_2::operator()() const build_docker/../src/Server/TCPHandler.cpp:248:21
    #2 0x42e0374f in decltype(static_cast<DB::TCPHandler::runImpl()::$_2&>(fp)()) std::__1::__invoke<DB::TCPHandler::runImpl()::$_2&>(DB::TCPHandler::runImpl()::$_2&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #3 0x42e0374f in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::TCPHandler::runImpl()::$_2&>(DB::TCPHandler::runImpl()::$_2&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #4 0x42e0374f in std::__1::__function::__default_alloc_func<DB::TCPHandler::runImpl()::$_2, void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #5 0x42e0374f in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TCPHandler::runImpl()::$_2, void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #6 0xb82dca6 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #7 0xb82dca6 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #8 0xb82dca6 in DB::ThreadStatus::onFatalError() build_docker/../src/Common/ThreadStatus.cpp:255:9
    #9 0x3af06db5 in SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, unsigned int, DB::ThreadStatus*) const build_docker/../src/Daemon/BaseDaemon.cpp:389:25
    #10 0x3af001a8 in SignalListener::run()::'lambda'()::operator()() const build_docker/../src/Daemon/BaseDaemon.cpp:254:41
    #11 0x3af001a8 in decltype(static_cast<SignalListener::run()::'lambda'()>(fp)()) std::__1::__invoke<SignalListener::run()::'lambda'()>(SignalListener::run()::'lambda'()&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #12 0x3af001a8 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, SignalListener::run()::'lambda'()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, SignalListener::run()::'lambda'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #13 0x3af001a8 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, SignalListener::run()::'lambda'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #14 0x7f8beafd2608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #15 0x7f8beaef7132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

  Uninitialized value was created by a heap deallocation
    #0 0xb714a99 in operator delete(void*, unsigned long) (/usr/bin/clickhouse+0xb714a99) (BuildId: 503259d28c59cea6)
    #1 0x42dbf1eb in DB::TCPHandler::~TCPHandler() build_docker/../src/Server/TCPHandler.cpp:95:1
    #2 0x534a506c in std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()(Poco::Net::TCPServerConnection*) const build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54:5
    #3 0x534a506c in std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*) build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:315:7
    #4 0x534a506c in std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::~unique_ptr() build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:269:19
    #5 0x534a506c in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116:6
    #6 0x53bc9998 in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #7 0x53bc557f in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/../contrib/poco/Foundation/src/Thread.cpp:55:11
    #8 0x53bc15f8 in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #9 0x7f8beafd2608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/../src/Server/TCPHandler.cpp:1740:9 in DB::TCPHandler::sendLogs()
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

This closes #37889.

### CODE REVIEW

File: src/Server/TCPHandler.cpp [hunk 1]
```diff
@@ -611,6 +611,8 @@ void TCPHandler::runImpl()
         /// It is important to destroy query context here. We do not want it to live arbitrarily longer than the query.
         query_context.reset();
 
+        CurrentThread::setFatalErrorCallback({});
```
Comment (alexey-milovidov) [inline src/Server/TCPHandler.cpp:614]: We reset the callback before the destruction of TCPHandler.

File: src/Common/ThreadStatus.cpp [hunk 2]
```diff
@@ -237,6 +237,7 @@ void ThreadStatus::setFatalErrorCallback(std::function<void()> callback)
 
 void ThreadStatus::onFatalError()
 {
+    std::lock_guard lock(thread_group->mutex);
```
Comment (alexey-milovidov) [inline src/Common/ThreadStatus.cpp:240]: This allows it to be reset.

File: src/Daemon/BaseDaemon.cpp [hunk 3]
```diff
@@ -159,7 +161,16 @@ static void signalHandler(int sig, siginfo_t * info, void * context)
     if (sig != SIGTSTP) /// This signal is used for debugging.
     {
         /// The time that is usually enough for separate thread to print info into log.
-        sleepForSeconds(20);  /// FIXME: use some feedback from threads that process stacktrace
```
Comment (alexey-milovidov) [inline src/Daemon/BaseDaemon.cpp:162]: Implement TODO.
The logs will be sent to the client in more cases.

**Comment by alexey-milovidov** [comment]
I didn't reproduce the case, but it should become better.

File: src/Daemon/BaseDaemon.cpp [hunk 4]
```diff
@@ -134,6 +134,8 @@ static void terminateRequestedSignalHandler(int sig, siginfo_t *, void *)
 }
 
 
+static std::atomic<bool> fatal_error_printed{false};
```
Comment (tavplubix) [inline src/Daemon/BaseDaemon.cpp:137]: It's not quite correct to use std::atomic in a signal handler, it would be better to use `std::atomic_flag`. However, I doubt someone actually uses ClickHouse on architectures where it matters.

**Review by tavplubix — COMMENTED** [review]
LGTM

File: src/Common/ThreadStatus.cpp (hunk 2 above)
Comment (tavplubix) [inline src/Common/ThreadStatus.cpp:240]: @alexey-milovidov, `thread_group` may not be set: https://pastila.nl/?02a69da9/edd0fb1660431e9ce76569b799c52032
