### PR TITLE
Fix parsing of shell-style quotes in arguments for the executable table function

### LINKED ISSUE #66634: Unable to pass argument containing space to the 'executable'
Currently it is not possible to pass values requiring quotes to the `executable`.

Steps to reproduce:
* create `argument_test.sh` with following content in the user scripts directory:
```bash
#!/bin/bash

first="$1"
echo $first
```
* `chmod +x ./argument_test.sh`
* when invoked from shell as `./argument_test.sh 'a b'` or `./argument_test.sh "a b"`  script outputs `a b`
* try to get the same output using `select * from executable('argument_test.sh', LineAsString, 'value String')`

Tried several variants but non worked:
```sql
ch :) select * from executable('argument_test.sh ''a b''', LineAsString, 'value String')

SELECT *
FROM executable('argument_test.sh \'a b\'', LineAsString, 'value String')

   ┌─value─┐
1. │ 'a    │
   └───────┘
   
ch :) select * from executable('argument_test.sh "a b"', LineAsString, 'value String')

SELECT *
FROM executable('argument_test.sh "a b"', LineAsString, 'value String')

   ┌─value─┐
1. │ "a    │
   └───────┘
   
ch :) select * from executable('argument_test.sh \\''a b\\''', LineAsString, 'value String')

SELECT *
FROM executable('argument_test.sh \\\'a b\\\'', LineAsString, 'value String')

   ┌─value─┐
1. │ \'a   │
   └───────┘

ch :) select * from executable('argument_test.sh \\"a b\\"', LineAsString, 'value String')

SELECT *
FROM executable('argument_test.sh \\"a b\\"', LineAsString, 'value String')

   ┌─value─┐
1. │ \"a   │
   └───────┘
   
ch :) select * from executable('argument_test.sh \\\'a b\\\'', LineAsString, 'value String')

SELECT *
FROM executable('argument_test.sh \\\'a b\\\'', LineAsString, 'value String')

   ┌─value─┐
1. │ \'a   │
   └───────┘

```

### PR DESCRIPTION
**Pull request by leftmain**
Fixes #66634.

Currently, the executable table function fails to handle quoted arguments because it relies on `boost::split`, so this PR replaces it with `boost::program_options::split_unix` to support proper shell-style quoting instead of simple space-based splitting

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)


### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix parsing of shell-style quotes in arguments for the `executable` table function.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

<!---
Directly edit documentation source files in the "docs" folder with the same pull-request as code changes

or

Add a user-readable short description of the changes that should be added to docs.clickhouse.com below.

At a minimum, the following information should be added (but add more as needed).
- Motivation: Why is this function, table engine, etc. useful to ClickHouse users?

- Parameters: If the feature being added takes arguments, options or is influenced by settings, please list them below with a brief explanation.

- Example use: A query or command.
-->
N/A. Just a bug fix, no new features

### Details

Working example from the issue #66634:
```
│:) select * from executable('argument_test.sh "a b"', LineAsString, 'value String')                                                                                                                                                                                                    │
│                                                                                                                                                                                                                                                                                       │
│SELECT *                                                                                                                                                                                                                                                                               │
│FROM executable('argument_test.sh "a b"', LineAsString, 'value String')                                                                                                                                                                                                                │
│                                                                                                                                                                                                                                                                                       │
│Query id: 1c712b2d-673e-49a2-965c-24378db6f99a                                                                                                                                                                                                                                         │
│                                                                                                                                                                                                                                                                                       │
│   ┌─value─┐                                                                                                                                                                                                                                                                           │
│1. │ a b   │                                                                                                                                                                                                                                                                           │
│   └───────┘
```

### CODE REVIEW

File: src/TableFunctions/TableFunctionExecutable.cpp [hunk 1]
```diff
@@ -122,13 +122,11 @@ void TableFunctionExecutable::parseArguments(const ASTPtr & ast_function, Contex
...
     auto script_name_with_arguments_value = checkAndGetLiteralArgument<String>(args[0], "script_name_with_arguments_value");
-
-    VectorWithMemoryTracking<String> script_name_with_arguments;
-    boost::split(script_name_with_arguments, script_name_with_arguments_value, [](char c){ return c == ' '; });
+    auto script_name_with_arguments = boost::program_options::split_unix(script_name_with_arguments_value);
 
     script_name = std::move(script_name_with_arguments[0]);
     script_name_with_arguments.erase(script_name_with_arguments.begin());
-    arguments = std::move(script_name_with_arguments);
+    arguments.assign(script_name_with_arguments.begin(), script_name_with_arguments.end());
```
Comment (alexey-milovidov) [inline src/TableFunctions/TableFunctionExecutable.cpp:131]: Ok, but why this change?

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/TableFunctions/TableFunctionExecutable.cpp (hunk 1 above)
Comment (leftmain) [reply src/TableFunctions/TableFunctionExecutable.cpp:131]: These are different types:
- `TableFunctionExecutable::arguments` is a `VectorWithMemoryTracking<String>` (which is `std::vector` with a custom allocator)
-  `script_name_with_arguments` is a `std::vector<std::string>` (the only type `boost::program_options::split_unix` can return)

Alternatively, I could change `arguments` back to a standard `std::vector`. On one hand, this vector is small, so memory tracking may not be strictly necessary. On the other hand, it might affect type consistency (`VectorWithMemoryTracking<String>` a common way to handle command arguments in the repo):
```
:~/ClickHouse$ rg "VectorWithMemoryTracking<String>" src/
src/TableFunctions/TableFunctionExecutable.cpp
64:    VectorWithMemoryTracking<String> arguments;

src/Dictionaries/ExecutableDictionarySource.cpp
261:        VectorWithMemoryTracking<String> command_arguments;

src/Dictionaries/ExecutablePoolDictionarySource.h
30:        VectorWithMemoryTracking<String> command_arguments;

src/Dictionaries/ExecutablePoolDictionarySource.cpp
230:        VectorWithMemoryTracking<String> command_arguments;

src/Dictionaries/LibraryDictionarySource.cpp
183:    VectorWithMemoryTracking<String> attributes_names(dict_struct.attributes.size());

src/AggregateFunctions/AggregateFunctionDistinctDynamicTypes.cpp
71:        VectorWithMemoryTracking<String> sorted_data(data.begin(), data.end());

src/AggregateFunctions/AggregateFunctionDistinctJSONPaths.cpp
111:        VectorWithMemoryTracking<String> sorted_data(data.begin(), data.end());
236:        VectorWithMemoryTracking<std::pair<String, VectorWithMemoryTracking<String>>> sorted_data;
240:            VectorWithMemoryTracking<String> sorted_types(types.begin(), types.end());

src/Functions/UserDefined/ExternalUserDefinedExecutableFunctionsLoader.cpp
162:    VectorWithMemoryTracking<String> command_arguments;

src/Functions/UserDefined/UserDefinedExecutableFunctionFactory.cpp
271:    VectorWithMemoryTracking<String> command_arguments_with_parameters;

src/Storages/StorageExecutable.cpp
225:        VectorWithMemoryTracking<String> script_name_with_arguments
```

File: src/TableFunctions/TableFunctionExecutable.cpp [hunk 2]
```diff
@@ -122,13 +122,11 @@ void TableFunctionExecutable::parseArguments(const ASTPtr & ast_function, Contex
         args[i] = evaluateConstantExpressionOrIdentifierAsLiteral(args[i], context);
 
     auto script_name_with_arguments_value = checkAndGetLiteralArgument<String>(args[0], "script_name_with_arguments_value");
-
-    VectorWithMemoryTracking<String> script_name_with_arguments;
-    boost::split(script_name_with_arguments, script_name_with_arguments_value, [](char c){ return c == ' '; });
+    auto script_name_with_arguments = boost::program_options::split_unix(script_name_with_arguments_value);
 
     script_name = std::move(script_name_with_arguments[0]);
```
[the remark this answers is not in the document]
Comment (leftmain) [reply src/TableFunctions/TableFunctionExecutable.cpp:129]: Indeed, this caused the failure: `boost::split` returns `{""}` on the empty input, whereas `boost::program_options::split_unix` returns `{}`, which leads to segfault on the following line

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Thanks, all green!
