### PR TITLE
fix and test that S3Clients are reused

### LINKED ISSUE #58160: StorageS3*: client is recreated each time
It happens here 
https://github.com/ClickHouse/ClickHouse/blob/c6fe84d3fe7408c14fe899cdbc8e4eed118fe085/src/Storages/S3Queue/StorageS3Queue.cpp#L382

`static_configuration: 0` no matter is there was `NOSIGN` or not.

The `StorageS3::Configuration:` has
`no_sign_request: 1` when `NOSIGN` or `no_sign_request: 0` otherwise.

`s3_settings.auth_settings` from context has `no_sign_request: null`.

it is clear with `no_sign_request`. It is a bug.
But I do not still understand why `static_configuration` is `0` even when `NOSIGN` is explicitly set

### PR DESCRIPTION
**Pull request by CheSema**
fixes https://github.com/ClickHouse/ClickHouse/issues/58160

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit d5f86f671d34a22b42300ddf13ef2bd3ad795b00 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58573/d5f86f671d34a22b42300ddf13ef2bd3ad795b00/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58573/d5f86f671d34a22b42300ddf13ef2bd3ad795b00/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/IO/S3Common.cpp [hunk 1]
```diff
@@ -175,7 +172,7 @@ void AuthSettings::updateFrom(const AuthSettings & from)
         expiration_window_seconds = from.expiration_window_seconds;
 
     if (from.no_sign_request.has_value())
-        no_sign_request = *from.no_sign_request;
+        no_sign_request = from.no_sign_request;
```
Comment (antonio2368) [inline src/IO/S3Common.cpp:175]: what's the difference here?

File: src/IO/S3Common.cpp [hunk 2]
```diff
@@ -147,6 +138,12 @@ AuthSettings AuthSettings::loadFromConfig(const std::string & config_elem, const
     };
 }
 
+bool AuthSettings::hasUpdates(const AuthSettings & other) const
+{
+    AuthSettings copy = *this;
+    copy.updateFrom(other);
```
Comment (antonio2368) [inline src/IO/S3Common.cpp:144]: why do we need to do this extra copy?

File: src/IO/S3Common.cpp (hunk 1 above)
Comment (CheSema) [reply src/IO/S3Common.cpp:175]: It is the same actually. I just made it consistent with other code below.

File: src/IO/S3Common.cpp (hunk 2 above)
Comment (CheSema) [reply src/IO/S3Common.cpp:144]: Previously `operator ==() const = default` has been used as a function for detection are there any updated. 
But `operator ==() const = default` doesn't fit to it. It brings a bug to the code.

With that context, I had 2 choices:
- write custom `operator ==` -- bad choice, that become totally different fuction
- write custom `bool hasUpdate()` -- good, there are some options how to do it
  - write a big function which carries about each field/member -- hard to read
  - write a small one which reuses `update()` and native `operator ==()` -- I find it easy to read. Yes, there is a copy of a struct.
  - one more alternative it is alter `void update()` to `bool update()`, return value answers to the question were settings been updated.

Comment (antonio2368) [reply src/IO/S3Common.cpp:144]: what was the bug if we just use default `==`?

Comment (CheSema) [reply src/IO/S3Common.cpp:144]: It is a good question. In short all is wrong)

1. We compare full set of setting with some diff which we want to apply to the state. It is usually not equal. Exmp: when state has `option<bool>  = false` and the diff has `option<bool>  = null` and vice versa . `operator ==()` return false, but `update()` doesn't change anything. That is real bug apart from the bug in calculation of `static_configuration`.
2. Usually diff has `option<T>` fields and state should not have such fields. We use the same structure for state and diff of the setting. That bring more logic to figure out what the state is and how to apply diff. Example, when in the state `option<bool> no_sign_request = null` that actually means just `bool no_sign_request = false` but it is not clear from the code.

I could have solve p.2 but it would take more efforts. So I just fix p.1.

**Review by antonio2368 — APPROVED** [review]
