### PR TITLE
Fix `02597_column_update_and_replication`

### LINKED ISSUE #74798: Test 02597_column_update_and_replication failed
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/74688/6126fedd07f780de52666b0181ee008ba2fb4f69/stateless_tests__release__old_analyzer__s3__databasereplicated__[2_2].html

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The problem explained in the [comment](https://github.com/ClickHouse/ClickHouse/issues/74798#issuecomment-2603053994).

Closes: #74798

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Stateful tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit efe0a56b16b4e884ce82f5af442b00a928ba15ef with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74826/efe0a56b16b4e884ce82f5af442b00a928ba15ef/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs <a href="https://github.com/ClickHouse/ClickBench/">ClickBench</a> with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/cab5a3377cea82f6b1e8e41a17f4a2f4739aa404/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/00a0f1250d08fe308057a8839be23e5e4c49b111/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by serxa — APPROVED** [review]

**Comment by nickitat** [comment]
`Stateless tests (tsan, s3 storage) [2/3]` - https://github.com/ClickHouse/ClickHouse/issues/54748

File: tests/queries/0_stateless/02597_column_update_and_replication.sql [hunk 1]
```diff
@@ -15,11 +15,7 @@ set mutations_sync=0;
 ALTER TABLE test UPDATE d = d || toString(sleepEachRow(0.3)) where 1;
 
 ALTER TABLE test ADD COLUMN x UInt32 default 0;
-ALTER TABLE test UPDATE x = x + 1 where 1;
-ALTER TABLE test DROP COLUMN x SETTINGS mutations_sync = 2; --{serverError BAD_ARGUMENTS}
```
Comment (azat) [inline tests/queries/0_stateless/02597_column_update_and_replication.sql:19]: The initial test was for `checkDropCommandDoesntAffectInProgressMutations`, so it looks like the test is useless now, did I missed something?
