### PR TITLE
SpaceSaving remove last element from map fix

### LINKED ISSUE #17404: Query Fuzzer, `topK`, segfault.
https://clickhouse-test-reports.s3.yandex.net/17375/99073c26ee2692f8efe2ab14b2d8ae0fd813b80e/fuzzer/fuzzer.log

```
SELECT
    k,
    topK(v)
FROM 
(
    SELECT
        number % 7 AS k,
        arrayMap(x -> arrayMap(x -> if(x = 0, NULL, toString(x)), range(x)), range(intDiv(number, 1))) AS v
    FROM system.numbers
    LIMIT 257
)
GROUP BY k
ORDER BY k ASC
```

### PR DESCRIPTION
**Pull request by kitaisreal**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Mentioned in https://github.com/ClickHouse/ClickHouse/issues/17404.

Changelog category (leave one):
- Bug Fix

Changelog Entry:
Fix possible segfault in `topK` aggregate function. This closes #17404.

### CODE REVIEW

**Review by alexey-milovidov — COMMENTED** [review]
```
15061972 
00453_top_k.reference
```

The reference file is too large.
You can wrap `topK` calls with `length`.

File: src/Common/tests/hash_table_erase.cpp [hunk 1]
```diff
@@ -0,0 +1,43 @@
+#include <iomanip>
+#include <iostream>
+
+#include <Common/HashTable/HashMap.h>
+#include <Common/HashTable/HashSet.h>
+
+
+int main(int, char **)
```
Comment (alexey-milovidov) [inline src/Common/tests/hash_table_erase.cpp:8]: BTW, it's better to "unitize" this test (see `gtest_*.cpp` files), so it will be run in CI.

File: src/Common/tests/hash_table.cpp [hunk 2]
```diff
@@ -1,5 +1,5 @@
-#include <iostream>
 #include <iomanip>
```
Comment (alexey-milovidov) [inline src/Common/tests/hash_table.cpp:1]: BTW, this test is also not unitized (as it is very old), it will be better to convert it to unit test.

File: src/Common/HashTable/HashTable.h [hunk 3]
```diff
@@ -954,6 +958,67 @@ class HashTable :
...
+
+        if (buf[i].isZero(*this))
+        {
+            return;
+        }
+
+        /// We need to guarantee loop termination because there will be empty position
+        assert(m_size < grower.bufSize());
+
+        size_t j = i;
```
Comment (alexey-milovidov) [inline src/Common/HashTable/HashTable.h:999]: i, j, k are cryptic names, maybe invent some better names?

File: src/Common/HashTable/HashTable.h [hunk 4]
```diff
@@ -954,6 +958,67 @@ class HashTable :
...
+            j = grower.next(j);
+
+            if (buf[j].isZero(*this))
+            {
+                break;
+            }
+
+            size_t k = grower.place(buf[j].getHash(*this));
+
+            if (i <= j ? ((k <= i) || (k > j)) : ((k <= i) && (k > j)))
```
Comment (alexey-milovidov) [inline src/Common/HashTable/HashTable.h:1012]: memcpy implies `i != j` but here we check for `i <= j` that is confusing.

Comment (alexey-milovidov) [reply src/Common/HashTable/HashTable.h:1012]: It's strange to use ?: operator inside if condition.

&& and || will look better.

Comment (kitaisreal) [reply src/Common/HashTable/HashTable.h]: Agreed.

File: src/Common/HashTable/HashTable.h (hunk 3 above)
Comment (kitaisreal) [reply src/Common/HashTable/HashTable.h]: Agreed.

File: src/Common/tests/hash_table.cpp (hunk 2 above)
Comment (kitaisreal) [reply src/Common/tests/hash_table.cpp]: Updated.

File: src/Common/tests/hash_table_erase.cpp (hunk 1 above)
Comment (kitaisreal) [reply src/Common/tests/hash_table_erase.cpp]: Updated.

**Review by alexey-milovidov — APPROVED** [review]
