### PR TITLE
Better reporting of broken parts

### LINKED ISSUE #51125: Exception "while reading from part" does not tell you about the table name
**Use case**

`Code: 432. DB::Exception: Unknown codec family code: 60: (while reading column event_date): (while reading from part /var/lib/clickhouse/store/a07/a07660e7-b4aa-4520-a802-833765c28feb/202306_96661_96661_0/ from mark 0 with max_rows_to_read = 8): While executing MergeTreeThread. (UNKNOWN_CODEC) (version 23.5.1.34385 (official build))`

There is no table name in this exception.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Resolves #51125.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit ee68e85d310a6843ed833fe9c985a540620f9940 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51270/ee68e85d310a6843ed833fe9c985a540620f9940/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/MergeTree/IMergeTreeReader.cpp [hunk 1]
```diff
@@ -278,4 +278,13 @@ void IMergeTreeReader::checkNumberOfColumns(size_t num_columns_to_read) const
                         "Expected {}, got {}", requested_columns.size(), num_columns_to_read);
 }
 
+String IMergeTreeReader::getMessageForDiagnosticOfBrokenPart(size_t from_mark, size_t max_rows_to_read) const
+{
+    return fmt::format(
```
Comment (hanfei1991) [inline src/Storages/MergeTree/IMergeTreeReader.cpp:283]: new message did not contain disk type/name but old message did. Is it ok?

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp [hunk 2]
```diff
@@ -422,7 +422,7 @@ CheckResult ReplicatedMergeTreePartCheckThread::checkPart(const String & part_na
                 /// Don't count the part as broken if there is not enough memory to load it.
                 /// In fact, there can be many similar situations.
                 /// But it is OK, because there is a safety guard against deleting too many parts.
```
Comment (hanfei1991) [inline src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:424]: do we need to remove this comment?

File: src/Storages/MergeTree/IMergeTreeReader.cpp (hunk 1 above)
Comment (CurtizJ) [reply src/Storages/MergeTree/IMergeTreeReader.cpp:283]: No, it's was accidentally removed because of wrong conflicts resolution.

File: src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp (hunk 2 above)
Comment (CurtizJ) [reply src/Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp:424]: Yes, at least update it.

**Review by hanfei1991 — APPROVED** [review]
