### PR TITLE
Fix logical error `Logical error: Trying to extract chunk from ChunkBuffer before all inputs are finished` in correlated subqueries

### LINKED ISSUE #93832: Logical error: Trying to extract chunk from ChunkBuffer before all inputs are finished
### Describe the bug

Only happens in the current head. Easy to reproduce, seems related to a correlated subquery cc @novikd Maybe https://github.com/ClickHouse/ClickHouse/pull/91205 ?

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/55c92754-cff5-403f-8ecd-18c106f01dd2

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Trying to extract chunk from ChunkBuffer before all inputs are finished (unfinished inputs: 18446744073709551615)'.
<Fatal> : Format string: 'Trying to extract chunk from ChunkBuffer before all inputs are finished (unfinished inputs: {})'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000002683a8f2
1. src/Common/Exception.cpp:136: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000163dbce9
2. src/Common/Exception.h:172: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d9cda94
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d9cd591
4. src/Common/Exception.h:190: DB::Exception::Exception<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x000000000e2866c3
5. src/Processors/ChunkBuffer.h:36: DB::ChunkBuffer::extractNext() @ 0x0000000020c04ba4
6. src/Processors/Sources/ReadFromCommonBufferSource.h:23: DB::ReadFromCommonBufferSource::generate() @ 0x0000000020c04a13
7. src/Processors/ISource.cpp:144: DB::ISource::tryGenerate() @ 0x00000000204e8b2a
8. src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x00000000204e8801
9. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x0000000020504cf0
10. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x00000000204f6f38
11. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x00000000204f756c
12. src/Processors/Executors/PipelineExecutor.cpp:565: void std::__function::__policy_func<void ()>::__call_func[abi:se210105]<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0>(std::__function::__policy_storage const*) @ 0x00000000204f878e
13. contrib/llvm-project/libcxx/include/__functional/function.h:508: ? @ 0x000000001652ac39
14. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000016531028
15. contrib/llvm-project/libcxx/include/__functional/function.h:508: ? @ 0x0000000016528143
16. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: void* std::__thread_proxy[abi:se210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001652ecce
17. ? @ 0x00000000000a3d64
18. __clone3 @ 0x00000000001373bc
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
The `ISimpleTransform::prepare` method can call `onFinish` from two different code paths: when the output port finishes and when the input port finishes. This caused `SaveSubqueryResultToBufferTransform::onFinish` to call `chunk_buffer->onInputFinish` multiple times, leading to an underflow of `unfinished_inputs` counter in `ChunkBuffer`.

Added a `finished` flag to ensure `onInputFinish` is only called once, and added a `chassert` in `ChunkBuffer::onInputFinish` to catch underflow issues in debug builds.

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

See https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=95068&sha=bdb2c3ebf0d614b433e0d2861f7d32951a43ab79&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29&name_1=AST%20fuzzer%20%28amd_debug%29
https://github.com/ClickHouse/ClickHouse/pull/95068

Fixes https://github.com/ClickHouse/ClickHouse/issues/93832.

### Version info
- Merged into: `26.2.1.233`

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
The fix itself could be better, let's ask @novikd

File: src/Processors/QueryPlan/SaveSubqueryResultToBufferStep.cpp [hunk 1]
```diff
@@ -49,13 +49,28 @@ void SaveSubqueryResultToBufferStep::transformPipeline(QueryPipelineBuilder & pi
...
+    /// We only add transforms for the main data streams, not for totals/extremes.
+    /// The totals/extremes streams will pass through unchanged.
+    /// This avoids the issue where addSimpleTransform would create more transforms
+    /// than the number of main streams (because it also creates transforms for
+    /// totals and extremes), causing an underflow in the unfinished_inputs counter.
+    size_t streams = pipeline.getNumStreams();
+    if (pipeline.hasTotals())
+        --streams;
+    if (pipeline.hasExtremes())
+        --streams;
```
Comment (novikd) [inline src/Processors/QueryPlan/SaveSubqueryResultToBufferStep.cpp]: I just added a correct calculation of the number of inputs.

**Review by novikd — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok, but now the test fails.
