### PR TITLE
Fix VALID UNTIL clause resetting after restart

### LINKED ISSUE #66405: User expiration (VALID UNTIL clause) disappears after server restart
**Describe what's wrong**
When you create an [expiring user](https://clickhouse.com/docs/en/sql-reference/statements/create/user#valid-until-clause) with `CREATE USER ... VALID UNTIL`, then restart ClickHouse, the VALID UNTIL clause disappears, even if the restart occurs after the user has already expired.

**Does it reproduce on the most recent release?**

Reproduces on 24.5.3 and 24.3.3.

**How to reproduce**
Run ClickHouse with a default setup, and [enable SQL-driven access control](https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control). Then do the following:

1.
  ```sql
CREATE USER test VALID UNTIL '1970-01-01 00:00:01 UTC';
SHOW CREATE USER test;

--┌─CREATE USER test───────────────────────────────────┐
--│ CREATE USER test VALID UNTIL '1970-01-01 00:00:01' │
--└────────────────────────────────────────────────────┘
  ```
2. Attempt to log in as the test user (`clickhouse client --user test`), observe that it prompts for a password and always fails.
3. Restart ClickHouse.
4. Try to log in as the test user, observe that it now succeeds.
5. Observe that the VALID UNTIL clause has disappeared from the CREATE USER statement.
  ```sql
SHOW CREATE USER test;

--┌─CREATE USER test─┐
--│ CREATE USER test │
--└──────────────────┘
  ```

**Expected behavior**
The VALID UNTIL clause should be preserved across server restarts, and logins to expired users should not succeed.

**Additional context**
I've noticed that specifying a VALID UNTIL clause with Unix time 0 ('1970-01-01 00:00:00 UTC') is the same as the default when you specify nothing ('infinity'), so I'm guessing there's some time field on the user instance that's being zero-initialized and not properly populated when the user is reloaded at startup.

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the VALID UNTIL clause in the user definition resetting after a restart. Closes https://github.com/ClickHouse/ClickHouse/issues/66405

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit fa2270fd59c0de91d45ac50f2064d31f568935e4 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66409/fa2270fd59c0de91d45ac50f2064d31f568935e4/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

File: src/Interpreters/Access/InterpreterCreateUserQuery.cpp [hunk 1]
```diff
@@ -259,7 +259,22 @@ void InterpreterCreateUserQuery::updateUserFromQuery(User & user, const ASTCreat
     if (query.auth_data)
         auth_data = AuthenticationData::fromAST(*query.auth_data, {}, !query.attach);
 
-    updateUserFromQueryImpl(user, query, auth_data, {}, {}, {}, {}, {}, allow_no_password, allow_plaintext_password, true);
+    std::optional<time_t> valid_until;
```
Comment (Algunenano) [inline src/Interpreters/Access/InterpreterCreateUserQuery.cpp:262]: Doesn't it make more sense to do this inside `updateUserFromQueryImpl` instead of duplicating the code. We always pass the query itself, so passing the parsed value doesn't make much sense unless it was changed elsewhere

Comment (evillique) [reply src/Interpreters/Access/InterpreterCreateUserQuery.cpp:262]: It is not exactly the same since we parse the date time in a specific (more strict) format in case of an attach query and don't fill in the substitutions. `updateUserFromQueryImpl` is basically a setter function that is passed to access storage, so I am not sure if we want to throw parsing or other exceptions caused by bad arguments passed by user from there.

Otherwise, I can do it if you think it makes sense.

Comment (evillique) [reply src/Interpreters/Access/InterpreterCreateUserQuery.cpp:274]: I implemented an intermediate option with parsing taking place in a separate function, let me know if you think I should move it into `updateUserFromQueryImpl`

**Review by Algunenano — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
@evillique, everything has failed, please merge with the master branch and fix the remaining tests.

**Comment by evillique** [comment]
> @evillique, everything has failed, please merge with the master branch and fix the remaining tests.

It looks like only clang tidy build was broken and no related tests failed, so I updated it to the fresh master and will merge it as soon as the tests are finished.

**Comment by alexey-milovidov** [comment]
@evillique also merge this into your PR: https://github.com/ClickHouse/ClickHouse/pull/66623
