### PR TITLE
Fix parallel_view_processing

### LINKED ISSUE #29621: Parallel view processing no longer working
**Describe what's wrong**

In master, `parallel_view_processing` doesn't have any effect and the MV are executed sequentially. 

**Does it reproduce on recent release?**

Only master.

Taken from parallel_mv.xml perf test:

```sql
create table main_table (number UInt64) engine = MergeTree order by tuple();
create materialized view mv_1 engine = MergeTree order by tuple() as
        select number, toString(number) from main_table where number % 13 != 0;
create materialized view mv_2 engine = MergeTree order by tuple() as
        select number, toString(number) from main_table where number % 13 != 1;
create materialized view mv_3 engine = MergeTree order by tuple() as
        select number, toString(number) from main_table where number % 13 != 3;
create materialized view mv_4 engine = MergeTree order by tuple() as
        select number, toString(number) from main_table where number % 13 != 4;
```

21.9.4:
* No parallel: Elapsed: 1.333 sec
* With parallel view processing: 0.588 sec

21.10.2.8264:
* No parallel: 1.372 sec
* Parallel: 0.582

21.11.1.8263 from master:
* No parallel: 1.415 sec
* With parallel: 1.423 sec

**Additional context**

Checking the [stats of CI](https://play-ci.clickhouse.com/play?user=play#V0lUSCAwLjA1IEFTIHMKU0VMRUNUIG9sZF9zaGEsIG5ld19zaGEsIGV2ZW50X3RpbWUsIG1lc3NhZ2UsIG9sZF92YWx1ZSBBUyBgb2xkIHNlcnZlcmAsICAgbmV3X3ZhbHVlIEFTIGBuZXcgc2VydmVyYCwgYmVmb3JlIEFTIGBwcmV2IDExIHJ1bnNgLCBhZnRlciBBUyBgbmV4dCAxMSBydW5zYCwgICAgZGlmZiBBUyBgZGlmZiwgcmF0aW9gLCBzdGF0X3RocmVzaG9sZF9oaXN0b3JpY2FsIEFTIGBzdGF0IHRocmVzaG9sZCwgcmF0aW8sIGhpc3RvcmljYWxgLCBzdGF0X3RocmVzaG9sZCBBUyBgc3RhdCB0aHJlc2hvbGQsIHJhdGlvLCBwZXItcnVuYCwgY3B1X21vZGVsLHF1ZXJ5X2Rpc3BsYXlfbmFtZQpGUk9NIAooU0VMRUNUICosIHJ1bl9hdHRyaWJ1dGVzX3YxLnZhbHVlIEFTIGNwdV9tb2RlbCwKICAgICAgICBtZWRpYW4ob2xkX3ZhbHVlKSBPVkVSIChQQVJUSVRJT04gQlkgcnVuX2F0dHJpYnV0ZXNfdjEudmFsdWUsIHRlc3QsIHF1ZXJ5X2luZGV4LCBxdWVyeV9kaXNwbGF5X25hbWUgT1JERVIgQlkgZXZlbnRfZGF0ZSBBU0MgUk9XUyBCRVRXRUVOIDExIFBSRUNFRElORyBBTkQgQ1VSUkVOVCBST1cpIEFTIGJlZm9yZSwKICAgICAgICBtZWRpYW4obmV3X3ZhbHVlKSBPVkVSIChQQVJUSVRJT04gQlkgcnVuX2F0dHJpYnV0ZXNfdjEudmFsdWUsIHRlc3QsIHF1ZXJ5X2luZGV4LCBxdWVyeV9kaXNwbGF5X25hbWUgT1JERVIgQlkgZXZlbnRfZGF0ZSBBU0MgUk9XUyBCRVRXRUVOIENVUlJFTlQgUk9XIEFORCAxMSBGT0xMT1dJTkcpIEFTIGFmdGVyLAogICAgICAgIHF1YW50aWxlRXhhY3QoMC45NSkoYWJzKGRpZmYpKSBPVkVSIChQQVJUSVRJT04gQlkgcnVuX2F0dHJpYnV0ZXNfdjEudmFsdWUsIHRlc3QsIHF1ZXJ5X2luZGV4LCBxdWVyeV9kaXNwbGF5X25hbWUgT1JERVIgQlkgZXZlbnRfZGF0ZSBBU0MgUk9XUyBCRVRXRUVOIDM3IFBSRUNFRElORyBBTkQgQ1VSUkVOVCBST1cpIEFTIHN0YXRfdGhyZXNob2xkX2hpc3RvcmljYWwKICAgIEZST00gcGVyZnRlc3QucXVlcnlfbWV0cmljc192MgogICAgTEVGVCBKT0lOIHBlcmZ0ZXN0LnJ1bl9hdHRyaWJ1dGVzX3YxIFVTSU5HIChvbGRfc2hhLCBuZXdfc2hhKQogICAgV0hFUkUgKGF0dHJpYnV0ZSA9ICdsc2NwdS1tb2RlbC1uYW1lJykgQU5EIChtZXRyaWMgPSAnY2xpZW50X3RpbWUnKQogICAgICAgIC0tIG9ubHkgZm9yIGNvbW1pdHMgaW4gbWFzdGVyCiAgICAgICAgQU5EIChwcl9udW1iZXIgPSAwKQogICAgICAgIC0tIHNlbGVjdCB0aGUgcXVlcmllcyB3ZSBhcmUgaW50ZXJlc3RlZCBpbgogICAgICAgIEFORCAodGVzdCA9ICdwYXJhbGxlbF9tdicpCikgQVMgdApBTlkgTEVGVCBKT0lOIGBnaC1kYXRhYC5jb21taXRzIE9OIG5ld19zaGEgPSBzaGEKV0hFUkUKICAgIC0tIENoZWNrIGZvciBhIHBlcnNpc3RlbnQgYW5kIHNpZ25pZmljYW50IGNoYW5nZSBpbiBxdWVyeSBydW4gdGltZSwgaW50cm9kdWNlZCBieSBhIGNvbW1pdDoKICAgIC0tIDEpIG9uIGEgaGlzdG9yaWNhbCBncmFwaCBvZiBxdWVyeSBydW4gdGltZSwgdGhlcmUgaXMgYSBzdGVwIGJldHdlZW4gdGhlIGFkamFjZW50IGNvbW1pdHMsCiAgICAtLSB0aGF0IGlzIGhpZ2hlciB0aGFuIHRoZSBub3JtYWwgdmFyaWFuY2UsCiAgICAoKChhYnMoYWZ0ZXIgLSBiZWZvcmUpIC8gaWYoYWZ0ZXIgPiBiZWZvcmUsIGFmdGVyLCBiZWZvcmUpKSBBUyBzdGVwX2hlaWdodCkgPj0gZ3JlYXRlc3Qocywgc3RhdF90aHJlc2hvbGRfaGlzdG9yaWNhbCkpCiAgICAtLSAyKSBpbiBzaWRlLXRvLXNpZGUgY29tcGFyaXNvbiBvZiB0aGVzZSB0d28gY29tbWl0cywgdGhlcmUgd2FzIGEgc3RhdGlzdGljYWxseSBzaWduaWZpY2FudCBkaWZmZXJlbmNlCiAgICAtLSB0aGF0IGlzIGFsc28gaGlnaGVyIHRoYW4gdGhlIG5vcm1hbCB2YXJpYW5jZSwKICAgICAgICBBTkQgKGFicyhkaWZmKSA+PSBncmVhdGVzdChzdGF0X3RocmVzaG9sZCwgc3RhdF90aHJlc2hvbGRfaGlzdG9yaWNhbCwgcykpCiAgICAtLSAzKSBmaW5hbGx5LCB0aGlzIHNpZGUtdG8tc2lkZSBkaWZmZXJlbmNlIGlzIG9mIG1hZ25pdHVkZSBjb21wYXJhYmxlIHRvIHRoZSBzdGVwIGluIGhpc3RvcmljYWwgZ3JhcGhzLgogICAgICAgIEFORCAoYWJzKGRpZmYpID49ICgwLjcgKiBzdGVwX2hlaWdodCkpCm9yZGVyIGJ5IGV2ZW50X3RpbWUgZGVzYwpmb3JtYXQgVmVydGljYWwKCgo=) it points to #28582 as the culptrit.

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `parallel_view_processing`

Fixes: #28582 (cc @KochetovNicolai )
Fixes: #29621
Closes: #29760

*NOTE: marked as not for changelog, since the original PR has not been included to any release yet*

### CODE REVIEW

File: tests/queries/0_stateless/01275_parallel_mv.reference [hunk 1]
```diff
@@ -1,4 +1,27 @@
...
+8
+select count() from testX;
 10
+select count() from testXA;
 10
+select count() from testXB;
 0
+select count() from testXC;
 10
+set parallel_view_processing=0;
```
Comment (azat) [inline tests/queries/0_stateless/01275_parallel_mv.reference:15]: Note, that now (I guess after #28582) with `parallel_view_processing=0` MVs that goes after MV with an error will be processed too.

Comment (Algunenano) [reply tests/queries/0_stateless/01275_parallel_mv.reference:15]: That was changed in 21.9 so it was deterministic and all views were processed fully; otherwise they could be aborted after any of the 3 steps (prefix, write, suffix) and it was impossible to know what was the status of the target table. So no (new) behaviour change.

Comment (azat) [reply tests/queries/0_stateless/01275_parallel_mv.reference:15]: Ok, got it, thanks!

File: src/Processors/QueryPipelineBuilder.cpp [hunk 2]
```diff
@@ -139,6 +139,7 @@ void QueryPipelineBuilder::addChains(std::vector<Chain> chains)
 {
     checkInitializedAndNotCompleted();
     pipe.addChains(std::move(chains));
+    setMaxThreads(pipe.maxParallelStreams());
```
Comment (KochetovNicolai) [inline src/Processors/QueryPipelineBuilder.cpp:142]: Ok, but I would prefer to set the limit at call place.

**Review by KochetovNicolai — APPROVED** [review]

**Review by KochetovNicolai — APPROVED** [review]
