### PR TITLE
Fix sumMapFiltered with NaN values

### LINKED ISSUE #58741: sumMapFiltered aggregate function wrong result starting from 23.11
```sql
SELECT sumMapFiltered([6.7])([x],[y]) FROM values('x Float64, y Float64', (0, 1), (1, 2.3), (nan,inf), (6.7,3), (4,4), (5, 1))
```

Before 23.11:
``` 
([6.7],[3])
````

Starting from 23.11:
```
 ([nan],[inf])
````

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix sumMapFiltered with NaN values. NaN values are now placed at the end (instead of randomly) and considered different from any values. `-0` is now also treated as equal to `0`; since 0 values are discarded, `-0` values are discarded too.

### Documentation entry for user-facing changes

Implement NaN handling in `DB::Field::operator<`, which is used by `std::set<DB::Field>`

Closes https://github.com/ClickHouse/ClickHouse/issues/58741

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit f08202785dabe40ccd845561ef0edad27030e625 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58959/f08202785dabe40ccd845561ef0edad27030e625/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58959/f08202785dabe40ccd845561ef0edad27030e625/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Core/Field.h [hunk 1]
```diff
@@ -1029,3 +1029,92 @@ struct fmt::formatter<DB::Field>
...
+            using Which = DB::Field::Types::Which;
+            size_t type_hash = std::hash<UInt8>{}(field.getType());
+            switch (field.getType())
+            {
+            case Which::Null:
+                return 0;
+            case Which::Bool:
+                [[fallthrough]];
+            case Which::UInt64:
+                return type_hash ^ std::hash<UInt64>{}(field.get<UInt64>());
```
Comment (alexey-milovidov) [inline src/Core/Field.h:1049]: `std::hash` is very bad for integers, see:
https://presentations.clickhouse.com/hash_tables/#8

Xor of hashes is very bad for hash combining, see:
https://presentations.clickhouse.com/hash_tables/#11

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/Core/Field.h [hunk 2]
```diff
@@ -1029,3 +1029,92 @@ struct fmt::formatter<DB::Field>
...
+            case Which::Float64:
+                return type_hash ^ std::hash<Float64>{}(field.get<Float64>());
+            case Which::String:
+                return type_hash ^ std::hash<String>{}(field.get<String>());
+            case Which::Array:
+            {
+                auto const & array = field.get<DB::Array>();
+                size_t res = type_hash;
+                for (const auto & e : array)
+                    res ^= std::hash<DB::Field>{}(e);
```
Comment (alexey-milovidov) [inline src/Core/Field.h:1075]: Not good.

File: src/Core/Field.h (hunk 1 above)
Comment (Algunenano) [reply src/Core/Field.h:1049]: Reimplementing with intHash and `hash(x) ^ y`.

Comment (Algunenano) [reply src/Core/Field.h:1049]: After implementing it I've decided to instead fix `Field::operator<()`. I might keep the implementation in a separate file in case we want to use it in the future (although in a different file, to avoid pushing even more deps to Field.h

File: src/Core/FieldHash.h [hunk 3]
```diff
@@ -0,0 +1,147 @@
+#pragma once
```
Comment (Algunenano) [inline src/Core/FieldHash.h:1]: I introduced this but it's not used. We could remove it or keep it in case we want to use std::unordered_map / std::unordered_set of DB::Field. I did not include it into Field.h itself to avoid adding more dependencies to a file that's used in almost 3000 other files.

Comment (Algunenano) [reply src/Core/FieldHash.h]: Nevermind, the style did not like it, so I've removed it.

**Review by alexey-milovidov — APPROVED** [review]

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
It looks like the newly added test is passed on the old version.

**Comment by Algunenano** [comment]
It looks like the check is broken. I don’t see it running the tests. Here is fiddle: https://fiddle.clickhouse.com/7720d824-6c43-46b7-b708-20538042bd2a

**Comment by Algunenano** [comment]
Need to investigate the perf failures. Something odd is going on

**Comment by Algunenano** [comment]
Unrelated failures. The perf failures (`Arrays passed to arrayMap must have equal size`) did not happen again after improving the error message to get better diagnostics.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by azat** [comment]
This PR indeed breaks perf tests, see https://github.com/ClickHouse/ClickHouse/pull/59287 for details, though maybe it worth to fix the behavior of `sumMap` for negative zeroes (since it is a backward incompatible change), or at least document it in `Backward incompatible` section.

File: src/Functions/array/FunctionArrayMapped.h [hunk 4]
```diff
@@ -335,7 +335,11 @@ class FunctionArrayMapped : public IFunction
                         && column_array->getOffsets() != typeid_cast<const ColumnArray::ColumnOffsets &>(*offsets_column).getData())
                         throw Exception(
                             ErrorCodes::SIZES_OF_ARRAYS_DONT_MATCH,
-                                "Arrays passed to {} must have equal size", getName());
+                            "Arrays passed to {} must have equal size. Argument {} has size {}, but expected {}",
```
Comment (azat) [inline src/Functions/array/FunctionArrayMapped.h:338]: This works incorrectly, it will always match, since this is the number of rows in the column, not number of elements in array.

**Comment by Algunenano** [comment]
> This PR indeed breaks perf tests, see https://github.com/ClickHouse/ClickHouse/pull/59287 for details, though maybe it worth to fix the behavior of sumMap for negative zeroes (since it is a backward incompatible change), or at least document it in Backward incompatible section.

TBH, I don't understand why sumMap doesn't return zeroes (positive or now negative). It's not documented anywhere and it seems to be caused by bad code design. This doesn't make any sense to me:

```
SELECT sumMap(['foo', 'foo'], [-5., 5])

Query id: b81635c5-31a6-4fff-9661-a86420136cad

┌─sumMap(['foo', 'foo'], [-5., 5])─┐
│ ([],[])                          │
└──────────────────────────────────┘
```

It seems it was added as a bug and then people started to rely on it
