### PR TITLE
Fix test `03237_insert_sparse_columns_mem`

### LINKED ISSUE #73047: 03272_prewarm_mark_cache_add_column is flaky
Introduced in https://github.com/ClickHouse/ClickHouse/pull/71996

https://s3.amazonaws.com/clickhouse-test-reports/73013/ee1c650e38663fc9f0143be4b7d2a4240e8fb509/stateless_tests__ubsan__[2_2].html

```
2024-12-10 18:53:37 Reason: result differs with reference:  
2024-12-10 18:53:37 --- /repo/tests/queries/0_stateless/03272_prewarm_mark_cache_add_column.reference	2024-12-10 18:37:07.300941079 +0400
2024-12-10 18:53:37 +++ /repo/tests/queries/0_stateless/03272_prewarm_mark_cache_add_column.stdout	2024-12-10 18:53:37.912983442 +0400
2024-12-10 18:53:37 @@ -1,3 +1,3 @@
2024-12-10 18:53:37  1	0
2024-12-10 18:53:37  2	2
2024-12-10 18:53:37 -0
2024-12-10 18:53:37 +6
2024-12-10 18:53:37 
2024-12-10 18:53:37 
2024-12-10 18:53:37 Settings used in the test: --max_insert_threads 1 --group_by_two_level_threshold 235716 --group_by_two_level_threshold_bytes 10616551 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 3853836 --max_read_buffer_size 623196 --prefer_localhost_replica 0 --max_block_size 86998 --max_joined_block_size_rows 97669 --max_threads 1 --optimize_append_index 1 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 13 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 40447698 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 10737418240 --local_filesystem_read_method read --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 2 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 128Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 1Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_aggregate_expressions 1 --compile_sort_description 1 --merge_tree_coarse_index_granularity 12 --optimize_distinct_in_order 1 --max_bytes_before_external_sort 3709708742 --max_bytes_before_external_group_by 0 --max_bytes_before_remerge_sort 1343824809 --min_compress_block_size 1851527 --max_compress_block_size 3128930 --merge_tree_compact_parts_min_granules_to_multibuffer_read 10 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 5552394 --http_wait_end_of_query True --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 3 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone America/Mazatlan --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.52 --prefer_external_sort_block_bytes 1 --cross_join_min_rows_to_compress 1 --cross_join_min_bytes_to_compress 0 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 10 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 0 --query_plan_join_swap_table auto --output_format_native_write_json_as_string 1 --enable_vertical_final 1
2024-12-10 18:53:37 
2024-12-10 18:53:37 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 3493334277 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 10737418240 --index_granularity_bytes 6295991 --merge_max_block_size 2670 --index_granularity 60009 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 70755 --primary_key_compress_block_size 13544 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 114873983 --compact_parts_max_bytes_to_buffer 477509730 --compact_parts_max_granules_to_buffer 18 --compact_parts_merge_max_bytes_to_prefetch_part 15503367 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 100 --old_parts_lifetime 319 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1
2024-12-10 18:53:37 
2024-12-10 18:53:37 Database: test_xfpnouw2
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

Fixes #73047.

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 05da266790a9986c5a3018747946e7e733fc0480 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75242/05da266790a9986c5a3018747946e7e733fc0480/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs <a href="https://github.com/ClickHouse/ClickBench/">ClickBench</a> with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/51a2845a156a285ad3926e1af05daf5822c5c617/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/03047_on_fly_mutations_multiple_updates.sql [hunk 1]
```diff
@@ -1,4 +1,4 @@
--- Tags: no-random-merge-tree-settings, no-random-settings
+-- Tags: no-random-merge-tree-settings, no-random-settings, no-parallel
```
Comment (antonio2368) [inline tests/queries/0_stateless/03047_on_fly_mutations_multiple_updates.sql:1]: why?
same question for `_rmt` version

Comment (CurtizJ) [reply tests/queries/0_stateless/03047_on_fly_mutations_multiple_updates.sql:1]: I added comments to the tests.

**Review by antonio2368 — APPROVED** [review]

**Comment by CurtizJ** [comment]
Two tests failed: `02944_dynamically_change_filesystem_cache_size`, `02676_analyzer_limit_offset`. It doesn't seem related.
