### PR TITLE
Fix msan issue in randomStringUTF8(<uneven number>)

### LINKED ISSUE #49672: AST Fuzzer (msan): use-of-uninitialized-value in StringSearcher
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/49636/fe02317d4595ddcea9837dc5a33f047242653642/fuzzer_astfuzzermsan/report.html)

Stacks:
https://pastila.nl/?030ef1b1/7e71a0d51ee89c61ce8ca97856c021e2
https://pastila.nl/?0269eed6/0c3c7e9b0b6c6db8cbc7dbeed06ce055
https://pastila.nl/?0269eed6/2d09fe39393369b364c2d304993d12cc

Look like something related to string searcher
CC @rschu1ze

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes #49672

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix uninitialized memory when using randomStringUTF8() with an uneven codepoint count

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit 1f3b1c47af6ce82397f5e4d357537d7410b4d506 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49750/1f3b1c47af6ce82397f5e4d357537d7410b4d506/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Common/Volnitsky.h [hunk 1]
```diff
@@ -729,15 +727,15 @@ class MultiVolnitskyBase
 
 
 using Volnitsky = VolnitskyBase<true, true, ASCIICaseSensitiveStringSearcher>;
-using VolnitskyUTF8 = VolnitskyBase<true, false, ASCIICaseSensitiveStringSearcher>; /// exactly same as Volnitsky
+using VolnitskyUTF8 = VolnitskyBase<true, false, UTF8CaseSensitiveStringSearcher>;
```
Comment (vdimir) [inline src/Common/Volnitsky.h:730]: Why VolnitskyUTF8 used to use ASCII searcher? Doesn't look like type, because there was a comment

**Review by vdimir — APPROVED** [review]
