### PR TITLE
Fixing "Invalid number of rows in Chunk" with lightweight deletes

### LINKED ISSUE #40651: Logical error: Invalid number of rows in Chunk (when using lightweight delete)
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
new command "delete from" occasionally fails and throws an error on any table it happens to be executed against

**How to reproduce**

I'm not sure how to reproduce this as it seems completely random when it happens.

* Which ClickHouse server version to use

22.8.1.2097 (official build)

* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved

create table url_na_log
(
    SiteId          UInt32,
    DateVisit       Date,
    Url             String,
    UrlHash         UInt64,
    UniquePageViews UInt64,
    PageViews       UInt64,
    Bounces         UInt64,
    Entrances       UInt64,
    Exits           UInt64,
    PageLoadTime    Float32,
    Duration        UInt64,
    TotalDuration   UInt64,
    CountryName     String,
    StateName       String,
    CityName        String
)
    engine = MergeTree()
        PARTITION BY toYYYYMM(DateVisit)
        TTL DateVisit + INTERVAL 730 DAY
        ORDER BY (SiteId, DateVisit,CountryName,StateName,CityName,Url,UrlHash)
        SETTINGS index_granularity = 8192;

* Sample data for all these tables, use [clickhouse-obfuscator]

SiteId,DateVisit,'http://someurl.com',UrlHash,UniquePageViews,PageViews,Bounces,Entrances,Exits,PageLoadTime,Duration,TotalDuration,CountryName,StateName,CityName
206,2022-08-20,http://someurl.com,14834984358841950838,1,1,1,1,1,6,0,0,Antigua and Barbuda,Saint John,Saint John's
206,2022-08-20,http://someurl.com,13712571174015756189,1,1,1,1,1,10,0,0,Antigua and Barbuda,Saint Peter,Parham
206,2022-08-20,http://someurl.com,13045909168297867568,1,1,0,0,1,1,0,0,Aruba,Aruba,Oranjestad
206,2022-08-20,http://someurl.com,10402145386108460621,1,1,0,0,1,1,0,0,Aruba,Aruba,Oranjestad
206,2022-08-20,http://someurl.com,14393843429037430790,1,1,0,1,0,25,0,5,Aruba,Aruba,Oranjestad
206,2022-08-20,http://someurl.com,8020371086158661466,1,1,0,1,0,10,0,2,Aruba,Aruba,Oranjestad
206,2022-08-20,http://someurl.com,18148625793235144982,1,1,1,1,1,991,0,0,Bahamas,New Providence,Nassau
206,2022-08-20,http://someurl.com,4124249807051967616,3,4,1,3,2,187.75,0,178,Barbados,Saint Michael,Bridgetown
206,2022-08-20,http://someurl.com,15986728358981925438,1,2,0,0,1,404.5,0,14,Barbados,Saint Michael,Bridgetown
206,2022-08-20,http://someurl.com,6183460368517011299,1,1,1,1,1,9,0,0,Belize,Belize,Belize City
206,2022-08-20,http://someurl.com,15986728358981925438,1,1,1,1,1,9,0,0,Belize,Belize,Belize City
206,2022-08-20,http://someurl.com,1899826446909527700,10,11,8,10,9,231.63637,0,18,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,9546716705715622668,1,1,0,0,1,0,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,7618588109351181755,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,6046648213051826790,2,2,0,0,2,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,737591207347186672,1,1,0,0,1,0,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,18160025937253821314,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,9899401848846057271,1,1,0,0,0,1,0,70,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,4162722060959086320,2,2,1,1,2,0.5,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,452905313417854173,1,1,0,0,0,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,18214249339417175046,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3062939672349444070,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3129029941432017978,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3247644969313855078,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,477928152093667836,3,3,1,1,3,0.6666667,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,15800753931814496722,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,14317856065777638343,1,1,0,0,1,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,9661495952711760853,1,1,0,0,1,0,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,17448941459428242808,2,2,0,0,2,0.5,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,14175638096105338,1,1,0,0,0,1,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,16462862077400701897,2,2,2,2,2,66.5,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,11869671953902229235,1,1,1,1,1,100,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,8675739909535592405,1,1,1,1,1,7,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,13737580010622714795,1,1,1,1,1,541,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,5820424819651434058,4,4,3,4,3,24.75,0,240,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,10824131320270348554,1,1,0,0,1,86,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,16478232107478764765,1,1,1,1,1,10,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,14022144213268325582,1,1,0,1,0,17,0,3,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,4182441687366257263,1,1,1,1,1,5,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,10137956043142453669,1,1,0,1,0,12,0,2,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,1129288651464321895,1,1,0,0,1,6,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,8471043265410181871,1,1,1,1,1,8,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,16689120262499163142,1,1,0,1,0,7,0,1,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,13570026696672484589,1,1,0,0,1,9,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,18133527325438134188,1,1,0,1,0,100,0,2,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3710569133307537667,1,1,0,1,0,123,0,2,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,12952667749072357105,1,1,0,1,0,106,0,2,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3855332652456530919,2,2,0,2,0,114,0,16,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,17894724967939028344,1,1,0,1,0,90,0,2,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,10072118804318402981,1,1,0,1,0,10,0,3,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,11938278778041902232,1,1,0,1,0,11,0,1,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,11844179890914806141,1,1,0,1,0,20,0,1,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,15625232388759477446,1,1,0,0,0,92,0,26,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,5613752836775496652,1,1,0,1,0,8,0,4,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,12219933988635525995,2,2,0,2,0,7,0,3,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,838679288188702546,1,1,0,1,0,146,0,1,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,9981703118863607825,1,1,0,0,0,116,0,3,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,12550277140029476585,1,1,0,1,0,12,0,1,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,5094600822715966297,2,2,1,2,1,7.5,0,1,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,12601242452660122980,2,2,0,1,0,8.5,0,2,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,9288107175792582931,1,1,0,1,1,6,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3830991492355738336,1,1,1,1,1,7,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,15800014026673450333,1,1,1,1,1,6,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,2096890569575269753,1,1,1,1,1,5,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,10223831461805466928,1,1,1,1,1,70,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,5012921533700387893,6,7,4,6,5,6.428571,0,1777,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,13712571174015756189,3,3,3,3,3,8,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,2001665996102123032,1,4,0,1,0,67.25,0,283,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,15986728358981925438,8,15,1,7,8,224.13333,0,38,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,3098435693104928063,1,1,1,1,1,19,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,1123526652268590525,1,1,0,0,1,13,0,0,Canada,Alberta,Calgary
206,2022-08-20,http://someurl.com,15986728358981925438,1,1,1,1,1,633,0,0,Canada,Alberta,Camrose
206,2022-08-20,http://someurl.com,1899826446909527700,6,6,6,6,6,72.333336,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,1332624377919777055,1,1,0,0,1,0,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,259549802779970955,1,1,0,0,1,0,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,17416287209263962487,1,1,0,0,1,1,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,10109270757046376937,1,1,0,0,1,1,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,5268160270674935149,1,1,0,0,1,1,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,9661495952711760853,2,2,0,0,2,442,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,13414308503523165901,2,2,2,2,2,7,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,15283428054663549429,1,1,1,1,1,8,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,5051859335394255485,1,1,0,1,0,176,0,1,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,1604211581031131161,1,1,0,1,0,144,0,4,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,7684163173139975246,1,1,0,1,0,27,0,2,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,1440962019752748800,1,1,0,1,0,10,0,1,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,12109985804349109197,1,1,0,1,0,36,0,2,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,5094600822715966297,2,2,0,2,0,8,0,3,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,7744008991450186838,1,1,1,1,1,11,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,5012921533700387893,2,2,2,2,2,8.5,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,7637926963831027281,1,1,0,1,0,70,0,27,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,13712571174015756189,2,2,1,1,2,34.5,0,0,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,15986728358981925438,2,5,0,2,2,220.8,0,629,Canada,Alberta,Edmonton
206,2022-08-20,http://someurl.com,13712571174015756189,1,1,1,1,1,10,0,0,Canada,Alberta,Fort McMurray
206,2022-08-20,http://someurl.com,12601242452660122980,1,1,1,1,1,9,0,0,Canada,Alberta,Lethbridge
206,2022-08-20,http://someurl.com,15986728358981925438,1,1,1,1,1,91,0,0,Canada,Alberta,Lethbridge
206,2022-08-20,http://someurl.com,13712571174015756189,1,1,1,1,1,9,0,0,Canada,Alberta,Mundare
206,2022-08-20,http://someurl.com,1899826446909527700,1,2,0,1,0,31,0,52,Canada,Alberta,Red Deer
206,2022-08-20,http://someurl.com,1778728408626810735,1,1,0,0,1,1,0,0,Canada,Alberta,Red Deer
206,2022-08-20,http://someurl.com,10261655128591171862,1,1,0,0,1,1,0,0,Canada,Alberta,Red Deer
206,2022-08-20,http://someurl.com,9661495952711760853,1,1,0,0,0,1,0,4,Canada,Alberta,Red Deer

* Queries to run that lead to unexpected result

delete from url_na_log where SiteId = 206
                    and DateVisit >= '2022-08-20'
                    and DateVisit < '2022-08-21'

**Expected behavior**

I expect it to not throw an error and work correctly

**Error message and/or stacktrace**

2022.08.26 02:01:42.673678 [ 1543150 ] {c2dafbe2-d9f5-42ad-abf4-cc6a15e6465c} <Error> executeQuery: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt32 position 1: expected 6380, got 2807: While executing MergeTreeThread. (LOGICAL_ERROR) (version 22.8.1.2097 (official build)) (from 10.10.64.128:52314) (in query: select count() from url_na_log where SiteId = 206 and DateVisit >= '2022-08-20' and DateVisit < '2022-08-21'), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa38beba in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x15cfae0c in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::generate() @ 0x1608b103 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x15d0d475 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x15d0cf86 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x15d29fea in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15d1dcfc in /usr/bin/clickhouse
7. ? @ 0x15d20cfb in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa44f7cc in /usr/bin/clickhouse
9. ? @ 0xa452a5d in /usr/bin/clickhouse
10. ? @ 0x7f5a4350a609 in ?
11. __clone @ 0x7f5a4342f163 in ?

2022.08.26 02:01:42.675883 [ 1543150 ] {c2dafbe2-d9f5-42ad-abf4-cc6a15e6465c} <Error> TCPHandler: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt32 position 1: expected 6380, got 2807: While executing MergeTreeThread. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa38beba in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x15cfae0c in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::generate() @ 0x1608b103 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x15d0d475 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x15d0cf86 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x15d29fea in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15d1dcfc in /usr/bin/clickhouse
7. ? @ 0x15d20cfb in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa44f7cc in /usr/bin/clickhouse
9. ? @ 0xa452a5d in /usr/bin/clickhouse
10. ? @ 0x7f5a4350a609 in ?
11. __clone @ 0x7f5a4342f163 in ?

**Additional context**

It seems that the data is deleted as I can't find it in the table after the fact but when this happened the other day on a different table it left the table in some sort of inconsistent state as alter table delete mutations would no longer seem to work (they would hang forever with now error). Since this is just a test I ended up just dropping the other table to get mutations working again.

### LINKED ISSUE #41404: CH version 22.8.4.7 Invalid number of rows in Chunk column Int64 position 0
**Table schema**
`
-- pub_summary_db_sem_haosou.pub_setting_sem_keyword definition

CREATE TABLE pub_summary_db_sem_haosou.pub_setting_sem_keyword
(

    `publisher_id` Int32,

    `price` Float64,

    `wap_price_guide` Float64,

    `channel_id` Int32,

    `wmatch_prefer` Int32,

    `wap_reason` Int32,

    `chan_pub_id` Int64,

    `wap_business_relationship` Int32,

    `pub_campaign_id` Int64,

    `wap_landpage_experience` Int32,

    `status` Int32,

    `pc_quality` Int32,

    `pub_keyword_id` Int64,

    `pub_adgroup_name` String,

    `delete_time` Nullable(DateTime),

    `wap_destination_url` String,

    `match_type` Int32,

    `pc_reason` Int32,

    `wap_reliable` Int32,

    `tabs` String,

    `wap_estimated_click_rate` Int32,

    `pc_estimated_click_rate` Int32,

    `phrase_type` Int32,

    `pc_reliable` Int32,

    `pause` Int32,

    `wap_quality` Int32,

    `pub_keyword` String,

    `pub_account_name` String,

    `pub_account_id` Int64,

    `pc_left3_price_guide` Float64,

    `pc_landpage_experience` Int32,

    `pub_campaign_name` String,

    `pub_adgroup_id` Int64,

    `keyword_length` Int32,

    `pc_left_price_guide` Float64,

    `pc_business_relationship` Int32,

    `pc_destination_url` String,

    `deeplink_url` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/pub_summary_db_sem_haosou/new_keyword_6eab1486344611ed928dfa163e676c73_20220915015242',
 '{replica}')
PRIMARY KEY (chan_pub_id,
 pub_campaign_id,
 pub_adgroup_id,
 pub_keyword_id)
ORDER BY (chan_pub_id,
 pub_campaign_id,
 pub_adgroup_id,
 pub_keyword_id)
SETTINGS index_granularity = 8192;
`

**Query**
`
SELECT
    chan_pub_id,
    count() AS c_number
FROM pub_summary_db_sem_haosou.pub_setting_sem_keyword
WHERE status = 4900
GROUP BY chan_pub_id
HAVING c_number > 10000000
ORDER BY c_number DESC

2022.09.16 17:52:02.922436 [ 2833 ] {df1a1cf9-6203-415f-a041-137806e67017} <Error> executeQuery: Code: 49. DB::Exception: Invalid number of rows in Chunk column Int64 position 0: expected 65505, got 5304: While executing MergeTreeThread. (LOGICAL_ERROR) (version 22.8.4.7 (official build)) (from 10.252.4.8:53837) (in query: select chan_pub_id, count() as c_number from pub_summary_db_sem_haosou.pub_setting_sem_keyword where status = 4900 group by chan_pub_id having c_number > 10000000 order by c_number desc LIMIT 0, 200 FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3c367a in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x15bd044e in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::generate() @ 0x15f5cba0 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x15be2915 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x15be2466 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x15bfeeea in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15bf345b in /usr/bin/clickhouse
7. ? @ 0x15bf5cf9 in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa485048 in /usr/bin/clickhouse
9. ? @ 0xa48825d in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
`

**We changed sql to** 
`
SELECT
    chan_pub_id,
    count() AS c_number
FROM pub_summary_db_sem_haosou.pub_setting_sem_keyword
WHERE status = '4900'
GROUP BY chan_pub_id
HAVING c_number > 10000000
ORDER BY c_number DESC

It works well
`

### PR DESCRIPTION
**Pull request by davenger**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
#40651 #41404

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by albertcht** [comment]
Hi @davenger ,

I was wondering when will this pull request be merged? Thanks in advance!

**Comment by davenger** [comment]
Hi @albertcht I'm actively working on it, but there still some issues that need to be solved. Hope to finish soon.

**Comment by albertcht** [comment]
> Hi @albertcht I'm actively working on it, but there are still some issues that need to be solved. Hope to finish soon.

Thanks for your quick reply, looking forward to this fix :)

File: src/Storages/MergeTree/MergeTreeRangeReader.cpp [hunk 1]
```diff
@@ -30,13 +30,15 @@ namespace ErrorCodes
...
 
-static void filterColumns(Columns & columns, const IColumn::Filter & filter)
+static void filterColumns(Columns & columns, const IColumn::Filter & filter, size_t filter_bytes)
 {
     for (auto & column : columns)
     {
         if (column)
         {
-            column = column->filter(filter, -1);
+            assert(column->size() == filter.size());
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeRangeReader.cpp:39]: chassert is better.
Or maybe even throw a logical error?

File: src/Storages/MergeTree/MergeTreeRangeReader.cpp [hunk 2]
```diff
@@ -348,74 +353,250 @@ void MergeTreeRangeReader::ReadResult::shrink(Columns & old_columns)
...
 void MergeTreeRangeReader::ReadResult::setFilterConstTrue()
 {
-    clearFilter();
-    filter_holder = DataTypeUInt8().createColumnConst(num_rows, 1u);
+    /// Remove the filter, so newly read columns will not be filtered.
+    final_filter = FilterWithCachedCount();
 }
 
-void MergeTreeRangeReader::ReadResult::setFilterConstFalse()
+ColumnPtr andFilters(ColumnPtr c1, ColumnPtr c2)
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeRangeReader.cpp:430]: static?

File: src/Storages/MergeTree/MergeTreeRangeReader.cpp [hunk 3]
```diff
@@ -348,74 +353,250 @@ void MergeTreeRangeReader::ReadResult::shrink(Columns & old_columns)
...
+    const auto & c1_data = typeid_cast<const ColumnUInt8&>(*c1).getData();
+    const auto & c2_data = typeid_cast<const ColumnUInt8&>(*c2).getData();
+    const size_t size = c1->size();
+    const size_t step = 16;
+    size_t i = 0;
+    /// NOTE: '&&' must be used instead of '&' for 'AND' operation because UInt8 columns might contain any non-zero
+    /// value for true and we cannot bitwise AND them to get the correct result.
+    for (; i + step < size; i += step)
+        for (size_t j = 0; j < step; ++j)
+            res_data[i+j] = (c1_data[i+j] && c2_data[i+j]);
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeRangeReader.cpp:445]: I hope this loop vectorizes well.
But actually, I think a simple loop would be vectorized in the same way.
What can we improve is actually to round up to 16 bytes, because ColumnUInt8 uses PaddedPodArray with 15 bytes padding (so we won't need a tail).

File: src/Storages/MergeTree/MergeTreeRangeReader.cpp [hunk 4]
```diff
@@ -348,74 +353,250 @@ void MergeTreeRangeReader::ReadResult::shrink(Columns & old_columns)
...
+void MergeTreeRangeReader::ReadResult::applyFilter(const FilterWithCachedCount & filter)
+{
+    assert(filter.size() == num_rows);
+
+    LOG_TEST(log, "ReadResult::applyFilter() num_rows before: {}", num_rows);
+
+    filterColumns(columns, filter);
+
+    {
+        auto c = additional_columns.getColumns();
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeRangeReader.cpp:462]: :)

**Review by KochetovNicolai — APPROVED** [review]
