### PR TITLE
Fix async RESTORE with Replicated database

### LINKED ISSUE #59570: RESTORE TABLE: Failed assertion (internal || CurrentThread::get().getQueryContext())
Report: https://s3.amazonaws.com/clickhouse-test-reports/59383/7be91e66dda4662d7faf78727ac57edb446ff49e/stress_test__debug_.html

```
$ grep Fatal clickhouse-server.stress.log
2024.02.03 00:38:43.805679 [ 6865 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.02.03 00:38:43.832504 [ 6865 ] {} <Fatal> BaseDaemon: (version 24.2.1.1, build id: C1A48325BBDBC3ADA2C977A98757C7AA192EBA06, git hash: a629abc06367e5309173a719b8d42b421bdc7443) (from thread 4260) Received signal 6
2024.02.03 00:38:43.836064 [ 6865 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2024.02.03 00:38:43.837338 [ 6865 ] {} <Fatal> BaseDaemon: 
2024.02.03 00:38:43.841655 [ 6865 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f11ba8799fc 0x00007f11ba825476 0x00007f11ba80b7f3 0x00007f11ba80b71b 0x00007f11ba81ce96 0x000000001ca722c4 0x000000001ca78d61 0x000000001b796629 0x000000001b795324 0x000000001b2525bf 0x000000001b21e676 0x000000001c1fdfb5 0x000000001c206476 0x000000001b25de07 0x000000001b231710 0x000000001a98c515 0x000000001a9859e8 0x000000001a981ef9 0x000000001a8f979b 0x000000001a90085d 0x000000001a900735 0x000000001a900715 0x000000001a9006f5 0x000000001a9006c0 0x0000000012307556 0x0000000012307195 0x0000000013b7f8fd 0x0000000013b887c4 0x0000000013b88795 0x0000000013b88779 0x0000000013b886dd 0x0000000013b885e5 0x0000000013b88555 0x0000000013b88535 0x0000000013b88515 0x0000000013b884e0 0x0000000012307556 0x0000000012307195 0x0000000013b7c6bd 0x0000000013b83184 0x0000000013b83135
2024.02.03 00:38:43.842905 [ 6865 ] {} <Fatal> BaseDaemon: ########################################
2024.02.03 00:38:43.857474 [ 6865 ] {} <Fatal> BaseDaemon: (version 24.2.1.1, build id: C1A48325BBDBC3ADA2C977A98757C7AA192EBA06, git hash: a629abc06367e5309173a719b8d42b421bdc7443) (from thread 4260) (query_id: d93df238-1542-4055-a4c8-a59e3420b10c) (query: /* ddl_entry=query-0000000001 */ RESTORE TABLE test_xibn15d0.mv FROM Disk('backups', '02907_backup_mv_with_no_source_table_test_xibn15d0') SETTINGS restore_uuid = '26fed8c8-dea4-45e7-9477-de5becddd914', internal = true, async = true, host_id = 'localhost:9000', cluster_host_ids = [['localhost:9000']]) Received signal Aborted (6)
2024.02.03 00:38:43.858607 [ 6865 ] {} <Fatal> BaseDaemon: 
2024.02.03 00:38:43.862459 [ 6865 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f11ba8799fc 0x00007f11ba825476 0x00007f11ba80b7f3 0x00007f11ba80b71b 0x00007f11ba81ce96 0x000000001ca722c4 0x000000001ca78d61 0x000000001b796629 0x000000001b795324 0x000000001b2525bf 0x000000001b21e676 0x000000001c1fdfb5 0x000000001c206476 0x000000001b25de07 0x000000001b231710 0x000000001a98c515 0x000000001a9859e8 0x000000001a981ef9 0x000000001a8f979b 0x000000001a90085d 0x000000001a900735 0x000000001a900715 0x000000001a9006f5 0x000000001a9006c0 0x0000000012307556 0x0000000012307195 0x0000000013b7f8fd 0x0000000013b887c4 0x0000000013b88795 0x0000000013b88779 0x0000000013b886dd 0x0000000013b885e5 0x0000000013b88555 0x0000000013b88535 0x0000000013b88515 0x0000000013b884e0 0x0000000012307556 0x0000000012307195 0x0000000013b7c6bd 0x0000000013b83184 0x0000000013b83135
2024.02.03 00:38:43.903352 [ 6865 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f11ba8799fc
2024.02.03 00:38:43.903740 [ 6865 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f11ba825476
2024.02.03 00:38:43.904140 [ 6865 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f11ba80b7f3
2024.02.03 00:38:43.904575 [ 6865 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007f11ba80b71b
2024.02.03 00:38:43.905008 [ 6865 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00007f11ba81ce96
2024.02.03 00:38:45.247189 [ 6865 ] {} <Fatal> BaseDaemon: 9. /build/src/Interpreters/executeQuery.cpp:693: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001ca722c4 in /usr/bin/clickhouse
2024.02.03 00:38:46.772667 [ 6865 ] {} <Fatal> BaseDaemon: 10. /build/src/Interpreters/executeQuery.cpp:1395: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001ca78d61 in /usr/bin/clickhouse
2024.02.03 00:38:47.364877 [ 6865 ] {} <Fatal> BaseDaemon: 11. /build/src/Interpreters/DDLWorker.cpp:497: DB::DDLWorker::tryExecuteQuery(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x000000001b796629 in /usr/bin/clickhouse
2024.02.03 00:38:47.930526 [ 6865 ] {} <Fatal> BaseDaemon: 12. /build/src/Interpreters/DDLWorker.cpp:661: DB::DDLWorker::processTask(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x000000001b795324 in /usr/bin/clickhouse
2024.02.03 00:38:48.148045 [ 6865 ] {} <Fatal> BaseDaemon: 13. /build/src/Databases/DatabaseReplicatedWorker.cpp:286: DB::DatabaseReplicatedDDLWorker::tryEnqueueAndExecuteEntry(DB::DDLLogEntry&, std::shared_ptr<DB::Context const>) @ 0x000000001b2525bf in /usr/bin/clickhouse
2024.02.03 00:38:48.910987 [ 6865 ] {} <Fatal> BaseDaemon: 14. /build/src/Databases/DatabaseReplicated.cpp:783: DB::DatabaseReplicated::tryEnqueueReplicatedDDL(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::QueryFlags) @ 0x000000001b21e676 in /usr/bin/clickhouse
2024.02.03 00:38:49.497329 [ 6865 ] {} <Fatal> BaseDaemon: 15. /build/src/Interpreters/InterpreterCreateQuery.cpp:1345: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000001c1fdfb5 in /usr/bin/clickhouse
2024.02.03 00:38:50.109695 [ 6865 ] {} <Fatal> BaseDaemon: 16. /build/src/Interpreters/InterpreterCreateQuery.cpp:0: DB::InterpreterCreateQuery::execute() @ 0x000000001c206476 in /usr/bin/clickhouse
2024.02.03 00:38:50.268426 [ 6865 ] {} <Fatal> BaseDaemon: 17. /build/src/Databases/DatabasesCommon.cpp:391: DB::DatabaseWithOwnTablesBase::createTableRestoredFromBackup(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::IRestoreCoordination>, unsigned long) @ 0x000000001b25de07 in /usr/bin/clickhouse
2024.02.03 00:38:50.952887 [ 6865 ] {} <Fatal> BaseDaemon: 18. /build/src/Databases/DatabaseReplicated.cpp:1576: DB::DatabaseReplicated::createTableRestoredFromBackup(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::IRestoreCoordination>, unsigned long) @ 0x000000001b231710 in /usr/bin/clickhouse
2024.02.03 00:38:51.636449 [ 6865 ] {} <Fatal> BaseDaemon: 19. /build/src/Backups/RestorerFromBackup.cpp:746: DB::RestorerFromBackup::createTable(DB::QualifiedTableName const&) @ 0x000000001a98c515 in /usr/bin/clickhouse
2024.02.03 00:38:52.403686 [ 6865 ] {} <Fatal> BaseDaemon: 20. /build/src/Backups/RestorerFromBackup.cpp:708: DB::RestorerFromBackup::createTables() @ 0x000000001a9859e8 in /usr/bin/clickhouse
2024.02.03 00:38:53.090188 [ 6865 ] {} <Fatal> BaseDaemon: 21. /build/src/Backups/RestorerFromBackup.cpp:136: DB::RestorerFromBackup::run(DB::RestorerFromBackup::Mode) @ 0x000000001a981ef9 in /usr/bin/clickhouse
2024.02.03 00:38:53.573596 [ 6865 ] {} <Fatal> BaseDaemon: 22. /build/src/Backups/BackupsWorker.cpp:1003: DB::BackupsWorker::doRestore(std::shared_ptr<DB::ASTBackupQuery> const&, String const&, String const&, DB::BackupInfo const&, DB::RestoreSettings, std::shared_ptr<DB::IRestoreCoordination>, std::shared_ptr<DB::Context>, std::shared_ptr<DB::ThreadGroup>, bool) @ 0x000000001a8f979b in /usr/bin/clickhouse
2024.02.03 00:38:54.160332 [ 6865 ] {} <Fatal> BaseDaemon: 23. /build/src/Backups/BackupsWorker.cpp:859: DB::BackupsWorker::startRestoring(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>)::$_0::operator()() const @ 0x000000001a90085d in /usr/bin/clickhouse
2024.02.03 00:38:55.125720 [ 6865 ] {} <Fatal> BaseDaemon: 24. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ? @ 0x000000001a900735 in /usr/bin/clickhouse
2024.02.03 00:38:55.613740 [ 6865 ] {} <Fatal> BaseDaemon: 25. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: ? @ 0x000000001a900715 in /usr/bin/clickhouse
2024.02.03 00:38:55.901529 [ 6865 ] {} <Fatal> BaseDaemon: 26. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: ? @ 0x000000001a9006f5 in /usr/bin/clickhouse
2024.02.03 00:38:56.161212 [ 6865 ] {} <Fatal> BaseDaemon: 27. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a9006c0 in /usr/bin/clickhouse
2024.02.03 00:38:56.373706 [ 6865 ] {} <Fatal> BaseDaemon: 28. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x0000000012307556 in /usr/bin/clickhouse
2024.02.03 00:38:56.585171 [ 6865 ] {} <Fatal> BaseDaemon: 29. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: ? @ 0x0000000012307195 in /usr/bin/clickhouse
2024.02.03 00:38:56.668070 [ 6865 ] {} <Fatal> BaseDaemon: 30. /build/src/Common/ThreadPool.cpp:455: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000013b7f8fd in /usr/bin/clickhouse
2024.02.03 00:38:56.770430 [ 6865 ] {} <Fatal> BaseDaemon: 31. /build/src/Common/ThreadPool.cpp:217: void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()::operator()() const @ 0x0000000013b887c4 in /usr/bin/clickhouse
2024.02.03 00:38:56.879707 [ 6865 ] {} <Fatal> BaseDaemon: 32. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ? @ 0x0000000013b88795 in /usr/bin/clickhouse
2024.02.03 00:38:56.989219 [ 6865 ] {} <Fatal> BaseDaemon: 33. /build/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()&, std::tuple<>&>(void&&, std::tuple<>&, std::__tuple_indices<>) @ 0x0000000013b88779 in /usr/bin/clickhouse
2024.02.03 00:38:57.098509 [ 6865 ] {} <Fatal> BaseDaemon: 34. /build/contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15000]<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()&, std::tuple<>&>(void&&, std::tuple<>&) @ 0x0000000013b886dd in /usr/bin/clickhouse
2024.02.03 00:38:57.184097 [ 6865 ] {} <Fatal> BaseDaemon: 35. /build/src/Common/ThreadPool.h:223: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x0000000013b885e5 in /usr/bin/clickhouse
2024.02.03 00:38:57.294235 [ 6865 ] {} <Fatal> BaseDaemon: 36. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ? @ 0x0000000013b88555 in /usr/bin/clickhouse
2024.02.03 00:38:57.396719 [ 6865 ] {} <Fatal> BaseDaemon: 37. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: ? @ 0x0000000013b88535 in /usr/bin/clickhouse
2024.02.03 00:38:57.498972 [ 6865 ] {} <Fatal> BaseDaemon: 38. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: ? @ 0x0000000013b88515 in /usr/bin/clickhouse
2024.02.03 00:38:57.601425 [ 6865 ] {} <Fatal> BaseDaemon: 39. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000013b884e0 in /usr/bin/clickhouse
2024.02.03 00:38:57.813426 [ 6865 ] {} <Fatal> BaseDaemon: 40. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x0000000012307556 in /usr/bin/clickhouse
2024.02.03 00:38:58.025263 [ 6865 ] {} <Fatal> BaseDaemon: 41. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: ? @ 0x0000000012307195 in /usr/bin/clickhouse
2024.02.03 00:38:58.107580 [ 6865 ] {} <Fatal> BaseDaemon: 42. /build/src/Common/ThreadPool.cpp:455: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x0000000013b7c6bd in /usr/bin/clickhouse
2024.02.03 00:38:58.203189 [ 6865 ] {} <Fatal> BaseDaemon: 43. /build/src/Common/ThreadPool.cpp:217: void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()::operator()() const @ 0x0000000013b83184 in /usr/bin/clickhouse
2024.02.03 00:38:58.309736 [ 6865 ] {} <Fatal> BaseDaemon: 44. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ? @ 0x0000000013b83135 in /usr/bin/clickhouse
2024.02.03 00:38:58.309859 [ 6865 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2024.02.03 00:39:06.011777 [ 6865 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2024.02.03 00:39:09.912809 [ 3043 ] {} <Fatal> Application: Child process was terminated by signal 6.
 ` `

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix async RESTORE with Replicated database

cc @vitlibar 

Fix https://github.com/ClickHouse/ClickHouse/issues/59570

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit de4b2e566db207d61acaf151591e9b817c181777 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60934/de4b2e566db207d61acaf151591e9b817c181777/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Backups/BackupsWorker.cpp [hunk 1]
```diff
@@ -864,6 +865,8 @@ OperationID BackupsWorker::startRestoring(const ASTPtr & query, ContextMutablePt
             /// process_list_element_holder is used to make an element in ProcessList live while RESTORE is working asynchronously.
             auto process_list_element = context_in_use->getProcessListElement();
 
+            /// we need to keep query context alive until RESTORE is done
+            auto query_context = CurrentThread::getQueryContext();
```
Comment (vitlibar) [inline src/Backups/BackupsWorker.cpp:869]: But the `query_context` must be the same as `context_in_use` and it's kept alive already.

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:869]: couple of lines above you can see that if it's async we do this
```cpp
context_in_use = Context::createCopy(context);
```
so the initial context is not kept

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:869]: it's possible that the `if` needs to be `if (on_cluster)`
WDYT is better?

Comment (vitlibar) [reply src/Backups/BackupsWorker.cpp:869]: > so the initial context is not kept

But do we need the initial context since we're using `context_in_use` to enqueue a DDL entry and not the initial context?

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:869]: Because the restore thread will attach to thread group created by the query and which contains the initial context.
We can also create a new QueryScope with `context_in_use` as context inside the restore thread.

Comment (vitlibar) [reply src/Backups/BackupsWorker.cpp:869]: > it's possible that the if needs to be if (on_cluster) instead of if (restore_settings.async || on_cluster)
WDYT is better?

AFAIK contexts have not much of synchronization so we always copy a context if we pass it to another thread.

Comment (vitlibar) [reply src/Backups/BackupsWorker.cpp:869]: > We can also create a new QueryScope with context_in_use as context inside the restore thread.

It's strange that we need that. Because `QueryScope::QueryScope()` mostly calls `CurrentThread::attachToGroup()` however ``CurrentThread::attachToGroup()` is called already - see the call of `scheduleFromThreadPool()` in `BackupsWorker::startRestoring()`.

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:869]: As I said, `ThreadGroup` stores `weak_ptr` to the context so `attachToGroup` won't extend the lifetime of it.
- run RESTORE async
- create query context and with QueryScope add it to thread group
- create restore thread and inside it:
      - attach to the group 
      - get the weak_ptr to context
- query finishes because it's async while the restore thread is running in background
- created query context is deleted and all weak_ptr to it become invalid

Comment (vitlibar) [reply src/Backups/BackupsWorker.cpp:869]: BTW can we just set `internal = true` and pass this assertion? It seems it would be even correct logically.

Comment (vitlibar) [reply src/Backups/BackupsWorker.cpp:869]: > We can also create a new QueryScope with context_in_use as context inside the restore thread.

Yes, it seems it would be better to create `QueryScope` before calling `doRestore()` on a separate thread.

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:869]: setting it to internal doesn't help, not sure why exactly 
I will try with `QueryScope`
Important we now know where the problem is, and I'm open to any solution

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:869]: also, do we want to do the same with backup inside `startMakingBackup`?

File: src/Backups/BackupsWorker.cpp [hunk 2]
```diff
@@ -876,6 +877,7 @@ OperationID BackupsWorker::startRestoring(const ASTPtr & query, ContextMutablePt
                  on_exception,
                  process_list_element_holder = process_list_element ? process_list_element->getProcessListEntry() : nullptr]
                 {
+                    CurrentThread::QueryScope query_scope(context_in_use);
```
Comment (vitlibar) [inline src/Backups/BackupsWorker.cpp:880]: `setThreadName()` here could be also useful.

Comment (vitlibar) [inline src/Backups/BackupsWorker.cpp:880]: I'm not sure if it's better to make query scope inside `try` or not.

Comment (antonio2368) [reply src/Backups/BackupsWorker.cpp:881]: I can put it inside try just to be safe

File: src/Backups/BackupsWorker.cpp [hunk 3]
```diff
@@ -876,8 +878,10 @@ OperationID BackupsWorker::startRestoring(const ASTPtr & query, ContextMutablePt
                  on_exception,
                  process_list_element_holder = process_list_element ? process_list_element->getProcessListEntry() : nullptr]
                 {
+                    setThreadName("RestorerWorker");
```
Comment (vitlibar) [inline src/Backups/BackupsWorker.cpp:881]: setThreadName() can in theory also throw exceptions

**Review by vitlibar — APPROVED** [review]
