### PR TITLE
Fix crash in lag/lead

### LINKED ISSUE #68162: Segfault with lagInFlame()
**Describe the bug**
[A link to the report](https://s3.amazonaws.com/clickhouse-test-reports/67700/f2b60c4f7410311afd18d03c458e780a924b6f94/ast_fuzzer__debug_.html)

**How to reproduce**
Stack from debug build
```
[ip-10-2-2-126] 2024.08.11 18:36:03.980439 [ 165758 ] <Fatal> BaseDaemon: ########################################
[ip-10-2-2-126] 2024.08.11 18:36:03.980556 [ 165758 ] <Fatal> BaseDaemon: (version 24.8.1.1, build id: 0C398F147D358D967328485E6D99FCA1DB3451E8, git hash: f2b60c4f7410311afd18d03c458e780a924b6f94) (from thread 165620) (query_id: 89524b8e-47c8-4bfc-a642-62383d1433e6) (query: SELECT
    number,
    YYYYMMDDToDate(1, toLowCardinality(11), max(YYYYMMDDToDate(YYYYMMDDToDate(toLowCardinality(1), 11, materialize(NULL), 19700101.1, 1, 27, 7, materialize(toUInt256(37)), 9, 19, 9), 1, toUInt128(11), NULL, 19700101.1, 1, 27, 7, 37, 9, 19, 9), toUInt256(30)) IGNORE NULLS OVER w, NULL, 19700101.1, toNullable(1), 27, materialize(7), 37, 9, 19, 9),
    p,
    pp,
    lagInFrame(number, number - pp) OVER w AS lag2,
    lagInFrame(number, number - pp, number * 11) OVER w AS lag,
    leadInFrame(number, number - pp, number * 11) OVER w AS lead
FROM
(
    SELECT
        number,
        intDiv(number, 5) AS p,
        p * 5 AS pp
    FROM numbers(16)
)
WHERE toLowCardinality(1)
WINDOW w AS (PARTITION BY p ORDER BY number ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
ORDER BY number DESC NULLS LAST
SETTINGS max_block_size = 3) Received signal Aborted (6)
[ip-10-2-2-126] 2024.08.11 18:36:03.980637 [ 165758 ] <Fatal> BaseDaemon:
[ip-10-2-2-126] 2024.08.11 18:36:03.980684 [ 165758 ] <Fatal> BaseDaemon: Stack trace: 0x000000000c745088 0x000000000c983abe 0x0000727893c42520 0x0000727893c969fd 0x0000727893c42476 0x0000727893c287f3 0x000000001867161d 0x00000000130cbe7a 0x00000000130b979c 0x00000000130b9b43 0x00000000130bc883 0x0000000012de3b2b 0x0000000012dd97b1 0x0000000012dd842c 0x0000000012dd7e45 0x0000000012de69ff 0x000000000c7ba901 0x000000000c7bee45 0x0000727893c94ac3 0x0000727893d26850
[ip-10-2-2-126] 2024.08.11 18:36:04.004720 [ 165758 ] <Fatal> BaseDaemon: 0.0. inlined from /home/ubuntu/git/ClickHouse/src/Common/StackTrace.cpp:349: StackTrace::tryCapture()
[ip-10-2-2-126] 2024.08.11 18:36:04.004785 [ 165758 ] <Fatal> BaseDaemon: 0. /home/ubuntu/git/ClickHouse/src/Common/StackTrace.cpp:318: StackTrace::StackTrace(ucontext_t const&) @ 0x000000000c745088
[ip-10-2-2-126] 2024.08.11 18:36:04.039807 [ 165758 ] <Fatal> BaseDaemon: 1. /home/ubuntu/git/ClickHouse/src/Common/SignalHandlers.cpp:0: signalHandler(int, siginfo_t*, void*) @ 0x000000000c983abe
[ip-10-2-2-126] 2024.08.11 18:36:04.039882 [ 165758 ] <Fatal> BaseDaemon: 2. ? @ 0x0000727893c42520
[ip-10-2-2-126] 2024.08.11 18:36:04.039926 [ 165758 ] <Fatal> BaseDaemon: 3. ? @ 0x0000727893c969fd
[ip-10-2-2-126] 2024.08.11 18:36:04.039970 [ 165758 ] <Fatal> BaseDaemon: 4. ? @ 0x0000727893c42476
[ip-10-2-2-126] 2024.08.11 18:36:04.040010 [ 165758 ] <Fatal> BaseDaemon: 5. ? @ 0x0000727893c287f3
[ip-10-2-2-126] 2024.08.11 18:36:04.133246 [ 165758 ] <Fatal> BaseDaemon: 6. ? @ 0x000000001867161d
[ip-10-2-2-126] 2024.08.11 18:36:04.295045 [ 165758 ] <Fatal> BaseDaemon: 7.0. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/vector:1500: std::vector<unsigned long, std::allocator<unsigned long>>::operator[][abi:v15007](unsigned long) const
[ip-10-2-2-126] 2024.08.11 18:36:04.295111 [ 165758 ] <Fatal> BaseDaemon: 7. /home/ubuntu/git/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:2417: DB::WindowFunctionLagLeadInFrame<true>::windowInsertResultInto(DB::WindowTransform const*, unsigned long) const @ 0x00000000130cbe7a
[ip-10-2-2-126] 2024.08.11 18:36:04.385997 [ 165758 ] <Fatal> BaseDaemon: 8. /home/ubuntu/git/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:1052: DB::WindowTransform::writeOutCurrentRow() @ 0x00000000130b979c
[ip-10-2-2-126] 2024.08.11 18:36:04.477163 [ 165758 ] <Fatal> BaseDaemon: 9.0. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/atomic:958: bool std::__cxx_atomic_load[abi:v15007]<bool>(std::__cxx_atomic_base_impl<bool> const*, std::memory_order)
[ip-10-2-2-126] 2024.08.11 18:36:04.477217 [ 165758 ] <Fatal> BaseDaemon: 9.1. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/atomic:1560: std::__atomic_base<bool, false>::load[abi:v15007](std::memory_order) const
[ip-10-2-2-126] 2024.08.11 18:36:04.477252 [ 165758 ] <Fatal> BaseDaemon: 9.2. inlined from /home/ubuntu/git/ClickHouse/src/Processors/IProcessor.h:257: DB::IProcessor::isCancelled() const
[ip-10-2-2-126] 2024.08.11 18:36:04.477283 [ 165758 ] <Fatal> BaseDaemon: 9. /home/ubuntu/git/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:1247: DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x00000000130b9b43
[ip-10-2-2-126] 2024.08.11 18:36:04.572089 [ 165758 ] <Fatal> BaseDaemon: 10.0. inlined from /home/ubuntu/git/ClickHouse/src/Processors/Transforms/WindowTransform.h:41: DB::RowNumber::operator<=>(DB::RowNumber const&) const
[ip-10-2-2-126] 2024.08.11 18:36:04.572136 [ 165758 ] <Fatal> BaseDaemon: 10. /home/ubuntu/git/ClickHouse/src/Processors/Transforms/WindowTransform.cpp:1487: DB::WindowTransform::work() @ 0x00000000130bc883
[ip-10-2-2-126] 2024.08.11 18:36:04.581845 [ 165758 ] <Fatal> BaseDaemon: 11.0. inlined from /home/ubuntu/git/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
[ip-10-2-2-126] 2024.08.11 18:36:04.581884 [ 165758 ] <Fatal> BaseDaemon: 11. /home/ubuntu/git/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:96: DB::ExecutionThreadContext::executeTask() @ 0x0000000012de3b2b
[ip-10-2-2-126] 2024.08.11 18:36:04.613069 [ 165758 ] <Fatal> BaseDaemon: 12.0. inlined from /home/ubuntu/git/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*)
[ip-10-2-2-126] 2024.08.11 18:36:04.613113 [ 165758 ] <Fatal> BaseDaemon: 12. /home/ubuntu/git/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:239: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x0000000012dd97b1
[ip-10-2-2-126] 2024.08.11 18:36:04.639633 [ 165758 ] <Fatal> BaseDaemon: 13.0. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
[ip-10-2-2-126] 2024.08.11 18:36:04.639677 [ 165758 ] <Fatal> BaseDaemon: 13. /home/ubuntu/git/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:412: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000012dd842c
[ip-10-2-2-126] 2024.08.11 18:36:04.668869 [ 165758 ] <Fatal> BaseDaemon: 14.0. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: std::unique_ptr<DB::ExecutingGraph, std::default_delete<DB::ExecutingGraph>>::operator->[abi:v15007]() const
[ip-10-2-2-126] 2024.08.11 18:36:04.668917 [ 165758 ] <Fatal> BaseDaemon: 14. /home/ubuntu/git/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:114: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000012dd7e45
[ip-10-2-2-126] 2024.08.11 18:36:04.696277 [ 165758 ] <Fatal> BaseDaemon: 15.0. inlined from /home/ubuntu/git/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
[ip-10-2-2-126] 2024.08.11 18:36:04.696321 [ 165758 ] <Fatal> BaseDaemon: 15.1. inlined from /home/ubuntu/git/ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109: operator()
[ip-10-2-2-126] 2024.08.11 18:36:04.696351 [ 165758 ] <Fatal> BaseDaemon: 15.2. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
[ip-10-2-2-126] 2024.08.11 18:36:04.696384 [ 165758 ] <Fatal> BaseDaemon: 15.3. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<>)
[ip-10-2-2-126] 2024.08.11 18:36:04.696421 [ 165758 ] <Fatal> BaseDaemon: 15.4. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
[ip-10-2-2-126] 2024.08.11 18:36:04.696450 [ 165758 ] <Fatal> BaseDaemon: 15.5. inlined from /home/ubuntu/git/ClickHouse/src/Common/ThreadPool.h:251: operator()
[ip-10-2-2-126] 2024.08.11 18:36:04.696479 [ 165758 ] <Fatal> BaseDaemon: 15.6. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
[ip-10-2-2-126] 2024.08.11 18:36:04.696507 [ 165758 ] <Fatal> BaseDaemon: 15.7. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
[ip-10-2-2-126] 2024.08.11 18:36:04.696531 [ 165758 ] <Fatal> BaseDaemon: 15.8. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
[ip-10-2-2-126] 2024.08.11 18:36:04.696561 [ 165758 ] <Fatal> BaseDaemon: 15. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012de69ff
[ip-10-2-2-126] 2024.08.11 18:36:04.719481 [ 165758 ] <Fatal> BaseDaemon: 16.0. inlined from /home/ubuntu/git/ClickHouse/base/base/../base/strong_typedef.h:23: StrongTypedef<std::integral_constant<bool, true> >
[ip-10-2-2-126] 2024.08.11 18:36:04.719542 [ 165758 ] <Fatal> BaseDaemon: 16.1. inlined from /home/ubuntu/git/ClickHouse/src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
[ip-10-2-2-126] 2024.08.11 18:36:04.719578 [ 165758 ] <Fatal> BaseDaemon: 16. /home/ubuntu/git/ClickHouse/src/Common/ThreadPool.cpp:464: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000c7ba901
[ip-10-2-2-126] 2024.08.11 18:36:04.757412 [ 165758 ] <Fatal> BaseDaemon: 17.0. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15007](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
[ip-10-2-2-126] 2024.08.11 18:36:04.757478 [ 165758 ] <Fatal> BaseDaemon: 17.1. inlined from /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
[ip-10-2-2-126] 2024.08.11 18:36:04.757529 [ 165758 ] <Fatal> BaseDaemon: 17. /home/ubuntu/git/ClickHouse/contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c7bee45
[ip-10-2-2-126] 2024.08.11 18:36:04.757577 [ 165758 ] <Fatal> BaseDaemon: 18. ? @ 0x0000727893c94ac3
[ip-10-2-2-126] 2024.08.11 18:36:04.757623 [ 165758 ] <Fatal> BaseDaemon: 19. ? @ 0x0000727893d26850
[ip-10-2-2-126] 2024.08.11 18:36:04.757667 [ 165758 ] <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
[ip-10-2-2-126] 2024.08.11 18:36:05.471128 [ 165758 ] <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
[ip-10-2-2-126] 2024.08.11 18:36:05.471255 [ 165758 ] <Fatal> BaseDaemon: Changed settings: max_block_size = 3, log_queries = true, allow_introspection_functions = true
↘ Progress: 16.00 rows, 128.00 B (3.24 rows/s., 25.96 B/s.)  99%Error on processing query: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF) (version 24.8.1.1)
```

Can be related to https://github.com/ClickHouse/ClickHouse/issues/67594

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix crash in `lag`/`lead` which is introduced in #67091

Closes #68162

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit c13b7575ccc4eed884aaf9c5557130878c476569 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68262/c13b7575ccc4eed884aaf9c5557130878c476569/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/40382451a291896c13e4fae57aed2b761563d10e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by thevar1able — APPROVED** [review]

File: src/Processors/Transforms/WindowTransform.cpp [hunk 1]
```diff
@@ -1159,6 +1159,12 @@ void WindowTransform::appendChunk(Chunk & chunk)
         {
             if (ws.window_function_impl)
                 block.casted_columns.push_back(ws.window_function_impl->castColumn(block.input_columns, ws.argument_column_indices));
+            else
+            {
+                /// `castColumn` returns nullptr at default, so it's OK to put nullptr as a placeholder here
+                /// it should not be used in fact.
```
Comment (yakov-olkhovskiy) [inline src/Processors/Transforms/WindowTransform.cpp:1165]: I think this comment is somewhat irrelevant and therefore misleading and not needed. The whole `if` block can be replaced with
```
block.casted_columns.push_back(ws.window_function_impl ? ws.window_function_impl->castColumn(block.input_columns, ws.argument_column_indices ) : nullptr);
```

**Review by yakov-olkhovskiy — APPROVED** [review]
LGTM though consider my comment
