### PR TITLE
AggregateFunctionTopK: read alphaMap for generic

### LINKED ISSUE #1283: Server exits after running topK() query on table using Distributed engine
I have a cluster which consists of two clickhouse-servers. I have `pageviews` table and then on top of that I have `pageviews_dist` table defined as 

```
create table pageviews_dist ( 
  ..., 
  SessionId FixedString(16), 
  ..., 
  DominantWinner Nullable(String),
  ...
 ) engine = Distributed(pageviews, default, pageviews, cityHash64(ContentSiteName));
```

When I run query on the `pageviews` table (on each server) I got good results (one server returns empty set the other one returns one value:

```
ubuntu@backend-01:~$ clickhouse-client --query "select topK(3)(coalesce(DominantWinner, 'unknown')) as top1 from pageviews where SessionId = UUIDStringToNum('6af5e8fa-2d9a-407c-b37f-fe562355077e')" --port 9000
ubuntu@backend-01:~$ clickhouse-client --query "select topK(3)(coalesce(DominantWinner, 'unknown')) as top1 from pageviews where SessionId = UUIDStringToNum('6af5e8fa-2d9a-407c-b37f-fe562355077e')" --port 9001
['google','fan','springserve']
```

When I run same query on the `pageviews_dist` via `--port 9001`:

```
ubuntu@backend-01:~$ clickhouse-client --query "select topK(3)(coalesce(DominantWinner, 'unknown')) as top1 from pageviews_dist where SessionId = UUIDStringToNum('6af5e8fa-2d9a-407c-b37f-fe562355077e')" --port 9001
['google','fan','sonobi']
```

but when run via `--port 9000`
```
ubuntu@backend-01:~$ clickhouse-client --query "select topK(3)(coalesce(DominantWinner, 'unknown')) as top1 from pageviews_dist where SessionId = UUIDStringToNum('6af5e8fa-2d9a-407c-b37f-fe562355077e')" --port 9000
Received exception from server:
Code: 100. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown packet 227213735 from server clickhouse2:9000, 10.0.0.7. 
```

```
ubuntu@backend-01:~$ docker logs ddfd511e556f 2>&1 | grep -A 20 Error
2017.09.25 11:09:46.096149 [ 28 ] <Error> BaseDaemon: ########################################
2017.09.25 11:09:46.096256 [ 28 ] <Error> BaseDaemon: (from thread 27) Received signal Segmentation fault (11).
2017.09.25 11:09:46.096284 [ 28 ] <Error> BaseDaemon: Address: 0x28
2017.09.25 11:09:46.111243 [ 28 ] <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::Connection::sendCancel()+0x11) [0x2e398b1]
2017.09.25 11:09:46.111263 [ 28 ] <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::MultiplexedConnections::sendCancel()+0x6d) [0x2e5280d]
2017.09.25 11:09:46.111273 [ 28 ] <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::RemoteBlockInputStream::tryCancel(char const*)+0x18b) [0x25623db]
2017.09.25 11:09:46.111280 [ 28 ] <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::RemoteBlockInputStream::cancel()+0xfa) [0x25625ca]
2017.09.25 11:09:46.111297 [ 28 ] <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::cancel()+0x8a) [0x2d1effa]
2017.09.25 11:09:46.111309 [ 28 ] <Error> BaseDaemon: 5. /usr/bin/clickhouse-server() [0x2d1f2c0]
2017.09.25 11:09:46.111320 [ 28 ] <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::thread(MemoryTracker*, unsigned long)+0x98) [0x2d1fdc8]
2017.09.25 11:09:46.111331 [ 28 ] <Error> BaseDaemon: 7. /usr/bin/clickhouse-server() [0x399d05f]
2017.09.25 11:09:46.111337 [ 28 ] <Error> BaseDaemon: 8. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f84205f56ba]
2017.09.25 11:09:46.116712 [ 26 ] <Error> executeQuery: Code: 100, e.displayText() = DB::Exception: Unknown packet 227213735 from server clickhouse2:9000, 10.0.0.7, e.what() = DB::Exception (from 10.255.0.3:52260) (in query: select topK(3)(coalesce(DominantWinner, 'unknown')) as top1 from pageviews_dist where SessionId = UUIDStringToNum('6af5e8fa-2d9a-407c-b37f-fe562355077e')), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x2bed4a6]
1. /usr/bin/clickhouse-server(DB::Connection::receivePacket()+0x10ba) [0x2e44d3a]
2. /usr/bin/clickhouse-server(DB::MultiplexedConnections::receivePacket()+0x80) [0x2e54110]
3. /usr/bin/clickhouse-server(DB::RemoteBlockInputStream::readImpl()+0xa1) [0x2566e91]
4. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x221) [0x255db11]
5. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::loop(unsigned long)+0x152) [0x2d1f6d2]
6. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::thread(MemoryTracker*, unsigned long)+0x77) [0x2d1fda7]
7. /usr/bin/clickhouse-server() [0x399d05f]
8. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f84205f56ba]
9. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f841fc163dd]
```

### PR DESCRIPTION
**Pull request by vavrusa**
I think this should fix #1283, the generic variant didn't read alphaMap state from wire, which I guess caused problems for the reader as it interpreted the following bytes as the header of a next packet. The crash in cancelation is probably exposed because of that.

* the alpha_map vector always (de)serialises
  the actual version (could empty sometimes)
* AggregateFunctionTopK generic variant deserialises
  it as well instead of ignoring it
* AggregateFunctionTopK generic variant clears the
  array before deserialising

refs #1283

### CODE REVIEW

File: dbms/src/Common/SpaceSaving.h [hunk 1]
```diff
@@ -255,6 +260,8 @@ class SpaceSaving
         writeVarUInt(size(), wb);
         for (auto counter : counter_list)
             counter->write(wb);
+
+        writeVarUInt(alpha_map.size(), wb);
```
Comment (vavrusa) [inline dbms/src/Common/SpaceSaving.h]: This explicitly stores the alpha map size in state in case, it should be the same most of the times though (unless someone actually stores this and then uses different K when finalizing state).

File: dbms/src/AggregateFunctions/AggregateFunctionTopK.h [hunk 2]
```diff
@@ -206,6 +209,8 @@ class AggregateFunctionTopKGeneric : public IUnaryAggregateFunction<AggregateFun
             set.insert(ref, count, error);
             arena->rollback(ref.size);
         }
+
+        set.readAlphaMap(buf);
```
Comment (vavrusa) [inline dbms/src/AggregateFunctions/AggregateFunctionTopK.h]: This is probably the cause.

**Comment by vavrusa** [comment]
```sql
:) SELECT * FROM system.clusters

┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name─┬─host_address─┬─port─┬─is_local─┬─user────┬─default_database─┐
│ logs    │         1 │            1 │           1 │ localhost │ ::1          │ 9000 │        1 │ default │                  │
│ logs    │         2 │            2 │           1 │ localhost │ ::1          │ 9000 │        0 │ default │ extra            │
└─────────┴───────────┴──────────────┴─────────────┴───────────┴──────────────┴──────┴──────────┴─────────┴──────────────────┘

2 rows in set. Elapsed: 0.014 sec.

:) CREATE TABLE extra.numbers AS numbers ENGINE = Memory()

Ok.

0 rows in set. Elapsed: 0.003 sec.

:) CREATE VIEW extra.numbers AS SELECT * FROM system.numbers LIMIT 1000000

Ok.

0 rows in set. Elapsed: 0.004 sec.

:) DROP TABLE d

Ok.

0 rows in set. Elapsed: 0.002 sec.

:) CREATE TABLE d AS system.numbers ENGINE = Distributed(logs, '', numbers)

Ok.

0 rows in set. Elapsed: 0.004 sec.

:) SELECT topK(5)(toString(if((number % 2) = 0, number % 5, number))) FROM d

┌─topK(5)(toString(if(equals(modulo(number, 2), 0), modulo(number, 5), number)))─┐
│ ['3','1','4','2','0']                                                          │
└────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.184 sec. Processed 1.05 million rows, 8.39 MB (5.71 million rows/s., 45.70 MB/s.)
```

File: dbms/src/Common/SpaceSaving.h [hunk 3]
```diff
@@ -273,7 +280,14 @@ class SpaceSaving
             push(counter);
         }
 
-        for (size_t i = 0; i < nextAlphaSize(m_capacity); ++i)
+        readAlphaMap(rb);
```
Comment (vavrusa) [inline dbms/src/Common/SpaceSaving.h]: Now the bucket frequencies (alpha map) are serialised/deserialised as well which should increase precision in distributed tables (or when processing a lot of rows).

**Comment by vavrusa** [comment]
@alexey-milovidov could you take a look? I have some other changes, but don't want to start separate PRs depending on this.

**Comment by alexey-milovidov** [comment]
Sorry for the delay. Looking right now...
