### PR TITLE
Change the behaviour of domain function with URLs containing UserInfo & @

### LINKED ISSUE #41262: Wrong behaviour of domain() function with URLs containing userInfo part
I found a wrong behaviour of function domain() when URL has userInfo part (basicauth) data in it. 
This cause error in defining right domain for valid URLs according to RFC: [rfc1738](https://www.rfc-editor.org/rfc/rfc1738), [rfc2396](https://www.rfc-editor.org/rfc/rfc2396) 
The domain() function returned an empty answer or userInfo data instead of the actual domain for URLs like this:
1. https://user:pass@clickhouse.com/
2. https://alexey.milovidov:pass@clickhouse.com/

Behaviour was successfully reproduced on the latest release 22.8.5.29 and bellow.

**How to reproduce**
```
SELECT domain('https://user:pass@clickhouse.com/docs/en/intro/')

Query id: ac53e392-90fc-44ee-a0f2-15e236a13e90

┌─domain('https://user:pass@clickhouse.com/docs/en/intro/')─┐
│                                                           │
└───────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

SELECT domain('https://alexey.milovidov:pass@clickhouse.com/docs/en/intro/')

Query id: c4812dcd-c311-4a20-90a5-19247b150e33

┌─domain('https://alexey.milovidov:pass@clickhouse.com/docs/en/intro/')─┐
│ alexey.milovidov                                                      │
└───────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.

SELECT version()

Query id: 620c2b92-efb2-454f-9b1a-79b684d4ddb3

┌─version()─┐
│ 22.8.5.29 │
└───────────┘
```
* ClickHouse server version 22.8.5.29

**Expected behavior**
1. https://user:pass@clickhouse.com/docs/en/intro/    -->   clickhouse.com
2. https://alexey.milovidov:pass@clickhouse.com/docs/en/intro/  --> clickhouse.com

**Additional context**

I had created some SQL code to roundabout this issue, it may be helpful to someone who faced it.
Code was tested on 1bln of real valid URLs containing the '@' symbol in different places.

```
SELECT
    url,
    domain(multiIf(match(url, '@') = 0, domain(url), ((position(url, '?') AS c) < a) AND (c > 0), domain(url), ((position(url, '/', 9) AS b) > 0) AND ((position(url, '@', 9) AS a) < b), substring(url, a + 1, (b - a) - 1), b = 0, substring(url, a + 1, length(url) - a), domain(url))) AS dom,
    domain(url)
FROM
(
    SELECT 'https://user:pass@clickhouse.com/docs/en/intro/' AS url
    UNION ALL
    SELECT 'https://alexey.milovidov:pass@clickhouse.com/docs/en/intro/' AS url
)

Query id: dce5bc09-d148-4683-a6ee-4955eedf3094

┌─url─────────────────────────────────────────────┬─dom────────────┬─domain(url)─┐
│ https://user:pass@clickhouse.com/docs/en/intro/ │ clickhouse.com │             │
└─────────────────────────────────────────────────┴────────────────┴─────────────┘
┌─url─────────────────────────────────────────────────────────┬─dom────────────┬─domain(url)──────┐
│ https://alexey.milovidov:pass@clickhouse.com/docs/en/intro/ │ clickhouse.com │ alexey.milovidov │
└─────────────────────────────────────────────────────────────┴────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.003 sec
```

### PR DESCRIPTION
**Pull request by dentiscalprum**
When UserInfo part and '@' appear in the URL, the host after @ should be returned. For example, when url is "https://user:pass@clickhouse.com/", start_of_host should be char 'c' after '@', end_of_host should be '/' other than ':'.

### Changelog category (leave one):

* New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

* Add `URL` Functions which conform rfc. Functions include: `cutToFirstSignificantSubdomainCustomRFC`, `cutToFirstSignificantSubdomainCustomWithWWWRFC`, `cutToFirstSignificantSubdomainRFC`, `cutToFirstSignificantSubdomainWithWWWRFC`, `domainRFC`, `domainWithoutWWWRFC`, `firstSignificantSubdomainCustomRFC`, `firstSignificantSubdomainRFC`, `portRFC`,  `topLevelDomainRFC`

For example, when url is "https://user:pass@clickhouse.com/", start_of_host should be char 'c' after '@', end_of_host should be '/' other than ':'.

Close https://github.com/ClickHouse/ClickHouse/issues/41262

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: tests/queries/0_stateless/00398_url_functions.sql [hunk 1]
```diff
@@ -8,6 +8,8 @@ SELECT protocol('//127.0.0.1:443/') AS Scheme;
 
 SELECT '====HOST====';
 SELECT domain('http://paul@www.example.com:80/') AS Host;
+SELECT domain('http://paul:password@www.example.com:80/') AS HOST;
+SELECT domain('http://paul.user:password@www.example.com:80/') AS HOST;
```
Comment (vdimir) [inline tests/queries/0_stateless/00398_url_functions.sql:12]:
```suggestion
SELECT domain('http://paul.user:password@www.example.com:80/') AS HOST;
SELECT domain('http://paul.user:password@www.example.com:80') AS HOST;
SELECT domain('http://paul.user:password@www.example.com/') AS HOST;
SELECT domain('http://paul.user:password@www.example.com') AS HOST;
SELECT domain('http://paul.user:pass.word@www.example.com') AS HOST;
```

File: tests/queries/0_stateless/00398_url_functions.reference [hunk 2]
```diff
@@ -7,6 +7,8 @@ http
 
 ====HOST====
 www.example.com
+www.example.com
+www.example.com
```
Comment (vdimir) [inline tests/queries/0_stateless/00398_url_functions.reference:11]:
```suggestion
www.example.com
www.example.com
www.example.com
www.example.com
www.example.com
```

File: tests/queries/0_stateless/00398_url_functions.sql (hunk 1 above)
Comment (vdimir) [reply tests/queries/0_stateless/00398_url_functions.sql:12]: Actually maybe we can find some known testsuite for the rfc ?

**Comment by vdimir** [comment]
Some tests are failed because they use `domain` function for out `test.hits` dataset in stateful tests. Behaviour is changed, and it leads to a different result. We may check which rows were affected, validate if the current version is correct, and update these tests.

**Comment by dentiscalprum** [comment]
> Some tests are failed because they use `domain` function for out `test.hits` dataset in stateful tests. Behaviour is changed, and it leads to a different result. We may check which rows were affected, validate if the current version is correct, and update these tests.

I found the address that solved fail and this situation has been adapted.

**Comment by vdimir** [comment]
> I found the address that solved fail and this situation has been adapted.

Great! Could you also please some of them here?

**Comment by dentiscalprum** [comment]
> Great! Could you also please some of them here?

This two address:
https://hurpass.com:3912%2F1.2&name=43&text=зайцев финансоножка&noreask
http://hurpass.com:3912&Sn=238699-wh-643-fw-1164427100

It seems that there are still addresses that cannot be domained, I will check again

File: tests/queries/0_stateless/00398_url_functions.sql (hunk 1 above)
Comment (dentiscalprum) [reply tests/queries/0_stateless/00398_url_functions.sql]: > Actually maybe we can find some known testsuite for the rfc ?

https://github.com/Sporkmonger/Addressable/blob/master/spec/addressable/uri_spec.rb

Refer to this

**Comment by alexey-milovidov** [comment]
How does performance change?

**Comment by azat** [comment]
Also it will be great to show in changelog that it affects not only `domain` function everything that uses it internally:

```
src/Functions/URL/ExtractFirstSignificantSubdomain.h:        ExtractDomain<without_www>::execute(data, size, tmp, domain_length);
src/Functions/URL/ExtractFirstSignificantSubdomain.h:        ExtractDomain<without_www>::execute(data, size, tmp, domain_length);
src/Functions/URL/domain.cpp:using FunctionDomain = FunctionStringToString<ExtractSubstringImpl<ExtractDomain<false>>, NameDomain>;
src/Functions/URL/domain.h:inline std::string_view getURLHost(const char * data, size_t size)
src/Functions/URL/domain.h:struct ExtractDomain
src/Functions/URL/domain.h:        std::string_view host = getURLHost(data, size);
src/Functions/URL/domainWithoutWWW.cpp:using FunctionDomainWithoutWWW = FunctionStringToString<ExtractSubstringImpl<ExtractDomain<true>>, NameDomainWithoutWWW>;
src/Functions/URL/port.cpp:        std::string_view host = getURLHost(p, size);
src/Functions/URL/topLevelDomain.cpp:        std::string_view host = getURLHost(data, size);
src/Functions/URL/topLevelDomain.cpp:            /// since getURLHost() will not return a host if there is symbol after dot.
```

So:

- `port`
- `topLevelDomain`
- `domain`
- `cutToFirstSignificantSubdomain` (and all it's variants)

**Comment by azat** [comment]
>How does performance change?

Performance tests shows a little slowdown:



Old, s | New, s | Ratio of speedup (-) or slowdown (+) | Relative difference (new − old) / old | p < 0.01 threshold | Test | # | Query
-- | -- | -- | -- | -- | -- | -- | --
0.618 | 0.682 | +1.102x | 0.102 | 0.102 | url_hits | 1 | SELECT count() FROM hits_100m_single WHERE NOT ignore(domain(URL))

But only for raw domain, everything else is OK.
Maybe because now there are few more instructions for each domain, even though they can be omitted if you don't have userinfo in the URL.

File: tests/queries/0_stateless/00398_url_functions.sql [hunk 3]
```diff
@@ -8,6 +8,12 @@ SELECT protocol('//127.0.0.1:443/') AS Scheme;
 
 SELECT '====HOST====';
 SELECT domain('http://paul@www.example.com:80/') AS Host;
+SELECT domain('user:password@example.com:8080') AS Host;
+SELECT domain('http://user:password@example.com:8080') AS Host;
+SELECT domain('http://user:password@example.com:8080/path?query=value#fragment') AS Host;
+SELECT domain('newuser:@example.com') AS Host;
+SELECT domain('http://:pass@example.com') AS Host;
+SELECT domain(':newpass@example.com') AS Host;
```
Comment (azat) [inline tests/queries/0_stateless/00398_url_functions.sql:16]: Consider adding examples with multiple `@`/`:`, i.e. `http://foo:bar@bar@.com`.
Now this implementation works like `urllib.urlparse` in python, however it is better to document this in the tests.

**Comment by azat** [comment]
By the way, maybe it work marking this is backward incompatible change? Since someone may rely on the specific behavior of this function (for example if someone uses it for sharding).

**Comment by azat** [comment]
@dentiscalprum about changelog entry, I meant to use `Backward Incompatible Change` as `Changelog category` (https://raw.githubusercontent.com/ClickHouse/ClickHouse/master/.github/PULL_REQUEST_TEMPLATE.md).

Also AFAIR changelogs are not supports multiple list elements, so it is better to write it in one line somehow.

**Comment by alexey-milovidov** [comment]
Yes, let's do.

**Comment by azat** [comment]
>Maybe it will be convenient to keep the old functions under some names?

I would vote to introduce new functions with this new behavior not with old.

**Comment by alexey-milovidov** [comment]
@azat yes, it will be much better.

Let's name them:

domainPrecise
portPrecise
... etc.

**Comment by azat** [comment]
Maybe `domainRFC` and similar? (means RFC compatible)

**Comment by dentiscalprum** [comment]
> Maybe `domainRFC` and similar? (means RFC compatible)

@alexey-milovidov @azat @vdimir  Added RFC form of these functions, please review this PR

**Review by vdimir — APPROVED** [review]
Thank you for the great work!

It is worth adding test cases for all added functions (probably using `.sql.j2` not to have copy-paste) and documentation (the current `domain` is not documented as well, though). But I don't want to block this PR anymore, so we can do it ourselves in a separate PR.

**Comment by azat** [comment]
Also worth to add performance tests for this new functions.

File: src/Functions/URL/domain.h [hunk 4]
```diff
@@ -20,6 +20,115 @@ inline std::string_view checkAndReturnHost(const Pos & pos, const Pos & dot_pos,
     return std::string_view(start_of_host, pos - start_of_host);
 }
 
+/// Extracts host from given url (RPC).
+///
+/// @return empty string view if the host is not valid (i.e. it does not have dot, or there no symbol after dot).
+inline std::string_view getURLHostRFC(const char * data, size_t size)
```
Comment (azat) [inline src/Functions/URL/domain.h:26]: New functions are still non RFC conformant, here are some issues with it:

- maximum schema length is 16 (this is an optimization likely, because it should work for both, URL and domain)
- restricted symbols are wrong, they should be like this:

```

      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
      pct-encoded = "%" HEXDIG HEXDIG
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
      reserved    = gen-delims / sub-delims

      userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
      host        = IP-literal / IPv4address / reg-name
      reg-name    = *( unreserved / pct-encoded / sub-delims )
```

While here lots of this symbols are prohibited (`~`, `%`, ...)

According to https://www.rfc-editor.org/rfc/rfc3986

Comment (azat) [reply src/Functions/URL/domain.h:26]: And while it is more or less OK to ignore lots of symbols in host name (since unlikely you will be able to register such domain, though you can always server wildcard domains from your server directly, and in this case you depends on what browsers detects ad domain), it could be a problem to not allow such symbols in userinfo

Comment (azat) [reply src/Functions/URL/domain.h:26]: Here are some changes - https://github.com/ClickHouse/ClickHouse/pull/46841
