### PR TITLE
Fix `nan` in Aggregator.cpp

### LINKED ISSUE #75225: Aggregator.cpp:nan is outside the range of representable values

### PR DESCRIPTION
**Pull request by yariks5s**
Fixes #75225

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit f3903fc14c1d3985d69c6e20d204abd5515213dd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75226/f3903fc14c1d3985d69c6e20d204abd5515213dd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d819a5d0e4c4f9b1fe582ec61689c9a053c045d7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by yariks5s** [comment]
I didn't create the test because it seems to be memory-dependent, and it is not clear how to create it

File: src/Interpreters/Aggregator.cpp [hunk 1]
```diff
@@ -240,23 +241,35 @@ size_t Aggregator::Params::getMaxBytesBeforeExternalGroupBy(size_t max_bytes_bef
...
 
-            LOG_TRACE(getLogger("Aggregator"), "Adjusting memory limit before external aggregation with {} (ratio: {}, available system memory: {})",
-                formatReadableSizeWithBinarySuffix(ratio_in_bytes),
-                ratio,
-                formatReadableSizeWithBinarySuffix(*available_system_memory));
-        }
-        else
-        {
-            LOG_WARNING(getLogger("Aggregator"), "No system memory limits configured. Ignoring max_bytes_ratio_before_external_group_by");
+            double computed_value = static_cast<double>(*available_system_memory) * ratio;
```
Comment (nickitat) [inline src/Interpreters/Aggregator.cpp:249]: It doesn't seem possible to get a NaN value by multiplying a finite number by a value in [0; 1). So maybe just check that `ratio` is a valid number on l.238?

Comment (yariks5s) [reply src/Interpreters/Aggregator.cpp]: done

**Comment by nickitat** [comment]
could you also pls add a test that reproduces the original problem

File: src/Interpreters/Aggregator.cpp [hunk 2]
```diff
@@ -239,7 +239,7 @@ size_t Aggregator::Params::getMaxBytesBeforeExternalGroupBy(size_t max_bytes_bef
             throw Exception(ErrorCodes::BAD_ARGUMENTS, "Setting max_bytes_ratio_before_external_group_by should be >= 0 and < 1 ({})", ratio);
 
         auto available_system_memory = getMostStrictAvailableSystemMemory();
-        if (available_system_memory.has_value())
+        if (available_system_memory.has_value() && !std::isnan(ratio))
```
Comment (alexey-milovidov) [inline src/Interpreters/Aggregator.cpp:242]: SortingStep.cpp

File: tests/queries/0_stateless/03322_nan_in_aggregator.sql [hunk 3]
```diff
@@ -0,0 +1,6 @@
+SET send_logs_level='fatal';
+
+SELECT uniqExact(CAST(number, 'String'))
+FROM numbers(1000.)
+GROUP BY CAST(number % 2, 'String')
+SETTINGS max_bytes_ratio_before_external_group_by = nan;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/03322_nan_in_aggregator.sql:6]: The fix is not in the right place. Instead, we should prevent NaN and Inf in floating point settings.

Comment (yariks5s) [reply tests/queries/0_stateless/03322_nan_in_aggregator.sql]: I will push a fix regarding it shortly

**Comment by yariks5s** [comment]
Will merge it now to fix the connected issue and push a proper fix shortly after this one.

File: src/Processors/QueryPlan/SortingStep.cpp [hunk 4]
```diff
@@ -78,7 +78,7 @@ size_t getMaxBytesBeforeExternalSort(size_t max_bytes_before_external_sort, doub
             throw Exception(ErrorCodes::BAD_ARGUMENTS, "Setting max_bytes_ratio_before_external_sort should be >= 0 and < 1 ({})", ratio);
 
         auto available_system_memory = getMostStrictAvailableSystemMemory();
-        if (available_system_memory.has_value())
+        if (available_system_memory.has_value() && !std::isnan(ratio))
```
[the remark this answers is not in the document]
Comment (rschu1ze) [reply src/Processors/QueryPlan/SortingStep.cpp:81]: Ah, I didn't read above discussion :)
