### PR TITLE
Make query_log faster under MSAN

### LINKED ISSUE #91410: Timeouts on `SYSTEM FLUSH LOGS` (caused by MSan overhead)
_Important: This issue was automatically created and is used by CI to track and match failures. DO NOT edit or remove the issue title, labels, or body content._

Failure reason: DB::Exception: Timeout exceeded

Failure flags: retry_ok

Required CI action: ignore

Job pattern: Stateless tests (amd_msan%
Test pattern: %

CI report example: [Stateless tests (amd_msan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91696&sha=6db1ad733e34f0d8552150d028c44dea96c97e42&name_0=PR&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%29)
Test output example:
```
2025-12-08 16:47:33 Reason: return code:  159
2025-12-08 16:47:33 [434f7079de3c] 2025.12.08 16:47:33.248684 [ 868832 ] {577c5f91-c213-41c6-9098-a9c3a573ce23} <Error> executeQuery: Code: 159. DB::Exception: Timeout exceeded (180 s) while flushing ...
2025-12-08 16:47:33 
2025-12-08 16:47:33 0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000005eedfe26
2025-12-08 16:47:33 1. ./ci/tmp/build/./src/Common/Exception.cpp:131: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002b505f70
2025-12-08 16:47:33 2. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000a89f92e
2025-12-08 16:47:33 3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000a89e5ff
2025-12-08 16:47:33 4. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000a89c88...
2025-12-08 16:47:33 5. ./ci/tmp/build/./src/Common/SystemLogBase.cpp:186: DB::SystemLogQueue<DB::TraceLogElement>::waitFlush(long, bool) @ 0x000000002b9bdaab
2025-12-08 16:47:33 6. ./ci/tmp/build/./src/Common/SystemLogBase.cpp:288: DB::SystemLogBase<DB::TraceLogElement>::flush(long, bool) @ 0x000000002b9bc866
2025-12-08 16:47:33 7. ./ci/tmp/build/./src/Interpreters/SystemLog.cpp:539: DB::SystemLogs::flushImpl(std::vector<std::pair<String, String>, std::allocator<std::pair<String, String>>> const&, bool, bo...
2025-12-08 16:47:33 8. ./ci/tmp/build/./src/Interpreters/SystemLog.cpp:556: DB::SystemLogs::flush(std::vector<std::pair<String, String>, std::allocator<std::pair<String, String>>> const&) @ 0x00000000...
2025-12-08 16:47:33 9. ./ci/tmp/build/./src/Interpreters/InterpreterSystemQuery.cpp:860: DB::InterpreterSystemQuery::execute() @ 0x00000000431b455e
2025-12-08 16:47:33 10. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1746: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::...
2025-12-08 16:47:33 11. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1967: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000...
2025-12-08 16:47:33 12. ./ci/tmp/build/./src/Server/TCPHandler.cpp:777: DB::TCPHandler::runImpl() @ 0x0000000051ab164d
2025-12-08 16:47:33 13. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2873: DB::TCPHandler::run() @ 0x0000000051b25e0e
2025-12-08 16:47:33 14. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000005f178960
2025-12-08 16:47:33 15. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000005f179952
2025-12-08 16:47:33 16. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000005f0207f5
2025-12-08 16:47:33 17. ./ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000005f01ccae
2025-12-08 16:47:33 18. ./base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000005f019711
2025-12-08 16:47:33 19. ? @ 0x0000000000094ac3
2025-12-08 16:47:33 20. ? @ 0x00000000001268c0
2025-12-08 16:47:33 
2025-12-08 16:47:33 Received exception from server (version 25.12.1):
2025-12-08 16:47:33 Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Timeout exceeded (180 s) while flushing system log 'DB::SystemLogQueue<DB::TraceLogElement>'.. (TIMEOUT_EXCEE...
2025-12-08 16:47:33 (query: SYSTEM FLUSH LOGS /* all tables */;)
2025-12-08 16:47:33 , result:
2025-12-08 16:47:33 
2025-12-08 16:47:33 
2025-12-08 16:47:33 
2025-12-08 16:47:33 stdout:
2025-12-08 16:47:33 
2025-12-08 16:47:33 
2025-12-08 16:47:33 Settings used in the test: --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 33658432 --distributed_aggregation_memory_efficient 1 ...
2025-12-08 16:47:33 
2025-12-08 16:47:33 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 1 --vertical_merge_algorithm_min_rows_to_activate 1 --ve...
2025-12-08 16:47:33 
2025-12-08 16:47:33 Database: test_naoxh389
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Make query_log faster under MSAN by disabling it when building Settings.cpp

Closes https://github.com/ClickHouse/ClickHouse/issues/91410

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Core/Settings.cpp [hunk 1]
```diff
@@ -7665,26 +7668,39 @@ void SettingsImpl::dumpToMapColumn(IColumn * column, bool changed_only)
...
     auto & key_column = typeid_cast<ColumnLowCardinality &>(tuple_column.getColumn(0));
     auto & value_column = typeid_cast<ColumnLowCardinality &>(tuple_column.getColumn(1));
 
+    chassert(!key_column.isSharedDictionary());
+    auto & key_dictionary = typeid_cast<ColumnUnique<ColumnString> &>(key_column.getDictionary());
+    auto & key_indexes = key_column.getColumnIndex();
+
+    chassert(!value_column.isSharedDictionary());
+    auto & value_dictionary = typeid_cast<ColumnUnique<ColumnString> &>(value_column.getDictionary());
+    auto & value_indexes = value_column.getColumnIndex();
```
Comment (azat) [inline src/Core/Settings.cpp]: Do we still need this after `-fomit-frame-pointer -momit-leaf-frame-pointer -fno-sanitize-memory-track-origins` ?

File: src/Core/Settings.cpp [hunk 2]
```diff
@@ -7665,26 +7668,39 @@ void SettingsImpl::dumpToMapColumn(IColumn * column, bool changed_only)
...
+
     size_t size = 0;
 
     /// Iterate over standard settings
     const auto & accessor = Traits::Accessor::instance();
+    const auto & field_infos = accessor.field_infos;
     for (size_t i = 0; i < accessor.size(); i++)
     {
-        if (changed_only && !accessor.isValueChanged(*this, i))
+        if (changed_only && !field_infos[i].is_value_changed_function(*this))
```
Comment (azat) [inline src/Core/Settings.cpp]: Does this really helps?

File: src/Core/Settings.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Core/Settings.cpp]: Probably not, I started commit by commit and probably the last one is the only one that matters

**Comment by azat** [comment]
Apparently the situation became worse right now, maybe upgrade to clang-21 makes MSan slower...

UPD: nope - https://play.clickhouse.com/play?user=play&run=1#U0VMRUNUIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSwgY291bnQoKQpGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMTAwIGRheQogICAgQU5EIChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBzdGFydHNXaXRoKGhlYWRfcmVwbywgJ0NsaWNrSG91c2UvJykpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScpIAogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCB0ZXN0X2NvbnRleHRfcmF3IGxpa2UgJyVUaW1lb3V0IGV4Y2VlZGVkJXdoaWxlIGZsdXNoaW5nIHN5c3RlbSBsb2clREI6OlN5c3RlbUxvZ1F1ZXVlPERCOjpRdWVyeUxvZ0VsZW1lbnQ+JScKR1JPVVAgQlkgMQpPUkRFUiBCWSAx

File: src/Core/Settings.cpp (hunk 1 above)
Comment (azat) [reply src/Core/Settings.cpp]: Maybe it make sense to leave only last commit then?

**Comment by azat** [comment]
Also let's do logging of timings (added in https://github.com/ClickHouse/ClickHouse/pull/91472) only if it exceed some threshold, i.e. 100ms?

File: src/Core/Settings.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Core/Settings.cpp]: Done
