### PR TITLE
Fix crash in `sqidDecode`

### LINKED ISSUE #69450: `LOGICAL_ERROR` in `sqidDecode` function
```sql
create table test (id String) engine=MergeTree order by id;
insert into test select * from generateRandom() limit 1000000;
select sqidDecode(id) from test;
-- Boom.
```

### PR DESCRIPTION
**Pull request by rschu1ze**
Resolves #69450

### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed a `LOGICAL_ERROR` with function `sqidDecode` (#69450)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 04dcf73e8fb98fbcdee2ead46e7177c961e1b5f6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69451/04dcf73e8fb98fbcdee2ead46e7177c961e1b5f6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/db42cf12fd0e7a54b9a63118b21c300eddb7970e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Functions/sqid.cpp [hunk 1]
```diff
@@ -124,7 +124,7 @@ class FunctionSqidDecode : public IFunction
                 std::string_view sqid = col_non_const->getDataAt(i).toView();
                 std::vector<UInt64> integers = sqids.decode(String(sqid));
                 res_nested_data.insert(integers.begin(), integers.end());
-                res_offsets_data.push_back(integers.size());
+                res_offsets_data.push_back(i == 0 ? integers.size() : res_offsets_data.back() + integers.size());
```
Comment (Avogar) [inline src/Functions/sqid.cpp:127]: `res_offsets_data` is `PaddedPODArray` and `back()` returns 0 when it's empty, so no need to check for `i = 0`

Comment (rschu1ze) [reply src/Functions/sqid.cpp:127]: Tnx, fixed.

**Review by Avogar — APPROVED** [review]
