### PR TITLE
Refactor `midpoint` function and fix many logical errors, overflow and functional bugs

### LINKED ISSUE #91816: [Fuzzer] `midpoint` produces empty Nullable result and fails with “Invalid number of rows in Chunk” on nullable literal input
### Describe the bug

A query using midpoint with a nullable literal crashes with a chunk size mismatch.

Stack trace ends at DB::Chunk::checkNumRowsIsConsistent() via ExpressionTransform::transform. The result column from midpoint is Nullable(Float64) with size 0 while other columns are Const(size = 2), causing the crash.

Maybe caused by  `useDefaultImplementationForNulls() == false` but lacking accurate nullable handling.

### How to reproduce

```
SELECT midpoint(materialize(toNullable(toNullable(71))), 11);
```

http://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91431&sha=2c87d97a664c2b2757e96e022608f6c2f24c37bb&name_0=PR&name_1=AST+fuzzer+%28arm_asan%29

https://fiddle.clickhouse.com/9296b8e6-684f-40b0-80c7-1412b3b67709

### Error message and/or stacktrace

```
Error:
Logical error: 'Invalid number of rows in Chunk  Nullable(size = 0, Float64(size = 0), UInt8(size = 0)) Const(size = 2, UInt8(size = 1)) Const(size = 2, UInt64(size = 1)) Const(size = 2, String(size = 1)) column Nullable(Float64) at position 0: expected 2, got 0'.
---

Failed query:
SELECT DISTINCT midpoint(materialize(toNullable(toNullable(71))), f64) AS result, or(not(isNull(3)), equals(6048000000000000, 71)), 6048000000000000, toTypeName(result) AS type FROM midpoint_test
---

Reproduce commands (auto-generated; may require manual adjustment):
CREATE TABLE midpoint_test (`ui8` UInt8, `ui16` UInt16, `ui32` UInt32, `i8` Int8, `i16` Int16, `i32` Int32, `f32` Float32, `f64` Float64, `d32` Decimal32(3), `d64` Decimal64(3)) ENGINE = Memory
SELECT DISTINCT midpoint(materialize(toNullable(toNullable(71))), f64) AS result, or(not(isNull(3)), equals(6048000000000000, 71)), 6048000000000000, toTypeName(result) AS type FROM midpoint_test
DROP TABLE IF EXISTS midpoint_test
---

Stack trace:
__pthread_kill_implementation @ 0x0000000000082009
gsignal @ 0x000000000003a83c
__GI_abort @ 0x0000000000027134
src/Common/Exception.cpp:54: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x000000001e002ff4
src/Common/Exception.cpp:87: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000001e00449c
src/Common/Exception.cpp:138: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001e004a58
DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000f3b6f9c
DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000f3b62cc
./src/Common/Exception.h:141: DB::Exception::Exception<String, String, unsigned long&, unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, String&&, String&&, unsigned long&, unsigned long&, unsigned long&&) @ 0x0000000033a16940
src/Processors/Chunk.cpp:65: DB::Chunk::checkNumRowsIsConsistent() @ 0x0000000033a12e6c
src/Processors/Transforms/ExpressionTransform.cpp:28: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x0000000033feeea8
./src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x0000000023647900
src/Processors/ISimpleTransform.cpp:98: DB::ISimpleTransform::work() @ 0x0000000033a2bcc0
src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x0000000033a67790
src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x0000000033a4c480
src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*)
src/Processors/Executors/PipelineExecutor.cpp:602: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000033a4ae60
src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000033a4a608
src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:102: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:249: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__invoke[abi:ne210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
inlined from ./contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:ne210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
inlined from ./contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:ne210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
inlined from ./src/Common/ThreadPool.h:312: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:249: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__invoke[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0 std::__invoke_r[abi:ne210105]<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>()
./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x0000000033a79174
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000001e2a4800
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:ne210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
./contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:ne210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001e2b17b0
asan_thread_start(void*) @ 0x000000000f366b34
start_thread @ 0x0000000000080398
thread_start @ 0x00000000000e9e9c
```

### PR DESCRIPTION
**Pull request by nihalzp**
#### Logical error:

```sql
SELECT midpoint(materialize(toNullable(1)), 11);
```

#### Wrong result for mixed numeric types:

```sql
SELECT midpoint(toUInt32(100), toDecimal32(200, 3));
```
Outputs `100.05` but should be `150`.

#### Inconsistent rounding behavior:

```sql
SELECT midpoint(-4, -5); 
-- Returns -5 (rounds towards neg infinity)

SELECT midpoint(-10, -4, -2, -2); 
-- Returns -4 (rounds towards 0)
```

#### Overflow:

```sql
SELECT midpoint(toInt64('9223372036854775807'), toInt64('9223372036854775807'), toInt64('9223372036854775807'));
```
Returns `3074457345618258601`, but should be `9223372036854775807`.

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix numerous logical errors, overflow and functional bugs in `midpoint` function. Closes https://github.com/ClickHouse/ClickHouse/issues/91816.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Functions/midpoint.h [hunk 1]
```diff
@@ -53,70 +54,265 @@ class FunctionMidpoint : public IFunction
...
+    static void calculateForNumericType(auto & result_data, const Columns & input_columns, size_t input_rows_count)
     {
-        using FieldType = typename ColumnType::ValueType;
-        res_data.resize(input_rows_count);
-        // For each row, sum across all input columns
+        using ResultType = typename ResultColumnType::ValueType;
+
+        /// We try to temporary use wider type to avoid overflow in summation
+        /// Otherwise, midpoint(UINT64_MAX, UINT64_MAX, UINT64_MAX) would overflow.
+        using SumType = WiderInt<ResultType>;
```
[the remark this answers is not in the document]
Comment (nihalzp) [reply src/Functions/midpoint.h:91]: To avoid overflow in Int256, we need Int512 which we do not have; so, it's unavoidable.

File: src/Functions/midpoint.h [hunk 2]
```diff
@@ -53,70 +54,265 @@ class FunctionMidpoint : public IFunction
...
+        static constexpr bool is_signed_v = std::numeric_limits<T>::is_signed;
+
+        using type = std::conditional_t<
+            (sizeof(T) <= 8),
+            std::conditional_t<is_signed_v, Int128, UInt128>,
+            std::conditional_t<
+                (sizeof(T) <= 16),
+                std::conditional_t<is_signed_v, Int256, UInt256>,
+                T>>; /// cannot widen beyond 256-bit
+    };
```
Comment (antonio2368) [inline src/Functions/midpoint.h]: maybe
```suggestion
    template <typename T>
    struct WiderIntImpl
    {
        using type = T;
    };

    template <typename T>
    requires is_integer_like_v<T> && (sizeof(T) <= 16) /// cannot widen beyond 256-bit
    struct WiderIntImpl<T>
    {
        static constexpr bool is_signed_v = std::numeric_limits<T>::is_signed;

        using type = std::conditional_t<
            (sizeof(T) <= 8),
            std::conditional_t<is_signed_v, Int128, UInt128>,
            std::conditional_t<is_signed_v, Int256, UInt256>>;
    };
```

File: src/Functions/midpoint.h [hunk 3]
```diff
@@ -53,70 +54,265 @@ class FunctionMidpoint : public IFunction
...
+        }
+    }
+
+    template <typename ResultColumnType>
+    static void calculateForDecimalType(auto & result_data, const Columns & input_columns, size_t input_rows_count)
+    {
+        using ResultType = typename ResultColumnType::ValueType;
+        using Native = typename ResultType::NativeType;
+
+        using SumType = std::conditional_t<(sizeof(Native) <= 8), Int128, std::conditional_t<(sizeof(Native) <= 16), Int256, Native>>;
```
Comment (antonio2368) [inline src/Functions/midpoint.h]: this is WiderInt right?

File: src/Functions/midpoint.h [hunk 4]
```diff
@@ -137,48 +333,93 @@ class FunctionMidpoint : public IFunction
...
     {
-        if constexpr ( // Fast path: built-in integers
-            std::is_integral_v<A> && std::is_integral_v<B> &&
-            sizeof(A) <= 8 && sizeof(B) <= 8
-        )
+        if constexpr (is_floating_point<Result>)
+        {
+            return (static_cast<Result>(a) + static_cast<Result>(b)) / static_cast<Result>(2);
+        }
+        else if constexpr (std::is_integral_v<Result> || is_big_int_v<Result>)
```
Comment (antonio2368) [inline src/Functions/midpoint.h]:
```suggestion
        else if constexpr (is_integer_like_v<Result>)
```

File: src/Functions/midpoint.h [hunk 5]
```diff
@@ -137,48 +333,93 @@ class FunctionMidpoint : public IFunction
...
     template <typename Result = ResultType>
     static Result apply(A a, B b)
     {
-        if constexpr ( // Fast path: built-in integers
-            std::is_integral_v<A> && std::is_integral_v<B> &&
-            sizeof(A) <= 8 && sizeof(B) <= 8
-        )
+        if constexpr (is_floating_point<Result>)
+        {
+            return (static_cast<Result>(a) + static_cast<Result>(b)) / static_cast<Result>(2);
```
Comment (antonio2368) [inline src/Functions/midpoint.h]: this path is same as `else`, why do we need it?

File: src/Functions/midpoint.h (hunk 2 above)
Comment (nihalzp) [reply src/Functions/midpoint.h]: Thanks! This is more elegant and more readable.

**Review by antonio2368 — APPROVED** [review]

**Comment by nihalzp** [comment]
[Integration tests (amd_asan, db disk, old analyzer, 4/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92102&sha=ac5b0067a9314ee2c21d4b58a3008ef290a96311&name_0=PR&name_1=Integration%20tests%20%28amd_asan%2C%20db%20disk%2C%20old%20analyzer%2C%204%2F6%29)
- https://github.com/ClickHouse/ClickHouse/issues/90662

[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92102&sha=ac5b0067a9314ee2c21d4b58a3008ef290a96311&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)
- https://github.com/ClickHouse/ClickHouse/issues/92069
- https://github.com/ClickHouse/ClickHouse/issues/91710
