### PR TITLE
Combining our lexer with replxx for better multiple line editing

### LINKED ISSUE #32399: Client: long queries are not removed when navigating through history
**How to reproduce:**
1. Run several long queries in `clickhouse-client` such that query does not fit into one line in terminal
2. Try to navigate through history using "up" and "down" keys
3. You will see something like this:

Screenshot from 2021-12-08 16-16-06

It makes query history almost impossible to use.

**Expected behavior:**
Client should remove previous query from terminal before printing the next one (just like it worked in older versions and how it works now if query fits into one line)
Screenshot from 2021-12-08 16-20-59
Screenshot from 2021-12-08 16-21-26

### PR DESCRIPTION
**Pull request by amosbird**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Improving the experience of multiple line editing for clickhouse-client. This is a follow-up of https://github.com/ClickHouse/ClickHouse/pull/31123

This PR also contains replxx bump https://github.com/ClickHouse-Extras/replxx/pull/19 which fixes https://github.com/ClickHouse/ClickHouse/issues/32399

NOTE: This PR extends our lexer in that `\G` has a special type: `TokenType::VerticalDelimiter`

NOTE: Make sure `--highlight` is on (default) to take full advantage.

NOTE: This PR also ignores case for history search and completion.  (The feature was reverted when we switch to upstream replxx, now it's available officially)

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Client/ClientBaseHelpers.cpp [hunk 1]
```diff
@@ -6,6 +6,9 @@
 #include <Parsers/Lexer.h>
 #include <Common/UTF8Helpers.h>
 
+#if USE_REPLXX
+extern bool replxx_last_is_delimiter;
```
Comment (alexey-milovidov) [inline src/Client/ClientBaseHelpers.cpp:10]: Ok.

Communication with global variable looks dirty, at least a comment needed.
Maybe we can do it in some other way, like exposing functions in ReplxxLineReader to set this variable?

Comment (amosbird) [reply src/Client/ClientBaseHelpers.cpp]: Done.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Some tests need to be updated.

**Comment by amosbird** [comment]
The test failures are significant. It's because our original behavior of case-insensitive completion gets accidentally changed upstream. I've submitted the PR to change it back https://github.com/ClickHouse-Extras/replxx/pull/20 .

**Comment by amosbird** [comment]
CI looks good. No related failures.
