### PR TITLE
Attempt to fix test_peak_memory_usage - Part 2

### LINKED ISSUE #90840: Flaky test: test_peak_memory_usage/test.py::test_clickhouse_client_max_peak_memory_usage_distributed
### Highlights
- https://github.com/ClickHouse/ClickHouse/issues/90840#issuecomment-3662483887

### Report

Failure reason: assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
[CI report: [Integration tests (amd_binary, 2/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90717&sha=2d993904c4f95324ba1379a2c350943ce038502c&name_0=PR&name_1=Integration%20tests%20%28amd_binary%2C%202%2F5%29)]
[cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICd0ZXN0X3BlYWtfbWVtb3J5X3VzYWdlL3Rlc3QucHk6OnRlc3RfY2xpY2tob3VzZV9jbGllbnRfbWF4X3BlYWtfbWVtb3J5X3VzYWdlX2Rpc3RyaWJ1dGVkJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnSW50ZWdyYXRpb24gdGVzdHMgKGFtZF9iaW5hcnksIDIvNSknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwKSBPUiBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDApCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAIL [test_peak_memory_usage/test.py::test_clickhouse_client_max_peak_memory_usage_distributed]
  | File: test_peak_memory_usage/test.py:101 - in test_clickhouse_client_max_peak_memory_usage_distributed
  |     assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
  | E   AssertionError: assert False
  | E    +  where False = contains_in_log('Query peak memory usage: 8.23')
  | E    +    where contains_in_log = <helpers.cluster.ClickHouseInstance object at 0x7f62ad427dc0>.contains_in_log
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

### PR DESCRIPTION
**Pull request by alexbakharew**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Follow-up of https://github.com/ClickHouse/ClickHouse/pull/93910
Fixes: https://github.com/ClickHouse/ClickHouse/issues/90840

### Version info
- Merged into: `26.2.1.135`

### CODE REVIEW

File: src/Server/TCPHandler.cpp [hunk 1]
```diff
@@ -841,11 +841,10 @@ void TCPHandler::runImpl()
                 if (auto * create_query = query_state->parsed_query->as<ASTCreateQuery>();
                     create_query && create_query->isCreateQueryWithImmediateInsertSelect())
                 {
-                    sendProgress(*query_state);
-
                     /// Log peak memory usage just before sending it to client to make it as accurate as possible
                     /// (though note we may still have some allocations in between, that will make the difference)
                     query_scope->logPeakMemoryUsage();
+                    sendProgress(*query_state);
```
Comment (azat) [inline src/Server/TCPHandler.cpp:839]: I don't understand why this helps

The server logs peak memory usage via `logPeakMemoryUsage`
And the client receive peak memory usage via `sendSelectProfileEvents` (`thread_group->memory_tracker.getPeak()`)

So if you add more code between it should make things only worse, though unlikely `sendProgress` allocate something

But to be honest, I don't think that we need to report exactly the same values in the server logs and to the client, so I see two options - https://github.com/ClickHouse/ClickHouse/pull/93910#discussion_r2694523980:
- make the comparsion less strict
- use more complex query, so that allocations here will not update peak (since it will use more memory before)

Comment (azat) [reply src/Server/TCPHandler.cpp:839]: I've looked at one [failure](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=88ebc4a5a11762d01b191303f1577d5a18a093e8&name_0=MasterCI&name_1=Integration%20tests%20%28amd_binary%2C%202%2F5%29&name_1=Integration%20tests%20%28amd_binary%2C%202%2F5%29), but, it does not have events between these two lines

### test

```
File: test_peak_memory_usage/test.py:101 - in test_clickhouse_client_max_peak_memory_usage_distributed
    assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
E   AssertionError: assert False
E    +  where False = contains_in_log('Query peak memory usage: 9.25')
```

### shard_2

```
2026.01.26 02:41:51.736904 [ 18 ] {0be2b1ea-e07b-4272-ac4b-804024498422} <Debug> executeQuery: (from 172.16.2.5:52274, initial_query_id: a963d703-ae40-4daf-9b15-1d247d88f774) (query 1, line 1) SELECT count() AS `COUNT()` FROM `default`.`fixed_numbers` AS `__table1` ALL INNER JOIN `default`.`fixed_numbers_2` AS `__table2` ON `__table1`.`number` = `__table2`.`number` (stage: WithMergeableState)
2026.01.26 02:41:51.747163 [ 18 ] {0be2b1ea-e07b-4272-ac4b-804024498422} <Debug> MemoryTracker: Query peak memory usage: 8.32 MiB.
```

### shard_1 - initiator

```
2026.01.26 02:41:51.731816 [ 18 ] {a963d703-ae40-4daf-9b15-1d247d88f774} <Debug> executeQuery: (from 172.16.2.1:61928) (query 1, line 1) SELECT COUNT(*) FROM distributed_fixed_numbers JOIN fixed_numbers_2 ON distributed_fixed_numbers.number=fixed_numbers_2.number SETTINGS query_plan_join_swap_table = 'false', join_algorithm='hash' (stage: Complete)
2026.01.26 02:41:51.748141 [ 18 ] {a963d703-ae40-4daf-9b15-1d247d88f774} <Debug> MemoryTracker: Query peak memory usage: 3.81 MiB.
```

### trace_log on shard_2

```
:) select * except('symbols|lines'), arrayStringConcat(symbols, '\n') from system.trace_log where event_time = '2026.01.26 03:41:51' and trace_type = 'MemoryPeak' and query_id = '0be2b1ea-e07b-4272-ac4b-804024498422' and memory_context != 'Global' order by 1\G

SELECT
    * EXCEPT 'symbols|lines',
    arrayStringConcat(symbols, '\n')
FROM system.trace_log
WHERE (event_time = '2026.01.26 03:41:51') AND (trace_type = 'MemoryPeak') AND (query_id = '0be2b1ea-e07b-4272-ac4b-804024498422') AND (memory_context != 'Global')
ORDER BY 1 ASC

Query id: f895ae83-8a84-4120-92e3-5034d9ac5035

Row 1:
──────
hostname:                 shard_2
event_date:               2026-01-26
event_time:               2026-01-26 03:41:51
event_time_microseconds:  2026-01-26 03:41:51.740685
timestamp_ns:             1769395311740685469
revision:                 54506
trace_type:               MemoryPeak
cpu_id:                   13
thread_id:                261
thread_name:              QueryPipelineEx
query_id:                 0be2b1ea-e07b-4272-ac4b-804024498422
trace:                    [324811876,324688785,324688999,323960716,323957507,428843507,435060518,435055561,427721294,427711414,483509176,480780256,480727534,480733507,325517260,325538214,325508277,325530939,140486988520131,140486989117632]
size:                     8662630 -- 8.66 million
ptr:                      0
memory_context:           Process
memory_blocked_context:   Max
event:
increment:                0
function_id:              ᴺᵁᴸᴸ
function_name:            ᴺᵁᴸᴸ
handler:                  ᴺᵁᴸᴸ
entry_type:               ᴺᵁᴸᴸ
duration_nanoseconds:     ᴺᵁᴸᴸ
arrayStringC⋯bols, '\n'): StackTrace::StackTrace()
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
CurrentMemoryTracker::allocImpl(long, bool)
Allocator<true, true>::realloc(void*, unsigned long, unsigned long, unsigned long)
HashTable<unsigned long, HashMapCell<unsigned long, DB::RowRefList, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, DB::RowRefList>>, HashCRC32<unsigned long>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::resize(unsigned long, unsigned long)
void DB::HashJoinMethods<(DB::JoinKind)0, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>::insertFromBlockImplTypeCase<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned long, DB::RowRefList>, DB::RowRefList, unsigned long, false, true, false>, HashMapTable<unsigned long, HashMapCell<unsigned long, DB::RowRefList, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, DB::RowRefList>>, HashCRC32<unsigned long>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, std::__1::pair<unsigned long, unsigned long>>(DB::HashJoin&, HashMapTable<unsigned long, HashMapCell<unsigned long, DB::RowRefList, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, DB::RowRefList>>, HashCRC32<unsigned long>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long>> const&, DB::ColumnsInfo const*, std::__1::pair<unsigned long, unsigned long> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, DB::JoinCommon::JoinMask const&, DB::Arena&, bool&, bool&)
DB::HashJoinMethods<(DB::JoinKind)0, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>::insertFromBlockImpl(DB::HashJoin&, DB::HashJoin::Type, DB::HashJoin::MapsTemplate<DB::RowRefList>&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long>> const&, DB::ColumnsInfo const*, DB::detail::Selector const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, DB::JoinCommon::JoinMask const&, DB::Arena&, bool&, bool&)
DB::HashJoin::addBlockToJoin(DB::Block const&, DB::detail::Selector, bool)
DB::HashJoin::addBlockToJoin(DB::Block const&, bool)
DB::FillingRightJoinSideTransform::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::__1::atomic<bool>*)
void std::__1::__function::__policy_func<void ()>::__call_func[abi:ne210105]<DB::PipelineExecutor::spawnThreads(std::__1::shared_ptr<DB::IAcquiredSlot>)::$_0>(std::__1::__function::__policy_storage const*)
ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker()
ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()()
ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker()
void* std::__1::__thread_proxy[abi:ne210105]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*)
```

Comment (alexbakharew) [reply src/Server/TCPHandler.cpp:839]: As suggested, now test checks that difference between client and server values is in range [0,1)

File: src/Server/TCPHandler.cpp [hunk 2]
```diff
@@ -1446,12 +1438,8 @@ void TCPHandler::processOrdinaryQuery(QueryState & state, CurrentThread::QuerySc
         sendTotals(state, executor.getTotalsBlock());
         sendExtremes(state, executor.getExtremesBlock());
         sendProfileInfo(state, executor.getProfileInfo());
-        sendProgress(state);
+        // sendProgress(state);
```
Comment (azat) [inline src/Server/TCPHandler.cpp]: Why commented?
Let's organize this PR as two patches:
- 1) revert of the https://github.com/ClickHouse/ClickHouse/pull/93910
- 2) make the test more reliable

File: tests/integration/test_peak_memory_usage/test.py [hunk 3]
```diff
@@ -64,23 +64,39 @@ def started_cluster():
...
-
-    print(f"peak_memory_usage not found")
+                peak_memory_usage = search_obj.group()
+                print(f"peak_memory_usage {peak_memory_usage}")
+    
     client_output.close()
-    return ""
+    
+    if query_id is None:
+        print(f"query_id not found")
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py]: Why not just assert?

File: tests/integration/test_peak_memory_usage/test.py [hunk 4]
```diff
@@ -96,9 +112,39 @@ def test_clickhouse_client_max_peak_memory_usage_distributed(started_cluster):
...
+    server_memory_match = re.search(r"Query peak memory usage: ([0-9.]+)", server_memory_log)
+    assert server_memory_match, "Failed to parse server memory usage"
+    server_memory_value = float(server_memory_match.group(1))
+    
+    # Parse client memory usage value
+    client_memory_value = float(peak_memory_usage)
+    
+    # Assert difference is less than 1 MB
+    memory_diff = abs(client_memory_value - server_memory_value)
+    assert memory_diff < 1.0, f"Memory usage difference {memory_diff} MiB exceeds 1 MiB threshold (client: {client_memory_value} MiB, server: {server_memory_value} MiB)"
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py:115]: It is a good idea to make allow some diff in general, but maybe we can simply use more complex query that will eat more RAM, so, that once the query finished any other allocations will not increase their peak, i.e. something like this `SELECT sumMap([number], [number]) FROM numbers(1e6) format Null` ?

File: tests/integration/test_peak_memory_usage/test.py [hunk 5]
```diff
@@ -96,9 +112,39 @@ def test_clickhouse_client_max_peak_memory_usage_distributed(started_cluster):
...
 
-    peak_memory_usage = get_memory_usage_from_client_output_and_close(client_output)
+    query_id, peak_memory_usage = get_memory_usage_from_client_output_and_close(client_output)
+    assert query_id
     assert peak_memory_usage
-    assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
+    
+    # Extract required_query_id from shard2 logs
+    required_query_id = None
+    shard_2_logs = shard_2.grep_in_log(f"initial_query_id: {query_id}")
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py]: It is a good idea to match by query_id as well, but, it is easier to just use `send_logs_level=trace` on client, and get all the logs instead of grep the server log, and you will receive the message, example

```sql
azat.local$  :) SELECT sumMap([number], [number]) FROM numbers(1e6) format Null SETTINGS send_logs_level='trace', send_logs_source_regexp='MemoryTracker'

SELECT sumMap([number], [number])
FROM numbers(1000000.)
FORMAT `Null`
SETTINGS send_logs_level = 'trace', send_logs_source_regexp = 'MemoryTracker'

Query id: 2c2d67f2-a432-4211-b202-da82b041eb1e

[azat-desktop.local] 2026.01.28 18:38:44.845299 [ 8519 ] {2c2d67f2-a432-4211-b202-da82b041eb1e} <Debug> MemoryTracker: Query peak memory usage: 175.64 MiB.
Ok.

0 rows in set. Elapsed: 0.410 sec. Processed 1.00 million rows, 8.00 MB (2.44 million rows/s., 19.49 MB/s.)
Peak memory usage: 175.64 MiB.

```

File: tests/integration/test_peak_memory_usage/test.py [hunk 6]
```diff
@@ -96,9 +110,39 @@ def test_clickhouse_client_max_peak_memory_usage_distributed(started_cluster):
         client1.expect("Peak memory usage", timeout=60)
         client1.expect(prompt)
 
-    peak_memory_usage = get_memory_usage_from_client_output_and_close(client_output)
+    query_id, peak_memory_usage = get_memory_usage_from_client_output_and_close(client_output)
+    assert query_id
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py]: Here you always have `query_id`

File: tests/integration/test_peak_memory_usage/test.py (hunk 5 above)
Comment (azat) [reply tests/integration/test_peak_memory_usage/test.py]: The code looks complex, let's simply use `send_logs_level=trace` from the client and grep it

File: tests/integration/test_peak_memory_usage/test.py [hunk 7]
```diff
@@ -64,23 +64,31 @@ def started_cluster():
...
-        if not peek_memory_usage_str_found:
-            # Can be both Peak/peak
-            peek_memory_usage_str_found = "eak memory usage" in line
+    client_memory_value = None
+    server_memory_value = None
+    peak_memory_usage_found = False
 
-        if peek_memory_usage_str_found:
+    for line in client_output:
+        # Peak memory usage should be on shard_2
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py]: Is it the case for `test_clickhouse_client_max_peak_memory_single_node` ?

File: tests/integration/test_peak_memory_usage/test.py [hunk 8]
```diff
@@ -91,14 +99,19 @@ def test_clickhouse_client_max_peak_memory_usage_distributed(started_cluster):
...
         client1.expect("Peak memory usage", timeout=60)
         client1.expect(prompt)
 
-    peak_memory_usage = get_memory_usage_from_client_output_and_close(client_output)
-    assert peak_memory_usage
-    assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
+    client_memory_value, server_memory_value = get_memory_usage_from_client_output_and_close(client_output)
+    
+    assert client_memory_value is not None, "Client peak memory usage not found"
+    assert server_memory_value is not None, "Server peak memory usage not found"
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py]: Better to move those checks into the `get_memory_usage_from_client_output_and_close`

File: tests/integration/test_peak_memory_usage/test.py (hunk 7 above)
Comment (alexbakharew) [reply tests/integration/test_peak_memory_usage/test.py]: No, have reverted

**Review by azat — APPROVED** [review]
