### PR TITLE
Some fixes for ReplicatedMergeTree

### LINKED ISSUE #36610: Uncaught exception in ActiveDataPartSet::add
https://s3.amazonaws.com/clickhouse-test-reports/36579/bff54af46eecc9b33bcc1aeceda32876057f2ce1/stateless_tests__ubsan__actions_.html

```
2022.04.25 02:01:53.825389 [ 388 ] {} <Trace> BaseDaemon: Received signal -1
2022.04.25 02:01:53.825461 [ 388 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: ACED567A0CAB7BCA) (from thread 598) Terminate called for uncaught exception:
2022.04.25 02:01:53.825491 [ 388 ] {} <Fatal> BaseDaemon: Code: 49. DB::Exception: Part 4_4_83_1 intersects next part 4_54_54_1. It is a bug or a result of manual intervention in the ZooKeeper data. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
2022.04.25 02:01:53.825515 [ 388 ] {} <Fatal> BaseDaemon: 
2022.04.25 02:01:53.825533 [ 388 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x26685052 in /usr/bin/clickhouse
2022.04.25 02:01:53.825553 [ 388 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Common/Exception.cpp:58: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xfd144cf in /usr/bin/clickhouse
2022.04.25 02:01:53.825575 [ 388 ] {} <Fatal> BaseDaemon: 2. ./build_docker/../contrib/libcxx/include/string:1445: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x145736f7 in /usr/bin/clickhouse
2022.04.25 02:01:53.825605 [ 388 ] {} <Fatal> BaseDaemon: 3. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) @ 0x240e141d in /usr/bin/clickhouse
2022.04.25 02:01:53.825634 [ 388 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::insertUnlocked(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> const&, std::__1::optional<long>&, std::__1::lock_guard<std::__1::mutex>&) @ 0x244852c2 in /usr/bin/clickhouse
2022.04.25 02:01:53.825653 [ 388 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../contrib/libcxx/include/string:1445: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x2448e437 in /usr/bin/clickhouse
2022.04.25 02:01:53.825681 [ 388 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../contrib/libcxx/include/__functional/function.h:813: DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x23e71979 in /usr/bin/clickhouse
2022.04.25 02:01:53.825701 [ 388 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Stopwatch.h:49: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x225133e0 in /usr/bin/clickhouse
2022.04.25 02:01:53.825718 [ 388 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../contrib/poco/Foundation/include/Poco/AutoPtr.h:90: DB::BackgroundSchedulePool::threadFunction() @ 0x225151fe in /usr/bin/clickhouse
2022.04.25 02:01:53.825742 [ 388 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) @ 0x22515c7f in /usr/bin/clickhouse
2022.04.25 02:01:53.825770 [ 388 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/libcxx/include/__functional/function.h:1157: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xfde887a in /usr/bin/clickhouse
2022.04.25 02:01:53.825797 [ 388 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0
2022.04.25 02:01:53.825819 [ 388 ] {} <Trace> BaseDaemon: Received signal 6
2022.04.25 02:01:53.825955 [ 215703 ] {} <Fatal> BaseDaemon: ########################################
2022.04.25 02:01:53.825979 [ 215703 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: ACED567A0CAB7BCA) (from thread 598) (no query) Received signal Aborted (6)
2022.04.25 02:01:53.825996 [ 215703 ] {} <Fatal> BaseDaemon: 
2022.04.25 02:01:53.826041 [ 215703 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f924351803b 0x7f92434f7859 0x221fc733 0x279b58c8 0x279b5835 0x2448fd97 0x23e71979 0x225133e0 0x225151fe 0x22515c7f 0xfde887a 0xfdeb342 0x7f92436cf609 0x7f92435f4163
2022.04.25 02:01:53.826081 [ 215703 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f924351803b in ?
2022.04.25 02:01:53.826107 [ 215703 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f92434f7859 in ?
2022.04.25 02:01:53.849168 [ 215703 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../base/daemon/BaseDaemon.cpp:443: terminate_handler() @ 0x221fc733 in /usr/bin/clickhouse
2022.04.25 02:01:53.856352 [ 215703 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../contrib/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x279b58c8 in /usr/bin/clickhouse
2022.04.25 02:01:53.864493 [ 215703 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../contrib/libcxxabi/src/cxa_handlers.cpp:0: std::terminate() @ 0x279b5835 in /usr/bin/clickhouse
2022.04.25 02:01:53.955431 [ 215703 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:712: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x2448fd97 in /usr/bin/clickhouse
2022.04.25 02:01:54.168000 [ 215703 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:813: ~__policy_func
2022.04.25 02:01:54.168025 [ 215703 ] {} <Fatal> BaseDaemon: 9.2. inlined from ../contrib/libcxx/include/__functional/function.h:1171: ~function
2022.04.25 02:01:54.168039 [ 215703 ] {} <Fatal> BaseDaemon: 9. ../src/Storages/StorageReplicatedMergeTree.cpp:2907: DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x23e71979 in /usr/bin/clickhouse
2022.04.25 02:01:54.181266 [ 215703 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../src/Common/Stopwatch.h:49: Stopwatch::elapsedNanoseconds() const
2022.04.25 02:01:54.181298 [ 215703 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../src/Common/Stopwatch.h:51: Stopwatch::elapsedMilliseconds() const
2022.04.25 02:01:54.181317 [ 215703 ] {} <Fatal> BaseDaemon: 10. ../src/Core/BackgroundSchedulePool.cpp:106: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x225133e0 in /usr/bin/clickhouse
2022.04.25 02:01:54.195768 [ 215703 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/AutoPtr.h:90: ~AutoPtr
2022.04.25 02:01:54.195795 [ 215703 ] {} <Fatal> BaseDaemon: 11. ../src/Core/BackgroundSchedulePool.cpp:260: DB::BackgroundSchedulePool::threadFunction() @ 0x225151fe in /usr/bin/clickhouse
2022.04.25 02:01:54.210701 [ 215703 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: operator()
2022.04.25 02:01:54.210734 [ 215703 ] {} <Fatal> BaseDaemon: 12. ../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) @ 0x22515c7f in /usr/bin/clickhouse
2022.04.25 02:01:54.226362 [ 215703 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:1157: std::__1::function<void ()>::operator=(std::nullptr_t)
2022.04.25 02:01:54.226413 [ 215703 ] {} <Fatal> BaseDaemon: 13. ../src/Common/ThreadPool.cpp:284: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xfde887a in /usr/bin/clickhouse
2022.04.25 02:01:54.246083 [ 215703 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xfdeb342 in /usr/bin/clickhouse
2022.04.25 02:01:54.246136 [ 215703 ] {} <Fatal> BaseDaemon: 15. ? @ 0x7f92436cf609 in ?
2022.04.25 02:01:54.246162 [ 215703 ] {} <Fatal> BaseDaemon: 16. __clone @ 0x7f92435f4163 in ?
2022.04.25 02:01:54.591891 [ 215703 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7833E7805745E43565B3841080D21010. There is no information about the reference checksum.
```

### LINKED ISSUE #42120: Logical error: Part is already written by concurrent request
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/42066/fe90919f1083ff94e14c054f5a13991c66c92880/stress_test__ubsan_.html

```
2022.10.05 00:47:17.032381 [ 7099 ] {96887a4b-1ad8-4ecd-a896-09c0b484e1c8} <Fatal> : Logical error: 'Part with name -5_0_0_0 is already written by concurrent request. It should not happen for non-duplicate data parts because unique names are assigned for them. It's a bug'.
2022.10.05 00:48:14.402913 [ 50083 ] {} <Fatal> BaseDaemon: ########################################
2022.10.05 00:48:14.402984 [ 50083 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: A5CC905F77A70E42A002E7AC430369DE3673E94A) (from thread 7099) (query_id: 96887a4b-1ad8-4ecd-a896-09c0b484e1c8) (query: INSERT INTO concurrent_optimize_table SELECT rand(1), rand(2), 1 / rand(3), toString(rand(4)), [rand(5), rand(6)], rand(7) % 2 ? NULL : generateUUIDv4(), (rand(8), rand(9)) FROM numbers(10000)) Received signal Aborted (6)
2022.10.05 00:48:14.425578 [ 50083 ] {} <Fatal> BaseDaemon: 
2022.10.05 00:48:14.425676 [ 50083 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fcf5c6c500b 0x7fcf5c6a4859 0x1f8a78a3 0x1f8a7b4f 0x17c844f9 0x2c327750 0x2c320f3f 0x2c31fbbf 0x2cb1e271 0x2c9ef853 0x2c9ef4d2 0x2c9ee508 0x2c61a454 0x2c60a4db 0x2c609d16 0x2c609aca 0x2c608f54 0x1f9809d3 0x1f9847a4 0x7fcf5c87c609 0x7fcf5c7a1133
2022.10.05 00:48:14.427550 [ 50083 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7fcf5c6c500b in ?
2022.10.05 00:48:14.433409 [ 50083 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7fcf5c6a4859 in ?
2022.10.05 00:48:14.497946 [ 50083 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:47: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1f8a78a3 in /usr/bin/clickhouse
2022.10.05 00:48:14.534059 [ 50083 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1f8a7b4f in /usr/bin/clickhouse
2022.10.05 00:48:16.211853 [ 50083 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x17c844f9 in /usr/bin/clickhouse
2022.10.05 00:48:16.361565 [ 50083 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:511: DB::ReplicatedMergeTreeSink::commitPart(std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, unsigned long) @ 0x2c327750 in /usr/bin/clickhouse
2022.10.05 00:48:16.405698 [ 50083 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:270: DB::ReplicatedMergeTreeSink::finishDelayedChunk(std::__1::shared_ptr<zkutil::ZooKeeper>&) @ 0x2c320f3f in /usr/bin/clickhouse
2022.10.05 00:48:16.450121 [ 50083 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/compressed_pair.h:48: __compressed_pair_elem<std::nullptr_t, void>
2022.10.05 00:48:16.451439 [ 50083 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../contrib/libcxx/include/__memory/compressed_pair.h:130: __compressed_pair<std::nullptr_t, std::__1::__default_init_tag>
2022.10.05 00:48:16.454206 [ 50083 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/../contrib/libcxx/include/vector:652: vector
2022.10.05 00:48:16.454256 [ 50083 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:231: DB::ReplicatedMergeTreeSink::consume(DB::Chunk) @ 0x2c31fbbf in /usr/bin/clickhouse
2022.10.05 00:48:16.469174 [ 50083 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/../src/Processors/Chunk.h:32: ~Chunk
2022.10.05 00:48:16.469225 [ 50083 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Processors/Sinks/SinkToStorage.cpp:18: DB::SinkToStorage::onConsume(DB::Chunk) @ 0x2cb1e271 in /usr/bin/clickhouse
2022.10.05 00:48:16.496644 [ 50083 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/Processors/Chunk.h:32: ~Chunk
2022.10.05 00:48:16.499248 [ 50083 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:151: operator()
2022.10.05 00:48:16.499298 [ 50083 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::ExceptionKeepingTransform::work()::$_1&>(fp)()) std::__1::__invoke<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&)
2022.10.05 00:48:16.500414 [ 50083 ] {} <Fatal> BaseDaemon: 12.4. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&)
2022.10.05 00:48:16.500454 [ 50083 ] {} <Fatal> BaseDaemon: 12.5. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>::operator()()
2022.10.05 00:48:16.502101 [ 50083 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()> >(std::__1::__function::__policy_storage const*) @ 0x2c9ef853 in /usr/bin/clickhouse
2022.10.05 00:48:16.528925 [ 50083 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x2c9ef4d2 in /usr/bin/clickhouse
2022.10.05 00:48:16.549287 [ 50083 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:0: DB::ExceptionKeepingTransform::work() @ 0x2c9ee508 in /usr/bin/clickhouse
2022.10.05 00:48:16.561338 [ 50083 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2022.10.05 00:48:16.561409 [ 50083 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2c61a454 in /usr/bin/clickhouse
2022.10.05 00:48:16.592468 [ 50083 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2c60a4db in /usr/bin/clickhouse
2022.10.05 00:48:16.626827 [ 50083 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2c609d16 in /usr/bin/clickhouse
2022.10.05 00:48:16.665044 [ 50083 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:284: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::operator->() const
2022.10.05 00:48:16.666247 [ 50083 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:92: DB::PipelineExecutor::execute(unsigned long) @ 0x2c609aca in /usr/bin/clickhouse
2022.10.05 00:48:16.681484 [ 50083 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:0: DB::threadFunction(DB::CompletedPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)
2022.10.05 00:48:16.681563 [ 50083 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build_docker/../src/Processors/Executors/CompletedPipelineExecutor.cpp:79: operator()
2022.10.05 00:48:16.681611 [ 50083 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3648: decltype(static_cast<DB::CompletedPipelineExecutor::execute()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::CompletedPipelineExecutor::execute()::$_0&>(DB::CompletedPipelineExecutor::execute()::$_0&)
2022.10.05 00:48:16.684057 [ 50083 ] {} <Fatal> BaseDaemon: 19.4. inlined from ./build_docker/../contrib/libcxx/include/tuple:1595: decltype(auto) std::__1::__apply_tuple_impl<DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&>(DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
2022.10.05 00:48:16.685205 [ 50083 ] {} <Fatal> BaseDaemon: 19.5. inlined from ./build_docker/../contrib/libcxx/include/tuple:1604: decltype(auto) std::__1::apply<DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&>(DB::CompletedPipelineExecutor::execute()::$_0&, std::__1::tuple<>&)
2022.10.05 00:48:16.685270 [ 50083 ] {} <Fatal> BaseDaemon: 19.6. inlined from ./build_docker/../src/Common/ThreadPool.h:193: operator()
2022.10.05 00:48:16.685337 [ 50083 ] {} <Fatal> BaseDaemon: 19.7. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::CompletedPipelineExecutor::execute()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&>(DB::CompletedPipelineExecutor::execute()::$_0&&)
2022.10.05 00:48:16.688094 [ 50083 ] {} <Fatal> BaseDaemon: 19.8. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'()&)
2022.10.05 00:48:16.688166 [ 50083 ] {} <Fatal> BaseDaemon: 19.9. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>::operator()()
2022.10.05 00:48:16.691287 [ 50083 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x2c608f54 in /usr/bin/clickhouse
2022.10.05 00:48:16.713144 [ 50083 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
2022.10.05 00:48:16.713202 [ 50083 ] {} <Fatal> BaseDaemon: 20.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
2022.10.05 00:48:16.713258 [ 50083 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x1f9809d3 in /usr/bin/clickhouse
2022.10.05 00:48:16.740449 [ 50083 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x1f9847a4 in /usr/bin/clickhouse
2022.10.05 00:48:16.742584 [ 50083 ] {} <Fatal> BaseDaemon: 22. ? @ 0x7fcf5c87c609 in ?
2022.10.05 00:48:16.745610 [ 50083 ] {} <Fatal> BaseDaemon: 23. clone @ 0x7fcf5c7a1133 in 
```

Maybe related #28848.

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

- Removed "abandonable_lock", now block number allocation takes 1 RTT
- Fixed race condition between INSERT and ALTER PARTITION that might lead to intersecting parts, fixes https://github.com/ClickHouse/ClickHouse/issues/36610
- Fixed race condition between INSERT and DROP, fixes https://github.com/ClickHouse/ClickHouse/issues/42120
- Fixed incorrect check for `is_active` node in quorum inserts (see https://github.com/ClickHouse/ClickHouse/pull/42541#issuecomment-1297273046)

### CODE REVIEW

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -6380,6 +6399,76 @@ void StorageReplicatedMergeTree::removePartsFromZooKeeper(
...
+            LOG_WARNING(log, "Some query is trying to concurrently insert block {}, will cancel it", paths_to_get[i]);
+            zookeeper.tryRemove(paths_to_get[i]);
+        }
+        else
+        {
+            constexpr const char * old_version_warning = "Ephemeral lock {} (referencing {}) is created by a replica "
+                "that running old version of ClickHouse (< 22.11). Cannot remove it, will wait for this lock to disappear. "
+                "Upgrade remaining hosts in the cluster to address this warning.";
+            constexpr const char * new_version_warning = "Ephemeral lock {} has unexpected content ({}), "
+                "probably it is created by a replica that running newer version of ClickHouse. "
```
Comment (hanfei1991) [inline src/Storages/StorageReplicatedMergeTree.cpp:6454]: I can understand the remaining old version locks. But in which case will a new version clickhouse write unexpected content?

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 2]
```diff
@@ -6389,21 +6478,18 @@ void StorageReplicatedMergeTree::getClearBlocksInPartitionOps(
...
+    auto results = zookeeper.tryGet(paths_to_get);
+
+    for (size_t i = 0; i < paths_to_get.size(); ++i)
     {
-        const String & path = pair.first;
-        auto result = pair.second.get();
+        const String & path = paths_to_get[i];
+        auto & result = results[i];
 
         if (result.error == Coordination::Error::ZNONODE)
```
Comment (hanfei1991) [inline src/Storages/StorageReplicatedMergeTree.cpp:6494]: It seems when it's NONODE we will throw an exception in line 6492 because we use `tryGet`.

Comment (tavplubix) [reply src/Storages/StorageReplicatedMergeTree.cpp:6494]: No, `try*` methods do not throw on `ZNONODE`

Comment (hanfei1991) [reply src/Storages/StorageReplicatedMergeTree.cpp:6494]: you are right :)

File: src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp [hunk 3]
```diff
@@ -464,7 +469,7 @@ void ReplicatedMergeTreeSink::commitPart(
                     else
                         quorum_path = storage.zookeeper_path + "/quorum/status";
 
-                    waitForQuorum(zookeeper, existing_part_name, quorum_path, quorum_info.is_active_node_value, replicas_num);
+                    waitForQuorum(zookeeper, existing_part_name, quorum_path, quorum_info.is_active_node_version, replicas_num);
```
Comment (hanfei1991) [inline src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:472]: Why do we do this change? Is `is_active_node_value` still used?

Comment (tavplubix) [reply src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp:472]: > Why do we do this change?

See https://github.com/ClickHouse/ClickHouse/pull/42541#issuecomment-1297273046

> Is is_active_node_value still used?

No, will remove it

**Review by hanfei1991 — APPROVED** [review]

**Comment by tavplubix** [comment]
Builds - https://github.com/ClickHouse/ClickHouse/issues/43084
Integration tests (tsan) [1/4] - https://github.com/ClickHouse/ClickHouse/issues/42734
Stateless tests flaky check (asan) - 01158_zookeeper_log_long flakyness fixed in https://github.com/ClickHouse/ClickHouse/pull/42607
Stress test (msan) - clearOldPartsFromFilesystem on shutdown
Stress test (ubsan) - https://github.com/ClickHouse/ClickHouse/issues/41218

**Comment by azat** [comment]
@tavplubix can you please comment on what was the motivation to remove that 2-RTT lock from `EphemeralLockInZooKeeper`?

The reason I'm asking is that even after #43675 traffic and number of `List` requests to ZooKeeper is 4x higher then without this patch, and the setup is pretty simple, only 50 partitions, 10-20 tables, and not that match of INSERTs.

**Comment by tavplubix** [comment]
> @tavplubix can you please comment on what was the motivation to remove that 2-RTT lock from EphemeralLockInZooKeeper?

The motivation was that it was 2RTT :) 
Well, actually, there was another reason to remove it: I wanted to write some useful metadata (instead of an abandonable lock path) into block number nodes (see  `clearLockedBlockNumbersInPartition` for details). 

> The reason I'm asking is that even after https://github.com/ClickHouse/ClickHouse/pull/43675 traffic and number of List requests to ZooKeeper is 4x higher then without this patch, and the setup is pretty simple, only 50 partitions, 10-20 tables, and not that match of INSERTs.

We need more smart scheduling of background tasks in `ReplicatedMergeTree` tables. It does not make sense to run a merge selecting task each `merge_selecting_sleep_ms` (5000 by default) when the table is rarely updated and no data is inserted.

**Comment by NickStepanov** [comment]
@tavplubix is there any chance to roll this back?

This change brought our Zookeeper cluster to its knees and the amount of requests has gone up so dramatically that the replication queue went out of control and halted the entire cluster for a good part of two days before we figured out what caused it
Screenshot 2023-02-26 at 17 10 58

This all happened after upgrading to 22.12 and then we tried rolling back to 22.8, which didn't help to revert the situation, by the way. We had do use the solution described here: https://github.com/ClickHouse/ClickHouse/issues/43647#issuecomment-1327377459

Changes like these should be tested more carefully not to affect users in such a dramatic way.

**Comment by tavplubix** [comment]
How many replicated tables and how many partitions in total do you have? Is it correct that you have a lot of replicated tables with very rare inserts? Then you probably faced another issue: https://github.com/ClickHouse/ClickHouse/issues/31919. Yes, this PR made it worse, but the root cause of the issue is different. We have to fix the background tasks scheduling and do not run these tasks too frequently for unchanged tables. As a temporary workaround, you can tune `merge_selecting_sleep_ms` and `cleanup_delay_period` settings.

> @tavplubix is there any chance to roll this back?

@NickStepanov, feel free to send a pull request that rolls this back. However, you have to provide an alternative fix for [this](https://github.com/ClickHouse/ClickHouse/blob/1c6a6172079bcc113a52b96e724f1aa8ec4cc8c8/src/Storages/StorageReplicatedMergeTree.cpp#L6405-L6412) issue first if you want to roll this back.

> Changes like these should be tested more carefully not to affect users in such a dramatic way.

I agree that there's still a big room for improvements in our CI system, but it's hard to test all marginal usecases. Also, we highly recommend users to have a staging cluster with a workload similar to what they have on production. Checking everything on staging before rolling it out to production guarantees that your production will not be suddenly brought to its knees in a dramatic way.

**Comment by NickStepanov** [comment]
Thanks for coming back @tavplubix 

I am pretty confident that the issue we're facing is the one described here: https://github.com/ClickHouse/ClickHouse/issues/43647#issuecomment-1327377459

And the workaround:

> Manually remove /table_path_in_zk/temp/abandonable_lock-insert and /table_path_in_zk/temp/abandonable_lock-other nodes from ZooKeeper for each table.

Did help us.

The number of tables we have is around 500, with 500k+ parts in total (if I calculate correctly). The inserts are definitely not rare, I would say the insert rate is actually pretty high.

Unfortunately, I am not much of a developer, so a PR to roll it back or to provide an alertnative fix is not something I can offer.

**Comment by den-crane** [comment]
@NickStepanov 

>500k+ parts

share

```
select count(), uniqExact(partition_id) p 
from system.parts where active 
group by database, table order by p desc limit 10;
```

**Comment by NickStepanov** [comment]
@den-crane alright, this is what we have:

        count()	p
0	18912	18912
1	3658	2604
2	4113	2587
3	3290	2570
4	3936	2570
5	3840	2568
6	2565	2565
7	2906	1914
8	1897	1897
9	1330	1195

**Comment by tavplubix** [comment]
> I am pretty confident that the issue we're facing is the one described here: https://github.com/ClickHouse/ClickHouse/issues/43647#issuecomment-1327377459

That comment was about a high number of empty partitions that were dropped or cleaned up by TTL. It was fixed in https://github.com/ClickHouse/ClickHouse/pull/43675. 

However, it's not the only case that can lead to zk overload. Before this PR, merge selecting tasks worked like this:
1. Check if the table has any INSERT queries in progress (1 zk request)
2. If there are some INSERTs - load block numbers for all partitions (N zk requests, where N is the number of partitions)

And now it always loads block numbers for all partitions. Actually, it does not change the number of zk requests if you always have some INSERT queries running. But if you have a table with many partitions and insert into that table not so often, then the merge selecting task will constantly try to load all block numbers. But the problem is that we don't need to run the merge selecting task at all if no new parts were inserted, and that's what https://github.com/ClickHouse/ClickHouse/issues/31919 is about. 

> 0	18912	18912

It means that you have a table with almost 19k partitions and 19k parts, so it makes 19k zk requests each `merge_selecting_sleep_ms` (5 seconds, so it's almost 4k rps). The number of parts equals the number of partitions, so all parts are merged, so I can assume that inserts are quite rare in that table (otherwise we would see unmerged parts in some partitions). It makes sense to increase `merge_selecting_sleep_ms` for that table.

In addition to implementing smarter merge selecting task scheduling, we can avoid loading block numbers for "small" partitions having only a few parts and prefer partitions with a lot of parts when selecting a merge.

**Comment by tavplubix** [comment]
Or we can simply return the check for running inserts back. Seems like it's possible to do without 2RTT on insert and without breaking backward compatibility, I will check.

**Comment by NickStepanov** [comment]
@tavplubix ok, I am starting to get a bit more confused :) 

1. What has definitely helped in our case, was removing the files like `/table_path_in_zk/temp/abandonable_lock-insert` and `/table_path_in_zk/temp/abandonable_lock-other` for all of our tables. At the exact second we removed them, the entire Zookeeper and Clickhouse cluster came back to life. Therefore, a process related to these files is the one that caused trouble for us.
2. The tables we have, they have a good amount of inserts, definitely not something I would call rare.

**Comment by tavplubix** [comment]
> What has definitely helped in our case, was removing the files like /table_path_in_zk/temp/abandonable_lock-insert and /table_path_in_zk/temp/abandonable_lock-other

It's because these "files" make the merge selecting task on old versions ignore the first step and always load all block numbers

**Comment by NickStepanov** [comment]
Ok, I see, so if the return of the check for running inserts (step 1) can be reintroduced, that's going to solve this?

**Comment by tavplubix** [comment]
> so if the return of the check for running inserts (step 1) can be reintroduced, that's going to solve this?

Yep. But other improvements (like smarter scheduling) still make sense.

**Comment by den-crane** [comment]
@NickStepanov Also try

```
   <merge_tree>
        <cleanup_delay_period>300</cleanup_delay_period>
        <merge_selecting_sleep_ms>600000</merge_selecting_sleep_ms>
   </merge_tree>
```

We (Altinity) tested it with clients who have issues with ZK load, no harm from it. 
It will reduce CPU usage of CH and Zookeeper in your system with any version of Clickhouse. 
Because now merge_selector analyzes all your parts/partitions every 5 seconds.

**Comment by hjun881** [comment]
@den-crane Thank you very much. Based on your settings, the problem has been resolved. Can you explain the specific principle in detail and why changing this parameter can solve the problem
```xml
   <merge_tree>
        <cleanup_delay_period>300</cleanup_delay_period>
        <merge_selecting_sleep_ms>600000</merge_selecting_sleep_ms>
   </merge_tree>
```

**Comment by tavplubix** [comment]
> > > so if the return of the check for running inserts (step 1) can be reintroduced, that's going to solve this?
> > 
> > 
> > Yep. But other improvements (like smarter scheduling) still make sense.
> 
> @tavplubix is there a plan to bring it back in newer versions?

@NickStepanov, there's no plan to bring it back because it appeared to be much more complex than I thought. But there are two PRs that should significantly reduce the number of ZooKeeper requests in use cases like yours: https://github.com/ClickHouse/ClickHouse/pull/49637 and https://github.com/ClickHouse/ClickHouse/pull/50107.

**Comment by ozcanyarimdunya** [comment]
> @NickStepanov Also try
> 
> ```
>    <merge_tree>
>         <cleanup_delay_period>300</cleanup_delay_period>
>         <merge_selecting_sleep_ms>600000</merge_selecting_sleep_ms>
>    </merge_tree>
> ```
> 
> We (Altinity) tested it with clients who have issues with ZK load, no harm from it. It will reduce CPU usage of CH and Zookeeper in your system with any version of Clickhouse. Because now merge_selector analyzes all your parts/partitions every 5 seconds.

We got the same issue, based on these settings, the problem has been resolved.
Thanks!
