### PR TITLE
Fix index analysis with session_timezone specified

### LINKED ISSUE #86654: Partition pruning does not consider session timezone correctly for datetime-based partition keys
### Company or project name

_No response_

### Describe what's wrong

Partition pruning does not consider session timezone correctly when using toStartOfDay() (or any other epoch) function as partition key. 
This affects all the multi-timezone applications that use DateTime column based functions as partition key, and break validness of the query output. 

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Problem is reproduceable on the latest version. Was last working on this 24.3-LTS, broken on 24.8-LTS and above (didn't check interim non-LTS versions). 

[fiddle.clickhouse.com/9b578911-b237-4381-8c76-1164f9a4bd65](https://fiddle.clickhouse.com/15b88a1d-f04c-4d89-a2b0-9f3b539f31ad)

```
select '--- CH version';
select version();
select '--- setting TZ to America/New_York';
set session_timezone='America/New_York';

DROP TABLE IF EXISTS default.testpartitiondat_toStartOfDay;
CREATE TABLE default.testpartitiondat_toStartOfDay(
    dtkey DateTime,
    a UInt32,
    b UInt32
)
ENGINE = MergeTree
PARTITION BY (toStartOfDay(dtkey))
ORDER BY tuple()
SETTINGS index_granularity = 8192;
 

-- load data in US tz session setting WITHOUT tz info
select '--- load data in US tz session setting WITHOUT tz info';
insert into default.testpartitiondat_toStartOfDay VALUES (toDateTime('2025-09-03 02:58:00'), 1, 1);

--- query with datetime explicitly in US TZ
select '--- query with datetime explicitly in US TZ - works';
select dtkey, _partition_value from default.testpartitiondat_toStartOfDay 
where dtkey>=toDateTime('2025-09-03 00:00:00', 'America/New_York')
and dtkey<toDateTime('2025-09-03 05:00:00', 'America/New_York');

-- query without explicit TZ, relying on session tz - works
select '-- query without explicit TZ, relying on session tz - works';
select dtkey, _partition_value from default.testpartitiondat_toStartOfDay 
where dtkey>=toDateTime('2025-09-03 00:00:00')
and dtkey<toDateTime('2025-09-03 05:00:00');

-- change session tz
select '-- change session tz';
set session_timezone='Europe/Bucharest';

--- query with datetime explicitly in US TZ -- fails!!!
select '--- query with datetime explicitly in US TZ -- fails!!!';
select dtkey, _partition_value from default.testpartitiondat_toStartOfDay 
where dtkey>=toDateTime('2025-09-03 00:00:00', 'America/New_York')
and dtkey<toDateTime('2025-09-03 05:00:00', 'America/New_York');

-- explain plan shows that it's trying to apply pruning in server TZ, instead of using session TZ (PK works correctly)
select '-- explain plan shows that its trying to apply pruning in server TZ, instead of using session TZ (PK works correctly)';

explain indexes=1, actions=0  select dtkey, _partition_value from default.testpartitiondat_toStartOfDay 
where dtkey>=toDateTime('2025-09-03 00:00:00', 'America/New_York')
and dtkey<toDateTime('2025-09-03 05:00:00', 'America/New_York');

```

Explain plan shows the problem clearly (condition of index is correct, but is incorrect for partition key). Wrapping dtkey in identity() function make it work. 
```
Expression ((Project names + Projection))
  Expression ((WHERE + Change column names to column identifiers))
    ReadFromMergeTree (default.testpartitiondat_toStartOfDay)
    Indexes:
      MinMax
        Keys:
          dtkey
        Condition: and((dtkey in (-Inf, 1756889999]), (dtkey in [1756872000, +Inf)))
        Parts: 1/1
        Granules: 1/1
      Partition
        Keys:
          toStartOfDay(dtkey)
        Condition: and((toStartOfDay(dtkey) in (-Inf, 1756846800]), (toStartOfDay(dtkey) in [1756846800, +Inf)))
        Parts: 0/1
        Granules: 0/1
        Ranges: 0

```

### Expected behavior

changing session timezone shall have no impact on partition pruning and query output (except for time to string conversions). 

### Error message and/or stacktrace

_No response_

### Additional context

It would be good to know if there is any way or parameter setting that can work it around (without recreating table DDLs). 

Touching table DDL and when writing happens from single timezone there are several workarounds such as:
- using PARTITION BY toYYYYMMDD string functions (they come with their own problems when working in multi-tz datacenter/clusters though, and may still have issues)
- using PARTITION BY (toStartOfDay(toTimezone(dtkey, 'America/New_York'))) - using timezone of writing session makes it work for all sessions

### PR DESCRIPTION
**Pull request by korowa**
Closes #86654 

- The main issue was caused by rebuilding key functions chain using the query context (which inferred timezone into the functions)
- Disabling index analysis for indexes containing date parsing functions in case the query specifies non-empty session timezone, and parsing datetime from string is required, as this part is not working properly since at least 24.1 ([example](https://fiddle.clickhouse.com/86f8db88-5b14-48ea-9cd9-ba1f574e322b))

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix for incorrect granules/partitions elimination for datetime-based keys, when using `session_timezone` setting in queries

Fixes: https://github.com/ClickHouse/ClickHouse/pull/65335

### CODE REVIEW

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 1]
```diff
@@ -1909,12 +1910,23 @@ bool KeyCondition::extractMonotonicFunctionsChainFromKey(
...
-                            func_name = func_name + "OrNull";
-                    }
+                        // In case when session timezone is used while querying, skipping the analysis
+                        if (!context->getSettingsRef()[Setting::session_timezone].value.empty())
+                            return false;
 
-                    auto func_builder = FunctionFactory::instance().tryGet(func_name, context);
+                        const auto & func_arg_types = func_base->getArgumentTypes();
+
+                        // Otherwise, in case when datetime parsing is required, rebuilding function
```
Comment (azat) [inline src/Storages/MergeTree/KeyCondition.cpp]: Do we need to do this only to apply `OrNull`? Let's update the comment to make it clear

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 2]
```diff
@@ -1909,12 +1910,23 @@ bool KeyCondition::extractMonotonicFunctionsChainFromKey(
 
                     if (date_time_parsing_functions.contains(func_name))
                     {
-                        const auto & arg_types = func_base->getArgumentTypes();
-                        if (!arg_types.empty() && isStringOrFixedString(arg_types[0]))
-                            func_name = func_name + "OrNull";
-                    }
+                        // In case when session timezone is used while querying, skipping the analysis
+                        if (!context->getSettingsRef()[Setting::session_timezone].value.empty())
```
Comment (azat) [inline src/Storages/MergeTree/KeyCondition.cpp]: Because of this check some tests in `03173_set_transformed_partition_pruning.sql` will fail (note, that you will not see this in fasttest because it does not randomize `session_timezone`)

**Review by azat — COMMENTED** [review]
PTAL at the test failures, by some reason test with `xxHash32` failed

File: src/Storages/MergeTree/KeyCondition.cpp (hunk 2 above)
Comment (korowa) [reply src/Storages/MergeTree/KeyCondition.cpp]: Thank you, already noticed while running the failed test locally.

File: src/Storages/MergeTree/KeyCondition.cpp (hunk 1 above)
Comment (korowa) [reply src/Storages/MergeTree/KeyCondition.cpp]: Done.

**Comment by korowa** [comment]
> [Integration tests (amd_binary, 2/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87987&sha=latest&name_0=PR&name_1=Integration+tests+%28amd_binary%2C+2%2F5%29)

https://github.com/ClickHouse/ClickHouse/issues/87560

> [Integration tests (amd_tsan, 4/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87987&sha=latest&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+4%2F6%29)

https://github.com/ClickHouse/ClickHouse/issues/88328

> [Stateless tests (amd_tsan, parallel, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87987&sha=latest&name_0=PR&name_1=Stateless+tests+%28amd_tsan%2C+parallel%2C+2%2F2%29)

Unrelated, 00159_parallel_formatting_http has couple of [failures](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMzAgREFZCiAgICAtLUFORCAoc3RhcnRzV2l0aChoZWFkX3JlcG8sICdDbGlja0hvdXNlLycpKQogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EICh0ZXN0X3N0YXR1cyBMSUtFICdGJScgT1IgdGVzdF9zdGF0dXMgTElLRSAnRSUnKSAKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgcG9zaXRpb24odGVzdF9uYW1lLCAnMDAxNTlfcGFyYWxsZWxfZm9ybWF0dGluZ19odHRwJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=) on the TSAN builds related to curl timeouts, will check if the query can be less heavy.

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 3]
```diff
@@ -1122,13 +1123,14 @@ bool applyFunctionChainToColumn(
...
-        auto argument_type = getArgumentTypeOfMonotonicFunction(*func);
+        auto argument_type = removeLowCardinality(getArgumentTypeOfMonotonicFunction(*func));
         if (!canBeSafelyCast(result_type, argument_type))
             return false;
 
         result_column = castColumnAccurate({result_column, result_type, ""}, argument_type);
         result_column = func->execute({{result_column, argument_type, ""}}, func->getResultType(), result_column->size(), /* dry_run = */ false);
-        result_type = func->getResultType();
+        result_column = result_column->convertToFullIfNeeded();
+        result_type = removeLowCardinality(func->getResultType());
```
Comment (azat) [inline src/Storages/MergeTree/KeyCondition.cpp:1131]: This looks slightly better:

```patch
$ git di
diff --git a/src/Storages/MergeTree/KeyCondition.cpp b/src/Storages/MergeTree/KeyCondition.cpp
index 5b6c3487d9d..63ef2304212 100644
--- a/src/Storages/MergeTree/KeyCondition.cpp
+++ b/src/Storages/MergeTree/KeyCondition.cpp
@@ -1128,9 +1128,8 @@ bool applyFunctionChainToColumn(
             return false;

         result_column = castColumnAccurate({result_column, result_type, ""}, argument_type);
-        result_column = func->execute({{result_column, argument_type, ""}}, func->getResultType(), result_column->size(), /* dry_run = */ false);
-        result_column = result_column->convertToFullIfNeeded();
         result_type = removeLowCardinality(func->getResultType());
+        result_column = func->execute({{result_column, argument_type, ""}}, result_type, result_column->size(), /* dry_run = */ false);

         // Transforming nullable columns to the nested ones, in case no nulls found
         if (result_column->isNullable())
```

**Review by azat — APPROVED** [review]

File: src/Storages/MergeTree/KeyCondition.cpp (hunk 3 above)
Comment (korowa) [reply src/Storages/MergeTree/KeyCondition.cpp:1131]: True, applied.

**Comment by azat** [comment]
CI:
- https://github.com/ClickHouse/ClickHouse/issues/87900
- https://github.com/ClickHouse/ClickHouse/issues/88384

**Comment by azat** [comment]
CI:
- https://github.com/ClickHouse/ClickHouse/issues/88425
- https://github.com/ClickHouse/ClickHouse/issues/87560
