### PR TITLE
Fix UBSan report in Decimal parse

### LINKED ISSUE #7540: ubsan in fuzz test: signed integer overflow
```
../dbms/src/Core/Types.h:143:58: runtime error: signed integer overflow: -7174046 * 1000000 cannot be represented in type 'int'
    #0 0x1780c221 in DB::Decimal<int>::operator*=(int const&) /build/obj-x86_64-linux-gnu/../dbms/src/Core/Types.h:143:58
    #1 0x1780c221 in DB::DataTypeDecimal<DB::Decimal<int> >::tryReadText(DB::Decimal<int>&, DB::ReadBuffer&, unsigned int, unsigned int) /build/obj-x86_64-linux-gnu/../dbms/src/DataTypes/DataTypesDecimal.cpp:61
    #2 0x10a82f4b in void DB::ConvertThroughParsing<DB::DataTypeString, DB::DataTypeDecimal<DB::Decimal<int> >, DB::NameToDecimal32OrZero, (DB::ConvertFromStringExceptionMode)1, (DB::ConvertFromStringParsingMode)0>::execute<unsigned int>(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, unsigned int) (/usr/bin/clickhouse+0x10a82f4b)
    #3 0x175883b6 in DB::PreparedFunctionImpl::defaultImplementationForConstantArguments(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /build/obj-x86_64-linux-gnu/../dbms/src/Functions/IFunction.cpp:259:5
    #4 0x175890ed in DB::PreparedFunctionImpl::executeWithoutLowCardinalityColumns(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /build/obj-x86_64-linux-gnu/../dbms/src/Functions/IFunction.cpp:303:9
    #5 0x1758a133 in DB::PreparedFunctionImpl::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /build/obj-x86_64-linux-gnu/../dbms/src/Functions/IFunction.cpp:473:13
```

https://clickhouse-test-reports.s3.yandex.net/7500/15d12db16a2ac65af695aadcecc2c55b9a9c668a/functional_stateless_tests_(ubsan).html

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix UBSan report in Decimal parse. This fixes #7540.

### CODE REVIEW

File: src/DataTypes/DataTypesDecimal.cpp [hunk 1]
```diff
@@ -58,7 +58,7 @@ void DataTypeDecimal<T>::serializeText(const IColumn & column, size_t row_num, W
 }
 
 template <typename T>
-bool DataTypeDecimal<T>::tryReadText(T & x, ReadBuffer & istr, UInt32 precision, UInt32 scale)
+bool NO_SANITIZE_UNDEFINED DataTypeDecimal<T>::tryReadText(T & x, ReadBuffer & istr, UInt32 precision, UInt32 scale)
```
Comment (alesapin) [inline src/DataTypes/DataTypesDecimal.cpp:61]: Maybe it doesn't work for template classes?

Comment (alexey-milovidov) [reply src/DataTypes/DataTypesDecimal.cpp:61]: Maybe.

Also there is another way - to enable overflow check (and throw exception on overflow).
There are the following considerations:
- it will be cheap but not free;
- we need performance test for formats but it is disabled at this moment of time;
- maybe I can prepare another performance test for decimal parse;
- overflow check is better from user perspective but worth to note that it will have some false negatives - if the number exceeds maximum number of digits but still don't overflow inside integer data type.

**Comment by alexey-milovidov** [comment]
For some reason, performance test does not show the comparison.
