### PR TITLE
Catch exceptions on finalize in `InterserverIOHTTPHandler`

### LINKED ISSUE #58991: InterserverIOHTTPHandler: Cannot write to finalized buffer
Report: https://s3.amazonaws.com/clickhouse-test-reports/58942/cd4aefcddb9bb91d1f70f46e3ba7c8f0eb554779/stress_test__msan_.html

GDB logs:

```
2024-01-19 06:19:15 Thread 868 "IntersrvHandler" received signal SIGABRT, Aborted.
2024-01-19 06:19:15 [Switching to Thread 0x7f2d20793640 (LWP 4061)]
2024-01-19 06:19:15 0x00007f309edb29fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 06:19:15 #0  0x00007f309edb29fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 06:19:15 No symbol table info available.
2024-01-19 06:19:15 #1  0x00007f309ed5e476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 06:19:15 No symbol table info available.
2024-01-19 06:19:15 #2  0x00007f309ed447f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-01-19 06:19:15 No symbol table info available.
2024-01-19 06:19:15 #3  0x000056313096adea in DB::abortOnFailedAssertion (description=...) at ./build_docker/./src/Common/Exception.cpp:43
2024-01-19 06:19:15 No locals.
2024-01-19 06:19:15 #4  0x000056313096c524 in DB::handle_error_code (msg=..., code=49, trace=..., remote=<optimized out>) at ./build_docker/./src/Common/Exception.cpp:59
2024-01-19 06:19:15 No locals.
2024-01-19 06:19:15 #5  DB::Exception::Exception (this=0x714002586e80, msg_masked=..., code=49, remote_=<optimized out>) at ./build_docker/./src/Common/Exception.cpp:100
2024-01-19 06:19:15 No locals.
2024-01-19 06:19:15 #6  0x00005631187ab1cd in DB::Exception::Exception<>(int, FormatStringHelperImpl<>) ()
2024-01-19 06:19:15 No symbol table info available.
2024-01-19 06:19:15 #7  0x00005631187e4a78 in DB::WriteBuffer::write(char const*, unsigned long) ()
2024-01-19 06:19:16 No symbol table info available.
2024-01-19 06:19:16 #8  0x000056314c476004 in DB::writeString (data=0xfdd <error: Cannot access memory at address 0xfdd>, size=2851, buf=...) at ./src/IO/WriteHelpers.h:205
2024-01-19 06:19:16 No locals.
2024-01-19 06:19:16 #9  DB::writeString (ref=..., buf=...) at ./src/IO/WriteHelpers.h:216
2024-01-19 06:19:16 No locals.
2024-01-19 06:19:16 #10 DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&)::$_0::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (this=this@entry=0x7f2d2078b4b8, message=...) at ./build_docker/./src/Server/InterserverIOHTTPHandler.cpp:105
2024-01-19 06:19:18         out = @0x713000668d98: {<DB::HTTPWriteBuffer> = {<DB::WriteBufferFromPocoSocket> = {<DB::BufferWithOwnMemory<DB::WriteBuffer>> = {<DB::WriteBuffer> = {<DB::BufferBase> = {pos = 0x7f285bb84000 "\341\070p\234/\212R\244\344m\231\227n", bytes = 1554, working_buffer = {begin_pos = 0x7f285bb84000 "\341\070p\234/\212R\244\344m\231\227n", end_pos = 0x7f285bc84000 ""}, internal_buffer = {begin_pos = 0x7f285bb84000 "\341\070p\234/\212R\244\344m\231\227n", end_pos = 0x7f285bc84000 ""}, padded = true}, _vptr$WriteBuffer = 0x5631578dfb30 <vtable for DB::WriteBufferFromHTTPServerResponse+16>, finalized = true}, memory = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, <Allocator<false, false>> = {static clear_memory = 127}, static pad_right = 63, m_capacity = 1048639, m_size = 1048576, m_data = 0x7f285bb84000 "\341\070p\234/\212R\244\344m\231\227n", alignment = 0}}, socket = @0x7f2d2078b810, peer_address = {static IPv4 = Poco::Net::AddressFamily::IPv4, static IPv6 = Poco::Net::AddressFamily::IPv6, static UNIX_LOCAL = Poco::Net::AddressFamily::UNIX_LOCAL, _pImpl = {_ptr = 0x703002006100}}, our_address = {static IPv4 = Poco::Net::AddressFamily::IPv4, static IPv6 = Poco::Net::AddressFamily::IPv6, static UNIX_LOCAL = Poco::Net::AddressFamily::UNIX_LOCAL, _pImpl = {_ptr = 0x703000d63da0}}, write_event = {t = 518}, async_callback = {<std::__1::__function::__maybe_derive_from_unary_function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &, unsigned int)>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &, unsigned int)>> = {<No data fields>}, __f_ = {__buf_ = {__small = '\000' <repeats 15 times>, __large = 0x0}, __invoker_ = {__call_ = 0x563130f250a0 <std::__1::__function::__policy_invoker<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int)>::__call_empty(std::__1::__function::__policy_storage const*, int, Poco::Timespan&&, DB::AsyncEventTimeoutType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int)>}, __policy_ = 0x56315735bb90 <std::__1::__function::__policy::__create_empty[abi:v15000]()::__policy_>}}, socket_description = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x703001e5e200 "socket ([2001:db8:1::242:ac11:2]:40244)", __size_ = 39, __cap_ = 48, __is_long_ = 1}, __s = {__data_ = "\000\342\345\001\060p\000\000'\000\000\000\000\000\000\000\060\000\000\000\000\000", __padding_ = 0x713000668e4f "\200\001", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __r = {__words = {123351492583936, 39, 9223372036854775856}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}}, chunked = true, fixed_length = 0, count_length = 0}, response = @0x7f2d2078b6b8, is_http_method_head = false, add_cors_header = false, keep_alive_timeout = 10, initialized = true, headers_started_sending = true, headers_finished_sending = true, accumulated_progress = {read_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, read_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_rows_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_bytes_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, elapsed_ns = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 222654013}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}}, send_progress = false, send_progress_interval_ms = 100, progress_watch = {start_ns = 3058549369930, stop_ns = 0, clock_type = 4, is_running = true}, compression_method = DB::CompressionMethod::None, exception_code = 0, mutex = {__m_ = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}}
2024-01-19 06:19:18 #11 0x000056314c474e18 in DB::InterserverIOHTTPHandler::handleRequest (this=0x703000fd7940, request=..., response=..., write_event=...) at ./build_docker/./src/Server/InterserverIOHTTPHandler.cpp:144
2024-01-19 06:19:20         message = {text = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x71e001505400 "Code: 210. DB::NetException: Connection reset by peer, while writing to socket ([2001:db8:1::242:ac11:2]:9009 -> [2001:db8:1::242:ac11:2]:40244). (NETWORK_ERROR), Stack trace (when copying this messag"..., __size_ = 2851, __cap_ = 2864, __is_long_ = 1}, __s = {__data_ = "\000TP\001\340q\000\000#\v\000\000\000\000\000\000\060\v\000\000\000\000", __padding_ = 0x7f2d2078b5bf "\200\004.\a\022\061V", __size_ = 0 '\000', __is_long_ = 1 '\001'}, __r = {__words = {125206908654592, 2851, 9223372036854778672}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, format_string = {static npos = 18446744073709551615, __data = 0x563112072e04 "{}, while writing to socket ({} -> {})", __size = 38}}
2024-01-19 06:19:20         is_real_error = <optimized out>
2024-01-19 06:19:27         thread_status = {<boost::noncopyable_::noncopyable> = {<boost::noncopyable_::base_token> = {<No data fields>}, <No data fields>}, thread_id = 4061, os_thread_priority = 0, performance_counters = {counters = 0x721003b57400, counters_holder = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::atomic<unsigned long>*, 0, false>> = {__value_ = 0x721003b57400}, <std::__1::__compressed_pair_elem<std::__1::default_delete<std::__1::atomic<unsigned long> []>, 1, true>> = {<std::__1::default_delete<std::__1::atomic<unsigned long> []>> = {<No data fields>}, <No data fields>}, <No data fields>}}, parent = 0x5631597eb5b8 <ProfileEvents::global_counters>, trace_profile_events = false, level = VariableContext::Thread, static num_counters = {t = 525}}, current_performance_counters = 0x7f2d2078b1d0, memory_tracker = {amount = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, peak = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, soft_limit = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, hard_limit = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, profiler_limit = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, allow_use_jemalloc_memory = {<std::__1::__atomic_base<bool, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<bool>> = {__a_value = true}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, static free_memory_in_allocator_arenas = {<std::__1::__atomic_base<long, true>> = {<std::__1::__atomic_base<long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, profiler_step = 0, fault_probability = 0, sample_probability = -1, min_allocation_size_bytes = 0, max_allocation_size_bytes = 0, parent = {<std::__1::__atomic_base<MemoryTracker*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<MemoryTracker*>> = {__a_value = 0x5631597e9428 <total_memory_tracker>}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, metric = {<std::__1::__atomic_base<StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<StrongTypedef<unsigned long, CurrentMetrics::MetricTag> >> = {__a_value = {t = 252}}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, description_ptr = {<std::__1::__atomic_base<char const*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<char const*>> = {__a_value = 0x5631120515c3 "(for thread)"}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, max_wait_time = {<std::__1::__atomic_base<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> >, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >> = {__a_value = {__rep_ = 0}}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, overcommit_tracker = {<std::__1::__atomic_base<OvercommitTracker*, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<OvercommitTracker*>> = {__a_value = 0x0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, log_peak_memory_usage_in_destructor = true, static USAGE_EVENT_NAME = <optimized out>, static PEAK_USAGE_EVENT_NAME = <optimized out>, level = VariableContext::Thread}, untracked_memory = 1048639, untracked_memory_limit = 4194304, progress_in = {read_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, read_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_rows_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_bytes_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, elapsed_ns = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}}, progress_out = {read_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, read_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_rows_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, total_bytes_to_read = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, written_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_rows = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, result_bytes = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}, elapsed_ns = {<std::__1::__atomic_base<unsigned long, true>> = {<std::__1::__atomic_base<unsigned long, false>> = {__a_ = {<std::__1::__cxx_atomic_base_impl<unsigned long>> = {__a_value = 0}, <No data fields>}, static is_always_lock_free = <optimized out>}, <No data fields>}, <No data fields>}}, thread_group = {__ptr_ = 0x0, __cntrl_ = 0x0}, global_context = {__ptr_ = 0x0, __cntrl_ = 0x0}, query_context = {__ptr_ = 0x0, __cntrl_ = 0x0}, fatal_error_callback = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = '\000' <repeats 15 times>, __large = 0x0}, __invoker_ = {__call_ = 0x56312c8db5c0 <std::__1::__function::__policy_invoker<void ()>::__call_empty(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x56315735bb90 <std::__1::__function::__policy::__create_empty[abi:v15000]()::__policy_>}}, local_data = {profile_queue_ptr = {__ptr_ = 0x0, __cntrl_ = 0x0}, logs_queue_ptr = {__ptr_ = 0x0, __cntrl_ = 0x0}, client_logs_level = DB::LogsLevel::none, query_for_logs = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7f2d2078b3af "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, normalized_query_hash = 0, query_is_canceled_predicate = {<std::__1::__function::__maybe_derive_from_unary_function<bool ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<bool ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "H\264x -\177\000\000\000\000\000\000\000\000\000", __large = 0x7f2d2078b448}, __invoker_ = {__call_ = 0x5631308f9660 <std::__1::__function::__policy_invoker<bool ()>::__call_empty(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x56315735bb90 <std::__1::__function::__policy::__create_empty[abi:v15000]()::__policy_>}}}, performance_counters_finalized = false, query_id_from_query_context = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x0, __size_ = 0, __cap_ = 0, __is_long_ = 0}, __s = {__data_ = '\000' <repeats 22 times>, __padding_ = 0x7f2d2078b3f7 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {0, 0, 0}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, query_start_time = {point = {__d_ = {__rep_ = 0}}}, query_profiler_real = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::QueryProfilerReal*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::QueryProfilerReal>, 1, true>> = {<std::__1::default_delete<DB::QueryProfilerReal>> = {<No data fields>}, <No data fields>}, <No data fields>}}, query_profiler_cpu = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::QueryProfilerCPU*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::QueryProfilerCPU>, 1, true>> = {<std::__1::default_delete<DB::QueryProfilerCPU>> = {<No data fields>}, <No data fields>}, <No data fields>}}, last_rusage = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::RUsageCounters*, 0, false>> = {__value_ = 0x70300218ceb0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::RUsageCounters>, 1, true>> = {<std::__1::default_delete<DB::RUsageCounters>> = {<No data fields>}, <No data fields>}, <No data fields>}}, taskstats = {__ptr_ = {<std::__1::__compressed_pair_elem<DB::TasksStatsCounters*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::default_delete<DB::TasksStatsCounters>, 1, true>> = {<std::__1::default_delete<DB::TasksStatsCounters>> = {<No data fields>}, <No data fields>}, <No data fields>}}, stopwatch = {start_ns = 3059360345005, stop_ns = 0, clock_type = 6, is_running = true}, last_performance_counters_update_time = 0, internal_thread = false, deleter = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {__small = "@yL\000\260p\000\000\023\000\000\000-\177\000", __large = 0x70b0004c7940}, __invoker_ = {__call_ = 0x56312c8db5c0 <std::__1::__function::__policy_invoker<void ()>::__call_empty(std::__1::__function::__policy_storage const*)>}, __policy_ = 0x56315735bb90 <std::__1::__function::__policy::__create_empty[abi:v15000]()::__policy_>}}, log = 0x704000013d80, check_current_thread_on_destruction = true}
2024-01-19 06:19:27         write_response = {used_output = @0x7f2d2078b590, response = @0x7f2d2078b6b8, this = 0x703000fd7940}
2024-01-19 06:19:27         used_output = {out = {__ptr_ = 0x713000668d98, __cntrl_ = 0x713000668d80}}
2024-01-19 06:19:27         keep_alive_timeout = <optimized out>
2024-01-19 06:19:27         e = <optimized out>
2024-01-19 06:19:27 #12 0x000056314c5c94e5 in DB::HTTPServerConnection::run (this=<optimized out>) at ./build_docker/./src/Server/HTTP/HTTPServerConnection.cpp:70
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Should fix https://github.com/ClickHouse/ClickHouse/issues/58991

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Server/InterserverIOHTTPHandler.cpp [hunk 1]
```diff
@@ -117,7 +117,17 @@ void InterserverIOHTTPHandler::handleRequest(HTTPServerRequest & request, HTTPSe
         if (auto [message, success] = checkAuthentication(request); success)
         {
             processQuery(request, response, used_output);
-            used_output.out->finalize();
+
+            try
+            {
+                used_output.out->finalize();
```
Comment (CheSema) [inline src/Server/InterserverIOHTTPHandler.cpp:123]: I suppose we also have to destroy buffer in catch session, otherwise in the debug build the check "WriteBuffer is not finalized when destructor is called." would be triggered.

Comment (CheSema) [reply src/Server/InterserverIOHTTPHandler.cpp:123]: No. Im wrong, `finalized = true;` is set for even failed attempt to call `finalize()`.

Comment (antonio2368) [reply src/Server/InterserverIOHTTPHandler.cpp:123]: `finalized` is set to true even if exception happened so it should be okay.

Comment (CheSema) [reply src/Server/InterserverIOHTTPHandler.cpp:123]: I think that we could encounter similar cases in lines. The case when something wring on server side but after we unable to send error to the client as well.

https://github.com/ClickHouse/ClickHouse/blob/f421d3d571e07c2d4a5d006128fe2d2b54b82b35/src/Server/InterserverIOHTTPHandler.cpp#L99

https://github.com/ClickHouse/ClickHouse/blob/f421d3d571e07c2d4a5d006128fe2d2b54b82b35/src/Server/InterserverIOHTTPHandler.cpp#L111

Comment (antonio2368) [reply src/Server/InterserverIOHTTPHandler.cpp:123]: yes you are correct

**Review by CheSema — APPROVED** [review]
