### PR TITLE
Fix simple state with nullable

### LINKED ISSUE #34407: -SimpleState with nullable argument creates Nullable(SimpleAggregateFunction(...))
```
SELECT toTypeName(minSimpleState(toNullable(0)))

Query id: ca70501a-76f0-400e-89c2-3539a7ce6740

┌─toTypeName(minSimpleState(toNullable(0)))─────┐
│ Nullable(SimpleAggregateFunction(min, UInt8)) │
└───────────────────────────────────────────────┘
```

Should be 
```
SimpleAggregateFunction(min, Nullable(DateTime))
```

### PR DESCRIPTION
**Pull request by priera**
### Changelog category (leave one):
- Bug Fix 

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Nullable should be applied to the argument of SimpleAggregateFunction when -SimpleState is taken from Nullable (the same as for -State function)

Fixed #34407 

When instantiating a -Null combinator, the same behavior is applied to aggregates with -State or -SimpleState combinator

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 49d44e2a9dcc54b7a6d267de654dbf42936817df with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55030/49d44e2a9dcc54b7a6d267de654dbf42936817df/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>❌ failure</td></tr>
<tbody>
</table>

**Comment by priera** [comment]
I think the failing test, `02313_filesystem_cache_seeks`, is flaky: [query](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDcgREFZCiAgICBBTkQgdGVzdF9uYW1lID0gJzAyMzEzX2ZpbGVzeXN0ZW1fY2FjaGVfc2Vla3MnCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyA9ICdGQUlMJwpPUkRFUiBCWSBjaGVja19uYW1lLCB0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWU=)

File: src/AggregateFunctions/AggregateFunctionNull.cpp [hunk 1]
```diff
@@ -39,6 +38,34 @@ class AggregateFunctionCombinatorNull final : public IAggregateFunctionCombinato
...
+    }
+
+    AggregateFunctionPtr tryTransformStateFunction(const AggregateFunctionPtr & nested_function,
+                                                   const AggregateFunctionProperties & properties,
+                                                   const DataTypes & arguments,
+                                                   const Array & params) const
+    {
+        return tryTransformStateFunctionImpl<AggregateFunctionState>(nested_function, properties, arguments, params)
+            .or_else([&]() { return tryTransformStateFunctionImpl<AggregateFunctionSimpleState>(nested_function, properties, arguments, params); })
+            .value_or(nullptr);
```
Comment (yakov-olkhovskiy) [inline src/AggregateFunctions/AggregateFunctionNull.cpp:66]: convoluted but clever :)

**Review by yakov-olkhovskiy — APPROVED** [review]
