### PR TITLE
Fix incorrect query result when doing constant aggregation

### LINKED ISSUE #36728: Query returns wrong result when reading constant from MergeTree with GROUP BY
### The problem is reproduced in 22.3.2.1

`CREATE TABLE test02( id Int,col1 String,col2 String,create_date Date ) ENGINE = MergeTree() order by id;

INSERT into  default.test02 (id,col1,col2,create_date) VALUES (4,'1','1','2021-12-31 23:59:59')`

sql:
`select version() as version from test02 group by version order by version

SELECT version() AS version
FROM test02
GROUP BY version
ORDER BY version ASC

Query id: e0eb958d-54ac-4444-9d11-341035adcc02

Ok.

0 rows in set. Elapsed: 0.011 sec.`

**Expected behavior**

> get the function result

**Triggering conditions**

1. Use merge tree table engine
2. Do not reference column elements in tables in functions
3. use group by

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect query result when doing constant aggregation. This fixes https://github.com/ClickHouse/ClickHouse/issues/36728 .

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -5534,7 +5533,11 @@ std::optional<ProjectionCandidate> MergeTreeData::getQueryProcessingStageWithAgg
             max_added_blocks.get(),
             query_context);
 
-        if (query_info.minmax_count_projection_block && minmax_count_projection_candidate->prewhere_info)
+        // minmax_count_projection should not be used when there is no data to process.
```
Comment (amosbird) [inline src/Storages/MergeTree/MergeTreeData.cpp:5536]: Here is the fix

**Review by antonio2368 — APPROVED** [review]
