### PR TITLE
Fix AMBIGUOUS_COLUMN_NAME with lazy materialization

### LINKED ISSUE #79730: SELECT * ORDER BY rand() LIMIT 10 triggers DB::Exception: Block structure mismatch
### Company or project name

_No response_

### Describe what's wrong

A simple query causes exception, but only for specific values of LIMIT

It works just fine with LIMIT 0 or LIMIT 11 and above. Only LIMIT between 1 and 10 throws exception.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

CREATE TABLE default.test
(
    `foo` UInt32,
)
ENGINE = MergeTree
ORDER BY foo;

INSERT INTO test SELECT * FROM generateRandom() LIMIT 50;

SELECT * FROM test ORDER BY rand() LIMIT 10;

### Expected behavior

Return 10 rows of results.

### Error message and/or stacktrace

Received exception from server (version 25.4.1):
Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different columns:
foo UInt32 UInt32(size = 50)
foo UInt32 Lazy(size = 50): While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder).(AMBIGUOUS_COLUMN_NAME)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devcrafter**
Fixes https://github.com/ClickHouse/ClickHouse/issues/79730

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes AMBIGUOUS_COLUMN_NAME error with lazy materialization when no columns are used for query execution until projection. Example, SELECT * FROM t ORDER BY rand() LIMIT 5

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/QueryPlan/Optimizations/optimizeLazyMaterialization.cpp [hunk 1]
```diff
@@ -264,6 +264,11 @@ void optimizeLazyMaterialization(QueryPlan::Node & root, Stack & stack, QueryPla
     if (lazily_read_info->lazily_read_columns.empty())
         return;
 
+    /// avoid applying this optimization on impractical queries for sake of implementation simplicity
+    /// i.e. when no column used in query until projection, for example, select * from t order by rand() limit 10
+    if (reading_step->getAllColumnNames().size() == lazily_read_info->lazily_read_columns.size())
+        return;
```
Comment (yakov-olkhovskiy) [inline src/Processors/QueryPlan/Optimizations/optimizeLazyMaterialization.cpp:270]: I'm not sure this solution is optimal (if I understand it correctly) - if we have multiple columns and none of them is filtering  it still may be preferable to lazy all of them except one... again - if I understand this logic correctly...

**Review by yakov-olkhovskiy — APPROVED** [review]
