### PR TITLE
Low cardinality cases moved to the function for its corresponding type

### LINKED ISSUE #30184: Slow JSONExtract with LowCardinality(String) tuples
`JSONExtract` of Tuples with `LowCardinality(String)` is significantly slower than with regular strings: ~2.5 slower. 

Tested on CH 21.8.8.29

## Unexpectedly slow example

**60MB/s**

```
cat test.ndjson | clickhouse local -q "
    
SELECT JSONExtract(event, 'Tuple(
a LowCardinality(String),
b LowCardinality(String),
c LowCardinality(String),
d LowCardinality(String)

)') AS json FROM table" --input-format LineAsString --output-format Native --structure   "
    event String" --verbose --logger.level trace >> /dev/null
```

## Expectedly fast example

**150 MB/s**
```
time cat test.ndjson | clickhouse local -q "
    
SELECT JSONExtract(event, 'Tuple(
a String,
b String,
c String,
d String

)') AS json FROM table" --input-format LineAsString --output-format Native --structure   "
    event String" --verbose --logger.level trace >> /dev/null
```

## Workaround

**140 MB/s**
```
cat test.ndjson | clickhouse local -q "

SELECT
    toLowCardinality(json.1) AS a,
    toLowCardinality(json.2) AS b,
    toLowCardinality(json.3) AS c,
    toLowCardinality(json.4) AS d

FROM (SELECT JSONExtract(event, 'Tuple(
a String,
b String,
c String,
d String

)') AS json FROM table)" --input-format LineAsString --output-format Native --structure   "
    event String" --verbose --logger.level trace >> /dev/null


```
cc: @Algunenano 

[test.ndjson.zip](https://github.com/ClickHouse/ClickHouse/files/7347611/test.ndjson.zip)

### PR DESCRIPTION
**Pull request by AlfVII**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed slowness in JSONExtract with LowCardinality(String) tuples

Fixes https://github.com/ClickHouse/ClickHouse/issues/30184.

### CODE REVIEW

File: src/Functions/FunctionsJSON.cpp [hunk 1]
```diff
@@ -1100,8 +1129,13 @@ struct JSONExtractTree
             case TypeIndex::LowCardinality:
             {
                 auto dictionary_type = typeid_cast<const DataTypeLowCardinality *>(type.get())->getDictionaryType();
+                if ((*dictionary_type).getTypeId() == TypeIndex::FixedString)
+                {
+                    auto fixed_length = typeid_cast<const DataTypeFixedString *>(dictionary_type.get())->getN();
+                    return std::make_unique<LowCardinalityFixedStringNode>(fixed_length);
+                }
                 auto impl = build(function_name, dictionary_type);
-                return std::make_unique<LowCardinalityNode>(dictionary_type, std::move(impl));
```
Comment (canhld94) [inline src/Functions/FunctionsJSON.cpp:1104]: How about LowCardinality(String)?

File: src/Functions/FunctionsJSON.cpp [hunk 2]
```diff
@@ -695,8 +696,16 @@ class JSONExtractNumericImpl
         else
             return false;
 
-        auto & col_vec = assert_cast<ColumnVector<NumberType> &>(dest);
-        col_vec.insertValue(value);
+        if (dest.getDataType() == TypeIndex::LowCardinality)
```
[the remark this answers is not in the document]
Comment (AlfVII) [reply src/Functions/FunctionsJSON.cpp:699]: My bad, I forgot to mention in the description that this is a fix for: https://github.com/ClickHouse/ClickHouse/issues/30184

The objective of this PR is not to improve performance per se, but to improve the lack of speed described in the above issue, which is when the user uses a lowCardinality Node from a tuple in a JSON.

[the remark this answers is not in the document]
Comment (AlfVII) [reply src/Functions/FunctionsJSON.cpp:699]: You can either run the queries in the issue 30184 or just the performance test I have added in this PR to verify the speed difference

File: src/Functions/FunctionsJSON.cpp [hunk 3]
```diff
@@ -833,7 +852,15 @@ struct JSONExtractTree
                 return false;
 
             auto uuid = parseFromString<UUID>(element.getString());
-            assert_cast<ColumnUUID &>(dest).insert(uuid);
+            if (dest.getDataType() == TypeIndex::LowCardinality)
```
[the remark this answers is not in the document]
Comment (AlfVII) [reply src/Functions/FunctionsJSON.cpp:855]: As mention before, this is just to fix the decrease of speed when the user extracts a tuple of UUIDs from a JSON.

File: src/Functions/FunctionsJSON.cpp (hunk 1 above)
Comment (AlfVII) [reply src/Functions/FunctionsJSON.cpp:1104]: Low cardinality for String and Numeric are processed in their respective previous functions in order to simplify code: `JSONExtractStringImpl` and `JSONExtractNumericImpl`
The problem was that for FixedString I needed to access the result from `getN()` as the fixed string length, which is why has a different call.

**Comment by serxa** [comment]
Looks like new test `02452_check_low_cardinality` fails for some reason:
```
2022-09-26 15:24:10 [cecebf754983] 2022.09.26 15:24:10.992267 [ 13773 ] {1eaf6aba-68f2-4b8e-b611-27cd4d24d7c8}  executeQuery: Code: 48. DB::Exception: Functions JSON* are not supported: while executing 'FUNCTION JSONExtract(data :: 0, 'Tuple(\n                            a LowCardinality(String),\n                            b LowCardinality(String),\n                            c LowCardinality(String),\n                            d LowCardinality(String)\n                            \n                            )' :: 1) -> JSONExtract(data, 'Tuple(\n                            a LowCardinality(String),\n                            b LowCardinality(String),\n                            c LowCardinality(String),\n                            d LowCardinality(String)\n                            \n                            )') Tuple(a LowCardinality(String), b LowCardinality(String), c LowCardinality(String), d LowCardinality(String)) : 2'. (NOT_IMPLEMENTED) (version 22.10.1.1) (from [::1]:48968) (comment: 02452_check_low_cardinality.sql) (in query: SELECT JSONExtract(data, 'Tuple(
2022-09-26 15:24:10                             a LowCardinality(String),
2022-09-26 15:24:10                             b LowCardinality(String),
2022-09-26 15:24:10                             c LowCardinality(String),
2022-09-26 15:24:10                             d LowCardinality(String)
2022-09-26 15:24:10                             
2022-09-26 15:24:10                             )') AS json FROM test_low_cardinality_string;), Stack trace (when copying this message, always include the lines below):
2022-09-26 15:24:10 
2022-09-26 15:24:10 0. /fasttest-workspace/build/../../ClickHouse/contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int) @ 0x10e81c4c in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 1. /fasttest-workspace/build/../../ClickHouse/src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0x6f1543a in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 2. DB::DummyJSONParser::parse(std::__1::basic_string_view >, DB::DummyJSONParser::Element&) @ 0x94b73c3 in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 3. DB::FunctionJSONHelpers::Executor::run(std::__1::vector > const&, std::__1::shared_ptr const&, unsigned long) @ 0x9c75ba8 in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 4. DB::ExecutableFunctionJSON::executeImpl(std::__1::vector > const&, std::__1::shared_ptr const&, unsigned long) const @ 0x9c7581b in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 5. /fasttest-workspace/build/../../ClickHouse/src/Functions/IFunction.cpp:0: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector > const&, std::__1::shared_ptr const&, unsigned long, bool) const @ 0xee2104b in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 6. /fasttest-workspace/build/../../ClickHouse/contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector > const&, std::__1::shared_ptr const&, unsigned long, bool) const @ 0xee21860 in /fasttest-workspace/build/programs/clickhouse
2022-09-26 15:24:10 7. /fasttest-workspace/build/../../ClickHouse/src/Functions/IFunction.cpp:372: DB::IExecutableFunction::execute(std::__1::vector
```

**Comment by Algunenano** [comment]
> Looks like new test 02452_check_low_cardinality fails with NOT_IMPLEMENTED for some reason

Fast tests are built without libraries, and you need them to run JSONExtract. I think that the test should be tagged as `-- Tags: no-fasttest`

**Comment by AlfVII** [comment]
> > Looks like new test 02452_check_low_cardinality fails with NOT_IMPLEMENTED for some reason
> 
> Fast tests are built without libraries, and you need them to run JSONExtract. I think that the test should be tagged as `-- Tags: no-fasttest`

Tag added

File: src/Functions/FunctionsJSON.cpp [hunk 4]
```diff
@@ -803,25 +821,26 @@ struct JSONExtractTree
...
-                assert_cast<ColumnLowCardinality &>(dest).insertData(value.data(), value.size());
-                return true;
-            }
-            return false;
+            auto str = element.getString();
+
+            if (str.size() > fixed_length)
+                return false;
+
+            auto padded_str = str.data() + std::string(fixed_length - std::min(fixed_length, str.length()), '\0');
```
Comment (serxa) [inline src/Functions/FunctionsJSON.cpp:836]: Where did it come from? There was no padding prior to `FixedStringColumn::insertData()` calls. If it is some kind of optimization, please explain it in comments.

File: src/Functions/FunctionsJSON.cpp (hunk 1 above)
Comment (serxa) [reply src/Functions/FunctionsJSON.cpp:1104]: Please, add some comments about general logic: how we handle LowCardinality. Also comment why we need this specialization for FixedString. Explanations in comments to PRs are hard to find later and this code looks hard to understand without piece of reasoning behind all this optimizations.

File: src/Functions/FunctionsJSON.cpp (hunk 4 above)
Comment (AlfVII) [reply src/Functions/FunctionsJSON.cpp:838]: Added, let me know if it's clear

File: src/Functions/FunctionsJSON.cpp (hunk 1 above)
Comment (AlfVII) [reply src/Functions/FunctionsJSON.cpp:1104]: Added, let me know if it's clear

File: src/Functions/FunctionsJSON.cpp [hunk 5]
```diff
@@ -803,25 +821,28 @@ struct JSONExtractTree
         }
     };
 
-    class LowCardinalityNode : public Node
+    class LowCardinalityFixedStringNode : public Node
     {
     public:
-        LowCardinalityNode(DataTypePtr dictionary_type_, std::unique_ptr<Node> impl_)
-            : dictionary_type(dictionary_type_), impl(std::move(impl_)) {}
+        LowCardinalityFixedStringNode(const size_t fixed_length_) : fixed_length(fixed_length_) {}
```
Comment (serxa) [inline src/Functions/FunctionsJSON.cpp:827]: Looks like the last warning in CI is in tidy clang-15 debug is:
```
Sep 27 18:02:45 /build/build_docker/../src/Functions/FunctionsJSON.cpp:827:9: error: single-argument constructors must be marked explicit to avoid unintentional implicit conversions [google-explicit-constructor,-warnings-as-errors]
Sep 27 18:02:45         LowCardinalityFixedStringNode(const size_t fixed_length_) : fixed_length(fixed_length_) {}
Sep 27 18:02:45         ^
Sep 27 18:02:45         explicit
```

```suggestion
        explicit LowCardinalityFixedStringNode(const size_t fixed_length_) : fixed_length(fixed_length_) {}
```

**Review by serxa — APPROVED** [review]
LGTM, other test fails look unrelated

**Comment by serxa** [comment]
There is a null pointer dereference that AST fuzzer managed to find in new code (you can find it using `grep -Fa server.log`):
```
2022.09.28 14:36:31.846928 [ 393 ] {} <Fatal> BaseDaemon: ########################################
2022.09.28 14:36:31.847019 [ 393 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: 0383150BEA802C83761152E020D5F85BD450BC18) (from thread 154) (query_id: 5ffc5ef0-3370-40eb-b0b8-3d364b774b77) (query: SELECT 'H\0llo', JSONExtract('{"a" : {"b" : {"c" : 1, "d" : "str"}}}', 'Tuple(\n                            a LowCardinality(FixedString(20)),\n                            b LowCardinality(FixedString(20)),\n                            c LowCardinality(FixedString(20)),\n                            d LowCardinality(FixedString(20))\n                            \n                            )') AS json FROM test_low_cardinality_string) Received signal Segmentation fault (11)
2022.09.28 14:36:31.847076 [ 393 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2022.09.28 14:36:31.847208 [ 393 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fe966dea6e5 0x2f8e657b 0x1c37516a 0x1c37d86c 0x1c36e117 0x1c36d96a 0x1c36d65d 0x1b16ad7f 0x297bd339 0x297bcab3 0x297bd238 0x297bebdb 0x297c01b1 0x2a0889ae 0x2a63a02c 0x2a649634 0x2a63f618 0x2a64421c 0x2a6155c9 0x2a5fc9e6 0x2a609a8c 0x2a60f173 0x2adb21af 0x2ada5fc2 0x2ad9cf25 0x2ad9904e 0x2ada0c0e 0x2beb4b1c 0x2beb8558 0x2adb1d62 0x2ada5fc2 0x2ad9cf25 0x2ad9910f 0x2ae1d068 0x2ae19b8e 0x2ae17671 0x2ad3f908 0x2ad3e1db 0x2b255a71 0x2b251c2c 0x2c3bfd00 0x2c3e073a
2022.09.28 14:36:31.847282 [ 393 ] {} <Fatal> BaseDaemon: 3. ? @ 0x7fe966dea6e5 in ?
2022.09.28 14:36:31.859187 [ 393 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../contrib/libcxx/include/string:2893: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::insert(unsigned long, char const*) @ 0x2f8e657b in /workspace/clickhouse
2022.09.28 14:36:32.828154 [ 393 ] {} <Fatal> BaseDaemon: 5. DB::JSONExtractTree<DB::SimdJSONParser>::LowCardinalityFixedStringNode::insertResultToColumn(DB::IColumn&, DB::SimdJSONParser::Element const&) @ 0x1c37516a in /workspace/clickhouse
2022.09.28 14:36:33.780431 [ 393 ] {} <Fatal> BaseDaemon: 6. DB::JSONExtractTree<DB::SimdJSONParser>::TupleNode::insertResultToColumn(DB::IColumn&, DB::SimdJSONParser::Element const&) @ 0x1c37d86c in /workspace/clickhouse
2022.09.28 14:36:34.733512 [ 393 ] {} <Fatal> BaseDaemon: 7. DB::FunctionJSONHelpers::Executor<DB::NameJSONExtract, DB::JSONExtractImpl, DB::SimdJSONParser>::run(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0x1c36e117 in /workspace/clickhouse
2022.09.28 14:36:35.686558 [ 393 ] {} <Fatal> BaseDaemon: 8. DB::ExecutableFunctionJSON<DB::NameJSONExtract, DB::JSONExtractImpl>::chooseAndRunJSONParser(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x1c36d96a in /workspace/clickhouse
2022.09.28 14:36:36.640166 [ 393 ] {} <Fatal> BaseDaemon: 9. DB::ExecutableFunctionJSON<DB::NameJSONExtract, DB::JSONExtractImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x1c36d65d in /workspace/clickhouse
2022.09.28 14:36:37.593030 [ 393 ] {} <Fatal> BaseDaemon: 10. DB::IExecutableFunction::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x1b16ad7f in /workspace/clickhouse
2022.09.28 14:36:37.605939 [ 393 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Functions/IFunction.cpp:0: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x297bd339 in /workspace/clickhouse
2022.09.28 14:36:37.618115 [ 393 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Functions/IFunction.cpp:0: DB::IExecutableFunction::defaultImplementationForConstantArguments(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x297bcab3 in /workspace/clickhouse
2022.09.28 14:36:37.630466 [ 393 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/../contrib/boost/boost/smart_ptr/detail/operator_bool.hpp:14: boost::intrusive_ptr<DB::IColumn const>::operator bool() const
2022.09.28 14:36:37.630517 [ 393 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Functions/IFunction.cpp:238: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x297bd238 in /workspace/clickhouse
2022.09.28 14:36:37.643777 [ 393 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: intrusive_ptr
2022.09.28 14:36:37.643834 [ 393 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:122: boost::intrusive_ptr<DB::IColumn const>::operator=(boost::intrusive_ptr<DB::IColumn const>&&)
2022.09.28 14:36:37.643893 [ 393 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/../src/Common/COW.h:136: COW<DB::IColumn>::immutable_ptr<DB::IColumn>::operator=(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&&)
2022.09.28 14:36:37.643930 [ 393 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Functions/IFunction.cpp:302: DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x297bebdb in /workspace/clickhouse
2022.09.28 14:36:37.657749 [ 393 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Functions/IFunction.cpp:0: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x297c01b1 in /workspace/clickhouse
2022.09.28 14:36:37.848612 [ 393 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Interpreters/ActionsDAG.cpp:0: DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x2a0889ae in /workspace/clickhouse
2022.09.28 14:36:37.908952 [ 393 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Interpreters/ActionsVisitor.cpp:0: DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x2a63a02c in /workspace/clickhouse
2022.09.28 14:36:37.973287 [ 393 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../contrib/libcxx/include/string:1445: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
2022.09.28 14:36:37.973342 [ 393 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/../contrib/libcxx/include/string:2231: ~basic_string
2022.09.28 14:36:37.973402 [ 393 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Interpreters/ActionsVisitor.h:182: DB::ActionsMatcher::Data::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x2a649634 in /workspace/clickhouse
2022.09.28 14:36:38.034920 [ 393 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Interpreters/ActionsVisitor.cpp:0: DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x2a63f618 in /workspace/clickhouse
2022.09.28 14:36:38.098269 [ 393 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../contrib/libcxx/include/vector:0: DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x2a64421c in /workspace/clickhouse
2022.09.28 14:36:38.163521 [ 393 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Interpreters/InDepthNodeVisitor.h:43: DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0x2a6155c9 in /workspace/clickhouse
2022.09.28 14:36:38.229425 [ 393 ] {} <Fatal> BaseDaemon: 22.1. inlined from ./build_docker/../src/Interpreters/ActionsVisitor.h:187: DB::ActionsMatcher::Data::getActions()
2022.09.28 14:36:38.229476 [ 393 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../src/Interpreters/ExpressionAnalyzer.cpp:556: DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0x2a5fc9e6 in /workspace/clickhouse
2022.09.28 14:36:38.302987 [ 393 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Interpreters/ExpressionAnalyzer.cpp:0: DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0x2a609a8c in /workspace/clickhouse
2022.09.28 14:36:38.378948 [ 393 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Interpreters/ExpressionAnalyzer.cpp:0: DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x2a60f173 in /workspace/clickhouse
2022.09.28 14:36:38.475157 [ 393 ] {} <Fatal> BaseDaemon: 25. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:804: DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x2adb21af in /workspace/clickhouse
2022.09.28 14:36:38.568123 [ 393 ] {} <Fatal> BaseDaemon: 26. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>)::$_1::operator()(bool) const @ 0x2ada5fc2 in /workspace/clickhouse
2022.09.28 14:36:38.658903 [ 393 ] {} <Fatal> BaseDaemon: 27. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x2ad9cf25 in /workspace/clickhouse
2022.09.28 14:36:38.749100 [ 393 ] {} <Fatal> BaseDaemon: 28. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x2ad9904e in /workspace/clickhouse
2022.09.28 14:36:38.843292 [ 393 ] {} <Fatal> BaseDaemon: 29. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x2ada0c0e in /workspace/clickhouse
2022.09.28 14:36:39.038609 [ 393 ] {} <Fatal> BaseDaemon: 30. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:0: DB::MergeTreeData::getQueryProcessingStageWithAggregateProjection(std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&) const @ 0x2beb4b1c in /workspace/clickhouse
2022.09.28 14:36:39.235822 [ 393 ] {} <Fatal> BaseDaemon: 31.1. inlined from ./build_docker/../contrib/libcxx/include/optional:321: std::__1::__optional_storage_base<DB::ProjectionCandidate, false>::has_value() const
2022.09.28 14:36:39.235877 [ 393 ] {} <Fatal> BaseDaemon: 31.2. inlined from ./build_docker/../contrib/libcxx/include/optional:975: std::__1::optional<DB::ProjectionCandidate>::operator bool() const
2022.09.28 14:36:39.235938 [ 393 ] {} <Fatal> BaseDaemon: 31. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:6108: DB::MergeTreeData::getQueryProcessingStage(std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, std::__1::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&) const @ 0x2beb8558 in /workspace/clickhouse
2022.09.28 14:36:39.332225 [ 393 ] {} <Fatal> BaseDaemon: 32. ./build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:784: DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x2adb1d62 in /workspace/clickhouse
```

**Review by serxa — CHANGES_REQUESTED** [review]
null pointer dereference in corner case should be fixed before merging

**Comment by AlfVII** [comment]
> null pointer dereference in corner case should be fixed before merging

Should be fixed now.
I also did a small fixed related to the same case, but without the lowCardinality: extracting a Tuple with a FixedString from a JSON was failing if the JSON was nested, as the JSONParser was marking it as an Object instead of a String, and the Object case was only considered for StringsNodes

**Review by serxa — APPROVED** [review]

**Comment by AlfVII** [comment]
Hi @serxa , is this fine for merging? Thanks!

**Comment by CurtizJ** [comment]
@serxa
A bug has been found by fuzzer #42632. Revert?

**Comment by serxa** [comment]
Yes, please, looks like there is something...

**Comment by alexey-milovidov** [comment]
A bug has been found: https://github.com/ClickHouse/ClickHouse/pull/42633
