### PR TITLE
Fix bug with inability to drop detached partition in replicated merge tree on top of S3 without zero copy

### LINKED ISSUE #52393: S3 disk garbage collection?
Hi,

If we use S3 as a disk for a table, how does Clickhouse make sure there are no orphan files left in the S3 bucket?

In my recent test, I have encountered a lot of S3 rate limiting errors (HTTP 503, "Slow Down") when bulk inserted lots of data.

Then I truncated the table. This seems have left many files in the S3 bucket undeleted, although the table is empty.

This bucket is used only in this test and only for this table, I expect the S3 bucket to be empty when truncated. I also waited some time for Clickhouse to perform some sort of "garbage collection" but it seems not happening.

This will be an issue if we use S3 disks for production and the 'garbage' size keeps growing (storage costs $$). 

Does Clickhouse have any mechanism to detect and collect garbage (unused S3 objects)?

Thanks for any insights if I missed something.

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix an issue with inability to drop detached partition in `ReplicatedMergeTree` engines family on top of S3 (without zero-copy replication). Fixes issue #55225. Fix bug with abandoned blobs on S3 for complex data types like Arrays or Nested columns. Partially fixes #52393. Many kudos to @alifirat for examples.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit eec64ba1d91ef17de7cce0da66734a91a4248a1a with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55309/eec64ba1d91ef17de7cce0da66734a91a4248a1a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6442470685">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55309/eec64ba1d91ef17de7cce0da66734a91a4248a1a/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alifirat** [comment]
@alesapin it's a great news to see those fixes. 
Do you think we can backport to them to the latest LTS?

**Comment by alesapin** [comment]
`>  Do you think we can backport to them to the latest LTS?`
I think we can, but want @CheSema to look at the changes in write operation.

File: src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp [hunk 1]
```diff
@@ -682,10 +683,17 @@ std::unique_ptr<WriteBufferFromFileBase> DiskObjectStorageTransaction::writeFile
...
     if (autocommit)
     {
-        create_metadata_callback = [tx = shared_from_this(), mode, path, blob_name] (size_t count)
+        create_metadata_callback = [tx = shared_from_this(), mode, path, blob_name](size_t count)
         {
             if (mode == WriteMode::Rewrite)
+            {
+                // Otherwise we will produce lost blobs which nobody points to
+                /// WriteOnce storages are not affected by the issue
+                if (!tx->object_storage.isWriteOnce() && tx->metadata_storage.exists(path))
```
Comment (CheSema) [inline src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:692]: Do we need such changes in writeFileUsingBlobWritingFunction also?

Comment (alesapin) [reply src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:692]: I think yes, let's do!

Comment (CheSema) [reply src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:692]: Also `Unfreezer::removeFreezedPart` has similar branch `if (disk->supportZeroCopyReplication())`. Maybe it is worth to fix it too.

**Review by CheSema — APPROVED** [review]
