### PR TITLE
`set` index: check condition for null values

### LINKED ISSUE #75485: Bad index default value
### Describe the bug

After inserting a default value into a column backed by a set index, the count() query returns a wrong result. Check Fiddle.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/0cf22543-05a2-49a7-b4e1-1fe61407d251 

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by ahmadov**
Fixes #75485

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Previously, `set` indexes didn't consider `Nullable` columns while checking if granules passed the filter (issue #75485)

### CODE REVIEW

File: tests/queries/0_stateless/02789_set_index_nullable_condition_bug.sql [hunk 1]
```diff
@@ -1,15 +1,65 @@
-drop table if exists test_table;
-CREATE TABLE test_table
+DROP TABLE IF EXISTS tab;
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02789_set_index_nullable_condition_bug.sql:1]: @ahmadov Strangely enough, I have the problem that the test is flaky. Can be easily reproduced locally by

```sh
PATH=build/programs/:$PATH tests/clickhouse-test --test-runs 5 02789_set_index_nullable_condition_bug
```

```
Reason: result differs with reference:
--- /data/ch5/tests/queries/0_stateless/02789_set_index_nullable_condition_bug.reference        2025-07-23 15:19:03.420132822 +0000
+++ /data/ch5/tests/queries/0_stateless/02789_set_index_nullable_condition_bug.1698954.stdout   2025-07-23 15:29:49.904700159 +0000
@@ -1,4 +1,4 @@
 v1     v2
-2
+0
 3
-2
+0
```

Comment (ahmadov) [reply tests/queries/0_stateless/02789_set_index_nullable_condition_bug.sql:1]: very interesting find.. I'm looking into what happens when the tests are executed in parallel.

Comment (ahmadov) [reply tests/queries/0_stateless/02789_set_index_nullable_condition_bug.sql:1]: Seems the issue caused by randomly setting `secondary_indices_enable_bulk_filtering`. Fixed the case for non bulk filtering.

Comment (rschu1ze) [reply tests/queries/0_stateless/02789_set_index_nullable_condition_bug.sql:1]: Fascinating stuff. Thanks for fixing.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Re-running "Upgrade check (amd_msan)".

**Comment by ahmadov** [comment]
> Re-running "Upgrade check (amd_msan)".

thanks. I was looking into builds to find its root cause but couldn't find it. I'm not sure from which build the check got that error message
