### PR TITLE
Fix optimization with lazy seek for async reads from remote fs

### LINKED ISSUE #32803: Asynchronous reading from S3 storage works unstable
**Describe what's wrong**

Reading from S3 storage with setting remote_filesystem_read_method='threadpool' works unstable.

**How to reproduce**

ClickHouse instance with local disk 'default' and remote S3 disk 'object_storage', version 21.11+

```
CREATE TABLE test (key UInt32, value String) Engine=MergeTree() ORDER BY key;
INSERT INTO test SELECT * FROM generateRandom('key UInt32, value String') LIMIT 100000000;
ALTER TABLE test MOVE PARTITION tuple() TO DISK 'object_storage';

SET remote_filesystem_read_method='read';

SELECT * FROM test WHERE value LIKE '%abc%' ORDER BY value LIMIT 10;

┌────────key─┬─value──────┐
│ 1386733915 │  90U"abcKl │
│ 3311351188 │  H=TE$abc" │
│ 3625292387 │  N}>Dabc+  │
│  522418730 │  Uabc^?~Y& │
│ 1481317993 │  abc       │
│ 2971179404 │ !TJyFabcA  │
│  494145162 │ !V0(abc!   │
│ 2906258491 │ !yabc      │
│ 1626308423 │ !}abcytSv+ │
│  710856985 │ ">pabc     │
└────────────┴────────────┘

SET remote_filesystem_read_method='threadpool';

SELECT * FROM test WHERE value LIKE '%abc%' ORDER BY value LIMIT 10;

Received exception from server (version 21.11.5):
Code: 271. DB::Exception: Received from localhost:9000. DB::Exception: Data compressed with different methods, given method byte 0x5f, previous method byte 0x82: (while reading column key): (while reading from part /var/lib/clickhouse/disks/object_storage/store/b3e/b3ed68ba-dab5-4089-b3ed-68badab5f089/all_1_89_3/ from mark 8412 with max_rows_to_read = 443): While executing MergeTreeThread. (CANNOT_DECOMPRESS)

```

**Expected behavior**

The same result as with remote_filesystem_read_method='read'

**Error message and/or stacktrace**

```
2021.12.15 14:37:01.953951 [ 2880 ] {868c95cf-c1e0-4c91-8963-2cd982034c70} <Error> executeQuery: Code: 271. DB::Exception: Data compressed with different methods, given method byte 0x02, previous method byte 0x82: (while reading column key): (while reading from part /var/lib/clickhouse/disks/object_storage/store/b3e/b3ed68ba-dab5-4089-b3ed-68badab5f089/all_1_89_3/ from mark 3850 with max_rows_to_read = 3379): While executing MergeTreeThread. (CANNOT_DECOMPRESS) (version 21.11.5.33 (official build)) (from [::1]:34148) (in query: select * from test where value like '%abc%' order by value limit 10), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b737d4 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
1. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x11b798c8 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
2. DB::CompressedReadBufferFromFile::readBig(char*, unsigned long) @ 0x11b7b808 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
3. DB::SerializationNumber<unsigned int>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x11d51a13 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
4. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x11d26815 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
5. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x12ed9fc2 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
6. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x12ed8d99 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
7. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x134087ee in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
8. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x1340c899 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
9. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x1340b8f3 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
10. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x13403fda in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
11. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x1340522d in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
12. DB::MergeTreeBaseSelectProcessor::generate() @ 0x134038cb in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
13. DB::ISource::tryGenerate() @ 0x1316a1f5 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
14. DB::ISource::work() @ 0x13169dba in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
15. DB::SourceWithProgress::work() @ 0x13376562 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
16. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x1318565b in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
17. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x13181611 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
18. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_4>(DB::PipelineExecutor::executeImpl(unsigned long)::$_4&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x131875e5 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb5897 in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
20. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x9bb929d in /usr/lib/debug/.build-id/76/a10a4f605ef849249f2e8673661f7254b779da.debug
21. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
22. clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so

```

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix optimization with lazy seek for async reads from remote fs. Closes https://github.com/ClickHouse/ClickHouse/issues/32803

### CODE REVIEW

File: src/Disks/IO/ReadBufferFromRemoteFSGather.cpp [hunk 1]
```diff
@@ -155,15 +156,26 @@ bool ReadBufferFromRemoteFSGather::readImpl()
...
+    {
         current_buf->ignore(bytes_to_ignore);
+        bytes_to_ignore = 0;
+    }
 
-    auto result = current_buf->next();
+    bool result = current_buf->hasPendingData();
+    if (result)
+    {
+        /// bytes_to_ignore alreade added.
```
Comment (alesapin) [inline src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:167]:
```suggestion
        /// bytes_to_ignore already added.
```

File: src/Disks/IO/ReadBufferFromRemoteFSGather.cpp [hunk 2]
```diff
@@ -75,14 +75,15 @@ size_t ReadBufferFromRemoteFSGather::readInto(char * data, size_t size, size_t o
...
     bytes_to_ignore = ignore;
+    if (bytes_to_ignore)
+        assert(initialized());
 
     auto result = nextImpl();
-    bytes_to_ignore = 0;
 
     if (result)
-        return working_buffer.size();
+        return {working_buffer.size(), BufferBase::offset()};
```
Comment (alesapin) [inline src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:84]: why we return offset? bytes_to_ignore already accounted?

File: src/Disks/IO/ReadBufferFromRemoteFSGather.cpp [hunk 3]
```diff
@@ -155,15 +156,26 @@ bool ReadBufferFromRemoteFSGather::readImpl()
...
         current_buf->ignore(bytes_to_ignore);
+        bytes_to_ignore = 0;
+    }
 
-    auto result = current_buf->next();
+    bool result = current_buf->hasPendingData();
+    if (result)
+    {
+        /// bytes_to_ignore alreade added.
+        absolute_position += current_buf->available();
```
Comment (alesapin) [inline src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:168]: How `bytes_to_ignore` affect absolute position?

File: src/Disks/IO/ReadBufferFromRemoteFSGather.h [hunk 4]
```diff
@@ -37,10 +37,14 @@ friend class ReadIndirectBufferFromRemoteFS;
 
     void setReadUntilPosition(size_t position) override;
 
-    size_t readInto(char * data, size_t size, size_t offset, size_t ignore = 0);
+    std::pair<size_t, size_t> readInto(char * data, size_t size, size_t offset, size_t ignore = 0);
 
     size_t getFileSize() const;
 
+    size_t getPos() const { return absolute_position; }
```
Comment (alesapin) [inline src/Disks/IO/ReadBufferFromRemoteFSGather.h:44]: /// Very detailed comment what is absolute position.
`getAbsolutePosition`

File: src/IO/SynchronousReader.cpp [hunk 5]
```diff
@@ -82,10 +82,8 @@ std::future<IAsynchronousReader::Result> SynchronousReader::submit(Request reque
         watch.stop();
         ProfileEvents::increment(ProfileEvents::DiskReadElapsedMicroseconds, watch.elapsedMicroseconds());
 
-        return bytes_read;
+        return std::make_pair(bytes_read, static_cast<size_t>(0));
```
Comment (alesapin) [inline src/IO/SynchronousReader.cpp:85]: `bytes_to_ignore` can be non-zero only in async reader when we decide to read some data instead of seek. So that is why here it's always zero?

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp [hunk 6]
```diff
@@ -152,12 +154,16 @@ bool AsynchronousReadIndirectBufferFromRemoteFS::nextImpl()
...
+            size_t offset;
+            std::tie(size, offset) = prefetch_future.get();
+            assert(offset < working_buffer.size());
             if (size)
             {
                 memory.swap(prefetch_buffer);
                 set(memory.data(), memory.size());
                 working_buffer.resize(size);
+                size = working_buffer.end() - (working_buffer.begin() + offset);
+                BufferBase::set(working_buffer.begin() + offset, size, 0);
```
Comment (alesapin) [inline src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:166]: Why we need BufferBase::set here?

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp [hunk 7]
```diff
@@ -152,12 +154,16 @@ bool AsynchronousReadIndirectBufferFromRemoteFS::nextImpl()
...
         {
-            size = prefetch_future.get();
+            size_t offset;
+            std::tie(size, offset) = prefetch_future.get();
+            assert(offset < working_buffer.size());
             if (size)
             {
                 memory.swap(prefetch_buffer);
                 set(memory.data(), memory.size());
                 working_buffer.resize(size);
```
Comment (alesapin) [inline src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:164]: maybe we need `size - offset`?

Comment (kssenii) [reply src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:164]: No, becuase first `offset` bytes must be skipped. We need last `working_buffer.size() - offset` bytes, so this is what is done in the next few lines -- we get correct part.

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp (hunk 6 above)
Comment (kssenii) [reply src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:166]: See comment below.

File: src/IO/SynchronousReader.cpp (hunk 5 above)
Comment (kssenii) [reply src/IO/SynchronousReader.cpp:85]: It can be non-zero only when we decide to do `ignore(bytes_to_ignore)`, this optimization is done inly for reading from remote fs, but `SynchronousReadBuffer` is for local fs, therefore it is `0` here.

File: src/Disks/IO/ReadBufferFromRemoteFSGather.cpp (hunk 3 above)
Comment (kssenii) [reply src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:168]: `bytes_to_ignore` is included in `file_offset_of_buffer_end` when define value of `bytes_to_ignore`. Then we pass `file_offset_of_buffer_end` to `ReadBufferFromRemoteFSGather` and assign to `absolute_position` https://github.com/ClickHouse/ClickHouse/blob/2ae5eb4cfad581011a6d86fcc3a83a21fa8f3466/src/Disks/IO/ReadBufferFromRemoteFSGather.cpp#L76
so that is why `bytes_to_ignore` is already included in `absolute_position`, after that we do `ignore` and need to add only `available` to `absolute_position`. `absolute_position` is in total how far the file was read.

File: src/Disks/IO/ReadBufferFromRemoteFSGather.cpp (hunk 2 above)
Comment (kssenii) [reply src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:84]: Here are inside a method `readInto(char * data, ...)` and in `ignore(bytes_to_ignore)` we read something and possibly there is pending data after `ignore` in current buffer. So in this case we return current buffer and offset -- to know that actual data starts from `offset` and not from `working_buffer.begin()`. This got a little complicated (adding `offset` as return parameter) because we cannot change where `data` in `readInto(char * data, ...)` points.

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp (hunk 6 above)
Comment (kssenii) [reply src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp]: Simplified this part.

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp (hunk 7 above)
Comment (kssenii) [reply src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:165]: Simplified this part.

**Comment by alexey-milovidov** [comment]
But remote fs is non-production feature. No need to backport.

**Comment by alexey-milovidov** [comment]
@vmihailenco If you already started playing with this experimental feature (that is not ready for production usages), 
you can install the latest ClickHouse version from master:

```
curl https://clickhouse.com/ | sh
```

**Comment by vmihailenco** [comment]
Judging by articles on Altinity, people are using S3 for 2 years now. I am using S3 since 2021. It works quite well but with some quirks (like CH in general but it is still the best and the development speed is unmatched). I am happy with it.

>you will be able to install the latest ClickHouse version from master:

I would do that, but regressions are not that rare so even staying 1 minor version behind the tip may not be enough. Using the latest version is adventurous :) That is an acceptable price to pay for having so many features in each release. And backporting the fixes helps a lots. That is why the downvote.

But overall, ClickHouse is awesome :+1:  Thanks everyone involved.

File: src/IO/AsynchronousReadBufferFromFileDescriptor.cpp [hunk 8]
```diff
@@ -90,7 +91,7 @@ bool AsynchronousReadBufferFromFileDescriptor::nextImpl()
     {
         /// No pending request. Do synchronous read.
 
-        auto size = readInto(memory.data(), memory.size()).get();
+        auto [size, offset] = readInto(memory.data(), memory.size()).get();
```
Comment (alesapin) [inline src/IO/AsynchronousReadBufferFromFileDescriptor.cpp:94]: `auto [size, _] = ` explicitly shows that we don't use second variable.

File: src/Disks/IO/ReadBufferFromRemoteFSGather.h [hunk 9]
```diff
@@ -57,7 +67,7 @@ friend class ReadIndirectBufferFromRemoteFS;
 
     size_t current_buf_idx = 0;
 
-    size_t absolute_position = 0;
+    size_t file_offset_of_buffer_end = 0;
```
Comment (alesapin) [inline src/Disks/IO/ReadBufferFromRemoteFSGather.h:70]:
```
File: |___________________|
Buffer:      |~~~~~~~|
this var:            ^
```
If true -- add a comment.

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp [hunk 10]
```diff
@@ -231,18 +245,23 @@ off_t AsynchronousReadIndirectBufferFromRemoteFS::seek(off_t offset_, int whence
...
+        && static_cast<off_t>(file_offset_of_buffer_end) > file_offset_before_seek
+        && static_cast<off_t>(file_offset_of_buffer_end) < file_offset_before_seek + static_cast<off_t>(min_bytes_for_seek))
     {
-       /**
-        * Lazy ignore. Save number of bytes to ignore and ignore it either for prefetch buffer or current buffer.
-        */
-        bytes_to_ignore = file_offset_of_buffer_end - getPosition();
+        ProfileEvents::increment(ProfileEvents::RemoteFSLazySeeks);
+        bytes_to_ignore = file_offset_of_buffer_end - file_offset_before_seek;
+        prefetch_future = readInto(prefetch_buffer.data(), prefetch_buffer.size());
```
Comment (alesapin) [inline src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:260]: Why we call `readInto` here now? Should we discard the result of previous `prefetch_future`?

Comment (kssenii) [reply src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:260]: > Should we discard the result of previous prefetch_future?

It is discarded 20 lines above.

> Why we call readInto here now? 

to ignore redundant now.

File: src/Disks/IO/ReadBufferFromRemoteFSGather.h (hunk 9 above)
Comment (kssenii) [reply src/Disks/IO/ReadBufferFromRemoteFSGather.h:70]: Okay

**Review by alesapin — APPROVED** [review]

**Comment by kssenii** [comment]
`test_merge_tree_azure_blob_storage/*` -- not related to changes, will fix in a separate pr.
