### PR TITLE
Fix reading port from config

### LINKED ISSUE #34776: clickhouse-client ignores port parameter from config file, ClickHouse 22.2.2
**Describe the issue**
In the latest version (22.2.2.1) clickhouse-client ignores `port` parameter from config file.
 
**How to reproduce**
Create `config.xml` with arbitrary value for `port` parameter. 
```
<config>
    <port>9001</port>
</config>
```

Run `clickhouse-client` with custom config file
```
# clickhouse-client --log-level trace -c config.xml
Processing configuration file 'config.xml'.
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user default.
Connecting. Database: (not specified). User: default. Uncompressed
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)

Uninitializing subsystem: Logging Subsystem
```

The output indicates that it's used default port value (9000) instead of the value from config file (9001).

### PR DESCRIPTION
**Pull request by vdimir**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix reading port from config, close https://github.com/ClickHouse/ClickHouse/issues/34776

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

File: programs/client/Client.cpp [hunk 1]
```diff
@@ -1106,8 +1106,11 @@ void Client::processOptions(const OptionsDescription & options_description,
             = po::command_line_parser(hosts_and_ports_argument).options(options_description.hosts_and_ports_description.value()).run();
         po::variables_map host_and_port_options;
         po::store(parsed_hosts_and_ports, host_and_port_options);
-        hosts_and_ports.emplace_back(
-            HostAndPort{host_and_port_options["host"].as<std::string>(), host_and_port_options["port"].as<UInt16>()});
+        std::string host = host_and_port_options["host"].as<std::string>();
+        std::optional<UInt16> port = !host_and_port_options["port"].empty()
+                                     ? std::make_optional(host_and_port_options["port"].as<UInt16>())
+                                     : std::nullopt;
+        hosts_and_ports.emplace_back(HostAndPort{host, port});
```
Comment (antonio2368) [inline programs/client/Client.cpp:1113]:
```suggestion
        hosts_and_ports.emplace_back(HostAndPort{std::move(host), port});
```

File: src/Client/ConnectionParameters.cpp [hunk 2]
```diff
@@ -25,7 +25,9 @@ namespace ErrorCodes
 
 ConnectionParameters::ConnectionParameters(const Poco::Util::AbstractConfiguration & config,
                                            std::string connection_host,
-                                           int connection_port) : host(connection_host), port(connection_port)
+                                           std::optional<UInt16> connection_port)
+    : host(connection_host)
```
Comment (antonio2368) [inline src/Client/ConnectionParameters.cpp:29]:
```suggestion
    : host(std::move(connection_host))
```

**Review by antonio2368 — APPROVED** [review]

**Comment by vdimir** [comment]
Test were not suitable to run in parallel. I've made temp config name random for each run
