### PR TITLE
Gracefully fail when querying a delayed remote source

### LINKED ISSUE #83282: use_delayed_remote_source failpoint vector out of bounds
### Describe the bug

Happens since v25.2

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/5f63268e-0b9a-4879-ab6c-3536c4109298

### Error message and/or stacktrace

Stack trace:

```
contrib/llvm-project/libcxx/include/vector:1436: assertion __n < size() failed: vector[] index out of bounds
2025.07.04 14:45:00.734678 [ 2015792 ] {} <Trace> BaseDaemon: Received signal 6
2025.07.04 14:45:00.734852 [ 2016509 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.07.04 14:45:00.734882 [ 2016509 ] {} <Fatal> BaseDaemon: (version 25.7.1.2256 (official build), build id: FF4A270C26B03771D09413B98B31C8E17F4AF4B2, git hash: 4409a3e94d33eb3a4c8618b8de2dcdb22bafd586, architecture: x86_64) (from thread 2016505) Received signal 6
2025.07.04 14:45:00.734893 [ 2016509 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.07.04 14:45:00.734896 [ 2016509 ] {} <Fatal> BaseDaemon: 
2025.07.04 14:45:00.734902 [ 2016509 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007b744bca50bd 0x00007b744bc456de 0x00007b744bc288cd 0x0000633f685fe01d 0x0000633f5fac157d 0x0000633f5c0bfd09 0x0000633f5c0dcdae 0x0000633f5c0dc35d 0x0000633f5c0dc1ba 0x0000633f5c0dc0e1
2025.07.04 14:45:00.734928 [ 2016509 ] {} <Fatal> BaseDaemon: ########################################
2025.07.04 14:45:00.734976 [ 2016509 ] {} <Fatal> BaseDaemon: (version 25.7.1.2256 (official build), build id: FF4A270C26B03771D09413B98B31C8E17F4AF4B2, git hash: 4409a3e94d33eb3a4c8618b8de2dcdb22bafd586) (from thread 2016505) (query_id: 9c429218-42a8-4b47-9193-f04e5db20531) (query: SELECT count() FROM remoteSecure('localhost:9440', 'default', 't0') AS t0d0;) Received signal Aborted (6)
2025.07.04 14:45:00.735010 [ 2016509 ] {} <Fatal> BaseDaemon: 
2025.07.04 14:45:00.735037 [ 2016509 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007b744bca50bd 0x00007b744bc456de 0x00007b744bc288cd 0x0000633f685fe01d 0x0000633f5fac157d 0x0000633f5c0bfd09 0x0000633f5c0dcdae 0x0000633f5c0dc35d 0x0000633f5c0dc1ba 0x0000633f5c0dc0e1
2025.07.04 14:45:00.735113 [ 2016509 ] {} <Fatal> BaseDaemon: 3. __GI___pthread_kill @ 0x00000000000a50bd
2025.07.04 14:45:00.735155 [ 2016509 ] {} <Fatal> BaseDaemon: 4. raise @ 0x00000000000456de
2025.07.04 14:45:00.735179 [ 2016509 ] {} <Fatal> BaseDaemon: 5. __GI_abort @ 0x00000000000288cd
2025.07.04 14:45:00.740047 [ 2016509 ] {} <Fatal> BaseDaemon: 6. contrib/llvm-project/libcxx/src/verbose_abort.cpp:74: ? @ 0x000000002582601d
2025.07.04 14:45:00.754539 [ 2016509 ] {} <Fatal> BaseDaemon: 7.0. inlined from contrib/llvm-project/libcxx/include/vector:1436: std::vector<DB::MultiplexedConnections::ReplicaState, std::allocator<DB::MultiplexedConnections::ReplicaState>>::operator[][abi:se190107](unsigned long)
2025.07.04 14:45:00.754581 [ 2016509 ] {} <Fatal> BaseDaemon: 7. src/Client/MultiplexedConnections.cpp:207: DB::MultiplexedConnections::sendQuery(DB::ConnectionTimeouts const&, String const&, String const&, unsigned long, DB::ClientInfo&, bool, std::vector<String, std::allocator<String>> const&) @ 0x000000001cce957d
2025.07.04 14:45:00.795018 [ 2016509 ] {} <Fatal> BaseDaemon: 8. src/QueryPipeline/RemoteQueryExecutor.cpp:453: DB::RemoteQueryExecutor::sendQueryUnlocked(DB::ClientInfo::QueryKind, std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>) @ 0x00000000192e7d09
2025.07.04 14:45:00.803343 [ 2016509 ] {} <Fatal> BaseDaemon: 9. src/QueryPipeline/RemoteQueryExecutorReadContext.cpp:48: DB::RemoteQueryExecutorReadContext::Task::run(std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>, std::function<void ()>) @ 0x0000000019304dae
2025.07.04 14:45:00.807159 [ 2016509 ] {} <Fatal> BaseDaemon: 10. src/Common/AsyncTaskExecutor.cpp:89: DB::AsyncTaskExecutor::Routine::operator()(std::function<void ()>) @ 0x000000001930435d
2025.07.04 14:45:00.810848 [ 2016509 ] {} <Fatal> BaseDaemon: 11.0. inlined from src/Common/Fiber.h:76: Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>::operator()(boost::context::fiber&&)
2025.07.04 14:45:00.810889 [ 2016509 ] {} <Fatal> BaseDaemon: 11.1. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&>()(std::declval<boost::context::fiber>())) std::__invoke[abi:se190107]<Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber>(Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>&, boost::context::fiber&&)
2025.07.04 14:45:00.810907 [ 2016509 ] {} <Fatal> BaseDaemon: 11.2. inlined from contrib/llvm-project/libcxx/include/__functional/invoke.h:28: ?
2025.07.04 14:45:00.810930 [ 2016509 ] {} <Fatal> BaseDaemon: 11. contrib/boost/boost/context/fiber_fcontext.hpp:157: boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>>::run(void*) @ 0x00000000193041ba
2025.07.04 14:45:00.815023 [ 2016509 ] {} <Fatal> BaseDaemon: 12. contrib/boost/boost/context/fiber_fcontext.hpp:97: void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, Fiber::RoutineImpl<DB::AsyncTaskExecutor::Routine>>>(boost::context::detail::transfer_t) @ 0x00000000193040e1
2025.07.04 14:45:01.012398 [ 2016509 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: C617E8D6CC0730D186C851FD1ACA6650)
2025.07.04 14:45:01.021004 [ 2016509 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.07.04 14:45:01.021171 [ 2016509 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, allow_reorder_prewhere_conditions = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 120., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_execute_multiif_columnar = true, allow_drop_detached = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, allow_experimental_correlated_subqueries = true, allow_unrestricted_reads_from_keeper = true, allow_deprecated_database_ordinary = true, allow_deprecated_syntax_for_merge_tree = true, keeper_max_retries = 15, allow_get_client_http_header = true, allow_create_index_without_type = true, allow_named_collection_override_by_default = true, allow_deprecated_error_prone_window_functions = true, allow_deprecated_snowflake_conversion_functions = true, allow_experimental_analyzer = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_archive_path_syntax = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_vector_similarity_index = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_inverted_index = true, allow_experimental_full_text_index = true, allow_experimental_join_condition = true, allow_experimental_live_view = true, allow_experimental_window_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_bfloat16_type = true, allow_experimental_shared_set_join = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by george-larionov**
Resolves #83282. Sometimes when the remote source is delayed sendQuery() receives an empty replica_states vector, which was not checked for. The fix was to add a check for an empty vector and fail gracefully in this case.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed issue where querying a delayed remote source could result in vector out of bounds.

### CODE REVIEW

File: tests/queries/0_stateless/03581_query_secure_delayed_remote_source.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
+-- Tags: no-parallel, no-fasttest
+-- Tag no-parallel: failpoint is used which can force DelayedSource on other tests
+-- Tag no-fasttest: fasttest is built without SSL so remoteSecure() fails
+
+DROP TABLE IF EXISTS t0;
+CREATE TABLE t0 (c0 Int) ENGINE = Memory;
+
+SYSTEM ENABLE FAILPOINT use_delayed_remote_source;
+
+SELECT count() FROM remoteSecure('localhost:9440', currentDatabase(), 't0') AS tx; -- { serverError 265 }
```
Comment (azat) [inline tests/queries/0_stateless/03581_query_secure_delayed_remote_source.sql]: Better to use names:

```suggestion
SELECT count() FROM remoteSecure('localhost:9440', currentDatabase(), 't0') AS tx; -- { serverError NO_AVAILABLE_REPLICA }
```

File: src/Client/MultiplexedConnections.cpp [hunk 2]
```diff
@@ -200,15 +200,19 @@ void MultiplexedConnections::sendQuery(
...
+    else if (num_replicas == 1)
     {
         /// Use single replica.
         replica_states[0].connection->sendQuery(
             timeouts, query, /* query_parameters */ {}, query_id, stage, &modified_settings, &client_info, with_pending_data, external_roles, {});
+        sent_query = true;
+    }
+    else
+    {
+        throw Exception(ErrorCodes::NO_AVAILABLE_REPLICA, "No available replica");
```
Comment (azat) [inline src/Client/MultiplexedConnections.cpp]: We should never get here with 0 replicas, and the problem is in `ReadFromRemote::addLazyPipe`, in case of `use_delayed_remote_source = true` we ignore the exceptions during obtaining the connections here - https://github.com/ClickHouse/ClickHouse/blob/c5f370c2c4845bf659141ceb11fefbd3e3e6be02/src/Processors/QueryPlan/ReadFromRemote.cpp#L521-L537

We need to rethrow the original exception if fallback to local replica (w/o TCP communication) is not possible, i.e.

<details>

<summary>patch</summary>

```patch
$ git di
diff --git a/src/Client/MultiplexedConnections.cpp b/src/Client/MultiplexedConnections.cpp
index 48ac03dc595..68058a48e41 100644
--- a/src/Client/MultiplexedConnections.cpp
+++ b/src/Client/MultiplexedConnections.cpp
@@ -186,6 +186,7 @@ void MultiplexedConnections::sendQuery(
     const bool enable_offset_parallel_processing = context->canUseOffsetParallelReplicas();

     size_t num_replicas = replica_states.size();
+    chassert(num_replicas > 0);
     if (num_replicas > 1)
     {
         if (enable_offset_parallel_processing)
diff --git a/src/Processors/QueryPlan/ReadFromRemote.cpp b/src/Processors/QueryPlan/ReadFromRemote.cpp
index 40e91f4e907..a18341cf277 100644
--- a/src/Processors/QueryPlan/ReadFromRemote.cpp
+++ b/src/Processors/QueryPlan/ReadFromRemote.cpp
@@ -515,6 +515,12 @@ void ReadFromRemote::addLazyPipe(
         auto timeouts = ConnectionTimeouts::getTCPTimeoutsWithFailover(current_settings)
                             .getSaturated(current_settings[Setting::max_execution_time]);

+        bool use_delayed_remote_source = false;
+        fiu_do_on(FailPoints::use_delayed_remote_source,
+        {
+            use_delayed_remote_source = true;
+        });
+
         // In case reading from parallel replicas is allowed, lazy case is not triggered,
         // so in this case it's required to get only one connection from the pool
         std::vector<ConnectionPoolWithFailover::TryResult> try_results;
@@ -529,7 +535,7 @@ void ReadFromRemote::addLazyPipe(
         }
         catch (const Exception & ex)
         {
-            if (ex.code() == ErrorCodes::ALL_CONNECTION_TRIES_FAILED)
+            if (use_delayed_remote_source && ex.code() == ErrorCodes::ALL_CONNECTION_TRIES_FAILED)
                 LOG_WARNING(getLogger("ClusterProxy::SelectStreamFactory"),
                     "Connections to remote replicas of local shard {} failed, will use stale local replica", my_shard.shard_info.shard_num);
             else
@@ -543,12 +549,6 @@ void ReadFromRemote::addLazyPipe(
                 max_remote_delay = std::max(try_result.delay, max_remote_delay);
         }

-        bool use_delayed_remote_source = false;
-        fiu_do_on(FailPoints::use_delayed_remote_source,
-        {
-            use_delayed_remote_source = true;
-        });
-
         if (!use_delayed_remote_source)
         {
             const auto replicated_storage = std::dynamic_pointer_cast<StorageReplicatedMergeTree>(my_storage);
```

</details>

But, the question is, why it fails with `remoteSecure`? The reason is that in fiddle we don't have SSL configured so it fails, but on CI we do, it should not fail there.

One more question, if the server is not available on that port, why it does not fail during trying to obtain the table structure (in `getStructureOfRemoteTable()`), this is due to `isLocal` check, which returns `true` and clickhouse does not goes via TCP, it simply execute query internally (`DESC table`) - https://github.com/ClickHouse/ClickHouse/blob/c5f370c2c4845bf659141ceb11fefbd3e3e6be02/src/Storages/getStructureOfRemoteTable.cpp#L50-L54

So, I would say that the problem is this failpoint, we need to do it only for `ReplicatedMergeTree` and ensure that all tests with it will be correct after this change.

File: tests/queries/0_stateless/03581_query_secure_delayed_remote_source.sql [hunk 3]
```diff
@@ -0,0 +1,14 @@
+-- Tags: no-parallel, no-fasttest
+-- Tag no-parallel: failpoint is used which can force DelayedSource on other tests
+-- Tag no-fasttest: fasttest is built without SSL so remoteSecure() fails
```
Comment (azat) [inline tests/queries/0_stateless/03581_query_secure_delayed_remote_source.sql]: Due to we have SSL configured in CI the test should fail, so you will likely need to write integration test for this, take a look at `tests/integration/test_unknown_column_dist_table_with_alias/test.py` as an example

File: tests/queries/0_stateless/03581_query_secure_delayed_remote_source.sql [hunk 4]
```diff
@@ -0,0 +1,15 @@
+-- Tags: no-parallel, no-fasttest, no-parallel-replicas, no-replicated-database
+-- Tag no-parallel: failpoint is used which can force DelayedSource on other tests
+-- Tag no-fasttest: fasttest is built without SSL so remoteSecure() fails
+-- Tag no-parallel-replicas: there is a different code path for parallel replicas which avoids the issue
+
+DROP TABLE IF EXISTS t0;
```
Comment (azat) [inline tests/queries/0_stateless/03581_query_secure_delayed_remote_source.sql]: BTW this can be also omitted:

```
SYSTEM ENABLE FAILPOINT use_delayed_remote_source;
SELECT count() FROM remoteSecure('localhost');
```

https://fiddle.clickhouse.com/c9cb62f3-60e5-4e03-af93-f3202e93401b

**Review by azat — CHANGES_REQUESTED** [review]

File: src/Client/MultiplexedConnections.cpp (hunk 2 above)
Comment (george-larionov) [reply src/Client/MultiplexedConnections.cpp]: Thanks for pointing me in this direction, I was looking in the wrong place. Two questions. First, did you mean to do `!use_delayed_remote_source` in the if statement? Second, is this failpoint the only time that fallback to a local replica is not possible? Is there any way to test directly for the presence of at least one replica before calling the sendQuery function?

Comment (azat) [reply src/Client/MultiplexedConnections.cpp]: >First, did you mean to do !use_delayed_remote_source in the if statement?

Actually after thinking about it more, we should do something like this

<details>

```patch
$ git di
diff --git a/src/Processors/QueryPlan/ReadFromRemote.cpp b/src/Processors/QueryPlan/ReadFromRemote.cpp
index 40e91f4e907..b5fdbe5493d 100644
--- a/src/Processors/QueryPlan/ReadFromRemote.cpp
+++ b/src/Processors/QueryPlan/ReadFromRemote.cpp
@@ -1,3 +1,4 @@
+#include <exception>
 #include <Processors/QueryPlan/ReadFromRemote.h>

 #include <Analyzer/QueryNode.h>
@@ -518,6 +519,7 @@ void ReadFromRemote::addLazyPipe(
         // In case reading from parallel replicas is allowed, lazy case is not triggered,
         // so in this case it's required to get only one connection from the pool
         std::vector<ConnectionPoolWithFailover::TryResult> try_results;
+        std::exception_ptr exception_ptr;
         try
         {
             if (my_table_func_ptr)
@@ -529,6 +531,7 @@ void ReadFromRemote::addLazyPipe(
         }
         catch (const Exception & ex)
         {
+            exception_ptr = std::current_exception();
             if (ex.code() == ErrorCodes::ALL_CONNECTION_TRIES_FAILED)
                 LOG_WARNING(getLogger("ClusterProxy::SelectStreamFactory"),
                     "Connections to remote replicas of local shard {} failed, will use stale local replica", my_shard.shard_info.shard_num);
@@ -577,6 +580,10 @@ void ReadFromRemote::addLazyPipe(
             }
         }

+
+        if (exception_ptr)
+            std::rethrow_exception(exception_ptr);
+
         std::vector<IConnectionPool::Entry> connections;
         connections.reserve(try_results.size());
         for (auto & try_result : try_results)
```

</details>

Comment (azat) [reply src/Client/MultiplexedConnections.cpp]: >Is there any way to test directly for the presence of at least one replica before calling the sendQuery function?

The connection should not be created with zero replicas (so `MultiplexedConnection::sendQuery()` should never be reached in this case), and we should check it here, the problem is this fallback to local server case, due to which we ignore errors from `pool::getMany*()`, and later do not check that we have any connections.

Comment (george-larionov) [reply src/Client/MultiplexedConnections.cpp]: Understood, this looks better to me as well

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 5]
```diff
@@ -577,6 +579,10 @@ void ReadFromRemote::addLazyPipe(
             }
         }
 
+        // We assumed when we caught this error that a local replica was available but it is not, so we rethrow it here
```
Comment (azat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp]:
```suggestion
        /// We assumed when we caught an exception during obtaining connections, that it was possible to fallback to local replica,
        /// but it turns out to be false (likely due to manual triggering of use_delayed_remote_source failpoint),
        /// so we need to rethrow exception here, to avoid creating connections with zero replicas
```

**Review by azat — APPROVED** [review]
Apart from minor comment adjustment, LGTM

P.S. I wouldn't even say that it is a bug-fix, AFAICS it is not possible to trigger this problem w/o failpoints, am I right?

**Comment by george-larionov** [comment]
> Apart from minor comment adjustment, LGTM
> 
> P.S. I wouldn't even say that it is a bug-fix, AFAICS it is not possible to trigger this problem w/o failpoints, am I right?

I guess, but isn't the failpoint supposed to model a situation that could happen in real life?

Edit: I see what you mean actually, since an actual similar error would probably be caught in the code block that the failpoint avoids. I wonder how useful is this failpoint if it avoids the actual codepath that would run in reality?

**Comment by azat** [comment]
>I wonder how useful is this failpoint if it avoids the actual codepath that would run in reality?

This one is quiestionable to me, but I think it is OK
