### PR TITLE
Parameterized view bug fix 47287 47247

### LINKED ISSUE #47287: Parameterized View incorrect substitution when parameter name is substring of column name
When the name of the parameter (in this case `i`) is present (substring) in the column being filtered related to the create view, there is an incorrect parsing of the string substitution when executing the select statement

For example ( Fiddle -> https://fiddle.clickhouse.com/8e42a8f4-d1aa-4808-a40c-38e25f837aba )
```
create table testid ( id UInt64 ) engine Memory;
insert into testid values (1),(2);
create view test_view as select * from testid where id = {i:UInt64};
select * from test_view (i=2);
```
This would result in the following error
```
Code: 10. DB::Exception: Column `i)` not found in table default.test_view (5e34b78d-0f40-45ee-8e91-a6c92530017f). (NOT_FOUND_COLUMN_IN_BLOCK) (version 23.1.3.5 (official build))
```
However, this works (https://fiddle.clickhouse.com/946a328a-8491-436e-ba8e-c2f9fe4a5ddf), where the parameter name was substituted to `s`

```
create table testid ( id UInt64 ) engine Memory;
insert into testid values (1),(2);
create view test_view as select * from testid where id = {s:UInt64};
select * from test_view (s=2);
```

Error occurs on fiddle too

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
Changelog category (leave one):
- Bug Fix 

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In parameterized view, moved parameter values to SelectQueryInfo from StorageView as it can be used by multiple queries and updated column name check to avoid issues with parameter name being substring of column name. Added a test for substring parameter name. resolves #47287 and #47247

### CODE REVIEW

File: src/Storages/StorageView.cpp [hunk 1]
```diff
@@ -266,7 +267,8 @@ String StorageView::replaceQueryParameterWithValue(const String & column_name, c
         if ((pos = name.find(parameter.first)) != std::string::npos)
         {
             auto parameter_datatype_iterator = parameter_types.find(parameter.first);
-            if (parameter_datatype_iterator != parameter_types.end())
+            size_t parameter_end = pos+parameter.first.size();
```
Comment (serxa) [inline src/Storages/StorageView.cpp:270]: to stick to the style guide
```suggestion
            size_t parameter_end = pos + parameter.first.size();
```

File: src/Storages/StorageView.cpp [hunk 2]
```diff
@@ -266,7 +267,8 @@ String StorageView::replaceQueryParameterWithValue(const String & column_name, c
...
+            if (parameter_datatype_iterator != parameter_types.end() && name.size() >= parameter_end && (name[parameter_end]==',' || name[parameter_end]==')'))
```
Comment (serxa) [inline src/Storages/StorageView.cpp:271]: to stick to the style guide
```suggestion
            if (parameter_datatype_iterator != parameter_types.end() && name.size() >= parameter_end && (name[parameter_end] == ',' || name[parameter_end] == ')'))
```

File: src/Storages/StorageView.cpp (hunk 1 above)
Comment (serxa) [reply src/Storages/StorageView.cpp:270]: I would also suggest to avoid using both `String` and `std::string` in the same file/function

File: src/Storages/StorageView.h [hunk 3]
```diff
@@ -47,20 +47,14 @@ class StorageView final : public IStorage
     static String replaceQueryParameterWithValue (const String & column_name, const NameToNameMap & parameter_values, const NameToNameMap & parameter_types);
     static String replaceValueWithQueryParameter (const String & column_name, const NameToNameMap & parameter_values);
 
-    void setParameterValues (NameToNameMap parameter_values_)
+    NameToNameMap getParameterTypes() const
```
Comment (serxa) [inline src/Storages/StorageView.h:50]: Not sure, but it looks like an unnecessary copy
```suggestion
    const NameToNameMap & getParameterTypes() const
```

Comment (SmitaRKulkarni) [reply src/Storages/StorageView.h]: addressed it

File: src/Storages/StorageView.cpp (hunk 2 above)
Comment (SmitaRKulkarni) [reply src/Storages/StorageView.cpp]: addressed it

File: src/Storages/StorageView.cpp (hunk 1 above)
Comment (SmitaRKulkarni) [reply src/Storages/StorageView.cpp]: Sorry I didnt get this, they are same right ?
https://github.com/ClickHouse/ClickHouse/blob/0d45443cb06abb8c11a3488fd795bad4e052b54e/base/base/types.h#L40

Comment (serxa) [reply src/Storages/StorageView.cpp]: Correct, but imho it is better not to mix names. It is a little bit confusing (also just about style)

**Review by serxa — APPROVED** [review]

File: src/Storages/StorageView.cpp (hunk 1 above)
Comment (SmitaRKulkarni) [reply src/Storages/StorageView.cpp]: got it. I might be refactoring some parts of parameterized view, will keep this in mind, thanks

**Comment by SmitaRKulkarni** [comment]
Integration tests - (asan/tsan) - test_replicated_merge_tree_s3_zero_copy - test is flaky - Fixed by #47547
Stateless tests (release, s3 storage) - 01300_client_save_history_when_terminated_long - #47574
