### PR TITLE
Analyzer: Rewrite SELECT query during VIEW creation

### LINKED ISSUE #75956: UNKNOWN_IDENTIFIER when using expression aliases in CREATE MATERIALIZED VIEW AS
### Describe what's wrong

When performing a CREATE VIEW or CREATE MATERIALIZED VIEW statement, if the `AS ...` clause contains an expression-alias style CTE and that alias is later referenced, ClickHouse complains of an UNKNOWN_IDENTIFIER (because it treats the identifer as a table reference).

```
CREATE MATERIALIZED VIEW myview
TO mydestination
AS WITH
    ('foo','bar') AS objects
SELECT
  'foo' as object
WHERE object IN objects
```

yields

```
Received exception from server (version 25.1.3):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown expression or table expression identifier `default.objects` in scope WITH ('foo', 'bar') AS objects SELECT 'foo' AS object WHERE object IN (default.objects). (UNKNOWN_IDENTIFIER)
(query: CREATE MATERIALIZED VIEW myview
TO mydestination
AS WITH
    ('foo','bar') AS objects
SELECT
  'foo' as object
WHERE object IN objects)
```

https://fiddle.clickhouse.com/68df16cb-5328-4ca6-9a4f-41d0fea4d81d (25.1.3.23)

This is true at HEAD as well

https://fiddle.clickhouse.com/cd3c0561-acc9-489b-a111-91590ff973ad

### Does it reproduce on the most recent release?

Yes

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix `SELECT` query rewriting during `VIEW` creation with enabled analyzer.
closes #75956

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/InterpreterCreateQuery.cpp [hunk 1]
```diff
@@ -1632,10 +1635,20 @@ BlockIO InterpreterCreateQuery::createTable(ASTCreateQuery & create)
...
-        // Expand CTE before filling default database
-        ApplyWithSubqueryVisitor(getContext()).visit(*create.select);
-        AddDefaultDatabaseVisitor visitor(getContext(), current_database);
-        visitor.visit(*create.select);
+        if (getContext()->getSettingsRef()[Setting::allow_experimental_analyzer])
+        {
+            InterpreterSelectQueryAnalyzer interpreter(create.select->clone(), getContext(), SelectQueryOptions{}.analyze());
+
+            /// Rewrite SELECT query to apply CTEs and expressions from WITH and qualify all the table expressions
+            create.set(create.select, interpreter.getQueryTree()->toAST());
```
Comment (novikd) [inline src/Interpreters/InterpreterCreateQuery.cpp:1643]: This line also leads to the `*` matcher expansion to the column list. Is it okay?

File: tests/queries/0_stateless/03359_analyzer_rewrite_view_query.sql [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+(
+    `object` String
+)
+ENGINE = MergeTree
+ORDER BY object;
+
+CREATE MATERIALIZED VIEW myview TO mydestination
+AS WITH ('foo', 'bar') AS objects
+SELECT 'foo' AS object
+WHERE object IN (objects);
```
Comment (tavplubix) [inline tests/queries/0_stateless/03359_analyzer_rewrite_view_query.sql:11]: should we also add `show create` to the test?

**Review by tavplubix — APPROVED** [review]

File: src/Interpreters/InterpreterCreateQuery.cpp (hunk 1 above)
Comment (yakov-olkhovskiy) [reply src/Interpreters/InterpreterCreateQuery.cpp:1643]: also I removed tables/joins aliasing, however it may create compatibility issues since table definition for VIEW now different - with resolved projection - they are fully qualified now...

**Comment by yakov-olkhovskiy** [comment]
...and original issue, while now works, but still awfull
```
CREATE MATERIALIZED VIEW myview
TO mydestination
AS WITH
    ('foo','bar') AS objects
SELECT
  'foo' as object
WHERE object IN objects;

SHOW CREATE TABLE myview FORMAT LineAsString;

Query id: 71068ad4-8c11-4e26-bf7d-3e74f4d9e045

CREATE MATERIALIZED VIEW default.myview TO default.mydestination
(
    `object` String
)
AS SELECT 'foo' AS object
FROM system.one
WHERE _CAST(1, 'UInt8')

```
besides now we have a pile of failing tests

@novikd I'm afraid this solution maybe not viable - maybe we need to create specialized analyzer for this?

**Comment by yakov-olkhovskiy** [comment]
@novikd I talked with @KochetovNicolai regarding this issue and we came to conclusion that this solution is incorrect - we don't want to modify SELECT query prior to view creation - query resolution need to be done only for (apparently) verification step - seems to be somewhere around `InterpreterCreateQuery::getTablePropertiesAndNormalizeCreateQuery()` - according to stack trace.
I'm taking over this PR since it's having common root with one of mine.

**Comment by yakov-olkhovskiy** [comment]
@novikd it seems we were dealing with wrong solution all along - the real issue was that `ApplyWithSubqueryVisitor` ignored Literal as CTE expression and subsequent `AddDefaultDatabaseVisitor` treated unresolved reference to this expression as a table name and qualified it with database name. Hopefully my last commit resolves this issue.
