### PR TITLE
Fix T64 codec crash when input size is not aligned to element size

### LINKED ISSUE #89282: Call to `estimateCompressionRatio('DoubleDelta, T64, ZSTD')(...)` leads to a crash
### Company or project name

_No response_

### Describe what's wrong

Call to `estimateCompressionRatio('DoubleDelta, T64, ZSTD')(value)` leads to a ClickHouse crash:

- process is terminated with exit code `139`
- queries from the clients (official Go driver) start to return error `read: connection reset by peer`

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Fiddle - https://fiddle.clickhouse.com/dc902919-23a4-447f-a441-b076df04e64a

```sql
CREATE TABLE compression_estimate_example (
    number UInt64
)
ENGINE = MergeTree()
ORDER BY number;

INSERT INTO compression_estimate_example
SELECT number FROM system.numbers LIMIT 100_000;

SELECT estimateCompressionRatio('DoubleDelta, T64, ZSTD')(number) AS estimate FROM compression_estimate_example;
```

### Expected behavior

_No response_

### Error message and/or stacktrace

```
[481c0ddc8f6c] 2025.10.31 10:39:53.190487 [ 88 ] <Fatal> BaseDaemon: ########################################
[481c0ddc8f6c] 2025.10.31 10:39:53.190544 [ 88 ] <Fatal> BaseDaemon: (version 25.11.1.836 (official build), build id: 771ABFEB91DE7030C10F59476517078738EB50A5, git hash: 94901ebfb1ef2adcebe0ac046e0900069d649386) (from thread 774) (query_id: 324fd213-8b9d-47c4-b0c6-252dfebf2009) (query: SELECT estimateCompressionRatio('DoubleDelta, T64, ZSTD')(number) AS estimate FROM compression_estimate_example;) Received signal Aborted (6)
[481c0ddc8f6c] 2025.10.31 10:39:53.190583 [ 88 ] <Fatal> BaseDaemon: 
[481c0ddc8f6c] 2025.10.31 10:39:53.190616 [ 88 ] <Fatal> BaseDaemon: Stack trace: 0x00007038755da9fd 0x0000703875586476 0x000070387556c7f3 0x0000000016ab5e66 0x0000000020b591c3 0x0000000020b591af 0x000000000cb2c65b 0x00000000145d06ea 0x0000000018415c7b 0x00000000184157fd 0x000000001aa6da89 0x000000001a7b2002 0x000000001a7a441b 0x000000001a7a8183 0x0000000013fcc2eb 0x0000000013fd3766 0x0000000013fc9212 0x0000000013fd0e9a 0x00007038755d8ac3 0x0000703875669a74
[481c0ddc8f6c] 2025.10.31 10:39:53.190668 [ 88 ] <Fatal> BaseDaemon: 2. ? @ 0x00000000000969fd
[481c0ddc8f6c] 2025.10.31 10:39:53.190700 [ 88 ] <Fatal> BaseDaemon: 3. ? @ 0x0000000000042476
[481c0ddc8f6c] 2025.10.31 10:39:53.190731 [ 88 ] <Fatal> BaseDaemon: 4. ? @ 0x00000000000287f3
[481c0ddc8f6c] 2025.10.31 10:39:53.190783 [ 88 ] <Fatal> BaseDaemon: 5. terminate_handler() @ 0x0000000016ab5e66
[481c0ddc8f6c] 2025.10.31 10:39:53.190829 [ 88 ] <Fatal> BaseDaemon: 6. std::__terminate(void (*)()) @ 0x0000000020b591c3
[481c0ddc8f6c] 2025.10.31 10:39:53.190865 [ 88 ] <Fatal> BaseDaemon: 7. std::terminate() @ 0x0000000020b591af
[481c0ddc8f6c] 2025.10.31 10:39:53.190897 [ 88 ] <Fatal> BaseDaemon: 8. ? @ 0x000000000cb2c65b
[481c0ddc8f6c] 2025.10.31 10:39:53.190925 [ 88 ] <Fatal> BaseDaemon: 9. ? @ 0x00000000145d06ea
[481c0ddc8f6c] 2025.10.31 10:39:53.190978 [ 88 ] <Fatal> BaseDaemon: 10. void DB::Aggregator::insertAggregatesIntoColumns<char*>(char*&, std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::Arena*) const @ 0x0000000018415c7b
[481c0ddc8f6c] 2025.10.31 10:39:53.191014 [ 88 ] <Fatal> BaseDaemon: 11. DB::Aggregator::prepareBlockAndFillWithoutKey(DB::AggregatedDataVariants&, bool, bool) const @ 0x00000000184157fd
[481c0ddc8f6c] 2025.10.31 10:39:53.191042 [ 88 ] <Fatal> BaseDaemon: 12. DB::ConvertingAggregatedToChunksTransform::work() @ 0x000000001aa6da89
[481c0ddc8f6c] 2025.10.31 10:39:53.191080 [ 88 ] <Fatal> BaseDaemon: 13. DB::ExecutionThreadContext::executeTask() @ 0x000000001a7b2002
[481c0ddc8f6c] 2025.10.31 10:39:53.191121 [ 88 ] <Fatal> BaseDaemon: 14. DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001a7a441b
[481c0ddc8f6c] 2025.10.31 10:39:53.191167 [ 88 ] <Fatal> BaseDaemon: 15. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001a7a8183
[481c0ddc8f6c] 2025.10.31 10:39:53.191202 [ 88 ] <Fatal> BaseDaemon: 16. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000013fcc2eb
[481c0ddc8f6c] 2025.10.31 10:39:53.191239 [ 88 ] <Fatal> BaseDaemon: 17. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013fd3766
[481c0ddc8f6c] 2025.10.31 10:39:53.191280 [ 88 ] <Fatal> BaseDaemon: 18. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013fc9212
[481c0ddc8f6c] 2025.10.31 10:39:53.191311 [ 88 ] <Fatal> BaseDaemon: 19. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000013fd0e9a
[481c0ddc8f6c] 2025.10.31 10:39:53.191361 [ 88 ] <Fatal> BaseDaemon: 20. ? @ 0x0000000000094ac3
[481c0ddc8f6c] 2025.10.31 10:39:53.191399 [ 88 ] <Fatal> BaseDaemon: 21. ? @ 0x0000000000125a74
[481c0ddc8f6c] 2025.10.31 10:39:53.365753 [ 88 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: C8DE168912130AECDD584BD5CF021329)
[481c0ddc8f6c] 2025.10.31 10:39:53.941864 [ 88 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[481c0ddc8f6c] 2025.10.31 10:39:53.942171 [ 88 ] <Fatal> BaseDaemon: Changed settings: output_format_pretty_color = 0, output_format_pretty_grid_charset = 'ASCII'
[481c0ddc8f6c] 2025.10.31 10:39:57.190567 [ 88 ] <Fatal> BaseDaemon: ########################################
[481c0ddc8f6c] 2025.10.31 10:39:57.190587 [ 88 ] <Fatal> BaseDaemon: (version 25.11.1.836 (official build), build id: 771ABFEB91DE7030C10F59476517078738EB50A5, git hash: 94901ebfb1ef2adcebe0ac046e0900069d649386) (from thread 774) (query_id: 324fd213-8b9d-47c4-b0c6-252dfebf2009) (query: SELECT estimateCompressionRatio('DoubleDelta, T64, ZSTD')(number) AS estimate FROM compression_estimate_example;) Received signal Segmentation fault (11)
[481c0ddc8f6c] 2025.10.31 10:39:57.190602 [ 88 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[481c0ddc8f6c] 2025.10.31 10:39:57.190626 [ 88 ] <Fatal> BaseDaemon: Stack trace: 0x000070387556c899 0x0000000016ab5e66 0x0000000020b591c3 0x0000000020b591af 0x000000000cb2c65b 0x00000000145d06ea 0x0000000018415c7b 0x00000000184157fd 0x000000001aa6da89 0x000000001a7b2002 0x000000001a7a441b 0x000000001a7a8183 0x0000000013fcc2eb 0x0000000013fd3766 0x0000000013fc9212 0x0000000013fd0e9a 0x00007038755d8ac3 0x0000703875669a74
[481c0ddc8f6c] 2025.10.31 10:39:57.190667 [ 88 ] <Fatal> BaseDaemon: 2. ? @ 0x0000000000028899
[481c0ddc8f6c] 2025.10.31 10:39:57.190709 [ 88 ] <Fatal> BaseDaemon: 3. terminate_handler() @ 0x0000000016ab5e66
[481c0ddc8f6c] 2025.10.31 10:39:57.190739 [ 88 ] <Fatal> BaseDaemon: 4. std::__terminate(void (*)()) @ 0x0000000020b591c3
[481c0ddc8f6c] 2025.10.31 10:39:57.190766 [ 88 ] <Fatal> BaseDaemon: 5. std::terminate() @ 0x0000000020b591af
[481c0ddc8f6c] 2025.10.31 10:39:57.190793 [ 88 ] <Fatal> BaseDaemon: 6. ? @ 0x000000000cb2c65b
[481c0ddc8f6c] 2025.10.31 10:39:57.190819 [ 88 ] <Fatal> BaseDaemon: 7. ? @ 0x00000000145d06ea
[481c0ddc8f6c] 2025.10.31 10:39:57.190854 [ 88 ] <Fatal> BaseDaemon: 8. void DB::Aggregator::insertAggregatesIntoColumns<char*>(char*&, std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::Arena*) const @ 0x0000000018415c7b
[481c0ddc8f6c] 2025.10.31 10:39:57.190881 [ 88 ] <Fatal> BaseDaemon: 9. DB::Aggregator::prepareBlockAndFillWithoutKey(DB::AggregatedDataVariants&, bool, bool) const @ 0x00000000184157fd
[481c0ddc8f6c] 2025.10.31 10:39:57.190914 [ 88 ] <Fatal> BaseDaemon: 10. DB::ConvertingAggregatedToChunksTransform::work() @ 0x000000001aa6da89
[481c0ddc8f6c] 2025.10.31 10:39:57.190942 [ 88 ] <Fatal> BaseDaemon: 11. DB::ExecutionThreadContext::executeTask() @ 0x000000001a7b2002
[481c0ddc8f6c] 2025.10.31 10:39:57.190971 [ 88 ] <Fatal> BaseDaemon: 12. DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001a7a441b
[481c0ddc8f6c] 2025.10.31 10:39:57.191004 [ 88 ] <Fatal> BaseDaemon: 13. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001a7a8183
[481c0ddc8f6c] 2025.10.31 10:39:57.191030 [ 88 ] <Fatal> BaseDaemon: 14. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000013fcc2eb
[481c0ddc8f6c] 2025.10.31 10:39:57.191069 [ 88 ] <Fatal> BaseDaemon: 15. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013fd3766
[481c0ddc8f6c] 2025.10.31 10:39:57.191104 [ 88 ] <Fatal> BaseDaemon: 16. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013fc9212
[481c0ddc8f6c] 2025.10.31 10:39:57.191148 [ 88 ] <Fatal> BaseDaemon: 17. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000013fd0e9a
[481c0ddc8f6c] 2025.10.31 10:39:57.191192 [ 88 ] <Fatal> BaseDaemon: 18. ? @ 0x0000000000094ac3
[481c0ddc8f6c] 2025.10.31 10:39:57.191231 [ 88 ] <Fatal> BaseDaemon: 19. ? @ 0x0000000000125a74
[481c0ddc8f6c] 2025.10.31 10:39:57.364096 [ 88 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: C8DE168912130AECDD584BD5CF021329)
[481c0ddc8f6c] 2025.10.31 10:39:57.679780 [ 88 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[481c0ddc8f6c] 2025.10.31 10:39:57.680066 [ 88 ] <Fatal> BaseDaemon: Changed settings: output_format_pretty_color = 0, output_format_pretty_grid_charset = 'ASCII'
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ylw510**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `Fatal` when compressing data with size not aligned to element size (in T64 codec). Resolves #89282

### Details

Resolves #89282

### CODE REVIEW

**Comment by thevar1able** [comment]
Thank you for your contribution!
Could you please add a unit test? See `src/Compression/tests/gtest_compressionCodec.cpp`.

**Comment by ylw510** [comment]
> Thank you for your contribution! Could you please add a unit test? See `src/Compression/tests/gtest_compressionCodec.cpp`.

Done.

**Review by thevar1able — APPROVED** [review]

**Comment by thevar1able** [comment]
@ylw510 please take a look at MSan report in unit tests

```
[2025-11-07 01:05:21] ==27==WARNING: MemorySanitizer: use-of-uninitialized-value
[2025-11-07 01:05:21] [Detaching after fork from child process 12428]
[2025-11-07 01:05:22]     #0 0x5555a89c9503 in DB::(anonymous namespace)::getValuableBitsNumber(long, long) ci/tmp/build/./src/Compression/CompressionCodecT64.cpp:463:17
[2025-11-07 01:05:22]     #1 0x5555a89c9503 in unsigned int DB::(anonymous namespace)::compressData<short, false>(char const*, unsigned int, char*) ci/tmp/build/./src/Compression/CompressionCodecT64.cpp:523:23
[2025-11-07 01:05:22]     #2 0x5555a89c9503 in unsigned int DB::(anonymous namespace)::compressData<short>(char const*, unsigned int, char*, DB::CompressionCodecT64::Variant) ci/tmp/build/./src/Compression/CompressionCodecT64.cpp:644:12
[2025-11-07 01:05:22]     #3 0x5555a89c9503 in DB::CompressionCodecT64::doCompressData(char const*, unsigned int, char*) const ci/tmp/build/./src/Compression/CompressionCodecT64.cpp:669:24
[2025-11-07 01:05:22]     #4 0x5555a8ac39f4 in DB::ICompressionCodec::compress(char const*, unsigned int, char*) const ci/tmp/build/./src/Compression/ICompressionCodec.cpp:95:39
[2025-11-07 01:05:22]     #5 0x55555f8a0650 in (anonymous namespace)::T64Test_TranscodeRawInput_Test::TestBody() ci/tmp/build/./src/Compression/tests/gtest_compressionCodec.cpp:1398:38
[2025-11-07 01:05:22]     #6 0x55557d8e5538 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2653:10
[2025-11-07 01:05:22]     #7 0x55557d8e5538 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2689:14
[2025-11-07 01:05:22]     #8 0x55557d8e5170 in testing::Test::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2728:5
[2025-11-07 01:05:22]     #9 0x55557d8e83bd in testing::TestInfo::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2874:11
[2025-11-07 01:05:22]     #10 0x55557d8eb8dd in testing::TestSuite::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:3052:30
[2025-11-07 01:05:22]     #11 0x55557d92761b in testing::internal::UnitTestImpl::RunAllTests() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:5982:44
[2025-11-07 01:05:22]     #12 0x55557d9264f8 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2653:10
[2025-11-07 01:05:22]     #13 0x55557d9264f8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2689:14
[2025-11-07 01:05:22]     #14 0x55557d92612f in testing::UnitTest::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:5561:10
[2025-11-07 01:05:22]     #15 0x55555f54df64 in RUN_ALL_TESTS() ci/tmp/build/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
[2025-11-07 01:05:22]     #16 0x55555f54df64 in main ci/tmp/build/./src/Common/tests/gtest_main.cpp:17:12
[2025-11-07 01:05:22]     #17 0x7ffff7da8d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 4f7b0c955c3d81d7cac1501a2498b69d1d82bfe7)
[2025-11-07 01:05:22]     #18 0x7ffff7da8e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 4f7b0c955c3d81d7cac1501a2498b69d1d82bfe7)
[2025-11-07 01:05:22]     #19 0x55555eaab7ed in _start (/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/unit_tests_dbms+0x95577ed) (BuildId: 75361b4e828a0383eb8bb5dfb9dbd2c795ca5ff9)
[2025-11-07 01:05:22] 
[2025-11-07 01:05:22]   Uninitialized value was created by a heap allocation
[2025-11-07 01:05:22]     #0 0x55555eada632 in malloc (/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/unit_tests_dbms+0x9586632) (BuildId: 75361b4e828a0383eb8bb5dfb9dbd2c795ca5ff9)
[2025-11-07 01:05:22]     #1 0x5555aaefaef8 in void* (anonymous namespace)::allocNoTrack<false, false>(unsigned long, unsigned long) ci/tmp/build/./src/Common/Allocator.cpp:86:19
[2025-11-07 01:05:22]     #2 0x5555aaefaef8 in Allocator<false, false>::alloc(unsigned long, unsigned long) ci/tmp/build/./src/Common/Allocator.cpp:133:18
[2025-11-07 01:05:22]     #3 0x55555f89ff43 in DB::Memory<Allocator<false, false>>::alloc(unsigned long) ci/tmp/build/./src/IO/BufferWithOwnMemory.h:135:49
[2025-11-07 01:05:22]     #4 0x55555f89ff43 in DB::Memory<Allocator<false, false>>::resize(unsigned long, bool) ci/tmp/build/./src/IO/BufferWithOwnMemory.h:84:13
[2025-11-07 01:05:22]     #5 0x55555f89ff43 in (anonymous namespace)::T64Test_TranscodeRawInput_Test::TestBody() ci/tmp/build/./src/Compression/tests/gtest_compressionCodec.cpp:1388:27
[2025-11-07 01:05:22]     #6 0x55557d8e5538 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2653:10
[2025-11-07 01:05:22]     #7 0x55557d8e5538 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2689:14
[2025-11-07 01:05:22]     #8 0x55557d8e5170 in testing::Test::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2728:5
[2025-11-07 01:05:22]     #9 0x55557d8e83bd in testing::TestInfo::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2874:11
[2025-11-07 01:05:22]     #10 0x55557d8eb8dd in testing::TestSuite::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:3052:30
[2025-11-07 01:05:22]     #11 0x55557d92761b in testing::internal::UnitTestImpl::RunAllTests() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:5982:44
[2025-11-07 01:05:22]     #12 0x55557d9264f8 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2653:10
[2025-11-07 01:05:22]     #13 0x55557d9264f8 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:2689:14
[2025-11-07 01:05:22]     #14 0x55557d92612f in testing::UnitTest::Run() ci/tmp/build/./contrib/googletest/googletest/src/gtest.cc:5561:10
[2025-11-07 01:05:22]     #15 0x55555f54df64 in RUN_ALL_TESTS() ci/tmp/build/./contrib/googletest/googletest/include/gtest/gtest.h:2334:73
[2025-11-07 01:05:22]     #16 0x55555f54df64 in main ci/tmp/build/./src/Common/tests/gtest_main.cpp:17:12
[2025-11-07 01:05:22]     #17 0x7ffff7da8d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 4f7b0c955c3d81d7cac1501a2498b69d1d82bfe7)
[2025-11-07 01:05:22] 
[2025-11-07 01:05:23] SUMMARY: MemorySanitizer: use-of-uninitialized-value ci/tmp/build/./src/Compression/CompressionCodecT64.cpp:463:17 in DB::(anonymous namespace)::getValuableBitsNumber(long, long)
[2025-11-07 01:05:23] Exiting
[2025-11-07 01:05:23] [Inferior 1 (process 27) exited with code 01]
[2025-11-07 01:05:23] No stack.
[2025-11-07 01:05:23] ERROR: No test result file [/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/gtest.json]
```

File: src/Compression/CompressionCodecT64.cpp
Comment (thevar1able) [inline src/Compression/CompressionCodecT64.cpp:477]: In a case when `bytes_size` == 1 in `compressData`, and `sizeof(T)` > 1, we're reading uninitialized memory.

Comment (ylw510) [reply src/Compression/CompressionCodecT64.cpp:477]: Thanks for the reminders. By the way, could you tell me what the `cmake` option is to reproduce this problem? I didn't find the relevant option(`ASAN`) in the top-level `CMakeLists.txt`

Comment (thevar1able) [reply src/Compression/CompressionCodecT64.cpp:477]: `-DSANITIZE=memory`

File: src/Compression/CompressionCodecT64.cpp [hunk 1]
```diff
@@ -504,6 +504,12 @@ UInt32 compressData(const char * src, UInt32 bytes_size, char * dst)
     src += bytes_to_skip;
     dst += bytes_to_skip;
 
+    if (bytes_size % sizeof(T) != 0)
+        throw Exception(ErrorCodes::CANNOT_COMPRESS, "Cannot compress with T64 codec, data size {} is not aligned to {}", bytes_size, sizeof(T));
+
+    if (bytes_size == 0)
+        return header_size + bytes_to_skip;
```
Comment (thevar1able) [inline src/Compression/CompressionCodecT64.cpp]: I think we don't actually write the header in this case.
Makes sense to throw `LOGICAL_ERROR` here, as compressing a buffer of size 0 is definitely not expected.

File: src/Compression/CompressionCodecT64.cpp [hunk 2]
```diff
@@ -10,8 +10,6 @@
 #include <IO/WriteHelpers.h>
 #include <Core/Types.h>
 #include <bit>
-
```
Comment (thevar1able) [inline src/Compression/CompressionCodecT64.cpp:13]: Undo this change please.

File: src/Compression/CompressionCodecT64.cpp (hunk 1 above)
Comment (ylw510) [reply src/Compression/CompressionCodecT64.cpp]: Done.

File: src/Compression/CompressionCodecT64.cpp (hunk 2 above)
Comment (ylw510) [reply src/Compression/CompressionCodecT64.cpp:13]: Done.

**Review by thevar1able — APPROVED** [review]

File: src/Compression/CompressionCodecT64.cpp [hunk 3]
```diff
@@ -500,14 +499,21 @@ UInt32 compressData(const char * src, UInt32 bytes_size, char * dst)
     static constexpr const UInt32 matrix_size = 64;
     static constexpr const UInt32 header_size = 2 * sizeof(UInt64);
 
-    if (bytes_size % sizeof(T))
-        throw Exception(ErrorCodes::CANNOT_COMPRESS, "Cannot compress with T64 codec, data size {} is not multiplier of {}",
-                        bytes_size, sizeof(T));
+    UInt8 bytes_to_skip = bytes_size % sizeof(T);
+    bytes_size -= bytes_to_skip;
+    memcpy(dst, src, bytes_to_skip);
```
Comment (4ertus2) [inline src/Compression/CompressionCodecT64.cpp:504]: Is it a forward-backward incompatible change in codec? Could older CH decompress the data compressed by newer `compressData` and vice versa?

I think it's better to copy `bytes_to_skip` of src's tail instead.

Comment (thevar1able) [reply src/Compression/CompressionCodecT64.cpp:504]: It does not look backward compatible (old version won't be able to read data compressed by a newer version), but should be forward compatible (new version will be able to read data compressed by an old version).

File: src/Compression/CompressionCodecT64.cpp [hunk 4]
```diff
@@ -500,14 +499,21 @@ UInt32 compressData(const char * src, UInt32 bytes_size, char * dst)
...
+    src += bytes_to_skip;
+    dst += bytes_to_skip;
+
+    if (bytes_size % sizeof(T) != 0)
```
Comment (thevar1able) [inline src/Compression/CompressionCodecT64.cpp]: This check looks meaningless, as we've just subtracted `bytes_size % sizeof(T)` from `bytes_size` on L503.

File: src/Compression/CompressionCodecT64.cpp [hunk 5]
```diff
@@ -500,14 +499,21 @@ UInt32 compressData(const char * src, UInt32 bytes_size, char * dst)
...
+        throw Exception(ErrorCodes::CANNOT_COMPRESS, "Cannot compress with T64 codec, data size {} is not aligned to {}", bytes_size, sizeof(T));
+
+    if (bytes_size == 0)
```
Comment (thevar1able) [inline src/Compression/CompressionCodecT64.cpp:508]: Let's just return buffer with the skipped bytes in this case, with no T64 compression header.

File: src/Compression/tests/gtest_compressionCodec.cpp [hunk 6]
```diff
@@ -1367,4 +1367,84 @@ TEST(DoubleDeltaTest, TranscodeRawInput)
...
+                ASSERT_EQ(memory_for_decompression.data()[i], source_memory.data()[i]) << "with data type " << type->getName() << " with buffer size " << buffer_size << " at position " << i;
+        }
+    }
+}
+
+TEST(T64Test, CompressZeroBufferThrows)
+{
+#ifdef DEBUG_OR_SANITIZER_BUILD
+    GTEST_SKIP() << "this test trigger LOGICAL_ERROR, runs only if DEBUG_OR_SANITIZER_BUILD is not defined";
+#else
```
Comment (thevar1able) [inline src/Compression/tests/gtest_compressionCodec.cpp]: And this exclusion should not be required after https://github.com/ClickHouse/ClickHouse/pull/89432/files#r2518442617.

File: src/Compression/CompressionCodecT64.cpp (hunk 4 above)
Comment (ylw510) [reply src/Compression/CompressionCodecT64.cpp]: I think so, too. But I see that other compression algorithms also have similar checks.
Like: Delta / Gorilla https://github.com/ClickHouse/ClickHouse/blob/50a1977b668a67d31dbef6fa011b61666717fc57/src/Compression/CompressionCodecDelta.cpp#L75
https://github.com/ClickHouse/ClickHouse/blob/50a1977b668a67d31dbef6fa011b61666717fc57/src/Compression/CompressionCodecGorilla.cpp#L205

File: src/Compression/CompressionCodecT64.cpp (hunk 5 above)
Comment (ylw510) [reply src/Compression/CompressionCodecT64.cpp:508]: You are right.

File: src/Compression/tests/gtest_compressionCodec.cpp (hunk 6 above)
Comment (ylw510) [reply src/Compression/tests/gtest_compressionCodec.cpp]: > And this exclusion should not be required after https://github.com/ClickHouse/ClickHouse/pull/89432/files#r2518442617.

```
TEST(T64Test, TranscodeRawInput)
{
    std::vector<DataTypePtr> types = {
        std::make_shared<DataTypeInt8>(),
        std::make_shared<DataTypeInt16>(),
        std::make_shared<DataTypeInt32>(),
        std::make_shared<DataTypeInt64>(),
        std::make_shared<DataTypeUInt8>(),
        std::make_shared<DataTypeUInt16>(),
        std::make_shared<DataTypeUInt32>(),
        std::make_shared<DataTypeUInt64>(),
    };

    for (const auto & type : types)
    {
        for (size_t buffer_size = 8; buffer_size < 2000; buffer_size++)
        {
            DB::Memory<> source_memory;
            source_memory.resize(buffer_size);

            for (size_t i = 0; i < buffer_size; ++i)
                source_memory.data()[i] = i;

            DB::Memory<> memory_for_compression;
            auto codec = makeCodec("T64", type);

            memory_for_compression.resize(codec->getCompressedReserveSize(buffer_size));

            auto compressed = codec->compress(source_memory.data(), UInt32(source_memory.size()), memory_for_compression.data());

            DB::Memory<> memory_for_decompression;
            memory_for_decompression.resize(buffer_size);
            auto decompressed = codec->decompress(memory_for_compression.data(), compressed, memory_for_decompression.data());

            ASSERT_EQ(decompressed, source_memory.size());
            for (size_t i = 0; i < decompressed; ++i)
                ASSERT_EQ(memory_for_decompression.data()[i], source_memory.data()[i]) << "with data type " << type->getName() << " with buffer size " << buffer_size << " at position " << i;
        }
    }
}

TEST(T64Test, CompressZeroBufferThrows)
{
#ifdef DEBUG_OR_SANITIZER_BUILD
    GTEST_SKIP() << "this test trigger LOGICAL_ERROR, runs only if DEBUG_OR_SANITIZER_BUILD is not defined";
#else
    std::vector<DataTypePtr> types = {
        std::make_shared<DataTypeInt8>(),
        std::make_shared<DataTypeInt16>(),
        std::make_shared<DataTypeInt32>(),
        std::make_shared<DataTypeInt64>(),
        std::make_shared<DataTypeUInt8>(),
        std::make_shared<DataTypeUInt16>(),
        std::make_shared<DataTypeUInt32>(),
        std::make_shared<DataTypeUInt64>(),
    };

    for (const auto & type : types)
    {
        // If the buffer size is 0, 'assert(source != nullptr && dest != nullptr);' will be triggered
        // in ICompressionCodec::compress(const char * source, UInt32 source_size, char * dest)
        for (size_t buffer_size = 1; buffer_size < type->getSizeOfValueInMemory(); buffer_size++)
        {
            DB::Memory<> source_memory;
            source_memory.resize(buffer_size);

            for (size_t i = 0; i < buffer_size; ++i)
                source_memory.data()[i] = i;

            DB::Memory<> memory_for_compression;
            auto codec = makeCodec("T64", type);

            memory_for_compression.resize(codec->getCompressedReserveSize(buffer_size));

            ASSERT_THROW(codec->compress(source_memory.data(), UInt32(source_memory.size()), memory_for_compression.data()), Exception);
        }
    }
#endif
}
```
Perhaps later we can merge the two unit tests into one. The specific content of the new unit test can be（Just change the `buffer_size` from `8` to `1`）:
```
TEST(T64Test, TranscodeRawInput)
{
    std::vector<DataTypePtr> types = {
        std::make_shared<DataTypeInt8>(),
        std::make_shared<DataTypeInt16>(),
        std::make_shared<DataTypeInt32>(),
        std::make_shared<DataTypeInt64>(),
        std::make_shared<DataTypeUInt8>(),
        std::make_shared<DataTypeUInt16>(),
        std::make_shared<DataTypeUInt32>(),
        std::make_shared<DataTypeUInt64>(),
    };

    for (const auto & type : types)
    {
        for (size_t buffer_size = 1; buffer_size < 2000; buffer_size++)
        {
            DB::Memory<> source_memory;
            source_memory.resize(buffer_size);

            for (size_t i = 0; i < buffer_size; ++i)
                source_memory.data()[i] = i;

            DB::Memory<> memory_for_compression;
            auto codec = makeCodec("T64", type);

            memory_for_compression.resize(codec->getCompressedReserveSize(buffer_size));

            auto compressed = codec->compress(source_memory.data(), UInt32(source_memory.size()), memory_for_compression.data());

            DB::Memory<> memory_for_decompression;
            memory_for_decompression.resize(buffer_size);
            auto decompressed = codec->decompress(memory_for_compression.data(), compressed, memory_for_decompression.data());

            ASSERT_EQ(decompressed, source_memory.size());
            for (size_t i = 0; i < decompressed; ++i)
                ASSERT_EQ(memory_for_decompression.data()[i], source_memory.data()[i]) << "with data type " << type->getName() << " with buffer size " << buffer_size << " at position " << i;
        }
    }
}
```

File: src/Compression/CompressionCodecT64.cpp (hunk 4 above)
Comment (thevar1able) [reply src/Compression/CompressionCodecT64.cpp]: Yep, but in the beginning of a separate method, as a sanity check.
I mean, it does not hurt to have it here, but it just makes no sense.

Comment (ylw510) [reply src/Compression/CompressionCodecT64.cpp]: Done.

File: src/Compression/tests/gtest_compressionCodec.cpp (hunk 6 above)
Comment (ylw510) [reply src/Compression/tests/gtest_compressionCodec.cpp]: Done.

**Review by thevar1able — APPROVED** [review]

**Comment by thevar1able** [comment]
>[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=89432&sha=0d1b991d6432d2046a3774c1ea30d9892a5af87a&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)

https://github.com/ClickHouse/ClickHouse/issues/90002

**Comment by thevar1able** [comment]
>test_storage_s3_queue/test_parallel_inserts.py::test_parallel_inserts_with_failures[1]

https://github.com/ClickHouse/ClickHouse/issues/88931
