### PR TITLE
Binary math functions Decimal support

### LINKED ISSUE #51073: use decimal type with pow function
hello,

version 23.5.2

`SELECT pow(toDecimal32(2, 2), 3)`

produce DB::Exception: Illegal type Decimal(9, 2) of argument of function pow: While processing pow(toDecimal32(2, 2), 3). (ILLEGAL_TYPE_OF_ARGUMENT)

thanks a lot

### PR DESCRIPTION
**Pull request by mgorshkov**
Closes #51073

Binary math functions now support Decimals as arguments

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Support decimal arguments in binary math functions (pow(), atan2(), max2, min2(), hypot()

### Documentation entry for user-facing changes

- [X] Documentation is written (mandatory for new features)

- Motivation: This enhancement allows using decimals as arguments of binary functions without cast. The cast is done inside the implementation.

- Parameters: Decimals as arguments of binary math functions.

- Example use: SELECT pow(toDecimal32(2, 2), 3)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>CI Settings</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step
- [ ]  Allow: Integration Tests
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Unit tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All with aarch64
- [ ]  Allow: All with ASAN
- [ ]  Allow: All with TSAN
- [ ]  Allow: All with Analyzer
- [ ]  Allow: All with Azure
- [ ]  Allow: Add your option here
---
- [ ]  Exclude: Fast test
- [ ]  Exclude: Integration Tests
- [ ]  Exclude: Stateless tests
- [ ]  Exclude: Stateful tests
- [ ]  Exclude: Performance tests
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN
- [ ]  Exclude: All with MSAN
- [ ]  Exclude: All with UBSAN
- [ ]  Exclude: All with Coverage
- [ ]  Exclude: All with Aarch64
---
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)
- [ ]  allow: batch 1 for multi-batch jobs
- [ ]  allow: batch 2
- [ ]  allow: batch 3
- [ ]  allow: batch 4, 5 and 6
</details>

### CODE REVIEW

**Comment by Algunenano** [comment]
As I told in the issue: Adding an autocast now and retuning Float64 means that whenever we do it correctly we will require a breaking change. Please try implementing correctly the first time.

**Comment by rvasin** [comment]
@Algunenano what do you mean? 

Do you mean that if at least one of two arguments are decimal then the result should be decimal? 

If so then as power engine I see two variants:

1. Use C function `double pow(double, double)` which will make the calculation. 
2. Implement own calculation "decimal arithmetic" engine for power function?

Please explain.

**Comment by Algunenano** [comment]
> Please explain.

I already did in https://github.com/ClickHouse/ClickHouse/issues/51073. But to clarify, pow(Decimal, other) should return Decimal of adapted precision, same as we do with multiplication.

**Comment by rvasin** [comment]
I have made some experiments with multiplication:


```
0077ef892331 :) select toDecimal32(2.123, 2) as x, toDecimal32(3.123456, 3) as y, x * y as z, toTypeName(z)


SELECT
    toDecimal32(2.123, 2) AS x,
    toDecimal32(3.123456, 3) AS y,
    x * y AS z,
    toTypeName(z)

Query id: 94ec50d8-293e-48ca-a05d-cd335c5a559c

┌────x─┬─────y─┬───────z─┬─toTypeName(multiply(toDecimal32(2.123, 2), toDecimal32(3.123456, 3)))─┐
│ 2.12 │ 3.123 │ 6.62076 │ Decimal(9, 5)                                                         │
└──────┴───────┴─────────┴───────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

0077ef892331 :) select 2.123 as x, toDecimal32(3.123456, 3) as y, x * y as z, toTypeName(z)

SELECT
    2.123 AS x,
    toDecimal32(3.123456, 3) AS y,
    x * y AS z,
    toTypeName(z)

Query id: 75d2b963-c78e-4d83-b029-9ba6e56d4bb4

┌─────x─┬─────y─┬─────────────────z─┬─toTypeName(multiply(2.123, toDecimal32(3.123456, 3)))─┐
│ 2.123 │ 3.123 │ 6.630129000000001 │ Float64                                               │
└───────┴───────┴───────────────────┴───────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

0077ef892331 :) select toDecimal32(2.123, 2) as x, 3.123456  as y, x * y as z, toTypeName(z)

SELECT
    toDecimal32(2.123, 2) AS x,
    3.123456 AS y,
    x * y AS z,
    toTypeName(z)

Query id: ac480172-964b-4ec6-909c-bfa45d0286b2

┌────x─┬────────y─┬─────────────────z─┬─toTypeName(multiply(toDecimal32(2.123, 2), 3.123456))─┐
│ 2.12 │ 3.123456 │ 6.621726720000001 │ Float64                                               │
└──────┴──────────┴───────────────────┴───────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

So only if both arguments are decimal we return the result of type decimal. 
Please confirm.

Second: what is the resulting precision? What do you think?

In case of multiplication example above the precision of result is 2+3=5. Should we use the same for `pow`?

Third: still cannot understand it from previous messages (I read again the messages in the issue). 
Is it OK that we use `double pow(double, double)` "calculation engine" as it's used now in ClickHouse for `pow` function?

**Comment by mgorshkov** [comment]
https://play.clickhouse.com/play?user=play#c2VsZWN0IHRvRGVjaW1hbDMyKDIuMTIzLCAzKSBhcyB4LCB0b0RlY2ltYWwzMigzLjEyMzQ1NiwgNikgIGFzIHksIG11bHRpcGx5RGVjaW1hbCh4LCB5KSBhcyB6LCB0b1R5cGVOYW1lKHop

If the first argument is decimal, and the second is any integer (or, ex, whole float, whole decimal etc), we can return decimal with enhanced precision, by multiplying same decimals through MultiplyDecimalsImpl::execute.

@Algunenano will this implementation be ok?

**Comment by rvasin** [comment]
I also see that multiplication of int by decimal returns decimal:

```
0077ef892331 :) select 2 as x, toDecimal32(3.123456, 3) as y, x * y as z, toTypeName(z)

SELECT
    2 AS x,
    toDecimal32(3.123456, 3) AS y,
    x * y AS z,
    toTypeName(z)

Query id: 6fe273f2-a5be-4411-99eb-0fe5313d7f75

┌─x─┬─────y─┬─────z─┬─toTypeName(multiply(2, toDecimal32(3.123456, 3)))─┐
│ 2 │ 3.123 │ 6.246 │ Decimal(9, 3)                                     │
└───┴───────┴───────┴───────────────────────────────────────────────────┘
```

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 1ea60697122e8fe3986aba507fe2b3e509d632eb with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64582/1ea60697122e8fe3986aba507fe2b3e509d632eb/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
Ok to test it even if the implementation is concerning.

**Comment by rvasin** [comment]
@Algunenano OK. I repeat the questions:

Just for `pow` function for which combinations of arguments which type of result do we need to use with which precision and while "calculation engine should we use".

Probably it's better to fill the answers into the table:

| Argument 1 Type  | Argument 1 Type   | Calc Engine  | Result Type  |  Result Precision  |
|---|---|---|---|---|
| int  | decimal |  |  |  |
| decimal | int |  |  |  |
| float | decimal  |  |  |  |
| decimal | float  |  |  |  |
| decimal | decimal  |  |  |  |

(I don''t cover existing combinations of arguments like float float).

File: src/Functions/FunctionMathBinaryFloat64.h [hunk 1]
```diff
@@ -53,35 +53,89 @@ class FunctionMathBinaryFloat64 : public IFunction
...
 
     template <typename LeftType, typename RightType>
-    ColumnPtr executeTyped(const ColumnConst * left_arg, const IColumn * right_arg) const
+    static void executeInIterations(const LeftType * left_src_data, size_t left_src_size, const RightType * right_src_data, size_t right_src_size, Float64 * dst_data)
     {
-        if (const auto right_arg_typed = checkAndGetColumn<ColumnVector<RightType>>(right_arg))
+        if (left_src_size == 0 || right_src_size == 0)
+            return; // empty column (ex, for dry run)
+
+        const auto left_rows_remaining = left_src_size % Impl::rows_per_iteration;
```
Comment (alexey-milovidov) [inline src/Functions/FunctionMathBinaryFloat64.h:61]: Functions are guaranteed to receive columns of the same size.

File: src/Functions/FunctionMathBinaryFloat64.h [hunk 2]
```diff
@@ -53,35 +53,89 @@ class FunctionMathBinaryFloat64 : public IFunction
     }
 
     template <typename LeftType, typename RightType>
```
Comment (alexey-milovidov) [inline src/Functions/FunctionMathBinaryFloat64.h:55]: If we do the conversion in advance by creating a temporary ColumnFloat64 with castColumn, the code will be simpler.

**Comment by alexey-milovidov** [comment]
Let's always return Float64 and use Float64 arithmetic for these functions.

File: src/Functions/FunctionMathBinaryFloat64.h (hunk 2 above)
Comment (mgorshkov) [reply src/Functions/FunctionMathBinaryFloat64.h:56]: This is done, please check.

File: src/Functions/FunctionMathBinaryFloat64.h [hunk 3]
```diff
@@ -53,35 +53,89 @@ class FunctionMathBinaryFloat64 : public IFunction
...
-            if (rows_remaining != 0)
-            {
-                RightType right_src_remaining[Impl::rows_per_iteration];
-                memcpy(right_src_remaining, &right_src_data[rows_size], rows_remaining * sizeof(RightType));
-                memset(right_src_remaining + rows_remaining, 0, (Impl::rows_per_iteration - rows_remaining) * sizeof(RightType));
-                Float64 dst_remaining[Impl::rows_per_iteration];
+            const auto rows_remaining = std::max(left_rows_remaining, right_rows_remaining);
 
-                Impl::execute(left_src_data, right_src_remaining, dst_remaining);
+            memcpy(&dst_data[rows_size], dst_remaining, rows_remaining * sizeof(Float64));
```
[the remark this answers is not in the document]
Comment (mgorshkov) [reply src/Functions/FunctionMathBinaryFloat64.h]: Eventually, I left this code as if was before, since Impl::execute operates by Impl::rows_per_operation size blocks, which may go beyond dst_data boundary.

**Review by alexey-milovidov — APPROVED** [review]
