### PR TITLE
Fix bad code in transforming query for external database.

### LINKED ISSUE #7245: sql error 1241 operand should contain 1 column
**Describe the bug:**
Query error, error info is sql error 1241 operand should contain 1 column
Version : 19.13.3.26

```
create table xjy_mysql_inventory_apply
(
    apply_id      Int64,
    campus_id     Int32,
    apply_user_id Int32,
    apply_type    Int8,
    apply_status  Int8,
    create_time   DateTime
)
    engine = MySQL();
```

error sql :
```SQL
select apply_id
                 from xjy_mysql_inventory_apply
                 where apply_type = 2
                   and create_time > addDays(now(),-7)
                   and apply_status in (3,4)
```

but i changed  addDays(now(),-7) to '2019-09-01 00:00:00', it works fine.

```SQL
select apply_id
                 from xjy_mysql_inventory_apply
                 where apply_type = 2
                   and create_time > '2019-09-01 00:00:00'
                   and apply_status in (3,4)
```

**Expected behavior**
Both SQL should run OK

### PR DESCRIPTION
**Pull request by alexey-milovidov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):
Fixed constant expressions folding for external database engines (MySQL, ODBC, JDBC). In previous versions it wasn't working for multiple constant expressions and was not working at all for Date, DateTime and UUID. This fixes #7245

### CODE REVIEW

File: dbms/src/Storages/transformQueryForExternalDatabase.cpp [hunk 1]
```diff
@@ -20,31 +23,64 @@ namespace ErrorCodes
...
 
-static void replaceConstFunction(IAST & node, const Context & context, const NamesAndTypesList & all_columns)
+namespace
 {
-    for (size_t i = 0; i < node.children.size(); ++i)
+
+class ReplacingConstantExpressionsMatcher
+{
+public:
+    using Data = Block;
```
Comment (4ertus2) [inline dbms/src/Storages/transformQueryForExternalDatabase.cpp]: Interesting hack. I've never thought about assigning Data to a real class.

Comment (alexey-milovidov) [reply dbms/src/Storages/transformQueryForExternalDatabase.cpp]: I didn't consider it as hack. I have just read ActionsVisitor and have thought that it's the intended way of usage.
