### PR TITLE
return const for function getMacro if not distributed query

### LINKED ISSUE #34727: getMacro should return constant value
**Describe the issue**
You can't use getMacro, if ClickHouse requires parameter to have constant value.

**How to reproduce**
ClickHouse version 22.2

```

SELECT
    isConstant(hostName()),
    isConstant(getSetting('max_threads')),
    isConstant(getMacro('shard'))

Query id: 1cfb16d8-9ac9-47b4-8ca3-9e6da9634689

┌─isConstant(hostName())─┬─isConstant(getSetting('max_threads'))─┬─isConstant(getMacro('shard'))─┐
│                      1 │                                     1 │                             0 │
└────────────────────────┴───────────────────────────────────────┴───────────────────────────────┘
```

**Expected behavior**

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Return const for function getMacro if not in distributed query. Close https://github.com/ClickHouse/ClickHouse/issues/34727

### CODE REVIEW

**Review by vdimir — APPROVED** [review]

File: src/Functions/getMacro.cpp [hunk 1]
```diff
@@ -27,15 +27,19 @@ class FunctionGetMacro : public IFunction
 {
 private:
     MultiVersion<Macros>::Version macros;
+    bool is_distributed;
```
Comment (kitaisreal) [inline src/Functions/getMacro.cpp:30]: Can't we use serverConstants.cpp ?

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Functions/getMacro.cpp (hunk 1 above)
Comment (taiyang-li) [reply src/Functions/getMacro.cpp:30]: I tried, but it is not suitable for functions with single argument. 
If we use serverConstants.cpp, we must get the result of `getMacro` in FunctionConstantBase to initialize `constant_value`, which is obvious impossible.

**Review by kitaisreal — APPROVED** [review]

**Review by kitaisreal — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
We have concerns about this implementation.
