### PR TITLE
Fix restart / stop command hanging.

### LINKED ISSUE #20214: '/etc/init.d/clickhouse-server restart' cannot restart CH
The 'restart' option of the init script cannot restart CH if it was not able to shutdown in `shutdown_wait_unfinished` seconds.
```
# sudo /etc/init.d/clickhouse-server restart
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 14388.
The process with pid = 14388 is running.
Sent terminate signal to process with pid 14388.
Waiting for server to stop
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 14388.
The process with pid = 14388 is running.
Waiting for server to stop
...
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 14388.
Waiting for server to stop
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 14388.
Waiting for server to stop
...
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 14388.
Will terminate forcefully.
Code: 425, e.displayText() = DB::ErrnoException: Cannot send kill signal, errno: 3, strerror: No such process (version 21.1.3.32 (official build))
```
The log:
```
2021.02.08 18:57:23.999226 [ 14388 ] {} <Information> Application: Closed connections. But 3 remain. Tip: To increase wait time add to config: <shutdown_wait_unfinished>60</shutdown_wait_unfinished>
2021.02.08 18:57:24.016684 [ 14388 ] {} <Information> Application: Will shutdown forcefully.
2021.02.08 18:58:28.478835 [ 23658 ] {} <Information> Application: Will watch for the process with pid 23659
2021.02.08 18:58:28.478962 [ 23659 ] {} <Information> Application: Forked a child process to watch
2021.02.08 18:58:28.479067 [ 23659 ] {} <Information> StatusFile: Status file /var/run/clickhouse-server/clickhouse-server.pid already exists - unclean restart. Contents: 14388
2021.02.08 18:58:28.479147 [ 23659 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.02.08 18:58:28.479183 [ 23659 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.02.08 18:58:28.532977 [ 23659 ] {} <Information> : Starting ClickHouse 21.1.3.32 with revision 54445, build id: 63BC1671E8C217170F9B6C6346099FD1F76E784F, PID 23659
2021.02.08 18:58:28.533059 [ 23659 ] {} <Information> Application: starting up
```

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix restart / stop command hanging. Closes #20214

Detailed description / Documentation draft:
When pid file still exists, but process dead isRunning was returning the pid.

### CODE REVIEW

File: programs/install/Install.cpp [hunk 1]
```diff
@@ -856,6 +856,10 @@ namespace
             {
                 fmt::print("The process with pid = {} is running.\n", pid);
             }
+            else
+            {
+                pid = 0;
```
Comment (alexey-milovidov) [inline programs/install/Install.cpp:861]: Missing comment.

Comment (alexey-milovidov) [inline programs/install/Install.cpp:861]: The code is incorrect:

man 2 kill:
```
RETURN VALUE
       On success (at least one signal was sent), zero is returned.  On error, -1 is returned, and errno is set appropriately.

ERRORS
       EINVAL An invalid signal was specified.

       EPERM  The calling process does not have permission to send the signal to any of the target processes.

       ESRCH  The target process or process group does not exist.  Note that an existing process might be a zombie, a process that has terminated execution, but has not yet been wait(2)ed for.
```

Comment (filimonov) [reply programs/install/Install.cpp:861]: What kind? If we can not send 0 signal to the process then the process does not exists anymore, and returning pid of dead process has no sense.

Comment (filimonov) [reply programs/install/Install.cpp:861]: You mean to check ESRCH explicitly?
I don't think there is any sense in that.
0 is not a real signal.

EINVAL responce is not possible. EPERM either (as no signal are actually send). 


It will just return 0 if process exists, and -1 otherwise. 
https://man7.org/linux/man-pages/man2/kill.2.html

>       If sig is 0, then no signal is sent, but existence and permission
>       checks are still performed; this can be used to check for the
>       existence of a process ID or process group ID that the caller is
>       permitted to signal.

Comment (filimonov) [reply programs/install/Install.cpp:861]: Ok i think EPERM is actually possible.

**Review by alexey-milovidov — APPROVED** [review]

File: programs/install/Install.cpp [hunk 2]
```diff
@@ -856,6 +856,11 @@ namespace
             {
                 fmt::print("The process with pid = {} is running.\n", pid);
             }
+            else if (errno == ESRCH)
+            {
+                fmt::print("The process with pid = {} does not exist.\n", pid);
```
Comment (filimonov) [inline programs/install/Install.cpp:861]: See line 868 below - now we will print 2 messages which are almost the same.

Comment (filimonov) [reply programs/install/Install.cpp:861]: Maybe do return on line 862?

File: programs/install/Install.cpp [hunk 3]
```diff
@@ -856,6 +856,11 @@ namespace
...
+                pid = 0;
+            }
```
Comment (alexey-milovidov) [inline programs/install/Install.cpp:863]: Here we ignore other errnos, I will add `throwFromErrno`.
