### PR TITLE
Fix tsan error lock-order-inversion

### LINKED ISSUE #47460: Lock order inversion: onCancel
https://s3.amazonaws.com/clickhouse-test-reports/47424/6ba54ab421b6f062759d7605de21e9254778b418/stateless_tests__tsan__%5B1/5%5D.html
```
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=668)
  Cycle in lock order graph: M0 (0x7b140013e1d0) => M1 (0x7b5c001b17f0) => M2 (0x7b60000c0338) => M0

  Mutex M1 acquired here while holding mutex M0 in thread T463:
    #0 pthread_mutex_lock <null> (clickhouse+0xc5aec5a) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #1 std::__1::__libcpp_mutex_lock[abi:v15000](pthread_mutex_t*) build_docker/../contrib/llvm-project/libcxx/include/__threading_support:304:10 (clickhouse+0x26dc08b9) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #2 std::__1::mutex::lock() build_docker/../contrib/llvm-project/libcxx/src/mutex.cpp:38:14 (clickhouse+0x26dc08b9)
    #3 std::__1::lock_guard<std::__1::mutex>::lock_guard[abi:v15000](std::__1::mutex&) build_docker/../contrib/llvm-project/libcxx/include/__mutex_base:94:27 (clickhouse+0x1c95de55) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #4 DB::RemoteQueryExecutor::tryCancel(char const*, std::__1::unique_ptr<DB::RemoteQueryExecutorReadContext, std::__1::default_delete<DB::RemoteQueryExecutorReadContext>>*) build_docker/../src/QueryPipeline/RemoteQueryExecutor.cpp:646:21 (clickhouse+0x1c95de55)
    #5 DB::RemoteQueryExecutor::cancel(std::__1::unique_ptr<DB::RemoteQueryExecutorReadContext, std::__1::default_delete<DB::RemoteQueryExecutorReadContext>>*) build_docker/../src/QueryPipeline/RemoteQueryExecutor.cpp:574:5 (clickhouse+0x1c95c854) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #6 DB::RemoteSource::onCancel() build_docker/../src/Processors/Sources/RemoteSource.cpp:170:21 (clickhouse+0x1f99fc69) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #7 DB::IProcessor::cancel() build_docker/../src/Processors/IProcessor.h:241:9 (clickhouse+0x1f5cb93f) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #8 DB::ExecutingGraph::cancel() build_docker/../src/Processors/Executors/ExecutingGraph.cpp:403:28 (clickhouse+0x1f5cb93f)
    #9 DB::PipelineExecutor::cancel() build_docker/../src/Processors/Executors/PipelineExecutor.cpp:74:12 (clickhouse+0x1f5c2b40) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #10 DB::QueryStatus::ExecutorHolder::cancel() build_docker/../src/Interpreters/ProcessList.cpp:384:19 (clickhouse+0x1dea89d0) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #11 DB::QueryStatus::cancelQuery(bool) build_docker/../src/Interpreters/ProcessList.cpp:419:12 (clickhouse+0x1dea89d0)
    #12 DB::ProcessList::sendCancelToQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) build_docker/../src/Interpreters/ProcessList.cpp:525:18 (clickhouse+0x1dea9204) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #13 DB::SyncKillQuerySource::generate() build_docker/../src/Interpreters/InterpreterKillQueryQuery.cpp:166:42 (clickhouse+0x1dd1eedc) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #14 DB::ISource::tryGenerate() build_docker/../src/Processors/ISource.cpp:125:18 (clickhouse+0x1f5ae8f4) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #15 DB::ISource::work() build_docker/../src/Processors/ISource.cpp:94:26 (clickhouse+0x1f5ae3a9) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #16 DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26 (clickhouse+0x1f5d2992) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #17 DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9 (clickhouse+0x1f5d2992)
    #18 DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26 (clickhouse+0x1f5c3b00) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #19 DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5 (clickhouse+0x1f5c2e62) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #20 DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:372:9 (clickhouse+0x1f5c2e62)
    #21 DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:90:9 (clickhouse+0x1f5c2c39) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #22 DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24 (clickhouse+0x1f5d7235) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #23 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:111:13 (clickhouse+0x1f5d7235)
    #24 decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5d7235)
    #25 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0x1f5d7235)
    #26 decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0x1f5d7235)
    #27 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:210:13 (clickhouse+0x1f5d7235)
    #28 decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5d7235)
    #29 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x1f5d7235)
    #30 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x1f5d7235)
    #31 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x1f5d7235)
    #32 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x146feb70) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #33 std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x146feb70)
    #34 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:315:17 (clickhouse+0x146feb70)
    #35 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:145:73 (clickhouse+0x14703ab1) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #36 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x14703ab1)
    #37 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0x14703ab1)
    #38 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0x14703ab1)

    Hint: use TSAN_OPTIONS=second_deadlock_stack=1 to get more informative warning message

  Mutex M2 acquired here while holding mutex M1 in thread T366:
    #0 pthread_mutex_lock <null> (clickhouse+0xc5aec5a) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #1 std::__1::__libcpp_mutex_lock[abi:v15000](pthread_mutex_t*) build_docker/../contrib/llvm-project/libcxx/include/__threading_support:304:10 (clickhouse+0x26dc08b9) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #2 std::__1::mutex::lock() build_docker/../contrib/llvm-project/libcxx/src/mutex.cpp:38:14 (clickhouse+0x26dc08b9)
    #3 std::__1::lock_guard<std::__1::mutex>::lock_guard[abi:v15000](std::__1::mutex&) build_docker/../contrib/llvm-project/libcxx/include/__mutex_base:94:27 (clickhouse+0x1dea8b36) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #4 DB::QueryStatus::addPipelineExecutor(DB::PipelineExecutor*) build_docker/../src/Interpreters/ProcessList.cpp:432:21 (clickhouse+0x1dea8b36)
    #5 DB::PipelineExecutor::PipelineExecutor(std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:55:31 (clickhouse+0x1f5c2537) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #6 DB::PipelineExecutor* std::__1::construct_at[abi:v15000]<DB::PipelineExecutor, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&, DB::PipelineExecutor*>(DB::PipelineExecutor*, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48 (clickhouse+0x1c9492a6) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #7 void std::__1::allocator_traits<std::__1::allocator<DB::PipelineExecutor>>::construct[abi:v15000]<DB::PipelineExecutor, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&, void, void>(std::__1::allocator<DB::PipelineExecutor>&, DB::PipelineExecutor*, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9 (clickhouse+0x1c9492a6)
    #8 std::__1::__shared_ptr_emplace<DB::PipelineExecutor, std::__1::allocator<DB::PipelineExecutor>>::__shared_ptr_emplace[abi:v15000]<std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&>(std::__1::allocator<DB::PipelineExecutor>, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9 (clickhouse+0x1c9492a6)
    #9 std::__1::shared_ptr<DB::PipelineExecutor> std::__1::allocate_shared[abi:v15000]<DB::PipelineExecutor, std::__1::allocator<DB::PipelineExecutor>, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&, void>(std::__1::allocator<DB::PipelineExecutor> const&, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55 (clickhouse+0x1c9492a6)
    #10 std::__1::shared_ptr<DB::PipelineExecutor> std::__1::make_shared[abi:v15000]<DB::PipelineExecutor, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&, void>(std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::shared_ptr<DB::QueryStatus>&) build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12 (clickhouse+0x1c9492a6)
    #11 DB::QueryPipelineBuilder::execute() build_docker/../src/QueryPipeline/QueryPipelineBuilder.cpp:688:12 (clickhouse+0x1c9492a6)
    #12 DB::Connection::sendExternalTablesData(std::__1::vector<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>, std::__1::allocator<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>>>&) build_docker/../src/Client/Connection.cpp:835:29 (clickhouse+0x1f429e00) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #13 DB::HedgedConnections::sendExternalTablesData(std::__1::vector<std::__1::vector<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>, std::__1::allocator<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>>>, std::__1::allocator<std::__1::vector<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>, std::__1::allocator<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>>>>>&)::$_2::operator()(DB::HedgedConnections::ReplicaState&) const build_docker/../src/Client/HedgedConnections.cpp:106:29 (clickhouse+0x1f448753) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #14 DB::HedgedConnections::sendExternalTablesData(std::__1::vector<std::__1::vector<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>, std::__1::allocator<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>>>, std::__1::allocator<std::__1::vector<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>, std::__1::allocator<std::__1::unique_ptr<DB::ExternalTableData, std::__1::default_delete<DB::ExternalTableData>>>>>>&) build_docker/../src/Client/HedgedConnections.cpp:112:17 (clickhouse+0x1f448753)
    #15 DB::RemoteQueryExecutor::sendExternalTables() build_docker/../src/QueryPipeline/RemoteQueryExecutor.cpp:639:18 (clickhouse+0x1c959cc6) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #16 DB::RemoteQueryExecutor::sendQuery(DB::ClientInfo::QueryKind) build_docker/../src/QueryPipeline/RemoteQueryExecutor.cpp:262:5 (clickhouse+0x1c9589d3) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #17 DB::RemoteSource::tryGenerate() build_docker/../src/Processors/Sources/RemoteSource.cpp:113:25 (clickhouse+0x1f99ebaa) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #18 DB::ISource::work() build_docker/../src/Processors/ISource.cpp:94:26 (clickhouse+0x1f5ae3a9) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #19 DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26 (clickhouse+0x1f5d2992) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #20 DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9 (clickhouse+0x1f5d2992)
    #21 DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26 (clickhouse+0x1f5c3b00) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #22 DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5 (clickhouse+0x1f5c2e62) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #23 DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:372:9 (clickhouse+0x1f5c2e62)
    #24 DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:90:9 (clickhouse+0x1f5c2c39) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #25 DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24 (clickhouse+0x1f5d7235) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #26 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:111:13 (clickhouse+0x1f5d7235)
    #27 decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5d7235)
    #28 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0x1f5d7235)
    #29 decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0x1f5d7235)
    #30 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:210:13 (clickhouse+0x1f5d7235)
    #31 decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5d7235)
    #32 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x1f5d7235)
    #33 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x1f5d7235)
    #34 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x1f5d7235)
    #35 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x146feb70) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #36 std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x146feb70)
    #37 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:315:17 (clickhouse+0x146feb70)
    #38 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:145:73 (clickhouse+0x14703ab1) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #39 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x14703ab1)
    #40 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0x14703ab1)
    #41 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0x14703ab1)

  Mutex M0 acquired here while holding mutex M2 in thread T347:
    #0 pthread_mutex_lock <null> (clickhouse+0xc5aec5a) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #1 std::__1::__libcpp_mutex_lock[abi:v15000](pthread_mutex_t*) build_docker/../contrib/llvm-project/libcxx/include/__threading_support:304:10 (clickhouse+0x26dc08b9) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #2 std::__1::mutex::lock() build_docker/../contrib/llvm-project/libcxx/src/mutex.cpp:38:14 (clickhouse+0x26dc08b9)
    #3 std::__1::lock_guard<std::__1::mutex>::lock_guard[abi:v15000](std::__1::mutex&) build_docker/../contrib/llvm-project/libcxx/include/__mutex_base:94:27 (clickhouse+0x1dea8d7e) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #4 DB::QueryStatus::ExecutorHolder::remove() build_docker/../src/Interpreters/ProcessList.cpp:389:21 (clickhouse+0x1dea8d7e)
    #5 DB::QueryStatus::removePipelineExecutor(DB::PipelineExecutor*) build_docker/../src/Interpreters/ProcessList.cpp:443:12 (clickhouse+0x1dea8d7e)
    #6 DB::PipelineExecutor::~PipelineExecutor() build_docker/../src/Processors/Executors/PipelineExecutor.cpp:62:31 (clickhouse+0x1f5c285e) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #7 void std::__1::__destroy_at[abi:v15000]<DB::PipelineExecutor, 0>(DB::PipelineExecutor*) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13 (clickhouse+0x1c95035d) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #8 void std::__1::destroy_at[abi:v15000]<DB::PipelineExecutor, 0>(DB::PipelineExecutor*) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5 (clickhouse+0x1c95035d)
    #9 void std::__1::allocator_traits<std::__1::allocator<DB::PipelineExecutor>>::destroy[abi:v15000]<DB::PipelineExecutor, void, void>(std::__1::allocator<DB::PipelineExecutor>&, DB::PipelineExecutor*) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9 (clickhouse+0x1c95035d)
    #10 std::__1::__shared_ptr_emplace<DB::PipelineExecutor, std::__1::allocator<DB::PipelineExecutor>>::__on_zero_shared() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:309:9 (clickhouse+0x1c95035d)
    #11 std::__1::__shared_count::__release_shared[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174:9 (clickhouse+0x1f5d7b2f) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #12 std::__1::__shared_weak_count::__release_shared[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215:27 (clickhouse+0x1f5d7b2f)
    #13 std::__1::shared_ptr<DB::PipelineExecutor>::~shared_ptr[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702:23 (clickhouse+0x1f5d7b2f)
    #14 DB::PullingAsyncPipelineExecutor::Data::~Data() build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:32:5 (clickhouse+0x1f5d7b2f)
    #15 std::__1::default_delete<DB::PullingAsyncPipelineExecutor::Data>::operator()[abi:v15000](DB::PullingAsyncPipelineExecutor::Data*) const build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5 (clickhouse+0x1f5d5480) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #16 std::__1::unique_ptr<DB::PullingAsyncPipelineExecutor::Data, std::__1::default_delete<DB::PullingAsyncPipelineExecutor::Data>>::reset[abi:v15000](DB::PullingAsyncPipelineExecutor::Data*) build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7 (clickhouse+0x1f5d5480)
    #17 std::__1::unique_ptr<DB::PullingAsyncPipelineExecutor::Data, std::__1::default_delete<DB::PullingAsyncPipelineExecutor::Data>>::~unique_ptr[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259:19 (clickhouse+0x1f5d5480)
    #18 DB::PullingAsyncPipelineExecutor::~PullingAsyncPipelineExecutor() build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:63:1 (clickhouse+0x1f5d5480)
    #19 DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/../src/Server/TCPHandler.cpp:873:5 (clickhouse+0x1f5566fc) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #20 DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:435:17 (clickhouse+0x1f54cc6c) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #21 DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1997:9 (clickhouse+0x1f5628e7) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #22 Poco::Net::TCPServerConnection::start() build_docker/../base/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x232b0282) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #23 Poco::Net::TCPServerDispatcher::run() build_docker/../base/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x232b0af2) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #24 Poco::PooledThread::run() build_docker/../base/poco/Foundation/src/ThreadPool.cpp:188:14 (clickhouse+0x2350ae99) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #25 Poco::(anonymous namespace)::RunnableHolder::run() build_docker/../base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x2350924f) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #26 Poco::ThreadImpl::runnableEntry(void*) build_docker/../base/poco/Foundation/src/Thread_POSIX.cpp:335:27 (clickhouse+0x23507867) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)

  Thread T463 'QueryPullPipeEx' (tid=1499, running) created by thread T409 at:
    #0 pthread_create <null> (clickhouse+0xc590f7d) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #1 std::__1::__libcpp_thread_create[abi:v15000](unsigned long*, void* (*)(void*), void*) build_docker/../contrib/llvm-project/libcxx/include/__threading_support:376:10 (clickhouse+0x147031fb) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #2 std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/../contrib/llvm-project/libcxx/include/thread:311:16 (clickhouse+0x147031fb)
    #3 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:145:35 (clickhouse+0x146fcbfd) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #4 ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, long, unsigned long, bool) build_docker/../src/Common/ThreadPool.cpp:182:5 (clickhouse+0x146fd7d2) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #5 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../src/Common/ThreadPool.h:190:38 (clickhouse+0x1f5c50db) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #6 ThreadFromGlobalPoolImpl<true>* std::__1::construct_at[abi:v15000]<ThreadFromGlobalPoolImpl<true>, DB::PipelineExecutor::spawnThreads()::$_0, ThreadFromGlobalPoolImpl<true>*>(ThreadFromGlobalPoolImpl<true>*, DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48 (clickhouse+0x1f5c50db)
    #7 void std::__1::allocator_traits<std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::construct[abi:v15000]<ThreadFromGlobalPoolImpl<true>, DB::PipelineExecutor::spawnThreads()::$_0, void, void>(std::__1::allocator<ThreadFromGlobalPoolImpl<true>>&, ThreadFromGlobalPoolImpl<true>*, DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9 (clickhouse+0x1f5c50db)
    #8 void std::__1::vector<ThreadFromGlobalPoolImpl<true>, std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::__construct_one_at_end[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/vector:808:5 (clickhouse+0x1f5c4759) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #9 ThreadFromGlobalPoolImpl<true>& std::__1::vector<ThreadFromGlobalPoolImpl<true>, std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::emplace_back<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/vector:1597:9 (clickhouse+0x1f5c4759)
    #10 DB::PipelineExecutor::spawnThreads() build_docker/../src/Processors/Executors/PipelineExecutor.cpp:305:17 (clickhouse+0x1f5c4759)
    #11 DB::PipelineExecutor::executeImpl(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:365:9 (clickhouse+0x1f5c2e14) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #12 DB::PipelineExecutor::execute(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:90:9 (clickhouse+0x1f5c2c39) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #13 DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24 (clickhouse+0x1f5d7235) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #14 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:111:13 (clickhouse+0x1f5d7235)
    #15 decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5d7235)
    #16 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0x1f5d7235)
    #17 decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0x1f5d7235)
    #18 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:210:13 (clickhouse+0x1f5d7235)
    #19 decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5d7235)
    #20 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x1f5d7235)
    #21 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x1f5d7235)
    #22 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x1f5d7235)
    #23 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x146feb70) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #24 std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x146feb70)
    #25 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:315:17 (clickhouse+0x146feb70)
    #26 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:145:73 (clickhouse+0x14703ab1) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #27 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x14703ab1)
    #28 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0x14703ab1)
    #29 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0x14703ab1)

  Thread T366 'ThreadPool' (tid=1224, running) created by thread T336 at:
    #0 pthread_create <null> (clickhouse+0xc590f7d) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #1 std::__1::__libcpp_thread_create[abi:v15000](unsigned long*, void* (*)(void*), void*) build_docker/../contrib/llvm-project/libcxx/include/__threading_support:376:10 (clickhouse+0x147031fb) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #2 std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) build_docker/../contrib/llvm-project/libcxx/include/thread:311:16 (clickhouse+0x147031fb)
    #3 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool) build_docker/../src/Common/ThreadPool.cpp:145:35 (clickhouse+0x146fcbfd) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #4 ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, long, unsigned long, bool) build_docker/../src/Common/ThreadPool.cpp:182:5 (clickhouse+0x146fd7d2) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #5 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../src/Common/ThreadPool.h:190:38 (clickhouse+0x1f5c50db) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #6 ThreadFromGlobalPoolImpl<true>* std::__1::construct_at[abi:v15000]<ThreadFromGlobalPoolImpl<true>, DB::PipelineExecutor::spawnThreads()::$_0, ThreadFromGlobalPoolImpl<true>*>(ThreadFromGlobalPoolImpl<true>*, DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48 (clickhouse+0x1f5c50db)
    #7 void std::__1::allocator_traits<std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::construct[abi:v15000]<ThreadFromGlobalPoolImpl<true>, DB::PipelineExecutor::spawnThreads()::$_0, void, void>(std::__1::allocator<ThreadFromGlobalPoolImpl<true>>&, ThreadFromGlobalPoolImpl<true>*, DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9 (clickhouse+0x1f5c50db)
    #8 void std::__1::vector<ThreadFromGlobalPoolImpl<true>, std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::__construct_one_at_end[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/vector:808:5 (clickhouse+0x1f5c4759) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #9 ThreadFromGlobalPoolImpl<true>& std::__1::vector<ThreadFromGlobalPoolImpl<true>, std::__1::allocator<ThreadFromGlobalPoolImpl<true>>>::emplace_back<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/vector:1597:9 (clickhouse+0x1f5c4759)
    #10 DB::PipelineExecutor::spawnThreads() build_docker/../src/Processors/Executors/PipelineExecutor.cpp:305:17 (clickhouse+0x1f5c4759)
    #11 DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:260:13 (clickhouse+0x1f5c3a8f) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #12 DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5 (clickhouse+0x1f5c53ad) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #13 DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:320:17 (clickhouse+0x1f5c53ad)
    #14 decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5c53ad)
    #15 decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1 (clickhouse+0x1f5c53ad)
    #16 decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1 (clickhouse+0x1f5c53ad)
    #17 ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:210:13 (clickhouse+0x1f5c53ad)
    #18 decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x1f5c53ad)
    #19 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9 (clickhouse+0x1f5c53ad)
    #20 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12 (clickhouse+0x1f5c53ad)
    #21 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16 (clickhouse+0x1f5c53ad)
    #22 std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16 (clickhouse+0x146feb70) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #23 std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12 (clickhouse+0x146feb70)
    #24 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:315:17 (clickhouse+0x146feb70)
    #25 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:145:73 (clickhouse+0x14703ab1) (BuildId: 387fdcebae3b54a68c1042d8afba9afcb19cb2d9)
    #26 decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23 (clickhouse+0x14703ab1)
    #27 void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5 (clickhouse+0x14703ab1)
    #28 void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5 (clickhouse+0x14703ab1)
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/47460

### CODE REVIEW

**Review by KochetovNicolai — APPROVED** [review]

**Comment by tavplubix** [comment]
Stateless tests (tsan, s3 storage) [3/5] - there's a data race between `QueryStatus::removePipelineExecutor` and `QueryStatus::ExecutorHolder::remove()`: https://pastila.nl/?0038f02c/9990ad75e485129914bf0bd050aa20c5

File: src/Interpreters/ProcessList.cpp [hunk 1]
```diff
@@ -428,17 +434,22 @@ void QueryStatus::addPipelineExecutor(PipelineExecutor * e)
         throw Exception(ErrorCodes::QUERY_WAS_CANCELLED, "Query was cancelled");
 
     std::lock_guard lock(executors_mutex);
-    assert(std::find_if(executors.begin(), executors.end(), [e](const ExecutorHolderPtr & x){ return x->executor == e; }) == executors.end());
+    assert(std::find_if(executors.begin(), executors.end(), [e](ExecutorHolderPtr & x){ return x->equals(e); }) == executors.end());
```
Comment (tavplubix) [inline src/Interpreters/ProcessList.cpp:437]: It will lock `ExecutorHolder::mutex` while holding `executors_mutex`, so here we are again

File: src/Interpreters/ProcessList.cpp [hunk 2]
```diff
@@ -428,17 +434,22 @@ void QueryStatus::addPipelineExecutor(PipelineExecutor * e)
...
+    {
+        std::lock_guard lock(executors_mutex);
+        auto it = std::find_if(executors.begin(), executors.end(), [e](ExecutorHolderPtr & x){ return x->equals(e); });
+        assert(it != executors.end());
+        executor_holder = *it;
+    }
     /// Invalidate executor pointer inside holder, but don't remove holder from the executors (to avoid race with cancelQuery)
-    (*it)->remove();
+    /// We should do it with released executors_mutex to avoid possible lock order inversion.
+    executor_holder->remove();
```
Comment (tavplubix) [inline src/Interpreters/ProcessList.cpp:452]: Same

File: src/Interpreters/ProcessList.cpp (hunk 1 above)
Comment (Avogar) [reply src/Interpreters/ProcessList.cpp:437]: Yeh, I already realozed it. I am thinking how to avoid it

Comment (Avogar) [reply src/Interpreters/ProcessList.cpp:437]: We can do same as in `cancelQuery`, first copy `executors` vector under mutex and then perform operations on `ExecutorHolder`

Comment (tavplubix) [reply src/Interpreters/ProcessList.cpp:437]: I have a stupid idea: we can rename `equals` to something like `inprecieseDebugCheckEquals`, do `try_lock` there, and return `true` if `try_lock` failed. It's okay for a debug assertion

**Comment by tavplubix** [comment]
@alexey-milovidov, see https://github.com/ClickHouse/ClickHouse/issues/47460#issuecomment-1481149788, that's why it must be backported

**Review by KochetovNicolai — APPROVED** [review]
