### PR TITLE
Fix crash in `min(multiply(1))` with optimize_arithmetic_operations_in_aggregate_functions

### LINKED ISSUE #11741: Received signal Segmentation fault (11)
**How to reproduce**
```SELECT min(multiply(1))```

**Error message and/or stacktrace**
```
2020.06.17 21:55:03.851021 [ 2942 ] {} <Fatal> BaseDaemon: ########################################
2020.06.17 21:55:03.851053 [ 2942 ] {} <Fatal> BaseDaemon: (version 20.5.1.1) (from thread 2869) (query_id: 571af238-2526-4953-92d8-de9ac37472df) Received signal Segmentation fault (11).
2020.06.17 21:55:03.851068 [ 2942 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2020.06.17 21:55:03.851085 [ 2942 ] {} <Fatal> BaseDaemon: Stack trace: 0xdc50701 0xdc50732 0xdc52d70 0xdc38572 0xdc385aa 0xdc385aa 0xdc3172f 0xda25221 0xda22516 0xda210ab 0xdb84595 0xd9cd15a 0xd9cc985 0xdc6db90 0xdc6d127 0xe0b79f8 0xe0c05f7 0xfe79037 0xfe794d8 0xff5a0a7 0xff57f36 0x7f53857676db 0x7f538508488f
2020.06.17 21:55:03.944085 [ 2942 ] {} <Fatal> BaseDaemon: 3. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/memory:3826: DB::findAllConsts(DB::ASTFunction const*, char const*) @ 0xdc50701 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.944710 [ 2942 ] {} <Fatal> BaseDaemon: 4. /home/ap11/ClickHouse/build_clang/../src/Interpreters/ArithmeticOperationsInAgrFuncOptimize.cpp:0: DB::findAllConsts(DB::ASTFunction const*, char const*) @ 0xdc50732 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.945346 [ 2942 ] {} <Fatal> BaseDaemon: 5. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/vector:662: DB::minOptimize(DB::ASTFunction*) @ 0xdc52d70 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.947106 [ 2942 ] {} <Fatal> BaseDaemon: 6. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/memory:3826: DB::InDepthNodeVisitor<DB::ArithmeticOperationsInAgrFuncMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0xdc38572 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.947994 [ 2942 ] {} <Fatal> BaseDaemon: 7. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/iterator:1480: DB::InDepthNodeVisitor<DB::ArithmeticOperationsInAgrFuncMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0xdc385aa in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.948833 [ 2942 ] {} <Fatal> BaseDaemon: 8. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/iterator:1480: DB::InDepthNodeVisitor<DB::ArithmeticOperationsInAgrFuncMatcher, true, std::__1::shared_ptr<DB::IAST> >::visit(std::__1::shared_ptr<DB::IAST>&) @ 0xdc385aa in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.949643 [ 2942 ] {} <Fatal> BaseDaemon: 9. /home/ap11/ClickHouse/build_clang/../src/Interpreters/SyntaxAnalyzer.cpp:0: DB::SyntaxAnalyzer::analyzeSelect(std::__1::shared_ptr<DB::IAST>&, DB::SyntaxAnalyzerResult&&, DB::SelectQueryOptions const&, std::__1::vector<DB::TableWithColumnNamesAndTypes, std::__1::allocator<DB::TableWithColumnNamesAndTypes> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::TableJoin>) const @ 0xdc3172f in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.951508 [ 2942 ] {} <Fatal> BaseDaemon: 10. /home/ap11/ClickHouse/build_clang/../src/Interpreters/InterpreterSelectQuery.cpp:308: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_2::operator()(bool) const @ 0xda25221 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.952476 [ 2942 ] {} <Fatal> BaseDaemon: 11. /home/ap11/ClickHouse/build_clang/../src/Interpreters/InterpreterSelectQuery.cpp:400: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xda22516 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.953048 [ 2942 ] {} <Fatal> BaseDaemon: 12. /home/ap11/ClickHouse/build_clang/../src/Interpreters/InterpreterSelectQuery.cpp:144: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xda210ab in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.954487 [ 2942 ] {} <Fatal> BaseDaemon: 13. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/memory:2204: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdb84595 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.956396 [ 2942 ] {} <Fatal> BaseDaemon: 14. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/memory:2204: std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions>(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&&) @ 0xd9cd15a in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.956943 [ 2942 ] {} <Fatal> BaseDaemon: 15. /home/ap11/ClickHouse/build_clang/../src/Interpreters/InterpreterFactory.cpp:0: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xd9cc985 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.959056 [ 2942 ] {} <Fatal> BaseDaemon: 16. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/memory:3913: DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xdc6db90 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.960301 [ 2942 ] {} <Fatal> BaseDaemon: 17. /home/ap11/ClickHouse/build_clang/../src/Interpreters/executeQuery.cpp:618: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdc6d127 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.962689 [ 2942 ] {} <Fatal> BaseDaemon: 18. /home/ap11/ClickHouse/build_clang/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0xe0b79f8 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.963903 [ 2942 ] {} <Fatal> BaseDaemon: 19. /home/ap11/ClickHouse/build_clang/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::run() @ 0xe0c05f7 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.966140 [ 2942 ] {} <Fatal> BaseDaemon: 20. /home/ap11/ClickHouse/build_clang/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0xfe79037 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.967333 [ 2942 ] {} <Fatal> BaseDaemon: 21. /home/ap11/ClickHouse/build_clang/../contrib/libcxx/include/atomic:1036: Poco::Net::TCPServerDispatcher::run() @ 0xfe794d8 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.969424 [ 2942 ] {} <Fatal> BaseDaemon: 22. /home/ap11/ClickHouse/build_clang/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0xff5a0a7 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.970822 [ 2942 ] {} <Fatal> BaseDaemon: 23. /home/ap11/ClickHouse/build_clang/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::ThreadImpl::runnableEntry(void*) @ 0xff57f36 in /home/ap11/ClickHouse/build_clang/programs/clickhouse
2020.06.17 21:55:03.970863 [ 2942 ] {} <Fatal> BaseDaemon: 24. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
2020.06.17 21:55:03.972804 [ 2942 ] {} <Fatal> BaseDaemon: 25. /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __clone @ 0x12188f in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by kamalov-ruslan**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes crash in special generated queries when `optimize_arithmetic_operations_in_aggregate_functions = 1`.

Detailed description / Documentation draft:
requests of the following form: SELECT min(multiply(1)), SELECT max(multiply(1)), etc.

Closes #11741

### CODE REVIEW

File: src/Interpreters/ArithmeticOperationsInAgrFuncOptimize.cpp [hunk 1]
```diff
@@ -94,7 +94,7 @@ std::pair<ASTs, ASTs> tryGetConst(const char * name, const ASTs & arguments)
             not_const.push_back(arg);
     }
 
-    if ((name == plus || name == mul) && const_num.size() + not_const.size() != 2)
+    if ((strcmp(name, plus) || strcmp(name, mul)) && const_num.size() + not_const.size() != 2)
```
Comment (azat) [inline src/Interpreters/ArithmeticOperationsInAgrFuncOptimize.cpp:97]: `strcmp() == 0` ?

Comment (kamalov-ruslan) [reply src/Interpreters/ArithmeticOperationsInAgrFuncOptimize.cpp:97]: yes, should be

**Review by 4ertus2 — APPROVED** [review]
