### PR TITLE
Fix inconsistent AST formatting of arrayElement with negate literal

### LINKED ISSUE #92288: Logical error: 'Inconsistent AST formatting in Function_divide: the query:
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: 'Inconsistent AST formatting in Function_divide: the query: (STID: 1941-1bfa)
CI report: [BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91930&sha=87494e8f9c35fde178c09662231f363a98895eeb&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ0luY29uc2lzdGVudCBBU1QgZm9ybWF0dGluZyBpbiBGdW5jdGlvbl9kaXZpZGU6IHRoZSBxdWVyeTonCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdCdXp6SG91c2UgKGFtZF9kZWJ1ZyknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwKSBPUiBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDApCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
Error:
Logical error: 'Inconsistent AST formatting in Function_divide: the query:
EXPLAIN SYNTAX WITH (+-16)[3] / randomString(461) AS `a0`, cte0d0 AS (SELECT `c0`, `c1`, `c2`, `c3`, `c4` FROM (WITH indexHint(22::UInt64) AS `a1`, 0.962 AS `a2` SELECT DISTINCT intervalLengthSum(DIST...
Formatted as:
EXPLAIN SYNTAX WITH (-(16)[3]) / randomString(461) AS a0, cte0d0 AS (SELECT c0, c1, c2, c3, c4 FROM (WITH indexHint(CAST('22', 'UInt64')) AS a1, 0.962 AS a2 SELECT DISTINCT intervalLengthSumDistinct(C...
            w0 AS (ROWS BETWEEN UNBOUNDED PRECEDING AND 5 FOLLOWING),
            w1 AS (ORDER BY (a2, a1, a2) ASC, sumOrDefaultDistinct(CAST('959230691832896684035', 'UInt128')) OVER (PARTITION BY CAST('ddfd30b7-1ee0-53fd-1273-177357f12b57', 'UUID'), a2, a1) ASC NULLS ...
            w2 AS (ORDER BY a1 ASC NULLS LAST) QUALIFY (a4 <= a3) AND (a3.^`1` = `a3.keys`) AND (NOT (((`a5.size0`[0]) < NULL) OR ((`a5.size0`[0]) > JSONSharedDataPaths(a4)))) ORDER BY 1 DESC NULLS LA...
Was parsed and formatted back as:
EXPLAIN SYNTAX WITH (-(16[3])) / randomString(461) AS a0, cte0d0 AS (SELECT c0, c1, c2, c3, c4 FROM (WITH indexHint(CAST('22', 'UInt64')) AS a1, 0.962 AS a2 SELECT DISTINCT intervalLengthSumDistinct(C...
            w0 AS (ROWS BETWEEN UNBOUNDED PRECEDING AND 5 FOLLOWING),
---

Failed query:
WITH (-(16)[3]) / randomString(461) AS a0, cte0d0 AS (SELECT c0, c1, c2, c3, c4 FROM (WITH indexHint(CAST('22', 'UInt64')) AS a1, 0.962 AS a2 SELECT DISTINCT intervalLengthSumDistinct(CAST('15', 'Int1...
---

Stack trace:
pthread_kill@@GLIBC_2.34 @ 0x00000000000969fd
raise @ 0x0000000000042476
__lgamma_r_finite@GLIBC_2.15 @ 0x00000000000287f3
src/Common/Exception.cpp:54: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x0000000015c9113c
src/Common/Exception.cpp:87: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x0000000015c9258...
src/Common/Exception.cpp:138: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015c928a5
src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d632754
src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d6322d3
src/Common/Exception.h:141: DB::Exception::Exception<String, std::basic_string_view<char, std::char_traits<char>>&, String&, String&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std:...
src/Interpreters/executeQuery.cpp:1284: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std...
src/Interpreters/executeQuery.cpp:1959: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c2865d4
src/Server/TCPHandler.cpp:776: DB::TCPHandler::runImpl() @ 0x000000001fa99f89
src/Server/TCPHandler.cpp:2866: DB::TCPHandler::run() @ 0x000000001fab5064
base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000025f912ce
base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000025f9193b
base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000025f31e3f
base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000025f2f4cf
start_thread @ 0x0000000000094ac3
__clone3 @ 0x00000000001268c0
```

### LINKED ISSUE #92386: Logical error: 'Inconsistent AST formatting in Subquery: the query:
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: 'Inconsistent AST formatting in Subquery: the query:
CI report: [BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=85760&sha=7a7525590549605626772699208bd90b5eaf99b3&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ0luY29uc2lzdGVudCBBU1QgZm9ybWF0dGluZyBpbiBTdWJxdWVyeTogdGhlIHF1ZXJ5OicKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0J1enpIb3VzZSAoYW1kX2RlYnVnKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
Error:
Logical error: 'Inconsistent AST formatting in Subquery: the query:
INSERT INTO TABLE d0.`t42` (`c0.c1`) SELECT `c1` FROM generateRandom('c1 Array(DateTime)', 338545717747078723, 215, 4) LIMIT 70 PARALLEL WITH DESCRIBE (WITH '9ba1f7a9-8106-fef3-e54b-b51db5436a33'::UUI...
Formatted as:
INSERT INTO d0.t42 (`c0.c1`) SELECT c1 FROM generateRandom('c1 Array(DateTime)', 338545717747078723, 215, 4) LIMIT 70 PARALLEL WITH DESCRIBE TABLE (WITH CAST('9ba1f7a9-8106-fef3-e54b-b51db5436a33', 'U...
        w0 AS (),
        w1 AS (PARTITION BY CAST(addSeconds(now(), 73), 'DateTime64(4)') RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
        w2 AS (ROWS BETWEEN UNBOUNDED PRECEDING AND concatAssumeInjective(toIntervalMinute(lag(CAST('50', 'Int128') GLOBAL NOT IN (SELECT CAST('{"😉😉":[]}', 'JSON') FROM `null`('c0 Nullable(DateTime), ...
Was parsed and formatted back as:
INSERT INTO d0.t42 (`c0.c1`) SELECT c1 FROM generateRandom('c1 Array(DateTime)', 338545717747078723, 215, 4) LIMIT 70 PARALLEL WITH DESCRIBE TABLE (WITH CAST('9ba1f7a9-8106-fef3-e54b-b51db5436a33', 'U...
        w0 AS (),
---

Failed query:
DESCRIBE TABLE (WITH CAST('9ba1f7a9-8106-fef3-e54b-b51db5436a33', 'UUID')[CAST('10', 'Int16')] AS a0 SELECT DISTINCT [-[1], hiveHash(CAST('-31', 'Int') OR '漂亮'), f10(percent_rank() OVER (w3), CAST('20...
---

Stack trace:
pthread_kill@@GLIBC_2.34 @ 0x00000000000969fd
raise @ 0x0000000000042476
__ieee754_lgamma_r @ 0x00000000000287f3
src/Common/Exception.cpp:54: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x0000000015ca55fc
src/Common/Exception.cpp:87: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x0000000015ca6a4...
src/Common/Exception.cpp:138: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015ca6d65
src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d63a214
src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d639d93
src/Common/Exception.h:141: DB::Exception::Exception<String, std::basic_string_view<char, std::char_traits<char>>&, String&, String&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std:...
src/Interpreters/executeQuery.cpp:1284: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std...
src/Interpreters/executeQuery.cpp:1959: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c2aab54
src/Server/TCPHandler.cpp:776: DB::TCPHandler::runImpl() @ 0x000000001fabec49
src/Server/TCPHandler.cpp:2866: DB::TCPHandler::run() @ 0x000000001fad9d24
base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000025fb194e
base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000025fb1fbb
base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000025f524bf
base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000025f4fb4f
start_thread @ 0x0000000000094ac3
clone3 @ 0x00000000001268c0
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix inconsistent AST formatting of arrayElement with negate literal.
Closes https://github.com/ClickHouse/ClickHouse/issues/92288
Closes https://github.com/ClickHouse/ClickHouse/issues/92212
Closes https://github.com/ClickHouse/ClickHouse/issues/91832
Closes https://github.com/ClickHouse/ClickHouse/issues/91789
Closes https://github.com/ClickHouse/ClickHouse/issues/91735
Closes https://github.com/ClickHouse/ClickHouse/issues/88495
Closes https://github.com/ClickHouse/ClickHouse/issues/92386

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Parsers/ASTFunction.cpp [hunk 1]
```diff
@@ -467,6 +467,9 @@ void ASTFunction::formatImplWithoutAlias(WriteBuffer & ostr, const FormatSetting
                 if (frame.need_parens)
                     ostr << '(';
 
+                /// Don't allow moving operators like '-' before parents,
```
Comment (azat) [inline src/Parsers/ASTFunction.cpp:470]: Let's maybe move this comment into the `allow_moving_operators_before_parens` declaration?

File: src/Parsers/IAST.h [hunk 2]
```diff
@@ -248,6 +248,7 @@ class IAST : public std::enable_shared_from_this<IAST>, public TypePromotion<IAS
         bool surround_each_list_element_with_parens = false;
         bool ignore_printed_asts_with_alias = false; /// Ignore FormatState::printed_asts_with_alias
         bool allow_operators = true; /// Format some functions, such as "plus", "in", etc. as operators.
+        bool allow_moving_operators_before_parens = true;
```
Comment (azat) [inline src/Parsers/IAST.h]: Yeah, sadly it is not possible to fix this formatting w/o introducing extra property (which I wanted to avoid in the first place)

File: tests/queries/0_stateless/03761_inconsistent_ast_formatting.sql [hunk 3]
```diff
@@ -0,0 +1,2 @@
+select (-(42))[3]; -- {serverError ILLEGAL_TYPE_OF_ARGUMENT}
+select(-('a')).1; -- {serverError ILLEGAL_TYPE_OF_ARGUMENT}
```
Comment (azat) [inline tests/queries/0_stateless/03761_inconsistent_ast_formatting.sql]: Let's convert the test to `explain syntax`, to fix bug check and make it more explicit

**Review by azat — COMMENTED** [review]
Just a few comments before I found yet another fix of this problem - https://github.com/ClickHouse/ClickHouse/pull/92340

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
Now we need to decide this one or https://github.com/ClickHouse/ClickHouse/pull/92340 (cc @alexey-milovidov), though there are lots of tests failed, and I think we can merge this as a first step (it should not break any new formatting, so this should be safe)

**Comment by Avogar** [comment]
>  think we can merge this as a first step (it should not break any new formatting, so this should be safe)

Agree. It should fix lots of `Inconsistent AST formatting` failures in CI and make CI better. https://github.com/ClickHouse/ClickHouse/pull/92340 will take some time to merge and we can spend more time on it with no rush if needed
