### PR TITLE
Throws an error if iceberg_metadata_log is not configured

### LINKED ISSUE #86681: Trivial SEGV with empty Iceberg table
### Describe the bug

Easy to reproduce.

### How to reproduce

Run:

```sql
CREATE TABLE t0 (c0 Int) ENGINE = IcebergLocal(local, format = 'Parquet', path = '/var/lib/clickhouse/user_files/t0/');
SELECT 1 FROM t0 SETTINGS iceberg_metadata_log_level = 'metadata'; --SEGV
```

### Error message and/or stacktrace

Stack trace:
```
2025.09.04 13:15:52.196430 [ 1764115 ] {} <Trace> BaseDaemon: Received signal 11
2025.09.04 13:15:52.196491 [ 1764115 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.09.04 13:15:52.196514 [ 1764115 ] {} <Fatal> BaseDaemon: (version 25.9.1.973 (official build), build id: E3FC7DCD219B0B1528C05115733717D7B61143CE, git hash: 9d1330bd554128f27f5fdae5bd610e81c94230bd, architecture: x86_64) (from thread 1764117) Received signal 11
2025.09.04 13:15:52.196524 [ 1764115 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2025.09.04 13:15:52.196538 [ 1764115 ] {} <Fatal> BaseDaemon: Address: 0x40. Access: read. Address not mapped to object.
2025.09.04 13:15:52.196570 [ 1764115 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005bbaba405bc1 0x00005bbac126f411 0x00005bbabf8f0a4e 0x00005bbabd9073da 0x00005bbabd90525f 0x00005bbabf7446e0 0x00005bbac09cf7d3 0x00005bbac09cffd3 0x00005bbac071de85 0x00005bbac07394d0 0x00005bbac0705b94 0x00005bbac0704bf6 0x00005bbac070420e 0x00005bbac076b113 0x00005bbac133ae67 0x00005bbac13395ed 0x00005bbac133c0f0 0x00005bbac12c7aeb 0x00005bbac164256c 0x00005bbac163c985 0x00005bbac5074bcf 0x00005bbac508ea64 0x00005bbacd340907 0x00005bbacd340ee5 0x00005bbacd2e00bf 0x00005bbacd2dd791 0x000072ce5caa27f1 0x000072ce5cb33c9c
2025.09.04 13:15:52.196581 [ 1764115 ] {} <Fatal> BaseDaemon: ########################################
2025.09.04 13:15:52.196672 [ 1764115 ] {} <Fatal> BaseDaemon: (version 25.9.1.973 (official build), build id: E3FC7DCD219B0B1528C05115733717D7B61143CE, git hash: 9d1330bd554128f27f5fdae5bd610e81c94230bd) (from thread 1764117) (query_id: e9cc9130-b866-4add-a3f4-88cea855eddf) (query: SELECT 1 FROM t0 SETTINGS iceberg_metadata_log_level = 'metadata';) Received signal Segmentation fault (11)
2025.09.04 13:15:52.196714 [ 1764115 ] {} <Fatal> BaseDaemon: Address: 0x40. Access: read. Address not mapped to object.
2025.09.04 13:15:52.196747 [ 1764115 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005bbaba405bc1 0x00005bbac126f411 0x00005bbabf8f0a4e 0x00005bbabd9073da 0x00005bbabd90525f 0x00005bbabf7446e0 0x00005bbac09cf7d3 0x00005bbac09cffd3 0x00005bbac071de85 0x00005bbac07394d0 0x00005bbac0705b94 0x00005bbac0704bf6 0x00005bbac070420e 0x00005bbac076b113 0x00005bbac133ae67 0x00005bbac13395ed 0x00005bbac133c0f0 0x00005bbac12c7aeb 0x00005bbac164256c 0x00005bbac163c985 0x00005bbac5074bcf 0x00005bbac508ea64 0x00005bbacd340907 0x00005bbacd340ee5 0x00005bbacd2e00bf 0x00005bbacd2dd791 0x000072ce5caa27f1 0x000072ce5cb33c9c
2025.09.04 13:15:52.254500 [ 1764115 ] {} <Fatal> BaseDaemon: 3.0. inlined from contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:744: std::shared_ptr<DB::SystemLogQueue<DB::IcebergMetadataLogElement>>::operator->[abi:se190107]() const
2025.09.04 13:15:52.254548 [ 1764115 ] {} <Fatal> BaseDaemon: 3. ci/tmp/build/./src/Common/SystemLogBase.cpp:311: DB::SystemLogBase<DB::IcebergMetadataLogElement>::add(DB::IcebergMetadataLogElement) @ 0x00000000145c5bc1
2025.09.04 13:15:52.267383 [ 1764115 ] {} <Fatal> BaseDaemon: 4. ci/tmp/build/./src/Interpreters/IcebergMetadataLog.cpp:99: DB::insertRowToLogTable(std::shared_ptr<DB::Context const> const&, String, DB::IcebergMetadataLogLevel, String const&, String const&, std::optional<unsigned long>) @ 0x000000001b42f411
2025.09.04 13:15:52.321590 [ 1764115 ] {} <Fatal> BaseDaemon: 5. ci/tmp/build/./src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp:247: DB::IcebergMetadata::update(std::shared_ptr<DB::Context const> const&) @ 0x0000000019ab0a4e
2025.09.04 13:15:52.407659 [ 1764115 ] {} <Fatal> BaseDaemon: 6. src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h:378: DB::DataLakeConfiguration<DB::StorageLocalConfiguration, DB::IcebergMetadata>::updateMetadataIfChanged(std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context const>) @ 0x0000000017ac73da
2025.09.04 13:15:52.491748 [ 1764115 ] {} <Fatal> BaseDaemon: 7. src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h:90: DB::DataLakeConfiguration<DB::StorageLocalConfiguration, DB::IcebergMetadata>::update(std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context const>, bool, bool) @ 0x0000000017ac525f
2025.09.04 13:15:52.529212 [ 1764115 ] {} <Fatal> BaseDaemon: 8. ci/tmp/build/./src/Storages/ObjectStorage/StorageObjectStorage.cpp:298: DB::StorageObjectStorage::updateExternalDynamicMetadataIfExists(std::shared_ptr<DB::Context const>) @ 0x00000000199046e0
2025.09.04 13:15:52.551259 [ 1764115 ] {} <Fatal> BaseDaemon: 9. ci/tmp/build/./src/Analyzer/Resolve/IdentifierResolver.cpp:203: DB::IdentifierResolver::tryResolveTableIdentifier(DB::Identifier const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001ab8f7d3
2025.09.04 13:15:52.572676 [ 1764115 ] {} <Fatal> BaseDaemon: 10. ci/tmp/build/./src/Analyzer/Resolve/IdentifierResolver.cpp:217: DB::IdentifierResolver::tryResolveTableIdentifierFromDatabaseCatalog(DB::Identifier const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001ab8ffd3
2025.09.04 13:15:52.672311 [ 1764115 ] {} <Fatal> BaseDaemon: 11. ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:1660: DB::QueryAnalyzer::tryResolveIdentifier(DB::IdentifierLookup const&, DB::IdentifierResolveScope&, DB::IdentifierResolveContext) @ 0x000000001a8dde85
2025.09.04 13:15:52.759639 [ 1764115 ] {} <Fatal> BaseDaemon: 12. ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:4593: DB::QueryAnalyzer::initializeQueryJoinTreeNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x000000001a8f94d0
2025.09.04 13:15:52.843617 [ 1764115 ] {} <Fatal> BaseDaemon: 13. ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:5949: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000001a8c5b94
2025.09.04 13:15:52.919927 [ 1764115 ] {} <Fatal> BaseDaemon: 14. ci/tmp/build/./src/Analyzer/Resolve/QueryAnalyzer.cpp:187: DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x000000001a8c4bf6
2025.09.04 13:15:52.922282 [ 1764115 ] {} <Fatal> BaseDaemon: 15. ci/tmp/build/./src/Analyzer/Resolve/QueryAnalysisPass.cpp:18: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x000000001a8c420e
2025.09.04 13:15:52.931013 [ 1764115 ] {} <Fatal> BaseDaemon: 16. ci/tmp/build/./src/Analyzer/QueryTreePassManager.cpp:188: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x000000001a92b113
2025.09.04 13:15:52.952671 [ 1764115 ] {} <Fatal> BaseDaemon: 17. ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:165: DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x000000001b4fae67
2025.09.04 13:15:52.970132 [ 1764115 ] {} <Fatal> BaseDaemon: 18. ci/tmp/build/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:182: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000001b4f95ed
2025.09.04 13:15:52.991163 [ 1764115 ] {} <Fatal> BaseDaemon: 19. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::make_unique[abi:se190107]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000001b4fc0f0
2025.09.04 13:15:52.998342 [ 1764115 ] {} <Fatal> BaseDaemon: 20.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.09.04 13:15:52.998374 [ 1764115 ] {} <Fatal> BaseDaemon: 20.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.09.04 13:15:52.998382 [ 1764115 ] {} <Fatal> BaseDaemon: 20. ci/tmp/build/./src/Interpreters/InterpreterFactory.cpp:395: DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x000000001b487aeb
2025.09.04 13:15:53.038764 [ 1764115 ] {} <Fatal> BaseDaemon: 21. ci/tmp/build/./src/Interpreters/executeQuery.cpp:1516: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001b80256c
2025.09.04 13:15:53.087430 [ 1764115 ] {} <Fatal> BaseDaemon: 22. ci/tmp/build/./src/Interpreters/executeQuery.cpp:1790: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001b7fc985
2025.09.04 13:15:53.123836 [ 1764115 ] {} <Fatal> BaseDaemon: 23. ci/tmp/build/./src/Server/TCPHandler.cpp:739: DB::TCPHandler::runImpl() @ 0x000000001f234bcf
2025.09.04 13:15:53.184505 [ 1764115 ] {} <Fatal> BaseDaemon: 24. ci/tmp/build/./src/Server/TCPHandler.cpp:2740: DB::TCPHandler::run() @ 0x000000001f24ea64
2025.09.04 13:15:53.188317 [ 1764115 ] {} <Fatal> BaseDaemon: 25. ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000027500907
2025.09.04 13:15:53.193205 [ 1764115 ] {} <Fatal> BaseDaemon: 26. ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000027500ee5
2025.09.04 13:15:53.197980 [ 1764115 ] {} <Fatal> BaseDaemon: 27. ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000274a00bf
2025.09.04 13:15:53.202506 [ 1764115 ] {} <Fatal> BaseDaemon: 28. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000002749d791
2025.09.04 13:15:53.202552 [ 1764115 ] {} <Fatal> BaseDaemon: 29. start_thread @ 0x00000000000a27f1
2025.09.04 13:15:53.202585 [ 1764115 ] {} <Fatal> BaseDaemon: 30. __clone3 @ 0x0000000000133c9c
2025.09.04 13:15:53.418280 [ 1764115 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 076D0EEA4A326B65E32EC54D16B6ADD9)
2025.09.04 13:15:53.430018 [ 1764115 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.09.04 13:15:53.430277 [ 1764115 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, s3_create_new_file_on_insert = true, azure_create_new_file_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, enable_lightweight_update = true, iceberg_metadata_log_level = 'metadata', allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, query_plan_max_limit_for_lazy_materialization = 0, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_live_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_shared_set_join = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by divanik**
Closes https://github.com/ClickHouse/ClickHouse/issues/86681

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Throws an error if iceberg_metadata_log is not configured, but user tries to get debug iceberg metadata info. Fixes nullptr access

### CODE REVIEW

File: src/Interpreters/IcebergMetadataLog.cpp [hunk 1]
```diff
@@ -95,7 +95,14 @@ void insertRowToLogTable(
     if (clock_gettime(CLOCK_REALTIME, &spec))
         throw ErrnoException(ErrorCodes::CANNOT_CLOCK_GETTIME, "Cannot clock_gettime");
 
-    Context::getGlobalContextInstance()->getIcebergMetadataLog()->add(
+    auto iceberg_metadata_log = Context::getGlobalContextInstance()->getIcebergMetadataLog();
+
+    if (!iceberg_metadata_log)
+    {
+        throw Exception(ErrorCodes::UNSUPPORTED_METHOD, "Iceberg metadata log table is not configured");
```
Comment (scanhex12) [inline src/Interpreters/IcebergMetadataLog.cpp]: Not sure that it's UNSUPPORTED_METHOD. BAD_ARGUMENTS seems better

**Review by scanhex12 — APPROVED** [review]

File: src/Interpreters/IcebergMetadataLog.cpp (hunk 1 above)
Comment (divanik) [reply src/Interpreters/IcebergMetadataLog.cpp]: I thought about this and came to conclusion that there is no error code which convey sense of an error precisely, so I can put BAD_ARGUMENTS if you wish

**Comment by divanik** [comment]
Flaky checks:
[AST fuzzer (amd_msan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87250&sha=latest&name_0=PR&name_1=AST+fuzzer+%28amd_msan%29) - https://github.com/ClickHouse/ClickHouse/issues/84186
