### PR TITLE
Fix exception "File segment can be completed only by downloader" in tests

### LINKED ISSUE #36141: `02241_remote_filesystem_cache_on_insert` is flaky
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjItMDMtMDEnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcwMjI0MV9yZW1vdGVfZmlsZXN5c3RlbV9jYWNoZV9vbl9pbnNlcnQlJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJywgJ0VSUk9SJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=

https://s3.amazonaws.com/clickhouse-test-reports/0/972357ebf63dfecdc8d3ec968b0e9bf321fabf54/stateless_tests__aarch64__actions_/runlog.log

```
2022-04-11 23:59:43 02241_remote_filesystem_cache_on_insert:                                [ FAIL ] 0.84 sec. - return code: 132
2022-04-11 23:59:43 [341676e869ff] 2022.04.11 23:59:43.433760 [ 136034 ] {dc9a4c3d-b47d-4ede-b22f-8e0dd96aae6d} <Error> executeQuery: Code: 644. DB::Exception: File segment can be completed only by downloader: Cache info: Buffer path: ibilietocgcnbenmvxxcoqrohopblfaf, hash key: 3f1f970e2842e56da96a85aff18ac8f4, file_offset_of_buffer_end: 4194304, internal buffer remaining read range: 4194304-4194303, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: dc9a4c3d-b47d-4ede-b22f-8e0dd96aae6d:145741, file segment info: File segment: [0, 4194303], state: DOWNLOADED, downloaded size: 4194304, downloader id: , caller id: dc9a4c3d-b47d-4ede-b22f-8e0dd96aae6d:145741: (while reading column value): (while reading from part /var/lib/clickhouse/disks/s3_cache/store/24c/24c1cd6b-0d9a-406b-beaa-c03df39cc106/all_7_7_0/ from mark 86 with max_rows_to_read = 75091): While executing MergeTreeThread. (REMOTE_FS_OBJECT_CACHE_ERROR) (version 22.4.1.1811 (official build)) (from [::1]:45928) (comment: 02241_remote_filesystem_cache_on_insert.sql) (in query: SELECT count() FROM test WHERE value LIKE '%010%';), Stack trace (when copying this message, always include the lines below):
2022-04-11 23:59:43 
2022-04-11 23:59:43 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x97855ac in /usr/bin/clickhouse
2022-04-11 23:59:43 1. DB::FileSegment::completeBatchAndResetDownloader() @ 0x11e2fee0 in /usr/bin/clickhouse
2022-04-11 23:59:43 2. DB::CachedReadBufferFromRemoteFS::nextImplStep() @ 0x1244f6d0 in /usr/bin/clickhouse
2022-04-11 23:59:43 3. DB::CachedReadBufferFromRemoteFS::nextImpl() @ 0x1244ea14 in /usr/bin/clickhouse
2022-04-11 23:59:43 4. DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x12448db0 in /usr/bin/clickhouse
2022-04-11 23:59:43 5. DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x12448b74 in /usr/bin/clickhouse
2022-04-11 23:59:43 6. ? @ 0x12446fd4 in /usr/bin/clickhouse
2022-04-11 23:59:43 7. std::__1::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() @ 0x11e72f24 in /usr/bin/clickhouse
2022-04-11 23:59:43 8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x982bfa4 in /usr/bin/clickhouse
2022-04-11 23:59:43 9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x982e328 in /usr/bin/clickhouse
2022-04-11 23:59:43 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9829384 in /usr/bin/clickhouse
2022-04-11 23:59:43 11. ? @ 0x982cee4 in /usr/bin/clickhouse
2022-04-11 23:59:43 12. start_thread @ 0x751c in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so
2022-04-11 23:59:43 13. ? @ 0xd122c in /usr/lib/aarch64-linux-gnu/libc-2.31.so
2022-04-11 23:59:43 
2022-04-11 23:59:43 Received exception from server (version 22.4.1):
2022-04-11 23:59:43 Code: 644. DB::Exception: Received from localhost:9000. DB::Exception: File segment can be completed only by downloader: Cache info: Buffer path: ibilietocgcnbenmvxxcoqrohopblfaf, hash key: 3f1f970e2842e56da96a85aff18ac8f4, file_offset_of_buffer_end: 4194304, internal buffer remaining read range: 4194304-4194303, read_type: REMOTE_FS_READ_AND_PUT_IN_CACHE, last caller: dc9a4c3d-b47d-4ede-b22f-8e0dd96aae6d:145741, file segment info: File segment: [0, 4194303], state: DOWNLOADED, downloaded size: 4194304, downloader id: , caller id: dc9a4c3d-b47d-4ede-b22f-8e0dd96aae6d:145741: (while reading column value): (while reading from part /var/lib/clickhouse/disks/s3_cache/store/24c/24c1cd6b-0d9a-406b-beaa-c03df39cc106/all_7_7_0/ from mark 86 with max_rows_to_read = 75091): While executing MergeTreeThread. (REMOTE_FS_OBJECT_CACHE_ERROR)
2022-04-11 23:59:43 (query: SELECT count() FROM test WHERE value LIKE '%010%';)
2022-04-11 23:59:43 , result:
2022-04-11 23:59:43 
2022-04-11 23:59:43 -- { echo }
2022-04-11 23:59:43 
2022-04-11 23:59:43 SET enable_filesystem_cache_on_write_operations=1;
2022-04-11 23:59:43 DROP TABLE IF EXISTS test;
2022-04-11 23:59:43 CREATE TABLE test (key UInt32, value String) Engine=MergeTree() ORDER BY key SETTINGS storage_policy='s3_cache', min_bytes_for_wide_part = 10485760;
2022-04-11 23:59:43 SYSTEM DROP FILESYSTEM CACHE;
2022-04-11 23:59:43 SELECT file_segment_range_begin, file_segment_range_end, size, state FROM (SELECT file_segment_range_begin, file_segment_range_end, size, state, local_path FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path) WHERE endsWith(local_path, 'data.bin') FORMAT Vertical;
2022-04-11 23:59:43 SELECT count() FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path;
2022-04-11 23:59:43 0
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 0
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100);
2022-04-11 23:59:43 SELECT file_segment_range_begin, file_segment_range_end, size, state FROM (SELECT file_segment_range_begin, file_segment_range_end, size, state, local_path FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path) WHERE endsWith(local_path, 'data.bin') FORMAT Vertical;
2022-04-11 23:59:43 Row 1:
2022-04-11 23:59:43 ──────
2022-04-11 23:59:43 file_segment_range_begin: 0
2022-04-11 23:59:43 file_segment_range_end:   745
2022-04-11 23:59:43 size:                     746
2022-04-11 23:59:43 state:                    DOWNLOADED
2022-04-11 23:59:43 SELECT count() FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache WHERE cache_hits > 0;
2022-04-11 23:59:43 0
2022-04-11 23:59:43 SELECT  * FROM test FORMAT Null;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache WHERE cache_hits > 0;
2022-04-11 23:59:43 2
2022-04-11 23:59:43 SELECT  * FROM test FORMAT Null;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache WHERE cache_hits > 0;
2022-04-11 23:59:43 2
2022-04-11 23:59:43 SELECT count() size FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SYSTEM DROP FILESYSTEM CACHE;
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100, 200);
2022-04-11 23:59:43 SELECT file_segment_range_begin, file_segment_range_end, size, state FROM (SELECT file_segment_range_begin, file_segment_range_end, size, state, local_path FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path) WHERE endsWith(local_path, 'data.bin') FORMAT Vertical;
2022-04-11 23:59:43 Row 1:
2022-04-11 23:59:43 ──────
2022-04-11 23:59:43 file_segment_range_begin: 0
2022-04-11 23:59:43 file_segment_range_end:   1659
2022-04-11 23:59:43 size:                     1660
2022-04-11 23:59:43 state:                    DOWNLOADED
2022-04-11 23:59:43 SELECT count() FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100) SETTINGS enable_filesystem_cache_on_write_operations=0;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100);
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(300, 10000);
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 21
2022-04-11 23:59:43 OPTIMIZE TABLE test FINAL;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 27
2022-04-11 23:59:43 SET mutations_sync=2;
2022-04-11 23:59:43 ALTER TABLE test UPDATE value = 'kek' WHERE key = 100;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 28
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(5000000);
2022-04-11 23:59:43 SYSTEM FLUSH LOGS;
2022-04-11 23:59:43 SELECT query, ProfileEvents['RemoteFSReadBytes'] > 0 as remote_fs_read
2022-04-11 23:59:43 FROM system.query_log
2022-04-11 23:59:43 WHERE query LIKE 'SELECT number, toString(number) FROM numbers(5000000)%'
2022-04-11 23:59:43 AND type = 'QueryFinish'
2022-04-11 23:59:43 AND current_database = currentDatabase()
2022-04-11 23:59:43 ORDER BY query_start_time DESC
2022-04-11 23:59:43 LIMIT 1;
2022-04-11 23:59:43 SELECT count() FROM test;
2022-04-11 23:59:43 5010500
2022-04-11 23:59:43 SELECT count() FROM test WHERE value LIKE '%010%';
2022-04-11 23:59:43 
2022-04-11 23:59:43 stdout:
2022-04-11 23:59:43 -- { echo }
2022-04-11 23:59:43 
2022-04-11 23:59:43 SET enable_filesystem_cache_on_write_operations=1;
2022-04-11 23:59:43 DROP TABLE IF EXISTS test;
2022-04-11 23:59:43 CREATE TABLE test (key UInt32, value String) Engine=MergeTree() ORDER BY key SETTINGS storage_policy='s3_cache', min_bytes_for_wide_part = 10485760;
2022-04-11 23:59:43 SYSTEM DROP FILESYSTEM CACHE;
2022-04-11 23:59:43 SELECT file_segment_range_begin, file_segment_range_end, size, state FROM (SELECT file_segment_range_begin, file_segment_range_end, size, state, local_path FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path) WHERE endsWith(local_path, 'data.bin') FORMAT Vertical;
2022-04-11 23:59:43 SELECT count() FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path;
2022-04-11 23:59:43 0
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 0
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100);
2022-04-11 23:59:43 SELECT file_segment_range_begin, file_segment_range_end, size, state FROM (SELECT file_segment_range_begin, file_segment_range_end, size, state, local_path FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path) WHERE endsWith(local_path, 'data.bin') FORMAT Vertical;
2022-04-11 23:59:43 Row 1:
2022-04-11 23:59:43 ──────
2022-04-11 23:59:43 file_segment_range_begin: 0
2022-04-11 23:59:43 file_segment_range_end:   745
2022-04-11 23:59:43 size:                     746
2022-04-11 23:59:43 state:                    DOWNLOADED
2022-04-11 23:59:43 SELECT count() FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache WHERE cache_hits > 0;
2022-04-11 23:59:43 0
2022-04-11 23:59:43 SELECT  * FROM test FORMAT Null;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache WHERE cache_hits > 0;
2022-04-11 23:59:43 2
2022-04-11 23:59:43 SELECT  * FROM test FORMAT Null;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache WHERE cache_hits > 0;
2022-04-11 23:59:43 2
2022-04-11 23:59:43 SELECT count() size FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SYSTEM DROP FILESYSTEM CACHE;
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100, 200);
2022-04-11 23:59:43 SELECT file_segment_range_begin, file_segment_range_end, size, state FROM (SELECT file_segment_range_begin, file_segment_range_end, size, state, local_path FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path) WHERE endsWith(local_path, 'data.bin') FORMAT Vertical;
2022-04-11 23:59:43 Row 1:
2022-04-11 23:59:43 ──────
2022-04-11 23:59:43 file_segment_range_begin: 0
2022-04-11 23:59:43 file_segment_range_end:   1659
2022-04-11 23:59:43 size:                     1660
2022-04-11 23:59:43 state:                    DOWNLOADED
2022-04-11 23:59:43 SELECT count() FROM (SELECT arrayJoin(cache_paths) AS cache_path, local_path, remote_path FROM system.remote_data_paths ) AS data_paths INNER JOIN system.filesystem_cache AS caches ON data_paths.cache_path = caches.cache_path;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100) SETTINGS enable_filesystem_cache_on_write_operations=0;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 7
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(100);
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(300, 10000);
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 21
2022-04-11 23:59:43 OPTIMIZE TABLE test FINAL;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 27
2022-04-11 23:59:43 SET mutations_sync=2;
2022-04-11 23:59:43 ALTER TABLE test UPDATE value = 'kek' WHERE key = 100;
2022-04-11 23:59:43 SELECT count() FROM system.filesystem_cache;
2022-04-11 23:59:43 28
2022-04-11 23:59:43 INSERT INTO test SELECT number, toString(number) FROM numbers(5000000);
2022-04-11 23:59:43 SYSTEM FLUSH LOGS;
2022-04-11 23:59:43 SELECT query, ProfileEvents['RemoteFSReadBytes'] > 0 as remote_fs_read
2022-04-11 23:59:43 FROM system.query_log
2022-04-11 23:59:43 WHERE query LIKE 'SELECT number, toString(number) FROM numbers(5000000)%'
2022-04-11 23:59:43 AND type = 'QueryFinish'
2022-04-11 23:59:43 AND current_database = currentDatabase()
2022-04-11 23:59:43 ORDER BY query_start_time DESC
2022-04-11 23:59:43 LIMIT 1;
2022-04-11 23:59:43 SELECT count() FROM test;
2022-04-11 23:59:43 5010500
2022-04-11 23:59:43 SELECT count() FROM test WHERE value LIKE '%010%';
2022-04-11 23:59:43 
2022-04-11 23:59:43 
2022-04-11 23:59:43 Settings used in the test: --max_insert_threads=14 --group_by_two_level_threshold=100000 --group_by_two_level_threshold_bytes=50000000 --distributed_aggregation_memory_efficient=0 --fsync_metadata=1 --priority=0 --output_format_parallel_formatting=0 --input_format_parallel_parsing=1 --min_chunk_bytes_for_parallel_parsing=6277119 --max_read_buffer_size=646842 --prefer_localhost_replica=0 --max_block_size=75091 --max_threads=10
2022-04-11 23:59:43 
2022-04-11 23:59:43 Database: test_v1qwhp
```

cc: @kssenii

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/36141.

### CODE REVIEW

File: src/Common/FileSegment.cpp [hunk 1]
```diff
@@ -492,8 +502,12 @@ void FileSegment::complete(std::lock_guard<std::mutex> & cache_lock)
     if (download_state == State::SKIP_CACHE || detached)
         return;
 
-    if (download_state != State::DOWNLOADED && getDownloadedSize(segment_lock) == range().size())
+    if (isDownloaderImpl(segment_lock)
```
Comment (kssenii) [inline src/Common/FileSegment.cpp:505]: The fix is in this line.
There could be a race: in this place anyone could mark the segment as downloaded in case downloaded_size equals file segment size. This is possible in case downloader updated downloaded size but did not yet call `completeFileSegmentAndResetDownloader`.

Comment (qoega) [reply src/Common/FileSegment.cpp:505]: Maybe add it as comment?

**Review by alesapin — APPROVED** [review]
