### PR TITLE
Fix inconsistent parts after clone replica

### LINKED ISSUE #6522: Inconsistent parts after DROP PARTITION and outdated replica restore
**Describe the bug**
If active replicas have executed `DROP PARTITION` while some replica was lost, the set of data parts will be inconsistent after recovery of lost replica.

**How to reproduce**
See test in the related PR.

**Expected behavior**
Consistent set of parts on all replicas.

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):
Fixes #6522

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: dbms/src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -1956,10 +1956,37 @@ void StorageReplicatedMergeTree::cloneReplica(const String & source_replica, Coo
...
+    for (const auto & part : local_parts_in_zk)
+    {
+        if (active_parts_set.getContainingPart(part).empty())
+        {
+            queue.remove(zookeeper, part);
+            parts_to_remove_from_zk.emplace_back(part);
+            LOG_WARNING(log, "Source replica does not have part " << part << ". Removing it from ZooKeeper.");
+        }
+    }
+    tryRemovePartsFromZooKeeperWithRetries(parts_to_remove_from_zk);
```
Comment (alexey-milovidov) [inline dbms/src/Storages/StorageReplicatedMergeTree.cpp]: Ok. But all usages of this function look suspicious because result is not checked.

**Comment by alexey-milovidov** [comment]
Also one thought: why don't we clone `queue` and `parts` from source replica, totally replacing our `queue` and `parts`? Maybe because it's more difficult to do atomically?
