### PR TITLE
Fix_kql_issue_found_by_wingfuzz

### LINKED ISSUE #59036: Clickhouse server v24.1.1.1 `SEGV` inside `DB::ParserKQLQuery::parseImpl`
**Describe the bug**

ClickHouse server version 24.1.1.1 received SIGSEGV signal
It was found by an in-development fuzzer of WINGFUZZ.

**How to reproduce**

The SQL statement to reproduce **(it is need to execute line by line)**: [poc-1.sql](https://drive.google.com/file/d/1LksdMH1DYP1s6GqlJ6dwbGRBfcRSsrsV/view?usp=sharing)

**Stacktrace**

```txt
Thread 3 "HTTPHandler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff3cced640 (LWP 704540)]
DB::ParserKQLQuery::parseImpl (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/Kusto/ParserKQLQuery.cpp:376
376     ./build/./src/Parsers/Kusto/ParserKQLQuery.cpp: No such file or directory.
(gdb) bt
#0  DB::ParserKQLQuery::parseImpl (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/Kusto/ParserKQLQuery.cpp:376
#1  0x0000000016ca6c2e in DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0::operator()() const (this=<optimized out>) at ./build/./src/Parsers/IParserBase.cpp:13
#2  DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&) (pos=..., func=...) at ./src/Parsers/IParserBase.h:31
#3  DB::IParserBase::parse (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/IParserBase.cpp:11
#4  0x0000000016df9fda in DB::ParserKQLWithUnionQuery::parseImpl (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/Kusto/ParserKQLStatement.cpp:42
#5  0x0000000016ca6c2e in DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0::operator()() const (this=<optimized out>) at ./build/./src/Parsers/IParserBase.cpp:13
#6  DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&) (pos=..., func=...) at ./src/Parsers/IParserBase.h:31
#7  DB::IParserBase::parse (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/IParserBase.cpp:11
#8  0x0000000016df9e14 in DB::ParserKQLWithOutput::parseImpl (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/Kusto/ParserKQLStatement.cpp:28
#9  0x0000000016ca6c2e in DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0::operator()() const (this=<optimized out>) at ./build/./src/Parsers/IParserBase.cpp:13
#10 DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&) (pos=..., func=...) at ./src/Parsers/IParserBase.h:31
#11 DB::IParserBase::parse (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/IParserBase.cpp:11
#12 0x0000000016df9d58 in DB::ParserKQLStatement::parseImpl (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/Kusto/ParserKQLStatement.cpp:18
#13 0x0000000016ca6c2e in DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0::operator()() const (this=<optimized out>) at ./build/./src/Parsers/IParserBase.cpp:13
#14 DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&) (pos=..., func=...) at ./src/Parsers/IParserBase.h:31
#15 DB::IParserBase::parse (this=<optimized out>, pos=..., node=..., expected=...) at ./build/./src/Parsers/IParserBase.cpp:11
#16 0x0000000016e590e2 in DB::tryParseKQLQuery (parser=...,
    _out_query_end=@0x7fff3cce9240: 0x7ff844077f40 "INSERT INTO DATE_INFO_DICT (TV, SHAMSI, HIJRI, MILADI, S_DAY, H_DAY, S_MONTH, H_MONTH, WEEK_DAY_NAME, DAY_NUMBER, HOLIDAY, WEEK_NAME) VALUES ('2017-04-01', '1396-01-12', '1438-07-04', '2017-04-01', 12"...,
    all_queries_end=all_queries_end@entry=0x7ff8440b7f41 "\377", out_error_message=..., hilite=false, query_description=..., allow_multi_statements=<optimized out>, max_query_size=262144, max_parser_depth=1000, skip_insignificant=<optimized out>)
    at ./build/./src/Parsers/Kusto/parseKQLQuery.cpp:350
#17 0x0000000016e5dad9 in DB::parseKQLQueryAndMovePosition (parser=..., pos=<error reading variable: Cannot access memory at address 0x60012>, end=0x7ff8446e7f80 "\002", end@entry=0x7ff8440b7f41 "\377", query_description=..., allow_multi_statements=6,
    max_query_size=231, max_query_size@entry=262144, max_parser_depth=399957032) at ./build/./src/Parsers/Kusto/parseKQLQuery.cpp:447
#18 0x0000000016e5dca2 in DB::parseKQLQuery (parser=...,
    begin=0x7ff844077f40 "INSERT INTO DATE_INFO_DICT (TV, SHAMSI, HIJRI, MILADI, S_DAY, H_DAY, S_MONTH, H_MONTH, WEEK_DAY_NAME, DAY_NUMBER, HOLIDAY, WEEK_NAME) VALUES ('2017-04-01', '1396-01-12', '1438-07-04', '2017-04-01', 12"..., end=0x7ff8446e7f80 "\002",
    end@entry=0x7ff8440b7f41 "\377", query_description=..., max_query_size=131078, max_query_size@entry=262144, max_parser_depth=<optimized out>) at ./build/./src/Parsers/Kusto/parseKQLQuery.cpp:463
#19 0x0000000014b1788e in DB::executeQueryImpl (
    begin=begin@entry=0x7ff844077f40 "INSERT INTO DATE_INFO_DICT (TV, SHAMSI, HIJRI, MILADI, S_DAY, H_DAY, S_MONTH, H_MONTH, WEEK_DAY_NAME, DAY_NUMBER, HOLIDAY, WEEK_NAME) VALUES ('2017-04-01', '1396-01-12', '1438-07-04', '2017-04-01', 12"...,
    end=end@entry=0x7ff8440b7f41 "\377", context=..., flags=..., stage=DB::QueryProcessingStage::Complete, istr=0x7ff844105900) at ./build/./src/Interpreters/executeQuery.cpp:715
#20 0x0000000014b23a3e in DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void (DB::IOutputFormat&)>) (istr=..., ostr=..., allow_into_outfile=false, context=..., set_result_details=..., flags=..., output_format_settings=..., handle_exception_in_output_format=...) at ./build/./src/Interpreters/executeQuery.cpp:1396
#21 0x00000000162b2cd4 in DB::HTTPHandler::processQuery (this=this@entry=0x7ff844101920, request=..., params=..., response=..., used_output=..., query_scope=..., write_event=...) at ./build/./src/Server/HTTPHandler.cpp:901
#22 0x00000000162ba58a in DB::HTTPHandler::handleRequest (this=0x7ff844101920, request=..., response=..., write_event=...) at ./build/./src/Server/HTTPHandler.cpp:1102
#23 0x0000000016389b4a in DB::HTTPServerConnection::run (this=0x7ff8443151f0) at ./build/./src/Server/HTTP/HTTPServerConnection.cpp:70
#24 0x000000001758b7e8 in Poco::Net::TCPServerConnection::start (this=0x17d6dc28 <__afl_area_ptr>) at ./build/./base/poco/Net/src/TCPServerConnection.cpp:43
#25 0x000000001758c2f3 in Poco::Net::TCPServerDispatcher::run (this=0x1b0b2830) at ./build/./base/poco/Net/src/TCPServerDispatcher.cpp:115
#26 0x0000000017616d01 in Poco::PooledThread::run (this=0x1a1c6180) at ./build/./base/poco/Foundation/src/ThreadPool.cpp:188
#27 0x000000001761351c in Poco::ThreadImpl::runnableEntry (pThread=<optimized out>) at ./base/poco/Foundation/src/Thread_POSIX.cpp:335
#28 0x00007ffff7e08ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#29 0x00007ffff7e9a850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```

**Server log**

```txt
2024.01.19 15:12:34.326756 [ 707037 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.01.19 15:12:34.326807 [ 707037 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 1319B83D2FDC4C3F91EFCCF1725FDD21F7D0ADBF, git hash: ce13b21d95e610593d49e5cadc1888e3313892ef) (from thread 704540) Received signal 11
2024.01.19 15:12:34.326837 [ 707037 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.01.19 15:12:34.326814 [ 704541 ] {} <Trace> DynamicQueryHandler: Request URI: /query?database=default&default_format=ODBCDriver2&session_id=clickhouse_odbc_11482216046058260007
2024.01.19 15:12:34.326864 [ 707037 ] {} <Fatal> BaseDaemon: Address: 0x7ff8449e8010. Access: read. Attempted access has violated the permissions assigned to the memory area.
2024.01.19 15:12:34.326912 [ 704541 ] {} <Debug> HTTP-Session: 21a7a92f-6564-46f5-861c-0107d0edf31a Authenticating user 'default' from 127.0.0.1:40954
2024.01.19 15:12:34.326924 [ 707037 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000016e07aec 0x0000000016ca6c2e 0x0000000016df9fda 0x0000000016ca6c2e 0x0000000016df9e14 0x0000000016ca6c2e 0x0000000016df9d58 0x0000000016ca6c2e 0x0000000016e590e2 0x0000000016e5dad9 0x0000000016e5dca2 0x0000000014b1788e 0x0000000014b23a3e 0x00000000162b2cd4 0x00000000162ba58a 0x0000000016389b4a 0x000000001758b7e8 0x000000001758c2f3 0x0000000017616d01 0x000000001761351c 0x00007ffff7e08ac3 0x00007ffff7e9a850
2024.01.19 15:12:34.326953 [ 707037 ] {} <Fatal> BaseDaemon: ########################################
2024.01.19 15:12:34.326964 [ 707037 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 1319B83D2FDC4C3F91EFCCF1725FDD21F7D0ADBF, git hash: ce13b21d95e610593d49e5cadc1888e3313892ef) (from thread 704540) (query_id: 52d46ce3-3daf-4745-8c96-daea0ba12382) (query: ) Received signal Segmentation fault (11)
2024.01.19 15:12:34.326972 [ 707037 ] {} <Fatal> BaseDaemon: Address: 0x7ff8449e8010. Access: read. Attempted access has violated the permissions assigned to the memory area.
2024.01.19 15:12:34.326989 [ 707037 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000016e07aec 0x0000000016ca6c2e 0x0000000016df9fda 0x0000000016ca6c2e 0x0000000016df9e14 0x0000000016ca6c2e 0x0000000016df9d58 0x0000000016ca6c2e 0x0000000016e590e2 0x0000000016e5dad9 0x0000000016e5dca2 0x0000000014b1788e 0x0000000014b23a3e 0x00000000162b2cd4 0x00000000162ba58a 0x0000000016389b4a 0x000000001758b7e8 0x000000001758c2f3 0x0000000017616d01 0x000000001761351c 0x00007ffff7e08ac3 0x00007ffff7e9a850
2024.01.19 15:12:34.327000 [ 704541 ] {} <Debug> HTTP-Session: 21a7a92f-6564-46f5-861c-0107d0edf31a Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2024.01.19 15:12:34.327051 [ 704541 ] {} <Debug> HTTP-Session: 21a7a92f-6564-46f5-861c-0107d0edf31a Creating named session context with name: clickhouse_odbc_11482216046058260007, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2024.01.19 15:12:34.327089 [ 704541 ] {} <Trace> NamedSessionsStorage: Reuse session from storage with session_id: clickhouse_odbc_11482216046058260007, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2024.01.19 15:12:34.358287 [ 704541 ] {} <Error> DynamicQueryHandler: Code: 373. DB::Exception: Session clickhouse_odbc_11482216046058260007 is locked by a concurrent client. (SESSION_IS_LOCKED), Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x00000000175a3d18 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
1. ./build/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b42f15c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2. ./contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000294cfc7 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
3. ./build/./src/Interpreters/Session.cpp:133: DB::NamedSessionsStorage::acquireSession(std::shared_ptr<DB::Context const> const&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, String const&, std::chrono::duration<long long, std::ratio<1l, 1000000000l>>, bool) @ 0x00000000146f738c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:612: DB::Session::makeSessionContext(String const&, std::chrono::duration<long long, std::ratio<1l, 1000000000l>>, bool) @ 0x00000000146f4d58 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTPHandler.cpp:583: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162ad843 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162ba58a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ? @ 0x00007ffff7e08ac3 in ?
13. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.379818 [ 707037 ] {} <Fatal> BaseDaemon: 3.1. inlined from ./src/Parsers/Lexer.h:102: DB::Token::isEnd() const
2024.01.19 15:12:34.379868 [ 707037 ] {} <Fatal> BaseDaemon: 3. ./build/./src/Parsers/Kusto/ParserKQLQuery.cpp:376: DB::ParserKQLQuery::parseImpl(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016e07aec in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.385430 [ 707037 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./build/./src/Parsers/IParserBase.cpp:13: operator()
2024.01.19 15:12:34.385467 [ 707037 ] {} <Fatal> BaseDaemon: 4.2. inlined from ./src/Parsers/IParserBase.h:31: bool DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&)
2024.01.19 15:12:34.385490 [ 707037 ] {} <Fatal> BaseDaemon: 4. ./build/./src/Parsers/IParserBase.cpp:11: DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016ca6c2e in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.393114 [ 707037 ] {} <Fatal> BaseDaemon: 5. ./build/./src/Parsers/Kusto/ParserKQLStatement.cpp:42: DB::ParserKQLWithUnionQuery::parseImpl(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016df9fda in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.398726 [ 707037 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build/./src/Parsers/IParserBase.cpp:13: operator()
2024.01.19 15:12:34.398757 [ 707037 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./src/Parsers/IParserBase.h:31: bool DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&)
2024.01.19 15:12:34.398763 [ 707037 ] {} <Fatal> BaseDaemon: 6. ./build/./src/Parsers/IParserBase.cpp:11: DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016ca6c2e in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.410300 [ 707037 ] {} <Fatal> BaseDaemon: 7. ./build/./src/Parsers/Kusto/ParserKQLStatement.cpp:0: DB::ParserKQLWithOutput::parseImpl(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016df9e14 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.420066 [ 707037 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build/./src/Parsers/IParserBase.cpp:13: operator()
2024.01.19 15:12:34.420105 [ 707037 ] {} <Fatal> BaseDaemon: 8.2. inlined from ./src/Parsers/IParserBase.h:31: bool DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&)
2024.01.19 15:12:34.420126 [ 707037 ] {} <Fatal> BaseDaemon: 8. ./build/./src/Parsers/IParserBase.cpp:11: DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016ca6c2e in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.431057 [ 707037 ] {} <Fatal> BaseDaemon: 9. ./build/./src/Parsers/Kusto/ParserKQLStatement.cpp:18: DB::ParserKQLStatement::parseImpl(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016df9d58 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.438794 [ 704516 ] {} <Trace> BaseDaemon: Received signal -1
2024.01.19 15:12:34.438898 [ 704516 ] {} <Fatal> BaseDaemon: (version 24.1.1.1, build id: 1319B83D2FDC4C3F91EFCCF1725FDD21F7D0ADBF, git hash: ce13b21d95e610593d49e5cadc1888e3313892ef) (from thread 704541) Terminate called for uncaught exception:
2024.01.19 15:12:34.438917 [ 704516 ] {} <Fatal> BaseDaemon: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (127.0.0.1:5273 -> 127.0.0.1:40954). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x00000000175a3d18 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
1. ./build/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b42f15c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2. ./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000b86575a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
3. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:116: DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000b864fe2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.438979 [ 704516 ] {} <Fatal> BaseDaemon:
0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x00000000175a3d18 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
1. ./build/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b42f15c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2. ./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000b86575a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
3. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:116: DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000b864fe2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439013 [ 704516 ] {} <Fatal> BaseDaemon: 0. ./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(String const&, int) @ 0x00000000175a3d18 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
1. ./build/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b42f15c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2. ./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000b86575a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
3. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:116: DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000b864fe2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439050 [ 704516 ] {} <Fatal> BaseDaemon: 1. ./build/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000b42f15c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2. ./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000b86575a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
3. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:116: DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000b864fe2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439094 [ 704516 ] {} <Fatal> BaseDaemon: 2. ./contrib/llvm-project/libcxx/include/string:1499: DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000b86575a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
3. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:116: DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000b864fe2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439158 [ 704516 ] {} <Fatal> BaseDaemon: 3. ./build/./src/IO/WriteBufferFromPocoSocket.cpp:116: DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000b864fe2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439198 [ 704516 ] {} <Fatal> BaseDaemon: 4. ./src/IO/WriteBufferFromString.h:0: DB::WriteBufferFromHTTPServerResponse::writeHeaderProgressImpl(char const*) @ 0x00000000163922f5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439423 [ 704516 ] {} <Fatal> BaseDaemon: 5. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:82: DB::WriteBufferFromHTTPServerResponse::finishSendHeaders() @ 0x0000000016392803 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439461 [ 704516 ] {} <Fatal> BaseDaemon: 6. ./contrib/llvm-project/libcxx/include/__mutex_base:0: DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000016393502 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439508 [ 704516 ] {} <Fatal> BaseDaemon: 7. ./src/IO/WriteBuffer.h:128: DB::WriteBuffer::finalize() @ 0x0000000002935c62 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439550 [ 704516 ] {} <Fatal> BaseDaemon: 8. ./build/./src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp:157: DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse() @ 0x00000000163933aa in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439605 [ 704516 ] {} <Fatal> BaseDaemon: 9. ./src/Server/HTTPHandler.h:94: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000162b80e5 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439638 [ 704516 ] {} <Fatal> BaseDaemon: 10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000162bc23c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439721 [ 704516 ] {} <Fatal> BaseDaemon: 11. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x0000000016389b4a in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439752 [ 704516 ] {} <Fatal> BaseDaemon: 12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x000000001758b7e8 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439780 [ 704516 ] {} <Fatal> BaseDaemon: 13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: Poco::Net::TCPServerDispatcher::run() @ 0x000000001758c2f3 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439891 [ 704516 ] {} <Fatal> BaseDaemon: 14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000017616d01 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439901 [ 704516 ] {} <Fatal> BaseDaemon: 15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001761351c in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439914 [ 704516 ] {} <Fatal> BaseDaemon: 16. ? @ 0x00007ffff7e08ac3 in ?
17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439926 [ 704516 ] {} <Fatal> BaseDaemon: 17. ? @ 0x00007ffff7e9a850 in ?
 (version 24.1.1.1)
2024.01.19 15:12:34.439933 [ 704516 ] {} <Fatal> BaseDaemon:  (version 24.1.1.1)
2024.01.19 15:12:34.440144 [ 707037 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build/./src/Parsers/IParserBase.cpp:13: operator()
2024.01.19 15:12:34.440175 [ 707037 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./src/Parsers/IParserBase.h:31: bool DB::IParserBase::wrapParseImpl<DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0>(DB::IParser::Pos&, DB::IParserBase::IncreaseDepthTag, DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&)::$_0 const&)
2024.01.19 15:12:34.440196 [ 707037 ] {} <Fatal> BaseDaemon: 10. ./build/./src/Parsers/IParserBase.cpp:11: DB::IParserBase::parse(DB::IParser::Pos&, std::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x0000000016ca6c2e in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.454105 [ 707037 ] {} <Fatal> BaseDaemon: 11. ./build/./src/Parsers/Kusto/parseKQLQuery.cpp:0: DB::tryParseKQLQuery(DB::IParser&, char const*&, char const*, String&, bool, String const&, bool, unsigned long, unsigned long, bool) @ 0x0000000016e590e2 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
2024.01.19 15:12:34.469519 [ 707037 ] {} <Fatal> BaseDaemon: 12. ./build/./src/Parsers/Kusto/parseKQLQuery.cpp:447: DB::parseKQLQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long) @ 0x0000000016e5dad9 in /home/smyl/old-griffin/install/clickhouse-2204/bin/clickhouse
```

### PR DESCRIPTION
**Pull request by kashwy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix segmentation fault in KQL parser when the input query exceeds the `max_query_size`. Also re-enable the KQL dialect. Fixes #59036 and #59037.

This commit fixes the issues:
 https://github.com/ClickHouse/ClickHouse/issues/59036
 https://github.com/ClickHouse/ClickHouse/issues/59037

both issues are same reason, the input query exceed the max_query_size, so the condition isEnd() of token is not meet and cause the assertion failure

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 84f09d0d50afadae73b7b65df6e0243ece34bfe3 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59626/84f09d0d50afadae73b7b65df6e0243ece34bfe3/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1">❌ failure</a></td></tr>
<tbody>
</table>

File: src/Parsers/Kusto/ParserKQLQuery.cpp [hunk 1]
```diff
@@ -373,7 +373,10 @@ bool ParserKQLQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
 
     uint16_t bracket_count = 0;
 
-    while (!pos->isEnd() && pos->type != TokenType::Semicolon)
+    while ((pos->type < TokenType::EndOfStream ||
+            pos->type == TokenType::ErrorSingleExclamationMark || // enable kql negative operators
+            String(pos->begin, pos->end) == "~") &&  // enable kql Case-Sensitive operators
+            pos->type != TokenType::Semicolon)
     {
```
Comment (antaljanosbenjamin) [inline src/Parsers/Kusto/ParserKQLQuery.cpp:380]:
```suggestion
    while ((pos.isValid() |
            pos->type == TokenType::ErrorSingleExclamationMark || // enable kql negative operators
            std::string_view(pos->begin, pos->end) == "~") &&  // enable kql Case-Sensitive operators
            pos->type != TokenType::Semicolon)
    {
```

**Review by antaljanosbenjamin — COMMENTED** [review]
Apart from these small changes I think the PR looks fine. I haven't checked the tests throrougly, but I assume it is coming from a good source and/or validated with other KQL parsers.

**Comment by antaljanosbenjamin** [comment]
I edited the PR description to hopefully make the PR check happy.

**Comment by kashwy** [comment]
> I edited the PR description to hopefully make the PR check happy.

thanks

**Comment by yakov-olkhovskiy** [comment]
I think we also need tests for these bugs

**Comment by kashwy** [comment]
> I think we also need test for this bug

this can be tested manually without  "--multiquery", otherwise the ErrorMaxQuerySizeExceeded is not triggered

**Comment by kashwy** [comment]
Hi @antaljanosbenjamin , can you do the Wing Fuzz test to verify the issue:

https://github.com/ClickHouse/ClickHouse/issues/59036
https://github.com/ClickHouse/ClickHouse/issues/59037

thanks

**Comment by kashwy** [comment]
> I can try to check the wingfuzz tests, but it is not clear to me how to reproduce the issue. I have also other tasks, so it might take some time.
> 
> In the meantime, I think the failing KQL test should be fixed. If the row order is random, we should either remove the test or make the row order deterministic.

yes, I have the test result updated.
for the wingfuzz tests, I think there is deadline for it, can you do  it ASAP ? 
thanks

**Comment by kashwy** [comment]
@antaljanosbenjamin, the failures are not related with this PR now

**Comment by kashwy** [comment]
@antaljanosbenjamin 
is there any news about the WING Fuzz test?

Best Regards

File: src/Parsers/Kusto/ParserKQLQuery.cpp [hunk 2]
```diff
@@ -373,9 +373,9 @@ bool ParserKQLQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
 
     uint16_t bracket_count = 0;
 
-    while ((pos->type < TokenType::EndOfStream ||
```
Comment (alexey-milovidov) [inline src/Parsers/Kusto/ParserKQLQuery.cpp]: Ok, but it works exactly the same.

Comment (kashwy) [reply src/Parsers/Kusto/ParserKQLQuery.cpp]: before we use  pos->isEnd() to validate, but if  when reach max_query_size,  the iterator already passed the end

Comment (alexey-milovidov) [reply src/Parsers/Kusto/ParserKQLQuery.cpp]: The code looks the same: `bool isValid() { return get().type < TokenType::EndOfStream; }`

Comment (kashwy) [reply src/Parsers/Kusto/ParserKQLQuery.cpp]: oh, yes, changed according to @antaljanosbenjamin 's suggestion

Comment (antaljanosbenjamin) [reply src/Parsers/Kusto/ParserKQLQuery.cpp]: Because `pos->isEnd()` would be `false` in case of `TokenType::ErrorMaxQuerySizeExceeded`, thus `!pos->isEnd()` wouldn't terminate the loop. Meanwhile `pos->isValid()` will be false in case of `TokenType::ErrorMaxQuerySizeExceeded`, thus stopping the loop. Do I miss something?

**Comment by alexey-milovidov** [comment]
Do you mean that the `makeseries` function contains a bug? Then, we should remove or fix it.

**Comment by antaljanosbenjamin** [comment]
> Do you mean that the makeseries function contains a bug? Then, we should remove or fix it.

Actually this might a general issue in KQL parsers. If I search for `isEnd()` in `src/Parsers` most of the matches are KQL parsers:
```
 grep -Rnwl './src/Parsers' -e 'isEnd()'
./src/Parsers/parseQuery.cpp
./src/Parsers/examples/lexer.cpp
./src/Parsers/Kusto/ParserKQLMakeSeries.cpp
./src/Parsers/Kusto/ParserKQLMVExpand.cpp
./src/Parsers/Kusto/parseKQLQuery.cpp
./src/Parsers/Kusto/ParserKQLSort.cpp
./src/Parsers/Kusto/ParserKQLStatement.cpp
./src/Parsers/Kusto/ParserKQLOperators.cpp
./src/Parsers/Kusto/ParserKQLExtend.cpp
./src/Parsers/Kusto/ParserKQLSummarize.cpp
./src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
./src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
./src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
./src/Parsers/Kusto/ParserKQLQuery.cpp
./src/Parsers/PRQL/ParserPRQLQuery.cpp
./src/Parsers/toOneLineQuery.cpp
./src/Parsers/Lexer.h
./src/Parsers/TokenIterator.cpp
./src/Parsers/queryNormalization.cpp
./src/Parsers/obfuscateQueries.cpp
./src/Parsers/fuzzers/lexer_fuzzer.cpp
```

This might mean that all of these checks in Kusto has to be addresssed:

```
grep -Rnw './src/Parsers/Kusto' -e 'isEnd()'
./src/Parsers/Kusto/ParserKQLMakeSeries.cpp:42:    while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLMakeSeries.cpp:99:    while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLMakeSeries.cpp:178:        while (!pos->isEnd())
./src/Parsers/Kusto/ParserKQLMakeSeries.cpp:204:        while (!pos->isEnd())
./src/Parsers/Kusto/ParserKQLMVExpand.cpp:52:    while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLMVExpand.cpp:128:        if (!pos->isEnd())
./src/Parsers/Kusto/ParserKQLMVExpand.cpp:130:        if (pos->isEnd() || pos->type == TokenType::PipeMark || pos->type == TokenType::Semicolon)
./src/Parsers/Kusto/parseKQLQuery.cpp:250:    for (TokenIterator it = begin; !it->isEnd(); ++it)
./src/Parsers/Kusto/parseKQLQuery.cpp:332:    if (token_iterator->isEnd()
./src/Parsers/Kusto/parseKQLQuery.cpp:406:    if (!token_iterator->isEnd()
./src/Parsers/Kusto/parseKQLQuery.cpp:424:        && !token_iterator->isEnd())
./src/Parsers/Kusto/ParserKQLSort.cpp:27:    while (!new_pos->isEnd() && new_pos->type != TokenType::PipeMark && new_pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLStatement.cpp:82:            while (!pos->isEnd())
./src/Parsers/Kusto/ParserKQLOperators.cpp:151:    while (!token_pos->isEnd() && token_pos->type != TokenType::PipeMark && token_pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLOperators.cpp:220:    while (!token_pos->isEnd() && token_pos->type != DB::TokenType::PipeMark && token_pos->type != DB::TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLOperators.cpp:332:    if (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLOperators.cpp:342:            if (pos->isEnd() || pos->type == TokenType::PipeMark || pos->type == TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLOperators.cpp:349:            if (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLOperators.cpp:363:        if (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLExtend.cpp:47:    while (!npos->isEnd())
./src/Parsers/Kusto/ParserKQLSummarize.cpp:123:                if (equal_pos->isEnd() || equal_pos->type == TokenType::Comma || equal_pos->type == TokenType::Semicolon
./src/Parsers/Kusto/ParserKQLSummarize.cpp:154:    while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp:524:    while (!pos->isEnd() && pos->type != TokenType::ClosingRoundBracket)
./src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp:591:    while (!pos->isEnd() && pos->type != TokenType::ClosingRoundBracket)
./src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp:54:        while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp:80:    while (!pos->isEnd() && pos->type != TokenType::ClosingRoundBracket)
./src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp:120:        while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp:593:    while (!pos->isEnd() && pos->type != TokenType::Semicolon && pos->type != TokenType::ClosingRoundBracket)
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp:76:    while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp:151:    if (pos->isEnd() || pos->type == TokenType::PipeMark || pos->type == TokenType::Semicolon)
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp:155:    while (!pos->isEnd() && pos->type != TokenType::PipeMark && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp:194:                    while (!pos->isEnd() && pos->type != TokenType::ClosingSquareBracket)
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp:249:    while (!pos->isEnd() && (!scopes.empty() || (pos->type != DB::TokenType::Comma && pos->type != DB::TokenType::ClosingRoundBracket)))
./src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp:360:        while (!pos->isEnd() && pos->type != TokenType::ClosingSquareBracket)
./src/Parsers/Kusto/ParserKQLQuery.cpp:133:    while (!end->isEnd() && end->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLQuery.cpp:152:    while (!pos->isEnd() && pos->type != TokenType::Semicolon)
./src/Parsers/Kusto/ParserKQLQuery.cpp:376:    while (!pos->isEnd() && pos->type != TokenType::Semicolon)
```

I am not sure, but it is suspicious. I will try to play with them and find new bugs.

**Comment by antaljanosbenjamin** [comment]
@kashwy if you want to help, you can also check out what happend when some of these `isEnd()` checks encounters `TokenType::ErrorMaxQuerySizeExceeded`.

**Comment by kashwy** [comment]
> Do you mean that the `makeseries` function contains a bug? Then, we should remove or fix it.

will fixed with a separated PR

**Comment by kashwy** [comment]
> @kashwy if you want to help, you can also check out what happend when some of these `isEnd()` checks encounters `TokenType::ErrorMaxQuerySizeExceeded`.

I can change all of them, although `TokenType::ErrorMaxQuerySizeExceeded`. will be screened out at the first place

**Comment by antaljanosbenjamin** [comment]
> I can change all of them, although TokenType::ErrorMaxQuerySizeExceeded. will be screened out at the first place

I miss something in the logic then. Could you please clarify?

**Comment by kashwy** [comment]
> > I can change all of them, although TokenType::ErrorMaxQuerySizeExceeded. will be screened out at the first place
> 
> I miss something in the logic then. Could you please clarify?

sure.
the current change is the entry point of kql parsing , if  encountered  TokenType::ErrorMaxQuerySizeExceeded, it will throw exception, and will not go to other parser

**Comment by antaljanosbenjamin** [comment]
> the current change is the entry point of kql parsing , if encountered TokenType::ErrorMaxQuerySizeExceeded, it will throw exception, and will not go to other parser

But what if other parsers are started to parse a portion of the query? E.g.:
```
$ cat query.txt
SET dialect = 'kusto';
SET max_query_size = 16;
Customers | where Education contains 'degree'
$ ./clickhouse_fixed -n < query.txt 
Code: 1001. DB::Exception: std::bad_alloc: std::bad_alloc. (STD_EXCEPTION)
```

I think what happens here is:
1. `Customers` is parsed as a `table` operator => everything is fine
2. A `ParserKQLFilter` starts to parse the `Education contains 'degree'` part. In this part the query size limit is reached in `'degree'`, so there will be the `TokenType::ErrorMaxQuerySizeExceeded`, however `ParserKQLBase :: getExprFromToken` only checks `!pos->isEnd()`, this it passes the end of the string and we end up with a huuuuuuge string, that is why `std::bad_alloc` is thrown.

But there is another example:
```
$ cat query.txt
SET dialect = 'kusto';
SET max_query_size = 44;
Customers | where Education contains 'degree' | order by LastName
$ ./clickhouse_fixed -n < query.txt 
Code: 1001. DB::Exception: std::length_error: basic_string. (STD_EXCEPTION)
```
Here the same thing happens, but with `ParserKQLSort`. If you use the debug builds, it is obvious that this is wrong:

```
$ cat query.txt
SET dialect = 'kusto';
SET max_query_size = 44;
Customers | where Education contains 'degree' | order by LastName
$ ./clickhouse_fixed_debug -n < query.txt 
clickhouse_fixed_debug: /build/src/Parsers/TokenIterator.h:31: const Token &DB::Tokens::operator[](size_t): Assertion `index < data.size()' failed.
Aborted (core dumped)
```
I think this needs to be fixed. All of the `isEnd()` calls in KQL parsers are potential issues.

(BTW: I just realized that Alexey's comment is about the tests, but it directed my focus and I think we ended up with a better result).

**Comment by kashwy** [comment]
> > the current change is the entry point of kql parsing , if encountered TokenType::ErrorMaxQuerySizeExceeded, it will throw exception, and will not go to other parser
> 
> But what if other parsers are started to parse a portion of the query? E.g.:
> 
> ```
> $ cat query.txt
> SET dialect = 'kusto';
> SET max_query_size = 16;
> Customers | where Education contains 'degree'
> $ ./clickhouse_fixed -n < query.txt 
> Code: 1001. DB::Exception: std::bad_alloc: std::bad_alloc. (STD_EXCEPTION)
> ```
> 
> I think what happens here is:
> 
> 1. `Customers` is parsed as a `table` operator => everything is fine
> 2. A `ParserKQLFilter` starts to parse the `Education contains 'degree'` part. In this part the query size limit is reached in `'degree'`, so there will be the `TokenType::ErrorMaxQuerySizeExceeded`, however `ParserKQLBase :: getExprFromToken` only checks `!pos->isEnd()`, this it passes the end of the string and we end up with a huuuuuuge string, that is why `std::bad_alloc` is thrown.
> 
> But there is another example:
> 
> ```
> $ cat query.txt
> SET dialect = 'kusto';
> SET max_query_size = 44;
> Customers | where Education contains 'degree' | order by LastName
> $ ./clickhouse_fixed -n < query.txt 
> Code: 1001. DB::Exception: std::length_error: basic_string. (STD_EXCEPTION)
> ```
> 
> Here the same thing happens, but with `ParserKQLSort`. If you use the debug builds, it is obvious that this is wrong:
> 
> ```
> $ cat query.txt
> SET dialect = 'kusto';
> SET max_query_size = 44;
> Customers | where Education contains 'degree' | order by LastName
> $ ./clickhouse_fixed_debug -n < query.txt 
> clickhouse_fixed_debug: /build/src/Parsers/TokenIterator.h:31: const Token &DB::Tokens::operator[](size_t): Assertion `index < data.size()' failed.
> Aborted (core dumped)
> ```
> 
> I think this needs to be fixed. All of the `isEnd()` calls in KQL parsers are potential issues.
> 
> (BTW: I just realized that Alexey's comment is about the tests, but it directed my focus and I think we ended up with a better result).

sure, I am fixing it

**Comment by kashwy** [comment]
@antaljanosbenjamin the issues are fixed:

```
SET dialect = 'kusto';
SET max_query_size = 16;
Customers | where Education contains 'degree'

Syntax error: failed at position 13 ('where'):
Customers | where Education contains 'degree'
Max query size exceeded: 'where'
```


```
SET dialect = 'kusto';
SET max_query_size = 44;
Customers | where Education contains 'degree' | order by LastName

Exception on client:
Code: 62. DB::Exception: Syntax error near contains. (SYNTAX_ERROR)
```

this is because the Max query size in the middle of the quote,



if  `SET max_query_size = 55;`

```
Customers | where Education contains 'degree' | order by LastName

Syntax error: failed at position 55 ('by'):

Customers | where Education contains 'degree' | order by LastName

Max query size exceeded: 'by'
```

**Comment by yakov-olkhovskiy** [comment]
@kashwy there is a typo:
```
2024-02-19 07:12:09 /ClickHouse/src/Parsers/Kusto/ParserKQLQuery.cpp:645:5: error: use of undeclared identifier 'node_table_in_select_query_emlement'; did you mean 'node_table_in_select_query_element'?
2024-02-19 07:12:09   645 |     node_table_in_select_query_emlement->children.emplace_back(node_table_expr);
2024-02-19 07:12:09       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-02-19 07:12:09       |     node_table_in_select_query_element
2024-02-19 07:12:09 /ClickHouse/src/Parsers/Kusto/ParserKQLQuery.cpp:642:12: note: 'node_table_in_select_query_element' declared here
2024-02-19 07:12:09   642 |     ASTPtr node_table_in_select_query_element = std::make_shared<ASTTablesInSelectQueryElement>();
2024-02-19 07:12:09       |            ^
2024-02-19 07:12:09 1 error generated.
```

**Comment by antaljanosbenjamin** [comment]
I think overall the PR is mergable, I don't see any possible dangerous issues.

However in the future (not in this PR though) this should be fixed:

> this is because the Max query size in the middle of the quote,

I think the reason here is because Kusto parsers sometimes written in a way that they don't have any other way to signal errors than throwing an exception, e.g.: `String KQLOperators::genHasAnyAllOpExpr(std::vector<String> & tokens, IParser::Pos & token_pos, String kql_op, String ch_op)`. Maybe they should return optional values and the simple parsing errors should be handled on higher levels. I am not sure, but the error message is too generic here. But again, this shouldn't be part of this PR, this PR aims to fix crashes, which it does in my opnion.

**Comment by kashwy** [comment]
Hi @antaljanosbenjamin , there are some test failures ,but I did not find anything related with my commit, can you help to take a look ?

Thanks

**Comment by kashwy** [comment]
> I think overall the PR is mergable, I don't see any possible dangerous issues.
> 
> However in the future (not in this PR though) this should be fixed:
> 
> > this is because the Max query size in the middle of the quote,
> 
> I think the reason here is because Kusto parsers sometimes written in a way that they don't have any other way to signal errors than throwing an exception, e.g.: `String KQLOperators::genHasAnyAllOpExpr(std::vector<String> & tokens, IParser::Pos & token_pos, String kql_op, String ch_op)`. Maybe they should return optional values and the simple parsing errors should be handled on higher levels. I am not sure, but the error message is too generic here. But again, this shouldn't be part of this PR, this PR aims to fix crashes, which it does in my opnion.

yeah, will do later

**Comment by antaljanosbenjamin** [comment]
So the issue is we recently made some changes in master in order to enforce that queries are formatted and parsed properly. That caused a lot of noise in our CI. As this PR is related to parsers, I will merge a recent master to rerun the tests. So far I haven't seen anything KQL related, but I might be wrong because of the huge number of failed tests I haven't checked every test in details.

**Comment by kashwy** [comment]
> So the issue is we recently made some changes in master in order to enforce that queries are formatted and parsed properly. That caused a lot of noise in our CI. As this PR is related to parsers, I will merge a recent master to rerun the tests. So far I haven't seen anything KQL related, but I might be wrong because of the huge number of failed tests I haven't checked every test in details.

thank you very much.  I did not see errors related with kql. 
Can this PR  be merged ? 

Best regard

**Comment by antaljanosbenjamin** [comment]
I have rerun the clang-tidy build, because that is required check. After that I think the PR can be merged.

**Comment by kashwy** [comment]
> I have rerun the clang-tidy build, because that is required check. After that I think the PR can be merged.

thanks

**Comment by antaljanosbenjamin** [comment]
Test failures:
- `Stress Test (ubsan)` #60349
- `00984_parser_stack_overflow` #60216
- `test_replicated_database/test.py::test_startup_without_zk` #60215
