### PR TITLE
Fix distributed table with a constant sharding key

### LINKED ISSUE #59589: Fatal after update to 24.1.1.2048
**Describe what's wrong**

If the Distributed table's sharding_key parameter contains a hash function with a literal instead of a column name, the cluster node receiving the insert query fails with a fatal error.

I realize this is a useless configuration but it shouldn't cause the node to crash.

**Does it reproduce on recent release?**

Yes.

**How to reproduce**

* Clickhouse version: 24.1.1.2048 (official build);
* You can reproduce it in any client;
* You need a cluster;
* Create schema and tables
```
CREATE DATABASE issue_db ON CLUSTER <cluster_name>;
 
CREATE OR REPLACE TABLE issue_db.numbers_shard ON CLUSTER <cluster_name>
(
    `number` Int32
)
ENGINE = MergeTree
ORDER BY (number)
SETTINGS index_granularity = 8192;
 
CREATE OR REPLACE TABLE issue_db.numbers ON CLUSTER <cluster_name>  AS issue_db.numbers_shard
ENGINE = Distributed('<cluster_name>', 'issue_db', 'numbers_shard', sipHash64('number'))
```
* Add records into the table:
```
INSERT INTO issue_db.numbers (`number`) VALUES 
('123123123'), ('123123123'), ('123123123'),
('123123123'), ('123123123');
```
* And got the error:
```
2024.02.01 15:18:58.242710 [ 14284 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.02.01 15:18:58.242796 [ 14284 ] {} <Fatal> BaseDaemon: (version 24.1.1.2048 (official build), build id: DB3BB386BCABA9D64AE7868998566DB2B5E2C562, git hash: 5a024dfc0936e062770d0cfaad0805b57c1fba17) (from thread 14063) Received signal 11
2024.02.01 15:18:58.242835 [ 14284 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.02.01 15:18:58.242856 [ 14284 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.02.01 15:18:58.242873 [ 14284 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000001226f22b 0x0000000012ccd702 0x0000000012c008cb 0x0000000012c005dc 0x0000000012bffcb3 0x000000001299565a 0x000000001298c0b0 0x000000001298b2c0 0x0000000012989a52 0x000000001190b3a3 0x00000000128bd2da 0x00000000128c2210 0x00000000129403ba 0x00000000153a79b2 0x00000000153a87b1 0x00000000154a0f87 0x000000001549f5bd 0x00007f96d3cfeea5 0x00007f96d3a27b0d
2024.02.01 15:18:58.242888 [ 14284 ] {} <Fatal> BaseDaemon: ########################################
2024.02.01 15:18:58.242897 [ 14284 ] {} <Fatal> BaseDaemon: (version 24.1.1.2048 (official build), build id: DB3BB386BCABA9D64AE7868998566DB2B5E2C562, git hash: 5a024dfc0936e062770d0cfaad0805b57c1fba17) (from thread 14063) (query_id: cd02d6dd-791a-4874-ad92-11c29f4314e1) (query: INSERT INTO issue_db.numbers (`number`) VALUES) Received signal Segmentation fault (11)
2024.02.01 15:18:58.242908 [ 14284 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.02.01 15:18:58.242915 [ 14284 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000001226f22b 0x0000000012ccd702 0x0000000012c008cb 0x0000000012c005dc 0x0000000012bffcb3 0x000000001299565a 0x000000001298c0b0 0x000000001298b2c0 0x0000000012989a52 0x000000001190b3a3 0x00000000128bd2da 0x00000000128c2210 0x00000000129403ba 0x00000000153a79b2 0x00000000153a87b1 0x00000000154a0f87 0x000000001549f5bd 0x00007f96d3cfeea5 0x00007f96d3a27b0d
2024.02.01 15:18:58.243132 [ 14284 ] {} <Fatal> BaseDaemon: 2. ? @ 0x000000001226f22b in /usr/bin/clickhouse
2024.02.01 15:18:58.243152 [ 14284 ] {} <Fatal> BaseDaemon: 3. ? @ 0x0000000012ccd702 in /usr/bin/clickhouse
2024.02.01 15:18:58.243205 [ 14284 ] {} <Fatal> BaseDaemon: 4. ? @ 0x0000000012c008cb in /usr/bin/clickhouse
2024.02.01 15:18:58.243240 [ 14284 ] {} <Fatal> BaseDaemon: 5. ? @ 0x0000000012c005dc in /usr/bin/clickhouse
2024.02.01 15:18:58.243269 [ 14284 ] {} <Fatal> BaseDaemon: 6. ? @ 0x0000000012bffcb3 in /usr/bin/clickhouse
2024.02.01 15:18:58.243283 [ 14284 ] {} <Fatal> BaseDaemon: 7. ? @ 0x000000001299565a in /usr/bin/clickhouse
2024.02.01 15:18:58.243309 [ 14284 ] {} <Fatal> BaseDaemon: 8. ? @ 0x000000001298c0b0 in /usr/bin/clickhouse
2024.02.01 15:18:58.243350 [ 14284 ] {} <Fatal> BaseDaemon: 9. ? @ 0x000000001298b2c0 in /usr/bin/clickhouse
2024.02.01 15:18:58.243376 [ 14284 ] {} <Fatal> BaseDaemon: 10. ? @ 0x0000000012989a52 in /usr/bin/clickhouse
2024.02.01 15:18:58.243428 [ 14284 ] {} <Fatal> BaseDaemon: 11. ? @ 0x000000001190b3a3 in /usr/bin/clickhouse
2024.02.01 15:18:58.243445 [ 14284 ] {} <Fatal> BaseDaemon: 12. ? @ 0x00000000128bd2da in /usr/bin/clickhouse
2024.02.01 15:18:58.243457 [ 14284 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00000000128c2210 in /usr/bin/clickhouse
2024.02.01 15:18:58.243472 [ 14284 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00000000129403ba in /usr/bin/clickhouse
2024.02.01 15:18:58.243483 [ 14284 ] {} <Fatal> BaseDaemon: 15. ? @ 0x00000000153a79b2 in /usr/bin/clickhouse
2024.02.01 15:18:58.243491 [ 14284 ] {} <Fatal> BaseDaemon: 16. ? @ 0x00000000153a87b1 in /usr/bin/clickhouse
2024.02.01 15:18:58.243504 [ 14284 ] {} <Fatal> BaseDaemon: 17. ? @ 0x00000000154a0f87 in /usr/bin/clickhouse
2024.02.01 15:18:58.243519 [ 14284 ] {} <Fatal> BaseDaemon: 18. ? @ 0x000000001549f5bd in /usr/bin/clickhouse
2024.02.01 15:18:58.243563 [ 14284 ] {} <Fatal> BaseDaemon: 19. ? @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
2024.02.01 15:18:58.243606 [ 14284 ] {} <Fatal> BaseDaemon: 20. ? @ 0x00000000000feb0d in /usr/lib64/libc-2.17.so
2024.02.01 15:18:58.516682 [ 14284 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: D78FF0C893F8E3CF4218408F07D9D44E)
2024.02.01 15:18:58.516795 [ 14284 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2024.02.01 15:18:58.516995 [ 14284 ] {} <Fatal> BaseDaemon: Changed settings: max_final_threads = 2, max_threads = 1, connect_timeout = 120., connect_timeout_with_failover_ms = 200, connect_timeout_with_failover_secure_ms = 300, receive_timeout = 1000., send_timeout = 1000., use_uncompressed_cache = false, distributed_foreground_insert = true, distributed_background_insert_batch = true, load_balancing = 'random', merge_tree_min_rows_for_concurrent_read = 1638400, merge_tree_min_bytes_for_concurrent_read = 2516582400, log_queries = true, distributed_product_mode = 'global', max_concurrent_queries_for_all_users = 110, distributed_ddl_task_timeout = 9000, http_send_timeout = 1800., http_receive_timeout = 1800., max_bytes_before_external_group_by = 80000000000, max_bytes_before_external_sort = 80000000000, max_execution_time = 18000., timeout_before_checking_execution_speed = 7200., readonly = 0, join_algorithm = 'prefer_partial_merge', max_memory_usage = 20000000000, allow_ddl = true, max_partitions_per_insert_block = 2000, database_atomic_wait_for_drop_and_detach_synchronously = true, mutations_sync = 1, lock_acquire_timeout = 120., merge_tree_min_rows_for_concurrent_read_for_remote_filesystem = 1638400, merge_tree_min_bytes_for_concurrent_read_for_remote_filesystem = 2516582400, allow_experimental_window_functions =
true, allow_experimental_map_type = false, partial_merge_join_optimizations = 1, background_fetches_pool_size = 8, background_schedule_pool_size = 128
2024.02.01 15:19:02.346023 [ 12785 ] {} <Fatal> Application: Child process was terminated by signal 11.
```

**Expected behavior**

There is no error, the data is in the table.

**Additional context**

The error is also reproduced when using "cityHash64()" instead of "sipHash64()". The data table engine doesn't matter.

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Bug Fix

### Changelog entry:
Fix distributed table with a constant sharding key.

Closes https://github.com/ClickHouse/ClickHouse/issues/59589

### CODE REVIEW

File: tests/queries/0_stateless/02983_const_sharding_key.sql [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+DROP DATABASE IF EXISTS shard_0;
+DROP DATABASE IF EXISTS shard_1;
+DROP TABLE IF EXISTS t_distr;
+
+CREATE DATABASE IF NOT EXISTS shard_0;
+CREATE DATABASE IF NOT EXISTS shard_1;
+
+CREATE TABLE shard_0.t_local (a Int) ENGINE = Memory;
+CREATE TABLE shard_1.t_local (a Int) ENGINE = Memory;
+CREATE TABLE t_distr (a Int) ENGINE = Distributed(test_cluster_two_shards_different_databases, '', 't_local', 1000);
```
Comment (vitlibar) [inline tests/queries/0_stateless/02983_const_sharding_key.sql:12]: A constant sharding key is not very useful but still valid. We must not crash on it.

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit f7f2dbbec818295be00371a33dddb4475a554d20 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59606/f7f2dbbec818295be00371a33dddb4475a554d20/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59606/f7f2dbbec818295be00371a33dddb4475a554d20/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Storages/StorageDistributed.cpp [hunk 2]
```diff
@@ -1533,10 +1533,7 @@ ClusterPtr StorageDistributed::getOptimizedCluster(
 IColumn::Selector StorageDistributed::createSelector(const ClusterPtr cluster, const ColumnWithTypeAndName & result)
 {
     const auto & slot_to_shard = cluster->getSlotToShard();
-
     const IColumn * column = result.column.get();
-    if (const auto * col_const = typeid_cast<const ColumnConst *>(column))
-        column = &col_const->getDataColumn();
```
Comment (vitlibar) [inline src/Storages/StorageDistributed.cpp:1539]: Function `StorageDistributed::createSelector()` must return a vector specifying how to split the input block into shards according to values of the sharding key. The size of this vector must be the same as the number of rows in the input block, i.e. the number of rows in the `result.column`.

Here this replacement `column = &col_const->getDataColumn()` was wrong because it caused the selector to have only one element. Also this replacement was unnecessary because below in this function the `createBlockSelector()` function is called which knows how to deal with const columns ([see](https://github.com/ClickHouse/ClickHouse/blob/a122857b6eed413e5a9bc985fe0155252847bef6/src/Interpreters/createBlockSelector.cpp#L40-L45)).

**Review by antonio2368 — APPROVED** [review]
