### PR TITLE
Fix double destroy call on exception throw in addBatchLookupTable8

### LINKED ISSUE #58727: Fatal error with aggThrow function (from 23.11)
https://fiddle.clickhouse.com/087a8981-9b6f-437a-a7fb-35271331be6e 

```sql
SELECT number % 2 AS even, aggThrow(number) FROM numbers(10) GROUP BY even 
```
Until 23.11 worked as expected (throwed an error).
Starting from 23.11 I get this:
```
[a639ea3958e4] 2024.01.11 21:33:19.579863 [ 733 ] <Fatal> BaseDaemon: ########################################
[a639ea3958e4] 2024.01.11 21:33:19.579925 [ 733 ] <Fatal> BaseDaemon: (version 23.12.2.59 (official build), build id: 7F4C1A822F9C67A4D137A58F9A95BD4B0F1B6A8A, git hash: 17ab210e76170917215be8cc3ae07d465a341d42) (from thread 54) (query_id: f3b8140e-4462-4c27-9471-7422f158690f) (query: SELECT number % 2 AS even, aggThrow(number) FROM numbers(10) GROUP BY even ) Received signal Aborted (6)
[a639ea3958e4] 2024.01.11 21:33:19.579960 [ 733 ] <Fatal> BaseDaemon: 
[a639ea3958e4] 2024.01.11 21:33:19.579991 [ 733 ] <Fatal> BaseDaemon: Stack trace: 0x00007f555638500b 0x00007f5556364859 0x000000000e3a0d8f 0x0000000010bc6360 0x0000000010b36d7c 0x00000000121eda8e 0x00000000129499f2 0x00000000129416c8 0x00000000105d0561 0x00000000105d2a9a 0x00000000105d82f1 0x000000001267abdb 0x000000001268cd79 0x00000000150f4e52 0x00000000150f5c51 0x00000000151ece67 0x00000000151eb45c 0x00007f555653c609 0x00007f5556461353
[a639ea3958e4] 2024.01.11 21:33:19.580032 [ 733 ] <Fatal> BaseDaemon: 2. ? @ 0x00007f555638500b in ?
[a639ea3958e4] 2024.01.11 21:33:19.580064 [ 733 ] <Fatal> BaseDaemon: 3. ? @ 0x00007f5556364859 in ?
[a639ea3958e4] 2024.01.11 21:33:19.580128 [ 733 ] <Fatal> BaseDaemon: 4. ? @ 0x000000000e3a0d8f in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.581088 [ 733 ] <Fatal> BaseDaemon: 5. void DB::Aggregator::destroyImpl<DB::AggregationMethodOneNumber<char8_t, FixedHashMap<char8_t, char*, FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>, FixedHashTableCalculatedSize<FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>>, Allocator<true, true>>, false, false>, FixedHashMap<char8_t, char*, FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>, FixedHashTableCalculatedSize<FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>>, Allocator<true, true>>>(FixedHashMap<char8_t, char*, FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>, FixedHashTableCalculatedSize<FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>>, Allocator<true, true>>&) const @ 0x0000000010bc6360 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.581974 [ 733 ] <Fatal> BaseDaemon: 6. DB::AggregatedDataVariants::~AggregatedDataVariants() @ 0x0000000010b36d7c in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.582853 [ 733 ] <Fatal> BaseDaemon: 7. DB::ManyAggregatedData::~ManyAggregatedData() @ 0x00000000121eda8e in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.583575 [ 733 ] <Fatal> BaseDaemon: 8. std::__shared_ptr_pointer<DB::ManyAggregatedData*, std::default_delete<DB::ManyAggregatedData>, std::allocator<DB::ManyAggregatedData>>::__on_zero_shared() @ 0x00000000129499f2 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.584230 [ 733 ] <Fatal> BaseDaemon: 9. DB::AggregatingTransform::~AggregatingTransform() @ 0x00000000129416c8 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.585030 [ 733 ] <Fatal> BaseDaemon: 10. std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() @ 0x00000000105d0561 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.585079 [ 733 ] <Fatal> BaseDaemon: 11. DB::QueryPipeline::~QueryPipeline() @ 0x00000000105d2a9a in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.585963 [ 733 ] <Fatal> BaseDaemon: 12. DB::QueryPipeline::reset() @ 0x00000000105d82f1 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.586851 [ 733 ] <Fatal> BaseDaemon: 13. DB::TCPHandler::runImpl() @ 0x000000001267abdb in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.587736 [ 733 ] <Fatal> BaseDaemon: 14. DB::TCPHandler::run() @ 0x000000001268cd79 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.588593 [ 733 ] <Fatal> BaseDaemon: 15. Poco::Net::TCPServerConnection::start() @ 0x00000000150f4e52 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.588653 [ 733 ] <Fatal> BaseDaemon: 16. Poco::Net::TCPServerDispatcher::run() @ 0x00000000150f5c51 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.588689 [ 733 ] <Fatal> BaseDaemon: 17. Poco::PooledThread::run() @ 0x00000000151ece67 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.589655 [ 733 ] <Fatal> BaseDaemon: 18. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000151eb45c in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:19.589686 [ 733 ] <Fatal> BaseDaemon: 19. ? @ 0x00007f555653c609 in ?
[a639ea3958e4] 2024.01.11 21:33:19.589719 [ 733 ] <Fatal> BaseDaemon: 20. ? @ 0x00007f5556461353 in ?
[a639ea3958e4] 2024.01.11 21:33:19.714119 [ 733 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: AC32B04C37311E5E413148969FBCE1EA)
[a639ea3958e4] 2024.01.11 21:33:19.715218 [ 733 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[a639ea3958e4] 2024.01.11 21:33:19.715378 [ 733 ] <Fatal> BaseDaemon: Changed settings: output_format_pretty_color = false, output_format_pretty_grid_charset = 'ASCII'
[a639ea3958e4] 2024.01.11 21:33:23.580166 [ 734 ] <Fatal> BaseDaemon: ########################################
[a639ea3958e4] 2024.01.11 21:33:23.580209 [ 734 ] <Fatal> BaseDaemon: (version 23.12.2.59 (official build), build id: 7F4C1A822F9C67A4D137A58F9A95BD4B0F1B6A8A, git hash: 17ab210e76170917215be8cc3ae07d465a341d42) (from thread 54) (query_id: f3b8140e-4462-4c27-9471-7422f158690f) (query: SELECT number % 2 AS even, aggThrow(number) FROM numbers(10) GROUP BY even ) Received signal Segmentation fault (11)
[a639ea3958e4] 2024.01.11 21:33:23.580257 [ 734 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[a639ea3958e4] 2024.01.11 21:33:23.580291 [ 734 ] <Fatal> BaseDaemon: Stack trace: 0x00007f5556364941 0x000000000e3a0d8f 0x0000000010bc6360 0x0000000010b36d7c 0x00000000121eda8e 0x00000000129499f2 0x00000000129416c8 0x00000000105d0561 0x00000000105d2a9a 0x00000000105d82f1 0x000000001267abdb 0x000000001268cd79 0x00000000150f4e52 0x00000000150f5c51 0x00000000151ece67 0x00000000151eb45c 0x00007f555653c609 0x00007f5556461353
[a639ea3958e4] 2024.01.11 21:33:23.580327 [ 734 ] <Fatal> BaseDaemon: 2. ? @ 0x00007f5556364941 in ?
[a639ea3958e4] 2024.01.11 21:33:23.580396 [ 734 ] <Fatal> BaseDaemon: 3. ? @ 0x000000000e3a0d8f in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580462 [ 734 ] <Fatal> BaseDaemon: 4. void DB::Aggregator::destroyImpl<DB::AggregationMethodOneNumber<char8_t, FixedHashMap<char8_t, char*, FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>, FixedHashTableCalculatedSize<FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>>, Allocator<true, true>>, false, false>, FixedHashMap<char8_t, char*, FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>, FixedHashTableCalculatedSize<FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>>, Allocator<true, true>>>(FixedHashMap<char8_t, char*, FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>, FixedHashTableCalculatedSize<FixedHashMapImplicitZeroCell<char8_t, char*, HashTableNoState>>, Allocator<true, true>>&) const @ 0x0000000010bc6360 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580516 [ 734 ] <Fatal> BaseDaemon: 5. DB::AggregatedDataVariants::~AggregatedDataVariants() @ 0x0000000010b36d7c in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580560 [ 734 ] <Fatal> BaseDaemon: 6. DB::ManyAggregatedData::~ManyAggregatedData() @ 0x00000000121eda8e in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580602 [ 734 ] <Fatal> BaseDaemon: 7. std::__shared_ptr_pointer<DB::ManyAggregatedData*, std::default_delete<DB::ManyAggregatedData>, std::allocator<DB::ManyAggregatedData>>::__on_zero_shared() @ 0x00000000129499f2 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580638 [ 734 ] <Fatal> BaseDaemon: 8. DB::AggregatingTransform::~AggregatingTransform() @ 0x00000000129416c8 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580675 [ 734 ] <Fatal> BaseDaemon: 9. std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() @ 0x00000000105d0561 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580714 [ 734 ] <Fatal> BaseDaemon: 10. DB::QueryPipeline::~QueryPipeline() @ 0x00000000105d2a9a in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580750 [ 734 ] <Fatal> BaseDaemon: 11. DB::QueryPipeline::reset() @ 0x00000000105d82f1 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580783 [ 734 ] <Fatal> BaseDaemon: 12. DB::TCPHandler::runImpl() @ 0x000000001267abdb in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580820 [ 734 ] <Fatal> BaseDaemon: 13. DB::TCPHandler::run() @ 0x000000001268cd79 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580856 [ 734 ] <Fatal> BaseDaemon: 14. Poco::Net::TCPServerConnection::start() @ 0x00000000150f4e52 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580887 [ 734 ] <Fatal> BaseDaemon: 15. Poco::Net::TCPServerDispatcher::run() @ 0x00000000150f5c51 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580924 [ 734 ] <Fatal> BaseDaemon: 16. Poco::PooledThread::run() @ 0x00000000151ece67 in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580960 [ 734 ] <Fatal> BaseDaemon: 17. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000151eb45c in /usr/bin/clickhouse
[a639ea3958e4] 2024.01.11 21:33:23.580993 [ 734 ] <Fatal> BaseDaemon: 18. ? @ 0x00007f555653c609 in ?
[a639ea3958e4] 2024.01.11 21:33:23.581017 [ 734 ] <Fatal> BaseDaemon: 19. ? @ 0x00007f5556461353 in ?
[a639ea3958e4] 2024.01.11 21:33:23.699803 [ 734 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: AC32B04C37311E5E413148969FBCE1EA)
[a639ea3958e4] 2024.01.11 21:33:23.700099 [ 734 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[a639ea3958e4] 2024.01.11 21:33:23.700233 [ 734 ] <Fatal> BaseDaemon: Changed settings: output_format_pretty_color = false, output_format_pretty_grid_charset = 'ASCII'
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix double destroy call on exception throw in addBatchLookupTable8

### Documentation entry for user-facing changes

Closes https://github.com/ClickHouse/ClickHouse/issues/58727

The problem is that the pointer is assigned before create is called, so if create throws it keeps the assignment and will try to call destroy again later. All other calls to `createAggregateStates` are doing it correctly.

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit e22371ad034f3104e0aa3ba7c5f8e9cf6a8e9e9b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58745/e22371ad034f3104e0aa3ba7c5f8e9cf6a8e9e9b/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58745/e22371ad034f3104e0aa3ba7c5f8e9cf6a8e9e9b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Interpreters/Aggregator.cpp [hunk 1]
```diff
@@ -1204,8 +1204,9 @@ void NO_INLINE Aggregator::executeImplBatch(
                     inst->state_offset,
                     [&](AggregateDataPtr & aggregate_data)
                     {
-                        aggregate_data = aggregates_pool->alignedAlloc(total_size_of_aggregate_states, align_aggregate_states);
+                        AggregateDataPtr place = aggregates_pool->alignedAlloc(total_size_of_aggregate_states, align_aggregate_states);
```
Comment (devcrafter) [inline src/Interpreters/Aggregator.cpp:1207]: Shouldn't we pass place into `createAggreateStates()`?

Comment (Algunenano) [reply src/Interpreters/Aggregator.cpp:1207]: Yes. Will fix

**Review by devcrafter — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
