### PR TITLE
Fix constants in the result of MergingSortedAlgorithm.

### LINKED ISSUE #46466: Segmentation fault when using window function and distinct
**Describe what's wrong**

ClickHouse crashes when using window function and distinct statement in a single query.

**How to reproduce**

ClickHouse version: 22.12.3

Create MergeTree table:
```
CREATE TABLE test_table
(
    string_value String
)
ENGINE = MergeTree
ORDER BY string_value;
```

Insert data:
```
insert into test_table
select *
from (
	select 'test_value_1'
	from numbers_mt(250000)
	union all
	select 'test_value_2'
	from numbers_mt(2000000)
)
order by rand();
```

Run query:
```
select distinct
    'constant_1' as constant_value,
    count(*) over(partition by constant_value, string_value) as value_cnt
from (
    select string_value
    from test_table
);
```

**Expected behavior**

Expected that ClickHouse will not crash with segmentation fault.

**Error message and/or stacktrace**

Stacktrace:
```
2023.02.16 08:26:54.104941 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Debug> executeQuery: (from 127.0.0.1:46168) select distinct 'constant_1' as constant_value, count(*) over(partition by constant_value, string_value) as value_cnt from ( select string_value from test_table ); (stage: Complete)
2023.02.16 08:26:54.105187 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> ContextAccess (default): Access granted: SELECT(string_value) ON default.test_table
2023.02.16 08:26:54.105265 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> ContextAccess (default): Access granted: SELECT(string_value) ON default.test_table
2023.02.16 08:26:54.105489 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> ContextAccess (default): Access granted: SELECT(string_value) ON default.test_table
2023.02.16 08:26:54.105527 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> ContextAccess (default): Access granted: SELECT(string_value) ON default.test_table
2023.02.16 08:26:54.105562 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.02.16 08:26:54.105584 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.02.16 08:26:54.105703 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Debug> default.test_table (c59540f0-3ade-4a40-b572-846898333bf0) (SelectExecutor): Key condition: unknown
2023.02.16 08:26:54.105938 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Debug> default.test_table (c59540f0-3ade-4a40-b572-846898333bf0) (SelectExecutor): Selected 3/4 parts by partition key, 3 parts by primary key, 275/275 marks by primary key, 275 marks to read from 3 ranges
2023.02.16 08:26:54.105978 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 2 ranges in order from part all_12_12_0, approx. 26094 rows starting from 0
2023.02.16 08:26:54.105991 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_11_11_0, approx. 196608 rows starting from 0
2023.02.16 08:26:54.106008 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_11_11_0, approx. 196608 rows starting from 196608
2023.02.16 08:26:54.106028 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_11_11_0, approx. 196608 rows starting from 393216
2023.02.16 08:26:54.106049 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_11_11_0, approx. 196608 rows starting from 589824
2023.02.16 08:26:54.106073 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_11_11_0, approx. 325521 rows starting from 786432
2023.02.16 08:26:54.106104 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_10_10_0, approx. 196608 rows starting from 0
2023.02.16 08:26:54.106132 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_10_10_0, approx. 196608 rows starting from 196608
2023.02.16 08:26:54.106162 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_10_10_0, approx. 196608 rows starting from 393216
2023.02.16 08:26:54.106189 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_10_10_0, approx. 196608 rows starting from 589824
2023.02.16 08:26:54.106225 [ 3006993 ] {5bdf0b84-85c5-404e-b2b8-19e44b69276c} <Trace> MergeTreeInOrderSelectProcessor: Reading 5 ranges in order from part all_10_10_0, approx. 325521 rows starting from 786432
┌─constant_value─┬─value_cnt─┐
│ constant_1     │    250000 │
└────────────────┴───────────┘
2023.02.16 08:26:54.138013 [ 3007541 ] <Fatal> BaseDaemon: ########################################
2023.02.16 08:26:54.138128 [ 3007541 ] <Fatal> BaseDaemon: (version 22.12.3.5 (official build), build id: 1FC9EF37AB97BF195F9DF1C7D44CEC3DCC837FAD) (from thread 3007382) (query_id: 5bdf0b84-85c5-404e-b2b8-19e44b69276c) (query: select distinct 'constant_1' as constant_value, count(*) over(partition by constant_value, string_value) as value_cnt from ( select string_value from test_table );) Received signal Segmentation fault (11)
2023.02.16 08:26:54.138178 [ 3007541 ] <Fatal> BaseDaemon: Address: 0x19 Access: read. Address not mapped to object.
2023.02.16 08:26:54.138209 [ 3007541 ] <Fatal> BaseDaemon: Stack trace: 0x147e3f97 0x157105a7 0x15710ada 0x110f9730 0x153d009f 0x153ee2a6 0x153e349c 0x153e55bd 0xe809f16 0xe80f0e1 0x7f046ccba609 0x7f046cbdf133
2023.02.16 08:26:54.138285 [ 3007541 ] <Fatal> BaseDaemon: 2. ? @ 0x147e3f97 in /usr/bin/clickhouse
2023.02.16 08:26:54.138332 [ 3007541 ] <Fatal> BaseDaemon: 3. DB::DistinctSortedChunkTransform::continueWithPrevRange(unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) @ 0x157105a7 in /usr/bin/clickhouse
2023.02.16 08:26:54.138360 [ 3007541 ] <Fatal> BaseDaemon: 4. DB::DistinctSortedChunkTransform::transform(DB::Chunk&) @ 0x15710ada in /usr/bin/clickhouse
2023.02.16 08:26:54.138394 [ 3007541 ] <Fatal> BaseDaemon: 5. ? @ 0x110f9730 in /usr/bin/clickhouse
2023.02.16 08:26:54.138425 [ 3007541 ] <Fatal> BaseDaemon: 6. DB::ISimpleTransform::work() @ 0x153d009f in /usr/bin/clickhouse
2023.02.16 08:26:54.138453 [ 3007541 ] <Fatal> BaseDaemon: 7. DB::ExecutionThreadContext::executeTask() @ 0x153ee2a6 in /usr/bin/clickhouse
2023.02.16 08:26:54.138476 [ 3007541 ] <Fatal> BaseDaemon: 8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x153e349c in /usr/bin/clickhouse
2023.02.16 08:26:54.138518 [ 3007541 ] <Fatal> BaseDaemon: 9. ? @ 0x153e55bd in /usr/bin/clickhouse
2023.02.16 08:26:54.138552 [ 3007541 ] <Fatal> BaseDaemon: 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe809f16 in /usr/bin/clickhouse
2023.02.16 08:26:54.138581 [ 3007541 ] <Fatal> BaseDaemon: 11. ? @ 0xe80f0e1 in /usr/bin/clickhouse
2023.02.16 08:26:54.138610 [ 3007541 ] <Fatal> BaseDaemon: 12. ? @ 0x7f046ccba609 in ?
2023.02.16 08:26:54.138630 [ 3007541 ] <Fatal> BaseDaemon: 13. clone @ 0x7f046cbdf133 in ?
2023.02.16 08:26:54.276726 [ 3007541 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 707A227274554878C01CAF89F747CA21)
2023.02.16 08:26:54.276769 [ 3007541 ] <Information> SentryWriter: Not sending crash report
→ Progress: 1.34 million rows, 28.07 MB (66.87 thousand rows/s., 1.40 MB/s.)                                                                              (0.0 CPU, 41.09 MB RAM)Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000. (ATTEMPT_TO_READ_AFTER_EOF)

Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a crash that could happen when constant values are used in `ORDER BY`. Fixes https://github.com/ClickHouse/ClickHouse/issues/46466

### CODE REVIEW

File: tests/queries/0_stateless/02662_sorting_constants_and_distinct_crash.sql [hunk 1]
```diff
@@ -0,0 +1,25 @@
+drop table if exists test_table;
+CREATE TABLE test_table (string_value String) ENGINE = MergeTree ORDER BY string_value;
+insert into test_table select * from (
```
Comment (devcrafter) [inline tests/queries/0_stateless/02662_sorting_constants_and_distinct_crash.sql:3]: Probably make sense to add `SYSTEM STOP MERGES test_table`. With some comment. Since we couldn't reproduce it after merges happened. I can be not necessary for the test, but will provide full info to future readers

**Review by devcrafter — APPROVED** [review]
LGTM

**Review by alexey-milovidov — APPROVED** [review]
