### PR TITLE
Fix crash when using input() in INSERT SELECT JOIN

### LINKED ISSUE #60035: server crash on excessive ) at the end of insert query
when I run the query by clickhouse-client or clickhouse-local the server is crashed:
```
create table test (a Int8) engine = MergeTree order by tuple();
INSERT INTO test
SELECT * FROM (
 SELECT number
 FROM system.numbers
 LIMIT 10
) AS x
INNER JOIN input('a Int64') AS y ON x.number = y.a
Format CSV)
```

2024.02.15 17:20:09.029175 [ 6399849 ] {} <Trace> BaseDaemon: Received signal 11
2024.02.15 17:20:09.029478 [ 6401482 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.02.15 17:20:09.029567 [ 6401482 ] {} <Fatal> BaseDaemon: (version 23.12.1.1339 (official build), build id: , git hash: 643dddb61986286e537360c48a4fc3ee72bcee0a) (from thread 6399850) Received signal 11
2024.02.15 17:20:09.029624 [ 6401482 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault: 11
2024.02.15 17:20:09.029668 [ 6401482 ] {} <Fatal> BaseDaemon: Address: 0xc0. Access: . Address not mapped to object.
2024.02.15 17:20:09.029688 [ 6401482 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000107e4e2eb 0x000000010811444f 0x00007ff80581d5ed 0x0000000107ff9581 0x000000010c5d3c50 0x000000010c2ec36f 0x000000010c265c52 0x000000010c26a70f 0x000000010c2a511b 0x000000010c2a2d9f 0x000000010c2a4863 0x000000010c249747 0x000000010c5c31f6 0x000000010c5bfa93 0x000000010d2cad6a 0x000000010d2e0b5c 0x000000010edfd80c 0x000000010edfdd5e 0x000000010ee71e67 0x000000010ee6f6a0 0x00007ff8057f01d3
2

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash when using input() in INSERT SELECT JOIN. Closes https://github.com/ClickHouse/ClickHouse/issues/60035

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit ddf0dd7eb8784b3fb49ccf948707fe509c5f45ee with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60765/ddf0dd7eb8784b3fb49ccf948707fe509c5f45ee/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -1790,7 +1790,7 @@ StoragePtr Context::executeTableFunction(const ASTPtr & table_expression, const
         }
 
         uint64_t use_structure_from_insertion_table_in_table_functions = getSettingsRef().use_structure_from_insertion_table_in_table_functions;
-        if (use_structure_from_insertion_table_in_table_functions && table_function_ptr->needStructureHint() && hasInsertionTable())
+        if (select_query_hint && use_structure_from_insertion_table_in_table_functions && table_function_ptr->needStructureHint() && hasInsertionTable())
```
Comment (devcrafter) [inline src/Interpreters/Context.cpp:1793]: Probably some comment would be helpful.

Comment (devcrafter) [reply src/Interpreters/Context.cpp:1793]: This is new code to me, I need more context to get it straight. One way to simplify the complex condition is to assign it to a variable with a self-explanatory name. Probably, it can help

**Review by devcrafter — APPROVED** [review]
