### PR TITLE
Fix incorrect RIGHT join result when using complex ON conditions

### LINKED ISSUE #92913: Concurrent LEFT JOIN different result with `query_plan_filter_push_down` value
### Describe the bug

Happens since v25.11 and only with Int64 cc @vdimir 

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/73bba18b-5b51-4584-b75b-ce9d65451bf4

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

* Fix possibly incorrect RIGHT join result when using complex ON conditions. Close https://github.com/ClickHouse/ClickHouse/issues/92913

### Version info
- Merged into: `26.1.1.746`
- Backported to: `25.12.4.37`, `25.11.8.9`, `25.10.6.10`, `25.8.16.8`

### CODE REVIEW

File: tests/queries/0_stateless/03799_parallel_right_join_flag_per_row.sql [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+WHERE t0.c0 = 2
+SETTINGS join_algorithm='parallel_hash', query_plan_filter_push_down = 1;
+
+SELECT '-';
+
+
+SELECT
+    *
+FROM t1
+RIGHT JOIN t0
```
Comment (novikd) [inline tests/queries/0_stateless/03799_parallel_right_join_flag_per_row.sql:50]: Let's add queries with `LEFT JOIN` from the issue as well.

File: src/Interpreters/HashJoin/JoinUsedFlags.h [hunk 2]
```diff
@@ -45,13 +45,21 @@ class JoinUsedFlags
...
         {
             assert(per_row_flags[columns].size() <= columns->at(0)->size());
             need_flags = true;
             per_row_flags[columns] = std::vector<std::atomic_bool>(columns->at(0)->size());
+
+            /// Mark all rows outside of selector as used.
+            /// We should not emit them in RIGHT/FULL JOIN result,
+            /// since they belongs to another shard, which will handle flags for these rows
+            for (auto & flag : per_row_flags[columns])
+                flag.store(true);
```
Comment (novikd) [inline src/Interpreters/HashJoin/JoinUsedFlags.h:60]:
```suggestion
            /// Mark all rows outside of selector as used.
            /// We should not emit them in RIGHT/FULL JOIN result,
            /// since they belongs to another shard, which will handle flags for these rows
            per_row_flags[columns] = std::vector<std::atomic_bool>(columns->at(0)->size(), true);
```

File: tests/queries/0_stateless/03799_parallel_right_join_flag_per_row.sql (hunk 1 above)
Comment (vdimir) [reply tests/queries/0_stateless/03799_parallel_right_join_flag_per_row.sql:50]: Thanks for the suggestion! I took a look, and queries using `LEFT JOIN` return the correct results (unless they’re rewritten to `RIGHT JOIN` depending on `query_plan_join_swap_table`, what happened in query from the issue). Since this PR is specifically fixing the `RIGHT JOIN` behavior, adding `LEFT JOIN` cases wouldn’t actually cover any of the code paths changed here. 

If you still think adding `LEFT JOIN` cases would be useful for completeness, I’m happy to do that in a follow-up PR. That way we can merge this fix without waiting on another CI run, which might be helpful given the upcoming release.
