### PR TITLE
Fix handling exception in `Aggregator::mergeBlocks`

### LINKED ISSUE #81283: Crash in Aggregator (memory fault injection)
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=81256&sha=500db58c1ab2acd4ece07f41947b0ea518bc1b3f&name_0=PR&name_1=Stress%20test%20%28amd_debug%29

### How to reproduce

Setup:
```sql
create table t1(a UInt32) engine=MergeTree order by tuple() partition by a % 4 settings index_granularity = 8192, index_granularity_bytes = 10485760;

system stop merges t1;

insert into t1 select number from numbers_mt(1e6);
insert into t1 select number from numbers_mt(1e6);
```

It seems it's related to memory fault injection so we need to run the query over an over until it crashes (takes just a ~10 seconds with a debug build in my machine, a bit more in release):

```
$ while true; do clickhouse client --query "SELECT count()
FROM
(
    SELECT throwIf(count() != 2)
    FROM t1
    GROUP BY a
)
SETTINGS min_compress_block_size = 912014, max_compress_block_size = 2942345, max_block_size = 94118, min_external_table_block_size_bytes = 100000000, max_joined_block_size_rows = 38422, max_insert_threads = 3, max_threads = 16, max_parsing_threads = 10, max_read_buffer_size = 847662, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, use_hedged_requests = false, idle_connection_timeout = 36000, s3_max_get_rps = 1000000, s3_max_get_burst = 2000000, s3_max_put_rps = 1000000, s3_max_put_burst = 2000000, s3_check_objects_after_upload = true, use_uncompressed_cache = true, max_remote_read_network_bandwidth = 1000000000000, max_remote_write_network_bandwidth = 1000000000000, max_local_read_bandwidth = 1000000000000, max_local_write_bandwidth = 1000000000000, stream_like_engine_allow_direct_select = true, enable_multiple_prewhere_read_steps = false, replication_wait_for_inactive_replica_timeout = 30, min_count_to_compile_expression = 0, min_count_to_compile_sort_description = 0, group_by_two_level_threshold = 403627, group_by_two_level_threshold_bytes = 1, distributed_aggregation_memory_efficient = false, enable_memory_bound_merging_of_aggregation_results = false, allow_nonconst_timezone_arguments = true, min_chunk_bytes_for_parallel_parsing = 11046431, min_bytes_to_use_direct_io = 1, min_bytes_to_use_mmap_io = 10737418240, use_skip_indexes_if_final = true, use_skip_indexes_if_final_exact_mode = true, secondary_indices_enable_bulk_filtering = false, log_queries = true, insert_quorum_timeout = 60000, table_function_remote_max_addresses = 200, memory_tracker_fault_probability = 0.0010000000474974513, merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0., http_wait_end_of_query = true, http_response_buffer_size = 6823172, fsync_metadata = true, http_send_timeout = 60., http_receive_timeout = 60., use_index_for_in_with_subqueries_max_values = 1000000000, opentelemetry_start_trace_probability = 0.10000000149011612, enable_vertical_final = false, max_rows_to_read = 20000000, max_bytes_to_read = 1000000000000, max_bytes_to_read_leaf = 1000000000000, max_rows_to_group_by = 10000000000, max_bytes_ratio_before_external_group_by = 0.2, max_rows_to_sort = 10000000000, max_bytes_to_sort = 10000000000, prefer_external_sort_block_bytes = 0, max_bytes_ratio_before_external_sort = 0.2, max_bytes_before_remerge_sort = 1697693528, max_result_rows = 1000000000, max_result_bytes = 1000000000, max_execution_time = 60., max_execution_speed = 100000000000, max_execution_speed_bytes = 10000000000000, timeout_before_checking_execution_speed = 300., max_estimated_execution_time = 600., max_columns_to_read = 20000, max_temporary_columns = 20000, max_temporary_non_const_columns = 20000, max_rows_in_set = 10000000000, max_bytes_in_set = 10000000000, max_rows_in_join = 10000000000, max_bytes_in_join = 10000000000, cross_join_min_rows_to_compress = 0, cross_join_min_bytes_to_compress = 100000000, max_rows_to_transfer = 1000000000, max_bytes_to_transfer = 1000000000, max_rows_in_distinct = 10000000000, max_bytes_in_distinct = 10000000000, max_memory_usage = 10000000000, max_memory_usage_for_user = 19899268300, max_untracked_memory = 1048576, memory_profiler_step = 1048576, max_network_bandwidth = 100000000000, max_network_bytes = 1000000000000, max_network_bandwidth_for_user = 100000000000, max_network_bandwidth_for_all_users = 100000000000, max_temporary_data_on_disk_size_for_user = 100000000000, max_temporary_data_on_disk_size_for_query = 100000000000, max_backup_bandwidth = 100000000000, log_comment = '02521_aggregation_by_partitions.sql', send_logs_level = 'warning', prefer_localhost_replica = false, optimize_aggregation_in_order = true, aggregation_in_order_max_block_bytes = 11234413, read_in_order_two_level_merge_threshold = 6, max_hyperscan_regexp_length = 1000000, max_hyperscan_regexp_total_length = 10000000, allow_introspection_functions = true, database_atomic_wait_for_drop_and_detach_synchronously = true, optimize_if_transform_strings_to_enum = true, optimize_functions_to_subcolumns = false, optimize_append_index = true, lock_acquire_timeout = 60., optimize_trivial_insert_select = true, optimize_use_projections = false, use_query_cache = false, query_cache_nondeterministic_function_handling = 'ignore', query_cache_system_table_handling = 'ignore', query_cache_max_size_in_bytes = 10000000, query_cache_max_entries = 100000, use_query_condition_cache = false, allow_aggregate_partitions_independently = true, force_aggregate_partitions_independently = true, database_replicated_allow_replicated_engine_arguments = 1, distributed_ddl_entry_format_version = 6, external_storage_max_read_rows = 10000000000, external_storage_max_read_bytes = 10000000000, local_filesystem_read_prefetch = true, remote_filesystem_read_prefetch = false, merge_tree_min_bytes_per_task_for_remote_reading = 8388608, merge_tree_compact_parts_min_granules_to_multibuffer_read = 40, async_insert_busy_timeout_max_ms = 5000, enable_filesystem_cache = true, enable_filesystem_cache_on_write_operations = true, throw_on_error_from_cache_on_write_operations = true, filesystem_cache_segments_batch_size = 5, page_cache_inject_eviction = true, load_marks_asynchronously = true, allow_prefetched_read_pool_for_remote_filesystem = false, allow_prefetched_read_pool_for_local_filesystem = false, filesystem_prefetch_step_marks = 50, filesystem_prefetch_max_memory_usage = 33554432, filesystem_prefetches_limit = 0, allow_deprecated_database_ordinary = true, max_streams_for_merge_tree_reading = 1000, optimize_sorting_by_input_stream_properties = false, insert_keeper_max_retries = 100, insert_keeper_retry_initial_backoff_ms = 1, insert_keeper_retry_max_backoff_ms = 10, insert_keeper_fault_injection_probability = 0.009999999776482582, ignore_drop_queries_probability = 0.20000000298023224, optimize_distinct_in_order = false, allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 3, cluster_for_parallel_replicas = 'parallel_replicas', parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, session_timezone = 'America/Mazatlan', optimize_extract_common_expressions = false"; done
```

I cannot reproduce it if I disable `allow_experimental_parallel_reading_from_replicas`, but it might be just a matter of luck (different allocations).

### Error message and/or stacktrace

Stacktrace:
```
[Mordor] 2025.06.04 04:33:45.450183 [ 108170 ] <Fatal> BaseDaemon: ########################################
[Mordor] 2025.06.04 04:33:45.450244 [ 108170 ] <Fatal> BaseDaemon: (version 25.6.1.1, build id: 3FE10ED5BC24F34882D06267CEA8B691046BA2C2, git hash: 2fab606e4a379ead5f8a4ec22d2b76ec88bc1ac7) (from thread 95014) (query_id: e68c40a6-aaf4-4873-b636-808978748413) (query: SELECT count()
FROM
(
    SELECT throwIf(count() != 2)
    FROM t1
    GROUP BY a
)
SETTINGS min_compress_block_size = 912014, max_compress_block_size = 2942345, max_block_size = 94118, min_external_table_block_size_bytes = 100000000, max_joined_block_size_rows = 38422, max_insert_threads = 3, max_threads = 16, max_parsing_threads = 10, max_read_buffer_size = 847662, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, use_hedged_requests = false, idle_connection_timeout = 36000, s3_max_get_rps = 1000000, s3_max_get_burst = 2000000, s3_max_put_rps = 1000000, s3_max_put_burst = 2000000, s3_check_objects_after_upload = true, use_uncompressed_cache = true, max_remote_read_network_bandwidth = 1000000000000, max_remote_write_network_bandwidth = 1000000000000, max_local_read_bandwidth = 1000000000000, max_local_write_bandwidth = 1000000000000, stream_like_engine_allow_direct_select = true, enable_multiple_prewhere_read_steps = false, replication_wait_for_inactive_replica_timeout = 30, min_count_to_compile_expression = 0, min_count_to_compile_sort_description = 0, group_by_two_level_threshold = 403627, group_by_two_level_threshold_bytes = 1, distributed_aggregation_memory_efficient = false, enable_memory_bound_merging_of_aggregation_results = false, allow_nonconst_timezone_arguments = true, min_chunk_bytes_for_parallel_parsing = 11046431, min_bytes_to_use_direct_io = 1, min_bytes_to_use_mmap_io = 10737418240, use_skip_indexes_if_final = true, use_skip_indexes_if_final_exact_mode = true, secondary_indices_enable_bulk_filtering = false, log_queries = true, insert_quorum_timeout = 60000, table_function_remote_max_addresses = 200, memory_tracker_fault_probability = 0.0010000000474974513, merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0., http_wait_end_of_query = true, http_response_buffer_size = 6823172, fsync_metadata = true, http_send_timeout = 60., http_receive_timeout = 60., use_index_for_in_with_subqueries_max_values = 1000000000, opentelemetry_start_trace_probability = 0.10000000149011612, enable_vertical_final = false, max_rows_to_read = 20000000, max_bytes_to_read = 1000000000000, max_bytes_to_read_leaf = 1000000000000, max_rows_to_group_by = 10000000000, max_bytes_ratio_before_external_group_by = 0.2, max_rows_to_sort = 10000000000, max_bytes_to_sort = 10000000000, prefer_external_sort_block_bytes = 0, max_bytes_ratio_before_external_sort = 0.2, max_bytes_before_remerge_sort = 1697693528, max_result_rows = 1000000000, max_result_bytes = 1000000000, max_execution_time = 60., max_execution_speed = 100000000000, max_execution_speed_bytes = 10000000000000, timeout_before_checking_execution_speed = 300., max_estimated_execution_time = 600., max_columns_to_read = 20000, max_temporary_columns = 20000, max_temporary_non_const_columns = 20000, max_rows_in_set = 10000000000, max_bytes_in_set = 10000000000, max_rows_in_join = 10000000000, max_bytes_in_join = 10000000000, cross_join_min_rows_to_compress = 0, cross_join_min_bytes_to_compress = 100000000, max_rows_to_transfer = 1000000000, max_bytes_to_transfer = 1000000000, max_rows_in_distinct = 10000000000, max_bytes_in_distinct = 10000000000, max_memory_usage = 10000000000, max_memory_usage_for_user = 19899268300, max_untracked_memory = 1048576, memory_profiler_step = 1048576, max_network_bandwidth = 100000000000, max_network_bytes = 1000000000000, max_network_bandwidth_for_user = 100000000000, max_network_bandwidth_for_all_users = 100000000000, max_temporary_data_on_disk_size_for_user = 100000000000, max_temporary_data_on_disk_size_for_query = 100000000000, max_backup_bandwidth = 100000000000, log_comment = '02521_aggregation_by_partitions.sql', send_logs_level = 'warning', prefer_localhost_replica = false, optimize_aggregation_in_order = true, aggregation_in_order_max_block_bytes = 11234413, read_in_order_two_level_merge_threshold = 6, max_hyperscan_regexp_length = 1000000, max_hyperscan_regexp_total_length = 10000000, allow_introspection_functions = true, database_atomic_wait_for_drop_and_detach_synchronously = true, optimize_if_transform_strings_to_enum = true, optimize_functions_to_subcolumns = false, optimize_append_index = true, lock_acquire_timeout = 60., optimize_trivial_insert_select = true, optimize_use_projections = false, use_query_cache = false, query_cache_nondeterministic_function_handling = 'ignore', query_cache_system_table_handling = 'ignore', query_cache_max_size_in_bytes = 10000000, query_cache_max_entries = 100000, use_query_condition_cache = false, allow_aggregate_partitions_independently = true, force_aggregate_partitions_independently = true, database_replicated_allow_replicated_engine_arguments = 1, distributed_ddl_entry_format_version = 6, external_storage_max_read_rows = 10000000000, external_storage_max_read_bytes = 10000000000, local_filesystem_read_prefetch = true, remote_filesystem_read_prefetch = false, merge_tree_min_bytes_per_task_for_remote_reading = 8388608, merge_tree_compact_parts_min_granules_to_multibuffer_read = 40, async_insert_busy_timeout_max_ms = 5000, enable_filesystem_cache = true, enable_filesystem_cache_on_write_operations = true, throw_on_error_from_cache_on_write_operations = true, filesystem_cache_segments_batch_size = 5, page_cache_inject_eviction = true, load_marks_asynchronously = true, allow_prefetched_read_pool_for_remote_filesystem = false, allow_prefetched_read_pool_for_local_filesystem = false, filesystem_prefetch_step_marks = 50, filesystem_prefetch_max_memory_usage = 33554432, filesystem_prefetches_limit = 0, allow_deprecated_database_ordinary = true, max_streams_for_merge_tree_reading = 1000, optimize_sorting_by_input_stream_properties = false, insert_keeper_max_retries = 100, insert_keeper_retry_initial_backoff_ms = 1, insert_keeper_retry_max_backoff_ms = 10, insert_keeper_fault_injection_probability = 0.009999999776482582, ignore_drop_queries_probability = 0.20000000298023224, optimize_distinct_in_order = false, allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 3, cluster_for_parallel_replicas = 'parallel_replicas', parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, session_timezone = 'America/Mazatlan', optimize_extract_common_expressions = false) Received signal Segmentation fault (11)
[Mordor] 2025.06.04 04:33:45.450272 [ 108170 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
[Mordor] 2025.06.04 04:33:45.450283 [ 108170 ] <Fatal> BaseDaemon: Stack trace: 0x0000558800f08294 0x00005588021cb7a2 0x00005588023e7e8c 0x00005588023e71f0 0x000055880224e932 0x00005588024558b6 0x00005587fe8ef561 0x00005587fe8ef30c 0x00005587fd51de57 0x00005587fd5245f4 0x00005587fd51b0e3 0x00005587fd521df4 0x00007f87524377eb 0x00007f87524bb18c
[Mordor] 2025.06.04 04:33:45.458990 [ 108170 ] <Fatal> BaseDaemon: 3.0. inlined from /mnt/ch/ClickHouse/src/Common/PODArray.h:432: void DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>::push_back<unsigned long&>(unsigned long&)
[Mordor] 2025.06.04 04:33:45.459004 [ 108170 ] <Fatal> BaseDaemon: 3.1. inlined from /mnt/ch/ClickHouse/src/AggregateFunctions/AggregateFunctionCount.h:138: DB::AggregateFunctionCount::insertResultInto(char*, DB::IColumn&, DB::Arena*) const
[Mordor] 2025.06.04 04:33:45.459011 [ 108170 ] <Fatal> BaseDaemon: 3. /mnt/ch/ClickHouse/src/AggregateFunctions/IAggregateFunction.h:687: DB::IAggregateFunctionHelper<DB::AggregateFunctionCount>::insertResultIntoBatch(unsigned long, unsigned long, char**, unsigned long, DB::IColumn&, DB::Arena*) const @ 0x00000000145db294
[Mordor] 2025.06.04 04:33:45.676500 [ 108170 ] <Fatal> BaseDaemon: 4. /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:2009: DB::Aggregator::insertResultsIntoColumns(DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::OutputBlockColumns&&, DB::Arena*, bool, bool) const @ 0x000000001589e7a2
[Mordor] 2025.06.04 04:33:45.949790 [ 108170 ] <Fatal> BaseDaemon: 5. /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:2108: std::variant<DB::Block, std::list<DB::Block, std::allocator<DB::Block>>> DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>, HashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>>>(DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>&, HashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>>&, DB::Arena*, std::vector<std::shared_ptr<DB::Arena>, std::allocator<std::shared_ptr<DB::Arena>>>&, bool, bool) const @ 0x0000000015abae8c
[Mordor] 2025.06.04 04:33:46.138476 [ 108170 ] <Fatal> BaseDaemon: 6. /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:1866: std::variant<DB::Block, std::list<DB::Block, std::allocator<DB::Block>>> DB::Aggregator::convertToBlockImpl<DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>, HashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>>>(DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>&, HashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>>&, DB::Arena*, std::vector<std::shared_ptr<DB::Arena>, std::allocator<std::shared_ptr<DB::Arena>>>&, bool, unsigned long, bool) const @ 0x0000000015aba1f0
[Mordor] 2025.06.04 04:33:46.319022 [ 108170 ] <Fatal> BaseDaemon: 7. /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:1707: DB::Block DB::Aggregator::convertOneBucketToBlock<DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>>(DB::AggregatedDataVariants&, DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>&, DB::Arena*, bool, int) const @ 0x0000000015921932
[Mordor] 2025.06.04 04:33:46.533986 [ 108170 ] <Fatal> BaseDaemon: 8. /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:2354: std::list<DB::Block, std::allocator<DB::Block>> DB::Aggregator::prepareBlocksAndFillTwoLevelImpl<DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>>(DB::AggregatedDataVariants&, DB::AggregationMethodOneNumber<unsigned int, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState, PairNoInit<unsigned long, char*>>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, Allocator<true, true>, HashMapTable>, true, false>&, bool) const::'lambda'(unsigned long)::operator()(unsigned long) const @ 0x0000000015b288b6
[Mordor] 2025.06.04 04:33:46.685035 [ 108170 ] <Fatal> BaseDaemon: 9.0. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[Mordor] 2025.06.04 04:33:46.685060 [ 108170 ] <Fatal> BaseDaemon: 9.1. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[Mordor] 2025.06.04 04:33:46.685069 [ 108170 ] <Fatal> BaseDaemon: 9. /mnt/ch/ClickHouse/src/Common/threadPoolCallbackRunner.h:129: void DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::function<void ()>>::executeCallback<std::function<void ()>>(std::promise<void>&, std::function<void ()>&&) @ 0x0000000011fc2561
[Mordor] 2025.06.04 04:33:46.768420 [ 108170 ] <Fatal> BaseDaemon: 10. /mnt/ch/ClickHouse/src/Common/threadPoolCallbackRunner.h:178: DB::ThreadPoolCallbackRunnerLocal<void, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>, std::function<void ()>>::operator()(std::function<void ()>&&, Priority, std::optional<unsigned long>)::'lambda'()::operator()() @ 0x0000000011fc230c
[Mordor] 2025.06.04 04:33:46.776323 [ 108170 ] <Fatal> BaseDaemon: 11.0. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[Mordor] 2025.06.04 04:33:46.776336 [ 108170 ] <Fatal> BaseDaemon: 11.1. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[Mordor] 2025.06.04 04:33:46.776345 [ 108170 ] <Fatal> BaseDaemon: 11. /mnt/ch/ClickHouse/src/Common/ThreadPool.cpp:799: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000010bf0e57
[Mordor] 2025.06.04 04:33:46.784643 [ 108170 ] <Fatal> BaseDaemon: 12.0. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
[Mordor] 2025.06.04 04:33:46.784654 [ 108170 ] <Fatal> BaseDaemon: 12.1. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
[Mordor] 2025.06.04 04:33:46.784663 [ 108170 ] <Fatal> BaseDaemon: 12.2. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
[Mordor] 2025.06.04 04:33:46.784669 [ 108170 ] <Fatal> BaseDaemon: 12. /mnt/ch/ClickHouse/src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000010bf75f4
[Mordor] 2025.06.04 04:33:46.791432 [ 108170 ] <Fatal> BaseDaemon: 13.0. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[Mordor] 2025.06.04 04:33:46.791442 [ 108170 ] <Fatal> BaseDaemon: 13.1. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[Mordor] 2025.06.04 04:33:46.791445 [ 108170 ] <Fatal> BaseDaemon: 13. /mnt/ch/ClickHouse/src/Common/ThreadPool.cpp:809: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000010bee0e3
[Mordor] 2025.06.04 04:33:46.805319 [ 108170 ] <Fatal> BaseDaemon: 14.0. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
[Mordor] 2025.06.04 04:33:46.805337 [ 108170 ] <Fatal> BaseDaemon: 14.1. inlined from /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
[Mordor] 2025.06.04 04:33:46.805347 [ 108170 ] <Fatal> BaseDaemon: 14. /mnt/ch/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000010bf4df4
[Mordor] 2025.06.04 04:33:46.806032 [ 108170 ] <Fatal> BaseDaemon: 15. /usr/src/debug/glibc/glibc/nptl/pthread_create.c:448: start_thread @ 0x00000000000957eb
[Mordor] 2025.06.04 04:33:46.806063 [ 108170 ] <Fatal> BaseDaemon: 16. ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78: __GI___clone3 @ 0x000000000011918c
[Mordor] 2025.06.04 04:33:46.806072 [ 108170 ] <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
[Mordor] 2025.06.04 04:33:48.153283 [ 108170 ] <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
[Mordor] 2025.06.04 04:33:48.153439 [ 108170 ] <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 912014, max_compress_block_size = 2942345, max_block_size = 94118, min_external_table_block_size_bytes = 100000000, max_joined_block_size_rows = 38422, max_insert_threads = 3, max_threads = 16, max_parsing_threads = 10, max_read_buffer_size = 847662, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, use_hedged_requests = false, idle_connection_timeout = 36000, s3_max_get_rps = 1000000, s3_max_get_burst = 2000000, s3_max_put_rps = 1000000, s3_max_put_burst = 2000000, s3_check_objects_after_upload = true, use_uncompressed_cache = true, max_remote_read_network_bandwidth = 1000000000000, max_remote_write_network_bandwidth = 1000000000000, max_local_read_bandwidth = 1000000000000, max_local_write_bandwidth = 1000000000000, stream_like_engine_allow_direct_select = true, enable_multiple_prewhere_read_steps = false, replication_wait_for_inactive_replica_timeout = 30, min_count_to_compile_expression = 0, min_count_to_compile_sort_description = 0, group_by_two_level_threshold = 403627, group_by_two_level_threshold_bytes = 1, distributed_aggregation_memory_efficient = false, enable_memory_bound_merging_of_aggregation_results = false, allow_nonconst_timezone_arguments = true, min_chunk_bytes_for_parallel_parsing = 11046431, min_bytes_to_use_direct_io = 1, min_bytes_to_use_mmap_io = 10737418240, use_skip_indexes_if_final = true, use_skip_indexes_if_final_exact_mode = true, secondary_indices_enable_bulk_filtering = false, log_queries = true, insert_deduplicate = true, insert_quorum_timeout = 60000, table_function_remote_max_addresses = 200, memory_tracker_fault_probability = 0.0010000000474974513, merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0., http_wait_end_of_query = true, http_response_buffer_size = 6823172, fsync_metadata = true, distributed_ddl_task_timeout = 120, http_send_timeout = 60., http_receive_timeout = 60., use_index_for_in_with_subqueries_max_values = 1000000000, joined_subquery_requires_alias = false, opentelemetry_start_trace_probability = 0.10000000149011612, enable_vertical_final = false, max_rows_to_read = 20000000, max_bytes_to_read = 1000000000000, max_bytes_to_read_leaf = 1000000000000, max_rows_to_group_by = 10000000000, max_bytes_before_external_group_by = 1442450940, max_bytes_ratio_before_external_group_by = 0.2, max_rows_to_sort = 10000000000, max_bytes_to_sort = 10000000000, prefer_external_sort_block_bytes = 0, max_bytes_ratio_before_external_sort = 0.2, max_bytes_before_remerge_sort = 1697693528, max_result_rows = 1000000000, max_result_bytes = 1000000000, max_execution_time = 60., max_execution_speed = 100000000000, max_execution_speed_bytes = 10000000000000, timeout_before_checking_execution_speed = 300., max_estimated_execution_time = 600., max_columns_to_read = 20000, max_temporary_columns = 20000, max_temporary_non_const_columns = 20000, max_expanded_ast_elements = 50000, max_rows_in_set = 10000000000, max_bytes_in_set = 10000000000, max_rows_in_join = 10000000000, max_bytes_in_join = 10000000000, cross_join_min_rows_to_compress = 0, cross_join_min_bytes_to_compress = 100000000, max_rows_to_transfer = 1000000000, max_bytes_to_transfer = 1000000000, max_rows_in_distinct = 10000000000, max_bytes_in_distinct = 10000000000, max_memory_usage = 10000000000, max_memory_usage_for_user = 19899268300, max_untracked_memory = 1048576, memory_profiler_step = 1048576, memory_usage_overcommit_max_wait_microseconds = 50000, max_network_bandwidth = 100000000000, max_network_bytes = 1000000000000, max_network_bandwidth_for_user = 100000000000, max_network_bandwidth_for_all_users = 100000000000, max_temporary_data_on_disk_size_for_user = 100000000000, max_temporary_data_on_disk_size_for_query = 100000000000, max_backup_bandwidth = 100000000000, log_query_threads = false, log_comment = '02521_aggregation_by_partitions.sql', send_logs_level = 'warning', prefer_localhost_replica = false, optimize_aggregation_in_order = true, aggregation_in_order_max_block_bytes = 11234413, read_in_order_two_level_merge_threshold = 6, max_hyperscan_regexp_length = 1000000, max_hyperscan_regexp_total_length = 10000000, allow_introspection_functions = true, max_partitions_per_insert_block = 100, database_atomic_wait_for_drop_and_detach_synchronously = true, optimize_if_transform_strings_to_enum = true, optimize_functions_to_subcolumns = false, optimize_append_index = true, lock_acquire_timeout = 60., optimize_trivial_insert_select = true, enable_global_with_statement = true, optimize_use_projections = false, use_query_cache = false, query_cache_nondeterministic_function_handling = 'ignore', query_cache_system_table_handling = 'ignore', query_cache_max_size_in_bytes = 10000000, query_cache_max_entries = 100000, use_query_condition_cache = false, allow_aggregate_partitions_independently = true, force_aggregate_partitions_independently = true, database_replicated_initial_query_timeout_sec = 120, database_replicated_enforce_synchronous_settings = true, database_replicated_always_detach_permanently = true, database_replicated_allow_replicated_engine_arguments = 1, distributed_ddl_output_mode = 'none', distributed_ddl_entry_format_version = 6, external_storage_max_read_rows = 10000000000, external_storage_max_read_bytes = 10000000000, local_filesystem_read_prefetch = true, remote_filesystem_read_prefetch = false, merge_tree_min_bytes_per_task_for_remote_reading = 8388608, merge_tree_compact_parts_min_granules_to_multibuffer_read = 40, async_insert_busy_timeout_max_ms = 5000, enable_filesystem_cache = true, enable_filesystem_cache_on_write_operations = true, throw_on_error_from_cache_on_write_operations = true, filesystem_cache_segments_batch_size = 5, page_cache_inject_eviction = true, load_marks_asynchronously = true, allow_prefetched_read_pool_for_remote_filesystem = false, allow_prefetched_read_pool_for_local_filesystem = false, filesystem_prefetch_step_marks = 50, filesystem_prefetch_max_memory_usage = 33554432, filesystem_prefetches_limit = 0, allow_deprecated_database_ordinary = true, max_streams_for_merge_tree_reading = 1000, optimize_sorting_by_input_stream_properties = false, insert_keeper_max_retries = 100, insert_keeper_retry_initial_backoff_ms = 1, insert_keeper_retry_max_backoff_ms = 10, insert_keeper_fault_injection_probability = 0.009999999776482582, ignore_drop_queries_probability = 0.20000000298023224, optimize_distinct_in_order = false, allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 3, cluster_for_parallel_replicas = 'parallel_replicas', parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, session_timezone = 'America/Mazatlan', optimize_extract_common_expressions = false, allow_experimental_database_replicated = true, input_format_null_as_default = false
```

Looks like we probably have swallowed a memory exception somewhere as `place` is NULL

```
#0  DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>::push_back<unsigned long&> (this=<optimized out>, 
    x=<error reading variable: Cannot access memory at address 0x0>) at /mnt/ch/ClickHouse/src/Common/PODArray.h:432
#1  DB::AggregateFunctionCount::insertResultInto (this=0x7f84c1b127b8, place=0x0, to=...) at /mnt/ch/ClickHouse/src/AggregateFunctions/AggregateFunctionCount.h:138
#2  DB::IAggregateFunctionHelper<DB::AggregateFunctionCount>::insertResultIntoBatch (this=0x7f84c1b127b8, row_begin=<optimized out>, row_end=958, places=0x7f846c1cc040, place_offset=0, 
    to=..., arena=0x7f84896e10a0) at /mnt/ch/ClickHouse/src/AggregateFunctions/IAggregateFunction.h:687
#3  0x00005588021cb7a2 in DB::Aggregator::insertResultsIntoColumns (this=this@entry=0x7f874bde8c10, places=..., out_cols=..., arena=0x7f84896e10a0, has_null_key_data=<optimized out>, 
    use_compiled_functions=<optimized out>) at /mnt/ch/ClickHouse/src/Interpreters/Aggregator.cpp:2009
```

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed possible crash in `Aggregator` in case of exception during merge.

---

Closes: #81283

### CODE REVIEW

**Comment by Algunenano** [comment]
This cannot be a "Not for changelog" when it's fixing a crash in an already released release (25.5)

File: src/Interpreters/Aggregator.cpp [hunk 1]
```diff
@@ -3100,6 +3100,9 @@ void Aggregator::mergeBlocks(BucketToBlocks bucket_to_blocks, AggregatedDataVari
                 if (bucket > max_bucket)
                     break;
 
+                if (!bucket_to_blocks.contains(bucket))
```
Comment (Algunenano) [inline src/Interpreters/Aggregator.cpp:3103]: 2 questions:
* A general one about the function: Shouldn't `bucket_to_blocks` be a reference?
* And about this change: Why? It seems the for-loop after checking is_cancelled is going to do the exact same as this if.

File: src/Interpreters/Aggregator.cpp [hunk 2]
```diff
@@ -3134,14 +3137,13 @@ void Aggregator::mergeBlocks(BucketToBlocks bucket_to_blocks, AggregatedDataVari
...
                 }
-
-                runner.waitForAllToFinishAndRethrowFirstError();
             }
             catch (...)
             {
                 is_cancelled.store(true);
                 runner.waitForAllToFinishAndRethrowFirstError();
             }
+            runner.waitForAllToFinishAndRethrowFirstError();
```
Comment (Algunenano) [inline src/Interpreters/Aggregator.cpp:3146]: Do we still need the `waitForAll...` in the catch?

File: src/Interpreters/Aggregator.cpp (hunk 1 above)
Comment (nickitat) [reply src/Interpreters/Aggregator.cpp:3103]: * it is a reference (we capture a reference to it)
* just seemed logical to me. not needed for correctness, indeed

File: src/Interpreters/Aggregator.cpp (hunk 2 above)
Comment (nickitat) [reply src/Interpreters/Aggregator.cpp:3146]: I think we should replace it with `throw;`. Exception might also be thrown inside 

``` cpp
result.aggregates_pools.push_back(std::make_shared<Arena>());
```

for example, in this case it won't be caught by the `runner` as far as I understand. But it will be caught by the `catch` on l.3141. Also `runner` will wait for all tasks in its dtor anyway, so it seems we're safe.

File: src/Interpreters/Aggregator.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Interpreters/Aggregator.cpp:3103]: > it is a reference (we capture a reference to it)

It's not in this function. There are 2 `Aggregator::mergeBlocks` and this one does not use a reference and passes a copy

**Review by Algunenano — APPROVED** [review]

**Comment by maxknv** [comment]
cidb data [looks suspicious](https://play.clickhouse.com/play?user=play#c2VsZWN0ICoKZnJvbSBjaGVja3MKd2hlcmUgY2hlY2tfbmFtZSBMSUtFICdTdGF0ZWxlc3MlbXNhbiUnCmFuZCBjaGVja19zdGFydF90aW1lID4gbm93KCkgLSBpbnRlcnZhbCAxMCBkYXkKYW5kIHRlc3Rfc3RhdHVzCT0gJ0ZBSUwnCmFuZCB0ZXN0X2NvbnRleHRfcmF3IGxpa2UgJyVEQjo6RXhjZXB0aW9uOiAodG90YWwpIG1lbW9yeSBsaW1pdCBleGNlZWRlZCUnCQpvcmRlciBieSBjaGVja19zdGFydF90aW1lCgo=) for this PR.
