### PR TITLE
Fix ZlibInflatingReadBuffer returns empty buffer while eof is not reached yet

### LINKED ISSUE #74708: Assertion failed when using ZlibInflatingReadBuffer
### Company or project name

_No response_

### Describe what's wrong

Insert from a gzip compressed file failed with assertion failed

### Does it reproduce on the most recent release?

Yes

### How to reproduce

1. Generate a gz file by this script, the generated file can be processed by gzip -d command
```python
import zlib
def compress_string(input_string):
    compressor = zlib.compressobj(wbits=zlib.MAX_WBITS | 16)
    compressed_data = compressor.compress(input_string.encode('utf-8'))
    compressed_data += compressor.flush()
    return compressed_data
with open('compressed.gz', 'wb') as f:
    for raw_str in ['{"value": "abc"} ', '{"value": "abc"}']:
        f.write(compress_string(raw_str))
```
2. Create table
```sql
CREATE TABLE default.mc_sc
(
    `value` String
)
ENGINE = MergeTree
ORDER BY tuple()
```
4. Insert data
```sql
set max_read_buffer_size = 1;
set input_format_parallel_parsing = 0;
insert into mc_sc from infile '/data.gz' format JSONEachRow;
```

### Expected behavior

Insert data normally

### Error message and/or stacktrace

```text
Logical error: 'position() < working_buffer.end()'.
Stack trace (when copying this message, always include the lines below):

0. /home/siyuan/clickhouse/src/Common/StackTrace.cpp:381: StackTrace::tryCapture() @ 0x000000000cdc2d92
1. /home/siyuan/clickhouse/src/Common/Exception.cpp:53: DB::abortOnFailedAssertion(String const&) @ 0x000000000cd907d5
2. /home/siyuan/clickhouse/src/IO/ReadBuffer.h:75: DB::ReadBuffer::next() @ 0x000000000777b5c1
3. /home/siyuan/clickhouse/src/IO/ReadBuffer.h:103: DB::JSONEachRowRowInputFormat::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadE
xtension&) @ 0x000000001487be0f
4. /home/siyuan/clickhouse/src/Processors/Formats/IRowInputFormat.cpp:143: DB::IRowInputFormat::read() @ 0x00000000147ca132
5. /home/siyuan/clickhouse/src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x00000000147729f6
6. /home/siyuan/clickhouse/src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x0000000014753317
7. /home/siyuan/clickhouse/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x00000000147530e7
8. /home/siyuan/clickhouse/src/Processors/Executors/ExecutionThreadContext.cpp:49: DB::ExecutionThreadContext::executeTask() @ 0x000000001476a434
9. /home/siyuan/clickhouse/src/Processors/Executors/PipelineExecutor.cpp:290: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014760505
10. /home/siyuan/clickhouse/src/Processors/Executors/PipelineExecutor.cpp:164: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x000000001475f9e9
11. /home/siyuan/clickhouse/src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x000000001476dd1f
12. /home/siyuan/clickhouse/src/Storages/StorageFile.cpp:1474: DB::StorageFileSource::generate() @ 0x0000000013b22319
13. /home/siyuan/clickhouse/src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x0000000014753317
14. /home/siyuan/clickhouse/src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x00000000147530e7
15. /home/siyuan/clickhouse/src/Processors/Executors/ExecutionThreadContext.cpp:49: DB::ExecutionThreadContext::executeTask() @ 0x000000001476a434
16. /home/siyuan/clickhouse/src/Processors/Executors/PipelineExecutor.cpp:290: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014760505
17. /home/siyuan/clickhouse/src/Processors/Executors/PipelineExecutor.cpp:256: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001476079e
18. /home/siyuan/clickhouse/src/Processors/Executors/PipelineExecutor.cpp:455: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001475f087
19. /home/siyuan/clickhouse/src/Processors/Executors/PipelineExecutor.cpp:127: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001475ea6f
20. /home/siyuan/clickhouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se180100]<std::__function::__default_alloc_func<ThreadFromGlobalPo
olImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__polic
y_storage const*) @ 0x000000001476d26a
21. /home/siyuan/clickhouse/contrib/llvm-project/libcxx/include/__functional/function.h:714: ? @ 0x000000000ce53806
22. /home/siyuan/clickhouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:312: void* std::__thread_proxy[abi:se180100]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct
>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000ce590e0
23. start_thread @ 0x0000000000007fa3
24. ? @ 0x00000000000f906f
```

If use a release build to execute this command, the insert query will failed with exception `std::length_error, e.what() = basic_string`

### Additional context

ZlibInflatingReadBuffer's nextImpl may return non eof while return non empty buffer. So sometimes, ReadBuffer's eof call may return false, while the working buffer is still empty, but some code has use this buffer directly, for example readChar in ReadHelpers.h

### PR DESCRIPTION
**Pull request by linkwk7**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix insertion of gzip-ed data sometimes fails due to flawed decompression on client side.

fix #74708 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Stateful tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Non-blocking CI mode (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by rschu1ze** [comment]
@CheSema

**Comment by yakov-olkhovskiy** [comment]
I was not able to reproduce it with example in the original issue.

File: src/IO/ReadBuffer.h [hunk 1]
```diff
@@ -63,20 +63,23 @@ class ReadBuffer : public BufferBase
...
+            if (!res)
+            {
+                working_buffer = Buffer(pos, pos);
+            }
+            else
+            {
+                pos = working_buffer.begin() + std::min(nextimpl_working_buffer_offset, working_buffer.size());
+            }
+            nextimpl_working_buffer_offset = 0;
+        } while (res && available() == 0);
```
Comment (yakov-olkhovskiy) [inline src/IO/ReadBuffer.h:80]: I don't think this is a right place to fix this issue - the problem is with ZlibInflatingReadBuffer

**Comment by yakov-olkhovskiy** [comment]
First of all it doesn't look like a correct way to fix this issue - I guess the real problem is here:
https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/ZlibInflatingReadBuffer.cpp#L103
The second issue - we need test for this bug - which leads to the third issue - I was not able to reproduce this bug with provided example - I guess problem here is that probably some zlib library produces different compressed data so we have this issue on decompression - in such case we can't rely on installed zlib (or gzip) to produce sample for the test - you will need to provide compressed file with which this bug can be reproduced.

**Comment by linkwk7** [comment]
@yakov-olkhovskiy Hi, for issue 1, since in ReadBuffer's next function call, it may move position iterator based on nextimpl_working_buffer_offset, so there are other scenario which after ReadBuffer's next function is invoked, it may return true, but position is already point to the end of working buffer. For example, if CachedCompressedReadBuffer is seek to a end of compressed block and it perform lazy seek. So i think maybe we can just fix in ReadBuffer's next, and all nextImpl didn't have to guarantee when nextImpl returns true it will have a non empty working buffer
For issue 2 and issue3, i add a test for this and attach the file to reproduce it

**Comment by yakov-olkhovskiy** [comment]
@linkwk7 
>for issue 1, since in ReadBuffer's next function call, it may

it all doesn't matter - the comment for `nextImpl()` states:
```
    /** Read the next data and fill a buffer with it.
      * Return `false` in case of the end, `true` otherwise.
      * Throw an exception if something is wrong.
      */
    virtual bool nextImpl() { return false; }
```
so, it's an interface contract and we shouldn't break it. For `nextimpl_working_buffer_offset` case it maybe a discussion, but I think all these cases can be resolved on the level of implementation of specific buffer.

also, could you please provide zlib version which produced this strange compression - I want to try to understand why it happens at all...

**Comment by yakov-olkhovskiy** [comment]
This post is not related to the fixing this bug.
My observations so far:
- bug does not appear in local - only (debug) client produces assertion core dump with consequent server's `Attempt to read after eof` exception - this nuance is curious - why the difference?
- the compressed data should be generated in two steps as @linkwk7 suggested in the original issue - i.e. `for raw_str in ['{"value": "abc"} ', '{"value": "abc"}']:` - if it's done with single line then generated compressed data does not trigger this bug - so apparently it is related to compression blocks within gzip codec.

Side note:
Thanks @linkwk7 for finding this bug and pointing out potential issues with `nextimpl_working_buffer_offset` - it was not clear from interface contract that its value should be taken into account by implementation which should guarantee buffer is still not empty even after applying this value to the position of the `ReadBuffer`. Unfortunately this architecture of buffer is unavoidably flawed because in order to make it fast by avoiding data copying we had decided to make this buffer fundamentally intrusive...

**Review by yakov-olkhovskiy — APPROVED** [review]
