### PR TITLE
Fix Logical error with suspicious LowCardinality: Function toInt256 with Null argument and default implementation for Nulls is expected to return Nullable result, got Int256

### LINKED ISSUE #72265: Logical error with suspicious `LowCardinality`: `Function toInt256 with Null argument and default implementation for Nulls is expected to return Nullable result, got Int256`
**Describe the bug**
A link to the report

**How to reproduce**
```sql
SET allow_suspicious_low_cardinality_types = 1;
SET send_logs_level = 'error';

DROP TABLE IF EXISTS t_primary_index_cache__fuzz_15;

CREATE TABLE t_primary_index_cache__fuzz_15 (`a` LowCardinality(Nullable(Int64)), `b` UInt64) ENGINE = MergeTree PARTITION BY a % 2 ORDER BY a SETTINGS allow_nullable_key = 1, index_granularity = 64, index_granularity_bytes = '10M', min_bytes_for_wide_part = 0;

INSERT INTO t_primary_index_cache__fuzz_15 SELECT number, number FROM numbers(10000);

SELECT count() FROM t_primary_index_cache__fuzz_15 WHERE (a > 100) AND ((a % 2) = toUInt128(0));
```

```
<Error> executeQuery: Code: 49. DB::Exception: Function toInt256 with Null argument and default implementation for Nulls is expected to return Nullable result, got Int256. (LOGICAL_ERROR) (version 24.12.1.1) (from 127.0.0.1:57226) (in query: SELECT count() FROM t_primary_index_cache__fuzz_15 WHERE (a > 100) AND ((a % 2) = toUInt128(0));), Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x0000000014cd6072
1. ./build_clang/./src/Common/Exception.cpp:109: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000ba81c99
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000069b0f0c
3. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x00000000069b236b
4. DB::IExecutableFunction::defaultImplementationForNulls(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b0ba1
5. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b029d
6. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b12e2
7. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b249b
8. DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b28d9
9. COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__function::__default_alloc_func<DB::(anonymous namespace)::FunctionCast::createFunctionAdaptor(std::shared_ptr<DB::IFunction>, std::shared_ptr<DB::IDataType const> const&)::'lambda'(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>>(std::__function::__policy_storage const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) @ 0x000000000f4411b6
10. COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__function::__default_alloc_func<DB::(anonymous namespace)::FunctionCast::prepareRemoveNullable(std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::IDataType const> const&, bool) const::'lambda'(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>>(std::__function::__policy_storage const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) @ 0x000000000f5ec6e7
11. DB::(anonymous namespace)::ExecutableFunctionCast::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000f42007a
12. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b02e5
13. DB::IExecutableFunction::defaultImplementationForConstantArguments(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3afedb
14. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b0272
15. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b11fb
16. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b249b
17. DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f3b28d9
18. ./build_clang/./src/Storages/MergeTree/KeyCondition.cpp:909: DB::applyFunction(std::shared_ptr<DB::IFunctionBase const> const&, std::shared_ptr<DB::IDataType const> const&, DB::FieldRef const&) @ 0x0000000011f750dc
19. ./build_clang/./src/Storages/MergeTree/KeyCondition.cpp:2745: DB::KeyCondition::applyMonotonicFunctionsChainToRange(DB::Range, std::vector<std::shared_ptr<DB::IFunctionBase const>, std::allocator<std::shared_ptr<DB::IFunctionBase const>>> const&, std::shared_ptr<DB::IDataType const>, bool) @ 0x0000000011f74c37
20. ./build_clang/./src/Storages/MergeTree/KeyCondition.cpp:3046: DB::KeyCondition::checkInHyperrectangle(std::vector<DB::Range, std::allocator<DB::Range>> const&, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const>>> const&) const @ 0x0000000011f7841a
21. ./build_clang/./src/Storages/MergeTree/KeyCondition.cpp:2708: DB::KeyCondition::checkInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const>>> const&, BoolMask) const @ 0x0000000011f7457a
22. ./build_clang/./src/Storages/MergeTree/KeyCondition.cpp:3290: DB::KeyCondition::mayBeTrueInRange(unsigned long, DB::FieldRef const*, DB::FieldRef const*, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const>>> const&) const @ 0x0000000011f7a24e
23. ./build_clang/./src/Storages/MergeTree/PartitionPruner.cpp:37: DB::PartitionPruner::canBePruned(DB::IMergeTreeDataPart const&) const @ 0x00000000122562bc
24. ./build_clang/./src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:1621: DB::MergeTreeDataSelectExecutor::selectPartsToRead(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>&, std::optional<std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>> const&, std::optional<DB::KeyCondition> const&, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const>>> const&, std::optional<DB::PartitionPruner> const&, std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>> const*, DB::MergeTreeDataSelectExecutor::PartFilterCounters&, std::shared_ptr<DB::QueryStatus>) @ 0x00000000120d3ab3
25. ./build_clang/./src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp:581: DB::MergeTreeDataSelectExecutor::filterPartsByPartition(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>&, std::optional<DB::PartitionPruner> const&, std::optional<DB::KeyCondition> const&, std::optional<std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeTreeData const&, std::shared_ptr<DB::Context const> const&, std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>> const*, std::shared_ptr<Poco::Logger>, std::vector<DB::ReadFromMergeTree::IndexStat, std::allocator<DB::ReadFromMergeTree::IndexStat>>&) @ 0x00000000120d22db
26. ./build_clang/./src/Processors/QueryPlan/ReadFromMergeTree.cpp:1736: DB::ReadFromMergeTree::selectRangesToRead(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const>, unsigned long, std::shared_ptr<std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>>>, DB::MergeTreeData const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<Poco::Logger>, std::optional<DB::ReadFromMergeTree::Indexes>&, bool) @ 0x0000000012a58b6d
27. ./build_clang/./src/Processors/QueryPlan/ReadFromMergeTree.cpp:1480: DB::ReadFromMergeTree::selectRangesToRead(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, bool) const @ 0x0000000012a57f7b
28. ./build_clang/./src/Processors/QueryPlan/ReadFromMergeTree.cpp:1475: DB::ReadFromMergeTree::selectRangesToRead(bool) const @ 0x0000000012a57d88
29. ./build_clang/./src/Processors/QueryPlan/Optimizations/optimizeUseAggregateProjection.cpp:612: DB::QueryPlanOptimizations::optimizeUseAggregateProjections(DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, bool) @ 0x0000000012afa10d
30. ./build_clang/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:164: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000012ad99ec
31. ./build_clang/./src/Processors/QueryPlan/QueryPlan.cpp:471: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x0000000012a3ef3d
32. 
```

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bug in unreleased changes

Closes https://github.com/ClickHouse/ClickHouse/issues/72265

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 3bd4fcd009d6f926c3beb0dbb8fb23a3ba14cfd9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74205/3bd4fcd009d6f926c3beb0dbb8fb23a3ba14cfd9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/73705/f00efc9b31ef2271a055e9f3ba1c94ac78a882cc/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by Algunenano — COMMENTED** [review]
Please add the tests in the repro issue

**Comment by taiyang-li** [comment]
> Please add the tests in the repro issue

done.

**Comment by taiyang-li** [comment]
Failed ut: https://s3.amazonaws.com/clickhouse-test-reports/74205/b94ea674591889a9367f5c41877112081e44d739/stateless_tests__debug__s3_storage_.html  could not reproduced in my local machine.

**Comment by Algunenano** [comment]
* AST fuzzer (asan) -> https://github.com/ClickHouse/ClickHouse/issues/74292
* AST fuzzer (ubsan) -> https://github.com/ClickHouse/ClickHouse/issues/74293

File: src/Functions/IFunction.cpp [hunk 1]
```diff
@@ -191,7 +191,7 @@ ColumnPtr IExecutableFunction::defaultImplementationForNulls(
 
     NullPresence null_presence = getNullPresense(args);
 
-    if (null_presence.has_null_constant || null_presence.has_nullable)
+    if (null_presence.has_null_constant)
```
Comment (Algunenano) [inline src/Functions/IFunction.cpp:194]: The 2 if conditions are now the same

**Comment by taiyang-li** [comment]
> * AST fuzzer (asan) -> [Empty result column after evaluation of constant expression for IN, VALUES, or LIMIT, or aggregate function parameter, or a table function argument #74292](https://github.com/ClickHouse/ClickHouse/issues/74292)
> * AST fuzzer (ubsan) -> [LOGICAL_ERROR: Size of selector: 1 doesn't match size of column: 0 #74293](https://github.com/ClickHouse/ClickHouse/issues/74293)

I tried with clickhouse version before https://github.com/ClickHouse/ClickHouse/pull/73820 is merged. The two tests still can't pass. 

```
SELECT
materialize(1) AND 0,
 arrayFold((acc, x) -> x, [0, 1], toUInt8(0)); 
```

File: src/Functions/IFunction.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Functions/IFunction.cpp:194]: Please don't ignore this comment

Comment (Algunenano) [reply src/Functions/IFunction.cpp:194]: This code is now doing:

```
if (a)
{
   // do X
}

if (a)
{
  // do Y
}
```

It should be:
```
if (a)
{
  // do X
  // do Y
}
```

Comment (taiyang-li) [reply src/Functions/IFunction.cpp:194]: get..
