### PR TITLE
Fix possible odbc invalid cursor state

### LINKED ISSUE #29473: Invalid cursor state from ODBC bridge to SQL Server
We use 40 dictionaries based on SQL queries to an SQL server, feeding tables with various sizes (smallest is a few lines, biggest is a few millions). They are configured to refresh every 5 minutes
Sometimes the dictionaries get "stuck" and each refresh (automatic or via "SYSTEM RELOAD DICTIONARIES") end up failed, with the following exception:

```
Code: 86, e.displayText() = DB::Exception: Received error from remote server /?connection_string=DSN%3DSERVERNAME%3BUID%3DXXXXXX%3BPWD%3DXXXXXX&max_block_size=8192. HTTP status code: 500 Internal Server Error, body: �std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1625: 2400: [FreeTDS][SQL Server]Invalid cursor state , Stack trace (when copying this message, always include the lines below):

0. ? @ 0x3a66342 in /usr/bin/clickhouse-odbc-bridge
1. ? @ 0x3a6893d in /usr/bin/clickhouse-odbc-bridge
2. ? @ 0x3a67a31 in /usr/bin/clickhouse-odbc-bridge
3. ? @ 0x2b52b7b in /usr/bin/clickhouse-odbc-bridge
4. ? @ 0x2b4c74d in /usr/bin/clickhouse-odbc-bridge
5. ? @ 0x3a05cd0 in /usr/bin/clickhouse-odbc-bridge
6. ? @ 0x52f5a8f in /usr/bin/clickhouse-odbc-bridge
7. ? @ 0x52f74fa in /usr/bin/clickhouse-odbc-bridge
8. ? @ 0x5e935b9 in ?
9. ? @ 0x5e9002a in ?
10. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
11. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 21.6.4.26 (official build)) (version 21.6.4.26 (official build))
```
 
We can most if the time reset them by manually killing the clickhouse-odbc-bridge process and forcing a refresh, however it often fails once again soon after, with the same exception. Note that the distant SQL server is indeed quite unstable, so a few failures are not suprising, however I'd not expect to have to reboot the odbc bridge to make it work once again.

We only tried on version 21.6.4.26, but the issue reproduces itself quite often. 

I also noticed that the odbc-bridge comes with a very long timeout:
`
/usr/bin/clickhouse-odbc-bridge --http-port 9018 --listen-host 127.0.0.1 --http-timeout 1800000000
`
This was discussed here https://github.com/ClickHouse/ClickHouse/issues/5089 but closed with a message that I feel doesn't answer the original question. As it  is, unless I'm mistaken, the timeout is 20 days! The http_receive_timeout is set in the config at 1800s, which is much better.

Any help would be appreciated, we could always cron a check on dictionary state and autokill the bridge, but it looks like a dirty solution which an honest timeout should handle

PS: we should probably slow down the refresh rate on very big tables too, maybe it would help?

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
In ODBC bridge add retries for error Invalid cursor state. It is a retriable error. Closes https://github.com/ClickHouse/ClickHouse/issues/29473.

### CODE REVIEW

**Review by Avogar — APPROVED** [review]

File: programs/odbc-bridge/ODBCConnectionFactory.h [hunk 1]
```diff
@@ -81,8 +81,12 @@ T execute(nanodbc::ConnectionHolderPtr connection_holder, std::function<T(nanodb
...
     catch (const nanodbc::database_error & e)
     {
-        /// SQLState, connection related errors start with 08S0.
-        if (e.state().starts_with("08S0"))
+        tryLogCurrentException(__PRETTY_FUNCTION__);
+        /// SQLState, connection related errors start with 08 (main: 08S01), cursor invalid state is 24000.
+        /// Invalid cursor state is a retriable error.
+        /// Invalid transaction state 25000. Truncate to 4 letters, because nanodbc does it.
+        /// https://docs.microsoft.com/ru-ru/sql/odbc/reference/appendixes/appendix-a-odbc-error-codes?view=sql-server-ver15
+        if (e.state().starts_with("08") || e.state().starts_with("24") || e.state().starts_with("2500"))
```
Comment (tavplubix) [inline programs/odbc-bridge/ODBCConnectionFactory.h:89]:
```suggestion
        if (e.state().starts_with("08") || e.state().starts_with("24") || e.state().starts_with("25"))
```
See https://www.postgresql.org/docs/10/errcodes-appendix.html

**Review by tavplubix — APPROVED** [review]

**Comment by kssenii** [comment]
@Mergifyio update
