### PR TITLE
ISSUES-117 support temporary table management

### LINKED ISSUE #117: Temporary table management
Hey, Happy Birthday to your company and thanks for making an awesome DBMS!

It'd be great to have better control over the native `TEMPORARY TABLE`s.
For instance, if you create one using `CREATE TEMPORARY TABLE temp_table (id UInt8);`,
you won't be able to
1) execute `SHOW CREATE TABLE temp_table;`
`#107: Cannot open file /.../metadata/default/temp_table.sql, errno: 2, strerror: No such file or directory.`

Judging by the exception, it may look like it supports just the permanently-stored ones, but you certainly can do `SHOW CREATE TABLE` over the regular tables with the `Memory` engine.
Also I've thought that the table was already deleted, but it was the same session and `SELECT * FROM temp_table;` works OK.

2) Same with `SHOW TABLES;` - the temporary tables aren't there.

3) You can't run `DROP TABLE` over a temporary table. You can over a `Memory` one though.
Of course, I'm free to end the session to make it disappear, but nevertheless...

I understand that it's not a big deal, and I guess I can send a pull request later that reflects these issues in the documentation. Just wanted to let you know.

### PR DESCRIPTION
**Pull request by zhang2014**
fix #117
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

File: dbms/src/Parsers/ParserShowTablesQuery.cpp [hunk 1]
```diff
@@ -37,28 +38,29 @@ bool ParserShowTablesQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expec
...
     {
         query->databases = true;
-    }
-    else if (s_tables.ignore(pos, expected))
-    {
-        if (s_from.ignore(pos, expected))
-        {
-            if (!name_p.parse(pos, database, expected))
-                return false;
+    } else {
```
Comment (ludv1x) [inline dbms/src/Parsers/ParserShowTablesQuery.cpp]: Style: 
```
}
else
{
    /// ...
}
```

File: dbms/src/Storages/System/StorageSystemTables.cpp [hunk 2]
```diff
@@ -30,6 +31,9 @@ static ColumnPtr getFilteredDatabases(const ASTPtr & query, const Context & cont
     for (const auto & db : context.getDatabases())
         column->insert(db.first);
 
+    std::string temporary_database = "";
+    column->insert(temporary_database);
```
Comment (ludv1x) [inline dbms/src/Storages/System/StorageSystemTables.cpp]: Just `column->insert(String{})` ?

File: dbms/tests/queries/0_stateless/00492_drop_temporary_table.sql [hunk 3]
```diff
@@ -1,8 +1,8 @@
...
-select number from temp_tab;
-drop table temp_tab;
-create temporary table temp_tab (number UInt64);
-select number from temp_tab;
-drop table temp_tab;
+DROP TEMPORARY TABLE IF EXISTS temp_tab;
+CREATE TEMPORARY TABLE temp_tab (number UInt64);
+INSERT INTO temp_tab SELECT number FROM system.numbers LIMIT 1;
+SELECT number FROM temp_tab;
+DROP TEMPORARY TABLE temp_tab;
```
Comment (ludv1x) [inline dbms/tests/queries/0_stateless/00492_drop_temporary_table.sql]: Is the new syntax backwards-compatible with the previous one?

File: dbms/src/Storages/System/StorageSystemTables.cpp [hunk 4]
```diff
@@ -54,24 +58,43 @@ BlockInputStreams StorageSystemTables::read(
...
+                res_columns[4]->insert(UInt64(0));
+            }
+        } else if (context.hasSessionContext())
         {
-            auto table_name = iterator->name();
-            res_columns[0]->insert(database_name);
-            res_columns[1]->insert(table_name);
-            res_columns[2]->insert(iterator->table()->getName());
-            res_columns[3]->insert(static_cast<UInt64>(database->getTableMetadataModificationTime(context, table_name)));
+            Tables externalTables = context.getSessionContext().getExternalTables();
```
Comment (ludv1x) [inline dbms/src/Storages/System/StorageSystemTables.cpp]: Camel case (`externalTables`) is used only for function names.

File: dbms/src/Storages/System/StorageSystemTables.cpp [hunk 5]
```diff
@@ -30,6 +31,9 @@ static ColumnPtr getFilteredDatabases(const ASTPtr & query, const Context & cont
     for (const auto & db : context.getDatabases())
         column->insert(db.first);
 
+    std::string temporary_database = "";
+    column->insert(temporary_database);
+
     Block block { ColumnWithTypeAndName( std::move(column), std::make_shared<DataTypeString>(), "database" ) };
```
Comment (ludv1x) [inline dbms/src/Storages/System/StorageSystemTables.cpp]: You could also put column `temporary` into the block.
It allows excluding the temporary database in case of `WHERE temporary != 0`

File: dbms/src/Interpreters/InterpreterShowTablesQuery.cpp [hunk 6]
```diff
@@ -38,6 +38,10 @@ String InterpreterShowTablesQuery::getRewrittenQuery()
       */
     context.assertDatabaseExists(database, false);
 
+    if (query.temporary) {
```
Comment (ludv1x) [inline dbms/src/Interpreters/InterpreterShowTablesQuery.cpp]: Style

**Comment by zhang2014** [comment]
@ludv1x Thank for your reply,I have made the modification。Please help review the changes

File: dbms/src/Parsers/ParserShowTablesQuery.cpp [hunk 7]
```diff
@@ -38,27 +39,36 @@ bool ParserShowTablesQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expec
...
-            query->not_like = true;
-
-        if (s_like.ignore(pos, expected))
+        if (s_tables.ignore(pos, expected))
         {
-            if (!like_p.parse(pos, like, expected))
+            if (s_from.ignore(pos, expected))
+            {
+                if (query->temporary)
+                    throw Exception("Unable to parse FROM,Because the temporary table does not have a database.");
```
Comment (ludv1x) [inline dbms/src/Parsers/ParserShowTablesQuery.cpp]: Add an error code.
I would suggest `ErrorCodes::SYNTAX_ERROR`, but I think it is not syntax error and the check should be done in the interpreter.

File: dbms/src/Parsers/ParserShowTablesQuery.h [hunk 8]
```diff
@@ -14,7 +14,7 @@ namespace DB
 class ParserShowTablesQuery : public IParserBase
 {
 protected:
-    const char * getName() const { return "SHOW TABLES|DATABASES query"; }
+    const char * getName() const { return "SHOW [TEMPORARY] TABLES|DATABASES query"; }
```
Comment (ludv1x) [inline dbms/src/Parsers/ParserShowTablesQuery.h]: Could you add the full syntax with `NOT LIKE` ...

File: dbms/src/Storages/System/StorageSystemTables.cpp [hunk 9]
```diff
@@ -68,10 +70,28 @@ BlockInputStreams StorageSystemTables::read(
...
+                static_cast<UInt64>(database->getTableMetadataModificationTime(context, table_name)));
+            res_columns[4]->insert(UInt64(0));
+        }
+    }
+
+    if (context.hasSessionContext())
+    {
+        Tables external_tables = context.getSessionContext().getExternalTables();
+
+        for (auto table = external_tables.begin(); table != external_tables.end(); table++)
```
Comment (ludv1x) [inline dbms/src/Storages/System/StorageSystemTables.cpp]: IMHO it is better to use for-range loop
