### PR TITLE
Fix inferring Date/DateTime/DateTime64 on dates that are out of supported range

### LINKED ISSUE #86025: Strings with dates less then 1970-01-01 are infered as Date time and saved as 1970-01-01 in text formats schema inference
### Company or project name

ClickHouse Inc.

### Describe what's wrong

If a column in text format contain dates less then `1970-01-01` it's inferred as `Date` type and converts such values to default `1970-01-01` date

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
) select * from format(JSONEachRow, '{"d" : "1920-01-01"}');

SELECT *
FROM format(JSONEachRow, '{"d" : "1920-01-01"}')

Query id: 18c3c895-8676-402d-8e40-ca1a93ce2da3

   ┌──────────d─┐
1. │ 1970-01-01 │
   └────────────┘
```

### Expected behavior

It should be inferred as `String` or as `Date32`

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix inferring Date/DateTime/DateTime64 on dates that are out of supported range.

Closes https://github.com/ClickHouse/ClickHouse/issues/86025

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Common/DateLUT.cpp [hunk 1]
```diff
@@ -13,6 +13,8 @@
 #include <filesystem>
 #include <fstream>
 
+#include <iostream>
```
Comment (bharatnc) [inline src/Common/DateLUT.cpp]: Is this include actually needed?

File: src/Common/DateLUTImpl.h [hunk 2]
```diff
@@ -1177,6 +1177,22 @@ class DateLUTImpl
...
 
+    std::optional<LUTIndex> tryToMakeLUTIndex(Int16 year, UInt8 month, UInt8 day_of_month) const
+    {
+        if (unlikely(year < DATE_LUT_MIN_YEAR || month < 1 || month > 12 || day_of_month < 1 || day_of_month > 31))
+            return std::nullopt;
+
+        if (unlikely(year > DATE_LUT_MAX_YEAR))
+            return std::nullopt;
+
+        auto year_lut_index = (year - DATE_LUT_MIN_YEAR) * 12 + month - 1;
```
Comment (bharatnc) [inline src/Common/DateLUTImpl.h:1185]: `nit:` `year_lut_index` and `index` below in other places below can be `const`.

**Review by bharatnc — APPROVED** [review]

**Comment by Avogar** [comment]
[Stateless tests (amd_binary, ParallelReplicas, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86184&sha=a0495c2a29418804fc09ad525f241ce76fa53fa7&name_0=PR&name_1=Stateless+tests+%28amd_binary%2C+ParallelReplicas%2C+s3+storage%2C+parallel%29) and [Stress test (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86184&sha=a0495c2a29418804fc09ad525f241ce76fa53fa7&name_0=PR&name_1=Stress+test+%28amd_tsan%29) - https://github.com/ClickHouse/ClickHouse/issues/87467
[Bugfix validation (integration tests)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86184&sha=a0495c2a29418804fc09ad525f241ce76fa53fa7&name_0=PR&name_1=Bugfix+validation+%28integration+tests%29) - for some reason it tested updated integration test and not the new sql test
[Stress test (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86184&sha=a0495c2a29418804fc09ad525f241ce76fa53fa7&name_0=PR&name_1=Stress+test+%28arm_asan%29) - https://github.com/ClickHouse/ClickHouse/issues/83988

**Comment by clickgapai** [comment]
Hi @Avogar @bharatnc — while reviewing this PR I found the following:

- **Bug (P1):** Missing range check after `adjust_time_zone` in `parseDateTimeBestEffortImpl` causes wrong DateTime inference — https://github.com/ClickHouse/ClickHouse/issues/102601

Happy to discuss — close anything that's wrong or already addressed.
