### PR TITLE
Trying to fix some trash in zero copy replication

### LINKED ISSUE #36259: Broken part after DROP INDEX when using a s3 disk (only when using non-production "zero-copy replication")
**Describe what's wrong**

Broken part (which leads to missing data) after `DROP INDEX` when using a s3 disk.

**Does it reproduce on recent release?**

Yes. Tested on  22.4.1.1289

**How to reproduce**

Prerequesite: Create a storage policy with s3 disks named `s3`.

```
CREATE TABLE partslost
  (x String) 
ENGINE=ReplicatedMergeTree('/clickhouse/table/partslost/{shard}', '{replica}') 
ORDER BY tuple() 
SETTINGS 
   min_rows_for_wide_part = 0, 
   min_bytes_for_wide_part = 0, 
   old_parts_lifetime = 10;

INSERT INTO partslost SELECT toString(number) AS x from system.numbers LIMIT 10000;

-- not sure if this is necessary
OPTIMIZE TABLE partslost FINAL;

-- the concrete type of the index probably doesn't matter
ALTER TABLE partslost ADD INDEX idx x TYPE tokenbf_v1(285000, 3, 12345) GRANULARITY 3;

ALTER TABLE partslost MATERIALIZE INDEX idx;

-- this causes a mutation where new parts reuse (s3) files of the old part 
ALTER TABLE partslost DROP INDEX idx
```

After some time, I see this in the log file:
```
2022.04.14 08:10:06.372439 [ 226 ] {} <Error> default.partslost (ReplicatedMergeTreePartCheckThread): Part all_0_0_1_2 looks broken. Removing it and will try to fetch.
```
and the part is moved to the `detached/broken/all_0_0_1_2` directory.

After that, a `SELECT * FROM partslost` returns 0 rows.

**Expected behavior**

Part shouldn't be broken and `SELECT * FROM partslost` should still return 10000 rows.

**Additional Context**
It seems that the part `all_0_0_1_2` (which is the result of the drop-index-mutation) reuses some files of the previous `all_0_0_1_1` part. But when the old `all_0_0_1_1` is removed, then those files are deleted from S3 - which turns the new `all_0_0_1_2` into a "broken" part because files are missing.

### PR DESCRIPTION
**Pull request by alesapin**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #36259.

### CODE REVIEW

File: src/Disks/IDiskRemote.cpp [hunk 1]
```diff
@@ -270,7 +271,7 @@ std::unordered_map<String, String> IDiskRemote::getSerializedMetadata(const std:
     return metadatas;
 }
 
-void IDiskRemote::removeMetadata(const String & path, std::vector<std::string> & paths_to_remove)
+void IDiskRemote::removeMetadata(const String & path, std::unordered_map<String, std::vector<String>> & paths_to_remove)
```
Comment (KochetovNicolai) [inline src/Disks/IDiskRemote.cpp:274]: unordered map looks too complicated.
Looks like this functions only changes `paths_to_remove[path]`, why not to use std::vector as before?

File: src/Disks/IDiskRemote.cpp [hunk 2]
```diff
@@ -482,45 +483,61 @@ void IDiskRemote::replaceFile(const String & from_path, const String & to_path)
...
-void IDiskRemote::removeSharedFiles(const RemoveBatchRequest & files, bool delete_metadata_only)
+void IDiskRemote::removeSharedFiles(const RemoveBatchRequest & files, bool keep_all_batch_metadata, const NameSet & file_names_remove_metadata_only)
 {
-    std::vector<String> paths_to_remove;
+    std::unordered_map<String, std::vector<String>> paths_to_remove;
     for (const auto & file : files)
     {
         bool skip = file.if_exists && !metadata_disk->exists(file.path);
         if (!skip)
             removeMetadata(file.path, paths_to_remove);
```
Comment (KochetovNicolai) [inline src/Disks/IDiskRemote.cpp:511]: `paths_to_remove[file.path]`?

File: src/Disks/IDiskRemote.cpp [hunk 3]
```diff
@@ -482,45 +483,61 @@ void IDiskRemote::replaceFile(const String & from_path, const String & to_path)
...
     }
 
-    if (!delete_metadata_only)
-        removeFromRemoteFS(paths_to_remove);
+    if (!keep_all_batch_metadata)
```
Comment (KochetovNicolai) [inline src/Disks/IDiskRemote.cpp:514]: Prev name `delete_metadata_only` is more readable to me ...

Comment (KochetovNicolai) [reply src/Disks/IDiskRemote.cpp:514]: Maybe it should be like `keep_remote_data`?

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 4]
```diff
@@ -1530,21 +1526,13 @@ catch (...)
...
-void IMergeTreeDataPart::cleanupOldName(const String & old_part_name) const
-{
-    if (name == old_part_name)
-        return;
-
-    storage.unlockSharedData(*this, old_part_name);
-}
-
-std::optional<bool> IMergeTreeDataPart::keepSharedDataInDecoupledStorage() const
+std::pair<bool, NameSet> IMergeTreeDataPart::canRemovePart() const
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:1529]: maybe `std::optional<NameSet>`?

File: src/Disks/IDiskRemote.cpp (hunk 3 above)
Comment (alesapin) [reply src/Disks/IDiskRemote.cpp]: Done.

**Review by KochetovNicolai — COMMENTED** [review]
LGTM.
The code quality did not become significantly worse.

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp (hunk 4 above)
Comment (alesapin) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:1529]: No, I don't want it.

File: src/Disks/IDisk.h [hunk 5]
```diff
@@ -192,17 +192,18 @@ class IDisk : public Space
...
-    virtual void removeSharedFile(const String & path, bool) { removeFile(path); }
+    virtual void removeSharedFile(const String & path, bool /* keep_shared_data */) { removeFile(path); }
 
     /// Remove file or directory with all children. Use with extra caution. Throws exception if file doesn't exists.
     /// Differs from removeRecursive for S3/HDFS disks
-    /// Second bool param is a flag to remove (true) or keep (false) shared data on S3
-    virtual void removeSharedRecursive(const String & path, bool) { removeRecursive(path); }
+    /// Second bool param is a flag to remove (true) or keep (false) shared data on S3.
+    /// Third param determines which files cannot be removed even if second is true.
+    virtual void removeSharedRecursive(const String & path, bool /* keep_all_shared_data */, const NameSet & /* file_names_remove_metadata_only */) { removeRecursive(path); }
```
Comment (tavplubix) [inline src/Disks/IDisk.h:201]: Seems like the values in comment are still mixed up:
```suggestion
    /// Second bool param is a flag to remove (false) or keep (true) shared data on S3.
    /// Third param determines which files cannot be removed even if second is true.
    virtual void removeSharedRecursive(const String & path, bool /* keep_all_shared_data */, const NameSet & /* file_names_remove_metadata_only */) { removeRecursive(path); }
```

**Comment by alesapin** [comment]
Ok, one run with trash settings.

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 6]
```diff
@@ -7343,54 +7387,63 @@ void StorageReplicatedMergeTree::lockSharedData(const IMergeTreeDataPart & part,
...
+    String path_to_set_hardlinked_files;
+    NameSet hardlinks;
+
+    if (hardlinked_files.has_value() && !hardlinked_files->hardlinks_from_source_part.empty())
+    {
+        path_to_set_hardlinked_files = getZeroCopyPartPath(
+            *getSettings(), disk->getType(), getTableSharedID(),
+            hardlinked_files->source_part_name, zookeeper_path)[0];
+
+        hardlinks = hardlinked_files->hardlinks_from_source_part;
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:7403]: This path contains table's UUID, so it will not work as expected with REPLACE/MOVE PARTITION. Seems like we also need to store "table shared id" in `hardlinked_files`, `source_part_name` is not enough

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 7]
```diff
@@ -7857,14 +7920,34 @@ void StorageReplicatedMergeTree::createZeroCopyLockNode(const zkutil::ZooKeeperP
                 Coordination::Requests ops;
                 ops.emplace_back(zkutil::makeRemoveRequest(zookeeper_node, -1));
                 ops.emplace_back(zkutil::makeCreateRequest(zookeeper_node, "", mode));
+                if (!path_to_set_hardlinked_files.empty() && !hardlinked_files.empty())
+                {
+                    std::string data = boost::algorithm::join(hardlinked_files, "\n");
+                    /// List of files used to detect hardlinks. path_to_set_hardlinked_files --
+                    /// is a path to source part zero copy node. During part removal hardlinked
+                    /// files will be left for source part.
+                    ops.emplace_back(zkutil::makeSetRequest(path_to_set_hardlinked_files, data, -1));
```
[the remark this answers is not in the document]
Comment (tavplubix) [reply src/Storages/StorageReplicatedMergeTree.cpp:7929]: Sorry, of course it cannot be empty. It's not clear if we can get different sets on different replicas or not, but seems like we can not. So it's ok.

**Comment by alesapin** [comment]
Pretend to work.

**Comment by alesapin** [comment]
Ok, I think this can be merged because it doesn't make anything worse, only fixes bugs with mutations.

**Comment by alesapin** [comment]
@mergifyio update

File: src/Storages/MergeTree/MergeTreeData.h [hunk 8]
```diff
@@ -958,6 +968,8 @@ class MergeTreeData : public IStorage, public WithMutableContext
     /// Remove local files and remote files if needed
     virtual bool removeDetachedPart(DiskPtr disk, const String & path, const String & part_name, bool is_freezed);
 
+    virtual String getTableSharedID() const { return ""; }
```
Comment (tavplubix) [inline src/Storages/MergeTree/MergeTreeData.h:971]: Maybe throw `NOT_IMPLEMETED` by default?

**Review by tavplubix — APPROVED** [review]

File: src/Storages/MergeTree/MergeTreeData.h (hunk 8 above)
Comment (alesapin) [reply src/Storages/MergeTree/MergeTreeData.h:971]: No, MutateTask use it.

Comment (tavplubix) [reply src/Storages/MergeTree/MergeTreeData.h:971]: But why MutateTask use it for non-replicated MergeTree?

**Comment by alesapin** [comment]
One run with 1 second lifetime and one run with normal settings.

**Comment by alesapin** [comment]
Flaky test was unrelated to changes. It's hardening for freezed queries.
