### PR TITLE
Forbid QUALIFY clause in the old analyzer

### LINKED ISSUE #64596: Deleting using QUALIFY operator deletes all the rows in the table
Deleting using QUALIFY operator deletes all the rows in the table. The following example should delete only one row.
logs: [downloaded-logs-20240529-165631.csv](https://github.com/ClickHouse/ClickHouse/files/15487174/downloaded-logs-20240529-165631.csv)

version: 24.4.1.2088

Steps to reproduce:

```sql
drop table if exists default.test_qualify;
create table default.test_qualify (number Int64) ENGINE = MergeTree ORDER BY (number);
insert into default.test_qualify SELECT * FROM numbers(100);
select count() from default.test_qualify; -- 100
select * from default.test_qualify qualify row_number() over (order by number) = 50; -- 49
delete from default.test_qualify where number in (select number from default.test_qualify qualify row_number() over (order by number) = 50);
select count() from default.test_qualify; -- 0
```

### PR DESCRIPTION
**Pull request by novikd**
### Changelog category (leave one):

- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Forbid `QUALIFY` clause in the old analyzer. The old analyzer ignored  `QUALIFY`, so it could lead to unexpected data removal in mutations

Closes #64596.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: Normal Builds
- [ ]  Allow: Special Builds
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit e310533930c6857e6ed08bca1ba4cc7e56240cd8 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65356/e310533930c6857e6ed08bca1ba4cc7e56240cd8/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>Checks correctness of the PR's body</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/03173_forbid_qualify.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
+drop table if exists default.test_qualify;
```
Comment (nickitat) [inline tests/queries/0_stateless/03173_forbid_qualify.sql:1]: it should be test database, otherwise concurrent execution will fail

**Review by nickitat — APPROVED** [review]
