### PR TITLE
Fix order by issue in StorageMerge

### LINKED ISSUE #84666: Sorting in StorageMerge is occasionally inaccurate
### Company or project name

_No response_

### Describe what's wrong

Under certain circumstances, when max_threads is set to 1, the sorting in StorageMerge can become inaccurate with a small probability.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

https://fiddle.clickhouse.com/95b78d4f-1149-4c7f-bd04-1e6363ba0b18

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wudidapaopao**
fix https://github.com/ClickHouse/ClickHouse/issues/84666

In the [example](https://fiddle.clickhouse.com/95b78d4f-1149-4c7f-bd04-1e6363ba0b18), when a Merge Table is nested within another Merge Table, and the nested Merge Table is further nested with a Distributed Table, the current query plan is similar to the following, where an ORDER BY is missing in the nested Merge Table leading to incorrect sorting.

```
Expression (Project names)
  Sorting (Merge sorted streams for ORDER BY, without aggregation)
    ReadFromMerge
      Expression (( + ))
        Sorting (Sorting for ORDER BY)
          Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
            ReadFromMemoryStorage
      Expression (( + ))
        ReadFromMerge
          Expression (( + ))
            Sorting (Sorting for ORDER BY)
              Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
                ReadFromMemoryStorage
          Expression (( + ))
            Sorting (Sorting for ORDER BY)
              Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
                ReadFromPreparedSource (Read from NullSource)
 ```          

Therefore, for such cases—where the nested table engine is a Merge Table and the processed_stage is greater than FetchColumns—it is necessary to re-run the InterpreterSelectQueryAnalyzer to generate the query plan. And the query plan is the following, added a step of Sorting (Sorting for ORDER BY)

```
Expression (Project names)
  Sorting (Merge sorted streams for ORDER BY, without aggregation)
    ReadFromMerge
      Expression (( + ))
        Sorting (Sorting for ORDER BY)
          Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
            ReadFromMemoryStorage
      Expression (( + ))
        >>>>> Sorting (Sorting for ORDER BY) <<<<<
          ReadFromMerge
            Expression (( + ))
              Sorting (Sorting for ORDER BY)
                Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
                  ReadFromMemoryStorage
            Expression (( + ))
              Sorting (Sorting for ORDER BY)
                Expression ((Before ORDER BY + (Projection + Change column names to column identifiers)))
                  ReadFromPreparedSource (Read from NullSource)
```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix potential inaccurate sorting issues in the Merge table engine.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by tuanpach** [comment]
Could you give some description about the cause and the fix?

**Comment by wudidapaopao** [comment]
Hi @tuanpach, thanks for the reminder. I have supplemented the cause of the issue and the corresponding fix above.

File: src/Storages/StorageMerge.cpp [hunk 1]
```diff
@@ -1203,7 +1203,7 @@ ReadFromMerge::ChildPlan ReadFromMerge::createPlanForTable(
 
     QueryPlan plan;
 
-    if (processed_stage <= storage_stage)
+    if (processed_stage <= storage_stage && (!std::dynamic_pointer_cast<StorageMerge>(storage) || processed_stage == QueryProcessingStage::FetchColumns))
```
Comment (tuanpach) [inline src/Storages/StorageMerge.cpp]:
```suggestion
    /// Refer to https://github.com/ClickHouse/ClickHouse/pull/85025
    bool must_rerun_interpreter_select_query_plan
        = processed_stage > QueryProcessingStage::FetchColumns && dynamic_cast<StorageMerge *>(storage.get());
    if (processed_stage <= storage_stage && !must_rerun_interpreter_select_query_plan)
```

I think it would fit more to your explanation

> Therefore, for such cases—where the nested table engine is a Merge Table and the processed_stage is greater than FetchColumns—it is necessary to re-run the InterpreterSelectQueryAnalyzer to generate the query plan. And the query plan is the following, added a step of Sorting (Sorting for ORDER BY)

File: tests/queries/0_stateless/02014_storage_merge_order_by.sql [hunk 2]
```diff
@@ -17,6 +22,21 @@ select sum(e) from (select * from merged order by t limit 10) SETTINGS max_threa
 select sum(e) from (select * from merged order by t limit 10) SETTINGS max_threads = 10;
 select sum(e) from (select * from merged order by t limit 10) SETTINGS max_threads = 50;
 
+CREATE TABLE t1 (key Int) ENGINE=MergeTree() ORDER BY key;
```
Comment (tuanpach) [inline tests/queries/0_stateless/02014_storage_merge_order_by.sql]: Should we separate this test into a different file?
It would be easier to troubleshoot.
It is very minor, feel free to ignore this suggestion.

File: src/Storages/StorageMerge.cpp (hunk 1 above)
Comment (wudidapaopao) [reply src/Storages/StorageMerge.cpp]: @tuanpach Thanks for the feedback! Updated as suggested.

File: tests/queries/0_stateless/02014_storage_merge_order_by.sql (hunk 2 above)
Comment (wudidapaopao) [reply tests/queries/0_stateless/02014_storage_merge_order_by.sql]: Done. Thanks for the feedback!

**Review by tuanpach — APPROVED** [review]
