### PR TITLE
Fix possible dtor of nullptr in GraphiteRollupSortedAlgorithm dtor

### LINKED ISSUE #78901: StressTest Failed: use of unitialized value in ~ GraphiteRollupMergedData()
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77156&sha=7e4e53babba054d395f58dc191d71548f73eefa7&name_0=PR&name_1=Stress%20test%20%28amd_msan%29

### How to reproduce

_No response_

### Error message and/or stacktrace

==3338==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5560b674490e in DB::GraphiteRollupSortedAlgorithm::GraphiteRollupMergedData::~GraphiteRollupMergedData() ci/tmp/build/./src/Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.cpp:302:46
    #1 0x5560b674494d in DB::GraphiteRollupSortedAlgorithm::GraphiteRollupMergedData::~GraphiteRollupMergedData() ci/tmp/build/./src/Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.cpp:300:1
    #2 0x5560b3fe328c in std::__1::default_delete<DB::MergedData>::operator()[abi:ne190107](DB::MergedData*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5
    #3 0x5560b3fe328c in std::__1::unique_ptr<DB::MergedData, std::__1::default_delete<DB::MergedData>>::reset[abi:ne190107](DB::MergedData*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:292:7
    #4 0x5560b3fe328c in std::__1::unique_ptr<DB::MergedData, std::__1::default_delete<DB::MergedData>>::~unique_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:261:71
    #5 0x5560b3fe328c in DB::IMergingAlgorithmWithSharedChunks::~IMergingAlgorithmWithSharedChunks() ci/tmp/build/./src/Processors/Merges/Algorithms/IMergingAlgorithmWithSharedChunks.h:12:7
    #6 0x5560b3ff7a6e in DB::GraphiteRollupSortedAlgorithm::~GraphiteRollupSortedAlgorithm() ci/tmp/build/./src/Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.h:21:7
    #7 0x5560b3ff767c in DB::IMergingTransform<DB::GraphiteRollupSortedAlgorithm>::~IMergingTransform() ci/tmp/build/./src/Processors/Merges/IMergingTransform.h:84:7
    #8 0x5560b3ff5d4c in void std::__1::__destroy_at[abi:ne190107]<DB::GraphiteRollupSortedTransform, 0>(DB::GraphiteRollupSortedTransform*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11
    #9 0x5560b3ff5d4c in void std::__1::allocator_traits<std::__1::allocator<DB::GraphiteRollupSortedTransform>>::destroy[abi:ne190107]<DB::GraphiteRollupSortedTransform, void, 0>(std::__1::allocator<DB::GraphiteRollupSortedTransform>&, DB::GraphiteRollupSortedTransform*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5
    #10 0x5560b3ff5d4c in void std::__1::__shared_ptr_emplace<DB::GraphiteRollupSortedTransform, std::__1::allocator<DB::GraphiteRollupSortedTransform>>::__on_zero_shared_impl[abi:ne190107]<std::__1::allocator<DB::GraphiteRollupSortedTransform>, 0>() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:283:5
    #11 0x5560b3ff5d4c in std::__1::__shared_ptr_emplace<DB::GraphiteRollupSortedTransform, std::__1::allocator<DB::GraphiteRollupSortedTransform>>::__on_zero_shared() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:286:78
    #12 0x5560a992e6c7 in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #13 0x5560a992e6c7 in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #14 0x5560a992e6c7 in std::__1::shared_ptr<DB::IProcessor>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #15 0x5560a992e6c7 in void std::__1::__destroy_at[abi:ne190107]<std::__1::shared_ptr<DB::IProcessor>, 0>(std::__1::shared_ptr<DB::IProcessor>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11
    #16 0x5560a992e6c7 in void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>::destroy[abi:ne190107]<std::__1::shared_ptr<DB::IProcessor>, void, 0>(std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>&, std::__1::shared_ptr<DB::IProcessor>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5
    #17 0x5560a992e6c7 in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>::__base_destruct_at_end[abi:ne190107](std::__1::shared_ptr<DB::IProcessor>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:985:7
    #18 0x5560a992e6c7 in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>::__clear[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:979:5
    #19 0x5560a992e6c7 in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>::__destroy_vector::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:530:16
    #20 0x5560a992e6c7 in std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>::~vector[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/vector:541:67
    #21 0x5560a992e6c7 in void std::__1::__destroy_at[abi:ne190107]<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>, 0>(std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11
    #22 0x5560a992e6c7 in void std::__1::allocator_traits<std::__1::allocator<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>>::destroy[abi:ne190107]<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>, void, 0>(std::__1::allocator<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>&, std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5
    #23 0x5560a992e6c7 in void std::__1::__shared_ptr_emplace<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>, std::__1::allocator<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared_impl[abi:ne190107]<std::__1::allocator<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>, 0>() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:283:5
    #24 0x5560a992e6c7 in std::__1::__shared_ptr_emplace<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>, std::__1::allocator<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:286:78
    #25 0x5560a9941712 in std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7
    #26 0x5560a9941712 in std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25
    #27 0x5560a9941712 in std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor>>>>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17
    #28 0x5560a9941712 in DB::QueryPipeline::~QueryPipeline() ci/tmp/build/./src/QueryPipeline/QueryPipeline.cpp:54:31
    #29 0x5560a9956790 in DB::QueryPipeline::reset() ci/tmp/build/./src/QueryPipeline/QueryPipeline.cpp:700:1
    #30 0x5560a9901f26 in DB::BlockIO::onException(bool) ci/tmp/build/./src/QueryPipeline/BlockIO.cpp:65:14
    #31 0x5560b567f017 in DB::TCPHandler::runImpl() ci/tmp/build/./src/Server/TCPHandler.cpp:776:33
    #32 0x5560b56e3d9b in DB::TCPHandler::run() ci/tmp/build/./src/Server/TCPHandler.cpp:2630:9
    #33 0x5560bbd1c7bf in Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3
    #34 0x5560bbd1d6f1 in Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38
    #35 0x5560bbbf6bd4 in Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14
    #36 0x5560bbbf39cd in Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11
    #37 0x5560bbbf0550 in Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #38 0x7f681782cac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)
    #39 0x7f68178be84f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f) (BuildId: cd410b710f0f094c6832edd95931006d883af48e)

### PR DESCRIPTION
**Pull request by ahmadov**
The `MemorySanitizer` reports use-of-uninitialized-value of the aggregation pattern function in GraphiteRollupSortedAlgorithm dtor. This might happen in case `startNextGroup` called with a valid aggregation pattern function first (then `aggregate_state_created` was set to true), later without invoking any function in between (e.g. `insertRow`), the `startNextGroup` function is called again with a nullptr valued aggregation pattern function. The `aggregation_state_created` was never set to false and was never reset to false in `startNextGroup` either. So, we might have a nullptr valued aggregation pattern function and `aggregation_state_created` was set to true. This might lead to invoke the `destroy` method on the nullptr value function.
This is the rare case and probably it's false-positive report from `MemorySanitizer`.

To avoid it, we can add extra checks to verify the aggregation pattern function is not `nullptr`.

Fixes #78901

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.cpp [hunk 1]
```diff
@@ -298,8 +304,8 @@ void GraphiteRollupSortedAlgorithm::GraphiteRollupMergedData::accumulateRow(RowR
 
 GraphiteRollupSortedAlgorithm::GraphiteRollupMergedData::~GraphiteRollupMergedData()
 {
-    if (aggregate_state_created)
-        std::get<1>(current_rule)->function->destroy(place_for_aggregate_state.data());
+    if (const Graphite::AggregationPattern * aggregation_pattern = extract_aggregation_pattern_function(current_rule))
+        aggregation_pattern->function->destroy(place_for_aggregate_state.data());
```
Comment (rschu1ze) [inline src/Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.cpp:308]: Instead of rewriting to `std::optional`, will it not be sufficient to add a check here (dtor) whether `aggregation_pattern->function` is `nullptr`?

Comment (ahmadov) [reply src/Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.cpp:308]: yes, that could be one approach but it still depends on the aggregate_state_created boolean variable. I just wanted to get rid of it and replace with std::optional.

**Review by rschu1ze — APPROVED** [review]
