### PR TITLE
Fix assertion from stress test

### LINKED ISSUE #50666: Logical error: Tasks in BackgroundSchedulePool cannot throw
https://s3.amazonaws.com/clickhouse-test-reports/0/36d298ceef12daf6689ae648b7efdedf2ee83d79/stress_test__debug_.html

```
12186036:2023.06.06 16:56:37.711770 [ 1905 ] {} <Error> void DB::BackgroundSchedulePoolTaskInfo::execute(): std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in file_size: No such file or directory ["/var/lib/clickhouse/caches/s3_cache/fef/fef3081de885557e1898f3449610a52a/0"], Stack trace (when copying this message, always include the lines below):
12186037-
12186038-0. /build/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x000000001ace5ca2 in /usr/bin/clickhouse
12186039-1. /build/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x000000001ace5c6d in /usr/bin/clickhouse
12186040-2. /build/contrib/llvm-project/libcxx/src/support/runtime/stdexcept_default.ipp:33: std::runtime_error::runtime_error(String const&) @ 0x0000000037ff383d in /usr/bin/clickhouse
12186041-3. /build/contrib/llvm-project/libcxx/src/system_error.cpp:247: std::system_error::system_error(std::error_code, String const&) @ 0x0000000037ffe3f3 in /usr/bin/clickhouse
12186042-4. /build/contrib/llvm-project/libcxx/include/__filesystem/filesystem_error.h:41: std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15000](String const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000024484141 in /usr/bin/clickhouse
12186043-5. /build/contrib/llvm-project/libcxx/include/__filesystem/filesystem_error.h:90: void std::__fs::filesystem::__throw_filesystem_error[abi:v15000]<String&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x0000000037f7d947 in /usr/bin/clickhouse
12186044-6. /build/contrib/llvm-project/libcxx/src/filesystem/filesystem_common.h:175: std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<unsigned long>::report(std::error_code const&) const @ 0x0000000037f86734 in /usr/bin/clickhouse
12186045-7. /build/contrib/llvm-project/libcxx/src/filesystem/operations.cpp:1158: std::__fs::filesystem::__file_size(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000037f864f5 in /usr/bin/clickhouse
12186046-8. /build/contrib/llvm-project/libcxx/include/__filesystem/operations.h:108: std::__fs::filesystem::file_size[abi:v15000](std::__fs::filesystem::path const&) @ 0x00000000243f54d9 in /usr/bin/clickhouse
12186047-9. /build/src/Interpreters/Cache/FileSegment.cpp:753: DB::FileSegment::assertCorrectnessUnlocked(DB::FileSegmentGuard::Lock const&) const @ 0x000000002d6eacfd in /usr/bin/clickhouse
12186048-10. /build/src/Interpreters/Cache/FileSegment.cpp:731: DB::FileSegment::assertCorrectness() const @ 0x000000002d6eab35 in /usr/bin/clickhouse
12186049-11. /build/src/Interpreters/Cache/FileCache.cpp:1081: DB::FileCache::assertCacheCorrectness()::$_0::operator()(DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>) const @ 0x000000002d6c6d08 in /usr/bin/clickhouse
12186050-12. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::FileCache::assertCacheCorrectness()::$_0&>()(std::declval<DB::LockedKey&>(), std::declval<std::shared_ptr<DB::FileSegmentMetadata>>())) std::__invoke[abi:v15000]<DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>>(DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>&&) @ 0x000000002d6c6ca6 in /usr/bin/clickhouse
12186051-13. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:470: DB::IFileCachePriority::IterationResult std::__invoke_void_return_wrapper<DB::IFileCachePriority::IterationResult, false>::__call<DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>>(DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>&&) @ 0x000000002d6c6c45 in /usr/bin/clickhouse
12186052-14. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::FileCache::assertCacheCorrectness()::$_0, DB::IFileCachePriority::IterationResult (DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>)>::operator()[abi:v15000](DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>&&) @ 0x000000002d6c6c05 in /usr/bin/clickhouse
12186053-15. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: DB::IFileCachePriority::IterationResult std::__function::__policy_invoker<DB::IFileCachePriority::IterationResult (DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>)>::__call_impl<std::__function::__default_alloc_func<DB::FileCache::assertCacheCorrectness()::$_0, DB::IFileCachePriority::IterationResult (DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>)>>(std::__function::__policy_storage const*, DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>&&) @ 0x000000002d6c6bcd in /usr/bin/clickhouse
12186054-16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<DB::IFileCachePriority::IterationResult (DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>)>::operator()[abi:v15000](DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>&&) const @ 0x000000002d6f4786 in /usr/bin/clickhouse
12186055-17. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<DB::IFileCachePriority::IterationResult (DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>)>::operator()(DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>) const @ 0x000000002d6f2369 in /usr/bin/clickhouse
12186056-18. /build/src/Interpreters/Cache/LRUFileCachePriority.cpp:128: DB::LRUFileCachePriority::iterate(std::function<DB::IFileCachePriority::IterationResult (DB::LockedKey&, std::shared_ptr<DB::FileSegmentMetadata>)>&&, DB::CacheGuard::Lock const&) @ 0x000000002d6f0731 in /usr/bin/clickhouse
12186057-19. /build/src/Interpreters/Cache/FileCache.cpp:1077: DB::FileCache::assertCacheCorrectness() @ 0x000000002d6c1abb in /usr/bin/clickhouse
12186058-20. /build/src/Interpreters/Cache/FileCache.cpp:992: DB::FileCache::cleanupThreadFunc() @ 0x000000002d6c1979 in /usr/bin/clickhouse
12186059-21. /build/src/Interpreters/Cache/FileCache.cpp:127: DB::FileCache::initialize()::$_0::operator()() const @ 0x000000002d6c2af8 in /usr/bin/clickhouse
12186060-22. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::FileCache::initialize()::$_0&>()()) std::__invoke[abi:v15000]<DB::FileCache::initialize()::$_0&>(DB::FileCache::initialize()::$_0&) @ 0x000000002d6c2ad5 in /usr/bin/clickhouse
12186061-23. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<DB::FileCache::initialize()::$_0&>(DB::FileCache::initialize()::$_0&) @ 0x000000002d6c2ab5 in /usr/bin/clickhouse
12186062-24. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::FileCache::initialize()::$_0, void ()>::operator()[abi:v15000]() @ 0x000000002d6c2a95 in /usr/bin/clickhouse
12186063-25. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::FileCache::initialize()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000002d6c2a5d in /usr/bin/clickhouse
12186064-26. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x000000002446b656 in /usr/bin/clickhouse
12186065-27. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x000000002446ab55 in /usr/bin/clickhouse
12186066-28. /build/src/Core/BackgroundSchedulePool.cpp:104: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x000000002b75b5fd in /usr/bin/clickhouse
12186067-29. /build/src/Core/BackgroundSchedulePool.cpp:302: DB::BackgroundSchedulePool::threadFunction() @ 0x000000002b75e326 in /usr/bin/clickhouse
12186068-30. /build/src/Core/BackgroundSchedulePool.cpp:168: DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0::operator()() const @ 0x000000002b75f398 in /usr/bin/clickhouse
12186069-31. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&>()()) std::__invoke[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&) @ 0x000000002b75f375 in /usr/bin/clickhouse
12186070-
12186071-Cannot print extra info for Poco::Exception (version 23.5.1.1 (official build))

12186086:2023.06.06 16:56:37.831559 [ 1905 ] {} <Fatal> : Logical error: 'false && "Tasks in BackgroundSchedulePool cannot throw"'.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/50666.

### CODE REVIEW

File: src/Interpreters/Cache/FileCache.cpp [hunk 1]
```diff
@@ -988,17 +988,18 @@ void FileCache::cleanup()
...
 void FileCache::cleanupThreadFunc()
 {
-#ifndef NDEBUG
-    assertCacheCorrectness();
-#endif
-
     try
     {
+#ifdef ABORT_ON_LOGICAL_ERROR
+        assertCacheCorrectness();
```
Comment (alesapin) [inline src/Interpreters/Cache/FileCache.cpp:994]: Ok, we want to see clear exception message instead of `background task cannot throw`.

File: src/Interpreters/Cache/Metadata.cpp [hunk 2]
```diff
@@ -278,7 +278,7 @@ void CacheMetadata::doCleanup()
         try
         {
             if (fs::exists(key_prefix_directory) && fs::is_empty(key_prefix_directory))
-                fs::remove_all(key_prefix_directory);
+                fs::remove(key_prefix_directory);
```
Comment (alesapin) [inline src/Interpreters/Cache/Metadata.cpp:281]: looks like it was race condition

**Review by alesapin — APPROVED** [review]
