### PR TITLE
Fixed parseDateTime64BestEffort implementation

### LINKED ISSUE #10925: parseDateTime64BestEffort is unusable
**Describe the bug**

We're trying to use `parseDateTime64BestEffort` to parse string datetimes such as `2020-05-14T03:37:03.253184Z`, unfortunately it always raises an exception.

**How to reproduce**

* Which ClickHouse server version to use
20.3.8.53

* Which interface to use, if matters
Tested on both CLI and HTTP interfaces.

* Queries to run that lead to unexpected result

```
SELECT parseDateTime64BestEffort('2020-05-14T03:37:03.253184Z'); // DB::Exception: Function parseDateTime64BestEffort expects 2 arguments for Decimal.
SELECT parseDateTime64BestEffort('2020-05-14T03:37:03.253184Z', 9); // DB::Exception: Number of arguments for function parseDateTime64BestEffort doesn't match: passed 2, should be 1. Second argument makes sense only for DateTime and Decimal.
SELECT parseDateTimeBestEffort('2020-05-14T03:37:03.253184Z'); // OK
```

### PR DESCRIPTION
**Pull request by Enmk**
Fixed argument resolution issues.
Added tests and made sure orNull and orZero variants also work correctly.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed parseDateTime64BestEffort argument resolution bugs. #10925

closes: #10925

### CODE REVIEW

File: src/Functions/FunctionsConversion.h [hunk 1]
```diff
@@ -1126,75 +1128,85 @@ class FunctionConvertFromString : public IFunction
...
-            else if constexpr (std::is_same_v<ToDataType, DataTypeDecimal<Decimal64>>)
-                res = createDecimal<DataTypeDecimal>(18, scale);
-            else if constexpr (std::is_same_v<ToDataType, DataTypeDecimal<Decimal128>>)
-                res = createDecimal<DataTypeDecimal>(38, scale);
+                if constexpr (std::is_same_v<ToDataType, DataTypeDecimal<Decimal32>>)
+                    res = createDecimal<DataTypeDecimal>(9, scale);
+                else if constexpr (std::is_same_v<ToDataType, DataTypeDecimal<Decimal64>>)
+                    res = createDecimal<DataTypeDecimal>(18, scale);
+                else if constexpr (std::is_same_v<ToDataType, DataTypeDecimal<Decimal128>>)
+                    res = createDecimal<DataTypeDecimal>(38, scale);
```
Comment (vitlibar) [inline src/Functions/FunctionsConversion.h:1202]: Why 38? A comment would be useful, I suppose.

File: src/Functions/FunctionsConversion.h [hunk 2]
```diff
@@ -1126,75 +1128,85 @@ class FunctionConvertFromString : public IFunction
...
+
+            if (!isStringOrFixedString(arguments[0].type))
             {
-                if (!isInteger(arguments[1].type))
-                    throw Exception("Illegal type " + arguments[1].type->getName() + " of 2nd argument of function " + getName(),
-                        ErrorCodes::ILLEGAL_TYPE_OF_ARGUMENT);
-                if (!arguments[1].column)
-                    throw Exception("Second argument for function " + getName() + " must be constant", ErrorCodes::ILLEGAL_COLUMN);
+                if (this->getName().find("OrZero") != std::string::npos ||
+                    this->getName().find("OrNull") != std::string::npos)
```
Comment (vitlibar) [inline src/Functions/FunctionsConversion.h:1158]: `endsWith()` seems to be more suitable here.

File: tests/queries/0_stateless/01281_parseDateTime64BestEffort.sql [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+SELECT 'orZero';
+SELECT parseDateTime64BestEffortOrZero('2020-05-14T03:37:03.253184Z', 3, 'UTC');
+SELECT parseDateTime64BestEffortOrZero('bar', 3, 'UTC');
+
+SELECT 'non-const';
+SELECT parseDateTime64BestEffort(materialize('2020-05-14T03:37:03.253184Z'), 3, 'UTC');
+
+SELECT 'Timezones';
+SELECT parseDateTime64BestEffort('2020-05-14T03:37:03.253184Z', 3, 'UTC');
+SELECT parseDateTime64BestEffort('2020-05-14T03:37:03.253184Z', 3, 'Europe/Minsk');
```
Comment (vitlibar) [inline tests/queries/0_stateless/01281_parseDateTime64BestEffort.sql:28]: A little offtopic. We have the function `parseDateTime64BestEffort()`, but we don't have function `parseDateTime64()`, right? I wonder how we came to that.

File: src/IO/parseDateTimeBestEffort.cpp [hunk 4]
```diff
@@ -562,8 +562,17 @@ ReturnType parseDateTime64BestEffortImpl(DateTime64 & res, UInt32 scale, ReadBuf
 {
     time_t whole;
     DateTimeSubsecondPart subsecond = {0, 0}; // needs to be explicitly initialized sine it could be missing from input string
-    if (!parseDateTimeBestEffortImpl<bool>(whole, in, local_time_zone, utc_time_zone, &subsecond))
-        return ReturnType(false);
+
+    if constexpr (std::is_same_v<ReturnType, bool>)
+    {
+        if (!parseDateTimeBestEffortImpl<bool>(whole, in, local_time_zone, utc_time_zone, &subsecond))
+            return ReturnType(false);
```
Comment (vitlibar) [inline src/IO/parseDateTimeBestEffort.cpp:569]: Isn't simple `return false` enough here?

File: tests/queries/0_stateless/01281_parseDateTime64BestEffort.sql (hunk 3 above)
Comment (Enmk) [reply tests/queries/0_stateless/01281_parseDateTime64BestEffort.sql:28]: Perfectly aligned with DateTime case: there is `parseDateTimeBestEffort`, but no `parseDateTime` function. IIRC, 'non-best-effort' parsing is done on casting/building DateTime/DateTime64 values from string explicitly.

File: src/IO/parseDateTimeBestEffort.cpp (hunk 4 above)
Comment (Enmk) [reply src/IO/parseDateTimeBestEffort.cpp:569]: Yep, nothing fancy required. That is a bool-specialization, we want just simple yes/no answer and there is no point in trying to parse sub-second part when parsing the main part has just failed.

Unfortunately, I couldn't find a more elegant way to do that without splitting into two compile-time branches.

File: src/Functions/FunctionsConversion.h (hunk 2 above)
Comment (Enmk) [reply src/Functions/FunctionsConversion.h:1158]: Yes, but I've just tossed that under an else-branch of `if constexpr`, so that piece is mostly as it was before.

IMO that exact piece (and the whole approach of how compile-time branching based on function return type is done) should be re-thought and re-designed, this piece is not the worst, but it is becoming a mess.

**Review by vitlibar — APPROVED** [review]
