### PR TITLE
Fix SQL security access checks with analyzer

### LINKED ISSUE #63777: Improving SQL DEFINERS for MV
Currently if you have a the following tables:

```
DROP TABLE events_mv;
DROP TABLE materialized_events;
DROP TABLE session_events;

CREATE TABLE session_events(
    clientId UUID,
    sessionId UUID,
    pageId UUID,
    timestamp DateTime,
    type String
) ORDER BY (timestamp);

CREATE MATERIALIZED VIEW events_mv
TO materialized_events
AS SELECT
    clientId,
    sessionId,
    pageId,
    timestamp,
    type
FROM session_events;

CREATE TABLE materialized_events(
    clientId UUID,
    sessionId UUID,
    pageId UUID,
    timestamp DateTime,
    type String
) ORDER BY (timestamp);
```

The minimum set of permission you currently need for a user to insert into the table:

```
DROP USER user_1;
CREATE USER user_1 IDENTIFIED WITH sha256_password BY 'My_password123@';
GRANT INSERT ON default.session_events TO user_1;
GRANT SELECT ON default.session_events TO user_1;
```

If you don't specify 

`GRANT SELECT ON default.session_events TO user_1;`

The insert will fail because of missing permission. 

The permission should be covered by the definer. Ideally the only grant that should be needed would be:

`GRANT INSERT ON default.session_events TO user_1;`

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
This fix will use a proper redefined context with the correct definer for each individual view in the query pipeline 

Closes https://github.com/ClickHouse/ClickHouse/issues/63777

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit dd6c763492d032738c922cff19c8687e05c2f542 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64079/dd6c763492d032738c922cff19c8687e05c2f542/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by vitlibar — APPROVED** [review]

File: tests/queries/0_stateless/02884_create_view_with_sql_security_option.sh [hunk 1]
```diff
@@ -192,6 +192,44 @@ ${CLICKHOUSE_CLIENT} --user $user1 --query "
...
+
+CREATE MATERIALIZED VIEW $db.mv2 TO $db.destination2
+AS SELECT *
+FROM $db.destination1;
+
+GRANT INSERT ON $db.source TO $user2;
+EOF
+
+${CLICKHOUSE_CLIENT} --user $user2 --query "INSERT INTO source SELECT * FROM generateRandom() LIMIT 100"
+${CLICKHOUSE_CLIENT} --query "SELECT count() FROM destination2"
```
Comment (vitlibar) [inline tests/queries/0_stateless/02884_create_view_with_sql_security_option.sh:231]: Please check `destination1` too

File: tests/queries/0_stateless/02884_create_view_with_sql_security_option.sh [hunk 2]
```diff
@@ -192,6 +192,44 @@ ${CLICKHOUSE_CLIENT} --user $user1 --query "
...
+ALTER TABLE $db.mv1 MODIFY DEFINER=default SQL SECURITY DEFINER;
+
+CREATE MATERIALIZED VIEW $db.mv2 TO $db.destination2
+AS SELECT *
+FROM $db.destination1;
+
+GRANT INSERT ON $db.source TO $user2;
+EOF
+
+${CLICKHOUSE_CLIENT} --user $user2 --query "INSERT INTO source SELECT * FROM generateRandom() LIMIT 100"
```
Comment (vitlibar) [inline tests/queries/0_stateless/02884_create_view_with_sql_security_option.sh:230]: You're only checking that `GRANT INSERT ON $db.source TO $user2` is enough in this test, but you aren't checking that it's required. Probably it's better to execute first this `INSERT` without any grants and get an exception.
