### PR TITLE
Throw exception when parsing illegal string as float if precise_float_parsing is true

### LINKED ISSUE #55858: Different behavior when parsing string to float with precise_float_parsing true/false
> You have to provide the following information whenever possible.

cc @zvonand

Below results could be reproduced in CH master version 
``` sql 
 :) set precise_float_parsing = true;

SET precise_float_parsing = 1

Query id: 565dc036-c190-4317-bb46-9d921800c6b8

Ok.

0 rows in set. Elapsed: 0.001 sec. 

 :) select cast('2012-12-11' as Float64) 

SELECT CAST('2012-12-11', 'Float64')

Query id: 6a707d60-51fd-4324-8f1c-bd78cdb92650

┌─CAST('2012-12-11', 'Float64')─┐
│                          2012 │
└───────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

 :) set precise_float_parsing = false;

SET precise_float_parsing = 0

Query id: e74b7414-a217-4ac7-9acb-87ecdba79d52

Ok.

0 rows in set. Elapsed: 0.001 sec. 

 :) select cast('2012-12-11' as Float64) 

SELECT CAST('2012-12-11', 'Float64')

Query id: 0beca197-0543-44bf-9e52-36869f5fd354


0 rows in set. Elapsed: 0.002 sec. 

```

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Throw exception when parsing illegal string as float if precise_float_parsing is true. Close https://github.com/ClickHouse/ClickHouse/issues/55858

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 6e3f35fc942b332c1506668edc2fc5be1242a88b with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55861/6e3f35fc942b332c1506668edc2fc5be1242a88b/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6585228334">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55861/6e3f35fc942b332c1506668edc2fc5be1242a88b/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: tests/queries/0_stateless/02900_issue_55858.sql [hunk 1]
```diff
@@ -0,0 +1,10 @@
+set precise_float_parsing = 1;
+
+select cast('2023-01-01' as Float64); -- { serverError 6 }
```
[the remark this answers is not in the document]
Comment (taiyang-li) [reply tests/queries/0_stateless/02900_issue_55858.sql:3]: It is actually `6 - CANNOT_PARSE_TEXT`
```
SELECT CAST('2023-01-01', 'Float64')

Query id: 38715fd9-d602-4556-9dc6-496b7803b955


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 23.10.1):
Code: 6. DB::Exception: Received from localhost:9001. DB::Exception: Cannot parse string '2023-01-01' as Float64: syntax error at position 4 (parsed just '2023'). Note: there are toFloat64OrZero and toFloat64OrNull functions, which returns zero/NULL instead of throwing exception.: While processing CAST('2023-01-01', 'Float64'). (CANNOT_PARSE_TEXT)

```

**Comment by taiyang-li** [comment]
Failed uts seems not related to this pr. https://s3.amazonaws.com/clickhouse-test-reports/55861/bb458c9fe1c64e1419f082d66cfa62abf60e584d/integration_tests__release__[2_4].html .  They are also failed in other prs.

File: src/IO/readFloatText.h [hunk 2]
```diff
@@ -148,11 +148,11 @@ ReturnType readFloatTextPreciseImpl(T & x, ReadBuffer & buf)
...
 
     static constexpr bool throw_exception = std::is_same_v<ReturnType, void>;
-
-    /// Fast path (avoid copying) if the buffer have at least MAX_LENGTH bytes.
     static constexpr int MAX_LENGTH = 316;
+    ReadBufferFromMemory * buf_from_memory = dynamic_cast<ReadBufferFromMemory *>(&buf);
 
-    if (likely(!buf.eof() && buf.position() + MAX_LENGTH <= buf.buffer().end()))
+    /// Fast path (avoid copying) if the buffer have at least MAX_LENGTH bytes or buf is ReadBufferFromMemory
+    if (likely(!buf.eof() && (buf_from_memory || buf.position() + MAX_LENGTH <= buf.buffer().end())))
```
Comment (Avogar) [inline src/IO/readFloatText.h:155]: I don't think it's the right way to fix it. If buf is not `ReadBufferFromMemory`, we will still have this bug. The actual problem is in slow path here:
https://github.com/ClickHouse/ClickHouse/blob/5923e1b1167b1bf755654e3dcb46c13106ec164b/src/IO/readFloatText.h#L241-L256

We don't check that data data copied to `tmp_buf` was used during float parsing. We can change ckech on line 250:
```
        if (unlikely(res.ec != std::errc()) || res.ptr - tmp_buf != num_copied_chars)
            ...
```

Comment (taiyang-li) [reply src/IO/readFloatText.h:155]: @Avogar If `readFloatTextPrecise` guarantees that `ReadBuffer & in` is all read after parsing, then you solution is right. Otherwise, we should use PeekableReadBuffer to mark the position before parsing, which is too heavy for current function. So I fix it using `ReadBufferFromMemory`(notice that `readFloatTextPreciseImpl` is only used in ConvertThroughParsing::execute, and all ReadBuffer passed to `readFloatTextPreciseImpl` is `ReadBufferFromMemory`)

Comment (Avogar) [reply src/IO/readFloatText.h]: > Otherwise, we should use PeekableReadBuffer to mark the position where the actual float parsing is finished, and rollback to it if not all chars copied to buffer are consumed

Ideally yes, we should rollback to the position when actual float parsing is finished, but right now we can read from the buffer more data than was used for float parsing and this extra data will be just silently ignored, like in example `2020-01-01` part `-01-01` will be read and just ignored, so it  won't be available after  `readFloatTextPreciseImpl` is finished. So I think we better throw an exception in this case instead of silently consuming extra data

Comment (taiyang-li) [reply src/IO/readFloatText.h]: But current checking of whether there are extra data after parsing is in `ConvertThroughParsing::isAllRead`.  If we throw exception in `readFloatTextPreciseImpl`, it will break the rules.

Comment (Avogar) [reply src/IO/readFloatText.h]: > it will break the rules

What rules? `readFloatTextPreciseImpl ` should parse correct float value from read data or throw an exception, it should not silently read some extra data without an exception.
The only think that will change is where we throw and exception and an exception message. And we can just improve exception message in `readFloatTextPreciseImpl` (make it like: `Cannot parse flloating point value here: <data_copied_to_tmp_buffer>`).

Comment (Avogar) [reply src/IO/readFloatText.h]: But we don't throw an exception in `ConvertThroughParsing::isAllRead` if `readFloatTextPreciseImpl` read extra bytes in tmp buffer in slow path. If we have `2020-01-01` and execute slow path in `readFloatTextPreciseImpl` we still get no excaption and silently ignored data

Comment (Avogar) [reply src/IO/readFloatText.h]: In slow path there is no way we can rely on `ConvertThroughParsing::isAllRead` because we can read extra data from the buffer that won't be used in float parsing. And `readFloatTextPreciseImpl ` should be responsible to throw an exception in this case, because we can't do it in any other place

Comment (Avogar) [reply src/IO/readFloatText.h]: And we should think about `readFloatTextPreciseImpl` in isolation as a function that parses float from the data and throw an exception if parsing goes wrong. Reading extra bytes from buffer and ignoring them is something wrong and we should throw an exception

Comment (Avogar) [reply src/IO/readFloatText.h]: So, I suggest keep check for `ReadBufferFromMemory` with a comment that this is an optimization to avoid copying data, but also add a check with an exception for slow path

Comment (taiyang-li) [reply src/IO/readFloatText.h]: Get it! I'll update codes and pls review later.

**Review by Avogar — APPROVED** [review]
