### PR TITLE
Fixed an incorrect std::exception for MVs with bad selects

### LINKED ISSUE #82889: Logical error: std::out_of_range on Materialized view with bad select
### Describe the bug

Easy to reproduce. Happens since v25.6, maybe related to https://github.com/ClickHouse/ClickHouse/issues/82784 ?

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/0d23bba0-db4d-468c-9ebb-db5fc41f417c

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'std::exception. Code: 1001, type: std::out_of_range, e.what() = map::at:  key not found (version 25.7.1.1588 (official build)), Stack trace:

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::logic_error::logic_error(char const*) @ 0x0000000024c1b9b4
1. contrib/llvm-project/libcxx/include/stdexcept:162: std::out_of_range::out_of_range[abi:se190107](char const*) @ 0x000000000c77d889
2. contrib/llvm-project/libcxx/include/stdexcept:248: std::__throw_out_of_range[abi:se190107](char const*) @ 0x000000000c77d83f
3. contrib/llvm-project/libcxx/include/map:1564: ? @ 0x000000001a0d2bff
4. src/Interpreters/InsertDependenciesBuilder.cpp:866: DB::InsertDependenciesBuilder::observePath(DB::InsertDependenciesBuilder::DependencyPath const&) @ 0x000000001a0cae4c
5. src/Interpreters/InsertDependenciesBuilder.cpp:988: void std::__function::__policy_invoker<void (DB::InsertDependenciesBuilder::StorageIDPrivate)>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::InsertDependenciesBuilder::collectAllDependencies()::$_0, void (DB::InsertDependenciesBuilder::StorageIDPrivate)>>(std::__function::__policy_storage const*, DB::InsertDependenciesBuilder::StorageIDPrivate&&) @ 0x000000001a0d1365
6. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a0d1666
7. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a0d184b
8. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a0d1666
9. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001a0c6773
10. src/Interpreters/InsertDependenciesBuilder.cpp:721: DB::InsertDependenciesBuilder::InsertDependenciesBuilder(std::shared_ptr<DB::IStorage>, std::shared_ptr<DB::IAST>, DB::Block, bool, bool, std::shared_ptr<DB::Context const>) @ 0x000000001a0c6342
11. src/Interpreters/InsertDependenciesBuilder.h:85: std::shared_ptr<DB::InsertDependenciesBuilder const> DB::InsertDependenciesBuilder::create<std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>>(std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&)::MakeSharedEnabler::MakeSharedEnabler(std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&) @ 0x000000001a0c1b98
12. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: std::shared_ptr<std::shared_ptr<DB::InsertDependenciesBuilder const> DB::InsertDependenciesBuilder::create<std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>>(std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&)::MakeSharedEnabler const> std::allocate_shared[abi:se190107]<std::shared_ptr<DB::InsertDependenciesBuilder const> DB::InsertDependenciesBuilder::create<std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>>(std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&)::MakeSharedEnabler const, std::allocator<std::shared_ptr<DB::InsertDependenciesBuilder const> DB::InsertDependenciesBuilder::create<std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>>(std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&)::MakeSharedEnabler>, std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>, 0>(std::allocator<std::shared_ptr<DB::InsertDependenciesBuilder const> DB::InsertDependenciesBuilder::create<std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>>(std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&)::MakeSharedEnabler> const&, std::shared_ptr<DB::IStorage>&, std::shared_ptr<DB::IAST>&, DB::Block&, bool const&, bool&, std::shared_ptr<DB::Context const>&&) @ 0x000000001a0c18f5
13. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:851: DB::InterpreterInsertQuery::buildInsertPipeline(DB::ASTInsertQuery&, std::shared_ptr<DB::IStorage>) @ 0x000000001a0bd406
14. src/Interpreters/InterpreterInsertQuery.cpp:761: DB::InterpreterInsertQuery::execute() @ 0x000000001a0bea24
15. src/Interpreters/executeQuery.cpp:1561: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001a3f75a3
16. src/Interpreters/executeQuery.cpp:1769: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001a3f2d7b
17. src/Server/TCPHandler.cpp:722: DB::TCPHandler::runImpl() @ 0x000000001c1b5372
18. src/Server/TCPHandler.cpp:2729: DB::TCPHandler::run() @ 0x000000001c1ce9a4
19. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000204a13a7
20. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000204a18a5
21. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000020449d9f
22. base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000020447951
23. start_thread @ 0x00000000000a2ef1
24. __clone3 @ 0x000000000013445c
```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
There was an incorrect dependency check for the INSERT with MVs that have malformed selects and the user might have received an obscure `std::exception` instead of a meaningful error with a clear explanation. This is now fixed. This fixes: https://github.com/ClickHouse/ClickHouse/issues/82889

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Interpreters/InsertDependenciesBuilder.h [hunk 1]
```diff
@@ -43,13 +43,32 @@ class InsertDependenciesBuilder : public std::enable_shared_from_this<InsertDepe
...
+        /// with the operator== then it will not work correctly.
+        /// Take a look at the comment for operator== in the StorageID itself.
+        bool contains(const StorageIDPrivate & id) const
+        {
+            for (const auto & x : visited)
+                if (x == id)
+                    return true;
+            return false;
+        }
+        void erase(const StorageIDPrivate & id) { visited.erase(id); }
```
Comment (nikitamikhaylov) [inline src/Interpreters/InsertDependenciesBuilder.h]: Hmm, it seems this one is also not consistent with contains and also uses `operator<`. Should we just replace everything with std::vector? Or replace with std::unordered_set and calculate a hash of StorageID?

Comment (nikitamikhaylov) [reply src/Interpreters/InsertDependenciesBuilder.h]: Let's just use std::unoredered_set.

**Review by CheSema — APPROVED** [review]

**Review by CheSema — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
`Build (fuzzers)`- https://github.com/ClickHouse/ClickHouse/issues/83272
