### PR TITLE
Fix performance with large tuples

### LINKED ISSUE #12534: Bad performance of IN with tuples interpreted as functions.
```
select count() from numbers(10) where number in tuple(1, 2, 3, 4, 5) settings max_temporary_columns = 3

Received exception from server (version 20.7.1):
Code: 165. DB::Exception: Received from localhost:9000. DB::Exception: Too many temporary columns: _dummy, 1, 2, 3. Maximum: 3. 
```

Workaround: Avoid function in tuple.
```select count() from numbers(10) where number in (1, 2, 3, 4, 5) settings max_temporary_columns = 3```

### PR DESCRIPTION
**Pull request by CurtizJ**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix performance with large tuples, which are interpreted as functions in `IN` section. The case when user write `WHERE x IN tuple(1, 2, ...)` instead of `WHERE x IN (1, 2, ...)` for some obscure reason.

Fixes #12534.

### CODE REVIEW

**Comment by CurtizJ** [comment]
For tuples-functions I've returned old code, when all tuples were created from AST.

File: src/Interpreters/ActionsVisitor.cpp [hunk 1]
```diff
@@ -64,6 +64,16 @@ static NamesAndTypesList::iterator findColumn(const String & name, NamesAndTypes
                         [&](const NamesAndTypesList::value_type & val) { return val.name == name; });
 }
 
+static size_t getTypeDepth(const DataTypePtr & type)
```
Comment (alexey-milovidov) [inline src/Interpreters/ActionsVisitor.cpp:67]: There is no check for stack overflow neither the comment about why stack overflow does not happen.

I will add a check.

**Review by alexey-milovidov — APPROVED** [review]
