### PR TITLE
Fix text index with empty arrays

### LINKED ISSUE #93432: Text index: EOF read with empty array
### Company or project name

_No response_

### Describe what's wrong

Constructing a text index over an array, and then writing an empty array, produces a read-after-EOF error.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Fiddle: https://fiddle.clickhouse.com/0dc33bc4-2e5b-456c-bcf8-4d79214c4cb1
```
SET enable_full_text_index;

CREATE TABLE t
(
  c Array(String),
  INDEX i c TYPE text(tokenizer=array)
)
ENGINE=MergeTree() ORDER BY tuple()
AS SELECT [];

-- The EOF read occurs during index analysis
EXPLAIN indexes = 1
SELECT * from t
WHERE hasAllTokens(c, 'abc')
FORMAT NULL;
```

### Expected behavior

I expect the query to return an empty rowset successfully.

### Error message and/or stacktrace

```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000163a0f6a
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000de0034e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000ddffd40
3. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000de149b6
4. DB::throwReadAfterEOF() @ 0x00000000164b0f0f
5. DB::MergeTreeIndexGranuleText::deserializeBinaryWithMultipleStreams(std::map<DB::MergeTreeIndexSubstream::Type, DB::MergeTreeReaderStream*, std::less<DB::MergeTreeIndexSubstream::Type>, std::allocator<std::pair<DB::MergeTreeIndexSubstream::Type const, DB::MergeTreeReaderStream*>>>&, DB::MergeTreeIndexDeserializationState&) @ 0x000000001c8087ea
6. DB::MergeTreeIndexReader::read(unsigned long, DB::IMergeTreeIndexCondition const*, std::shared_ptr<DB::IMergeTreeIndexGranule>&) @ 0x000000001c7ff856
7. DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex(std::shared_ptr<DB::IMergeTreeIndex const>, std::shared_ptr<DB::IMergeTreeIndexCondition>, std::optional<DB::KeyCondition> const&, std::shared_ptr<DB::IMergeTreeDataPart const>, DB::MarkRanges const&, DB::RangesInDataPartReadHints const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, DB::VectorSimilarityIndexCache*, bool, boost::dynamic_bitset<unsigned long, std::allocator<unsigned long>>&, std::shared_ptr<Poco::Logger>) @ 0x000000001c7c66ae
8. DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(DB::RangesInDataParts, std::shared_ptr<DB::StorageInMemoryMetadata const>, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const> const&, DB::KeyCondition const&, std::optional<DB::KeyCondition> const&, std::optional<DB::KeyCondition> const&, std::optional<DB::KeyCondition> const&, DB::UsefulSkipIndexes const&, std::optional<DB::TopKFilterInfo> const&, DB::MergeTreeReaderSettings const&, std::shared_ptr<Poco::Logger>, unsigned long, std::vector<DB::ReadFromMergeTree::IndexStat, std::allocator<DB::ReadFromMergeTree::IndexStat>>&, bool, bool, bool, bool, bool, DB::ReadFromMergeTree::AnalysisResult&)::$_1::operator()(unsigned long) const @ 0x000000001c7c10c5
9. DB::MergeTreeDataSelectExecutor::filterPartsByPrimaryKeyAndSkipIndexes(DB::RangesInDataParts, std::shared_ptr<DB::StorageInMemoryMetadata const>, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const> const&, DB::KeyCondition const&, std::optional<DB::KeyCondition> const&, std::optional<DB::KeyCondition> const&, std::optional<DB::KeyCondition> const&, DB::UsefulSkipIndexes const&, std::optional<DB::TopKFilterInfo> const&, DB::MergeTreeReaderSettings const&, std::shared_ptr<Poco::Logger>, unsigned long, std::vector<DB::ReadFromMergeTree::IndexStat, std::allocator<DB::ReadFromMergeTree::IndexStat>>&, bool, bool, bool, bool, bool, DB::ReadFromMergeTree::AnalysisResult&) @ 0x000000001c7b5cfb
10. DB::ReadFromMergeTree::selectRangesToRead(DB::RangesInDataParts const&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::optional<DB::VectorSearchParameters> const&, std::optional<DB::TopKFilterInfo> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::Context const>, unsigned long, std::shared_ptr<std::unordered_map<String, long, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, long>>> const>, DB::MergeTreeData const&, std::shared_ptr<DB::MergeTreeSettings const> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<Poco::Logger>, std::optional<DB::ReadFromMergeTree::Indexes>&, bool, bool, bool) @ 0x000000001d636754
11. DB::ReadFromMergeTree::selectRangesToRead(bool) const @ 0x000000001d634348
12. DB::ReadFromMergeTree::describeIndexes(DB::IQueryPlanStep::FormatSettings&) const @ 0x000000001d65279f
13. DB::explainStep(DB::IQueryPlanStep&, DB::IQueryPlanStep::FormatSettings&, DB::ExplainPlanOptions const&, unsigned long) @ 0x000000001d5f1fa4
14. DB::QueryPlan::explainPlan(DB::WriteBuffer&, DB::ExplainPlanOptions const&, unsigned long, unsigned long) const @ 0x000000001d5f2ea4
15. DB::InterpreterExplainQuery::executeImpl() @ 0x000000001b2b78a7
16. DB::InterpreterExplainQuery::execute() @ 0x000000001b2b4b17
17. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001b751f84
18. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001b74c490
19. DB::TCPHandler::runImpl() @ 0x000000001cf83be8
20. DB::TCPHandler::run() @ 0x000000001cfa5f24
21. Poco::Net::TCPServerConnection::start() @ 0x00000000223ba5c7
22. Poco::Net::TCPServerDispatcher::run() @ 0x00000000223baab1
23. Poco::PooledThread::run() @ 0x000000002237a71c
24. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000022378bcf
25. ? @ 0x0000000000094ac3
26. clone @ 0x0000000000125a74
```

### Additional context

The error does **not** occur with `SETTINGS use_skip_index_on_data_read`, only the old pre-reading filtering.

In a more realistic production environment I saw a different error:
```
Code: 33. DB::Exception: Received from igm-qpr-dbtest10:9000. DB::Exception: Too many marks in file ./store/117/11763a30-65d4-4bc5-bab8-ecbf62ebdce9/20251005_276_276_0/skp_idx_ix_text_something.cmrk2, marks expected 1 (bytes size 24). (CANNOT_READ_ALL_DATA)
```
That part's `.cmrk2` file looks like this:
```
xxd 20251005_276_276_0/skp_idx_ix_text_something.cmrk2
00000000: c985 0eb6 9c1a 9840 ce79 54df 34fb 0481  .......@.yT.4...
00000010: 9022 0000 0020 0100 0028 b52f fd60 2000  ."... ...(./.` .
00000020: 7d00 0020 0000 0100 0300 f59d 1400 0a96  }.. ............
00000030: 0116                                     ..
```
Contrast with a different part that succeeds:
```
xxd 20251004_275_275_0/skp_idx_ix_text_something.cmrk2
00000000: 7cc3 f4b0 5b3f 752b 47e6 06d4 0711 528e  |...[?u+G.....R.
00000010: 9022 0000 0018 0000 0028 b52f fd20 1885  .".......(./. ..
00000020: 0000 5000 0001 0000 0000 0000 0001 0032  ..P............2
00000030: c002                                     ..
```
(I gave up trying to decompress these by hand)

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed text index analysis on array columns when the index contains no tokens (all arrays are empty or all tokens are skipped by the tokenizer).

Fixes #93432.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeIndexText.cpp [hunk 1]
```diff
@@ -1022,8 +1022,12 @@ void MergeTreeIndexTextGranuleBuilder::addDocument(std::string_view document)
...
             return false;
         });
+}
 
-    ++num_processed_documents;
+void MergeTreeIndexTextGranuleBuilder::incrementCurrentRow()
+{
+    is_empty = false;
+    ++current_row;
 }
```
Comment (Ergus) [inline src/Storages/MergeTree/MergeTreeIndexText.cpp:1031]: A question here. These two are initialized together when resetting. So why use two variables instead of just `current_row == 0`?

File: tests/queries/0_stateless/03783_text_index_empty_array.sql [hunk 2]
```diff
@@ -0,0 +1,15 @@
+SET enable_full_text_index = 1;
```
Comment (Ergus) [inline tests/queries/0_stateless/03783_text_index_empty_array.sql:3]: Please add a comment referencing the issue to remember in the future.

**Review by Ergus — COMMENTED** [review]
LGTM, but I added a question

File: src/Storages/MergeTree/MergeTreeIndexText.cpp (hunk 1 above)
Comment (CurtizJ) [reply src/Storages/MergeTree/MergeTreeIndexText.cpp:1031]: We can start not from the 0 row during materialization of the index (https://github.com/ClickHouse/ClickHouse/blob/7efa64226575f96fbc1e56d5bb95480fd693e22d/src/Storages/MergeTree/TextIndexUtils.cpp#L185). So, it will be slightly incorrect.

**Review by Ergus — APPROVED** [review]
