### PR TITLE
Fix crash with optimize_rewrite_array_exists_to_has

### LINKED ISSUE #71382: Explain syntax SEGV
**Describe the bug**
A SEGV may happen with `SET optimize_rewrite_array_exists_to_has = 1` and Explain syntax.

**How to reproduce**
It may take a few tries to reproduce. Run:
```sql
CREATE TABLE t0 (c0 Int) ENGINE = Memory();
SET optimize_rewrite_array_exists_to_has = 1;
EXPLAIN SYNTAX SELECT 1 FROM t0 JOIN t0 y ON (SELECT 1) JOIN t0 z ON 1;
```

UBSAN output:
```
contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702:23: runtime error: member call on misaligned address 0x6567617373656d for type 'std::__shared_weak_count', which requires 8 byte alignment
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash with optimize_rewrite_array_exists_to_has

Closes https://github.com/ClickHouse/ClickHouse/issues/71382

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 389fdd80d36b5073698b87b7a7d24dcc4c6560bf with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71432/389fdd80d36b5073698b87b7a7d24dcc4c6560bf/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71402/5c69cf3205c77bbb2dcf8a5d52539679507c86fe/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp [hunk 1]
```diff
@@ -63,7 +63,7 @@ bool ExecuteScalarSubqueriesMatcher::needChildVisit(ASTPtr & node, const ASTPtr
     if (node->as<ASTSelectQuery>())
     {
         /// Do not go to FROM, JOIN, UNION.
-        if (child->as<ASTTableExpression>() || child->as<ASTSelectQuery>())
+        if (child->as<ASTTableExpression>() || child->as<ASTSelectQuery>() || child->as<ASTTablesInSelectQuery>())
```
Comment (Algunenano) [inline src/Interpreters/ExecuteScalarSubqueriesVisitor.cpp:66]: Fix 1: ExecuteScalarSubqueriesVisitor was visiting the join elements of the query (contrary to the comment above) and altering the children of ASTTableExpression, but not the named pointers (using_expression_list, on_expression). This only worked because then we ignored children and kept using the named pointers.

File: src/Interpreters/RewriteArrayExistsFunctionVisitor.cpp [hunk 2]
```diff
@@ -20,21 +20,21 @@ void RewriteArrayExistsFunctionMatcher::visit(ASTPtr & ast, Data & data)
         if (join->using_expression_list)
         {
             auto * it = std::find(join->children.begin(), join->children.end(), join->using_expression_list);
+            if (it == join->children.end())
+                throw Exception(ErrorCodes::LOGICAL_ERROR, "Could not find join->using_expression_list in '{}'", join->formatForLogging());
 
             visit(join->using_expression_list, data);
-
-            if (it && *it != join->using_expression_list)
```
Comment (Algunenano) [inline src/Interpreters/RewriteArrayExistsFunctionVisitor.cpp:26]: Fix 2. It shouldn't have been `it && ...` but `it != join->children.end() && ...`.

In any case, it's much better to assert your expectations (which is that the named pointer must be a child) instead of adding unexplained `if`'s

File: tests/queries/0_stateless/03261_optimize_rewrite_array_exists_to_has_crash.sql [hunk 3]
```diff
@@ -0,0 +1,10 @@
+-- https://github.com/ClickHouse/ClickHouse/issues/71382
+DROP TABLE IF EXISTS rewrite;
+CREATE TABLE rewrite (c0 Int) ENGINE = Memory();
+SELECT 1
+FROM rewrite
+INNER JOIN rewrite AS y ON (
+    SELECT 1
+)
+INNER JOIN rewrite AS z ON 1
+SETTINGS allow_experimental_analyzer=0, optimize_rewrite_array_exists_to_has=1;
```
Comment (novikd) [inline tests/queries/0_stateless/03261_optimize_rewrite_array_exists_to_has_crash.sql:10]: Why only with a disabled analyzer when you also made changes to `JoinNode`?

**Comment by Algunenano** [comment]
* AST fuzzer (debug) -> Already reverted the PR that caused it in master. I'll refresh
* Bugfix validation: The test only crashes with the old analyzer, but we left the test with open settings so it's tested with both. The validation is only running with the new analyzer so it's not crashing. I could change it to use `EXPLAIN SYNTAX`, which still uses the old analyzer underneath, but then we would not test the new one. Let's leave it as is.
* Stateless tests (tsan, s3 storage) [2/3] : `is broken and needs manual correction` https://github.com/ClickHouse/ClickHouse/issues/54748

**Comment by Algunenano** [comment]
ROFL:

```
+ attach_gdb_to_clickhouse
++ clickhouse-client --query 'SELECT count() FROM system.build_options WHERE name = '\''CXX_FLAGS'\'' AND position('\''sanitize=address'\'' IN value)'
Received exception from server (version 24.11.1):
Code: 439. DB::Exception: Received from localhost:9000. DB::Exception: Cannot schedule a task: fault injected (threads=1, jobs=1). (CANNOT_SCHEDULE_TASK)
(query: SELECT count() FROM system.build_options WHERE name = 'CXX_FLAGS' AND position('sanitize=address' IN value))
+ IS_ASAN=
+ [[ '' = \1 ]]
```

I'll have a look to see how we can disable this :D
