### PR TITLE
Avoid deadlock when starting table in attach thread of `ReplicatedMergeTree`

### LINKED ISSUE #49962: server does not start after upgrading to version 22.9 and later
HI! I have met with problem after updating to any version later than 22.9
now i have 22.8.16 version. It is the latest version witch don't have any problem with start
Today I tried to upgrade to 23.4
when the server tries to start after the update, it stops at the initialization of a table and does not continue further
```
2023.05.17 10:25:34.488205 [ 1499100 ] {} <Information> Application: Starting ClickHouse 23.4.2.11 (revision: 54473, git hash: b6442320f9dc85d127bfaf84febe76e9294b2407, build id: CB00FF1352DDBA096F95C86
E890588C10074E9A1), PID 1499100
...
2023.05.17 10:26:02.167995 [ 1499545 ] {} <Debug> pulse.top_stat_all_by_week_replicated (c0602bff-6917-4249-9293-7a2c14ec5f10): Creating shared ID for table pulse.top_stat_all_by_week_replicated (c0602b
ff-6917-4249-9293-7a2c14ec5f10)
2023.05.17 10:26:02.169083 [ 1499545 ] {} <Debug> pulse.top_stat_all_by_week_replicated (c0602bff-6917-4249-9293-7a2c14ec5f10): Initializing table shared ID with c0602bff-6917-4249-9293-7a2c14ec5f10
2023.05.17 10:26:02.170105 [ 1499545 ] {} <Information> pulse.top_stat_all_by_week_replicated (c0602bff-6917-4249-9293-7a2c14ec5f10): Became leader
```
but in error log there is no any errors that connected with it
strace shows that it is waiting for something (but this strace example is not from the last try, I have checked that the behavior is always the same)
```
strace -p 1182283
strace: Process 1182283 attached
futex(0x7ffe070b7ea0, FUTEX_WAIT_PRIVATE, 0, NULL
```

**Does it reproduce on recent release?**

yes, i've reproduce it on every version later than 22.9

**How to reproduce**
I don't know how exactly to reproduce this problem. I indicated above how it happens to me

**Expected behavior**

normal starting after upgrade

**Additional context**

if it helps, i can try to collect a full trace log after launch. Or maybe you know how i can update my servers
if it matters i have a cluster of 6 servers with 3 shards

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid deadlock when starting `ReplicatedMergeTree` tables. Tables could end up in deadlock if background threadpool size was lower than the number of tables.

Fix https://github.com/ClickHouse/ClickHouse/issues/49962

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 3107070e7699d14a6895dbdeb556b69986fc604b with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50026/3107070e7699d14a6895dbdeb556b69986fc604b/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -4416,21 +4416,30 @@ void StorageReplicatedMergeTree::startupImpl(bool from_attach_thread)
 
         startBeingLeader();
 
-        /// In this thread replica will be activated.
-        restarting_thread.start();
+        if (from_attach_thread)
+        {
+            /// Try activating replica in current thread.
+            restarting_thread.run();
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:4422]: Don't we need to start it after that?

Comment (antonio2368) [reply src/Storages/StorageReplicatedMergeTree.cpp:4422]: maybe I understood something wrong, but if it was a successful `run`, task will just finish and nothing will be scheduled in background anyway.
In case `run` had a failure, `task->scheduleAfter` is called inside of it so it will be scheduled in both cases.

One thing I would probably need to do is call `activate` on the task so it works with `wakeup`.

Comment (tavplubix) [reply src/Storages/StorageReplicatedMergeTree.cpp:4422]: Yep, the problem is that `schedule`/`scheduleAfter` do nothing if the task was not activated

Comment (antonio2368) [reply src/Storages/StorageReplicatedMergeTree.cpp:4425]: definitely a nice catch

**Review by tavplubix — APPROVED** [review]
