### PR TITLE
Fix getting file format from globs in file() function

### LINKED ISSUE #88920: Unexpected exception behavior with brace expansion and table function
### Company or project name

_No response_

### Describe the unexpected behaviour

While importing files using the `file` table function, ClickHouse behaves differently when importing a single file or the same file twice using brace expansion.

ClickHouse throws a parsing exception when importing a single file, but not with multiple files with brace expansion.

### Which ClickHouse versions are affected?

25.8, but should also apply to previous versions. 

### How to reproduce

```

SELECT version()

Query id: 7d0ecc42-0d70-48f8-86be-6bfeec055091

Connecting to localhost:9000 as user default.

Connected to ClickHouse server version 25.8.1.

   ┌─version()───┐

1. │ 25.8.1.3085 │

   └─────────────┘

CREATE TABLE test

(

    `ts` DateTime64(9, 'UTC')

)

ORDER BY tuple();

# insert nr.1 - With a single file ClickHouse throws a parsing exception

INSERT INTO test (ts) SELECT ts

FROM file(`output.parquet`)

Received exception from server (version 25.8.1):

Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '2020-01-01 14:00:00+00:00' as DateTime64(9, 'UTC'): syntax error at position 19 (parsed just '2020-01-01 14:00:00'): while converting column `ts` from type String to type DateTime64(9, 'UTC'): (in file/uri /Users/s.allegrini/Desktop/python_test/user_files/output.parquet): While executing ParquetBlockInputFormat: While executing File. (CANNOT_PARSE_TEXT)

# insert nr.2 - With brace expression ClickHouse doesn't throw the exception

INSERT INTO test (ts) SELECT ts

FROM file(`{output.parquet,output.parquet}`)

0 rows in set. Elapsed: 0.003 sec. 

# checking the data

SELECT *

FROM test

Query id: 069f2963-a680-4a47-9547-247f46443dc6

   ┌────────────────────────────ts─┐

1. │ 1970-01-01 00:00:00.000000000 │

2. │ 1970-01-01 00:00:00.000000000 │

   └───────────────────────────────┘

```

### Expected behavior

Always throw the exception

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):
Fix getting file format from globs in file() function. Resolves #88920

### CODE REVIEW

File: tests/queries/0_stateless/03701_parquet_conversion_to_datetime64.sh [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+# shellcheck source=../shell_config.sh
+. "$CURDIR"/../shell_config.sh
+
+#Test file were created with:
+#
+# import pyarrow.parquet as pq
+# import pyarrow as pa
+# id = pa.array(["1"], type=pa.string())
+# ts = pa.array(["2020-01-01 14:00:00"], type=pa.string())
+# ts_plus_tz = pa.array(["2020-01-01 14:00:00+00:00"], type=pa.string())
```
Comment (vitlibar) [inline tests/queries/0_stateless/03701_parquet_conversion_to_datetime64.sh:16]: `2020-01-01 14:00:00+00:00` is a wrong format for ClickHouse columns of type `DateTime64`. So the command

```
INSERT INTO test (ts) SELECT ts_plus_tz FROM file('conversion_to_datetime64_test.parquet')
```

fails with error message `Cannot parse string '2020-01-01 14:00:00+00:00' as DateTime64(9, 'UTC')` as expected.

---

However before this fix the following command
```
INSERT INTO test (ts) SELECT ts_plus_tz FROM file('conversion_to_datetime64_test.par?uet')
```
was successful and inserted `1970-01-01 00:00:00.000000000` to the table.

This PR makes such commands using globs fail with error message `Cannot parse` as expected.

**Comment by PedroTadim** [comment]
Does it fix https://github.com/ClickHouse/ClickHouse/issues/88920 ? If so, please mention it to close it.

**Comment by vitlibar** [comment]
> Does it fix #88920 ? If so, please mention it to close it.

Yes. Thanks, I didn't notice they created an issue.

File: src/TableFunctions/TableFunctionFile.cpp [hunk 2]
```diff
@@ -90,13 +90,12 @@ StoragePtr TableFunctionFile::getStorage(
...
         String{},
         global_context->getSettingsRef()[Setting::rename_files_after_processing],
-        path_to_archive,
     };
 
     if (fd >= 0)
         return std::make_shared<StorageFile>(fd, args);
 
-    return std::make_shared<StorageFile>(source, global_context->getUserFilesPath(), false, args);
+    return std::make_shared<StorageFile>(*file_source, args);
```
Comment (jkartseva) [inline src/TableFunctions/TableFunctionFile.cpp:100]: chassert(file_source.has_value())

File: src/Storages/StorageFile.cpp [hunk 3]
```diff
@@ -910,6 +974,58 @@ namespace
...
+            }
+        }
+    }
+
+    if (!res.paths.empty())
+        res.path_for_partitioned_write = res.paths.front();
+    else
+        res.path_for_partitioned_write = filename;
+
+    return res;
```
Comment (jkartseva) [inline src/Storages/StorageFile.cpp:1026]: As a suggestion, instead of setting fields manually, pass them to a private `FileSource` c-tor:
```
    FileSource(String filename_, Strings paths_, std::optional<ArchiveInfo> archive_info_, size_t total_bytes_to_read_)
        : filename(std::move(filename_)), paths(std::move(paths_)), archive_info(std::move(archive_info_)), total_bytes_to_read(total_bytes_to_read_)
    {
    }
 ```

File: src/Storages/StorageFile.cpp [hunk 4]
```diff
@@ -910,6 +974,58 @@ namespace
...
+
+    FileSource res;
+    String user_files_path = context->getUserFilesPath();
+
+    if (!path_to_archive.empty())
+        res.archive_info = getArchiveInfo(path_to_archive, filename, user_files_path, context, res.total_bytes_to_read);
+    else
+        res.paths = getPathsList(filename, user_files_path, context, res.total_bytes_to_read);
+
+    res.with_globs = res.paths.size() > 1;
```
Comment (jkartseva) [inline src/Storages/StorageFile.cpp:998]: `with_globs` is derived from another field and it's cheap so that it can be in the form of a getter instead:
```
bool withGlobs() const { return paths.size() > 1; }
```

File: src/Storages/StorageFile.cpp [hunk 5]
```diff
@@ -910,6 +974,58 @@ namespace
...
+                res.format_from_filenames = {};
+                break;
+            }
+        }
+    }
+
+    if (!res.paths.empty())
+        res.path_for_partitioned_write = res.paths.front();
+    else
+        res.path_for_partitioned_write = filename;
```
Comment (jkartseva) [inline src/Storages/StorageFile.cpp:1024]: `path_for_partitioned_write` can also be in the form of a method

File: src/Storages/StorageFile.cpp [hunk 6]
```diff
@@ -268,6 +268,119 @@ void checkCreationIsAllowed(
...
+
+    std::string_view filename_view = std::string_view{source}.substr(pos + 2);
+    while (filename_view.starts_with(' '))
+        filename_view.remove_prefix(1);
+
+    /// possible situations when the first part can be archive is only if one of the following is true:
+    /// - it contains supported extension
+    /// - it contains characters that could mean glob expression
+    if (filename_view.empty() || path_to_archive_view.empty()
+        || (!hasSupportedArchiveExtension(path_to_archive_view) && path_to_archive_view.find_first_of("*?{") == std::string_view::npos))
```
Comment (jkartseva) [inline src/Storages/StorageFile.cpp]: nit: splitting the top (sanity check) and the bottom (is archive) conditions would make the code more readable. It's not a new code, so it doesn’t need to be modified as part of the bugfix.

**Review by jkartseva — APPROVED** [review]
LGTM

File: src/Storages/StorageFile.cpp (hunk 6 above)
Comment (vitlibar) [reply src/Storages/StorageFile.cpp]: done

File: src/TableFunctions/TableFunctionFile.cpp (hunk 2 above)
Comment (vitlibar) [reply src/TableFunctions/TableFunctionFile.cpp:100]: I added this `chassert` in this place and other places too with a comment.

File: src/Storages/StorageFile.cpp (hunk 3 above)
Comment (vitlibar) [reply src/Storages/StorageFile.cpp:1026]: Honestly I don't really see any benefits of adding such a constructor because since these fields are public and we need to calculate these fields anyway, the constructor looks like just an extra step.

File: src/Storages/StorageFile.cpp (hunk 4 above)
Comment (vitlibar) [reply src/Storages/StorageFile.cpp:998]: Yes, this calculation is simple, however it looks clear why `with_globs = (paths.size() > 1)` only when we parse `FileSource` from string. If we made this calculation later it would look strange. For this reason I'd prefer to keep this code as is.

File: src/Storages/StorageFile.cpp (hunk 5 above)
Comment (vitlibar) [reply src/Storages/StorageFile.cpp:1024]: Yes, this calculation is simple, however it looks clear why `path_for_partitioned_write = res.paths.front()` (or `filename`) only when we parse `FileSource` from string. If we made this calculation later it would look strange. For this reason I'd prefer to keep this code as is.

**Comment by vitlibar** [comment]
CI failures are unrelated:
- [00900_long_parquet_load_2](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88947&sha=8e30ae1720834a5b2b3fa2f171f4d825b83ecd7b&name_0=PR&name_1=Stateless+tests+%28amd_binary%2C+old+analyzer%2C+s3+storage%2C+DatabaseReplicated%2C+parallel%29) - test is [flaky](https://github.com/ClickHouse/ClickHouse/pull/87735#discussion_r2483735903).
- [Disk does not support WriteMode::Append. (NOT_IMPLEMENTED)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88947&sha=8e30ae1720834a5b2b3fa2f171f4d825b83ecd7b&name_0=PR&name_1=Stress+test+%28arm_asan%29) - see [issue #84669](https://github.com/ClickHouse/ClickHouse/issues/84669)

**Comment by azat** [comment]
This change actually breaks `00900_long_parquet_load_2`, since you added new file, will be fixed in https://github.com/ClickHouse/ClickHouse/pull/89383

**Comment by clickgapai** [comment]
Hi @vitlibar @jkartseva — while reviewing this PR I found the following:

- **Bug (P3):** `StorageFile` constructor from `FileSource` doesn't transfer `total_bytes_to_read`, breaking progress percentage for `file` queries — https://github.com/ClickHouse/ClickHouse/issues/102637

Happy to discuss — close anything that's wrong or already addressed.
