### PR TITLE
Fix read in order optimization for DESC sorting with FINAL

### LINKED ISSUE #45815: Order by desc issue for ReplacingMergeTree [regress]
This bug is reproducible in release `22.12.3.5` and cannot be reproduced in early version `22.6.1.1985`.

`Order by desc` is not applies to applies in some cases on `ReplacingMergeTree`. We expect that `order by desc` sort values in descenting order but it is not happens:

image

but without `FINAL`  or `WHERE` sorting works correct

image

image

# How to reproduce

Create table and insert new data:

```
CREATE TABLE mytable
(
    timestamp        UInt64,
    insert_timestamp UInt64,
    key              UInt64,
    value            Float64
) ENGINE = ReplacingMergeTree(insert_timestamp)
      PRIMARY KEY (key, timestamp)
      ORDER BY (key, timestamp);

INSERT INTO mytable (timestamp, insert_timestamp, key, value)
VALUES (1900000010000, 1675159770000, 5, -1)
       (1900000020000, 1675159770000, 5, -0.0002),
       (1900000030000, 1675159770000, 5, 0),
       (1900000040000, 1675159770000, 5, 0.05),
       (1900000050000, 1675159770000, 5, 1);
```

Execute query:

```
SELECT timestamp,
       value
FROM mytable
    FINAL
WHERE key = 5
ORDER BY timestamp DESC;
```

Expected:

```
1900000050000,1
1900000040000,0.05
1900000030000,0
1900000020000,-0.0002
1900000010000,-1
```

But found:

```
1900000010000,-1
1900000020000,-0.0002
1900000030000,0
1900000040000,0.05
1900000050000,1
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix read in order optimization for DESC sorting with FINAL, close https://github.com/ClickHouse/ClickHouse/issues/45815

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 1]
```diff
@@ -824,11 +829,14 @@ Pipe ReadFromMergeTree::spreadMarkRangesAmongStreamsFinal(
             pipe.addSimpleTransform([sorting_expr](const Block & header)
                                     { return std::make_shared<ExpressionTransform>(header, sorting_expr); });
 
-        /// If do_not_merge_across_partitions_select_final is true and there is only one part in partition
-        /// with level > 0 then we won't postprocess this part
+        /// If do_not_merge_across_partitions_select_final is true
+        /// and there is only one part in partition with level > 0
+        /// then we won't postprocess this part
+        bool should_read_in_order = !input_order_info || input_order_info->direction == 0;
```
Comment (hanfei1991) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:835]: Why should we read in order if input_order_info is null

Comment (vdimir) [reply src/Processors/QueryPlan/ReadFromMergeTree.cpp]: My mistake was that it should be `should_not_read_in_order`.
But anyway, decided to use another solution. We need to disable read-in-order optimization for reverse order with `final` because it may lead to incorrect `final` behavior (it may rely on read in direct order). Check out new commits in the PR, please.

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 2]
```diff
@@ -1262,12 +1256,15 @@ MergeTreeDataSelectAnalysisResultPtr ReadFromMergeTree::selectRangesToReadImpl(
...
 }
 
-void ReadFromMergeTree::requestReadingInOrder(size_t prefix_size, int direction, size_t limit)
+bool ReadFromMergeTree::requestReadingInOrder(size_t prefix_size, int direction, size_t limit)
 {
     /// if dirction is not set, use current one
     if (!direction)
         direction = getSortDirection();
 
+    if (direction != 1 && isFinal(query_info))
```
Comment (hanfei1991) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:1265]: Please add some comments about why final select can't support reverse order reading.

File: src/Storages/StorageMerge.cpp [hunk 3]
```diff
@@ -912,6 +908,23 @@ void ReadFromMerge::convertingSourceStream(
     }
 }
 
+bool ReadFromMerge::requestReadingInOrder(InputOrderInfoPtr order_info_)
```
Comment (hanfei1991) [inline src/Storages/StorageMerge.cpp:911]: ditto.

**Review by hanfei1991 — COMMENTED** [review]
rest LGTM

**Review by hanfei1991 — APPROVED** [review]

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp (hunk 2 above)
Comment (vdimir) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:1265]:
```suggestion
    /// Disable read-in-order optimization for reverse order with final. 
    /// Otherwise, it can lead to incorrect final behavior because the implementation may rely on the reading in direct order). 
    if (direction != 1 && isFinal(query_info))
```

File: src/Storages/StorageMerge.cpp [hunk 4]
```diff
@@ -912,6 +908,23 @@ void ReadFromMerge::convertingSourceStream(
...
+{
+    if (order_info_->direction != 1 && isFinal(query_info))
```
Comment (vdimir) [inline src/Storages/StorageMerge.cpp:913]:
```suggestion
    /// Disable read-in-order optimization for reverse order with final. 
    /// Otherwise, it can lead to incorrect final behavior because the implementation may rely on the reading in direct order). 
    if (order_info_->direction != 1 && isFinal(query_info))
```
