### PR TITLE
Fix runtime error while converting [Null] field to Array(Variant)

### LINKED ISSUE #65276: Variant: runtime error: load of value 808482864, which is not a valid value for type Types::Which
https://s3.amazonaws.com/clickhouse-test-reports/0/d93ce45a13a9047b50459f57699626391106351e/ast_fuzzer__ubsan_.html

```
SELECT variantElement(CAST(if(number % 2, NULL, number), 'Variant(String, UInt64)'), 'String')
FROM numbers([(('-128', 4, 4, 4, toUInt128(toNullable(4)), toNullable(4), 4, 4, 4, 4, toLowCardinality(4), toUInt128(4)), '-128', 4, 4, 4, 4, 4, 4, 4, toNullable(4), 4), toUInt64(0), NULL, toLowCardinality(2)], 4)
WHERE toLowCardinality(materialize(1))
SETTINGS max_threads = 8, receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, allow_experimental_analyzer = true, max_execution_time = 10., max_memory_usage = 10000000000, log_comment = '/workspace/ch/tests/queries/0_stateless/02943_variant_element.sql', send_logs_level = 'fatal', enable_optimize_predicate_expression = false, allow_introspection_functions = true, system_events_show_zero_values = true, optimize_syntax_fuse_functions = true, optimize_group_by_function_keys = false, allow_deprecated_syntax_for_merge_tree = true, use_variant_as_common_type = true, allow_experimental_variant_type = tru
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible runtime error while converting Array field with nulls to Array(Variant).

Closes https://github.com/ClickHouse/ClickHouse/issues/65276

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 392183832834bf7041a0cae4fd27fc1112f51bc2 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66727/392183832834bf7041a0cae4fd27fc1112f51bc2/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/4b0ef8edce0eca049bcdb8938fd9aecb0e8c2377/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by antaljanosbenjamin — APPROVED** [review]

File: src/Interpreters/convertFieldToType.cpp [hunk 1]
```diff
@@ -356,7 +356,7 @@ Field convertFieldToTypeImpl(const Field & src, const IDataType & type, const ID
             for (size_t i = 0; i < src_arr_size; ++i)
             {
                 res[i] = convertFieldToType(src_arr[i], element_type);
-                if (res[i].isNull() && !element_type.isNullable())
+                if (res[i].isNull() && !canContainNull(element_type))
```
Comment (antaljanosbenjamin) [inline src/Interpreters/convertFieldToType.cpp:359]: Github acted up or I messed up, but my comment is lost.

So this condition and the one below basically serves the same purpose: so set `have_unconvertible_element` only when we have issues in conversion. However the completely different phrasing (`A AND !B` and `!A OR B`) makes them a bit confusing. I know it is not strictly connected to the PR, so feel free to merge it without changing it, but if you are up for the change and willing to do it, it would be nice.

Comment (Avogar) [reply src/Interpreters/convertFieldToType.cpp:359]: Let's use `A AND !B` in all places

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @Avogar @antaljanosbenjamin — while reviewing this PR I found the following:

- **Bug (P2):** `ValuesBlockInputFormat.cpp:591` uses `isNullable()` instead of `canContainNull()`, rejecting NULL inserts into Variant columns when `input_format_null_as_default=0` — https://github.com/ClickHouse/ClickHouse/issues/104909

Happy to discuss — close anything that's wrong or already addressed.
