### PR TITLE
Fix logical error in evaluate constant expression

### LINKED ISSUE #47533: trying to get name of not a column: Set for table function
```sql

SELECT count() FROM mysql(mysql('127.0.0.1:9004', currentDatabase(), foo, 'default', '', SETTINGS connection_pool_size = 1), '127.0.0.1:9004', currentDatabase(), foo, '', '')

```

https://s3.amazonaws.com/clickhouse-test-reports/47316/027db789d6a40fa11a3dfbc93bbda1825a8371d6/fuzzer_astfuzzerasan/report.html

https://s3.amazonaws.com/clickhouse-test-reports/47316/027db789d6a40fa11a3dfbc93bbda1825a8371d6/fuzzer_astfuzzerubsan/report.html

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

Close #47533 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/evaluateConstantExpression.cpp [hunk 1]
```diff
@@ -44,6 +44,9 @@ static std::pair<Field, std::shared_ptr<const IDataType>> getFieldAndDataTypeFro
 
 std::pair<Field, std::shared_ptr<const IDataType>> evaluateConstantExpression(const ASTPtr & node, const ContextPtr & context)
 {
+    if (!node->hasColumnName())
```
Comment (CheSema) [inline src/Interpreters/evaluateConstantExpression.cpp:47]: Sorry, I do not fully understand the original problem. My question might be incorrect.

In scope of this 2 lines. Why if the is no column name then it is not not a constant expression. Is the reverse statement valid: node with column names is a constant expression?

Comment (vdimir) [reply src/Interpreters/evaluateConstantExpression.cpp:47]: Usually, all expressions passed here have column names, but in some weird cases like `mysql('127.0.0.1:9004', currentDatabase(), 'foo', 'default', '', SETTINGS connection_pool_size = 1)` we may have unexpected AST type (ASTSet in the example). The table function can't be constant.

Another solution is to check the table function name and throw an error for `mysql` and others. Like here https://github.com/ClickHouse/ClickHouse/blob/a1397d7a0dc60d965249c74bfca4db3310f2a0ad/src/Parsers/ASTFunction.cpp#L474-L475

It may be less generic, though. So need to realize if there're any other cases.

Comment (CheSema) [reply src/Interpreters/evaluateConstantExpression.cpp:47]: Thanks for clarification.
I understand now that we expect a constant expression as an argument. But encounter a function call.

But still I see some unclear statement: why presents of column names say anything about is expression constant or not? Furthermore my intuition says me an opposite thing, it is might be non constant if it has column name.

**Comment by vdimir** [comment]
I attempted to check the function type in `ActionsMatcher::visit` before calling `ast->getColumnName()` but some other tests are failing (e.g., suggestion hints are handled in a different place, also there can be udfs that are difficult to distinguish).
So, we can probably go with the same check already done for `view` function (for the same reason).

**Review by CheSema — APPROVED** [review]
