### PR TITLE
Prevent implicit conversions to `Field` when calling `toString`

### LINKED ISSUE #76797: Remove DB::toString from Field.h
Today I've spent ~2 hours debugging why removing an include in a header made some tests fail.

The failure occurred in `02932_refreshable_materialized_views_1`, which usually takes ~10 seconds, but after removing `#include <Interpreters/executeQuery.h>` from `IDatabase.h` it simply does not finish.
What's the reason?

Well:
* `executeQuery.h` includes `#include <Interpreters/QueryLogElement.h>`
* `QueryLogElement.h` includes `#include <Common/TransactionID.h>`
* And `TransactionID.h` includes `#include <IO/WriteHelpers.h>`

Why does this matter? Because we have multiple implementations of DB::toString:

https://github.com/ClickHouse/ClickHouse/blob/42d3a0a70bf5aec8f916f2f34417a2c0eefe4411/src/IO/WriteHelpers.h#L1323-L1346

https://github.com/ClickHouse/ClickHouse/blob/42d3a0a70bf5aec8f916f2f34417a2c0eefe4411/src/Core/Field.h#L835

So when you call toString with a type which is implicitly convertible to Field, which one will be used?

https://github.com/ClickHouse/ClickHouse/blob/48827c8942c2ad5d6cfd7da7549faf15a8460258/src/Storages/System/StorageSystemViewRefreshes.cpp#L61

Well, if you are including WriteHelpers you'll get the template implementation. If you don't then you get the Field implementation. One will print `Scheduled`, the other will print `2`. Fantastic UX.

So let's remove DB::toString from Field.h and rename it to something like more explicit such as FieldToString (please not another implicit conversion / operator String, it's doomed to cause issues again)

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Prevent implicit conversions to `Field` when calling `toString`, which could result in slow code and unintended results. Closes #76797.

### CODE REVIEW

File: src/Backups/SettingsFieldOptionalString.cpp [hunk 1]
```diff
@@ -10,6 +11,8 @@ namespace ErrorCodes
     extern const int CANNOT_PARSE_BACKUP_SETTINGS;
 }
 
+SettingFieldOptionalString::operator Field() const { return Field(value ? toString(*value) : ""); }
```
Comment (vitlibar) [inline src/Backups/SettingsFieldOptionalString.cpp]: `*value` is already a `String` here in `SettingFieldOptionalString`.

File: src/Storages/MergeTree/EphemeralLockInZooKeeper.cpp [hunk 2]
```diff
@@ -87,7 +87,7 @@ std::optional<EphemeralLockInZooKeeper> createEphemeralLockInZooKeeper(
         if (e != Coordination::Error::ZOK)
         {
             zkutil::KeeperMultiException::check(e, ops, responses); // This should always throw the proper exception
-            throw Exception(ErrorCodes::LOGICAL_ERROR, "Unable to handle error {} when acquiring ephemeral lock in ZK", toString(e));
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Unable to handle error {} when acquiring ephemeral lock in ZK", static_cast<int32_t>(e));
```
Comment (vitlibar) [inline src/Storages/MergeTree/EphemeralLockInZooKeeper.cpp]: `Coordination::errorMessage(e)` or just `e` seems better here than `static_cast<int32_t>(e)`

File: src/Core/Field.h [hunk 3]
```diff
@@ -839,7 +838,8 @@ void writeFieldText(const Field & x, WriteBuffer & buf);
 void writeFieldBinary(const Field & x, WriteBuffer & buf);
 Field readFieldBinary(ReadBuffer & buf);
 
-String toString(const Field & x);
+String fieldToString(const Field & x);
```
Comment (vitlibar) [inline src/Core/Field.h:841]: We could make it a public member function of `Field`.

**Review by vitlibar — APPROVED** [review]
