### PR TITLE
Fix rows_before_limit_at_least for LIMIT BY clause

### LINKED ISSUE #25581: rows_before_limit_at_least and COUNT(*) OVER() window function do not return expected count with LIMIT BY
We want to implement pagination using LIMIT (and OFFSET) and for that we need the total number of rows. We have so far used the rows_before_limit_at_least for this but have experienced that it for some queries do not give the expected result. It gives a number bigger than what is actually true. The issue can be boiled down to the following example:

```
create table if not exists test
(
    id      Int8,
    text    String,
    number  Int8
)
    engine = MergeTree()
        PARTITION BY id % 2
        ORDER BY (id, text);

insert into test (id, text, number)
VALUES (1, 'a', 1),
       (1, 'b', 2),
       (2, 'c', 3);

select id, text, sum(number), COUNT(*) OVER() as window_function_count
from test
group by id, text
order by text desc
limit 1 by id
limit 5
settings allow_experimental_window_functions = 1
FORMAT
JSON
```

which gives the following output:

```
{
	"meta":
	[
		{
			"name": "id",
			"type": "Int8"
		},
		{
			"name": "text",
			"type": "String"
		},
		{
			"name": "sum(number)",
			"type": "Int64"
		},
		{
			"name": "window_function_count",
			"type": "UInt64"
		}
	],

	"data":
	[
		{
			"id": 2,
			"text": "c",
			"sum(number)": "3",
			"window_function_count": "3"
		},
		{
			"id": 1,
			"text": "b",
			"sum(number)": "2",
			"window_function_count": "3"
		}                                                                                                                                                             
	],

	"rows": 2,

	"rows_before_limit_at_least": 3,

	"statistics":
	{
		"elapsed": 0.009523299,
		"rows_read": 3,
		"bytes_read": 36
	}
}

```

As expected the result returns two rows as it is limited to one row for each `id`, but both the count over window function and the `rows_before_limit_at_least` says there are three rows which is clearly not the case for this query. They count in the row which should be excluded by the `LIMIT 1 BY id`.

**So the question is:** Is this as expected or is it a bug? And in the case that this is expected behavior is there a different way to get the total rows without doing a query with count(*) as well as the "normal" query?

### PR DESCRIPTION
**Pull request by korowa**
Closes #25581 

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
For queries with combination of `ORDER BY ... LIMIT BY ... LIMIT N`, when ORDER BY is executed as a PartialSorting, the counter `rows_before_limit_at_least` now reflects the number of rows consumed by LIMIT clause instead of number of rows consumed by sorting transform.

### CODE REVIEW

**Comment by korowa** [comment]
Marking as draft to figure out how to make it work for parallel replicas.

**Comment by korowa** [comment]
@azat  could you please take a look when you have some time?

File: src/QueryPipeline/QueryPipeline.cpp [hunk 1]
```diff
@@ -22,6 +22,7 @@
 #include <Processors/Transforms/AggregatingTransform.h>
 #include <Processors/Transforms/CountingTransform.h>
 #include <Processors/Transforms/ExpressionTransform.h>
+#include "Processors/Transforms/LimitByTransform.h"
```
Comment (azat) [inline src/QueryPipeline/QueryPipeline.cpp]:
```suggestion
#include <Processors/Transforms/LimitByTransform.h>
```

**Review by azat — APPROVED** [review]
Sorry for the delay, LGTM!

As usual very decent tests, thank you!

**Comment by azat** [comment]
CI failures are unrelated:

>[Stateless tests (amd_binary, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78999&sha=f9dbacd9eb903ec81c061223c6c8b8e9ed4b3d1b&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%29) — Failed: 1, Passed: 7118, Skipped: 883
>[Stateless tests (amd_debug, distributed plan, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78999&sha=f9dbacd9eb903ec81c061223c6c8b8e9ed4b3d1b&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%29) — Failed: 1, Passed: 7808, Skipped: 340

- #82792 

>[Integration tests (release, 4/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78999&sha=f9dbacd9eb903ec81c061223c6c8b8e9ed4b3d1b&name_0=PR&name_1=Integration%20tests%20%28release%2C%204%2F4%29) — fail: 1, passed: 910

- `test_storage_iceberg/test.py::test_minmax_pruning[True-local]` - https://github.com/ClickHouse/ClickHouse/issues/82810
