### PR TITLE
Fix crash when arguments of the dictionary layout are zero values

### LINKED ISSUE #78314: Another division by 0
### Describe the bug

This time happens with dictionaries with `block_size` 0

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/ac7905e3-ea7d-40db-9ef8-f1f94ec72656

### Error message and/or stacktrace

Stack trace:

```
#0  0x00005555670e03f5 in DB::parseSSDCacheStorageConfiguration (config=..., full_name=..., layout_type=..., dictionary_layout_prefix=..., dict_lifetime=...) at src/Dictionaries/registerCacheDictionaries.cpp:110
#1  0x00005555671054b1 in DB::createCacheDictionaryLayout<(DB::DictionaryKeyType)0, true> (full_name=..., dict_struct=..., config=..., config_prefix=..., source_ptr=..., global_context=..., created_from_ddl=<optimized out>)
    at src/Dictionaries/registerCacheDictionaries.cpp:225
#2  0x00005555670e1175 in DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool) const (source_ptr=..., 
    global_context=..., this=<optimized out>, full_name=..., dict_struct=..., config=..., config_prefix=..., created_from_ddl=<optimized out>) at src/Dictionaries/registerCacheDictionaries.cpp:293
#3  std::__1::__invoke[abi:se190107]<DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool>(DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>&&, std::__1::shared_ptr<DB::Context const>&&, bool&&) (__args=<optimized out>, __args=<optimized out>, __f=..., __args=<optimized out>, 
    __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149
#4  std::__1::__invoke_void_return_wrapper<std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> >, false>::__call[abi:se190107]<DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool>(DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>&&, std::__1::shared_ptr<DB::Context const>&&, bool&&) (__args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:216
#5  std::__1::__function::__default_alloc_func<DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2, std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool)>::operator()[abi:se190107](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>&&, std::__1::shared_ptr<DB::Context const>&&, bool&&) (
    __arg=<optimized out>, __arg=<optimized out>, this=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>)
    at contrib/llvm-project/libcxx/include/__functional/function.h:210
#6  std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool)>::__call_impl[abi:se190107]<std::__1::__function::__default_alloc_func<DB::registerDictionaryCache(DB::DictionaryFactory&)::$_2, std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool)> >(std::__1::__function::__policy_storage const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>&&, std::__1::shared_ptr<DB::Context const>&&, bool) (__buf=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>)
    at contrib/llvm-project/libcxx/include/__functional/function.h:610
#7  0x00005555681c249d in std::__1::__function::__policy_func<std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool)>::operator()[abi:se190107](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>&&, std::__1::shared_ptr<DB::Context const>&&, bool&&) const (this=0x7ffeb0451c80, __args=<optimized out>, 
    __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>) at contrib/llvm-project/libcxx/include/__functional/function.h:716
#8  std::__1::function<std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDictionarySource>, std::__1::shared_ptr<DB::Context const>, bool)>::operator() (
    this=0x7ffeb0451c80, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>, __arg=<optimized out>)
    at contrib/llvm-project/libcxx/include/__functional/function.h:989
#9  DB::DictionaryFactory::create (this=0x555575b692b8 <DB::DictionaryFactory::instance()::ret>, name=..., config=..., config_prefix=..., global_context=..., created_from_ddl=<optimized out>)
    at src/Dictionaries/DictionaryFactory.cpp:58
#10 0x0000555569cf94a4 in DB::ExternalDictionariesLoader::createObject (this=<optimized out>, name=..., config=..., key_in_config=..., repository_name=...) at src/Interpreters/ExternalDictionariesLoader.cpp:47
#11 0x0000555569d05348 in DB::ExternalLoader::createOrCloneObject (this=0x7ffeb0451c80, previous_version=..., name=..., config=...) at src/Interpreters/ExternalLoader.cpp:1512
#12 DB::ExternalLoader::LoadingDispatcher::loadSingleObject (this=this@entry=0x7ffd35b7e900, name=..., config=..., previous_version=...) at src/Interpreters/ExternalLoader.cpp:1043
#13 0x0000555569d03ddd in DB::ExternalLoader::LoadingDispatcher::doLoading (this=<optimized out>, name=..., loading_id=<optimized out>, forced_to_reload=<optimized out>, min_id_to_finish_loading_dependencies_=<optimized out>, 
    async=<optimized out>, thread_group=...) at src/Interpreters/ExternalLoader.cpp:998
#14 0x0000555569d07df4 in std::__1::__invoke[abi:se190107]<void (DB::ExternalLoader::LoadingDispatcher::*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), DB::ExternalLoader::LoadingDispatcher*&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&, std::__1::shared_ptr<DB::ThreadGroup>&, void>(void (DB::ExternalLoader::LoadingDispatcher::*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), DB::ExternalLoader::LoadingDispatcher*&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&, std::__1::shared_ptr<DB::ThreadGroup>&) (
    __a0=@0x7ffd259ebe10: 0x7ffd35b7e900, __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __f=<optimized out>) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#15 std::__1::__apply_tuple_impl[abi:se190107]<void (DB::ExternalLoader::LoadingDispatcher::*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup> >&, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>(void (DB::ExternalLoader::LoadingDispatcher::*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup> >&, std::__1::__tuple_indices<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>) (__t=..., __f=<optimized out>) at contrib/llvm-project/libcxx/include/tuple:1354
#16 std::__1::apply[abi:se190107]<void (DB::ExternalLoader::LoadingDispatcher::*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup> >&>(void (DB::ExternalLoader::LoadingDispatcher::*&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), std::__1::tuple<DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup> >&) (__t=..., 
    __f=<optimized out>) at contrib/llvm-project/libcxx/include/tuple:1358
#17 ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<void (DB::ExternalLoader::LoadingDispatcher::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool, std::__1::shared_ptr<DB::ThreadGroup> >(void (DB::ExternalLoader::LoadingDispatcher::*&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroup>), DB::ExternalLoader::LoadingDispatcher*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&&, std::__1::shared_ptr<DB::ThreadGroup>&&)::{lambda()#1}::operator()() (this=0x7ffeb371dc00) at src/Common/ThreadPool.h:312
#18 0x0000555565134632 in std::__1::__function::__policy_func<void ()>::operator()[abi:se190107]() const (this=0x7ffd259ec210) at contrib/llvm-project/libcxx/include/__functional/function.h:716
#19 std::__1::function<void()>::operator() (this=0x7ffd259ec210) at contrib/llvm-project/libcxx/include/__functional/function.h:989
#20 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (this=0x7ffeb36da060) at src/Common/ThreadPool.cpp:809
#21 0x000055556513a920 in std::__1::__invoke[abi:se190107]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) (__f=<optimized out>, __a0=<optimized out>) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#22 std::__1::__thread_execute[abi:se190107]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (__t=...) at contrib/llvm-project/libcxx/include/__thread/thread.h:192
#23 std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=<optimized out>) at contrib/llvm-project/libcxx/include/__thread/thread.h:201
#24 0x00007ffff7ca1e2e in start_thread (arg=<optimized out>) at nptl/pthread_create.c:447
#25 0x00007ffff7d33a4c in __GI___clone3 () at .sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### PR DESCRIPTION
**Pull request by ahmadov**
Fixes #78314 

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Dictionaries of type `ssd_cache` now reject zero or negative `block_size` and `write_buffer_size` parameters (issue #78314).

### CODE REVIEW

File: src/Dictionaries/getDictionaryConfigurationFromAST.cpp [hunk 1]
```diff
@@ -166,6 +166,13 @@ void buildLayoutConfiguration(
                 value_field.getTypeName());
         }
 
+        if (value_field.safeGet<UInt64>() == 0)
```
Comment (rschu1ze) [inline src/Dictionaries/getDictionaryConfigurationFromAST.cpp:169]: Did you test what happens if a negative value is passed as Float or String (--> l. 161), e.g. `-2.0`? I could imagine that `safeGet<UInt64>` does a numeric roll-over internally and we'll get UINT_MAX - 1 in which case the new check would not work.

Please also add a small SQL test --> https://clickhouse.com/docs/development/tests in tests/queries/0_stateless/ - thanks!

Comment (ahmadov) [reply src/Dictionaries/getDictionaryConfigurationFromAST.cpp:169]: yes, I tested with negative value and it fails in the previous check. It detects the negative value as `Int64`, then it throws an error.

Comment (ahmadov) [reply src/Dictionaries/getDictionaryConfigurationFromAST.cpp:169]: added the test with cc40fc3c996d4eb09f93776d6ef02c435cc78b93

File: tests/queries/0_stateless/03405_ssd_cache_layout.sh [hunk 2]
```diff
@@ -0,0 +1,44 @@
+#!/usr/bin/env bash
+# Tags: no-replicated-database
+
+CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03405_ssd_cache_layout.sh:4]: @ahmadov .sql tests are simpler than .sh tests (fewer degrees of freedom, less complexity), and therefore preferred. In some cases .sh tests are needed but as far as I see, this isn't one of them.

It is possible to do "negative" tests in .sql tests as well - see tests/queries/0_stateless/02354_vector_search_index_creation_negative.sql for an example. One can only check the error code instead the full error string but that is fine.

Therefore, could you please try to convert this test to .sql? Thanks!

File: tests/queries/0_stateless/03405_ssd_cache_layout.sh [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+# shellcheck source=../shell_config.sh
+. "$CURDIR"/../shell_config.sh
+
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03405_ssd_cache_layout.sh:7]: Let's also add a comment on top which states that this is a test for GitHub issue #78314

File: tests/queries/0_stateless/03406_dictionary_lifetime.sh [hunk 4]
```diff
@@ -0,0 +1,48 @@
+#!/usr/bin/env bash
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03406_dictionary_lifetime.sh:1]: Same comments as in the other test apply here.

Minor comment: Could we maybe rename the test to 03406_dictionary_incorrect_min_max_lifetimes?

Comment (rschu1ze) [reply tests/queries/0_stateless/03406_dictionary_lifetime.sh:1]: Let's rename the other test similarly: tests/queries/0_stateless/03405_ssd_cache_incorrect_min_max_lifetimes_and_block_size.sh

**Review by rschu1ze — APPROVED** [review]

File: src/Dictionaries/getDictionaryConfigurationFromAST.cpp [hunk 5]
```diff
@@ -81,6 +81,14 @@ void buildLifetimeConfiguration(
     if (!lifetime)
         return;
 
+    if (lifetime->min_sec > lifetime->max_sec)
+    {
+        throw DB::Exception(
+            ErrorCodes::BAD_ARGUMENTS,
+            "{} parameter 'MIN' must be less than or equal to 'MAX'.",
```
[the remark this answers is not in the document]
Comment (ahmadov) [reply src/Dictionaries/getDictionaryConfigurationFromAST.cpp]: 1d06a0c061cc1822e6e1a57db4e36a3f938428ad

File: tests/queries/0_stateless/03405_ssd_cache_layout.sh (hunk 3 above)
Comment (ahmadov) [reply tests/queries/0_stateless/03405_ssd_cache_layout.sh]: added in 1d06a0c061cc1822e6e1a57db4e36a3f938428ad

File: tests/queries/0_stateless/03405_ssd_cache_layout.sh (hunk 2 above)
Comment (ahmadov) [reply tests/queries/0_stateless/03405_ssd_cache_layout.sh]: yes, the only reason I used `.sh` tests to check the exact error message but as you mentioned it's not so important since the error codes can be used as well. Moved them into `.sql` tests with 1d06a0c061cc1822e6e1a57db4e36a3f938428ad

File: tests/queries/0_stateless/03405_ssd_cache_incorrect_min_max_lifetimes_and_block_size.sql [hunk 6]
```diff
@@ -0,0 +1,18 @@
+-- Tags: no-ordinary-database
+
+-- Tests that various conditions are checked during creation of a ssd_cache layout of a dictionary
+
+-- Github issue #78314
+
+DROP DICTIONARY IF EXISTS dx;
+
+SELECT 'BLOCK_SIZE is a negative value.';
+CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(BLOCK_SIZE -1)) LIFETIME(1); -- { serverError 36 }
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03405_ssd_cache_incorrect_min_max_lifetimes_and_block_size.sql:10]: `36` will work but the cleartext error name from src/Common/ErrorCodes.cpp would also work:

```cpp
-- { serverError BAD_ARGUMENTS }
```

Comment (ahmadov) [reply tests/queries/0_stateless/03405_ssd_cache_incorrect_min_max_lifetimes_and_block_size.sql]: a833c89a8e6cae4b1a2066122217f036d9361f30

Comment (rschu1ze) [reply tests/queries/0_stateless/03405_ssd_cache_incorrect_min_max_lifetimes_and_block_size.sql]: Cool, thanks. No need to post commit SHAs (I wouldn't usually check the individual commits anyways - I just look at the entire PR) 😄 Rather, feel free to mark the comment as resolved.

Comment (ahmadov) [reply tests/queries/0_stateless/03405_ssd_cache_incorrect_min_max_lifetimes_and_block_size.sql]: kinda old habits 😄
