### PR TITLE
Iterate through shards in getStructureOfRemoteTable if skip_unavailable_shards is set

### LINKED ISSUE #7268: skip_unavailable_shards is not working as expected
```sql
-- This works as expected.
SELECT count()
FROM remote('{127,1}.0.0.{2,3}', system.one)
SETTINGS skip_unavailable_shards = 1

┌─count()─┐
│       2 │
└─────────┘

-- However if we change the pattern so that the first host in unavailable it will fail.
SELECT count()
FROM remote('{1,127}.0.0.{2,3}', system.one)
SETTINGS skip_unavailable_shards = 1

Received exception from server (version 19.14.3):
Code: 279. DB::Exception: Received from localhost:9000. DB::NetException. DB::NetException: All connection tries failed. Log:

Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 1.0.0.2:9000 (1.0.0.2:9000) (version 19.14.3.3 (official build))
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 1.0.0.2:9000 (1.0.0.2:9000) (version 19.14.3.3 (official build))
Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: 1.0.0.2:9000 (1.0.0.2:9000) (version 19.14.3.3 (official build))

.

0 rows in set. Elapsed: 0.162 sec.
```

### PR DESCRIPTION
**Pull request by nvartolomei**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

For changelog. Remove if this is non-significant change.

Category (leave one):
- Improvement

Short description (up to few sentences):
Try to all shards in cluster when getting structure of remote table and skip_unavailable_shards is set.

Fixes #7268.

### CODE REVIEW

File: dbms/src/Storages/getStructureOfRemoteTable.cpp [hunk 1]
```diff
@@ -31,9 +32,42 @@ ColumnsDescription getStructureOfRemoteTable(
...
+    for (auto & shard_info : shards_info)
+    {
+        try {
+            const auto & res = getStructureOfRemoteTableInShard(shard_info, database, table, context, table_func_ptr);
+            return res;
+        }
+        catch (const DB::NetException & e)
+        {
+            /// THIS DOES NOT WORK AND IS ALWAYS FALSE???
+            if (context.getSettingsRef().skip_unavailable_shards)
```
Comment (nvartolomei) [inline dbms/src/Storages/getStructureOfRemoteTable.cpp]: This is always 0, what I'm missing?

File: dbms/src/Storages/getStructureOfRemoteTable.cpp [hunk 2]
```diff
@@ -31,9 +32,42 @@ ColumnsDescription getStructureOfRemoteTable(
...
+            {
+                std::string fail_message = getCurrentExceptionMessage(false);
+                fail_messages += fail_message + '\n';
```
Comment (nvartolomei) [inline dbms/src/Storages/getStructureOfRemoteTable.cpp]: Would be nice to log these. How to get the logger in this context, just pass it to the function?

File: dbms/src/Storages/getStructureOfRemoteTable.cpp (hunk 1 above)
Comment (nvartolomei) [reply dbms/src/Storages/getStructureOfRemoteTable.cpp]: The problem is that this is `context.query_context` which is built before query parsing by `context.makeQueryContext()` call in executeQuery.cpp. Not sure what is the right fix.

**Comment by nvartolomei** [comment]
This PR fixes the issue if skip_unavailable_shards is set on the connection level or session level.

File: dbms/src/Storages/getStructureOfRemoteTable.cpp [hunk 3]
```diff
@@ -31,9 +32,48 @@ ColumnsDescription getStructureOfRemoteTable(
     const Context & context,
     const ASTPtr & table_func_ptr)
 {
-    /// Send to the first any remote shard.
-    const auto & shard_info = cluster.getAnyShardInfo();
+    const auto & shards_info = cluster.getShardsInfo();
 
+    std::string fail_messages;
```
Comment (zhang2014) [inline dbms/src/Storages/getStructureOfRemoteTable.cpp]: Maybe `hasColumnInTable` function won't work?

File: dbms/src/Storages/getStructureOfRemoteTable.cpp [hunk 4]
```diff
@@ -31,9 +32,48 @@ ColumnsDescription getStructureOfRemoteTable(
...
+
+    for (auto & shard_info : shards_info)
```
Comment (zhang2014) [inline dbms/src/Storages/getStructureOfRemoteTable.cpp]: Maybe we just need to wrap all shard pools in one ConnectionPoolWithFailover when `skip_unavailable_shards = 1` ?

File: dbms/src/Storages/getStructureOfRemoteTable.cpp (hunk 3 above)
Comment (nvartolomei) [reply dbms/src/Storages/getStructureOfRemoteTable.cpp]: Why?

File: dbms/src/Storages/getStructureOfRemoteTable.cpp (hunk 4 above)
Comment (nvartolomei) [reply dbms/src/Storages/getStructureOfRemoteTable.cpp]: This could be neat (and we get out of the box prioritization based on error rates, could also implement prioritization of local replicas), but it looks like it would need a bit more refactoring which I'm not ready to do at the moment.

File: dbms/src/Storages/getStructureOfRemoteTable.cpp (hunk 3 above)
Comment (zhang2014) [reply dbms/src/Storages/getStructureOfRemoteTable.cpp]: Sorry I missed it's already in its own test.

**Review by zhang2014 — APPROVED** [review]

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
TSan report is relevant.
Look at `stderr.log`.

**Comment by nvartolomei** [comment]
@alexey-milovidov looks like we might need lock on settings object or cloning for settings? I was trying to lift applying settings before we insert query in process list, but it will break settings on sub-queries.

File: dbms/src/Storages/getStructureOfRemoteTable.cpp (hunk 2 above)
Comment (akuzm) [reply dbms/src/Storages/getStructureOfRemoteTable.cpp]: It's `LOG_INFO(&Poco::Logger::get("<some arbitrary name of your logging scope>"), "<the message>")`.

Going to improve this soon because it's absolutely undiscoverable, good that you asked.

File: dbms/src/Interpreters/InterpreterSelectQuery.cpp [hunk 5]
```diff
@@ -2694,7 +2694,10 @@ void InterpreterSelectQuery::initSettings()
 {
     auto & query = getSelectQuery();
     if (query.settings())
+    {
         InterpreterSetQuery(query.settings(), context).executeForCurrentContext();
+        InterpreterSetQuery(query.settings(), context.getQueryContext()).executeForCurrentContext();
```
[the remark this answers is not in the document]
Comment (akuzm) [reply dbms/src/Interpreters/InterpreterSelectQuery.cpp]: might be related: https://github.com/ClickHouse/ClickHouse/issues/3178

[the remark this answers is not in the document]
Comment (nvartolomei) [reply dbms/src/Interpreters/InterpreterSelectQuery.cpp]: Right. https://github.com/ClickHouse/ClickHouse/pull/7278/commits/18430b7f189eae1bb880322fbad3d6098ac49ac6 see commit message and comment on the diff.

I was trying to refactor a bit context usage but looks like I'd need a bit of time to wrap my head around that. Would appreciate if someone who knows the code better could do it.

**Comment by alexey-milovidov** [comment]
Sorry, I almost forgot about this PR because it gets postponed due TSan failure.
We should continue...

**Comment by alexey-milovidov** [comment]
The code looks Ok. I will try to merge...
