### PR TITLE
Fix `ReservoirSampler` self-merging

### LINKED ISSUE #78299: ASAN heap-use-after-free on ReservoirSampler
### Describe the bug

From this report: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=78284&sha=57f4abebb6364d08696df87e802d3517ae3059a9&name_0=PR&name_1=AST+fuzzer+%28asan%29

### How to reproduce

I can reproduce it on ASAN build with:

```sql
SELECT 1
FROM numbers(finalizeAggregation(10 * (
    SELECT medianState(number)
    FROM numbers(10)
)))
GROUP BY (SELECT 1);
```

### Error message and/or stacktrace

Stack trace:
```
[ip-172-31-18-156] 2025.03.26 11:27:20.320911 [ 3945434 ] <Fatal> BaseDaemon: ########################################
[ip-172-31-18-156] 2025.03.26 11:27:20.321184 [ 3945434 ] <Fatal> BaseDaemon: (version 25.4.1.1143 (official build), build id: 18549848918667F44AD217756C707D240CB0494B, git hash: 851f3d1fe293ea9c3de395d0b5b0b57d147e5b82) (from thread 3944662) (query_id: 03c4af38-49e2-478e-bc86-103c398fa3e3) (query: SELECT 1
FROM numbers(finalizeAggregation(10 * (
    SELECT medianState(number)
    FROM numbers(10)
)))
GROUP BY (SELECT 1);) Received signal sanitizer trap (-3)
[ip-172-31-18-156] 2025.03.26 11:27:20.321322 [ 3945434 ] <Fatal> BaseDaemon: Sanitizer trap.
[ip-172-31-18-156] 2025.03.26 11:27:20.321418 [ 3945434 ] <Fatal> BaseDaemon: Stack trace: 0x00005814735e2ae7 0x0000581473ccaf6b 0x0000581463afeb50 0x0000581463ae5229 0x0000581463ae8367 0x0000581463ae9246 0x0000581474b495b8 0x000058146db7d993 0x000058146db7cac2 0x000058146db7b1c5 0x0000581463b290b5 0x000058147d0c5b95 0x000058147d0b6a8f 0x000058147d0b9e39 0x000058147d0bc3d6 0x000058147ff4e308 0x000058147ff1d62e 0x000058147ff1c179 0x000058147ff47015 0x000058147ff1d62e 0x000058147ff219bf 0x000058147ff703ce 0x000058147ff10112 0x000058147ff0e0a8 0x000058147ff0cb57 0x000058147ffd9a6c 0x0000581481b18e72 0x0000581481b151d6 0x0000581481b1c51e 0x0000581481a62a3b 0x00005814822a2f1c 0x000058148229c065 0x000058148747c876 0x00005814874bc53a 0x000058148fd28b8f 0x000058148fd29857 0x000058148fc2d20b 0x000058148fc26e08 0x0000581463adde77 0x000079776e4a1e2e 0x000079776e533a4c
[ip-172-31-18-156] 2025.03.26 11:27:20.387804 [ 3945434 ] <Fatal> BaseDaemon: 0.0. inlined from src/Common/StackTrace.cpp:386: StackTrace::tryCapture()
[ip-172-31-18-156] 2025.03.26 11:27:20.387919 [ 3945434 ] <Fatal> BaseDaemon: 0. src/Common/StackTrace.cpp:61: StackTrace::StackTrace() @ 0x000000001bd51ae7
[ip-172-31-18-156] 2025.03.26 11:27:20.472919 [ 3945434 ] <Fatal> BaseDaemon: 1. src/Common/SignalHandlers.cpp:212: sanitizerDeathCallback() @ 0x000000001c439f6b
[ip-172-31-18-156] 2025.03.26 11:27:20.559063 [ 3945434 ] <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x000000000c26db50
[ip-172-31-18-156] 2025.03.26 11:27:20.604701 [ 3945434 ] <Fatal> BaseDaemon: 3. __asan::ScopedInErrorReport::~ScopedInErrorReport() @ 0x000000000c254229
[ip-172-31-18-156] 2025.03.26 11:27:20.649067 [ 3945434 ] <Fatal> BaseDaemon: 4. __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) @ 0x000000000c257367
[ip-172-31-18-156] 2025.03.26 11:27:20.692896 [ 3945434 ] <Fatal> BaseDaemon: 5. __asan_report_load8 @ 0x000000000c258246
[ip-172-31-18-156] 2025.03.26 11:27:21.037060 [ 3945434 ] <Fatal> BaseDaemon: 6.0. inlined from src/Common/PODArray.h:430: void DB::PODArray<unsigned long, 64ul, AllocatorWithStackMemory<Allocator<false, false>, 64ul, 8ul>, 0ul, 0ul>::push_back<unsigned long const&>(unsigned long const&)
[ip-172-31-18-156] 2025.03.26 11:27:21.037175 [ 3945434 ] <Fatal> BaseDaemon: 6.1. inlined from src/AggregateFunctions/ReservoirSampler.h:92: ReservoirSampler<unsigned long, (ReservoirSamplerOnEmpty::Enum)1, std::less<unsigned long>>::insert(unsigned long const&)
[ip-172-31-18-156] 2025.03.26 11:27:21.037236 [ 3945434 ] <Fatal> BaseDaemon: 6. src/AggregateFunctions/ReservoirSampler.h:169: ReservoirSampler<unsigned long, (ReservoirSamplerOnEmpty::Enum)1, std::less<unsigned long>>::merge(ReservoirSampler<unsigned long, (ReservoirSamplerOnEmpty::Enum)1, std::less<unsigned long>> const&) @ 0x000000001d2b85b8
[ip-172-31-18-156] 2025.03.26 11:27:21.080976 [ 3945434 ] <Fatal> BaseDaemon: 7. DB::FunctionBinaryArithmetic<DB::MultiplyImpl, DB::NameMultiply, true, true, false>::executeAggregateMultiply(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000162ec993
[ip-172-31-18-156] 2025.03.26 11:27:21.124194 [ 3945434 ] <Fatal> BaseDaemon: 8. DB::FunctionBinaryArithmetic<DB::MultiplyImpl, DB::NameMultiply, true, true, false>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000162ebac2
[ip-172-31-18-156] 2025.03.26 11:27:21.166967 [ 3945434 ] <Fatal> BaseDaemon: 9. DB::FunctionBinaryArithmeticWithConstants<DB::MultiplyImpl, DB::NameMultiply, true, true, false>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000162ea1c5
[ip-172-31-18-156] 2025.03.26 11:27:21.209213 [ 3945434 ] <Fatal> BaseDaemon: 10. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000c2980b5
[ip-172-31-18-156] 2025.03.26 11:27:21.217600 [ 3945434 ] <Fatal> BaseDaemon: 11. src/Functions/IFunctionAdaptors.cpp:16: DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000025834b95
[ip-172-31-18-156] 2025.03.26 11:27:21.259516 [ 3945434 ] <Fatal> BaseDaemon: 12. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000025825a8f
[ip-172-31-18-156] 2025.03.26 11:27:21.301321 [ 3945434 ] <Fatal> BaseDaemon: 13. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000025828e39
[ip-172-31-18-156] 2025.03.26 11:27:21.343128 [ 3945434 ] <Fatal> BaseDaemon: 14. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000002582b3d6
[ip-172-31-18-156] 2025.03.26 11:27:21.640035 [ 3945434 ] <Fatal> BaseDaemon: 15. src/Analyzer/Resolve/QueryAnalyzer.cpp:3566: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000286bd308
[ip-172-31-18-156] 2025.03.26 11:27:21.987345 [ 3945434 ] <Fatal> BaseDaemon: 16. src/Analyzer/Resolve/QueryAnalyzer.cpp:3837: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000002868c62e
[ip-172-31-18-156] 2025.03.26 11:27:22.328340 [ 3945434 ] <Fatal> BaseDaemon: 17. src/Analyzer/Resolve/QueryAnalyzer.cpp:3979: DB::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool) @ 0x000000002868b179
[ip-172-31-18-156] 2025.03.26 11:27:22.623145 [ 3945434 ] <Fatal> BaseDaemon: 18. src/Analyzer/Resolve/QueryAnalyzer.cpp:2924: DB::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&) @ 0x00000000286b6015
[ip-172-31-18-156] 2025.03.26 11:27:22.969899 [ 3945434 ] <Fatal> BaseDaemon: 19. src/Analyzer/Resolve/QueryAnalyzer.cpp:3837: DB::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, bool, bool, bool) @ 0x000000002868c62e
[ip-172-31-18-156] 2025.03.26 11:27:23.323862 [ 3945434 ] <Fatal> BaseDaemon: 20. src/Analyzer/Resolve/QueryAnalyzer.cpp:4801: DB::QueryAnalyzer::resolveTableFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&, bool) @ 0x00000000286909bf
[ip-172-31-18-156] 2025.03.26 11:27:23.703834 [ 3945434 ] <Fatal> BaseDaemon: 21. src/Analyzer/Resolve/QueryAnalyzer.cpp:5324: DB::QueryAnalyzer::resolveQueryJoinTreeNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&) @ 0x00000000286df3ce
[ip-172-31-18-156] 2025.03.26 11:27:24.065194 [ 3945434 ] <Fatal> BaseDaemon: 22. src/Analyzer/Resolve/QueryAnalyzer.cpp:5582: DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000002867f112
[ip-172-31-18-156] 2025.03.26 11:27:24.397612 [ 3945434 ] <Fatal> BaseDaemon: 23. src/Analyzer/Resolve/QueryAnalyzer.cpp:177: DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x000000002867d0a8
[ip-172-31-18-156] 2025.03.26 11:27:24.403970 [ 3945434 ] <Fatal> BaseDaemon: 24. src/Analyzer/Resolve/QueryAnalysisPass.cpp:18: DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x000000002867bb57
[ip-172-31-18-156] 2025.03.26 11:27:24.438863 [ 3945434 ] <Fatal> BaseDaemon: 25. src/Analyzer/QueryTreePassManager.cpp:184: DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x0000000028748a6c
[ip-172-31-18-156] 2025.03.26 11:27:24.542471 [ 3945434 ] <Fatal> BaseDaemon: 26. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:151: DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x000000002a287e72
[ip-172-31-18-156] 2025.03.26 11:27:24.623021 [ 3945434 ] <Fatal> BaseDaemon: 27. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:168: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000002a2841d6
[ip-172-31-18-156] 2025.03.26 11:27:24.726016 [ 3945434 ] <Fatal> BaseDaemon: 28. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::make_unique[abi:ne190107]<DB::InterpreterSelectQueryAnalyzer, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&>(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&) @ 0x000000002a28b51e
[ip-172-31-18-156] 2025.03.26 11:27:24.757753 [ 3945434 ] <Fatal> BaseDaemon: 29.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[ip-172-31-18-156] 2025.03.26 11:27:24.757828 [ 3945434 ] <Fatal> BaseDaemon: 29.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[ip-172-31-18-156] 2025.03.26 11:27:24.757880 [ 3945434 ] <Fatal> BaseDaemon: 29. src/Interpreters/InterpreterFactory.cpp:392: DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x000000002a1d1a3b
[ip-172-31-18-156] 2025.03.26 11:27:24.938240 [ 3945434 ] <Fatal> BaseDaemon: 30. src/Interpreters/executeQuery.cpp:1391: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x000000002aa11f1c
[ip-172-31-18-156] 2025.03.26 11:27:25.168628 [ 3945434 ] <Fatal> BaseDaemon: 31. src/Interpreters/executeQuery.cpp:1625: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000002aa0b065
[ip-172-31-18-156] 2025.03.26 11:27:25.327842 [ 3945434 ] <Fatal> BaseDaemon: 32. src/Server/TCPHandler.cpp:665: DB::TCPHandler::runImpl() @ 0x000000002fbeb876
[ip-172-31-18-156] 2025.03.26 11:27:25.624437 [ 3945434 ] <Fatal> BaseDaemon: 33. src/Server/TCPHandler.cpp:2630: DB::TCPHandler::run() @ 0x000000002fc2b53a
[ip-172-31-18-156] 2025.03.26 11:27:25.630818 [ 3945434 ] <Fatal> BaseDaemon: 34. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000038497b8f
[ip-172-31-18-156] 2025.03.26 11:27:25.642280 [ 3945434 ] <Fatal> BaseDaemon: 35. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000038498857
[ip-172-31-18-156] 2025.03.26 11:27:25.655467 [ 3945434 ] <Fatal> BaseDaemon: 36. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000003839c20b
[ip-172-31-18-156] 2025.03.26 11:27:25.668314 [ 3945434 ] <Fatal> BaseDaemon: 37. base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000038395e08
[ip-172-31-18-156] 2025.03.26 11:27:25.712253 [ 3945434 ] <Fatal> BaseDaemon: 38. asan_thread_start(void*) @ 0x000000000c24ce77
[ip-172-31-18-156] 2025.03.26 11:27:25.712332 [ 3945434 ] <Fatal> BaseDaemon: 39. ? @ 0x000079776e4a1e2e
[ip-172-31-18-156] 2025.03.26 11:27:25.712375 [ 3945434 ] <Fatal> BaseDaemon: 40. ? @ 0x000079776e533a4c
[ip-172-31-18-156] 2025.03.26 11:27:26.189009 [ 3945434 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 1625E5BDB97E5ABADBD1E5242F1CC9AC)
[ip-172-31-18-156] 2025.03.26 11:27:31.457035 [ 3945434 ] <Fatal> BaseDaemon: Changed settings: allow_reorder_prewhere_conditions = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_nonconst_timezone_arguments = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_execute_multiif_columnar = true, allow_drop_detached = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, allow_experimental_kafka_offsets_storage_in_keeper = true, allow_unrestricted_reads_from_keeper = true, allow_deprecated_database_ordinary = true, allow_deprecated_syntax_for_merge_tree = true, allow_get_client_http_header = true, allow_create_index_without_type = true, allow_named_collection_override_by_default = true, allow_deprecated_error_prone_window_functions = true, allow_deprecated_snowflake_conversion_functions = true, allow_experimental_parallel_reading_from_replicas = 1, parallel_replicas_for_non_replicated_merge_tree = true, parallel_replicas_for_cluster_engines = false, allow_experimental_analyzer = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_vector_similarity_index = true, allow_experimental_codecs = true, allow_experimental_shared_set_join = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_archive_path_syntax = true, allow_experimental_inverted_index = true, allow_experimental_full_text_index = true, allow_experimental_join_condition = true, allow_experimental_live_view = true, allow_experimental_window_view = true, allow_experimental_database_materialized_postgresql = true, type_json_skip_duplicated_paths = true
```

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
todo

Closes: #78299

### CODE REVIEW

File: src/AggregateFunctions/ReservoirSampler.h [hunk 1]
```diff
@@ -161,6 +161,13 @@ class ReservoirSampler
     {
         if (sample_count != b.sample_count)
             throw Poco::Exception("Cannot merge ReservoirSampler's with different sample_count");
+
+        // There will be an aliasing issue if we merge the same object with itself. I.e. we will insert from `b.samples` into `a.samples`,
+        // but both refer to the same array. It might happen in case of multiplying an aggregate function state by a numberic constant.
```
Comment (nickitat) [inline src/AggregateFunctions/ReservoirSampler.h:166]:
```suggestion
        // but both refer to the same array. It might happen in case of multiplying an aggregate function state by a numeric constant.
```

**Review by serxa — APPROVED** [review]

File: src/AggregateFunctions/ReservoirSampler.h [hunk 2]
```diff
@@ -161,6 +161,13 @@ class ReservoirSampler
     {
         if (sample_count != b.sample_count)
             throw Poco::Exception("Cannot merge ReservoirSampler's with different sample_count");
+
+        // There will be an aliasing issue if we merge the same object with itself. I.e. we will insert from `b.samples` into `a.samples`,
+        // but both refer to the same array. It might happen in case of multiplying an aggregate function state by a numeric constant.
+        // ATST, it seems that self-merging cannot improve accuracy, so there is no point to do it anyway.
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/ReservoirSampler.h:167]: What is ATST?

**Review by alexey-milovidov — APPROVED** [review]

File: src/AggregateFunctions/ReservoirSampler.h (hunk 2 above)
Comment (nickitat) [reply src/AggregateFunctions/ReservoirSampler.h:167]: at the same time )

**Comment by nickitat** [comment]
`Integration tests (tsan, 4/6)` - test_storage_rabbitmq
`Stress test (amd_tsan)` - https://github.com/ClickHouse/ClickHouse/issues/64936
