### PR TITLE
Analyzer: fix storage replacement with insertion block

### LINKED ISSUE #58080: Query from `02479_race_condition_between_insert_and_droppin_mv` may get stuck
https://s3.amazonaws.com/clickhouse-test-reports/57906/e4a831be17f85e345c5c9cd8f00bd22b8e759692/stateless_tests__release__analyzer_.html

```
2023-12-15 21:11:56 Found hung queries in processlist:
2023-12-15 21:11:56 Row 1:
2023-12-15 21:11:56 ──────
2023-12-15 21:11:56 is_initial_query:     1
2023-12-15 21:11:56 user:                 default
2023-12-15 21:11:56 query_id:             5c8c78d8-70f4-474b-a02c-090cdd83099d
2023-12-15 21:11:56 address:              ::1
2023-12-15 21:11:56 port:                 40178
2023-12-15 21:11:56 initial_user:         default
2023-12-15 21:11:56 initial_query_id:     5c8c78d8-70f4-474b-a02c-090cdd83099d
2023-12-15 21:11:56 initial_address:      ::1
2023-12-15 21:11:56 initial_port:         40178
2023-12-15 21:11:56 interface:            1
2023-12-15 21:11:56 os_user:              
2023-12-15 21:11:56 client_hostname:      e52d4065eab8
2023-12-15 21:11:56 client_name:          ClickHouse client
2023-12-15 21:11:56 client_revision:      54466
2023-12-15 21:11:56 client_version_major: 23
2023-12-15 21:11:56 client_version_minor: 12
2023-12-15 21:11:56 client_version_patch: 1
2023-12-15 21:11:56 http_method:          0
2023-12-15 21:11:56 http_user_agent:      
2023-12-15 21:11:56 http_referer:         
2023-12-15 21:11:56 forwarded_for:        
2023-12-15 21:11:56 quota_key:            
2023-12-15 21:11:56 distributed_depth:    0
2023-12-15 21:11:56 elapsed:              3455.436973
2023-12-15 21:11:56 is_cancelled:         0
2023-12-15 21:11:56 is_all_data_sent:     0
2023-12-15 21:11:56 read_rows:            250886
2023-12-15 21:11:56 read_bytes:           2007088
2023-12-15 21:11:56 total_rows_approx:    249886
2023-12-15 21:11:56 written_rows:         501
2023-12-15 21:11:56 written_bytes:        17008
2023-12-15 21:11:56 memory_usage:         7339080
2023-12-15 21:11:56 peak_memory_usage:    9433904
2023-12-15 21:11:56 query:                INSERT INTO test_race_condition_landing SELECT number, toString(number), toString(number) from system.numbers limit 1386, 500
2023-12-15 21:11:56 query_kind:           Insert
2023-12-15 21:11:56 thread_ids:           [9696,1946,31713,32004,32007,31813,31720,9798,31709,2027,31587,31834,31651,32121,31589,9861,31783,9830,1973,31685,1518,2711,9707,31629,9708,2724,1478,31742,9820,1943,31741,2244,31635,1953,2282,31870,1509,2261,2014,31987,2248,1903,2012,31972,2290,9785,31657,9832,1939,31690,31656,2700,31638,1964,31807,2427]
2023-12-15 21:11:56 ProfileEvents:        {'Query':1,'InsertQuery':1,'QueriesWithSubqueries':9,'SelectQueriesWithSubqueries':7,'InsertQueriesWithSubqueries':2,'FileOpen':42,'ReadBufferFromFileDescriptorReadBytes':994353,'WriteBufferFromFileDescriptorWrite':9,'WriteBufferFromFileDescriptorWriteBytes':6785,'ReadCompressedBytes':926531,'CompressedReadBufferBlocks':61,'CompressedReadBufferBytes':1986016,'OpenedFileCacheMisses':33,'OpenedFileCacheMicroseconds':35,'IOBufferAllocs':87,'IOBufferAllocBytes':3763628,'ArenaAllocChunks':2,'ArenaAllocBytes':8192,'FunctionExecute':6,'MarkCacheHits':11,'MarkCacheMisses':11,'CreatedReadBufferOrdinary':33,'DiskReadElapsedMicroseconds':1870,'DiskWriteElapsedMicroseconds':170,'NetworkReceiveElapsedMicroseconds':1650,'NetworkSendElapsedMicroseconds':20510,'NetworkSendBytes':267439,'InsertedRows':501,'InsertedBytes':17008,'SelectedParts':22,'SelectedRanges':22,'SelectedMarks':50,'SelectedRows':250886,'SelectedBytes':2007088,'WaitMarksLoadMicroseconds':3037,'BackgroundLoadingMarksTasks':22,'LoadedMarksCount':108,'LoadedMarksMemoryBytes':1344,'MergeTreeDataWriterRows':500,'MergeTreeDataWriterUncompressedBytes':17000,'MergeTreeDataWriterCompressedBytes':6438,'MergeTreeDataWriterBlocks':1,'MergeTreeDataWriterBlocksAlreadySorted':1,'InsertedCompactParts':1,'ContextLock':98,'RWLockAcquiredReadLocks':21,'PartsLockHoldMicroseconds':156,'RealTimeMicroseconds':15054340,'UserTimeMicroseconds':14021392,'SystemTimeMicroseconds':367199,'SoftPageFaults':7053,'OSCPUWaitMicroseconds':23,'OSCPUVirtualTimeMicroseconds':4207,'OSReadChars':1040662,'CannotWriteToWriteBufferDiscard':3,'QueryProfilerRuns':10291,'ThreadPoolReaderPageCacheMiss':61,'ThreadPoolReaderPageCacheMissBytes':994353,'ThreadPoolReaderPageCacheMissElapsedMicroseconds':1870,'SynchronousReadWaitMicroseconds':6437,'LogTrace':39,'LogDebug':46,'LogInfo':1}
2023-12-15 21:11:56 Settings:             {'connect_timeout_with_failover_ms':'2000','connect_timeout_with_failover_secure_ms':'3000','idle_connection_timeout':'36000','s3_check_objects_after_upload':'1','stream_like_engine_allow_direct_select':'1','replication_wait_for_inactive_replica_timeout':'30','allow_nonconst_timezone_arguments':'1','log_queries':'1','insert_quorum_timeout':'60000','fsync_metadata':'0','http_send_timeout':'60','http_receive_timeout':'60','opentelemetry_start_trace_probability':'0.1','allow_experimental_analyzer':'1','max_untracked_memory':'1048576','memory_profiler_step':'1048576','log_comment':'02479_race_condition_between_insert_and_droppin_mv.sh','send_logs_level':'error','allow_introspection_functions':'1','database_atomic_wait_for_drop_and_detach_synchronously':'1','distributed_ddl_entry_format_version':'6','async_insert_busy_timeout_ms':'5000','enable_filesystem_cache':'1','enable_filesystem_cache_on_write_operations':'1','filesystem_cache_segments_batch_size':'10','load_marks_asynchronously':'1','allow_prefetched_read_pool_for_remote_filesystem':'0','allow_prefetched_read_pool_for_local_filesystem':'0','filesystem_prefetch_max_memory_usage':'1073741824','insert_keeper_max_retries':'20','insert_keeper_fault_injection_probability':'0.01'}
2023-12-15 21:11:56 current_database:     test_9pzvs9be
2023-12-15 21:11:56 stacktraces:          Thread ID 2427
2023-12-15 21:11:56 ::
2023-12-15 21:11:56 ::
2023-12-15 21:11:56 ./base/poco/Foundation/src/Event_POSIX.cpp:145::Poco::EventImpl::waitImpl(long)
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:96::DB::CompletedPipelineExecutor::execute()
2023-12-15 21:11:56 ./build_docker/./src/Server/TCPHandler.cpp:548::DB::TCPHandler::runImpl()
2023-12-15 21:11:56 ./build_docker/./src/Server/TCPHandler.cpp:2294::DB::TCPHandler::run()
2023-12-15 21:11:56 ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57::Poco::Net::TCPServerConnection::start()
2023-12-15 21:11:56 ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48::Poco::Net::TCPServerDispatcher::run()
2023-12-15 21:11:56 ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202::Poco::PooledThread::run()
2023-12-15 21:11:56 ./base/poco/Foundation/include/Poco/SharedPtr.h:231::Poco::ThreadImpl::runnableEntry(void*)
2023-12-15 21:11:56 ::
2023-12-15 21:11:56 ::Thread ID 31656
2023-12-15 21:11:56 ./contrib/jemalloc/include/jemalloc/internal/sz.h:191::operator delete(void*, unsigned long)
2023-12-15 21:11:56 ./contrib/llvm-project/libcxx/include/new:0::std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>>>::__move_assign(std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, unsigned long>>>&, std::__1::integral_constant<bool, true>)
2023-12-15 21:11:56 ./src/Core/Block.h:25::DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)
2023-12-15 21:11:56 ./build_docker/./src/Processors/Transforms/JoiningTransform.cpp:0::DB::JoiningTransform::work()
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0::DB::ExecutionThreadContext::executeTask()
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273::DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
2023-12-15 21:11:56 ./contrib/llvm-project/libcxx/include/atomic:958::DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*)
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/PullingPipelineExecutor.cpp:54::DB::PullingPipelineExecutor::pull(DB::Chunk&)
2023-12-15 21:11:56 ./build_docker/./src/Processors/Transforms/buildPushingToViewsChain.cpp:648::DB::ExecutingInnerQueryFromViewTransform::onGenerate()
2023-12-15 21:11:56 ./build_docker/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:164::void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_2, void ()>>(std::__1::__function::__policy_storage const*)
2023-12-15 21:11:56 ./contrib/llvm-project/libcxx/include/__functional/function.h:848::DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*)
2023-12-15 21:11:56 ./contrib/llvm-project/libcxx/include/__functional/function.h:818::DB::ExceptionKeepingTransform::work()
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0::DB::ExecutionThreadContext::executeTask()
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273::DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
2023-12-15 21:11:56 ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701::DB::PipelineExecutor::execute(unsigned long, bool)
2023-12-15 21:11:56 ./build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:0::void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
2023-12-15 21:11:56 ./base/base/../base/wide_integer_impl.h:809::void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)
2023-12-15 21:11:56 ::
2023-12-15 21:11:56 ::
```

The query is waiting for something for 3455 seconds

~~cc: @AlfVII, @Avogar~~

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix analyzer - insertion from select with subquery referencing insertion table should process only insertion block for all table expressions.
Fixes #58080.
follow-up #50857

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit bb1058e2b28401b8189c2d21db9476fca19286cb with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58958/bb1058e2b28401b8189c2d21db9476fca19286cb/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58958/bb1058e2b28401b8189c2d21db9476fca19286cb/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Analyzer/Utils.h [hunk 1]
```diff
@@ -50,6 +50,9 @@ std::optional<bool> tryExtractConstantFromConditionNode(const QueryTreeNodePtr &
   */
 void addTableExpressionOrJoinIntoTablesInSelectQuery(ASTPtr & tables_in_select_query_ast, const QueryTreeNodePtr & table_expression, const IQueryTreeNode::ConvertToASTOptions & convert_to_ast_options);
 
+/// Extract table expressions from tree
+QueryTreeNodes extractTrueTableExpressions(const QueryTreeNodePtr & tree);
```
Comment (vdimir) [inline src/Analyzer/Utils.h:54]: It's not really clear what `True` refers to and what is the essential difference from `extractTableExpressions`, consider clarifying comment

File: src/Interpreters/InterpreterSelectQueryAnalyzer.cpp [hunk 2]
```diff
@@ -74,60 +75,28 @@ ContextMutablePtr buildContext(const ContextPtr & context, const SelectQueryOpti
...
-            }
-        }
-    }
+        auto & table_node = node->as<TableNode &>();
 
-    /// Don't replace storage if table name differs
-    if (auto * table_node = table_expression_to_replace->as<TableNode>(); table_node && table_node->getStorageID().getFullNameNotQuoted() != storage->getStorageID().getFullNameNotQuoted())
-        return;
+        /// Don't replace storage if table name differs
+        if (table_node.getStorageID().getFullNameNotQuoted() != storage->getStorageID().getFullNameNotQuoted())
```
Comment (vdimir) [inline src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:86]: Wouldn't it be better to compare `uuid`s? Though, it's difficult to imagine a case when comparing full names is a problem.

File: src/Interpreters/InterpreterSelectQueryAnalyzer.cpp [hunk 3]
```diff
@@ -74,60 +75,28 @@ ContextMutablePtr buildContext(const ContextPtr & context, const SelectQueryOpti
...
-        table_expression_modifiers = table_function_node->getTableExpressionModifiers();
-    else if (auto * identifier_node = table_expression_to_replace->as<IdentifierNode>())
-        table_expression_modifiers = identifier_node->getTableExpressionModifiers();
+        if (auto table_expression_modifiers = table_node.getTableExpressionModifiers())
+            replacement_table_expression->setTableExpressionModifiers(*table_expression_modifiers);
 
-    if (table_expression_modifiers)
-        replacement_table_expression->setTableExpressionModifiers(*table_expression_modifiers);
+        if (node->hasAlias())
+            replacement_table_expression->setAlias(node->getAlias() + "_replacement");
```
Comment (vdimir) [inline src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:95]: Why do we need to add the suffix to alias?

**Review by vdimir — COMMENTED** [review]
Do we have a tests dedicated to this specific case? If not it's worth adding

File: src/Analyzer/Utils.cpp [hunk 4]
```diff
@@ -326,6 +326,69 @@ void addTableExpressionOrJoinIntoTablesInSelectQuery(ASTPtr & tables_in_select_q
     }
 }
 
+QueryTreeNodes extractTrueTableExpressions(const QueryTreeNodePtr & tree)
+{
+    QueryTreeNodes result;
+
+    std::deque<QueryTreeNodePtr> nodes_to_process;
```
Comment (novikd) [inline src/Analyzer/Utils.cpp:333]: I don't think the order matters here. You can use just `std::vector`.

File: src/Analyzer/Utils.cpp [hunk 5]
```diff
@@ -326,6 +326,69 @@ void addTableExpressionOrJoinIntoTablesInSelectQuery(ASTPtr & tables_in_select_q
     }
 }
 
+QueryTreeNodes extractTrueTableExpressions(const QueryTreeNodePtr & tree)
```
Comment (novikd) [inline src/Analyzer/Utils.cpp:329]: Let's rename it to `extractAllTableReferences`.

File: src/Interpreters/InterpreterSelectQueryAnalyzer.cpp (hunk 3 above)
Comment (novikd) [reply src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:95]: It'll be set to the alias of `node` anyway in `cloneAndReplace`. I don't think we need this line.

**Review by novikd — COMMENTED** [review]
In general LGTM. We need to finish it ASAP.

**Comment by novikd** [comment]
I pushed some changes after the review. Let's merge this PR if CI doesn't find any issues. I don't think full table name vs UUID comparison is a stopper here.

File: src/Analyzer/Utils.cpp [hunk 6]
```diff
@@ -326,6 +326,69 @@ void addTableExpressionOrJoinIntoTablesInSelectQuery(ASTPtr & tables_in_select_q
...
+            case QueryTreeNodeType::UNION:
+            {
+                for (const auto & union_node : node_to_process->as<UnionNode>()->getQueries().getNodes())
+                    nodes_to_process.push_back(union_node);
+                break;
+            }
+            case QueryTreeNodeType::TABLE_FUNCTION:
+            {
+                for (const auto & argument_node : node_to_process->as<TableFunctionNode>()->getArgumentsNode()->getChildren())
+                    nodes_to_process.push_back(argument_node);
```
Comment (novikd) [inline src/Analyzer/Utils.cpp:364]: I suspect that tests fail because it's incorrect. There are no TableNodes in the table function arguments. There can be QueryNodes but they are unresolved, we can't do anything with them.
