### PR TITLE
Fix abort in `WriteBufferValidUTF8`

### LINKED ISSUE #83514: JSONColumns with output_format_json_validate_utf8 crash
### Describe the bug

This is a regression since v24.11

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/d5b318d2-569e-4395-8829-0db50a40b418

### Error message and/or stacktrace

Stack trace is long. It's a uncaught exception: https://pastila.nl/?000cba97/28f0daeb625771887bb3a20090b5a3dc#PDTzh0T+53FLdOfGpdjp+Q==

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix abort in `WriteBufferValidUTF8`. This closes #83514.

@CheSema, @alesapin, this might not be the best fix, but I wonder why we ignored a bug report for a whole week.

### CODE REVIEW

File: src/IO/WriteBufferValidUTF8.cpp [hunk 1]
```diff
@@ -142,7 +142,16 @@ void WriteBufferValidUTF8::nextImpl()
 WriteBufferValidUTF8::~WriteBufferValidUTF8()
 {
     if (!canceled)
-        finalize();
+    {
+        try
+        {
+            finalize();
```
Comment (CheSema) [inline src/IO/WriteBufferValidUTF8.cpp:148]: We should not call finalize in d-tor. Please make a propper fix. Or at least do not hide the issue with fast fixing.
