### PR TITLE
Fix `heap-use-after-free` in create with constraints

### LINKED ISSUE #96660: ThreadSanitizer (STID: 3836-4234)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: ThreadSanitizer (STID: 3836-4234)
CI report: [BuzzHouse (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=96110&sha=c80d7d46a60c541c51c35938a39d9caea394926f&name_0=PR&name_1=BuzzHouse%20%28amd_tsan%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdUaHJlYWRTYW5pdGl6ZXIgKFNUSUQ6IDM4MzYtNDIzNCknCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdCdXp6SG91c2UgKGFtZF90c2FuKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBiYXNlX3JlZiBJTiAoJ21hc3RlcicpKQogICAgLS0gQU5EIHRlc3RfY29udGV4dF9yYXcgTElLRSAnJXBhdHRlcm4lJyAgLS0gdW5jb21tZW50IGFuZCBlZGl0IHRvIGZpbHRlciBieSBmYWlsdXJlIHBhdHRlcm4KR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
Error:
WARNING: ThreadSanitizer: heap-use-after-free (pid=631)
  Read of size 8 at 0x72240021e010 by thread T7:
---

Stack trace:
#0 __cxxabiv1::(anonymous namespace)::dyn_cast_get_derived_info(__cxxabiv1::(anonymous namespace)::derived_object_info*, void const*) ci/tmp/build/./contrib/llvm-project/libcxxabi/src/private_typeinfo.cpp:119:32 (clickhouse+0x320b9f30) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#1 __dynamic_cast ci/tmp/build/./contrib/llvm-project/libcxxabi/src/private_typeinfo.cpp:915:5 (clickhouse+0x320b9f30)
#2 DB::ASTConstraintDeclaration::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const ci/tmp/build/./src/Parsers/ASTConstraintDeclaration.cpp:29:28 (clickhouse+0x27ac3c44) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#3 DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&) const ci/tmp/build/./src/Parsers/IAST.h:317:9 (clickhouse+0xd9bece2) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#4 DB::IAST::formatWithPossiblyHidingSensitiveData(unsigned long, bool, bool, bool, DB::IdentifierQuotingRule, DB::IdentifierQuotingStyle) const ci/tmp/build/./src/Parsers/IAST.cpp:203:5 (clickhouse+0x27bb6319) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#5 DB::IAST::formatWithSecretsOneLine() const ci/tmp/build/./src/Parsers/IAST.cpp:231:12 (clickhouse+0x27bb65f4) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#6 DB::TreeRewriterResult::collectUsedColumns(boost::intrusive_ptr<DB::IAST> const&, bool, bool) ci/tmp/build/./src/Interpreters/TreeRewriter.cpp:1237:48 (clickhouse+0x20635ef3) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#7 DB::TreeRewriter::analyze(boost::intrusive_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::IStorage const>, std::__1::shared_ptr<DB::StorageSnapshot> const&, bool, bool, bool, bool) const ci/tmp/build/./src/Interpreters/TreeRewriter.cpp:1556:25 (clickhouse+0x206447da) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#8 DB::InterpreterCreateQuery::getConstraintsDescription(DB::ASTExpressionList const*, DB::ColumnsDescription const&, std::__1::shared_ptr<DB::Context const>) ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:730:41 (clickhouse+0x20138f03) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#9 DB::InterpreterCreateQuery::getTablePropertiesAndNormalizeCreateQuery(DB::ASTCreateQuery&, DB::LoadingStrictnessLevel) ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:797:34 (clickhouse+0x20139e69) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#10 DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:1663:34 (clickhouse+0x20147c6c) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#11 DB::InterpreterCreateQuery::execute() ci/tmp/build/./src/Interpreters/InterpreterCreateQuery.cpp:2437:12 (clickhouse+0x2015c243) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#12 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer>>&, boost::intrusive_ptr<DB::IAST>&, std::__1::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::__1::function<void ()>, DB::QueryResultDetails&) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1736:40 (clickhouse+0x20715832) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#13 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1964:11 (clickhouse+0x2070e3eb) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#14 DB::TCPHandler::runImpl() ci/tmp/build/./src/Server/TCPHandler.cpp:788:68 (clickhouse+0x2639c403) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#15 DB::TCPHandler::run() ci/tmp/build/./src/Server/TCPHandler.cpp:2890:9 (clickhouse+0x263cc967) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#16 Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3 (clickhouse+0x2edb2222) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#17 Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:42 (clickhouse+0x2edb2b29) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#18 Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14 (clickhouse+0x2ed14c82) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#19 Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x2ed12d6f) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
#20 Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:341:27 (clickhouse+0x2ed11009) (BuildId: 758a563d509b95d702c2138560c7d4dae4cd0da3)
```

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed `heap-use-after-free` in `CREATE TABLE` with constraints.

Closes: #96660

### Version info
- Merged into: `26.2.1.631`
- Backported to: `26.1.3.43`

### CODE REVIEW

File: src/Interpreters/InDepthNodeVisitor.h [hunk 1]
```diff
@@ -89,7 +89,14 @@ class InDepthNodeVisitor
                 need_visit_child = Matcher::needChildVisit(ast, child);
 
             if (need_visit_child)
+            {
+                IAST * old_ptr = child.get();
```
Comment (nickitat) [inline src/Interpreters/InDepthNodeVisitor.h:93]: Direct copy-paste of the logic `ReplaceQueryParameterVisitor::visitChildren` implements.

**Review by yariks5s — APPROVED** [review]
