### PR TITLE
Make use of `ALTER_MOVE_PARTITION` access type.

### LINKED ISSUE #16403: RBAC - ALTER MOVE PARTITION privilege does nothing
**Describe the bug**
In order to execute `ALTER TABLE table0 MOVE PARTITION 1 TO TABLE table1` user is required to have `SELECT` and `ALTER DELETE` on table0 and `INSERT` on table1. The privilege `ALTER MOVE PARTITION` is not required and granting it doesn't permit the user to execute the statement.

**How to reproduce**
ClickHouse server version 20.10.1 revision 54440

* Queries to run that lead to unexpected result
```
ClickHouse client version 20.10.1.1.
Connecting to localhost:9000 as user user0.
Connected to ClickHouse server version 20.10.1 revision 54440.

clickhouse1 :) ALTER TABLE table0 MOVE PARTITION 1 TO TABLE table1

ALTER TABLE table0
    MOVE PARTITION 1 TO TABLE table1


Ok.

0 rows in set. Elapsed: 0.002 sec.
```
```
clickhouse1 :) show grants for user0

SHOW GRANTS FOR user0

┌─GRANTS FOR user0──────────────────────────────────────┐
│ GRANT INSERT ON default.table1 TO user0               │
│ GRANT SELECT, ALTER DELETE ON default.table0 TO user0 │
└───────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.002 sec.
```

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Historically for some reason, the query `ALTER TABLE MOVE PARTITION TO TABLE` checked `SELECT` and `ALTER DELETE` rights instead of dedicated `ALTER_MOVE_PARTITION`. This PR makes use of this access type. 
For compatibility, this permission is also will be granted implicitly if `SELECT` and `ALTER DELETE` are granted, but this behavior will be removed in future releases.
Closes https://github.com/ClickHouse/ClickHouse/issues/16403

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit cf86df99660fb8ad28f719d532a6578bb7eec9fe with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71632/cf86df99660fb8ad28f719d532a6578bb7eec9fe/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/6e566dd5f3d43ce67a4c1ecfbaf5bf4b541a1040/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Access/ContextAccess.cpp [hunk 1]
```diff
@@ -168,6 +168,12 @@ AccessRights ContextAccess::addImplicitAccessRights(const AccessRights & access,
             res |= show_databases;
         }
 
+        static const AccessFlags alter_delete = AccessType::ALTER_DELETE;
+        static const AccessFlags select = AccessType::SELECT;
+        static const AccessFlags move_partition = AccessType::ALTER_MOVE_PARTITION;
+        if ((res & alter_delete) && (res & select) && level <= 2)
```
Comment (jkartseva) [inline src/Access/ContextAccess.cpp:174]: Is the new `level <= 2` requirement backward compatible?

**Review by jkartseva — APPROVED** [review]
Sorry for the late review, the change LGTM. Should there be a test?

**Comment by pufit** [comment]
> Should there be a test

It's actually already well-tested functionality, but I'll make another one just in case.

File: src/Access/ContextAccess.cpp (hunk 1 above)
Comment (pufit) [reply src/Access/ContextAccess.cpp:174]: No, the `ALTER_MOVE_PARTITION` grant can be granted only on a database (level=1) or table (level=2). It can't be granted on a column
