### PR TITLE
Fix INCOMPATIBLE_TYPE_OF_JOIN for Join storage 

### LINKED ISSUE #80794: INCOMPATIBLE_TYPE_OF_JOIN with filter pushdown to Engine Join and analyzer enabled
### Company or project name

found in telegram

### Describe the unexpected behaviour

Works without the analyzer

```
create or replace table users (uid UInt64, name String, age UInt8)
  engine = Join(ALL, LEFT, uid);
create or replace table events (uid UInt64, user_id UInt64, message String)
  engine = Memory;

insert into users values
  (1, 'John', 33),
  (2, 'Ksenia', 48),
  (3, 'Alice', 50)
;

insert into events values
  (1, 1, 'hello'),
  (2, 2, 'hello world!')
;

--set enable_analyzer = 0;
  
select
  event.message,
  user.name,
  user.age
from events event
left join users user on event.user_id = user.uid
 where user.uid > 0
;

DB::Exception: Table 'default.users has incompatible type of JOIN. (INCOMPATIBLE_TYPE_OF_JOIN)

```

https://fiddle.clickhouse.com/fc713194-7a02-4deb-ae68-9a3e32b4ffc0

### Which ClickHouse versions are affected?

25.5

### How to reproduce

above

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix INCOMPATIBLE_TYPE_OF_JOIN error for Join storage and outer to inner join optimization applied. Resolves #80794

### CODE REVIEW

**Review by nickitat — APPROVED** [review]

File: src/Processors/QueryPlan/Optimizations/convertOuterJoinToInnerJoin.cpp [hunk 1]
```diff
@@ -180,7 +180,7 @@ size_t tryConvertOuterJoinToInnerJoin(QueryPlan::Node * parent_node, QueryPlan::
     auto & join_operator = join->getJoinOperator();
     if (join_operator.strictness == JoinStrictness::Any)
         return tryConvertAnyOuterJoinToInnerJoin(filter, child_node, join);
-    if (join_operator.strictness != JoinStrictness::All)
+    if (join_operator.strictness != JoinStrictness::All || !join->typeChangingSides().empty() || join->hasPreparedJoinStorage())
```
Comment (vdimir) [inline src/Processors/QueryPlan/Optimizations/convertOuterJoinToInnerJoin.cpp]:
```suggestion
    if (join_operator.strictness != JoinStrictness::All)
```

**Comment by vdimir** [comment]
> 03640_load_marks_synchronously 	FAIL 		IGNORED

https://github.com/ClickHouse/ClickHouse/issues/92537

**Comment by clickgapai** [comment]
Hi @vdimir @nickitat — while reviewing this PR I found the following:

- **Bug (P1):** `tryConvertAnyJoinToSemiOrAntiJoin` missing Storage Join guard causes `INCOMPATIBLE_TYPE_OF_JOIN` — https://github.com/ClickHouse/ClickHouse/issues/103318

Happy to discuss — close anything that's wrong or already addressed.
