### PR TITLE
Fix rare bug in `DROP COLUMN` and enabled sparse columns

### LINKED ISSUE #50434: 992: Found unexpected column {} in serialization infos (CORRUPTED_DATA)
https://s3.amazonaws.com/clickhouse-test-reports/0/a44c00c9265a8573a78152a316c6099c3f6cdd68/stateless_tests__ubsan__[2_2].html

```
2023-06-01 14:23:46 00992_system_parts_race_condition_zookeeper_long:                       [ FAIL ] 319.41 sec. - having stderror: 
2023-06-01 14:23:46 [390a28ff213f] 2023.06.01 14:23:44.877243 [ 124318 ] {7f7fe964-8b4c-430e-8e61-aaba1eb161ef} <Error> InterpreterSystemQuery: SYNC REPLICA test_t63y4tr4.alter_table0 (b64a0612-c91e-4fa3-acd4-f54f0ee1cfdd): Timed out!
...
2023-06-01 14:23:46 sync failed, queue:	default	alter_table0	r1	0	queue-0000000445	MUTATE_PART	2023-06-01 14:18:33	0	r2	-2_0_22_1_41	['-2_0_22_1_36']	0	0	546	Code: 246. DB::Exception: Found unexpected column \'h\' in serialization infos. (CORRUPTED_DATA), Stack trace (when copying this message, always include the lines below):\n\n0. std::exception::capture() @ 0x000000002af0cd55 in /usr/bin/clickhouse\n1. ./build_docker/./base/poco/Foundation/src/Exception.cpp:28: Poco::Exception::Exception(String const&, int) @ 0x0000000048a46405 in /usr/bin/clickhouse\n2. ./build_docker/./src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000003759f56b in /usr/bin/clickhouse\n3. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000002b6523a7 in /usr/bin/clickhouse\n4. ./build_docker/./src/DataTypes/Serializations/SerializationInfo.cpp:286: DB::SerializationInfoByName::readJSON(DB::NamesAndTypesList const&, DB::SerializationInfo::Settings const&, DB::ReadBuffer&) @ 0x0000000043e43c55 in /usr/bin/clickhouse\n5. ./build_docker/./contrib/llvm-project/libcxx/include/__tree:1729: DB::IMergeTreeDataPart::loadColumns(bool) @ 0x000000004681a8d0 in /usr/bin/clickhouse\n6. ./build_docker/./src/Storages/MergeTree/IMergeTreeDataPart.cpp:626: DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x0000000046818be8 in /usr/bin/clickhouse\n7. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:815: DB::MergeTreeData::cloneAndLoadDataPartOnSameDisk(std::shared_ptr<DB::IMergeTreeDataPart const> const&, String const&, DB::MergeTreePartInfo const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::MergeTreeTransaction> const&, DB::MergeTreeData::HardlinkedFiles*, bool, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&) @ 0x00000000469cb966 in /usr/bin/clickhouse\n8. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:815: DB::MutateTask::prepare() @ 0x0000000046c87962 in /usr/bin/clickhouse\n9. ./build_docker/./src/Storages/MergeTree/MutateTask.cpp:1667: DB::MutateTask::execute() @ 0x0000000046c827c1 in /usr/bin/clickhouse\n10. ./build_docker/./src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:0: DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x0000000046d000bb in /usr/bin/clickhouse\n11. ./build_docker/./src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:0: DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000046cfdc81 in /usr/bin/clickhouse\n12. ./build_docker/./src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:185: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x000000004690b57d in /usr/bin/clickhouse\n13. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000004690d07f in /usr/bin/clickhouse\n14. ./build_docker/./base/base/../base/wide_integer_impl.h:796: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x00000000376ef340 in /usr/bin/clickhouse\n15. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::\'lambda0\'()>(void&&)::\'lambda\'()::operator()() @ 0x00000000376f478f in /usr/bin/clickhouse\n16. ./build_docker/./base/base/../base/wide_integer_impl.h:796: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x00000000376ec200 in /usr/bin/clickhouse\n17. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::\'lambda0\'()>>(void*) @ 0x00000000376f17ca in /usr/bin/clickhouse\n18. ? @ 0x00007f9b1bb0b609 in ?\n19. clone @ 0x00007f9b1ba30133 in ?\n (version 23.5.1.1 (official build))	2023-06-01 14:23:44	2023-06-01 14:23:44	0		1970-01-01 01:00:00	
2023-06-01 14:23:46 Failed to sync some replicas
```

CI DB: [link](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMDk5Ml9zeXN0ZW1fcGFydHNfcmFjZV9jb25kaXRpb25fem9va2VlcGVyX2xvbmcnIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpIGFuZCB0ZXN0X2NvbnRleHRfcmF3IGxpa2UgJyVUaW1lZCBvdXQhJScKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

Probably was introduced in https://github.com/ClickHouse/ClickHouse/pull/49660

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes #50434.

### CODE REVIEW

File: src/Storages/MergeTree/MutateTask.cpp [hunk 1]
```diff
@@ -292,13 +298,15 @@ getColumnsForNewDataPart(
...
         auto it = renamed_columns_from_to.find(name);
         auto new_name = it == renamed_columns_from_to.end() ? name : it->second;
 
-        if (!updated_header.has(new_name))
+        if (!storage_columns_set.contains(new_name))
+            continue;
+
+        /// In compact part we read all columns and all of them are in @updated_header.
+        /// But in wide part we must keep serialization infos for columns that are not touched by mutation.
+        if (!updated_header.has(new_name) && isWidePart(source_part))
```
Comment (CurtizJ) [inline src/Storages/MergeTree/MutateTask.cpp:309]: The issue is that sometimes column may be dropped implicitly by another mutation (see https://github.com/ClickHouse/ClickHouse/blob/c2a5318df4a91678850cf8f493e75728264cf139/src/Storages/MergeTree/MutateTask.cpp#L158-L164). Previously it wasn't accounted in serialization infos.

**Comment by CurtizJ** [comment]
The test is not mandatory because this case is covered by test `00992_system_parts_race_condition_zookeeper_long` with random settings.

**Comment by robot-ch-test-poll3** [comment]
This is an automated comment for commit ede63a0f4e8239c56999a72bfe3af3f59e63dfb2 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51809/ede63a0f4e8239c56999a72bfe3af3f59e63dfb2/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]
