### PR TITLE
Fix lgamma negative integers

### LINKED ISSUE #70518: lgamma wrong result with negative integers
```sql
SELECT lgamma(-1)
```

latest (24.9.2.42) output:
```
37.78343889855838
```

24.10.1.1198 with asan:
```
inf
```

Expected result:
NaN or an error since the gamma function is not defined for negative integers.

### PR DESCRIPTION
**Pull request by IlyaKataev**
This closes #70518.
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix lgamma function behavior for negative integers.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Functions/lgamma.cpp [hunk 1]
```diff
@@ -16,6 +16,9 @@ namespace
 /// Use wrapper and use lgamma_r version because std::lgamma is not threadsafe.
 Float64 lgamma_wrapper(Float64 arg)
 {
+    if (arg < 0 && arg == std::floor(arg))
```
Comment (jsc0218) [inline src/Functions/lgamma.cpp:19]: May I know why `arg == std::floor(arg)`?

Comment (IlyaKataev) [reply src/Functions/lgamma.cpp:19]: A number is an integer if and only if it is equal to its floor value. This works for all double values, even for large numbers that don’t fit into int64.
