### PR TITLE
Fix possible logical error in cache if `do_not_evict_index_and_mrk_files=1`

### LINKED ISSUE #42142: Filesystem cache setting `do_not_evict_index_and_mark_files` results in logical error
ClickHouse version 22.9.3.18 (official build)

The cache is defined like this:

```xml
      <fs_cache>
        <type>cache</type>
        <disk>webdisk</disk>
        <path>/var/lib/clickhouse/storagebox-cache/</path>
        <max_size>17179869184</max_size>
        <do_not_evict_index_and_mark_files>1</do_not_evict_index_and_mark_files>
      </fs_cache>
```

The error I am getting when executing some queries:

```
2022.10.07 09:53:44.100082 [ 111428 ] {23442c6f-0702-484b-abb5-f2c54603097b} <Error> executeQuery: Code: 49. DB::Exception: File path does not exist, but file has DOWNLOADED state. File segment: [26203, 28233], key: 14e3daa144f0065af3d19680cd97e06f, state: DOWNLOADED, downloaded size: 2031, reserved size: 2031, downloader id: None, current write offset: 28234, first non-downloaded offset: 28234, caller id: 23442c6f-0702-484b-abb5-f2c54603097b:111529, detached: 0, persistent: 0: Cache info: . (LOGICAL_ERROR) (version 22.9.3.18 (official build)) (from [::ffff:10.0.1.1]:57090) (in query: STRIPPED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d627a in /usr/bin/clickhouse
1. ? @ 0x79fe658 in /usr/bin/clickhouse
2. DB::FileCache::useCell(DB::FileCache::FileSegmentCell const&, std::__1::list<std::__1::shared_ptr<DB::FileSegment>, std::__1::allocator<std::__1::shared_ptr<DB::FileSegment> > >&, std::__1::lock_guard<std::__1::mutex>&) @ 0x123a5dfd in /usr/bin/clickhouse
3. DB::FileCache::getImpl(DB::FileCacheKey const&, DB::FileSegment::Range const&, std::__1::lock_guard<std::__1::mutex>&) @ 0x123a63b9 in /usr/bin/clickhouse
4. DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&) @ 0x123a7ac0 in /usr/bin/clickhouse
5. DB::CachedOnDiskReadBufferFromFile::initialize(unsigned long, unsigned long) @ 0x115d2761 in /usr/bin/clickhouse
6. DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x115d990b in /usr/bin/clickhouse
7. DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x115d972c in /usr/bin/clickhouse
8. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x113205b8 in /usr/bin/clickhouse
9. DB::CompressedReadBufferFromFile::nextImpl() @ 0x1132298e in /usr/bin/clickhouse
10. ? @ 0x7916813 in /usr/bin/clickhouse
11. DB::MergeTreeIndexGranuleBloomFilter::deserializeBinary(DB::ReadBuffer&, unsigned char) @ 0x12ba8080 in /usr/bin/clickhouse
12. DB::MergeTreeDataSelectExecutor::filterMarksUsingIndex(std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::shared_ptr<DB::IMergeTreeIndexCondition>, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&, unsigned long&, unsigned long&, DB::MarkCache*, DB::UncompressedCache*, Poco::Logger*) @ 0x12b7f74c in /usr/bin/clickhouse
13. ? @ 0x12b7c122 in /usr/bin/clickhouse
14. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x797c1ec in /usr/bin/clickhouse
15. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x797ef17 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x797872c in /usr/bin/clickhouse
17. ? @ 0x797de3e in /usr/bin/clickhouse
18. ? @ 0x7fc35d832b43 in ?
19. ? @ 0x7fc35d8c4a00 in ?
```

The same query works once when I drop the cache with `SYSTEM DROP FILESYSTEM CACHE`.  But executing the query with ` SETTINGS enable_filesystem_cache = 0` does not help.

Disabling the filesystem cache completely via removing storage policy also works.

The table has a bloom filter (`DB::MergeTreeIndexGranuleBloomFilter` in stacktrace).

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible logical error in cache if `do_not_evict_index_and_mrk_files=1`. Closes https://github.com/ClickHouse/ClickHouse/issues/42142.

### CODE REVIEW

File: src/Interpreters/Cache/FileCache.cpp [hunk 1]
```diff
@@ -1107,8 +1107,10 @@ void FileCache::reduceSizeToDownloaded(
             file_segment->getInfoForLogUnlocked(segment_lock));
     }
 
+    CreateFileSegmentSettings create_settings{ .is_persistent = file_segment->is_persistent };
```
Comment (kssenii) [inline src/Interpreters/Cache/FileCache.cpp:1110]: The fix is in this line.

**Review by vdimir — APPROVED** [review]
