### PR TITLE
Fix capture of nested lambda.

### LINKED ISSUE #62036: Memory limit exceeded with new analyzer
Hello!
I prepared a minimal reproducible example of the problem (tested on 24.3.1.2672):
```sql
WITH
    groupArray(count) AS counts,
    arrayMap(x -> (x + 1), counts) AS some_metric,
    arrayMap(x -> (x / arraySum(some_metric)), some_metric) AS res
SELECT arrayJoin(res) AS result
FROM
(
    SELECT *
    FROM generateRandom('count UInt8')
    LIMIT 1000000
)
FORMAT `Null`
SETTINGS allow_experimental_analyzer = 0
```
```
0 rows in set. Elapsed: 0.045 sec. Processed 1.31 million rows, 1.31 MB (29.08 million rows/s., 29.08 MB/s.)
Peak memory usage: 16.75 MiB.
```

But new analyzer needs a way more RAM to handle the same query:
```sql
WITH
    groupArray(count) AS counts,
    arrayMap(x -> (x + 1), counts) AS some_metric,
    arrayMap(x -> (x / arraySum(some_metric)), some_metric) AS res
SELECT arrayJoin(res) AS result
FROM
(
    SELECT *
    FROM generateRandom('count UInt8')
    LIMIT 1000000
)
FORMAT `Null`
SETTINGS allow_experimental_analyzer = 1
```
```
Elapsed: 0.023 sec. 

Received exception from server (version 24.3.1):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception:
Memory limit (total) exceeded: would use 932.93 GiB (attempt to allocate chunk of 1000003273111 bytes), maximum: 27.93 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.: while executing 'FUNCTION arrayMap(__lambda_8141180715573801285_17054877471657376131 :: 2, arrayMap(__lambda_14042983518542017256_6366473326654511736, groupArray(__table1.count)) :: 1) -> arrayMap(__lambda_8141180715573801285_17054877471657376131, arrayMap(__lambda_14042983518542017256_6366473326654511736, groupArray(__table1.count))) Array(Float64) : 0'. (MEMORY_LIMIT_EXCEEDED)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix excessive memory usage for queries with nested lambdas. Fixes #62036

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 8a172003ce280c6bd262302408e139325ccdb8bc with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62462/8a172003ce280c6bd262302408e139325ccdb8bc/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by nikitamikhaylov** [comment]
What about this query? 
```
SELECT
  arrayWithConstant(pow(10,6), 1) AS nums,
  arrayMap(x -> x, nums) AS m,
  arrayMap(x -> x + arraySum(m), m) AS res
```

File: src/Planner/PlannerActionsVisitor.cpp [hunk 1]
```diff
@@ -500,7 +501,39 @@ class PlannerActionsVisitorImpl
...
+        size_t max() const { return 63 - __builtin_clzll(mask); }
+
+    private:
+        uint64_t mask = 0;
+
+        void check(size_t level)
+        {
+            if (level >= 63)
+                throw Exception(ErrorCodes::INCORRECT_QUERY, "Maximum lambda depth exceeded. Maximum 63.");
+        }
```
Comment (antaljanosbenjamin) [inline src/Planner/PlannerActionsVisitor.cpp:533]: Shouldn't this be `level > 63`? I think 63 should be possible (`1 << 63` is valid), and as far as I understood the exception message also suggests that (maximum 63, maximum is exceeded => bigger than 63).

**Review by novikd — APPROVED** [review]
LGTM

File: src/Planner/PlannerActionsVisitor.cpp [hunk 2]
```diff
@@ -510,26 +510,31 @@ class PlannerActionsVisitorImpl
...
+            if (level)
+                mask &= ~(uint64_t(1) << (level - 1));
         }
 
         void add(Levels levels) { mask |= levels.mask; }
 
-        size_t max() const { return 63 - __builtin_clzll(mask); }
+        size_t max() const
+        {
+            return mask ? (64 - __builtin_clzll(mask)) : 0;
```
Comment (antaljanosbenjamin) [inline src/Planner/PlannerActionsVisitor.cpp:528]: Now, as you changed the range level can be `0` (previously I think it was at least 1) I think we should change `__builtin_clzll` to `getLeadingZeroBits` as the return value is undefined in case of  `mask == 0`

Comment (KochetovNicolai) [reply src/Planner/PlannerActionsVisitor.cpp:528]: but I check that mask != 0 ... but ok, it looks simplier

Comment (antaljanosbenjamin) [reply src/Planner/PlannerActionsVisitor.cpp]: Ah sorry, you are right.

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Stateless tests (ubsan)  : https://github.com/ClickHouse/ClickHouse/pull/62287
