### PR TITLE
fix DataTypeAggregateFunction deserialization

### LINKED ISSUE #6575: SQL parsing exception on worker node if the outer query is against distributed table and the scalar subquery contains bitmap function
(you don't have to strictly follow this form)

**Describe the bug**
I have a Clickhouse cluster, with distributed table `dist_cdp_orders_partition_by_day`, and local table `cdp_cust_tag_yzc`, `cdp_orders_partition_by_day`. I open clickhouse-client, connect to 10.126.144.141, issue following SQL:

```
-- ok!
SELECT toDate(order_complete_time) AS day, sum(order_total_sales) AS amount FROM cdp_orders_partition_by_day WHERE bitmapContains((SELECT groupBitmapState(mid_seq) FROM dist_cdp_cust_tag_yzc WHERE gender='男'), mid_seq) GROUP BY day ORDER BY day;

-- error! 
SELECT toDate(order_complete_time) AS day, sum(order_total_sales) AS amount FROM dist_cdp_orders_partition_by_day WHERE bitmapContains((SELECT groupBitmapState(mid_seq) FROM cdp_cust_tag_yzc WHERE gender='男'), mid_seq) GROUP BY day ORDER BY day;
↘ Progress: 279.46 million rows, 1.12 GB (408.36 million rows/s., 1.63 GB/s.)  96%Received exception from server (version 19.11.3):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Received from 10.126.144.147:9000. DB::Exception: Syntax error: failed at position 186: '\\\0\0up\00|\0Yz\0B~\0&�\0��\t\0��\n\0[n\0n\0�\0�\0cr\0�\0<\0�5\0h=\0����ېN��u�z!�7��J�pL�TV�?��G��0����Ժ����. Expected one of: NOT, BETWEEN, AND, alias, AS, OR, NOT LIKE, LIKE, GLOBAL IN, IN, GLOBAL NOT IN, NOT IN, Comma, QuestionMark, IS, token. 
```

The attached 9000.pcap is the capture on host 10.126.144.147 tcp port 9000. The TCP stream indicates that 10.126.144.147 failed to parse the SQL which 10.126.144.141 sent. It was clear that the the bitmap binary in the SQL caused the parsing exception.

* Which ClickHouse server version to use
ClickHouse server version 19.11.3.11, on CentOS 7
* Which interface to use, if matters
clickhouse CLI, version 19.11.3.11

**Error message and/or stacktrace**
Screenshot_2019-08-20_23-52-53

### PR DESCRIPTION
**Pull request by yuzhichang**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Category (leave one):
- Bug Fix

Short description (up to few sentences):
Try to fix [6575](https://github.com/yandex/ClickHouse/issues/6575).
I have to enlarge DEFAULT_MAX_STRING_SIZE in dbms/src/IO/ReadHelpers.h, and max_query_size in users.xml.

### CODE REVIEW

File: dbms/src/IO/ReadHelpers.h [hunk 1]
```diff
@@ -39,7 +39,7 @@
 #endif
 
 
-#define DEFAULT_MAX_STRING_SIZE 0x00FFFFFFULL
+#define DEFAULT_MAX_STRING_SIZE 0x3FFFFFFFULL
```
Comment (alexey-milovidov) [inline dbms/src/IO/ReadHelpers.h]: Missing comment here. Why 3F, how it is motivated?

**Comment by alexey-milovidov** [comment]
Ok. But test is missing.
Could you please make a simple functional test
(it can involve `remote('127.0.0.{2,3}', ...` to emulate distributed queries, see examples around; it should contain `shard` in it's name as a tag that it performs distributed query)

File: dbms/src/IO/ReadHelpers.h (hunk 1 above)
Comment (yingfeng) [reply dbms/src/IO/ReadHelpers.h]: The intermediate state of bitmap is also contained within the query to be transferred among nodes, it's very easy to exceed the original 16MB size for a bitmap state and it would be cut leading to parsing exception.

**Comment by yuzhichang** [comment]
@alexey-milovidov I don't understand how `remote('127.0.0.{2,3}', ... to emulate distributed queries` work. Could you provide document or code link?

File: dbms/src/IO/ReadHelpers.h (hunk 1 above)
Comment (yuzhichang) [reply dbms/src/IO/ReadHelpers.h]: bitmap serialization writes each UInt32 as 4 bytes, and become at most 8 bytes when escaped. 0x3FFFFFFFULL can cover at least (2^30)/8=125M UInt32 integers.
We could reduce bitmap serialization size by using the official CRoaring serialization. This also could help to improve bitmap serialization/deserialization performance.

Comment (alexey-milovidov) [reply dbms/src/IO/ReadHelpers.h]: Ok.

> This also could help to improve bitmap serialization/deserialization performance.

It will be appreciated if you can implement it with backwards compatibility.

**Comment by alexey-milovidov** [comment]
> The log indicates that the standalone node receives the query which aim to 127.0.0.2, without listening on 127.0.0.2.

We run ClickHouse that listen to `::` (everything) to run tests with `shard` tag.
