### PR TITLE
tests: fix flakiness of tests for system.filesystem_cache

### LINKED ISSUE #75876: filesystem cache tests are flaky
### Tests

- 02286_drop_filesystem_cache
- 02240_system_filesystem_cache_table
- 02240_filesystem_query_cache
- 02241_filesystem_cache_on_write_operations - https://s3.amazonaws.com/clickhouse-test-reports/75763/6e1052f7efe8009d1dcfd76cb28f75516740cb1a/stateless_tests__tsan__1_3_.html

CI DB - https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSB0ZXN0X25hbWUgTElLRSAnJTAyMjQwX2ZpbGVzeXN0ZW1fcXVlcnlfY2FjaGUlJwogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCAyNCBkYXkKICAgIEFORCAoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgc3RhcnRzV2l0aChoZWFkX3JlcG8sICdDbGlja0hvdXNlLycpKQogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EICh0ZXN0X3N0YXR1cyBMSUtFICdGJScgT1IgdGVzdF9zdGF0dXMgTElLRSAnRSUnKSAKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCk9SREVSIEJZIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgY2hlY2tfc3RhcnRfdGltZQ== (even more if not only in master)

CI - https://s3.amazonaws.com/clickhouse-test-reports/75849/a14e0fe3d9d30cb63a5dd850511ce63354e8f20d/stateless_tests__tsan__2_3_.html

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The problem is that some entries can be locked, i.e. due to merges, so let's:
- disable merges for the tables that can cause this
- add retries for `SYSTEM DROP FILESYSTEM CACHE` into all tests that query `system.filesystem_cache` w/o extra filters (i.e. by `key`)

Fixes: https://github.com/ClickHouse/ClickHouse/issues/75876

### CODE REVIEW

File: tests/docker_scripts/stateless_runner.sh [hunk 1]
```diff
@@ -243,6 +243,10 @@ function prepare_stateful_data() {
             ENGINE = CollapsingMergeTree(Sign) PARTITION BY toYYYYMM(StartDate) ORDER BY (CounterID, StartDate, intHash32(UserID), VisitID)
             SAMPLE BY intHash32(UserID) SETTINGS index_granularity = 8192, storage_policy='s3_cache'"
 
+        # Avoid locking filesystem cache
+        clickhouse-client --query "SYSTEM STOP MERGES test.hits"
```
Comment (kssenii) [inline tests/docker_scripts/stateless_runner.sh:247]: I'd rather not stop merges, but use a its own cache for tests which fail if it actually does not matter for the test (there are tests which on purpose use a common cache to generate more load/concurrency with it). In this exact case for tests which were modified in this PR it does not matter.

**Review by alexey-milovidov — APPROVED** [review]

File: tests/docker_scripts/stateless_runner.sh (hunk 1 above)
Comment (kssenii) [reply tests/docker_scripts/stateless_runner.sh:247]: > 02286_drop_filesystem_cache assumes that there will be no cache entries after SYSTEM DROP FILESYSTEM CACHE, but, due to very slow merges for test.hits some entries has not been removed since they are still in use.

yes, but there is no need to use the same cache object in test `02286_drop_filesystem_cache` as for `test.hits`, so with independent caches we do not care about slow merges of `test.hits`. `system.filesystem_cache` has a `name` columns, which is a name of the cache, so we can check only a specific cache in `02286_drop_filesystem_cache`, so `test.hits` will not have any impact on it.
