### PR TITLE
Fix bloom filters for String (data skipping indices)

### LINKED ISSUE #11634: Bloom filter issue
```
CREATE TABLE br_test ( `id` UInt64, `val` String, INDEX ind val TYPE bloom_filter() GRANULARITY 1 ) ENGINE = MergeTree() ORDER BY id SETTINGS index_granularity = 2;

INSERT INTO br_test (id, val) select number as id, toString(number) as val from numbers(100);

SELECT count() FROM br_test WHERE identity(val) = '50';

-- 1 

SELECT count() FROM br_test WHERE val = '50';

-- 0 !!!
```

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix bloom filters for String (data skipping indices)

Detailed description / Documentation draft:
bloom filter was broken for the first element, if all of the following
conditions satisfied:
- they are created on INSERT (in thie case bloom filter hashing uses
  offsets, in case of OPTIMIZE it does not, since it already has
  granulars).
- the record is not the first in the block
- the record is the first per index_granularity (do not confuse this
  with data skipping index GRANULARITY).
- type of the field for indexing is "String" (not FixedString)

Because in this case there was incorrect length and *data* for that string.

Fixes: #11634
Cc: @filimonov

### CODE REVIEW

File: src/Interpreters/BloomFilterHash.h [hunk 1]
```diff
@@ -196,18 +196,17 @@ struct BloomFilterHash
...
             const ColumnString::Offsets & offsets = index_column->getOffsets();
 
-            ColumnString::Offset current_offset = pos;
             for (size_t index = 0, size = vec.size(); index < size; ++index)
             {
+                ColumnString::Offset current_offset = offsets[index + pos - 1];
+                size_t length = offsets[index + pos] - current_offset - 1 /* terminating zero */;
                 UInt64 city_hash = CityHash_v1_0_2::CityHash64(
-                    reinterpret_cast<const char *>(&data[current_offset]), offsets[index + pos] - current_offset - 1);
+                    reinterpret_cast<const char *>(&data[current_offset]), length);
```
Comment (azat) [inline src/Interpreters/BloomFilterHash.h:204]: Speaking about this, there are tons of such places, but there is `getDataAt`, and asm looks the same (at least after a quick look), maybe complexity does not worth it?

**Comment by azat** [comment]
Cc: @zhang2014

File: src/Interpreters/BloomFilterHash.h [hunk 2]
```diff
@@ -196,18 +196,17 @@ struct BloomFilterHash
             const ColumnString::Chars & data = index_column->getChars();
             const ColumnString::Offsets & offsets = index_column->getOffsets();
 
-            ColumnString::Offset current_offset = pos;
```
Comment (zhang2014) [inline src/Interpreters/BloomFilterHash.h:199]: We just need to change this to `ColumnString::Offset current_offset = offsets[pos - 1];` to fix this bug.

: (
But I don't know why it affects all the data (in fact, it should only affect the first row of data)

File: src/Interpreters/BloomFilterHash.h (hunk 1 above)
Comment (zhang2014) [reply src/Interpreters/BloomFilterHash.h:204]: I understand that this may be because getDataAt is a virtual function

**Comment by zhang2014** [comment]
LGTM

File: src/Interpreters/BloomFilterHash.h (hunk 2 above)
Comment (azat) [reply src/Interpreters/BloomFilterHash.h:199]: >We just need change this to ColumnString::Offset current_offset = offsets[pos - 1]; to fix this bug.

Yes, but to avoid double assignment, I just moved into the loop

>But I don't know why it affects all the data (in fact, it should only affect the first row of data)

You are right, and to be more precise, it affects the first row per index_granularity , but not the first row in block (detailed description reflects that).

File: src/Interpreters/BloomFilterHash.h (hunk 1 above)
Comment (azat) [reply src/Interpreters/BloomFilterHash.h:204]: Good point! But AFAICS the `getDataAt` may be marked `final`, and I guess it is always used after casting to some column type so compiler will optimize this (like here)

Although there can be cases when this will not happen I guess, and in this case explicit writing preferable.

Anyway this is just a thought, not related to this bugfix.

**Comment by akuzm** [comment]
Build failure and perftest error are CI problem.
