### PR TITLE
Fix some issues with transactions

### LINKED ISSUE #49923: Logical error: Data part is Outdated and has creation TID  and CSN, but does not have removal tid
https://s3.amazonaws.com/clickhouse-test-reports/49912/ff6187128cc481d97e99b24646145669562a1e41/stress_test__ubsan_.html

```
[ 47323 ] {} <Fatal> : Logical error: \'Data part -9_18_18_0_98 is Outdated and has creation TID (201, 39, dbfe6a33-d532-4ef2-a586-5a9362c92263) and CSN 202, but does not have removal tid. It\'s a bug or a result of manual intervention.\'.
 [ 47531 ] {} <Fatal> BaseDaemon: ########################################
 [ 47531 ] {} <Fatal> BaseDaemon: (version 23.5.1.1, build id: 9DF8435409E8E9D92EFCE5964BC379CDD6B6C44B) (from thread 47323) (no query) Received signal Aborted (6)
 [ 47531 ] {} <Fatal> BaseDaemon: 
 [ 47531 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f21dcef800b 0x00007f21dced7859 0x000056350e1e8788 0x000056350e1e90ee 0x000056351d5a1ade 0x000056351d4c89c7 0x000056351d5955a3 0x000056351a486fa5 0x0000563519ddd0a1 0x000056350e339bc0 0x000056350e33f00f 0x000056350e336a80 0x000056350e33c04a 0x0000
 [ 47531 ] {} <Fatal> BaseDaemon: 3. raise @ 0x00007f21dcef800b in ?
 [ 47531 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007f21dced7859 in ?
 [ 47531 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:49: DB::abortOnFailedAssertion(String const&) @ 0x00000000347d1788 in /usr/bin/clickhouse
 [ 47531 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000347d20ee in /usr/bin/clickhouse
 [ 47531 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
 [ 47531 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:2333: ~basic_string
 [ 47531 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/./src/Common/Exception.h:42: ~MessageMasked
 [ 47531 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/./src/Common/Exception.h:54: Exception
 [ 47531 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Common/Exception.h:81: DB::Exception::Exception<String&, DB::TransactionID&, unsigned long&>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<DB::TransactionID&>::type, std::type_identity<unsigned long&>::type
 [ 47531 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:1164: DB::preparePartForRemoval(std::shared_ptr<DB::IMergeTreeDataPart> const&) @ 0x0000000043ab19c7 in /usr/bin/clickhouse
 [ 47531 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
 [ 47531 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/./src/Storages/MergeTree/MergeTreeData.h:1403: ~LoadPartResult
 [ 47531 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:1973: operator()
 [ 47531 ] {} <Fatal> BaseDaemon: 9.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::MergeTreeData::loadOutdatedDataParts(bool)::$_0&>()()) std::__invoke[abi:v15000]<DB::MergeTreeData::loadOutdatedDataParts(bool)::$_0&>(DB::Mer
 [ 47531 ] {} <Fatal> BaseDaemon: 9.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::MergeTreeData::loadOutdatedDataParts(bool)::$_0&>(DB::MergeTreeData::loadOutdatedDataParts(bool)::$_0&)
 [ 47531 ] {} <Fatal> BaseDaemon: 9.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::MergeTreeData::loadOutdatedDataParts(bool)::$_0, void ()>::operator()[abi:v15000]()
 [ 47531 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeData::loadOutdatedDataParts(bool)::$_0, void ()>>(std::__function::__
 [ 47531 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:0: std::function<std::future<void> (std::function<void ()>&&, long)> DB::threadPoolCallbackRunner<void, std::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String 
 [ 47531 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./contrib/llvm-project/libcxx/include/future:2069: std::packaged_task<void ()>::operator()() @ 0x00000000403c60a1 in /usr/bin/clickhouse
 [ 47531 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:796: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 47531 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1463: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 47531 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 47531 ] {} <Fatal> BaseDaemon: 12.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 47531 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Common/ThreadPool.cpp:418: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000034922bc0 in /usr/bin/clickhouse
 [ 47531 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::\'lambda0\'()>(void&
 [ 47531 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:796: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 47531 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1463: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 47531 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 47531 ] {} <Fatal> BaseDaemon: 14.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 47531 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Common/ThreadPool.cpp:418: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000003491fa80 in /usr/bin/clickhouse
 [ 47531 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
 [ 47531 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 47531 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
 [ 47531 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
 [ 47531 ] {} <Fatal> BaseDaemon: 15.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(st
 [ 47531 ] {} <Fatal> BaseDaemon: 15.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::
 [ 47531 ] {} <Fatal> BaseDaemon: 15.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 47531 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function
 [ 47531 ] {} <Fatal> BaseDaemon: 16. ? @ 0x00007f21dd0af609 in ?
 [ 47531 ] {} <Fatal> BaseDaemon: 17. __clone @ 0x00007f21dcfd4133 in ?
 [ 47531 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
 [ 47007 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 1874 ] {c64e6fd3-687d-4612-99f9-462bd5764d50::-9_18_18_0_149} <Fatal> : Logical error: \'Unexpected CSN state: 203\'.
 [ 46145 ] {} <Fatal> BaseDaemon: ########################################
 [ 46145 ] {} <Fatal> BaseDaemon: (version 23.5.1.1, build id: 9DF8435409E8E9D92EFCE5964BC379CDD6B6C44B) (from thread 1874) (query_id: c64e6fd3-687d-4612-99f9-462bd5764d50::-9_18_18_0_149) (query: ) Received signal Aborted (6)
 [ 46145 ] {} <Fatal> BaseDaemon: 
 [ 46145 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fd78ea7800b 0x00007fd78ea57859 0x0000555718ee2788 0x0000555718ee30ee 0x000055570e0bb6f7 0x0000555726d8802b 0x0000555726d88617 0x0000555726d892eb 0x000055572824b529 0x00005557286dd6b4 0x00005557281a255d 0x00005557281a405f 0x0000555719033bc0 0x0000
 [ 46145 ] {} <Fatal> BaseDaemon: 3. raise @ 0x00007fd78ea7800b in ?
 [ 46145 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007fd78ea57859 in ?
 [ 46145 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:49: DB::abortOnFailedAssertion(String const&) @ 0x00000000347d1788 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000347d20ee in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type>, unsigned long&) @ 0x00000000299aa6f7 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Interpreters/MergeTreeTransaction.cpp:0: DB::MergeTreeTransaction::checkIsNotCancelled() const @ 0x000000004267702b in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Interpreters/MergeTreeTransaction.cpp:137: DB::MergeTreeTransaction::addNewPart(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::IMergeTreeDataPart const> const&) @ 0x0000000042677617 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Interpreters/MergeTreeTransaction.cpp:0: DB::MergeTreeTransaction::addNewPartAndRemoveCovered(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::IMergeTreeDataPart const> const&, std::vector<std::shared_ptr<DB::IMergeTreeDataPart cons
 [ 46145 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
 [ 46145 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Storages/MergeTree/MergeTreeData.cpp:6127: DB::MergeTreeData::Transaction::commit(std::unique_lock<std::mutex>*) @ 0x0000000043b3a529 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:580: std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>::data[abi:v15000]() const
 [ 46145 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:760: std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>::__annotate_delete[abi:v15000]() const
 [ 46145 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:431: ~vector
 [ 46145 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Storages/MergeTree/MutatePlainMergeTreeTask.cpp:102: DB::MutatePlainMergeTreeTask::executeStep() @ 0x0000000043fcc6b4 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:185: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x0000000043a9155d in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
 [ 46145 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:305: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000043a9305f in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:796: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 46145 ] {} <Fatal> BaseDaemon: 15.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1463: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 46145 ] {} <Fatal> BaseDaemon: 15.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 46145 ] {} <Fatal> BaseDaemon: 15.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 46145 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Common/ThreadPool.cpp:418: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000034922bc0 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::\'lambda0\'()>(void&
 [ 46145 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:796: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 46145 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1463: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 46145 ] {} <Fatal> BaseDaemon: 17.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 46145 ] {} <Fatal> BaseDaemon: 17.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 46145 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Common/ThreadPool.cpp:418: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000003491fa80 in /usr/bin/clickhouse
 [ 46145 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
 [ 46145 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 46145 ] {} <Fatal> BaseDaemon: 18.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
 [ 46145 ] {} <Fatal> BaseDaemon: 18.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
 [ 46145 ] {} <Fatal> BaseDaemon: 18.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(st
 [ 46145 ] {} <Fatal> BaseDaemon: 18.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::
 [ 46145 ] {} <Fatal> BaseDaemon: 18.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 46145 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function
 [ 46145 ] {} <Fatal> BaseDaemon: 19. ? @ 0x00007fd78ec2f609 in ?
 [ 46145 ] {} <Fatal> BaseDaemon: 20. __clone @ 0x00007fd78eb54133 in ?
 [ 46145 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
 [ 1588 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 47323 ] {} <Fatal> : Logical error: \'Data part -9_18_18_0_98 is Outdated and has creation TID (201, 39, dbfe6a33-d532-4ef2-a586-5a9362c92263) and CSN 202, but does not have removal tid. It\'s a bug or a result of manual intervention.\'.
 [ 47531 ] {} <Fatal> BaseDaemon: ########################################
 [ 47531 ] {} <Fatal> BaseDaemon: (version 23.5.1.1, build id: 9DF8435409E8E9D92EFCE5964BC379CDD6B6C44B) (from thread 47323) (no query) Received signal Aborted (6)
 [ 47531 ] {} <Fatal> BaseDaemon: 
 [ 47531 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f21dcef800b 0x00007f21dced7859 0x000056350e1e8788 0x000056350e1e90ee 0x000056351d5a1ade 0x000056351d4c89c7 0x000056351d5955a3 0x000056351a486fa5 0x0000563519ddd0a1 0x000056350e339bc0 0x000056350e33f00f 0x000056350e336a80 0x000056350e33c04a 0x0000
 [ 47531 ] {} <Fatal> BaseDaemon: 3. raise @ 0x00007f21dcef800b in ?
 [ 47531 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007f21dced7859 in ?
 [ 47531 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:49: DB::abortOnFailedAssertion(String const&) @ 0x00000000347d1788 in /usr/bin/clickhouse
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/49923
Also fixes `Found removal_csn in metadata file, but removal_tid is (0, 0, 00000000-0000-0000-0000-000000000000): While loading version metadata from table` (https://s3.amazonaws.com/clickhouse-test-reports/0/7a593ed9a59139aba3ea133c3170488ac7818e64/stress_test__msan_.html)

See also https://pastila.nl/?008bd018/5b22ca9db3f2bd07691e7a04e9cff314

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
This is an automated comment for commit 8c83786e5477b5c2744457004ab7e8bf6d8de2ee with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51959/8c83786e5477b5c2744457004ab7e8bf6d8de2ee/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

File: src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp [hunk 1]
```diff
@@ -267,11 +269,12 @@ void MergeTreeBackgroundExecutor<Queue>::routine(TaskRuntimeDataPtr item)
     try
     {
         ALLOW_ALLOCATIONS_IN_SCOPE;
+        item->task->getQueryId();
```
Comment (Algunenano) [inline src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:272]: Is this missing an assignment?

```
        query_id = item->task->getQueryId();
````

Comment (tavplubix) [reply src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:272]: Yes, thank you
https://github.com/ClickHouse/ClickHouse/pull/52261
