### PR TITLE
Fix `X-ClickHouse-Timezone` header with `session_timezone`

### LINKED ISSUE #1464: Query settings session_timezone not being applied
### Describe the bug
Clickhouse allows user to set query to multiple level including at the query level. When the setting `session_timezone` is set in dbeaver , the setting is not being picked up. I have looked at this issue #604 where the timezone is set correctly for `toDateTime` but it does not seem to be the case when using this setting. Whenever I use `session_timezone`, the datetime uses the wrong timezone.

image

In this query, the date should be identical to the second column not the third. Running it directly using `clickhouse-client`, the result of this query should be the following:

image

By changing the `session_timezone`, the value in the first column should change to adapt to the new timezone.

#### ClickHouse server
* ClickHouse Server version: 23.8.2.7
* Statement:
```
WITH temp AS
    (
        SELECT 1696431276 AS date
    )
SELECT
    toDateTime(date),
    toDateTime(date, 'America/New_York'),
    toDateTime(date, 'UTC')
FROM temp
SETTINGS session_timezone = 'America/Vancouver'
```

### LINKED ISSUE #63359: session_timezone is not reflected in X-ClickHouse-Timezone
```sql
(curl -v "http://localhost:8123/?query=select+1+settings+session_timezone='Europe/Berlin'") 2>&1 |grep Timezone
< X-ClickHouse-Timezone: Etc/UTC
```

expected: X-ClickHouse-Timezone: Europe/Berlin

### PR DESCRIPTION
**Pull request by zvonand**
Closes #63359, closes https://github.com/ClickHouse/clickhouse-java/issues/1464

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `X-ClickHouse-Timezone` header returning wrong timezone when using `session_timezone` as query level setting.

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

<details>

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit d269e4eb9ff90723a0af20af97d1faccbe7c01ef with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63377/d269e4eb9ff90723a0af20af97d1faccbe7c01ef/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by zvonand** [comment]
The only red test:
* `Stateless tests (msan) [6/6]`:
  - `02481_async_insert_race_long` -- flaky, see #47866

**Comment by den-crane** [comment]
@zvonand please add a test for `session_timezone` passed as url parameter:

```
http://localhost:8123/?session_timezone=Europe/Berlin&query=...
```

File: tests/queries/0_stateless/00265_http_content_type_format_timezone.sh [hunk 1]
```diff
@@ -13,3 +13,12 @@ ${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL}" --data-binary @- <<< "SELECT 1 FORMA
...
 ${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL}" --data-binary @- <<< "SELECT 1 FORMAT RowBinary"    2>&1 | grep -e '< Content-Type' -e '< X-ClickHouse-Format' -e '< X-ClickHouse-Timezone' | sed "s|$CLICKHOUSE_TIMEZONE_ESCAPED|CLICKHOUSE_TIMEZONE|" | sed 's/\r$//' | sort;
+
+${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL}" --data-binary @- <<< "SELECT timezone() SETTINGS session_timezone='Europe/Berlin'" 2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
+${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL}" --data-binary @- <<< "SELECT timezone() SETTINGS session_timezone='Africa/Cairo'"  2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
+
+# Not pretty but working way of removing randomized session_timezone for this part of test
+CLICKHOUSE_URL_WO_SESSION_TZ=$(echo "${CLICKHOUSE_URL}" |sed 's/\&session_timezone\=\([A-Za-z]*\(\%2F\|\/\)[A-Za-z]*\|[A-Za-z0-9\+\-]*\)//g' | sed 's/\?session_timezone\=\([A-Za-z]*\(\%2F\|\/\)[A-Za-z]*\|[A-Za-z0-9\+\-]*\)\&/\?/g');
```
Comment (davenger) [inline tests/queries/0_stateless/00265_http_content_type_format_timezone.sh:21]: I listed time zones from 
```
select * from system.time_zones
```
And it looks like this regexp doesn't work with some of them:

```
America/Argentina/Jujuy
America/Argentina/La_Rioja
America/Argentina/Mendoza
...
Etc/GMT+0
Etc/GMT+1
Etc/GMT+10
```

Comment (davenger) [reply tests/queries/0_stateless/00265_http_content_type_format_timezone.sh]: Shouldn't these parts of regexp be the same in the 1st and 2nd sed?
`[A-Za-z0-9\/\%\_\-\+\-]*`
 and
`[A-Za-z\_]*[A-Za-z0-9\/\%\_\-\+\-]*`

Comment (zvonand) [reply tests/queries/0_stateless/00265_http_content_type_format_timezone.sh]: Of course, thanks

**Comment by davenger** [comment]
@zvonand I see some more interesting scenarios that need to covered by test cases:
 
1. Different session_timezone in subqueries:
```
SELECT 2 FROM (SELECT 1 SETTINGS session_timezone = 'Africa/Cairo');
SELECT 2 FROM (SELECT 1 SETTINGS session_timezone = 'Africa/Cairo') SETTINGS session_timezone = 'Europe/Paris';
```
2. Query fails with runtime error:
```
SELECT intDiv(1,0) SETTINGS session_timezone = 'Africa/Cairo';
```
3. 1+2 combined
```
SELECT intDiv(2,0) FROM (SELECT 1 SETTINGS session_timezone = 'Africa/Cairo') SETTINGS session_timezone = 'Europe/Paris';
SELECT 2 FROM (SELECT intDiv(1,0) SETTINGS session_timezone = 'Africa/Cairo') SETTINGS session_timezone = 'Europe/Paris';
SELECT 2 FROM (SELECT intDiv(1,0) SETTINGS session_timezone = 'Africa/Cairo');
```

For 2 and 3 I think that `result_details.timezone = DateLUT::instance().getTimeZone();` might need to be added to this `catch(...)`
https://github.com/ClickHouse/ClickHouse/pull/63377/files#diff-ff8ad4aed4cf07fe29cb5344d2ab79bc24efd97d054aa112c3a05b5ab853cc44R1525

Also it makes sense to add comment for the line `result_details.timezone = DateLUT::instance().getTimeZone();` describing that this is needed to return the timezone if i was overridden via query settings.

**Comment by davenger** [comment]
> The query failed in general, why should we use the session_timezone defined in this query in the result header?

Even in case of query failure we set `X-ClickHouse-Timezone` header in the reply, and the timezone setting can be the cause of the query failure, so it's better to fill this header with the correct value.
Here is an example, even though it's a bit artificial. Note that header says that timezone is UTC, but the query failed because the used timezone actually is 1h ahead of UTC  

```
$ curl -vsS "http://localhost:8123/?session_timezone=UTC&query=SELECT+intDiv(1,+(3600-timeZoneOffset(now())))+SETTINGS+session_timezone+=+'Europe/Lisbon';"
*   Trying 127.0.0.1:8123...
* Connected to localhost (127.0.0.1) port 8123 (#0)
> GET /?session_timezone=UTC&query=SELECT+intDiv(1,+(3600-timeZoneOffset(now())))+SETTINGS+session_timezone+=+'Europe/Lisbon'; HTTP/1.1
> Host: localhost:8123
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 06 May 2024 14:33:53 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: davenger-xps
< Transfer-Encoding: chunked
< X-ClickHouse-Query-Id: 18a583df-a5eb-4423-b3cd-6e07a0d08d68
< X-ClickHouse-Timezone: UTC
< X-ClickHouse-Exception-Code: 153
< Keep-Alive: timeout=3
< X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"24567774"}
< 
Code: 153. DB::Exception: Division by zero: In scope SELECT intDiv(1, 3600 - timeZoneOffset(now())) SETTINGS session_timezone = 'Europe/Lisbon'. (ILLEGAL_DIVISION) (version 24.5.1.1)
* Connection #0 to host localhost left intact

```

**Comment by zvonand** [comment]
Regarding note 1: session_timezone is not properly handled in a subquery. The value in system.settings is fine, but subqueries still use timezone from the main query. I will take a look into this.

However, I suggest keeping this problem out of scope of this PR: it was made to solve an existing problem that people have, and I'd better fix another problem (the one with subqueries) in a different PR

**Comment by davenger** [comment]
> However, I suggest keeping this problem out of scope of this PR: it was made to solve an existing problem that people have, and I'd better fix another problem (the one with subqueries) in a different PR

Ok, but please add a test case with simple failed query without subqueries

File: tests/queries/0_stateless/00265_http_content_type_format_timezone.sh [hunk 2]
```diff
@@ -13,3 +13,14 @@ ${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL}" --data-binary @- <<< "SELECT 1 FORMA
...
+${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL}" --data-binary @- <<< "SELECT timezone() SETTINGS session_timezone='Africa/Cairo'"  2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
+
+# Not pretty but working way of removing randomized session_timezone for this part of test
+CLICKHOUSE_URL_WO_SESSION_TZ=$(echo "${CLICKHOUSE_URL}" |sed 's/\&session_timezone\=[A-Za-z0-9\/\%\_\-\+\-]*//g' | sed 's/\?session_timezone\=[A-Za-z0-9\/\%\_\-\+\-]*\&/\?/g');
+
+${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL_WO_SESSION_TZ}&session_timezone=Europe/Berlin&query=SELECT+timezone()" 2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
+${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL_WO_SESSION_TZ}&session_timezone=America/Denver&query=SELECT+timezone()" 2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
+# check that proper X-ClickHouse-Timezone returned on query fail
+${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL_WO_SESSION_TZ}&session_timezone=UTC&query=SELECT+intDiv(1,+(3600-timeZoneOffset(now())))+SETTINGS+session_timezone+=+'Europe/Lisbon'" 2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
```
Comment (davenger) [inline tests/queries/0_stateless/00265_http_content_type_format_timezone.sh:26]: Hardcode DateTime instead of now() to make test stable 

```suggestion
${CLICKHOUSE_CURL} -vsS "${CLICKHOUSE_URL_WO_SESSION_TZ}&session_timezone=UTC&query=SELECT+intDiv(1,+(3600-timeZoneOffset('2024-05-06+12:00:00'::DateTime)))+SETTINGS+session_timezone+=+'Europe/Lisbon'" 2>&1 | grep '< X-ClickHouse-Timezone' | grep -v 'GET' | tr -d '\r';
```

**Comment by den-crane** [comment]
>Regarding note 1: session_timezone is not properly handled in a subquery. 

```
SELECT timezone() x, y FROM (SELECT timezone() y  limit 10 SETTINGS session_timezone = 'Africa/Cairo') SETTINGS session_timezone = 'Europe/Paris';
┌─x────────────┬─y────────────┐
│ Europe/Paris │ Europe/Paris │
└──────────────┴──────────────┘
```

I think it's OK, and expected.

I don't think it's a good idea to use session_timezone setting from a subquery.

Because columns are provided by the most-top SELECT and all columns have the only one default timezone.

```
select now() E_P, A_C from (select now() A_C settings session_timezone = 'Africa/Cairo') settings session_timezone = 'Europe/Paris';
┌─────────────────E_P─┬─────────────────A_C─┐
│ 2024-05-06 17:33:44 │ 2024-05-06 17:33:44 │
└─────────────────────┴─────────────────────┘
```

**Comment by davenger** [comment]
Yes, it makes perfect sense for the header in the reply to return the timezone of the topmost query.

**Review by davenger — APPROVED** [review]
