### PR TITLE
Fix fixed string partial sort

### LINKED ISSUE #13182: ORDER BY field with type FixedString(16) gives unexpected result
Trying to sort query by field with type 'FixedString(16)' results is wrong record order.

**How to reproduce**
Tested versions: 
 * 20.7.1.4189 -- reproducible
 * 20.5.3.27 -- reproducible
 * 20.5.2.7 -- reproducible
 * 20.4.7.67 -- non-reproducible
 * 18.12.17 -- non-reproducible

Example data set:
Table containing rows with string name and corresponding UUID5 of each name (uuid_old == uuid_new and always match name).
**Each statement of the set must be executed as separate query (not in one batch).**

    -- sql.txt
    CREATE TABLE IF NOT EXISTS bad_uuid_sort (date Date, timestamp DateTime, name String, uuid5_old FixedString(16), uuid5_new UUID, subitem String) engine MergeTree(date, (timestamp, uuid5_old), 8192);

    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item1');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item3');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item2');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item5');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item4');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item1');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item3');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item2');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item5');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_1', UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '999e1140-66ef-5610-9c3a-b3fb33e0fda9', 'item4');

    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item5');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item2');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item3');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item4');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item1');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item5');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item2');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item3');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item4');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_2', UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '8ad8fc5e-a49e-544c-98e6-1140afd79f80', 'item1');

    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item3');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item5');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item2');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item1');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item4');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item3');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item5');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item2');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item1');
    INSERT INTO bad_uuid_sort values (toDate(now()), now(), 'id_3', UUIDStringToNum('ffa62c2d-2a77-52ff-a90b-7e296821f0f0'), 'ffa62c2d-2a77-52ff-a90b-7e296821f0f0', 'item4');

    
    # Insert one-by-one with this oneliner
    cat sql.txt | xargs -d '\n' -I QUERY clickhouse-client -q 'QUERY'
    

Selection with ordering by uuid5_old gives broken ordering for ordering keys following it (check subitem column):

    # clickhouse-client -q SELECT date, timestamp, name_raw, UUIDNumToString(uuid5_old), uuid5_new, subitem FROM bad_uuid_sort ORDER BY name_raw ASC, uuid5_old ASC, subitem ASC, timestamp ASC;
    
    2020-07-31      2020-07-31 12:55:33     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item1
    2020-07-31      2020-07-31 12:55:33     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item3
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item1
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item2
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item2
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item3
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item4
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item4
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item5
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item5
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item2
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item5
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item1
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item1
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item2
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item3
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item3
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item4
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item4
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item5
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item1
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item1
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item2
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item2
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item3
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item3
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item4
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item4
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item5
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item5

Selecting by uuid5_new gives expected ordering:

    # clickhouse-client -q SELECT date, timestamp, name_raw, UUIDNumToString(uuid5_old), uuid5_new, subitem FROM bad_uuid_sort ORDER BY name_raw ASC, uuid5_new ASC, subitem ASC, timestamp ASC;
    
    2020-07-31      2020-07-31 12:55:33     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item1
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item1
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item2
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item2
    2020-07-31      2020-07-31 12:55:33     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item3
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item3
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item4
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item4
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item5
    2020-07-31      2020-07-31 12:55:34     id_1    999e1140-66ef-5610-9c3a-b3fb33e0fda9    999e1140-66ef-5610-9c3a-b3fb33e0fda9    item5
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item1
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item1
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item2
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item2
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item3
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item3
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item4
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item4
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item5
    2020-07-31      2020-07-31 12:55:34     id_2    8ad8fc5e-a49e-544c-98e6-1140afd79f80    8ad8fc5e-a49e-544c-98e6-1140afd79f80    item5
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item1
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item1
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item2
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item2
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item3
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item3
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item4
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item4
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item5
    2020-07-31      2020-07-31 12:55:34     id_3    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    ffa62c2d-2a77-52ff-a90b-7e296821f0f0    item5
    
Results are not always consistent, inserting same data over and over again with some intervals usually helps.

**Expected behavior**
Both queries should result in same ordering

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect sorting for `FixedString` columns. Fixes #13182

### CODE REVIEW

File: tests/queries/0_stateless/01453_fixsed_string_sort.sql [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+INSERT INTO badFixedStringSort values (UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '2');
+INSERT INTO badFixedStringSort values (UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '1');
+INSERT INTO badFixedStringSort values (UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '2');
+INSERT INTO badFixedStringSort values (UUIDStringToNum('8ad8fc5e-a49e-544c-98e6-1140afd79f80'), '1');
+
+INSERT INTO badFixedStringSort values (UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '1');
+INSERT INTO badFixedStringSort values (UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '2');
+INSERT INTO badFixedStringSort values (UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '1');
+INSERT INTO badFixedStringSort values (UUIDStringToNum('999e1140-66ef-5610-9c3a-b3fb33e0fda9'), '2');
+
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/01453_fixsed_string_sort.sql:18]: Maybe add this lines either?
```sql
SELECT cityHash64(groupArray(subitem)) FROM (select * from badFixedStringSort ORDER BY  uuid5_old ASC, subitem ASC);
SELECT cityHash64(groupArray(subitem)) FROM (select * from badFixedStringSort ORDER BY  uuid5_old ASC, subitem ASC settings max_block_size=1);

system start merges badFixedStringSort;
optimize table badFixedStringSort final;

SELECT cityHash64(groupArray(subitem)) FROM (select * from badFixedStringSort ORDER BY  uuid5_old ASC, subitem ASC);
SELECT cityHash64(groupArray(subitem)) FROM (select * from badFixedStringSort ORDER BY  uuid5_old ASC, subitem ASC settings max_block_size=1);
```

**Review by nikitamikhaylov — APPROVED** [review]

File: tests/queries/0_stateless/01453_fixsed_string_sort.sql (hunk 1 above)
Comment (KochetovNicolai) [reply tests/queries/0_stateless/01453_fixsed_string_sort.sql:18]: Ok, I'll add `optimize table` because the bug appears only after merge.

**Comment by KochetovNicolai** [comment]
`01444_create_table_drop_database_race` - fixed in 30e0cd438ea0f383d9b5431d1acea7eb2fac5966
build check - build broken in master
AST fuzzer - reported #13893
