### PR TITLE
Check only selected primary key ranges for intersection in PrimaryKeyExpand processing in FINAL query

### LINKED ISSUE #94696: use_skip_indexes_if_final_exact_mode processing exceeds granules compared to primary key analysis
### Company or project name
ClickHouse Server

From a `EXPLAIN indexes=1` -
```
PrimaryKey
  Keys:
...
  Condition: 
...
  Parts: 61/82
  Granules: 582/672731
  Search Algorithm: generic exclusion search
Skip
  Name: <redact>
  Description: minmax GRANULARITY 1
  Parts: 61/61
  Granules: 582/582
PrimaryKeyExpand
  Description: Selects all granules that intersect by PK values with the previous skip indexes selection
  Parts: 61/61
  Granules: 377501/582
  Ranges: 645
```

There was a UUID in the primary key.

Currently, the `PrimaryKeyExpand` algorithm looks for intersection in all the `parts` shortlisted after primary key analysis. The algorithm can be improved to restrict the scope of intersection to the granules selected after primary key analysis.

### Describe the unexpected behaviour

Please check above

### Which ClickHouse versions are affected?

25.8+

### How to reproduce

Check above

### Expected behavior

Faster query execution

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shankar-iyer**
Resolves https://github.com/ClickHouse/ClickHouse/issues/94696.

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description]
If a `FINAL` query used primary key condition for filtering followed by skip indexes for other conditions, the `PrimaryKeyExpand` processing step will now only check the initial shortlisted primary key ranges for intersection.

### Version info
- Merged into: `26.2.1.262`
- Backported to: `25.12.6.31`

### CODE REVIEW

**Comment by shankar-iyer** [comment]
> @shankar-iyer, It is ready for review, right?

Yes, missed to clear draft status!

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 1]
```diff
@@ -951,6 +951,8 @@ RangesInDataParts findPKRangesForFinalAfterSkipIndexImpl(RangesInDataParts & ran
         /// The final mark may not be written under some situations e.g index_granularity_bytes = 0.
         if (!index_granularity->hasFinalMark())
         {
+            LOG_TRACE(logger, "use_skip_indexes_if_final_exact_mode processing could not find final mark in {}",
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp]: It reads like "some internal logic of the exact_mode wasn't able to find something", but the reality is that the part either has the final mark or not. It has nothing to do with the `exact_mode` optimisation. Moreover, the most important part here is that the optimisation was skipped. Can we replace it with, e.g., "use_skip_indexes_if_final_exact_mode processing is not applied, because {} doesn't have the final mark"?

File: src/Storages/MergeTree/RangesInDataPart.h [hunk 2]
```diff
@@ -94,6 +94,8 @@ struct RangesInDataPart
     MarkRanges exact_ranges;
     RangesInDataPartReadHints read_hints;
 
+    std::optional<MarkRanges> ranges_snapshot_after_pk_analysis;
```
Comment (nickitat) [inline src/Storages/MergeTree/RangesInDataPart.h:101]: Please clarify in the comment when it is set and when it is used.

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 3]
```diff
@@ -982,37 +984,50 @@ RangesInDataParts findPKRangesForFinalAfterSkipIndexImpl(RangesInDataParts & ran
...
     const PartsRangesIterator selected_lower_bound = selected_ranges[0];
 
+    /// Find the ranges that were rejected in each part. We use the 'ranges_snapshot_after_pk_analysis'
+    /// member because ranges already rejected by pk analysis don't need to be checked again for intersection.
     for (size_t part_index = 0; part_index < ranges_in_data_parts.size(); ++part_index)
     {
-        const auto & index_granularity = ranges_in_data_parts[part_index].data_part->index_granularity;
-        const auto & part_lower_bound = index_access.getValue(part_index, 0);
-        const auto & part_upper_bound = index_access.getValue(part_index, index_granularity->getMarksCountWithoutFinal());
+        if (!ranges_in_data_parts[part_index].ranges_snapshot_after_pk_analysis)
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp:991]: If I'm not mistaken, `ranges_snapshot_after_pk_analysis` should always be initialised in cases when we can reach this code. If that's true, we should throw a logical error rather than continue.

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 4]
```diff
@@ -982,37 +984,50 @@ RangesInDataParts findPKRangesForFinalAfterSkipIndexImpl(RangesInDataParts & ran
...
+            continue;
+
+        auto part_ranges_after_pk_analysis_begin = ranges_in_data_parts[part_index].ranges_snapshot_after_pk_analysis->begin()->begin;
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp]: Looks simpler IMO

```suggestion
        const auto & ranges = *ranges_in_data_parts[part_index].ranges_snapshot_after_pk_analysis;
        const auto part_ranges_after_pk_analysis_begin = ranges.front().begin;
        ...
```

File: src/Processors/QueryPlan/PartsSplitter.cpp [hunk 5]
```diff
@@ -982,37 +984,50 @@ RangesInDataParts findPKRangesForFinalAfterSkipIndexImpl(RangesInDataParts & ran
...
         {
-            if (std::binary_search(part_selected_ranges[part_index].begin(), part_selected_ranges[part_index].end(), range_begin))
-                continue;
-            MarkRange rejected_range(range_begin, range_begin + 1);
-            rejected_ranges.push_back(
-                {index_access.getValue(part_index, rejected_range.begin), false, rejected_range, part_index,
+            for (auto range_begin = part_candidate_range.begin; range_begin < part_candidate_range.end; range_begin++)
+            {
+                if (range_begin < candidates_start || range_begin > candidates_end)
+                    continue;
```
Comment (nickitat) [inline src/Processors/QueryPlan/PartsSplitter.cpp]: It is not a big deal, but just for the sake of premature optimisation. 

```suggestion
            for (auto range_begin = max(part_candidate_range.begin, candidates_start); range_begin < max(part_candidate_range.end, candidates_end+1); range_begin++)
            {
```

File: src/Processors/QueryPlan/PartsSplitter.cpp (hunk 1 above)
Comment (shankar-iyer) [reply src/Processors/QueryPlan/PartsSplitter.cpp]: Done

File: src/Storages/MergeTree/RangesInDataPart.h (hunk 2 above)
Comment (shankar-iyer) [reply src/Storages/MergeTree/RangesInDataPart.h:101]: done, thanks!

File: src/Processors/QueryPlan/PartsSplitter.cpp (hunk 3 above)
Comment (shankar-iyer) [reply src/Processors/QueryPlan/PartsSplitter.cpp:991]: Yes, corrected!

File: src/Processors/QueryPlan/PartsSplitter.cpp (hunk 4 above)
Comment (shankar-iyer) [reply src/Processors/QueryPlan/PartsSplitter.cpp]: Agree, done!

File: src/Processors/QueryPlan/PartsSplitter.cpp (hunk 5 above)
Comment (shankar-iyer) [reply src/Processors/QueryPlan/PartsSplitter.cpp]: Done

File: tests/queries/0_stateless/03244_skip_index_in_final_query_with_pk_rescan_pk_subset.sql [hunk 6]
```diff
@@ -0,0 +1,57 @@
+DROP TABLE IF EXISTS rmt1;
```
Comment (nickitat) [inline tests/queries/0_stateless/03244_skip_index_in_final_query_with_pk_rescan_pk_subset.sql:1]: Pls help me understand if the test covers the original issue we found. I suppose, without the fix, we were selecting more granules to read, and that was the problem. So this test is enough?

**Review by nickitat — APPROVED** [review]

File: tests/queries/0_stateless/03244_skip_index_in_final_query_with_pk_rescan_pk_subset.sql (hunk 6 above)
Comment (shankar-iyer) [reply tests/queries/0_stateless/03244_skip_index_in_final_query_with_pk_rescan_pk_subset.sql:1]: >we were selecting more granules to read, and that was the problem

Yes, that was the original issue and this test covers that. Without the fix, the test fails with following dif -

```
 Granules: 2
 Granules: 1
-Granules: 2
+Granules: 157 <----- 157 granules added back, although filtered out by primary key condition. More below
 Granules: 17
 Granules: 1
-Granules: 17
+Granules: 157
 Granules: 26
 Granules: 1
-Granules: 10
+Granules: 134
 Granules: 5
 Granules: 1
-Granules: 5
+Granules: 290
 Granules: 23
 Granules: 1
-Granules: 23
+Granules: 157
```
