### PR TITLE
Removed forceful drop cache command, fix detached status state

### LINKED ISSUE #36789: Assertion failed in destructor of `FileSegmentsHolder`
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/36077/20e2fa9b3f12e03f888461369bb0f78bc5709f60/stress_test__debug__actions_.html

```
2022.04.29 00:12:50.162735 [ 4058 ] {} <Fatal> BaseDaemon: ########################################
2022.04.29 00:12:50.250985 [ 4058 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: 8E6CC4881A822B3B) (from thread 760) (query_id: eb97d5a7-b931-45cb-a882-86dafb9840cc::201403_17_24_1) (query: ) Received signal Aborted (6)
2022.04.29 00:12:50.578744 [ 4058 ] {} <Fatal> BaseDaemon:
2022.04.29 00:12:50.582239 [ 4058 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f5de2a9803b 0x7f5de2a77859 0x7f5de2a77729 0x7f5de2a89006 0x258d71a1 0x258d744a 0x262966a7 0x26296675 0x26296655 0x26296635 0x26296615 0x262965f5 0x262965d5 0x26295fc1 0x26276847 0x262767d5 0x262767b9 0x262765ae 0x17b65331 0x17b652d9 0x258c8b4c 0x26258031 0x262582fa 0x2625824b 0x262587ca 0x17b65331 0x17b652d9 0x262aa5ac 0x262abba5 0x262abbd9 0x2620e58c 0x2620e4fc 0x2620e499 0x2620e035 0x262abe35 0x262abe59 0x2620e58c 0x2620e4fc 0x2620e499 0x2620e035 0x2620e0ae
2022.04.29 00:12:50.686906 [ 4058 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f5de2a9803b in ?
2022.04.29 00:12:50.727429 [ 4058 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f5de2a77859 in ?
2022.04.29 00:12:50.743583 [ 4058 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f5de2a77729 in ?
2022.04.29 00:12:50.746819 [ 4058 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f5de2a89006 in ?
2022.04.29 00:12:51.217785 [ 4058 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../src/Common/FileSegment.cpp:655: DB::FileSegment::assertDetachedStatus() const @ 0x258d71a1 in /usr/bin/clickhouse
2022.04.29 00:12:51.624284 [ 4058 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../src/Common/FileSegment.cpp:694: DB::FileSegmentsHolder::~FileSegmentsHolder() @ 0x258d744a in /usr/bin/clickhouse
2022.04.29 00:12:52.266279 [ 4058 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/libcxx/include/optional:239: std::__1::__optional_destruct_base<DB::FileSegmentsHolder, false>::~__optional_destruct_base() @ 0x262966a7 in /usr/bin/clickhouse
2022.04.29 00:12:52.769433 [ 4058 ] {} <Fatal> BaseDaemon: 11. /build/build_docker/../contrib/libcxx/include/optional:312: std::__1::__optional_storage_base<DB::FileSegmentsHolder, false>::~__optional_storage_base() @ 0x26296675 in /usr/bin/clickhouse
2022.04.29 00:12:53.329024 [ 4058 ] {} <Fatal> BaseDaemon: 12. /build/build_docker/../contrib/libcxx/include/optional:485: std::__1::__optional_copy_base<DB::FileSegmentsHolder, false>::~__optional_copy_base() @ 0x26296655 in /usr/bin/clickhouse
2022.04.29 00:12:53.875401 [ 4058 ] {} <Fatal> BaseDaemon: 13. /build/build_docker/../contrib/libcxx/include/optional:513: std::__1::__optional_move_base<DB::FileSegmentsHolder, false>::~__optional_move_base() @ 0x26296635 in /usr/bin/clickhouse
2022.04.29 00:12:54.420383 [ 4058 ] {} <Fatal> BaseDaemon: 14. /build/build_docker/../contrib/libcxx/include/optional:546: std::__1::__optional_copy_assign_base<DB::FileSegmentsHolder, false>::~__optional_copy_assign_base() @ 0x26296615 in /usr/bin/clickhouse
2022.04.29 00:12:54.785569 [ 4058 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../contrib/libcxx/include/optional:578: std::__1::__optional_move_assign_base<DB::FileSegmentsHolder, false>::~__optional_move_assign_base() @ 0x262965f5 in /usr/bin/clickhouse
2022.04.29 00:12:55.418670 [ 4058 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../contrib/libcxx/include/optional:621: std::__1::optional<DB::FileSegmentsHolder>::~optional() @ 0x262965d5 in /usr/bin/clickhouse
2022.04.29 00:12:55.942669 [ 4058 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../src/Disks/IO/CachedReadBufferFromRemoteFS.h:12: DB::CachedReadBufferFromRemoteFS::~CachedReadBufferFromRemoteFS() @ 0x26295fc1 in /usr/bin/clickhouse
2022.04.29 00:12:56.188207 [ 4058 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../contrib/libcxx/include/__memory/construct_at.h:57: void std::__1::__destroy_at<DB::CachedReadBufferFromRemoteFS, 0>(DB::CachedReadBufferFromRemoteFS*) @ 0x26276847 in /usr/bin/clickhouse
2022.04.29 00:12:56.932843 [ 4058 ] {} <Fatal> BaseDaemon: 19. /build/build_docker/../contrib/libcxx/include/__memory/construct_at.h:82: void std::__1::destroy_at<DB::CachedReadBufferFromRemoteFS, 0>(DB::CachedReadBufferFromRemoteFS*) @ 0x262767d5 in /usr/bin/clickhouse
2022.04.29 00:12:57.214613 [ 4058 ] {} <Fatal> BaseDaemon: 20. /build/build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:321: void std::__1::allocator_traits<std::__1::allocator<DB::CachedReadBufferFromRemoteFS> >::destroy<DB::CachedReadBufferFromRemoteFS, void, void>(std::__1::allocator<DB::CachedReadBufferFromRemoteFS>&, DB::CachedReadBufferFromRemoteFS*) @ 0x262767b9 in /usr/bin/clickhouse
2022.04.29 00:12:57.592011 [ 4058 ] {} <Fatal> BaseDaemon: 21. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:310: std::__1::__shared_ptr_emplace<DB::CachedReadBufferFromRemoteFS, std::__1::allocator<DB::CachedReadBufferFromRemoteFS> >::__on_zero_shared() @ 0x262765ae in /usr/bin/clickhouse
2022.04.29 00:12:57.703989 [ 4058 ] {} <Fatal> BaseDaemon: 22. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:175: std::__1::__shared_count::__release_shared() @ 0x17b65331 in /usr/bin/clickhouse
2022.04.29 00:12:57.839772 [ 4058 ] {} <Fatal> BaseDaemon: 23. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:216: std::__1::__shared_weak_count::__release_shared() @ 0x17b652d9 in /usr/bin/clickhouse
2022.04.29 00:12:58.396533 [ 4058 ] {} <Fatal> BaseDaemon: 24. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:704: std::__1::shared_ptr<DB::SeekableReadBuffer>::~shared_ptr() @ 0x258c8b4c in /usr/bin/clickhouse
2022.04.29 00:12:59.035949 [ 4058 ] {} <Fatal> BaseDaemon: 25. /build/build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.h:23: DB::ReadBufferFromRemoteFSGather::~ReadBufferFromRemoteFSGather() @ 0x26258031 in /usr/bin/clickhouse
2022.04.29 00:12:59.898668 [ 4058 ] {} <Fatal> BaseDaemon: 26. /build/build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.h:100: DB::ReadBufferFromS3Gather::~ReadBufferFromS3Gather() @ 0x262582fa in /usr/bin/clickhouse
2022.04.29 00:13:01.652061 [ 4058 ] {} <Fatal> BaseDaemon: 27. /build/build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54: std::__1::default_delete<DB::ReadBufferFromS3Gather>::operator()(DB::ReadBufferFromS3Gather*) const @ 0x2625824b in /usr/bin/clickhouse
2022.04.29 00:13:02.164544 [ 4058 ] {} <Fatal> BaseDaemon: 28. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:264: std::__1::__shared_ptr_pointer<DB::ReadBufferFromS3Gather*, std::__1::default_delete<DB::ReadBufferFromS3Gather>, std::__1::allocator<DB::ReadBufferFromS3Gather> >::__on_zero_shared() @ 0x262587ca in /usr/bin/clickhouse
2022.04.29 00:13:02.426634 [ 4058 ] {} <Fatal> BaseDaemon: 29. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:175: std::__1::__shared_count::__release_shared() @ 0x17b65331 in /usr/bin/clickhouse
2022.04.29 00:13:02.614435 [ 4058 ] {} <Fatal> BaseDaemon: 30. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:216: std::__1::__shared_weak_count::__release_shared() @ 0x17b652d9 in /usr/bin/clickhouse
2022.04.29 00:13:02.867516 [ 4058 ] {} <Fatal> BaseDaemon: 31. /build/build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:704: std::__1::shared_ptr<DB::ReadBufferFromRemoteFSGather>::~shared_ptr() @ 0x262aa5ac in /usr/bin/clickhouse
2022.04.29 00:13:03.201874 [ 4058 ] {} <Fatal> BaseDaemon: 32. /build/build_docker/../src/Disks/IO/ReadIndirectBufferFromRemoteFS.h:18: DB::ReadIndirectBufferFromRemoteFS::~ReadIndirectBufferFromRemoteFS() @ 0x262abba5 in /usr/bin/clickhouse
2022.04.29 00:13:03.398391 [ 4058 ] {} <Fatal> BaseDaemon: 33. /build/build_docker/../src/Disks/IO/ReadIndirectBufferFromRemoteFS.h:18: DB::ReadIndirectBufferFromRemoteFS::~ReadIndirectBufferFromRemoteFS() @ 0x262abbd9 in /usr/bin/clickhouse
2022.04.29 00:13:03.711699 [ 4058 ] {} <Fatal> BaseDaemon: 34. /build/build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:55: std::__1::default_delete<DB::SeekableReadBuffer>::operator()(DB::SeekableReadBuffer*) const @ 0x2620e58c in /usr/bin/clickhouse
2022.04.29 00:13:04.114308 [ 653 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**How to reproduce**
The assertion failed during merge. Related logs are attached.
[log_assert.txt](https://github.com/ClickHouse/ClickHouse/files/8590290/log_assert.txt)

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/36789#event-6555099518

### CODE REVIEW

File: src/Common/FileSegment.cpp [hunk 1]
```diff
@@ -366,14 +316,17 @@ bool FileSegment::reserve(size_t size)
     if (!size)
         throw Exception(ErrorCodes::REMOTE_FS_OBJECT_CACHE_ERROR, "Zero space reservation is not allowed");
 
-    assertNotDetached();
+    std::lock_guard cache_lock(cache->mutex);
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:319]: Comment, why we need both locks here.

File: src/Common/FileSegment.cpp [hunk 2]
```diff
@@ -366,14 +316,17 @@ bool FileSegment::reserve(size_t size)
...
+    std::lock_guard detach_lock(detach_mutex);
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:320]: Very complex, taking three mutexes at once. Need detailed explanation.

File: src/Common/FileSegment.cpp [hunk 3]
```diff
@@ -649,15 +607,37 @@ void FileSegment::assertCorrectnessImpl(std::lock_guard<std::mutex> & /* segment
...
-void FileSegment::assertDetachedStatus(std::lock_guard<std::mutex>  & /* segment_lock */) const
+
+void FileSegment::assertNotDetached(std::lock_guard<std::mutex> & segment_lock) const
 {
-    assert(download_state == State::EMPTY || hasFinalizedState());
+    if (is_detached)
+        throwDetachedUnlocked(segment_lock);
+}
+
+void FileSegment::assertDetachedStatus(std::lock_guard<std::mutex> & segment_lock) const
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:632]: I don't understand how this name related to function body. What is different from previous one?

File: src/Common/FileSegment.cpp [hunk 4]
```diff
@@ -649,15 +607,37 @@ void FileSegment::assertCorrectnessImpl(std::lock_guard<std::mutex> & /* segment
     assert(download_state != FileSegment::State::DOWNLOADED || std::filesystem::file_size(cache->getPathInLocalCache(key(), offset())) > 0);
 }
 
-void FileSegment::assertNotDetached() const
+void FileSegment::throwDetached() const
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:610]: `throwIfDetached`?

File: src/Common/FileSegment.h [hunk 5]
```diff
@@ -151,19 +153,30 @@ friend struct FileSegmentsHolder;
 
     static FileSegmentPtr getSnapshot(const FileSegmentPtr & file_segment, std::lock_guard<std::mutex> & cache_lock);
 
-    void detach(std::lock_guard<std::mutex> & cache_lock, std::lock_guard<std::mutex> & segment_lock);
+        void detach(
```
Comment (alesapin) [inline src/Common/FileSegment.h:156]:
```suggestion
    void detach(
```

File: src/Common/FileSegment.h [hunk 6]
```diff
@@ -151,19 +153,30 @@ friend struct FileSegmentsHolder;
...
     String getInfoForLogImpl(std::lock_guard<std::mutex> & segment_lock) const;
     void assertCorrectnessImpl(std::lock_guard<std::mutex> & segment_lock) const;
-    void assertNotDetached() const;
-    void assertDetachedStatus(std::lock_guard<std::mutex> & segment_lock) const;
     bool hasFinalizedState() const;
-    bool isDetached(std::lock_guard<std::mutex> & /* segment_lock */) const { return detached; }
+
+    bool isDetached(std::lock_guard<std::mutex> & /* segment_lock */) const { return is_detached; }
     void markAsDetached(std::lock_guard<std::mutex> & segment_lock);
+    [[noreturn]] void throwDetachedUnlocked(std::lock_guard<std::mutex> & segment_lock) const;
```
Comment (alesapin) [inline src/Common/FileSegment.h:176]: throwIfDetached.

File: src/Common/FileSegment.h [hunk 7]
```diff
@@ -197,9 +210,17 @@ friend struct FileSegmentsHolder;
...
+    /// global locking order rule:
+    /// 1. cache lock
+    /// 2. detach lock (if needed)
+    /// 3. segment lock
+
     mutable std::mutex mutex;
     std::condition_variable cv;
 
+    bool is_write_through_cache = false;
+    mutable std::mutex detach_mutex;
```
Comment (alesapin) [inline src/Common/FileSegment.h:222]: Scope of this mutex is not clear to me. What it protects? Maybe we can just make some flags (is_detached and so on) atomic?

File: src/Common/FileSegment.h [hunk 8]
```diff
@@ -226,14 +248,56 @@ friend struct FileSegmentsHolder;
...
+    {
+        file_segments.push_back(file_segment);
+    }
+
     FileSegments file_segments{};
 
     String toString();
 };
 
+class FileSegmentRangeWriter
```
Comment (alesapin) [inline src/Common/FileSegment.h:269]: What is it? Need a comment.

File: src/Common/FileSegment.cpp [hunk 9]
```diff
@@ -775,4 +763,116 @@ String FileSegmentsHolder::toString()
...
+
+    if (file_segments_holder.file_segments.empty() || current_file_segment.expired())
+        return;
+
+    auto file_segment = current_file_segment.lock();
+
+    std::lock_guard cache_lock(cache->mutex);
+    file_segment->complete(cache_lock);
+
+    finalized = true;
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:839]: Is it important to set this flag under lock?

File: src/Common/FileSegment.cpp [hunk 10]
```diff
@@ -684,29 +664,39 @@ bool FileSegment::hasFinalizedState() const
...
+void FileSegment::detach(
+    bool forced_detach,
+    std::lock_guard<std::mutex> & /* cache_lock */,
+    std::lock_guard<std::mutex> & /* detach_lock */,
+    std::lock_guard<std::mutex> & segment_lock)
+{
+    if (is_detached)
         return;
 
     markAsDetached(segment_lock);
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:682]: Is it possible to get rid of this function?

File: src/Common/FileSegment.cpp [hunk 11]
```diff
@@ -649,15 +607,37 @@ void FileSegment::assertCorrectnessImpl(std::lock_guard<std::mutex> & /* segment
...
+    throw Exception(
+        is_forcefully_detached ? ErrorCodes::CACHE_FILE_SEGMENT_IS_DETACHED : ErrorCodes::LOGICAL_ERROR,
+        "Cache file segment is in detached state, operation not allowed. "
+        "It can happen when cache was concurrently dropped with SYSTEM DROP FILESYSTEM CACHE FORCE. "
+        "Please, retry. File segment info: {}", getInfoForLogImpl(segment_lock));
 }
 
-void FileSegment::assertDetachedStatus(std::lock_guard<std::mutex>  & /* segment_lock */) const
+
+void FileSegment::assertNotDetached(std::lock_guard<std::mutex> & segment_lock) const
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:626]: It is very strange that we have `detach_mutex` but for some reason it's not requited in this function.

File: src/Common/FileSegment.cpp [hunk 12]
```diff
@@ -224,7 +238,12 @@ void FileSegment::write(const char * from, size_t size, size_t offset_)
                         "Attempt to write {} bytes to offset: {}, but current download offset is {}",
                         size, offset_, download_offset);
 
-    assertNotDetached();
+    std::lock_guard detach_lock(detach_mutex);
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:241]: Why we need it here? Add a comment.

File: src/Common/FileSegment.cpp [hunk 13]
```diff
@@ -160,6 +170,10 @@ String FileSegment::getDownloader() const
 bool FileSegment::isDownloader() const
 {
     std::lock_guard segment_lock(mutex);
+
+    if (is_forcefully_detached)
+        throwDetachedUnlocked(segment_lock);
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:175]: it's unexpected that method with `is` prefix can throw an exception.

File: src/Common/FileSegment.cpp [hunk 14]
```diff
@@ -56,6 +57,8 @@ FileSegment::FileSegment(
         /// needed, downloader is set on file segment creation).
         case (State::DOWNLOADING):
         {
+            /// On write-through cache we do not check downloader id.
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:60]: What does it mean? Where we don't check it?

File: src/IO/WriteBufferFromS3.cpp [hunk 15]
```diff
@@ -296,14 +262,8 @@ void WriteBufferFromS3::writePart()
     {
         UploadPartTask task;
         fillUploadRequest(task.req, part_tags.size() + 1);
-        if (file_segments_holder)
```
Comment (alesapin) [inline src/IO/WriteBufferFromS3.cpp:299]: Unclear changes to me.

**Review by alesapin — CHANGES_REQUESTED** [review]
Need clarification.

**Comment by kssenii** [comment]
Some changes still make sense, will remove only what is not needed with removal of forced detach

File: src/Common/FileSegment.cpp (hunk 3 above)
Comment (kssenii) [reply src/Common/FileSegment.cpp:697]: Added a comment

File: src/Common/FileSegment.cpp (hunk 10 above)
Comment (kssenii) [reply src/Common/FileSegment.cpp:739]: No, it is used many times in FileCache.cpp, it sets `is_detached=true` and updated ProfileEvents, if there was no profile events update or if this method needed in no more than 3 places (now about 6), then it could be removed

File: src/Common/FileSegment.cpp [hunk 16]
```diff
@@ -684,29 +730,30 @@ bool FileSegment::hasFinalizedState() const
...
+    std::lock_guard<std::mutex> & /* cache_lock */,
+    std::lock_guard<std::mutex> & segment_lock)
 {
-    if (detached)
+    if (is_detached)
         return;
 
     markAsDetached(segment_lock);
+    download_state = State::PARTIALLY_DOWNLOADED_NO_CONTINUATION;
+    downloader_id.clear();
```
Comment (kssenii) [inline src/Common/FileSegment.cpp:742]: the most important change here, though its absence should not affect anything because now detached status can be in 2 cases, which do not do any complex logic and check exactly for detached status:
1) there is only 1 remaining file segment holder && it does not need this segment anymore && this file segment was in cache and needs to be removed
2) in `read_from_cache_if_exists_otherwise_bypass_cache` case (`get` method can create them)

So this change not required, but it is more correct to have it (so the file segment state becomes consistent). Other remaining changes in this pr are just assertions and adding logical errors in some places.

File: src/Common/FileSegment.h [hunk 17]
```diff
@@ -215,7 +230,8 @@ friend struct FileSegmentsHolder;
 
     /// "detached" file segment means that it is not owned by cache ("detached" from cache).
     /// In general case, all file segments are owned by cache.
-    bool detached = false;
+    bool is_detached = false;
+    bool is_forcefully_detached = false;
```
Comment (alesapin) [inline src/Common/FileSegment.h:234]: redundant?

File: src/Common/FileSegment.cpp (hunk 16 above)
Comment (alesapin) [inline src/Common/FileSegment.cpp:742]: Add this comment to the code

File: src/Common/FileSegment.cpp [hunk 18]
```diff
@@ -342,6 +345,12 @@ FileSegment::State FileSegment::wait()
 {
     std::unique_lock segment_lock(mutex);
 
+    if (is_detached)
+        throw Exception(
+            ErrorCodes::LOGICAL_ERROR,
+            "Cache file segment is in detached state, operation not allowed. "
+            "It can happen when cache was concurrently dropped with SYSTEM DROP FILESYSTEM CACHE FORCE");
```
Comment (alesapin) [inline src/Common/FileSegment.cpp:352]: Is it still required?

**Review by alesapin — APPROVED** [review]
Small comments.

**Review by alesapin — APPROVED** [review]

**Comment by alesapin** [comment]
Failure unrelated.
