### PR TITLE
Fix bug where materialized views with UNIONs don't work on new replicas

### LINKED ISSUE #77569: BAD_ARGUMENT error after server restart when using UNION in materialized view
### Company or project name

ClickHouse Inc.

### Describe what's wrong

Since https://github.com/ClickHouse/ClickHouse/pull/72347 UNION is allowed in materialized views. This works as expected directly after creating the materialized view. However, **after a server restart**, the same INSERT into the source table fails with error `Code: 36. DB::Exception: UNION mode UNION_DEFAULT must be normalized. (BAD_ARGUMENTS)`

### Does it reproduce on the most recent release?

Only tested in ClickHouse Cloud with 24.12

### How to reproduce

The following example creates two source table and a materialized view that runs `UNION` over the two source tables.

```-- Create first source table
CREATE TABLE source_1
(
    timestamp DateTime,
    value Float64
) ENGINE = MergeTree()
ORDER BY timestamp;

-- Create second source table
CREATE TABLE source_2
(
    timestamp DateTime,
    value Float64
) ENGINE = MergeTree()
ORDER BY timestamp;

-- Create target table
CREATE TABLE target
(
    timestamp DateTime,
    value Float64
) ENGINE = MergeTree()
ORDER BY timestamp;

-- Create materialized view (problematic UNION ALL inside WITH)
CREATE MATERIALIZED VIEW mv_test TO target AS
WITH source_data AS (
    SELECT timestamp, value FROM source_1
    UNION ALL
    SELECT timestamp, value FROM source_2
)
SELECT timestamp, value FROM source_data;
```

After creating those tables, INSERTs work without problems.
After server restart, INSERTs fail with the below error.

### Expected behavior

INSERTs still work after server restart.

### Error message and/or stacktrace

```
Code: 36. DB::Exception: UNION mode UNION_DEFAULT must be normalized. (BAD_ARGUMENTS) (version 24.12.1.18074 (official build))

0. ./build_docker/./src/Common/Exception.cpp:107: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d92193b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000880d5cc
2. DB::Exception::Exception<char const*>(int, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x000000000ad4166b
3. ./build_docker/./src/Analyzer/UnionNode.cpp:49: DB::UnionNode::UnionNode(std::shared_ptr<DB::Context>, DB::SelectUnionMode) @ 0x0000000011b2f5b8
4. ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35: DB::(anonymous namespace)::QueryTreeBuilder::buildSelectWithUnionExpression(std::shared_ptr<DB::IAST> const&, bool, String const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&) const @ 0x0000000011b9d6a9
5. ./build_docker/./src/Analyzer/QueryTreeBuilder.cpp:895: DB::(anonymous namespace)::QueryTreeBuilder::buildSelectExpression(std::shared_ptr<DB::IAST> const&, bool, String const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&) const @ 0x0000000011b9e915
6. ./build_docker/./src/Analyzer/QueryTreeBuilder.cpp:164: DB::(anonymous namespace)::QueryTreeBuilder::buildSelectOrUnionExpression(std::shared_ptr<DB::IAST> const&, bool, String const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&) const @ 0x0000000011b9a8c6
7. ./build_docker/./src/Analyzer/QueryTreeBuilder.cpp:144: DB::buildQueryTree(std::shared_ptr<DB::IAST>, std::shared_ptr<DB::Context const>) @ 0x0000000011b9a606
8. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:138: DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) (.llvm.7303357092807998720) @ 0x00000000124dba25
9. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:167: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000124d9b1c
10. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:204: DB::InterpreterSelectQueryAnalyzer::getSampleBlock(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&) @ 0x00000000124dc759
11. ./build_docker/./src/Processors/Transforms/buildPushingToViewsChain.cpp:351: DB::generateViewChain(std::shared_ptr<DB::Context const>, unsigned long, DB::StorageID const&, std::shared_ptr<DB::ThreadGroup>, DB::Chain&, std::shared_ptr<DB::ViewsData>, std::shared_ptr<DB::ThreadStatusesHolder>, bool, DB::Block const&, bool) @ 0x00000000143303bf
12. ./build_docker/./src/Processors/Transforms/buildPushingToViewsChain.cpp:524: DB::buildPushingToViewsChain(std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, std::shared_ptr<DB::IAST> const&, unsigned long, bool, std::shared_ptr<DB::ThreadStatusesHolder>, std::shared_ptr<DB::ThreadGroup>, std::atomic<unsigned long>*, bool, DB::Block const&) @ 0x0000000014334018
13. ./build_docker/./src/Interpreters/InterpreterInsertQuery.cpp:366: DB::InterpreterInsertQuery::buildSink(std::shared_ptr<DB::IStorage> const&, unsigned long, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::ThreadStatusesHolder>, std::shared_ptr<DB::ThreadGroup>, std::atomic<unsigned long>*) @ 0x000000001247ac36
14. ./build_docker/./src/Interpreters/InterpreterInsertQuery.cpp:458: DB::InterpreterInsertQuery::buildPreAndSinkChains(unsigned long, unsigned long, std::shared_ptr<DB::IStorage>, unsigned long, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&) @ 0x000000001247b99e
15. ./build_docker/./src/Interpreters/InterpreterInsertQuery.cpp:710: DB::InterpreterInsertQuery::execute() @ 0x000000001247fed5
16. ./build_docker/./src/Interpreters/executeQuery.cpp:1374: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000129294c3
17. ./build_docker/./src/Interpreters/executeQuery.cpp:1673: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000001292dba4
18. ./build_docker/./src/Server/HTTPHandler.cpp:582: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000013ef7112
19. ./build_docker/./src/Server/HTTPHandler.cpp:751: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000013efb721
20. ./build_docker/./src/Server/HTTP/HTTPServerConnection.cpp:71: DB::HTTPServerConnection::run() @ 0x0000000013fa1a89
21. ./src/Server/TCPProtocolStackHandler.h:38: DB::TCPProtocolStackHandler::run() @ 0x000000000dc4b27c
22. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000016ede847
23. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000016edecd9
24. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000016ea483c
25. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000016ea2ddd
26. ? @ 0x000079737917fac3
27. ? @ 0x0000797379211850
```

### Additional context

The reproducer was run ClickHouse Cloud with the currently available 24.12 version. The example was done with **new analyzer enabled.**

### PR DESCRIPTION
**Pull request by samay-sharma**
Should fix https://github.com/ClickHouse/ClickHouse/issues/77569

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow materialized views with UNIONs to work correctly on new replicas.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/DatabaseReplicated.cpp [hunk 1]
```diff
@@ -1463,8 +1465,11 @@ void DatabaseReplicated::recoverLostReplica(const ZooKeeperPtr & current_zookeep
                 }
 
                 auto query_ast = parseQueryFromMetadataInZooKeeper(table_name, create_query_string);
-
                 auto create_query_context = make_query_context();
+
```
Comment (mstetsyuk) [inline src/Databases/DatabaseReplicated.cpp:1469]: nit: this probably belongs in `InterpreterCreateQuery`

File: src/Databases/DatabaseReplicated.cpp [hunk 2]
```diff
@@ -1463,8 +1465,11 @@ void DatabaseReplicated::recoverLostReplica(const ZooKeeperPtr & current_zookeep
...
+                NormalizeSelectWithUnionQueryVisitor::Data data{create_query_context->getSettingsRef()[Setting::union_default_mode]};
```
Comment (mstetsyuk) [inline src/Databases/DatabaseReplicated.cpp:1470]: nit: this probably belongs in `InterpreterCreateQuery`

**Comment by godofcodeeyes** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

File: src/Databases/DatabaseReplicated.cpp (hunk 2 above)
Comment (nikitamikhaylov) [reply src/Databases/DatabaseReplicated.cpp:1470]: Interestingly, DatabaseBackup and DatabaseOrdinary have the same code. Maybe indeed it is worth to move it to the InterpreterCreateQuery instead.

**Review by nikitamikhaylov — APPROVED** [review]
