### PR TITLE
Fix clash of constant strings in aggregate function, prewhere and join

### LINKED ISSUE #36891: unexpected errors with toDateTime function and join
```sql
drop table if exists e;

CREATE TABLE e
(   a UInt64, t DateTime )
Engine=MergeTree PARTITION BY toDate(t)
ORDER BY tuple()

insert into e select 0, toDateTime('2020-02-01 12:00:01') + interval number month from numbers(10);

SELECT sumIf( 1, if( 1, toDateTime('2020-01-01 00:00:00', 'UTC'), toDateTime('1970-01-01 00:00:00', 'UTC')) > t ) 
FROM e JOIN ( SELECT 1 joinKey) AS da ON joinKey = a
WHERE  t >= toDateTime('2021-07-19T13:00:00', 'UTC') AND t <= toDateTime('2021-07-19T13:59:59', 'UTC');

Received exception from server (version 22.5.1):
DB::Exception: Illegal type of argument #2 'timezone' of function toDateTime, expected const String, got String: 
While processing toDateTime('2020-01-01 00:00:00', 'UTC') > t. (ILLEGAL_COLUMN)



SELECT sumIf( 1, if( 1, toDateTime('2020-01-01 00:00:00', 'UTC'), toDateTime('1970-01-01 00:00:00', 'UTC')) > t ) 
FROM e JOIN ( SELECT 1 joinKey) AS da ON joinKey = a
WHERE  t >= toDateTime('2020-01-01 00:00:00', 'UTC') AND t <= toDateTime('2021-07-19T13:59:59', 'UTC');

Received exception from server (version 22.5.1):
Code: 10. DB::Exception: Received from localhost:9000. 
DB::Exception: Not found column toDateTime('2020-01-01 00:00:00', 'UTC') in block. (NOT_FOUND_COLUMN_IN_BLOCK)
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix unexpected errors with a clash of constant strings in aggregate function, prewhere and join. Close https://github.com/ClickHouse/ClickHouse/issues/36891

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/ExpressionActions.cpp [hunk 1]
```diff
@@ -1034,19 +1034,16 @@ void ExpressionActionsChain::ArrayJoinStep::finalize(const NameSet & required_ou
...
     , analyzed_join(std::move(analyzed_join_))
     , join(std::move(join_))
 {
     for (const auto & column : required_columns_)
         required_columns.emplace_back(column.name, column.type);
 
-    NamesAndTypesList result_names_and_types = required_columns;
-    analyzed_join->addJoinedColumnsAndCorrectTypes(result_names_and_types, true);
-    for (const auto & [name, type] : result_names_and_types)
-        /// `column` is `nullptr` because we don't care on constness here, it may be changed in join
```
Comment (vdimir) [inline src/Interpreters/ExpressionActions.cpp:1048]: > `column` is `nullptr` because we don't care on constness here, it may be changed in join

Maybe that was fixed later in other way (it's good to find what change exactly, but seems tricky), now all test passed without replacing `column` to `nullptr`

Comment (vdimir) [inline src/Interpreters/ExpressionActions.cpp:1048]: > `column` is `nullptr` because we don't care on constness here, it may be changed in join

Maybe that was fixed later in other way (it's good to find what change exactly, but seems tricky), now all test passed without replacing `column` to `nullptr`

**Review by novikd — APPROVED** [review]
