### PR TITLE
Fix CaresPTRResolver race condition

### LINKED ISSUE #39807: When I upgrade to 22.7.1.2484 from 21.8.14.5, after a few minutes all servers crash.The part of log are as follows.
image

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
A segmentation fault that has CaresPTRResolver::resolve in the stack trace has been reported:

```
 {} <Fatal> BaseDaemon: 4. ? @ 0xbb48f5c in /usr/bin/clickhouse,2022-08-05T16:14:36.963240840Z
 <Fatal> BaseDaemon: 3. DB::CaresPTRResolver::resolve(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xbb5196c in /usr/bin/clickhouse",2022-08-05T16:14:36.963236350Z
<Fatal> BaseDaemon: 2. ? @ 0x1b4c7163 in /usr/bin/clickhouse,2022-08-05T16:14:36.963230570Z
{} <Fatal> BaseDaemon: Stack trace: 0x1b4c7163 0xbb5196c 0xbb48f5c,2022-08-05T16:14:36.963204690Z
{} <Fatal> BaseDaemon: Address: 0x8 Access: read. Address not mapped to object.,2022-08-05T16:14:36.963198870Z
{} <Fatal> BaseDaemon: (version 22.7.2.15 (official build), build id: A975FB2E13DEF38A) (from thread 208) (no query) Received signal Segmentation fault (11)",2022-08-05T16:14:36.963170759Z
```
Looking at the full logs, this happened in multiple threads, which raises the suspicious of race conditions.

`DB::DNSResolver::reverseResolve` is called from multiple threads. The `DB::DNSPTRResolverProvider::get` method, called by reverseResolve, would return a singleton of `DB::CaresPTRResolver`. `DB::CaresPTRResolver` is not thread safe, mainly because of the `channel` member. The decision of having CaresPTRResolver as a singleton was made because of two reasons: 1. c-ares library initialization should happen only once 2. premature optimization.

This PR fixes this issue by using a fresh instance of CaresPTRResolver for each and every thread. Single initialization is handled by static initialization, which is thread safe and happens only once.

Tested with the below unit test:

```
TEST(Common, ReverseDNS)
{
    auto func = []()
    {
        auto resolver = DNSPTRResolverProvider::get();
        auto result = resolver->resolve("");
        assert(result.empty());
    };

    auto number_of_threads = 100u;
    std::vector<std::thread> threads;
    threads.reserve(number_of_threads);

    for (auto i = 0u; i < number_of_threads; i++)
    {
        threads.emplace_back(func);
    }

    for (auto & thread : threads)
    {
        thread.join();
    }
}
```

Previously, most of the times, it would crash with segfault. After the changes, it never crashed. Did around 10 runs.

Might close/ fix #39807

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by den-crane** [comment]
I wonder is this code CaresPTRResolver works only if auth by hostregex is enabled? 

May be (we/I) can test it by bombarding a server by hundreds  parallel incoming connections/logins?

**Comment by arthurpassos** [comment]
> I wonder is this code CaresPTRResolver works only if auth by hostregex is enabled? Or it works always (unconditionally) during connecting to a server?
> 
> May be (we/I) can test it by bombarding a server by hundreds parallel incoming connections/logins?

Any reverse DNS resolution performed by ClickHouse will go through this code, with the exception of cached resolutions

**Comment by arthurpassos** [comment]
Hi. There is one fast test failure, but doesn't seem related: `2022-08-11 21:11:26 02102_row_binary_with_names_and_types:                                  [ FAIL ] 2.64 sec. - having stderror: `. Maybe a re-run will do the trick? @alexey-milovidov

**Comment by arthurpassos** [comment]
@tavplubix could you review it? since you already have context

File: src/Common/CaresPTRResolver.cpp [hunk 1]
```diff
@@ -45,7 +50,12 @@ namespace DB
     CaresPTRResolver::~CaresPTRResolver()
     {
         ares_destroy(channel);
-        ares_library_cleanup();
+        /*
+         * Library initialization is currently done only once in the constructor. Multiple instances of CaresPTRResolver
+         * will be used in the lifetime of ClickHouse, thus it's problematic to have de-init here.
+         * In a practical view, it makes little to no sense to de-init a DNS library since DNS requests will happen
+         * until the end of the program. Hence, ares_library_cleanup() will not be called.
+         * */
```
Comment (tavplubix) [inline src/Common/CaresPTRResolver.cpp:58]: Does `ares_library_cleanup` free some memory? It may cause test failures with LeakSanitizer

Comment (arthurpassos) [reply src/Common/CaresPTRResolver.cpp:58]: As of now, it doesn't. It only re-sets a couple of global variables, see implementation: https://github.com/c-ares/c-ares/blob/main/src/lib/ares_library_init.c#L85. Plus, `ares_library_init` doesn't seem allocate anything, see implementation: https://github.com/c-ares/c-ares/blob/main/src/lib/ares_library_init.c#L54.

In general, it's not a good thing to rely on these implementation details, but it looks better than alternative approaches like having some sort of lock to call `ares_library_init` & `ares_library_cleanup` multiple times in a thread safe manner.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Performance tests - hashed_dictionary - #40268
Stateless tests (ubsan) - 00725_memory_tracking - #40199
