### PR TITLE
fix crash caused by merge_tree_min_read_task_size being set to 0

### LINKED ISSUE #84714: Don't set `merge_tree_min_read_task_size` to 0
### Describe the bug

It gives issues with LWU

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/d8a54ea0-dc9f-4211-b555-2f3f4d85e8b5

### Error message and/or stacktrace

Stack trace:

```
2025.07.30 11:32:49.056083 [ 2445753 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.07.30 11:32:49.056107 [ 2445753 ] {} <Fatal> BaseDaemon: (version 25.8.1.1849 (official build), build id: 1CD0CAA0879941FFF6DAE067F69A8216210FC928, git hash: ac2444bf98d85ec097acfb7a19158f3e996ff51e, architecture: x86_64) (from thread 2445756) Received signal 8
2025.07.30 11:32:49.056113 [ 2445753 ] {} <Fatal> BaseDaemon: Signal description: Arithmetic exception
2025.07.30 11:32:49.056114 [ 2445753 ] {} <Fatal> BaseDaemon: Integer divide by zero.
2025.07.30 11:32:49.056137 [ 2445753 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000622be9196ca1 0x0000622be9b0c30b 0x0000622be9b09ede 0x0000622be9b3d344 0x0000622be9afa535 0x0000622be9acde34 0x0000622be9acfb6e 0x0000622be9ad1e55 0x0000622be9ae374a 0x0000622be9ae4f51 0x0000622be9a732db 0x0000622be9aa5314 0x0000622be5f01e62 0x0000622be5f01b9c 0x0000622be61f95c3 0x0000622be61f353b 0x0000622be947848f 0x0000622be9492324 0x0000622bf155f187 0x0000622bf155f765 0x0000622bf14fe93f 0x0000622bf14fc011 0x00007ed6eeea27f1 0x00007ed6eef33c9c
2025.07.30 11:32:49.056165 [ 2445753 ] {} <Fatal> BaseDaemon: ########################################
2025.07.30 11:32:49.056214 [ 2445753 ] {} <Fatal> BaseDaemon: (version 25.8.1.1849 (official build), build id: 1CD0CAA0879941FFF6DAE067F69A8216210FC928, git hash: ac2444bf98d85ec097acfb7a19158f3e996ff51e) (from thread 2445756) (query_id: 11151ca1-021c-4ee8-a880-b37f2f4ba68d) (query: SELECT count() FROM t0 SETTINGS apply_mutations_on_fly = 1, merge_tree_min_read_task_size = 0;) Received signal Arithmetic exception (8)
2025.07.30 11:32:49.056241 [ 2445753 ] {} <Fatal> BaseDaemon: Integer divide by zero.
2025.07.30 11:32:49.056276 [ 2445753 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000622be9196ca1 0x0000622be9b0c30b 0x0000622be9b09ede 0x0000622be9b3d344 0x0000622be9afa535 0x0000622be9acde34 0x0000622be9acfb6e 0x0000622be9ad1e55 0x0000622be9ae374a 0x0000622be9ae4f51 0x0000622be9a732db 0x0000622be9aa5314 0x0000622be5f01e62 0x0000622be5f01b9c 0x0000622be61f95c3 0x0000622be61f353b 0x0000622be947848f 0x0000622be9492324 0x0000622bf155f187 0x0000622bf155f765 0x0000622bf14fe93f 0x0000622bf14fc011 0x00007ed6eeea27f1 0x00007ed6eef33c9c
2025.07.30 11:32:49.076073 [ 2445753 ] {} <Fatal> BaseDaemon: 3. src/Storages/MergeTree/PatchParts/RangesInPatchParts.cpp:186: DB::RangesInPatchParts::optimize() @ 0x000000001e28fca1
2025.07.30 11:32:49.107304 [ 2445753 ] {} <Fatal> BaseDaemon: 4. src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:242: DB::MergeTreeReadPoolBase::fillPerPartInfos(DB::Settings const&) @ 0x000000001ec0530b
2025.07.30 11:32:49.131477 [ 2445753 ] {} <Fatal> BaseDaemon: 5. src/Storages/MergeTree/MergeTreeReadPoolBase.cpp:56: DB::MergeTreeReadPoolBase::MergeTreeReadPoolBase(DB::RangesInDataParts&&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>, std::shared_ptr<DB::StorageSnapshot> const&, std::shared_ptr<DB::PrewhereInfo> const&, DB::ExpressionActionsSettings const&, DB::MergeTreeReaderSettings const&, std::vector<String, std::allocator<String>> const&, DB::MergeTreeReadPoolBase::PoolSettings const&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001ec02ede
2025.07.30 11:32:49.145363 [ 2445753 ] {} <Fatal> BaseDaemon: 6. src/Storages/MergeTree/MergeTreeReadPoolInOrder.cpp:25: DB::MergeTreeReadPoolInOrder::MergeTreeReadPoolInOrder(bool, DB::MergeTreeReadType, DB::RangesInDataParts, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>, std::shared_ptr<DB::StorageSnapshot> const&, std::shared_ptr<DB::PrewhereInfo> const&, DB::ExpressionActionsSettings const&, DB::MergeTreeReaderSettings const&, std::vector<String, std::allocator<String>> const&, DB::MergeTreeReadPoolBase::PoolSettings const&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001ec36344
2025.07.30 11:32:49.292099 [ 2445753 ] {} <Fatal> BaseDaemon: 7. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::MergeTreeReadPoolInOrder* std::construct_at[abi:se190107]<DB::MergeTreeReadPoolInOrder, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&, DB::MergeTreeReadPoolInOrder*>(DB::MergeTreeReadPoolInOrder*, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&) @ 0x000000001ebf3535
2025.07.30 11:32:49.379423 [ 2445753 ] {} <Fatal> BaseDaemon: 8.0. inlined from contrib/llvm-project/libcxx/include/__memory/construct_at.h:49: DB::MergeTreeReadPoolInOrder* std::__construct_at[abi:se190107]<DB::MergeTreeReadPoolInOrder, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&, DB::MergeTreeReadPoolInOrder*>(DB::MergeTreeReadPoolInOrder*, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&)
2025.07.30 11:32:49.379469 [ 2445753 ] {} <Fatal> BaseDaemon: 8.1. inlined from contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:328: void std::allocator_traits<std::allocator<DB::MergeTreeReadPoolInOrder>>::construct[abi:se190107]<DB::MergeTreeReadPoolInOrder, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&, void, 0>(std::allocator<DB::MergeTreeReadPoolInOrder>&, DB::MergeTreeReadPoolInOrder*, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&)
2025.07.30 11:32:49.379502 [ 2445753 ] {} <Fatal> BaseDaemon: 8.2. inlined from contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:264: __shared_ptr_emplace<bool &, DB::MergeTreeReadType &, DB::RangesInDataParts &, std::shared_ptr<const DB::MergeTreeData::IMutationsSnapshot> &, std::unordered_map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, DB::Field, std::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, DB::Field> > > &, std::shared_ptr<DB::StorageSnapshot> &, std::shared_ptr<DB::PrewhereInfo> &, DB::ExpressionActionsSettings &, DB::MergeTreeReaderSettings &, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > &, DB::MergeTreeReadPoolBase::PoolSettings &, const DB::MergeTreeReadTask::BlockSizeParams &, std::shared_ptr<const DB::Context> &, std::allocator<DB::MergeTreeReadPoolInOrder>, 0>
2025.07.30 11:32:49.379551 [ 2445753 ] {} <Fatal> BaseDaemon: 8.3. inlined from contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:843: std::shared_ptr<DB::MergeTreeReadPoolInOrder> std::allocate_shared[abi:se190107]<DB::MergeTreeReadPoolInOrder, std::allocator<DB::MergeTreeReadPoolInOrder>, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&, 0>(std::allocator<DB::MergeTreeReadPoolInOrder> const&, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&)
2025.07.30 11:32:49.379600 [ 2445753 ] {} <Fatal> BaseDaemon: 8.4. inlined from contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:851: std::shared_ptr<DB::MergeTreeReadPoolInOrder> std::make_shared[abi:se190107]<DB::MergeTreeReadPoolInOrder, bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&, 0>(bool&, DB::MergeTreeReadType&, DB::RangesInDataParts&, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>&, std::unordered_map<String, DB::Field, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, DB::Field>>>&, std::shared_ptr<DB::StorageSnapshot>&, std::shared_ptr<DB::PrewhereInfo>&, DB::ExpressionActionsSettings&, DB::MergeTreeReaderSettings&, std::vector<String, std::allocator<String>>&, DB::MergeTreeReadPoolBase::PoolSettings&, DB::MergeTreeReadTask::BlockSizeParams const&, std::shared_ptr<DB::Context const>&)
2025.07.30 11:32:49.379624 [ 2445753 ] {} <Fatal> BaseDaemon: 8. src/Processors/QueryPlan/ReadFromMergeTree.cpp:627: DB::ReadFromMergeTree::readInOrder(DB::RangesInDataParts, std::vector<String, std::allocator<String>>, DB::MergeTreeReadPoolBase::PoolSettings, DB::MergeTreeReadType, unsigned long) @ 0x000000001ebc6e34
2025.07.30 11:32:49.485433 [ 2445753 ] {} <Fatal> BaseDaemon: 9. src/Processors/QueryPlan/ReadFromMergeTree.cpp:759: DB::ReadFromMergeTree::read(DB::RangesInDataParts, std::vector<String, std::allocator<String>>, DB::MergeTreeReadType, unsigned long, unsigned long, bool) @ 0x000000001ebc8b6e
2025.07.30 11:32:49.584326 [ 2445753 ] {} <Fatal> BaseDaemon: 10. src/Processors/QueryPlan/ReadFromMergeTree.cpp:1070: DB::ReadFromMergeTree::spreadMarkRangesAmongStreams(DB::RangesInDataParts&&, unsigned long, std::vector<String, std::allocator<String>> const&) @ 0x000000001ebcae55
2025.07.30 11:32:49.705082 [ 2445753 ] {} <Fatal> BaseDaemon: 11. src/Processors/QueryPlan/ReadFromMergeTree.cpp:2333: DB::ReadFromMergeTree::spreadMarkRanges(DB::RangesInDataParts&&, unsigned long, DB::ReadFromMergeTree::AnalysisResult&, std::optional<DB::ActionsDAG>&) @ 0x000000001ebdc74a
2025.07.30 11:32:49.812122 [ 2445753 ] {} <Fatal> BaseDaemon: 12. src/Processors/QueryPlan/ReadFromMergeTree.cpp:2446: DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x000000001ebddf51
2025.07.30 11:32:49.817997 [ 2445753 ] {} <Fatal> BaseDaemon: 13. src/Processors/QueryPlan/ISourceStep.cpp:20: DB::ISourceStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000001eb6c2db
2025.07.30 11:32:49.842166 [ 2445753 ] {} <Fatal> BaseDaemon: 14. src/Processors/QueryPlan/QueryPlan.cpp:202: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001eb9e314
2025.07.30 11:32:49.864892 [ 2445753 ] {} <Fatal> BaseDaemon: 15. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x000000001affae62
2025.07.30 11:32:49.885142 [ 2445753 ] {} <Fatal> BaseDaemon: 16. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001affab9c
2025.07.30 11:32:49.925562 [ 2445753 ] {} <Fatal> BaseDaemon: 17. src/Interpreters/executeQuery.cpp:1561: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001b2f25c3
2025.07.30 11:32:49.973178 [ 2445753 ] {} <Fatal> BaseDaemon: 18. src/Interpreters/executeQuery.cpp:1769: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001b2ec53b
2025.07.30 11:32:50.008944 [ 2445753 ] {} <Fatal> BaseDaemon: 19. src/Server/TCPHandler.cpp:739: DB::TCPHandler::runImpl() @ 0x000000001e57148f
2025.07.30 11:32:50.069309 [ 2445753 ] {} <Fatal> BaseDaemon: 20. src/Server/TCPHandler.cpp:2740: DB::TCPHandler::run() @ 0x000000001e58b324
2025.07.30 11:32:50.073364 [ 2445753 ] {} <Fatal> BaseDaemon: 21. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000026658187
2025.07.30 11:32:50.078021 [ 2445753 ] {} <Fatal> BaseDaemon: 22. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000026658765
2025.07.30 11:32:50.082691 [ 2445753 ] {} <Fatal> BaseDaemon: 23. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000265f793f
2025.07.30 11:32:50.087186 [ 2445753 ] {} <Fatal> BaseDaemon: 24. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000265f5011
2025.07.30 11:32:50.087222 [ 2445753 ] {} <Fatal> BaseDaemon: 25. start_thread @ 0x00000000000a27f1
2025.07.30 11:32:50.087246 [ 2445753 ] {} <Fatal> BaseDaemon: 26. __clone3 @ 0x0000000000133c9c
2025.07.30 11:32:50.230623 [ 2446428 ] {} <Trace> default.t0 (1500e37a-3d50-43a3-a5ca-25fe2a313b40): Unloaded primary key for outdated parts all_1_1_0
2025.07.30 11:32:50.296564 [ 2445753 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 82FA3489EEB1090C39BBE4AC76DE3F2F)
```

### PR DESCRIPTION
**Pull request by ylw510**
When `merge_tree_min_read_task_size` is set to 0, `RangesInPatchParts::optimize` encounters a division by zero, causing a crash.  Detect this case and throw an error instead.

Closes: #84714 

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix crash caused by `merge_tree_min_read_task_size` being set to 0

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/MergeTree/PatchParts/RangesInPatchParts.cpp [hunk 1]
```diff
@@ -188,6 +189,14 @@ void RangesInPatchParts::optimize()
 
         for (auto & range : optimized_ranges)
         {
+            if (max_granules_in_range == 0)
```
Comment (PedroTadim) [inline src/Storages/MergeTree/PatchParts/RangesInPatchParts.cpp]: Could you check how other settings like this one were fixed? The `merge_tree_min_read_task_size` should be declared as `SettingsNonZeroUInt64`.

Comment (ylw510) [reply src/Storages/MergeTree/PatchParts/RangesInPatchParts.cpp]: > Could you check how other settings like this one were fixed? The `merge_tree_min_read_task_size` should be declared as `SettingsNonZeroUInt64`.

Thanks for the reminder.I will do it.

Comment (ylw510) [reply src/Storages/MergeTree/PatchParts/RangesInPatchParts.cpp]: Done.

File: tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+TABLE_NAME="table_${RANDOM}${RANDOM}"
+
+$CLICKHOUSE_CLIENT -q "SET allow_experimental_lightweight_update = 1"
+
+# catch error BAD_ARGUMENTS
+$CLICKHOUSE_CLIENT -q "SET merge_tree_min_read_task_size = 0; -- { serverError BAD_ARGUMENTS }"
+
+$CLICKHOUSE_CLIENT -q "CREATE TABLE ${TABLE_NAME} (c0 Int) ENGINE = MergeTree() ORDER BY tuple()
+ SETTINGS enable_block_number_column = 1, enable_block_offset_column = 1;"
```
Comment (bharatnc) [inline tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: Let's also add another case where we first create the table and then try to alter the table with the invalid setting.

Comment (ylw510) [reply tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: > Let's also add another case where we first create the table and then try to alter the table with the invalid setting.

I understand your point. But since `merge_tree_min_read_task_size` is a session-level setting, is it really necessary to modify it using ALTER TABLE?
If use ALTER TABLE to modify `merge_tree_min_read_task_size`, the result will be as shown in the figure below. Is this the result you want?

image

Comment (bharatnc) [reply tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: yes, you're right. I didn't notice that it's a session level setting earlier.

File: tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh [hunk 3]
```diff
@@ -0,0 +1,28 @@
+#!/usr/bin/env bash
```
Comment (bharatnc) [inline tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: Btw, `.sql` tests are preferred over `.sh` tests whenever possible. There doesn't seem to be any particular reason that it should be a `.sh` test - or is there one?

**Review by bharatnc — APPROVED** [review]

File: tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh (hunk 3 above)
Comment (ylw510) [reply tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: > Btw, `.sql` tests are preferred over `.sh` tests whenever possible. There doesn't seem to be any particular reason that it should be a `.sh` test - or is there one?

There’s nothing special, I just got used to writing it as a .sh test. Thanks for the reminder, I’ll change it to a .sql test.

Comment (ylw510) [reply tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: By the way, I’d like to ask about the timing for adding the no-fasttest tag: which kinds of tests need the no-fasttest tag, and in what scenarios is it not necessary?
Is there any documentation here that explains the purpose of these tags?

Comment (bharatnc) [reply tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: The fasttest binary is usually not built with many of the libraries like `S3`, `H3`, `MySQL` etc. So for such tests that depend on those libraries, you would usually just label them as `no-fasttest` so that the tests are only run with binary built with all the libraries (those are the stateless test runs that you see on CI which follows fasttest). 

There is a bit of documentation about it [here](https://clickhouse.com/docs/development/tests#restricting-test-runs) under the table in that section. Usually if the fasttest fails, you would know why and add the tags accordingly.

Comment (ylw510) [reply tests/queries/0_stateless/03604_test_merge_tree_min_read_task_size_is_zero.sh]: Thanks for reply.I got it.

**Comment by ylw510** [comment]
@bharatnc Hi, are there any other adjustments needed for this PR

**Comment by bharatnc** [comment]
> @bharatnc Hi, are there any other adjustments needed for this PR

No, changes look good and test failures not related.
