### PR TITLE
Try fix data race on default ssl context

### LINKED ISSUE #85412: Data race on `cert_cb` (openssl)
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/PRs/85378/9c3c95dd94efdde041befc60b845404f6a329b82//integration_tests_tsan_4_6/integration_run_parallel_0.log

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Unfortunately, I don't know how to reproduce it. It has only two failures in CI so far: [link](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcldGVzdF9rZWVwZXJfc2VjdXJlX2NsaWVudCUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==)

Closes: #85412

### CODE REVIEW

**Comment by nickitat** [comment]
`Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, parallel)` - #54748
`Stateless tests (amd_debug, distributed plan, s3 storage, parallel)` - #54748
`Integration tests (tsan, 4/6) (pull_request)` - https://github.com/ClickHouse/ClickHouse/issues/85493

File: programs/server/Server.cpp [hunk 1]
```diff
@@ -2340,8 +2340,23 @@ try
...
+#if USE_SSL
+    /// We may notice that try to reload certificates twice within this function.
+    /// First time here before starting the `servers_to_start_before_tables`, and then
+    /// one more time before starting the `servers`. The problem we're trying to avoid is:
+    /// 1. We create a socket for keeper secure protocol (w/o starting a server yet). That creates a SSL context (in particular, it might be the default context).
+    /// 2. We then start this server a few lines below. While handling the first request, it will access (read) certs.
+    /// 3. A little further down, we reload certificates before starting the rest of the servers.
+    /// 4. `CertificateReloader` will set its custom `cert_cb` to the default context if it is not initialized yet (see `CertificateReloader::init()`).
+    /// 5. Items (2) and (4) are not synchronized, so there might be a data race for example (see https://github.com/ClickHouse/ClickHouse/issues/85412).
+    CertificateReloader::instance().tryLoad(config());
```
Comment (azat) [inline programs/server/Server.cpp:2354]: We can also return this global context with a lock holder, but I guess it does not worth it, and this is enough

**Review by azat — APPROVED** [review]
