### PR TITLE
Fix crash when selecting subcolumns from Buffer table

### LINKED ISSUE #102104: Logical error: Unknown virtual column: 'A (STID: 3381-2a5e)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: Unknown virtual column: 'A (STID: 3381-2a5e)
CI report: [BuzzHouse (amd_msan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=bee4543f12f9822940d563c860aea9214172e5ba&name_0=MasterCI&name_1=BuzzHouse%20%28amd_msan%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiBVbmtub3duIHZpcnR1YWwgY29sdW1uOiAnJ0EgKFNUSUQ6IDMzODEtMmE1ZSknCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdCdXp6SG91c2UgKGFtZF9tc2FuKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBiYXNlX3JlZiBJTiAoJycsICdtYXN0ZXInKSkKICAgIEFORCB0ZXN0X2NvbnRleHRfcmF3IExJS0UgJyVFeGNlcHRpb246JScKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
Error:
Logical error: 'Unknown virtual column: 'c0.null''.
---

Stack trace:
pthread_kill @ 0x00000000000969fd
raise @ 0x0000000000042476
__lgamma_r_finite @ 0x00000000000287f3
src/Common/Exception.cpp:60:5: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x000000002bc644a1
src/Common/Exception.cpp:93:13: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x000000002bc6660a
src/Common/Exception.cpp:146:19: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002bc66f9e
./src/Common/Exception.h:171:100: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b7733ae
./src/Common/Exception.h:57:54: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b771d0d
./src/Common/Exception.h:189:77: DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000b7af14a
src/Storages/StorageBuffer.cpp:214:15: DB::BufferSource::fillVirtualColumn(String const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000052c715ec
src/Storages/StorageBuffer.cpp:254:38: DB::BufferSource::generate() @ 0x0000000052c70324
src/Processors/ISource.cpp:144:18: DB::ISource::tryGenerate() @ 0x0000000055682d2e
src/Processors/ISource.cpp:110:26: DB::ISource::work() @ 0x00000000556824e4
src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
src/Processors/Executors/ExecutionThreadContext.cpp:102:26: DB::ExecutionThreadContext::executeTask() @ 0x00000000556f1ce3
src/Processors/Executors/PipelineExecutor.cpp:351:26: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x00000000556b7b55
src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*)
src/Processors/Executors/PipelineExecutor.cpp:602:5: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x00000000556b53fe
src/Processors/Executors/PipelineExecutor.cpp:136:9: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000556b496c
src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:77: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:103: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>::type std::__invoke[abi:fe210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
inlined from ./contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:fe210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
inlined from ./contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:fe210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
inlined from ./src/Common/ThreadPool.h:312: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>::type std::__invoke[abi:fe210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:fe210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0 std::__invoke_r[abi:fe210105]<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>()
./contrib/llvm-project/libcxx/include/__functional/function.h:450:24: ? @ 0x000000005570f656
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Common/ThreadPool.cpp:809:12: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000002c2461a3
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: std::__invoke_result_impl<void, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>::type std::__invoke[abi:fe210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:fe210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
./contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:fe210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000002c25af95
start_thread @ 0x0000000000094ac3
__clone3 @ 0x00000000001268d0
```

### PR DESCRIPTION
**Pull request by groeneai**
## Linked issues
- fixes https://github.com/ClickHouse/clickhouse-core-incidents/issues/1917

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed a crash (`LOGICAL_ERROR: Unknown virtual column`) when selecting subcolumns (like `.null` for Nullable, `.size0` for Array, tuple elements, or map keys/values) from a Buffer table engine.

### What changed and why:

When selecting subcolumns from a `Buffer` table, the server crashed with:
```
Logical error: 'Unknown virtual column: 'c0.null''
```

**Root cause:** `BufferSource::generate()` iterates over the output header columns and checks `buffer.data.has(name)` to decide whether to read from the in-memory buffer or fill a virtual column. For subcolumn accesses like `c0.null`, the name is the full qualified subcolumn name (e.g., `"c0.null"`), but the buffer's data block only stores parent columns (e.g., `"c0"`). So `has()` returned false, and the code fell through to `fillVirtualColumn()`, which only handles the `_table` virtual column and threw a `LOGICAL_ERROR`.

**Fix:** Resolve column names through the storage metadata (`ColumnsDescription::tryGetColumnOrSubcolumn`), which properly identifies subcolumns and returns a `NameAndTypePair` with the correct parent column name and subcolumn extraction info. This allows the existing `getColumnFromBlock()` function to find the parent column in the buffer data and extract the subcolumn correctly.

This is the same approach used by `ReadFromMemoryStorageStep`, which correctly handles subcolumns from in-memory data blocks.

**Reproduction (from https://github.com/ClickHouse/ClickHouse/issues/102104):**
```sql
CREATE TABLE t0 (c0 Nullable(Int)) ENGINE = MergeTree() ORDER BY tuple();
CREATE TABLE t1 ENGINE = Buffer(default, t0, 60, 816, 532, 50, 191, 494, 766);
SET optimize_trivial_insert_select = 1, min_insert_block_size_rows = 1025;
INSERT INTO TABLE t1 (c0) SELECT number FROM numbers(1026);
SELECT c0.null FROM t1; -- crashes without fix
```

Closes https://github.com/ClickHouse/ClickHouse/issues/102104

### Version info
- Merged into: `26.5.1.146` (included in `26.5` and later)
- Backported to: `26.4.5.98`

### CODE REVIEW

**Comment by groeneai** [comment]
### Pre-PR Validation Gate (session: cron:clickhouse-ci-task-worker:20260411-174500)

**a) Deterministic repro?** ✅ Yes — `SELECT c0.null FROM <buffer_table>` crashes 100% of the time on current master.

**b) Root cause explained?** ✅ `BufferSource::generate()` checks `buffer.data.has(name)` using the full subcolumn name (`"c0.null"`), but the buffer's in-memory data block only stores parent columns (`"c0"`). `has()` returns false → falls to `fillVirtualColumn()` → only handles `_table` → throws `LOGICAL_ERROR: Unknown virtual column`.

**c) Fix matches root cause?** ✅ The fix resolves column names through `ColumnsDescription::tryGetColumnOrSubcolumn()` to get a proper `NameAndTypePair` with subcolumn delimiter info, allowing `getColumnFromBlock()` to find the parent column and extract the subcolumn. Same pattern as `ReadFromMemoryStorageStep`.

**d) New test added?** ✅ `04097_buffer_subcolumn_virtual_column_crash` — tests `.null`, `.size0`, tuple elements, and map keys/values through Buffer tables.

**e) Both directions demonstrated?** ✅ Without fix: crashes with `LOGICAL_ERROR`. With fix: returns correct results. 50/50 passes with full randomization.

**f) Fix is general?** ✅ Covers ALL subcolumn types via metadata resolution — not hardcoded to specific subcolumn names. Preserves existing behavior for regular columns and virtual columns. Other storages (StorageLog, StorageStripeLog) use different read patterns (file-based serialization) and are not affected.

**Comment by groeneai** [comment]
cc @novikd @azat — could you review this? It fixes a LOGICAL_ERROR crash when selecting subcolumns (`.null`, `.size0`, tuple/map accessors) from a Buffer table — the BufferSource didn't resolve subcolumn names through storage metadata, so it tried to treat them as virtual columns.

**Comment by groeneai** [comment]
Rebased onto current `master` at commit 496f4b27c159 to clear the DIRTY state (which accumulated since 2026-04-21) and to pick up the trunk fix #103489 (merged today, 2026-04-24 11:48 UTC) — this resolves the previous spurious `Unit tests (msan, function_prop_fuzzer)` failure which was a chronic trunk bug, not caused by this PR.

### Conflict resolution

The only merge conflict was in `src/Storages/StorageBuffer.cpp`:

Master refactored the virtuals API (#102304, `move virtuals into in-memory metadata`):
- `storage_snapshot->virtual_columns` was removed; virtuals now live under `metadata->virtuals`.
- `setVirtuals(createVirtuals())` moved before `setInMemoryMetadata(...)`.

My original fix added two members to `BufferSource`:
- `virtual_columns(storage_snapshot->virtual_columns)` — **never used** in `generate()`; removed (it was dead code, and master's API change would have made it fail to compile).
- `metadata(storage_snapshot->metadata)` — used in `generate()` via `columns_desc = metadata->getColumns()` to resolve subcolumn names through `tryGetColumnOrSubcolumn`; kept.

### Verification

- The fix logic (subcolumn-resolving lookup in `generate()`) is unchanged.
- `StorageSnapshot::metadata` and `ColumnsDescription::tryGetColumnOrSubcolumn` both still exist in master — no other API breakage.
- Branch has exactly 2 commits ahead of master: the original fix `88a9b67cf13b` and this merge commit `496f4b27c159`.

cc @novikd @azat — could you take another look? CI will re-run on the rebased HEAD.

File: tests/queries/0_stateless/04097_buffer_subcolumn_virtual_column_crash.sql [hunk 1]
```diff
@@ -0,0 +1,42 @@
+-- Tags: no-parallel
```
[the remark this answers is not in the document]
Comment (groeneai) [reply tests/queries/0_stateless/04097_buffer_subcolumn_virtual_column_crash.sql]: Removed in 0bce791c14bd6e7c284746d0345650e21a84d370 — thanks for the catch.

The test only creates/drops two local tables in the current database (`t_buf_sub`, `t_buf_sub_dst`) and does not touch any shared/global state, so it is safe to run in parallel. The `no-parallel` tag was an unneeded carryover.

**Comment by groeneai** [comment]
@Michicosun — could you please review this PR?

This fixes the chronic BuzzHouse trunk bug **STID 3381-2a5e — `Logical error: Unknown virtual column`** (tracking issue: #102104, ~9 occurrences across master + 7 PRs in 90 days, including PR #100949 which surfaced it as `Unknown virtual column: 'עברית0.size0'`). The bug was introduced in commit aac90df2e0a (`support common virtuals for buffer table`, 2026-04-01) which you authored.

**Root cause:** `BufferSource::generate()` checks `buffer.data.has(name)` for the full subcolumn name (e.g. `arr.size0`, `c0.null`), but the buffer's in-memory data block only stores parent columns, so subcolumns fall through to `fillVirtualColumn()` which only handles `_table` and throws `LOGICAL_ERROR`.

**Fix:** Resolve names through `metadata->getColumns().tryGetColumnOrSubcolumn(...)` to obtain a proper `NameAndTypePair` with subcolumn delimiter info, then let `getColumnFromBlock()` extract the subcolumn via `tryGetSubcolumn()`. Same pattern as `ReadFromMemoryStorageStep`.

**CI is clean** on the rebased HEAD (`0bce791c`):
- `Style check` ✅, `Fast test` ✅, `Code Review` ✅ (AI Review verdict: Approve)
- The two reported failures are unrelated chronic flaky tests tracked separately:
  - `04103_user_network_bandwidth_throttler` — known P2 flaky (5–7 master failures/day across all PRs)
  - `Unit tests (asan_ubsan, function_prop_fuzzer)` — 0 master failures in last 14 days, very rare flake

**Regression test** (`04097_buffer_subcolumn_virtual_column_crash.sql`) covers `.null`, `.size0`, tuple elements, and map keys/values through Buffer tables — the exact subcolumn shapes BuzzHouse keeps rediscovering.

Per @alexey-milovidov's directive on #100949 (2026-04-25): this is the separate fix he asked for. cc @alexey-milovidov @azat @novikd

Session: cron:clickhouse-ci-task-worker:20260427-151500

File: src/Storages/StorageBuffer.cpp [hunk 2]
```diff
@@ -243,11 +244,19 @@ class BufferSource : public ISource
...
 
-            if (buffer.data.has(name))
+            /// Resolve the column through metadata to get proper subcolumn info
+            /// (e.g., "c0.null" for Nullable, "arr.size0" for Array).
+            /// The header's NameAndTypePair lacks subcolumn_delimiter_position,
+            /// so getNameInStorage() would return the full name instead of the parent.
+            auto resolved = columns_desc.tryGetColumnOrSubcolumn(GetColumnsOptions::All, name);
+            if (resolved && buffer.data.has(resolved->getNameInStorage()))
+                columns.emplace_back(getColumnFromBlock(buffer.data, *resolved));
+            else if (buffer.data.has(name))
```
Comment (Michicosun) [inline src/Storages/StorageBuffer.cpp]: @groeneai 

Remove this comment completely.

change logic to the following:
1. Use the metadata isVirtualColumn method to check if the column is virtual
2. If it is virtual, use fillVirtualColumns
3. If it is not virtual, use tryGetColumnFromBlock
4. If the column is not found, throw a logical error

Comment (groeneai) [reply src/Storages/StorageBuffer.cpp]: Done in `2cbf5702041` — refactored to the 4-step shape you specified:

```cpp
if (metadata->isVirtualColumn(name))
{
    columns.emplace_back(fillVirtualColumn(name, type, buffer.data.rows()));
    continue;
}

auto resolved = columns_desc.tryGetColumnOrSubcolumn(GetColumnsOptions::All, name);
auto col = resolved ? tryGetColumnFromBlock(buffer.data, *resolved) : nullptr;

if (!col)
    throw Exception(ErrorCodes::LOGICAL_ERROR,
        "Column or subcolumn '{}' not found in Buffer table", name);

columns.emplace_back(std::move(col));
```

Notes:
- The intermediate `tryGetColumnOrSubcolumn` lookup is needed because the header pair from `getPort().getHeader().getNamesAndTypes()` is built via the default `NameAndTypePair(name, type)` constructor, which leaves `subcolumn_delimiter_position` unset. `tryGetColumnFromBlock` relies on `requested_column.isSubcolumn()` to extract subcolumns, so without resolving against `metadata->getColumns()` first it would treat `c0.null` as a top-level column and fail. Same pattern as `ReadFromMemoryStorageStep::fillPhysicalColumns`.
- `fillVirtualColumn` (singular) — kept the name unchanged, since this helper returns one column per call.
- Explanatory comment removed as requested.

Verified locally on debug build:
- `04097_buffer_subcolumn_virtual_column_crash` — 50/50 PASS with full randomization
- Manual repro from issue #102104 (`SELECT c0.null FROM buffer_table`) returns correct values, no `LOGICAL_ERROR`
- `_table` virtual column still works
- Adjacent Buffer/virtual-column tests (00126, 00158, 00168, 02890, 03094) all pass

PR HEAD: `2cbf5702041` on `fork:fix/buffer-subcolumn-crash`.

**Comment by groeneai** [comment]
Refactor pushed in `2cbf5702041`. cc @Michicosun

Applied @Michicosun's [4-step refactor request](https://github.com/ClickHouse/ClickHouse/pull/102470#discussion_r3148532396):

1. `metadata->isVirtualColumn(name)` check
2. Virtual → `fillVirtualColumn`
3. Otherwise → `tryGetColumnOrSubcolumn` to resolve subcolumn delimiter, then `tryGetColumnFromBlock`
4. Not found → `LOGICAL_ERROR`

The intermediate `tryGetColumnOrSubcolumn` is necessary because the header pair from `getPort().getHeader().getNamesAndTypes()` doesn't carry subcolumn info — same pattern as `ReadFromMemoryStorageStep::fillPhysicalColumns`. Explanatory comment removed.

Verified on debug build: 50/50 PASS for `04097_buffer_subcolumn_virtual_column_crash` with full randomization, plus manual issue #102104 repro and adjacent Buffer/virtual-column tests (00126, 00158, 00168, 02890, 03094) all green.

Inline reply: https://github.com/ClickHouse/ClickHouse/pull/102470#discussion_r3149008382

File: src/Storages/StorageBuffer.cpp [hunk 3]
```diff
@@ -243,14 +244,25 @@ class BufferSource : public ISource
 
         Columns columns;
         columns.reserve(getPort().getHeader().columns());
+        const auto & columns_desc = metadata->getColumns();
```
Comment (Michicosun) [inline src/Storages/StorageBuffer.cpp]:
```suggestion
```

File: src/Storages/StorageBuffer.cpp [hunk 4]
```diff
@@ -243,14 +244,25 @@ class BufferSource : public ISource
...
+            }
+
+            auto resolved = columns_desc.tryGetColumnOrSubcolumn(GetColumnsOptions::All, name);
+            auto col = resolved ? tryGetColumnFromBlock(buffer.data, *resolved) : nullptr;
+
+            if (!col)
+                throw Exception(ErrorCodes::LOGICAL_ERROR,
+                    "Column or subcolumn '{}' not found in Buffer table", name);
+
+            columns.emplace_back(std::move(col));
```
Comment (Michicosun) [inline src/Storages/StorageBuffer.cpp]:
```suggestion
            if (metadata->isVirtualColumn(name))
                columns.push_back(fillVirtualColumn(name, type, buffer.data.rows()));
            else if (auto physical_column = tryGetColumnFromBlock(buffer.data, metadata->columns.getColumnOrSubcolumn(GetColumnsOptions::All, name)))
                columns.push_back(std::move(physical_column))
            else
                throw Exception(ErrorCodes::LOGICAL_ERROR, "Column or subcolumn '{}' not found in Buffer table", name);
```

File: src/Storages/StorageBuffer.cpp [hunk 5]
```diff
@@ -247,10 +248,12 @@ class BufferSource : public ISource
         {
             const auto & [name, type] = packed;
 
-            if (buffer.data.has(name))
-                columns.emplace_back(getColumnFromBlock(buffer.data, packed));
+            if (metadata->isVirtualColumn(name))
+                columns.push_back(fillVirtualColumn(name, type, buffer.data.rows()));
+            else if (auto physical_column = tryGetColumnFromBlock(buffer.data, metadata->columns.getColumnOrSubcolumn(GetColumnsOptions::All, name)))
```
Comment (Michicosun) [inline src/Storages/StorageBuffer.cpp]:
```suggestion
            else if (auto physical_column = tryGetColumnFromBlock(buffer.data, metadata->columns.getColumnOrSubcolumn(GetColumnsOptions::All, name)));
```

File: src/Storages/StorageBuffer.cpp [hunk 6]
```diff
@@ -247,10 +248,12 @@ class BufferSource : public ISource
         {
             const auto & [name, type] = packed;
 
-            if (buffer.data.has(name))
-                columns.emplace_back(getColumnFromBlock(buffer.data, packed));
+            if (metadata->isVirtualColumn(name))
+                columns.push_back(fillVirtualColumn(name, type, buffer.data.rows()));
+            else if (auto physical_column = tryGetColumnFromBlock(buffer.data, metadata->columns.getColumnOrSubcolumn(GetColumnsOptions::All, name)));
+                columns.push_back(std::move(physical_column))
```
Comment (Michicosun) [inline src/Storages/StorageBuffer.cpp]:
```suggestion
            else if (auto physical_column = tryGetColumnFromBlock(buffer.data, metadata->columns.getColumnOrSubcolumn(GetColumnsOptions::All, name)))
                columns.push_back(std::move(physical_column));
```

Comment (groeneai) [reply src/Storages/StorageBuffer.cpp]: Thanks for applying these directly, @Michicosun — saves a round-trip.

I've verified your final state at `6d8e6a530a8` locally on a debug build (clang-21):

- Compiled cleanly (no warnings on `StorageBuffer.cpp`)
- `04097_buffer_subcolumn_virtual_column_crash` — **50/50 PASS** with full `--random-settings` and `--random-merge-tree-settings`
- Manual issue #102104 repro: all subcolumns (`Nullable.null`, `Array.size0`, `Tuple` elements, `Map.keys`/`.values`) and `_table` virtual return correct results — no exception
- Unknown column name (`SELECT nonexistent FROM buffer_table`) — correctly raises `UNKNOWN_IDENTIFIER` (Code 47) at the analyzer, never reaching the `LOGICAL_ERROR` branch (which is now correctly reserved for genuine metadata/data-block desync)
- Adjacent buffer + virtual-column tests `00126_buffer`, `00158_buffer_and_nonexistent_table`, `00168_buffer_defaults`, `02890_describe_table_options`, `03094_virtual_column_table_name` all pass on this HEAD

The `getColumnOrSubcolumn` (asserting variant) is the cleaner choice — it makes the intent explicit and the `LOGICAL_ERROR` branch becomes a true invariant guard rather than an error-message fallback.

Ready for re-review / merge whenever you're happy with it.

**Review by Michicosun — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @groeneai @Michicosun — this PR fixes a `LOGICAL_ERROR` (code 49), which according to the changelog rules should be categorized as `Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR` rather than `Bug Fix`.

I verified this by running the test queries which produce: `Code: 49. DB::Exception ... Unknown virtual column: 'c0.null' ... (LOGICAL_ERROR)`

Could you update the changelog category? Feel free to ignore if there's a specific reason for the current categorization.

**Comment by clickgapai** [comment]
Hi — this PR may need backporting to `26.3` (LTS), `26.2`, `26.1`, `25.8` (LTS), but no backport label was found.

**Affected code:** `BufferSource::generate` in `src/Storages/StorageBuffer.cpp` — core code present in all supported branches.

**Why:** `StorageBuffer.cpp` and `BufferSource` predate all supported branches (file is ancient — `git log --diff-filter=A` shows no recent add). The bug — `LOGICAL_ERROR` when selecting any subcolumn through a `Buffer` table — is reproducible on the running master binary and affects any user reading subcolumns of `Nullable`, `Array`, `Tuple`, `Map`, etc. through a `Buffer`. Each currently supported branch (25.8 lts, 26.1, 26.2, 26.3 lts) contains the buggy code path.

If this should be backported, consider adding `pr-must-backport` or a version-specific label (e.g. `v26.3-must-backport`). Ignore this if backporting is not applicable.
