### PR TITLE
ISSUES-957 fix not work when materialized columns with buff table

### LINKED ISSUE #957: Buffer table does not work with materialized columns
When the underlying table has a materialized column, the database raises an exception when trying to flush the buffer to disk. Here's a simple example that demonstrates the problem:
```
CREATE DATABASE IF NOT EXISTS test;

CREATE TABLE test.nums (
    n UInt64,
    m UInt64 MATERIALIZED n+1
) ENGINE = Log;

CREATE TABLE nums_buf AS test.nums ENGINE = Buffer(test, nums, 1, 10, 100, 1, 3, 10000000, 100000000);

INSERT INTO nums_buf (n) VALUES (1);
INSERT INTO nums_buf (n) VALUES (2);
INSERT INTO nums_buf (n) VALUES (3);
INSERT INTO nums_buf (n) VALUES (4);
INSERT INTO nums_buf (n) VALUES (5);
```

After inserting a few rows successfully, you get this error:
```
Received exception from server:
Code: 44. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Cannot insert column m. 
```

The server log shows this stack trace:
```
2017.07.08 09:58:08.198983 [ 9 ] <Trace> StorageBuffer (nums_buf): Flushing buffer with 4 rows, 64 bytes, age 1 seconds.
2017.07.08 09:58:08.238359 [ 9 ] <Error> void DB::StorageBuffer::flushThread(): Code: 44, e.displayText() = DB::Exception: Cannot insert column m, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x2969826]
1. clickhouse-server(DB::ProhibitColumnsBlockOutputStream::write(DB::Block const&)+0x112) [0x2bedfa2]
2. clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x3f5) [0x2d74145]
3. clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x11) [0x2d742b1]
4. clickhouse-server(DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::shared_ptr<DB::IStorage>)+0xb8c) [0x2a1c63c]
5. clickhouse-server() [0x2a1d4f4]
6. clickhouse-server(DB::StorageBuffer::flushThread()+0x63) [0x2a1d793]
7. clickhouse-server() [0x36744ef]
8. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7ff1c2c656ba]
9. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff1c22863dd]
```

### PR DESCRIPTION
**Pull request by zhang2014**
fix #957 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

### CODE REVIEW

File: dbms/src/Interpreters/Settings.h [hunk 1]
```diff
@@ -300,7 +300,8 @@ struct Settings
     /* Timeout for flushing data from streaming storages. */ \
     M(SettingMilliseconds, stream_flush_interval_ms, DEFAULT_QUERY_LOG_FLUSH_INTERVAL_MILLISECONDS, "Timeout for flushing data from streaming storages.") \
     /* Schema identifier (used by schema-based formats) */ \
-    M(SettingString, format_schema, "", "Schema identifier (used by schema-based formats)")
+    M(SettingString, format_schema, "", "Schema identifier (used by schema-based formats)") \
+    M(SettingBool, insert_allow_materialized_columns, 0, "If setting is enabled, require materialized columns for the INSERT query.")
```
Comment (alexey-milovidov) [inline dbms/src/Interpreters/Settings.h]: *Allow* materialized columns in INSERT, not *require*.

File: dbms/src/DataStreams/ProhibitColumnsBlockOutputStream.cpp [hunk 2]
```diff
@@ -13,9 +13,12 @@ namespace ErrorCodes
 
 void ProhibitColumnsBlockOutputStream::write(const Block & block)
 {
-    for (const auto & column : columns)
-        if (block.has(column.name))
-            throw Exception{"Cannot insert column " + column.name, ErrorCodes::ILLEGAL_COLUMN};
+    if (allow_materialized)
```
Comment (alexey-milovidov) [inline dbms/src/DataStreams/ProhibitColumnsBlockOutputStream.cpp]: With `allow_materialized`, `ProhibitColumnsBlockOutputStream` effectively becomes no-op.
It's better to not use `ProhibitColumnsBlockOutputStream` in INSERT pipeline in this case at all, look at `InterpreterInsertQuery.cpp`:

```
out = std::make_shared<ProhibitColumnsBlockOutputStream>(out, table->materialized_columns);
```

You just have to add a condition above this line.
And `ProhibitColumnsBlockOutputStream` will be unmodified.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: dbms/src/DataStreams/ProhibitColumnsBlockOutputStream.cpp (hunk 2 above)
Comment (alexey-milovidov) [reply dbms/src/DataStreams/ProhibitColumnsBlockOutputStream.cpp]: And you have to do the same at `InterpreterCreateQuery.h` for the case of `CREATE ... SELECT`.

File: dbms/src/Interpreters/InterpreterCreateQuery.cpp [hunk 3]
```diff
@@ -560,17 +560,20 @@ BlockIO InterpreterCreateQuery::createTable(ASTCreateQuery & create)
...
+            create.database, create.table, res, create.is_temporary ? context.getSessionContext() : context, query_ptr);
+
+        out = std::make_shared<MaterializingBlockOutputStream>(out);
+
+        /// @note shouldn't these two contexts be session contexts in case of temporary table?
+        bool strict_insert_defaults = static_cast<bool>(context.getSettingsRef().strict_insert_defaults);
+        out = std::make_shared<AddingDefaultBlockOutputStream>(
+            out, columns.columns, columns.column_defaults, context, strict_insert_defaults);
+
+        if (context.getSettingsRef().insert_allow_materialized_columns)
```
Comment (alexey-milovidov) [inline dbms/src/Interpreters/InterpreterCreateQuery.cpp]: This condition should be negative?

Comment (alexey-milovidov) [reply dbms/src/Interpreters/InterpreterCreateQuery.cpp]: "If insertion of materialized columns is not permitted then add a check into pipeline."
