### PR TITLE
Use function isNotDistinctFrom only in join key

### LINKED ISSUE #62358: [Regression][24.3] : Function isNotDistinctFrom can be used only in the JOIN ON section
**Describe what's wrong**

Following query stopped to work in 24.3 version: https://fiddle.clickhouse.com/8c3a5ec2-a07e-49a8-b452-8eb6a784fcac

with following error : `Function isNotDistinctFrom can be used only in the JOIN ON section. `

**Does it reproduce on the most recent release?**

 Yep

**How to reproduce**

Use link to fiddle above

**Expected behavior**

No error or at least error that tells what's wrong with query if it is not correct

**Error message and/or stacktrace**

`Function isNotDistinctFrom can be used only in the JOIN ON section. `

**Additional context**

Nope

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

close https://github.com/ClickHouse/ClickHouse/issues/62358

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

File: src/Analyzer/Utils.cpp [hunk 1]
```diff
@@ -760,4 +760,52 @@ QueryTreeNodePtr createCastFunction(QueryTreeNodePtr node, DataTypePtr result_ty
     return function_node;
 }
 
+/** Returns:
+  * {_, false} - multiple sources
```
Comment (serxa) [inline src/Analyzer/Utils.cpp:764]: The comment is not entirely correct. `_` is always `nullptr` and looks like it also happens if `getColumnSourceOrNull` returns `nullptr` (not multiple sources). Although it was just moved...

**Review by serxa — APPROVED** [review]
