### PR TITLE
Separate consumer/producer settings for Kafka

### LINKED ISSUE #58983: Unexpected Warning Logs from Kafka Engine Table in ClickHouse
While ingesting data into a Kafka engine table in ClickHouse with the following configuration:

```sql
ENGINE = Kafka
SETTINGS kafka_broker_list = '<KAFKA_BROKER>', kafka_topic_list = '<TOPIC_NAME>', kafka_group_name = 'group1', kafka_format = 'JSONEachRow', kafka_max_block_size = 1048576
```

I am encountering a series of warning logs for each insert operation. The logs are as follows:

```log
2024.01.19 10:44:16.319716 [ 15642 ] {77ffc983-74f9-4681-b442-b51f0c6bc933} <Warning> StorageKafka (<TABLE_NAME>): [rdk:CONFWARN] [thrd:app]: Configuration property session.timeout.ms is a consumer property and will be ignored by this producer instance
2024.01.19 10:44:16.319823 [ 15642 ] {77ffc983-74f9-4681-b442-b51f0c6bc933} <Warning> StorageKafka (<TABLE_NAME>): [rdk:CONFWARN] [thrd:app]: Configuration property heartbeat.interval.ms is a consumer property and will be ignored by this producer instance
2024.01.19 10:44:16.319879 [ 15642 ] {77ffc983-74f9-4681-b442-b51f0c6bc933} <Warning> StorageKafka (<TABLE_NAME>): [rdk:CONFWARN] [thrd:app]: Configuration property max.poll.interval.ms is a consumer property and will be ignored by this producer instance
```

These warnings are puzzling as I have not set these properties in my configuration. Could you please help me understand why these logs are appearing and how I can prevent them from showing up?

### PR DESCRIPTION
**Pull request by AVMusorin**
Closes: #58983

**Why does this happen?**

`librdkafka` prints this kind of warning if consumer properties are used for producer instances or producer properties for consumers. https://github.com/ClickHouse/librdkafka/blob/master/src/rdkafka_conf.c#L3940

**New configuration example:**

```xml
<kafka>
        <heartbeat_interval_ms>301</heartbeat_interval_ms>
        <statistics_interval_ms>600</statistics_interval_ms>
       
       <kafka_topic>
            <name>football</name>
            <request_timeout_ms>6000</request_timeout_ms>
        </kafka_topic>
       
        <producer>
          <compression_codec>gzip</compression_codec>
        </producer>

       <consumer>
          <enable_auto_commit>true</enable_auto_commit>
        </consumer>
</kafka>
```

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Introduce separate consumer/producer tags for the Kafka configuration. This avoids warnings from librdkafka that consumer properties were specified for producer instances and vice versa (e.g. `Configuration property session.timeout.ms is a consumer property and will be ignored by this producer instance`). Closes: #58983

### CODE REVIEW

File: src/Storages/Kafka/StorageKafka.cpp [hunk 1]
```diff
@@ -870,6 +888,21 @@ void StorageKafka::updateConfiguration(cppkafka::Configuration & kafka_config)
...
 
+void StorageKafka::updateConsumerConfiguration(cppkafka::Configuration & kafka_config)
+{
+    const auto & config = getContext()->getConfigRef();
+    auto config_prefix = getConfigPrefix();
+    if (config.has(config_prefix))
+        loadConsumerConfig(kafka_config, config, config_prefix, topics);
+}
+
+void StorageKafka::updateProducerConfiguration(cppkafka::Configuration & kafka_config) {
```
Comment (azat) [inline src/Storages/Kafka/StorageKafka.cpp:899]: Coding style issue

```suggestion
void StorageKafka::updateProducerConfiguration(cppkafka::Configuration & kafka_config)
{
```

File: src/Storages/Kafka/StorageKafka.cpp [hunk 2]
```diff
@@ -268,69 +268,103 @@ namespace
...
-                    /// See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
-                    const String setting_path = kafka_topic_path + "." + inner_tag;
-                    const String setting_value = config.getString(setting_path);
+                    const String topic_name = config.getString(kafpa_topic_name_path);
 
-                    const String setting_name_in_kafka_config = (inner_tag == "log_level") ? inner_tag : boost::replace_all_copy(inner_tag, "_", ".");
-                    kafka_config.set(setting_name_in_kafka_config, setting_value);
+                    if (topic_name != topic)
+                        continue;
+                    loadTopicConfig(kafka_config, config, kafka_topic_path);
```
Comment (azat) [inline src/Storages/Kafka/StorageKafka.cpp:340]: I was thinking that separate consumer/producer settings should support per-topic syntax as well, and both of them, this one and simpler.

Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp:340]: Do you mean `<kafka_TOPIC_NAME>`? I thought that it is a part of the legacy... (regarding code comments)

Maybe it is better to reject `<kafka_TOPIC_NAME>` at all? Simpler code / less config variations.

Comment (azat) [reply src/Storages/Kafka/StorageKafka.cpp:340]: >Do you mean <kafka_TOPIC_NAME>? I thought that it is a part of the legacy... (regarding code comments)

Yes, it is deprecated syntax, but maybe it still make sense to support it, since it is not a lot of code, but easier syntax (usually you don't have special symbols in the topic names and you are allowed to use easier syntax instead of more "advanced " one).

But I don't have strong opinion here, I'm OK to leave it as-is.

File: src/Storages/Kafka/StorageKafka.cpp (hunk 1 above)
Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp]: Fixed.

File: src/Storages/Kafka/StorageKafka.cpp (hunk 2 above)
Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp:340]: Moved the legacy topic parsing to a separate function (will be easier to deprecate in the future) and allowed to use it (old schema) inside `<consumer>/<producer>` tags.

File: src/Storages/Kafka/StorageKafka.cpp [hunk 3]
```diff
@@ -870,6 +899,26 @@ void StorageKafka::updateConfiguration(cppkafka::Configuration & kafka_config)
...
 }
 
+void StorageKafka::updateConsumerConfiguration(cppkafka::Configuration & kafka_config)
+{
+    const auto & config = getContext()->getConfigRef();
+    auto config_prefix = getConfigPrefix();
+    if (config.has(config_prefix))
+        loadConsumerConfig(kafka_config, config, config_prefix, topics);
+
+    loadTopicLegacyConfig(kafka_config, config, config_prefix, topics);
```
Comment (azat) [inline src/Storages/Kafka/StorageKafka.cpp:909]: Should this be inside `loadConsumerConfig`? Since without it will not have `consumer` in the config prefix and will load nothing I guess (same for producer)

Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp:913]: Yes, makes sense.

**Comment by AVMusorin** [comment]
Could please someone else take a look at this PR?

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 0cd0aaa6779a54dbc84ba0fea3209d3e8205b051 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58956/0cd0aaa6779a54dbc84ba0fea3209d3e8205b051/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58956/0cd0aaa6779a54dbc84ba0fea3209d3e8205b051/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by AVMusorin** [comment]
@rschu1ze Could you please take a look at this PR? Since I partially rewrote your code.

**Comment by rschu1ze** [comment]
> @rschu1ze Could you please take a look at this PR? Since I partially rewrote your code.

Ah, that would be #58956, right? Yes, I can check in a bit.

**Comment by rschu1ze** [comment]
If you don't mind, could you please explain the actual root cause of #58983? It is neither clear to me from the issue nor from the PR message.

**Comment by AVMusorin** [comment]
> @AVMusorin If you don't mind, could you please explain the actual root cause of #58983? It is neither clear to me from the issue nor from the PR message.

Yes. I've also updated the description.

In short, `librdkafka` prints this kind of warning if consumer properties are used for producer instances or producer properties for consumers. https://github.com/ClickHouse/librdkafka/blob/master/src/rdkafka_conf.c#L3940

The main idea of this PR - is to allow to specify settings for a consumer and a producer in separate config sections (but under `kafka` tag). It is clearer what settings will be applied for a consumer and what for a producer, also, it prevents printing annoying messages in the log...

File: tests/integration/test_storage_kafka/configs/kafka.xml [hunk 4]
```diff
@@ -11,16 +10,39 @@
...
-				<statistics_interval_ms>600</statistics_interval_ms>
+        <!-- default 3000 (every three second) seems too long for test -->
+        <statistics_interval_ms>600</statistics_interval_ms>
 
         <kafka_topic>
             <name>consumer_hang</name>
             <!-- default: 3000 -->
             <heartbeat_interval_ms>300</heartbeat_interval_ms>
+        </kafka_topic>
+        <consumer>
```
Comment (rschu1ze) [inline tests/integration/test_storage_kafka/configs/kafka.xml:21]: Cosmetic: Let's use 4 spaces indentation instead of 2.

File: tests/integration/test_storage_kafka/configs/kafka.xml [hunk 5]
```diff
@@ -11,16 +10,39 @@
...
+          <auto_offset_reset>earliest</auto_offset_reset>
+            <kafka_topic>
+            <!-- Setting for topic will be applied only for consumer -->
+            <name>consumer_hang</name>
```
Comment (rschu1ze) [inline tests/integration/test_storage_kafka/configs/kafka.xml:25]: Please intend this, it's visually hard to keep things apart.

File: tests/integration/test_storage_kafka/configs/kafka.xml [hunk 6]
```diff
@@ -11,16 +10,39 @@
...
+        <statistics_interval_ms>600</statistics_interval_ms>
 
         <kafka_topic>
             <name>consumer_hang</name>
             <!-- default: 3000 -->
             <heartbeat_interval_ms>300</heartbeat_interval_ms>
+        </kafka_topic>
+        <consumer>
+          <auto_offset_reset>earliest</auto_offset_reset>
+            <kafka_topic>
```
Comment (rschu1ze) [inline tests/integration/test_storage_kafka/configs/kafka.xml:23]: Please don't intend this.

File: tests/integration/test_storage_kafka/configs/kafka.xml [hunk 7]
```diff
@@ -11,16 +10,39 @@
...
-        </kafka_topic>
+          </kafka_topic>
+          <kafka_topic>
+            <name>separate_settings</name>
+            <!-- default: 10000 -->
+            <session_timeout_ms>6001</session_timeout_ms>
+          </kafka_topic>
+        </consumer>
+        <producer>
+          <!-- NOTE: consumer_hang - name of the topic -->
```
Comment (rschu1ze) [inline tests/integration/test_storage_kafka/configs/kafka.xml:36]: L. 36 talks about topic `consumer_hang` but I don't see where the XML on l. 36 - 45 does anything specifically for `consumer_hang`.

File: tests/integration/test_storage_kafka/configs/kafka.xml [hunk 8]
```diff
@@ -11,16 +10,39 @@
...
+          <kafka_separate_settings>
```
Comment (rschu1ze) [inline tests/integration/test_storage_kafka/configs/kafka.xml:37]: What is `kafka_separate_settings`? It does not look like a kafka topic (otherwise it would be wrapped in `<kafka_topic><name>`). Why do we need it? Why can't the producer settings simply be listed under `<producer>`?

File: src/Storages/Kafka/StorageKafka.cpp [hunk 9]
```diff
@@ -846,6 +879,24 @@ void StorageKafka::updateConfiguration(cppkafka::Configuration & kafka_config)
...
+}
+
+void StorageKafka::updateProducerConfiguration(cppkafka::Configuration & kafka_config)
+{
+    const auto & config = getContext()->getConfigRef();
+    auto config_prefix = getConfigPrefix();
+    if (config.has(config_prefix))
+        loadProducerConfig(kafka_config, config, config_prefix, topics);
```
Comment (rschu1ze) [inline src/Storages/Kafka/StorageKafka.cpp:897]: Silly question but why don't we `loadTopicLegacyConfig()` as in l. 889?

File: src/Storages/Kafka/StorageKafka.cpp [hunk 10]
```diff
@@ -244,69 +244,130 @@ namespace
...
+    }
+
+    void loadProducerConfig(cppkafka::Configuration & kafka_config, const Poco::Util::AbstractConfiguration & config, const String & prefix, const Names & topics)
+    {
+        const String producer_path = prefix + "." + CONFIG_KAFKA_PRODUCER_TAG;
+        if (!config.has(producer_path))
+            return;
+        loadFromConfig(kafka_config, config, producer_path, topics);
+        /// Load legacy configuration per topic from the same producer level
+        loadTopicLegacyConfig(kafka_config, config, producer_path, topics);
```
Comment (rschu1ze) [inline src/Storages/Kafka/StorageKafka.cpp:369]: I actually thought that we should remove the legacy syntax (basically `loadTopicLegacyConfig()`), now that it has been deprecated for a year (#46752). Perhaps that would simplify the code.

File: src/Storages/Kafka/StorageKafka.cpp [hunk 11]
```diff
@@ -653,6 +710,19 @@ cppkafka::Configuration StorageKafka::getConsumerConfiguration(size_t consumer_n
     return conf;
 }
 
+cppkafka::Configuration StorageKafka::getProducerConfiguration()
+{
+    cppkafka::Configuration conf;
+    conf.set("metadata.broker.list", brokers);
+    conf.set("client.id", client_id);
+    conf.set("client.software.name", VERSION_NAME);
+    conf.set("client.software.version", VERSION_DESCRIBE);
```
Comment (rschu1ze) [inline src/Storages/Kafka/StorageKafka.cpp:719]: Cosmetic: + newline before l. 720, also in l. 702.

File: src/Storages/Kafka/StorageKafka.cpp [hunk 12]
```diff
@@ -244,69 +244,130 @@ namespace
...
+    {
+        // Update consumer topic-specific configuration (legacy syntax, retained for compatibility). Example with topic "football":
+        //     <kafka_football>
+        //         <retry_backoff_ms>250</retry_backoff_ms>
+        //         <fetch_min_bytes>100000</fetch_min_bytes>
+        //     </kafka_football>
+        // The legacy syntax has the problem that periods in topic names (e.g. "sports.football") are not supported because the Poco
+        // configuration framework hierarchy is based on periods as level separators. Besides that, per-topic tags at the same level
+        // as <kafka> are ugly.
+        String topic_path = prefix;
```
Comment (rschu1ze) [inline src/Storages/Kafka/StorageKafka.cpp:341]: The stuff on l. 341-343 is new and I don't get why it is needed.

**Review by rschu1ze — COMMENTED** [review]
I tried to verify the correctness of this PR by looking at the code but too many things were thrown from one place to another, renamed and slightly changed in meaning, so it is hard to be sure. I could install Kafka and verify by debugging but I remember the horrors of getting Kafka set up one year ago for my other PR.

Please have a look at my comments. I am happily to merge this PR if you think that everything is really okay.

From my view, we can drop the legacy syntax for Kafka topics (I wrote it in a comment). I would be happy if you like to do this in this PR (or in another one), I guess this would also simplify the code.

**Comment by rschu1ze** [comment]
@antaljanosbenjamin Just FYI since you were working on Kafka recently

**Comment by rschu1ze** [comment]
Kindly take a look at the remaining comments, then I can happily merge. Thanks!

**Comment by AVMusorin** [comment]
> Kindly take a look at the remaining comments, then I can happily merge. Thanks!

Yes, sure. I'm in the process and let you know when it's done. Thanks!

**Comment by alexey-milovidov** [comment]
@AVMusorin, How is the progress?

File: programs/server/config.xml [hunk 13]
```diff
@@ -1553,6 +1553,43 @@
         </tables>
     </rocksdb>
     -->
+    <!-- <kafka> -->
+        <!-- Global configuration properties -->
+        <!--
+        <heartbeat_interval_ms>301</heartbeat_interval_ms>
+        <statistics_interval_ms>600</statistics_interval_ms>
+        -->
+        <!-- End Global configuration -->
```
[the remark this answers is not in the document]
Comment (AVMusorin) [reply programs/server/config.xml]: Fixed.

File: programs/server/config.xml [hunk 14]
```diff
@@ -1553,6 +1553,43 @@
         </tables>
     </rocksdb>
     -->
+    <!-- <kafka> -->
```
[the remark this answers is not in the document]
Comment (AVMusorin) [reply programs/server/config.xml:1582]: Yep. Done.

File: tests/integration/test_storage_kafka/configs/kafka.xml (hunk 5 above)
Comment (AVMusorin) [reply tests/integration/test_storage_kafka/configs/kafka.xml]: Sorry for this. Fixed.

File: tests/integration/test_storage_kafka/configs/kafka.xml (hunk 7 above)
Comment (AVMusorin) [reply tests/integration/test_storage_kafka/configs/kafka.xml]: Fixed

File: src/Storages/Kafka/StorageKafka.cpp (hunk 9 above)
Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp]: I agreed to remove this legacy syntax at all and throw a warning if it is used.

File: src/Storages/Kafka/StorageKafka.cpp (hunk 11 above)
Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp:767]: Done.

File: src/Storages/Kafka/StorageKafka.cpp (hunk 12 above)
Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp]: Also, removed.

File: src/Storages/Kafka/StorageKafka.cpp (hunk 10 above)
Comment (AVMusorin) [reply src/Storages/Kafka/StorageKafka.cpp]: Yes, agree! I removed it and added a warning if someone still uses it.

File: tests/integration/test_storage_kafka/configs/kafka.xml (hunk 8 above)
Comment (AVMusorin) [reply tests/integration/test_storage_kafka/configs/kafka.xml]: `<kafka_separate_settings>` this is the old syntax I left it here to check that the warning works fine.

**Comment by AVMusorin** [comment]
A short recap of what've done since the last changes:
* fixes review comments
* remove legacy syntax to apply kafka settings per topic (this helped to simplify code). The warning will be generated highlight that someone till uses the deprecated syntax.
* added trace logs with what exactly settings were read and applied for consumer and producer. Helps to debug especially since the last changes kafka settings can be read not only from CH config files but also from named collections.

File: programs/server/config.xml [hunk 15]
```diff
@@ -1553,6 +1553,43 @@
...
+        <statistics_interval_ms>600</statistics_interval_ms>
+        -->
+        <!-- End Global configuration -->
+
+        <!-- Topic configuration properties -->
+        <!--
+        <kafka_topic>
+            <name>football</name>
+            <request_timeout_ms>6000</request_timeout_ms>
+        </kafka_topic>
```
[the remark this answers is not in the document]
Comment (AVMusorin) [reply programs/server/config.xml:1596]: They should work for now since I haven't removed the processing of the old syntax.

File: docs/en/engines/table-engines/integrations/kafka.md [hunk 16]
```diff
@@ -170,53 +170,37 @@ Similar to GraphiteMergeTree, the Kafka engine supports extended configuration u
...
-    </kafka_topic>
-
-    <kafka_topic>
-      <name>stats</name>
-      <retry_backoff_ms>400</retry_backoff_ms>
-      <fetch_min_bytes>50000</fetch_min_bytes>
-    </kafka_topic>
+    <statistics_interval_ms>3000</statistics_interval_ms>
+
+    <!-- Settings for consumer -->
```
Comment (rschu1ze) [inline docs/en/engines/table-engines/integrations/kafka.md:175]: Stupid question but is it no longer possible to have `<kafka_topic>` defined directly under `<kafka>`? Asking because the PR description says that is possible.

**Review by rschu1ze — APPROVED** [review]
Thanks.

The codebase is still in a stabilization phase, I'll hopefully be able to merge this next week.

File: docs/en/engines/table-engines/integrations/kafka.md (hunk 16 above)
Comment (AVMusorin) [reply docs/en/engines/table-engines/integrations/kafka.md:175]: Yes, it is possible to define `<kafka_topic>` directly under `<kafka>`. I'll add this case in the documentation.
