### PR TITLE
Fix SimpleSquashingChunksTransform

### LINKED ISSUE #62173: 00088_global_in_one_shard_and_rows_before_limit is flaky
Last 24 hours:

failures | last | Test Name | PRs | last_report_link | Check Names
-- | -- | -- | -- | -- | --
15 | 2024-04-02 14:14:12 | 00088_global_in_one_shard_and_rows_before_limit | [0,60023,60920,61116,61995] | https://s3.amazonaws.com/clickhouse-test-reports/0/d729b63293b393437e3c39d964fa0418001b2f2d/stateful_tests__msan__parallelreplicas_.html | ["Stateful tests (aarch64)","Stateful tests (asan)","Stateful tests (debug)","Stateful tests (debug, ParallelReplicas)","Stateful tests (msan)","Stateful tests (msan, ParallelReplicas)","Stateful tests (release)","Stateful tests (tsan)","Stateful tests (ubsan)","Stateful tests (ubsan, ParallelReplicas)"]

Seems like it started quite recently (maybe analyzer?)

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed rare bug in `SimpleSquashingChunksTransform` that may lead to a loss of the last chunk of data in a stream.

---

Analyzer became a victim, because it puts `SimpleSquashingChunksTransform` before `MemorySink` when collecting data into a temp table.

Fixes: #62173 #62192

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit d37c2f71db9124fd01c0a4120f536e9c67ff6f41 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62451/d37c2f71db9124fd01c0a4120f536e9c67ff6f41/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Processors/Transforms/SquashingChunksTransform.cpp [hunk 1]
```diff
@@ -64,8 +69,22 @@ void SimpleSquashingChunksTransform::transform(Chunk & chunk)
     }
     else
     {
+        if (chunk.hasRows())
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Chunk expected to be empty, otherwise it will be lost");
```
Comment (devcrafter) [inline src/Processors/Transforms/SquashingChunksTransform.cpp:73]: Don't know if it's important, but new code doesn't fit comment to `SimpleSquashingChunksTransform` - https://github.com/ClickHouse/ClickHouse/blob/ad385238da24682e02e9867b28a38fb060eba834/src/Processors/Transforms/SquashingChunksTransform.h#L31

Comment (nickitat) [reply src/Processors/Transforms/SquashingChunksTransform.cpp:73]: this comment describes different situation (that is not a bug if we consider it in isolation from squashing transform). when the transform reading output from squashing stops accepting chunks while there are some more to be returned from squashing.

**Comment by nickitat** [comment]
`AST fuzzer (ubsan)` -  #62486
`Stateless tests (debug) [2/5]` - #62487
`Stateful tests (msan)` - #62252

File: src/Processors/Transforms/SquashingChunksTransform.cpp [hunk 2]
```diff
@@ -64,8 +69,22 @@ void SimpleSquashingChunksTransform::transform(Chunk & chunk)
...
+
         auto block = squashing.add({});
         chunk.setColumns(block.getColumns(), block.rows());
+
+        /// ISimpleTransform keeps output chunk (result of transform() execution) for some time and push it in the output port within subsequent prepare() call.
+        /// Because of our custom prepare() implementation we have to take care of both places where data could be buffered: `output_data` and `squashing`.
+        if (output_data.chunk.hasRows())
+        {
+            auto res = std::move(output_data.chunk);
+            output_data.chunk.clear();
```
Comment (devcrafter) [inline src/Processors/Transforms/SquashingChunksTransform.cpp:83]: Isn't access to moved object undefined behavior?

File: src/Processors/Transforms/SquashingChunksTransform.cpp [hunk 3]
```diff
@@ -64,8 +69,22 @@ void SimpleSquashingChunksTransform::transform(Chunk & chunk)
...
     {
+        if (chunk.hasRows())
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Chunk expected to be empty, otherwise it will be lost");
+
         auto block = squashing.add({});
         chunk.setColumns(block.getColumns(), block.rows());
+
+        /// ISimpleTransform keeps output chunk (result of transform() execution) for some time and push it in the output port within subsequent prepare() call.
+        /// Because of our custom prepare() implementation we have to take care of both places where data could be buffered: `output_data` and `squashing`.
+        if (output_data.chunk.hasRows())
```
Comment (devcrafter) [inline src/Processors/Transforms/SquashingChunksTransform.cpp:80]: I find this rather hacky. IMO, the proper fix would be to modify `prepair()` i.e. check there as well if we can push to the output port, i.e. we can simply write left data to `chunk` as usual.

File: src/Processors/Transforms/SquashingChunksTransform.cpp (hunk 2 above)
Comment (antaljanosbenjamin) [reply src/Processors/Transforms/SquashingChunksTransform.cpp:83]: I checked this PR because of `SimpleSquashingChunksTransform`, but I found this comment and I couldn't stand not to answer (because this is my all time favourite answer in terms of C++): the "moved-from-objects" are in **a valid, but unspecified state**. That means reading from them might be tricky, but calling any function on them that doesn't have any preconditions is fine. In other worlds you can use the objects as you want, you just have to "forget" everything you know about them. An [SO answer](https://stackoverflow.com/a/7028318/6639989) explaining this with a bit more context

**Review by devcrafter — APPROVED** [review]
