### PR TITLE
Fix `parseDateTimeBestEffort` incorrectly parsing words starting with month/weekday prefixes

### LINKED ISSUE #97965: Variant value incorrectly stored as datetime
### Company or project name

_No response_

### Describe what's wrong

In Clickhouse Cloud v25.10, when inserting into a table with a Variant column that allows both String and DateTime, some strings appear to be unexpectedly being interpreted as date times

The problem does not appear to be reproducible in https://fiddle.clickhouse.com

### Does it reproduce on the most recent release?

No

### How to reproduce

```
CREATE OR REPLACE TABLE example
( 
    key String,
    value Variant(String, DateTime)
) 
ENGINE = ReplacingMergeTree() 
ORDER BY (key);

INSERT INTO example (key, value) VALUES ('key1', 'Married');

SELECT key, value FROM example FINAL
```

This returns
```
key1	2025-03-01 00:00:00
```

However, it appears the behaviour is non-deterministic as sometimes it does return the correct expected value

```
key1	Married
```

Screenshot:
Image

### Expected behavior

It should return

```
key1	Married
```

### Error message and/or stacktrace

N/A

### Additional context

I was able to replicate this on multiple Clickhouse Cloud services

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `parseDateTimeBestEffort` incorrectly parsing words starting with month/weekday prefixes. Closes https://github.com/ClickHouse/ClickHouse/issues/97965

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.3.1.531`

### CODE REVIEW

File: src/IO/parseDateTimeBestEffort.cpp [hunk 1]
```diff
@@ -675,8 +676,51 @@ ReturnType parseDateTimeBestEffortImpl(
...
+                    /// Read remaining alphabetical characters of the word.
+                    /// For example, "March" after reading "Mar", or "Monday" after reading "Mon".
+                    char rest[7]; /// Longest valid suffix: "tember" or "nesday" (6 chars)
+                    size_t num_rest = readAlpha(rest, sizeof(rest), in);
+
+                    /// If there are still more alphabetical characters, the word is longer than any known name.
+                    if (!in.eof() && isAlphaASCII(*in.position()))
+                    {
+                        while (!in.eof() && isAlphaASCII(*in.position()))
+                            ++in.position();
```
Comment (nihalzp) [inline src/IO/parseDateTimeBestEffort.cpp]:
```suggestion
```
I am not sure we need these two lines because we return immediately after it.

**Review by nihalzp — APPROVED** [review]

File: src/IO/parseDateTimeBestEffort.cpp (hunk 1 above)
Comment (Avogar) [reply src/IO/parseDateTimeBestEffort.cpp]: Good point
