### PR TITLE
Aliases for StorageMerge fix

### LINKED ISSUE #6051: Merge engine do not supports alias columns in source tables
Table with Merge engine can not work with alias column in data table.

```
create table issue6051_Table
(
    dt       Date,
    col      UInt32,
    colAlias UInt32 alias col
)
engine = MergeTree() partition by toYYYYMM(dt) order by (dt);

create table issue6051_Merge
(
    dt       Date,
    colAlias UInt32
)
engine = Merge(currentDatabase(), '^issue6051_');

insert into issue6051_Table (dt, col) values ('2019-01-01', 1);

select dt, colAlias from issue6051_Table;
┌─────────dt─┬─colAlias─┐
│ 2019-01-01 │        1 │
└────────────┴──────────┘

select dt, colAlias from issue6051_Merge;

Received exception from server (version 19.4.0):
Code: 16. DB::Exception: Received from localhost:9000, ::1. DB::Exception: 
There is no column with name colAlias in table. There are columns: dt, col.
```

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow StorageMerge to access tables with aliases. Closes https://github.com/ClickHouse/ClickHouse/issues/6051.

### CODE REVIEW

File: src/Storages/StorageMerge.cpp [hunk 1]
```diff
@@ -246,12 +249,63 @@ Pipe StorageMerge::read(
...
             throw Exception("Illegal SAMPLE: table doesn't support sampling", ErrorCodes::SAMPLING_NOT_SUPPORTED);
 
+        Aliases aliases;
         auto storage_metadata_snapshot = storage->getInMemoryMetadataPtr();
+        auto storage_columns = storage_metadata_snapshot->getColumns();
+
+        if (processed_stage == QueryProcessingStage::FetchColumns && !storage_columns.getAliases().empty())
+        {
+            NameSet required_columns_set;
+            std::function<void(ASTPtr)> extract_columns_from_alias_expression = [&](ASTPtr expr)
```
Comment (CurtizJ) [inline src/Storages/StorageMerge.cpp:259]: Maybe we can reuse `ColumnAliasesVisitor`?

Comment (kssenii) [reply src/Storages/StorageMerge.cpp]: Done.

**Review by CurtizJ — APPROVED** [review]
