### PR TITLE
ISSUES-5432 fix bad alloc when truncate join storage

### LINKED ISSUE #5432: std::bad_alloc when TRUNCATE table with Engine=JOIN
```sql
CREATE TABLE join_test (number UInt8, value Float32) Engine = Join(ANY, LEFT, number);
TRUNCATE TABLE join_test;
```
Result:
```
Received exception from server (version 19.6.2):
Code: 1001. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: std::bad_alloc. Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x767c3f6]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x39294a2]
2. /usr/bin/clickhouse-server() [0x35993f1]
3. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x39372ab]
4. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x77879bf]
5. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x77880f9]
6. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x783b231]
7. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x78373f8]
8. /usr/bin/clickhouse-server() [0xb5488bf]
9. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7ff9019396db]
10. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7ff900eb888f]

```

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Fixes #5432

For changelog. Remove if this is non-significant change.

Category (leave one):
- Bug Fix

Short description (up to few sentences):

 fix bad alloc when truncate join storage

### CODE REVIEW

File: dbms/src/Storages/StorageJoin.h [hunk 1]
```diff
@@ -43,7 +43,7 @@ class StorageJoin : public ext::shared_ptr_helper<StorageJoin>, public StorageSe
 
 private:
     Block sample_block;
-    const Names & key_names;
+    const Names key_names;
```
Comment (alexey-milovidov) [inline dbms/src/Storages/StorageJoin.h]: Do we have similar issue in another storages? We should check everywhere.

Comment (alexey-milovidov) [reply dbms/src/Storages/StorageJoin.h]: Ok, this is the only such case in Storages.
