### PR TITLE
Use double quote identifier in odbc as default in case of error

### LINKED ISSUE #6412: Hive odbc driver
After udpdated to CH 19.11.4.24 from 18.x version 

CH raise exception when I use query through odbc
```
 Code: 86, e.displayText() = DB::Exception: Received error from remote server /identifier_quote?connection_string=DSN%3DHWX_SSL. HTTP status code: 500 Internal Server Error, body: Error getting identifier quote style from ODBC 'Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Connection attempt failed: Connection:Not applicable
Server:HWX_SSL
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = HY000
Native Error Code = 11560
[Cloudera][ODBC] (11560) Unable to locate SQLGetPrivateProfileString function.
```

It telegram channel Denny Crane said that is because CH request call for discover quotes `"` or ```

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Return double quote identifier if unable to get from driver. Closes https://github.com/ClickHouse/ClickHouse/issues/6412.

### CODE REVIEW

File: programs/odbc-bridge/getIdentifierQuote.cpp [hunk 1]
```diff
@@ -19,7 +19,18 @@ namespace ErrorCodes
...
 {
-    return connection.get_info<std::string>(SQL_IDENTIFIER_QUOTE_CHAR);
+    std::string quote;
+    try
+    {
+        quote = connection.get_info<std::string>(SQL_IDENTIFIER_QUOTE_CHAR);
+    }
+    catch (...)
+    {
+        LOG_WARNING(&Poco::Logger::get("ODBCGetIdentifierQuote"), "Cannot fetch identifier quote. Default double quote is used");
```
Comment (alexey-milovidov) [inline programs/odbc-bridge/getIdentifierQuote.cpp:29]: Let's also log current exception message (getCurrentExceptionMessage).

**Review by alexey-milovidov — APPROVED** [review]
