### PR TITLE
Try fix intersecting parts

### LINKED ISSUE #23296: Part X intersects next part Y. It is a bug.
**Describe the bug**
At some point of time next error appears at log. (After that this error spams the log endlessly..)

`
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 2021.04.17 17:45:30.287957 [ 780 ] {} <Error> db.table(d577b766-e1b9-4a33-be19-6ac5f968ad41): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Part d23fba2922c1a8f3adafceb40a86c34c_45540_46193_7_46162 intersects next part d23fba2922c1a8f3adafceb40a86c34c_46190_46194_1 (state Committed). It is a bug.,
`
Table with ReplicatedMergeTree engine.

**Does it reproduce on recent release?**
Reproduces at version 21.3.5.42 

**How to reproduce**
I didn't find any specific requests around this time: only inserts and several alter deletes ( in 1-hour time range around 17:45)

**Error message and/or stacktrace**
`
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 2021.04.17 17:45:30.287957 [ 780 ] {} <Error> db.table (d577b766-e1b9-4a33-be19-6ac5f968ad41): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 49, e.displayText() = DB::Exception: Part d23fba2922c1a8f3adafceb40a86c34c_45540_46193_7_46162 intersects next part d23fba2922c1a8f3adafceb40a86c34c_46190_46194_1 (state Committed). It is a bug., Stack trace (when copying this message, always include the lines below):
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 0. DB::MergeTreeData::getActivePartsToReplace(DB::MergeTreePartInfo const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>&, std::__1::unique_lock<std::__1::mutex>&) const @ 0xf5e6ed0 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 1. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >*) @ 0xf5e8484 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 2. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) @ 0xf5eaabd in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 3. DB::MergeTreeDataMergerMutator::renameMergedTemporaryPart(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&, DB::MergeTreeData::Transaction*) @ 0xf6389f2 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 4. DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) @ 0xf3eb027 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 5. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xf3dfef2 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 6. ? @ 0xf451b7f in /usr/bin/clickhouse   Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 7. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xf787d98 in /usr/bin/clickhouse                                                                                                                       Apr 17 17:45:30click-inst-1.com clickhouse-server[43]: 8. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0xf409f3d in /usr/bin/clickhouse        Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 9. ? @ 0xf5789a7 in /usr/bin/clickhouse   Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x86502c8 in /usr/bin/clickhouse                       Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 11. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x865227f in /usr/bin/clickhouse                                                                                                                Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864d89f in /usr/bin/clickhouse                               Apr 17 17:45:30 click-inst-1.comu clickhouse-server[43]: 13. ? @ 0x8651333 in /usr/bin/clickhouse
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 14. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: 15. clone @ 0xfdead in /usr/lib64/libc-2.17.so
Apr 17 17:45:30 click-inst-1.com clickhouse-server[43]: (version 21.3.5.42 (official build)) `

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Some `ALTER PARTITION` queries might cause `Part A intersects previous part B` and `Unexpected merged part C intersecting drop range D` errors in replication queue. It's fixed.
Fixes #23296.

Detailed description / Documentation draft:
Fixed two independent bugs:
 - Race between creation of `MERGE_PARTS` and `DROP_RANGE`/`REPLACE_RANGE` on multiple leaders
 - Incorrect virtual part name for `REPLACE_RANGE` which breaks invariants in replication queue and merge predicate

### CODE REVIEW

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -2459,7 +2495,17 @@ bool StorageReplicatedMergeTree::executeReplaceRange(const LogEntry & entry)
...
-                parts_to_remove = removePartsInRangeFromWorkingSet(drop_range, true, false, data_parts_lock);
+            {
+                parts_to_remove = removePartsInRangeFromWorkingSet(drop_range, true, data_parts_lock);
+                String parts_to_remove_str;
+                for (const auto & part : parts_to_remove)
+                {
+                    parts_to_remove_str += part->name;
+                    parts_to_remove_str += " ";
+                }
+                LOG_TRACE(log, "Replacing {} parts {}with {} parts ", parts_to_remove.size(), parts_to_remove_str,
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:2506]:
```suggestion
                LOG_TRACE(log, "Replacing {} parts {}with {} parts {}", parts_to_remove.size(), parts_to_remove_str,
```

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 2]
```diff
@@ -4748,27 +4795,31 @@ bool StorageReplicatedMergeTree::getFakePartCoveringAllPartsInPartition(const St
...
-    auto max_level = std::numeric_limits<decltype(part_info.level)>::max();
-    if (!for_replace_partition)
+    if (for_replace_range)
     {
-        max_level = MergeTreePartInfo::MAX_LEVEL;
-
-        /// Empty partition.
-        if (right == 0)
-            return false;
+        /// NOTE Undo max block number decrement for REPLACE_RANGE, because there are invariants:
```
Comment (tavplubix) [inline src/Storages/StorageReplicatedMergeTree.cpp:4805]:
```suggestion
        /// NOTE Do not decrement max block number for REPLACE_RANGE, because there are invariants:
```

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 3]
```diff
@@ -6169,25 +6219,31 @@ void StorageReplicatedMergeTree::replacePartitionFrom(
     /// So, such case has special meaning, if drop_range contains only one block it means that nothing to drop.
     /// TODO why not to add normal DROP_RANGE entry to replication queue if `replace` is true?
     MergeTreePartInfo drop_range;
-    getFakePartCoveringAllPartsInPartition(partition_id, drop_range, true);
+    std::optional<EphemeralLockInZooKeeper> delimiting_block_lock;
+    bool partition_was_empty = !getFakePartCoveringAllPartsInPartition(partition_id, drop_range, delimiting_block_lock, true);
+    if (replace && partition_was_empty)
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:6224]: But where is the guarantee that no concurrent insert can happen here? Or in this case it's OK?

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 4]
```diff
@@ -6511,13 +6566,15 @@ void StorageReplicatedMergeTree::movePartitionToTable(const StoragePtr & dest_ta
...
     }
 
-    Coordination::Requests ops_dest;
+    Coordination::Requests ops_src;
 
-    ops_dest.emplace_back(zkutil::makeCreateRequest(
+    ops_src.emplace_back(zkutil::makeCreateRequest(
         zookeeper_path + "/log/log-", entry_delete.toString(), zkutil::CreateMode::PersistentSequential));
-    ops_dest.emplace_back(zkutil::makeSetRequest(zookeeper_path + "/log", "", -1));  /// Just update version
+    ops_src.emplace_back(zkutil::makeSetRequest(zookeeper_path + "/log", "", -1));  /// Just update version
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:6573]: Maybe add to comment: `because merges assignment relies on it` or something like this.

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 5]
```diff
@@ -2474,7 +2510,17 @@ bool StorageReplicatedMergeTree::executeReplaceRange(const LogEntry & entry)
...
+            {
+                parts_to_remove = removePartsInRangeFromWorkingSet(drop_range, true, data_parts_lock);
+                String parts_to_remove_str;
+                for (const auto & part : parts_to_remove)
+                {
+                    parts_to_remove_str += part->name;
+                    parts_to_remove_str += " ";
+                }
+                LOG_TRACE(log, "Replacing {} parts {}with {} parts {}", parts_to_remove.size(), parts_to_remove_str,
+                          final_parts.size(), boost::algorithm::join(final_part_names, ", "));
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:2522]: btw `fmt::join` requires less characters :)

File: src/Storages/MergeTree/ReplicatedMergeTreeLogEntry.cpp [hunk 6]
```diff
@@ -386,4 +387,35 @@ ReplicatedMergeTreeLogEntry::Ptr ReplicatedMergeTreeLogEntry::parse(const String
...
+    /// should not be blocked (only execution of merges should be blocked).
+    if (type == CLEAR_COLUMN || type == CLEAR_INDEX)
+        return {};
+
+    if (type == REPLACE_RANGE)
+    {
+        Strings res = replace_range_entry->new_part_names;
+        auto drop_range_info = MergeTreePartInfo::fromPartName(replace_range_entry->drop_range_part_name, format_version);
+        assert(drop_range_info.getBlocksCount() != 0);
+        if (drop_range_info.getBlocksCount() > 1)
```
Comment (alesapin) [inline src/Storages/MergeTree/ReplicatedMergeTreeLogEntry.cpp:410]: Sounds weird, but maybe even create a separate function for this check?)

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 7]
```diff
@@ -224,6 +224,26 @@ static String extractZooKeeperPath(const String & path)
...
+static MergeTreePartInfo makeDummyDropRangeForMovePartitionOrAttachPartitionFrom(const String & partition_id)
+{
+    /// NOTE We don't have special log entry type for MOVE PARTITION/ATTACH PARTITION FROM,
+    /// so we use REPLACE_RANGE with dummy range of one block, which means "attach, not replace".
+    /// It's safe to fill drop range for MOVE PARTITION/ATTACH PARTITION FROM with zeros,
+    /// because drop range for REPLACE PARTITION must contain at least 2 blocks,
+    /// so we can distinguish dummy drop range from any real or virtual part.
+    /// But we should never construct such part name, even for virtual part,
+    /// because it can be confused with real part <partition>_0_0_0.
+    /// TODO get rid of this.
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:236]: ohhh, maybe just add a flag and make it backward-incompatible?

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 8]
```diff
@@ -4853,27 +4900,30 @@ bool StorageReplicatedMergeTree::getFakePartCoveringAllPartsInPartition(const St
...
-
-        /// Empty partition.
-        if (right == 0)
-            return false;
+        /// NOTE Do not decrement max block number for REPLACE_RANGE, because there are invariants:
+        /// - drop range for REPLACE PARTITION must contain at least 2 blocks (1 skipped block and at least 1 real block)
+        /// - drop range for MOVE PARTITION/ATTACH PARTITION FROM always contains 1 block
 
-        --right;
+        /// NOTE UINT_MAX was previously used as max level for REPLACE/MOVE PARTITION (it was incorrect)
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:4914]: I'd prefer to forget about it :)

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 9]
```diff
@@ -2359,16 +2359,13 @@ MergeTreeData::DataPartsVector MergeTreeData::removePartsInRangeFromWorkingSet(c
...
             throw Exception("Unexpected partition_id of part " + part->name + ". This is a bug.", ErrorCodes::LOGICAL_ERROR);
 
-        if (part->info.min_block < drop_range.min_block)
+        if (part->info.min_block < drop_range.min_block)    /// NOTE Always false, because drop_range.min_block == 0
         {
             if (drop_range.min_block <= part->info.max_block)
             {
                 /// Intersect left border
-                String error = "Unexpected merged part " + part->name + " intersecting drop range " + drop_range.getPartName();
-                if (!skip_intersecting_parts)
```
Comment (alesapin) [inline src/Storages/MergeTree/MergeTreeData.cpp:2368]: What the hell was that....

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 10]
```diff
@@ -6169,25 +6219,31 @@ void StorageReplicatedMergeTree::replacePartitionFrom(
...
-        /// It is better to prohibit them on leader replica (like DROP PARTITION makes),
-        ///  but it is inconvenient for a user since he could actually use source table from this replica.
-        /// Therefore prohibit merges on the initializer server now and on the remaining servers when log entry will be executed.
-        /// It does not provides strong guarantees, but is suitable for intended use case (assume merges are quite rare).
-
-        {
-            std::lock_guard merge_selecting_lock(merge_selecting_mutex);
-            queue.disableMergesInBlockRange(drop_range_fake_part_name);
-        }
+        /// Optional step
```
Comment (alesapin) [inline src/Storages/StorageReplicatedMergeTree.cpp:6244]: Bad comment, need clarification.

**Review by alesapin — COMMENTED** [review]
I understand the current implementation, but I don't understand how it has been working before...

And maybe a backward-incompatible change would be OK.

File: src/Storages/StorageReplicatedMergeTree.cpp (hunk 3 above)
Comment (tavplubix) [reply src/Storages/StorageReplicatedMergeTree.cpp:6224]: It's ok, all blocks with numbers less than `delimiting_block_lock->getNumber()` will be dropped, and newer blocks with greater numbers will not. But we must hold `delimiting_block_lock` until creation of `DROP_RANGE`/`REPLACE_RANGE` entry in replication log to avoid merges intersecting `delimiting_block_lock->getNumber()`.

File: src/Storages/StorageReplicatedMergeTree.cpp (hunk 7 above)
Comment (tavplubix) [reply src/Storages/StorageReplicatedMergeTree.cpp:236]: It will not be possible to backport the fix with such change

**Review by alesapin — APPROVED** [review]
LGTM

**Comment by alesapin** [comment]
`Functional stateless tests flaky check (address)` -- timeout is ok, the test quite long.
` Integration tests (asan)` -- timeout ok
`Integration tests (thread)` -- both failed tests are known
`Stress test (thread)` -- single optimize query hung on `waitForTableReplicaToProcessLogEntry`. Again, looks like we wait something in sanitizer allocator https://gist.github.com/alesapin/6cbc18d51d10be790e636798bec0da63
