### PR TITLE
fix crash with clickhouse-client with syntax highlighting

### LINKED ISSUE #83987: The shortest query to break ClickHouse client record has been broken
### Describe the bug

Just type 13 chars plus newline 😄 

### How to reproduce

Run:

```sql
SELECT x'A0';
```

### Error message and/or stacktrace

Stack trace:

```
contrib/llvm-project/libcxx/include/vector:1436: assertion __n < size() failed: vector[] index out of bounds
########## Short fault info ############
(version 25.8.1.294 (official build), build id: 551F4E4A587A1B1EDA328C4DEA6725344D6F3D93, git hash: cdcbc99238dee34ff1b1825ca8f2923567a92daa, architecture: x86_64) (from thread 3167611) Received signal 6
Signal description: Aborted

Stack trace: 0x0000733fdcea49bd 0x0000733fdce4579e 0x0000733fdce288cd 0x000062c6ca4dcedd 0x000062c6c19702cf 0x000062c6c1970b04 0x000062c6c193ba92 0x000062c6c194bc51 0x000062c6c194c3fc 0x000062c6c194db72 0x000062c6c19562eb 0x000062c6b7ec3d79 0x000062c6c9968451 0x000062c6b7ecf0a6 0x000062c6b0cbdea7 0x0000733fdce2a578 0x0000733fdce2a63b 0x000062c6b0caf02e
########################################
(version 25.8.1.294 (official build), build id: 551F4E4A587A1B1EDA328C4DEA6725344D6F3D93, git hash: cdcbc99238dee34ff1b1825ca8f2923567a92daa) (from thread 3167611) (no query) Received signal Aborted (6)

Stack trace: 0x0000733fdcea49bd 0x0000733fdce4579e 0x0000733fdce288cd 0x000062c6ca4dcedd 0x000062c6c19702cf 0x000062c6c1970b04 0x000062c6c193ba92 0x000062c6c194bc51 0x000062c6c194c3fc 0x000062c6c194db72 0x000062c6c19562eb 0x000062c6b7ec3d79 0x000062c6c9968451 0x000062c6b7ecf0a6 0x000062c6b0cbdea7 0x0000733fdce2a578 0x0000733fdce2a63b 0x000062c6b0caf02e
3. __pthread_kill @ 0x00000000000a49bd
4. __GI_raise @ 0x000000000004579e
5. abort @ 0x00000000000288cd
6. contrib/llvm-project/libcxx/src/verbose_abort.cpp:74: ? @ 0x000000002659aedd
7.0. inlined from contrib/llvm-project/libcxx/include/vector:1436: std::vector<replxx::Replxx::Color, std::allocator<replxx::Replxx::Color>>::operator[][abi:se190107](unsigned long)
7. src/Client/ClientBaseHelpers.cpp:243: DB::highlight(String const&, std::vector<replxx::Replxx::Color, std::allocator<replxx::Replxx::Color>>&, DB::Context const&, int) @ 0x000000001da2e2cf
8. src/Client/ClientBaseHelpers.cpp:418: DB::highlighted(String const&, DB::Context const&) @ 0x000000001da2eb04
9. src/Client/ClientBase.cpp:433: DB::ClientBase::parseQuery(char const*&, char const*, DB::Settings const&, bool) @ 0x000000001d9f9a92
10. src/Client/ClientBase.cpp:2412: DB::ClientBase::analyzeMultiQueryText(char const*&, char const*&, char const*, std::shared_ptr<DB::IAST>&, std::unique_ptr<DB::Exception, std::default_delete<DB::Exception>>&) @ 0x000000001da09c51
11. src/Client/ClientBase.cpp:2536: DB::ClientBase::executeMultiQuery(String const&) @ 0x000000001da0a3fc
12. src/Client/ClientBase.cpp:2894: DB::ClientBase::processQueryText(String const&) @ 0x000000001da0bb72
13. src/Client/ClientBase.cpp:3598: DB::ClientBase::runInteractive() @ 0x000000001da142eb
14. programs/client/Client.cpp:401: DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000013f81d79
15. base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x0000000025a26451
16. programs/client/Client.cpp:1143: mainEntryClickHouseClient(int, char**) @ 0x0000000013f8d0a6
17. programs/main.cpp:340: main @ 0x000000000cd7bea7
18. __libc_start_call_main @ 0x000000000002a578
19. __libc_start_main@@GLIBC_2.34 @ 0x000000000002a63b
20. _start @ 0x000000000cd6d02e
```

### PR DESCRIPTION
**Pull request by bharatnc**
Fix crash with clickhouse-client when used in interactive mode with syntax highlighting. It doesn't seem to crash with non-interactive mode.

Closes: https://github.com/ClickHouse/ClickHouse/issues/83987

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix crash with clickhouse client when used in interactive mode with syntax highlighting.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by Algunenano — CHANGES_REQUESTED** [review]
I don't understand why the fix is necessary and where the original bug is. It seems we calculate there are 9 code points, but then we try to access a 10th. Why are we trying to access a non existent code point to begin with?

File: tests/queries/0_stateless/03568_client_hex_literal_crash.sh [hunk 1]
```diff
@@ -0,0 +1,26 @@
+#!/usr/bin/expect -f
```
Comment (azat) [inline tests/queries/0_stateless/03568_client_hex_literal_crash.sh]: Also consider rewriting this as other `.expect` tests (i.e. `01565_query_loop_after_client_error.expect`) that has proper `eof` handling and introspection (via `exp_internal`), and don't forget to exclude `--disable_suggestion` from `CLICKHOUSE_CLIENT_EXPECT_OPT`

Comment (azat) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.sh]: Also, do we already have other tests for highlighting (with respect how many times recent changes lead to bugs in this area), if so, maybe we can close https://github.com/ClickHouse/ClickHouse/issues/82722 ?

**Comment by bharatnc** [comment]
> I don't understand why the fix is necessary and where the original bug is. It seems we calculate there are 9 code points, but then we try to access a 10th. Why are we trying to access a non existent code point to begin with?

It looks like this particular crash is specific to `hex` string literals such as: `x'A0'`. From my understanding, it looks like the parser counts each hex digit as a separate logical character and the `code_point_pos` is incremented once per digit and therefore twice per encoded byte. However, it looks like there's only one code point available per unicode character in the colors vector that's provided to the `highlight` function of the original query.  So, due to this increment behavior, `code_point_pos` could be become equal to `colors.size()` (one past the end) and when this happens, any subsequent writes can lead to out of bound access. The minimal and easiest fix I can think of was introducing bound checks to guard the assignments. I think a longer term fix is probably to refactor `hex-literal` path to handle such cases properly. I'll add a comment on the checks being added for a potential follow up if that makes sense to you.

**Comment by bharatnc** [comment]
> I don't understand why the fix is necessary and where the original bug is. It seems we calculate there are 9 code points, but then we try to access a 10th. Why are we trying to access a non existent code point to begin with?

This particular crash is specific to hex string literals such as: x'A0'. From my understanding, hex literals can be interpreted as invalid utf-8 sequences and the `code_point_pos` could be incremented incorrectly. However, it looks like the `colors` vector that's provided to the highlight function is sized based on `utf-8` code points. Due to this increment behavior, `code_point_pos` could be become equal to `colors.size()` (one past the end) leading to out of bound access on subsequent writes. The easiest safeguard that I was able to think of was introducing bound checks to guard these assignments. For now, I can add a comment on the checks being added and do a follow up (later) if needed later.

File: tests/queries/0_stateless/03568_client_hex_literal_crash.sh (hunk 1 above)
Comment (bharatnc) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.sh]: > Also consider rewriting this as other .expect tests (i.e. 01565_query_loop_after_client_error.expect) that has proper eof handling and introspection (via exp_internal), and don't forget to exclude --disable_suggestion from CLICKHOUSE_CLIENT_EXPECT_OPT

Sure, I converted the test to a `.expect` test and adopted the test setup from the existing `.expect` test. Excluded the option `--disable_suggestion`.

Comment (bharatnc) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.sh]: > Also, do we already have other tests for highlighting (with respect how many times recent changes lead to bugs in this area), if so, maybe we can close https://github.com/ClickHouse/ClickHouse/issues/82722 ?

I'm not sure about that. Btw, there are some `.expect` tests left masquerading as `.sh` tests:
```
grep -r --include="*.sh" '#!/usr/bin/expect -f' .
./01599_multiline_input_and_singleline_comments.sh:#!/usr/bin/expect -f
./01610_client_spawn_editor.sh:#!/usr/bin/expect -f
./02204_fractional_progress_bar_long.sh:#!/usr/bin/expect -f
./02910_bad_logs_level_in_local.sh:#!/usr/bin/expect -f
./02563_progress_when_no_rows_from_prewhere.sh:#!/usr/bin/expect -f
./03021_output_format_tty.sh:#!/usr/bin/expect -f
```

I can probably do a followup to convert them to proper `.expect` tests.

**Comment by Algunenano** [comment]
> This particular crash is specific to hex string literals such as: x'A0'. From my understanding, hex literals can be interpreted as invalid utf-8 sequences and the code_point_pos could be incremented incorrectly. However, it looks like the colors vector that's provided to the highlight function is sized based on utf-8 code points

I don't understand this reasoning. I'd expect `UTF8::countCodePoints` to be consistent with `char_pos += UTF8::seqLength` and if not that's the bug.

> The easiest safeguard that I was able to think of was introducing bound checks to guard these assignments

This is just hiding the bug. If the the number of characters doesn't match, doing bounds check is only going to prevent the crash while having incorrect highlighting. Let's fix it properly or revert the change and reintroduce later once it's properly done

**Comment by bharatnc** [comment]
>  I'd expect UTF8::countCodePoints to be consistent with char_pos += UTF8::seqLength and if not that's the bug.

Yes, it looks like there are some inconsistencies between `UTF8::countCodePoints` and `UTF8::seqLength`. It looks like `UTF8::seqLength` does the correct thing and `UTF8::countCodePoints` needs some fixing. I pushed another temporary fix which doesn't involve bound checks but also uses `UTF8::seqLength` to calculate code points instead of `UTF8::countCodePoints `. I'll either keep this fix or the original bounds check and circle back with a proper fix in case I can't get the fix in by the release. At least, one of these temporary fixes would act as a safeguard from crashing.

**Review by Algunenano — APPROVED** [review]
Really useful comment. Thanks!

File: tests/queries/0_stateless/03568_client_hex_literal_crash.sh (hunk 1 above)
Comment (azat) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.sh]: >I can probably do a followup to convert them to proper .expect tests.

Thanks! That would be really useful

File: tests/queries/0_stateless/03568_client_hex_literal_crash.expect [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+match_max 100000
+
+expect_after {
+    # Do not ignore eof from expect
+    -i $any_spawn_id eof { exp_continue }
+    # A default timeout action is to do nothing, change it to fail
+    -i $any_spawn_id timeout { exit 1 }
+}
+
+spawn bash -c "source $basedir/../shell_config.sh ; \$CLICKHOUSE_CLIENT_BINARY \$CLICKHOUSE_CLIENT_EXPECT_OPT -m --history_file=$history_file"
```
Comment (azat) [inline tests/queries/0_stateless/03568_client_hex_literal_crash.expect]:
```suggestion
spawn bash -c "source $basedir/../shell_config.sh ; \$CLICKHOUSE_CLIENT_BINARY \${CLICKHOUSE_CLIENT_EXPECT_OPT/--highlight 0/--highlight 1} -m --history_file=$history_file"
```

File: src/Client/ClientBaseHelpers.cpp [hunk 3]
```diff
@@ -413,7 +413,42 @@ void highlight(const String & query, std::vector<replxx::Replxx::Color> & colors
...
+    /// counting to ensure consistency when invalid UTF-8 bytes are detected (use UTF8::countCodePoints for all other
+    /// cases to mainly for performance concerns).
+    /// TODO: @bharatnc Fix UTF8::countCodePoints to handle invalid UTF-8 sequences consistently with seqLength so that
+    /// this logic can be removed.
+    bool has_invalid_utf8 = false;
+    for (const char c : query)
+    {
+        /// Standalone UTF-8 continuation bytes (0x80-0xBF, e.g. 0xA0 from hex literals)
+        /// cause countCodePoints/seqLength inconsistency.
+        if (static_cast<unsigned char>(c) >= 0x80 && static_cast<unsigned char>(c) <= 0xBF)
```
Comment (azat) [inline src/Client/ClientBaseHelpers.cpp:431]: Not sure that two loops instead of one will be faster, but I'm fine with it anyway

**Review by azat — APPROVED** [review]

File: tests/queries/0_stateless/03568_client_hex_literal_crash.expect [hunk 4]
```diff
@@ -21,7 +21,7 @@ expect_after {
     -i $any_spawn_id timeout { exit 1 }
 }
 
-spawn bash -c "source $basedir/../shell_config.sh ; \$CLICKHOUSE_CLIENT_BINARY \$CLICKHOUSE_CLIENT_EXPECT_OPT -m --history_file=$history_file"
+spawn bash -c "source $basedir/../shell_config.sh ; \$CLICKHOUSE_CLIENT_BINARY \${CLICKHOUSE_CLIENT_EXPECT_OPT/--highlight 0/--highlight 1} -m --history_file=$history_file"
```
Comment (bharatnc) [inline tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: @azat I'm not sure why we have provided `--hightlight 0` and then `--highlight 1`. Was this supposed to be just `--highlight 1`? Test failure is related as it doesn't seem to like both options together.

Comment (azat) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: No, this is not like this, the fix was correct, `CLICKHOUSE_CLIENT_EXPECT_OPT` contains `--highlight 0`, what my patch did is **substitute `--highlight 0` with `--highlight 1`**

Comment (azat) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: Please revert your patch (or `reset --hard HEAD^`)

Comment (bharatnc) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: Reverted. You're right, my bad I didn't initially notice that that it was doing a bash parameter expansion and substitution.

**Comment by bharatnc** [comment]
Test failure is due to job timeout:

- [Integration tests (release, 3/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84025&sha=957e19c0e960222b7d334afa9c66fe0b93957092&name_0=PR&name_1=Integration%20tests%20%28release%2C%203%2F4%29)  https://github.com/ClickHouse/ClickHouse/issues/82674 - (known issue)

File: tests/queries/0_stateless/03568_client_hex_literal_crash.expect (hunk 4 above)
Comment (azat) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: @bharatnc can we also match the exact escape sequences that is used for highligiting, to ensure that it is there? That way the test will fail with `--highlight 0`

Comment (bharatnc) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: sure, doing it in https://github.com/ClickHouse/ClickHouse/pull/84628

Comment (azat) [reply tests/queries/0_stateless/03568_client_hex_literal_crash.expect]: Thank you! I've tested it and now the test does not work w/o `highligh 1` substitution
