### PR TITLE
Fix stacktraces for binaries without debug symbols

### LINKED ISSUE #59438: Empty stacktrace on ClickHouse 24.1
I'm installing ClickHouse 24.1 using the official packages with

```
sudo apt install clickhouse-client=24.1.1.2048 clickhouse-server=24.1.1.2048 clickhouse-common-static=24.1.1.2048
```

After running the server I've started seeing empty stacktraces as the following one:

```
2024.01.31 15:49:06.902219 [ 1822983 ] {cea6f52f-3def-4bf1-9ca2-9bab93df0051} <Error> TCPHandler: Code: 47. DB::Exception: Missing columns: 'jrdi' while processing query: 'SELECT hostname, event_time, table, name, event_type, merge_reason, jrdi FROM system.part_log WHERE name = '2024_207072_207868_163'', required columns: 'hostname' 'table' 'event_type' 'event_time' 'name' 'merge_reason' 'jrdi', maybe you meant: 'hostname', 'table', 'event_type', 'event_time' or 'merge_reason'. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):

0. ? @ 0x000000000c802edb in /usr/bin/clickhouse
1. ? @ 0x000000000730800c in /usr/bin/clickhouse
2. ? @ 0x00000000118574c0 in /usr/bin/clickhouse
3. ? @ 0x000000001185d61b in /usr/bin/clickhouse
4. ? @ 0x00000000114dec05 in /usr/bin/clickhouse
5. ? @ 0x00000000114d4e6c in /usr/bin/clickhouse
6. ? @ 0x0000000011593358 in /usr/bin/clickhouse
7. ? @ 0x0000000011599757 in /usr/bin/clickhouse
8. ? @ 0x00000000114bae39 in /usr/bin/clickhouse
9. ? @ 0x0000000011904956 in /usr/bin/clickhouse
10. ? @ 0x00000000119016ba in /usr/bin/clickhouse
11. ? @ 0x000000001291dd69 in /usr/bin/clickhouse
12. ? @ 0x0000000012935df9 in /usr/bin/clickhouse
13. ? @ 0x00000000153a79b2 in /usr/bin/clickhouse
14. ? @ 0x00000000153a87b1 in /usr/bin/clickhouse
15. ? @ 0x00000000154a0f87 in /usr/bin/clickhouse
16. ? @ 0x000000001549f5bd in /usr/bin/clickhouse
17. ? @ 0x00007fba65094ac3
18. ? @ 0x00007fba65126850
```

Looks like something is off with those packages. To test things further I've install debug symbols with the following command and the situation improved a bit:

```
sudo apt install clickhouse-common-static-dbg=24.1.1.2048
```

```
2024.01.31 15:49:06.902219 [ 1822983 ] {cea6f52f-3def-4bf1-9ca2-9bab93df0051} <Error> TCPHandler: Code: 47. DB::Exception: Missing columns: 'jrdi' while processing query: 'SELECT hostname, event_time, table, name, event_type, merge_reason, jrdi FROM system.part_log WHERE name = '2024_207072_207868_163'', required columns: 'hostname' 'table' 'event_type' 'event_time' 'name' 'merge_reason' 'jrdi', maybe you meant: 'hostname', 'table', 'event_type', 'event_time' or 'merge_reason'. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:96: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c802edb in /usr/lib/debug/usr/bin/clickhouse.debug
1. ? @ 0x000000000730800c in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./src/Interpreters/TreeRewriter.cpp:0: DB::TreeRewriterResult::collectUsedColumns(std::shared_ptr<DB::IAST> const&, bool, bool) @ 0x00000000118574c0 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./src/Interpreters/TreeRewriter.cpp:0: DB::TreeRewriter::analyzeSelect(std::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::vector<DB::TableWithColumnNamesAndTypes, std::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::TableJoin>) const @ 0x000000001185d61b in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./contrib/llvm-project/libcxx/include/__utility/swap.h:37: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>)::$_0::operator()(bool) const @ 0x00000000114dec05 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x00000000114d4e6c in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000011593358 in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./contrib/llvm-project/libcxx/include/__functional/function.h:717: ? @ 0x0000000011599757 in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./src/Interpreters/InterpreterFactory.cpp:0: DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x00000000114bae39 in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011904956 in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/./src/Interpreters/executeQuery.cpp:1285: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000119016ba in /usr/lib/debug/usr/bin/clickhouse.debug
11. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:612: DB::TCPHandler::runImpl() @ 0x000000001291dd69 in /usr/lib/debug/usr/bin/clickhouse.debug
12. ./build_docker/./src/Server/TCPHandler.cpp:2298: DB::TCPHandler::run() @ 0x0000000012935df9 in /usr/lib/debug/usr/bin/clickhouse.debug
13. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x00000000153a79b2 in /usr/lib/debug/usr/bin/clickhouse.debug
14. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x00000000153a87b1 in /usr/lib/debug/usr/bin/clickhouse.debug
15. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x00000000154a0f87 in /usr/lib/debug/usr/bin/clickhouse.debug
16. ./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001549f5bd in /usr/lib/debug/usr/bin/clickhouse.debug
17. ? @ 0x00007face0094ac3
18. ? @ 0x00007face0126850
```

This is easy to reproduce, just start the ClickHouse server and run any query that produces an error. I'm using this one:

```sql
SELECT
    hostname,
    event_time,
    table,
    name,
    event_type,
    merge_reason,
    jrdi -- Wrong columns
FROM system.part_log
WHERE name = '2024_207072_207868_163'
```

### PR DESCRIPTION
**Pull request by azat**
During refactoring in #58610 it had been broken since itassumes that the information about file is always available, otherwise it will not print symbol name.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix stacktraces for binaries without debug symbols

Fixes: https://github.com/ClickHouse/ClickHouse/issues/59438 (cc @nickitat)

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit f8f66a083e293a8ac555c42525b0ad1dbcb51db2 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59444/f8f66a083e293a8ac555c42525b0ad1dbcb51db2/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59444/f8f66a083e293a8ac555c42525b0ad1dbcb51db2/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by nickitat** [comment]
can we create a test for it?

**Comment by azat** [comment]
>can we create a test for it?

I thought about this, but I don't want to strip binaries (or/and play with debug symbols in tests, plus fasttest has different type of binary then the packages has) in tests.

But I think something like this will be OK - [`0b74c4e` (#59444)](https://github.com/ClickHouse/ClickHouse/pull/59444/commits/0b74c4e58042e6eefdcb70a2b1c635dcbe7a31e7)

File: docker/test/fasttest/run.sh [hunk 1]
```diff
@@ -211,6 +211,11 @@ function build
         echo "build_clickhouse_fasttest_binary: [ OK ] $BUILD_SECONDS_ELAPSED sec." \
           | ts '%Y-%m-%d %H:%M:%S' \
           | tee "$FASTTEST_OUTPUT/test_result.txt"
+
+        stripped_clickhouse_shows_symbols_names=FAIL
+        programs/clickhouse-stripped --stacktrace -q 'select' |& grep -q 'DB::LocalServer::main' && stripped_clickhouse_shows_symbols_names=OK
+        echo "stripped_clickhouse_shows_symbols_names: [ $stripped_clickhouse_shows_symbols_names ] 0 sec."
```
Comment (nickitat) [inline docker/test/fasttest/run.sh:217]: shouldn't it be written into `test_result.txt`?

Comment (azat) [reply docker/test/fasttest/run.sh]: Ops, forgot this bit, thanks

**Comment by azat** [comment]
>Fast test — fail: 1, passed: 4976, skipped: 1084

- `02720_row_policy_column_with_dots` - #59453

**Comment by azat** [comment]
>Fast test — fail: 0, passed: 4977, skipped: 1084

- `stripped_clickhouse_shows_symbols_names` - OK

**Comment by Felixoid** [comment]
It's definitely fixed. Let's spin a new patch release today

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/issues/59475 azure sanitizer
