### PR TITLE
Set enable_http_compression default value to 1

### LINKED ISSUE #71591: Enable enable_http_compression by default
**Describe the issue**
Clients using the HTTP Interface can benefit from compression by enabling the `enable_http_compression` setting, either with `/?enable_http_compression=1` or `... SETTINGS enable_http_compression = 1`.
They also need to opt in with either `Accept-Encoding` (response) or `Content-Encoding` (request body).

HTTP natively supports a way to opt into compression (and ClickHouse already requires it). Why is `enable_http_compression=1` not the default?

**How to reproduce**
* Which ClickHouse server version to use
* 23.3
* Which interface to use, if matters
* HTTP

**Expected behavior**
`enable_http_compression=1` by default?

**Additional context**
I noticed trying to "optimize" a service – and noticed _harder_ when it broke because `readonly` clients can't change settings.

### PR DESCRIPTION
**Pull request by petern48**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Changes the default value of `enable_http_compression` from 0 to 1. Closes #71591

### Documentation entry for user-facing changes

- [x] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Also add to SettingsChangesHistory for the version 24.11.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit f60d35161f9d4b34fac0f51ad566906301cb3762 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71774/f60d35161f9d4b34fac0f51ad566906301cb3762/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/71774/f60d35161f9d4b34fac0f51ad566906301cb3762/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by petern48** [comment]
@alexey-milovidov All passed

File: src/Core/Settings.cpp [hunk 1]
```diff
@@ -1794,7 +1794,7 @@ Possible values:
 
 - 0 — Disabled.
 - 1 — Enabled.
-)", 0) \
+)", 1) \
```
Comment (Algunenano) [inline src/Core/Settings.cpp:1797]: This change was incorrect and should have changed the first line (false -> true). Reverting in https://github.com/ClickHouse/ClickHouse/pull/72319 since it requires test changes and we need to keep things clean for 24.11. Need to be reintroduced with those fixes for 24.12
