### PR TITLE
Fix memory leak in slru cache policy

### LINKED ISSUE #64791: Memory leaks in FileCache (in SLRU cache eviction policy)
It seems some memory isn't freed on shutdown in FileCache (maybe due to cyclic references?) CC @kssenii 

**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/64767/7290e270dc0f834edaeeb37e26485224d9977023/stress_test__asan_/stderr.log

**Error message and/or stacktrace**
```
==73618==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 31992 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x5588330b91be in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x5588330b91be in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x5588330b91be in std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegment, std::__1::allocator<DB::FileSegment>>>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x5588330b91be in std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegment, std::__1::allocator<DB::FileSegment>>>>::allocate[abi:v15000](std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegment, std::__1::allocator<DB::FileSegment>>>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x5588330b91be in std::__1::__allocation_guard<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegment, std::__1::allocator<DB::FileSegment>>>>::__allocation_guard[abi:v15000]<std::__1::allocator<DB::FileSegment>>(std::__1::allocator<DB::FileSegment>, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocation_guard.h:53:18
    #6 0x5588330b91be in std::__1::shared_ptr<DB::FileSegment> std::__1::allocate_shared[abi:v15000]<DB::FileSegment, std::__1::allocator<DB::FileSegment>, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void>(std::__1::allocator<DB::FileSegment> const&, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:952:48
    #7 0x5588330b91be in std::__1::shared_ptr<DB::FileSegment> std::__1::make_shared[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void>(DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #8 0x5588330b91be in DB::FileCache::addFileSegment(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, DB::CachePriorityGuard::Lock const*) build_docker/./src/Interpreters/Cache/FileCache.cpp:785:25
    #9 0x5588330b87a2 in DB::FileCache::splitRangeIntoFileSegments(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, unsigned long, DB::CreateFileSegmentSettings const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:364:41
    #10 0x5588330bd44a in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:663:25
    #11 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #12 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #13 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9
    #14 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16
    #15 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #16 0x55882f2bccae in DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:209:32

Indirect leak of 17112 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x5588331591c7 in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x5588331591c7 in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x5588331591c7 in std::__1::allocator<std::__1::__shared_ptr_emplace<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>>>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x5588331591c7 in std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>>>>::allocate[abi:v15000](std::__1::allocator<std::__1::__shared_ptr_emplace<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>>>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x5588331591c7 in std::__1::__allocation_guard<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>>>>::__allocation_guard[abi:v15000]<std::__1::allocator<DB::KeyMetadata>>(std::__1::allocator<DB::KeyMetadata>, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocation_guard.h:53:18
    #6 0x5588331591c7 in std::__1::shared_ptr<DB::KeyMetadata> std::__1::allocate_shared[abi:v15000]<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&, void>(std::__1::allocator<DB::KeyMetadata> const&, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:952:48
    #7 0x55883313a4e4 in std::__1::shared_ptr<DB::KeyMetadata> std::__1::make_shared[abi:v15000]<DB::KeyMetadata, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&, void>(DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #8 0x55883313a4e4 in DB::CacheMetadata::getKeyMetadata(DB::FileCacheKey const&, DB::CacheMetadata::KeyNotFoundPolicy, DB::FileCacheUserInfo const&, bool) build_docker/./src/Interpreters/Cache/Metadata.cpp:286:18
    #9 0x55883313934a in DB::CacheMetadata::lockKeyMetadata(DB::FileCacheKey const&, DB::CacheMetadata::KeyNotFoundPolicy, DB::FileCacheUserInfo const&, bool) build_docker/./src/Interpreters/Cache/Metadata.cpp:230:25
    #10 0x5588330bcb94 in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:572:32
    #11 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #12 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #13 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9
    #14 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16
    #15 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)

Indirect leak of 8184 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x5588331892e6 in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x5588331892e6 in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x5588331892e6 in std::__1::allocator<std::__1::__shared_ptr_emplace<DB::IFileCachePriority::Entry, std::__1::allocator<DB::IFileCachePriority::Entry>>>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x5588331892e6 in std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::IFileCachePriority::Entry, std::__1::allocator<DB::IFileCachePriority::Entry>>>>::allocate[abi:v15000](std::__1::allocator<std::__1::__shared_ptr_emplace<DB::IFileCachePriority::Entry, std::__1::allocator<DB::IFileCachePriority::Entry>>>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x5588331892e6 in std::__1::__allocation_guard<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::IFileCachePriority::Entry, std::__1::allocator<DB::IFileCachePriority::Entry>>>>::__allocation_guard[abi:v15000]<std::__1::allocator<DB::IFileCachePriority::Entry>>(std::__1::allocator<DB::IFileCachePriority::Entry>, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocation_guard.h:53:18
    #6 0x5588331892e6 in std::__1::shared_ptr<DB::IFileCachePriority::Entry> std::__1::allocate_shared[abi:v15000]<DB::IFileCachePriority::Entry, std::__1::allocator<DB::IFileCachePriority::Entry>, DB::FileCacheKey const&, unsigned long&, unsigned long&, std::__1::shared_ptr<DB::KeyMetadata>&, void>(std::__1::allocator<DB::IFileCachePriority::Entry> const&, DB::FileCacheKey const&, unsigned long&, unsigned long&, std::__1::shared_ptr<DB::KeyMetadata>&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:952:48
    #7 0x5588331892e6 in std::__1::shared_ptr<DB::IFileCachePriority::Entry> std::__1::make_shared[abi:v15000]<DB::IFileCachePriority::Entry, DB::FileCacheKey const&, unsigned long&, unsigned long&, std::__1::shared_ptr<DB::KeyMetadata>&, void>(DB::FileCacheKey const&, unsigned long&, unsigned long&, std::__1::shared_ptr<DB::KeyMetadata>&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #8 0x5588331892e6 in DB::SLRUFileCachePriority::add(std::__1::shared_ptr<DB::KeyMetadata>, unsigned long, unsigned long, DB::FileCacheUserInfo const&, DB::CachePriorityGuard::Lock const&, bool) build_docker/./src/Interpreters/Cache/SLRUFileCachePriority.cpp:121:52
    #9 0x5588330c1144 in DB::FileCache::tryReserve(DB::FileSegment&, unsigned long, DB::FileCacheReserveStat&, DB::FileCacheUserInfo const&, unsigned long) build_docker/./src/Interpreters/Cache/FileCache.cpp:936:41
    #10 0x558833111963 in DB::FileSegment::reserve(unsigned long, unsigned long, DB::FileCacheReserveStat*) build_docker/./src/Interpreters/Cache/FileSegment.cpp:562:28
    #11 0x55882f2d5313 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:1001:41
    #12 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16
    #13 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #14 0x55882f2bccae in DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:209:32
    #15 0x55882f2bcb4a in DB::ReadBufferFromRemoteFSGather::nextImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:181:9
    #16 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)

Indirect leak of 8184 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x558833189396 in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x558833189396 in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x558833189396 in std::__1::allocator<std::__1::__shared_ptr_emplace<DB::SLRUFileCachePriority::SLRUIterator, std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>>>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x558833189396 in std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::SLRUFileCachePriority::SLRUIterator, std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>>>>::allocate[abi:v15000](std::__1::allocator<std::__1::__shared_ptr_emplace<DB::SLRUFileCachePriority::SLRUIterator, std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>>>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x558833189396 in std::__1::__allocation_guard<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::SLRUFileCachePriority::SLRUIterator, std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>>>>::__allocation_guard[abi:v15000]<std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>>(std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocation_guard.h:53:18
    #6 0x558833189396 in std::__1::shared_ptr<DB::SLRUFileCachePriority::SLRUIterator> std::__1::allocate_shared[abi:v15000]<DB::SLRUFileCachePriority::SLRUIterator, std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator>, DB::SLRUFileCachePriority*, DB::LRUFileCachePriority::LRUIterator, bool, void>(std::__1::allocator<DB::SLRUFileCachePriority::SLRUIterator> const&, DB::SLRUFileCachePriority*&&, DB::LRUFileCachePriority::LRUIterator&&, bool&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:952:48
    #7 0x558833189396 in std::__1::shared_ptr<DB::SLRUFileCachePriority::SLRUIterator> std::__1::make_shared[abi:v15000]<DB::SLRUFileCachePriority::SLRUIterator, DB::SLRUFileCachePriority*, DB::LRUFileCachePriority::LRUIterator, bool, void>(DB::SLRUFileCachePriority*&&, DB::LRUFileCachePriority::LRUIterator&&, bool&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #8 0x558833189396 in DB::SLRUFileCachePriority::add(std::__1::shared_ptr<DB::KeyMetadata>, unsigned long, unsigned long, DB::FileCacheUserInfo const&, DB::CachePriorityGuard::Lock const&, bool) build_docker/./src/Interpreters/Cache/SLRUFileCachePriority.cpp:122:20
    #9 0x5588330c1144 in DB::FileCache::tryReserve(DB::FileSegment&, unsigned long, DB::FileCacheReserveStat&, DB::FileCacheUserInfo const&, unsigned long) build_docker/./src/Interpreters/Cache/FileCache.cpp:936:41
    #10 0x558833111963 in DB::FileSegment::reserve(unsigned long, unsigned long, DB::FileCacheReserveStat*) build_docker/./src/Interpreters/Cache/FileSegment.cpp:562:28
    #11 0x55882f2d5313 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:1001:41
    #12 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16
    #13 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #14 0x55882f2bccae in DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:209:32
    #15 0x55882f2bcb4a in DB::ReadBufferFromRemoteFSGather::nextImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:181:9
    #16 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)

Indirect leak of 5952 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x55883bd8c692 in Poco::Logger::unsafeGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) build_docker/./base/poco/Foundation/src/Logger.cpp:396:13
    #2 0x55883bd8cd3a in Poco::Logger::getShared(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) build_docker/./base/poco/Foundation/src/Logger.cpp:356:24
    #3 0x5588331049e1 in DB::FileSegment::FileSegment(DB::FileCacheKey const&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::weak_ptr<DB::KeyMetadata>, std::__1::shared_ptr<DB::IFileCachePriority::Iterator>) build_docker/./src/Interpreters/Cache/FileSegment.cpp:71:11
    #4 0x5588330b9294 in DB::FileSegment* std::__1::construct_at[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, DB::FileSegment*>(DB::FileSegment*, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #5 0x5588330b9294 in void std::__1::allocator_traits<std::__1::allocator<DB::FileSegment>>::construct[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void, void>(std::__1::allocator<DB::FileSegment>&, DB::FileSegment*, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #6 0x5588330b9294 in std::__1::__shared_ptr_emplace<DB::FileSegment, std::__1::allocator<DB::FileSegment>>::__shared_ptr_emplace[abi:v15000]<DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>>(std::__1::allocator<DB::FileSegment>, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #7 0x5588330b9294 in std::__1::shared_ptr<DB::FileSegment> std::__1::allocate_shared[abi:v15000]<DB::FileSegment, std::__1::allocator<DB::FileSegment>, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void>(std::__1::allocator<DB::FileSegment> const&, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #8 0x5588330b9294 in std::__1::shared_ptr<DB::FileSegment> std::__1::make_shared[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void>(DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #9 0x5588330b9294 in DB::FileCache::addFileSegment(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, DB::CachePriorityGuard::Lock const*) build_docker/./src/Interpreters/Cache/FileCache.cpp:785:25
    #10 0x5588330b87a2 in DB::FileCache::splitRangeIntoFileSegments(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, unsigned long, DB::CreateFileSegmentSettings const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:364:41
    #11 0x5588330bd44a in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:663:25
    #12 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #13 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #14 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9

Indirect leak of 5952 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x55883bd8c867 in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x55883bd8c867 in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x55883bd8c867 in std::__1::allocator<char>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x55883bd8c867 in std::__1::allocator<char>::allocate_at_least[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:119:17
    #5 0x55883bd8c867 in std::__1::allocation_result<std::__1::allocator_traits<std::__1::allocator<char>>::pointer> std::__1::allocate_at_least[abi:v15000]<std::__1::allocator<char>>(std::__1::allocator<char>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocate_at_least.h:33:20
    #6 0x55883bd8c867 in auto std::__1::__allocate_at_least[abi:v15000]<std::__1::allocator<char>>(std::__1::allocator<char>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocate_at_least.h:42:10
    #7 0x55883bd8c867 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__init_copy_ctor_external(char const*, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/string:2047:25
    #8 0x55883bd8c867 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./contrib/llvm-project/libcxx/include/string:2015:9
    #9 0x55883bd8c867 in Poco::Logger::Logger(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, Poco::Channel*, int) build_docker/./base/poco/Foundation/src/Logger.cpp:51:72
    #10 0x55883bd8c867 in Poco::Logger::unsafeGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) build_docker/./base/poco/Foundation/src/Logger.cpp:396:17
    #11 0x55883bd8cd3a in Poco::Logger::getShared(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) build_docker/./base/poco/Foundation/src/Logger.cpp:356:24
    #12 0x5588331049e1 in DB::FileSegment::FileSegment(DB::FileCacheKey const&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::weak_ptr<DB::KeyMetadata>, std::__1::shared_ptr<DB::IFileCachePriority::Iterator>) build_docker/./src/Interpreters/Cache/FileSegment.cpp:71:11
    #13 0x5588330b9294 in DB::FileSegment* std::__1::construct_at[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, DB::FileSegment*>(DB::FileSegment*, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #14 0x5588330b9294 in void std::__1::allocator_traits<std::__1::allocator<DB::FileSegment>>::construct[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void, void>(std::__1::allocator<DB::FileSegment>&, DB::FileSegment*, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #15 0x5588330b9294 in std::__1::__shared_ptr_emplace<DB::FileSegment, std::__1::allocator<DB::FileSegment>>::__shared_ptr_emplace[abi:v15000]<DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>>(std::__1::allocator<DB::FileSegment>, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #16 0x5588330b9294 in std::__1::shared_ptr<DB::FileSegment> std::__1::allocate_shared[abi:v15000]<DB::FileSegment, std::__1::allocator<DB::FileSegment>, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void>(std::__1::allocator<DB::FileSegment> const&, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #17 0x5588330b9294 in std::__1::shared_ptr<DB::FileSegment> std::__1::make_shared[abi:v15000]<DB::FileSegment, DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool, DB::FileCache*, std::__1::shared_ptr<DB::KeyMetadata>, void>(DB::FileCacheKey const&, unsigned long&, unsigned long&, DB::FileSegmentState&, DB::CreateFileSegmentSettings const&, bool&&, DB::FileCache*&&, std::__1::shared_ptr<DB::KeyMetadata>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #18 0x5588330b9294 in DB::FileCache::addFileSegment(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, DB::CachePriorityGuard::Lock const*) build_docker/./src/Interpreters/Cache/FileCache.cpp:785:25
    #19 0x5588330b87a2 in DB::FileCache::splitRangeIntoFileSegments(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, unsigned long, DB::CreateFileSegmentSettings const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:364:41
    #20 0x5588330bd44a in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:663:25
    #21 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #22 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #23 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9

Indirect leak of 5208 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x5588330b948f in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x5588330b948f in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x5588330b948f in std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x5588330b948f in std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>>>::allocate[abi:v15000](std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x5588330b948f in std::__1::unique_ptr<std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>, std::__1::__tree_node_destructor<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>>>> std::__1::__tree<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>>>::__construct_node<unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&>(unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&) build_docker/./contrib/llvm-project/libcxx/include/__tree:2132:23
    #6 0x5588330b948f in std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>*, long>, bool> std::__1::__tree<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>>>::__emplace_unique_key_args<unsigned long, unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&>(unsigned long const&, unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&) build_docker/./contrib/llvm-project/libcxx/include/__tree:2095:29
    #7 0x5588330b948f in std::__1::enable_if<__can_extract_map_key<unsigned long&, unsigned long, std::__1::pair<unsigned long const, std::__1::shared_ptr<DB::FileSegmentMetadata>>>::value, std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>*, long>, bool>>::type std::__1::__tree<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::__map_value_compare<unsigned long, std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::less<unsigned long>, true>, std::__1::allocator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>>>::__emplace_unique[abi:v15000]<unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&>(unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&) build_docker/./contrib/llvm-project/libcxx/include/__tree:1179:16
    #8 0x5588330b948f in std::__1::pair<std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, std::__1::__tree_node<std::__1::__value_type<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>>, void*>*, long>>, bool> std::__1::map<unsigned long, std::__1::shared_ptr<DB::FileSegmentMetadata>, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, std::__1::shared_ptr<DB::FileSegmentMetadata>>>>::emplace[abi:v15000]<unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&>(unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&) build_docker/./contrib/llvm-project/libcxx/include/map:1221:24
    #9 0x5588330b948f in auto DB::LockedKey::emplace<unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&>(unsigned long&, std::__1::shared_ptr<DB::FileSegmentMetadata>&) build_docker/./src/Interpreters/Cache/Metadata.h:297:58
    #10 0x5588330b948f in DB::FileCache::addFileSegment(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, DB::CachePriorityGuard::Lock const*) build_docker/./src/Interpreters/Cache/FileCache.cpp:788:60
    #11 0x5588330b87a2 in DB::FileCache::splitRangeIntoFileSegments(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, unsigned long, DB::CreateFileSegmentSettings const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:364:41
    #12 0x5588330bd44a in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:663:25
    #13 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #14 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #15 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9
    #16 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16
    #17 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #18 0x55882f2bccae in DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:209:32

Indirect leak of 4464 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x55883313479f in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x55883313479f in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x55883313479f in std::__1::allocator<char>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x55883313479f in std::__1::allocator<char>::allocate_at_least[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:119:17
    #5 0x55883313479f in std::__1::allocation_result<std::__1::allocator_traits<std::__1::allocator<char>>::pointer> std::__1::allocate_at_least[abi:v15000]<std::__1::allocator<char>>(std::__1::allocator<char>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocate_at_least.h:33:20
    #6 0x55883313479f in auto std::__1::__allocate_at_least[abi:v15000]<std::__1::allocator<char>>(std::__1::allocator<char>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocate_at_least.h:42:10
    #7 0x55883313479f in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__init_copy_ctor_external(char const*, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/string:2047:25
    #8 0x55883313479f in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) build_docker/./contrib/llvm-project/libcxx/include/string:2015:9
    #9 0x55883313479f in DB::FileCacheUserInfo::FileCacheUserInfo(DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/UserInfo.h:7:8
    #10 0x55883313479f in DB::KeyMetadata::KeyMetadata(DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata const*, bool) build_docker/./src/Interpreters/Cache/Metadata.cpp:67:7
    #11 0x55883315924b in DB::KeyMetadata* std::__1::construct_at[abi:v15000]<DB::KeyMetadata, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&, DB::KeyMetadata*>(DB::KeyMetadata*, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35:48
    #12 0x55883315924b in void std::__1::allocator_traits<std::__1::allocator<DB::KeyMetadata>>::construct[abi:v15000]<DB::KeyMetadata, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&, void, void>(std::__1::allocator<DB::KeyMetadata>&, DB::KeyMetadata*, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298:9
    #13 0x55883315924b in std::__1::__shared_ptr_emplace<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>>::__shared_ptr_emplace[abi:v15000]<DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&>(std::__1::allocator<DB::KeyMetadata>, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292:9
    #14 0x55883315924b in std::__1::shared_ptr<DB::KeyMetadata> std::__1::allocate_shared[abi:v15000]<DB::KeyMetadata, std::__1::allocator<DB::KeyMetadata>, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&, void>(std::__1::allocator<DB::KeyMetadata> const&, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953:55
    #15 0x55883313a4e4 in std::__1::shared_ptr<DB::KeyMetadata> std::__1::make_shared[abi:v15000]<DB::KeyMetadata, DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*, bool&, void>(DB::FileCacheKey const&, DB::FileCacheUserInfo const&, DB::CacheMetadata*&&, bool&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #16 0x55883313a4e4 in DB::CacheMetadata::getKeyMetadata(DB::FileCacheKey const&, DB::CacheMetadata::KeyNotFoundPolicy, DB::FileCacheUserInfo const&, bool) build_docker/./src/Interpreters/Cache/Metadata.cpp:286:18
    #17 0x55883313934a in DB::CacheMetadata::lockKeyMetadata(DB::FileCacheKey const&, DB::CacheMetadata::KeyNotFoundPolicy, DB::FileCacheUserInfo const&, bool) build_docker/./src/Interpreters/Cache/Metadata.cpp:230:25
    #18 0x5588330bcb94 in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:572:32
    #19 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #20 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #21 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9
    #22 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16

Indirect leak of 4464 byte(s) in 93 object(s) allocated from:
    #0 0x5588141aadbd in operator new(unsigned long) (/usr/bin/clickhouse+0xa49edbd) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #1 0x5588330b9334 in void* std::__1::__libcpp_operator_new[abi:v15000]<unsigned long>(unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:246:10
    #2 0x5588330b9334 in std::__1::__libcpp_allocate[abi:v15000](unsigned long, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/new:272:10
    #3 0x5588330b9334 in std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegmentMetadata, std::__1::allocator<DB::FileSegmentMetadata>>>::allocate[abi:v15000](unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x5588330b9334 in std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegmentMetadata, std::__1::allocator<DB::FileSegmentMetadata>>>>::allocate[abi:v15000](std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegmentMetadata, std::__1::allocator<DB::FileSegmentMetadata>>>&, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x5588330b9334 in std::__1::__allocation_guard<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::FileSegmentMetadata, std::__1::allocator<DB::FileSegmentMetadata>>>>::__allocation_guard[abi:v15000]<std::__1::allocator<DB::FileSegmentMetadata>>(std::__1::allocator<DB::FileSegmentMetadata>, unsigned long) build_docker/./contrib/llvm-project/libcxx/include/__memory/allocation_guard.h:53:18
    #6 0x5588330b9334 in std::__1::shared_ptr<DB::FileSegmentMetadata> std::__1::allocate_shared[abi:v15000]<DB::FileSegmentMetadata, std::__1::allocator<DB::FileSegmentMetadata>, std::__1::shared_ptr<DB::FileSegment>, void>(std::__1::allocator<DB::FileSegmentMetadata> const&, std::__1::shared_ptr<DB::FileSegment>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:952:48
    #7 0x5588330b9334 in std::__1::shared_ptr<DB::FileSegmentMetadata> std::__1::make_shared[abi:v15000]<DB::FileSegmentMetadata, std::__1::shared_ptr<DB::FileSegment>, void>(std::__1::shared_ptr<DB::FileSegment>&&) build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962:12
    #8 0x5588330b9334 in DB::FileCache::addFileSegment(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, DB::CreateFileSegmentSettings const&, DB::CachePriorityGuard::Lock const*) build_docker/./src/Interpreters/Cache/FileCache.cpp:786:34
    #9 0x5588330b87a2 in DB::FileCache::splitRangeIntoFileSegments(DB::LockedKey&, unsigned long, unsigned long, DB::FileSegmentState, unsigned long, DB::CreateFileSegmentSettings const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:364:41
    #10 0x5588330bd44a in DB::FileCache::getOrSet(DB::FileCacheKey const&, unsigned long, unsigned long, unsigned long, DB::CreateFileSegmentSettings const&, unsigned long, DB::FileCacheUserInfo const&) build_docker/./src/Interpreters/Cache/FileCache.cpp:663:25
    #11 0x55882f2c3f7c in DB::CachedOnDiskReadBufferFromFile::nextFileSegmentsBatch() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:138:32
    #12 0x55882f2c456f in DB::CachedOnDiskReadBufferFromFile::initialize() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:154:10
    #13 0x55882f2d3589 in DB::CachedOnDiskReadBufferFromFile::nextImplStep() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:817:9
    #14 0x55882f2d304e in DB::CachedOnDiskReadBufferFromFile::nextImpl() build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:800:16
    #15 0x55881510a7ea in DB::ReadBuffer::next() (/usr/bin/clickhouse+0xb3fe7ea) (BuildId: 9a3499e913307702a7fe6ac4c6fd23d74eebb113)
    #16 0x55882f2bccae in DB::ReadBufferFromRemoteFSGather::readImpl() build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:209:32
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix memory leak in slru cache policy

Closes https://github.com/ClickHouse/ClickHouse/issues/64791.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All NOT Required Checks
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: Integration Tests
- [ ]  Exclude: Stateless tests
- [ ]  Exclude: Stateful tests
- [ ]  Exclude: Performance tests
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with Aarch64
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
---
- [ ]  Do not test
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit c05d4e52d332bdadc887ad568d8313bea55ada03 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/64803/c05d4e52d332bdadc887ad568d8313bea55ada03/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>A Sync</td><td>If it fails, ask a maintainer for help</td><td>⏳ pending</td></tr>
<tbody>
</table>
<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by evillique — APPROVED** [review]

File: src/Interpreters/Cache/SLRUFileCachePriority.h [hunk 1]
```diff
@@ -125,7 +125,10 @@ class SLRUFileCachePriority::SLRUIterator : public IFileCachePriority::Iterator
 
     SLRUFileCachePriority * cache_priority;
     LRUFileCachePriority::LRUIterator lru_iterator;
-    const EntryPtr entry;
+    /// Entry itself is stored by lru_iterator.entry.
+    /// We have it as a separate field to use entry without requiring any lock
+    /// (which will be required if we wanted to get entry from lru_iterator.getEntry()).
+    const std::weak_ptr<Entry> entry;
```
Comment (devcrafter) [inline src/Interpreters/Cache/SLRUFileCachePriority.h:131]: It seems there is no need to store entry `weak_ptr`. We hold strong reference (shared_ptr) on `lru_iterator` which holds strong reference on `entry` (`EntryPtr` via `LRUQueue::iterator`), i.e. it's guaranteed that the `entry` is valid until we explicitly somewhere reset it. So, if we don't do the last, then it'd be sufficient to hold reference on `EntryPtr` i.e. `const EntryPtr &`.

Comment (kssenii) [reply src/Interpreters/Cache/SLRUFileCachePriority.h:131]: weak_ptr seems safer, there is one tricky place where we temporarily remove queue iterator and reassign it: https://github.com/ClickHouse/ClickHouse/blob/c14d1b482f9b3e5647f688dd22e81fd6b100188b/src/Interpreters/Cache/SLRUFileCachePriority.cpp#L374-L403
Even though I tried to make it as safe as possible in terms of not loosing the iterator, I would still like to choose a safer approach with weak_ptr.

**Comment by kssenii** [comment]
> Integration tests (aarch64) [5/6] — fail: 1

`test_checking_s3_blobs_paranoid/test.py::test_query_is_canceled_with_inf_retries` -- broken in master

> Stateless tests

02340_parts_refcnt_mergetree
03023_zeros_generate_random_with_limit_progress_bar

-- look unrelated

**Review by devcrafter — APPROVED** [review]
