### PR TITLE
Substitute UDFs in `CREATE` queries

### LINKED ISSUE #41327: Incorrect metadata initialization order
When using a materialized column, the expression of which will be a user-defined function, within which the dictionary will be called, the server cannot up due to an incorrect initialization order. This bug reproduces on 22.1.3, 22.3.11, 22.8 (most likely other versions as well)

How to reproduce:
```
CREATE VIEW default.view AS SELECT toUInt64(1) id, toUInt32(1) value;

CREATE DICTIONARY default.dict (
  id UInt64,
  value UInt32
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(
  host 'localhost'
  port 9000
  password ''
  user 'default'
  db 'default'
  table 'view'
))
LAYOUT(FLAT())
LIFETIME(300);

CREATE FUNCTION func AS (x) -> dictGet('default.dict', 'value',toUInt64(1));

CREATE TABLE default.table (
  col1 UInt32,
  col2 MATERIALIZED func(1)
) ENGINE = MergeTree() ORDER BY tuple();

+ restart
```

Error:
```
<Error> Application: DB::Exception: Dictionary (`default.dict`) not found: While processing _CAST(dictGet('default.dict', 'value', toUInt64(1)) AS col2_tmp_alter4123183136832856956, 'UInt32') AS col2: default expression and column type are incompatible.: Cannot attach table `default`.`table` from metadata file /var/lib/clickhouse/store/f63/f634d710-a55c-4190-822e-ba08bc224842/table.sql from query ATTACH TABLE default.table UUID '18b847db-1ed2-4846-8c75-a3802a544f3c' (`col1` UInt32, `col2` UInt32 MATERIALIZED func(1)) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 8192
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Substitute UDFs in `CREATE` query to avoid failures during loading at the startup. Additionally, UDFs can now be used as `DEFAULT` expressions for columns.

Fixes https://github.com/ClickHouse/ClickHouse/issues/41327

I don't think integration tests with restarts are necessary because `DESCRIBE TABLE` queries show that the substitution is done.
Also, there are multiple places where I could've done the substitution so feel free to comment on that if you think it should be moved.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/InterpreterCreateQuery.cpp [hunk 1]
```diff
@@ -520,6 +523,13 @@ ColumnsDescription InterpreterCreateQuery::getColumnsDescription(
         /// add column to postprocessing if there is a default_expression specified
         if (col_decl.default_expression)
         {
+            // substitute possible UDFs with their definitions
+            if (!UserDefinedSQLFunctionFactory::instance().empty())
```
Comment (kitaisreal) [inline src/Interpreters/InterpreterCreateQuery.cpp:527]: This solution is good, but we have our AST implementation problem. If you check ASTColumnDeclaration you can see that there are a bunch of members (`default_expression`), and there are also children array and they are not synchronized. If we only change member, children array will not be updated and it can become a big issue, with very hard to debug bugs.
Last time when I tried to do inline UDF in table definition, I tried to replace `ORDER BY`, `PARTITION BY` definitions in table, then there were a bunch of crashes, because `ASTStorage` does not keep shared members, but just raw pointers.
In QueryTree, there are no public members, only public getters, and setters that operate on children array. The only solution without redesigning our AST children, to make it work, it seems to just write visitor that is aware of our AST implementation problems, and in this visitor we need special handling for `ASTColumnDeclaration`, `ASTStorage`.

**Review by kitaisreal — CHANGES_REQUESTED** [review]

File: src/Interpreters/InterpreterCreateQuery.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Interpreters/InterpreterCreateQuery.cpp:527]: Yes, I noticed that issue, not in form of crash but with inconsistencies. If you modify the create AST with the visitor, the tree will be correct but the `default_expression` will contain the old definition which at later steps will be used making the visitor changes obsolete. Really annoying to debug.

I'll try then with modifying the visitor 👍

Comment (antonio2368) [reply src/Interpreters/InterpreterCreateQuery.cpp]: Would this be what you had in mind?
I can expand with extra checks, wanted to be sure about the idea first.

Also, does it make sense for me to try to expand with `ORDER BY`, `PARTITION BY` inlining? Because the same problem should occur as in the linked issues if UDFs are used there.

**Review by kitaisreal — APPROVED** [review]

**Comment by m1khal3v** [comment]
Is this closes #43005 ?

File: src/Functions/UserDefined/UserDefinedSQLFunctionVisitor.cpp [hunk 2]
```diff
@@ -19,24 +22,96 @@ namespace ErrorCodes
...
-    auto * function = ast->as<ASTFunction>();
-    if (!function)
+    const auto visit_child_with_shared_ptr = [&](ASTPtr & child)
+    {
+        if (!child)
+            return;
+
+        auto * old_value = child.get();
+        visit(child);
+        ast->setOrReplace(old_value, child);
```
Comment (KochetovNicolai) [inline src/Functions/UserDefined/UserDefinedSQLFunctionVisitor.cpp:34]: I don't like that
* We use dynamic_cast in `setOrReplace` - it is not needed. Maybe write a simple for-loop here?
* We iterate all children every time unconditionally. Probably check `old_value != child.get()`?

File: src/Functions/UserDefined/UserDefinedSQLFunctionVisitor.cpp [hunk 3]
```diff
@@ -19,24 +22,96 @@ namespace ErrorCodes
     extern const int UNSUPPORTED_METHOD;
 }
 
-void UserDefinedSQLFunctionMatcher::visit(ASTPtr & ast, Data &)
+void UserDefinedSQLFunctionVisitor::visit(ASTPtr & ast)
 {
-    auto * function = ast->as<ASTFunction>();
-    if (!function)
+    const auto visit_child_with_shared_ptr = [&](ASTPtr & child)
```
Comment (KochetovNicolai) [inline src/Functions/UserDefined/UserDefinedSQLFunctionVisitor.cpp:27]: Would be good to have a comment why we are working with shared_ptr.

Comment (antonio2368) [reply src/Functions/UserDefined/UserDefinedSQLFunctionVisitor.cpp:27]: could you help me with this one
I'm not sure how it affects the logic here, in some cases AST nodes will have an extra shared_ptr to their children.
