### PR TITLE
Fix flaky 03261_minmax_indices_by_default

### LINKED ISSUE #78665: Flaky stateless test `03261_minmax_indices_by_default`
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=74945&sha=987be5d530d5dd73ef2ecc126647bc7c63734057&name_0=PR&name_1=Stateless+tests+%28tsan%2C+1%2F3%29

```2025-04-04 00:37:13 Reason: result differs with reference:  
2025-04-04 00:37:13 --- /repo/tests/queries/0_stateless/03261_minmax_indices_by_default.reference	2025-04-04 00:29:40.717954684 +0800
2025-04-04 00:37:13 +++ /repo/tests/queries/0_stateless/03261_minmax_indices_by_default.stdout	2025-04-04 00:37:13.583759327 +0800
2025-04-04 00:37:13 @@ -1,41 +1,41 @@
2025-04-04 00:37:13  Check skipping indices after table creation
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  Add numeric column
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  auto_minmax_index_n	minmax	n	0
2025-04-04 00:37:13  After materialize
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 -auto_minmax_index_n	minmax	n	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13 +auto_minmax_index_n	minmax	n	35
2025-04-04 00:37:13  Drop numeric column
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  Add string column
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  auto_minmax_index_s	minmax	s	0
2025-04-04 00:37:13  Add another string column
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  auto_minmax_index_s	minmax	s	0
2025-04-04 00:37:13  auto_minmax_index_t	minmax	t	0
2025-04-04 00:37:13  Drop string column t
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  auto_minmax_index_s	minmax	s	0
2025-04-04 00:37:13  Rename column s to t
2025-04-04 00:37:13 -x_idx	minmax	x	34
2025-04-04 00:37:13 -auto_minmax_index_key	minmax	key	34
2025-04-04 00:37:13 -auto_minmax_index_y	minmax	y	34
2025-04-04 00:37:13 +x_idx	minmax	x	43
2025-04-04 00:37:13 +auto_minmax_index_key	minmax	key	43
2025-04-04 00:37:13 +auto_minmax_index_y	minmax	y	43
2025-04-04 00:37:13  auto_minmax_index_t	minmax	t	0
2025-04-04 00:37:13  tbl5 with add_minmax_index_for_numeric_columns and add_minmax_index_for_string_columns disabled
2025-04-04 00:37:13  x_idx	minmax	x	0
2025-04-04 00:37:13 
2025-04-04 00:37:13 
2025-04-04 00:37:13 Settings used in the test: --max_insert_threads 1 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 16303414 --distributed_aggregation_memory_efficient 1 --fsync_metadata 0 --output_format_parallel_formatting 0 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 4092299 --max_read_buffer_size 604318 --prefer_localhost_replica 0 --max_block_size 40883 --max_joined_block_size_rows 46372 --max_threads 1 --optimize_append_index 0 --optimize_if_chain_to_multiif 0 --optimize_if_transform_strings_to_enum 1 --optimize_read_in_order 1 --optimize_or_like_chain 1 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 0 --read_in_order_two_level_merge_threshold 67 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 18106405 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 1 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 10 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 64Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 30 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 2816028193 --min_compress_block_size 2705943 --max_compress_block_size 615235 --merge_tree_compact_parts_min_granules_to_multibuffer_read 23 --optimize_sorting_by_input_stream_properties 0 --http_response_buffer_size 9353916 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 0 --min_count_to_compile_sort_description 0 --session_timezone America/Hermosillo --use_page_cache_for_disks_without_file_cache True --page_cache_inject_eviction True --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.15 --prefer_external_sort_block_bytes 100000000 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 100000000 --min_external_table_block_size_bytes 0 --max_parsing_threads 0 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 1 --query_plan_join_swap_table auto --enable_vertical_final 0 --optimize_extract_common_expressions 0 --use_query_condition_cache 0 --max_bytes_before_external_sort 10737418240 --max_bytes_before_external_group_by 0 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0
2025-04-04 00:37:13 
2025-04-04 00:37:13 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 1 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 10737418240 --index_granularity_bytes 24122231 --merge_max_block_size 183 --index_granularity 2 --min_bytes_for_wide_part 727749892 --marks_compress_block_size 9456 --primary_key_compress_block_size 68804 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 475075322 --compact_parts_max_granules_to_buffer 212 --compact_parts_merge_max_bytes_to_prefetch_part 9036201 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 48 --old_parts_lifetime 301 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 1
2025-04-04 00:37:13 
2025-04-04 00:37:13 Database: test_h3yonyla
```

### PR DESCRIPTION
**Pull request by korowa**
Closes #78665 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Run the test with explicit index_granularity settings to prevent index size fluctuations due to randomized ones.

### CODE REVIEW

File: tests/queries/0_stateless/03261_minmax_indices_by_default.sql [hunk 1]
```diff
@@ -11,11 +11,14 @@ CREATE TABLE tbl1
     key Int,
     x Int,
     y Int,
-    INDEX x_idx x TYPE minmax
+    INDEX x_idx x TYPE minmax GRANULARITY 1
```
Comment (azat) [inline tests/queries/0_stateless/03261_minmax_indices_by_default.sql:14]: Am I right that this is not required to fix flakiness? (It is OK to keep it, just curiosity)

**Review by azat — APPROVED** [review]

File: tests/queries/0_stateless/03261_minmax_indices_by_default.sql (hunk 1 above)
Comment (korowa) [reply tests/queries/0_stateless/03261_minmax_indices_by_default.sql:14]: Yes, that's not required, I've set it "just in case"
