### PR TITLE
Remind properly if use clickhouse-client --file without preceeding --external 

### LINKED ISSUE #34747: Confusing message on a cli client flag misuse.
**Describe the issue**
It's hard to understand what I did wrong or how can I fix the problem.

I rechecked my typing 5 times, it's fine.
```
# clickhouse-client --file -
Code: 552. DB::Exception: Unrecognized option '--file'. Maybe you meant ['--file','--time']. (UNRECOGNIZED_ARGUMENTS)
```

This is a minimal flag set to get into the problem. I tried multiple flag sets, with `--format`, `--name`, reading from stdin or file, used = or not. It's all the same.

**Expected behavior**
Some short description how it was expected to be used or at least the message that do not confuse you more.

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remind properly if use clickhouse-client --file without preceeding --external. Close https://github.com/ClickHouse/ClickHouse/issues/34747

### CODE REVIEW

**Comment by kitaisreal** [comment]
@taiyang-li need to fix fast test.

**Comment by taiyang-li** [comment]
I will fix them soon.

**Comment by taiyang-li** [comment]
clickhouse-client will remind like this: 
```
$ ./build_gcc/programs/clickhouse client   --file  -  
Code: 36. DB::Exception: Parameter must be in external group, try add --external before --file. (BAD_ARGUMENTS)
```

**Comment by taiyang-li** [comment]
Failed integration tests irrelavent with clickhouse-client

**Comment by taiyang-li** [comment]
@kitaisreal  All checks have passed.

File: programs/client/Client.cpp [hunk 1]
```diff
@@ -1234,6 +1236,160 @@ void Client::processConfig()
     client_info.quota_key = config().getString("quota_key", "");
 }
 
+void Client::readArguments(
```
Comment (kitaisreal) [inline programs/client/Client.cpp:1239]: @taiyang-li could you please explain, why we extracted this method as ClientBase abstraction ?

Comment (kitaisreal) [inline programs/client/Client.cpp:1239]: @taiyang-li could you please explain, why we extracted this method as ClientBase abstraction ?

Comment (taiyang-li) [reply programs/client/Client.cpp:1239]: @kitaisreal Only in clickhouse-client we need to distinguish whether an option is in external group or not, because `options_description.external_description` is not empty. But in clickhouse-local, we don't have to consider it. So implmentation for clickhouse-client and clickhouse-local seperately is necessary.

Comment (taiyang-li) [reply programs/client/Client.cpp:1239]: Same reason as above.

Comment (taiyang-li) [reply programs/client/Client.cpp:1239]: @kitaisreal do you think it is ok ?

**Comment by taiyang-li** [comment]
@kitaisreal  Do you think this pr could be merged? Pls let me know if there are any other issues

**Comment by taiyang-li** [comment]
@kitaisreal  Waiting for you reply, thanks!

File: programs/client/Client.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply programs/client/Client.cpp:1036]: Yes, totally ok.

**Review by alexey-milovidov — APPROVED** [review]
The code LGTM.
