### PR TITLE
Fix formatting constant JSON literals

### LINKED ISSUE #74418: JSON Strings not properly escaped when sent to MySQL
**Describe the bug**

**How to reproduce**
In MySQL run:
```sql
 CREATE TABLE test.t0(c0 VARCHAR(32));
```
Then in ClickHouse run:
```sql
CREATE TABLE t0 (c0 String) ENGINE = MySQL('<host:port>', 'test', 't0', '<credentials>');
SELECT 1 FROM t0 WHERE c0 = '{"c0":1}'::JSON;
/*
DB::Exception: mysqlxx::BadQuery: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"c0": 1}' at line 1 while executing query: 'SELECT `c0` FROM `test`.`t0` WHERE `c0` = {"c0": 1}' (127.0.0.1:3306). (POCO_EXCEPTION)
*/
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix formatting constant JSON literals. Previously it could lead to syntax errors during sending the query to another server.

Closes https://github.com/ClickHouse/ClickHouse/issues/74418

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, BuzzHouse, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 7c296d582ebc08f3ce8d2cf233bb0b4243195e65 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74533/7c296d582ebc08f3ce8d2cf233bb0b4243195e65/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/74533/7c296d582ebc08f3ce8d2cf233bb0b4243195e65/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Common/FieldVisitorToJSONElement.cpp [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+String FieldVisitorToJSONElement::operator() (const AggregateFunctionStateData & x) const { return formatAsString(x.data); }
+String FieldVisitorToJSONElement::operator() (const bool & x) const { return x ? "true" : "false"; }
+String FieldVisitorToJSONElement::operator() (const CustomType & x) const { return formatString(x.toString()); }
+
+String FieldVisitorToJSONElement::operator() (const Array & x) const
+{
+    WriteBufferFromOwnString wb;
+
+    wb << '[';
+    for (Array::const_iterator it = x.begin(); it != x.end(); ++it)
```
Comment (antonio2368) [inline src/Common/FieldVisitorToJSONElement.cpp:63]:
```suggestion
    for (auto it = x.begin(); it != x.end(); ++it)
```
why not this? if you want const you can use `cbegin` and `cend`

File: src/Common/FieldVisitorToJSONElement.cpp [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+
+    return wb.str();
+}
+
+String FieldVisitorToJSONElement::operator() (const Tuple & x) const
+{
+    WriteBufferFromOwnString wb;
+
+    wb << '[';
+    for (Array::const_iterator it = x.begin(); it != x.end(); ++it)
```
Comment (antonio2368) [inline src/Common/FieldVisitorToJSONElement.cpp:79]: same comment as above?

**Review by antonio2368 — APPROVED** [review]

File: src/Common/FieldVisitorToJSONElement.cpp (hunk 1 above)
Comment (Avogar) [reply src/Common/FieldVisitorToJSONElement.cpp:63]: I just copied the code from the `FieldVisitorToString` with slight adjusments. So there was no reason, let's change

File: src/Common/FieldVisitorToJSONElement.cpp (hunk 2 above)
Comment (Avogar) [reply src/Common/FieldVisitorToJSONElement.cpp:79]:
```suggestion
    for (auto it = x.begin(); it != x.end(); ++it)
```
