### PR TITLE
Fix merging null values in AggregateFunctionSumMap

### LINKED ISSUE #43022: Logical error: Cannot compare Nulls in SumMap function
https://s3.amazonaws.com/clickhouse-test-reports/41874/f1b172d43be420349b2f40967fdd8dc67ca8d73b/fuzzer_astfuzzerubsan//report.html

Query: ([fiddle](https://fiddle.clickhouse.com/219c3c58-d779-493f-84fb-58d22fd14aa1))
``` sql
SELECT
    maxMap([toInt32(number % 1048577), 
    (number % 65537) + -1], 
    [number, NULL]) AS m 
FROM 
    numbers(2147483646, 65537)
GROUP BY
    [CAST(toInt32(number) - 0., 'Decimal(10, 2)')] WITH ROLLUP
```

```
2022.11.08 05:11:35.460456 [ 402 ] {380fcb66-b67b-4ba7-bc0a-d4f2573b20ce} <Fatal> : Logical error: 'Cannot compare Nulls'.
2022.11.08 05:12:01.153864 [ 426 ] {} <Fatal> BaseDaemon: ########################################
2022.11.08 05:12:01.153914 [ 426 ] {} <Fatal> BaseDaemon: (version 22.11.1.1, build id: 97CDDB3169C4EA35FE9773D533470AA07FBA0623) (from thread 402) (query_id: 380fcb66-b67b-4ba7-bc0a-d4f2573b20ce) (query: SELECT maxMap([toInt32(number % 1048577), (number % 65537) + -1], [number, NULL]) AS m FROM numbers(2147483646, 65537) GROUP BY [CAST(toInt32(number) - 0., 'Decimal(10, 2)')] WITH ROLLUP) Received signal Aborted (6)
2022.11.08 05:12:01.153938 [ 426 ] {} <Fatal> BaseDaemon: 
2022.11.08 05:12:01.153985 [ 426 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fd044d8c00b 0x7fd044d6b859 0x204dc203 0x204dc48f 0x2433be31 0x2442ee9f 0x24431d24 0x2b19a19d 0x2b0e275e 0x2b0fe558 0x2b09d746 0x2db8f30a 0x2db902a8 0x2d542b9f 0x2d57187f 0x2d56131b 0x2d562991 0x205c05ba 0x205c40a4 0x7fd044f43609 0x7fd044e68133
2022.11.08 05:12:01.154022 [ 426 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7fd044d8c00b in ?
2022.11.08 05:12:01.154044 [ 426 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7fd044d6b859 in ?
2022.11.08 05:12:01.181718 [ 426 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:47: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x204dc203 in /workspace/clickhouse
2022.11.08 05:12:01.199678 [ 426 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:70: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0x204dc48f in /workspace/clickhouse
2022.11.08 05:12:01.440254 [ 426 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/AggregateFunctions/AggregateFunctionSumMap.h:0: DB::FieldVisitorMax::operator()(DB::Null&) const @ 0x2433be31 in /workspace/clickhouse
2022.11.08 05:12:01.697793 [ 426 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../src/Common/FieldVisitors.h:0: auto DB::applyVisitor<DB::FieldVisitorMax, DB::Field&>(DB::FieldVisitorMax&&, DB::Field&)
2022.11.08 05:12:01.697843 [ 426 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/AggregateFunctions/AggregateFunctionSumMap.h:278: DB::AggregateFunctionMapBase<long, DB::AggregateFunctionMaxMap<long, false>, DB::FieldVisitorMax, true, false, false>::merge(char*, char const*, DB::Arena*) const @ 0x2442ee9f in /workspace/clickhouse
2022.11.08 05:12:01.955437 [ 426 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/AggregateFunctions/IAggregateFunction.h:0: DB::IAggregateFunctionHelper<DB::AggregateFunctionMaxMap<long, false>>::mergeBatch(unsigned long, unsigned long, char**, unsigned long, char* const*, DB::Arena*) const @ 0x24431d24 in /workspace/clickhouse
2022.11.08 05:12:02.068764 [ 426 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Interpreters/Aggregator.cpp:2752: void DB::Aggregator::mergeStreamsImplCase<false, DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const @ 0x2b19a19d in /workspace/clickhouse
2022.11.08 05:12:02.181699 [ 426 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Interpreters/Aggregator.cpp:0: void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const @ 0x2b0e275e in /workspace/clickhouse
2022.11.08 05:12:02.356723 [ 426 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Interpreters/Aggregator.cpp:2776: void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Block, DB::Arena*, DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, StringRefHash64, HashTableNoState>, StringRefHash64, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, DB::Arena*) const @ 0x2b0fe558 in /workspace/clickhouse
2022.11.08 05:12:02.531370 [ 426 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Interpreters/Aggregator.cpp:3084: DB::Aggregator::mergeBlocks(std::__1::list<DB::Block, std::__1::allocator<DB::Block>>&, bool) @ 0x2b09d746 in /workspace/clickhouse
2022.11.08 05:12:02.548765 [ 426 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Processors/Transforms/RollupTransform.cpp:0: DB::GroupByModifierTransform::merge(std::__1::vector<DB::Chunk, std::__1::allocator<DB::Chunk>>&&, bool, bool) @ 0x2db8f30a in /workspace/clickhouse
2022.11.08 05:12:02.566106 [ 426 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Processors/Transforms/RollupTransform.cpp:107: DB::RollupTransform::generate() @ 0x2db902a8 in /workspace/clickhouse
2022.11.08 05:12:02.576100 [ 426 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Processors/IAccumulatingTransform.cpp:102: DB::IAccumulatingTransform::work() @ 0x2d542b9f in /workspace/clickhouse
2022.11.08 05:12:02.581411 [ 426 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2022.11.08 05:12:02.581435 [ 426 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2d57187f in /workspace/clickhouse
2022.11.08 05:12:02.595352 [ 426 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2d56131b in /workspace/clickhouse
2022.11.08 05:12:02.610427 [ 426 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: operator()
2022.11.08 05:12:02.610461 [ 426 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15003]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&)
2022.11.08 05:12:02.610482 [ 426 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&)
2022.11.08 05:12:02.610499 [ 426 ] {} <Fatal> BaseDaemon: 19.4. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15003]()
2022.11.08 05:12:02.610513 [ 426 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../contrib/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2d562991 in /workspace/clickhouse
2022.11.08 05:12:02.619064 [ 426 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
2022.11.08 05:12:02.619083 [ 426 ] {} <Fatal> BaseDaemon: 20.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
2022.11.08 05:12:02.619096 [ 426 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x205c05ba in /workspace/clickhouse
2022.11.08 05:12:02.629342 [ 426 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15003]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x205c40a4 in /workspace/clickhouse
2022.11.08 05:12:02.629362 [ 426 ] {} <Fatal> BaseDaemon: 22. ? @ 0x7fd044f43609 in ?
2022.11.08 05:12:02.629376 [ 426 ] {} <Fatal> BaseDaemon: 23. clone @ 0x7fd044e68133 in ?
2022.11.08 05:12:02.913813 [ 426 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: 316592C1B1EA7B19C5548FDF51841480)
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix logical error in `sumMap/minMap/maxMap` functions executing `TOTALS/ROLLUP/CUBE` on `NULL` values. Close https://github.com/ClickHouse/ClickHouse/issues/43022

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Common/FieldVisitorSum.cpp [hunk 1]
```diff
@@ -21,7 +21,12 @@ bool FieldVisitorSum::operator() (UInt64 & x) const
 
 bool FieldVisitorSum::operator() (Float64 & x) const { x += rhs.get<Float64>(); return x != 0; }
 
-bool FieldVisitorSum::operator() (Null &) const { throw Exception("Cannot sum Nulls", ErrorCodes::LOGICAL_ERROR); }
+bool FieldVisitorSum::operator() (Null &) const
+{
+    /// Do not add anything
+    return rhs != 0;
```
Comment (vdimir) [inline src/Common/FieldVisitorSum.cpp:27]:
```suggestion
    return false;
```

**Review by Avogar — APPROVED** [review]
