### PR TITLE
Fix assertion in CacheMetadata::doCleanup

### LINKED ISSUE #49386: DB::CacheMetadata::doCleanup() Logical error: 'false'.
Stress test failure: https://s3.amazonaws.com/clickhouse-test-reports/49365/0f6a4b973e0029f6c400385891077378aa2f0787/stress_test__tsan_.html

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a race in CacheMetadata::doCleanup. Closes https://github.com/ClickHouse/ClickHouse/issues/49386

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
This is an automated comment for commit d4ea3ea045a250c86859ebfcff953b13822f0a23 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49914/d4ea3ea045a250c86859ebfcff953b13822f0a23/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by kssenii** [comment]
> Unit tests (asan) — PASSED record not found. 

broken in master

> Stateless tests (release, DatabaseReplicated) [4/4] — fail: 1

00992_system_parts_race_condition_zookeeper_long - flaky in master

File: src/Interpreters/Cache/Metadata.cpp [hunk 1]
```diff
@@ -272,9 +271,17 @@ void CacheMetadata::doCleanup()
         }
         catch (...)
         {
-            tryLogCurrentException(__PRETTY_FUNCTION__);
+            LOG_ERROR(log, "Error while removing key {}: {}", cleanup_key, getCurrentExceptionMessage(false));
             chassert(false);
         }
+
+        /// Remove key from metadata AFTER deleting key directory, because otherwise key lock is
```
Comment (devcrafter) [inline src/Interpreters/Cache/Metadata.cpp:278]: I didn't understand how moving `erase(it)` help here. The key lock is held until the end of the loop iteration. So, it looks the comment is not correct. Did I miss something?

File: src/Interpreters/Cache/Metadata.cpp [hunk 2]
```diff
@@ -1,6 +1,7 @@
 #include <Interpreters/Cache/Metadata.h>
 #include <Interpreters/Cache/FileCache.h>
 #include <Interpreters/Cache/FileSegment.h>
+#include "Common/Exception.h"
```
[the remark this answers is not in the document]
Comment (kssenii) [reply src/Interpreters/Cache/Metadata.cpp]: thx, my IDE adds this on its own... removed this include completely

File: src/Interpreters/Cache/Metadata.cpp (hunk 1 above)
Comment (kssenii) [reply src/Interpreters/Cache/Metadata.cpp:277]: > The key lock is held until the end of the loop iteration

it is, but `KeyGuard` object lies inside `metadata[key]`, so if we do `erase(it)` the lock is deleted as well (so the last shared pointer to this key_metadata is hold by LockedKey which holds the lock in this iteration), which means that the thread which will come to cache to take the same key - it will create a new key metadata and a new KeyGuard will be used.

Comment (devcrafter) [reply src/Interpreters/Cache/Metadata.cpp:277]: AFAIS, `erase(it)` removes the `KeyMetadataPtr` from cache metadata, but the iterator is still holding the corresponding shared pointer on `KeyMetadata`, so the `KeyMetadata` destruction should happen at the end of the loop. 
BTW, It'd be better to make it more explicit, by assigning `KeyMetadataPtr` in `it->second` to a local variable

File: src/Interpreters/Cache/Metadata.cpp [hunk 3]
```diff
@@ -260,19 +260,37 @@ void CacheMetadata::doCleanup()
...
+        try
+        {
             if (fs::exists(key_prefix_directory) && fs::is_empty(key_prefix_directory))
                 fs::remove_all(key_prefix_directory);
         }
+        catch (const fs::filesystem_error & e)
+        {
+            /// Key prefix directory can become non-empty just now, it is expected.
+            if (e.code() == std::errc::directory_not_empty)
+                return;
```
Comment (devcrafter) [inline src/Interpreters/Cache/Metadata.cpp:287]:
```suggestion
                continue;
```

Comment (devcrafter) [reply src/Interpreters/Cache/Metadata.cpp:287]: It seems there is no need to exit from the function at this point. We can proceed to handle others keys in the cleanup queue

**Review by devcrafter — APPROVED** [review]
LGTM with comment

**Comment by kssenii** [comment]
> Unit tests (asan) — PASSED record not found.

broken on master:
```
==13==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f00000cca10 at pc 0x555d81667d61 bp 0x7efec3c8edd0 sp 0x7efec3c8edc8
READ of size 8 at 0x7f00000cca10 thread T3999 (ThreadPool)
    #0 0x555d81667d60 in IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0::operator()() const build_docker/./src/IO/Resource/tests/gtest_resource_manager_hierarchical.cpp:93:17
    #1 0x555d81667d60 in decltype(std::declval<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&>()()) std::__1::__invoke[abi:v15000]<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&>(IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #2 0x555d81667d60 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&, std::__1::tuple<>&>(IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #3 0x555d81667d60 in decltype(auto) std::__1::apply[abi:v15000]<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&, std::__1::tuple<>&>(IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #4 0x555d81667d60 in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0>(IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:228:13
    #5 0x555d81667d60 in decltype(std::declval<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0>(IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&&)::'lambda'()&>(IOResourceDynamicResourceManager_Fairness_Test::TestBody()::$_0&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
```
