### PR TITLE
Show schema for parameterized_view

### LINKED ISSUE #88875: No information about parameterized view columns is returned.
### Company or project name

_No response_

### Describe what's wrong

Can't get the the information about parameterized view's columns.

Here is the example: https://fiddle.clickhouse.com/2b675b3f-ce3a-48c0-b186-a5fbff976d49

Expected return is

```
id	Int16	NO		\N		\N	Test comment	
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=Memory;

INSERT INTO users VALUES (1231, 'John', 33);
INSERT INTO users VALUES (6666, 'Ksenia', 48);
INSERT INTO users VALUES (8888, 'Alice', 50);

CREATE VIEW v_users (id Int16 COMMENT 'Test comment') AS SELECT id FROM "users" WHERE age > {age:Int16};

SHOW FULL COLUMNS IN v_users;

### Expected behavior

```
id	Int16	NO		\N		\N	Test comment	
```

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GSokol**
Show the schema of a parameterized view when it's explicitly specified.

### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
If the schema of parameterized view is specified explicitly it is shown. Close https://github.com/ClickHouse/ClickHouse/issues/88875, https://github.com/ClickHouse/ClickHouse/issues/81385

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.576`

### CODE REVIEW

**Comment by GSokol** [comment]
@SmitaRKulkarni, could you please take a look?

File: src/Storages/StorageView.cpp [hunk 1]
```diff
@@ -128,7 +128,8 @@ StorageView::StorageView(
     if (!is_parameterized_view_)
     {
         /// If CREATE query is to create parameterized view, then we dont want to set columns
-        if (!query.isParameterizedView())
+        /// if thed don't specified explicitly.
```
Comment (robinbetts-oxecon) [inline src/Storages/StorageView.cpp]: /// if they aren't specified explicitly.

**Comment by GSokol** [comment]
@SmitaRKulkarni, I have concerns about the "proper" behavior: right now, if the schema explicitly defined and really returned do not matched -- nothing happens:

```
CREATE VIEW v_my_number
(
    `n` UInt64,
    `v` String
)
AS SELECT number AS n
FROM numbers({upper_bound:UInt64});

SELECT *
FROM v_my_number(upper_bound = 4);

   ┌─n─┐
1. │ 0 │
2. │ 1 │
3. │ 2 │
4. │ 3 │
   └───┘
```

Should I keep it, or raise an error instead. Raising an error seams to be more "proper" and "consistent", but:
1. It is breaking change, so, maybe someone is already using parameterized views with explicit schema, that doesn't match and happy with it.
2. It could require extra operations on the query executions, slowing them down (a bit, but anyway).

What do you think, which approach is batter?

File: src/Storages/StorageView.cpp (hunk 1 above)
Comment (GSokol) [reply src/Storages/StorageView.cpp]: Done

**Comment by SmitaRKulkarni** [comment]
@GSokol : 

>  I have concerns about the "proper" behavior: right now, if the schema explicitly defined and really returned do not matched -- nothing happens:

Good point. This should be fixed.  Could you please update to raise an error in such case.

> It could require extra operations on the query executions, slowing them down (a bit, but anyway).
- Few extra operations should not be a concern

**Comment by GSokol** [comment]
Got fever. So, I'm not disappearing,just need couple of days to recover. Next week I push the updates and test for the case.

**Comment by GSokol** [comment]
@SmitaRKulkarni, throwing an error on actual and defined schema mismatch.

**Review by SmitaRKulkarni — COMMENTED** [review]
LGTM , lets wait for CI checks

**Comment by GSokol** [comment]
> LGTM , lets wait for CI checks

@SmitaRKulkarni, some unrelated tests failed.

**Comment by SmitaRKulkarni** [comment]
Unrelated fails:

[Integration tests (amd_binary, 4/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90220&sha=a20033fb2c521b5c022f699d9449cb13ba352b2f&name_0=PR&name_1=Integration+tests+%28amd_binary%2C+4%2F5%29) - test_storage_s3_queue & test_userspace_page_cache
[Integration tests (arm_binary, distributed plan, 3/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90220&sha=a20033fb2c521b5c022f699d9449cb13ba352b2f&name_0=PR&name_1=Integration+tests+%28arm_binary%2C+distributed+plan%2C+3%2F4%29) - test_backup_restore_on_cluster
[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90220&sha=a20033fb2c521b5c022f699d9449cb13ba352b2f&name_0=PR&name_1=BuzzHouse+%28amd_debug%29) - 'Logical error: 'Inconsistent AST formatting: the query: (STID: 1941-1bfa)'

**Review by SmitaRKulkarni — APPROVED** [review]
