### PR TITLE
Read iceberg data files by field ids

### LINKED ISSUE #83065: Implement reading from Iceberg data files using `field-id`
### Company or project name

_No response_

### Describe the unexpected behaviour

When ClickHouse read data from Iceberg table, it properly applies schema evolution, but expect columns names to be written in parquet files. Almost all known Iceberg writers implementations actually write proper column names in data files, however it's not required according to the [spec](https://iceberg.apache.org/spec/#column-projection) it's not required. Proper read from Iceberg data files must happen by field-id's as well, which also present in [parquet files](https://github.com/apache/parquet-format/blob/master/README.md#schema). 

ClickHouse reading code infrastructure tightly relies on column names, however after this PR: https://github.com/ClickHouse/ClickHouse/pull/82949 it's possible to provide custom metadata for parquet format: https://github.com/ClickHouse/ClickHouse/pull/82949/files#diff-4331753365131b0ff5d3cbe0dc2fb94addff9c68286f6725abb1696783f7a5f1R23-R67. Now we need to use this struct to read columns from Iceberg by `field-id`: https://github.com/ClickHouse/clickhouse-private/blob/master/src/Storages/ObjectStorage/StorageObjectStorageSource.cpp#L493-L504

### How to reproduce

Complex, but I have table for it.

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- New Feature

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Read iceberg data files by field ids. This closes https://github.com/ClickHouse/ClickHouse/issues/83065

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/Formats/Impl/ArrowFieldIndexUtil.h [hunk 1]
```diff
@@ -90,6 +91,8 @@ class ArrowFieldIndexUtil
         {
             const auto & named_col = header.getByPosition(i);
             std::string col_name = named_col.name;
+            if (clickhouse_to_parquet_names)
+                col_name = clickhouse_to_parquet_names->at(col_name);
```
Comment (serxa) [inline src/Processors/Formats/Impl/ArrowFieldIndexUtil.h]: What if `at()` throws? Is it okay here?

File: src/Processors/QueryPlan/ReadFromObjectStorageStep.cpp [hunk 2]
```diff
@@ -79,6 +79,7 @@ void ReadFromObjectStorageStep::initializePipeline(QueryPipelineBuilder & pipeli
     }
 
     auto parser_group = std::make_shared<FormatParserGroup>(context->getSettingsRef(), num_streams, filter_actions_dag, context);
+    parser_group->opaque = opaque;
```
[the remark this answers is not in the document]
Comment (serxa) [reply src/Processors/QueryPlan/ReadFromObjectStorageStep.cpp]: Seems like a real issue.

File: src/Storages/ObjectStorage/DataLakes/IDataLakeMetadata.h [hunk 3]
```diff
@@ -58,6 +58,8 @@ class IDataLakeMetadata : boost::noncopyable
     virtual std::optional<size_t> totalRows(ContextPtr) const { return {}; }
     virtual std::optional<size_t> totalBytes(ContextPtr) const { return {}; }
 
+    virtual std::shared_ptr<void> getOpaque() const { return nullptr; }
```
Comment (serxa) [inline src/Storages/ObjectStorage/DataLakes/IDataLakeMetadata.h]: It would be good to have at least a comment about the purpose of this thing in the interface. TBH, is it really necessary to be so abstract? Maybe just put here what you needed in the first place, and return nothing if there is no such thing?

**Review by serxa — APPROVED** [review]
