### PR TITLE
Fix non joined rows from nullable column

### LINKED ISSUE #27691: Logical error: 'ColumnUnique can't contain null values.'
#27685

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):

- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix non joined rows from nullable column. Close #27691

### CODE REVIEW

File: src/Interpreters/join_common.cpp [hunk 1]
```diff
@@ -30,12 +29,42 @@ namespace ErrorCodes
 namespace
 {
 
+void insertFromNullableOrDefault(MutableColumnPtr & dst, const ColumnNullable * nullable_col)
```
Comment (Avogar) [inline src/Interpreters/join_common.cpp:32]: Can you explain why do we need to insert defaults in case of Null? Why don't just copy all data from nested column?

File: src/Processors/Transforms/JoiningTransform.cpp [hunk 2]
```diff
@@ -15,7 +15,9 @@ namespace ErrorCodes
 Block JoiningTransform::transformHeader(Block header, const JoinPtr & join)
 {
     ExtraBlockPtr tmp;
+    LOG_DEBUG(&Poco::Logger::get("JoiningTransform"), "Before join block: '{}'", header.dumpStructure());
     join->joinBlock(header, tmp);
+    LOG_DEBUG(&Poco::Logger::get("JoiningTransform"), "After join block: '{}'", header.dumpStructure());
```
Comment (Avogar) [inline src/Processors/Transforms/JoiningTransform.cpp:20]: Do you want to leave these logs?

File: src/Interpreters/join_common.cpp (hunk 1 above)
Comment (vdimir) [reply src/Interpreters/join_common.cpp:32]: Because it can contain some unexpected values. It can be reproduced with this example added to test https://github.com/ClickHouse/ClickHouse/blob/943b71e4ff61d0a4da58f7feb89df30187232bc8/tests/queries/0_stateless/00445_join_nullable_keys.sql#L41 Without setting default values, nested column will contain non-zero values for NULLs.

File: src/Processors/Transforms/JoiningTransform.cpp (hunk 2 above)
Comment (vdimir) [reply src/Processors/Transforms/JoiningTransform.cpp:20]: Yes, it's printed once per request and it usually helps to debug how columns and types is changed after join.

File: src/Interpreters/join_common.cpp [hunk 3]
```diff
@@ -30,12 +29,42 @@ namespace ErrorCodes
...
+{
+
```
Comment (Avogar) [inline src/Interpreters/join_common.cpp:34]: Extra space

**Review by Avogar — APPROVED** [review]

File: src/Interpreters/join_common.cpp (hunk 3 above)
Comment (vdimir) [reply src/Interpreters/join_common.cpp:34]:
```suggestion
```
