### PR TITLE
MaterializedPostgreSQL: Support "generated columns" and default values

### LINKED ISSUE #40449: MaterializedPostgreSQL fails on data update in case of postgresql generated columns.
Clickhouse version affected  22.3.7.28, 22.8.1.2097 
postgres 14

Imaging following table in postgresql.

```sql
--postgres
CREATE TABLE test (
    id integer PRIMARY KEY,
    x double precision,
    y double precision GENERATED ALWAYS AS (x*2) STORED
);
insert into test values (1,1);
insert into test values (2,2);
```

then at clickhouse create

```sql
-- clickhouse
CREATE DATABASE IF NOT EXISTS {REPLICATION_IDENTIFIER:Identifier}
ENGINE = MaterializedPostgreSQL('db:5432', database', 'login', 'pass')
SETTINGS materialized_postgresql_tables_list='test';
// Wait until SELECT name, total_rows  FROM system.tables WHERE database = 'pg'; // gives 2 rows
```

do 

```sql
-- clickhouse
select * from pg.test
```

Everything is fine, all 3 columns are visible `id, x, y`

Now at postgresql delete column

```sql
-- postgres
delete from test where id = 2;
```

Update will not be replicated. In logs will be
```log
<Warning> PostgreSQLReplicaConsumer(scrapers): Table test (relation_id: 61753011) is skipped, because table schema has changed
```

I think, but not sure 100% it's because of this check
 https://github.com/ClickHouse/ClickHouse/blob/5e86d6c55b6f325c22a3bb1f2d0cafb47b94e16c/src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp#L500-L504

because no other warnings etc are seen in the log.

without `GENERATED` columns all is fine.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support PostgreSQL generated columns and default column values in `MaterializedPostgreSQL`. Closes https://github.com/ClickHouse/ClickHouse/issues/40449.

### CODE REVIEW

**Comment by kssenii** [comment]
No related failures:

> Stateful tests (asan) 

00180_no_seek_avoiding_when_reading_from_cache

> Stateful tests (debug) 

00180_no_seek_avoiding_when_reading_from_cache

> Stateful tests (ubsan)

00180_no_seek_avoiding_when_reading_from_cache

File: src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp [hunk 1]
```diff
@@ -195,7 +197,8 @@ void StorageMaterializedPostgreSQL::createNestedIfNeeded(PostgreSQLTableStructur
         const auto ast_create = getCreateNestedTableQuery(std::move(table_structure), table_override);
         auto table_id = getStorageID();
         auto tmp_nested_table_id = StorageID(table_id.database_name, getNestedTableName());
-        LOG_DEBUG(log, "Creating clickhouse table for postgresql table {}", table_id.getNameForLogs());
+        LOG_DEBUG(log, "Creating clickhouse table for postgresql table {} (ast: {})",
+                  table_id.getNameForLogs(), serializeAST(*ast_create));
```
Comment (vdimir) [inline src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp:201]: BTW, we have `IAST::formatForLogging` that formats ast with settings suitable for logging (oneline, hide secrets, etc)
https://github.com/ClickHouse/ClickHouse/blob/efb82a93c5fd365caf01a850cb90511153e9fa7d/src/Parsers/IAST.h#L283

Doesn't make to much difference here, but just in case.

File: src/Storages/PostgreSQL/PostgreSQLReplicationHandler.cpp [hunk 2]
```diff
@@ -444,12 +447,16 @@ StorageInfo PostgreSQLReplicationHandler::loadFromSnapshot(postgres::Connection
     assertBlocksHaveEqualStructure(input->getPort().getHeader(), block_io.pipeline.getHeader(), "postgresql replica load from snapshot");
     block_io.pipeline.complete(Pipe(std::move(input)));
 
+    /// TODO: make a test when we fail in the middle of inserting data from source.
```
Comment (vdimir) [inline src/Storages/PostgreSQL/PostgreSQLReplicationHandler.cpp:450]: Perhaps introducing a  fail point can make it easier to reproduce
https://github.com/ClickHouse/ClickHouse/blob/efb82a93c5fd365caf01a850cb90511153e9fa7d/src/Common/FailPoint.cpp#L41

File: src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp [hunk 3]
```diff
@@ -40,125 +56,160 @@ MaterializedPostgreSQLConsumer::MaterializedPostgreSQLConsumer(
...
-    description.init(sample_block);
-
-    columns = description.sample_block.cloneEmptyColumns();
-    const auto & storage_columns = storage_metadata->getColumns().getAllPhysical();
-    auto insert_columns = std::make_shared<ASTExpressionList>();
+    if (columns_.end() != std::find_if(
+            columns_.begin(), columns_.end(),
+            [](const auto & col) { return col.name == "_sign" || col.name == "_version"; }))
+    {
+        throw Exception(ErrorCodes::LOGICAL_ERROR,
```
Comment (vdimir) [inline src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:107]: Can't user create a columns with such names somehow?

File: src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp [hunk 4]
```diff
@@ -507,47 +549,94 @@ void MaterializedPostgreSQLConsumer::processReplicationMessage(const char * repl
                 return;
             }
 
+            auto log_table_structure_changed = [&](std::string_view reason)
```
Comment (vdimir) [inline src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:552]: I'm not entirely sure, but it seems like there might be a potential issue with the lifetime of the temporary std::string object returned by fmt::format. 

```suggestion
            auto log_table_structure_changed = [&](const std::string & reason)
```

File: src/Storages/PostgreSQL/PostgreSQLReplicationHandler.cpp (hunk 2 above)
Comment (kssenii) [reply src/Storages/PostgreSQL/PostgreSQLReplicationHandler.cpp:450]: Wow, cool, did not know about that, thanks.
Though this comment can be removed, because a test to which this comment is referring was added in https://github.com/ClickHouse/ClickHouse/pull/57567.

File: src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp (hunk 3 above)
Comment (kssenii) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:107]: Yes, he can of course, this code checks if they were added during ALTER query after MaterializedPostgreSQL table was created successfully as there. But it is written in doc that these column names are reserved for internal usage.

Comment (vdimir) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:107]: Shouldn't it be another error code then `LOGICAL_ERROR` that indicated bug in out code?

**Review by vdimir — APPROVED** [review]

File: src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp (hunk 3 above)
Comment (kssenii) [reply src/Storages/PostgreSQL/MaterializedPostgreSQLConsumer.cpp:107]: Yes, good point.

**Comment by tavplubix** [comment]
Looks like it breaks `test_postgresql_replica_database_engine_1`: [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X3Bvc3RncmVzcWxfcmVwbGljYV9kYXRhYmFzZV9lbmdpbmVfMScgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

**Comment by kssenii** [comment]
> Looks like it breaks test_postgresql_replica_database_engine_1: [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X3Bvc3RncmVzcWxfcmVwbGljYV9kYXRhYmFzZV9lbmdpbmVfMScgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)
Let's fix it quickly or revert

https://github.com/ClickHouse/ClickHouse/pull/57863

File: src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp [hunk 5]
```diff
@@ -186,20 +187,25 @@ PostgreSQLTableStructure::ColumnsInfoPtr readNamesAndTypesList(
...
+                    const auto column_name = std::get<0>(row);
+                    const auto data_type = convertPostgreSQLDataType(
                         std::get<1>(row), recheck_array,
                         use_nulls && (std::get<2>(row) == /* not nullable */"f"),
                         std::get<3>(row));
 
-                    columns.push_back(NameAndTypePair(std::get<0>(row), data_type));
+                    columns.push_back(NameAndTypePair(column_name, data_type));
+                    auto attgenerated = std::get<6>(row);
+                    LOG_TEST(&Poco::Logger::get("kssenii"), "KSSENII: attgenerated: {}", attgenerated);
```
Comment (azat) [inline src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:201]: Debug logging, I will remove it here - https://github.com/ClickHouse/ClickHouse/pull/58198

Comment (kssenii) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:201]: thanks

Comment (azat) [reply src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp:201]: New PR - #58237
