### PR TITLE
Handling loopback host ID properly to avoid collision when processing DDL tasks:

### LINKED ISSUE #86434: ClickHouse 25.8.1.5101 Keeper exception
### Company or project name

_No response_

### Describe what's wrong

All cluster nodes are trying to acquire the same node in Keeper `/clickhouse/task_queue/replicas/localhost:9000/active`.
This results in timeouts when executing DDL queries with ON CLUSTER.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

I prepared a test configuration to reproduce the error.

[keeper_server.xml](https://github.com/user-attachments/files/22063593/keeper_server.xml)
[docker-compose.yml](https://github.com/user-attachments/files/22063595/docker-compose.yml)
[config.xml](https://github.com/user-attachments/files/22063594/config.xml)

```bash
docker compose up -d
# wait at least 90 seconds
sleep 100
# error is already here
docker exec -it clickhouse-bug-clickhouse_02-1 chc "SELECT * FROM system.errors WHERE code=49 FORMAT Vertical"
Row 1:
──────
name:                     LOGICAL_ERROR
code:                     49
value:                    1
last_error_time:          2025-08-31 06:30:21
last_error_message:       Ephemeral node /clickhouse/task_queue/replicas/localhost:9000/active still exists after 90s, probably it's owned by someone else. Either session_timeout_ms in client's config is different from server's config or it's a bug. Node data: 'df192718-4dd7-414e-b4ae-14b121e67c26'
last_error_format_string: Ephemeral node {} still exists after {}s, probably it's owned by someone else. Either session_timeout_ms in client's config is different from server's config or it's a bug. Node data: '{}'
last_error_trace:         [322564383,210027726,210026368,440506736,440505297,399958939,399821186,399965734,323985234,324016666,132232044874435,132232045468164]
remote:                   0
query_id:  

# try to execute distributed DDL
docker exec -it clickhouse-bug-clickhouse_02-1 chc "CREATE TABLE table1 ON CLUSTER test (key String) Engine MergeTree() ORDER BY key FORMAT Vertical SETTINGS max_execution_time=10 "
Row 1:
──────
host:                clickhouse_01
port:                9000
status:              0
error:               
num_hosts_remaining: 1
num_hosts_active:    0
Received exception from server (version 25.8.1):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Timeout exceeded: elapsed 10576.002335 ms, maximum: 10000 ms. (TIMEOUT_EXCEEDED)
(query: CREATE TABLE table1 ON CLUSTER test (key String) Engine MergeTree() ORDER BY key FORMAT Vertical SETTINGS max_execution_time=10 )

# try to execute distributed DDL without timeout
time docker exec -it clickhouse-bug-clickhouse_02-1 chc "CREATE TABLE table3 ON CLUSTER test (key String) Engine MergeTree() ORDER BY key FORMAT Vertical"
Row 1:
──────
host:                clickhouse_01
port:                9000
status:              0
error:               
num_hosts_remaining: 1
num_hosts_active:    0

Row 2:
──────
host:                clickhouse_02
port:                9000
status:              0
error:               
num_hosts_remaining: 0
num_hosts_active:    0

real    1m30.763s
user    0m0.015s
sys     0m0.019s
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tuanpach**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Handling loopback host ID properly to avoid collision when processing DDL tasks:

- When marking the host as active, if it failed to claim the host (as another already claimed), if the host is loopback, just print a log.
- When processing the task, if the host of the task is a loopback, it must check if the host is already claimed by itself.

Closes [#86434](https://github.com/ClickHouse/ClickHouse/issues/86434)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by Algunenano** [comment]
I'm not sure about `allow_ddl_loopback_hosts` begin true by default. Isn't this what's causing all the problems in 25.8?

**Comment by Algunenano** [comment]
Also, can you explain how https://github.com/ClickHouse/ClickHouse/pull/81395 broke it? If we are not 100% sure about the fix I'd rather revert https://github.com/ClickHouse/ClickHouse/pull/81395, backport the revert to 25.8 and then reintroduce it properly.

**Comment by tuanpach** [comment]
> Also, can you explain how #81395 broke it? If we are not 100% sure about the fix I'd rather revert #81395, backport the revert to 25.8 and then reintroduce it properly.

In `DDLWorker`, `active_node_holders` is the map from the host_id to the `EphemeralNodeHolderPtr` that the replica has already claimed as its own host. (marked active).

The PR fixed the `DDLWorker::markReplicasActive` by removing the host from `active_node_holders` if the zookeeper expired. That's why the replica will try to mark the host as its own more frequently, every time the zookeeper expires.

In the issue https://github.com/ClickHouse/ClickHouse/issues/86434, because there is localhost in the config, both replicas tried to claim it as their own host. The failed one will throw the LOGICAL_ERROR.

> I'm not sure about allow_ddl_loopback_hosts begin true by default. Isn't this what's causing all the problems in 25.8?

At first, I tried to ignore loopback hosts when registering and marking active.
However, in our tests, we use `localhost` and `127.0.0.1` in the config. So I came up with the idea of adding `allow_ddl_loopback_hosts` with a default value of `true`. So it doesn't break the test. But it is not a good idea.

I will update the PR. My idea is that:
- When marking the host as active, if it failed to claim the host (as another already claimed), if the host is loopback, just print a log.
- When processing the task, if the host of the task is a loopback, it must check if the host is already claimed by itself.

**Comment by Algunenano** [comment]
> However, in our tests, we use localhost and 127.0.0.1 in the config. So I came up with the idea of adding allow_ddl_loopback_hosts with a default value of true. So it doesn't break the test. But it is not a good idea.

I would rather break and change the tests to be honest.

I don't think it makes sense to use a loopback host in DDLs, because that means effectively nobody can connect to you except yourself, and that's the complete opposite of replication. I would prefer to outright block the use of localhost and other loopback hosts there completely.

**Comment by tuanpach** [comment]
Using `localhost` might be useful in some cases. For example, when testing with 2 replicas on the same host. Each replica has its own port. In that case, they won't try to claim the same address.

Another thing is that the `localhost` is configured in [tests/config/config.d/clusters.xml](https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/clusters.xml), which is used in fast-test, stateless test. I think we don't know the exact IP of the running host to configure until it is running.

@Algunenano Please let me know your thoughts

File: src/Interpreters/DDLTask.cpp [hunk 1]
```diff
@@ -506,6 +541,20 @@ String DDLTask::getShardID() const
     return res;
 }
 
+bool DDLTask::isSeflHostID(const HostID & checking_host_id, std::optional<UInt16> maybe_self_secure_port, UInt16 self_port)
```
Comment (Algunenano) [inline src/Interpreters/DDLTask.cpp]:
```suggestion
bool DDLTask::isSelfHostID(const HostID & checking_host_id, std::optional<UInt16> maybe_self_secure_port, UInt16 self_port)
```

File: src/Interpreters/DDLTask.cpp [hunk 2]
```diff
@@ -506,6 +541,20 @@ String DDLTask::getShardID() const
...
+{
+    // If the checking_host_id has a loopback address, it is not considered as the self host_id.
+    // Because all replicas will try to claim it as their own hosts.
+    return (maybe_self_secure_port && checking_host_id.isLocalAddress(*maybe_self_secure_port))
+        || checking_host_id.isLocalAddress(self_port);
+}
+
+bool DDLTask::isSeflHostname(const String & checking_host_name, std::optional<UInt16> maybe_self_secure_port, UInt16 self_port)
```
Comment (Algunenano) [inline src/Interpreters/DDLTask.cpp]:
```suggestion
bool DDLTask::isSelfHostname(const String & checking_host_name, std::optional<UInt16> maybe_self_secure_port, UInt16 self_port)
```

**Review by Algunenano — COMMENTED** [review]
> Another thing is that the localhost is configured in [tests/config/config.d/clusters.xml](https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/clusters.xml), which is used in fast-test, stateless test. I think we don't know the exact IP of the running host to configure until it is running.

I'm failing to see how will this work if there are two different servers and both use localhost:9000 as their hostname. How do we prevent that? It's probably not related to `findCurrentHostID` but somewhere else, but I can't find it

**Comment by tuanpach** [comment]
> I'm failing to see how will this work if there are two different servers and both use localhost:9000 as their hostname. How do we prevent that? It's probably not related to `findCurrentHostID` but somewhere else, but I can't find it

They are running on localhost but using different ports. When claiming the host ID, it checks if the port is the same as the listening one.

There is a utility repo which can setup two replicas clusters for testing: https://github.com/ClickHouse/core-test-utils

File: src/Interpreters/DDLTask.cpp (hunk 1 above)
Comment (tuanpach) [reply src/Interpreters/DDLTask.cpp]: Updated

**Comment by Algunenano** [comment]
> They are running on localhost but using different ports. When claiming the host ID, it checks if the port is the same as the listening one.

If I have 2 different servers in 2 different machines, which is the case most of the time and in the reports. They would run in localhost and in the same port

**Comment by tuanpach** [comment]
> > They are running on localhost but using different ports. When claiming the host ID, it checks if the port is the same as the listening one.
> 
> If I have 2 different servers in 2 different machines, which is the case most of the time and in the reports. They would run in localhost and in the same port

From my understanding, the stateless tests are running with one replica. 

In integration tests, a few tests use the loopback host. And in this case, it will wait for 45s (3*keeper_session_timeout) to see if the host_id (localhost) is released. So the test can finish before triggering the LOGICAL_ERROR after waiting.

https://github.com/ClickHouse/ClickHouse/blob/0c75ac759b0918135b0f5d29c9fa39c42ec3b8b6/src/Common/ZooKeeper/ZooKeeper.cpp#L1150

With the changes in this PR, when two replicas are running on different machines with the same port (e.g, 9000), if `localhost:9000` host ID is configured in the `remote_servers`, one replica will claim the host as its own. The other will skip it instead of throwing LOGICAL_ERROR because the host is a loopback.


Please let me know if I missed anything.

**Comment by Algunenano** [comment]
> From my understanding, the stateless tests are running with one replica.
> In integration tests, a few tests use the loopback host.

I don't care about tests (:smile:) . I care about the multiple reports of people running several docker images (different servers) which clash because they all use `localhost:9000`.

This was working before, maybe by chance or maybe not, but something changed and we started using `localhost` (or doing it more often) which means it clashes with other replicas. That's why I'm asking and wondering if we should just avoid localhost if other hostnames are availab.e

**Comment by tuanpach** [comment]
> This was working before, maybe by chance or maybe not, but something changed and we started using localhost (or doing it more often) which means it clashes with other replicas

I explained the reason why the issue happened here: https://github.com/ClickHouse/ClickHouse/pull/86479#issuecomment-3256584444

With these changes, if the loopback host is claimed by one replica, others will not try to claim it. There will be no LOGICAL_ERROR.

> That's why I'm asking and wondering if we should just avoid localhost if other hostnames are availab.e

Disallowing loopback hosts might be too restrictive. Loopback hosts should not be used in production, but are helpful when testing.

**Review by Algunenano — APPROVED** [review]

**Comment by tuanpach** [comment]
- [Stress test (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86479&sha=5164a029d2f7791d2c6b41e979bd5f7781dec15c&name_0=PR&name_1=Stress%20test%20%28amd_tsan%29):
https://github.com/ClickHouse/ClickHouse/issues/84669

**Comment by veerendra2** [comment]
Hello @tuanpach, are these changes released in https://github.com/ClickHouse/ClickHouse/releases/tag/v25.8.3.66-lts ?

**Comment by tuanpach** [comment]
> Hello @tuanpach, are these changes released in https://github.com/ClickHouse/ClickHouse/releases/tag/v25.8.3.66-lts ?

No. It should be in https://github.com/ClickHouse/ClickHouse/releases/tag/v25.8.4.13-lts

https://github.com/ClickHouse/ClickHouse/compare/v25.8.3.66-lts...v25.8.4.13-lts
