### PR TITLE
Fix quantilesGK bug

### LINKED ISSUE #57683: quantilesGKState throws an exception `Aggregate function for calculation of multiple quantiles require at least one parameter.`
I perform these queries: 

```sql
SELECT quantilesGK(100, 0.25, 0.5, 0.75)(number + 1)
FROM numbers(1000);

SELECT quantilesGKState(1, 0.25, 0.5, 0.75)(number + 1)
FROM numbers(1000);
```
I tried the latest, 23.9 and 23.8. Output is the same.
I expect to see the result and a state representation of this result, but I get an error in the second query.

```
DB::Exception: Aggregate function for calculation of multiple quantiles require at least one parameter. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)
```

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix quantilesGK bug, close https://github.com/ClickHouse/ClickHouse/issues/57683

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 3a03e58cc6c0b1e7a7105b420466da1c977723e0 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58216/3a03e58cc6c0b1e7a7105b420466da1c977723e0/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58216/3a03e58cc6c0b1e7a7105b420466da1c977723e0/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Let's take a look at Fast Test.

**Comment by alexey-milovidov** [comment]
The code is not memory-safe: there is double-free: https://s3.amazonaws.com/clickhouse-test-reports/58216/d168dae7d1fca79903fe96f10f1711a349bacfb5/fuzzer_astfuzzerasan/report.html

When you will fix it, also add the example from Fuzzer as a new test.

**Comment by taiyang-li** [comment]
> The code is not memory-safe: there is double-free: https://s3.amazonaws.com/clickhouse-test-reports/58216/d168dae7d1fca79903fe96f10f1711a349bacfb5/fuzzer_astfuzzerasan/report.html
> 
> When you will fix it, also add the example from Fuzzer as a new test.

I'm really confused about how to find the sql which caused crash. Need you help, thanks

**Comment by alexey-milovidov** [comment]
It should be near the end at `server.log.zst`

**Comment by taiyang-li** [comment]
> It should be near the end at `server.log.zst`

@alexey-milovidov  fixed, hope for your review and merge

**Comment by alexey-milovidov** [comment]
Ok. Looks perfect. Can we make a functional test for this?
Otherwise, it complains: "Bugfix validate check — Changed tests don't reproduce the bug "

**Comment by taiyang-li** [comment]
> Ok. Looks perfect. Can we make a functional test for this?
> Otherwise, it complains: "Bugfix validate check — Changed tests don't reproduce the bug "

it was already added in tests/queries/0_stateless/02661_quantile_approx.reference

File: src/AggregateFunctions/QuantileGK.h [hunk 1]
```diff
@@ -0,0 +1,491 @@
...
+
+    void read(ReadBuffer & buf)
+    {
+        readBinaryLittleEndian(compress_threshold, buf);
+        readBinaryLittleEndian(relative_error, buf);
+        readBinaryLittleEndian(count, buf);
+
+        size_t sampled_len = 0;
+        readBinaryLittleEndian(sampled_len, buf);
+        sampled.resize(sampled_len);
```
Comment (Algunenano) [inline src/AggregateFunctions/QuantileGK.h:263]: Needs sanity check

**Review by Algunenano — COMMENTED** [review]
The failures are unrelated. Please update with master so they go away.

And have a look at [this comment](https://github.com/ClickHouse/ClickHouse/pull/58216#discussion_r1466987963). Let's add a sanity check so we don't reserve too much memory on corrupted input (which a client might send maliciously).

File: src/AggregateFunctions/QuantileGK.h (hunk 1 above)
Comment (Algunenano) [reply src/AggregateFunctions/QuantileGK.h:263]: :point_up:

Comment (taiyang-li) [reply src/AggregateFunctions/QuantileGK.h:267]: Sorry to reply late. It is added now.

File: src/AggregateFunctions/QuantileGK.h [hunk 2]
```diff
@@ -260,6 +260,10 @@ class ApproxSampler
 
         size_t sampled_len = 0;
         readBinaryLittleEndian(sampled_len, buf);
+        if (sampled_len > compress_threshold)
```
Comment (Algunenano) [inline src/AggregateFunctions/QuantileGK.h:264]: If the user controls both `sampled_len` and `compress_threshold` this is not a sanity check. What if it sends 2^63 in both?

File: src/AggregateFunctions/QuantileGK.h [hunk 3]
```diff
@@ -0,0 +1,496 @@
...
+        , head_sampled(other.head_sampled.begin(), other.head_sampled.end())
+    {
+    }
+
+    explicit ApproxSampler(
+        double relative_error_, size_t compress_threshold_ = default_compress_threshold, size_t count_ = 0, bool compressed_ = false)
+        : relative_error(relative_error_), compress_threshold(compress_threshold_), count(count_), compressed(compressed_)
+    {
+        sampled.reserve(compress_threshold);
+        backup_sampled.reserve(compress_threshold);
```
Comment (Algunenano) [inline src/AggregateFunctions/QuantileGK.h:63]: Why do we need to reserve for `backup_sampled` here. Seems like a waste of memory. For small states reserving for `sampled` will be a waste of memory too (making -Merge use way more memory than necessary).

File: src/AggregateFunctions/QuantileGK.h [hunk 4]
```diff
@@ -0,0 +1,496 @@
...
+        , compress_threshold(other.compress_threshold)
+        , count(other.count)
+        , compressed(other.compressed)
+        , sampled(other.sampled.begin(), other.sampled.end())
+        , backup_sampled(other.backup_sampled.begin(), other.backup_sampled.end())
+        , head_sampled(other.head_sampled.begin(), other.head_sampled.end())
+    {
+    }
+
+    explicit ApproxSampler(
```
Comment (Algunenano) [inline src/AggregateFunctions/QuantileGK.h:58]: It seems like we only ever set `relative_error_` and the rest of the parameters are unused. Is it even possible to change `compress_threshold` or set `count`/`compressed`? Let's simplify

File: src/AggregateFunctions/QuantileGK.h (hunk 2 above)
Comment (Algunenano) [reply src/AggregateFunctions/QuantileGK.h:264]: Since it seems that users can't change the compress_threshold at all, we should check against that for both `compress_threshold` (which should be equal) and `sampled_len` (which should be <=). Am I understanding it correctly?

**Review by Algunenano — CHANGES_REQUESTED** [review]
Some comments about the PR:
* As a bugfix, this PR is bad. A whole refactor means that a) the PR is 100x what it needed to be (5 vs 500 lines), b) it takes longer to be reviewed and c) you get a full review and d) it won't be backported.
* I don't like moving code from .cpp to .h just to add an example that doesn't provide any value. For testing you can simply include the .cpp (`#include <AggregateFunctions/AggregateFunctionQuantileGK.cpp>`) and do whatever local tests you require. No need to add new headers that will be misused and grow the compilation and binary size.
* I'd recommend you to clean up the commits before making a PR. Having commits adding prints or commenting and uncommenting code is bad as it will show you as the last person changing the code, although you left it exactly as it was.

**Comment by taiyang-li** [comment]
> Some comments about the PR:
> 
> * As a bugfix, this PR is bad. A whole refactor means that a) the PR is 100x what it needed to be (5 vs 500 lines), b) it takes longer to be reviewed and c) you get a full review and d) it won't be backported.
> * I don't like moving code from .cpp to .h just to add an example that doesn't provide any value. For testing you can simply include the .cpp (`#include <AggregateFunctions/AggregateFunctionQuantileGK.cpp>`) and do whatever local tests you require. No need to add new headers that will be misused and grow the compilation and binary size.
> * I'd recommend you to clean up the commits before making a PR. Having commits adding prints or commenting and uncommenting code is bad as it will show you as the last person changing the code, although you left it exactly as it was.

Good advices. I'll make this PR clean.

File: src/AggregateFunctions/QuantileGK.h (hunk 2 above)
Comment (taiyang-li) [reply src/AggregateFunctions/QuantileGK.h:264]: Yes

File: src/AggregateFunctions/QuantileGK.h (hunk 3 above)
Comment (taiyang-li) [reply src/AggregateFunctions/QuantileGK.h:63]: It is used to avoid reallocs

File: src/AggregateFunctions/QuantileGK.h (hunk 4 above)
Comment (taiyang-li) [reply src/AggregateFunctions/QuantileGK.h:58]: It is impossible to modify compress_threshold  for users.

Comment (taiyang-li) [reply src/AggregateFunctions/QuantileGK.h:58]: > Let's simplify

File: src/AggregateFunctions/AggregateFunctionQuantileGK.cpp [hunk 5]
```diff
@@ -261,11 +260,15 @@ class ApproxSampler
 
         size_t sampled_len = 0;
         readBinaryLittleEndian(sampled_len, buf);
+        if (sampled_len > compress_threshold)
```
Comment (Algunenano) [inline src/AggregateFunctions/AggregateFunctionQuantileGK.cpp:263]: For this to work we need to also check `compress_threshold` against `default_compress_threshold` (which we should probably do anyway).

Comment (Algunenano) [reply src/AggregateFunctions/AggregateFunctionQuantileGK.cpp:263]: I can't push to the branch directly to fix it so here is what I was planning on adding:

```patch
diff --git a/src/AggregateFunctions/AggregateFunctionQuantileGK.cpp b/src/AggregateFunctions/AggregateFunctionQuantileGK.cpp
index de8ab65982f..f991282fbb1 100644
--- a/src/AggregateFunctions/AggregateFunctionQuantileGK.cpp
+++ b/src/AggregateFunctions/AggregateFunctionQuantileGK.cpp
@@ -17,6 +17,7 @@ namespace DB
 namespace ErrorCodes
 {
     extern const int ILLEGAL_TYPE_OF_ARGUMENT;
+    extern const int INCORRECT_DATA;
     extern const int LOGICAL_ERROR;
     extern const int NOT_IMPLEMENTED;
 }
@@ -255,6 +256,12 @@ public:
     void read(ReadBuffer & buf)
     {
         readBinaryLittleEndian(compress_threshold, buf);
+        if (compress_threshold != default_compress_threshold)
+            throw Exception(
+                ErrorCodes::INCORRECT_DATA,
+                "The compress threshold ({}) isn't the expected one ({})",
+                compress_threshold,
+                default_compress_threshold);
         readBinaryLittleEndian(relative_error, buf);
         readBinaryLittleEndian(count, buf);
 ```

**Review by Algunenano — APPROVED** [review]
