### PR TITLE
Resubmit 'Partial merge join uses fs cache for temp files'

### LINKED ISSUE #77522: Logical error in MergeJoin::mergeFlushedRightBlocks
### Describe the bug

Logical error: '(isConst() || isSparse()) ? getDataType() == rhs.getDataType() : typeid(*this) == typeid(rhs)'.

Same error as in #75450 in a different context

### How to reproduce

```
SELECT count(1), uniqExact(1) FROM (
SELECT k FROM (SELECT materialize(1) as k FROM numbers(1)) nums
JOIN (SELECT 1 AS k, number n FROM numbers(100000)) j
USING k);
```

### Error message and/or stacktrace

See https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=76621&sha=0e4651187cda4199e67bf178d67516313695fbfc&name_0=PR&name_1=Stress+test+%28ubsan%29 
in PR #76621 

```
2025.03.12 16:40:52.958916 [ 25176 ] {25b6644d-be7c-4c5d-8268-b174fb269276} <Fatal> : Logical error: '(isConst() || isSparse()) ? getDataType() == rhs.getDataType() : typeid(*this) == typeid(rhs)'.
2025.03.12 16:40:52.974715 [ 25176 ] {25b6644d-be7c-4c5d-8268-b174fb269276} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/StackTrace.cpp:386: StackTrace::StackTrace() @ 0x00000000234ba3e3
1. ./build_docker/./src/Common/Exception.cpp:53: DB::abortOnFailedAssertion(String const&) @ 0x00000000233c18c3
2. DB::IColumn::assertTypeEquality(DB::IColumn const&) const @ 0x0000000017a44473
3. ./src/Columns/IColumn.h:197: DB::(anonymous namespace)::extractMinMax(DB::Block const&, DB::Block const&) @ 0x000000002d795c95
4. ./build_docker/./src/Interpreters/MergeJoin.cpp:640: void std::__function::__policy_invoker<void (DB::Block const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::MergeJoin::mergeFlushedRightBlocks()::$_0, void (DB::Block const&)>>(std::__function::__policy_storage const*, DB::Block const&) @ 0x000000002d79a9f8
5. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000002d8ae7bf
6. ./build_docker/./src/Interpreters/MergeJoin.cpp:644: DB::MergeJoin::mergeFlushedRightBlocks() @ 0x000000002d79554c
7. ./build_docker/./src/Interpreters/MergeJoin.cpp:575: DB::MergeJoin::setTotals(DB::Block const&) @ 0x000000002d79453f
8. ./build_docker/./src/Processors/Transforms/JoiningTransform.cpp:353: DB::FillingRightJoinSideTransform::work() @ 0x00000000316b56f9
9. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000003112550e
10. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:296: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000031110a3f
11. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:262: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000003110fc05
12. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:128: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000003110f60a
13. ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000003112a517
14. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000002359c72f
15. ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000235a43ca
16. ? @ 0x00007f5809221ac3
17. ? @ 0x00007f58092b3850

2025.03.12 16:42:33.798468 [ 37603 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.03.12 16:42:33.822637 [ 37603 ] {} <Fatal> BaseDaemon: (version 25.3.1.1851, build id: 97A181A4CEC04074A32CC8B6F3C5BECAB9ED7049, git hash: 757c062cebc7fb0074be0c63a3ef9ec4e9acca60, architecture: x86_64) (from thread 25176) Received signal 6
2025.03.12 16:42:33.833462 [ 37603 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.03.12 16:42:33.849961 [ 37603 ] {} <Fatal> BaseDaemon: 
2025.03.12 16:42:33.855906 [ 37603 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000558dba0ce92d 0x0000558dba59c1a9 0x00007f58091cf520 0x00007f58092239fd 0x00007f58091cf476 0x00007f58091b57f3 0x0000558db9fd47f5 0x0000558db9fd48e0 0x0000558dae657473 0x0000558dc43a8c95 0x0000558dc43ad9f8 0x0000558dc44c17bf 0x0000558dc43a854c 0x0000558dc43a753f 0x0000558dc82c86f9 0x0000558dc7d3850e 0x0000558dc7d23a3f 0x0000558dc7d22c05 0x0000558dc7d2260a 0x0000558dc7d3d517 0x0000558dba1af72f 0x0000558dba1b73ca 0x00007f5809221ac3 0x00007f58092b3850
2025.03.12 16:42:33.875734 [ 37603 ] {} <Fatal> BaseDaemon: ########################################
2025.03.12 16:42:33.878844 [ 37603 ] {} <Fatal> BaseDaemon: (version 25.3.1.1851, build id: 97A181A4CEC04074A32CC8B6F3C5BECAB9ED7049, git hash: 757c062cebc7fb0074be0c63a3ef9ec4e9acca60) (from thread 25176) (query_id: 25b6644d-be7c-4c5d-8268-b174fb269276) (query: SELECT count(1), uniqExact(1) FROM (
SELECT k FROM (SELECT materialize(1) as k FROM numbers(1)) nums
JOIN (SELECT 1 AS k, number n FROM numbers(100000)) j
USING k);) Received signal Aborted (6)
2025.03.12 16:42:33.963152 [ 37603 ] {} <Fatal> BaseDaemon: 
2025.03.12 16:42:33.976767 [ 37603 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000558dba0ce92d 0x0000558dba59c1a9 0x00007f58091cf520 0x00007f58092239fd 0x00007f58091cf476 0x00007f58091b57f3 0x0000558db9fd47f5 0x0000558db9fd48e0 0x0000558dae657473 0x0000558dc43a8c95 0x0000558dc43ad9f8 0x0000558dc44c17bf 0x0000558dc43a854c 0x0000558dc43a753f 0x0000558dc82c86f9 0x0000558dc7d3850e 0x0000558dc7d23a3f 0x0000558dc7d22c05 0x0000558dc7d2260a 0x0000558dc7d3d517 0x0000558dba1af72f 0x0000558dba1b73ca 0x00007f5809221ac3 0x00007f58092b3850
2025.03.12 16:42:34.024350 [ 37603 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./build_docker/./src/Common/StackTrace.cpp:386: StackTrace::tryCapture()
2025.03.12 16:42:34.037616 [ 37603 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:355: StackTrace::StackTrace(ucontext_t const&) @ 0x00000000234bb92d
2025.03.12 16:42:34.068900 [ 37603 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/SignalHandlers.cpp:106: signalHandler(int, siginfo_t*, void*) @ 0x00000000239891a9
2025.03.12 16:42:34.080159 [ 37603 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007f58091cf520
2025.03.12 16:42:34.088229 [ 37603 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007f58092239fd
2025.03.12 16:42:34.094196 [ 37603 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f58091cf476
2025.03.12 16:42:34.106524 [ 37603 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f58091b57f3
2025.03.12 16:42:34.151979 [ 37603 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x00000000233c17f5
2025.03.12 16:42:34.244880 [ 37603 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Common/Exception.cpp:54: DB::Exception::MessageMasked::MessageMasked(String const&) @ 0x00000000233c18e0
2025.03.12 16:42:34.486536 [ 37603 ] {} <Fatal> BaseDaemon: 8. DB::IColumn::assertTypeEquality(DB::IColumn const&) const @ 0x0000000017a44473
2025.03.12 16:42:34.752172 [ 37603 ] {} <Fatal> BaseDaemon: 9.0. inlined from ./src/Columns/IColumn.h:197: DB::IColumn::insertFrom(DB::IColumn const&, unsigned long)
2025.03.12 16:42:34.752564 [ 37603 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Interpreters/MergeJoin.cpp:134: DB::(anonymous namespace)::extractMinMax(DB::Block const&, DB::Block const&) @ 0x000000002d795c95
2025.03.12 16:42:34.864117 [ 37603 ] {} <Fatal> BaseDaemon: 10.0. inlined from ./build_docker/./src/Interpreters/MergeJoin.cpp:640: operator()
2025.03.12 16:42:34.865986 [ 37603 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::MergeJoin::mergeFlushedRightBlocks()::$_0&>()(std::declval<DB::Block const&>())) std::__invoke[abi:ne190107]<DB::MergeJoin::mergeFlushedRightBlocks()::$_0&, DB::Block const&>(DB::MergeJoin::mergeFlushedRightBlocks()::$_0&, DB::Block const&)
2025.03.12 16:42:34.867840 [ 37603 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne190107]<DB::MergeJoin::mergeFlushedRightBlocks()::$_0&, DB::Block const&>(DB::MergeJoin::mergeFlushedRightBlocks()::$_0&, DB::Block const&)
2025.03.12 16:42:34.880006 [ 37603 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.03.12 16:42:34.881561 [ 37603 ] {} <Fatal> BaseDaemon: 10. ./contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x000000002d79a9f8
2025.03.12 16:42:34.914812 [ 37603 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.03.12 16:42:34.918333 [ 37603 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.03.12 16:42:34.919881 [ 37603 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./build_docker/./src/Interpreters/SortedBlocksWriter.cpp:82: DB::(anonymous namespace)::flushToManyFiles(std::shared_ptr<DB::TemporaryDataOnDiskScope> const&, DB::QueryPipelineBuilder, std::function<void (DB::Block const&)>)
2025.03.12 16:42:34.921178 [ 37603 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Interpreters/SortedBlocksWriter.cpp:275: DB::SortedBlocksWriter::finishMerge(std::function<void (DB::Block const&)>) @ 0x000000002d8ae7bf
2025.03.12 16:42:35.013809 [ 37603 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Interpreters/MergeJoin.cpp:644: DB::MergeJoin::mergeFlushedRightBlocks() @ 0x000000002d79554c
2025.03.12 16:42:35.133847 [ 37603 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Interpreters/MergeJoin.cpp:575: DB::MergeJoin::setTotals(DB::Block const&) @ 0x000000002d79453f
2025.03.12 16:42:35.242171 [ 37603 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Processors/Transforms/JoiningTransform.cpp:353: DB::FillingRightJoinSideTransform::work() @ 0x00000000316b56f9
2025.03.12 16:42:35.277286 [ 37603 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.03.12 16:42:35.278510 [ 37603 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000003112550e
2025.03.12 16:42:35.295700 [ 37603 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:296: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000031110a3f
2025.03.12 16:42:35.318978 [ 37603 ] {} <Fatal> BaseDaemon: 17.0. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:262: DB::PipelineExecutor::executeSingleThread(unsigned long)
2025.03.12 16:42:35.323838 [ 37603 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:454: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000003110fc05
2025.03.12 16:42:35.342583 [ 37603 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:128: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000003110f60a
2025.03.12 16:42:35.376619 [ 37603 ] {} <Fatal> BaseDaemon: 19.0. inlined from ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
2025.03.12 16:42:35.382950 [ 37603 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:102: operator()
2025.03.12 16:42:35.389214 [ 37603 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__invoke[abi:ne190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
2025.03.12 16:42:35.400538 [ 37603 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:ne190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
2025.03.12 16:42:35.407645 [ 37603 ] {} <Fatal> BaseDaemon: 19.4. inlined from ./contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:ne190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
2025.03.12 16:42:35.411513 [ 37603 ] {} <Fatal> BaseDaemon: 19.5. inlined from ./src/Common/ThreadPool.h:312: operator()
2025.03.12 16:42:35.413116 [ 37603 ] {} <Fatal> BaseDaemon: 19.6. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__invoke[abi:ne190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
2025.03.12 16:42:35.414884 [ 37603 ] {} <Fatal> BaseDaemon: 19.7. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
2025.03.12 16:42:35.417189 [ 37603 ] {} <Fatal> BaseDaemon: 19.8. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.03.12 16:42:35.420240 [ 37603 ] {} <Fatal> BaseDaemon: 19. ./contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x000000003112a517
2025.03.12 16:42:35.440270 [ 37603 ] {} <Fatal> BaseDaemon: 20.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.03.12 16:42:35.442045 [ 37603 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.03.12 16:42:35.442637 [ 37603 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./src/Common/ThreadPool.cpp:809: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000002359c72f
2025.03.12 16:42:35.521695 [ 37603 ] {} <Fatal> BaseDaemon: 21.0. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.03.12 16:42:35.522511 [ 37603 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:ne190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.03.12 16:42:35.523140 [ 37603 ] {} <Fatal> BaseDaemon: 21. ./contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000235a43ca
2025.03.12 16:42:35.523969 [ 37603 ] {} <Fatal> BaseDaemon: 22. ? @ 0x00007f5809221ac3
2025.03.12 16:42:35.524660 [ 37603 ] {} <Fatal> BaseDaemon: 23. ? @ 0x00007f58092b3850
2025.03.12 16:42:35.525871 [ 37603 ] {} <Fatal> BaseDaemon: ========================================
2025.03.12 16:42:35.527905 [ 37603 ] {} <Fatal> BaseDaemon: Job's origin stack trace: 0x0000558dba0cd3e3 0x0000558dba1aeb98 0x0000558dba1b0d70 0x0000558dba1b14b6 0x0000558dc7d3be8d 0x0000558dc7d3c57d 0x0000558dc7be4a65 0x0000558dc7bd0139 0x0000558dc7bff76e 0x0000558dcbfbb0a2 0x0000558dcbfbbd72 0x0000558dcbf24ad7 0x0000558dcbf204ce 0x00007f5809221ac3 0x00007f58092b3850
2025.03.12 16:42:35.545781 [ 37603 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./build_docker/./src/Common/StackTrace.cpp:386: StackTrace::tryCapture()
2025.03.12 16:42:35.547316 [ 37603 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:61: StackTrace::StackTrace() @ 0x00000000234ba3e3
2025.03.12 16:42:35.573799 [ 37603 ] {} <Fatal> BaseDaemon: 1.0. inlined from ./build_docker/./src/Common/ThreadPool.cpp:130: JobWithPriority
2025.03.12 16:42:35.592364 [ 37603 ] {} <Fatal> BaseDaemon: 1.1. inlined from ./contrib/boost/boost/heap/detail/stable_heap.hpp:306: internal_type<std::function<void ()>, Priority &, StrongTypedef<unsigned long, CurrentMetrics::MetricTag> &, const DB::OpenTelemetry::TracingContextOnThread, bool &, (anonymous namespace)::ScopedDecrement>
2025.03.12 16:42:35.595315 [ 37603 ] {} <Fatal> BaseDaemon: 1.2. inlined from ./contrib/boost/boost/heap/detail/stable_heap.hpp:400: boost::heap::detail::heap_base<JobWithPriority, std::less<JobWithPriority>, false, unsigned long, true>::internal_type boost::heap::detail::heap_base<JobWithPriority, std::less<JobWithPriority>, false, unsigned long, true>::make_node<std::function<void ()>, Priority&, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>&, DB::OpenTelemetry::TracingContextOnThread const, bool&, (anonymous namespace)::ScopedDecrement>(std::function<void ()>&&, Priority&, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&, (anonymous namespace)::ScopedDecrement&&)
2025.03.12 16:42:35.596718 [ 37603 ] {} <Fatal> BaseDaemon: 1. ./contrib/boost/boost/heap/priority_queue.hpp:260: void boost::heap::priority_queue<JobWithPriority, boost::heap::stable<true>, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::emplace<std::function<void ()>, Priority&, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>&, DB::OpenTelemetry::TracingContextOnThread const, bool&, (anonymous namespace)::ScopedDecrement>(std::function<void ()>&&, Priority&, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>&, DB::OpenTelemetry::TracingContextOnThread const&&, bool&, (anonymous namespace)::ScopedDecrement&&) @ 0x000000002359bb98
2025.03.12 16:42:35.614611 [ 37603 ] {} <Fatal> BaseDaemon: 2. ./build_docker/./src/Common/ThreadPool.cpp:401: void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool) @ 0x000000002359dd70
2025.03.12 16:42:35.642647 [ 37603 ] {} <Fatal> BaseDaemon: 3. ./build_docker/./src/Common/ThreadPool.cpp:506: ThreadPoolImpl<std::thread>::scheduleOrThrow(std::function<void ()>, Priority, unsigned long, bool) @ 0x000000002359e4b6
2025.03.12 16:42:35.655239 [ 37603 ] {} <Fatal> BaseDaemon: 4.0. inlined from ./src/Common/ThreadPool.h:279: ThreadFromGlobalPoolImpl<(lambda at ./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:100:21)>
2025.03.12 16:42:35.655976 [ 37603 ] {} <Fatal> BaseDaemon: 4. ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long) @ 0x0000000031128e8d
2025.03.12 16:42:35.669028 [ 37603 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:131: DB::PullingAsyncPipelineExecutor::pull(DB::Block&, unsigned long) @ 0x000000003112957d
2025.03.12 16:42:35.776216 [ 37603 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Server/TCPHandler.cpp:1237: DB::TCPHandler::processOrdinaryQuery(DB::QueryState&) @ 0x0000000030fd1a65
2025.03.12 16:42:36.040711 [ 37603 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Server/TCPHandler.cpp:678: DB::TCPHandler::runImpl() @ 0x0000000030fbd139
2025.03.12 16:42:36.387429 [ 37603 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Server/TCPHandler.cpp:2629: DB::TCPHandler::run() @ 0x0000000030fec76e
2025.03.12 16:42:36.395700 [ 37603 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000353a80a2
2025.03.12 16:42:36.405531 [ 37603 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000353a8d72
2025.03.12 16:42:36.417945 [ 37603 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000035311ad7
2025.03.12 16:42:36.425171 [ 37603 ] {} <Fatal> BaseDaemon: 12. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000003530d4ce
2025.03.12 16:42:36.427027 [ 37603 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007f5809221ac3
2025.03.12 16:42:36.428159 [ 37603 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f58092b3850
2025.03.12 16:42:36.429918 [ 37603 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

### PR DESCRIPTION
**Pull request by vdimir**
Resubmit  #77390, close https://github.com/ClickHouse/ClickHouse/issues/77522

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Reverted

* Join algorithm 'partial_merge' uses `temporary_data_in_cache` feature when it's enabled

### CODE REVIEW

File: src/Interpreters/TemporaryDataOnDisk.cpp [hunk 1]
```diff
@@ -334,8 +334,9 @@ void TemporaryDataOnDiskScope::deltaAllocAndCheck(ssize_t compressed_delta, ssiz
 
 TemporaryBlockStreamHolder::TemporaryBlockStreamHolder(const Block & header_, TemporaryDataOnDiskScope * parent_, size_t reserve_size)
     : WrapperGuard(std::make_unique<TemporaryDataBuffer>(parent_, reserve_size), DBMS_TCP_PROTOCOL_VERSION, header_)
-    , header(header_)
-{}
+    , header(header_.cloneWithoutColumns()) /// header is copied without columns to exclude constant columns since they are not supported in (de/)serialization
```
Comment (vdimir) [inline src/Interpreters/TemporaryDataOnDisk.cpp:337]: Fix for https://github.com/ClickHouse/ClickHouse/issues/77522

**Review by jkartseva — APPROVED** [review]
Looks good
