### PR TITLE
Check for bad index granularity

### LINKED ISSUE #44536: CH hangs with insertion (index_granularity  = 0)
```sql
CREATE TABLE t
(
   id Int64, 
   d String,
   p Map(String, String)
   
)
ENGINE = ReplacingMergeTree order by id settings index_granularity  = 0;


insert into t values (1,  's', {'a':'b'});

CH starts eating RAM until it crashes

the same with

insert into t select 1,  's', map('a','b');

```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Prevent users from mistakenly specifying zero (invalid) value for `index_granularity`. This closes #44536.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -1,34 +1,23 @@
 #include <Storages/MergeTree/MergeTreeData.h>
 
 #include <Backups/BackupEntriesCollector.h>
-#include <Backups/BackupEntryFromImmutableFile.h>
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeData.cpp:4]: CLion.

File: src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp [hunk 2]
```diff
@@ -152,11 +154,13 @@ static size_t computeIndexGranularityImpl(
             index_granularity_for_block = index_granularity_bytes / size_of_row_in_bytes;
         }
     }
-    if (index_granularity_for_block == 0) /// very rare case when index granularity bytes less then single row
-        index_granularity_for_block = 1;
-
     /// We should be less or equal than fixed index granularity
     index_granularity_for_block = std::min(fixed_index_granularity_rows, index_granularity_for_block);
+
```
Comment (alesapin) [inline src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp:159]: Why you changed the order or these lines?

**Review by alesapin — APPROVED** [review]

File: src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp (hunk 2 above)
Comment (alexey-milovidov) [reply src/Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp:159]: It will saturate 0 to 1 even if `fixed_index_granularity_rows` was 0 in this function.

**Comment by alexey-milovidov** [comment]
#44549
