### PR TITLE
odbc fix

### LINKED ISSUE #25029: Got Error Message when Using clickhouse-odbc-bridge sometimes
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Hello @alexey-milovidov, I have got some error message when using select odbc table sometimes, and throw the error message like `HTTP status code: 500 Internal Server Error, body: ?std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1625: 08S0: Could not send Query(connection dead);`, and I need to `kill` the `clickhouse-odbc-bridge` sub process, but after sometime, the error message recurred. I guess the connection was closed   unexpectedly, so the error message will recurred. please tell me  how to solve it?

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**
```
2021.06.07 14:18:26.991634 [ 119147 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: [::ffff:10.254.8.103]:52528, User-Agent: (none), Length: 0, Content Type: text/plain, Transfer Encoding: identity, X-Forwarded-For: (none)
2021.06.07 14:18:26.991720 [ 119147 ] {} <Trace> DynamicQueryHandler: Request URI: /?user=default&session_timeout=60&output_format_json_quote_64bit_integers=0&enable_http_compression=0&database=default&query_id=26e89631-b8e0-4d4c-8c26-2c92907292b5&query=select+member_id+from+dmp_enrichment.%60user_tag_%E7%94%A8%E6%88%B7%E5%88%86%E5%B1%82%60+where+value+%3D+%27%E6%96%B0%E7%94%A8%E6%88%B7%27+and+month%3D%272021-03-01%27+limit+50001+FORMAT+JSON%3B
2021.06.07 14:18:26.991777 [ 119147 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2021.06.07 14:18:26.991793 [ 119147 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.*
2021.06.07 14:18:26.991810 [ 119147 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.*
2021.06.07 14:18:26.992518 [ 119147 ] {26e89631-b8e0-4d4c-8c26-2c92907292b5} <Trace> ReadWriteBufferFromHTTP: Sending request to http://127.0.0.1:9018/ping
2021.06.07 14:18:26.992956 [ 119147 ] {26e89631-b8e0-4d4c-8c26-2c92907292b5} <Trace> ReadWriteBufferFromHTTP: Sending request to http://127.0.0.1:9018/?connection_string=DSN%3Dgp234&max_block_size=65505
2021.06.07 14:18:26.993863 [ 119147 ] {26e89631-b8e0-4d4c-8c26-2c92907292b5} <Error> executeQuery: Code: 86, e.displayText() = DB::Exception: Received error from remote server /?connection_string=DSN%3Dgp234&max_block_size=65505. HTTP status code: 500 Internal Server Error, body: ?std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1625: 08S0: Could not send Query(connection dead);
Could not send Query(connection dead) , Stack trace (when copying this message, always include the lines below):

0. ? @ 0x39c7262 in /usr/bin/clickhouse-odbc-bridge
1. ? @ 0x39c983d in /usr/bin/clickhouse-odbc-bridge
2. ? @ 0x39c8951 in /usr/bin/clickhouse-odbc-bridge
3. ? @ 0x2b33786 in /usr/bin/clickhouse-odbc-bridge
4. ? @ 0x2b2d524 in /usr/bin/clickhouse-odbc-bridge
5. ? @ 0x396b550 in /usr/bin/clickhouse-odbc-bridge
6. ? @ 0x52637af in /usr/bin/clickhouse-odbc-bridge
7. ? @ 0x526521a in /usr/bin/clickhouse-odbc-bridge
8. ? @ 0x5d996b9 in ?
9. ? @ 0x5d9612a in ?
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x879d83a in /usr/bin/clickhouse
1. DB::assertResponseIsOk(Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) @ 0xd5b3da3 in /usr/bin/clickhouse
2. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::call(Poco::URI, Poco::Net::HTTPResponse&) @ 0xd5abcae in /usr/bin/clickhouse
3. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::ReadWriteBufferFromHTTPBase(std::__1::shared_ptr<DB::UpdatableSession>, Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DB::RemoteHostFilter const&) @ 0xd5a8400 in /usr/bin/clickhouse
4. DB::ReadWriteBufferFromHTTP::ReadWriteBufferFromHTTP(Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, DB::ConnectionTimeouts const&, unsigned long, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, DB::RemoteHostFilter const&) @ 0xd5a7bf7 in /usr/bin/clickhouse
5. DB::IStorageURLBase::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf915e1b in /usr/bin/clickhouse
6. DB::StorageXDBC::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf91f3c5 in /usr/bin/clickhouse
7. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf74b877 in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0xf0ce9e0 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf0c4c94 in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf0c3c7c in /usr/bin/clickhouse
11. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf3e4e9e in /usr/bin/clickhouse
12. DB::InterpreterSelectWithUnionQuery::execute() @ 0xf3e6011 in /usr/bin/clickhouse
13. ? @ 0xf5a2864 in /usr/bin/clickhouse
14. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf5a6375 in /usr/bin/clickhouse
15. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xfd2194f in /usr/bin/clickhouse
16. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfd25069 in /usr/bin/clickhouse
17. DB::HTTPServerConnection::run() @ 0xfda8ed0 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x1241daef in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x1241f57a in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x12559339 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x1255532a in /usr/bin/clickhouse
22. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
23. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

2021.06.07 14:18:26.994026 [ 119147 ] {26e89631-b8e0-4d4c-8c26-2c92907292b5} <Error> DynamicQueryHandler: Code: 86, e.displayText() = DB::Exception: Received error from remote server /?connection_string=DSN%3Dgp234&max_block_size=65505. HTTP status code: 500 Internal Server Error, body: ?std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1625: 08S0: Could not send Query(connection dead);
Could not send Query(connection dead) , Stack trace (when copying this message, always include the lines below):

2021.06.07 14:18:26.994026 [ 119147 ] {26e89631-b8e0-4d4c-8c26-2c92907292b5} <Error> DynamicQueryHandler: Code: 86, e.displayText() = DB::Exception: Received error from remote server /?connection_string=DSN%3Dgp234&max_block_size=65505. HTTP status code: 500 Internal Server Error, body: ?std::exception. Code: 1001, type: nanodbc::database_error, e.what() = ../contrib/nanodbc/nanodbc/nanodbc.cpp:1625: 08S0: Could not send Query(connection dead);
Could not send Query(connection dead) , Stack trace (when copying this message, always include the lines below):

0. ? @ 0x39c7262 in /usr/bin/clickhouse-odbc-bridge
1. ? @ 0x39c983d in /usr/bin/clickhouse-odbc-bridge
2. ? @ 0x39c8951 in /usr/bin/clickhouse-odbc-bridge
3. ? @ 0x2b33786 in /usr/bin/clickhouse-odbc-bridge
4. ? @ 0x2b2d524 in /usr/bin/clickhouse-odbc-bridge
5. ? @ 0x396b550 in /usr/bin/clickhouse-odbc-bridge
6. ? @ 0x52637af in /usr/bin/clickhouse-odbc-bridge
7. ? @ 0x526521a in /usr/bin/clickhouse-odbc-bridge
8. ? @ 0x5d996b9 in ?
9. ? @ 0x5d9612a in ?
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 21.5.5.12 (official build)), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x879d83a in /usr/bin/clickhouse
1. DB::assertResponseIsOk(Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) @ 0xd5b3da3 in /usr/bin/clickhouse
2. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::call(Poco::URI, Poco::Net::HTTPResponse&) @ 0xd5abcae in /usr/bin/clickhouse
3. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::ReadWriteBufferFromHTTPBase(std::__1::shared_ptr<DB::UpdatableSession>, Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DB::RemoteHostFilter const&) @ 0xd5a8400 in /usr/bin/clickhouse
4. DB::ReadWriteBufferFromHTTP::ReadWriteBufferFromHTTP(Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, DB::ConnectionTimeouts const&, unsigned long, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, DB::RemoteHostFilter const&) @ 0xd5a7bf7 in /usr/bin/clickhouse
5. DB::IStorageURLBase::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf915e1b in /usr/bin/clickhouse
6. DB::StorageXDBC::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf91f3c5 in /usr/bin/clickhouse
7. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xf74b877 in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0xf0ce9e0 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf0c4c94 in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf0c3c7c in /usr/bin/clickhouse
11. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf3e4e9e in /usr/bin/clickhouse
12. DB::InterpreterSelectWithUnionQuery::execute() @ 0xf3e6011 in /usr/bin/clickhouse
13. ? @ 0xf5a2864 in /usr/bin/clickhouse
14. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf5a6375 in /usr/bin/clickhouse
15. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xfd2194f in /usr/bin/clickhouse
16. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xfd25069 in /usr/bin/clickhouse
17. DB::HTTPServerConnection::run() @ 0xfda8ed0 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x1241daef in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x1241f57a in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x12559339 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x1255532a in /usr/bin/clickhouse
22. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
23. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 21.5.5.12 (official build))
```
**ClickHouse Version**
```
ClickHouse client version 21.5.5.12 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.5.5 revision 54448.
```
**ClickHouse Processes**
```
clickho+  14914 10.3  5.3 19487768 861648 ?     Sl   May27 1640:52  \_ /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/cli
clickho+  24590  0.0  0.0      0     0 ?        Z    May27   2:06      \_ [clickhouse-odbc] <defunct>
clickho+   3440  0.0  0.0      0     0 ?        Z    May31   0:00      \_ [clickhouse-odbc] <defunct>
clickho+   3441  0.0  0.0      0     0 ?        Z    May31   0:00      \_ [clickhouse-odbc] <defunct>
clickho+   3442  0.0  0.1 379712 22660 ?        Sl   May31   1:04      \_ /usr/bin/clickhouse-odbc-bridge --http-port 9018 --listen-host 127.0.0.1 --http-timeout 1800000000
```
**Additional context**
mysql odbc postgresql driver is: 
```
# Driver from the postgresql-odbc package
# Setup from the unixODBC package
[PostgreSQL]
Description     = ODBC for PostgreSQL
Driver          = /usr/lib/psqlodbcw.so
Setup           = /usr/lib/libodbcpsqlS.so
Driver64        = /usr/lib64/psqlodbcw.so
Setup64         = /usr/lib64/libodbcpsqlS.so
FileUsage       = 1
```

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/25029.

### CODE REVIEW

File: programs/odbc-bridge/ODBCConnectionFactory.h [hunk 1]
```diff
@@ -50,6 +53,7 @@ namespace DB
 
 static constexpr inline auto ODBC_CONNECT_TIMEOUT = 100;
 static constexpr inline auto ODBC_POOL_WAIT_TIMEOUT = 10000;
+static constexpr auto ODBC_CHECK_CONNECTION_QUERY = "SELECT 1";
```
Comment (filimonov) [inline programs/odbc-bridge/ODBCConnectionFactory.h:56]: Will not work on oracle: `ORA-00923: FROM keyword not found where expected `

**Review by filimonov — CHANGES_REQUESTED** [review]

File: programs/odbc-bridge/ODBCConnectionFactory.h (hunk 1 above)
Comment (filimonov) [reply programs/odbc-bridge/ODBCConnectionFactory.h:56]: Have no idea how to solve it. Most of other databases will complain on Oracle's `SELECT 1 FROM dual`

Making it configurable sounds like overkill.

File: programs/odbc-bridge/ODBCConnectionFactory.h [hunk 2]
```diff
@@ -77,12 +97,15 @@ class ODBCConnectionFactory final : private boost::noncopyable
 
         try
         {
-            if (!connection || !connection->connected())
+            if (!connection || needReconnect(*connection))
```
Comment (filimonov) [inline programs/odbc-bridge/ODBCConnectionFactory.h:100]: Maybe just catch 'no connection' exception during the user's query preparation/execution and reconnect / retry query?

File: programs/odbc-bridge/ODBCConnectionFactory.h [hunk 3]
```diff
@@ -60,6 +64,22 @@ class ODBCConnectionFactory final : private boost::noncopyable
...
+    static bool needReconnect(nanodbc::connection & connection)
+    {
+        try
+        {
+            /// just_execute - execution without preparing any result object.
+            just_execute(connection, ODBC_CHECK_CONNECTION_QUERY);
+        }
+        catch (const nanodbc::database_error &)
+        {
+            return true;
```
Comment (filimonov) [inline programs/odbc-bridge/ODBCConnectionFactory.h:77]: Well, actually it will work :D By reconnecting every time (but it will not the exception you may expect to get :) )

File: programs/odbc-bridge/ODBCConnectionFactory.h (hunk 2 above)
Comment (kssenii) [reply programs/odbc-bridge/ODBCConnectionFactory.h:100]: I doubt it is ok, because there are quite many places where connection is used and it is used not in a uniform way. Adding try catch with reconnect and retry in all those places will look bad..

**Review by alexey-milovidov — APPROVED** [review]
