### PR TITLE
Fix assertion in async read buffer from remote

### LINKED ISSUE #45313: Logical error: 'file_offset_of_buffer_end >= range.left && file_offset_of_buffer_end <= range.right'.
https://s3.amazonaws.com/clickhouse-test-reports/0/e6b3f54842290cbca46808791370b4b13bd9ffde/stress_test__ubsan_.html

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:32:23.151198 [ 207603 ] {3183b529-55dd-4295-9923-a49ce15b896a} <Fatal> : Logical error: 'file_offset_of_buffer_end >= range.left && file_offset_of_buffer_end <= range.right'.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.219553 [ 217797 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.221440 [ 217797 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: 45EB8727E958BE6C75B4269C550B3A08F9FF4BB4) (from thread 207603) (query_id: 3183b529-55dd-4295-9923-a49ce15b896a) (query: SELECT CounterID, count(), max(GoalsReached), min(GoalsReached), minIf(GoalsReached, notEmpty(GoalsReached)) FROM test.hits GROUP BY CounterID ORDER BY count() DESC LIMIT 20;) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.221494 [ 217797 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.221834 [ 217797 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f04cb28e00b 0x7f04cb26d859 0x22021743 0x2cf81996 0x2cf83d72 0x2cf89db1 0x2cf8b2c7 0x2cf8aca5 0x1765c716 0x2cfda8da 0x2cfd9b26 0x2cfd9943 0x2cfde146 0x1765c716 0x17e856b2 0x2cfe34c6 0x2cb32180 0x2f2c212e 0x2f2c7921 0x2f2c7fb3 0x2cdc6e76 0x2f2c6071 0x2f2c494b 0x300882f6 0x3008844b 0x30088e12 0x30093e96 0x30091b37 0x3007d868 0x3007e355 0x3007ac62 0x300afc41 0x2f94b95f 0x2f9736bf 0x2f962e7b 0x2f9644df 0x2212b95a 0x2212f3a4 0x7f04cb445609 0x7f04cb36a133
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.223687 [ 217797 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7f04cb28e00b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.229366 [ 217797 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f04cb26d859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.258375 [ 217797 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x22021743 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.276141 [ 217797 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.276179 [ 217797 ] {} <Fatal> BaseDaemon: 6.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.276200 [ 217797 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:389: DB::CachedOnDiskReadBufferFromFile::getImplementationBuffer(std::__1::shared_ptr<DB::FileSegment>&) @ 0x2cf81996 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.294692 [ 217797 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:499: DB::CachedOnDiskReadBufferFromFile::completeFileSegmentAndGetNext() @ 0x2cf83d72 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.313504 [ 217797 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:677: DB::CachedOnDiskReadBufferFromFile::updateImplementationBufferIfNeeded() @ 0x2cf89db1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.327429 [ 217797 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:0: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x2cf8b2c7 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:18.346491 [ 217797 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:766: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x2cf8aca5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:22.576580 [ 217797 ] {} <Fatal> BaseDaemon: 11. DB::ReadBuffer::next() @ 0x1765c716 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:22.585544 [ 217797 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:0: DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x2cfda8da in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:22.594264 [ 217797 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:148: DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x2cfd9b26 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:22.602896 [ 217797 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:106: DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) @ 0x2cfd9943 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:22.607233 [ 217797 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Disks/IO/ReadIndirectBufferFromRemoteFS.cpp:98: DB::ReadIndirectBufferFromRemoteFS::nextImpl() @ 0x2cfde146 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:23.605032 [ 217797 ] {} <Fatal> BaseDaemon: 16. DB::ReadBuffer::next() @ 0x1765c716 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.714955 [ 217797 ] {} <Fatal> BaseDaemon: 17. DB::ReadBuffer::ignore(unsigned long) @ 0x17e856b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.725628 [ 217797 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/IO/SeekAvoidingReadBuffer.cpp:28: DB::SeekAvoidingReadBuffer::seek(long, int) @ 0x2cfe34c6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.735342 [ 217797 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.746734 [ 217797 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build_docker/../src/IO/BufferBase.h:79: DB::BufferBase::offset() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.746785 [ 217797 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Compression/CompressedReadBufferFromFile.cpp:81: DB::CompressedReadBufferFromFile::seek(unsigned long, unsigned long) @ 0x2cb32180 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.770065 [ 217797 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderStream.cpp:246: DB::MergeTreeReaderStream::seekToMark(unsigned long) @ 0x2f2c212e in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.815081 [ 217797 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:235: DB::getStream(bool, DB::ISerialization::SubstreamPath const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::unique_ptr<DB::MergeTreeReaderStream, std::__1::default_delete<DB::MergeTreeReaderStream>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::unique_ptr<DB::MergeTreeReaderStream, std::__1::default_delete<DB::MergeTreeReaderStream>>>>>&, DB::NameAndTypePair const&, unsigned long, bool, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&) @ 0x2f2c7921 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.849784 [ 217797 ] {} <Fatal> BaseDaemon: 22.1. inlined from ./build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:298: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.849885 [ 217797 ] {} <Fatal> BaseDaemon: 22.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3&>()(std::declval<DB::ISerialization::SubstreamPath const&>())) std::__1::__invoke[abi:v15000]<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3&, DB::ISerialization::SubstreamPath const&>(DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3&, DB::ISerialization::SubstreamPath const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.849994 [ 217797 ] {} <Fatal> BaseDaemon: 22.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:470: DB::ReadBuffer* std::__1::__invoke_void_return_wrapper<DB::ReadBuffer*, false>::__call<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3&, DB::ISerialization::SubstreamPath const&>(DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3&, DB::ISerialization::SubstreamPath const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.850144 [ 217797 ] {} <Fatal> BaseDaemon: 22.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3, DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>::operator()[abi:v15000](DB::ISerialization::SubstreamPath const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.850204 [ 217797 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: DB::ReadBuffer* std::__1::__function::__policy_invoker<DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool)::$_3, DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>>(std::__1::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x2f2c7fb3 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.868574 [ 217797 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/DataTypes/Serializations/ISerialization.cpp:129: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x2cdc6e76 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.893620 [ 217797 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:0: DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, bool) @ 0x2f2c6071 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.919813 [ 217797 ] {} <Fatal> BaseDaemon: 25. ./build_docker/../src/Storages/MergeTree/MergeTreeReaderWide.cpp:111: DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x2f2c494b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:24.959495 [ 217797 ] {} <Fatal> BaseDaemon: 26. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:105: DB::MergeTreeRangeReader::DelayedStream::readRows(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x300882f6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.011986 [ 217797 ] {} <Fatal> BaseDaemon: 27. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:177: DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x3008844b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.048798 [ 217797 ] {} <Fatal> BaseDaemon: 28.1. inlined from ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.h:121: DB::MergeTreeRangeReader::DelayedStream::isFinished() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.072067 [ 217797 ] {} <Fatal> BaseDaemon: 28. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:290: DB::MergeTreeRangeReader::Stream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x30088e12 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.111792 [ 217797 ] {} <Fatal> BaseDaemon: 29. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) @ 0x30093e96 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.153871 [ 217797 ] {} <Fatal> BaseDaemon: 30. ./build_docker/../src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>&) @ 0x30091b37 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.235943 [ 217797 ] {} <Fatal> BaseDaemon: 31. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:404: DB::IMergeTreeSelectAlgorithm::readFromPartImpl() @ 0x3007d868 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.317029 [ 217797 ] {} <Fatal> BaseDaemon: 32. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:447: DB::IMergeTreeSelectAlgorithm::readFromPart() @ 0x3007e355 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.381845 [ 217797 ] {} <Fatal> BaseDaemon: 33. ./build_docker/../src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:224: DB::IMergeTreeSelectAlgorithm::read() @ 0x3007ac62 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.412097 [ 217797 ] {} <Fatal> BaseDaemon: 34. ./build_docker/../src/Storages/MergeTree/MergeTreeSource.cpp:214: DB::MergeTreeSource::tryGenerate() @ 0x300afc41 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.479611 [ 217797 ] {} <Fatal> BaseDaemon: 35.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:344: std::__1::__optional_storage_base<DB::Chunk, false>::has_value[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.479669 [ 217797 ] {} <Fatal> BaseDaemon: 35.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:998: std::__1::optional<DB::Chunk>::operator bool[abi:v15000]() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.479696 [ 217797 ] {} <Fatal> BaseDaemon: 35. ./build_docker/../src/Processors/ISource.cpp:94: DB::ISource::work() @ 0x2f94b95f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.492814 [ 217797 ] {} <Fatal> BaseDaemon: 36.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.502845 [ 217797 ] {} <Fatal> BaseDaemon: 36. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x2f9736bf in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.547194 [ 217797 ] {} <Fatal> BaseDaemon: 37. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2f962e7b in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.583910 [ 217797 ] {} <Fatal> BaseDaemon: 38.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584112 [ 217797 ] {} <Fatal> BaseDaemon: 38.2. inlined from ./build_docker/../base/base/scope_guard.h:99: BasicScopeGuard<DB::PipelineExecutor::spawnThreads()::$_0::operator()() const::'lambda'()>::invoke()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584146 [ 217797 ] {} <Fatal> BaseDaemon: 38.3. inlined from ./build_docker/../base/base/scope_guard.h:48: ~BasicScopeGuard
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584179 [ 217797 ] {} <Fatal> BaseDaemon: 38.4. inlined from ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:328: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584215 [ 217797 ] {} <Fatal> BaseDaemon: 38.5. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584246 [ 217797 ] {} <Fatal> BaseDaemon: 38.6. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584568 [ 217797 ] {} <Fatal> BaseDaemon: 38.7. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584616 [ 217797 ] {} <Fatal> BaseDaemon: 38.8. inlined from ./build_docker/../src/Common/ThreadPool.h:196: operator()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584737 [ 217797 ] {} <Fatal> BaseDaemon: 38.9. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584774 [ 217797 ] {} <Fatal> BaseDaemon: 38.10. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584824 [ 217797 ] {} <Fatal> BaseDaemon: 38.11. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.584867 [ 217797 ] {} <Fatal> BaseDaemon: 38. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x2f9644df in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.604534 [ 217797 ] {} <Fatal> BaseDaemon: 39.1. inlined from ./build_docker/../base/base/strong_typedef.h:23: StrongTypedef<std::__1::integral_constant<bool, true> >
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.604594 [ 217797 ] {} <Fatal> BaseDaemon: 39.2. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.604623 [ 217797 ] {} <Fatal> BaseDaemon: 39. ./build_docker/../src/Common/ThreadPool.cpp:297: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x2212b95a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.630440 [ 217797 ] {} <Fatal> BaseDaemon: 40. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x2212f3a4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.632125 [ 217797 ] {} <Fatal> BaseDaemon: 41. ? @ 0x7f04cb445609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:25.648834 [ 217797 ] {} <Fatal> BaseDaemon: 42. clone @ 0x7f04cb36a133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:33:26.101121 [ 217797 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 426EFA9F43C852D04D1B8214AC12779B)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.14 00:38:14.332650 [ 1581 ] {} <Fatal> Application: Child process was terminated by signal 6.
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.14 00:32:23.151198 [ 207603 ] {3183b529-55dd-4295-9923-a49ce15b896a} <Fatal> : Logical error: 'file_offset_of_buffer_end >= range.left && file_offset_of_buffer_end <= range.right'.
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.14 00:33:18.219553 [ 217797 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.stress.log:2023.01.14 00:33:18.221440 [ 217797 ] {} <Fatal> BaseDaemon: (version 22.13.1.1 (official build), build id: 45EB8727E958BE6C75B4269C550B3A08F9FF4BB4) (from thread 207603) (query_id: 3183b529-55dd-4295-9923-a49ce15b896a) (query: SELECT CounterID, count(), max(GoalsReached), min(GoalsReached), minIf(GoalsReached, notEmpty(GoalsReached)) FROM test.hits GROUP BY CounterID ORDER BY count() DESC LIMIT 20;) Received signal Aborted (6)

```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/45313.

### CODE REVIEW

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp [hunk 1]
```diff
@@ -164,6 +164,8 @@ bool AsynchronousReadIndirectBufferFromRemoteFS::nextImpl()
     if (!hasPendingDataToRead())
         return false;
 
+    assert(file_offset_of_buffer_end <= impl->getFileSize());
```
Comment (SmitaRKulkarni) [inline src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:167]: As discussed, we can add below assert under an if that there are no tasks in threadpool
assert(file_offset_of_buffer_end >= impl->getImplementationBufferOffset());

**Review by SmitaRKulkarni — COMMENTED** [review]
Everything else LGTM

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp [hunk 2]
```diff
@@ -171,8 +171,9 @@ bool AsynchronousReadIndirectBufferFromRemoteFS::nextImpl()
     if (!hasPendingDataToRead())
         return false;
 
-    size_t size, offset;
+    chassert(file_offset_of_buffer_end <= impl->getFileSize());
```
Comment (SmitaRKulkarni) [inline src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:174]: Should we also check the below condition if that there are no tasks in threadpool 
`chassert(file_offset_of_buffer_end >= impl->getImplementationBufferOffset());`
we had discussed this some time back, not sure if it still makes sense to check it here. what do you think?

**Review by SmitaRKulkarni — COMMENTED** [review]
Rest all LGTM

File: src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp (hunk 2 above)
Comment (kssenii) [reply src/Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp:174]: I added it in commit above and the removed it in last commit https://github.com/ClickHouse/ClickHouse/pull/41231/commits/6a02bdc917435eaa32a39955a8e162475974c68e above, because I thought about this assertion more carefully, and concluded that it must be removed because there is the following situation: we cannot add this assertion before checking prefetch_future, because state which we check in this assertion can be concurrently updated, but if we move this assertion after checking the future, then in the case the future is valid, this assert will actually never be true, because `impl->getImplementationBufferOffset()` will actually be ` file_offset_of_buffer_end <= impl->getImplementationBufferOffset()`, but if we check at the future is not valid, then it must be - `file_offset_of_buffer_end == impl->getImplementationBufferOffset()` in case there was no seek, and if there was seek - we cannot compare them at all, because we could also seek backwards or forwards, so adding the assertion will be incorrect as the offset of impl will not be valid after seek.

**Review by SmitaRKulkarni — APPROVED** [review]
