### PR TITLE
Fix revoke with columns

### LINKED ISSUE #74263: Partial revoke with wildcard removes all privileges
---
**Describe the unexpected behaviour**
When attempting a partial revoke (e.g., REVOKE SELECT(column)), using a wildcard in the ON clause (e.g., dev1.*) results in the removal of all privileges for the specified user, instead of just the specified column(s)

This behavior is unexpected and can lead to unintended privilege loss.

---
**How to reproduce**  
1. **ClickHouse versions tested**:  
   - `24.3.5.48.altinityfips`  
   - `24.3.14.35`  
   - `24.8.2.3`  (latest available lts release)

2. **Interface used**: ClickHouse client (`clickhouse-client`).  
3. **Steps**:  
   - Grant `SELECT` on a database:  
     ```sql
     GRANT SELECT ON dev1.* TO dev1;
     ```
   - Verify the grant in `system.grants`:  
     ```sql
     SELECT * FROM system.grants WHERE role_name='dev1';
     ```
     Output:
     ```
     ┌─user_name─┬─role_name─┬─access_type─┬─database─┬─table─┬─column─┬─is_partial_revoke─┬─grant_option─┐
     │ ᴺᵁᴸᴸ      │ dev1      │ SELECT      │ dev1     │ ᴺᵁᴸᴸ  │ ᴺᵁᴸᴸ   │                 0 │            0 │
     └───────────┴───────────┴─────────────┴──────────┴───────┴────────┴───────────────────┴──────────────┘
     ```

   - Revoke partial privileges:  
     ```sql
     REVOKE SELECT(json) ON dev1.* FROM dev1;
     ```
   - Check the `system.grants` table again:  
     ```sql
     SELECT * FROM system.grants WHERE role_name='dev1';
     ```
     Output:
     ```
     Ok.

     0 rows in set. Elapsed: 0.003 sec.  
     ```

---

**Expected behavior**  
When attempting to revoke a partial privilege with a wildcard, one of the following behaviors is expected:
* A warning or notification that all privileges will be removed.
* An exception indicating that the combination of partial revoke and wildcard is not supported or incompatible.
* ..?

Removing all privileges without explicit confirmation or warning can result in unintended privilege loss.

---

**Error message and/or stacktrace**  
No errors or warnings were reported during the `GRANT` or `REVOKE` commands.

---

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Partial revokes with wildcard grants could remove more privileges than expected. Closes https://github.com/ClickHouse/ClickHouse/issues/74263

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Stateful tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Non-blocking CI mode (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit fca25ebaccc693f9348f4cbf8fbd6d837a57b8b1 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74751/fca25ebaccc693f9348f4cbf8fbd6d837a57b8b1/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/f74ed1bca90ccb86e9c7db9aefdbf873a068ced0/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/03141_wildcard_grants.sql [hunk 1]
```diff
@@ -20,5 +20,6 @@ SHOW GRANTS FOR user_03141;
 SELECT '---';
```
Comment (bharatnc) [inline tests/queries/0_stateless/03141_wildcard_grants.sql:20]: `nit:` Should we also have a test case for when the database name empty? `... ON .* TO ...`

**Review by bharatnc — APPROVED** [review]

**Comment by rschu1ze** [comment]
@pufit Could you please provide a human-readable changelog entry? `#74263` doesn't count. Thanks!
