### PR TITLE
fs cache: small optimization

### LINKED ISSUE #55867: FileCache::assertCacheCorrectness() Logical error: entry.size == reserved_size
Report: https://s3.amazonaws.com/clickhouse-test-reports/51692/a4f5e9e045ce8a1617f0a85cb5a5e26afc41022f/stress_test__debug_.html

Backtrace:
```
 [ 492 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by \'forcestop\' command or manually, the possible cause is OOM Killer (see \'dmesg\' and look at the \'/var/log/kern.log\' for the details).
 [ 492 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by \'forcestop\' command or manually, the possible cause is OOM Killer (see \'dmesg\' and look at the \'/var/log/kern.log\' for the details).
 [ 5537 ] {e6767d7d-6343-468d-9823-a9ee422d072d} <Fatal> : Logical error: \'entry.size == reserved_size\'.
 [ 8124 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 8124 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: 00467853E187CB83F443EDCE6AF10BAA6505ADAE, git hash: 4f11fd027084c463a8f4341b272c429ff9e7cc53) (from thread 5537) Received signal 6
 [ 8124 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 8124 ] {} <Fatal> BaseDaemon: 
 [ 8124 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fa5e1f369fc 0x00007fa5e1ee2476 0x00007fa5e1ec87f3 0x0000000013af639e 0x000000001d4c974c 0x000000001d4c961f 0x000000001d4c8e4e 0x000000001d4a373d 0x000000001d4a367d 0x000000001d4a363d 0x000000001d4a35fd 0x000000001d4a35c5 0x000000001d4ef0de 0x00000
 [ 8124 ] {} <Fatal> BaseDaemon: ########################################
 [ 8124 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: 00467853E187CB83F443EDCE6AF10BAA6505ADAE, git hash: 4f11fd027084c463a8f4341b272c429ff9e7cc53) (from thread 5537) (query_id: e6767d7d-6343-468d-9823-a9ee422d072d) (query: SELECT * FROM system.filesystem_cache LIMIT 10000 FORMAT Null) Rece
 [ 8124 ] {} <Fatal> BaseDaemon: 
 [ 8124 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fa5e1f369fc 0x00007fa5e1ee2476 0x00007fa5e1ec87f3 0x0000000013af639e 0x000000001d4c974c 0x000000001d4c961f 0x000000001d4c8e4e 0x000000001d4a373d 0x000000001d4a367d 0x000000001d4a363d 0x000000001d4a35fd 0x000000001d4a35c5 0x000000001d4ef0de 0x00000
 [ 8124 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007fa5e1f369fc in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007fa5e1ee2476 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007fa5e1ec87f3 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 7. /build/src/Common/Exception.cpp:43: DB::abortOnFailedAssertion(String const&) @ 0x0000000013af639e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 8. /build/src/Interpreters/Cache/FileSegment.cpp:779: DB::FileSegment::assertCorrectnessUnlocked(DB::FileSegmentGuard::Lock const&) const::$_0::operator()(std::shared_ptr<DB::IFileCachePriority::IIterator> const&) const @ 0x000000001d4c974c in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 9. /build/src/Interpreters/Cache/FileSegment.cpp:807: DB::FileSegment::assertCorrectnessUnlocked(DB::FileSegmentGuard::Lock const&) const @ 0x000000001d4c961f in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 10. /build/src/Interpreters/Cache/FileSegment.cpp:766: DB::FileSegment::assertCorrectness() const @ 0x000000001d4c8e4e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 11. /build/src/Interpreters/Cache/FileCache.cpp:1158: DB::FileCache::assertCacheCorrectness()::$_0::operator()(DB::LockedKey&) const @ 0x000000001d4a373d in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 12. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::FileCache::assertCacheCorrectness()::$_0&>()(std::declval<DB::LockedKey&>())) std::__invoke[abi:v15000]<DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&>(
 [ 8124 ] {} <Fatal> BaseDaemon: 13. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&>(DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&) @ 0x0000
 [ 8124 ] {} <Fatal> BaseDaemon: 14. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::FileCache::assertCacheCorrectness()::$_0, void (DB::LockedKey&)>::operator()[abi:v15000](DB::LockedKey&) @ 0x000000001d4a35fd in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 15. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void (DB::LockedKey&)>::__call_impl<std::__function::__default_alloc_func<DB::FileCache::assertCacheCorrectness()::$_0, void (DB::LockedKey&)>>(std::__f
 [ 8124 ] {} <Fatal> BaseDaemon: 16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void (DB::LockedKey&)>::operator()[abi:v15000](DB::LockedKey&) const @ 0x000000001d4ef0de in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 17. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void (DB::LockedKey&)>::operator()(DB::LockedKey&) const @ 0x000000001d4e31fd in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 18. /build/src/Interpreters/Cache/Metadata.cpp:253: DB::CacheMetadata::iterate(std::function<void (DB::LockedKey&)>&&) @ 0x000000001d4d869e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 19. /build/src/Interpreters/Cache/FileCache.cpp:1152: DB::FileCache::assertCacheCorrectness() @ 0x000000001d498ed2 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 20. /build/src/Interpreters/Cache/FileCache.cpp:1087: DB::FileCache::getSnapshot() @ 0x000000001d49ca11 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 21. /build/src/Storages/System/StorageSystemFilesystemCache.cpp:47: DB::StorageSystemFilesystemCache::fillData(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, std::shared_ptr<DB::Context const>, DB
 [ 8124 ] {} <Fatal> BaseDaemon: 22. /build/src/Storages/System/IStorageSystemOneBlock.h:65: DB::IStorageSystemOneBlock<DB::StorageSystemFilesystemCache>::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::C
 [ 8124 ] {} <Fatal> BaseDaemon: 23. /build/src/Storages/IStorage.cpp:144: DB::IStorage::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, uns
 [ 8124 ] {} <Fatal> BaseDaemon: 24. /build/src/Interpreters/InterpreterSelectQuery.cpp:2565: DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x000000001ce3d9ef in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 25. /build/src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x000000001ce3612a in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 26. /build/src/Interpreters/InterpreterSelectQuery.cpp:933: DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x000000001ce3527d in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 27. /build/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:303: DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x000000001cf57834 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 28. /build/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:377: DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000001cf58380 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 29. /build/src/Interpreters/executeQuery.cpp:1098: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001d452e6a in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 30. /build/src/Interpreters/executeQuery.cpp:1243: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x000000001d44e044 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 31. /build/src/Server/TCPHandler.cpp:500: DB::TCPHandler::runImpl() @ 0x000000001e9ae70d in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 32. /build/src/Server/TCPHandler.cpp:2192: DB::TCPHandler::run() @ 0x000000001e9c13a5 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 33. /build/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x0000000024d71b39 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 34. /build/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000024d7239c in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 35. /build/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000024f5d4b4 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 36. /build/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x0000000024f5a25a in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 37. /build/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000024f58f9e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 38. ? @ 0x00007fa5e1f34ac3 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 39. ? @ 0x00007fa5e1fc6a40 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
 [ 8124 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
 [ 8124 ] {} <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 2952919, max_compress_block_size = 619188, max_block_size = 8391, max_insert_threads = 10, max_read_buffer_size = 544771, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 3000, idle_connect
 [ 2133 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 5537 ] {e6767d7d-6343-468d-9823-a9ee422d072d} <Fatal> : Logical error: \'entry.size == reserved_size\'.
 [ 8124 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
 [ 8124 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: 00467853E187CB83F443EDCE6AF10BAA6505ADAE, git hash: 4f11fd027084c463a8f4341b272c429ff9e7cc53) (from thread 5537) Received signal 6
 [ 8124 ] {} <Fatal> BaseDaemon: Signal description: Aborted
 [ 8124 ] {} <Fatal> BaseDaemon: 
 [ 8124 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fa5e1f369fc 0x00007fa5e1ee2476 0x00007fa5e1ec87f3 0x0000000013af639e 0x000000001d4c974c 0x000000001d4c961f 0x000000001d4c8e4e 0x000000001d4a373d 0x000000001d4a367d 0x000000001d4a363d 0x000000001d4a35fd 0x000000001d4a35c5 0x000000001d4ef0de 0x00000
 [ 8124 ] {} <Fatal> BaseDaemon: ########################################
 [ 8124 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: 00467853E187CB83F443EDCE6AF10BAA6505ADAE, git hash: 4f11fd027084c463a8f4341b272c429ff9e7cc53) (from thread 5537) (query_id: e6767d7d-6343-468d-9823-a9ee422d072d) (query: SELECT * FROM system.filesystem_cache LIMIT 10000 FORMAT Null) Rece
 [ 8124 ] {} <Fatal> BaseDaemon: 
 [ 8124 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fa5e1f369fc 0x00007fa5e1ee2476 0x00007fa5e1ec87f3 0x0000000013af639e 0x000000001d4c974c 0x000000001d4c961f 0x000000001d4c8e4e 0x000000001d4a373d 0x000000001d4a367d 0x000000001d4a363d 0x000000001d4a35fd 0x000000001d4a35c5 0x000000001d4ef0de 0x00000
 [ 8124 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007fa5e1f369fc in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007fa5e1ee2476 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007fa5e1ec87f3 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 7. /build/src/Common/Exception.cpp:43: DB::abortOnFailedAssertion(String const&) @ 0x0000000013af639e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 8. /build/src/Interpreters/Cache/FileSegment.cpp:779: DB::FileSegment::assertCorrectnessUnlocked(DB::FileSegmentGuard::Lock const&) const::$_0::operator()(std::shared_ptr<DB::IFileCachePriority::IIterator> const&) const @ 0x000000001d4c974c in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 9. /build/src/Interpreters/Cache/FileSegment.cpp:807: DB::FileSegment::assertCorrectnessUnlocked(DB::FileSegmentGuard::Lock const&) const @ 0x000000001d4c961f in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 10. /build/src/Interpreters/Cache/FileSegment.cpp:766: DB::FileSegment::assertCorrectness() const @ 0x000000001d4c8e4e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 11. /build/src/Interpreters/Cache/FileCache.cpp:1158: DB::FileCache::assertCacheCorrectness()::$_0::operator()(DB::LockedKey&) const @ 0x000000001d4a373d in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 12. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::FileCache::assertCacheCorrectness()::$_0&>()(std::declval<DB::LockedKey&>())) std::__invoke[abi:v15000]<DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&>(
 [ 8124 ] {} <Fatal> BaseDaemon: 13. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&>(DB::FileCache::assertCacheCorrectness()::$_0&, DB::LockedKey&) @ 0x0000
 [ 8124 ] {} <Fatal> BaseDaemon: 14. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::FileCache::assertCacheCorrectness()::$_0, void (DB::LockedKey&)>::operator()[abi:v15000](DB::LockedKey&) @ 0x000000001d4a35fd in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 15. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void (DB::LockedKey&)>::__call_impl<std::__function::__default_alloc_func<DB::FileCache::assertCacheCorrectness()::$_0, void (DB::LockedKey&)>>(std::__f
 [ 8124 ] {} <Fatal> BaseDaemon: 16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void (DB::LockedKey&)>::operator()[abi:v15000](DB::LockedKey&) const @ 0x000000001d4ef0de in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 17. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void (DB::LockedKey&)>::operator()(DB::LockedKey&) const @ 0x000000001d4e31fd in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 18. /build/src/Interpreters/Cache/Metadata.cpp:253: DB::CacheMetadata::iterate(std::function<void (DB::LockedKey&)>&&) @ 0x000000001d4d869e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 19. /build/src/Interpreters/Cache/FileCache.cpp:1152: DB::FileCache::assertCacheCorrectness() @ 0x000000001d498ed2 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 20. /build/src/Interpreters/Cache/FileCache.cpp:1087: DB::FileCache::getSnapshot() @ 0x000000001d49ca11 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 21. /build/src/Storages/System/StorageSystemFilesystemCache.cpp:47: DB::StorageSystemFilesystemCache::fillData(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, std::shared_ptr<DB::Context const>, DB
 [ 8124 ] {} <Fatal> BaseDaemon: 22. /build/src/Storages/System/IStorageSystemOneBlock.h:65: DB::IStorageSystemOneBlock<DB::StorageSystemFilesystemCache>::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::C
 [ 8124 ] {} <Fatal> BaseDaemon: 23. /build/src/Storages/IStorage.cpp:144: DB::IStorage::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, uns
 [ 8124 ] {} <Fatal> BaseDaemon: 24. /build/src/Interpreters/InterpreterSelectQuery.cpp:2565: DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x000000001ce3d9ef in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 25. /build/src/Interpreters/InterpreterSelectQuery.cpp:0: DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x000000001ce3612a in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 26. /build/src/Interpreters/InterpreterSelectQuery.cpp:933: DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x000000001ce3527d in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 27. /build/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:303: DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x000000001cf57834 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 28. /build/src/Interpreters/InterpreterSelectWithUnionQuery.cpp:377: DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000001cf58380 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 29. /build/src/Interpreters/executeQuery.cpp:1098: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001d452e6a in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 30. /build/src/Interpreters/executeQuery.cpp:1243: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x000000001d44e044 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 31. /build/src/Server/TCPHandler.cpp:500: DB::TCPHandler::runImpl() @ 0x000000001e9ae70d in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 32. /build/src/Server/TCPHandler.cpp:2192: DB::TCPHandler::run() @ 0x000000001e9c13a5 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 33. /build/base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x0000000024d71b39 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 34. /build/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000024d7239c in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 35. /build/base/poco/Foundation/src/ThreadPool.cpp:188: Poco::PooledThread::run() @ 0x0000000024f5d4b4 in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 36. /build/base/poco/Foundation/src/Thread.cpp:46: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x0000000024f5a25a in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 37. /build/base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000024f58f9e in /usr/bin/clickhouse
 [ 8124 ] {} <Fatal> BaseDaemon: 38. ? @ 0x00007fa5e1f34ac3 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: 39. ? @ 0x00007fa5e1fc6a40 in ?
 [ 8124 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
 [ 8124 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
```

The query: `SELECT * FROM system.filesystem_cache LIMIT 10000 FORMAT Null`

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/55867.

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 2801c0ffd597510c3e669041ab0bfab84b2237ea with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57615/2801c0ffd597510c3e669041ab0bfab84b2237ea/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7128094643">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57615/2801c0ffd597510c3e669041ab0bfab84b2237ea/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Interpreters/Cache/Metadata.cpp [hunk 1]
```diff
@@ -938,8 +938,18 @@ KeyMetadata::iterator LockedKey::removeFileSegmentImpl(
...
+            /// FIXME: For temporary file segment the requirement is not as strong because
+            /// the implementation of "temporary data in cache" creates files in advance.
+            if (fs::exists(path))
+                fs::remove(path);
+        }
+        else if (file_segment->downloaded_size == 0)
+        {
+            chassert(!fs::exists(path));
+        }
+        else if (fs::exists(path))
```
Comment (kssenii) [inline src/Interpreters/Cache/Metadata.cpp:952]: The point of this PR is not to do `fs::exists` check unconditionally, but only if `downloaded_size == 0`.

File: src/Interpreters/Cache/FileSegment.cpp [hunk 2]
```diff
@@ -781,21 +795,42 @@ bool FileSegment::assertCorrectness() const
...
+    auto check_iterator = [&](const Priority::IteratorPtr & it)
     {
         UNUSED(this);
         if (!it)
             return;
 
         const auto & entry = it->getEntry();
-        UNUSED(entry);
-        chassert(entry->size == reserved_size);
+        if (download_state != State::DOWNLOADING && entry->size != reserved_size)
```
Comment (kssenii) [inline src/Interpreters/Cache/FileSegment.cpp:812]: This additional check for downloaded state fixes https://github.com/ClickHouse/ClickHouse/issues/55867.

**Comment by kssenii** [comment]
> Upgrade check (asan) 
Upgrade check (debug) 

https://github.com/ClickHouse/ClickHouse/issues/58319

File: src/Interpreters/Cache/FileSegment.cpp [hunk 3]
```diff
@@ -339,30 +339,31 @@ void FileSegment::write(const char * from, size_t size, size_t offset)
...
     {
         auto lock = lockFileSegment();
-
         assertIsDownloaderUnlocked("write", lock);
         assertNotDetachedUnlocked(lock);
+    }
+
+    const auto file_segment_path = getPath();
 
+    {
```
Comment (nickitat) [inline src/Interpreters/Cache/FileSegment.cpp:350]: why this block (l. 351-379) in indented btw?

File: src/Interpreters/Cache/FileSegment.cpp (hunk 2 above)
Comment (nickitat) [reply src/Interpreters/Cache/FileSegment.cpp:812]: just for my information, why it cannot be e.g. `PARTIALLY_DOWNLOADED_NO_CONTINUATION`?

File: src/Interpreters/Cache/Metadata.cpp (hunk 1 above)
Comment (nickitat) [reply src/Interpreters/Cache/Metadata.cpp:952]: > The point of this PR is not to do `fs::exists` check unconditionally, but only if `downloaded_size == 0`.

you mean `!=`?

Comment (kssenii) [reply src/Interpreters/Cache/Metadata.cpp:952]: Oops, yes, typo

File: src/Interpreters/Cache/FileSegment.cpp (hunk 2 above)
Comment (kssenii) [reply src/Interpreters/Cache/FileSegment.cpp:812]: In `tryReserve` we first update `entry->size` and right after `reserved_size`, which is done under cache lock (which is priority queue lock). But here in `assertCacheCorrectness` this lock is not taken, so it can see `entry->size != reserved_size`. As `tryReserve` is executing while file segment has `DOWNLOADING` state, therefore I added this check. `PARTIALLY_DOWNLOADED_NO_CONTINUATION` does not apply to the described case.

File: src/Interpreters/Cache/FileSegment.cpp (hunk 3 above)
Comment (kssenii) [reply src/Interpreters/Cache/FileSegment.cpp:350]: For readability (in my opinion). This block contains only safety & correctness checks and it seemed to look good to somehow visualize it separately.. if it makes sense..

**Review by nickitat — APPROVED** [review]
