### PR TITLE
Import `FROM INFILE`

### LINKED ISSUE #22054: insert from file for temporary tables
It is possible to insert data from file using clickhouse-client:
`clickhouse-client ... --query 'insert into mytable format CSV < data.csv`

But for temporary tables it is not working because temporary tables are not visible in other sessions.

I suggest to allow 'insert' from file within clickhouse-client session, like select does (select into outfile '...').
For example:
`insert into mytable format CSV fromfile 'data.csv'`

### PR DESCRIPTION
**Pull request by FArthur-cmd**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Add `FROM INFILE` command.

Detailed description / Documentation draft:
Now it is available to import data in table from files.

**Example**
```sql
INSERT INTO TABLE table_name FROM INFILE file_name;
```

Data from `file_name` will be send to `table_name`. If file was compressed using one of supported by ClickHouse algorithms of compression, it's data will be extracted and send to server.

### CODE REVIEW

File: programs/client/Client.cpp [hunk 1]
```diff
@@ -1894,7 +1895,24 @@ class Client : public Poco::Util::Application
...
+
+            auto in_buffer = wrapReadBufferWithCompressionMethod(std::make_unique<ReadBufferFromFile>(in_file), chooseCompressionMethod(in_file, ""));
+
+            try
+            {
+                sendDataFrom(*in_buffer, sample, columns_description);
+            }
+            catch (Exception & e)
+            {
+                e.addMessage("data for INSERT was parsed from query");
```
Comment (tavplubix) [inline programs/client/Client.cpp:1911]:
```suggestion
                e.addMessage("data for INSERT was parsed from file");
```

File: src/Parsers/ASTInsertQuery.cpp [hunk 2]
```diff
@@ -48,11 +49,15 @@ void ASTInsertQuery::formatImpl(const FormatSettings & settings, FormatState & s
...
+        if (infile)
+        {
+            settings.ostr << (settings.hilite ? hilite_keyword : "") << " FROM INFILE " << (settings.hilite ? hilite_none : "") << infile->as<ASTLiteral &>().value.safeGet<std::string>();
+        }
         if (!format.empty())
         {
             settings.ostr << (settings.hilite ? hilite_keyword : "") << " FORMAT " << (settings.hilite ? hilite_none : "") << format;
         }
-        else
+        else if (!infile)
```
Comment (tavplubix) [inline src/Parsers/ASTInsertQuery.cpp:60]: What will happen on queries like `INSERT INTO test FROM INFILE 'some_values' VALUES ('another', 'values')`? 
We should not allow queries with both `INFILE` and data for insert.

Comment (tavplubix) [reply src/Parsers/ASTInsertQuery.cpp:60]: Ok, I see that we will fail to parse such query

File: src/Parsers/ParserInsertQuery.cpp [hunk 3]
```diff
@@ -86,11 +90,17 @@ bool ParserInsertQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expected)
...
     if (s_values.ignore(pos, expected))
     {
         data = pos->begin;
     }
+    else if (s_from_infile.ignore(pos, expected))
+    {
+        if (!infile_name_p.parse(pos, infile, expected))
+            return false;
+    }
     else if (s_format.ignore(pos, expected))
```
Comment (tavplubix) [inline src/Parsers/ParserInsertQuery.cpp:104]: How to specify format of file?

**Comment by tavplubix** [comment]
If we send `INSERT ... FROM INFILE` query directly to server (through http or grpc interface), then server will just ignore it. Maybe throw some exception?

File: src/Processors/Transforms/getSourceFromFromASTInsertQuery.cpp [hunk 4]
```diff
@@ -35,6 +35,9 @@ Pipe getSourceFromFromASTInsertQuery(
     if (!ast_insert_query)
         throw Exception("Logical error: query requires data to insert, but it is not INSERT query", ErrorCodes::LOGICAL_ERROR);
 
+    if (ast_insert_query->infile)
+        throw Exception("Logical error: query has infile and was send directly to server", ErrorCodes::LOGICAL_ERROR);
```
Comment (tavplubix) [inline src/Processors/Transforms/getSourceFromFromASTInsertQuery.cpp:39]: It's not a logical error. `LOGICAL_ERROR` is a special error code for exceptions that may happen only if some invariant is broken due to bug in code. It works as ordinary exception in release builds and as assertion in debug builds. 

Btw, could you please add a test that sends query with `FROM INFILE` to http interface? Test with clickhouse-local will be also useful. It's ok to add them into `02009_from_infile.sh`, search for `${CLICKHOUSE_CURL}` and `${CLICKHOUSE_LOCAL}` in functional tests if you need examples.

File: tests/queries/0_stateless/02009_from_infile.sh [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+gzip "${CLICKHOUSE_TMP}"/test_infile
+
+${CLICKHOUSE_CLIENT} --query "DROP TABLE IF EXISTS test_infile;"
+${CLICKHOUSE_CLIENT} --query "CREATE TABLE test_infile (word String) ENGINE=Memory();"
+${CLICKHOUSE_CLIENT} --query "INSERT INTO test_infile FROM INFILE '${CLICKHOUSE_TMP}/test_infile.gz' FORMAT CSV;"
+${CLICKHOUSE_CLIENT} --query "SELECT * FROM test_infile;"
+
+# if it not fails, select will print information
+${CLICKHOUSE_LOCAL} --query "CREATE TABLE test_infile (word String) ENGINE=Memory(); INSERT INTO test_infile FROM INFILE '${CLICKHOUSE_TMP}/test_infile.gz' FORMAT CSV; SELECT * from test_infile;" 2>&1  | grep -q "UNKNOWN_TYPE_OF_QUERY" && echo "Correct Local" || echo 'Fail'
```
Comment (tavplubix) [inline tests/queries/0_stateless/02009_from_infile.sh:22]: Maybe it should work with clickhouse-local. We do not allow to execute queries like `FROM INFILE` on clickhouse-server, because it's possible to read/write arbitrary files on server-side using such queries. But there are no reasons to disable such queries in clickhouse-local.

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Looks like Style Check works incorrectly
