### PR TITLE
Don't delete default rows in coalescing merge tree

### LINKED ISSUE #81303: CoalescingMergeTree is unable to store default values, like zeros or empty strings
### Company or project name

https://www.innervate.com/

### Describe the unexpected behaviour

From my POV a new CoalescingMergeTree behaves unexpectedly with default values, at least it should be documented.

```sql
CREATE TABLE test_table
(
    key UInt32,
    A UInt32,
    B String
)
ENGINE = CoalescingMergeTree()
ORDER BY key;

INSERT INTO test_table Values(1,0, '');

SELECT count() FROM test_table;
   +-count()-+
1. |       0 |  ---<<<<--- I expect 1 here
   +---------+


drop table test_table;

CREATE TABLE test_table
(
    key UInt32,
    A Nullable(UInt32),
    B Nullable(String)
)
ENGINE = CoalescingMergeTree()
ORDER BY key;

INSERT INTO test_table Values(1, Null, '');

SELECT count() FROM test_table;
   +-count()-+
1. |       0 |  ---<<<<--- I expect 1 here
   +---------+
```

### Which ClickHouse versions are affected?

head

### How to reproduce

https://fiddle.clickhouse.com/817ad0bc-4c95-4211-a089-e3cfb8e093c0

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
This closes https://github.com/ClickHouse/ClickHouse/issues/81303

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by UnamedRus** [comment]
For SummingMergeTree it was kinda intended and expected behavior, not sure that we should change it in such way.

**Comment by den-crane** [comment]
@scanhex12 what about this

```
CREATE TABLE test_table
(
    key UInt32,
    A Nullable(UInt32),
    B Nullable(String)
)
ENGINE = CoalescingMergeTree()
ORDER BY key;

INSERT INTO test_table Values(1, 1,  'x');
SELECT * FROM test_table final;
   +-key-+-A-+-B-+
1. |   1 | 1 | x |
   +-----+---+---+

INSERT INTO test_table Values(1, 2,  'y');
SELECT * FROM test_table final;
   +-key-+-A-+-B-+
1. |   1 | 2 | x |                               -----<<<--- expected 'y'
   +-----+---+---+

INSERT INTO test_table Values(1, 3,  'z');
SELECT * FROM test_table final;
   +-key-+-A-+-B-+
1. |   1 | 3 | x |                               -----<<<--- expected 'z'
   +-----+---+---+

```

https://fiddle.clickhouse.com/16be1755-560e-44f0-be6f-9220bad086f5

**Comment by den-crane** [comment]
Also the documentation is very vague about requirements of Nullable columns and about a behaviour without  Nullable types.

Examples are misleading

```
CREATE TABLE test_table
(
    key UInt32,
    value UInt32
)
ENGINE = CoalescingMergeTree()
ORDER BY key

INSERT INTO test_table VALUES(1,NULL)      -- in reality Null will be converted to 0 by the insert.
```

I would expect different results:

```
CREATE TABLE test_table
(
    key UInt32,
    value UInt32
)
ENGINE = CoalescingMergeTree()
ORDER BY key;

INSERT INTO test_table VALUES(1,6);   
INSERT INTO test_table VALUES(1,NULL); 

select * from test_table final;
┌─key─┬─value─┐
│   1 │     0 │
└─────┴───────┘


CREATE TABLE test_table
(
    key UInt32,
    value Nullable(UInt32)
)
ENGINE = CoalescingMergeTree()
ORDER BY key;

INSERT INTO test_table VALUES(1,6);   
INSERT INTO test_table VALUES(1,NULL); 

select * from test_table final;
┌─key─┬─value─┐
│   1 │     6 │
└─────┴───────┘
```

**Comment by jkartseva** [comment]
I think that the results should be consistent with the `coalesce` function:
```
ip-172-31-8-86.us-west-1.compute.internal :) select coalesce(6, NULL)

SELECT coalesce(6, NULL)

Query id: 20164203-d7bb-4817-bde9-428a66e0a563

   ┌─coalesce(6, NULL)─┐
1. │                 6 │
   └───────────────────┘

1 row in set. Elapsed: 0.002 sec.

ip-172-31-8-86.us-west-1.compute.internal :)
```
(with the difference that the latest is used instead of the leftmost)

**Comment by jkartseva** [comment]
The behavior is different depending on whether the data is inserted in a single batch or not: https://pastila.nl/?02fba128/cc7bbde5979bde7d70370afe6644caf3#oD+cHhOAh/vr4virt1xzHg==

**Comment by den-crane** [comment]
One more example.
I would expect similar behavior (at least it's a desired behavior of an upsert) from `AggregatingMergeTree+SimpleAggregateFunction(anyLast` and `CoalescingMergeTree`

https://fiddle.clickhouse.com/3a33d254-c620-4401-acbf-a246cdcc4949

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/84015

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/84116

**Comment by timxian** [comment]
May I know when this fix will be released?

**Comment by scanhex12** [comment]
@timxian @jkartseva @den-crane I added all your cases and updated the documentation, now everything should work. Please check.

File: src/Processors/Merges/Algorithms/SummingSortedAlgorithm.h [hunk 1]
```diff
@@ -25,7 +25,10 @@ class SummingSortedAlgorithm final : public IMergingAlgorithmWithDelayedChunk
         const Names & partition_and_sorting_required_columns,
         size_t max_block_size_rows,
         size_t max_block_size_bytes,
-        const String & sum_function_name);
+        const String & sum_function_name,
+        const String & sum_function_map_name,
+        bool remove_default_values,
+        bool aggregate_all_columns);
```
Comment (jkartseva) [inline src/Processors/Merges/Algorithms/SummingSortedAlgorithm.h:31]: nit: (false, false) and (true, true) combinations are not used, so that a single boolean value would cover all use cases; but, it's okay to leave it as is for readability.

File: src/Processors/Merges/CoalescingSortedTransform.h [hunk 2]
```diff
@@ -32,7 +32,10 @@ class CoalescingSortedTransform final : public IMergingTransform<SummingSortedAl
             partition_key_columns,
             max_block_size_rows,
             max_block_size_bytes,
-            "last_value")
+            "last_value",
+            "last_value",
+            false,
+            true)
```
Comment (jkartseva) [inline src/Processors/Merges/CoalescingSortedTransform.h]:
```
/*remove_default_values*/ false,
/*aggregate_all_columns*/ true
```

File: tests/queries/0_stateless/03566_one_row_summing_merge_tree.sql [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+    last_update DateTime64 Materialized now64(), -- optional (used with argMax)
+    battery_level Nullable(UInt8), -- in %
+    lat Nullable(Float64), -- latitude (°)
+    lon Nullable(Float64), -- longitude (°)
+    firmware_version Nullable(String),
+    cabin_temperature Nullable(Float32), -- in °C
+    speed_kmh Nullable(Float32) -- from sensor
+)
+ENGINE = CoalescingMergeTree
+ORDER BY vin;
```
Comment (jkartseva) [inline tests/queries/0_stateless/03566_one_row_summing_merge_tree.sql:139]: 👍

File: tests/queries/0_stateless/03566_one_row_summing_merge_tree.sql [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+
+select '\n\n -- CoalescingMergeTree --\n' format TSVRaw;
+
+drop table test_table;
+CREATE TABLE test_table
+(
+    key UInt32,
+    A Nullable(Int64),  
+    B Nullable(DateTime),
+    C Nullable(String),
```
Comment (jkartseva) [inline tests/queries/0_stateless/03566_one_row_summing_merge_tree.sql:106]: Please test a column of a composite type, for example, `D Variant(Array(UInt32), Nothing)` from https://github.com/ClickHouse/ClickHouse/issues/84015

**Review by jkartseva — APPROVED** [review]
Looks good.

**Comment by bharatnc** [comment]
@scanhex12 I'll add a backport for this bug-fix so that it can be fixed in `v25.6` and later (when CoalescingMergeTree seems to be first available).
