### PR TITLE
Fix aggregate projections with normalized states

### LINKED ISSUE #54406: Projection issue Block structure mismatch in AggregatingStep stream
worked with 22.8: https://fiddle.clickhouse.com/bba44076-1961-4356-b59c-df7e26362245
fails with 23.3: https://fiddle.clickhouse.com/731c266b-df63-437e-ac64-05a36422ad36

```sql
CREATE TABLE r (
     x String,
     a LowCardinality(String),
     q AggregateFunction(quantilesTiming(0.5, 0.95, 0.99), Int64),
     s Int64,
     PROJECTION p 
         (SELECT a, quantilesTimingMerge(0.5, 0.95, 0.99)(q), sum(s) GROUP BY a)
) Engine=SummingMergeTree order by (x,   a);

insert into r 
select number%100 x,
       'x' a, 
       quantilesTimingState(0.5, 0.95, 0.99)(number::Int64) q, 
       sum(1) s
from numbers(1000)
group by x,a;

SELECT 
       ifNotFinite(quantilesTimingMerge(0.95)(q)[1],0) as d1, 
       ifNotFinite(quantilesTimingMerge(0.99)(q)[1],0) as d2,
       ifNotFinite(quantilesTimingMerge(0.50)(q)[1],0) as d3,
       sum(s)
FROM cluster('test_cluster_two_shards', default, r)
WHERE a = 'x' 
settings prefer_localhost_replica=0
format PrettyCompact;


DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Block structure mismatch in AggregatingStep stream: different types:
quantilesTimingMerge(0.99)(q) 
```

WA: disable projection (`allow_experimental_projection_optimization=0`)
https://fiddle.clickhouse.com/89156fe6-169d-444b-a8ab-4c07781d7d11

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect aggregation projection optimization when using variant aggregate states. This optimization is accidentally enabled but not properly implemented, because after https://github.com/ClickHouse/ClickHouse/pull/39420 the comparison of DataTypeAggregateFunction is normalized. This fixes #54406

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit 8804159a4a0ef650674a4f91dea3572a193b8252 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54480/8804159a4a0ef650674a4f91dea3572a193b8252/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by amosbird** [comment]
> Stateless tests (debug) [3/5] — fail: 2, passed: 1149, skipped: 23

1. mutations_and_errors_zookeeper  is listed in https://github.com/ClickHouse/ClickHouse/issues/14414 
2. lz4_compression_bug  is just too slow to run

File: src/Functions/FunctionsConversion.h [hunk 1]
```diff
@@ -3188,14 +3189,40 @@ class FunctionCast final : public FunctionCastBase
...
+        else if (const auto * agg_type = checkAndGetDataType<DataTypeAggregateFunction>(from_type_untyped.get()))
         {
-            if (cast_type == CastType::accurateOrNull)
-                return createToNullableColumnWrapper();
-            else
-                throw Exception(ErrorCodes::CANNOT_CONVERT_TYPE, "Conversion from {} to {} is not supported",
-                    from_type_untyped->getName(), to_type->getName());
+            if (agg_type->getFunction()->haveSameStateRepresentation(*to_type->getFunction()))
+            {
+                return [agg_type](
```
Comment (KochetovNicolai) [inline src/Functions/FunctionsConversion.h:3196]: Looks like we capture raw pointer here. Looks a bit dangerous.
Let's capture `from_type_untyped` by value and use `assert_case` in lambda.

File: src/Processors/QueryPlan/Optimizations/optimizeUseAggregateProjection.cpp [hunk 2]
```diff
@@ -249,12 +249,17 @@ static void appendAggregateFunctions(
...
 
         const auto * node = input;
 
         if (node->result_name != aggregate.column_name)
-            node = &proj_dag.addAlias(*node, aggregate.column_name);
+        {
+            /// Always cast to aggregate types specified in query, because input
+            /// columns from projection might have the same state but different
+            /// type, which can generate wrong results during finalization.
+            node = &proj_dag.addCast(*node, type, aggregate.column_name);
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/Optimizations/optimizeUseAggregateProjection.cpp:261]: It is almost ok, but can we check that the types are different separately?
I think it may be possible that types are equals, but names are different.
Can we add `cast` only if types are different, and `alias` only if names are different?

**Review by KochetovNicolai — COMMENTED** [review]
Generally looks good.

File: src/Functions/FunctionsConversion.h (hunk 1 above)
Comment (amosbird) [reply src/Functions/FunctionsConversion.h:3196]: Ah yes. I think it's better to capture `agg_type->getFunction()` directly.

File: src/Processors/QueryPlan/Optimizations/optimizeUseAggregateProjection.cpp (hunk 2 above)
Comment (amosbird) [reply src/Processors/QueryPlan/Optimizations/optimizeUseAggregateProjection.cpp:261]: Hmm, I don't think it's possible after #39420 , otherwise we need a different `equals` method for DataTypeAggregateFunction

**Review by KochetovNicolai — APPROVED** [review]
