### PR TITLE
Fix nullable processing in JSONFunctions

### LINKED ISSUE #29615: UBSan: downcast of address which does not point to an object of type 'DB::ColumnString'
https://clickhouse-test-reports.s3.yandex.net/0/d72e10367f53b3afce931b36bb97dba147df66f3/fuzzer_ubsan/report.html#fail1

```
2021.10.01 13:26:54.807229 [ 93 ] {1873cc6b-5522-44a8-9a71-46974ec369c4} <Debug> executeQuery: (from [::1]:57302) SELECT DISTINCT JSONExtractRaw(concat('{"x":', if(rand() % 2, 'true', NULL), '}'), 'x') AS res FROM numbers(1000000) ORDER BY res DESC
2021.10.01 13:26:54.807492 [ 93 ] {1873cc6b-5522-44a8-9a71-46974ec369c4} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2021.10.01 13:26:54.808582 [ 93 ] {1873cc6b-5522-44a8-9a71-46974ec369c4} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
../src/Common/assert_cast.h:50:12: runtime error: downcast of address 0x7f98fc020f10 which does not point to an object of type 'DB::ColumnString'
0x7f98fc020f10: note: object is of type 'DB::ColumnNullable'
 00 00 00 00  68 05 1b 08 00 00 00 00  01 00 00 00 00 00 00 00  00 18 08 8b a3 7f 00 00  60 17 02 fc
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'DB::ColumnNullable'
2021.10.01 13:26:56.116739 [ 276 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 43.48 GiB, peak 51.86 GiB, will set to 43.48 GiB (RSS), difference: 3.06 MiB
2021.10.01 13:26:56.126913 [ 133 ] {} <Trace> SystemLog (system.query_log): Flushing system log, 22 entries to flush up to offset 49296
2021.10.01 13:26:56.134198 [ 133 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.10.01 13:26:56.136818 [ 133 ] {} <Trace> system.query_log (4aec61c0-5a6c-4ca6-8aec-61c05a6ccca6): Renaming temporary part tmp_insert_202110_56_56_0 to 202110_56_56_0.
2021.10.01 13:26:56.137275 [ 133 ] {} <Trace> SystemLog (system.query_log): Flushed system log up to offset 49296
2021.10.01 13:26:56.826849 [ 91 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #1
2021.10.01 13:26:57.670438 [ 140 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 7644 entries to flush up to offset 598892
2021.10.01 13:26:57.675742 [ 140 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.10.01 13:26:57.677355 [ 140 ] {} <Trace> system.asynchronous_metric_log (040e9ccf-59fa-4b62-840e-9ccf59fafb62): Renaming temporary part tmp_insert_202110_67_67_0 to 202110_67_67_0.
2021.10.01 13:26:57.677584 [ 140 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 598892
    #0 0x11ecc56b in DB::JSONExtractRawImpl<DB::SimdJSONParser>::insertResultToColumn(DB::IColumn&, DB::SimdJSONParser::Element const&, std::__1::basic_string_view<char, std::__1::char_traits<char> > const&) (/workspace/clickhouse+0x11ecc56b)
    #1 0x11eea89f in DB::FunctionJSONHelpers::Executor<DB::NameJSONExtractRaw, DB::JSONExtractRawImpl, DB::SimdJSONParser>::run(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) (/workspace/clickhouse+0x11eea89f)
    #2 0x11eea1e8 in DB::ExecutableFunctionJSON<DB::NameJSONExtractRaw, DB::JSONExtractRawImpl>::chooseAndRunJSONParser(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x11eea1e8)
    #3 0x11ee9f55 in DB::ExecutableFunctionJSON<DB::NameJSONExtractRaw, DB::JSONExtractRawImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x11ee9f55)
    #4 0x1a61d1b4 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:217:15
    #5 0x1a61df2b in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:260:22
    #6 0x1ad9e60d in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:601:60
    #7 0x1ad9c6c1 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:718:13
    #8 0x1c6b43c5 in DB::ExpressionTransform::transform(DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #9 0x171745aa in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:37:9
    #10 0x1c39f80c in DB::ISimpleTransform::work() obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89:9
    #11 0x1c3f7d58 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:88:20
    #12 0x1c3f7c46 in DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:105:13
    #13 0x1c3f7c46 in decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #14 0x1c3f61e7 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #15 0x1c3f61e7 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #16 0x1c3f61e7 in DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:599:17
    #17 0x1c3f4b87 in DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:487:5
    #18 0x1c3f4b87 in DB::PipelineExecutor::executeImpl(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:826:9
    #19 0x1c3f457c in DB::PipelineExecutor::execute(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:407:9
    #20 0x1c404e46 in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:85:24
    #21 0x1c404da1 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112:13
    #22 0x1c404da1 in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #23 0x1c404c5a in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #24 0x1c404c5a in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #25 0x1c404c5a in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #26 0x1c404c5a in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #27 0xc7d9699 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #28 0xc7d9699 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #29 0xc7d9699 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:274:17
    #30 0xc7dc0a1 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:139:73
    #31 0xc7dc0a1 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #32 0xc7dc0a1 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #33 0xc7dc0a1 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #34 0x7fa86c6c8608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #35 0x7fa86c5ef292 in __clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/Common/assert_cast.h:50:12 in 
2021.10.01 13:27:00.303024 [ 44 ] {} <Trace> BaseDaemon: Received signal -3
2021.10.01 13:27:00.303201 [ 321 ] {} <Fatal> BaseDaemon: ########################################
2021.10.01 13:27:00.303322 [ 321 ] {} <Fatal> BaseDaemon: (version 21.11.1.8265 (official build), build id: ED116A83A49C7D896FFB3A5ECBC80CB43DC5182B) (from thread 314) (query_id: 1873cc6b-5522-44a8-9a71-46974ec369c4) Received signal Unknown signal (-3)
2021.10.01 13:27:00.303360 [ 321 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2021.10.01 13:27:00.303431 [ 321 ] {} <Fatal> BaseDaemon: Stack trace: 0xc7aa8aa 0x1a559131 0xc76c1e6 0xc77df19 0x11ecc56c 0x11eea8a0 0x11eea1e9 0x11ee9f56 0x1a61d1b5 0x1a61df2c 0x1ad9e60e 0x1ad9c6c2 0x1c6b43c6 0x171745ab 0x1c39f80d 0x1c3f7d59 0x1c3f7c47 0x1c3f61e8 0x1c3f4b88 0x1c3f457d 0x1c404e47 0x1c404da2 0x1c404c5b 0xc7d969a 0xc7dc0a2 0x7fa86c6c8609 0x7fa86c5ef293
2021.10.01 13:27:00.370273 [ 321 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./obj-x86_64-linux-gnu/../src/Common/StackTrace.cpp:304: StackTrace::tryCapture()
2021.10.01 13:27:00.370306 [ 321 ] {} <Fatal> BaseDaemon: 0. ../src/Common/StackTrace.cpp:265: StackTrace::StackTrace() @ 0xc7aa8aa in /workspace/clickhouse
2021.10.01 13:27:00.401877 [ 321 ] {} <Fatal> BaseDaemon: 1. ./obj-x86_64-linux-gnu/../base/daemon/BaseDaemon.cpp:400: sanitizerDeathCallback() @ 0x1a559131 in /workspace/clickhouse
2021.10.01 13:27:01.000171 [ 276 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 43.48 GiB, peak 51.86 GiB, will set to 43.60 GiB (RSS), difference: 116.17 MiB
2021.10.01 13:27:01.532389 [ 134 ] {} <Trace> SystemLog (system.query_thread_log): Flushing system log, 13 entries to flush up to offset 93531
2021.10.01 13:27:01.536094 [ 134 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.10.01 13:27:01.537659 [ 134 ] {} <Trace> system.query_thread_log (79a1de57-46e6-44bc-b9a1-de5746e6d4bc): Renaming temporary part tmp_insert_202110_55_55_0 to 202110_55_55_0.
2021.10.01 13:27:01.538013 [ 134 ] {} <Trace> SystemLog (system.query_thread_log): Flushed system log up to offset 93531
2021.10.01 13:27:01.566547 [ 321 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xc76c1e6 in /workspace/clickhouse
2021.10.01 13:27:01.706410 [ 138 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.10.01 13:27:01.707407 [ 138 ] {} <Trace> system.text_log (84a65b53-d7d0-44c4-84a6-5b53d7d004c4): Renaming temporary part tmp_insert_202110_63_63_0 to 202110_63_63_0.
2021.10.01 13:27:02.000145 [ 276 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 43.60 GiB, peak 51.86 GiB, will set to 43.81 GiB (RSS), difference: 218.36 MiB
2021.10.01 13:27:02.204036 [ 139 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 7 entries to flush up to offset 476
2021.10.01 13:27:02.223629 [ 139 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.10.01 13:27:02.228833 [ 139 ] {} <Trace> system.metric_log (541231bf-059f-42c6-9412-31bf059fc2c6): Renaming temporary part tmp_insert_202110_63_63_0 to 202110_63_63_0.
2021.10.01 13:27:02.230285 [ 139 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 476
2021.10.01 13:27:02.716953 [ 321 ] {} <Fatal> BaseDaemon: 3. ? @ 0xc77df19 in /workspace/clickhouse
2021.10.01 13:27:03.858360 [ 321 ] {} <Fatal> BaseDaemon: 4. DB::JSONExtractRawImpl<DB::SimdJSONParser>::insertResultToColumn(DB::IColumn&, DB::SimdJSONParser::Element const&, std::__1::basic_string_view<char, std::__1::char_traits<char> > const&) @ 0x11ecc56c in /workspace/clickhouse
2021.10.01 13:27:04.677787 [ 140 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 8918 entries to flush up to offset 607810
2021.10.01 13:27:04.683776 [ 140 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 4.64 TiB.
2021.10.01 13:27:04.685446 [ 140 ] {} <Trace> system.asynchronous_metric_log (040e9ccf-59fa-4b62-840e-9ccf59fafb62): Renaming temporary part tmp_insert_202110_68_68_0 to 202110_68_68_0.
2021.10.01 13:27:04.685651 [ 140 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 607810
2021.10.01 13:27:04.987895 [ 321 ] {} <Fatal> BaseDaemon: 5. DB::FunctionJSONHelpers::Executor<DB::NameJSONExtractRaw, DB::JSONExtractRawImpl, DB::SimdJSONParser>::run(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0x11eea8a0 in /workspace/clickhouse
2021.10.01 13:27:06.116619 [ 321 ] {} <Fatal> BaseDaemon: 6. DB::ExecutableFunctionJSON<DB::NameJSONExtractRaw, DB::JSONExtractRawImpl>::chooseAndRunJSONParser(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x11eea1e9 in /workspace/clickhouse
2021.10.01 13:27:06.826787 [ 91 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #1
2021.10.01 13:27:06.844630 [ 184 ] {} <Debug> DNSResolver: Updating DNS cache
2021.10.01 13:27:06.844893 [ 184 ] {} <Debug> DNSResolver: Updated DNS cache
2021.10.01 13:27:07.261600 [ 321 ] {} <Fatal> BaseDaemon: 7. DB::ExecutableFunctionJSON<DB::NameJSONExtractRaw, DB::JSONExtractRawImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x11ee9f56 in /workspace/clickhouse
2021.10.01 13:27:07.273624 [ 321 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:0: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x1a61d1b5 in /workspace/clickhouse
2021.10.01 13:27:07.285594 [ 321 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: intrusive_ptr
2021.10.01 13:27:07.285633 [ 321 ] {} <Fatal> BaseDaemon: 9.2. inlined from ../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:122: boost::intrusive_ptr<DB::IColumn const>::operator=(boost::intrusive_ptr<DB::IColumn const>&&)
2021.10.01 13:27:07.285656 [ 321 ] {} <Fatal> BaseDaemon: 9.3. inlined from ../src/Common/COW.h:136: COW<DB::IColumn>::immutable_ptr<DB::IColumn>::operator=(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&&)
2021.10.01 13:27:07.285703 [ 321 ] {} <Fatal> BaseDaemon: 9. ../src/Functions/IFunction.cpp:260: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x1a61df2c in /workspace/clickhouse
2021.10.01 13:27:07.359580 [ 321 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:115: intrusive_ptr
2021.10.01 13:27:07.359620 [ 321 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:122: boost::intrusive_ptr<DB::IColumn const>::operator=(boost::intrusive_ptr<DB::IColumn const>&&)
2021.10.01 13:27:07.359647 [ 321 ] {} <Fatal> BaseDaemon: 10.3. inlined from ../src/Common/COW.h:136: COW<DB::IColumn>::immutable_ptr<DB::IColumn>::operator=(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&&)
2021.10.01 13:27:07.359666 [ 321 ] {} <Fatal> BaseDaemon: 10. ../src/Interpreters/ExpressionActions.cpp:601: DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) @ 0x1ad9e60e in /workspace/clickhouse
2021.10.01 13:27:07.416746 [ 321 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:0: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x1ad9c6c2 in /workspace/clickhouse
2021.10.01 13:27:07.427374 [ 321 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:0: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x1c6b43c6 in /workspace/clickhouse
2021.10.01 13:27:07.447426 [ 321 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:38: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x171745ab in /workspace/clickhouse
2021.10.01 13:27:07.461621 [ 321 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x1c39f80d in /workspace/clickhouse
2021.10.01 13:27:07.496205 [ 321 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:96: DB::executeJob(DB::IProcessor*) @ 0x1c3f7d59 in /workspace/clickhouse
2021.10.01 13:27:07.529831 [ 321 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:108: operator()
2021.10.01 13:27:07.529861 [ 321 ] {} <Fatal> BaseDaemon: 16. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(fp)()) std::__1::__invoke<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&>(DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0&) @ 0x1c3f7c47 in /workspace/clickhouse
2021.10.01 13:27:07.559173 [ 321 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:606: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1c3f61e8 in /workspace/clickhouse
2021.10.01 13:27:07.583537 [ 321 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:0: DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long)
2021.10.01 13:27:07.583572 [ 321 ] {} <Fatal> BaseDaemon: 18. ../src/Processors/Executors/PipelineExecutor.cpp:826: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1c3f4b88 in /workspace/clickhouse
2021.10.01 13:27:07.611841 [ 321 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1627: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::operator->() const
2021.10.01 13:27:07.611874 [ 321 ] {} <Fatal> BaseDaemon: 19. ../src/Processors/Executors/PipelineExecutor.cpp:410: DB::PipelineExecutor::execute(unsigned long) @ 0x1c3f457d in /workspace/clickhouse
2021.10.01 13:27:07.630743 [ 321 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./obj-x86_64-linux-gnu/../base/common/../common/scope_guard.h:94: basic_scope_guard<DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)::$_2>::invoke()
2021.10.01 13:27:07.630779 [ 321 ] {} <Fatal> BaseDaemon: 20.2. inlined from ../base/common/../common/scope_guard.h:44: ~basic_scope_guard
2021.10.01 13:27:07.630792 [ 321 ] {} <Fatal> BaseDaemon: 20. ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:86: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0x1c404e47 in /workspace/clickhouse
2021.10.01 13:27:07.648644 [ 321 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) @ 0x1c404da2 in /workspace/clickhouse
2021.10.01 13:27:07.666808 [ 321 ] {} <Fatal> BaseDaemon: 22.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:0: operator()
2021.10.01 13:27:07.666842 [ 321 ] {} <Fatal> BaseDaemon: 22. ../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) @ 0x1c404c5b in /workspace/clickhouse
2021.10.01 13:27:07.679905 [ 321 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2533: std::__1::function<void ()>::operator=(std::nullptr_t)
2021.10.01 13:27:07.679936 [ 321 ] {} <Fatal> BaseDaemon: 23. ../src/Common/ThreadPool.cpp:277: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xc7d969a in /workspace/clickhouse
2021.10.01 13:27:07.694563 [ 321 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xc7dc0a2 in /workspace/clickhouse
2021.10.01 13:27:07.694619 [ 321 ] {} <Fatal> BaseDaemon: 25. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021.10.01 13:27:07.694655 [ 321 ] {} <Fatal> BaseDaemon: 26. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
2021.10.01 13:27:07.979308 [ 321 ] {} <Fatal> BaseDaemon: Checksum of the binary: 1B65C52984A86D9029A2CAAE336ED5AC, integrity check passed.
```

### PR DESCRIPTION
**Pull request by amosbird**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect nullable processing of JSONFunctions. This fixes https://github.com/ClickHouse/ClickHouse/issues/29615 . Mark as improvement because https://github.com/ClickHouse/ClickHouse/pull/28012 is not released.

Detailed description / Documentation draft:
.

### CODE REVIEW

**Comment by Avogar** [comment]
Seems like the bug was also fixed by @azat in https://github.com/ClickHouse/ClickHouse/pull/29746 (I merge it because did't know about this PR). But fix in this PR is much better. I can revert https://github.com/ClickHouse/ClickHouse/pull/29746 and then merge this PR or we can delete changes from another fix in this PR. @amosbird what do you think?

**Comment by azat** [comment]
Yeah, sorry I missed it too.
I like this patch more then mine, and it does not have extra complexity (that I though should be).
I'm voting for reverting #29746 and apply this one.

File: tests/queries/0_stateless/02013_json_function_null_column.sql [hunk 1]
```diff
@@ -6,3 +6,4 @@ SELECT JSONExtract(toNullable('{"string_value":null}'), 'string_value', 'Nullabl
 SELECT JSONExtract(toNullable('{"string_value":null}'), 'string_value', 'String') as x, toTypeName(x);
 SELECT JSONExtract(NULL, 'string_value', 'Nullable(String)') as x, toTypeName(x);
 SELECT JSONExtract(NULL, 'string_value', 'String') as x, toTypeName(x);
+SELECT JSONExtractString('["a", "b", "c", "d", "e"]', idx) FROM (SELECT arrayJoin([2, NULL, 2147483646, 65535, 65535, 3]) AS idx);
```
Comment (Avogar) [inline tests/queries/0_stateless/02013_json_function_null_column.sql:9]: Let's also add tests with other JSONExtract* functions (e.g. JSONExtractUInt, JSONExtractFloat)

Comment (azat) [reply tests/queries/0_stateless/02013_json_function_null_column.sql:9]: BTW It can be copied from #29746

Comment (amosbird) [reply tests/queries/0_stateless/02013_json_function_null_column.sql:9]: Done.

**Review by Avogar — APPROVED** [review]

**Comment by amosbird** [comment]
> Seems like the bug was also fixed by @azat in #29746 (I merge it because did't know about this PR). But fix in this PR is much better. I can revert #29746 and then merge this PR or we can delete changes from another fix in this PR. @amosbird what do you think?

Cool. Let's use this fix instead. Sorry I was on holiday and didn't respond in time.

File: src/Functions/FunctionsJSON.h [hunk 2]
```diff
@@ -388,21 +395,25 @@ class JSONOverloadResolver : public IFunctionOverloadResolver, WithContext
 
     FunctionBasePtr build(const ColumnsWithTypeAndName & arguments) const override
     {
+        DataTypePtr json_return_type = Impl<DummyJSONParser>::getReturnType(Name::name, createBlockWithNestedColumns(arguments));
```
Comment (azat) [inline src/Functions/FunctionsJSON.h:398]: Actually this is not enough to implement this in a proper way (and this is what I was talking about in the #29746)

```sql
-- ok
┌─JSONExtract('["1"]', toNullable(2), 'Nullable(String)')─┐
│ ᴺᵁᴸᴸ                                                    │
└─────────────────────────────────────────────────────────┘

-- not ok
┌─JSONExtractString('["1"]', toNullable(2))─┐
│                                           │
└───────────────────────────────────────────┘
```

So it does not update the Nullable map I guess.

File: tests/queries/0_stateless/02013_json_function_null_column.sql [hunk 3]
```diff
@@ -6,3 +6,19 @@ SELECT JSONExtract(toNullable('{"string_value":null}'), 'string_value', 'Nullabl
...
+
+SELECT JSONExtractArrayRaw('["1"]', toNullable(1)); -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
+SELECT JSONExtractKeysAndValuesRaw('["1"]', toNullable(1)); -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
+SELECT JSONExtractKeysAndValues('["1"]', toNullable(1)); -- { serverError ILLEGAL_COLUMN }
+
+SELECT JSONExtract('[1]', toNullable(1), 'Nullable(Int)');
+SELECT JSONExtract('[1]', toNullable(1), 'Nullable(UInt8)');
+SELECT JSONExtract('[1]', toNullable(1), 'Nullable(Bool)');
+SELECT JSONExtract('[1]', toNullable(1), 'Nullable(Float)');
+SELECT JSONExtract('["a"]', toNullable(1), 'Nullable(String)');
```
Comment (azat) [inline tests/queries/0_stateless/02013_json_function_null_column.sql:24]: Worth adding a test that will indeed return `NULL` for non-existing key.

File: src/Functions/FunctionsJSON.h (hunk 2 above)
Comment (azat) [reply src/Functions/FunctionsJSON.h:398]: Ok, I see. (although it is strange that return value is Nullable, but it does not return NULL when key does not exists, but `JSONExtract('["1"]', toNullable(2), 'String')` has the same semantics anyway)

**Comment by amosbird** [comment]
Done.
