### PR TITLE
Normalize named tuple arguments in agg states

### LINKED ISSUE #69732: DB::Exception: Conversion from AggregateFunction(uniq, Tuple(city String, name String))
24.6.6.6 https://fiddle.clickhouse.com/3a334edc-0f5e-49c0-9870-9a5f1c9b29b6

```
---- users:
1	London	John
2	Paris	Alice
1	Berlin	Ksenia
---- users2:
1	2
2	1

```

24.7.6.8 https://fiddle.clickhouse.com/bfbeec0c-3c7b-4170-9e29-3e1388ba8ffe

```
 DB::Exception: Conversion from AggregateFunction(uniq, Tuple(city String, name String)) to
 AggregateFunction(uniq, Tuple(String, String)) is not supported: while converting source 
column city_name_uniq to destination column city_name_uniq. (CANNOT_CONVERT_TYPE)
```

https://github.com/ClickHouse/ClickHouse/pull/54881

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Normalize named tuple arguments in aggregation states. This fixes #69732 .

This PR also re-enables `enable_named_columns_in_function_tuple`, as all known bugs related to it have been resolved. The only remaining exception is issue #70830, which simplifies to the following scenario:

```sql
create table x (t Tuple(a int, b int)) engine MergeTree order by ();
insert into x select (1 as a2, 2 as b2);
select * from x format JSONEachRow;

{"t":{"a":0,"b":0}}
```

Since ClickHouse does not support inserting tuples with different names (e.g., `Tuple(a2 int, b2 int)`) into a tuple structure defined as `Tuple(a int, b int)`, enabling `enable_named_columns_in_function_tuple` would naturally break this compatibility.

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit ee3c0b5440711547e1677c37a55d27dd88829b3a with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70853/ee3c0b5440711547e1677c37a55d27dd88829b3a/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/9ae3d85dfe5977297b7801e0f92e8ea0da8177d7/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/DataTypes/IDataType.h [hunk 1]
```diff
@@ -88,6 +88,10 @@ class IDataType : private boost::noncopyable, public std::enable_shared_from_thi
 
     DataTypePtr getPtr() const { return shared_from_this(); }
 
+    /// Return the normalized form of the current type, currently only
+    /// converting named tuples to unnamed tuples.
```
Comment (alexey-milovidov) [inline src/DataTypes/IDataType.h:92]: The comment didn't mention the purpose.

**Review by serxa — APPROVED** [review]
Looks good

**Comment by amosbird** [comment]
@serxa It would be better to wait for @alexey-milovidov 's input before merging this PR, as it breaks compatibility for certain `INSERT SELECT` queries.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by Algunenano** [comment]
I don't understand why we are ok with breaking the INSERT behaviour, from a expected one to a completely unexpected one.

In the original message:

```
create table x (t Tuple(a int, b int)) engine MergeTree order by ();
insert into x select (1 as a2, 2 as b2);
select * from x format JSONEachRow;
```

Without this setting: `{"t":{"a":1,"b":2}}`
With this setting: `{"t":{"a":0,"b":0}}`

I would expect it to either have the same behaviour as before and match columns in order, or throw because the columns don't match, but inserting default values is totally unexpected.

File: src/Core/Settings.cpp [hunk 2]
```diff
@@ -4453,7 +4453,7 @@ Optimize GROUP BY when all keys in block are constant
     M(Bool, legacy_column_name_of_tuple_literal, false, R"(
 List all names of element of large tuple literals in their column names instead of hash. This settings exists only for compatibility reasons. It makes sense to set to 'true', while doing rolling update of cluster from version lower than 21.7 to higher.
 )", 0) \
-    M(Bool, enable_named_columns_in_function_tuple, false, R"(
+    M(Bool, enable_named_columns_in_function_tuple, true, R"(
 Generate named tuples in function tuple() when all names are unique and can be treated as unquoted identifiers.
 Beware that this setting might currently result in broken queries. It's not recommended to use in production
```
Comment (Algunenano) [inline src/Core/Settings.cpp:4458]: We enabled it while there is still broken behaviour, or at least I understand so, (https://github.com/ClickHouse/ClickHouse/pull/70853#issuecomment-2433542210) and the description still says it's broken and not to use it in production.

**Comment by alexey-milovidov** [comment]
@amosbird, please edit the inline documentation accordingly.

**Comment by amosbird** [comment]
> I would expect it to either have the same behaviour as before and match columns in order, or throw because the columns don't match, but inserting default values is totally unexpected.

@Algunenano The "unexpected" behavior originates from the different conversion rules applied to named and unnamed tuples: https://github.com/ClickHouse/ClickHouse/blob/4c0ce6ad102398235cc2a19bc5e18462cf7be635/src/Functions/FunctionsConversion.cpp#L3727-L3765

```
select (1, 2)::Tuple(a int, b int) by_pos, (1 as a2, 2 as b2)::Tuple(a int, b int) by_name format JSONEachRow;

{"by_pos":{"a":1,"b":2},"by_name":{"a":0,"b":0}}
```

To my knowledge this behavior difference between named and unnamed tuple conversions is not explicitly documented in ClickHouse, nor is it standardized in SQL specifications. In order to help users (who rely on such implementation defined behavior) catch potential data loss issues during INSERT-SELECT, we can introduce a `strict_named_tuple_conversion` setting which throws an exception whenever subcolumns from the source tuple are lost during conversion. I'll do that together with inline documentation adjustments in next PR. @alexey-milovidov WDYT?

**Comment by alexey-milovidov** [comment]
If we enable it by default - ok, otherwise don't bother.

**Comment by Algunenano** [comment]
> If we enable it by default - ok, otherwise don't bother.

The strict feature is being added in https://github.com/ClickHouse/ClickHouse/pull/71030, as a breaking change, and it's not part of 24.10. I'm going to keep enable_named_columns_in_function_tuple disabled in 24.10 and we can enable it in https://github.com/ClickHouse/ClickHouse/pull/71030 cc @amosbird
