### PR TITLE
Fix `L2DistanceTransposed` return type after optimisation with `Nullable` parameter

### LINKED ISSUE #88362: Logical error: 'FUNCTION query tree node does not have valid source node after running L2DistanceTransposedPartialReadsPass'
### Describe the bug

Logical error: 'FUNCTION query tree node does not have valid source node after running L2DistanceTransposedPartialReadsPass'

### How to reproduce

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87687&sha=70da360b66f3d321d4e173eaed743129e833647d&name_0=PR&name_1=AST+fuzzer+%28arm_asan%29

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by rienath**
The `p` parameter in `L2DistanceTransposed(vec1, vec2, p)` gets optimised out to enable partial reading of the `QBit` data type. However, when `p` was `Nullable`, the optimisation incorrectly lost the `Nullable` from the return type too, causing a mismatch between the optimised and unoptimised return types. This resulted in `LOGICAL_ERROR`. 

Fixes https://github.com/ClickHouse/ClickHouse/issues/88362.

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fixed `LOGICAL_ERROR` in `L2DistanceTransposed(vec1, vec2, p)` where the optimisation for partial `QBit` reading incorrectly removed `Nullable` from the return type when `p` was `Nullable`.

### CODE REVIEW

File: src/Analyzer/Passes/L2DistanceTransposedPartialReadsPass.cpp [hunk 1]
```diff
@@ -107,8 +113,11 @@ class L2DistanceTransposedPartialReadsPassVisitor : public InDepthQueryTreeVisit
         if (!function_node->getResultType()->equals(*original_result_type))
             throw Exception(
                 ErrorCodes::LOGICAL_ERROR,
-                "{} query tree node does not have valid source node after running L2DistanceTransposedPartialReadsPass",
-                node->getNodeTypeName());
+                "{} query tree node does not have a valid source node after running L2DistanceTransposedPartialReadsPass. Before: {}, "
+                "after: {}",
+                node->getNodeTypeName(),
+                original_result_type->getName(),
+                function_node->getResultType()->getName());
```
Comment (rienath) [inline src/Analyzer/Passes/L2DistanceTransposedPartialReadsPass.cpp:120]: To improve debugging experience in case of future problems

File: src/Analyzer/Passes/L2DistanceTransposedPartialReadsPass.cpp [hunk 2]
```diff
@@ -94,6 +94,12 @@ class L2DistanceTransposedPartialReadsPassVisitor : public InDepthQueryTreeVisit
 
         /// Add dimension as penultimate argument and reference vector as last argument
         auto dimension_constant = std::make_shared<ConstantNode>(qbit->getDimension());
+
+        /// If the precision node was nullable, the result needs to be nullable too. As this pass removes precision_node, we force
+        /// the nullability on the dimension constant (if former was te case) to preserve the nullability of the result
```
Comment (rienath) [inline src/Analyzer/Passes/L2DistanceTransposedPartialReadsPass.cpp]:
```suggestion
        /// the nullability on the dimension constant (if former was the case) to preserve the nullability of the result
```

**Comment by rienath** [comment]
Stateless tests (amd_ubsan, parallel)
* https://github.com/ClickHouse/ClickHouse/issues/88893

Integration tests (amd_asan, old analyzer, 1/6)
* https://github.com/ClickHouse/ClickHouse/issues/88931

Stateless tests (amd_msan, sequential, 2/2)
* https://github.com/ClickHouse/ClickHouse/issues/88981

[Performance Comparison (amd_release, master_head, 2/3)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88974&sha=ee9f71229b0041359618c77f6004c4e34afc1dba&name_0=PR&name_1=Performance+Comparison+%28amd_release%2C+master_head%2C+2%2F3%29)
* `text_index` and `reading_from_file` performance are unrelated to this change

**Review by Michicosun — APPROVED** [review]
