### PR TITLE
Fix conversion Date32 / DateTime64 / Date to narrow types

### LINKED ISSUE #39249: Casting of the date/timestamps to smaller types should return min/max instead of overflow
```sql
SELECT
    toDate32('2160-01-01') AS a,
    toDate('2160-01-01') AS b,
    toDate(a),
    toDateTime(a),
    toDateTime(b)

Query id: b1043ea4-a5c4-4ab8-98f2-e6d0fbcfbdf5

Row 1:
──────
a:                                  2160-01-01
b:                                  2149-06-06
toDate(toDate32('2160-01-01')):     1980-07-27 -- max date value expected, i.e. 2149-06-06  
toDateTime(toDate32('2160-01-01')): 2023-11-24 17:31:44 -- max datetime value expected, i.e. 2106-02-07 06:28:15
toDateTime(toDate('2160-01-01')):   2013-04-29 17:31:44 -- max datetime value expected, i.e. 2106-02-07 06:28:15
```

```sql
SELECT
    toDateTime64('2160-01-01 00:00:00', 0) AS a,
    toDateTime('2160-01-01 00:00:00') AS b,
    toDate(a),
    toDateTime(a)

Query id: a6085a36-4a41-467b-915d-b69638445754

Row 1:
──────
a:                                                  2160-01-01 00:00:00
b:                                                  2106-02-07 06:28:15
toDate(toDateTime64('2160-01-01 00:00:00', 0)):     1980-07-27 -- max malue, i.e. 2149-06-06  is expected
toDateTime(toDateTime64('2160-01-01 00:00:00', 0)): 2023-11-24 17:31:44 -- max value, i.e. 2106-02-07 06:28:15 is expected
```

P.S. It seems like fixing that may also be a fix for https://github.com/ClickHouse/ClickHouse/issues/39248 (which also can be fixed independently).

### PR DESCRIPTION
**Pull request by zvonand**
Fixes #39249, also impacts #25284. The upper or lower value is considered when out of normal range.
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
More natural conversion of Date32, DateTime64, Date to narrower types: upper or lower normal value is considered when out of normal range

### CODE REVIEW

**Comment by den-crane** [comment]
@mergify update

**Comment by den-crane** [comment]
@Mergifyio update

**Comment by nikitamikhaylov** [comment]
Looks like Mergify is on vacation

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov We don't use mergify anymore, we use the "Update branch" button.

**Comment by zvonand** [comment]
@rschu1ze ping?

File: src/Functions/DateTimeTransforms.h [hunk 1]
```diff
@@ -61,15 +61,22 @@ struct ToDateImpl
 
     static inline UInt16 execute(Int64 t, const DateLUTImpl & time_zone)
     {
-        return UInt16(time_zone.toDayNum(t));
+        if (t < 0)
```
Comment (rschu1ze) [inline src/Functions/DateTimeTransforms.h:64]: Just wondering: does the input `Int64` (l. 62) represent the ClickHouse data type "Int64" or the ClickHouse data type "DateTime64"? In case of the latter, I wonder what a negative DateTime64 means.

File: src/Functions/DateTimeTransforms.h [hunk 2]
```diff
@@ -111,19 +118,37 @@ struct ToStartOfDayImpl
     //TODO: right now it is hardcoded to produce DateTime only, needs fixing later. See date_and_time_type_details::ResultDataTypeMap for deduction of result type example.
     static inline UInt32 execute(const DecimalUtils::DecimalComponents<DateTime64> & t, const DateLUTImpl & time_zone)
     {
-        return time_zone.toDate(static_cast<time_t>(t.whole));
+        if (t.whole < 0)
+            return 0;
```
Comment (rschu1ze) [inline src/Functions/DateTimeTransforms.h:122]: What about something like -0.3? It's negative but 0 in the whole part.

File: src/Functions/DateTimeTransforms.h [hunk 3]
```diff
@@ -111,19 +118,37 @@ struct ToStartOfDayImpl
...
+
+        Int64 date_time = time_zone.fromDayNum(ExtendedDayNum(t.whole));
```
Comment (rschu1ze) [inline src/Functions/DateTimeTransforms.h:124]: Maybe I am confused but in case `date_time <= 0xffffffff`, should we not do in l. 126 `return time_zone.toDate(date_time);`?

**Review by rschu1ze — COMMENTED** [review]
Pong 😄 

I didn't try it out but it would be interesting to know if the other methods mentioned [here](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions) work correctly at the type boundaries, e.g. what happens when `addYears()` (or `date_add` etc.) produces an out-of-bounds value, what happens if `yesterday()` is called on the lowest possible value etc.

File: src/Functions/DateTimeTransforms.h (hunk 1 above)
Comment (zvonand) [reply src/Functions/DateTimeTransforms.h:64]: A negative DT64 means timepoint prior to 1970

File: src/Functions/DateTimeTransforms.h (hunk 2 above)
Comment (zvonand) [reply src/Functions/DateTimeTransforms.h:122]: Good note, thanks

File: tests/queries/0_stateless/02403_date_time_narrowing.sql [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+       toDateTime(toDateTime64('2150-01-01 12:12:12.12', 3, 'UTC'), 'UTC');
+
+SELECT toDateTime(toDate32('1930-01-01', 'UTC'), 'UTC'),
+       toDateTime(toDate32('2150-01-01', 'UTC'), 'UTC');
+
+SELECT toDateTime(toDate('2140-01-01', 'UTC'), 'UTC');
+
+SELECT 'toStartOfDay';
+SELECT toStartOfDay(toDate('2141-01-01', 'UTC'), 'UTC'),
+       toStartOfDay(toDate('1941-01-01', 'UTC'), 'UTC'),
```
[the remark this answers is not in the document]
Comment (zvonand) [reply tests/queries/0_stateless/02403_date_time_narrowing.sql:17]: > '2141-01-01' is a valid date.
Indeed [it is](https://clickhouse.com/docs/ru/sql-reference/data-types/date/), but it is not a valid [DateTime](https://clickhouse.com/docs/ru/sql-reference/data-types/datetime/) -- this can cause a lot of confusion (maybe it already did for someone)

File: tests/queries/0_stateless/02403_date_time_narrowing.sql [hunk 5]
```diff
@@ -1,51 +1,51 @@
...
+SELECT toStartOfMonth(toDate32('1930-01-01', 'UTC')),
+       toStartOfMonth(toDate32('2151-01-01', 'UTC')),
+       toStartOfMonth(toDateTime64('1930-01-01 12:12:12.123', 3, 'UTC'), 'UTC'),
        toStartOfMonth(toDateTime64('2151-01-01 12:12:12.123', 3, 'UTC'), 'UTC');
 
 SELECT 'toLastDayOfMonth';
-SELECT toLastDayOfMonth(toDate32('2151-01-01', 'UTC')),
-       toLastDayOfMonth(toDate32('1941-01-01', 'UTC')),
-       toLastDayOfMonth(toDateTime64('1941-01-01 12:12:12.123', 3, 'UTC'), 'UTC'),
+SELECT toLastDayOfMonth(toDate32('1930-01-01', 'UTC')),
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02403_date_time_narrowing.sql:36]: For unclear reasons, function `toLastDayOfMonth` is not documented in the official docs (but it [should be](https://github.com/ClickHouse/ClickHouse/pull/34394/files)).

Comment (rschu1ze) [reply tests/queries/0_stateless/02403_date_time_narrowing.sql:36]: Function `toLastDayOfMonth` has the interesting property that when called on 1th, 2nd, 3rd, 4th, 5th, 6th June 2148, it should (in theory) produce 30th June 2148 but that is outside the range of the date type. So truncation happens not only (potentially) for inputs but also for outputs. Note that all other tested functions (`toStartOfXYZ`) don't have a similar property for their output values because date types `Date`, `Date32`, `DateTime` and `DateTime64` all start on 1st January. 

So maybe it's worth to test that special case as well.

EDIT1: `toMonday` is also interesting. As far as I see, it produces a 16 bit value, i.e. data type `Date`. The computed "monday" for input values 1th, 2th, 3th and 4th January 1970 as inputs should (in theory) be 29th December 1969 which is outside the range of `Date`. Surely also worth a test. (--> https://www.timeanddate.com/calendar/?year=1969&country=8)

EDIT2: Reading the [docs](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#tostartofweektmode), method `toStartOfWeek`potentially has the same problem. It is not tested here.

Comment (rschu1ze) [reply tests/queries/0_stateless/02403_date_time_narrowing.sql:36]:
```
┌─toLastDayOfMonth(toDate('2149-06-03'))─┐
│                             1970-01-24 │
└────────────────────────────────────────┘
```

Comment (rschu1ze) [reply tests/queries/0_stateless/02403_date_time_narrowing.sql:36]: At least the latter two work:
```
┌─toMonday(toDate('1970-01-02'))─┐
│                     1970-01-01 │
└────────────────────────────────┘

┌─toStartOfWeek(toDate('1970-01-02'))─┐
│                          1970-01-01 │
└─────────────────────────────────────┘
```

File: src/Functions/DateTimeTransforms.h [hunk 6]
```diff
@@ -111,19 +111,30 @@ struct ToStartOfDayImpl
...
     {
         return time_zone.toDate(t);
     }
     static inline UInt32 execute(Int32 d, const DateLUTImpl & time_zone)
     {
-        return time_zone.toDate(ExtendedDayNum(d));
+        if (d < 0)
+            return 0;
+
+        Int64 date_time = time_zone.fromDayNum(ExtendedDayNum(d));
```
Comment (rschu1ze) [inline src/Functions/DateTimeTransforms.h:128]: `fromDayNum()` returns type `Time` ... we should use this typedef (or `auto`)

(same above)

File: src/Functions/FunctionsConversion.h [hunk 7]
```diff
@@ -319,23 +324,31 @@ struct ToDateTimeImpl
...
     }
 
-    static inline Int64 execute(Int32 d, const DateLUTImpl & time_zone)
+    static inline UInt32 execute(Int32 d, const DateLUTImpl & time_zone)
     {
-        return time_zone.fromDayNum(ExtendedDayNum(d));
+        if (d < 0)
+            return 0;
+
+        Int64 date_time = time_zone.fromDayNum(ExtendedDayNum(d));
```
Comment (rschu1ze) [inline src/Functions/FunctionsConversion.h:336]: `Time date_time = ` or `auto date_time =`.

File: src/Functions/FunctionsConversion.h [hunk 8]
```diff
@@ -319,23 +324,31 @@ struct ToDateTimeImpl
...
     {
         return dt;
     }
 
-    // TODO: return UInt32 ???
-    static inline Int64 execute(Int64 dt64, const DateLUTImpl & /*time_zone*/)
+    static inline UInt32 execute(const DecimalUtils::DecimalComponents<DateTime64> & t, const DateLUTImpl & time_zone)
     {
-        return dt64;
+        if (t.whole < 0)
```
Comment (rschu1ze) [inline src/Functions/FunctionsConversion.h:347]: `|| (t.whole >= 0 && t.fractional < 0))` ?

**Review by rschu1ze — COMMENTED** [review]
My brain has melted after review but the change is almost ready ^^

**Comment by zvonand** [comment]
Final run (actually I forgot to do it) -- I'll wait for tests to finish and fix failing tests (that are failing due to updated narrowing)

File: tests/queries/0_stateless/02403_date_time_narrowing.sql [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+       toMonday(toDateTime64('1930-01-01 12:12:12.123', 3, 'UTC'), 'UTC'),
+       toMonday(toDateTime64('2151-01-01 12:12:12.123', 3, 'UTC'), 'UTC');
+
+SELECT 'toStartOfMonth';
+SELECT toStartOfMonth(toDate32('1930-01-01', 'UTC')),
+       toStartOfMonth(toDate32('2151-01-01', 'UTC')),
+       toStartOfMonth(toDateTime64('1930-01-01 12:12:12.123', 3, 'UTC'), 'UTC'),
+       toStartOfMonth(toDateTime64('2151-01-01 12:12:12.123', 3, 'UTC'), 'UTC');
+
+SELECT 'toStartOfMonth';
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02403_date_time_narrowing.sql:57]: Minor: block is copy-paste of l. 51ff

**Review by rschu1ze — COMMENTED** [review]
Outstanding are only a build problem on Darwin and a little test issue. After that we can merge. Thanks.

**Comment by rschu1ze** [comment]
> Will try to look into Darwin fails (why is there a difference between usual and darwin builds? It says:
> 
> ```
> Aug 24 23:59:37 /build/src/Functions/FunctionsConversion.h:359:16: error: no matching function for call to 'min'
> Aug 24 23:59:37         return std::min(t.whole, time_t(0xFFFFFFFF));
> ```
> 
> Is the build made with different args?

Build steps for crosscompiling on Linux for Darwin are [here](https://clickhouse.com/docs/en/development/build-cross-osx).

I reproduced it locally. The problem is that on Darwin, `time_t` is 32-bit (long) and `std::min` complains rightfully about a 32 vs. a 64 bit argument. A cast `static_cast<DateTime64::NativeType>(time_t(0xFFFFFFFF))` will fix the issue.

The deeper problem is the usage of platform-specific type `time_t`. I haven't looked further maybe there exists a platform-independent abstraction for it. Or comparing against a 64-bit constant `0xFFFFFFFF` would also do the trick.

**Comment by rschu1ze** [comment]
Okay, you got rid of `time_t` in a slightly different way. That's also good.

**Review by rschu1ze — APPROVED** [review]

**Comment by zvonand** [comment]
I can't see why PPC build is failing -- the job seems to be frozen (at least, I see no output). Will restart checks by merging master

**Comment by zvonand** [comment]
Great, it passes

**Comment by zvonand** [comment]
I really don't know what are `Stateless tests (release, DatabaseReplicated)` and why my test fail there but pass in other stateless runs. Some hint on what it is will be appreciated

**Comment by rschu1ze** [comment]
I also don't have a good idea right now but I can ask in our internal chat.

Just wondering: For query `SELECT toDate32(toInt32(toDate32('2299-12-31')) + 1)`, the expected result `1970-01-02` seems weird. `SELECT toInt32(toDate32('2299-12-31'))` gives `120529` as internal integer representation, so one would expect that `toDate32(120529 + 1)` (which overflows `Date32`) returns the upper border `2299-12-31` according to the docs ["If the value is outside the range returns the border values supported by Date32."](https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#todate32).

**Comment by zvonand** [comment]
> the expected result 1970-01-02 seems weird

Well, yes, but no. If the result exceeds this value, then this value is considered to be not day number,but timestamp. I know its kind of weird, but this is how it was before - maybe it has sense. It is because thru all int to time conversion logic 32 and 64 are processed together. Amd this is a tricky place - its been so for a while, and by changing it we may break someone's workflow. Moreover, it looks reasonable at some point

**Comment by rschu1ze** [comment]
Thanks for the explanation. The semantics seem quite dangerous to me, and they are also not documented. Perhaps integer-to-date conversion should not be allowed in the first place. But that's a different topic.

I asked about the non-distributed / distributed mismatch in our internal chat and hope to come back with some findings.

**Comment by rschu1ze** [comment]
@tavplubix pointed to timezone randomization in test ... https://github.com/ClickHouse/ClickHouse/blob/52832ea7882311f8caea58c39b94aaf9add08b56/docker/test/stateless/run.sh#L6-L9

**Comment by zvonand** [comment]
@rschu1ze everything passes now

**Comment by rvasin** [comment]
@alexey-milovidov I need your advice because the situation is really interesting.

I was working on #38435 and my branch https://github.com/arenadata/ClickHouse/tree/ADQM-528-B
is ready for PR (I need only to update docs).

In my branch I fixed the functions: toStartOfYear, toStartOfISOYear, toStartOfQuarter, toStartOfMonth, toStartOfWeek, toMonday, toLastDayOfMonth
The are all working fine with range 1900-01-01 - 2299-12-31. Functional tests are ready and they aso work.
I also implemented a compatibility option: enable_date32_results

Today before doing my PR I tried to merge with upstream master and I had a merge conflict because of this PR #40217

After a code review I have noticed many strange new things. For example, consider only function toLastDayOfMonth (most of all other functions are also affected);

this PR #40217

```
struct ToLastDayOfMonthImpl
{
    static constexpr auto name = "toLastDayOfMonth";

    static inline UInt16 execute(Int64 t, const DateLUTImpl & time_zone)
    {
        if (t < 0)
            return 0;

        /// 0xFFF9 is Int value for 2149-05-31 -- the last day where we can actually find LastDayOfMonth. This will also be the return value.
        return time_zone.toLastDayNumOfMonth(ExtendedDayNum(std::min(Int32(time_zone.toDayNum(t)), Int32(0xFFF9))));
    }
    static inline UInt16 execute(UInt32 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline UInt16 execute(Int32 d, const DateLUTImpl & time_zone)
    {
        if (d < 0)
            return 0;

        /// 0xFFF9 is Int value for 2149-05-31 -- the last day where we can actually find LastDayOfMonth. This will also be the return value.
        return time_zone.toLastDayNumOfMonth(ExtendedDayNum(std::min(d, Int32(0xFFF9))));
    }
    static inline UInt16 execute(UInt16 d, const DateLUTImpl & time_zone)
    {
        /// 0xFFF9 is Int value for 2149-05-31 -- the last day where we can actually find LastDayOfMonth. This will also be the return value.
        return time_zone.toLastDayNumOfMonth(DayNum(std::min(d, UInt16(0xFFF9))));
    }

    using FactorTransform = ZeroTransform;
};
```

In my branch:

```
struct ToLastDayOfMonthImpl
{
    static constexpr auto name = "toLastDayOfMonth";

    static inline Int64 execute(Int64 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline UInt16 execute(UInt32 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline Int32 execute(Int32 d, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(ExtendedDayNum(d));
    }
    static inline UInt16 execute(UInt16 d, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(DayNum(d));
    }

    using FactorTransform = ZeroTransform;
};
```

In master at the beginning of August:

```
struct ToLastDayOfMonthImpl
{
    static constexpr auto name = "toLastDayOfMonth";

    static inline UInt16 execute(Int64 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline UInt16 execute(UInt32 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(time_zone.toDayNum(t));
    }
    static inline UInt16 execute(Int32 d, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(ExtendedDayNum(d));
    }
    static inline UInt16 execute(UInt16 d, const DateLUTImpl & time_zone)
    {
        return time_zone.toLastDayNumOfMonth(DayNum(d));
    }

    using FactorTransform = ZeroTransform;
};
```

So please advice what should I do now? I seems to make it working with full range 1900-01-01 to 2299-12-31  I need to completely discard the changes to all mentioned functions. 

Right now what we have:

`SELECT toLastDayOfMonth(toDateTime64('1950-02-02 10:20:30', 3));`

before this PR #40217 (master from the beginning of August 2022); it returns: 
2129-08-04

in this PR #40217 it returns:
1970-01-01

I my branch it returns the correct result:
1950-02-28

**Comment by rschu1ze** [comment]
@rvasin Allow me to answer. This PR (#40217) is in some sense a stopgap solution. As you correction mention at the end of your last comment, it produces incorrect results when the input is of extended date/time type and outside the standard value range. The improvement is that prior to this PR, the result was in principle completely random, whereas the calculation of the incorrect result is now at least deterministic. The exact behavior is documented [here](https://github.com/ClickHouse/ClickHouse/pull/40217/files). More specifically, most date/time functions now implement "cropping" semantics which makes sense iff one assumes they always produce output in a standard precision type.

An implementation which produces the correct result for all input type + value combinations requires type promotion (and yes, such an implementation would replace the modifications in this PR). The reason this has not been done yet were [compat concerns](https://github.com/ClickHouse/ClickHouse/issues/25284).
My personal opinion is that of (1) in https://github.com/ClickHouse/ClickHouse/issues/25284#issuecomment-1004496808. I think that the [reasons](https://github.com/ClickHouse/ClickHouse/issues/25284#issuecomment-1007107402) for not changing the date/time functions in a backwards-incompatible way are legit. On the other hand, I also think they are not substantiated enough as
1. only date/time values in the 1900-1969 and 2150-2299 time ranges would be affected and I doubt that users have a lot of such data. The situation would be different for an OLTP database where there is a high chance of storing birthdays etc. But to support such use cases regardless, we should have a server setting which re-enables the legacy cropping behavior.
2. Adding new "extended" versions of date time functions (e.g. `toLastDayOfMonth64`) + doing AST transformations sounds hard to implement and difficult to comprehend for users.

**Comment by ilejn** [comment]
Hello @rschu1ze , thanks for the reply.
Could you shed some light on backward compatibility issues here, please?
Asking to be sure that we are not missing something important.

**Comment by rschu1ze** [comment]
I would say the approach in your comment https://github.com/ClickHouse/ClickHouse/issues/38435#issuecomment-1218332137 is the most intuitive one, i.e. for Date and DateTime inputs date/time functions produce a Date (*) and for Date32 and DateTime64 inputs they produce a Date32. I also agree with https://github.com/ClickHouse/ClickHouse/issues/38435#issuecomment-1217829992 that ideally all date/time functions should accept extended date/time types as input unless we want the user to insert explicit casts.

About compatibility issues: I guess that the folks I mentioned in https://github.com/ClickHouse/ClickHouse/pull/40217#issuecomment-1236177537 recall the concerns better than me (I joined the team just a few months ago). Let's hear their feedback.
In my understanding, the potential backwards incompatibility for partition clauses involving date/time functions is not about the type (because the integers underlying the extended-precision types equal the ones for standard-precision types for the range where the types overlap, as far as I know) but about the result value. In that sense, a backwards compatibility setting would not affect the type but whether the correct value or a truncated value is computed.

(*) Just to nitpick, `toLastDayOfMonth()` will never able to handle Date inputs in the range [2149-06-01, 2149-06-06] correctly, even with your new approach. Maybe your approach should throw an exception for these values instead of doing truncation as done in this PR.

**Comment by rvasin** [comment]
@rschu1ze OK. Robert, it would it great if you could be a reviewer for my PR.

I will probably write more details on Monday. Here I will mention some of my ideas about the current situation.

> (*) Just to nitpick, `toLastDayOfMonth()` will never able to handle Date inputs in the range [2149-06-01, 2149-06-06] correctly, even with your new approach. Maybe your approach should throw an exception for these values instead of doing truncation as done in this PR.

I don't understand what are you talking about [2149-06-01, 2149-06-06] range. In my branch all mentioned functions work fine in [1900-01-01, 2299-12-31] range.

It's implemented in such way that if argument is Date32 or DateTime64 the result is Date32 (wide range) otherwise the result is Date type (narrow range).

So it's backward incompatible solution. Therefore as I discussed with  @ilejn  we decided to implemented the compatibility option enable_date32_results which currently has FALSE value by default. So my PR would not break compatibility. And if someone wants to to use wide ranges he may set value to TRUE. Lets say it's phase A.

Phase B. correct functions like date_diff to accept Date32 and DateTime64 as arguments. This what is causing the main backward compatibility concerts. If we have things like
date_diff(toStartOfMonth(),toLastDayOfMonth())
and if toStartOfMonth or toLastDayOfMonth return Date32 this will break date_diff().
But if we correct all date/time functions like date_diff to make it working with Date32 or DateTime64 arguments. Then because there are no backward compatibility concerts on this phase. So we may move to Phase C:

Phase C. The idea that with some CH version (for example in October or November) we may set this option TRUE by default (there is special compatibility section for that in CH). 

Phase D. Somewhere in the future to make is function obsolete. Because behavior will be as TRUE 

What comes to my mind: 

Maybe narrowing implemented in current PR makes sense. We may keep it (while I have ideas how to refactor it using std::clamp function etc).

So my idea is:
In my PR I may keep all narrowing code (don't remove it). So it will keep CH backward compatible.
And put my code with enable_date32_results=false
So my PR would be a combination of 
1. turned on narrowing and 
2. turned off Date32 results by default. 
What do you think? 

And maybe somewhere on phase D we may remove all narrowing code. 

Maybe it's a good strategy. What do you think? I think there is should be some strategy of evolution of date/time functions with final goal: all date/time functions must accept Date32/DateTime64 in addition to Date/DateTime and return also narrow range ro wide range. So finally full range 1900-01-01 - 2299-12-31 must be supported by all CH date/time functions.

What bothers me in current PR #40217 there is performance degradation because of clamping/cropping. 
Please read [my comment](https://github.com/ClickHouse/ClickHouse/pull/39425#issuecomment-1209422852) from by previous PR. There is similar clamping/cropping. I tried many ways to find a better code. But there is still the performance degradation.
Finally @alexey-milovidov said to remove the clamping code from PR.
But as I said maybe on Phase D we may remove all narrowing code so the performance will be the same as in code at the beginning of August.

Another thing: I also think the approach to use functions like toStartOfDay64  is not a good idea. Because
1. We need to keep CH more ANSI SQL compatible. Other databases like MySQL/PostgreSQL don't have functions like toStartOfDay64. 
2. CH already has functions like date_add and date_sub (and it does not have functions like date_add 64) which return Date, Date32, DateTime or DateTime64 types depending on arguments. So it's llogical when for example toStartOfMonth returns Date or Date32 (as currently implemented in my branch).

**Comment by rvasin** [comment]
@rschu1ze Right now I am working on integration of the code from this PR into my branch. So I will talk about compatibility aspects later (which are also important).  I am planning to make my PR at the middle of the next week.

Now I want to answer on the following:

> Are you saying that this PR https://github.com/ClickHouse/ClickHouse/pull/40217 causes performance degradation? Could you point me to the performance report which shows that?

As an example of performance degradation as you see there were added many ifs in toDateTime() function:
https://github.com/ClickHouse/ClickHouse/pull/40217/files#diff-2859e9a878020ac61a5586d7413871dfc37b790071c191bc1fe3f091ee56370eR324-R338

    static inline UInt32 execute(Int64 d, const DateLUTImpl & time_zone)
    {
        if (d < 0)
            return 0;

        auto date_time = time_zone.toDate(d);
        return date_time <= 0xffffffff ? date_time : 0xffffffff;
    }

    static inline UInt32 execute(const DecimalUtils::DecimalComponents<DateTime64> & t, const DateLUTImpl & /*time_zone*/)
    {
        return dt64;
        if (t.whole < 0 || (t.whole >= 0 && t.fractional < 0))
            return 0;

        return std::min<Int64>(t.whole, Int64(0xFFFFFFFF));
    }

And on the tests we see:
https://s3.amazonaws.com/clickhouse-test-reports/40217/b9b8f7a05d29104af1dbeb8216c3d99da2cb140c/performance_comparison_[2/4]/report.html

`SELECT count() FROM numbers(10000000) WHERE NOT ignore(toDateTime('2017-01-01 00:00:00') + number % 100000000 + rand() % 100000 AS t, formatDateTime(t, '%Y-%m-%d %H:%M:%S'))`

+1.502x  - it's 50% degradation. 

I have to note that all performance tests of this PR are "green". Maybe date time functions are not covered well by tests. 

As I explained earlier: 
In my previous PR I had the similar situation:
My performance tests were also "green".
But after adding clamping/cropping code to AddDaysImpl and AddWeeksImpl we have noticed the degradation:
https://s3.amazonaws.com/clickhouse-test-reports/39425/96598e35743aa83e3ac31cc4776190543671f1d1/performance_comparison_[4/4]/report.html

`SELECT count() FROM numbers(50000000) WHERE NOT ignore(toDate('2017-01-01') + number % 1000 + rand() % 10 AS t, toRelativeDayNum(t))`

+1.217x

So in final commit we removed the clamping code:
https://github.com/ClickHouse/ClickHouse/pull/39425/commits/537ba613dcc5c2f23f5763f894dcbe2b9823d32d

I must admit that such performance degradations must be considered separately and more carefully. I will probably write several queries specific to affected functions like toLastDayOfMonth, toStartOf and I will compare the performance of different branches. 
Right now I want to concentrate on integrating on current PR (which is in master now)  with my branch as explained in my previous messages.

**Comment by rvasin** [comment]
> PS: @rvasin Feel free to set me as reviewer to your PR once it is ready, I am by now quite deep in the entire date/time madness smile

@rschu1ze Robert, I created PR #41214 please set yourself as reviewer for the PR. 
We will discuss compatibility questions etc in PR #41214  and probably make some more improvements after a talk there.

**Comment by rschu1ze** [comment]
Agree that it is a good idea to write performance tests for all date/time functions (or to check at least the test coverage for them). With your new PR #41214, I would not worry too much about the performance degradations because at some future point, narrowing will completely go away and with it all the if statements. And for the remaining few cases, `likely()/unlikely()` statements can help too.

**Comment by alexey-milovidov** [comment]
@zvonand I also don't understand what was the motivation for this change.
It is unclear whether we need narrowing.

**Comment by rschu1ze** [comment]
The original motivation was #39249.

I don't mind if we keep the original behavior which is to produce random results for arguments values outside the converted-to type's range.
E.g. `SELECT toDate(toDate32('1930-01-01'))` -- before the revert: 1970-01-01, after the revert: 2109-06-07
It should just be documented (--> [here](https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions/#todate))
