### PR TITLE
Fix: insert delay calculation

### LINKED ISSUE #44902: Fix formula for insert delay time calculation
We have following function which allows to delay inserts in case of TOO_MANY_PARTS:
https://github.com/ClickHouse/ClickHouse/blob/c09f83654dae58fd964e024f7842de64f59ab579/src/Storages/MergeTree/MergeTreeData.cpp#L3724-L3798.

Delay time formula looks really strange and can lead to enormous value of sleep time, like:
```
Delaying inserting block by 9223372036854775808 ms. because there are 199 parts and their average size is 1.85 GiB
```
This can lead to unexpected errors from `tryWait` function like:
```
0. Poco::EventImpl::waitImpl(long) @ 0x1730d6e6 in /usr/bin/clickhouse
1. DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*, std::__1::shared_ptr<DB::Context const>) const @ 0x13e9ca32 in /usr/bin/clickhouse
2. ? @ 0x145d9379 in /usr/bin/clickhouse
3. DB::ExceptionKeepingTransform::work() @ 0x145d8b54 in /usr/bin/clickhouse
4. DB::ExecutionThreadContext::executeTask() @ 0x14409026 in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x143fdadc in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x143fc519 in /usr/bin/clickhouse
7. DB::PipelineExecutor::execute(unsigned long) @ 0x143fc31d in /usr/bin/clickhouse
8. DB::CompletedPipelineExecutor::execute() @ 0x143fad3d in /usr/bin/clickhouse
9. DB::AsynchronousInsertQueue::processData(DB::AsynchronousInsertQueue::InsertQuery, std::__1::unique_ptr<DB::AsynchronousInsertQueue::InsertData, std::__1::default_delete<DB::AsynchronousInsertQueue::InsertData>>, std::__1::shared_ptr<DB::Context const>) @ 0x1293f3f4 in /usr/bin/clickhouse
10. ? @ 0x12941ed0 in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xda87576 in /usr/bin/clickhouse
12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0xda89d37 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xda83b96 in /usr/bin/clickhouse
14. ? @ 0xda88d01 in /usr/bin/clickhouse
15. ? @ 0x7f636c46c609 in ?
16. clone @ 0x7f636c391133 in ?
```

Need to rethink the logic of delay time calculation and introduce better formula or some other thresholds.

### PR DESCRIPTION
**Pull request by devcrafter**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Delay for INSERT can be calculated incorrectly, which can lead to always using `max_delay_to_insert`  setting as delay instead of a correct value. Using simple formula `max_delay_to_insert * (parts_over_threshold/max_allowed_parts_over_threshold)` i.e. delay grows proportionally to parts over threshold. Closes #44902

### Documentation entry for user-facing changes
TODO: the formula is even documented [here](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings/#max-delay-to-insert). So, I'll change the documentation after PR will be approved (i.e. the new formula as well). See https://github.com/ClickHouse/ClickHouse/pull/44954

### CODE REVIEW

**Comment by devcrafter** [comment]
Asked for review to check formula. Need to add a test

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -3722,70 +3722,93 @@ std::optional<Int64> MergeTreeData::getMinPartDataVersion() const
...
     size_t average_part_size = parts_count_in_partition ? size_of_partition / parts_count_in_partition : 0;
-    bool parts_are_large_enough_in_average = settings->max_avg_part_size_for_too_many_parts
-        && average_part_size > settings->max_avg_part_size_for_too_many_parts;
-
-    if (parts_count_in_partition >= parts_to_throw_insert && !parts_are_large_enough_in_average)
+    const auto active_parts_to_delay_insert
+        = query_settings.parts_to_delay_insert ? query_settings.parts_to_delay_insert : settings->parts_to_delay_insert;
+    const auto active_parts_to_throw_insert
+        = query_settings.parts_to_throw_insert ? query_settings.parts_to_throw_insert : settings->parts_to_throw_insert;
+    size_t active_parts_over_threshold = [&](size_t parts_count) -> size_t
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeData.cpp:3768]: Strange + 1 :)

Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergeTreeData.cpp:3768]: Like, why average_part_size is captured, but parts_count_in_partition an argument?
I'd better to avoid using lamdas

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 2]
```diff
@@ -3722,70 +3722,93 @@ std::optional<Int64> MergeTreeData::getMinPartDataVersion() const
...
+        }
+        if (active_parts_to_delay_insert > 0 && parts_count >= active_parts_to_delay_insert && !parts_are_large_enough_in_average)
+            /// if parts_count == parts_to_delay_insert -> we're 1 part over threshold
+            return parts_count - active_parts_to_delay_insert + 1;
+
+        return 0;
+    }(parts_count_in_partition);
+
+    /// no need for delay
+    if (!active_parts_over_threshold && !outdated_parts_over_threshold)
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeData.cpp:3790]: Ok, I see now why we have +1.
Maybe it's better to use std::optional or bool flag or something.

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 3]
```diff
@@ -3722,70 +3722,93 @@ std::optional<Int64> MergeTreeData::getMinPartDataVersion() const
...
-        = std::min(max_delay_milliseconds, static_cast<UInt64>(::pow(max_delay_milliseconds, static_cast<double>(k) / max_k)));
+        size_t parts_over_threshold = std::max(active_parts_over_threshold, outdated_parts_over_threshold);
+        size_t allowed_parts_over_threshold = 1;
+        if (active_parts_over_threshold >= outdated_parts_over_threshold)
+            allowed_parts_over_threshold = active_parts_to_throw_insert - active_parts_to_delay_insert;
+        else
+            allowed_parts_over_threshold
+                = (settings->inactive_parts_to_throw_insert > 0
+                       ? settings->inactive_parts_to_throw_insert - settings->inactive_parts_to_delay_insert
+                       : outdated_parts_over_threshold);
```
[the remark this answers is not in the document]
Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergeTreeData.cpp:3803]: Have I said that I don't like operator `?`? :D 
Especially inside nested if...

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 4]
```diff
@@ -3722,70 +3722,93 @@ std::optional<Int64> MergeTreeData::getMinPartDataVersion() const
...
+
+        chassert(parts_over_threshold <= allowed_parts_over_threshold);
```
Comment (KochetovNicolai) [inline src/Storages/MergeTree/MergeTreeData.cpp:3805]: Let's better throw LOGICAL_ERROR.

Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergeTreeData.cpp:3805]: Let's also check allowed_parts_over_threshold > 0

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 5]
```diff
@@ -3722,70 +3722,93 @@ std::optional<Int64> MergeTreeData::getMinPartDataVersion() const
...
+
+        const UInt64 max_delay_milliseconds = (settings->max_delay_to_insert > 0 ? settings->max_delay_to_insert * 1000 : 1000);
+        double delay_factor = static_cast<double>(parts_over_threshold) / allowed_parts_over_threshold;
+        /// min() as a save guard here
+        return std::min(max_delay_milliseconds, static_cast<UInt64>(max_delay_milliseconds * delay_factor));
```
[the remark this answers is not in the document]
Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergeTreeData.cpp:3810]: The formula is ok, but I would still add something like `min_delay_milliseconds` (like 100).
And wait for `max(min_delay_milliseconds, max_delay_milliseconds * delay_factor + min_delay_milliseconds * (1.0 - delay_factor))`

**Review by KochetovNicolai — COMMENTED** [review]
The good thing is that code became more readable.

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 6]
```diff
@@ -3722,70 +3722,93 @@ std::optional<Int64> MergeTreeData::getMinPartDataVersion() const
...
             throw Exception(
                 ErrorCodes::TOO_MANY_PARTS,
                 "Too many inactive parts ({}). Parts cleaning are processing significantly slower than inserts",
-                inactive_parts_count_in_partition);
+                outdated_parts_count_in_partition);
         }
-        k_inactive = static_cast<ssize_t>(inactive_parts_count_in_partition) - static_cast<ssize_t>(settings->inactive_parts_to_delay_insert);
-    }
+        if (settings->inactive_parts_to_delay_insert > 0 && outdated_parts_count_in_partition >= settings->inactive_parts_to_delay_insert)
+            return outdated_parts_count_in_partition - settings->inactive_parts_to_delay_insert + 1;
```
[the remark this answers is not in the document]
Comment (devcrafter) [reply src/Storages/MergeTree/MergeTreeData.cpp:3757]: `outdated_parts_over_threshold == 0` means no delay is necessary due to outdated parts

File: src/Storages/MergeTree/MergeTreeData.cpp (hunk 2 above)
Comment (devcrafter) [reply src/Storages/MergeTree/MergeTreeData.cpp:3866]: I understand, but with current variable names it'd sound confusing like “Number of active parts over threshold is 0 therefore we will delay insert”

I guess, introduction boolean flags or optional will make code less clear.
Here logic is, – the range for number of parts where we introduce delay is [`parts_to_delay_insert`, `parts_to_throw_insert`). If `number_of_parts` == `parts_to_delay_inserts` then we need to delay.

WDYT?

**Review by KochetovNicolai — APPROVED** [review]
