### PR TITLE
Fix crash in IAccessStorage::authenticateImpl

### LINKED ISSUE #84425: Clickhouse server crash in IAccessStorage::authenticateImpl
### Company or project name

Clickhouse Server

### Describe what's wrong

A user is created identified with `no_password` when the server setting `allow_no_password` was `True`. If the server setting is changed to `False`, attempting to login as the same user could crash the Clickhouse server.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Check above

### Expected behavior

No crash

### Error message and/or stacktrace

25.6.2.5671
```

2. ./ci/tmp/build/./src/Access/IAccessStorage.cpp:570: DB::IAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, DB::ClientInfo const&, bool, bool, bool) const
3. ./ci/tmp/build/./src/Access/MultipleAccessStorage.cpp:452: DB::MultipleAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, DB::ClientInfo const&, bool, bool, bool) const
4. ./ci/tmp/build/./src/Access/IAccessStorage.cpp:515: DB::IAccessStorage::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, DB::ClientInfo const&, bool, bool) const
5. ./ci/tmp/build/./src/Access/AccessControl.cpp:632: DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ClientInfo const&) const
6. ./ci/tmp/build/./src/Interpreters/Session.cpp:384: DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&)
7. ./ci/tmp/build/./src/Server/HTTP/authenticateUserByHTTP.cpp:275: DB::authenticateUserByHTTP(DB::HTTPServerRequest const&, DB::HTMLForm const&, DB::HTTPServerResponse&, DB::Session&, std::unique_ptr<DB::Credentials, std::default_delete<DB::Credentials>>&, DB::HTTPHandlerConnectionConfig const&, std::shared_ptr<DB::Context const>, std::shared_ptr<Poco::Logger>)
8. ./ci/tmp/build/./src/Server/HTTPHandler.cpp:208: DB::HTTPHandler::authenticateUser(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&)
9. ./ci/tmp/build/./src/Server/HTTPHandler.cpp:224: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&)
10. ./ci/tmp/build/./src/Server/HTTPHandler.cpp:759: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&)
11. ./ci/tmp/build/./src/Server/HTTP/HTTPServerConnection.cpp:104: DB::HTTPServerConnection::run()
12. ./src/Server/TCPProtocolStackHandler.h:38: DB::TCPProtocolStackHandler::run()
13. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start()
14. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run()
15. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run()
16. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*)
17. ?
18. ?
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shankar-iyer**
Resolves https://github.com/ClickHouse/ClickHouse/issues/84425

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description]
- Fixed server crash when a user created with `no_password` attempts to login after the server setting `allow_no_password` was changed to 0.

### CODE REVIEW

**Comment by shankar-iyer** [comment]
Only single failure in CI - "Stress test (amd_tsan)" : https://github.com/ClickHouse/ClickHouse/issues/83988

File: tests/queries/0_stateless/03574_no_password_existing_user.sh [hunk 1]
```diff
@@ -0,0 +1,130 @@
+#!/usr/bin/env bash
+# Tags: no-parallel, no-fasttest
```
Comment (bharatnc) [inline tests/queries/0_stateless/03574_no_password_existing_user.sh:2]: Curious, why `no-fasttest?`

File: tests/queries/0_stateless/03574_no_password_existing_user.sh [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+# 1st : Start with allow_no_password=1 and create a user with no_password and login as that user will also succeed.
+# 2nd : Restart the server with allow_no_password=0. Now login as that user should error and not crash Clickhouse server.
+
+CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CURDIR"/../shell_config.sh
+
+cp ${CLICKHOUSE_CONFIG_DIR}/users.xml "$CURDIR"/users.xml
+sed -i 's/<password><\/password>/<password_sha256_hex>c64c5e4e53ea1a9f1427d2713b3a22bbebe8940bc807adaf654744b1568c70ab<\/password_sha256_hex>/g' "$CURDIR"/users.xml
+ sed -i 's/<!-- <access_management>1<\/access_management> -->/<access_management>1<\/access_management>/g' "$CURDIR"/users.xml
```
Comment (bharatnc) [inline tests/queries/0_stateless/03574_no_password_existing_user.sh]: `nit:`
```suggestion
sed -i 's/<!-- <access_management>1<\/access_management> -->/<access_management>1<\/access_management>/g' "$CURDIR"/users.xml
```

File: tests/queries/0_stateless/03574_no_password_existing_user.sh (hunk 1 above)
Comment (shankar-iyer) [reply tests/queries/0_stateless/03574_no_password_existing_user.sh:2]: Inherited from `02207_allow_plaintext_and_no_password`, test starts Clickhouse instance for itself with custom config file and even restarts it once.

File: tests/queries/0_stateless/03574_no_password_existing_user.sh (hunk 2 above)
Comment (shankar-iyer) [reply tests/queries/0_stateless/03574_no_password_existing_user.sh]: ack, thanks!

**Review by bharatnc — APPROVED** [review]
