### PR TITLE
Follow up to #61723

### LINKED ISSUE #51819: Logical error: candidate->releasable()
https://s3.amazonaws.com/clickhouse-test-reports/0/3371e038cfde35bedc6eeb08b98891b784ea474c/stress_test__ubsan_.html

```
 [ 2843 ] {917e9129-2db9-4f83-ab3f-ad3dc5128537} <Fatal> : Logical error: \'candidate->releasable()\'.
 [ 43212 ] {} <Fatal> BaseDaemon: ########################################
 [ 43212 ] {} <Fatal> BaseDaemon: (version 23.7.1.1 (official build), build id: F292C37AAE756A1C824646199918F07DBB209EC5, git hash: 3371e038cfde35bedc6eeb08b98891b784ea474c) (from thread 2843) (query_id: 917e9129-2db9-4f83-ab3f-ad3dc5128537) (query: SELECT uniq(URL) FROM test.hits WHERE TraficSource
 [ 43212 ] {} <Fatal> BaseDaemon: 
 [ 43212 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f22cb926a7c 0x00007f22cb8d2476 0x00007f22cb8b87f3 0x0000561ae4010c48 0x0000561af266a7fd 0x0000561af268765f 0x0000561af00ab7f0 0x0000561af00a8f6f 0x0000561ad7994db9 0x0000561af0093bd3 0x0000561af0092787 0x0000561ad7994db9 0x0000561ad8256fa1 0x0000
 [ 43212 ] {} <Fatal> BaseDaemon: 3. pthread_kill @ 0x00007f22cb926a7c in ?
 [ 43212 ] {} <Fatal> BaseDaemon: 4. raise @ 0x00007f22cb8d2476 in ?
 [ 43212 ] {} <Fatal> BaseDaemon: 5. abort @ 0x00007f22cb8b87f3 in ?
 [ 43212 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:50: DB::abortOnFailedAssertion(String const&) @ 0x0000000037df0c48 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: String::__is_long[abi:v15000]() const
 [ 43212 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/string:2333: ~basic_string
 [ 43212 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Interpreters/Cache/FileCache.cpp:754: DB::FileCache::tryReserve(DB::FileSegment&, unsigned long) @ 0x000000004644a7fd in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Interpreters/Cache/FileSegment.cpp:526: DB::FileSegment::reserve(unsigned long) @ 0x000000004646765f in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:983: DB::CachedOnDiskReadBufferFromFile::nextImplStep() @ 0x0000000043e8b7f0 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Disks/IO/CachedOnDiskReadBufferFromFile.cpp:781: DB::CachedOnDiskReadBufferFromFile::nextImpl() @ 0x0000000043e88f6f in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 11. DB::ReadBuffer::next() @ 0x000000002b774db9 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:0: DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x0000000043e73bd3 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:159: DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x0000000043e72787 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 14. DB::ReadBuffer::next() @ 0x000000002b774db9 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 15. DB::ReadBuffer::ignore(unsigned long) @ 0x000000002c036fa1 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Disks/IO/ReadBufferFromRemoteFSGather.cpp:0: DB::ReadBufferFromRemoteFSGather::seek(long, int) @ 0x0000000043e757fc in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/./src/IO/BufferBase.h:39: DB::BufferBase::Buffer::begin() const
 [ 43212 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./build_docker/./src/IO/BufferBase.h:79: DB::BufferBase::offset() const
 [ 43212 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Compression/CompressedReadBufferFromFile.cpp:80: DB::CompressedReadBufferFromFile::seek(unsigned long, unsigned long) @ 0x00000000445d945a in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderStream.cpp:247: DB::MergeTreeReaderStream::seekToMark(unsigned long) @ 0x000000004768d5ab in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:283: DB::getStream(bool, DB::ISerialization::SubstreamPath const&, std::map<String, std::unique_ptr<DB::MergeTreeReaderStream, std::default_delete<DB::MergeTreeReaderStream>>, std::less<String>, std
 [ 43212 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:347: operator()
 [ 43212 ] {} <Fatal> BaseDaemon: 20.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<D
 [ 43212 ] {} <Fatal> BaseDaemon: 20.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:470: DB::ReadBuffer* std::__invoke_void_return_wrapper<DB::ReadBuffer*, false>::__call<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISe
 [ 43212 ] {} <Fatal> BaseDaemon: 20.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn
 [ 43212 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: DB::ReadBuffer* std::__function::__policy_invoker<DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeReader
 [ 43212 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./src/DataTypes/Serializations/ISerialization.cpp:0: DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB:
 [ 43212 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:0: DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, std::shared_ptr<DB::ISerialization const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, 
 [ 43212 ] {} <Fatal> BaseDaemon: 23. ./build_docker/./src/Storages/MergeTree/MergeTreeReaderWide.cpp:159: DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB:
 [ 43212 ] {} <Fatal> BaseDaemon: 24. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:107: DB::MergeTreeRangeReader::DelayedStream::readRows(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x0
 [ 43212 ] {} <Fatal> BaseDaemon: 25. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:179: DB::MergeTreeRangeReader::DelayedStream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) @ 0x00000000476b7bd3
 [ 43212 ] {} <Fatal> BaseDaemon: 26.1. inlined from ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:0: DB::MergeTreeRangeReader::Stream::finalize(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
 [ 43212 ] {} <Fatal> BaseDaemon: 26. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:1230: DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult const&, unsigned long&) @ 0x00000000476c556a in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 27. ./build_docker/./src/Storages/MergeTree/MergeTreeRangeReader.cpp:979: DB::MergeTreeRangeReader::read(unsigned long, DB::MarkRanges&) @ 0x00000000476c30cf in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 28. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:408: DB::IMergeTreeSelectAlgorithm::readFromPartImpl() @ 0x00000000476b1548 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 29. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:451: DB::IMergeTreeSelectAlgorithm::readFromPart() @ 0x00000000476b21b7 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 30. ./build_docker/./src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp:168: DB::IMergeTreeSelectAlgorithm::read() @ 0x00000000476ad3a1 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 31. ./build_docker/./src/Storages/MergeTree/MergeTreeSource.cpp:0: DB::MergeTreeSource::tryGenerate() @ 0x00000000485ba80a in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 32.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/optional:344: std::__optional_storage_base<DB::Chunk, false>::has_value[abi:v15000]() const
 [ 43212 ] {} <Fatal> BaseDaemon: 32.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/optional:998: std::optional<DB::Chunk>::operator bool[abi:v15000]() const
 [ 43212 ] {} <Fatal> BaseDaemon: 32. ./build_docker/./src/Processors/ISource.cpp:94: DB::ISource::work() @ 0x0000000047c53f96 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 33.1. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
 [ 43212 ] {} <Fatal> BaseDaemon: 33. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x0000000047c7e650 in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 34. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000047c6d93b in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 35.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833: std::shared_ptr<DB::ThreadGroup>::operator bool[abi:v15000]() const
 [ 43212 ] {} <Fatal> BaseDaemon: 35.2. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:332: operator()
 [ 43212 ] {} <Fatal> BaseDaemon: 35.3. inlined from ./build_docker/./base/base/../base/scope_guard.h:99: BasicScopeGuard<DB::PipelineExecutor::spawnThreads()::$_0::operator()() const::\'lambda\'()>::invoke()
 [ 43212 ] {} <Fatal> BaseDaemon: 35.4. inlined from ./build_docker/./base/base/../base/scope_guard.h:48: ~BasicScopeGuard
 [ 43212 ] {} <Fatal> BaseDaemon: 35.5. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:351: operator()
 [ 43212 ] {} <Fatal> BaseDaemon: 35.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spaw
 [ 43212 ] {} <Fatal> BaseDaemon: 35.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
 [ 43212 ] {} <Fatal> BaseDaemon: 35.8. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]()
 [ 43212 ] {} <Fatal> BaseDaemon: 35. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_st
 [ 43212 ] {} <Fatal> BaseDaemon: 36.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 43212 ] {} <Fatal> BaseDaemon: 36.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 43212 ] {} <Fatal> BaseDaemon: 36.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 43212 ] {} <Fatal> BaseDaemon: 36.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 43212 ] {} <Fatal> BaseDaemon: 36. ./build_docker/./src/Common/ThreadPool.cpp:429: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000037f453dc in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 37. ./build_docker/./src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::\'lambda0\'()>(v
 [ 43212 ] {} <Fatal> BaseDaemon: 38.1. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:809: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 43212 ] {} <Fatal> BaseDaemon: 38.2. inlined from ./build_docker/./base/base/../base/wide_integer_impl.h:1482: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
 [ 43212 ] {} <Fatal> BaseDaemon: 38.3. inlined from ./build_docker/./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
 [ 43212 ] {} <Fatal> BaseDaemon: 38.4. inlined from ./build_docker/./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
 [ 43212 ] {} <Fatal> BaseDaemon: 38. ./build_docker/./src/Common/ThreadPool.cpp:429: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x0000000037f41e1c in /usr/bin/clickhouse
 [ 43212 ] {} <Fatal> BaseDaemon: 39.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
 [ 43212 ] {} <Fatal> BaseDaemon: 39.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 43212 ] {} <Fatal> BaseDaemon: 39.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
 [ 43212 ] {} <Fatal> BaseDaemon: 39.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
 [ 43212 ] {} <Fatal> BaseDaemon: 39.5. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(st
 [ 43212 ] {} <Fatal> BaseDaemon: 39.6. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::
 [ 43212 ] {} <Fatal> BaseDaemon: 39.7. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 43212 ] {} <Fatal> BaseDaemon: 39. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function
 [ 43212 ] {} <Fatal> BaseDaemon: 40. ? @ 0x00007f22cb924b43 in ?
 [ 43212 ] {} <Fatal> BaseDaemon: 41. ? @ 0x00007f22cb9b6a00 in ?
 [ 43212 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: DCB92BF79A88B6D4F7A2370019592EB0)
 [ 43212 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
 [ 43212 ] {} <Fatal> BaseDaemon: Changed settings: min_compress_block_size = 91830, max_compress_block_size = 34958, max_block_size = 11163, max_insert_threads = 12, max_threads = 29, max_read_buffer_size = 1028472, connect_timeout_with_failover_ms = 2000, connect_timeout_with_failover_secure_ms = 
 [ 1689 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

cc: @kssenii, @devcrafter

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Follow up to https://github.com/ClickHouse/ClickHouse/pull/61723.
Closes https://github.com/ClickHouse/ClickHouse/issues/51819.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

File: src/Interpreters/Cache/EvictionCandidates.cpp [hunk 1]
```diff
@@ -159,56 +159,68 @@ void EvictionCandidates::evict()
...
     size_t elements,
     IFileCachePriority & priority,
     const CachePriorityGuard::Lock & lock)
 {
-    if (hold_space)
-        throw Exception(ErrorCodes::LOGICAL_ERROR, "Space hold is already set");
-    else
-        hold_space = std::make_unique<IFileCachePriority::HoldSpace>(size, elements, priority, lock);
+    /// Currently we can have more than one space holder during dynamic cache resize.
+    hold_space.emplace_back(std::make_unique<IFileCachePriority::HoldSpace>(size, elements, priority, lock));
```
Comment (kssenii) [inline src/Interpreters/Cache/EvictionCandidates.cpp:217]: first fix -- adding vector

File: src/Interpreters/Cache/FileCache.cpp [hunk 2]
```diff
@@ -1414,45 +1414,69 @@ void FileCache::applySettingsIfPossible(const FileCacheSettings & new_settings,
...
-            }
-            catch (...)
-            {
-                if (eviction_candidates.needFinalize())
-                    eviction_candidates.finalize(nullptr, lockCache());
-                throw;
-            }
-
-            if (eviction_candidates.needFinalize())
-                eviction_candidates.finalize(nullptr, lockCache());
```
Comment (kssenii) [inline src/Interpreters/Cache/FileCache.cpp:1450]: Second fix -- we did not always call finalize, but we should have because we needed to release space holders

**Review by kssenii — COMMENTED** [review]
There are two fixes, changes apart from them is refactoring

File: src/Interpreters/Cache/EvictionCandidates.cpp [hunk 3]
```diff
@@ -159,56 +159,68 @@ void EvictionCandidates::evict()
...
+}
+
+void EvictionCandidates::releaseSpaceHolders()
+{
+    for (const auto & holder : hold_space)
+        holder->release();
```
Comment (vdimir) [inline src/Interpreters/Cache/EvictionCandidates.cpp:223]: Can we just use `hold_space.clear()`? In fact, there's not a big difference, though.

File: src/Interpreters/Cache/FileCache.cpp [hunk 4]
```diff
@@ -1414,45 +1414,69 @@ void FileCache::applySettingsIfPossible(const FileCacheSettings & new_settings,
...
+                    try
+                    {
+                        /// Do actual eviction from filesystem.
+                        eviction_candidates.evict();
+                    }
+                    catch (...)
+                    {
+                        tryLogCurrentException(__PRETTY_FUNCTION__);
+                        finalize_eviction();
+                        throw;
```
Comment (vdimir) [inline src/Interpreters/Cache/FileCache.cpp:1461]: As far as we re-throw exception, logging here may be excessive, but shouldn't be an issue anyway.

File: src/Interpreters/Cache/FileCache.cpp [hunk 5]
```diff
@@ -1414,45 +1414,69 @@ void FileCache::applySettingsIfPossible(const FileCacheSettings & new_settings,
...
+                    auto finalize_eviction = [&]()
+                    {
+                        if (eviction_candidates.requiresLockToFinalize())
+                        {
+                            cache_lock.lock();
+                            eviction_candidates.finalize(nullptr, &cache_lock);
+                        }
+                        else
+                            eviction_candidates.finalize(nullptr);
+                    };
```
Comment (vdimir) [inline src/Interpreters/Cache/FileCache.cpp:1450]: Perhaps we can just wrap it with `SCOPE_EXIT`

File: src/Interpreters/Cache/EvictionCandidates.cpp [hunk 6]
```diff
@@ -159,56 +159,68 @@ void EvictionCandidates::evict()
...
+    else
+    {
+        chassert(on_finalize.empty() && queue_entries_to_invalidate.empty());
+    }
 }
 
-bool EvictionCandidates::needFinalize() const
+bool EvictionCandidates::requiresLockToFinalize() const
 {
     /// Do we need to call finalize()?
```
Comment (vdimir) [inline src/Interpreters/Cache/EvictionCandidates.cpp:206]: The comment seems to be outdated. Please add details explaining why we need or don't need a lock to finalize and if we always finalize.

File: src/Interpreters/Cache/FileCache.cpp (hunk 4 above)
Comment (kssenii) [reply src/Interpreters/Cache/FileCache.cpp:1461]: Yeah, I just thought that may be good to log it in case there is an exception from finalize_eviction(), but I agree better to remove

File: src/Interpreters/Cache/SLRUFileCachePriority.cpp [hunk 7]
```diff
@@ -269,17 +269,22 @@ bool SLRUFileCachePriority::collectCandidatesForEviction(
...
     chassert(!max_candidates_to_evict || res.size() <= max_candidates_to_evict);
     chassert(res.size() == stat.total_stat.releasable_count);
 
     if (max_candidates_to_evict && res.size() >= max_candidates_to_evict)
         return probationary_limit_satisfied;
 
-    const auto desired_protected_size = getRatio(max_size, size_ratio);
-    const auto desired_protected_elements_num = getRatio(max_elements, size_ratio);
+    const auto desired_protected_size = getRatio(desired_size, size_ratio);
+    const auto desired_protected_elements_num = getRatio(desired_elements_count, size_ratio);
```
Comment (kssenii) [inline src/Interpreters/Cache/SLRUFileCachePriority.cpp:287]: After adding more logs in this PR and seeing the error still present in stress test I found the actual bug is here. Will add a unit test for this. Will mark this PR as non-draft after all stress tests pass.

**Comment by kssenii** [comment]
> AST fuzzer (asan)
AST fuzzer (debug)

https://github.com/ClickHouse/ClickHouse/issues/62593

**Review by vdimir — APPROVED** [review]
More or less clear, comments are really helpful.
I’m 87.6% sure I understand what's going on here
