### PR TITLE
Remove Sparse columns from header in merge algorithms

### LINKED ISSUE #91377: CoalescingMergeTree table engine returns `Too large size (..) passed to allocator` in 25.11.2
### Company or project name

_No response_

### Describe what's wrong

We are seeing an error that started to happen with CoalescingMergeTree table engine in ClickHouse 25.11.2, but was working in 25.11.1:
> Too large size (18446464455627382046) passed to allocator

Repro: https://fiddle.clickhouse.com/17ed121f-2d03-42c3-a3a6-371b1a2dce19

### Does it reproduce on the most recent release?

Yes

### How to reproduce

See fiddle link above (works in 25.11.1, errors in 25.11.2)

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Remove Sparse columns from header in merge algorithms. Closes https://github.com/ClickHouse/ClickHouse/issues/91377

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by vdimir — APPROVED** [review]

File: tests/queries/0_stateless/03751_summing_coalescing_merge_tree_sparse_columns_in_header.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
+drop table if exists src;
+create table src (x UInt64) engine=MergeTree order by tuple();
+insert into src select 0 from numbers(1000000);
```
Comment (PedroTadim) [inline tests/queries/0_stateless/03751_summing_coalescing_merge_tree_sparse_columns_in_header.sql:3]: May I ask why 1000000 rows are needed?

Comment (Avogar) [reply tests/queries/0_stateless/03751_summing_coalescing_merge_tree_sparse_columns_in_header.sql:3]: No particular reason, we can reduce it later (don't want to rerun the ci for this)
