### PR TITLE
Limit the number of parallel tasks of the same type in `BackgroundSchedulePool`

### LINKED ISSUE #81500: If I specify a low size of the global thread pool in the server configuration, it hangs
### Company or project name

ClickHouse

### Describe the unexpected behaviour

`./clickhouse-server -- --max_thread_pool_size 631`

On my machine, value 631 is too low, and 632 is the minimal working value.

### Which ClickHouse versions are affected?

25.6.

### How to reproduce

.

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Limit the number of tasks of each type in `BackgroundSchedulePool`. Avoid situations when all slots are occupied by task of one type, while other tasks are starving. Also avoids deadlocks when tasks wait for each other. This is controlled by `background_schedule_pool_max_parallel_tasks_per_type_ratio` server setting

Probably fixes https://github.com/ClickHouse/ClickHouse/issues/81500 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Core/BackgroundSchedulePool.cpp [hunk 1]
```diff
@@ -361,15 +389,45 @@ void BackgroundSchedulePool::threadFunction()
             if (shutdown)
                 break;
 
-            if (!tasks.empty())
+            if (runnable_task_types.empty())
+                continue;
+
+            task_type_to_run = runnable_task_types[thread_local_rng() % runnable_task_types.size()];
```
Comment (serxa) [inline src/Core/BackgroundSchedulePool.cpp:398]: A round-robin over groups might be a bit more fair and faster because we are under lock here anyway

Comment (tavplubix) [reply src/Core/BackgroundSchedulePool.cpp:398]: I thought about simple round-robin initially, but I'm not sure how many different types of tasks we have, and it would need to iterate through all groups until it finds something that it can execute, so I implemented O(1) task selection. And I'm not sure how to impelement round-robin over `runnable_task_types` because we move elements there

**Review by serxa — APPROVED** [review]
