### PR TITLE
Fix a crash in clickhouse-client syntax highlighting

### LINKED ISSUE #71864: UBSAN error on UTF8 helper message
**Company or project name**

Clickhouse employee :smile: 

**Describe what's wrong**

UBSAN gives an error when trying to edit a PARTITION expression.

**Does it reproduce on the most recent release?**

Yes.

**How to reproduce**

Compile and link Clickhouse using UBSAN, then open the client and type:

```sql
alter table t0 update c1 = 1 in partition (x+1) where true;
```
Before hitting enter, place the cursor on `x` and delete it with backspace. UBSAN will report an error.

**Expected behavior**

No error from UBSAN.

**Error message and/or stacktrace**

Stack trace:
```
build/src/Common/UTF8Helpers.h:64:29: runtime error: addition of unsigned offset to 0x5684ecc8063d overflowed to 0x5684ecc8063c
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /build/src/Common/UTF8Helpers.h:64:29 
########## Short fault info ############
(version 24.11.1.1576 (official build), build id: , git hash: 9caac43b2aa5e7c5474a87b7596dea95f5a2569a, architecture: x86_64) (from thread 1368149) Received signal -3
Signal description: sanitizer trap
Sanitizer trap.
Stack trace: 0x00005684b02a8f57 0x00005684b0732567 0x00005684a3f54446 0x00005684a3f60f1f 0x00005684a6d1c476 0x00005684bfcca5b4 0x00005684c406d328 0x00005684c406aab5 0x00005684c4066aec 0x00005684c4066631 0x00005684c4065b32 0x00005684c406c299 0x00005684c406be54 0x00005684bfd794b4 0x00005684bfd4de36 0x00005684bfcb8c3b 0x00005684b05e7e4a 0x00005684c3b4eb93 0x00005684b05ffb99 0x00005684a3f63ccd 0x00007650e902a3b8 0x00007650e902a47b 0x00005684a3f4b02e
########################################
(version 24.11.1.1576 (official build), build id: , git hash: 9caac43b2aa5e7c5474a87b7596dea95f5a2569a) (from thread 1368149) (no query) Received signal sanitizer trap (-3)
Sanitizer trap.
Stack trace: 0x00005684b02a8f57 0x00005684b0732567 0x00005684a3f54446 0x00005684a3f60f1f 0x00005684a6d1c476 0x00005684bfcca5b4 0x00005684c406d328 0x00005684c406aab5 0x00005684c4066aec 0x00005684c4066631 0x00005684c4065b32 0x00005684c406c299 0x00005684c406be54 0x00005684bfd794b4 0x00005684bfd4de36 0x00005684bfcb8c3b 0x00005684b05e7e4a 0x00005684c3b4eb93 0x00005684b05ffb99 0x00005684a3f63ccd 0x00007650e902a3b8 0x00007650e902a47b 0x00005684a3f4b02e
0. src/Common/StackTrace.cpp:380: StackTrace::tryCapture() @ 0x0000000025603f57
1.0. inlined from ./src/Common/StackTrace.h:48: StackTrace
1. src/Common/SignalHandlers.cpp:186: sanitizerDeathCallback() @ 0x0000000025a8d567
2. __sanitizer::Die() @ 0x00000000192af446
3. ? @ 0x00000000192bbf1f
4. DB::UTF8::countCodePoints(char8_t const*, unsigned long) @ 0x000000001c077476
5. src/Client/ClientBaseHelpers.cpp:182: DB::highlight(String const&, std::vector<replxx::Replxx::Color, std::allocator<replxx::Replxx::Color>>&, DB::Context const&) @ 0x00000000350255b4
6.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ?
6.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:1197: ?
6. contrib/replxx/src/replxx_impl.cxx:810: replxx::Replxx::ReplxxImpl::render(replxx::Replxx::ReplxxImpl::HINT_ACTION) @ 0x00000000393c8328
7. contrib/replxx/src/replxx_impl.cxx:1003: replxx::Replxx::ReplxxImpl::refresh_line(replxx::Replxx::ReplxxImpl::HINT_ACTION, bool) @ 0x00000000393c5ab5
8. contrib/replxx/src/replxx_impl.cxx:1858: replxx::Replxx::ReplxxImpl::backspace_character(char32_t) @ 0x00000000393c1aec
9. contrib/replxx/src/replxx_impl.cxx:1440: replxx::Replxx::ReplxxImpl::action(unsigned long long, replxx::Replxx::ACTION_RESULT (replxx::Replxx::ReplxxImpl::* const&)(char32_t), char32_t) @ 0x00000000393c1631
10. contrib/replxx/src/replxx_impl.cxx:0: replxx::Replxx::ReplxxImpl::invoke(replxx::Replxx::ACTION, char32_t) @ 0x00000000393c0b32
11.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ?
11.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:1197: ?
11. contrib/replxx/src/replxx_impl.cxx:1426: replxx::Replxx::ReplxxImpl::get_input_line() @ 0x00000000393c7299
12. contrib/replxx/src/replxx_impl.cxx:671: replxx::Replxx::ReplxxImpl::input(String const&) @ 0x00000000393c6e54
13. src/Client/ReplxxLineReader.cpp:498: DB::ReplxxLineReader::readOneLine(String const&) @ 0x00000000350d44b4
14. src/Client/LineReader.cpp:159: DB::LineReader::readLine(String const&, String const&) @ 0x00000000350a8e36
15. src/Client/ClientBase.cpp:2732: DB::ClientBase::runInteractive() @ 0x0000000035013c3b
16. programs/client/Client.cpp:399: DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000025942e4a
17. base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x0000000038ea9b93
18. programs/client/Client.cpp:1388: mainEntryClickHouseClient(int, char**) @ 0x000000002595ab99
19. programs/main.cpp:246: main @ 0x00000000192beccd
20. ? @ 0x00007650e902a3b8
21. ? @ 0x00007650e902a47b
22. _start @ 0x00000000192a602e
```

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a crash in clickhouse-client syntax highlighting. Closes https://github.com/ClickHouse/ClickHouse/issues/71864

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 0bd6a1fb04fca136f21043463892524567263214 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71949/0bd6a1fb04fca136f21043463892524567263214/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/acd4f46d9c703b5f8bb757555e6d085c0ea0a5fa/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by alexey-milovidov — APPROVED** [review]

File: src/Parsers/IParser.cpp [hunk 1]
```diff
@@ -45,6 +45,10 @@ void Expected::highlight(HighlightedRange range)
         return;
 
     auto it = highlights.lower_bound(range);
+
+    if (it != highlights.begin())
+        it = std::prev(it);
+
     while (it != highlights.end() && range.begin < it->end)
```
Comment (tavplubix) [inline src/Parsers/IParser.cpp:52]: Please add a comment. It should be enough to check only one range to the left because it contains non-intersecting ranges ordered by `begin`. So if it's not intersecting with the current one, then all ranges the the left should be fine too
