### PR TITLE
Fix possible missing subcolumn in MV during alter of source table

### LINKED ISSUE #93231: Alter Statements fail due to Dot Notation used on a JSON column in a Materialized View
### Company or project name

Bloomberg

### Describe the unexpected behaviour

When I issue an alter statement on my table, the query fails due to a syntax issue with the materialized view. The materialized view uses dot notation on a JSON column. If I remove that statement, or adjust the statement to use `getSubcolumn` instead, the materialized view syntactically passes and so does the alter statement.

### Which ClickHouse versions are affected?

25.11.3.54

### How to reproduce

* **Version**: 25.11.3.54
* **DDL** Statements:

Main Table:
```
SET allow_experimental_json_type = 1;

DROP DATABASE IF EXISTS dtobs;
CREATE DATABASE dtobs;
USE dtobs;

CREATE TABLE span_local
(
    links Array(JSON),
    dummy UInt8
)
ENGINE = MergeTree
ORDER BY tuple();

-- Target table: ONE column
CREATE TABLE span_link_local
(
    linked_id String
)
ENGINE = MergeTree
ORDER BY tuple();
```

Materialized View:
```
CREATE MATERIALIZED VIEW mv_bad
TO span_link_local
AS
SELECT
    link.`trace_id` AS linked_id
FROM
(
    SELECT arrayJoin(links) AS link
    FROM span_local
)
WHERE linked_id IS NOT NULL;
```
* **sample data**: not needed
* **query to run**:
```
ALTER TABLE span_local DROP COLUMN dummy;
```

### Expected behavior

When I drop the `dummy` column, I'd expect the drop to happen with no problem. Instead, the query fails because of the faulty materialized view which complains about the `WHERE linked_id IS NOT NULL;` clause.

### Error message and/or stacktrace

```
Received exception from server (version 25.11.3):
Code: 47. DB::Exception: Received from ch_s1r1:9000. DB::Exception: Missing columns: 'link.trace_id' while processing: 'SELECT arrayJoin(links) AS link FROM dtobs.span_local WHERE link.trace_id IS NOT NULL', required columns: 'link.trace_id' 'links', maybe you meant: 'links'. (UNKNOWN_IDENTIFIER)
```

### Additional context

Interestingly, if I switch the materialized view to use `getSubcolumn` instead of dot notation, the alter statement passes. The below code demonstrates that:

```
DROP VIEW mv_bad;

CREATE MATERIALIZED VIEW mv_good
TO span_link_local
AS
SELECT
    getSubcolumn(link, 'trace_id') AS linked_id
FROM
(
    SELECT arrayJoin(links) AS link
    FROM span_local
)
WHERE getSubcolumn(link, 'trace_id') IS NOT NULL;
```

Then

```
ALTER TABLE span_local DROP COLUMN dummy;
```

Result:
```
Ok.

0 rows in set. Elapsed: 0.008 sec.
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix possible missing subcolumn in MV during alter of source table. Closes https://github.com/ClickHouse/ClickHouse/issues/93231

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.655`

### CODE REVIEW

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 1]
```diff
@@ -2083,8 +2084,13 @@ ExpressionAnalysisResult::ExpressionAnalysisResult(
                     before_where_sample = source_header;
                 if (sanitizeBlock(before_where_sample))
                 {
+                    auto dag = before_where->dag.clone();
+                    auto extracting_subcolumns_dag = createSubcolumnsExtractionActions(before_where_sample, dag.getRequiredColumnsNames(), context);
```
Comment (KochetovNicolai) [inline src/Interpreters/ExpressionAnalyzer.cpp:2090]: Please add a comment why `createSubcolumnsExtractionActions` is needed.

**Review by KochetovNicolai — APPROVED** [review]

File: src/Planner/collectSelectedColumnsFromTable.h [hunk 2]
```diff
@@ -0,0 +1,13 @@
+#pragma once
+
+#include <Analyzer/IQueryTreeNode.h>
+#include <Interpreters/StorageID.h>
+#include <Interpreters/Context_fwd.h>
+
+namespace DB
+{
+
+/// Collect list of selected columns for a specific table from query tree.
```
Comment (novikd) [inline src/Planner/collectSelectedColumnsFromTable.h:10]: Let's add a comment that it should work similarly to `collectTableExpressionData`.

**Review by novikd — APPROVED** [review]
