### PR TITLE
Setting JoinAlgorithm respect specified order

### LINKED ISSUE #46543: Join with a dictionary checks join_algorithm incorrectly
The documentation states that join_algorithm = default (and default = 'direct,hash').

```sql
23.1.3.5

drop database test;
create database test;

create table if not exists test.src( id UInt64,  s  String ) engine = MergeTree() order by id
as  select number, toString(number) from numbers(1000000);

create dictionary test.dict(
  id UInt64,
  s  String 
) primary key id
source( clickhouse (table 'src'  db 'test'))
lifetime (MIN 0 MAX 0)
layout(HASHED());

select * from system.settings where name = 'join_algorithm';
┌─name───────────┬─value───┬
│ join_algorithm │ default │
└────────────────┴─────────┴

select s from (select toUInt64(9911) id) x inner join test.dict z using id;
┌─s────┐
│ 9911 │
└──────┘
1 row in set. Elapsed: 0.094 sec. Processed 1.00 million rows, 22.89 MB (10.65 million rows/s., 243.77 MB/s.)


set join_algorithm='direct,hash';

select s from (select toUInt64(9911) id) x inner join test.dict z using id;
┌─s────┐
│ 9911 │
└──────┘
1 row in set. Elapsed: 0.009 sec.


set join_algorithm='hash,direct';

select s from (select toUInt64(9911) id) x inner join test.dict z using id;
┌─s────┐
│ 9911 │
└──────┘
1 row in set. Elapsed: 0.011 sec.
```

### LINKED ISSUE #50589: setting join_algorithm is not working as expected based on docs
Working with EmbeddedRocksDB and joins, it seems to me that the `default` setting for `join_algorithm` is not equivalent to `direct,hash` as stated in the docs.  I am using `explain` to see the difference, but maybe that is not the right way?.  (full example at end)

**How to reproduce**
* Which ClickHouse server version to use: head
* Non-default settings, if any:
  * `SET join_algorithm = 'direct'`
  * `SET join_algorithm = 'default'`
  * `SET join_algorithm = 'direct, hash'`
  * `SET join_algorithm = 'hash'`
* `CREATE TABLE` statements for all tables involved

**Expected behavior**
I expect the explain for `SET join_algorithm = 'direct'`, SET join_algorithm = 'default'`, and `SET join_algorithm = 'direct, hash' to all be the same.

## Setup
```sql
CREATE TABLE rdb
(
    `key` UInt32,
    `value` Array(UInt32),
    `value2` String
)
ENGINE = EmbeddedRocksDB
PRIMARY KEY key


INSERT INTO rdb SELECT
    toUInt32(sipHash64(number) % 10) AS key,
    [key, key + 1] AS value,
    concat('val2', toString(key)) AS value2
FROM numbers_mt(10)


CREATE TABLE t2
(
    `k` UInt16
)
ENGINE = TinyLog


INSERT INTO t2 SELECT number AS k
FROM numbers_mt(10)


SELECT *
FROM system.settings
WHERE name = 'join_algorithm'
FORMAT Vertical


Row 1:
──────
name:        join_algorithm
value:       default
changed:     0
description: Specify join algorithm.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        JoinAlgorithm
default:     default
alias_for:   


```
## Using above default setting for join_algorithm
```sql
EXPLAIN
SELECT *
FROM
(
    SELECT k AS key
    FROM t2
) AS t2
INNER JOIN rdb ON rdb.key = t2.key
ORDER BY key ASC

Query id: 4fc42192-ddba-4326-911d-3cabe8faf547

┌─explain─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                                                                     │
│   Sorting (Sorting for ORDER BY)                                                                                            │
│     Expression (Before ORDER BY)                                                                                            │
│       Join (JOIN FillRightFirst)                                                                                            │
│         Expression ((Convert JOIN columns + (Before JOIN + (Projection + Before ORDER BY))))                                │
│           ReadFromStorage (TinyLog)                                                                                         │
│         Expression ((Convert joined columns + (Joined actions + (Rename joined columns + (Projection + Before ORDER BY))))) │
│           ReadFromStorage (EmbeddedRocksDB)                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

## Using `direct, hash` (which based on docs should == `default`)
```sql
SET join_algorithm = 'direct, hash'


fedora :) explain SELECT *
FROM
(
    SELECT k AS key
    FROM t2
) AS t2
INNER JOIN rdb ON rdb.key = t2.key
ORDER BY key ASC

EXPLAIN
SELECT *
FROM
(
    SELECT k AS key
    FROM t2
) AS t2
INNER JOIN rdb ON rdb.key = t2.key
ORDER BY key ASC


┌─explain──────────────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                                      │
│   Sorting (Sorting for ORDER BY)                                                             │
│     Expression (Before ORDER BY)                                                             │
│       FilledJoin (JOIN)                                                                      │
│         Expression ((Convert JOIN columns + (Before JOIN + (Projection + Before ORDER BY)))) │
│           ReadFromStorage (TinyLog)                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
```

## Using hash
```sql
SET join_algorithm = 'hash'

EXPLAIN
SELECT *
FROM
(
    SELECT k AS key
    FROM t2
) AS t2
INNER JOIN rdb ON rdb.key = t2.key
ORDER BY key ASC


┌─explain─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                                                                     │
│   Sorting (Sorting for ORDER BY)                                                                                            │
│     Expression (Before ORDER BY)                                                                                            │
│       Join (JOIN FillRightFirst)                                                                                            │
│         Expression ((Convert JOIN columns + (Before JOIN + (Projection + Before ORDER BY))))                                │
│           ReadFromStorage (TinyLog)                                                                                         │
│         Expression ((Convert joined columns + (Joined actions + (Rename joined columns + (Projection + Before ORDER BY))))) │
│           ReadFromStorage (EmbeddedRocksDB)                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

cc: @vdimir

### LINKED ISSUE #50813: join_algorithm does not respect the order/priority of algorithms
23.3.2.37

```sql
SET join_algorithm = 'grace_hash, hash', 
max_memory_usage='30G', grace_hash_join_initial_buckets=4, grace_hash_join_max_buckets=4;

SELECT query

Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 27.95 GiB



SET join_algorithm = 'grace_hash', 
max_memory_usage='30G', grace_hash_join_initial_buckets=4, grace_hash_join_max_buckets=4;

SELECT query

1 row in set. Elapsed: 70.380 sec. Processed 24.51 million rows, 40.95 GB (348.25 thousand rows/s., 581.91 MB/s.)
```

-------

why do I need both?

grace_hash -- does not support some of types of joins

```
Cannot load data for command line suggestions: Code: 48. DB::Exception:DB::Exception:
 Can't execute GRACE_HASH join algorithm for this strictness/kind and right storage type. 
(NOT_IMPLEMENTED) (version 23.3.2.37 (official build))
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Setting `join_algorithm` respects specified order

close https://github.com/ClickHouse/ClickHouse/issues/46543
close https://github.com/ClickHouse/ClickHouse/issues/50813
close https://github.com/ClickHouse/ClickHouse/issues/50589

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 8e6b4b5313a42bd990950186fce7a1ed1969bad6 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51745/8e6b4b5313a42bd990950186fce7a1ed1969bad6/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Comment by UnamedRus** [comment]
Have some ability to set priority of joins algos is must have feature (or we need to modify to change priority), because right now `full_sorting` merge join is behind `grace_hash`

**Comment by vdimir** [comment]
Old PR waiting for review. Sorry for pinging, I have just chosen some random people for the team to request a review

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -1645,7 +1645,6 @@ void InterpreterSelectQuery::executeImpl(QueryPlan & query_plan, std::optional<P
                         expressions.join,
                         settings.max_block_size);
 
-                    filled_join_step->setStepDescription("JOIN");
```
Comment (novikd) [inline src/Interpreters/InterpreterSelectQuery.cpp:1648]: Why?

File: src/Storages/MySQL/MySQLSettings.h [hunk 2]
```diff
@@ -24,7 +24,7 @@ class ASTSetQuery;
     M(Bool, connection_auto_close, true, "Auto-close connection after query execution, i.e. disable connection reuse.", 0) \
     M(UInt64, connect_timeout, DBMS_DEFAULT_CONNECT_TIMEOUT_SEC, "Connect timeout (in seconds)", 0) \
     M(UInt64, read_write_timeout, DBMS_DEFAULT_RECEIVE_TIMEOUT_SEC, "Read/write timeout (in seconds)", 0) \
-    M(MySQLDataTypesSupport, mysql_datatypes_support_level, 0, "Which MySQL types should be converted to corresponding ClickHouse types (rather than being represented as String). Can be empty or any combination of 'decimal' or 'datetime64'. When empty MySQL's DECIMAL and DATETIME/TIMESTAMP with non-zero precision are seen as String on ClickHouse's side.", 0) \
+    M(MySQLDataTypesSupport, mysql_datatypes_support_level, {}, "Which MySQL types should be converted to corresponding ClickHouse types (rather than being represented as String). Can be empty or any combination of 'decimal' or 'datetime64'. When empty MySQL's DECIMAL and DATETIME/TIMESTAMP with non-zero precision are seen as String on ClickHouse's side.", 0) \
```
Comment (novikd) [inline src/Storages/MySQL/MySQLSettings.h:27]: I think it's better to write specific value, not the default constructor.

**Review by novikd — COMMENTED** [review]
LGTM

File: src/Interpreters/InterpreterSelectQuery.cpp (hunk 1 above)
Comment (vdimir) [reply src/Interpreters/InterpreterSelectQuery.cpp:1648]: Incorrect merge with https://github.com/ClickHouse/ClickHouse/pull/53006, will restore this line

File: src/Core/Settings.h [hunk 3]
```diff
@@ -587,7 +587,7 @@ class IColumn;
...
     M(Bool, allow_experimental_database_materialized_postgresql, false, "Allow to create database with Engine=MaterializedPostgreSQL(...).", 0) \
     M(Bool, system_events_show_zero_values, false, "When querying system.events or system.metrics tables, include all metrics, even with zero values.", 0) \
-    M(MySQLDataTypesSupport, mysql_datatypes_support_level, 0, "Which MySQL types should be converted to corresponding ClickHouse types (rather than being represented as String). Can be empty or any combination of 'decimal', 'datetime64', 'date2Date32' or 'date2String'. When empty MySQL's DECIMAL and DATETIME/TIMESTAMP with non-zero precision are seen as String on ClickHouse's side.", 0) \
+    M(MySQLDataTypesSupport, mysql_datatypes_support_level, {}, "Which MySQL types should be converted to corresponding ClickHouse types (rather than being represented as String). Can be empty or any combination of 'decimal', 'datetime64', 'date2Date32' or 'date2String'. When empty MySQL's DECIMAL and DATETIME/TIMESTAMP with non-zero precision are seen as String on ClickHouse's side.", 0) \
```
[the remark this answers is not in the document]
Comment (vdimir) [reply src/Core/Settings.h]: Since this setting is a MultiEnum, `0` was passed to this constructor indicating an empty `MultiEnum`: https://github.com/ClickHouse/ClickHouse/blob/335e7bf7ef5ab3ed820caaed7c7aec1caad4096c/src/Core/SettingsFields.h#L470

I've modified the code to store a vector instead of a `MultiEnum` in `SettingFieldMultiEnum` and removed this constructor. To maintain the same behavior, we should initialize the setting with an empty value. After the change, we have these constructors: https://github.com/ClickHouse/ClickHouse/blob/d336b60a1943462549b5385f40d4efdf7ac8fafa/src/Core/SettingsFields.h#L467-L469

Let's specify `std::vector<MySQLDataTypesSupport>{}` here instead of `{}` to make it clearer what value the setting will have.

File: src/Storages/MySQL/MySQLSettings.h (hunk 2 above)
Comment (vdimir) [reply src/Storages/MySQL/MySQLSettings.h]: Changed to `std::vector<MySQLDataTypesSupport>{}`

File: src/Core/Settings.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (novikd) [reply src/Core/Settings.h]: Let's do `using MySQLDataTypesSupportList = std::vector<MySQLDataTypesSupport>;` and use `MySQLDataTypesSupportList{}` everywhere.

[the remark this answers is not in the document]
Comment (vdimir) [reply src/Core/Settings.h]: Ok, then it probably makes sense to introduce `*List` using's for all multi enum settings (now only `JoinAlgorithm` and `MySQLDataTypesSupport`) so I added this definition into `DECLARE_SETTING_MULTI_ENUM`

**Comment by vdimir** [comment]
> Stress test (ubsan) — Killed by signal (in clickhouse-server.log) [Details](https://s3.amazonaws.com/clickhouse-test-reports/51745/b74840597637a7ff68fd64e2f217d953a734f4af/stress_test__ubsan_.html)

https://github.com/ClickHouse/ClickHouse/issues/43303

> Integration tests (release) [4/4] — fail: 1, passed: 653 [Details](https://s3.amazonaws.com/clickhouse-test-reports/51745/b74840597637a7ff68fd64e2f217d953a734f4af/integration_tests__release__[4_4].html)

`test_broken_part_during_merge/test.py::test_merge_and_part_corruption`

Query `OPTIMIZE` timed out:

<details>
<summary>run.log</summary>

```
=================================== FAILURES ===================================
________________________ test_merge_and_part_corruption ________________________
[gw2] linux -- Python 3.10.12 /usr/bin/python3

started_cluster = <helpers.cluster.ClickHouseCluster object at 0x7fef48bae980>

    def test_merge_and_part_corruption(started_cluster):
        node1.query(
            """
            CREATE TABLE replicated_mt(date Date, id UInt32, value Int32)
            ENGINE = ReplicatedMergeTree('/clickhouse/tables/replicated_mt', '{replica}') ORDER BY id
            SETTINGS cleanup_delay_period=1, cleanup_delay_period_random_add=1, cleanup_thread_preferred_points_per_iteration=0;
                """.format(
                replica=node1.name
            )
        )
    
        node1.query("SYSTEM STOP REPLICATION QUEUES replicated_mt")
        for i in range(4):
            node1.query(
                "INSERT INTO replicated_mt SELECT toDate('2019-10-01'), number, number * number FROM numbers ({f}, 100000)".format(
                    f=i * 100000
                )
            )
    
        assert (
            node1.query(
                "SELECT COUNT() FROM system.parts WHERE table='replicated_mt' AND active=1"
            )
            == "4\n"
        )
    
        # Need to corrupt "border part" (left or right). If we will corrupt something in the middle
        # clickhouse will not consider merge as broken, because we have parts with the same min and max
        # block numbers.
        corrupt_part_data_on_disk(node1, "replicated_mt", "all_3_3_0")
    
        with Pool(1) as p:
    
            def optimize_with_delay(x):
                node1.query("OPTIMIZE TABLE replicated_mt FINAL", timeout=30)
    
            # corrupt part after merge already assigned, but not started
            res_opt = p.apply_async(optimize_with_delay, (1,))
            node1.query(
                "CHECK TABLE replicated_mt",
                settings={"check_query_single_value_result": 0, "max_threads": 1},
            )
            # start merge
            node1.query("SYSTEM START REPLICATION QUEUES replicated_mt")
>           res_opt.get()

test_broken_part_during_merge/test.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.10/multiprocessing/pool.py:774: in get
    raise self._value
/usr/lib/python3.10/multiprocessing/pool.py:125: in worker
    result = (True, func(*args, **kwds))
test_broken_part_during_merge/test.py:57: in optimize_with_delay
    node1.query("OPTIMIZE TABLE replicated_mt FINAL", timeout=30)
helpers/cluster.py:3432: in query
    return self.client.query(
helpers/client.py:36: in wrap
    return func(self, *args, **kwargs)
helpers/client.py:74: in query
    ).get_answer()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <helpers.client.CommandRequest object at 0x7fef46648c10>

    def get_answer(self):
        self.process.wait(timeout=DEFAULT_QUERY_TIMEOUT)
        self.stdout_file.seek(0)
        self.stderr_file.seek(0)
    
        stdout = self.stdout_file.read().decode("utf-8", errors="replace")
        stderr = self.stderr_file.read().decode("utf-8", errors="replace")
    
        if (
            self.timer is not None
            and not self.process_finished_before_timeout
            and not self.ignore_error
        ):
            logging.debug(f"Timed out. Last stdout:{stdout}, stderr:{stderr}")
>           raise QueryTimeoutExceedException("Client timed out!")
E           helpers.client.QueryTimeoutExceedException: Client timed out!

helpers/client.py:234: QueryTimeoutExceedException
```

</details>

<details>
<summary>clickhouse-server.log</summary>


```
logs/clickhouse-server.log
326:2023.11.29 02:37:33.044977 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> executeQuery: (from 172.16.21.1:60368) OPTIMIZE TABLE replicated_mt FINAL (stage: Complete)
327:2023.11.29 02:37:33.045013 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Trace> ContextAccess (default): Access granted: OPTIMIZE ON default.replicated_mt
332:2023.11.29 02:37:33.046069 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> default.replicated_mt (cf833a67-0eb9-4583-8d95-fa83d9eb5ae4) (MergerMutator): Selected 4 parts from all_0_0_0 to all_3_3_0
337:2023.11.29 02:37:33.047500 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Trace> default.replicated_mt (cf833a67-0eb9-4583-8d95-fa83d9eb5ae4): Created log entry /clickhouse/tables/replicated_mt/log/log-0000000004 for merge all_0_3_1
339:2023.11.29 02:37:33.047524 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> default.replicated_mt (cf833a67-0eb9-4583-8d95-fa83d9eb5ae4): Waiting for node1 to process log entry
340:2023.11.29 02:37:33.047536 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> default.replicated_mt (cf833a67-0eb9-4583-8d95-fa83d9eb5ae4): Waiting for node1 to pull log-0000000004 to queue
350:2023.11.29 02:37:33.049303 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> default.replicated_mt (cf833a67-0eb9-4583-8d95-fa83d9eb5ae4): Looking for node corresponding to log-0000000004 in node1 queue
353:2023.11.29 02:37:33.049906 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> default.replicated_mt (cf833a67-0eb9-4583-8d95-fa83d9eb5ae4): Waiting for queue-0000000004 to disappear from node1 queue
15309:2023.11.29 02:38:03.750390 [ 9 ] {50e25bec-4dd8-4e5d-b5d5-782e994e05e2} <Debug> TCPHandler: Processed in 30.705146145 sec.
```

</details>
