### PR TITLE
Ask for the password in clickhouse-client interactively

### LINKED ISSUE #46702: `clickhouse-client` If the password is not specified in the command line, and no-password auth is rejected, ask for password interactively.
Currently it works as follows:
```
milovidov@milovidov-desktop:~$ clickhouse client --host xqr42pv6yb.eu-west-1.aws.clickhouse-staging.com --secure
ClickHouse client version 23.2.1.1.
Connecting to xqr42pv6yb.eu-west-1.aws.clickhouse-staging.com:9440 as user default.
Code: 516. DB::Exception: Received from xqr42pv6yb.eu-west-1.aws.clickhouse-staging.com:9440. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.
```

Should fall back to interactive password prompt (similarly if I added the `--password` argument):
```
milovidov@milovidov-desktop:~$ clickhouse client --host xqr42pv6yb.eu-west-1.aws.clickhouse-staging.com --secure --password
ClickHouse client version 23.2.1.1.
Password for user (default):
```

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Ask for the password in clickhouse-client interactively in a case when the empty password is wrong. Closes https://github.com/ClickHouse/ClickHouse/issues/46702

### CODE REVIEW

File: programs/client/Client.cpp [hunk 1]
```diff
@@ -327,7 +327,29 @@ try
...
+                throw;
+
+            String prompt = fmt::format("Password for user ({}): ", config().getString("user", ""));
+            String password;
+            if (auto * result = readpassphrase(prompt, buf, sizeof(buf), 0))
+                password = result;
+
+            config().setString("password", password);
+            connect();
+        }
```
Comment (vdimir) [inline programs/client/Client.cpp:351]: Should we rethrow other error codes?
```suggestion
        }
        else
        	throw;
```

**Review by alexey-milovidov — APPROVED** [review]
