### PR TITLE
Fix parsing of tuples in case of errors

### LINKED ISSUE #39419: offsets_column has data inconsistent with nested_column: data for INSERT was parsed from query. (LOGICAL_ERROR)
https://pastila.nl/?00ad187f/ecfb3d92d2e879533cc3aea0536ab3d7

22.3 Exception on client:
Code: 49. DB::Exception: offsets_column has data inconsistent with nested_column: data for INSERT was parsed from query. (LOGICAL_ERROR)

22.7 the insert hangs

21.8.4 Received exception from server (version 21.8.4): Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Empty query.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix rare cases of parsing of arrays of tuples in format `Values`. 

Fixes #39419.

### CODE REVIEW

File: src/DataTypes/Serializations/SerializationTuple.cpp [hunk 1]
```diff
@@ -135,20 +135,21 @@ void SerializationTuple::deserializeText(IColumn & column, ReadBuffer & istr, co
...
         skipWhitespaceIfAny(istr);
-        // Allow both (1) and (1,)
-        checkChar(',', istr);
-    }
-    skipWhitespaceIfAny(istr);
-    assertChar(')', istr);
+        assertChar(')', istr);
 
-    if (whole && !istr.eof())
-        throwUnexpectedDataAfterParsedValue(column, istr, settings, "Tuple");
```
Comment (CurtizJ) [inline src/DataTypes/Serializations/SerializationTuple.cpp:151]: The bug was because some parsing functions were outside the `addElementSafe` and if exception was thrown in them, rollback was not applied.

**Review by evillique — APPROVED** [review]
