### PR TITLE
Limit disks to search for orphaned parts 

### LINKED ISSUE #70514: Unexpected dependency on unused s3
**Company or project name**

Discovered by a customer that has a data pipeline involving the creation of numerous auxiliary tables.

**Describe the unexpected behaviour**

During the ATTACH TABLE operation (with CREATE being a specific case), ClickHouse may check for the presence of data parts across all configured disks, even if the disk does not belong to the corresponding policy.

This presence check relies on metadata and is typically a low-cost operation; however, it is non-local for s3_plain storages.

**How to reproduce**

This behavior can be triggered by several conditions.

For example, if an s3_plain disk is configured as follows:

``` xml
<disks>
  <aws_plain>
      <type>s3_plain</type>
      ...
```

and if the 'default' policy is defined as:

``` xml
<policies>
  <default>
     <volumes>
         <hot>
             <disk>default</disk>
         </hot>
         ...
```

then creating a table with this policy would lead ClickHouse to generate API calls to check for data parts on aws_plain. 

Moreover, if the object storage behind aws_plain is temporarily unavailable, it would become impossible to create a table.

**Which ClickHouse server version to use**

Reproducible against 23.8.6.16 (official build) and against master as of October 24.

**Expected behavior**

Currently, I do not have a clear solution for this issue and appreciate comments/suggestions.

A potential improvement could involve introducing a flag to exclude a specific disk from this presence check. Excluding all disks with non-local metadata might also be an option, though I am unsure about its feasibility.

The logic that triggers the check seems strange, see https://github.com/ClickHouse/ClickHouse/blob/f36bc0cf8be61ceb3a827b3947259a009498f740/src/Disks/StoragePolicy.cpp#L170 . May be it should be more consistent.

### PR DESCRIPTION
**Pull request by ilejn**
### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
New MergeTree setting `search_orphaned_parts_drives` to limit scope to look for parts e.g. by disks with local metadata.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/70514

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.h [hunk 1]
```diff
@@ -722,6 +722,10 @@ class MergeTreeData : public IStorage, public WithMutableContext
     /// Makes sense only for ordinary MergeTree engines because for them block numbering doesn't depend on partition.
     std::optional<Int64> getMinPartDataVersion() const;
 
+    /// Is the disk included in the scope for searching [detached] parts
+    ///   sometimes it is better to bypass a disk e.g. to avoid interactions with a remote storage
+    bool lookOnDisk(DiskPtr disk) const;
```
Comment (arthurpassos) [inline src/Storages/MergeTree/MergeTreeData.h]: I would make the method name a bit more descriptive (e.g, `shouldSearchForPartsOnDisk`)

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 2]
```diff
@@ -2126,6 +2139,11 @@ void MergeTreeData::loadDataParts(bool skip_sanity_checks, std::optional<std::un
             }
 
             bool is_disk_defined = defined_disk_names.contains(disk_name);
+            if (!is_disk_defined && !lookOnDisk(disk))
```
Comment (arthurpassos) [inline src/Storages/MergeTree/MergeTreeData.cpp]: Is it possible the disk is "defined" but we still don't want to look at it? sorry for the dumb question, what does "is_disk_defined" actually mean?

1. Disk is defined somewhere in the settings regardless of being related to this table;
2. Disk is defined AND is related to this table

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 3]
```diff
@@ -7092,7 +7110,7 @@ DetachedPartsInfo MergeTreeData::getDetachedParts() const
         /// While it is possible to have detached parts on readonly/write-once disks
         /// (if they were produced on another machine, where it wasn't readonly)
         /// to avoid wasting resources for slow disks, avoid trying to enumerate them.
-        if (disk->isReadOnly() || disk->isWriteOnce())
+        if (disk->isReadOnly() || disk->isWriteOnce() || !lookOnDisk(disk))
```
Comment (arthurpassos) [inline src/Storages/MergeTree/MergeTreeData.cpp]: Perhaps move `disk->isReadOnly()` and `disk->isWriteOnce()` inside `lookOnDisk`?

File: src/Interpreters/DatabaseCatalog.cpp [hunk 4]
```diff
@@ -1459,11 +1467,35 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
         table.table->drop();
     }
 
+    /// Check if we are interested in a particular disk
+    ///   or it is better to bypass it e.g. to avoid interactions with a remote storage
+    auto look_on_disk =
```
Comment (arthurpassos) [inline src/Interpreters/DatabaseCatalog.cpp]: Why do we need this on DatabaseCatalog?

File: tests/integration/test_search_detached_parts/test.py [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+            CREATE TABLE {table_name} (
+            id Int64,
+            data String
+            ) ENGINE=MergeTree()
+            PARTITION BY id % 10
+            ORDER BY id
+            SETTINGS storage_policy='{storage_policy}', search_detached_parts_drives='{search_mode}'
+            """
+        )
+        # To drop when minio is not available
```
Comment (arthurpassos) [inline tests/integration/test_search_detached_parts/test.py]: I would add a more descriptive comment explaining how this test works. Example:

```
Verify the search detached parts logic by placing an isolation rule that blocks all connections to MinIO. In this scenario, the following should happen for search each policy:

*  `none` should not search s3 and the query should succeed
* `local` should not search s3 and the query should succeed
* `any` should search s3 and the query should throw
```

File: src/Storages/MergeTree/MergeTreeData.cpp (hunk 2 above)
Comment (ilejn) [reply src/Storages/MergeTree/MergeTreeData.cpp]: As far as I understand the code,

`is_disk_defined` actually means that we are not worried if we can find a part that belongs to the table on this disk.

From the code standpoint, there are two cases
1. disk is actually bound to the table via policy
2. cache or encrypted disk

Probably it would be more faithful to introduce another unordered_set like 'ephemeral_disk_we_are_too_lazy_to_analyze_properly ' or rename `defined_disk_names` to `disk_names_we_are_not_surprised_to_see_part` ;)
but I don't see enough reasons to interfere and would prefer to keep it as is.

File: src/Storages/MergeTree/MergeTreeData.cpp (hunk 3 above)
Comment (ilejn) [reply src/Storages/MergeTree/MergeTreeData.cpp]: Actually it is an error, lookOnDisk (renamed to shouldSearchForPartsOnDisk) cannot be used here.

There are two different things:
1. detached parts (parts in a specific directory, that are not used)
2. parts on unexpected disks, that look like active parts

Fortunately there is no mixture and we are not looking for detached parts on unexpected disks.

This PR is a about (2) and I have to clean up the mess with e.g. parameter name.

File: src/Interpreters/DatabaseCatalog.cpp (hunk 4 above)
Comment (ilejn) [reply src/Interpreters/DatabaseCatalog.cpp]: Because DatabaseCatalog::dropTableFinally does drop table finally traversing all disks (not only disks that belong to table policy).

Comment (arthurpassos) [reply src/Interpreters/DatabaseCatalog.cpp]: I initially thought `DatabaseCatalog` was somewhat related to data lakes catalogs lol. It makes sense.

File: src/Core/SettingsChangesHistory.cpp [hunk 6]
```diff
@@ -803,6 +803,8 @@ const VersionToSettingsChangesMap & getMergeTreeSettingsChangesHistory()
     {
         addSettingsChanges(merge_tree_settings_changes_history, "25.8",
         {
+            {"write_marks_for_substreams_in_compact_parts", false, true, "Enable writing marks for substreams in compact parts by default"},
```
Comment (azat) [inline src/Core/SettingsChangesHistory.cpp]:
```suggestion
```

it is already defined below.

File: src/Core/SettingsEnums.h [hunk 7]
```diff
@@ -422,4 +422,12 @@ enum class GeoToH3ArgumentOrder : uint8_t
 
 DECLARE_SETTING_ENUM(GeoToH3ArgumentOrder)
 
+enum class SearchOrphanedPartsDrives : uint8_t
```
Comment (azat) [inline src/Core/SettingsEnums.h]: Let's rename **driver** with **disk** everywhere (we use disk, not drive)

File: src/Interpreters/DatabaseCatalog.cpp [hunk 8]
```diff
@@ -1459,11 +1467,35 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
...
+        [this](DiskPtr disk, std::shared_ptr<MergeTreeData> tbl)
+    {
+        if (!tbl)
+            /// Not a MergeTree - don't skip
+            return true;
```
Comment (azat) [inline src/Interpreters/DatabaseCatalog.cpp]:
```suggestion
        /// Not a MergeTree - don't skip
        if (!tbl)
            return true;
```

File: src/Interpreters/DatabaseCatalog.cpp [hunk 9]
```diff
@@ -1459,11 +1467,35 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
...
+
+        if (tbl->getStoragePolicy()->tryGetVolumeIndexByDiskName(disk->getName()).has_value())
+            /// Disk is actually used - don't skip
+            return true;
```
Comment (azat) [inline src/Interpreters/DatabaseCatalog.cpp]:
```suggestion
        /// Disk is actually used - don't skip
        if (tbl->getStoragePolicy()->tryGetVolumeIndexByDiskName(disk->getName()).has_value())
            return true;
```

File: src/Interpreters/DatabaseCatalog.cpp [hunk 10]
```diff
@@ -1459,11 +1467,35 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
...
+
+        auto is_local_metadata = [&]() { return !(disk->isRemote() && disk->isPlain()); };
```
Comment (azat) [inline src/Interpreters/DatabaseCatalog.cpp]: Let's just use `isRemote`

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 11]
```diff
@@ -2082,6 +2084,17 @@ std::vector<MergeTreeData::LoadPartResult> MergeTreeData::loadDataPartsFromDisk(
     return loaded_parts;
 }
 
+bool MergeTreeData::shouldSearchForPartsOnDisk(DiskPtr disk) const
+{
+    auto is_local_metadata = [&]() { return !(disk->isRemote() && disk->isPlain()); };
```
Comment (azat) [inline src/Storages/MergeTree/MergeTreeData.cpp]: Let's just use `isRemote`

File: src/Interpreters/DatabaseCatalog.cpp [hunk 12]
```diff
@@ -1459,11 +1467,35 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
...
+
+        SearchOrphanedPartsDrives mode = (*tbl->getSettings())[MergeTreeSetting::search_orphaned_parts_drives];
+        bool is_look_needed = mode == SearchOrphanedPartsDrives::ANY
+            || (mode == SearchOrphanedPartsDrives::LOCAL && is_local_metadata());
+
+        LOG_TRACE(log, "look_on_disk: mode {}, is_look_needed {}", mode, is_look_needed);
```
Comment (azat) [inline src/Interpreters/DatabaseCatalog.cpp]: This logging looks more for developers, consider making it user friendly, i.e.

```suggestion
        LOG_TRACE(log, "Disk {} will be skipped (search_orphaned_parts_drives: {})", ...);
```

Below we have a log message if the disk will be processed, so it is OK to log only skipped disks I think

Actually I think the message should be in the caller not here

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 13]
```diff
@@ -199,6 +199,7 @@ namespace Setting
     extern const SettingsUInt64 min_insert_block_size_rows;
     extern const SettingsUInt64 min_insert_block_size_bytes;
     extern const SettingsBool apply_patch_parts;
+    extern const SettingsBool function_date_trunc_return_type_behavior;
```
Comment (azat) [inline src/Storages/MergeTree/MergeTreeData.cpp]:
```suggestion
```

File: tests/integration/test_search_orphaned_parts/configs/storage_conf.xml [hunk 14]
```diff
@@ -0,0 +1,63 @@
+<clickhouse>
+    <storage_configuration>
+      <disks>
+  				  <default>
```
Comment (azat) [inline tests/integration/test_search_orphaned_parts/configs/storage_conf.xml]: Bad indent

File: src/Storages/MergeTree/MergeTreeData.h [hunk 15]
```diff
@@ -1886,6 +1886,11 @@ class MergeTreeData : public IStorage, public WithMutableContext
     createStorageSnapshot(const StorageMetadataPtr & metadata_snapshot, ContextPtr query_context, bool without_data) const;
 
     bool isReadonlySetting(const std::string & setting_name) const;
+
+    /// Is the disk should be searched for orphaned parts (ones that belong to a table based on file names, but located
+    ///   on disks that are not a part of storage policy of the table).
+    /// Sometimes it is better to bypass a disk e.g. to avoid interactions with a remote storage
+    bool shouldSearchForPartsOnDisk(DiskPtr disk) const;
```
Comment (azat) [inline src/Storages/MergeTree/MergeTreeData.h]: Maybe `isDiskEligibleForOrphanedPartSearch` is a better name?

File: tests/integration/test_search_orphaned_parts/test.py [hunk 16]
```diff
@@ -0,0 +1,124 @@
...
+# The following is expected
+# * search_orphaned_parts_drives is `none` - does not search s3, the query is successful
+# * search_orphaned_parts_drives is `local` - does not search s3, the query is successful
+# * search_orphaned_parts_drives is `any` - searches s3, the query throws
+# Note, disk_s3_plain is not a part either of `no_s3` or of `local_cache` policies
+def test_search_orphaned_parts():
+    table_name = "t1"
+
+    # Note that disk_s3_plain and s3_plain_rewritable are not used in these policies,
+    # !ClickHouse looks for orpaned parts on 'undefined' disks
```
Comment (azat) [inline tests/integration/test_search_orphaned_parts/test.py]: Let's adjust the comment to reflect that it is enough to have this disks in config and not use them since under  `search_orphaned_parts_drives=any` those disks will be scanned by ClickHouse

File: tests/integration/test_search_orphaned_parts/test.py [hunk 17]
```diff
@@ -0,0 +1,124 @@
...
+            data String
+            ) ENGINE=MergeTree()
+            PARTITION BY id % 10
+            ORDER BY id
+            SETTINGS storage_policy='{storage_policy}', search_orphaned_parts_drives='{search_mode}'
+            """
+        )
+        # To drop when minio is not available
+
+        with PartitionManager() as pm:
```
Comment (azat) [inline tests/integration/test_search_orphaned_parts/test.py]: Tests with `PartitionManager` tend to be flaky, let's simply remove MinIO and use `skip_access_check` to allow ClickHouse start with this disk.

**Review by azat — CHANGES_REQUESTED** [review]

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 18]
```diff
@@ -2136,6 +2149,11 @@ void MergeTreeData::loadDataParts(bool skip_sanity_checks, std::optional<std::un
             }
 
             bool is_disk_defined = defined_disk_names.contains(disk_name);
+            if (!is_disk_defined && !shouldSearchForPartsOnDisk(disk))
```
Comment (azat) [inline src/Storages/MergeTree/MergeTreeData.cpp]: Why not just add a check for `shouldSearchForPartsOnDisk` on L2145? I think it is OK to do so, since we will try to load parts on the defined disks anyway

File: src/Interpreters/DatabaseCatalog.cpp (hunk 10 above)
Comment (ilejn) [reply src/Interpreters/DatabaseCatalog.cpp]: Are you sure? Why?
And remove '... that have local metadata"?

Comment (azat) [reply src/Interpreters/DatabaseCatalog.cpp]: The `isPlain()  == false` API does not guarantee that the disk will be local (i.e. `MetadataStorageType::Keeper`)

File: src/Storages/MergeTree/MergeTreeData.cpp (hunk 18 above)
Comment (ilejn) [reply src/Storages/MergeTree/MergeTreeData.cpp]: To avoid defined_disk_names.contains(disk_name) for isBroken() or isCustomDisk.
Ok, lets keep it simple.

Comment (ilejn) [reply src/Storages/MergeTree/MergeTreeData.cpp]: Hm .. not sure that it looks better
```
         for (const auto & [disk_name, disk] : getContext()->getDisksMap())
         {
-            if (disk->isBroken() || disk->isCustomDisk())
-            {
-                skip_check_disks.insert(disk_name);
-                continue;
-            }
-
             bool is_disk_defined = defined_disk_names.contains(disk_name);
-            if (!is_disk_defined && !shouldSearchForPartsOnDisk(disk))
+            if (disk->isBroken() || disk->isCustomDisk() || (!is_disk_defined && !isDiskEligibleForOrphanedPartsSearch(disk)))
             {
```

Comment (azat) [reply src/Storages/MergeTree/MergeTreeData.cpp]: Why do we need to make sure that the disk is not defined for this new check? I think we can skip it, since the parts will be loaded from those disks anyway?

Comment (ilejn) [reply src/Storages/MergeTree/MergeTreeData.cpp]: > Why do we need to make sure that the disk is not defined for this new check? 

We do not.
Makes sense.

**Comment by ilejn** [comment]
CH is not able to start if s3 is not available and s3 disk with plain_rewritable metadata is configured.
https://pastila.nl/?00314508/95c6b93efc0152bc16406a0c3d4eddc1#e1OEKKuCGwcIWUy941a3Zw==
I'd like to leave it out of the scope of this PR and investigate later.

File: tests/integration/test_search_orphaned_parts/configs/storage_conf.xml [hunk 19]
```diff
@@ -0,0 +1,65 @@
...
+                <skip_access_check>true</skip_access_check>
+            </disk_s3_plain>
+            <local_disk_1>
+              <path>/internal/1/</path>
+            </local_disk_1>
+            <local_disk_2>
+              <type>local_blob_storage</type>
+              <path>/internal/2/</path>
+            </local_disk_2>
+            <!-- <s3_plain_rewritable> -->
```
Comment (azat) [inline tests/integration/test_search_orphaned_parts/configs/storage_conf.xml:22]: Let's add a comment for the reason it is commented

Comment (azat) [inline tests/integration/test_search_orphaned_parts/configs/storage_conf.xml:22]:
```suggestion
            <!-- plain_rewritable disk is not able to start w/o S3, since it tries to load metadata at start-->
            <!-- <s3_plain_rewritable> -->
```

File: src/Interpreters/DatabaseCatalog.cpp [hunk 20]
```diff
@@ -1459,11 +1466,34 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
         table.table->drop();
     }
 
+    /// Check if we are interested in a particular disk
+    ///   or it is better to bypass it e.g. to avoid interactions with a remote storage
+    auto is_disk_eligible_for_search =
+        [this](DiskPtr disk, std::shared_ptr<MergeTreeData> tbl)
+    {
+        bool is_disk_eligible = !disk->isReadOnly();
+        SearchOrphanedPartsDisks mode = (*tbl->getSettings())[MergeTreeSetting::search_orphaned_parts_disks];
```
Comment (azat) [inline src/Interpreters/DatabaseCatalog.cpp]:
```suggestion
        SearchOrphanedPartsDisks mode = (*tbl->getSettings())[MergeTreeSetting::search_orphaned_parts_disks];
```

UB in case of table is not a MergeTree family table

File: src/Interpreters/DatabaseCatalog.cpp [hunk 21]
```diff
@@ -1459,11 +1466,34 @@ void DatabaseCatalog::dropTableFinally(const TableMarkedAsDropped & table)
         table.table->drop();
     }
 
+    /// Check if we are interested in a particular disk
+    ///   or it is better to bypass it e.g. to avoid interactions with a remote storage
+    auto is_disk_eligible_for_search =
+        [this](DiskPtr disk, std::shared_ptr<MergeTreeData> tbl)
```
Comment (azat) [inline src/Interpreters/DatabaseCatalog.cpp]: AFAIR this style is more common

```suggestion
    auto is_disk_eligible_for_search = [this](DiskPtr disk, std::shared_ptr<MergeTreeData> table)
```

Also consider using `storage` or `table` over `tbl`, these abbrev is not worth it, and it is more common to avoid such in the code

Comment (ilejn) [reply src/Interpreters/DatabaseCatalog.cpp]: I guess that using 'table' can raise a warning like "Variable shadowed".
Ok, let it be "storage".

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
Tests has failed, @ilejn PTAL

**Comment by ilejn** [comment]
Something about settings changes history.
Trace
```
2025.08.06 14:09:04.930748 [ 777 ] {} <Error> Application: Code: 170. DB::Exception: Bad get: has UInt64, requested String. (BAD_GET), Stack trace (when copying this message, always include the lines below):

0. /home/ilejn/projects/ClickHouse_search_orphaned_parts/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001e145f72
1. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Common/Exception.cpp:116: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000108024db
2. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000097e826c
3. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Common/Exception.h:137: DB::Exception::Exception<std::basic_string_view<char, std::char_traits<char>>, std::basic_string_view<char, std::char_traits<char>>>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>>::type>, std::basic_string_view<char, std::char_traits<char>>&&, std::basic_string_view<char, std::char_traits<char>>&&) @ 0x0000000014ccc22b
4. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Core/Field.cpp:874: DB::NearestFieldTypeImpl<__decay(String), void>::Type& DB::Field::safeGet<String>() & @ 0x0000000014ccd2ab
5. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Core/Field.h:437: DB::SettingFieldEnum<DB::SearchOrphanedPartsDisks, DB::SettingFieldSearchOrphanedPartsDisksTraits>::SettingFieldEnum(DB::Field const&) @ 0x00000000190f01cc
6. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Storages/MergeTree/MergeTreeSettings.cpp:1915: DB::MergeTreeSettingsTraits::Accessor::instance()::$_0::operator()() const::'lambda501'(DB::Field const&)::__invoke(DB::Field const&) @ 0x00000000190e7f52
7. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Storages/MergeTree/MergeTreeSettings.cpp:1890: DB::MergeTreeSettings::applyCompatibilitySetting(String const&) @ 0x00000000190af7ce
8. /home/ilejn/projects/ClickHouse_search_orphaned_parts/src/Interpreters/Context.cpp:5409: DB::Context::getMergeTreeSettings() const @ 0x0000000015ed1352
9. /home/ilejn/projects/ClickHouse_search_orphaned_parts/programs/server/Server.cpp:837: DB::(anonymous namespace)::sanityChecks(DB::Server&) @ 0x0000000010b312ad
```
Probably I misunderstand semantic somehow
```
        addSettingsChanges(merge_tree_settings_changes_history, "25.8",
        {
            {"search_orphaned_parts_disks", SearchOrphanedPartsDisks::ANY, SearchOrphanedPartsDisks::ANY, "New setting"},

```

**Comment by ilejn** [comment]
Hm ... it seems it should be 
{"search_orphaned_parts_disks", "any", "any"

Rechecking.

**Comment by ilejn** [comment]
Observing exactly the same issue in other PR https://play.clickhouse.com/play?user=play#c2VsZWN0ICogZnJvbSBjaGVja3Mgd2hlcmUgcHVsbF9yZXF1ZXN0X251bWJlcj04MzA5NCBhbmQgdGVzdF9uYW1lPScwMTE1NF9tb3ZlX3BhcnRpdGlvbl9sb25nJyBhbmQgY2hlY2tfc3RhcnRfdGltZSA+ICcyMDI1LTA3LTA3JyBhbmQgY2hlY2tfc3RhdHVzPSdmYWlsdXJlJyBvcmRlciBieSBjaGVja19zdGFydF90aW1lIGRlc2MgbGltaXQgMTA7Cg==

**Comment by azat** [comment]
>CH Inc sync - Waiting for status to be reported — Conflicts found. The sync PR is not mergeable, it probably has conflicts

Conflicts has been resolved

**Comment by ilejn** [comment]
Test failures are new (did not exist while previous run). 
It seems that test_storage_delta is flaky, while I will look into it.

**Comment by ilejn** [comment]
I cannot say anything meaningful about the nature of test_storage_delta failures,
but they are not related to the PR.

**Comment by azat** [comment]
CI:
- `02126_dist_desc` - flaky
- `test_storage_delta` - flaky - https://github.com/ClickHouse/ClickHouse/issues/85209

File: tests/integration/test_search_orphaned_parts/test.py [hunk 22]
```diff
@@ -0,0 +1,70 @@
...
+
+
+def get_cluster(with_minio):
+    cluster = ClickHouseCluster(__file__)
+    cluster.add_instance(
+        "node",
+        main_configs=["configs/storage_conf.xml"],
+        user_configs=["configs/users.xml"],
+        with_minio=with_minio,
+        stay_alive=True,
```
Comment (azat) [inline tests/integration/test_search_orphaned_parts/test.py:14]:
```suggestion
        stay_alive=True,
        # remote database disk adds MinIO implicitly
        # FIXME: disable with_remote_database_disk if with_minio set to False explicitly
        with_remote_database_disk=False,
```

**Comment by azat** [comment]
CI:
- https://github.com/ClickHouse/ClickHouse/issues/71049
- https://github.com/ClickHouse/ClickHouse/issues/81144
