### PR TITLE
Try fix flaky 02497_storage_file_reader_selection

### LINKED ISSUE #51462: Flaky 02497_storage_file_reader_selection
https://s3.amazonaws.com/clickhouse-test-reports/51407/e92035072b7b3367da12089b28041893eb90e636/stateless_tests__tsan__[3_5].html

```
2023-06-26 16:40:35 --- /usr/share/clickhouse-test/queries/0_stateless/02497_storage_file_reader_selection.reference	2023-06-26 16:37:04.121177254 +0100
2023-06-26 16:40:35 +++ /tmp/clickhouse-test/0_stateless/02497_storage_file_reader_selection.stdout	2023-06-26 16:40:35.722208759 +0100
2023-06-26 16:40:35 @@ -1,4 +1,4 @@
2023-06-26 16:40:35 -1
2023-06-26 16:40:35 +2
2023-06-26 16:40:35  0
2023-06-26 16:40:35  0
2023-06-26 16:40:35  1
2023-06-26 16:40:35 
2023-06-26 16:40:35 
2023-06-26 16:40:35 Settings used in the test: --max_insert_threads=0 --group_by_two_level_threshold=721671 --group_by_two_level_threshold_bytes=1 --distributed_aggregation_memory_efficient=0 --fsync_metadata=1 --output_format_parallel_formatting=1 --input_format_parallel_parsing=0 --min_chunk_bytes_for_parallel_parsing=16570559 --max_read_buffer_size=765861 --prefer_localhost_replica=0 --max_block_size=44064 --max_threads=17 --optimize_or_like_chain=0 --optimize_read_in_order=0 --enable_multiple_prewhere_read_steps=0 --read_in_order_two_level_merge_threshold=28 --optimize_aggregation_in_order=0 --aggregation_in_order_max_block_bytes=29360551 --min_compress_block_size=764567 --max_compress_block_size=917864 --use_uncompressed_cache=0 --min_bytes_to_use_direct_io=10737418240 --min_bytes_to_use_mmap_io=1 --local_filesystem_read_method=pread --remote_filesystem_read_method=read --local_filesystem_read_prefetch=0 --remote_filesystem_read_prefetch=1 --allow_prefetched_read_pool_for_remote_filesystem=0 --filesystem_prefetch_max_memory_usage=128Mi --filesystem_prefetches_limit=10 --filesystem_prefetch_min_bytes_for_single_read_task=8Mi --filesystem_prefetch_step_marks=0 --filesystem_prefetch_step_bytes=100Mi --compile_expressions=0 --compile_aggregate_expressions=1 --compile_sort_description=1 --merge_tree_coarse_index_granularity=18 --optimize_distinct_in_order=0 --optimize_sorting_by_input_stream_properties=1 --http_response_buffer_size=823164 --http_wait_end_of_query=False --enable_memory_bound_merging_of_aggregation_results=0
2023-06-26 16:40:35 
2023-06-26 16:40:35 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization=1.0 --prefer_fetch_merged_part_size_threshold=10737418240 --vertical_merge_algorithm_min_rows_to_activate=1 --vertical_merge_algorithm_min_columns_to_activate=100 --allow_vertical_merges_from_compact_to_wide_parts=0 --min_merge_bytes_to_use_direct_io=10737418240 --index_granularity_bytes=20102423 --merge_max_block_size=10927 --index_granularity=40324 --min_bytes_for_wide_part=0 --marks_compress_block_size=89250 --primary_key_compress_block_size=14482
2023-06-26 16:40:35 
2023-06-26 16:40:35 Database: test_ffib5iom
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes https://github.com/ClickHouse/ClickHouse/issues/51462

### CODE REVIEW

File: tests/queries/0_stateless/02497_storage_file_reader_selection.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@ CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 DATA_FILE=test_02497_$CLICKHOUSE_TEST_UNIQUE_NAME.tsv
 echo -e 'key\nfoo\nbar' > $DATA_FILE
 
-$CLICKHOUSE_LOCAL --storage_file_read_method=mmap --print-profile-events -q "SELECT * FROM file($DATA_FILE) FORMAT Null" 2>&1 | grep -F -c "CreatedReadBufferMMap"
+$CLICKHOUSE_LOCAL --storage_file_read_method=mmap --print-profile-events -q "SELECT * FROM file($DATA_FILE) FORMAT Null" 2>&1 | grep -F -c "CreatedReadBufferMMap:"
```
Comment (Avogar) [inline tests/queries/0_stateless/02497_storage_file_reader_selection.sh:10]: AFAIU sometimes this query can get both `CreatedReadBufferMMap` and `CreatedReadBufferMMapFailed` events . Let's grep only for `CreatedReadBufferMMap`

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit b4b21c0cf2e0c9c128a1558b543787297059748a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51468/b4b21c0cf2e0c9c128a1558b543787297059748a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

File: tests/queries/0_stateless/02497_storage_file_reader_selection.sh (hunk 1 above)
Comment (azat) [reply tests/queries/0_stateless/02497_storage_file_reader_selection.sh:10]: This does not helps completely - https://s3.amazonaws.com/clickhouse-test-reports/52068/b6f9be2ad842a4cb9338d521bab07b931a0b3271/fast_test.html

I think that there is some problems with profile events, but I cannot reproduce it locally, either by slowing down the process to 0.1% of cpus artificially and without.

BTW in which case it may get both events?

Comment (Avogar) [reply tests/queries/0_stateless/02497_storage_file_reader_selection.sh:10]: > BTW in which case it may get both events?

Actually, I didn't fully understand it and it was more like a hypothesis, I could be wrong
