### PR TITLE
Optimize make ManifestFileEntry non-copyable

### LINKED ISSUE #91462: Improve the performance of icebergCluster
### Company or project name

I basic run a query like using `icebergHDFSCluster`
```
SELECT
    rtl_week_beg_dt AS week_begin_dt,
    age_for_rtl_week_id,
    coalesce(sum(snad_60d_cnt), 0) AS snad,
    coalesce(sum(elgb_trans_60d_cnt), 0) AS trans,
    coalesce(sum(bbe_60d_cnt), 0) AS bbe_trans,
FROM icebergHDFSCluster('default', 'hdfs://hxxxx', 'auto')
WHERE (xxxx)
GROUP BY
    rtl_week_beg_dt,
    age_for_rtl_week_id
ORDER BY age_for_rtl_week_id AS
```
Found the cluster read throughput is same as using singe node. ~0.5G/s 

```
43 rows in set. Elapsed: 197.053 sec. Processed 1.54 billion rows, 90.31 GB (7.84 million rows/s., 458.31 MB/s.)
```

This query will read 1000+ data files cost 150s,

```
[ICEBERG] partition pruned files[on]: partition_pruned_files:3171, min-max index pruned files: 1782, not-pruned files: 1425
```

I try to get the flamegraph of this  query base on [link](https://clickhouse.com/docs/sql-reference/aggregate-functions/reference/flame_graph#building-a-flamegraph-based-on-a-memory-query-profiler-showing-allocations-which-were-not-deallocated-in-query-context)

Image

From above pic there 20% cost in `StorageObjectStorageStableTaskDistributor::getNexttask`

Most of them are creating `ManifestFileEntry ` （these structs has been cached in memory and they are readonly, IMO we should using shardPtr to pass the value to avoid additional memory copy.
Image

### Describe the situation

Make ManifestFileEntry not copyable.
`struct ManifestFileEntry : public boost::noncopyable`

Passing shard_ptr in all function
`ManifestFileEntryPtr = std::shared_ptr<ManifestFileEntry>`

### Which ClickHouse versions are affected?

all

### How to reproduce

read data files more than 1000+

### Expected performance

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ted-Jiang**
### Changelog category (leave one):
* Performance Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
 Improve performance of  `icebergCluster`. Closes #91462.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
@Algunenano @kssenii could you make this pr CI  ?

File: src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h [hunk 1]
```diff
@@ -79,8 +79,43 @@ struct ManifestFileEntry
...
+        , columns_infos(columns_infos_)
+        , file_format(file_format_)
+        , reference_data_file_path(reference_data_file_path_)
+        , equality_ids(equality_ids_)
+        , sort_order_id(sort_order_id_)
+    {
+    }
 };
 
+using ManifestFileEntryPtr = std::shared_ptr<ManifestFileEntry>;
```
Comment (divanik) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h]: Could you, please, make it shared_ptr to const ManifestFileEntry

File: src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h [hunk 2]
```diff
@@ -79,8 +79,43 @@ struct ManifestFileEntry
...
+        , added_sequence_number(added_sequence_number_)
+        , snapshot_id(snapshot_id_)
+        , schema_id(schema_id_)
+        , partition_key_value(partition_key_value_)
+        , common_partition_specification(common_partition_specification_)
+        , columns_infos(columns_infos_)
+        , file_format(file_format_)
+        , reference_data_file_path(reference_data_file_path_)
+        , equality_ids(equality_ids_)
+        , sort_order_id(sort_order_id_)
```
Comment (divanik) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h:112]: std::move

File: src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h (hunk 1 above)
Comment (Ted-Jiang) [reply src/Storages/ObjectStorage/DataLakes/Iceberg/ManifestFile.h]: thx!  change to `using ManifestFileEntryPtr = std::shared_ptr<const ManifestFileEntry>;`

**Comment by Ted-Jiang** [comment]
@divanik thx for the review, seems unrelated test fail, could you help to check it?

**Comment by divanik** [comment]
@Ted-Jiang, it is definitely related (no failures in master, a lot of Iceberg tests have failed). it is unobviously related though, but it seems to be reproduced easily (use asan binary, you can also enable thread fuzzer in integration tests). Are you capable to launch functional and integration test locally with praktika?

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang, it is definitely related (no failures in master, a lot of Iceberg tests have failed). it is unobviously related though, but it seems to be reproduced easily (use asan binary, you can also enable thread fuzzer in integration tests). Are you capable to launch functional and integration test locally with praktika?

@divanik Thx for the reply! I will look into the praktika, its glad to get the information from you, thx again!

**Comment by Ted-Jiang** [comment]
@divanik Sorry to bother you again,  I have fixed all iceberg related, now i got fail in two case:

one is:
``` 
Marking '03141_fetches_errors_stress' as flaky (matched: 03141_fetches_errors_stress, issue: #83373)
```

Another is what the label retry_ok means?
image
How should i solve this, i am a little trapped.

**Comment by Ted-Jiang** [comment]
@divanik @kssenii Now ci fail at buzzHouse. From document this should call admin right? 🆘

**Comment by divanik** [comment]
> How should i solve this, i am a little trapped.

Hi, @Ted-Jiang. Probably, you shouldn't, this seems unrelated, I never said that you should fix all the tests in a PR

**Review by divanik — APPROVED** [review]
LGTM

**Comment by Ted-Jiang** [comment]
@divanik thx for helping on this ! 👍
