### PR TITLE
More fixes for parquet reader v3, enable it in stateless tests

### LINKED ISSUE #87396: Unexpected uncompressed page size: read stage: MainData: column: bool - with parquet native reader v3
### Company or project name

_No response_

### Describe what's wrong

I get the following exception when using native reader v3:

```
Error on processing query: Code: 117. DB::Exception: Unexpected uncompressed page size: read stage: MainData: column: bool: (in file/uri /var/lib/clickhouse/user_files/file_6bb64ca7_97a4_11f0_88de_498af214c503.Parquet): While executing ParquetV3BlockInputFormat: While executing File: data for INSERT was parsed from file. (INCORRECT_DATA) (version 25.8.4.13 (official build))
```

I wasn't able to create smaller steps to reproduce the issue but the sequence is ass follows:

1. I create a table with a schema containing a lot of columns with different datatypes 
2. I insert the data from that table into a FUNCTION file()
3. Insert the data from the generated parquet file back to the table

Here is the gist with all the steps as the queries are too big to fit here: https://gist.github.com/Selfeer/1acfea443d1155b7fc834025b2c33eda

### Does it reproduce on the most recent release?

Yes

### How to reproduce

**ClickHouse version:** `25.8.4.13`
**Settings:** `input_format_parquet_use_native_reader_v3 = 1`

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### LINKED ISSUE #87509: Segmentation fault when reading from a Parquet file with parquet native reader v3
### Company or project name

_No response_

### Describe what's wrong

I hit a ClickHouse crash when selecting from a file that has a Bool column with a bloom filter applied to it:

```
[665bc865432b] 2025.09.23 13:23:03.769097 [ 82 ] <Fatal> BaseDaemon: ########################################
[665bc865432b] 2025.09.23 13:23:03.769219 [ 82 ] <Fatal> BaseDaemon: (version 25.8.4.13 (official build), build id: AA4DCCDCCDCECCBA683D762F836A961FE245B65E, git hash: 42d08f157cb5e869d62715738177452c45dc007e) (from thread 940) (query_id: 968c5383-f61f-4490-a967-5cc280361fdc) (query: SELECT * FROM file('boolean_bloom.gz.parquet', 'Parquet') SETTINGS input_format_parquet_use_native_reader_v3 = 1) Received signal Segmentation fault (11)
[665bc865432b] 2025.09.23 13:23:03.769269 [ 82 ] <Fatal> BaseDaemon: Address: 0x101010109. Access: write. Address not mapped to object.
[665bc865432b] 2025.09.23 13:23:03.769330 [ 82 ] <Fatal> BaseDaemon: Stack trace: 0x000000001a1d8a85 0x000000001a1ee72b 0x000000001a1cfcc8 0x0000000014e3fb56 0x0000000013508aab 0x000000001350fe26 0x0000000013505a92 0x000000001350d55a 0x00007be600b16ac3 0x00007be600ba7a04
[665bc865432b] 2025.09.23 13:23:03.769485 [ 82 ] <Fatal> BaseDaemon: 2. DB::Parquet::PlainBooleanDecoder::~PlainBooleanDecoder() @ 0x000000001a1d8a85
[665bc865432b] 2025.09.23 13:23:03.769574 [ 82 ] <Fatal> BaseDaemon: 3. DB::Parquet::Reader::decodePrimitiveColumn(DB::Parquet::Reader::ColumnChunk&, DB::Parquet::Reader::PrimitiveColumnInfo const&, DB::Parquet::Reader::ColumnSubchunk&, DB::Parquet::Reader::RowGroup const&, DB::Parquet::Reader::RowSubgroup const&) @ 0x000000001a1ee72b
[665bc865432b] 2025.09.23 13:23:03.769639 [ 82 ] <Fatal> BaseDaemon: 4. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::Parquet::ReadManager::scheduleTasksIfNeeded(DB::Parquet::ReadStage)::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x000000001a1cfcc8
[665bc865432b] 2025.09.23 13:23:03.769709 [ 82 ] <Fatal> BaseDaemon: 5. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::ThreadPoolCallbackRunnerFast::initThreadPool(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>&, unsigned long, String, std::shared_ptr<DB::ThreadGroup>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000014e3fb56
[665bc865432b] 2025.09.23 13:23:03.769787 [ 82 ] <Fatal> BaseDaemon: 6. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000013508aab
[665bc865432b] 2025.09.23 13:23:03.769884 [ 82 ] <Fatal> BaseDaemon: 7. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001350fe26
[665bc865432b] 2025.09.23 13:23:03.769962 [ 82 ] <Fatal> BaseDaemon: 8. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013505a92
[665bc865432b] 2025.09.23 13:23:03.770012 [ 82 ] <Fatal> BaseDaemon: 9. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001350d55a
[665bc865432b] 2025.09.23 13:23:03.770100 [ 82 ] <Fatal> BaseDaemon: 10. ? @ 0x0000000000094ac3
[665bc865432b] 2025.09.23 13:23:03.770156 [ 82 ] <Fatal> BaseDaemon: 11. ? @ 0x0000000000125a04
[665bc865432b] 2025.09.23 13:23:03.904590 [ 82 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: DC9D3CA0A2E89B903B7F99DC0AC7E60E)
[665bc865432b] 2025.09.23 13:23:04.502618 [ 82 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
[665bc865432b] 2025.09.23 13:23:04.502899 [ 82 ] <Fatal> BaseDaemon: Changed settings: input_format_parquet_use_native_reader_v3 = true
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

**ClickHouse version:** `25.8.4.13`
**Settings:** `input_format_parquet_use_native_reader_v3=1`
**The file that caused the issue:** https://github.com/Selfeer/parquet-files/blob/main/parquet/boolean_bloom.gz.parquet

**Steps:**

I just ran the SELECT query a couple of times:

```sql
SELECT * FROM file('boolean_bloom.gz.parquet', 'Parquet') SETTINGS input_format_parquet_use_native_reader_v3 = 1
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

~This PR is stacked on top of https://github.com/ClickHouse/ClickHouse/pull/87220 , review only the commits starting from `Fixes for parquet reader v3, enable it in stateless tests`.~

Closes https://github.com/ClickHouse/ClickHouse/issues/87509
Closes https://github.com/ClickHouse/ClickHouse/issues/87396

All stateless tests should pass now.

### CODE REVIEW

**Comment by EmeraldShift** [comment]
Any chance these and all your other good fixes to pqv3 and index analysis can be backported to 25.8 LTS and 25.9-stable?

File: src/Storages/StorageURL.cpp [hunk 1]
```diff
@@ -1096,7 +1096,7 @@ bool IStorageURLBase::canMoveConditionsToPrewhere() const
 
 std::optional<NameSet> IStorageURLBase::supportedPrewhereColumns() const
 {
-    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions();
+    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions(hive_partition_columns_to_read_from_file_path);
```
Comment (divanik) [inline src/Storages/StorageURL.cpp]:
```suggestion
    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions(/*exclude=*/hive_partition_columns_to_read_from_file_path);
```

File: src/Storages/StorageFile.cpp [hunk 2]
```diff
@@ -1029,8 +1029,9 @@ bool StorageFile::canMoveConditionsToPrewhere() const
 
 std::optional<NameSet> StorageFile::supportedPrewhereColumns() const
 {
-    /// Currently don't support prewhere for virtual columns and columns with default expressions.
-    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions();
+    /// Currently don't support prewhere for virtual columns, columns with default expressions,
+    /// and columns taken from file path (hive partitioning).
+    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions(hive_partition_columns_to_read_from_file_path);
```
Comment (divanik) [inline src/Storages/StorageFile.cpp]:
```suggestion
    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions(/*exclude=*/hive_partition_columns_to_read_from_file_path);

```

File: src/Storages/ObjectStorage/StorageObjectStorage.cpp [hunk 3]
```diff
@@ -263,7 +263,7 @@ bool StorageObjectStorage::canMoveConditionsToPrewhere() const
 
 std::optional<NameSet> StorageObjectStorage::supportedPrewhereColumns() const
 {
-    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions();
+    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions(hive_partition_columns_to_read_from_file_path);
```
Comment (divanik) [inline src/Storages/ObjectStorage/StorageObjectStorage.cpp]:
```suggestion
    return getInMemoryMetadataPtr()->getColumnsWithoutDefaultExpressions(/*exclude=*/hive_partition_columns_to_read_from_file_path);

```

File: src/Formats/FormatFactory.h [hunk 4]
```diff
@@ -178,7 +178,7 @@ class FormatFactory final : private boost::noncopyable
         UInt64 max_block_size,
         const std::optional<FormatSettings> & format_settings = std::nullopt,
         FormatParserSharedResourcesPtr parser_shared_resources = nullptr,
-        FormatFilterInfoPtr format_filter_info = std::make_shared<FormatFilterInfo>(),
+        FormatFilterInfoPtr format_filter_info = nullptr,
```
Comment (divanik) [inline src/Formats/FormatFactory.h:183]: Could you explain the reason behind this change, please?

File: src/Formats/FormatFilterInfo.cpp [hunk 5]
```diff
@@ -15,11 +15,15 @@ namespace DB
...
     extern const int LOGICAL_ERROR;
+    extern const int ICEBERG_SPECIFICATION_VIOLATION;
 }
 
 void ColumnMapper::setStorageColumnEncoding(std::unordered_map<String, Int64> && storage_encoding_)
 {
     storage_encoding = std::move(storage_encoding_);
+    for (const auto & [column_name, field_id] : storage_encoding)
+        if (!field_id_to_clickhouse_name.emplace(field_id, column_name).second)
+            throw Exception(ErrorCodes::ICEBERG_SPECIFICATION_VIOLATION, "Duplicate field id {}", field_id);
```
Comment (divanik) [inline src/Formats/FormatFilterInfo.cpp:27]: I think that logic supposes that setStorageColumnEncoding is called uniquely, doesn't it. If so, let's add a check that storage_encoding is std::nullopt in the beginning of this function

File: tests/queries/0_stateless/03036_test_parquet_bloom_filter_push_down.sh [hunk 6]
```diff
@@ -22,96 +22,96 @@ ${CLICKHOUSE_CLIENT} --query="select count(*) from file('${DATA_FILE_USER_PATH}'
 
 echo "bloom filter is off, all row groups should be read"
 echo "expect rows_read = select count()"
```
Comment (divanik) [inline tests/queries/0_stateless/03036_test_parquet_bloom_filter_push_down.sh:26]: JAS:

```suggestion
${CLICKHOUSE_CLIENT} --query="SET optimize_move_to_prewhere=false"
${CLICKHOUSE_CLIENT} --query="input_format_parquet_page_filter_push_down"
```

File: src/Processors/Formats/Impl/Parquet/Decoding.cpp [hunk 7]
```diff
@@ -745,7 +745,7 @@ struct ByteStreamSplitDecoder : public PageDecoder
 
 bool PageDecoderInfo::canReadDirectlyIntoColumn(parq::Encoding::type encoding, size_t num_values, IColumn & col, std::span<char> & out) const
 {
-    if (encoding == parq::Encoding::PLAIN && fixed_size_converter && fixed_size_converter->isTrivial())
+    if (encoding == parq::Encoding::PLAIN && fixed_size_converter && physical_type != parq::Type::BOOLEAN && fixed_size_converter->isTrivial())
```
Comment (divanik) [inline src/Processors/Formats/Impl/Parquet/Decoding.cpp:748]: Why can't we read boolean directly to column?

File: src/Processors/Formats/Impl/Parquet/Reader.h [hunk 8]
```diff
@@ -455,8 +450,10 @@ struct Reader
     size_t total_primitive_columns_in_file = 0;
     std::vector<OutputColumnInfo> output_columns;
     /// Maps idx_in_output_block to index in output_columns. I.e.:
-    /// sample_block_to_output_columns_idx[output_columns[i].idx_in_output_block] = i
-    std::vector<size_t> sample_block_to_output_columns_idx;
+    ///     sample_block_to_output_columns_idx[output_columns[i].idx_in_output_block] = i
+    /// nullopt if the column is produced by PREWHERE expression:
+    ///     prewhere_steps[k].idx_in_output_block == i
```
Comment (divanik) [inline src/Processors/Formats/Impl/Parquet/Reader.h]: What is k here?

File: src/Processors/Formats/Impl/Parquet/Reader.cpp [hunk 9]
```diff
@@ -602,54 +609,71 @@ void Reader::initializePrefetches()
...
-            step.input_column_idxs.push_back(output_idx);
+    /// Assert that sample_block_to_output_columns_idx is valid.
+    for (size_t i = 0; i < sample_block_to_output_columns_idx.size(); ++i)
+    {
+        /// (`prewhere_steps` has at most two elements)
+        size_t is_prewhere_output = std::count_if(prewhere_steps.begin(), prewhere_steps.end(),
+            [&](const PrewhereStep & step) { return step.idx_in_output_block == i; });
+        if (is_prewhere_output > 1 ||
+            /// Column must appear in exactly one of {output_columns, prewhere output}.
+            sample_block_to_output_columns_idx[i].has_value() == (is_prewhere_output == 1))
```
Comment (divanik) [inline src/Processors/Formats/Impl/Parquet/Reader.cpp]: FYI: A bit difficult condition to read, but not a catastrophe

File: src/Processors/Formats/Impl/Parquet/Reader.cpp [hunk 10]
```diff
@@ -602,54 +609,71 @@ void Reader::initializePrefetches()
...
-    /// TODO [parquet]: We currently run prewhere after reading all prewhere columns of the row
-    ///     subgroup, in one thread per row group. Instead, we could extract single-column conditions
-    ///     and run them after decoding the corresponding columns, in parallel.
-    ///     (Still run multi-column conditions, like `col1 = 42 or col2 = 'yes'`, after reading all columns.)
-    ///     Probably reuse tryBuildPrewhereSteps from MergeTree for splitting the expression.
-
-    /// Convert ActionsDAG to ExpressionActions.
-    ExpressionActionsSettings actions_settings;
-    if (prewhere_info->row_level_filter.has_value())
+    if (prewhere_info)
```
Comment (divanik) [inline src/Processors/Formats/Impl/Parquet/Reader.cpp]: JAS: move assertion to the top and return early "return from function"

**Review by divanik — COMMENTED** [review]
Took a look partially, will review SchemaConverter a bit later

File: src/Formats/FormatFactory.h (hunk 4 above)
Comment (al13n321) [reply src/Formats/FormatFactory.h:183]: To not create it for formats that don't need it.

File: src/Processors/Formats/Impl/Parquet/Decoding.cpp (hunk 7 above)
Comment (al13n321) [reply src/Processors/Formats/Impl/Parquet/Decoding.cpp:748]: In the file it's 1 bit per value, in column it's 1 byte per value.

File: src/Processors/Formats/Impl/Parquet/Reader.cpp (hunk 10 above)
Comment (al13n321) [reply src/Processors/Formats/Impl/Parquet/Reader.cpp]: How do you move the assertion without duplicating code?

**Comment by al13n321** [comment]
Is there a label to make CI run all tests? Does `ci-non-blocking` do that? Does `no-fast-tests` do that (except for fast tests)? EDIT: Yes, at least one of these seems to work.

**Comment by al13n321** [comment]
03578_parallel_replicas_minicrawl and ast fuzzer are flaky.

File: src/Processors/Formats/Impl/Parquet/Decoding.cpp [hunk 11]
```diff
@@ -1419,7 +1419,7 @@ void GeoConverter::convertColumn(std::span<const char> chars, const UInt64 * off
 {
     col.reserve(col.size() + num_values);
     chassert(chars.size() >= offsets[num_values - 1]);
-    for (size_t i = 0; i < num_values; ++i)
+    for (ssize_t i = 0; i < ssize_t(num_values); ++i)
```
Comment (divanik) [inline src/Processors/Formats/Impl/Parquet/Decoding.cpp:1422]: I am not sure that the underlying code is written in a safe manner, but this change is obviously an improvement

File: src/Processors/Formats/Impl/Parquet/SchemaConverter.h [hunk 12]
```diff
@@ -49,23 +58,87 @@ struct SchemaConverter
...
+        {
+            if (!name.empty())
+                name += ".";
+            name += mapped_field_name;
+            if (parquet_name.has_value() || mapped_field_name != parquet_field_name)
+            {
+                if (parquet_name.has_value())
+                    *parquet_name += ".";
+                else
+                    parquet_name.emplace();
```
Comment (divanik) [inline src/Processors/Formats/Impl/Parquet/SchemaConverter.h:105]: Shouldn't we copy the whole name here?

**Review by divanik — APPROVED** [review]

File: src/Processors/Formats/Impl/Parquet/Decoding.cpp (hunk 11 above)
Comment (al13n321) [reply src/Processors/Formats/Impl/Parquet/Decoding.cpp:1422]: `offsets[-1]` is valid, that's how ch array/string offsets wok.

File: src/Processors/Formats/Impl/Parquet/SchemaConverter.h (hunk 12 above)
Comment (al13n321) [reply src/Processors/Formats/Impl/Parquet/SchemaConverter.h:105]: The next line does that? Like, if it's the first component of the name then append it to empty string, without a '.'

**Comment by al13n321** [comment]
03658_joined_block_split_single_row_bytes and 03578_parallel_replicas_minicrawl are flaky.
