### PR TITLE
Fix `ObjectStorageQueue` with ZK and older Keeper

### LINKED ISSUE #70376: 24.8 S3Queue + Zookeeper 3.8 => Marshalling error
```
SELECT * FROM s3_files_queue SETTINGS stream_like_engine_allow_direct_select = 1
Query id: fb9598bc-0b03-45b5-b8e2-bea98cb9468b
Elapsed: 0.040 sec. 

Received exception from server (version 24.8.4):
Code: 999. DB::Exception: Received from localhost:9011. DB::Exception: Coordination error: Marshalling error: While executing ObjectStorageQueue. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c2cb4e4
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000763a89c
2. DB::Exception::Exception<char const*>(int, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x00000000099ac278
3. Coordination::Exception::Exception<char const*>(Coordination::Error, FormatStringHelperImpl<std::type_identity<char const*>::type>, char const*&&) @ 0x00000000113410b0
4. Coordination::Exception::Exception(Coordination::Error) @ 0x000000001134106c
5. zkutil::ZooKeeper::tryMulti(std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>&, bool) @ 0x000000001134fa7c
6. DB::ObjectStorageQueueUnorderedFileMetadata::setProcessingImpl() @ 0x0000000010b5e570
7. DB::ObjectStorageQueueIFileMetadata::setProcessing() @ 0x0000000010ae9220
8. DB::ObjectStorageQueueSource::FileIterator::nextImpl(unsigned long) @ 0x0000000010b6daac
9. DB::StorageObjectStorageSource::IIterator::next(unsigned long) @ 0x000000000eb8a9e8
10. DB::StorageObjectStorageSource::createReader(unsigned long, std::shared_ptr<DB::StorageObjectStorageSource::IIterator> const&, std::shared_ptr<DB::StorageObjectStorage::Configuration> const&, std::shared_ptr<DB::IObjectStorage> const&, DB::ReadFromFormatInfo&, std::optional<DB::FormatSettings> const&, std::shared_ptr<DB::KeyCondition const> const&, std::shared_ptr<DB::Context const> const&, DB::SchemaCache*, std::shared_ptr<Poco::Logger> const&, unsigned long, unsigned long, bool) @ 0x000000000eb88d54
11. DB::ObjectStorageQueueSource::generateImpl() @ 0x0000000010b75c34
12. DB::ObjectStorageQueueSource::generate() @ 0x0000000010b75900
13. DB::ISource::tryGenerate() @ 0x0000000010d1a76c
14. DB::ISource::work() @ 0x0000000010d1a454
15. DB::ExecutionThreadContext::executeTask() @ 0x0000000010d2ec90
16. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000010d254d0
17. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000010d269a4
18. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c38953c
19. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c38cf90
20. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c38bdac
21. start_thread @ 0x0000000000007624
22. ? @ 0x00000000000d162c
. (KEEPER_EXCEPTION)
```

In Zookeeper logs: 

```
2024-10-04 10:31:03,124 [myid:] - ERROR [ProcessThread(sid:0 cport:2181)::o.a.z.s.PrepRequestProcessor@951] - Failed to process sessionid:0x1000c356a16093d type:multi cxid:0x90 zxid:0xde12 txntype:14 reqpath:
java.io.IOException: Invalid type of op
	at org.apache.zookeeper.MultiOperationRecord.deserialize(MultiOperationRecord.java:162)
	at org.apache.zookeeper.server.ByteBufferInputStream.byteBuffer2Record(ByteBufferInputStream.java:78)
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequestHelper(PrepRequestProcessor.java:832)
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequest(PrepRequestProcessor.java:779)
	at org.apache.zookeeper.server.PrepRequestProcessor.run(PrepRequestProcessor.java:157)
```

See also https://github.com/ClickHouse/ClickHouse/issues/67895

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix ObjectStorageQueue with ZooKeeper and older Keeper

Fix https://github.com/ClickHouse/ClickHouse/issues/70376

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp [hunk 1]
```diff
@@ -37,56 +37,66 @@ ObjectStorageQueueUnorderedFileMetadata::ObjectStorageQueueUnorderedFileMetadata
...
-    Coordination::Requests requests;
-    requests.push_back(zkutil::makeCreateRequest(processed_node_path, "", zkutil::CreateMode::Persistent));
-    requests.push_back(zkutil::makeRemoveRequest(processed_node_path, -1));
-    requests.push_back(zkutil::makeCreateRequest(failed_node_path, "", zkutil::CreateMode::Persistent));
-    requests.push_back(zkutil::makeRemoveRequest(failed_node_path, -1));
-    requests.push_back(zkutil::makeCreateRequest(processing_node_path, node_metadata.toString(), zkutil::CreateMode::Ephemeral));
+    while (true)
+    {
+        Coordination::Requests requests;
+        const size_t processed_path_doesnt_exist = 0;
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp:47]:
```suggestion
        const size_t processed_path_doesnt_exist_idx = 0;
```
may be like this?

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp [hunk 2]
```diff
@@ -37,56 +37,66 @@ ObjectStorageQueueUnorderedFileMetadata::ObjectStorageQueueUnorderedFileMetadata
...
-    }
+        bool create_if_not_exists_enabled = zk_client->isFeatureEnabled(DB::KeeperFeatureFlag::CREATE_IF_NOT_EXISTS);
+        if (create_if_not_exists_enabled)
+        {
+            requests.push_back(
+                zkutil::makeCreateRequest(processing_node_id_path, "", zkutil::CreateMode::Persistent, /* ignore_if_exists */ true));
 
-    if (is_request_failed(PROCESSED_PATH_DOESNT_EXIST))
-        return {false, FileStatus::State::Processed};
+            requests.push_back(zkutil::makeSetRequest(processing_node_id_path, processor_info, -1));
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp:62]: same as above - e.g. line 69 is identical so it can be moved after if-else block

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp [hunk 3]
```diff
@@ -37,56 +37,66 @@ ObjectStorageQueueUnorderedFileMetadata::ObjectStorageQueueUnorderedFileMetadata
...
+            return {false, FileStatus::State::Failed};
+
+        if (has_request_failed(created_processing_path))
+            return {false, FileStatus::State::Processing};
+
+        if (create_if_not_exists_enabled)
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Unexpected state of zookeeper transaction: {}", magic_enum::enum_name(code));
+
+        /// most likely the node was removed so let's try again
+        LOG_TRACE(log, "Retrying setProcessing because processing node id path is unexpectedly missing or was created");
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueUnorderedFileMetadata.cpp:98]: add `code` to log message?

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueOrderedFileMetadata.cpp [hunk 4]
```diff
@@ -259,61 +257,78 @@ std::pair<bool, ObjectStorageQueueIFileMetadata::FileStatus::State> ObjectStorag
...
             LOG_TEST(log, "Version of max processed file changed: {}. Will retry for file `{}`", code, path);
             continue;
         }
 
-        throw Exception(ErrorCodes::LOGICAL_ERROR, "Unexpected response state: {}", code);
+        if (create_if_not_exists_enabled)
+            throw Exception(ErrorCodes::LOGICAL_ERROR, "Unexpected state of zookeeper transaction: {}", magic_enum::enum_name(code));
+
+        /// most likely the processing node id path node was removed or created so let's try again
+        LOG_TRACE(log, "Retrying setProcessing because processing node id path is unexpectedly missing or was created");
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueOrderedFileMetadata.cpp:331]: same about `code`

File: src/Storages/ObjectStorageQueue/ObjectStorageQueueOrderedFileMetadata.cpp [hunk 5]
```diff
@@ -259,61 +257,78 @@ std::pair<bool, ObjectStorageQueueIFileMetadata::FileStatus::State> ObjectStorag
         }
 
         Coordination::Requests requests;
-        requests.push_back(zkutil::makeCreateRequest(failed_node_path, "", zkutil::CreateMode::Persistent));
-        requests.push_back(zkutil::makeRemoveRequest(failed_node_path, -1));
+        const auto failed_path_doesnt_exist = 0;
```
Comment (kssenii) [inline src/Storages/ObjectStorageQueue/ObjectStorageQueueOrderedFileMetadata.cpp:260]:
```suggestion
        const auto failed_path_doesnt_exist_idx = 0;
```
idx/ind/index/etc ?

**Review by kssenii — APPROVED** [review]
