### PR TITLE
Fix issues 39469

### LINKED ISSUE #39469: Projection select query exception. Not found column toStartOfHour(datetime) in block.
**Describe what's wrong**

I am testing projection. An exception was found during query: ```DB::Exception: Not found column toStartOfHour(datetime) in block.```

**Does it reproduce on recent release?**

v22.3.4.20-lts

**How to reproduce**

* My ClickHouse server version is 22.3.4.20 and 22.7.1

```
CREATE TABLE video_log
(
 `datetime` DateTime, -- 20,000 records per second
 `user_id` UInt64, -- Cardinality == 100,000,000
 `device_id` UInt64, -- Cardinality == 200,000,000
 `domain` LowCardinality(String), -- Cardinality == 100
 `bytes` UInt64, -- Ranging from 128 to 1152
 `duration` UInt64 -- Ranging from 100 to 400
)
ENGINE = MergeTree
PARTITION BY toDate(datetime) -- Daily partitioning
ORDER BY (user_id, device_id); -- Can only favor one column here

CREATE TABLE rng
(
 `user_id_raw` UInt64,
 `device_id_raw` UInt64,
 `domain_raw` UInt64,
 `bytes_raw` UInt64,
 `duration_raw` UInt64
)
ENGINE = GenerateRandom(1024);

INSERT INTO video_log SELECT
 toUnixTimestamp(toDateTime(today()))
 + (rowNumberInAllBlocks() / 20000),
 user_id_raw % 100000000 AS user_id,
 device_id_raw % 200000000 AS device_id,
 domain_raw % 100,
 (bytes_raw % 1024) + 128,
 (duration_raw % 300) + 100
FROM rng
LIMIT 17280000;

ALTER TABLE video_log ADD PROJECTION p_norm
 (
 SELECT
 datetime,
 device_id,
 bytes,
 duration
 ORDER BY device_id
 );

ALTER TABLE video_log MATERIALIZE PROJECTION p_norm;

ALTER TABLE video_log ADD PROJECTION p_agg
 (
 SELECT
 toStartOfHour(datetime) AS hour,
 domain,
 sum(bytes),
 avg(duration)
 GROUP BY
 hour,
 domain
 );

ALTER TABLE video_log MATERIALIZE PROJECTION p_agg;

```
```

SELECT
    toStartOfHour(datetime) AS hour,
    sum(bytes),
    avg(duration)
FROM video_log
WHERE (toDate(hour) = today()) AND (device_id = '100')
GROUP BY hour

Query id: ffc3bc0c-26cf-4415-9a00-d2184130c30d


0 rows in set. Elapsed: 0.035 sec. 

Received exception from server (version 22.7.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column toStartOfHour(datetime) in block. (NOT_FOUND_COLUMN_IN_BLOCK)

```

### PR DESCRIPTION
**Pull request by nicelulu**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible "Not found column in block" exception when using projections. This closes #39469

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
I've edited the changelog.

Was:
> https://github.com/ClickHouse/ClickHouse/issues/39469

Now:
> Fix possible "Not found column in block" exception when using projections. This closes #39469

**Comment by alexey-milovidov** [comment]
@kssenii a test for PostgreSQL replica has failed: https://s3.amazonaws.com/clickhouse-test-reports/39470/c5d9a6c37c1e6fa5be6bfff332943cabb13242cb/integration_tests__asan__[3/3].html

**Comment by alexey-milovidov** [comment]
@nicelulu flaky check shows that the new test is flaky: https://s3.amazonaws.com/clickhouse-test-reports/39470/c5d9a6c37c1e6fa5be6bfff332943cabb13242cb/stateless_tests_flaky_check__address_.html

PTAL.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

**Comment by nicelulu** [comment]
```
2022.07.25 11:38:44.753334 [ 892 ] {fe1d8acf-fc7c-4c12-ab27-1897ac551585} <Error> test_2m9u7n.video_log (321809a5-9194-4edf-a12f-04c201753597): Cannot quickly remove directory /var/lib/clickhouse/store/321/321809a5-9194-4edf-a12f-04c201753597/delete_tmp_tmp_mut_20220722_2_2_0_5 by removing files; fallback to recursive removal. Reason: Code: 458. DB::ErrnoException: Cannot unlink file /var/lib/clickhouse/store/321/321809a5-9194-4edf-a12f-04c201753597/delete_tmp_tmp_mut_20220722_2_2_0_5/checksums.txt, errno: 2, strerror: No such file or directory. (CANNOT_UNLINK) (version 22.8.1.1)
2
```
Strange, doesn't seem to have anything to do with the change.

**Comment by alexey-milovidov** [comment]
Yes, looks strange. Need help from @tavplubix

**Comment by tavplubix** [comment]
> Cannot quickly remove directory ... delete_tmp_tmp_mut_20220722_2_2_0_5 ... Cannot unlink file ... delete_tmp_tmp_mut_20220722_2_2_0_5/checksums.txt ...  No such file or directory

It's because part was not completely mutated and some files are absent (It's OK).
Part was not completely mutated because ALTERs in test are asynchronous.
So new test it not quite correct.

File: tests/queries/0_stateless/02371_select_projection_normal_agg.sql [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+        avg(duration)
+    GROUP BY
+        hour,
+        domain
+);
+
+ALTER TABLE video_log MATERIALIZE PROJECTION p_agg;
+
+SELECT sleep(3);
+SELECT sleep(3);
```
Comment (tavplubix) [inline tests/queries/0_stateless/02371_select_projection_normal_agg.sql:77]: There's no way it can work

File: tests/queries/0_stateless/02371_select_projection_normal_agg.sql [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+
+SELECT
+    toStartOfHour(datetime) AS hour,
+    ignore(sum(bytes)),
+    ignore(avg(duration))
+FROM video_log
+WHERE (toDate(hour) = '2022-07-22') AND (device_id = '100') --(device_id = '100') Make sure it's not good and doesn't go into prewhere.
+GROUP BY hour;
```
Comment (tavplubix) [inline tests/queries/0_stateless/02371_select_projection_normal_agg.sql:85]: Seems like this query does not actually check result of ALTERs

File: tests/queries/0_stateless/02371_select_projection_normal_agg.sql (hunk 1 above)
Comment (nicelulu) [reply tests/queries/0_stateless/02371_select_projection_normal_agg.sql:77]: Thanks

**Review by alexey-milovidov — APPROVED** [review]
