### PR TITLE
Short circuit optimization for functions executed over Nullable arguments

### LINKED ISSUE #34854: "Unexpected inf or nan to integer conversion" error when using toInt32 and if/isNaN check
**Describe the unexpected behaviour**

"Unexpected inf or nan to integer conversion" error is thrown when calling `toInt32` on the result of an `if` expression that checks for `isNaN` and evaulates to `NULL`.

**How to reproduce**

* Which ClickHouse server version to use:  **21.12.4 revision 54452** & **22.2.2 revision 54455**
* Which interface to use, if matters: **clickhouse-client**
* Non-default settings, if any: **none**

* `CREATE TABLE` statements for all tables involved

```
create temporary table tmp_repro_nan_check (
  foo Nullable(Int32)
);
```

* Sample data for all these tables, use [clickhouse-obfuscator]

```
insert into tmp_repro_nan_check values (nan);
```

* Queries to run that lead to unexpected result
```
SELECT toInt32(if(isNaN(foo), NULL, foo))
FROM tmp_repro_nan_check
```

**Expected behavior**

Expect the result to be `NULL` similar to the following:

```
SELECT toInt32(NULL)
```

**Error message and/or stacktrace**

```
Code: 70. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected inf or nan to integer conversion: while executing 'FUNCTION toInt32(if(isNaN(foo), NULL, foo) :: 3) -> toInt32(if(isNaN(foo), NULL, foo)) Nullable(Int32) : 0'. (CANNOT_CONVERT_TYPE)
```

**Additional context**

There seems to be an issues with returning `NULL` in the truthy/left branch of the condition. Updating the select statement to return `0` does not throw an error

```
SELECT toInt32(if(isNaN(foo), 0, foo))
FROM tmp_repro_nan_check

Query id: 6f91e2e3-caf2-4aa8-96a0-83bd6755ca37

┌─toInt32(if(isNaN(foo), 0, foo))─┐
│                               0 │
└─────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add 2 new settings `short_circuit_function_evaluation_for_nulls` and `short_circuit_function_evaluation_for_nulls_threshold` that allow to execute functions over `Nullable` columns in short-circuit manner when the ratio of NULL values in the block of data exceeds the specified threshold. It means that the function will be executed only on rows with non-null values. It applies only to functions that return NULL value for rows where at least one argument is NULL.

It also closes https://github.com/ClickHouse/ClickHouse/issues/34854

### Documentation entry:
Short circuit optimization for defaultImplementationForNulls. It makes sense only when useDefaultImplementationForNulls() = true. For functions with useDefaultImplementationForNulls() = true, and result_type is Nullable(T): 
- If each rows contains argument with null value, skip function evaluation and return column with all rows null directly
- If `short_circuit_function_evaluation_for_nulls` and the ratio of rows containing nulls to total rows exceeds `short_circuit_function_evaluation_for_nulls_threshold`, skip evaluation for those rows containing nulls 
- Otherwise process rows as it was processed before. 

``` sql 
SQL:
with null::Nullable(String) as x, 'hello' as y, ' clickhouse' as z  select concat(materialize(x), materialize(y), materialize(z)) from numbers(10000000) format Null;   

Before: 
0 rows in set. Elapsed: 0.253 sec. Processed 10.00 million rows, 80.00 MB (39.57 million rows/s., 316.54 MB/s.)
Peak memory usage: 4.00 MiB.

After:
0 rows in set. Elapsed: 0.518 sec. Processed 10.00 million rows, 80.00 MB (19.30 million rows/s., 154.40 MB/s.)
Peak memory usage: 11.33 MiB.
```

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 2febfb4173665dee83352d1c06aa02a0457e41b1 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60129/2febfb4173665dee83352d1c06aa02a0457e41b1/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/60129/2febfb4173665dee83352d1c06aa02a0457e41b1/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Avogar** [comment]
We should add a setting to be able to turn it on/off

**Comment by taiyang-li** [comment]
> We should add a setting to be able to turn it on/off

I'm afraid current changes will slow down performance. Let's keep it as draft.

**Comment by taiyang-li** [comment]
> But we still can have it under a setting that will be disabled by default, it will be useful in some cases. For example, afaiu it an solve this problem: [#34854 (comment)](https://github.com/ClickHouse/ClickHouse/issues/34854#issuecomment-1059139859)

I'll try.

**Comment by taiyang-li** [comment]
@Avogar  I wonder why  "ClickHouse special build check" is pending in : https://s3.amazonaws.com/clickhouse-test-reports/60129/7cf67df78d19c7e2722b423ba311872f6628964c/clickhouse_special_build_check/report.html

**Comment by Avogar** [comment]
> Do you known why ?

No I don't. Fast test is failed and in this case we don't run any build checks. Let's ask @Felixoid why it shows pending.
BTW, server creashes in Fast test and it's related to the changes, please, take a look and fix

**Comment by Algunenano** [comment]
Fast tests is a hard check before other tasks are run, like other builds or full stateless tests.

**Comment by Felixoid** [comment]
Both reports are pending because of the crashed server, @Algunenano is right.

**Comment by Avogar** [comment]
> Both reports are pending because of the crashed server, Algunenano is right.

Probably the question was why it is pending when we will not run any builds (as fasttest fail), pending status may be misleading that it will be run

**Comment by taiyang-li** [comment]
> > Both reports are pending because of the crashed server, Algunenano is right.
> 
> Probably the question was why it is pending when we will not run any builds (as fast test fail), pending status may be misleading that it will be actually run

Yes, this is the most important thing I care about. Where could I find any valuable clues to fix it ?

**Comment by taiyang-li** [comment]
> Both reports are pending because of the crashed server, @Algunenano is right.

Crash is fixed now. Let wait for ci.

File: src/Core/Settings.h [hunk 1]
```diff
@@ -896,6 +896,7 @@ class IColumn;
...
     M(Int64, prefer_warmed_unmerged_parts_seconds, 0, "Only available in ClickHouse Cloud. If a merged part is less than this many seconds old and is not pre-warmed (see cache_populated_by_fetch), but all its source parts are available and pre-warmed, SELECT queries will read from those parts instead. Only for ReplicatedMergeTree. Note that this only checks whether CacheWarmer processed the part; if the part was fetched into cache by something else, it'll still be considered cold until CacheWarmer gets to it; if it was warmed, then evicted from cache, it'll still be considered warm.", 0) \
     M(Bool, iceberg_engine_ignore_schema_evolution, false, "Ignore schema evolution in Iceberg table engine and read all data using latest schema saved on table creation. Note that it can lead to incorrect result", 0) \
+    M(Bool, allow_short_circuit_default_implementation_for_nulls, false, "Setting for short-circuit default implementations for null in function with useDefaultImplementationForNulls() = true. If true, function will not actually evaluate for rows in which there are at least one argument with null value.", 0) \
```
[the remark this answers is not in the document]
Comment (taiyang-li) [reply src/Core/Settings.h]: done

**Comment by taiyang-li** [comment]
It is ready for review now. cc @Avogar

**Comment by Avogar** [comment]
Fast test failed because of another issue: https://github.com/ClickHouse/ClickHouse/issues/62917
Let's merge with master

File: src/Functions/FunctionHelpers.cpp [hunk 2]
```diff
@@ -275,6 +275,37 @@ ColumnPtr wrapInNullable(const ColumnPtr & src, const ColumnsWithTypeAndName & a
...
+    if (src->onlyNull())
+        return src;
+
+    ColumnPtr result_null_map_column;
+
+    /// If result is already nullable.
+    ColumnPtr src_not_nullable = src;
+
+    if (src->onlyNull())
+        return src;
```
Comment (Avogar) [inline src/Functions/FunctionHelpers.cpp:289]: We already have this check above

File: src/Functions/FunctionHelpers.cpp [hunk 3]
```diff
@@ -275,6 +275,37 @@ ColumnPtr wrapInNullable(const ColumnPtr & src, const ColumnsWithTypeAndName & a
...
+    else if (const auto * nullable = checkAndGetColumn<ColumnNullable>(*src))
+    {
+        src_not_nullable = nullable->getNestedColumnPtr();
+        result_null_map_column = nullable->getNullMapColumnPtr();
+
+        MutableColumnPtr mutable_result_null_map_column = IColumn::mutate(std::move(result_null_map_column));
+        NullMap & result_null_map = assert_cast<ColumnUInt8 &>(*mutable_result_null_map_column).getData();
+        const NullMap & null_map_data = assert_cast<const ColumnUInt8 &>(*null_map).getData();
+        for (size_t i = 0; i < result_null_map.size(); ++i)
+            result_null_map[i] |= null_map_data[i];
```
Comment (Avogar) [inline src/Functions/FunctionHelpers.cpp:299]: Can we just use `ColumnNullable::applyNullMap` ?

**Review by Avogar — COMMENTED** [review]
Overall looks good, let's see the tests

File: src/Functions/FunctionHelpers.cpp (hunk 3 above)
Comment (taiyang-li) [reply src/Functions/FunctionHelpers.cpp:299]: I'm afrait not.  `ColumnNullable::applyNullMap` requires mutable nullable column, which means we have to execute `IColumn::mutate(nullable)`. It is obviously too heavy, compared to just executing `IColumn::mutate(std::move(result_null_map_column));`.

**Comment by Avogar** [comment]
Fast test failures seems related

**Comment by Avogar** [comment]
@taiyang-li do ypu plan to finish this PR or we can close it?

**Comment by taiyang-li** [comment]
> @taiyang-li do ypu plan to finish this PR or we can close it?

I'd like to continue to do it.

File: src/Core/SettingsChangesHistory.h [hunk 4]
```diff
@@ -131,6 +131,7 @@ static const std::map<ClickHouseVersion, SettingsChangesHistory::SettingsChanges
               {"max_parsing_threads", 0, 0, "Add a separate setting to control number of threads in parallel parsing from files"},
               {"ignore_drop_queries_probability", 0, 0, "Allow to ignore drop queries in server with specified probability for testing purposes"},
               {"lightweight_deletes_sync", 2, 2, "The same as 'mutation_sync', but controls only execution of lightweight deletes"},
+              {"allow_short_circuit_default_implementation_for_nulls", false, true, "Setting for short-circuit default implementations for null in function with useDefaultImplementationForNulls() = true. If true, function will not actually evaluate for rows in which there are at least one argument with null value."},
```
Comment (Algunenano) [inline src/Core/SettingsChangesHistory.h:134]: 24.6 is released. This will need to be changed

**Comment by Avogar** [comment]
`Fast test — fail: 76` - please, fix the tests first. The failures are related to the changes

**Comment by taiyang-li** [comment]
@Avogar I had fix the failed uts, do you have time to review it again? Thanks!

**Comment by taiyang-li** [comment]
@alexey-milovidov hope for your reviews, thanks!

**Comment by Avogar** [comment]
I will take a look this week

File: src/Core/Settings.cpp [hunk 5]
```diff
@@ -5455,6 +5455,14 @@ Only available in ClickHouse Cloud. Number of background threads for speculative
...
     DECLARE(Int64, ignore_cold_parts_seconds, 0, R"(
 Only available in ClickHouse Cloud. Exclude new data parts from SELECT queries until they're either pre-warmed (see cache_populated_by_fetch) or this many seconds old. Only for Replicated-/SharedMergeTree.
+)", 0) \
+    DECLARE(Bool, short_circuit_default_implementation_for_nulls, true, R"(
+Setting for short-circuit default implementations for nulls in function with useDefaultImplementationForNulls() = true.
+If true, function will not actually evaluate for rows in which there are at least one argument with null value.
+)", 0) \
+    DECLARE(Double, short_circuit_default_implementation_for_nulls_threshold, 1.0, R"(
+Ratio threshold for short-circuit default implementations for nulls in function with useDefaultImplementationForNulls() = true. It is only valid when short_circuit_default_implementation_for_nulls is true.
+When the ratio of rows containing nulls to the total number of rows exceeds this threshold, these rows containing nulls would not be evaluated.
```
Comment (Avogar) [inline src/Core/Settings.cpp:5465]: From user perspective it's unclear what is `default implementation for nulls`, let's not use it in setting name and description and write better description.
For setting names, maybe better to use smth like `short_circuit_function_evaluation_for_nulls` and `short_circuit_function_evaluation_for_nulls_threshold`

File: src/Core/SettingsChangesHistory.cpp [hunk 6]
```diff
@@ -103,6 +103,8 @@ static std::initializer_list<std::pair<ClickHouseVersion, SettingsChangesHistory
             {"distributed_cache_read_alignment", 0, 0, "A setting for ClickHouse Cloud"},
             {"distributed_cache_max_unacked_inflight_packets", 10, 10, "A setting for ClickHouse Cloud"},
             {"distributed_cache_data_packet_ack_window", 5, 5, "A setting for ClickHouse Cloud"},
+            {"short_circuit_default_implementation_for_nulls", false, true, "Setting for short-circuit default implementations for null in function with useDefaultImplementationForNulls() = true. If true, function will not actually evaluate for rows in which there are at least one argument with null value."},
+            {"short_circuit_default_implementation_for_nulls_threshold", 0.0, 0.0, "Ratio threshold for short-circuit default implementations for nulls in function with useDefaultImplementationForNulls() = true. It is only valid when short_circuit_default_implementation_for_nulls is true."},
```
Comment (Avogar) [inline src/Core/SettingsChangesHistory.cpp:107]:
```suggestion
            {"short_circuit_default_implementation_for_nulls_threshold", 1.0, 1.0, "Ratio threshold for short-circuit default implementations for nulls in function with useDefaultImplementationForNulls() = true. It is only valid when short_circuit_default_implementation_for_nulls is true."},
```

**Comment by Avogar** [comment]
Looks good! Let's improve settings names and description and merge it

File: src/Core/SettingsChangesHistory.cpp (hunk 6 above)
Comment (Algunenano) [reply src/Core/SettingsChangesHistory.cpp:107]: And please move it to 24.11, since 24.10 branch has been created already

File: src/Core/Settings.cpp [hunk 7]
```diff
@@ -5465,6 +5465,13 @@ Only available in ClickHouse Cloud. Number of background threads for speculative
 )", 0) \
     DECLARE(Int64, ignore_cold_parts_seconds, 0, R"(
 Only available in ClickHouse Cloud. Exclude new data parts from SELECT queries until they're either pre-warmed (see cache_populated_by_fetch) or this many seconds old. Only for Replicated-/SharedMergeTree.
+)", 0) \
+    DECLARE(Bool, short_circuit_function_evaluation_for_nulls, true, R"(
+Whether to enable short-circuit evaluation for rows with at least one null in arguments in functions where useDefaultImplementationForNulls() is true.
```
Comment (Avogar) [inline src/Core/Settings.cpp:5470]:
```suggestion
Allows to execute functions with Nullable arguments only on rows with non-null values in all arguments. Applies only to functions that return NULL value for rows with at least one NULL value in arguments.
```

File: src/Core/Settings.cpp [hunk 8]
```diff
@@ -5465,6 +5465,13 @@ Only available in ClickHouse Cloud. Number of background threads for speculative
...
+)", 0) \
+    DECLARE(Double, short_circuit_function_evaluation_for_nulls_threshold, 1.0, R"(
+Ratio threshold for short-circuit evaluation for rows with at least one null in arguments in functions where useDefaultImplementationForNulls() is true. This is only valid when short_circuit_function_evaluation_for_nulls is true.
+When the ratio of rows containing nulls to the total number of rows exceeds this threshold, these rows containing nulls will not be evaluated.
```
Comment (Avogar) [inline src/Core/Settings.cpp:5474]:
```suggestion
Ratio threshold of NULL values in function arguments for short-circuit function evaluation of rows with at least one null in arguments. This is only valid when short_circuit_function_evaluation_for_nulls is enabled.
When the ratio of rows containing nulls to the total number of rows exceeds this threshold, these rows containing nulls will not be evaluated.
```

File: src/Core/SettingsChangesHistory.cpp [hunk 9]
```diff
@@ -64,6 +64,8 @@ static std::initializer_list<std::pair<ClickHouseVersion, SettingsChangesHistory
     },
     {"24.11",
         {
+            {"short_circuit_function_evaluation_for_nulls", false, true, "Whether to enable short-circuit evaluation for rows with at least one null in arguments in functions where useDefaultImplementationForNulls() is true."},
+            {"short_circuit_function_evaluation_for_nulls_threshold", 1.0, 1.0, "Ratio threshold for short-circuit evaluation for rows with at least one null in arguments in functions where useDefaultImplementationForNulls() is true. This is only valid when short_circuit_function_evaluation_for_nulls is true."},
```
Comment (Avogar) [inline src/Core/SettingsChangesHistory.cpp:68]:
```suggestion
            {"short_circuit_function_evaluation_for_nulls", false, true, "Allow to execute some functions with Nullable arguments only on rows with non-NULL values in all arguments"},
            {"short_circuit_function_evaluation_for_nulls_threshold", 1.0, 1.0, "Ratio threshold of NULL values to execute some functions with Nullable arguments only on rows with non-NULL values in all arguments. Applies when setting short_circuit_function_evaluation_for_nulls is enabled."},
```

**Comment by Avogar** [comment]
I see some degradation in performance tests:
Screenshot 2024-10-30 at 11 10 57
Screenshot 2024-10-30 at 11 11 15
I am afraid we cannot merge it like that

**Comment by taiyang-li** [comment]
@Avogar I'll look into it...

**Comment by taiyang-li** [comment]
@Avogar I can't reproduce the performance regression in my machine. Let's trigger the CI again and wait for the result.

**Comment by taiyang-li** [comment]
@Avogar do you know why there is no performance tests in the newest CI ?

**Comment by taiyang-li** [comment]
@Avogar I had improved the performance. Let's wait for the newest performance report.

**Comment by Avogar** [comment]
The fasttest is broken

**Comment by Avogar** [comment]
Performance tests are ok now. Failied test `02809_storage_set_analysis_bug` is related (it's flaky and fails only sometimes, you can run this test with `clickhouse-test --test-runs 100 -j 10` to reproduce)

**Comment by taiyang-li** [comment]
@Avogar `02809_storage_set_analysis_bug` is failed because for `in` function, the first argument contains null in each row.  The execution is short-circuited, instead of throwing exception, it returns `0`.

**Review by Avogar — APPROVED** [review]

**Comment by Algunenano** [comment]
It would be nice to have a performance test that verifies the impact of this feature in the real world. Right now all I see is 300 lines of code changed and some dubious performance reports with several degradations.

**Comment by taiyang-li** [comment]
@Algunenano we will test this feature in apache gluten. cc @baibaichen

**Comment by Algunenano** [comment]
As suspected and shown by the existing perf tests, it's degrading the performance:


```
SELECT count() FROM (SELECT toNullable(materialize(1)) AS x1, toNullable(materialize(1)) AS x2 FROM zeros(100000000000)) WHERE NOT ignore(xor(x1,x2)
```
* Before the change: 7.70 GB/s.
* After the change: 6.02 GB/s.

As the perf test show no advantage from having this change, I'm reverting this. Please resubmit with proper proof of the impact and without ignoring degradations in the existing benchmarks.

**Comment by clickgapai** [comment]
Hi @taiyang-li @Avogar — while reviewing this PR I found the following:

- **Coverage gap:** Short-circuit `filter`/`execute`/`expand` branch in `IExecutableFunction::defaultImplementationForNulls` has zero deterministic stateless coverage — https://github.com/ClickHouse/ClickHouse/pull/103878

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
