### PR TITLE
Dictionaries added Date32 type support

### LINKED ISSUE #32913: Date32 datatype is not supported in dictionaries
Date32 datatype is not supported in dictionaries. For example:
```sql
CREATE DICTIONARY testDate32
(
  date Date32
)
PRIMARY KEY date
SOURCE(CLICKHOUSE(
  host 'localhost'
  query 'SELECT toDate32(now())'
))
LAYOUT(COMPLEX_KEY_HASHED())
LIFETIME(0)
```

```
DB::Exception: Unknown type Date32 for dictionary attribute. (UNKNOWN_TYPE) (version 21.12.2.17 (official build))
```

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Dictionaries added `Date32` date type support. Closes #32913.

### CODE REVIEW

File: src/Dictionaries/DictionaryStructure.cpp [hunk 1]
```diff
@@ -38,11 +41,12 @@ DictionaryTypedSpecialAttribute makeDictionaryTypedSpecialAttribute(
     return DictionaryTypedSpecialAttribute{std::move(name), std::move(expression), DataTypeFactory::instance().get(type_name)};
 }
 
-std::optional<AttributeUnderlyingType> maybeGetAttributeUnderlyingType(TypeIndex index)
+std::optional<AttributeUnderlyingType> tryGetAttributeUnderlyingType(TypeIndex index)
 {
     switch (index) /// Special cases which do not map TypeIndex::T -> AttributeUnderlyingType::T
     {
         case TypeIndex::Date:       return AttributeUnderlyingType::UInt16;
+        case TypeIndex::Date32:     return AttributeUnderlyingType::UInt32;
```
Comment (Avogar) [inline src/Dictionaries/DictionaryStructure.cpp:49]: Internal type of `Date32` is `Int32`, not `UInt32`

File: src/Dictionaries/DictionaryStructure.cpp [hunk 2]
```diff
@@ -38,11 +41,12 @@ DictionaryTypedSpecialAttribute makeDictionaryTypedSpecialAttribute(
...
         case TypeIndex::DateTime:   return AttributeUnderlyingType::UInt32;
         case TypeIndex::DateTime64: return AttributeUnderlyingType::UInt64;
```
Comment (Avogar) [inline src/Dictionaries/DictionaryStructure.cpp:51]: `DateTime64` is implemented by `Int64`, should we use `Int64` here?

**Review by Avogar — APPROVED** [review]
