### PR TITLE
Fix crash during short circuit function evaluation

### LINKED ISSUE #35496: heap-buffer-overflow in MaskOperations
https://s3.amazonaws.com/clickhouse-test-reports/24258/9a505476a5c53dfbcc308139679fad5d47904b34/fuzzer_astfuzzerasan,actions//report.html

```
2022.03.22 00:50:00.054438 [ 208 ] {af2da264-7f7e-408a-a32b-09a3aceea34a} <Debug> executeQuery: (from [::ffff:127.0.0.1]:34518) SELECT 65536 AND 2147483647, throwIf((((1048575 AND throwIf((0. AND NULL) AND (((65536 AND 257) AND (1.1754943508222875e-38 AND 1024) AND -2147483649) AND NULL) AND (10 AND NULL)) AND (((65536 AND 257) AND (1.1754943508222875e-38 AND 1024) AND -1) AND NULL) AND 65535) AND -1) AND NULL) AND (NULL AND NULL), NULL < number) FROM numbers(1024)
2022.03.22 00:50:00.054823 [ 208 ] {af2da264-7f7e-408a-a32b-09a3aceea34a} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE ON *.*
2022.03.22 00:50:00.057259 [ 208 ] {af2da264-7f7e-408a-a32b-09a3aceea34a} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.03.22 00:50:01.440449 [ 455 ] {} <Fatal> BaseDaemon: (version 22.4.1.1, build id: E27D1D37997A9FB5) (from thread 431) (query_id: af2da264-7f7e-408a-a32b-09a3aceea34a) (query: SELECT 65536 AND 2147483647, throwIf((((1048575 AND throwIf((0. AND NULL) AND (((65536 AND 257) AND (1.1754943508222875e-38 AND 1024) AND -2147483649) AND NULL) AND (10 AND NULL)) AND (((65536 AND 257) AND (1.1754943508222875e-38 AND 1024) AND -1) AND NULL) AND 65535) AND -1) AND NULL) AND (NULL AND NULL), NULL < number) FROM numbers(1024)) Received signal Unknown signal (-3)



=================================================================
==106==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000f877e0 at pc 0x00002abc93b3 bp 0x7fd97f2ff8f0 sp 0x7fd97f2ff8e8
READ of size 1 at 0x603000f877e0 thread T222 (QueryPipelineEx)
    #0 0x2abc93b2 in unsigned long DB::extractMaskNumericImpl<false, true, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> >(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:104:29
    #1 0x2abc6655 in bool DB::extractMaskNumeric<false, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::MaskInfo&) obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:140:22
    #2 0x2abc6655 in DB::MaskInfo DB::extractMaskImpl<false>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:200:11
    #3 0x2abc627b in DB::MaskInfo DB::extractMaskImpl<false>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:195:16
    #4 0x14af1477 in DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeShortCircuit(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&) const (/workspace/clickhouse+0x14af1477)
    #5 0x14aeb284 in DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x14aeb284)
    #6 0x12218a8b in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x12218a8b)
    #7 0x277cfc82 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:216:15
    #8 0x277d0ba4 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:264:22
    #9 0x277d494e in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:334:16
    #10 0x28a98289 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:602:60
    #11 0x28a98289 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:719:13
    #12 0x2c7d35da in DB::ExpressionTransform::transform(DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #13 0x1fdaa8fd in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:37:9
    #14 0x2c2888d7 in DB::ISimpleTransform::work() obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89:9
    #15 0x2c2ea6e5 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:45:20
    #16 0x2c2ea6e5 in DB::ExecutionThreadContext::executeTask() obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:63:9
    #17 0x2c2cafc6 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:213:26
    #18 0x2c2c94ee in DB::PipelineExecutor::executeSingleThread(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:178:5
    #19 0x2c2c94ee in DB::PipelineExecutor::executeImpl(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:324:9
    #20 0x2c2c87af in DB::PipelineExecutor::execute(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:84:9
    #21 0x2c2f400c in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:78:24
    #22 0x2c2f400c in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105:13
    #23 0x2c2f400c in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #24 0x2c2f400c in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #25 0x2c2f400c in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #26 0x2c2f400c in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #27 0x2c2f400c in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #28 0x2c2f400c in void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:348:9
    #29 0x2c2f400c in std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()() obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608:12
    #30 0x2c2f400c in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089:16
    #31 0xbf8a106 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #32 0xbf8a106 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #33 0xbf8a106 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:277:17
    #34 0xbf92696 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:142:73
    #35 0xbf92696 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #36 0xbf92696 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #37 0xbf92696 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #38 0x7fdad75b4608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
    #39 0x7fdad74d9162 in __clone /build/glibc-sMfBJT/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x603000f877e0 is located 0 bytes to the right of 32-byte region [0x603000f877c0,0x603000f877e0)
allocated by thread T222 (QueryPipelineEx) here:
    #0 0xbd665dd in malloc (/workspace/clickhouse+0xbd665dd)
    #1 0xbeaa80a in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Common/Allocator.h:227:27
    #2 0x2a7a2681 in Allocator<false, false>::alloc(unsigned long, unsigned long) obj-x86_64-linux-gnu/../src/Common/Allocator.h:96:16
    #3 0x2a7a2681 in void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc<>(unsigned long) obj-x86_64-linux-gnu/../src/Common/PODArray.h:128:65
    #4 0x2a7a2681 in DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc_for_num_elements(unsigned long) obj-x86_64-linux-gnu/../src/Common/PODArray.h:122:9
    #5 0x2a7a2681 in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>::PODArray(unsigned long, char8_t const&) obj-x86_64-linux-gnu/../src/Common/PODArray.h:346:15
    #6 0x2a7a2681 in DB::ColumnVector<char8_t>::ColumnVector(unsigned long, char8_t) obj-x86_64-linux-gnu/../src/Columns/ColumnVector.h:132:55
    #7 0x2a7a2681 in COW<DB::IColumn>::mutable_ptr<DB::ColumnVector<char8_t> > COWHelper<DB::ColumnVectorHelper, DB::ColumnVector<char8_t> >::create<unsigned long, int>(unsigned long&&, int&&) obj-x86_64-linux-gnu/../src/Common/COW.h:284:71
    #8 0x2a7a2681 in DB::makeNullable(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) obj-x86_64-linux-gnu/../src/Columns/ColumnNullable.cpp:720:43
    #9 0x277ef4eb in DB::wrapInNullable(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) obj-x86_64-linux-gnu/../src/Functions/FunctionHelpers.cpp:293:16
    #10 0x277d032e in DB::IExecutableFunction::defaultImplementationForNulls(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:197:16
    #11 0x277cfb86 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:209:20
    #12 0x277d0ba4 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:264:22
    #13 0x277d494e in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:334:16
    #14 0x12217e36 in DB::IFunctionBase::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x12217e36)
    #15 0x2a72ed36 in DB::ColumnFunction::reduce() const obj-x86_64-linux-gnu/../src/Columns/ColumnFunction.cpp:269:28
    #16 0x2abba79c in DB::maskedExecute(DB::ColumnWithTypeAndName&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, DB::MaskInfo const&) obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:279:35
    #17 0x14af14ed in DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeShortCircuit(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&) const (/workspace/clickhouse+0x14af14ed)
    #18 0x14aeb284 in DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x14aeb284)
    #19 0x12218a8b in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x12218a8b)
    #20 0x277cfc82 in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:216:15
    #21 0x277d0ba4 in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:264:22
    #22 0x277d494e in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:334:16
    #23 0x28a98289 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:602:60
    #24 0x28a98289 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:719:13
    #25 0x2c7d35da in DB::ExpressionTransform::transform(DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #26 0x1fdaa8fd in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:37:9
    #27 0x2c2888d7 in DB::ISimpleTransform::work() obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89:9
    #28 0x2c2ea6e5 in DB::executeJob(DB::IProcessor*) obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:45:20
    #29 0x2c2ea6e5 in DB::ExecutionThreadContext::executeTask() obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:63:9
    #30 0x2c2cafc6 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:213:26
    #31 0x2c2c94ee in DB::PipelineExecutor::executeSingleThread(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:178:5
    #32 0x2c2c94ee in DB::PipelineExecutor::executeImpl(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:324:9
    #33 0x2c2c87af in DB::PipelineExecutor::execute(unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:84:9
    #34 0x2c2f400c in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:78:24
    #35 0x2c2f400c in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:105:13
    #36 0x2c2f400c in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682:1
    #37 0x2c2f400c in decltype(auto) std::__1::__apply_tuple_impl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415:1
    #38 0x2c2f400c in decltype(auto) std::__1::apply<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424:1
    #39 0x2c2f400c in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188:13
    #40 0x2c2f400c in decltype(std::__1::forward<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #41 0x2c2f400c in void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:348:9
    #42 0x2c2f400c in std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()() obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608:12
    #43 0x2c2f400c in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089:16
    #44 0xbf8a106 in std::__1::__function::__policy_func<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16
    #45 0xbf8a106 in std::__1::function<void ()>::operator()() const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12
    #46 0xbf8a106 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:277:17
    #47 0xbf92696 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:142:73
    #48 0xbf92696 in decltype(std::__1::forward<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1
    #49 0xbf92696 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:280:5
    #50 0xbf92696 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291:5
    #51 0x7fdad75b4608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8

Thread T222 (QueryPipelineEx) created by T3 (TCPHandler) here:
    #0 0xbd50c9c in pthread_create (/workspace/clickhouse+0xbd50c9c)
    #1 0xbf91676 in std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) obj-x86_64-linux-gnu/../contrib/libcxx/include/__threading_support:509:10
    #2 0xbf91676 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'(), void>(void&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:307:16
    #3 0xbf869d9 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:142:35
    #4 0xbf883fc in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:174:5
    #5 0x2c2f05cf in ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:169:38
    #6 0x2c2f05cf in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:108:24
    #7 0x2c2f195a in DB::PullingAsyncPipelineExecutor::pull(DB::Block&, unsigned long) obj-x86_64-linux-gnu/../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:145:10
    #8 0x2c1d81b3 in DB::TCPHandler::processOrdinaryQueryWithProcessors() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:679:25
    #9 0x2c1c7183 in DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:345:17
    #10 0x2c1eef9f in DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1767:9
    #11 0x2e95ab4e in Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x2e95b8c0 in Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #13 0x2ee2d205 in Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #14 0x2ee264b9 in Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #15 0x7fdad75b4608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8

Thread T3 (TCPHandler) created by T0 here:
    #0 0xbd50c9c in pthread_create (/workspace/clickhouse+0xbd50c9c)
    #1 0x2ee25769 in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6
    #2 0x2ee287fd in Poco::Thread::start(Poco::Runnable&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:128:2
    #3 0x2ee2dbf9 in Poco::PooledThread::start() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10
    #4 0x2ee2dbf9 in Poco::ThreadPool::ThreadPool(int, int, int, int) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:252:12
    #5 0xbdad938 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) obj-x86_64-linux-gnu/../programs/server/Server.cpp:572:22
    #6 0x2e9937da in Poco::Util::Application::run() obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:334:8
    #7 0xbda6c98 in DB::Server::run() obj-x86_64-linux-gnu/../programs/server/Server.cpp:452:25
    #8 0x2e9d6f5d in Poco::Util::ServerApplication::run(int, char**) obj-x86_64-linux-gnu/../contrib/poco/Util/src/ServerApplication.cpp:611:9
    #9 0xbda03fd in mainEntryClickHouseServer(int, char**) obj-x86_64-linux-gnu/../programs/server/Server.cpp:183:20
    #10 0xbd9bf88 in main obj-x86_64-linux-gnu/../programs/main.cpp:378:12
    #11 0x7fdad73de0b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:104:29 in unsigned long DB::extractMaskNumericImpl<false, true, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> >(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*)
Shadow bytes around the buggy address:
  0x0c06801e8ea0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06801e8eb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06801e8ec0: fa fa fa fa fa fa fa fa 00 00 00 00 fa fa fa fa
  0x0c06801e8ed0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06801e8ee0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c06801e8ef0: fa fa fd fd fd fa fa fa 00 00 00 00[fa]fa fa fa
  0x0c06801e8f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
--
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==106==ABORTING

```

### LINKED ISSUE #35497: Assertion in PODArray
https://github.com/ClickHouse/ClickHouse/blob/e7772ed434be81ab10b8eafab25f912a55170a5c/src/Common/PODArray.h#L384

https://s3.amazonaws.com/clickhouse-test-reports/24258/9a505476a5c53dfbcc308139679fad5d47904b34/fuzzer_astfuzzerdebug,actions//report.html

```
2022.03.22 00:41:24.991595 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> executeQuery: (from [::ffff:127.0.0.1]:59536) SELECT NULL AND throwIf((0 AND NULL) AND 2147483646 AND NULL AND NULL) AND -2147483649 AND (NULL AND NULL) AND NULL, 100 AND NULL, 65536 FROM (SELECT n FROM mt1 UNION ALL SELECT * FROM mt2)
2022.03.22 00:41:24.993596 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt1
2022.03.22 00:41:24.994944 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt2
2022.03.22 00:41:24.996835 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt1
2022.03.22 00:41:24.998145 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt2
2022.03.22 00:41:25.002895 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt1
2022.03.22 00:41:25.004411 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt2
2022.03.22 00:41:25.006780 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt1
2022.03.22 00:41:25.007665 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt1
2022.03.22 00:41:25.009901 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt2
2022.03.22 00:41:25.010754 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> ContextAccess (default): Access granted: SELECT(n) ON default.mt2
2022.03.22 00:41:25.011589 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.03.22 00:41:25.011973 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.03.22 00:41:25.012278 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.03.22 00:41:25.014141 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> default.mt1 (f8b70154-67c5-43a3-a6f8-336eaf275392) (SelectExecutor): Key condition: unknown
2022.03.22 00:41:25.014998 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> default.mt1 (f8b70154-67c5-43a3-a6f8-336eaf275392) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 3/3 marks by primary key, 3 marks to read from 3 ranges
2022.03.22 00:41:25.015612 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> default.mt1 (f8b70154-67c5-43a3-a6f8-336eaf275392) (SelectExecutor): Reading approx. 7 rows with 3 streams
2022.03.22 00:41:25.017050 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> default.mt2 (0d470b97-4ee2-4490-bec5-921e2fe50f55) (SelectExecutor): Key condition: unknown
2022.03.22 00:41:25.017906 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> default.mt2 (0d470b97-4ee2-4490-bec5-921e2fe50f55) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 3/3 marks by primary key, 3 marks to read from 3 ranges
2022.03.22 00:41:25.018535 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Debug> default.mt2 (0d470b97-4ee2-4490-bec5-921e2fe50f55) (SelectExecutor): Reading approx. 7 rows with 3 streams
2022.03.22 00:42:30.354059 [ 238 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Information> TCPHandler: Query was cancelled.
2022.03.22 00:42:30.369249 [ 490 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> PipelineExecutor: Thread finished. Total time: 65.343080468 sec. Execution time: 0.000818622 sec. Processing time: 0.000351645 sec. Wait time: 65.341910201 sec.
2022.03.22 00:42:30.369263 [ 485 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> PipelineExecutor: Thread finished. Total time: 65.343037692 sec. Execution time: 0.001147488 sec. Processing time: 0.000359656 sec. Wait time: 65.341530548 sec.
2022.03.22 00:42:30.369263 [ 487 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> PipelineExecutor: Thread finished. Total time: 65.343035357 sec. Execution time: 0.001152237 sec. Processing time: 0.000345994 sec. Wait time: 65.341537126 sec.
2022.03.22 00:42:30.369261 [ 468 ] {21bf3d59-81dc-404d-a9ff-8c2d25f0a97f} <Trace> PipelineExecutor: Thread finished. Total time: 65.343078142 sec. Execution time: 0.000803882 sec. Processing time: 0.000235471 sec. Wait time: 65.342038789 sec.

clickhouse-server: ../src/Common/PODArray.h:390: const T &DB::PODArray<char8_t, 4096, Allocator<false, false>, 15, 16>::operator[](ssize_t) const [T = char8_t, initial_bytes = 4096, TAllocator = Allocator<false, false>, pad_right_ = 15, pad_left_ = 16]: Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))' failed.
clickhouse-server: ../src/Common/PODArray.h:390: const T &DB::PODArray<char8_t, 4096, Allocator<false, false>, 15, 16>::operator[](ssize_t) const [T = char8_t, initial_bytes = 4096, TAllocator = Allocator<false, false>, pad_right_ = 15, pad_left_ = 16]: Assertion `(n >= (static_cast<ssize_t>(pad_left_) ? -1 : 0)) && (n <= static_cast<ssize_t>(this->size()))' failed.

2022.03.22 00:42:30.370272 [ 495 ] {} <Fatal> BaseDaemon: ########################################
2022.03.22 00:42:30.370129 [ 494 ] {} <Fatal> BaseDaemon: ########################################
2022.03.22 00:42:30.370747 [ 495 ] {} <Fatal> BaseDaemon: (version 22.4.1.1, build id: 659D69B74B66232A) (from thread 489) (query_id: 21bf3d59-81dc-404d-a9ff-8c2d25f0a97f) (query: SELECT NULL AND throwIf((0 AND NULL) AND 2147483646 AND NULL AND NULL) AND -2147483649 AND (NULL AND NULL) AND NULL, 100 AND NULL, 65536 FROM (SELECT n FROM mt1 UNION ALL SELECT * FROM mt2)) Received signal Aborted (6)
2022.03.22 00:42:30.370899 [ 494 ] {} <Fatal> BaseDaemon: (version 22.4.1.1, build id: 659D69B74B66232A) (from thread 486) (query_id: 21bf3d59-81dc-404d-a9ff-8c2d25f0a97f) (query: SELECT NULL AND throwIf((0 AND NULL) AND 2147483646 AND NULL AND NULL) AND -2147483649 AND (NULL AND NULL) AND NULL, 100 AND NULL, 65536 FROM (SELECT n FROM mt1 UNION ALL SELECT * FROM mt2)) Received signal Aborted (6)
2022.03.22 00:42:30.371099 [ 495 ] {} <Fatal> BaseDaemon: 
2022.03.22 00:42:30.371177 [ 494 ] {} <Fatal> BaseDaemon: 
2022.03.22 00:42:30.371416 [ 495 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f4030e5e03b 0x7f4030e3d859 0x7f4030e3d729 0x7f4030e4f006 0x144bb286 0x228f609d 0x228f5561 0x228f4ac2 0x228f4a82 0x228ef652 0x182c0816 0x182bf2f0 0x17585a4d 0x20e7fd8a 0x20e80895 0x20e81783 0x218fd2a6 0x218fc75c 0x23856924 0x1d883d22 0x2347b71e 0x234b8ab9 0x234b89b5 0x2349c6a1 0x2349c977 0x2349e122 0x2349e09d 0x2349e041 0x2349df52 0x2349de1b 0x2349dcdd 0x2349dc9d 0x2349dc75 0x2349dc40 0x14473f26 0x14470235 0x1451b3ef 0x14521f84 0x14521efd 0x14521e25 0x14521762
2022.03.22 00:42:30.371475 [ 494 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f4030e5e03b 0x7f4030e3d859 0x7f4030e3d729 0x7f4030e4f006 0x144bb286 0x228f609d 0x228f5561 0x228f4ac2 0x228f4a82 0x228ef652 0x182c0816 0x182bf2f0 0x17585a4d 0x20e7fd8a 0x20e80895 0x20e81783 0x218fd2a6 0x218fc75c 0x23856924 0x1d883d22 0x2347b71e 0x234b8ab9 0x234b89b5 0x2349c6a1 0x2349c977 0x2349e122 0x2349e09d 0x2349e041 0x2349df52 0x2349de1b 0x2349dcdd 0x2349dc9d 0x2349dc75 0x2349dc40 0x14473f26 0x14470235 0x1451b3ef 0x14521f84 0x14521efd 0x14521e25 0x14521762
2022.03.22 00:42:30.371801 [ 495 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7f4030e5e03b in ?
2022.03.22 00:42:30.371803 [ 494 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7f4030e5e03b in ?
2022.03.22 00:42:30.372068 [ 494 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f4030e3d859 in ?
2022.03.22 00:42:30.372215 [ 495 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f4030e3d859 in ?
2022.03.22 00:42:30.372512 [ 494 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f4030e3d729 in ?
2022.03.22 00:42:30.372628 [ 495 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f4030e3d729 in ?
2022.03.22 00:42:30.373056 [ 494 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f4030e4f006 in ?
2022.03.22 00:42:30.373127 [ 495 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f4030e4f006 in ?
2022.03.22 00:42:30.414846 [ 495 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Common/PODArray.h:0: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>::operator[](long) const @ 0x144bb286 in /workspace/clickhouse
2022.03.22 00:42:30.429640 [ 494 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../src/Common/PODArray.h:0: DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>::operator[](long) const @ 0x144bb286 in /workspace/clickhouse
2022.03.22 00:42:30.511712 [ 495 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:104: unsigned long DB::extractMaskNumericImpl<false, true, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> >(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) @ 0x228f609d in /workspace/clickhouse
2022.03.22 00:42:30.530601 [ 494 ] {} <Fatal> BaseDaemon: 9. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:104: unsigned long DB::extractMaskNumericImpl<false, true, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> >(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) @ 0x228f609d in /workspace/clickhouse
2022.03.22 00:42:30.607282 [ 495 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:140: bool DB::extractMaskNumeric<false, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::MaskInfo&) @ 0x228f5561 in /workspace/clickhouse
2022.03.22 00:42:30.624881 [ 494 ] {} <Fatal> BaseDaemon: 10. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:140: bool DB::extractMaskNumeric<false, char8_t>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::MaskInfo&) @ 0x228f5561 in /workspace/clickhouse
2022.03.22 00:42:30.702107 [ 495 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:200: DB::MaskInfo DB::extractMaskImpl<false>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) @ 0x228f4ac2 in /workspace/clickhouse
2022.03.22 00:42:30.718668 [ 494 ] {} <Fatal> BaseDaemon: 11. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:200: DB::MaskInfo DB::extractMaskImpl<false>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) @ 0x228f4ac2 in /workspace/clickhouse
2022.03.22 00:42:30.796775 [ 495 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:195: DB::MaskInfo DB::extractMaskImpl<false>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) @ 0x228f4a82 in /workspace/clickhouse
2022.03.22 00:42:30.812399 [ 494 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:195: DB::MaskInfo DB::extractMaskImpl<false>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, char8_t, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*) @ 0x228f4a82 in /workspace/clickhouse
2022.03.22 00:42:30.891601 [ 495 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:237: DB::extractMask(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*, char8_t) @ 0x228ef652 in /workspace/clickhouse
2022.03.22 00:42:30.906206 [ 494 ] {} <Fatal> BaseDaemon: 13. ./obj-x86_64-linux-gnu/../src/Columns/MaskOperations.cpp:237: DB::extractMask(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>*, char8_t) @ 0x228ef652 in /workspace/clickhouse
2022.03.22 00:42:31.121118 [ 495 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Functions/FunctionsLogical.cpp:583: DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeShortCircuit(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0x182c0816 in /workspace/clickhouse
2022.03.22 00:42:31.133572 [ 494 ] {} <Fatal> BaseDaemon: 14. ./obj-x86_64-linux-gnu/../src/Functions/FunctionsLogical.cpp:583: DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeShortCircuit(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >&, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0x182c0816 in /workspace/clickhouse
2022.03.22 00:42:31.349784 [ 495 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../src/Functions/FunctionsLogical.cpp:618: DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x182bf2f0 in /workspace/clickhouse
2022.03.22 00:42:31.359350 [ 494 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../src/Functions/FunctionsLogical.cpp:618: DB::FunctionsLogicalDetail::FunctionAnyArityLogical<DB::FunctionsLogicalDetail::AndImpl, DB::NameAnd>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x182bf2f0 in /workspace/clickhouse
2022.03.22 00:42:31.699586 [ 495 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Functions/IFunctionAdaptors.h:21: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x17585a4d in /workspace/clickhouse
2022.03.22 00:42:31.704491 [ 494 ] {} <Fatal> BaseDaemon: 16. ./obj-x86_64-linux-gnu/../src/Functions/IFunctionAdaptors.h:21: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x17585a4d in /workspace/clickhouse
2022.03.22 00:42:31.806897 [ 495 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:216: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x20e7fd8a in /workspace/clickhouse
2022.03.22 00:42:31.810167 [ 494 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:216: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x20e7fd8a in /workspace/clickhouse
2022.03.22 00:42:31.914753 [ 495 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:264: DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x20e80895 in /workspace/clickhouse
2022.03.22 00:42:31.916484 [ 494 ] {} <Fatal> BaseDaemon: 18. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:264: DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x20e80895 in /workspace/clickhouse
2022.03.22 00:42:32.023204 [ 495 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:334: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x20e81783 in /workspace/clickhouse
2022.03.22 00:42:32.023479 [ 494 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Functions/IFunction.cpp:334: DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x20e81783 in /workspace/clickhouse
2022.03.22 00:42:32.472924 [ 494 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:602: DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) @ 0x218fd2a6 in /workspace/clickhouse
2022.03.22 00:42:32.474153 [ 495 ] {} <Fatal> BaseDaemon: 20. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:602: DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool) @ 0x218fd2a6 in /workspace/clickhouse
2022.03.22 00:42:32.840036 [ 494 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:719: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x218fc75c in /workspace/clickhouse
2022.03.22 00:42:32.843200 [ 495 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionActions.cpp:719: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x218fc75c in /workspace/clickhouse
2022.03.22 00:42:32.949679 [ 494 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:23: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x23856924 in /workspace/clickhouse
2022.03.22 00:42:32.952860 [ 495 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../src/Processors/Transforms/ExpressionTransform.cpp:23: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x23856924 in /workspace/clickhouse
2022.03.22 00:42:33.094628 [ 494 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:38: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x1d883d22 in /workspace/clickhouse
2022.03.22 00:42:33.098349 [ 495 ] {} <Fatal> BaseDaemon: 23. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.h:38: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x1d883d22 in /workspace/clickhouse
2022.03.22 00:42:33.216784 [ 494 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x2347b71e in /workspace/clickhouse
2022.03.22 00:42:33.220884 [ 495 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../src/Processors/ISimpleTransform.cpp:89: DB::ISimpleTransform::work() @ 0x2347b71e in /workspace/clickhouse
2022.03.22 00:42:33.305076 [ 494 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:45: DB::executeJob(DB::IProcessor*) @ 0x234b8ab9 in /workspace/clickhouse
2022.03.22 00:42:33.309319 [ 495 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:45: DB::executeJob(DB::IProcessor*) @ 0x234b8ab9 in /workspace/clickhouse
2022.03.22 00:42:33.389285 [ 494 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:63: DB::ExecutionThreadContext::executeTask() @ 0x234b89b5 in /workspace/clickhouse
2022.03.22 00:42:33.393635 [ 495 ] {} <Fatal> BaseDaemon: 26. ./obj-x86_64-linux-gnu/../src/Processors/Executors/ExecutionThreadContext.cpp:63: DB::ExecutionThreadContext::executeTask() @ 0x234b89b5 in /workspace/clickhouse
2022.03.22 00:42:33.550559 [ 494 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:213: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2349c6a1 in /workspace/clickhouse
2022.03.22 00:42:33.557498 [ 495 ] {} <Fatal> BaseDaemon: 27. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:213: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x2349c6a1 in /workspace/clickhouse
2022.03.22 00:42:33.711615 [ 494 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:178: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x2349c977 in /workspace/clickhouse
2022.03.22 00:42:33.718705 [ 495 ] {} <Fatal> BaseDaemon: 28. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:178: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x2349c977 in /workspace/clickhouse
2022.03.22 00:42:33.885488 [ 494 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeImpl(unsigned long)::$_1::operator()() const @ 0x2349e122 in /workspace/clickhouse
2022.03.22 00:42:33.893149 [ 495 ] {} <Fatal> BaseDaemon: 29. ./obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeImpl(unsigned long)::$_1::operator()() const @ 0x2349e122 in /workspace/clickhouse
2022.03.22 00:42:34.064681 [ 494 ] {} <Fatal> BaseDaemon: 30. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&) @ 0x2349e09d in /workspace/clickhouse
2022.03.22 00:42:34.072809 [ 495 ] {} <Fatal> BaseDaemon: 30. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3682: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&) @ 0x2349e09d in /workspace/clickhouse
2022.03.22 00:42:34.243837 [ 494 ] {} <Fatal> BaseDaemon: 31. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415: decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) @ 0x2349e041 in /workspace/clickhouse
2022.03.22 00:42:34.252287 [ 495 ] {} <Fatal> BaseDaemon: 31. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1415: decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) @ 0x2349e041 in /workspace/clickhouse
2022.03.22 00:42:34.422932 [ 494 ] {} <Fatal> BaseDaemon: 32. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424: decltype(auto) std::__1::apply<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&) @ 0x2349df52 in /workspace/clickhouse
2022.03.22 00:42:34.431458 [ 495 ] {} <Fatal> BaseDaemon: 32. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/tuple:1424: decltype(auto) std::__1::apply<DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&, std::__1::tuple<>&) @ 0x2349df52 in /workspace/clickhouse
2022.03.22 00:42:34.576139 [ 494 ] {} <Fatal> BaseDaemon: 33. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()::operator()() @ 0x2349de1b in /workspace/clickhouse
2022.03.22 00:42:34.585267 [ 495 ] {} <Fatal> BaseDaemon: 33. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:188: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()::operator()() @ 0x2349de1b in /workspace/clickhouse
2022.03.22 00:42:34.754440 [ 494 ] {} <Fatal> BaseDaemon: 34. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) @ 0x2349dcdd in /workspace/clickhouse
2022.03.22 00:42:34.764325 [ 495 ] {} <Fatal> BaseDaemon: 34. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&) @ 0x2349dcdd in /workspace/clickhouse
2022.03.22 00:42:34.928283 [ 494 ] {} <Fatal> BaseDaemon: 35. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&...) @ 0x2349dc9d in /workspace/clickhouse
2022.03.22 00:42:34.938604 [ 495 ] {} <Fatal> BaseDaemon: 35. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:349: void std::__1::__invoke_void_return_wrapper<void>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'()&>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&...) @ 0x2349dc9d in /workspace/clickhouse
2022.03.22 00:42:35.102472 [ 494 ] {} <Fatal> BaseDaemon: 36. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'(), void ()>::operator()() @ 0x2349dc75 in /workspace/clickhouse
2022.03.22 00:42:35.112808 [ 495 ] {} <Fatal> BaseDaemon: 36. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608: std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'(), void ()>::operator()() @ 0x2349dc75 in /workspace/clickhouse
2022.03.22 00:42:35.275995 [ 494 ] {} <Fatal> BaseDaemon: 37. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x2349dc40 in /workspace/clickhouse
2022.03.22 00:42:35.287763 [ 495 ] {} <Fatal> BaseDaemon: 37. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_1>(DB::PipelineExecutor::executeImpl(unsigned long)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x2349dc40 in /workspace/clickhouse
2022.03.22 00:42:35.342704 [ 494 ] {} <Fatal> BaseDaemon: 38. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x14473f26 in /workspace/clickhouse
2022.03.22 00:42:35.354957 [ 495 ] {} <Fatal> BaseDaemon: 38. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221: std::__1::__function::__policy_func<void ()>::operator()() const @ 0x14473f26 in /workspace/clickhouse
2022.03.22 00:42:35.402184 [ 494 ] {} <Fatal> BaseDaemon: 39. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const @ 0x14470235 in /workspace/clickhouse
2022.03.22 00:42:35.414813 [ 495 ] {} <Fatal> BaseDaemon: 39. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560: std::__1::function<void ()>::operator()() const @ 0x14470235 in /workspace/clickhouse
2022.03.22 00:42:35.474378 [ 494 ] {} <Fatal> BaseDaemon: 40. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:277: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x1451b3ef in /workspace/clickhouse
2022.03.22 00:42:35.487665 [ 495 ] {} <Fatal> BaseDaemon: 40. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:277: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x1451b3ef in /workspace/clickhouse
2022.03.22 00:42:35.563475 [ 494 ] {} <Fatal> BaseDaemon: 41. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:142: void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const @ 0x14521f84 in /workspace/clickhouse
2022.03.22 00:42:35.577568 [ 495 ] {} <Fatal> BaseDaemon: 41. ./obj-x86_64-linux-gnu/../src/Common/ThreadPool.cpp:142: void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const @ 0x14521f84 in /workspace/clickhouse
2022.03.22 00:42:35.657654 [ 494 ] {} <Fatal> BaseDaemon: 42. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<void>(fp)(std::__1::forward<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(fp0)...)) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...) @ 0x14521efd in /workspace/clickhouse
2022.03.22 00:42:35.672771 [ 495 ] {} <Fatal> BaseDaemon: 42. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676: decltype(std::__1::forward<void>(fp)(std::__1::forward<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(fp0)...)) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...) @ 0x14521efd in /workspace/clickhouse
2022.03.22 00:42:35.751769 [ 494 ] {} <Fatal> BaseDaemon: 43. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:281: void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) @ 0x14521e25 in /workspace/clickhouse
2022.03.22 00:42:35.767832 [ 495 ] {} <Fatal> BaseDaemon: 43. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:281: void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) @ 0x14521e25 in /workspace/clickhouse
2022.03.22 00:42:35.845751 [ 494 ] {} <Fatal> BaseDaemon: 44. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x14521762 in /workspace/clickhouse
2022.03.22 00:42:35.862503 [ 495 ] {} <Fatal> BaseDaemon: 44. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/thread:291: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x14521762 in /workspace/clickhouse
2022.03.22 00:42:36.882145 [ 494 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 79203E6B0639D8B1A194B3FDF71A8DD0. There is no information about the reference checksum.
2022.03.22 00:42:36.903283 [ 495 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 79203E6B0639D8B1A194B3FDF71A8DD0. There is no information about the reference checksum.

```

### PR DESCRIPTION
**Pull request by kitaisreal**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash during short circuit function evaluation when one of arguments is nullable constant. Closes #35497. Closes #35496.

### CODE REVIEW

File: src/Columns/MaskOperations.cpp [hunk 1]
```diff
@@ -85,7 +85,11 @@ size_t extractMaskNumericImpl(
 {
     size_t ones_count = 0;
     size_t data_index = 0;
-    for (size_t i = 0; i != mask.size(); ++i)
+
+    size_t mask_size = mask.size();
+    size_t data_size = data.size();
+
+    for (size_t i = 0; i != mask_size && data_index != data_size; ++i)
```
Comment (kitaisreal) [inline src/Columns/MaskOperations.cpp:92]: @Avogar below there is condition
```c++
if constexpr (column_is_short)
{
    index = data_index;
    ++data_index;
}
    else
         index = i;
```
I am not familiar with this part of short circuit evaluation, should not we always increate `data_index`, because we always increase index like:
```c++
if (!mask[i])
{
    ++data_index;
    continue;
}
```

Comment (Avogar) [reply src/Columns/MaskOperations.cpp:92]: No, in case when we have `column_is_short=true` we expect that `data.size()` is equal to the number of ones in mask. And seems like this expectation could be wrong and it leads to crash. It means that the real bug is not here. Let's add your fix and add new check after the loop that `i == mask_size` and if it's not, throw logical error. I will try to find the real bug

Comment (kitaisreal) [reply src/Columns/MaskOperations.cpp:92]: Yes, bug already fixed in https://github.com/ClickHouse/ClickHouse/pull/35500, because it returned wrong constant this parts rely on this. No changes required.

**Comment by Avogar** [comment]
Maybe worth adding throwing logical error in case of possible overflow in extractMaskNumericImpl?  In case of external bug it would be better to get an exception here other than crash

**Review by Avogar — APPROVED** [review]

**Comment by kitaisreal** [comment]
@Avogar not sure if assertion can be easily added in hot loop, not sure if it worth it.
