### PR TITLE
Fix parseDateTimeBestEffort incorrectly parsing words starting with month prefixes in DD-month-YYYY format

### LINKED ISSUE #99345: parseDateTimeBestEffort accepts invalid words as month names in DD-Month-YYYY format
### Describe what's wrong

parseDateTimeBestEffort accepts invalid words as month names in DD-Month-YYYY format

### Does it reproduce on the most recent release?

Yes

### How to reproduce

SELECT parseDateTimeBestEffort('1-Married-2025');
2025-03-01 00:00:00

Fiddle: https://fiddle.clickhouse.com/ede15f2d-3cf7-4bd4-a9f1-53e5cfc996d1

### Expected behavior

Exception: CANNOT_PARSE_DATETIME

### Additional context

In `src/IO/parseDateTimeBestEffort.cpp`, the DD-Month-YYYY path reads up to 9 alphabetical characters but validates only the first 3 via strncasecmp. Any word whose first 3 letters match a month abbreviation is silently accepted as that month.

PR #98742 fixed this for the standalone-word path but missed this code path.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix parseDateTimeBestEffort incorrectly parsing words starting with month prefixes in DD-month-YYYY format. Closes https://github.com/ClickHouse/ClickHouse/issues/99345#event-23517658314

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

---

> [!NOTE]
> **Medium Risk**
> Changes core DateTime parsing behavior to be stricter about alphabetic month tokens, which could cause previously-accepted (but incorrect) inputs to start failing in some formats.
> 
> **Overview**
> Fixes `parseDateTimeBestEffort` incorrectly accepting arbitrary words that start with a 3-letter month prefix in `DD-month-YYYY` inputs (e.g. `1-Married-2025`).
> 
> Adds a shared validator for full month/weekday names and uses it to ensure alphabetic date parts either match a known full name or are exactly a 3-letter abbreviation, rejecting extra trailing letters. Updates stateless tests to cover the new invalid/valid `DD-month-YYYY` cases and expected `NULL`/errors.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 7e4c99d312b5ff7964aac8d8c2ba05f4a6d63415. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.4.1.200`

### CODE REVIEW

File: src/IO/parseDateTimeBestEffort.cpp [hunk 1]
```diff
@@ -150,6 +150,30 @@ ReturnType parseDateTimeBestEffortImpl(
         return true;
     };
 
+    /// Validate that a word is a known full month or weekday name (not just a prefix match).
+    /// For example, "March" is valid but "Married" is not, even though both start with "Mar".
+    auto is_valid_month_or_weekday_name = [] (const char * word, size_t len)
+    {
+        return (len == 7 && 0 == strncasecmp(word, "January", 7))
```
Comment (Ergus) [inline src/IO/parseDateTimeBestEffort.cpp:157]: Just a comment, Isn't this simpler with a `switch (len)`?

**Review by Ergus — APPROVED** [review]
LGTM

File: src/IO/parseDateTimeBestEffort.cpp (hunk 1 above)
Comment (Avogar) [reply src/IO/parseDateTimeBestEffort.cpp:157]: We have repeated len for some months/days. It will look bulky. Also there is a similar code used in this file in read_alpha_month, so I decided to keep it similar.
