### PR TITLE
Respect max_block_size for array join to avoid possible OOM

### LINKED ISSUE #54290: Respect settings: max_block_size for arrayJoin function
**Describe the unexpected behaviour**
Currently in CH, arrayJoin action always processes one input chunk and does transforming, finally output another one chunk. The output chunk is probably huge if serveral arrayJoins are calculated continuously in SQL, which is not friendly for memory limited usages(e.g. gluten)

To avoid OOM, we should respect `max_block_size` settings while executing arrayJoin

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Respect max_block_size for array join to avoid possible OOM. Close https://github.com/ClickHouse/ClickHouse/issues/54290

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 7c773f32ed415dbc03fcf2fa6f9a8427575eba75 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/54664/7c773f32ed415dbc03fcf2fa6f9a8427575eba75/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>✅ success</td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>⏳ pending</td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
Let's add a test.

**Comment by alexey-milovidov** [comment]
Thank you! I wanted this feature for a very long time :tada:

**Comment by taiyang-li** [comment]
``` sql 
 :) set max_block_size = 10;

SET max_block_size = 10

Query id: a82913e9-bd2d-41c4-99de-70f16f1d7f6b

Ok.

0 rows in set. Elapsed: 0.001 sec. 

 :) SELECT n % 10, count(1) from (SELECT range(0, number) as x FROM numbers(10000)) LEFT ARRAY JOIN x as n group by n % 10;

SELECT
    n % 10,
    count(1)
FROM
(
    SELECT range(0, number) AS x
    FROM numbers(10000)
)
LEFT ARRAY JOIN x AS n
GROUP BY n % 10

Query id: 72db26cd-1a66-46ad-9e53-4334cbf321ee

┌─modulo(n, 10)─┬─count()─┐
│             0 │ 5004001 │
│             1 │ 5003000 │
│             2 │ 5002000 │
│             3 │ 5001000 │
│             4 │ 5000000 │
│             5 │ 4999000 │
│             6 │ 4998000 │
│             7 │ 4997000 │
│             8 │ 4996000 │
│             9 │ 4995000 │
└───────────────┴─────────┘

10 rows in set. Elapsed: 0.372 sec. Processed 10.00 thousand rows, 80.00 KB (26.86 thousand rows/s., 214.86 KB/s.)
Peak memory usage: 8.61 MiB.

 :) set max_block_size = 100000;

SET max_block_size = 100000

Query id: b4081541-2fde-47ac-983d-980d45d9a850

Ok.

0 rows in set. Elapsed: 0.001 sec. 

 :) SELECT n % 10, count(1) from (SELECT range(0, number) as x FROM numbers(10000)) LEFT ARRAY JOIN x as n group by n % 10;

SELECT
    n % 10,
    count(1)
FROM
(
    SELECT range(0, number) AS x
    FROM numbers(10000)
)
LEFT ARRAY JOIN x AS n
GROUP BY n % 10

Query id: 6fdae9a2-680f-4b67-a170-4ac00934bb49

┌─modulo(n, 10)─┬─count()─┐
│             0 │ 5004001 │
│             1 │ 5003000 │
│             2 │ 5002000 │
│             3 │ 5001000 │
│             4 │ 5000000 │
│             5 │ 4999000 │
│             6 │ 4998000 │
│             7 │ 4997000 │
│             8 │ 4996000 │
│             9 │ 4995000 │
└───────────────┴─────────┘

10 rows in set. Elapsed: 0.689 sec. Processed 10.00 thousand rows, 80.00 KB (14.51 thousand rows/s., 116.05 KB/s.)
Peak memory usage: 898.64 MiB.
```

**Comment by taiyang-li** [comment]
> Let's add a test.

done

**Comment by taiyang-li** [comment]
Hope for your reviews @alexey-milovidov

File: tests/queries/0_stateless/02865_array_join_with_max_block_size.sql [hunk 1]
```diff
@@ -0,0 +1,16 @@
+-- { echoOn }
```
Comment (nickitat) [inline tests/queries/0_stateless/02865_array_join_with_max_block_size.sql:1]: let's add a test on block size itself
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02355_control_block_size_in_aggregator.sql

File: src/Processors/Transforms/ArrayJoinTransform.cpp [hunk 2]
```diff
@@ -1,32 +1,55 @@
...
+}
+
 Block ArrayJoinTransform::transformHeader(Block header, const ArrayJoinActionPtr & array_join)
 {
-    array_join->execute(header);
-    return header;
+    auto columns = header.getColumnsWithTypeAndName();
+    array_join->prepare(columns);
+    Block res{std::move(columns)};
+    res.setColumns(res.mutateColumns());
```
Comment (nickitat) [inline src/Processors/Transforms/ArrayJoinTransform.cpp:18]: why `res.setColumns(res.mutateColumns());` is needed?

Comment (taiyang-li) [reply src/Processors/Transforms/ArrayJoinTransform.cpp:18]: Make column not null, otherwise uts like tests/queries/0_stateless/00041_big_array_join.sql would failed

**Review by nickitat — APPROVED** [review]

File: tests/queries/0_stateless/02355_control_block_size_in_array_join.sql [hunk 3]
```diff
@@ -0,0 +1,13 @@
+SET max_block_size = 8192;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02355_control_block_size_in_array_join.sql:1]: This test passed on 23.7

File: tests/queries/0_stateless/02865_array_join_with_max_block_size.sql [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+set max_block_size = 10, enable_unaligned_array_join = true;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02865_array_join_with_max_block_size.sql:2]: This test also passed on 23.7

**Comment by alexey-milovidov** [comment]
@nickitat I didn't find any difference after this feature, and the tests have passed on previous ClickHouse versions.
