### PR TITLE
Fix premature TTL column removal causing merge failures and wrong defaults

### LINKED ISSUE #88002: Exception: Not found column Timestamp in block during merge on GraphiteMergeTree/ReplicatedGraphiteMergeTree  Table
### Company or project name

_No response_

### Describe the unexpected behaviour

After upgrading from v25.3 to v25.8 MERGE_PARTS operations started to fail. This seems to only fail for "old" data where the Timestamp column's TTL value  has been exceeded(see schema in the how to reproduce section) 

### Which ClickHouse versions are affected?

v25.7, v25.8, v25.10
I haven't tried v25.9 
v25.6 is unaffected

### How to reproduce

Use clickhouse v25.8

1. I used the schema below

```sql
CREATE DATABASE graphite; 
CREATE TABLE IF NOT EXISTS graphite.graphite_tmp (
  Path String CODEC(ZSTD(3)),
  Value Float64 CODEC(Gorilla, LZ4),
  Time UInt32 CODEC(DoubleDelta, LZ4),
  Date Date CODEC(DoubleDelta, LZ4),
  Timestamp UInt32 CODEC(DoubleDelta, LZ4) TTL Date + INTERVAL 1 DAY
) ENGINE = GraphiteMergeTree('graphite_rollup')
PARTITION BY toYYYYMM(Date)
ORDER BY (Path, Time)
TTL Date + INTERVAL 1 YEAR;
```
For configuration I am using defaults. Happy to dump it out if necessary. 

2. I then inserted data in the 202503 partition (I had data from another table here)

```sql
INSERT INTO graphite.graphite_tmp (Date, Time, Path, Value, Timestamp)
SELECT
    toDate('2025-03-01') AS Date,
    toDateTime('2025-03-01 00:00:00') + number * 30 AS Time,
    concat('servers.', toString(intDiv(number, 1000)), '.', arrayElement(['cpu.load','mem.used','disk.io'], (number % 3) + 1)) AS Path,
    50 + 10 * sin(number / 200) + rand() % 5 AS Value, 
    1 AS Version
FROM numbers(1000000000);
```
3. Watch the log once the MERGE_PARTS operations starts you'll see the stacktrace. 

### Expected behavior

On versions before v25.7 the merge would succeed without any issue. 

### Error message and/or stacktrace

Below are stack traces I got on both ReplicatedGraphiteMergeTree and GraphiteMergeTree

**ReplicatedGraphiteMergeTree**
```
Code: 10. DB::Exception: Not found column Timestamp in block. There are only columns: Path, Time, Value, Date. (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000133ab85f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c8569ce
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c856480
3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000d85812b
4. DB::Block::getPositionByName(String const&, bool) const @ 0x0000000016a8ab24
5. DB::GraphiteRollupSortedAlgorithm::GraphiteRollupSortedAlgorithm(std::shared_ptr<DB::Block const>, unsigned long, DB::SortDescription, unsigned long, unsigned long, DB::Graphite::Params, long) @ 0x0000000019edf512
6. DB::IMergingTransform<DB::GraphiteRollupSortedAlgorithm>::IMergingTransform<std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription, unsigned long&, unsigned long&, DB::Graphite::Params, long&>(unsigned long, std::shared_ptr<DB::Block const>, std::shared_ptr<DB::Block const>, bool, unsigned long, bool, std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription&&, unsigned long&, unsigned long&, DB::Graphite::Params&&, long&) @ 0x0000000019141ad1
7. DB::MergePartsStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x00000000191355f0
8. DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x0000000019fd0ed7
9. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001a009d19
10. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() const @ 0x0000000019119be5
11. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x0000000019112212
12. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x000000001911c10e
13. DB::MergeTask::execute() @ 0x000000001912ad22
14. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000019543720
15. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001915d4ef
16. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000001350976b
17. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013510ae6
18. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013506752
19. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001350e21a
20. ? @ 0x0000000000094ac3
21. ? @ 0x0000000000125a04
 (version 25.8.7.3 (official build))
```

**GraphiteMergeTree**

```
2025.10.02 02:29:31.078701 [ 657 ] {de8941c8-dc65-4a01-89d9-54d9618aaa18::202503_26_85_4} <Error> virtual bool DB::MergePlainMergeTreeTask::executeStep(): Exception is in merge_task.: Code: 10. DB::Exception: Not found column Timestamp in block. There are only columns: Path, Time, Value, Date. (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000133ab85f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c8569ce
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c856480
3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000d85812b
4. DB::Block::getPositionByName(String const&, bool) const @ 0x0000000016a8ab24
5. DB::GraphiteRollupSortedAlgorithm::GraphiteRollupSortedAlgorithm(std::shared_ptr<DB::Block const>, unsigned long, DB::SortDescription, unsigned long, unsigned long, DB::Graphite::Params, long) @ 0x0000000019edf512
6. DB::IMergingTransform<DB::GraphiteRollupSortedAlgorithm>::IMergingTransform<std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription, unsigned long&, unsigned long&, DB::Graphite::Params, long&>(unsigned long, std::shared_ptr<DB::Block const>, std::shared_ptr<DB::Block const>, bool, unsigned long, bool, std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription&&, unsigned long&, unsigned long&, DB::Graphite::Params&&, long&) @ 0x0000000019141ad1
7. DB::MergePartsStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x00000000191355f0
8. DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x0000000019fd0ed7
9. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001a009d19
10. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() const @ 0x0000000019119be5
11. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x0000000019112212
12. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x000000001911c10e
13. DB::MergeTask::execute() @ 0x000000001912ad22
14. DB::MergePlainMergeTreeTask::executeStep() @ 0x00000000191ad73f
15. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001915d4ef
16. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000001350976b
17. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013510ae6
18. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013506752
19. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001350e21a
20. ? @ 0x0000000000094ac3
21. ? @ 0x0000000000125a04
 (version 25.8.7.3 (official build))
2025.10.02 02:29:31.078817 [ 657 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {de8941c8-dc65-4a01-89d9-54d9618aaa18::202503_26_85_4}: Code: 10. DB::Exception: Not found column Timestamp in block. There are only columns: Path, Time, Value, Date. (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000133ab85f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000c8569ce
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000c856480
3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000d85812b
4. DB::Block::getPositionByName(String const&, bool) const @ 0x0000000016a8ab24
5. DB::GraphiteRollupSortedAlgorithm::GraphiteRollupSortedAlgorithm(std::shared_ptr<DB::Block const>, unsigned long, DB::SortDescription, unsigned long, unsigned long, DB::Graphite::Params, long) @ 0x0000000019edf512
6. DB::IMergingTransform<DB::GraphiteRollupSortedAlgorithm>::IMergingTransform<std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription, unsigned long&, unsigned long&, DB::Graphite::Params, long&>(unsigned long, std::shared_ptr<DB::Block const>, std::shared_ptr<DB::Block const>, bool, unsigned long, bool, std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription&&, unsigned long&, unsigned long&, DB::Graphite::Params&&, long&) @ 0x0000000019141ad1
7. DB::MergePartsStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x00000000191355f0
8. DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x0000000019fd0ed7
9. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001a009d19
10. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() const @ 0x0000000019119be5
11. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x0000000019112212
12. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x000000001911c10e
13. DB::MergeTask::execute() @ 0x000000001912ad22
14. DB::MergePlainMergeTreeTask::executeStep() @ 0x00000000191ad73f
15. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001915d4ef
16. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x000000001350976b
17. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013510ae6
18. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000013506752
19. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001350e21a
20. ? @ 0x0000000000094ac3
21. ? @ 0x0000000000125a04
 (version 25.8.7.3 (official build))
```

### Additional context

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed several issues caused by premature column removal in TTL. Resolves #88002

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Details

1. Fix merge failures in GraphiteMergeTree, VersionedCollapsingMergeTree, ReplacingMergeTree, and AggregatingMergeTree when TTL-removed columns were still required by merge logic
2. Fix incorrect skip index or data values caused by filling missing columns with type defaults instead of column DEFAULT expressions
3. Fix missing OPTIMIZE ... DEDUPLICATE BY behavior when deduplication columns were removed by TTL

### CODE REVIEW

**Review by jkartseva — APPROVED** [review]
Looks good. Could you please add a test for one of the engines mentioned in the changelog?
> Merge failures in GraphiteMergeTree, VersionedCollapsingMergeTree, ReplacingMergeTree, and AggregatingMergeTree when TTL-removed columns were still required by merge logic.

**Comment by amosbird** [comment]
> Looks good. Could you please add a test for one of the engines mentioned in the changelog?

Sure. I've added more tests and fixed more issues.

**Comment by Felixoid** [comment]
Thanks for the PR!

Looks like the tests has failed, unfortunately =\

**Comment by amosbird** [comment]
> Looks like the tests has failed, unfortunately =\

It should be fine now.

**Comment by Felixoid** [comment]
I wrote a test, unfortunately, it fails as following:

```
=================================== FAILURES ===================================
_______________________________ test_ttl_version _______________________________
[gw0] linux -- Python 3.10.12 /usr/bin/python3
test_graphite_merge_tree/test.py:534: in test_ttl_version
    q("OPTIMIZE TABLE test.graphite PARTITION 200109 FINAL")
helpers/cluster.py:4255: in query
    return self.client.query(
helpers/client.py:39: in wrap
    return func(self, *args, **kwargs)
helpers/client.py:79: in query
    ).get_answer()
helpers/client.py:247: in get_answer
    raise QueryRuntimeException(
E   helpers.client.QueryRuntimeException: Client failed! Return code: 10, stderr: Received exception from server (version 25.11.1):
E   Code: 10. DB::Exception: Received from 172.16.1.2:9000. DB::Exception: Not found column updated in block. There are only columns: metric, timestamp, value, date. Stack trace:
E
E   0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013eab75f
E   1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cb63fce
E   2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cb63a80
E   3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000dc115ab
E   4. DB::Block::getPositionByName(String const&, bool) const @ 0x0000000017681de4
E   5. DB::GraphiteRollupSortedAlgorithm::GraphiteRollupSortedAlgorithm(std::shared_ptr<DB::Block const>, unsigned long, DB::SortDescription, unsigned long, unsigned long, std::optional<unsigned long>, DB::Graphite::Params, long) @ 0x000000001ac60ef6
E   6. DB::IMergingTransform<DB::GraphiteRollupSortedAlgorithm>::IMergingTransform<std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription, unsigned long&, unsigned long&, std::optional<unsigned long>&, DB::Graphite::Params, long&>(unsigned long, std::shared_ptr<DB::Block const>, std::shared_ptr<DB::Block const>, bool, unsigned long, bool, std::shared_ptr<DB::Block const>&, unsigned long&, DB::SortDescription&&, unsigned long&, unsigned long&, std::optional<unsigned long>&, DB::Graphite::Params&&, long&) @ 0x0000000019e82d83
E   7. DB::MergePartsStep::transformPipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x0000000019e762c6
E   8. DB::ITransformingStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000001ad51f57
E   9. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001ad96d80
E   10. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() const @ 0x0000000019e6020d
E   11. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x0000000019e58ec1
E   12. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x0000000019e6234e
E   13. DB::MergeTask::execute() @ 0x0000000019e6bd62
E   14. DB::MergePlainMergeTreeTask::executeStep() @ 0x0000000019e4a0bf
E   15. DB::StorageMergeTree::merge(bool, String const&, bool, bool, std::vector<String, std::allocator<String>> const&, bool, std::shared_ptr<DB::MergeTreeTransaction> const&, PreformattedMessage&, bool) @ 0x0000000019812b46
E   16. DB::StorageMergeTree::optimize(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::IAST> const&, bool, bool, std::vector<String, std::allocator<String>> const&, bool, std::shared_ptr<DB::Context const>) @ 0x000000001981cfd1
E   17. DB::InterpreterOptimizeQuery::execute() @ 0x000000001904fbf7
E   18. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>) @ 0x0000000018fd0304
E   19. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000018fca133
E   20. DB::TCPHandler::runImpl() @ 0x000000001a77a8b7
E   21. DB::TCPHandler::run() @ 0x000000001a79ce99
E   22. Poco::Net::TCPServerConnection::start() @ 0x000000001f86f407
E   23. Poco::Net::TCPServerDispatcher::run() @ 0x000000001f86f899
E   24. Poco::PooledThread::run() @ 0x000000001f836047
E   25. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001f834441
E   26. ? @ 0x0000000000094ac3
E   27. ? @ 0x00000000001268c0
E   . (NOT_FOUND_COLUMN_IN_BLOCK)
E   (query: OPTIMIZE TABLE test.graphite PARTITION 200109 FINAL)
```

You can launch it locally as `python -m ci.praktika run integration --test test_graphite_merge_tree/test.py::test_ttl_version` from the repo root, the `clickhouse` binary could be placed in `ci/tmp`

**Comment by amosbird** [comment]
> I wrote a test, unfortunately, it fails as following:

Thanks! The test passes now.

**Comment by amosbird** [comment]
I've updated the PR to address https://github.com/ClickHouse/ClickHouse/pull/37570 in a more general way, which also satisfies the second requirement of #4968.

**Comment by amosbird** [comment]
Now it exposes additional issues: dependencies in default expressions are not handled correctly during column TTL. I’ll work on a proper fix.

**Comment by amosbird** [comment]
Handling missing columns that have default expressions is non-trivial and currently unresolved (see https://github.com/ClickHouse/ClickHouse/issues/91127). For now, we conservatively avoid expiring such columns.

PR is ready. @jkartseva @Felixoid Could you help take another look?

File: tests/queries/0_stateless/03221_merge_profile_events.reference [hunk 1]
```diff
@@ -1,3 +1,3 @@
 Horizontal	1	20000	3	0	480000	1	1	1	1	1	1
 Vertical	1	20000	1	2	480000	1	1	1	1	1	1	1	1
-Vertical	2	400000	2	6	12800000	1	1	1	1	1	1	1	1	1	1	1	1
+Vertical	2	400000	2	3	8000000	1	1	1	1	1	1	1	1	1	1	1	1
```
Comment (amosbird) [inline tests/queries/0_stateless/03221_merge_profile_events.reference:3]: This reveals an underlying issue in projections. The reference file itself is updated correctly, and the problem will also be addressed by the fix in #91352.

File: tests/queries/0_stateless/00443_optimize_final_vertical_merge.reference [hunk 2]
```diff
@@ -1,3 +1,3 @@
 150000	150000	150000	150000	150000	150000
-[['def']]	[['','']]
+[['def']]	[['zzz']]
```
Comment (amosbird) [inline tests/queries/0_stateless/00443_optimize_final_vertical_merge.reference:2]: This is still undefined behavior, and it’s unclear what the value should be. The tricky part is described in https://github.com/ClickHouse/ClickHouse/issues/4968#issuecomment-3600273169
. I believe the updated answer reflects the most reasonable interpretation.

**Comment by jkartseva** [comment]
Thank you, will take a look in the morning.

File: src/Processors/Transforms/TTLTransform.cpp [hunk 3]
```diff
@@ -71,32 +91,50 @@ TTLTransform::TTLTransform(
...
+            return Result{};
+        const auto & column = storage_columns.get(name);
+        auto default_ast = it->second.expression->clone();
+        default_ast = addTypeConversionToAST(std::move(default_ast), column.type->getName());
+        auto syntax_result = TreeRewriter(storage_.getContext()).analyze(default_ast, storage_columns.getAll());
+        auto actions = ExpressionAnalyzer{default_ast, syntax_result, storage_.getContext()}.getActions(true);
+        return Result{actions, default_ast->getColumnName()};
+    };
+
+    auto expired_columns_map = expired_columns.getNameToTypeMap();
```
Comment (jkartseva) [inline src/Processors/Transforms/TTLTransform.cpp]: nit: can be moved inside `metadata_snapshot_->hasAnyColumnTTL()` block

File: src/Storages/MergeTree/MergeTask.cpp [hunk 4]
```diff
@@ -526,8 +556,34 @@ bool MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const
...
+            bool is_expired = expired_columns.contains(column.name);
+            bool is_required_for_merge = global_ctx->merge_required_key_columns.contains(column.name);
+
+            if (is_expired)
+                global_ctx->storage_columns_expired_by_ttl.push_back(column);
+
+            if (!is_expired || is_required_for_merge)
+                storage_columns.push_back(column);
+        }
+        global_ctx->storage_columns = std::move(storage_columns);
```
Comment (jkartseva) [inline src/Storages/MergeTree/MergeTask.cpp]: Shared logic can be extracted into a lambda:
```
global_ctx->merging_columns = filter_columns(global_ctx->merging_columns, global_ctx->merging_columns_expired_by_ttl);
global_ctx->storage_columns = filter_columns(global_ctx->storage_columns, global_ctx->storage_columns_expired_by_ttl);
```

File: src/Processors/Transforms/TTLTransform.cpp [hunk 5]
```diff
@@ -131,6 +169,25 @@ void TTLTransform::consume(Chunk chunk)
...
 
+    /// Fill expired columns with default values which will later be handled in TTLColumnAlgorithm
+    for (const auto & [column, data] : expired_columns_data)
+    {
+        auto default_column
+            = ITTLAlgorithm::executeExpressionAndGetColumn(data.default_expression, block, data.default_column_name);
+        if (default_column)
+            default_column = default_column->convertToFullColumnIfConst();
+        else
+            default_column = data.type->createColumnConstWithDefaultValue(block.rows())->convertToFullColumnIfConst();
```
Comment (jkartseva) [inline src/Processors/Transforms/TTLTransform.cpp:179]: Do I assume correctly that the case of `data.default_expression == nullptr` is handled here?

**Review by jkartseva — APPROVED** [review]
Looks good from my side, @Felixoid would you mind giving this PR another look?

File: src/Processors/Transforms/TTLTransform.cpp (hunk 5 above)
Comment (amosbird) [reply src/Processors/Transforms/TTLTransform.cpp:179]: Yes. It's inside `executeExpressionAndGetColumn` which returns `nullptr`.

**Comment by Felixoid** [comment]
I can only approve that the original issue that we found in https://github.com/ClickHouse/ClickHouse/issues/88002 is addressed, since my tests are OK :+1:

**Comment by amosbird** [comment]
> CH Inc sync -  tests failed

@jkartseva It looks like some tests in the private repo are failing. This might be related to the behavioral change introduced in this PR, which is also reflected in the updated test reference files.

**Comment by jkartseva** [comment]
I don't see that the failure in private is related to this PR, it looks like an error in our CI infra. Asking around..

**Comment by amosbird** [comment]
> I don't see that the failure in private is related to this PR, it looks like an error in our CI infra. Asking around..

@jkartseva I’ve resolved the merge conflict, but it still shows the same private-repo failure. Could you please take another look?

**Comment by jkartseva** [comment]
@amosbird Private had merge conflicts with https://github.com/ClickHouse/ClickHouse/pull/91569, I resolved as following:
```
diff --cc src/Storages/MergeTree/MergeTask.cpp
index c2253639fc1,a0fb92a411f..b4a6c1e8f5d
--- a/src/Storages/MergeTree/MergeTask.cpp
+++ b/src/Storages/MergeTree/MergeTask.cpp
@@@ -292,29 -292,17 +292,26 @@@ void MergeTask::ExecuteAndFinalizeHoriz
              key_columns.insert(String(Nested::getColumnFromSubcolumn(name, storage_columns)));
      }

-     /// Force sign column for Collapsing mode
-     if (global_ctx->merging_params.mode == MergeTreeData::MergingParams::Collapsing)
+     /// Force sign column for Collapsing mode and VersionedCollapsing mode
+     if (!global_ctx->merging_params.sign_column.empty())
          key_columns.emplace(global_ctx->merging_params.sign_column);

-     /// Force version column for Replacing mode
-     if (global_ctx->merging_params.mode == MergeTreeData::MergingParams::Replacing)
-     {
+     /// Force is_deleted column for Replacing mode
+     if (!global_ctx->merging_params.is_deleted_column.empty())
          key_columns.emplace(global_ctx->merging_params.is_deleted_column);
-         key_columns.emplace(global_ctx->merging_params.version_column);
-     }

 +    /// Force all columns params of Graphite mode.
 +    if (global_ctx->merging_params.mode == MergeTreeData::MergingParams::Graphite)
 +    {
 +        key_columns.emplace(global_ctx->merging_params.graphite_params.path_column_name);
 +        key_columns.emplace(global_ctx->merging_params.graphite_params.time_column_name);
 +        key_columns.emplace(global_ctx->merging_params.graphite_params.value_column_name);
 +        key_columns.emplace(global_ctx->merging_params.graphite_params.version_column_name);
 +    }
 +
-     /// Force sign column for VersionedCollapsing mode. Version is already in primary key.
-     if (global_ctx->merging_params.mode == MergeTreeData::MergingParams::VersionedCollapsing)
-         key_columns.emplace(global_ctx->merging_params.sign_column);
+     /// Force version column for Replacing mode and VersionedCollapsing mode
+     if (!global_ctx->merging_params.version_column.empty())
+         key_columns.emplace(global_ctx->merging_params.version_column);

      /// Force to merge at least one column in case of empty key
      if (key_columns.empty())
```

**Comment by jkartseva** [comment]
Also, sync did not went through for your last two commits.

**Comment by jkartseva** [comment]
I manually resolved the conflicts; the sync went through.

**Comment by jkartseva** [comment]
And now arm_tidy build is failing in private, but it's not related to this PR

**Comment by amosbird** [comment]
> And now arm_tidy build is failing in private, but it's not related to this PR

Cool. Is there any other blocker to merge this?

**Comment by jkartseva** [comment]
The test `test_graphite_merge_tree` is in the skip list in private repository, which is why the asan_flaky check can't start properly, and this blocks private sync.

**Comment by amosbird** [comment]
> The test test_graphite_merge_tree is in the skip list in private repository, which is why the asan_flaky check can't start properly, and this blocks private sync.

Is this something we can unblock? It looks like the CH Inc sync test is still stuck in “pending”.

**Comment by iankosen** [comment]
Any plans to backport to v25.8?
