### PR TITLE
Fix logical error AggregateFunctionFactory returned nullptr

### LINKED ISSUE #24386: Logical error: AggregateFunctionFactory returned nullptr,
https://clickhouse-test-reports.s3.yandex.net/0/471142043ff3515c3d425eb7d294fc43c0c40e2a/stress_test_(undefined).html

``` sql
2021.05.20 23:54:24.407935 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Debug> executeQuery: (from [::1]:47014, using production parser) (comment: '/usr/share/clickhouse-test/queries/0_stateless/00746_sql_fuzzy.sh') SELECT deltaSumTimestamp(-17.47, ( SELECT now64() ) );
2021.05.20 23:54:24.408830 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2021.05.20 23:54:24.409004 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.05.20 23:54:24.504206 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Logical error: AggregateFunctionFactory returned nullptr (version 21.7.1.6902 (official build)) (from [::1]:47014) (comment: '/usr/share/clickhouse-test/queries/0_stateless/00746_sql_fuzzy.sh') (in query: SELECT deltaSumTimestamp(-17.47, ( SELECT now64() ) );), Stack trace (when copying this message, always include the lines below):
2021.05.20 23:54:24.505201 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Error> TCPHandler: Code: 49, e.displayText() = DB::Exception: Logical error: AggregateFunctionFactory returned nullptr, Stack trace:
2021.05.20 23:54:24.506247 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
```

```
2021.05.20 23:54:24.505201 [ 1918 ] {dbf9a6a6-2025-4656-bae3-4a5f52cf06c7} <Error> TCPHandler: Code: 49, e.displayText() = DB::Exception: Logical error: AggregateFunctionFactory returned nullptr, Stack trace:

0. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1e1f2e92 in /usr/bin/clickhouse
1. ./obj-x86_64-linux-gnu/../src/Common/Exception.cpp:57: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xf4aed9e in /usr/bin/clickhouse
2. ./obj-x86_64-linux-gnu/../src/AggregateFunctions/AggregateFunctionFactory.cpp:0: DB::AggregateFunctionFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Array const&, DB::AggregateFunctionProperties&) const @ 0x1b6329a3 in /usr/bin/clickhouse
3. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3124: DB::ExpressionAnalyzer::makeAggregateDescriptions(std::__1::shared_ptr<DB::ActionsDAG>&) @ 0x1be3db5c in /usr/bin/clickhouse
4. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:224: DB::ExpressionAnalyzer::analyzeAggregation() @ 0x1be3bab5 in /usr/bin/clickhouse
5. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.cpp:0: DB::ExpressionAnalyzer::ExpressionAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context>, unsigned long, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >) @ 0x1be3b292 in /usr/bin/clickhouse
6. ./obj-x86_64-linux-gnu/../src/Interpreters/ExpressionAnalyzer.h:289: DB::SelectQueryExpressionAnalyzer::SelectQueryExpressionAnalyzer(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::TreeRewriterResult const> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, DB::SelectQueryOptions const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >) @ 0x1c144fba in /usr/bin/clickhouse
7. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068: std::__1::__unique_if<DB::SelectQueryExpressionAnalyzer>::__unique_single std::__1::make_unique<DB::SelectQueryExpressionAnalyzer, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::TreeRewriterResult const>&, std::__1::shared_ptr<DB::Context>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, bool, DB::SelectQueryOptions&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > > >(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::TreeRewriterResult const>&, std::__1::shared_ptr<DB::Context>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&&, bool&&, DB::SelectQueryOptions&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >&&) @ 0x1c14aa56 in /usr/bin/clickhouse
8. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:431: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&)::$_2::operator()(bool) const @ 0x1c121b18 in /usr/bin/clickhouse
9. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:498: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1c11d008 in /usr/bin/clickhouse
10. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:160: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c11ac11 in /usr/bin/clickhouse
11. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2068: std::__1::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&>(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c3ca47c in /usr/bin/clickhouse
12. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:212: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c3c7945 in /usr/bin/clickhouse
13. ./obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:134: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1c3c5e6a in /usr/bin/clickhouse
14. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&) @ 0x1be2382a in /usr/bin/clickhouse
15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1649: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x1be22309 in /usr/bin/clickhouse
16. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:531: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1c6368d7 in /usr/bin/clickhouse
17. ./obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:920: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1c63553f in /usr/bin/clickhouse
18. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:312: DB::TCPHandler::runImpl() @ 0x1d17baae in /usr/bin/clickhouse
19. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1623: DB::TCPHandler::run() @ 0x1d197eed in /usr/bin/clickhouse
20. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1e16354c in /usr/bin/clickhouse
21. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:114: Poco::Net::TCPServerDispatcher::run() @ 0x1e163a2c in /usr/bin/clickhouse
22. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/ScopedLock.h:36: Poco::PooledThread::run() @ 0x1e25011a in /usr/bin/clickhouse
23. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::ThreadImpl::runnableEntry(void*) @ 0x1e24dccc in /usr/bin/clickhouse
24. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
25. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

### PR DESCRIPTION
**Pull request by Avogar**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix logical error "AggregateFunctionFactory returned nullptr" when using deltaSumTimestamp. Closes https://github.com/ClickHouse/ClickHouse/issues/24386.

Detailed description / Documentation draft:

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

File: src/AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp [hunk 1]
```diff
@@ -28,11 +28,11 @@ AggregateFunctionPtr createAggregateFunctionDeltaSumTimestamp(
         throw Exception("Incorrect number of arguments for aggregate function " + name,
             ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
 
-    if (!isInteger(arguments[0]) && !isFloat(arguments[0]) && !isDateOrDateTime(arguments[0]))
+    if (!isInteger(arguments[0]) && !isFloat(arguments[0]) && !isDate(arguments[0]) && !isDateTime(arguments[0]))
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp:31]: I cannot understand the logic in this change.

Looks like it uncovered a huge tech debt after merging #7170,
and this tech debt has to be fixed ASAP.

Both `isDateTime` and `isDateOrDateTime` should either include or not include the `DateTime64` data type.

Comment (alexey-milovidov) [reply src/AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp:31]: And how exactly it is related to the error "AggregateFunctionFactory returned nullptr"?

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp (hunk 1 above)
Comment (Avogar) [reply src/AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp:31]: > Both isDateTime and isDateOrDateTime should either include or not include the DateTime64 data type.

We have separate methods for DateTime and DateTime64: 
https://github.com/ClickHouse/ClickHouse/blob/master/src/DataTypes/IDataType.h#L325-L326

I think checking DateTime64 in isDateOrDateTime method is not good, because DateTime64 column is implemented by ColumnDecimal, while Date and DateTime columns by ColumnVector. 

> And how exactly it is related to the error "AggregateFunctionFactory returned nullptr"?

nullptr is returned here:
https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/Helpers.h#L263-L267

deltaSumTimestamp doesn't support working with DateTime64. I suppose author (and me too) didn't know that isDateOrDateTime return true for DateTime64.

Now I think that I should also add DateTime64 in https://github.com/ClickHouse/ClickHouse/blob/f22702001831c074c789be306a9f77c5406d848d/src/AggregateFunctions/Helpers.h#L249 and https://github.com/ClickHouse/ClickHouse/blob/f22702001831c074c789be306a9f77c5406d848d/src/AggregateFunctions/Helpers.h#L231 and set DateTime64Supported = false for deltaSumTimestamp

Comment (Avogar) [reply src/AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp:31]: Ok

**Review by alexey-milovidov — APPROVED** [review]
