### PR TITLE
ALTER to LowCardinality was leading to segfault on empty parts

### LINKED ISSUE #5289: Enum8 -> LowCardinality(String) column type modification SegFault
**How to reproduce and description**
While trying to convert Enum8 column with ~30 distinct small String values to LowCardinality(String) with statement:
`alter table impressions modify column node_name LowCardinality(String)`

table contains around 3.5 billion rows. Also this bug reproduces not only with Enum8 -> LowCardinality(String), but also with String -> LowCardinality(String).

clickhouse version:
`ClickHouse client version 19.4.3.11.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.4.3 revision 54416.`

os version:
`CentOS Linux release 7.5.1804 (Core) `

stacktrace in clickhouse-server.err.log:
```
2019.05.15 19:37:45.804094 [ 234 ] {} <Error> BaseDaemon: ########################################
2019.05.15 19:37:45.804237 [ 234 ] {} <Error> BaseDaemon: (from thread 33) Received signal Segmentation fault (11).
2019.05.15 19:37:45.804273 [ 234 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.05.15 19:37:45.804293 [ 234 ] {} <Error> BaseDaemon: Access: read.
2019.05.15 19:37:45.804310 [ 234 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.05.15 19:37:45.858422 [ 234 ] {} <Error> BaseDaemon: 0. clickhouse-server() [0x54ec03b]
2019.05.15 19:37:45.858558 [ 234 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::DataTypeLowCardinality::serializeBinaryBulkStateSuffix(DB::IDataType::SerializeBinaryBulkSettings&, std::shared_ptr<DB::IDataType::SerializeBinaryBulkState>&) const+0x1f) [0x54eddcf]
2019.05.15 19:37:45.858589 [ 234 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::MergedColumnOnlyOutputStream::writeSuffixAndGetChecksums()+0x1b6) [0x58ec396]
2019.05.15 19:37:45.858615 [ 234 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::MergeTreeData::alterDataPart(std::shared_ptr<DB::MergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::vector<std::shared_ptr<DB::ASTIndexDeclaration>, std::allocator<std::shared_ptr<DB::ASTIndexDeclaration> > > const&, bool)+0x973) [0x587a533]
2019.05.15 19:37:45.858639 [ 234 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::StorageMergeTree::alter(DB::AlterCommands const&, std::string const&, std::string const&, DB::Context const&)+0x384) [0x57cb3b4]
2019.05.15 19:37:45.858659 [ 234 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::InterpreterAlterQuery::execute()+0x833) [0x5b78233]
2019.05.15 19:37:45.858689 [ 234 ] {} <Error> BaseDaemon: 6. clickhouse-server() [0x56f5fb6]
2019.05.15 19:37:45.858709 [ 234 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::executeQuery(std::string const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0x61) [0x56f7eb1]
2019.05.15 19:37:45.858730 [ 234 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::TCPHandler::runImpl()+0x47c) [0x2e1676c]
2019.05.15 19:37:45.858754 [ 234 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x2e17b0c]
2019.05.15 19:37:45.858779 [ 234 ] {} <Error> BaseDaemon: 10. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x613634f]
2019.05.15 19:37:45.858795 [ 234 ] {} <Error> BaseDaemon: 11. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x61369b0]
2019.05.15 19:37:45.858812 [ 234 ] {} <Error> BaseDaemon: 12. clickhouse-server(Poco::PooledThread::run()+0x77) [0x621e117]
2019.05.15 19:37:45.858828 [ 234 ] {} <Error> BaseDaemon: 13. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x621b678]
2019.05.15 19:37:45.858843 [ 234 ] {} <Error> BaseDaemon: 14. clickhouse-server() [0x692ecef]
2019.05.15 19:37:45.858863 [ 234 ] {} <Error> BaseDaemon: 15. /lib64/libpthread.so.0(+0x7e25) [0x7f951025ce25]
```

clickhouse successfully restarts after this crash.

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Non-significant (changelog entry is not needed)

Detailed description (optional):
When empty part was altered to LowCardinality segmentation fault was happening with a stack trace like that:

```
2019.11.15 12:11:14.565554 [ 392 ] {} <Error> BaseDaemon: ########################################
2019.11.15 12:11:14.565607 [ 392 ] {} <Error> BaseDaemon: (version 19.11.12.69 (official build)) (from thread 41) Received signal Segmentation fault (11).
2019.11.15 12:11:14.565639 [ 392 ] {} <Error> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2019.11.15 12:11:14.606264 [ 392 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(StackTrace::StackTrace(ucontext_t const&)+0x31) [0x7dcc1f1]
1. /usr/bin/clickhouse-server() [0x3d15f3e]
2. /lib64/libpthread.so.0(+0xf5d0) [0x7f2109a805d0]
3. /usr/bin/clickhouse-server() [0x6bb8bf3]
4. /usr/bin/clickhouse-server(DB::DataTypeLowCardinality::serializeBinaryBulkStateSuffix(DB::IDataType::SerializeBinaryBulkSettings&, std::shared_ptr<DB::IDataType::Seria
5. /usr/bin/clickhouse-server(DB::MergedColumnOnlyOutputStream::writeSuffixAndGetChecksums()+0x1f6) [0x7010966]
6. /usr/bin/clickhouse-server(DB::MergeTreeData::alterDataPart(DB::NamesAndTypesList const&, std::vector<std::shared_ptr<DB::ASTIndexDeclaration>, std::allocator<std::sha
7. /usr/bin/clickhouse-server(ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>)+0x1a7) [0x772b977]
8. /usr/bin/clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::option
9. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1a6) [0x7729486]
10. /usr/bin/clickhouse-server() [0xb89e440]
11. /lib64/libpthread.so.0(+0x7dd5) [0x7f2109a78dd5]
12. /lib64/libc.so.6(clone+0x6d) [0x7f210929c02d
```

It like the root of the problem was fixed between 19.11.12 and 19.11.13.
~~Most probably it was that fix: https://github.com/ClickHouse/ClickHouse/pull/7062/~~
It was fixed in https://github.com/ClickHouse/ClickHouse/pull/6780/

Adding test just in case.

It looks like those 2 issues can be also closed: https://github.com/ClickHouse/ClickHouse/issues/5289 and https://github.com/ClickHouse/ClickHouse/issues/6877

### CODE REVIEW

File: dbms/tests/queries/0_stateless/01035_lc_empty_part_bug.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
+-- that test is failing on versions <= 19.11.12
+DROP TABLE IF EXISTS lc_empty_part_bug;
+create table lc_empty_part_bug (id  UInt64, s String) Engine=MergeTree ORDER BY id;
+insert into lc_empty_part_bug select number as id, toString(rand()) from numbers(100);
+alter table lc_empty_part_bug delete where id < 100;
+SELECT 'wait for delete to finish', sleep(1);
```
Comment (alexey-milovidov) [inline dbms/tests/queries/0_stateless/01035_lc_empty_part_bug.sql]: This will make the test flacky.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
Look at the examples for waiting for mutation to finish in another tests.

**Comment by alexey-milovidov** [comment]
Fixed.
