### PR TITLE
Fix bug with `intDiv` for decimal arguments

### LINKED ISSUE #56414: why intDivOrZero result is  decimal
SELECT
toDecimal32(161.73,4) sumRevenue,
6962 sumInstall,
if(sumInstall >0,intDivOrZero(sumRevenue,sumInstall) ,0) eachOfferRevenue 
image

### PR DESCRIPTION
**Pull request by yariks5s**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes bug with for function `intDiv` with decimal arguments. Fixes #56414.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 36055bd0089f52473f893d71c475a2782a45e8b4 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59243/36055bd0089f52473f893d71c475a2782a45e8b4/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59243/36055bd0089f52473f893d71c475a2782a45e8b4/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Functions/FunctionBinaryArithmetic.h [hunk 1]
```diff
@@ -146,10 +146,25 @@ struct BinaryOperationTraits
...
     using ResultDataType = Switch<
+        /// Result must be Integer
+        Case<
+            only_integer && (IsDataTypeDecimal<LeftDataType> || IsDataTypeDecimal<RightDataType>),
+            Switch<
+                Case<
+                    IsDataTypeDecimal<LeftDataType> || IsDataTypeDecimal<RightDataType>,
+                    Switch<
+                        Case<IsIntegralOrExtended<LeftDataType>, LeftDataType>,
+                        Case<IsIntegralOrExtended<RightDataType>, RightDataType>,
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:162]: It doesn't seems right, intDiv(Decimal256, UInt8) -> UInt8, but should be Int256 I guess. Example:
Current bahaviour:
```
:) SELECT intDiv(CAST('42424242424242424424242.42', 'Decimal256(2)'), 2)

┌─intDiv(CAST('42424242424242424424242.42', 'Decimal256(2)'), 2)─┐
│                                     21212121212121212212121.21 │
└────────────────────────────────────────────────────────────────┘
```

New:
```
:) SELECT intDiv(CAST('42424242424242424424242.42', 'Decimal128(2)'), 2)

Received exception:
Code: 407. DB::Exception: Convert overflow: While processing intDiv(CAST('42424242424242424424242.42', 'Decimal128(2)'), 2). (DECIMAL_OVERFLOW)

```

Comment (Avogar) [reply src/Functions/FunctionBinaryArithmetic.h:162]: I think we should only take first argument into account when we decide the result type. From the documentation about `intDiv`: `The result has the same width as the dividend (the first parameter)`
 So, if first argument is Integer, use it as result type, if first is Decimal, use corresponding interger type.

File: src/Functions/FunctionBinaryArithmetic.h [hunk 2]
```diff
@@ -2026,6 +2108,12 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
                 left_col = castColumn(arguments[0], converted_type);
                 right_col = castColumn(arguments[1], converted_type);
             }
+            else if constexpr (is_div_int_with_decimal)
+            {
+                const auto converted_type = std::make_shared<DataTypeInt64>();
+                left_col = castColumn(arguments[0], converted_type);
+                right_col = castColumn(arguments[1], converted_type);
+            }
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:2116]: So, we actually don't do real decimal division, we just cast both arguments to `Int64` and then devide them as integers. But it won't work, we will lose precision, and we cannot convert for examplt `Decimal128` to `Int64`. Examples:
```
avogar-dev :) select intDiv(22.8::Decimal32(2), 0.1::Decimal32(2))

Received exception:
Code: 153. DB::Exception: Division by zero: While processing intDiv(CAST('22.8', 'Decimal32(2)'), CAST('0.1', 'Decimal32(2)')). (ILLEGAL_DIVISION)

avogar-dev :) select intDiv(222222222222222222222222222222222222.8::Decimal128(2), 2::Decimal32(2))

Received exception:
Code: 407. DB::Exception: Convert overflow: While processing intDiv(CAST('222222222222222222222222222222222222.8', 'Decimal128(2)'), CAST('2', 'Decimal32(2)')). (DECIMAL_OVERFLOW)
```

I think we should do real decimal division and after it cast it to result integer. Need to think how to do it properly

Comment (yariks5s) [reply src/Functions/FunctionBinaryArithmetic.h:2116]: I considered this problem and didn't know how to resolve it as well, so came up with this solution, though it can be not good

File: src/Functions/FunctionBinaryArithmetic.h [hunk 3]
```diff
@@ -1667,31 +1673,51 @@ class FunctionBinaryArithmetic : public IFunction
                 {
                     if constexpr (IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType>)
                     {
-                        if constexpr (is_division)
+                        if constexpr (is_div_int || is_div_int_or_zero)
+                            type_res = std::make_shared<ResultDataType>();
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:1677]: I think we can move this condition one layer outside:
```c++
if constexpr (is_div_int || is_div_int_or_zero)
{
    type_res = std::make_shared<ResultDataType>();
}
else if constexpr (IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType>)
{
    ...
}
```
So we won't need to check `is_div_int || is_div_int_or_zero` in any other scopes

File: src/Functions/FunctionBinaryArithmetic.h [hunk 4]
```diff
@@ -2051,6 +2077,46 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
...
+                    Case<
+                        IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType> && UseLeftDecimal<LeftDataType, RightDataType>,
+                        LeftDataType>,
+                    Case<IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType>, RightDataType>,
+                    Case<IsDataTypeDecimal<LeftDataType> && IsIntegralOrExtended<RightDataType>, LeftDataType>,
+                    Case<IsDataTypeDecimal<RightDataType> && IsIntegralOrExtended<LeftDataType>, RightDataType>,
+
+                    /// Decimal <op> Real is not supported (traditional DBs convert Decimal <op> Real to Real)
+                    Case<IsDataTypeDecimal<LeftDataType> && !IsIntegralOrExtendedOrDecimal<RightDataType>, InvalidType>,
+                    Case<IsDataTypeDecimal<RightDataType> && !IsIntegralOrExtendedOrDecimal<LeftDataType>, InvalidType>>; /// Determine result decimal type as it would be with usual division (as we determine BinaryOperationTraits::ResultType)
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:2092]: I think we can avoid code duplication in this case. We can declare `DecimalResultDataType` in `BinaryOperationTraits` before `ResultDataType` and use it both in `ResultDataType` and here.
It may look like this:
```c++
    using DecimalResultDataType = Switch<
        Case<!allow_decimal, InvalidType>,
        Case<IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType> && UseLeftDecimal<LeftDataType, RightDataType>, LeftDataType>,
        Case<IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType>, RightDataType>,
        Case<IsDataTypeDecimal<LeftDataType> && IsIntegralOrExtended<RightDataType>, LeftDataType>,
        Case<IsDataTypeDecimal<RightDataType> && IsIntegralOrExtended<LeftDataType>, RightDataType>,

        /// e.g Decimal +-*/ Float, least(Decimal, Float), greatest(Decimal, Float) = Float64
        Case<IsDataTypeDecimal<LeftDataType> && IsFloatingPoint<RightDataType>, DataTypeFloat64>,
        Case<IsDataTypeDecimal<RightDataType> && IsFloatingPoint<LeftDataType>, DataTypeFloat64>,

        Case<IsOperation<Operation>::bit_hamming_distance && IsIntegral<LeftDataType> && IsIntegral<RightDataType>, DataTypeUInt8>,
        Case<IsOperation<Operation>::bit_hamming_distance && IsFixedString<LeftDataType> && IsFixedString<RightDataType>, DataTypeUInt16>,
        Case<IsOperation<Operation>::bit_hamming_distance && IsString<LeftDataType> && IsString<RightDataType>, DataTypeUInt64>,

          /// Decimal <op> Real is not supported (traditional DBs convert Decimal <op> Real to Real)
        Case<IsDataTypeDecimal<LeftDataType> && !IsIntegralOrExtendedOrDecimal<RightDataType>, InvalidType>,
        Case<IsDataTypeDecimal<RightDataType> && !IsIntegralOrExtendedOrDecimal<LeftDataType>, InvalidType>>;

    using ResultDataType = Switch<
        /// Result must be Integer
        Case<IsOperation<Operation>::div_int || IsOperation<Operation>::div_int_or_zero, DataTypeFromFieldType<typename Op::ResultType>>,
        /// Decimal cases
        Case<IsDataTypeDecimal<LeftDataType> || IsDataTypeDecimal<RightDataType>, DecimalResultDataType>,
        ...

```

File: src/Functions/FunctionBinaryArithmetic.h [hunk 5]
```diff
@@ -2051,6 +2077,46 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
                     col_left_size,
                     right_nullmap);
             }
+            else if constexpr (!decimal_with_float && (is_div_int || is_div_int_or_zero) && (IsDataTypeDecimal<LeftDataType> || IsDataTypeDecimal<RightDataType>))
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:2080]: Let's write a comment about this case, why we need it and what we are doing here

File: src/Functions/FunctionBinaryArithmetic.h [hunk 6]
```diff
@@ -622,7 +643,10 @@ struct DecimalBinaryOperation
             if constexpr (op_case == OpCase::RightConstant)
             {
                 if ((*right_nullmap)[0])
+                {
+                    c[0] = ResultType();
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:647]: Seems like this is the problem. We should do it in a loop:
```suggestion
                    for (size_t i = 0; i < size; ++i)
                        c[i] = ResultType();
```

File: src/Functions/FunctionBinaryArithmetic.h [hunk 7]
```diff
@@ -1681,17 +1708,23 @@ class FunctionBinaryArithmetic : public IFunction
                                 if (left.getScale() + right.getScale() > ResultDataType::maxPrecision())
                                     throw Exception(ErrorCodes::DECIMAL_OVERFLOW, "Overflow during decimal division");
                             }
+                            ResultDataType result_type = decimalResultType<is_multiply, is_division>(left, right);
+                            type_res = std::make_shared<ResultDataType>(result_type.getPrecision(), result_type.getScale());
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:1712]: Why it was moved into another scope?

Comment (yariks5s) [reply src/Functions/FunctionBinaryArithmetic.h]: fixed

File: src/Functions/FunctionBinaryArithmetic.h [hunk 8]
```diff
@@ -2051,6 +2085,36 @@ ColumnPtr executeStringInteger(const ColumnsWithTypeAndName & arguments, const A
...
+                    if constexpr (IsDataTypeDecimal<LeftDataType> && IsDataTypeDecimal<RightDataType>)
+                    {
+                        DecimalResultType result_type = decimalResultType<is_multiply, is_division>(left, right);
+                        type_res = std::make_shared<DecimalResultType>(result_type.getPrecision(), result_type.getScale());
+                    }
+                    else if constexpr (IsDataTypeDecimal<LeftDataType>)
+                        type_res = std::make_shared<LeftDataType>(left.getPrecision(), left.getScale());
+                    else
+                        type_res = std::make_shared<RightDataType>(right.getPrecision(), right.getScale());
+                    // Create result decimal type somehow, maybe similar to how we do it in getReturnTypeImplStatic
```
Comment (Avogar) [inline src/Functions/FunctionBinaryArithmetic.h:2104]:
```suggestion
```

**Review by Avogar — APPROVED** [review]
