### PR TITLE
Using validation function instead of manual validation for getReturnTypeImpl

### LINKED ISSUE #67447: Replace manual function input validation by `validateFunctionArguments`
SQL functions in ClickHouse need to implement method `getReturnTypeImpl` which checks the number and type of inputs, and throws an exception if something is not as expected. Most functions check the input manually which is error-prone and often done inconsistently across functions (see e.g. [here](https://github.com/ClickHouse/ClickHouse/pull/66851) for a PR that tries to resolve inconsistencies).

src/Functions/FunctionHelpers.h provides method `validateFunctionArguments`, which checks the function arguments in a more abstract manner.

Example:

```cpp
FunctionArgumentDescriptors mandatory_args{
    {"time"", static_cast<FunctionArgumentDescriptor::TypeValidator>(&isNumber), nullptr, "(U)Int*"},
    {"format", static_cast<FunctionArgumentDescriptor::TypeValidator>(&isString), nullptr, "String"},
};

FunctionArgumentDescriptors optional_args{
    {"timezone", static_cast<FunctionArgumentDescriptor::TypeValidator>(&isString), nullptr, "String"},
};

validateFunctionArguments(*this, arguments, mandatory_args, optional_args);
```

for a (hypothetical) function with signature `f(time, format[, timezone])`;

Doing so will reduce the mental load and provide more uniform error messages.

We should go through all functions and convert manual checking to `validateFunctionArguments` where possible (sometimes, the function signature is too complex for `validateFunctionArguments`). Since there are hundreds of SQL functions in ClickHouse, this issue is ideally addressed incrementally.

### PR DESCRIPTION
**Pull request by MaxMaz111**
### Changelog category:
- Improvement

### Changelog entry

`getReturnTypeImpl` for `tupleConcat` now checks input using a `validateFunctionArgumentsWithVariadics` instead of doing it manually.

this closes https://github.com/ClickHouse/ClickHouse/issues/67447

---

> [!NOTE]
> **Medium Risk**
> Touches `getReturnTypeImpl` validation across many built-in functions; behavior should be equivalent but could subtly change accepted argument combinations and error messages/codes, affecting compatibility.
> 
> **Overview**
> **Standardizes function argument validation** by replacing ad-hoc checks in `getReturnTypeImpl` with `validateFunctionArguments`/`validateFunctionArgumentsWithVariadics` across a set of functions (e.g., `file`, `now`, `tupleConcat`, JSON/string/random/introspection helpers).
> 
> Adds small reusable type predicates (notably `isLowCardinalityType` in `FunctionHelpers`, plus local helpers like `isStringOrNull`/`isDateOrDateTime`) to express expected argument types, improving consistency and reducing duplicated error-handling logic.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9ccf1399af0be737cef2a6beff049c532e5029b6. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: src/Functions/appendTrailingCharIfAbsent.cpp [hunk 1]
```diff
@@ -42,13 +42,14 @@ class FunctionAppendTrailingCharIfAbsent : public IFunction
         return 2;
     }
 
-    DataTypePtr getReturnTypeImpl(const DataTypes & arguments) const override
+    DataTypePtr getReturnTypeImpl(const ColumnsWithTypeAndName & arguments) const override
     {
-        if (!isString(arguments[0]))
-            throw Exception(ErrorCodes::ILLEGAL_TYPE_OF_ARGUMENT, "Illegal type {} of the first argument of function {}", arguments[0]->getName(), getName());
+        FunctionArgumentDescriptors mandatory_args{
+            {"s", &isString, nullptr, "String"},
```
Comment (scanhex12) [inline src/Functions/appendTrailingCharIfAbsent.cpp:48]: 's' and 'c' seems strange, how did you get such names?

**Review by scanhex12 — APPROVED** [review]
LGTM

File: src/Functions/appendTrailingCharIfAbsent.cpp (hunk 1 above)
Comment (MaxMaz111) [reply src/Functions/appendTrailingCharIfAbsent.cpp:48]: As far i as i remember, all the arguments names are from `FunctionDocumentation::Arguments` listed below
