### PR TITLE
Fix high memory consumption on Squashing

### LINKED ISSUE #68263: (Alternative build) High memory usage in `INSERT INTO ... SELECT` query when upgrading from 24.5 to 24.6
**Describe the unexpected behaviour**

We have some pipelines running simple `INSERT ... SELECT` queries. After upgrading from 24.5 to 24.6, the memory usage increase significantly and cause OOM:

```
-- v24.5.3.1
Query id: b17800bd-e0f4-409a-8e44-d0328a27051f

Ok.

0 rows in set. Elapsed: 198.548 sec. Processed 251.80 million rows, 13.01 GB (1.27 million rows/s., 65.52 MB/s.)
Peak memory usage: 2.68 GiB.

-- v24.6.2.17
Query id: c7716df9-b5c2-4085-a440-bed4085d6b98

Ok.

0 rows in set. Elapsed: 169.896 sec. Processed 251.80 million rows, 13.01 GB (1.48 million rows/s., 76.57 MB/s.)
Peak memory usage: 9.47 GiB.
```

Settings used in both queries are same:

```
  join_use_nulls=1,
  max_insert_block_size=83886080,
  min_insert_block_size_rows=20000000,
  min_insert_block_size_bytes=2000000000,
  max_threads=1,
  optimize_trivial_insert_select=1
```

Initial investigation point out to #61047, as when looking at memory profiling:

- v24.5.3.1 top 3 trace by memory

```
Row 1:
──────
trace_symbols:                 MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
Allocator<false, false>::alloc(unsigned long, unsigned long)
DB::Arena::addMemoryChunk(unsigned long)
DB::pushBackAndCreateState(DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::Arena&, DB::IAggregateFunction const*) (.llvm.15954055847746520766)
DB::ColumnAggregateFunction::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)
DB::Block DB::SquashingTransform::addImpl<DB::Block&&>(DB::Block&&)
DB::SimpleSquashingChunksTransform::consume(DB::Chunk)
DB::IInflatingTransform::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::execute(unsigned long, bool)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)


formatReadableSize(sum(size)): 1.55 GiB

Row 2:
──────
trace_symbols:                 MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long)
void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long)
DB::ColumnVector<double>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)
DB::Block DB::SquashingTransform::addImpl<DB::Block&&>(DB::Block&&)
DB::SimpleSquashingChunksTransform::consume(DB::Chunk)
DB::IInflatingTransform::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::execute(unsigned long, bool)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)


formatReadableSize(sum(size)): 275.56 MiB

Row 3:
──────
trace_symbols:                 MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long)
void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::reserveForNextSize<>()
DB::pushBackAndCreateState(DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::Arena&, DB::IAggregateFunction const*) (.llvm.15954055847746520766)
DB::ColumnAggregateFunction::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)
DB::Block DB::SquashingTransform::addImpl<DB::Block&&>(DB::Block&&)
DB::SimpleSquashingChunksTransform::consume(DB::Chunk)
DB::IInflatingTransform::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::execute(unsigned long, bool)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)


formatReadableSize(sum(size)): 229.01 MiB

```

- v24.6.2.17 top 3 trace by memory

```
Row 1:
──────
trace_symbols:                 MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
Allocator<false, false>::alloc(unsigned long, unsigned long)
DB::Arena::addMemoryChunk(unsigned long)
DB::pushBackAndCreateState(DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul>&, DB::Arena&, DB::IAggregateFunction const*) (.llvm.13781325878661108696)
DB::ColumnAggregateFunction::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)
DB::Squashing::squash(std::__1::vector<DB::Chunk, std::__1::allocator<DB::Chunk>>&)
DB::ApplySquashingTransform::onConsume(DB::Chunk)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__1::__function::__policy_storage const*)
DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*)
DB::ExceptionKeepingTransform::work()
DB::ApplySquashingTransform::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::execute(unsigned long, bool)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)


formatReadableSize(sum(size)): 5.00 GiB

Row 2:
──────
trace_symbols:                 MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
Allocator<false, false>::alloc(unsigned long, unsigned long)
void DB::PODArrayBase<1ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::realloc<>(unsigned long)
DB::SerializationString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const
DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const
DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
DB::MergeTreeRangeReader::read(unsigned long, DB::MarkRanges&)
DB::MergeTreeReadTask::read(DB::MergeTreeReadTask::BlockSizeParams const&)
DB::MergeTreeInOrderSelectAlgorithm::readFromTask(DB::MergeTreeReadTask&, DB::MergeTreeReadTask::BlockSizeParams const&)
DB::MergeTreeSelectProcessor::read()
DB::MergeTreeSource::tryGenerate()
DB::ISource::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::execute(unsigned long, bool)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)


formatReadableSize(sum(size)): 1013.47 MiB

Row 3:
──────
trace_symbols:                 MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
MemoryTracker::allocImpl(long, bool, MemoryTracker*, double)
Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long)
void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::realloc<>(unsigned long)
DB::Squashing::squash(std::__1::vector<DB::Chunk, std::__1::allocator<DB::Chunk>>&)
DB::ApplySquashingTransform::onConsume(DB::Chunk)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__1::__function::__policy_storage const*)
DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*)
DB::ExceptionKeepingTransform::work()
DB::ApplySquashingTransform::work()
DB::ExecutionThreadContext::executeTask()
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::execute(unsigned long, bool)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*)
```

**Additional context**
Not official build but we believe this doesn't relates to our changes.

### LINKED ISSUE #69415: Increased memory consumption of join query after up from 24.5 to 24.8
Same code run at v.24.5 and v.24.8

Memory consumption of test_table query (based on query_log):
v.24.5: 79541876 bytes
v.24.8: 23405643120 bytes

```
drop table if exists id_values;
create table id_values engine MergeTree order by id1 as
select arrayJoin(range(1000000)) as id1, arrayJoin(range(1000)) as id2;

drop table if exists test_table;
create table test_table engine MergeTree order by id as
select id_values.id1             as id,
       string_values.string_val1 as string_val1,
       string_values.string_val2 as string_val2
from id_values
         join (select arrayJoin(range(10)) as id1,
                      'qwe'                as string_val1,
                      'asd'                as string_val2) as string_values
              on id_values.id1 = string_values.id1
    settings join_algorithm = 'hash';
```

### LINKED ISSUE #69435: Increased memory consumption after upgrading from 24.5 to 24.8
**Describe the situation**
Recently, we encountered a significant increase in memory consumption during query inserts involving joins.
After upgrading to version 24.8, the same queries now utilize 10x more memory or even more, occasionally resulting in failures.
This situation has forced us to apply special settings (join_algorithm='partial_merge'), which unfortunately causes the queries to run much slower.

The issue seems to be particularly pronounced when joining tables with columns containing long JSON Strings (usually 200+ characters). Interestingly, the source tables themselves are small in terms of storage size — kilobytes!

The read and result stats are exactly the same before/after the upgrade:
* read_bytes: 3057073
* read_rows: 17005
* result_bytes: 658
* result_rows: 4

Here is the memory usage comparison:

Memory usage before upgrade: 361,705,119
Memory usage after upgrading: 39,020,451,116 (with the setting join_algorithm='partial_merge'; without this setting, the query fails due to a memory exception)

other default settings:
* allow_experimental_analyzer: 0
* max_bytes_before_external_group_by: 8000000000
* max_bytes_before_external_sort: 8000000000
* max_memory_usage: 55000000000

Example to relevant query:
```sql
select
    rt1."id" as "id",
    rt1."data_source_id" as "data_source_id",
    rt1."table_name" as "table_name",
    rt1."source" as "source",
    rt1."created_timestamp" as "created_timestamp",
    -- Column consists long JSON Strings
    lt2.raw_data as raw_data
from rt1	-- ~ 1 MB
join lt2	-- ~ 500 KB
    on rt1.id = lt2.id
```

* ClickHouse version: 24.8.3.59
* Prevouis ClickHouse version:  24.5.3.5

**Expected performance**
Use the same amount of memory

### PR DESCRIPTION
**Pull request by yariks5s**
Fixes https://github.com/ClickHouse/ClickHouse/issues/69415, Fixes https://github.com/ClickHouse/ClickHouse/issues/68263, Fixes #69435

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed case when memory consumption was too high because of the squashing in `INSERT INTO ... SELECT` or `CREATE TABLE AS SELECT` queries

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit caab4dd8b903a8caaa45b0e9d811487110ac2560 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/69469/caab4dd8b903a8caaa45b0e9d811487110ac2560/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/db42cf12fd0e7a54b9a63118b21c300eddb7970e/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by antonio2368 — APPROVED** [review]

File: tests/queries/0_stateless/03236_squashing_high_memory.sql [hunk 1]
```diff
@@ -0,0 +1,22 @@
+DROP TABLE IF EXISTS id_values;
+
+DROP TABLE IF EXISTS test_table;
+
+CREATE TABLE id_values ENGINE MergeTree ORDER BY id1 AS
+    SELECT arrayJoin(range(1000000)) AS id1, arrayJoin(range(1000)) AS id2;
```
Comment (antonio2368) [inline tests/queries/0_stateless/03236_squashing_high_memory.sql:6]:
```suggestion
    SELECT arrayJoin(range(500000)) AS id1, arrayJoin(range(1000)) AS id2;
```

is okay for me locally with 5GiB limit while the difference in memory usage is still high

File: tests/queries/0_stateless/03236_squashing_high_memory.sql [hunk 2]
```diff
@@ -0,0 +1,25 @@
+-- Tags: no-fasttest
+-- reason: test requires too many rows to read
+
+DROP TABLE IF EXISTS id_values;
+
+DROP TABLE IF EXISTS test_table;
+
+CREATE TABLE id_values ENGINE MergeTree ORDER BY id1 AS
+    SELECT arrayJoin(range(20000)) AS id1, arrayJoin(range(1000)) AS id2;
```
Comment (antonio2368) [inline tests/queries/0_stateless/03236_squashing_high_memory.sql:9]: If you reduce it too much the test loses its point
Please check if you can increase the row limit for this query or something else.
