### PR TITLE
Make big integers production ready.

### LINKED ISSUE #4176: LowCardinality: UUID is not implemented
version 19.1.6. 

select toLowCardinality(generateUUIDv4()) 
Unexpected dictionary type for DataTypeLowCardinality: UUID.

### LINKED ISSUE #7834: Code: 48. DB::Exception: There are no UInt128 literals in SQL
This error occurs when a subquery returns a value of the type UUID.

**How to reproduce**
* ClickHouse server versions: 19.16.3, 19.17.3.7
* Create two tables:
`CREATE TABLE single_id(id UUID) ENGINE = Log`
`CREATE TABLE other_table(id UUID) ENGINE = Log`
* Sample data (single row):
`INSERT INTO single_id VALUES ('61f0c404-5cb3-11e7-907b-a6006ad3dba0')`
* Run query:
`SELECT * FROM other_table WHERE id = (SELECT * FROM single_id)`

**Expected behavior**
The query should return a table with one column and zero rows.

**Error message**
`Received exception from server (version 19.16.3):`
`Code: 48. DB::Exception: There are no UInt128 literals in SQL.`

### LINKED ISSUE #17828: Can't cast any String decimal to Decimal256
**Describe the unexpected behaviour**

Hi,

When trying to cast a String to a `Decimal256`, I encountered 2 different unexpected exceptions:

- The first one is a `Can't compare` exception when casting a decimal with high precision and scale:
```
data :) SELECT CAST('123456789123456789123456789.123456789123456789123456789', 'Decimal256(38)')

SELECT CAST('123456789123456789123456789.123456789123456789123456789', 'Decimal256(38)')


Received exception from server (version 20.11.4):
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Can't compare. 

0 rows in set. Elapsed: 0.234 sec. 
```

- The second one is a `Decimal math overflow` when trying to cast a simple string decimal, while the casting to `Decimal128` work as intended: 
```
data :) SELECT CAST('1.0', 'Decimal256(38)')

SELECT CAST('1.0', 'Decimal256(38)')


Received exception from server (version 20.11.4):
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Decimal math overflow: While processing CAST('1.0', 'Decimal256(38)'). 

0 rows in set. Elapsed: 0.196 sec. 

data :) SELECT CAST('1.0', 'Decimal128(18)')

SELECT CAST('1.0', 'Decimal128(18)')

┌─CAST('1.0', 'Decimal128(18)')─┐
│          1.000000000000000000 │
└───────────────────────────────┘

1 rows in set. Elapsed: 0.195 sec. 
```

**How to reproduce**

Please see the above queries to reproduce. 
Server version: `20.11.4`
Client version: `20.10.2.20`

**Expected behavior**
I would expect the casting of both string to `Decimal256(38)` to work and not raise any exception as the numbesr that I'm trying to cast are in the range of the `Decimal256(38)`.

**Error message and/or stacktrace**
2 errors:
```
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Can't compare. 
```
```
Code: 407. DB::Exception: Received from 10.170.2.185:9000. DB::Exception: Decimal math overflow: While processing CAST('1.0', 'Decimal256(38)'). 
```

### LINKED ISSUE #23936: LowCardinality(UUID) is forbidden since 21.2
On 21.1::
```
create table test (x LowCardinality(UUID)) engine=Memory;

Received exception from server (version 21.1.9):
Code: 455. DB::Exception: Received from localhost:9000. DB::Exception: Creating columns of type LowCardinality(UUID) is prohibited by default due to expected negative impact on performance. It can be enabled with the "allow_suspicious_low_cardinality_types" setting.. Stack trace:

0. DB::InterpreterCreateQuery::validateTableStructure(DB::ASTCreateQuery const&, DB::InterpreterCreateQuery::TableProperties const&) const @ 0xec3ec84 in /usr/bin/clickhouse
1. DB::InterpreterCreateQuery::setProperties(DB::ASTCreateQuery&) const @ 0xec3d5b8 in /usr/bin/clickhouse
2. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xec4196e in /usr/bin/clickhouse
3. DB::InterpreterCreateQuery::execute() @ 0xec46647 in /usr/bin/clickhouse
4. ? @ 0xf1672db in /usr/bin/clickhouse
5. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf165cbd in /usr/bin/clickhouse
6. DB::TCPHandler::runImpl() @ 0xf875556 in /usr/bin/clickhouse
7. DB::TCPHandler::run() @ 0xf884367 in /usr/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x11dca62f in /usr/bin/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x11dcc041 in /usr/bin/clickhouse
10. Poco::PooledThread::run() @ 0x11ef7c49 in /usr/bin/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x11ef3bda in /usr/bin/clickhouse
12. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
13. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

and allowing it:

```
set allow_suspicious_low_cardinality_types=1;
create table test (x LowCardinality(UUID)) engine=Memory;

Ok.

0 rows in set. Elapsed: 0.004 sec. 
```

On 21.2 and newer:
```
:) create table test (x LowCardinality(UUID)) engine=Memory;

0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 21.6.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: DataTypeLowCardinality is supported only for numbers, strings, Date or DateTime, but got UUID. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87df5fa in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
1. DB::DataTypeLowCardinality::DataTypeLowCardinality(std::__1::shared_ptr<DB::IDataType const>) @ 0xed65f26 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
2. std::__1::shared_ptr<DB::DataTypeLowCardinality> std::__1::allocate_shared<DB::DataTypeLowCardinality, std::__1::allocator<DB::DataTypeLowCardinality>, std::__1::shared_ptr<DB::IDataType const>, void>(std::__1::allocator<DB::DataTypeLowCardinality> const&, std::__1::shared_ptr<DB::IDataType const>&&) @ 0xed68397 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
3. DB::create(std::__1::shared_ptr<DB::IAST> const&) (.llvm.15080078877451193199) @ 0xed67b00 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
4. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0xed5c622 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
5. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0xed5c406 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
6. DB::InterpreterCreateQuery::getColumnsDescription(DB::ASTExpressionList const&, std::__1::shared_ptr<DB::Context>, bool) @ 0xf06dc10 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
7. DB::InterpreterCreateQuery::setProperties(DB::ASTCreateQuery&) const @ 0xf06fa1a in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
8. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xf075664 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
9. DB::InterpreterCreateQuery::execute() @ 0xf07bd61 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
10. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xf6161e4 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf614863 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
12. DB::TCPHandler::runImpl() @ 0xfde46d2 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
13. DB::TCPHandler::run() @ 0xfdf7659 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
14. Poco::Net::TCPServerConnection::start() @ 0x1249674f in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
15. Poco::Net::TCPServerDispatcher::run() @ 0x124981da in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
16. Poco::PooledThread::run() @ 0x125d1f99 in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x125cdf8a in /usr/lib/debug/.build-id/d3/728012801ccf966515b1b6be77a02c9ae2a69e.debug
18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

and `allow_suspicious_low_cardinality_types` doesn't help anymore (same exception).

Actually `UUID` is the same as `FixedSting(16)`, and it definitely have sense to use it with LowCardinality.

### LINKED ISSUE #24018: toDecimal256 returns exception for values that should be in range.
**Describe the bug**
Documentation states the range of Decimal256(S) is (-10*(76-S), 10*(76-S)). toDecimal256(value,0) returns an error at 10\*10 and -10\*10 and values farther out.

**How to reproduce**
* ClickHouse server version 21.5.1 revision 54447
* Queries to run that lead to unexpected result
```
:) select toDecimal256('10000000000',0)

SELECT toDecimal256('10000000000', 0)

Query id: bb396e72-4fe6-4b9b-8319-9975e950d388


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.5.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Can't compare.

:) select toDecimal256(10000000000,0)

SELECT toDecimal256(10000000000, 0)

Query id: 13386ae2-535c-40f0-b99b-78e8e98793fb


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.5.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Can't compare.

:) select toDecimal256(-10000000000,0)

SELECT toDecimal256(-10000000000, 0)

Query id: ada9f101-e8af-4413-9dc8-fa83dc6d4036


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.5.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Can't compare.

:) select toDecimal256('-10000000000',0)

SELECT toDecimal256('-10000000000', 0)

Query id: 03efbf92-3fb3-44f5-9cd8-d9e0bd98be0e


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 21.5.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: Can't compare.
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Make big integers production ready. Add support for `UInt128` data type. Fix known issues with the `Decimal256` data type. Support big integers in dictionaries. Support `gcd`/`lcm` functions for big integers. Support big integers in array search and conditional functions. Support `LowCardinality(UUID)`. Support big integers in `generateRandom` table function and `clickhouse-obfuscator`. Fix error with returning `UUID` from scalar subqueries. This fixes #7834. This fixes #23936. This fixes #4176. This fixes #24018. This fixes #17828. Backward incompatible change: values of `UUID` type cannot be compared with integer. For example, instead of writing `uuid != 0` type `uuid != '00000000-0000-0000-0000-000000000000'`.

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Conversion from Float to Decimal is imprecise:

```
SELECT toDecimal256(0.1, 76)
```

is:
```
0.1000000000000000127244406382982157680441515146893321226564617167921968152000
```

must be:
```
0.1000000000000000055511151231257827021181583404541015625000000000000000000000
```

File: base/pcg-random/pcg_extras.hpp [hunk 1]
```diff
@@ -447,77 +447,14 @@ inline SrcIter uneven_copy(SrcIter src_first,
...
-                / ((GEN_SIZE / DEST_SIZE) + GEN_IS_SMALLER);
-                        //  this odd code ^^^^^^^^^^^^^^^^^ is work-around for
-                        //  a bug: http://llvm.org/bugs/show_bug.cgi?id=21287
-
-    if (FROM_ELEMS <= 1024) {
-        uint32_t buffer[FROM_ELEMS];
-        generator.generate(buffer, buffer+FROM_ELEMS);
-        uneven_copy(buffer, dest, dest+size);
-    } else {
-        uint32_t* buffer = static_cast<uint32_t*>(malloc(GEN_SIZE * FROM_ELEMS));
```
Comment (alexey-milovidov) [inline base/pcg-random/pcg_extras.hpp:483]: They did not check the return value of malloc.
I decided to remove this code for that offence.

**Comment by alexey-milovidov** [comment]
> Functional stateless tests flaky check (address) — Timeout, fail: 0, passed: 845 

Ok (timeout due to too many changed tests).

**Comment by alexey-milovidov** [comment]
> Stress test (thread) — Killed by signal (in clickhouse-server.log) 

https://github.com/ClickHouse/ClickHouse/issues/24010
