### PR TITLE
Fix function neighbor for LowCardinality argument.

### LINKED ISSUE #10333: neighbor + LowCardinality = wrong result
```
SELECT
    neighbor(n, -2) AS int,
    neighbor(s, -2) AS str,
    neighbor(lcs, -2) AS lowCstr
FROM
(
    SELECT
        number % 5 AS n,
        toString(n) AS s,
        CAST(s, 'LowCardinality(String)') AS lcs
    FROM numbers(10)
)

┌─int─┬─str─┬─lowCstr─┐
│   0 │     │         │
│   0 │     │         │
│   0 │ 0   │ 0       │
│   1 │ 1   │ 1       │
│   2 │ 2   │ 2       │
│   3 │ 3   │         │
│   4 │ 4   │         │
│   0 │ 0   │ 0       │
│   1 │ 1   │ 1       │
│   2 │ 2   │ 2       │
└─────┴─────┴─────────┘
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong result of function `neighbor` for `LowCardinality` argument. Fixes #10333

### CODE REVIEW

File: src/Functions/neighbor.cpp [hunk 1]
```diff
@@ -50,6 +50,8 @@ class FunctionNeighbor : public IFunction
 
     bool useDefaultImplementationForConstants() const override { return false; }
 
+    bool useDefaultImplementationForLowCardinalityColumns() const override { return false; }
```
Comment (alexey-milovidov) [inline src/Functions/neighbor.cpp:53]: What is the point? Why it was working wrong?

Comment (KochetovNicolai) [reply src/Functions/neighbor.cpp:53]: The optimization happened. Function was executed over dictionary

Comment (alexey-milovidov) [reply src/Functions/neighbor.cpp:53]: Could you please add a comment?

**Review by alexey-milovidov — APPROVED** [review]
