### PR TITLE
Set content-length for empty POST requests

### LINKED ISSUE #47888: Thousands of warnings for interserver communication
After https://github.com/ClickHouse/ClickHouse/pull/46681 there are thousands of errors in the CH logs due to a warning that was introduced there.

```
2023.03.15 12:39:13.058952 [ 30569 ] {} <Warning> HTTPServerRequest: Got an HTTP request with no content length and no chunked/multipart encoding, it may be impossible to distinguish graceful EOF from abnormal connection loss
```

After a few hours of running without queries (just as a replica attached to a cluster receiving new data and operating normally):
```
grep "no content length" clickhouse-server.log | wc -l
62490
```

This happens even with internal communication between servers where CH is both the server and the client. For example:

```
2023.03.22 13:02:47.642688 [ 112642 ] {} <Warning> HTTPServerRequest: Got an HTTP request with no content length and no chunked/multipart encoding, it may be impossible to distinguish graceful EOF from abnormal connection loss
2023.03.22 13:02:47.642794 [ 112642 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 192.168.1.200:51616, User-Agent: ClickHouse/23.3.1.2537, Content Type: , Transfer Encoding: identity, X-Forwarded-For: (none)
2023.03.22 13:02:47.642978 [ 112642 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fmany_tables2.source1%2Freplicas%2Fclickhouse-01&part=all_777_777_0&client_protocol_version=7&compress=false
2023.03.22 13:02:47.643044 [ 112642 ] {} <Trace> many_tables2.source1 (2eb7a2fd-74e0-40e6-9e9e-9911093ac0ea) (Replicated PartsService): Sending part all_777_777_0
2023.03.22 13:02:47.644051 [ 112642 ] {} <Debug> InterserverIOHTTPHandler: Done processing query
```

### LINKED ISSUE #47893: [Error] "Got an HTTP request with no content length" with valid headers
Hi!
ClickHouse version 23.2.4.12  had started to write warning logs:
```bash
2023.03.22 16:13:14.067399 [ 261 ] {} <Warning> HTTPServerRequest: Got an HTTP request with no content length and no chunked/multipart encoding, it may be impossible to distinguish graceful EOF from abnormal connection loss
```

How to reproduce:
The issue reproduces only in the cluster mode with Replicated tables.
I made  [docker-compose](https://github.com/mrsuh/clickhouse-cluster-test) file to test it.
```bash
git clone git@github.com:mrsuh/clickhouse-cluster-test.git && cd clickhouse-cluster-test
make config up
```

After starting, the database already has simple_table and replicated_table.
```sql
CREATE DATABASE IF NOT EXISTS db_test;

DROP TABLE IF EXISTS db_test.replicated_table;
CREATE TABLE IF NOT EXISTS db_test.replicated_table
(
    `name` String,
    `date` Date
)
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/db_test/replicated_table', '${SHARD}')
    PARTITION BY toYYYYMMDD(date)
    ORDER BY name;

DROP TABLE IF EXISTS db_test.simple_table;
CREATE TABLE IF NOT EXISTS db_test.simple_table
(
    `name` String,
    `date` Date
)
    ENGINE = MergeTree()
    PARTITION BY toYYYYMMDD(date)
    ORDER BY name;
```

Start listen to logs:
```bash
docker logs -f clickhouse01 2>&1 | grep "Got an HTTP request with no content length"
```

Insert query into replicated table make warning record.
```bash
echo "INSERT INTO db_test.replicated_table VALUES ('replicated', '2000-01-01')" | curl -H 'Transfer-Encoding: chunked' 'http://127.0.0.1:8123/' --data-binary @- -vvv
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8123 (#0)
> POST / HTTP/1.1
> Host: 127.0.0.1:8123
> User-Agent: curl/7.64.1
> Accept: */*
> Transfer-Encoding: chunked
> Content-Type: application/x-www-form-urlencoded
> 
> 49
* upload completely sent off: 80 out of 73 bytes
< HTTP/1.1 200 OK
< Date: Wed, 22 Mar 2023 13:16:21 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: clickhouse01
< Transfer-Encoding: chunked
< Keep-Alive: timeout=3
< X-ClickHouse-Summary: {"read_rows":"1","read_bytes":"21","written_rows":"1","written_bytes":"21","total_rows_to_read":"0","result_rows":"1","result_bytes":"21"}
< 
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
```

```bash
2023.03.22 16:13:14.067399 [ 261 ] {} <Warning> HTTPServerRequest: Got an HTTP request with no content length and no chunked/multipart encoding, it may be impossible to distinguish graceful EOF from abnormal connection loss
```

We sent a request with the header `-H 'Transfer-Encoding: chunked'`, but it looks like the function `getChunkedTransferEncoding()` not working.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/HTTP/HTTPServerRequest.cpp#L56

Can you help with it?

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Replaces https://github.com/ClickHouse/ClickHouse/pull/47903
Fixes https://github.com/ClickHouse/ClickHouse/issues/47893
Fixes https://github.com/ClickHouse/ClickHouse/issues/47888

### CODE REVIEW

File: src/Server/HTTP/HTTPServerRequest.cpp [hunk 1]
```diff
@@ -63,11 +63,9 @@ HTTPServerRequest::HTTPServerRequest(HTTPContextPtr context, HTTPServerResponse
     }
     else if (getMethod() != HTTPRequest::HTTP_GET && getMethod() != HTTPRequest::HTTP_HEAD && getMethod() != HTTPRequest::HTTP_DELETE)
     {
-        /// That check for has_body may be false-negative in rare cases, but it's okay
-        bool has_body = in->hasPendingData();
         stream = std::move(in);
-        if (!startsWith(getContentType(), "multipart/form-data") && has_body)
-            LOG_WARNING(&Poco::Logger::get("HTTPServerRequest"), "Got an HTTP request with no content length "
+        if (!startsWith(getContentType(), "multipart/form-data"))
+            LOG_WARNING(LogFrequencyLimiter(&Poco::Logger::get("HTTPServerRequest"), 10), "Got an HTTP request with no content length "
```
Comment (serxa) [inline src/Server/HTTP/HTTPServerRequest.cpp:68]: But `LogFrequencyLimiterIml` does not filter messages without a format string. Not sure how this message is converted into Poco::Message `message.getFormatString()`

Comment (tavplubix) [reply src/Server/HTTP/HTTPServerRequest.cpp:68]: This message has a "format string" with no parameters, so `message.getFormatString()` will return the message itself. Logging without a format string looks like this:
https://github.com/ClickHouse/ClickHouse/blob/4a5e4274f03f4d320b9e3d0c6315b38084255c8e/src/Dictionaries/CassandraHelpers.cpp#L57-L61

**Review by serxa — APPROVED** [review]

**Comment by tavplubix** [comment]
Integration tests - tests for backups are still flaky
Stateless tests (tsan) [1/5] - https://github.com/ClickHouse/ClickHouse/issues/47460
