### PR TITLE
Find big allocations without memory limits checks 

### LINKED ISSUE #48441: 00002_log_and_exception_messages_formatting is flaky
00002_log_and_exception_messages_formatting got some flaky runs:
https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTAzLTAyJyBhbmQgdGVzdF9uYW1lIGxpa2UgJyVsb2dfYW5kX2V4Y2VwdGlvbl9tZXNzYWdlc19mb3JtYXR0aW5nJScgYW5kIHN0YXR1cyAhPSAnT0snCm9yZGVyIGJ5IGNoZWNrX3N0YXJ0X3RpbWUgZGVzYw==

E.g.
- https://s3.amazonaws.com/clickhouse-test-reports/48434/7975df538e74e9487645ce7f4e9dab072cdf2151/stateless_tests__release_.html
- https://s3.amazonaws.com/clickhouse-test-reports/48422/ecdc3555787421e50e28f4f12c6dd499a4d5037c/stateless_tests__release_.html
- https://s3.amazonaws.com/clickhouse-test-reports/46589/949f7c1839160f73ca19d6f9190c705044d8f23d/stateless_tests__aarch64_.html

```
2023-04-05 06:01:46 --- /usr/share/clickhouse-test/queries/0_stateless/00002_log_and_exception_messages_formatting.reference	2023-04-05 05:04:31.407900193 -0800
2023-04-05 06:01:46 +++ /tmp/clickhouse-test/0_stateless/00002_log_and_exception_messages_formatting.stdout	2023-04-05 06:01:46.923013277 -0800
2023-04-05 06:01:46 @@ -2,7 +2,7 @@
2023-04-05 06:01:46  runtime exceptions	0.05
2023-04-05 06:01:46  messages shorter than 10	10
2023-04-05 06:01:46  messages shorter than 16	40
2023-04-05 06:01:46 -exceptions shorter than 30	120
2023-04-05 06:01:46 +exceptions shorter than 30	121
2023-04-05 06:01:46  noisy messages	0.3
2023-04-05 06:01:46  noisy Trace messages	0.16
2023-04-05 06:01:46  noisy Debug messages	0.09
2023-04-05 06:01:46 
2023-04-05 06:01:46 
2023-04-05 06:01:46 Settings used in the test: --max_insert_threads=0 --group_by_two_level_threshold=62815 --group_by_two_level_threshold_bytes=17337780 --distributed_aggregation_memory_efficient=1 --fsync_metadata=1 --output_format_parallel_formatting=0 --input_format_parallel_parsing=1 --min_chunk_bytes_for_parallel_parsing=4946821 --max_read_buffer_size=600032 --prefer_localhost_replica=1 --max_block_size=15013 --max_threads=24 --optimize_or_like_chain=1 --optimize_read_in_order=1 --read_in_order_two_level_merge_threshold=23 --optimize_aggregation_in_order=1 --aggregation_in_order_max_block_bytes=10182998 --min_compress_block_size=841738 --max_compress_block_size=2415571 --use_uncompressed_cache=1 --min_bytes_to_use_direct_io=1 --min_bytes_to_use_mmap_io=1 --local_filesystem_read_method=pread --remote_filesystem_read_method=threadpool --local_filesystem_read_prefetch=0 --remote_filesystem_read_prefetch=1 --compile_expressions=0 --compile_aggregate_expressions=1 --compile_sort_description=0 --merge_tree_coarse_index_granularity=21 --optimize_distinct_in_order=0 --optimize_sorting_by_input_stream_properties=1 --http_response_buffer_size=4184980 --http_wait_end_of_query=True --enable_memory_bound_merging_of_aggregation_results=0
2023-04-05 06:01:46 
2023-04-05 06:01:46 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization=1.0 --prefer_fetch_merged_part_size_threshold=7738159148 --vertical_merge_algorithm_min_rows_to_activate=1000000 --vertical_merge_algorithm_min_columns_to_activate=100 --allow_vertical_merges_from_compact_to_wide_parts=0 --min_merge_bytes_to_use_direct_io=10737418240 --index_granularity_bytes=6130931 --merge_max_block_size=20409 --index_granularity=3044 --min_bytes_for_wide_part=77717572 --marks_compress_block_size=66387 --primary_key_compress_block_size=23943
2023-04-05 06:01:46 
2023-04-05 06:01:46 Database: test_sw44p432
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

About big allocations and OOMs: https://github.com/ClickHouse/ClickHouse/pull/48178#issuecomment-1489144335 

Also it fixes `00002_log_and_exception_messages_formatting`: https://s3.amazonaws.com/clickhouse-test-reports/0/d0ba1e76bfdef462ae5fd7b652105b4abf780251/stateless_tests__release_.html
(the test has found non-informative exception messages added in https://github.com/ClickHouse/ClickHouse/pull/43858#discussion_r1157495310, but it was impossible to understand from the test output, let's improve it)

Fixes https://github.com/ClickHouse/ClickHouse/issues/48441

### CODE REVIEW

**Review by novikd — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]

File: src/Common/MemoryTracker.cpp [hunk 1]
```diff
@@ -82,6 +82,26 @@ inline std::string_view toDescription(OvercommitResult result)
...
+    if (size < 0)
+        return;
+
+    constexpr Int64 threshold = 16 * 1024 * 1024;   /// The choice is arbitrary (maybe we should decrease it)
+    if (size < threshold)
+        return;
+
+    MemoryTrackerBlockerInThread blocker;
+    LOG_TRACE(&Poco::Logger::get("MemoryTracker"), "Too big allocation ({} bytes) without checking memory limits, "
+                                                   "it may lead to OOM. Stack trace: {}", size, StackTrace().toString());
```
Comment (azat) [inline src/Common/MemoryTracker.cpp:99]: Interesting idea! Maybe it also worth to add a check to `{stateless/stress}/run.sh` for this pattern?

**Comment by tavplubix** [comment]
Integration tests (asan) [4/6] - https://github.com/ClickHouse/ClickHouse/issues/45435
Stateless tests flaky check (asan) - it's okay, not enough statistics for the test
