### PR TITLE
Fix mutation failure when MATERIALIZED column depends on EPHEMERAL column

### LINKED ISSUE #84981: Lightweight updates fail when a table has a MATERIALIZED column whose value depends on an EPHEMERAL column
### Company or project name

n/a

### Describe the unexpected behaviour

Attempting to perform a lightweight update on a table with a `MATERIALIZED` column which depends on an `EPHEMERAL` column results in an error that the `EPHEMERAL` column does not exist. This is unexpected since the value of the `EPHEMERAL` column is not relevant for the update being performed.

### Which ClickHouse versions are affected?

25.7

### How to reproduce

https://fiddle.clickhouse.com/8d3f4fc2-a3f3-47c9-b3e4-e394c1f33dd6

```
CREATE TABLE t1 (c1 String EPHEMERAL, c2 String MATERIALIZED tryBase64Decode(c1), c3 BOOLEAN)
ENGINE=MergeTree
ORDER BY tuple()
SETTINGS enable_block_number_column=1, enable_block_offset_column=1;

INSERT INTO t1(c1, c3) VALUES ('SGVsbG8gV29ybGQh', true);

SET asterisk_include_materialized_columns = 1;

SELECT * FROM t1;

SET allow_experimental_lightweight_update = 1;

UPDATE t1 SET c3 = false WHERE c2='Hello World!';

SELECT * FROM t1;
```

### Expected behavior

Lightweight update should complete without error.

### Error message and/or stacktrace

```
Received exception from server (version 25.7.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'c1' while processing: 'tryBase64Decode(c1)', required columns: 'c1', available columns: '_block_number' '_row_exists' '_part_data_version' '_part_offset' '_disk_name' '_sample_factor' '_part_starting_offset' '_part_index' '_part' '_part_granule_offset' '_block_offset' '_part_uuid' 'c3' '_partition_id' 'c2'. (UNKNOWN_IDENTIFIER)
(query: UPDATE t1 SET c3 = false WHERE c2='Hello World!';)
```

### Additional context

Replacing the `MATERIALIZED` column with a `DEFAULT` column eliminates the error, but this changes the semantics of the column.

This appears to be the same failure mode as #68839 and #71793.

### PR DESCRIPTION
**Pull request by Onyx2406**
### Changelog category (leave one):

Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):

Fixed `ALTER TABLE UPDATE/DELETE` failing with `Missing columns` error when a table has a MATERIALIZED column whose expression depends on an EPHEMERAL column.

### Documentation entry for user-facing changes

- [x] Documentation is not required (bug fix)

### What this PR does

When a table has:
```sql
c1 String EPHEMERAL,
c2 String MATERIALIZED tryBase64Decode(c1),
c3 Bool
```

Running `ALTER TABLE t UPDATE c3 = false WHERE c2 = 'Hello World!'` fails with:
```
Missing columns: 'c1' while processing: 'tryBase64Decode(c1)'
```

**Root cause**: During mutations, `MutationsInterpreter::prepare()` tries to analyze MATERIALIZED column expressions to detect dependencies. It calls `TreeRewriter::analyze()` with `all_columns` which excludes EPHEMERAL columns (they're not physical/on-disk). When the MATERIALIZED expression references an EPHEMERAL column, TreeRewriter throws because it can't find it.

**Fix**: Before analyzing MATERIALIZED expressions, include EPHEMERAL columns in the analysis set (so TreeRewriter can resolve them), then check if any required source columns are EPHEMERAL. If so, skip recalculating that MATERIALIZED column — its on-disk value is already correct from INSERT time, and we can't read EPHEMERAL data from disk anyway.

### Changes (32 insertions, 1 file + tests)

**`src/Interpreters/MutationsInterpreter.cpp`**:
- Collect EPHEMERAL column names from `columns_desc`
- Build `all_columns_with_ephemeral` that includes EPHEMERAL columns for TreeRewriter analysis
- After analyzing each MATERIALIZED expression, check if it depends on any EPHEMERAL column
- If yes, skip adding it to `column_to_affected_materialized` (don't try to recalculate it)

### Test plan

- [x] New stateless test `04044_mutation_ephemeral_materialized.sql`:
  - Creates table with EPHEMERAL + MATERIALIZED + regular columns
  - INSERT with EPHEMERAL value, verify MATERIALIZED computed correctly
  - UPDATE regular column WHERE MATERIALIZED = value (was failing)
  - DELETE WHERE MATERIALIZED = value (was failing)
  - Verifies data correctness after each operation
- [x] CI (full test suite)

Fixes #84981
Related: #68839, #71793

---

> [!NOTE]
> **Medium Risk**
> Touches mutation preparation logic for MATERIALIZED dependency analysis, which can affect which columns get recomputed during `ALTER UPDATE/DELETE`. While scoped, incorrect dependency handling could lead to missed recalculations or stale on-disk values.
> 
> **Overview**
> Fixes `ALTER TABLE ... UPDATE/DELETE` failures when a `MATERIALIZED` column expression references an `EPHEMERAL` column by including ephemeral columns in the dependency-analysis input to `TreeRewriter`.
> 
> During mutation planning, `MATERIALIZED` columns that depend on `EPHEMERAL` inputs are now **excluded from recalculation**, with a warning logged if a mixed dependency (ephemeral + regular) could become stale. Adds a stateless test (`04044_mutation_ephemeral_materialized.sql`) covering update/delete, mixed materialized columns, mixed-dependency staleness behavior, and the lightweight update path.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 7afd5ad1b43001b10a4bcb456960b6b87fa3b56e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.4.1.179`

### CODE REVIEW

File: tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql [hunk 1]
```diff
@@ -0,0 +1,51 @@
+DROP TABLE IF EXISTS t_ephemeral_materialized;
+
+CREATE TABLE t_ephemeral_materialized
```
Comment (tiandiwonder) [inline tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql:6]: add a test covering the lightweight update case

File: src/Interpreters/MutationsInterpreter.cpp [hunk 2]
```diff
@@ -677,15 +677,51 @@ void MutationsInterpreter::prepare(bool dry_run)
...
+                for (const auto & dep : required)
+                {
+                    if (ephemeral_columns.contains(dep))
+                    {
+                        depends_on_ephemeral = true;
+                        break;
+                    }
+                }
+
+                if (depends_on_ephemeral)
```
[the remark this answers is not in the document]
Comment (tiandiwonder) [reply src/Interpreters/MutationsInterpreter.cpp]: When a MATERIALIZED column depends on **both** an ephemeral and a non-ephemeral column — e.g., `c2 = MATERIALIZED concat(tryBase64Decode(c1), '-', c3)` — and a mutation updates `c3`, the code silently skips c2. The result is that c2 retains the INSERT-time value of c3 while c3 has been updated on disk. This data inconsistency is invisible to the user.

At the `continue` point, all necessary information is already in scope (`required`, `ephemeral_columns`, `updated_columns`) to detect this specific case: a non-ephemeral dependency of the skipped MATERIALIZED column is being updated. A `LOG_WARNING` should fire only in this situation, not on the normal case where MATERIALIZED depends only on ephemeral columns:

```cpp
if (depends_on_ephemeral)
{
    bool affected_non_ephemeral_dep = std::any_of(required.begin(), required.end(),
        [&](const auto & dep)
        {
            return !ephemeral_columns.contains(dep) && updated_columns.contains(dep);
        });

    if (affected_non_ephemeral_dep)
        LOG_WARNING(logger,
            "MATERIALIZED column '{}' depends on both EPHEMERAL column(s) and "
            "regular column(s) that are being updated. Its value will NOT be "
            "recalculated during this mutation — the on-disk value may become "
            "inconsistent. To fix this, re-INSERT the affected rows.",
            column.name);

    continue;
}
```

File: src/Interpreters/MutationsInterpreter.cpp [hunk 3]
```diff
@@ -677,15 +677,51 @@ void MutationsInterpreter::prepare(bool dry_run)
...
+        /// Include ephemeral columns in the analysis set so TreeRewriter can resolve
+        /// MATERIALIZED expressions that reference them (we need to detect the dependency,
+        /// not actually read the data).
+        NamesAndTypesList all_columns_with_ephemeral = all_columns;
+        if (!ephemeral_columns.empty())
+        {
+            for (const auto & column : columns_desc.getEphemeral())
+                all_columns_with_ephemeral.push_back(column);
+        }
+
```
Comment (tiandiwonder) [inline src/Interpreters/MutationsInterpreter.cpp]: Two separate loops both iterate ephemeral columns. They can be combined into one pass, removing the `if (!ephemeral_columns.empty())` guard (which is a no-op since the loop body handles the empty case naturally):

```cpp
NamesAndTypesList all_columns_with_ephemeral = all_columns;
std::unordered_set<String> ephemeral_columns;
for (const auto & col : columns_desc.getEphemeral())
{
    ephemeral_columns.insert(col.name);
    all_columns_with_ephemeral.push_back(col);
}
```

File: tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+
+-- Mixed case: table with BOTH ephemeral-dependent AND non-ephemeral MATERIALIZED columns.
+-- Updating the source of the non-ephemeral one should recalculate it without
+-- trying to recalculate the ephemeral-dependent one.
+DROP TABLE IF EXISTS t_mixed_materialized;
+
+CREATE TABLE t_mixed_materialized
+(
+    c1 String EPHEMERAL,
+    c2 String MATERIALIZED tryBase64Decode(c1),
```
Comment (tiandiwonder) [inline tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql]: Mixed-dependency MATERIALIZED column** (EPHEMERAL + ordinary in same expression):

```sql
CREATE TABLE t_mixed_dep (
    c1 String EPHEMERAL,
    c3 String,
    c2 String MATERIALIZED concat(tryBase64Decode(c1), '-', c3)
) ENGINE = MergeTree ORDER BY tuple();
```

File: tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql [hunk 5]
```diff
@@ -0,0 +1,94 @@
+-- Tags: no-fasttest
```
Comment (tiandiwonder) [inline tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql]:
```sql
-- Tags: no-fasttest
-- no-fasttest: requires enable_lightweight_update (enable_block_number_column) not available in fasttest
```

File: tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+ALTER TABLE t_mixed_dep UPDATE c3 = 'world' WHERE c3 = 'hello';
+-- c2 stays stale (Hello World!-hello) because it depends on EPHEMERAL c1 which cannot be re-read
+SELECT c2, c3 FROM t_mixed_dep;
+
+DROP TABLE t_mixed_dep;
+
+-- Case 4: Lightweight delete path
+DROP TABLE IF EXISTS t_ephemeral_lightweight;
+
+CREATE TABLE t_ephemeral_lightweight
```
Comment (tiandiwonder) [inline tests/queries/0_stateless/04044_mutation_ephemeral_materialized.sql]: enable setting for table and use update(delete will not cover current code path).
```sql
-- Case 4: lightweight UPDATE path — the actual scenario from issue #84981
DROP TABLE IF EXISTS t_ephemeral_lwu;

CREATE TABLE t_ephemeral_lwu
(
    c1 String EPHEMERAL,
    c2 String MATERIALIZED tryBase64Decode(c1),
    c3 Bool
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS enable_block_number_column = 1, enable_block_offset_column = 1;

INSERT INTO t_ephemeral_lwu (c1, c3) VALUES ('SGVsbG8gV29ybGQh', true);

SET enable_lightweight_update = 1;
UPDATE t_ephemeral_lwu SET c3 = false WHERE c2 = 'Hello World!';

SELECT c2, c3 FROM t_ephemeral_lwu;

DROP TABLE t_ephemeral_lwu;
```

File: src/Interpreters/MutationsInterpreter.cpp [hunk 7]
```diff
@@ -677,15 +677,59 @@ void MutationsInterpreter::prepare(bool dry_run)
...
-                auto syntax_result = TreeRewriter(context).analyze(query, all_columns);
-                for (const auto & dependency : syntax_result->requiredSourceColumns())
+                replaceSubcolumnsToGetSubcolumnFunctionInQuery(query, all_columns_with_ephemeral);
+                auto syntax_result = TreeRewriter(context).analyze(query, all_columns_with_ephemeral);
+                auto required = syntax_result->requiredSourceColumns();
+
+                /// If the MATERIALIZED expression depends on any EPHEMERAL column,
+                /// skip it — EPHEMERAL columns are only available during INSERT
+                /// and cannot be read from disk during mutations.
+                bool depends_on_ephemeral = false;
```
Comment (tiandiwonder) [inline src/Interpreters/MutationsInterpreter.cpp]: We can make it short as the following(keep comments):
```
auto required_columns = syntax_result->requiredSourceColumns();

  if (std::ranges::any_of(required_columns,
      [&](const auto & dep) { return ephemeral_columns.contains(dep); }))
  {
      if (std::ranges::any_of(required_columns, [&](const auto & dep)
          { return !ephemeral_columns.contains(dep) && updated_columns.contains(dep); }))
          LOG_WARNING(logger, "MATERIALIZED column '{}' depends on both EPHEMERAL and regular "
              "columns that are being updated. Its value will NOT be recalculated "
              "during this mutation — the on-disk value may become inconsistent. "
              "To fix this, re-INSERT the affected rows.", column.name);
      continue;
  }
```

File: src/Interpreters/MutationsInterpreter.cpp [hunk 8]
```diff
@@ -677,15 +677,59 @@ void MutationsInterpreter::prepare(bool dry_run)
...
             if (column.default_desc.kind == ColumnDefaultKind::Materialized && available_columns_set.contains(column.name))
             {
                 auto query = column.default_desc.expression->clone();
-                /// Replace all subcolumns to the getSubcolumn() to get only top level columns as required source columns.
-                replaceSubcolumnsToGetSubcolumnFunctionInQuery(query, all_columns);
-                auto syntax_result = TreeRewriter(context).analyze(query, all_columns);
-                for (const auto & dependency : syntax_result->requiredSourceColumns())
+                replaceSubcolumnsToGetSubcolumnFunctionInQuery(query, all_columns_with_ephemeral);
+                auto syntax_result = TreeRewriter(context).analyze(query, all_columns_with_ephemeral);
+                auto required = syntax_result->requiredSourceColumns();
```
Comment (tiandiwonder) [inline src/Interpreters/MutationsInterpreter.cpp]: use required_columns.

**Review by tiandiwonder — COMMENTED** [review]
please fix the test failure.
