### PR TITLE
Fix rename Distributed table

### LINKED ISSUE #24971: Unable to move Distributed table from Ordinary database to Atomic
**Describe the bug**

Can't rename distributed table and move it from Ordinary to Atomic database

**How to reproduce**

```
CREATE DATABASE atomic_database ON CLUSTER cluster_name ENGINE = Atomic
```
```
CREATE DATABASE ordinary_database ON CLUSTER cluster_name ENGINE = Ordinary
```

```
CREATE TABLE ordinary_database.t ON CLUSTER cluster_name
...
ENGINE = ReplicatedMergeTree(...)
...
```

```
CREATE TABLE ordinary_database.distributed_table ON CLUSTER cluster_name AS ordinary_database.t 
ENGINE = Distributed(cluster_name, ordinary_database, t)
```

```
RENAME TABLE ordinary_database.distributed_table TO atomic_database.distributed_table

Query id: 7bd2101e-f78a-4584-8374-6e44a0bbf23f


0 rows in set. Elapsed: 0.011 sec.

Received exception from server (version 21.5.6):
Code: 1000. DB::Exception: Received from clickhouse-server:9000. DB::Exception: File not found: /var/lib/clickhouse/data/ordinary_database/distributed_table.
```
But 
```
ls -lh /var/lib/clickhouse/data/ordinary_database
total 0
drwxr-x---  2 ...  staff    64B Jun  4 18:19 distributed_table
drwxr-x---  4 ...  staff   128B Jun  4 18:18 t
```

**Does it reproduce on recent release?**
Checked on 21.5.6.6 version

**Expected behavior**

For example, renaming _Views_ works perfectly. I expect the same from the _Distributed_ table

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed `No such file or directory` error on moving `Distributed` table between databases. Fixes #24971

### CODE REVIEW

File: tests/queries/0_stateless/01155_rename_move_materialized_view.sql [hunk 1]
```diff
@@ -27,13 +31,14 @@ DROP DATABASE test_01155_ordinary;
 USE default;
 
 INSERT INTO test_01155_atomic.src VALUES ('after moving tables');
-SELECT 2, substr(_table, 1, 10), s FROM merge('test_01155_atomic', '') ORDER BY _table, s; -- { serverError 81 }
+SELECT materialize(2), substr(_table, 1, 10), s FROM merge('test_01155_atomic', '') ORDER BY _table, s; -- { serverError 81 }
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/01155_rename_move_materialized_view.sql:34]: How materialization is connected to the issue of this PR?

Comment (tavplubix) [reply tests/queries/0_stateless/01155_rename_move_materialized_view.sql:34]: Test has found another bug (`Cannot convert column `1` because it is non constant in source stream but must be constant in result`), `materialize()` is a workaround

**Review by nikitamikhaylov — APPROVED** [review]
