### PR TITLE
Don't throw exception for unexpected values in enum during to string conversion

### LINKED ISSUE #25806: Setting use_join_nulls to 1 may throw an exception unexpectedly
**Describe the bug**

A combination of `use_join_nulls=1`, a `Nullable(enum)` column, `OUTER JOIN`, and `toString()` may throw an exception while generating a result.

**Does it reproduce on recent release?**

This happens on 21.6.3 stable.

**How to reproduce**

With the following setup:

```sql
CREATE TABLE a (
  key  String
) ENGINE=MergeTree ORDER BY key;

CREATE TABLE b (
  key  String,
  data Nullable(Enum16('a'=1, 'b'=2))
) ENGINE=MergeTree ORDER BY key;

INSERT INTO a VALUES('x');
INSERT INTO a VALUES('y');

INSERT INTO b VALUES('x', 'a');
```

This query appears to work correctly:
```
SELECT
	key, data
FROM a
ANY LEFT OUTER JOIN b USING (key)
FORMAT JSONCompact
SETTINGS join_use_nulls = 1;
```

```
{
        "meta":
        [
                {
                        "name": "key",
                        "type": "String"
                },
                {
                        "name": "data",
                        "type": "Nullable(Enum16('a' = 1, 'b' = 2))"
                }
        ],
        "data":
        [
                ["y", null],                                                                                                                                                                                                
                ["x", "a"]                                                                                                                                                                                                     
        ],
        "rows": 2,
        "statistics":
        {
                "elapsed": 0.002955967,
                "rows_read": 3,
                "bytes_read": 33
        }
}
```

But it throws an exception when `toString()` is applied to the joined column:

```sql
SELECT
	key, toString(data)
FROM a
LEFT OUTER JOIN b USING (key)
FORMAT JSONCompact
SETTINGS join_use_nulls = 1;
```

```
{
        "meta":
        [
                {
                        "name": "key",
                        "type": "String"
                },
                {
                        "name": "toString(data)",
                        "type": "Nullable(String)"
                }
        ],

        "data":
        [
                ["x", "a"]                                                                                                                                                                                                      Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
1 rows in set. Elapsed: 0.003 sec.

Received exception from server (version 21.6.3):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected value 0 in enum: while executing 'FUNCTION toString(data :: 1) -> toString(data) Nullable(String) : 2'.
```

**Expected behavior**

It produces a string `NULL` without throwing an exception.

### PR DESCRIPTION
**Pull request by vdimir**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Don't throw exception in `toString` for nullable enum, close #25806

### CODE REVIEW

**Review by kitaisreal — APPROVED** [review]

**Review by kitaisreal — APPROVED** [review]

File: src/Functions/FunctionsConversion.h [hunk 1]
```diff
@@ -683,12 +722,23 @@ struct ConvertImpl<FromDataType, std::enable_if_t<!std::is_same_v<FromDataType,
 
             for (size_t i = 0; i < size; ++i)
             {
-                FormatImpl<FromDataType>::execute(vec_from[i], write_buffer, &type, time_zone);
+                if (null_map)
```
Comment (kitaisreal) [inline src/Functions/FunctionsConversion.h:725]: @vdimir it seems that because of this check performance for toString for non nullable type is affected. My proposal is to move this check if out of hot loop.
And check if that helps.
```c++
if (null_map)
{
    for (size_t i = 0; i < size; ++i)
    {
         bool is_ok = FormatImpl<FromDataType>::template execute<bool>(vec_from[i], write_buffer, &type, time_zone);
         null_map->getData()[i] |= !is_ok;
    }
}
else
{
    for (size_t i = 0; i < size; ++i)
    {
          FormatImpl<FromDataType>::template execute<void>(vec_from[i], write_buffer, &type, time_zone);
    }
}
```

**Review by kitaisreal — CHANGES_REQUESTED** [review]

**Review by kitaisreal — APPROVED** [review]
