### PR TITLE
Fix invalid cast of nullable type when nullable primary key is used

### LINKED ISSUE #31075: Code: 43. DB::Exception: Nested type Nullable(UInt32) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT) (version 21.10.2.15 (official build))
> You have to provide the following information whenever possible.

**Describe what's wrong**

When the table has a `Nullable(DateTime)` column, the select sql can not be executed successfully

there is only 1 row in this talbe

image

the column `pay_time` is `Nullable(DateTime)`

image

this can success

```sql
select * from dou_ch_item_orders final where pay_time is not null;
```

this failed

```sql
select * from dou_ch_item_orders final where pay_time between '2021-11-03 00:00:00' and '2021-11-03 23:59:59';
```

In version `21.10.2.15`, the second sql  went wrong.

深度截图_选择区域_20211104173441

In version `21.8.4.51`, all the sqls are executed successfully

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by amosbird**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix invalid cast of nullable type when nullable primary key is used. This fixes https://github.com/ClickHouse/ClickHouse/issues/31075

Detailed description / Documentation draft:
.

### CODE REVIEW

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 1]
```diff
@@ -1316,18 +1316,18 @@ bool KeyCondition::tryParseAtomFromAST(const ASTPtr & node, ContextPtr context,
...
                             {nullptr, key_expr_type, ""},
                             {DataTypeString().createColumnConst(1, common_type_maybe_nullable->getName()), common_type_maybe_nullable, ""}};
                         FunctionOverloadResolverPtr func_builder_cast = CastInternalOverloadResolver<CastType::nonAccurate>::createImpl();
                         auto func_cast = func_builder_cast->build(arguments);
 
                         /// If we know the given range only contains one value, then we treat all functions as positive monotonic.
-                        if (!func_cast || (!single_point && !func_cast->hasInformationAboutMonotonicity()))
+                        if (!single_point && !func_cast->hasInformationAboutMonotonicity())
                             return false;
-                        chain.push_back(func_cast);
```
Comment (CurtizJ) [inline src/Storages/MergeTree/KeyCondition.cpp:1330]: Why remove it from chain? Looks like it breaks test with `Date/DateTime`.

Comment (amosbird) [reply src/Storages/MergeTree/KeyCondition.cpp:1330]: I have no idea why that line of code gets removed... I'll add it back.

**Comment by CurtizJ** [comment]
@Mergifyio update

**Review by CurtizJ — APPROVED** [review]
