### PR TITLE
Throw an exception when the parquet batch size is set to 0

### LINKED ISSUE #78392: output_format_parquet_batch_size = 0 hangs
### Describe the bug

Setting `output_format_parquet_batch_size = 0`, gives an infinite loop while writing to a Parquet file. Maybe it shouldn't be allowed.

### How to reproduce

Run:

```sql
SET output_format_parquet_batch_size = 0;
INSERT INTO TABLE FUNCTION file('<path to file>', 'Parquet', 'c0 Int') SELECT 0; --hangs
```

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by daryawessely**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Throw an exception when the parquet batch size is set to 0. Previously when output_format_parquet_batch_size = 0 ClickHouse would hang. Now this behavior is fixed.

This fixes https://github.com/ClickHouse/ClickHouse/issues/78392

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Formats/FormatFactory.cpp [hunk 1]
```diff
@@ -207,6 +207,12 @@ FormatSettings getFormatSettings(const ContextPtr & context, const Settings & se
     format_settings.parquet.use_custom_encoder = settings[Setting::output_format_parquet_use_custom_encoder];
     format_settings.parquet.parallel_encoding = settings[Setting::output_format_parquet_parallel_encoding];
     format_settings.parquet.data_page_size = settings[Setting::output_format_parquet_data_page_size];
+    if (settings[Setting::output_format_parquet_batch_size] == 0)
+    {
+        throw DB::Exception(
+            ErrorCodes::BAD_ARGUMENTS,
+            "Invalid value for setting 'output_format_parquet_batch_size': must be greater than 0");
+    }
```
Comment (Avogar) [inline src/Formats/FormatFactory.cpp:215]: Instead of explicit check here we can just use type `NonZeroUInt64` for this setting in `FormatFactorySettings.h`. The check will happend when we set the setting.

**Comment by Avogar** [comment]
There is a problem in ClickHouse build. Seems like we have to add `NonZeroUInt64` to `*_SETTINGS_SUPPORTED_TYPES` macros in some places like `ObjectStorageQueueSettings.h`/`KafkaSettings.h`/etc. Do you have an ability to build the binary locally to fix it? If no, no problem, I can do it.

**Comment by daryawessely** [comment]
no worries @Avogar giving it another try now, thanks!
