### PR TITLE
Fix inconsistent AST formatting for CREATE ROW POLICY with alias

### LINKED ISSUE #99314: Inconsistent AST formatting with row policy
### Describe the bug

Easy cc @alexey-milovidov and @george-larionov 

### How to reproduce

Run:
```sql
CREATE ROW POLICY p0 ON t0 USING (1 AS a);
```

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Inconsistent AST formatting: the query:
CREATE ROW POLICY p0 ON t0 FOR SELECT USING 1 AS a
cannot parse query back from CREATE ROW POLICY p0 ON t0 USING (1 AS a);'.
<Fatal> : Format string: 'Inconsistent AST formatting: the query:
{}
cannot parse query back from {}'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113:14: Poco::Exception::Exception(String&&, int) @ 0x0000000026af78b3
1. src/Common/Exception.cpp:139:7: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000016205329
2. src/Common/Exception.h:171:100: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000e26ab94
3. src/Common/Exception.h:57:54: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000e26a691
4. src/Common/Exception.h:189:77: DB::Exception::Exception<String&, std::basic_string_view<char, std::char_traits<char>>&>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type>, String&, std::basic_string_view<char, std::char_traits<char>>&) @ 0x000000001c950106
5. src/Interpreters/executeQuery.cpp:1221:31: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, boost::intrusive_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001c9445a0
6. src/Interpreters/executeQuery.cpp:2104:11: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c93a463
7. src/Server/TCPHandler.cpp:788:68: DB::TCPHandler::runImpl() @ 0x00000000200ae158
8. src/Server/TCPHandler.cpp:2926:9: DB::TCPHandler::run() @ 0x00000000200c97e4
9. base/poco/Net/src/TCPServerConnection.cpp:40:3: Poco::Net::TCPServerConnection::start() @ 0x0000000026badd8e
10. base/poco/Net/src/TCPServerDispatcher.cpp:115:42: Poco::Net::TCPServerDispatcher::run() @ 0x0000000026bae3d2
11. base/poco/Foundation/src/ThreadPool.cpp:205:14: Poco::PooledThread::run() @ 0x0000000026b4e0bf
12. base/poco/Foundation/src/Thread_POSIX.cpp:341:27: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000026b4b74f
13. start_thread @ 0x000000000009caa4
14. __clone3 @ 0x0000000000129c6c
```

### PR DESCRIPTION
**Pull request by george-larionov**
Resolves #99314

Use `ParserExpressionWithOptionalAlias` instead of `ParserExpression` so that aliases are properly consumed when re-parsing filter expressions.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Version info
- Merged into: `26.3.1.768`

### CODE REVIEW

File: tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference [hunk 1]
```diff
@@ -82,3 +82,7 @@ Original:          EXPLAIN AST (SELECT 1) UNION ALL (SELECT 2) SETTINGS max_thre
 format(original):  EXPLAIN AST (SELECT 1) UNION ALL (SELECT 2) SETTINGS max_threads = 1 INTO OUTFILE '/dev/null' FORMAT `Null`
 format(formatted): EXPLAIN AST (SELECT 1) UNION ALL (SELECT 2) SETTINGS max_threads = 1 INTO OUTFILE '/dev/null' FORMAT `Null`
 
+Original:          CREATE ROW POLICY p0 ON t0 USING (1 AS a)
+format(original):  CREATE ROW POLICY p0 ON t0 FOR SELECT USING 1 AS a
+format(formatted): CREATE ROW POLICY p0 ON t0 FOR SELECT USING 1 AS a
```
Comment (vitlibar) [inline tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference]: What was the output here with the original `ParserExpression parser`?

Comment (george-larionov) [reply tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference]: The first formatting was the same (because of the parentheses) but the second formatting failed with:

```
Code: 62. DB::Exception: Syntax error (query): failed at position 50 (a): a
. Expected one of: RESTRICTIVE, PERMISSIVE, end of query. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. /home/ubuntu/ch1/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113:16: std::exception::capture() @ 0x00000000123f0f62
1. /home/ubuntu/ch1/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:85:5: std::exception::exception[abi:se210105]() @ 0x00000000123f0f2d
2. /home/ubuntu/ch1/ClickHouse/base/poco/Foundation/src/Exception.cpp:31:12: Poco::Exception::Exception(String&&, int) @ 0x000000003848bda0
3. /home/ubuntu/ch1/ClickHouse/src/Common/Exception.cpp:139:7: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001c2da8b1
4. /home/ubuntu/ch1/ClickHouse/src/Common/Exception.h:170:105: DB::Exception::Exception(String const&, int, String, bool) @ 0x000000001a7effcc
5. /home/ubuntu/ch1/ClickHouse/src/Common/Exception.h:178:16: DB::Exception::createDeprecated(String const&, int, bool) @ 0x000000001c49e1e4
6. /home/ubuntu/ch1/ClickHouse/src/Parsers/parseQuery.cpp:416:11: DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long, unsigned long) @ 0x000000002ea64907
7. /home/ubuntu/ch1/ClickHouse/programs/format/Format.cpp:264:30: mainEntryClickHouseFormat(int, char**) @ 0x000000001c7c9826
8. /home/ubuntu/ch1/ClickHouse/programs/main.cpp:400:21: main @ 0x000000001234a8b2
9. __libc_start_call_main @ 0x000000000002a1ca
10. __libc_start_main_alias_1 @ 0x000000000002a28b
11. _start @ 0x000000001233fcae
 (version 26.3.1.1)
```

**Comment by george-larionov** [comment]
Ok, it seems the simple fix does not work, since it gets in the way of queries such as `CREATE ROW POLICY 02131_filter_1 ON 02131_rqtable USING x=1 AS permissive TO ALL`. The `AS permissive` is no longer accepted. I will think of a different way to resolve the formatting inconsistency. Perhaps we should ban aliases in such statements and only allow the special `AS {PERMISSIVE | RESTRICTIVE}` syntax.

File: src/Parsers/Access/ParserCreateRowPolicyQuery.cpp [hunk 2]
```diff
@@ -66,6 +72,22 @@ namespace
             if (!parser.parse(pos, x, expected))
                 return false;
 
+            auto has_alias = [](this auto const& self, const ASTPtr & ast)->bool
```
Comment (vitlibar) [inline src/Parsers/Access/ParserCreateRowPolicyQuery.cpp]: This doesn't look good

File: tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference (hunk 1 above)
Comment (vitlibar) [reply tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference]: Maybe it's better to keep parsing as is, but fix formatting to make it format any top-level alias with parentheses, so it could be parsed back:

```
CREATE ROW POLICY p0 ON t0 FOR SELECT USING (1 AS a)
```

Comment (vitlibar) [reply tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference]: Though it seems there is no point in top-level aliases anyway, so throwing an exception in parser seems to be OK too, but please don't check for aliases recursively, it seems to be enough to check for a top-level alias only:

```
if (!x->tryGetAlias().empty())
    throw Exception(ErrorCodes::SYNTAX_ERROR, "...");
```

Comment (george-larionov) [reply tests/queries/0_stateless/03786_AST_formatting_inconsistencies_in_debug_check.reference]: Ok, it turns out nested aliases are wrapped by parens by default, so they do not cause a problem. See my newest updates

File: src/Parsers/Access/ParserCreateRowPolicyQuery.cpp [hunk 3]
```diff
@@ -66,6 +72,11 @@ namespace
             if (!parser.parse(pos, x, expected))
                 return false;
 
+            /// This only checks for top-level aliases, nested aliases are always parenthesized so they
+            /// do not cause a formatting inconsistency.
+            if (!x->tryGetAlias().empty())
+                throw Exception(ErrorCodes::SYNTAX_ERROR, "Aliases are not allowed in CREATE ROW POLICY queries.");
```
Comment (vitlibar) [inline src/Parsers/Access/ParserCreateRowPolicyQuery.cpp]: The error message should be rather `Top-level alias is not allowed...`
Because non-top-level aliases is not a problem.

[the remark this answers is not in the document]
Comment (george-larionov) [reply src/Parsers/Access/ParserCreateRowPolicyQuery.cpp]: I think it is wrong (AS restrictive|permissive is not parsed as an alias), I double checked such a query in my local build, let's see what the tests say though...

Comment (george-larionov) [reply src/Parsers/Access/ParserCreateRowPolicyQuery.cpp]: I was worried that might be too confusing of an error message, but I think you are right.

File: tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql [hunk 4]
```diff
@@ -50,3 +50,5 @@ SELECT (tab.*).2 FROM tab;
 DROP TABLE tab;
 
 WITH (((1,1),1),1) AS t1 SELECT t1.1.1.1;
+
+CREATE ROW POLICY p0 ON t0 USING (1 AS a); -- { clientError SYNTAX_ERROR }
```
[the remark this answers is not in the document]
Comment (george-larionov) [reply tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql:54]: Good point, I'll add another test

**Review by vitlibar — APPROVED** [review]

File: tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql [hunk 5]
```diff
@@ -50,3 +50,9 @@ SELECT (tab.*).2 FROM tab;
...
```
[the remark this answers is not in the document]
Comment (george-larionov) [reply tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql:54]: These tests exist in many other tests, see for example 02131_used_row_policies_in_query_log
