### PR TITLE
Fix parsing IPv6 from query parameter and fix IPv6 to string conversion

### LINKED ISSUE #33928: "CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING" on an IPv6 parameter
**Describe the unexpected behaviour**
Exception when passing an IPv6 address via HTTP parameters or command line. Same IPv6 address works when passed to `toIPv6` function

**How to reproduce**
```
$> clickhouse-client --query "SELECT toIPv6('2001:db8:85a3::8a2e:370:7334')"
2001:db8:85a3::8a2e:370:7334

$> clickhouse-client --param_var 2001:db8:85a3::8a2e:370:7334 --query "SELECT {var:IPv6}"
Received exception from server (version 22.1.2):
Code: 441. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Invalid IPv6 value.: While processing _CAST(' \r���\0\0\0\0�.ps4', 'IPv6'). (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING)
(query: SELECT {var:IPv6})
```

**Additional context**
This is a regression in versions 22.* (21.* work), potentially related to #31072

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix parsing IPv6 from query parameter and fix IPv6 to string conversion.
Closes https://github.com/ClickHouse/ClickHouse/issues/33928

### CODE REVIEW

File: src/Interpreters/ReplaceQueryParameterVisitor.cpp [hunk 1]
```diff
@@ -69,7 +69,14 @@ void ReplaceQueryParameterVisitor::visitQueryParameter(ASTPtr & ast)
             " because it isn't parsed completely: only {} of {} bytes was parsed: {}",
             value, type_name, ast_param.name, read_buffer.count(), value.size(), value.substr(0, read_buffer.count()));
 
-    ast = addTypeConversionToAST(std::make_shared<ASTLiteral>(temp_column[0]), type_name);
+    Field literal;
+    /// If data type has custom serialization, we should use CAST from String,
+    /// because CAST from field may not work correctly (for example for type IPv6).
```
Comment (Avogar) [inline src/Interpreters/ReplaceQueryParameterVisitor.cpp:74]: The problem with IPv6 is that the underlying type is FixedString(16) and it's field type is String, so when we try to CAST field to IPv6 we try to do it through string parsing and get error, because this string is not an IPv6 string, it's 16 bytes representation of IPv6

File: src/Functions/FunctionsConversion.h [hunk 2]
```diff
@@ -1772,6 +1772,9 @@ class FunctionConvert : public IFunction
             }
         }
 
+        if (std::is_same_v<ToDataType, DataTypeString> && from_type->getCustomSerialization())
```
Comment (kitaisreal) [inline src/Functions/FunctionsConversion.h:1775]: Consider to add `if constexpr (std::is_same_v<ToDataType, DataTypeString>)` before this check

**Review by kitaisreal — APPROVED** [review]
