### PR TITLE
Fix silent ignore of delta_lake_snapshot_version without DeltaKernel

### LINKED ISSUE #100502: DeltaLake: delta_lake_snapshot_version (time travel) silently ignored for Azure — returns wrong data instead of error
## Description

When using `deltaLakeAzure` (or any DeltaLake storage where DeltaKernel is disabled), the `delta_lake_snapshot_version` setting is **silently ignored** and the query always returns the latest table state instead of the requested snapshot. No error is raised, so the user receives wrong data with no indication that anything went wrong.

## Root cause

`delta_lake_snapshot_version` is only read inside `DeltaLakeMetadataDeltaKernel.cpp::getSnapshotVersion`, which is only reachable when DeltaKernel is active (S3 and Local storage only).

For Azure (and GCS), `isDeltaKernelEnabled` returns `false`:

```cpp
// DeltaLakeMetadata.cpp:621-625
static bool isDeltaKernelEnabled(ContextPtr context, ObjectStorageType storage_type)
{
    const bool supports_delta_kernel = storage_type == ObjectStorageType::S3
                                    || storage_type == ObjectStorageType::Local;
    return supports_delta_kernel && context->getSettingsRef()[Setting::allow_experimental_delta_kernel_rs];
}
```

So the legacy `DeltaLakeMetadata` reader is used, whose `processMetadataFiles()` has zero references to `delta_lake_snapshot_version` and always reads up to the latest version.

The same silent failure applies to CDF settings (`delta_lake_snapshot_start_version`) on Azure table functions — the `dynamic_cast<DeltaLakeMetadataDeltaKernel *>` at `StorageObjectStorage.cpp:447` returns `nullptr` for the legacy reader, so the CDF code path is skipped entirely and all data is returned.

## Reproducer

Create a two-version DeltaLake table on Azure:

```python
import pyarrow as pa
from deltalake import write_deltalake

storage_options = {
    "AZURE_STORAGE_ACCOUNT_NAME": "<account>",
    "AZURE_STORAGE_ACCOUNT_KEY": "<key>",
}
uri = "az://<container>/repro/time_travel_test"

# Version 0: 3 rows
write_deltalake(uri, pa.table({
    "id": pa.array([1, 2, 3], type=pa.int64()),
    "v":  pa.array(["a", "b", "c"], type=pa.string()),
}), mode="overwrite", storage_options=storage_options)

# Version 1: append 3 more rows → total 6 rows
write_deltalake(uri, pa.table({
    "id": pa.array([4, 5, 6], type=pa.int64()),
    "v":  pa.array(["d", "e", "f"], type=pa.string()),
}), mode="append", storage_options=storage_options)
```

Query from ClickHouse:

```sql
-- Expected: 3 rows (version 0 only)
-- Actual:   6 rows (latest version, setting silently ignored)
SELECT count()
FROM deltaLakeAzure('https://<account>.blob.core.windows.net', '<container>', 'repro/time_travel_test', '<account>', '<key>')
SETTINGS delta_lake_snapshot_version = 0;
```

## Local confirmation

The same behaviour can be reproduced locally by disabling DeltaKernel (which forces the legacy reader, identical to the Azure code path):

```sql
-- DeltaKernel enabled (S3/Local) — correct
SELECT count() FROM deltaLakeLocal('/path/to/table')
SETTINGS delta_lake_snapshot_version = 0, allow_experimental_delta_kernel_rs = 1;
-- → 3

-- Legacy reader (Azure equivalent) — wrong, silently returns latest
SELECT count() FROM deltaLakeLocal('/path/to/table')
SETTINGS delta_lake_snapshot_version = 0, allow_experimental_delta_kernel_rs = 0;
-- → 6
```

## Expected behaviour

Either:
1. Throw `UNSUPPORTED_METHOD`: _"Time travel (`delta_lake_snapshot_version`) is not supported for this storage backend — DeltaKernel is required"_, or
2. Support time travel in the legacy reader.

Related Issue #100438

### PR DESCRIPTION
**Pull request by Daedalus-Icarus**
Closes https://github.com/ClickHouse/ClickHouse/issues/100502

Previously, `delta_lake_snapshot_version` and CDF settings (`delta_lake_snapshot_start_version` / `delta_lake_snapshot_end_version`) were silently ignored when DeltaKernel was not active (Azure, GCS, or `allow_experimental_delta_kernel_rs = 0`), causing queries to return the latest table state instead of the requested snapshot with no indication of error.

Now the legacy metadata reader raises `UNSUPPORTED_METHOD` if any of these settings are set to a non-default value, so users get a clear error instead of wrong data.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Throw an error when `delta_lake_snapshot_version` or CDF version settings are used without DeltaKernel enabled, instead of silently returning wrong data.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

When using DeltaLake time travel (`delta_lake_snapshot_version`) or change data feed (`delta_lake_snapshot_start_version` / `delta_lake_snapshot_end_version`) with storage backends that do not support DeltaKernel (e.g. Azure, GCS), ClickHouse now raises an `UNSUPPORTED_METHOD` error instead of silently ignoring the setting. To use these features, use S3 or Local storage with `allow_experimental_delta_kernel_rs = 1`.

### Version info
- Merged into: `26.4.1.780`

### CODE REVIEW

File: tests/queries/0_stateless/04075_delta_lake_snapshot_version_without_kernel.sql [hunk 1]
```diff
@@ -0,0 +1,23 @@
+-- Tags: no-fasttest
```
Comment (Avogar) [inline tests/queries/0_stateless/04075_delta_lake_snapshot_version_without_kernel.sql]:
```suggestion
-- Tags: no-fasttest, no-msan
```

Delta lake is not supported under msan afaik

**Review by Avogar — CHANGES_REQUESTED** [review]
This PR also contains commit from https://github.com/ClickHouse/ClickHouse/pull/101446, please, clean commits up

**Review by Avogar — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi — this PR may need backporting to `26.3` (LTS), `26.2`, `26.1`, `25.8` (LTS), but no backport label was found.

**Affected code:** `DeltaLakeMetadata::create` in DeltaLakeMetadata.cpp — introduced in 25.8.

**Why:** delta_lake_snapshot_version was introduced in 25.8 (SettingsChangesHistory.cpp line 362), and delta_lake_snapshot_start_version / delta_lake_snapshot_end_version were introduced in 25.12 (lines 187-188). All supported branches contain at least delta_lake_snapshot_version and exhibit the silent-ignore bug. On 25.8, only the delta_lake_snapshot_version check is relevant; on 26.1+ all three settings need the validation.

If this should be backported, consider adding `pr-must-backport` or a version-specific label (e.g. `v26.3-must-backport`). Ignore this if backporting is not applicable.

**Comment by Desel72** [comment]
Thanks @alexey-milovidov
