### PR TITLE
Keeper fix for install snapshot and preprocessing performance improvements

### LINKED ISSUE #40571: Clickhouse Keeper v22.7 crashing on every startup with segfault 11
**Describe what's wrong**

Clickhouse keeper is crashing during initialization with segfault. This repeats on every start - we're unable to start the keeper server, either from existing data or from the new ones, it always crashes after a few minutes of initializing. We're running a standalone dockerized keeper instance.

**Does it reproduce on recent release?**

Yes, we're using the version v22.7 of keeper.

**How to reproduce**

* Which ClickHouse server version to use: 

We tested these versions (so far) and all are crashing with the same error
```
v22.7.1.2484
v22.7.4.16
v22.8.2.11
---
v22.5.1.2079 
```

* Non-default settings, if any:

We tweaked some configurations which may be related, though it's inconclusive on our side:

```
    <coordination_settings>
      <force_sync>false</force_sync>
      <max_requests_batch_size>2000</max_requests_batch_size>
    </coordination_settings>
```

**Expected behavior**

We don't expect the process to crash.

**Error message and/or stacktrace**

```
successfully receive a snapshot (idx 4149762924 term 335) from leader
Compact logs up to log index 4149762924, our max log id is 4148717923
Seems like this node recovers from leaders snapshot, removing all logs
Removing changelog /var/lib/clickhouse/coordination/log/changelog_4148562925_4148662924.bin.zstd because of compaction
Trying to remove log /var/lib/clickhouse/coordination/log/changelog_4148662925_4148762924.bin.zstd which is current active log for write. Possibly this node recovers from snapshot
Removing changelog /var/lib/clickhouse/coordination/log/changelog_4148662925_4148762924.bin.zstd because of compaction
Removed changelog /var/lib/clickhouse/coordination/log/changelog_4148562925_4148662924.bin.zstd because of compaction.
Removed changelog /var/lib/clickhouse/coordination/log/changelog_4148662925_4148762924.bin.zstd because of compaction.
Compaction up to 4149762924 finished new min index 4149762925, new max index 4149762924
successfully compact the log store, will now ask the statemachine to apply the snapshot
########################################
(version 22.7.1.2484 (official build), build id: BB14295F0BE31ECF) (from thread 66) (no query) Received signal Segmentation fault (11)
Address: NULL pointer. Access: read. Address not mapped to object.
Stack trace: 0xa5860d
0. ? @ 0xa5860d in /usr/bin/clickhouse-keeper
Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: E4590F1FEA25C5B140060D818924BBD1)
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
keeper-fix: fix race in accessing logs while snapshot is being installed

Fix [#40571](https://github.com/ClickHouse/ClickHouse/issues/40571)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Coordination/KeeperStorage.h [hunk 1]
```diff
@@ -257,7 +263,40 @@ class KeeperStorage
...
+            auto operator()(const std::string_view a,
+                            const std::string_view b) const
+            {
+                return a == b;
+            }
+
+            using is_transparent = void; // required to make find() work with different type than key_type
+        };
+
+        mutable std::unordered_map<std::string, UncommittedNode, Hash, Equal> nodes;
```
Comment (alesapin) [inline src/Coordination/KeeperStorage.h:289]: Is it really works faster than ordinary unordered_map with default hash? If yes please add a comment.

**Review by alesapin — APPROVED** [review]
As far as I understand race fix is in nuraft and here we have perf improvement + fix for Auth request.
