### PR TITLE
Fix data race in Context::executeTableFunction

### LINKED ISSUE #90712: TSAN data race at executeTableFunction
### Describe the bug

Seen here: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=288616ba67a3f968f574ee0e17cb80e6a600b4a3&name_0=MasterCI&name_1=BuzzHouse+%28amd_tsan%29

### How to reproduce

Difficult to reduce the script.

### Error message and/or stacktrace

Stack trace too large to paste here: https://pastila.nl/?0001051b/c949f4e9abbbe2990cdf0eb0aee36cb5#Xuz9PEFd6cC8CWBPwAB9xg==

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix data race in evaluating table functions in materialized views.

Found by BuzzHouse, but I lost where it was.
Running the test under TSan on master gives https://pastila.nl/?00001f0c/3ca86a2ec3fd4c7442e446bf2b79ba00#yrPNRTU3JtB/psfKHE+a2g==GCM

Closes #90712.

### Version info
- Merged into: `26.1.1.536`
- Backported to: `25.12.4.15`, `25.11.7.36`, `25.10.5.28`

### CODE REVIEW

File: src/Interpreters/Context.h [hunk 1]
```diff
@@ -530,6 +530,7 @@ class ContextData
     /// TODO: maybe replace with temporary tables?
     StoragePtr view_source;                 /// Temporary StorageValues used to generate alias columns for materialized views
     Tables table_function_results;          /// Temporary tables obtained by execution of table functions. Keyed by AST tree id.
+    mutable std::mutex table_function_results_mutex;
```
Comment (novikd) [inline src/Interpreters/Context.h:533]: Query analysis is done in a single thread. I don't quite understand how this data race happens. Is it possible that incorrect context was passed into the processing view?

File: tests/queries/0_stateless/03788_table_function_results_race.sql [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+DROP TABLE IF EXISTS mv;
+DROP TABLE IF EXISTS dest;
+DROP TABLE IF EXISTS source;
+
+CREATE TABLE source (x UInt64) ENGINE = MergeTree ORDER BY x;
+CREATE TABLE dest (x UInt64, y UInt64) ENGINE = MergeTree ORDER BY x;
+
+-- Materialized view that uses a table function in a JOIN.
+-- When data is inserted into source, multiple threads may process chunks
+-- and resolve the numbers() table function concurrently.
```
Comment (novikd) [inline tests/queries/0_stateless/03788_table_function_results_race.sql:13]: But why do they have the same Context?

Comment (alexey-milovidov) [reply tests/queries/0_stateless/03788_table_function_results_race.sql:13]: I think it's because it is the query context, which belongs to the original query.

Comment (novikd) [reply tests/queries/0_stateless/03788_table_function_results_race.sql:13]: `ExecutingInnerQueryFromViewTransform::process` creates a context copy on each block. I think the bug is somewhere else.
Of course, we can merge this PR, but the proper fix would be to find the place where incorrect context is used.

**Comment by alexey-milovidov** [comment]
This is suspicious to me. But I'd merge, because:
- the test reproduces the bug and checks that it is fixed;
- concurrent access to table functions might happen somewhere else - I'd also prefer not to have it, but the fix for now is reasonable.

File: tests/queries/0_stateless/03788_table_function_results_race.sql (hunk 2 above)
Comment (azat) [reply tests/queries/0_stateless/03788_table_function_results_race.sql:13]: Analyzer uses `Context::getQueryContext()` which is the same even after `Context::copy()`
And I guess there can be more problem like this

We can use smth like this `create_context->setQueryContext(std::const_pointer_cast<Context>(current_context))`, does not looks good, but we already have such in i.e. `InterpreterCreateQuery`

Comment (azat) [reply tests/queries/0_stateless/03788_table_function_results_race.sql:13]: Something like this - https://github.com/ClickHouse/ClickHouse/pull/94287
