### PR TITLE
Try fix `No user in current context, it's a bug`

### LINKED ISSUE #55041: `No user in current context, it's a bug`
```
❯ rg -zau '9f675133-0284-4399-b6cb-80ef02843aa2' clickhouse-server.log-21.zst
1291924:2023.09.26 13:36:43.995396 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> executeQuery: (from [::1]:59130) (comment: 00385_storage_file_and_clickhouse-local_app_long.sh) CREATE TABLE buf_00385 ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions (stage: Complete)
1291925:2023.09.26 13:36:43.995432 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON test_gjpt75bh.buf_00385
1291926:2023.09.26 13:36:43.995603 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Trace> ContextAccess (default): Access granted: SELECT(name, is_aggregate) ON system.functions
1291927:2023.09.26 13:36:43.995655 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> DatabaseReplicated (test_gjpt75bh): Proposing query: CREATE TABLE buf_00385 UUID 'ddb3bdc2-2e0e-4405-80ed-815de505d5ee' (`name` String, `is_aggregate` UInt8) ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions
1291930:2023.09.26 13:36:43.997174 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> DDLWorker(test_gjpt75bh): Waiting for worker thread to process all entries before query-0000000016
1291934:2023.09.26 13:36:43.997213 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> DDLWorker(test_gjpt75bh): Processing task query-0000000016 (CREATE TABLE test_gjpt75bh.buf_00385 UUID 'ddb3bdc2-2e0e-4405-80ed-815de505d5ee' (`name` String, `is_aggregate` UInt8) ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions)
1291936:2023.09.26 13:36:43.997506 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> DDLWorker(test_gjpt75bh): Executing query: CREATE TABLE test_gjpt75bh.buf_00385 UUID 'ddb3bdc2-2e0e-4405-80ed-815de505d5ee' (`name` String, `is_aggregate` UInt8) ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions
1291937:2023.09.26 13:36:43.997652 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> executeQuery: (from 0.0.0.0:0, user: ) (comment: 00385_storage_file_and_clickhouse-local_app_long.sh) /* ddl_entry=query-0000000016 */ CREATE TABLE test_gjpt75bh.buf_00385 UUID 'ddb3bdc2-2e0e-4405-80ed-815de505d5ee' (`name` String, `is_aggregate` UInt8) ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions (stage: Complete)
1291943:2023.09.26 13:36:44.010335 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Error> executeQuery: Code: 49. DB::Exception: No user in current context, it's a bug. (LOGICAL_ERROR) (version 23.9.1.1579) (from 0.0.0.0:0) (comment: 00385_storage_file_and_clickhouse-local_app_long.sh) (in query: /* ddl_entry=query-0000000016 */ CREATE TABLE test_gjpt75bh.buf_00385 UUID 'ddb3bdc2-2e0e-4405-80ed-815de505d5ee' (`name` String, `is_aggregate` UInt8) ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions), Stack trace (when copying this message, always include the lines below):
1291978:2023.09.26 13:36:44.011305 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Error> executeQuery: Code: 49. DB::Exception: No user in current context, it's a bug. (LOGICAL_ERROR) (version 23.9.1.1579) (from [::1]:59130) (comment: 00385_storage_file_and_clickhouse-local_app_long.sh) (in query: CREATE TABLE buf_00385 ENGINE = Memory AS SELECT name, is_aggregate FROM system.functions), Stack trace (when copying this message, always include the lines below):
1292013:2023.09.26 13:36:44.011436 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Error> TCPHandler: Code: 49. DB::Exception: No user in current context, it's a bug. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
1292048:2023.09.26 13:36:44.011478 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> TCPHandler: Processed in 0.016412643 sec.
1292049:2023.09.26 13:36:44.011492 [ 64623 ] {9f675133-0284-4399-b6cb-80ef02843aa2} <Debug> MemoryTracker: Peak memory usage (for query): 2.03 MiB.
```

https://s3.amazonaws.com/clickhouse-test-reports/54905/595027b1c6497f0b4792818e6c1f5dc5c8f0c28c/stateless_tests__release__databasereplicated__[4_4].html

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix https://github.com/ClickHouse/ClickHouse/issues/55041

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f80407e39f9c2f546231683b3ddd3a324af8603f with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56789/f80407e39f9c2f546231683b3ddd3a324af8603f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6877747976">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56789/f80407e39f9c2f546231683b3ddd3a324af8603f/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by Algunenano** [comment]
Doesn't it make more sense to fix those functions to introduce a `Context::tryGetUser()` and throw if it's not able to get it?

File: src/Storages/System/StorageSystemFunctions.cpp [hunk 1]
```diff
@@ -143,14 +143,26 @@ void StorageSystemFunctions::fillData(MutableColumns & res_columns, ContextPtr c
...
+            static const std::unordered_map<std::string_view, bool> known_values
+            {
+                {"defaultRoles", false},
+                {"defaultProfiles", false},
+            };
+
+            if (auto it = known_values.find(function_name); it != known_values.end())
+                is_deterministic = it->second;
+            else
+                is_deterministic = functions_factory.tryGet(function_name, context)->isDeterministic();
```
Comment (vitlibar) [inline src/Storages/System/StorageSystemFunctions.cpp:159]: So the problem seems to be here because `FunctionCurrentRoles` and `FunctionProfiles` both try to get their results in their constructor instead of doing that in their `executeImpl()` functions?

Comment (antonio2368) [reply src/Storages/System/StorageSystemFunctions.cpp:159]: Yes actually, we could introduce a flag to initialize on first call.

Comment (vitlibar) [reply src/Storages/System/StorageSystemFunctions.cpp:159]: > we could introduce a flag to initialize on first call

**Comment by antonio2368** [comment]
@Algunenano  Yes, that's also valid, but we would get NULL for functions we know are not deterministic. @vitlibar suggestion would work better I think.

**Review by vitlibar — APPROVED** [review]

File: src/Functions/currentProfiles.cpp [hunk 2]
```diff
@@ -72,6 +65,9 @@ namespace
 
         ColumnPtr executeImpl(const ColumnsWithTypeAndName &, const DataTypePtr &, size_t input_rows_count) const override
         {
+            if (!initialized)
+                initialize();
```
Comment (vitlibar) [inline src/Functions/currentProfiles.cpp:69]: I'm not quite sure but perhaps it's safer to use a mutex here?

File: src/Functions/currentRoles.cpp [hunk 3]
```diff
@@ -67,6 +49,8 @@ namespace
 
         ColumnPtr executeImpl(const ColumnsWithTypeAndName &, const DataTypePtr &, size_t input_rows_count) const override
         {
+            std::call_once(initialized_flag, [&]{ initialize(); });
```
[the remark this answers is not in the document]
Comment (Algunenano) [reply src/Functions/currentRoles.cpp:52]: Ah no, I missread this. I thought the call was still happening in the constructor and not in execute. Considering the kind of function it is, I wasn't even bothering with call_once and suggesting moving the whole initialize body into execute. If somebody complains that calling currentRoles() over more than 1 row is slow (or one block in this case) that's on them.
