### PR TITLE
Properly wait consumers before shutting down Kafka engine

### LINKED ISSUE #80674: Segfault on attempt to create engine=Kafka table without group name
### Company or project name

_No response_

### Describe what's wrong

table was create from named collection w/o kafka_group_name 

```
2025.05.22 07:18:42.642441 [ 84 ] {8585aac2-7690-4514-bbee-68e219868062} <Error> executeQuery: Code: 1001. DB::Exception: cppkafka::HandleException: Local: Unknown group. (STD_EXCEPTION) (version 25.1.5.31 (official build)) (from 127.0.0.1:52142) (query 1, line 1) (in query: SELECT * FROM dummy_http_logs_test LIMIT 10 SETTINGS stream_like_engine_allow_direct_select=1;), Stack trace (when copying this message, always include the lines below):

0. cppkafka::Consumer::get_subscription() const @ 0x0000000017127cd6
1. DB::KafkaConsumer::subscribe() @ 0x000000001108ca5c
2. DB::KafkaSource::generateImpl() @ 0x00000000110f87b1
3. DB::KafkaSource::generate() @ 0x00000000110fc40f
4. DB::ISource::tryGenerate() @ 0x0000000013f13afb
5. DB::ISource::work() @ 0x0000000013f137e7
6. DB::ExecutionThreadContext::executeTask() @ 0x0000000013f2fa47
7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000013f226e4
8. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000013f2199e
9. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne180100]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000013f331d2
10. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000ddead7f
11. void* std::__thread_proxy[abi:ne180100]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000ddf1efa
12. ? @ 0x00007b01bc05dac3
13. ? @ 0x00007b01bc0eea04


2025.05.22 07:19:42.997696 [ 813 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.05.22 07:19:42.997746 [ 813 ] {} <Fatal> BaseDaemon: (version 25.1.5.31 (official build), build id: 28E55A67E083A6497229FC977904A62169BEBCE0, git hash: 48f17e8a805c167a91a343975ad04c1555ad901d, architecture: x86_64) (from thread 766) Received signal 11
2025.05.22 07:19:42.997786 [ 813 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2025.05.22 07:19:42.997805 [ 813 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2025.05.22 07:19:42.997827 [ 813 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000e0862d5 0x00007b01bc00b520 0x00007b01bc1667fe 0x0000000017127dbf 0x00000000110a41af 0x000000000ddead7f 0x000000000ddf1efa 0x00007b01bc05dac3 0x00007b01bc0eea04
2025.05.22 07:19:42.997846 [ 813 ] {} <Fatal> BaseDaemon: ########################################
2025.05.22 07:19:42.997862 [ 813 ] {} <Fatal> BaseDaemon: (version 25.1.5.31 (official build), build id: 28E55A67E083A6497229FC977904A62169BEBCE0, git hash: 48f17e8a805c167a91a343975ad04c1555ad901d) (from thread 766) (no query) Received signal Segmentation fault (11)
2025.05.22 07:19:42.997879 [ 813 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2025.05.22 07:19:42.997892 [ 813 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000e0862d5 0x00007b01bc00b520 0x00007b01bc1667fe 0x0000000017127dbf 0x00000000110a41af 0x000000000ddead7f 0x000000000ddf1efa 0x00007b01bc05dac3 0x00007b01bc0eea04
2025.05.22 07:19:42.997950 [ 813 ] {} <Fatal> BaseDaemon: 0. signalHandler(int, siginfo_t*, void*) @ 0x000000000e0862d5
2025.05.22 07:19:42.997970 [ 813 ] {} <Fatal> BaseDaemon: 1. ? @ 0x00007b01bc00b520
2025.05.22 07:19:42.997986 [ 813 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007b01bc1667fe
2025.05.22 07:19:42.998015 [ 813 ] {} <Fatal> BaseDaemon: 3. cppkafka::Consumer::get_member_id() const @ 0x0000000017127dbf
2025.05.22 07:19:42.998068 [ 813 ] {} <Fatal> BaseDaemon: 4. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne180100]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::StorageKafka::StorageKafka(DB::StorageID const&, std::shared_ptr<DB::Context const>, DB::ColumnsDescription const&, String const&, std::unique_ptr<DB::KafkaSettings, std::default_delete<DB::KafkaSettings>>, String const&)::$_0>(DB::StorageKafka::StorageKafka(DB::StorageID const&, std::shared_ptr<DB::Context const>, DB::ColumnsDescription const&, String const&, std::unique_ptr<DB::KafkaSettings, std::default_delete<DB::KafkaSettings>>, String const&)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000110a41af
2025.05.22 07:19:42.998101 [ 813 ] {} <Fatal> BaseDaemon: 5. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000ddead7f
2025.05.22 07:19:42.998127 [ 813 ] {} <Fatal> BaseDaemon: 6. void* std::__thread_proxy[abi:ne180100]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000ddf1efa
2025.05.22 07:19:42.998146 [ 813 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007b01bc05dac3
2025.05.22 07:19:42.998161 [ 813 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00007b01bc0eea04
2025.05.22 07:19:43.140162 [ 813 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: B315C7B01FA03C5E3F65D78CC8863D5F)
2025.05.22 07:19:43.140301 [ 813 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues

```

```
KfkCln:dummy_ht[321311]: segfault at 0 ip 00007b01bc1667fd sp 00007affcfbf7cc8 error 4 in libc.so.6[7b01bbff1000+195000] likely on CPU 3 (core 3, socket 0)
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```
CREATE OR REPLACE NAMED COLLECTION kafka_config AS
    kafka_broker_list = 'localhost:9092';

CREATE TABLE dummy_http_logs_test 
(
    raw_message String
) engine=Kafka(kafka_config)
SETTTINGS kafka_topic_list='dummy_http_logs_test', kafka_format='RawBLOB';
```

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Properly wait consumers before shutting down Kafka engine (active consumers after shutdown can trigger various debug assertions and also may read data from brokers in background after table has been dropped/detached)

_See commit messages for details_

Fixes: https://github.com/ClickHouse/ClickHouse/issues/80674
Fixes: https://github.com/ClickHouse/ClickHouse/pull/58310

### CODE REVIEW

File: src/Storages/Kafka/StorageKafka.cpp [hunk 1]
```diff
@@ -333,6 +332,36 @@ void StorageKafka::shutdown(bool)
     }
 }
 
+void StorageKafka::cleanConsumers()
+{
+    /// We need to clear the cppkafka::Consumer separately from KafkaConsumer, since cppkafka::Consumer holds a weak_ptr to the KafkaConsumer (for logging callback)
```
[the remark this answers is not in the document]
Comment (azat) [reply src/Storages/Kafka/StorageKafka.cpp:337]: >I cannot find the place where the cppkafka::Consumer holds the weak_ptr of KafkaConsumer? Could you show me where it is?

https://github.com/ClickHouse/ClickHouse/blob/dd26a88716319e10c18374422b9542f568daa633/src/Storages/Kafka/KafkaConfigLoader.cpp#L407

File: src/Storages/Kafka/StorageKafka.cpp [hunk 2]
```diff
@@ -333,6 +332,36 @@ void StorageKafka::shutdown(bool)
...
+    /// So if we will remove cppkafka::Consumer from KafkaConsumer destructor, then due to librdkafka will call the logging again from destructor, it will lead to a deadlock
+    std::vector<ConsumerPtr> consumers_to_close;
```
Comment (tuanpach) [inline src/Storages/Kafka/StorageKafka.cpp:339]: I think we should put a log before waiting for the `cv` and after clearing  `consumers_to_close`. It would be easier when troubleshooting as we would know if all consumers have been returned back yet.

Comment (azat) [reply src/Storages/Kafka/StorageKafka.cpp:339]: Indeed. And there are already such logs in the caller of `cleanConsumers`

**Comment by azat** [comment]
One more issue in kafka

```
2025.05.25 21:40:23.677721 [ 899 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.05.25 21:40:23.677840 [ 899 ] {} <Fatal> BaseDaemon: (version 25.6.1.1, build id: 9FD48A61A5A5F0872E3193E3AD84F4BCF773051C, git hash: 761af4c14f6f43fbcd2b969dc66a3f735e284f90, architecture: x86_64) (from thread 9) Received signal -3
2025.05.25 21:40:23.677905 [ 899 ] {} <Fatal> BaseDaemon: Signal description: sanitizer trap
2025.05.25 21:40:23.677965 [ 899 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2025.05.25 21:40:23.678019 [ 899 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055ce71048c47 0x000055ce7173072b 0x000055ce5fe1bb50 0x000055ce5fe02229 0x000055ce5fe05367 0x000055ce5fdfb869 0x000055ce95085934 0x000055ce7b9dd3b4 0x000055ce8d0992aa 0x000055ce8d098d29 0x000055ce8d0e63fa 0x000055ce8d0e97bc 0x000055ce8d09c3d0 0x000055ce7b9f5dcb 0x000055ce7b9f0bc9 0x000055ce7f77b4c4 0x000055ce7f77841d 0x000055ce7f776aa1 0x000055ce7f77>
2025.05.25 21:40:23.678070 [ 899 ] {} <Fatal> BaseDaemon: ########################################
2025.05.25 21:40:23.678315 [ 899 ] {} <Fatal> BaseDaemon: (version 25.6.1.1, build id: 9FD48A61A5A5F0872E3193E3AD84F4BCF773051C, git hash: 761af4c14f6f43fbcd2b969dc66a3f735e284f90) (from thread 9) (query_id: 7f0ecc6e-f399-4581-9f92-1704972d3a55) (query: DROP TABLE test.kafka) Received signal sanitizer trap (-3)
2025.05.25 21:40:23.678425 [ 899 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2025.05.25 21:40:23.678510 [ 899 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055ce71048c47 0x000055ce7173072b 0x000055ce5fe1bb50 0x000055ce5fe02229 0x000055ce5fe05367 0x000055ce5fdfb869 0x000055ce95085934 0x000055ce7b9dd3b4 0x000055ce8d0992aa 0x000055ce8d098d29 0x000055ce8d0e63fa 0x000055ce8d0e97bc 0x000055ce8d09c3d0 0x000055ce7b9f5dcb 0x000055ce7b9f0bc9 0x000055ce7f77b4c4 0x000055ce7f77841d 0x000055ce7f776aa1 0x000055ce7f77>
2025.05.25 21:40:23.716550 [ 899 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./ci/tmp/build/./src/Common/StackTrace.cpp:389: StackTrace::tryCapture()
2025.05.25 21:40:23.716696 [ 899 ] {} <Fatal> BaseDaemon: 0. ./ci/tmp/build/./src/Common/StackTrace.cpp:61: StackTrace::StackTrace() @ 0x000000001d611c47
2025.05.25 21:40:23.778614 [ 899 ] {} <Fatal> BaseDaemon: 1. ./ci/tmp/build/./src/Common/SignalHandlers.cpp:212: sanitizerDeathCallback() @ 0x000000001dcf972b
2025.05.25 21:40:23.848476 [ 899 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x000000000c3e4b50
2025.05.25 21:40:23.887747 [ 899 ] {} <Fatal> BaseDaemon: 3. __asan::ScopedInErrorReport::~ScopedInErrorReport() @ 0x000000000c3cb229
2025.05.25 21:40:23.926353 [ 899 ] {} <Fatal> BaseDaemon: 4. __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) @ 0x000000000c3ce367
2025.05.25 21:40:23.965043 [ 899 ] {} <Fatal> BaseDaemon: 5. __asan_memmove @ 0x000000000c3c4869
2025.05.25 21:40:24.011708 [ 899 ] {} <Fatal> BaseDaemon: 6.0. inlined from ./contrib/llvm-project/libcxx/include/__string/constexpr_c_functions.h:227: char* std::__constexpr_memmove[abi:ne190107]<char, char const, 0>(char*, char const*, std::__element_count)
2025.05.25 21:40:24.011830 [ 899 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./contrib/llvm-project/libcxx/include/__string/char_traits.h:148: std::char_traits<char>::copy[abi:ne190107](char*, char const*, unsigned long)
2025.05.25 21:40:24.011899 [ 899 ] {} <Fatal> BaseDaemon: 6. ./contrib/llvm-project/libcxx/include/string:2575: String& String::__assign_no_alias<false>(char const*, unsigned long) @ 0x000000004164e934
2025.05.25 21:40:24.081113 [ 899 ] {} <Fatal> BaseDaemon: 7.0. inlined from ./contrib/llvm-project/libcxx/include/string:2665: String::operator=(String const&)
2025.05.25 21:40:24.081297 [ 899 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./src/Storages/Kafka/KafkaConsumer.h:125: DB::KafkaConsumer::setRDKafkaStat(String const&)
2025.05.25 21:40:24.081356 [ 899 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./ci/tmp/build/./src/Storages/Kafka/KafkaConsumer.cpp:76: operator()
2025.05.25 21:40:24.081447 [ 899 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::KafkaConsumer::createConsumer(cppkafka::Configuration)::$_0&>()(std::declval<cppkafka::KafkaHandleBase&>(), std::declval<String const&>())) std::__invoke[abi:ne190107]<DB::KafkaConsumer::createConsumer(cppkafka::Configuration)::$_0&, cppkafka::KafkaHandleBase>
2025.05.25 21:40:24.081533 [ 899 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne190107]<DB::KafkaConsumer::createConsumer(cppkafka::Configuration)::$_0&, cppkafka::KafkaHandleBase&, String const&>(DB::KafkaConsumer::createConsumer(cppkafka::Configuration)::$_0&, cppkafka::KafkaHandleBase&, String co>
2025.05.25 21:40:24.081590 [ 899 ] {} <Fatal> BaseDaemon: 7.5. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.05.25 21:40:24.081642 [ 899 ] {} <Fatal> BaseDaemon: 7. ./contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x0000000027fa63b4
2025.05.25 21:40:24.105704 [ 899 ] {} <Fatal> BaseDaemon: 8.0. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.05.25 21:40:24.105801 [ 899 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.05.25 21:40:24.105869 [ 899 ] {} <Fatal> BaseDaemon: 8. ./contrib/cppkafka/include/cppkafka/detail/callback_invoker.h:84: void cppkafka::CallbackInvoker<std::function<void (cppkafka::KafkaHandleBase&, String const&)>>::operator()<cppkafka::KafkaHandleBase&, String>(cppkafka::KafkaHandleBase&, String&&) const @ 0x00000000396622aa
2025.05.25 21:40:24.139455 [ 899 ] {} <Fatal> BaseDaemon: 9. ./ci/tmp/build/./contrib/cppkafka/src/configuration.cpp:92: cppkafka::stats_callback_proxy(rd_kafka_s*, char*, unsigned long, void*) @ 0x0000000039661d29
2025.05.25 21:40:24.149244 [ 899 ] {} <Fatal> BaseDaemon: 10. ./ci/tmp/build/./contrib/librdkafka/src/rdkafka.c:4065: rd_kafka_poll_cb @ 0x00000000396af3fa
2025.05.25 21:40:24.157533 [ 899 ] {} <Fatal> BaseDaemon: 11. ./ci/tmp/build/./contrib/librdkafka/src/rdkafka.c:3459: rd_kafka_consumer_close @ 0x00000000396b27bc
2025.05.25 21:40:24.184795 [ 899 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./ci/tmp/build/./contrib/cppkafka/src/consumer.cpp:296: cppkafka::Consumer::close()
2025.05.25 21:40:24.184887 [ 899 ] {} <Fatal> BaseDaemon: 12. ./ci/tmp/build/./contrib/cppkafka/src/consumer.cpp:82: cppkafka::Consumer::~Consumer() @ 0x00000000396653d0
2025.05.25 21:40:24.364999 [ 899 ] {} <Fatal> BaseDaemon: 13.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156: std::__shared_count::__release_shared[abi:ne190107]()
2025.05.25 21:40:24.365095 [ 899 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185: std::__shared_weak_count::__release_shared[abi:ne190107]()
2025.05.25 21:40:24.365139 [ 899 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668: ~shared_ptr
2025.05.25 21:40:24.365224 [ 899 ] {} <Fatal> BaseDaemon: 13.3. inlined from ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67: void std::__destroy_at[abi:ne190107]<std::shared_ptr<cppkafka::Consumer>, 0>(std::shared_ptr<cppkafka::Consumer>*)
2025.05.25 21:40:24.365271 [ 899 ] {} <Fatal> BaseDaemon: 13.4. inlined from ./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339: void std::allocator_traits<std::allocator<std::shared_ptr<cppkafka::Consumer>>>::destroy[abi:ne190107]<std::shared_ptr<cppkafka::Consumer>, void, 0>(std::allocator<std::shared_ptr<cppkafka::Consumer>>&, std::shared_ptr<cppkafka::Consumer>*)
2025.05.25 21:40:24.365311 [ 899 ] {} <Fatal> BaseDaemon: 13.5. inlined from ./contrib/llvm-project/libcxx/include/vector:985: std::vector<std::shared_ptr<cppkafka::Consumer>, std::allocator<std::shared_ptr<cppkafka::Consumer>>>::__base_destruct_at_end[abi:ne190107](std::shared_ptr<cppkafka::Consumer>*)
2025.05.25 21:40:24.365350 [ 899 ] {} <Fatal> BaseDaemon: 13.6. inlined from ./contrib/llvm-project/libcxx/include/vector:979: std::vector<std::shared_ptr<cppkafka::Consumer>, std::allocator<std::shared_ptr<cppkafka::Consumer>>>::__clear[abi:ne190107]()
2025.05.25 21:40:24.365384 [ 899 ] {} <Fatal> BaseDaemon: 13.7. inlined from ./contrib/llvm-project/libcxx/include/vector:749: std::vector<std::shared_ptr<cppkafka::Consumer>, std::allocator<std::shared_ptr<cppkafka::Consumer>>>::clear[abi:ne190107]()
2025.05.25 21:40:24.365424 [ 899 ] {} <Fatal> BaseDaemon: 13. ./ci/tmp/build/./src/Storages/Kafka/StorageKafka.cpp:363: DB::StorageKafka::cleanConsumers() @ 0x0000000027fbedcb
2025.05.25 21:40:24.531732 [ 899 ] {} <Fatal> BaseDaemon: 14. ./ci/tmp/build/./src/Storages/Kafka/StorageKafka.cpp:323: DB::StorageKafka::shutdown(bool) @ 0x0000000027fb9bc9
2025.05.25 21:40:24.615145 [ 899 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./src/Storages/IStorage.h:571: DB::IStorage::flushAndShutdown(bool)
2025.05.25 21:40:24.615247 [ 899 ] {} <Fatal> BaseDaemon: 15. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:306: DB::InterpreterDropQuery::executeToTableImpl(std::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x000000002bd444c4
2025.05.25 21:40:24.691976 [ 899 ] {} <Fatal> BaseDaemon: 16. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:122: DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) @ 0x000000002bd4141d
2025.05.25 21:40:24.764821 [ 899 ] {} <Fatal> BaseDaemon: 17. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:95: DB::InterpreterDropQuery::executeSingleDropQuery(std::shared_ptr<DB::IAST> const&) @ 0x000000002bd3faa1
2025.05.25 21:40:24.837965 [ 899 ] {} <Fatal> BaseDaemon: 18. ./ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:76: DB::InterpreterDropQuery::execute() @ 0x000000002bd3f530
2025.05.25 21:40:24.982954 [ 899 ] {} <Fatal> BaseDaemon: 19. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1522: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x000000002c531192
2025.05.25 21:40:25.168009 [ 899 ] {} <Fatal> BaseDaemon: 20. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1714: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000002c526806
2025.05.25 21:40:25.284522 [ 899 ] {} <Fatal> BaseDaemon: 21. ./ci/tmp/build/./src/Server/TCPHandler.cpp:686: DB::TCPHandler::runImpl() @ 0x0000000031819b8e
2025.05.25 21:40:25.521021 [ 899 ] {} <Fatal> BaseDaemon: 22. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2674: DB::TCPHandler::run() @ 0x000000003185aaba
2025.05.25 21:40:25.526077 [ 899 ] {} <Fatal> BaseDaemon: 23. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000039f610af
2025.05.25 21:40:25.535259 [ 899 ] {} <Fatal> BaseDaemon: 24. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000039f61d77
2025.05.25 21:40:25.545738 [ 899 ] {} <Fatal> BaseDaemon: 25. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000039e664af
2025.05.25 21:40:25.556607 [ 899 ] {} <Fatal> BaseDaemon: 26. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000039e600c8
2025.05.25 21:40:25.596845 [ 899 ] {} <Fatal> BaseDaemon: 27. asan_thread_start(void*) @ 0x000000000c3c3e77
2025.05.25 21:40:25.596970 [ 899 ] {} <Fatal> BaseDaemon: 28. ? @ 0x0000000000094ac3
2025.05.25 21:40:25.597004 [ 899 ] {} <Fatal> BaseDaemon: 29. ? @ 0x0000000000126850
2025.05.25 21:40:25.597039 [ 899 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2025.05.25 21:40:27.479082 [ 899 ] {} <Fatal> BaseDaemon: Changed settings: max_block_size = 38604, max_joined_block_size_rows = 28231, stream_like_engine_allow_direct_select = true, query_plan_join_swap_table = 'auto', function_sleep_max_microseconds_per_block = 0, insert_keeper_max_retries = 0
```

**Review by tuanpach — APPROVED** [review]

**Comment by azat** [comment]
>[Stateless tests (release, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80795&sha=467d8849aefcf57e42b09735a8a1a28473c8ae99&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20ParallelReplicas%2C%20s3%20storage%29) — fail: 1, passed: 6925, skipped: 981

- https://github.com/ClickHouse/ClickHouse/issues/65382

>[Stateless tests (tsan, s3 storage, 3/3)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80795&sha=467d8849aefcf57e42b09735a8a1a28473c8ae99&name_0=PR&name_1=Stateless%20tests%20%28tsan%2C%20s3%20storage%2C%203%2F3%29) — Server died, fail: 12, passed: 1320, skipped: 30

- https://github.com/ClickHouse/ClickHouse/issues/80866

**Comment by azat** [comment]
>[Bugfix validation](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80795&sha=f7262e4f25d80d154f9a58bfeda4bc3306b1ab21&name_0=PR&name_1=Bugfix%20validation) — New test(s) failed to reproduce a bug

Test can reproduce the problem reliably only with ASan/debug build.
