### PR TITLE
fix stale read race in `ReadFromRemote`

### LINKED ISSUE #69753: test_delayed_replica_failover/test.py::test is flaky
https://s3.amazonaws.com/clickhouse-test-reports/0/a997cfad2b61200c81371202acf5c6382d3d57f6/integration_tests__asan__[4_4].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgLS0gQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0JST0tFTicpCiAgICBBTkQgdG9EYXRlKGNoZWNrX3N0YXJ0X3RpbWUpID4gJzIwMjQtMDctMDEnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2RlbGF5ZWRfcmVwbGljYV9mYWlsb3ZlciUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQw==

```
            # At this point all replicas are stale, but the query must still go to second replicas which are the least stale ones.
            assert (
                instance_with_dist_table.query(
                    """
    SELECT sum(x) FROM distributed SETTINGS
        load_balancing='in_order',
        max_replica_delay_for_distributed_queries=1
    """
                ).strip()
                == "3"
            )
    
            # Prefer fallback_to_stale_replicas over skip_unavailable_shards
            assert (
                instance_with_dist_table.query(
                    """
    SELECT sum(x) FROM distributed SETTINGS
        load_balancing='in_order',
        skip_unavailable_shards=1,
        max_replica_delay_for_distributed_queries=1
    """
                ).strip()
                == "3"
            )
    
            # If we forbid stale replicas, the query must fail. But sometimes we must have bigger timeouts.
            for _ in range(20):
                try:
                    instance_with_dist_table.query(
                        """
    SELECT count() FROM distributed SETTINGS
        load_balancing='in_order',
        max_replica_delay_for_distributed_queries=1,
        fallback_to_stale_replicas_for_distributed_queries=0
    """
                    )
                    time.sleep(0.5)
                except:
                    break
            else:
>               raise Exception("Didn't raise when stale replicas are not allowed")
E               Exception: Didn't raise when stale replicas are not allowed

```

### PR DESCRIPTION
**Pull request by mstetsyuk**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

Fixes: https://github.com/ClickHouse/ClickHouse/issues/69753

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit c459c2b11e00e0c8bb7092fad9ca0e99d584ef28 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75293/c459c2b11e00e0c8bb7092fad9ca0e99d584ef28/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Comment by mstetsyuk** [comment]
Fixes https://github.com/ClickHouse/ClickHouse/issues/69753.

There was something similar to a race condition:
1. We are the only stale replica, and the delay is 1
2. We set `local_delay = 1`
3. Time passes and the local delay becomes 2
4. We read delays from all replicas (our is 2, others' is 0)
5. Then we check that the recorded local delay from (2) is 1 and is less than the `max_remote_delay` which is 2
6. We decide to read from the local replica because we think it's not the most stale replica (which is wrong)

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 1]
```diff
@@ -472,7 +492,15 @@ void ReadFromRemote::addLazyPipe(Pipes & pipes, const ClusterProxy::SelectStream
                 max_remote_delay = std::max(try_result.delay, max_remote_delay);
         }
 
-        if (try_results.empty() || local_delay < max_remote_delay)
+        const time_t local_delay = replicated_storage->getAbsoluteDelay();
```
Comment (antonio2368) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:495]: let's add a comment that a race can happen here but it should be really rare

Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:495]: If the current replica is the most stale one, we will never decide to read from it.

**Review by antonio2368 — APPROVED** [review]

**Review by antonio2368 — APPROVED** [review]

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 2]
```diff
@@ -431,12 +439,25 @@ void ReadFromRemote::addLazyPipe(Pipes & pipes, const ClusterProxy::SelectStream
     if (filter_actions_dag)
         pushed_down_filters = std::make_shared<const ActionsDAG>(filter_actions_dag->clone());
 
+    const StorageID resolved_id = context->resolveStorageID(main_table);
+    const StoragePtr storage = DatabaseCatalog::instance().tryGetTable(resolved_id, context);
+    if (!storage)
+    {
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Storage with id {} not found", resolved_id);
```
Comment (azat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:446]: Should this be `LOGICAL_ERROR`? And what if the underlying table had been removed?
Also isn't the `main_table` will be empty in case of `select * from remote remote()`?

Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp]: Changed the error to `UNKNOWN_TABLE`.

Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp]: > Also isn't the main_table will be empty in case of `select * from remote remote()`?

The `addLazyPipe` function will not be called for tables that don't exist locally:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/ClusterProxy/SelectStreamFactory.cpp#L230 (`lazy = false` is passed here).

By the way, I've changed the code to use `main_table` only  if `shard.main_table` is empty, in line with this: https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/QueryPlan/ReadFromRemote.h#L23

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 3]
```diff
@@ -431,12 +440,25 @@ void ReadFromRemote::addLazyPipe(Pipes & pipes, const ClusterProxy::SelectStream
...
+    const StoragePtr storage = DatabaseCatalog::instance().tryGetTable(resolved_id, context);
+    if (!storage)
+    {
+        throw Exception(ErrorCodes::UNKNOWN_TABLE, "Storage with id {} not found", resolved_id);
+    }
+
+    const auto * replicated_storage = dynamic_cast<const StorageReplicatedMergeTree *>(storage.get());
+    if (!replicated_storage)
+    {
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Unexpected lazy remote read from a non-replicated table: {}", storage->getName());
```
Comment (azat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:453]: It is possible to trigger this in case of fail point, see src/Interpreters/ClusterProxy/SelectStreamFactory.cpp#L197

File: src/Interpreters/ClusterProxy/SelectStreamFactory.cpp [hunk 4]
```diff
@@ -169,7 +169,7 @@ void SelectStreamFactory::createForShardImpl(
             query_ast, header, context, processed_stage, shard_info.shard_num, shard_count, has_missing_objects));
     };
 
-    auto emplace_remote_stream = [&](bool lazy = false, time_t local_delay = 0)
+    auto emplace_remote_stream = [&](bool lazy = false)
```
Comment (azat) [inline src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:172]: While you are here, can also add a comment for what `lazy` means

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 5]
```diff
@@ -472,12 +494,33 @@ void ReadFromRemote::addLazyPipe(Pipes & pipes, const ClusterProxy::SelectStream
...
+        fiu_do_on(FailPoints::use_delayed_remote_source,
+        {
+            use_delayed_remote_source = true;
+        });
+
+        if (!use_delayed_remote_source)
         {
-            auto plan = createLocalPlan(
-                query, header, my_context, my_stage, my_shard.shard_info.shard_num, my_shard_count, my_shard.has_missing_objects);
+            if (try_results.empty() && local_delay >= max_allowed_delay)
```
Comment (azat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:508]: Can you please add a comment why this could not happens under normal circumstances? I.e. why it is `LOGICAL_ERROR` here

Assume that in `SelectStreamFactory::createForShardImpl`:
- `prefer_localhost_replica=1`
- `max_replica_delay_for_distributed_queries=5`
- `local_delay=10`

And other replica is unavailable, so `try_result.empty() == true` (_am I right that this is the case for this?_), so it will enter here.

What did I miss?

**Review by azat — COMMENTED** [review]
BTW I guess it is also possible to add a test case for this, by artificially breaking the replication + sleep afterwards

File: src/Processors/QueryPlan/ReadFromRemote.cpp (hunk 5 above)
Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:509]: Indeed, you are right: we don't add entries for connections that we failed to establish to `try_results`. Changed the error to `REPLICA_IS_STALE`.

File: src/Processors/QueryPlan/ReadFromRemote.cpp (hunk 3 above)
Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp]: That's a good catch. I changed it so that this cast will be executed only if `use_delayed_remote_source` is not used.

File: src/Interpreters/ClusterProxy/SelectStreamFactory.cpp (hunk 4 above)
Comment (mstetsyuk) [reply src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:173]: done

**Comment by mstetsyuk** [comment]
> BTW I guess it is also possible to add a test case for this, by artificially breaking the replication + sleep afterwards

This is already tested by `test_delayed_replica_failover`.

File: src/Processors/QueryPlan/ReadFromRemote.cpp [hunk 6]
```diff
@@ -472,12 +489,38 @@ void ReadFromRemote::addLazyPipe(Pipes & pipes, const ClusterProxy::SelectStream
...
+            {
+                throw Exception(ErrorCodes::LOGICAL_ERROR, "Unexpected lazy remote read from a non-replicated table: {}", my_storage->getName());
+            }
+            const UInt64 local_delay = replicated_storage->getAbsoluteDelay();
+            const UInt64 max_allowed_delay = current_settings[Setting::max_replica_delay_for_distributed_queries];
+
+            if (try_results.empty() && local_delay >= max_allowed_delay)
+            {
+                throw Exception(
+                    ErrorCodes::REPLICA_IS_STALE,
```
Comment (azat) [inline src/Processors/QueryPlan/ReadFromRemote.cpp:511]: Shouldn't we just use **existing** `ALL_REPLICAS_ARE_STALE`? Since in this case all replicas either stale or unavailable

**Review by azat — APPROVED** [review]

File: src/Processors/QueryPlan/ReadFromRemote.cpp (hunk 6 above)
Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:511]: I considered using it, but what if the client just connected to the stale replica, which can't connect to other replicas?

Comment (azat) [reply src/Processors/QueryPlan/ReadFromRemote.cpp:511]: Well, AFAICS `ALL_REPLICAS_ARE_STALE` has the same issue

Comment (mstetsyuk) [reply src/Processors/QueryPlan/ReadFromRemote.cpp]: Got it, changed the error to `ALL_REPLICAS_ARE_STALE `

**Comment by azat** [comment]
>Integration tests (release, 1/4) — fail: 1, passed: 824

- https://github.com/ClickHouse/ClickHouse/pull/75762

_P.S. it is better to fix at least one test to make CI better overall_
