### PR TITLE
Fix race in grace hash join with limit

### LINKED ISSUE #45986: Crash in JOIN with method `grace_hash`
Found by WingFuzz team with the help of [Griffin](https://dl.acm.org/doi/abs/10.1145/3551349.3560431) tool.

**How to reproduce**

```sql
DROP TABLE IF EXISTS test_grace_hash;

CREATE TABLE test_grace_hash (id UInt32, value UInt64) ENGINE = MergeTree ORDER BY id;

INSERT INTO test_grace_hash SELECT number, number % 100 = 0 FROM numbers(100000);

SET join_algorithm = 'grace_hash';

SELECT count() FROM (SELECT f.id FROM test_grace_hash AS f LEFT JOIN test_grace_hash AS d ON f.id = d.id LIMIT 1000);

DROP TABLE test_grace_hash;
```

ASan report:
```
=================================================================
==4056962==ERROR: AddressSanitizer: heap-use-after-free on address 0x7f2c67660520 at pc 0x0000307b0944 bp 0x7f2cb478c790 sp 0x7f2cb478c788
READ of size 4 at 0x7f2c67660520 thread T245 (QueryPipelineEx)
    #0 0x307b0943 in HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>::isZero(unsigned int const&, HashTableNoState const&) build_docker/../src/Common/HashTable/HashMap.h:89:93
    #1 0x307b0943 in HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>::isZero(HashTableNoState const&) const build_docker/../src/Common/HashTable/HashMap.h:88:53
    #2 0x307b0943 in HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::findCell(unsigned int const&, unsigned long, unsigned long) const build_docker/../src/Common/HashTable/HashTable.h:484:34
    #3 0x307b0943 in HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::find(unsigned int const&) build_docker/../src/Common/HashTable/HashTable.h:1099:30
    #4 0x307b0943 in HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::find(unsigned int const&) const build_docker/../src/Common/HashTable/HashTable.h:1105:67
    #5 0x307b0943 in DB::ColumnsHashing::columns_hashing_impl::FindResultImpl<DB::RowRefList const, true> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, false, true>::findKeyImpl<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const, unsigned int>(unsigned int, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const&) build_docker/../src/Common/ColumnsHashingImpl.h:263:24
    #6 0x307b0943 in DB::ColumnsHashing::columns_hashing_impl::FindResultImpl<DB::RowRefList const, true> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, false, true>::findKey<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const>(HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const&, unsigned long, DB::Arena&) build_docker/../src/Common/ColumnsHashingImpl.h:165:16
    #7 0x307b0943 in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumns<(DB::JoinKind)1, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, false>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) build_docker/../src/Interpreters/HashJoin.cpp:1240:79
    #8 0x307883df in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumnsSwitchMultipleDisjuncts<(DB::JoinKind)1, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) build_docker/../src/Interpreters/HashJoin.cpp:1358:11
    #9 0x307883df in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::joinRightColumnsSwitchNullability<(DB::JoinKind)1, (DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(std::__1::vector<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>, std::__1::allocator<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList const, unsigned int, false, true>>>&&, std::__1::vector<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*, std::__1::allocator<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::JoinStuff::JoinUsedFlags&) build_docker/../src/Interpreters/HashJoin.cpp:1382:20
    #10 0x307883df in DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> DB::(anonymous namespace)::switchJoinRightColumns<(DB::JoinKind)1, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>(std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>> const&, DB::(anonymous namespace)::AddedColumns&, DB::HashJoin::Type, DB::JoinStuff::JoinUsedFlags&) build_docker/../src/Interpreters/HashJoin.cpp:1428:9
    #11 0x3122dc5d in void DB::HashJoin::joinBlockImpl<(DB::JoinKind)1, (DB::JoinStrictness)3, DB::HashJoin::MapsTemplate<DB::RowRefList>>(DB::Block&, DB::Block const&, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>> const&, bool) const build_docker/../src/Interpreters/HashJoin.cpp:1482:34
    #12 0x30703982 in auto DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4::operator()<std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)1>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)3>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>>>(std::__1::integral_constant<DB::JoinKind, (DB::JoinKind)1>, std::__1::integral_constant<DB::JoinStrictness, (DB::JoinStrictness)3>, std::__1::vector<DB::HashJoin::MapsTemplate<DB::RowRefList> const*, std::__1::allocator<DB::HashJoin::MapsTemplate<DB::RowRefList> const*>>&) const build_docker/../src/Interpreters/HashJoin.cpp:1745:13
    #13 0x30703982 in auto bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)::operator()<std::__1::integral_constant<int, 2>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>) const build_docker/../src/Interpreters/joinDispatch.h:121:13
    #14 0x30703982 in bool func_wrapper<bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), std::__1::integral_constant<int, 2>>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) build_docker/../base/base/constexpr_helpers.h:18:16
    #15 0x30703982 in bool static_for_impl<int, 0, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&, std::__1::integer_sequence<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>) build_docker/../base/base/constexpr_helpers.h:24:13
    #16 0x30703982 in bool static_for<0, 24, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&) build_docker/../base/base/constexpr_helpers.h:31:12
    #17 0x3058a091 in bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4>(DB::JoinKind, DB::JoinStrictness, std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>> const*>>&, DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&)::$_4&&) build_docker/../src/Interpreters/joinDispatch.h:106:12
    #18 0x3058a091 in DB::HashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&) build_docker/../src/Interpreters/HashJoin.cpp:1743:13
    #19 0x3056513f in DB::GraceHashJoin::joinBlock(DB::Block&, std::__1::shared_ptr<DB::ExtraBlock>&) build_docker/../src/Interpreters/GraceHashJoin.cpp:428:16
    #20 0x351a516e in DB::JoiningTransform::readExecute(DB::Chunk&) build_docker/../src/Processors/Transforms/JoiningTransform.cpp
    #21 0x351a2fd8 in DB::JoiningTransform::transform(DB::Chunk&) build_docker/../src/Processors/Transforms/JoiningTransform.cpp:191:17
    #22 0x351a203b in DB::JoiningTransform::work() build_docker/../src/Processors/Transforms/JoiningTransform.cpp:125:9
    #23 0x34ba12c0 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #24 0x34ba12c0 in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #25 0x34b805bc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26
    #26 0x34b84036 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5
    #27 0x34b84036 in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:320:17
    #28 0x34b84036 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #29 0x34b84036 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1
    #30 0x34b84036 in decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1
    #31 0x34b84036 in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:196:13
    #32 0x34b84036 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #33 0x34b84036 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #34 0x34b84036 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #35 0x34b84036 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #36 0x1f3ff0ac in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #37 0x1f3ff0ac in std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #38 0x1f3ff0ac in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:295:17
    #39 0x1f4093bf in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #40 0x1f4093bf in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #41 0x1f4093bf in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5
    #42 0x1f4093bf in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5
    #43 0x7f2f0ba18608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
    #44 0x7f2f0b93d162 in __clone /build/glibc-sMfBJT/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x7f2c67660520 is located 32032 bytes inside of 8388608-byte region [0x7f2c67658800,0x7f2c67e58800)
freed by thread T299 (QueryPipelineEx) here:
    #0 0xe9468c2 in free (/usr/bin/clickhouse+0xe9468c2) (BuildId: 3b3eb5ac479e2388030e68557e67fa51ba9e50fb)
    #1 0x1f110de8 in Allocator<true, true>::freeNoTrack(void*, unsigned long) build_docker/../src/Common/Allocator.h:258:13
    #2 0x1f1109a0 in Allocator<true, true>::free(void*, unsigned long) build_docker/../src/Common/Allocator.h:105:13
    #3 0x311f09ec in HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::free() build_docker/../src/Common/HashTable/HashTable.h:520:24
    #4 0x311f09ec in HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::~HashTable() build_docker/../src/Common/HashTable/HashTable.h:776:9
    #5 0x311f09ec in std::__1::default_delete<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>::operator()[abi:v15000](HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>*) const build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48:5
    #6 0x311f09ec in std::__1::unique_ptr<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, std::__1::default_delete<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>>::reset[abi:v15000](HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>*) build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305:7
    #7 0x311f09ec in std::__1::unique_ptr<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, std::__1::default_delete<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>>::~unique_ptr[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259:19
    #8 0x311f09ec in DB::HashJoin::MapsTemplate<DB::RowRefList>::~MapsTemplate() build_docker/../src/Interpreters/HashJoin.h:243:12
    #9 0x3120100e in decltype(auto) std::__1::__variant_detail::__visitation::__base::__visit_alt[abi:v15000]<std::__1::__variant_detail::__dtor<std::__1::__variant_detail::__traits<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, (std::__1::__variant_detail::_Trait)1>::__destroy[abi:v15000]()::'lambda'(auto&), std::__1::__variant_detail::__dtor<std::__1::__variant_detail::__traits<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, (std::__1::__variant_detail::_Trait)1>&>(auto&&, std::__1::__variant_detail::__dtor<std::__1::__variant_detail::__traits<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, (std::__1::__variant_detail::_Trait)1>&) build_docker/../contrib/llvm-project/libcxx/include/variant:511:12
    #10 0x3120100e in std::__1::__variant_detail::__dtor<std::__1::__variant_detail::__traits<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, (std::__1::__variant_detail::_Trait)1>::__destroy[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/variant:854:1
    #11 0x3120100e in std::__1::__variant_detail::__dtor<std::__1::__variant_detail::__traits<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, (std::__1::__variant_detail::_Trait)1>::~__dtor() build_docker/../contrib/llvm-project/libcxx/include/variant:854:1
    #12 0x3120100e in std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>::~variant() build_docker/../contrib/llvm-project/libcxx/include/variant:1375:22
    #13 0x3120100e in void std::__1::__destroy_at[abi:v15000]<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>*) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13
    #14 0x3120100e in void std::__1::destroy_at[abi:v15000]<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0>(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>*) build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5
    #15 0x3120100e in void std::__1::allocator_traits<std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>>>::destroy[abi:v15000]<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, void, void>(std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>>&, std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>*) build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9
    #16 0x3120100e in std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>>>::__base_destruct_at_end[abi:v15000](std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>*) build_docker/../contrib/llvm-project/libcxx/include/vector:833:9
    #17 0x3120100e in std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>>>::__clear[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/vector:827:29
    #18 0x3120100e in std::__1::vector<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, std::__1::allocator<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>>>::~vector[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/vector:436:9
    #19 0x3058e278 in std::__1::__shared_count::__release_shared[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174:9
    #20 0x3058e278 in std::__1::__shared_weak_count::__release_shared[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215:27
    #21 0x3058e278 in std::__1::shared_ptr<DB::HashJoin::RightTableData>::~shared_ptr[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702:23
    #22 0x3058e278 in std::__1::shared_ptr<DB::HashJoin::RightTableData>::reset[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:768:9
    #23 0x3058e278 in DB::HashJoin::releaseJoinedBlocks(bool) build_docker/../src/Interpreters/HashJoin.cpp:2048:14
    #24 0x30566f4b in DB::GraceHashJoin::getDelayedBlocks() build_docker/../src/Interpreters/GraceHashJoin.cpp:561:40
    #25 0x351b05c7 in DB::DelayedJoinedBlocksTransform::work() build_docker/../src/Processors/Transforms/JoiningTransform.cpp:400:28
    #26 0x34ba12c0 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #27 0x34ba12c0 in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #28 0x34b805bc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26
    #29 0x34b84036 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5
    #30 0x34b84036 in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:320:17
    #31 0x34b84036 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #32 0x34b84036 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1
    #33 0x34b84036 in decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1
    #34 0x34b84036 in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:196:13
    #35 0x34b84036 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #36 0x34b84036 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #37 0x34b84036 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #38 0x34b84036 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #39 0x1f3ff0ac in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #40 0x1f3ff0ac in std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #41 0x1f3ff0ac in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:295:17
    #42 0x1f4093bf in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #43 0x1f4093bf in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #44 0x1f4093bf in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5
    #45 0x1f4093bf in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5
    #46 0x7f2f0ba18608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8

previously allocated by thread T265 (QueryPipelineEx) here:
    #0 0xe946f96 in realloc (/usr/bin/clickhouse+0xe946f96) (BuildId: 3b3eb5ac479e2388030e68557e67fa51ba9e50fb)
    #1 0x1f11123b in Allocator<true, true>::realloc(void*, unsigned long, unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:134:30
    #2 0x3120bdfd in HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::resize(unsigned long, unsigned long) build_docker/../src/Common/HashTable/HashTable.h:573:55
    #3 0x305c30e9 in void HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplaceNonZeroImpl<unsigned int&>(unsigned long, unsigned int&, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>*&, bool&, unsigned long) build_docker/../src/Common/HashTable/HashTable.h:971:17
    #4 0x305c30e9 in void HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplaceNonZero<unsigned int&>(unsigned int&, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>*&, bool&, unsigned long) build_docker/../src/Common/HashTable/HashTable.h:999:9
    #5 0x305c30e9 in void HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplace<unsigned int&>(unsigned int&, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>*&, bool&, unsigned long) build_docker/../src/Common/HashTable/HashTable.h:1078:13
    #6 0x305c30e9 in void HashTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplace<unsigned int&>(unsigned int&, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>*&, bool&) build_docker/../src/Common/HashTable/HashTable.h:1069:9
    #7 0x305c30e9 in DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<DB::RowRefList> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, unsigned int, false, true>, PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, false, true>::emplaceImpl<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, unsigned int>(unsigned int&, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&) build_docker/../src/Common/ColumnsHashingImpl.h:209:14
    #8 0x305c30e9 in DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<DB::RowRefList> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, unsigned int, false, true>, PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, false, true>::emplaceKey<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, unsigned long, DB::Arena&) build_docker/../src/Common/ColumnsHashingImpl.h:158:16
    #9 0x305c30e9 in DB::(anonymous namespace)::Inserter<HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, unsigned int, false, true>>::insertAll(DB::HashJoin const&, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, unsigned int, false, true>&, DB::Block*, unsigned long, DB::Arena&) build_docker/../src/Interpreters/HashJoin.cpp:549:46
    #10 0x305c30e9 in unsigned long DB::(anonymous namespace)::insertFromBlockImplTypeCase<(DB::JoinStrictness)3, DB::ColumnsHashing::HashMethodOneNumber<PairNoInit<unsigned int, DB::RowRefList>, DB::RowRefList, unsigned int, false, true>, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false>(DB::HashJoin&, HashMapTable<unsigned int, HashMapCell<unsigned int, DB::RowRefList, HashCRC32<unsigned int>, HashTableNoState>, HashCRC32<unsigned int>, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long>> const&, DB::Block*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, DB::Arena&) build_docker/../src/Interpreters/HashJoin.cpp:602:17
    #11 0x30580f1a in bool static_for_impl<int, 0, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3>(DB::JoinKind, DB::JoinStrictness, std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>), 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3>(DB::JoinKind, DB::JoinStrictness, std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&, std::__1::integer_sequence<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23>) build_docker/../base/base/constexpr_helpers.h
    #12 0x30580f1a in bool static_for<0, 24, bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3>(DB::JoinKind, DB::JoinStrictness, std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)>(bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3>(DB::JoinKind, DB::JoinStrictness, std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3&&)::'lambda'(std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>)&&) build_docker/../base/base/constexpr_helpers.h:31:12
    #13 0x30580f1a in bool DB::joinDispatch<std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3>(DB::JoinKind, DB::JoinStrictness, std::__1::variant<DB::HashJoin::MapsTemplate<DB::RowRef>, DB::HashJoin::MapsTemplate<DB::RowRefList>, DB::HashJoin::MapsTemplate<std::__1::unique_ptr<DB::SortedLookupVectorBase, std::__1::default_delete<DB::SortedLookupVectorBase>>>>&, DB::HashJoin::addJoinedBlock(DB::Block const&, bool)::$_3&&) build_docker/../src/Interpreters/joinDispatch.h:84:12
    #14 0x30580f1a in DB::HashJoin::addJoinedBlock(DB::Block const&, bool) build_docker/../src/Interpreters/HashJoin.cpp:780:17
    #15 0x30560eed in DB::GraceHashJoin::addJoinedBlockImpl(DB::Block) build_docker/../src/Interpreters/GraceHashJoin.cpp:633:20
    #16 0x30560558 in DB::GraceHashJoin::addJoinedBlock(DB::Block const&, bool) build_docker/../src/Interpreters/GraceHashJoin.cpp:320:5
    #17 0x351aa2f0 in DB::FillingRightJoinSideTransform::work() build_docker/../src/Processors/Transforms/JoiningTransform.cpp:308:31
    #18 0x34ba12c0 in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #19 0x34ba12c0 in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #20 0x34b805bc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:229:26
    #21 0x34b84036 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:195:5
    #22 0x34b84036 in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:320:17
    #23 0x34b84036 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #24 0x34b84036 in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/tuple:1789:1
    #25 0x34b84036 in decltype(auto) std::__1::apply[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/llvm-project/libcxx/include/tuple:1798:1
    #26 0x34b84036 in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:196:13
    #27 0x34b84036 in decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #28 0x34b84036 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #29 0x34b84036 in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #30 0x34b84036 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #31 0x1f3ff0ac in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #32 0x1f3ff0ac in std::__1::function<void ()>::operator()() const build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #33 0x1f3ff0ac in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:295:17
    #34 0x1f4093bf in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #35 0x1f4093bf in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #36 0x1f4093bf in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5
    #37 0x1f4093bf in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5
    #38 0x7f2f0ba18608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fix race in grace hash join with limit, close https://github.com/ClickHouse/ClickHouse/issues/45986

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Interpreters/GraceHashJoin.h [hunk 1]
```diff
@@ -139,7 +139,7 @@ class GraceHashJoin final : public IJoin
     mutable SharedMutex rehash_mutex;
 
     FileBucket * current_bucket = nullptr;
-    mutable std::mutex current_bucket_mutex;
+    mutable SharedMutex current_bucket_mutex;
```
Comment (alexey-milovidov) [inline src/Interpreters/GraceHashJoin.h:142]: Let's add a comment on why we need SharedMutex here.

**Comment by devcrafter** [comment]
Discussed a bit with @vdimir. `getDelayedBlocks()` is not supposed to be called before joining current bucket is completed. Technically, the fix should work, but from design PoV looks contradictory

File: src/Interpreters/GraceHashJoin.cpp [hunk 2]
```diff
@@ -410,6 +410,8 @@ void GraceHashJoin::initialize(const Block & sample_block)
 
 void GraceHashJoin::joinBlock(Block & block, std::shared_ptr<ExtraBlock> & not_processed)
 {
+    std::shared_lock current_bucket_lock(current_bucket_mutex);
```
Comment (devcrafter) [inline src/Interpreters/GraceHashJoin.cpp:413]: If we go with the mutex solution now, then rather need to use `hash_join_mutex` here and remove `current_bucket_mutex` at all since we need to synchronize access to in-memory hash join (plus extra info, like bucket it corresponds to).

File: src/Interpreters/GraceHashJoin.h [hunk 3]
```diff
@@ -139,6 +139,8 @@ class GraceHashJoin final : public IJoin
     mutable SharedMutex rehash_mutex;
 
     FileBucket * current_bucket = nullptr;
+
+    /// Function `getDelayedBlocks` is a critical section, we process only one bucket at a time.
```
Comment (devcrafter) [inline src/Interpreters/GraceHashJoin.h:143]: This comment looks misleading. While only one `getDelayedBlocks()` should be executed at a time, it's not because of the mutex, but because of the pipeline is built for grace join. So, probably, better remove it.

In general, this mutex looks redundant. But this matter can be addressed separately to allow now land the fix.

File: src/Processors/Transforms/JoiningTransform.cpp [hunk 4]
```diff
@@ -318,13 +318,21 @@ DelayedJoinedBlocksWorkerTransform::DelayedJoinedBlocksWorkerTransform(Block out
...
     auto & input = inputs.front();
 
+    if (output.isFinished())
+    {
+        input.close();
+        return Status::Finished;
+    }
+
+    if (!output.canPush())
+        return Status::PortFull;
```
Comment (devcrafter) [inline src/Processors/Transforms/JoiningTransform.cpp:331]:
```suggestion
        input.setNotNeeded();
        return Status::PortFull;
```

File: src/Processors/Transforms/JoiningTransform.cpp [hunk 5]
```diff
@@ -397,15 +405,25 @@ DelayedJoinedBlocksTransform::DelayedJoinedBlocksTransform(size_t num_streams, J
...
 
-
 IProcessor::Status DelayedJoinedBlocksTransform::prepare()
 {
     for (auto & output : outputs)
     {
+        if (output.isFinished())
+        {
+            /// If at least one output is finished, then we have read all data from buckets.
+            /// Some workers can still can busy with joining the last chunk of data in memory,
```
Comment (devcrafter) [inline src/Processors/Transforms/JoiningTransform.cpp:422]:
```suggestion
            /// Some workers can still be busy with joining the last chunk of data in memory,
```

**Review by devcrafter — APPROVED** [review]

File: src/Interpreters/GraceHashJoin.h (hunk 3 above)
Comment (vdimir) [inline src/Interpreters/GraceHashJoin.h:143]:
```suggestion
```

File: src/Interpreters/GraceHashJoin.cpp (hunk 2 above)
Comment (vdimir) [reply src/Interpreters/GraceHashJoin.cpp]: Probably `current_bucket_mutex` can be removed since there's only one `DelayedJoinedBlocksTransform` instance, will check with another PR

**Comment by vdimir** [comment]
> Bugfix validate check — Changed tests don't reproduce the bug [Details](https://s3.amazonaws.com/clickhouse-test-reports/47153/3076e929802c56fa9e38770f56a02e0622233e02/bugfix_validate_check.html)

Race is not 100% each time reproducible.


> Integration tests (tsan) [6/6] — fail: 1, passed: 420, flaky: 0 [Details](https://s3.amazonaws.com/clickhouse-test-reports/47153/3076e929802c56fa9e38770f56a02e0622233e02/integration_tests__tsan__[6/6].html)

❓ `test_merge_tree_s3/test.py::test_attach_detach_partition` 
```python
assert (
            len(list(minio.list_objects(cluster.minio_bucket, "data/")))
            == FILES_OVERHEAD + FILES_OVERHEAD_PER_PART_WIDE * 1
        )
E       AssertionError: assert 15 == (1 + (15 * 1))
```

> Stateless tests (debug, s3 storage) [3/6] — fail: 1, passed: 806, skipped: 17 [Details](https://s3.amazonaws.com/clickhouse-test-reports/47153/3076e929802c56fa9e38770f56a02e0622233e02/stateless_tests__debug__s3_storage__[3/6].html)

`02232_dist_insert_send_logs_level_hung`

> Upgrade check (asan) — Error message in clickhouse-server.log (see upgrade_error_messages.txt) [Details](https://s3.amazonaws.com/clickhouse-test-reports/47153/3076e929802c56fa9e38770f56a02e0622233e02/upgrade_check__asan_.html)


Issue https://github.com/ClickHouse/ClickHouse/issues/47200
