### PR TITLE
Fix LOGICAL_ERROR when Merge table tries to read from parametrized view

### LINKED ISSUE #74703: Logical error: 'No available columns'. (`StorageMerge.cpp:1245: DB::ReadFromMerge::createPlanForTable`)
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/74548/332210bfb9d8b41e60680fff92d38c24925e5e6e/stress_test__tsan_/fatal_messages.txt

### How to reproduce

_No response_

### Error message and/or stacktrace
```
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:26:43.772560 [ 15653 ] {d8873735-d663-4f72-b925-a1b22a011679} <Fatal> : Logical error: 'No available columns'.
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:26:44.149663 [ 15653 ] {d8873735-d663-4f72-b925-a1b22a011679} <Fatal> : Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.781740 [ 35456 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.781921 [ 35456 ] {} <Fatal> BaseDaemon: (version 25.1.1.3309, build id: 27E775F2B165752C420AAB042D0C7D51B85472E0, git hash: 13681f053bc11b9cba2d9ec0cdfc1858827bbcca, architecture: x86_64) (from thread 15653) Received signal 6
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.782046 [ 35456 ] {} <Fatal> BaseDaemon: Signal description: Aborted
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.782130 [ 35456 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.796880 [ 35456 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055aadb2a517d 0x000055aadb6ade02 0x000055aad28fd7a6 0x000055aad28fdcfb 0x00007f3f2a7f1520 0x00007f3f2a8459fd 0x00007f3f2a7f1476 0x00007f3f2a7d77f3 0x000055aad28fc267 0x000055aadb25ebe7 0x000055aadb25fe8a 0x000055aad29827be 0x000055aad29915fa 0x000055aae401772f 0x000055aae6d1296e 0x000055aae6d0b37b 0x000055aae6d0767e 0x000055aae6d1b8d7 0x000055aae85a9d86 0x000055aae85a9c16 0x000055aae85a80a8 0x000055aae84a6678 0x000055aae4aaba57 0x000055aae4aab6b0 0x000055aae4f3e162 0x000055aae4f38ed6 0x000055aae7ceb165 0x000055aae7d11788 0x000055aaeccf6ea3 0x000055aaeccf7712 0x000055aaecc70d83 0x000055aaecc6f090 0x000055aaecc6d44a 0x000055aad28f5428 0x00007f3f2a843ac3 0x00007f3f2a8d5850
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.797050 [ 35456 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.834850 [ 35456 ] {} <Fatal> BaseDaemon: (version 25.1.1.3309, build id: 27E775F2B165752C420AAB042D0C7D51B85472E0, git hash: 13681f053bc11b9cba2d9ec0cdfc1858827bbcca) (from thread 15653) (query_id: d8873735-d663-4f72-b925-a1b22a011679) (query: select toTypeName(x), x FROM m_table SETTINGS additional_table_filters = {'m_table':'x != 4'}, optimize_move_to_prewhere=1, enable_analyzer=1;) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.835080 [ 35456 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:10.835239 [ 35456 ] {} <Fatal> BaseDaemon: Stack trace: 0x000055aadb2a517d 0x000055aadb6ade02 0x000055aad28fd7a6 0x000055aad28fdcfb 0x00007f3f2a7f1520 0x00007f3f2a8459fd 0x00007f3f2a7f1476 0x00007f3f2a7d77f3 0x000055aad28fc267 0x000055aadb25ebe7 0x000055aadb25fe8a 0x000055aad29827be 0x000055aad29915fa 0x000055aae401772f 0x000055aae6d1296e 0x000055aae6d0b37b 0x000055aae6d0767e 0x000055aae6d1b8d7 0x000055aae85a9d86 0x000055aae85a9c16 0x000055aae85a80a8 0x000055aae84a6678 0x000055aae4aaba57 0x000055aae4aab6b0 0x000055aae4f3e162 0x000055aae4f38ed6 0x000055aae7ceb165 0x000055aae7d11788 0x000055aaeccf6ea3 0x000055aaeccf7712 0x000055aaecc70d83 0x000055aaecc6f090 0x000055aaecc6d44a 0x000055aad28f5428 0x00007f3f2a843ac3 0x00007f3f2a8d5850
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:11.069226 [ 35456 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./build_docker/./src/Common/StackTrace.cpp:381: StackTrace::tryCapture()
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:11.069453 [ 35456 ] {} <Fatal> BaseDaemon: 0. ./build_docker/./src/Common/StackTrace.cpp:350: StackTrace::StackTrace(ucontext_t const&) @ 0x000000001077317d
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:11.353347 [ 35456 ] {} <Fatal> BaseDaemon: 1. ./build_docker/./src/Common/SignalHandlers.cpp:102: signalHandler(int, siginfo_t*, void*) @ 0x0000000010b7be02
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:12.161683 [ 35456 ] {} <Fatal> BaseDaemon: 2. __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, int, __sanitizer::__sanitizer_siginfo*, void*) @ 0x0000000007dcb7a6
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:12.483631 [ 35456 ] {} <Fatal> BaseDaemon: 3. sighandler(int, __sanitizer::__sanitizer_siginfo*, void*) @ 0x0000000007dcbcfb
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:12.484107 [ 35456 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007f3f2a7f1520
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:12.484264 [ 35456 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007f3f2a8459fd
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:12.484376 [ 35456 ] {} <Fatal> BaseDaemon: 6. ? @ 0x00007f3f2a7f1476
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:12.484505 [ 35456 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007f3f2a7d77f3
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:13.408054 [ 35456 ] {} <Fatal> BaseDaemon: 8. ___interceptor_abort @ 0x0000000007dca267
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:13.664043 [ 35456 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x000000001072cbe7
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:13.859102 [ 35456 ] {} <Fatal> BaseDaemon: 10.0. inlined from ./build_docker/./src/Common/Exception.cpp:70: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:13.859253 [ 35456 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001072de8a
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:13.985215 [ 35456 ] {} <Fatal> BaseDaemon: 11. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e507be
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:14.215526 [ 35456 ] {} <Fatal> BaseDaemon: 12. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x0000000007e5f5fa
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:14.890155 [ 35456 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Interpreters/ExpressionActions.cpp:863: DB::ExpressionActions::getSmallestColumn(DB::NamesAndTypesList const&) @ 0x00000000194e572f
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:16.275378 [ 35456 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Storages/StorageMerge.cpp:1245: DB::ReadFromMerge::createPlanForTable(std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, DB::QueryProcessingStage::Enum, unsigned long, std::tuple<String, std::shared_ptr<DB::IStorage>, std::shared_ptr<DB::RWLockImpl::LockHolderImpl>, String> const&, std::vector<String, std::allocator<String>> const&, std::optional<DB::ReadFromMerge::RowPolicyData> const&, std::shared_ptr<DB::Context>, unsigned long) const @ 0x000000001c1e096e
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:16.841969 [ 35456 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Storages/StorageMerge.cpp:707: DB::ReadFromMerge::createChildrenPlans(DB::SelectQueryInfo&) const @ 0x000000001c1d937b
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:18.063658 [ 35456 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Storages/StorageMerge.cpp:567: DB::ReadFromMerge::filterTablesAndCreateChildrenPlans() @ 0x000000001c1d567e
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:19.640146 [ 35456 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Storages/StorageMerge.cpp:1680: DB::ReadFromMerge::applyFilters(DB::ActionDAGNodes) @ 0x000000001c1e98d7
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:19.690534 [ 35456 ] {} <Fatal> BaseDaemon: 18. ./src/Processors/QueryPlan/SourceStepWithFilter.h:65: DB::SourceStepWithFilter::applyFilters() @ 0x000000001da77d86
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:19.752520 [ 35456 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./src/Processors/QueryPlan/Optimizations/optimizePrimaryKeyConditionAndLimit.cpp:50: DB::QueryPlanOptimizations::optimizePrimaryKeyConditionAndLimit(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>> const&) @ 0x000000001da77c16
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:19.816772 [ 35456 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:119: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x000000001da760a8
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:19.964150 [ 35456 ] {} <Fatal> BaseDaemon: 21.0. inlined from ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:487: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&)
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:19.964377 [ 35456 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:174: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x000000001d974678
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:20.369928 [ 35456 ] {} <Fatal> BaseDaemon: 22. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:261: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x0000000019f79a57
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:20.580671 [ 35456 ] {} <Fatal> BaseDaemon: 23. ./build_docker/./src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:228: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x0000000019f796b0
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:21.452106 [ 35456 ] {} <Fatal> BaseDaemon: 24. ./build_docker/./src/Interpreters/executeQuery.cpp:1441: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001a40c162
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:22.121750 [ 35456 ] {} <Fatal> BaseDaemon: 25. ./build_docker/./src/Interpreters/executeQuery.cpp:1608: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001a406ed6
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:22.530365 [ 35456 ] {} <Fatal> BaseDaemon: 26. ./build_docker/./src/Server/TCPHandler.cpp:658: DB::TCPHandler::runImpl() @ 0x000000001d1b9165
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:23.578770 [ 35456 ] {} <Fatal> BaseDaemon: 27. ./build_docker/./src/Server/TCPHandler.cpp:2625: DB::TCPHandler::run() @ 0x000000001d1df788
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:23.591287 [ 35456 ] {} <Fatal> BaseDaemon: 28. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000221c4ea3
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:23.608318 [ 35456 ] {} <Fatal> BaseDaemon: 29. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000221c5712
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:23.626873 [ 35456 ] {} <Fatal> BaseDaemon: 30. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000002213ed83
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:23.648375 [ 35456 ] {} <Fatal> BaseDaemon: 31. ./build_docker/./base/poco/Foundation/src/Thread.cpp:45: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000002213d090
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:23.666669 [ 35456 ] {} <Fatal> BaseDaemon: 32. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000002213b44a
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:24.647139 [ 35456 ] {} <Fatal> BaseDaemon: 33. __tsan_thread_start_func @ 0x0000000007dc3428
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:24.647569 [ 35456 ] {} <Fatal> BaseDaemon: 34. ? @ 0x00007f3f2a843ac3
/var/log/clickhouse-server/clickhouse-server.err.log:2025.01.16 13:28:24.647656 [ 35456 ] {} <Fatal> BaseDaemon: 35. ? @ 0x00007f3f2a8d5850
```

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Stress test failed like this: https://github.com/ClickHouse/ClickHouse/issues/74703 . There was a Merge table that merges lots of tables (everything named `test.*` in the whole stress test). The error implies that one of these tables had `StorageInMemoryMetadata` with no physical columns.

I spent a while skimming the `create table test.*` queries in server log looking for weird engines or column attributes or data types and trying to reproduce the error using those `create table` statements, but failed.

Also skimmed call sites of `setInMemoryMetadata` looking for one that may pass empty list of columns, and found one: patametrized view (when no parameters were passed). And it reproduces the crash!:
```sql
create view v as select number from numbers(5) where number%2={parity:Int8};
create table vv (number Int8) engine Merge('default','v');
select * from vv;
```

But the stress test failure was probably caused by something else as there's no `create view (default\.)?test[^\. ]* .*\{` in server log.

So this PR makes StorageMerge:
 * Check for parametrized view and throw a non-LOGICAL_ERROR.
 * Add child table name to exception message.
 * Print child table name before building query plan for that table (because in debug build the server will SIGABRT on LOGICAL_ERROR before reaching the code that extends the exception message). This should make this more investigatable next time it happens.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/74703

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 6b61125a32c58a23c5e62cb9c2b2fb52cb811e25 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75318/6b61125a32c58a23c5e62cb9c2b2fb52cb811e25/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/88ddc3c17d397a7ccdb23bf7878bae7b0a5c9935/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Storages/StorageMerge.cpp [hunk 1]
```diff
@@ -604,142 +605,164 @@ std::vector<ReadFromMerge::ChildPlan> ReadFromMerge::createChildrenPlans(SelectQ
...
-            if (with_aliases)
+            if (storage_metadata_snapshot->getColumns().empty())
             {
-                ASTPtr required_columns_expr_list = std::make_shared<ASTExpressionList>();
-                ASTPtr column_expr;
+                /// (Assuming that view has empty list of columns iff it's parametrized.)
+                if (storage->isView())
+                    throw Exception(ErrorCodes::STORAGE_REQUIRES_PARAMETER, "Parametrized view can't be queried through a Merge table.");
+                else
+                    throw Exception(ErrorCodes::LOGICAL_ERROR, "Table has no columns.");
```
Comment (al13n321) [inline src/Storages/StorageMerge.cpp:644]: (The real changes are: this, `getLogger` call above, and try-catch outside this. Everything else is indentation change from wrapping code in try-catch. Idk why git/github's diff algorithm failed so badly on this.)

**Comment by azat** [comment]
We need this to make CI greener :)

File: src/Storages/StorageMerge.cpp [hunk 2]
```diff
@@ -604,142 +605,164 @@ std::vector<ReadFromMerge::ChildPlan> ReadFromMerge::createChildrenPlans(SelectQ
         query_info_.input_order_info = input_sorting_info;
     }
 
+    auto logger = getLogger("StorageMerge");
```
Comment (azat) [inline src/Storages/StorageMerge.cpp:608]: BTW maybe it make sense to make it a member already (we can include a Merge table name as well there, as for MergeTree)?

Comment (kssenii) [reply src/Storages/StorageMerge.cpp:608]: Let's do this in follow-up PR, this PR is too green, it would be a shame not to merge :)
