### PR TITLE
Fix toDecimalOrNull() with exception inside

### LINKED ISSUE #8312: toDecimal128OrNull throws an exception but it is supposed to return Null
```
SELECT toDecimal128OrNull('ee', 1)

┌─toDecimal128OrNull('ee', 1)─┐
│                        ᴺᵁᴸᴸ │
└─────────────────────────────┘

SELECT toDecimal128OrNull('e', 1)

Received exception from server (version 19.17.4):
Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof.
```

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Fix `toDecimal*OrNull()` functions family when called with string 'e'. Fixes #8312

Detailed description (optional):
Better check for wrong decimal parcing.

### CODE REVIEW

**Comment by 4ertus2** [comment]
#8312

File: dbms/src/IO/readDecimalText.h [hunk 1]
```diff
@@ -145,10 +132,17 @@ inline bool tryReadDecimalText(ReadBuffer & buf, T & x, unsigned int precision,
...
-        static_cast<int>(digits) + exponent > static_cast<int>(precision - scale) ||
-        static_cast<int>(scale) + exponent < 0)
+    try
+    {
+        readDigits(buf, x, digits, exponent, true);
+        if (static_cast<int>(digits) + exponent > static_cast<int>(precision - scale) ||
+            static_cast<int>(scale) + exponent < 0)
+            return false;
+    }
+    catch (const Exception &)
```
Comment (alexey-milovidov) [inline dbms/src/IO/readDecimalText.h]: This is extremely slow in exceptional case.
Not viable solution to process column data.

**Review by alexey-milovidov — APPROVED** [review]
