### PR TITLE
mark window functions as ready for general use

### LINKED ISSUE #26396: remove experimental status of window functions
Blocking issues:

- [x] broken null handling, need to refactor to add deeper separation between window and aggregate functions https://github.com/ClickHouse/ClickHouse/issues/26115
- [ ] expression analyzer woes, not all expression dependencies are handled properly https://github.com/ClickHouse/ClickHouse/issues/24892
- [x] a mystery ubsan failure that doesn't reproduce https://github.com/ClickHouse/ClickHouse/issues/24184
- [x] a segfault found by fuzzer https://github.com/ClickHouse/ClickHouse/issues/25276
- [x] https://github.com/ClickHouse/ClickHouse/issues/26580

### PR DESCRIPTION
**Pull request by akuzm**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Mark window functions as ready for general use. Remove the `allow_experimental_window_functions` setting.

Fixes https://github.com/ClickHouse/ClickHouse/issues/26396

### CODE REVIEW

File: src/Core/Settings.h [hunk 1]
```diff
@@ -449,7 +449,6 @@ class IColumn;
     M(Bool, optimize_skip_merged_partitions, false, "Skip partitions with one part with level > 0 in optimize final", 0) \
     M(Bool, optimize_on_insert, true, "Do the same transformation for inserted block of data as if merge was done on this block.", 0) \
     M(Bool, allow_experimental_map_type, true, "Obsolete setting, does nothing.", 0) \
-    M(Bool, allow_experimental_window_functions, false, "Allow experimental window functions", 0) \
```
Comment (kitaisreal) [inline src/Core/Settings.h:452]: Previously when I make map type not experimental I just converted setting to dummy
```
M(Bool, allow_experimental_map_type, true, "Obsolete setting, does nothing.", 0)
```
It seems that it can be just removed, right ?

**Review by kitaisreal — APPROVED** [review]

File: src/Core/Settings.h (hunk 1 above)
Comment (akuzm) [reply src/Core/Settings.h:452]: I think yes, because it was experimental. There might be some problems (not sure which problems exactly) when e.g. doing an upgrade, so we sometimes keep the old settings for several releases before removing them, but for experimental ones this is not needed.

**Comment by akuzm** [comment]
The errors are expected.

File: src/Core/Settings.h (hunk 1 above)
Comment (alexey-milovidov) [reply src/Core/Settings.h:452]: @kitaisreal This PR breaks everything:

```
2021.08.08 18:05:42.564335 [ 1433476 ] {} <Error> Application: DB::Exception: Unknown setting allow_experimental_window_functions
2021.08.08 18:05:42.564371 [ 1433476 ] {} <Information> Application: shutting down
2021.08.08 18:05:42.564377 [ 1433476 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.08.08 18:05:42.564579 [ 1433477 ] {} <Trace> BaseDaemon: Received signal -2
2021.08.08 18:05:42.564616 [ 1433477 ] {} <Information> BaseDaemon: Stop SignalListener thread
2021.08.08 18:05:42.586497 [ 1433468 ] {} <Information> Application: Child process exited normally with code 70.
```

**Comment by alexey-milovidov** [comment]
@akuzm You merged it too early.
