### PR TITLE
Parse data in JSON format as JSONEachRow if failed to parse metadata

### LINKED ISSUE #45740: Automatically distinguish between JSON and JSONEachRow for format autodetection.
Quite often files are named .json when they should be .jsonl or .ndjson.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Parse data in JSON format as JSONEachRow if failed to parse metadata. It will allow to read files with `.json` extension even if real format is JSONEachRow. Closes https://github.com/ClickHouse/ClickHouse/issues/45740

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 2fcd07712bb1ace82a430ad4e6bfad5513057893 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/54405/2fcd07712bb1ace82a430ad4e6bfad5513057893/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Processors/Formats/Impl/JSONRowInputFormat.cpp [hunk 1]
```diff
@@ -12,42 +12,95 @@ namespace ErrorCodes
...
+        JSONUtils::skipObjectStart(*peekable_buf);
+        names_and_types_from_metadata = JSONUtils::readMetadata(*peekable_buf);
+        JSONUtils::skipComma(*peekable_buf);
+        if (!JSONUtils::skipUntilFieldInObject(*peekable_buf, "data"))
+            throw Exception(ErrorCodes::INCORRECT_DATA, "Expected field \"data\" with table content");
+
+        JSONUtils::skipArrayStart(*peekable_buf);
+        data_in_square_brackets = true;
+    }
+    catch (...)
```
Comment (antaljanosbenjamin) [inline src/Processors/Formats/Impl/JSONRowInputFormat.cpp:43]: What about constraining the possible exceptions here? E.g.: if something goes wrong by reading in the underlying buffer, we just silently fall over trying to parse the json as `JSONEachRow`. I think it would be nice to constraint the possible exceptions:
- `Exception` with `ErrorCodes::INCORRECT_DATA` code for `JSONUtils::readMetadata` and line 38
- `ParsingException`for `JSONUtils::skipXXX` functions and general parsing errors

Comment (Avogar) [reply src/Processors/Formats/Impl/JSONRowInputFormat.cpp:43]: Yeah, that's good idea, I will try

**Review by antaljanosbenjamin — APPROVED** [review]
