### PR TITLE
Fix dynamic subcolumns resolution in column aliases in analyzer

### LINKED ISSUE #91434: Performance degradation when using ALIAS column with new JSON data type compared to direct JSON field access
### Company or project name

_No response_

### Describe the situation

When using the new JSON data type, selecting a field via an ALIAS column produces significantly worse performance compared to selecting the same field directly from the JSON object.

### Which ClickHouse versions are affected?

25.11.2

### How to reproduce

```sql
CREATE TABLE default.json_test (
    json JSON,
    col_a Int64 ALIAS json.a
) ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO default.json_test
SELECT formatRow('JSONEachRow',
                 number as a,
                 number / 10 as b,
                 number / 100 as c,
                 number / 1000 as d,
                 number / 10000 as e)
FROM numbers(10000000);

OPTIMIZE TABLE default.json_test FINAL;
```
Query 1 — Using ALIAS column
```sql
SELECT col_a FROM default.json_test FORMAT Null;
0.309 sec
```

Query 2 — Direct JSON field access
```sql
SELECT json.a AS col_a FROM default.json_test FORMAT Null;
0.047 sec
```
Its getting worse with bigger JSON

### Expected performance

Selecting an alias of a JSON field should have similar performance than accessing the JSON field directly.

### Additional context

Profile events query 1 
```json
{

   "Query":1,
   "SelectQuery":1,
   "InitialQuery":1,
   "QueriesWithSubqueries":1,
   "SelectQueriesWithSubqueries":1,
   "FileOpen":28,
   "ReadBufferFromFileDescriptorReadBytes":251771438,
   "ReadCompressedBytes":248990021,
   "CompressedReadBufferBlocks":7325,
   "CompressedReadBufferBytes":482736197,
   "OpenedFileCacheHits":66,
   "OpenedFileCacheMisses":28,
   "OpenedFileCacheMicroseconds":43,
   "IOBufferAllocs":156,
   "IOBufferAllocBytes":13885702,
   "FunctionExecute":2338,
   "MarkCacheHits":94,
   "CreatedReadBufferOrdinary":94,
   "DiskReadElapsedMicroseconds":67706,
   "RealTimeMicroseconds":1544836
}
```
Profile events query 2
```json
{
   "Query":1,
   "SelectQuery":1,
   "InitialQuery":1,
   "QueriesWithSubqueries":1,
   "SelectQueriesWithSubqueries":1,
   "FileOpen":5,
   "ReadBufferFromFileDescriptorReadBytes":40864598,
   "ReadCompressedBytes":40049383,
   "CompressedReadBufferBlocks":1228,
   "CompressedReadBufferBytes":80026141,
   "OpenedFileCacheHits":9,
   "OpenedFileCacheMisses":5,
   "DiskReadElapsedMicroseconds":7514,
   "RealTimeMicroseconds":230654
}
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix dynamic subcolumns resolution in column aliases in analyzer. Previously dynamic subcolumn in column alias was wrapped in `getSubcolumn` and in some cases could be not resolved at all. Closes https://github.com/ClickHouse/ClickHouse/issues/91434

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.379`
- Backported to: `25.12.3.11`, `25.11.7.28`, `25.10.5.30`, `25.8.15.25`, `25.3.14.5`

### CODE REVIEW

**Comment by Avogar** [comment]
@novikd kind ping

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 1]
```diff
@@ -3661,7 +3661,8 @@ void QueryAnalyzer::initializeTableExpressionData(const QueryTreeNodePtr & table
             alias_column_to_resolve = column_name_to_column_node[alias_column_to_resolve_name];
 
             IdentifierResolveScope & alias_column_resolve_scope = createIdentifierResolveScope(alias_column_to_resolve, &scope /*parent_scope*/);
-            alias_column_resolve_scope.column_name_to_column_node = std::move(column_name_to_column_node);
+            table_expression_data.column_name_to_column_node = std::move(column_name_to_column_node);
```
Comment (novikd) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp]: Actually, in this `for` cycle we are filling the `column_name_to_column_node` mapping and set it in the table expression data imideately after the cycle:
```c++
table_expression_data.column_name_to_column_node = std::move(column_name_to_column_node);
```
I suggest doing it before the cycle and just reuse `table_expression_data.column_name_to_column_node`.

**Review by novikd — APPROVED** [review]
LGTM
