### PR TITLE
Avoid reusing columns among different named tuples

### LINKED ISSUE #70022: 24.7 broke some queries using `tuple()` and NULLs
The change in behavior of the `tuple()` function in 24.7 (https://github.com/ClickHouse/ClickHouse/pull/54881) seems to break some INSERT SELECT requests with two similar tuples in different columns. 

I found one case (using `tuple()`, NULLs, grouping and array) where a query :

- crashes since 24.7 : https://fiddle.clickhouse.com/7446614a-4743-4729-958c-b3142a29e89c
- works in 24.6.6.6 : https://fiddle.clickhouse.com/22c57812-2a36-44e1-a61f-83283d03256b

And one simpler case (using `tuple()` and NULLs) where the result between the INSERT SELECT and the SELECT
- is different since 24.7 : https://fiddle.clickhouse.com/22ee195e-7151-4be9-bdac-e87432a64407 
- was the same in 24.6.6.6 : https://fiddle.clickhouse.com/5f9727fe-c602-4f2f-b4b5-7c58a698d224

From the error message it looks like the names of the elements from the two Tuple columns are being mixed up.

**Expected behavior**

The behavior of 24.6.6.6 was correct

**Error message and/or stacktrace**

```
Received exception from server (version 24.8.4):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Cannot capture column 2 because it has incompatible type: got Tuple(col_a Nullable(String), type String), but Tuple(col_b Nullable(String), type String) is expected.. (LOGICAL_ERROR)
```

**Additional context**

For the crashing case :

- When removing the `arraySort()` the query works in 24.7 and latest but the result is different than in 24.6.6.6 (and wrong).
- Using `NULL` instead of `nullIf(data, '')` gives the same error.
- Using `data` instead of `nullIf(data, '')` gives the same behavior as when removing the `arraySort()`

In my original use case the two `nullIf(data, '')` are two different templeted JSON extraction function, sometimes at `NULL` based on our workflow.

I hope there is enough context to identify what is causing this bug.

EDIT : added link to fiddles in the last working version

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid reusing columns among different named tuples when evaluating `tuple` functions. This fixes #70022

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 5d798cc46c94918e19cdf6db18bdedf561c342a7 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70103/5d798cc46c94918e19cdf6db18bdedf561c342a7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/924e21f632d22ad26b8380f3286666715d448270/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Planner/PlannerActionsVisitor.cpp [hunk 1]
```diff
@@ -182,6 +182,30 @@ class ActionNodeNameHelper
                     break;
                 }
 
+                /// Function "tuple" which generates named tuple should use argument aliases to construct its name.
+                if (function_node.getFunctionName() == "tuple")
+                {
+                    if (const DataTypeTuple * type_tuple = typeid_cast<const DataTypeTuple *>(function_node.getResultType().get()))
+                    {
+                        if (type_tuple->haveExplicitNames())
```
Comment (novikd) [inline src/Planner/PlannerActionsVisitor.cpp:190]: This will likely not work in the distributed case because the query on the follower node won't have `AS col_a` and `AS col_b` for the `tuple` function argument. I think a proper fix would also include creating a cast operation.

Comment (novikd) [reply src/Planner/PlannerActionsVisitor.cpp:190]: Also, I think that such code should check `enable_named_columns_in_function_tuple` setting.

Comment (amosbird) [reply src/Planner/PlannerActionsVisitor.cpp]: > This will likely not work in the distributed case because the query on the follower node won't have `AS col_a` and `AS col_b` for the `tuple` function argument. I think a proper fix would also include creating a cast operation.

It works because we do `addConvertingActions` in ReadFromRemote step. I've added a test case to verify this.

> Also, I think that such code should check enable_named_columns_in_function_tuple setting.

Sure.

File: src/Planner/PlannerActionsVisitor.cpp [hunk 2]
```diff
@@ -182,6 +183,33 @@ class ActionNodeNameHelper
...
+                            {
+                                const auto & names = type_tuple->getElementNames();
+                                size_t size = names.size();
+                                WriteBufferFromOwnString s;
+                                s << "tuple(";
+                                for (size_t i = 0; i < size; ++i)
+                                {
+                                    if (i != 0)
+                                        s << ", ";
+                                    s << names[i];
```
Comment (alexey-milovidov) [inline src/Planner/PlannerActionsVisitor.cpp:203]: Missing escaping.

**Comment by Algunenano** [comment]
A case that's not covered by this fix:

```
DROP TABLE IF EXISTS src;
DROP TABLE IF EXISTS target;
SET flatten_nested = 0;

CREATE TABLE src
(
    id UInt64,
    minmax Nested(
        min Float64,
        max Float64,
    )
)
ENGINE = MergeTree
ORDER BY (id);

CREATE TABLE target AS src;


INSERT INTO src VALUES (0, [(-10, 10)]);


INSERT INTO target
SELECT
    id,
    groupArray(tuple(bucket_min, bucket_max))
FROM
(
    SELECT
        id,
        minmax.1 AS bucket_min,
        minmax.2 AS bucket_max
    FROM
    (
        select
            id, arrayJoin(minmax) as minmax
        FROM src
    )
)
GROUP BY id;

SELECT * FROM target;
```

```
$ clickhouse local --queries-file repro.sql --enable_named_columns_in_function_tuple=0
0       [(-10,10)]
$ clickhouse local --queries-file repro.sql --enable_named_columns_in_function_tuple=1
0       [(0,0)]
```

I'm going to disable with setting by default (and backport) in the meantime.

**Comment by amosbird** [comment]
> A case that's not covered by this fix:

```
create table x (t Tuple(a int, b int)) engine MergeTree order by ();
insert into x select (1 as a2, 2 as b2);
select * from x format JSONEachRow;

{"t":{"a":0,"b":0}}
```
We never support inserting `Tuple(a2 int, b2 int)` into `Tuple(a int, b int)`, but it's fine to insert `Tuple(int, int)` into `Tuple(a int, b int)`. I'm not sure what's the expected behavior. Maybe we should keep this feature disabled by default?

**Comment by rschu1ze** [comment]
Just for reference: Setting `enable_named_columns_in_function_tuple` was disabled here: https://github.com/ClickHouse/ClickHouse/pull/70833

**Comment by alexey-milovidov** [comment]
@amosbird, please enable it back in a subsequent pull request.

**Comment by amosbird** [comment]
> please enable it back in a subsequent pull request.

@alexey-milovidov Sure. I'll mention this backward incompatibility in the following PR https://github.com/ClickHouse/ClickHouse/pull/70103#issuecomment-2423417333
