### PR TITLE
Fix data race in StorageFile

### LINKED ISSUE #34111: Data race in `StorageFile::read`
https://s3.amazonaws.com/clickhouse-test-reports/0/277fe4e1c4eaf45708c4eedc640136d387c7f869/stateless_tests__thread__actions__[1/3].html

```
WARNING: ThreadSanitizer: data race (pid=386)
  Read of size 8 at 0x7b6800b60370 by thread T458:
    #0 std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >::release() obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1648:26 (clickhouse+0x18c06640)
    #1 std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >::unique_ptr(std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1554:20 (clickhouse+0x18c06640)
    #2 void std::__1::allocator<DB::StorageFileSource>::construct<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(DB::StorageFileSource*, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:886:32 (clickhouse+0x18c06640)
    #3 void std::__1::allocator_traits<std::__1::allocator<DB::StorageFileSource> >::__construct<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::StorageFileSource>&, DB::StorageFileSource*, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:519:21 (clickhouse+0x18c0006d)
    #4 void std::__1::allocator_traits<std::__1::allocator<DB::StorageFileSource> >::construct<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(std::__1::allocator<DB::StorageFileSource>&, DB::StorageFileSource*, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:481:14 (clickhouse+0x18c0006d)
    #5 std::__1::__shared_ptr_emplace<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource> >::__shared_ptr_emplace<std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(std::__1::allocator<DB::StorageFileSource>, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2594:9 (clickhouse+0x18c0006d)
    #6 std::__1::shared_ptr<DB::StorageFileSource> std::__1::allocate_shared<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource>, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >, void>(std::__1::allocator<DB::StorageFileSource> const&, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3360:55 (clickhouse+0x18c0006d)
    #7 std::__1::shared_ptr<DB::StorageFileSource> std::__1::make_shared<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >, void>(std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3369:12 (clickhouse+0x18c0006d)
    #8 DB::StorageFile::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageFile.cpp:623:28 (clickhouse+0x18c0006d)
    #9 DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/IStorage.cpp:113:17 (clickhouse+0x18b99ce3)
    #10 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1981:18 (clickhouse+0x18239423)
    #11 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #12 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #13 DB::ClusterProxy::(anonymous namespace)::createLocalPlan(std::__1::shared_ptr<DB::IAST> const&, DB::Block const&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned int, unsigned int) obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:84:17 (clickhouse+0x18be340b)
    #14 DB::ClusterProxy::SelectStreamFactory::createForShard(DB::Cluster::ShardInfo const&, std::__1::shared_ptr<DB::IAST> const&, DB::StorageID const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> > > >&, std::__1::vector<DB::ClusterProxy::IStreamFactory::Shard, std::__1::allocator<DB::ClusterProxy::IStreamFactory::Shard> >&, unsigned int)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:105:34 (clickhouse+0x18be340b)
    #15 DB::ClusterProxy::SelectStreamFactory::createForShard(DB::Cluster::ShardInfo const&, std::__1::shared_ptr<DB::IAST> const&, DB::StorageID const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> > > >&, std::__1::vector<DB::ClusterProxy::IStreamFactory::Shard, std::__1::allocator<DB::ClusterProxy::IStreamFactory::Shard> >&, unsigned int) obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:161:13 (clickhouse+0x18be1e2a)
    #16 DB::ClusterProxy::executeQuery(DB::QueryPlan&, DB::Block const&, DB::QueryProcessingStage::Enum, DB::StorageID const&, std::__1::shared_ptr<DB::IAST> const&, DB::ClusterProxy::IStreamFactory&, Poco::Logger*, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Cluster> const&) obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/executeQuery.cpp:167:24 (clickhouse+0x18be5bb5)
    #17 DB::StorageDistributed::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageDistributed.cpp:647:5 (clickhouse+0x18bcfed2)
    #18 DB::StorageDistributed::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageDistributed.cpp:600:5 (clickhouse+0x18bcf2ce)
    #19 DB::StorageMerge::createSources(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, DB::QueryProcessingStage::Enum const&, unsigned long, DB::Block const&, std::__1::vector<DB::StorageMerge::AliasData, std::__1::allocator<DB::StorageMerge::AliasData> > const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IStorage>, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::shared_ptr<DB::Context>, unsigned long, bool, bool, bool) obj-x86_64-linux-gnu/../src/Storages/StorageMerge.cpp:457:25 (clickhouse+0x18c8cbff)
    #20 DB::StorageMerge::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageMerge.cpp:383:28 (clickhouse+0x18c89e55)
    #21 DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/IStorage.cpp:113:17 (clickhouse+0x18b99ce3)
    #22 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1981:18 (clickhouse+0x18239423)
    #23 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #24 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #25 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:264:38 (clickhouse+0x1856aaf6)
    #26 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1902:31 (clickhouse+0x18238446)
    #27 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #28 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #29 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:274:37 (clickhouse+0x1856afe7)
    #30 DB::StorageView::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageView.cpp:145:17 (clickhouse+0x18dd7eab)
    #31 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1981:18 (clickhouse+0x18239423)
    #32 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #33 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #34 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:264:38 (clickhouse+0x1856aaf6)
    #35 DB::InterpreterSelectWithUnionQuery::execute() obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:331:5 (clickhouse+0x1856bbf8)
    #36 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:666:36 (clickhouse+0x187ddd4c)
    #37 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:985:30 (clickhouse+0x187dba61)
    #38 DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:333:24 (clickhouse+0x193ec0b8)
    #39 DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1909:9 (clickhouse+0x19401627)
    #40 Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1c434da2)
    #41 Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1c435612)
    #42 Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14 (clickhouse+0x1c68c935)
    #43 Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1c68aacf)
    #44 Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1c689147)

  Previous write of size 8 at 0x7b6800b60370 by thread T1069:
    #0 std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >::release() obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1649:20 (clickhouse+0x18c0664b)
    #1 std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >::unique_ptr(std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1554:20 (clickhouse+0x18c0664b)
    #2 void std::__1::allocator<DB::StorageFileSource>::construct<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(DB::StorageFileSource*, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:886:32 (clickhouse+0x18c0664b)
    #3 void std::__1::allocator_traits<std::__1::allocator<DB::StorageFileSource> >::__construct<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::StorageFileSource>&, DB::StorageFileSource*, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:519:21 (clickhouse+0x18c0006d)
    #4 void std::__1::allocator_traits<std::__1::allocator<DB::StorageFileSource> >::construct<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(std::__1::allocator<DB::StorageFileSource>&, DB::StorageFileSource*, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__memory/allocator_traits.h:481:14 (clickhouse+0x18c0006d)
    #5 std::__1::__shared_ptr_emplace<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource> >::__shared_ptr_emplace<std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> > >(std::__1::allocator<DB::StorageFileSource>, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2594:9 (clickhouse+0x18c0006d)
    #6 std::__1::shared_ptr<DB::StorageFileSource> std::__1::allocate_shared<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource>, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >, void>(std::__1::allocator<DB::StorageFileSource> const&, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3360:55 (clickhouse+0x18c0006d)
    #7 std::__1::shared_ptr<DB::StorageFileSource> std::__1::make_shared<DB::StorageFileSource, std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >, void>(std::__1::shared_ptr<DB::StorageFile>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>&, unsigned long&, std::__1::shared_ptr<DB::StorageFileSource::FilesInfo>&, DB::ColumnsDescription&&, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >&&) obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3369:12 (clickhouse+0x18c0006d)
    #8 DB::StorageFile::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageFile.cpp:623:28 (clickhouse+0x18c0006d)
    #9 DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/IStorage.cpp:113:17 (clickhouse+0x18b99ce3)
    #10 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1981:18 (clickhouse+0x18239423)
    #11 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #12 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #13 DB::ClusterProxy::(anonymous namespace)::createLocalPlan(std::__1::shared_ptr<DB::IAST> const&, DB::Block const&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned int, unsigned int) obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:84:17 (clickhouse+0x18be340b)
    #14 DB::ClusterProxy::SelectStreamFactory::createForShard(DB::Cluster::ShardInfo const&, std::__1::shared_ptr<DB::IAST> const&, DB::StorageID const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> > > >&, std::__1::vector<DB::ClusterProxy::IStreamFactory::Shard, std::__1::allocator<DB::ClusterProxy::IStreamFactory::Shard> >&, unsigned int)::$_0::operator()() const obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:105:34 (clickhouse+0x18be340b)
    #15 DB::ClusterProxy::SelectStreamFactory::createForShard(DB::Cluster::ShardInfo const&, std::__1::shared_ptr<DB::IAST> const&, DB::StorageID const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> >, std::__1::allocator<std::__1::unique_ptr<DB::QueryPlan, std::__1::default_delete<DB::QueryPlan> > > >&, std::__1::vector<DB::ClusterProxy::IStreamFactory::Shard, std::__1::allocator<DB::ClusterProxy::IStreamFactory::Shard> >&, unsigned int) obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/SelectStreamFactory.cpp:161:13 (clickhouse+0x18be1e2a)
    #16 DB::ClusterProxy::executeQuery(DB::QueryPlan&, DB::Block const&, DB::QueryProcessingStage::Enum, DB::StorageID const&, std::__1::shared_ptr<DB::IAST> const&, DB::ClusterProxy::IStreamFactory&, Poco::Logger*, std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryInfo const&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Cluster> const&) obj-x86_64-linux-gnu/../src/Interpreters/ClusterProxy/executeQuery.cpp:167:24 (clickhouse+0x18be5bb5)
    #17 DB::StorageDistributed::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageDistributed.cpp:647:5 (clickhouse+0x18bcfed2)
    #18 DB::StorageDistributed::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageDistributed.cpp:600:5 (clickhouse+0x18bcf2ce)
    #19 DB::StorageMerge::createSources(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, DB::QueryProcessingStage::Enum const&, unsigned long, DB::Block const&, std::__1::vector<DB::StorageMerge::AliasData, std::__1::allocator<DB::StorageMerge::AliasData> > const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IStorage>, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::shared_ptr<DB::Context>, unsigned long, bool, bool, bool) obj-x86_64-linux-gnu/../src/Storages/StorageMerge.cpp:457:25 (clickhouse+0x18c8cbff)
    #20 DB::StorageMerge::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageMerge.cpp:383:28 (clickhouse+0x18c89e55)
    #21 DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/IStorage.cpp:113:17 (clickhouse+0x18b99ce3)
    #22 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1981:18 (clickhouse+0x18239423)
    #23 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #24 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #25 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:264:38 (clickhouse+0x1856aaf6)
    #26 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1902:31 (clickhouse+0x18238446)
    #27 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #28 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #29 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:274:37 (clickhouse+0x1856afe7)
    #30 DB::StorageView::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) obj-x86_64-linux-gnu/../src/Storages/StorageView.cpp:145:17 (clickhouse+0x18dd7eab)
    #31 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1981:18 (clickhouse+0x18239423)
    #32 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:1033:9 (clickhouse+0x18231d7a)
    #33 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectQuery.cpp:576:5 (clickhouse+0x18231577)
    #34 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:264:38 (clickhouse+0x1856aaf6)
    #35 DB::InterpreterSelectWithUnionQuery::execute() obj-x86_64-linux-gnu/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:331:5 (clickhouse+0x1856bbf8)
    #36 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:666:36 (clickhouse+0x187ddd4c)
    #37 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:985:30 (clickhouse+0x187dba61)
    #38 DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:333:24 (clickhouse+0x193ec0b8)
    #39 DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1909:9 (clickhouse+0x19401627)
    #40 Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1c434da2)
    #41 Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1c435612)
    #42 Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14 (clickhouse+0x1c68c935)
    #43 Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1c68aacf)
    #44 Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1c689147)

  Location is heap block of size 1400 at 0x7b6800b5fe00 allocated by thread T238:
    #0 operator new(unsigned long) <null> (clickhouse+0xa9ee4d8)
    #1 std::__1::shared_ptr<DB::StorageFile> shared_ptr_helper<DB::StorageFile>::create<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageFile::CommonArguments&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageFile::CommonArguments&) obj-x86_64-linux-gnu/../base/base/../base/shared_ptr_helper.h:17:35 (clickhouse+0x18c0d9e8)
    #2 DB::registerStorageFile(DB::StorageFactory&)::$_3::operator()(DB::StorageFactory::Arguments const&) const obj-x86_64-linux-gnu/../src/Storages/StorageFile.cpp:1034:24 (clickhouse+0x18c0511b)
    #3 decltype(std::__1::forward<DB::registerStorageFile(DB::StorageFactory&)::$_3&>(fp)(std::__1::forward<DB::StorageFactory::Arguments const&>(fp0))) std::__1::__invoke<DB::registerStorageFile(DB::StorageFactory&)::$_3&, DB::StorageFactory::Arguments const&>(DB::registerStorageFile(DB::StorageFactory&)::$_3&, DB::StorageFactory::Arguments const&) obj-x86_64-linux-gnu/../contrib/libcxx/include/type_traits:3676:1 (clickhouse+0x18c0511b)
    #4 std::__1::shared_ptr<DB::IStorage> std::__1::__invoke_void_return_wrapper<std::__1::shared_ptr<DB::IStorage> >::__call<DB::registerStorageFile(DB::StorageFactory&)::$_3&, DB::StorageFactory::Arguments const&>(DB::registerStorageFile(DB::StorageFactory&)::$_3&, DB::StorageFactory::Arguments const&) obj-x86_64-linux-gnu/../contrib/libcxx/include/__functional_base:317:16 (clickhouse+0x18c0511b)
    #5 std::__1::__function::__default_alloc_func<DB::registerStorageFile(DB::StorageFactory&)::$_3, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1608:12 (clickhouse+0x18c0511b)
    #6 std::__1::shared_ptr<DB::IStorage> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerStorageFile(DB::StorageFactory&)::$_3, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)> >(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2089:16 (clickhouse+0x18c0511b)
    #7 std::__1::__function::__policy_func<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2221:16 (clickhouse+0x18bf8db5)
    #8 std::__1::function<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) const obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2560:12 (clickhouse+0x18bf8db5)
    #9 DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const obj-x86_64-linux-gnu/../src/Storages/StorageFactory.cpp:225:16 (clickhouse+0x18bf8db5)
    #10 DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterCreateQuery.cpp:1095:42 (clickhouse+0x17dc8f45)
    #11 DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) obj-x86_64-linux-gnu/../src/Interpreters/InterpreterCreateQuery.cpp:979:20 (clickhouse+0x17dc4896)
    #12 DB::InterpreterCreateQuery::execute() obj-x86_64-linux-gnu/../src/Interpreters/InterpreterCreateQuery.cpp:1336:16 (clickhouse+0x17dcb19e)
    #13 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:666:36 (clickhouse+0x187ddd4c)
    #14 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:985:30 (clickhouse+0x187dba61)
    #15 DB::TCPHandler::runImpl() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:333:24 (clickhouse+0x193ec0b8)
    #16 DB::TCPHandler::run() obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1909:9 (clickhouse+0x19401627)
    #17 Poco::Net::TCPServerConnection::start() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1c434da2)
    #18 Poco::Net::TCPServerDispatcher::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1c435612)
    #19 Poco::PooledThread::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14 (clickhouse+0x1c68c935)
    #20 Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1c68aacf)
    #21 Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1c689147)

  Thread T458 'TCPHandler' (tid=39364, running) created by thread T223 at:
    #0 pthread_create <null> (clickhouse+0xa97979d)
    #1 Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6 (clickhouse+0x1c688b95)
    #2 Poco::Thread::start(Poco::Runnable&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:128:2 (clickhouse+0x1c68a40c)
    #3 Poco::PooledThread::start() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10 (clickhouse+0x1c68e746)
    #4 Poco::ThreadPool::getThread() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:461:14 (clickhouse+0x1c68e746)
    #5 Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:365:2 (clickhouse+0x1c68eb47)
    #6 Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:152:17 (clickhouse+0x1c435b0e)
    #7 Poco::Net::TCPServer::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServer.cpp:148:21 (clickhouse+0x1c434627)
    #8 Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1c68aacf)
    #9 Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1c689147)

  Thread T1069 'TCPHandler' (tid=45462, running) created by thread T223 at:
    #0 pthread_create <null> (clickhouse+0xa97979d)
    #1 Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6 (clickhouse+0x1c688b95)
    #2 Poco::Thread::start(Poco::Runnable&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:128:2 (clickhouse+0x1c68a40c)
    #3 Poco::PooledThread::start() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10 (clickhouse+0x1c68e746)
    #4 Poco::ThreadPool::getThread() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:461:14 (clickhouse+0x1c68e746)
    #5 Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:365:2 (clickhouse+0x1c68eb47)
    #6 Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:152:17 (clickhouse+0x1c435b0e)
    #7 Poco::Net::TCPServer::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServer.cpp:148:21 (clickhouse+0x1c434627)
    #8 Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1c68aacf)
    #9 Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1c689147)

  Thread T238 'TCPHandler' (tid=657, running) created by thread T221 at:
    #0 pthread_create <null> (clickhouse+0xa97979d)
    #1 Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6 (clickhouse+0x1c688b95)
    #2 Poco::Thread::start(Poco::Runnable&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:128:2 (clickhouse+0x1c68a40c)
    #3 Poco::PooledThread::start() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10 (clickhouse+0x1c68e746)
    #4 Poco::ThreadPool::getThread() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:461:14 (clickhouse+0x1c68e746)
    #5 Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:365:2 (clickhouse+0x1c68eb47)
    #6 Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:152:17 (clickhouse+0x1c435b0e)
    #7 Poco::Net::TCPServer::run() obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServer.cpp:148:21 (clickhouse+0x1c434627)
    #8 Poco::(anonymous namespace)::RunnableHolder::run() obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1c68aacf)
    #9 Poco::ThreadImpl::runnableEntry(void*) obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1c689147)

SUMMARY: ThreadSanitizer: data race obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1648:26 in std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer> >::release()
```

Probably related to #33960, cc: @Avogar

### PR DESCRIPTION
**Pull request by Avogar**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible data race in StorageFile that was introduced in https://github.com/ClickHouse/ClickHouse/pull/33960. Closes https://github.com/ClickHouse/ClickHouse/issues/34111

### CODE REVIEW

**Comment by tavplubix** [comment]
Stateful tests (ubsan, actions) and Stateless tests (ubsan, actions) failures are related: has_peekable_read_buffer_from_fd is not initialized if peekable_read_buffer_from_fd is false

File: src/Storages/StorageFile.cpp [hunk 1]
```diff
@@ -620,8 +623,16 @@ Pipe StorageFile::read(
                 return metadata_snapshot->getColumns();
         };
 
+        /// In case of reading from fd we have to check whether we have already created
```
Comment (tavplubix) [inline src/Storages/StorageFile.cpp:626]: Btw, how do parallel reads from fd work?

Comment (Avogar) [reply src/Storages/StorageFile.cpp:626]: They don't work I guess, just this branch of code is also executing for files and here we got a data race on moving empty unique ptr (code around schema inference from stdin lools not good, but I had no other variants here)

**Review by tavplubix — APPROVED** [review]

**Comment by tavplubix** [comment]
Stress test (thread, actions) - segfault without stacktrace
