### PR TITLE
Fix MongoDB dictionary source failing with named collections

### LINKED ISSUE #97840: Named collections for MongoDB dictionary settings do not work
### Company or project name

_No response_

### Describe what's wrong

First, create the named collection and a MongoDB dictionary: 
```
CREATE NAMED COLLECTION mongo AS options = 'ssl=false', uri = 'mongodb://example.com/main';
CREATE DICTIONARY tmp0
(
    `id` UInt64,
    `name` String
)
PRIMARY KEY id
SOURCE(MONGODB(NAME mongo COLLECTION 'dsps'))
LIFETIME(MIN 100 MAX 5400)
LAYOUT(HASHED())
```
Then, try to use the dictionary:
```
SELECT * FROM tmp0;
```
Results in this error:
```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected key `name` in named collection. Required keys: collection, optional keys: . (BAD_ARGUMENTS)
```

P.S. Creating the same dictionary without named collection works without issues.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Clickhouse version 25.8.12.129.

### Expected behavior

_No response_

### Error message and/or stacktrace

```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected key `name` in named collection. Required keys: collection, optional keys: . (BAD_ARGUMENTS)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pamarcos**
Fix MongoDB dictionary source failing with named collections

The config-based tryGetNamedCollectionWithOverrides() was leaking the 'name' key (used to identify the named collection) into the collection's data keys. This caused validateNamedCollection() to reject it as an unexpected key. Skip 'name' in the override loop since it is a meta-key.

Also fix MongoDBDictionarySource to list 'uri' as required and 'options' as optional in the URI path, which were previously missing.

Closes #97840

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix MongoDB dictionary source failing with named collections. Closes #97840

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Dictionaries/MongoDBDictionarySource.cpp [hunk 1]
```diff
@@ -52,7 +52,7 @@ void registerDictionarySourceMongoDB(DictionarySourceFactory & factory)
         {
             if (named_collection->has("uri"))
             {
-                validateNamedCollection(*named_collection, {"collection"}, {});
+                validateNamedCollection(*named_collection, {"uri", "collection"}, {"options"});
```
Comment (GrigoryPervakov) [inline src/Dictionaries/MongoDBDictionarySource.cpp]: `options` are included in the `uri`. So it's better to throw a validation error if set, to show that it has no effect.

Maybe we can unify the MongoDB client creation from the different sources?
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageMongoDB.cpp#L120

Comment (pamarcos) [reply src/Dictionaries/MongoDBDictionarySource.cpp]: Thanks, that makes sense. Fixed in https://github.com/ClickHouse/ClickHouse/pull/98528/commits/65c280f33782ced2d1a55690d3e8adb87de99b71

**Review by GrigoryPervakov — APPROVED** [review]
