### PR TITLE
 fix the validation of asynchronous metrics update period settings

### LINKED ISSUE #82302: asynchronous_heavy_metrics_update_period_s contradiction
### Describe the bug

Here: https://github.com/ClickHouse/ClickHouse/blob/e4a07a425ad3af05720946c9e803976fcc7f3682/src/Interpreters/ServerAsynchronousMetrics.cpp#L76 says `asynchronous_heavy_metrics_update_period_s` cannot be zero, but if I set it to that value, the server takes forever to start.

### How to reproduce

set:

```xml
<asynchronous_heavy_metrics_update_period_s>0</asynchronous_heavy_metrics_update_period_s>
```

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by bharatnc**
Move the validation of `asynchronous_metrics_update_period_s` and `asynchronous_heavy_metrics_update_period_s` to server startup so that we can fail early. Currently, this is being done in the constructor of `ServerAsynchronousMetrics`, which does throw an exception, but it looks like this causes the server to still get stuck starting up and doesn't lead to immediate shutdown after the exception is thrown.

Closes: https://github.com/ClickHouse/ClickHouse/issues/82302
See also: https://github.com/ClickHouse/ClickHouse/pull/53428 where the sanity check was initially added.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the validation of async metrics settings `asynchronous_metrics_update_period_s` and `asynchronous_heavy_metrics_update_period_s`.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: programs/server/Server.cpp [hunk 1]
```diff
@@ -1148,6 +1149,13 @@ try
             page_cache_max_size);
     }
 
+    size_t update_period_seconds = server_settings[ServerSetting::asynchronous_metrics_update_period_s];
+    size_t heavy_metrics_update_period_seconds = server_settings[ServerSetting::asynchronous_heavy_metrics_update_period_s];
+    if (update_period_seconds == 0 || (heavy_metrics_update_period_seconds == 0))
```
Comment (tuanpach) [inline programs/server/Server.cpp]:
```suggestion
    if (update_period_seconds == 0 || heavy_metrics_update_period_seconds == 0)
```

Comment (tuanpach) [reply programs/server/Server.cpp]: Should we create a new type `NonZeroUInt32`?

Comment (bharatnc) [reply programs/server/Server.cpp]: No strong preference here. The current check works just fine. Perhaps we don't need to create if we don't really need it? Can do a follow up later too.

File: tests/integration/test_system_reload_async_metrics/test.py [hunk 2]
```diff
@@ -1,7 +1,4 @@
 import os
-import shutil
-import time
```
Comment (tuanpach) [inline tests/integration/test_system_reload_async_metrics/test.py:3]: I think you must drop `tab` table in test_system_reload_async_metrics to fix the test

Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test.py:3]: Yes, looks like table clean up is missing, I'll fix the test.

File: tests/integration/test_system_reload_async_metrics/test.py [hunk 3]
```diff
@@ -32,18 +29,21 @@ def start_cluster():
...
-    res2 = node.query(
-        "SELECT value FROM system.asynchronous_metrics WHERE metric = 'NumberOfTables'"
-    )
-    assert int(res1.rstrip()) + 1 == int(res2.rstrip())
+        res2 = node.query(
+            "SELECT value FROM system.asynchronous_metrics WHERE metric = 'NumberOfTables'"
+        )
+        assert int(res1.rstrip()) + 1 == int(res2.rstrip())
+    finally:
+        node.query("DROP TABLE IF EXISTS tab;")
```
Comment (tuanpach) [inline tests/integration/test_system_reload_async_metrics/test.py]: We can drop the table to the beginning of the test. So if other tests create`tab` table, this test will not fail as it will drop the table before the test logic

Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test.py]: I tried this too locally. However, in either case, the flaky [test](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82310&sha=19f775d5da2b66a96c27ff41340431a7d2dcdc3e&name_0=PR&name_1=Integration%20tests%20%28asan%2C%20flaky%20check%29) seems to happen in this part:
```
>           assert int(res1.rstrip()) + 1 == int(res2.rstrip())
E           AssertionError: assert (144 + 1) == 144
E            +  where 144 = int('144')
E            +    where '144' = <built-in method rstrip of str object at 0x7f1d569e09f0>()
E            +      where <built-in method rstrip of str object at 0x7f1d569e09f0> = '144\n'.rstrip
E            +  and   144 = int('144')
E            +    where '144' = <built-in method rstrip of str object at 0x7f1d56940570>()
E            +      where <built-in method rstrip of str object at 0x7f1d56940570> = '144\n'.rstr
```

What's confusing is, even without any of my changes, failure seems to happen locally against master if I run it multiple times in parallel: `./runner  'test_system_reload_async_metrics'  --count 5 -n 5`. I'm not sure if I'm caching anything locally, but I don't understand why it doesn't fail on master CI though, but fails when run locally. In fact, it's not also excluded by [parallel_skip.yaml](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/parallel_skip.yaml).

Comment (tuanpach) [reply tests/integration/test_system_reload_async_metrics/test.py]: In master CI, it might be only run 1 time. The flaky test is triggered only when there are changes in the test file.

Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test.py]: Good point. Perhaps the flaky check was not present when the test was originally added but it fails now based on the new diff.  I'll work on a fix - the assertion in this test needs to be fixed. Its currently failing as it's possible for the tables (though we drop them) to increment the asynchronous metric in background for total table count when the tests are being run in parallel.

File: tests/integration/test_system_reload_async_metrics/test.py [hunk 4]
```diff
@@ -33,17 +30,25 @@ def start_cluster():
 
 def test_system_reload_async_metrics(start_cluster):
     node.query("SYSTEM DROP QUERY CACHE")
+    node.query("DROP TABLE IF EXISTS tab SYNC;")
+
+    # Reload asynchronous metrics to get the latest state (async metrics update period has been set to a large value
+    # intentionally in the test config to test the manual reload functionality)
+    node.query("SYSTEM RELOAD ASYNCHRONOUS METRICS")
```
Comment (bharatnc) [inline tests/integration/test_system_reload_async_metrics/test.py:37]: So this was the main fix to get the tests to work consistently with parallel runs. In order to test `SYSTEM RELOAD ASYNCHRONOUS METRICS`, the values of `asynchronous_metrics_update_period_s` and `asynchronous_heavy_metrics_update_period_s` have been set to a very large value (`60000` s) in [default.xml](https://github.com/ClickHouse/ClickHouse/blob/2ebb506a29814ccdc81445c12aed04c6cb72a307/tests/integration/test_system_reload_async_metrics/configs/default.xml). So, between parallel runs, the metric was never updated leading to test failure as the base metric was always outdated I guess. Forcing a reload before test start makes the  test to work as expected.

File: tests/integration/test_system_reload_async_metrics/test.py [hunk 5]
```diff
@@ -33,17 +30,25 @@ def start_cluster():
...
 
     node.query("SYSTEM RELOAD ASYNCHRONOUS METRICS")
 
     res2 = node.query(
         "SELECT value FROM system.asynchronous_metrics WHERE metric = 'NumberOfTables'"
     )
-    assert int(res1.rstrip()) + 1 == int(res2.rstrip())
+
+    # Verify the count increased (could sometimes be more than +1 due to parallel tests)
+    assert int(res2.strip()) >= int(res1.strip()) + 1
```
Comment (bharatnc) [inline tests/integration/test_system_reload_async_metrics/test.py]: This fix is not really needed (i.e we can just use `==`), but it's better to compare like this just in case.

File: tests/integration/test_system_reload_async_metrics/test.py (hunk 3 above)
Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test.py]: See https://github.com/ClickHouse/ClickHouse/pull/82310#discussion_r2162726121 for the fix.

File: tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+# Tests the validation of asynchronous metrics settings:
+# asynchronous_metrics_update_period_s & asynchronous_heavy_metrics_update_period_s
+
+cluster = ClickHouseCluster(__file__)
+
+
+@pytest.fixture(scope="module")
+def start_cluster():
+    try:
+        cluster.add_instance(
```
Comment (tuanpach) [inline tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py:14]: Should we just put this test logic in `test_invalid_settings` instead of using a fixture? If there are tests in the future, this fixture will not be reused anymore.

**Comment by bharatnc** [comment]
[Bugfix validation (integration tests)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82310&sha=a326be25e50c1b2b17497493bd936f69a80e931a&name_0=PR&name_1=Bugfix%20validation%20%28integration%20tests%29) - PR for fix: https://github.com/ClickHouse/ClickHouse/pull/82465

File: tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py (hunk 6 above)
Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py:14]: I think that it's ok. I prefer having the test setup in the current way so that it's mostly uniform with 90% of the other tests (there might be some setting up differently).

Comment (tuanpach) [reply tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py:14]: I think we can set up the cluster with valid settings in `start_cluster`. Then, in your test, we can stop the instance, copy the invalid settings, and restart the instance.
So that the cluster can be reused like other tests.
We need to remove the invalid settings at the end of the test.

File: tests/integration/test_system_reload_async_metrics/test.py (hunk 5 above)
Comment (tuanpach) [reply tests/integration/test_system_reload_async_metrics/test.py]: > Verify the count increased (could sometimes be more than +1 due to parallel tests)

From what I understand, when specifying more than 1 job(with `-j`), we can have multiple tests running at the same time, but each test runs only 1 at a time. Even when we run with `--count`, the same test is run multiple times sequentially.
So this comment is a bit confusing to me.

If `==` is expected in this case, then I think we can stick with it.

File: tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py (hunk 6 above)
Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py:14]: That would be unnecessarily complicating the test flow during multiple replace configs (I don't want to do it as it might lead to more test flakiness). I have just moved the fixture to part of the main function `test_invalid_settings` as per your initial request.

File: tests/integration/test_system_reload_async_metrics/test.py (hunk 5 above)
Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test.py]: changed to use `==`  yeah it's what's expected.

File: tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py (hunk 6 above)
Comment (tuanpach) [reply tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py:14]: FYI, there are some tests which replace the config and restart the instance.

https://github.com/ClickHouse/ClickHouse/blob/3343a276be4d5728a70e0dc5a0a11baf7cee0abf/tests/integration/test_keeper_incorrect_config/test.py#L208

https://github.com/tuanpach/ClickHouse/blob/3343a276be4d5728a70e0dc5a0a11baf7cee0abf/tests/integration/test_keeper_internal_secure/test.py#L156

Comment (bharatnc) [reply tests/integration/test_system_reload_async_metrics/test_async_metrics_invalid_settings.py:14]: yeah I noticed - there are a few places, but I found your initial suggestion to be more simpler and in this case, we have a single test case testing for something specific and we don't really reuse the test fixture for another test.

**Review by tuanpach — APPROVED** [review]

**Comment by bharatnc** [comment]
Test failure not related:

- [Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82310&sha=82ee52a74f4603cb62cc068c33eb9f5aa202721f&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%202%2F2%29) - https://github.com/ClickHouse/ClickHouse/issues/74734
