### PR TITLE
Fix totals and extremes with constants in clickhouse-local

### LINKED ISSUE #43831: SIGABRT in clickhouse local
https://s3.amazonaws.com/clickhouse-test-reports/38191/21f93e9f4cde9d08fbc06dd103fa7f530630d0aa/fuzzer_astfuzzermsan//report.html

Query: `SELECT '-0.0000000002', (-1 + NULL) = any('0.0000001024', (NULL + NULL) + NULL, 3.4028234663852886e38 + NULL), NULL, any((0. + NULL) + NULL), any(NULL) WITH TOTALS`

Minimized example:

```bash
$ ~/clickhouse local -q "SELECT NULL, any(NULL) WITH TOTALS"
\N	\N
fish: Job 1, '~/clickhouse local -q "SELECT N…' terminated by signal SIGABRT (Abort)```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix totals and extremes with constants in clickhouse-local.
Closes https://github.com/ClickHouse/ClickHouse/issues/43831.

### CODE REVIEW

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -481,14 +481,14 @@ void ClientBase::onLogData(Block & block)
 void ClientBase::onTotals(Block & block, ASTPtr parsed_query)
 {
     initOutputFormat(block, parsed_query);
-    output_format->setTotals(block);
+    output_format->setTotals(materializeBlock(block));
```
Comment (Avogar) [inline src/Client/ClientBase.cpp:484]: Same as in `onData` method.

**Review by alexey-milovidov — APPROVED** [review]
