### PR TITLE
fix s3 support question mark wildcard

### LINKED ISSUE #42731: "?" in s3 table function doesn't work?
When i learn about "s3 table function" by folllowing https://clickhouse.com/docs/en/engines/table-engines/integrations/s3/, I found "?" does not work. 
The detailed tests are as follows. Is it a problem?
Obviously, "*" is workable.
The file name  in s3 is  test_1.parquet, test_2.parquet, test_3.parquet

```
:) show create table test_s3_test;

SHOW CREATE TABLE test_s3_test

Query id: 2975f0f5-53f2-4c07-8996-dec40458fae5

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE cos.test_s3_test
(
    `a` Int32,
    `b` String
)
ENGINE = S3('http://xxxxxxxx/testfile/test_?', ak, sk, 'Parquet') │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.

:) show create table test_s3_test2;

SHOW CREATE TABLE test_s3_test2

Query id: 621bf107-f651-41d6-993e-60ac96887da5

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE cos.test_s3_test2
(
    `a` Int32,
    `b` String
)
ENGINE = S3('http://xxxxxxxxx/testfile/test_?.parquet', ak, sk, 'Parquet') │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.

 :) select count(*) from test_s3_test;

SELECT count(*)
FROM test_s3_test

Query id: 326c6eb2-a4bf-48b5-8c23-7827d0bf84f5

→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
0 rows in set. Elapsed: 0.697 sec.

Received exception from server (version 22.10.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: No response body.: While executing ParquetBlockInputFormat: While executing COSN. (S3_ERROR)

 :) select count(*) from test_s3_test2;

SELECT count(*)
FROM test_s3_test2

Query id: 82d747a6-3009-45cd-8a70-61a2f5cdfe0b

↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
0 rows in set. Elapsed: 0.225 sec.

Received exception from server (version 22.10.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: No response body.: While executing ParquetBlockInputFormat: While executing COSN. (S3_ERROR)
```

### PR DESCRIPTION
**Pull request by xiedeyantu**
### Changelog category (leave one):
- Bug Fix 

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix s3 support question mark wildcard. Closes #42731

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/IO/S3Common.cpp [hunk 1]
```diff
@@ -754,16 +754,30 @@ namespace S3
...
+        bool has_version_id = false;
         for (const auto & [query_key, query_value] : uri.getQueryParameters())
             if (query_key == "versionId")
+            {
                 version_id = query_value;
+                has_version_id = true;
+            }
+
+        /// If uri contains parameter "versionId", the "?" will not be used as wildcards.
+        /// Otherwise it is necessary to encode "?" to avoid deletion during parsing.
```
Comment (kssenii) [inline src/IO/S3Common.cpp:774]: why could it be deleted? why not encode regardless of the has_version_id value?

Comment (xiedeyantu) [reply src/IO/S3Common.cpp:774]: > why could it be deleted? why not encode regardless of the has_version_id value?

Poco::URI will ignore '?' when parsing the path, but if there is a vestionId in the http parameter, '?' can not be used as a wildcard, otherwise it will be ambiguous.

File: src/IO/S3Common.cpp [hunk 2]
```diff
@@ -754,16 +754,32 @@ namespace S3
...
+            }
+
+        /// Poco::URI will ignore '?' when parsing the path, but if there is a vestionId in the http parameter,
+        /// '?' can not be used as a wildcard, otherwise it will be ambiguous.
+        /// If no "vertionId" in the http parameter, '?' can be used as a wildcard.
+        /// It is necessary to encode '?' to avoid deletion during parsing path.
+        if (!has_version_id && uri_.find('?') != String::npos)
+        {
+            String uri_with_question_mark_encode;
+            Poco::URI::encode(uri_, "?", uri_with_question_mark_encode);
```
Comment (kssenii) [inline src/IO/S3Common.cpp:780]: As I understand in this case we can encode part of url without version id "?version_id=<version>" and set version id back in uri after encoding.

Comment (xiedeyantu) [reply src/IO/S3Common.cpp:780]: > As I understand in this case we can encode part of url without version id "?version_id=" and set version id back in uri after encoding.

If versionid exist, we won't encode, we do not know '?' is a wildcard or prefix of parameter. we will ignore '?' wildcard.

Comment (kssenii) [reply src/IO/S3Common.cpp:780]: In fact we can know this exactly as it is under key "versionId" in query parameters of uri, but thinking one more time about it - this improvement is not really applicable along with version id so current way is ok

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
Fuzz - https://github.com/ClickHouse/ClickHouse/issues/43324

**Comment by xiedeyantu** [comment]
> 

？
