### PR TITLE
test for #64211

### LINKED ISSUE #64211: The merge function doesn't work with a subquery from 23.6 to 24.1
```sql
SELECT version()
```
```
23.8.14.6
```
I create table on three servers:
```sql
CREATE TABLE default.test_local (name String, date Date, sign Int8) 
ENGINE = CollapsingMergeTree(sign) 
PARTITION BY date 
ORDER BY name 
SETTINGS index_granularity = 8192
```

**_Queries below executed on first server._**
I create distributed table:
```sql
CREATE TABLE test_distributed
ENGINE = Distributed(sharded_cluster, currentDatabase(), test_local, rand64());
```
I insert data:
```sql
INSERT INTO test_distributed
VALUES ('11', '2024-01-01', 1), ('3', '2024-01-01', 1), ('2', '2024-05-01', 1), ('8', '2024-01-05', 1), ('5', '2024-01-06', 1), ('4', '2024-02-01', 1), ('6', '2024-04-01', 1), ('16', '2024-01-11', 1), ('12', '2024-01-12', 1), ('1', '2024-08-01', 1), ('9', '2024-11-01', 1)
```
```sql
SELECT count()
FROM default.test_distributed
WHERE name GLOBAL IN (
SELECT name
FROM default.test_distributed
)
```
```
11
```
```sql
SELECT count()
FROM merge('default', 'test_distributed')
WHERE name GLOBAL IN (
SELECT name
FROM default.test_distributed
)
```
```
7 
```

```
        <sharded_cluster>
            <shard>
                <replica>
                    <host>clickhouse1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse3</host>
                    <port>9000</port>
                </replica>
            </shard>
        </sharded_cluster>
```

### PR DESCRIPTION
**Pull request by den-crane**
closes: #64211

There was an issue related to engine Merge and primary key for queries with Global In. 

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

File: tests/queries/0_stateless/01227_distributed_merge_global_in_primary_key.sql [hunk 1]
```diff
@@ -0,0 +1,79 @@
+-- https://github.com/ClickHouse/ClickHouse/issues/64211
+
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/01227_distributed_merge_global_in_primary_key.sql:2]:
```suggestion
DROP TABLE IF EXISTS test_merge;
DROP TABLE IF EXISTS test_merge_distributed;
DROP TABLE IF EXISTS test_distributed_merge;
DROP TABLE IF EXISTS test_distributed;
DROP TABLE IF EXISTS test_local;
```
