### PR TITLE
Fix intersect/except with limit

### LINKED ISSUE #27754: INTERSECT with LIMIT in top level query (LOGICAL_ERROR)
**Describe the bug**

Clickhouse throw LOGICAL ERROR if you would try to use LIMIT in main query if you have INTERSECT in sub query.

**Does it reproduce on recent release?**

Yes.

```
SELECT version()

┌─version()───┐
│ 21.9.1.7787 │
└─────────────┘
```
**How to reproduce**

```
:) SELECT count() FROM (SELECT 1 intersect SELECT 1) LIMIT 100;

SELECT count()
FROM
(
    SELECT 1
    UNION DISTINCT
    SELECT 1
)
LIMIT 100


0 rows in set. Elapsed: 0.003 sec.

Received exception from server (version 21.9.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ASTSelectIntersectExceptQuery to DB::ASTSelectQuery. (LOGICAL_ERROR)


:) SELECT count()
:-] FROM
:-] (
:-]     SELECT 1
:-]     UNION DISTINCT
:-]     SELECT 1
:-] )
:-] LIMIT 100;

SELECT count()
FROM
(
    SELECT 1
    UNION DISTINCT
    SELECT 1
)
LIMIT 100

┌─count()─┐
│       1 │
└─────────┘

1 rows in set. Elapsed: 0.003 sec.
```

**Expected behavior**

Query works.

**Additional context**

Related https://github.com/ClickHouse/ClickHouse/pull/24757

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/27754.

### CODE REVIEW

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -878,16 +879,38 @@ static bool hasWithTotalsInAnySubqueryInFromClause(const ASTSelectQuery & query)
...
             for (const auto & elem : ast_union->list_of_selects->children)
             {
+                /// After normalization, the height of the AST tree is at most 2.
                 if (const auto * child_union = elem->as<ASTSelectWithUnionQuery>())
                 {
                     for (const auto & child_elem : child_union->list_of_selects->children)
                         if (hasWithTotalsInAnySubqueryInFromClause(child_elem->as<ASTSelectQuery &>()))
                             return true;
                 }
+                /// After normalization, the height of the AST tree can have any depth,
```
Comment (evillique) [inline src/Interpreters/InterpreterSelectQuery.cpp:891]: Seems like it worth to clarify the difference between tree with any depth and tree with maximum depth 2

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 2]
```diff
@@ -878,16 +879,38 @@ static bool hasWithTotalsInAnySubqueryInFromClause(const ASTSelectQuery & query)
...
+                /// but the number of children at each level is always 2.
+                else if (elem->as<ASTSelectIntersectExceptQuery>())
+                {
+                    std::function<bool(ASTPtr)> traverse_recursively = [&](ASTPtr child_ast) -> bool
```
Comment (evillique) [inline src/Interpreters/InterpreterSelectQuery.cpp:895]: From my standpoint it seems like `std::function<bool(ASTPtr)>` does not add any new information and `auto` would be better :)

**Review by evillique — APPROVED** [review]

File: src/Interpreters/InterpreterSelectQuery.cpp (hunk 2 above)
Comment (kssenii) [reply src/Interpreters/InterpreterSelectQuery.cpp:895]: Because it is called recursively, therefore `auto` is  not allowed.
