### PR TITLE
Fix leaking of MergesMutationsMemoryTracking and fix query_views_log for streaming

### LINKED ISSUE #86398: query_views_log Stops Recording After Upgrade from 25.1 to 25.7
### Company or project name

_No response_

### Describe the unexpected behaviour

Hi ClickHouse team,

We've observed an issue in two of our clusters (QA and Production) after upgrading from version 25.1.7.20 to 25.7.4.11. It seems the system.query_views_log table completely stopped recording activity. No new log entries or table suffixes are being created.

We've investigated our system and can confirm that our materialized views are still processing data. The problem appears to be specific to the logging of view activity, not the functionality of the views themselves.

Here's a summary of what we observed and tried:

* The issue started immediately after upgrading to 25.7.4.11.

* We then tried upgrading to the latest stable version, 25.7.5.34, and the logs were still stopped.

* When we downgraded our QA cluster back to 25.1.7.20, logging resumed. Notably, the server also automatically recreated the query_views_log table that we had previously renamed during testing, and events started flowing into the new table.

* Running SYSTEM FLUSH LOGS; had no effect on the newer versions.

Configuration Details:

* The log_query_views setting is confirmed to be 1.

* We have no specific query_views_log configurations in our XML files.

* No configuration files were changed during the upgrade process.

* We checked the backward incompatibilities in the changelog but couldn't find anything related to this log table.

Since this is happening across multiple clusters, it seems less likely to be a unique environmental issue. Any ideas on what might have changed or what we could check next would be greatly appreciated.

Thanks!

Also created slack thread: https://clickhousedb.slack.com/archives/CU478UEQZ/p1756353749094149

### Which ClickHouse versions are affected?

25.7.4.11 & 25.7.5.34

### How to reproduce

As in the description

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix leaking of `MergesMutationsMemoryTracking` due to `Buffer` tables and fix `query_views_log` for streaming from `Kafka` (and others)

For `Buffer` we started to use `background_memory_tracker` since #79963, but forgot to call `background_memory_tracker.adjustOnBackgroundTaskEnd()`, like we do for merges/mutations and this leads to drift in `MergesMutationsMemoryTracking` (significant one), which later will lead to TOO_MANY_PARTS, because merges will stop.

At first I actually added it (`adjustOnBackgroundTaskEnd()`) but later decided that it is wrong, merges/mutations should not take care about `Buffer` flushes. Instead I've just created separate `MemoryTracker` with `total_memory_tracker` as parent, that does not requires such hacks. And this also fixes `query_views_log` for streaming from `Kafka` (and others), since previously there was no `ThreadGroup` for them.

_Note, maybe it will be a good idea to have a RAII for return value of createForBackgroundProcess() that will take care of adjustOnBackgroundTaskEnd(), but but this is not can be tricky since you need to make sure that there are no users of it (i.e. ThreadGroupSwitcher already finished)._

Fixes: #79963 (cc @CheSema )
Fixes: #86398

### CODE REVIEW

**Comment by azat** [comment]
This will break `system.query_views_log` for `Buffer` flushes

File: src/Storages/StorageBuffer.cpp [hunk 1]
```diff
@@ -1089,18 +1089,13 @@ void StorageBuffer::writeBlockToDestination(const Block & block, StoragePtr tabl
 
 void StorageBuffer::backgroundFlush()
 {
+    try
     {
-        auto thread_group = ThreadGroup::createForBackgroundProcess(getContext());
```
Comment (CheSema) [inline src/Storages/StorageBuffer.cpp:1093]: You wrote 
> /// For background tasks (i.e. Buffer flush) there may not be any group

But here thread group has been create for buffer flush. It did not match.

**Review by CheSema — APPROVED** [review]
Any way, with that PR you create thread group for all the cases when there have not been thread group for current thread created yet.

**Comment by azat** [comment]
CI known and unrelated.
