### PR TITLE
fix: Propagate context on internal casts

### LINKED ISSUE #78025: Format settings are not respected during internal CAST
```sql
set enable_json_type=1;
create table test (json JSON) engine=Memory;
insert into test select '{"a" : "2024 April 4"}' settings date_time_input_format='best_effort';
select JSONAllPathsWithTypes(json) from test;

   ┌─JSONAllPathsWithTypes(json)─┐
1. │ {'a':'String'}              │
   └─────────────────────────────┘
```

It should parse `DateTime`:
```sql
:) select '{"d" : "2024 April 4"}'::JSON as json, JSONAllPathsWithTypes(json) settings date_time_input_format='best_effort'

   ┌─json────────────────────────┬─JSONAllPathsWithTypes(json)─┐
1. │ {"d":"2024-04-04 00:00:00"} │ {'d':'DateTime'}            │
   └─────────────────────────────┴─────────────────────────────┘

```

### PR DESCRIPTION
**Pull request by raimannma**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Propagate context on internal casts. Fixing multiple issues where cast-settings weren't propagated. Closes #88873. Closes #78025.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Functions/CastOverloadResolver.cpp [hunk 1]
```diff
@@ -93,10 +95,15 @@ class CastOverloadResolverImpl : public IFunctionOverloadResolver
         arguments.emplace_back(std::move(from));
         arguments.emplace_back().type = std::make_unique<DataTypeString>();
 
+        /// If context is not provided, try to get it from the current thread.
```
Comment (alexey-milovidov) [inline src/Functions/CastOverloadResolver.cpp]: This is strange, a better solution is needed. Let's ask @Avogar

Comment (raimannma) [reply src/Functions/CastOverloadResolver.cpp]: Yeah the tests also show it has side effects to add the context there. :thinking:

File: src/Functions/CastOverloadResolver.h [hunk 2]
```diff
@@ -28,6 +28,6 @@ struct CastDiagnostic
     std::string column_to;
 };
 
-FunctionBasePtr createInternalCast(ColumnWithTypeAndName from, DataTypePtr to, CastType cast_type, std::optional<CastDiagnostic> diagnostic);
+FunctionBasePtr createInternalCast(ColumnWithTypeAndName from, DataTypePtr to, CastType cast_type, std::optional<CastDiagnostic> diagnostic, ContextPtr context = nullptr);
```
Comment (Avogar) [inline src/Functions/CastOverloadResolver.h]: We should not use `nullptr` as default argument here. We just need to always propagate context on each call of `createInternalCast`

**Comment by Avogar** [comment]
It should also fix https://github.com/ClickHouse/ClickHouse/issues/78025, please, add a test from this issue and make sure it passes

**Comment by UnamedRus** [comment]
If duplicated paths dedup setting will be respected during insert, may be it will fix as well? https://github.com/ClickHouse/ClickHouse/issues/82206

**Comment by Avogar** [comment]
> If duplicated paths dedup setting will be respected during insert, may be it will fix as well? https://github.com/ClickHouse/ClickHouse/issues/82206

In this particular issue error happens during merges, and I believe it happens during binary deserialization of a nested `Array(JSON)` from shared data where we always use `type_json_skip_duplicated_paths = 0`, because duplicated paths there are unexpected (they should not happen during inserts so only some bug could lead to it).

File: src/Functions/CastOverloadResolver.h (hunk 2 above)
Comment (raimannma) [reply src/Functions/CastOverloadResolver.h]: I think I got all the spots now where I could propagate the contaxt towards internal cast, at some points I couldn't find a way to get a context without changing a lot of code.

File: src/Interpreters/ActionsDAG.h [hunk 3]
```diff
@@ -164,7 +164,7 @@ class ActionsDAG
         const FunctionBasePtr & function_base,
         NodeRawConstPtrs children,
         std::string result_name);
-    const Node & addCast(const Node & node_to_cast, const DataTypePtr & cast_type, std::string result_name);
+    const Node & addCast(const Node & node_to_cast, const DataTypePtr & cast_type, std::string result_name, ContextPtr context = nullptr);
```
Comment (Avogar) [inline src/Interpreters/ActionsDAG.h]: And here again, don't use nullptr as default value, we should always propagate context to this and `makeConvertingActions` methods. Places where we need `nullptr` as a context should not exist (or be rare exceptions with a reason for this).

File: src/Interpreters/castColumn.cpp [hunk 4]
```diff
@@ -29,7 +29,7 @@ static ColumnPtr castColumn(CastType cast_type, const ColumnWithTypeAndName & ar
     };
     auto get_cast_func = [from = arg, to = type, cast_type]
     {
-        return createInternalCast(from, to, cast_type, {});
+        return createInternalCast(from, to, cast_type, {}, nullptr);
```
Comment (Avogar) [inline src/Interpreters/castColumn.cpp:32]: We should propagate real context here

File: src/Planner/Utils.h [hunk 5]
```diff
@@ -39,7 +39,8 @@ Block buildCommonHeaderForUnion(const SharedHeaders & queries_headers, SelectUni
 void addConvertingToCommonHeaderActionsIfNeeded(
     std::vector<std::unique_ptr<QueryPlan>> & query_plans,
     const Block & union_common_header,
-    SharedHeaders & query_plans_headers);
+    SharedHeaders & query_plans_headers,
+    ContextPtr context = nullptr);
```
Comment (Avogar) [inline src/Planner/Utils.h]: Don't use nullptr default value for context, always propagate real context

File: src/Processors/Transforms/BuildRuntimeFilterTransform.cpp [hunk 6]
```diff
@@ -28,7 +28,7 @@ BuildRuntimeFilterTransform::BuildRuntimeFilterTransform(
 {
     const auto & filter_column = header_->getByPosition(filter_column_position);
     if (!filter_column_target_type->equals(*filter_column_original_type))
-        cast_to_target_type = createInternalCast(filter_column, filter_column_target_type, CastType::nonAccurate, {});
+        cast_to_target_type = createInternalCast(filter_column, filter_column_target_type, CastType::nonAccurate, {}, nullptr);
```
Comment (Avogar) [inline src/Processors/Transforms/BuildRuntimeFilterTransform.cpp:31]: We should propagate real context here

File: src/Processors/Transforms/WindowTransform.cpp [hunk 7]
```diff
@@ -2325,7 +2325,7 @@ struct WindowFunctionLagLeadInFrame final : public StatelessWindowFunction
 
         auto get_cast_func = [from = argument_types[2], to = argument_types[0]]
         {
-            return createInternalCast({from, {}}, to, CastType::accurate, {});
+            return createInternalCast({from, {}}, to, CastType::accurate, {}, nullptr);
```
Comment (Avogar) [inline src/Processors/Transforms/WindowTransform.cpp:2446]: Same, need to propagate real context here

File: src/Storages/MergeTree/KeyCondition.cpp [hunk 8]
```diff
@@ -2230,7 +2230,7 @@ bool KeyCondition::extractAtomFromTree(const RPNBuilderTreeNode & node, const Bu
                             ? DataTypePtr(std::make_shared<DataTypeNullable>(common_type))
                             : common_type;
 
-                        auto func_cast = createInternalCast({key_expr_type, {}}, common_type_maybe_nullable, CastType::nonAccurate, {});
+                        auto func_cast = createInternalCast({key_expr_type, {}}, common_type_maybe_nullable, CastType::nonAccurate, {}, nullptr);
```
Comment (Avogar) [inline src/Storages/MergeTree/KeyCondition.cpp]: Same

File: src/Storages/ObjectStorage/DataLakes/DeltaLake/EnginePredicate.cpp [hunk 9]
```diff
@@ -386,7 +386,8 @@ uintptr_t EngineIterator::getNextImpl(EngineIteratorData & iterator_data, const
                             /* from */std::move(left_column),
                             /* to */column_node->result_type,
                             DB::CastType::nonAccurate,
-                            std::move(diagnostic));
+                            std::move(diagnostic),
+                            nullptr);
```
Comment (Avogar) [inline src/Storages/ObjectStorage/DataLakes/DeltaLake/EnginePredicate.cpp]: Not sure if we really need context here, but ideally better to propagate here as well

File: src/Processors/Transforms/WindowTransform.cpp (hunk 7 above)
Comment (raimannma) [reply src/Processors/Transforms/WindowTransform.cpp:2446]: window functions are stateless, I don't think we can easily get context there, only way I see is through the current thread context?

File: src/Interpreters/castColumn.cpp (hunk 4 above)
Comment (raimannma) [reply src/Interpreters/castColumn.cpp:32]: we have almost at no invocation the context given, so removing this nullprt default would result in lots of changes which would just be `, nullprt)`

Comment (Avogar) [reply src/Interpreters/castColumn.cpp:32]: Ideally we should propagate context even here, but I understand that it will lead to lots of changes. Let's keep it like this for now as we already fixed the main issues

File: src/Processors/Transforms/WindowTransform.cpp (hunk 7 above)
Comment (Avogar) [reply src/Processors/Transforms/WindowTransform.cpp:2446]: > window functions are stateless

Right, let's keep it as nullptr here

File: src/Functions/CastOverloadResolver.cpp [hunk 10]
```diff
@@ -8,6 +8,7 @@
 #include <Core/Settings.h>
 #include <Interpreters/parseColumnsListForTableFunction.h>
 #include <Interpreters/Context.h>
+#include <Common/CurrentThread.h>
```
Comment (Avogar) [inline src/Functions/CastOverloadResolver.cpp]:
```suggestion
```

File: src/Interpreters/InterpreterInsertQuery.cpp [hunk 11]
```diff
@@ -416,10 +416,12 @@ QueryPipeline InterpreterInsertQuery::addInsertToSelectPipeline(ASTInsertQuery &
         }
     }
 
+    auto context = Context::createCopy(getContext());
```
Comment (Avogar) [inline src/Interpreters/InterpreterInsertQuery.cpp]: Why do we need a copy here?

File: src/Storages/ObjectStorage/DataLakes/DeltaLake/TableSnapshot.cpp [hunk 12]
```diff
@@ -166,7 +166,7 @@ class TableSnapshot::Iterator final : public DB::IObjectIterator
     {
         if (filter.has_value() && enable_engine_predicate)
         {
-            auto predicate = getEnginePredicate(filter.value(), engine_predicate_exception);
+            auto predicate = getEnginePredicate(filter.value(), engine_predicate_exception, DB::Context::getGlobalContextInstance());
```
Comment (Avogar) [inline src/Storages/ObjectStorage/DataLakes/DeltaLake/TableSnapshot.cpp]: I see it's too complex to propagate real context here for now, let's not use global context and use `nullptr` in `createInternalCast` in `EnginePredicate.h`

File: src/Processors/Transforms/BuildRuntimeFilterTransform.cpp [hunk 13]
```diff
@@ -28,7 +28,10 @@ BuildRuntimeFilterTransform::BuildRuntimeFilterTransform(
 {
     const auto & filter_column = header_->getByPosition(filter_column_position);
     if (!filter_column_target_type->equals(*filter_column_original_type))
-        cast_to_target_type = createInternalCast(filter_column, filter_column_target_type, CastType::nonAccurate, {});
+    {
+        auto query_context = CurrentThread::get().getQueryContext();
+        cast_to_target_type = createInternalCast(filter_column, filter_column_target_type, CastType::nonAccurate, {}, query_context);
```
Comment (Avogar) [inline src/Processors/Transforms/BuildRuntimeFilterTransform.cpp]: If it's too complex to propagate real context here, let's use `nullptr`, better to avoid using `CurrentThread`.

**Review by Avogar — COMMENTED** [review]
Great work, thanks! Just a few minor comments and let's merge it

**Review by Avogar — APPROVED** [review]

**Comment by raimannma** [comment]
Thanks for the fixes!

Can be merged or anything left to do?

**Comment by Avogar** [comment]
Let's merge it right away!

**Comment by raimannma** [comment]
03212_variant_dynamic_cast_or_default is flaky https://github.com/ClickHouse/ClickHouse/issues/87583

**Comment by Avogar** [comment]
Integration tests: https://github.com/ClickHouse/ClickHouse/issues/89758
