### PR TITLE
Fix possible heap-use-after-free error when reading system.projection_parts and system.projection_parts_columns

### LINKED ISSUE #37184: heap-use-after-free in IMergeTreeDataPart
https://s3.amazonaws.com/clickhouse-test-reports/37054/320efb2221390e88f9312060eee92a4da2c5c9fd/stateless_tests__thread__actions__[3/3]/stderr.log

```
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=397)
  Read of size 8 at 0x7b6400a507d0 by thread T309:
    #0 DB::IMergeTreeDataPart::getTotalColumnsSize() const build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.h:121:53 (clickhouse+0x1880196e)
    #1 DB::StorageSystemProjectionPartsColumns::processNextStorage(std::__1::shared_ptr<DB::Context const>, std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::__1::vector<char8_t, std::__1::allocator<char8_t> >&, DB::StoragesInfo const&, bool) build_docker/../src/Storages/System/StorageSystemProjectionPartsColumns.cpp:113:49 (clickhouse+0x1880196e)
    #2 DB::StorageSystemPartsBase::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) build_docker/../src/Storages/System/StorageSystemPartsBase.cpp:271:9 (clickhouse+0x187d3efc)
    #3 DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageSnapshot const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) build_docker/../src/Storages/IStorage.cpp:113:17 (clickhouse+0x1a3632de)
    #4 DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:2136:18 (clickhouse+0x19a1c8e2)
    #5 DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:1166:9 (clickhouse+0x19a14b27)
    #6 DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) build_docker/../src/Interpreters/InterpreterSelectQuery.cpp:625:5 (clickhouse+0x19a142d7)
    #7 DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:269:38 (clickhouse+0x19a87e56)
    #8 DB::InterpreterSelectWithUnionQuery::execute() build_docker/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:336:5 (clickhouse+0x19a88dd8)
    #9 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) build_docker/../src/Interpreters/executeQuery.cpp:704:36 (clickhouse+0x19ddb2b1)
    #10 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) build_docker/../src/Interpreters/executeQuery.cpp:1067:30 (clickhouse+0x19dd8a61)
    #11 DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:332:24 (clickhouse+0x1ac01c06)
    #12 DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1781:9 (clickhouse+0x1ac12827)
    #13 Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3 (clickhouse+0x1f8c7fa2)
    #14 Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20 (clickhouse+0x1f8c8812)
    #15 Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14 (clickhouse+0x1fb2d0b5)
    #16 Poco::(anonymous namespace)::RunnableHolder::run() build_docker/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1fb2b24f)
    #17 Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1fb298c7)

  Previous write of size 8 at 0x7b6400a507d0 by thread T195 (mutexes: write M37719978):
    #0 operator delete(void*, unsigned long) <null> (clickhouse+0xaf0c490)
    #1 void std::__1::__libcpp_operator_delete<void*, unsigned long>(void*, unsigned long) build_docker/../contrib/libcxx/include/new:255:3 (clickhouse+0x1a855bfe)
    #2 void std::__1::__do_deallocate_handle_size<>(void*, unsigned long) build_docker/../contrib/libcxx/include/new:281:10 (clickhouse+0x1a855bfe)
    #3 std::__1::__libcpp_deallocate(void*, unsigned long, unsigned long) build_docker/../contrib/libcxx/include/new:295:14 (clickhouse+0x1a855bfe)
    #4 std::__1::allocator<std::__1::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::__1::allocator<DB::MergeTreeDataPartCompact> > >::deallocate(std::__1::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::__1::allocator<DB::MergeTreeDataPartCompact> >*, unsigned long) build_docker/../contrib/libcxx/include/__memory/allocator.h:114:13 (clickhouse+0x1a855bfe)
    #5 std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::__1::allocator<DB::MergeTreeDataPartCompact> > > >::deallocate(std::__1::allocator<std::__1::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::__1::allocator<DB::MergeTreeDataPartCompact> > >&, std::__1::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::__1::allocator<DB::MergeTreeDataPartCompact> >*, unsigned long) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:282:13 (clickhouse+0x1a855bfe)
    #6 std::__1::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::__1::allocator<DB::MergeTreeDataPartCompact> >::__on_zero_shared_weak() build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:321:9 (clickhouse+0x1a855bfe)
    #7 std::__1::__shared_weak_count::__release_weak() build_docker/../contrib/libcxx/src/memory.cpp (clickhouse+0x216a8f76)
    #8 std::__1::__shared_weak_count::__release_shared() build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:217:9 (clickhouse+0x1a5283f2)
    #9 std::__1::shared_ptr<DB::IMergeTreeDataPart const>::~shared_ptr() build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:703:23 (clickhouse+0x1a5283f2)
    #10 void std::__1::__destroy_at<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, 0>(std::__1::shared_ptr<DB::IMergeTreeDataPart const>*) build_docker/../contrib/libcxx/include/__memory/construct_at.h:56:13 (clickhouse+0x1a5283f2)
    #11 void std::__1::destroy_at<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, 0>(std::__1::shared_ptr<DB::IMergeTreeDataPart const>*) build_docker/../contrib/libcxx/include/__memory/construct_at.h:81:5 (clickhouse+0x1a5283f2)
    #12 void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >::destroy<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, void, void>(std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> >&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>*) build_docker/../contrib/libcxx/include/__memory/allocator_traits.h:317:9 (clickhouse+0x1a5283f2)
    #13 std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >::__base_destruct_at_end(std::__1::shared_ptr<DB::IMergeTreeDataPart const>*) build_docker/../contrib/libcxx/include/vector:803:9 (clickhouse+0x1a5283f2)
    #14 std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >::__clear() build_docker/../contrib/libcxx/include/vector:797:29 (clickhouse+0x1a5283f2)
    #15 std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >::~vector() build_docker/../contrib/libcxx/include/vector:401:9 (clickhouse+0x1a5283f2)
    #16 DB::StorageReplicatedMergeTree::clearOldPartsAndRemoveFromZK() build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:6211:1 (clickhouse+0x1a5283f2)
    #17 DB::ReplicatedMergeTreeCleanupThread::iterate() build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp:60:13 (clickhouse+0x1a9f8a4c)
    #18 DB::ReplicatedMergeTreeCleanupThread::run() build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp:40:9 (clickhouse+0x1a9f884a)
    #19 DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0::operator()() const build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp:29:81 (clickhouse+0x1aa01141)
    #20 decltype(static_cast<DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0&>(fp)()) std::__1::__invoke<DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0&>(DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x1aa01141)
    #21 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0&>(DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x1aa01141)
    #22 std::__1::__function::__default_alloc_func<DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0, void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x1aa01141)
    #23 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::ReplicatedMergeTreeCleanupThread::ReplicatedMergeTreeCleanupThread(DB::StorageReplicatedMergeTree&)::$_0, void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x1aa01141)
    #24 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0x18bdff3e)
    #25 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0x18bdff3e)
    #26 DB::BackgroundSchedulePoolTaskInfo::execute() build_docker/../src/Core/BackgroundSchedulePool.cpp:105:5 (clickhouse+0x18bdff3e)
    #27 DB::TaskNotification::execute() build_docker/../src/Core/BackgroundSchedulePool.cpp:18:28 (clickhouse+0x18be286b)
    #28 DB::BackgroundSchedulePool::threadFunction() build_docker/../src/Core/BackgroundSchedulePool.cpp:279:31 (clickhouse+0x18be286b)
    #29 DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1::operator()() const build_docker/../src/Core/BackgroundSchedulePool.cpp:159:48 (clickhouse+0x18be3051)
    #30 decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0x18be3051)
    #31 decltype(auto) std::__1::__apply_tuple_impl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0x18be3051)
    #32 decltype(auto) std::__1::apply<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0x18be3051)
    #33 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0x18be3051)
    #34 decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x18be3051)
    #35 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x18be3051)
    #36 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x18be3051)
    #37 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x18be3051)
    #38 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xafe44ad)
    #39 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xafe44ad)
    #40 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:281:17 (clickhouse+0xafe44ad)
    #41 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:143:73 (clickhouse+0xafe7cf0)
    #42 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xafe7cf0)
    #43 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xafe7cf0)
    #44 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xafe7cf0)

  Mutex M37719978 (0x7b34002fca38) created at:
    #0 pthread_mutex_lock <null> (clickhouse+0xaeb4038)
    #1 std::__1::__libcpp_mutex_lock(pthread_mutex_t*) build_docker/../contrib/libcxx/include/__threading_support:303:10 (clickhouse+0x216a9359)
    #2 std::__1::mutex::lock() build_docker/../contrib/libcxx/src/mutex.cpp:33:14 (clickhouse+0x216a9359)
    #3 std::__1::lock_guard<std::__1::mutex>::lock_guard(std::__1::mutex&) build_docker/../contrib/libcxx/include/__mutex_base:91:27 (clickhouse+0x18bdfe90)
    #4 DB::BackgroundSchedulePoolTaskInfo::execute() build_docker/../src/Core/BackgroundSchedulePool.cpp:93:21 (clickhouse+0x18bdfe90)
    #5 DB::TaskNotification::execute() build_docker/../src/Core/BackgroundSchedulePool.cpp:18:28 (clickhouse+0x18be286b)
    #6 DB::BackgroundSchedulePool::threadFunction() build_docker/../src/Core/BackgroundSchedulePool.cpp:279:31 (clickhouse+0x18be286b)
    #7 DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1::operator()() const build_docker/../src/Core/BackgroundSchedulePool.cpp:159:48 (clickhouse+0x18be3051)
    #8 decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(fp)()) std::__1::__invoke_constexpr<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&) build_docker/../contrib/libcxx/include/type_traits:3648:23 (clickhouse+0x18be3051)
    #9 decltype(auto) std::__1::__apply_tuple_impl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1 (clickhouse+0x18be3051)
    #10 decltype(auto) std::__1::apply<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1 (clickhouse+0x18be3051)
    #11 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:188:13 (clickhouse+0x18be3051)
    #12 decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0x18be3051)
    #13 void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9 (clickhouse+0x18be3051)
    #14 std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12 (clickhouse+0x18be3051)
    #15 void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16 (clickhouse+0x18be3051)
    #16 std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16 (clickhouse+0xafe44ad)
    #17 std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12 (clickhouse+0xafe44ad)
    #18 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:281:17 (clickhouse+0xafe44ad)
    #19 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:143:73 (clickhouse+0xafe7cf0)
    #20 decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23 (clickhouse+0xafe7cf0)
    #21 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5 (clickhouse+0xafe7cf0)
    #22 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) build_docker/../contrib/libcxx/include/thread:293:5 (clickhouse+0xafe7cf0)

  Thread T309 'TCPHandler' (tid=1707, running) created by thread T246 at:
    #0 pthread_create <null> (clickhouse+0xae96d5d)
    #1 Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:202:6 (clickhouse+0x1fb29315)
    #2 Poco::Thread::start(Poco::Runnable&) build_docker/../contrib/poco/Foundation/src/Thread.cpp:128:2 (clickhouse+0x1fb2ab8c)
    #3 Poco::PooledThread::start() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:85:10 (clickhouse+0x1fb2eea6)
    #4 Poco::ThreadPool::getThread() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:461:14 (clickhouse+0x1fb2eea6)
    #5 Poco::ThreadPool::startWithPriority(Poco::Thread::Priority, Poco::Runnable&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:365:2 (clickhouse+0x1fb2f2a7)
    #6 Poco::Net::TCPServerDispatcher::enqueue(Poco::Net::StreamSocket const&) build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:152:17 (clickhouse+0x1f8c8d0e)
    #7 Poco::Net::TCPServer::run() build_docker/../contrib/poco/Net/src/TCPServer.cpp:148:21 (clickhouse+0x1f8c7827)
    #8 Poco::(anonymous namespace)::RunnableHolder::run() build_docker/../contrib/poco/Foundation/src/Thread.cpp:55:11 (clickhouse+0x1fb2b24f)
    #9 Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27 (clickhouse+0x1fb298c7)

  Thread T195 'BgSchPool' (tid=605, running) created by main thread at:
    #0 pthread_create <null> (clickhouse+0xae96d5d)
    #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) build_docker/../contrib/libcxx/include/__threading_support:375:10 (clickhouse+0xafe77a0)
    #2 std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'(), void>(void&&) build_docker/../contrib/libcxx/include/thread:309:16 (clickhouse+0xafe77a0)
    #3 void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) build_docker/../src/Common/ThreadPool.cpp:143:35 (clickhouse+0xafe2ad4)
    #4 ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) build_docker/../src/Common/ThreadPool.cpp:175:5 (clickhouse+0xafe3407)
    #5 ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) build_docker/../src/Common/ThreadPool.h:169:38 (clickhouse+0x18be0cb8)
    #6 DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*) build_docker/../src/Core/BackgroundSchedulePool.cpp:159:18 (clickhouse+0x18be0cb8)
    #7 std::__1::__unique_if<DB::BackgroundSchedulePool>::__unique_single std::__1::make_unique<DB::BackgroundSchedulePool, unsigned long&, unsigned long const&, char const (&) [10]>(unsigned long&, unsigned long const&, char const (&) [10]) build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:725:32 (clickhouse+0x194f8b42)
    #8 DB::Context::getSchedulePool() const build_docker/../src/Interpreters/Context.cpp:1865:33 (clickhouse+0x194f8b42)
    #9 DB::DatabaseCatalog::loadDatabases() build_docker/../src/Interpreters/DatabaseCatalog.cpp:149:38 (clickhouse+0x1956bf97)
    #10 DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) build_docker/../programs/server/Server.cpp:1491:26 (clickhouse+0xaf1f5ef)
    #11 Poco::Util::Application::run() build_docker/../contrib/poco/Util/src/Application.cpp:334:8 (clickhouse+0x1f8dfe2a)
    #12 DB::Server::run() build_docker/../programs/server/Server.cpp:456:25 (clickhouse+0xaf11ab4)
    #13 Poco::Util::ServerApplication::run(int, char**) build_docker/../contrib/poco/Util/src/ServerApplication.cpp:611:9 (clickhouse+0x1f8fe4c6)
    #14 mainEntryClickHouseServer(int, char**) build_docker/../programs/server/Server.cpp:187:20 (clickhouse+0xaf0f5d6)
    #15 main build_docker/../programs/main.cpp:409:12 (clickhouse+0xaf0d233)

SUMMARY: ThreadSanitizer: heap-use-after-free build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.h:121:53 in DB::IMergeTreeDataPart::getTotalColumnsSize() const
```

### PR DESCRIPTION
**Pull request by amosbird**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible heap-use-after-free error when reading system.projection_parts and system.projection_parts_columns . This fixes https://github.com/ClickHouse/ClickHouse/issues/37184

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -4362,27 +4362,17 @@ MergeTreeData::DataPartsVector MergeTreeData::getDataPartsVectorForInternalUsage
...
             }
         }
-        else
-        {
-            std::swap(buf, res);
-            res.clear();
-            std::merge(range.begin(), range.end(), buf.begin(), buf.end(), std::back_inserter(res), LessDataPart()); //-V783
-        }
+
+        std::swap(buf, res);
```
Comment (amosbird) [inline src/Storages/MergeTree/MergeTreeData.cpp:4366]: We need to hold parent parts when iterating over projection parts.

**Review by tavplubix — CHANGES_REQUESTED** [review]
So now `getDataPartsVectorForInternalUsage(...)` mixes normal parts and projection parts in one vector? How do I work with vector returned from this method? Check `getParentPart()` for `nullptr` each time? 

Also seems like `require_projection_parts` flag is set to true only when we get all parts for showing them in system tables. Let's remove this flag from `getDataPartsVectorForInternalUsage(...)` and create separate method that returns set of projection parts for introspection purposes.

**Review by tavplubix — APPROVED** [review]
