### PR TITLE
Fix incorrect L2 distance calculations for `QBit` columns with type-mismatched reference vectors

### LINKED ISSUE #89976: QBit Vector Search Yields Near-Zero Recall and High Latency
### Company or project name

_No response_

### Describe the situation

The new QBit vector indexing feature (as introduced in the ClickHouse blog post “We built a vector search engine that lets you choose precision at query time”) is not behaving as expected. When testing QBit on the same real dataset of 1 million high-dimensional vectors (DBpedia 1M entity embeddings, 1536-dim Float32 each) mentioned in the blog post, we observed extremely low recall (~0%) at all tested precision levels. This contrasts with the blog’s claims.

### Which ClickHouse versions are affected?

ClickHouse version: 25.11.1.2141 (official build).

### How to reproduce

[ch_qbit_issue.py](https://github.com/user-attachments/files/23521473/ch_qbit_issue.py)

### Expected performance

According to the QBit design, reducing precision should trade off some accuracy for performance, and higher precision should yield accuracy closer to brute-force. In the ClickHouse blog’s own DBpedia example, a 5-bit QBit query produced “surprisingly good” results while running faster than brute-force.

The actual outcomes were the opposite: Recall stayed near zero for all tested precisions, and query times did not show the intended speedup (in fact, 8–10 bit queries were 2–2.5× slower than brute-force, and even the 4-bit query was ~200 ms, about on par with brute force). Increasing the precision from 4 to 10 bits did not materially improve the accuracy.

### Additional context

The QBit feature was enabled via setting `allow_experimental_qbit_type = 1`

### PR DESCRIPTION
**Pull request by rienath**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed incorrect distance calculations in `L2DistanceTransposed` when using array reference vectors (which default to `Array(Float64))` with `QBit` columns of non-`Float64` element types (`Float32`, `BFloat16`). The function now automatically casts the reference vector to match the `QBit`'s element type. Resolves #89976

### Details
Closes https://github.com/ClickHouse/ClickHouse/issues/89976

### CODE REVIEW

File: src/Functions/array/l2DistanceTransposed.cpp [hunk 1]
```diff
@@ -179,14 +192,34 @@ class FunctionArrayDistance : public IFunction
...
+        /// Check that the number of bit planes doesn't exceed the maximum precision for the reference vector type.
+        size_t max_precision_for_type = 0;
+        if (ref_vec_type_id == TypeIndex::BFloat16)
+            max_precision_for_type = 16;
+        else if (ref_vec_type_id == TypeIndex::Float32)
+            max_precision_for_type = 32;
+        else if (ref_vec_type_id == TypeIndex::Float64)
+            max_precision_for_type = 64;
+        else
+            return false;
```
Comment (Avogar) [inline src/Functions/array/l2DistanceTransposed.cpp]: We already checked that type is one of `BFloat16`, `Float32`, `Float64` above, so here we can do just this:
```suggestion
        size_t max_precision_for_type = ref_vec_type->getNestedType()->getSizeOfValueInMemory() * 8;
```

File: src/Functions/array/l2DistanceTransposed.cpp [hunk 2]
```diff
@@ -179,14 +192,34 @@ class FunctionArrayDistance : public IFunction
...
+
+        if (precision > max_precision_for_type)
+            throw Exception(
+                ErrorCodes::BAD_ARGUMENTS,
+                "Number of bit planes ({}) exceeds the maximum precision ({}) for reference vector type {}",
+                precision,
+                max_precision_for_type,
+                ref_vec_type->getNestedType()->getName());
```
Comment (Avogar) [inline src/Functions/array/l2DistanceTransposed.cpp]: In other cases here we return `false` on any mismatch to fallback to non-optimized version, should we do the same here?

Comment (rienath) [reply src/Functions/array/l2DistanceTransposed.cpp]: Good idea. On one hand, we've done enough checks to be sure we are in the optimized version by this point. But the user should not be touching it anyway, so no point returning a nice-looking error

**Review by rienath — COMMENTED** [review]
Thanks for the review! I've addressed both points you raised

**Review by Avogar — APPROVED** [review]

**Comment by rienath** [comment]
Errors BuzzHouse found are unrelated.

[PR / Build (amd_compat) (pull_request)](https://github.com/ClickHouse/ClickHouse/actions/runs/19546107121/job/55974174265?pr=90485)
* https://github.com/ClickHouse/ClickHouse/issues/90492

[PR / Integration tests (amd_tsan, 5/6) (pull_request)](https://github.com/ClickHouse/ClickHouse/actions/runs/19546107121/job/55974175125?pr=90485)
* https://github.com/ClickHouse/ClickHouse/issues/88775

[PR / Stress test (amd_tsan) (pull_request)](https://github.com/ClickHouse/ClickHouse/actions/runs/19546107121/job/55974175090?pr=90485)
* [Hung check regularly fails](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdIdW5nIGNoZWNrIGZhaWxlZCwgcG9zc2libGUgZGVhZGxvY2sgZm91bmQgKHNlZSBodW5nX2NoZWNrLmxvZyknCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdTdHJlc3MgdGVzdCAoYW1kX3RzYW4pJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)
