### PR TITLE
Forbid empty `ORDER BY` key in special `MergeTree` storages

### LINKED ISSUE #88633: Logical error: 'Written 1 elements of column c0, but 0 rows of PK columns'
### Describe the bug

Not so easy to reproduce. Related to vertical merges?

### How to reproduce

My [users.xml](https://github.com/user-attachments/files/22945774/users.xml)

On a debug build run:
```sql
CREATE TABLE t0 (c0 String) ENGINE = ReplacingMergeTree() PRIMARY KEY tuple() SETTINGS min_bytes_for_wide_part = 0, vertical_merge_algorithm_min_bytes_to_activate = 1, vertical_merge_algorithm_min_rows_to_activate = 0, index_granularity = 1, vertical_merge_algorithm_min_columns_to_activate = 1;
INSERT INTO TABLE t0 (c0) VALUES ('do'), ('你们'), ('日本'), (')'), ('day'), ('try'), (NULL), ('爸爸'), ('哪国人'), (x'E28228FF'), ('😉'), ('{'), (';'), ('漂亮'), ('照片'), ('\0'), ('move'), ('think'), ('日本'), ('is'), ('c\nc'), ('{}'), ('美国'), (NULL), ('照片'), (NULL), ('look'), ('thing'), (NULL), ('😉'), ('keep'), (NULL), ('back'), ('show'), ('😉'), ('{}'), ('照片'), ('cut'), ('名字'), ('兄弟姐妹'), ('美国'), ('1'), (NULL), ('叫'), ('😉'), ('/'), ('b\tb'), ('爸爸'), (','), ('ask'), (NULL), ('man'), ('want'), ('0'), (NULL), ('look'), ('walk'), (''), ('will'), ('哪国人'), ('watch'), (NULL), ('had'), ('漂亮'), (NULL), (NULL), ('seem'), ('find'), (NULL), ('sentence'), (')'), ('{'), ('照片'), ('\\'), ('认识你很高兴'), (x'A0A1'), ('say'), ('ask'), ('认识你很高兴'), ('null'), ('back'), (NULL), ('你们'), ('has'), (x'E28228FF'), ('照片'), ('漂亮'), ('[]'), ('should'), ('went'), ('日本'), ('know'), ('play'), ('open'), ('你们'), ('-1'), ('日本'), ('认识你很高兴'), ('FALSE'), ('name'), ('名字'), ('()'), (';'), ('你们'), ('think'), ('study'), ('thought'), ('follow'), ('study'), (''), ('-1'), ('叫'), ('\''), ('叫'), (''), (NULL), ('漂亮'), ('had'), (NULL), ('water'), ('does}日本照片日本]make认识你很高兴'), ('let'), ('你们'), ('say'), ('should'), ('你们'), ('_'), (x'AAC328'), ('😉'), ('--'), ('close'), ('have'), ('日本'), ('place'), ('美国'), ('哪国人'), ('哪国人'), ('thing'), ('叫'), ('show'), ('{}'), ('认识你很高兴'), ('()'), ('\n'), ('need'), ('漂亮'), ('漂亮'), ('use'), ('你们'), ('\n'), ('漂亮'), ('see'), ('兄弟姐妹'), ('read'), (NULL), ('美国'), ('日本'), ('NULL'), ('might'), ('grow'), ('took'), ('兄弟姐妹'), ('get'), ('be'), (x'F0288C28'), ('你们'), ('can'), ('has'), (':'), ('did'), ('got'), ('日本'), ('carry'), ('may'), ('grow'), ('said'), ('hear'), ('😉'), (x'C328'), (NULL), ('哪国人'), ('爸爸'), ('哪国人');
INSERT INTO TABLE t0 (c0) SELECT c0 FROM generateRandom('c0 String', 11534244747785854120, 6119, 2) LIMIT 679;
INSERT INTO TABLE t0 (c0) SELECT 'need' FROM numbers(522);
INSERT INTO TABLE t0 (c0) SELECT c0 FROM generateRandom('c0 String', 17010632438609867543, 501, 10) LIMIT 972;
INSERT INTO TABLE t0 (c0) SELECT '.' FROM numbers(878);
```
It may take a few tries, not sure if race condition.

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Written 1 elements of column c0, but 0 rows of PK columns'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000241d14f2
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014aa46e9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d38d30e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d38cd11
4. src/Common/Exception.h:141: DB::Exception::Exception<String, String const&, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String const&>::type, std::type_identity<String>::type>, String&&, String const&, String&&) @ 0x0000000019c6aaf6
5. src/Storages/MergeTree/MergeTask.cpp:1373: DB::MergeTask::VerticalMergeStage::finalizeVerticalMergeForOneColumn() const @ 0x000000001dc481d9
6. src/Storages/MergeTree/MergeTask.cpp:1643: DB::MergeTask::VerticalMergeStage::executeVerticalMergeForAllColumns() const @ 0x000000001dc4abdc
7. src/Storages/MergeTree/MergeTask.cpp:1564: DB::MergeTask::VerticalMergeStage::execute() @ 0x000000001dc4a6d9
8. src/Storages/MergeTree/MergeTask.cpp:1658: DB::MergeTask::execute() @ 0x000000001dc49ff6
9. src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:58: DB::MergePlainMergeTreeTask::executeStep() @ 0x000000001dcb84ce
10. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:305: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x000000001dc77175
11. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:369: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001dc77c82
12. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000014be7d13
13. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000014bee3e6
14. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000014be51a6
15. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000014bebbc0
16. start_thread @ 0x00000000000a27f1
17. __clone3 @ 0x0000000000133b5c
```

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
It is now forbidden to create special `MergeTree` tables (such as `ReplacingMergeTree`, `CollapsingMergeTree`, etc.) with an empty `ORDER BY` key, since merge behavior in these tables is undefined.  If you still need to create such a table, enable the `allow_suspicious_primary_key` setting.  

Fixes #88633.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTask.cpp [hunk 1]
```diff
@@ -282,20 +282,17 @@ void MergeTask::ExecuteAndFinalizeHorizontalPart::extractMergingAndGatheringColu
...
+    /// Force is_deleted column for Replacing mode
+    if (!global_ctx->merging_params.is_deleted_column.empty())
         key_columns.emplace(global_ctx->merging_params.is_deleted_column);
-        key_columns.emplace(global_ctx->merging_params.version_column);
-    }
 
-    /// Force sign column for VersionedCollapsing mode. Version is already in primary key.
-    if (global_ctx->merging_params.mode == MergeTreeData::MergingParams::VersionedCollapsing)
-        key_columns.emplace(global_ctx->merging_params.sign_column);
+    /// Force version column for Replacing mode
```
Comment (antaljanosbenjamin) [inline src/Storages/MergeTree/MergeTask.cpp]:
```suggestion
    /// Force version column for Replacing mode and VersionedCollapsing mode
```

**Review by antaljanosbenjamin — COMMENTED** [review]
I guess some of the tests should be fixed, but the changes looks okay.
