### PR TITLE
Increase max array size in group bitmap

### LINKED ISSUE #50233: Changes in #47519 cause queries to fail on some bitmap columns
The PR #47519(since 23.3) imposes the size restriction to 1GiB when reading data from bitmap columns.

https://github.com/ClickHouse/ClickHouse/blob/f1a3c9cfd5c9c533fdba7478ed0b209d9bb71262/src/AggregateFunctions/AggregateFunctionGroupBitmapData.h#L125-L131

This introduces backward compatibilty problem. We have lots of cases that the cardinality of a bitmap is tens of millions, however, after #47519, we can't read these data any more.

A very simple case illustrates this problem.

```sql
CREATE TABLE bitmap_test
(
    `id` UInt64,
    `bitmap` AggregateFunction(groupBitmap, UInt64)
)
ENGINE = AggregatingMergeTree
ORDER BY id

-- simulate to generate 50,000,000 different id
INSERT INTO bitmap_test SELECT
    toUInt64(101),
    groupBitmapState(rand64())
FROM numbers(50000000)

-- TOO_LARGE_ARRAY_SIZE error is raised since 23.3
-- Before 23.3 it only takes some time and some memory to compute the cardinality
SELECT bitmapCardinality(bitmap) FROM bitmap_test
```

If the data is inserted in old version, and after upgrading to 23.3, queries fail to compute `bitmapCardinality` or execute some other functions.

I think this size restriction during read does not make sense, because we can still insert more than 1GiB data to the bitmap.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/50233

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionGroupBitmapData.h [hunk 1]
```diff
@@ -122,7 +122,7 @@ class RoaringBitmapWithSmallSet : private boost::noncopyable
             size_t size;
             readVarUInt(size, in);
 
-            static constexpr size_t max_size = 1_GiB;
+            static constexpr size_t max_size = 100_GiB;
```
Comment (Algunenano) [inline src/AggregateFunctions/AggregateFunctionGroupBitmapData.h:125]: Having such a high limit here seems dangerous. It seems like it will allocate a huge amount of memory without checking max_memory_usage, leading to a server being killed by OOM.

I've tested it doing something like:
```
static constexpr size_t max_size = 1000_GiB;
```

```sql
SELECT CAST(unhex('0181808080908380000000'), 'AggregateFunction(groupBitmap, UInt64)')
SETTINGS max_memory_usage = 536870912
```

```
jun 06 13:34:14 Mordor clickhouse[338865]: 2023.06.06 11:34:14.015792 [ 339142 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 87.27 GiB, peak 87.27 GiB, free memory in arenas 596.00 KiB, will set to 89.86 GiB (RSS), difference: 2.60 GiB
jun 06 13:34:14 Mordor clickhouse[338865]: 2023.06.06 11:34:14.017429 [ 339142 ] {} <Debug> MemoryTracker: Current memory usage (total): 89.86 GiB.
jun 06 13:34:15 Mordor clickhouse[338819]: 2023.06.06 11:34:15.129934 [ 338819 ] {} <Fatal> Application: Child process was terminated by signal 9 (KILL). If it is not done by 'forcestop' command or manually, the possible cause is OOM Killer (see 'dmesg' and look at the '/var/log/kern.log' for the details).
```
