### PR TITLE
MaterializeMySQL: support ENUM data type

### LINKED ISSUE #18310: MaterializedMySQL: Support ENUM data type
I was checking out this new  feature - on MYSQL I have a table customer

```
CREATE TABLE `addresses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `street` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `zip` varchar(255) NOT NULL,
  `type` enum('SHIPPING','BILLING','LIVING') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `address_customer` (`customer_id`),
  CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1
```

But replication is failing when using  MaterializeMySQL

```
2020.12.21 11:56:08.925135 [ 48 ] {} <Debug> executeQuery: (internal) /*Materialize MySQL step 1: execute MySQL DDL for dump data*/ EXTERNAL DDL FROM MySQL(inventory, inventory) CREATE TABLE `addresses` ( `id` int(11) NOT NULL AUTO_INCREMENT, `customer_id` int(11) NOT NULL, `street` varchar(255) NOT NULL, `city` varchar(255) NOT NULL, `state` varchar(255) NOT NULL, `zip` varchar(255) NOT NULL, `type` enum('SHIPPING','BILLING','LIVING') NOT NULL, PRIMARY KEY (`id`), KEY `address_customer` (`customer_id`), CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1
2020.12.21 11:56:08.925526 [ 48 ] {} <Error> MaterializeMySQLSyncThread(inventory): Query EXTERNAL DDL FROM MySQL(inventory, inventory)  CREATE TABLE `addresses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `street` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `zip` varchar(255) NOT NULL,
  `type` enum('SHIPPING','BILLING','LIVING') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `address_customer` (`customer_id`),
  CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1 wasn't finished successfully: Code: 50, e.displayText() = DB::Exception: Unknown data type family: enum. Maybe you meant: ['Enum','Enum8'], Stack trace (when copying this message, always include the lines below):

0. DB::DataTypeFactory::findCreatorByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xd52a936 in /usr/bin/clickhouse
1. DB::DataTypeFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&) const @ 0xd529bf8 in /usr/bin/clickhouse
2. DB::DataTypeFactory::get(std::__1::shared_ptr<DB::IAST> const&) const @ 0xd5299e0 in /usr/bin/clickhouse
3. ? @ 0xdcc8388 in /usr/bin/clickhouse
4. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdcc4907 in /usr/bin/clickhouse
5. DB::MySQLInterpreter::InterpreterMySQLDDLQuery<DB::MySQLInterpreter::InterpreterCreateImpl>::execute() @ 0xd922fac in /usr/bin/clickhouse
6. DB::InterpreterExternalDDLQuery::execute() @ 0xd922027 in /usr/bin/clickhouse
7. ? @ 0xdca2baa in /usr/bin/clickhouse
8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdca177d in /usr/bin/clickhouse
9. ? @ 0xd8d13e4 in /usr/bin/clickhouse
10. ? @ 0xd8e9128 in /usr/bin/clickhouse
11. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xd8eed2e in /usr/bin/clickhouse
12. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0xd8ef221 in /usr/bin/clickhouse
13. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xd8caff9 in /usr/bin/clickhouse
14. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xd8ca67a in /usr/bin/clickhouse
15. ? @ 0xd8e87ca in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b7293d in /usr/bin/clickhouse
17. ? @ 0x7b76463 in /usr/bin/clickhouse
18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.11.4.13 (official build))
2020.12.21 11:56:08.925748 [ 48 ] {} <Error> MaterializeMySQLSyncThread: Code: 50, e.displayText() = DB::Exception: Unknown data type family: enum. Maybe you meant: ['Enum','Enum8'], Stack trace (when copying this message, always include the lines below):

```

### PR DESCRIPTION
**Pull request by sand6255**
* Implemented Enum for MaterializeMySQL

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
MaterializeMySQL now supports `ENUM` data type.

Detailed description / Documentation draft
MaterializeMySQL now supports `ENUM` data type. It is converted to `Enum8` if the number of elements in `ENUM` is less than 128, otherwise it is converted to `Enum16`. Enumerator names are case-sensitive by design and require the use of canonical casing from MySQL column.

Resolves [#18310](https://github.com/ClickHouse/ClickHouse/issues/18310)

### CODE REVIEW

File: src/Formats/MySQLBlockInputStream.cpp [hunk 1]
```diff
@@ -157,6 +158,14 @@ namespace
                 assert_cast<ColumnFloat64 &>(column).insertValue(value.getDouble());
                 read_bytes_size += 8;
                 break;
+            case ValueType::vtEnum8:
+                assert_cast<ColumnInt8 &>(column).insertValue(static_cast<const DataTypeEnum<Int8> &>(data_type).castToValue(value.data()).get<Int64>());
```
Comment (kssenii) [inline src/Formats/MySQLBlockInputStream.cpp:162]:
```suggestion
                assert_cast<ColumnInt8 &>(column).insertValue(assert_cast<const DataTypeEnum<Int8> &>(data_type).castToValue(value.data()).get<Int64>());
```

File: src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp [hunk 2]
```diff
@@ -92,22 +92,40 @@ static NamesAndTypesList getColumnsList(const ASTExpressionList * columns_defini
...
+                if (type_name_upper.find("INT") != String::npos && !endsWith(type_name_upper, "SIGNED")
                     && !endsWith(type_name_upper, "UNSIGNED"))
                     data_type_function->name = type_name_upper + " UNSIGNED";
             }
-        }
 
+            /// Transforms MySQL ENUM's list of strings to ClickHouse string-integer pairs
+            /// For example ENUM('a', 'b', 'c') -> ENUM('a'=1, 'b'=2, 'c'=3)
+            /// Elements on a position further than 32767 are assigned negative values, starting with -32768.
+            /// Note: Enum would be transformed to Enum8 if number of ellements is less then 128, otherwise it would be transformed to Enum16.
```
Comment (kssenii) [inline src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp:112]:
```suggestion
            /// Note: Enum would be transformed to Enum8 if number of elements is less then 128, otherwise it would be transformed to Enum16.
```

File: src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp [hunk 3]
```diff
@@ -92,22 +92,40 @@ static NamesAndTypesList getColumnsList(const ASTExpressionList * columns_defini
...
+        if (data_type_function)
         {
-            auto * data_type_function = data_type->as<ASTFunction>();
+            String type_name_upper = Poco::toUpper(data_type_function->name);
 
-            if (data_type_function)
+            if (is_unsigned)
             {
-                String type_name_upper = Poco::toUpper(data_type_function->name);
-
```
Comment (kssenii) [inline src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp:103]: Though it does not change anything, but seems like previous ordering was better.

**Review by kssenii — APPROVED** [review]
LGTM

File: src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp (hunk 3 above)
Comment (sand6255) [reply src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp:103]: The new ordering allows us to share `if (data_type_function)` between the new and the old code, if `if (is_unsigned)` goes first - we will later have to have separate `if (data_type_function)` for the new code.

Comment (kssenii) [reply src/Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp:103]: Ok
