### PR TITLE
Fix move_functions_out_of_any optimisation with lambda

### LINKED ISSUE #12621: DB::Exception: lambda argument declarations must be identifiers.
```
:) CREATE TABLE test
(
    `Source.C1` Array(UInt64),
    `Source.C2` Array(UInt64)
)
ENGINE = MergeTree()
ORDER BY tuple()

:) SELECT any(arrayFilter((c, d) -> (4 = d), `Source.C1`, `Source.C2`)[1]) AS x
FROM test
WHERE 0
GROUP BY 42

Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: lambda argument declarations must be identifiers. 

```

### PR DESCRIPTION
**Pull request by 4ertus2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix optimization `optimize_move_functions_out_of_any=1` in case of `any(func(<lambda>))`.

Closes #12621

### CODE REVIEW

File: src/Interpreters/RewriteAnyFunctionVisitor.cpp [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+    for (auto * ast_to_change : identifiers)
+    {
+        ASTPtr identifier_ast = *ast_to_change;
+        *ast_to_change = makeASTFunction(func.name);
+        (*ast_to_change)->as<ASTFunction>()->arguments->children.emplace_back(identifier_ast);
+    }
+
+    /// Unwrap function: any(f(any(x), any(y), g(any(z)))) -> f(any(x), any(y), g(any(z)))
+    String alias = func.alias;
+    ast = func_arguments[0];
```
Comment (CurtizJ) [inline src/Interpreters/RewriteAnyFunctionVisitor.cpp:76]: Do we need to clone ast here? There was a problem with it in previous implemetation.

Comment (4ertus2) [reply src/Interpreters/RewriteAnyFunctionVisitor.cpp:76]: I think it's OK. We rewrite it on exit with its child. I can't imagine situation where it could lead to troubles.

**Comment by 4ertus2** [comment]
This query fails
```
WITH any(number * 1) AS x SELECT x FROM numbers(1);
```

**Comment by CurtizJ** [comment]
Seems that clone of ast is still needed. Previously there was the problem.
https://github.com/ClickHouse/ClickHouse/pull/11529#discussion_r437420658

**Comment by 4ertus2** [comment]
> Seems that clone of ast is still needed.

I've made a solution without `clone()`. Clone after `normalize()` brakes indirect assumption that the aliases links to the same AST object. This assumtion should not be used later. But all our tests are for scenario where we do not brake this assumption. So it's very easy to catch bugs here.

**Review by CurtizJ — APPROVED** [review]
