### PR TITLE
Issue-88496: fix limit not pushed down

### LINKED ISSUE #88496: LIMIT not pushed down when inject_random_order_for_select_without_order_by = 1
### Describe what's wrong

When the setting `inject_random_order_for_select_without_order_by` is enabled, the query planner no longer pushes down the LIMIT to the data-source stage.
This causes the query to scan indefinitely on sources like `system.numbers`, since LimitTransform no longer stops data generation early.

### How to reproduce

1. Without random order injection
```sql
SET inject_random_order_for_select_without_order_by = 0;
functional-tests :) EXPLAIN PLAN SELECT number
FROM system.numbers
LIMIT 1;
┌─explain─────────────────────────────────────────────────────────────────────────────────┐
1. │ Expression ((Project names + (Projection + Change column names to column identifiers))) │
2. │   Limit (preliminary LIMIT (without OFFSET))                                            │
3. │     ReadFromSystemNumbers                                                               │
   └─────────────────────────────────────────────────────────────────────────────────────────┘
```

Limit appears directly above ReadFromSystemNumbers — limit is pushed down and the query terminates correctly.

2. With random order injection enabled
```sql
SET inject_random_order_for_select_without_order_by = 1;
functional-tests :) EXPLAIN PLAN SELECT number
FROM system.numbers
LIMIT 1;
Query id: 2915a6cc-285e-4e70-afb3-f963ba35e204   ┌─explain─────────────────────────────────────────────────────────────────────────────────────────┐
1. │ Expression (Project names)                                                                      │
2. │   Limit (preliminary LIMIT (without OFFSET))                                                    │
3. │     Sorting (Sorting for ORDER BY)                                                              │
4. │       Expression ((Before ORDER BY + (Projection + Change column names to column identifiers))) │
5. │         ReadFromSystemNumbers                                                                   │
   └─────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Limit is now above the Sorting step (inserted for ORDER BY rand()), which means the LimitTransform is no longer pushed down to the source.
As a result, the query no longer stops — it reads from system.numbers endlessly.

**Note** - Similar behavior when below query is run with inject_random_order_for_select_without_order_by is disabled

```sql
SET inject_random_order_for_select_without_order_by = 0;
EXPLAIN SELECT number FROM system.numbers ORDER BY number LIMIT 1;

EXPLAIN
SELECT number
FROM system.numbers
ORDER BY number ASC
LIMIT 1

Query id: 8f3ce075-df43-4612-8f7c-0d8b72a708b4

   ┌─explain─────────────────────────────────────────────────────────────────────────────────────────┐
1. │ Expression (Project names)                                                                      │
2. │   Limit (preliminary LIMIT (without OFFSET))                                                    │
3. │     Sorting (Sorting for ORDER BY)                                                              │
4. │       Expression ((Before ORDER BY + (Projection + Change column names to column identifiers))) │
5. │         ReadFromSystemNumbers                                                                   │
   └─────────────────────────────────────────────────────────────────────────────────────────────────┘

```
Version: **master**

### PR DESCRIPTION
**Pull request by NilSper**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Details

Resolves #88496

Instead of injecting a `ORDER BY rand()` into the top-level `SELECT` queries, wrap these queries into a new `SELECT` query that includes the `ORDER BY rand()`.

Example:
```
SET inject_random_order_for_select_without_order_by = 1;
SELECT number FROM system.numbers LIMIT 1
```
is transformed into:

```
SELECT * FROM (
    SELECT number FROM system.numbers LIMIT 1)
ORDER BY rand();
```
This ensures that the `LIMIT` section is executed before the `ORDER BY` section.

### CODE REVIEW

**Comment by NilSper** [comment]
@rschu1ze should I link to the original Issue or only once it's ready for review?

**Comment by rschu1ze** [comment]
@NilSper Nevermind, I updated the PR message so it links to the issue.

**Comment by NilSper** [comment]
@rschu1ze how do I trigger the CI checks?

**Comment by rschu1ze** [comment]
I added the magic keyword.

grafik

**Comment by NilSper** [comment]
@rschu1ze what's the CH Inc sync and how can I check what's wrong?

**Comment by rschu1ze** [comment]
> @rschu1ze what's the CH Inc sync and how can I check what's wrong?

No worries, only ClickHouse employees can check (I'll do that).
"CH Inc sync" basically ensures that the PR doesn't break anything in our private repository.

File: src/Analyzer/QueryTreePassManager.h [hunk 1]
```diff
@@ -25,15 +25,15 @@ class QueryTreePassManager : public WithContext
     void addPass(QueryTreePassPtr pass);
 
     /// Run query tree passes on query tree
-    void run(QueryTreeNodePtr & query_tree_node);
+    void run(QueryTreeNodePtr query_tree_node);
```
Comment (NilSper) [inline src/Analyzer/QueryTreePassManager.h]: @rschu1ze without the reference to the shared_ptr in the Manager, I cannot easily replace the top-level QueryNode with my wrapping QueryNode that incl the ORDER BY rand(). What do you think?

**Comment by NilSper** [comment]
@rschu1ze do you have any change requests or can we merge this PR?

**Comment by rschu1ze** [comment]
@NilSper We should be good. I merged from master again and then we can get this PR in. Thanks.

**Comment by rschu1ze** [comment]
BuzzHouse: False positive.

Text index test failure: fixed in https://github.com/ClickHouse/ClickHouse/pull/90124

**Comment by clickgapai** [comment]
Hi @NilSper @rschu1ze — while reviewing this PR I found the following:

- **Bug (P1):** `wrapWithSelectOrderBy` breaks all `SELECT FROM VIEW` queries when `inject_random_order_for_select_without_order_by` is enabled — https://github.com/ClickHouse/ClickHouse/issues/102933

Happy to discuss — close anything that's wrong or already addressed.
