### PR TITLE
ISSUES-16835 try fix miss match header with MySQL SHOW statement

### LINKED ISSUE #16835: Use MaterializeMySQL synchronization problem
When I used ClickHouse's MaterializeMySQL feature to synchronize data from MySQL to ClickHouse, I had some problems. The Click House version I'm using is 20.10.3.30, and the MySQL version I'm using is 5.7.28-log.

The SQL statement I executed is as follows:
> SET allow_experimental_database_materialize_mysql = 1;
drop database if exists ck_test;
CREATE DATABASE if not exists ck_test ENGINE = MaterializeMySQL('x.x.x.x:3306', 'test', 'user', 'test');

After I executed the SQL statement, I saw the following information from the error log /var/log/clickhouse-server/clickhouse-server.err. Log:

> 2020.11.10 20:27:39.611578 [ 33057 ] {} <Error> MaterializeMySQLSyncThread: Code: 20, e.displayText() = DB::Exception: mysqlxx::UseQueryResult contains 4 columns while 2 expected, Stack trace (when copying this message, always include the lines below):

> 0. DB::MySQLBlockInputStream::MySQLBlockInputStream(mysqlxx::Pool::Entry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, unsigned long, bool) @ 0xe587457 in /usr/bin/clickhouse

> 1. DB::MaterializeMetadata::MaterializeMetadata(mysqlxx::Pool::Entry&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdb1cbf3 in /usr/bin/clickhouse

> 2. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf8bf1 in /usr/bin/clickhouse

> 3. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaf836a in /usr/bin/clickhouse

> 4. ? @ 0xdb1480d in /usr/bin/clickhouse

> 5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse

> 6. ? @ 0x7b8d153 in /usr/bin/clickhouse

> 7. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so

> 8. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

>  (version 20.10.3.30 (official build))

Does anybody have a problem like this?

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fixes #16835 
try fix miss match header with MySQL SHOW statement

### CODE REVIEW

**Comment by zhang2014** [comment]
CC: @tavplubix

**Comment by zhang2014** [comment]
Integration tests (release) — fail: 11, passed: 937, error: 2 - unrelated
Integration tests (thread) — fail: 1, passed: 943, error: 0 - unrelated
Performance — 4 errors, 4 too long, 3 faster, 65 unstable - unrelated

File: src/Formats/MySQLBlockInputStream.cpp [hunk 1]
```diff
@@ -132,27 +135,69 @@ Block MySQLBlockInputStream::readImpl()
     for (const auto i : ext::range(0, columns.size()))
         columns[i] = description.sample_block.getByPosition(i).column->cloneEmpty();
 
+    if (unlikely(position_mapping.size() != description.sample_block.columns()))
```
Comment (tavplubix) [inline src/Formats/MySQLBlockInputStream.cpp:138]:
```suggestion
    if (unlikely(position_mapping.empty()))
```

Comment (tavplubix) [reply src/Formats/MySQLBlockInputStream.cpp:138]: Btw, can we initialize `position_mapping` in constructor? And what will happen if query has returned 0 rows? Seems like we will not check block structure in this case.

Comment (zhang2014) [reply src/Formats/MySQLBlockInputStream.cpp]: > Btw, can we initialize position_mapping in constructor? 

Done.

> And what will happen if query has returned 0 rows? Seems like we will not check block structure in this case.

return Block{} if query result structure is matched. Otherwise,  throw Exception.

**Review by tavplubix — APPROVED** [review]
