### PR TITLE
Fix use-after-free in AST fuzzer when replacing predicates

### LINKED ISSUE #99194: Fuzzer crash
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=99102&sha=57fa55634d0e6f5dd12df00ba0d477c1d67174e8&name_0=PR&name_1=AST%20fuzzer%20%28amd_ubsan%29

The fuzzer itself crashed, not the server

### How to reproduce

_No response_

### Error message and/or stacktrace

```
########## Short fault info ############
(version 26.3.1.536, build id: 1046323859999EA7EB40B92E16174EBBB86780A0, git hash: 9eb247b53d37190d5a32d2ffe350343008b8ea89, architecture: x86_64) (from thread 2102) Received signal 11 (signal sent by pid 104 from user 0)
Signal description: Segmentation fault
Address: 0x68. Access: read. Address not mapped to object.
Stack trace: 0x0000560a3a5434b0 0x0000560a4b078967 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b03ed01 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b066808 0x0000560a3a5434b2 0x0000560a4b06e91c 0x0000560a4b061cfa 0x0000560a3a5434b2 0x0000560a4b078967 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b0859a3 0x0000560a3a5434b2 0x0000560a4b086fc2 0x0000560a3a5434b2 0x0000560a4b087347 0x0000560a3a5434b2 0x0000560a4b0664e8 0x0000560a3a5434b2 0x0000560a4b06e91c 0x0000560a4b061cfa 0x0000560a3a5434b2 0x0000560a4b078967 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b0859a3 0x0000560a3a5434b2 0x0000560a4b086fc2 0x0000560a3a5434b2 0x0000560a4b087347 0x0000560a3a5434b2 0x0000560a4b0664e8 0x0000560a3a5434b2 0x0000560a4b06e91c 0x0000560a4b061cfa 0x0000560a32777bb6 0x0000560a4b0e5c3d 0x0000560a4b0e5e22
########################################
(version 26.3.1.536, build id: 1046323859999EA7EB40B92E16174EBBB86780A0, git hash: 9eb247b53d37190d5a32d2ffe350343008b8ea89) (from thread 2102) (no query) Received signal Segmentation fault (11)
Address: 0x68. Access: read. Address not mapped to object.
Stack trace: 0x0000560a3a5434b0 0x0000560a4b078967 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b03ed01 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b066808 0x0000560a3a5434b2 0x0000560a4b06e91c 0x0000560a4b061cfa 0x0000560a3a5434b2 0x0000560a4b078967 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b0859a3 0x0000560a3a5434b2 0x0000560a4b086fc2 0x0000560a3a5434b2 0x0000560a4b087347 0x0000560a3a5434b2 0x0000560a4b0664e8 0x0000560a3a5434b2 0x0000560a4b06e91c 0x0000560a4b061cfa 0x0000560a3a5434b2 0x0000560a4b078967 0x0000560a4b096bbd 0x0000560a3a5434b2 0x0000560a4b0859a3 0x0000560a3a5434b2 0x0000560a4b086fc2 0x0000560a3a5434b2 0x0000560a4b087347 0x0000560a3a5434b2 0x0000560a4b0664e8 0x0000560a3a5434b2 0x0000560a4b06e91c 0x0000560a4b061cfa 0x0000560a32777bb6 0x0000560a4b0e5c3d 0x0000560a4b0e5e22
3. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b0
4. ./ci/tmp/build/./src/Parsers/ASTSubquery.cpp:48:18: DB::ASTSubquery::formatImplWithoutAlias(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcd3967
5. ./ci/tmp/build/./src/Parsers/ASTWithAlias.cpp:38:9: DB::ASTWithAlias::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcf1bbd
6. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
7. ./ci/tmp/build/./src/Parsers/ASTFunction.cpp:804:23: DB::ASTFunction::formatImplWithoutAlias(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fc99d01
8. ./ci/tmp/build/./src/Parsers/ASTWithAlias.cpp:38:9: DB::ASTWithAlias::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcf1bbd
9. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
10. ./ci/tmp/build/./src/Parsers/ASTSelectQuery.cpp:107:21: DB::ASTSelectQuery::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcc1808
11. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
12. ./ci/tmp/build/./src/Parsers/ASTSelectWithUnionQuery.cpp:122:20: DB::ASTSelectWithUnionQuery::formatQueryImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcc991c
13. ./ci/tmp/build/./src/Parsers/ASTQueryWithOutput.cpp:40:5: DB::ASTQueryWithOutput::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcbccfa
14. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
15. ./ci/tmp/build/./src/Parsers/ASTSubquery.cpp:48:18: DB::ASTSubquery::formatImplWithoutAlias(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcd3967
16. ./ci/tmp/build/./src/Parsers/ASTWithAlias.cpp:38:9: DB::ASTWithAlias::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcf1bbd
17. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
18. ./ci/tmp/build/./src/Parsers/ASTTablesInSelectQuery.cpp:130:19: DB::ASTTableExpression::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fce09a3
19. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
20. ./ci/tmp/build/./src/Parsers/ASTTablesInSelectQuery.cpp:305:27: DB::ASTTablesInSelectQueryElement::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fce1fc2
21. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
22. ./ci/tmp/build/./src/Parsers/ASTTablesInSelectQuery.cpp:320:16: DB::ASTTablesInSelectQuery::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fce2347
23. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
24. ./ci/tmp/build/./src/Parsers/ASTSelectQuery.cpp:89:19: DB::ASTSelectQuery::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcc14e8
25. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
26. ./ci/tmp/build/./src/Parsers/ASTSelectWithUnionQuery.cpp:122:20: DB::ASTSelectWithUnionQuery::formatQueryImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcc991c
27. ./ci/tmp/build/./src/Parsers/ASTQueryWithOutput.cpp:40:5: DB::ASTQueryWithOutput::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcbccfa
28. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
29. ./ci/tmp/build/./src/Parsers/ASTSubquery.cpp:48:18: DB::ASTSubquery::formatImplWithoutAlias(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcd3967
30. ./ci/tmp/build/./src/Parsers/ASTWithAlias.cpp:38:9: DB::ASTWithAlias::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcf1bbd
31. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
32. ./ci/tmp/build/./src/Parsers/ASTTablesInSelectQuery.cpp:130:19: DB::ASTTableExpression::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fce09a3
33. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
34. ./ci/tmp/build/./src/Parsers/ASTTablesInSelectQuery.cpp:305:27: DB::ASTTablesInSelectQueryElement::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fce1fc2
35. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
36. ./ci/tmp/build/./src/Parsers/ASTTablesInSelectQuery.cpp:320:16: DB::ASTTablesInSelectQuery::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fce2347
37. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
38. ./ci/tmp/build/./src/Parsers/ASTSelectQuery.cpp:89:19: DB::ASTSelectQuery::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcc14e8
39. ./src/Parsers/IAST.h:322:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000001f19e4b2
40. ./ci/tmp/build/./src/Parsers/ASTSelectWithUnionQuery.cpp:122:20: DB::ASTSelectWithUnionQuery::formatQueryImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcc991c
41. ./ci/tmp/build/./src/Parsers/ASTQueryWithOutput.cpp:40:5: DB::ASTQueryWithOutput::formatImpl(DB::WriteBuffer&, DB::IAST::FormatSettings const&, DB::IASTFormatState&, DB::IAST::FormatStateStacked) const @ 0x000000002fcbccfa
42. ./src/Parsers/IAST.h:317:9: DB::IAST::format(DB::WriteBuffer&, DB::IAST::FormatSettings const&) const @ 0x00000000173d2bb6
43. ./ci/tmp/build/./src/Parsers/IAST.cpp:203:5: DB::IAST::formatWithPossiblyHidingSensitiveData(unsigned long, bool, bool, bool, DB::IdentifierQuotingRule, DB::IdentifierQuotingStyle) const @ 0x000000002fd40c3d
44. ./ci/tmp/build/./src/Parsers/IAST.cpp:231:12: DB::IAST::formatWithSecretsOneLine() const @ 0x000000002fd40e22
timeout: the monitored command dumped core
```

### PR DESCRIPTION
**Pull request by Algunenano**
## Summary

- Fix segfault in AST fuzzer caused by use-after-free when `addOrReplacePredicate` reuses a predicate node whose `children` were just cleared
- Remove 4 unnecessary `children.clear()` calls before `addOrReplacePredicate` for HAVING, WHERE, PREWHERE, and QUALIFY clauses
- Bug was introduced in d866dfd88df ("Fuzz predicates and remove unused functions") and 2a92ae8d8e1 ("Fuzz PREWHERE clause")

## Details

`addOrReplacePredicate` may combine the old predicate with a new one via `makeASTFunction("and", new_pred, old_pred)`. The `children.clear()` on the line before empties the old node's internal children, so when the combined expression is later formatted, `ASTSubquery::formatImplWithoutAlias` accesses `children[0]` on the gutted subquery — reading freed memory (dangling pointer with zeroed vtable → segfault at address 0x68).

CI report: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=99102&sha=57fa55634d0e6f5dd12df00ba0d477c1d67174e8&name_0=PR&name_1=AST%20fuzzer%20%28amd_ubsan%29
https://github.com/ClickHouse/ClickHouse/pull/99102

cc @PedroTadim

Closes #99194

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

---

> [!NOTE]
> **Low Risk**
> Low risk, localized to AST fuzzer logic; it only changes how `HAVING`/`WHERE`/`PREWHERE`/`QUALIFY` predicates are mutated to prevent use-after-free/segfaults during formatting.
> 
> **Overview**
> Prevents a fuzzer crash by **stopping `HAVING`/`WHERE`/`PREWHERE`/`QUALIFY` predicate nodes from having `children` cleared immediately before `addOrReplacePredicate` potentially reuses them** (e.g., by combining old/new predicates).
> 
> This removes four `children.clear()` calls so predicate replacement/augmentation operates on intact AST nodes, avoiding use-after-free during later AST formatting.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0c1246e860ff59a77aafe557fe1e147ea15e56fa. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.578`

### CODE REVIEW

File: src/Common/QueryFuzzer.cpp [hunk 1]
```diff
@@ -2517,8 +2517,6 @@ void QueryFuzzer::fuzz(ASTPtr & ast)
             {
                 if (fuzz_rand() % 50 == 0)
                 {
-                    select->having()->children.clear();
```
Comment (PedroTadim) [inline src/Common/QueryFuzzer.cpp:2662]: This was already before the changes last week, so it can't be this.

Comment (Algunenano) [reply src/Common/QueryFuzzer.cpp:2662]: I don't  think the crash is related to the changes last week. It looks like it's related to changes from a long time ago but we either didn't notice it or we have very good luck not hitting it.
                                                                                                                                           
1. The crash is in formatting the PREWHERE clause of an ASTSelectQuery                                                                   
2. The PREWHERE expression is an ASTFunction with name = "and" (frame 4) — exactly what addOrReplacePredicate creates viamakeASTFunction("and", new_pred, old_pred)                                                                                               
3. One of the children of this "and" function is an ASTSubquery (frame 2) with children.size() = 0 (the cleared vector) 
4. Accessing children[0] in ASTSubquery::formatImplWithoutAlias reads a stale pointer from the freed buffer → SIGSEGV
  The full call chain from the coredump:
  - fuzzMain calls ast->formatWithSecretsOneLine()
  - → ASTSelectQuery::formatImpl at line 107: prewhere()->format(...)
  - → ASTFunction("and")::formatImpl — the "and" node created by addOrReplacePredicate
  - → ASTSubquery::formatImplWithoutAlias at line 48: children[0]->format(...) — boom, children was cleared

This matches exactly the code path in QueryFuzzer.cpp where:
```
  select->prewhere()->children.clear();  // ← clears ASTSubquery's children
  addOrReplacePredicate(select, ASTSelectQuery::Expression::PREWHERE);  // ← reuses old_pred containing the now-broken ASTSubquery
```

Since AST is random I don't know if it's possible to know exactly which transformations happened, I only see the current AST with the invalid pointers.

Comment (PedroTadim) [reply src/Common/QueryFuzzer.cpp:2662]: Ok, I trust you

**Review by PedroTadim — APPROVED** [review]
