### PR TITLE
Dynamic update s3 access tokens in long queries

### LINKED ISSUE #93981: Issue with vended credentials for long running queries
### Company or project name

_No response_

### Describe the unexpected behaviour

When ClickHouse is running long-running queries to an Iceberg or Delta lake via a catalog, if the query duration is longer than the duration of the token it seems than ClickHouse do no refresh the token and then the query fail after 30-45 minutes. 

### Which ClickHouse versions are affected?

Latest

### How to reproduce

Running a long running query using a catalog with vended credentials. 

### Expected behavior

ClickHouse should refresh the token in case of expired token. 

### Error message and/or stacktrace

You can see various authorization issues in the traces of a long-running query: https://pastila.nl/?00026435/1b0a7dda2303e71996a6476f039593f4#Yoc2O394I3H28WDl45iEWQ==GCM

### Additional context

This is pretty impactful for our workload especially for people wanting to load data from a data lake to ClickHouse

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Dynamic update s3 access tokens in long queries with unity catalog. This closes https://github.com/ClickHouse/ClickHouse/issues/93981

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.2.1.487`

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
How would you test?

**Comment by scanhex12** [comment]
Seems like it works:

```
WITH 8 AS k
SELECT
    sum((l1.l_extendedprice * l2.l_extendedprice) * (1 + abs(l1.r - l2.r))) AS s,
    count() AS pairs
FROM
(
    SELECT
        l_partkey,
        l_suppkey,
        l_orderkey,
        l_extendedprice,
        arrayJoin(range(k)) AS r
    FROM unity_demo2.`tpch.lineitem`
) AS l1
CROSS JOIN
(
    SELECT
        l_partkey,
        l_suppkey,
        l_orderkey,
        l_extendedprice,
        arrayJoin(range(k)) AS r
    FROM unity_demo2.`tpch.lineitem`
) AS l2
WHERE (l1.l_partkey = l2.l_partkey) AND ((l1.l_suppkey, l1.r) != (l2.l_suppkey, l2.r)) AND ((l1.l_orderkey, l1.r) != (l2.l_orderkey, l2.r))
SETTINGS max_threads = 1, max_bytes_before_external_group_by = 1000000., max_bytes_before_external_sort = 1000000.

Query id: 159757e4-9d5a-4a82-a1bd-148ca1ff5981

   ┌──────────────────────────s─┬───────pairs─┐
1. │ 327643947294768618350.6448 │ 57452701912 │ -- 57.45 billion
   └────────────────────────────┴─────────────┘

1 row in set. Elapsed: 3340.520 sec. Processed 60.00 million rows, 1.51 GB (17.96 thousand rows/s., 451.20 KB/s.)

```

On the master branch this query crashed:

```
WITH 8 AS k
SELECT
    sum((l1.l_extendedprice * l2.l_extendedprice) * (1 + abs(l1.r - l2.r))) AS s,
    count() AS pairs
FROM
(
    SELECT
        l_partkey,
        l_suppkey,
        l_orderkey,
        l_extendedprice,
        arrayJoin(range(k)) AS r
    FROM unity_demo2.`tpch.lineitem`
) AS l1
CROSS JOIN
(
    SELECT
        l_partkey,
        l_suppkey,
        l_orderkey,
        l_extendedprice,
        arrayJoin(range(k)) AS r
    FROM unity_demo2.`tpch.lineitem`
) AS l2
WHERE (l1.l_partkey = l2.l_partkey) AND ((l1.l_suppkey, l1.r) != (l2.l_suppkey, l2.r)) AND ((l1.l_orderkey, l1.r) != (l2.l_orderkey, l2.r))
SETTINGS max_threads = 1, max_bytes_before_external_group_by = 1000000., max_bytes_before_external_sort = 1000000.

Query id: 6e0b7ef4-575a-4149-ad10-8979994edd42


Elapsed: 2043.466 sec. Processed 35.58 million rows, 893.99 MB (17.41 thousand rows/s., 437.49 KB/s.)

Received exception from server (version 26.1.1):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: Unable to parse ExceptionName: ExpiredToken Message: The provided token has expired: (in file/uri databricks-workspace-stack-423f3-bucket/unity-catalog/3991137281740682/__unitystorage/catalogs/c78a8ed1-f901-4f90-ae0c-22fb31116b9a/tables/033bad64-5343-4fd9-9f2a-d4fb791020cc/JT/part-00002-f50861b0-175a-4631-9f0e-38d76664b84f.c000.zstd.parquet): While executing ParquetV3BlockInputFormat: While executing ReadFromObjectStorage. (S3_ERROR)

```

File: src/Disks/DiskObjectStorage/ObjectStorages/S3/diskSettings.cpp [hunk 1]
```diff
@@ -198,16 +202,29 @@ getClient(const S3::URI & url, const S3Settings & settings, ContextPtr context,
         /*sts_endpoint_override=*/""
     };
 
+    String access_key_id = auth_settings[S3AuthSetting::access_key_id];
+    String secret_access_key = auth_settings[S3AuthSetting::secret_access_key];
+    String session_token = auth_settings[S3AuthSetting::session_token];
+
+    auto updated_credentials = refresh_credentials_callback();
```
Comment (divanik) [inline src/Disks/DiskObjectStorage/ObjectStorages/S3/diskSettings.cpp]: Needs assertion that refresh_credentials_callback is not nullptr (std::function can be nullpt)

File: src/Databases/DataLake/RestCatalog.cpp [hunk 2]
```diff
@@ -957,6 +960,56 @@ void RestCatalog::dropTable(const String & namespace_name, const String & table_
...
+        std::string session_token;
+        std::string storage_endpoint;
+        if (config_object->has(access_key_id_str))
+            access_key_id = config_object->get(access_key_id_str).extract<String>();
+        if (config_object->has(secret_access_key_str))
+            secret_access_key = config_object->get(secret_access_key_str).extract<String>();
+        if (config_object->has(session_token_str))
+            session_token = config_object->get(session_token_str).extract<String>();
+        if (config_object->has(storage_endpoint_str))
+            storage_endpoint = config_object->get(storage_endpoint_str).extract<String>();
```
Comment (divanik) [inline src/Databases/DataLake/RestCatalog.cpp]: Move to a separate function (can return pair<shared_ptr<S3Credentials>, string>)

File: src/Databases/DataLake/RestCatalog.cpp [hunk 3]
```diff
@@ -957,6 +960,56 @@ void RestCatalog::dropTable(const String & namespace_name, const String & table_
...
+
+        if (buf->eof())
+        {
+            LOG_DEBUG(log, "Table doesn't exist (endpoint: {})", endpoint);
+            return nullptr;
+        }
+
+        String json_str;
+        readJSONObjectPossiblyInvalid(json_str, *buf);
+        LOG_DEBUG(log, "Receiving table metadata {} {}", table_name, json_str);
```
Comment (divanik) [inline src/Databases/DataLake/RestCatalog.cpp:990]: Move to a function and reuse (as much as possible)

File: src/Disks/DiskObjectStorage/ObjectStorages/S3/diskSettings.cpp [hunk 4]
```diff
@@ -198,16 +202,29 @@ getClient(const S3::URI & url, const S3Settings & settings, ContextPtr context,
...
+    if (updated_credentials)
+    {
+        auto s3_updated_credentials = std::static_pointer_cast<DataLake::S3Credentials>(updated_credentials);
```
Comment (divanik) [inline src/Disks/DiskObjectStorage/ObjectStorages/S3/diskSettings.cpp]: Let's use dynamic_cast and assert it it not null (not a performance critical place)

File: src/IO/ReadBufferFromS3.h [hunk 5]
```diff
@@ -109,6 +113,8 @@ class ReadBufferFromS3 : public ReadBufferFromFileBase
     bool restricted_seek;
 
     bool read_all_range_successfully = false;
+
+    const S3CredentialsRefreshCallback credentials_refresh_callback;
```
Comment (divanik) [inline src/IO/ReadBufferFromS3.h:117]: Let's rename to client refresh callback (I think it makes code more readable)

File: src/Storages/ObjectStorage/StorageObjectStorageSource.cpp [hunk 6]
```diff
@@ -713,6 +720,7 @@ std::future<StorageObjectStorageSource::ReaderHolder> StorageObjectStorageSource
 }
 
 std::unique_ptr<ReadBufferFromFileBase> createReadBuffer(
+    const StorageID & /*storage_id*/,
```
Comment (divanik) [inline src/Storages/ObjectStorage/StorageObjectStorageSource.cpp]: What it is needed for here?

Comment (divanik) [reply src/Storages/ObjectStorage/StorageObjectStorageSource.cpp]: I ask because there is a lot of changes to deliver it here, but here it is not used, that seems strange

Comment (scanhex12) [reply src/Storages/ObjectStorage/StorageObjectStorageSource.cpp]: It's actually useless

File: src/Storages/ObjectStorage/ReadBufferIterator.cpp [hunk 7]
```diff
@@ -6,6 +6,7 @@
 #include <Storages/ObjectStorage/StorageObjectStorage.h>
 #include <Storages/ObjectStorage/StorageObjectStorageSource.h>
 #include <Storages/ObjectStorage/Utils.h>
+#include <Interpreters/StorageID.h>
```
Comment (divanik) [inline src/Storages/ObjectStorage/ReadBufferIterator.cpp]: Remove

File: src/Storages/ObjectStorage/IObjectIterator.cpp [hunk 8]
```diff
@@ -9,6 +9,7 @@
 #include <Core/Defines.h>
 #include <Storages/ObjectStorage/Utils.h>
 #include <Processors/Formats/IInputFormat.h>
+#include <Interpreters/StorageID.h>
```
Comment (divanik) [inline src/Storages/ObjectStorage/IObjectIterator.cpp]: Here as well

File: src/Storages/ObjectStorage/S3/Configuration.cpp [hunk 9]
```diff
@@ -165,14 +165,21 @@ ObjectStoragePtr StorageS3Configuration::createObjectStorage(ContextPtr context,
     }
 
     auto client = getClient(url, *s3_settings, context, /* for_disk_s3 */false);
+    auto client_refresher = [refresh_credentials_callback, this, context] (const DB::StorageID & sid)
```
Comment (divanik) [inline src/Storages/ObjectStorage/S3/Configuration.cpp]: Can we add storage_id to the function itself? If you don't have places in the code where storage_id is got later than callback, I guess you can (and this will simplify the code a lot)

Comment (scanhex12) [reply src/Storages/ObjectStorage/S3/Configuration.cpp]: no, because catalog doesn't know which `storage` is processing at the query execution moment

**Comment by divanik** [comment]
Sorry, confused PRs

**Review by divanik — APPROVED** [review]
