### PR TITLE
Reintroduce nonNegativeDerivative()

### LINKED ISSUE #38532: nonNegativeDerivative window function fails with LOGICAL_ERROR
**Describe the unexpected behaviour**
New `nonNegativeDerivative` window function fails with LOGICAL_ERROR.

**How to reproduce**

```
root@clickhouse1:/# clickhouse client
ClickHouse client version 22.6.1.1985 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.6.1 revision 54455.

clickhouse1 :) Bye.
root@clickhouse1:/# echo -e "SELECT id, metric, ts, nonNegativeDerivative(metric, ts) OVER (ORDER BY id ASC) AS nnd FROM values('id Int8, metric Float32, ts DateTime64(0)', (1,1,'2022-12-12 00:00:00'), (2,2,'2022-12-12 00:00:01'),(3,3,'2022-12-12 00:00:02')) FORMAT TabSeparatedWithNames" | clickhouse client -n 2>&1
Received exception from server (version 22.6.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Invalid number of rows in Chunk column Float32 position 3: expected 3, got 6. (LOGICAL_ERROR)
(query: SELECT id, metric, ts, nonNegativeDerivative(metric, ts) OVER (ORDER BY id ASC) AS nnd FROM values('id Int8, metric Float32, ts DateTime64(0)', (1,1,'2022-12-12 00:00:00'), (2,2,'2022-12-12 00:00:01'),(3,3,'2022-12-12 00:00:02')) FORMAT TabSeparatedWithNames
)
root@clickhouse1:/# 
```

**Which ClickHouse server version to use**
22.6.1.1985 (official build).

**Error message and/or stacktrace**
```
2022.06.28 15:45:36.627221 [ 9 ] {5552a5a1-7727-4ee2-a7ad-f06064384257} <Error> TCPHandler: Code: 49. DB::Exception: Invalid number of rows in Chunk column Float32 position 3: expected 3, got 6. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a147a in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x1718194e in /usr/bin/clickhouse
2. DB::WindowTransform::prepare() @ 0x173d497f in /usr/bin/clickhouse
3. DB::ExecutingGraph::updateNode(unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&) @ 0x171a9b59 in /usr/bin/clickhouse
4. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x171a440b in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x171a3921 in /usr/bin/clickhouse
6. DB::PipelineExecutor::execute(unsigned long) @ 0x171a36b8 in /usr/bin/clickhouse
7. ? @ 0x171b38ce in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb94d0b7 in /usr/bin/clickhouse
9. ? @ 0xb9504dd in /usr/bin/clickhouse
10. ? @ 0x7f7cd5e02609 in ?
11. clone @ 0x7f7cd5d29293 in ?
```

### PR DESCRIPTION
**Pull request by zvonand**
Reintroduced `nonNegativeDerivative` window function (previously added in #37628 and reverted in #38551)  
Fixes #38532, updated precision when working with DateTime64 up to Nanoseconds

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by zvonand** [comment]
@rschu1ze can you put `can-be-tested` as soon as you revieved the old version :)

File: src/Processors/Transforms/WindowTransform.cpp [hunk 1]
```diff
@@ -2247,6 +2248,12 @@ struct WindowFunctionNonNegativeDerivative final : public StatefulWindowFunction
                             argument_types[ARGUMENT_TIMESTAMP]->getName());
         }
 
+        if (typeid_cast<const DataTypeDateTime64 *>(argument_types[ARGUMENT_TIMESTAMP].get()))
```
Comment (rschu1ze) [inline src/Processors/Transforms/WindowTransform.cpp:2251]: Could use if initializer:

```
if (const auto * arg_timestamp_dt64 = typeid_cast<const DataTypeDateTime64 *>(argument_types[ARGUMENT_TIMESTAMP]; arg_timestamp_dt64 != nullptr)
{
    ts_scale_multiplier = DecimalUtils::scaleMultiplier<DateTime64>(arg_timestamp_dt64->getScale());
}
```

File: src/Processors/Transforms/WindowTransform.cpp [hunk 2]
```diff
@@ -2247,6 +2248,12 @@ struct WindowFunctionNonNegativeDerivative final : public StatefulWindowFunction
...
+        {
+            const auto & datetime64_type = assert_cast<const DataTypeDateTime64 &>(*argument_types[ARGUMENT_TIMESTAMP]);
+            ts_scale_multiplier = DecimalUtils::scaleMultiplier<DateTime64>(datetime64_type.getScale());
```
Comment (rschu1ze) [inline src/Processors/Transforms/WindowTransform.cpp:2254]: Just wondering, if ts_scale_multiplier is set here to 0, we end up in the if branch starting in l. 2308. Is that expected?

File: src/Processors/Transforms/WindowTransform.cpp [hunk 3]
```diff
@@ -2200,6 +2203,128 @@ struct WindowFunctionNthValue final : public WindowFunction
...
+        Float64 result;
+
+        if (ts_scale_multiplier)
+        {
+            const auto & column = transform->blockAt(transform->current_row.block).input_columns[workspace.argument_column_indices[ARGUMENT_TIMESTAMP]];
+            const auto & curr_timestamp = checkAndGetColumn<DataTypeDateTime64::ColumnType>(column.get())->getInt(transform->current_row.row);
+
+            Float64 time_elapsed = curr_timestamp - state.previous_timestamp;
+            result = (time_elapsed > 0) ? (metric_diff * ts_scale_multiplier / time_elapsed  * interval_duration) : 0;
+            state.previous_timestamp = curr_timestamp;
```
Comment (rschu1ze) [inline src/Processors/Transforms/WindowTransform.cpp:2306]: Could pull l. 2306 / 2313 out, similar to l. 2315.

File: src/Processors/Transforms/WindowTransform.cpp (hunk 2 above)
Comment (zvonand) [reply src/Processors/Transforms/WindowTransform.cpp:2254]: yes, than the scale as 0 and we can simply treat the value as `Float64`, and no rounding error will occur -- the timestamp is a whole number then

File: src/Processors/Transforms/WindowTransform.cpp (hunk 3 above)
Comment (zvonand) [reply src/Processors/Transforms/WindowTransform.cpp:2306]: No, we cannot -- `curr_timestamp` is initialized differently in the branches

File: src/Common/IntervalKind.cpp [hunk 4]
```diff
@@ -9,13 +9,13 @@ namespace ErrorCodes
...
 {
     switch (kind)
     {
-        case IntervalKind::Nanosecond:
-        case IntervalKind::Microsecond:
-        case IntervalKind::Millisecond: return 0; /// fractional parts of seconds have 0 seconds
+        case IntervalKind::Nanosecond: return 0.000000001;
+        case IntervalKind::Microsecond: return 0.000001;
+        case IntervalKind::Millisecond: return 0.001;
         case IntervalKind::Second: return 1;
```
Comment (qoega) [inline src/Common/IntervalKind.cpp:19]: Can you implement your logic without converting it to float? It will introduce floating point errors where we had accuracy before.

Comment (rschu1ze) [reply src/Common/IntervalKind.cpp:19]: The original PR had the same discussion :-)
https://github.com/ClickHouse/ClickHouse/pull/37628/files#r886792381

**Comment by rschu1ze** [comment]
There were some test failures ... restarted tests.

File: src/Common/IntervalKind.cpp [hunk 5]
```diff
@@ -15,7 +16,7 @@ Int32 IntervalKind::toAvgSeconds() const
     {
         case IntervalKind::Nanosecond:
         case IntervalKind::Microsecond:
-        case IntervalKind::Millisecond: return 0; /// fractional parts of seconds have 0 seconds
+        case IntervalKind::Millisecond: return 0;
```
Comment (rschu1ze) [inline src/Common/IntervalKind.cpp:19]: (nit: return type of toAvgSeconds could have been unsigned but that's okay)

File: src/Common/IntervalKind.h [hunk 6]
```diff
@@ -33,10 +33,17 @@ struct IntervalKind
     /// For `Month`, `Quarter` and `Year` the function returns an average number of seconds.
     Int32 toAvgSeconds() const;
 
+    /// Returns exact number of seconds in one interval.
```
Comment (rschu1ze) [inline src/Common/IntervalKind.h:36]: (nit: could have listed the "base case" (toSeconds) before the "advanced case" (toAvgSeconds))

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Hm, the flaky tests failed which is strange given that the function works deterministically.
Perhaps merge from master once more and if the tests are green then, I'll happily submit?

File: src/Common/IntervalKind.cpp (hunk 5 above)
Comment (zvonand) [reply src/Common/IntervalKind.cpp:19]: I wasn't the one who introduced this so left it as is

**Comment by rschu1ze** [comment]
Stress test failures are unrelated. The stateless tests flaky check sometimes fails for the first query

```
SELECT (
           SELECT
               ts,
               metric,
               nonNegativeDerivative(metric, ts) OVER (PARTITION BY metric ORDER BY ts ASC Rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS deriv
           FROM nnd
           LIMIT 5, 1
       ) = (
           SELECT
               ts,
               metric,
               nonNegativeDerivative(metric, ts, toIntervalSecond(1)) OVER (PARTITION BY metric ORDER BY ts ASC Rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS deriv
           FROM nnd
           LIMIT 5, 1
       );
```

which is quite strange given that the query is deterministic. Do you have an idea what could be wrong?

**Comment by zvonand** [comment]
> Do you have an idea what could be wrong?

The only thong I came up with is maybe I shall first `OPTIMIZE TABLE` ?

**Comment by rschu1ze** [comment]
Yes, that could make sense.

File: src/Common/IntervalKind.cpp (hunk 4 above)
Comment (rschu1ze) [reply src/Common/IntervalKind.cpp]: The code changed in the meantime. The only Interval method which returns a Float is `toSeconds`. Its only user is the new nonNegativeDerive() SQL function which is okay with Floats.

The other Interval method `toAvgSeconds` still returns int. But even if it would return floats, its callers would not care at all because they just use the value to compare against some threshold or for logging.

The general problem is that sub-second durations cannot be expressed with integers. We would have to base the method on the smallest unit (nanoseconds). Which means (for example) a month will have 2629746000000000 nanoseconds. Quite unnatural, imho. So this will always be some sort of compromise.
