### PR TITLE
clickhouse-client: Force that `--password` is specified at most once

### LINKED ISSUE #50459: Specifying --password "secret" --password in client asks user to enter password
ClickHouse client version 23.5.1.1

**Describe the unexpected behavior.**
Specifying `--password "secret" --password` asks the user to enter the password instead of failing in the console output.

**Repro**
`clickhouse-client --password "secret" --password`

**Expected behavior**
An error: `Bad arguments: option '--password' cannot be specified more than once`

**Error message and/or stacktrace**
No error message. The client just ignores the "secret" password, and uses implicit_value "" from the boost options configuration.
If the password is an empty string, then the client asks the user to enter the password (even if the user does not have a password).

### PR DESCRIPTION
**Pull request by Demilivor**
Closes #50459

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Command line parameter "--password" in clickhouse-client can now be specified only once.

### CODE REVIEW

**Comment by Demilivor** [comment]
Hello @rschu1ze please be reviewer of this pull request and add a label 'can be tested'.

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit 1f76d0874398f4985bb00dd16caf68a772c95502 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/50966/1f76d0874398f4985bb00dd16caf68a772c95502/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: programs/client/Client.cpp [hunk 1]
```diff
@@ -1391,6 +1385,12 @@ void Client::readArguments(
                 arg = argv[arg_num];
                 addMultiquery(arg, common_arguments);
             }
+            else if (arg == "--password" && ((arg_num + 1) >= argc || std::string_view(argv[arg_num + 1]).starts_with('-')))
+            {
+                common_arguments.emplace_back(arg);
+                // Add implicit value to the password. '\n' means client should ask user for password.
```
Comment (rschu1ze) [inline programs/client/Client.cpp:1391]: `/// No password provided by user. Add '\n' as implicit password which encodes that client should ask user for the password. '\n' is used because there is hardly a chance that a user would use '\n' as password.

**Review by rschu1ze — APPROVED** [review]
Lgtm, just a minor comment.

File: programs/client/Client.cpp (hunk 1 above)
Comment (Demilivor) [reply programs/client/Client.cpp]: Done!
