### PR TITLE
Fix toWeek monotonicity

### LINKED ISSUE #24422: Date range filter doesn't work for table partitioned by toWeek
(you don't have to strictly follow this form)

**Describe the issue**
Date filter not working when table is partitioned by week. 

**How to reproduce**
* Which ClickHouse server versions are incompatible 21.4.6
* Table definition - 
CREATE TABLE returns.test_tbl
(
    `vend_nm` String,
    `ship_dt` Date
)
ENGINE = MergeTree
PARTITION BY toWeek(ship_dt)
ORDER BY vend_nm
SETTINGS index_granularity = 8192

Sample Data - 
insert into returns.test_tbl values('1', '2020-11-11')('1', '2021-01-01');

* Queries to run that lead to unexpected result
1.  select * From test_tbl where ship_dt>= toDate('2020-11-01') and ship_dt <= toDate('2021-05-05');
    This query returns no result. 
2. select * From test_tbl where ship_dt>= toDate('2020-01-01') and ship_dt <= toDate('2021-05-05');
    This query returns 1 record for date -  2021-01-01

This was working fine with version 20.5.3

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix incorrect monotonicity of toWeek function. This fixes  https://github.com/ClickHouse/ClickHouse/issues/24422 . This bug was introduced in https://github.com/ClickHouse/ClickHouse/pull/5212 , and was exposed later by smarter partition pruner.

Detailed description / Documentation draft:

.

### CODE REVIEW

File: src/Functions/CustomWeekTransforms.h [hunk 1]
```diff
@@ -106,8 +94,6 @@ struct ToStartOfWeekImpl
     {
         return time_zone.toFirstDayNumOfWeek(ExtendedDayNum(d), week_mode);
     }
-
-    using FactorTransform = ZeroTransform;
```
Comment (CurtizJ) [inline src/Functions/CustomWeekTransforms.h:110]: But function `toStartOfWeek` is always monotonic and it's better to keep this behaviour.

File: src/Functions/FunctionCustomWeekToSomething.h [hunk 2]
```diff
@@ -143,15 +137,15 @@ class FunctionCustomWeekToSomething : public IFunction
 
         if (checkAndGetDataType<DataTypeDate>(&type))
         {
-            return Transform::FactorTransform::execute(UInt16(left.get<UInt64>()), DEFAULT_WEEK_MODE, date_lut)
-                    == Transform::FactorTransform::execute(UInt16(right.get<UInt64>()), DEFAULT_WEEK_MODE, date_lut)
+            return Transform::execute(UInt16(left.get<UInt64>()), DEFAULT_WEEK_MODE, date_lut)
+                    == Transform::execute(UInt16(right.get<UInt64>()), DEFAULT_WEEK_MODE, date_lut)
```
Comment (CurtizJ) [inline src/Functions/FunctionCustomWeekToSomething.h:141]: This looks wrong, because, it will erroneously return true for ranges, that start at the same week, but last more than year and will return false for ranges, that last less than one year, but start at different weeks. I think, it's better to use `ToStartOfYearImpl` as `FactorTransform` for `toWeek` like it is done, e.g. for function `toMonth` in `DateTimeTransforms.h`.

File: src/Functions/CustomWeekTransforms.h (hunk 1 above)
Comment (CurtizJ) [reply src/Functions/CustomWeekTransforms.h:110]: The same about `toYearWeek`.

File: src/Functions/FunctionCustomWeekToSomething.h (hunk 2 above)
Comment (amosbird) [reply src/Functions/FunctionCustomWeekToSomething.h:141]: Yeah. I didn't understand the code style. It should be trivial :) Updated

File: src/Functions/CustomWeekTransforms.h [hunk 3]
```diff
@@ -110,6 +86,30 @@ struct ToStartOfWeekImpl
...
+        YearWeek yw = time_zone.toYearWeek(time_zone.toDayNum(t), week_mode);
+        return yw.second;
+    }
+    static inline UInt8 execute(UInt16 d, UInt8 week_mode, const DateLUTImpl & time_zone)
+    {
+        YearWeek yw = time_zone.toYearWeek(DayNum(d), week_mode);
+        return yw.second;
+    }
+
+    using FactorTransform = ToStartOfWeekImpl;
```
Comment (CurtizJ) [inline src/Functions/CustomWeekTransforms.h:110]: `ToStartOfYearImpl`? We need to check, that two dates belong to the same year.

Comment (amosbird) [reply src/Functions/CustomWeekTransforms.h:110]: but `toStartOfWeek` contains year
```
┌─toStartOfWeek(now())─┐
│           2021-05-23 │
└──────────────────────┘
```

Comment (CurtizJ) [reply src/Functions/CustomWeekTransforms.h:110]: Yes, but `toWeek` in range of one year can be treated as monotonic, but `toStartOfWeek` don't allow this.

Comment (amosbird) [reply src/Functions/CustomWeekTransforms.h:110]: Right.

**Review by CurtizJ — APPROVED** [review]

**Comment by CurtizJ** [comment]
@Mergifyio update

**Comment by CurtizJ** [comment]
No new tests failed.
