### PR TITLE
Make behaviour of remainder of division for floating point numbers compatible with most of DBMS

### LINKED ISSUE #7323: The mod() function only supports integers.
The function `mod(8.5,2.5)` is valid in most databases. It does not work as expected in ClickHouse. In ClickHouse the arguments are truncated to integers.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Backward Incompatible Change

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Function `modulo` (operator `%`) with at least one floating point number as argument will calculate remainder of division directly on floating point numbers without converting both arguments to integers. It makes behaviour compatible with most of DBMS. This also applicable for Date and DateTime data types. Added alias `mod`. This closes #7323

### CODE REVIEW

File: src/Functions/DivisionUtils.h [hunk 1]
```diff
@@ -86,8 +87,15 @@ struct ModuloImpl
     template <typename Result = ResultType>
     static inline Result apply(A a, B b)
     {
-        throwIfDivisionLeadsToFPE(typename NumberTraits::ToInteger<A>::Type(a), typename NumberTraits::ToInteger<B>::Type(b));
-        return typename NumberTraits::ToInteger<A>::Type(a) % typename NumberTraits::ToInteger<B>::Type(b);
+        if constexpr (std::is_floating_point_v<ResultType>)
+        {
+            return ResultType(a) - trunc(ResultType(a) / ResultType(b)) * ResultType(b);
```
Comment (akuzm) [inline src/Functions/DivisionUtils.h:92]: why not `fmod`?

Comment (alexey-milovidov) [reply src/Functions/DivisionUtils.h:92]: I did not aware of this function (what a shame), let's test it...

**Comment by alexey-milovidov** [comment]
BTW, new division is much faster than previous but `fmod` is terrible.

`SELECT count() FROM system.numbers WHERE NOT ignore(number % 1.1)`

master (conversion + integer division): 134.35 million rows/s.
this PR (divide, multiply and subtract):  1.10 billion rows/s., fully inlined vectorized.
this PR (fmod): 23.86 million rows/s., `libm-2.30.so [.] __fmod_finite`

`fmod` is not inlined (in contrast to `trunc` that is compiler intrinsic) and probably it is doing some magic to ensure better precision of the result.

Sometimes ignorance is better :)

**Review by akuzm — APPROVED** [review]
