### PR TITLE
Fix logical error and modulo bug in `ReadFromSystemNumbersStep`

### LINKED ISSUE #83398: Assert `block_size == UInt64(pos - vec.begin())` in `ReadFromSystemNumbersStep`
### Describe the bug

```
ClickHouse local version 25.7.1.1.

:) SELECT DISTINCT number * 1 FROM numbers(10, sipHash64(sipHash64(sipHash64(2), 1), 1, 2, *), sipHash64(sipHash64(29103473, sipHash64(1), '3', sipHash64(1), 1))) GROUP BY 1, isNullable(1) WITH TOTALS

SELECT DISTINCT number * 1
FROM numbers(10, sipHash64(sipHash64(sipHash64(2), 1), 1, 2, *), sipHash64(sipHash64(29103473, sipHash64(1), '3', sipHash64(1), 1)))
GROUP BY
    1,
    isNullable(1)
    WITH TOTALS

Query id: f0f7b38d-b760-4e77-ba1f-a119935e354e

2025.07.07 17:56:53.138798 [ 229979 ] {f0f7b38d-b760-4e77-ba1f-a119935e354e} <Fatal> : Logical error: 'block_size == UInt64(pos - vec.begin())'.
[tpx1] 2025.07.07 17:56:53.138798 [ 229979 ] {f0f7b38d-b760-4e77-ba1f-a119935e354e} <Fatal> : Logical error: 'block_size == UInt64(pos - vec.begin())'.
← Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:55.358423 [ 229979 ] {f0f7b38d-b760-4e77-ba1f-a119935e354e} <Fatal> : Stack trace (when copying this message, always include the lines below):ace key to toggle the display of the progress table.

0. /home/tavplubix/ch/ClickHouse/src/Common/StackTrace.cpp:389: StackTrace::StackTrace() @ 0x0000000012469164
1. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:55: DB::abortOnFailedAssertion(String const&) @ 0x00000000123c1e04
2. /home/tavplubix/ch/ClickHouse/src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp:335: DB::(anonymous namespace)::NumbersRangedSource::generate() @ 0x000000001bd3939b
3. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001b6e59e8
4. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001b6e5666
5. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001b703638
6. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001b6f6b86
7. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:276: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001b6f6fcf
8. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:472: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001b6f7b8d
9. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012515577
10. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000001251bd14
11. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012512803
12. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000012519514
13. ? @ 0x00000000000957eb
14. ? @ 0x000000000011918c

[tpx1] 2025.07.07 17:56:55.358423 [ 229979 ] {f0f7b38d-b760-4e77-ba1f-a119935e354e} <Fatal> : Stack trace (when copying this message, always include the lines below):

0. /home/tavplubix/ch/ClickHouse/src/Common/StackTrace.cpp:389: StackTrace::StackTrace() @ 0x0000000012469164
1. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:55: DB::abortOnFailedAssertion(String const&) @ 0x00000000123c1e04
2. /home/tavplubix/ch/ClickHouse/src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp:335: DB::(anonymous namespace)::NumbersRangedSource::generate() @ 0x000000001bd3939b
3. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001b6e59e8
4. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001b6e5666
5. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001b703638
6. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001b6f6b86
7. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:276: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001b6f6fcf
8. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:472: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001b6f7b8d
9. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012515577
10. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000001251bd14
11. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012512803
12. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000012519514
13. ? @ 0x00000000000957eb
14. ? @ 0x000000000011918c

2025.07.07 17:56:55.371801 [ 230366 ] {} <Fatal> ClientBase: ########## Short fault info ############
2025.07.07 17:56:55.372047 [ 230366 ] {} <Fatal> ClientBase: (version 25.7.1.1, build id: 3B2497A8C3F2864173A3BE727283F17033A99C44, git hash: 7c806c2a3f1cb8ba19b36286bd5c72fb2b301a4d, architecture: x86_64) (from thread 229979) Received signal 6
2025.07.07 17:56:55.372157 [ 230366 ] {} <Fatal> ClientBase: Signal description: Aborted
2025.07.07 17:56:55.372198 [ 230366 ] {} <Fatal> ClientBase: 
2025.07.07 17:56:55.372271 [ 230366 ] {} <Fatal> ClientBase: Stack trace: 0x00007f2556db174d 0x00007f2556d57dc0 0x00007f2556d3f57a 0x0000562eab1f6a63 0x0000562eab1f6e37 0x0000562eb4b6e39b 0x0000562eb451a9e8 0x0000562eb451a666 0x0000562eb4538638 0x0000562eb452bb86 0x0000562eb452bfcf 0x0000562eb452cb8d 0x0000562eab34a577 0x0000562eab350d14 0x0000562eab347803 0x0000562eab34e514 0x00007f2556daf7eb 0x00007f2556e3318c
2025.07.07 17:56:55.372373 [ 230366 ] {} <Fatal> ClientBase: ########################################
2025.07.07 17:56:55.372696 [ 230366 ] {} <Fatal> ClientBase: (version 25.7.1.1, build id: 3B2497A8C3F2864173A3BE727283F17033A99C44, git hash: 7c806c2a3f1cb8ba19b36286bd5c72fb2b301a4d) (from thread 229979) (query_id: f0f7b38d-b760-4e77-ba1f-a119935e354e) (query: SELECT DISTINCT number * 1 FROM numbers(10, sipHash64(sipHash64(sipHash64(2), 1), 1, 2, *), sipHash64(sipHash64(29103473, sipHash64(1), '3', sipHash64(1), 1))) GROUP BY 1, isNullable(1) WITH TOTALS) Received signal Aborted (6)
2025.07.07 17:56:55.372955 [ 230366 ] {} <Fatal> ClientBase: 
2025.07.07 17:56:55.373132 [ 230366 ] {} <Fatal> ClientBase: Stack trace: 0x00007f2556db174d 0x00007f2556d57dc0 0x00007f2556d3f57a 0x0000562eab1f6a63 0x0000562eab1f6e37 0x0000562eb4b6e39b 0x0000562eb451a9e8 0x0000562eb451a666 0x0000562eb4538638 0x0000562eb452bb86 0x0000562eb452bfcf 0x0000562eb452cb8d 0x0000562eab34a577 0x0000562eab350d14 0x0000562eab347803 0x0000562eab34e514 0x00007f2556daf7eb 0x00007f2556e3318c
2025.07.07 17:56:55.373443 [ 230366 ] {} <Fatal> ClientBase: 3. ? @ 0x000000000009774d
2025.07.07 17:56:55.373614 [ 230366 ] {} <Fatal> ClientBase: 4. ? @ 0x000000000003ddc0
2025.07.07 17:56:55.373828 [ 230366 ] {} <Fatal> ClientBase: 5. ? @ 0x000000000002557a
[tpx1] 2025.07.07 17:56:55.372373 [ 230366 ] <Fatal> ClientBase: ########################################
[tpx1] 2025.07.07 17:56:55.372696 [ 230366 ] <Fatal> ClientBase: (version 25.7.1.1, build id: 3B2497A8C3F2864173A3BE727283F17033A99C44, git hash: 7c806c2a3f1cb8ba19b36286bd5c72fb2b301a4d) (from thread 229979) (query_id: f0f7b38d-b760-4e77-ba1f-a119935e354e) (query: SELECT DISTINCT number * 1 FROM numbers(10, sipHash64(sipHash64(sipHash64(2), 1), 1, 2, *), sipHash64(sipHash64(29103473, sipHash64(1), '3', sipHash64(1), 1))) GROUP BY 1, isNullable(1) WITH TOTALS) Received signal Aborted (6)
[tpx1] 2025.07.07 17:56:55.372955 [ 230366 ] <Fatal> ClientBase: 
[tpx1] 2025.07.07 17:56:55.373132 [ 230366 ] <Fatal> ClientBase: Stack trace: 0x00007f2556db174d 0x00007f2556d57dc0 0x00007f2556d3f57a 0x0000562eab1f6a63 0x0000562eab1f6e37 0x0000562eb4b6e39b 0x0000562eb451a9e8 0x0000562eb451a666 0x0000562eb4538638 0x0000562eb452bb86 0x0000562eb452bfcf 0x0000562eb452cb8d 0x0000562eab34a577 0x0000562eab350d14 0x0000562eab347803 0x0000562eab34e514 0x00007f2556daf7eb 0x00007f2556e3318c
[tpx1] 2025.07.07 17:56:55.373443 [ 230366 ] <Fatal> ClientBase: 3. ? @ 0x000000000009774d
[tpx1] 2025.07.07 17:56:55.373614 [ 230366 ] <Fatal> ClientBase: 4. ? @ 0x000000000003ddc0
[tpx1] 2025.07.07 17:56:55.373828 [ 230366 ] <Fatal> ClientBase: 5. ? @ 0x000000000002557a
↙ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:56.055521 [ 230366 ] {} <Fatal> ClientBase: 6. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:50: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x00000000123c1a63
[tpx1] 2025.07.07 17:56:56.055521 [ 230366 ] <Fatal> ClientBase: 6. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:50: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x00000000123c1a63
↗ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:56.400501 [ 230366 ] {} <Fatal> ClientBase: 7. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:56: DB::abortOnFailedAssertion(String const&) @ 0x00000000123c1e37lay of the progress table.
[tpx1] 2025.07.07 17:56:56.400501 [ 230366 ] <Fatal> ClientBase: 7. /home/tavplubix/ch/ClickHouse/src/Common/Exception.cpp:56: DB::abortOnFailedAssertion(String const&) @ 0x00000000123c1e37
↖ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:57.805650 [ 230366 ] {} <Fatal> ClientBase: 8. /home/tavplubix/ch/ClickHouse/src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp:335: DB::(anonymous namespace)::NumbersRangedSource::generate() @ 0x000000001bd3939b
[tpx1] 2025.07.07 17:56:57.805650 [ 230366 ] <Fatal> ClientBase: 8. /home/tavplubix/ch/ClickHouse/src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp:335: DB::(anonymous namespace)::NumbersRangedSource::generate() @ 0x000000001bd3939b
→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:58.166181 [ 230366 ] {} <Fatal> ClientBase: 9. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001b6e59e8gle the display of the progress table.
[tpx1] 2025.07.07 17:56:58.166181 [ 230366 ] <Fatal> ClientBase: 9. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001b6e59e8
2025.07.07 17:56:58.257910 [ 230366 ] {} <Fatal> ClientBase: 10. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001b6e5666
[tpx1] 2025.07.07 17:56:58.257910 [ 230366 ] <Fatal> ClientBase: 10. /home/tavplubix/ch/ClickHouse/src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001b6e5666
2025.07.07 17:56:58.391248 [ 230366 ] {} <Fatal> ClientBase: 11.0. inlined from /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.07.07 17:56:58.391509 [ 230366 ] {} <Fatal> ClientBase: 11. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001b703638
[tpx1] 2025.07.07 17:56:58.391248 [ 230366 ] <Fatal> ClientBase: 11.0. inlined from /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
[tpx1] 2025.07.07 17:56:58.391509 [ 230366 ] <Fatal> ClientBase: 11. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000001b703638
↑ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:58.748406 [ 230366 ] {} <Fatal> ClientBase: 12. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001b6f6b86
[tpx1] 2025.07.07 17:56:58.748406 [ 230366 ] <Fatal> ClientBase: 12. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001b6f6b86
↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:59.148400 [ 230366 ] {} <Fatal> ClientBase: 13. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:276: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001b6f6fcf
[tpx1] 2025.07.07 17:56:59.148400 [ 230366 ] <Fatal> ClientBase: 13. /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:276: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x000000001b6f6fcf
← Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:59.397308 [ 230366 ] {} <Fatal> ClientBase: 14.0. inlined from /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:472: operator()oggle the display of the progress table.
2025.07.07 17:56:59.397631 [ 230366 ] {} <Fatal> ClientBase: 14.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.07.07 17:56:59.397793 [ 230366 ] {} <Fatal> ClientBase: 14.2. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
2025.07.07 17:56:59.397891 [ 230366 ] {} <Fatal> ClientBase: 14.3. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.07.07 17:56:59.398012 [ 230366 ] {} <Fatal> ClientBase: 14. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x000000001b6f7b8d
[tpx1] 2025.07.07 17:56:59.397308 [ 230366 ] <Fatal> ClientBase: 14.0. inlined from /home/tavplubix/ch/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:472: operator()
[tpx1] 2025.07.07 17:56:59.397631 [ 230366 ] <Fatal> ClientBase: 14.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>()()) std::__invoke[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[tpx1] 2025.07.07 17:56:59.397793 [ 230366 ] <Fatal> ClientBase: 14.2. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&>(DB::PipelineExecutor::spawnThreadsImpl(std::shared_ptr<DB::IAcquiredSlot>)::$_0&)
[tpx1] 2025.07.07 17:56:59.397891 [ 230366 ] <Fatal> ClientBase: 14.3. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
[tpx1] 2025.07.07 17:56:59.398012 [ 230366 ] <Fatal> ClientBase: 14. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x000000001b6f7b8d
↑ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:59.632094 [ 230366 ] {} <Fatal> ClientBase: 15.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? the display of the progress table.
2025.07.07 17:56:59.632418 [ 230366 ] {} <Fatal> ClientBase: 15.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.07.07 17:56:59.632526 [ 230366 ] {} <Fatal> ClientBase: 15. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:799: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000012515577
[tpx1] 2025.07.07 17:56:59.632094 [ 230366 ] <Fatal> ClientBase: 15.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[tpx1] 2025.07.07 17:56:59.632418 [ 230366 ] <Fatal> ClientBase: 15.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[tpx1] 2025.07.07 17:56:59.632526 [ 230366 ] <Fatal> ClientBase: 15. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:799: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000012515577
↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:56:59.852518 [ 230366 ] {} <Fatal> ClientBase: 16.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
2025.07.07 17:56:59.852774 [ 230366 ] {} <Fatal> ClientBase: 16.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
2025.07.07 17:56:59.852869 [ 230366 ] {} <Fatal> ClientBase: 16.2. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
2025.07.07 17:56:59.852943 [ 230366 ] {} <Fatal> ClientBase: 16. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000001251bd14
[tpx1] 2025.07.07 17:56:59.852518 [ 230366 ] <Fatal> ClientBase: 16.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&>().*std::declval<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&, void>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&)
[tpx1] 2025.07.07 17:56:59.852774 [ 230366 ] <Fatal> ClientBase: 16.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, 0ul>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&, std::__tuple_indices<0ul>)
[tpx1] 2025.07.07 17:56:59.852869 [ 230366 ] <Fatal> ClientBase: 16.2. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&)(), std::tuple<ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>&)
[tpx1] 2025.07.07 17:56:59.852943 [ 230366 ] <Fatal> ClientBase: 16. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.h:312: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x000000001251bd14
2025.07.07 17:57:00.010546 [ 230366 ] {} <Fatal> ClientBase: 17.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.07.07 17:57:00.010783 [ 230366 ] {} <Fatal> ClientBase: 17.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.07.07 17:57:00.010869 [ 230366 ] {} <Fatal> ClientBase: 17. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:809: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000012512803
[tpx1] 2025.07.07 17:57:00.010546 [ 230366 ] <Fatal> ClientBase: 17.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
[tpx1] 2025.07.07 17:57:00.010783 [ 230366 ] <Fatal> ClientBase: 17.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
[tpx1] 2025.07.07 17:57:00.010869 [ 230366 ] <Fatal> ClientBase: 17. /home/tavplubix/ch/ClickHouse/src/Common/ThreadPool.cpp:809: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000012512803
← Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)         2025.07.07 17:57:00.146845 [ 230366 ] {} <Fatal> ClientBase: 18.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.07.07 17:57:00.147039 [ 230366 ] {} <Fatal> ClientBase: 18.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.07.07 17:57:00.147112 [ 230366 ] {} <Fatal> ClientBase: 18. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000012519514
2025.07.07 17:57:00.147203 [ 230366 ] {} <Fatal> ClientBase: 19. ? @ 0x00000000000957eb
2025.07.07 17:57:00.147262 [ 230366 ] {} <Fatal> ClientBase: 20. ? @ 0x000000000011918c
2025.07.07 17:57:00.147313 [ 230366 ] {} <Fatal> ClientBase: This ClickHouse version is not official and should be upgraded to the official build.
2025.07.07 17:57:00.147934 [ 230366 ] {} <Fatal> ClientBase: Changed settings: allow_introspection_functions = true, serialize_query_plan = false, storage_file_read_method = 'mmap', implicit_select = true
[tpx1] 2025.07.07 17:57:00.146845 [ 230366 ] <Fatal> ClientBase: 18.0. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
[tpx1] 2025.07.07 17:57:00.147039 [ 230366 ] <Fatal> ClientBase: 18.1. inlined from /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
[tpx1] 2025.07.07 17:57:00.147112 [ 230366 ] <Fatal> ClientBase: 18. /home/tavplubix/ch/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000012519514
[tpx1] 2025.07.07 17:57:00.147203 [ 230366 ] <Fatal> ClientBase: 19. ? @ 0x00000000000957eb
[tpx1] 2025.07.07 17:57:00.147262 [ 230366 ] <Fatal> ClientBase: 20. ? @ 0x000000000011918c
[tpx1] 2025.07.07 17:57:00.147313 [ 230366 ] <Fatal> ClientBase: This ClickHouse version is not official and should be upgraded to the official build.
[tpx1] 2025.07.07 17:57:00.147934 [ 230366 ] <Fatal> ClientBase: Changed settings: allow_introspection_functions = true, serialize_query_plan = false, storage_file_read_method = 'mmap', implicit_select = true

```

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by nihalzp**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix logical error and modulo bug in `numbers` system table when big step size is used. Closes https://github.com/ClickHouse/ClickHouse/issues/83398.

### Documentation entry for user-facing changes
- [ ] Documentation is written (mandatory for new features)

### Details
The following query has logical error in debug build:

```sql
SELECT number FROM numbers(10, 14630045721179951620, 6670599363308407409);
```

Modulo bug:

```sql
SELECT number FROM numbers(18446744073709551610, 9, 3);
```

Currently gives:
```txt
18446744073709551610
18446744073709551613
2
```

Should be:
```txt
18446744073709551610
18446744073709551613
0
```

### CODE REVIEW

File: src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp [hunk 1]
```diff
@@ -197,56 +197,60 @@ class NumbersRangedSource : public ISource
 
     String getName() const override { return "NumbersRange"; }
 
-protected:
+private:
     /// Find the data range in ranges and return how many item found.
     /// If no data left in ranges return 0.
-    UInt64 findRanges(RangesPos & start, RangesPos & end, UInt64 base_block_size_)
+    UInt64 findRanges(RangesPos & start, RangesPos & end)
```
Comment (antaljanosbenjamin) [inline src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp]: I know it is not your changes, but as you removed another argument, I will ask: cannot we get rid of `end` also? We don't read its value, the first time we access it on line 213 we overwrite it. That suggests me it doesn't hold any valueable input.

**Review by antaljanosbenjamin — APPROVED** [review]

File: src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp (hunk 1 above)
Comment (nihalzp) [reply src/Processors/QueryPlan/ReadFromSystemNumbersStep.cpp]: That's a very good catch! I missed it. I have removed it + made some minor simplifications/improvements as well.

**Comment by nihalzp** [comment]
[Build (amd_compat)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90123&sha=83c67e4eef8bd3d754de8d1d1835e670f54d7546&name_0=PR&name_1=Build%20%28amd_compat%29)
- https://github.com/ClickHouse/ClickHouse/issues/90492
