### PR TITLE
Fetching a part waits when that part is fully committed on remote replica

### LINKED ISSUE #49926: Replication errors in master: NO_SUCH_DATA_PART / RECEIVED_ERROR_FROM_REMOTE_IO_SERVER
When running inserts with master in one replica and 23.3/HEAD in another we've started seeing these errors during some runs:

Server 1 (ingesting data)
```
Summary of errors: 
Row 1:
──────
server_shard:       1
version:            23.5.1.1523
name:               NO_SUCH_DATA_PART
code:               232
quantity:           1
last_error_message: No part all_551_551_0 in table
traceback:          DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)
DB::DataPartsExchange::Service::findPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
DB::DataPartsExchange::Service::processQuery(DB::HTMLForm const&, DB::ReadBuffer&, DB::WriteBuffer&, DB::HTTPServerResponse&)
DB::InterserverIOHTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&)
DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&)
DB::HTTPServerConnection::run()
Poco::Net::TCPServerConnection::start()
Poco::Net::TCPServerDispatcher::run()
Poco::PooledThread::run()
Poco::ThreadImpl::runnableEntry(void*)
```

Server 2 (replicating data):
```
Row 2:
──────
server_shard:       2
version:            23.3.2.37
name:               RECEIVED_ERROR_FROM_REMOTE_IO_SERVER
code:               86
quantity:           1
last_error_message: Received error from remote server /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 232. DB::Exception: No part all_551_551_0 in table. (NO_SUCH_DATA_PART), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000dd11c15 in /usr/bin/clickhouse
1. ? @ 0x0000000008b0da63 in /usr/bin/clickhouse
2. DB::DataPartsExchange::Service::findPart(String const&) @ 0x000000001403e528 in /usr/bin/clickhouse
3. DB::DataPartsExchange::Service::processQuery(DB::HTMLForm const&, DB::ReadBuffer&, DB::WriteBuffer&, DB::HTTPServerResponse&) @ 0x000000001403c6ee in /usr/bin/clickhouse
4. DB::InterserverIOHTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&) @ 0x000000001459334a in /usr/bin/clickhouse
5. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000014593c5c in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x00000000145f0cd2 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x00000000175274b4 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000175286d1 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x00000000176a51a7 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000176a2bdc in /usr/bin/clickhouse
11. ? @ 0x00007f526cc5ab43 in ?
12. ? @ 0x00007f526cceca00 in ?
 (version 23.5.1.1523 (official build))
traceback:          DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)
DB::assertResponseIsOk(Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, std::__1::basic_istream<char, std::__1::char_traits<char>>&, bool)
DB::DataPartsExchange::Fetcher::fetchSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Throttler>, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::optional<DB::CurrentlySubmergingEmergingTagger>*, bool, std::__1::shared_ptr<DB::IDisk>)
DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>, bool)
DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool)
DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&)
DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)
DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)
DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>)
DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction()
ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)
Please review these new errors and fix them
```

Looking at the logs it seems that server 1 declares (via ZK) that there is a new part `all_551_551_0`. The second replica tries to fetch it, and then the source replica says it doesn't exists.

Server 1 (trimmed) logs:

```
2023.05.16 11:34:10.608776 [ 290 ] {} <Trace> DynamicQueryHandler: Request URI: /?database=d_test_public_e2e_eaf76028&query_id=bdf3b983-5ac8-4ca7-8823-e1c7288d78f6&query=insert+into+%60t_7c9c5a1e92974e82b23c20ca3d814da0%60+%28span_id%2C+operation_name%2C+start_datetime%2C+start_time%2C+duration%2C+parent_id%2C+component%2C+kind%2C+user%2C+user_email%2C+workspace%2C+workspace_name%2C+token%2C+token_name%2C+url%2C+method%2C+status_code%2C+error%2C+logs%2C+tags%29+FORMAT+CSV&max_result_bytes=104857600&log_queries=1&optimize_throw_if_noop=1&output_format_json_quote_64bit_integers=0&lock_acquire_timeout=10&wait_end_of_query=1&buffer_size=104857600&format_csv_delimiter=%2C&input_format_defaults_for_omitted_fields=1&max_execution_time=10
2023.05.16 11:34:10.609227 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> executeQuery: (from 127.0.0.1:33766) insert into `t_7c9c5a1e92974e82b23c20ca3d814da0` (span_id, operation_name, start_datetime, start_time, duration, parent_id, component, kind, user, user_email, workspace, workspace_name, token, token_name, url, method, status_code, error, logs, tags) FORMAT CSV  (stage: Complete)
2023.05.16 11:34:10.609389 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: INSERT(span_id, operation_name, start_datetime, start_time, duration, parent_id, component, kind, user, user_email, workspace, workspace_name, token, token_name, url, method, status_code, error, logs, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.610162 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(assumeNotNull(status_code) AS status_code) != 429" moved to PREWHERE
2023.05.16 11:34:10.610670 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(span_id, operation_name, start_datetime, duration, workspace, token, token_name, url, status_code, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.611789 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "((operation_name = 'APIPipeDataHandler') AND JSONHas(tags, 'pipe_id')) OR (operation_name = 'APIQueryHandler')" moved to PREWHERE
2023.05.16 11:34:10.612394 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(operation_name, start_datetime, duration, workspace, url, status_code, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.613429 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(user IS NOT NULL) AND (operation_name = 'APIPipeDataHandler')" moved to PREWHERE
2023.05.16 11:34:10.613952 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(span_id, operation_name, start_datetime, user, url, status_code, error, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.614457 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "url LIKE '/snapshot/%'" moved to PREWHERE
2023.05.16 11:34:10.614610 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(start_datetime, url) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.615086 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ParallelParsingInputFormat: Parallel parsing is used
2023.05.16 11:34:10.615820 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0 (266c6161-b923-4773-80f1-1cc1b017b2e3): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2023.05.16 11:34:10.615868 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 55.61 GiB.
2023.05.16 11:34:10.616246 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> MergedBlockOutputStream: filled checksums 202305_2663_2663_0 (state Temporary)
2023.05.16 11:34:10.616445 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0 (266c6161-b923-4773-80f1-1cc1b017b2e3) (Replicated OutputStream): Wrote block with ID '202305_2444977480161974539_6595773958984168092', 1 rows
2023.05.16 11:34:10.617383 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0 (266c6161-b923-4773-80f1-1cc1b017b2e3): Renaming temporary part tmp_insert_202305_2663_2663_0 to 202305_2662_2662_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2023.05.16 11:34:10.619551 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(span_id, operation_name, start_datetime, duration, workspace, token, token_name, url, status_code, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.619676 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.05.16 11:34:10.622467 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(operation_name, start_datetime, duration, workspace, url, status_code, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.622569 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.05.16 11:34:10.624564 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000694126 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624699 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregating
2023.05.16 11:34:10.624734 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> Aggregator: An entry for key=5731657522645148255 found in cache: sum_of_sizes=1, median_size=0
2023.05.16 11:34:10.624751 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> Aggregator: Aggregation method: serialized
2023.05.16 11:34:10.624788 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 1 to 1 rows (from 114.00 B) in 0.000941449 sec. (1062.192 rows/sec., 118.25 KiB/sec.)
2023.05.16 11:34:10.624803 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000915215 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624819 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000916776 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624832 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000915271 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624852 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.00092067 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624866 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000921199 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624884 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000926105 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.624902 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> Aggregator: Merging aggregated data
2023.05.16 11:34:10.626246 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(span_id, operation_name, start_datetime, user, url, status_code, error, tags) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.626332 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.05.16 11:34:10.627786 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> MergingSortedTransform: Merge sorted 1 blocks, 0 rows in 0 sec.
2023.05.16 11:34:10.628414 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> ContextAccess (default): Access granted: SELECT(start_datetime, url) ON d_test_public_e2e_eaf76028.t_7c9c5a1e92974e82b23c20ca3d814da0
2023.05.16 11:34:10.628491 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.05.16 11:34:10.629008 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000224935 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629066 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000292442 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629086 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000306401 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629106 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000324311 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629122 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000338672 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629136 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000349741 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629148 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000359144 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629167 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.00 B) in 0.000373648 sec. (0.000 rows/sec., 0.00 B/sec.)
2023.05.16 11:34:10.629181 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> Aggregator: Merging aggregated data
2023.05.16 11:34:10.629461 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2023.05.16 11:34:10.629505 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 55.61 GiB.
2023.05.16 11:34:10.629810 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Trace> MergedBlockOutputStream: filled checksums all_552_552_0 (state Temporary)
2023.05.16 11:34:10.629935 [ 290 ] {bdf3b983-5ac8-4ca7-8823-e1c7288d78f6} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Replicated OutputStream): Wrote block with 1 rows
2023.05.16 11:34:10.637444 [ 287 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 10.32.7.3:34658, User-Agent: ClickHouse/23.3.2.37, Length: 0, Content Type: , Transfer Encoding: identity, X-Forwarded-For: (none)
2023.05.16 11:34:10.637545 [ 287 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false
2023.05.16 11:34:10.637581 [ 287 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Replicated PartsService): Sending part all_551_551_0
2023.05.16 11:34:10.637722 [ 287 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Replicated PartsService): Part all_551_551_0 was not found, do not report it as broken
2023.05.16 11:34:10.637966 [ 287 ] {} <Error> InterserverIOHTTPHandler: Code: 232. DB::Exception: No part all_551_551_0 in table. (NO_SUCH_DATA_PART), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000dd11c15 in /usr/bin/clickhouse
1. ? @ 0x0000000008b0da63 in /usr/bin/clickhouse
2. DB::DataPartsExchange::Service::findPart(String const&) @ 0x000000001403e528 in /usr/bin/clickhouse
3. DB::DataPartsExchange::Service::processQuery(DB::HTMLForm const&, DB::ReadBuffer&, DB::WriteBuffer&, DB::HTTPServerResponse&) @ 0x000000001403c6ee in /usr/bin/clickhouse
4. DB::InterserverIOHTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&) @ 0x000000001459334a in /usr/bin/clickhouse
5. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000014593c5c in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x00000000145f0cd2 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x00000000175274b4 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000175286d1 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x00000000176a51a7 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000176a2bdc in /usr/bin/clickhouse
11. ? @ 0x00007f526cc5ab43 in ?
12. ? @ 0x00007f526cceca00 in ?
 (version 23.5.1.1523 (official build))
```

Server 2 trimmed logs:
```
2023.05.16 11:34:10.634300 [ 151 ] {} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000661 - log-0000000661
2023.05.16 11:34:10.635688 [ 151 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (ReplicatedMergeTreeQueue): Insert entry queue-0000000661 to queue with type GET_PART with virtual parts [all_551_551_0]
2023.05.16 11:34:10.635731 [ 151 ] {} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2023.05.16 11:34:10.637057 [ 252 ] {} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb): Fetching part all_551_551_0 from /clickhouse/tables/01-01/d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635/replicas/clickhouse-01
2023.05.16 11:34:10.637313 [ 252 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://runner-mjyz7t4s-project-6576720-concurrent-24k78s5:29009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false
2023.05.16 11:34:10.638441 [ 252 ] {} <Error> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 86. DB::HTTPException: Received error from remote server /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 232. DB::Exception: No part all_551_551_0 in table. (NO_SUCH_DATA_PART), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000dd11c15 in /usr/bin/clickhouse
1. ? @ 0x0000000008b0da63 in /usr/bin/clickhouse
2. DB::DataPartsExchange::Service::findPart(String const&) @ 0x000000001403e528 in /usr/bin/clickhouse
3. DB::DataPartsExchange::Service::processQuery(DB::HTMLForm const&, DB::ReadBuffer&, DB::WriteBuffer&, DB::HTTPServerResponse&) @ 0x000000001403c6ee in /usr/bin/clickhouse
4. DB::InterserverIOHTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&) @ 0x000000001459334a in /usr/bin/clickhouse
5. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000014593c5c in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x00000000145f0cd2 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x00000000175274b4 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000175286d1 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x00000000176a51a7 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000176a2bdc in /usr/bin/clickhouse
11. ? @ 0x00007f526cc5ab43 in ?
12. ? @ 0x00007f526cceca00 in ?
 (version 23.5.1.1523 (official build)). (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe1e20b5 in /usr/bin/clickhouse
1. ? @ 0xe3f496f in /usr/bin/clickhouse
2. ? @ 0xe3f4658 in /usr/bin/clickhouse
3. DB::assertResponseIsOk(Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, std::basic_istream<char, std::char_traits<char>>&, bool) @ 0xe3f4564 in /usr/bin/clickhouse
4. ? @ 0x14454999 in /usr/bin/clickhouse
5. ? @ 0x144504ef in /usr/bin/clickhouse
6. DB::DataPartsExchange::Fetcher::fetchSelectedPart(std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, String const&, String const&, String const&, int, DB::ConnectionTimeouts const&, String const&, String const&, String const&, std::shared_ptr<DB::Throttler>, bool, String const&, std::optional<DB::CurrentlySubmergingEmergingTagger>*, bool, std::shared_ptr<DB::IDisk>) @ 0x1443d1d9 in /usr/bin/clickhouse
7. ? @ 0x141603f0 in /usr/bin/clickhouse
8. DB::StorageReplicatedMergeTree::fetchPart(String const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, String const&, bool, unsigned long, std::shared_ptr<zkutil::ZooKeeper>, bool) @ 0x14096b18 in /usr/bin/clickhouse
9. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool) @ 0x14087d50 in /usr/bin/clickhouse
10. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x140757c5 in /usr/bin/clickhouse
11. ? @ 0x1415dc5f in /usr/bin/clickhouse
12. DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x147dcfa6 in /usr/bin/clickhouse
13. DB::StorageReplicatedMergeTree::processQueueEntry(std::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x140b887c in /usr/bin/clickhouse
14. ? @ 0x1415e931 in /usr/bin/clickhouse
15. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x89ce4cc in /usr/bin/clickhouse
16. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction() @ 0x89ce180 in /usr/bin/clickhouse
17. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe2b5625 in /usr/bin/clickhouse
18. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe2b8195 in /usr/bin/clickhouse
19. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2b13f3 in /usr/bin/clickhouse
20. ? @ 0xe2b7061 in /usr/bin/clickhouse
21. ? @ 0x7f9fad4deb43 in ?
22. ? @ 0x7f9fad570a00 in ?
 (version 23.3.2.37 (official build))

2023.05.16 11:34:10.650500 [ 229 ] {} <Trace> HTTPCommon: Failed communicating with runner-mjyz7t4s-project-6576720-concurrent-24k78s5 with error 'Received error from remote server /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false. HTTP status code: 500 Internal Server Error, body: Code: 232. DB::Exception: No part all_551_551_0 in table. (NO_SUCH_DATA_PART), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000dd11c15 in /usr/bin/clickhouse
1. ? @ 0x0000000008b0da63 in /usr/bin/clickhouse
2. DB::DataPartsExchange::Service::findPart(String const&) @ 0x000000001403e528 in /usr/bin/clickhouse
3. DB::DataPartsExchange::Service::processQuery(DB::HTMLForm const&, DB::ReadBuffer&, DB::WriteBuffer&, DB::HTTPServerResponse&) @ 0x000000001403c6ee in /usr/bin/clickhouse
4. DB::InterserverIOHTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&) @ 0x000000001459334a in /usr/bin/clickhouse
5. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000014593c5c in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x00000000145f0cd2 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x00000000175274b4 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000175286d1 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x00000000176a51a7 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000176a2bdc in /usr/bin/clickhouse
11. ? @ 0x00007f526cc5ab43 in ?
12. ? @ 0x00007f526cceca00 in ?
 (version 23.5.1.1523 (official build))' will try to reconnect session
```

A few seconds later it retries and now it gets the part:

Server 1:
```
2023.05.16 11:34:10.853111 [ 287 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 10.32.7.3:34658, User-Agent: ClickHouse/23.3.2.37, Length: 0, Content Type: , Transfer Encoding: identity, X-Forwarded-For: (none)
2023.05.16 11:34:10.853143 [ 201 ] {72bc53a6-9644-4c5a-ab09-2df40dc21191} <Trace> MergedBlockOutputStream: filled checksums 202305_0_2661_946 (state Temporary)
2023.05.16 11:34:10.853211 [ 287 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false
2023.05.16 11:34:10.853252 [ 287 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Replicated PartsService): Sending part all_551_551_0
2023.05.16 11:34:10.853793 [ 287 ] {} <Debug> InterserverIOHTTPHandler: Done processing query
```

Server 2:
```
2023.05.16 11:34:10.852404 [ 252 ] {} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb): Fetching part all_551_551_0 from /clickhouse/tables/01-01/d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635/replicas/clickhouse-01
2023.05.16 11:34:10.852944 [ 252 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://runner-mjyz7t4s-project-6576720-concurrent-24k78s5:29009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01-01%2Fd_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635%2Freplicas%2Fclickhouse-01&part=all_551_551_0&client_protocol_version=7&compress=false
2023.05.16 11:34:10.853863 [ 252 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2023.05.16 11:34:10.853912 [ 252 ] {} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 55.61 GiB.
2023.05.16 11:34:10.853954 [ 252 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Fetcher): Disk for fetch is not provided, getting disk from reservation default with type 'local'
2023.05.16 11:34:10.854012 [ 252 ] {} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Fetcher): Downloading part all_551_551_0 onto disk default.
2023.05.16 11:34:10.854835 [ 252 ] {} <Debug> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb) (Fetcher): Download of part all_551_551_0 onto disk default finished.
2023.05.16 11:34:10.854968 [ 252 ] {} <Trace> d_test_public_e2e_eaf76028.t_27451b7df15347229e4a6c11c2393635 (dbc14010-5be2-443b-bfc4-e01dd56010eb): Renaming temporary part tmp-fetch_all_551_551_0 to all_551_551_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
```

It might also be happening in master-master, but we are not testing it currently.

Looking at recent changes it seems to be related to the removal of preactive parts in DataPartsExchange Service::findPart in https://github.com/ClickHouse/ClickHouse/pull/49432. It seems benign and recoverable but it's triggering errors in both logs and system.errors, which will lead to alerts of problems that aren't there.

cc @CheSema @tavplubix

### PR DESCRIPTION
**Pull request by CheSema**
fixes https://github.com/ClickHouse/ClickHouse/issues/49926

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fetching a part waits when that part is fully committed on remote replica. It is better not send part in PreActive state. In case of zero copy this is mandatory restriction.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 5d3e288c4e4eedd320f609289ef5883c972670c7 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56808/5d3e288c4e4eedd320f609289ef5883c972670c7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6880315100">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56808/5d3e288c4e4eedd320f609289ef5883c972670c7/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Storages/MergeTree/DataPartsExchange.cpp [hunk 1]
```diff
@@ -140,6 +139,29 @@ void Service::processQuery(const HTMLForm & params, ReadBuffer & /*body*/, Write
     {
         part = findPart(part_name);
 
+        /// Ephemeral zero-copy lock may be lost for PreActive parts
+        /// do not expose PreActive parts
+        if (client_protocol_version >= REPLICATION_PROTOCOL_VERSION_WITH_WAITING_PREACTIVE)
```
Comment (Algunenano) [inline src/Storages/MergeTree/DataPartsExchange.cpp:144]: Philosophical question: Why prefer waiting on the "client" (when error is returned) instead of waiting in the server? If we waited in the server we wouldn't need to add a new protocol version, just wait for some time and return it (or an error if waited for more than x amount of time).

Comment (CheSema) [reply src/Storages/MergeTree/DataPartsExchange.cpp:144]: Possible too.
I just not see it good if server just hungs. Some receive timeout on client could be triggered. That would be looked like either network errors or server hungs. Sending some headers time to time could solve that, but it overkill.
But I agree that this is overthinking.
Will try your approach.

File: src/Storages/MergeTree/DataPartsExchange.cpp [hunk 2]
```diff
@@ -351,22 +349,53 @@ MergeTreeData::DataPart::Checksums Service::sendPartFromDisk(
...
-    throw Exception(ErrorCodes::NO_SUCH_DATA_PART, "No part {} in table", name);
+    /// Ephemeral zero-copy lock may be lost for PreActive parts
+    /// do not expose PreActive parts for zero-copy
+
+    static const UInt32 wait_timeout_ms = 1000;
+    bool pred_result = wait_loop(wait_timeout_ms, [&] () { return part->getState() != MergeTreeDataPartState::PreActive; });
+
+    if (!pred_result)
+        throw Exception(
+                ErrorCodes::ABORTED,
```
Comment (Algunenano) [inline src/Storages/MergeTree/DataPartsExchange.cpp:394]: This error message seems the opposite of what it should be , right? The part is in PreActive state and that's why it cannot be sent

File: tests/clickhouse-test [hunk 3]
```diff
@@ -673,6 +673,9 @@ class MergeTreeSettingsRandomizer:
         "primary_key_compress_block_size": lambda: random.randint(8000, 100000),
         "replace_long_file_name_to_hash": lambda: random.randint(0, 1),
         "max_file_name_length": threshold_generator(0.3, 0.3, 0, 128),
+        "sleep_before_commit_local_part_in_replicated_table_ms": threshold_generator(
```
Comment (CheSema) [inline tests/clickhouse-test:676]: Doing it for all tests affects them in a bad way. 
Some sleeps in commit + sleeps in fetches + waiting on client, that consumes resources for nothing. The heavy inserting tests become too slow for nothing.
Will remove that from randomization since the solution is short and understandable.

File: src/Storages/MergeTree/DataPartsExchange.cpp [hunk 4]
```diff
@@ -351,22 +349,53 @@ MergeTreeData::DataPart::Checksums Service::sendPartFromDisk(
...
-    if (part)
+    if (!zero_copy_enabled)
         return part;
 
-    throw Exception(ErrorCodes::NO_SUCH_DATA_PART, "No part {} in table", name);
+    /// Ephemeral zero-copy lock may be lost for PreActive parts
+    /// do not expose PreActive parts for zero-copy
+
+    static const UInt32 wait_timeout_ms = 1000;
+    bool pred_result = wait_loop(wait_timeout_ms, [&] () { return part->getState() != MergeTreeDataPartState::PreActive; });
```
Comment (CheSema) [inline src/Storages/MergeTree/DataPartsExchange.cpp:390]: Here is a data race. `state` is changed concurrently without any synchonization.

File: src/Storages/MergeTree/DataPartsExchange.cpp [hunk 5]
```diff
@@ -351,22 +349,59 @@ MergeTreeData::DataPart::Checksums Service::sendPartFromDisk(
...
+    {
+        auto lock = data.lockParts();
+        return part->getState() != MergeTreeDataPartState::PreActive;
+    };
+
+    bool pred_result = wait_loop(wait_timeout_ms, pred);
+    if (!pred_result)
+        throw Exception(
+                ErrorCodes::ABORTED,
+                "Part {} is in PreActive state for {} ms. Another host has to be asked.",
```
Comment (Algunenano) [inline src/Storages/MergeTree/DataPartsExchange.cpp:401]: Could we make it even more obvious for the client?

Something like `Could not exchange part {} as it's in preActive state ({} ms) and it uses zero copy replication. This is expected behaviour and the client will retry fetching the part automatically`.

That way we avoid (more) questions about the error.

**Review by Algunenano — APPROVED** [review]
