### PR TITLE
Fix ColumnConst comparison.

### LINKED ISSUE #17088: Address: NULL pointer. Access: read. Unknown si_code  error
clickHouse-version：  20.8.3.18
Today I encountered a BUG when I executed the following SQL:
ps：the count of query_log table is about  3000000

```
select '1111' as name from query_log order by name limit 10000;
```
When I sort the constants, the ch server crashed directly and serve went offline

and the Error details below ：
```
[zm-uat-118-24] 2020.11.16 20:01:09.458092 [ 18523 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458247 [ 18523 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7784) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458267 [ 18525 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458275 [ 18523 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458347 [ 18525 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7788) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458349 [ 18523 ] <Fatal> BaseDaemon: Stack trace: 0x10e81a33 0x113e5156 0x113e5a01 0x1126d50c 0x1129478e 0x1129a868 0x1129b0a3 0xa43cc4d 0xa43b3ff 0x7f02797dfdd5 0x7f02790fcead
[zm-uat-118-24] 2020.11.16 20:01:09.458359 [ 18526 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458392 [ 18525 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458455 [ 18523 ] <Fatal> BaseDaemon: 3. void DB::IColumn::compareImpl<DB::ColumnString, false, false>(DB::ColumnString const&, unsigned long, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&, int) const @ 0x10e81a33 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458459 [ 18526 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7791) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458510 [ 18526 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458360 [ 18524 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458534 [ 18523 ] <Fatal> BaseDaemon: 4. DB::getFilterMask(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, std::__1::vector<DB::SortColumnDescription, std::__1::allocator<DB::SortColumnDescription> > const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x113e5156 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458491 [ 18527 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458563 [ 18523 ] <Fatal> BaseDaemon: 5. DB::PartialSortingTransform::transform(DB::Chunk&) @ 0x113e5a01 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458568 [ 18527 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7783) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458629 [ 18523 ] <Fatal> BaseDaemon: 6. DB::ISimpleTransform::work() @ 0x1126d50c in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458545 [ 18526 ] <Fatal> BaseDaemon: Stack trace: 0x10e81a33 0x113e5156 0x113e5a01 0x1126d50c 0x1129478e 0x1129a868 0x1129b0a3 0xa43cc4d 0xa43b3ff 0x7f02797dfdd5 0x7f02790fcead
[zm-uat-118-24] 2020.11.16 20:01:09.458496 [ 18525 ] <Fatal> BaseDaemon: Stack trace: 0x10e81a33 0x113e5156 0x113e5a01 0x1126d50c 0x1129478e 0x1129a868 0x1129b0a3 0xa43cc4d 0xa43b3ff 0x7f02797dfdd5 0x7f02790fcead
[zm-uat-118-24] 2020.11.16 20:01:09.458673 [ 18523 ] <Fatal> BaseDaemon: 7. ? @ 0x1129478e in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458632 [ 18527 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458557 [ 18524 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7785) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458729 [ 18527 ] <Fatal> BaseDaemon: Stack trace: 0x10e81a33 0x113e5156 0x113e5a01 0x1126d50c 0x1129478e 0x1129a868 0x1129b0a3 0xa43cc4d 0xa43b3ff 0x7f02797dfdd5 0x7f02790fcead
[zm-uat-118-24] 2020.11.16 20:01:09.458711 [ 18528 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458719 [ 18523 ] <Fatal> BaseDaemon: 8. ? @ 0x1129a868 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458781 [ 18523 ] <Fatal> BaseDaemon: 9. ? @ 0x1129b0a3 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458748 [ 18526 ] <Fatal> BaseDaemon: 3. void DB::IColumn::compareImpl<DB::ColumnString, false, false>(DB::ColumnString const&, unsigned long, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&, int) const @ 0x10e81a33 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458768 [ 18528 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7787) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458779 [ 18527 ] <Fatal> BaseDaemon: 3. void DB::IColumn::compareImpl<DB::ColumnString, false, false>(DB::ColumnString const&, unsigned long, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&, int) const @ 0x10e81a33 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458749 [ 18524 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458822 [ 18528 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458832 [ 18526 ] <Fatal> BaseDaemon: 4. DB::getFilterMask(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, std::__1::vector<DB::SortColumnDescription, std::__1::allocator<DB::SortColumnDescription> > const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x113e5156 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458777 [ 18529 ] <Fatal> BaseDaemon: ########################################
[zm-uat-118-24] 2020.11.16 20:01:09.458830 [ 18523 ] <Fatal> BaseDaemon: 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa43cc4d in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458909 [ 18526 ] <Fatal> BaseDaemon: 5. DB::PartialSortingTransform::transform(DB::Chunk&) @ 0x113e5a01 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458883 [ 18528 ] <Fatal> BaseDaemon: Stack trace: 0x10e81a33 0x113e5156 0x113e5a01 0x1126d50c 0x1129478e 0x1129a868 0x1129b0a3 0xa43cc4d 0xa43b3ff 0x7f02797dfdd5 0x7f02790fcead
[zm-uat-118-24] 2020.11.16 20:01:09.458749 [ 18525 ] <Fatal> BaseDaemon: 3. void DB::IColumn::compareImpl<DB::ColumnString, false, false>(DB::ColumnString const&, unsigned long, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&, int) const @ 0x10e81a33 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458887 [ 18527 ] <Fatal> BaseDaemon: 4. DB::getFilterMask(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, std::__1::vector<DB::SortColumnDescription, std::__1::allocator<DB::SortColumnDescription> > const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x113e5156 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458914 [ 18529 ] <Fatal> BaseDaemon: (version 20.8.3.18, no build id) (from thread 7790) (query_id: da7b2507-7d1c-4879-a584-ee40cfc25554) Received signal Segmentation fault (11)
[zm-uat-118-24] 2020.11.16 20:01:09.458968 [ 18527 ] <Fatal> BaseDaemon: 5. DB::PartialSortingTransform::transform(DB::Chunk&) @ 0x113e5a01 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458955 [ 18526 ] <Fatal> BaseDaemon: 6. DB::ISimpleTransform::work() @ 0x1126d50c in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458876 [ 18524 ] <Fatal> BaseDaemon: Stack trace: 0x10e81a33 0x113e5156 0x113e5a01 0x1126d50c 0x1129478e 0x1129a868 0x1129b0a3 0xa43cc4d 0xa43b3ff 0x7f02797dfdd5 0x7f02790fcead
[zm-uat-118-24] 2020.11.16 20:01:09.458972 [ 18529 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[zm-uat-118-24] 2020.11.16 20:01:09.458984 [ 18528 ] <Fatal> BaseDaemon: 3. void DB::IColumn::compareImpl<DB::ColumnString, false, false>(DB::ColumnString const&, unsigned long, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>*, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&, int) const @ 0x10e81a33 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.459005 [ 18527 ] <Fatal> BaseDaemon: 6. DB::ISimpleTransform::work() @ 0x1126d50c in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.459097 [ 18527 ] <Fatal> BaseDaemon: 7. ? @ 0x1129478e in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.458978 [ 18525 ] <Fatal> BaseDaemon: 4. DB::getFilterMask(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, std::__1::vector<DB::SortColumnDescription, std::__1::allocator<DB::SortColumnDescription> > const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x113e5156 in /usr/bin/clickhouse
[zm-uat-118-24] 2020.11.16 20:01:09.459071 [ 18528 ] <Fatal> BaseDaemon: 4. DB::getFilterMask(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, unsigned long, std::__1::vector<DB::SortColumnDescription, std::__1::allocator<DB::SortColumnDescription> > const&, unsigned long, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 15ul, 16ul>&) @ 0x113e5156 in
```

Can anyone help me ？？？ please
This sql caused me a production accident because the clickHouse service was directly down

When I try to connect again, an error is reported：

```
Exception on client:
Code: 210. DB::NetException: Connection refused (127.0.0.1:9002)

Connecting to database system at 127.0.0.1:9002 as user default.
Code: 210. DB::NetException: Connection refused (127.0.0.1:9002)

[root@UAT-大数据-01:trace_log]20:04:43# clickhouse-client -h 127.0.0.1 --port 9002 -d default -m -u default --password default
ClickHouse client version 20.8.3.18.
Connecting to database default at 127.0.0.1:9002 as user default.
Code: 210. DB::NetException: Connection refused (127.0.0.1:9002)
```

image

image

image

image

and I test  reduce the parameter  ‘limit’  to  
```
select '1111' as name from query_log order by name limit 1000;
```
the strange thing is  Correct return，the clickHouse server is ok ！ 
I suspect that too much constant data caused the service to hang

then，I try to change the version to fix this problem，Here are some of my attempts and test results

version：19.17.10.1   PASS
sudo yum install clickhouse-server-common-19.17.10.1-1.el7.x86_64
sudo yum install clickhouse-common-static-19.17.10.1-1.el7.x86_64
sudo yum install clickhouse-server-19.17.10.1-1.el7.x86_64
sudo yum install clickhouse-client-19.17.10.1-1.el7.x86_64

version：20.3.15.133  PASS
sudo yum install clickhouse-server-common-20.3.15.133-1.el7.x86_64
sudo yum install clickhouse-common-static-20.3.15.133-1.el7.x86_64
sudo yum install clickhouse-server-20.3.15.133-1.el7.x86_64
sudo yum install clickhouse-client-20.3.15.133-1.el7.x86_64

version：20.5.4.40  FAIL 
sudo yum install clickhouse-server-common-20.5.4.40-1.el7.x86_64
sudo yum install clickhouse-common-static-20.5.4.40-1.el7.x86_64
sudo yum install clickhouse-server-20.5.4.40-1.el7.x86_64
sudo yum install clickhouse-client-20.5.4.40-1.el7.x86_64

version：20.6.6.7  FAIL
sudo yum install clickhouse-server-common-20.6.6.7-1.el7.x86_64
sudo yum install clickhouse-common-static-20.6.6.7-1.el7.x86_64
sudo yum install clickhouse-server-20.6.6.7-1.el7.x86_64
sudo yum install clickhouse-client-20.6.6.7-1.el7.x86_64

version：20.8.3.18  FAIL
sudo yum install clickhouse-server-common-20.8.3.18-1.el7.x86_64
sudo yum install clickhouse-common-static-20.8.3.18-1.el7.x86_64
sudo yum install clickhouse-server-20.8.3.18-1.el7.x86_64
sudo yum install clickhouse-client-20.8.3.18-1.el7.x86_64

I don’t understand why there are bugs when the version is updated ？？？

### PR DESCRIPTION
**Pull request by amosbird**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fix ColumnConst comparison which leads to crash. This fixed https://github.com/ClickHouse/ClickHouse/issues/17088 .

Detailed description / Documentation draft:

This bug seems to be there for quite some time but never gets triggered.

### CODE REVIEW

File: src/Columns/ColumnConst.cpp [hunk 1]
```diff
@@ -138,4 +138,12 @@ void ColumnConst::updateWeakHash32(WeakHash32 & hash) const
         value = intHashCRC32(data_hash, value);
 }
 
+void ColumnConst::compareColumn(
+    const IColumn & rhs, size_t, PaddedPODArray<UInt64> *, PaddedPODArray<Int8> & compare_results, int, int nan_direction_hint)
+    const
+{
+    Int8 res = compareAt(1, 1, rhs, nan_direction_hint);
```
Comment (alexey-milovidov) [inline src/Columns/ColumnConst.cpp:145]: It's guaranteed to be always zero.

**Review by alexey-milovidov — APPROVED** [review]

File: src/Columns/ColumnConst.cpp (hunk 1 above)
Comment (amosbird) [reply src/Columns/ColumnConst.cpp]: Hmm, I don't get it. Where do we cast that guarantee?

Comment (alexey-milovidov) [reply src/Columns/ColumnConst.cpp]: Sorry, I got it wrong..
