### PR TITLE
One more fix for vertical merges with text indexes

### LINKED ISSUE #93098: [CI crash] Vertical merge stage execution failure in MergeTask
<details><summary>Stack trace details</summary>

The sipHash64(st.trace_full) is 8151285217141855561
The trace is from the master or release branch: True

The query for CIDB to compare the trace with the known one:

```sql
WITH
    (
        SELECT groupArrayDistinct(cleanStackTrace(trace_full) AS trace) FROM default.stack_traces
        WHERE sipHash64(trace) IN (8151285217141855561, {ANOTHER_TRACE_HASH}) -- FIXME: replace with the known hash
    ) AS traces,
    1.97 AS alpha,
    stack_frame_weights AS (
        WITH
            (
                SELECT count()
                FROM default.stack_traces
                FINAL
            ) AS total,
            2.0 AS beta,
            3.7 AS gamma
        SELECT
            arrayJoin(cleanStackTrace(trace_full)) AS frame,
            countDistinct(trace_full) AS count,
            log(total / count) AS IDF,
            sigmoid(beta * (IDF - gamma)) AS weight
        FROM default.stack_traces
        FINAL
        GROUP BY frame
    ),
    (SELECT groupArray(weight) AS w, groupArray(frame) AS f FROM stack_frame_weights) AS weights,
    (trace -> arrayMap((_frame, pos) -> (pow(pos, -alpha) * arrayFirst(w, f -> (f = _frame), weights.w, weights.f)), trace, arrayEnumerate(trace))) AS get_trace_weights,
    (arr -> arrayStringConcat(arr, '\n')) AS joinArr

SELECT arraySimilarity(traces[1], traces[2], get_trace_weights(traces[1]) AS weights1, get_trace_weights(traces[2]) AS weights2) AS similarity,
    arrayLevenshteinDistanceWeighted(traces[1], traces[2], weights1, weights2),
    joinArr(traces[1]), joinArr(traces[2]), joinArr(weights1), joinArr(weights2)

```
</details>

The following new stack trace from CI Logs `system.crash_log` found:

```
   DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&)
   void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::basic_string_view<char, std::char_traits<char>>, bool)
   DB::UnionStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&)
   DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool)
   DB::MergeTask::VerticalMergeStage::createPipelineForReadingOneColumn(String const&) const
   DB::MergeTask::VerticalMergeStage::prepareVerticalMergeForOneColumn() const
   DB::MergeTask::VerticalMergeStage::executeVerticalMergeForAllColumns() const
   DB::MergeTask::VerticalMergeStage::execute()
   DB::MergeTask::execute()
   DB::MergePlainMergeTreeTask::executeStep()
   DB::StorageMergeTree::merge(bool, String const&, bool, bool, std::vector<String, std::allocator<String>> const&, bool, std::shared_ptr<DB::MergeTreeTransaction> const&, PreformattedMessage&, bool)
   DB::StorageMergeTree::optimize(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::IAST> const&, bool, bool, std::vector<String, std::allocator<String>> const&, bool, std::shared_ptr<DB::Context const>)
   DB::InterpreterOptimizeQuery::execute()
   DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&)
   DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum)
   DB::TCPHandler::runImpl()
   DB::TCPHandler::run()
   Poco::Net::TCPServerConnection::start()
   Poco::Net::TCPServerDispatcher::run()
   Poco::PooledThread::run()
   Poco::ThreadImpl::runnableEntry(void*)
```

Possible causes:  
- Incorrect column data processing during vertical merge
- Mismatch between block structure and expected data format
- Invalid column configuration in merge process
- Incorrect handling of data during column-wise merge
- Potential data corruption during merge operation

The stack trace appeared in the following checks:  
- [Stateless tests (amd_debug, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=ee92d9591b66d594709456b1fed266d69dfaf076&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_debug%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_debug%2C%20parallel%29)

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

In addition to #93073.
Fixes #93098.

### CODE REVIEW

File: src/Processors/QueryPlan/UnionStep.cpp [hunk 1]
```diff
@@ -55,7 +55,7 @@ QueryPipelineBuilderPtr UnionStep::updatePipeline(QueryPipelineBuilders pipeline
 
     for (auto & cur_pipeline : pipelines)
     {
-#if !defined(NDEBUG)
```
Comment (CurtizJ) [inline src/Processors/QueryPlan/UnionStep.cpp:58]: This case is already covered by test `03775_text_index_expressions.sql` with random settings for vertical merges. However, since we had an assertion only for the debug build and not for sanitizers here, this bug is rarely triggered, and it was not caught in the original PR.

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM
