### PR TITLE
Fix FileLog engine unnesessary create meta data directory when create table failed

### LINKED ISSUE #31962: FileLog is able to read files only in /var/lib/clickhouse/user_files/
```
touch /tmp/aaa.csv

CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
DB::Exception: The absolute data path should be inside `user_files_path`(/var/lib/clickhouse/user_files/). (BAD_ARGUMENTS)


CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV');
DB::Exception: Metadata files already exist by path: /var/lib/clickhouse/.filelog_storage_metadata/default/log, remove them manually if it is intended. (TABLE_METADATA_ALREADY_EXISTS)
```

### PR DESCRIPTION
**Pull request by ucasfl**
Changelog category (leave one):

- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix FileLog engine unnesessary create meta data directory when create table failed. Fix #31962.

### CODE REVIEW

File: tests/queries/0_stateless/02125_fix_storage_filelog.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV'); -- {serverError 36 }
+CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV'); -- {serverError 36 }
+CREATE TABLE log (A String) ENGINE= FileLog('/tmp/aaa.csv', 'CSV'); -- {serverError 36 }
```
Comment (kssenii) [inline tests/queries/0_stateless/02125_fix_storage_filelog.sql:3]: May be in this test after creating file log engine with incorrect path, test creating with correct path (so it would be same as in the issue)?

**Review by kssenii — APPROVED** [review]

File: tests/queries/0_stateless/02125_fix_storage_filelog.sql (hunk 1 above)
Comment (ucasfl) [reply tests/queries/0_stateless/02125_fix_storage_filelog.sql:3]: If creating with correct path after creating with incorrect path, it will success.

Comment (kssenii) [reply tests/queries/0_stateless/02125_fix_storage_filelog.sql:3]: I believe. Ok I see that is not easy to add such test because in will have to be .sh test and .sh test does not allow test hints to suppress expected error. Then ok as it is now.

Comment (kssenii) [reply tests/queries/0_stateless/02125_fix_storage_filelog.sql:3]: Hm, no, actually it is ok to add one more sh test. 
(I believe that it works, but it might get broken in the future again)

Comment (ucasfl) [reply tests/queries/0_stateless/02125_fix_storage_filelog.sql:3]: OK.
