### PR TITLE
Fix order by tuple in iceberg

### LINKED ISSUE #92977: Iceberg ORDER BY tuple assertion error
### Describe the bug

Easy to reproduce.

### How to reproduce

Run:
```sql
CREATE TABLE t0 (c0 Int, c1 Tuple(c2 Int)) ENGINE = IcebergLocal(local, path = '/var/lib/clickhouse/user_files/lakehouses/t0') ORDER BY (c0, c1);
```

### Error message and/or stacktrace

Stack trace:
```
clickhouse: contrib/abseil-cpp/absl/container/inlined_vector.h:366: auto absl::InlinedVector<std::shared_ptr<DB::IAST>, 7>::operator[](size_type)::(anonymous class)::operator()() const [T = std::shared_ptr<DB::IAST>, N = 7, A = std::allocator<std::shared_ptr<DB::IAST>>]: Assertion `false && "i < size()"' failed.
2025.12.24 09:12:13.090733 [ 3413467 ] {} <Trace> BaseDaemon: Received signal 6
2025.12.24 09:12:13.090785 [ 3413467 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.12.24 09:12:13.090802 [ 3413467 ] {} <Fatal> BaseDaemon: (version 26.1.1.125 (official build), build id: 079DC763182651C4390499825913CC43F84E4864, git hash: 52010622aa6adaf271b037483f475b532509df81, architecture: x86_64) (from thread 3413469) Received signal 6
2025.12.24 09:12:13.090808 [ 3413467 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.12.24 09:12:13.090809 [ 3413467 ] {} <Fatal> BaseDaemon: 
2025.12.24 09:12:13.090837 [ 3413467 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007d19d02a5fee 0x00007d19d0245e2e 0x00007d19d0228888 0x00007d19d02287f0 0x000064f91d97ee07 0x000064f91d981dce 0x000064f91d8c1ef6 0x000064f91b861d93 0x000064f91d6dc0a1 0x000064f92255c590 0x000064f92255c247 0x000064f9225593e8 0x000064f92255abc4 0x000064f922193904 0x000064f91f45d249 0x000064f91f456010 0x000064f91f463d32 0x000064f91f863168 0x000064f91f85c8d4 0x000064f9230aaf89 0x000064f9230c5fa4 0x000064f929554dce 0x000064f92955543b 0x000064f9294f593f 0x000064f9294f2fcf 0x00007d19d02a3d64 0x00007d19d03373bc
2025.12.24 09:12:13.090846 [ 3413467 ] {} <Fatal> BaseDaemon: ########################################
2025.12.24 09:12:13.090916 [ 3413467 ] {} <Fatal> BaseDaemon: (version 26.1.1.125 (official build), build id: 079DC763182651C4390499825913CC43F84E4864, git hash: 52010622aa6adaf271b037483f475b532509df81) (from thread 3413469) (query_id: daafcf2c-b10d-4658-85cb-d8677b8dd2d6) (query: CREATE TABLE t0 (c0 Int, c1 Tuple(c2 Int)) ENGINE = IcebergLocal(local, path = '/var/lib/clickhouse/user_files/lakehouses/t0') ORDER BY (c0, c1);) Received signal Aborted (6)
2025.12.24 09:12:13.090957 [ 3413467 ] {} <Fatal> BaseDaemon: 
2025.12.24 09:12:13.090985 [ 3413467 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007d19d02a5fee 0x00007d19d0245e2e 0x00007d19d0228888 0x00007d19d02287f0 0x000064f91d97ee07 0x000064f91d981dce 0x000064f91d8c1ef6 0x000064f91b861d93 0x000064f91d6dc0a1 0x000064f92255c590 0x000064f92255c247 0x000064f9225593e8 0x000064f92255abc4 0x000064f922193904 0x000064f91f45d249 0x000064f91f456010 0x000064f91f463d32 0x000064f91f863168 0x000064f91f85c8d4 0x000064f9230aaf89 0x000064f9230c5fa4 0x000064f929554dce 0x000064f92955543b 0x000064f9294f593f 0x000064f9294f2fcf 0x00007d19d02a3d64 0x00007d19d03373bc
2025.12.24 09:12:13.091033 [ 3413467 ] {} <Fatal> BaseDaemon: 3. pthread_kill@@GLIBC_2.34 @ 0x00000000000a5fee
2025.12.24 09:12:13.091066 [ 3413467 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x0000000000045e2e
2025.12.24 09:12:13.091093 [ 3413467 ] {} <Fatal> BaseDaemon: 5. abort @ 0x0000000000028888
2025.12.24 09:12:13.091126 [ 3413467 ] {} <Fatal> BaseDaemon: 6. __GI___assert_perror_fail @ 0x00000000000287f0
2025.12.24 09:12:13.148964 [ 3413467 ] {} <Fatal> BaseDaemon: 7.0. inlined from contrib/abseil-cpp/absl/container/inlined_vector.h:366: operator()
2025.12.24 09:12:13.149011 [ 3413467 ] {} <Fatal> BaseDaemon: 7.1. inlined from contrib/abseil-cpp/absl/container/inlined_vector.h:366: absl::lts_20250512::InlinedVector<std::shared_ptr<DB::IAST>, 7ul, std::allocator<std::shared_ptr<DB::IAST>>>::operator[](unsigned long)
2025.12.24 09:12:13.149041 [ 3413467 ] {} <Fatal> BaseDaemon: 7. src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp:744: DB::Iceberg::parseTransformAndColumn(std::shared_ptr<DB::IAST>, unsigned long) @ 0x000000001a977e07
2025.12.24 09:12:13.201849 [ 3413467 ] {} <Fatal> BaseDaemon: 8. src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp:837: DB::Iceberg::createEmptyMetadataFile(String, DB::ColumnsDescription const&, std::shared_ptr<DB::IAST>, std::shared_ptr<DB::IAST>, std::shared_ptr<DB::Context const>, unsigned long) @ 0x000000001a97adce
2025.12.24 09:12:13.254885 [ 3413467 ] {} <Fatal> BaseDaemon: 9. src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergMetadata.cpp:584: DB::IcebergMetadata::createInitial(std::shared_ptr<DB::IObjectStorage> const&, std::weak_ptr<DB::StorageObjectStorageConfiguration> const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::ColumnsDescription> const&, std::shared_ptr<DB::IAST>, std::shared_ptr<DB::IAST>, bool, std::shared_ptr<DataLake::ICatalog>, DB::StorageID const&) @ 0x000000001a8baef6
2025.12.24 09:12:13.341590 [ 3413467 ] {} <Fatal> BaseDaemon: 10. src/Storages/ObjectStorage/DataLakes/DataLakeConfiguration.h:121: DB::DataLakeConfiguration<DB::StorageLocalConfiguration, DB::IcebergMetadata>::create(std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context const>, std::optional<DB::ColumnsDescription> const&, std::shared_ptr<DB::IAST>, std::shared_ptr<DB::IAST>, bool, std::shared_ptr<DataLake::ICatalog>, DB::StorageID const&) @ 0x000000001885ad93
2025.12.24 09:12:13.370957 [ 3413467 ] {} <Fatal> BaseDaemon: 11. src/Storages/ObjectStorage/StorageObjectStorage.cpp:155: DB::StorageObjectStorage::StorageObjectStorage(std::shared_ptr<DB::StorageObjectStorageConfiguration>, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context const>, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>, DB::LoadingStrictnessLevel, std::shared_ptr<DataLake::ICatalog>, bool, bool, bool, std::shared_ptr<DB::IAST>, std::shared_ptr<DB::IAST>, bool, bool) @ 0x000000001a6d50a1
2025.12.24 09:12:13.413285 [ 3413467 ] {} <Fatal> BaseDaemon: 12. contrib/llvm-project/libcxx/include/__memory/construct_at.h:38: DB::StorageObjectStorage* std::construct_at[abi:se210105]<DB::StorageObjectStorage, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>, bool const&, bool, bool, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&, DB::StorageObjectStorage*>(DB::StorageObjectStorage*, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>&&, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>&&, bool const&, bool&&, bool&&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&) @ 0x000000001f555590
2025.12.24 09:12:13.455236 [ 3413467 ] {} <Fatal> BaseDaemon: 13.0. inlined from contrib/llvm-project/libcxx/include/__memory/construct_at.h:46: DB::StorageObjectStorage* std::__construct_at[abi:se210105]<DB::StorageObjectStorage, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>, bool const&, bool, bool, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&, DB::StorageObjectStorage*>(DB::StorageObjectStorage*, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>&&, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>&&, bool const&, bool&&, bool&&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&)
2025.12.24 09:12:13.455280 [ 3413467 ] {} <Fatal> BaseDaemon: 13.1. inlined from contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:302: void std::allocator_traits<std::allocator<DB::StorageObjectStorage>>::construct[abi:se210105]<DB::StorageObjectStorage, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>, bool const&, bool, bool, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&, 0>(std::allocator<DB::StorageObjectStorage>&, DB::StorageObjectStorage*, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>&&, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>&&, bool const&, bool&&, bool&&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&)
2025.12.24 09:12:13.455313 [ 3413467 ] {} <Fatal> BaseDaemon: 13.2. inlined from contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:162: __shared_ptr_emplace<std::shared_ptr<DB::StorageObjectStorageConfiguration> &, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context> &, const DB::StorageID &, const DB::ColumnsDescription &, const DB::ConstraintsDescription &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, std::optional<DB::FormatSettings> &, const DB::LoadingStrictnessLevel &, std::shared_ptr<DataLake::ICatalog>, const bool &, bool, bool, std::shared_ptr<DB::IAST> &, std::shared_ptr<DB::IAST> &, std::allocator<DB::StorageObjectStorage>, 0>
2025.12.24 09:12:13.455331 [ 3413467 ] {} <Fatal> BaseDaemon: 13. contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:736: std::shared_ptr<DB::StorageObjectStorage> std::allocate_shared[abi:se210105]<DB::StorageObjectStorage, std::allocator<DB::StorageObjectStorage>, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>, bool const&, bool, bool, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&, 0>(std::allocator<DB::StorageObjectStorage> const&, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>&&, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>&&, bool const&, bool&&, bool&&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&) @ 0x000000001f555247
2025.12.24 09:12:13.498267 [ 3413467 ] {} <Fatal> BaseDaemon: 14.0. inlined from contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:744: std::shared_ptr<DB::StorageObjectStorage> std::make_shared[abi:se210105]<DB::StorageObjectStorage, std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>, bool const&, bool, bool, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&, 0>(std::shared_ptr<DB::StorageObjectStorageConfiguration>&, std::shared_ptr<DB::IObjectStorage>&&, std::shared_ptr<DB::Context>&, DB::StorageID const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::optional<DB::FormatSettings>&, DB::LoadingStrictnessLevel const&, std::shared_ptr<DataLake::ICatalog>&&, bool const&, bool&&, bool&&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::IAST>&)
2025.12.24 09:12:13.498303 [ 3413467 ] {} <Fatal> BaseDaemon: 14. src/Storages/ObjectStorage/registerStorageObjectStorage.cpp:80: DB::(anonymous namespace)::createStorageObjectStorage(DB::StorageFactory::Arguments const&, std::shared_ptr<DB::StorageObjectStorageConfiguration>) @ 0x000000001f5523e8
2025.12.24 09:12:13.535829 [ 3413467 ] {} <Fatal> BaseDaemon: 15.0. inlined from src/Storages/ObjectStorage/registerStorageObjectStorage.cpp:372: operator()
2025.12.24 09:12:13.535866 [ 3413467 ] {} <Fatal> BaseDaemon: 15.1. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&>::type std::__invoke[abi:se210105]<DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&>(DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&)
2025.12.24 09:12:13.535891 [ 3413467 ] {} <Fatal> BaseDaemon: 15.2. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:334: std::shared_ptr<DB::IStorage> std::__invoke_void_return_wrapper<std::shared_ptr<DB::IStorage>, false>::__call[abi:se210105]<DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&>(DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&)
2025.12.24 09:12:13.535920 [ 3413467 ] {} <Fatal> BaseDaemon: 15.3. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: std::shared_ptr<DB::IStorage> std::__invoke_r[abi:se210105]<std::shared_ptr<DB::IStorage>, DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&>(DB::registerStorageIceberg(DB::StorageFactory&)::$_4&, DB::StorageFactory::Arguments const&)
2025.12.24 09:12:13.535955 [ 3413467 ] {} <Fatal> BaseDaemon: 15. contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000001f553bc4
2025.12.24 09:12:13.542573 [ 3413467 ] {} <Fatal> BaseDaemon: 16.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
2025.12.24 09:12:13.542596 [ 3413467 ] {} <Fatal> BaseDaemon: 16.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
2025.12.24 09:12:13.542629 [ 3413467 ] {} <Fatal> BaseDaemon: 16. src/Storages/StorageFactory.cpp:228: DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, DB::LoadingStrictnessLevel, bool) const @ 0x000000001f18c904
2025.12.24 09:12:13.590764 [ 3413467 ] {} <Fatal> BaseDaemon: 17. src/Interpreters/InterpreterCreateQuery.cpp:1964: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x000000001c456249
2025.12.24 09:12:13.653056 [ 3413467 ] {} <Fatal> BaseDaemon: 18. src/Interpreters/InterpreterCreateQuery.cpp:1742: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x000000001c44f010
2025.12.24 09:12:13.722776 [ 3413467 ] {} <Fatal> BaseDaemon: 19. src/Interpreters/InterpreterCreateQuery.cpp:2390: DB::InterpreterCreateQuery::execute() @ 0x000000001c45cd32
2025.12.24 09:12:13.766389 [ 3413467 ] {} <Fatal> BaseDaemon: 20. src/Interpreters/executeQuery.cpp:1748: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001c85c168
2025.12.24 09:12:13.817786 [ 3413467 ] {} <Fatal> BaseDaemon: 21. src/Interpreters/executeQuery.cpp:1972: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001c8558d4
2025.12.24 09:12:13.849821 [ 3413467 ] {} <Fatal> BaseDaemon: 22. src/Server/TCPHandler.cpp:774: DB::TCPHandler::runImpl() @ 0x00000000200a3f89
2025.12.24 09:12:13.902061 [ 3413467 ] {} <Fatal> BaseDaemon: 23. src/Server/TCPHandler.cpp:2862: DB::TCPHandler::run() @ 0x00000000200befa4
2025.12.24 09:12:13.905615 [ 3413467 ] {} <Fatal> BaseDaemon: 24. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000002654ddce
2025.12.24 09:12:13.909734 [ 3413467 ] {} <Fatal> BaseDaemon: 25. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000002654e43b
2025.12.24 09:12:13.913753 [ 3413467 ] {} <Fatal> BaseDaemon: 26. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000264ee93f
2025.12.24 09:12:13.917741 [ 3413467 ] {} <Fatal> BaseDaemon: 27. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000264ebfcf
2025.12.24 09:12:13.917773 [ 3413467 ] {} <Fatal> BaseDaemon: 28. ? @ 0x00000000000a3d64
2025.12.24 09:12:13.917795 [ 3413467 ] {} <Fatal> BaseDaemon: 29. __GI___clone3 @ 0x00000000001373bc
2025.12.24 09:12:14.148211 [ 3413467 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 413E36A6B0577CF0AA5DFB53465D2AC3)
2025.12.24 09:12:14.159398 [ 3413467 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.12.24 09:12:14.159595 [ 3413467 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, azure_truncate_on_insert = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, enable_positional_arguments = true, allow_nonconst_timezone_arguments = true, enable_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, use_skip_indexes = true, use_skip_indexes_on_data_read = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, max_execution_time = 60., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_drop_detached = true, enable_lightweight_delete = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, optimize_use_projections = true, optimize_use_projection_filtering = true, enable_lightweight_update = true, use_query_condition_cache = false, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, database_replicated_allow_replicated_engine_arguments = 1, allow_experimental_correlated_subqueries = true, keeper_max_retries = 15, enable_order_by_all = true, allow_named_collection_override_by_default = true, allow_experimental_delta_lake_writes = true, cluster_for_parallel_replicas = 'cluster0', parallel_replicas_for_non_replicated_merge_tree = true, allow_experimental_database_iceberg = true, allow_experimental_database_unity_catalog = true, allow_experimental_database_glue_catalog = true, allow_experimental_analyzer = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, enable_full_text_index = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_qbit_type = true, allow_experimental_database_hms_catalog = true, allow_experimental_insert_into_iceberg = true, allow_experimental_iceberg_compaction = true, allow_experimental_time_series_aggregate_functions = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_condition = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, allow_experimental_live_view = true, allow_experimental_shared_set_join = true, allow_experimental_object_type = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by scanhex12**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix order by tuple in iceberg. This closes https://github.com/ClickHouse/ClickHouse/issues/92977

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp [hunk 1]
```diff
@@ -741,7 +739,11 @@ std::pair<String, String> parseTransformAndColumn(ASTPtr object, size_t i)
         return parse_function(object);
     }
 
-    auto function_desc = object->children[0]->children[i]->children[0];
+    auto function_desc = object->children[0]->children[i];
+    if (auto * identifier = function_desc->as<ASTIdentifier>(); identifier)
+        return {"identity", identifier->name()};
+
+    function_desc = function_desc->children[0];
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp:749]: Let's also check that `!function_desc->children.empty()`

File: src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp [hunk 2]
```diff
@@ -741,7 +739,11 @@ std::pair<String, String> parseTransformAndColumn(ASTPtr object, size_t i)
         return parse_function(object);
     }
 
-    auto function_desc = object->children[0]->children[i]->children[0];
+    auto function_desc = object->children[0]->children[i];
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp:744]: `object->children[0]` here should be `ASTExpressionList`, right? As I remember this is usually checked with `as` before getting its children for ASTFunction

File: tests/integration/test_storage_iceberg_with_spark/test_writes_create_table.py [hunk 3]
```diff
@@ -110,3 +110,26 @@ def test_writes_create_table_bug_partitioning(started_cluster_iceberg_with_spark
...
+
+    TABLE_NAME = "test_writes_create_table_bug_tuple_" + storage_type + "_" + get_uuid_str()
+
+    create_iceberg_table(storage_type, instance, TABLE_NAME, started_cluster_iceberg_with_spark, "(x Int, y Tuple(c2 Int))", order_by="(x, y)", format_version=format_version)
+    instance.query(f"INSERT INTO {TABLE_NAME} VALUES (1, (2)), (1, (3));", settings={"allow_experimental_insert_into_iceberg": 1})
+    assert instance.query(f"SELECT * FROM {TABLE_NAME}") == '1\t(2)\n1\t(3)\n'
+
+    TABLE_NAME = "test_writes_create_table_bug_tuple_" + storage_type + "_" + get_uuid_str()
+
+    create_iceberg_table(storage_type, instance, TABLE_NAME, started_cluster_iceberg_with_spark, "(x Int, y Int)", order_by="(x ASC, y DESC)", format_version=format_version)
```
Comment (kssenii) [inline tests/integration/test_storage_iceberg_with_spark/test_writes_create_table.py:133]: let's also add empty order_by -- `ORDER BY tuple()`

File: src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp [hunk 4]
```diff
@@ -739,10 +739,13 @@ std::pair<String, String> parseTransformAndColumn(ASTPtr object, size_t i)
         return parse_function(object);
     }
 
+    chassert(!object->children.empty());
+    chassert(object->children[0]->as<ASTExpressionList>());
     auto function_desc = object->children[0]->children[i];
     if (auto * identifier = function_desc->as<ASTIdentifier>(); identifier)
         return {"identity", identifier->name()};
 
+    chassert(!function_desc->children.empty());
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/Utils.cpp:748]: I'd prefer a full exception instead of just assert to avoid crashes in non-debug build, but ok

**Review by kssenii — APPROVED** [review]
