### PR TITLE
Disallow configuring compression CODECs for alias columns

### LINKED ISSUE #47332: Alias columns should not allow codec
**Column ALIAS should not allow codec**
Alias column (as a non-materialized one) should probably not allow adding codec

**How to reproduce**
* server version: ClickHouse server version 22.12.3 revision 54461.
* client: ClickHouse client version 22.12.3.5 (official build).
* Non-default settings: seems none relevant
* Sample data - unnecessary
* Queries to run:
```
create database if not exists tmp;

create table if not exists tmp.alias_column_should_not_allow_compression ( user_id UUID, user_id_hashed ALIAS (cityHash64(user_id)))
engine MergeTree
partition by tuple()
order by tuple()
;

/* -- generate alters
select --name, type,
    'alter table '|| database || '.' || table || ' modify column `' || name || '` ' || type || ' codec(LZ4HC(1));'
from system.columns where database = 'tmp' and table = 'alias_column_should_not_allow_compression' and compression_codec = ''
;
*/

alter table tmp.alias_column_should_not_allow_compression modify column `user_id_hashed` UInt64 codec(LZ4HC(1));
-- performed ok, though I understand that it makes no sense for alias - missed in bulk operation and no possibility to override on table's MergeTree settings level for default

detach table tmp.alias_column_should_not_allow_compression;

attach table tmp.alias_column_should_not_allow_compression;
-- throws error (same for server restart - loops daemon startup)
-- Received exception from server (version 22.12.3):
-- Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Cannot specify codec for column type ALIAS. (BAD_ARGUMENTS)
```

**Expected behavior**
I suppose best here - is to throw on alter attempt (but disregard of codec on attach/operation of alias column is an option as well)

---

**Additional context**
```-- also related minor issues:
-- 1 - how to drop table in such situation? or remove replica?
drop table tmp.alias_column_should_not_allow_compression;
-- returns 
-- Received exception from server (version 22.12.3):
-- Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table tmp.alias_column_should_not_allow_compression doesn't exist. (UNKNOWN_TABLE)
create or replace table tmp.alias_column_should_not_allow_compression ( user_id UUID, user_id_hashed ALIAS (cityHash64(user_id)))
engine MergeTree
partition by tuple()
order by tuple()
;
-- returns:
-- Received exception from server (version 22.12.3):
-- Code: 57. DB::Exception: Received from localhost:9000. DB::Exception: Table `tmp`.`alias_column_should_not_allow_compression` already exists (detached). (TABLE_ALREADY_EXISTS)
replace table tmp.alias_column_should_not_allow_compression ( user_id UUID, user_id_hashed ALIAS (cityHash64(user_id)))
engine MergeTree
partition by tuple()
order by tuple()
;
-- returns:
-- Received exception from server (version 22.12.3):
-- Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table `tmp`.`alias_column_should_not_allow_compression` doesn't exist. (UNKNOWN_TABLE)

-- *if there is a way do it by SQL - please let me know (we resolved only via manipulations with ZK and afterwadrs restore of replica)


-- 2 - exception readability
create table if not exists tmp.alias_column_should_not_allow_compression_2 ( user_id UUID, user_id_hashed ALIAS (cityHash64(user_id)))
engine MergeTree
partition by tuple()
order by tuple()
;

alter table tmp.alias_column_should_not_allow_compression_2 modify column if exists `user_id_hashed` remove CODEC;
-- if column has no codec - throws: ...doesn't have TTL ... - may be would be better readable if parametrized like ...doesn't have {item_property_to_remove}...
-- Received exception from server (version 22.12.3):
-- Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Column `user_id_hashed` doesn't have TTL, cannot remove it. (BAD_ARGUMENTS)
```

### PR DESCRIPTION
**Pull request by tsolodov**
### Changelog category:
- Bug Fix

### Changelog entry:
Added validation for `ALTER TABLE MODIFY COLUMN`: if CODEC is specified and modified column is alias to another column - throw an exception. Closes #47332.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
This is an automated comment for commit e49842ff6ce32864983f3ed6164fbe5c289eb94d with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/49363/e49842ff6ce32864983f3ed6164fbe5c289eb94d/ci_running.html)
The overall status of the commit is 🔴 failure

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🔴 failure</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/AlterCommands.cpp [hunk 1]
```diff
@@ -1090,7 +1090,14 @@ void AlterCommands::validate(const StoragePtr & table, ContextPtr context) const
                                                              "in a single ALTER query", backQuote(column_name));
 
             if (command.codec)
```
Comment (vmarora) [inline src/Storages/AlterCommands.cpp:1092]: It seems that the code above this in line 1076 is already doing a loop over all_columns. Would it more efficient if this new loop is merged with above? Something like is_alias is set as well in the loop at line 1076.

Comment (tsolodov) [reply src/Storages/AlterCommands.cpp:1092]: thanks, removed loop from the logic

**Review by nikitamikhaylov — APPROVED** [review]

File: src/Storages/ColumnsDescription.cpp [hunk 2]
```diff
@@ -659,6 +659,12 @@ bool ColumnsDescription::hasPhysical(const String & column_name) const
         it->default_desc.kind != ColumnDefaultKind::Alias && it->default_desc.kind != ColumnDefaultKind::Ephemeral;
 }
 
+bool ColumnsDescription::hasAlias(const String & column_name) const
+{
+    auto it = columns.get<1>().find(column_name);
+    return it->default_desc.kind == ColumnDefaultKind::Alias;
```
Comment (alexey-milovidov) [inline src/Storages/ColumnsDescription.cpp:665]: Is it guaranteed that the column is found?
Then, maybe we can use `at` instead of `find`?
Otherwise, check for `it`.

Comment (alexey-milovidov) [reply src/Storages/ColumnsDescription.cpp:665]: I see checks for `end()` in the methods above and below.

File: tests/queries/0_stateless/02725_alias_columns_should_not_allow_compression_codec.sql [hunk 3]
```diff
@@ -0,0 +1,7 @@
+drop table if exists alias_column_should_not_allow_compression;
+create table if not exists alias_column_should_not_allow_compression ( user_id UUID, user_id_hashed ALIAS (cityHash64(user_id))) engine=MergeTree() order by tuple();
+create table if not exists alias_column_should_not_allow_compression_fail ( user_id UUID, user_id_hashed ALIAS (cityHash64(user_id)) codec(LZ4HC(1))) engine=MergeTree() order by tuple(); -- { serverError BAD_ARGUMENTS }
+alter table alias_column_should_not_allow_compression modify column user_id codec(LZ4HC(1));
+alter table alias_column_should_not_allow_compression modify column user_id_hashed codec(LZ4HC(1)); -- { serverError BAD_ARGUMENTS }
+alter table alias_column_should_not_allow_compression add column user_id_hashed_1 UInt64 ALIAS (cityHash64(user_id)) codec(LZ4HC(1)); -- { serverError BAD_ARGUMENTS }
+
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02725_alias_columns_should_not_allow_compression_codec.sql:7]: `drop table` at the end (this makes sense when you run a single test manually)

Comment (nikitamikhaylov) [reply tests/queries/0_stateless/02725_alias_columns_should_not_allow_compression_codec.sql:7]: There is a `drop table` at the top.

File: src/Storages/ColumnsDescription.cpp (hunk 2 above)
Comment (nikitamikhaylov) [reply src/Storages/ColumnsDescription.cpp:665]: Exactly, that code looks suspicious, but seems like here we have an invariant.

Comment (tsolodov) [reply src/Storages/ColumnsDescription.cpp:665]: Thanks @alexey-milovidov , I will look into this

File: tests/queries/0_stateless/02725_alias_columns_should_not_allow_compression_codec.sql (hunk 3 above)
Comment (tsolodov) [reply tests/queries/0_stateless/02725_alias_columns_should_not_allow_compression_codec.sql]: running `code/ClickHouse//tests/clickhouse-test 02725_alias_columns_should_not_allow_compression_codec` would keep table in runtime. Added drop table.
