### PR TITLE
fixes ClickHouse/ClickHouse#87082 - materialized views to use database where they were created as context

### LINKED ISSUE #87082: materialized views do not use their namespace when calling nested parameterized views, leading to UNKNOWN_FUNCTION unless explicitly qualifying nested views
### Company or project name

fintech

### Describe what's wrong

When calling a parameterized view from a materialized view, we expect that the name of the parameterized view does not need to be qualified, and upon execution it will try finding the parameterized view in the same database/namespace in which materialized view was created.

Instead, we observe the UNKNOWN_FUNCTION error on server side during scheduled execution, and querying the materialized view returns empty result.

This can be worked around by explicitly qualifying the name of the parameterized view with database name, but this is inconvenient because we expect to be able to apply the same set of scripts to different databases without having to templatize scripts/substitute db name.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

reproduces on latest i.e. 25.8.2.29
Consider the following repro:
1.  Setup

```
CREATE DATABASE db1;

use db1;
CREATE TABLE tbl1
(
    `id` int,
    `data` varchar(10)
)
ENGINE = MergeTree
ORDER BY id;

insert into tbl1 (*) values (1,'db1 data');

CREATE VIEW v1
AS SELECT
    id,
    data,
    {p:varchar(10)} as p
FROM tbl1;

CREATE MATERIALIZED VIEW mv1
REFRESH EVERY 1 MINUTE
ORDER BY id
AS SELECT
    id,
    data,
    p
FROM v1(p='db1 mv1'); -- NOTE: v1 is not qualified by db name

CREATE MATERIALIZED VIEW mv2
REFRESH EVERY 1 MINUTE
ORDER BY id
AS SELECT
    id,
    data,
    p
FROM db1.v1(p='db1 mv2');  -- NOTE: v1 is fully qualified by db name
```

2. Queries to illustrate/reproduce issue (after a short while - to give time to execute the materialized views)

2.1 this doesn't work as expected

```
SELECT *
FROM mv1

Ok.

0 rows in set. Elapsed: 0.001 sec.  --- <-- THIS IS UNEXPECTED

we expected
   ┌─id─┬─data─────┬─p───────┐
1. │  1 │ db1 data │ db1 mv1 │
   └────┴──────────┴─────────┘

but got empty results plus the following error in the server logs:

2025.09.13 00:28:00.210013 [ 32633526 ] {} <Error> executeQuery: Code: 46. DB::Exception: Unknown table function v1. (UNKNOWN_FUNCTION) (version 25.8.2.29 (official build)) (from 0.0.0.0:0) (comment: refresh of db1.mv1 (attempt 3/3)) (in query: (create target table)) (see separate field below for full stack trace)


```

2.2 by contrast, this does work, but is not a great workaround
```
select * from mv2

SELECT *
FROM mv2

Query id: 21b0887a-c28b-49bc-a1ea-3250a8526ee4

   ┌─id─┬─data─────┬─p───────┐
1. │  1 │ db1 data │ db1 mv2 │
   └────┴──────────┴─────────┘

1 row in set. Elapsed: 0.002 sec.  --- <-- THIS IS EXPECTED, but mv2 will always return data from db1, even if we apply the above script in another databse e.g. db2.

```

### Expected behavior

we expected that when clickhouse server executes mv1 query on a schedule, it "knows" that (this instance of) mv1 was created in db1, and searches for v1 in the context/namespace of db1, leading to correct data being returned.

instead, it appears to execute in default namespace, and thus cannot find v1 and logs the error message reported below.  
the materialized view remains empty.

### Error message and/or stacktrace

2025.09.13 00:28:00.210013 [ 32633526 ] {} <Error> executeQuery: Code: 46. DB::Exception: Unknown table function v1. (UNKNOWN_FUNCTION) (version 25.8.2.29 (official build)) (from 0.0.0.0:0) (comment: refresh of db1.mv1 (attempt 3/3)) (in query: (create target table)), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(String const&, int) @ 0x000000011360407c
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000001081dd92c
2. DB::Exception::Exception(String&&, int, String, bool) @ 0x0000000102ecc158
3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000102ecbd68
4. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x0000000103ae3bbc
5. DB::QueryAnalyzer::resolveTableFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&, bool) @ 0x000000010c43fd48
6. DB::QueryAnalyzer::resolveQueryJoinTreeNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::IdentifierResolveScope&, DB::QueryExpressionsAliasVisitor&) @ 0x000000010c461464
7. DB::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::IdentifierResolveScope&) @ 0x000000010c43723c
8. DB::QueryAnalyzer::resolve(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::Context const>) @ 0x000000010c436550
9. DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x000000010c435ba0
10. DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x000000010c3a66fc
11. DB::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) @ 0x000000010cae3e5c
12. DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x000000010cae2658
13. DB::InterpreterSelectQueryAnalyzer::getSampleBlock(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&) @ 0x000000010cae425c
14. DB::StorageMaterializedView::prepareRefresh(bool, std::shared_ptr<DB::Context>, std::optional<DB::StorageID>&) const @ 0x000000010f309658
15. DB::RefreshTask::executeRefreshUnlocked(bool, int, std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long long, std::ratio<1l, 1000000l>>>, Stopwatch const&, String const&, String&) @ 0x000000010fb33c40
16. DB::RefreshTask::refreshTask() @ 0x000000010fb307f0
17. DB::BackgroundSchedulePoolTaskInfo::execute(DB::BackgroundSchedulePool&) @ 0x000000010bd1a20c
18. DB::BackgroundSchedulePool::threadFunction() @ 0x000000010bd1da7c
19. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000010bd1ee5c
20. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000010835c274
21. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000108367dc8
22. _pthread_start @ 0x00000001885cbc0c
23. thread_start @ 0x00000001885c6b80

### Additional context

as explained above, the workaround with explicitly specifying the db name for any nested view used inside a materialized view is not great - because it severely complicates application of the same set of views to different databases

### PR DESCRIPTION
**Pull request by dk-github**
fixes ClickHouse/ClickHouse#87082 - materialized views to use database where they were created as context

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Materialized views now use the database where they were created as execution context, meaning that:
- it is possible to omit explicit database qualification on names referred in view's select query
- if no explicit database qualification is given, the same database where the materialized view was created is assumed

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.2.1.564`

### CODE REVIEW

**Comment by pamarcos** [comment]
Adding tests to verify this fixes the issue and to ensure we don't have any regressions would be nice

**Comment by dk-github** [comment]
hi @pamarcos , thanks for having a look!

Re illustrating that it fixes the issue:
- any advice on how best to add automated test for this? the error happens asynchronously on server side, in refresh task scheduled by the server on view creation or on restart, so just running some SQL statements without somehow waiting for refresh task to finish in background won't cut it...  
- I did test manually though, as in running the repro statements I shared in the issue description, and verifying that with the fix it works as expected - can share the evidence here in a comment

Re regression:
- my understanding was that, now that you have added "can be tested" label, the regression tests will run - and if any fail, I will look at them and see if this was due to my change
- if there is anything else to it that I need to do - please let me know

**Comment by dk-github** [comment]
ok, I can see a bunch of tests in test_refreshable_mv/ failing - will fix those, and take as an inspiration to add a new test for this issue

**Comment by pamarcos** [comment]
> * my understanding was that, now that you have added "can be tested" label, the regression tests will run - and if any fail, I will look at them and see if this was due to my change

You're understanding is right. Sorry I didn't elaborate. I didn't meant your change breaking something. I meant a test for expected behavior so that we don't break it again in the future.

>ok, I can see a bunch of tests in test_refreshable_mv/ failing - will fix those, and take as an inspiration to add a new test for this issue

I was checking [here](https://play.clickhouse.com/play?user=play#V0lUSAogICAgMzAgQVMgbGFzdF9kYXlzX3RvX2NoZWNrLAogICAgMTAwIEFTIG1heF90ZXN0c190b19zaG93LAogICAgNSBhcyBtYXhfcHJzX3RvX3Nob3csCiAgICA3MCBBUyB0ZXN0X25hbWVfbWF4X2xlbmd0aApTRUxFQ1QKICAgIGNoZWNrX3N0YXJ0X3RpbWUsCiAgICBwdWxsX3JlcXVlc3RfbnVtYmVyLAogICAgdGVzdF9zdGF0dXMsCiAgICByZXBvcnRfdXJsLAogICAgcHVsbF9yZXF1ZXN0X3VybApGUk9NIGNoZWNrcwpXSEVSRQogICAgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIGludGVydmFsIGxhc3RfZGF5c190b19jaGVjayBkYXkKICAgIEFORCAodGVzdF9zdGF0dXMgPSAnRkFJTCcpCiAgICBBTkQgdGVzdF9uYW1lIElMSUtFICcldGVzdF9yZWZyZXNoYWJsZV9tdiUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQwpMSU1JVCBtYXhfdGVzdHNfdG9fc2hvdw==) whether it was a flaky test, but it's not, so it seems your changes are the ones causing that failure.

**Comment by dk-github** [comment]
apologies for the delay from my side, I still plan to revisit and  fix the tests . my issue is that they apparently require a linux environment with iptables, whereas so far I was set up on MacOS.  so I need to set up a Linux container and re-setup in there to actually be able to run those tests and see what's failing. will update here once I manage to get to it.

**Comment by dk-github** [comment]
@pamarcos I have merged in latest master and fixed the issues previously flagged by the failing tests. A few things worth noting are:

- There were a couple of edge cases, on startup and on restoring from archive, where the new logic was failing because the DDL for the views was being analysed/validated before the actual databases existed. 
    - The fix was to introduce an optional parameter to skip the checks in such edge cases.
- I believe this logic is fully in line with both 
    - the previous implementation (which was using global context where current database was set to default without validation, also as a special edge case), 
    - the general idea behind current implementation of bootstrapping/restoring (i.e. for some reason we need to analyse the MV's DDL before the actual databases are even created, this is done on best-effort basis and the actual execution is deferred to the moment when everything is set up, and then it is validated fully again)
- There are some failed tests in the latest CI run, but they appear to be a) unrelated to my changes b) pre-existing in other builds as well

Basically, from my side it looks good to go, but please let me know if you have any concerns/next steps

PS. Happy 2026!

File: tests/queries/0_stateless/03779_materialized_view_database_context.sql [hunk 1]
```diff
@@ -0,0 +1,66 @@
+-- Tags: no-parallel
```
Comment (pamarcos) [inline tests/queries/0_stateless/03779_materialized_view_database_context.sql]: I understand you added this because you're hardcoding database names. But we could use `{CLICKHOUSE_DATABASE:Identifier}` and `{CLICKHOUSE_DATABASE_1:Identifier}` instead so that they're random database names, allowing to execute the test in parallel.

File: tests/queries/0_stateless/03779_materialized_view_database_context.sql [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+CREATE DATABASE db1_03779;
+USE db1_03779;
+
+CREATE TABLE tbl1 (id Int32, data String) ENGINE = MergeTree ORDER BY id;
+INSERT INTO tbl1 VALUES (1, 'db1_data');
+
+-- Parameterized view in db1_03779
+CREATE VIEW v1 AS SELECT id, data, {p:String} as p FROM tbl1;
+
+-- REFRESH MV calling unqualified parameterized view (should use db1_03779 context)
```
Comment (pamarcos) [inline tests/queries/0_stateless/03779_materialized_view_database_context.sql]: I you want the MVs to use the underlying database the view was created in, why don't you change the DB to the other one before creating the MV? Otherwise, you're just testing that the `USE db` is working (which seems redundant since that's what `tests/queries/0_stateless/00101_materialized_views_and_insert_without_explicit_database.sql` is testing)

**Review by pamarcos — COMMENTED** [review]
I merged master into your branch to ensure we're running the CI with the updated fixes for flaky tests.

Apart of the nitpick Copilot pointed out of using `///` instead of `//` for comments, there's two things I see here:
- What about `ALTER TABLE ... MODIFY QUERY`? e.g.
```sql
ALTER TABLE db1_03779.mv1 MODIFY QUERY SELECT id, data, p, source FROM v2(p='after_alter');
```
- I think the tests can be improved to test what I understand this is trying to fix.

File: tests/queries/0_stateless/03779_materialized_view_database_context.sql (hunk 1 above)
Comment (dk-github) [reply tests/queries/0_stateless/03779_materialized_view_database_context.sql]: I tried, but the substitution didn't work correctly for queries inside the views. But I have now changed it to use shell, where substitution works on bash level - hope that's ok, and that enables the parallel run

File: tests/queries/0_stateless/03779_materialized_view_database_context.sql (hunk 2 above)
Comment (dk-github) [reply tests/queries/0_stateless/03779_materialized_view_database_context.sql]: Actually, for materialized views "USE db" wasn't working properly before the fix either - as in, it did create the actual view in correct database, but the crux of the issue we're trying to fix here was that all the actual syntax of the view's SQL and anything that was called from it was evaluated in global context, not in the context of that database where it was created (which is what one usually expects when writing SQL in a database). So even referring to objects in the same database required explicit database name qualifier, or else won't work from inside materialized view, even though it would work fine when executed in a client session. See the original issue where hopefully the example makes it clearer.
In this sense, the version of the test you reviewed already did test the actual fix just fine.  But the new shell version is now creating everything with explicit database name qualifier - hopefully that addresses your concern anyway.

Comment (dk-github) [reply tests/queries/0_stateless/03779_materialized_view_database_context.sql]: re ALTER TABLE ... MODIFY QUERY - good catch, thanks!  I concentrated on my own use case and didn't look carefully enough to realise that this MODIFY QUERY is even a thing, and that it uses a separate code path which needs the same fix - added now, and extended the test as well

File: src/Interpreters/Context.cpp [hunk 3]
```diff
@@ -3069,6 +3069,16 @@ void Context::setCurrentDatabase(const String & name)
     setCurrentDatabaseWithLock(name, lock);
 }
 
+void Context::setCurrentDatabaseUnchecked(const String & name)
+{
+    if (name.empty())
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Database name cannot be empty");
```
[the remark this answers is not in the document]
Comment (dk-github) [reply src/Interpreters/Context.cpp:3130]: I think this is not worth doing - will add more lines than it removes, and not add anything in terms of clarity

File: tests/queries/0_stateless/03779_materialized_view_database_context.sh [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+# Clean up
+$CLICKHOUSE_CLIENT --query "DROP DATABASE IF EXISTS $DB1"
+$CLICKHOUSE_CLIENT --query "DROP DATABASE IF EXISTS $DB2"
+
+# Setup db1 with table, parameterized view, and REFRESH MV
+$CLICKHOUSE_CLIENT --query "CREATE DATABASE $DB1"
+$CLICKHOUSE_CLIENT --query "CREATE TABLE $DB1.tbl1 (id Int32, data String) ENGINE = MergeTree ORDER BY id"
+$CLICKHOUSE_CLIENT --query "INSERT INTO $DB1.tbl1 VALUES (1, 'db1_data')"
+$CLICKHOUSE_CLIENT --query "CREATE VIEW $DB1.v1 AS SELECT id, data, {p:String} as p FROM $DB1.tbl1"
+$CLICKHOUSE_CLIENT --query "CREATE MATERIALIZED VIEW $DB1.mv1 REFRESH EVERY 1 SECOND ORDER BY id AS SELECT id, data, p FROM $DB1.v1(p='from_mv1_db1')"
```
Comment (pamarcos) [inline tests/queries/0_stateless/03779_materialized_view_database_context.sh]: I'm sorry, but shouldn't you test here and on the other reference in Line 30 the unqualified reference?

```sql
CREATE MATERIALIZED VIEW $DB1.mv1 REFRESH EVERY 1 SECOND ORDER BY id AS SELECT id, data, p FROM v1(p='from_mv1_db1')
```

That doesn't seem to work. If I understand the issue properly, I'd expect this test to work, and right now it doesn't:

```bash
#!/usr/bin/env bash
# Test that materialized views use the MV's database context (not session context)
# when resolving UNQUALIFIED parameterized view references at creation time.
#
# This is a regression test for issue #87082.
# The key difference from 03779_materialized_view_database_context.sh is that
# this test uses UNQUALIFIED view references (v1 instead of $DB1.v1) to verify
# that the database resolution uses the MV's target database.

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

DB1="${CLICKHOUSE_DATABASE}_1"
DB2="${CLICKHOUSE_DATABASE}_2"

# Clean up
$CLICKHOUSE_CLIENT --query "DROP DATABASE IF EXISTS $DB1"
$CLICKHOUSE_CLIENT --query "DROP DATABASE IF EXISTS $DB2"

# Setup db1 with table and parameterized view
$CLICKHOUSE_CLIENT --query "CREATE DATABASE $DB1"
$CLICKHOUSE_CLIENT --query "CREATE TABLE $DB1.tbl1 (id Int32, data String) ENGINE = MergeTree ORDER BY id"
$CLICKHOUSE_CLIENT --query "INSERT INTO $DB1.tbl1 VALUES (1, 'db1_data')"
$CLICKHOUSE_CLIENT --query "CREATE VIEW $DB1.v1 AS SELECT id, data, {p:String} as p FROM $DB1.tbl1"

$CLICKHOUSE_CLIENT --query "CREATE DATABASE $DB2"
$CLICKHOUSE_CLIENT --query "USE DATABASE $DB2;"

# KEY TEST: Create MV in DB1 with UNQUALIFIED view reference "v1" (not "$DB1.v1")
# The unqualified v1 should resolve to DB1.v1 (MV's database), not the session's current database (DB2.v1)
$CLICKHOUSE_CLIENT --query "CREATE MATERIALIZED VIEW $DB1.mv1 REFRESH EVERY 1 SECOND ORDER BY id AS SELECT id, data, p FROM v1(p='from_mv1_db1')"
$CLICKHOUSE_CLIENT --query "SYSTEM WAIT VIEW $DB1.mv1"
$CLICKHOUSE_CLIENT --query "SELECT 'mv1_db1:', * FROM $DB1.mv1 ORDER BY id"

# Cleanup
$CLICKHOUSE_CLIENT --query "DROP DATABASE $DB1"
$CLICKHOUSE_CLIENT --query "DROP DATABASE $DB2"
```

File: tests/queries/0_stateless/03779_materialized_view_database_context.sql (hunk 2 above)
Comment (pamarcos) [reply tests/queries/0_stateless/03779_materialized_view_database_context.sql]: I made a new comment where I thought was relevant: https://github.com/ClickHouse/ClickHouse/pull/88193#discussion_r2695404606 with a test example of what I meant

**Comment by pamarcos** [comment]
Some tests failed: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88193&sha=33b6fdfdb95d104d4e1514715b11084a21b85e49&name_0=PR

```
FAIL	03779_materialized_view_database_context retry_failed[cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMzc3OV9tYXRlcmlhbGl6ZWRfdmlld19kYXRhYmFzZV9jb250ZXh0JwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnU3RhdGVsZXNzIHRlc3RzIChhbWRfYmluYXJ5LCBvbGQgYW5hbHl6ZXIsIHMzIHN0b3JhZ2UsIERhdGFiYXNlUmVwbGljYXRlZCwgcGFyYWxsZWwpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwIE9SIGJhc2VfcmVmIElOICgnbWFzdGVyJykpCiAgICBBTkQgdGVzdF9jb250ZXh0X3JhdyBMSUtFICclaGF2aW5nIHN0ZGVycm9yJScKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)	17.39
2026-01-13 16:26:10 Reason: having stderror:  
2026-01-13 16:26:10 [7ea13ad1ee08] 2026.01.13 14:26:01.323643 [ 293443 ] {0ff889a8-6707-4ca5-a695-ef4f661f35a7} <Error> executeQuery: Code: 46. DB::Exception: Unknown table function v2:  or incorrect parameterized view. (UNKNOWN_FUNCTION) (version 26.1.1.468) (from [::1]:56538) (comment: 03779_materialized_view_database_context.sh-test_79y7c1ek) (query 1, line 1) (in query: ALTER TABLE test_79y7c1ek_1.mv1 MODIFY QUERY SELECT id, data, p FROM v2(p='modified_query_db1')), Stack trace (when copying this message, always include the lines below):
2026-01-13 16:26:10 
2026-01-13 16:26:10 0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000022307332
2026-01-13 16:26:10 1. ./ci/tmp/build/./src/Common/Exception.cpp:136: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013666da9
2026-01-13 16:26:10 2. ./src/Common/Exception.h:172: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b1ec20e
2026-01-13 16:26:10 3. ./src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b1ebcc9
2026-01-13 16:26:10 4. ./src/Common/Exception.h:190: DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000b1fb8f6
2026-01-13 16:26:10 5. ./ci/tmp/build/./src/TableFunctions/TableFunctionFactory.cpp:50: DB::TableFunctionFactory::get(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>) const @ 0x000000001793d8f4
2026-01-13 16:26:10 6. ./ci/tmp/build/./src/Interpreters/Context.cpp:2595: DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, DB::ASTSelectQuery const*) @ 0x0000000019406403
2026-01-13 16:26:10 7. ./ci/tmp/build/./src/Interpreters/JoinedTables.cpp:221: DB::JoinedTables::getLeftTableStorage() @ 0x00000000197167f6
2026-01-13 16:26:10 8. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQuery.cpp:582: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x00000000196b00d8
2026-01-13 16:26:10 9. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQuery.cpp:330: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196af291
2026-01-13 16:26:10 10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:759: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196eaf92
2026-01-13 16:26:10 11. ./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:167: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196e9c10
2026-01-13 16:26:10 12. ./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:56: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196e8b42
2026-01-13 16:26:10 13. ./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:300: DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x00000000196eb97d
2026-01-13 16:26:10 14. ./ci/tmp/build/./src/Storages/AlterCommands.cpp:872: DB::AlterCommand::apply(DB::StorageInMemoryMetadata&, std::shared_ptr<DB::Context const>) const @ 0x000000001beb6ea0
2026-01-13 16:26:10 15. ./ci/tmp/build/./src/Storages/AlterCommands.cpp:1241: DB::AlterCommands::apply(DB::StorageInMemoryMetadata&, std::shared_ptr<DB::Context const>) const @ 0x000000001bebb681
2026-01-13 16:26:10 16. ./ci/tmp/build/./src/Storages/StorageMaterializedView.cpp:673: DB::StorageMaterializedView::alter(DB::AlterCommands const&, std::shared_ptr<DB::Context const>, std::unique_lock<std::timed_mutex>&) @ 0x000000001c0288ee
2026-01-13 16:26:10 17. ./ci/tmp/build/./src/Interpreters/InterpreterAlterQuery.cpp:275: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x0000000019645c4d
2026-01-13 16:26:10 18. ./ci/tmp/build/./src/Interpreters/InterpreterAlterQuery.cpp:85: DB::InterpreterAlterQuery::execute() @ 0x000000001964344d
2026-01-13 16:26:10 19. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1738: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x0000000019a42146
2026-01-13 16:26:10 20. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1962: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000019a3d7d1
2026-01-13 16:26:10 21. ./ci/tmp/build/./src/Server/TCPHandler.cpp:774: DB::TCPHandler::runImpl() @ 0x000000001ce5f108
2026-01-13 16:26:10 22. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2867: DB::TCPHandler::run() @ 0x000000001ce7cce3
2026-01-13 16:26:10 23. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000223cce47
2026-01-13 16:26:10 24. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000223cd47e
2026-01-13 16:26:10 25. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000002236643f
2026-01-13 16:26:10 26. ./base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000022363a91
2026-01-13 16:26:10 27. ? @ 0x0000000000094ac3
2026-01-13 16:26:10 28. ? @ 0x00000000001268c0
2026-01-13 16:26:10 
2026-01-13 16:26:10 Received exception from server (version 26.1.1):
2026-01-13 16:26:10 Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table function v2:  or incorrect parameterized view. (UNKNOWN_FUNCTION)
2026-01-13 16:26:10 (query: ALTER TABLE test_79y7c1ek_1.mv1 MODIFY QUERY SELECT id, data, p FROM v2(p='modified_query_db1'))
2026-01-13 16:26:10 [7ea13ad1ee08] 2026.01.13 14:26:03.552526 [ 42956 ] {6e6c302b-cb72-4da3-a4a3-df5b3114f5c2} <Error> executeQuery: Code: 46. DB::Exception: Unknown table function v2:  or incorrect parameterized view. (UNKNOWN_FUNCTION) (version 26.1.1.468) (from [::1]:40774) (comment: 03779_materialized_view_database_context.sh-test_79y7c1ek) (query 1, line 1) (in query: ALTER TABLE test_79y7c1ek_2.mv1 MODIFY QUERY SELECT id, data, p FROM v2(p='modified_query_db2')), Stack trace (when copying this message, always include the lines below):
2026-01-13 16:26:10 
2026-01-13 16:26:10 0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000022307332
2026-01-13 16:26:10 1. ./ci/tmp/build/./src/Common/Exception.cpp:136: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000013666da9
2026-01-13 16:26:10 2. ./src/Common/Exception.h:172: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b1ec20e
2026-01-13 16:26:10 3. ./src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b1ebcc9
2026-01-13 16:26:10 4. ./src/Common/Exception.h:190: DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000b1fb8f6
2026-01-13 16:26:10 5. ./ci/tmp/build/./src/TableFunctions/TableFunctionFactory.cpp:50: DB::TableFunctionFactory::get(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>) const @ 0x000000001793d8f4
2026-01-13 16:26:10 6. ./ci/tmp/build/./src/Interpreters/Context.cpp:2595: DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, DB::ASTSelectQuery const*) @ 0x0000000019406403
2026-01-13 16:26:10 7. ./ci/tmp/build/./src/Interpreters/JoinedTables.cpp:221: DB::JoinedTables::getLeftTableStorage() @ 0x00000000197167f6
2026-01-13 16:26:10 8. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQuery.cpp:582: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x00000000196b00d8
2026-01-13 16:26:10 9. ./ci/tmp/build/./src/Interpreters/InterpreterSelectQuery.cpp:330: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196af291
2026-01-13 16:26:10 10. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:759: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196eaf92
2026-01-13 16:26:10 11. ./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:167: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196e9c10
2026-01-13 16:26:10 12. ./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:56: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000196e8b42
2026-01-13 16:26:10 13. ./ci/tmp/build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:300: DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x00000000196eb97d
2026-01-13 16:26:10 14. ./ci/tmp/build/./src/Storages/AlterCommands.cpp:872: DB::AlterCommand::apply(DB::StorageInMemoryMetadata&, std::shared_ptr<DB::Context const>) const @ 0x000000001beb6ea0
2026-01-13 16:26:10 15. ./ci/tmp/build/./src/Storages/AlterCommands.cpp:1241: DB::AlterCommands::apply(DB::StorageInMemoryMetadata&, std::shared_ptr<DB::Context const>) const @ 0x000000001bebb681
2026-01-13 16:26:10 16. ./ci/tmp/build/./src/Storages/StorageMaterializedView.cpp:673: DB::StorageMaterializedView::alter(DB::AlterCommands const&, std::shared_ptr<DB::Context const>, std::unique_lock<std::timed_mutex>&) @ 0x000000001c0288ee
2026-01-13 16:26:10 17. ./ci/tmp/build/./src/Interpreters/InterpreterAlterQuery.cpp:275: DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x0000000019645c4d
2026-01-13 16:26:10 18. ./ci/tmp/build/./src/Interpreters/InterpreterAlterQuery.cpp:85: DB::InterpreterAlterQuery::execute() @ 0x000000001964344d
2026-01-13 16:26:10 19. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1738: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x0000000019a42146
2026-01-13 16:26:10 20. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1962: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000019a3d7d1
2026-01-13 16:26:10 21. ./ci/tmp/build/./src/Server/TCPHandler.cpp:774: DB::TCPHandler::runImpl() @ 0x000000001ce5f108
2026-01-13 16:26:10 22. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2867: DB::TCPHandler::run() @ 0x000000001ce7cce3
2026-01-13 16:26:10 23. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x00000000223cce47
2026-01-13 16:26:10 24. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000223cd47e
2026-01-13 16:26:10 25. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000002236643f
2026-01-13 16:26:10 26. ./base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000022363a91
2026-01-13 16:26:10 27. ? @ 0x0000000000094ac3
2026-01-13 16:26:10 28. ? @ 0x00000000001268c0
2026-01-13 16:26:10 
2026-01-13 16:26:10 Received exception from server (version 26.1.1):
2026-01-13 16:26:10 Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table function v2:  or incorrect parameterized view. (UNKNOWN_FUNCTION)
2026-01-13 16:26:10 (query: ALTER TABLE test_79y7c1ek_2.mv1 MODIFY QUERY SELECT id, data, p FROM v2(p='modified_query_db2'))
2026-01-13 16:26:10 
2026-01-13 16:26:10 stdout:
2026-01-13 16:26:10 mv1_db1:	1	db1_data	from_mv1_db1
2026-01-13 16:26:10 mv1_db2:	2	db2_data	from_mv1_db2
2026-01-13 16:26:10 qualified:	2	db2_data	qualified_crossdb
2026-01-13 16:26:10 modified_mv1_db1:	1	db1_data	from_mv1_db1
2026-01-13 16:26:10 modified_mv1_db2:	2	db2_data	from_mv1_db2
2026-01-13 16:26:10 
2026-01-13 16:26:10 /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/test_79y7c1ek/03779_materialized_view_database_context.sh.debuglog:
2026-01-13 16:26:10 + [2026-01-13 16:25:52] [:9] DB1=test_79y7c1ek_1
2026-01-13 16:26:10 + [2026-01-13 16:25:52] [:10] DB2=test_79y7c1ek_2
2026-01-13 16:26:10 + [2026-01-13 16:25:52] [:13] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_79y7c1ek --log_comment 03779_materialized_view_database_context.sh-test_79y7c1ek --max_insert_threads 1 --group_by_two_level_threshold 584665 --group_by_two_level_threshold_bytes 50000000 --distributed_aggregation_memory_efficient 0 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 1024 --max_read_buffer_size 813162 --prefer_localhost_replica 1 --max_block_size 63354 --max_joined_block_size_rows 49555 --joined_block_split_single_row 0 --join_output_by_rowlist_perkey_rows_threshold 94 --max_threads 2 --optimize_append_index 1 --use_hedged_requests 0 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 15 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 9674430 --use_uncompressed_cache 1 --min_bytes_to_use_direct_io 10737418240 --min_bytes_to_use_mmap_io 588074974 --local_filesystem_read_method pread_threadpool --remote_filesystem_read_method threadpool --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 1 --allow_prefetched_read_pool_for_remote_filesystem 0 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 10 --filesystem_prefetch_min_bytes_for_single_read_task 1Mi --filesystem_prefetch_step_marks 0 --filesystem_prefetch_step_bytes 0 --compile_expressions 1 --compile_aggregate_expressions 1 --compile_sort_description 0 --merge_tree_coarse_index_granularity 15 --optimize_distinct_in_order 0 --max_bytes_before_remerge_sort 2006539996 --min_compress_block_size 1465431 --max_compress_block_size 1966313 --merge_tree_compact_parts_min_granules_to_multibuffer_read 124 --optimize_sorting_by_input_stream_proper
FAIL	Scrapping system tables [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdTY3JhcHBpbmcgc3lzdGVtIHRhYmxlcycKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0YXRlbGVzcyB0ZXN0cyAoYW1kX2JpbmFyeSwgb2xkIGFuYWx5emVyLCBzMyBzdG9yYWdlLCBEYXRhYmFzZVJlcGxpY2F0ZWQsIHBhcmFsbGVsKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBiYXNlX3JlZiBJTiAoJ21hc3RlcicpKQogICAgQU5EIHRlc3RfY29udGV4dF9yYXcgTElLRSAnJUNvZGU6JScKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)[issue](https://github.com/ClickHouse/ClickHouse/issues/93959)
```

File: tests/queries/0_stateless/03779_materialized_view_database_context.sh (hunk 4 above)
Comment (dk-github) [reply tests/queries/0_stateless/03779_materialized_view_database_context.sh]: Got it, thank you! yes, this is yet another place where the same fix was required - passing correct context to query analysis. (I must say, I didn't realize when I started it that there would be so many disparate places where the same internal sql is going to be analysed...) Hopefully this is the last place - thank you for spotting it!

So I added the fix for this case, and also modified the test to more clearly show what I originally fixed, then added your test practically verbatim at the end - it also passes now. the only thing I had to change was making sue that "use database $db2" is executed in one client invocation with the rest of it - but it is not super-important, it should work as you wrote it as well - with default session database

please have another look when you have time

**Comment by dk-github** [comment]
> Some tests failed: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88193&sha=33b6fdfdb95d104d4e1514715b11084a21b85e49&name_0=PR

I was confused because the first set of tests in teh link were clearly failing due to some (intermittent?) ZK issues, but looking at the second revealed that while my test passed in other configs, the "old analyser" config fails, and there is actually a whole bunch of "old analyser" codepaths which I had never encountered that needed a similar treatment to the one in "new" analyzer... thanks for spotting, it passes now when i run it locally with "old analyser" settings too...

**Comment by dk-github** [comment]
> There are some tests that fail quite consistently with runs for this PR:

okay, let me see if I can reproduce, or find anything  in the various logs that is more relevant than the exception bubbled up to the test runner... I see in the last update that only 3 are failing (below) - so will start with those ones


02232_allow_only_replicated_engine 
02514_database_replicated_no_arguments_for_rmt 
03248_create-same-table-concurrently-with-replicated-engine

**Comment by dk-github** [comment]
@pamarcos I have merged in a bunch of latest changes from main, which included fixes for various flakiness modes, and the latest run failed in just ONE test, which is:
- not one of the previous often-failing ones which you were worried about (those passed)
- not from the same build/architecture suite as last time, so any link to specific architecture seems even less likely
- doesn't seem to have anything to do with my changes
- has retry_ok label - not sure what that means, if not that it passed on retry?

I think this reinforces my argument that my changes are passing all tests and look good to go - but of course if you have any concerns left, please let me know what should my next steps be to get this over the line.

Thanks for your time!

**Review by pamarcos — APPROVED** [review]

**Review by pamarcos — APPROVED** [review]
Thanks @dk-github for your contribution. Much appreciated.
Sorry it took a while, but the current CI status is so-so and there was also the private CI that was failing due to your changes but it was impossible for you to identify or fix since you don't have access to it.
