### PR TITLE
Docker entrypoint: do not fail if keys are not present in config

### LINKED ISSUE #41200: Not found: https_port (version 22.9.1.1693 (official build))
Hello,

I just updated my local clickhouse version in docker to head (from 22.8.4.7) and now it refuses to start.
The error in the log is : 

Poco::Exception. Code: 1000, e.code() = 0, Not found: https_port (version 22.9.1.1693 (official build))

Is there any extra configuration to do for version 22.9 ?

Thanks,
Aubry

### PR DESCRIPTION
**Pull request by yakov-olkhovskiy**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixes issue when docker run will fail if "https_port" is not present in config.

closes #41200

### CODE REVIEW

File: docker/server/entrypoint.sh [hunk 1]
```diff
@@ -106,8 +106,8 @@ fi
 
 if [ -n "$(ls /docker-entrypoint-initdb.d/)" ] || [ -n "$CLICKHOUSE_DB" ]; then
     # port is needed to check if clickhouse-server is ready for connections
-    HTTP_PORT="$(clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key=http_port)"
-    HTTPS_PORT="$(clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key=https_port)"
+    HTTP_PORT="$(clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key=http_port --try)"
+    HTTPS_PORT="$(clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key=https_port --try)"
```
Comment (antonio2368) [inline docker/server/entrypoint.sh:111]:
```suggestion
    HTTP_PORT="$(clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key=http_port || true)"
    HTTPS_PORT="$(clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key=https_port || true)"

```

in other places this form is used which also works but I prefer it this way

**Review by antonio2368 — APPROVED** [review]
