### PR TITLE
Fix password leak in show create mysql table

### LINKED ISSUE #45023: Error hiding password [HIDDEN] in SHOW CREATE TABLE of MySQL table
Instead of a password, the login in the created SQL is closed.

```
> SHOW CREATE TABLE mydb1.table

CREATE TABLE mydb1.table
(
    ...
)
ENGINE = MySQL('127.0.0.1:3306', 'db1', 'table', '[HIDDEN]', 'password')
```

ClickHouse server version 22.12.1.1752 (official build).

### LINKED ISSUE #52723: MySQL connection password leaked in SHOW CREATE TABLE query
**Describe the unexpected behaviour**

CH masks the user instead of the password.

image

To reproduce:

- Create a MySQL database
- Create a MySQL table inside the MySQL database
- Run SHOW CREATE TABLE

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix password leak in show create mysql table

To reproduce:

- create a database `test_db` on mysql
- create a mysql database `test_db` on clickhouse
- create a table `test_tb` on the mysql in `test_db` database
- run `show create table test_db.test_tb` on clickhouse

I can reproduce locally with mariadb, some user using rds also report the same issue.

close #45023 close #52723

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by kssenii — APPROVED** [review]

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit 06229c1ba6816978d92f6cddf892e283c8704a0a with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52962/06229c1ba6816978d92f6cddf892e283c8704a0a/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by kssenii — APPROVED** [review]

**Comment by canhld94** [comment]
SQLite engine actually doesn't have password, but still add the logic, it's semantically more correct.

File: src/Databases/MySQL/DatabaseMySQL.cpp [hunk 1]
```diff
@@ -144,6 +144,7 @@ ASTPtr DatabaseMySQL::getCreateTableQueryImpl(const String & table_name, Context
     auto table_storage_define = database_engine_define->clone();
     {
         ASTStorage * ast_storage = table_storage_define->as<ASTStorage>();
+        ast_storage->engine->kind = ASTFunction::Kind::TABLE_ENGINE;
```
Comment (Algunenano) [inline src/Databases/MySQL/DatabaseMySQL.cpp:147]: Do you know why this doesn't this come from the clone and needs to be set explicitly?

Comment (canhld94) [reply src/Databases/MySQL/DatabaseMySQL.cpp:147]: Because the original `database_engine_define` is a database engine, so the type is `ASTFunction::Kind::DATABASE_ENGINE`.

**Comment by canhld94** [comment]
Integration tests failed:

```
test_zookeeper_config/test.py::test_chroot_with_different_root
test_zookeeper_config/test.py::test_chroot_with_same_root
```

Keeper timeout while starting, look unrelated
