### PR TITLE
Fix crash in function `formatRow` with `JSON` format and HTTP  interface

### LINKED ISSUE #62794: Segfault while running query with formatRow
**Describe what's wrong**

Running the following query against the HTTP endpoint will cause clickhouse to segfault:
```
SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(1000000))
```
When you run with less numbers it will not crash but give weird results:
```
❯ curl http://localhost:8123 -d "SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(15))"
{"number":"0"}\n
{"number":"1"}\n
{"number":"2"}\n
{"number":"3"}\n
{"number":"4"}\n
{"number":"5"}\n
{"number":"6"}\n
{"number":"7"}\n
{"number":"8"}\n
{"number":"9"}\n
{"number":"10"}\n
{"number":"11"}\0
\0\0\0\0\0\0\0\0\0\0\0\0\0\0��
���\0\0��|���\0\0\0\0\0
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
```

Running the query with clickhouse-client seems to work fine.

Using `FORMAT` also works fine:
```
❯ curl http://localhost:8123 -d "SELECT number FROM numbers(100000) FORMAT JSONEachRow"
...
{"number":"99998"}
{"number":"99999"}
```

**Does it reproduce on the most recent release?**

Yes.

**How to reproduce**

Run the latest image
```
docker run -p 8123:8123 clickhouse/clickhouse-server:latest
```
Then run the query using the HTTP endpoint:
```
curl http://localhost:8123 -d "SELECT formatRow('JSONEachRow', number) as test FROM (SELECT number FROM numbers(1000000))"
```

As soon as you run it, the container will exit with exit code 139.

### PR DESCRIPTION
**Pull request by CurtizJ**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed crash in function `formatRow` with `JSON` format in queries executed via the HTTP interface.

Fixes #62794.

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 59125601a1a23446a2db99e970bd8849013fa4c9 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/62840/59125601a1a23446a2db99e970bd8849013fa4c9/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Functions/formatRow.cpp [hunk 1]
```diff
@@ -38,8 +38,14 @@ class FunctionFormatRow : public IFunction
...
         , arguments_column_names(std::move(arguments_column_names_))
         , context(std::move(context_))
+        , format_settings(getFormatSettings(context))
     {
         FormatFactory::instance().checkFormatName(format_name);
+
+        /// We don't need handling exceptions while formatting as a row.
+        /// But it can be enabled in query sent via http interface.
+        format_settings.json.valid_output_on_exception = false;
+        format_settings.xml.valid_output_on_exception = false;
```
Comment (CurtizJ) [inline src/Functions/formatRow.cpp:48]: The problem is that the `PeekableWriteBuffer` is used when these settings are enabled, but it works incorrectly with `WriteBufferFromVector` which is used in function `formatRow`. Probably it's worth to fix that or forbid using `WriteBufferFromVector` and maybe some other write buffers for using with `PeekableWriteBuffer`. However this change makes sense anyway because `PeekableWriteBuffer` adds an overhead of extra copying.

**Review by alexey-milovidov — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @CurtizJ @alexey-milovidov — while reviewing this PR I found the following:

- **Coverage gap:** `formatRow('XML', ...)` over HTTP with `http_write_exception_in_output_format=1` untested — XML branch of the fix has zero coverage — https://github.com/ClickHouse/ClickHouse/pull/104090

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
