### PR TITLE
#32039 Make HDFS replication configurable in WriteBufferFromHDFSImpl#WriteBu…

### LINKED ISSUE #32039: Make HDFS replication configurable in WriteBufferFromHDFSImpl#WriteBufferFromHDFSImpl
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Current HDFS replication is zero in WriteBufferFromHDFSImpl#WriteBufferFromHDFSImpl and  when HDFS replication is zero in libhdfs3 client，it will set HDFS replication default num. 
Many of our users need adjust the replication num according to their own needs, so we recommend making HDFS replication configurable in WriteBufferFromHDFSImpl#WriteBufferFromHDFSImpl 
image

### PR DESCRIPTION
**Pull request by leosunli**
Signed-off-by:  leosunli <lisheng.sun08@gmail.com>

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow a user configured `hdfs_replication` parameter for DiskHdfs and StorageHdfs. Closes https://github.com/ClickHouse/ClickHouse/issues/32039.

### CODE REVIEW

File: src/Storages/HDFS/StorageHDFS.cpp [hunk 1]
```diff
@@ -202,7 +202,7 @@ class HDFSSink : public SinkToStorage
         const CompressionMethod compression_method)
         : SinkToStorage(sample_block)
     {
-        write_buf = wrapWriteBufferWithCompressionMethod(std::make_unique<WriteBufferFromHDFS>(uri, context->getGlobalContext()->getConfigRef()), compression_method, 3);
+        write_buf = wrapWriteBufferWithCompressionMethod(std::make_unique<WriteBufferFromHDFS>(uri, context->getGlobalContext()->getConfigRef(), 0), compression_method, 3);
```
Comment (kssenii) [inline src/Storages/HDFS/StorageHDFS.cpp:205]: Does it make sence to support for `StorageHDFS` too? You can just add a setting to `Core/Settings.h` and access it like `context->getSettingsRef().hdfs_dfs_replication`.

File: src/Disks/HDFS/DiskHDFS.cpp [hunk 2]
```diff
@@ -57,9 +57,11 @@ DiskHDFS::DiskHDFS(
     const String & hdfs_root_path_,
     SettingsPtr settings_,
     const String & metadata_path_,
-    const Poco::Util::AbstractConfiguration & config_)
+    const Poco::Util::AbstractConfiguration & config_,
+    const Settings & contextSettings_)
     : IDiskRemote(disk_name_, hdfs_root_path_, metadata_path_, "DiskHDFS", settings_->thread_pool_size)
     , config(config_)
+    , contextSettings(contextSettings_)
```
Comment (kssenii) [inline src/Disks/HDFS/DiskHDFS.cpp:64]: I would rather put the value `hdfs_replication` from context settings to disk settings (in getSettings function below), so there will be no need to save context settings in disk.

Comment (leosunli) [reply src/Disks/HDFS/DiskHDFS.cpp]: done. Could you help continue review it？ Thank you.

File: src/Core/Settings.h [hunk 3]
```diff
@@ -75,6 +75,7 @@ class IColumn;
     M(UInt64, s3_max_single_read_retries, 4, "The maximum number of retries during single S3 read.", 0) \
     M(UInt64, s3_max_redirects, 10, "Max number of S3 redirects hops allowed.", 0) \
     M(UInt64, s3_max_connections, 1024, "The maximum number of connections per server.", 0) \
+    M(UInt64, hdfs_replication, 3, "The actual number of replications can be specified when the hdfs file is created.", 0) \
```
Comment (kssenii) [inline src/Core/Settings.h:78]: I think by default it should be as it was -- 0.

Comment (leosunli) [reply src/Core/Settings.h]: done

**Review by kssenii — APPROVED** [review]

**Comment by kssenii** [comment]
@leosunli 

Please fix build, it fails now
```
Dec 02 20:29:57 /build/src/Disks/HDFS/DiskHDFS.cpp:177:13: error: no matching function for call to 'getSettings'
Dec 02 20:29:57             getSettings(config, config_prefix),
Dec 02 20:29:57             ^~~~~~~~~~~
Dec 02 20:29:57 /build/src/Disks/HDFS/DiskHDFS.cpp:145:35: note: candidate function not viable: requires 3 arguments, but 2 were provided
Dec 02 20:29:57 std::unique_ptr<DiskHDFSSettings> getSettings(const Poco::Util::AbstractConfiguration & config, const String & config_prefix, const Settings & setttings)
Dec 02 20:29:57                                   ^
Dec 02 20:29:57 /build/src/Disks/HDFS/DiskHDFS.cpp:178:36: error: use of undeclared identifier 'context'
Dec 02 20:29:57             metadata_disk, config, context.getSettingsRef());
Dec 02 20:29:57                                    ^
Dec 02 20:29:57 2 errors generated.

Dec 02 20:30:13 /build/src/Storages/HDFS/StorageHDFS.cpp:206:153: error: no member named 'getSettingsRef' in 'std::shared_ptr<const DB::Context>'; did you mean to use '->' instead of '.'?
Dec 02 20:30:13         write_buf = wrapWriteBufferWithCompressionMethod(std::make_unique<WriteBufferFromHDFS>(uri, context->getGlobalContext()->getConfigRef(), context.getSettingsRef().hdfs_replication), compression_method, 3);
Dec 02 20:30:13                                                                                                                                                         ^
Dec 02 20:30:13                                                                                                                                                         ->
Dec 02 20:30:13 1 error generated.
```

**Comment by ka1bi4** [comment]
Internal documentation ticket:DOCSUP-19957
