### PR TITLE
Fix segfault while inserting interval

### LINKED ISSUE #74299: INSERT INTERVAL SEGV
**Describe the bug**
Also very easy to reproduce.

**How to reproduce**
Run Fiddle: https://fiddle.clickhouse.com/593644e6-cba1-45bb-9909-b821a587052c

### PR DESCRIPTION
**Pull request by NamHoaiNguyen**
Resolves #74299

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash when inserting interval (issue #74299)

### CODE REVIEW

**Comment by NamHoaiNguyen** [comment]
Test had already been added. Please help to recheck. Thanks

File: tests/queries/0_stateless/00540_bad_data_types.sh [hunk 1]
```diff
@@ -23,3 +23,6 @@ echo
 $CLICKHOUSE_CLIENT --query="SELECT * FROM system.one WHERE CAST(NULL AS Nullable(UInt8))"
 $CLICKHOUSE_CLIENT --query="SELECT * FROM system.one WHERE 255"
 $CLICKHOUSE_CLIENT --query="SELECT * FROM system.one WHERE CAST(255 AS Nullable(UInt8))"
+
```
Comment (bharatnc) [inline tests/queries/0_stateless/00540_bad_data_types.sh:26]: New tests should generally be added to a new test file.

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 8e774e017ae774bd83aaa5d068faf455079f9877 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74478/8e774e017ae774bd83aaa5d068faf455079f9877/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/7aa3fddfa948e254c1a76245216df0c7e26c4c30/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/03312_issue_74299.sh [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#!/usr/bin/env bash
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+$CLICKHOUSE_CLIENT --query="CREATE TABLE t0 (c0 Int) engine=Memory"
+$CLICKHOUSE_CLIENT --query="INSERT INTO t0 values (1)"
+($CLICKHOUSE_CLIENT --query="INSERT INTO TABLE t0 (c0) VALUES (INTERVAL currentProfiles() MINUTE)" 2>/dev/null && echo "Expected failure") || true
+$CLICKHOUSE_CLIENT --query="SELECT * FROM t0 where 1"
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03312_issue_74299.sh:10]: Cannot this be written in a single sql script?

```
CREATE TABLE t0 (c0 Int) engine=Memory;

INSERT INTO t0 values (1);
INSERT INTO TABLE t0 (c0) VALUES (INTERVAL currentProfiles() MINUTE);
SELECT * FROM t0 where 1;
```

SQL scripts are more favorable then SH scripts, because they are simpler, faster and our fuzzer can use them as seed queries.

File: src/Interpreters/Context.cpp [hunk 3]
```diff
@@ -1841,12 +1841,20 @@ void Context::setCurrentProfiles(const SettingsProfilesInfo & profiles_info, boo
...
     return settings_constraints_and_current_profiles->current_profiles;
 }
 
 std::vector<UUID> Context::getEnabledProfiles() const
 {
     SharedLockGuard lock(mutex);
+    if (!settings_constraints_and_current_profiles)
+    {
+        return {};
+    }
```
Comment (antaljanosbenjamin) [inline src/Interpreters/Context.cpp:1857]:
```suggestion
    if (!settings_constraints_and_current_profiles)
        return {};
```

**Review by antaljanosbenjamin — CHANGES_REQUESTED** [review]

File: src/Interpreters/Context.cpp [hunk 4]
```diff
@@ -1841,12 +1841,20 @@ void Context::setCurrentProfiles(const SettingsProfilesInfo & profiles_info, boo
 std::vector<UUID> Context::getCurrentProfiles() const
 {
     SharedLockGuard lock(mutex);
+    if (!settings_constraints_and_current_profiles)
+    {
+        return {};
+    }
```
[the remark this answers is not in the document]
Comment (NamHoaiNguyen) [reply src/Interpreters/Context.cpp]: Code has been refactored

File: tests/queries/0_stateless/03312_issue_74299.sh (hunk 2 above)
Comment (NamHoaiNguyen) [reply tests/queries/0_stateless/03312_issue_74299.sh]: Insert test should fail during type checking and return an error code. This could cause a fast test failure, so I think we should fall back to using a shell script.

Comment (bharatnc) [reply tests/queries/0_stateless/03312_issue_74299.sh]: FWIW I think that you should still be able to do the same using a sql script and be able assert for the error code using error tags like [this](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02981_variant_type_function.sql#L9)  (for an example).

Comment (NamHoaiNguyen) [reply tests/queries/0_stateless/03312_issue_74299.sh]: Fall back to sql file. I didn't know the appearance of error tags until seeing TestHint.
Thanks for your help.

**Review by antaljanosbenjamin — COMMENTED** [review]
The changes look okay, however it seems like the master is not in a good state because of the failed tests. The flaky tests blocked the tests 2 group, which is necessary to merge. Could you please try to merge a recent master? I hope that flaky tests are fixed.

File: tests/queries/0_stateless/03312_issue_74299.sql [hunk 5]
```diff
@@ -0,0 +1,11 @@
+DROP TABLE if exists t0;
+
+CREATE TABLE t0 (c0 Int) ENGINE = Memory;
+
+INSERT INTO t0 values (1);
+
+SELECT * FROM t0 where 1;
+
+INSERT INTO TABLE t0 (c0) VALUES (INTERVAL currentProfiles() MINUTE); -- { clientError ILLEGAL_TYPE_OF_ARGUMENT }
```
Comment (rschu1ze) [inline tests/queries/0_stateless/03312_issue_74299.sql:9]: Afais, the inserted data doesn't need to be of type `INTERVAL` for the problem to reproduce. `VALUES (currentProfiles())` would be just fine.

(minor: `if exists` isn't needed in l. 11.)

(minor: why does the test need l. 5 and l. 7?)

Comment (NamHoaiNguyen) [reply tests/queries/0_stateless/03312_issue_74299.sql]: VALUES (currentProfiles()) works fine. I’ve fixed that.

**Comment by rschu1ze** [comment]
CI is in too bad shape (not clear if failures are related), let's wait another week or two and try again.

**Comment by antaljanosbenjamin** [comment]
Merged recent master, let's see what happens.

**Comment by NamHoaiNguyen** [comment]
I had already run unit tests at local and everything was fine. So, I think it is worth trying again :)

**Comment by rschu1ze** [comment]
ClickHouse Stateless tests (msan) [3/4]
- 00157_cache_dictionary: #75073

Other failures are infra-related.

**Review by antaljanosbenjamin — APPROVED** [review]

**Comment by Algunenano** [comment]
@antaljanosbenjamin Should we backport and close https://github.com/ClickHouse/ClickHouse/issues/74299?
