### PR TITLE
Fix column name clash with `join_using_top_level_identifier`

### LINKED ISSUE #73142: Use after free: Column identifier __table1.c0 is already registered
**Describe the bug**
Just run the Fiddle, related to `analyzer_compatibility_join_using_top_level_identifier` setting.

**How to reproduce**
Run Fiddle: https://fiddle.clickhouse.com/67278d49-b76e-4f68-a97d-735c8657df41

Stack trace:
```
0. std::exception::exception[abi:v15007]() @ 0x0000000018ed1bf4
1. base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x00000000389c75a0
2. src/Common/Exception.cpp:105: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000259c200b
3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000018d6f8b6
4. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x0000000018d9dbef
5. src/Planner/PlannerContext.cpp:36: DB::GlobalPlannerContext::createColumnIdentifier(DB::NameAndTypePair const&, std::shared_ptr<DB::IQueryTreeNode> const&) @ 0x0000000030e5934b
6. src/Planner/PlannerJoinTree.cpp:432: DB::buildJoinTreeQueryPlan(std::shared_ptr<DB::IQueryTreeNode> const&, DB::SelectQueryInfo const&, DB::SelectQueryOptions&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&, std::shared_ptr<DB::PlannerContext>&) @ 0x00000000320880c2
7. src/Planner/Planner.cpp:1546: DB::Planner::buildPlanForQueryNode() @ 0x000000003206197a
8. src/Planner/Planner.cpp:1300: DB::Planner::buildQueryPlanIfNeeded() @ 0x000000003205c6be
9. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:241: DB::InterpreterSelectQueryAnalyzer::getQueryPlan() @ 0x0000000032059299
10. src/Interpreters/executeQuery.cpp:1317: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000032553bb6
11. src/Interpreters/executeQuery.cpp:1535: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000003254e38e
12. src/Server/TCPHandler.cpp:656: DB::TCPHandler::runImpl() @ 0x0000000034fef63c
13. src/Server/TCPHandler.cpp:2598: DB::TCPHandler::run() @ 0x000000003501a58e
14. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000038b005c2
15. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000038b01292
16. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000038a5ec17
17. base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000038a5a50e
18. ? @ 0x00007ffff7ca1e2e
19. ? @ 0x00007ffff7d33a4
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Fixed a logical error in cases of column name clashes when analyzer_compatibility_join_using_top_level_identifier is enabled.

Close https://github.com/ClickHouse/ClickHouse/issues/73142

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit 9c9f7db2fd6017961ed10620e21772f3b636b4dd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75676/9c9f7db2fd6017961ed10620e21772f3b636b4dd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/0bfda2c21d37fdc82a9bff9ccadade7fe66e4d63/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 1]
```diff
@@ -5194,6 +5194,41 @@ void QueryAnalyzer::resolveJoin(QueryTreeNodePtr & join_node, IdentifierResolveS
...
+                            }
+                            else
+                            {
+                                throw Exception(ErrorCodes::LOGICAL_ERROR,
+                                    "Expected TableNode, TableFunctionNode, QueryNode or UnionNode, got {}: {}",
+                                    left_table_expression->getNodeTypeName(),
+                                    left_table_expression->formatASTForErrorMessage());
+                            }
+
+                            while (existing_columns.contains(identifier_full_name_))
```
Comment (tuanpach) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:5229]: I think we should keep `const String & identifier_full_name_,` as we don't change it in all cases.
And we create a new one when we need:

```
std::string final_identifier_full_name = identifier_full_name_;
while (existing_columns.contains(final_identifier_full_name))
final_identifier_full_name = "_" + final_identifier_full_name;

/// Create ColumnNode with expression from parent projection
return std::make_shared<ColumnNode>(
    NameAndTypePair{final_identifier_full_name, resolved_nodes.front()->getResultType()},
    resolved_nodes.front(),
    left_table_expression);
```

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 2]
```diff
@@ -5171,7 +5171,7 @@ void QueryAnalyzer::resolveJoin(QueryTreeNodePtr & join_node, IdentifierResolveS
               * Example: SELECT a + 1 AS b FROM (SELECT 1 AS a) t1 JOIN (SELECT 2 AS b) USING b
               * In this case `b` is not in the left table expression, but it is in the parent subquery projection.
               */
-            auto try_resolve_identifier_from_query_projection = [this](const String & identifier_full_name_,
+            auto try_resolve_identifier_from_query_projection = [this](String identifier_full_name_,
```
Comment (tuanpach) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:5174]: After these changes, this lambda function is pretty big. Should we move this to a separate method?
Or I think we move the logic of getting the final identifier_full_name_ in a separate function.

Comment (vdimir) [reply src/Analyzer/Resolve/QueryAnalyzer.cpp]: Extracted function `getColumnsFromTableExpression`

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 3]
```diff
@@ -5230,7 +5270,7 @@ void QueryAnalyzer::resolveJoin(QueryTreeNodePtr & join_node, IdentifierResolveS
             {
                 String extra_message;
                 const QueryNode * query_node = scope.scope_node ? scope.scope_node->as<QueryNode>() : nullptr;
-                if (settings[Setting::analyzer_compatibility_join_using_top_level_identifier] && query_node)
+                if (!settings[Setting::analyzer_compatibility_join_using_top_level_identifier] && query_node)
```
Comment (tuanpach) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:5273]: @vdimir 
This PR is to fix the column name clash with `join_using_top_level_identifier`. However, this condition has been updated to `!settings[Setting::analyzer_compatibility_join_using_top_level_identifier]`.

Could you elaborate on this change? Does it fix something else?

Comment (vdimir) [reply src/Analyzer/Resolve/QueryAnalyzer.cpp:5273]: Yes, this is not related to the main fix, juts typo I found in the mean time. This check only for displaying different error message.
As you may see from code below, if setting is disabled, we check if enabling can help to execute a query and then it's mentioned in the error message. Otherwise, show default error message, but behavior is the same - trowing an error,

Comment (tuanpach) [reply src/Analyzer/Resolve/QueryAnalyzer.cpp:5273]: I see. We eventually throw an error at the end of the block.

**Review by tuanpach — APPROVED** [review]

**Comment by vdimir** [comment]
Fuzzer falires reated to added test but bug is from master. Fixing in separately in https://github.com/ClickHouse/ClickHouse/pull/78848

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 4]
```diff
@@ -5203,6 +5212,42 @@ void QueryAnalyzer::resolveCrossJoin(QueryTreeNodePtr & cross_join_node, Identif
...
+            existing_columns.insert(column.name);
+    }
+    else
+    {
+        throw Exception(ErrorCodes::LOGICAL_ERROR,
+            "Expected TableNode, TableFunctionNode, QueryNode or UnionNode, got {}: {}",
+            table_expression->getNodeTypeName(),
+            table_expression->formatASTForErrorMessage());
+    }
+    return existing_columns;
```
Comment (tuanpach) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp:5248]:
```suggestion
    NameSet existing_columns;
    switch (table_expression->getNodeType())
    {
        case QueryTreeNodeType::TABLE: {
            const auto * table_node = table_expression->as<TableNode>();
            chassert(table_node);

            auto get_column_options = GetColumnsOptions(GetColumnsOptions::AllPhysical).withSubcolumns();
            for (const auto & column : table_node->getStorageSnapshot()->getColumns(get_column_options))
                existing_columns.insert(column.name);

            return existing_columns;
        }
        case QueryTreeNodeType::TABLE_FUNCTION: {
            const auto * table_function_node = table_expression->as<TableFunctionNode>();
            chassert(table_function_node);

            auto get_column_options = GetColumnsOptions(GetColumnsOptions::AllPhysical).withSubcolumns();
            for (const auto & column : table_function_node->getStorageSnapshot()->getColumns(get_column_options))
                existing_columns.insert(column.name);

            return existing_columns;
        }
        case QueryTreeNodeType::QUERY: {
            const auto * query_node = table_expression->as<QueryNode>();
            chassert(query_node);

            for (const auto & column : query_node->getProjectionColumns())
                existing_columns.insert(column.name);

            return existing_columns;
        }
        case QueryTreeNodeType::UNION: {
            const auto * union_node = table_expression->as<UnionNode>();
            chassert(union_node);

            for (const auto & column : union_node->computeProjectionColumns())
                existing_columns.insert(column.name);

            return existing_columns;
        }
        default:
            throw Exception(
                ErrorCodes::LOGICAL_ERROR,
                "Expected TableNode, TableFunctionNode, QueryNode or UnionNode, got {}: {}",
                table_expression->getNodeTypeName(),
                table_expression->formatASTForErrorMessage());
    }
```

I think checking type with `table_expression->getNodeType()` will reduce the cast operation and make it more readable.

File: src/Analyzer/JoinNode.cpp [hunk 5]
```diff
@@ -81,6 +81,10 @@ static ASTPtr tryMakeUsingColumnASTWithAlias(const QueryTreeNodePtr & node)
     if (!lhs_column_node || !rhs_column_node)
         return nullptr;
 
+    /// If USING column resolved from projection, keep its name
```
Comment (tuanpach) [inline src/Analyzer/JoinNode.cpp:84]: Could you give an example of a query for this case?

This part is new to me. Could you please provide a bit more explanation?

Comment (vdimir) [reply src/Analyzer/JoinNode.cpp:84]: It’s related to the recent PR https://github.com/ClickHouse/ClickHouse/pull/79942) which allows the syntax `JOIN ... USING (a AS b)`, meaning that `a` is taken from the left table and `b` from the right. 
Consider the following query:
```
SELECT x + 1 AS a
FROM t1
JOIN t2
USING (a)
```
If table `t2` has a column `a`, and we assume that `x + 1` from the left table `t1` is used as `a`. However, if `t1` already has a column named `a`, expression is renamed to `_a`. Despite this, the query tree node retains the expression `x + 1` in `getExpression` for evaluation. Therefore, there’s no need to format the query as `USING (_a AS a)` for the remote query; we can send the original `USING (a)` to the replica. (The formatting here is crucial for distributed queries.)

**Review by tuanpach — APPROVED** [review]
