### PR TITLE
RFC: Do not retry S3 requests in case of host not found

### LINKED ISSUE #68663: Can't drop MATERIALIZED VIEW for S3Queue table when host is incorrect (or service has not worked).
Hello. I can't drop `MATERIALIZED VIEW` or `S3Queue` when the host is incorrect (or the service has not worked). It is unexpected behavior for me. Could you please check? Thank you! 

**How to reproduce**
* Version 24.3.6.27
* Queries to run that lead to unexpected result:

1) Create table
```
CREATE TABLE IF NOT EXISTS test_s3_issue
(
    `test_field` String
)
ENGINE = MergeTree
ORDER BY test_field

```

2) Create S3Queue table
```
CREATE TABLE IF NOT EXISTS test_s3_issue_queue
(
    `test_field` String
)
ENGINE = S3Queue('http://minio:9000/not-exist-s3-bucket/**.log.gz', 'JSONEachRow', 'gz')
SETTINGS keeper_path = '/clickhouse/db_name/s3queue/test_s3_issue', mode = 'unordered', after_processing = 'keep', s3queue_loading_retries = 3, s3queue_processing_threads_num = 30, s3queue_enable_logging_to_s3queue_log = 1, s3queue_polling_min_timeout_ms = 1000, s3queue_polling_max_timeout_ms = 5000, s3queue_polling_backoff_ms = 1500, s3queue_tracked_file_ttl_sec = 345600, s3queue_tracked_files_limit = 1000000
```

3) Create MATERIALIZED VIEW
```
CREATE MATERIALIZED VIEW IF NOT EXISTS test_s3_issue_mv TO test_s3_issue AS
SELECT *
FROM test_s3_issue_queue
```

4) Get error about not existing host
```
SELECT
    name,
    code,
    value
FROM system.errors
WHERE name = 'DNS_ERROR'

Query id: 183ceca6-cae8-4c32-b7da-0ab824ff2cf6

┌─name──────┬─code─┬─value─┐
│ DNS_ERROR │  198 │    13 │
└───────────┴──────┴───────┘
```

5) Try to remove MATERIALIZED VIEW
```
DROP TABLE IF EXISTS test_s3_issue_mv SYNC
```

6) Get error:
`Read timed out, server ClickHouseNode [uri=http://localhost:10011/db_name_test, options={session_id=DataGrip_dda76b5f-9639-46a9-9e19-9a66ebff2aea}]@2094539699`

7) Try to remove S3Queue
```
DROP TABLE IF EXISTS test_s3_issue_queue SYNC
```

6) Get error:
`Read timed out, server ClickHouseNode [uri=http://localhost:10011/db_name_test, options={session_id=DataGrip_c4c4d94b-3f5b-4783-8d2a-88d988130050}]@1437525759`

**Expected behavior**
`DROP TABLE` works without errors

### PR DESCRIPTION
**Pull request by azat**
The problem is that in case you simply created endpoint with incorrect hostname then you will have to wait until 100 retries (done) will be done, and this too slow.

But note that DNS may sometimes incorrectly return NOTEXIST, and even though ClickHouse has builtin DNS cache (that may help in terms of less load to DNS only) it still may be affected.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not retry S3 requests in case of host not found

Fixes: https://github.com/ClickHouse/ClickHouse/issues/68663

### CODE REVIEW

File: src/IO/S3/PocoHTTPClient.cpp [hunk 1]
```diff
@@ -668,6 +670,22 @@ void PocoHTTPClient::makeRequestInternalImpl(
         }
         throw Exception(ErrorCodes::TOO_MANY_REDIRECTS, "Too many redirects while trying to access {}", request.GetUri().GetURIString());
     }
+    catch (const NetException & e)
```
Comment (kssenii) [inline src/IO/S3/PocoHTTPClient.cpp:673]: It seems should be easy to add a test?

Comment (azat) [reply src/IO/S3/PocoHTTPClient.cpp:673]: Make sense, done.

**Comment by azat** [comment]
>[Stateless tests (release, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77678&sha=45b41499888cf732f34d09fbaf718a51460756db&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20ParallelReplicas%2C%20s3%20storage%29) — fail: 1, passed: 6806, skipped: 958

- https://github.com/ClickHouse/ClickHouse/pull/78054

>[Stateless tests (coverage, 3/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=77678&sha=45b41499888cf732f34d09fbaf718a51460756db&name_0=PR&name_1=Stateless%20tests%20%28coverage%2C%203%2F6%29) — Invalid check_status.tsv

- https://github.com/ClickHouse/ClickHouse/issues/78062
- https://github.com/ClickHouse/ClickHouse/pull/78066

**Review by kssenii — APPROVED** [review]
