### PR TITLE
Fix finalized buffer issue on windows aggregation operations

### LINKED ISSUE #91415: Another estimateCompressionRatio issue
### Describe the bug

Related to https://github.com/ClickHouse/ClickHouse/issues/89282 ? Easy to reproduce.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/4c0877e9-8829-4c33-b83f-182330d7f7b5

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Cannot write to finalized buffer'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000252662b2
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000001569c4a9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d3d3ece
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d3d3a11
4. src/Common/Exception.h:141: DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000d3e2c36
5. src/IO/WriteBuffer.cpp:41: DB::WriteBuffer::write(char const*, unsigned long) @ 0x00000000157a5351
6. src/DataTypes/Serializations/ISerialization.cpp:218: DB::ISerialization::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::ISerialization::SerializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::SerializeBinaryBulkState>&) const @ 0x000000001a6f2398
7. src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp:179: DB::(anonymous namespace)::AggregateFunctionEstimateCompressionRatio::addBatchSinglePlace(unsigned long, unsigned long, char*, DB::IColumn const**, DB::Arena*, long) const @ 0x0000000015e0b97a
8. src/Processors/Transforms/WindowTransform.cpp:1034: DB::WindowTransform::updateAggregationState() @ 0x000000001f480fb3
9. src/Processors/Transforms/WindowTransform.cpp:1234: DB::WindowTransform::appendChunk(DB::Chunk&) @ 0x000000001f481d9b
10. src/Processors/Transforms/WindowTransform.cpp:1462: DB::WindowTransform::work() @ 0x000000001f484195
11. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001f10cbf0
12. src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001f0ff718
13. src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001f0ffd29
14. src/Processors/Executors/PipelineExecutor.cpp:602: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001f0fe4a1
15. src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001f0fdbff
16. src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_func<void ()>::__call_func[abi:se210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()>(std::__function::__policy_storage const*) @ 0x000000001f114ba2
17. contrib/llvm-project/libcxx/include/__functional/function.h:508: ? @ 0x00000000157e66f2
18. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:217: void* std::__thread_proxy[abi:se210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000157ed200
19. ? @ 0x00000000000a3d64
20. __GI___clone3 @ 0x00000000001373bc
```

### PR DESCRIPTION
**Pull request by Ergus**
Finalized buffers can't be reset, so they need to be also reconstructed.

Fixes: #91415

On Windows execution insertResultInto needs to call buffer finalization to compute size on every iteration. But in the next iteration the buffer needs reconstruction.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp [hunk 1]
```diff
@@ -77,25 +77,37 @@ class AggregateFunctionEstimateCompressionRatio final
...
-            data(place).null_buf = std::make_unique<NullWriteBuffer>();
-        if (!data(place).compressed_buf)
-            data(place).compressed_buf = std::make_unique<CompressedWriteBuffer>(
-                *data(place).null_buf, getCodecOrDefault(), block_size_bytes.value_or(DBMS_DEFAULT_BUFFER_SIZE));
+        Data & data_ref = data(place);
+
+        if (!data_ref.null_buf || data_ref.null_buf->isFinalized())
+            data_ref.null_buf = std::make_unique<NullWriteBuffer>();
+
+        /// When aggregating on column windows the buffer is finalized but not deleted.
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: This comment is a bit unclear. 1. "column windows" is not a well established term. 2. it doesn't say why and when this happens.

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp [hunk 2]
```diff
@@ -77,25 +77,37 @@ class AggregateFunctionEstimateCompressionRatio final
 
     void createBuffersIfNeeded(AggregateDataPtr __restrict place) const
     {
-        if (!data(place).null_buf)
-            data(place).null_buf = std::make_unique<NullWriteBuffer>();
-        if (!data(place).compressed_buf)
-            data(place).compressed_buf = std::make_unique<CompressedWriteBuffer>(
-                *data(place).null_buf, getCodecOrDefault(), block_size_bytes.value_or(DBMS_DEFAULT_BUFFER_SIZE));
+        Data & data_ref = data(place);
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp:82]: The whole fix is 2 lines of code but with this change the diff is bloated.

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp [hunk 3]
```diff
@@ -77,25 +77,37 @@ class AggregateFunctionEstimateCompressionRatio final
 
     void createBuffersIfNeeded(AggregateDataPtr __restrict place) const
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: Now it's "recreateBuffersIfNeeded"

**Review by nikitamikhaylov — APPROVED** [review]
Ok, but please address comments.

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp (hunk 2 above)
Comment (Ergus) [reply src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp:82]: Hi @nikitamikhaylov 

Indeed, the original code was hard to debug because `data` is a function that performs a `reinterpret_cast` and was hiding the issue. This is a trivial improvement to make debugging easier in the future.

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp (hunk 1 above)
Comment (Ergus) [reply src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: Solved via 935cbf932d4ed0e81aaa8d01b1b345eba4a255aa

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp [hunk 4]
```diff
@@ -75,27 +75,42 @@ class AggregateFunctionEstimateCompressionRatio final
     std::optional<UInt64> block_size_bytes;
 
 
-    void createBuffersIfNeeded(AggregateDataPtr __restrict place) const
+    void reCreateBuffersIfNeeded(AggregateDataPtr __restrict place) const
```
Comment (rschu1ze) [inline src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: The existing buffer is replaced by a new buffer. Can we rename to `resetBuffersIfNeeded`? ("reCreate" also looks a bit weird)

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp [hunk 5]
```diff
@@ -75,27 +75,42 @@ class AggregateFunctionEstimateCompressionRatio final
...
-        if (!data(place).compressed_buf)
-            data(place).compressed_buf = std::make_unique<CompressedWriteBuffer>(
-                *data(place).null_buf, getCodecOrDefault(), block_size_bytes.value_or(DBMS_DEFAULT_BUFFER_SIZE));
+        Data & data_ref = data(place);
+
+        if (!data_ref.null_buf || data_ref.null_buf->isFinalized())
+            data_ref.null_buf = std::make_unique<NullWriteBuffer>();
+
+        /// When aggregating on windows transformed columns, the function WindowTransform::appendChunk
+        /// calls updateAggregationState + writeOutCurrentRow in a loop.
```
Comment (rschu1ze) [inline src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp:88]: I'd vote for removing the comment in l. 85-90.
- It talks about functions in a completely different part of the sources. If the other code changes, the comment will be outdated.
- L. 88 is a TODO item. Here seems not the right place for it.
- L. 90 is also needless because `estimateCompressionRatio` merely exists for introspection.

Comment (Ergus) [reply src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp:88]: I added this comment because @nikitamikhaylov pointed that my initial comment was a bit unspecific. The trade off here is that: if those other parts of the code change, maybe this change won't be needed. So if the comment is outdated, maybe this code will be as well?

I am fine removing the TODO. However, I would like to keep some hint for the future me because reconstructing the buffer on every iteration may impact performance and we already know how to solve it. 

| L. 90 is also needless because estimateCompressionRatio merely exists for introspection.

Until some user decides to add it for some fancy use case ;)

**Review by rschu1ze — APPROVED** [review]

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp (hunk 4 above)
Comment (Ergus) [reply src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp]: Solved via 4474d46

File: src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp (hunk 5 above)
Comment (Ergus) [reply src/AggregateFunctions/AggregateFunctionEstimateCompressionRatio.cpp:88]: Partially solved via a3f2ffb. @rschu1ze please check if that is enough to merge

**Review by rschu1ze — APPROVED** [review]

**Comment by Ergus** [comment]
Failing tests are unrelated:

Already reported as flaky:
1. 01459_manual_write_to_replicas_quorum_detach_attach: #93010
2. test_dictionaries_update_and_reload/test.py::test_reload_while_loading: #93250
3. test_userspace_page_cache/test.py::test_size_adjustment: #92761
4. test_storage_s3_queue/test_migration.py::test_migration[3-]: #93196

Other fails are also unrelated: like an `'Out of memory: Killed process'`

https://s3.amazonaws.com/clickhouse-test-reports/PRs/92395/808f66c728faa8fe3d119c8d2275b57ad776463b//ast_fuzzer_amd_debug/job.log
