### PR TITLE
Query Cache: Assume UDFs are non-deterministic

### LINKED ISSUE #77553: UDF are considered deterministic
### Company or project name

_No response_

### Describe what's wrong

Opposite to what's described in [QueryCache documentation](https://clickhouse.com/docs/en/operations/query-cache#configuration-settings-and-usage) UDF's are managed as deterministic by default.

This is opposite to the request in issue #59988 but needs to be fixed before in order to implement that feature.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
CREATE FUNCTION parity_str AS (n) -> if(n % 2, 'odd', 'even');
SELECT parity_str(4) settings use_query_cache = 1;

SELECT count(*) FROM system.query_cache; -- returns 1
```

Something similar happens with externally defined UDFs.

### Expected behavior

In the previous example the `SELECT count(*) FROM system.query_cache; `should return `0` at the end.

### Error message and/or stacktrace

_No response_

### Additional context

`astContainsNonDeterministicFunctions` internally uses the visitor code in:

`QuerryResultCache.cpp:HasNonDeterministicFunctionsMatcher:visit`

The problem is that this function uses the UDF function name to call

`FunctionFactory.cpp:FunctionFactory::tryGet`

Ignoring the functions in `UserDefinedSQLFunctionFactory` and `UserDefinedExecutableFunctionFactory`

### PR DESCRIPTION
**Pull request by Ergus**
As issue #77553 explains, all UDFs were wrongly treated as deterministic opposite to the [QueryCache documentation](https://clickhouse.com/docs/en/operations/query-cache#configuration-settings-and-usage).

This PR solves that issue and adds 2 new tests to assert that this errors never pass silently again.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The query cache now assumes that UDFs are non-deterministic. Accordingly, results of queries with UDFs are no longer cached. Previously, users were able to define non-deterministic UDFs whose result would erronously be cached (issue #77553).

### CODE REVIEW

**Comment by Ergus** [comment]
@rschu1ze the HW change needs this approved before.

**Comment by Ergus** [comment]
Hi @yariks5s

I see that the style check is failing. Do you have some style guideline I can consult?

Is it declaring the variable inside the `if (const auto var = smething)`,
or the `} else if (const auto var = smething) {` or both?

BTW, the total workflow seems to have been executed but freeze in the complete job step. Is this intended?

**Comment by yariks5s** [comment]
@Ergus you can go to the Style check link in the CI, and click on the `FAIL` text. After that, you can see the fail report:
image

According to our style check you should put figure brackets at the new line. You left figure brackets on the same line on: 
- /ClickHouse/src/Interpreters/Cache/QueryResultCache.cpp:61
- /ClickHouse/src/Interpreters/Cache/QueryResultCache.cpp:64
- /ClickHouse/src/Interpreters/Cache/QueryResultCache.cpp:66

**Comment by Ergus** [comment]
Hi @yariks5s: 

> According to our style check you should put figure brackets at the separate line. You left figure brackets on the same line on:
> 
> * /ClickHouse/src/Interpreters/Cache/QueryResultCache.cpp:61
> * /ClickHouse/src/Interpreters/Cache/QueryResultCache.cpp:64
> * /ClickHouse/src/Interpreters/Cache/QueryResultCache.cpp:66

Thanks, I already fixed it ;)

 I was actually asking for a clang format file or something similar where you define the rules so I can check them and setup my editor.
This seems similar to Allman but with spaces instead of tabs... But I suppose that there may be more details.

**Comment by Ergus** [comment]
Hi @rschu1ze:

I see that some tests are failing. I tried the stateless one locally and it is failing on master, so seem unrelated with my change.

What's your common method to proceed? In an organization I would try to git-blame and try to contact the developer of the failing code in order to ask for help and get a faster solution.

**Comment by rschu1ze** [comment]
@Ergus I added a few finishing touches to the PR, it looks good. Thanks!

> I was actually asking for a clang format file or something similar where you define the rules so I can check them and setup my editor.
> This seems similar to Allman but with spaces instead of tabs... But I suppose that there may be more details.

Yeah, there is a `.clang-format` in the root directory of the repository. Though in practice, most people run a lot more often into the typo checker than the style checker :-)

> I see that some tests are failing. I tried the stateless one locally and it is failing on master, so seem unrelated with my change.

Yes, the failures are 100% unrelate4d. ClickHosue's CI is flaky and it is an uphill battle to stabilize it. 

> What's your common method to proceed? In an organization I would try to git-blame and try to contact the developer of the failing code in order to ask for help and get a faster solution.

No need to something from your side for now (though `git-blame` would make sense) - Most of the failures are tracked as issues already and being taken care of.

File: tests/queries/0_stateless/02494_query_cache_udf_executable.sh [hunk 1]
```diff
@@ -0,0 +1,35 @@
+#!/usr/bin/env bash
+# Tags: no-parallel
+# Tag no-parallel: Messes with internal cache
+
+# Test for issue #77553: External UDFs may be non-deterministic. The query cache should treat them as such, i.e. reject them.
+# Also see 02494_query_cache_udf_sql.sql
+
+set -e
```
Comment (rschu1ze) [inline tests/queries/0_stateless/02494_query_cache_udf_executable.sh:8]: As per your findings in https://github.com/ClickHouse/ClickHouse/issues/59988#issuecomment-2727041022 (thanks for noticing!), we'll need to go for an integration test actually. I tried quickly with standard `clickhouse-client` instead of `clickhouse-local` but could not get it to work easily.

Re integration tests: They can be a bit more difficult to setup, see tests/integration/README.md for prerequisites. I recommend testing with the runner script.

**Comment by Ergus** [comment]
Hi:

Just pushed the integration tests. I think it is sensible to delete the previous query tests as they are not doing the job they were supposed to do.

If you give green light I will revert e437ab4b3e4 and 55bbf428196; unless you think that they have some value if modified somehow.

**Comment by rschu1ze** [comment]
@Ergus Yes, let's revert these

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
@Ergus While checking, I noticed that we can at least retain the stateless tests for SQL-defined UDFs and I did just that. The reason is that integration tests are a pain in the ass overall, and we rather have only the minimally required amount of them.
