### PR TITLE
Fix wrong query result when http_write_exception_in_output_format=1

### LINKED ISSUE #56072: Wrong query result when query via http with JSON output format and http_write_exception_in_output_format=1
**Describe what's wrong**
If table has long string column and query that column them via http with `http_write_exception_in_output_format=1` and use JSON or JSONCompact output format, the body of the string is randomly truncated.

**How to reproduce**

`wc -w` here should return > 1000000 words.

```bash
> echo "SELECT repeat('1 ', 1000000) from system.one" | curl '127.0.0.1:8123/?default_format=JSON' --data-binary @- | wc -w
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  929k    0  929k  100    45  74.8M   3713 --:--:-- --:--:-- --:--:-- 75.6M
475745
```

Set `http_write_exception_in_output_format = 0` and it's correct:

```bash
> echo "SELECT repeat('1 ', 1000000) from system.one" | curl '127.0.0.1:8123/?default_format=JSON&http_write_exception_in_output_format=0' --data-binary @- | wc -w
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1953k    0 1953k  100    45   146M   3445 --:--:-- --:--:-- --:--:--  146M
1000033
```

Use tcp client and it's correct:

```bash
> clickhouse client -q "SELECT repeat('1 ', 1000000) from system.one FORMAT JSON" | wc -w
1000033
```

Change JSON to JSONEachRow and it's also correct:

```bash
> echo "SELECT repeat('1 ', 1000000) from system.one" | curl '127.0.0.1:8123/?default_format=JSONEachRow' --data-binary @- | wc -w
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1953k    0 1953k  100    45   105M   2492 --:--:-- --:--:-- --:--:--  105M
1000003
```

Suspect #52853

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong query result when setting `http_write_exception_in_output_format` is enabled. Closes https://github.com/ClickHouse/ClickHouse/issues/56072

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit c7857646bcf0bb39f8f6956ed858c15c29744348 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56135/c7857646bcf0bb39f8f6956ed858c15c29744348/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6696971021">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56135/c7857646bcf0bb39f8f6956ed858c15c29744348/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: tests/queries/0_stateless/02907_http_exception_json_bug.sh [hunk 1]
```diff
@@ -0,0 +1,10 @@
+#!/usr/bin/env bash
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+CH_URL="$CLICKHOUSE_URL&http_write_exception_in_output_format=1&allow_experimental_analyzer=0"
```
Comment (Algunenano) [inline tests/queries/0_stateless/02907_http_exception_json_bug.sh:7]:
```suggestion
CH_URL="$CLICKHOUSE_URL&http_write_exception_in_output_format=1"
```

Extra `allow_experimental_analyzer=0` shouldn't be necessary

**Review by Algunenano — APPROVED** [review]
