### PR TITLE
Fix uncaught exception in HTTPHandler

### LINKED ISSUE #45308: Uncaught exception in HTTPHandler
https://s3.amazonaws.com/clickhouse-test-reports/44547/6de4837580676830b5c58c1443452ac1c3677fac/stress_test__asan_.html

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869314 [ 1686 ] {} <Fatal> BaseDaemon: (version 22.13.1.1, build id: A86CA3301E4841EC88C7F7EDB70316687C0AB2D4) (from thread 56604) Terminate called for uncaught exception:
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869383 [ 1686 ] {} <Fatal> BaseDaemon: Code: 241. DB::Exception: Memory limit (for user) exceeded: would use 32.97 GiB (attempt to allocate chunk of 112 bytes), maximum: 20.57 GiB. OvercommitTracker decision: Memory overcommit has freed not enough memory. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869440 [ 1686 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869494 [ 1686 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x3d0a3d8c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869545 [ 1686 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x200a8743 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869603 [ 1686 ] {} <Fatal> BaseDaemon: 2. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string_view<char, std::__1::char_traits<char>>>::type>, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string_view<char, std::__1::char_traits<char>>&&) @ 0x200ca62d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869669 [ 1686 ] {} <Fatal> BaseDaemon: 3. ./build_docker/../src/Common/MemoryTracker.cpp:263: MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x200c83f9 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869752 [ 1686 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../src/Common/MemoryTracker.cpp:0: MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x200c7b73 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869801 [ 1686 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/MemoryTracker.cpp:0: MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x200c7b73 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869852 [ 1686 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/CurrentMemoryTracker.cpp:59: CurrentMemoryTracker::alloc(long) @ 0x2001da99 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869902 [ 1686 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/AllocatorWithMemoryTracking.h:35: DB::OpenTelemetry::Span::addAttribute(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long) @ 0x20315a52 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.869959 [ 1686 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Server/HTTPHandler.cpp:0: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x3547efe2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870021 [ 1686 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Server/HTTP/HTTPServerConnection.cpp:0: DB::HTTPServerConnection::run() @ 0x355acccf in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870081 [ 1686 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x3cd0542f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870136 [ 1686 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x3cd06185 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870193 [ 1686 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x3d1ca23c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870248 [ 1686 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x3d1c37ed in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870310 [ 1686 ] {} <Fatal> BaseDaemon: 14. ? @ 0x7f9a6a5d5609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870354 [ 1686 ] {} <Fatal> BaseDaemon: 15. __clone @ 0x7f9a6a4fa133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.01.13 21:58:51.870400 [ 1686 ] {} <Fatal> BaseDaemon:  (version 22.13.1.1)
```

Slightly related to https://github.com/ClickHouse/ClickHouse/pull/39010
cc: @FrankChen021, @rschu1ze

### PR DESCRIPTION
**Pull request by FrankChen021**
Fixes #45308

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix uncaught exception in HTTPHandler when open telemetry is enabled

### CODE REVIEW

File: src/Common/OpenTelemetryTraceContext.h [hunk 1]
```diff
@@ -23,16 +23,15 @@ struct Span
...
-    void addAttribute(std::string_view name, std::string_view value);
-    void addAttributeIfNotEmpty(std::string_view name, std::string_view value);
-    void addAttribute(std::string_view name, std::function<String()> value_supplier);
-
-    /// Following two methods are declared as noexcept to make sure they're exception safe
-    /// This is because they're usually called in exception handler
-    void addAttribute(const Exception & e) noexcept;
-    void addAttribute(std::exception_ptr e) noexcept;
+    /// Following methods are declared as noexcept to make sure they're exception safe
+    /// This is because sometimes they will be called in exception handlers/dtor
```
Comment (rschu1ze) [inline src/Common/OpenTelemetryTraceContext.h:27]: Let's add sth. like `/// Returns true if successful and false otherwise.`

File: src/Common/OpenTelemetryTraceContext.cpp [hunk 2]
```diff
@@ -14,76 +14,73 @@ namespace OpenTelemetry
...
 
-    try
-    {
-        this->attributes.push_back(Tuple{"clickhouse.exception", getExceptionMessage(e, false)});
-    }
-    catch (...)
-    {
-        /// Ignore exceptions
-    }
+    return addAttribute("clickhouse.exception", getExceptionMessage(e, false));
```
Comment (rschu1ze) [inline src/Common/OpenTelemetryTraceContext.cpp:83]: `this->isTraceEnabled()` is checked twice: here + in `addAttribute` called in l. 83. What about introducing a method `bool Span::addAttribute_impl(std::string_view name, std::string_view value)` to which *all* `addAttribute()` methods map to? That way, you could implement all common checks only in a single place (_impl method).

File: src/Common/OpenTelemetryTraceContext.h (hunk 1 above)
Comment (rschu1ze) [reply src/Common/OpenTelemetryTraceContext.h:27]: We now return something from `addAttribute*()` but the callers were not changed to check the return value. Is that okay?

File: src/Common/OpenTelemetryTraceContext.h [hunk 3]
```diff
@@ -23,16 +23,15 @@ struct Span
...
+    bool addAttribute(std::string_view name, UInt64 value) noexcept;
+    bool addAttributeIfNotZero(std::string_view name, UInt64 value) noexcept;
+    bool addAttribute(std::string_view name, std::string_view value) noexcept;
```
Comment (rschu1ze) [inline src/Common/OpenTelemetryTraceContext.h:30]: Add a `try` prefix to all of these methods? (cf. the discussion in issue #45308)

File: src/Common/OpenTelemetryTraceContext.h (hunk 1 above)
Comment (FrankChen021) [reply src/Common/OpenTelemetryTraceContext.h:27]: Yes, no callers are changed to check the returned value. In most cases, we don't need to check the returned value, the returned value is kept in case some one needs it.

File: src/Common/OpenTelemetryTraceContext.cpp (hunk 2 above)
Comment (FrankChen021) [reply src/Common/OpenTelemetryTraceContext.cpp]: Good point. `addAttributeImpl`, a private method which has no parameter check, is added. All checks are still kept in the public methods this is because these checks can prevent extra functions calls such as `getExceptionMessage` if the checks return false.

File: src/Common/OpenTelemetryTraceContext.h (hunk 3 above)
Comment (FrankChen021) [reply src/Common/OpenTelemetryTraceContext.h:31]: Although `tryAddAttribute` is semantically perfect, changing the function name will introduce lots of changes. Let's keep the change in this PR small.

**Comment by rschu1ze** [comment]
ClickHouse Bugfix Validate Check:
- clicking "Report" gives "Access denied" ... anyways, a test would be highly specific and probably not be too useful

AST Fuzzer:
- segfault (nullptr access) in ColumnToPolygonsConverter<...>::convert(): #45355

ClickHouse Stateless Tests (asan) [3/4]:
ClickHouse Stateless Tests (msan) [1/6]:
ClickHouse Stateless Tests (ubsan) [1/2]:
- 02540_date_column_consistent_insert_behaviour: Unrelated, happens in master too, responsible PR was rolled back

ClickHouse Stateless Tests (debug, S3 Storage) [3/6]:
- 02346_full_text_search: unrelated issue (infra problem?)
