### PR TITLE
Fix logical error resolving matcher with multiple JOINs

### LINKED ISSUE #81969: Unexpected return type from equals. Expected UInt8. Got Nullable(UInt8).
### Describe what's wrong

LOGICAL ERROR during query analysis

### Does it reproduce on the most recent release?

Yes

### How to reproduce

https://fiddle.clickhouse.com/a36cef4c-67a5-4431-abe8-43e931b62a99

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix logical error when resolving matcher in query with multiple JOINs, close https://github.com/ClickHouse/ClickHouse/issues/81969

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Analyzer/Resolve/QueryAnalyzer.cpp [hunk 1]
```diff
@@ -2245,12 +2245,12 @@ ProjectionNames QueryAnalyzer::resolveMatcher(QueryTreeNodePtr & matcher_node, I
           * We are taking the nearest JoinNode to check to which table column belongs,
           * because for LEFT/RIGHT join, we convert only the corresponding side.
```
Comment (serxa) [inline src/Analyzer/Resolve/QueryAnalyzer.cpp]: Minor. Probably we should mention multiple tables in the comment

**Review by serxa — APPROVED** [review]
