### PR TITLE
Validate direct dictionary lifetime is unset during creation

### LINKED ISSUE #27861: It's possible to create direct dictionary with LIFETIME, but not use it.
**Describe the issue**
You can create direct dictionary with lifetime trait and clickhouse wouldn't complain, but it would throw exception if you would try to use this dictionary. 

**How to reproduce**
Clickhouse version 21.9

```
CREATE TABLE dict_source (key UInt64, value String) ENGINE=MergeTree ORDER BY key;
INSERT INTO dict_source SELECT number, toString(number) FROM numbers(1000000);
CREATE DICTIONARY dict　(　    `key` UInt64,　    `value` String　)　PRIMARY KEY key　SOURCE(CLICKHOUSE(table 'dict_source'))　LAYOUT(DIRECT()) LIFETIME(300)　;

SELECT dictGet('dict', 'value', 1::UInt64);

SELECT dictGet('dict', 'value', CAST('1', 'UInt64'))

Query id: d31b3dd7-bd6c-4c7b-b997-f9f7222c3cfa


0 rows in set. Elapsed: 0.004 sec.

Received exception from server (version 21.9.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: 'lifetime' parameter is redundant for the dictionary' of layout 'direct': While processing dictGet('dict', 'value', CAST('1', 'UInt64')). (BAD_ARGUMENTS)
```

**Expected behavior**
Clickhouse will throw this error on dictionary creation.

**Error message and/or stacktrace**
```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: 'lifetime' parameter is redundant for the dictionary' of layout 'direct': While processing dictGet('dict', 'value', CAST('1', 'UInt64')). (BAD_ARGUMENTS)
```

### PR DESCRIPTION
**Pull request by RoryCrispin**
### Changelog category:
- Improvement

### Changelog entry:
Creating a direct dictionary with a lifetime field set will be rejected at create time. Fixes: #27861

### CODE REVIEW

File: src/Dictionaries/getDictionaryConfigurationFromAST.cpp [hunk 1]
```diff
@@ -571,11 +571,24 @@ void checkPrimaryKey(const AttributeNameToConfiguration & all_attrs, const Names
 
 }
 
+void checkLifetime(const ASTCreateQuery & query)
+{
+    if (query.dictionary->layout && query.dictionary->layout->layout_type == "direct")
```
Comment (alexey-milovidov) [inline src/Dictionaries/getDictionaryConfigurationFromAST.cpp:576]: It should be allowed if the dictionary is ATTACHed, e.g., during the server's startup. This is needed to allow seamless upgrades.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]

File: tests/queries/0_stateless/02716_create_direct_dict_with_lifetime_crash.sql [hunk 2]
```diff
@@ -0,0 +1,3 @@
+CREATE TABLE IF NOT EXISTS dict_source (key UInt64, value String) ENGINE=MergeTree ORDER BY key;
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02716_create_direct_dict_with_lifetime_crash.sql:1]: The test name is not good.

The "crash" means abnormal program termination; this is a strong word. If ClickHouse crashes, it is a disaster, requiring immediate attention and stopping all other work across the company. An error message for a query is not "crash".

File: src/Dictionaries/getDictionaryConfigurationFromAST.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply src/Dictionaries/getDictionaryConfigurationFromAST.cpp:576]: Somewhere around `StorageFactory::Arguments`, `attach`, check its usage.

**Comment by alexey-milovidov** [comment]
@RoryCrispin changed to "improvement" because no bugs were fixed.

**Comment by alexey-milovidov** [comment]
Let's continue.
