### PR TITLE
DatabaseIceberg: support s3.endpoint natively from catalog config

### LINKED ISSUE #74558: Iceberg Database does not respect `s3.endpoint` setting of catalog config
**Describe the unexpected behaviour**
When using an Iceberg database/table with `vended_credentials`, the config setting `s3.endpoint` from the REST catalog is not used. Instead, the request is sent to AWS (unless a `storage_endpoint` is explicitly set in the database engine settings).

**How to reproduce**
* Set up an Iceberg REST catalog implementation and a non-AWS S3-compatible storage backend (e.g. Polaris with [this enhancement](https://github.com/apache/polaris/pull/389))
* Create a catalog using these settings:
    ```json5
    {
      "type": "INTERNAL",
      "name": "test_s3_catalog",
      "properties": {
        "default-base-location": "s3://${BUCKET_NAME}"
      },
      "storageConfigInfo": {
        "storageType": "S3_COMPATIBLE",
        "s3.endpoint": "http://${S3_ENDPOINT}",  // <-- this is the important bit, it should point to e.g. minio
        "s3.credentials.catalog.accessKeyId": "ACCESS_KEY_ID",
        "s3.credentials.catalog.secretAccessKey": "SECRET_ACCESS_KEY",
        "s3.pathStyleAccess": true,
        "skipCredentialSubscopingIndirection": true,
        "s3.credentials.client.accessKeyId": "",
        "s3.credentials.client.secretAccessKey": "",
        "s3.region": "irrelevant",
        "s3.roleArn": null,
        "allowedLocations": [
          "s3://${BUCKET_NAME}"
        ]
      }
    }
    ```
* Create a principal and set all necessary roles and permissions for that principal on the catalog
* Upload data into a new Iceberg table in that catalog (e.g. using pyspark, see [here](https://www.tabular.io/blog/rest-catalog-docker/))
* Start `clickhouse/clickhouse-server:head` with docker
* Create an Iceberg database: 
```sql
    CREATE DATABASE test
    ENGINE = Iceberg('http://<CATALOG_HOSTNAME>/api/catalog')
    SETTINGS catalog_type = 'rest', warehouse = 'test_s3_catalog', catalog_credential = '<principal_client_id>:<principal_client_secret>'
```
* Try to query the uploaded table, e.g. via `SELECT count() FROM test.<table.name>`

**Expected behavior**
The underlying request should fire against the `s3.endpoint` configured in the catalog and successfully return data.

**Error message and/or stacktrace**
This error is returned:
```
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: The AWS Access Key Id you provided does not exist in our records. (Code: 23, S3 exception: 'InvalidAccessKeyId'). (S3_ERROR)
```
This indicates that the request is fired against the default AWS S3 endpoint (ending up in an authorization error) instead of the configured one. 

**Additional context**
I would expect the logic to be somewhere around [here](https://github.com/ClickHouse/ClickHouse/blob/6adaf4a835506b06ac9b4b0f2012f57f5290e077/src/Databases/Iceberg/RestCatalog.cpp#L618), where the response from the `api/catalog/v1/test_s3_catalog/namespaces/<namespace>/tables/<table>`  is processed. This response does include the `config` object (if header `X-Iceberg-Access-Delegation:vended-credentials` is set) and that object includes the `s3.endpoint` setting, but it's not used by ClickHouse.

When adding `storage_endpoint = 'http://<S3_ENDPOINT>/<BUCKET_NAME>'` to the database engine settings, the request works, but this would contradict one of the key advantages/features of a REST catalog: abstracting away the storage implementation.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support `s3.endpoint` natively from catalog config in `DatabaseIceberg`. Closes https://github.com/ClickHouse/ClickHouse/issues/74558.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [x]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [x]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 88f4c7881cacf88aa1ba9875d848523a10819342 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75375/88f4c7881cacf88aa1ba9875d848523a10819342/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/75375/88f4c7881cacf88aa1ba9875d848523a10819342/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Databases/Iceberg/DatabaseIceberg.cpp
Comment (kssenii) [inline src/Databases/Iceberg/DatabaseIceberg.cpp:1]: There is no test in this PR, because this feature is not supported by the catalog image used in our tests. To test this change I used Polaris catalog built with unmerged PR https://github.com/apache/polaris/pull/389. 
I am planning to add this catalog into tests, but it will take some effort. I will do that separately in a different PR.

File: src/Databases/Iceberg/ICatalog.cpp [hunk 1]
```diff
@@ -63,21 +63,49 @@ void TableMetadata::setLocation(const std::string & location_)
...
+
+    return constructLocation(endpoint_);
+}
+
+std::string TableMetadata::constructLocation(const std::string & endpoint_) const
+{
+    std::filesystem::path location = endpoint_;
+    if (endpoint_.ends_with('/'))
+        location = endpoint_.substr(0, endpoint_.size() - 1);
+    if (!endpoint_.ends_with(bucket))
```
Comment (divanik) [inline src/Databases/Iceberg/ICatalog.cpp:100]:
```
if (location.ends_with('/')) 
   location.pop_back(); 
```

File: src/Databases/Iceberg/ICatalog.cpp [hunk 2]
```diff
@@ -63,21 +63,49 @@ void TableMetadata::setLocation(const std::string & location_)
...
+        location /= bucket;
```
[the remark this answers is not in the document]
Comment (divanik) [reply src/Databases/Iceberg/ICatalog.cpp:101]: Or does bucket always finish with '/'?

**Review by divanik — COMMENTED** [review]
Some questions and small corrections

**Review by divanik — APPROVED** [review]

**Comment by kssenii** [comment]
> Stateless tests (debug, s3 storage)

`02962_system_sync_replica_lightweight_from_modifier` - flaky

> Stateless tests (release, old analyzer, s3, DatabaseReplicated, 2/2) 

`02125_many_mutations` - flaky
