### PR TITLE
Ensure coded DoubleDelta codec only accepts numeric types

### LINKED ISSUE #80220: DoubleDelta codec in a refreshable materialized view definition is allowed when it should not
### Describe the bug

This shouldn't be allowed, so I guess a validation is missing.

### How to reproduce

Run:

```sql
CREATE TABLE t0 (c0 String) ENGINE = MergeTree() ORDER BY tuple();
CREATE MATERIALIZED VIEW v0 REFRESH AFTER 1 SECOND APPEND TO t0 (c0 String CODEC(DoubleDelta(2))) EMPTY AS (SELECT 'a' AS c0);
```
Then restart the server, and the materialized view cannot be attached.

### Error message and/or stacktrace

Stack trace:

```
<Error> void DB::AsyncLoader::worker(Pool &): Code: 36. DB::Exception: Codec DoubleDelta is not applicable for String because the data type is not of fixed size: Cannot attach table `default`.`v0` from metadata file store/96c/96c0a346-8949-4e8c-9f3d-3979076d530c/v0.sql from query ATTACH MATERIALIZED VIEW default.v0 UUID 'f6e0785e-c859-4292-83d8-0a1e79f5f3e5' REFRESH AFTER 1 SECOND APPEND TO default.t0 (`c0` String CODEC(DoubleDelta)) DEFINER = default SQL SECURITY DEFINER AS SELECT 'a' AS c0. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001d66cdb2
1. src/Common/Exception.cpp:108: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000121b8044
2. src/Common/Exception.h:112: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000baefc2c
3. src/Common/Exception.h:130: DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x000000000baef8d6
4. src/Compression/CompressionCodecDoubleDelta.cpp:448: std::shared_ptr<DB::ICompressionCodec> std::__function::__policy_invoker<std::shared_ptr<DB::ICompressionCodec> (std::shared_ptr<DB::IAST> const&, DB::IDataType const*)>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::registerCodecDoubleDelta(DB::CompressionCodecFactory&)::$_0, std::shared_ptr<DB::ICompressionCodec> (std::shared_ptr<DB::IAST> const&, DB::IDataType const*)>>(std::__function::__policy_storage const*, std::shared_ptr<DB::IAST> const&, DB::IDataType const*) @ 0x000000001a34a142
5. src/Compression/CompressionFactoryAdditions.cpp:135: void std::__function::__policy_invoker<void (DB::ISerialization::SubstreamPath const&)>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::CompressionCodecFactory::validateCodecAndGetPreprocessedAST(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IDataType const> const&, bool, bool, bool, bool) const::$_0, void (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x000000001a35b1ec
6. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001641de94
7. src/DataTypes/Serializations/ISerialization.cpp:104: DB::ISerialization::enumerateStreams(std::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::shared_ptr<DB::IDataType const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) const @ 0x000000001641e1aa
8. src/Compression/CompressionFactoryAdditions.cpp:146: DB::CompressionCodecFactory::validateCodecAndGetPreprocessedAST(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IDataType const> const&, bool, bool, bool, bool) const @ 0x000000001a35a14d
9. src/Interpreters/InterpreterCreateQuery.cpp:707: DB::InterpreterCreateQuery::getColumnsDescription(DB::ASTExpressionList const&, std::shared_ptr<DB::Context const>, DB::LoadingStrictnessLevel, bool) @ 0x00000000171a7171
10. src/Databases/DatabaseOnDisk.cpp:130: DB::createTableFromAST(DB::ASTCreateQuery, String const&, String const&, std::shared_ptr<DB::Context>, DB::LoadingStrictnessLevel) @ 0x00000000165236e3
11. src/Databases/DatabaseOrdinary.cpp:335: DB::DatabaseOrdinary::loadTableFromMetadata(std::shared_ptr<DB::Context>, String const&, DB::QualifiedTableName const&, std::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x0000000016536783
12. src/Databases/DatabaseOrdinary.cpp:386: void std::__function::__policy_invoker<void (DB::AsyncLoader&, std::shared_ptr<DB::LoadJob> const&)>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::DatabaseOrdinary::loadTableFromMetadataAsync(DB::AsyncLoader&, std::unordered_set<std::shared_ptr<DB::LoadJob>, std::hash<std::shared_ptr<DB::LoadJob>>, std::equal_to<std::shared_ptr<DB::LoadJob>>, std::allocator<std::shared_ptr<DB::LoadJob>>>, std::shared_ptr<DB::Context>, String const&, DB::QualifiedTableName const&, std::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel)::$_0, void (DB::AsyncLoader&, std::shared_ptr<DB::LoadJob> const&)>>(std::__function::__policy_storage const*, DB::AsyncLoader&, std::shared_ptr<DB::LoadJob> const&) @ 0x000000001653e994
13. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001246c5bd
14. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000122e26b3
15. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x00000000122e87e3
16. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000122dfcc6
17. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000122e62a0
18. ? @ 0x0000758bfa6a1e2e
19. ? @ 0x0000758bfa733a4c
```

### PR DESCRIPTION
**Pull request by Ergus**
Fixes #80220 

Note: this PR is technically a backward-incompatible change. However, DoubleDelta-compressed FixedString columns never worked in the past, so it is more of a bugfix.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Codec `DoubleDelta` codec can now only be applied to columns of numeric type. In particular `FixedString` columns can no longer be compressed using `DoubleDelta`. (fixes #80220)

### CODE REVIEW

**Comment by nickitat** [comment]
Please add the tests from Pedro

**Comment by Ergus** [comment]
> Please add the tests from Pedro

Yes, that's in another commit, but I wanted to test first that this doesn't break any existing test cause this change adds extra restrictions. That's why I didn't add a reviewer either ;)

**Comment by Ergus** [comment]
I am wondering if a similar change needs to be done for the `Delta` codec.

File: tests/queries/0_stateless/00950_test_double_delta_codec_types.sql [hunk 1]
```diff
@@ -0,0 +1,18 @@
+-- Tags: no-random-merge-tree-settings
+
```
Comment (rschu1ze) [inline tests/queries/0_stateless/00950_test_double_delta_codec_types.sql:2]: Like to add a comment with a reference to the issue nr (80220)?

File: tests/queries/0_stateless/00950_test_double_delta_codec_types.sql [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+DROP TABLE IF EXISTS codecTest;
+
+-- Check error on FixedString with and without argument.
+CREATE TABLE codecTest (c0 FixedString(9) CODEC(DoubleDelta)) ENGINE = MergeTree() ORDER BY tuple(); -- { serverError BAD_ARGUMENTS }
+CREATE TABLE codecTest (c0 FixedString(9) CODEC(DoubleDelta(1))) ENGINE = MergeTree() ORDER BY tuple(); -- { serverError BAD_ARGUMENTS }
+
+-- Similarly on LowCardinality(nullable)
+set enable_time_time64_type=1;
+CREATE TABLE codecTest (c0 LowCardinality(Nullable(Time)) CODEC(DoubleDelta)) ENGINE = MergeTree() ORDER BY tuple(); -- { serverError BAD_ARGUMENTS }
```
Comment (rschu1ze) [inline tests/queries/0_stateless/00950_test_double_delta_codec_types.sql]: It is not clear for the reader if table creation is supposed to fail because the type is Time, because of LowCardinality or because of Nullable. Suggest to split this into multiple tests.

File: tests/queries/0_stateless/00950_test_double_delta_codec_types.sql [hunk 3]
```diff
@@ -0,0 +1,18 @@
+-- Tags: no-random-merge-tree-settings
```
Comment (rschu1ze) [inline tests/queries/0_stateless/00950_test_double_delta_codec_types.sql]: Guess we can omit this tag. If a type is eligible for DoubleDelta doesn't depend on any setting.

File: src/Compression/CompressionCodecDoubleDelta.cpp [hunk 4]
```diff
@@ -569,18 +576,18 @@ void registerCodecDoubleDelta(CompressionCodecFactory & factory)
             if (!literal || literal->value.getType() != Field::Types::Which::UInt64)
                 throw Exception(ErrorCodes::ILLEGAL_CODEC_PARAMETER, "DoubleDelta codec argument must be unsigned integer");
 
-            size_t user_bytes_size = literal->value.safeGet<UInt64>();
+            const size_t user_bytes_size = literal->value.safeGet<UInt64>();
             if (user_bytes_size != 1 && user_bytes_size != 2 && user_bytes_size != 4 && user_bytes_size != 8)
                 throw Exception(ErrorCodes::ILLEGAL_CODEC_PARAMETER, "Argument value for DoubleDelta codec can be 1, 2, 4 or 8, given {}", user_bytes_size);
+
+            /// TODO: Maybe we should add some check between both values here instead of just override.
```
Comment (rschu1ze) [inline src/Compression/CompressionCodecDoubleDelta.cpp:583]: The user explicitly _wants_ to override the default byte size. I don't quite see what we should check here? Remove the comment?

**Review by rschu1ze — APPROVED** [review]

File: src/Compression/CompressionCodecDoubleDelta.cpp (hunk 4 above)
Comment (Ergus) [reply src/Compression/CompressionCodecDoubleDelta.cpp:583]: I added the comment because I checked some documentation around and some of that the codec size should never be smaller that the underlying data type. As I was not sure about that I added the comment just in case

File: tests/queries/0_stateless/00950_test_double_delta_codec_types.sql
Comment (rschu1ze) [inline tests/queries/0_stateless/00950_test_double_delta_codec_types.sql:1]: (I would say things will be more maintainable in the long run if the tests for Delta and DoubleDelta are in the same file but I don't have a super strong opinion.)

Comment (Ergus) [reply tests/queries/0_stateless/00950_test_double_delta_codec_types.sql:1]: I agree, but they are totally independent at the moment and already duplicate many lines code. I considered to unify them (including some the code), but a fix should always be as simple as possible in order to track it down. I avoid doing refactor with fixes in the same PR

If we want to unify the code (now that everything is working) we can do it in a different PR.

File: src/Compression/CompressionCodecDelta.cpp [hunk 5]
```diff
@@ -202,6 +203,10 @@ void registerCodecDelta(CompressionCodecFactory & factory)
         /// Default bytes size is 1.
         UInt8 delta_bytes_size = 1;
 
+        // But always check against column_type if available to ensure it is also a valid type
```
Comment (ahmadov) [inline src/Compression/CompressionCodecDelta.cpp]: [very minor] comments start with `///`

File: src/Compression/CompressionCodecDoubleDelta.cpp [hunk 6]
```diff
@@ -554,11 +555,17 @@ void CompressionCodecDoubleDelta::doDecompressData(const char * source, UInt32 s
...
-    factory.registerCompressionCodecWithType("DoubleDelta", method_code,
-        [&](const ASTPtr & arguments, const IDataType * column_type) -> CompressionCodecPtr
+
+    auto reg_func = [&](const ASTPtr & arguments, const IDataType * column_type) -> CompressionCodecPtr
     {
-        /// Default bytes size is 1.
+        /// Default bytes size is 1
         UInt8 data_bytes_size = 1;
+
+        // But always check against column_type if available to ensure it is also a valid type
```
Comment (ahmadov) [inline src/Compression/CompressionCodecDoubleDelta.cpp:564]: same here L.564 and L.568

**Review by ahmadov — APPROVED** [review]
LGTM

File: src/Compression/CompressionCodecDelta.cpp [hunk 7]
```diff
@@ -179,13 +179,14 @@ namespace
 
 UInt8 getDeltaBytesSize(const IDataType * column_type)
 {
-    if (!column_type->isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion())
-        throw Exception(ErrorCodes::BAD_ARGUMENTS, "Codec Delta is not applicable for {} because the data type is not of fixed size",
+    if (!column_type->isValueRepresentedByNumber())
```
Comment (rschu1ze) [inline src/Compression/CompressionCodecDelta.cpp]: Thinking about this, restricting the eligible types for \*Delta makes sense overall (\*), but I'm sure that _someone_ out there is using \*Delta compression on a now forbidden type (e.g. FixedString). In that case, affected tables will fail to load. That's a problem. I think we should approach the problem a bit differently: ClickHouse has a setting `allow_suspicious_codecs` for dubious codec combinations. What if we keep `isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion` as a condition in the codecs but throw an error if the data type does not satisfy `isValueRepresentedByNumber` (--> can be done in src/Compression/CompressionFactoryAdditions.cpp). Existing tables can then be loaded with setting `allow_suspicious_codecs = 1`.

(*) even if not all combinations of a now-disabled type (FixedString) with different codec parameters (`Delta(1)`, `Delta(2)`) and data type lengths (`FixedString(1)`, `FixedString(2)`) might fail.

Comment (Ergus) [reply src/Compression/CompressionCodecDelta.cpp]: @rschu1ze 

I would ask here is we have some kind of deprecation policy/process. Because ideally what we could do is (as you suggested) trigger a warning but specifying that the feature will be totally disabled in a future version x.x.

Comment (Ergus) [reply src/Compression/CompressionCodecDelta.cpp]: Before this change there were a couple of issues that were not exposed because of the error that `delta is not a compression codec` triggered earlier:

For example these two were hidden

```sql
CREATE TABLE codecTest (c0 FixedString(9) CODEC(Delta)) ENGINE = MergeTree() ORDER BY tuple();
CREATE TABLE codecTest (c0 FixedString(9) CODEC(Delta(1))) ENGINE = MergeTree() ORDER BY tuple();
```
but this one:

```sql
set allow_suspicious_codecs = 1;
CREATE TABLE codecTest (c0 FixedString(9) CODEC(Delta(2))) ENGINE = MergeTree() ORDER BY tuple();
```
worked because the user specified the size and the code totally ignored the column size. AFAIK that is an issue because `9%2 != 0`

In the current code we enforce to check the column size to be: `1, 2, 4, 8` even when we respect the user value latter. So the question now is if we are supposed to go back to the previous code even if we know that there is an issue? 

Or we must ensure some extra correctness check. like checking that the column size is divisible by the user size when provides? Is it correct (for example) `c0 FixedString(9) CODEC(Delta(2))`?

What about `c0 FixedString(16) CODEC(Delta(4))`?

Comment (rschu1ze) [reply src/Compression/CompressionCodecDelta.cpp]: > I would ask here is we have some kind of deprecation policy/process. Because ideally what we could do is (as you suggested) trigger a warning but specifying that the feature will be totally disabled in a future version x.x.

Breaking existing usage must be avoided if possible. ClickHouse uses the "compatibility setting" mechanism for that (see [here](https://github.com/ClickHouse/ClickHouse/issues/35972) and [here](https://clickhouse.com/docs/operations/settings/settings#compatibility)). For example, customers can choose to upgrade a cluster but keep the compatibility level - the system will keep behaving like before the upgrade (in theory). The list of changed settings per version can be found in src/Core/SettingsChangesHistory.cpp.

"totally disabling" can only be done at a future point in time when we know that no user has a compatibility level smaller than 25.8 configured.
- for ClickHouse Cloud, that is usually the case after ~6 months.
- for ClickHouse OSS, that will likely never be the case. We will need to wait until ancient compatibility levels are forcefully removed from the code (that never happened yet).

The problem here is that we'd need a new MergeTree setting `allow_delta_and_doubledelta_compression_with_non_numeric_types` with default = true before this PR and default = false after this PR. Actually, this would be the best solution but it requires support in the code for passing and checking MergeTree settings in the CodecsFactory as well as the Codecs ... this is currently not there. Compared to that, my proposal of making the load dependent `allow_suspicious_codecs` is slightly inferior - loading will _always_ break after upgrade and manual intervention is required (one could argue that likely only few files are affected but still).

Comment (rschu1ze) [reply src/Compression/CompressionCodecDelta.cpp]: Re your other comment:

With `set allow_suspicious_codecs = 1;`, all bets are off, i.e., codecs may produce arbitrary garbage with this setting. This is known and accepted behavior.

> In the current code we enforce to check the column size to be: 1, 2, 4, 8 even when we respect the user value latter. So the question now is if we are supposed to go back to the previous code even if we know that there is an issue?

> Or we must ensure some extra correctness check. like checking that the column size is divisible by the user size when provides? Is it correct (for example) c0 FixedString(9) CODEC(Delta(2))?

> What about c0 FixedString(16) CODEC(Delta(4))?

I don't know the answers but this PR eliminates support for FixedString and therefore the entire sub-class of problems you describe.

Comment (rschu1ze) [reply src/Compression/CompressionCodecDelta.cpp]: Thinking about this, the change from `isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion` to `isValueRepresentedByNumber` affects data types UUID, FixedString, and Array (these will no longer be Delta/DoubleDelta compressible). Out of these, UUID has a fixed byte sizes and it setting integer parameter `N` as in `Delta(N)` and `DoubleDelta(N)` makes no sense. Setting `N` only makes sense for FixedString (even there it is doubtful). For Array, I don't know.

For un-affected data types (integers, floats, decimals, enums), setting `N` also makes no sense.

I guess this PR should also make setting `N` a no-op? (we can then also remove mentions of `N` from the docs).

Comment (Ergus) [reply src/Compression/CompressionCodecDelta.cpp]: But doing that would break backward compatibility for tables already created with N. Even if that is wrong.

Both codecs have the N parameter as well, and some tests use them.

Does it worth doing the change and updating all those? 

This will probably affect some other people around, should we ask someone from other group about this?

Comment (rschu1ze) [reply src/Compression/CompressionCodecDelta.cpp]: Usage of codecs `Delta(N)` / `DoubleDelta(N)` (where `N` is != the type byte length) for integers, floats, decimals, enums is highly dubious, but indeed ... chances are that someone uses that. For CHC, we can check internally if someone uses that (I'll ping you). We can eventually move such combinations under setting `allow_suspicous_codecs` as well.

**Comment by rschu1ze** [comment]
Stress test (amd_ubsan):
- `Expected JOIN table expression to be table` ... known, frequent and unrelated issue.

**Comment by rschu1ze** [comment]
Something bad happened to the public CI tests. Merging from master once more.

**Comment by rschu1ze** [comment]
Stateless tests (amd_binary, old analyzer, s3 storage, DatabaseReplicated, parallel):
- 02443_detach_attach_partition: known, unrelated and frequent failures

Integration tests (amd_asan, old analyzer, 2/6):
- test_replicated_database: fails sporadically in master with the same error, happens only with the old analyzer so probably not critical

**Comment by rschu1ze** [comment]
@Ergus Could you please update the [docs](https://clickhouse.com/docs/sql-reference/statements/create/table) as well? They say at the moment:

```
Can be used with any fixed-width type.
```

**Comment by Ergus** [comment]
> @Ergus Could you please update the [docs](https://clickhouse.com/docs/sql-reference/statements/create/table) as well? They say at the moment:
> 
> ```
> Can be used with any fixed-width type.
> ```

May I add a deprecation notice about the `bytes_size` argument as well? In order to discourage its use?

**Comment by rschu1ze** [comment]
@Ergus Yes, please do.
