### PR TITLE
Fix system.query_views_log for MVs that are pushed from background threads

### LINKED ISSUE #47311: `query_views_log` does not get populated when using a Materialized View attached to a Kafka table
**Describe the unexpected behaviour**

Using a simple pipeline: 

| Kafka engine table | ---> | Materialized View | ---> | Destination table |

- data is flowing correctly but `system.query_views_log` is not updated accordingly.

- `query_views_log` is correctly configured and working with other MVs.

Versions tested 22.8 and 23.2

**How to reproduce**

```sql
SELECT
    name,
    value
FROM system.settings
WHERE name = 'log_queries'

┌─name────────┬─value─┐
│ log_queries │ 1     │
└─────────────┴───────┘


CREATE TABLE IF NOT EXISTS default.test_to
(
    `key` String,
    `value` UInt8
)
ENGINE = MergeTree
ORDER BY key

CREATE TABLE IF NOT EXISTS default.test_kafka
(
    `key` String,
    `value` UInt8
)
ENGINE = Kafka
SETTINGS 
    kafka_broker_list = 'localhost:9092',
    kafka_topic_list = 'test1', 
    kafka_group_name = 'group1',  
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 1,
    kafka_thread_per_consumer = 0

CREATE MATERIALIZED VIEW IF NOT EXISTS default.test_mv TO test_to
AS
SELECT *
FROM default.test_kafka SETTINGS log_query_views = 1;

INSERT INTO test_kafka FORMAT JSONEachRow {"key": "key1", "value": 1};


SELECT * FROM system.query_views_log

0 rows in set. Elapsed: 0.002 sec.
```

**Expected behavior**
There should be an entry in `query_views_log`, so it seems when using a Kafka table engine and a MV is attached to it the `query_views_log` does not get populated.

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix system.query_views_log for MVs that are pushed from background threads (`Buffer`, `Distributed`, `system.*_log`)

Some of such places:
- push from Buffer
- push from Distributed sends
- system.*_log workers

Before #47564 it simply does not work, but after it throws LOGICAL_ERROR
in such situation.

v2: remove expired() check after #46709 got merged
v3: use ThreadGroupStatus ctor with ContextPtr (after #47564)

Cc: @Algunenano 
Fixes: #47311

### CODE REVIEW

File: src/Processors/Transforms/buildPushingToViewsChain.cpp [hunk 1]
```diff
@@ -274,6 +274,9 @@ Chain buildPushingToViewsChain(
             running_group = current_thread->getThreadGroup();
         else
             running_group = std::make_shared<ThreadGroupStatus>();
+        /// Always set query_context for system.query_views_log
```
Comment (Algunenano) [inline src/Processors/Transforms/buildPushingToViewsChain.cpp:277]: TBH, I don't remember why I never implemented `query_views_log` for background inserts. I remember testing it and we have such views in production, but I don't remember why I decided to not work on it. Thanks!

Will this play well with https://github.com/ClickHouse/ClickHouse/pull/40732/? (It was your fix too :heart:)
Or worded better: will the memory / objects attached to that context be freed at the end of the MV execution or will they live forever attached to the main context?

Comment (azat) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:277]: >will the memory / objects attached to that context be freed at the end of the MV execution or will they live forever attached to the main context?

Yes, it should be OK.
Since there was a problem with global `ThreadGroupStatus` (`MainThreadStatus::getInstance().getThreadGroup()`)

Comment (Algunenano) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:277]: Ok, now I remember one of the potential problems for this.

If you create a MV on top of system.query_views_log (for aggregation/analysis later) then you will have new logs constantly:

```
CREATE TABLE a
(
    `a` Int64
)
ENGINE = MergeTree
ORDER BY a;

CREATE TABLE b AS a;

CREATE MATERIALIZED VIEW a_to_b TO b AS
SELECT *
FROM a;

-- Very stupid MV to showcase the example
CREATE MATERIALIZED VIEW query_views_log_to_b TO b AS
SELECT count()
FROM system.query_views_log;

INSERT INTO a SELECT *
FROM numbers(100);
```


This will create an infinite number of rows (it will keep creating new rows related to the MV from query_views_log which would trigger a new row):

```
Row 1:
──────
event_date:              2023-02-22
event_time:              2023-02-22 10:20:13
event_time_microseconds: 2023-02-22 10:20:13.587659
view_duration_ms:        0
initial_query_id:        77a42294-bf5e-46bd-bc54-502017df4074
view_name:               default.a_to_b
view_uuid:               0a88273e-fe84-4796-81c6-c19e87d2756f
view_type:               Materialized
view_query:              SELECT * FROM default.a
view_target:             default.b
read_rows:               100
read_bytes:              800
written_rows:            100
written_bytes:           800
peak_memory_usage:       0
ProfileEvents:           {'FileOpen':7,'WriteBufferFromFileDescriptorWrite':7,'WriteBufferFromFileDescriptorWriteBytes':741,'IOBufferAllocs':14,'IOBufferAllocBytes':3242866,'DiskWriteElapsedMicroseconds':24,'InsertedRows':100,'InsertedBytes':800,'SelectedRows':100,'SelectedBytes':800,'MergeTreeDataWriterRows':100,'MergeTreeDataWriterUncompressedBytes':800,'MergeTreeDataWriterCompressedBytes':497,'MergeTreeDataWriterBlocks':1,'MergeTreeDataWriterBlocksAlreadySorted':1,'InsertedCompactParts':1,'ContextLock':29,'RWLockAcquiredReadLocks':4,'RealTimeMicroseconds':610,'SoftPageFaults':8}
status:                  QueryFinish
exception_code:          0
exception:               
stack_trace:             

Row 2:
──────
event_date:              2023-02-22
event_time:              2023-02-22 10:20:18
event_time_microseconds: 2023-02-22 10:20:18.768816
view_duration_ms:        0
initial_query_id:        
view_name:               default.query_views_log_to_b
view_uuid:               6d5ecb51-9d58-4c3c-a0af-1d122682d41b
view_type:               Materialized
view_query:              SELECT count() FROM system.query_views_log
view_target:             default.b
read_rows:               0
read_bytes:              0
written_rows:            1
written_bytes:           0
peak_memory_usage:       0
ProfileEvents:           {'ArenaAllocChunks':1,'ArenaAllocBytes':4096,'InsertedRows':1,'SelectedRows':1,'SelectedBytes':1,'ContextLock':23,'RWLockAcquiredReadLocks':4,'RealTimeMicroseconds':391,'SoftPageFaults':17}
status:                  QueryFinish
exception_code:          0
exception:               
stack_trace:             

Row 3:
──────
event_date:              2023-02-22
event_time:              2023-02-22 10:20:26
event_time_microseconds: 2023-02-22 10:20:26.270970
view_duration_ms:        0
initial_query_id:        
view_name:               default.query_views_log_to_b
view_uuid:               6d5ecb51-9d58-4c3c-a0af-1d122682d41b
view_type:               Materialized
view_query:              SELECT count() FROM system.query_views_log
view_target:             default.b
read_rows:               0
read_bytes:              0
written_rows:            1
written_bytes:           0
peak_memory_usage:       0
ProfileEvents:           {'ArenaAllocChunks':1,'ArenaAllocBytes':4096,'InsertedRows':1,'SelectedRows':1,'SelectedBytes':1,'ContextLock':23,'RWLockAcquiredReadLocks':4,'RealTimeMicroseconds':404,'SoftPageFaults':7}
status:                  QueryFinish
exception_code:          0
exception:               
stack_trace:             

Row 4:
──────
event_date:              2023-02-22
event_time:              2023-02-22 10:20:33
event_time_microseconds: 2023-02-22 10:20:33.773233
view_duration_ms:        0
initial_query_id:        
view_name:               default.query_views_log_to_b
```

I'm not sure how how to best address this to avoid recursive inserts, or maybe it's not necessary to prevent them.

Comment (azat) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:277]: There is the same issue for `system.text_log`, each flushing to `text_log` creates few messages that will be flushed again after, so I don't think it is a problem (anyway I guess there will be almost 0 users for MV over `system.query_views_log` and if so, this should be understandable)

Plus this is not only about `system.*_log` tables but also about Buffer flushes and so on.

**Comment by azat** [comment]
>[Stateless tests flaky check (asan) — fail: 12, passed: 89](https://s3.amazonaws.com/clickhouse-test-reports/46668/015991bc5e20c787851050c2eaa13f0fef3aac00/stateless_tests_flaky_check__asan_.html)

The failure is real, this is because the query context was wrong, here is a fix - #46709

**Comment by azat** [comment]
>[Stress test (asan) — Sanitizer assert (in stderr.log)](https://s3.amazonaws.com/clickhouse-test-reports/46668/210f25b78e5556f465adc9696451ed7455a30ef5/stress_test__asan_.html)

```
==1657==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61b000b958b8 at pc 0x000035c57643 bp 0x7f9538821270 sp 0x7f9538821268
READ of size 8 at 0x61b000b958b8 thread T1967
    #0 0x35c57642 in std::__1::shared_ptr<DB::InternalTextLogsQueue>::get[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:801:16
    #1 0x35c57642 in std::__1::shared_ptr<DB::InternalTextLogsQueue>::operator bool[abi:v15000]() const build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:833:16
    #2 0x35c57642 in DB::TCPHandler::sendLogs() build_docker/../src/Server/TCPHandler.cpp:1943:10
    #3 0x35c72e50 in DB::TCPHandler::runImpl()::$_2::operator()() const build_docker/../src/Server/TCPHandler.cpp:304:21
    #4 0x35c72e50 in decltype(std::declval<DB::TCPHandler::runImpl()::$_2&>()()) std::__1::__invoke[abi:v15000]<DB::TCPHandler::runImpl()::$_2&>(DB::TCPHandler::runImpl()::$_2&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #5 0x35c72e50 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::TCPHandler::runImpl()::$_2&>(DB::TCPHandler::runImpl()::$_2&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #6 0x35c72e50 in std::__1::__function::__default_alloc_func<DB::TCPHandler::runImpl()::$_2, void ()>::operator()[abi:v15000]() build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #7 0x35c72e50 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TCPHandler::runImpl()::$_2, void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #8 0x206bc6bb in SignalListener::onFault(int, siginfo_t const&, ucontext_t*, StackTrace const&, unsigned int, DB::ThreadStatus*) const build_docker/../src/Daemon/BaseDaemon.cpp:409:25
    #9 0x206b83b0 in SignalListener::run()::'lambda'()::operator()() const build_docker/../src/Daemon/BaseDaemon.cpp:257:41
    #10 0x206b83b0 in decltype(std::declval<SignalListener::run()::'lambda'()>()()) std::__1::__invoke[abi:v15000]<SignalListener::run()::'lambda'()>(SignalListener::run()::'lambda'()&&) build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #11 0x206b83b0 in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, SignalListener::run()::'lambda'()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, SignalListener::run()::'lambda'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/llvm-project/libcxx/include/thread:284:5
    #12 0x206b83b0 in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, SignalListener::run()::'lambda'()>>(void*) build_docker/../contrib/llvm-project/libcxx/include/thread:295:5
    #13 0x7fa726d7a608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #14 0x7fa726c9f132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

Address 0x61b000b958b8 is a wild pointer inside of access range of size 0x000000000008.
SUMMARY: AddressSanitizer: heap-buffer-overflow build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:801:16 in std::__1::shared_ptr<DB::InternalTextLogsQueue>::get[abi:v15000]() const
```

And also

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.02.23 12:21:58.078097 [ 2313 ] {48af83d8-51f5-482f-83cc-c78191b54095} <Fatal> : Logical error: 'Operation `completePartAndResetDownloader` can be done only by downloader. (CallerId: None:2313, downloader id: 48af83d8-51f5-482f-83cc-c78191b54095:2313)'.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.02.23 12:21:58.079360 [ 2287 ] {48af83d8-51f5-482f-83cc-c78191b54095} <Fatal> : Logical error: 'Operation `write` can be done only by downloader. (CallerId: None:2287, downloader id: 48af83d8-51f5-482f-83cc-c78191b54095:2287)'.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.02.23 12:21:58.079684 [ 2381 ] {48af83d8-51f5-482f-83cc-c78191b54095} <Fatal> : Logical error: 'Operation `completePartAndResetDownloader` can be done only by downloader. (CallerId: None:2381, downloader id: 48af83d8-51f5-482f-83cc-c78191b54095:2381)'.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.02.23 12:21:58.079701 [ 2332 ] {48af83d8-51f5-482f-83cc-c78191b54095} <Fatal> : Logical error: 'Operation `write` can be done only by downloader. (CallerId: None:2332, downloader id: 48af83d8-51f5-482f-83cc-c78191b54095:2332)'.
```

Seems that it is a known issue (https://github.com/ClickHouse/ClickHouse/pull/46624#issuecomment-1441566298)

>[Stress test (debug) — Killed by signal (in clickhouse-server.log)](https://s3.amazonaws.com/clickhouse-test-reports/46668/210f25b78e5556f465adc9696451ed7455a30ef5/stress_test__debug_.html)

```
 [ 124279 ] {} <Fatal> BaseDaemon: (version 23.2.1.1, build id: 23BCEF8A5D6FACFF75D5CB79CBECD30FFC68ECF1) (from thread 1628) (query_id: 9c694f24-aa57-4652-a161-8503bef89657::202302_195_208_1) (query: ) Received signal Illegal instruction (4)
 [ 124279 ] {} <Fatal> BaseDaemon: Illegal operand.
 [ 124279 ] {} <Fatal> BaseDaemon: Stack trace: 0x30ed4a68 0x30ed4f84 0x30ed471b 0x21ad0d05 0x2c2155e1 0x2c21552d 0x2c2154d5 0x2c2154b9 0x2c21512e 0x1919ce54 0x1919cdf9 0x21dee86c 0x21dee7aa 0x21dee775 0x21dee74d 0x21dee6f5 0x21dee579 0x21dee3af 0x21dee2d9 0x21dedcb5 0x21dee1f8 0x2c20aec7 0x2b6ac4e7 0x2b6af48e 0x2b6af435 0x2b6af419 0x2b6af12e 0x1919ce54 0x1919cdf9 0x28e20d0c 0x28e250ed 0x28e25095 
 [ 124279 ] {} <Fatal> BaseDaemon: 4. /build/build_docker/../contrib/llvm-project/compiler-rt/lib/gwp_asan/platform_specific/utilities_posix.cpp:27: gwp_asan::die(char const*) @ 0x30ed4a68 in /usr/bin/clickhouse
 [ 124279 ] {} <Fatal> BaseDaemon: 5. /build/build_docker/../contrib/llvm-project/compiler-rt/lib/gwp_asan/platform_specific/guarded_pool_allocator_posix.cpp:98: gwp_asan::GuardedPoolAllocator::deallocateInGuardedPool(void*, unsigned long) const @ 0x30ed4f84 in /usr/bin/clickhouse
 [ 124279 ] {} <Fatal> BaseDaemon: 6. /build/build_docker/../contrib/llvm-project/compiler-rt/lib/gwp_asan/guarded_pool_allocator.cpp:322: gwp_asan::GuardedPoolAllocator::deallocate(void*) @ 0x30ed471b in /usr/bin/clickhouse
```

- https://github.com/ClickHouse/ClickHouse/pull/45226#issuecomment-1431205026

**Comment by azat** [comment]
Can someone take a look please?

**Comment by azat** [comment]
Kind ping on this one, thanks.

**Comment by azat** [comment]
After #46709 the patch became cleaner, no more icky `expired()` check

File: src/Interpreters/ThreadStatusExt.cpp [hunk 2]
```diff
@@ -480,7 +480,10 @@ void ThreadStatus::logToQueryViewsLog(const ViewRuntimeData & vinfo)
 {
     auto query_context_ptr = query_context.lock();
     if (!query_context_ptr)
+    {
+        LOG_ERROR(log, "No query context, query_views_log will not be written (this should never happens)");
```
Comment (Algunenano) [inline src/Interpreters/ThreadStatusExt.cpp:484]: Super minor nitpick: `happens` -> `happen`

File: src/Processors/Transforms/buildPushingToViewsChain.cpp [hunk 3]
```diff
@@ -270,11 +270,14 @@ Chain buildPushingToViewsChain(
...
+        /// otherwise entry to the system.query_views_log will not be added
+        /// (see ThreadStatus::logToQueryViewsLog())
         ThreadGroupStatusPtr running_group;
-        if (current_thread && current_thread->getThreadGroup())
+        if (current_thread)
             running_group = current_thread->getThreadGroup();
-        else
-            running_group = std::make_shared<ThreadGroupStatus>();
+        if (!running_group)
+            running_group = std::make_shared<ThreadGroupStatus>(context);
```
Comment (CheSema) [inline src/Processors/Transforms/buildPushingToViewsChain.cpp:280]: Can you help with the question? When there is a current_thread->getThreadGroup and when there is no group in current thread?

One more question, in case then current_thread do not have TG, why is it ring to make a TG for each view insted make one for all?

Comment (CheSema) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:280]: Oh I see. The is recursion call buildPushingToViewsChain. And that call appears 6 times in the code. Actually, as for me, it not so much to touch. An only one of them is trigger: src/Interpreters/InterpreterInsertQuery.cpp:276.

In order to achieve one TG for all, we could either pass it through the function args buildPushingToViewsChain.

Or:

Move the block
```
ThreadGroupStatusPtr running_group;
        if (current_thread)
            running_group = current_thread->getThreadGroup();
        if (!running_group)
            running_group = std::make_shared<ThreadGroupStatus>(context);
```
out of the for loop. Then, when we had to make new TG, bind current thread with this new TG with ThreadGroupSwitcher for the scope of buildPushingToViewsChain. That makes following recursive calls to see the new TG. (Or rewrite it in other similat way: if no current_thread->getThreadGroup(), the create it add attach temporarily)

Actually, all this things about finding/creating/attaching TG to the thread should  be done between (or inside) InterpreterInsertQuery::buildChainImpl and buildPushingToViewsChain. In that way it looks more simple, without recursion context in the mind.

How do you see this? I do not insist for such approach. You are solving specific problem and the way is OK. 
However one TG for MVs allows to collect all the memory accounting and profiles counters in one place: that TG. In case if that had been done in scope if query, all that information would be binded to the query. Your solution already do that binding, that is cool.

Comment (CheSema) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:280]: One thing: no need to use ThreadGroupSwitcher as long as we bind new thread group to the thread without thread group. That binding could be permanent.

Comment (azat) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:280]: >Then, when we had to make new TG, bind current thread with this new TG with ThreadGroupSwitcher for the scope of buildPushingToViewsChain. That makes following recursive calls to see the new TG. (Or rewrite it in other similat way: if no current_thread->getThreadGroup(), the create it add attach temporarily)

Well, it will work, but this implicit usage looks not clean.

>Actually, all this things about finding/creating/attaching TG to the thread should be done between (or inside) InterpreterInsertQuery::buildChainImpl and buildPushingToViewsChain. In that way it looks more simple, without recursion context in the mind.

The reason I kept it in `buildPushingToViewsChain`, because it play low level games to manipulate the `ThreadStatus`, and this thing cannot moved to the `InterpreterInsertQuery`.

And this place will be moved to the `InterpreterInsertQuery`, then there will be two different places that will do this low level stuff, at first I thought that this is a bad idea, but while writing this paragraph, I slightly changed my mind, so I guess it is OK.

>One thing: no need to use ThreadGroupSwitcher as long as we bind new thread group to the thread without thread group. That binding could be permanent.

Yes, make sense, missed the patches where `MemoryTrackerThreadSwitcher` had been renamed to `ThreadGroupSwitcher`.

But I found it odd that it is located in the `MergeTree` code, so what I'm going to do is:
- move `ThreadGroupSwitcher` into a separate file
- rename `ThreadGroupStatus` to `ThreadGroup`
- fix this place with multiple TG attached here
But I think it is better to do this on top of this  PR in a separate one, @CheSema objections?

**Review by CheSema — APPROVED** [review]

File: src/Processors/Transforms/buildPushingToViewsChain.cpp (hunk 3 above)
Comment (CheSema) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:280]: Sounds good!
ThreadGroupSwitcher deserve better place indeed.
However here is it has no use since we create and bind designated TG only if there is no query scope TG. That binding could be permanent without ThreadGroupSwitcher. The other case: if there is a query scope TG, we attach it to all MV's thread statuses, in other words we reuse it.

Comment (azat) [reply src/Processors/Transforms/buildPushingToViewsChain.cpp:280]: >That binding could be permanent without ThreadGroupSwitcher

Yes, indeed.

So here it is - #48543
