### PR TITLE
Fix crash in flattened Dynamic serialization

### LINKED ISSUE #81670: Logical error: 'Bad cast from type DB::ColumnDecimal<DB::DateTime64> to DB::ColumnArray'
### Describe the bug

Easy to reproduce.

### How to reproduce
Run:
```sql
CREATE TABLE t0 (c0 Variant(Int,JSON(max_dynamic_paths=3, max_dynamic_types=13))) ENGINE = SummingMergeTree() ORDER BY tuple();
INSERT INTO TABLE t0 (c0) VALUES ('{"c0":"992:20:55.723081186","😆":{"c1":0.2173147,"c0.c1":[true,"-48:28:48"]}}'), ('{"😉😉":null,"😉😉":{},"😆":"133.255.110.124"}'), ('{"c0":[[null],"叫"],"😆":{"😉😉":{}}}'), (1683795563), ('{}'), ('{"c0.c1":"went","c1":["got"],"😆":{}}'), (982353035), (936165152), ('{"😉😉":[]}'), ('{"c1":"99.32.225.166"}'), (-1639743405), ('{"😆":[["1982-11-02 23:19:29.196875786"]]}'), (-194589659), (-1589702347), (1729726898), (1837618099), (1095229141), (-704854738), ('{"😉😉":"c:0:d:3:2:6:9:e"}'), (1245962182), (-1948473775), (771485528), (-1271733140), (-109091627), ('{"c1":"2057-03-29"}');
INSERT INTO TABLE t0 (c0) VALUES ('{"c0.c1":[]}'), ('{"😆":"2062-12-18 16:51:55.946416515","c0.c1":[[],{},[]],"😆":"😉"}'), ('{"c0.c1":"7:9:a:c:b:7:a:c"}'), ('{"😉😉":"230.232.166.39"}'), (-673463142), (-1607537269), ('{"c0.c1":[[],{}],"😉😉":[[294]]}'), (2158150), (-539108270), (-591335476), ('{}'), (-1687367455), ('{}'), ('{}'), ('{}'), ('{"c0":{"😉😉":["2039-11-02","728ef23e-fcbe-b1fb-6074-7dd13779ae4c"],"😉😉":["2071-11-04","兄弟姐妹","2061-03-28 19:00:48.403210868"]}}'), ('{"😉😉":{}}'), (-346391673), ('{"😆":[],"c1":"165:21:14"}'), ('{}'), (656028231), (-314759878), ('{"c0":["美国"],"c0":null,"c1":{}}'), ('{"c0":6872.02,"c1":"9:e:f:6:a:e:5:d"}'), ('{"c0":0.7,"😉😉":{"c0":{"c1":["286:45:04",-7076004352056519724]},"😉😉":"1921-08-18","😉😉":{"c0.c1":["41.142.87.9",false],"c0.c1":[true,"美国",362],"😆":true}}}');
SELECT c0 FROM t0 FINAL SETTINGS output_format_native_use_flattened_dynamic_and_json_serialization = 1;

```

### Error message and/or stacktrace

Stack trace:
```
Logical error: 'Bad cast from type DB::ColumnDecimal<DB::DateTime64> to DB::ColumnArray'.
Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001d34ea92
1. src/Common/Exception.cpp:110: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000011de9166
2. src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000ba020ac
3. src/Common/Exception.h:137: DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000ba010f6
4. src/Common/assert_cast.h:48: DB::ColumnArray const& assert_cast<DB::ColumnArray const&, DB::IColumn const&>(DB::IColumn const&) @ 0x000000000c3f0ece
5. src/DataTypes/Serializations/SerializationArray.cpp:67: DB::SerializationArray::serializeBinary(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const @ 0x00000000160be911
6. src/DataTypes/Serializations/SerializationDynamic.cpp:667: DB::SerializationDynamic::serializeBinary(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const @ 0x00000000160dc871
7. src/Columns/ColumnObject.cpp:771: DB::ColumnObject::serializePathAndValueIntoSharedData(DB::ColumnString*, DB::ColumnString*, std::basic_string_view<char, std::char_traits<char>>, DB::IColumn const&, unsigned long) @ 0x0000000017fcd6ef
8. src/DataTypes/Serializations/SerializationObjectHelpers.cpp:72: DB::unflattenAndInsertPaths(std::vector<String, std::allocator<String>> const&, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&&, DB::ColumnObject&, unsigned long) @ 0x000000001616075f
9. src/DataTypes/Serializations/SerializationObject.cpp:901: DB::SerializationObject::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x0000000016141998
10. src/DataTypes/Serializations/SerializationVariant.cpp:574: DB::SerializationVariant::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x0000000016189f5e
11. src/Formats/NativeReader.cpp:99: DB::NativeReader::readData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, std::optional<DB::FormatSettings> const&, unsigned long, double) @ 0x0000000019008d9c
12. src/Formats/NativeReader.cpp:244: DB::NativeReader::read() @ 0x00000000190099fd
13. src/Client/Connection.cpp:1396: DB::Connection::receiveDataImpl(DB::NativeReader&) @ 0x0000000018e5bb99
14. src/Client/Connection.cpp:1377: DB::Connection::receivePacket() @ 0x0000000018e5ac66
15. src/Client/ClientBase.cpp:1365: DB::ClientBase::receiveAndProcessPacket(std::shared_ptr<DB::IAST>, bool) @ 0x0000000018e303fe
16. src/Client/ClientBase.cpp:1340: DB::ClientBase::receiveResult(std::shared_ptr<DB::IAST>, int, bool) @ 0x0000000018e2fed4
17. src/Client/ClientBase.cpp:1249: DB::ClientBase::processOrdinaryQuery(String, std::shared_ptr<DB::IAST>) @ 0x0000000018e2eafc
18. src/Client/ClientBase.cpp:2243: DB::ClientBase::processParsedSingleQuery(std::basic_string_view<char, std::char_traits<char>>, std::shared_ptr<DB::IAST>, bool&, unsigned long) @ 0x0000000018e2ce9d
19. src/Client/ClientBase.cpp:2615: DB::ClientBase::executeMultiQuery(String const&) @ 0x0000000018e38059
20. src/Client/ClientBase.cpp:2802: DB::ClientBase::processQueryText(String const&) @ 0x0000000018e3917b
21. src/Client/ClientBase.cpp:3357: DB::ClientBase::runInteractive() @ 0x0000000018e4066b
22. programs/client/Client.cpp:405: DB::Client::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000011ffd1a7
23. base/poco/Util/src/Application.cpp:315: Poco::Util::Application::run() @ 0x000000001d415a51
24. programs/client/Client.cpp:1145: mainEntryClickHouseClient(int, char**) @ 0x00000000120085a1
25. programs/main.cpp:321: main @ 0x000000000b9f9e87
26. __libc_start_call_main @ 0x000000000002a338
27. __libc_start_main_impl @ 0x000000000002a3fb
28. _start @ 0x000000000b9eb02e
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash in flattened Dynamic serialization.

Closes https://github.com/ClickHouse/ClickHouse/issues/81670

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/DataTypes/Serializations/SerializationDynamicHelpers.cpp [hunk 1]
```diff
@@ -206,24 +206,24 @@ void unflattenDynamicColumn(FlattenedDynamicColumn && flattened_column, ColumnDy
...
+        if (!dynamic_column.addNewVariant(flattened_column.types[i], type_name))
         {
             first_index_for_shared_variant = i;
             break;
         }
     }
 
+    /// Map (index -> discriminator) for types that were successfully added as variants.
+    std::unordered_map<size_t, ColumnVariant::Discriminator> index_to_discriminator;
+    for (size_t i = 0; i != first_index_for_shared_variant; ++i)
```
Comment (Ergus) [inline src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:223]: Minor: In this case it is more clear to use the `<` operator instead of `!=`

File: src/DataTypes/Serializations/SerializationDynamicHelpers.cpp [hunk 2]
```diff
@@ -206,24 +206,24 @@ void unflattenDynamicColumn(FlattenedDynamicColumn && flattened_column, ColumnDy
...
+        index_to_discriminator[i] = dynamic_column.getVariantInfo().variant_name_to_discriminator.at(flattened_column.types[i]->getName());
```
Comment (Ergus) [inline src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:224]: It is not a good idea to use the `at` operator without a custom error handling in order to return a precise error message to the user.  So I would recommend to use `try-catch` or better use a `find + != end() + throw` with precise error message about the not available key if that happens.

**Review by Ergus — CHANGES_REQUESTED** [review]
Hope this helps

File: src/DataTypes/Serializations/SerializationDynamicHelpers.cpp (hunk 2 above)
Comment (Avogar) [reply src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:224]: Here it's not needed because `flattened_column.types[i]->getName()` is guaranteed to be inside `variant_name_to_discriminator` by the the logic of the code above

File: src/DataTypes/Serializations/SerializationDynamicHelpers.cpp (hunk 1 above)
Comment (Avogar) [reply src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:223]: To be honest, I don't see why it's more clear. Both operators are equivalent here as `i` is guaranteed to be less or equal than `first_index_for_shared_variant`

File: src/DataTypes/Serializations/SerializationDynamicHelpers.cpp (hunk 2 above)
Comment (Ergus) [reply src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:224]: Just a comment/question then: 

If the value is guarantee to be there, then why to use the `at` function instead of the `[]` operator that generates simpler code?

Comment (Avogar) [reply src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:224]: Because `getVariantInfo()` returns constant reference and `[]` is not constant operator (`at` is constant method)

File: src/DataTypes/Serializations/SerializationDynamicHelpers.cpp (hunk 1 above)
Comment (Ergus) [reply src/DataTypes/Serializations/SerializationDynamicHelpers.cpp:223]: Probably is a matter of style. but for ranges usually is clearer the `<` as is more explicit., any way, it was just a comment

**Comment by Avogar** [comment]
[Integration tests (release, 3/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82117&sha=e0a5920358d314759ff53c39507e5920db4833dd&name_0=PR&name_1=Integration%20tests%20%28release%2C%203%2F4%29) - `Job timeout expired` . @maxknv Maybe we should increase the timeout or split tests more?
