### PR TITLE
Fix crash in `loop` function used on top of Distributed storage; respect the LIMIT clause

### LINKED ISSUE #77030: Loop function with remote SEGV
### Describe the bug

Easy to reproduce, seems to exist since the `loop` function was added.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/f7a99717-c417-44ca-bd40-1373ae390913

### Error message and/or stacktrace

Stack trace:
```
#0  DB::StorageDistributed::read (this=0x7ffeb738e420, query_plan=..., storage_snapshot=..., query_info=..., local_context=..., processed_stage=DB::QueryProcessingStage::FetchColumns) at src/Storages/StorageDistributed.cpp:879
#1  0x000055556beacd68 in DB::LoopSource::generate (this=0x7ffeb73f6020) at src/Processors/QueryPlan/ReadFromLoopStep.cpp:57
#2  0x000055556ba3da3a in DB::ISource::tryGenerate (this=0x7ffd7eecb388) at src/Processors/ISource.cpp:139
#3  0x000055556ba3d727 in DB::ISource::work (this=0x7ffeb73f6020) at src/Processors/ISource.cpp:108
#4  0x000055556ba583ef in DB::executeJob (node=0x7ffd3164b600, read_progress_callback=0x7ffeb722b460) at src/Processors/Executors/ExecutionThreadContext.cpp:53
#5  DB::ExecutionThreadContext::executeTask (this=0x7ffd40145000) at src/Processors/Executors/ExecutionThreadContext.cpp:102
#6  0x000055556ba4d4e5 in DB::PipelineExecutor::executeStepImpl (this=this@entry=0x7ffeb73bca18, thread_num=thread_num@entry=0, yield_flag=yield_flag@entry=0x0) at src/Processors/Executors/PipelineExecutor.cpp:296
#7  0x000055556ba4d79e in DB::PipelineExecutor::executeSingleThread (this=0x7ffd40129058, this@entry=0x7ffeb73bca18, thread_num=140726732895112, thread_num@entry=0) at src/Processors/Executors/PipelineExecutor.cpp:262
#8  0x000055556ba4bfc7 in DB::PipelineExecutor::executeImpl (this=this@entry=0x7ffeb73bca18, num_threads=num_threads@entry=1, concurrency_control=<optimized out>) at src/Processors/Executors/PipelineExecutor.cpp:454
#9  0x000055556ba4b7d4 in DB::PipelineExecutor::execute (this=0x7ffeb73bca18, num_threads=1, concurrency_control=true) at src/Processors/Executors/PipelineExecutor.cpp:128
#10 0x000055556ba5b38b in DB::threadFunction (data=..., thread_group=..., num_threads=1, concurrency_control=true) at src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76
#11 DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const (this=0x7ffd371eb1e8) at src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:102
#12 std::__1::__invoke[abi:se190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) (__f=...)
    at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149
#13 _ZNSt3__118__apply_tuple_implB8se190107IRZN2DB28PullingAsyncPipelineExecutor4pullERNS1_5ChunkEmE3$_0RNS_5tupleIJEEETpTnmJEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE (__f=..., __t=...)
    at contrib/llvm-project/libcxx/include/tuple:1354
#14 std::__1::apply[abi:se190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) (__f=..., 
    __t=...) at contrib/llvm-project/libcxx/include/tuple:1358
#15 ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}::operator()() (this=<optimized out>) at src/Common/ThreadPool.h:310
#16 std::__1::__invoke[abi:se190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) (__f=...) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149
#17 std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}&) (__args=...) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224
#18 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()>::operator()[abi:se190107]() (this=<optimized out>) at contrib/llvm-project/libcxx/include/__functional/function.h:210
#19 std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>)
    at contrib/llvm-project/libcxx/include/__functional/function.h:610
#20 0x0000555564e27bf2 in std::__1::__function::__policy_func<void ()>::operator()[abi:se190107]() const (this=0x7ffd371eb5d0) at contrib/llvm-project/libcxx/include/__functional/function.h:716
#21 std::__1::function<void()>::operator() (this=0x7ffd371eb5d0) at contrib/llvm-project/libcxx/include/__functional/function.h:989
#22 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker (this=0x7ffd3b5fb7c0) at src/Common/ThreadPool.cpp:795
#23 0x0000555564e2de60 in std::__1::__invoke[abi:se190107]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, , void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) (__f=<optimized out>, __a0=<optimized out>) at contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117
#24 std::__1::__thread_execute[abi:se190107]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) (__t=...) at contrib/llvm-project/libcxx/include/__thread/thread.h:192
#25 std::__1::__thread_proxy[abi:se190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*> >(void*) (__vp=<optimized out>) at contrib/llvm-project/libcxx/include/__thread/thread.h:201
#26 0x00007ffff7ca1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#27 0x00007ffff7d33a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### PR DESCRIPTION
**Pull request by jkartseva**
The first commit fixes the original issue. The crash occurred because `cluster` was not set for the query information, and it is fixed by overloading `getQueryProcessingStage`.
The second commit addresses another issue discovered during testing – the LIMIT clause was ignored, causing an infinite loop.
Fixes: #77030 

### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix a crash in the `loop` function when used with the `remote` function family. Ensure the LIMIT clause is respected in `loop(remote(...))`.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Processors/QueryPlan/ReadFromLoopStep.cpp [hunk 1]
```diff
@@ -74,14 +76,24 @@ namespace DB
...
                         return chunk;
-                    }
 
+                    size_t remaining_rows = query_info.trivial_limit + chunk.getNumRows() - rows_read;
+                    auto columns = chunk.detachColumns();
+                    for (auto & col : columns)
+                    {
+                        col = col->cut(0, remaining_rows);
+                    }
+                    return {std::move(columns), remaining_rows};
```
Comment (Avogar) [inline src/Processors/QueryPlan/ReadFromLoopStep.cpp:96]: Why do we need it? Won't `LIMIT` be applied later in `LimitTransform`?

Comment (jkartseva) [reply src/Processors/QueryPlan/ReadFromLoopStep.cpp:96]: Without the change, LIMIT does not apply, and the following query runs in an infinite loop until cancelled:
```
SELECT * FROM loop(remote('localhost:9000', currentDatabase(), 't0')) tx LIMIT 3;
```
I'll take a look at the  LimitTransform, maybe something is missing.

Comment (alexey-milovidov) [reply src/Processors/QueryPlan/ReadFromLoopStep.cpp:96]: IIRC, when querying a single remote shard, we offload the LIMIT entirely to the remote server.
