### PR TITLE
Fix UBSan error in `ParquetDataBuffer`

### LINKED ISSUE #74512: Test `02998_native_parquet_reader` is flaky
It is broken around the 9th of January.

https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDI5OThfbmF0aXZlX3BhcnF1ZXRfcmVhZGVyJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

### PR DESCRIPTION
**Pull request by arthurpassos**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix mem alignment issue reported by UBSan https://github.com/ClickHouse/ClickHouse/issues/74512

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, BuzzHouse, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit e1ecbf01a248862388ca1cf490600b603d49e81f with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74534/e1ecbf01a248862388ca1cf490600b603d49e81f/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/74534/e1ecbf01a248862388ca1cf490600b603d49e81f/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h [hunk 1]
```diff
@@ -54,11 +54,14 @@ class ParquetDataBuffer
...
-        const ParquetType* src = reinterpret_cast<const ParquetType*>(data);
-
         for (std::size_t i = 0; i < count; i++)
         {
-            dst[i] = static_cast<TValue>(src[i]);
+            ParquetType temp;
+            auto offset = i * sizeof(ParquetType);
+
+            // necessary to prevent memory alignment issues https://github.com/ClickHouse/ClickHouse/issues/74512#issuecomment-2587260001
+            memcpy(&temp, data + offset, sizeof(ParquetType));
```
Comment (arthurpassos) [inline src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h:63]: I can also just add `NO_SANITIZE_UNDEFINED` and keep the same function as before. What do you prefer @nickitat?

Comment (nickitat) [reply src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h:63]: I'd prefer the current solution, and I'd also suggest to replace this code with a call to `unalignedLoad`

File: src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h [hunk 2]
```diff
@@ -54,11 +54,10 @@ class ParquetDataBuffer
         auto necessary_bytes = count * sizeof(ParquetType);
         checkAvaible(necessary_bytes);
 
-        const ParquetType* src = reinterpret_cast<const ParquetType*>(data);
-
         for (std::size_t i = 0; i < count; i++)
         {
-            dst[i] = static_cast<TValue>(src[i]);
+            auto offset = i * sizeof(ParquetType);
+            dst[i] = unalignedLoad<TValue>(data + offset);
```
Comment (nickitat) [inline src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h:60]: is it guaranteed that `sizeof(ParquetType) == sizeof(TValue)`. let's add `static_assert` if so.

Comment (arthurpassos) [reply src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h:60]: It is guaranteed that `sizeof(ParquetType) <= sizeof(TValue)`

Comment (nickitat) [reply src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h:60]: is it fine that we don't consider endianness of the machine running this code. afaiu parquet always writes in LE, but what if we're running on a BE?

Comment (arthurpassos) [reply src/Processors/Formats/Impl/Parquet/ParquetDataBuffer.h:60]: Native reader is only available on LE systems: https://github.com/ClickHouse/ClickHouse/blob/4212fa4210175b5566d7571eb2a4f40379ace550/src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp#L694

**Comment by nickitat** [comment]
`Integration tests (asan, old analyzer) [1/6]` - some glitch in git, I assume
`Stateless tests (release, old analyzer, s3 storage, DatabaseReplicated) [2/2]` -
* `02125_many_mutations` - https://github.com/ClickHouse/ClickHouse/issues/65589
* `02884_create_view_with_sql_security_option ` - https://github.com/ClickHouse/ClickHouse/issues/74549
* `03272_parallel_replicas_read_in_order` - https://github.com/ClickHouse/ClickHouse/issues/74554
`Stateless tests (release, ParallelReplicas, s3 storage)` - [haven't failed since yesterday](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHRvZGF5KCkgLSBJTlRFUlZBTCAnMyBtb250aHMnIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDMyOTBfZm9yY2Vfbm9ybWFsX3Byb2plY3Rpb24lJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=), maybe fixed

**Review by nickitat — APPROVED** [review]
