### PR TITLE
Fix logical optimizer with LowCardinality in new analyzer

### LINKED ISSUE #59703: [Analyzer] convert_query_to_cnf: Logical error: expects argument to have Nullable(UInt8) type but receives UInt8 after running LogicalExpressionOptimizer pass
Report: https://s3.amazonaws.com/clickhouse-test-reports/59485/25738c8313bff80f3a2e3a8e3a53101041a62f2c/ast_fuzzer__debug_.html

Slightly reduced repro:

```sql
create table d1 (key Int, value Int) engine=Memory();
create view v1 as select * from d1;
create table m as v1 engine=Merge(currentDatabase(), 'v1');

SELECT _table, key FROM m WHERE (_table = toFixedString(toFixedString(toFixedString('v1', toNullable(2)), 2), 2)) OR ((value = toLowCardinality(toNullable(10))) AND (_table = toFixedString(toNullable('v3'), 2))) OR ((value = 20) AND (_table = toFixedString(toFixedString(toFixedString('v1', 2), 2), 2)) AND (_table = toFixedString(toLowCardinality(toFixedString('v3', 2)), 2))) SETTINGS allow_experimental_analyzer = true, join_use_nulls = true, convert_query_to_cnf = true;
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fix https://github.com/ClickHouse/ClickHouse/issues/59703

cc @vdimir could be interesting to you as you added code for handling nullable

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 160f1b7fd85add76128c978f0d7ae93729b53a5e with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59766/160f1b7fd85add76128c978f0d7ae93729b53a5e/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59766/160f1b7fd85add76128c978f0d7ae93729b53a5e/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp [hunk 1]
```diff
@@ -486,7 +486,7 @@ class LogicalExpressionOptimizerVisitor : public InDepthQueryTreeVisitorWithCont
             /// first we create tuple from RHS of equals functions
             for (const auto & equals : equals_functions)
             {
-                is_any_nullable |= equals->getResultType()->isNullable();
+                is_any_nullable |= removeLowCardinality(equals->getResultType())->isNullable();
```
Comment (vdimir) [inline src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp:489]: Can `in_function->getResultType()`tat we check below  also be `LowCardinality(Nullable)` ?

**Review by vdimir — APPROVED** [review]

**Review by novikd — APPROVED** [review]

File: src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp (hunk 1 above)
Comment (antonio2368) [reply src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp:489]: hmm not sure, but if it wasn't `LowCardinality(Nullable)` in this case I don't know when it can be
