### PR TITLE
Optimized processing of ORDER BY in window functions

### LINKED ISSUE #19289: window functions: use storage sorting key
To compute a window function, we must first sort data according to `PARTITION BY` and then `ORDER BY` clauses of the window.
When the storage sorting key and the `PARTITION BY` + `ORDER BY` of the window have a common prefix, we must avoid sorting the data fully from scratch, and instead read it in (partially) sorted order and then sort incrementally.

For large amounts of data, sorting it is not feasible, so this incremental sorting is the only way to compute a window function. See an example we discussed in #18097:

> 'Crash tests' use case. Imagine a fast trading dataset.
>
> Every second you have up to 10 million transactions with a micro/nanosecond resolution.
> 
> The task is to calculate the sum and the number of transactions in the exactly X seconds window prepending the transaction. (not on the second boundary but back from the current event). Single select can extract up to several weeks of data.
> 
> This is sum over (order by transaction_time range between 'X seconds' preceding and current row).
> 10M records per second * 30 days per month * 24 * 60 * 60 seconds a day = 25T records, probably about 100TB of data compressed

### PR DESCRIPTION
**Pull request by excitoon**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Optimized processing of ORDER BY in window functions.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

Closes: #19289

### CODE REVIEW

File: src/Interpreters/ExpressionAnalyzer.h [hunk 1]
```diff
@@ -81,7 +81,7 @@ struct ExpressionAnalyzerData
   *
   * NOTE: if `ast` is a SELECT query from a table, the structure of this table should not change during the lifetime of ExpressionAnalyzer.
   */
-class ExpressionAnalyzer : protected ExpressionAnalyzerData, private boost::noncopyable, protected WithContext
+class ExpressionAnalyzer : public ExpressionAnalyzerData, private boost::noncopyable, protected WithContext
```
Comment (novikd) [inline src/Interpreters/ExpressionAnalyzer.h:84]: I don't think you need to change public interface of `ExpressionAnalyzer` for this optimization.

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+        return 0;
+    }
+
+    /// Window <- Sorting <- [Expression] <- [SettingQuotaAndLimits] <- ReadFromMergeTree
+
+    auto context = read_from_merge_tree->getContext();
+    const auto & query_info = read_from_merge_tree->getQueryInfo();
+    const auto * select_query = query_info.query->as<ASTSelectQuery>();
+
+    auto analyzer = std::make_unique<ExpressionAnalyzer>(query_info.query, query_info.syntax_analyzer_result, context);
```
Comment (novikd) [inline src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp:84]: It's strange to analyse the whole query again at this point. As I understand you need it only to call `ExpressionAnalyzer::getRootActions`. This method doesn't use any internal information of analyzer. You can use `ActionsVisitor` explicitly.

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+            }
+
+            if (definition.order_by)
+            {
+                for (const auto & column_ast : definition.order_by->children)
+                {
+                    auto actions_dag = std::make_shared<ActionsDAG>(analyzer->columns_after_window);
+                    analyzer->getRootActions(column_ast, false, actions_dag);
+                    order_by_elements_actions.emplace_back(
+                            std::make_shared<ExpressionActions>(actions_dag, ExpressionActionsSettings::fromContext(context, CompileExpressions::yes)));
```
Comment (novikd) [inline src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp:114]: This cycle is a complete copy-paste of a previous one. It can be generalised.

File: src/Processors/QueryPlan/WindowStep.h [hunk 4]
```diff
@@ -24,9 +24,9 @@ class WindowStep : public ITransformingStep
 
     void describeActions(JSONBuilder::JSONMap & map) const override;
     void describeActions(FormatSettings & settings) const override;
+    WindowDescription window_description;
```
Comment (novikd) [inline src/Processors/QueryPlan/WindowStep.h:27]: It's not used anywhere so no reason to make it public.

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 5]
```diff
@@ -1944,6 +1944,14 @@ void InterpreterSelectQuery::executeFetchColumns(QueryProcessingStage::Enum proc
         {
             if (analysis_result.optimize_read_in_order)
             {
+                for (auto & child : std::dynamic_pointer_cast<ASTSelectQuery>(query_info.query)->orderBy()->children)
+                {
+                    auto actions_dag = std::make_shared<ActionsDAG>(query_analyzer->columns_after_join);
+                    query_analyzer->getRootActions(child, false, actions_dag);
+                    analysis_result.order_by_elements_actions.emplace_back(
+                        std::make_shared<ExpressionActions>(actions_dag, ExpressionActionsSettings::fromContext(context, CompileExpressions::yes)));
+                }
```
Comment (novikd) [inline src/Interpreters/InterpreterSelectQuery.cpp:1953]: Why do we need it?

**Review by novikd — CHANGES_REQUESTED** [review]

**Comment by alexey-milovidov** [comment]
Please resolve conflicts.

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 6]
```diff
@@ -1317,7 +1317,11 @@ ActionsDAGPtr SelectQueryExpressionAnalyzer::appendOrderBy(ExpressionActionsChai
             with_fill = true;
     }
 
-    if (optimize_read_in_order)
+    if (static_cast<void *>(&order_by_elements_actions) && optimize_read_in_order)
```
[the remark this answers is not in the document]
Comment (excitoon) [reply src/Interpreters/ExpressionAnalyzer.cpp]: That was a draft part of code, fixed.

File: src/Processors/QueryPlan/Optimizations/Optimizations.h [hunk 7]
```diff
@@ -44,15 +44,19 @@ size_t tryMergeExpressions(QueryPlan::Node * parent_node, QueryPlan::Nodes &);
...
 {
-    static const std::array<Optimization, 5> optimizations =
+    static const std::array<Optimization, 6> optimizations =
     {{
         {tryLiftUpArrayJoin, "liftUpArrayJoin", &QueryPlanOptimizationSettings::optimize_plan},
         {tryPushDownLimit, "pushDownLimit", &QueryPlanOptimizationSettings::optimize_plan},
         {trySplitFilter, "splitFilter", &QueryPlanOptimizationSettings::optimize_plan},
         {tryMergeExpressions, "mergeExpressions", &QueryPlanOptimizationSettings::optimize_plan},
         {tryPushDownFilter, "pushDownFilter", &QueryPlanOptimizationSettings::filter_push_down},
+        {tryReuseStorageOrdering, "reuseStorageOrdering",&QueryPlanOptimizationSettings::optimize_plan}
```
[the remark this answers is not in the document]
Comment (excitoon) [reply src/Processors/QueryPlan/Optimizations/Optimizations.h]: Done.

File: src/Interpreters/ExpressionAnalyzer.h (hunk 1 above)
Comment (excitoon) [reply src/Interpreters/ExpressionAnalyzer.h]: Done.

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp (hunk 3 above)
Comment (excitoon) [reply src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp]: Done.

File: src/Processors/QueryPlan/WindowStep.h (hunk 4 above)
Comment (excitoon) [reply src/Processors/QueryPlan/WindowStep.h]: Done.

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp (hunk 2 above)
Comment (excitoon) [reply src/Processors/QueryPlan/Optimizations/reuseStorageOrdering.cpp]: Done.

File: src/Interpreters/InterpreterSelectQuery.cpp (hunk 5 above)
Comment (excitoon) [reply src/Interpreters/InterpreterSelectQuery.cpp]: Done. Can you please re-check?

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 8]
```diff
@@ -684,6 +687,10 @@ void makeWindowDescriptionFromAST(const Context & context,
                     order_by_element.children.front()->getColumnName(),
                     order_by_element.direction,
                     order_by_element.nulls_direction));
+
+            auto actions_dag = std::make_shared<ActionsDAG>(columns_after_join);
+            getRootActions(column_ast, false, actions_dag);
+            desc.partition_by_actions.push_back(std::move(actions_dag));
```
Comment (novikd) [inline src/Interpreters/ExpressionAnalyzer.cpp:693]: Maybe?
```suggestion
            desc.order_by_actions.push_back(std::move(actions_dag));
```

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 9]
```diff
@@ -598,7 +597,7 @@ void ExpressionAnalyzer::makeAggregateDescriptions(ActionsDAGPtr & actions, Aggr
     }
 }
 
-void makeWindowDescriptionFromAST(const Context & context,
+void ExpressionAnalyzer::makeWindowDescriptionFromAST(const Context & context_,
```
Comment (novikd) [inline src/Interpreters/ExpressionAnalyzer.cpp:600]: You can remove the first parameter because it's a member function now.

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 10]
```diff
@@ -830,7 +830,7 @@ static FillColumnDescription getWithFillDescription(const ASTOrderByElement & or
     return descr;
 }
 
-static SortDescription getSortDescription(const ASTSelectQuery & query, ContextPtr context)
+SortDescription InterpreterSelectQuery::getSortDescription(const ASTSelectQuery & query, ContextPtr context_)
```
Comment (novikd) [inline src/Interpreters/InterpreterSelectQuery.cpp:833]: Here you can remove the second parameter.

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 11]
```diff
@@ -974,12 +974,12 @@ static std::pair<UInt64, UInt64> getLimitLengthAndOffset(const ASTSelectQuery &
 }
 
 
-static UInt64 getLimitForSorting(const ASTSelectQuery & query, ContextPtr context)
+UInt64 InterpreterSelectQuery::getLimitForSorting(const ASTSelectQuery & query, ContextPtr context_)
```
Comment (novikd) [inline src/Interpreters/InterpreterSelectQuery.cpp:977]: The same here

File: src/Interpreters/WindowDescription.h [hunk 12]
```diff
@@ -7,6 +7,7 @@
 #include <DataTypes/IDataType.h>
 #include <Core/Names.h>
 #include <Core/Types.h>
+#include <Processors/QueryPlan/FilterStep.h>
```
Comment (novikd) [inline src/Interpreters/WindowDescription.h:10]: Accidental change?

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp [hunk 13]
```diff
@@ -0,0 +1,125 @@
...
+    auto * sorting = typeid_cast<SortingStep *>(sorting_node->step.get());
+    if (!sorting)
+        return 0;
+    if (sorting_node->children.size() != 1)
+        return 0;
+
+    auto * possible_read_from_merge_tree_node = sorting_node->children.front();
+
+    auto * expression = typeid_cast<ExpressionStep *>(possible_read_from_merge_tree_node->step.get());
+    if (expression)
```
Comment (novikd) [inline src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp:53]:
```suggestion
    if (auto * expression = typeid_cast<ExpressionStep *>(possible_read_from_merge_tree_node->step.get()))
```

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp [hunk 14]
```diff
@@ -0,0 +1,125 @@
...
+    {
+        if (possible_read_from_merge_tree_node->children.size() != 1)
+            return 0;
+
+        possible_read_from_merge_tree_node = possible_read_from_merge_tree_node->children.front();
+    }
+
+    auto * quota_and_limits = typeid_cast<SettingQuotaAndLimitsStep *>(possible_read_from_merge_tree_node->step.get());
+    if (quota_and_limits)
```
Comment (novikd) [inline src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp:62]:
```suggestion
    if (auto * quota_and_limits = typeid_cast<SettingQuotaAndLimitsStep *>(possible_read_from_merge_tree_node->step.get()))
```

**Review by novikd — COMMENTED** [review]
Looks good. Please, add a test with `over (partition by ... order by ...)`.

File: src/Interpreters/ExpressionAnalyzer.cpp (hunk 9 above)
Comment (excitoon) [reply src/Interpreters/ExpressionAnalyzer.cpp:600]: It is still static member and we can't easily make that because basically lots of code for that class is made through static functions in corresponding cpp file. And same in two other cases in `InterpreterSelectQuery.cpp`.

File: src/Interpreters/WindowDescription.h (hunk 12 above)
Comment (excitoon) [reply src/Interpreters/WindowDescription.h:10]: +

File: src/Interpreters/ExpressionAnalyzer.cpp (hunk 8 above)
Comment (excitoon) [reply src/Interpreters/ExpressionAnalyzer.cpp:693]: +

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp (hunk 13 above)
Comment (excitoon) [reply src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp]: +

File: src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp (hunk 14 above)
Comment (excitoon) [reply src/Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp]: +

**Comment by filimonov** [comment]
https://gist.github.com/filimonov/260c288b3233f675f260120c47f0f753

**Comment by filimonov** [comment]
High memory usage for UNBOUNDED PRECEDING + UNBOUNDED FOLLOWING looks expected: we can not start steaming out any row before the last row in the window will be read. 

So we need to store all the seen rows + all the whole window. 

But in practice, we sometimes see almost 3.5x memory usage.

```sql
select number, lagInFrame(number) OVER (ORDER BY number ASC ROWS
                 BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS prev from test format Null;

-- Peak memory usage (for query): 11.81 GiB. -- while the data size is 3.2 Gb
```

That additional memory increase looks related to the block sizes (and their size prediction?)

```sql
set max_block_size = 256;
-- Peak memory usage (for query): 11.95 GiB.

SET max_block_size = 8192;
-- Peak memory usage (for query): 11.93 GiB.

set max_block_size = 65505; -- default
-- Peak memory usage (for query): 11.81 GiB.

SET max_block_size = 80000
-- Peak memory usage (for query): 9.58 GiB.

SET max_block_size = 90000
-- Peak memory usage (for query): 8.70 GiB.

SET max_block_size = 100000;
-- Peak memory usage (for query): 7.49 GiB.

SET max_block_size = 130000
-- Peak memory usage (for query): 6.50 GiB.

SET max_block_size = 524288
-- Peak memory usage (for query): 6.51 GiB.
```

**Review by novikd — APPROVED** [review]
LGTM, but needs to fix flaky check:
> Stateless tests flaky check (address, actions) — Timeout, fail: 77, passed: 0

File: tests/queries/0_stateless/01655_plan_optimizations_optimize_read_in_window_order_long.sh [hunk 15]
```diff
@@ -0,0 +1,47 @@
+#!/usr/bin/env bash
+
```
Comment (novikd) [inline tests/queries/0_stateless/01655_plan_optimizations_optimize_read_in_window_order_long.sh:2]:
```suggestion
# Tags: long
```

**Comment by excitoon** [comment]
```
+ for table in query_log zookeeper_log trace_log transactions_info_log
+ clickhouse-local --path /var/lib/clickhouse/ -q 'select * from system.query_log format TSVWithNamesAndTypes'
+ pigz
Code: 76. DB::Exception: Cannot lock file /var/lib/clickhouse/status. Another server instance in same directory is already running. (CANNOT_OPEN_FILE)
```

**Comment by novikd** [comment]
@Mergifyio update

**Comment by excitoon** [comment]
Rebased.

**Comment by excitoon** [comment]
@Mergifyio rebase

**Comment by excitoon** [comment]
@Mergifyio rebase

**Comment by excitoon** [comment]
@Mergifyio rebase

**Comment by excitoon** [comment]
I rebased but failed to fix @Mergifyio

**Review by novikd — APPROVED** [review]
