### PR TITLE
Fix `has()` function with `Nullable` column

### LINKED ISSUE #60214: Function 'has' works incorrectly with 'Nullable' columns
**Describe what's wrong**

Function `has` works incorrectly when the second argument is a `nullable` column.

It may return 1 for expression `has([0, 1], a)`, when `a` is `Null`.

It looks like that for nullable columns the function uses an `underlying` column (`assumeNotNullable`), and the null bitmap is ignored.

(the result for second query is wrong)
https://fiddle.clickhouse.com/d508fc65-6e05-495f-a923-a142f6b906b7

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

* Which ClickHouse server version to use
23.8/24.1/latest

* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE test (a Nullable(Int64)) ENGINE=Memory;
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
```sql
INSERT INTO test VALUES (1), (Null);
```
* Queries to run that lead to an unexpected result
```sql
SELECT a, has([0, 1], a) as b FROM test;

-----
1	1
\N	1
-----
```

**Expected behavior**
`has` should return 0 if the value is `Null` and `Null` is missing in the array
```
-----
1	1
\N	0
-----
```

> A clear and concise description of what you expected to happen.

### PR DESCRIPTION
**Pull request by mkmkme**
Previous implementation didn't check for `null_map` when the given argument was not `Null`. This commit adds the missing check.

Fixes #60214

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `has()` function with `Nullable` column (fixes #60214)

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 94f15dd5e058fc9f68bf3644c895908bba849db6 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/61249/94f15dd5e058fc9f68bf3644c895908bba849db6/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: tests/queries/0_stateless/00662_has_nullable.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+DROP TABLE IF EXISTS 00662_has_nullable;
+CREATE TABLE 00662_has_nullable(a Nullable(UInt64)) ENGINE = Memory;
+
+INSERT INTO 00662_has_nullable VALUES (1), (Null);
+SELECT a, has([0, 1], a) FROM 00662_has_nullable;
+
+DROP TABLE 00662_has_nullable;
```
Comment (yariks5s) [inline tests/queries/0_stateless/00662_has_nullable.sql:7]: Would be also good to add more tests cases (more values in nullable table, put nullable arguments as left/both arguments in `has()` function.

Comment (mkmkme) [reply tests/queries/0_stateless/00662_has_nullable.sql:7]: Will do

Comment (mkmkme) [reply tests/queries/0_stateless/00662_has_nullable.sql:7]: @yariks5s also JFYI the cases you described actually exist in https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/00662_array_has_nullable.sql

I was thinking about expanding it instead of writing the new file, but that test didn't have any table creation, hence I decided to create a new one.

**Review by yariks5s — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @mkmkme @yariks5s — while reviewing this PR I found the following:

- **Coverage gap:** `indexOf` and `countEqual` with constant non-NULL array and `Nullable` value column carrying NULLs is untested — https://github.com/ClickHouse/ClickHouse/pull/103922

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
