### PR TITLE
Fix pointer handling for `currentDatabase` function in `CONSTRAINT` and `ON CLUSTER` queries

### LINKED ISSUE #78100: Create table with constraint crash with cluster table
### Describe the bug

Easy to reproduce.

### How to reproduce

With `test_shard_localhost` remote setup from testing run:

```sql
CREATE TABLE t0 ON CLUSTER 'test_shard_localhost' (c0 Int, CONSTRAINT cc CHECK currentDatabase()) ENGINE = MergeTree() ORDER BY tuple();
```

### Error message and/or stacktrace

Stack trace with gdb:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=0) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c4519e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c28902 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555574af5cc6 in abort_message (format=warning: (Error: pc 0x55555877fa6b in address map, but not in symtab.)
0x55555877fa6b "Pure virtual function called!") at contrib/llvm-project/libcxxabi/src/abort_message.cpp:78
#6  0x0000555574b1588f in __cxa_pure_virtual () at contrib/llvm-project/libcxxabi/src/cxa_virtual.cpp:16
#7  0x000055556ce70c38 in DB::ASTConstraintDeclaration::clone (this=0x7ffeb2da1a18) at src/Parsers/ASTConstraintDeclaration.cpp:17
#8  0x000055556ce77048 in DB::ASTColumns::formatImpl (this=0x7ffd1befa218, ostr=..., s=..., state=..., frame=...) at src/Parsers/ASTCreateQuery.cpp:213
#9  0x000055556ce7aa20 in DB::IAST::format (ostr=..., settings=..., state=..., frame=..., this=<optimized out>) at src/Parsers/IAST.h:264
#10 DB::ASTCreateQuery::formatQueryImpl (this=0x7ffeb2de1c98, ostr=..., settings=..., state=..., frame=...) at src/Parsers/ASTCreateQuery.cpp:480
#11 0x000055556ceb47d0 in DB::ASTQueryWithOutput::formatImpl (this=0x7ffeb2de1c98, ostr=..., s=..., state=..., frame=...) at src/Parsers/ASTQueryWithOutput.cpp:40
#12 0x0000555560e04b6e in DB::IAST::format (this=0x74919, ostr=..., settings=...) at src/Parsers/IAST.h:259
#13 0x000055556cf1b07a in DB::IAST::formatWithPossiblyHidingSensitiveData (this=0x7ffeb2de1c98, max_length=max_length@entry=0, one_line=true, show_secrets=true, print_pretty_type_names=false, 
    identifier_quoting_rule=DB::IdentifierQuotingRule::WhenNecessary, identifier_quoting_style=DB::IdentifierQuotingStyle::Backticks) at src/Parsers/IAST.cpp:187
#14 0x000055556cf1b19d in DB::IAST::formatWithSecretsOneLine (this=0x74923) at src/Parsers/IAST.cpp:215
#15 0x000055556a0a3cda in DB::executeDDLQueryOnCluster (query_ptr_=..., context=..., params=...) at src/Interpreters/executeDDLQueryOnCluster.cpp:187
#16 0x0000555569d2a277 in DB::InterpreterCreateQuery::executeQueryOnCluster (this=this@entry=0x7ffeb2d73fa0, create=...) at src/Interpreters/InterpreterCreateQuery.cpp:2310
#17 0x0000555569d27f7d in DB::InterpreterCreateQuery::createTable (this=0x7ffeb2d73fa0, create=...) at src/Interpreters/InterpreterCreateQuery.cpp:1730
#18 0x0000555569d34341 in DB::InterpreterCreateQuery::execute (this=0x7ffeb2d73fa0) at src/Interpreters/InterpreterCreateQuery.cpp:2340
#19 0x000055556a0b6b48 in DB::executeQueryImpl (begin=<optimized out>, end=<optimized out>, context=..., flags=..., stage=DB::QueryProcessingStage::Complete, istr=0x0, out_ast=...) at src/Interpreters/executeQuery.cpp:1458
#20 0x000055556a0b19eb in DB::executeQuery (query=..., context=..., flags=..., flags@entry=..., stage=DB::QueryProcessingStage::FetchColumns) at src/Interpreters/executeQuery.cpp:1625
#21 0x000055556bd2ce41 in DB::TCPHandler::runImpl (this=0x7ffeb2d9d000) at src/Server/TCPHandler.cpp:665
#22 0x000055556bd44fb9 in DB::TCPHandler::run (this=0x74919) at src/Server/TCPHandler.cpp:2630
#23 0x0000555570137367 in Poco::Net::TCPServerConnection::start (this=0x74919) at base/poco/Net/src/TCPServerConnection.cpp:40
#24 0x000055557013783e in Poco::Net::TCPServerDispatcher::run (this=0x7ffd3fe7b500) at base/poco/Net/src/TCPServerDispatcher.cpp:115
#25 0x00005555700e1432 in Poco::PooledThread::run (this=0x7ffff6415580) at base/poco/Foundation/src/ThreadPool.cpp:205
#26 0x00005555700df06f in Poco::ThreadImpl::runnableEntry (pThread=<optimized out>) at base/poco/Foundation/src/Thread_POSIX.cpp:335
#27 0x00007ffff7ca1e2e in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#28 0x00007ffff7d33a4c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash for a very specific situation when the `currentDatabase` function was used in `CONSTRAINT` sections for `ON CLUSTER` queries
Closes https://github.com/ClickHouse/ClickHouse/issues/78100

### CODE REVIEW

File: src/Interpreters/AddDefaultDatabaseVisitor.h [hunk 1]
```diff
@@ -308,27 +313,31 @@ class AddDefaultDatabaseVisitor
         }
     }
 
-    void visitDDL(ASTFunction & function, ASTPtr & node) const
+    void visitDDL(ASTPtr & parent, ASTFunction & function, ASTPtr & node) const
     {
         if (function.name == "currentDatabase")
         {
+            void * old_pointer = node.get();
             node = std::make_shared<ASTLiteral>(database_name);
```
Comment (tuanpach) [inline src/Interpreters/AddDefaultDatabaseVisitor.h:321]: After assigning `node` to a new `ASTLiteral`, the old node might get destroyed, and `old_pointer` might point to an invalid object.
In this case, we call `parent->updatePointerToChild(old_pointer, new_pointer);` and it just checks the address. So it is safe.
However, I think we should hold the old node until we no longer use it (just in case we change the logic and access `old_pointer` in  `parent->updatePointerToChild`).

File: src/Interpreters/AddDefaultDatabaseVisitor.h [hunk 2]
```diff
@@ -53,13 +53,18 @@ class AddDefaultDatabaseVisitor
     }
 
     void visitDDL(ASTPtr & ast) const
+    {
+        visitDDLWithParent(nullptr, ast);
+    }
+
+    void visitDDLWithParent(ASTPtr parent, ASTPtr & ast) const
```
Comment (tuanpach) [inline src/Interpreters/AddDefaultDatabaseVisitor.h:60]: I think we can add a `parent` field to `ASTPtr`. However, it might introduce lots of changes.

Comment (pufit) [reply src/Interpreters/AddDefaultDatabaseVisitor.h:61]: This is a great idea, but I think it should be implemented in a separate PR.
Added a TODO

File: src/Interpreters/AddDefaultDatabaseVisitor.h (hunk 1 above)
Comment (pufit) [reply src/Interpreters/AddDefaultDatabaseVisitor.h:325]: Done + added a comment about this behavior, should have been there from the start.

File: src/Interpreters/AddDefaultDatabaseVisitor.h [hunk 3]
```diff
@@ -308,27 +314,36 @@ class AddDefaultDatabaseVisitor
...
+            /// However, just for safety, let's store the old node for a little longer.
+            ASTPtr old_node = node;
             node = std::make_shared<ASTLiteral>(database_name);
-            return;
+            void * new_pointer = node.get();
+
+            if (parent)
+            {
+                parent->updatePointerToChild(old_pointer, new_pointer);
+            }
```
Comment (tuanpach) [inline src/Interpreters/AddDefaultDatabaseVisitor.h:331]:
```suggestion

            if (parent)
            {
                parent->updatePointerToChild(old_node.get(), node.get());
            }
```

File: src/Interpreters/AddDefaultDatabaseVisitor.h [hunk 4]
```diff
@@ -308,27 +314,36 @@ class AddDefaultDatabaseVisitor
         }
     }
 
-    void visitDDL(ASTFunction & function, ASTPtr & node) const
+    void visitDDL(ASTPtr & parent, ASTFunction & function, ASTPtr & node) const
     {
         if (function.name == "currentDatabase")
         {
+            void * old_pointer = node.get();
```
Comment (tuanpach) [inline src/Interpreters/AddDefaultDatabaseVisitor.h:321]:
```suggestion
```

File: src/Interpreters/AddDefaultDatabaseVisitor.h (hunk 3 above)
Comment (tuanpach) [reply src/Interpreters/AddDefaultDatabaseVisitor.h:331]: With this way, we don't need to declare `old_pointer` and `new_pointer`.
It is a minor thing. Feel free to skip this suggestion.

**Review by tuanpach — APPROVED** [review]

**Review by tuanpach — APPROVED** [review]
