### PR TITLE
Fix flaky test 03364_estimate_compression_ratio

### LINKED ISSUE #85999: Test 03364_estimate_compression_ratio is really flaky
https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMzM2NF9lc3RpbWF0ZV9jb21wcmVzc2lvbl9yYXRpbycgQVMgbmFtZV9zdWJzdHIsCiAgICAzMCBBUyBpbnRlcnZhbF9kYXlzClNFTEVDVAogICAgY2hlY2tfc3RhcnRfdGltZSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCkdST1VQIEJZIGQKT1JERVIgQlkgZCBERVNDCg==

Example of the failure:
```
2025-08-21 08:56:19 Reason: return code:  1
2025-08-21 08:56:19 /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/test_efsavmgl/03364_estimate_compression_ratio.sh.debuglog:
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:7] column_names=("number_col" "str_col" "array_col" "nullable_col" "sparse_col" "tuple_col")
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:8] table_name=table_for_estimate_compression_ratio
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:9] tolerance=0.40
2025-08-21 08:56:19 ++ [2025-08-21 08:56:02] [:10] awk 'BEGIN {printf "%.2f", 0.40 * 100}'
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:10] formatted_tolerance=40.00%
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:13] codecs=("ZSTD(1)" "LZ4")
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:14] block_sizes=(65536 1048576)
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:15] num_rows_list=(1_000 50_000)
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:125] for num_rows in "${num_rows_list[@]}"
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:126] create_table 1_000
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:18] local num_rows=1_000
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:20] query='DROP TABLE IF EXISTS table_for_estimate_compression_ratio'
2025-08-21 08:56:19 + [2025-08-21 08:56:02] [:21] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_efsavmgl --log_comment 03364_estimate_compression_ratio.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 47533467 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 6985604 --max_read_buffer_size 953736 --prefer_localhost_replica 0 --max_block_size 28386 --max_joined_block_size_rows 63750 --max_threads 1 --optimize_append_index 1 --use_hedged_requests 0 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 78 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 15515312 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1191114021 --min_bytes_to_use_mmap_io 2012511407 --local_filesystem_read_method mmap --remote_filesystem_read_method read --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 64Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 0 --compile_aggregate_expressions 1 --compile_sort_description 1 --merge_tree_coarse_index_granularity 20 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 514700714 --min_compress_block_size 1645603 --max_compress_block_size 131964 --merge_tree_compact_parts_min_granules_to_multibuffer_read 86 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 1716425 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 0 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone Europe/Amsterdam --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.58 --prefer_external_sort_block_bytes 1 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 1 --max_parsing_threads 0 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 0 --query_plan_join_swap_table auto --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_async_executor_for_materialized_views 0 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 0 --max_bytes_before_external_sort 9408884913 --max_bytes_before_external_group_by 10737418240 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0 --use_skip_indexes_if_final_exact_mode 0 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.655963774504059 --prefer_fetch_merged_part_size_threshold 8276924024 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 2709338110 --index_granularity_bytes 246663 --merge_max_block_size 20445 --index_granularity 63052 --min_bytes_for_wide_part 0 --marks_compress_block_size 47420 --primary_key_compress_block_size 98119 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 488082212 --compact_parts_max_bytes_to_buffer 58453998 --compact_parts_max_granules_to_buffer 1 --compact_parts_merge_max_bytes_to_prefetch_part 24080962 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 0 --old_parts_lifetime 69 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03364_estimate_compression_ratio.stderr-fatal -q 'DROP TABLE IF EXISTS table_for_estimate_compression_ratio'
2025-08-21 08:56:19 + [2025-08-21 08:56:03] [:31] query='CREATE TABLE table_for_estimate_compression_ratio (
2025-08-21 08:56:19         number_col UInt64,
2025-08-21 08:56:19         str_col String,
2025-08-21 08:56:19         array_col Array(String),
2025-08-21 08:56:19         nullable_col Nullable(Int64),
2025-08-21 08:56:19         sparse_col Int64,
2025-08-21 08:56:19         tuple_col Tuple(Int64, Tuple(Int64, Int64)),
2025-08-21 08:56:19     ) ENGINE = MergeTree ORDER BY number_col
2025-08-21 08:56:19     SETTINGS min_bytes_for_wide_part = 0'
2025-08-21 08:56:19 + [2025-08-21 08:56:03] [:33] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_efsavmgl --log_comment 03364_estimate_compression_ratio.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 47533467 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 6985604 --max_read_buffer_size 953736 --prefer_localhost_replica 0 --max_block_size 28386 --max_joined_block_size_rows 63750 --max_threads 1 --optimize_append_index 1 --use_hedged_requests 0 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 78 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 15515312 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1191114021 --min_bytes_to_use_mmap_io 2012511407 --local_filesystem_read_method mmap --remote_filesystem_read_method read --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 64Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 0 --compile_aggregate_expressions 1 --compile_sort_description 1 --merge_tree_coarse_index_granularity 20 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 514700714 --min_compress_block_size 1645603 --max_compress_block_size 131964 --merge_tree_compact_parts_min_granules_to_multibuffer_read 86 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 1716425 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 0 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone Europe/Amsterdam --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.58 --prefer_external_sort_block_bytes 1 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 1 --max_parsing_threads 0 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 0 --query_plan_join_swap_table auto --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_async_executor_for_materialized_views 0 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 0 --max_bytes_before_external_sort 9408884913 --max_bytes_before_external_group_by 10737418240 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0 --use_skip_indexes_if_final_exact_mode 0 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.655963774504059 --prefer_fetch_merged_part_size_threshold 8276924024 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 2709338110 --index_granularity_bytes 246663 --merge_max_block_size 20445 --index_granularity 63052 --min_bytes_for_wide_part 0 --marks_compress_block_size 47420 --primary_key_compress_block_size 98119 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 488082212 --compact_parts_max_bytes_to_buffer 58453998 --compact_parts_max_granules_to_buffer 1 --compact_parts_merge_max_bytes_to_prefetch_part 24080962 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 0 --old_parts_lifetime 69 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03364_estimate_compression_ratio.stderr-fatal -q 'CREATE TABLE table_for_estimate_compression_ratio (
2025-08-21 08:56:19         number_col UInt64,
2025-08-21 08:56:19         str_col String,
2025-08-21 08:56:19         array_col Array(String),
2025-08-21 08:56:19         nullable_col Nullable(Int64),
2025-08-21 08:56:19         sparse_col Int64,
2025-08-21 08:56:19         tuple_col Tuple(Int64, Tuple(Int64, Int64)),
2025-08-21 08:56:19     ) ENGINE = MergeTree ORDER BY number_col
2025-08-21 08:56:19     SETTINGS min_bytes_for_wide_part = 0'
2025-08-21 08:56:19 + [2025-08-21 08:56:04] [:43] query='INSERT INTO table_for_estimate_compression_ratio
2025-08-21 08:56:19     SELECT
2025-08-21 08:56:19         number as number_col,
2025-08-21 08:56:19         toString(rand64()) as str_col,
2025-08-21 08:56:19         [toString(rand64()), toString(rand64())] as array_col,
2025-08-21 08:56:19         if(number % 20 = 0, number, NULL) as nullable_col,
2025-08-21 08:56:19         if(number % 3 = 0, number, 0) as sparse_col,
2025-08-21 08:56:19         (number, (0, 0)) as tuple_col
2025-08-21 08:56:19     FROM system.numbers LIMIT 1_000'
2025-08-21 08:56:19 + [2025-08-21 08:56:04] [:45] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_efsavmgl --log_comment 03364_estimate_compression_ratio.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 47533467 --distributed_aggregation_memory_efficient 1 --fsync_metadata 1 --output_format_parallel_formatting 1 --input_format_parallel_parsing 0 --min_chunk_bytes_for_parallel_parsing 6985604 --max_read_buffer_size 953736 --prefer_localhost_replica 0 --max_block_size 28386 --max_joined_block_size_rows 63750 --max_threads 1 --optimize_append_index 1 --use_hedged_requests 0 --optimize_if_chain_to_multiif 1 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 0 --optimize_substitute_columns 1 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 78 --optimize_aggregation_in_order 1 --aggregation_in_order_max_block_bytes 15515312 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1191114021 --min_bytes_to_use_mmap_io 2012511407 --local_filesystem_read_method mmap --remote_filesystem_read_method read --local_filesystem_read_prefetch 1 --filesystem_cache_segments_batch_size 3 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 0 --throw_on_error_from_cache_on_write_operations 1 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 64Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 8Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 100Mi --compile_expressions 0 --compile_aggregate_expressions 1 --compile_sort_description 1 --merge_tree_coarse_index_granularity 20 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 514700714 --min_compress_block_size 1645603 --max_compress_block_size 131964 --merge_tree_compact_parts_min_granules_to_multibuffer_read 86 --optimize_sorting_by_input_stream_properties 1 --http_response_buffer_size 1716425 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 0 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 0 --session_timezone Europe/Amsterdam --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction False --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.58 --prefer_external_sort_block_bytes 1 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 1 --max_parsing_threads 0 --optimize_functions_to_subcolumns 1 --parallel_replicas_local_plan 0 --query_plan_join_swap_table auto --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_async_executor_for_materialized_views 0 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 0 --max_bytes_before_external_sort 9408884913 --max_bytes_before_external_group_by 10737418240 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0 --use_skip_indexes_if_final_exact_mode 0 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.655963774504059 --prefer_fetch_merged_part_size_threshold 8276924024 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 2709338110 --index_granularity_bytes 246663 --merge_max_block_size 20445 --index_granularity 63052 --min_bytes_for_wide_part 0 --marks_compress_block_size 47420 --primary_key_compress_block_size 98119 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 488082212 --compact_parts_max_bytes_to_buffer 58453998 --compact_parts_max_granules_to_buffer 1 --compact_parts_merge_max_bytes_to_prefetch_part 24080962 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 0 --old_parts_lifetime 69 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Closes https://github.com/ClickHouse/ClickHouse/issues/85999

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Still flaky...

File: tests/queries/0_stateless/03364_estimate_compression_ratio.sh [hunk 1]
```diff
@@ -28,7 +27,7 @@ create_table() {
         sparse_col Int64,
         tuple_col Tuple(Int64, Tuple(Int64, Int64)),
     ) ENGINE = MergeTree ORDER BY number_col
-    SETTINGS min_bytes_for_wide_part = 0"
+    SETTINGS min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization=1, index_granularity=8128"
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/03364_estimate_compression_ratio.sh:30]: Why not 8192...

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
`03595_alter_drop_column_comment_if_exists`: https://github.com/ClickHouse/ClickHouse/pull/86001

File: tests/queries/0_stateless/03364_estimate_compression_ratio.sh (hunk 1 above)
Comment (Avogar) [reply tests/queries/0_stateless/03364_estimate_compression_ratio.sh:30]: Because my brain said that 8128 is the power of 2 and the default value 🤪
