### PR TITLE
Query cache: Fix per-user quota

### LINKED ISSUE #58149: is query_cache_max_entries working?
version 23.11.3.23  

This one is a bit odd. I swear I saw it working ONCE, but never after this again. Restarting clickhouse-server doesn't help. I hope this is reproducible this way:

```sql
system drop query cache;
set query_cache_max_entries = 0; -- default setting
select 1 settings use_query_cache=1;
select 2 settings use_query_cache=1;
set query_cache_max_entries = 3;
select 3 settings use_query_cache=1;
select 4 settings use_query_cache=1;
select * from system.query_cache;
```

The cache should now show 3 entries. (I believe this was also the case for me).
Now repeat the same procedure (dropping query cache also first). And the cache will remain empty. After this only `set query_cache_max_entries = 0;` will store new entries in the cache.

Is anyone seeing this behavior as well?

### PR DESCRIPTION
**Pull request by rschu1ze**
Fixes #58149

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The query cache now behaves properly when per-user quotas are defined and `SYSTEM DROP QUERY CACHE` ran.

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 164d466695e1d5fb29f043c19f8beb5abf1882c9 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58731/164d466695e1d5fb29f043c19f8beb5abf1882c9/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58731/164d466695e1d5fb29f043c19f8beb5abf1882c9/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: tests/queries/0_stateless/02956_format_constexpr.sql [hunk 1]
```diff
@@ -1 +0,0 @@
-SELECT isConstant(format('{}, world', 'Hello'));
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/02956_format_constexpr.sql:1]: ?

File: tests/queries/0_stateless/00949_format.sql [hunk 2]
```diff
@@ -226,3 +226,5 @@ select format('{}{}{}', materialize(toFixedString('a', 1)), toFixedString('b', 1
 select format('{}{}{}', materialize(toFixedString('a', 1)), toFixedString('b', 1), materialize(toFixedString('c', 1))) == 'abc' from system.numbers limit 5;
 select format('{}{}{}', materialize(toFixedString('a', 1)), materialize(toFixedString('b', 1)), toFixedString('c', 1)) == 'abc' from system.numbers limit 5;
 select format('{}{}{}', materialize(toFixedString('a', 1)), materialize(toFixedString('b', 1)), materialize(toFixedString('c', 1))) == 'abc' from system.numbers limit 5;
+
+SELECT isConstant(format('{}, world', 'Hello'));
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/00949_format.sql:230]: It's much better to add new test cases to new tests instead of modifying the existing ones.

The advantages are:
- you get a more granular report when only a single case has failed;
- the history of test runs is consistent;
- it is easier to attribute tests to particular changes in the code.

Comment (rschu1ze) [reply tests/queries/0_stateless/00949_format.sql:230]: Okay, these reasons are valid. Will do.

File: src/Common/TTLCachePolicy.h [hunk 3]
```diff
@@ -38,12 +38,12 @@ class PerUserTTLCachePolicyUserQuota : public ICachePolicyUserQuota
     bool approveWrite(const UUID & user_id, size_t entry_size_in_bytes) const override
     {
         auto it_actual = actual.find(user_id);
-        Resources actual_for_user{.size_in_bytes = 0, .num_items = 0}; /// assume zero actual resource consumption is user isn't found
+        Resources actual_for_user{.size_in_bytes = 0, .num_items = 0}; /// default if no user is found is no resource consumption
```
Comment (devcrafter) [inline src/Common/TTLCachePolicy.h:41]: The comment sounds odd, some commas are needed or maybe this way?
```suggestion
        Resources actual_for_user{.size_in_bytes = 0, .num_items = 0}; /// default, no user -> no resource consumption
```

File: src/Common/TTLCachePolicy.h [hunk 4]
```diff
@@ -38,12 +38,12 @@ class PerUserTTLCachePolicyUserQuota : public ICachePolicyUserQuota
...
         if (it_actual != actual.end())
             actual_for_user = it_actual->second;
 
         auto it_quota = quotas.find(user_id);
-        Resources quota_for_user{.size_in_bytes = std::numeric_limits<size_t>::max(), .num_items = std::numeric_limits<size_t>::max()}; /// assume no threshold if no quota is found
+        Resources quota_for_user{.size_in_bytes = std::numeric_limits<size_t>::max(), .num_items = std::numeric_limits<size_t>::max()}; /// default if no user is found is no threshold
```
Comment (devcrafter) [inline src/Common/TTLCachePolicy.h:46]: the same regarding comment

**Review by devcrafter — APPROVED** [review]

File: src/Common/TTLCachePolicy.h (hunk 3 above)
Comment (rschu1ze) [reply src/Common/TTLCachePolicy.h:41]: Rewrote the comment, should be more readable now. Thanks.

File: src/Common/TTLCachePolicy.h (hunk 4 above)
Comment (rschu1ze) [reply src/Common/TTLCachePolicy.h:46]: Same

**Comment by rschu1ze** [comment]
@devcrafter Approve? Thanks!

**Review by devcrafter — APPROVED** [review]
