### PR TITLE
Fix `h3ToGeo()` to return (lat, lon) instead of (lon, lat)

### LINKED ISSUE #74279: `h3ToGeo` returns reversed `(lat, lon)`
Issue [h3ToGeoBoundary returns result which is different from documentation](https://github.com/ClickHouse/clickhouse-docs/issues/3031) points out that the return of `h3ToGeoBoundary` function is inconsistent with the behaviour of the function. This is corrected in #74278.

However looks that in the code `h3ToGeo` returns `(longitude, latitude)` but `h3ToGeoBoundary` returns `(latitude, longitude)`. The functions should behave the same as the standard order for geographic coordinates is `latitude, longitude`, unless there is a specific reason to have them switched for this function.

Compare
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/h3toGeo.cpp#L94-L97
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/h3ToGeoBoundary.cpp#L95-L97

-  The standard order for geographic coordinates is `latitude, longitude` so we need to switch parameter ordering for `h3ToGeo`.
 -  A compatibility setting (similar to the many compatability settings for [formatDateTime](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#formatdatetime)) should also be added so that existing usage is not broken unintentionally.

### PR DESCRIPTION
**Pull request by mgill25**
Closes https://github.com/ClickHouse/ClickHouse/issues/74279

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Function `h3ToGeo()` now returns the results in the order `(lat, lon)` (which is the standard order for geometric functions).  Users who wish to retain the legacy result order `(lon, lat)` can set setting `h3togeo_lon_lat_result_order = true`.

### CODE REVIEW

File: src/Core/Settings.cpp [hunk 1]
```diff
@@ -3184,7 +3184,9 @@ Formatters '%c', '%l' and '%k' in function 'formatDateTime' print months and hou
     DECLARE(Bool, least_greatest_legacy_null_behavior, false, R"(
 If enabled, functions 'least' and 'greatest' return NULL if one of their arguments is NULL.
 )", 0) \
-    \
+    DECLARE(Bool, h3togeo_standard_order, true, R"(
+Enforces the h3ToGeo() function to return (lat, lon) instead of (lon, lat)
```
Comment (rschu1ze) [inline src/Core/Settings.cpp:3188]: A tad more concise: "Function 'h3ToGeo' returns (lat, lon) if true, otherwise (lon, lat)."

File: src/Core/SettingsChangesHistory.cpp [hunk 2]
```diff
@@ -98,6 +98,7 @@ const VersionToSettingsChangesMap & getSettingsChangesHistory()
             {"validate_enum_literals_in_operators", false, false, "A new setting"},
             {"allow_experimental_kusto_dialect", true, false, "A new setting"},
             {"allow_experimental_prql_dialect", true, false, "A new setting"},
+            {"h3togeo_standard_order", false, true, "New setting, fixes h3ToGeo() function to return (lat, lon)"},
```
Comment (rschu1ze) [inline src/Core/SettingsChangesHistory.cpp:101]: "standard_order" sounds slightly weird. Maybe "result_order"?

EDIT 1: Oh, I see "result_order" would not work either because the parameter is boolean. Can we rename it to "h3togeo_lat_lon_result_order"

EDIT 2: We should invert the semantics. The database ideally has as _few_ settings enabled by default as possible. Hence, the new default value for the setting should be `false`. If users like to go back to the previous behavior, they should need to enable a setting (not the other way round: disable a setting). Can we name the setting `h3togeo_lon_lat_result_order` (default: false)?

Comment (rschu1ze) [inline src/Core/SettingsChangesHistory.cpp:101]: Just saying `New setting`, like for the other entries, is fine. Further explanation (like you did) only duplicates what is already mentioned in Core/Settings.cpp.

File: src/Functions/h3toGeo.cpp [hunk 3]
```diff
@@ -12,12 +13,18 @@
 #include <Functions/FunctionFactory.h>
 #include <Functions/IFunction.h>
 #include <Common/typeid_cast.h>
-
+#include <Interpreters/Context.h>
```
Comment (rschu1ze) [inline src/Functions/h3toGeo.cpp:16]: Formatting: \+ newline after l. 17 (because `<h3api.h>` includes external code, making it different from the other includes)

File: src/Core/SettingsChangesHistory.cpp [hunk 4]
```diff
@@ -98,6 +98,7 @@ const VersionToSettingsChangesMap & getSettingsChangesHistory()
             {"validate_enum_literals_in_operators", false, false, "A new setting"},
             {"allow_experimental_kusto_dialect", true, false, "A new setting"},
             {"allow_experimental_prql_dialect", true, false, "A new setting"},
+            {"h3togeo_lon_lat_result_order", false, false, "A new setting"},
```
Comment (rschu1ze) [inline src/Core/SettingsChangesHistory.cpp:101]: Let's change `false, false` to `true, false`. These bools are used by the compatibility mechanism in ClickHouse. The first value is the previous behavior, the second one is the new one.

File: src/Core/Settings.cpp [hunk 5]
```diff
@@ -3184,7 +3184,9 @@ Formatters '%c', '%l' and '%k' in function 'formatDateTime' print months and hou
     DECLARE(Bool, least_greatest_legacy_null_behavior, false, R"(
 If enabled, functions 'least' and 'greatest' return NULL if one of their arguments is NULL.
 )", 0) \
-    \
+    DECLARE(Bool, h3togeo_lon_lat_result_order, true, R"(
```
Comment (rschu1ze) [inline src/Core/Settings.cpp:3187]: `true` --> `false`

File: src/Core/Settings.cpp [hunk 6]
```diff
@@ -3184,7 +3184,9 @@ Formatters '%c', '%l' and '%k' in function 'formatDateTime' print months and hou
...
+Function 'h3ToGeo' returns (lat, lon) if true, otherwise (lon, lat)
```
Comment (rschu1ze) [inline src/Core/Settings.cpp:3188]: We'll need to invert here too:

```
Function 'h3ToGeo' returns (lon, lat) if true, otherwise (lat, lon).
```

File: src/Functions/h3toGeo.cpp [hunk 7]
```diff
@@ -52,9 +65,18 @@ class FunctionH3ToGeo : public IFunction
                 "Illegal type {} of argument {} of function {}. Must be UInt64",
                 arg->getName(), 1, getName());
 
-        return std::make_shared<DataTypeTuple>(
-            DataTypes{std::make_shared<DataTypeFloat64>(), std::make_shared<DataTypeFloat64>()},
-            Strings{"longitude", "latitude"});
+        if (h3togeo_lon_lat_result_order)
+        {
+            return std::make_shared<DataTypeTuple>(
```
Comment (rschu1ze) [inline src/Functions/h3toGeo.cpp:70]: I think we need to switch both branches, no?

File: src/Functions/h3toGeo.cpp [hunk 8]
```diff
@@ -92,8 +114,16 @@ class FunctionH3ToGeo : public IFunction
         }
 
         MutableColumns columns;
-        columns.emplace_back(std::move(longitude));
-        columns.emplace_back(std::move(latitude));
+        if (h3togeo_lon_lat_result_order)
+        {
+            columns.emplace_back(std::move(latitude));
```
Comment (rschu1ze) [inline src/Functions/h3toGeo.cpp:119]: Same here, let's switch both branches.

File: src/Core/SettingsChangesHistory.cpp (hunk 2 above)
Comment (mgill25) [reply src/Core/SettingsChangesHistory.cpp]: Fixed.

File: src/Functions/h3toGeo.cpp (hunk 7 above)
Comment (mgill25) [reply src/Functions/h3toGeo.cpp:70]: I think it's fine now? `h3togeo_lon_lat_result_order` means `longitude` comes first. That's the behaviour now.

File: src/Core/Settings.cpp (hunk 1 above)
Comment (mgill25) [reply src/Core/Settings.cpp]: Docs updated.

**Comment by bharatnc** [comment]
Just heads up - there's already another PR doing the same: https://github.com/ClickHouse/ClickHouse/pull/74468

**Comment by bharatnc** [comment]
I had a general question If we are already adding a flag to preserve the old behavior, are such changes considered backwards incompatible?

**Review by rschu1ze — APPROVED** [review]

**Comment by mgill25** [comment]
> I had a general question If we are already adding a flag to preserve the old behavior, are such changes considered backwards incompatible?

@bharatnc my take on this is that since the default behaviour has changed, it should be considered backwards incompatible. The setting is opt-in to take you back to legacy behaviour.

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 5a8c1038ffaa8d81ff5032bc7fd44e78f2599731 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/74719/5a8c1038ffaa8d81ff5032bc7fd44e78f2599731/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/74719/5a8c1038ffaa8d81ff5032bc7fd44e78f2599731/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by rschu1ze** [comment]
> I had a general question If we are already adding a flag to preserve the old behavior, are such changes considered backwards incompatible?

Technically, such changes are backward-incompatible. Specifically, the database behaves differently assuming that the user did not set the compatibility level to the previous verison.

**Comment by mgill25** [comment]
Re: the CI failures, I'm not sure if this is caused by the changes in the PR itself (the test I added passes locally). Probably unrelated?

**Comment by bharatnc** [comment]
> Re: the CI failures, I'm not sure if this is caused by the changes in the PR itself (the test I added passes locally). Probably unrelated?

Seems to be a fast test failure caused by `02944_variant_as_common_type` likely unrelated to the PR.

**Comment by bharatnc** [comment]
> Re: the CI failures, I'm not sure if this is caused by the changes in the PR itself (the test I added passes locally). Probably unrelated?

Yes, the fast test failure seem [related](https://s3.amazonaws.com/clickhouse-test-reports/74719/5a8c1038ffaa8d81ff5032bc7fd44e78f2599731/fast_test.html).

**Comment by mgill25** [comment]
Strange. On a fresh build on my VM, this test passes.  I will check on Monday~

**Comment by bharatnc** [comment]
> Strange. On a fresh build on my VM, this test passes. I will check on Monday~

We skip fast tests for h3 related functions because we don't built the binary with H3 enabled. But they run as stateless tests. From the error log:
```
2025-01-17 17:46:17 Reason: return code:  46
2025-01-17 17:46:17 [ip-172-31-82-129] 2025.01.17 17:46:17.628169 [ 259515 ] {16d95020-e7c7-4a28-801b-01b5e088e632} <Error> executeQuery: Code: 46. DB::Exception: Function with name `h3ToGeo` does not exist. In scope SELECT h3ToGeo(644325524701193974) SETTINGS h3togeo_lon_lat_result_order = true. (UNKNOWN_FUNCTION) (version 25.1.1.1) (from [::ffff:127.0.0.1]:50822) (comment: 03313_h3geo_order.sql) (in query: SELECT h3ToGeo(644325524701193974) SETTINGS h3togeo_lon_lat_result_order=true;), Stack trace (when copying this message, always include the lines below):
2025-01-17 17:46:17 
2025-01-17 17:46:17 0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:106: Poco::Exception::Exception(String const&, int) @ 0x000000000f7d764b
2025-01-17 17:46:17 1. /fasttest-workspace/build/./src/Common/Exception.cpp:105: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000082d6899
2025-01-17 17:46:17 2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000032c58ec
```
Also need to fix tests in other places - possibly [here](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01906_h3_to_geo.sql).

**Comment by mgill25** [comment]
> We skip fast tests for h3 related functions because we don't built the binary with H3 enabled. But they run as stateless tests. From the error log:


Yeah figured. I'm just building the fat binary with all external dependencies.  So I guess `-- Tags: no-fasttest` will make sure this test isn't a _fasttest_?

> Also need to fix tests in other places - possibly [here](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01906_h3_to_geo.sql).

Yeah saw those while grepping the code. Will look 👍🏼

**Comment by mgill25** [comment]
Seems like the latest failure is some Logical Error _unrelated_ to the PR: https://s3.amazonaws.com/clickhouse-test-reports/74719/6ad0a5273300607bbe9f2fd27c3e31c3f331bb98/stateless_tests__release__old_analyzer__s3_storage__databasereplicated__[2_2].html

**Comment by rschu1ze** [comment]
Yes, that's definitely unrelated.
