### PR TITLE
Fix AddressSanitizer: SEGV : Add null pointer check in getQuotaUsage()

### LINKED ISSUE #84245: AddressSanitizer: SEGV on EnabledQuota::getUsage inside InterpreterShowCreateAccessEntityQuery
### Describe the bug

https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=d3df74ff06a8709e7ebca74e30d636678c0323d2&name_0=NightlyFuzzers&name_1=libFuzzer%20tests&name_1=libFuzzer%20tests

### How to reproduce

_No response_

### Error message and/or stacktrace

```
==693==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000088 (pc 0xaaf8e59b0d48 bp 0xffffdb87cf60 sp 0xffffdb87cec0 T0)
==693==The signal is caused by a READ memory access.
==693==Hint: address points to the zero page.
warning: address range table at offset 0x10bde90 has a premature terminator entry at offset 0x10c4620
warning: address range table at offset 0x11171b0 has a premature terminator entry at offset 0x1118520
warning: address range table at offset 0x1122570 has a premature terminator entry at offset 0x11228a0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260a0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260b0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260c0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260d0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260e0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260f0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x1126100
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127bc0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127bd0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127be0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127bf0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127c00
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127c10
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127c20
warning: address range table at offset 0x1130750 has a premature terminator entry at offset 0x1130dc0
warning: address range table at offset 0x1130750 has a premature terminator entry at offset 0x1130e20
warning: address range table at offset 0x1138000 has a premature terminator entry at offset 0x1138b50
warning: address range table at offset 0x1138000 has a premature terminator entry at offset 0x1138b60
warning: address range table at offset 0x1138000 has a premature terminator entry at offset 0x1138b90
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414a0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414b0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414c0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414d0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414e0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141a90
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141ab0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141ac0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141d90
warning: address range table at offset 0x115c3e0 has a premature terminator entry at offset 0x115d4d0
warning: address range table at offset 0x116a130 has a premature terminator entry at offset 0x116a4e0
warning: address range table at offset 0x116a130 has a premature terminator entry at offset 0x116a520
warning: address range table at offset 0x116f000 has a premature terminator entry at offset 0x116f2a0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd00
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd10
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd20
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd50
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd60
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd90
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fe20
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fe40
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fe50
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fed0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fee0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170080
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x11700b0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170120
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170330
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170340
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170360
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170370
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170390
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170430
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170440
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170460
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170540
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170560
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716b0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716c0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716d0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716e0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716f0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x1171700
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x1171710
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x1171720
warning: address range table at offset 0x1185540 has a premature terminator entry at offset 0x1185840
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x11893c0
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189510
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189620
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189630
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189640
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x11896e0
warning: address range table at offset 0x11ca840 has a premature terminator entry at offset 0x11cacb0
warning: address range table at offset 0x11ca840 has a premature terminator entry at offset 0x11cacc0
warning: address range table at offset 0x11fe030 has a premature terminator entry at offset 0x11fed60
warning: address range table at offset 0x125d4b0 has a premature terminator entry at offset 0x125d530
warning: address range table at offset 0x126a910 has a premature terminator entry at offset 0x126abc0
warning: address range table at offset 0x126f290 has a premature terminator entry at offset 0x126f3e0
warning: address range table at offset 0x1294c00 has a premature terminator entry at offset 0x12950d0
warning: address range table at offset 0x1294c00 has a premature terminator entry at offset 0x12950e0
warning: address range table at offset 0x1294c00 has a premature terminator entry at offset 0x1295110
warning: address range table at offset 0x12d7380 has a premature terminator entry at offset 0x12d7e10
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x1304760
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x1304790
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x13047a0
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x13047c0
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x13047d0
warning: address range table at offset 0x1314950 has a premature terminator entry at offset 0x1314b00
    #0 0xaaf8e59b0d48 in boost::detail::spinlock::try_lock() ci/tmp/build/./contrib/boost/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:48:16
    #1 0xaaf8e59b0d48 in boost::detail::spinlock::lock() ci/tmp/build/./contrib/boost/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:53:31
    #2 0xaaf8e59b0d48 in boost::detail::spinlock::scoped_lock::scoped_lock(boost::detail::spinlock&) ci/tmp/build/./contrib/boost/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:79:16
    #3 0xaaf8e59b0d48 in boost::atomic_shared_ptr<DB::EnabledQuota::Intervals const>::load() const ci/tmp/build/./contrib/boost/boost/smart_ptr/atomic_shared_ptr.hpp:108:46
    #4 0xaaf8e59b0d48 in DB::EnabledQuota::getUsage() const ci/tmp/build/./src/Access/EnabledQuota.cpp:318:29
    #5 0xaaf8e5852698 in DB::ContextAccess::getQuotaUsage() const ci/tmp/build/./src/Access/ContextAccess.cpp:516:24
    #6 0xaaf8e9ed8f04 in DB::ContextAccessWrapper::getQuotaUsage() const ci/tmp/build/./src/Access/ContextAccess.h:242:84
    #7 0xaaf8e9ed8f04 in DB::Context::getQuotaUsage() const ci/tmp/build/./src/Interpreters/Context.cpp:1915:25
    #8 0xaaf8f1ff1cf4 in DB::InterpreterShowCreateAccessEntityQuery::getEntities() const ci/tmp/build/./src/Interpreters/Access/InterpreterShowCreateAccessEntityQuery.cpp:306:36
    #9 0xaaf8f1ff0b78 in DB::InterpreterShowCreateAccessEntityQuery::getCreateQueries() const ci/tmp/build/./src/Interpreters/Access/InterpreterShowCreateAccessEntityQuery.cpp:353:21
    #10 0xaaf8f1fef0b0 in DB::InterpreterShowCreateAccessEntityQuery::executeImpl() ci/tmp/build/./src/Interpreters/Access/InterpreterShowCreateAccessEntityQuery.cpp:265:27
    #11 0xaaf8f1feedb0 in DB::InterpreterShowCreateAccessEntityQuery::execute() ci/tmp/build/./src/Interpreters/Access/InterpreterShowCreateAccessEntityQuery.cpp:257:20
    #12 0xaaf8eabc1894 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::ImplicitTransactionControlExecutor>) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1561:40
    #13 0xaaf8eabb1ab0 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1769:11
    #14 0xaaf8cd4fa2b4 in LLVMFuzzerTestOneInput ci/tmp/build/./src/Interpreters/fuzzers/execute_query_fuzzer.cpp:71:19
    #15 0xaaf9018bb714 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
    #16 0xaaf9018ba5b4 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:516:7
    #17 0xaaf9018bed54 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:829:7
    #18 0xaaf9018bfb48 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:867:3
    #19 0xaaf9018a5430 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:915:6
    #20 0xaaf90189bd34 in main ci/tmp/build/./contrib/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #21 0xff9147e273f8  (/lib/aarch64-linux-gnu/libc.so.6+0x273f8) (BuildId: a10ee556ec5706640b27d9a9c346cb29e9516cec)
    #22 0xff9147e274c8 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274c8) (BuildId: a10ee556ec5706640b27d9a9c346cb29e9516cec)

AddressSanitizer can not provide additional info.
warning: address range table at offset 0x10bde90 has a premature terminator entry at offset 0x10c4620
warning: address range table at offset 0x11171b0 has a premature terminator entry at offset 0x1118520
warning: address range table at offset 0x1122570 has a premature terminator entry at offset 0x11228a0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260a0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260b0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260c0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260d0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260e0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x11260f0
warning: address range table at offset 0x1125fd0 has a premature terminator entry at offset 0x1126100
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127bc0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127bd0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127be0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127bf0
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127c00
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127c10
warning: address range table at offset 0x1127b70 has a premature terminator entry at offset 0x1127c20
warning: address range table at offset 0x1130750 has a premature terminator entry at offset 0x1130dc0
warning: address range table at offset 0x1130750 has a premature terminator entry at offset 0x1130e20
warning: address range table at offset 0x1138000 has a premature terminator entry at offset 0x1138b50
warning: address range table at offset 0x1138000 has a premature terminator entry at offset 0x1138b60
warning: address range table at offset 0x1138000 has a premature terminator entry at offset 0x1138b90
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414a0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414b0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414c0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414d0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x11414e0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141a90
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141ab0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141ac0
warning: address range table at offset 0x113fab0 has a premature terminator entry at offset 0x1141d90
warning: address range table at offset 0x115c3e0 has a premature terminator entry at offset 0x115d4d0
warning: address range table at offset 0x116a130 has a premature terminator entry at offset 0x116a4e0
warning: address range table at offset 0x116a130 has a premature terminator entry at offset 0x116a520
warning: address range table at offset 0x116f000 has a premature terminator entry at offset 0x116f2a0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd00
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd10
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd20
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd50
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd60
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fd90
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fe20
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fe40
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fe50
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fed0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x116fee0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170080
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x11700b0
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170120
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170330
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170340
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170360
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170370
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170390
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170430
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170440
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170460
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170540
warning: address range table at offset 0x116f330 has a premature terminator entry at offset 0x1170560
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716b0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716c0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716d0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716e0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x11716f0
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x1171700
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x1171710
warning: address range table at offset 0x1170710 has a premature terminator entry at offset 0x1171720
warning: address range table at offset 0x1185540 has a premature terminator entry at offset 0x1185840
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x11893c0
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189510
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189620
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189630
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x1189640
warning: address range table at offset 0x1189020 has a premature terminator entry at offset 0x11896e0
warning: address range table at offset 0x11ca840 has a premature terminator entry at offset 0x11cacb0
warning: address range table at offset 0x11ca840 has a premature terminator entry at offset 0x11cacc0
warning: address range table at offset 0x11fe030 has a premature terminator entry at offset 0x11fed60
warning: address range table at offset 0x125d4b0 has a premature terminator entry at offset 0x125d530
warning: address range table at offset 0x126a910 has a premature terminator entry at offset 0x126abc0
warning: address range table at offset 0x126f290 has a premature terminator entry at offset 0x126f3e0
warning: address range table at offset 0x1294c00 has a premature terminator entry at offset 0x12950d0
warning: address range table at offset 0x1294c00 has a premature terminator entry at offset 0x12950e0
warning: address range table at offset 0x1294c00 has a premature terminator entry at offset 0x1295110
warning: address range table at offset 0x12d7380 has a premature terminator entry at offset 0x12d7e10
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x1304760
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x1304790
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x13047a0
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x13047c0
warning: address range table at offset 0x13046d0 has a premature terminator entry at offset 0x13047d0
warning: address range table at offset 0x1314950 has a premature terminator entry at offset 0x1314b00
SUMMARY: AddressSanitizer: SEGV ci/tmp/build/./contrib/boost/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:48:16 in boost::detail::spinlock::try_lock()
==693==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x53,0x48,0x4f,0x57,0x20,0x43,0x72,0x45,0x41,0x54,0x45,0x20,0x51,0x55,0x4f,0x54,0x41,0x20,0xa,
SHOW CrEATE QUOTA \012
artifact_prefix='./'; Test unit written to /test_output/execute_query_fuzzer.unit
Base64: U0hPVyBDckVBVEUgUVVPVEEgCg==
```

### PR DESCRIPTION
**Pull request by shankar-iyer**
Resolves #84245

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
A test?

**Comment by shankar-iyer** [comment]
> A test?

The regular Clickhouse server process sets up well populated Context / roles / quota object for a user login session. Hence, I cannot reproduce the crash with Clickhouse server. `execute_query_fuzzer` is a specially linked executable and directly calls entrypoint `executeQuery` with fuzz'ed SQLs. The `Context` in `execute_query_fuzzer` ends up with a null default roles   and hence the crash when specifically executing 'SHOW CREATE QUOTA'.

File: src/Access/ContextAccess.cpp [hunk 1]
```diff
@@ -513,6 +513,8 @@ std::shared_ptr<const EnabledQuota> ContextAccess::getQuota() const
 
 std::optional<QuotaUsage> ContextAccess::getQuotaUsage() const
 {
+    if (getQuota() == nullptr) /// Detected by fuzzer
```
Comment (rschu1ze) [inline src/Access/ContextAccess.cpp]: 1. Can we write the code like this

```cpp
auto quota = getQuota();
if (!quota)
    return {};
else
    quota->getUsage();
```

2. Returning `std::nullopt` may cause follow-up problems further up the stack. Perhaps we should throw an exception similar to l. 491? If _only_ the fuzzer runs into this path it can be changed to handle this situation gracefully.

Comment (shankar-iyer) [reply src/Access/ContextAccess.cpp]: I returned `nullopt` because the routine had the capability of `optional` return. I can throw an exception. The fuzzer is well designed to handle all exceptions, I will anyways again test with throwing an exception.

Comment (shankar-iyer) [reply src/Access/ContextAccess.cpp]: Turns out that throwing a exception of type `LOGICAL_ERROR` will still cause the fuzzer to abort (because of https://github.com/ClickHouse/ClickHouse/blob/a7f922cea2ce628137d2ca0e823e56fe090d04aa/src/Common/Exception.cpp#L68. Only `LOGICAL_ERROR` makes sense I think. 

I have retained the return of `nullopt` since `optional<>` was in place.

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
This is the most beautiful thing I have seen this week.

grafik
