### PR TITLE
Fix __actionName, add tests for internal functions direct call

### LINKED ISSUE #62271: Analyzer: Logical error on `__actionName` call from sql
https://s3.amazonaws.com/clickhouse-test-reports/62261/c70ecfe5f3bc37ad49dffb79158a86dc887de798/stateless_tests__asan__[1_4].html

```
2024.04.04 08:07:26.090059 [ 4207 ] {52304732-8c36-4768-b010-46d3c977de83} <Debug> executeQuery: (from [::1]:40756) (comment: 00746_sql_fuzzy.sh) SELECT __actionName('~v+', ''); (stage: Complete)
2024.04.04 08:07:26.090136 [ 3805 ] {5ff86783-4649-46c2-9f7d-fae0cb477c08} <Debug> test_bchx4xgw.mt_00763_1 (e66abf01-4ea0-4fee-a5f5-6494ce19ab7c) (SelectExecutor): Key condition: unknown
2024.04.04 08:07:26.090345 [ 3805 ] {5ff86783-4649-46c2-9f7d-fae0cb477c08} <Debug> test_bchx4xgw.mt_00763_1 (e66abf01-4ea0-4fee-a5f5-6494ce19ab7c) (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 1/1 marks by primary key, 1 marks to read from 1 ranges
2024.04.04 08:07:26.090433 [ 3805 ] {5ff86783-4649-46c2-9f7d-fae0cb477c08} <Trace> test_bchx4xgw.mt_00763_1 (e66abf01-4ea0-4fee-a5f5-6494ce19ab7c) (SelectExecutor): Spreading mark ranges among streams (default reading)
2024.04.04 08:07:26.090590 [ 3805 ] {5ff86783-4649-46c2-9f7d-fae0cb477c08} <Trace> test_bchx4xgw.mt_00763_1 (e66abf01-4ea0-4fee-a5f5-6494ce19ab7c) (SelectExecutor): Reading 1 ranges in order from part all_1_1_0_425, approx. 3 rows starting from 0
2024.04.04 08:07:26.090749 [ 3750 ] {} <Trace> TCP-Session: ebeeb68f-d6fe-49a3-81bf-512a94a6ff86 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2024.04.04 08:07:26.091632 [ 4207 ] {52304732-8c36-4768-b010-46d3c977de83} <Trace> Planner: Query SELECT __actionName('~v+', '') AS `__actionName('~v+', '')` FROM system.one AS __table1 to stage Complete
2024.04.04 08:07:26.091827 [ 4207 ] {52304732-8c36-4768-b010-46d3c977de83} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2024.04.04 08:07:26.092190 [ 4207 ] {52304732-8c36-4768-b010-46d3c977de83} <Trace> Planner: Query SELECT __actionName('~v+', '') AS `__actionName('~v+', '')` FROM system.one AS __table1 from stage FetchColumns to stage Complete
2024.04.04 08:07:26.092508 [ 4207 ] {52304732-8c36-4768-b010-46d3c977de83} <Fatal> : Logical error: 'No node with name . There are only nodes __table1.dummy, '~v+'_String, ''_String, __actionName('~v+'_String, ''_String)'.

```

```
2024-04-04 08:07:26 Thread 1152 "TCPHandler" received signal SIGABRT, Aborted.
2024-04-04 08:07:26 [Switching to Thread 0x7f81019f6640 (LWP 4207)]
2024-04-04 08:07:26 0x00007f878b2579fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-04 08:07:26 #0  0x00007f878b2579fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-04 08:07:26 No symbol table info available.
2024-04-04 08:07:26 #1  0x00007f878b203476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-04 08:07:26 No symbol table info available.
2024-04-04 08:07:26 #2  0x00007f878b1e97f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2024-04-04 08:07:26 No symbol table info available.
2024-04-04 08:07:26 #3  0x000055b37988c874 in DB::abortOnFailedAssertion (description=...) at ./build_docker/./src/Common/Exception.cpp:44
2024-04-04 08:07:26 No locals.
2024-04-04 08:07:26 #4  0x000055b37988e229 in DB::handle_error_code (msg=..., trace=..., code=<optimized out>, remote=<optimized out>) at ./build_docker/./src/Common/Exception.cpp:60
2024-04-04 08:07:26 No locals.
2024-04-04 08:07:26 #5  DB::Exception::Exception (this=0x515003099f00, msg_masked=..., code=<optimized out>, remote_=<optimized out>) at ./build_docker/./src/Common/Exception.cpp:101
2024-04-04 08:07:26 No locals.
2024-04-04 08:07:26 #6  0x000055b36977b376 in DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, FormatStringHelperImpl<std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type, std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) ()
2024-04-04 08:07:26 No symbol table info available.
2024-04-04 08:07:26 #7  0x000055b388d104ff in DB::(anonymous namespace)::ActionsScopeNode::getNodeOrThrow (this=<optimized out>, node_name=...) at ./build_docker/./src/Planner/PlannerActionsVisitor.cpp:418
2024-04-04 08:07:27         it = <optimized out>
2024-04-04 08:07:27 #8  0x000055b388cf7dc9 in DB::(anonymous namespace)::PlannerActionsVisitorImpl::visit (this=0x7f80ff82b9b0, expression_node=...) at ./build_docker/./src/Planner/PlannerActionsVisitor.cpp:545
2024-04-04 08:07:27         node_name = @0x7f80ff82b840: {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = 0x2030203235313900 <error: Cannot access memory at address 0x2030203235313900>, __size_ = 4049914956759441456, __cap_ = 15534111270641716, __is_long_ = 0}, __s = {__data_ = "\000\071\061\065\062 0 0 0 20484 0 107", __padding_ = 0x7f80ff82b857 "", __size_ = 0 '\000', __is_long_ = 0 '\000'}, __r = {__words = {2319389208108677376, 4049914956759441456, 15534111270641716}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}
2024-04-04 08:07:27         node = @0x502001f4ecd0: {__ptr_ = 0x511000468898, __cntrl_ = 0x511000468880}
2024-04-04 08:07:27         __range3 = <optimized out>
2024-04-04 08:07:27         __begin3 = {__i = 0x502001f4ecd0}
2024-04-04 08:07:27         __end3 = {__i = 0x502001f4ece0}
2024-04-04 08:07:27         expression_list_node = <optimized out>
2024-04-04 08:07:27         result = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::ActionsDAG::Node const**, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::ActionsDAG::Node const*>, 1, true>> = {<std::__1::allocator<DB::ActionsDAG::Node const*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::ActionsDAG::Node const*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}
2024-04-04 08:07:27         expression_list_node = <optimized out>
2024-04-04 08:07:27         node_name = <optimized out>
2024-04-04 08:07:27         _ = <optimized out>
2024-04-04 08:07:27         __range3 = <optimized out>
2024-04-04 08:07:27         __begin3 = <optimized out>
2024-04-04 08:07:27         __end3 = <optimized out>
2024-04-04 08:07:27         node = <optimized out>
2024-04-04 08:07:27         node_name = <optimized out>
2024-04-04 08:07:27         _ = <optimized out>
2024-04-04 08:07:27 #9  DB::PlannerActionsVisitor::visit (this=<optimized out>, actions_dag=..., expression_node=...) at ./build_docker/./src/Planner/PlannerActionsVisitor.cpp:946
2024-04-04 08:07:27         actions_visitor_impl = {actions_stack = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::(anonymous namespace)::ActionsScopeNode*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::(anonymous namespace)::ActionsScopeNode>, 1, true>> = {<std::__1::allocator<DB::(anonymous namespace)::ActionsScopeNode>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::(anonymous namespace)::ActionsScopeNode> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, node_to_node_name = {__table_ = {__bucket_list_ = {__ptr_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>**, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>*> >, 1, false>> = {__value_ = {__data_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>*>, 1, true>> = {<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>*>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, <No data fields>}}, __p1_ = {<std::__1::__compressed_pair_elem<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*>, 0, false>> = {__value_ = {__next_ = <optimized out>}}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> >, 1, true>> = {<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p2_ = {<std::__1::__compressed_pair_elem<unsigned long, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_hasher<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::shared_ptr<DB::IQueryTreeNode> >, std::__1::equal_to<std::__1::shared_ptr<DB::IQueryTreeNode> >, true>, 1, true>> = {<std::__1::__unordered_map_hasher<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::shared_ptr<DB::IQueryTreeNode> >, std::__1::equal_to<std::__1::shared_ptr<DB::IQueryTreeNode> >, true>> = {<std::__1::hash<std::__1::shared_ptr<DB::IQueryTreeNode> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, __p3_ = {<std::__1::__compressed_pair_elem<float, 0, false>> = {__value_ = 1}, <std::__1::__compressed_pair_elem<std::__1::__unordered_map_equal<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::shared_ptr<DB::IQueryTreeNode> >, std::__1::hash<std::__1::shared_ptr<DB::IQueryTreeNode> >, true>, 1, true>> = {<std::__1::__unordered_map_equal<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::__hash_value_type<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::shared_ptr<DB::IQueryTreeNode> >, std::__1::hash<std::__1::shared_ptr<DB::IQueryTreeNode> >, true>> = {<std::__1::equal_to<std::__1::shared_ptr<DB::IQueryTreeNode> >> = {<std::__1::__binary_function_keep_layout_base<std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::shared_ptr<DB::IQueryTreeNode>, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}, planner_context = {__ptr_ = 0x0, __cntrl_ = 0x0}, action_node_name_helper = {node_to_name = @0x7f80ff82b9c8, planner_context = @0x5120017ee358, use_column_identifier_as_action_node_name = true}, use_column_identifier_as_action_node_name = true}
2024-04-04 08:07:27 #10 0x000055b38b25df17 in DB::buildActionsDAGFromExpressionNode (expression_node=..., input_columns=..., planner_context=...) at ./build_docker/./src/Planner/Utils.cpp:242
2024-04-04 08:07:28         expression_dag_index_nodes = <optimized out>
2024-04-04 08:07:28         action_dag = {__ptr_ = 0x0, __cntrl_ = <synthetic pointer>}
2024-04-04 08:07:28         actions_visitor = <optimized out>
2024-04-04 08:07:28 #11 0x000055b38b311364 in DB::(anonymous namespace)::analyzeProjection (query_node=..., input_columns=..., planner_context=..., actions_chain=...) at ./build_docker/./src/Planner/PlannerExpressionAnalysis.cpp:316
2024-04-04 08:07:28         projection_actions = <optimized out>
2024-04-04 08:07:28         projection_columns = <optimized out>
2024-04-04 08:07:28         projection_columns_size = <optimized out>
2024-04-04 08:07:28         projection_column_names = <optimized out>
2024-04-04 08:07:28         projection_column_names_with_display_aliases = <optimized out>
2024-04-04 08:07:28         projection_outputs_size = <optimized out>
2024-04-04 08:07:28         projection_actions_step = <optimized out>
2024-04-04 08:07:28         result = <optimized out>
2024-04-04 08:07:28         projection_actions_outputs = <optimized out>
2024-04-04 08:07:28         i = <optimized out>
2024-04-04 08:07:28         projection_column = <optimized out>
2024-04-04 08:07:28         projection_node = <optimized out>
2024-04-04 08:07:28         projection_node_name = <optimized out>
2024-04-04 08:07:28 #12 DB::buildExpressionAnalysisResult (query_tree=..., join_tree_input_columns=..., planner_context=..., planner_query_processing_info=...) at ./build_docker/./src/Planner/PlannerExpressionAnalysis.cpp:516
2024-04-04 08:07:28         actions_chain = {steps = {__begin_ = 0x0, __end_ = 0x0, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::unique_ptr<DB::ActionsChainStep, std::__1::default_delete<DB::ActionsChainStep> >*, 0, false>> = {__value_ = 0x0}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::unique_ptr<DB::ActionsChainStep, std::__1::default_delete<DB::ActionsChainStep> > >, 1, true>> = {<std::__1::allocator<std::__1::unique_ptr<DB::ActionsChainStep, std::__1::default_delete<DB::ActionsChainStep> > >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::unique_ptr<DB::ActionsChainStep, std::__1::default_delete<DB::ActionsChainStep> > > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}
2024-04-04 08:07:28         where_analysis_result_optional = {<std::__1::__optional_move_assign_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_copy_assign_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_move_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_copy_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_storage_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_destruct_base<DB::FilterAnalysisResult, false>> = {{__null_state_ = <optimized out>, __val_ = {filter_actions = {__ptr_ = <optimized out>, __cntrl_ = <optimized out>}, filter_column_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = <optimized out>, __size_ = <optimized out>, __cap_ = <optimized out>, __is_long_ = <optimized out>}, __s = {__data_ = {<optimized out> <repeats 23 times>}, __padding_ = 0x0, __size_ = <optimized out>, __is_long_ = <optimized out>}, __r = {__words = {<optimized out>, <optimized out>, <optimized out>}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, remove_filter_column = <optimized out>}}, __engaged_ = false}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2024-04-04 08:07:28         current_output_columns = <optimized out>
2024-04-04 08:07:28         aggregation_analysis_result_optional = {<std::__1::__optional_move_assign_base<DB::AggregationAnalysisResult, false>> = {<std::__1::__optional_copy_assign_base<DB::AggregationAnalysisResult, false>> = {<std::__1::__optional_move_base<DB::AggregationAnalysisResult, false>> = {<std::__1::__optional_copy_base<DB::AggregationAnalysisResult, false>> = {<std::__1::__optional_storage_base<DB::AggregationAnalysisResult, false>> = {<std::__1::__optional_destruct_base<DB::AggregationAnalysisResult, false>> = {{__null_state_ = <optimized out>, __val_ = {before_aggregation_actions = {__ptr_ = <optimized out>, __cntrl_ = <optimized out>}, aggregation_keys = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, 1, true>> = {<std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >> = {<std::__1::__non_trivial_if<true, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, aggregate_descriptions = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::AggregateDescription*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::AggregateDescription>, 1, true>> = {<std::__1::allocator<DB::AggregateDescription>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::AggregateDescription> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, grouping_sets_parameters_list = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::GroupingSetsParams*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::GroupingSetsParams>, 1, true>> = {<std::__1::allocator<DB::GroupingSetsParams>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::GroupingSetsParams> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, group_by_with_constant_keys = <optimized out>}}, __engaged_ = false}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2024-04-04 08:07:28         having_analysis_result_optional = {<std::__1::__optional_move_assign_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_copy_assign_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_move_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_copy_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_storage_base<DB::FilterAnalysisResult, false>> = {<std::__1::__optional_destruct_base<DB::FilterAnalysisResult, false>> = {{__null_state_ = <optimized out>, __val_ = {filter_actions = {__ptr_ = <optimized out>, __cntrl_ = <optimized out>}, filter_column_name = {static __endian_factor = 1, __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__data_ = <optimized out>, __size_ = <optimized out>, __cap_ = <optimized out>, __is_long_ = <optimized out>}, __s = {__data_ = {<optimized out> <repeats 23 times>}, __padding_ = 0x0, __size_ = <optimized out>, __is_long_ = <optimized out>}, __r = {__words = {<optimized out>, <optimized out>, <optimized out>}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<char> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}, remove_filter_column = <optimized out>}}, __engaged_ = false}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
2024-04-04 08:07:28         window_analysis_result_optional = {<std::__1::__optional_move_assign_base<DB::WindowAnalysisResult, false>> = {<std::__1::__optional_copy_assign_base<DB::WindowAnalysisResult, false>> = {<std::__1::__optional_move_base<DB::WindowAnalysisResult, false>> = {<std::__1::__optional_copy_base<DB::WindowAnalysisResult, false>> = {<std::__1::__optional_storage_base<DB::WindowAnalysisResult, false>> = {<std::__1::__optional_destruct_base<DB::WindowAnalysisResult, false>> = {{__null_state_ = <optimized out>, __val_ = {before_window_actions = {__ptr_ = <optimized out>, __cntrl_ = <optimized out>}, window_descriptions = {__begin_ = <optimized out>, __end_ = <optimized out>, __end_cap_ = {<std::__1::__compressed_pair_elem<DB::WindowDescription*, 0, false>> = {__value_ = <optimized out>}, <std::__1::__compressed_pair_elem<std::__1::allocator<DB::WindowDescription>, 1, true>> = {<std::__1::allocator<DB::WindowDescription>> = {<std::__1::__non_trivial_if<true, std::__1::allocator<DB::WindowDescription> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}}}, __engaged_ = false}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__1::__sfinae_ctor_base<true, true>> = {<No data fields>}, <std::__1::__sfinae_assign_base<true, true>> = {<No data fields>}, <No data fields>}
```

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

close https://github.com/ClickHouse/ClickHouse/issues/62271

### CODE REVIEW

File: src/Planner/PlannerActionsVisitor.cpp [hunk 1]
```diff
@@ -159,7 +159,17 @@ class ActionNodeNameHelper
                 const auto & function_node = node->as<FunctionNode &>();
                 if (function_node.getFunctionName() == "__actionName")
                 {
-                    result = toString(function_node.getArguments().getNodes().at(1)->as<ConstantNode>()->getValue());
+                    /// Perform sanity check, because user may call this function with unexpected arguments
```
Comment (novikd) [inline src/Planner/PlannerActionsVisitor.cpp:162]: This function should be allowed to be called by user. This is a implementation specific function.

Comment (vdimir) [reply src/Planner/PlannerActionsVisitor.cpp:162]: How can we forbid it? One possible option to have a specific setting in context that allows creating such functions, but it become more tricky to distinguish cases when query comes from remote server. Probably, `__actionName` cannot be transferred to remote, but I'm not sure (maybe some complex case with `Merge` over `Distributed`).

Comment (novikd) [reply src/Planner/PlannerActionsVisitor.cpp:162]: We have ClientInfo in the context check if query come from user or from another server. The initiator should throw an exception if user calls this function.

Comment (vdimir) [reply src/Planner/PlannerActionsVisitor.cpp:162]: Ok, let's merge this PR and backport since it's a trivial one and prevents segfault, and then discuss something more sophisticated to forbid `__actionName` call from SQL in more

**Comment by vdimir** [comment]
> AST fuzzer (debug) — Logical error: 'Unexpected return type from concat. Expected Nullable. Got String'. [Details](https://s3.amazonaws.com/clickhouse-test-reports/62287/4ce35b1fe68e13fd64fc545f6431724c038f9022/ast_fuzzer__debug_.html)
> AST fuzzer (msan) — Logical error: 'Unexpected return type from concat. Expected Nullable. Got String'. [Details](https://s3.amazonaws.com/clickhouse-test-reports/62287/4ce35b1fe68e13fd64fc545f6431724c038f9022/ast_fuzzer__msan_.html)
> AST fuzzer (tsan) — Logical error: 'Unexpected return type from concat. Expected Nullable. Got String'. [Details](https://s3.amazonaws.com/clickhouse-test-reports/62287/4ce35b1fe68e13fd64fc545f6431724c038f9022/ast_fuzzer__tsan_.html)

Checking..

> Stateful tests (release, ParallelReplicas) — fail: 1, passed: 129, skipped: 5 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62287/4ce35b1fe68e13fd64fc545f6431724c038f9022/stateful_tests__release__parallelreplicas_.html)

https://github.com/ClickHouse/ClickHouse/issues/62252

> Stateless tests (msan) [6/6] — fail: 1, passed: 1022, skipped: 7 [Details](https://s3.amazonaws.com/clickhouse-test-reports/62287/4ce35b1fe68e13fd64fc545f6431724c038f9022/stateless_tests__msan__[6_6].html)

https://github.com/ClickHouse/ClickHouse/issues/47866

**Comment by clickgapai** [comment]
Hi @vdimir — while reviewing this PR I found the following:

- **Coverage gap:** `__actionName` `useDefaultImplementationForLowCardinalityColumns() = false` override is untested — https://github.com/ClickHouse/ClickHouse/pull/104006

Could you review the test PR and add the `can be tested` label if it looks good?
Happy to discuss — close anything that's wrong or already addressed.
