### PR TITLE
Fix for positional args

### LINKED ISSUE #31173: enable_positional_arguments doesnt work with substr(key, 10)
**Describe what's wrong**

ClickHouse doesn't understand that argument belongs to substr function

**Does it reproduce on recent release?**

21.11

**How to reproduce**
```
WITH 'aaaaaaaaaaaaaa' AS key
SELECT substr(key, 10) AS key_a
FROM numbers(10)
GROUP BY key_a
SETTINGS enable_positional_arguments = 1


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 21.12.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Positional argument out of bounds: 10 (exprected in range [1, 1]. (ILLEGAL_TYPE_OF_ARGUMENT)
```

**Expected behavior**

Query works

**Error message and/or stacktrace**

Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Positional argument out of bounds: 10 (exprected in range [1, 1]. (ILLEGAL_TYPE_OF_ARGUMENT)

### PR DESCRIPTION
**Pull request by kssenii**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix throwing exception like positional argument out of bounds for non-positional arguments. Closes https://github.com/ClickHouse/ClickHouse/issues/31173#event-5789668239.

### CODE REVIEW

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 1]
```diff
@@ -177,20 +176,12 @@ bool checkPositionalArguments(ASTPtr & argument, const ASTSelectQuery * select_q
...
-                positional &= checkPositionalArguments(arg, select_query, expression);
-        }
+            return false;
     }
     else
-        positional = false;
+        return false;
 
-    return positional;
+    return true;
```
Comment (tavplubix) [inline src/Interpreters/ExpressionAnalyzer.cpp:184]: This line is never executed

File: src/Interpreters/ExpressionAnalyzer.cpp [hunk 2]
```diff
@@ -177,20 +176,12 @@ bool checkPositionalArguments(ASTPtr & argument, const ASTSelectQuery * select_q
...
-            positional = false;
-    }
-    else if (const auto * ast_function = typeid_cast<const ASTFunction *>(argument.get()))
-    {
-        if (ast_function->arguments)
-        {
-            for (auto & arg : ast_function->arguments->children)
-                positional &= checkPositionalArguments(arg, select_query, expression);
-        }
+            return false;
```
Comment (tavplubix) [inline src/Interpreters/ExpressionAnalyzer.cpp:179]: It would be better to use [return early pattern](https://szymonkrajewski.pl/why-should-you-return-early/) here to get rid of some nested branches and make code more readable, but it's minor remark, feel free to ignore it.

**Review by tavplubix — APPROVED** [review]

File: src/Interpreters/ExpressionAnalyzer.cpp (hunk 1 above)
Comment (kssenii) [reply src/Interpreters/ExpressionAnalyzer.cpp:184]: It is executed (case when first 3 if's are true)
