### PR TITLE
Fix `Couldn't pack tar archive: Failed to write all bytes` error caused by incorrect archive entry size set in header

### LINKED ISSUE #89075: Another bad backup
### Describe the bug

Seems not related to https://github.com/ClickHouse/ClickHouse/issues/84711 and https://github.com/ClickHouse/ClickHouse/issues/81871

### How to reproduce

Set `default` as an allowed disk, then run:
```sql
CREATE TABLE t0 (c1 Map(Int,Int), c2 Int) ENGINE = MergeTree() ORDER BY tuple() PARTITION BY (c1, c2 % 6084);
INSERT INTO TABLE t0 (c1, c2) SELECT map(), 2 FROM numbers(100);
SET min_insert_block_size_rows = 64, optimize_trivial_insert_select = 1;
INSERT INTO TABLE t0 (c1, c2) SELECT c1, c2 FROM generateRandom('c1 Map(Int,Int), c2 Int', 2607967781039168224, 1, 1) LIMIT 400;
BACKUP TABLE t0 TO Disk('default', 'b0.tar');
```

### Error message and/or stacktrace

Stack trace:
```
<Error> BackupsWorker: Failed to make backup Disk('default', 'b0.tar'): Code: 642. DB::Exception: Couldn't pack tar archive: Failed to write all bytes, 0 of 65448, filename='.backup'. (CANNOT_PACK_ARCHIVE), Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000247d85b2
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014ff0069
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d50e30e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d50dd11
4. src/Common/Exception.h:141: DB::Exception::Exception<long&, long&, String>(int, FormatStringHelperImpl<std::type_identity<long&>::type, std::type_identity<long&>::type, std::type_identity<String>::type>, long&, long&, String&&) @ 0x000000001980dd36
5. src/IO/Archives/LibArchiveWriter.cpp:93: DB::LibArchiveWriter::WriteBufferFromLibArchive::nextImpl() @ 0x000000001980d9f4
6. src/IO/WriteBuffer.h:53: DB::WriteBuffer::next() @ 0x000000000d51b59e
7. src/IO/Archives/LibArchiveWriter.cpp:74: DB::LibArchiveWriter::WriteBufferFromLibArchive::finalizeImpl() @ 0x000000001980d849
8. src/IO/WriteBuffer.cpp:95: DB::WriteBuffer::finalize() @ 0x00000000150f19f0
9. src/Backups/BackupImpl.cpp:437: DB::BackupImpl::writeBackupMetadata() @ 0x00000000197fdee9
10. src/Backups/BackupImpl.cpp:1085: DB::BackupImpl::finalizeWriting() @ 0x0000000019804969
11. src/Backups/BackupsWorker.cpp:675: DB::BackupsWorker::doBackup(std::shared_ptr<DB::IBackup>, std::shared_ptr<DB::ASTBackupQuery> const&, String const&, DB::BackupSettings const&, std::shared_ptr<DB::IBackupCoordination>, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context const> const&, bool, std::shared_ptr<DB::Cluster> const&) @ 0x00000000197db8e6
12. src/Backups/BackupsWorker.cpp:462: DB::BackupsWorker::BackupStarter::doBackup() @ 0x00000000197e91d0
13. src/Backups/BackupsWorker.cpp:551: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::BackupsWorker::startMakingBackup(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000197e400c
14. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000167c8204
15. contrib/llvm-project/libcxx/include/future:1589: std::packaged_task<void ()>::operator()() @ 0x00000000167c8377
16. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000015133693
17. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000015139d66
18. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000015130b26
19. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000015137540
20. start_thread @ 0x00000000000a27f1
21. __clone3 @ 0x0000000000133b5c
 (version 25.11.1.243 (official build))
```

### PR DESCRIPTION
**Pull request by jkartseva**
Fixes: https://github.com/ClickHouse/ClickHouse/issues/89075

This error occurs because the size value passed to `archive_entry_set_size` is incorrect when an entry's data exceeds the fixed write buffer size; it was incorrectly being set to the buffer's capacity (DBMS_DEFAULT_BUFFER_SIZE) instead of the actual file size.

An adaptive-size buffer is used to address this, accommodating entries larger than the previous fixed limit. This approach is necessary when the total entry size is impossible to know in advance, yet it is required by the archive format before the entry data is written.

The total size is now calculated at finalization time and written to the archive header before the data is committed.

When the adaptive buffer limit is exceeded, throw `ErrorCodes::LIMIT_EXCEEDED, "Adaptive buffer size limit of {} bytes is exceeded"` error.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix the `Couldn't pack tar archive: Failed to write all bytes` error caused by an incorrect archive entry size header. Fixes https://github.com/ClickHouse/ClickHouse/issues/89075

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.462`

### CODE REVIEW

File: src/IO/Archives/createArchiveWriter.h [hunk 1]
```diff
@@ -1,19 +1,22 @@
...
-/// `path_to_archive` is used only to determine the archive's type.
-std::shared_ptr<IArchiveWriter> createArchiveWriter(const String & path_to_archive, std::unique_ptr<WriteBuffer> archive_write_buffer);
-
+/// If `archive_write_buffer` is null, the archive is written to the local filesystem at `path_to_archive`.
+/// Otherwise, `path_to_archive` is used only to determine the archive type.
+std::shared_ptr<IArchiveWriter> createArchiveWriter(
+    const String & path_to_archive,
+    std::unique_ptr<WriteBuffer> archive_write_buffer = nullptr,
+    size_t buf_size = DBMS_DEFAULT_BUFFER_SIZE,
+    size_t adaptive_buffer_max_size = 8 * DBMS_DEFAULT_BUFFER_SIZE);
```
Comment (tiandiwonder) [inline src/IO/Archives/createArchiveWriter.h:21]: the max size is 8M, it really limits the use of tar backup. what about making it configurable?

File: src/IO/Archives/LibArchiveWriter.cpp [hunk 2]
```diff
@@ -82,8 +97,38 @@ class LibArchiveWriter::WriteBufferFromLibArchive : public WriteBufferFromFileBa
 private:
     void nextImpl() override
     {
-        if (!offset())
+        if (!available() && use_adaptive_buffer_size)
```
Comment (tiandiwonder) [inline src/IO/Archives/LibArchiveWriter.cpp]: trival: if the data is exactly the same size of adaptive_max_buffer_size, it will get exception.

File: src/IO/Archives/LibArchiveWriter.cpp [hunk 3]
```diff
@@ -82,8 +97,38 @@ class LibArchiveWriter::WriteBufferFromLibArchive : public WriteBufferFromFileBa
...
+        {
+            if (memory.size() >= adaptive_max_buffer_size)
+                throw Exception(
+                    ErrorCodes::LIMIT_EXCEEDED,
+                    "Adaptive buffer size limit of {} bytes is exceeded for the file '{}'",
+                    adaptive_max_buffer_size,
+                    filename);
```
Comment (tiandiwonder) [inline src/IO/Archives/LibArchiveWriter.cpp]: We can suggest zip format here?

File: src/IO/tests/gtest_archive_reader_and_writer.cpp [hunk 4]
```diff
@@ -558,6 +560,129 @@ TEST(TarArchiveReaderTest, CheckFileInfo)
     fs::remove(archive_path);
 }
 
+TEST(TarArchiveReaderAndWriterTest, BufferSizeLimitExceededUnknownContentsSize)
+{
+    thread_local_rng.seed(42);
```
[the remark this answers is not in the document]
Comment (jkartseva) [reply src/IO/tests/gtest_archive_reader_and_writer.cpp:565]: I think it's irrelevant. Parallel execution does not affect the behavior being tested.

File: src/IO/Archives/LibArchiveWriter.cpp [hunk 5]
```diff
@@ -82,8 +100,42 @@ class LibArchiveWriter::WriteBufferFromLibArchive : public WriteBufferFromFileBa
...
-        if (!offset())
+        if (use_adaptive_buffer_size)
+        {
+            if (!available())
+            {
+                if (memory.size() == adaptive_max_buffer_size)
+                    throw Exception(
+                        ErrorCodes::LIMIT_EXCEEDED,
+                        "Adaptive buffer size limit of {} bytes is exceeded for the file '{}'. "
+                        "Consider using ZIP format for files of unknown size",
```
Comment (tiandiwonder) [inline src/IO/Archives/LibArchiveWriter.cpp]: 1. unknow size is confusing, actually it's because the backup doesn't calculate the size of all files in advance?
2. "Consider using ZIP format or adjust archive_adaptive_buffer_max_size_bytes..."

Comment (jkartseva) [reply src/IO/Archives/LibArchiveWriter.cpp]: To calculate the size in advance, the backup needs to scan through the data. That can mean holding everything in memory at some point instead of flushing to the output stream, which kind of defeats the purpose.

**Comment by jkartseva** [comment]
@tiandiwonder I addressed your comments, would you take another look?

**Review by tiandiwonder — APPROVED** [review]
