### PR TITLE
Fix `Bad get: has Null` from skip index set.

### LINKED ISSUE #84856: `DB::Exception: Bad get: has Null` from skip index set
### Company or project name

N/A

### Describe what's wrong

```sql
CREATE OR REPLACE TABLE test
(
    `ts` Int64,
    `v` LowCardinality(String),
    INDEX v v TYPE set(0) GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY (ts);

INSERT INTO test (v) FORMAT Values ('VALUE1');

EXPLAIN indexes = 1 SELECT CAST('', 'Nullable(String)') AS source, v AS v FROM test WHERE (source = 'VALUE1') OR (v ILIKE 'VALUE1');

EXPLAIN indexes = 1 SELECT CAST(NULL, 'Nullable(String)') AS source, v AS v FROM test WHERE (source = 'VALUE1') OR (v ILIKE 'VALUE1');
```
https://fiddle.clickhouse.com/1cc26ccd-d117-4499-a2d0-8f2fde84b080

### Does it reproduce on the most recent release?

Yes

### How to reproduce

^

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix `Bad get` error that happened during `Set` index analysis in case the predicate contained `NULL` constant. Fixes #84856 and #82974

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Details

Resolves #84856 and #82974

### Version info
- Merged into: `25.11.1.1034`
- Backported to: `25.11.3.53`, `25.8.22.7`

### CODE REVIEW

File: tests/queries/0_stateless/03707_set_index_bad_get_null_bug.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
+drop table if exists test;
```
Comment (shankar-iyer) [inline tests/queries/0_stateless/03707_set_index_bad_get_null_bug.sql:1]: I think needs `SET parallel_replicas_local_plan = 1;` for  the failure in the Parallel_Replicas suite.

**Review by shankar-iyer — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi @KochetovNicolai @github-merge-queue[bot] @shankar-iyer — while reviewing this PR I found the following:

- **Bug (P0):** `atomFromDAG` passes NULL constant to `__bitWrapperFunc` which propagates NULL instead of UNKNOWN, causing `mayBeTrueOnGranule` to incorrectly prune matching granules — https://github.com/ClickHouse/ClickHouse/issues/103103

Happy to discuss — close anything that's wrong or already addressed.
