### PR TITLE
Better errors for CLEAR/DROP columns (possibly in partitions)

### LINKED ISSUE #7941: ClickHouse does not like empty columns in a part
```
:) create table t (a Int, b Int) engine = MergeTree order by tuple() partition by tuple();
:) insert into t values (1,2)
:) alter table t drop column b
:) alter table t add column b Int
:) alter table t drop column a
:) alter table t add column a Int

:) select * from t

SELECT *
FROM t

Received exception from server (version 19.18.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Could not find a column of minimum size in MergeTree, part /var/lib/clickhouse/data/default/t/all_1_1_0/. 

0 rows in set. Elapsed: 0.002 sec. 
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
If MergeTree table does not contain ORDER BY or PARTITION BY, it was possible to request ALTER to CLEAR all the columns and ALTER will stuck. Fixed #7941.

### CODE REVIEW

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 1]
```diff
@@ -1530,6 +1540,27 @@ void MergeTreeData::checkAlterIsPossible(const AlterCommands & commands, const S
...
+                at_least_one_column_rest = true;
+                break;
+            }
+        }
+        if (!at_least_one_column_rest)
+        {
+            std::string postfix = "";
+            if (dropped_columns.size() > 1)
+                postfix = "s";
+            throw Exception(ErrorCodes::BAD_ARGUMENTS,
```
Comment (alesapin) [inline src/Storages/MergeTree/MergeTreeData.cpp:1560]: It would be much more convenient if mutations will be able to remove absolutely empty parts. Also, we have to write empty parts, but with number rows to implement clearing of all columns in table.

File: src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp [hunk 2]
```diff
@@ -1068,20 +1068,6 @@ bool ReplicatedMergeTreeQueue::shouldExecuteLogEntry(
         }
     }
 
-    /// TODO: it makes sense to check DROP_RANGE also
```
Comment (alesapin) [inline src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1071]: Not relevant to changes, just redundant code.

**Comment by alesapin** [comment]
I'm not completely sure, about theses restrictions, but I think it's OK as a temporary solution (better than stucked mutation).
