### PR TITLE
Fix icebergS3Cluster reading with position deletes rows

### LINKED ISSUE #88287: icebergS3Cluster adds deleted rows
### Company or project name

_No response_

### Describe what's wrong

If you use icebergS3, everything works correctly, as soon as I start using icebergS3Cluster, I see duplicates by keys. On the Iceberg tables side, this row is marked as deleted.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Which ClickHouse server version to use:
25.8.4.13
Queries to run that lead to unexpected result:
TRINO:
```sql
create table test.test.test_ch_cluster(
   dataflow_dttm timestamp,
   id integer
);

insert into test.test.test_ch_cluster values 
(current_timestamp,1)


update test.test.test_ch_cluster set dataflow_dttm = current_timestamp;
```

CH:
```sql
SELECT * FROM icebergS3Cluster(standard_cluster,  NAMED_COLLECTION , url='https://s3a', filename ='table')
```

Image

```sql
SELECT * FROM icebergS3(NAMED_COLLECTION , url='https://s3a', filename ='table')
```

Image

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ted-Jiang**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fix icebergS3Cluster protocol. Started supporting schema evolution, positional and equality deletes in iceberg cluster function. Resolves #88287

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Details

Related issue: https://github.com/ClickHouse/ClickHouse/issues/88287
Closes: https://github.com/ClickHouse/ClickHouse/issues/88287

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
related issue https://github.com/ClickHouse/ClickHouse/issues/88287

**Comment by Ted-Jiang** [comment]
@kssenii could you  plz look at this pr or maybe ping someone related this ❤️

**Comment by Ted-Jiang** [comment]
Another question is how to generate related test data like below. https://github.com/ClickHouse/ClickHouse/blob/7f6dea269bac92290ef7e8363a5deefc5974f14e/tests/queries/0_stateless/03402_cluster_table_functions_settings_parsing.sql#L5

**Comment by kssenii** [comment]
> maybe ping someone related this

@divanik @scanhex12

**Comment by Ted-Jiang** [comment]
@kssenii @alexey-milovidov Is there anything i can do to make this pr in progress?

**Comment by divanik** [comment]
Yes, that's a good fix, I wanted to do the same for last several weeks but was busy by other tasks

**Comment by divanik** [comment]
@Ted-Jiang, please, add an integration test. Do you know how to do it?

File: src/Interpreters/ClusterFunctionReadTask.h [hunk 1]
```diff
@@ -1,14 +1,33 @@
...
+#include <Storages/ObjectStorage/DataLakes/Iceberg/EqualityDeleteObject.h>
+#include <Storages/ObjectStorage/IObjectIterator.h>
 
 
 namespace DB
 {
 class ReadBuffer;
 class WriteBuffer;
 
+struct IcebergObjectSerializableInfo
```
Comment (divanik) [inline src/Interpreters/ClusterFunctionReadTask.h]: I made a decision to do this struct here because I want to have all serializable entities in one place, so person who will touch this in the future will be aware of what it should do in terms of backward compatibility.

Comment (divanik) [reply src/Interpreters/ClusterFunctionReadTask.h]: Also I made a decision not to reuse this code in another parts of codebase, but if a reviewer thinks that it is better to reuse it in IcebergDataObject, I can do it

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang, please, add an integration test. Do you know how to do it?

That is one my question, how to put data on s3 like this one?

https://github.com/ClickHouse/ClickHouse/blob/7f6dea269bac92290ef7e8363a5deefc5974f14e/tests/queries/0_stateless/03402_cluster_table_functions_settings_parsing.sql#L5

**Comment by divanik** [comment]
> > @Ted-Jiang, please, add an integration test. Do you know how to do it?
> 
> That is one my question, how to put data on s3 like this one?
> 
> https://github.com/ClickHouse/ClickHouse/blob/7f6dea269bac92290ef7e8363a5deefc5974f14e/tests/queries/0_stateless/03402_cluster_table_functions_settings_parsing.sql#L5

You need to put the files to `tests/queries/0_stateless/data_minio`, they will upload to minio on a pipeline start automatically

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp [hunk 2]
```diff
@@ -69,6 +70,151 @@ std::shared_ptr<ISimpleTransform> IcebergDataObjectInfo::getPositionDeleteTransf
...
+            writeStringBinary(eq_delete_obj.file_format, out);
+            writeVarInt(eq_delete_obj.schema_id, out);
+            if (!eq_delete_obj.equality_ids)
+            {
+                writeVarUInt(0, out);
+            }
+            else
+            {
+                writeVarUInt(1, out);
+                writeVarUInt(eq_delete_obj.equality_ids->size(), out);
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp]: It should be fine to just write `size` without this 0/1 indicator before the size

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp [hunk 3]
```diff
@@ -69,6 +70,151 @@ std::shared_ptr<ISimpleTransform> IcebergDataObjectInfo::getPositionDeleteTransf
...
+                for (const auto & equality_id : *eq_delete_obj.equality_ids)
+                {
+                    writeVarInt(equality_id, out);
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp:136]: Not sure why we store these ids as ints and not uints as they must be unsigned, then we could have used `writeVarUInt`

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp [hunk 4]
```diff
@@ -69,6 +70,151 @@ std::shared_ptr<ISimpleTransform> IcebergDataObjectInfo::getPositionDeleteTransf
...
 }
+
+void IcebergDataObjectInfo::addPositionDeleteObject(Iceberg::ManifestFileEntry position_delete_object)
+{
+    auto toupper = [](String & str)
+    {
+        std::transform(str.begin(), str.end(), str.begin(), ::toupper);
+        return str;
+    };
+    if (toupper(info.file_format) != "PARQUET")
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp]:
```suggestion
    if (Poco::toUpper(info.file_format) != "PARQUET")
```

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp [hunk 5]
```diff
@@ -36,25 +38,24 @@ namespace Setting
...
-    , sequence_number(data_manifest_file_entry_.added_sequence_number)
-    , file_format(data_manifest_file_entry_.file_format)
+    , info{
+          data_manifest_file_entry_.file_path_key,
+          data_manifest_file_entry_.schema_id,
+          schema_id_relevant_to_iterator_,
+          data_manifest_file_entry_.added_sequence_number,
+          data_manifest_file_entry_.file_format,
+          {},
+          {}}
```
Comment (kssenii) [inline src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp]:
```suggestion
          /* position_deletes_objects */{},
          /* equality_deletes_objects */{}}
```

File: src/Core/ProtocolDefines.h [hunk 6]
```diff
@@ -35,7 +35,8 @@ static constexpr auto DBMS_MIN_REVISION_WITH_AGGREGATE_FUNCTIONS_VERSIONING = 54
 
 static constexpr auto DBMS_CLUSTER_INITIAL_PROCESSING_PROTOCOL_VERSION = 1;
 static constexpr auto DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION_WITH_DATA_LAKE_METADATA = 2;
-static constexpr auto DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION = 2;
+static constexpr auto DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION_WITH_ICEBERG_METADATA = 3;
+static constexpr auto DBMS_CLUSTER_PROCESSING_LAST_PROTOCOL_VERSION = DBMS_CLUSTER_PROCESSING_PROTOCOL_VERSION_WITH_ICEBERG_METADATA;
```
Comment (kssenii) [inline src/Core/ProtocolDefines.h]: Let's revert to version without "LAST" (in `DBMS_CLUSTER_PROCESSING_LAST_PROTOCOL_VERSION`) for consistency with other namings like `DBMS_PARALLEL_REPLICAS_PROTOCOL_VERSION`, `DBMS_TCP_PROTOCOL_VERSION`, etc

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp (hunk 2 above)
Comment (divanik) [reply src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp]: The type of the variable is "optional". So we need to distinguish between std::nullopt and empty arrays. I will replace if condition with !eq_delete_obj.equality_ids.has_value() so it is more clear for the reader that this is optional, but I don't want to deserialize an object to a different one.

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp (hunk 3 above)
Comment (divanik) [reply src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp:136]: In specs they are stored as ints:
image

File: src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp (hunk 2 above)
Comment (divanik) [reply src/Storages/ObjectStorage/DataLakes/Iceberg/IcebergDataObjectInfo.cpp]: As a alternative I can write down -1 in case of std::nullopt

**Comment by divanik** [comment]
I did the last change (changed warning to info) because we trigger on warnings in our integration tests (I think this is a wrong behavior, but I don't want to deal with it now)

**Review by kssenii — APPROVED** [review]

**Comment by divanik** [comment]
[Upgrade check (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88919&sha=5d01e48ce85395372336427c82ff0f48727cfaf1&name_0=PR&name_1=Upgrade%20check%20%28amd_tsan%29) - https://github.com/ClickHouse/ClickHouse/issues/89409

**Comment by divanik** [comment]
@Ted-Jiang, thank you for your contribution! The ClickHouse community really appreciates it

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang, thank you for your contribution! The ClickHouse community really appreciates it

@divanik Thanks for your helping, make this happen! 👍
