### PR TITLE
Fix `assertHasValidVersionMetadata` exception when part directory is externally removed

### LINKED ISSUE #98949: [CI crash] Double free or corruption in MergeTreeDataPartCompact
<details><summary>Stack trace details</summary>

The sipHash64(st.trace_full) is 6651196023970317821
The trace is from the master or release branch: True

The query for CIDB to compare the trace with the known one:

```sql
WITH
    (
        SELECT groupArrayDistinct(cleanStackTrace(trace_full) AS trace) FROM default.stack_traces
        WHERE sipHash64(trace) IN (6651196023970317821, {ANOTHER_TRACE_HASH}) -- FIXME: replace with the known hash
    ) AS traces,
    1.97 AS alpha,
    stack_frame_weights AS (
        WITH
            (
                SELECT count()
                FROM default.stack_traces
                FINAL
            ) AS total,
            2.0 AS beta,
            3.7 AS gamma
        SELECT
            arrayJoin(cleanStackTrace(trace_full)) AS frame,
            countDistinct(trace_full) AS count,
            log(total / count) AS IDF,
            sigmoid(beta * (IDF - gamma)) AS weight
        FROM default.stack_traces
        FINAL
        GROUP BY frame
    ),
    (SELECT groupArray(weight) AS w, groupArray(frame) AS f FROM stack_frame_weights) AS weights,
    (trace -> arrayMap((_frame, pos) -> (pow(pos, -alpha) * arrayFirst(w, f -> (f = _frame), weights.w, weights.f)), trace, arrayEnumerate(trace))) AS get_trace_weights,
    (arr -> arrayStringConcat(arr, '\n')) AS joinArr

SELECT arraySimilarity(traces[1], traces[2], get_trace_weights(traces[1]) AS weights1, get_trace_weights(traces[2]) AS weights2) AS similarity,
    arrayLevenshteinDistanceWeighted(traces[1], traces[2], weights1, weights2),
    joinArr(traces[1]), joinArr(traces[2]), joinArr(weights1), joinArr(weights2)

```
</details>

The following new stack trace from CI Logs `system.crash_log` found:

```
   __interceptor_abort
   DB::IMergeTreeDataPart::removeIfNeeded()
   DB::MergeTreeDataPartCompact::~MergeTreeDataPartCompact()
   std::__shared_ptr_emplace<DB::MergeTreeDataPartCompact, std::allocator<DB::MergeTreeDataPartCompact>>::__on_zero_shared()
   boost::multi_index::detail::ordered_index_impl<boost::multi_index::global_fun<std::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreePartInfo const&, &DB::MergeTreeData::dataPartPtrToInfo(std::shared_ptr<DB::IMergeTreeDataPart const> const&)>, std::less<DB::MergeTreePartInfo const>, boost::multi_index::detail::nth_layer<1, std::shared_ptr<DB::IMergeTreeDataPart const>, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::multi_index::tag<DB::MergeTreeData::TagByInfo, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::global_fun<std::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreePartInfo const&, &DB::MergeTreeData::dataPartPtrToInfo(std::shared_ptr<DB::IMergeTreeDataPart const> const&)>, mpl_::na>, boost::multi_index::ordered_unique<boost::multi_index::tag<DB::MergeTreeData::TagByStateAndInfo, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::global_fun<std::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeData::DataPartStateAndInfo, &DB::MergeTreeData::dataPartPtrToStateAndInfo(std::shared_ptr<DB::IMergeTreeDataPart const> const&)>, DB::MergeTreeData::LessStateDataPart>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, boost::mpl::v_item<DB::MergeTreeData::TagByInfo, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::ordered_unique_tag, boost::multi_index::detail::null_augment_policy>::delete_all_nodes(boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>>>*)
   boost::multi_index::detail::ordered_index_impl<boost::multi_index::global_fun<std::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreePartInfo const&, &DB::MergeTreeData::dataPartPtrToInfo(std::shared_ptr<DB::IMergeTreeDataPart const> const&)>, std::less<DB::MergeTreePartInfo const>, boost::multi_index::detail::nth_layer<1, std::shared_ptr<DB::IMergeTreeDataPart const>, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::multi_index::tag<DB::MergeTreeData::TagByInfo, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::global_fun<std::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreePartInfo const&, &DB::MergeTreeData::dataPartPtrToInfo(std::shared_ptr<DB::IMergeTreeDataPart const> const&)>, mpl_::na>, boost::multi_index::ordered_unique<boost::multi_index::tag<DB::MergeTreeData::TagByStateAndInfo, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::global_fun<std::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::MergeTreeData::DataPartStateAndInfo, &DB::MergeTreeData::dataPartPtrToStateAndInfo(std::shared_ptr<DB::IMergeTreeDataPart const> const&)>, DB::MergeTreeData::LessStateDataPart>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>, boost::mpl::v_item<DB::MergeTreeData::TagByInfo, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::ordered_unique_tag, boost::multi_index::detail::null_augment_policy>::delete_all_nodes(boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>>>*)
   DB::MergeTreeData::~MergeTreeData()
   DB::StorageMergeTree::~StorageMergeTree()
   std::__shared_ptr_emplace<DB::StorageMergeTree, std::allocator<DB::StorageMergeTree>>::__on_zero_shared()
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   std::__tree<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, std::__map_value_compare<std::pair<String, String>, std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>, std::less<std::pair<String, String>>, true>, std::allocator<std::pair<std::pair<String, String> const, std::shared_ptr<DB::IStorage>>>>::destroy(std::__tree_node<std::__value_type<std::pair<String, String>, std::shared_ptr<DB::IStorage>>, void*>*)
   DB::ColumnsSource::~ColumnsSource()
   std::__shared_ptr_emplace<DB::ColumnsSource, std::allocator<DB::ColumnsSource>>::__on_zero_shared()
   std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared()
   DB::QueryPipeline::~QueryPipeline()
   DB::QueryPipeline::reset()
   DB::finalizeQueryPipelineBeforeLogging(DB::QueryPipeline&&, DB::QueryResultCacheUsage, bool)
   DB::BlockIO::onFinish(std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long long, std::ratio<1l, 1000000l>>>)
   DB::TCPHandler::runImpl()
   DB::TCPHandler::run()
   Poco::Net::TCPServerConnection::start()
   Poco::Net::TCPServerDispatcher::run()
   Poco::PooledThread::run()
   Poco::(anonymous namespace)::RunnableHolder::run()
```

Possible causes:  
- Incorrect destruction of MergeTreeDataPartCompact object
- Double deletion of a shared pointer in a multi-index container
- Race condition during data part removal or destruction
- Invalid state in the multi-index container during deletion
- Improper handling of shared_ptr lifetimes in MergeTreeData

The stack trace appeared in the following checks:  
- [Stateless tests (amd_tsan, parallel, 2/2)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=06598f27ab378120683ccf2cc08c0632aca84f0c&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_tsan%2C%20parallel%2C%202%2F2%29&name_1=Stateless%20tests%20%28amd_tsan%2C%20parallel%2C%202%2F2%29)

### PR DESCRIPTION
**Pull request by Algunenano**
## Summary

In CI, test `03915_intersecting_parts_rollback` runs in parallel with tests that query `system.columns` (e.g., `00941_system_columns_race_condition`). The race condition:

1. Test `03915` creates a MergeTree table in an Ordinary database and does `BEGIN TRANSACTION; INSERT`, creating a part with non-prehistoric `creation_tid`
2. A concurrent `system.columns` query captures `shared_ptr<IStorage>` to all tables, including this one
3. Test `03915` does `DETACH TABLE`, then `rm -rf` on part directories as part of its normal intersecting-parts-rollback test procedure
4. The `system.columns` query finishes and releases its `shared_ptr` — now the last reference to the storage
5. Storage destructor fires, `removeIfNeeded` calls `assertHasValidVersionMetadata`, which tries to read `txn_version.txt` from the already-deleted part directory, returns `false`, and `chassert` fires

The fix: in `assertHasValidVersionMetadata`, when the version metadata file is missing, check whether the part directory itself still exists. If the directory is gone, there is nothing to validate — return `true` instead of `false`.

Also adds a regression test that reproduces this race.

CI report: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=99272&sha=8a1f5e87eee68b39005270be969516abd1fcbb48&name_0=PR&name_1=Stateless%20tests%20%28amd_tsan%2C%20parallel%2C%202%2F2%29
https://github.com/ClickHouse/ClickHouse/pull/99272

Closes #99375
Closes #98949

### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

---

> [!NOTE]
> **Low Risk**
> Low risk: changes only a debug-only validation path to tolerate externally deleted part directories, plus adds a race-focused stateless regression test.
> 
> **Overview**
> Prevents `chassert(assertHasValidVersionMetadata())` from aborting when `txn_version.txt` is missing because the entire part directory was removed externally; `assertHasValidVersionMetadata()` now treats a missing version file as valid if the part storage no longer exists.
> 
> Adds a stateless regression test (`04039_assert_valid_version_metadata_race.sh`) that reproduces the `system.columns`/`DETACH` race by deleting a part directory during concurrent metadata queries.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit e0140dd45b61f28e4fcc787e358485a403a23a76. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Version info
- Merged into: `26.3.1.684`

### CODE REVIEW

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 1]
```diff
@@ -2218,7 +2218,14 @@ bool IMergeTreeDataPart::assertHasValidVersionMetadata() const
         read_settings.local_fs_method = LocalFSReadMethod::pread;
         auto buf = getDataPartStorage().readFileIfExists(TXN_VERSION_METADATA_FILE_NAME, read_settings, small_file_size);
         if (!buf)
+        {
+            /// The part directory may have been removed externally (e.g., between
+            /// DETACH and ATTACH in an Ordinary database). If the directory is gone,
+            /// there is nothing to validate.
+            if (!getDataPartStorage().exists())
```
Comment (Ergus) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp]: `return !getDataPartStorage().exists()` isn't clearer?

File: tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+    wait
+
+    # Re-ATTACH so the next iteration's DROP can find the table.
+    $CLICKHOUSE_CLIENT -q "ATTACH TABLE ${db_name}.test_intersect" 2>/dev/null ||:
+done
+
+$CLICKHOUSE_CLIENT --allow_deprecated_database_ordinary=1 -q "DROP DATABASE IF EXISTS ${db_name}"
+
+echo "OK"
```
Comment (Ergus) [inline tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh]: This is printed if the client succeeded or not. Is it intended?

**Review by Ergus — APPROVED** [review]
LGTM

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp (hunk 1 above)
Comment (Algunenano) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp]: Makes sense. Thanks!

File: tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh (hunk 2 above)
Comment (Algunenano) [reply tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh]: It doesn't matter. It was initially part of the script to reproduce it, but I kept it when migrating to a stateless test. I'll remove it

File: tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+
+    # DETACH while `system.columns` is running -- `ColumnsSource` may hold the last ref.
+    $CLICKHOUSE_CLIENT -q "DETACH TABLE ${db_name}.test_intersect"
+
+    # Remove the first part directory from disk (including `txn_version.txt`).
+    # This mimics what `03915_intersecting_parts_rollback` does between DETACH/ATTACH.
+    if [ -n "$data_dir" ]; then
+        for d in "${data_dir}"all_*; do
+            [ -d "$d" ] || continue
+            rm -rf "$d"
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh:69]: Unfortunately, the test breaks the invariant of ReplicatedMergeTree, leading to inconsistency, detected by Stress test: `assertHasValidVersionMetadata`.

Doing `rm` manually is an illegal operation in tests. I will remove. The fix is good on its own.

Comment (Ergus) [reply tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh:69]: > Doing `rm` manually is an illegal operation in tests. I will remove. The fix is good on its own.


Hi @alexey-milovidov 

In this case then, is there some "legal" way to test changes like this? Should we consider to implement one in the future?

Comment (Algunenano) [reply tests/queries/0_stateless/04039_assert_valid_version_metadata_race.sh:69]: https://github.com/ClickHouse/ClickHouse/pull/96635/changes#diff-91d320b6849c952565b91edd17c464380157b42e09d8a41613a2a81a5cc29122R64 is the `rm` that started everything.

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 4]
```diff
@@ -2218,13 +2218,26 @@ bool IMergeTreeDataPart::assertHasValidVersionMetadata() const
...
 
         readStringUntilEOF(content, *buf);
         ReadBufferFromString str_buf{content};
         VersionMetadata file;
         file.read(str_buf);
         bool valid_creation_tid = version.creation_tid == file.creation_tid;
+
+        /// If the creation TID on disk doesn't match in-memory state, the file
+        /// belongs to a different incarnation of the part (e.g., an Ordinary database
+        /// reusing the same data directory path after DROP + CREATE). There is nothing
```
Comment (tavplubix) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:2236]: I think this situation is not okay, and we should not handle it. Btw, how exactly does this happen? Looks like it should throw an exception if the data dir is not empty on table creation: https://github.com/ClickHouse/ClickHouse/blob/121eec58a8be136698a45e28226ffc8ece0189d4/src/Storages/StorageMergeTree.cpp#L202-L207

File: src/Storages/MergeTree/IMergeTreeDataPart.cpp [hunk 5]
```diff
@@ -2218,13 +2218,26 @@ bool IMergeTreeDataPart::assertHasValidVersionMetadata() const
         read_settings.local_fs_method = LocalFSReadMethod::pread;
         auto buf = getDataPartStorage().readFileIfExists(TXN_VERSION_METADATA_FILE_NAME, read_settings, small_file_size);
         if (!buf)
-            return false;
+        {
+            /// The part directory may have been removed externally (e.g., between
+            /// DETACH and ATTACH in an Ordinary database). If the directory is gone,
```
Comment (tavplubix) [inline src/Storages/MergeTree/IMergeTreeDataPart.cpp:2223]: How did we get this `IMergeTreeDataPart` instance at all if the part dir was removed between DETACH and ATTACH? We would not load this data part on ATTACH if it was removed

Comment (Algunenano) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:2223]: The part instance isn't from the ATTACH after rm -rf. It's from a previous ATTACH, held alive by system.columns's StoragePtrs. The sequence is:
* ATTACH (loads part)
* system.columns captures references in ColumnsSource.
* DETACH
* rm -rf
* system.columns releases the reference
* The destructor fires on the part whose directory is gone.

Comment (tavplubix) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:2223]: Yes, I understand the problem, but I don't understand the comment:

> The part directory may have been removed externally (e.g., between DETACH and ATTACH in an Ordinary database)

But in this case we would not load the removed data part. Also, it's not possible to detach and re-attach a table while some query is still using it

Comment (Algunenano) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:2223]: Yes, the comment is wrong, because it was based in what the test was doing, but not what was triggering the assert (the destructor is delayed and being called at the end of the system.columns query).

I can adjust the comment, or since we've removed the tests deleting data (thinking it was ok doing so after detach returned) we can revert the change altogether (the test was already removed). WDYT?

Comment (tavplubix) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:2223]: I think it's better to keep the check stricter given that the root cause is addressed by removing the inconsistent test. We also have some other asserts/logical errors that can be triggered by manual intervention into keeper or data on disk

Comment (Algunenano) [reply src/Storages/MergeTree/IMergeTreeDataPart.cpp:2223]: Perfect. I'll remove it then. Thanks for having a look!
