### PR TITLE
Make the code of geodist less wrong.

### LINKED ISSUE #8080: Behaviour of greatCircleDistance function has been changed
**Describe the bug or unexpected behaviour**
The behaviour of `greatCircleDistance` function in current release differs from current master. Previous this function returned length of an arc on the surface of sphere with radius 6372797.560856 meters, but after commit ae2f5ad7d253243130c5f93557021a5fd4b0f91 the output of this function has been changed. It looks like now this function returns the distance between point of an ellipsoid, the constants in the code points to [WGS 84 system](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84), but I'm not sure. The new behaviour doesn't allow us to name this function after great circle because the surface is not sphere any more.

**Example**

This example compares distances near the equator and the North pole.

**Release 19.17.5**
```sql
SELECT greatCircleDistance(0., 0., 0., 1.) / greatCircleDistance(0., 89., 0., 90.) AS x
```
```text
┌──────────────────x─┐
│ 0.9999999999999986 │
└────────────────────┘
```

**Master**
```sql
SELECT greatCircleDistance(0., 0., 0., 1.) / greatCircleDistance(0., 89., 0., 90.) AS x
```
```text
┌──────────────────x─┐
│ 0.9898663431043628 │
└────────────────────┘
```

**Conclusion**
I propose to keep old `greatCircleDistance` function and introduce some new function for ellipsoid distances.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Performance Improvement

Changelog entry (up to few sentences, required except for Non-significant/Documentation categories):
Added a function `geoDistance`. It is similar to `greatCircleDistance` but uses approximation to WGS-84 ellipsoid model. The performance of both functions are near the same.

Detailed description:
This fixes #8080. The code in #7307 was incomplete. Must be backported to release 19.18.

### CODE REVIEW

File: dbms/src/Functions/greatCircleDistance.cpp [hunk 1]
```diff
@@ -7,77 +7,87 @@
 #include <Functions/FunctionHelpers.h>
 #include <Functions/FunctionFactory.h>
 #include <ext/range.h>
-#include <cmath>
+#include <math.h>
```
Comment (stavrolia) [inline dbms/src/Functions/greatCircleDistance.cpp]: Why we want to use C library instead of C++?

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: My KDevelop IDE failed to highlight float versions of math functions and I changed the header to math.h (but probably this change is irrelevant).

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: Yes, it's irrelevant.

File: dbms/src/Functions/greatCircleDistance.cpp [hunk 2]
```diff
@@ -7,77 +7,87 @@
...
-float g_GeoAsin[GEODIST_TABLE_ASIN + 1];    /// asin(sqrt(x)) table
-float g_GeoFlatK[GEODIST_TABLE_K + 1][2];    /// geodistAdaptive() flat ellipsoid method k1, k2 coeffs table
 
 inline double sqr(double v)
 {
     return v * v;
 }
 
-inline float fsqr(float v)
+inline float sqrf(float v)
```
Comment (stavrolia) [inline dbms/src/Functions/greatCircleDistance.cpp]: Do we have a rule for such naming or is it for better consistency with names from standard library for math functions?

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: Yes, it is for consistency with C math library.

File: dbms/src/Functions/greatCircleDistance.cpp [hunk 3]
```diff
@@ -14,70 +14,80 @@
...
+constexpr float EARTH_DIAMETER = 2 * 6371000;
+
+float cos_lut[COS_LUT_SIZE + 1];       /// cos(x) table
+float asin_sqrt_lut[ASIN_SQRT_LUT_SIZE + 1]; /// asin(sqrt(x)) * earth_diameter table
 
-constexpr size_t GEODIST_TABLE_COS = 1024; // maxerr 0.00063%
-constexpr size_t GEODIST_TABLE_ASIN = 512;
-constexpr size_t GEODIST_TABLE_K = 1024;
+float sphere_metric_lut[METRIC_LUT_SIZE + 1];    /// sphere metric: the distance for one degree across longitude depending on latitude
+float wgs84_metric_lut[2 * (METRIC_LUT_SIZE + 1)];  /// ellipsoid metric: the distance across one degree latitude/longitude depending on latitude
```
Comment (stavrolia) [inline dbms/src/Functions/greatCircleDistance.cpp]: If I understand correctly compiler would work with two-dimensional like with one-dimensional, so we can have an impact on performance only by access order (by choice what are rows and what are columns). But two-dimensional array looks simplier to read.

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: Two dimensional array will be placed in one contiguous place in memory.
But access to that array will be represented as double pointer redirection.

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: Actually you are right, it will be the same :)
https://godbolt.org/z/fwuQ8d

File: dbms/src/Functions/greatCircleDistance.cpp [hunk 4]
```diff
@@ -14,70 +14,80 @@
...
-constexpr float TO_RADF2 = static_cast<float>(PI / 360.0);
+constexpr float RAD_IN_DEG = static_cast<float>(PI / 180.0);
+constexpr float RAD_IN_DEG_HALF = static_cast<float>(PI / 360.0);
+
+constexpr size_t COS_LUT_SIZE = 1024; // maxerr 0.00063%
+constexpr size_t ASIN_SQRT_LUT_SIZE = 512;
+constexpr size_t METRIC_LUT_SIZE = 1024;
+
+/// Earth mean diameter in meters, https://en.wikipedia.org/wiki/Earth
+constexpr float EARTH_DIAMETER = 2 * 6371000;
```
Comment (hombit) [inline dbms/src/Functions/greatCircleDistance.cpp]: Please, can you keep WGS-84 Earth radius from old implementation?
https://github.com/ClickHouse/ClickHouse/blob/v19.17.5.18-stable/dbms/src/Functions/greatCircleDistance.cpp#L14

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: I have no idea what was that radius. There was no comments about it. Does it conform to some standard or to astronomical data?

```
Physical characteristics

mean radius  6371.0 km
equatorial     6378.1 km
polar radius  6356.8 km
```

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: I found that it is "quadratic mean earth radius".
I need to spent a few minutes to figure out, what does it mean and by what measure the mean is taken...

Comment (hombit) [reply dbms/src/Functions/greatCircleDistance.cpp]: OK,  was wrong neither current, nor new radius are not correspondent to WGS 84. Probably it is better to use the same WGS 84 authalic radius (the radius of the sphere with the same area as WGS 84 ellipsoid) as H3 is used, because H3 is already a part of ClickHouse.
https://github.com/uber/h3/blob/master/src/h3lib/include/constants.h#L58
 
BTW, it is better to have angular distance function because it doesn't depend on spherical Earth radius definition.

Comment (hombit) [reply dbms/src/Functions/greatCircleDistance.cpp]: See table 3.3 here: 
https://earth-info.nga.mil/GandG/publications/tr8350.2/wgs84fin.pdf

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: I have found it very unclear.
https://github.com/ClickHouse/ClickHouse/pull/8086/commits/1e3b9af66f567f0e6a266fd24bbc5ed403715003

But I can change to the radius from H3 :)

Comment (alexey-milovidov) [reply dbms/src/Functions/greatCircleDistance.cpp]: Yes, we can add one more function. The name `greatCircleAngle` sounds Ok.

**Comment by alexey-milovidov** [comment]
Continued in https://github.com/ClickHouse/ClickHouse/pull/8105

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/5739
