### PR TITLE
Fix inconsistent formatting when subquery or tuple in IN or NOT has alias

### LINKED ISSUE #93576: Logical error: 'Inconsistent AST formatting in SelectQuery: the query: (STID: 1941-1bfa)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: 'Inconsistent AST formatting in SelectQuery: the query: (STID: 1941-1bfa)
CI report: [BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=93512&sha=0613cd5c3ce49801613e055a045fcfc013945a4f&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29)
CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJ0luY29uc2lzdGVudCBBU1QgZm9ybWF0dGluZyBpbiBTZWxlY3RRdWVyeTogdGhlIHF1ZXJ5OiAoU1RJRDogMTk0MS0xYmZhKScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ0J1enpIb3VzZSAoYW1kX2RlYnVnKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgocHVsbF9yZXF1ZXN0X251bWJlciA9IDAgQU5EIGhlYWRfcmVmID0gJ2ZpeC1zdWJjb2x1bW4tb2Ytc3BhcnNlJykgT1IgKHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCBBTkQgYmFzZV9yZWYgPSAnbWFzdGVyJykpCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
Error:
Logical error: 'Inconsistent AST formatting in SelectQuery: the query:
WITH [`t1d0`.`c3.mark`] AS `a2`, cte0d0 AS (SELECT `c0` FROM (SELECT toUInt16((+*)) AS `a5` FROM (SELECT `c0`, `c1` FROM (SELECT 80 AS `a3`, emptyArrayUInt64() FROM `null`(generateRandomStructure(50, 12780225248748482144)) AS t0d2 GLOBAL LEFT ALL JOIN numbers_mt(171774) AS t1d2 ON `t1d2`.`number` = `t0d2`.`c24` PREWHERE (parseDateTime(`t0d2`.`c42`.`Time64(7)`) BETWEEN 38::UInt32 AND -49::Int128) WHERE greater(`t0d2`.`c3`, '0:5:0:9:a:1:1:b'::IPv6) AND not((FALSE BETWEEN 89::Int128 AND `t0d2`.`c37`)) GROUP BY ALL WINDOW w0 AS (PARTITION BY COLUMNS('4')) LIMIT 0.5577)(c0, c1)) AS t0d1 ARRAY JOIN (`t0d1`.`c1`.`1`[].:`LowCardinality(Nullable(Date32))` AS `a4`) GROUP BY CAST(51::Int64 AS Array(LowCardinality(Time))), 1, `a4` LIMIT 1)(c0)), cte1d0 AS (SELECT `c0`, `c1` FROM (SELECT (CASE CAST(-9::Int16 AS LowCardinality(Nullable(Date32))) WHEN 1 THEN 1 ELSE `t0d1`.`c0` END AS `a7`), `t0d1`.`c0` AS `a8` FROM (SELECT `c0` FROM (FROM d2.`t2` AS t0d2 SELECT (SELECT `t0d2`.`_block_number` SETTINGS merge_tree_compact_parts_min_granules_to_multibuffer_read = 67, decimal_check_overflow = 1, distributed_plan_optimize_exchanges = 0, lightweight_delete_mode = 'lightweight_update_force', distributed_plan_force_shuffle_aggregation = 0, optimize_redundant_functions_in_order_by = 0, output_format_pretty_multiline_fields = 0, distributed_cache_alignment = 0, join_output_by_rowlist_perkey_rows_threshold = 952, load_balancing_first_offset = 0, iceberg_metadata_log_level = 'none', compile_expressions = 0, make_distributed_plan = 1, query_plan_aggregation_in_order = 0, max_autoincrement_series = 8388608, parsedatetime_parse_without_leading_zeros = 1, input_format_parquet_max_block_size = 524288, optimize_using_constraints = 1, regexp_dict_allow_hyperscan = 0, use_query_condition_cache = 0, enable_shared_storage_snapshot_in_query = 1, filesystem_cache_segments_batch_size = 50, iceberg_insert_max_partitions = 6922, update_sequential_consistency = 0, query_plan_join_shard_by_pk_ranges = 1, date_time_overflow_behavior = 'throw', max_bytes_before_remerge_sort = 8187864, optimize_on_insert = 1, iceberg_snapshot_id = -1, use_statistics_cache = 1, distributed_cache_discard_connection_if_unread_data = 1, input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference = 0, query_plan_convert_outer_join_to_inner_join = 1, format_display_secrets_in_show_and_select = 1, apply_deleted_mask = 1, query_plan_merge_filter_into_join_condition = 0, input_format_json_infer_incomplete_types_as_strings = 0) AS `a6` PREWHERE `t0d2`.`_disk_name` = NULL WHERE `t0d2`.`_sample_factor`.1 GROUP BY `t0d2`.`_block_offset` WITH TOTALS OFFSET INTERVAL (`t0d2`.`_block_offset`) MINUTE SETTINGS parallel_replicas_min_number_of_rows_per_replica = 1, validate_enum_literals_in_operators = 0, use_legacy_to_time = 1, optimize_arithmetic_operations_in_aggregate_functions = 0, output_format_binary_write_json_as_string = 1, min_insert_block_size_rows = 0, max_insert_threads = 9, validate_enum_literals_in_operators = 0, restore_replicated_merge_tree_to_shared_merge_tree = 0, max_bytes_before_external_sort = 2583883, interval_output_format = 'kusto', split_intersecting_parts_ranges_into_layers_final = 1, input_format_json_try_infer_named_tuples_from_objects = 0, input_format_parquet_bloom_filter_push_down = 0, optimize_qbit_distance_function_reads = 0, max_parser_backtracks = 64, enable_join_runtime_filters = 1, output_format_pretty_max_rows = 0, optimize_min_inequality_conjunction_chain_length = 4, throw_if_deduplication_in_dependent_materialized_views_enabled_with_async_insert = 1, optimize_trivial_approximate_count_query = 0, enable_sharing_sets_for_mutations = 1, iceberg_snapshot_id = -1, enable_job_stack_trace = 1, enable_sharing_sets_for_mutations = 0, fsync_metadata = 1, output_format_arrow_use_signed_indexes_for_dictionary = 0, merge_tree_min_read_task_size = 0, allow_asynchronous_read_from_io_pool_for_merge_tree = 0, s3_slow_all_threads_after_network_error = 1, enable_positional_arguments_for_projections = 1, allow_special_bool_values_inside_variant = 1)(c0)) AS t0d1 CROSS JOIN generateSeries(83::UInt256, 173215, 59::Int8) AS t1d1 LIMIT 26)(c0, c1)) SELECT (-`t1d0`.`c0.mark`), exponentialTimeDecayedMax(toRelativeQuarterNum(`t1d0`.`c2`))('2031-07-01 22:58:41.121100443'::DateTime64, `t1d0`.`c0.mark`), `t1d0`.`c1.size`, `t1d0`.* FROM `t0` AS t0d0 RIGHT JOIN mergeTreeIndex('d2', 't2', with_marks = false, with_minmax = true) AS t1d0 ON equals(`t1d0`.`rows_in_granule`, `t0d0`.`c0`) AND `t1d0`.`part_name` = `t0d0`.`c0`.^`😆`.^`😉😉` LEFT ARRAY JOIN (`t0d0`.`c0` AS `a0`) LEFT ARRAY JOIN (`a0` AS `a1`) WHERE trimLeft(COLUMNS('[6-6]')) GROUP BY GROUPING SETS((`t1d0`.`c1`, 1, ((`t0d0`.`c0`, `t1d0`.`c2.mark`) AS `a9`), `t1d0`.`c0`), (COLUMNS('[2-2]'), `t1d0`.`c1.size`, `t1d0`.`c0.mark`), (`t1d0`.`c0.mark`, `t1d0`.`mark_number`)) HAVING `t1d0`.`c1` QUALIFY (NOT ((`t0d0`.`c0`, `t1d0`.`c2.mark`) AS `a9`) > 'e:b:4:1:6:3:4:c'::IPv6) ORDER BY ALL LIMIT 0 OFFSET `t1d0`.`c1` BY 5 INTO OUTFILE '/var/lib/clickhouse/user_files/file.data' TRUNCATE FORMAT Null;
Formatted as:
WITH [t1d0.`c3.mark`] AS a2, cte0d0 AS (SELECT c0 FROM (SELECT toUInt16(*) AS a5 FROM (SELECT c0, c1 FROM (SELECT 80 AS a3, emptyArrayUInt64() FROM `null`(generateRandomStructure(50, 12780225248748482144)) AS t0d2 GLOBAL ALL LEFT JOIN numbers_mt(171774) AS t1d2 ON t1d2.number = t0d2.c24 PREWHERE (parseDateTime(t0d2.c42.`Time64(7)`) >= CAST('38', 'UInt32')) AND (parseDateTime(t0d2.c42.`Time64(7)`) <= CAST('-49', 'Int128')) WHERE greater(t0d2.c3, CAST('0:5:0:9:a:1:1:b', 'IPv6')) AND (NOT ((false >= CAST('89', 'Int128')) AND (false <= t0d2.c37))) GROUP BY ALL WINDOW w0 AS (PARTITION BY COLUMNS('4')) LIMIT 0.5577) (c0, c1)) AS t0d1 ARRAY JOIN t0d1.c1.`1`.:`Array(JSON)`.:`LowCardinality(Nullable(Date32))` AS a4 GROUP BY CAST(CAST('51', 'Int64'), 'Array(LowCardinality(Time))'), 1, a4 LIMIT 1) (c0)), cte1d0 AS (SELECT c0, c1 FROM (SELECT caseWithExpression(CAST(CAST('-9', 'Int16'), 'LowCardinality(Nullable(Date32))'), 1, 1, t0d1.c0) AS a7, t0d1.c0 AS a8 FROM (SELECT c0 FROM (SELECT (SELECT t0d2._block_number SETTINGS merge_tree_compact_parts_min_granules_to_multibuffer_read = 67, decimal_check_overflow = 1, distributed_plan_optimize_exchanges = 0, lightweight_delete_mode = 'lightweight_update_force', distributed_plan_force_shuffle_aggregation = 0, optimize_redundant_functions_in_order_by = 0, output_format_pretty_multiline_fields = 0, distributed_cache_alignment = 0, join_output_by_rowlist_perkey_rows_threshold = 952, load_balancing_first_offset = 0, iceberg_metadata_log_level = 'none', compile_expressions = 0, make_distributed_plan = 1, query_plan_aggregation_in_order = 0, max_autoincrement_series = 8388608, parsedatetime_parse_without_leading_zeros = 1, input_format_parquet_max_block_size = 524288, optimize_using_constraints = 1, regexp_dict_allow_hyperscan = 0, use_query_condition_cache = 0, enable_shared_storage_snapshot_in_query = 1, filesystem_cache_segments_batch_size = 50, iceberg_insert_max_partitions = 6922, update_sequential_consistency = 0, query_plan_join_shard_by_pk_ranges = 1, date_time_overflow_behavior = 'throw', max_bytes_before_remerge_sort = 8187864, optimize_on_insert = 1, iceberg_snapshot_id = -1, use_statistics_cache = 1, distributed_cache_discard_connection_if_unread_data = 1, input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference = 0, query_plan_convert_outer_join_to_inner_join = 1, format_display_secrets_in_show_and_select = 1, apply_deleted_mask = 1, query_plan_merge_filter_into_join_condition = 0, input_format_json_infer_incomplete_types_as_strings = 0) AS a6 FROM d2.t2 AS t0d2 PREWHERE t0d2._disk_name = NULL WHERE t0d2._sample_factor.1 GROUP BY t0d2._block_offset WITH TOTALS OFFSET toIntervalMinute(t0d2._block_offset) SETTINGS parallel_replicas_min_number_of_rows_per_replica = 1, validate_enum_literals_in_operators = 0, use_legacy_to_time = 1, optimize_arithmetic_operations_in_aggregate_functions = 0, output_format_binary_write_json_as_string = 1, min_insert_block_size_rows = 0, max_insert_threads = 9, validate_enum_literals_in_operators = 0, restore_replicated_merge_tree_to_shared_merge_tree = 0, max_bytes_before_external_sort = 2583883, interval_output_format = 'kusto', split_intersecting_parts_ranges_into_layers_final = 1, input_format_json_try_infer_named_tuples_from_objects = 0, input_format_parquet_bloom_filter_push_down = 0, optimize_qbit_distance_function_reads = 0, max_parser_backtracks = 64, enable_join_runtime_filters = 1, output_format_pretty_max_rows = 0, optimize_min_inequality_conjunction_chain_length = 4, throw_if_deduplication_in_dependent_materialized_views_enabled_with_async_insert = 1, optimize_trivial_approximate_count_query = 0, enable_sharing_sets_for_mutations = 1, iceberg_snapshot_id = -1, enable_job_stack_trace = 1, enable_sharing_sets_for_mutations = 0, fsync_metadata = 1, output_format_arrow_use_signed_indexes_for_dictionary = 0, merge_tree_min_read_task_size = 0, allow_asynchronous_read_from_io_pool_for_merge_tree = 0, s3_slow_all_threads_after_network_error = 1, enable_positional_arguments_for_projections = 1, allow_special_bool_values_inside_variant = 1) (c0)) AS t0d1 CROSS JOIN generateSeries(CAST('83', 'UInt256'), 173215, CAST('59', 'Int8')) AS t1d1 LIMIT 26) (c0, c1)) SELECT -t1d0.`c0.mark`, exponentialTimeDecayedMax(toRelativeQuarterNum(t1d0.c2))(CAST('2031-07-01 22:58:41.121100443', 'DateTime64'), t1d0.`c0.mark`), t1d0.`c1.size`, t1d0.* FROM t0 AS t0d0 RIGHT JOIN mergeTreeIndex('d2', 't2', with_marks = false, with_minmax = true) AS t1d0 ON equals(t1d0.rows_in_granule, t0d0.c0) AND (t1d0.part_name = t0d0.c0.^`😆`.^`😉😉`) LEFT ARRAY JOIN t0d0.c0 AS a0 LEFT ARRAY JOIN a0 AS a1 WHERE trimLeft(COLUMNS('[6-6]')) GROUP BY GROUPING SETS ((t1d0.c1, 1, (t0d0.c0, t1d0.`c2.mark`) AS a9, t1d0.c0), (COLUMNS('[2-2]'), t1d0.`c1.size`, t1d0.`c0.mark`), (t1d0.`c0.mark`, t1d0.mark_number)) HAVING t1d0.c1 QUALIFY NOT (a9) > CAST('e:b:4:1:6:3:4:c', 'IPv6') ORDER BY ALL ASC LIMIT t1d0.c1, 0 BY 5 INTO OUTFILE '/var/lib/clickhouse/user_files/file.data' TRUNCATE FORMAT `Null`
Was parsed and formatted back as:
WITH [t1d0.`c3.mark`] AS a2, cte0d0 AS (SELECT c0 FROM (SELECT toUInt16(*) AS a5 FROM (SELECT c0, c1 FROM (SELECT 80 AS a3, emptyArrayUInt64() FROM `null`(generateRandomStructure(50, 12780225248748482144)) AS t0d2 GLOBAL ALL LEFT JOIN numbers_mt(171774) AS t1d2 ON t1d2.number = t0d2.c24 PREWHERE (parseDateTime(t0d2.c42.`Time64(7)`) >= CAST('38', 'UInt32')) AND (parseDateTime(t0d2.c42.`Time64(7)`) <= CAST('-49', 'Int128')) WHERE greater(t0d2.c3, CAST('0:5:0:9:a:1:1:b', 'IPv6')) AND (NOT ((false >= CAST('89', 'Int128')) AND (false <= t0d2.c37))) GROUP BY ALL WINDOW w0 AS (PARTITION BY COLUMNS('4')) LIMIT 0.5577) (c0, c1)) AS t0d1 ARRAY JOIN t0d1.c1.`1`.:`Array(JSON)`.:`LowCardinality(Nullable(Date32))` AS a4 GROUP BY CAST(CAST('51', 'Int64'), 'Array(LowCardinality(Time))'), 1, a4 LIMIT 1) (c0)), cte1d0 AS (SELECT c0, c1 FROM (SELECT caseWithExpression(CAST(CAST('-9', 'Int16'), 'LowCardinality(Nullable(Date32))'), 1, 1, t0d1.c0) AS a7, t0d1.c0 AS a8 FROM (SELECT c0 FROM (SELECT (SELECT t0d2._block_number SETTINGS merge_tree_compact_parts_min_granules_to_multibuffer_read = 67, decimal_check_overflow = 1, distributed_plan_optimize_exchanges = 0, lightweight_delete_mode = 'lightweight_update_force', distributed_plan_force_shuffle_aggregation = 0, optimize_redundant_functions_in_order_by = 0, output_format_pretty_multiline_fields = 0, distributed_cache_alignment = 0, join_output_by_rowlist_perkey_rows_threshold = 952, load_balancing_first_offset = 0, iceberg_metadata_log_level = 'none', compile_expressions = 0, make_distributed_plan = 1, query_plan_aggregation_in_order = 0, max_autoincrement_series = 8388608, parsedatetime_parse_without_leading_zeros = 1, input_format_parquet_max_block_size = 524288, optimize_using_constraints = 1, regexp_dict_allow_hyperscan = 0, use_query_condition_cache = 0, enable_shared_storage_snapshot_in_query = 1, filesystem_cache_segments_batch_size = 50, iceberg_insert_max_partitions = 6922, update_sequential_consistency = 0, query_plan_join_shard_by_pk_ranges = 1, date_time_overflow_behavior = 'throw', max_bytes_before_remerge_sort = 8187864, optimize_on_insert = 1, iceberg_snapshot_id = -1, use_statistics_cache = 1, distributed_cache_discard_connection_if_unread_data = 1, input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference = 0, query_plan_convert_outer_join_to_inner_join = 1, format_display_secrets_in_show_and_select = 1, apply_deleted_mask = 1, query_plan_merge_filter_into_join_condition = 0, input_format_json_infer_incomplete_types_as_strings = 0) AS a6 FROM d2.t2 AS t0d2 PREWHERE t0d2._disk_name = NULL WHERE t0d2._sample_factor.1 GROUP BY t0d2._block_offset WITH TOTALS OFFSET toIntervalMinute(t0d2._block_offset) SETTINGS parallel_replicas_min_number_of_rows_per_replica = 1, validate_enum_literals_in_operators = 0, use_legacy_to_time = 1, optimize_arithmetic_operations_in_aggregate_functions = 0, output_format_binary_write_json_as_string = 1, min_insert_block_size_rows = 0, max_insert_threads = 9, validate_enum_literals_in_operators = 0, restore_replicated_merge_tree_to_shared_merge_tree = 0, max_bytes_before_external_sort = 2583883, interval_output_format = 'kusto', split_intersecting_parts_ranges_into_layers_final = 1, input_format_json_try_infer_named_tuples_from_objects = 0, input_format_parquet_bloom_filter_push_down = 0, optimize_qbit_distance_function_reads = 0, max_parser_backtracks = 64, enable_join_runtime_filters = 1, output_format_pretty_max_rows = 0, optimize_min_inequality_conjunction_chain_length = 4, throw_if_deduplication_in_dependent_materialized_views_enabled_with_async_insert = 1, optimize_trivial_approximate_count_query = 0, enable_sharing_sets_for_mutations = 1, iceberg_snapshot_id = -1, enable_job_stack_trace = 1, enable_sharing_sets_for_mutations = 0, fsync_metadata = 1, output_format_arrow_use_signed_indexes_for_dictionary = 0, merge_tree_min_read_task_size = 0, allow_asynchronous_read_from_io_pool_for_merge_tree = 0, s3_slow_all_threads_after_network_error = 1, enable_positional_arguments_for_projections = 1, allow_special_bool_values_inside_variant = 1) (c0)) AS t0d1 CROSS JOIN generateSeries(CAST('83', 'UInt256'), 173215, CAST('59', 'Int8')) AS t1d1 LIMIT 26) (c0, c1)) SELECT -t1d0.`c0.mark`, exponentialTimeDecayedMax(toRelativeQuarterNum(t1d0.c2))(CAST('2031-07-01 22:58:41.121100443', 'DateTime64'), t1d0.`c0.mark`), t1d0.`c1.size`, t1d0.* FROM t0 AS t0d0 RIGHT JOIN mergeTreeIndex('d2', 't2', with_marks = false, with_minmax = true) AS t1d0 ON equals(t1d0.rows_in_granule, t0d0.c0) AND (t1d0.part_name = t0d0.c0.^`😆`.^`😉😉`) LEFT ARRAY JOIN t0d0.c0 AS a0 LEFT ARRAY JOIN a0 AS a1 WHERE trimLeft(COLUMNS('[6-6]')) GROUP BY GROUPING SETS ((t1d0.c1, 1, (t0d0.c0, t1d0.`c2.mark`) AS a9, t1d0.c0), (COLUMNS('[2-2]'), t1d0.`c1.size`, t1d0.`c0.mark`), (t1d0.`c0.mark`, t1d0.mark_number)) HAVING t1d0.c1 QUALIFY (NOT a9) > CAST('e:b:4:1:6:3:4:c', 'IPv6') ORDER BY ALL ASC LIMIT t1d0.c1, 0 BY 5 INTO OUTFILE '/var/lib/clickhouse/user_files/file.data' TRUNCATE FORMAT `Null`'.
---

Failed query:
WITH [t1d0.`c3.mark`] AS a2, cte0d0 AS (SELECT c0 FROM (SELECT toUInt16(*) AS a5 FROM (SELECT c0, c1 FROM (SELECT 80 AS a3, emptyArrayUInt64() FROM `null`(generateRandomStructure(50, 12780225248748482144)) AS t0d2 GLOBAL ALL LEFT JOIN numbers_mt(171774) AS t1d2 ON t1d2.number = t0d2.c24 PREWHERE (parseDateTime(t0d2.c42.`Time64(7)`) >= CAST('38', 'UInt32')) AND (parseDateTime(t0d2.c42.`Time64(7)`) <= CAST('-49', 'Int128')) WHERE greater(t0d2.c3, CAST('0:5:0:9:a:1:1:b', 'IPv6')) AND (NOT ((false >= CAST('89', 'Int128')) AND (false <= t0d2.c37))) GROUP BY ALL WINDOW w0 AS (PARTITION BY COLUMNS('4')) LIMIT 0.5577) (c0, c1)) AS t0d1 ARRAY JOIN t0d1.c1.`1`.:`Array(JSON)`.:`LowCardinality(Nullable(Date32))` AS a4 GROUP BY CAST(CAST('51', 'Int64'), 'Array(LowCardinality(Time))'), 1, a4 LIMIT 1) (c0)), cte1d0 AS (SELECT c0, c1 FROM (SELECT caseWithExpression(CAST(CAST('-9', 'Int16'), 'LowCardinality(Nullable(Date32))'), 1, 1, t0d1.c0) AS a7, t0d1.c0 AS a8 FROM (SELECT c0 FROM (SELECT (SELECT t0d2._block_number SETTINGS merge_tree_compact_parts_min_granules_to_multibuffer_read = 67, decimal_check_overflow = 1, distributed_plan_optimize_exchanges = 0, lightweight_delete_mode = 'lightweight_update_force', distributed_plan_force_shuffle_aggregation = 0, optimize_redundant_functions_in_order_by = 0, output_format_pretty_multiline_fields = 0, distributed_cache_alignment = 0, join_output_by_rowlist_perkey_rows_threshold = 952, load_balancing_first_offset = 0, iceberg_metadata_log_level = 'none', compile_expressions = 0, make_distributed_plan = 1, query_plan_aggregation_in_order = 0, max_autoincrement_series = 8388608, parsedatetime_parse_without_leading_zeros = 1, input_format_parquet_max_block_size = 524288, optimize_using_constraints = 1, regexp_dict_allow_hyperscan = 0, use_query_condition_cache = 0, enable_shared_storage_snapshot_in_query = 1, filesystem_cache_segments_batch_size = 50, iceberg_insert_max_partitions = 6922, update_sequential_consistency = 0, query_plan_join_shard_by_pk_ranges = 1, date_time_overflow_behavior = 'throw', max_bytes_before_remerge_sort = 8187864, optimize_on_insert = 1, iceberg_snapshot_id = -1, use_statistics_cache = 1, distributed_cache_discard_connection_if_unread_data = 1, input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference = 0, query_plan_convert_outer_join_to_inner_join = 1, format_display_secrets_in_show_and_select = 1, apply_deleted_mask = 1, query_plan_merge_filter_into_join_condition = 0, input_format_json_infer_incomplete_types_as_strings = 0) AS a6 FROM d2.t2 AS t0d2 PREWHERE t0d2._disk_name = NULL WHERE t0d2._sample_factor.1 GROUP BY t0d2._block_offset WITH TOTALS OFFSET toIntervalMinute(t0d2._block_offset) SETTINGS parallel_replicas_min_number_of_rows_per_replica = 1, validate_enum_literals_in_operators = 0, use_legacy_to_time = 1, optimize_arithmetic_operations_in_aggregate_functions = 0, output_format_binary_write_json_as_string = 1, min_insert_block_size_rows = 0, max_insert_threads = 9, validate_enum_literals_in_operators = 0, restore_replicated_merge_tree_to_shared_merge_tree = 0, max_bytes_before_external_sort = 2583883, interval_output_format = 'kusto', split_intersecting_parts_ranges_into_layers_final = 1, input_format_json_try_infer_named_tuples_from_objects = 0, input_format_parquet_bloom_filter_push_down = 0, optimize_qbit_distance_function_reads = 0, max_parser_backtracks = 64, enable_join_runtime_filters = 1, output_format_pretty_max_rows = 0, optimize_min_inequality_conjunction_chain_length = 4, throw_if_deduplication_in_dependent_materialized_views_enabled_with_async_insert = 1, optimize_trivial_approximate_count_query = 0, enable_sharing_sets_for_mutations = 1, iceberg_snapshot_id = -1, enable_job_stack_trace = 1, enable_sharing_sets_for_mutations = 0, fsync_metadata = 1, output_format_arrow_use_signed_indexes_for_dictionary = 0, merge_tree_min_read_task_size = 0, allow_asynchronous_read_from_io_pool_for_merge_tree = 0, s3_slow_all_threads_after_network_error = 1, enable_positional_arguments_for_projections = 1, allow_special_bool_values_inside_variant = 1) (c0)) AS t0d1 CROSS JOIN generateSeries(CAST('83', 'UInt256'), 173215, CAST('59', 'Int8')) AS t1d1 LIMIT 26) (c0, c1)) SELECT -t1d0.`c0.mark`, exponentialTimeDecayedMax(toRelativeQuarterNum(t1d0.c2))(CAST('2031-07-01 22:58:41.121100443', 'DateTime64'), t1d0.`c0.mark`), t1d0.`c1.size`, t1d0.* FROM t0 AS t0d0 RIGHT JOIN mergeTreeIndex('d2', 't2', with_marks = false, with_minmax = true) AS t1d0 ON equals(t1d0.rows_in_granule, t0d0.c0) AND (t1d0.part_name = t0d0.c0.^`😆`.^`😉😉`) LEFT ARRAY JOIN t0d0.c0 AS a0 LEFT ARRAY JOIN a0 AS a1 WHERE trimLeft(COLUMNS('[6-6]')) GROUP BY GROUPING SETS ((t1d0.c1, 1, (t0d0.c0, t1d0.`c2.mark`) AS a9, t1d0.c0), (COLUMNS('[2-2]'), t1d0.`c1.size`, t1d0.`c0.mark`), (t1d0.`c0.mark`, t1d0.mark_number)) HAVING t1d0.c1 QUALIFY NOT (a9) > CAST('e:b:4:1:6:3:4:c', 'IPv6') ORDER BY ALL ASC LIMIT t1d0.c1, 0 BY 5
---

Stack trace:
pthread_kill @ 0x00000000000969fd
gsignal @ 0x0000000000042476
__lgamma_r_finite@GLIBC_2.15 @ 0x00000000000287f3
src/Common/Exception.cpp:57: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x00000000162cccbc
src/Common/Exception.cpp:90: DB::handle_error_code(String const&, std::basic_string_view<char, std::char_traits<char>>, int, bool, std::vector<void*, std::allocator<void*>> const&) @ 0x00000000162ce0cd
src/Common/Exception.cpp:143: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000162ce3b9
src/Common/Exception.h:172: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d89fed4
src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d89f9d1
src/Common/Exception.h:190: DB::Exception::Exception<String, std::basic_string_view<char, std::char_traits<char>>&, String&, String&>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type, std::type_identity<String&>::type, std::type_identity<String&>::type>, String&&, std::basic_string_view<char, std::char_traits<char>>&, String&, String&) @ 0x000000001ca6f3ce
src/Interpreters/executeQuery.cpp:1260: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::function<void ()>, DB::QueryResultDetails&) @ 0x000000001ca5e446
src/Interpreters/executeQuery.cpp:1955: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001ca5bd94
src/Server/TCPHandler.cpp:774: DB::TCPHandler::runImpl() @ 0x00000000202b6609
src/Server/TCPHandler.cpp:2867: DB::TCPHandler::run() @ 0x00000000202d1664
base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000026780c8e
base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000267812fb
base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000267217ff
base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000002671ee8f
start_thread @ 0x0000000000094ac3
clone3 @ 0x00000000001268c0
```

### PR DESCRIPTION
**Pull request by george-larionov**
Fixes #93576.

Queries with subqueries or tuples with aliases in IN or NOT statements would be inconsistently wrapped in parentheses during the format-parse-format debug check.

f.e.
`SELECT ((SELECT [1,2,3]) AS a1), [5] IN ((SELECT [1,2,3]) AS a1)`
Formatted as:
`SELECT (SELECT [1, 2, 3]) AS a1, [5] IN a1`
Was parsed and formatted back as:
`SELECT (SELECT [1, 2, 3]) AS a1, [5] IN (a1)'`

Note the difference: `5 in a1` vs `5 in (a1)`.

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Version info
- Merged into: `26.1.1.472`

### CODE REVIEW

File: tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql [hunk 1]
```diff
@@ -12,3 +14,15 @@ DROP TABLE tab;
 
 SELECT 'Test that large max_query_size doesnt cause overflow:';
 SELECT 'test' SETTINGS max_query_size = 9223372036854775309;
+
+SELECT 'Test repeated alias in subquery after IN:';
+SELECT ((SELECT [1,2,3]) AS a1), [5] IN ((SELECT [1,2,3]) AS a1);
```
Comment (nikitamikhaylov) [inline tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql:19]: You can add the .sh test with `CLICKHOUSE_FORMAT` to verify the output and the way how ClickHouse formats the query.

Comment (george-larionov) [reply tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql:19]: Do you think it is needed? I really only care that it succeeds and does not fail the debug check

Comment (nikitamikhaylov) [reply tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql:19]: Yes, it's needed. The formatting could be entirely wrong

Comment (george-larionov) [reply tests/queries/0_stateless/03780_AST_formatting_inconsistencies_in_debug_check.sql:19]: @nikitamikhaylov done. Let me know if it is what you had in mind.

**Review by nikitamikhaylov — APPROVED** [review]
