### PR TITLE
Fix Set index with constant nullable comparison.

### LINKED ISSUE #49569: Creating Index changes the query result, all rows are skipped
Clickhouse v22.8.17.17+

I expect to get 1 row, but I get an empty result

[https://fiddle.clickhouse.com/75841829-0825-4e49-878c-4e0ceba63bb0](https://fiddle.clickhouse.com/75841829-0825-4e49-878c-4e0ceba63bb0)

```
CREATE OR REPLACE TABLE test_table
(
    col1 String,
    col2 String,
    INDEX test_table_col2_idx col2 TYPE set(0) GRANULARITY 1
) ENGINE = MergeTree()
      ORDER BY col1
AS SELECT 'v1', 'v2';

-- empty result
SELECT * FROM test_table
WHERE 1 == 1 AND col1 == col1 OR
       0 AND col2 == NULL;

ALTER TABLE test_table DROP INDEX test_table_col2_idx;

-- 1 row in result
SELECT *
FROM test_table
WHERE (1 == 1 AND col1 = 'v1' OR
       0 AND col2 == NULL);
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible empty result for a query with `Set` index and `WHERE` condition containing `NULL`. Fixes #49569

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
This is an automated comment for commit 5bda0b535d9b161acf17980ebddd252e1dd4f587 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51205/5bda0b535d9b161acf17980ebddd252e1dd4f587/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Storages/MergeTree/MergeTreeIndexSet.cpp [hunk 1]
```diff
@@ -1,3 +1,4 @@
+#include "Parsers/queryToString.h"
```
Comment (nikitamikhaylov) [inline src/Storages/MergeTree/MergeTreeIndexSet.cpp:1]:
```suggestion
#include <Parsers/queryToString.h>
```

File: src/Storages/MergeTree/MergeTreeIndexSet.cpp [hunk 2]
```diff
@@ -554,7 +554,7 @@ void MergeTreeIndexConditionSet::traverseAST(ASTPtr & node) const
     if (atomFromAST(node))
     {
         if (node->as<ASTIdentifier>() || node->as<ASTFunction>())
-            node = makeASTFunction("__bitWrapperFunc", node);
+            node = makeASTFunction("__bitWrapperFunc", makeASTFunction("toUInt8OrDefault", node));
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeIndexSet.cpp:557]: Missing comment.

I don't understand this code.
1. Why did it work before? The bitWrapperFunc should throw an exception for incorrect types.
2. How should it work for String fields? Is returning 0 as default correct?

Comment (KochetovNicolai) [reply src/Storages/MergeTree/MergeTreeIndexSet.cpp:557]: This is an attempt to mute the default implementation for Null. Maybe using `ifNull` is better, but it has 2 args.
Will make it more explicit.
