### PR TITLE
Write structure of table functions to metadata

### LINKED ISSUE #9249: CREATE as remote(...) may lead to server startup failure
**How to reproduce**
```
create database z;
create table z.tmp (n Int8) engine=Memory;
create table default.remote as remote('localhost', 'z', 'tmp');
```
and restart clickhouse-server

**Error message and/or stacktrace**
```
2020.02.20 15:29:48.875097 [ 1 ] {} <Error> Application: DB::Exception: Cannot attach table 'remote' from query ATTACH TABLE remote AS remote('localhost', 'z', 'tmp'). Error: Code: 81, e.displayText() = DB::Exception: Database z doesn't exist, Stack trace (when copying this message, always include the lines below):

0. 0x4832817 StackTrace::StackTrace() /home/avtokmakov/ch/ClickHouse/build/../dbms/src/Common/StackTrace.cpp:228
1. 0x8196321 DB::Context::getTableImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Exception*) const /home/avtokmakov/ch/ClickHouse/build/../dbms/src/Common/Exception.h:0
2. 0x8195ef0 DB::Context::getTable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/memory:3939
3. 0x85fe35a DB::getStructureOfRemoteTable(DB::Cluster const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context const&, std::__1::shared_ptr<DB::IAST> const&) /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/memory:3933
4. 0x7fb67ee DB::TableFunctionRemote::executeImpl(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/memory:3939
5. 0x8883153 DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const /home/avtokmakov/ch/ClickHouse/build/../dbms/src/TableFunctions/ITableFunction.cpp:16
6. 0x89aca45 DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool) /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/memory:4520
7. 0x89b5c2b std::__1::__function::__func<DB::DatabaseOrdinary::loadStoredObjects(DB::Context&, bool)::$_1, std::__1::allocator<DB::DatabaseOrdinary::loadStoredObjects(DB::Context&, bool)::$_1>, void ()>::operator()() /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/string:3073
8. 0x4867296 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/atomic:1036
9. 0x48691f8 std::__1::__function::__func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&)::'lambda'(), std::__1::allocator<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&)::'lambda'()>, void ()>::operator()() /home/avtokmakov/ch/ClickHouse/build/../dbms/src/Common/ThreadPool.cpp:0
10. 0x4865526 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/atomic:1036
11. 0x4868120 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) /home/avtokmakov/ch/ClickHouse/build/../contrib/libcxx/include/memory:2648
12. 0x7f55a7f106db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
13. 0x7f55a7a3588f clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Additional context**
Table function `remote(...)` creates `Distributed` storage, which requires columns description. If it cannot get columns description for some reason (table is not loaded yet, or remote server is unavailable now) server fails to start.

It cannot be fixed in the way like #8824. Probably we need rewrite CREATE query to add columns description even for table functions

### LINKED ISSUE #14214: Issues related to Distributed format of StorageFile
Unexpected behaviour (table structure is overriden):
```
:) create table d (n UInt64) engine=Distributed('test_shard_localhost2', 'system', 'numbers')
Ok.

:) insert into d values (1)
Ok.

:) create table f (s String) engine=File('Distributed', '/var/lib/clickhouse/data/default/d/default@127%2E0%2E0%2E2:9000/1.bin')
Ok.

:) desc table f
┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ n    │ UInt64 │              │                    │         │                  │                │
└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

:) show create table f
┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.f
(
    `s` String
)
ENGINE = File('Distributed', '/var/lib/clickhouse/data/default/d/default@127%2E0%2E0%2E2:9000/1.bin') │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


config.xml:

<user_files_path>/var/lib/clickhouse/</user_files_path>

<test_shard_localhost2>
            <shard>
                <replica>
                    <host>127.0.0.2</host>
                    <port>9000</port>
                </replica>
            </shard>
</test_shard_localhost2>

```

Logical error caused by empty paths list and empty columns list:
```
:) select count() from file('kek*', 'Distributed', 'col UInt8')

2020.08.28 14:00:04.329971 [ 4338 ] {376d0a69-5a21-4fbf-ad0d-c72786c27531} <Error> : Logical error: 'No available columns'.
clickhouse: ../src/Common/Exception.cpp:45: DB::Exception::Exception(const std::string &, int): Assertion `false' failed.
2020.08.28 14:00:04.330861 [ 4213 ] {} <Trace> BaseDaemon: Received signal 6
2020.08.28 14:00:04.331467 [ 4727 ] {} <Fatal> BaseDaemon: ########################################
2020.08.28 14:00:04.332164 [ 4727 ] {} <Fatal> BaseDaemon: (version 20.8.1.1, build id: 7BF608A90FDC580802F2787C9686E2BF9B8B8690) (from thread 4338) (query_id: 376d0a69-5a21-4fbf-ad0d-c72786c27531) Received signal Aborted (6)
2020.08.28 14:00:04.332568 [ 4727 ] {} <Fatal> BaseDaemon: 
2020.08.28 14:00:04.332913 [ 4727 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f38997f7f47 0x7f38997f98b1 0x7f38997e942a 0x7f38997e94a2 0x1a3e33b1 0x2548c0aa 0x24623447 0x246247e6 0x244a72b4 0x244a5843 0x244a472c 0x24520f91 0x2451fc8d 0x2446c235 0x2446b2bf 0x246473a5 0x246465ca 0x24d27e56 0x24d2f2e8 0x2912d2dc 0x2912daec 0x29261953 0x2925e87d 0x2925d708 0x7f3899fbd6db 0x7f38998daa3f
2020.08.28 14:00:04.333414 [ 4727 ] {} <Fatal> BaseDaemon: 4. /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51: raise @ 0x3ef47 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.08.28 14:00:04.333835 [ 4727 ] {} <Fatal> BaseDaemon: 5. /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81: abort @ 0x408b1 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.08.28 14:00:04.334219 [ 4727 ] {} <Fatal> BaseDaemon: 6. /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89: __assert_fail_base @ 0x3042a in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.08.28 14:00:04.334766 [ 4727 ] {} <Fatal> BaseDaemon: 7. ? @ 0x304a2 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2020.08.28 14:00:04.335421 [ 4727 ] {} <Fatal> BaseDaemon: 8. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Common/Exception.cpp:48: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a3e33b1 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.393163 [ 4727 ] {} <Fatal> BaseDaemon: 9. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/ExpressionActions.cpp:729: DB::ExpressionActions::getSmallestColumn(DB::NamesAndTypesList const&) @ 0x2548c0aa in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.441110 [ 4727 ] {} <Fatal> BaseDaemon: 10. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/TreeRewriter.cpp:479: DB::TreeRewriterResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, bool) @ 0x24623447 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.488405 [ 4727 ] {} <Fatal> BaseDaemon: 11. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/TreeRewriter.cpp:619: DB::TreeRewriter::analyzeSelect(std::__1::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::__1::vector<DB::TableWithColumnNamesAndTypes, std::__1::allocator<DB::TableWithColumnNamesAndTypes> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::TableJoin>) const @ 0x246247e6 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.536264 [ 4727 ] {} <Fatal> BaseDaemon: 12. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/InterpreterSelectQuery.cpp:315: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&)::$_2::operator()(bool) const @ 0x244a72b4 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.583845 [ 4727 ] {} <Fatal> BaseDaemon: 13. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/InterpreterSelectQuery.cpp:406: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x244a5843 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.629967 [ 4727 ] {} <Fatal> BaseDaemon: 14. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/InterpreterSelectQuery.cpp:147: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x244a472c in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.676387 [ 4727 ] {} <Fatal> BaseDaemon: 15. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/memory:3028: std::__1::__unique_if<DB::InterpreterSelectQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectQuery, std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&>(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x24520f91 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.723045 [ 4727 ] {} <Fatal> BaseDaemon: 16. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/InterpreterSelectWithUnionQuery.cpp:84: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x2451fc8d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.769170 [ 4727 ] {} <Fatal> BaseDaemon: 17. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/libcxx/include/memory:3028: std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions>(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&&) @ 0x2446c235 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.815706 [ 4727 ] {} <Fatal> BaseDaemon: 18. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/InterpreterFactory.cpp:107: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0x2446b2bf in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.863750 [ 4727 ] {} <Fatal> BaseDaemon: 19. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/executeQuery.cpp:369: DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x246473a5 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.911585 [ 4727 ] {} <Fatal> BaseDaemon: 20. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Interpreters/executeQuery.cpp:675: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x246465ca in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:04.963866 [ 4727 ] {} <Fatal> BaseDaemon: 21. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Server/TCPHandler.cpp:253: DB::TCPHandler::runImpl() @ 0x24d27e56 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.016646 [ 4727 ] {} <Fatal> BaseDaemon: 22. /home/avtokmakov/ch/ClickHouse/build_debug/../src/Server/TCPHandler.cpp:1213: DB::TCPHandler::run() @ 0x24d2f2e8 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.083860 [ 4727 ] {} <Fatal> BaseDaemon: 23. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x2912d2dc in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.150960 [ 4727 ] {} <Fatal> BaseDaemon: 24. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Net/src/TCPServerDispatcher.cpp:114: Poco::Net::TCPServerDispatcher::run() @ 0x2912daec in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.217901 [ 4727 ] {} <Fatal> BaseDaemon: 25. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/ThreadPool.cpp:199: Poco::PooledThread::run() @ 0x29261953 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.284639 [ 4727 ] {} <Fatal> BaseDaemon: 26. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x2925e87d in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.352017 [ 4727 ] {} <Fatal> BaseDaemon: 27. /home/avtokmakov/ch/ClickHouse/build_debug/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345: Poco::ThreadImpl::runnableEntry(void*) @ 0x2925d708 in /home/avtokmakov/ch/ClickHouse/build_debug/programs/clickhouse
2020.08.28 14:00:05.352684 [ 4727 ] {} <Fatal> BaseDaemon: 28. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
2020.08.28 14:00:05.353163 [ 4727 ] {} <Fatal> BaseDaemon: 29. /build/glibc-2ORdQG/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __clone @ 0x121a3f in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
```

Probably there are some more issues.

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow explicitly specify columns list in `CREATE TABLE table AS table_function(...)` query.
Fixes #9249
Fixes #14214

### CODE REVIEW

File: src/Storages/StorageProxy.h [hunk 1]
```diff
@@ -0,0 +1,158 @@
+#pragma once
+
+#include <Storages/IStorage.h>
+#include <Processors/Pipe.h>
+
+
+namespace DB
+{
+
+class StorageProxy : public IStorage
```
Comment (alexey-milovidov) [inline src/Storages/StorageProxy.h:10]: Missing comments.
