### PR TITLE
Fixed `quantile(s)TDigest` inaccuracies

### LINKED ISSUE #22408: quantileTDigest inaccuracy with extreme quanties.
**Use case**
Clickhouse version 21.4
```
SELECT
    quantileTiming(0.95)(key) AS timing,
    quantileExact(0.95)(key) AS exact,
    quantileTDigest(0.95)(key) AS tdigest
FROM
(
    SELECT
        9000 AS key,
        2 AS count
    UNION ALL
    SELECT
        3000,
        11
    UNION ALL
    SELECT
        1000,
        26
)
ARRAY JOIN range(count) AS s

Query id: addce63f-0b75-46e2-b896-712d66711fb0

┌─timing─┬─exact─┬──tdigest─┐
│   9000 │  9000 │ 8123.076 │
└────────┴───────┴──────────┘


SELECT
    quantileTiming(0.9)(key) AS timing,
    quantileExact(0.9)(key) AS exact,
    quantileTDigest(0.9)(key) AS tdigest
FROM
(
    SELECT key
    FROM
    (
        SELECT
            9000 AS key,
            2 AS count
        UNION ALL
        SELECT
            3000,
            11
        UNION ALL
        SELECT
            1000,
            26
    )
    ARRAY JOIN range(count) AS s
    ORDER BY key ASC
)

Query id: e92e3d07-3b97-4155-aa10-9a15544d9312

┌─timing─┬─exact─┬───tdigest─┐
│   3000 │  3000 │ 6323.0757 │
└────────┴───────┴───────────┘

```

Probably related: https://github.com/tdunning/t-digest/issues/154

### PR DESCRIPTION
**Pull request by excitoon**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement.

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Fixed `quantile(s)TDigest`. Added special handling of singleton centroids according to tdunning/t-digest 3.2+. Also a bug with over-compression of centroids in implementation of earlier version of the algorithm was fixed.

Resolves #22408.

### CODE REVIEW

**Comment by excitoon** [comment]
```
programs/clickhouse local -q 'SELECT quantileArray(0.9)([9000, 9000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000] AS a) AS q90, quantileArray(0.95)(a) AS q95, quantileExactArray(0.9)(a) AS qe90, quantilesExactArray(0.9, 0.95)(a) AS exact, quantilesTimingArray(0.9, 0.95)(a) AS timing, quantilesTDigestArray(0.9, 0.95)(a) AS tdigest FORMAT Pretty'
┏━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃  q90 ┃                q95 ┃ qe90 ┃ exact       ┃ timing      ┃ tdigest     ┃
┡━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ 3000 │ 3600.0000000000086 │ 3000 │ [3000,9000] │ [3000,9000] │ [3000,9000] │
└──────┴────────────────────┴──────┴─────────────┴─────────────┴─────────────┘
```

File: src/AggregateFunctions/QuantileTDigest.h [hunk 1]
```diff
@@ -320,16 +311,29 @@ class QuantileTDigest
...
 
         for (const auto & c : centroids)
         {
             Float64 current_x = sum + c.count * 0.5;
 
             if (current_x >= x)
-                return interpolate(x, prev_x, prev_mean, current_x, c.mean);
+            {
+                /// Special handling of singletons.
+                Float64 left = prev_x + 0.5*(prev_count == 1);
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/QuantileTDigest.h:323]: Style.

File: src/AggregateFunctions/QuantileTDigest.h [hunk 2]
```diff
@@ -364,25 +368,40 @@ class QuantileTDigest
...
         for (const auto & c : centroids)
         {
             Float64 current_x = sum + c.count * 0.5;
 
-            while (current_x >= x)
+            if (current_x >= x)
             {
-                result[levels_permutation[result_num]] = interpolate(x, prev_x, prev_mean, current_x, c.mean);
+                /// Special handling of singletons.
+                Float64 left = prev_x + 0.5*(prev_count == 1);
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/QuantileTDigest.h:381]: Style.

File: src/AggregateFunctions/QuantileTDigest.h [hunk 3]
```diff
@@ -195,15 +195,6 @@ class QuantileTDigest
             BetterFloat l_count = l->count;
             while (r != centroids.end())
             {
-                if (l->mean == r->mean) // Perfect aggregation (fast). We compare l->mean, not l_mean, to avoid identical elements after compress
```
Comment (alexey-milovidov) [inline src/AggregateFunctions/QuantileTDigest.h:198]: Need to clarify what exactly has been changed.
It will be better if you will provide illustructive "textbook" examples on this matter directly in comments.

**Comment by excitoon** [comment]
In comments to PR or in the code?

**Comment by alexey-milovidov** [comment]
In code.

File: src/AggregateFunctions/QuantileTDigest.h (hunk 3 above)
Comment (excitoon) [reply src/AggregateFunctions/QuantileTDigest.h:198]: Done.

File: src/AggregateFunctions/QuantileTDigest.h (hunk 2 above)
Comment (excitoon) [reply src/AggregateFunctions/QuantileTDigest.h]: +

File: src/AggregateFunctions/QuantileTDigest.h (hunk 1 above)
Comment (excitoon) [reply src/AggregateFunctions/QuantileTDigest.h]: +

**Comment by excitoon** [comment]
> Need to fix the title of this PR and add a meaningful message for changelog.

@alexey-milovidov Fixed.

**Comment by alexey-milovidov** [comment]
@Mergifyio update

**Comment by excitoon** [comment]
@alexey-milovidov I cannot follow this guide because I have a fork in organization. I can not add @Mergifyio to collaborators because "Could not find a GitHub account matching @Mergifyio ". I will rebase it against master.

**Review by alexey-milovidov — APPROVED** [review]
