### PR TITLE
[Green CI] Fix crash in DistributedAsyncInsert when connection is empty

### LINKED ISSUE #66740: Crash Bug - Segmentation fault - Address: NULL pointer. Access: read. Address not mapped to object.
Crash bug on ClickHouse server version version 24.3.3.102 (official build),  It has been running normally for a month.,  All nodes are down within a short period of time.

```
2024.07.19 10:33:31.702639 [ 28272 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.07.19 10:33:31.702671 [ 28272 ] {} <Fatal> BaseDaemon: (version 24.3.3.102 (official build), build id: EF9E1BD0781C858153E899F2D95A044F4DD82F9B, git hash: 7e7f3bdd9be3ced03925d1d602037db8687e6401) (from thread 28069) Received signal 11
2024.07.19 10:33:31.702693 [ 28272 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.07.19 10:33:31.702701 [ 28272 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2024.07.19 10:33:31.702710 [ 28272 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000011c223c6 0x0000000011c1805c 0x0000000011c2619a 0x000000000fd99d07 0x000000000fd9ae73 0x000000000cc7714d 0x00007f2abd06122a 0x00007f2abd0e3cf0
2024.07.19 10:33:31.702716 [ 28272 ] {} <Fatal> BaseDaemon: ########################################
2024.07.19 10:33:31.702724 [ 28272 ] {} <Fatal> BaseDaemon: (version 24.3.3.102 (official build), build id: EF9E1BD0781C858153E899F2D95A044F4DD82F9B, git hash: 7e7f3bdd9be3ced03925d1d602037db8687e6401) (from thread 28069) (no query) Received signal Segmentation fault (11)
2024.07.19 10:33:31.702742 [ 28272 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2024.07.19 10:33:31.702748 [ 28272 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000011c223c6 0x0000000011c1805c 0x0000000011c2619a 0x000000000fd99d07 0x000000000fd9ae73 0x000000000cc7714d 0x00007f2abd06122a 0x00007f2abd0e3cf0
2024.07.19 10:33:31.702806 [ 28272 ] {} <Fatal> BaseDaemon: 2. DB::DistributedAsyncInsertDirectoryQueue::processFile(String&, DB::SettingsChanges const&) @ 0x0000000011c223c6
2024.07.19 10:33:31.702819 [ 28272 ] {} <Fatal> BaseDaemon: 3. DB::DistributedAsyncInsertDirectoryQueue::processFiles(DB::SettingsChanges const&) @ 0x0000000011c1805c
2024.07.19 10:33:31.702856 [ 28272 ] {} <Fatal> BaseDaemon: 4. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::DistributedAsyncInsertDirectoryQueue::DistributedAsyncInsertDirectoryQueue(DB::StorageDistributed&, std::shared_ptr<DB::IDisk> const&, String const&, std::shared_ptr<DB::ConnectionPoolWithFailover>, DB::ActionBlocker&, DB::BackgroundSchedulePool&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000011c2619a
2024.07.19 10:33:31.702880 [ 28272 ] {} <Fatal> BaseDaemon: 5. DB::BackgroundSchedulePool::threadFunction() @ 0x000000000fd99d07
2024.07.19 10:33:31.702936 [ 28272 ] {} <Fatal> BaseDaemon: 6. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000fd9ae73
2024.07.19 10:33:31.702982 [ 28272 ] {} <Fatal> BaseDaemon: 7. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000cc7714d
2024.07.19 10:33:31.702999 [ 28272 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00007f2abd06122a
2024.07.19 10:33:31.703004 [ 28272 ] {} <Fatal> BaseDaemon: 9. ? @ 0x00007f2abd0e3cf0
2024.07.19 10:33:31.935150 [ 28272 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: F3691ADAC982D94BEEF75EF7C8E42F75)
2024.07.19 10:33:31.935195 [ 28272 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues

```

It's not caused by query， Are there any methods for me to troubleshoot?

### PR DESCRIPTION
**Pull request by pamarcos**
Fix crash in DistributedAsyncInsert when connection is empty

### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash in DistributedAsyncInsert when connection is empty

Closes https://github.com/ClickHouse/ClickHouse/issues/66740

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 42384af0ef38dd326337e8cf18327871924f7359 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/67219/42384af0ef38dd326337e8cf18327871924f7359/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/9ff1492245ee1805c6062f57ffb243106a839399/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by pamarcos** [comment]
The [only test that failed](https://s3.amazonaws.com/clickhouse-test-reports/67219/981135bfb104b5ecfa0f1da5533e3d12f6850838/stateless_tests__msan__[2_4].html) is already [reported](https://github.com/ClickHouse/ClickHouse/issues/67169) and [fixed](https://github.com/ClickHouse/ClickHouse/pull/67173)

File: src/Storages/Distributed/DistributedAsyncInsertBatch.cpp [hunk 1]
```diff
@@ -245,6 +246,9 @@ void DistributedAsyncInsertBatch::sendBatch(const SettingsChanges & settings_cha
                 connection = std::move(result.front().entry);
                 compression_expected = connection->getCompression() == Protocol::Compression::Enable;
 
+                if (connection.isNull())
```
Comment (divanik) [inline src/Storages/Distributed/DistributedAsyncInsertBatch.cpp:249]: It really seems as a logical error and ideally should be debugged. As far as I see invariant that should be satisfied is !r.entry.isNull() && r.is_usable && !(settings.distributed_insert_skip_read_only_replicas && r.is_readonly). Could you double check this and change condition to this one, please?

**Review by divanik — COMMENTED** [review]
1. Also, please, add LogicalError to https://github.com/ClickHouse/ClickHouse/blob/a05312c6541d4c761fd5c242dba372d2cff5e842/src/Common/PoolWithFailoverBase.h#L324-L325 checking that up_to_date_count <= try_results.size(). Till now I haven't found any places where the invariant can be broken.
2. Could you explain to me briefly, how you found out that seg fault in the issue is connected with the LogicalError you added in this PR?

**Comment by pamarcos** [comment]
> Could you explain to me briefly, how you found out that seg fault in the issue is connected with the LogicalError you added in this PR?

Sure. I haven't been able to reproduce the issue, but according to the stack trace, the NULL pointer access happens in `void DistributedAsyncInsertDirectoryQueue::processFile`. Analyzing the source code in that function looking for pointer accesses, the only one that makes sense is the connection, because the `pool` is moved in its constructor and I didn't see in the logic how that could ever be NULL.

File: src/Storages/Distributed/DistributedAsyncInsertBatch.cpp (hunk 1 above)
Comment (pamarcos) [reply src/Storages/Distributed/DistributedAsyncInsertBatch.cpp]: Done! You're right. Because of [this line](https://github.com/ClickHouse/ClickHouse/blob/1480275ade1919651877e087fee3fda19924bc9f/src/Common/PoolWithFailoverBase.h#L303), that's the invariant that should be satisfied moving forward

**Comment by pamarcos** [comment]
> 1. Also, please, add LogicalError to https://github.com/ClickHouse/ClickHouse/blob/a05312c6541d4c761fd5c242dba372d2cff5e842/src/Common/PoolWithFailoverBase.h#L324-L325

Done in https://github.com/ClickHouse/ClickHouse/commit/eaede913b2ae0d5a4cb02ae82db20b6011270fe6#diff-f206c93448029d3b6e8aa3baa8834d0909740bd20709f984e1e06cfaecc0f6cdR330

**Review by divanik — APPROVED** [review]

**Comment by kssenii** [comment]
@pamarcos  Could this PR have caused this error ` Logical error: 'Received from kng4alm55c.us-east-2.aws.clickhouse-staging.com:9440. DB::Exception: Unexpected error for async deduplicated insert, please check error logs.` ? I saw this error today for the first time, no similar issue found. https://s3.amazonaws.com/clickhouse-test-reports/67361/2b79da36c0701bb9ca392fddd9129a7e0e04ef3f/stateless_tests__azure__asan__[2_3].html

**Comment by pamarcos** [comment]
> @pamarcos Could this PR have caused this error ` Logical error: 'Received from kng4alm55c.us-east-2.aws.clickhouse-staging.com:9440. DB::Exception: Unexpected error for async deduplicated insert, please check error logs.` ? I saw this error today for the first time, no similar issue found. [https://s3.amazonaws.com/clickhouse-test-reports/67361/2b79da36c0701bb9ca392fddd9129a7e0e04ef3f/stateless_tests__azure__asan__[2_3].html](https://s3.amazonaws.com/clickhouse-test-reports/67361/2b79da36c0701bb9ca392fddd9129a7e0e04ef3f/stateless_tests__azure__asan__%5B2_3%5D.html)

Hum. These changes do not include that trace, that's for sure. I downloaded the logs and checked that neither of the logical errors added by this PR happened. There's no

>Could not find enough connections for up-to-date results

and no

>Got an invalid connection result

There's another interesting error right before the one you shared:

```
2024.07.31 18:24:11.995609 [ 1460 ] {} <Error> system.query_log_sender.DistributedInsertQueue.default: Code: 241. DB::Exception: Received from kng4alm55c.us-east-2.aws.clickhouse-staging.com:9440. DB::Exception: Memory limit (for user) exceeded: would use 1.79 TiB (attempt to allocate chunk of 1513063 bytes), maximum: 20.60 GiB. OvercommitTracker decision: Memory overcommit has freed not enough memory..
```
