### PR TITLE
Fix crash in JSON column

### LINKED ISSUE #69870: JSON with Variant heap-use-after-free
**Describe the bug**

Running `kafkaMurmurHash` hash function on JSON with Variant causes a heap-use-after-free error.

**How to reproduce**

Run this Fiddle: https://fiddle.clickhouse.com/89be7c13-54cf-42ad-b798-22c2b6df6272

```sql
SET allow_experimental_json_type = 1, allow_experimental_variant_type = 1;
CREATE TABLE t0 (c0 Int) ENGINE = Memory();
INSERT INTO t0 (c0) VALUES (1);
ALTER TABLE t0 (ADD COLUMN c1 JSON(c1 Variant(Int,JSON(c1 Int))));
INSERT INTO t0 (c0, c1) VALUES (2, '{"c1":1}'::JSON);
SELECT kafkaMurmurHash(t0.c1) FROM t0;
```
Here is the address sanitizer output:

```
==1696407==ERROR: AddressSanitizer: heap-use-after-free on address 0x5040007a6ca0 at pc 0x555563b47f96 bp 0x7ffada5f30d0 sp 0x7ffada5f2890
READ of size 2 at 0x5040007a6ca0 thread T670 (QueryPullPipeEx)
    #0 0x555563b47f95 in __asan_memcpy (clickhouse+0xe5f3f95) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881)
    #1 0x555563bcf921 in DB::WriteBuffer::write(char const*, unsigned long) src/IO/WriteBuffer.h:94:13
    #2 0x555582d1623b in DB::writeString(char const*, unsigned long, DB::WriteBuffer&) src/IO/WriteHelpers.h:200:9
    #3 0x555582d1623b in DB::writeText(std::__1::basic_string_view<char, std::__1::char_traits<char>>, DB::WriteBuffer&) src/IO/WriteHelpers.h:1069:64
    #4 0x555582d1623b in DB::WriteBuffer& DB::operator<<<std::__1::basic_string_view<char, std::__1::char_traits<char>>>(DB::WriteBuffer&, std::__1::basic_string_view<char, std::__1::char_traits<char>> const&) src/IO/Operators.h:46:70
    #5 0x555582d1623b in DB::ColumnObject::getName() const src/Columns/ColumnObject.cpp:143:20
    #6 0x555582f697bc in DB::ColumnVariant::getName() const src/Columns/ColumnVariant.cpp:42:41
    #7 0x555582d162bc in DB::ColumnObject::getName() const src/Columns/ColumnObject.cpp:143:70
    #8 0x555582d19f2b in DB::ColumnObject::getDataAt(unsigned long) const src/Columns/ColumnObject.cpp:250:94
    #9 0x5555652915d9 in void DB::TargetSpecific::Default::FunctionAnyHash<DB::KafkaMurmurHashImpl, false, char, char>::executeGeneric<true>(char const&, DB::IColumn const*, DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 63ul, 64ul>&) const src/Functions/FunctionsHashing.h:870:1
    #10 0x555565281701 in void DB::TargetSpecific::Default::FunctionAnyHash<DB::KafkaMurmurHashImpl, false, char, char>::executeAny<true>(char const&, DB::IDataType const*, DB::IColumn const*, DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 63ul, 64ul>&) const src/Functions/FunctionsHashing.h:870:1
    #11 0x555565280f36 in DB::TargetSpecific::Default::FunctionAnyHash<DB::KafkaMurmurHashImpl, false, char, char>::executeForArgument(char const&, DB::IDataType const*, DB::IColumn const*, DB::PODArray<unsigned int, 4096ul, Allocator<false, false>, 63ul, 64ul>&, bool&) const src/Functions/FunctionsHashing.h:870:1
    #12 0x55556528010d in DB::TargetSpecific::Default::FunctionAnyHash<DB::KafkaMurmurHashImpl, false, char, char>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const src/Functions/FunctionsHashing.h:870:1
    #13 0x55556481301b in DB::ImplementationSelector<DB::IFunction>::selectAndExecute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const src/Functions/PerformanceAdaptors.h:228:40
    #14 0x55556527ff11 in DB::FunctionAnyHash<DB::KafkaMurmurHashImpl, false, char, char>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const src/Functions/FunctionsHashing.h:1421:25
    #15 0x555563bca7b4 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const src/Functions/IFunctionAdaptors.h:22:26
    #16 0x555565c278da in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const src/Functions/IFunction.cpp:247:15
    #17 0x555565c2992e in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const src/Functions/IFunction.cpp:303:22
    #18 0x555565c2ca04 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const src/Functions/IFunction.cpp:380:16
    #19 0x55558086aef4 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool, bool) src/Interpreters/ExpressionActions.cpp:636:60
    #20 0x55558086aef4 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const src/Interpreters/ExpressionActions.cpp:770:13
    #21 0x5555853c0bf8 in DB::ExpressionTransform::transform(DB::Chunk&) src/Processors/Transforms/ExpressionTransform.cpp:25:17
    #22 0x555574091ffe in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) src/Processors/ISimpleTransform.h:32:9
    #23 0x555584d87399 in DB::ISimpleTransform::work() src/Processors/ISimpleTransform.cpp:89:9
    #24 0x555584dcaded in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #25 0x555584dcaded in DB::ExecutionThreadContext::executeTask() src/Processors/Executors/ExecutionThreadContext.cpp:96:9
    #26 0x555584daf58f in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) src/Processors/Executors/PipelineExecutor.cpp:288:26
    #27 0x555584daffc9 in DB::PipelineExecutor::executeSingleThread(unsigned long) src/Processors/Executors/PipelineExecutor.cpp:254:5
    #28 0x555584dad07a in DB::PipelineExecutor::executeImpl(unsigned long, bool) src/Processors/Executors/PipelineExecutor.cpp:429:9
    #29 0x555584dac436 in DB::PipelineExecutor::execute(unsigned long, bool) src/Processors/Executors/PipelineExecutor.cpp:125:9
    #30 0x555584dd2d3c in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroup>, unsigned long, bool) src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24
    #31 0x555584dd2d3c in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109:13
    #32 0x555584dd2d3c in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #33 0x555584dd2d3c in decltype(auto) std::__1::__apply_tuple_impl[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) contrib/llvm-project/libcxx/include/tuple:1789:1
    #34 0x555584dd2d3c in decltype(auto) std::__1::apply[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) contrib/llvm-project/libcxx/include/tuple:1798:1
    #35 0x555584dd2d3c in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() src/Common/ThreadPool.h:251:13
    #36 0x555584dd2d3c in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15007]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #37 0x555584dd2d3c in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #38 0x555584dd2d3c in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15007]() contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #39 0x555584dd2d3c in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #40 0x555573c1fd7d in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #41 0x555573c1fd7d in std::__1::function<void ()>::operator()() const contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #42 0x555573c1fd7d in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) src/Common/ThreadPool.cpp:540:17
    #43 0x555573c2ab0c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const src/Common/ThreadPool.cpp:252:73
    #44 0x555573c2ab0c in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15007]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #45 0x555573c2ab0c in void std::__1::__thread_execute[abi:v15007]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<...>) contrib/llvm-project/libcxx/include/thread:284:5
    #46 0x555573c2ab0c in void* std::__1::__thread_proxy[abi:v15007]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) contrib/llvm-project/libcxx/include/thread:295:5
    #47 0x555563b47bcc in asan_thread_start(void*) crtstuff.c
    #48 0x7ffff7c9ca93 in start_thread nptl/pthread_create.c:447:8
    #49 0x7ffff7d29c3b in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

0x5040007a6ca0 is located 16 bytes inside of 48-byte region [0x5040007a6c90,0x5040007a6cc0)
freed by thread T670 (QueryPullPipeEx) here:
    #0 0x555563b7f556 in operator delete(void*, unsigned long) (clickhouse+0xe62b556) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881)
    #1 0x555582d4261c in void std::__1::__libcpp_operator_delete[abi:v15007]<void*, unsigned long>(void*, unsigned long) contrib/llvm-project/libcxx/include/new:256:3
    #2 0x555582d4261c in void std::__1::__do_deallocate_handle_size[abi:v15007]<>(void*, unsigned long) contrib/llvm-project/libcxx/include/new:282:10
    #3 0x555582d4261c in std::__1::__libcpp_deallocate[abi:v15007](void*, unsigned long, unsigned long) contrib/llvm-project/libcxx/include/new:296:14
    #4 0x555582d4261c in std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>::deallocate[abi:v15007](std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*, unsigned long) contrib/llvm-project/libcxx/include/__memory/allocator.h:128:13
    #5 0x555582d4261c in std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>>::deallocate[abi:v15007](std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>&, std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*, unsigned long) contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:282:13
    #6 0x555582d4261c in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*>*) contrib/llvm-project/libcxx/include/__hash_table:1533:9
    #7 0x555582d4261c in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::~__hash_table() contrib/llvm-project/libcxx/include/__hash_table:1473:5
    #8 0x555582d3a9ed in DB::ColumnObject::~ColumnObject() src/Columns/ColumnObject.h:18:7
    #9 0x555567783b7e in void boost::sp_adl_block::intrusive_ptr_release<DB::IColumn, boost::sp_adl_block::thread_safe_counter>(boost::sp_adl_block::intrusive_ref_counter<DB::IColumn, boost::sp_adl_block::thread_safe_counter> const*) contrib/boost/boost/smart_ptr/intrusive_ref_counter.hpp:173:9
    #10 0x555567783b7e in boost::intrusive_ptr<DB::IColumn const>::~intrusive_ptr() contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:100:23
    #11 0x555567783b7e in COW<DB::IColumn>::chameleon_ptr<DB::IColumn>::~chameleon_ptr() src/Common/COW.h:195:11
    #12 0x555567783b7e in void std::__1::__destroy_at[abi:v15007]<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, 0>(COW<DB::IColumn>::chameleon_ptr<DB::IColumn>*) contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13
    #13 0x555567783b7e in void std::__1::destroy_at[abi:v15007]<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, 0>(COW<DB::IColumn>::chameleon_ptr<DB::IColumn>*) contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5
    #14 0x555567783b7e in void std::__1::allocator_traits<std::__1::allocator<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>::destroy[abi:v15007]<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, void, void>(std::__1::allocator<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>&, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>*) contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9
    #15 0x555567783b7e in std::__1::vector<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>::__base_destruct_at_end[abi:v15007](COW<DB::IColumn>::chameleon_ptr<DB::IColumn>*) contrib/llvm-project/libcxx/include/vector:843:9
    #16 0x555567783b7e in std::__1::vector<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>::__clear[abi:v15007]() contrib/llvm-project/libcxx/include/vector:837:29
    #17 0x555567783b7e in std::__1::vector<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>::__destroy_vector::operator()[abi:v15007]() contrib/llvm-project/libcxx/include/vector:439:20
    #18 0x555582f98041 in std::__1::vector<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>::~vector[abi:v15007]() contrib/llvm-project/libcxx/include/vector:449:67
    #19 0x555582f98041 in DB::ColumnVariant::~ColumnVariant() src/Columns/ColumnVariant.h:59:7
    #20 0x555582f9820d in DB::ColumnVariant::~ColumnVariant() src/Columns/ColumnVariant.h:59:7
    #21 0x555582d426b3 in void boost::sp_adl_block::intrusive_ptr_release<DB::IColumn, boost::sp_adl_block::thread_safe_counter>(boost::sp_adl_block::intrusive_ref_counter<DB::IColumn, boost::sp_adl_block::thread_safe_counter> const*) contrib/boost/boost/smart_ptr/intrusive_ref_counter.hpp:173:9
    #22 0x555582d426b3 in boost::intrusive_ptr<DB::IColumn const>::~intrusive_ptr() contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:100:23
    #23 0x555582d426b3 in COW<DB::IColumn>::chameleon_ptr<DB::IColumn>::~chameleon_ptr() src/Common/COW.h:195:11
    #24 0x555582d426b3 in std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>::~pair() contrib/llvm-project/libcxx/include/__utility/pair.h:40:29
    #25 0x555582d426b3 in void std::__1::__destroy_at[abi:v15007]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>*) contrib/llvm-project/libcxx/include/__memory/construct_at.h:63:13
    #26 0x555582d426b3 in void std::__1::destroy_at[abi:v15007]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>*) contrib/llvm-project/libcxx/include/__memory/construct_at.h:88:5
    #27 0x555582d426b3 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>>::destroy[abi:v15007]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void, void>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>*) contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317:9
    #28 0x555582d426b3 in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*>*) contrib/llvm-project/libcxx/include/__hash_table:1532:9
    #29 0x555582d426b3 in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::~__hash_table() contrib/llvm-project/libcxx/include/__hash_table:1473:5
    #30 0x555582d3a9ed in DB::ColumnObject::~ColumnObject() src/Columns/ColumnObject.h:18:7
    #31 0x555582aee18e in void boost::sp_adl_block::intrusive_ptr_release<DB::IColumn, boost::sp_adl_block::thread_safe_counter>(boost::sp_adl_block::intrusive_ref_counter<DB::IColumn, boost::sp_adl_block::thread_safe_counter> const*) contrib/boost/boost/smart_ptr/intrusive_ref_counter.hpp:173:9
    #32 0x555582aee18e in boost::intrusive_ptr<DB::IColumn const>::~intrusive_ptr() contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:100:23
    #33 0x555582aee18e in COW<DB::IColumn>::chameleon_ptr<DB::IColumn>::~chameleon_ptr() src/Common/COW.h:195:11
    #34 0x555582aee18e in DB::ColumnConst::~ColumnConst() src/Columns/ColumnConst.h:23:7
    #35 0x555582aee18e in DB::ColumnConst::~ColumnConst() src/Columns/ColumnConst.h:23:7
    #36 0x555581c8454a in void boost::sp_adl_block::intrusive_ptr_release<DB::IColumn, boost::sp_adl_block::thread_safe_counter>(boost::sp_adl_block::intrusive_ref_counter<DB::IColumn, boost::sp_adl_block::thread_safe_counter> const*) contrib/boost/boost/smart_ptr/intrusive_ref_counter.hpp:173:9
    #37 0x555581c8454a in boost::intrusive_ptr<DB::IColumn const>::~intrusive_ptr() contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:100:23
    #38 0x555581c8454a in DB::createColumnWithDefaultValue(DB::IDataType const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long) src/Interpreters/inplaceBlockConversions.cpp:295:1
    #39 0x555581c82ae6 in DB::fillMissingColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long, DB::NamesAndTypesList const&, DB::NamesAndTypesList const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>) src/Interpreters/inplaceBlockConversions.cpp:424:30
    #40 0x55558584dd12 in DB::MemorySource::generate() src/Processors/QueryPlan/ReadFromMemoryStorageStep.cpp:78:9
    #41 0x555584d8d739 in DB::ISource::tryGenerate() src/Processors/ISource.cpp:139:18
    #42 0x555584d8cd42 in DB::ISource::work() src/Processors/ISource.cpp:108:26
    #43 0x555584dcaded in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #44 0x555584dcaded in DB::ExecutionThreadContext::executeTask() src/Processors/Executors/ExecutionThreadContext.cpp:96:9
    #45 0x555584daf58f in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) src/Processors/Executors/PipelineExecutor.cpp:288:26
    #46 0x555584daffc9 in DB::PipelineExecutor::executeSingleThread(unsigned long) src/Processors/Executors/PipelineExecutor.cpp:254:5
    #47 0x555584dad07a in DB::PipelineExecutor::executeImpl(unsigned long, bool) src/Processors/Executors/PipelineExecutor.cpp:429:9
    #48 0x555584dac436 in DB::PipelineExecutor::execute(unsigned long, bool) src/Processors/Executors/PipelineExecutor.cpp:125:9
    #49 0x555584dd2d3c in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroup>, unsigned long, bool) src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24
    #50 0x555584dd2d3c in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109:13
    #51 0x555584dd2d3c in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #52 0x555584dd2d3c in decltype(auto) std::__1::__apply_tuple_impl[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) contrib/llvm-project/libcxx/include/tuple:1789:1
    #53 0x555584dd2d3c in decltype(auto) std::__1::apply[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) contrib/llvm-project/libcxx/include/tuple:1798:1
    #54 0x555584dd2d3c in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() src/Common/ThreadPool.h:251:13
    #55 0x555584dd2d3c in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15007]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #56 0x555584dd2d3c in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #57 0x555584dd2d3c in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15007]() contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #58 0x555584dd2d3c in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #59 0x555573c1fd7d in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #60 0x555573c1fd7d in std::__1::function<void ()>::operator()() const contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #61 0x555573c1fd7d in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) src/Common/ThreadPool.cpp:540:17
    #62 0x555573c2ab0c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const src/Common/ThreadPool.cpp:252:73
    #63 0x555573c2ab0c in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15007]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #64 0x555573c2ab0c in void std::__1::__thread_execute[abi:v15007]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<...>) contrib/llvm-project/libcxx/include/thread:284:5
    #65 0x555573c2ab0c in void* std::__1::__thread_proxy[abi:v15007]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) contrib/llvm-project/libcxx/include/thread:295:5
    #66 0x555563b47bcc in asan_thread_start(void*) crtstuff.c

previously allocated by thread T670 (QueryPullPipeEx) here:
    #0 0x555563b7e8d1 in operator new(unsigned long) (clickhouse+0xe62a8d1) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881)
    #1 0x555582d42dcb in void* std::__1::__libcpp_operator_new[abi:v15007]<unsigned long>(unsigned long) contrib/llvm-project/libcxx/include/new:246:10
    #2 0x555582d42dcb in std::__1::__libcpp_allocate[abi:v15007](unsigned long, unsigned long) contrib/llvm-project/libcxx/include/new:272:10
    #3 0x555582d42dcb in std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>::allocate[abi:v15007](unsigned long) contrib/llvm-project/libcxx/include/__memory/allocator.h:112:38
    #4 0x555582d42dcb in std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>>::allocate[abi:v15007](std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>&, unsigned long) contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:262:20
    #5 0x555582d42dcb in std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>>>> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::__construct_node_hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>&&) contrib/llvm-project/libcxx/include/__hash_table:2381:23
    #6 0x555582d42dcb in std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*>, bool> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>&&) contrib/llvm-project/libcxx/include/__hash_table:2013:29
    #7 0x555582d13bdb in std::__1::enable_if<__can_extract_map_key<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>::value, std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*>, bool>>::type std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, std::__1::equal_to<void>, DB::StringHashForHeterogeneousLookup, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::__emplace_unique[abi:v15007]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>&&) contrib/llvm-project/libcxx/include/__hash_table:1053:16
    #8 0x555582d13bdb in std::__1::pair<std::__1::__hash_map_iterator<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>, void*>*>>, bool> std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>, DB::StringHashForHeterogeneousLookup, std::__1::equal_to<void>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::chameleon_ptr<DB::IColumn>>>>::emplace[abi:v15007]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, COW<DB::IColumn>::mutable_ptr<DB::IColumn>&&) contrib/llvm-project/libcxx/include/unordered_map:1258:25
    #9 0x555582d13bdb in DB::ColumnObject::ColumnObject(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>>, unsigned long, unsigned long) src/Columns/ColumnObject.cpp:78:31
    #10 0x555582d39d1e in COW<DB::IColumn>::mutable_ptr<DB::ColumnObject> COWHelper<DB::IColumnHelper<DB::ColumnObject, DB::IColumn>, DB::ColumnObject>::create<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>>, unsigned long&, unsigned long&>(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>>&&, unsigned long&, unsigned long&) src/Common/COW.h:284:71
    #11 0x555582d15f40 in DB::ColumnObject::create(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>>, unsigned long, unsigned long) src/Columns/ColumnObject.cpp:133:12
    #12 0x55557fc558c4 in DB::DataTypeObject::createColumn() const src/DataTypes/DataTypeObject.cpp:222:12
    #13 0x55557fc7eabd in DB::DataTypeVariant::createColumn() const src/DataTypes/DataTypeVariant.cpp:92:47
    #14 0x55557fc5564a in DB::DataTypeObject::createColumn() const src/DataTypes/DataTypeObject.cpp:220:42
    #15 0x55557fcf8244 in DB::IDataType::createColumnConst(unsigned long, DB::Field const&) const src/DataTypes/IDataType.cpp:58:19
    #16 0x55557fcf879a in DB::IDataType::createColumnConstWithDefaultValue(unsigned long) const src/DataTypes/IDataType.cpp:66:12
    #17 0x555581c841a7 in DB::createColumnWithDefaultValue(DB::IDataType const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long) src/Interpreters/inplaceBlockConversions.cpp:282:29
    #18 0x555581c82ae6 in DB::fillMissingColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&, unsigned long, DB::NamesAndTypesList const&, DB::NamesAndTypesList const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>) src/Interpreters/inplaceBlockConversions.cpp:424:30
    #19 0x55558584dd12 in DB::MemorySource::generate() src/Processors/QueryPlan/ReadFromMemoryStorageStep.cpp:78:9
    #20 0x555584d8d739 in DB::ISource::tryGenerate() src/Processors/ISource.cpp:139:18
    #21 0x555584d8cd42 in DB::ISource::work() src/Processors/ISource.cpp:108:26
    #22 0x555584dcaded in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #23 0x555584dcaded in DB::ExecutionThreadContext::executeTask() src/Processors/Executors/ExecutionThreadContext.cpp:96:9
    #24 0x555584daf58f in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) src/Processors/Executors/PipelineExecutor.cpp:288:26
    #25 0x555584daffc9 in DB::PipelineExecutor::executeSingleThread(unsigned long) src/Processors/Executors/PipelineExecutor.cpp:254:5
    #26 0x555584dad07a in DB::PipelineExecutor::executeImpl(unsigned long, bool) src/Processors/Executors/PipelineExecutor.cpp:429:9
    #27 0x555584dac436 in DB::PipelineExecutor::execute(unsigned long, bool) src/Processors/Executors/PipelineExecutor.cpp:125:9
    #28 0x555584dd2d3c in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroup>, unsigned long, bool) src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24
    #29 0x555584dd2d3c in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109:13
    #30 0x555584dd2d3c in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #31 0x555584dd2d3c in decltype(auto) std::__1::__apply_tuple_impl[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) contrib/llvm-project/libcxx/include/tuple:1789:1
    #32 0x555584dd2d3c in decltype(auto) std::__1::apply[abi:v15007]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) contrib/llvm-project/libcxx/include/tuple:1798:1
    #33 0x555584dd2d3c in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() src/Common/ThreadPool.h:251:13
    #34 0x555584dd2d3c in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15007]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #35 0x555584dd2d3c in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #36 0x555584dd2d3c in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15007]() contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #37 0x555584dd2d3c in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #38 0x555573c1fd7d in std::__1::__function::__policy_func<void ()>::operator()[abi:v15007]() const contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #39 0x555573c1fd7d in std::__1::function<void ()>::operator()() const contrib/llvm-project/libcxx/include/__functional/function.h:1197:12
    #40 0x555573c1fd7d in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) src/Common/ThreadPool.cpp:540:17
    #41 0x555573c2ab0c in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const src/Common/ThreadPool.cpp:252:73
    #42 0x555573c2ab0c in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15007]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #43 0x555573c2ab0c in void std::__1::__thread_execute[abi:v15007]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<...>) contrib/llvm-project/libcxx/include/thread:284:5
    #44 0x555573c2ab0c in void* std::__1::__thread_proxy[abi:v15007]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) contrib/llvm-project/libcxx/include/thread:295:5
    #45 0x555563b47bcc in asan_thread_start(void*) crtstuff.c

Thread T670 (QueryPullPipeEx) created by T3 (TCPHandler) here:
    #0 0x555563b2fa55 in pthread_create (clickhouse+0xe5dba55) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881)
    #1 0x555573c29ce3 in std::__1::__libcpp_thread_create[abi:v15007](unsigned long*, void* (*)(void*), void*) contrib/llvm-project/libcxx/include/__threading_support:376:10
    #2 0x555573c29ce3 in std::__1::thread::thread<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) contrib/llvm-project/libcxx/include/thread:311:16
    #3 0x555573c1d9c7 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool) src/Common/ThreadPool.cpp:252:35
    #4 0x555573c1e2b2 in ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, Priority, unsigned long, bool) src/Common/ThreadPool.cpp:337:5
    #5 0x555584dd08e8 in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) src/Common/ThreadPool.h:218:38
    #6 0x555584dd08e8 in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long) src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:112:24
    #7 0x555584dd153e in DB::PullingAsyncPipelineExecutor::pull(DB::Block&, unsigned long) src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:138:10
    #8 0x555584bff052 in DB::TCPHandler::processOrdinaryQuery() src/Server/TCPHandler.cpp:1127:25
    #9 0x555584bea693 in DB::TCPHandler::runImpl() src/Server/TCPHandler.cpp:609:17
    #10 0x555584c1a188 in DB::TCPHandler::run() src/Server/TCPHandler.cpp:2520:9
    #11 0x55558c8bc22e in Poco::Net::TCPServerConnection::start() base/poco/Net/src/TCPServerConnection.cpp:43:3
    #12 0x55558c8bce36 in Poco::Net::TCPServerDispatcher::run() base/poco/Net/src/TCPServerDispatcher.cpp:115:38
    #13 0x55558c7de30a in Poco::PooledThread::run() base/poco/Foundation/src/ThreadPool.cpp:205:14
    #14 0x55558c7d8fc7 in Poco::ThreadImpl::runnableEntry(void*) base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #15 0x555563b47bcc in asan_thread_start(void*) crtstuff.c

Thread T3 (TCPHandler) created by T0 here:
    #0 0x555563b2fa55 in pthread_create (clickhouse+0xe5dba55) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881)
    #1 0x55558c7d843b in Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) base/poco/Foundation/src/Thread_POSIX.cpp:198:6
    #2 0x55558c7db165 in Poco::Thread::start(Poco::Runnable&) base/poco/Foundation/src/Thread.cpp:118:2
    #3 0x55558c7dea1c in Poco::PooledThread::start() base/poco/Foundation/src/ThreadPool.cpp:91:10
    #4 0x55558c7dea1c in Poco::ThreadPool::ThreadPool(int, int, int, int, unsigned long, unsigned long) base/poco/Foundation/src/ThreadPool.cpp:258:12
    #5 0x555573dd2bb6 in DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) programs/server/Server.cpp:908:22
    #6 0x55558c915d76 in Poco::Util::Application::run() base/poco/Util/src/Application.cpp:315:8
    #7 0x555573dc7ee1 in DB::Server::run() programs/server/Server.cpp:410:25
    #8 0x555573dc3a9f in mainEntryClickHouseServer(int, char**) programs/server/Server.cpp:216:20
    #9 0x555563b822d5 in main programs/main.cpp:248:21
    #10 0x7ffff7c2a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #11 0x7ffff7c2a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #12 0x555563ab102d in _start (clickhouse+0xe55d02d) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881)

SUMMARY: AddressSanitizer: heap-use-after-free (clickhouse+0xe5f3f95) (BuildId: 0560a6927d33d3b2b183ee5b0ae19b5f1a541881) in __asan_memcpy
Shadow bytes around the buggy address:
  0x5040007a6a00: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 00 00
  0x5040007a6a80: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 00 00
  0x5040007a6b00: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00 00 00
  0x5040007a6b80: fa fa 00 00 00 00 00 fa fa fa fd fd fd fd fd fd
  0x5040007a6c00: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
=>0x5040007a6c80: fa fa fd fd[fd]fd fd fd fa fa fd fd fd fd fd fd
  0x5040007a6d00: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x5040007a6d80: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x5040007a6e00: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x5040007a6e80: fa fa fd fd fd fd fd fd fa fa 00 00 00 00 00 00
  0x5040007a6f00: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1696407==ABORTING
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Critical Bug Fix (crash, LOGICAL_ERROR, data loss, RBAC)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible crash in JSON column.

Closes https://github.com/ClickHouse/ClickHouse/issues/69870

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 6a1e328d3888941962478093312560965bcd8148 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70172/6a1e328d3888941962478093312560965bcd8148/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/70160/2f4518fa66d4baa425fa6ef8479cb8f6debb369d/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by antonio2368 — APPROVED** [review]

File: src/Columns/ColumnObject.cpp [hunk 1]
```diff
@@ -87,6 +87,29 @@ ColumnObject::ColumnObject(
...
+    /// point to the new strings in typed_paths and dynamic_paths.
+    sorted_typed_paths.clear();
+    for (const auto & [path, _] : typed_paths)
+        sorted_typed_paths.emplace_back(path);
+    std::sort(sorted_typed_paths.begin(), sorted_typed_paths.end());
+
+    sorted_dynamic_paths.clear();
+    for (const auto & [path, _] : dynamic_paths)
+        sorted_dynamic_paths.emplace(path);
+}
```
Comment (csun5285) [inline src/Columns/ColumnObject.cpp:111]: std::sort(sorted_dynamic_paths.begin(), sorted_dynamic_paths.end()); ?
