### PR TITLE
Fix UBSAN in largestTriangleThreeBuckets

### LINKED ISSUE #73143: largestTriangleThreeBuckets UBSAN error
**Describe the bug**
Run the following query with UBSAN.

**How to reproduce**
Run:

```sql
SELECT largestTriangleThreeBuckets(1)(0, '1900-01-01 00:00:00'::DateTime64);
```
Error output:
```
src/AggregateFunctions/AggregateFunctionLargestTriangleThreeBuckets.cpp:332:65:
runtime error: -2.20899e+12 is outside the range of representable values of type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer:
undefined-behavior src/AggregateFunctions/AggregateFunctionLargestTriangleThreeBuckets.cpp:332:65
```

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Closes #73143.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll** [comment]
*This is an automated comment for commit 49bcd726a4f7e5d95c25c0489199c7e5f985f930 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/73172/49bcd726a4f7e5d95c25c0489199c7e5f985f930/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/73172/49bcd726a4f7e5d95c25c0489199c7e5f985f930/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by yariks5s — APPROVED** [review]

File: tests/queries/0_stateless/02842_largestTriangleThreeBuckets_aggregate_function.sql [hunk 1]
```diff
@@ -61,4 +61,6 @@ SELECT
   point_x - neighbor(point_x, -1) AS point_x_diff_with_previous_row
 FROM largestTriangleTreeBucketsBucketSizeTest LIMIT 990, 10;
 
+SELECT largestTriangleThreeBuckets(1)(0, '1900-01-01 00:00:00'::DateTime64);
+
```
Comment (alexkats) [inline tests/queries/0_stateless/02842_largestTriangleThreeBuckets_aggregate_function.sql:65]: We shouldn't change existing tests, but rather create new ones

Comment (rschu1ze) [reply tests/queries/0_stateless/02842_largestTriangleThreeBuckets_aggregate_function.sql:65]: There are two schools of thoughts about this :)
