### PR TITLE
Analyzer duplicate alias crash fix

### LINKED ISSUE #44196: Analyzer: Logical error: 'Node NULL with duplicate alias does not exists in alias table'
https://s3.amazonaws.com/clickhouse-test-reports/0/8fc23262c5f4e15a5cbb548b7ff88699e8e210fb/fuzzer_astfuzzerasan//report.html
```
022.12.13 11:29:57.012562 [ 157 ] {d6b6ba0f-d198-446f-9f26-364cfc4fd57b} <Fatal> : Logical error: 'Node NULL with duplicate alias  does not exists in alias table. In scope (SELECT x IN (SELECT 255 FROM (SELECT -2 AS z)), 9223372036854775806, x IN (SELECT countIf(y, z = -2147483647) FROM (SELECT '9223372036854775807' AS y, -2147483648 AS z)) FROM (SELECT NULL WHERE x IN (SELECT NULL FROM (SELECT NULL))))'.
2022.12.13 11:29:57.013208 [ 715 ] {} <Fatal> BaseDaemon: ########################################
2022.12.13 11:29:57.013334 [ 715 ] {} <Fatal> BaseDaemon: (version 22.12.1.1 (official build), build id: B2D526007484596E9DC2915910EF8A836262A715) (from thread 157) (query_id: d6b6ba0f-d198-446f-9f26-364cfc4fd57b) (query: SELECT toUInt64(NULL) AS x FROM (SELECT 1.0001 WHERE 100) WITH TOTALS HAVING x IN (SELECT x IN (SELECT countIf(z = -2147483647) FROM (SELECT 1025 AS z)), NULL FROM (SELECT x IN (SELECT x IN (SELECT 255 FROM (SELECT -2 AS z)), 9223372036854775806, x IN (SELECT countIf(y, z = -2147483647) FROM (SELECT '9223372036854775807' AS y, -2147483648 AS z)) FROM (SELECT NULL WHERE x IN (SELECT NULL FROM (SELECT NULL)))), '0.7'))) Received signal Aborted (6)
2022.12.13 11:29:57.013434 [ 715 ] {} <Fatal> BaseDaemon: 
2022.12.13 11:29:57.013562 [ 715 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fd4e646d00b 0x7fd4e644c859 0x1f754bdb 0x1f7552fb 0x30beba0e 0x30b631d4 0x30ba523c 0x30b71177 0x30b6f237 0x30b5c6b9 0x30b7894e 0x30b5c651 0x30b70eed 0x30b6f237 0x30b9d05a 0x30b71177 0x30b5db31 0x30b56e0c 0x30b526fc 0x3170c05f 0x30c86993 0x3203829c 0x3203326c 0x3453a51e 0x3456ac26 0x3bc95fef 0x3bc96d45 0x3c15aafc 0x3c1540ad 0x7fd4e6624609 0x7fd4e6549133
2022.12.13 11:29:57.013678 [ 715 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7fd4e646d00b in ?
2022.12.13 11:29:57.013784 [ 715 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7fd4e644c859 in ?
2022.12.13 11:29:57.153877 [ 715 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1f754bdb in /workspace/clickhouse
2022.12.13 11:29:57.289686 [ 715 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../src/Common/Exception.cpp:64: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*>> const&)
2022.12.13 11:29:57.289798 [ 715 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:78: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x1f7552fb in /workspace/clickhouse
2022.12.13 11:29:57.826710 [ 715 ] {} <Fatal> BaseDaemon: 7.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__is_long[abi:v15000]() const
2022.12.13 11:29:57.826832 [ 715 ] {} <Fatal> BaseDaemon: 7.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/string:2333: ~basic_string
2022.12.13 11:29:57.826906 [ 715 ] {} <Fatal> BaseDaemon: 7.3. inlined from ./build_docker/../src/Common/Exception.h:32: ~MessageMasked
2022.12.13 11:29:57.826983 [ 715 ] {} <Fatal> BaseDaemon: 7.4. inlined from ./build_docker/../src/Common/Exception.h:41: Exception
2022.12.13 11:29:57.827052 [ 715 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Common/Exception.h:50: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x30beba0e in /workspace/clickhouse
2022.12.13 11:29:58.246346 [ 715 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:6057: DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x30b631d4 in /workspace/clickhouse
2022.12.13 11:29:58.834149 [ 715 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:4127: DB::(anonymous namespace)::QueryAnalyzer::resolveFunction(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x30ba523c in /workspace/clickhouse
2022.12.13 11:29:59.231757 [ 715 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x30b71177 in /workspace/clickhouse
2022.12.13 11:29:59.623812 [ 715 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x30b6f237 in /workspace/clickhouse
2022.12.13 11:30:00.046457 [ 715 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:815: std::__1::shared_ptr<DB::IQueryTreeNode>::operator->[abi:v15000]() const
2022.12.13 11:30:00.046558 [ 715 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:5101: DB::(anonymous namespace)::QueryAnalyzer::resolveProjectionExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&)
2022.12.13 11:30:00.046616 [ 715 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:5928: DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x30b5c6b9 in /workspace/clickhouse
2022.12.13 11:30:00.528380 [ 715 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:5434: DB::(anonymous namespace)::QueryAnalyzer::resolveQueryJoinTreeNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, DB::(anonymous namespace)::QueryExpressionsAliasVisitor&) @ 0x30b7894e in /workspace/clickhouse
2022.12.13 11:30:00.936632 [ 715 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x30b5c651 in /workspace/clickhouse
2022.12.13 11:30:01.329811 [ 715 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:4833: DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x30b70eed in /workspace/clickhouse
2022.12.13 11:30:01.726878 [ 715 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNodeList(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x30b6f237 in /workspace/clickhouse
2022.12.13 11:30:02.320024 [ 715 ] {} <Fatal> BaseDaemon: 17. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveFunction(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x30b9d05a in /workspace/clickhouse
2022.12.13 11:30:02.722210 [ 715 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:0: DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNode(std::__1::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x30b71177 in /workspace/clickhouse
2022.12.13 11:30:03.134851 [ 715 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/vector:580: std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::data[abi:v15000]() const
2022.12.13 11:30:03.134953 [ 715 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/vector:760: std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>::__annotate_delete[abi:v15000]() const
2022.12.13 11:30:03.135019 [ 715 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/vector:431: ~vector
2022.12.13 11:30:03.135066 [ 715 ] {} <Fatal> BaseDaemon: 19. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:5965: DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::__1::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x30b5db31 in /workspace/clickhouse
2022.12.13 11:30:03.515035 [ 715 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:996: DB::(anonymous namespace)::QueryAnalyzer::resolve(std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::shared_ptr<DB::IQueryTreeNode> const&, std::__1::shared_ptr<DB::Context const>)
2022.12.13 11:30:03.515137 [ 715 ] {} <Fatal> BaseDaemon: 20. ./build_docker/../src/Analyzer/Passes/QueryAnalysisPass.cpp:6249: DB::QueryAnalysisPass::run(std::__1::shared_ptr<DB::IQueryTreeNode>, std::__1::shared_ptr<DB::Context const>) @ 0x30b56e0c in /workspace/clickhouse
2022.12.13 11:30:03.545891 [ 715 ] {} <Fatal> BaseDaemon: 21. ./build_docker/../src/Analyzer/QueryTreePassManager.cpp:97: DB::QueryTreePassManager::run(std::__1::shared_ptr<DB::IQueryTreeNode>) @ 0x30b526fc in /workspace/clickhouse
2022.12.13 11:30:03.603852 [ 715 ] {} <Fatal> BaseDaemon: 22.1. inlined from ./build_docker/../src/Analyzer/QueryTreePassManager.h:13: ~QueryTreePassManager
2022.12.13 11:30:03.603944 [ 715 ] {} <Fatal> BaseDaemon: 22.2. inlined from ./build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:57: DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&)
2022.12.13 11:30:03.603993 [ 715 ] {} <Fatal> BaseDaemon: 22. ./build_docker/../src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:66: DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::__1::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context const>) @ 0x3170c05f in /workspace/clickhouse
2022.12.13 11:30:03.668901 [ 715 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:0: std::__1::__unique_if<DB::InterpreterSelectQueryAnalyzer>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectQueryAnalyzer, std::__1::shared_ptr<DB::IAST>&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context>&>(std::__1::shared_ptr<DB::IAST>&, DB::SelectQueryOptions const&, std::__1::shared_ptr<DB::Context>&)
2022.12.13 11:30:03.668973 [ 715 ] {} <Fatal> BaseDaemon: 23. ./build_docker/../src/Interpreters/InterpreterFactory.cpp:140: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x30c86993 in /workspace/clickhouse
2022.12.13 11:30:04.007124 [ 715 ] {} <Fatal> BaseDaemon: 24. ./build_docker/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x3203829c in /workspace/clickhouse
2022.12.13 11:30:04.376552 [ 715 ] {} <Fatal> BaseDaemon: 25. ./build_docker/../src/Interpreters/executeQuery.cpp:1083: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x3203326c in /workspace/clickhouse
2022.12.13 11:30:04.603011 [ 715 ] {} <Fatal> BaseDaemon: 26. ./build_docker/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x3453a51e in /workspace/clickhouse
2022.12.13 11:30:04.976828 [ 715 ] {} <Fatal> BaseDaemon: 27. ./build_docker/../src/Server/TCPHandler.cpp:1904: DB::TCPHandler::run() @ 0x3456ac26 in /workspace/clickhouse
2022.12.13 11:30:04.986909 [ 715 ] {} <Fatal> BaseDaemon: 28. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x3bc95fef in /workspace/clickhouse
2022.12.13 11:30:05.005291 [ 715 ] {} <Fatal> BaseDaemon: 29.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()[abi:v15000](Poco::Net::TCPServerConnection*) const
2022.12.13 11:30:05.005379 [ 715 ] {} <Fatal> BaseDaemon: 29.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2022.12.13 11:30:05.005436 [ 715 ] {} <Fatal> BaseDaemon: 29.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2022.12.13 11:30:05.005482 [ 715 ] {} <Fatal> BaseDaemon: 29. ./build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x3bc96d45 in /workspace/clickhouse
2022.12.13 11:30:05.028014 [ 715 ] {} <Fatal> BaseDaemon: 30. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x3c15aafc in /workspace/clickhouse
2022.12.13 11:30:05.046520 [ 715 ] {} <Fatal> BaseDaemon: 31.1. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::get()
2022.12.13 11:30:05.046597 [ 715 ] {} <Fatal> BaseDaemon: 31.2. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::assign(Poco::Runnable*)
2022.12.13 11:30:05.046669 [ 715 ] {} <Fatal> BaseDaemon: 31.3. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::operator=(Poco::Runnable*)
2022.12.13 11:30:05.046715 [ 715 ] {} <Fatal> BaseDaemon: 31. ./build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x3c1540ad in /workspace/clickhouse
2022.12.13 11:30:05.046767 [ 715 ] {} <Fatal> BaseDaemon: 32. ? @ 0x7fd4e6624609 in ?
2022.12.13 11:30:05.046817 [ 715 ] {} <Fatal> BaseDaemon: 33. __clone @ 0x7fd4e6549133 in ?
2022.12.13 11:30:05.923403 [ 715 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 8FF007069C3C089FCA41F13A7C31AC5E)
2022.12.13 11:31:17.715869 [ 146 ] {} <Fatal> Application: Child process was terminated by signal 6.

```

### PR DESCRIPTION
**Pull request by kitaisreal**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes #44196.

### CODE REVIEW

**Comment by SmitaRKulkarni** [comment]
Some failures in fasttest, eg:
`CREATE TABLE test_table ( id UInt64,  value String ) ENGINE=TinyLog;`
`DESCRIBE (WITH test_table_in_cte AS (SELECT id FROM test_table) SELECT id IN test_table_in_cte FROM test_table)`
I think some changes are needed in resolveFunction in place of the removed code , what do you think ?

**Comment by kitaisreal** [comment]
@SmitaRKulkarni updated.

File: src/Analyzer/Passes/QueryAnalysisPass.cpp [hunk 1]
```diff
@@ -4717,13 +4715,29 @@ ProjectionNames QueryAnalyzer::resolveExpressionNode(QueryTreeNodePtr & node, Id
...
+                    else
+                        union_node->setIsCTE(false);
+
+                    IdentifierResolveScope subquery_scope(node, &scope /*parent_scope*/);
+                    subquery_scope.subquery_depth = scope.subquery_depth + 1;
+
+                    if (subquery_node)
+                        resolveQuery(node, subquery_scope);
+                    else
+                        resolveUnion(node, subquery_scope);
```
Comment (SmitaRKulkarni) [inline src/Analyzer/Passes/QueryAnalysisPass.cpp:4740]: In the above block, we check multiple times whether node is QueryNode or UnionNode, mostly because of CTE manipulation.I agree this is better than duplicating code by having a big if else block.
If it's likely to be used extensively like this, maybe we can have an abstract parent to QueryNode & UnionNode which supports CTE ( in a separate PR), what do you think ?

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM

File: src/Analyzer/Passes/QueryAnalysisPass.cpp (hunk 1 above)
Comment (kitaisreal) [reply src/Analyzer/Passes/QueryAnalysisPass.cpp:4740]: We discussed it with @novikd before, and I am not sure about this. Query and Union nodes have some common boolean flags, so this can be performed. But need to discuss once again.
