### PR TITLE
Fix data race between getWorkloadEntityStorage and ContextSharedPart::shutdown

### LINKED ISSUE #83331: Data race between getWorkloadEntityStorage and ContextSharedPart::shutdown
```
0x120ba2ecstd::__1::unique_ptr<DB::IWorkloadEntityStorage, std::__1::default_delete<DB::IWorkloadEntityStorage>>::operator bool[abi:ne190107]() const
./ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:279:19
DB::ContextSharedPart::shutdown()
./ci/tmp/build/./src/Interpreters/Context.cpp:807:9

DB::Context::shutdown()
./ci/tmp/build/./src/Interpreters/Context.cpp:5699:13

DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_4::operator()() const
./ci/tmp/build/./programs/server/Server.cpp:1272:5

BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_4>::invoke()
./ci/tmp/build/./base/base/../base/scope_guard.h:101:9
BasicScopeGuard<DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)::$_4>::~BasicScopeGuard()
./ci/tmp/build/./base/base/../base/scope_guard.h:50:26
DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)
./ci/tmp/build/./programs/server/Server.cpp:3045:1

Poco::Util::Application::run()
./ci/tmp/build/./base/poco/Util/src/Application.cpp:315:8

DB::Server::run()
./ci/tmp/build/./programs/server/Server.cpp:613:25

Poco::Util::ServerApplication::run(int, char**)
./ci/tmp/build/./base/poco/Util/src/ServerApplication.cpp:131:9


mainEntryClickHouseServer(int, char**)
./ci/tmp/build/./programs/server/Server.cpp:409:20
```

```
std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*))
./ci/tmp/build/./contrib/llvm-project/libcxx/src/call_once.cpp:57:5

void std::__1::call_once[abi:ne190107]<DB::Context::getWorkloadEntityStorage() const::$_0>(std::__1::once_flag&, DB::Context::getWorkloadEntityStorage() const::$_0&&)
./ci/tmp/build/./contrib/llvm-project/libcxx/include/__mutex/once_flag.h:131:5
void DB::callOnce<DB::Context::getWorkloadEntityStorage() const::$_0>(std::__1::once_flag&, DB::Context::getWorkloadEntityStorage() const::$_0&&)
./ci/tmp/build/./src/Common/callOnce.h:13:5
DB::Context::getWorkloadEntityStorage() const
./ci/tmp/build/./src/Interpreters/Context.cpp:3293:5

DB::allocateCPUSlots(unsigned long, bool)
./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:389:65
DB::PipelineExecutor::initializeExecution(unsigned long, bool)
./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:424:17

DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*)
./ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:167:9

DB::PullingPipelineExecutor::pull(DB::Chunk&)
./ci/tmp/build/./src/Processors/Executors/PullingPipelineExecutor.cpp:54:20

DB::PullingPipelineExecutor::pull(DB::Block&)
./ci/tmp/build/./src/Processors/Executors/PullingPipelineExecutor.cpp:65:10

DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() const
./ci/tmp/build/./src/Storages/MergeTree/MergeTask.cpp:1071:67

DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute()
./ci/tmp/build/./src/Storages/MergeTree/MergeTask.cpp:898:16
```

Cc @serxa

### PR DESCRIPTION
**Pull request by serxa**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Details
Fixes https://github.com/ClickHouse/ClickHouse/issues/83331. This is a very rare data race, so there is no proper way to add a test. It also fixes other places in the Context class that used a similar pattern of destruction.

### CODE REVIEW

File: src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -3473,10 +3481,14 @@ void Context::setUserDefinedSQLObjectsStorage(std::unique_ptr<IUserDefinedSQLObj
 IWorkloadEntityStorage & Context::getWorkloadEntityStorage() const
 {
     callOnce(shared->workload_entity_storage_initialized, [&] {
-        shared->workload_entity_storage = createWorkloadEntityStorage(getGlobalContext());
+        auto value = = createWorkloadEntityStorage(getGlobalContext());
```
Comment (Michicosun) [inline src/Interpreters/Context.cpp]:
```suggestion
        auto value = createWorkloadEntityStorage(getGlobalContext());
```

File: src/Interpreters/Context.cpp [hunk 2]
```diff
@@ -3473,10 +3481,14 @@ void Context::setUserDefinedSQLObjectsStorage(std::unique_ptr<IUserDefinedSQLObj
...
+        std::lock_guard lock(shared->mutex);
+        shared->workload_entity_storage = std::move(value);
```
Comment (Michicosun) [inline src/Interpreters/Context.cpp]: I suppose doing this under the lock is not enough, because still there is a race with this line https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/Context.cpp#L854, but now on just access to unique pointer

Comment (Michicosun) [inline src/Interpreters/Context.cpp]: Also, I suppose if this call is being called concurrently with shutdown, we should not create anything. Perhaps we should synchronize with `is_shutdown_called` as well?

Comment (serxa) [reply src/Interpreters/Context.cpp]: It's also very interesting why all other structs in ContextSharedPart are not protected at all. Let's say `external_user_defined_executable_functions_loader` is almost the same as `user_defined_sql_objects_storage`. It is just another storage, but it is not protected at all by the mutex. I don't understand why yet.

Comment (serxa) [reply src/Interpreters/Context.cpp]: It turns out that everything is based on the proper order of destruction, so we just should make sure nobody will access workload entity storage before we are going to destruct it. Now merges may access it.

Comment (serxa) [reply src/Interpreters/Context.cpp]: Yes, this is also fixed by proper shutdown order

File: src/Interpreters/Context.cpp [hunk 3]
```diff
@@ -3460,23 +3461,15 @@ IUserDefinedSQLObjectsStorage & Context::getUserDefinedSQLObjectsStorage()
...
-    shared->user_defined_sql_objects_storage = std::move(storage);
-}
-
 IWorkloadEntityStorage & Context::getWorkloadEntityStorage() const
 {
     callOnce(shared->workload_entity_storage_initialized, [&] {
         shared->workload_entity_storage = createWorkloadEntityStorage(getGlobalContext());
     });
 
-    std::lock_guard lock(shared->mutex);
```
Comment (serxa) [inline src/Interpreters/Context.cpp:3479]: Note that there is no need for locking at all. I initially copy-pasted it from getUserDefinedSQLObjectsStorage, which had a setter previously and required locking. However, since the setter is no longer in use, we do not need any locking there and here as well.

**Review by Michicosun — APPROVED** [review]
