### PR TITLE
Fix incorrect judgement of of monotonicity of function abs

### LINKED ISSUE #63082: Wrong query result when using abs function for index analysis
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

A query that use `abs` for index analysis may incorrectly skip some ranges.

Reproduce:

```sql
CREATE TABLE t (id UInt64, ts DateTime) ENGINE = MergeTree() ORDER BY (id, ts) SETTINGS index_granularity = 2;

INSERT INTO t VALUES (1, '2023-05-04 21:17:23') (1, '2023-05-04 22:17:23') (2, '2023-05-04 22:17:23') (2, '2023-05-04 23:17:23');

-- This query should return two rows with ts = '2023-05-04 22:17:23'
SELECT *, abs(toUnixTimestamp(ts) - toUnixTimestamp(1683238643)) AS error FROM t WHERE error < 3600;

1	2023-05-04 22:17:23	0

```

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

Yes, in HEAD https://fiddle.clickhouse.com/0ccd5f20-f35b-4d79-9300-2e92cfc257c7

**Additional context**

> Add any other context about the problem here.

Can assign to me as I'm working on the fix already

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Fix incorrect judgement of of monotonicity of function `abs`

Close #63082 

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

---
### Modify your CI run:
**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [x]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 4b7abbce68d65f51e316501d4fdb6fc85421208d with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63097/4b7abbce68d65f51e316501d4fdb6fc85421208d/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by yariks5s — APPROVED** [review]

**Comment by yariks5s** [comment]
failed tests seem to be really unrelated to your changes, will merge this PR as soon as those tests will be fixed

File: src/Functions/abs.cpp [hunk 1]
```diff
@@ -45,7 +45,7 @@ template <> struct FunctionUnaryArithmeticMonotonicity<NameAbs>
         if ((left_float < 0 && right_float > 0) || (left_float > 0 && right_float < 0))
             return {};
 
-        return { .is_monotonic = true, .is_positive = left_float > 0, .is_strict = true, };
+        return { .is_monotonic = true, .is_positive = std::min(left_float, right_float) >= 0, .is_strict = true, };
```
Comment (alexey-milovidov) [inline src/Functions/abs.cpp:48]: If both boundaries are greater or equals zero it is positive; if both less or equal zero it is negative; otherwise it is not monotonic.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/Functions/abs.cpp (hunk 1 above)
Comment (canhld94) [reply src/Functions/abs.cpp:48]: I think the implementation already works as you describe?

The previous condition makes sure that both boundaries are either >=0 or <= 0:

```cpp
if ((left_float < 0 && right_float > 0) || (left_float > 0 && right_float < 0))
            return {};
```

Then `.is_positive = std::min(left_float, right_float) >= 0` means it's positive if the lower boundary >= 0.

Comment (alexey-milovidov) [reply src/Functions/abs.cpp:48]: That's true, thank you!
