### PR TITLE
Fix unary operators parsing

### LINKED ISSUE #57696: Incorrect plus operation with not function
ClickHouse version: 23.11.1.2711

select not(0) + not(0), plus(not(0), not(0)), abs(1) + abs(2);

will produce result: 0 2 3 instead of 2 2 3

In column names we will see next expressions:
column 1: not(plus(0, not(0)))
column 2: plus(not(0), not(0))
column 3: plus(abs(1), abs(2))

Logically, the calculations of the first and second columns should be identical, but this is not the case, column 1 contains wrong formula.

It can be fixed by adding parentheses like (not(0)) + not(0), it will produce right formula: plus(not(0), not(0))

### PR DESCRIPTION
**Pull request by evillique**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix unary operator `NOT` parsing when followed by round braces, now it will be interpreted as function `not`. Closes https://github.com/ClickHouse/ClickHouse/issues/57696

### CODE REVIEW

**Comment by robot-clickhouse-ci-2** [comment]
*This is an automated comment for commit fc8656ee9ea27cc486caec79adee2dc8adca2870 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57713/fc8656ee9ea27cc486caec79adee2dc8adca2870/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7153969176">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57713/fc8656ee9ea27cc486caec79adee2dc8adca2870/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — APPROVED** [review]

**Comment by evillique** [comment]
Tests:
- Integration tests (release) [4/4]: https://github.com/ClickHouse/ClickHouse/issues/57651

File: tests/queries/0_stateless/02920_unary_operators_functions.sql [hunk 1]
```diff
@@ -0,0 +1 @@
+SELECT NOT (0) + NOT (0);
```
Comment (azat) [inline tests/queries/0_stateless/02920_unary_operators_functions.sql:1]: I've came across this because the behavior for some queries changed:

```sql
# upstream
SELECT NOT (3-1) = 1
-- SELECT (NOT (3 - 1)) = 1
0

# 23.11
SELECT NOT (3-1) = 1
-- SELECT NOT ((3 - 1) = 1)
1
```

And MySQL also prints 1 - https://sqlfiddle.com/mysql/online-compiler?id=09bbe665-6e2b-4089-9c78-6ff07f457d50

This particular query is invalid for MySQL, but it looks like `not` is "greedy" there.

Any comments on this?
