### PR TITLE
Fix inconsistent behaviour of GROUP BY constant on empty set

### LINKED ISSUE #6842: Inconsistent behaviour of GROUP BY constant on empty set
**Describe the bug or unexpected behaviour**
```
SELECT 
    1 AS a, 
    count()
FROM numbers(10)
WHERE 0
GROUP BY a

┌─a─┬─count()─┐
│ 1 │       0 │
└───┴─────────┘
```

While
```
SELECT 
    materialize(1) AS a, 
    count()
FROM numbers(10)
WHERE 0
GROUP BY a

Ok.

0 rows in set.
```

This issue was found by Yurii Galitsky (@duremar).

### PR DESCRIPTION
**Pull request by kssenii**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix inconsistent behaviour of GROUP BY constant on empty set. Closes https://github.com/ClickHouse/ClickHouse/issues/6842.

### CODE REVIEW

File: src/Interpreters/ActionsDAG.cpp [hunk 1]
```diff
@@ -219,6 +219,9 @@ const ActionsDAG::Node & ActionsDAG::addFunction(
             column = node.function_base->getConstantResultForNonConstArguments(arguments, node.result_type);
         }
 
+        if (all_const && column && !isColumnConst(*column) && column->size() <= 1)
+            column = ColumnConst::create(std::move(column), column->size());
```
Comment (kssenii) [inline src/Interpreters/ActionsDAG.cpp:223]: In order to be consistent, it needs to be removed here in `analyzeAggregation`:
https://github.com/ClickHouse/ClickHouse/blob/e8407dc930ee7e2c6c7891b4c91a94ab93fb707b/src/Interpreters/ExpressionAnalyzer.cpp#L252-L261
And in order to be removed - a non-null column needs to be added here:
https://github.com/ClickHouse/ClickHouse/blob/e8407dc930ee7e2c6c7891b4c91a94ab93fb707b/src/Interpreters/ActionsVisitor.cpp#L1061
It will be not null and added in this line only if it is columnConst:
https://github.com/ClickHouse/ClickHouse/blob/970af529a09082419d4eee74097c927922ec419d/src/Interpreters/ActionsDAG.cpp#L223-L233
It also works if casting to `columnConst` in case result column is size 1 in `IFunction::execute` and seems it is also ok - may be it will be better to cast there?

**Comment by kssenii** [comment]
> Functional stateless tests (ANTLR debug)

:(
```
01925_test_group_by_const_consistency:                                  [ FAIL ] 3.58 sec. - return code 62
 <Error> ClickHouseLexer: Lexer error: token recognition error at: '　'
 <Error> executeQuery: Code: 62, e.displayText() = DB::Exception: Can't recognize input: token recognition error at: '　'
 (in query: SELECT 1 as a, count() FROM numbers(10) WHERE 0 GROUP BY a;)
```

**Comment by alexey-milovidov** [comment]
As long as it is only ANTLR related error, I don't care.

**Comment by alexey-milovidov** [comment]
@kssenii 

```
SELECT 1 as a, count() FROM numbers(10) WHERE 0 GROUP BY a;

┌─a─┬─count()─┐
│ 1 │       0 │
└───┴─────────┘
```

Does not look like correct result.

Compare with:

```
SELECT number > number - 1 as a, count() FROM numbers(10) WHERE 0 GROUP BY a;
```

**Comment by kssenii** [comment]
:eyes: :eyes: :eyes:
```
2021-07-03 12:26:20 01602_max_distributed_connections:                                      [ FAIL ] - having stderror:
2021-07-03 12:26:20 Code: 210. DB::NetException: Connection reset by peer, while reading from socket ([::1]:9000)
2021-07-03 12:26:20 
2021-07-03 12:26:20 
2021-07-03 12:26:20 Database: test_ikv62t
2021-07-03 12:26:20 Server does not respond to health check
2021-07-03 12:26:20 
2021-07-03 12:26:20 Having 2 errors! 200 tests passed. 15 tests skipped. 170.60 s elapsed (ForkPoolWorker-6).
2021-07-03 12:26:20 Break tests execution
```

**Comment by kssenii** [comment]
@Mergifyio update

**Review by alexey-milovidov — APPROVED** [review]
