### PR TITLE
hide credentails for datalake catalog

### LINKED ISSUE #79897: `SHOW CREATE DATABASE` exposes storage secret key for DataLakeCatalog engine (should be masked)
### Describe what's wrong

`SHOW CREATE DATABASE` exposes storage secret key for DataLakeCatalog engine, should be masked.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
SHOW CREATE DATABASE datalake
FORMAT TabSeparated
```

`
CREATE DATABASE datalake\nENGINE = DataLakeCatalog(\'http://catalog:8181\', \'admin\', \'password\')\nSETTINGS catalog_type = \'rest\', storage_endpoint = \'http://minio:9000/warehouse\', warehouse = \'s3://bucket1/\'
`

### Expected behavior

Output with hidden:
`
CREATE DATABASE datalake\nENGINE = DataLakeCatalog(\'http://catalog:8181\', \'admin\', \'[HIDDEN]\')\nSETTINGS catalog_type = \'rest\', storage_endpoint = \'http://minio:9000/warehouse\', warehouse = \'s3://bucket1/\'
`

### Error message and/or stacktrace

_No response_

### Additional context

```sql
SELECT *
FROM system.server_settings
WHERE name = 'display_secrets_in_show_and_select'
FORMAT Vertical
```

```
Row 1:
──────
name:                       display_secrets_in_show_and_select
value:                      0
default:                    0
changed:                    0
description:                
    Enables or disables showing secrets in `SHOW` and `SELECT` queries for tables, databases, table functions, and dictionaries.

    User wishing to see secrets must also have
    [`format_display_secrets_in_show_and_select` format setting](../settings/formats#format_display_secrets_in_show_and_select)
    turned on and a
    [`displaySecretsInShowAndSelect`](/sql-reference/statements/grant#displaysecretsinshowandselect) privilege.

    Possible values:

    - `0` — Disabled.
    - `1` — Enabled.
    
type:                       Bool
changeable_without_restart: No
is_obsolete:                0
```

### PR DESCRIPTION
**Pull request by hanfei1991**
fix https://github.com/ClickHouse/ClickHouse/issues/79897
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Hide password for query `CREATE DATABASE datalake ENGINE = DataLakeCatalog(\'http://catalog:8181\', \'admin\', \'password\')`

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Parsers/FunctionSecretArgumentsFinder.h [hunk 1]
```diff
@@ -623,7 +623,7 @@ class FunctionSecretArgumentsFinder
             /// PostgreSQL('host:port', 'database', 'user', 'password')
             findMySQLDatabaseSecretArguments();
         }
-        else if (engine_name == "S3")
+        else if (engine_name == "S3" || engine_name == "DataLakeCatalog")
         {
             /// S3('url', 'access_key_id', 'secret_access_key')
             findS3DatabaseSecretArguments();
```
Comment (nikitamikhaylov) [inline src/Parsers/FunctionSecretArgumentsFinder.h:629]: So it is not a `S3` database secret anymore :)

Comment (hanfei1991) [reply src/Parsers/FunctionSecretArgumentsFinder.h:629]: yes. but `DataLakeCatalog` should (and will) support azure as well. So it's only a hot-fix

Comment (vitlibar) [reply src/Parsers/FunctionSecretArgumentsFinder.h:629]: Probably it's better to create another function like `findS3DatabaseSecretArguments()` or rename it.

Comment (hanfei1991) [reply src/Parsers/FunctionSecretArgumentsFinder.h:629]: created a new function and left comments, PTAL

**Review by vitlibar — APPROVED** [review]

**Comment by hanfei1991** [comment]
flaky test https://github.com/ClickHouse/ClickHouse/issues/75876
