### PR TITLE
Fix configuration merge for nodes with substitution attributes

### LINKED ISSUE #56537: Configuration overlay is not working as expected
**Describe what's wrong**

```
root@f421713f:/etc/clickhouse-server/config.d# grep -A2 backup_thread *
100-config.yaml:backup_threads:
100-config.yaml-  '@from_env': CONFIG_BACKUP_THREADS
100-config.yaml-cache_size_to_ram_max_ratio:
--
200-another-config.yaml:backup_threads: 128
200-another-config.yaml-replica_group_name: backup
root@f421713f:/etc/clickhouse-server/config.d# env | grep BACKUP_THREADS
CONFIG_BACKUP_THREADS=24
```

```
root@f421713f:/etc/clickhouse-server/config.d# cat /var/lib/clickhouse/preprocessed_configs/config.xml | grep backup_threads
    <backup_threads>12824</backup_threads>
```

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Expected behavior**

Value from a configuration file with higher precedence (assuming they are sorted lexicographically) should be applied, i.e. `backup_threads` should equal `128` instead of `12824`.

### PR DESCRIPTION
**Pull request by thevar1able**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix unexpected configuration value concatenation in case of overriding an entry having a substitution (`from_env`/`from_zk`/`incl`) https://github.com/ClickHouse/ClickHouse/issues/56537

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 9483d95d67dc7696be84e3872cd1cb18e10fe640 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56694/9483d95d67dc7696be84e3872cd1cb18e10fe640/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6854436924">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56694/9483d95d67dc7696be84e3872cd1cb18e10fe640/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by evillique — APPROVED** [review]

File: src/Common/Config/ConfigProcessor.cpp [hunk 1]
```diff
@@ -535,6 +544,9 @@ void ConfigProcessor::doIncludesRecursive(
 
     if (attr_nodes["from_env"]) /// we have env subst
     {
+        if (node->hasChildNodes()) /// only allow substitution for nodes with no value
+            throw Poco::Exception("Element <" + node->nodeName() + "> has value, can't process from_env substitution");
```
Comment (azat) [inline src/Common/Config/ConfigProcessor.cpp:548]: I used this behavior before (define default value in the xml and override it via env) for development, AFAICS the bug that described in https://github.com/ClickHouse/ClickHouse/issues/56537 is fixed by removing `SUBSTITUTION_ATTRS` from source node during merging before?
