### PR TITLE
Track memory consumed by Roaring Bitmaps.

### LINKED ISSUE #26555: Memory tracking issue in groupBitmapState ?
That query uses about 10Gb of RAM, should fail with that setting.
In practice it can go OOM, and clickhouse memory tracker doesn't know about that:

```
SET max_threads = 8, max_memory_usage = '3G';
CREATE TABLE oom_issue ENGINE = AggregatingMergeTree ORDER BY n AS　SELECT cityHash64(rand() % 1000) as n, groupBitmapState(number) FROM numbers_mt(2000000000) GROUP BY n;
```

```
[laptop-5591] 2021.07.20 13:22:45.739115 [ 272424 ] {cda8ab45-5c7c-47de-83eb-14ec6d0fdb4c} <Debug> MemoryTracker: Peak memory usage (for query): 6.53 MiB.
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Memory consumed by bitmap aggregate functions now is taken into account for memory limits. This closes #26555.

Note: it is implemented in quite hacky way: C does not require implicit function declarations; it also depends on linking order.

### CODE REVIEW

File: src/Interpreters/Aggregator.cpp [hunk 1]
```diff
@@ -1193,6 +1193,9 @@ bool Aggregator::checkLimits(size_t result_size, bool & no_more_keys) const
         }
     }
 
+    /// Some aggregate functions cannot throw exceptions on allocations (e.g. from C malloc)
+    /// but still tracks memory. Check it here.
+    CurrentMemoryTracker::check();
```
Comment (alexey-milovidov) [inline src/Interpreters/Aggregator.cpp:1198]: Note: memory are not checked while deserializing aggregation states from file or network.

File: contrib/croaring-cmake/CMakeLists.txt [hunk 2]
```diff
@@ -24,3 +24,11 @@ add_library(roaring ${SRCS})
 target_include_directories(roaring PRIVATE "${LIBRARY_DIR}/include/roaring")
 target_include_directories(roaring SYSTEM BEFORE PUBLIC "${LIBRARY_DIR}/include")
 target_include_directories(roaring SYSTEM BEFORE PUBLIC "${LIBRARY_DIR}/cpp")
+
+target_compile_definitions(roaring PRIVATE
```
Comment (alexey-milovidov) [inline contrib/croaring-cmake/CMakeLists.txt:28]: This is the main part of the fix.

File: src/Interpreters/Aggregator.cpp [hunk 3]
```diff
@@ -1193,6 +1193,9 @@ bool Aggregator::checkLimits(size_t result_size, bool & no_more_keys) const
         }
     }
 
+    /// Some aggregate functions cannot throw exceptions on allocations (e.g. from C malloc)
```
Comment (amosbird) [inline src/Interpreters/Aggregator.cpp:1196]: Is it ok to just return a `nullptr` when memory limit is exceeded?

Comment (alexey-milovidov) [reply src/Interpreters/Aggregator.cpp:1196]: Generally I won't do it, many libraries are not ready (they will either segfault on nullptr dereference or abort).
Maybe Roaring Bitmap is ok but I don't want to "surprise" it.

E.g. I expect it may have memory leak if one of subsequent allocations return nullptr.

Comment (alexey-milovidov) [reply src/Interpreters/Aggregator.cpp:1196]: PS. You might noticed, we have removed throwing from operator new.

**Comment by alexey-milovidov** [comment]
Ok, all tests passed...

**Comment by alexey-milovidov** [comment]
@mergifyio update

**Comment by Algunenano** [comment]
@alexey-milovidov The test does not work with split libraries. The query uses ~11 GB and then the python client uses ~15 GB of memory, until it works (so the test fails).
If this is only going to work with static libraries, can we disable it somehow (similar to some test being disabled under the sanitizers)?

**Comment by alexey-milovidov** [comment]
I did not find a section in skip_list for shared builds.
But we don't test shared builds in CI, so it does not matter.

**Comment by Algunenano** [comment]
> But we don't test shared builds in CI, so it does not matter.

The wiki (https://clickhouse.tech/docs/en/development/build/) basically recommends the split build for development, which means that anyone using the development build won't be able to pass the tests. IMO this should either work or be disabled.

Note that it is the only stateless test that won't work witha a split build. If it's going to always fail, why recommend (or even support at all) the split build?

**Comment by alexey-milovidov** [comment]
In fact I don't recomment split build for development.

There are too many issues:
- cannot scp binary to server;
- segfault during rebuild if binary is run;
- cannot run integration tests;
- cannot run in built binary in Docker without hodgepodges.

But if split build is important for you, maybe you can convert this test to .sh test that will check system.build_options and succeed unconditionally if it is split build?

**Comment by Algunenano** [comment]
> But if split build is important for you, maybe you can convert this test to .sh test that will check system.build_options and succeed unconditionally if it is split build?

Sure, I'll give it a try. Note that the only reason I'm using a split build is because the wiki implies that is the most convenient for development, so I'll add that information to the wiki too. Really useful. Thanks!
