### PR TITLE
Throw on query timeout in ZooKeeperRetries

### LINKED ISSUE #60882: Logical error: 'No responses set for MultiRead'.
https://s3.amazonaws.com/clickhouse-test-reports/60649/7dfe8afa76806449aed35faaff1b0e7dbe87849b/ast_fuzzer__ubsan_.html

```
2024.03.05 16:01:09.812108 [ 1673 ] {ae173055-e7c8-4d6f-bd1a-6d2ca2ae26c9} <Fatal> : Logical error: 'No responses set for MultiRead'.
2024.03.05 16:01:09.812650 [ 2243 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.03.05 16:01:09.812684 [ 2243 ] {} <Fatal> BaseDaemon: (version 24.3.1.1, build id: 4A174C7D6C0FCCCD5A6E8AED02703FA2CD915C81, git hash: 1dfa70292a92cd2be1f61b265455b09194986547) (from thread 1673) Received signal 6
2024.03.05 16:01:09.812694 [ 2243 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2024.03.05 16:01:09.812701 [ 2243 ] {} <Fatal> BaseDaemon: 
2024.03.05 16:01:09.812713 [ 2243 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fd0eb4f09fc 0x00007fd0eb49c476 0x00007fd0eb4827f3 0x00005614bc665ea8 0x00005614bc666df5 0x00005614b0155eae 0x00005614c67c741f 0x00005614c67b085f 0x00005614cbba4834 0x00005614cbba3ff7 0x00005614cbbd0310 0x00005614cbbc007b 0x00005614cbbbd8f7 0x00005614cbbbd50a 0x00005614cbbd5d91 0x00005614bc763c7b 0x00005614bc7689ca 0x00007fd0eb4eeac3 0x00007fd0eb580850
2024.03.05 16:01:09.812723 [ 2243 ] {} <Fatal> BaseDaemon: ########################################
2024.03.05 16:01:09.812760 [ 2243 ] {} <Fatal> BaseDaemon: (version 24.3.1.1, build id: 4A174C7D6C0FCCCD5A6E8AED02703FA2CD915C81, git hash: 1dfa70292a92cd2be1f61b265455b09194986547) (from thread 1673) (query_id: ae173055-e7c8-4d6f-bd1a-6d2ca2ae26c9) (query: SELECT path,  23, name FROM system.zookeeper WHERE path = '/keeper' ORDER BY name ASC SETTINGS insert_keeper_retry_initial_backoff_ms = 1, insert_keeper_retry_max_backoff_ms = 65535, insert_keeper_fault_injection_probability = 3.4028234663852886e38, insert_keeper_fault_injection_seed = 1025, log_comment = '') Received signal Aborted (6)
2024.03.05 16:01:09.812773 [ 2243 ] {} <Fatal> BaseDaemon: 
2024.03.05 16:01:09.812783 [ 2243 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fd0eb4f09fc 0x00007fd0eb49c476 0x00007fd0eb4827f3 0x00005614bc665ea8 0x00005614bc666df5 0x00005614b0155eae 0x00005614c67c741f 0x00005614c67b085f 0x00005614cbba4834 0x00005614cbba3ff7 0x00005614cbbd0310 0x00005614cbbc007b 0x00005614cbbbd8f7 0x00005614cbbbd50a 0x00005614cbbd5d91 0x00005614bc763c7b 0x00005614bc7689ca 0x00007fd0eb4eeac3 0x00007fd0eb580850
2024.03.05 16:01:09.812800 [ 2243 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007fd0eb4f09fc
2024.03.05 16:01:09.812810 [ 2243 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00007fd0eb49c476
2024.03.05 16:01:09.812819 [ 2243 ] {} <Fatal> BaseDaemon: 5. ? @ 0x00007fd0eb4827f3
2024.03.05 16:01:09.830351 [ 2243 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:43: DB::abortOnFailedAssertion(String const&) @ 0x0000000025747ea8
2024.03.05 16:01:09.846856 [ 2243 ] {} <Fatal> BaseDaemon: 7.0. inlined from ./build_docker/./src/Common/Exception.cpp:63: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
2024.03.05 16:01:09.846950 [ 2243 ] {} <Fatal> BaseDaemon: 7. ./build_docker/./src/Common/Exception.cpp:100: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000025748df5
2024.03.05 16:01:10.783304 [ 2243 ] {} <Fatal> BaseDaemon: 8. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x0000000019237eae
2024.03.05 16:01:10.847633 [ 2243 ] {} <Fatal> BaseDaemon: 9.0. inlined from ./src/Common/ZooKeeper/ZooKeeper.h:133: operator()<std::monostate>
2024.03.05 16:01:10.847705 [ 2243 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.03.05 16:01:10.847721 [ 2243 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./contrib/llvm-project/libcxx/include/variant:668: decltype(auto) std::__variant_detail::__visitation::__variant::__value_visitor<zkutil::MultiReadResponses<Coordination::ListResponse, true>::operator[](unsigned long)::'lambda'<typename $T>($T&)>::operator()[abi:v15000]<std::__variant_detail::__alt<0ul, std::monostate>&>(std::__variant_detail::__alt<0ul, std::monostate>&) const
2024.03.05 16:01:10.847729 [ 2243 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.03.05 16:01:10.847741 [ 2243 ] {} <Fatal> BaseDaemon: 9. ./contrib/llvm-project/libcxx/include/variant:548: decltype(auto) std::__variant_detail::__visitation::__base::__dispatcher<0ul>::__dispatch[abi:v15000]<std::__variant_detail::__visitation::__variant::__value_visitor<zkutil::MultiReadResponses<Coordination::ListResponse, true>::operator[](unsigned long)::'lambda'<typename $T>($T&)>&&, std::__variant_detail::__base<(std::__variant_detail::_Trait)1, std::monostate, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>, zkutil::MultiReadResponses<Coordination::ListResponse, true>::ResponsesWithFutures>&>($T, std::__variant_detail::__base<(std::__variant_detail::_Trait)1, std::monostate, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>>, zkutil::MultiReadResponses<Coordination::ListResponse, true>::ResponsesWithFutures>&) @ 0x000000002f8a941f
2024.03.05 16:01:10.895269 [ 2243 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Storages/System/StorageSystemZooKeeper.cpp:0: DB::SystemZooKeeperSource::generate() @ 0x000000002f89285f
2024.03.05 16:01:10.905149 [ 2243 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./src/Processors/Chunk.h:90: DB::Chunk::hasRows() const
2024.03.05 16:01:10.905213 [ 2243 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./src/Processors/Chunk.h:92: DB::Chunk::empty() const
2024.03.05 16:01:10.905236 [ 2243 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./src/Processors/Chunk.h:93: DB::Chunk::operator bool() const
2024.03.05 16:01:10.905262 [ 2243 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Processors/ISource.cpp:140: DB::ISource::tryGenerate() @ 0x0000000034c86834
2024.03.05 16:01:10.914215 [ 2243 ] {} <Fatal> BaseDaemon: 12.0. inlined from ./contrib/llvm-project/libcxx/include/optional:344: std::__optional_storage_base<DB::Chunk, false>::has_value[abi:v15000]() const
2024.03.05 16:01:10.914267 [ 2243 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./contrib/llvm-project/libcxx/include/optional:998: std::optional<DB::Chunk>::operator bool[abi:v15000]() const
2024.03.05 16:01:10.914301 [ 2243 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x0000000034c85ff7
2024.03.05 16:01:10.918097 [ 2243 ] {} <Fatal> BaseDaemon: 13.0. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:50: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2024.03.05 16:01:10.918140 [ 2243 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:95: DB::ExecutionThreadContext::executeTask() @ 0x0000000034cb2310
2024.03.05 16:01:10.931060 [ 2243 ] {} <Fatal> BaseDaemon: 14.0. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:273: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*)
2024.03.05 16:01:10.931116 [ 2243 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:239: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x0000000034ca207b
2024.03.05 16:01:10.942657 [ 2243 ] {} <Fatal> BaseDaemon: 15.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
2024.03.05 16:01:10.942714 [ 2243 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:412: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000034c9f8f7
2024.03.05 16:01:10.955478 [ 2243 ] {} <Fatal> BaseDaemon: 16.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: std::unique_ptr<DB::ExecutingGraph, std::default_delete<DB::ExecutingGraph>>::operator->[abi:v15000]() const
2024.03.05 16:01:10.955535 [ 2243 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:114: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000034c9f50a
2024.03.05 16:01:10.968706 [ 2243 ] {} <Fatal> BaseDaemon: 17.0. inlined from ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:0: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
2024.03.05 16:01:10.968774 [ 2243 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109: operator()
2024.03.05 16:01:10.968797 [ 2243 ] {} <Fatal> BaseDaemon: 17.2. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.03.05 16:01:10.968823 [ 2243 ] {} <Fatal> BaseDaemon: 17.3. inlined from ./contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<>)
2024.03.05 16:01:10.968845 [ 2243 ] {} <Fatal> BaseDaemon: 17.4. inlined from ./contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
2024.03.05 16:01:10.968864 [ 2243 ] {} <Fatal> BaseDaemon: 17.5. inlined from ./src/Common/ThreadPool.h:223: operator()
2024.03.05 16:01:10.968879 [ 2243 ] {} <Fatal> BaseDaemon: 17.6. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: ?
2024.03.05 16:01:10.968897 [ 2243 ] {} <Fatal> BaseDaemon: 17.7. inlined from ./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: ?
2024.03.05 16:01:10.968912 [ 2243 ] {} <Fatal> BaseDaemon: 17.8. inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:235: ?
2024.03.05 16:01:10.968930 [ 2243 ] {} <Fatal> BaseDaemon: 17. ./contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000034cb7d91
2024.03.05 16:01:10.978124 [ 2243 ] {} <Fatal> BaseDaemon: 18.0. inlined from ./base/base/../base/wide_integer_impl.h:810: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.03.05 16:01:10.978163 [ 2243 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./base/base/../base/wide_integer_impl.h:1483: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
2024.03.05 16:01:10.978183 [ 2243 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./base/base/../base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
2024.03.05 16:01:10.978200 [ 2243 ] {} <Fatal> BaseDaemon: 18.3. inlined from ./src/Common/OpenTelemetryTraceContext.h:65: DB::OpenTelemetry::Span::isTraceEnabled() const
2024.03.05 16:01:10.978220 [ 2243 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./src/Common/ThreadPool.cpp:457: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x0000000025845c7b
2024.03.05 16:01:10.989734 [ 2243 ] {} <Fatal> BaseDaemon: 19.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>::reset[abi:v15000](std::__thread_struct*)
2024.03.05 16:01:10.989764 [ 2243 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2024.03.05 16:01:10.989781 [ 2243 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
2024.03.05 16:01:10.989800 [ 2243 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./contrib/llvm-project/libcxx/include/tuple:538: ~tuple
2024.03.05 16:01:10.989827 [ 2243 ] {} <Fatal> BaseDaemon: 19.4. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*) const
2024.03.05 16:01:10.989853 [ 2243 ] {} <Fatal> BaseDaemon: 19.5. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
2024.03.05 16:01:10.989872 [ 2243 ] {} <Fatal> BaseDaemon: 19.6. inlined from ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2024.03.05 16:01:10.989890 [ 2243 ] {} <Fatal> BaseDaemon: 19. ./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000002584a9ca
2024.03.05 16:01:10.989911 [ 2243 ] {} <Fatal> BaseDaemon: 20. ? @ 0x00007fd0eb4eeac3
2024.03.05 16:01:10.989926 [ 2243 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00007fd0eb580850
2024.03.05 16:01:10.989946 [ 2243 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2024.03.05 16:01:12.124374 [ 2243 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2024.03.05 16:01:12.124565 [ 2243 ] {} <Fatal> BaseDaemon: Changed settings: max_insert_threads = 1, receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, group_by_two_level_threshold = 2, distributed_aggregation_memory_efficient = true, max_parallel_replicas = 2, allow_experimental_parallel_reading_from_replicas = 0, log_queries = true, table_function_remote_max_addresses = 200, joined_subquery_requires_alias = false, allow_experimental_analyzer = true, max_bytes_before_external_group_by = 16, max_execution_time = 10., max_memory_usage = 10000000000, log_comment = '', send_logs_level = 'fatal', optimize_aggregation_in_order = true, allow_introspection_functions = true, check_query_single_value_result = true, optimize_monotonous_functions_in_order_by = false, allow_deprecated_syntax_for_merge_tree = true, insert_keeper_retry_initial_backoff_ms = 1, insert_keeper_retry_max_backoff_ms = 65535, insert_keeper_fault_injection_probability = 3.4028234663852886e38, insert_keeper_fault_injection_seed = 1025
2024.03.05 16:01:46.968878 [ 156 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/60882 and makes it better in general

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 45c4a3a235bac763a8100dc23a3961905b0bda85 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/60922/45c4a3a235bac763a8100dc23a3961905b0bda85/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Common/ZooKeeper/ZooKeeperRetries.h [hunk 1]
```diff
@@ -221,7 +220,8 @@ class ZooKeeperRetriesControl
         }
 
         if (process_list_element && !process_list_element->checkTimeLimitSoft())
-            return false;
+            throw Exception(
+                ErrorCodes::QUERY_WAS_CANCELLED, "Query was either killed or timeout was exceeded (defined by max_exceution_time)");
```
Comment (antonio2368) [inline src/Common/ZooKeeper/ZooKeeperRetries.h:224]:
```suggestion
                ErrorCodes::QUERY_WAS_CANCELLED, "Query was either killed or timeout was exceeded (defined by max_execution_time)");
```

File: src/Common/ZooKeeper/ZooKeeperRetries.h [hunk 2]
```diff
@@ -221,7 +220,8 @@ class ZooKeeperRetriesControl
         }
 
         if (process_list_element && !process_list_element->checkTimeLimitSoft())
-            return false;
+            throw Exception(
```
Comment (Algunenano) [inline src/Common/ZooKeeper/ZooKeeperRetries.h:223]: I would suggest introducing a new function instead of `checkTimeLimitSoft()` that throws in the cases it's ok to throw (KILL or timeout with mode THROW). Otherwise we'd be throwing here with mode BREAK, which is kinda unexpected. It also gives us the option to say exactly what happened with a clear error message

Comment (antonio2368) [reply src/Common/ZooKeeper/ZooKeeperRetries.h:223]: > that throws in the cases it's ok to throw (KILL or timeout with mode THROW)

You described `checkTimeLimit` which already exists.
But isn't the point here that we want to ignore timeout mode and throw in every case?

Comment (antonio2368) [reply src/Common/ZooKeeper/ZooKeeperRetries.h:223]: Maybe more explicit would be adding function which checks if the limit is exceeded? there already is `isKilled`

Comment (Algunenano) [reply src/Common/ZooKeeper/ZooKeeperRetries.h:223]: > You described checkTimeLimit which already exists.

Seems like it is. Let's use it instead.

> But isn't the point here that we want to ignore timeout mode and throw in every case?

No. If the user requested `BREAK` we don't want to throw as it halts the execution (which they've explicitly requested not to do). IMO it's better to continue running in that situation, even if timeouts are not respected.

Comment (antonio2368) [reply src/Common/ZooKeeper/ZooKeeperRetries.h:223]: we will still have the same problem
For example in https://github.com/ClickHouse/ClickHouse/issues/60882
if `BREAK` is requested, execution will continue and a `LOGICAL_ERROR` will be thrown.
My thought process was to prefer a better exception even though it ignores timeout mode than throw `LOGICAL_ERROR`.

Comment (Algunenano) [reply src/Common/ZooKeeper/ZooKeeperRetries.h:223]: I mean to continue on BREAK (no check), that is keep the loop going and sending keeper requests as if there was no timeout.

Comment (antonio2368) [reply src/Common/ZooKeeper/ZooKeeperRetries.h:223]: That makes sense

**Review by Algunenano — APPROVED** [review]
