### PR TITLE
Fix assert in SpanHolder::finish() with fibers attempt 2

### LINKED ISSUE #49185: Abort in `OpenTelemetry::SpanHolder::finish()`
https://s3.amazonaws.com/clickhouse-test-reports/0/80c1a4ed88fad4e1a2679d19920eaa3ff63699ea/stateless_tests__debug__[1/5].html

Looks like "terminate called for uncaught exception", but it may be an assertion as well:
```
2023.04.26 06:58:46.054529 [ 2883 ] {} <Fatal> BaseDaemon: ########################################
2023.04.26 06:58:46.054949 [ 2883 ] {} <Fatal> BaseDaemon: (version 23.4.1.1 (official build), build id: E3E0936B36CD53B684EE940C52D363CE775999A6) (from thread 1412) (query_id: b4c077e1-1807-463c-aaad-7d4959637aa2) (query: kill query where query_id = 'test_pzkratru_test_02585_query_to_kill_id_1' sync) Received signal Aborted (6)
2023.04.26 06:58:46.055147 [ 2883 ] {} <Fatal> BaseDaemon: 
2023.04.26 06:58:46.055344 [ 2883 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f7207c6300b 0x7f7207c42859 0x7f7207c42729 0x7f7207c53fd6 0x22eb0ca4 0x22eb0eb9 0x2d2ed7a6 0x2d0f47ea 0x2d12325d 0x2d1230fe 0x2a3b45c1 0x2a3b3fb6 0x2a3d1682 0x2a3d0398 0x2a3d02c8 0x2a3d0288 0x2a3d01be 0x2a3d003d
2023.04.26 06:58:46.055570 [ 2883 ] {} <Fatal> BaseDaemon: 4. gsignal @ 0x7f7207c6300b in ?
2023.04.26 06:58:46.055756 [ 2883 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f7207c42859 in ?
2023.04.26 06:58:46.055895 [ 2883 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f7207c42729 in ?
2023.04.26 06:58:46.056115 [ 2883 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f7207c53fd6 in ?
2023.04.26 06:58:46.134479 [ 2883 ] {} <Fatal> BaseDaemon: 8. /build/src/Common/OpenTelemetryTraceContext.cpp:0: DB::OpenTelemetry::SpanHolder::finish() @ 0x22eb0ca4 in /usr/bin/clickhouse
2023.04.26 06:58:46.233511 [ 2883 ] {} <Fatal> BaseDaemon: 9. /build/src/Common/OpenTelemetryTraceContext.cpp:170: DB::OpenTelemetry::SpanHolder::~SpanHolder() @ 0x22eb0eb9 in /usr/bin/clickhouse
2023.04.26 06:58:46.349611 [ 2883 ] {} <Fatal> BaseDaemon: 10. /build/src/Processors/Executors/PipelineExecutor.cpp:134: DB::PipelineExecutor::execute(unsigned long) @ 0x2d2ed7a6 in /usr/bin/clickhouse
2023.04.26 06:58:46.592244 [ 2883 ] {} <Fatal> BaseDaemon: 11. /build/src/Client/Connection.cpp:869: DB::Connection::sendExternalTablesData(std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>&) @ 0x2d0f47ea in /usr/bin/clickhouse
2023.04.26 06:58:46.792386 [ 2883 ] {} <Fatal> BaseDaemon: 12. /build/src/Client/HedgedConnections.cpp:106: DB::HedgedConnections::sendExternalTablesData(std::vector<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>, std::allocator<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>>>&)::$_2::operator()(DB::HedgedConnections::ReplicaState&) const @ 0x2d12325d in /usr/bin/clickhouse
2023.04.26 06:58:46.980880 [ 2883 ] {} <Fatal> BaseDaemon: 13. /build/src/Client/HedgedConnections.cpp:111: DB::HedgedConnections::sendExternalTablesData(std::vector<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>, std::allocator<std::vector<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>, std::allocator<std::unique_ptr<DB::ExternalTableData, std::default_delete<DB::ExternalTableData>>>>>>&) @ 0x2d1230fe in /usr/bin/clickhouse
2023.04.26 06:58:47.196219 [ 2883 ] {} <Fatal> BaseDaemon: 14. /build/src/QueryPipeline/RemoteQueryExecutor.cpp:701: DB::RemoteQueryExecutor::sendExternalTables() @ 0x2a3b45c1 in /usr/bin/clickhouse
2023.04.26 06:58:47.426912 [ 2883 ] {} <Fatal> BaseDaemon: 15. /build/src/QueryPipeline/RemoteQueryExecutor.cpp:269: DB::RemoteQueryExecutor::sendQueryUnlocked(DB::ClientInfo::QueryKind, std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>) @ 0x2a3b3fb6 in /usr/bin/clickhouse
2023.04.26 06:58:47.507256 [ 2883 ] {} <Fatal> BaseDaemon: 16. /build/src/QueryPipeline/RemoteQueryExecutorReadContext.cpp:39: DB::RemoteQueryExecutorReadContext::Task::run(std::function<void (int, Poco::Timespan, DB::AsyncEventTimeoutType, String const&, unsigned int)>, std::function<void ()>) @ 0x2a3d1682 in /usr/bin/clickhouse
2023.04.26 06:58:47.567867 [ 2883 ] {} <Fatal> BaseDaemon: 17. /build/src/Common/AsyncTaskExecutor.cpp:88: DB::AsyncTaskExecutor::Routine::operator()(boost::context::fiber&&) @ 0x2a3d0398 in /usr/bin/clickhouse
2023.04.26 06:58:47.629997 [ 2883 ] {} <Fatal> BaseDaemon: 18. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::AsyncTaskExecutor::Routine&>()(std::declval<boost::context::fiber>())) std::__invoke[abi:v15000]<DB::AsyncTaskExecutor::Routine&, boost::context::fiber>(DB::AsyncTaskExecutor::Routine&, boost::context::fiber&&) @ 0x2a3d02c8 in /usr/bin/clickhouse
2023.04.26 06:58:47.691781 [ 2883 ] {} <Fatal> BaseDaemon: 19. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:531: std::invoke_result<DB::AsyncTaskExecutor::Routine&, boost::context::fiber>::type std::invoke<DB::AsyncTaskExecutor::Routine&, boost::context::fiber>(DB::AsyncTaskExecutor::Routine&, boost::context::fiber&&) @ 0x2a3d0288 in /usr/bin/clickhouse
2023.04.26 06:58:47.752637 [ 2883 ] {} <Fatal> BaseDaemon: 20. /build/contrib/boost/boost/context/fiber_fcontext.hpp:140: boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>::run(void*) @ 0x2a3d01be in /usr/bin/clickhouse
2023.04.26 06:58:47.814377 [ 2883 ] {} <Fatal> BaseDaemon: 21. /build/contrib/boost/boost/context/fiber_fcontext.hpp:80: void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::AsyncTaskExecutor::Routine>>(boost::context::detail::transfer_t) @ 0x2a3d003d in /usr/bin/clickhouse
2023.04.26 06:58:51.300496 [ 2883 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 2824BEEE901BA995655CF98FC401E68C)
2023.04.26 06:58:54.565147 [ 658 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

May be related to https://github.com/ClickHouse/ClickHouse/pull/47667
cc: @FrankChen021, @nickitat

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix assert in SpanHolder::finish() with fibers. Closes https://github.com/ClickHouse/ClickHouse/issues/49185.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

File: src/Common/AsyncTaskExecutor.h [hunk 1]
```diff
@@ -124,48 +123,6 @@ class AsyncTaskExecutor
     std::unique_ptr<AsyncTask> task;
 };
 
-/// Simple implementation for fiber local variable.
-template <typename T>
-struct FiberLocal
```
Comment (Avogar) [inline src/Common/AsyncTaskExecutor.h:129]: This implementation from previous fix is not good for 2 reasons:
1) It works only when fibers are executed in one thread. But sometimes it can happen that fiber was started in one thread, suspended and resumed in another thread (for example during query cancellation).
2) It doesn't clean instances created for fibers when fiber is destroyed (I just didn't think about it, my fault).

File: src/Common/Fiber.h [hunk 2]
```diff
@@ -4,4 +4,181 @@
...
+        current_fiber_info = FiberInfo{this, &parent_fiber_info};
+        impl = std::move(impl).resume();
+        /// Restore current fiber info.
+        current_fiber_info = parent_fiber_info;
+    }
+
+    /// Set pointer to fiber-specific data, it will be stored in hash-map
+    /// using provided key and cleaned on fiber destructor using provided
+    /// cleanup function.
+    void setLocalData(void * key, void * ptr, CleanUpFn * cleanup_fn)
```
Comment (KochetovNicolai) [inline src/Common/Fiber.h:60]: Need a comment what's key here.

Also probably make `setLocalData/getLocalData` private and available only from FiberLocal

File: src/Common/Fiber.h [hunk 3]
```diff
@@ -4,4 +4,181 @@
...
+    struct CustomCleanUpFn : public Fiber::CleanUpFn
+    {
+        explicit CustomCleanUpFn(void (*fn_)(T*)) : fn(fn_)
+        {
+        }
+
+        void operator()(void * data) override
+        {
+            if (likely(fn != nullptr))
+                fn(static_cast<T *>(data));
```
Comment (KochetovNicolai) [inline src/Common/Fiber.h:124]: Maybe if we want this, we'd better call `delete static_cast<T *>(data);` here (not expect fn will do it)

File: src/Common/Fiber.h [hunk 4]
```diff
@@ -3,5 +3,147 @@
...
+        Fiber * current_fiber = Fiber::getCurrentFiber();
+        if (!current_fiber)
+            return main_instance;
+
+        Fiber::DataPtr & ptr = current_fiber->getLocalData(this);
+        /// Initialize instance on first request.
+        if (!ptr)
+            ptr = std::make_unique<DataWrapperImpl>();
+
+        return dynamic_cast<DataWrapperImpl *>(ptr.get())->impl;
```
Comment (KochetovNicolai) [inline src/Common/Fiber.h:144]: I think we can do `static_cast` here?

File: src/Common/Fiber.h [hunk 5]
```diff
@@ -3,5 +3,147 @@
...
+    }
+
+    T main_instance;
```
Comment (KochetovNicolai) [inline src/Common/Fiber.h:147]: Make it std::optional or unique_ptr maybe

File: src/Common/Fiber.h [hunk 6]
```diff
@@ -3,5 +3,147 @@
...
+class Fiber
+{
+private:
+    using Impl = boost::context::fiber;
+    using FiberPtr = Fiber *;
+    template <typename T> friend class FiberLocal;
+
+public:
+    template< typename StackAlloc, typename Fn>
+    Fiber(StackAlloc && salloc, Fn && fn) : impl(std::allocator_arg_t(), std::forward<StackAlloc>(salloc), RoutineImpl(std::forward<Fn>(fn)))
```
Comment (KochetovNicolai) [inline src/Common/Fiber.h:21]: I am a bit confused about `RoutineImpl` here. Is it needed? And what's happening here?
Looks like we are creating a tmp object and destroying it immediately...

**Review by KochetovNicolai — APPROVED** [review]

File: src/Common/Fiber.h (hunk 4 above)
Comment (Avogar) [reply src/Common/Fiber.h:144]: Sure, I will add it in the next PR.
