### PR TITLE
Fix flaky test_parallel_replicas_failover

### LINKED ISSUE #81499: test_parallel_replicas_failover is flaky
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=81474&sha=24d4607d215fcf8f3afb8283602a0e7a3543ccd7&name_0=PR&name_1=Integration%20tests%20%28aarch64%2C%20distributed%20plan%2C%203%2F4%29

```
        node1.query("SYSTEM FLUSH LOGS")
>       assert (
            node1.query(
                f"SELECT ProfileEvents['DistributedConnectionMissingTable'], ProfileEvents['ParallelReplicasUnavailableCount'] FROM system.query_log WHERE type = 'QueryFinish' AND query_id IN (SELECT query_id FROM system.query_log WHERE current_database = currentDatabase() AND log_comment = '{log_comment}' AND type = 'QueryFinish' AND initial_query_id = query_id)  SETTINGS enable_parallel_replicas=0"
            )
            == "1\t1\n"
        )
E       AssertionError: assert '0\t0\n' == '1\t1\n'
E         - 1	1
E         + 0	0
```

And it fails [pretty frequently](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMjQgSE9VUgogICAgQU5EIChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBzdGFydHNXaXRoKGhlYWRfcmVwbywgJ0NsaWNrSG91c2UvJykpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScpIAogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICd0ZXN0X3BhcmFsbGVsX3JlcGxpY2FzX2ZhaWxvdmVyJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=)

Cc: @devcrafter

### PR DESCRIPTION
**Pull request by devcrafter**
Closes https://github.com/ClickHouse/ClickHouse/issues/81499

After https://github.com/ClickHouse/ClickHouse/pull/80199, query execution can finish before we'll connect to some nodes. It can make some tests flaky

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

File: src/Core/SettingsChangesHistory.cpp [hunk 1]
```diff
@@ -79,6 +79,7 @@ const VersionToSettingsChangesMap & getSettingsChangesHistory()
             {"use_skip_indexes_if_final", 0, 1, "Change in default value of setting"},
             {"use_skip_indexes_if_final_exact_mode", 0, 1, "Change in default value of setting"},
             {"min_outstreams_per_resize_after_split", 0, 24, "New setting."},
+            {"parallel_replicas_wait_for_unused_replica", false, false, "New setting"},
```
Comment (azat) [inline src/Core/SettingsChangesHistory.cpp]:
```suggestion
            {"parallel_replicas_wait_for_unused_replicas", false, false, "New setting"},
```

File: src/Core/Settings.cpp [hunk 2]
```diff
@@ -6430,6 +6430,9 @@ Use local pipeline during distributed INSERT SELECT with parallel replicas
 )", BETA) \
     DECLARE(Milliseconds, parallel_replicas_connect_timeout_ms, 300, R"(
 The timeout in milliseconds for connecting to a remote replica during query execution with parallel replicas. If the timeout is expired, the corresponding replicas is not used for query execution
+)", BETA) \
+    DECLARE(Bool, parallel_replicas_wait_for_unused_replicas, false, R"(
```
Comment (azat) [inline src/Core/Settings.cpp]: Do you think that it worth to add a setting just to fix the test? Maybe we can remove this assertion from the test instead?

Comment (devcrafter) [reply src/Core/Settings.cpp]: We need to test some functionality, and its execution can't be reach reliably if we cancel `RemoteSource` processors as soon as all read tasks assigned. The setting allows reaching desired code path reliably.

Agree, usage of settings for this purpose can be excessive. We can use fail point mechanism with the same purpose (i.e., as setting for testing) which is not exactly fail point but since it's for testing - should be fine.

Comment (azat) [reply src/Core/Settings.cpp]: >We need to test some functionality, and its execution can't be reach reliably if we cancel RemoteSource processors as soon as all read tasks assigned. The setting allows reaching desired code path reliably.

Maybe we can tune parallel replicas that way that it will reach all servers? Either by decreasing `parallel_replicas_mark_segment_size` and some generic sleep, like `sleep_in_send_data_ms`/`sleep_after_receiving_query_ms`, or if this is not enough maybe some generic sleep that will be useful for PR. What do you think?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by devcrafter** [comment]
Failures in integration tests are unrelated
