### PR TITLE
Fix test_peak_memory_usage flakiness by making logging of peak memory more accurate

### LINKED ISSUE #90840: Flaky test: test_peak_memory_usage/test.py::test_clickhouse_client_max_peak_memory_usage_distributed
### Highlights
- https://github.com/ClickHouse/ClickHouse/issues/90840#issuecomment-3662483887

### Report

Failure reason: assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
[CI report: [Integration tests (amd_binary, 2/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90717&sha=2d993904c4f95324ba1379a2c350943ce038502c&name_0=PR&name_1=Integration%20tests%20%28amd_binary%2C%202%2F5%29)]
[cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICd0ZXN0X3BlYWtfbWVtb3J5X3VzYWdlL3Rlc3QucHk6OnRlc3RfY2xpY2tob3VzZV9jbGllbnRfbWF4X3BlYWtfbWVtb3J5X3VzYWdlX2Rpc3RyaWJ1dGVkJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnSW50ZWdyYXRpb24gdGVzdHMgKGFtZF9iaW5hcnksIDIvNSknCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJykKICAgIEFORCAoKGhlYWRfcmVmID0gJ21hc3RlcicgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwKSBPUiBwdWxsX3JlcXVlc3RfbnVtYmVyICE9IDApCkdST1VQIEJZIGRheQpPUkRFUiBCWSBkYXkgREVTQwo=)

Test output:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAIL [test_peak_memory_usage/test.py::test_clickhouse_client_max_peak_memory_usage_distributed]
  | File: test_peak_memory_usage/test.py:101 - in test_clickhouse_client_max_peak_memory_usage_distributed
  |     assert shard_2.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
  | E   AssertionError: assert False
  | E    +  where False = contains_in_log('Query peak memory usage: 8.23')
  | E    +    where contains_in_log = <helpers.cluster.ClickHouseInstance object at 0x7f62ad427dc0>.contains_in_log
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

### PR DESCRIPTION
**Pull request by alexbakharew**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

Fixes: https://github.com/ClickHouse/ClickHouse/issues/90840

### Version info
- Merged into: `26.1.1.570`

### CODE REVIEW

File: src/Server/TCPHandler.cpp [hunk 1]
```diff
@@ -810,6 +810,8 @@ void TCPHandler::runImpl()
                 /// NOTE: we cannot send Progress for regular INSERT (with VALUES)
                 /// without breaking protocol compatibility, but it can be done
                 /// by increasing revision.
+                /// Do it before sending end of stream, to have a chance to show log message in client.
+                query_scope->logPeakMemoryUsage();
```
Comment (azat) [inline src/Server/TCPHandler.cpp]: Better to send it exactly before `sendSelectProfileEvents`

File: src/Server/TCPHandler.cpp [hunk 2]
```diff
@@ -785,12 +789,15 @@ void TCPHandler::runImpl()
             }
             else if (query_state->io.pipeline.pulling())
             {
-                processOrdinaryQuery(*query_state);
+                LOG_DEBUG(log, "debug_marker Thread {} In query_state->io.pipeline.pulling(), Call processOrdinaryQuery()", thread_id);
+                processOrdinaryQuery(*query_state, query_scope);
+                is_peak_memory_usage_logged = true;
```
Comment (alexbakharew) [inline src/Server/TCPHandler.cpp]: This fixes the failure of tests/integration/test_peak_memory_usage/test.py

File: src/Server/TCPHandler.cpp [hunk 3]
```diff
@@ -1431,6 +1445,11 @@ void TCPHandler::processOrdinaryQuery(QueryState & state)
         sendProfileInfo(state, executor.getProfileInfo());
         sendProgress(state);
         sendLogs(state);
+        /// Do it before sending end of stream, to have a chance to show log message in client.
+        query_scope->logPeakMemoryUsage();
+        auto thread_id = CurrentThread::get().thread_id;
+        LOG_DEBUG(log, "debug_marker Thread {} In processOrdinaryQuery in the end, Call sendSelectProfileEvents()", thread_id);
```
Comment (alexbakharew) [inline src/Server/TCPHandler.cpp]: This fixes the failure of tests/integration/test_peak_memory_usage/test.py

File: ci/defs/job_configs.py [hunk 4]
```diff
@@ -791,6 +791,11 @@ class JobConfigs:
                 parameter=f"amd_asan, flaky",
                 runs_on=RunnerLabels.AMD_MEDIUM,
                 requires=[ArtifactNames.CH_AMD_ASAN],
+            ),
```
Comment (azat) [inline ci/defs/job_configs.py]: Looks like some other changes got into this PR

File: ci/jobs/integration_test_job.py [hunk 5]
```diff
@@ -93,7 +93,7 @@ def parse_args():
     return parser.parse_args()
 
 
-FLAKY_CHECK_TEST_REPEAT_COUNT = 3
+FLAKY_CHECK_TEST_REPEAT_COUNT = 1000
```
Comment (azat) [inline ci/jobs/integration_test_job.py]: Let's revert all unrelated changes

File: src/Server/TCPHandler.cpp [hunk 6]
```diff
@@ -547,6 +548,8 @@ void TCPHandler::runImpl()
                 continue;
 
             chassert(query_state);
+            LOG_DEBUG(log, "debug_marker Thread {} Going to process query with ID {}", thread_id, query_state->query_id);
```
Comment (azat) [inline src/Server/TCPHandler.cpp]: Let's revert all debug logging and code

File: src/Server/TCPHandler.h [hunk 7]
```diff
@@ -305,7 +305,7 @@ class TCPHandler : public Poco::Net::TCPServerConnection
     AsynchronousInsertQueue::PushResult processAsyncInsertQuery(QueryState & state, AsynchronousInsertQueue & insert_queue);
 
     /// Process a request that does not require the receiving of data blocks from the client
-    void processOrdinaryQuery(QueryState & state);
+    void processOrdinaryQuery(QueryState & state, std::optional<CurrentThread::QueryScope>& query_scope);
```
Comment (azat) [inline src/Server/TCPHandler.h]: And please take a look at the patch for coding style issues

```suggestion
    void processOrdinaryQuery(QueryState & state, std::optional<CurrentThread::QueryScope> & query_scope);
```

File: tests/integration/test_peak_memory_usage/test.py [hunk 8]
```diff
@@ -118,3 +118,5 @@ def test_clickhouse_client_max_peak_memory_single_node(started_cluster):
     peak_memory_usage = get_memory_usage_from_client_output_and_close(client_output)
     assert peak_memory_usage
     assert shard_1.contains_in_log(f"Query peak memory usage: {peak_memory_usage}")
+
+
```
Comment (azat) [inline tests/integration/test_peak_memory_usage/test.py]: No need to touch this file

**Review by azat — CHANGES_REQUESTED** [review]
In general this is correct fix, but remove all unrelated changes, and I will look one more time

File: ci/defs/job_configs.py (hunk 4 above)
Comment (alexbakharew) [reply ci/defs/job_configs.py]: At this moment we don't have any flaky check on ARM, so I have added it in this PR to check all my hypothesizes whether they fix bug or not. Should be reverted though

File: src/Server/TCPHandler.cpp [hunk 9]
```diff
@@ -1431,6 +1436,9 @@ void TCPHandler::processOrdinaryQuery(QueryState & state)
         sendProfileInfo(state, executor.getProfileInfo());
         sendProgress(state);
         sendLogs(state);
+        /// Do it before sending end of stream, to have a chance to show log message in client.
```
Comment (azat) [inline src/Server/TCPHandler.cpp]: The comment is outdated, it should reflect why it is done here for SELECT

But what is more importantly, why we are doing it only for SELECT?

Let's do the following: do this for all queries, and rely on logging from dtor of query scope in case of exception, then we can remove this extra bool flag

And this should be enough for now.

Also note, that the still can be some drift actually (it is just a matter of do we have allocations between sending profile events this log)

So, if the test will be flaky after we can do the following:
- make the comparsion less strict
- use more complex query, so that allocations here will not update peak (since it will use more memory before)
- remove the test

File: src/Server/TCPHandler.cpp [hunk 10]
```diff
@@ -785,7 +786,8 @@ void TCPHandler::runImpl()
             }
             else if (query_state->io.pipeline.pulling())
             {
-                processOrdinaryQuery(*query_state);
+                processOrdinaryQuery(*query_state, query_scope);
+                is_peak_memory_usage_logged = true;
```
Comment (azat) [inline src/Server/TCPHandler.cpp]: It should be near to the first call of `logPeakMemoryUsage`

File: src/Server/TCPHandler.cpp [hunk 11]
```diff
@@ -810,6 +810,10 @@ void TCPHandler::runImpl()
                 /// NOTE: we cannot send Progress for regular INSERT (with VALUES)
                 /// without breaking protocol compatibility, but it can be done
                 /// by increasing revision.
+
+                // Send peak memory usage value to server logs before sending it to client
+                // 'sendProfileEvents' may allocate memory and change peak memory usage value on client
+                query_scope->logPeakMemoryUsage();
                 sendProgress(*query_state);
                 sendSelectProfileEvents(*query_state);
```
Comment (azat) [inline src/Server/TCPHandler.cpp]:
```suggestion
                sendProgress(*query_state);

                /// Log peak memory usage just before sending it to client to make it as accurate as possible
                /// (though note we may still have some allocations in between, that will make the difference)
                query_scope->logPeakMemoryUsage();
                sendSelectProfileEvents(*query_state);
```

File: src/Server/TCPHandler.cpp [hunk 12]
```diff
@@ -822,14 +826,13 @@ void TCPHandler::runImpl()
                 if (auto * create_query = query_state->parsed_query->as<ASTCreateQuery>();
                     create_query && create_query->isCreateQueryWithImmediateInsertSelect())
                 {
+                    // Send peak memory usage value to server logs before sending it to client
+                    // 'sendProfileEvents' may allocate memory and change peak memory usage value on client
+                    query_scope->logPeakMemoryUsage();
                     sendProgress(*query_state);
                     sendSelectProfileEvents(*query_state);
```
Comment (azat) [inline src/Server/TCPHandler.cpp]:
```suggestion
                    sendProgress(*query_state);

                    /// Log peak memory usage just before sending it to client to make it as accurate as possible
                    /// (though note we may still have some allocations in between, that will make the difference)
                    query_scope->logPeakMemoryUsage();
                    sendSelectProfileEvents(*query_state);
```

File: src/Server/TCPHandler.cpp [hunk 13]
```diff
@@ -1431,6 +1437,10 @@ void TCPHandler::processOrdinaryQuery(QueryState & state)
         sendProfileInfo(state, executor.getProfileInfo());
         sendProgress(state);
         sendLogs(state);
+        // Send peak memory usage value to server logs before sending it to client
+        // 'sendProfileEvents' may allocate memory and change peak memory usage value on client
+        query_scope->logPeakMemoryUsage();
+
```
Comment (azat) [inline src/Server/TCPHandler.cpp:1447]:
```suggestion
```

File: src/Server/TCPHandler.cpp [hunk 14]
```diff
@@ -1431,6 +1437,10 @@ void TCPHandler::processOrdinaryQuery(QueryState & state)
         sendProfileInfo(state, executor.getProfileInfo());
         sendProgress(state);
         sendLogs(state);
+        // Send peak memory usage value to server logs before sending it to client
+        // 'sendProfileEvents' may allocate memory and change peak memory usage value on client
```
Comment (azat) [inline src/Server/TCPHandler.cpp]:
```suggestion

        // Log peak memory usage just before sending it to client to make it as accurate as possible
        // (though note we may still have some allocations in between, that will make the difference)
```

**Review by azat — APPROVED** [review]
