### PR TITLE
Use partial match for SKIP REGEXP in JSON type by default

### LINKED ISSUE #79250: JSON SKIP REGEXP Requires Full Match, Unlike Standard REGEXP
### Company or project name

_No response_

### Describe what's wrong

This will not skip "skip_me".
```
DROP TABLE IF EXISTS json_test;
CREATE TABLE json_test (
    data JSON(
        `dot.ted.key` UInt32,
        SKIP REGEXP 'skip'
    )
) ENGINE = Memory;
INSERT INTO json_test VALUES ('{"skip_me": 1, "dot.ted.key": 42}');
SELECT data FROM json_test;
```
I found that this is because SKIP REGEXP requires a full match. The following actually will skip "skip_me"
```
DROP TABLE IF EXISTS json_test;
CREATE TABLE json_test (
    data JSON(
        `dot.ted.key` UInt32,
        SKIP REGEXP 'skip.*'
    )
) ENGINE = Memory;
INSERT INTO json_test VALUES ('{"skip_me": 1, "dot.ted.key": 42}');
SELECT data FROM json_test;
```

But I guess in most cases, REGEXP shouldn't require a full match. For example, when you try
```
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
    path String
) ENGINE = Memory;
INSERT INTO logs VALUES
('/var/log/error.log'), ('/var/log/info.log');
SELECT * FROM logs WHERE path REGEXP 'error';
```
You will get
```
/var/log/error.log
```
Only the row for "error" will be kept.

Perhaps SKIP REGEXP should be changed to use substring matching so that its behavior is consistent? Thanks!

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```
DROP TABLE IF EXISTS json_test;
CREATE TABLE json_test (
    data JSON(
        `dot.ted.key` UInt32,
        SKIP REGEXP 'skip'
    )
) ENGINE = Memory;
INSERT INTO json_test VALUES ('{"skip_me": 1, "dot.ted.key": 42}');
SELECT data FROM json_test;
```

### Expected behavior

```
{"dot":{"ted":{"key":42}}} 
```

### Error message and/or stacktrace

```
{"dot":{"ted":{"key":42}},"skip_me":"1"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Use partial match for SKIP REGEXP in JSON type by default. Closes https://github.com/ClickHouse/ClickHouse/issues/79250

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Core/FormatFactorySettings.h [hunk 1]
```diff
@@ -545,6 +545,9 @@ Possible values:
 )", 0) \
     DECLARE(Bool, type_json_skip_duplicated_paths, false, R"(
 When enabled, during parsing JSON object into JSON type duplicated paths will be ignored and only the first one will be inserted instead of an exception
+)", 0) \
+    DECLARE(Bool, type_json_use_partial_match_to_skip_paths_by_regexp, true, R"(
```
Comment (scanhex12) [inline src/Core/FormatFactorySettings.h:549]: Maybe it's better to set it to false by default?
In previous versions it uses full match

**Review by scanhex12 — APPROVED** [review]

File: src/Core/FormatFactorySettings.h (hunk 1 above)
Comment (Avogar) [reply src/Core/FormatFactorySettings.h:549]: It's much more user friendly to have a partial match, also in some other places we use partial match by default, so I decided to add it here for consistency. The change is guarded by `compatibility` setting, so it should be ok.

**Comment by fm4v** [comment]
Changed category to `Backward Incompatible Change` to notify users
