### PR TITLE
Remove completely processed WAL files

### LINKED ISSUE #17731: Slow start with high memory consumption: log filled with "<Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 16.90 TiB."
**Describe the bug**

Since we upgraded to 20.10.3.30, one of our clickhouse cluster takes much more time to start. (Up to 50 minutes, and before it took ~3 minutes)
The log file is filled with
>  <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 16.90 TiB

Additionally, the memory consumption increases, linearly, a lot (up to arround 230 G for us) and then drop back to normal values once clickhouse finished starting up. During that loading phase, a single CPU core is used at 100%.
If that memory is not available for the machine, clickhouse gets OOMed by the kernel.

**How to reproduce**
* Issue appeared after we upgraded to ClickHouse server version 20.10.3.30

* How could I find wich of our tables may be responsible for that ?

**Expected behavior**
A fast startup :)

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove completely processed WAL files

Fixes: #17731 (cc @CurtizJ )

_P.S. I've started to use shared build, again :)_

### CODE REVIEW

**Comment by azat** [comment]
>[Stateless tests (release, wide parts enabled) — fail: 1, passed: 4390, skipped: 3](https://s3.amazonaws.com/clickhouse-test-reports/40592/f9e16be7aab74baf218591d384443265c2946364/stateless_tests__debug__[3/3].html)

- `02405_pmj_issue_40335` - #40610

File: src/Storages/MergeTree/MergeTreeWriteAheadLog.cpp [hunk 1]
```diff
@@ -234,6 +241,15 @@ MergeTreeData::MutableDataPartsVector MergeTreeWriteAheadLog::restore(const Stor
...
 
+    /// All parts in WAL had been already committed into the disk -> clear the WAL
+    if (parts.empty())
+    {
+        LOG_DEBUG(log, "WAL file '{}' had been completely processed. Removing.", path);
+        disk->removeFile(path);
+        init();
+        return {};
+    }
+
```
Comment (CurtizJ) [inline src/Storages/MergeTree/MergeTreeWriteAheadLog.cpp:252]: Maybe do this check after removing of dropped parts, because looks like for them `getActiveContainingPart` may return `false`, but we don't need to process them?

Comment (azat) [reply src/Storages/MergeTree/MergeTreeWriteAheadLog.cpp]: You are right, nice catch! Rebased.

**Review by CurtizJ — APPROVED** [review]
