### PR TITLE
Optimize `cramersV`, `cramersVBiasCorrected`, `theilsU`, and `contingency` when used with window functions

### LINKED ISSUE #83521: cramersV and contingency aggregates not scaling well with window functions.
### Company or project name

ClickHouse employee 😄 

### Describe the unexpected behaviour

Not sure if a real issue. Benchmarks from my machine:
```sql
SELECT cramersV(number, number) OVER () FROM numbers(10000); --About 3 seconds
SELECT cramersV(number, number) OVER () FROM numbers(20000); -- About 10 seconds
```
It seems these aggregates do not scale well inside window functions. I tried with other statistical aggregates and they run pretty fast.

### Which ClickHouse versions are affected?

Latest master.

### How to reproduce

Run the steps above.

### Expected behavior

The performance should not scale that badly with the number of elements.

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### LINKED ISSUE #103060: Wrong sign and range in `theilsU` documentation example output
_Found via ClickGap automated review. Please close or comment if this is incorrect or needs adjustment._

_Retrospective finding from a historical scan of [PR #92831](https://github.com/ClickHouse/ClickHouse/pull/92831) (merged 2025-12-23). Confirmed on current codebase — close with a note if already fixed._

### Describe what's wrong

`theilsU` documentation example shows result `-0.30195720557678846` (negative) but the function returns `0.30195720557678846` (positive). Also, the description incorrectly states the range is -1.0 to +1.0 instead of 0 to 1.

**Root cause:** AggregateFunctionTheilsU.cpp:87: the documentation example output was written with an incorrect negative sign. Line 59: the range description was copied from a correlation coefficient description. Line 70: ReturnedValue also says 'between -1 and 1'. The implementation at TheilsUData::getResult correctly returns (h_a - dep) / h_a which is always >= 0.

**Why we believe this is a bug:** AggregateFunctionTheilsU.cpp:87 — the example output string literal contains a negative sign that doesn't match the actual function output. Line 59 describes the range as -1.0 to +1.0, which is characteristic of correlation coefficients (like Pearson's r), not Theil's U uncertainty coefficient which ranges from 0 to 1.

**Affected locations:**
- `src/AggregateFunctions/AggregateFunctionTheilsU.cpp:87` — Wrong sign in example output string
- `src/AggregateFunctions/AggregateFunctionTheilsU.cpp:59` — Wrong range description: -1.0 to +1.0 should be 0 to 1
- `src/AggregateFunctions/AggregateFunctionTheilsU.cpp:70` — ReturnedValue text says 'between -1 and 1'

**Impact:** Users reading the inline documentation will see an incorrect example output with a negative sign. The description also misleads users about the valid range of Theil's U, potentially causing confusion about interpretation of results.

### Does it reproduce on most recent release?

Yes — confirmed on current `master` (commit `1c88918b544d`).

### How to reproduce

```sql
SELECT theilsU(a, b) FROM (SELECT number % 10 AS a, number % 4 AS b FROM numbers(150));
```

[Try it on ClickHouse Fiddle](https://fiddle.clickhouse.com/bd643962-06a4-4525-ae3d-46888deb6c86)

### Expected behavior

```
0.30195720557678846
```

### Error message and/or stacktrace

```
0.30195720557678846
```

### Additional context

**Suggested fix:** Change line 87 from `-0.30195720557678846` to `0.30195720557678846`. Change line 59 from 'range from −1.0 ... to +1.0' to 'range from 0.0 (no association) to 1.0 (complete association)'. Change line 70 from 'between -1 and 1' to 'between 0 and 1'.

**Analysis details:** Confidence HIGH | Severity P3 | Testability: `STATELESS_SQL`

Found during automated review of [PR #92831](https://github.com/ClickHouse/ClickHouse/pull/92831).

---
_ClickGapAI · Confidence: HIGH · Severity: P3 · Finding: `h_pr92831_001`_

### LINKED ISSUE #103062: Wrong `cramersV` and `cramersVBiasCorrected` documentation example outputs due to stale values from pre-fix `getPhiSquared`
_Found via ClickGap automated review. Please close or comment if this is incorrect or needs adjustment._

_Retrospective finding from a historical scan of [PR #92787](https://github.com/ClickHouse/ClickHouse/pull/92787) (merged 2025-12-24). Confirmed on current codebase — close with a note if already fixed._

### Describe what's wrong

The documentation embedded in source code for `cramersV` (AggregateFunctionCramersV.cpp:88) claims `cramersV(number%10, number%5)` over `numbers(150)` returns `0.8944271909999159`, but the actual result is `1`. Similarly, `cramersVBiasCorrected` (AggregateFunctionCramersVBiasCorrected.cpp:74-75) claims `cramersV = 0.41171788506213564` and `cramersVBiasCorrected = 0.33369281784141364` for `number%10, number%4`, but actual values are `0.5798088336225177` and `0.5305112825189072`.

**Root cause:** AggregateFunctionCramersV.cpp:88 and AggregateFunctionCramersVBiasCorrected.cpp:74-75: documentation example output strings contain values computed by the old buggy `getPhiSquared` formula, not the corrected one

**Why we believe this is a bug:** Documentation examples → `cramersV(number%10, number%5, numbers(150))` → `CramersVData::getResult` (AggregateFunctionCramersV.cpp:21-28) → `CrossTabData::getPhiSquared` (CrossTab.h:127-159). The `getPhiSquared` implementation was fixed in commit 8815dd80428c (2025-09-29) but documentation examples still contain the old incorrect values from before the fix.

**Affected locations:**
- `src/AggregateFunctions/AggregateFunctionCramersV.cpp:88` — cramersV high-association example output claims 0.8944271909999159
- `src/AggregateFunctions/AggregateFunctionCramersVBiasCorrected.cpp:74` — cramersVBiasCorrected example output claims wrong cramersV and cramersVBiasCorrected values

**Impact:** User-facing documentation will show wrong expected output for `cramersV` and `cramersVBiasCorrected` examples, causing confusion when users try to reproduce the examples and get different results.

### Does it reproduce on most recent release?

Yes — confirmed on current `master` (commit `1c88918b544d`).

### How to reproduce

```sql
-- Test: Verify cramersV and cramersVBiasCorrected documentation example outputs are correct
-- Covers: AggregateFunctionCramersV.cpp:87-89 and AggregateFunctionCramersVBiasCorrected.cpp:74-76

-- cramersV "High association" example from documentation
-- Documentation claims result is 0.8944271909999159 but correct result is 1
SELECT 'cramersV_high_assoc';
SELECT cramersV(a, b)
FROM (SELECT number % 10 AS a, number % 5 AS b FROM numbers(150))
ORDER BY 1;

-- cramersV "No association" example (should be 0)
SELECT 'cramersV_no_assoc';
SELECT cramersV(a, b)
FROM (SELECT number % 3 AS a, number % 5 AS b FROM numbers(150))
ORDER BY 1;

-- cramersVBiasCorrected example from documentation
-- Documentation claims cramersV=0.41171788506213564 and cramersVBiasCorrected=0.33369281784141364
SELECT 'cramersVBiasCorrected';
SELECT cramersV(a, b), cramersVBiasCorrected(a, b)
FROM (SELECT number % 10 AS a, number % 4 AS b FROM numbers(150))
ORDER BY 1;
```

[Try it on ClickHouse Fiddle](https://fiddle.clickhouse.com/66d316f7-037c-4473-94e6-bcbbb4cd4d19)

### Expected behavior

```
cramersV_high_assoc
1
cramersV_no_assoc
0
cramersVBiasCorrected
0.5798088336225177	0.5305112825189072
```

### Error message and/or stacktrace

```
cramersV_high_assoc
1
cramersV_no_assoc
0
cramersVBiasCorrected
0.5798088336225177	0.5305112825189072
```

### Additional context

**Open risks:**
- Other CrossTab-based documentation (theilsU, contingency) may also have stale example outputs

**Suggested fix:** Update the `cramersV` high-association example output to `1` and the `cramersVBiasCorrected` example outputs to `cramersV = 0.5798088336225177` and `cramersVBiasCorrected = 0.5305112825189072`.

**Analysis details:** Confidence HIGH | Severity P3 | Testability: `STATELESS_SQL`

Found during automated review of [PR #92787](https://github.com/ClickHouse/ClickHouse/pull/92787).

---
_ClickGapAI · Confidence: HIGH · Severity: P3 · Finding: `h_pr92787_001`_

### LINKED ISSUE #103067: Wrong `contingency` and `cramersV` values in `contingency` documentation example due to stale `getPhiSquared` outputs
_Found via ClickGap automated review. Please close or comment if this is incorrect or needs adjustment._

_Retrospective finding from a historical scan of [PR #92397](https://github.com/ClickHouse/ClickHouse/pull/92397) (merged 2025-12-22). Confirmed on current codebase — close with a note if already fixed._

### Describe what's wrong

The documentation example in `AggregateFunctionContingencyCoefficient.cpp` claims `cramersV(a, b) = 0.41171788506213564` and `contingency(a, b) = 0.05812725261759165` for the query `SELECT cramersV(a, b), contingency(a, b) FROM (SELECT number % 10 AS a, number % 4 AS b FROM numbers(150))`, but the actual outputs are `0.5798088336225177` and `0.708607540104077` respectively.

**Root cause:** AggregateFunctionContingencyCoefficient.cpp:79: the example output string `0.41171788506213564` for `cramersV` and `0.05812725261759165` for `contingency` were copied from old documentation that predated the `getPhiSquared` fix in CrossTab.h

**Why we believe this is a bug:** AggregateFunctionContingencyCoefficient.cpp:79 → documentation example output string contains values computed before the `getPhiSquared` algorithm was refactored in CrossTab.h:127. The documented values are from the old implementation and no longer match the current function output.

**Affected locations:**
- `src/AggregateFunctions/AggregateFunctionContingencyCoefficient.cpp:79` — documentation example output string with wrong cramersV and contingency values

**Impact:** Users reading the auto-generated documentation will see incorrect expected output values for the `contingency` function example, potentially causing confusion when their query results differ from the documented output.

### Does it reproduce on most recent release?

Yes — confirmed on current `master` (commit `1c88918b544d`).

### How to reproduce

```sql
SELECT cramersV(a, b), contingency(a, b) FROM (SELECT number % 10 AS a, number % 4 AS b FROM numbers(150));
```

[Try it on ClickHouse Fiddle](https://fiddle.clickhouse.com/bfa6cbb0-1e01-4fac-8bfb-65d483ed1bdb)

### Expected behavior

```
Documented claims 0.41171788506213564 for cramersV and 0.05812725261759165 for contingency, but actual correct output is 0.5798088336225177 and 0.708607540104077
```

### Error message and/or stacktrace

```
0.5798088336225177	0.708607540104077
```

### Additional context

**Open risks:**
- Other cross-tab function documentation (theilsU, cramersVBiasCorrected) may have similar stale values if their docs are moved to source

**Suggested fix:** Update the example output to match the actual function output: `cramersV(a, b) = 0.5798088336225177` and `contingency(a, b) = 0.708607540104077`

**Analysis details:** Confidence HIGH | Severity P3 | Testability: `STATELESS_SQL`

Found during automated review of [PR #92397](https://github.com/ClickHouse/ClickHouse/pull/92397).

---
_ClickGapAI · Confidence: HIGH · Severity: P3 · Finding: `h_pr92397_001`_

### PR DESCRIPTION
**Pull request by nihalzp**
```sql
SELECT cramersV(number, number) OVER (ORDER BY number) FROM numbers(20000) FORMAT NULL;
```
Master: 4.198 sec
PR: 0.014 sec

These functions were running in quadratic time complexity when used in window context. This PR adds `window` variants of these aggregate functions. When a query uses these aggregates in a window context, `resolveFunction` chooses the window variants creators.

We do not use these `Window` versions for non-window context such as GROUP BY because they will be slower. `Window` versions are optimized for incremental updates so that `getResult` is `O(1)`.

image

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Optimize `cramersV`, `cramersVBiasCorrected`, `theilsU`, and `contingency` when used with window functions. Closes https://github.com/ClickHouse/ClickHouse/issues/83521.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.5.1.27`

### CODE REVIEW

**Comment by UnamedRus** [comment]
Slightly different direction, but for that particular window 

```
SELECT cramersV(number, number) OVER () FROM numbers(20000);
```

It actually does not change aggregated state between calling of getResult ( as window is the same for all rows)

Could we have flag and cached result value in function.
So, if we call `getResult`, it will set flag to true and save result in `cache`. and if `add/merge` function is called, it would just reset flag to false and clear cache. 

But, it wouldn't work for windows if it's rolling or adding.

**Comment by nihalzp** [comment]
Yes, you are right. For this format:

```sql
SELECT cramersV(number, number) OVER () FROM numbers(20000);
```
we can definitely use your idea; but that is a different problem and require changes in various other places.

The PR also optimizes any window functions like rolling or partition. For example:

```sql
SELECT cramersV(number, number) OVER (ORDER BY number) FROM numbers(20000);
```

File: src/AggregateFunctions/CrossTab.h [hunk 1]
```diff
@@ -138,30 +156,508 @@ struct CrossTabData
...
+///         toUInt32(number % 1000) AS a,
+///         toUInt32(intDiv(number, 1000) % 1000) AS b
+///     FROM numbers(1000 * 1000)
+/// );
+/// This generates an almost complete 1000×1000 set of (a,b) pairs, so each add() processes ~1000 incident edges,
+/// which will be very slow.
+///
+/// This base is used by window-friendly implementations of `cramersV`, `cramersVBiasCorrected`,
+/// and `contingencyCoefficient`.
+struct CrossTabWindowPhiSquaredData
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/CrossTab.h]: This giant comment doesn't say **what** you do here. Just say that you are computing `phi^2` coefficient by definition and store the observations as a graph in a tricky form.

File: src/AggregateFunctions/CrossTab.h [hunk 2]
```diff
@@ -138,30 +156,508 @@ struct CrossTabData
...
+        const bool has_edge = (it_edge != ab_edge_index_by_pair.end());
+        UInt32 edge_idx = has_edge ? it_edge->getMapped() : INVALID_EDGE_IDX;
+
+        /// Remove old contributions for the affected row/column
+        if (old_count_a)
+            applyRowPhiDelta(a_idx, static_cast<Float64>(old_count_a), -1.0);
+
+        if (old_count_b)
+            applyColumnPhiDelta(b_idx, static_cast<Float64>(old_count_b), -1.0, has_edge ? edge_idx : INVALID_EDGE_IDX);
+
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/CrossTab.h:312]: If we take a look at the $\chi^2= \sum_{i,j}\frac{\left(n_{ij} - \dfrac{n_{i\cdot} n_{\cdot j}}{n}\right)^2}{\dfrac{n_{i\cdot} n_{\cdot j}}{n}}$ and taking into account that $\varphi^2 = \frac{\chi^2}{n}$ 

We can see that $\varphi^2= \sum_{i,j}\frac{n_{ij}^2}{n_{i\cdot} n_{\cdot j}}+2\frac{n_{ij}}{n}+ \frac{n_{i\cdot} n_{\cdot j}}{n^2}$, 

But I don't see we care much about $\frac{n_{i\cdot} n_{\cdot j}}{n^2}$

Comment (nikitamikhaylov) [reply src/AggregateFunctions/CrossTab.h:312]: Understood.

**Review by nikitamikhaylov — APPROVED** [review]

File: src/AggregateFunctions/AggregateFunctionTheilsU.cpp [hunk 3]
```diff
@@ -50,14 +62,216 @@ struct TheilsUData : CrossTabData
...
+
+        for (const auto & [key, add_value] : other.count_b)
+            addToCountAndSum(count_b, key, add_value, sum_b_nlogn);
+
+        for (const auto & [key, add_value] : other.count_ab)
+            addToCountAndSum(count_ab, key, add_value, sum_ab_nlogn);
+    }
+
+    /// Keep the same serialization format as CrossTabAggregateData
+    void serialize(WriteBuffer & buf) const
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/AggregateFunctionTheilsU.cpp]: Let's write a test and make sure that the serialization format is byte-to-byte identical

File: src/AggregateFunctions/IAggregateFunction.h [hunk 4]
```diff
@@ -70,6 +94,28 @@ class IAggregateFunction : public std::enable_shared_from_this<IAggregateFunctio
...
+        /// correctly detects Aggregation vs Window state mismatches
+        if (auto nested = getNestedFunction())
+            return nested->getStateVariant();
+
+        return AggregateFunctionStateVariant::Aggregation;
+    }
+
+    /// Optional hook used when haveSameStateRepresentation() is false but states still need to be merged
+    /// (for example, aggregation vs window variants of the same function).
+    virtual bool canMergeStateFromDifferentVariant(const IAggregateFunction & /*rhs*/) const { return false; }
```
Comment (nikitamikhaylov) [inline src/AggregateFunctions/IAggregateFunction.h:114]: Do we have any examples of functions with the following parameters: 
- `haveSameStateRepresentation()` == false
- `canMergeStateFromDifferentVariant()` == true


For AggregateFunctionCrossTab it seems `haveSameStateRepresentation()` is true (as default implementation) and then I don't quite understand how `mergeStateFromDifferentVariant` can be called.

File: src/AggregateFunctions/Combinators/AggregateFunctionCombinatorsArgMinArgMax.cpp [hunk 5]
```diff
@@ -83,6 +84,39 @@ class AggregateFunctionCombinatorArgMinArgMax final : public IAggregateFunctionH
...
+        chassert(rhs_nested != nullptr);
+
+        const size_t rhs_key_offset = ::Memory::alignUp(rhs_nested->sizeOfData(), alignof(Key));
+        const auto & rhs_key = *reinterpret_cast<const Key *>(rhs_place + rhs_key_offset);
+
+        if ((isMin && data(place).data().setIfSmaller(rhs_key.data(), arena))
+            || (!isMin && data(place).data().setIfGreater(rhs_key.data(), arena)))
+        {
+            nested_function->destroy(place);
+            nested_function->create(place);
```
Comment (azat) [inline src/AggregateFunctions/Combinators/AggregateFunctionCombinatorsArgMinArgMax.cpp:111]: What will happen if `create` will throw? (i.e. `MEMORY_LIMIT_EXCEEDED`) Likely it will try to destroy the state again

File: src/AggregateFunctions/IAggregateFunction.h [hunk 6]
```diff
@@ -70,6 +94,28 @@ class IAggregateFunction : public std::enable_shared_from_this<IAggregateFunctio
...
+
+    /// Similar to merge() but allows merging between different variants (Aggregate/Window).
+    /// Must be called only if canMergeStateFromDifferentVariant(rhs) returns true.
+    /// See CrossTab.h for an example implementation.
+    virtual void mergeStateFromDifferentVariant(AggregateDataPtr __restrict place, const IAggregateFunction & rhs, ConstAggregateDataPtr rhs_place, Arena * arena) const;
```
Comment (azat) [inline src/AggregateFunctions/IAggregateFunction.h:123]: Can you please add a comment when merging of aggregate with window state can occur?

File: src/AggregateFunctions/IAggregateFunction.h (hunk 4 above)
Comment (nihalzp) [reply src/AggregateFunctions/IAggregateFunction.h:114]: > Do we have any examples of functions with the following parameters:
>
> haveSameStateRepresentation() == false
> canMergeStateFromDifferentVariant() == true

All `CrossTab` functions actually satisfy this if `lhs` and `rhs` are of different variant. For example, for `cramersV`, if `lhs` is `Aggregate` variant and and `rhs` is `Window` variant, then `haveSameStateRepresentation()` will be false and `canMergeStateFromDifferentVariant()` will be true.

> For AggregateFunctionCrossTab it seems haveSameStateRepresentation() is true (as default implementation) and then I don't quite understand how mergeStateFromDifferentVariant can be called.
Actually, I have changed default implementation of `haveSameStateRepresentation()` to:

```cpp
bool IAggregateFunction::haveSameStateRepresentation(const IAggregateFunction & rhs) const
{
    const auto & lhs_base = getBaseAggregateFunctionWithSameStateRepresentation();
    const auto & rhs_base = rhs.getBaseAggregateFunctionWithSameStateRepresentation();

    /// Consider Window vs Aggregation variants as different state representations.
    if (lhs_base.getStateVariant() != rhs_base.getStateVariant())
        return false;

    return lhs_base.haveSameStateRepresentationImpl(rhs_base);
}
```
So, `haveSameStateRepresentation()` will only be true if they are the same aggregate function and also have the same name. Then, we check `canMergeStateFromDifferentVariant()` if it's true, we use `mergeStateFromDifferentVariant()`.

If `haveSameStateRepresentation()` is true, then `canMergeStateFromDifferentVariant()` will return false.

File: src/AggregateFunctions/Combinators/AggregateFunctionCombinatorsArgMinArgMax.cpp (hunk 5 above)
Comment (nihalzp) [reply src/AggregateFunctions/Combinators/AggregateFunctionCombinatorsArgMinArgMax.cpp:111]: I understand the concern. Actually, this logic is not unique to the PR. I just tried to mirror the semantics between `mergeStateFromDifferentVariant()` and the existing `merge()`. Seems like the same issue exists for `merge()` as well.

File: src/AggregateFunctions/IAggregateFunction.h [hunk 7]
```diff
@@ -71,12 +96,42 @@ class IAggregateFunction : public std::enable_shared_from_this<IAggregateFunctio
...
+    /// Allows merging states produced by different state variants of the same aggregate function
+    /// (for example, Aggregate vs Window) when haveSameStateRepresentation() is false.
+    /// This is used by the -Merge combinator to decide whether it can call mergeStateFromDifferentVariant().
+    virtual bool canMergeStateFromDifferentVariant(const IAggregateFunction & /*rhs*/) const { return false; }
+
+    /// Similar to merge() but allows merging between different variants (Aggregate/Window).
+    /// Called by the -Merge combinator when haveSameStateRepresentation() is false and canMergeStateFromDifferentVariant()
+    /// returns true and the input AggregateFunction state column was produced by the same aggregate function
+    /// but with a different state variant (e.g. Window vs Aggregate),
+    /// If haveSameStateRepresentation() is true, then always merge() is called.
```
Comment (azat) [inline src/AggregateFunctions/IAggregateFunction.h:120]: Not a suggestion, but a question - is this use case useful? Maybe it is better to forbid it for now?

Also AFAICS there is no test for it? Or maybe I missed something?

Comment (nihalzp) [reply src/AggregateFunctions/IAggregateFunction.h:120]: Yes, this is required to make the following queries work when in-memory data state of one variant is merged in other state variant context. For example,
```sql
SELECT 'contingency: normal (aggregate) states merged in OVER() (window consumes normal states)';
WITH
    (SELECT contingency(toUInt8(number % 10), toUInt8(number % 6)) FROM numbers(10_000)) AS direct_raw,
    (
        SELECT contingencyMerge(st)
            OVER (ORDER BY g ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
        FROM
        (
            SELECT
                number % 1000 AS g,
                CAST(
                    CAST(contingencyState(toUInt8(number % 10), toUInt8(number % 6)), 'String'),
                    'AggregateFunction(contingency, UInt8, UInt8)'
                ) AS st
            FROM numbers(10_000)
            GROUP BY g
            ORDER BY g
        )
        ORDER BY g DESC
        LIMIT 1
    ) AS over_merged_raw
SELECT
    round(direct_raw, 4) AS direct,
    round(over_merged_raw, 4) AS merged_over,
    abs(direct_raw - over_merged_raw) < 1e-9;
```
Otherwise, this kind of queries will not work anymore causing backward incompatibility.

Yes, most of the tests are actually testing this. For example, the test file `tests/queries/0_stateless/03811_contingency_window_functions_nested_combinators_merge.sql` uses execution of this function to exhaustively test all combinators we have.

Comment (nihalzp) [reply src/AggregateFunctions/IAggregateFunction.h:120]: Also, if some combinator forgets to implement it or if some new aggregate function that supports both (`Window` and `Aggregate`) variant does not implement it, then it will show a proper error for a query that tries to merge one variant states in the context of other variant state (e.g. `Window` states into `Aggregate` context) instead of crashing.

File: src/AggregateFunctions/AggregateFunctionTheilsU.cpp (hunk 3 above)
Comment (nihalzp) [reply src/AggregateFunctions/AggregateFunctionTheilsU.cpp]: I have added the new `tests/queries/0_stateless/03916_contingency_state_variant_serialization_match.sql` to test equality of the serialization format.

File: src/AggregateFunctions/CrossTab.h [hunk 8]
```diff
@@ -138,31 +164,606 @@ struct CrossTabData
...
+            const UInt32 edge_idx = static_cast<UInt32>(ab_edges.size());
+            ab_edges.push_back(Edge{a_idx, b_idx, cnt_ab});
+
+            ab_edge_index_by_pair[pair_key] = edge_idx;
+            a_incident_edges[a_idx].push_back(edge_idx);
+            b_incident_edges[b_idx].push_back(edge_idx);
+
+            const Float64 a = static_cast<Float64>(a_marginal_count[a_idx]);
+            const Float64 b = static_cast<Float64>(b_marginal_count[b_idx]);
+            phi_term_sum += phiTerm(cnt_ab, a, b);
```
[the remark this answers is not in the document]
Comment (nihalzp) [reply src/AggregateFunctions/CrossTab.h:568]: It cannot happen.

File: src/AggregateFunctions/CrossTab.h [hunk 9]
```diff
@@ -138,31 +164,606 @@ struct CrossTabData
...
+        ++a_marginal_count[a_idx];
+        ++b_marginal_count[b_idx];
+
+        if (has_edge)
+        {
+            ++ab_edges[edge_idx].count;
+        }
+        else
+        {
+            edge_idx = static_cast<UInt32>(ab_edges.size());
```
[the remark this answers is not in the document]
Comment (nihalzp) [reply src/AggregateFunctions/CrossTab.h:325]: If that happens, there would be other bigger issues like OOM.

**Comment by alexey-milovidov** [comment]
The flaky check failure is fixed in https://github.com/ClickHouse/ClickHouse/pull/102148, let's update the branch.

**Comment by azat** [comment]
Do we need 3 idential enums here? (AggregateFunctionUsage, AggregateFunctionStateVariant, CrossTabImplementationVariant)

File: src/Formats/NativeReader.cpp [hunk 10]
```diff
@@ -262,7 +262,16 @@ Block NativeReader::read()
 
                 if (!header_column.type->equals(*column.type))
                 {
-                    if (format_settings && format_settings->native.allow_types_conversion)
+                    /// In the event of the same aggregate function but of a different variant (e.g. Window vs Aggregate),
+                    /// we should try to convert and read, since the difference in `Window` vs `Aggregate` is not a
+                    /// user-facing type difference but rather an internal implementation detail.
+                    /// This can happen when external sort spills blocks to disk: the header carries the Window variant from the query plan,
+                    /// but `NativeReader` deserializes the type name and resolves it via `AggregateFunctionFactory`, which always produces the
+                    /// Aggregation variant.
```
Comment (azat) [inline src/Formats/NativeReader.cpp:270]: Are you sure that we need this?
I mean AFAICS the serializaton on disk is idential for window and aggregation states?
If this is true then we can remove this `equalsIgnoringVariant`, and maybe we can even ignore state variant in `DataTypeAggregateFunction`? (not sure about this though)

Comment (nihalzp) [reply src/Formats/NativeReader.cpp:270]: > Are you sure that we need this?

Yes, otherwise queries like this that use external sort will fail with `TYPE_MISMATCH`:

```sql
SET max_bytes_before_external_sort = 100;
SET max_bytes_ratio_before_external_sort = 0;

SELECT cramersVMerge(s) FROM (
    SELECT cramersVState(toUInt8(number % 10), toUInt8(number % 6)) OVER () AS s, number
    FROM numbers(100000)
    ORDER BY number
    LIMIT 1 BY number % 1000
);
```

> I mean AFAICS the serializaton on disk is idential for window and aggregation states?

Yes, the serialized bytes are identical across variants — that's why `NativeReader` can deserialize the blocks in the first place (into the default `Aggregation` variant). But after deserialization, `NativeReader` compares the column's type (`Aggregation` variant) against the header's expected type (`Window` variant from the query plan). Even though the serialized bytes are the same, the in-memory representations are different between `Aggregation` and `Window`; that's why we have to go through `castColumn` to get the correct in-memory representation (`Window` in our case) and the correct `DataTypeAggregateFunction` (`Window` variant).

> If this is true then we can remove this equalsIgnoringVariant, and maybe we can even ignore state variant in DataTypeAggregateFunction? (not sure about this though)

Yes, for the same reason as above, the `Window` and `Aggregation` variants are resolved as different `DataTypeAggregateFunction` objects. If `DataTypeAggregateFunction::equals()` treated `Window` and `Aggregation` variants as equal, numerous places would incorrectly try to merge one variant's data into another, causing potential segfaults. Having `equalsIgnoringVariant` is a cheap, convenient way to check if two `DataTypeAggregateFunction` objects may even be mergeable, allowing us to then try to do cross-variant conversion.

File: src/AggregateFunctions/CrossTab.h [hunk 11]
```diff
@@ -138,31 +164,619 @@ struct CrossTabData
...
+
+        /// Update the internal states
+        a_hash_by_index.reserve(count_a.size());
+        a_marginal_count.reserve(count_a.size());
+        a_incident_edges.reserve(count_a.size());
+        a_epoch_mark.reserve(count_a.size());
+
+        for (const auto & [hash, cnt] : count_a)
+        {
+            chassert(a_hash_by_index.size() < INVALID_EDGE_IDX);
```
Comment (azat) [inline src/AggregateFunctions/CrossTab.h]: I think `chassert` should be replaced with a `Exception(CORRUPTED_DATA)`, since the input can contain garbage

File: src/AggregateFunctions/CrossTab.h [hunk 12]
```diff
@@ -138,31 +164,619 @@ struct CrossTabData
...
+
+        b_hash_by_index.reserve(count_b.size());
+        b_marginal_count.reserve(count_b.size());
+        b_incident_edges.reserve(count_b.size());
+
+        for (const auto & [hash, cnt] : count_b)
         {
-            assert(phi_squared > -1e-10);
-            phi_squared = 0.0;
+            chassert(b_hash_by_index.size() < INVALID_EDGE_IDX);
```
Comment (azat) [inline src/AggregateFunctions/CrossTab.h]: I think `chassert` should be replaced with a `Exception(CORRUPTED_DATA)`

File: src/AggregateFunctions/CrossTab.h [hunk 13]
```diff
@@ -138,31 +164,619 @@ struct CrossTabData
...
+
+        for (const auto & [pair_key, cnt_ab] : count_ab)
+        {
+            const UInt64 hash_a = pair_key.items[UInt128::_impl::little(0)];
+            const UInt64 hash_b = pair_key.items[UInt128::_impl::little(1)];
+
+            const UInt32 a_idx = a_index_by_hash.at(hash_a);
+            const UInt32 b_idx = b_index_by_hash.at(hash_b);
+
+            chassert(ab_edges.size() < INVALID_EDGE_IDX);
```
Comment (azat) [inline src/AggregateFunctions/CrossTab.h]: I think `chassert` should be replaced with a `Exception(CORRUPTED_DATA)`

**Review by azat — APPROVED** [review]
I have not looked at the implementation of optimized version for window states (there was already approve before), everything else looks good, also PTAL at some minor comments
