### PR TITLE
Fix distributed ddl alter

### LINKED ISSUE #3268: create & alter inconsistency with "on cluster" for ENGINE = Distributed
```
<vscluster>
   <shard>
       <internal_replication>true</internal_replication>
       <replica><host>node1</host></replica>
       <replica><host>node2</host></replica>
   </shard>
</vscluster>
```

**CREATE works! And creates Distributed table on both replicas.**
CREATE TABLE  vs.t1_distrib ON CLUSTER vscluster (ts DATETIME,c1 VARCHAR) ENGINE=Distributed('vscluster','vs','t1')

**ALTER does not work!**
ALTER TABLE vs.t1_distrib ON CLUSTER vscluster ADD COLUMN c2 VARCHAR

Code: 371, e.displayText() = DB::Exception: Table t1_distrib isn't replicated, but shard #1 is replicated according to its cluster definition, e.what() = DB::Exception.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/clickhouse/BmsOrL2AMN4/eQnjeC1CAQAJ

### PR DESCRIPTION
**Pull request by shinoi2**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow ALTER ON CLUSTER of Distributed tables with internal replication. This fixes #3268

### CODE REVIEW

File: dbms/src/Interpreters/DDLWorker.cpp [hunk 1]
```diff
@@ -684,6 +684,12 @@ void DDLWorker::checkShardConfig(const String & table, const DDLTask & task, Sto
     const auto & shard_info = task.cluster->getShardsInfo().at(task.host_shard_num);
     bool config_is_replicated_shard = shard_info.hasInternalReplication();
 
+    if (storage->isDistributed())
```
Comment (alesapin) [inline dbms/src/Interpreters/DDLWorker.cpp]: Maybe we can just check with `dynamic_cast` https://github.com/clickhouse/ClickHouse/blob/master/dbms/src/Interpreters/DDLWorker.cpp#L710?

**Review by alexey-milovidov — APPROVED** [review]
