### PR TITLE
fix a possible crash with join_on_disk_max_files_to_merge

### LINKED ISSUE #84668: Don't set `join_on_disk_max_files_to_merge` too high
### Describe the bug

Easy to reproduce.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/568751ea-5f44-426c-b354-ddaa6f926ac3

### Error message and/or stacktrace

Stack trace:

```
<Fatal> : Logical error: 'std::exception. Code: 1001, type: std::length_error, e.what() = vector (version 25.8.1.1751 (official build)), Stack trace:

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: std::logic_error::logic_error(char const*) @ 0x0000000027257534
1. contrib/llvm-project/libcxx/include/stdexcept:151: std::length_error::length_error[abi:se190107](char const*) @ 0x000000000cd7f989
2. contrib/llvm-project/libcxx/include/stdexcept:240: std::__throw_length_error[abi:se190107](char const*) @ 0x000000000cd7f91f
3. contrib/llvm-project/libcxx/include/vector:999: ? @ 0x000000001779bd8d
4. contrib/llvm-project/libcxx/include/vector:1466: std::vector<DB::Pipe, std::allocator<DB::Pipe>>::reserve(unsigned long) @ 0x00000000179b7009
5. src/Interpreters/SortedBlocksWriter.cpp:244: DB::SortedBlocksWriter::premerge() @ 0x000000001b0d102f
6. src/Interpreters/SortedBlocksWriter.cpp:293: DB::SortedBlocksWriter::finishMerge(std::function<void (DB::Block const&)>) @ 0x000000001b0d1ef4
7. src/Interpreters/MergeJoin.cpp:651: DB::MergeJoin::mergeFlushedRightBlocks() @ 0x000000001b02c71d
8. src/Interpreters/MergeJoin.cpp:593: DB::MergeJoin::setTotals(DB::Block const&) @ 0x000000001b02b88e
9. src/Processors/Transforms/JoiningTransform.cpp:314: DB::FillingRightJoinSideTransform::work() @ 0x000000001e8fa47e
10. src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001e6529d0
11. src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001e645685
12. src/Processors/Executors/PipelineExecutor.cpp:278: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001e645be9
13. src/Processors/Executors/PipelineExecutor.cpp:598: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000001e644121
14. src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001e64383f
15. src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001e65ac24
16. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000141d7fa6
17. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000141de9c0
18. start_thread @ 0x00000000000a27f1
19. __clone3 @ 0x0000000000133c9c
```

### PR DESCRIPTION
**Pull request by bharatnc**
Closes: https://github.com/ClickHouse/ClickHouse/issues/84668

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix a possible crash with `join_on_disk_max_files_to_merge` setting.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by azat — APPROVED** [review]
Looks ok, but why bug fix does not pass?

**Comment by bharatnc** [comment]
> Looks ok, but why bug fix does not pass?

I'm not entirely sure, I'll take a look.

File: tests/queries/0_stateless/03775_join_on_disk_max_files_to_merge.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+-- Fixes issue: https://github.com/ClickHouse/ClickHouse/issues/84668
+
+SELECT count() FROM (SELECT number AS c0 FROM numbers(10000)) tx JOIN (SELECT number AS c0 FROM numbers(10000)) ty ON tx.c0 = ty.c0 SETTINGS default_max_bytes_in_join = 1024, join_on_disk_max_files_to_merge = 18446744073709551615, join_algorithm = 'prefer_partial_merge';
```
Comment (azat) [inline tests/queries/0_stateless/03775_join_on_disk_max_files_to_merge.sql]:
```suggestion
SELECT count() FROM (SELECT number AS c0 FROM numbers(10000)) tx JOIN (SELECT number AS c0 FROM numbers(10000)) ty ON tx.c0 = ty.c0 SETTINGS max_bytes_in_join = 1024, join_on_disk_max_files_to_merge = 18446744073709551615, join_algorithm = 'prefer_partial_merge';
```

**Comment by bharatnc** [comment]
> Looks ok, but why bug fix does not pass?

Thank you for looking into it (in https://github.com/ClickHouse/ClickHouse/pull/92335#discussion_r2657119385). The setting`max_bytes_in_join` had to overridden for the Bug fix validation test to pass on CI - the value was 10G in CI.
