### PR TITLE
fix redis storage get by keys with empty rows

### LINKED ISSUE #81659: Strange error with Redis table
### Describe the bug

The documentation says it's possible to join Redis tables, but in my test case, a strange error occurs.

### How to reproduce

Run:

```sql
CREATE TABLE t0 (c0 Int) ENGINE = Redis('<host:port>', 0, '<password>') PRIMARY KEY (c0);
CREATE  TABLE t1 (c0 Int) ENGINE = MergeTree() ORDER BY tuple();
INSERT INTO TABLE t0 (c0) VALUES (1);
INSERT INTO TABLE t1 (c0) VALUES (1);
SELECT 1 FROM t1 JOIN t0 ON t1.c0 = t0.c0;
/*
Error on processing query 'SELECT 1 FROM t1 INNER JOIN t0 ON t1.c0 = t0.c0': Received from localhost:9000. DB::Exception: Null value
*/
```

### Error message and/or stacktrace

Stack trace:

```
Error on processing query 'SELECT 1 FROM t1 INNER JOIN t0 ON t1.c0 = t0.c0': Received from localhost:9000. DB::Exception: Null value. Stack trace:

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::NullValueException::NullValueException(int) @ 0x000000001d34fc8e
1. base/poco/Foundation/include/Poco/Nullable.h:228: DB::StorageRedis::multiGet(Poco::Redis::Array const&) const @ 0x000000001845f676
2. src/Storages/StorageRedis.cpp:358: DB::StorageRedis::getBySerializedKeys(Poco::Redis::Array const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>*) const @ 0x000000001845edd0
3. src/Storages/StorageRedis.cpp:348: DB::StorageRedis::getBySerializedKeys(std::vector<String, std::allocator<String>> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>*) const @ 0x000000001845ec28
4. src/Storages/StorageRedis.cpp:460: DB::StorageRedis::getByKeys(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&, std::vector<String, std::allocator<String>> const&) const @ 0x00000000184604dd
5. src/Storages/StorageRedis.cpp:0: non-virtual thunk to DB::StorageRedis::getByKeys(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&, std::vector<String, std::allocator<String>> const&) const @ 0x0000000018460750
6. src/Interpreters/DirectJoin.cpp:131: DB::DirectKeyValueJoin::joinBlock(DB::Block&, std::shared_ptr<DB::ExtraBlock>&) @ 0x0000000016dc9aca
7. src/Processors/Transforms/JoiningTransform.cpp:30: DB::JoiningTransform::transformHeader(DB::Block, std::shared_ptr<DB::IJoin> const&) @ 0x00000000192cb0b0
8. src/Processors/QueryPlan/JoinStep.cpp:288: DB::FilledJoinStep::FilledJoinStep(DB::Block const&, std::shared_ptr<DB::IJoin>, unsigned long) @ 0x00000000195320f8
9. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: DB::QueryPlanOptimizations::convertLogicalJoinToPhysical(DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlanOptimizationSettings const&, std::optional<unsigned long>) @ 0x000000001962e8d0
10. src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:165: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000019625497
11. src/Processors/QueryPlan/QueryPlan.cpp:494: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x0000000019554cf4
12. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x0000000016f1cf64
13. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x0000000016f1ccdc
14. src/Interpreters/executeQuery.cpp:1523: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*, std::shared_ptr<DB::IAST>&) @ 0x00000000171f6557
15. src/Interpreters/executeQuery.cpp:1715: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000171f08b1
16. src/Server/TCPHandler.cpp:687: DB::TCPHandler::runImpl() @ 0x0000000018f7a306
17. src/Server/TCPHandler.cpp:2677: DB::TCPHandler::run() @ 0x0000000018f93884
18. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000001d3f3ce7
19. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000001d3f41e5
20. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000001d39c81f
21. base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001d39a3d1
22. start_thread @ 0x00000000000a2ef1
23. __GI___clone3 @ 0x000000000013445c
```

### PR DESCRIPTION
**Pull request by GrigoryPervakov**
DirectJoin is called with an empty block during the planning stage to transform the header.
Currently, in such a case, the redis client would throw, so a valid query cannot be executed.
Closes: #81659

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix StorageRedis join in some cases

### CODE REVIEW

File: src/Storages/StorageRedis.cpp [hunk 1]
```diff
@@ -405,6 +405,9 @@ std::pair<RedisIterator, RedisArray> StorageRedis::scan(RedisIterator iterator,
 
 RedisArray StorageRedis::multiGet(const RedisArray & keys) const
 {
+    if (keys.isNull() || keys.size() == 0)
+        return{};
```
Comment (kssenii) [inline src/Storages/StorageRedis.cpp]:
```suggestion
        return {};
```

File: tests/integration/test_storage_redis/test.py [hunk 2]
```diff
@@ -402,3 +402,34 @@ def test_hiding_credentials(started_cluster):
...
+
+def test_direct_join(started_cluster):
+    address = get_address_for_ch()
+
+    # clean all
+    drop_table("test_direct_join")
+    drop_table("test_mt")
+
+    node.query
+
```
Comment (kssenii) [inline tests/integration/test_storage_redis/test.py]: needs to be removed?

File: tests/integration/test_storage_redis/test.py [hunk 3]
```diff
@@ -402,3 +402,34 @@ def test_hiding_credentials(started_cluster):
...
+        f"""
+            CREATE TABLE test_direct_join(k Int) Engine=Redis('{address}', 0, 'clickhouse') PRIMARY KEY (k);
+            CREATE TABLE test_mt (k Int) ENGINE = MergeTree() ORDER BY tuple();
+            INSERT INTO TABLE test_direct_join VALUES (1);
+            INSERT INTO TABLE test_mt VALUES (1);
+        """
+    )
+
+
+    response = TSV.toMat(node.query("SELECT * FROM test_direct_join JOIN test_mt ON "
```
Comment (kssenii) [inline tests/integration/test_storage_redis/test.py:424]: It does not looks like getting empty rows (the issue which this PR fixes) as both tables have only 1 row with the same value? Or am I just missing how it works?

Comment (GrigoryPervakov) [reply tests/integration/test_storage_redis/test.py:424]: DirectJoin is calling getKeys with an empty rows. I'll check if I can reproduce it without join

Comment (GrigoryPervakov) [reply tests/integration/test_storage_redis/test.py:424]: We have a check during read()
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageRedis.cpp#L243

But I have found another issue while looking there 😁

**Review by kssenii — APPROVED** [review]

**Comment by GrigoryPervakov** [comment]
Performance comparison failed to send the result in s3
CH Inc sync: known flaky backup test
