### PR TITLE
Fix possible cannot-read-all-data in storage FileLog

### LINKED ISSUE #45051: It's possible that FileLog cannot read its metadata after stress test
https://s3.amazonaws.com/clickhouse-test-reports/0/32cc41f0ebc41b4cee425c823de5e051f0eaa888/stress_test__msan_.html

**Describe the bug**
```
2023.01.08 11:23:45.431662 [ 338001 ] {} <Error> DB::StorageFileLog::StorageFileLog(const DB::StorageID &, DB::ContextPtr, const DB::ColumnsDescription &, const DB::String &, const DB::String &, const DB::String &, std::unique_ptr<FileLogSettings>, const DB::String &, bool): Code: 33. DB::Exception: Read meta file store/89e/89e45767-cd48-4bad-adfc-851bc648f329/metadata/a.txt failed. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../contrib/llvm-project/libcxx/include/exception:0: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x57664769 in /usr/bin/clickhouse
1. ./build_docker/../src/Common/Exception.cpp:0: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x296ed193 in /usr/bin/clickhouse
2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0xc61f66e in /usr/bin/clickhouse
3. ./build_docker/../src/Storages/FileLog/StorageFileLog.cpp:0: DB::StorageFileLog::deserialize() @ 0x4986d60b in /usr/bin/clickhouse
4. ./build_docker/../src/Storages/FileLog/StorageFileLog.cpp:144: DB::StorageFileLog::loadMetaFiles(bool) @ 0x49865996 in /usr/bin/clickhouse
5. ./build_docker/../src/Storages/FileLog/StorageFileLog.cpp:106: DB::StorageFileLog::StorageFileLog(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, DB::ColumnsDescription const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::unique_ptr<DB::FileLogSettings, std::__1::default_delete<DB::FileLogSettings>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) @ 0x498611f5 in /usr/bin/clickhouse
6. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:35: std::__1::shared_ptr<DB::StorageFileLog> std::__1::allocate_shared[abi:v15000]<DB::StorageFileLog, std::__1::allocator<DB::StorageFileLog>, DB::StorageID const&, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::unique_ptr<DB::FileLogSettings, std::__1::default_delete<DB::FileLogSettings>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool const&, void>(std::__1::allocator<DB::StorageFileLog> const&, DB::StorageID const&, std::__1::shared_ptr<DB::Context>&&, DB::ColumnsDescription const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::unique_ptr<DB::FileLogSettings, std::__1::default_delete<DB::FileLogSettings>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool const&) @ 0x498aa18a in /usr/bin/clickhouse
7. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962: std::__1::shared_ptr<DB::IStorage> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerStorageFileLog(DB::StorageFactory&)::$_3, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) @ 0x498925f3 in /usr/bin/clickhouse
8. ./build_docker/../src/Storages/StorageFactory.cpp:0: DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x48dcbe37 in /usr/bin/clickhouse
9. ./build_docker/../src/Databases/DatabaseOnDisk.cpp:0: DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x430b457c in /usr/bin/clickhouse
10. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x43124673 in /usr/bin/clickhouse
11. ./build_docker/../src/Databases/TablesLoader.cpp:196: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TablesLoader::startLoadingTables(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, std::__1::shared_ptr<DB::Context>, std::__1::vector<DB::StorageID, std::__1::allocator<DB::StorageID>> const&, unsigned long)::$_1, void ()>>(std::__1::__function::__policy_storage const*) @ 0x43262f2d in /usr/bin/clickhouse
12. ./build_docker/../base/base/wide_integer_impl.h:786: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x29a57ec5 in /usr/bin/clickhouse
13. ./build_docker/../src/Common/ThreadPool.h:197: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x29a64f69 in /usr/bin/clickhouse
14. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:717: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x29a64de9 in /usr/bin/clickhouse
15. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x29a4f1cd in /usr/bin/clickhouse
16. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x29a5d343 in /usr/bin/clickhouse
17. ? @ 0x7fe3bbba7609 in ?
18. clone @ 0x7fe3bbacc133 in ?
 (version 22.13.1.1 (official build))
```

### PR DESCRIPTION
**Pull request by kssenii**
File was not properly written because of out of memory issue
```
2023.01.08 11:01:48.791711 [ 177608 ] {} <Error> void DB::StorageFileLog::threadFunc(): Code: 241. DB::Exception: Memory limit (total) exceeded: would use 52.17 GiB (attempt to allocate chunk of 4969215 bytes), maximum: 34.29 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):
8. ./build_docker/../src/Storages/FileLog/StorageFileLog.cpp:0: DB::StorageFileLog::serialize() const @ 0x14c5a359 in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/../src/Storages/FileLog/StorageFileLog.cpp:457: DB::StorageFileLog::openFilesAndSetPos() @ 0x14c5ecab in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/../contrib/llvm-project/libcxx/include/vector:666: DB::StorageFileLog::streamToViews() @ 0x14c6229a in /usr/lib/debug/usr/bin/clickhouse.debug
11. ./build_docker/../src/Storages/FileLog/StorageFileLog.cpp:590: DB::StorageFileLog::threadFunc() @ 0x14c60d08 in /usr/lib/debug/usr/bin/clickhouse.debug
```
and on server startup we tried to read it and get
```
2023.01.08 11:23:45.431662 [ 338001 ] {} <Error> DB::StorageFileLog::StorageFileLog(const DB::StorageID &, DB::ContextPtr, const DB::ColumnsDescription &, const DB::String &, const DB::String &, const DB::String &, std::unique_ptr<FileLogSettings>, const DB::String &, bool): Code: 33. DB::Exception: Read meta file store/89e/89e45767-cd48-4bad-adfc-851bc648f329/metadata/a.txt failed. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

```

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible cannot-read-all-data error in storage FileLog. Closes https://github.com/ClickHouse/ClickHouse/issues/45051, https://github.com/ClickHouse/ClickHouse/issues/38257.

### CODE REVIEW

File: src/Storages/FileLog/StorageFileLog.cpp [hunk 1]
```diff
@@ -224,76 +224,48 @@ void StorageFileLog::loadFiles()
...
+    try
+    {
+        auto out = disk->writeFile(full_path);
+        writeIntText(inode, *out);
+        writeChar('\n', *out);
+        writeIntText(file_meta.last_writen_position, *out);
+    }
+    catch (...)
+    {
+        disk->removeFile(full_path);
```
Comment (alexey-milovidov) [inline src/Storages/FileLog/StorageFileLog.cpp:251]: This is not reliable because the server can be killed in the middle.
We should solve it by creating a temporary file and renaming it.

**Comment by kssenii** [comment]
> Integration tests (release) [2/4] — fail: 2

test_storage_rabbitmq https://github.com/ClickHouse/ClickHouse/pull/45175
test_multiple_disks https://github.com/ClickHouse/ClickHouse/pull/45180

> Integration tests (asan) [4/6] — fail: 1

test_storage_rabbitmq https://github.com/ClickHouse/ClickHouse/pull/45175

**Review by alexey-milovidov — APPROVED** [review]
