### PR TITLE
Fix use-after-free in Distributed due to race between shutdown and background INSERTs

### LINKED ISSUE #88640: ThreadSanitizer: heap-use-after-free in StorageDistributed::ClusterNodeData
CI: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=88608&sha=5e70ceafe381fb239036cddd604abfb8a26104a3&name_0=PR&name_1=Stateless%20tests%20%28amd_tsan%2C%20s3%20storage%2C%20sequential%2C%201%2F2%29

```
WARNING: ThreadSanitizer: heap-use-after-free (pid=1641)
  Read of size 8 at 0x7258001012b8 by thread T749:
    #0 pthread_cond_signal <null> (clickhouse+0x92e79af) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #1 std::__1::__libcpp_condvar_signal[abi:ne190107](pthread_cond_t*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/support/pthread.h:114:93 (clickhouse+0x2cd9d699) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #2 std::__1::condition_variable::notify_one() ci/tmp/build/./contrib/llvm-project/libcxx/src/condition_variable.cpp:23:50 (clickhouse+0x2cd9d699)
    #3 bool ConcurrentBoundedQueue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::emplaceImpl<true, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(std::__1::optional<unsigned long>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) ci/tmp/build/./src/Common/ConcurrentBoundedQueue.h:59:23 (clickhouse+0x21b653c3) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #4 bool ConcurrentBoundedQueue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::emplace<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) ci/tmp/build/./src/Common/ConcurrentBoundedQueue.h:131:16 (clickhouse+0x21b5b48a) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #5 ConcurrentBoundedQueue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::push(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) ci/tmp/build/./src/Common/ConcurrentBoundedQueue.h:124:16 (clickhouse+0x21b5b48a)
    #6 DB::DistributedAsyncInsertDirectoryQueue::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) ci/tmp/build/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:322:24 (clickhouse+0x21b5b48a)
    #7 DB::DistributedAsyncInsertDirectoryQueue::addFileAndSchedule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, unsigned long) ci/tmp/build/./src/Storages/Distributed/DistributedAsyncInsertDirectoryQueue.cpp:528:5 (clickhouse+0x21b62eb9) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #8 DB::DistributedSink::writeToShard(DB::Cluster::ShardInfo const&, DB::Block const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) ci/tmp/build/./src/Storages/Distributed/DistributedSink.cpp:923:25 (clickhouse+0x21b8735e) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #9 DB::DistributedSink::writeAsyncImpl(DB::Block const&, unsigned long) ci/tmp/build/./src/Storages/Distributed/DistributedSink.cpp:739:13 (clickhouse+0x21b800dd) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #10 DB::DistributedSink::writeAsync(DB::Block const&) ci/tmp/build/./src/Storages/Distributed/DistributedSink.cpp (clickhouse+0x21b7e4f5) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #11 DB::DistributedSink::consume(DB::Chunk&) ci/tmp/build/./src/Storages/Distributed/DistributedSink.cpp:181:9 (clickhouse+0x21b7e4f5)
    #12 DB::SinkToStorage::onConsume(DB::Chunk) ci/tmp/build/./src/Processors/Sinks/SinkToStorage.cpp:10:5 (clickhouse+0x22e9be2c) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #13 DB::ExceptionKeepingTransform::work()::$_1::operator()() const ci/tmp/build/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:134:51 (clickhouse+0x22d184a5) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #14 decltype(std::declval<DB::ExceptionKeepingTransform::work()::$_1&>()()) std::__1::__invoke[abi:ne190107]<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x22d184a5)
    #15 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne190107]<DB::ExceptionKeepingTransform::work()::$_1&>(DB::ExceptionKeepingTransform::work()::$_1&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224:5 (clickhouse+0x22d184a5)
    #16 std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12 (clickhouse+0x22d184a5)
    #17 void std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__1::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12 (clickhouse+0x22d184a5)
    #18 std::__1::__function::__policy_func<void ()>::operator()[abi:ne190107]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12 (clickhouse+0x22d181b3) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #19 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10 (clickhouse+0x22d181b3)
    #20 DB::runStep(std::__1::function<void ()>, std::__1::shared_ptr<DB::ThreadGroup>&) ci/tmp/build/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:103:9 (clickhouse+0x22d181b3)
    #21 DB::ExceptionKeepingTransform::work() ci/tmp/build/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:134:34 (clickhouse+0x22d177f3) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #22 DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53:26 (clickhouse+0x22940851) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #23 DB::ExecutionThreadContext::executeTask() ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:102:9 (clickhouse+0x22940851)
    #24 DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::__1::atomic<bool>*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:351:26 (clickhouse+0x2292d257) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #25 DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:179:5 (clickhouse+0x2292cc19) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #26 DB::PushingPipelineExecutor::finish() ci/tmp/build/./src/Processors/Executors/PushingPipelineExecutor.cpp:131:47 (clickhouse+0x22951c4d) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #27 DB::SystemLog<DB::ErrorLogElement>::flushImpl(std::__1::vector<DB::ErrorLogElement, std::__1::allocator<DB::ErrorLogElement>> const&, unsigned long) ci/tmp/build/./src/Interpreters/SystemLog.cpp:691:18 (clickhouse+0x1cbce9fe) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #28 DB::SystemLog<DB::ErrorLogElement>::savingThreadFunction() ci/tmp/build/./src/Interpreters/SystemLog.cpp:613:17 (clickhouse+0x1cbcca2e) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #29 DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()::operator()() const ci/tmp/build/./src/Common/SystemLogBase.cpp:292:69 (clickhouse+0x139f9718) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #30 decltype(std::declval<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&>()()) std::__1::__invoke[abi:ne190107]<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x139f9718)
    #31 decltype(auto) std::__1::__apply_tuple_impl[abi:ne190107]<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&, std::__1::tuple<>&>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1354:5 (clickhouse+0x139f9718)
    #32 decltype(auto) std::__1::apply[abi:ne190107]<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&, std::__1::tuple<>&>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&, std::__1::tuple<>&) ci/tmp/build/./contrib/llvm-project/libcxx/include/tuple:1358:5 (clickhouse+0x139f9718)
    #33 ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&)::'lambda'()::operator()() ci/tmp/build/./src/Common/ThreadPool.h:312:13 (clickhouse+0x139f9718)
    #34 decltype(std::declval<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>()()) std::__1::__invoke[abi:ne190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&)::'lambda'()&>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149:25 (clickhouse+0x139f9661) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #35 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&)::'lambda'()&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224:5 (clickhouse+0x139f9661)
    #36 std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&)::'lambda'(), void ()>::operator()[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:210:12 (clickhouse+0x139f9661)
    #37 void std::__1::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::ErrorLogElement>::startup()::'lambda'()&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:610:12 (clickhouse+0x139f9661)
    #38 std::__1::__function::__policy_func<void ()>::operator()[abi:ne190107]() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:716:12 (clickhouse+0x13979be2) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #39 std::__1::function<void ()>::operator()() const ci/tmp/build/./contrib/llvm-project/libcxx/include/__functional/function.h:989:10 (clickhouse+0x13979be2)
    #40 ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::worker() ci/tmp/build/./src/Common/ThreadPool.cpp:812:17 (clickhouse+0x13979be2)
    #41 decltype(*std::declval<ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)()>()()) std::__1::__invoke[abi:ne190107]<void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*&&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117:25 (clickhouse+0x13982c9b) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #42 void std::__1::__thread_execute[abi:ne190107]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>&, std::__1::__tuple_indices<2ul>) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:192:3 (clickhouse+0x13982c9b)
    #43 void* std::__1::__thread_proxy[abi:ne190107]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::__1::thread>::ThreadFromThreadPool*>>(void*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/thread.h:201:3 (clickhouse+0x13982c9b)

  Previous write of size 8 at 0x7258001012b8 by thread T3580 (mutexes: write M0, write M1):
    #0 operator delete(void*, unsigned long) <null> (clickhouse+0x9368b58) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #1 std::__1::default_delete<DB::DistributedAsyncInsertDirectoryQueue>::operator()[abi:ne190107](DB::DistributedAsyncInsertDirectoryQueue*) const ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:80:5 (clickhouse+0x213e31b9) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #2 std::__1::__shared_ptr_pointer<DB::DistributedAsyncInsertDirectoryQueue*, std::__1::default_delete<DB::DistributedAsyncInsertDirectoryQueue>, std::__1::allocator<DB::DistributedAsyncInsertDirectoryQueue>>::__on_zero_shared() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:227:3 (clickhouse+0x213e31b9)
    #3 std::__1::__shared_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:156:7 (clickhouse+0x213dff27) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #4 std::__1::__shared_weak_count::__release_shared[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:185:25 (clickhouse+0x213dff27)
    #5 std::__1::shared_ptr<DB::DistributedAsyncInsertDirectoryQueue>::~shared_ptr[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:668:17 (clickhouse+0x213dff27)
    #6 DB::StorageDistributed::ClusterNodeData::~ClusterNodeData() ci/tmp/build/./src/Storages/StorageDistributed.h:272:12 (clickhouse+0x213dff27)
    #7 std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::StorageDistributed::ClusterNodeData>::~pair() ci/tmp/build/./contrib/llvm-project/libcxx/include/__utility/pair.h:65:29 (clickhouse+0x213dff27)
    #8 void std::__1::__destroy_at[abi:ne190107]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::StorageDistributed::ClusterNodeData>, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::StorageDistributed::ClusterNodeData>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/construct_at.h:67:11 (clickhouse+0x213c8bd5) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #9 void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, void*>>>::destroy[abi:ne190107]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::StorageDistributed::ClusterNodeData>, void, 0>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, void*>>&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::StorageDistributed::ClusterNodeData>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:339:5 (clickhouse+0x213c8bd5)
    #10 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>>>::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, void*>*>*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__hash_table:1139:5 (clickhouse+0x213c8bd5)
    #11 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData>>>::clear() ci/tmp/build/./contrib/llvm-project/libcxx/include/__hash_table:1315:5 (clickhouse+0x213c8bd5)
    #12 std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::StorageDistributed::ClusterNodeData, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::StorageDistributed::ClusterNodeData>>>::clear[abi:ne190107]() ci/tmp/build/./contrib/llvm-project/libcxx/include/unordered_map:1326:59 (clickhouse+0x213c8bd5)
    #13 DB::StorageDistributed::shutdown(bool) ci/tmp/build/./src/Storages/StorageDistributed.cpp:1524:24 (clickhouse+0x213c8bd5)
    #14 DB::IStorage::flushAndShutdown(bool) ci/tmp/build/./src/Storages/IStorage.h:589:9 (clickhouse+0x1c82cd3b) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #15 DB::InterpreterDropQuery::executeToTableImpl(std::__1::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:306:20 (clickhouse+0x1c82cd3b)
    #16 DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:122:16 (clickhouse+0x1c82ae14) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #17 DB::InterpreterDropQuery::executeSingleDropQuery(std::__1::shared_ptr<DB::IAST> const&) ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:95:16 (clickhouse+0x1c829fc9) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #18 DB::InterpreterDropQuery::execute() ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:76:15 (clickhouse+0x1c829ccf) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #19 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer>>&, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::__1::function<void ()>) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1603:40 (clickhouse+0x1cd88b00) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #20 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1812:11 (clickhouse+0x1cd8288d) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #21 DB::TCPHandler::runImpl() ci/tmp/build/./src/Server/TCPHandler.cpp:744:68 (clickhouse+0x227e5b2f) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #22 DB::TCPHandler::run() ci/tmp/build/./src/Server/TCPHandler.cpp:2818:9 (clickhouse+0x2280ef67) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #23 Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3 (clickhouse+0x2a16df22) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #24 Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38 (clickhouse+0x2a16e7f1) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #25 Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14 (clickhouse+0x2a0dd410) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #26 Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x2a0db5ef) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #27 Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:341:27 (clickhouse+0x2a0d9849) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)

  Mutex M0 (0x720c03606ed0) created at:
    #0 pthread_mutex_lock <null> (clickhouse+0x92e81ce) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #1 std::__1::__libcpp_mutex_lock[abi:ne190107](pthread_mutex_t*) ci/tmp/build/./contrib/llvm-project/libcxx/include/__thread/support/pthread.h:95:10 (clickhouse+0x2ce21599) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #2 std::__1::mutex::lock() ci/tmp/build/./contrib/llvm-project/libcxx/src/mutex.cpp:29:12 (clickhouse+0x2ce21599)
    #3 std::__1::unique_lock<std::__1::mutex>::unique_lock[abi:ne190107](std::__1::mutex&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__mutex/unique_lock.h:42:11 (clickhouse+0x1c6ddbdd) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #4 DB::DDLGuard::DDLGuard(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::DDLGuard::Entry, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::DDLGuard::Entry>>>&, DB::SharedMutex&, std::__1::unique_lock<std::__1::mutex>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) ci/tmp/build/./src/Interpreters/DatabaseCatalog.cpp:2063:18 (clickhouse+0x1c6ddbdd)
    #5 std::__1::__unique_if<DB::DDLGuard>::__unique_single std::__1::make_unique[abi:ne190107]<DB::DDLGuard, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::DDLGuard::Entry, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::DDLGuard::Entry>>>&, DB::SharedMutex&, std::__1::unique_lock<std::__1::mutex>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::DDLGuard::Entry, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::DDLGuard::Entry>>>&, DB::SharedMutex&, std::__1::unique_lock<std::__1::mutex>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) ci/tmp/build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634:30 (clickhouse+0x1c6c7a0e) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #6 DB::DatabaseCatalog::getDDLGuard(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) ci/tmp/build/./src/Interpreters/DatabaseCatalog.cpp:1007:12 (clickhouse+0x1c6c7a0e)
    #7 DB::InterpreterDropQuery::executeToTableImpl(std::__1::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::__1::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:146:72 (clickhouse+0x1c82b920) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #8 DB::InterpreterDropQuery::executeToTable(DB::ASTDropQuery&) ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:122:16 (clickhouse+0x1c82ae14) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #9 DB::InterpreterDropQuery::executeSingleDropQuery(std::__1::shared_ptr<DB::IAST> const&) ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:95:16 (clickhouse+0x1c829fc9) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #10 DB::InterpreterDropQuery::execute() ci/tmp/build/./src/Interpreters/InterpreterDropQuery.cpp:76:15 (clickhouse+0x1c829ccf) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #11 DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::__1::unique_ptr<DB::ReadBuffer, std::__1::default_delete<DB::ReadBuffer>>&, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::ImplicitTransactionControlExecutor>, std::__1::function<void ()>) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1603:40 (clickhouse+0x1cd88b00) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #12 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) ci/tmp/build/./src/Interpreters/executeQuery.cpp:1812:11 (clickhouse+0x1cd8288d) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #13 DB::TCPHandler::runImpl() ci/tmp/build/./src/Server/TCPHandler.cpp:744:68 (clickhouse+0x227e5b2f) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #14 DB::TCPHandler::run() ci/tmp/build/./src/Server/TCPHandler.cpp:2818:9 (clickhouse+0x2280ef67) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #15 Poco::Net::TCPServerConnection::start() ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40:3 (clickhouse+0x2a16df22) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #16 Poco::Net::TCPServerDispatcher::run() ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115:38 (clickhouse+0x2a16e7f1) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #17 Poco::PooledThread::run() ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205:14 (clickhouse+0x2a0dd410) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #18 Poco::(anonymous namespace)::RunnableHolder::run() ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45:11 (clickhouse+0x2a0db5ef) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)
    #19 Poco::ThreadImpl::runnableEntry(void*) ci/tmp/build/./base/poco/Foundation/src/Thread_POSIX.cpp:341:27 (clickhouse+0x2a0d9849) (BuildId: 7f0ffee6f15d3e138ce7b5eaef9ac7b210fc21b2)

```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):
Fix use-after-free in Distributed due to race between shutdown and background INSERTs. Resolves #88640

### Details
`StorageDistributed::shutdown()` clears all `DistributedAsyncInsertDirectoryQueue`, but DistributedSink may hold a reference to `DistributedAsyncInsertDirectoryQueue`, and this will lead to use-after-free.

Simply returning `shared_ptr` from `getDirectoryQueue()` should be enough to fix it, since in case of `shutdown`/`TRUNCATE` the `pending_files` (which modified by the `addFileAndSchedule()`) should be stopped (which prevents adding new files after shutdown), and also the task for sending data to remote nodes (`task_handle`) also joined (which will make sure that newly added files will not be sent after shutdown).

Resolves #88640

### CODE REVIEW

File: src/Storages/StorageDistributed.cpp [hunk 1]
```diff
@@ -1645,7 +1645,7 @@ DistributedAsyncInsertDirectoryQueue & StorageDistributed::getDirectoryQueue(con
             async_insert_blocker,
             getContext()->getDistributedSchedulePool());
     }
-    return *node_data.directory_queue;
+    return node_data.directory_queue;
```
Comment (CheSema) [inline src/Storages/StorageDistributed.cpp:1648]: I do not follow the logic here.
Do you move pointer from `node_data.directory_queue` to the return function value and convert it from uniq to shared ptr?

It looks like `node_data.directory_queue` should be created as shared ptr.

Comment (azat) [reply src/Storages/StorageDistributed.cpp:1648]: Egh, missed that it uses `make_unique` (though the type of `node_data.directory_queue` is `shared_ptr<>`, so everything should be OK).

Fixed, good catch, thanks.

**Comment by azat** [comment]
@CheSema there is also one small related change, maybe you can also take a look https://github.com/ClickHouse/ClickHouse/pull/89135?

**Review by CheSema — APPROVED** [review]
