### PR TITLE
Some fixes for parallel replicas

### LINKED ISSUE #48302: Logical error: Final modifier is not supported with parallel replicas
https://s3.amazonaws.com/clickhouse-test-reports/0/99194d0ff89069291971254be16345cfc1beebc2/fuzzer_astfuzzerasan/report.html

```
2023.03.31 19:09:21.111892 [ 159 ] {757442e0-08bc-43ee-8cb4-6e2b226aa659} <Fatal> : Logical error: 'Final modifier is not supported with parallel replicas'.
2023.03.31 19:09:21.112564 [ 520 ] {} <Fatal> BaseDaemon: ########################################
2023.03.31 19:09:21.112673 [ 520 ] {} <Fatal> BaseDaemon: (version 23.4.1.1 (official build), build id: B69DE92C25798DB18C24FFEB52A6E8284D6066C2) (from thread 159) (query_id: 757442e0-08bc-43ee-8cb4-6e2b226aa659) (query: EXPLAIN ESTIMATE  SELECT * FROM prewhere_move_select_final FINAL WHERE x > 100) Received signal Aborted (6)
2023.03.31 19:09:21.112749 [ 520 ] {} <Fatal> BaseDaemon: 
2023.03.31 19:09:21.112862 [ 520 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f2bef5cf00b 0x7f2bef5ae859 0x20274c3b 0x20275a81 0xfe8888d 0x36e14a1b 0x36e175ce 0x36d7c618 0x36dc7d8c 0x32bde4cb 0x32bdb41b 0x3392b206 0x3392470c 0x3622257e 0x362570bb 0x3e07e6ef 0x3e07f445 0x3e543c3c 0x3e53d14d 0x7f2bef786609 0x7f2bef6ab133
2023.03.31 19:09:21.112963 [ 520 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f2bef5cf00b in ?
2023.03.31 19:09:21.113051 [ 520 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f2bef5ae859 in ?
2023.03.31 19:09:21.275908 [ 520 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:41: DB::abortOnFailedAssertion(String const&) @ 0x20274c3b in /workspace/clickhouse
2023.03.31 19:09:21.431607 [ 520 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/./src/Common/Exception.cpp:64: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
2023.03.31 19:09:21.431702 [ 520 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x20275a81 in /workspace/clickhouse
2023.03.31 19:09:28.300074 [ 520 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<char const (&) [55], void>(int, char const (&) [55]) @ 0xfe8888d in /workspace/clickhouse
2023.03.31 19:09:29.005175 [ 520 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Processors/QueryPlan/ReadFromMergeTree.cpp:0: DB::ReadFromMergeTree::spreadMarkRanges(DB::RangesInDataParts&&, unsigned long, DB::ReadFromMergeTree::AnalysisResult&, std::shared_ptr<DB::ActionsDAG>&) @ 0x36e14a1b in /workspace/clickhouse
2023.03.31 19:09:29.528222 [ 520 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./src/QueryPipeline/Pipe.h:103: DB::Pipe::getProcessors() const
2023.03.31 19:09:29.528311 [ 520 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Processors/QueryPlan/ReadFromMergeTree.cpp:1669: DB::ReadFromMergeTree::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x36e175ce in /workspace/clickhouse
2023.03.31 19:09:29.580129 [ 520 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Processors/QueryPlan/ISourceStep.cpp:24: DB::ISourceStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x36d7c618 in /workspace/clickhouse
2023.03.31 19:09:29.718374 [ 520 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>::reset[abi:v15000](DB::QueryPipelineBuilder*)
2023.03.31 19:09:29.718480 [ 520 ] {} <Fatal> BaseDaemon: 11.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:225: std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>::operator=[abi:v15000](std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>&&)
2023.03.31 19:09:29.718534 [ 520 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Processors/QueryPlan/QueryPlan.cpp:187: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x36dc7d8c in /workspace/clickhouse
2023.03.31 19:09:29.941774 [ 520 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:0: DB::InterpreterExplainQuery::executeImpl() @ 0x32bde4cb in /workspace/clickhouse
2023.03.31 19:09:30.153756 [ 520 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Interpreters/InterpreterExplainQuery.cpp:88: DB::InterpreterExplainQuery::execute() @ 0x32bdb41b in /workspace/clickhouse
2023.03.31 19:09:30.591117 [ 520 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x3392b206 in /workspace/clickhouse
2023.03.31 19:09:31.068769 [ 520 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./src/Interpreters/executeQuery.cpp:1160: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x3392470c in /workspace/clickhouse
2023.03.31 19:09:31.358531 [ 520 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x3622257e in /workspace/clickhouse
2023.03.31 19:09:31.864826 [ 520 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./src/Server/TCPHandler.cpp:2039: DB::TCPHandler::run() @ 0x362570bb in /workspace/clickhouse
2023.03.31 19:09:31.876573 [ 520 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x3e07e6ef in /workspace/clickhouse
2023.03.31 19:09:31.897564 [ 520 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<Poco::Net::TCPServerConnection>::operator()[abi:v15000](Poco::Net::TCPServerConnection*) const
2023.03.31 19:09:31.897662 [ 520 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2023.03.31 19:09:31.897720 [ 520 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.03.31 19:09:31.897761 [ 520 ] {} <Fatal> BaseDaemon: 19. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x3e07f445 in /workspace/clickhouse
2023.03.31 19:09:31.923822 [ 520 ] {} <Fatal> BaseDaemon: 20. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x3e543c3c in /workspace/clickhouse
2023.03.31 19:09:31.945402 [ 520 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::get()
2023.03.31 19:09:31.945483 [ 520 ] {} <Fatal> BaseDaemon: 21.2. inlined from ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::assign(Poco::Runnable*)
2023.03.31 19:09:31.945540 [ 520 ] {} <Fatal> BaseDaemon: 21.3. inlined from ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:180: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::operator=(Poco::Runnable*)
2023.03.31 19:09:31.945581 [ 520 ] {} <Fatal> BaseDaemon: 21. ./build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x3e53d14d in /workspace/clickhouse
2023.03.31 19:09:31.945644 [ 520 ] {} <Fatal> BaseDaemon: 22. ? @ 0x7f2bef786609 in ?
2023.03.31 19:09:31.945693 [ 520 ] {} <Fatal> BaseDaemon: 23. clone @ 0x7f2bef6ab133 in ?
2023.03.31 19:09:32.849803 [ 520 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: CBB3F0645A06EB0A75F41722A637402B)
2023.03.31 19:11:03.111908 [ 150 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### LINKED ISSUE #48367: Attempting to upgrade to 23.2 or 23.3.. version results in Not found column count() in block on aggregations
I was attempting to upgrade clickhouse from version 23.1 to either 23.2 or 23.3 but all aggregation queries are failing. select * works. Rolled back and it works fine.  below is a result of doing  a select count() from table.. 

```:Exception: Not found column count() in block. There are only columns: . (NOT_FOUND_COLUMN_IN_BLOCK)```

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Previously when setting only `allow_experimental_parallel_reading_from_replicas` to 1 some queries could end up with an error like `column in not find a block`. This is now fixed. Closes: #48367
- Changed error code `LOGICAL_ERROR` to `SUPPORT_IS_DISABLED` when we see that there is a query with FINAL modifier and parallel replicas deep inside the code. While we will try to execute a query without parallel replicas in that case, the user may still receive such an error. Closes: #48302

### CODE REVIEW

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -462,6 +462,20 @@ InterpreterSelectQuery::InterpreterSelectQuery(
         context->setSetting("parallel_replicas_custom_key", String{""});
     }
 
+    /// Try to execute query without parallel replicas if we find that there is a FINAL modifier there.
+    bool is_query_with_final = false;
+    if (query_info.table_expression_modifiers)
+        is_query_with_final = query_info.table_expression_modifiers->hasFinal();
+    else if (query_info.query)
+        is_query_with_final = query_info.query->as<ASTSelectQuery &>().final();
```
Comment (KochetovNicolai) [inline src/Interpreters/InterpreterSelectQuery.cpp:470]: `ReadFromMergeTree::isFinal(const SelectQueryInfo & query_info)`?

**Review by KochetovNicolai — APPROVED** [review]
