### PR TITLE
Fix too many watches in ReplicatedMergeTree while waiting for log entry

### LINKED ISSUE #94132: Logical error: 'callbacks.size() <= WATCHES_CALLBACK_SANITY_LIMIT'
CI: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=5a8ca8dd0d2cb04dbff8b8f51bc3b84db561846b&name_0=MasterCI&name_1=BuzzHouse%20%28amd_ubsan%29&name_1=BuzzHouse%20%28amd_ubsan%29

```
Error:
Logical error: 'callbacks.size() <= WATCHES_CALLBACK_SANITY_LIMIT'.
---

Stack trace:
__pthread_kill @ 0x00000000000969fd
gsignal @ 0x0000000000042476
__lgamma_r_finite @ 0x00000000000287f3
src/Common/Exception.cpp:57: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x00000000203ec21d
src/Common/Exception.cpp:63: ? @ 0x00000000203ec749
src/Common/ZooKeeper/ZooKeeperImpl.cpp:1092: Coordination::ZooKeeper::receiveEvent()::$_1::operator()(std::shared_ptr<Coordination::ZooKeeperRequest> const&, std::shared_ptr<Coordination::Response> const&, Coordination::WatchCallbackPtrOrEventPtr const&) const @ 0x000000003038032a
src/Common/ZooKeeper/ZooKeeperImpl.cpp:1126: Coordination::ZooKeeper::receiveEvent() @ 0x000000003037e74b
src/Common/ZooKeeper/ZooKeeperImpl.cpp:905: Coordination::ZooKeeper::receiveThread() @ 0x000000003037d4e9
src/Common/ZooKeeper/ZooKeeperImpl.cpp:462: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&>::type std::__invoke[abi:ne210105]<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&)
inlined from ./contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:ne210105]<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&, std::tuple<>&>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&, std::tuple<>&, std::__tuple_indices<...>)
inlined from ./contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:ne210105]<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&, std::tuple<>&>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&, std::tuple<>&)
inlined from ./src/Common/ThreadPool.h:312: operator()
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&&)::'lambda'()&>::type std::__invoke[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&&)::'lambda'()&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&&)::'lambda'()&)
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1 std::__invoke_r[abi:ne210105]<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1>(Coordination::ZooKeeper::ZooKeeper(std::vector<zkutil::ShuffleHost, std::allocator<zkutil::ShuffleHost>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>, std::shared_ptr<DB::AggregatedZooKeeperLog>)::$_1&&)::'lambda'()&>()
./contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000003038b6e3
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from ./contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000002056efb8
inlined from ./contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: std::__invoke_result_impl<void, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>::type std::__invoke[abi:ne210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
inlined from ./contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:ne210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
./contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:ne210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000020575faa
start_thread @ 0x0000000000094ac3
__GI___clone3 @ 0x00000000001268c0
```

In server logs

```
2026.01.13 22:26:29.284613 [ 1334 ] {} <Warning> ZooKeeperClient: Too many watches for path /clickhouse/tables/ccfd27b6-6911-48cc-a79f-9f1d192f7c00/s1/replicas/r1/log_pointer: 9997 (This is likely an error)
2026.01.13 22:26:29.285304 [ 1334 ] {} <Warning> ZooKeeperClient: Too many watches for path /clickhouse/tables/ccfd27b6-6911-48cc-a79f-9f1d192f7c00/s1/replicas/r1/log_pointer: 9998 (This is likely an error)
2026.01.13 22:26:29.285917 [ 1334 ] {} <Warning> ZooKeeperClient: Too many watches for path /clickhouse/tables/ccfd27b6-6911-48cc-a79f-9f1d192f7c00/s1/replicas/r1/log_pointer: 9999 (This is likely an error)
2026.01.13 22:26:29.286629 [ 1334 ] {} <Warning> ZooKeeperClient: Too many watches for path /clickhouse/tables/ccfd27b6-6911-48cc-a79f-9f1d192f7c00/s1/replicas/r1/log_pointer: 10000 (This is likely an error)
```

And this is

```
2026.01.13 22:24:02.308870 [ 606 ] {88af4f9f-aaa8-4684-9366-fac3693da6fa} <Debug> DatabaseReplicated (d0): Proposing query: CREATE TABLE t175 UUID 'ccfd27b6-6911-48cc-a79f-9f1d192f7c00' (`c0` LowCardinality(Nullable(String)) SETTINGS (min_compress_block_size = 0)) ENGINE = ReplicatedSummingMergeTree PARTITION BY c0 PRIMARY KEY c0 ORDER BY c0
```

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix too many watches in ReplicatedMergeTree while waiting for log entry

Fixes: https://github.com/ClickHouse/ClickHouse/issues/94132

### Version info
- Merged into: `26.1.1.744`

### CODE REVIEW

**Comment by PedroTadim** [comment]
Add a test? I can try to reduce the test case

**Comment by azat** [comment]
@PedroTadim thanks, that would be great!

**Comment by PedroTadim** [comment]
> @PedroTadim thanks, that would be great!

Reproduced it. Reducing the script.

**Comment by PedroTadim** [comment]
It's a bad use case. There is a partition key, and it ends up with many parts with few rows each. The size of the inserts could be reduced further still.
```sql
SET throw_on_max_partitions_per_insert_block = 0;
CREATE TABLE t0 (c0 String) ENGINE = ReplicatedSummingMergeTree() ORDER BY (c0) PARTITION BY (c0) PRIMARY KEY (c0);
INSERT INTO TABLE t0 (c0) SELECT c0 FROM generateRandom('c0 String', 6027844971511223261, 174, 13) LIMIT 1450;
INSERT INTO TABLE t0 (c0) SELECT c0 FROM generateRandom('c0 String', 5464182748884687427, 61, 22) LIMIT 3583;
INSERT INTO TABLE t0 (c0) SELECT c0 FROM generateRandom('c0 String', 4085951178204172438, 414, 20) LIMIT 3661;
INSERT INTO TABLE t0 (c0) SELECT NULL FROM numbers(3286);
INSERT INTO TABLE t0 (c0) SELECT CAST((-number) % 22 AS String) FROM numbers(849);
INSERT INTO TABLE t0 (c0) SELECT CAST((-number) AS String) FROM numbers(2746);
TRUNCATE t0;
```

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 1]
```diff
@@ -7282,12 +7282,12 @@ bool StorageReplicatedMergeTree::tryWaitForReplicaToProcessLogEntry(
 
         LOG_DEBUG(log, "Waiting for {} to pull {} to queue", replica, log_node_name);
 
+        Coordination::EventPtr event = std::make_shared<Poco::Event>();
```
Comment (Michicosun) [inline src/Storages/StorageReplicatedMergeTree.cpp]: You need to call reset on this event now, after the timeout exceeded error, because the internal state of this event after the first watch will not be automatically rolled back

Comment (azat) [reply src/Storages/StorageReplicatedMergeTree.cpp]: Indeed, thanks. Fixed.

Comment (azat) [reply src/Storages/StorageReplicatedMergeTree.cpp]: And it was actually not enough, since in case of lots of partitions, we need to create object earlier (not in this function), now also fixed

**Comment by azat** [comment]
@PedroTadim thanks a lot for the test, I've adopted it and added

**Review by Michicosun — APPROVED** [review]

**Comment by azat** [comment]
Ok, let's merge it this way, and I will take a look at reworking of wathces in ZooKeeper client
