### PR TITLE
Fix Alter ttl modification unsupported table engine

### LINKED ISSUE #33344: Block TTL's for Distributed tables during alters
Right now clickhouse allows to create TTL columns for Distributed tables during alters. It is working normally until server restart. After that it won't start because engine distributed doesn't support TTL clause. Modify metadata is required.

My cluster has 21.3 but tested it also with 21.11 and the same behavior.
It is blocked during create but it should be also be blocked during alters.
Tested on table from tutorial
ENGINE = Distributed('stage, 'default', 'hits_v1') 
alter table hits_v1_all modify column UTMCampaign String TTL EventDate + INTERVAL 1 MONTH ← it passes normally

### PR DESCRIPTION
**Pull request by zhongyuankai**
Changelog category (leave one):

- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Disallow ALTER TTL for engines that does not support it, to avoid breaking ATTACH TABLE (closes #33344)

### CODE REVIEW

File: src/Storages/StorageDistributed.cpp [hunk 1]
```diff
@@ -800,6 +800,9 @@ void StorageDistributed::checkAlterIsPossible(const AlterCommands & commands, Co
                     ErrorCodes::ALTER_OF_COLUMN_IS_FORBIDDEN);
             }
         }
+
+        if (command.ttl)
+            throw Exception("Engine Distributed doesn't support TTL clause", ErrorCodes::NOT_IMPLEMENTED);
```
Comment (azat) [inline src/Storages/StorageDistributed.cpp:805]: The same applies for other tables (i.e. Buffer/Merge/...), so maybe it is better to look at supports_ttl storage feature.
And also worth adding a test to avoid problems in future (`ALTER`/`DETACH`/`ATTACH` should be enough I guess)

Comment (zhongyuankai) [reply src/Storages/StorageDistributed.cpp:805]: OK, I checked it, and currently only `merge tree` supports ttl, so I want to add the `supportsTTL` interface to `IStorage`. What do you think?

File: src/Storages/IStorage.h [hunk 2]
```diff
@@ -132,6 +132,9 @@ class IStorage : public std::enable_shared_from_this<IStorage>, public TypePromo
     /// Returns true if the storage supports insert queries with the PARTITION BY section.
     virtual bool supportsPartitionBy() const { return false; }
 
+    /// Returns true if the storage supports queries with the TTL section.
+    virtual bool supportsTTL() const { return false; }
```
Comment (azat) [inline src/Storages/IStorage.h:136]: Let's also add a comment in https://github.com/ClickHouse/ClickHouse/blob/98a94eae7d63fcfb0ec2d7ac62096adc09989a61/src/Storages/StorageFactory.h#L62

File: src/Storages/AlterCommands.h [hunk 3]
```diff
@@ -186,7 +186,7 @@ class AlterCommands : public std::vector<AlterCommand>
     /// Checks that all columns exist and dependencies between them.
     /// This check is lightweight and base only on metadata.
     /// More accurate check have to be performed with storage->checkAlterIsPossible.
-    void validate(const StorageInMemoryMetadata & metadata, ContextPtr context) const;
+    void validate(StoragePtr table, ContextPtr context) const;
```
Comment (azat) [inline src/Storages/AlterCommands.h:189]:
```suggestion
    void validate(const StoragePtr & table, ContextPtr context) const;
```

**Review by azat — COMMENTED** [review]
Yes, now it looks like it should fix all engines.
Also I think it worth to add a test (you don't need to restart the server, simple ATTACH/DETACH should be the same)

File: src/Storages/IStorage.h (hunk 2 above)
Comment (zhongyuankai) [reply src/Storages/IStorage.h:136]: Yes, both need to be consistent.

**Comment by zhongyuankai** [comment]
> Yes, now it looks like it should fix all engines. Also I think it worth to add a test (you don't need to restart the server, simple ATTACH/DETACH should be the same)

OK, but I'm not quite sure if the current tests are enough.

File: tests/queries/0_stateless/02163_storage_add_support_ttl.sql [hunk 4]
```diff
@@ -0,0 +1,9 @@
+DROP TABLE IF EXISTS 02163_test_tb;
+
+CREATE TABLE 02163_test_tb (id UInt64, name String, dt Date) Engine=MergeTree ORDER BY id;
```
Comment (azat) [inline tests/queries/0_stateless/02163_storage_add_support_ttl.sql:3]: >OK, but I'm not quite sure if the current tests are enough.

Not enough, since this is only covers MergeTree table. You need to also add a test for others, i.e. Distributed/Merge/Buffer/Memory/Log/TinyLog

stateless tests support jinja2 templates (.sql.j2/.reference.j2), so you can either use it (to avoid copy-paste), or write test in bash (.sh)

Comment (zhongyuankai) [reply tests/queries/0_stateless/02163_storage_add_support_ttl.sql:3]: Ok, but when I receive `Engine Distributed doesn't support TTL`, how should I make the test pass, I need some hints.

Comment (azat) [reply tests/queries/0_stateless/02163_storage_add_support_ttl.sql:3]: Sure:

```sql
DROP TABLE IF EXISTS null_02163;
CREATE TABLE null_02163 AS system.one Engine=Null();
ALTER TABLE null_02163 MODIFY COLUMN dummy Int TTL now() + INTERVAL 1 MONTH; -- { serverError BAD_ARGUMENTS }
DETACH TABLE null_02163;
ATTACH TABLE null_02163;
```

(for tests clickhouse-client supports some hints, like `serverError` - https://github.com/ClickHouse/ClickHouse/blob/dd2779fadc1874846b52839ef18244aedb8636fc/src/Client/TestHint.h#L10-L42)

**Comment by zhongyuankai** [comment]
@azat Thank you for your hint, I have completed the test, but `02156_storage_merge_prewhere` cannot pass, it seems that it has nothing to do with the current changes.

**Comment by azat** [comment]
> but 02156_storage_merge_prewhere cannot pass, it seems that it has nothing to do with the current changes.

Right, you can ignore this failure.

**Comment by zhongyuankai** [comment]
@azat Can this patch be merged to master?

**Comment by azat** [comment]
I think yes, at least it looks good to me, so let's ask someone who can merge, @alexey-milovidov can you take a look?

By the way @zhongyuankai it worth rebase from master (to fix that unrelated test failure and update the build, maybe something had been changed, but I don't remember such things) and update description since now it is not only about distributed engine. Also your description doesn't match the template.

**Comment by zhongyuankai** [comment]
> I think yes, at least it looks good to me, so let's ask someone who can merge, @alexey-milovidov can you take a look?
> 
> By the way @zhongyuankai it worth rebase from master (to fix that unrelated test failure and update the build, maybe something had been changed, but I don't remember such things) and update description since now it is not only about distributed engine. Also your description doesn't match the template.

@azat ok thanks, @alexey-milovidov can you help review this patch!

**Comment by zhongyuankai** [comment]
@Mergifyio update

**Comment by azat** [comment]
>PullRequestCI / CheckLabels (pull_request) Failing after 11s — CheckLabels

You should update the description to match the template - https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md

But looks like you need to rebase *after* you changing the description, or now you can use `mergify` bot, since there are new commits in upstream alread.

Also let's make the changelog entry more user-friendly, something like `Disallow ALTER TTL for engines that does not support it, to avoid breaking ATTACH TABLE (closes #33344)`

**Comment by zhongyuankai** [comment]
> > PullRequestCI / CheckLabels (pull_request) Failing after 11s — CheckLabels
> 
> You should update the description to match the template - https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md
> 
> But looks like you need to rebase _after_ you changing the description, or now you can use `mergify` bot, since there are new commits in upstream alread.
> 
> Also let's make the changelog entry more user-friendly, something like `Disallow ALTER TTL for engines that does not support it, to avoid breaking ATTACH TABLE (closes #33344)`
> 
> P.S. Don't forget to `Mark as resolved` already resolved review threads.

@azat ok thanks, recovered.

**Comment by CurtizJ** [comment]
@Mergifyio update

**Review by CurtizJ — APPROVED** [review]
