### PR TITLE
Not support transaction for tables with disks which do not support writing with append.

### LINKED ISSUE #84669: Stress test fails with `Disk does not support WriteMode::Append`
Noexcept method `MergeTreeTransaction::afterCommit` becomes very sad when it receives a `NOT_IMPLEMENTED` exception.

Example failure (from [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84590&sha=latest&name_0=PR&name_1=Stress+test+%28amd_debug%29))

```
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.861655 [ 7935 ] {} <Fatal> BaseDaemon: (version 25.8.1.1, build id: CCD580EA735727FAED180CBF3C1572E6A6B2370D, git hash: fb421536e5e6c684dbdc8849142390dcce1904e4) (from thread 10090) Terminate called for uncaught exception:
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.864759 [ 7935 ] {} <Fatal> BaseDaemon: Code: 48. DB::Exception: Disk does not support WriteMode::Append. (NOT_IMPLEMENTED), Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.868186 [ 7935 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.877736 [ 7935 ] {} <Fatal> BaseDaemon: 0. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000002659d8f2
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.885192 [ 7935 ] {} <Fatal> BaseDaemon: 1. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000140941a6
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.899106 [ 7935 ] {} <Fatal> BaseDaemon: 2. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cd895ac
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.903175 [ 7935 ] {} <Fatal> BaseDaemon: 3. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/Exception.h:137: DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000cd93c36
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.908182 [ 7935 ] {} <Fatal> BaseDaemon: 4. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:811: DB::DiskObjectStorageTransaction::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&, bool) @ 0x000000001a2a2ee9
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.915295 [ 7935 ] {} <Fatal> BaseDaemon: 5. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Disks/ObjectStorages/DiskObjectStorage.cpp:893: DB::DiskObjectStorage::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x000000001a29913d
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.920480 [ 7935 ] {} <Fatal> BaseDaemon: 6. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Storages/MergeTree/DataPartStorageOnDiskBase.cpp:935: DB::DataPartStorageOnDiskBase::writeTransactionFile(DB::WriteMode) const @ 0x000000001dd8a9a1
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.931152 [ 7935 ] {} <Fatal> BaseDaemon: 7. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Storages/MergeTree/IMergeTreeDataPart.cpp:1817: DB::IMergeTreeDataPart::appendCSNToVersionMetadata(DB::VersionMetadata::WhichCSN) const @ 0x000000001ddbcf08
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.935476 [ 7935 ] {} <Fatal> BaseDaemon: 8. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/MergeTreeTransaction.cpp:241: DB::MergeTreeTransaction::afterCommit(unsigned long) @ 0x000000001b04236b
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:30.942913 [ 7935 ] {} <Fatal> BaseDaemon: 9. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/TransactionLog.cpp:485: DB::TransactionLog::finalizeCommittedTransaction(DB::MergeTreeTransaction*, unsigned long, BasicScopeGuard<std::function<void ()>>&) @ 0x000000001b241f6f
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.004249 [ 7935 ] {} <Fatal> BaseDaemon: 10. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/TransactionLog.cpp:464: DB::TransactionLog::commitTransaction(std::shared_ptr<DB::MergeTreeTransaction> const&, bool) @ 0x000000001b244963
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.010400 [ 7935 ] {} <Fatal> BaseDaemon: 11. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/InterpreterTransactionControlQuery.cpp:71: DB::InterpreterTransactionControlQuery::executeCommit(std::shared_ptr<DB::Context>) @ 0x000000001b2fe4dc
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.017835 [ 7935 ] {} <Fatal> BaseDaemon: 12. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/InterpreterTransactionControlQuery.cpp:35: DB::InterpreterTransactionControlQuery::execute() @ 0x000000001b2fe0d5
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.027208 [ 7935 ] {} <Fatal> BaseDaemon: 13. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Interpreters/executeQuery.cpp:947: DB::ImplicitTransactionControlExecutor::commit(std::shared_ptr<DB::Context> const&) @ 0x000000001b2f96cd
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.041835 [ 7935 ] {} <Fatal> BaseDaemon: 14. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000019e41079
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.042832 [ 7935 ] {} <Fatal> BaseDaemon: 15. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x000000001e56c907
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.070290 [ 7935 ] {} <Fatal> BaseDaemon: 16. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Server/TCPHandler.cpp:2740: DB::TCPHandler::run() @ 0x000000001e586624
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.079042 [ 7935 ] {} <Fatal> BaseDaemon: 17. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000026654187
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.100642 [ 7935 ] {} <Fatal> BaseDaemon: 18. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000026654765
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.121606 [ 7935 ] {} <Fatal> BaseDaemon: 19. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000265f393f
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.199526 [ 7935 ] {} <Fatal> BaseDaemon: 20. /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/base/poco/Foundati
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.329242 [ 7935 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.336022 [ 7935 ] {} <Fatal> BaseDaemon: (version 25.8.1.1, build id: CCD580EA735727FAED180CBF3C1572E6A6B2370D, git hash: fb421536e5e6c684dbdc8849142390dcce1904e4, architecture: x86_64) (from thread 10090) Received signal 6
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.339761 [ 7935 ] {} <Fatal> BaseDaemon: Signal description: Aborted
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.347349 [ 7935 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.366690 [ 7935 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fd6f4da49fd 0x00007fd6f4d50476 0x00007fd6f4d367f3 0x0000556d18321b86 0x0000556d267f3183 0x0000556d267f30b8 0x0000556d0c2f088b 0x0000556d1a5b25fe 0x0000556d1a7b1f6f 0x0000556d1a7b4963 0x0000556d1a86e4dc 0x0000556d1a86e0d5 0x0000556d1a8696cd 0x0000556d193b1079 0x0000556d1dadc907 0x0000556d1daf6624 0x0000556d25bc4187 0x0000556d25bc4765 0x0000556d25b6393f 0x0000556d25b61011 0x00007fd6f4da2ac3 0x00007fd6f4e34850
/var/log/clickhouse-server/clickhouse-server.err.log:2025.07.29 13:17:31.371990 [ 7935 ] {} <Fatal> BaseDaemon: 
```

### PR DESCRIPTION
**Pull request by tuanpach**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes into CHANGELOG.md):

For MergeTree tables using object storage which do not support writing with append, it will not support transactions. Closes #84669

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

Directly edit documentation source files in the "docs" folder with the same pull-request as code changes

or

Add a user-readable short description of the changes that should be added to docs.clickhouse.com below.

At a minimum, the following information should be added (but add more as needed).
- Motivation: Why is this function, table engine, etc. useful to ClickHouse users?

- Parameters: If the feature being added takes arguments, options or is influenced by settings, please list them below with a brief explanation.

- Example use: A query or command.

### CODE REVIEW

File: tests/queries/0_stateless/03657_merge_tree_disk_support_transaction.sql [hunk 1]
```diff
@@ -0,0 +1,41 @@
+-- Tags: no-ordinary-database, no-fasttest, no-encrypted-storage
+
+CREATE OR REPLACE TABLE t (x INT) ENGINE=MergeTree ORDER BY x;
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03657_merge_tree_disk_support_transaction.sql:3]: Could you please also add a test where you modify the `storage_policy`? I think if you change the storage policy to a disk which supports transaction, the table should start to support transactions.

Comment (tuanpach) [reply tests/queries/0_stateless/03657_merge_tree_disk_support_transaction.sql:3]: We have a check in `StoragePolicy::checkCompatibleWith` which ensures that the new policy has the same disks as the current policy. So I can't change the policy from `not supporting transaction` to `supporting transaction`.

https://github.com/ClickHouse/ClickHouse/blob/f7ac16b45a1e258c20aa0156ff1cfe3dd2c82fc4/src/Disks/StoragePolicy.cpp#L358-L406

**Comment by tuanpach** [comment]
01079_parallel_alter_detach_table_zookeeper
- https://github.com/ClickHouse/ClickHouse/issues/82676

test_log_query_probability/test.py::test_log_quries_probability_two
- https://github.com/ClickHouse/ClickHouse/issues/89279

**Review by antaljanosbenjamin — APPROVED** [review]
