### PR TITLE
Fix expressions in metadata

### LINKED ISSUE #6508: Buffer tables, created with currentDatabase(), lose their database assigment after restarting clickhouse server
**Describe the bug**
Buffer tables lose information about their database when the clickhouse server restarts.

**How to reproduce**
* Which ClickHouse server version to use
19.13.2.19
* `CREATE TABLE` statements for all tables involved

CREATE TABLE Test (
        uuid            UUID,
        pkghash         UInt64
) 
ENGINE = MergeTree
ORDER BY (uuid, pkghash) PRIMARY KEY (uuid);

CREATE TABLE Test_buffer AS Test
ENGINE = Buffer(currentDatabase(), Test, 16, 10, 200, 10000, 1000000, 10000000, 1000000000);

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

insert into Test_buffer SELECT generateUUIDv4(),rand64()

* Queries to run that lead to unexpected result

`# systemctl restart clickhouse-server`
`# clickhouse-client -n -d test_buff -q 'INSERT INTO Test_buffer SELECT generateUUIDv4(),rand64();'
Received exception from server (version 19.13.2):
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Default database is not selected.
`

**Expected behavior**

Insert without error

**Error message and/or stacktrace**

INSERT INTO Test_buffer SELECT 
    generateUUIDv4(), 
    rand64()

. Received exception from server (version 19.13.2):
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Default database is not selected.

**Additional context**

### PR DESCRIPTION
**Pull request by tavplubix**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
When executing CREATE query, fold constant expressions in storage engine arguments. Replace empty database name with current database. Fixes #6508, #3492

Also fix check for local address in `ClickHouseDictionarySource`

### CODE REVIEW

File: dbms/src/Storages/StorageDistributed.cpp [hunk 1]
```diff
@@ -253,6 +253,10 @@ StorageDistributed::StorageDistributed(
         if (num_local_shards && remote_database == id_.database_name && remote_table == id_.table_name)
             throw Exception("Distributed table " + id_.table_name + " looks at itself", ErrorCodes::INFINITE_LOOP);
     }
+    if (remote_database.empty())
+    {
+        LOG_WARNING(log, "Name of remote database is empty. Default database will be used implicitly.");
```
Comment (alexey-milovidov) [inline dbms/src/Storages/StorageDistributed.cpp]: BTW, it is used for cross-replication (replicas of different shards are stored on a single server in different databases).

**Review by alexey-milovidov — APPROVED** [review]

File: dbms/tests/queries/0_stateless/01083_expressions_in_engine_arguments.sql [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+);
+
+-- The following line is needed just to disable checking stderr for emptiness
+SELECT nonexistentsomething; -- { serverError 47 }
+
+CREATE DICTIONARY dict (n UInt64, _path String DEFAULT '42') PRIMARY KEY n
+SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9440 SECURE 1 USER 'default' TABLE 'url' DB 'test_01083')) LIFETIME(1) LAYOUT(CACHE(SIZE_IN_CELLS 1));
+
+-- TODO make fuzz test from this
+CREATE TABLE rich_syntax as remote
```
Comment (alesapin) [inline dbms/tests/queries/0_stateless/01083_expressions_in_engine_arguments.sql]: 0_o

**Comment by nikitamikhaylov** [comment]
Conflicts in 20.2
