### PR TITLE
Fix parsing errors for inserts with trailing comment

### LINKED ISSUE #42919: INSERT parsing bug - when there is a trailing comment
Clickhouse can't parse an INSERT query with a comment/metadata at the bottom.  See the following screenshot for an example and the exception it produces.

NOTE:  if the INSERT is for only one row (not two) then it works. 

image

### PR DESCRIPTION
**Pull request by pratimapatel2008**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed `INSERT` with `VALUES` failing when the data was followed by a trailing SQL comment (`--` or `/* */`) on the next line. The comment is now skipped instead of being parsed as another row.

Fixes: https://github.com/ClickHouse/ClickHouse/issues/42919

### Version info
- Merged into: `26.4.1.137`

### CODE REVIEW

File: src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp [hunk 1]
```diff
@@ -122,6 +122,7 @@ Chunk ValuesBlockInputFormat::read()
         try
         {
             skipWhitespaceIfAny(*buf);
+            skipWhitespaceAndSQLComments(*buf);
```
Comment (evillique) [inline src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: Do we still need the first skipWhitespaceIfAny call?

Comment (pratimapatel2008) [reply src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp]: Thank you for pointing out, I don't think it's needed, let me remove this in another place.

**Review by evillique — APPROVED** [review]
