### PR TITLE
Fix structure comparison between 2 JSON columns

### LINKED ISSUE #68679: JSON-type ReplacingMergeTree Block structure mismatch in joined block stream
Version: 24.8.1.2684  

https://fiddle.clickhouse.com/3b5d95da-5bd8-43bd-90ef-7438cfa17dab

Joins don't seem to work yet when the engine is ReplacingMergeTree and the new JSON-type is used in a table.

Specifics:
- ReplacingMergeTree
- `JOIN`

Discovery:
- MergeTree works fine with same data and same query

Reproducible:
```sql
CREATE OR REPLACE TABLE test_new_json_type(id UInt32, data JSON, version UInt64) ENGINE=ReplacingMergeTree(version) ORDER BY id;

INSERT INTO test_new_json_type format JSONEachRow
{"id":1,"data":{"foo1":"bar"},"version":1}
{"id":2,"data":{"foo2":"bar"},"version":1}
{"id":3,"data":{"foo2":"bar"},"version":1}
;

SELECT
    a.data
    , b.data
FROM
    test_new_json_type a
    JOIN test_new_json_type b
        ON a.id = b.id;
```
Error
```
DB::Exception: Block structure mismatch in joined block stream: different columns:
__table2.data JSON Object(size = 0, Array(size = 0, UInt64(size = 0), Tuple(size = 0, String(size = 0), String(size = 0))))
__table2.data JSON Object(size = 3, Dynamic(size = 3, Variant(size = 3, UInt8(size = 3), UInt64(size = 3), String(size = 0), String(size = 2))), Dynamic(size = 3, Variant(size = 3, UInt8(size = 3), UInt64(size = 3), String(size = 0), String(size = 1))), Array(size = 3, UInt64(size = 3), Tuple(size = 0, String(size = 0), String(size = 0)))): While executing FillingRightJoinSide. (LOGICAL_ERROR)
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix possible error `DB::Exception: Block structure mismatch in joined block stream: different columns:` with new JSON column.

Closes https://github.com/ClickHouse/ClickHouse/issues/68679

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit ca880ccdee16a212cebccce7090eabf4f528aa68 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/68686/ca880ccdee16a212cebccce7090eabf4f528aa68/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/f1b1f8afcfa65b5ab2644ba791d171a996c752ff/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Columns/ColumnObject.cpp [hunk 1]
```diff
@@ -1047,7 +1047,7 @@ bool ColumnObject::structureEquals(const IColumn & rhs) const
 {
     /// 2 Object columns have equal structure if they have the same typed paths and max_dynamic_paths/max_dynamic_types.
```
Comment (davenger) [inline src/Columns/ColumnObject.cpp:1048]:
```suggestion
    /// 2 Object columns have equal structure if they have the same typed paths and global_max_dynamic_paths/max_dynamic_types.
```

**Review by davenger — APPROVED** [review]

**Comment by Avogar** [comment]
> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [2/2] — fail: 1, passed: 3421, skipped: 69

https://github.com/ClickHouse/ClickHouse/pull/68841
