### PR TITLE
Choose correct aggregation method for lc128 and lc256

### LINKED ISSUE #42330: use-of-uninitialized-value in DB::Aggregator
https://s3.amazonaws.com/clickhouse-test-reports/42302/cecc1027fb01e27bc72ea465fcc4360ce47bf996/fuzzer_astfuzzermsan//report.html

```
==142==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x3ec5da8d in HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>::isZero(wide::integer<128ul, unsigned int> const&, HashTableNoState const&) build_docker/../src/Common/HashTable/HashMap.h:89:93
    #1 0x3ec5da8d in HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>::isZero(HashTableNoState const&) const build_docker/../src/Common/HashTable/HashMap.h:88:53
    #2 0x3ec5da8d in HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::findCell(wide::integer<128ul, unsigned int> const&, unsigned long, unsigned long) const build_docker/../src/Common/HashTable/HashTable.h:486:34
    #3 0x3ec5da8d in void HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplaceNonZero<wide::integer<128ul, unsigned int>&>(wide::integer<128ul, unsigned int>&, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>*&, bool&, unsigned long) build_docker/../src/Common/HashTable/HashTable.h:989:30
    #4 0x3ec5da8d in void HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplace<wide::integer<128ul, unsigned int>&>(wide::integer<128ul, unsigned int>&, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>*&, bool&, unsigned long) build_docker/../src/Common/HashTable/HashTable.h:1069:13
    #5 0x3ec5da8d in void HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>::emplace<wide::integer<128ul, unsigned int>&>(wide::integer<128ul, unsigned int>&, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>*&, bool&) build_docker/../src/Common/HashTable/HashTable.h:1060:9
    #6 0x3ec5da8d in DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<char*> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodKeysFixed<PairNoInit<wide::integer<128ul, unsigned int>, char*>, wide::integer<128ul, unsigned int>, char*, false, false, true, false>, PairNoInit<wide::integer<128ul, unsigned int>, char*>, char*, true, false>::emplaceImpl<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&) build_docker/../src/Common/ColumnsHashingImpl.h:209:14
    #7 0x3ec5da8d in DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<char*> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodKeysFixed<PairNoInit<wide::integer<128ul, unsigned int>, char*>, wide::integer<128ul, unsigned int>, char*, false, false, true, false>, PairNoInit<wide::integer<128ul, unsigned int>, char*>, char*, true, false>::emplaceKey<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, unsigned long, DB::Arena&) build_docker/../src/Common/ColumnsHashingImpl.h:158:16
    #8 0x3ec5da8d in void DB::Aggregator::mergeStreamsImplCase<false, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const build_docker/../src/Interpreters/Aggregator.cpp:2721:41
    #9 0x3eaa8831 in void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const build_docker/../src/Interpreters/Aggregator.cpp:2789:9
    #10 0x3eaa8831 in void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Block, DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, DB::Arena*) const build_docker/../src/Interpreters/Aggregator.cpp:2771:5
    #11 0x3e86e7ff in DB::Aggregator::mergeBlocks(std::__1::list<DB::Block, std::__1::allocator<DB::Block>>&, bool) build_docker/../src/Interpreters/Aggregator.cpp:3079:9
    #12 0x45c5a17d in DB::MergingAggregatedBucketTransform::transform(DB::Chunk&) build_docker/../src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:361:37
    #13 0x31dcd0ca in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_docker/../src/Processors/ISimpleTransform.h:32:9
    #14 0x4530a590 in DB::ISimpleTransform::work() build_docker/../src/Processors/ISimpleTransform.cpp:89:9
    #15 0x45384f8d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #16 0x45384f8d in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #17 0x4534b2fc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228:26
    #18 0x45350eeb in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:194:5
    #19 0x45350eeb in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:315:17
    #20 0x45350eeb in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #21 0x45350eeb in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #22 0x45350eeb in decltype(auto) std::__1::apply<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #23 0x45350eeb in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #24 0x45350eeb in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #25 0x45350eeb in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #26 0x45350eeb in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #27 0x45350eeb in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #28 0x25f0c8d0 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #29 0x25f0c8d0 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #30 0x25f0c8d0 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #31 0x25f197a2 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #32 0x25f197a2 in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #33 0x25f197a2 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #34 0x25f197a2 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #35 0x7ff21c898608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #36 0x7ff21c7bd132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

  Uninitialized value was created by a heap allocation
    #0 0xbc8b6c0 in malloc (/workspace/clickhouse+0xbc8b6c0) (BuildId: d53ad990180f4047136a8f58583842b65dc7db16)
    #1 0x25b96dcc in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) build_docker/../src/Common/Allocator.h:227:27
    #2 0xc0ac001 in void DB::PODArrayBase<16ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::alloc<>(unsigned long) (/workspace/clickhouse+0xc0ac001) (BuildId: d53ad990180f4047136a8f58583842b65dc7db16)
    #3 0x21f1bf38 in DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>::resize_fill(unsigned long) (/workspace/clickhouse+0x21f1bf38) (BuildId: d53ad990180f4047136a8f58583842b65dc7db16)
    #4 0x248a632e in void DB::packFixedBatch<wide::integer<128ul, unsigned int>>(unsigned long, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long>> const&, DB::PODArray<wide::integer<128ul, unsigned int>, 4096ul, Allocator<false, false>, 15ul, 16ul>&) (/workspace/clickhouse+0x248a632e) (BuildId: d53ad990180f4047136a8f58583842b65dc7db16)
    #5 0x3eb49a41 in DB::ColumnsHashing::HashMethodKeysFixed<PairNoInit<wide::integer<128ul, unsigned int>, char*>, wide::integer<128ul, unsigned int>, char*, false, false, true, false>::HashMethodKeysFixed(std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long>> const&, std::__1::shared_ptr<DB::ColumnsHashing::HashMethodContext> const&) build_docker/../src/Common/ColumnsHashing.h:539:13
    #6 0x3ec5b663 in void DB::Aggregator::mergeStreamsImplCase<false, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const build_docker/../src/Interpreters/Aggregator.cpp:2708:28
    #7 0x3eaa8831 in void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const build_docker/../src/Interpreters/Aggregator.cpp:2789:9
    #8 0x3eaa8831 in void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Block, DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, DB::Arena*) const build_docker/../src/Interpreters/Aggregator.cpp:2771:5
    #9 0x3e86e7ff in DB::Aggregator::mergeBlocks(std::__1::list<DB::Block, std::__1::allocator<DB::Block>>&, bool) build_docker/../src/Interpreters/Aggregator.cpp:3079:9
    #10 0x45c5a17d in DB::MergingAggregatedBucketTransform::transform(DB::Chunk&) build_docker/../src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:361:37
    #11 0x31dcd0ca in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_docker/../src/Processors/ISimpleTransform.h:32:9
    #12 0x4530a590 in DB::ISimpleTransform::work() build_docker/../src/Processors/ISimpleTransform.cpp:89:9
    #13 0x45384f8d in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #14 0x45384f8d in DB::ExecutionThreadContext::executeTask() build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92:9
    #15 0x4534b2fc in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228:26
    #16 0x45350eeb in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/../src/Processors/Executors/PipelineExecutor.cpp:194:5
    #17 0x45350eeb in DB::PipelineExecutor::spawnThreads()::$_0::operator()() const build_docker/../src/Processors/Executors/PipelineExecutor.cpp:315:17
    #18 0x45350eeb in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0&>(fp)()) std::__1::__invoke_constexpr<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&) build_docker/../contrib/libcxx/include/type_traits:3648:23
    #19 0x45350eeb in decltype(auto) std::__1::__apply_tuple_impl<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/tuple:1595:1
    #20 0x45350eeb in decltype(auto) std::__1::apply<DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&>(DB::PipelineExecutor::spawnThreads()::$_0&, std::__1::tuple<>&) build_docker/../contrib/libcxx/include/tuple:1604:1
    #21 0x45350eeb in ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()::operator()() build_docker/../src/Common/ThreadPool.h:193:13
    #22 0x45350eeb in decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #23 0x45350eeb in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&) build_docker/../contrib/libcxx/include/__functional/invoke.h:61:9
    #24 0x45350eeb in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()() build_docker/../contrib/libcxx/include/__functional/function.h:230:12
    #25 0x45350eeb in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/../contrib/libcxx/include/__functional/function.h:711:16
    #26 0x25f0c8d0 in std::__1::__function::__policy_func<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:843:16
    #27 0x25f0c8d0 in std::__1::function<void ()>::operator()() const build_docker/../contrib/libcxx/include/__functional/function.h:1184:12
    #28 0x25f0c8d0 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/../src/Common/ThreadPool.cpp:294:17
    #29 0x25f197a2 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/../src/Common/ThreadPool.cpp:144:73
    #30 0x25f197a2 in decltype(static_cast<void>(fp)()) std::__1::__invoke<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/../contrib/libcxx/include/type_traits:3640:23
    #31 0x25f197a2 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) build_docker/../contrib/libcxx/include/thread:282:5
    #32 0x25f197a2 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/../contrib/libcxx/include/thread:293:5
    #33 0x7ff21c898608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8

SUMMARY: MemorySanitizer: use-of-uninitialized-value build_docker/../src/Common/HashTable/HashMap.h:89:93 in HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>::isZero(wide::integer<128ul, unsigned int> const&, HashTableNoState const&)
Exiting
==142==WARNING: MemorySanitizer: use-of-uninitialized-value
Uninitialized bytes in __interceptor_write at offset 0 inside [0x7ff047eb6ee0, 392)
2022.10.14 20:52:09.489379 [ 152 ] {} <Trace> BaseDaemon: Received signal -3
2022.10.14 20:52:18.302490 [ 419 ] {} <Fatal> BaseDaemon: ########################################
2022.10.14 20:52:18.302733 [ 419 ] {} <Fatal> BaseDaemon: (version 22.10.1.1, build id: D53AD990180F4047136A8F58583842B65DC7DB16) (from thread 410) (query_id: 5cc7cdad-e9ad-49ab-9a13-52fd7a06c2dd) (query: SELECT sum(v) AS s FROM group_by_pk__fuzz_42 GROUP BY k ORDER BY s ASC LIMIT 1024 SETTINGS optimize_aggregation_in_order = 1, max_block_size = 1) Received signal Unknown signal -3 (-3)
2022.10.14 20:52:18.302949 [ 419 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2022.10.14 20:52:18.303188 [ 419 ] {} <Fatal> BaseDaemon: Stack trace: 0x25cd2379 0x2640b9ba 0xbc6b4b6 0xbc80053 0x3ec5da8e 0x3eaa8832 0x3e86e800 0x45c5a17e 0x31dcd0cb 0x4530a591 0x45384f8e 0x4534b2fd 0x45350eec 0x25f0c8d1 0x25f197a3 0x7ff21c898609 0x7ff21c7bd133
2022.10.14 20:52:18.451330 [ 419 ] {} <Fatal> BaseDaemon: 0.1. inlined from ./build_docker/../src/Common/StackTrace.cpp:332: StackTrace::tryCapture()
2022.10.14 20:52:18.451484 [ 419 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../src/Common/StackTrace.cpp:293: StackTrace::StackTrace() @ 0x25cd2379 in /workspace/clickhouse
2022.10.14 20:52:18.801939 [ 419 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Daemon/BaseDaemon.cpp:415: sanitizerDeathCallback() @ 0x2640b9ba in /workspace/clickhouse
2022.10.14 20:52:27.523203 [ 419 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0xbc6b4b6 in /workspace/clickhouse
2022.10.14 20:52:36.339763 [ 419 ] {} <Fatal> BaseDaemon: 3. ? @ 0xbc80053 in /workspace/clickhouse
2022.10.14 20:52:42.739898 [ 419 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./build_docker/../src/Common/HashTable/HashMap.h:0: void HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >::emplaceNonZero<wide::integer<128ul, unsigned int>&>(wide::integer<128ul, unsigned int>&, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>*&, bool&, unsigned long)
2022.10.14 20:52:42.740105 [ 419 ] {} <Fatal> BaseDaemon: 4.2. inlined from ./build_docker/../src/Common/HashTable/HashTable.h:1069: void HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >::emplace<wide::integer<128ul, unsigned int>&>(wide::integer<128ul, unsigned int>&, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>*&, bool&, unsigned long)
2022.10.14 20:52:42.740240 [ 419 ] {} <Fatal> BaseDaemon: 4.3. inlined from ./build_docker/../src/Common/HashTable/HashTable.h:1060: void HashTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >::emplace<wide::integer<128ul, unsigned int>&>(wide::integer<128ul, unsigned int>&, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>*&, bool&)
2022.10.14 20:52:42.740417 [ 419 ] {} <Fatal> BaseDaemon: 4.4. inlined from ./build_docker/../src/Common/ColumnsHashingImpl.h:209: DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<char*> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodKeysFixed<PairNoInit<wide::integer<128ul, unsigned int>, char*>, wide::integer<128ul, unsigned int>, char*, false, false, true, false>, PairNoInit<wide::integer<128ul, unsigned int>, char*>, char*, true, false>::emplaceImpl<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, wide::integer<128ul, unsigned int> >(wide::integer<128ul, unsigned int>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >&)
2022.10.14 20:52:42.740571 [ 419 ] {} <Fatal> BaseDaemon: 4.5. inlined from ./build_docker/../src/Common/ColumnsHashingImpl.h:158: DB::ColumnsHashing::columns_hashing_impl::EmplaceResultImpl<char*> DB::ColumnsHashing::columns_hashing_impl::HashMethodBase<DB::ColumnsHashing::HashMethodKeysFixed<PairNoInit<wide::integer<128ul, unsigned int>, char*>, wide::integer<128ul, unsigned int>, char*, false, false, true, false>, PairNoInit<wide::integer<128ul, unsigned int>, char*>, char*, true, false>::emplaceKey<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> > >(HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >&, unsigned long, DB::Arena&)
2022.10.14 20:52:42.740689 [ 419 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../src/Interpreters/Aggregator.cpp:2721: void DB::Aggregator::mergeStreamsImplCase<false, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> > >(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >&, char*, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, DB::Arena*) const @ 0x3ec5da8e in /workspace/clickhouse
2022.10.14 20:52:51.961330 [ 419 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./build_docker/../src/Interpreters/Aggregator.cpp:2789: void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> > >(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >&, char*, bool, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 15ul, 16ul> const*> > const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*> > const&, DB::Arena*) const
2022.10.14 20:52:51.961555 [ 419 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Interpreters/Aggregator.cpp:2771: void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> > >(DB::Block, DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >, false, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128Hash, HashTableNoState>, UInt128Hash, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true> >&, char*, bool, DB::Arena*) const @ 0x3eaa8832 in /workspace/clickhouse
2022.10.14 20:53:02.406945 [ 419 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Interpreters/Aggregator.cpp:3079: DB::Aggregator::mergeBlocks(std::__1::list<DB::Block, std::__1::allocator<DB::Block> >&, bool) @ 0x3e86e800 in /workspace/clickhouse
2022.10.14 20:53:02.830015 [ 419 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp:0: DB::MergingAggregatedBucketTransform::transform(DB::Chunk&) @ 0x45c5a17e in /workspace/clickhouse
2022.10.14 20:53:03.175289 [ 419 ] {} <Fatal> BaseDaemon: 8.1. inlined from ./build_docker/../contrib/libcxx/include/__utility/swap.h:35: std::__1::enable_if<(is_move_constructible<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value) && (is_move_assignable<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value), void>::type std::__1::swap<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>(COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&)
2022.10.14 20:53:03.175559 [ 419 ] {} <Fatal> BaseDaemon: 8.2. inlined from ./build_docker/../contrib/libcxx/include/vector:1923: std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >::swap(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&)
2022.10.14 20:53:03.175700 [ 419 ] {} <Fatal> BaseDaemon: 8.3. inlined from ./build_docker/../src/Processors/Chunk.h:64: DB::Chunk::swap(DB::Chunk&)
2022.10.14 20:53:03.175817 [ 419 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x31dcd0cb in /workspace/clickhouse
2022.10.14 20:53:03.390136 [ 419 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Processors/ISimpleTransform.cpp:0: DB::ISimpleTransform::work() @ 0x4530a591 in /workspace/clickhouse
2022.10.14 20:53:03.476996 [ 419 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2022.10.14 20:53:03.477210 [ 419 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x45384f8e in /workspace/clickhouse
2022.10.14 20:53:03.763886 [ 419 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x4534b2fd in /workspace/clickhouse
2022.10.14 20:53:04.104018 [ 419 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/Common/ThreadPool.h:194: operator()
2022.10.14 20:53:04.104326 [ 419 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::PipelineExecutor::spawnThreads()::$_0>(fp)()) std::__1::__invoke<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(DB::PipelineExecutor::spawnThreads()::$_0&&)
2022.10.14 20:53:04.104514 [ 419 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./build_docker/../contrib/libcxx/include/__functional/invoke.h:61: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'()&)
2022.10.14 20:53:04.104692 [ 419 ] {} <Fatal> BaseDaemon: 12.4. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:230: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()>::operator()()
2022.10.14 20:53:04.104823 [ 419 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x45350eec in /workspace/clickhouse
2022.10.14 20:53:04.350968 [ 419 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../contrib/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x25f0c8d1 in /workspace/clickhouse
2022.10.14 20:53:04.656168 [ 419 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x25f197a3 in /workspace/clickhouse
2022.10.14 20:53:04.656430 [ 419 ] {} <Fatal> BaseDaemon: 15. ? @ 0x7ff21c898609 in ?
2022.10.14 20:53:04.656564 [ 419 ] {} <Fatal> BaseDaemon: 16. clone @ 0x7ff21c7bd133 in ?
2022.10.14 20:53:10.256609 [ 419 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: 6B05E48A984C623F427CFA9D1958006D)
```

### PR DESCRIPTION
**Pull request by canhld94**
### Changelog category (leave one):
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Choose correct aggregation method for LowCardinality with BigInt

Close #42330

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by vdimir — APPROVED** [review]
👍

File: src/Interpreters/Aggregator.cpp [hunk 1]
```diff
@@ -811,6 +811,10 @@ AggregatedDataVariants::Type Aggregator::chooseAggregationMethod()
                 return AggregatedDataVariants::Type::low_cardinality_key32;
             if (size_of_field == 8)
                 return AggregatedDataVariants::Type::low_cardinality_key64;
+            if (size_of_field == 16)
+                return AggregatedDataVariants::Type::low_cardinality_keys128;
+            if (size_of_field == 32)
+                return AggregatedDataVariants::Type::low_cardinality_keys256;
```
Comment (azat) [inline src/Interpreters/Aggregator.cpp:817]: Maybe it worth adding `else throw` to avoid such issues in future?

**Comment by alexey-milovidov** [comment]
@azat @vdimir any idea why it didn't simply use `AggregatedDataVariants::Type::serialized`?

**Comment by azat** [comment]
> any idea why it didn't simply use AggregatedDataVariants::Type::serialized?

There is optimization for `LowCardinality` , that had been added in #3138

**Review by alexey-milovidov — APPROVED** [review]

**Comment by canhld94** [comment]
Fail cases:
- Stateless:  00463_long_sessions_in_http_interface
- msan: OOM kill, not sure...
- tsan: backward compatibility,
- ubsan: backward compatibility, cannot attach table
