### PR TITLE
Fix #79394: non-zero parameter fix

### LINKED ISSUE #79394: input_format_parquet_max_block_size = 0 infinite loop with Parquet Native reader
### Describe the bug

Yes, another variable = 0 issue :/

### How to reproduce

Run:

```sql
INSERT INTO TABLE FUNCTION file('<path to file>', 'Parquet', 'c0 Int') SELECT 1;
SELECT * FROM file('<path to file>', Parquet, 'c0 Int') SETTINGS input_format_parquet_max_block_size = 0, input_format_parquet_use_native_reader = 1; --stuck
```

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by abashkeev**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Previously when `input_format_parquet_max_block_size = 0` ClickHouse would stuck. Now this behaviour is fixed. This closes https://github.com/ClickHouse/ClickHouse/issues/79394

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03432_input_format_parquet_max_block_size_validation.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+-- Test that negative values are not allowed
+SET input_format_parquet_max_block_size = -1; -- { serverError CANNOT_CONVERT_TYPE }
+
+-- Test that valid positive values are allowed
+SET input_format_parquet_max_block_size = 8192;
+SELECT name, value FROM system.settings WHERE name = 'input_format_parquet_max_block_size' FORMAT TSV;
+
+-- Test that the setting works with queries
+SELECT 1 AS x FORMAT Parquet SETTINGS input_format_parquet_max_block_size = 16384;
```
Comment (jkartseva) [inline tests/queries/0_stateless/03432_input_format_parquet_max_block_size_validation.sql:12]: Produces binary output. Please consider converting this test into shell and redirecting the output; for reference: https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/00900_long_parquet.sh#L13-L17

Comment (nikitamikhaylov) [reply tests/queries/0_stateless/03432_input_format_parquet_max_block_size_validation.sql:12]: Alternative you can you `SELECT INTO OUTFILE /dev/null`

Comment (abashkeev) [reply tests/queries/0_stateless/03432_input_format_parquet_max_block_size_validation.sql]: Thx!

**Review by nikitamikhaylov — APPROVED** [review]
