### PR TITLE
Fix behavior of `TRIM` with computed trim characters

### LINKED ISSUE #69922: `TRIM` does not support empty trim characters, pt. II
This issue is motivated by https://github.com/ClickHouse/ClickHouse/issues/67792#issuecomment-2373036614.

As per #68455, function `TRIM` supports empty characters `''` as a trim character argument. This was implemented as a shortcut for `''` in src/Parsers/ExpressionListParsers.cpp.

The problem is that _computed_ empty trim characters still throw an error, e.g.

```sql
SELECT TRIM(leading concat('') FROM 'foo');

-- Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: The pattern argument is not a valid re2 pattern: missing ]: []+: In scope SELECT replaceRegexpOne('foo', concat('^[', regexpQuoteMeta(concat('')), ']+'), ''). (BAD_ARGUMENTS)
```

The code calls `regexpReplaceOne` with pattern `^[]+` which is not a valid re2 pattern.

I think the problem is that we map to `regexpReplaceAll` at all. We should rather
- extend the existing trim function (src/Functions/trim.cpp) with two optional arguments: the trim character (right now, it is hardcoded to `' '`) and an integer mode argument (0 = both, 1 = left, 2 = right)
- replace the mapping from `regexpReplaceAll` to the extended trim function.

Since `trim` is not based on regexps, any regexp-related issues will go away with that + it will probably also be faster.

### PR DESCRIPTION
**Pull request by mgill25**
Resolves #69922

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Function `TRIM` with computed empty trim characters are now correctly handled. Example: `SELECT TRIM(LEADING concat('') FROM 'foo')` (Issue #69922)

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit 5e910d6911f9452913910060a4d43d4375f5602c with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75399/5e910d6911f9452913910060a4d43d4375f5602c/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/74477/aad9680fbc1a55b062e4b87361096d1dca181de0/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by mgill25** [comment]
I guess adding the `description` for these functions failed the tests. Happy to remove it but I'm guessing more docs is a good thing, so I'll let @rschu1ze chime in on this :)

**Comment by mgill25** [comment]
Failure is unrelated to PR.

File: src/Parsers/ExpressionListParsers.cpp [hunk 1]
```diff
@@ -1702,72 +1703,17 @@ class TrimLayer : public Layer
                 {
                     /// The operation does nothing.
                 }
-                if (char_override)
```
Comment (rschu1ze) [inline src/Parsers/ExpressionListParsers.cpp:1705]: I love how all this code goes away.

File: src/Parsers/ExpressionListParsers.cpp [hunk 2]
```diff
@@ -1702,72 +1703,17 @@ class TrimLayer : public Layer
...
-                    pattern_func_node->name = "concat";
-                    pattern_func_node->arguments = std::move(pattern_list_args);
-                    pattern_func_node->children.push_back(pattern_func_node->arguments);
-
-                    pattern_node = std::move(pattern_func_node);
-
-                    elements.push_back(pattern_node);
-                    elements.push_back(std::make_shared<ASTLiteral>(""));
-                }
+                if (trim_left && trim_right)
```
Comment (rschu1ze) [inline src/Parsers/ExpressionListParsers.cpp:1706]: L. 1702-1706 looks strange ... but it has been like that already before.

**Comment by rschu1ze** [comment]
@mgill25 I did some adjustments in trim.cpp and find_symbols for consistency with existing code, and extended the tests a bit. For some reason, Git rejected my push to your fork with a `permission denied` error. Therefore, kindly pick the "some fixups" commit from https://github.com/rschu1ze/ClickHouse/commits/better-trim-function/ into this PR, thanks.

**Comment by mgill25** [comment]
@rschu1ze done

**Comment by rschu1ze** [comment]
CI (FastTest) is broken again. Let's wait a couple of days and then merge from `master` again.

**Comment by rschu1ze** [comment]
Stateless tests (azure, asan, 1/3):
- 02421_truncate_isolation_no_merges: #75981

Integration tests (release, 4/4):
- test_dns_cache: #75982
