### PR TITLE
fix: quota limit was not reached, but the limit was exceeded

### LINKED ISSUE #31174: Quota limit was not reached, but the limit was exceeded
## Describe what's wrong
quota limit was not reached, but the limit was exceeded，Changes from https://github.com/ClickHouse/ClickHouse/commit/d8d2bd885c72ae06707f0a15001f2bfb7ba21054#diff-ebadfab5af066c0ff22a9999d1455c293936dff46dd572f002b912ab355bf00f

## Does it reproduce on recent release?
Version 21.3 or later

## How to reproduce
1、Set the quota of the account
```
CREATE USER IF NOT EXISTS jd_olap IDENTIFIED WITH double_sha1_password BY '123456'

GRANT SHOW, SELECT, INSERT, ALTER, CREATE DATABASE, CREATE TABLE, CREATE VIEW, CREATE DICTIONARY, DROP, TRUNCATE, OPTIMIZE, SYSTEM MERGES, SYSTEM TTL MERGES, SYSTEM FETCHES, SYSTEM MOVES, SYSTEM SENDS, SYSTEM REPLICATION QUEUES, SYSTEM SYNC REPLICA, SYSTEM RESTART REPLICA, SYSTEM FLUSH DISTRIBUTED, dictGet ON jd_olap.* TO jd_olap

CREATE QUOTA jd_olap_10s FOR INTERVAL 10 second MAX queries = 10 TO jd_olap;
```

2、create table
```
CREATE DATABASE IF NOT EXISTS quota_test_local on cluster system_cluster;

CREATE TABLE IF NOT EXISTS jd_olap.quota_test_local on cluster system_cluster 
( 
`user` String, 
`max_concurrent_queries` UInt32, 
`max_execution_time` UInt32, 
`requests_per_minute` UInt32,
`dt` Date 
) 
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/system_cluster/jdob_ha/jd_olap/quota_test_local/{shard}', '{replica}') \
PARTITION BY dt 
ORDER BY user 
SETTINGS storage_policy = 'jdob_ha', index_granularity = 8192;
```

3、execute the query（insert， select， alter）, will trigger the problem
image

## Expected behavior**
there is a bug where end time is 1970, causing end_loaded.count =0；
image

the used quota is not reset when it is first calculated (e.g., when a node is restarted or created for the first time) because 1970 is the first end time, the initial used logic is incremented from the first calculated value to the next interval. Used quota values are reset only at the next interval, as must be shown in the following figure: 16:45 and 16:47 are both calculated for the first time on the node restart, and the quota is not reset；
```
2021.11.09 16:49:17.481461 [ 14825 ] {1686DC283041A762} <Information> EnabledQuota: current_time: 2021-11-09 16:49:17, end: 1970-01-01 08:00:00
2021.11.09 16:49:17.481479 [ 14825 ] {1686DC283041A762} <Information> EnabledQuota: need_reset_counters: false, end_load_count: 0, interval.used: 11
```

### PR DESCRIPTION
**Pull request by sunny19930321**
Changelog category (leave one):
- Bug Fix

Changelog entry:
Quota limit was not reached, but the limit was exceeded. This PR fixes https://github.com/ClickHouse/ClickHouse/issues/31174

### CODE REVIEW

File: src/Access/EnabledQuota.cpp [hunk 1]
```diff
@@ -66,7 +64,12 @@ struct EnabledQuota::Impl
             UInt64 n = static_cast<UInt64>((current_time - end + duration) / duration);
             end = end + duration * n;
             if (end_of_interval.compare_exchange_strong(end_loaded, end.time_since_epoch()))
+            {
+                /// We reset counters only if the interval's end has been calculated before.
+                /// If it hasn't we just calculate the interval's end for the first time and don't reset counters yet.
+                need_reset_counters = true;
```
Comment (vitlibar) [inline src/Access/EnabledQuota.cpp:70]:
```suggestion
                need_reset_counters = (end_loaded.count() != 0);
```

I mean we shouldn't reset counters if `end_loaded.count() == 0` here (see the failed tests). There can be three cases at the point `getEndOfInterval()` is called:
1) `current_time < end_of_interval` -- the counters should not be reset.
2) `current_time >= end_of_interval` -- the counters usually should be reset, with an exception if we have the case 3 (see below).
3) `end_of_interval == 0` -- that means the `end_of_interval` is not initialized. Of course in this case also `current_time >= end_of_interval` because `current_time >= 0` for any `current_time`. But in this case that doesn't mean we should reset the counters: `end_of_interval` is actually not initialized, so we can't say that the `current_time >= end_of_interval` does really means anything in this case.

Comment (sunny19930321) [reply src/Access/EnabledQuota.cpp:70]: ok，thank you for advice

**Review by vitlibar — APPROVED** [review]
