### PR TITLE
Try fix flaky tests with transactions

### LINKED ISSUE #37920: Logical error: 'Cannot unlock removal_tid, it's a bug'
https://s3.amazonaws.com/clickhouse-test-reports/37837/d39e72411288ca572deebf98bc14c29e09546f66/stateless_tests__thread__actions__[1/3].html

```
2022.06.08 07:44:28.764640 [ 695 ] {} <Fatal> : Logical error: 'Cannot unlock removal_tid, it's a bug. Current: 15317705874040209379 (1, 1, 00000000-0000-0000-0000-000000000000), actual: 0 (0, 0, 00000000-0000-0000-0000-000000000000)'.
2022.06.08 07:44:29.174959 [ 51544 ] {} <Fatal> BaseDaemon: ########################################
2022.06.08 07:44:29.175070 [ 51544 ] {} <Fatal> BaseDaemon: (version 22.6.1.1, build id: 52E4307A00A9C93F) (from thread 695) (no query) Received signal Aborted (6)
2022.06.08 07:44:29.175129 [ 51544 ] {} <Fatal> BaseDaemon: 
2022.06.08 07:44:29.175235 [ 51544 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f432d4a800b 0x7f432d487859 0xb2a03fb 0xb36037a 0xb3605ad 0x1abe320f 0x1abe2fdf 0x1b7162bd 0x1b441821 0x1b8af9fb 0x1b455529 0x1b6c6834 0x1b6c7706 0x1b6cce82 0xb3f2d52 0xb3f5b39 0xb3f59e2 0xb3f0658 0xb3f3d91 0xb29ab19 0x7f432d65f609 0x7f432d584133
2022.06.08 07:44:29.175372 [ 51544 ] {} <Fatal> BaseDaemon: 5. gsignal @ 0x7f432d4a800b in ?
2022.06.08 07:44:29.175447 [ 51544 ] {} <Fatal> BaseDaemon: 6. abort @ 0x7f432d487859 in ?
2022.06.08 07:44:49.762942 [ 625 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by tavplubix**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Previous PR #36644 fixed tests, but it triggers a bug in bash... 
Let's try to simply send SIGTERM without any tricks
Also fixes #37920

### CODE REVIEW

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Tests with tsan - timeouts - broken after upgrading to llvm-14
Stateless tests flaky check (address, actions) - OK
Stress tests - #35156, suppressed in 299f102ccf92e1ea001ad9483171f75f33cb75bc

**Comment by tavplubix** [comment]
Integration tests - No space left on device
Stateless tests with tsan are broken
Stateless tests flaky check - OK

But let's run tests again just in case

**Comment by tavplubix** [comment]
@Mergifyio update

**Comment by tavplubix** [comment]
Integration tests (asan, actions) [1/3] - No space left on device
Integration tests (release, actions) [2/2] - no space left on device
Integration tests (thread, actions) [4/4] - no space left on device

Stateless tests (aarch64, actions) - 02232_dist_insert_send_logs_level_hung -  #38219
Stateless tests (address, actions) [1/2] - 02232_dist_insert_send_logs_level_hung
Stateless tests (debug, actions) [3/3] - 02232_dist_insert_send_logs_level_hung
Stateless tests (memory, actions) [3/3] - 02232_dist_insert_send_logs_level_hung
Stateless tests (release, DatabaseReplicated, actions) [1/2] - 02232_dist_insert_send_logs_level_hung
 Stateless tests (release, actions) - 02232_dist_insert_send_logs_level_hung and 01281_group_by_limit_memory_tracking
Stateless tests (release, s3 storage, actions) - 02232_dist_insert_send_logs_level_hung
Stateless tests (release, wide parts enabled, actions) - 02232_dist_insert_send_logs_level_hung
Stateless tests (thread, actions) [3/3] - 02232_dist_insert_send_logs_level_hung
Stateless tests (ubsan, actions) - 02232_dist_insert_send_logs_level_hung

Stateless tests flaky check (address, actions) - OK

Stress test (debug, actions) and Stress test (thread, actions):
```
2022-06-20 16:54:46,552 Checking if some queries hung
usage: clickhouse-test [-h] [-q QUERIES] [--tmp TMP] [-b BINARY] [-c CLIENT]
...
clickhouse-test: error: unrecognized arguments: --stress
```
Some inconsistency in docker images (race condition in CI, cc: @Felixoid)

File: src/Common/noexcept_scope.h [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+#define NOEXCEPT_SCOPE_IMPL_CONCAT(n, expected) \
+    LockMemoryExceptionInThread lock_memory_tracker##n(VariableContext::Global);   \
+    SCOPE_EXIT(                                                                    \
+        {                                                                          \
+            const auto uncaught = std::uncaught_exceptions();                      \
+            assert((expected) == uncaught || (expected) + 1 == uncaught);          \
+            if ((expected) < uncaught)                                             \
+            {                                                                      \
+                tryLogCurrentException("NOEXCEPT_SCOPE");                          \
```
Comment (azat) [inline src/Common/noexcept_scope.h:15]: This will not work, you cannot rethrow exception outside the catch block, this will simply terminate (via std::terminate) the program. So this `NOEXCEPT_SCOPE` macro will simply call `std::terminate` on exception and will lost original exception.

I was thinking about this a little, and the only thing that pops up in my mind is setting some flag here and check it in Exception ctor and if it set, call abort/std::terminate, that way you will not loose it, however it looks not great.

File: src/Storages/MergeTree/MergeTreeData.cpp [hunk 2]
```diff
@@ -4951,6 +4949,18 @@ MergeTreeData::DataPartsVector MergeTreeData::Transaction::commit(MergeTreeData:
...
+        {
+            for (const DataPartPtr & part : precommitted_parts)
+            {
+                DataPartPtr covering_part;
+                DataPartsVector covered_parts = data.getActivePartsToReplace(part->info, part->name, covering_part, *owing_parts_lock);
+                MergeTreeTransaction::addNewPartAndRemoveCovered(data.shared_from_this(), part, covered_parts, txn);
+            }
+        }
+
+        NOEXCEPT_SCOPE;
```
Comment (azat) [inline src/Storages/MergeTree/MergeTreeData.cpp:4962]: Can you please explain why it is required? And looks like it is better to add a comment for users of NOEXCEPT_SCOPE, thoughts?

File: src/Interpreters/TransactionLog.cpp [hunk 3]
```diff
@@ -146,8 +143,7 @@ void TransactionLog::loadEntries(Strings::const_iterator beg, Strings::const_ite
     }
     futures.clear();
 
-    NOEXCEPT_SCOPE;
-    LockMemoryExceptionInThread lock_memory_tracker(VariableContext::Global);
+    NOEXCEPT_SCOPE_STRICT;
```
Comment (azat) [inline src/Interpreters/TransactionLog.cpp:146]: I see the difference between them, but can you explain why strict variant is used here?

File: src/Common/noexcept_scope.h (hunk 1 above)
Comment (tavplubix) [reply src/Common/noexcept_scope.h:15]: You're right, it does not work as expected and seems like it's there's no way to get exception that is currently unwinding stack (even using `__cxa_*` functions or something from libunwind...). Not sure what options is better: just remove this like or add thread-local flag and check it when throwing an exception. Maybe it's ok to simply remove it for now and think about logging if we will face some issue that we will not be able to debug without information about unexpected exception...

File: src/Storages/MergeTree/MergeTreeData.cpp (hunk 2 above)
Comment (tavplubix) [reply src/Storages/MergeTree/MergeTreeData.cpp:4962]: See the comment:
https://github.com/ClickHouse/ClickHouse/blob/39c0219c11aab1d4fd0897d05e00543eeef45eef/src/Common/noexcept_scope.h#L30-L33

It's required in `MergeTreeData::Transaction::commit` because changes to precommitted parts and `MergeTreeData` state (like set of parts with their states, indexes and column sizes) are not undone on exceptions. Normally this code should not throw any exceptions (unless maybe `MEMORY_LIMIT_EXCEEDED`, but exceptions from `MemoryTracker` are blocked), but in case it does (due to some bug or whatever) I would prefer to terminate immediately. 

You can think of this macro as kind of paranoid defensive programming :)

File: src/Interpreters/TransactionLog.cpp (hunk 3 above)
Comment (tavplubix) [reply src/Interpreters/TransactionLog.cpp:146]: Because initially we had only strict variant and it was the only place where this macro was used. But strict variant is not generic enough to use it in other places. I decided to leave strict variant here because something is probably going wrong if some code tries to initialize transaction log during stack unwinding.

File: src/Common/noexcept_scope.h (hunk 1 above)
Comment (azat) [reply src/Common/noexcept_scope.h:15]: Here is an RFC - #39229
