### PR TITLE
Fix incompatible result type for scalar queries with empty result.

### LINKED ISSUE #25411: Bug report: Assertion `result_type->isNullable()' failed
**Describe the bug**

I used my fuzzing tool to test ClickHouse (v21.5.6.6-stable), and found an assertion failure by using specific sql.

**Does it reproduce on recent release?**

v21.5.6.6-stable

**How to reproduce**

* ClickHouse server version: v21.5.6.6-stable
* Installation: 
```
1. mkdir build; cd build
2. cmake ..  \
        -DCMAKE_BUILD_TYPE=Debug     \
        -DENABLE_CLICKHOUSE_ALL=OFF     \
        -DENABLE_CLICKHOUSE_SERVER=ON     \
        -DENABLE_CLICKHOUSE_CLIENT=ON     \
        -DENABLE_LIBRARIES=OFF     \
        -DUSE_UNWIND=ON     \
        -DENABLE_UTILS=OFF     \
        -DENABLE_TESTS=OFF -DSANITIZE=address
3. sudo make install
```

* Test command: 
```
1. clickhouse-server &

2. clickhouse-client --query '
create table t_q1ht4gq_5 (
c_zeij INTEGER NOT NULL,
c_fehk75l TEXT ,
c_jz TEXT ,
c_wynzuek TEXT ,
c_nkt INTEGER NOT NULL,
c_g TEXT ,
c_mc2 TEXT ,
primary key(c_nkt)
) engine = MergeTree();'

3. clickhouse-client --query '
WITH
cte_0 AS (select
    subq_0.c6 as c2,
    case when 0<>0 then ((select c_zeij from t_q1ht4gq_5 order by c_zeij limit 1 offset 1)
           + subq_0.c4) else ((select c_zeij from t_q1ht4gq_5 order by c_zeij limit 1 offset 1)
           + subq_0.c4) end as c4 
  from
    (select  
          ref_0.c_nkt as c4, 
          ref_0.c_nkt as c6  
        from 
          t_q1ht4gq_5 as ref_0
        ) as subq_0
  )
select
    ref_12.c_zeij as c3
  from
    t_q1ht4gq_5 as ref_12
  where (ref_12.c_jz not in (
          select
              ref_14.c_mc2 as c0
            from
              t_q1ht4gq_5 as ref_14
                cross join cte_0 as ref_15
            where ref_15.c4 > ref_15.c2))
;'
```

**Expected behavior**

Normally run.

**Error message and/or stacktrace**

```
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:900
```

**Log file of ClickHouse Server**

```
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Logging trace to console
2021.06.17 20:40:36.834407 [ 32415 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.06.17 20:40:43.260089 [ 32415 ] {} <Information> : Starting ClickHouse 21.5.6.1 with revision 54450, build id: D418120B6778C79B, PID 32415
2021.06.17 20:40:43.260757 [ 32415 ] {} <Information> : Set OOM score adjustment to 555
2021.06.17 20:40:43.261943 [ 32415 ] {} <Information> Application: starting up
2021.06.17 20:40:43.299861 [ 32415 ] {} <Warning> Application: Server was built in debug mode. It will work slowly.
2021.06.17 20:40:43.300162 [ 32415 ] {} <Warning> Application: Server was built with sanitizer. It will work slowly.
2021.06.17 20:41:33.539241 [ 32415 ] {} <Warning> Application: Calculated checksum of the binary: 3F2399641A58AB6899D4DE6968820D06. There is no information about the reference checksum.
2021.06.17 20:41:33.539820 [ 32415 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/local/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2021.06.17 20:41:33.540425 [ 32415 ] {} <Information> StatusFile: Status file ./status already exists - unclean restart. Contents:
PID: 31500
Started at: 2021-06-17 20:37:24
Revision: 54450

2021.06.17 20:41:33.540817 [ 32415 ] {} <Debug> Application: rlimit on number of file descriptors is 1048576
2021.06.17 20:41:33.541079 [ 32415 ] {} <Debug> Application: Initializing DateLUT.
2021.06.17 20:41:33.541265 [ 32415 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2021.06.17 20:41:33.541651 [ 32415 ] {} <Debug> Application: Setting up ./tmp/ to store temporary data in it
2021.06.17 20:41:33.542406 [ 32415 ] {} <Debug> Application: Initiailizing interserver credentials.
2021.06.17 20:41:33.570810 [ 32415 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2021.06.17 20:41:33.576967 [ 32415 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2021.06.17 20:41:33.584385 [ 32415 ] {} <Information> Application: Setting max_server_memory_usage was set to 28.22 GiB (31.36 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2021.06.17 20:41:33.586544 [ 32415 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2021.06.17 20:41:33.614348 [ 32415 ] {} <Debug> ConfigReloader: Loading config 'config.xml'
Processing configuration file 'config.xml'.
There is no file 'config.xml', will use embedded config.
Saved preprocessed configuration to './preprocessed_configs/config.xml'.
2021.06.17 20:41:33.620156 [ 32415 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performing update on configuration
2021.06.17 20:41:33.653580 [ 32415 ] {} <Debug> ConfigReloader: Loaded config 'config.xml', performed update on configuration
2021.06.17 20:41:33.659532 [ 32415 ] {} <Debug> Access(user directories): Added users.xml access storage 'users.xml', path: config.xml
2021.06.17 20:41:33.662998 [ 32415 ] {} <Information> Application: Loading metadata from ./
2021.06.17 20:41:33.666256 [ 32415 ] {} <Information> DatabaseAtomic (system): Total 0 tables and 0 dictionaries.
2021.06.17 20:41:33.666403 [ 32415 ] {} <Information> DatabaseAtomic (system): Starting up tables.
2021.06.17 20:41:35.443707 [ 32415 ] {} <Information> DatabaseAtomic (default): Total 0 tables and 0 dictionaries.
2021.06.17 20:41:35.443962 [ 32415 ] {} <Information> DatabaseAtomic (default): Starting up tables.
2021.06.17 20:41:35.460386 [ 32415 ] {} <Information> DatabaseAtomic (re_test_db): Total 1 tables and 0 dictionaries.
2021.06.17 20:41:35.472996 [ 32617 ] {} <Debug> re_test_db.t_q1ht4gq_5 (0c4ce51e-840f-42f7-add8-6634c8677067): Loading data parts
2021.06.17 20:41:35.473598 [ 32617 ] {} <Debug> re_test_db.t_q1ht4gq_5 (0c4ce51e-840f-42f7-add8-6634c8677067): There are no data parts
2021.06.17 20:41:35.474639 [ 32415 ] {} <Information> DatabaseAtomic (re_test_db): Starting up tables.
2021.06.17 20:41:35.475728 [ 32617 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 16 threads
2021.06.17 20:41:35.494538 [ 32415 ] {} <Information> DatabaseCatalog: Found 4 partially dropped tables. Will load them and retry removal.
2021.06.17 20:41:35.495689 [ 32617 ] {} <Information> DatabaseCatalog: Trying load partially dropped table re_test_db.t_q1ht4gq_5 (32d819e1-c9fb-4ab0-8170-5e75c4cfe8f4) from ./metadata_dropped/re_test_db.t_q1ht4gq_5.32d819e1-c9fb-4ab0-8170-5e75c4cfe8f4.sql
2021.06.17 20:41:35.497318 [ 32637 ] {} <Information> DatabaseCatalog: Trying load partially dropped table re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab) from ./metadata_dropped/re_test_db.t_q1ht4gq_5.88e3180c-15bd-4aa4-af72-a89626a70dab.sql
2021.06.17 20:41:35.497425 [ 32635 ] {} <Information> DatabaseCatalog: Trying load partially dropped table re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8) from ./metadata_dropped/re_test_db.t_q1ht4gq_5.50cc7d75-6274-48b0-a944-9d528ff2cdd8.sql
2021.06.17 20:41:35.497463 [ 32636 ] {} <Information> DatabaseCatalog: Trying load partially dropped table re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc) from ./metadata_dropped/re_test_db.t_q1ht4gq_5.61a92440-26d4-4c45-8011-c788893650dc.sql
2021.06.17 20:41:35.518976 [ 32617 ] {} <Debug> re_test_db.t_q1ht4gq_5 (32d819e1-c9fb-4ab0-8170-5e75c4cfe8f4): Loading data parts
2021.06.17 20:41:35.519102 [ 32637 ] {} <Debug> re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab): Loading data parts
2021.06.17 20:41:35.519749 [ 32617 ] {} <Debug> re_test_db.t_q1ht4gq_5 (32d819e1-c9fb-4ab0-8170-5e75c4cfe8f4): There are no data parts
2021.06.17 20:41:35.519796 [ 32637 ] {} <Debug> re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab): There are no data parts
2021.06.17 20:41:35.524137 [ 32635 ] {} <Debug> re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8): Loading data parts
2021.06.17 20:41:35.524195 [ 32636 ] {} <Debug> re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc): Loading data parts
2021.06.17 20:41:35.524770 [ 32635 ] {} <Debug> re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8): There are no data parts
2021.06.17 20:41:35.524788 [ 32636 ] {} <Debug> re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc): There are no data parts
2021.06.17 20:41:35.526129 [ 32415 ] {} <Debug> Application: Loaded metadata.
2021.06.17 20:41:35.526315 [ 32415 ] {} <Information> Application: Query Profiler and TraceCollector are disabled because they cannot work under sanitizers when two different stack unwinding methods will interfere with each other.
2021.06.17 20:41:35.526579 [ 32620 ] {} <Information> DatabaseCatalog: Have 4 tables in drop queue (0 of them are in use), will try drop re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab)
2021.06.17 20:41:35.526725 [ 32415 ] {} <Information> Application: It looks like the process has no CAP_SYS_NICE capability, the setting 'os_thread_priority' will have no effect. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_sys_nice=+ep /usr/local/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2021.06.17 20:41:35.527087 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab): dropAllData: waiting for locks.
2021.06.17 20:41:35.527359 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab): dropAllData: removing data from memory.
2021.06.17 20:41:35.527618 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab): dropAllData: removing data from filesystem.
2021.06.17 20:41:35.528823 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab): dropAllData: done.
2021.06.17 20:41:35.528955 [ 32415 ] {} <Information> Application: Listening for http://[::1]:8123
2021.06.17 20:41:35.529356 [ 32620 ] {} <Information> DatabaseCatalog: Removing metadata ./metadata_dropped/re_test_db.t_q1ht4gq_5.88e3180c-15bd-4aa4-af72-a89626a70dab.sql of dropped table re_test_db.t_q1ht4gq_5 (88e3180c-15bd-4aa4-af72-a89626a70dab)
2021.06.17 20:41:35.530037 [ 32415 ] {} <Information> Application: Listening for connections with native protocol (tcp): [::1]:9000
2021.06.17 20:41:35.530416 [ 32619 ] {} <Trace> DatabaseCatalog: Not found any suitable tables to drop, still have 3 tables in drop queue (0 of them are in use). Will check again after 3 seconds
2021.06.17 20:41:35.530819 [ 32415 ] {} <Information> Application: Listening for MySQL compatibility protocol: [::1]:9004
2021.06.17 20:41:35.531607 [ 32415 ] {} <Information> Application: Listening for http://127.0.0.1:8123
2021.06.17 20:41:35.532045 [ 32415 ] {} <Information> Application: Listening for connections with native protocol (tcp): 127.0.0.1:9000
2021.06.17 20:41:35.532532 [ 32415 ] {} <Information> Application: Listening for MySQL compatibility protocol: 127.0.0.1:9004
2021.06.17 20:41:35.533126 [ 32415 ] {} <Debug> AsynchronousMetrics: MemoryTracking: was 0.00 B, peak 0.00 B, will set to 1.34 GiB (RSS), difference: 1.34 GiB
2021.06.17 20:41:35.533360 [ 32415 ] {} <Debug> MemoryTracker: Current memory usage (total): 1.34 GiB.
2021.06.17 20:41:35.555381 [ 32415 ] {} <Information> DNSCacheUpdater: Update period 15 seconds
2021.06.17 20:41:35.555820 [ 32415 ] {} <Information> Application: Available RAM: 31.36 GiB; physical cores: 12; logical cores: 12.
2021.06.17 20:41:35.555897 [ 32621 ] {} <Debug> DNSResolver: Updating DNS cache
2021.06.17 20:41:35.556327 [ 32621 ] {} <Debug> DNSResolver: Updated DNS cache
2021.06.17 20:41:35.558515 [ 32415 ] {} <Information> Application: Ready for connections.
2021.06.17 20:41:38.531592 [ 32620 ] {} <Information> DatabaseCatalog: Have 3 tables in drop queue (0 of them are in use), will try drop re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc)
2021.06.17 20:41:38.532154 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc): dropAllData: waiting for locks.
2021.06.17 20:41:38.532468 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc): dropAllData: removing data from memory.
2021.06.17 20:41:38.532837 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc): dropAllData: removing data from filesystem.
2021.06.17 20:41:38.534560 [ 32620 ] {} <Trace> re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc): dropAllData: done.
2021.06.17 20:41:38.535194 [ 32620 ] {} <Information> DatabaseCatalog: Removing metadata ./metadata_dropped/re_test_db.t_q1ht4gq_5.61a92440-26d4-4c45-8011-c788893650dc.sql of dropped table re_test_db.t_q1ht4gq_5 (61a92440-26d4-4c45-8011-c788893650dc)
2021.06.17 20:41:38.536869 [ 32621 ] {} <Trace> DatabaseCatalog: Not found any suitable tables to drop, still have 2 tables in drop queue (0 of them are in use). Will check again after 12 seconds
2021.06.17 20:41:50.538183 [ 32625 ] {} <Information> DatabaseCatalog: Have 2 tables in drop queue (0 of them are in use), will try drop re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8)
2021.06.17 20:41:50.538876 [ 32625 ] {} <Trace> re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8): dropAllData: waiting for locks.
2021.06.17 20:41:50.539242 [ 32625 ] {} <Trace> re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8): dropAllData: removing data from memory.
2021.06.17 20:41:50.539592 [ 32625 ] {} <Trace> re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8): dropAllData: removing data from filesystem.
2021.06.17 20:41:50.541254 [ 32625 ] {} <Trace> re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8): dropAllData: done.
2021.06.17 20:41:50.541918 [ 32625 ] {} <Information> DatabaseCatalog: Removing metadata ./metadata_dropped/re_test_db.t_q1ht4gq_5.50cc7d75-6274-48b0-a944-9d528ff2cdd8.sql of dropped table re_test_db.t_q1ht4gq_5 (50cc7d75-6274-48b0-a944-9d528ff2cdd8)
2021.06.17 20:41:50.543361 [ 32626 ] {} <Trace> DatabaseCatalog: Not found any suitable tables to drop, still have 1 tables in drop queue (0 of them are in use). Will check again after 132 seconds
2021.06.17 20:41:50.556840 [ 32627 ] {} <Debug> DNSResolver: Updating DNS cache
2021.06.17 20:41:50.557251 [ 32627 ] {} <Debug> DNSResolver: Updated DNS cache
2021.06.17 20:41:51.515891 [ 32613 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 127.0.0.1:57958
2021.06.17 20:41:51.518286 [ 32613 ] {} <Debug> TCPHandler: Connected ClickHouse client version 21.5.0, revision: 54448, user: default.
2021.06.17 20:41:51.522732 [ 32613 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2021.06.17 20:41:51.523594 [ 32613 ] {} <Trace> ContextAccess (default): List of all grants: GRANT ALL ON *.* WITH GRANT OPTION
2021.06.17 20:41:51.524275 [ 32613 ] {} <Trace> ContextAccess (default): List of all grants including implicit: GRANT ALL ON *.* WITH GRANT OPTION
2021.06.17 20:41:53.483966 [ 32613 ] {d2553833-0157-4096-b471-226bac4d82e8} <Debug> executeQuery: (from 127.0.0.1:57958, using production parser)  create table t_q1ht4gq_5 ( c_zeij INTEGER NOT NULL, c_fehk75l TEXT , c_jz TEXT , c_wynzuek TEXT , c_nkt INTEGER NOT NULL, c_g TEXT , c_mc2 TEXT , primary key(c_nkt) ) engine = MergeTree();
2021.06.17 20:41:53.485256 [ 32613 ] {d2553833-0157-4096-b471-226bac4d82e8} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON default.t_q1ht4gq_5
2021.06.17 20:41:53.539214 [ 32613 ] {d2553833-0157-4096-b471-226bac4d82e8} <Debug> default.t_q1ht4gq_5 (e3fe7790-5077-42b4-9572-ca623ac3e4fb): Loading data parts
2021.06.17 20:41:53.539954 [ 32613 ] {d2553833-0157-4096-b471-226bac4d82e8} <Debug> default.t_q1ht4gq_5 (e3fe7790-5077-42b4-9572-ca623ac3e4fb): There are no data parts
2021.06.17 20:41:53.582449 [ 32613 ] {d2553833-0157-4096-b471-226bac4d82e8} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.06.17 20:41:53.583784 [ 32613 ] {} <Debug> TCPHandler: Processed in 0.11289809 sec.
2021.06.17 20:41:53.584877 [ 32613 ] {} <Debug> TCPHandler: Done processing connection.
2021.06.17 20:42:00.332290 [ 32613 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 127.0.0.1:57960
2021.06.17 20:42:00.334155 [ 32613 ] {} <Debug> TCPHandler: Connected ClickHouse client version 21.5.0, revision: 54448, user: default.
2021.06.17 20:42:02.375165 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Debug> executeQuery: (from 127.0.0.1:57960, using production parser)  WITH cte_0 AS (select subq_0.c6 as c2, case when 0<>0 then ((select c_zeij from t_q1ht4gq_5 order by c_zeij limit 1 offset 1) + subq_0.c4) else ((select c_zeij from t_q1ht4gq_5 order by c_zeij limit 1 offset 1) + subq_0.c4) end as c4 from (select ref_0.c_nkt as c4, ref_0.c_nkt as c6 from t_q1ht4gq_5 as ref_0 ) as subq_0 ) select ref_12.c_zeij as c3 from t_q1ht4gq_5 as ref_12 where (ref_12.c_jz not in ( select ref_14.c_mc2 as c0 from t_q1ht4gq_5 as ref_14 cross join cte_0 as ref_15 where ref_15.c4 > ref_15.c2)) ;
2021.06.17 20:42:02.398051 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_nkt) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.403211 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_nkt) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.410950 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_zeij) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.436332 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_nkt) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.444426 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_zeij) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.447759 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.06.17 20:42:02.459083 [ 32656 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> PipelineExecutor: Thread finished. Total time: 0.001007495 sec. Execution time: 0.00019242 sec. Processing time: 0.000722463 sec. Wait time: 9.2612e-05 sec.
2021.06.17 20:42:02.466889 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_zeij) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.469941 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.06.17 20:42:02.480478 [ 32656 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> PipelineExecutor: Thread finished. Total time: 0.001129093 sec. Execution time: 0.000155334 sec. Processing time: 0.000877237 sec. Wait time: 9.6522e-05 sec.
2021.06.17 20:42:02.500658 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: Running 'analyze' second time
2021.06.17 20:42:02.505775 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_nkt) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.512319 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: Running 'analyze' second time
2021.06.17 20:42:02.531375 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: Running 'analyze' second time
2021.06.17 20:42:02.536219 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_nkt) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.542674 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.06.17 20:42:02.544544 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.06.17 20:42:02.549745 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Debug> HashJoin: Right sample block: c2 Int32 Int32(size = 0), c4 Nullable(Nothing) Nullable(size = 0, Nothing(size = 0), UInt8(size = 0))
2021.06.17 20:42:02.553503 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> ContextAccess (default): Access granted: SELECT(c_mc2) ON default.t_q1ht4gq_5
2021.06.17 20:42:02.554657 [ 32613 ] {3e73eaf7-99b8-459e-9213-d623f8bbe6d4} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
clickhouse-server: ../src/Functions/IFunction.cpp:263: DB::ColumnPtr DB::ExecutableFunctionAdaptor::defaultImplementationForNulls(const DB::ColumnsWithTypeAndName &, const DB::DataTypePtr &, size_t, bool) const: Assertion `result_type->isNullable()' failed.
2021.06.17 20:42:02.557345 [ 32432 ] {} <Trace> BaseDaemon: Received signal 6
2021.06.17 20:42:02.558289 [ 32739 ] {} <Fatal> BaseDaemon: ########################################
2021.06.17 20:42:02.560063 [ 32739 ] {} <Fatal> BaseDaemon: (version 21.5.6.1, build id: D418120B6778C79B) (from thread 32613) (query_id: 3e73eaf7-99b8-459e-9213-d623f8bbe6d4) Received signal Aborted (6)
2021.06.17 20:42:02.560812 [ 32739 ] {} <Fatal> BaseDaemon: 
2021.06.17 20:42:02.562125 [ 32739 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f177c6eef47 0x7f177c6f08b1 0x7f177c6e042a 0x7f177c6e04a2 0x1f25c93b 0x1f25adb5 0x1f2625f1 0x44e17b8b 0x44e1357e 0x4daefaa0 0x4e0a085b 0x45570b82 0x45501cbe 0x454d2746 0x454c6f2a 0x47b6be7d 0x466db77d 0x466c1574 0x466bce75 0x465de395 0x4657ab0c 0x4659e454 0x465bbc15 0x454db328 0x454c2ec2 0x454ab159 0x454a48ff 0x47b76a5d 0x47b676aa 0x47b646f0 0x47d22feb 0x48b1418a 0x48a90f98 0x48a86600 0x4d02b55c 0x4d07cce5 0x508c5203 0x508c7962 0x51a754e6 0x51a5e2ce 0x51a56b10 0x7f177c0fa6db 0x7f177c7d1a3f
2021.06.17 20:42:02.573895 [ 32739 ] {} <Fatal> BaseDaemon: 4. /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51: __GI_raise @ 0x3ef47 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2021.06.17 20:42:02.596775 [ 32739 ] {} <Fatal> BaseDaemon: 5. /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81: abort @ 0x408b1 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2021.06.17 20:42:02.631400 [ 32739 ] {} <Fatal> BaseDaemon: 6. /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89: __assert_fail_base @ 0x3042a in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2021.06.17 20:42:02.813716 [ 32739 ] {} <Fatal> BaseDaemon: 7. ? @ 0x304a2 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
2021.06.17 20:42:05.557845 [ 32633 ] {} <Debug> DNSResolver: Updating DNS cache
2021.06.17 20:42:05.558369 [ 32633 ] {} <Debug> DNSResolver: Updated DNS cache
2021.06.17 20:42:17.822707 [ 32739 ] {} <Fatal> BaseDaemon: 8. /home/ssr/research-project/dbms-test/target-dbms/ClickHouse/build/../src/Functions/IFunction.cpp:0: DB::ExecutableFunctionAdaptor::defaultImplementationForNulls(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x1f25c93b in /usr/local/bin/clickhouse
2021.06.17 20:42:20.559001 [ 32633 ] {} <Debug> DNSResolver: Updating DNS cache
2021.06.17 20:42:20.559504 [ 32633 ] {} <Debug> DNSResolver: Updated DNS cache
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by KochetovNicolai**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Now, scalar subquery always returns `Nullable` result if it's type can be `Nullable`. It is needed because in case of empty subquery it's result should be `Null`. Previously, it was possible to get error about incompatible types (type deduction does not execute scalar subquery, and it could use not-nullable type). Scalar subquery with empty result which can't be converted to `Nullable` (like `Array` or `Tuple`) now throws error.  Fixes #25411

### CODE REVIEW

File: src/Functions/IFunction.cpp [hunk 1]
```diff
@@ -181,7 +181,10 @@ ColumnPtr IExecutableFunction::defaultImplementationForNulls(
     {
         // Default implementation for nulls returns null result for null arguments,
         // so the result type must be nullable.
-        assert(result_type->isNullable());
+        if (!result_type->isNullable())
+            throw Exception(ErrorCodes::LOGICAL_ERROR,
+                            "Function {} with Null argument and default implementation for Nulls "
```
Comment (alexey-milovidov) [inline src/Functions/IFunction.cpp:186]: expect -> is expected

File: tests/queries/0_stateless/00205_scalar_subqueries.sql [hunk 2]
```diff
@@ -8,3 +8,52 @@ SELECT (SELECT toDate('2015-01-02'), 'Hello') AS x, x, identity((SELECT 1)), ide
 -- SELECT (SELECT uniqState(''));
 
  SELECT ( SELECT throwIf(1 + dummy) );  -- { serverError 395 }
+
+-- Scalar subquery with 0 rows must return Null
+SELECT (SELECT 1 WHERE 0);
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/00205_scalar_subqueries.sql:13]: I think splitting it to a new test will be better.

**Review by alexey-milovidov — APPROVED** [review]
