### PR TITLE
Fix incorrect partition pruning when constant in predicate has no supertype of related key columns

### LINKED ISSUE #35304: Using UInt64 with partition using toYYYYMMDD produces empty result on queries filtering against negative values
**Describe the issue**
A table that includes a field with UInt64 and uses that field to create partition using toYYYYMMDD fails to return values when doing a query for values larger than -1. This used to work in ClickHouse version 20.8.7.15 and it is currently broken in version 22.2.3.1 resulting in broken code.

**Which ClickHouse server versions are incompatible**
Versions 20.8.7.15 and 22.2.3.1

**How to reproduce**
Create table and insert data:
```
CREATE TABLE broken ( time UInt64 ) ENGINE = MergeTree PARTITION BY toYYYYMMDD(toDate(time / 1000)) ORDER BY time;
INSERT INTO broken (time) VALUES (1647353101000), (1647353101001), (1647353101002), (1647353101003);
```

Run the following queries:
```
SELECT * FROM broken WHERE time>0;
SELECT * FROM broken WHERE time>-1;
```

The first query returns all records, the second one returns empty result.

### PR DESCRIPTION
**Pull request by amosbird**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix partition pruning in case of comparison with constant in `WHERE`. If column and constant had different types, overflow was possible. Query could return an incorrect empty result. This fixes https://github.com/ClickHouse/ClickHouse/issues/35304

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by KochetovNicolai** [comment]
Ok, some tests are broken now - looks like we need a better check when we can cast constant.
Or, maybe, we need a special attention to Date/DateTime case?

**Comment by KochetovNicolai** [comment]
maybe just use castColumnAccurate(OrNull)?

File: src/Client/ClientBase.cpp [hunk 1]
```diff
@@ -1979,9 +1979,8 @@ void ClientBase::readArguments(
         }
         /// Options with value after equal sign.
         else if (in_external_group
-            && (0 == strncmp(arg, "--file=", strlen("--file=")) || 0 == strncmp(arg, "--name=", strlen("--name="))
-                || 0 == strncmp(arg, "--format=", strlen("--format=")) || 0 == strncmp(arg, "--structure=", strlen("--structure="))
-                || 0 == strncmp(arg, "--types=", strlen("--types="))))
+            && (arg == "--file="sv || arg == "--name="sv || arg == "--format="sv
+                || arg == "--structure="sv || arg == "--types="sv))
```
Comment (Avogar) [inline src/Client/ClientBase.cpp:1983]: This wont work. For example when we have `--file=file_name` the value of `arg` will be `"--file=file_name`" and we will compare it with `"--file="` and it will fail

Comment (amosbird) [reply src/Client/ClientBase.cpp:1983]: Oh, so it's a `startsWith` semantic.

Comment (amosbird) [reply src/Client/ClientBase.cpp:1983]: But why do we do exact match for variant without equal sign?

Comment (Avogar) [reply src/Client/ClientBase.cpp]: I think we can use `starts_with` from C++20 here to simplify the code

**Review by KochetovNicolai — APPROVED** [review]

**Comment by KochetovNicolai** [comment]
Looks like Backward compatibility check cannot fond old binary packet.

**Comment by Avogar** [comment]
> Looks like Backward compatibility check cannot fond old binary packet.

Yep, I am investigating. Maybe some retries will help. If not, will make this check always green until I fix it.
