### PR TITLE
Allow server to start with broken data lake table and fix itself lazily

### LINKED ISSUE #58625: DeltaLake: ClickHouse Server fails to start if the Bucket does not exist.
**Version**: 23.9.2.46708

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

The following exception causes the server to crash. 

```
2024.01.09 12:09:41.101670 [ 85 ]  {} <Error> Application: DB::Exception: Could not list objects in bucket 'bucket-name' with key '<redacted>, S3 exception: `NoSuchBucket`, message: 'The specified bucket does not exist': Cannot attach table `default`.`<table_name>` from metadata file /var/lib/clickhouse/store/.../.../table_name.sql from query ATTACH TABLE default.table_name UUID '<uuid>' (...) ENGINE = DeltaLake('https://s3.amazonaws.com/path/to/delta/lake', 'aws_access_key_id', 'aws_secret_access_key')
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c7a6957 in /usr/bin/clickhouse
1. DB::S3Exception::S3Exception<String, String, String, String>(Aws::S3::S3Errors, fmt::v8::basic_format_string<char, fmt::v8::type_identity<String>::type, fmt::v8::type_identity<String>::type, fmt::v8::type_identity<String>::type, fmt::v8::type_identity<String>::type>, String&&, String&&, String&&, String&&) @ 0x0000000010eabe88 in /usr/bin/clickhouse
2. DB::S3DataLakeMetadataReadHelper::listFiles(DB::StorageS3::Configuration const&, String const&, String const&) @ 0x0000000010eaba39 in /usr/bin/clickhouse
3. DB::DeltaLakeMetadataParser<DB::StorageS3::Configuration, DB::S3DataLakeMetadataReadHelper>::getFiles(DB::StorageS3::Configuration const&, std::shared_ptr<DB::Context const>) @ 0x00000000071aabce in /usr/bin/clickhouse
4. DB::IStorageDataLake<DB::StorageS3, DB::StorageDeltaLakeName, DB::DeltaLakeMetadataParser<DB::StorageS3::Configuration, DB::S3DataLakeMetadataReadHelper>>::getDataFiles(DB::StorageS3::Configuration const&, std::shared_ptr<DB::Context const>) @ 0x0000000010b8846b in /usr/bin/clickhouse
5. DB::IStorageDataLake<DB::StorageS3, DB::StorageDeltaLakeName, DB::DeltaLakeMetadataParser<DB::StorageS3::Configuration, DB::S3DataLakeMetadataReadHelper>>::getConfigurationForDataRead(DB::StorageS3::Configuration const&, std::shared_ptr<DB::Context const>, std::vector<String, std::allocator<String>> const&) @ 0x0000000010b87cd3 in /usr/bin/clickhouse
6. std::shared_ptr<DB::IStorage> std::__function::__policy_invoker<std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__function::__default_alloc_func<DB::registerStorageDeltaLake(DB::StorageFactory&)::$_0, std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) (.llvm.872024380460091824) @ 0x0000000012d935ac in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context>, std::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x00000000129aa1bb in /usr/bin/clickhouse
8. DB::createTableFromAST(DB::ASTCreateQuery, String const&, String const&, std::shared_ptr<DB::Context>, bool) @ 0x00000000116901d0 in /usr/bin/clickhouse
9. DB::DatabaseOrdinary::loadTableFromMetadata(std::shared_ptr<DB::Context>, String const&, DB::QualifiedTableName const&, std::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x00000000116af08f in /usr/bin/clickhouse
10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::TablesLoader::startLoadingTables(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, std::shared_ptr<DB::Context>, std::vector<DB::StorageID, std::allocator<DB::StorageID>> const&, unsigned long)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000120b96ff in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c8927bf in /usr/bin/clickhouse
12. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c8962dc in /usr/bin/clickhouse
13. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c894b07 in /usr/bin/clickhouse
14. ? @ 0x00007fc8f0cf7ac3 in ?
15. ? @ 0x00007fc8f0d89660 in ?
 (version 23.9.2.47608 (official build))
2024.01.09 12:09:41.101831 [ 85 ] {} <Information> Application: shutting down
2024.01.09 12:09:41.101840 [ 85 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2024.01.09 12:09:41.102478 [ 87 ] {} <Trace> BaseDaemon: Received signal -2
2024.01.09 12:09:41.102511 [ 87 ] {} <Information> BaseDaemon: Stop SignalListener thread
2024.01.09 12:09:41.160849 [ 1 ] {} <Information> Application: Child process exited normally with code 70.
 ```

**Expected behavior**

Even if the bucket no longer exists, the server should still continue to run.

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Allow server to start with broken data lake table. Closes https://github.com/ClickHouse/ClickHouse/issues/58625.

### CODE REVIEW

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 1aa8e62bb78bdeb41479b48d345e83bf317cb961 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/59080/1aa8e62bb78bdeb41479b48d345e83bf317cb961/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/59080/1aa8e62bb78bdeb41479b48d345e83bf317cb961/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

File: src/Storages/DataLakes/IStorageDataLake.h [hunk 1]
```diff
@@ -22,15 +22,15 @@ class IStorageDataLake : public Storage
     using Configuration = typename Storage::Configuration;
 
     template <class ...Args>
-    explicit IStorageDataLake(const Configuration & configuration_, ContextPtr context_, Args && ...args)
-        : Storage(getConfigurationForDataRead(configuration_, context_), context_, std::forward<Args>(args)...)
+    explicit IStorageDataLake(const Configuration & configuration_, ContextPtr context_, bool attach, Args && ...args)
```
Comment (Avogar) [inline src/Storages/DataLakes/IStorageDataLake.h:25]: I don't quite understand why we need `attach` flag in the constructor, I see that we set it alwasy to `true` in `ITableFunctionDataLake.h`.
We can just add `throw_on_error` flag to `getConfigurationForDataRead` and set it to `false` when it's called from constructor.

File: src/Storages/DataLakes/IStorageDataLake.h [hunk 2]
```diff
@@ -94,10 +104,11 @@ class IStorageDataLake : public Storage
         const bool updated = base_configuration.update(local_context);
         auto new_keys = getDataFiles(base_configuration, local_context);
 
-        if (!updated && new_keys == Storage::getConfiguration().keys)
+        if (!updated && !base_configuration.is_broken && new_keys == Storage::getConfiguration().keys)
```
Comment (Avogar) [inline src/Storages/DataLakes/IStorageDataLake.h:107]: Why do we need `is_broken` flag? If we failed to parse metadata on storage creation and managed to do it on read in `getDataFiles` called above, we will have different `new_keys` and `Storage::getConfiguration().keys` and this condition will not pass. If we failed to parse metadata on read too, we will have an exception during `getDataFiles` call above.

File: src/Storages/DataLakes/Iceberg/StorageIceberg.cpp [hunk 3]
```diff
@@ -52,8 +73,12 @@ void StorageIceberg::updateConfigurationImpl(ContextPtr local_context)
 {
     const bool updated = base_configuration.update(local_context);
     auto new_metadata = parseIcebergMetadata(base_configuration, local_context);
+
+    if (!current_metadata)
+        current_metadata = parseIcebergMetadata(base_configuration, local_context);
```
Comment (Avogar) [inline src/Storages/DataLakes/Iceberg/StorageIceberg.cpp:78]: If we don't have `current_metadata`, we will do the same work twice here. We can check if we don't have `current_metadata` just parse it and update the configuration, because we don't have 2 different metadatas to compare

File: src/Storages/DataLakes/IStorageDataLake.h (hunk 1 above)
Comment (Avogar) [reply src/Storages/DataLakes/IStorageDataLake.h:25]: I think it's ok not to throw not only in case of attach, but always on storage creation and throw only when we read from it.

Comment (kssenii) [reply src/Storages/DataLakes/IStorageDataLake.h:25]: > I think it's ok not to throw not only in case of attach, but always on storage creation and throw only when we read from it.

I think we should not silence the error on create query, it is done this way for several table engines already.

File: src/TableFunctions/ITableFunctionDataLake.h [hunk 4]
```diff
@@ -34,7 +34,7 @@ class ITableFunctionDataLake : public TableFunction
             columns = parseColumnsListFromString(TableFunction::configuration.structure, context);
 
         StoragePtr storage = Storage::create(
-            TableFunction::configuration, context, StorageID(TableFunction::getDatabaseName(), table_name),
+            TableFunction::configuration, context, false, StorageID(TableFunction::getDatabaseName(), table_name),
```
Comment (Avogar) [inline src/TableFunctions/ITableFunctionDataLake.h:37]: What if table was created using `CREATE TABLE ... AS iceberg(...)`. Will we use table function during attach query?

Comment (kssenii) [reply src/TableFunctions/ITableFunctionDataLake.h:37]: Good point, though added a test in [a4082f5](https://github.com/ClickHouse/ClickHouse/pull/59080/commits/a4082f5b971b6da51bcdc65fca26b21b4b429c84) and it seems to work...

**Review by Avogar — APPROVED** [review]

File: src/TableFunctions/ITableFunctionDataLake.h (hunk 4 above)
Comment (Avogar) [reply src/TableFunctions/ITableFunctionDataLake.h:37]: Also made a test locally, and seems like in case of `CREATE TABLE ... AS iceberg(...)` during server startup we execute table function lazily on first request, so we don't actually attach Iceberg table
