### PR TITLE
Fix unused interpolate expressions

### LINKED ISSUE #65389: DB::Exception Not found column after upgrading from 23.8 to 24.5
**Describe what's wrong**

After upgrading to version 24.5.x, the request start  failing with the following error:
 
```
SQL Error [10] [07000]: Code: 10. DB::Exception: Not found column toFloat64(argMax(__table2.close_price, __table2.open_time)) in block. There are only columns: toDateTime64(toStartOfInterval(__table2.open_time, _CAST(1_IntervalHour, 'IntervalHour'_String)), 3_UInt8), argMin(__table2.open_price, __table2.open_time), argMax(__table2.close_price, __table2.open_time), toFloat64(argMin(__table2.open_price, __table2.open_time)). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.5.3.5 (official build))
```

**Does it reproduce on the most recent release?**

24.3 - 24.5.3.5

**How to reproduce**

```sql
CREATE TABLE foo_klines (
     open_time DateTime64(3),
     close_time DateTime64(3),
     open_price Decimal64(8),
     close_price Decimal64(8),
     high_price Decimal64(8),
     low_price Decimal64(8)
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(open_time)
ORDER BY open_time;


CREATE TABLE bar_klines (
    `time` DateTime64(0),
    open_price Decimal64(8),
    close_price Decimal64(8),
    high_price Decimal64(8),
    low_price Decimal64(8)
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(time)
ORDER BY time;


SELECT
    toUnixTimestamp64Milli(q0.open_time) as open_time,
    q0.open * q1.close as open
FROM (
	SELECT
	    toDateTime64(group_time, 3) as open_time,
	    toFloat64(argMin(open_price, t0.open_time)) as open,
	    toFloat64(argMax(close_price, t0.open_time)) as close
	FROM
	    foo_klines  as t0
	GROUP BY 
	    toStartOfInterval(t0.open_time, INTERVAL 1 HOUR) as group_time
	ORDER BY open_time ASC WITH FILL STEP INTERVAL 1 HOUR INTERPOLATE (
	    open, close
	)
) q0 INNER JOIN (
	SELECT
	    toDateTime64(group_time, 3) as open_time,
	    toFloat64(argMax(close_price, t1.time)) as close
	FROM
	    bar_klines as t1
	GROUP BY 
	    toStartOfInterval(t1.time, INTERVAL 1 HOUR) as group_time
	ORDER BY open_time ASC WITH FILL STEP INTERVAL 1 HOUR INTERPOLATE (
	    close
	)
) q1 ON q0.open_time = q1.open_time
ORDER BY open_time ASC;
```

**Expected behavior**

The result will be returned without any exceptions, just as in version 23.8

**Error message and/or stacktrace**

```
SQL Error [10] [07000]: Code: 10. DB::Exception: Not found column toFloat64(argMax(__table2.close_price, __table2.open_time)) in block. There are only columns: toDateTime64(toStartOfInterval(__table2.open_time, _CAST(1_IntervalHour, 'IntervalHour'_String)), 3_UInt8), argMin(__table2.open_price, __table2.open_time), argMax(__table2.close_price, __table2.open_time), toFloat64(argMin(__table2.open_price, __table2.open_time)). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.5.3.5 (official build))
```

**Additional context**

The same query work  like a charm in versions 23.8 - 24.2

### PR DESCRIPTION
**Pull request by antaljanosbenjamin**
Fixes #65389

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix queries with unused interpolation with the new analyzer.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit c53b746af82b22298a926e90e79f32d33f8cf9aa with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75173/c53b746af82b22298a926e90e79f32d33f8cf9aa/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/d99795b7636b6542a860ef2144283943d9f882f8/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/QueryNode.cpp [hunk 1]
```diff
@@ -86,26 +87,23 @@ void QueryNode::removeUnusedProjectionColumns(const std::unordered_set<std::stri
...
+
+        auto & interpolate_node = getInterpolate();
+        auto & interpolate_list_nodes = interpolate_node->as<ListNode &>().getNodes();
+        std::erase_if(
+            interpolate_list_nodes,
+            [&used_projection_columns](const QueryTreeNodePtr & interpolate)
+            { return !used_projection_columns.contains(interpolate->as<InterpolateNode &>().getExpressionName()); });
+
+        if (interpolate_list_nodes.empty())
+            interpolate_node = nullptr;
```
Comment (antaljanosbenjamin) [inline src/Analyzer/QueryNode.cpp:105]: This is the actual fix. The github diff is messed up.

**Comment by antaljanosbenjamin** [comment]
Will add tests.

**Review by novikd — APPROVED** [review]
LGTM
