### PR TITLE
Fix condition not being moved to PREWHERE in case there is a row policy (version 2)

### LINKED ISSUE #69777: Conditions isn't moved to PREWHERE if a row policy presents
Example:

```
CREATE TABLE tbl1(a Int32, b Int32) ENGINE=MergeTree ORDER BY tuple();
INSERT INTO tbl1 VALUES (1, 2);
```

A simple query 
```
EXPLAIN PLAN actions=1 SELECT * FROM tbl1 WHERE b=2;
```
moves the WHERE condition to PREWHERE:

```
    ┌─explain──────────────────────────────────────────────────────────────────────────────────────┐
 1. │ Expression ((Project names + Projection))                                                    │
 2. │ Actions: INPUT : 0 -> __table1.a Int32 : 0                                                   │
 3. │          INPUT : 1 -> __table1.b Int32 : 1                                                   │
 4. │          ALIAS __table1.a :: 0 -> a Int32 : 2                                                │
 5. │          ALIAS __table1.b :: 1 -> b Int32 : 0                                                │
 6. │ Positions: 2 0                                                                               │
 7. │   Expression                                                                                 │
 8. │   Actions: INPUT : 0 -> a Int32 : 0                                                          │
 9. │            INPUT : 1 -> b Int32 : 1                                                          │
10. │            ALIAS a :: 0 -> __table1.a Int32 : 2                                              │
11. │            ALIAS b :: 1 -> __table1.b Int32 : 0                                              │
12. │   Positions: 2 0                                                                             │
13. │     ReadFromMergeTree (default.tbl1)                                                         │
14. │     ReadType: Default                                                                        │
15. │     Parts: 1                                                                                 │
16. │     Granules: 1                                                                              │
17. │     Prewhere info                                                                            │
18. │     Need filter: 1                                                                           │
19. │       Prewhere filter                                                                        │
20. │       Prewhere filter column: equals(__table1.b, 2_UInt8) (removed)                          │
21. │       Actions: INPUT : 0 -> b Int32 : 0                                                      │
22. │                COLUMN Const(UInt8) -> 2_UInt8 UInt8 : 1                                      │
23. │                FUNCTION equals(b : 0, 2_UInt8 :: 1) -> equals(__table1.b, 2_UInt8) UInt8 : 2 │
24. │       Positions: 0 2                                                                         │
    └──────────────────────────────────────────────────────────────────────────────────────────────┘
```

However if there is another condition inside a row policy:
```
CREATE ROW POLICY pol1 ON tbl1 USING a=1 TO CURRENT_USER;
EXPLAIN PLAN actions=1 SELECT * FROM tbl1 WHERE b=2;
```
then it doesn't move the WHERE condition to PREWHERE:
```
    ┌─explain───────────────────────────────────────────────────────────────────────────────────┐
 1. │ Expression ((Project names + Projection))                                                 │
 2. │ Actions: INPUT : 0 -> __table1.a Int32 : 0                                                │
 3. │          INPUT : 1 -> __table1.b Int32 : 1                                                │
 4. │          ALIAS __table1.a :: 0 -> a Int32 : 2                                             │
 5. │          ALIAS __table1.b :: 1 -> b Int32 : 0                                             │
 6. │ Positions: 2 0                                                                            │
 7. │   Filter ((WHERE + Change column names to column identifiers))                            │
 8. │   Filter column: equals(__table1.b, 2_UInt8) (removed)                                    │
 9. │   Actions: INPUT : 0 -> a Int32 : 0                                                       │
10. │            INPUT : 1 -> b Int32 : 1                                                       │
11. │            COLUMN Const(UInt8) -> 2_UInt8 UInt8 : 2                                       │
12. │            ALIAS a :: 0 -> __table1.a Int32 : 3                                           │
13. │            ALIAS b : 1 -> __table1.b Int32 : 0                                            │
14. │            FUNCTION equals(b :: 1, 2_UInt8 :: 2) -> equals(__table1.b, 2_UInt8) UInt8 : 4 │
15. │   Positions: 4 3 0                                                                        │
16. │     ReadFromMergeTree (default.tbl1)                                                      │
17. │     ReadType: Default                                                                     │
18. │     Parts: 1                                                                              │
19. │     Granules: 1                                                                           │
20. │     Prewhere info                                                                         │
21. │     Need filter: 1                                                                        │
22. │       Prewhere filter                                                                     │
23. │       Prewhere filter column: equals(a, 1_UInt8) (removed)                                │
24. │       Actions: INPUT : 0 -> a Int32 : 0                                                   │
25. │                COLUMN Const(UInt8) -> 1_UInt8 UInt8 : 1                                   │
26. │                FUNCTION equals(a : 0, 1_UInt8 :: 1) -> equals(a, 1_UInt8) UInt8 : 2       │
27. │       Positions: 2 0                                                                      │
    └───────────────────────────────────────────────────────────────────────────────────────────┘
```
Since it moved to PREWHERE the condition from the row policy condition it looks like moving the row policy's condition to PREWHERE somehow prevents ClickHouse from moving the WHERE condition to PREWHERE.

### LINKED ISSUE #83748: Analyzer: row policy may disable optimize_move_to_prewhere
### Company or project name

_No response_

### Describe the situation

In some cases for tables which have row policy attached, the  automatic movements of where condition to prewhere stopped to work leading to significant query speed degradation when upgrade 23.8 -> 24.8 

### Which ClickHouse versions are affected?

24.3+

### How to reproduce

```sql
CREATE TABLE n ENGINE=MergeTree ORDER BY tuple()
AS select number, intDiv(number, 16384) as x, randomPrintableASCII(10) as s FROM numbers(1000000);

-- IRL it was custom, user-defined setting
CREATE ROW POLICY n_rp ON n USING getSetting('temporary_live_view_timeout')=1 TO ALL;

SELECT 'no PREWHERE (always true row policy there instad)'; 

explain actions=1 SELECT max(s) FROM n WHERE number > 16384*9 and x < 10 SETTINGS optimize_move_to_prewhere = 1;

SELECT max(s) FROM n WHERE number > 16384*9 and x < 10 SETTINGS optimize_move_to_prewhere = 1 FORMAT JSON;

SELECT 'there is PREWHERE (both Row level filter and Prewhere filter are in the explain):'; 

explain actions=1 SELECT max(s) FROM n WHERE number > 16384*9 and x < 10 SETTINGS optimize_move_to_prewhere = 1, query_plan_optimize_prewhere = 0, enable_analyzer = 0;

-- pay attenction at elapsed & bytes_read
SELECT max(s) FROM n WHERE number > 16384*9 and x < 10 SETTINGS optimize_move_to_prewhere = 1, query_plan_optimize_prewhere = 0, enable_analyzer = 0 FORMAT JSON;
```

https://fiddle.clickhouse.com/a571b1ea-0ba3-4453-9d26-8b75fe9e106b

### Expected performance

same as with `optimize_move_to_prewhere = 1, query_plan_optimize_prewhere = 0, enable_analyzer = 0 ` 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fixed move-to-prewhere optimization, which did not work in the presence of row policy.
Continuation of #85118.
Closes #69777.
Closes #83748.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by mkmkme** [comment]
Hey @KochetovNicolai!

Great to see this issue being fixed. Will this PR also address https://github.com/ClickHouse/ClickHouse/issues/85834 ?

**Comment by mkmkme** [comment]
>Will this PR also address https://github.com/ClickHouse/ClickHouse/issues/85834 ?

Answering myself: Yes, it seems this PR fixes that as well.

File: src/Planner/PlannerJoinTree.cpp [hunk 1]
```diff
@@ -617,7 +618,13 @@ std::optional<FilterDAGInfo> buildAdditionalFiltersIfNeeded(const StoragePtr & s
         return {};
 
     table_expression_query_info.additional_filter_ast = additional_filter_ast;
-    return buildFilterInfo(additional_filter_ast, table_expression_query_info.table_expression, planner_context);
+    auto filter_info = buildFilterInfo(additional_filter_ast, table_expression_query_info.table_expression, planner_context);
+    if (prewhere_info)
+    {
+        for (const auto * input : filter_info.actions.getInputs())
+            prewhere_info->prewhere_actions.tryRestoreColumn(input->result_name);
+    }
```
Comment (novikd) [inline src/Planner/PlannerJoinTree.cpp:626]: I still don't get why is it needed

**Review by novikd — APPROVED** [review]

File: src/Planner/PlannerJoinTree.cpp (hunk 1 above)
Comment (KochetovNicolai) [reply src/Planner/PlannerJoinTree.cpp:626]: This is because additional filters may need a column which can be removed by prewhere.

Simply saying, we don't track dependency for additional filters DAG. And I don't want to, it will make the code more complicated.

There is a test which I had to fix, so added this hack.

File: src/Processors/QueryPlan/ReadFromMergeTree.cpp [hunk 2]
```diff
@@ -1018,13 +1030,14 @@ Pipe ReadFromMergeTree::spreadMarkRangesAmongStreams(
         = settings[Setting::merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability];
     std::bernoulli_distribution fault(read_split_ranges_into_intersecting_and_non_intersecting_injection_probability);
 
+    /// TODO: Should we consider row-policy filter here?
```
Comment (KochetovNicolai) [inline src/Processors/QueryPlan/ReadFromMergeTree.cpp:1033]: Let's add row policy in the check as well.
Previously row policy was inside prewhere actions.

**Comment by rzilkha** [comment]
Thank you for this fix , can someone say if this is going to be backported also to older versions , such as 24.8 , where it seems to happen as well

**Comment by rienath** [comment]
Yes, backport to 25.8 is wip

________________________________

**Comment by rienath** [comment]
@rzilkha we decided against it. This is a performance improvement that touches a lot of files. Such large backport can introduce problems in a stable release
