### PR TITLE
Fix `clusterAllReplicas` queries with external role when it was dropped

### LINKED ISSUE #87670: Code: 492 ACCESS_ENTITY_NOT_FOUND after DROP ROLE; error persists after reconnect and any clusterAllReplicas() query fails
### Company or project name

_No response_

### Describe what's wrong

If a user has a role assigned and that role is later dropped with ON CLUSTER, any subsequent call to clusterAllReplicas() fails with:
`Code: 492. DB::Exception: ID(39466a48-025e-8da5-9655-6333b4a1de88) not found in `user directories`: While executing Remote. (ACCESS_ENTITY_NOT_FOUND) (version 25.6.1.3206 (official build))`

This happens even after disconnecting and reconnecting as the user. It is not specific to a particular dictionary/table — any clusterAllReplicas() call fails with the same 492 until the dangling role reference is cleared. Re-granting equivalent privileges does not help; reconnecting alone does not help.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Environment
	•	ClickHouse server: 25.6.1.3206
	•	Cluster topology: uses ON CLUSTER and clusterAllReplicas().
	•	Problem reproduces across new client sessions (not only in the session where the role was dropped).

-- 0) Cleanup
```
DROP USER IF EXISTS test_roles ON CLUSTER '{cluster}';
DROP ROLE IF EXISTS test_roles_dict ON CLUSTER '{cluster}';
```

-- 1) Create user and role
password: `G2PdwR`
```
CREATE USER test_roles ON CLUSTER '{cluster}'
    IDENTIFIED WITH SHA256_HASH BY '3550a1d34c8c669b3fcf72f4275c3e96a7fbfff44a27862034381cf25ed87405';
```

`CREATE ROLE test_roles_dict ON CLUSTER '{cluster}';`

-- 2) Grant privileges (both directly and via role to show it's not about SELECT)
```
GRANT ON CLUSTER '{cluster}' SELECT ON dictionaries.* TO test_roles_dict;
GRANT ON CLUSTER '{cluster}' SELECT ON dictionaries.* TO test_roles;        -- direct grant
GRANT ON CLUSTER '{cluster}' REMOTE ON *.* TO test_roles_dict;
```

-- Assign role to the user
`GRANT ON CLUSTER '{cluster}' test_roles_dict TO test_roles;`

-- 3) Connect as test_roles (Session A) and verify clusterAllReplicas works
-- (If your client can't reauth inline, open a separate terminal as test_roles.)
```
SELECT hostName() AS h, count()
FROM clusterAllReplicas('{cluster}', system.one)
GROUP BY h
SETTINGS skip_unavailable_shards = 1;
```

-- 4) From an admin session, DROP the role across the cluster
`DROP ROLE test_roles_dict ON CLUSTER '{cluster}';`

-- 5) Close Session A. Open **new** Session B as test_roles (fresh reconnect).

-- 6) Now ANY clusterAllReplicas() query fails in Session B with 492:

-- Example A: a dictionary
```
SELECT hostName() AS h, count()
FROM clusterAllReplicas('{cluster}', dictionaries.some_table)
GROUP BY h
SETTINGS skip_unavailable_shards = 1;
```

-- Example B: a neutral table still fails the same way
```
SELECT hostName() AS h, count()
FROM clusterAllReplicas('{cluster}', system.one)
GROUP BY h
SETTINGS skip_unavailable_shards = 1;
```

### Expected behavior

- After DROP ROLE, the user’s remaining privileges should apply, or an ACCESS_DENIED should be returned if insufficient.

- The system should not return ACCESS_ENTITY_NOT_FOUND (492) due to an internal dangling reference, especially after a new login.

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pufit**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix ACCESS_ENTITY_NOT_FOUND error when trying to execute clusterAllReplicas from a user with a non-existing role. Resolves #87670

### CODE REVIEW

File: src/QueryPipeline/RemoteQueryExecutor.cpp [hunk 1]
```diff
@@ -425,7 +425,7 @@ void RemoteQueryExecutor::sendQueryUnlocked(ClientInfo::QueryKind query_kind, As
             const auto & access_control = context->getAccessControl();
             for (const auto & e : user->granted_roles.getElements())
             {
-                auto names = access_control.readNames(e.ids);
+                auto names = access_control.tryReadNames(e.ids);
```
Comment (serxa) [inline src/QueryPipeline/RemoteQueryExecutor.cpp:429]: Perhaps we should add a comment here to explain what might go wrong if an exception is thrown. It does not look intuitive

**Review by serxa — APPROVED** [review]

File: src/QueryPipeline/RemoteQueryExecutor.cpp (hunk 1 above)
Comment (pufit) [reply src/QueryPipeline/RemoteQueryExecutor.cpp:429]: If an exception is thrown, then the query fails with this exception. Looks very much intuitive to me 🙂
