### PR TITLE
Fix overflow in `estimateNumRowsForMaxSizeColumn`

### LINKED ISSUE #83969: Don't set `preferred_max_column_in_block_size_bytes` too high
### Describe the bug

Easy to reproduce.

### How to reproduce

Using a UBSAN build:

```sql
CREATE TABLE t0 (c0 LowCardinality(Bool)) ENGINE = MergeTree() ORDER BY tuple();
INSERT INTO TABLE t0 (c0) VALUES (TRUE);
SELECT c0 FROM t0 SETTINGS preferred_max_column_in_block_size_bytes = 18446744073709551615;
```

### Error message and/or stacktrace

Stack trace:

```
src/Storages/MergeTree/MergeTreeBlockReadUtils.h:70:35: runtime error: 1.84467e+19 is outside the range of representable values of type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior  src/Storages/MergeTree/MergeTreeBlockReadUtils.h:70:35 
2025.07.18 10:05:33.745489 [ 2696987 ] {} <Trace> BaseDaemon: Received signal -3
2025.07.18 10:05:33.745600 [ 2697704 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.07.18 10:05:33.745620 [ 2697704 ] {} <Fatal> BaseDaemon: (version 25.8.1.233 (official build), build id: C0BABC2994B9110854CCF8B9614535D42893BE62, git hash: d028d721239690c2601197da05708c74107caa1b, architecture: x86_64) (from thread 2697689) Received signal -3
2025.07.18 10:05:33.745626 [ 2697704 ] {} <Fatal> BaseDaemon: Signal description: sanitizer trap
2025.07.18 10:05:33.745628 [ 2697704 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2025.07.18 10:05:33.745637 [ 2697704 ] {} <Fatal> BaseDaemon: Stack trace: 0x000060cea8857663 0x000060ceb00a72ab 0x000060ce9a516d30 0x000060ce9a522cf9 0x000060ceb906caee 0x000060ceb906b539 0x000060ceb906b8a4 0x000060ceba4ff371 0x000060ceb90803f4 0x000060ceba531515 0x000060ceb9989e53 0x000060ceb99baeee 0x000060ceb99a368e 0x000060ceb99a1d68 0x000060ceb99a168a 0x000060ceb99cd5c5 0x000060cea894f04f 0x000060cea8956e4a 0x000079bbedaa27f1 0x000079bbedb33c9c
2025.07.18 10:05:33.745647 [ 2697704 ] {} <Fatal> BaseDaemon: ########################################
2025.07.18 10:05:33.745728 [ 2697704 ] {} <Fatal> BaseDaemon: (version 25.8.1.233 (official build), build id: C0BABC2994B9110854CCF8B9614535D42893BE62, git hash: d028d721239690c2601197da05708c74107caa1b) (from thread 2697689) (query_id: b63e4453-8b52-4378-b0db-662c63ddb489) (query: SELECT c0 FROM t0 SETTINGS preferred_max_column_in_block_size_bytes = 18446744073709551615;) Received signal sanitizer trap (-3)
2025.07.18 10:05:33.745765 [ 2697704 ] {} <Fatal> BaseDaemon: Sanitizer trap.
2025.07.18 10:05:33.745794 [ 2697704 ] {} <Fatal> BaseDaemon: Stack trace: 0x000060cea8857663 0x000060ceb00a72ab 0x000060ce9a516d30 0x000060ce9a522cf9 0x000060ceb906caee 0x000060ceb906b539 0x000060ceb906b8a4 0x000060ceba4ff371 0x000060ceb90803f4 0x000060ceba531515 0x000060ceb9989e53 0x000060ceb99baeee 0x000060ceb99a368e 0x000060ceb99a1d68 0x000060ceb99a168a 0x000060ceb99cd5c5 0x000060cea894f04f 0x000060cea8956e4a 0x000079bbedaa27f1 0x000079bbedb33c9c
2025.07.18 10:05:33.756488 [ 2697704 ] {} <Fatal> BaseDaemon: 0.0. inlined from ci/tmp/build/./src/Common/StackTrace.cpp:389: StackTrace::tryCapture()
2025.07.18 10:05:33.756512 [ 2697704 ] {} <Fatal> BaseDaemon: 0. ci/tmp/build/./src/Common/StackTrace.cpp:61: StackTrace::StackTrace() @ 0x0000000027e7b663
2025.07.18 10:05:33.773230 [ 2697704 ] {} <Fatal> BaseDaemon: 1. ci/tmp/build/./src/Common/SignalHandlers.cpp:212: sanitizerDeathCallback() @ 0x000000002f6cb2ab
2025.07.18 10:05:33.835490 [ 2697704 ] {} <Fatal> BaseDaemon: 2. __sanitizer::Die() @ 0x0000000019b3ad30
2025.07.18 10:05:33.866215 [ 2697704 ] {} <Fatal> BaseDaemon: 3. ? @ 0x0000000019b46cf9
2025.07.18 10:05:33.887996 [ 2697704 ] {} <Fatal> BaseDaemon: 4. src/Storages/MergeTree/MergeTreeBlockReadUtils.h:70: ? @ 0x0000000038690aee
2025.07.18 10:05:33.908052 [ 2697704 ] {} <Fatal> BaseDaemon: 5. ci/tmp/build/./src/Storages/MergeTree/MergeTreeReadTask.cpp:195: DB::MergeTreeReadTask::estimateNumRows() const @ 0x000000003868f539
2025.07.18 10:05:33.928159 [ 2697704 ] {} <Fatal> BaseDaemon: 6. ci/tmp/build/./src/Storages/MergeTree/MergeTreeReadTask.cpp:218: DB::MergeTreeReadTask::read() @ 0x000000003868f8a4
2025.07.18 10:05:33.937809 [ 2697704 ] {} <Fatal> BaseDaemon: 7. src/Storages/MergeTree/MergeTreeSelectAlgorithms.h:53: DB::MergeTreeInOrderSelectAlgorithm::readFromTask(DB::MergeTreeReadTask&) @ 0x0000000039b23371
2025.07.18 10:05:33.963778 [ 2697704 ] {} <Fatal> BaseDaemon: 8. ci/tmp/build/./src/Storages/MergeTree/MergeTreeSelectProcessor.cpp:228: DB::MergeTreeSelectProcessor::read() @ 0x00000000386a43f4
2025.07.18 10:05:33.978281 [ 2697704 ] {} <Fatal> BaseDaemon: 9. ci/tmp/build/./src/Storages/MergeTree/MergeTreeSource.cpp:229: DB::MergeTreeSource::tryGenerate() @ 0x0000000039b55515
2025.07.18 10:05:33.986745 [ 2697704 ] {} <Fatal> BaseDaemon: 10. ci/tmp/build/./src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x0000000038fade53
2025.07.18 10:05:33.991627 [ 2697704 ] {} <Fatal> BaseDaemon: 11.0. inlined from ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2025.07.18 10:05:33.991649 [ 2697704 ] {} <Fatal> BaseDaemon: 11. ci/tmp/build/./src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x0000000038fdeeee
2025.07.18 10:05:34.007518 [ 2697704 ] {} <Fatal> BaseDaemon: 12. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x0000000038fc768e
2025.07.18 10:05:34.022769 [ 2697704 ] {} <Fatal> BaseDaemon: 13.0. inlined from ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:278: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*)
2025.07.18 10:05:34.022799 [ 2697704 ] {} <Fatal> BaseDaemon: 13. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:598: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000038fc5d68
2025.07.18 10:05:34.037834 [ 2697704 ] {} <Fatal> BaseDaemon: 14. ci/tmp/build/./src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000038fc568a
2025.07.18 10:05:34.048749 [ 2697704 ] {} <Fatal> BaseDaemon: 15.0. inlined from ci/tmp/build/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
2025.07.18 10:05:34.048775 [ 2697704 ] {} <Fatal> BaseDaemon: 15.1. inlined from ci/tmp/build/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:102: operator()
2025.07.18 10:05:34.048790 [ 2697704 ] {} <Fatal> BaseDaemon: 15.2. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__invoke[abi:ne190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
2025.07.18 10:05:34.048810 [ 2697704 ] {} <Fatal> BaseDaemon: 15.3. inlined from contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:ne190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
2025.07.18 10:05:34.048825 [ 2697704 ] {} <Fatal> BaseDaemon: 15.4. inlined from contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:ne190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
2025.07.18 10:05:34.048833 [ 2697704 ] {} <Fatal> BaseDaemon: 15.5. inlined from src/Common/ThreadPool.h:312: operator()
2025.07.18 10:05:34.048846 [ 2697704 ] {} <Fatal> BaseDaemon: 15.6. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__invoke[abi:ne190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
2025.07.18 10:05:34.048861 [ 2697704 ] {} <Fatal> BaseDaemon: 15.7. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:ne190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
2025.07.18 10:05:34.048871 [ 2697704 ] {} <Fatal> BaseDaemon: 15.8. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.07.18 10:05:34.048877 [ 2697704 ] {} <Fatal> BaseDaemon: 15. contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x0000000038ff15c5
2025.07.18 10:05:34.059835 [ 2697704 ] {} <Fatal> BaseDaemon: 16.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.07.18 10:05:34.059853 [ 2697704 ] {} <Fatal> BaseDaemon: 16.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.07.18 10:05:34.059937 [ 2697704 ] {} <Fatal> BaseDaemon: 16. ci/tmp/build/./src/Common/ThreadPool.cpp:809: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000027f7304f
2025.07.18 10:05:34.079451 [ 2697704 ] {} <Fatal> BaseDaemon: 17.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:ne190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
2025.07.18 10:05:34.079481 [ 2697704 ] {} <Fatal> BaseDaemon: 17.1. inlined from contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:ne190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
2025.07.18 10:05:34.079529 [ 2697704 ] {} <Fatal> BaseDaemon: 17. contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000027f7ae4a
2025.07.18 10:05:34.079583 [ 2697704 ] {} <Fatal> BaseDaemon: 18. start_thread @ 0x00000000000a27f1
2025.07.18 10:05:34.079621 [ 2697704 ] {} <Fatal> BaseDaemon: 19. __GI___clone3 @ 0x0000000000133c9c
2025.07.18 10:05:34.388389 [ 2697704 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: E3E8DF67262437637A4950E86B78733C)
2025.07.18 10:05:34.388598 [ 2697704 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, allow_reorder_prewhere_conditions = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, preferred_max_column_in_block_size_bytes = 18446744073709551615, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 120., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_execute_multiif_columnar = true, allow_drop_detached = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, allow_experimental_correlated_subqueries = true, allow_unrestricted_reads_from_keeper = true, allow_deprecated_database_ordinary = true, allow_deprecated_syntax_for_merge_tree = true, keeper_max_retries = 15, allow_get_client_http_header = true, allow_create_index_without_type = true, allow_named_collection_override_by_default = true, allow_deprecated_error_prone_window_functions = true, allow_deprecated_snowflake_conversion_functions = true, parallel_replicas_for_cluster_engines = false, allow_experimental_analyzer = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_archive_path_syntax = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_codecs = true, allow_experimental_vector_similarity_index = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_full_text_index = true, allow_experimental_live_view = true, allow_experimental_window_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_bfloat16_type = true, allow_experimental_inverted_index = true, allow_experimental_join_condition = true, allow_experimental_shared_set_join = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by nickitat**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Closes: #83969

### CODE REVIEW

**Comment by nickitat** [comment]
`Integration tests (release, 3/4)` - timeout
`Integration tests (asan, old analyzer, 4/6)` -  https://github.com/ClickHouse/ClickHouse/issues/80359
`Stateless tests (amd_tsan, s3 storage, parallel)` - https://github.com/ClickHouse/ClickHouse/issues/84247
`Stateless tests (amd_debug, parallel)` - https://github.com/ClickHouse/ClickHouse/issues/84372

File: src/Storages/MergeTree/MergeTreeBlockReadUtils.h [hunk 1]
```diff
@@ -64,6 +64,13 @@ struct MergeTreeBlockSizePredictor
     /// Predicts what number of rows should be read to exhaust byte quota per column
     size_t estimateNumRowsForMaxSizeColumn(size_t bytes_quota) const
     {
+        /// Below we calculate the following expression: `bytes_quota / max_size_per_row` and then cast its result to size_t.
+        /// The problem is that the conversion to double (`max_size_per_row` is double) can overflow size_t if `bytes_quota` is close to `SIZE_MAX`
+        /// and an attempt to convert this value back to size_t will result in undefined behavior.
+        /// ATST, if `bytes_quota` is close to `SIZE_MAX`, we can safely ignore it and assume that no limit was set.
+        if (static_cast<double>(bytes_quota) >= static_cast<double>(std::numeric_limits<size_t>::max()))
+            return 0;
```
Comment (rschu1ze) [inline src/Storages/MergeTree/MergeTreeBlockReadUtils.h:72]: (I'm more in the camp of throwing an exception because the user specified such a large value probably unintentionally but returning 0 is also okay.)

**Review by rschu1ze — APPROVED** [review]

**Comment by rschu1ze** [comment]
Oops, I saw @yariks5s is already assigned 😄

**Comment by yariks5s** [comment]
No problem, I was also going to approve it🙂
