### PR TITLE
Fix recursive static var initialization in ThreadFuzzer

### LINKED ISSUE #82091: Recursive static var initialization in ThreadFuzzer
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=82074&sha=1e74b62b9b55f88621e52557ea0c2527851bf711&name_0=PR&name_1=Stress%20test%20%28amd_debug%29

```
2025-06-18 00:29:47 #3  0x0000555600418546 in abort_message (format=0x5555e0eac0ac "__cxa_guard_acquire detected recursive initialization: do you have a function-local static variable whose initialization depends on that function?") at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxxabi/src/abort_message.cpp:78
2025-06-18 00:29:47 No locals.
2025-06-18 00:29:47 #4  0x0000555600437e6d in __cxxabiv1::(anonymous namespace)::InitByteGlobalMutex<__cxxabiv1::(anonymous namespace)::LibcppMutex, __cxxabiv1::(anonymous namespace)::LibcppCondVar, __cxxabiv1::(anonymous namespace)::GlobalStatic<__cxxabiv1::(anonymous namespace)::LibcppMutex>::instance, __cxxabiv1::(anonymous namespace)::GlobalStatic<__cxxabiv1::(anonymous namespace)::LibcppCondVar>::instance, &__cxxabiv1::(anonymous namespace)::PlatformThreadID>::acquire (this=<optimized out>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxxabi/src/cxa_guard_impl.h:331
2025-06-18 00:29:47         g = {calling_func_ = 0x5555e0b59d46 "__cxa_guard_acquire"}
2025-06-18 00:29:47 #5  __cxxabiv1::(anonymous namespace)::GuardObject<__cxxabiv1::(anonymous namespace)::InitByteGlobalMutex<__cxxabiv1::(anonymous namespace)::LibcppMutex, __cxxabiv1::(anonymous namespace)::LibcppCondVar, __cxxabiv1::(anonymous namespace)::GlobalStatic<__cxxabiv1::(anonymous namespace)::LibcppMutex>::instance, __cxxabiv1::(anonymous namespace)::GlobalStatic<__cxxabiv1::(anonymous namespace)::LibcppCondVar>::instance, &__cxxabiv1::(anonymous namespace)::PlatformThreadID> >::cxa_guard_acquire (this=<optimized out>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxxabi/src/cxa_guard_impl.h:590
2025-06-18 00:29:47 No locals.
2025-06-18 00:29:47 #6  __cxa_guard_acquire (raw_guard_object=0x55560135f880 <guard variable for DB::ThreadFuzzer::instance()::res>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxxabi/src/cxa_guard.cpp:39
2025-06-18 00:29:47         imp = {guard_byte = {guard_byte = {b_ = 0x55560135f880 <guard variable for DB::ThreadFuzzer::instance()::res> ""}}, init_byte = {init_byte_address = 0x55560135f881 <guard variable for DB::ThreadFuzzer::instance()::res+1> "\006", thread_id_address = 0x55560135f884 <guard variable for DB::ThreadFuzzer::instance()::res+4>, has_thread_id_support = true, current_thread_id = {value = 2718, is_init = true}}}
2025-06-18 00:29:47 #7  0x00005555f054f684 in DB::ThreadFuzzer::instance () at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.h:50
2025-06-18 00:29:47 No locals.
2025-06-18 00:29:47 #8  DB::ThreadFuzzer::signalHandler () at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.cpp:276
2025-06-18 00:29:47         _allocations_flag_prev_val274 = false
2025-06-18 00:29:47         scope_exit274 = {static is_nullable = <optimized out>, function = {_allocations_flag_prev_val274 = @0x7ffdea3f5627}}
2025-06-18 00:29:47         saved_errno = 2
2025-06-18 00:29:47         fuzzer = <optimized out>
2025-06-18 00:29:47 #9  <signal handler called>
2025-06-18 00:29:47 No symbol table info available.
2025-06-18 00:29:47 #10 0x00007f38781fdd7b in setitimer () from /lib/x86_64-linux-gnu/libc.so.6
2025-06-18 00:29:47 No symbol table info available.
2025-06-18 00:29:47 #11 0x00005555f054ef4b in DB::ThreadFuzzer::setup (this=this@entry=0x55560135f848 <DB::ThreadFuzzer::instance()::res>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.cpp:310
2025-06-18 00:29:47         timer_precision = <optimized out>
2025-06-18 00:29:47         sa = {__sigaction_handler = {sa_handler = 0x5555f054f520 <DB::ThreadFuzzer::signalHandler(int)>, sa_sigaction = 0x5555f054f520 <DB::ThreadFuzzer::signalHandler(int)>}, sa_mask = {__val = {67108864, 0 <repeats 15 times>}}, sa_flags = 268435456, sa_restorer = 0x0}
2025-06-18 00:29:47         timer = {it_interval = {tv_sec = 0, tv_usec = 1000}, it_value = {tv_sec = 0, tv_usec = 1000}}
2025-06-18 00:29:47         interval = {tv_sec = <optimized out>, tv_usec = 139880510250363}
2025-06-18 00:29:47 #12 0x00005555f054e1c1 in DB::ThreadFuzzer::ThreadFuzzer (this=0x55560135f848 <DB::ThreadFuzzer::instance()::res>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.cpp:56
2025-06-18 00:29:47 No locals.
2025-06-18 00:29:47 #13 0x00005555f07943f5 in DB::ThreadFuzzer::instance () at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.h:50
2025-06-18 00:29:47 No locals.
```

### PR DESCRIPTION
**Pull request by azat**
CI found [1]:

    0x00007f59e28479fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
    0  0x00007f59e28479fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
    1  0x00007f59e27f3476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    2  0x00007f59e27d97f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
    3  0x0000559301190806 in abort_message (format=0x5592dd4fa28e "__cxa_guard_acquire detected recursive initialization: do you have a function-local static variable whose initialization depends on that function?") at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxxabi/src/abort_message.cpp:78
    ...
    8  DB::ThreadFuzzer::signalHandler () at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.cpp:276
    9  <signal handler called>
    10 0x00007f59e288dd7b in setitimer () from /lib/x86_64-linux-gnu/libc.so.6
    11 0x00005592ee025a2b in DB::ThreadFuzzer::setup (this=this@entry=0x559302365048 <DB::ThreadFuzzer::instance()::res>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.cpp:310
    12 0x00005592ee024c61 in DB::ThreadFuzzer::ThreadFuzzer (this=0x559302365048 <DB::ThreadFuzzer::instance()::res>) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.cpp:56
    13 0x00005592ee29aeeb in DB::ThreadFuzzer::instance () at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Common/ThreadFuzzer.h:50
    14 DB::Server::main (this=0x7ffc3e7f5bd8) at /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/programs/server/Server.cpp:1079

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84098&sha=afe784755359c3c8e9b0835aa9187b88dd890013&name_0=PR&name_1=Stress%20test%20%28amd_debug%29

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Fixes: https://github.com/ClickHouse/ClickHouse/issues/82091

### CODE REVIEW

File: src/Common/ThreadFuzzer.cpp [hunk 1]
```diff
@@ -52,8 +52,6 @@ namespace ErrorCodes
 ThreadFuzzer::ThreadFuzzer()
 {
     initConfiguration();
```
Comment (nickitat) [inline src/Common/ThreadFuzzer.cpp:54]: Do you know if `getenv` and `get_nprocs` calls are safe in this regard?

Comment (azat) [reply src/Common/ThreadFuzzer.cpp:54]: If I understand your question correctly, then I don't think this patch changes any behavior here, it is OK to obtain it in different parts of the code if you are asking about this, since it is unlikely (and we can ignore this) will be changed.

Comment (nickitat) [reply src/Common/ThreadFuzzer.cpp:54]: Sorry for confusing you. Here is what I meant: AFAIU, the problem is that we have a call to `setitimer` inside the ctor, which in turn calls the ctor again. We are no longer doing this call here, but we still call `initConfiguration`, which calls `getenv` and `get_nprocs`. So the question is, are those functions safe from also trying to create `ThreadFuzzer` instance?

Comment (azat) [reply src/Common/ThreadFuzzer.cpp:54]: Understood. Yep, this is safe. The only problem is `setitimer` since it install timer, and it may be triggered when the we initializating the `ThreadStatus` (it is called by the kernel, not by user code)

**Review by nickitat — APPROVED** [review]

**Comment by azat** [comment]
>[Stress test (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84156&sha=4455f391ddf833a9e4518a443ca59d701b842bf5&name_0=PR&name_1=Stress%20test%20%28amd_tsan%29) — Killed by signal (in clickhouse-server.log)

- https://github.com/ClickHouse/ClickHouse/issues/81144

>[Stateless tests (amd_tsan, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84156&sha=4455f391ddf833a9e4518a443ca59d701b842bf5&name_0=PR&name_1=Stateless%20tests%20%28amd_tsan%2C%20s3%20storage%2C%20parallel%29) — Failed: 1, Passed: 7315, Skipped: 307

- `00002_log_and_exception_messages_formatting` - https://github.com/ClickHouse/ClickHouse/issues/84247

>[Stateless tests (arm_binary, sequential)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84156&sha=4455f391ddf833a9e4518a443ca59d701b842bf5&name_0=PR&name_1=Stateless%20tests%20%28arm_binary%2C%20sequential%29) — Failed: 1, Passed: 638, Skipped: 4

- `02561_null_as_default_more_formats` - https://github.com/ClickHouse/ClickHouse/issues/83756
