### PR TITLE
Always replace file names to hash in MergeTree if filesystem is case insensitive

### LINKED ISSUE #82851: Table corruption when importing many rows with JSON at once
### Company or project name

_No response_

### Describe what's wrong

When trying to import rows from a .json file with JSONEachRow format, the table can become corrupted. I tried to come up with a minimal reproducable file (randomized data file attached) and noticed that it depends on how many rows are imported at once. If I import the file piece by piece (via LIMIT), the table does not get corrupted. When the table is corrupted, a simple SELECT will fail with an exception.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Version: 25.6.2
Interface: clickhouse client

`create table events(properties JSON) engine=MergeTree order by ();`

`insert into events select properties from file('filtered.json', 'JSONEachRow', 'properties JSON');`

`select * from events;`

[filtered.json](https://github.com/user-attachments/files/20969528/filtered.json)

### Expected behavior

_No response_

### Error message and/or stacktrace

```
Code: 33. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 25.: While reading or decompressing ./store/a83/a83d3305-7735-4516-ad47-08443936280f/all_8_8_0/properties.url.dynamic_structure.cmrk2 (position: 54, typename: DB::AsynchronousReadBufferFromFileWithDescriptorsCache, compressed data header: 0b0b4756f0239cb4946e68a266424b55902500000030000000): (while reading prefix of column properties): (while reading from part ./store/a83/a83d3305-7735-4516-ad47-08443936280f/all_8_8_0/ in table default.events2 (a83d3305-7735-4516-ad47-08443936280f) located on disk default of type local, from mark 0 with max_rows_to_read = 5000, offset = 0): While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder). (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(String const&, int) @ 0x000000011025bc9c
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000108a2d0a4
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000010407231c
3. DB::Exception::Exception<unsigned long&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<String>::type>, unsigned long&, String&&) @ 0x0000000107467a60
4. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x0000000108c03e88
5. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x000000010f107f38
6. DB::CompressedReadBufferFromFile::nextImpl() @ 0x000000010f109c78
7. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0x000000010e18cd78
8. DB::MergeTreeMarksLoader::loadMarksSync() @ 0x000000010e18bf30
9. DB::MergeTreeMarksLoader::loadMarks() @ 0x000000010e18b8f8
10. DB::MergeTreeReaderStreamSingleColumn::estimateMarkRangeBytes(DB::MarkRanges const&) @ 0x000000010e1d3db0
11. DB::MergeTreeReaderStream::init() @ 0x000000010e1d20b4
12. DB::MergeTreeReaderStream::adjustRightMark(unsigned long) @ 0x000000010e1d39f8
13. DB::MergeTreeReaderWide::getStream(bool, DB::ISerialization::SubstreamPath const&, DB::MergeTreeDataPartChecksums const&, DB::NameAndTypePair const&, unsigned long, bool, unsigned long, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&) @ 0x000000010e1d71dc
14. DB::ReadBuffer* std::__function::__policy_invoker<DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::MergeTreeReaderWide::deserializePrefix(std::shared_ptr<DB::ISerialization const> const&, DB::NameAndTypePair const&, unsigned long, unsigned long, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>&, std::unordered_map<String, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>&, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>&, std::function<void (DB::ISerialization::SubstreamPath const&)>)::$_0, DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x000000010e1d8e7c
15. DB::ReadBuffer* std::__function::__policy_invoker<DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::SerializationObject::deserializeBinaryBulkStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>*) const::$_1, DB::ReadBuffer* (DB::ISerialization::SubstreamPath const&)>>(std::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) @ 0x000000010c44e034
16. DB::SerializationDynamic::deserializeDynamicStructureStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>*) @ 0x000000010c3ea82c
17. DB::SerializationDynamic::deserializeBinaryBulkStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>*) const @ 0x000000010c3e9cfc
18. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::SerializationObject::deserializeBinaryBulkStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>*) const::$_4, void ()>>(std::__function::__policy_storage const*) @ 0x000000010c44dcd8
19. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne190107]<std::__function::__default_alloc_func<DB::SerializationObject::deserializeBinaryBulkStatePrefix(DB::ISerialization::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::unordered_map<String, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>>>>*) const::$_5, void ()>>(std::__function::__policy_storage const*) @ 0x000000010c44e2a4
20. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::worker() @ 0x0000000108b91c94
21. ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000108b9b02c
22. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000108b8e6f4
23. void* std::__thread_proxy[abi:ne190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000108b995e8
24. _pthread_start @ 0x00000001901a02e4
25. thread_start @ 0x000000019019b0fc
```

### Additional context

While anonymizing the data I also noticed that changing certain JSON keys (characters but not length) will prevent the issue from arising but I could not figure out what exactly it triggers.

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Always replace file names to hash in MergeTree if filesystem is case insensitive. Previously on systems with case insensitive filesystem (like MacOS) it could lead to data corruption when several column/subcolumn names differs only in the case.

Closes https://github.com/ClickHouse/ClickHouse/issues/82851

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.507`

### CODE REVIEW

File: src/Disks/IDisk.cpp [hunk 1]
```diff
@@ -286,6 +288,22 @@ catch (Exception & e)
     throw;
 }
 
+void IDisk::checkCaseSensitivity()
+{
+    const String path = fmt::format("clickhouse_case_sensitivity_check_{}", toString(DB::UUIDHelpers::generateV4()));
```
Comment (azat) [inline src/Disks/IDisk.cpp:304]: Maybe we can just use the same `checkAccessImpl` for it, to avoid creating extra file?

File: src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp [hunk 2]
```diff
@@ -582,7 +582,7 @@ void MergeTreeDataPartWriterWide::validateColumnOfFixedSize(const NameAndTypePai
 
     String escaped_name = escapeForFileName(name);
     String stream_name;
-    if ((*storage_settings)[MergeTreeSetting::replace_long_file_name_to_hash] && escaped_name.size() > (*storage_settings)[MergeTreeSetting::max_file_name_length])
+    if (data_part_storage->isCaseInsensitive() || ((*storage_settings)[MergeTreeSetting::replace_long_file_name_to_hash] && escaped_name.size() > (*storage_settings)[MergeTreeSetting::max_file_name_length]))
```
Comment (azat) [inline src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp]: Should we update this as well?

```
$ gg 'MergeTreeSetting::replace_long_file_name_to_hash' -- :^src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp
src/Storages/MergeTree/IMergeTreeDataPart.cpp:    if (storage_settings_ && (*storage_settings_)[MergeTreeSetting::replace_long_file_name_to_hash] && stream_name.size() > (*storage_settings_)[MergeTreeSetting::max_file_name_length])
src/Storages/MergeTree/MergeTreeData.cpp:            if (settings[MergeTreeSetting::replace_long_file_name_to_hash] && full_stream_name.size() > settings[MergeTreeSetting::max_file_name_length])
src/Storages/MergeTree/MergeTreeData.cpp:                if (settings[MergeTreeSetting::replace_long_file_name_to_hash])
src/Storages/MergeTree/MutateTask.cpp:                    if ((*storage_settings)[MergeTreeSetting::replace_long_file_name_to_hash] && full_stream_to.size() > (*storage_settings)[MergeTreeSetting::max_file_name_length])
```

Also, maybe we need to add some generic method for this, instead of copy-pasting it?

File: src/Disks/DiskSelector.cpp [hunk 3]
```diff
@@ -60,14 +60,17 @@ void DiskSelector::initialize(
     }
     if (!has_default_disk)
     {
-        disks.emplace(
-            DEFAULT_DISK_NAME, std::make_shared<DiskLocal>(DEFAULT_DISK_NAME, context->getPath(), 0, context, config, config_prefix));
+        auto disk = std::make_shared<DiskLocal>(DEFAULT_DISK_NAME, context->getPath(), 0, context, config, config_prefix);
+        disk->startup(/*skip_access_check=*/ true);
```
Comment (azat) [inline src/Disks/DiskSelector.cpp]: Why we are skipping access checks here?

**Review by azat — COMMENTED** [review]
Maybe also worth to add a test?

I think we can create ext4 file system with `casefold` (hope that will not be any trickery due to containers)

```
fallocate -l200M ext4.img
mke2fs -t ext4 -O casefold ext4.img
mkdir /mnt/ext4
mount ext4.img -o loop /mnt/ext4
mkdir /mnt/ext4/case-insensitive
chattr +F /mnt/ext4/case-insensitive/
touch /mnt/ext4/case-insensitive/foo
ls /mnt/ext4/case-insensitive/FOO
```

**Comment by azat** [comment]
>Bug Fix (user-visible misbehavior in an official stable release)

Also about changelog entry, maybe it worth to mark as backward incompatible, to highlight it in logs?

File: src/Disks/IDisk.cpp (hunk 1 above)
Comment (Avogar) [reply src/Disks/IDisk.cpp:304]: Sometimes we skip check access, for example in `clickhouse-local` here:
https://github.com/ClickHouse/ClickHouse/blob/901b98d8563b873d178b2f658b1d578b4be41f21/programs/local/LocalServer.cpp#L622

But we need to check case sensitivity in `clickhouse-local` as well, because we can create `MergeTree` there.

File: src/Disks/DiskSelector.cpp (hunk 3 above)
Comment (Avogar) [reply src/Disks/DiskSelector.cpp]: We didn't run `startup` for this disk at all previously (and so access check), so I decided to keep old behaviour just in case. But I can enable it and we can see if it will break something

File: src/Disks/IDisk.cpp (hunk 1 above)
Comment (azat) [reply src/Disks/IDisk.cpp:304]: Hm, I think that was the intention to avoid creating files there, since `clickhouse-local` can be used with server config, and it is better to avoid any extra IO, especially for S3.

And if we will do case-insesitive check anyway, then, we can get `checkAccessImpl` almost for free, right?

Comment (Avogar) [reply src/Disks/IDisk.cpp:304]: > And if we will do case-insesitive check anyway, then, we can get checkAccessImpl almost for free, right?

Yes, let's try at least

**Comment by azat** [comment]
Interesting why the test fails on CI

>[2025-12-19 20:00:27] 2025-12-19 20:00:24.241000 [ 475 ] DEBUG : Command:[docker exec roottestcaseinsensitivedisk-gw0-node1-1 bash -c mount /tmp/ext4.img -o loop /mnt/ext4] (cluster.py:159, run_and_check)

Even though `--privielged` has been passed to praktika and for docker-in-docker

File: src/Disks/IDisk.cpp [hunk 4]
```diff
@@ -283,6 +290,32 @@ catch (Exception & e)
     throw;
 }
 
+bool IDisk::isCaseInsensitive()
+{
+    /// For readonly disk we cannot perform the case sensitivity check.
+    if (isReadOnly())
+        return false;
```
Comment (azat) [inline src/Disks/IDisk.cpp]: Maybe we can even `throw` here? Since I guess the method should not be called for read-only disks?

File: src/Disks/IDisk.cpp [hunk 5]
```diff
@@ -283,6 +290,32 @@ catch (Exception & e)
...
+
+    if (is_case_sensitivity_checked)
```
Comment (azat) [inline src/Disks/IDisk.cpp:300]: How it can be `false` if `IDisk::checkAccessImpl` sets it?

File: tests/integration/test_case_insensitive_disk/test.py [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+    with_zookeeper=True,
+    stay_alive=True,
+    privileged_docker=True,
+)
+
+
+@pytest.fixture(scope="module")
+def started_cluster():
+    try:
+        cluster.start()
```
Comment (azat) [inline tests/integration/test_case_insensitive_disk/test.py]: We can first prepare the filesystem with casefold, and only after this start the cluster

File: src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp (hunk 2 above)
Comment (azat) [reply src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp]: What about `MutateTask.cpp`?

File: src/Disks/IDisk.cpp (hunk 5 above)
Comment (alexey-milovidov) [reply src/Disks/IDisk.cpp:300]: The access check can be disabled.

File: tests/integration/test_case_insensitive_disk/test.py (hunk 6 above)
Comment (Avogar) [reply tests/integration/test_case_insensitive_disk/test.py]: But docker container for the node is created here in `cluster.start()`, without it `node1.exec_in_container` will not work

File: src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp (hunk 2 above)
Comment (Avogar) [reply src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp]: Done

File: src/Disks/IDisk.cpp (hunk 4 above)
Comment (Avogar) [reply src/Disks/IDisk.cpp]: Done

File: src/Disks/IDisk.cpp (hunk 5 above)
Comment (Avogar) [reply src/Disks/IDisk.cpp:300]: Exactly, we can skip access check, and in this case we will check filesystem case sensitivity lazily on first request

**Comment by Avogar** [comment]
I cannot make the test to work in the CI for some reason:
```
E   Exception: Command [docker exec roottestcaseinsensitivedisk-gw1-node1-1 bash -c mount /tmp/ext4.img -o loop /mnt/ext4] return non-zero code 32: mount: /mnt/ext4: failed to setup loop device for /tmp/ext4.img.
```

No idea how to fix it, so I will remove the test

**Comment by alexey-milovidov** [comment]
@Avogar fyi https://github.com/ClickHouse/ClickHouse/pull/93199

**Comment by azat** [comment]
About new test, I think making it sequential should help, though I also have no clue why it happens (I've tested various ways, running plain mount in parallel inside docker, running tests in parallel - and everything works locally)

```
diff --git a/ci/jobs/scripts/integration_tests_configs.py b/ci/jobs/scripts/integration_tests_configs.py
index c1e87f9db90..ab017801ed8 100644
--- a/ci/jobs/scripts/integration_tests_configs.py
+++ b/ci/jobs/scripts/integration_tests_configs.py
@@ -88,6 +88,7 @@ TEST_CONFIGS = [
     TC("test_server_overload/", True, "no idea why i'm sequential"),
     # TC("test_server_reload/", True, "no idea why i'm sequential"),
     TC("test_storage_kafka/", True, "no idea why i'm sequential"),
+    TC("test_case_insensitive_disk/", True, "mount fails otherwise"),
     TC("test_storage_kerberized_kafka/", True, "no idea why i'm sequential"),
     # TC("test_storage_s3_queue/", True, "no idea why i'm sequential"),
     # TC("test_system_flush_logs/", True, "no idea why i'm sequential"),
```

**Comment by Avogar** [comment]
> I think making it sequential should help

Let's try

**Comment by Avogar** [comment]
Doesn't help, test still fails

File: src/Disks/IDisk.cpp (hunk 5 above)
Comment (azat) [reply src/Disks/IDisk.cpp:300]: Well also need this to support `DiskObjectStorage` AFAICS (they do not call `checkAccessImpl`, but unlikely there is some object storage that is case insensitive)

**Review by azat — APPROVED** [review]
We can add test later I guess

**Comment by Avogar** [comment]
Interesting that the test passes for some integration tests runs:
`tsan` - https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86559&sha=ab846d3cf5cbfbd23c5754888d3a707a2ba69f34&name_0=PR&name_1=Integration+tests+%28amd_tsan%2C+1%2F6%29

`arm binary` - https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=86559&sha=ab846d3cf5cbfbd23c5754888d3a707a2ba69f34&name_0=PR&name_1=Integration+tests+%28arm_binary%2C+distributed+plan%2C+1%2F4%29
