### PR TITLE
Functions `hasToken*` were totally wrong. Add a test for #43358

### LINKED ISSUE #43358: Function hasToken return incorrect result
**Describe the unexpected behaviour**
Function `hasToken` may return wrong result in some cases.

**How to reproduce**
See: [fiddle](https://fiddle.clickhouse.com/781c4a16-0531-4afd-b6ce-1a0b41e62abf)

**Expected behavior**
In the above case, `hasToken` should return 0.

**Additional context**
When the search text size  >= min_haystack_size_for_algorithm(default 20000), function `hasToken` use Volnitsky algorithm, with a normal fallback token searcher, these may lead to wrong result sometimes. 
Since function `hasToken` treats `ColumnString` as a whole text, so the bug is easily to be reproduced on a normal String column.
Here are some cases I met：
```
:) SELECT path FROM test WHERE  hasToken(path, 'quota');

SELECT path
FROM test
WHERE hasToken(path, 'quota')

Query id: 4630e82c-bcf8-48b9-93e1-2927ac155023

┌─path───────────────┐
│ /api/crm/podsquota │
└────────────────────┘

1 rows in set. Elapsed: 0.090 sec. Processed 851.63 thousand rows, 19.91 MB (9.47 million rows/s., 221.49 MB/s.)

:) set preferred_block_size_bytes = 10000;

SET preferred_block_size_bytes = 10000

Query id: a86af3f8-f046-4e9f-ae77-b9cfdae83422

Ok.

0 rows in set. Elapsed: 0.003 sec.

:) SELECT path FROM test WHERE  hasToken(path, 'quota');

SELECT path
FROM test
WHERE hasToken(path, 'quota')

Query id: 87d4c33c-a8fd-4061-b230-141a42ba1935

┌─path───────────────┐
│ /api/crm/podsquota │
└────────────────────┘
┌─path───────────────┐
│ /api/crm/podsquota │
└────────────────────┘

2 rows in set. Elapsed: 0.081 sec. Processed 851.63 thousand rows, 19.91 MB (10.45 million rows/s., 244.41 MB/s.)

:) set preferred_block_size_bytes = 100000000;

SET preferred_block_size_bytes = 100000000

Query id: f5377329-20b4-4aba-88f8-61fd59c581b0

Ok.

0 rows in set. Elapsed: 0.003 sec.

:) SELECT path FROM test WHERE  hasToken(path, 'quota');

SELECT path
FROM test
WHERE hasToken(path, 'quota')

Query id: bdd9fc6a-6d44-4c8e-bb8a-10f491eb4229

Ok.

0 rows in set. Elapsed: 0.076 sec. Processed 851.63 thousand rows, 19.91 MB (11.24 million rows/s., 262.86 MB/s.)
```

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
The functions `hasToken`, `hasTokenCaseInsensitive`, `hasTokenOrNull`, `hasTokenCaseInsensitiveOrNull` were wrong. This closes #43358.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
This is an automated comment for commit 940cf69ce436107415c3990088738b83dfb201c7 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51378/940cf69ce436107415c3990088738b83dfb201c7/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

File: src/Functions/HasTokenImpl.h [hunk 1]
```diff
@@ -67,21 +68,31 @@ struct HasTokenImpl
         /// We will search for the next occurrence in all rows at once.
         while (pos < end && end != (pos = searcher.search(pos, end - pos)))
         {
-            /// Let's determine which index it refers to.
-            while (begin + haystack_offsets[i] <= pos)
+            /// The found substring is a token
+            if ((pos == begin || isTokenSeparator(pos[-1]))
```
Comment (alexey-milovidov) [inline src/Functions/HasTokenImpl.h:72]: Ten lines of code instead of a complex C++ template.
