### PR TITLE
Compress logs and profile events in the native protocol

### LINKED ISSUE #82533: Compress logs and profile events in the native protocol
### Company or project name

ClickHouse

### Describe the situation

On clusters with 100+ replicas, profile events take 1..10 MB/sec, and the progress bar is sluggish on slow Internet connections.

### Which ClickHouse versions are affected?

.

### How to reproduce

.

### Expected performance

Introduce new `DBMS_TCP_PROTOCOL_VERSION` and compress it if the client is new enough.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexey-milovidov**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Compress logs and profile events in the native protocol. On clusters with 100+ replicas, uncompressed profile events take 1..10 MB/sec, and the progress bar is sluggish on slow Internet connections. This closes #82533.

### CODE REVIEW

File: src/Core/ProtocolDefines.h [hunk 1]
```diff
@@ -112,12 +112,14 @@ static constexpr auto DBMS_MIN_REVISON_WITH_PARALLEL_BLOCK_MARSHALLING = 54478;
 
 static constexpr auto DBMS_MIN_REVISION_WITH_VERSIONED_CLUSTER_FUNCTION_PROTOCOL = 54479;
 
+static constexpr auto DBMS_MIN_REVISION_WITH_COMPRESSED_LOGS_PROFILE_EVENTS = 54480;
```
Comment (azat) [inline src/Core/ProtocolDefines.h]: Maybe `TableColumns` also should be compressed (https://github.com/ClickHouse/ClickHouse/issues/75719)?

Comment (alexey-milovidov) [reply src/Core/ProtocolDefines.h]: Added.

File: src/Client/Connection.cpp [hunk 2]
```diff
@@ -1422,23 +1418,27 @@ Block Connection::receiveProfileEvents()
 
 void Connection::initInputBuffers()
```
Comment (azat) [inline src/Client/Connection.cpp:1430]: Looks redundant now

File: src/Storages/StorageReplicatedMergeTree.cpp [hunk 3]
```diff
@@ -993,7 +993,7 @@ bool StorageReplicatedMergeTree::createTableIfNotExistsAttempt(const StorageMeta
 
         ops.emplace_back(zkutil::makeCreateRequest(zookeeper_path + "/metadata", metadata_str,
             zkutil::CreateMode::Persistent));
-        ops.emplace_back(zkutil::makeCreateRequest(zookeeper_path + "/columns", metadata_snapshot->getColumns().toString(),
+        ops.emplace_back(zkutil::makeCreateRequest(zookeeper_path + "/columns", metadata_snapshot->getColumns().toString(true),
```
Comment (azat) [inline src/Storages/StorageReplicatedMergeTree.cpp:996]: Likely we need to fix SMT

File: src/Core/ProtocolDefines.h [hunk 4]
```diff
@@ -112,12 +112,14 @@ static constexpr auto DBMS_MIN_REVISON_WITH_PARALLEL_BLOCK_MARSHALLING = 54478;
 
 static constexpr auto DBMS_MIN_REVISION_WITH_VERSIONED_CLUSTER_FUNCTION_PROTOCOL = 54479;
 
+static constexpr auto DBMS_MIN_REVISION_WITH_COMPRESSED_LOGS_PROFILE_EVENTS_COLUMNS = 54480;
```
Comment (azat) [inline src/Core/ProtocolDefines.h:115]: We may also want to add a test for this, i.e. expose revision as a client argument, run with older revision, run with newer and check that at least we have less bytes send/receive over network.

**Comment by azat** [comment]
With this patch it is 2.6 less for columns descriptions for `system.metric_log`

```
$ chc --print-profile-events -q 'insert into system.metric_log (event_date) values (today())' |& grep InterfaceNative
[localhost] 2025.06.25 12:07:19 [ 0 ] InterfaceNativeSendBytes: 66433 (increment)
[localhost] 2025.06.25 12:07:19 [ 0 ] InterfaceNativeReceiveBytes: 43 (increment)
[localhost] 2025.06.25 12:07:19 [ 0 ] InterfaceNativeSendBytes: 1613 (increment)
```

But, it is still bigger then I was expecting, any ideas?

```
$ chc "select name, type from system.columns where table = 'metric_log'" | wc -c
63711
$ chc "select name, type from system.columns where table = 'metric_log'" | zstd -c | wc -c
9332
$ chc "select name, type from system.columns where table = 'metric_log'" | lz4 -c | wc -c
14939 # I was expecting something near this value
```

**Comment by alexey-milovidov** [comment]
```
$ chc "select name, type from system.columns where table = 'metric_log'" | wc -c
108331
$ chc "select name, type from system.columns where table = 'metric_log'" | clickhouse-compressor | wc -c
16773
```

But we send the list of columns twice - one for `TableColumns`, another for the sample `Block`.
The first was added a long time ago to accommodate DEFAULT expressions, and this is why we have redundancy.

**Comment by tavplubix** [comment]
It has broken `00133_long_shard_memory_tracker_and_exception_safety` in a funny way: https://pastila.nl/?000e37bf/144955095e30e01ef848763cff03aad9#9412lNwFrsq4e56l90JScQ==

If fails to allocate memory for `CompressedWriteBuffer`, and therefore fails to send the original exception to the client, and the client exits with `ATTEMPT_TO_READ_AFTER_EOF` instead of `MEMORY_LIMIT_EXCEEDED`

According to [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMDEzM19sb25nX3NoYXJkX21lbW9yeV90cmFja2VyX2FuZF9leGNlcHRpb25fc2FmZXR5JyBBUyBuYW1lX3N1YnN0ciwKICAgIDkwIEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJywgJ0ludGVncmF0aW9uIHRlc3RzIChhc2FuKSBbMS8zXScsICdTdGF0ZWxlc3MgdGVzdHMgKHRzYW4pIFsxLzNdJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=), it's currently the most flaky test in master
