### PR TITLE
Avoid possible abort() in CapnProto on exception descruction

### LINKED ISSUE #30706: abort() called in capnproto on exception destruction
https://clickhouse-test-reports.s3.yandex.net/0/b549bddc11081641ca5523308406a587c7fb5753/stress_test_(memory).html#fail1

Possibly the ExceptionImpl was destroyed on a different thread than created it:
https://github.com/capnproto/capnproto/blob/fe30e978ae789c704fb7622173acce4c6878125b/c%2B%2B/src/kj/exception.c%2B%2B#L892-L903

```
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:58:59.588711 [ 23555 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:58:59.589082 [ 23555 ] {} <Fatal> BaseDaemon: (version 21.11.1.8564 (official build), build id: 2F76347EDBC8AF49AE8D4D8182535717573C3A2D) (from thread 2248) (query_id: 0d2f01e9-1719-4293-ba86-cad365fe6dc1) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:58:59.592848 [ 23555 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:58:59.607520 [ 23555 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f6c16a5318b 0x7f6c16a32859 0x42481b2f 0x4ad578b2 0x4aad94ab 0x36965e46 0x36965928 0x36945759 0x30d5e96d 0x369892fe 0x34f0c890 0x34f08cf2 0x313b60f5 0x313c7503 0x31359c0a 0x3684ca78 0x3680384d 0x3684418c 0x41969e7c 0x4196b1b2 0x41d9ee12 0x41d9a469 0x41d96816 0x7f6c16c08609 0x7f6c16b2f293
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:58:59.630359 [ 23555 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:58:59.633964 [ 23555 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.169897 [ 23604 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.170555 [ 23604 ] {} <Fatal> BaseDaemon: (version 21.11.1.8564 (official build), build id: 2F76347EDBC8AF49AE8D4D8182535717573C3A2D) (from thread 6551) (query_id: 11feb6f7-81c1-447c-8c1a-e93899541657) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.170652 [ 23604 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.170788 [ 23604 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f6c16a5318b 0x7f6c16a32859 0x42481b2f 0x4ad578b2 0x4aad94ab 0x36965e46 0x36965928 0x36945759 0x30d5e96d 0x369892fe 0x34f0c890 0x34f08cf2 0x313b60f5 0x313c7503 0x31359c0a 0x3684ca78 0x3680384d 0x3684418c 0x41969e7c 0x4196b1b2 0x41d9ee12 0x41d9a469 0x41d96816 0x7f6c16c08609 0x7f6c16b2f293
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.179384 [ 23604 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.179540 [ 23604 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.824788 [ 23642 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.824905 [ 23642 ] {} <Fatal> BaseDaemon: (version 21.11.1.8564 (official build), build id: 2F76347EDBC8AF49AE8D4D8182535717573C3A2D) (from thread 10640) (query_id: 745f5bcc-ebda-4adf-9eb6-1110ada31510) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.825602 [ 23642 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.825747 [ 23642 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f6c16a5318b 0x7f6c16a32859 0x42481b2f 0x4ad578b2 0x4aad94ab 0x36965e46 0x36965928 0x36945759 0x30d5e96d 0x369892fe 0x34f0c890 0x34f08cf2 0x313b60f5 0x313c7503 0x31359c0a 0x3684ca78 0x3680384d 0x3684418c 0x41969e7c 0x4196b1b2 0x41d9ee12 0x41d9a469 0x41d96816 0x7f6c16c08609 0x7f6c16b2f293
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.830180 [ 23642 ] {} <Fatal> BaseDaemon: 4. raise @ 0x4618b in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.830332 [ 23642 ] {} <Fatal> BaseDaemon: 5. abort @ 0x25859 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.934373 [ 23604 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/capnproto/c++/src/kj/exception.c++:894: kj::ExceptionImpl::~ExceptionImpl() @ 0x42481b2f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:00.946600 [ 23642 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/capnproto/c++/src/kj/exception.c++:894: kj::ExceptionImpl::~ExceptionImpl() @ 0x42481b2f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.024574 [ 23555 ] {} <Fatal> BaseDaemon: 6. ./obj-x86_64-linux-gnu/../contrib/capnproto/c++/src/kj/exception.c++:894: kj::ExceptionImpl::~ExceptionImpl() @ 0x42481b2f in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.027453 [ 23642 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_exception.cpp:0: __cxa_decrement_exception_refcount @ 0x4ad578b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.034699 [ 23555 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_exception.cpp:0: __cxa_decrement_exception_refcount @ 0x4ad578b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.045406 [ 23604 ] {} <Fatal> BaseDaemon: 7. ./obj-x86_64-linux-gnu/../contrib/libcxxabi/src/cxa_exception.cpp:0: __cxa_decrement_exception_refcount @ 0x4ad578b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.054604 [ 23642 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/src/support/runtime/exception_pointer_cxxabi.ipp:18: std::exception_ptr::~exception_ptr() @ 0x4aad94ab in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.054605 [ 23555 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/src/support/runtime/exception_pointer_cxxabi.ipp:18: std::exception_ptr::~exception_ptr() @ 0x4aad94ab in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:01.055338 [ 23604 ] {} <Fatal> BaseDaemon: 8. ./obj-x86_64-linux-gnu/../contrib/libcxx/src/support/runtime/exception_pointer_cxxabi.ipp:18: std::exception_ptr::~exception_ptr() @ 0x4aad94ab in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.241839 [ 23642 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2191: ~__policy_func
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.241840 [ 23555 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2191: ~__policy_func
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.248759 [ 23642 ] {} <Fatal> BaseDaemon: 9.2. inlined from ../contrib/libcxx/include/functional:2547: ~function
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.248759 [ 23555 ] {} <Fatal> BaseDaemon: 9.2. inlined from ../contrib/libcxx/include/functional:2547: ~function
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.248865 [ 23642 ] {} <Fatal> BaseDaemon: 9. ../src/Processors/Executors/ExecutingGraph.h:70: DB::ExecutingGraph::Node::~Node() @ 0x36965e46 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.248874 [ 23555 ] {} <Fatal> BaseDaemon: 9. ../src/Processors/Executors/ExecutingGraph.h:70: DB::ExecutingGraph::Node::~Node() @ 0x36965e46 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.333433 [ 23604 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:2191: ~__policy_func
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.333542 [ 23604 ] {} <Fatal> BaseDaemon: 9.2. inlined from ../contrib/libcxx/include/functional:2547: ~function
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.333608 [ 23604 ] {} <Fatal> BaseDaemon: 9. ../src/Processors/Executors/ExecutingGraph.h:70: DB::ExecutingGraph::Node::~Node() @ 0x36965e46 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.493883 [ 23642 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::ExecutingGraph::Node>::operator()(DB::ExecutingGraph::Node*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.494056 [ 23642 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >::reset(DB::ExecutingGraph::Node*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.494440 [ 23555 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::ExecutingGraph::Node>::operator()(DB::ExecutingGraph::Node*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.494631 [ 23555 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >::reset(DB::ExecutingGraph::Node*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.495844 [ 23642 ] {} <Fatal> BaseDaemon: 10.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.495982 [ 23555 ] {} <Fatal> BaseDaemon: 10.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.496343 [ 23642 ] {} <Fatal> BaseDaemon: 10.4. inlined from ../contrib/libcxx/include/memory:891: std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >::destroy(std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.496428 [ 23555 ] {} <Fatal> BaseDaemon: 10.4. inlined from ../contrib/libcxx/include/memory:891: std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >::destroy(std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.497470 [ 23642 ] {} <Fatal> BaseDaemon: 10.5. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:539: void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::__destroy<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >&, std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.497698 [ 23555 ] {} <Fatal> BaseDaemon: 10.5. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:539: void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::__destroy<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >&, std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.504202 [ 23642 ] {} <Fatal> BaseDaemon: 10.6. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::destroy<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >(std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >&, std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.505618 [ 23555 ] {} <Fatal> BaseDaemon: 10.6. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::destroy<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >(std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >&, std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.506749 [ 23642 ] {} <Fatal> BaseDaemon: 10.7. inlined from ../contrib/libcxx/include/vector:428: std::__1::__vector_base<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::__destruct_at_end(std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.507113 [ 23642 ] {} <Fatal> BaseDaemon: 10.8. inlined from ../contrib/libcxx/include/vector:371: std::__1::__vector_base<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::clear()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.510898 [ 23642 ] {} <Fatal> BaseDaemon: 10.9. inlined from ../contrib/libcxx/include/vector:465: ~__vector_base
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.511412 [ 23642 ] {} <Fatal> BaseDaemon: 10.10. inlined from ../contrib/libcxx/include/vector:557: ~vector
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.511522 [ 23642 ] {} <Fatal> BaseDaemon: 10. ../src/Processors/Executors/ExecutingGraph.h:10: DB::ExecutingGraph::~ExecutingGraph() @ 0x36965928 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.511596 [ 23555 ] {} <Fatal> BaseDaemon: 10.7. inlined from ../contrib/libcxx/include/vector:428: std::__1::__vector_base<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::__destruct_at_end(std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.511856 [ 23555 ] {} <Fatal> BaseDaemon: 10.8. inlined from ../contrib/libcxx/include/vector:371: std::__1::__vector_base<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::clear()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.511972 [ 23555 ] {} <Fatal> BaseDaemon: 10.9. inlined from ../contrib/libcxx/include/vector:465: ~__vector_base
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.512073 [ 23555 ] {} <Fatal> BaseDaemon: 10.10. inlined from ../contrib/libcxx/include/vector:557: ~vector
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.512201 [ 23555 ] {} <Fatal> BaseDaemon: 10. ../src/Processors/Executors/ExecutingGraph.h:10: DB::ExecutingGraph::~ExecutingGraph() @ 0x36965928 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.562183 [ 23604 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::ExecutingGraph::Node>::operator()(DB::ExecutingGraph::Node*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.562378 [ 23604 ] {} <Fatal> BaseDaemon: 10.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >::reset(DB::ExecutingGraph::Node*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.562511 [ 23604 ] {} <Fatal> BaseDaemon: 10.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.562645 [ 23604 ] {} <Fatal> BaseDaemon: 10.4. inlined from ../contrib/libcxx/include/memory:891: std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >::destroy(std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.562817 [ 23604 ] {} <Fatal> BaseDaemon: 10.5. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:539: void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::__destroy<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >&, std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.567325 [ 23604 ] {} <Fatal> BaseDaemon: 10.6. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::destroy<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >(std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > >&, std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.568208 [ 23604 ] {} <Fatal> BaseDaemon: 10.7. inlined from ../contrib/libcxx/include/vector:428: std::__1::__vector_base<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::__destruct_at_end(std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.568401 [ 23604 ] {} <Fatal> BaseDaemon: 10.8. inlined from ../contrib/libcxx/include/vector:371: std::__1::__vector_base<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> >, std::__1::allocator<std::__1::unique_ptr<DB::ExecutingGraph::Node, std::__1::default_delete<DB::ExecutingGraph::Node> > > >::clear()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.568496 [ 23604 ] {} <Fatal> BaseDaemon: 10.9. inlined from ../contrib/libcxx/include/vector:465: ~__vector_base
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.568563 [ 23604 ] {} <Fatal> BaseDaemon: 10.10. inlined from ../contrib/libcxx/include/vector:557: ~vector
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.568624 [ 23604 ] {} <Fatal> BaseDaemon: 10. ../src/Processors/Executors/ExecutingGraph.h:10: DB::ExecutingGraph::~ExecutingGraph() @ 0x36965928 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.816970 [ 23555 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::ExecutingGraph>::operator()(DB::ExecutingGraph*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.817811 [ 23555 ] {} <Fatal> BaseDaemon: 11.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::reset(DB::ExecutingGraph*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.817927 [ 23555 ] {} <Fatal> BaseDaemon: 11.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.818021 [ 23555 ] {} <Fatal> BaseDaemon: 11. ../src/Processors/Executors/PipelineExecutor.cpp:68: DB::PipelineExecutor::~PipelineExecutor() @ 0x36945759 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.842602 [ 23642 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::ExecutingGraph>::operator()(DB::ExecutingGraph*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.842784 [ 23642 ] {} <Fatal> BaseDaemon: 11.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::reset(DB::ExecutingGraph*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.842863 [ 23642 ] {} <Fatal> BaseDaemon: 11.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.843273 [ 23642 ] {} <Fatal> BaseDaemon: 11. ../src/Processors/Executors/PipelineExecutor.cpp:68: DB::PipelineExecutor::~PipelineExecutor() @ 0x36945759 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.925960 [ 23604 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::ExecutingGraph>::operator()(DB::ExecutingGraph*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.927251 [ 23604 ] {} <Fatal> BaseDaemon: 11.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::ExecutingGraph, std::__1::default_delete<DB::ExecutingGraph> >::reset(DB::ExecutingGraph*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.927377 [ 23604 ] {} <Fatal> BaseDaemon: 11.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:02.927479 [ 23604 ] {} <Fatal> BaseDaemon: 11. ../src/Processors/Executors/PipelineExecutor.cpp:68: DB::PipelineExecutor::~PipelineExecutor() @ 0x36945759 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.712138 [ 23604 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::PipelineExecutor, std::__1::allocator<DB::PipelineExecutor> >::__on_zero_shared() @ 0x30d5e96d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.713332 [ 23555 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::PipelineExecutor, std::__1::allocator<DB::PipelineExecutor> >::__on_zero_shared() @ 0x30d5e96d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.713432 [ 23642 ] {} <Fatal> BaseDaemon: 12. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::PipelineExecutor, std::__1::allocator<DB::PipelineExecutor> >::__on_zero_shared() @ 0x30d5e96d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.900663 [ 23604 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: std::__1::__shared_weak_count::__release_shared()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.900663 [ 23555 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: std::__1::__shared_weak_count::__release_shared()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.909029 [ 23604 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../contrib/libcxx/include/memory:3212: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.909199 [ 23604 ] {} <Fatal> BaseDaemon: 13. ../src/Processors/Executors/PullingPipelineExecutor.cpp:35: DB::PullingPipelineExecutor::~PullingPipelineExecutor() @ 0x369892fe in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.916524 [ 23555 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../contrib/libcxx/include/memory:3212: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.916657 [ 23555 ] {} <Fatal> BaseDaemon: 13. ../src/Processors/Executors/PullingPipelineExecutor.cpp:35: DB::PullingPipelineExecutor::~PullingPipelineExecutor() @ 0x369892fe in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.941266 [ 23642 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: std::__1::__shared_weak_count::__release_shared()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.941402 [ 23642 ] {} <Fatal> BaseDaemon: 13.2. inlined from ../contrib/libcxx/include/memory:3212: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:03.941472 [ 23642 ] {} <Fatal> BaseDaemon: 13. ../src/Processors/Executors/PullingPipelineExecutor.cpp:35: DB::PullingPipelineExecutor::~PullingPipelineExecutor() @ 0x369892fe in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.088874 [ 23555 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::PullingPipelineExecutor>::operator()(DB::PullingPipelineExecutor*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.089131 [ 23604 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::PullingPipelineExecutor>::operator()(DB::PullingPipelineExecutor*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.089440 [ 23555 ] {} <Fatal> BaseDaemon: 14.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::PullingPipelineExecutor, std::__1::default_delete<DB::PullingPipelineExecutor> >::reset(DB::PullingPipelineExecutor*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090072 [ 23555 ] {} <Fatal> BaseDaemon: 14.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090121 [ 23642 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:0: std::__1::default_delete<DB::PullingPipelineExecutor>::operator()(DB::PullingPipelineExecutor*) const
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090161 [ 23604 ] {} <Fatal> BaseDaemon: 14.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::PullingPipelineExecutor, std::__1::default_delete<DB::PullingPipelineExecutor> >::reset(DB::PullingPipelineExecutor*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090186 [ 23555 ] {} <Fatal> BaseDaemon: 14. ../src/Storages/StorageFile.cpp:255: DB::StorageFileSource::~StorageFileSource() @ 0x34f0c890 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090276 [ 23642 ] {} <Fatal> BaseDaemon: 14.2. inlined from ../contrib/libcxx/include/memory:1658: std::__1::unique_ptr<DB::PullingPipelineExecutor, std::__1::default_delete<DB::PullingPipelineExecutor> >::reset(DB::PullingPipelineExecutor*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090351 [ 23604 ] {} <Fatal> BaseDaemon: 14.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090402 [ 23642 ] {} <Fatal> BaseDaemon: 14.3. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090453 [ 23604 ] {} <Fatal> BaseDaemon: 14. ../src/Storages/StorageFile.cpp:255: DB::StorageFileSource::~StorageFileSource() @ 0x34f0c890 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.090502 [ 23642 ] {} <Fatal> BaseDaemon: 14. ../src/Storages/StorageFile.cpp:255: DB::StorageFileSource::~StorageFileSource() @ 0x34f0c890 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:06.984084 [ 23642 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource> >::__on_zero_shared() @ 0x34f08cf2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.065670 [ 23604 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource> >::__on_zero_shared() @ 0x34f08cf2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.154022 [ 23555 ] {} <Fatal> BaseDaemon: 15. ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: std::__1::__shared_ptr_emplace<DB::StorageFileSource, std::__1::allocator<DB::StorageFileSource> >::__on_zero_shared() @ 0x34f08cf2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398014 [ 23555 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: std::__1::__shared_weak_count::__release_shared()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398032 [ 23642 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: std::__1::__shared_weak_count::__release_shared()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398032 [ 23604 ] {} <Fatal> BaseDaemon: 16.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2518: std::__1::__shared_weak_count::__release_shared()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398126 [ 23555 ] {} <Fatal> BaseDaemon: 16.2. inlined from ../contrib/libcxx/include/memory:3212: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398225 [ 23642 ] {} <Fatal> BaseDaemon: 16.2. inlined from ../contrib/libcxx/include/memory:3212: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398287 [ 23604 ] {} <Fatal> BaseDaemon: 16.2. inlined from ../contrib/libcxx/include/memory:3212: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398678 [ 23555 ] {} <Fatal> BaseDaemon: 16.3. inlined from ../contrib/libcxx/include/memory:891: std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >::destroy(std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398699 [ 23604 ] {} <Fatal> BaseDaemon: 16.3. inlined from ../contrib/libcxx/include/memory:891: std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >::destroy(std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.398704 [ 23642 ] {} <Fatal> BaseDaemon: 16.3. inlined from ../contrib/libcxx/include/memory:891: std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >::destroy(std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.399419 [ 23555 ] {} <Fatal> BaseDaemon: 16.4. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:539: void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__destroy<std::__1::shared_ptr<DB::IProcessor> >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >&, std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.399496 [ 23642 ] {} <Fatal> BaseDaemon: 16.4. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:539: void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__destroy<std::__1::shared_ptr<DB::IProcessor> >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >&, std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.399500 [ 23604 ] {} <Fatal> BaseDaemon: 16.4. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:539: void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__destroy<std::__1::shared_ptr<DB::IProcessor> >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >&, std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.400921 [ 23555 ] {} <Fatal> BaseDaemon: 16.5. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::destroy<std::__1::shared_ptr<DB::IProcessor> >(std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >&, std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.400963 [ 23642 ] {} <Fatal> BaseDaemon: 16.5. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::destroy<std::__1::shared_ptr<DB::IProcessor> >(std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >&, std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.400999 [ 23604 ] {} <Fatal> BaseDaemon: 16.5. inlined from ../contrib/libcxx/include/__memory/allocator_traits.h:487: void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::destroy<std::__1::shared_ptr<DB::IProcessor> >(std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> >&, std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.401529 [ 23604 ] {} <Fatal> BaseDaemon: 16.6. inlined from ../contrib/libcxx/include/vector:428: std::__1::__vector_base<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__destruct_at_end(std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.401535 [ 23555 ] {} <Fatal> BaseDaemon: 16.6. inlined from ../contrib/libcxx/include/vector:428: std::__1::__vector_base<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__destruct_at_end(std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.402753 [ 23642 ] {} <Fatal> BaseDaemon: 16.6. inlined from ../contrib/libcxx/include/vector:428: std::__1::__vector_base<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::__destruct_at_end(std::__1::shared_ptr<DB::IProcessor>*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.402830 [ 23555 ] {} <Fatal> BaseDaemon: 16.7. inlined from ../contrib/libcxx/include/vector:371: std::__1::__vector_base<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::clear()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.402832 [ 23604 ] {} <Fatal> BaseDaemon: 16.7. inlined from ../contrib/libcxx/include/vector:371: std::__1::__vector_base<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::clear()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.402916 [ 23642 ] {} <Fatal> BaseDaemon: 16.7. inlined from ../contrib/libcxx/include/vector:371: std::__1::__vector_base<std::__1::shared_ptr<DB::IProcessor>, std::__1::allocator<std::__1::shared_ptr<DB::IProcessor> > >::clear()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.402981 [ 23555 ] {} <Fatal> BaseDaemon: 16.8. inlined from ../contrib/libcxx/include/vector:465: ~__vector_base
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403023 [ 23604 ] {} <Fatal> BaseDaemon: 16.8. inlined from ../contrib/libcxx/include/vector:465: ~__vector_base
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403048 [ 23642 ] {} <Fatal> BaseDaemon: 16.8. inlined from ../contrib/libcxx/include/vector:465: ~__vector_base
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403099 [ 23555 ] {} <Fatal> BaseDaemon: 16.9. inlined from ../contrib/libcxx/include/vector:557: ~vector
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403115 [ 23604 ] {} <Fatal> BaseDaemon: 16.9. inlined from ../contrib/libcxx/include/vector:557: ~vector
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403135 [ 23642 ] {} <Fatal> BaseDaemon: 16.9. inlined from ../contrib/libcxx/include/vector:557: ~vector
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403202 [ 23604 ] {} <Fatal> BaseDaemon: 16. ../src/QueryPipeline/QueryPipeline.cpp:29: DB::QueryPipeline::~QueryPipeline() @ 0x313b60f5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403217 [ 23642 ] {} <Fatal> BaseDaemon: 16. ../src/QueryPipeline/QueryPipeline.cpp:29: DB::QueryPipeline::~QueryPipeline() @ 0x313b60f5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.403203 [ 23555 ] {} <Fatal> BaseDaemon: 16. ../src/QueryPipeline/QueryPipeline.cpp:29: DB::QueryPipeline::~QueryPipeline() @ 0x313b60f5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.774163 [ 23555 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/QueryPipeline/QueryPipeline.cpp:535: DB::QueryPipeline::reset() @ 0x313c7503 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.774165 [ 23642 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/QueryPipeline/QueryPipeline.cpp:535: DB::QueryPipeline::reset() @ 0x313c7503 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.830285 [ 23642 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./obj-x86_64-linux-gnu/../src/QueryPipeline/BlockIO.cpp:0: DB::BlockIO::reset()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.830516 [ 23642 ] {} <Fatal> BaseDaemon: 18. ../src/QueryPipeline/BlockIO.cpp:32: DB::BlockIO::operator=(DB::BlockIO&&) @ 0x31359c0a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.830647 [ 23555 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./obj-x86_64-linux-gnu/../src/QueryPipeline/BlockIO.cpp:0: DB::BlockIO::reset()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.830770 [ 23555 ] {} <Fatal> BaseDaemon: 18. ../src/QueryPipeline/BlockIO.cpp:32: DB::BlockIO::operator=(DB::BlockIO&&) @ 0x31359c0a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.879351 [ 23604 ] {} <Fatal> BaseDaemon: 17. ./obj-x86_64-linux-gnu/../src/QueryPipeline/QueryPipeline.cpp:535: DB::QueryPipeline::reset() @ 0x313c7503 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.923798 [ 23604 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./obj-x86_64-linux-gnu/../src/QueryPipeline/BlockIO.cpp:0: DB::BlockIO::reset()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:07.923932 [ 23604 ] {} <Fatal> BaseDaemon: 18. ../src/QueryPipeline/BlockIO.cpp:32: DB::BlockIO::operator=(DB::BlockIO&&) @ 0x31359c0a in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.377457 [ 23604 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:36: DB::QueryState::operator=(DB::QueryState&&) @ 0x3684ca78 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.377744 [ 23555 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:36: DB::QueryState::operator=(DB::QueryState&&) @ 0x3684ca78 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.388893 [ 23642 ] {} <Fatal> BaseDaemon: 19. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:36: DB::QueryState::operator=(DB::QueryState&&) @ 0x3684ca78 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.860231 [ 23642 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:100: DB::QueryState::reset()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.860289 [ 23555 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:100: DB::QueryState::reset()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.860421 [ 23642 ] {} <Fatal> BaseDaemon: 20. ../src/Server/TCPHandler.cpp:474: DB::TCPHandler::runImpl() @ 0x3680384d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.860432 [ 23555 ] {} <Fatal> BaseDaemon: 20. ../src/Server/TCPHandler.cpp:474: DB::TCPHandler::runImpl() @ 0x3680384d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.886717 [ 23604 ] {} <Fatal> BaseDaemon: 20.1. inlined from ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.h:100: DB::QueryState::reset()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:09.888054 [ 23604 ] {} <Fatal> BaseDaemon: 20. ../src/Server/TCPHandler.cpp:474: DB::TCPHandler::runImpl() @ 0x3680384d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:10.832242 [ 23555 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::run() @ 0x3684418c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:10.832352 [ 23642 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::run() @ 0x3684418c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:10.853408 [ 23604 ] {} <Fatal> BaseDaemon: 21. ./obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:0: DB::TCPHandler::run() @ 0x3684418c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:10.865865 [ 23642 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x41969e7c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:10.865865 [ 23604 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x41969e7c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:10.865865 [ 23555 ] {} <Fatal> BaseDaemon: 22. ./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x41969e7c in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.018520 [ 23604 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.018622 [ 23555 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.018646 [ 23604 ] {} <Fatal> BaseDaemon: 23.2. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.018781 [ 23604 ] {} <Fatal> BaseDaemon: 23. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x4196b1b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.018789 [ 23555 ] {} <Fatal> BaseDaemon: 23.2. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.018944 [ 23555 ] {} <Fatal> BaseDaemon: 23. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x4196b1b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.019750 [ 23642 ] {} <Fatal> BaseDaemon: 23.1. inlined from ./obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.021724 [ 23642 ] {} <Fatal> BaseDaemon: 23.2. inlined from ../contrib/libcxx/include/memory:1612: ~unique_ptr
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.021899 [ 23642 ] {} <Fatal> BaseDaemon: 23. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x4196b1b2 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.125609 [ 23555 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x41d9ee12 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.125687 [ 23642 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x41d9ee12 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.125801 [ 23604 ] {} <Fatal> BaseDaemon: 24. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:0: Poco::PooledThread::run() @ 0x41d9ee12 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.247505 [ 23642 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x41d9a469 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.248367 [ 23555 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x41d9a469 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.248367 [ 23604 ] {} <Fatal> BaseDaemon: 25. ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread.cpp:56: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x41d9a469 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.291922 [ 23642 ] {} <Fatal> BaseDaemon: 26.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::get()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.292184 [ 23642 ] {} <Fatal> BaseDaemon: 26.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.295907 [ 23642 ] {} <Fatal> BaseDaemon: 26.3. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.296005 [ 23642 ] {} <Fatal> BaseDaemon: 26. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x41d96816 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.296615 [ 23642 ] {} <Fatal> BaseDaemon: 27. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.296787 [ 23642 ] {} <Fatal> BaseDaemon: 28. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313276 [ 23604 ] {} <Fatal> BaseDaemon: 26.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::get()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313276 [ 23555 ] {} <Fatal> BaseDaemon: 26.1. inlined from ./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::get()
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313471 [ 23555 ] {} <Fatal> BaseDaemon: 26.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313471 [ 23604 ] {} <Fatal> BaseDaemon: 26.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313613 [ 23604 ] {} <Fatal> BaseDaemon: 26.3. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313613 [ 23555 ] {} <Fatal> BaseDaemon: 26.3. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313733 [ 23555 ] {} <Fatal> BaseDaemon: 26. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x41d96816 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313733 [ 23604 ] {} <Fatal> BaseDaemon: 26. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x41d96816 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.313983 [ 23555 ] {} <Fatal> BaseDaemon: 27. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.314111 [ 23604 ] {} <Fatal> BaseDaemon: 27. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.314131 [ 23555 ] {} <Fatal> BaseDaemon: 28. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:11.314246 [ 23604 ] {} <Fatal> BaseDaemon: 28. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:17.175819 [ 23555 ] {} <Fatal> BaseDaemon: Checksum of the binary: BBB923EB541850D9499393D9125CA113, integrity check passed.
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:17.195976 [ 23604 ] {} <Fatal> BaseDaemon: Checksum of the binary: BBB923EB541850D9499393D9125CA113, integrity check passed.
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:17.465336 [ 23642 ] {} <Fatal> BaseDaemon: Checksum of the binary: BBB923EB541850D9499393D9125CA113, integrity check passed.
/var/log/clickhouse-server/clickhouse-server.log.2:2021.10.26 18:59:24.007576 [ 526 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Avoid possible abort() in CapnProto on exception descruction. Closes https://github.com/ClickHouse/ClickHouse/issues/30706

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by Avogar** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/30706#issuecomment-1188167123

File: src/Processors/Formats/Impl/CapnProtoRowInputFormat.cpp [hunk 1]
```diff
@@ -264,20 +264,26 @@ bool CapnProtoRowInputFormat::readRow(MutableColumns & columns, RowReadExtension
     if (in->eof())
         return false;
 
-    auto array = readMessage();
+    try
+    {
+        auto array = readMessage();
 
 #if CAPNP_VERSION >= 7000 && CAPNP_VERSION < 8000
```
Comment (alexey-milovidov) [inline src/Processors/Formats/Impl/CapnProtoRowInputFormat.cpp:271]: We can get rid of these ifdefs because the version is fixed now.
