### PR TITLE
Do not check parent scope for group_by_use_nulls outside of subquery.

### LINKED ISSUE #64930: [LOGICAL_ERROR] group_by_use_nulls: Column identifier <> is already registered
https://s3.amazonaws.com/clickhouse-test-reports/64766/91dc50da4adede3cac06a6b5cf98d3136b75ba03/ast_fuzzer__asan_.html

```
CREATE TABLE test
ENGINE = ReplacingMergeTree
PRIMARY KEY id
AS SELECT number AS id FROM numbers(100);

SELECT id
FROM test
FINAL
GROUP BY
    GROUPING SETS ((id))
ORDER BY
    id IN (
        SELECT DISTINCT id
        FROM test
        FINAL
        LIMIT 4
    ) ASC
LIMIT 256 BY id
SETTINGS allow_experimental_analyzer = 1, group_by_use_nulls=true;
```

```
Received exception from server (version 24.5.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Column identifier __table1.id is already registered. (LOGICAL_ERROR)
```

Works fine in 24.4. Fails in 24.5 and master.

### PR DESCRIPTION
**Pull request by KochetovNicolai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix `Column identifier is already registered` error with `group_by_use_nulls=true` and new analyzer.

Fixes #64930

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit 861dcbbffbef382c542e6e9485ec21a8e5fa5ffd with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66400/861dcbbffbef382c542e6e9485ec21a8e5fa5ffd/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Analyzer/Resolve/IdentifierResolveScope.h [hunk 1]
```diff
@@ -188,6 +188,8 @@ struct IdentifierResolveScope
     /// Join retutns NULLs instead of default values
     bool join_use_nulls = false;
 
+    bool is_query;
```
Comment (novikd) [inline src/Analyzer/Resolve/IdentifierResolveScope.h:191]: This could be done by `scope_node->getNodeType() == QueryTreeNodeType::QUERY`

**Review by novikd — COMMENTED** [review]
In general LGTM, but `is_query` filed is redundant. I'd recommend to remove it.
