### PR TITLE
Fix detach/attach for postgres database engine tables with numeric/decimal columns

### LINKED ISSUE #66242: PostgreSQL database engine cannot correctly map pg numeric type after detachment (Code: 50. DB::Exception: Unknown data type family: Decimal(14, 2))
Tested on versions 24.5.3.5 and 23.8.15.35

Error occurs when detaching, and then trying to attach back a table from database created with postgresql engine and use_table_cache option set to 1. 

How to reproduce: 

Create a test table in postgres database with a numeric(14, 2) field

```
CREATE TABLE test (
  some_numeric numeric(14,2)
);  
```

then create a clickhouse database mapped to a postgres database, with a `use_table_cache` option set to 1

```
CREATE DATABASE pg_test
ENGINE = PostgreSQL('postgres:5432', 'gp', 'postgres', 'postgres', 'public', 1); -- write your credentials
```

detach a table in clickhouse

```
DETACH TABLE pg_test.test -- works fine
```

try to attach it back

```
ATTACH TABLE pg_test.test
```

recieve and exception

`ClickHouse::DbException: [404] Code: 50. DB::Exception: Unknown data type family: Decimal(14, 2). Maybe you meant: ['Decimal128']. (UNKNOWN_TYPE) (version 24.5.3.5 (official build))
`

### PR DESCRIPTION
**Pull request by jmaicher**
Fixes #66242

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix detach/attach for postgres database engine tables with numeric/decimal columns

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Databases/PostgreSQL/DatabasePostgreSQL.cpp [hunk 1]
```diff
@@ -519,6 +520,9 @@ ASTPtr DatabasePostgreSQL::getColumnDeclaration(const DataTypePtr & data_type) c
     if (which.isDateTime64())
         return makeASTDataType("DateTime64", std::make_shared<ASTLiteral>(static_cast<UInt32>(6)));
 
+    if (which.isDecimal())
+        return makeASTDataType("Decimal", std::make_shared<ASTLiteral>(getDecimalPrecision(*data_type)), std::make_shared<ASTLiteral>(getDecimalScale(*data_type)));
```
Comment (tuanpach) [inline src/Databases/PostgreSQL/DatabasePostgreSQL.cpp:524]: The logic is different here:

https://github.com/tuanpach/ClickHouse/blob/f6c8582a54259903f3796ced5ab6a8685a94d46b/src/Storages/PostgreSQL/StorageMaterializedPostgreSQL.cpp#L335

Should wehave the same logic?

Comment (jmaicher) [reply src/Databases/PostgreSQL/DatabasePostgreSQL.cpp:524]: Yes, good point. We should use the same logic there. Just tested it with current logic for materialized that you linked, and there the advertised type in the ddl does not match the actual type:

```
:) show create table pg_test_materialized.postgres_table

SHOW CREATE TABLE pg_test_materialized.postgres_table

Query id: 96f28e3b-dbe8-4fa9-848f-16bf0ccd0e04

   ┌─statement────────────────────────────────────────┐
1. │ CREATE TABLE pg_test_materialized.postgres_table↴│
   │↳(                                               ↴│
   │↳    `a` Int32,                                  ↴│
   │↳    `b` Decimal128(19),                         ↴│
   │↳    `c` Decimal32(5),                           ↴│
   │↳    `_sign` Int8 MATERIALIZED 1,                ↴│
   │↳    `_version` UInt64 MATERIALIZED 1            ↴│
   │↳)                                               ↴│
   │↳ENGINE = ReplacingMergeTree(_version)           ↴│
   │↳ORDER BY tuple(a)                                │
   └──────────────────────────────────────────────────┘
```
vs.
```
 :) describe table pg_test_materialized.postgres_table

DESCRIBE TABLE pg_test_materialized.postgres_table

Query id: 620283a7-dfd5-4b74-8de0-8e884f494bc1

   ┌─name─────┬─type────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
1. │ a        │ Int32           │              │                    │         │                  │                │
2. │ b        │ Decimal(38, 19) │              │                    │         │                  │                │
3. │ c        │ Decimal(9, 5)   │              │                    │         │                  │                │
4. │ _sign    │ Int8            │ MATERIALIZED │ 1                  │         │                  │                │
5. │ _version │ UInt64          │ MATERIALIZED │ 1                  │         │                  │                │
   └──────────┴─────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

Comment (jmaicher) [reply src/Databases/PostgreSQL/DatabasePostgreSQL.cpp:524]: Done

Comment (jmaicher) [reply src/Databases/PostgreSQL/DatabasePostgreSQL.cpp:524]: @tuanpach Can we get this in?

**Review by tuanpach — APPROVED** [review]

**Comment by jmaicher** [comment]
Can we backport this to 25.8 LTS?

**Comment by jmaicher** [comment]
@tuanpach Any chance to get this into 25.8 LTS?

**Comment by tuanpach** [comment]
> @tuanpach Any chance to get this into 25.8 LTS?

Hi @jmaicher 

Sorry for missing your last message.
Yes, I will backport it to 25.8
