### PR TITLE
Fix to populate row policies for all select query types in query_log

### LINKED ISSUE #99456: system.query_log.used_row_policies is empty for VIEW and subquery queries
### Company or project name

_No response_

### Describe the unexpected behaviour

Row policies are applied correctly, but system.query_log.used_row_policies is not populated when the table is accessed through a view or a subquery.

```
Row 1:
──────
query:             SELECT * FROM rp_log_test.t1 ORDER BY id
tables:            ['rp_log_test.t1']
used_row_policies: ['pol_a ON rp_log_test.t1']

== view ==
1	1
3	1
Row 1:
──────
query:             SELECT * FROM rp_log_test.v1 ORDER BY id
tables:            ['rp_log_test.t1','rp_log_test.v1']
used_row_policies: []

== subquery ==
1	1
3	1
Row 1:
──────
query:             SELECT * FROM (SELECT * FROM rp_log_test.t1) ORDER BY id
tables:            ['rp_log_test.t1']
used_row_policies: []
```

### Which ClickHouse versions are affected?

25.8

### How to reproduce

```
#!/usr/bin/env bash
set -euo pipefail

DB="rp_log_test"
TABLE="t1"
VIEW="v1"
USER_A="A"

ch() {
  clickhouse-client "$@"
}

cleanup() {
  ch --user default -q "DROP VIEW IF EXISTS ${DB}.${VIEW}" >/dev/null 2>&1 || true
  ch --user default -q "DROP ROW POLICY IF EXISTS pol_a ON ${DB}.${TABLE}" >/dev/null 2>&1 || true
  ch --user default -q "DROP USER IF EXISTS ${USER_A}" >/dev/null 2>&1 || true
  ch --user default -q "DROP TABLE IF EXISTS ${DB}.${TABLE}" >/dev/null 2>&1 || true
  ch --user default -q "DROP DATABASE IF EXISTS ${DB}" >/dev/null 2>&1 || true
}

show_log() {
  local pattern="$1"

  ch --user default -q "SYSTEM FLUSH LOGS"

  ch --user default -q "
    SELECT
      query,
      tables,
      used_row_policies
    FROM system.query_log
    WHERE type = 'QueryFinish'
      AND query LIKE '${pattern}'
    ORDER BY event_time_microseconds DESC
    LIMIT 1
    FORMAT Vertical
  "
}

cleanup

echo "create objects"
ch --user default --multiquery <<SQL
CREATE DATABASE ${DB};

CREATE TABLE ${DB}.${TABLE}
(
    id UInt32,
    b UInt32
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO ${DB}.${TABLE} VALUES (1,1),(2,2),(3,1);

CREATE USER ${USER_A} IDENTIFIED WITH no_password;

GRANT SELECT ON ${DB}.${TABLE} TO ${USER_A};

CREATE ROW POLICY pol_a ON ${DB}.${TABLE}
FOR SELECT
USING b = 1
TO ${USER_A};

CREATE VIEW ${DB}.${VIEW} AS
SELECT * FROM ${DB}.${TABLE};

GRANT SELECT ON ${DB}.${VIEW} TO ${USER_A};
SQL

echo "== direct =="
ch --user "${USER_A}" -q "SELECT * FROM ${DB}.${TABLE} ORDER BY id"
show_log "%SELECT * FROM ${DB}.${TABLE} ORDER BY id%"

echo
echo "== view =="
ch --user "${USER_A}" -q "SELECT * FROM ${DB}.${VIEW} ORDER BY id"
show_log "%SELECT * FROM ${DB}.${VIEW} ORDER BY id%"

echo
echo "== subquery =="
ch --user "${USER_A}" -q "SELECT * FROM (SELECT * FROM ${DB}.${TABLE}) ORDER BY id"
show_log "%SELECT * FROM (SELECT * FROM ${DB}.${TABLE}) ORDER BY id%"


cleanup
```

### Expected behavior

`used_row_policies` are not empty for views and subqueries

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by npakeer**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Row policies were not populated for views, sub queries, insert select etc..to query_log. Even though row policies were used in the query planning, they were  not propagated  from sub palnner to the parent planner for logging. This change fixes this bug by keeping row_policies(only for logging) inside QueryAccessInfo, were planner and sub planners can access and populate.

Resolves https://github.com/ClickHouse/ClickHouse/issues/99456

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.4.1.816`

### CODE REVIEW

File: src/Interpreters/Context.cpp
Comment (nikitamikhaylov) [inline src/Interpreters/Context.cpp]:
```suggestion
        throw Exception(ErrorCodes::LOGICAL_ERROR, "Global context cannot have view access info");
```

File: src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -2584,6 +2584,15 @@ void Context::addViewAccessInfo(const String & view_name)
     query_access_info->views.emplace(view_name);
 }
 
+void Context::addUsedRowPolicy(const String & policy_name)
+{
+    if (isGlobalContext())
+        throw Exception(ErrorCodes::LOGICAL_ERROR, "Global context cannot have query access info");
```
Comment (nikitamikhaylov) [inline src/Interpreters/Context.cpp]:
```suggestion
        throw Exception(ErrorCodes::LOGICAL_ERROR, "Global context cannot have used row policies info");
```

File: src/Interpreters/InterpreterSelectIntersectExceptQuery.cpp [hunk 2]
```diff
@@ -197,23 +197,8 @@ void InterpreterSelectIntersectExceptQuery::ignoreWithTotals()
         interpreter->ignoreWithTotals();
 }
 
-void InterpreterSelectIntersectExceptQuery::extendQueryLogElemImpl(QueryLogElement & elem, const ASTPtr & /*ast*/, ContextPtr /*context_*/) const
+void InterpreterSelectIntersectExceptQuery::extendQueryLogElemImpl(QueryLogElement & /*elem*/, const ASTPtr & /*ast*/, ContextPtr /*context_*/) const
```
Comment (nikitamikhaylov) [inline src/Interpreters/InterpreterSelectIntersectExceptQuery.cpp]: This overriden method now has an empty body. Just remove it then.

**Review by nikitamikhaylov — CHANGES_REQUESTED** [review]

File: src/Interpreters/Context.cpp
Comment (npakeer) [reply src/Interpreters/Context.cpp]: Thanks! I will make this change.

File: src/Interpreters/InterpreterSelectIntersectExceptQuery.cpp (hunk 2 above)
Comment (npakeer) [reply src/Interpreters/InterpreterSelectIntersectExceptQuery.cpp]: This makes sense. I think the base class [IInterpreter.h](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/IInterpreter.h) seems to have empty function which should handle calls [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/executeQuery.cpp#L485-L486) for select queries. 

I pushed the changes.

File: src/Interpreters/Context.cpp (hunk 1 above)
Comment (npakeer) [reply src/Interpreters/Context.cpp]: Made these change in new commits being pushed.

**Comment by alexey-milovidov** [comment]
The Stress test (arm_msan) failure is fixed by https://github.com/ClickHouse/ClickHouse/pull/101239, which should be merged first. After it is merged, please update the branch to include the fix.

**Comment by alexey-milovidov** [comment]
The MSan stress test failure (MemorySanitizer: use-of-uninitialized-value, STID 4179-5154 or 4148-3044) is a known pre-existing issue unrelated to this PR. Fix: #102158

**Review by nikitamikhaylov — APPROVED** [review]

**Comment by clickgapai** [comment]
Hi — this PR may need backporting to `26.3` (LTS), `26.2`, `26.1`, `25.8` (LTS), but no backport label was found.

**Affected code:** InterpreterSelectQuery::extendQueryLogElemImpl, InterpreterSelectQueryAnalyzer::extendQueryLogElemImpl, executeQuery.cpp query log population — core code present in all supported branches.

**Why:** This fixes a user-visible bug where used_row_policies in system.query_log was empty for views, subqueries, and INSERT SELECT. The affected code (InterpreterSelectQuery::extendQueryLogElemImpl, InterpreterSelectQueryAnalyzer::extendQueryLogElemImpl, executeQuery.cpp logging) has existed since before all supported branches. The fix is safe — it only moves where row policy names are stored during query planning.

If this should be backported, consider adding `pr-must-backport` or a version-specific label (e.g. `v26.3-must-backport`). Ignore this if backporting is not applicable.
