### PR TITLE
Fix possible logical error in Log engine during subcolumns reading

### LINKED ISSUE #91710: Logical error: '(isConst() || isSparse() || isReplicated()) ? getDataType() == rhs.getDataType() : typeid(*this) == typeid(rhs)' (STID: 2508-35cc)
https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91581&sha=1f4aff8a1d8f0c0106ac8a2b3d5650663aaee399&name_0=PR&name_1=BuzzHouse+%28arm_asan%29

How to reproduce:
```sql
DROP TABLE IF EXISTS test;
CREATE TABLE test (c String) ENGINE = Log;
INSERT INTO TABLE test SELECT randomString(10) from numbers(1000);
INSERT INTO TABLE test SELECT randomString(10) from numbers(1000);
SELECT * FROM test ORDER BY c, c.size FORMAT Null;
DROP TABLE test;
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix possible logical error in Log engine during subcolumns reading. Closes https://github.com/ClickHouse/ClickHouse/issues/91710

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/StorageLog.cpp [hunk 1]
```diff
@@ -192,8 +193,17 @@ Chunk LogSource::generate()
     /// How many rows to read for the next block.
     size_t max_rows_to_read = std::min(block_size, rows_limit - rows_read);
     std::unordered_map<String, ISerialization::SubstreamsCache> caches;
+    std::unordered_map<String, ISerialization::SubstreamsDeserializeStatesCache> deserialize_states_caches;
```
Comment (SmitaRKulkarni) [inline src/Storages/StorageLog.cpp:196]: @Avogar where are we using this (`deserialize_states_caches`) map ?

Comment (Avogar) [reply src/Storages/StorageLog.cpp:196]: On line 203 in `readPrefix`. It's needed to read subcolumns that share common prefixes correctly

**Review by SmitaRKulkarni — APPROVED** [review]
LGTM
