### PR TITLE
Fix many flaky RMV tests

### LINKED ISSUE #90613: Tests `test_refreshable_mv/test.py::*` are flaky
https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X3JlZnJlc2hhYmxlX212JyBBUyBuYW1lX3N1YnN0ciwKICAgIDMwIEFTIGludGVydmFsX2RheXMKU0VMRUNUCiAgICBjaGVja19zdGFydF90aW1lIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK

Example:
https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=e77db570fc9e43590d269573884d171753e24f7a&name_0=MasterCI&name_1=Integration%20tests%20%28amd_binary%2C%203%2F5%29&name_1=Integration%20tests%20%28amd_binary%2C%203%2F5%29

Failures:
```
E   Code: 36. DB::Exception: Received from 172.16.2.9:9000. DB::Exception: Refreshable view re.a (080faa3e-7509-443d-b292-1d864bf10cec) doesn't exist. Stack trace:   
```

@al13n321 please take a look

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

Fixes https://github.com/ClickHouse/ClickHouse/issues/90613

This should cover all different failures that happened in CI recently on `master` branch outside PRs [1].

(Everyone is used to me being the owner of most RMV code, but almost none of these tests are mine. Triaging them by git blame on the test's code would've worked better.)

[1] https://play.clickhouse.com/play?user=play&run=1#c2VsZWN0IGNoZWNrX3N0YXJ0X3RpbWUsIGNvbW1pdF9zaGEsIGNoZWNrX25hbWUsIGNvdW50KCkgYXMgZmFpbF9jb3VudCwgZ3JvdXBBcnJheUlmKHRlc3RfbmFtZSwgKHRlc3RfbmFtZSBpbGlrZSAnJXJlZnJlc2hhYmxlJScgb3IgdGVzdF9uYW1lIGlsaWtlICclcm12JScpKSBhcyBybXZfZmFpbHMsIGFueShyZXBvcnRfdXJsKSBhcyByZXBvcnRfdXJsCmZyb20gY2hlY2tzCldIRVJFIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBpbnRlcnZhbCA5MCBkYXkgYW5kIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCBoZWFkX3JlZiA9ICdtYXN0ZXInCiAgICBhbmQgdGVzdF9uYW1lIG5vdCBpbiAoJ3Rlc3RfcmVmcmVzaGFibGVfbWF0X3ZpZXcvdGVzdC5weTo6dGVzdF9sb25nX3F1ZXJ5X2NhbmNlbCcsICd0ZXN0X3JlZnJlc2hhYmxlX212L3Rlc3QucHk6OnRlc3RfcmVmcmVzaGFibGVfbXZfaW5fcmVhZF9vbmx5X25vZGUnLCAndGVzdF9yZWZyZXNoYWJsZV9tdi90ZXN0LnB5Ojp0ZXN0X3JlZnJlc2hfdnNfc2h1dGRvd25fc21va2UnLCAndGVzdF9yZWZyZXNoYWJsZV9tdi90ZXN0LnB5Ojp0ZXN0X3BhdXNlJywgJ3Rlc3RfcmVmcmVzaGFibGVfbXYvdGVzdC5weTo6dGVzdF9iYWNrdXBfb3V0ZXJfdGFibGUnLCAndGVzdF9yZWZyZXNoYWJsZV9tdi90ZXN0LnB5Ojp0ZXN0X2JhY2t1cF9pbm5lcl90YWJsZScsICd0ZXN0X3JlZnJlc2hhYmxlX212L3Rlc3QucHk6OnRlc3RfYWRkaW5nX3JlcGxpY2EnLCAndGVzdF9yZWZyZXNoYWJsZV9tdi90ZXN0LnB5Ojp0ZXN0X3JlcGxpY2F0ZWRfZGJfc3RhcnR1cF9yYWNlJywgJzAzNzA0X3Jtdl9sb2dnaW5nX2ludGVybmFsX3F1ZXJpZXMnLCAnMDMyMjFfcmVmcmVzaGFibGVfbWF0dmlld19wcm9ncmVzcycsICd0ZXN0X3JlZnJlc2hhYmxlX212L3Rlc3QucHk6OnRlc3RfcmVmcmVzaGFibGVfbXZfaW5fcmVwbGljYXRlZF9kYicpCiAgICBhbmQgdGVzdF9uYW1lIG5vdCBsaWtlICd0ZXN0X3JlZnJlc2hhYmxlX21hdF92aWV3X3JlcGxpY2F0ZWQvdGVzdC5weTo6dGVzdF9yZWFsX3dhaXRfcmVmcmVzaCUnCiAgICBhbmQgdGVzdF9uYW1lIG5vdCBsaWtlICd0ZXN0X3JlZnJlc2hhYmxlX212X3NraXBfb2xkX3RlbXBfdGFibGVfZGRscy90ZXN0LnB5Ojp0ZXN0X3JlZnJlc2hhYmxlX212X3NraXBfb2xkX3RlbXBfdGFibGVzX2RkbHMlJwogICAgYW5kIHRlc3RfbmFtZSBub3QgbGlrZSAndGVzdF9yZWZyZXNoYWJsZV9tYXRfdmlldy90ZXN0LnB5Ojp0ZXN0X3NpbXBsZV9hcHBlbmQlJwpncm91cCBieSBjaGVja19zdGFydF90aW1lLCBjb21taXRfc2hhLCBjaGVja19uYW1lCmhhdmluZyBmYWlsX2NvdW50IDwgMzUgYW5kIGxlbmd0aChybXZfZmFpbHMpID4gMCBhbmQgbm90IGhhcyhybXZfZmFpbHMsICd0ZXN0X3JlZnJlc2hhYmxlX212L3Rlc3QucHk6OnRlc3RfcmVmcmVzaGFibGVfbXZfaW5fcmVhZF9vbmx5X25vZGVfbm9fZGRsJykKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZSBkZXNj

### CODE REVIEW

File: src/Common/FailPoint.cpp [hunk 1]
```diff
@@ -139,62 +139,12 @@ APPLY_FOR_FAILPOINTS(M, M, M, M)
...
-public:
-    explicit FailPointChannel(UInt64 timeout_)
-        : timeout_ms(timeout_)
-    {}
-    FailPointChannel()
-        : timeout_ms(0)
-    {}
-
-    void wait()
-    {
```
Comment (al13n321) [inline src/Common/FailPoint.cpp:153]: (This would incorrectly unblock on spurious wake up.)

File: src/Common/FailPoint.cpp [hunk 2]
```diff
@@ -139,62 +139,12 @@ APPLY_FOR_FAILPOINTS(M, M, M, M)
...
-    }
-
-private:
-    UInt64 timeout_ms;
-    std::mutex m;
     std::condition_variable cv;
+    bool notified = false;
 };
 
-void FailPointInjection::enablePauseFailPoint(const String & fail_point_name, UInt64 time_ms)
```
Comment (al13n321) [inline src/Common/FailPoint.cpp:173]: (This was unused.)

File: src/Common/FailPoint.cpp [hunk 3]
```diff
@@ -246,11 +197,11 @@ void FailPointInjection::wait(const String & fail_point_name)
     std::unique_lock lock(mu);
     auto iter = fail_point_wait_channels.find(fail_point_name);
     if (iter == fail_point_wait_channels.end())
-        throw Exception(ErrorCodes::BAD_ARGUMENTS, "Can not find channel for fail point {}", fail_point_name);
-
-    lock.unlock();
-    auto ptr = iter->second;
```
Comment (al13n321) [inline src/Common/FailPoint.cpp:252]: (This could use-after-free.)

File: src/Common/FailPoint.cpp [hunk 4]
```diff
@@ -246,11 +197,11 @@ void FailPointInjection::wait(const String & fail_point_name)
...
-    ptr->wait();
```
Comment (al13n321) [inline src/Common/FailPoint.cpp:253]: (This could wait forever if the SYSTEM DISABLE FAILPOINT happened between the `find` and the `wait`.)

File: src/Storages/MaterializedView/RefreshTask.cpp [hunk 5]
```diff
@@ -997,11 +992,6 @@ bool RefreshTask::updateCoordinationState(CoordinationZnode root, bool running,
         ops.emplace_back(zkutil::makeSetRequest(coordination.path, root.toString(), root.version));
         if (running)
         {
-            bool stop_racing_for_running_refresh = false;
-            fiu_do_on(FailPoints::refresh_task_stop_racing_for_running_refresh, { stop_racing_for_running_refresh = true; });
```
Comment (al13n321) [inline src/Storages/MaterializedView/RefreshTask.cpp:1001]: (This was ~equivalent to `SYSTEM STOP VIEW`.)

File: tests/integration/test_refreshable_mat_view/test.py [hunk 6]
```diff
@@ -147,12 +147,11 @@ def module_setup_tables(started_cluster):
     node.query(f"DROP DATABASE IF EXISTS test_db")
     node.query(f"CREATE DATABASE IF NOT EXISTS test_db ON CLUSTER default")
     node.query("DROP TABLE IF EXISTS test_rmv ON CLUSTER default")
+    node.query("DROP TABLE IF EXISTS test_db.test_rmv ON CLUSTER default")
     node.query("DROP TABLE IF EXISTS src1 ON CLUSTER default")
     node.query("DROP TABLE IF EXISTS src2 ON CLUSTER default")
     node.query("DROP TABLE IF EXISTS tgt1 ON CLUSTER default")
     node.query("DROP TABLE IF EXISTS tgt2 ON CLUSTER default")
-    node.query("DROP TABLE IF EXISTS test_rmv ON CLUSTER default")
-    node.query("DROP TABLE IF EXISTS test_db.test_rmv ON CLUSTER default")
```
Comment (al13n321) [inline tests/integration/test_refreshable_mat_view/test.py:155]: (RMV could re-create its target table after the target table has been dropped, so RMVs should be dropped first.)

File: tests/integration/test_refreshable_mat_view/test.py [hunk 7]
```diff
@@ -198,11 +201,6 @@ def fn_setup_tables():
 )
 @pytest.mark.parametrize("with_append", [True, False])
 @pytest.mark.parametrize("empty", [True, False])
-@pytest.mark.skipif(
-    datetime.now().minute > 57,
```
Comment (al13n321) [inline tests/integration/test_refreshable_mat_view/test.py:202]: (pytest may perform this check long before the test actually runs. I didn't check how exactly it happens; probably it just does the check for all tests before running any of them, then the earlier tests may take >>3 minutes. And also it's silly to make a test ineffective 5% of the time at random.)

File: tests/integration/test_refreshable_mat_view/test.py [hunk 8]
```diff
@@ -249,7 +247,6 @@ def test_simple_append(
 
 
 @pytest.mark.parametrize("with_append", [True, False])
-@pytest.mark.parametrize("if_not_exists", [True, False])
```
Comment (al13n321) [inline tests/integration/test_refreshable_mat_view/test.py:252]: (Having 128 minor variations of an expensive test is wasteful. This reduces it to 64, but would be nice to improve this further.)

File: tests/integration/test_refreshable_mat_view_replicated/test.py [hunk 9]
```diff
@@ -246,11 +250,9 @@ def test_append(
     with_append,
     empty,
 ):
-    opposite_minutes = math.floor((time.time() + 1800) % 3600 / 60)
```
Comment (al13n321) [inline tests/integration/test_refreshable_mat_view_replicated/test.py:249]: (Lots of tests are copy-pasted between `test_refreshable_mat_view` and `test_refreshable_mat_view_replicated`. Some of these bugs were already fixed in one of them, but the fix wasn't copy-pasted to the other.)

File: tests/integration/test_refreshable_mat_view_replicated/test.py [hunk 10]
```diff
@@ -357,124 +358,6 @@ def compare_DDL_on_all_nodes():
...
-    [True, False],
-)
-@pytest.mark.parametrize(
-    "to_clause",
-    [
-        (None, "tgt1", "tgt1"),
-        ("Engine ReplicatedMergeTree ORDER BY tuple()", None, "test_rmv"),
-    ],
-)
-def test_real_wait_refresh(
```
Comment (al13n321) [inline tests/integration/test_refreshable_mat_view_replicated/test.py:375]: (This test was removed from the other copy-pasta file a while ago, but forgotten here.)

File: tests/integration/test_refreshable_mv/test.py [hunk 11]
```diff
@@ -312,47 +313,49 @@ def test_refreshable_mv_in_read_only_node_no_ddl(started_cluster, cleanup):
     reading_node.replace_in_config(
         "/etc/clickhouse-server/users.d/users.xml", "<allow_ddl>1", "<allow_ddl>0"
```
Comment (al13n321) [inline tests/integration/test_refreshable_mv/test.py:313]: (When this test failed, it left this config change behind, and lots of other tests failed afterwards because of it.)

File: tests/integration/test_refreshable_mv/test.py [hunk 12]
```diff
@@ -312,47 +313,49 @@ def test_refreshable_mv_in_read_only_node_no_ddl(started_cluster, cleanup):
...
-    node1.query(
-        "create materialized view re.a refresh every 1 second (x Int64) engine ReplicatedMergeTree order by x as select number*10 as x from numbers(2)",
-    )
+        # this MV will be replicated to read_only node
+        node1.query(
+            "create materialized view re.a refresh every 1 second (x Int64) engine ReplicatedMergeTree order by x as select number*10 as x from numbers(2)",
+        )
 
-    reading_node.query("system refresh view re.a")
+        reading_node.query("system sync database replica re")
```
Comment (al13n321) [inline tests/integration/test_refreshable_mv/test.py:333]: (This was missing, so `system refresh view re.a` sometimes failed because the table doesn't exist yet.)

File: tests/integration/test_refreshable_mv_skip_old_temp_table_ddls/test.py [hunk 13]
```diff
@@ -79,82 +79,71 @@ def test_refreshable_mv_skip_old_temp_tables_ddls(
     db_name = "test_" + get_random_string()
     node1.query(f"DROP DATABASE IF EXISTS {db_name} SYNC")
     node2.query(f"DROP DATABASE IF EXISTS {db_name}  SYNC")
-    # Make sure that the MV is refreshed on node1
-    node2.query("SYSTEM ENABLE FAILPOINT refresh_task_stop_racing_for_running_refresh")
-    node2.query("SYSTEM ENABLE FAILPOINT database_replicated_delay_entry_execution")
```
Comment (al13n321) [inline tests/integration/test_refreshable_mv_skip_old_temp_table_ddls/test.py:84]: (This only delayed execution by 1 second, which wasn't always enough.)

File: tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh [hunk 14]
```diff
@@ -10,7 +10,7 @@ CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 $CLICKHOUSE_CLIENT --query "CREATE VIEW one_proxy AS SELECT * FROM system.one"
 $CLICKHOUSE_CLIENT --query "
 CREATE MATERIALIZED VIEW rmv_test
-REFRESH EVERY 1 HOUR
+REFRESH AFTER 1 HOUR
```
Comment (alexbakharew) [inline tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh:13]: What does this change actually fix?

**Review by alexbakharew — APPROVED** [review]
lgtm

File: tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh (hunk 14 above)
Comment (al13n321) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh:13]: Same reason as all the `opposite_minutes()` nonsense. The `countIf` query below expect that the view was refreshed only once, by the `SYSTEM REFRESH VIEW`. But if you create it at XX:59:59.9, it may also have time to do a scheduled refresh before the `countIf`.
