### PR TITLE
Fix wrong result of datetime64 when negative

### LINKED ISSUE #34831: DateTime64 to Arrow format mistreats negative timestamps
Related to recent PR #34561 
Wrong conversion of DateTime64 to Arrow:

Create Arrow file
```bash
./clickhouse client --query="SELECT toDateTime64('1965-12-12 12:12:12.123', 3, 'UTC') FORMAT Arrow" > a.arrow
```

Then, read it:
```python3
>>> pyarrow.open_file('a.arrow').read_all()
pyarrow.Table
toDateTime64('1965-12-12 12:12:12.123', 3, 'UTC'): timestamp[ms, tz=UTC] not null
----
toDateTime64('1965-12-12 12:12:12.123', 3, 'UTC'): [[1965-12-12 12:12:11.877]]


```

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix wrong result of datetime64 when negative. Close https://github.com/ClickHouse/ClickHouse/issues/34831

### CODE REVIEW

**Comment by taiyang-li** [comment]
Failed tests irrelavent with this pr.

**Comment by nickitat** [comment]
build error was fixed btw.

**Comment by nickitat** [comment]
@Megrifyio update

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by nickitat** [comment]
@Mergifyio update

**Comment by taiyang-li** [comment]
Failed tests irrelavent with pr.

**Comment by nickitat** [comment]
> Failed tests irrelavent with pr.

Most likely but it is better to rerun checks than blindly merge pr.

**Comment by taiyang-li** [comment]
@nickitat Thanks for your advice, I pushed again.

**Comment by taiyang-li** [comment]
@nickitat  I found a wrong test introduced by https://github.com/ClickHouse/ClickHouse/pull/34353/files. Fixed now.

File: src/Core/DecimalFunctions.h [hunk 1]
```diff
@@ -154,11 +155,20 @@ inline DecimalComponents<DecimalType> splitWithScaleMultiplier(
         typename DecimalType::NativeType scale_multiplier)
 {
     using T = typename DecimalType::NativeType;
-    const auto whole = decimal.value / scale_multiplier;
+    auto whole = decimal.value / scale_multiplier;
     auto fractional = decimal.value % scale_multiplier;
     if (fractional < T(0))
```
Comment (nickitat) [inline src/Core/DecimalFunctions.h:160]: >  When DecimalType is DateTime64, fractional is always positive, even if whole is negative.

could you pls clarify, why it is only about `DateTime64`? seems like this `if` should make `fractional` nonnegative in all cases?

Comment (taiyang-li) [reply src/Core/DecimalFunctions.h:160]: @nickitat See this issue: https://github.com/ClickHouse/ClickHouse/issues/34831
For datetime64 before `1970-01-01 00:00:00 UTC`, for example `1965-12-12 12:12:12.123`, its unit timestamp in ms unit is 
`-127943268000 + 123`, not `127943268000 - 123`

Comment (nickitat) [reply src/Core/DecimalFunctions.h:160]: IMO the main question is why do we get 127943268 as the `whole`. it seems like the input `decimal` has a wrong value, isn't it?
if you suspect that the pair `splitWithScaleMultiplier` + `decimalFromComponentsWithMultiplier` works incorrectly, you can try to reproduce it with [unit test](https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/tests/gtest_DecimalFunctions.cpp).

Comment (taiyang-li) [reply src/Core/DecimalFunctions.h:160]: @nickitat Yes. The decimal value tranformed from DateTime64 before `1970-01-01 00:00:00 UTC` is wrong. That's why we have to fix these two functions `splitWithScaleMultiplier` and `decimalFromComponentsWithMultiplier`

Comment (taiyang-li) [reply src/Core/DecimalFunctions.h:160]: 1. DateTime64(scale=3) -> Decimal
DateTime64: 1965-12-12 12:12:12.123 UTC
Expected value: -127943268000 + 123 = -127943267877
Real value:  -127943268000 - 123 = -127943268123

2. Decimal -> DateTime64(scale=3)
Decimal: -127943268000 + 123 = -127943267877  
Expected value:  whole = - 127943268 + 123 = 1965-12-12 12:12:12.123
Real value:  whole = -127943267  fractional = -877  -> 1965-12-12 12:12:13.877

**Comment by taiyang-li** [comment]
Failed check-style was  introduced  by master

File: src/Core/tests/gtest_DecimalFunctions.cpp [hunk 2]
```diff
@@ -170,3 +207,27 @@ INSTANTIATE_TEST_SUITE_P(Basic,
         }
     })
 );
+
+INSTANTIATE_TEST_SUITE_P(Basic,
+    DecimalUtilsSplitAndCombineForDateTime64Test,
+    ::testing::ValuesIn(std::initializer_list<DecimalUtilsSplitAndCombineTestParam>{
+        {
+            "Negative timestamp 1965-12-12 12:12:12.123 UTC",
+            DateTime64(-127943267877),
```
Comment (nickitat) [inline src/Core/tests/gtest_DecimalFunctions.cpp:216]: I encourage you to check if these tests don't work on master.

Comment (taiyang-li) [reply src/Core/tests/gtest_DecimalFunctions.cpp:216]: No. It's not

``` sql
:) select toDateTime64('1965-12-12 12:12:12.123', 3, 'UTC') as a,  cast(a as Decimal64(3))
┌───────────────────────a─┬─CAST(toDateTime64('1965-12-12 12:12:12.123', 3, 'UTC'), 'Decimal64(3)')─┐
│ 1965-12-12 12:12:12.123 │                                                          -127914468.123 │
└─────────────────────────┴─────────────────────────────────────────────────────────────────────────┘
```

**Comment by taiyang-li** [comment]
@nickitat Do we have any progress recently ?  Thank you in advance.

File: src/Core/tests/gtest_DecimalFunctions.cpp (hunk 2 above)
Comment (nickitat) [reply src/Core/tests/gtest_DecimalFunctions.cpp:216]: unit tests will pass if you apply the following diff:
``` bash
--- a/src/Core/tests/gtest_DecimalFunctions.cpp
+++ b/src/Core/tests/gtest_DecimalFunctions.cpp
@@ -216,8 +216,8 @@ INSTANTIATE_TEST_SUITE_P(Basic,
             DateTime64(-127943267877),
             3,
             {
-                -127943268,
-                123
+                -127943267,
+                877
             }
         },
```
and for me, everything looks like your fix fixes the problem because only one function ( `decimalFromComponentsWithMultiplier`) is getting called during the query execution.

Comment (taiyang-li) [reply src/Core/tests/gtest_DecimalFunctions.cpp:216]: You mean we must keep the sign of `whole` and `fractional` same in `DecimalComponents`  ?

**Comment by taiyang-li** [comment]
@nickitat  I refactored all this logic as you remind. Thank you for reviewing.

**Comment by taiyang-li** [comment]
Failed tests not related to this pr

**Comment by nickitat** [comment]
I confused by this line `2022.04.16 06:21:26.286238 [ 10284 ] {} <Fatal> BaseDaemon: (version 22.4.1.2071, build id: 904B03A60885B5CB) (from thread 2990) (query_id: 763945a1-5d69-47d8-9ef8-096d781247ef) (query: select * from file('test_02149.data', 'Avro')) Received signal Aborted (6)` in [log](https://s3.amazonaws.com/clickhouse-test-reports/35440/c646a13e3980785f60ad75a038a595051d91d9c6/stress_test__debug__actions_/clickhouse-server.err.log). please check `tests/queries/0_stateless/02149_schema_inference_formats_with_schema.sh` test.

**Comment by taiyang-li** [comment]
> I confused by this line `2022.04.16 06:21:26.286238 [ 10284 ] {} <Fatal> BaseDaemon: (version 22.4.1.2071, build id: 904B03A60885B5CB) (from thread 2990) (query_id: 763945a1-5d69-47d8-9ef8-096d781247ef) (query: select * from file('test_02149.data', 'Avro')) Received signal Aborted (6)` in [log](https://s3.amazonaws.com/clickhouse-test-reports/35440/c646a13e3980785f60ad75a038a595051d91d9c6/stress_test__debug__actions_/clickhouse-server.err.log). please check `tests/queries/0_stateless/02149_schema_inference_formats_with_schema.sh` test.

I can't reroduce it in my env.  Let's merge master again and see what will happen.

**Comment by nickitat** [comment]
looks ok, let's wait for the tests.

**Comment by taiyang-li** [comment]
Failed 2  integration tests not related to pr.

**Review by nickitat — APPROVED** [review]
