### PR TITLE
Better detecting of invalid S2 geo primitives

### LINKED ISSUE #27090: s2geometry: ERROR Invalid S2LatLng in S2LatLng::ToPoint
https://clickhouse-test-reports.s3.yandex.net/0/6951e8147d7a25f7bb4f7d43738793cff239db6d/stress_test_(debug).html#fail1

```
:) SELECT geoToS2(toFloat64(toUInt64(-1)), toFloat64(toUInt64(-1)));

SELECT geoToS2(toFloat64(toUInt64(-1)), toFloat64(toUInt64(-1)))

Query id: f1ef3f1d-b46d-4ef4-a5e5-869798d8379c

┌─geoToS2(toFloat64(toUInt64(-1)), toFloat64(toUInt64(-1)))─┐
│                                       4864204703484167331 │
└───────────────────────────────────────────────────────────┘
```

```
$ grep -Fa ERROR stderr.log 
../contrib/s2geometry/src/s2/s2latlng.cc:37 ERROR Invalid S2LatLng in S2LatLng::ToPoint: [1.84467e+19, 1.84467e+19]
```

Maybe it should throw exception if point is invalid. Also it should not print errors to `stderr`.

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Check whether S2 geo primitives are invalid as early as possible on ClickHouse side. This closes: https://github.com/ClickHouse/ClickHouse/issues/27090

### CODE REVIEW

File: src/Interpreters/Cache/Metadata.cpp [hunk 1]
```diff
@@ -337,7 +337,7 @@ friend struct CacheMetadata;
     {
         {
             std::lock_guard lock(mutex);
-            queue.emplace(file_segment->key(), file_segment->offset(), file_segment);
+            queue.push(DownloadInfo{file_segment->key(), file_segment->offset(), file_segment});
```
Comment (nikitamikhaylov) [inline src/Interpreters/Cache/Metadata.cpp:340]: This is needed to compile with `clang-15`. Unfortunately this is still the latest available version on Manjaro Linux.

**Comment by robot-clickhouse** [comment]
This is an automated comment for commit a06631f0dbaa7402966d69c8b4cac69761627b2d with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/52260/a06631f0dbaa7402966d69c8b4cac69761627b2d/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by alexey-milovidov — APPROVED** [review]

File: src/Interpreters/Cache/Metadata.cpp (hunk 1 above)
Comment (alexey-milovidov) [reply src/Interpreters/Cache/Metadata.cpp:340]: You can always build the latest clang-17 from master:

```
git clone git@github.com:llvm/llvm-project.git
mkdir llvm-build
cd llvm-build
cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DLLVM_ENABLE_PROJECTS=all -DLLVM_TARGETS_TO_BUILD=all ../llvm-project/llvm
time ninja
sudo ninja install
```

Linux package managers are irrelevant to modern software development.
