### PR TITLE
handle incorrect page_cache size limits suitably

### LINKED ISSUE #79793: Very low page cache size gives Logical Error
### Describe the bug

The very first issue from `La Casa del Dolor`

### How to reproduce

At config.xml set

```xml
<page_cache_max_size>8192</page_cache_max_size>
```
then a logical error happens when starting ClickHouse

### Error message and/or stacktrace

Stack trace:

```
contrib/llvm-project/libcxx/include/__algorithm/clamp.h:29: assertion !__comp(__hi, __lo) failed: Bad bounds passed to std::clamp
2025.05.02 12:47:37.175778 [ 2304739 ] {} BaseDaemon: Received signal 6
2025.05.02 12:47:37.175927 [ 2305369 ] {} BaseDaemon: ########## Short fault info ############
2025.05.02 12:47:37.175974 [ 2305369 ] {} BaseDaemon: (version 25.5.1.1900 (official build), build id: 2DA54EA90B6C78A36D4E7B4CD26A2A0280B289A3, git hash: https://github.com/ClickHouse/clickhouse-private/commit/120768e6967cb0313003238ab672844e86c08898, architecture: x86_64) (from thread 2304746) Received signal 6
2025.05.02 12:47:37.176010 [ 2305369 ] {} BaseDaemon: Signal description: Aborted
2025.05.02 12:47:37.176021 [ 2305369 ] {} BaseDaemon:
2025.05.02 12:47:37.176043 [ 2305369 ] {} BaseDaemon: Stack trace: 0x0000603e1fd49db3 0x0000603e20022830 0x000074a016245250 0x000074a0162a3f1d 0x000074a01624519e 0x000074a016228902 0x0000603e2fb2119d 0x0000603e1fd3dca6 0x0000603e1fe42f8b 0x0000603e1fe449e7 0x0000603e1fddeda6 0x0000603e1fde5380 0x000074a0162a1e2e 0x000074a016333a4c
2025.05.02 12:47:37.176062 [ 2305369 ] {} BaseDaemon: ########################################
2025.05.02 12:47:37.176074 [ 2305369 ] {} BaseDaemon: (version 25.5.1.1900 (official build), build id: 2DA54EA90B6C78A36D4E7B4CD26A2A0280B289A3, git hash: https://github.com/ClickHouse/clickhouse-private/commit/120768e6967cb0313003238ab672844e86c08898) (from thread 2304746) (no query) Received signal Aborted (6)
2025.05.02 12:47:37.176082 [ 2305369 ] {} BaseDaemon:
2025.05.02 12:47:37.176092 [ 2305369 ] {} BaseDaemon: Stack trace: 0x0000603e1fd49db3 0x0000603e20022830 0x000074a016245250 0x000074a0162a3f1d 0x000074a01624519e 0x000074a016228902 0x0000603e2fb2119d 0x0000603e1fd3dca6 0x0000603e1fe42f8b 0x0000603e1fe449e7 0x0000603e1fddeda6 0x0000603e1fde5380 0x000074a0162a1e2e 0x000074a016333a4c
2025.05.02 12:47:37.187735 [ 2305369 ] {} BaseDaemon: 0.0. inlined from src/Common/StackTrace.cpp:386: StackTrace::tryCapture()
2025.05.02 12:47:37.187762 [ 2305369 ] {} BaseDaemon: 0. src/Common/StackTrace.cpp:355: StackTrace::StackTrace(ucontext_t const&) @ 0x0000000011c97db3
2025.05.02 12:47:37.200196 [ 2305369 ] {} BaseDaemon: 1. src/Common/SignalHandlers.cpp:106: signalHandler(int, siginfo_t*, void*) @ 0x0000000011f70830
2025.05.02 12:47:37.200222 [ 2305369 ] {} BaseDaemon: 2. ? @ 0x000074a016245250
2025.05.02 12:47:37.200232 [ 2305369 ] {} BaseDaemon: 3. ? @ 0x000074a0162a3f1d
2025.05.02 12:47:37.200241 [ 2305369 ] {} BaseDaemon: 4. ? @ 0x000074a01624519e
2025.05.02 12:47:37.200253 [ 2305369 ] {} BaseDaemon: 5. ? @ 0x000074a016228902
2025.05.02 12:47:37.203588 [ 2305369 ] {} BaseDaemon: 6. contrib/llvm-project/libcxx/src/verbose_abort.cpp:74: ? @ 0x0000000021a6f19d
2025.05.02 12:47:37.214691 [ 2305369 ] {} BaseDaemon: 7.0. inlined from contrib/llvm-project/libcxx/include/__algorithm/clamp.h:29: unsigned long const& std::clamp[abi:se190107]<unsigned long, std::__less<void, void>>(unsigned long const&, unsigned long const&, unsigned long const&, std::__less<void, void>)
2025.05.02 12:47:37.214717 [ 2305369 ] {} BaseDaemon: 7.1. inlined from contrib/llvm-project/libcxx/include/__algorithm/clamp.h:38: unsigned long const& std::clamp[abi:se190107](unsigned long const&, unsigned long const&, unsigned long const&)
2025.05.02 12:47:37.214731 [ 2305369 ] {} BaseDaemon: 7. src/Common/PageCache.cpp:175: DB::PageCache::autoResize(long, unsigned long) @ 0x0000000011c8bca6
2025.05.02 12:47:37.217856 [ 2304736 ] {} KeeperDispatcher: Server initialized, waiting for quorum
2025.05.02 12:47:37.227487 [ 2305369 ] {} BaseDaemon: 8. src/Common/MemoryWorker.cpp:334: DB::MemoryWorker::backgroundThread() @ 0x0000000011d90f8b
2025.05.02 12:47:37.241427 [ 2305369 ] {} BaseDaemon: 9.0. inlined from src/Common/MemoryWorker.cpp:280: operator()
2025.05.02 12:47:37.241456 [ 2305369 ] {} BaseDaemon: 9.1. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declvalDB::MemoryWorker::start()::$_0&()()) std::__invoke[abi:se190107]DB::MemoryWorker::start()::$_0&(DB::MemoryWorker::start()::$_0&)
2025.05.02 12:47:37.241475 [ 2305369 ] {} BaseDaemon: 9.2. inlined from contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<DB::MemoryWorker::start()::$_0&, std::tuple<>&>(DB::MemoryWorker::start()::$_0&, std::tuple<>&, std::__tuple_indices<...>)
2025.05.02 12:47:37.241498 [ 2305369 ] {} BaseDaemon: 9.3. inlined from contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<DB::MemoryWorker::start()::$_0&, std::tuple<>&>(DB::MemoryWorker::start()::$_0&, std::tuple<>&)
2025.05.02 12:47:37.241514 [ 2305369 ] {} BaseDaemon: 9.4. inlined from src/Common/ThreadPool.h:312: operator()
2025.05.02 12:47:37.241528 [ 2305369 ] {} BaseDaemon: 9.5. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declvalDB::MemoryWorker::start()::$_0()()) std::__invoke[abi:se190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImplDB::MemoryWorker::start()::$_0(DB::MemoryWorker::start()::$_0&&)::'lambda'()&>(DB::MemoryWorker::start()::$_0&&)
2025.05.02 12:47:37.241548 [ 2305369 ] {} BaseDaemon: 9.6. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImplDB::MemoryWorker::start()::$_0(DB::MemoryWorker::start()::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImplDB::MemoryWorker::start()::$_0(DB::MemoryWorker::start()::$_0&&)::'lambda'()&)
2025.05.02 12:47:37.241561 [ 2305369 ] {} BaseDaemon: 9.7. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
2025.05.02 12:47:37.241574 [ 2305369 ] {} BaseDaemon: 9. contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x0000000011d929e7
2025.05.02 12:47:37.251645 [ 2305369 ] {} BaseDaemon: 10.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
2025.05.02 12:47:37.251666 [ 2305369 ] {} BaseDaemon: 10.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
2025.05.02 12:47:37.251678 [ 2305369 ] {} BaseDaemon: 10. src/Common/ThreadPool.cpp:809: ThreadPoolImplstd::thread::ThreadFromThreadPool::worker() @ 0x0000000011d2cda6
2025.05.02 12:47:37.271431 [ 2305369 ] {} BaseDaemon: 11.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(std::declval<ThreadPoolImplstd::thread::ThreadFromThreadPool>().std::declval<void (ThreadPoolImplstd::thread::ThreadFromThreadPool::)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImplstd::thread::ThreadFromThreadPool::)(), ThreadPoolImplstd::thread::ThreadFromThreadPool, void>(void (ThreadPoolImplstd::thread::ThreadFromThreadPool::&&)(), ThreadPoolImplstd::thread::ThreadFromThreadPool&&)
2025.05.02 12:47:37.271464 [ 2305369 ] {} BaseDaemon: 11.1. inlined from contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_deletestd::__thread_struct>, void (ThreadPoolImplstd::thread::ThreadFromThreadPool::)(), ThreadPoolImplstd::thread::ThreadFromThreadPool, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_deletestd::__thread_struct>, void (ThreadPoolImplstd::thread::ThreadFromThreadPool::)(), ThreadPoolImplstd::thread::ThreadFromThreadPool>&, std::__tuple_indices<2ul>)
2025.05.02 12:47:37.271482 [ 2305369 ] {} BaseDaemon: 11. contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_deletestd::__thread_struct>, void (ThreadPoolImplstd::thread::ThreadFromThreadPool::)(), ThreadPoolImplstd::thread::ThreadFromThreadPool>>(void*) @ 0x0000000011d33380
2025.05.02 12:47:37.271498 [ 2305369 ] {} BaseDaemon: 12. ? @ 0x000074a0162a1e2e
2025.05.02 12:47:37.271508 [ 2305369 ] {} BaseDaemon: 13. ? @ 0x000074a016333a4c
2025.05.02 12:47:37.445926 [ 2305369 ] {} BaseDaemon: Integrity check of the executable successfully passed (checksum: 2601C35AEEDC11C0A1207BF8C8DCC14F)
2025.05.02 12:47:37.445976 [ 2305369 ] {} SentryWriter: Not sending crash report
2025.05.02 12:47:37.445988 [ 2305369 ] {} BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
```

### PR DESCRIPTION
**Pull request by bharatnc**
If the page cache `page_cache_min_size` and `page_cache_max_size` limits are not configured correctly, then it's possible to make the server crash during a page cache resize operation. For example in the case where `page_cache_max_size` < `page_cache_min_size`, try to validate the config and fail fast during server startup.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Handle incorrectly configured page_cache_limits suitably.

Closes: https://github.com/ClickHouse/ClickHouse/issues/79793

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Common/PageCache.cpp [hunk 1]
```diff
@@ -172,7 +173,22 @@ void PageCache::autoResize(Int64 memory_usage_signed, size_t memory_limit)
...
+    /// then set the target_size to page_cache_min_size to ensure that the resizing logic
+    /// works correctly and doesn't cause the server to crash.
+    if (min_size_in_bytes <= max_size_in_bytes)
+    {
+        target_size = std::clamp(target_size, min_size_in_bytes, max_size_in_bytes);
+    }
+    else
+    {
+        target_size = min_size_in_bytes;
+        LOG_WARNING(
```
Comment (alexey-milovidov) [inline src/Common/PageCache.cpp:187]: It's better to throw an exception and prevent server startup.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: src/Common/PageCache.cpp (hunk 1 above)
Comment (bharatnc) [reply src/Common/PageCache.cpp]: Sure, moved the validation to server startup.

**Review by alexey-milovidov — APPROVED** [review]
