### PR TITLE
default variant implementation throw on type mismatch

### LINKED ISSUE #95839: Logical error: '(isConst() || isSparse() || isReplicated()) ? getDataType() == rhs.getDataType() : typeid(*this) == typeid(rhs)' (STID: 2508-1fb5)
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: Logical error: '(isConst() || isSparse() || isReplicated()) ? getDataType() == rhs.getDataType() : typeid(*this) == typeid(rhs)' (STID: 2508-1fb5)
CI report: [AST fuzzer (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=95767&sha=7342b287c6f6c68a7fc88c3f9429b1cf924de278&name_0=PR&name_1=AST%20fuzzer%20%28amd_debug%29)
Failing test history: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICdMb2dpY2FsIGVycm9yOiAnJyhpc0NvbnN0KCkgfHwgaXNTcGFyc2UoKSB8fCBpc1JlcGxpY2F0ZWQoKSkgPyBnZXREYXRhVHlwZSgpID09IHJocy5nZXREYXRhVHlwZSgpIDogdHlwZWlkKCp0aGlzKSA9PSB0eXBlaWQocmhzKScnIChTVElEOiAyNTA4LTFmYjUpJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnQVNUIGZ1enplciAoYW1kX2RlYnVnKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBiYXNlX3JlZiBJTiAoJ21hc3RlcicpKQogICAgLS0gQU5EIHRlc3RfY29udGV4dF9yYXcgTElLRSAnJXBhdHRlcm4lJyAgLS0gdW5jb21tZW50IGFuZCBlZGl0IHRvIGZpbHRlciBieSBmYWlsdXJlIHBhdHRlcm4KR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
Error:
Logical error: '(isConst() || isSparse() || isReplicated()) ? getDataType() == rhs.getDataType() : typeid(*this) == typeid(rhs)'.
---

Failed query:
SELECT arrayRemove([[[isNotDistinctFrom(16, isNotDistinctFrom(16, assumeNotNull(isNotNull(materialize(8)))))]], [[materialize(toUInt128(8)), equals(2, isNull(isZeroOrNull(*)))], *], [isNotDistinctFrom(isNull(assumeNotNull(16)), isNotDistinctFrom(isZeroOrNull(NULL), 16)), [], [arrayMap(x -> materialize(0), [NULL])]], [isZeroOrNull(8), [isZeroOrNull(8)]]], [[arrayRemove(['hello', 'world'], concat('a', 1, equals(16, isNullable(8)))), isNotDistinctFrom(16, isNotDistinctFrom(isZeroOrNull(8), 16))]])
---

Reproduce commands (auto-generated; may require manual adjustment):
SELECT arrayRemove([[[isNotDistinctFrom(16, isNotDistinctFrom(16, assumeNotNull(isNotNull(materialize(8)))))]], [[materialize(toUInt128(8)), equals(2, isNull(isZeroOrNull(*)))], *], [isNotDistinctFrom(isNull(assumeNotNull(16)), isNotDistinctFrom(isZeroOrNull(NULL), 16)), [], [arrayMap(x -> materialize(0), [NULL])]], [isZeroOrNull(8), [isZeroOrNull(8)]]], [[arrayRemove(['hello', 'world'], concat('a', 1, equals(16, isNullable(8)))), isNotDistinctFrom(16, isNotDistinctFrom(isZeroOrNull(8), 16))]])
---

Stack trace:
pthread_kill @ 0x00000000000969fd
gsignal @ 0x0000000000042476
__lgamma_r_finite@GLIBC_2.15 @ 0x00000000000287f3
/ClickHouse/src/Common/Exception.cpp:57: DB::abortOnFailedAssertion(String const&, std::basic_string_view<char, std::char_traits<char>>, void* const*, unsigned long, unsigned long) @ 0x00000000162581dd
/ClickHouse/src/Common/Exception.cpp:63: ? @ 0x0000000016258f07
/ClickHouse/src/Columns/IColumn.h:812: DB::IColumn::assertTypeEquality(DB::IColumn const&) const @ 0x000000000d82dc10
inlined from /ClickHouse/src/Columns/IColumn.h:226: DB::IColumn::insertFrom(DB::IColumn const&, unsigned long)
/ClickHouse/src/Functions/if.cpp:828: DB::(anonymous namespace)::FunctionIf::executeGeneric(DB::ColumnVector<char8_t> const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, unsigned long, bool) @ 0x000000001b99ee22
/ClickHouse/src/Functions/if.cpp:1301: DB::(anonymous namespace)::FunctionIf::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001b99c698
/ClickHouse/src/Functions/IFunctionAdaptors.cpp:10: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001a05b9fa
/ClickHouse/src/Functions/IFunction.cpp:365: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a054601
/ClickHouse/src/Functions/IFunction.cpp:438: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a055eb1
/ClickHouse/src/Functions/IFunction.cpp:577: DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a057186
/ClickHouse/src/Functions/IFunction.cpp:486: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a056b61
/ClickHouse/src/Functions/IFunction.cpp:592: DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a0575dc
/ClickHouse/src/Functions/array/arrayRemove.cpp:25: DB::(anonymous namespace)::BuildAndExecuteFunction(String const&, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::Context const>, unsigned long) @ 0x0000000015cc3a3b
/ClickHouse/src/Functions/array/arrayRemove.cpp:127: DB::FunctionArrayRemove::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000015cc16cb
/ClickHouse/src/Functions/IFunctionAdaptors.cpp:10: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001a05b9fa
/ClickHouse/src/Functions/IFunction.cpp:365: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a054601
/ClickHouse/src/Functions/IFunction.cpp:438: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a055eb1
/ClickHouse/src/Functions/IFunction.cpp:577: DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a057186
/ClickHouse/src/Functions/IFunction.cpp:486: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001a056b61
inlined from /ClickHouse/src/Interpreters/ExpressionActions.cpp:692: DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool, bool, bool)
/ClickHouse/src/Interpreters/ExpressionActions.cpp:835: DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const @ 0x000000001c3353a1
/ClickHouse/src/Processors/Transforms/ExpressionTransform.cpp:30: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x00000000202e0259
/ClickHouse/src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x0000000018c49ad3
/ClickHouse/src/Processors/ISimpleTransform.cpp:100: DB::ISimpleTransform::work() @ 0x0000000020008e0a
inlined from /ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x00000000200275b0
/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:351: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x00000000200196f8
/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:279: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x0000000020019d2c
/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:602: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x00000000200186a1
/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:136: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000020017d7e
inlined from /ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
inlined from /ClickHouse/src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:102: operator()
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>::type std::__invoke[abi:se210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/tuple:1380: decltype(auto) std::__apply_tuple_impl[abi:se210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/tuple:1384: decltype(auto) std::apply[abi:se210105]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
inlined from /ClickHouse/src/Common/ThreadPool.h:312: operator()
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:87: std::__invoke_result_impl<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>::type std::__invoke[abi:se210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:342: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se210105]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:348: DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0 std::__invoke_r[abi:se210105]<void, ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>()
/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:450: ? @ 0x000000002002fb28
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:508: ?
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:772: ?
/ClickHouse/src/Common/ThreadPool.cpp:811: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x00000000163a5503
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:0: std::__invoke_result_impl<void, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>::type std::__invoke[abi:se210105]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
inlined from /ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:159: void std::__thread_execute[abi:se210105]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
/ClickHouse/contrib/llvm-project/libcxx/include/__thread/thread.h:168: void* std::__thread_proxy[abi:se210105]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x00000000163ac08e
start_thread @ 0x0000000000094ac3
__clone3 @ 0x00000000001268c0
```

### PR DESCRIPTION
**Pull request by bharatnc**
Throw on `Variant` type mismatch. Fixes https://github.com/ClickHouse/ClickHouse/issues/95839.                                                                                                                                                                 

### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix logical error on `Variant` type mismatch. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.2.1.301`
- Backported to: `26.1.3.13`

### CODE REVIEW

File: src/Core/Settings.cpp [hunk 1]
```diff
@@ -6646,6 +6656,24 @@ SELECT map('a', range(number), 'b', number, 'c', 'str_' || toString(number)) as
 │ {'a':[0,1],'b':2,'c':'str_2'} │
 └───────────────────────────────┘
 ```
+)", 0) \
+    DECLARE(Bool, variant_throw_on_type_mismatch, false, R"(
```
Comment (Avogar) [inline src/Core/Settings.cpp]: Let's make a single setting for both Variant and Dynamic default implementations. It will be useful for both.

Also, let's make a separate PR without the settings that makes the "throw" behaviour by default and backport it to 26.1 for consistency.

Comment (bharatnc) [reply src/Core/Settings.cpp]: Sure, I have updated the PR with throw behavior by default and also made it as a fix for https://github.com/ClickHouse/ClickHouse/issues/95839.

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
> I'm going to change the category to Backward Incompatible Change

Why? This change was backported to 26.1 to change the default behaviour of this feature https://github.com/ClickHouse/ClickHouse/pull/90900 to make it consistent with similar frature for Dynamic type. I would say it should be `Not for changelog`.

**Comment by clickgapai** [comment]
Hi @bharatnc @Avogar — while reviewing this PR I found the following:

- **Bug (P1):** `variant_throw_on_type_mismatch=false` fails for comparison functions: `try_build` only wraps `build`, not `execute` — https://github.com/ClickHouse/ClickHouse/issues/103484

Happy to discuss — close anything that's wrong or already addressed.
