### PR TITLE
Overflow prevention while DateTime and Time reading

### LINKED ISSUE #82269: Signed integer overflow related to DateTime type
### Describe the bug

With bad input, there's an overflow while parsing datetime values.

### How to reproduce

With this file [table.csv](https://github.com/user-attachments/files/20834759/table.csv), 
users.xml configuration file [users.txt](https://github.com/user-attachments/files/20834816/users.txt), 
config.xml configuration file [config.txt](https://github.com/user-attachments/files/20834887/config.txt), and ClickHouse compiled with UBSAN, run:

```sql
CREATE TABLE t0 (c0 FixedString(643), c1 Int8, c2 Array(Nullable(UInt8)), c3 Decimal(70), c4 LowCardinality(UInt256), c5 DateTime) ENGINE = Memory;
INSERT INTO TABLE t0 (c5, c4, c3, c2, c1, c0) FROM INFILE '<path to table.csv>' SETTINGS input_format_parallel_parsing = 0, max_read_buffer_size = 8, input_format_allow_errors_num = 30 FORMAT CSV; --overflow
```

### Error message and/or stacktrace

Stack trace:

```
src/IO/ReadHelpers.cpp:1589:37: runtime error: signed integer overflow: 974258205985706246 * 10 cannot be represented in type 'time_t' (aka 'long')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/IO/ReadHelpers.cpp:1589:37 
########## Short fault info ############
(version 25.7.1.1, build id: 0C17BCB3E8EA28FABA706CF99A24ED7D5A030A01, git hash: b28c690c4dc27e7bf25f3a94b4305cc7c30617cc, architecture: x86_64) (from thread 653277) Received signal -3
Signal description: sanitizer trap
Sanitizer trap.
Stack trace: 0x000060db8d56d5c3 0x000060db8dab58f3 0x000060db805690a4 0x000060db8057407b 0x000060db8d5e2cdf 0x000060db961a46e2 0x000060db9624f079 0x000060db9b4c82bb 0x000060db9b450808 0x000060db9b3ea7bc 0x000060db9b319ae4 0x000060db9b2d6db9 0x000060db9b2d6684 0x000060db9b30622d 0x000060db9b2f0e58 0x000060db9b2f01c3 0x000060db9b3107b4 0x000060db99ea6940 0x000060db9b2d6db9 0x000060db9b2d6684 0x000060db9b30622d 0x000060db9b2f0e58 0x000060db9b2f12a1 0x000060db9b2eea04 0x000060db9b2edc20 0x000060db9b30ee57 0x000060db8d656f5a 0x000060db8d65ee7f 0x00007e88b34a2ef1 0x00007e88b353445c
########################################
(version 25.7.1.1, build id: 0C17BCB3E8EA28FABA706CF99A24ED7D5A030A01, git hash: b28c690c4dc27e7bf25f3a94b4305cc7c30617cc) (from thread 653277) (no query) Received signal sanitizer trap (-3)
Sanitizer trap.
Stack trace: 0x000060db8d56d5c3 0x000060db8dab58f3 0x000060db805690a4 0x000060db8057407b 0x000060db8d5e2cdf 0x000060db961a46e2 0x000060db9624f079 0x000060db9b4c82bb 0x000060db9b450808 0x000060db9b3ea7bc 0x000060db9b319ae4 0x000060db9b2d6db9 0x000060db9b2d6684 0x000060db9b30622d 0x000060db9b2f0e58 0x000060db9b2f01c3 0x000060db9b3107b4 0x000060db99ea6940 0x000060db9b2d6db9 0x000060db9b2d6684 0x000060db9b30622d 0x000060db9b2f0e58 0x000060db9b2f12a1 0x000060db9b2eea04 0x000060db9b2edc20 0x000060db9b30ee57 0x000060db8d656f5a 0x000060db8d65ee7f 0x00007e88b34a2ef1 0x00007e88b353445c
0.0. inlined from src/Common/StackTrace.cpp:389: StackTrace::tryCapture()
0. src/Common/StackTrace.cpp:61: StackTrace::StackTrace() @ 0x0000000028ae25c3
1. src/Common/SignalHandlers.cpp:212: sanitizerDeathCallback() @ 0x000000002902a8f3
2. __sanitizer::Die() @ 0x000000001bade0a4
3. ? @ 0x000000001bae907b
4. src/IO/ReadHelpers.cpp:1589: void DB::readDateTimeTextFallback<void, false>(long&, DB::ReadBuffer&, DateLUTImpl const&, char const*, char const*) @ 0x0000000028b57cdf
5.0. inlined from src/DataTypes/Serializations/SerializationDateTime.cpp:31: DB::(anonymous namespace)::readText(long&, DB::ReadBuffer&, DB::FormatSettings const&, DateLUTImpl const&, DateLUTImpl const&)
5. src/DataTypes/Serializations/SerializationDateTime.cpp:281: DB::SerializationDateTime::deserializeTextCSV(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x00000000317196e2
6. src/DataTypes/Serializations/SerializationNullable.cpp:773: DB::SerializationNullable::deserializeNullAsDefaultOrNestedTextCSV(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&, std::shared_ptr<DB::ISerialization const> const&) @ 0x00000000317c4079
7. src/Processors/Formats/Impl/CSVRowInputFormat.cpp:386: DB::CSVFormatReader::readField(DB::IColumn&, std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::ISerialization const> const&, bool, String const&) @ 0x0000000036a3d2bb
8. src/Processors/Formats/RowInputFormatWithNamesAndTypes.cpp:304: DB::RowInputFormatWithNamesAndTypes<DB::CSVFormatReader>::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x00000000369c5808
9. src/Processors/Formats/IRowInputFormat.cpp:144: DB::IRowInputFormat::read() @ 0x000000003695f7bc
10. src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x000000003688eae4
11. src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x000000003684bdb9
12. src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000003684b684
13.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
13. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000003687b22d
14. src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000036865e58
15. src/Processors/Executors/PipelineExecutor.cpp:177: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000368651c3
16. src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x00000000368857b4
17. src/Storages/StorageFile.cpp:1480: DB::StorageFileSource::generate() @ 0x000000003541b940
18. src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x000000003684bdb9
19. src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000003684b684
20.0. inlined from src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
20. src/Processors/Executors/ExecutionThreadContext.cpp:102: DB::ExecutionThreadContext::executeTask() @ 0x000000003687b22d
21. src/Processors/Executors/PipelineExecutor.cpp:306: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000036865e58
22. src/Processors/Executors/PipelineExecutor.cpp:276: DB::PipelineExecutor::executeSingleThread(unsigned long) @ 0x00000000368662a1
23. src/Processors/Executors/PipelineExecutor.cpp:508: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x0000000036863a04
24. src/Processors/Executors/PipelineExecutor.cpp:135: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000036862c20
25.0. inlined from src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:76: DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::shared_ptr<DB::ThreadGroup>, unsigned long, bool)
25.1. inlined from src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:102: operator()
25.2. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__invoke[abi:se190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&)
25.3. inlined from contrib/llvm-project/libcxx/include/tuple:1354: decltype(auto) std::__apply_tuple_impl[abi:se190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&, std::__tuple_indices<...>)
25.4. inlined from contrib/llvm-project/libcxx/include/tuple:1358: decltype(auto) std::apply[abi:se190107]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::tuple<>&)
25.5. inlined from src/Common/ThreadPool.h:312: operator()
25.6. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:149: decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__invoke[abi:se190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)
25.7. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:224: void std::__invoke_void_return_wrapper<void, true>::__call[abi:se190107]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&)
25.8. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:210: ?
25. contrib/llvm-project/libcxx/include/__functional/function.h:610: ? @ 0x0000000036883e57
26.0. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:716: ?
26.1. inlined from contrib/llvm-project/libcxx/include/__functional/function.h:989: ?
26. src/Common/ThreadPool.cpp:809: ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x0000000028bcbf5a
27.0. inlined from contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: decltype(*std::declval<ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>().*std::declval<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)()>()()) std::__invoke[abi:se190107]<void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, void>(void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*&&)
27.1. inlined from contrib/llvm-project/libcxx/include/__thread/thread.h:192: void std::__thread_execute[abi:se190107]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*, 2ul>(std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>&, std::__tuple_indices<2ul>)
27. contrib/llvm-project/libcxx/include/__thread/thread.h:201: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000028bd3e7f
28. start_thread @ 0x00000000000a2ef1
29. __clone3 @ 0x000000000013445c
```

### PR DESCRIPTION
**Pull request by yariks5s**
Closes https://github.com/ClickHouse/ClickHouse/issues/82269

### Changelog category (leave one):
- Not for changelog

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix UBSan report when reading DateTime or Time types. Closes #82269.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.1.1.694`

### CODE REVIEW

**Review by pamarcos — COMMENTED** [review]
Code LGTM. 

The test is where I see issues. I don't understand why the stateless test is a .sh instead of a .sql. It's slower this way, and more error prone:

- The `tests/queries/0_stateless/03562_datetime_reading_overflow_check.sh` was added with 644 permissions, so neither the CI nor I can run it.
- Since the SET settings are per session, they're lost in the following `$CLICKHOUSE_CLIENT` calls, resulting in an error on the test:

```
Received exception from server (version 25.7.1):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create column with type 'FixedString(643)' because fixed string with size > 256 is suspicious. Set setting allow_suspicious_fixed_string_types = 1 i
n order to allow it. (ILLEGAL_COLUMN)
(query: CREATE TABLE t0 (c0 FixedString(643), c1 Int8, c2 Array(Nullable(UInt8)), c3 Decimal(70), c4 LowCardinality(UInt256), c5 DateTime) ENGINE = Memory)
[pablo-marcos-dev-vm] 2025.07.04 01:02:17.561178 [ 130665 ] {4fadfef0-c4c4-426f-9b24-2443a0624812} <Error> executeQuery: Code: 60. DB::Exception: Table test_a3w4raem.t0 does not exist. (UNKNOWN_TABLE) (version 25.7.1.1) (from
 127.0.0.1:58572) (comment: 03562_datetime_reading_overflow_check.sh) (query 1, line 1) (in query: INSERT INTO TABLE t0 (c5, c4, c3, c2, c1, c0) FROM INFILE '/home/ubuntu/ClickHouse/ClickHouse/tests/queries/0_stateless/data_c
sv/overflow_check.csv' SETTINGS input_format_parallel_parsing = 0, max_read_buffer_size = 8, input_format_allow_errors_num = 30 FORMAT CSV), Stack trace (when copying this message, always include the lines below):
```

I'd change the changelog entry to something more direct. From:

>In some cases, an integer overflow was possible while reading DateTime or Time types.

To something like

>Fix possible integer overflow when reading DateTime or Time types.

**Comment by yariks5s** [comment]
> I don't understand why the stateless test is a .sh instead of a .sql.

Because this test must read a CSV file, I didn't see any previous mentions of using user-created files in .sql tests. Maybe you know how to do it?




> The tests/queries/0_stateless/03562_datetime_reading_overflow_check.sh was added with 644 permissions, so neither the CI nor I can run it.

✅




> Since the SET settings are per session, they're lost in the following $CLICKHOUSE_CLIENT calls, resulting in an error on the test:

✅



> I'd change the changelog entry to something more though. From:
> 
> > In some cases, an integer overflow was possible while reading DateTime or Time types.
>
> To something like
> 
> > Fix possible integer overflow when reading DateTime or Time types.

✅

**Comment by pamarcos** [comment]
> Because this test must read a CSV file, I didn't see any previous mentions of using user-created files in .sql tests. Maybe you know how to do it?

Right, every usage of a user file I've seen in .sql files is from a file generated within the own test. [Example](https://github.com/ClickHouse/ClickHouse/blob/4feba31c916c944f0236e2b525abbc7ff702bc43/tests/queries/0_stateless/01545_url_file_format_settings.sql). I guess that unless it's very easy to generate your overflow csv, it's not worth to give this another though. We can use a shell script.

I took the freedom of fixing the test at https://github.com/ClickHouse/ClickHouse/pull/83212/commits/4f72506595ebdf1849ecab202485ffe1e44d0dea to trigger the CI aiming to merge this ASAP

**Review by pamarcos — APPROVED** [review]

**Comment by pamarcos** [comment]
@yariks5s the bugfix validation failed: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83212&sha=4f72506595ebdf1849ecab202485ffe1e44d0dea&name_0=PR&name_1=Bugfix+validation+%28functional+tests%29&name_2=Tests

As I understand it, this means the test is also successful on previous versions without your fix.

**Comment by yariks5s** [comment]
It was failing only with UBSan. I think that's the reason.

**Comment by pamarcos** [comment]
> It fails only with UBSan. I think that's the reason.

I don't think that's the case, cause I did run the test with 25.3.2.39 and it was successful. Have you tried running the test against clickhouse server from master?

**Comment by yariks5s** [comment]
It was failing for me and for Pedro for ch-client with UBSan: https://github.com/ClickHouse/ClickHouse/issues/82269. 


I just tried to run test with [this](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83296&sha=6bae3297d6de272f2f4bd9650b84f35a38ff7be0&name_0=PR) UBSan build, and it fails: https://pastila.nl/?0011a000/db5a4b8d4fe0387d14c8d9da55a30c5b#pFPzgqkewfoA0yBew2xeuA==

**Comment by pamarcos** [comment]
>It was failing only with UBSan. I think that's the reason.

Ah, you meant the binary was failing only when built with UBSan. Got it. I thought you meant the bugfix validation ran in UBSan or something and I was lost.

So, I get that the prior source code fails when fed with the [provided CSV ](https://github.com/user-attachments/files/20834759/table.csv) in UBSan. What the bugfix validation is checking is that the new version of the test is successful while the prior version (master) is not. To do that, you'd have to feed values that trigger the two new exceptions you added in your code. Or just ignore the bugfix validation check and override its status.

I think the CSV file provided doesn't make the server run through the new lines you added, otherwise you'd already be expecting the exceptions, right? I've built this PR, set breakpoints on the new code and ran the test without hitting any of them. So, either I'm missing something, or the code you've fixed is solving a different issue than the one that happened to Pedro on UBSan.

**Comment by yariks5s** [comment]
AFAIK, ReadHelpers.h is part of ClickHouse Client, not Server, so I think that's why breakpoints don't work. The failed stacktrace mentions that line of code I've fixed

**Comment by pamarcos** [comment]
> AFAIK, ReadHelpers.h is part of ClickHouse Client, not Server, so I think that's why breakpoints don't work.

That makes sense. It happens often times to me :sweat: 
I haven't been able to get the expected error when inserting from the CSV the same way the test does with `clickhouse local` either.

**Comment by yariks5s** [comment]
yep, test uses clickhouse client command

I think I can override the check and merge the PR?

**Comment by pamarcos** [comment]
> yep, test uses clickhouse client command

I have also tried to use the clickhouse client with breakpoints and didn't hit any.

> I think I can override the check and merge the PR?

I don't think the test is testing the new code you introduced, to be honest. But I'm more than happy to be proved wrong if you show me how you got your new code to be executed with that CSV file.

**Comment by pamarcos** [comment]
I downloaded the [UBSan clickhouse built from master](https://clickhouse-builds.s3.amazonaws.com/REFs/master/ddbff557d1101ef967b7ded342809c134f3172f7/build_amd_ubsan/clickhouse), ran the server and then the new `03562_datetime_reading_overflow_check` with that binary and indeed it got to the expected sanitizer trap as you said.

I did the same with the [UBSan clickhouse built from this PR](https://clickhouse-builds.s3.amazonaws.com/PRs/83212/4f72506595ebdf1849ecab202485ffe1e44d0dea/build_amd_ubsan/clickhouse) and it worked ok.

Again, I'm ok with the source code changes. What I'm pushing is for a proper test that ensures we test this properly on non-UBSan flavors. For instance, after seeing your changes, I'd expect the test to expect the new error at some point. In other words, I expected to see a `-- { clientError CANNOT_PARSE_DATETIME }` or some other way of checking that it went through your code (cause in case of no `throw_exception` it returns just false instead of throwing the error). That would also ensure the bugfix validation is happy with the test even if on non-UBSan flavors it was a silent error (undefined behavior to be more precise, but you know)

File: src/IO/ReadHelpers.cpp [hunk 1]
```diff
@@ -1737,7 +1747,17 @@ ReturnType readTimeTextFallback(time_t & time, ReadBuffer & buf, const DateLUTIm
                     if (!isNumericASCII(*digit_pos))
                         return false;
                 }
-                time = time * 10 + *digit_pos - '0';
+
+                /// Check for overflow before performing multiplication
+                static constexpr time_t max_div_10 = std::numeric_limits<time_t>::max() / 10;
+                if (time > max_div_10)
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.cpp]:
```suggestion
                if (unlikely(time > max_div_10))
```

File: src/IO/ReadHelpers.cpp [hunk 2]
```diff
@@ -1623,7 +1623,17 @@ ReturnType readDateTimeTextFallback(
                     if (!isNumericASCII(*digit_pos))
                         return false;
                 }
-                datetime = datetime * 10 + *digit_pos - '0';
+
+                /// Check for overflow before performing multiplication
+                static constexpr time_t max_div_10 = std::numeric_limits<time_t>::max() / 10;
+                if (datetime > max_div_10)
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.cpp]:
```suggestion
                if (unlikely(datetime > max_div_10))
```

File: src/IO/ReadHelpers.cpp [hunk 3]
```diff
@@ -1623,7 +1623,17 @@ ReturnType readDateTimeTextFallback(
...
+                /// Check for overflow before performing multiplication
+                static constexpr time_t max_div_10 = std::numeric_limits<time_t>::max() / 10;
+                if (unlikely(datetime > max_div_10))
+                {
+                    if constexpr (throw_exception)
+                        throw Exception(ErrorCodes::CANNOT_PARSE_DATETIME, "Too large value for DateTime");
+                    else
+                        return false;
+                }
+                datetime = datetime * 10 + (*digit_pos - '0');
```
Comment (alexey-milovidov) [inline src/IO/ReadHelpers.cpp]: But here are extra 9 positions that can overflow.

**Comment by alexey-milovidov** [comment]
I'd prefer to make the function NO_SANITIZE_UNDEFINED to avoid performance impact.
Otherwise the fix is very sparse - does not cover many other cases.

**Comment by alexey-milovidov** [comment]
Just in case, don't look at [PR / Bugfix validation (functional tests) (pull_request)](https://github.com/ClickHouse/ClickHouse/actions/runs/21154904236/job/60837897841?pr=83212) right now - it is entirely broken, and @maxknv will do something about it.

**Review by alexey-milovidov — APPROVED** [review]
LGTM

**Comment by yariks5s** [comment]
[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83212&sha=1de91cd52394a7195079572cd6425d021d4e3dca&name_0=PR&name_1=BuzzHouse+%28amd_debug%29) -- https://github.com/ClickHouse/ClickHouse/issues/93861

[AST fuzzer (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=83212&sha=1de91cd52394a7195079572cd6425d021d4e3dca&name_0=PR&name_1=AST+fuzzer+%28amd_ubsan%29) -- https://github.com/ClickHouse/ClickHouse/issues/92845
