### PR TITLE
Insert QueryFinish on AsyncInsertFlush with no data

### LINKED ISSUE #63007: query_log has no exceptions logged for asynchronous inserts
#51160 introduced events from `asynchronous_insert_log` into `query_log` which is very nice!

Unfortunately if exception happens at the flush time that exception is not logged to the `query_log`
It's still logged to `asynchronous_insert_log` though, which is good, but it limits the usage of `query_log` for async insert monitoring.

To repro:
```sql
create table t1 (id UInt32, ts DateTime64) engine = MergeTree order by tuple();
insert into t1 settings async_insert = 1, wait_for_async_insert = 0, async_insert_busy_timeout_ms = 1000 format Values (1, '9th November 2024 09:15')
```

The entry will be present in `asynchronous_insert_log`:
```
exception:               DB::Exception: Cannot parse string '9th November 2023 09:15' as DateTime64(3): syntax error at position 10 (parsed just '9th Novemb'): while executing 'FUNCTION if(isNull(_dummy_0) : 3, defaultValueOfTypeName('DateTime64(3)') :: 2, _CAST(_dummy_0, 'DateTime64(3)') :: 4) -> if(isNull(_dummy_0), defaultValueOfTypeName('DateTime64(3)'), _CAST(_dummy_0, 'DateTime64(3)')) DateTime64(3) : 1'
```
But in `query_log` the entry for `query_kind = 'AsyncInsertFlush' and type = 'QueryFinish'` will not be logged. 

version tested: 24.1.5.6

cc: @Algunenano

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- Insert QueryFinish on AsyncInsertFlush with no data

### Documentation entry for user-facing changes

Some bug fixes around async insert:
* When all the data was discarded in a batch for async insert, we logged QueryStart but not QueryFinish. We also didn't refresh `queue_shard_flush_time_history`. Now we log QueryFinish (with 0 rows) and refresh the timer.
* Populate `system.asynchronous_query_log.flush_query_id` for all elements, including those that were not pushed due to errors. This simplifies looking into what happened with a batch, without knowing the initial query_id.

Closes https://github.com/ClickHouse/ClickHouse/issues/63007

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit c99f15a843fb8cae05a111f90b185433224481ae with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63483/c99f15a843fb8cae05a111f90b185433224481ae/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

**Review by antaljanosbenjamin — APPROVED** [review]

File: tests/queries/0_stateless/03148_async_queries_in_query_log_errors.sh [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+          SELECT
+              database,
+              table,
+              query,
+              format,
+              extract(replace(exception::String, 'Exception', 'Exc*****on'), '.*UInt32:') as error,
+              not empty(flush_query_id) as populated_flush_query_id
+          FROM system.asynchronous_insert_log
+          WHERE
+              event_date >= yesterday()
```
Comment (pkit) [inline tests/queries/0_stateless/03148_async_queries_in_query_log_errors.sh:23]: It's probably better to use `now() - INTERVAL 24 HOUR` otherwise the tests will flake when run at midnight...

Comment (Algunenano) [reply tests/queries/0_stateless/03148_async_queries_in_query_log_errors.sh:23]: Notice it's `>= yesterday()` (the **>=** is the important part). So it's always covering at least 24 hours, normally more.

Comment (Algunenano) [reply tests/queries/0_stateless/03148_async_queries_in_query_log_errors.sh:23]: Don't worry. You can find the same condition in many other tests, so I'm used to writing and seeing it.
