### PR TITLE
Fix possible name collision in calculation of DEFAULT expression.

### LINKED ISSUE #9359: Bug with CREATE query default expression
**How to reproduce**

``` sql
CREATE TABLE test(test String DEFAULT 'test', test_tmp Int DEFAULT 1)ENGINE = Memory;
```

related #8429
I will fixes it.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Calculation of `DEFAULT` expressions was involving possible name collisions (that was very unlikely to encounter). This fixes #9359

### CODE REVIEW

**Review by alesapin — APPROVED** [review]

File: tests/queries/0_stateless/01093_cyclic_defaults_filimonov.sql [hunk 1]
```diff
@@ -1,7 +1,7 @@
 CREATE TABLE test
 (
-    `a1` UInt64 DEFAULT a + 1,
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01093_cyclic_defaults_filimonov.sql:3]: Interesting, how it was possible to create this table? Maybe identical columns just collapsed?

Comment (alesapin) [reply tests/queries/0_stateless/01093_cyclic_defaults_filimonov.sql:3]: It was not possible https://github.com/ClickHouse/ClickHouse/pull/16612/files#diff-bc57ecabc455a3cc24084ccda135da53206df9e520bbe2203c42312f34f1b527R9

**Comment by alesapin** [comment]
Tests ok (failures are known)
