### PR TITLE
Fix bad creation of sparse columns during mutation

### LINKED ISSUE #92633: Flaky test: 02319_lightweight_delete_on_merge_tree
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: 02319_lightweight_delete_on_merge_tree
Failure reason: result differs with reference
CI report: [Stateless tests (amd_debug, AsyncInsert, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91844&sha=f1653a0cc5986994bfda83a70fdd222229ffbd29&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20AsyncInsert%2C%20s3%20storage%2C%20parallel%29)

CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMjMxOV9saWdodHdlaWdodF9kZWxldGVfb25fbWVyZ2VfdHJlZScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0YXRlbGVzcyB0ZXN0cyAoYW1kX2RlYnVnLCBBc3luY0luc2VydCwgczMgc3RvcmFnZSwgcGFyYWxsZWwpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK)

Test output:
```
2025-12-19 10:04:06 Reason: result differs with reference:  
2025-12-19 10:04:06 --- /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02319_lightweight_delete_on_merge_tree.reference	2025-12-19 09:54:18.737515223 +0500
2025-12-19 10:04:06 +++ /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02319_lightweight_delete_on_merge_tree.stdout	2025-12-19 10:04:06.450120809 +0500
2025-12-19 10:04:06 @@ -4,32 +4,32 @@
2025-12-19 10:04:06  1
2025-12-19 10:04:06  0
2025-12-19 10:04:06  1
2025-12-19 10:04:06  -----lightweight mutation type-----
2025-12-19 10:04:06  1
2025-12-19 10:04:06  1
2025-12-19 10:04:06  1
2025-12-19 10:04:06  (UPDATE _row_exists = 0 WHERE (c % 5) = 1)	1
2025-12-19 10:04:06  (UPDATE _row_exists = 0 WHERE c = 4)	1
2025-12-19 10:04:06  (MATERIALIZE INDEX i_c)	1
2025-12-19 10:04:06 -(UPDATE b = -1 WHERE a < 3)	1
2025-12-19 10:04:06 -(DROP INDEX i_c)	1
2025-12-19 10:04:06 +(UPDATE b = -1 WHERE a < 3)	0
2025-12-19 10:04:06 +(DROP INDEX i_c)	0
2025-12-19 10:04:06  -----Check that select and merge with lightweight delete.-----
2025-12-19 10:04:06  7
2025-12-19 10:04:06 -0	-1	0
2025-12-19 10:04:06 +0	0	0
2025-12-19 10:04:06  2	-1	2
2025-12-19 10:04:06  3	3	3
2025-12-19 10:04:06  5	5	5
2025-12-19 10:04:06  7	7	7
2025-12-19 10:04:06  8	8	8
2025-12-19 10:04:06  9	9	9
2025-12-19 10:04:06 -t_light	0	0_1_1_0_10	2
2025-12-19 10:04:06 +t_light	0	0_1_1_0_8	2
2025-12-19 10:04:06  t_light	1	1_2_2_0_10	2
2025-12-19 10:04:06  t_light	2	2_3_3_0_10	2
2025-12-19 10:04:06  t_light	3	3_4_4_0_10	2
2025-12-19 10:04:06  t_light	4	4_5_5_0_10	2
2025-12-19 10:04:06  7
2025-12-19 10:04:06  t_light	0	0_1_1_1_10	2
2025-12-19 10:04:06  t_light	2	2_3_3_1_10	2
2025-12-19 10:04:06  t_light	3	3_4_4_1_10	2
2025-12-19 10:04:06  t_light	4	4_5_5_1_10	1
2025-12-19 10:04:06  -----Test lightweight delete in multi blocks-----
2025-12-19 10:04:06 
2025-12-19 10:04:06 
2025-12-19 10:04:06 
2025-12-19 10:04:06 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 7505773205 --vertical_merge_algorithm_min_rows_to_activate 847878 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1 --index_granularity_bytes 3503798 --merge_max_block_size 21863 --index_granularity 27384 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 48952 --primary_key_compress_block_size 15890 --replace_long_file_name_to_hash 0 --max_file_name_length 128 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 92788809 --compact_parts_max_granules_to_buffer 98 --compact_parts_merge_max_bytes_to_prefetch_part 16544586 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 100 --old_parts_lifetime 480 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 0 --object_serialization_version v3 --object_shared_data_serialization_version map_with_buckets --object_shared_data_serialization_version_for_zero_level_parts map_with_buckets --object_shared_data_buckets_for_compact_part 16 --object_shared_data_buckets_for_wide_part 29 --dynamic_serialization_version v2 --auto_statistics_types uniq,tdigest,countmin --serialization_info_version with_types --string_serialization_version with_size_stream --nullable_serialization_version basic --enable_shared_storage_snapshot_in_query 1
2025-12-19 10:04:06 
2025-12-19 10:04:06 Database: test_zledkslr
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix possible error `FILE_DOESNT_EXIST` after mutation of a sparse column with `ratio_of_defaults_for_sparse_serialization=0.0`. Closes https://github.com/ClickHouse/ClickHouse/issues/92633

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Storages/MergeTree/MutateTask.cpp [hunk 1]
```diff
@@ -586,12 +586,21 @@ getColumnsForNewDataPart(
     }
 
     SerializationInfo::Settings settings;
-    /// If mutations doesn't affect all columns we must use serialization info settings from source part,
+    /// If mutations doesn't affect all columns we must i serialization info settings from source part,
```
Comment (amosbird) [inline src/Storages/MergeTree/MutateTask.cpp]: This looks unintended to me

Comment (Avogar) [reply src/Storages/MergeTree/MutateTask.cpp]: Yes, thanks for noticing

File: tests/queries/0_stateless/03774_wide_part_mutation_sparse_ratio_setting_bug.sql [hunk 2]
```diff
@@ -0,0 +1,14 @@
+drop table if exists test;
+create table test (a UInt32, b UInt32) engine=MergeTree order by tuple() settings min_bytes_for_wide_part=0, ratio_of_defaults_for_sparse_serialization=0.0;
```
Comment (azat) [inline tests/queries/0_stateless/03774_wide_part_mutation_sparse_ratio_setting_bug.sql]:
```suggestion
create table test (a UInt32, b UInt32) engine=MergeTree order by tuple() settings min_bytes_for_wide_part=0, ratio_of_defaults_for_sparse_serialization=0.0, max_suspicious_broken_parts=0, max_suspicious_broken_parts_bytes=0;
```

Looks like the test relies on the fact that w/o the fix new parts will be broken ad won't be attached, so you may get old result, better to do this expliciclty that way you will get proper error - https://pastila.nl/?0366a32d/d78a329550444c54f3f67e5512972ae0#9Fo8v8G6QBqAGxLcqCmkgg==

File: src/Storages/MergeTree/MutateTask.cpp [hunk 3]
```diff
@@ -591,7 +591,14 @@ getColumnsForNewDataPart(
     /// settings will not be applied for them (for example, new serialization versions for data types).
     if (!affects_all_columns)
     {
-        settings = serialization_infos.getSettings();
+        settings = SerializationInfo::Settings
+        {
+            (*source_part->storage.getSettings())[MergeTreeSetting::ratio_of_defaults_for_sparse_serialization],
```
Comment (azat) [inline src/Storages/MergeTree/MutateTask.cpp:596]: Also why `serialization_infos.getSettings().ratio_of_defaults_for_sparse` initialized with default value (`1`)? Maybe this should be fixed instead?

Comment (Avogar) [reply src/Storages/MergeTree/MutateTask.cpp:596]: > Also why serialization_infos.getSettings().ratio_of_defaults_for_sparse initialized with default value (1)?

I think to disable Sparse serialization if default settings are used. Maybe just for historical reasons.

> Maybe this should be fixed instead?

The main thing here is that `serialization_infos.getSettings().ratio_of_defaults_for_sparse` will be default always, because we don't serialize this value in `serializations.json` and during deserialization of it from source part we always use default value. So we need to use value from storage settings always.

Comment (azat) [reply src/Storages/MergeTree/MutateTask.cpp:596]: Thanks, make sense.
Maybe it make sense to initialize this value from storage for now?

**Review by azat — APPROVED** [review]

File: src/Storages/MergeTree/MutateTask.cpp (hunk 3 above)
Comment (azat) [reply src/Storages/MergeTree/MutateTask.cpp:596]: But for bug-fix better to keep patches short, so LGTM

Comment (Avogar) [reply src/Storages/MergeTree/MutateTask.cpp:596]: > Maybe it make sense to initialize this value from storage for now?

What do you mean? Propagate value from storage to SerializationInfo deserialization, so we initialize it always with the correct value?

Comment (azat) [reply src/Storages/MergeTree/MutateTask.cpp:596]: >Propagate value from storage to SerializationInfo deserialization, so we initialize it always with the correct value?

Yes

Comment (Avogar) [reply src/Storages/MergeTree/MutateTask.cpp:596]: Well, I am not sure about it. `ratio_of_defaults_for_sparse` is used only in serialization, not deserialization. And before serialization we usually set fresh values for all settings from the storage settings (as it was here before and as it's done for merge and new parts creation). So ideally we should not use the value of `ratio_of_defaults_for_sparse` from deserialized `SerializationInfo`. It was used here because of my mistake only.

**Comment by azat** [comment]
Hm, but it can be not only wide parts right? For instance indexes stored as a separate column in compact parts, so after `delete index` mutation for compact parts we can also have this problem, correct?

**Comment by Avogar** [comment]
> Hm, but it can be not only wide parts right? For instance indexes stored as a separate column in compact parts, so after delete index mutation for compact parts we can also have this problem, correct?

Sounds like yes

**Comment by Avogar** [comment]
Actually, this is incorrect fix. It just hides the real bug. And https://github.com/ClickHouse/ClickHouse/pull/92419 didn't introduce it, it just uncovered it using the test `02319_lightweight_delete_on_merge_tree`.

https://fiddle.clickhouse.com/e89aeaeb-200d-45c6-9649-e8d70ca2dc71

The problem is: if updated column in source part is Sparse, but in the mutated part is not Sparse (for example due to changed setting to `1.0` that disables sparse serialization), the `checksums.txt` file of mutated part will still contain files with sparse serialization for some reason (I guess because we copied checksums and didn't updated it or something like that). I will investigate it futher
