### PR TITLE
Avoid throwing ABORTED on normal situations

### LINKED ISSUE #51543: [Master] ATTEMPT_TO_READ_AFTER_EOF / ABORTED errors on table drop
Since a few days ago, running master/HEAD leads to new errors being reported (in system.errors and also in logs) when dropping a replicated table, apparently because concurrent fetches are being cancelled.

Sample script (it creates a table with several parts and drops it):

```bash
#!/bin/bash

CLUSTER="tinybird"
HOSTNAME="clickhouse-01"
PORT="49000"

__query()
{
    clickhouse client -h $HOSTNAME --port $PORT --query "$1"
}


__query "DROP DATABASE IF EXISTS test ON CLUSTER $CLUSTER SYNC;"
__query "CREATE DATABASE test ON CLUSTER $CLUSTER;"

for i in {1..100};
do
    echo $i
    __query "
        CREATE TABLE test.test$i ON CLUSTER $CLUSTER (date DateTime('UTC'), city String)
                        ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/test.test$i', '{replica}')
                        PARTITION BY toYear(date)
                        ORDER BY (date, city) TTL date + toIntervalDay(1)" > /dev/null || break;
    __query "INSERT INTO test.test$i Select now(), 'Madrid' from numbers(100000) settings max_insert_block_size=10000"
    __query "DROP TABLE test.test$i ON CLUSTER $CLUSTER SYNC" > /dev/null || break;
done

__query "Select shardNum(), version(), value, name from clusterAllReplicas('$CLUSTER', 'system.errors')"
__query "DROP DATABASE IF EXISTS test ON CLUSTER $CLUSTER SYNC;"
```

In 23.3, 23.4 and 23.5 you don't see any errors.

In master/HEAD:
```
1       23.6.1.1        1200    ABORTED
2       23.6.1.1        1200    ABORTED
```

Some logs accompany them:
```
jun 28 17:10:49 Mordor clickhouse[468213]: 2023.06.28 15:10:49.253362 [ 468314 ] {} <Debug> MergeTreeBackgroundExecutor: Code: 236. DB::Exception: Storage is about to be deleted. Done pending task as if it was aborted. (ABORTED)
jun 28 17:10:49 Mordor clickhouse[468213]: 2023.06.28 15:10:49.253390 [ 468518 ] {8302ec33-4624-42cd-9c7d-dac2c9c6bacf} <Debug> DDLWorker: Executed query: /* ddl_entry=query-0000268609 */ DROP TABLE test.test3 SYNC
jun 28 17:10:49 Mordor clickhouse[468213]: 2023.06.28 15:10:49.253435 [ 468518 ] {8302ec33-4624-42cd-9c7d-dac2c9c6bacf} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
jun 28 17:10:49 Mordor clickhouse[468213]: 2023.06.28 15:10:49.253442 [ 468314 ] {} <Debug> MergeTreeBackgroundExecutor: Code: 236. DB::Exception: Storage is about to be deleted. Done pending task as if it was aborted. (ABORTED)
jun 28 17:10:49 Mordor clickhouse[468213]: 2023.06.28 15:10:49.253526 [ 468314 ] {} <Debug> MergeTreeBackgroundExecutor: Code: 236. DB::Exception: Storage is about to be deleted. Done pending task as if it was aborted. (ABORTED)
jun 28 17:10:49 Mordor clickhouse[468213]: 2023.06.28 15:10:49.253592 [ 468314 ] {} <Debug> MergeTreeBackgroundExecutor: Code: 236. DB::Exception: Storage is about to be deleted. Done pending task as if it was aborted. (ABORTED)
```

And ocasionaly you might see something like this too (although I'm not 100% sure it comes from the same set of changes):
```
Row 1:
──────
server_shard:       2
version:            23.5.3.24
name:               ATTEMPT_TO_READ_AFTER_EOF
code:               32
quantity:           1
last_error_message: Attempt to read after EOF.
traceback:          DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)
DB::DataPartsExchange::Fetcher::downloadBaseOrProjectionPartToDisk(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IDataPartStorage> const&, DB::PooledReadWriteBufferFromHTTP&, std::__1::function<std::__1::unique_ptr<DB::WriteBufferFromFileBase, std::__1::default_delete<DB::WriteBufferFromFileBase>> (DB::IDataPartStorage&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long)>, DB::MergeTreeDataPartChecksums&, std::__1::shared_ptr<DB::Throttler>, bool) const
DB::DataPartsExchange::Fetcher::downloadPartToDisk(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::IDisk>, bool, DB::PooledReadWriteBufferFromHTTP&, std::__1::function<std::__1::unique_ptr<DB::WriteBufferFromFileBase, std::__1::default_delete<DB::WriteBufferFromFileBase>> (DB::IDataPartStorage&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long)>, unsigned long, std::__1::shared_ptr<DB::Throttler>, bool)
DB::DataPartsExchange::Fetcher::fetchSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Throttler>, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::optional<DB::CurrentlySubmergingEmergingTagger>*, bool, std::__1::shared_ptr<DB::IDisk>)
DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>, bool)
DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool)
DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&)
DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)
DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>)
DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>)
DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction()
ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>)
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*)
ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)
Please review these new errors and fix them
```

This new behaviour appears to have been introduced in https://github.com/ClickHouse/ClickHouse/pull/50395. cc @CheSema 

If this new behaviour is expected, I hope we can get rid of both the reports to system.errors and the logging.

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

Throwing `ErrorCodes::ABORTED` means errors get added to system.errors, which is wrong for expected behaviour. Moreover, this is only necessary to workaround an internal check. Using std::exception does not count anything in system.errors.

cc @CheSema 
Closes https://github.com/ClickHouse/ClickHouse/issues/51543

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 5f183649b2e54e3e20bfab8bcbce637aa282ab90 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/58252/5f183649b2e54e3e20bfab8bcbce637aa282ab90/ci_running.html) to open a full report in a separate page

<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/58252/5f183649b2e54e3e20bfab8bcbce637aa282ab90/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by alexey-milovidov** [comment]
I'm curious: why do we count all exceptions in `system.errors` instead of only exceptions that were unhandled before being logged or reported to the user?

File: src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp [hunk 1]
```diff
@@ -186,7 +186,8 @@ void MergeTreeBackgroundExecutor<Queue>::removeTasksCorrespondingToStorage(Stora
         try
         {
             /// An exception context is needed to proper delete write buffers without finalization
-            throw Exception(ErrorCodes::ABORTED, "Storage is about to be deleted. Done pending task as if it was aborted.");
+            /// See WriteBuffer::~WriteBuffer for more context
+            throw std::runtime_error("");
```
Comment (alexey-milovidov) [inline src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:190]: It looks like a hack. At least keep the message.

**Review by alexey-milovidov — APPROVED** [review]
