### PR TITLE
Fix reading subcolumns from a column with dot in the name in some cases

### LINKED ISSUE #81261: JSON subcolumns reading doesn't work with VIEW over a distributed table with 2+ shards
### Company or project name

CMSS

### Question

Does `Parameterized View` not support [JSON Data Type](https://clickhouse.com/docs/sql-reference/data-types/newjson) ?

My `JSON` related settings is:

```text
SELECT
    name,
    value
FROM system.settings
WHERE name LIKE '%json%'

Query id: 30ab34f7-4ead-489c-a1e2-38593f5e0e73

Row 1:
──────
name:  allow_simdjson
value: 1

Row 2:
──────
name:  function_json_value_return_type_allow_nullable
value: 0

Row 3:
──────
name:  function_json_value_return_type_allow_complex
value: 0

Row 4:
──────
name:  use_json_alias_for_old_object_type
value: 0

Row 5:
──────
name:  allow_experimental_json_type
value: 1

Row 6:
──────
name:  enable_json_type
value: 1

Row 7:
──────
name:  input_format_import_nested_json
value: 0

Row 8:
──────
name:  input_format_json_compact_allow_variable_number_of_columns
value: 0

Row 9:
───────
name:  schema_inference_make_json_columns_nullable
value: 0

Row 10:
───────
name:  input_format_json_read_bools_as_numbers
value: 1

Row 11:
───────
name:  input_format_json_read_bools_as_strings
value: 1

Row 12:
───────
name:  input_format_json_try_infer_numbers_from_strings
value: 0

Row 13:
───────
name:  input_format_json_validate_types_from_metadata
value: 1

Row 14:
───────
name:  input_format_json_read_numbers_as_strings
value: 1

Row 15:
───────
name:  input_format_json_read_objects_as_strings
value: 1

Row 16:
───────
name:  input_format_json_read_arrays_as_strings
value: 1

Row 17:
───────
name:  input_format_json_try_infer_named_tuples_from_objects
value: 1

Row 18:
───────
name:  input_format_json_use_string_type_for_ambiguous_paths_in_named_tuples_inference_from_objects
value: 0

Row 19:
───────
name:  input_format_json_infer_incomplete_types_as_strings
value: 1

Row 20:
───────
name:  input_format_json_named_tuples_as_objects
value: 1

Row 21:
───────
name:  input_format_json_ignore_unknown_keys_in_named_tuple
value: 1

Row 22:
───────
name:  input_format_json_defaults_for_missing_elements_in_named_tuple
value: 1

Row 23:
───────
name:  input_format_json_throw_on_bad_escape_sequence
value: 1

Row 24:
───────
name:  input_format_json_ignore_unnecessary_fields
value: 1

Row 25:
───────
name:  type_json_skip_duplicated_paths
value: 0

Row 26:
───────
name:  input_format_json_max_depth
value: 1000

Row 27:
───────
name:  input_format_json_empty_as_default
value: 0

Row 28:
───────
name:  output_format_native_write_json_as_string
value: 0

Row 29:
───────
name:  input_format_binary_read_json_as_string
value: 0

Row 30:
───────
name:  output_format_binary_write_json_as_string
value: 0

Row 31:
───────
name:  output_format_json_quote_64bit_integers
value: 1

Row 32:
───────
name:  output_format_json_quote_denormals
value: 0

Row 33:
───────
name:  output_format_json_quote_decimals
value: 0

Row 34:
───────
name:  output_format_json_quote_64bit_floats
value: 0

Row 35:
───────
name:  output_format_json_escape_forward_slashes
value: 1

Row 36:
───────
name:  output_format_json_named_tuples_as_objects
value: 1

Row 37:
───────
name:  output_format_json_skip_null_value_in_named_tuples
value: 0

Row 38:
───────
name:  output_format_json_array_of_rows
value: 0

Row 39:
───────
name:  output_format_json_validate_utf8
value: 0

Row 40:
───────
name:  output_format_json_pretty_print
value: 1

Row 41:
───────
name:  format_json_object_each_row_column_for_object_name
value:
```

I have a MergeTree Table and a Distributed Table.

MergeTree Table:

```sql
CREATE TABLE table_local
(
    BucketName String,
    LogAttributes JSON
)
ORDER BY BucketName
```

Distributed Table:

```sql
CREATE TABLE table_all
(
    BucketName String,
    LogAttributes JSON
)
ENGINE = Distributed('mycluster', 'default', 'table_local', rand())
```

And I have a Parameterized View:

```sql
CREATE VIEW default.table_pv
AS (SELECT
    BucketName,
    CAST(LogAttributes.http_user_agent, 'String') AS http_user_agent,
    CAST(LogAttributes.request, 'String') AS request,
    CAST(LogAttributes.status, 'UInt16') AS status,
    CAST(LogAttributes.http_method, 'String') AS http_method
FROM default.table_all AS tb
WHERE
    if(length({bucket_names:Array(String)}) = 0, 1, tb.BucketName IN ({bucket_names:Array(String)}))
ORDER BY
    BucketName ASC)
```

Then I exec SQL:

```sql
SELECT BucketName, COUNT(*) AS "error_count" FROM default.table_pv(bucket_names = ['new-bucket-cf930a0a1']) WHERE status != 200 GROUP BY BucketName ORDER BY error_count DESC FORMAT JSON
```

It throw error:

```text
"exception": "Code: 47. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Unknown expression or function identifier `LogAttributes.status` in scope SELECT __table1.BucketName AS BucketName, CAST(__table1.`LogAttributes.status`, 'UInt16') AS status FROM default.table_local AS __table1 WHERE (__table1.BucketName IN _CAST(['new-bucket-cf930a0a1'], 'Array(String)')) HAVING materialize(CAST(`LogAttributes.status`, 'UInt16')) != _CAST(200, 'UInt8') ORDER BY BucketName ASC, __table1.AccesserRowId ASC. Maybe you meant: ['LogAttributes']. (UNKNOWN_IDENTIFIER) (version 25.4.1.2934 (official build))
```

I manually executed the following SQL, and it also reported the same error.

```sql
SELECT __table1.BucketName AS BucketName, CAST(__table1.`LogAttributes.status`, 'UInt16') AS status FROM default.table_local AS __table1 WHERE (__table1.BucketName IN _CAST(['new-bucket-cf930a0a1'], 'Array(String)')) HAVING materialize(CAST(`LogAttributes.status`, 'UInt16')) != _CAST(200, 'UInt8') ORDER BY BucketName ASC, __table1.AccesserRowId ASC
```

But I modify
```sql
HAVING materialize(CAST(`LogAttributes.status`, 'UInt16')) != _CAST(200, 'UInt8')
```
to
```sql
HAVING materialize(CAST(__table1.`LogAttributes.status`, 'UInt16')) != _CAST(200, 'UInt8')
```
, it is OK:

```sql
SELECT __table1.BucketName AS BucketName, CAST(__table1.`LogAttributes.status`, 'UInt16') AS status FROM default.table_local AS __table1 WHERE (__table1.BucketName IN _CAST(['new-bucket-cf930a0a1'], 'Array(String)')) HAVING materialize(CAST(__table1.`LogAttributes.status`, 'UInt16')) != _CAST(200, 'UInt8') ORDER BY BucketName ASC, __table1.AccesserRowId ASC
```

My question is: The `HAVING ` statement is not add by me. Is there a problem in this place, and is it incompatible with JSON?

The ClickHouse version is 25.4.1.2934 (revision: 54497, git hash: 589918f385fc3dc208a4de06563956f9ce0f804e, build id: 8D14AB5D5A4B2060FEC5E79611CDF6CF7178B790).

Thanks!

### LINKED ISSUE #82058: Length-property of sub-columns does not work correctly with views after 25.4
### Company or project name

_No response_

### Describe what's wrong

The length-property of sub-columns does not seem to work correctly for 25.4 and upwards when queried through views:

Seems related to `optimize_functions_to_subcolumns`.

https://fiddle.clickhouse.com/35f64faf-c5f9-48d8-8325-4ead10db3b88

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```sql
CREATE OR REPLACE TABLE t (
  `x` Array(LowCardinality(String)),
  `y.id` Array(LowCardinality(String))
)
ENGINE = MergeTree()
ORDER BY ()
;

CREATE OR REPLACE VIEW v AS SELECT * FROM t;

-- Works
SELECT MAX(LENGTH(x)) FROM t;
SELECT MAX(LENGTH(x)) FROM v;
SELECT MAX(LENGTH(y.id)) FROM t;
SELECT MAX(LENGTH(y.id)) FROM v SETTINGS optimize_functions_to_subcolumns = 0;

-- Does not work
SELECT MAX(LENGTH(y.id)) FROM v;
```

### Expected behavior

Functioning query.

### Error message and/or stacktrace

```sql
Received exception from server (version 25.5.2):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Unknown expression identifier `y.id.size0` in scope SELECT y.id.size0 FROM (SELECT * FROM default.t). Maybe you meant: ['y.id.size0']. (UNKNOWN_IDENTIFIER)
(query: -- Does not work
SELECT MAX(LENGTH(y.id)) FROM v;)
```

### Additional context

_No response_

### LINKED ISSUE #88169: NOT_FOUND_COLUMN_IN_BLOCK with `exclude_materialize_skip_indexes_on_insert`
### Describe the bug

Not sure if a real issue or not. Referencing `size0` from a Nested subcolumn at an index definition is making a mutation stuck in an infinite loop later.

### How to reproduce

Run:
```sql
CREATE TABLE t0 (c0 Nested(c1 Int), INDEX i0 `c0.c1.size0` TYPE set(1)) ENGINE = MergeTree() ORDER BY tuple();
SET exclude_materialize_skip_indexes_on_insert = 'i0';
INSERT INTO TABLE t0 (`c0.c1`) SELECT [1] FROM numbers(1);
INSERT INTO TABLE t0 (`c0.c1`) SELECT [1] FROM numbers(1);
INSERT INTO TABLE t0 (`c0.c1`) SELECT [1] FROM numbers(1);
INSERT INTO TABLE t0 (`c0.c1`) SELECT [1] FROM numbers(1);
INSERT INTO TABLE t0 (`c0.c1`) SELECT [1] FROM numbers(1);
INSERT INTO TABLE t0 (`c0.c1`) SELECT [];
DELETE FROM t0 WHERE TRUE; --mutation stuck on the background
```

### Error message and/or stacktrace

Stack trace:
```
<Error> MergeTreeBackgroundExecutor: Exception while executing background task {db5acb59-bf1e-45de-bf12-1c11f0e563f9::all_1_5_1}: Code: 10. DB::Exception: Not found column c0.c1.size0: in block c0.c1 Array(Int32) Array(size = 0, UInt64(size = 0), Int32(size = 0)). (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000002770a8b2
1. src/Common/Exception.cpp:128: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000014a23c69
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d31930e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d318d11
4. src/Common/Exception.h:141: DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000e59f2f6
5. src/Interpreters/ActionsDAG.cpp:1028: DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, unsigned long, bool, bool) @ 0x000000001ae81e6c
6. src/Interpreters/ActionsDAG.cpp:932: DB::ActionsDAG::updateHeader(DB::Block const&) const @ 0x000000001ae803d2
7. src/Processors/Transforms/ExpressionTransform.cpp:12: DB::ExpressionTransform::transformHeader(DB::Block const&, DB::ActionsDAG const&) @ 0x000000001fa3bf92
8. src/Processors/QueryPlan/ExpressionStep.cpp:38: DB::ExpressionStep::ExpressionStep(std::shared_ptr<DB::Block const>, DB::ActionsDAG) @ 0x000000001fc8e34b
9. contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:634: std::__unique_if<DB::ExpressionStep>::__unique_single std::make_unique[abi:se190107]<DB::ExpressionStep, std::shared_ptr<DB::Block const> const&, DB::ActionsDAG>(std::shared_ptr<DB::Block const> const&, DB::ActionsDAG&&) @ 0x0000000019ddc21d
10. src/Storages/MergeTree/MergeTask.cpp:2125: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() const @ 0x000000001eef4556
11. src/Storages/MergeTree/MergeTask.cpp:686: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() const @ 0x000000001eeede53
12. src/Storages/MergeTree/MergeTask.cpp:826: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x000000001eef6499
13. src/Storages/MergeTree/MergeTask.cpp:1658: DB::MergeTask::execute() @ 0x000000001eefd236
14. src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:58: DB::MergePlainMergeTreeTask::executeStep() @ 0x000000001ef6b34e
15. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:305: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x000000001ef2a2b5
16. src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:369: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001ef2adc2
17. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000014b66f53
18. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000014b6d626
19. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000014b643e6
20. contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000014b6ae00
21. start_thread @ 0x00000000000a27f1
22. __clone3 @ 0x0000000000133b5c
```

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix reading subcolumns from a column with dot in the name in some cases. Resolves #81261, #82058, #88169

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Details

Resolves #81261.
Resolves #82058.
Resolves https://github.com/ClickHouse/ClickHouse/issues/88169.

### Version info
- Backported to: `25.11.7.14`, `25.10.5.16`, `25.8.15.13`, `25.3.14.4`

### CODE REVIEW

**Comment by Avogar** [comment]
Let's check if any test will fail

**Comment by Avogar** [comment]
Tests look ok

File: src/Storages/MergeTree/MergeTask.cpp [hunk 1]
```diff
@@ -322,19 +333,42 @@ void MergeTask::ExecuteAndFinalizeHorizontalPart::extractMergingAndGatheringColu
...
+                {
+                    for (auto [storage_column_name, _] : Nested::getAllColumnAndSubcolumnPairs(index_column))
+                    {
+                        if (storage_columns.contains(String(storage_column_name)))
+                        {
+                            key_columns.insert(String(storage_column_name));
+                            break;
+                        }
+                    }
+                }
```
Comment (george-larionov) [inline src/Storages/MergeTree/MergeTask.cpp]: Suggestion: (instead of the if/else)
```
for (const auto & index_column : index_columns)
{
    if (storage_columns.contains(index_column))
    {
        if (index_columns.size() == 1)
            global_ctx->skip_indexes_by_column[index_column].push_back(index);
        else
            key_columns.insert(index_column);
    }
    /// If we don't have this column in storage columns, it must be a subcolumn of one of the storage columns.
    else
    {
        for (auto [storage_index_column, _] : Nested::getAllColumnAndSubcolumnPairs(index_column))
        {
            if (storage_columns.contains(String(storage_index_column)))
            {
                if (index_columns.size() == 1)
                    global_ctx->skip_indexes_by_column[String(storage_index_column)].push_back(index);
                else
                    key_columns.insert(String(storage_index_column));

                break;
            }
        }
    }
}

if (index_columns.size() == 1)
    global_ctx->merging_skip_indexes.push_back(index);
```

File: src/Storages/ColumnsDescription.cpp [hunk 2]
```diff
@@ -635,12 +635,14 @@ bool ColumnsDescription::hasSubcolumn(const String & column_name) const
...
     /// Check for dynamic subcolumns
-    auto [ordinary_column_name, dynamic_subcolumn_name] = Nested::splitName(column_name);
-    auto it = columns.get<1>().find(ordinary_column_name);
-    if (it != columns.get<1>().end() && it->type->hasDynamicSubcolumns() && !dynamic_subcolumn_name.empty())
+    for (auto [ordinary_column_name, dynamic_subcolumn_name] : Nested::getAllColumnAndSubcolumnPairs(column_name))
     {
-        if (auto /*dynamic_subcolumn_type*/ _ = it->type->tryGetSubcolumnType(dynamic_subcolumn_name))
-            return true;
+        auto it = columns.get<1>().find(String(ordinary_column_name));
+        if (it != columns.get<1>().end() && it->type->hasDynamicSubcolumns() && !dynamic_subcolumn_name.empty())
```
Comment (george-larionov) [inline src/Storages/ColumnsDescription.cpp]: Why do we check ```!dynamic_subcolumn_name.empty()``` here but not in the other two?

If possible, I think it would be really nice to make these 3 almost duplicated sections into one function

File: src/Storages/ColumnsDescription.cpp [hunk 3]
```diff
@@ -817,12 +821,14 @@ bool ColumnsDescription::hasColumnOrSubcolumn(GetColumnsOptions::Kind kind, cons
...
-    it = columns.get<1>().find(ordinary_column_name);
-    if (it != columns.get<1>().end() && it->type->hasDynamicSubcolumns())
+    for (auto [ordinary_column_name, dynamic_subcolumn_name] : Nested::getAllColumnAndSubcolumnPairs(column_name))
     {
-        if (auto /*dynamic_subcolumn_type*/ _ = it->type->hasSubcolumn(dynamic_subcolumn_name))
-            return true;
+        it = columns.get<1>().find(String(ordinary_column_name));
+        if (it != columns.get<1>().end() && it->type->hasDynamicSubcolumns())
+        {
+            if (auto /*dynamic_subcolumn_type*/ _ = it->type->hasSubcolumn(dynamic_subcolumn_name))
```
Comment (george-larionov) [inline src/Storages/ColumnsDescription.cpp]: Why do you call hasSubcolumn here instead of tryGetSubcolumnType? It seems to just call it internally anyway, but has an extra param and returns a boolean instead of a pointer.

If you intend to call hasSubcolumn, you could make the if statement a bit more concise:
```if (it->type->hasSubcolumn(dynamic_subcolumn_name))```

**Review by george-larionov — COMMENTED** [review]
Here are my comments so far, I will continue tomorrow.

File: src/Interpreters/createSubcolumnsExtractionActions.cpp [hunk 4]
```diff
@@ -18,19 +18,24 @@ ActionsDAG createSubcolumnsExtractionActions(const Block & available_columns, co
...
-        if (!available_columns.has(required_column) && subcolumn)
+        if (available_columns.has(required_column))
+            continue;
+
+        for (auto [column_name, subcolumn_name] : Nested::getAllColumnAndSubcolumnPairs(required_column))
         {
-            auto [column_name, subcolumn_name] = Nested::splitName(required_column);
+            const auto * column = available_columns.findByName(column_name);
+            if (!column || !column->type->tryGetSubcolumnType(subcolumn_name))
+                continue;
```
Comment (george-larionov) [inline src/Interpreters/createSubcolumnsExtractionActions.cpp:28]: Question: if we iterate through this loop on the column/subcolumn pairs but never find the column, should we error since it is a "required column"? Or is it handled elsewhere?

**Review by george-larionov — APPROVED** [review]
It looks good to me, but it is my first time with this code so consider getting another review, I might have missed some corner case.

**Comment by Avogar** [comment]
[BuzzHouse (amd_debug)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87205&sha=8cd271406e1e833d27422c82ccbee5603e17c9f9&name_0=PR&name_1=BuzzHouse%20%28amd_debug%29) - https://github.com/ClickHouse/ClickHouse/issues/90297
[BuzzHouse (arm_asan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87205&sha=8cd271406e1e833d27422c82ccbee5603e17c9f9&name_0=PR&name_1=BuzzHouse+%28arm_asan%29) - https://github.com/ClickHouse/ClickHouse/issues/83883
[BuzzHouse (amd_tsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87205&sha=8cd271406e1e833d27422c82ccbee5603e17c9f9&name_0=PR&name_1=BuzzHouse+%28amd_tsan%29) - infrastructure error
[BuzzHouse (amd_ubsan)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87205&sha=8cd271406e1e833d27422c82ccbee5603e17c9f9&name_0=PR&name_1=BuzzHouse+%28amd_ubsan%29) - https://github.com/ClickHouse/ClickHouse/issues/75520
[Integration tests (amd_binary, 3/5)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87205&sha=8cd271406e1e833d27422c82ccbee5603e17c9f9&name_0=PR&name_1=Integration+tests+%28amd_binary%2C+3%2F5%29) - infrastructure error
