### PR TITLE
Fix race in `02962_system_sync_replica_lightweight_from_modifier`

### LINKED ISSUE #84077: `02962_system_sync_replica_lightweight_from_modifier` is flaky
I am aware of https://github.com/ClickHouse/ClickHouse/issues/60480 which is about timeouts in `02962_system_sync_replica_lightweight_from_modifier `.

This issue is about failures of this kind:

From [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=5bf35d6dc93572997e4ae11b50dcd845059671e8&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%29):

```
2025-07-16 06:13:08 Reason: return code:  1
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:23] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_10 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_2 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_3 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_4 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_5 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:06] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_6 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_7 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_8 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:32] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_0cpvl06n --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1000000 --vertical_merge_algorithm_min_columns_to_activate 56 --allow_vertical_merges_from_compact_to_wide_parts 0 --min_merge_bytes_to_use_direct_io 1145459371 --index_granularity_bytes 16123122 --merge_max_block_size 8288 --index_granularity 4048 --min_bytes_for_wide_part 1073741824 --marks_compress_block_size 58044 --primary_key_compress_block_size 78217 --replace_long_file_name_to_hash 0 --max_file_name_length 19 --min_bytes_for_full_part_storage 536870912 --compact_parts_max_bytes_to_buffer 384071715 --compact_parts_max_granules_to_buffer 180 --compact_parts_merge_max_bytes_to_prefetch_part 30475796 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 60 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 0 --enable_block_number_column 1 --enable_block_offset_column 1 --use_primary_key_cache 1 --prewarm_primary_key_cache 0 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_9 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:38] local i=0
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:39] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:43] pids[${i}]=1676735
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:44] i=1
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:39] for t in "${tables_arr[@]}"
2025-07-16 06:13:08 + [2025-07-16 06:13:07] [:43] pids[${i}]=1676736
2025-07
```

From [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=e6b98673772e716f55258e874212170848a627c1&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_binary%2C%20old%20analyzer%2C%20s3%20storage%2C%20DatabaseReplicated%2C%201%2F2%29):

```
2025-07-17 10:59:15 Reason: return code:  1
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:31] return
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:120] try_sync_replicas test_table_ 296
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:7] local table_name_prefix=test_table_
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:8] local time_left=296
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:10] local empty_partitions_arr
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:11] readarray -t empty_partitions_arr
2025-07-17 10:59:15 ++ [2025-07-17 10:59:13] [:11] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_60t9ejxo --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 11478664 --distributed_aggregation_memory_efficient 1 --fsync_metadata 0 --output_format_parallel_formatting 1 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 12862597 --max_read_buffer_size 997393 --prefer_localhost_replica 1 --max_block_size 96457 --max_joined_block_size_rows 67126 --max_threads 2 --optimize_append_index 0 --use_hedged_requests 0 --optimize_if_chain_to_multiif 0 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 1 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 55 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 15456461 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1960609317 --min_bytes_to_use_mmap_io 4852750905 --local_filesystem_read_method pread --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 100 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 1Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_expressions 1 --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 24 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 2948599278 --min_compress_block_size 872272 --max_compress_block_size 2580332 --merge_tree_compact_parts_min_granules_to_multibuffer_read 5 --optimize_sorting_by_input_stream_properties 0 --http_response_buffer_size 4379249 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 3 --session_timezone America/Mazatlan --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction True --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.51 --prefer_external_sort_block_bytes 100000000 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 10 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 1 --query_plan_join_swap_table false --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 10737418240 --max_bytes_before_external_group_by 10737418240 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0 --use_skip_indexes_if_final_exact_mode 1 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.5248089214704253 --prefer_fetch_merged_part_size_threshold 7310638719 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 1 --index_granularity_bytes 15725630 --merge_max_block_size 17238 --index_granularity 33609 --min_bytes_for_wide_part 954620588 --marks_compress_block_size 55217 --primary_key_compress_block_size 86154 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 497148649 --compact_parts_max_bytes_to_buffer 17059606 --compact_parts_max_granules_to_buffer 131 --compact_parts_merge_max_bytes_to_prefetch_part 8246107 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 6 --old_parts_lifetime 409 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT DISTINCT substr(new_part_name, 1, position(new_part_name, '\''_'\'') - 1) AS partition_id
2025-07-17 10:59:15         FROM system.replication_queue
2025-07-17 10:59:15         WHERE (database = currentDatabase()) AND (table LIKE '\''test_table_%'\'') AND (last_exception LIKE '\''%No active replica has part%'\'') AND (partition_id NOT IN (
2025-07-17 10:59:15             SELECT partition_id
2025-07-17 10:59:15             FROM system.parts
2025-07-17 10:59:15             WHERE (database = currentDatabase()) AND (table LIKE '\''test_table_%'\'')
2025-07-17 10:59:15         ))'
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:19] local tables_arr
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:20] readarray -t tables_arr
2025-07-17 10:59:15 ++ [2025-07-17 10:59:13] [:20] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_60t9ejxo --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 11478664 --distributed_aggregation_memory_efficient 1 --fsync_metadata 0 --output_format_parallel_formatting 1 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 12862597 --max_read_buffer_size 997393 --prefer_localhost_replica 1 --max_block_size 96457 --max_joined_block_size_rows 67126 --max_threads 2 --optimize_append_index 0 --use_hedged_requests 0 --optimize_if_chain_to_multiif 0 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 1 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 55 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 15456461 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1960609317 --min_bytes_to_use_mmap_io 4852750905 --local_filesystem_read_method pread --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 100 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 1Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_expressions 1 --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 24 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 2948599278 --min_compress_block_size 872272 --max_compress_block_size 2580332 --merge_tree_compact_parts_min_granules_to_multibuffer_read 5 --optimize_sorting_by_input_stream_properties 0 --http_response_buffer_size 4379249 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 3 --session_timezone America/Mazatlan --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction True --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.51 --prefer_external_sort_block_bytes 100000000 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 10 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 1 --query_plan_join_swap_table false --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 10737418240 --max_bytes_before_external_group_by 10737418240 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0 --use_skip_indexes_if_final_exact_mode 1 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.5248089214704253 --prefer_fetch_merged_part_size_threshold 7310638719 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 1 --index_granularity_bytes 15725630 --merge_max_block_size 17238 --index_granularity 33609 --min_bytes_for_wide_part 954620588 --marks_compress_block_size 55217 --primary_key_compress_block_size 86154 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 497148649 --compact_parts_max_bytes_to_buffer 17059606 --compact_parts_max_granules_to_buffer 131 --compact_parts_merge_max_bytes_to_prefetch_part 8246107 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 6 --old_parts_lifetime 409 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT name FROM system.tables WHERE database=currentDatabase() AND name like '\''test_table_%'\'' AND (engine like '\''%Replicated%'\'' or engine like '\''%Shared%'\'')'
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:22] local t
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:23] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:32] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_60t9ejxo --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 11478664 --distributed_aggregation_memory_efficient 1 --fsync_metadata 0 --output_format_parallel_formatting 1 --input_format_parallel_parsing 1 --min_chunk_bytes_for_parallel_parsing 12862597 --max_read_buffer_size 997393 --prefer_localhost_replica 1 --max_block_size 96457 --max_joined_block_size_rows 67126 --max_threads 2 --optimize_append_index 0 --use_hedged_requests 0 --optimize_if_chain_to_multiif 0 --optimize_if_transform_strings_to_enum 0 --optimize_read_in_order 1 --optimize_or_like_chain 1 --optimize_substitute_columns 0 --enable_multiple_prewhere_read_steps 1 --read_in_order_two_level_merge_threshold 55 --optimize_aggregation_in_order 0 --aggregation_in_order_max_block_bytes 15456461 --use_uncompressed_cache 0 --min_bytes_to_use_direct_io 1960609317 --min_bytes_to_use_mmap_io 4852750905 --local_filesystem_read_method pread --remote_filesystem_read_method read --local_filesystem_read_prefetch 0 --filesystem_cache_segments_batch_size 100 --read_from_filesystem_cache_if_exists_otherwise_bypass_cache 1 --throw_on_error_from_cache_on_write_operations 0 --remote_filesystem_read_prefetch 0 --allow_prefetched_read_pool_for_remote_filesystem 1 --filesystem_prefetch_max_memory_usage 32Mi --filesystem_prefetches_limit 0 --filesystem_prefetch_min_bytes_for_single_read_task 1Mi --filesystem_prefetch_step_marks 50 --filesystem_prefetch_step_bytes 0 --compile_expressions 1 --compile_aggregate_expressions 0 --compile_sort_description 1 --merge_tree_coarse_index_granularity 24 --optimize_distinct_in_order 1 --max_bytes_before_remerge_sort 2948599278 --min_compress_block_size 872272 --max_compress_block_size 2580332 --merge_tree_compact_parts_min_granules_to_multibuffer_read 5 --optimize_sorting_by_input_stream_properties 0 --http_response_buffer_size 4379249 --http_wait_end_of_query False --enable_memory_bound_merging_of_aggregation_results 1 --min_count_to_compile_expression 0 --min_count_to_compile_aggregate_expression 3 --min_count_to_compile_sort_description 3 --session_timezone America/Mazatlan --use_page_cache_for_disks_without_file_cache False --page_cache_inject_eviction True --merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability 0.51 --prefer_external_sort_block_bytes 100000000 --cross_join_min_rows_to_compress 0 --cross_join_min_bytes_to_compress 1 --min_external_table_block_size_bytes 100000000 --max_parsing_threads 10 --optimize_functions_to_subcolumns 0 --parallel_replicas_local_plan 1 --query_plan_join_swap_table false --enable_vertical_final 0 --optimize_extract_common_expressions 1 --use_query_condition_cache 0 --secondary_indices_enable_bulk_filtering 1 --use_skip_indexes_if_final 1 --max_bytes_before_external_sort 10737418240 --max_bytes_before_external_group_by 10737418240 --max_bytes_ratio_before_external_sort 0 --max_bytes_ratio_before_external_group_by 0 --use_skip_indexes_if_final_exact_mode 1 --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.5248089214704253 --prefer_fetch_merged_part_size_threshold 7310638719 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 1 --index_granularity_bytes 15725630 --merge_max_block_size 17238 --index_granularity 33609 --min_bytes_for_wide_part 954620588 --marks_compress_block_size 55217 --primary_key_compress_block_size 86154 --replace_long_file_name_to_hash 1 --max_file_name_length 0 --min_bytes_for_full_part_storage 497148649 --compact_parts_max_bytes_to_buffer 17059606 --compact_parts_max_granules_to_buffer 131 --compact_parts_merge_max_bytes_to_prefetch_part 8246107 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 6 --old_parts_lifetime 409 --prewarm_mark_cache 0 --use_const_adaptive_granularity 1 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 1 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'ALTER TABLE test_table_10 MODIFY SETTING max_replicated_merges_in_queue=0'
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:32] for t in "${tables_arr[@]}"
2025-07-17 10:59:15 + [2025-07-17 10:59:13] [:35] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_60t9ejxo --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 11478664 --distributed_aggregation_memory_efficient 1 --fsync_metadata 0 --output_format_parallel_formatting 1 --input_format_parallel_parsing 1 --min_chunk_bytes_for_paral
```

From [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=e6b98673772e716f55258e874212170848a627c1&name_0=MasterCI&name_1=Stateless%20tests%20%28amd_debug%2C%20distributed%20plan%2C%20s3%20storage%29):

```
2025-07-17 12:56:21 + [2025-07-17 12:56:18] [:70] local num_tries=0
2025-07-17 12:56:21 ++ [2025-07-17 12:56:18] [:71] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT count() FROM system.processes WHERE current_database=currentDatabase() AND query LIKE '\''%test_table_%'\'''
2025-07-17 12:56:21 + [2025-07-17 12:56:18] [:71] [[ 2 -ne 1 ]]
2025-07-17 12:56:21 + [2025-07-17 12:56:18] [:72] sleep 1
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:73] num_tries=1
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:74] '[' 1 -eq 250 ']'
2025-07-17 12:56:21 ++ [2025-07-17 12:56:19] [:71] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT count() FROM system.processes WHERE current_database=currentDatabase() AND query LIKE '\''%test_table_%'\'''
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:71] [[ 1 -ne 1 ]]
2025-07-17 12:56:21 ++ [2025-07-17 12:56:19] [:88] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT count() - sum(is_readonly) FROM system.replicas WHERE database=currentDatabase() AND table LIKE '\''test_table_%'\'''
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:88] local res=4
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:89] '[' 4 -eq 0 ']'
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:99] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal --prefer_warmed_unmerged_parts_seconds=0 --max_result_rows 0 --max_result_bytes 0 --max_rows_to_read 0 --max_bytes_to_read 0 -q 'SELECT * FROM merge(currentDatabase(), '\''test_table_'\'') FORMAT Null'
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:106] local time_left=299
2025-07-17 12:56:21 ++ [2025-07-17 12:56:19] [:109] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT name FROM system.tables WHERE database=currentDatabase() AND name like '\''test_table_%'\'' ORDER BY rand() LIMIT 1'
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:109] local some_table=test_table_10
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:110] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SYSTEM SYNC REPLICA test_table_10 PULL'
2025-07-17 12:56:21 ++ [2025-07-17 12:56:19] [:111] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SELECT name FROM system.tables WHERE database=currentDatabase() AND name like '\''test_table_%'\'' ORDER BY rand() LIMIT 1'
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:111] local some_table=test_table_8
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:112] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'SYSTEM SYNC REPLICA test_table_8 PULL'
2025-07-17 12:56:21 + [2025-07-17 12:56:19] [:115] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 100 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 9643158291 --index_granularity_bytes 14054201 --merge_max_block_size 14258 --index_granularity 30379 --min_bytes_for_wide_part 560522754 --marks_compress_block_size 32713 --primary_key_compress_block_size 39730 --replace_long_file_name_to_hash 1 --max_file_name_length 86 --min_bytes_for_full_part_storage 0 --compact_parts_max_bytes_to_buffer 457117823 --compact_parts_max_granules_to_buffer 124 --compact_parts_merge_max_bytes_to_prefetch_part 21948927 --cache_populated_by_fetch 0 --concurrent_part_removal_threshold 38 --old_parts_lifetime 10 --prewarm_mark_cache 1 --use_const_adaptive_granularity 0 --enable_index_granularity_compression 1 --enable_block_number_column 1 --enable_block_offset_column 0 --use_primary_key_cache 0 --prewarm_primary_key_cache 1 --allow_repeated_settings --client_logs_file=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/02962_system_sync_replica_lightweight_from_modifier.stderr-fatal -q 'KILL MUTATION WHERE database=currentDatabase() AND table like '\''test_table_%'\'''
2025-07-17 12:56:21 + [2025-07-17 12:56:20] [:118] wait_for_all_mutations test_table_%
2025-07-17 12:56:21 + [2025-07-17 12:56:20] [:24] local table=test_table_%
2025-07-17 12:56:21 + [2025-07-17 12:56:20] [:25] local database=
2025-07-17 12:56:21 + [2025-07-17 12:56:20] [:26] database=test_ijo1iyzv
2025-07-17 12:56:21 + [2025-07-17 12:56:20] [:28] for _ in {1..600}
2025-07-17 12:56:21 ++ [2025-07-17 12:56:20] [:30] /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-client --send_logs_level=warning --database=test_ijo1iyzv --log_comment 02962_system_sync_replica_lightweight_from_modifier.sh --allow_merge_tree_settings --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 -
```

[Test history](https://play.clickhouse.com/play?user=play#U0VMRUNUIGJhc2VfcmVwbywgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwciwgY2hlY2tfc3RhcnRfdGltZSwgY2hlY2tfbmFtZSwgdGVzdF9uYW1lLCB0ZXN0X3N0YXR1cywgcmVwb3J0X3VybC0tLCB0ZXN0X2NvbnRleHRfcmF3CkZST00gY2hlY2tzCldIRVJFIDEKICAgIC0tQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0JST0tFTicpCiAgICBBTkQgdG9EYXRlKGNoZWNrX3N0YXJ0X3RpbWUpID4gJzIwMjUtMDEtMDEnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMjk2Ml9zeXN0ZW1fc3luY19yZXBsaWNhX2xpZ2h0d2VpZ2h0X2Zyb21fbW9kaWZpZXIlJwogICAgQU5EIHByID0gMAogICAgLS0gQU5EIHRlc3RfY29udGV4dF9yYXcgbGlrZSAnJUFMVEVSX01FVEFEQVRBJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVND)

### PR DESCRIPTION
**Pull request by serxa**
Fixes https://github.com/ClickHouse/ClickHouse/issues/84077

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### CODE REVIEW

**Comment by serxa** [comment]
All the failed tests are unrelated:

|job_name|test_name|status|info|comment|
|:--|:--|:-:|:--|:--|
|[Stateless tests (amd_asan, distributed plan, sequential)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84743&sha=c962f1265511709047c639a74b2f94f728924e4a&name_0=PR&name_1=Stateless%20tests%20%28amd_asan%2C%20distributed%20plan%2C%20sequential%29)||failure|||
||00002_log_and_exception_messages_formatting|FAIL|https://github.com/ClickHouse/ClickHouse/issues/84642||
|[Stateless tests (amd_binary, ParallelReplicas, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84743&sha=c962f1265511709047c639a74b2f94f728924e4a&name_0=PR&name_1=Stateless%20tests%20%28amd_binary%2C%20ParallelReplicas%2C%20s3%20storage%2C%20parallel%29)||failure|||
||Logical error thrown (see clickhouse-server.log or logical_errors.txt)|FAIL|https://github.com/ClickHouse/ClickHouse/issues/84771||
|[Stateless tests (amd_debug, AsyncInsert, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84743&sha=c962f1265511709047c639a74b2f94f728924e4a&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20AsyncInsert%2C%20s3%20storage%2C%20parallel%29)||failure|||
||02443_detach_attach_partition|FAIL|https://github.com/ClickHouse/ClickHouse/issues/84173||
|[Stateless tests (amd_tsan, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=84743&sha=c962f1265511709047c639a74b2f94f728924e4a&name_0=PR&name_1=Stateless%20tests%20%28amd_tsan%2C%20s3%20storage%2C%20parallel%29)||failure|||
||02443_detach_attach_partition|FAIL|https://github.com/ClickHouse/ClickHouse/issues/84173||
||Scraping minio_audit_logs|FAIL|||

minio audit logs are failed to be scrapped due to:
```
Run command: [cd /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/run_r0 && clickhouse local --max_block_size 8192 --max_memory_usage 10G --max_threads 1 --max_result_rows 0 --max_result_bytes 0 --max_bytes_to_read 0 --only-system-tables --stacktrace --config-file=/etc/clickhouse-server/config.xml  --path /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/run_r0 --query "select * from system.minio_audit_logs into outfile '/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/system_tables/minio_audit_logs.tsv' format TSVWithNamesAndTypes" -- --zookeeper.implementation=testkeeper]
Logging trace to /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-local.log
Logging errors to /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/clickhouse-local.err.log
Code: 160. DB::Exception: Estimated query execution time (1081.90960 seconds) is too long. Maximum: 600. Estimated rows to process: 2190518 (612590 read in 302.56177 seconds).: While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (TOO_SLOW)
```

File: tests/queries/shell_config.sh [hunk 1]
```diff
@@ -225,6 +225,12 @@ function run_with_error()
     return 0
 }
 
+function with_lock()
+{
+    local lock_file="${CLICKHOUSE_TMP}/lock_${CLICKHOUSE_TEST_UNIQUE_NAME}_$1.lock"; shift
+    flock "$lock_file" "$@"
```
Comment (tavplubix) [inline tests/queries/shell_config.sh:231]: do we need a timeout just in case?

**Review by tavplubix — APPROVED** [review]

File: tests/queries/shell_config.sh (hunk 1 above)
Comment (serxa) [reply tests/queries/shell_config.sh:231]: Well, I thought about it and decided not to introduce timeouts. It's (1) not clear how to select a value and (2) we need to add more logic to the test for the timeout case. So for (2), I was not sure how to handle the timeout itself, so I decided that it's better to keep it simple.
