### PR TITLE
Fix reading column that exists in subset of tables in Merge engine

### LINKED ISSUE #76746: New merge table gives possibly incorrect result
### Company or project name

_No response_

### Describe the unexpected behaviour

https://fiddle.clickhouse.com/fd285730-8262-4f74-be69-5d5e15e4e8d1

Why does `m_n` return `abc` for the `not_in_m_n` column? I was expecting the coerced type to be one of `Nullable(String)` or for it to return an empty string

### How to reproduce

Fiddle

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect result during reading column that exists in subset of tables in Merge engine.

Closes https://github.com/ClickHouse/ClickHouse/issues/76746

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Comment by SaltTan** [comment]
will this fix https://github.com/ClickHouse/ClickHouse/issues/76746?

**Comment by Avogar** [comment]
Yes

File: tests/queries/0_stateless/03519_merge_engine_read_column_existing_in_subset_of_tables.sql [hunk 1]
```diff
@@ -0,0 +1,84 @@
+drop table if exists test1;
+drop table if exists test2;
+drop table if exists test3;
+drop table if exists test_merge;
+
+create table test1(a UInt64, b UInt64) engine=Memory;
+create table test2(a UInt64, c UInt64) engine=Memory;
+create table test3(a UInt64, d UInt64) engine=Memory;
+create table test_merge (a UInt64, b UInt64, c UInt64, d UInt64, e UInt64) engine=Merge(default, 'test');
```
Comment (GrigoryPervakov) [inline tests/queries/0_stateless/03519_merge_engine_read_column_existing_in_subset_of_tables.sql:9]: Failed because of random datrabase name in CI
```suggestion
create table test_merge (a UInt64, b UInt64, c UInt64, d UInt64, e UInt64) engine=Merge(database(), 'test');
```

**Review by GrigoryPervakov — APPROVED** [review]

**Comment by Avogar** [comment]
[Stateless tests (release, ParallelReplicas, s3 storage)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80643&sha=5d949c0542a2b235ee7b775e410222b7b43083aa&name_0=PR&name_1=Stateless%20tests%20%28release%2C%20ParallelReplicas%2C%20s3%20storage%29) - https://github.com/ClickHouse/ClickHouse/issues/65382
[Integration tests (tsan, 3/6)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80643&sha=5d949c0542a2b235ee7b775e410222b7b43083aa&name_0=PR&name_1=Integration%20tests%20%28tsan%2C%203%2F6%29) - https://github.com/ClickHouse/ClickHouse/issues/81221
`CH Inc sync` - known no such key error
