### PR TITLE
Attempt to fix flakiness of 01194_http_query_id

### LINKED ISSUE #56851: Test 01194_http_query_id is flaky
See [failures](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHJlcG9ydF91cmwKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjMtMTEtMDknIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICclMDExOTRfaHR0cF9xdWVyeV9pZCUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKQ==)

```
2023-11-15 09:24:12 01194_http_query_id:                                                    [ FAIL ] 66.89 sec. - having stderror: 
2023-11-15 09:24:12 curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
2023-11-15 09:24:12 
2023-11-15 09:24:12 stdout:
2023-11-15 09:24:12 Code: 373. DB::Exception: Session test_01194 is locked by a concurrent client. (SESSION_IS_LOCKED) (version 23.11.1.1)
2023-11-15 09:24:12 
2023-11-15 09:24:12 
2023-11-15 09:24:12 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.2769500930994129 --prefer_fetch_merged_part_size_threshold 10737418240 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 8884292534 --index_granularity_bytes 21479220 --merge_max_block_size 3394 --index_granularity 33464 --min_bytes_for_wide_part 884672932 --marks_compress_block_size 84207 --primary_key_compress_block_size 59389 --replace_long_file_name_to_hash 1 --max_file_name_length 51
2023-11-15 09:24:12 
2023-11-15 09:24:12 Database: test_petje0wm
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Attempt to fix flakiness of 01194_http_query_id.

On the failures I check, the problem was that `SYSTEM FLUSH LOGS` was slow and had the session open while it was flushing the queues, so the next query (countDistinct) could not start a new query with that session and failed.
I don't understand how it's possible that bash sent the new query if the previous one hadn't finished and curl showed no error but it happened. We don't need to use sessions for those 2 queries, so just remove it.

Also makes the test paralelizable by randomizing the session name.

Closes https://github.com/ClickHouse/ClickHouse/issues/56851

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-clickhouse-ci-1** [comment]
*This is an automated comment for commit 0cab22fd16caf260306e1b1feb77d2ddcced5205 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/66774/0cab22fd16caf260306e1b1feb77d2ddcced5205/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Builds</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/builds/report.html">✅ success</a></td></tr>
<tr><td>ClickBench</td><td>Runs [ClickBench](https://github.com/ClickHouse/ClickBench/) with instant-attach table</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/clickbench__aarch64_.html">✅ success</a></td></tr>
<tr><td>Compatibility check</td><td>Checks that <b>clickhouse</b> binary runs on distributions with old libc versions. If it fails, ask a maintainer for help</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/compatibility_check__aarch64_.html">✅ success</a></td></tr>
<tr><td>Docker keeper image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/docker_keeper_image.html">✅ success</a></td></tr>
<tr><td>Docker server image</td><td>The check to build and optionally push the mentioned image to docker hub</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/docker_server_image.html">✅ success</a></td></tr>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/b1b5123a6ab1262bab2c9849a1233e38189f686b/docs_check.html">✅ success</a></td></tr>
<tr><td>Install packages</td><td>Checks that the built packages are installable in a clear environment</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/install_packages__aarch64_.html">✅ success</a></td></tr>
<tr><td>Integration tests</td><td>The integration tests report. In parenthesis the package type is given, and in square brackets are the optional part/total tests</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/integration_tests__aarch64__[1_6].html">✅ success</a></td></tr>
<tr><td>Stateful tests</td><td>Runs stateful functional tests for ClickHouse binaries built in various configurations -- release, debug, with sanitizers, etc</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/stateful_tests__aarch64_.html">✅ success</a></td></tr>
<tr><td>Unit tests</td><td>Runs the unit tests for different release types</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/52b03eb776423a1d2ee847051ab0d9433e383540/unit_tests__asan_.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by nikitamikhaylov — APPROVED** [review]

File: tests/queries/0_stateless/01194_http_query_id.sh [hunk 1]
```diff
@@ -4,14 +4,14 @@ CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 # shellcheck source=../shell_config.sh
 . "$CURDIR"/../shell_config.sh
 
-url="http://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT_HTTP}/?session_id=test_01194"
 rnd=$RANDOM
+url="${CLICKHOUSE_URL}&session_id=test_01194_$RANDOM"
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01194_http_query_id.sh:8]: Btw, bash's RANDOM only has about 32768 unique values, and it means that for our 100 parallel invocations in the flaky check, it has a high chance to hit the birthday paradox.

File: tests/queries/0_stateless/01194_http_query_id.sh [hunk 2]
```diff
@@ -4,14 +4,14 @@ CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
...
 ${CLICKHOUSE_CURL} -sS "$url&query=SELECT+'test_01194',$rnd,1" > /dev/null
 ${CLICKHOUSE_CURL} -sS "$url&query=SELECT+'test_01194',$rnd,2" > /dev/null
 ${CLICKHOUSE_CURL} -sS "$url" --data "SELECT 'test_01194',$rnd,3" > /dev/null
 ${CLICKHOUSE_CURL} -sS "$url" --data "SELECT 'test_01194',$rnd,4" > /dev/null
 
-${CLICKHOUSE_CURL} -sS "$url" --data "SYSTEM FLUSH LOGS"
+${CLICKHOUSE_CURL} -sS "${CLICKHOUSE_URL}" --data "SYSTEM FLUSH LOGS"
 
-${CLICKHOUSE_CURL} -sS "$url&query=SELECT+count(DISTINCT+query_id)+FROM+system.query_log+WHERE+current_database+LIKE+currentDatabase()+AND+query+LIKE+'SELECT+''test_01194'',$rnd%25'"
+${CLICKHOUSE_CURL} -sS "${CLICKHOUSE_URL}" --data "SELECT count(DISTINCT query_id) FROM system.query_log WHERE current_database = currentDatabase() AND event_date >= yesterday() AND query LIKE 'SELECT ''test_01194'',$rnd%'"
```
Comment (alexey-milovidov) [inline tests/queries/0_stateless/01194_http_query_id.sh:17]: What if this query starts, and the query start event has a chance to be recorded in the query_log before this query takes the snapshot of the query log? Then the LIKE condition will also match this query by itself.

You can add `AND query NOT LIKE '%this_exact_query%'`

To allow the test to run in parallel, it might also need to be filtered by the session_id.

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
.

File: tests/queries/0_stateless/01194_http_query_id.sh (hunk 2 above)
Comment (Algunenano) [reply tests/queries/0_stateless/01194_http_query_id.sh:17]: `query LIKE 'SELECT ''test_01194'',$rnd%'"` won't be matched (no starting `%`)

**Review by alexey-milovidov — APPROVED** [review]
