### PR TITLE
Fix a few flaky tests

### LINKED ISSUE #91973: `03704_rmv_logging_internal_queries` is flaky
Happened here: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91470&sha=latest&name_0=PR&name_1=Stateless+tests+%28amd_tsan%2C+s3+storage%2C+parallel%29&name_2=Tests

History: https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMzcwNF9ybXZfbG9nZ2luZ19pbnRlcm5hbF9xdWVyaWVzJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnU3RhdGVsZXNzIHRlc3RzIChhbWRfdHNhbiwgczMgc3RvcmFnZSwgcGFyYWxsZWwpJwogICAgQU5EIHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicpCiAgICBBTkQgKChoZWFkX3JlZiA9ICdtYXN0ZXInIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCkgT1IgcHVsbF9yZXF1ZXN0X251bWJlciAhPSAwKQpHUk9VUCBCWSBkYXkKT1JERVIgQlkgZGF5IERFU0MK

### LINKED ISSUE #92284: Flaky test: 03759_marks_cache_events
_Important: This issue was automatically generated and is used by CI for matching failures. DO NOT modify the body content. DO NOT remove labels._

Test name: 03759_marks_cache_events
Failure reason: result differs with reference
CI report: [Stateless tests (amd_debug, AsyncInsert, s3 storage, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92249&sha=1590d944db9a04eceb7a2edc2e5c6330faaa4efe&name_0=PR&name_1=Stateless%20tests%20%28amd_debug%2C%20AsyncInsert%2C%20s3%20storage%2C%20parallel%29)

CIDB statistics: [cidb](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSA9ICcwMzc1OV9tYXJrc19jYWNoZV9ldmVudHMnCiAgICAtLSBBTkQgY2hlY2tfbmFtZSA9ICdTdGF0ZWxlc3MgdGVzdHMgKGFtZF9kZWJ1ZywgQXN5bmNJbnNlcnQsIHMzIHN0b3JhZ2UsIHBhcmFsbGVsKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

Test output:
```
2025-12-16 12:36:22 Reason: result differs with reference:  
2025-12-16 12:36:22 --- /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03759_marks_cache_events.reference	2025-12-16 12:29:50.553120518 -0300
2025-12-16 12:36:22 +++ /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/tests/queries/0_stateless/03759_marks_cache_events.stdout	2025-12-16 12:36:22.568584799 -0300
2025-12-16 12:36:22 @@ -1,9 +1,9 @@
2025-12-16 12:36:22  "query_kind","load_marks_asynchronously","hits","misses"
2025-12-16 12:36:22  "Insert","0",0,0
2025-12-16 12:36:22  "Select","0",0,1
2025-12-16 12:36:22 -"Select","0",1,0
2025-12-16 12:36:22 +"Select","0",0,1
2025-12-16 12:36:22  "Select","1",0,1
2025-12-16 12:36:22  "Select","1",1,0
2025-12-16 12:36:22  "part_name","hits","misses"
2025-12-16 12:36:22  "all_1_1_1",0,0
2025-12-16 12:36:22  "all_1_1_2",0,0
2025-12-16 12:36:22 
2025-12-16 12:36:22 
2025-12-16 12:36:22 
2025-12-16 12:36:22 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.713745519603141 --prefer_fetch_merged_part_size_threshold 4428779100 --vertical_merge_algorithm_min_...
2025-12-16 12:36:22 
2025-12-16 12:36:22 Database: test_kgo4yxnj
```

### PR DESCRIPTION
**Pull request by PedroTadim**
### Changelog category (leave one):
- CI Fix or Improvement (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
...

### Documentation entry for user-facing changes

For 03759_marks_cache_events:
I think the issue was due to enabled async inserts; the first select queries didn't see the part flushed into the storage yet. Also added defensive lines for the DETACH.
For 03704_rmv_logging_internal_queries:
Just check if inserts were logged; there could be other materialized views from other tests running in parallel, also doing inserts.

Closes https://github.com/ClickHouse/ClickHouse/issues/91973
Closes https://github.com/ClickHouse/ClickHouse/issues/92284

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

**Review by thevar1able — APPROVED** [review]

File: tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh [hunk 1]
```diff
@@ -31,8 +31,8 @@ $CLICKHOUSE_CLIENT --query "SYSTEM WAIT VIEW rmv_test" 2> /dev/null
 $CLICKHOUSE_CLIENT --query "SYSTEM FLUSH LOGS query_log"
 $CLICKHOUSE_CLIENT --query "
 SELECT
-    countIf(query LIKE '%INSERT INTO $CLICKHOUSE_DATABASE.\`.tmp.inner_id.%' AND type = 'QueryStart'),
-    countIf(query LIKE '%INSERT INTO $CLICKHOUSE_DATABASE.\`.tmp.inner_id.%' AND type = 'QueryFinish'),
+    countIf(query LIKE '%INSERT INTO $CLICKHOUSE_DATABASE.\`.tmp.inner_id.%' AND type = 'QueryStart') >= 1,
+    countIf(query LIKE '%INSERT INTO $CLICKHOUSE_DATABASE.\`.tmp.inner_id.%' AND type = 'QueryFinish') >= 1,
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: `$CLICKHOUSE_DATABASE` should make the insert queries unique, so I don't think this is the good approach.

Comment (thevar1able) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: Well true, there should be one unique insert with `$CLICKHOUSE_DATABASE` AFAIU if test is running less than one hour 😅

Comment (PedroTadim) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: I changed the views into a separate database

File: tests/queries/0_stateless/03759_marks_cache_events.sql [hunk 2]
```diff
@@ -12,7 +13,7 @@ insert into data values (1);
 select * from data format Null settings load_marks_asynchronously=0;
 select * from data format Null settings load_marks_asynchronously=0;
 -- drop marks cache
-detach table data;
+detach table data sync;
```
Comment (azat) [inline tests/queries/0_stateless/03759_marks_cache_events.sql]: Why do we need this? We have https://github.com/ClickHouse/ClickHouse/blob/2c489420495296f2a5fdeafc0c0f5000c6123224/tests/config/users.d/database_atomic_drop_detach_sync.xml#L4

**Comment by PedroTadim** [comment]
@antaljanosbenjamin can you give a look at this again?

File: tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh [hunk 3]
```diff
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Tags: atomic-database
+# Tags: no-parallel, atomic-database
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: Why no parallel would help here? Could you please elaborate and maybe leave it as a comment in the source file, because it is not obvious. The flakyness comes from the fact that it refereshes two times instead of one. I don't see how that correlates with parallel running.

File: tests/queries/0_stateless/03759_marks_cache_events.sql [hunk 4]
```diff
@@ -1,4 +1,5 @@
--- Tags: no-parallel-replicas
+-- Tags: no-parallel-replicas, no-parallel
+-- Test depends on mark cache, don't run with others in parallel
```
Comment (antaljanosbenjamin) [inline tests/queries/0_stateless/03759_marks_cache_events.sql:2]: Here I think it makes sense. Even if we avoid running tests that clear mark cache, other tests might overpopulate mark cache, so it is okay to run this without any parallelism IMO.

File: tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh (hunk 3 above)
Comment (PedroTadim) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: I think other tests may run other materialized views in parallel, then the `countIf` aggregates may output more, thus making the test flaky.

Comment (PedroTadim) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: May I merge this PR?

Comment (antaljanosbenjamin) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: But the `countIf` uses `CLICKHOUSE_DATABASE` to filter the queries. `CLICKHOUSE_DATABASE` should be unique for each test, they are just replaced by `default` in output to ensure consistent output. Let's read the logs and figure out why the query is run twice.

Comment (PedroTadim) [reply tests/queries/0_stateless/03704_rmv_logging_internal_queries.sh]: The refresh may run more than once.
