### PR TITLE
Forbid wrong create view syntax

### LINKED ISSUE #4331: Wrong / meaningless syntax [create view ... to ...] allowed
Connected to ClickHouse server version 19.1.6

CREATE VIEW X TO Y AS SELECT 1

Ok.
0 rows in set. Elapsed: 0.002 sec.

### PR DESCRIPTION
**Pull request by ucasfl**
### Changelog category (leave one):

- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Forbid wrong create View syntax `CREATE View X TO Y AS SELECT`. Closes #4331.

### CODE REVIEW

File: src/Parsers/ParserCreateQuery.cpp [hunk 1]
```diff
@@ -1299,14 +1299,13 @@ bool ParserCreateViewQuery::parseImpl(Pos & pos, ASTPtr & node, Expected & expec
             return false;
     }
 
-
-    if (ParserKeyword{"TO INNER UUID"}.ignore(pos, expected))
+    if (!is_ordinary_view && ParserKeyword{"TO INNER UUID"}.ignore(pos, expected))
```
Comment (hanfei1991) [inline src/Parsers/ParserCreateQuery.cpp:1302]: Is it equal to `if (is_materialized_view && ...`? maybe more straitfoward.

**Review by hanfei1991 — APPROVED** [review]
