### PR TITLE
Ignore some jemalloc messages

### LINKED ISSUE #74941: Test 02301_harmful_reexec is flaky
### Describe the bug

Report:
https://s3.amazonaws.com/clickhouse-test-reports/0/21bf133a7bbdc82005d53f209d8e2222347807f5/stateless_tests__debug__[1_2].html

### How to reproduce

_No response_

### Error message and/or stacktrace

_No response_

### PR DESCRIPTION
**Pull request by antonio2368**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Jemalloc can print out some messages to stderr, sometimes warnings and sometimes errors.
We can safely ignore some of those messages, e.g. `<jemalloc>: background thread creation failed (11)`. 
It is printed when pthread_create for background thread returns `EAGAIN`. It will be simply retried again.

Fix https://github.com/ClickHouse/ClickHouse/issues/74941
I could've ignored message in that test only but it could easily happen for some other random test.
These messages are only printed in nonrelease builds.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory and will run independently of the checks below:
- [ ]  Only: Stateless tests
- [ ]  Only: Integration tests
- [ ]  Only: Performance tests
---
- [ ]  Skip: Style check
- [ ]  Skip: Fast test
---
- [ ]  Run all checks ignoring all possible failures (Resource-intensive. All test jobs execute in parallel).
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit 904afe5bda077a2ac6589bee55275b323e29b358 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/75449/904afe5bda077a2ac6589bee55275b323e29b358/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/75391/479119f70248be0e9a6347a3e13192942a915de5/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: programs/main.cpp [hunk 1]
```diff
@@ -201,6 +203,29 @@ extern "C"
...
+        using namespace std::literals;
+        static const std::unordered_set<std::string_view> ignore_messages{
+            "<jemalloc>: background thread creation failed (11)\n"sv};
+
+        std::string_view message_view{str};
+        if (ignore_messages.contains(message_view))
+            return;
+
+#    if defined(SYS_write)
+        syscall(SYS_write, fd, message_view.data(), message_view.size());
```
Comment (davenger) [inline programs/main.cpp:223]:
```suggestion
        syscall(SYS_write, 2 /*stderr*/, message_view.data(), message_view.size());
```

File: programs/keeper/keeper_main.cpp [hunk 2]
```diff
@@ -126,6 +126,29 @@ extern "C"
...
+        using namespace std::literals;
+        static const std::unordered_set<std::string_view> ignore_messages{
+            "<jemalloc>: background thread creation failed (11)\n"sv};
+
+        std::string_view message_view{str};
+        if (ignore_messages.contains(message_view))
+            return;
+
+#    if defined(SYS_write)
+        syscall(SYS_write, fd, message_view.data(), message_view.size());
```
Comment (davenger) [inline programs/keeper/keeper_main.cpp:146]:
```suggestion
        syscall(SYS_write, 2 /*stderr*/, message_view.data(), message_view.size());
```

**Review by davenger — APPROVED** [review]

**Review by alexey-milovidov — APPROVED** [review]
This is smart. Maybe patching jemalloc would be a better solution. LGTM anyway.

**Comment by antonio2368** [comment]
> Maybe patching jemalloc would be a better solution

We recently moved back to the jemalloc repo from our fork.
When we have a better reason to revive our fork, we can fix this issue there instead of this workaround.
