### PR TITLE
Fix making backup when multiple shards are used

### LINKED ISSUE #56566: Backup database on cluster fails with - CANNOT_BACKUP_TABLE
### Environment

ClickHouse server version: 23.8.6.16
Cluster: 2 replicas x 2 shards

### Observed behavior

1. There is ClickHouse cluster with name **vcloud-ch**

```
select cluster,shard_num,shard_weight,replica_num,host_name,host_address,is_local  from system.clusters where cluster='vcloud-ch' FORMAT Markdown;
```

| cluster | shard_num | shard_weight | replica_num | host_name | host_address | is_local |
|:-|-:|-:|-:|:-|:-|-:|
| vcloud-ch | 1 | 1 | 1 | chi-vcloud-ch-vcloud-ch-0-0 | 127.0.0.1 | 1 |
| vcloud-ch | 1 | 1 | 2 | chi-vcloud-ch-vcloud-ch-0-1 | 10.3.5.30 | 0 |
| vcloud-ch | 2 | 1 | 1 | chi-vcloud-ch-vcloud-ch-1-0 | 10.3.4.80 | 0 |
| vcloud-ch | 2 | 1 | 2 | chi-vcloud-ch-vcloud-ch-1-1 | 10.3.5.195 | 0 |

2. There is database on cluster **oola_reporting_vcloud** with clustered table **events_shard**

```
show create database oola_reporting_vcloud FORMAT TabSeparated;

CREATE DATABASE oola_reporting_vcloud\nENGINE = Atomic
```

```
show create table oola_reporting_vcloud.events_shard;


 CREATE TABLE oola_reporting_vcloud.events_shard
(
    `user_id` UInt64,
    `entity_id` UInt64,
    `entity_type` String,
    `user_entity_status` String,
    `lesson_score` Float64,
    `learning_path_progress` Float64,
    `timestamp` DateTime64(3),
    `tenant_id` UInt64,
    `target_entity_id` UInt64,
    `target_entity_type` String,
    `event_name` String,
    `rating_score` Float64,
    `rating_total_entries` UInt32,
    `rating_average_score` Float64,
    `started_date` Nullable(DateTime64(3)),
    `required_count` UInt32,
    `completed_count` UInt32,
    `end_date` Nullable(DateTime64(3)),
    `expire_date` Nullable(DateTime64(3)),
    `valid_date` Nullable(DateTime64(3)),
    `achievement_date` Nullable(DateTime64(3))
)
ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/oola_reporting_vcloud/events_shard', '{replica}')
PARTITION BY toYYYYMM(timestamp)
PRIMARY KEY (tenant_id, user_id)
ORDER BY (tenant_id, user_id)
SETTINGS index_granularity = 8192
```

3. Database backup on the cluster fails with the error - CANNOT_BACKUP_TABLE

```
backup database oola_reporting_vcloud ON CLUSTER '{cluster}' TO Disk('backups', 'oola_reporting_vcloud-2023-11-10-0');

Query id: ebc35907-63fb-437d-a10c-42b1807209b6

Received exception from server (version 23.8.6):
Code: 647. DB::Exception: Received from localhost:9000. DB::Exception: Got error from chi%2Dvcloud%2Dch%2Dvcloud%2Dch%2D1%2D1:9000. DB::Exception: Table oola_reporting_vcloud.events_shard on replica chi-vcloud-ch-vcloud-ch-1-0 has part 201603_0_2_3 different from the part on replica chi-vcloud-ch-vcloud-ch-0-0 (checksum '2fb86be5208b5b5223e36600df06dc04' on replica chi-vcloud-ch-vcloud-ch-1-0 != checksum '8eedc42de3bed4506c915d26a38f9a49' on replica chi-vcloud-ch-vcloud-ch-0-0). (CANNOT_BACKUP_TABLE)
```

It is obviously that the replica **chi-vcloud-ch-vcloud-ch-1-0** has part 201603_0_2_3 different from the part on replica **chi-vcloud-ch-vcloud-ch-0-0**. 
This is because **chi-vcloud-ch-vcloud-ch-1-0** and **chi-vcloud-ch-vcloud-ch-0-0** belong to different shards.

```
chi-vcloud-ch-vcloud-ch-0-0 :) 

SELECT partition,name,min_block_number,max_block_number,hash_of_all_files,active FROM system.parts where database='oola_reporting_vcloud' and table='events_shard' limit 5 FORMAT Markdown;
```

| partition | name | min_block_number | max_block_number | hash_of_all_files | active |
|:-|:-|-:|-:|:-|-:|
| 201603 | 201603_0_2_3 | 0 | 2 | 8eedc42de3bed4506c915d26a38f9a49 | 1 |
| 201604 | 201604_0_4_2 | 0 | 4 | e4176bca77250c069719730bfed4119c | 1 |
| 201605 | 201605_0_10_4 | 0 | 10 | dcd5f0992c53db7c197e7deb006d3a54 | 1 |
| 201606 | 201606_0_27_7 | 0 | 27 | 8932508550d74340b17b8528ee3aadf5 | 1 |
| 201607 | 201607_0_2_2 | 0 | 2 | c2fb0f70dfdeb11f35db2163d7d4eeca | 1 |

```
chi-vcloud-ch-vcloud-ch-1-0 :)
SELECT partition,name,min_block_number,max_block_number,hash_of_all_files,active FROM system.parts where database='oola_reporting_vcloud' and table='events_shard' limit 5 FORMAT Markdown;
```

| partition | name | min_block_number | max_block_number | hash_of_all_files | active |
|:-|:-|-:|-:|:-|-:|
| 201603 | 201603_0_2_3 | 0 | 2 | 2fb86be5208b5b5223e36600df06dc04 | 1 |
| 201604 | 201604_0_3_2 | 0 | 3 | 0fd2b5819d777b0cda63b1da631ba825 | 1 |
| 201605 | 201605_0_2_2 | 0 | 2 | a0193ff721bb27c65bd839efb23240fd | 1 |
| 201606 | 201606_0_23_6 | 0 | 23 | c96f39586a4ca715087eba5f228c59b3 | 1 |
| 201608 | 201608_0_26_6 | 0 | 26 | d989729e72e415fe157ea77eae118a56 | 1 |

### PR DESCRIPTION
**Pull request by vitlibar**
### Changelog category:
- Bug Fix

### Changelog entry:
Fix making backup when multiple shards are used.
This PR fixes https://github.com/ClickHouse/ClickHouse/issues/56566

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit d2aaa270aebbb06922e033683f68b25d16ff2742 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/57684/d2aaa270aebbb06922e033683f68b25d16ff2742/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/7187438468">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/57684/d2aaa270aebbb06922e033683f68b25d16ff2742/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Comment by AntonFriberg** [comment]
What is the status of this one? Seems to have a few failing checks. Is it still being worked on?

**Comment by johnpptz** [comment]
Is there any information when this issue will be fixed?

**Comment by vitlibar** [comment]
> Is there any information when this issue will be fixed?

I'll take a look what is left to do here.

**Comment by eyakm1** [comment]
Hi! This bug blocks my progress, do you have any estimates of when this might get merged? (Just wondering, no pressure, thanks for your work!)

File: src/Backups/BackupCoordinationLocal.cpp [hunk 1]
```diff
@@ -33,42 +33,42 @@ Strings BackupCoordinationLocal::waitForStage(const String &, std::chrono::milli
     return {};
 }
 
-void BackupCoordinationLocal::addReplicatedPartNames(const String & table_shared_id, const String & table_name_for_logs, const String & replica_name, const std::vector<PartNameAndChecksum> & part_names_and_checksums)
```
Comment (vitlibar) [inline src/Backups/BackupCoordinationLocal.cpp:36]: The main problem with the earlier solution was that `table_shared_id` was used to identify sets of parts of a replicated table. That was not correct in case of using multiple shards - because parts on different shards are likely to be different. I've changed that solution - now a zookeeper path is used instead of `table_shared_id`. The zookeeper path is the same as it's set in the first argument of the create query which created a replicated table (i.e. it contains the shard name but doesn't the replica name)

File: src/Storages/MergeTree/registerStorageMergeTree.cpp [hunk 2]
```diff
@@ -122,6 +123,248 @@ static void verifySortingKey(const KeyDescription & sorting_key)
...
+        RenamingRestrictions renaming_restrictions;
+
+        extractZooKeeperPathAndReplicaNameFromEngineArgs(query, table_id, engine_name, engine_args, mode, context,
+                                                         zookeeper_path, replica_name, renaming_restrictions);
+
+        return zookeeper_path;
+    }
+    catch (...)
+    {
+        return {};
```
Comment (kssenii) [inline src/Storages/MergeTree/registerStorageMergeTree.cpp:365]: Should we at least log the exception? Do we really need to catch all exceptions or may be one concrete ones to avoid obscuring bugs?

**Review by kssenii — APPROVED** [review]

File: src/Storages/MergeTree/registerStorageMergeTree.cpp (hunk 2 above)
Comment (vitlibar) [reply src/Storages/MergeTree/registerStorageMergeTree.cpp]: done
