### PR TITLE
Better handling of join conditions involving IS NULL checks

### LINKED ISSUE #63318: Add support of a JOIN condition (t1.a IS NULL AND t2.a IS NULL)
**Describe the unexpected behaviour**

- At the moment ClickHouse doesn't support JOIN condition `(t1.a IS NULL AND t2.a IS NULL)`.

**How to reproduce**
* Queries to run that lead to unexpected result

```
SELECT
*
FROM
t1
LEFT JOIN t2 ON (
(
(t1.a = t2.a) AND (t1.a IS NOT NULL) AND (t2.a IS NOT NULL)
)
OR ( (t1.a IS NULL) AND (t2.a IS NULL))
);
```

**Expected behavior**

- The mentioned JOIN query should not return the error.

**Error message and/or stacktrace**

```
Cannot get JOIN keys from JOIN ON section
```
**Additional context**
- Related internal escalation https://github.com/ClickHouse/support-escalation/issues/1950.

### PR DESCRIPTION
**Pull request by vdimir**
### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
* Better handling of join conditions involving `IS NULL` checks (for example `ON (a = b AND (a IS NOT NULL) AND (b IS NOT NULL) ) OR ( (a IS NULL) AND (b IS NULL) )` is rewritten to `ON a <=> b`), fix incorrect optimization when condition other then `IS NULL` are present

close https://github.com/ClickHouse/ClickHouse/issues/63318

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit f5fb59db31074ac01d8ee3400a79baedb42e6223 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/65835/f5fb59db31074ac01d8ee3400a79baedb42e6223/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Style check</td><td>Runs a set of checks to keep the code style clean. If some of tests failed, see the related log from the report</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/65835/f5fb59db31074ac01d8ee3400a79baedb42e6223/style_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Comment by vdimir** [comment]
> Bugfix validation — New test(s) failed to reproduce a bug [Details](https://s3.amazonaws.com/clickhouse-test-reports/65835/d627709179db7b3af9b6e2f1b1c30b3e87da0cb1/bugfix_validation.html)

`Nothing to run` - check is broken 

> Stateless tests (debug, s3 storage) [4/6] — Tests are not finished, fail: 2, passed: 402, skipped: 10 [Details](https://s3.amazonaws.com/clickhouse-test-reports/65835/d627709179db7b3af9b6e2f1b1c30b3e87da0cb1/stateless_tests__debug__s3_storage__[4_6].html)

> Stateless tests (tsan, s3 storage) [1/5] — Tests are not finished, fail: 8, passed: 520, skipped: 7 [Details](https://s3.amazonaws.com/clickhouse-test-reports/65835/d627709179db7b3af9b6e2f1b1c30b3e87da0cb1/stateless_tests__tsan__s3_storage__[1_5].html)

`Logical error: 'Expected ReadBufferFromFile, but got DB::EmptyReadBuffer'` https://github.com/ClickHouse/ClickHouse/issues/65877


> Upgrade check (debug) — New settings are not reflected in settings changes history (see new_settings.txt) [Details](https://s3.amazonaws.com/clickhouse-test-reports/65835/d627709179db7b3af9b6e2f1b1c30b3e87da0cb1/upgrade_check__debug_.html)

Not an issue, `input_format_json_ignore_key_case` exists in master https://github.com/ClickHouse/ClickHouse/blob/63b031479c418297f98bd707a57db4853fd2f71c/src/Core/SettingsChangesHistory.cpp#L91

**Comment by Algunenano** [comment]
> Not an issue, input_format_json_ignore_key_case exists in master

100% an issue. Just not introduced here -> https://github.com/ClickHouse/ClickHouse/pull/65945

File: src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp [hunk 1]
```diff
@@ -93,47 +186,71 @@ class JoinOnLogicalExpressionOptimizerVisitor : public InDepthQueryTreeVisitorWi
...
+          * Then for each equality a = b we can check if we have operand (a IS NULL AND b IS NULL)
           */
         QueryTreeNodePtrWithHashMap<std::vector<size_t>> is_null_argument_to_indices;
 
+        bool is_anything_changed = false;
+
         for (const auto & argument : function_node.getArguments())
         {
-            or_operands.push_back(argument);
+            if (isNodeBooleanConstant(argument, false))
```
Comment (Algunenano) [inline src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp:197]: Should we also optimize for true? Any true found here should automatically allow ignoring any other conditions (and even remove the or if we wanted to and do a cross join).

Comment (Algunenano) [reply src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp:197]: An example:
```
EXPLAIN QUERY TREE
SELECT *
FROM t1
INNER JOIN t2 ON (t1.x = t2.x) OR ((t1.x IS NULL) AND (t2.x IS NULL)) OR (t1.x = 5)
ORDER BY t1.x ASC NULLS LAST
```

Works fine. Now if you replace (`t1.x = 5`) with `true`, nothing is optimized

**Review by Algunenano — COMMENTED** [review]
Seems there are

File: tests/queries/0_stateless/02911_join_on_nullsafe_optimization.sql [hunk 2]
```diff
@@ -1,30 +1,45 @@
...
+
+INSERT INTO t1n VALUES (1,42), (2,2), (3,3);
+INSERT INTO t2n VALUES (2,2), (3,33), (4,42);
+
 SET allow_experimental_analyzer = 1;
 
 -- { echoOn }
 SELECT * FROM t1 JOIN t2 ON (t1.x <=> t2.x OR (t1.x IS NULL AND t2.x IS NULL)) ORDER BY t1.x NULLS LAST;
 
-SELECT * FROM t1 JOIN t2 ON (t1.x <=> t2.x OR t1.x IS NULL AND t1.y <=> t2.y AND t2.x IS NULL) ORDER BY t1.x NULLS LAST;
```
[the remark this answers is not in the document]
Comment (vdimir) [reply tests/queries/0_stateless/02911_join_on_nullsafe_optimization.sql:15]: Put it back like that
https://github.com/ClickHouse/ClickHouse/blob/7a993d737b55177a27436f98159f0458f03610fc/tests/queries/0_stateless/02911_join_on_nullsafe_optimization.sql#L58-L65

File: src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp [hunk 3]
```diff
@@ -93,47 +186,71 @@ class JoinOnLogicalExpressionOptimizerVisitor : public InDepthQueryTreeVisitorWi
...
+                bool all_are_is_null = and_arguments.size() == 2 && isNodeFunction(and_arguments[0], "isNull") && isNodeFunction(and_arguments[1], "isNull");
+                if (all_are_is_null)
                 {
-                    auto * and_argument_function = and_argument->as<FunctionNode>();
-                    if (and_argument_function && and_argument_function->getFunctionName() == "isNull")
+                    is_null_argument_to_indices[getFunctionArgument(and_arguments.front(), 0)].push_back(or_operands.size() - 1);
+                    is_null_argument_to_indices[getFunctionArgument(and_arguments.back(), 0)].push_back(or_operands.size() - 1);
+                }
+
+                /// Expression `a = b AND (a IS NOT NULL) AND true AND (b IS NOT NULL)` we can be replaced with `a = b`
```
[the remark this answers is not in the document]
Comment (vdimir) [reply src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp:221]: Fixed and added this cases (before function was called only if there's OR function in ON)
https://github.com/ClickHouse/ClickHouse/blob/7a993d737b55177a27436f98159f0458f03610fc/tests/queries/0_stateless/02911_join_on_nullsafe_optimization.sql#L50-L56

File: tests/queries/0_stateless/02911_join_on_nullsafe_optimization.sql [hunk 4]
```diff
@@ -1,30 +1,45 @@
...
+SELECT * FROM t1 JOIN t2 ON (t1.x <=> t2.x OR t1.x IS NULL AND t2.x IS NULL) OR t1.y <=> t2.y ORDER BY t1.x NULLS LAST;
 
 SELECT * FROM t1 JOIN t2 ON (t1.x = t2.x OR t1.x IS NULL AND t2.x IS NULL) ORDER BY t1.x;
-SELECT * FROM t1 JOIN t2 ON t1.x <=> t2.x AND (t1.x = t1.y OR t1.x IS NULL AND t1.y IS NULL) ORDER BY t1.x;
+SELECT * FROM t1 JOIN t2 ON t1.x <=> t2.x AND ((t1.x = t1.y) OR t1.x IS NULL AND t1.y IS NULL) ORDER BY t1.x;
 
 SELECT * FROM t1 JOIN t2 ON (t1.x = t2.x OR t1.x IS NULL AND t2.x IS NULL) AND t1.y <=> t2.y ORDER BY t1.x NULLS LAST;
 
-SELECT * FROM t1 JOIN t2 ON (t1.x <=> t2.x OR t1.y <=> t2.y OR (t1.x IS NULL AND t1.y IS NULL AND t2.x IS NULL AND t2.y IS NULL)) ORDER BY t1.x NULLS LAST;
```
[the remark this answers is not in the document]
Comment (vdimir) [reply tests/queries/0_stateless/02911_join_on_nullsafe_optimization.sql:22]: Same as previous comment

File: src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp (hunk 1 above)
Comment (vdimir) [reply src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp]: In case we have `... OR true` the whole join expression is replaced with constant in some (another optimization) and we execute cross join. So, I suppose, we do not need to handle this case here.

File: src/Planner/PlannerJoins.cpp [hunk 5]
```diff
@@ -528,7 +528,7 @@ JoinClausesAndActions buildJoinClausesAndActions(
         size_t join_clause_key_nodes_size = join_clause.getLeftKeyNodes().size();
 
         if (join_clause_key_nodes_size == 0)
-            throw Exception(ErrorCodes::INVALID_JOIN_ON_EXPRESSION, "JOIN {} cannot get JOIN keys",
+            throw Exception(ErrorCodes::INVALID_JOIN_ON_EXPRESSION, "Cannot determine join keys in {}",
```
Comment (Algunenano) [inline src/Planner/PlannerJoins.cpp:531]: Unrelated to the changes, but there is an extra space for some reason:
```
Code: 403. DB::Exception: Cannot determine join keys in  INNER JOIN ... ON (t1.x = t2.x) OR (t1.x IS NULL). (INVALID_JOIN_ON_EXPRESSION)
```

Can't find why. We can fix it in the future

**Review by Algunenano — APPROVED** [review]

**Comment by vdimir** [comment]
> Stateless tests (release, old analyzer, s3, DatabaseReplicated) [3/4] — fail: 1, passed: 1596, skipped: 46 [Details](https://s3.amazonaws.com/clickhouse-test-reports/65835/7a993d737b55177a27436f98159f0458f03610fc/stateless_tests__release__old_analyzer__s3__databasereplicated__[3_4].html)

Interesting case, [pretty rare](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCAxODAgREFZCiAgICBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwIE9SIG5vdCBvbmx5X21hc3RlcikKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyBMSUtFICdGJScKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9jb250ZXh0X3JhdyBsaWtlICclQ2Fubm90IGVucXVldWUgcXVlcnklJwogICAgQU5EIGNoZWNrX25hbWUgbGlrZSAnJURhdGFiYXNlUmVwbGljYXRlZCUnCikKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVNDLCBjaGVja19uYW1lLCB0ZXN0X25hbWUKTElNSVQgMSBieSBzaGE=)

```
01710_minmax_count_projection_distributed_query 	FAIL 	0.51

2024-07-03 16:52:47 HTTPError
2024-07-03 16:52:47 Code: 500. Code: 341. DB::Exception: There was an error on [localhost:29000]: Code: 341. DB::Exception: Cannot enqueue query, because some replica are trying to enqueue another query. It may happen on high queries rate or, in rare cases, after connection loss. Client should retry. (UNFINISHED) (version 24.7.1.820). (UNFINISHED) (version 24.7.1.820)
```

Lot's of `KeeperDispatcher: Processing requests batch, size: 1, bytes: 228` after DDL is sheduled before the error. Perhaps indeed something with connection to keeper

https://pastila.nl/?0000b8b5/1dd4abe40a264602a50a7aeebf3bc1fa#orobxjCAlHV7HVcQ9nTm+A==

**Comment by vdimir** [comment]
> PullRequestCI / Builds_1 / s (package_aarch64, builder) / Build-package_aarch64 (pull_request) Failing after 32m [Details](https://github.com/ClickHouse/ClickHouse/actions/runs/9841248741/job/27168694311?pr=65835)
> PullRequestCI / Builds_Report / Builds (pull_request) Failing after 56s [Details](https://github.com/ClickHouse/ClickHouse/actions/runs/9841248741/job/27171195642?pr=65835)
> Builds Pending — 13 of 21 builds are missing. 18/31 artifact groups are OK [Details](https://s3.amazonaws.com/clickhouse-test-reports/65835/811cba0557e53ef1520af082643d0a1b81df2562/builds/report.html)

`/home/ubuntu/actions-runner/_work/_temp/0d8c4567-ff05-4ac4-ae0b-a3886e69008c.sh: line 5: 436647 Killed                  python3 "$GITHUB_WORKSPACE/tests/ci/ci.py" --infile ...`
