### PR TITLE
Fix MySQL text protocol DateTime formatting and LowCardinality(Nullable(T)) types reporting

### LINKED ISSUE #39297: [MySQL Interface] Nullable type reported as string to client
version: `22.6.3.35`

For `Float32` column server reports `FLOAT` type, but for `Nullable(Float32)` it returns `CHAR(0)`.

Same for `Float64`: `FLOAT` vs `CHAR(0)`

### PR DESCRIPTION
**Pull request by slvrtrn**
Resolves https://github.com/ClickHouse/ClickHouse/issues/39297

Related to the umbrella issue https://github.com/ClickHouse/ClickHouse/issues/55310 (fixes one of the issues mentioned there)

### Overview

* Fixed MySQL text protocol (`COM_QUERY`) DateTime64 formatting with precision higher than 6  - now it is correctly normalized to the expected 6 digits in the fractional part, as the client libraries expect.

```
mysql> SELECT toDateTime64('2020-02-29 17:54:55.123123476', 7);
+--------------------------------------------------+
| toDateTime64('2020-02-29 17:54:55.123123476', 7) |
+--------------------------------------------------+
| 2020-02-29 17:54:55.123123                       |
+--------------------------------------------------+
```

* Introduced the `removeLowCardinalityAndNullable` function that removes `LowCardinality` and `Nullable` from the provided data type in the correct order if necessary.
* Fixed incorrect `removeLowCardinality`/`removeNullable` usage across the codebase (wrong order of applying these functions). NB: correct usages were not migrated to use the `removeLowCardinalityAndNullable` function; it is better to do this as a follow-up.
* Added more MySQL text protocol tests; now, the same extended set of tests is executed not only with the prepared statements/binary protocol but with the text protocol as well.
* Removed old Java client tests and the related files as those tests are, essentially, surpassed by `test_java_client_text` and `test_java_client_binary` now.
* MySQL `ProtocolText`/`ProtocolBinary` parts were refactored a bit with the introduction of `MySQLUtils` to allow reusing the common code across them.

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fixed MySQL text protocol (`COM_QUERY`) `DateTime64` formatting when precision is higher than 6 - now it is correctly normalized to the expected 6 digits in the fractional part. Fixed MySQL text/binary protocol (`COM_QUERY`/`COM_STMT_EXECUTE`) incorrect type reporting for `LowCardinality(Nullable(T))` columns in the result set.

### CODE REVIEW

**Comment by robot-ch-test-poll2** [comment]
*This is an automated comment for commit e06d3ca1a55dd1675ab22e5fa9af1267ce274cc7 with description of existing statuses. It's updated for the latest CI running*

[❌ Click here](https://s3.amazonaws.com/clickhouse-test-reports/55479/e06d3ca1a55dd1675ab22e5fa9af1267ce274cc7/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6473147249">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/55479/e06d3ca1a55dd1675ab22e5fa9af1267ce274cc7/ci_running.html">❌ failure</a></td></tr>
<tbody>
</table>

File: src/Interpreters/parseColumnsListForTableFunction.cpp [hunk 1]
```diff
@@ -48,7 +48,7 @@ void validateDataType(const DataTypePtr & type, const DataTypeValidationSettings
 
     if (!settings.allow_suspicious_fixed_string_types)
     {
-        auto basic_type = removeLowCardinality(removeNullable(type));
+        auto basic_type = removeLowCardinalityAndNullable(type);
```
Comment (slvrtrn) [inline src/Interpreters/parseColumnsListForTableFunction.cpp:51]: Here and in [InterpreterCreateQuery.cpp](https://github.com/ClickHouse/ClickHouse/pull/55479/files#diff-da014867807d23b4f33a776259af48f88e03f9683f334cceed5773b51af54edb) it was misused. I am not sure if it was affecting anything, though.

File: tests/integration/test_mysql_protocol/java_client_test.sql [hunk 2]
```diff
@@ -17,7 +17,7 @@ CREATE OR REPLACE TABLE ps_simple_data_types
     b     Boolean
 ) ENGINE MergeTree ORDER BY i8;
 
-INSERT INTO ps_simple_data_types
+INSERT INTO simple_data_types
```
Comment (slvrtrn) [inline tests/integration/test_mysql_protocol/java_client_test.sql:20]: Removed the `ps_` (prepared statements) prefix as this dataset is now used for both text/binary protocols.

File: tests/integration/test_mysql_protocol/java_client_text.reference [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+f32 type is FLOAT, value: 1.234000
+f64 type is DOUBLE, value: 3.352451
+b type is TINYINT, value: false
+
+### testStringTypes
+Row #1
+s type is CHAR, value: 42
+sn type is CHAR, value: null
+lc type is CHAR, value: test
+nlc type is CHAR, value: null
```
Comment (slvrtrn) [inline tests/integration/test_mysql_protocol/java_client_text.reference:40]: This entire reference was copy-pasted only because of how NULLs are reported via binary (`ᴺᵁᴸᴸ`) vs text (`null`). We need to double-check whether our text protocol implementation follows MySQL standard, and maybe this entire copy-pasted reference will be removed as a follow-up.

File: tests/integration/test_mysql_protocol/test.py [hunk 4]
```diff
@@ -790,7 +792,11 @@ def test_mysqljs_client(started_cluster, nodejs_container):
     assert code == 1
 
 
-def test_java_client(started_cluster, java_container):
+@pytest.mark.skip(
+    """Deprecated in favor of test_java_client as the scope of the tests is higher,
+    and it covers both binary and test protocols"""
+)
+def test_java_client_old(started_cluster, java_container):
```
Comment (slvrtrn) [inline tests/integration/test_mysql_protocol/test.py:799]: Maybe we can remove this, the related reference file, and the related [Java file](https://github.com/slvrtrn/ClickHouse/blob/fix-mysql-datetime-incompatibilities/docker/test/integration/mysql_java_client/Test.java) altogether, as I am not sure if it is worth keeping it as the new set of tests is much larger in terms of coverage for all MySQL protocol variations.

File: tests/integration/test_mysql_protocol/test.py [hunk 5]
```diff
@@ -836,33 +842,32 @@ def test_java_client(started_cluster, java_container):
     assert stdout.decode() == reference
 
 
-def test_prepared_statements(started_cluster, java_container):
-    with open(os.path.join(SCRIPT_DIR, "prepared_statements.reference")) as fp:
+def test_java_client_text(started_cluster, java_container):
```
Comment (slvrtrn) [inline tests/integration/test_mysql_protocol/test.py:845]: Now runs in both binary (server prepared statements) and text (regular queries) variants.

File: src/Core/MySQL/MySQLUtils.h [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+{
+namespace MySQLUtils
+{
+/// Splits DateTime64 column data at a certain row number into whole and fractional part
+/// Additionally, normalizes the fractional part as if it was scale 6 for MySQL compatibility purposes
+DecimalUtils::DecimalComponents<DateTime64> getNormalizedDateTime64Components(DataTypePtr data_type, ColumnPtr col, int row_num);
+
+/// If a column is ColumnSparse/ColumnLowCardinality/ColumnNullable, it is unwrapped in a correct order;
+/// otherwise, the original column is returned
+ColumnPtr getBaseColumn(const DB::Columns & columns, size_t i);
```
Comment (slvrtrn) [inline src/Core/MySQL/MySQLUtils.h:17]: Maybe makes sense to move elsewhere if there is a use for it in the other parts of the code.

File: tests/integration/test_mysql_protocol/test.py (hunk 4 above)
Comment (slvrtrn) [reply tests/integration/test_mysql_protocol/test.py]: Removed.

**Comment by MaceWindu** [comment]
> DateTime64 formatting with precision higher than 6 - now it is correctly normalized to the expected 6 digits in the fractional part, as the client libraries expect.

I personally would prefer to receive values with precision > 6 as strings as it was before 23.9 release to avoid data loss

**Comment by slvrtrn** [comment]
@MaceWindu, I see. Maybe we could make this configurable. 
In some scenarios, it is preferred just to truncate (think BI tools looking into a table with a `created` column defined as `DateTime64(9)`); in others - report as strings.
Could you create a feature request?

**Comment by MaceWindu** [comment]
@slvrtrn done #55502

File: src/Core/MySQL/MySQLUtils.h (hunk 6 above)
Comment (rschu1ze) [reply src/Core/MySQL/MySQLUtils.h:19]: Fine to keep it here, imho - the code is quite simple and easy to replicate.

File: src/Core/MySQL/MySQLUtils.cpp [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+namespace DB
+{
+namespace MySQLProtocol
+{
+namespace MySQLUtils
+{
+
+DecimalUtils::DecimalComponents<DateTime64>
+getNormalizedDateTime64Components(const DataTypePtr data_type, const ColumnPtr col, const int row_num)
```
Comment (rschu1ze) [inline src/Core/MySQL/MySQLUtils.cpp:16]: Let's pass a `size_t` (just in case a part grows > 2 billion rows which sounds not too far fetched)

**Review by rschu1ze — APPROVED** [review]

File: src/Core/MySQL/MySQLUtils.cpp (hunk 7 above)
Comment (rschu1ze) [reply src/Core/MySQL/MySQLUtils.cpp:16]: I'll do that in one of my PRs

Comment (slvrtrn) [reply src/Core/MySQL/MySQLUtils.cpp:16]: I agree with this, I should've fixed it earlier, as that's how it was originally in ProtocolText, so that is why I kept using it in new implementations. Let's fix both ResultSetRow for text/binary and utils, then :+1:
