### PR TITLE
Remove data from all disks after DROP with Lazy database.

### LINKED ISSUE #62699: Log engines with object storage policy do not delete data on the disk after drop query.
**Describe the unexpected behaviour**
  
The `drop` query for `*Log` tables + object storage disk keeps data on the disk.   

**How to reproduce**
CH : `24.3.2.23 `
```
CREATE DATABASE lazy_s3 engine=Lazy(60)
CREATE TABLE lazy_s3.tiny (a int) engine=TinyLog() settings storage_policy='object_storage'
INSERT INTO lazy_s3.tiny SELECT number FROM numbers(100)


CREATE TABLE lazy_s3.stripe (a int) engine=StripeLog() settings storage_policy='object_storage'
INSERT INTO lazy_s3.stripe SELECT number FROM numbers(100)

CREATE TABLE lazy_s3.log (a int) engine=Log() settings storage_policy='object_storage'
INSERT INTO lazy_s3.log SELECT number FROM numbers(100)

DROP TABLE lazy_s3.log
DROP TABLE lazy_s3.tiny
DROP TABLE lazy_s3.stripe
```
Result:
```
/var/lib/clickhouse/disks/object_storage/data/lazy_s3 # ls -la /var/lib/clickhouse/disks/object_storage/data/lazy_s3/log/
total 20
drwxr-x--- 2 clickhouse clickhouse 4096 Apr 16 16:17 .
drwxr-x--- 5 clickhouse clickhouse 4096 Apr 16 16:17 ..
-rw-r----- 1 clickhouse clickhouse   50 Apr 16 16:17 a.bin
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:17 __marks.mrk
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:17 sizes.json

/var/lib/clickhouse/disks/object_storage/data/lazy_s3 # ls -la /var/lib/clickhouse/disks/object_storage/data/lazy_s3/stripe
total 20
drwxr-x--- 2 clickhouse clickhouse 4096 Apr 16 16:17 .
drwxr-x--- 5 clickhouse clickhouse 4096 Apr 16 16:17 ..
-rw-r----- 1 clickhouse clickhouse   50 Apr 16 16:17 data.bin
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:17 index.mrk
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:17 sizes.json

/var/lib/clickhouse/disks/object_storage/data/lazy_s3 # ls -la /var/lib/clickhouse/disks/object_storage/data/lazy_s3/tiny
total 16
drwxr-x--- 2 clickhouse clickhouse 4096 Apr 16 16:16 .
drwxr-x--- 5 clickhouse clickhouse 4096 Apr 16 16:17 ..
-rw-r----- 1 clickhouse clickhouse   50 Apr 16 16:16 a.bin
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:16 sizes.json
```
For default storage policy works as expected:
```
# The same queries to the ch, but all tables with default storage policy  

/var/lib/clickhouse/data/lazy # ls -la 
total 8
drwxr-x--- 2 clickhouse clickhouse 4096 Apr 16 16:32 .
drwxr-x--- 8 clickhouse clickhouse 4096 Apr 16 16:47 ..
```

Moreover we can recreate table:
```
CREATE TABLE lazy_s3.stripe (a int) engine=StripeLog() settings storage_policy='object_storage'
```
And get access to the already deleted data:
```
 SELECT count(*) FROM lazy_s3.stripe

SELECT count(*)
FROM lazy_s3.stripe

Query id: f3414ed9-420c-450b-88ad-29ba748e2d68

   ┌─count()─┐
1. │     100 │
   └─────────┘

```

### PR DESCRIPTION
**Pull request by MikhailBurdukov**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Remove the data from all disks after DROP with the Lazy database engines. Without these changes, orhpaned will remain on the disks. 

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Example:
```
CREATE DATABASE lazy_s3 engine=Lazy(60)
CREATE TABLE lazy_s3.stripe (a int) engine=StripeLog() settings storage_policy='object_storage'
INSERT INTO lazy_s3.stripe SELECT number FROM numbers(100)
DROP TABLE lazy_s3.stripe
```
Without changes:
```
/var/lib/clickhouse/disks/object_storage/data/lazy_s3 # ls -la /var/lib/clickhouse/disks/object_storage/data/lazy_s3/stripe
total 20
drwxr-x--- 2 clickhouse clickhouse 4096 Apr 16 16:17 .
drwxr-x--- 5 clickhouse clickhouse 4096 Apr 16 16:17 ..
-rw-r----- 1 clickhouse clickhouse   50 Apr 16 16:17 data.bin
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:17 index.mrk
-rw-r----- 1 clickhouse clickhouse   48 Apr 16 16:17 sizes.json
```
With changes:
```
/var/lib/clickhouse/disks/object_storage/data/lazy_s3 # ls -la /var/lib/clickhouse/disks/object_storage/data/lazy_s3
total 8
drwxr-x--- 2 clickhouse clickhouse 4096 Apr 16 16:32 .
drwxr-x--- 8 clickhouse clickhouse 4096 Apr 16 16:47 ..
```

Resolves: #62699

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

<details>
    <summary>Modify your CI run</summary>

**NOTE:** If your merge the PR with modified CI you **MUST KNOW** what you are doing
**NOTE:** Checked options will be applied if set before CI RunConfig/PrepareRunConfig step

#### Include tests (required builds will be added automatically):
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Unit tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with Analyzer
- [ ]  All with Azure
- [ ]  Add your option here

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [ ]  All with ASAN
- [ ]  All with TSAN
- [ ]  All with MSAN
- [ ]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [ ]  Add your option here

#### Extra options:
- [ ]  do not test (only style check)
- [ ]  disable merge-commit (no merge from master before tests)
- [ ]  disable CI cache (job reuse)

#### Only specified batches in multi-batch jobs:
- [ ]  1
- [ ]  2
- [ ]  3
- [ ]  4

</details>

### CODE REVIEW

**Comment by robot-ch-test-poll3** [comment]
*This is an automated comment for commit ae10e7ded1080d5bd72372dc611cdcb7b96137ef with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/63848/ae10e7ded1080d5bd72372dc611cdcb7b96137ef/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>PR Check</td><td>There's no description for the check yet, please add it to tests/ci/ci_config.py:CHECK_DESCRIPTIONS</td><td>✅ success</td></tr>
<tbody>
</table>
</details>

File: src/Databases/DatabaseOnDisk.cpp [hunk 1]
```diff
@@ -324,31 +325,36 @@ void DatabaseOnDisk::dropTable(ContextPtr local_context, const String & table_na
...
         fs::rename(table_metadata_path, table_metadata_path_drop);
         renamed = true;
-        table->drop();
-        table->is_dropped = true;
-
-        fs::path table_data_dir(local_context->getPath() + table_data_path_relative);
-        if (fs::exists(table_data_dir))
-            (void)fs::remove_all(table_data_dir);
+        // The table might be not loaded for Lazy database engine.
+        if (table)
```
Comment (alesapin) [inline src/Databases/DatabaseOnDisk.cpp:334]: I don't see how is it possible. We will throw exception https://github.com/ClickHouse/ClickHouse/blob/8f5c8fdb27c2528b3ff4d0bad31b7047ec690949/src/Databases/DatabaseLazy.cpp#L197-L198.

File: src/Databases/DatabaseOnDisk.cpp [hunk 2]
```diff
@@ -324,31 +325,36 @@ void DatabaseOnDisk::dropTable(ContextPtr local_context, const String & table_na
...
         LOG_WARNING(log, getCurrentExceptionMessageAndPattern(/* with_stacktrace */ true));
-        attachTable(local_context, table_name, table, table_data_path_relative);
+        if (table)
+            attachTable(local_context, table_name, table, table_data_path_relative);
         if (renamed)
             fs::rename(table_metadata_path_drop, table_metadata_path);
         throw;
     }
 
+    for (const auto & [disk_name, disk] : getContext()->getDisksMap())
```
Comment (alesapin) [inline src/Databases/DatabaseOnDisk.cpp:350]: If (table == nullptr) is possible than probably we are doing wrong thing here. We will remove all info about this table from disk, but for example may still have something in ZK.

**Review by alesapin — CHANGES_REQUESTED** [review]
Need to clarify

File: src/Databases/DatabaseOnDisk.cpp (hunk 1 above)
Comment (MikhailBurdukov) [reply src/Databases/DatabaseOnDisk.cpp:334]: As I understood:
https://github.com/ClickHouse/ClickHouse/blob/8f5c8fdb27c2528b3ff4d0bad31b7047ec690949/src/Databases/DatabaseLazy.cpp#L192-L205

If the table was recently touched it will be present in `tables_cache[name].table`, if not here will be nullptr.
So the return value from  Detach function is `it->second.table` not just `it`.

Here we are loading the table if `tables_cache[name].table` is a null: https://github.com/ClickHouse/ClickHouse/blob/8f5c8fdb27c2528b3ff4d0bad31b7047ec690949/src/Databases/DatabaseLazy.cpp#L133

Here we are doing reset if lifetime is expired:
https://github.com/ClickHouse/ClickHouse/blob/8f5c8fdb27c2528b3ff4d0bad31b7047ec690949/src/Databases/DatabaseLazy.cpp#L284 
https://github.com/ClickHouse/ClickHouse/blob/8f5c8fdb27c2528b3ff4d0bad31b7047ec690949/src/Databases/DatabaseLazy.cpp#L306-L307


Summary: `table` might be empty if it has not been touched recently

File: src/Databases/DatabaseOnDisk.cpp (hunk 2 above)
Comment (MikhailBurdukov) [reply src/Databases/DatabaseOnDisk.cpp:350]: >but for example may still have something in ZK

Agree, but rn we aren't doing it too... BTW all my changes here is just remove not only from the default disk but from all. So it should not change the behaviour of this class with ZK.

**Review by alesapin — APPROVED** [review]
Okay, but still it's not complete solution, garbage may be left in ZK
