### PR TITLE
Back/Restore concurrency check on previous fails

### LINKED ISSUE #45486: Flaky test_backup_restore_on_cluster/test_disallow_concurrency.py
This test is to check if disallowing of concurrent backups & restores works as expected. 
When one backup/restore fails, the status is not updated properly, thus we need to set the status of backup/restore so that other nodes in cluster are aware of failures.

Some occurences : 
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2JhY2t1cF9yZXN0b3JlX29uX2NsdXN0ZXIvdGVzdF9kaXNhbGxvd19jb25jdXJyZW5jeS5weSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

### PR DESCRIPTION
**Pull request by SmitaRKulkarni**
Changelog category (leave one):
* Bug Fix

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md): 
Updated to add error or completed status in zookeeper for a cluster for backup/restore, to avoid interpreting previously failed backup/restore when zookeeper is unable to remove nodes resolves #45486

### CODE REVIEW

File: src/Backups/IBackupCoordination.h [hunk 1]
```diff
@@ -22,6 +22,7 @@ class IBackupCoordination
 
     /// Sets the current stage and waits for other hosts to come to this stage too.
     virtual void setStage(const String & new_stage, const String & message) = 0;
+    virtual void setStageForCluster(const String & new_stage) = 0;
```
Comment (vitlibar) [inline src/Backups/IBackupCoordination.h:25]: What is the "stage for cluster"? Each host has its own stage.

File: src/Backups/RestoreCoordinationRemote.cpp [hunk 2]
```diff
@@ -95,8 +95,14 @@ void RestoreCoordinationRemote::setStage(const String & new_stage, const String
...
 }
 
+void RestoreCoordinationRemote::setStageForCluster(const String & new_stage)
+{
+    stage_sync->setStageForCluster(new_stage);
+}
+
 void RestoreCoordinationRemote::setError(const Exception & exception)
 {
+    stage_sync->setStageForCluster(Stage::ERROR);
```
Comment (vitlibar) [inline src/Backups/RestoreCoordinationRemote.cpp:105]: `stage_sync->setError()` already adds a ZooKeeper node `<backup_path>/stage/error` with information about the error. Why isn't it enough?

**Comment by vitlibar** [comment]
Can we just use `alive` nodes? I mean while a backup or restore process is working there are always `alive` nodes in ZooKeeper. So all you need is to check if there is other backup/restore process with alive nodes.

**Comment by SmitaRKulkarni** [comment]
I dont think we can use just alive nodes. It is a good indication to check if there are ongoing backup/restore, but if we decide to proceed with a backup/restore, we need to inform zookeeper (other hosts), and this happens before each host gets the query & we cannot create alive nodes yet. So I had added 'SCHEDULED_TO_START' phase, if this is present then no other backp/restore will start. The changes in this PR update this stage to COMPLETED or ERROR after success or failure of backup/restore.

File: src/Backups/RestoreCoordinationRemote.cpp (hunk 2 above)
Comment (SmitaRKulkarni) [reply src/Backups/RestoreCoordinationRemote.cpp:105]: In some of our CI fails, I see that zookeeper is not able to delete all the nodes. And at times, it deletes the error node, but the stage (which was added for concurrency check) remains, causing misinterpretation.

File: src/Backups/IBackupCoordination.h (hunk 1 above)
Comment (SmitaRKulkarni) [reply src/Backups/IBackupCoordination.h:25]: When we check for concurrency and allow a backup/restore to proceed, we need to inform zookeeper that this backup/restore is going to be processed even before each host gets the query. As mentioned in above comment, here having a state is needed.

Comment (vitlibar) [inline src/Backups/IBackupCoordination.h:25]: I think we don't need this extra function because there are only three stages which should be `for cluster`: "error", "completed" and "sheduled for start". I mean `BackupCoordinationStageSync` can understand by itself where to store a passed stage.

File: src/Backups/BackupCoordinationStage.h [hunk 3]
```diff
@@ -43,6 +43,10 @@ namespace BackupCoordinationStage
 
     /// Coordination stage meaning that a host finished its work.
     constexpr const char * COMPLETED = "completed";
+
+    /// Coordination stage meaning that backup/restore has failed due to an error
+    /// Check '/error' for the error message
+    constexpr const char * ERROR = "error";
 }
 
 }
```
Comment (vitlibar) [inline src/Backups/BackupCoordinationStage.h:52]: For consistency it seems it's better to set the stage `SCHEDULED_TO_START` via `backup_coordination->setStage()` like we do it with other stages instead of calling

```
zk->trySet(path, Stage::SCHEDULED_TO_START, stat.version)
```
in `hasConcurrentRestores()`.

File: src/Backups/IBackupCoordination.h (hunk 1 above)
Comment (vitlibar) [reply src/Backups/IBackupCoordination.h:25]: We could also rewrite `waitForStage()` to make it subscribe for the value of the root node instead of subscribing for children of the `stage` node. Just to simplify the code.

Comment (SmitaRKulkarni) [reply src/Backups/IBackupCoordination.h]: Sorry I didnt get how we can change `waitForStage()`, as this is used for the per node queries, so we will need to check the stage in the alive node.

File: src/Backups/BackupCoordinationStage.h (hunk 3 above)
Comment (SmitaRKulkarni) [reply src/Backups/BackupCoordinationStage.h:52]: I used `trySet` here because I want to verify the `stat.version ` as well (to confirm no other nodes were added during concurrency check)

**Review by vitlibar — APPROVED** [review]

**Comment by vitlibar** [comment]
@SmitaRKulkarni Have you noticed that one of the CI builds failed?

**Comment by SmitaRKulkarni** [comment]
> @SmitaRKulkarni Did you notice that one of the CI builds failed?
Fixed the build issue

**Comment by tavplubix** [comment]
Unit tests (asan) - `IOResourceDynamicResourceManager` was broken in master
