### PR TITLE
Auto cluster table function one subquery inside FROM

### LINKED ISSUE #92264: Automatic cluster table functions should be used for subqueries, if it's the only subquery inside FROM.
### Company or project name

ClickHouse

### Describe the situation

Currently, the following query
`SELECT * FROM (SELECT * FROM s3(...))`
does not automatically use the `s3Cluster` table function.

### Which ClickHouse versions are affected?

All.

### How to reproduce

.

### Expected performance

If a query has only one subquery inside the FROM section, apply the transformation recursively.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by phulv94**
### Changelog category (leave one):
- Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Use automatic cluster table functions for single subquery in FROM.
Closes [#92264](https://github.com/ClickHouse/ClickHouse/issues/92264).

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### Version info
- Merged into: `26.2.1.494`

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
@phulv94, let's add a test targeting this specific change.

**Comment by phulv94** [comment]
> @phulv94, let's add a test targeting this specific change.

Done. I've added a dedicated test for this change.

**Review by alexey-milovidov — COMMENTED** [review]
Looks good! (Also, all tests are green, which is :man_cook: :kiss:)

Let's do two minor changes:
- add a comment inside needChildVisit;
- add a comment before subquery_in_from_count;
- instead of modifying an existing test, add a new one.

Also, I'd like @thevar1able to review as well.

File: src/Analyzer/Resolve/TableFunctionsWithClusterAlternativesVisitor.h [hunk 1]
```diff
@@ -17,23 +17,43 @@ class TableFunctionsWithClusterAlternativesVisitor : public InDepthQueryTreeVisi
...
+                    if (parent_query && parent_query->getJoinTree().get() == child.get())
+                    {
+                        ++subquery_in_from_count;
+                    }
+                }
+            }
+        }
+
+        return true;
+    }
```
Comment (thevar1able) [inline src/Analyzer/Resolve/TableFunctionsWithClusterAlternativesVisitor.h]: Why do we count `subquery_in_from_count` in `needChildVisit` instead of `visitImpl`?

Comment (phulv94) [reply src/Analyzer/Resolve/TableFunctionsWithClusterAlternativesVisitor.h]: In `visitImpl`, we don’t have access to the parent node context.
Therefore, I perform the counting inside `needChildVisit`, since `needChildVisit` is called right after entering `visitImpl`.

**Review by thevar1able — APPROVED** [review]

File: src/Analyzer/Resolve/TableFunctionsWithClusterAlternativesVisitor.h (hunk 1 above)
Comment (thevar1able) [reply src/Analyzer/Resolve/TableFunctionsWithClusterAlternativesVisitor.h]: Do we need to match parent and child? Can we just check that number of subqueries is exactly one?

Comment (phulv94) [reply src/Analyzer/Resolve/TableFunctionsWithClusterAlternativesVisitor.h]: Yes, we can check that number of subqueries <= 1
