### PR TITLE
Fix crash when calculating the size of a block with empty columns

### LINKED ISSUE #83244: Assertion error with NULL table, async inserts and JSONColumns
### Describe the bug

This is happening since v25.6

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/e7ed8700-eb94-4dc4-8f34-2df8123e630a

### Error message and/or stacktrace

Stack trace:

```
clickhouse: contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:201: T *boost::intrusive_ptr<const DB::IColumn>::operator->() const [T = const DB::IColumn]: Assertion `px != 0' failed.
2025.07.04 17:40:02.870123 [ 1562200 ] {} <Trace> BaseDaemon: Received signal 6
2025.07.04 17:40:02.870271 [ 1562941 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2025.07.04 17:40:02.870300 [ 1562941 ] {} <Fatal> BaseDaemon: (version 25.7.1.2256 (official build), build id: FF4A270C26B03771D09413B98B31C8E17F4AF4B2, git hash: 4409a3e94d33eb3a4c8618b8de2dcdb22bafd586, architecture: x86_64) (from thread 1562202) Received signal 6
2025.07.04 17:40:02.870311 [ 1562941 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2025.07.04 17:40:02.870312 [ 1562941 ] {} <Fatal> BaseDaemon: 
2025.07.04 17:40:02.870318 [ 1562941 ] {} <Fatal> BaseDaemon: Stack trace: 0x000074b5468a50bd 0x000074b5468456de 0x000074b5468288cd 0x000074b546828830 0x00005e58e5273210 0x00005e58e633625b 0x00005e58e63373ef 0x00005e58e90031d4 0x00005e58e8ff72f5 0x00005e58e8fed77a 0x00005e58e9006b64 0x00005e58f0eb11a7 0x00005e58f0eb16a5 0x00005e58f0e59c7f 0x00005e58f0e57811 0x000074b5468a2ef1 0x000074b54693445c
2025.07.04 17:40:02.870347 [ 1562941 ] {} <Fatal> BaseDaemon: ########################################
2025.07.04 17:40:02.870386 [ 1562941 ] {} <Fatal> BaseDaemon: (version 25.7.1.2256 (official build), build id: FF4A270C26B03771D09413B98B31C8E17F4AF4B2, git hash: 4409a3e94d33eb3a4c8618b8de2dcdb22bafd586) (from thread 1562202) (query_id: fade8145-ed0f-4929-abc4-77414c219358) (query: INSERT INTO TABLE t0 (c0) FROM INFILE '/var/lib/clickhouse/user_files/table.data' FORMAT JSONColumns;) Received signal Aborted (6)
2025.07.04 17:40:02.870402 [ 1562941 ] {} <Fatal> BaseDaemon: 
2025.07.04 17:40:02.870423 [ 1562941 ] {} <Fatal> BaseDaemon: Stack trace: 0x000074b5468a50bd 0x000074b5468456de 0x000074b5468288cd 0x000074b546828830 0x00005e58e5273210 0x00005e58e633625b 0x00005e58e63373ef 0x00005e58e90031d4 0x00005e58e8ff72f5 0x00005e58e8fed77a 0x00005e58e9006b64 0x00005e58f0eb11a7 0x00005e58f0eb16a5 0x00005e58f0e59c7f 0x00005e58f0e57811 0x000074b5468a2ef1 0x000074b54693445c
2025.07.04 17:40:02.870477 [ 1562941 ] {} <Fatal> BaseDaemon: 3. __GI___pthread_kill @ 0x00000000000a50bd
2025.07.04 17:40:02.870495 [ 1562941 ] {} <Fatal> BaseDaemon: 4. __GI_raise @ 0x00000000000456de
2025.07.04 17:40:02.870508 [ 1562941 ] {} <Fatal> BaseDaemon: 5. abort @ 0x00000000000288cd
2025.07.04 17:40:02.870525 [ 1562941 ] {} <Fatal> BaseDaemon: 6. __GI___assert_perror_fail @ 0x0000000000028830
2025.07.04 17:40:02.893842 [ 1562941 ] {} <Fatal> BaseDaemon: 7.0. inlined from contrib/boost/boost/smart_ptr/intrusive_ptr.hpp:201: boost::intrusive_ptr<DB::IColumn const>::operator->() const
2025.07.04 17:40:02.893876 [ 1562941 ] {} <Fatal> BaseDaemon: 7. src/Core/Block.cpp:447: ? @ 0x0000000019052210
2025.07.04 17:40:02.936840 [ 1562941 ] {} <Fatal> BaseDaemon: 8.0. inlined from contrib/llvm-project/libcxx/include/variant:508: decltype(auto) std::__variant_detail::__visitation::__base::__visit_alt[abi:se190107]<std::__variant_detail::__visitation::__variant::__value_visitor<DB::AsynchronousInsertQueue::DataChunk::byteSize() const::'lambda'<typename $T>($T const&)>, std::__variant_detail::__impl<String, DB::Block> const&>($T&&, std::__variant_detail::__impl<String, DB::Block> const&)
2025.07.04 17:40:02.936883 [ 1562941 ] {} <Fatal> BaseDaemon: 8.1. inlined from contrib/llvm-project/libcxx/include/variant:593: decltype(auto) std::__variant_detail::__visitation::__variant::__visit_alt[abi:se190107]<std::__variant_detail::__visitation::__variant::__value_visitor<DB::AsynchronousInsertQueue::DataChunk::byteSize() const::'lambda'<typename $T>($T const&)>, DB::AsynchronousInsertQueue::DataChunk const&>($T&&, DB::AsynchronousInsertQueue::DataChunk const&)
2025.07.04 17:40:02.936964 [ 1562941 ] {} <Fatal> BaseDaemon: 8.2. inlined from contrib/llvm-project/libcxx/include/variant:605: decltype(auto) std::__variant_detail::__visitation::__variant::__visit_value[abi:se190107]<DB::AsynchronousInsertQueue::DataChunk::byteSize() const::'lambda'<typename $T>($T const&), DB::AsynchronousInsertQueue::DataChunk const&>($T&&, DB::AsynchronousInsertQueue::DataChunk const&)
2025.07.04 17:40:02.936991 [ 1562941 ] {} <Fatal> BaseDaemon: 8.3. inlined from contrib/llvm-project/libcxx/include/variant:1576: decltype(auto) std::visit[abi:se190107]<DB::AsynchronousInsertQueue::DataChunk::byteSize() const::'lambda'<typename $T>($T const&), DB::AsynchronousInsertQueue::DataChunk const&, void>($T&&, DB::AsynchronousInsertQueue::DataChunk const&)
2025.07.04 17:40:02.937006 [ 1562941 ] {} <Fatal> BaseDaemon: 8.4. inlined from src/Interpreters/AsynchronousInsertQueue.h:102: DB::AsynchronousInsertQueue::DataChunk::byteSize() const
2025.07.04 17:40:02.937034 [ 1562941 ] {} <Fatal> BaseDaemon: 8. src/Interpreters/AsynchronousInsertQueue.cpp:497: DB::AsynchronousInsertQueue::pushDataChunk(std::shared_ptr<DB::IAST>, DB::AsynchronousInsertQueue::DataChunk&&, std::shared_ptr<DB::Context const>) @ 0x000000001a11525b
2025.07.04 17:40:02.977925 [ 1562941 ] {} <Fatal> BaseDaemon: 9. src/Interpreters/AsynchronousInsertQueue.cpp:442: DB::AsynchronousInsertQueue::pushQueryWithBlock(std::shared_ptr<DB::IAST>, DB::Block&&, std::shared_ptr<DB::Context const>) @ 0x000000001a1163ef
2025.07.04 17:40:03.020323 [ 1562941 ] {} <Fatal> BaseDaemon: 10. src/Server/TCPHandler.cpp:1158: DB::TCPHandler::processAsyncInsertQuery(DB::QueryState&, DB::AsynchronousInsertQueue&) @ 0x000000001cde21d4
2025.07.04 17:40:03.064925 [ 1562941 ] {} <Fatal> BaseDaemon: 11. src/Server/TCPHandler.cpp:1229: DB::TCPHandler::processInsertQuery(DB::QueryState&) @ 0x000000001cdd62f5
2025.07.04 17:40:03.097604 [ 1562941 ] {} <Fatal> BaseDaemon: 12. src/Server/TCPHandler.cpp:732: DB::TCPHandler::runImpl() @ 0x000000001cdcc77a
2025.07.04 17:40:03.155756 [ 1562941 ] {} <Fatal> BaseDaemon: 13. src/Server/TCPHandler.cpp:2730: DB::TCPHandler::run() @ 0x000000001cde5b64
2025.07.04 17:40:03.160483 [ 1562941 ] {} <Fatal> BaseDaemon: 14. base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x0000000024c901a7
2025.07.04 17:40:03.165630 [ 1562941 ] {} <Fatal> BaseDaemon: 15. base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000024c906a5
2025.07.04 17:40:03.170515 [ 1562941 ] {} <Fatal> BaseDaemon: 16. base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000024c38c7f
2025.07.04 17:40:03.175037 [ 1562941 ] {} <Fatal> BaseDaemon: 17. base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000024c36811
2025.07.04 17:40:03.175074 [ 1562941 ] {} <Fatal> BaseDaemon: 18. start_thread @ 0x00000000000a2ef1
2025.07.04 17:40:03.175106 [ 1562941 ] {} <Fatal> BaseDaemon: 19. __clone3 @ 0x000000000013445c
2025.07.04 17:40:03.373122 [ 1562941 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: C617E8D6CC0730D186C851FD1ACA6650)
2025.07.04 17:40:03.381602 [ 1562941 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2025.07.04 17:40:03.381770 [ 1562941 ] {} <Fatal> BaseDaemon: Changed settings: s3_truncate_on_insert = true, allow_reorder_prewhere_conditions = true, allow_suspicious_low_cardinality_types = true, allow_suspicious_fixed_string_types = true, allow_suspicious_indices = true, allow_suspicious_ttl_expressions = true, allow_suspicious_variant_types = true, allow_suspicious_primary_key = true, allow_suspicious_types_in_group_by = true, allow_suspicious_types_in_order_by = true, allow_not_comparable_types_in_order_by = true, allow_not_comparable_types_in_comparison_functions = true, allow_nonconst_timezone_arguments = true, allow_experimental_time_time64_type = true, allow_nondeterministic_optimize_skip_unused_shards = true, allow_distributed_ddl = true, allow_suspicious_codecs = true, enable_zstd_qat_codec = true, enable_deflate_qpl_codec = true, max_execution_time = 120., allow_custom_error_code_in_throwif = true, allow_ddl = true, allow_introspection_functions = true, allow_execute_multiif_columnar = true, allow_drop_detached = true, allow_materialized_view_with_bad_select = true, allow_settings_after_format_in_insert = true, allow_nondeterministic_mutations = true, allow_non_metadata_alters = true, allow_experimental_kafka_offsets_storage_in_keeper = true, engine_file_truncate_on_insert = true, allow_experimental_correlated_subqueries = true, async_insert = true, allow_unrestricted_reads_from_keeper = true, allow_deprecated_database_ordinary = true, allow_deprecated_syntax_for_merge_tree = true, keeper_max_retries = 15, allow_get_client_http_header = true, allow_create_index_without_type = true, allow_named_collection_override_by_default = true, allow_deprecated_error_prone_window_functions = true, allow_deprecated_snowflake_conversion_functions = true, allow_experimental_analyzer = true, allow_experimental_variant_type = true, allow_experimental_dynamic_type = true, allow_experimental_json_type = true, allow_archive_path_syntax = true, allow_experimental_materialized_postgresql_table = true, allow_experimental_funnel_functions = true, allow_experimental_nlp_functions = true, allow_experimental_hash_functions = true, allow_experimental_object_type = true, allow_experimental_time_series_table = true, allow_experimental_vector_similarity_index = true, allow_experimental_codecs = true, allow_experimental_join_right_table_sorting = true, allow_experimental_statistics = true, allow_experimental_inverted_index = true, allow_experimental_full_text_index = true, allow_experimental_join_condition = true, allow_experimental_live_view = true, allow_experimental_window_view = true, allow_experimental_database_materialized_postgresql = true, allow_experimental_bfloat16_type = true, allow_experimental_shared_set_join = true, type_json_skip_duplicated_paths = true, input_format_parquet_allow_geoparquet_parser = true
```

### PR DESCRIPTION
**Pull request by Algunenano**
### Changelog category (leave one):
- Critical Bug Fix (crash, data loss, RBAC) or LOGICAL_ERROR

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix crash when calculating the size of a block with empty columns

https://github.com/ClickHouse/ClickHouse/pull/80972/commits/63c3fc9feb55db03a0019d71af65a67259472643 changed async insert to use `squashing.getHeader().cloneWithoutColumns()` to clone a Block when the squash chunk is empty. The problem is that the function `Block::bytes()` (or `allocatedBytes`) does not support having empty columns internally as others do (`rows` for example).

One possible solution would be to change the cloning and use `cloneEmpty` instead, but long term it makes sense to change Block instead as there are other places using `cloneWithoutColumns` and more might decide to use it in the future.

Closes https://github.com/ClickHouse/ClickHouse/issues/83244

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: tests/queries/0_stateless/03561_async_insert_crash.sh [hunk 1]
```diff
@@ -0,0 +1,16 @@
+#!/usr/bin/env bash
+
+CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+# shellcheck source=../shell_config.sh
+. "$CUR_DIR"/../shell_config.sh
+
+FILE="${USER_FILES_PATH}/03561_async_insert.data"
```
Comment (divanik) [inline tests/queries/0_stateless/03561_async_insert_crash.sh]: JAS: Can we add some randomisation while name generating?

**Review by divanik — APPROVED** [review]

**Comment by nikitamikhaylov** [comment]
Build (fuzzers): https://github.com/ClickHouse/ClickHouse/issues/83272
