### PR TITLE
Fix compatibility of some aggregate function states with String argument

### LINKED ISSUE #86915: `approx_top_sum` state format changed between 25.7 and 25.8 - null bytes appear in finalized strings
### Company or project name

_No response_

### Describe the unexpected behaviour

When finalizing `approx_top_sum` aggregate states created in 25.7 on ClickHouse 25.8, the resulting strings contain trailing \0 characters.
If the same states are created in 25.8, the output looks correct (no nulls).

This suggests the aggregate state serialization format changed between 25.7 and 25.8.
It breaks cross-version compatibility when persisting aggregate states (e.g. via hex(...State())).

### Which ClickHouse versions are affected?

25.8

### How to reproduce

https://fiddle.clickhouse.com/eba276cc-e63e-4fba-8cf8-3182ba2ad2d8

State is generated with 25.7 and then finalize aggregation used in 25.8

### Error message and/or stacktrace

_No response_

### Additional context

Same with 
- approx_top_k
- groupArray
- groupArrayLast
- groupUniqArray
- topK
- topKWeighted

### PR DESCRIPTION
**Pull request by Avogar**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix compatibility of some aggregate function states with String argument.

Closes https://github.com/ClickHouse/ClickHouse/issues/86915

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/Columns/IColumn.h [hunk 1]
```diff
@@ -272,6 +272,16 @@ class IColumn : public COW<IColumn>
       */
     virtual StringRef serializeValueIntoArena(size_t /* n */, Arena & /* arena */, char const *& /* begin */) const;
 
+    /// The same as serializeValueIntoArena but is used to store values inside aggregation states.
+    /// It's used in generic implementation of some aggregate functions.
+    /// serializeValueIntoArena is used for in-memory value representations, so it's implementation can be changed.
+    /// This method must respect compatibility with older versions because aggregation states may be serialized/deserialized
+    /// by servers with different versions.
+    virtual StringRef serializeAggregationStateValueIntoArena(size_t n, Arena & arena, char const *& begin) const
```
Comment (antaljanosbenjamin) [inline src/Columns/IColumn.h:280]: I see that all the columns that override `serializeValueIntoArena` also override `serializeAggregationStateValueIntoArena`, but `ColumnDynamic` doesn't. As  far as I see, that is not a problem, because `ColumnDynamic` doesn't call `serializeValueIntoArena`, but serializes the data through other means. Right?

**Review by antaljanosbenjamin — APPROVED** [review]

File: src/Columns/IColumn.h (hunk 1 above)
Comment (Avogar) [reply src/Columns/IColumn.h:280]: > As far as I see, that is not a problem, because ColumnDynamic doesn't call serializeValueIntoArena, but serializes the data through other means. Right?

Yes, that's right.
