### PR TITLE
Fix toLowCardinality type cast error with nullable columns

### LINKED ISSUE #89412: Logical error: 'Bad cast from type DB::ColumnNullable to DB::ColumnLowCardinality'
### Describe the bug

Happens since v25.7

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/75d1b16f-750c-4ca1-8e6f-838356a6ea0d

### Error message and/or stacktrace

Stack trace:
```
<Fatal> : Logical error: 'Bad cast from type DB::ColumnNullable to DB::ColumnLowCardinality'.
<Fatal> : Stack trace (when copying this message, always include the lines below):

0. contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x0000000024aee6b2
1. src/Common/Exception.cpp:129: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015075fe9
2. src/Common/Exception.h:123: DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000d61394e
3. src/Common/Exception.h:58: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000d613351
4. src/Common/Exception.h:141: DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000d6116b6
5. src/Common/typeid_cast.h:31: T typeid_cast<DB::ColumnLowCardinality&, DB::IColumn>(DB::IColumn&) @ 0x000000001395d25b
6. src/Functions/toLowCardinality.cpp:44: DB::(anonymous namespace)::FunctionToLowCardinality::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000001395ce9f
7. src/Functions/IFunctionAdaptors.cpp:10: DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x0000000018a9eb7a
8. src/Functions/IFunction.cpp:353: DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000018a982fc
9. src/Functions/IFunction.cpp:430: DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000018a9969b
10. src/Functions/IFunction.cpp:565: DB::IExecutableFunction::executeWithoutReplicatedColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000018a9aa82
11. src/Functions/IFunction.cpp:474: DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000018a9a51a
12. src/Functions/IFunction.cpp:580: DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000018a9ae99
13. src/Storages/MergeTree/KeyCondition.cpp:1053: DB::applyFunctionChainToColumn(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::shared_ptr<DB::IDataType const> const&, std::vector<std::shared_ptr<DB::IFunctionBase const>, std::allocator<std::shared_ptr<DB::IFunctionBase const>>> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, std::shared_ptr<DB::IDataType const>&) @ 0x000000001e319038
14. src/Storages/MergeTree/KeyCondition.cpp:1203: DB::KeyCondition::canConstantBeWrappedByFunctions(DB::RPNBuilderTreeNode const&, DB::KeyCondition::BuildInfo const&, unsigned long&, std::shared_ptr<DB::IDataType const>&, DB::Field&, std::shared_ptr<DB::IDataType const>&) @ 0x000000001e31b37d
15. src/Storages/MergeTree/KeyCondition.cpp:2124: DB::KeyCondition::extractAtomFromTree(DB::RPNBuilderTreeNode const&, DB::KeyCondition::BuildInfo const&, DB::KeyCondition::RPNElement&) @ 0x000000001e320256
16. contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001e6e3000
17. src/Storages/MergeTree/RPNBuilder.cpp:490: DB::RPNBuilder<DB::KeyCondition::RPNElement>::RPNBuilder(DB::ActionsDAG::Node const*, std::shared_ptr<DB::Context const>, std::function<bool (DB::RPNBuilderTreeNode const&, DB::KeyCondition::RPNElement&)> const&) @ 0x000000001e6e2c64
18. src/Storages/MergeTree/KeyCondition.cpp:893: DB::KeyCondition::KeyCondition(DB::ActionsDAGWithInversionPushDown const&, std::shared_ptr<DB::Context const>, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::ExpressionActions> const&, bool) @ 0x000000001e3175a3
19. src/Storages/MergeTree/PartitionPruner.cpp:9: DB::PartitionPruner::PartitionPruner(std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::ActionsDAGWithInversionPushDown const&, std::shared_ptr<DB::Context const>, bool) @ 0x000000001e6d9487
20. contrib/llvm-project/libcxx/include/__memory/construct_at.h:41: DB::buildIndexes(std::optional<DB::ReadFromMergeTree::Indexes>&, DB::ActionsDAG const*, DB::MergeTreeData const&, DB::RangesInDataParts const&, std::optional<DB::VectorSearchParameters> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x000000001f18ba75
21. src/Processors/QueryPlan/ReadFromMergeTree.cpp:1983: DB::ReadFromMergeTree::applyFilters(DB::ActionDAGNodes) @ 0x000000001f18b4d7
22. src/Processors/QueryPlan/SourceStepWithFilter.h:60: DB::SourceStepWithFilterBase::applyFilters() @ 0x000000001f236a9f
23. src/Processors/QueryPlan/Optimizations/optimizePrimaryKeyConditionAndLimit.cpp:49: DB::QueryPlanOptimizations::optimizePrimaryKeyConditionAndLimit(std::vector<DB::QueryPlanOptimizations::Frame, std::allocator<DB::QueryPlanOptimizations::Frame>> const&) @ 0x000000001f23685d
24. src/Processors/QueryPlan/Optimizations/optimizeTree.cpp:182: DB::QueryPlanOptimizations::optimizeTreeSecondPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&, DB::QueryPlan&) @ 0x000000001f233f39
25. src/Processors/QueryPlan/QueryPlan.cpp:506: DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001f14bf5f
26. src/Processors/QueryPlan/QueryPlan.cpp:180: DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&, bool) @ 0x000000001f14b800
27. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:289: DB::InterpreterSelectQueryAnalyzer::buildQueryPipeline() @ 0x000000001ae5bd65
28. src/Interpreters/InterpreterSelectQueryAnalyzer.cpp:256: DB::InterpreterSelectQueryAnalyzer::execute() @ 0x000000001ae5ba9c
29. src/Interpreters/MutationsInterpreter.cpp:231: DB::isStorageTouchedByMutations(std::shared_ptr<DB::IMergeTreeDataPart const>, std::shared_ptr<DB::MergeTreeData::IMutationsSnapshot const>, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::vector<DB::MutationCommand, std::allocator<DB::MutationCommand>> const&, std::shared_ptr<DB::Context const>, std::function<void (DB::Progress const&)>) @ 0x000000001aeb06de
30. src/Storages/MergeTree/MutateTask.cpp:2423: DB::MutateTask::prepare() @ 0x000000001e683b13
31. src/Storages/MergeTree/MutateTask.cpp:2254: DB::MutateTask::execute() @ 0x000000001e682a31
```

### PR DESCRIPTION
**Pull request by xiaohuanlin**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix type-casting errors when using `LowCardinality` columns in partition keys. Closes #89412.

### Details

Fixes #89412

When `toLowCardinality` is applied to nullable columns in partition keys or WHERE clauses, the `KeyCondition` optimization strips the `LowCardinality` wrapper from the result type via `removeLowCardinality()`. This causes `toLowCardinality::executeImpl` to receive a non-LowCardinality type (e.g., `Nullable(String)`) and attempt to cast the created column (`ColumnNullable`) to `ColumnLowCardinality`, resulting in a type cast error.

**Fix**: Check if `res_type` is already `LowCardinality` before creating the column. If not, wrap it with `DataTypeLowCardinality` to ensure the created column has the correct type.

### CODE REVIEW

**Comment by nihalzp** [comment]
https://fiddle.clickhouse.com/f94b15c7-8476-4301-b79b-f4a541e2ee29

The tests in this PR seems to be working in the latest version with no error. Could you also add the exact query in the issue https://github.com/ClickHouse/ClickHouse/issues/89412 to the tests?

File: tests/queries/0_stateless/03727_tolowcardinality_nullable_cast.sql [hunk 1]
```diff
@@ -0,0 +1,48 @@
+-- Tags: no-fasttest
```
Comment (nihalzp) [inline tests/queries/0_stateless/03727_tolowcardinality_nullable_cast.sql]: Why no fast test? Fast tests are quite useful in knowing quickly if something breaks in the future.

Comment (xiaohuanlin) [reply tests/queries/0_stateless/03727_tolowcardinality_nullable_cast.sql]: Removed the tag

File: src/Functions/toLowCardinality.cpp [hunk 2]
```diff
@@ -40,7 +40,12 @@ class FunctionToLowCardinality: public IFunction
         if (arg.type->lowCardinality())
             return arg.column;
 
-        auto column = res_type->createColumn();
+        /// res_type may have LowCardinality stripped by KeyCondition optimization
+        DataTypePtr low_cardinality_type = res_type->lowCardinality()
+            ? res_type
+            : std::make_shared<DataTypeLowCardinality>(res_type);
+
+        auto column = low_cardinality_type->createColumn();
```
Comment (nihalzp) [inline src/Functions/toLowCardinality.cpp]: Ideally `res_type` of a function should stay fixed and should not be needed to be changed in `executeImpl`. This indicates the problem is elsewhere because `toLowCardinality` function should have been called with `res_type` that already is `LowCardinality`.

Let's do this:
Here,
https://github.com/ClickHouse/ClickHouse/blob/516a6ed6f8bd8c5f6eed3a10e9037580b2fb6152/src/Storages/MergeTree/KeyCondition.cpp#L1052

We should not remove `LowCardinality` from `func->getResultType()`. 
Let's change to:

```cpp
result_type = func->getResultType();
```

Then, `toLowCardinality` function should get the correct `res_type`. To make sure, this does not happen in the future. Could we please do a check inside `executeImpl` of `FunctionToLowCardinality` to make sure `res_type` is `LowCardinality` and throw `LOGICAL_ERROR` otherwise?

**Comment by nihalzp** [comment]
The style check is complaining about missing error code.

```txt
ErrorCodes::LOGICAL_ERROR is used in file /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/src/Functions/toLowCardinality.cpp but not defined
```

We can resolve it by adding this at the top:
```cpp
namespace ErrorCodes
{
    extern const int LOGICAL_ERROR;
}
```

**Review by nihalzp — APPROVED** [review]
