### PR TITLE
Fix the CSV serialization/deserialization bug for Time

### LINKED ISSUE #82407: Logical Error: Invalid number of rows in Chunk
### Describe the bug

This may be related to the new Time type, because I can't reproduce it if I replace the time column with another type.

### How to reproduce

Run Fiddle: https://fiddle.clickhouse.com/7a4b9262-cd41-4175-a315-5f6c794f5fc9

### Error message and/or stacktrace

Stack trace:

```
Logical error: 'Invalid number of rows in Chunk  Int32(size = 3) Int32(size = 2) Int128(size = 3) Int32(size = 3) column Int32 at position 1: expected 3, got 2'.
Stack trace (when copying this message, always include the lines below):

0.  contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000001e868592
1.  src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000012df6a86
2.  src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000bed64ac
3.  src/Common/Exception.h:137: DB::Exception::Exception<String, String, unsigned long&, unsigned long&, unsigned long>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type>, String&&, String&&, unsigned long&, unsigned long&, unsigned long&&) @ 0x000000001a529544
4.  src/Processors/Chunk.cpp:65: DB::Chunk::checkNumRowsIsConsistent() @ 0x000000001a527687
5.  src/Processors/Chunk.cpp:35: DB::Chunk::Chunk(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>, unsigned long) @ 0x000000001a52776f
6.  src/Processors/Formats/IRowInputFormat.cpp:262: DB::IRowInputFormat::read() @ 0x000000001a5c15f5
7.  src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x000000001a55c376
8.  src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x000000001a536d85
9.  src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x000000001a536a72
10.  src/Processors/Formats/Impl/ParallelParsingInputFormat.h:180: DB::ParallelParsingInputFormat::InternalParser::getChunk() @ 0x000000001a6ccf3c
11.  src/Processors/Formats/Impl/ParallelParsingInputFormat.cpp:95: DB::ParallelParsingInputFormat::parserThreadFunction(std::shared_ptr<DB::ThreadGroup>, unsigned long) @ 0x000000001a6cbb50
12.  contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012f2ff73
13.  contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x0000000012f3609d
14.  contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x0000000012f2d586
15.  contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x0000000012f33b60
16. start_thread @ 0x00000000000a2ef1
17. __GI___clone3 @ 0x000000000013445c
```

### PR DESCRIPTION
**Pull request by yariks5s**
Closes https://github.com/ClickHouse/ClickHouse/issues/82407

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Fix a bug when incorrect type order during CSV deserialization led to the `LOGICAL_ERROR`

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

### CODE REVIEW

File: src/DataTypes/Serializations/SerializationTime.cpp [hunk 1]
```diff
@@ -113,10 +114,14 @@ void SerializationTime::deserializeTextQuoted(IColumn & column, ReadBuffer & ist
 bool SerializationTime::tryDeserializeTextQuoted(IColumn & column, ReadBuffer & istr, const FormatSettings & /*settings*/) const
 {
     time_t x = 0;
+    const char * begin = istr.position();
     if (checkChar('\'', istr)) /// Cases: '18:36:48' or '123808'
     {
         if (!tryReadTimeText(x, istr) || !checkChar('\'', istr))
+        {
+            istr.position() = const_cast<char *>(begin); // rollback on failure
```
Comment (alexey-milovidov) [inline src/DataTypes/Serializations/SerializationTime.cpp]: This looks incorrect, as the buffer could have changed.

**Review by alexey-milovidov — DISMISSED** [review]

File: src/DataTypes/Serializations/SerializationTime.cpp [hunk 2]
```diff
@@ -179,55 +184,33 @@ void SerializationTime::serializeTextCSV(const IColumn & column, size_t row_num,
...
-        String time_str;
-        readCSVString(time_str, istr, settings.csv);
-        ReadBufferFromString buf(time_str);
-        readTimeText(x, buf);
-        if (!buf.eof())
-            throwUnexpectedDataAfterParsedValue(column, istr, settings, "Time");
-    }
+    time_t x = 0;
+    ReadBufferFromString buf(time_str);
+    // Parse inside an isolated buffer, and fail gracefully if it doesn't fit
```
Comment (alexey-milovidov) [inline src/DataTypes/Serializations/SerializationTime.cpp]: Why do we need this change?

**Comment by alexey-milovidov** [comment]
@yariks5s, good news, the error was not anywhere around your code for the Time data type, and these changes are unneeded.

The error was introduced in this PR: https://github.com/ClickHouse/ClickHouse/pull/51716, @Avogar 
It was impossible to implement that feature correctly, and it does not make sense in general.

I recommend @Avogar deprecating that old mis-feature.

**Comment by yariks5s** [comment]
I think we can close this PR now as it will not fix the problem completely

**Comment by Avogar** [comment]
The problem not in the https://github.com/ClickHouse/ClickHouse/pull/51716, the problem is here:
https://github.com/ClickHouse/ClickHouse/blob/d8595d74935a445fc19915c78805ecf9469cf01f/src/DataTypes/Serializations/SerializationTime.cpp#L202

Function `throwUnexpectedDataAfterParsedValue` calls `column->popBack(1)`, but here in `SerializationTime::deserializeTextCSV` we don't add value to the column at the time we call this function. So we delete previous row and end up with 1 row less in the chunk.

Also I noticed that `input_format_allow_errors_num` doesn't work in this case because `UNEXPECTED_DATA_AFTER_PARSED_VALUE` is not listed as parsing error here:
https://github.com/ClickHouse/ClickHouse/blob/d8595d74935a445fc19915c78805ecf9469cf01f/src/Processors/Formats/IRowInputFormat.cpp#L36-L56

File: tests/queries/0_stateless/03365_csv_time_deserialization_bug.sql [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+SELECT c3, c2, c1, c0 FROM t0;
+
+TRUNCATE TABLE t0;
+
+-- Read it back from server-side using the file() table function
+-- (NOT FROM INFILE, which is client-side)
+INSERT INTO t0 (c0, c1, c2, c3)
+SELECT c0, c1, c2, c3
+FROM file('table_time_bug.csv', 'CSV',
+          'c0 Int, c1 Time, c2 Int128, c3 Int');
```
Comment (Avogar) [inline tests/queries/0_stateless/03365_csv_time_deserialization_bug.sql]:
```suggestion
INSERT INTO FUNCTION file(currentDatabase() || '_table_time_bug.csv', 'CSV',
    'c3 Int, c2 Int128, c1 Time, c0 Int')
SELECT c3, c2, c1, c0 FROM t0;

TRUNCATE TABLE t0;

-- Read it back from server-side using the file() table function
-- (NOT FROM INFILE, which is client-side)
INSERT INTO t0 (c0, c1, c2, c3)
SELECT c0, c1, c2, c3
FROM file(currentDatabase() || '_table_time_bug.csv', 'CSV',
          'c0 Int, c1 Time, c2 Int128, c3 Int');
```

This test might be running with itself in parallel, always better to have unique file names

Comment (yariks5s) [reply tests/queries/0_stateless/03365_csv_time_deserialization_bug.sql]: agree

**Review by Avogar — APPROVED** [review]

**Comment by yariks5s** [comment]
[PR / Integration tests (arm_binary, distributed plan, 2/4) (pull_request)](https://github.com/ClickHouse/ClickHouse/actions/runs/18133357990/job/51611237547?pr=87622) - https://github.com/ClickHouse/ClickHouse/issues/87995

[Integration tests (arm_binary, distributed plan, 3/4)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87622&sha=2ffa20fb2f4bbf98a71fda1cf6a7200bfa10e794&name_0=PR&name_1=Integration+tests+%28arm_binary%2C+distributed+plan%2C+3%2F4%29) - https://github.com/ClickHouse/ClickHouse/issues/71049, https://github.com/ClickHouse/ClickHouse/issues/87877

**Comment by clickgapai** [comment]
Hi @yariks5s @Avogar — while reviewing this PR I found the following:

- **Bug (P2):** `SerializationTime64::deserializeTextCSV` missing `!buf.eof()` check silently accepts trailing garbage in unquoted CSV fields — https://github.com/ClickHouse/ClickHouse/issues/102490

Happy to discuss — close anything that's wrong or already addressed.
