### PR TITLE
Test for input_format_allow_errors_num in CSV

### LINKED ISSUE #10668: input_format_allow_errors_num not working
**Describe the bug**
`input_format_allow_errors_num` and `input_format_allow_errors_ratio` not working as expected.

**How to reproduce**
* Version
20.3.8.53
* Interface
clickhouse-client
* Table
```
CREATE TABLE nums2 (
    num1 Int64,
    num2 Int64
) ENGINE = MergeTree() ORDER BY num1
```

* Data
nums.csv
```
1,0
2,0
3,0
4,0
5,0
6,0
7,0
8,0
9,0
10,0
11,0
12,AAAAAAA
13,0
14,0
15,0
16,0
17,0
18,0
19,0
20,0
```

**Command**
WORKS(using `-n 10` to only get first 10 lines):
```
$ head -n 10 /nums/nums.csv | tr '\r\n' '\n' | clickhouse-client -h clickhouse -q "INSERT INTO nums2(num1,num2) FORMAT CSV" --format_csv_delimiter="," --compression 0 --format_csv_allow_double_quotes=0 --format_csv_allow_single_quotes=0 --input_format_allow_errors_num=10 --input_format_allow_errors_ratio=0.1
```

DOESN'T WORK(using `-n 15` to include 12th line, `12,AAAAAAA`):
```
$ head -n 15 /nums/nums.csv | tr '\r\n' '\n' | clickhouse-client -h clickhouse -q "INSERT INTO nums2(num1,num2) FORMAT CSV" --format_csv_delimiter="," --compression 0 --format_csv_allow_double_quotes=0 --format_csv_allow_single_quotes=0 --input_format_allow_errors_num=10 --input_format_allow_errors_ratio=0.1
Code: 117, e.displayText() = DB::Exception: Expected end of line, Stack trace (when copying this message, always include the lines below):
```

Gets this error:
```
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10542450 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4272d in /usr/bin/clickhouse
2. ? @ 0xdc5f2ad in /usr/bin/clickhouse
3. ? @ 0xdc57971 in /usr/bin/clickhouse
4. DB::CSVRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xdc5da39 in /usr/bin/clickhouse
5. DB::IRowInputFormat::generate() @ 0xdc2b8d1 in /usr/bin/clickhouse
6. DB::ISource::work() @ 0xdba8ceb in /usr/bin/clickhouse
7. DB::InputStreamFromInputFormat::readImpl() @ 0xdb5986d in /usr/bin/clickhouse
8. DB::IBlockInputStream::read() @ 0xce5701f in /usr/bin/clickhouse
9. DB::ParallelParsingBlockInputStream::parserThreadFunction(unsigned long) @ 0xdb5e462 in /usr/bin/clickhouse
10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8f6792b in /usr/bin/clickhouse
11. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const @ 0x8f68608 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f667eb in /usr/bin/clickhouse
13. ? @ 0x8f64c33 in /usr/bin/clickhouse
14. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
15. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.3.8.53 (official build))
Code: 117. DB::Exception: Expected end of line
```

### PR DESCRIPTION
**Pull request by filimonov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

Changelog category (leave one):
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Test for a fixed issue #10668, related to input_format_allow_errors_num in CSV

Detailed description / Documentation draft:
Closes #10668
The issue itself was fixed earlier, most probably by #10418

### CODE REVIEW

File: tests/queries/0_stateless/01355_CSV_input_format_allow_errors.sh [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+expected_error_message='Already have 2 errors out of 7 rows'
+cat "$STD_ERROR_CAPTURED" | grep -q "$expected_error_message" && echo "OK: stderr contains a message '$expected_error_message'" || echo "FAILED: Error message is wrong"
+
+echo '******************'
+echo 'attempt to parse with input_format_allow_errors_num=2'
+cat "$SAMPLE_FILE" | clickhouse-local --input-format=CSV --structure='num1 Int64, num2 Int64' --query='SELECT * from table' --input_format_allow_errors_num=2 2>"$STD_ERROR_CAPTURED"
+echo "Return code: $?"
+cat "$STD_ERROR_CAPTURED"
+
+rm "$STD_ERROR_CAPTURED" "$SAMPLE_FILE"
```
Comment (filimonov) [inline tests/queries/0_stateless/01355_CSV_input_format_allow_errors.sh:45]: new line missing, i can add, but don't want to rerun CI one more time for that. So may be just after/before merge

File: tests/queries/0_stateless/01355_CSV_input_format_allow_errors.reference [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+attempt to parse with input_format_allow_errors_ratio=0.1
+Return code: 117
+OK: stderr contains a message 'Already have 1 errors out of 5 rows, which is 0.2'
+******************
+attempt to parse with input_format_allow_errors_ratio=0.3
+0	0
+1	0
+2	0
+3	0
+4	0
```
Comment (tavplubix) [inline tests/queries/0_stateless/01355_CSV_input_format_allow_errors.reference:23]: FYI ill-formatted rows should be skipped, but it does not happen in this case because of [another issue](https://github.com/ClickHouse/ClickHouse/issues/7943#issuecomment-559557022)

**Review by tavplubix — APPROVED** [review]
